### ISSUE TITLE
Add retirement date of 2021 to Australian F/A-18A/B Aircraft #3912 #3913

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#10]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3912 3913

### Summary of Changes

All A and B variants retired from RAAF in 2021

### Sources

https://www.scramble.nl/military-news/australia-says-goodbye-to-classic-hornet
https://australianaviation.com.au/2021/11/classic-hornet-retired-after-over-30-years-of-service/

**Comment by Jkryos** [comment]
Fixed DB3K 493.
