### ISSUE TITLE
Add GBU-49 Loadout out to USMC F-35B from 2020

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#100]
### DB Selector

DB3K

### User(s)

F-35B #534 #3496 #4701

### Weapons Carried

2 Amraam
2 GBU-49/B Paveway II

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Similar to other Mk.82 loadouts. this was the first loadout capable of hitting moving targets. 

### Sources

https://www.dvidshub.net/image/6156069/31st-meu-unleashes-f-35-fighter-aircraft-armed-with-gbu-49-bombs-philippine-sea
https://www.navy.mil/Resources/Photo-Gallery/igphoto/2002858701/
https://media.defense.gov/2021/Sep/21/2002858701/1088/820/0/210912-M-MS099-138.JPG
https://twitter.com/thef35jpo/status/1440654083732344836

**Comment by Jkryos** [comment]
Added DB3K 493.
