### ISSUE TITLE
Yugoslavia - PLAB-200 M71 Incendiary Bomb

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1001]
### DB Selector

DB3K

### DBID to Copy

1871 Mk77 Mod1

### Hypothetical

No

### Name

PLAB-200 M71 Incendiary Bomb

### Country

Yugoslavia

### Service

Airforce

### Sensors

-

### Mounts

-

### Loadout Options

-

### Other Changes

- Napalm 200kg

### Sources

used by G-4 Super Galeb, I'm going to make a seperate loadout request:
Weapons (post by Gavrinem):
http://www.paluba.info/smf/index.php?topic=20.msg477382#msg477382

https://imgur.com/gaWFDt1

**Comment by PygmalionOfCyprus** [comment]
Added 494.
