### ISSUE TITLE
Yugoslavia - FAB-575 M91 FAE

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1002]
### DB Selector

DB3K

### DBID to Copy

3459 ODAB-500shL FAE

### Hypothetical

No

### Name

FAB-575 M91 [Retarded]

### Country

Yugoslavia

### Service

Airforce

### In Commission

1991

### Other Changes

This was a somewhat secret project, the bigger brother of the FAB-275 M91 there isn't much information except for it's weight of 575kg and three pictures. The name FAB was misleading on purpose, it was a fuel air weapon. It is equiped with a M91 laser proximity fuse and a parachute. The special fuel is dispersed by the first charge. There are three openings in rear section which allow secondary charges to be ejected into the fuel cloud and ignite it.

### Sources

https://imgur.com/3NjaOvT
https://imgur.com/o8wQG8v
https://imgur.com/9WPc1MN
M91 fuze:
https://imgur.com/FixZFZx
Sadly only this picture for the FAB-575:
https://imgur.com/mbePeE4

Edit: I found 2 more pictures... they are pretty massive to say the least...
https://www.politika.rs/thumbs//upload/PhotoGallery/Images/2022_03///1014z570_2-623466f71bb10.jpg?text=Slide-1
https://www.mycity-military.com/slika.php?slika=133254_118258535_KVB-4%20c.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 494.
