### ISSUE TITLE
Yugoslavia - FAB-275 M91 FAE

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1003]
### DB Selector

DB3K

### Baseline

3459 Odab-500Shl FAE

### Hypothetical

No

### Name

FAB-275 M91 FAE [Retarded]

### Length (m)

2.6

### Width/Span (m)

0.6

### Diameter (m)

0.42

### Weight (kg)

275

### Range (nm)

1

### Launch Altitude / Depth (ft)

650ft AGL - 65000 ft ASL

### Warhead

275kg FAE

### Targets

Surface Vessel, Land Structure - Soft, Mobile Target - Soft, Mobile Target - Personnel

### CEP (m)

50

### Sensors

-

### Weapon Codes

Is Retarded Munition

### Comments

The name FAB was misleading on purpose, it was a fuel air weapon. It is equiped with a M91 laser proximity fuse and a parachute. The special fuel is dispersed by the first charge. There are three openings in the rear section which allow secondary charges to be ejected into the fuel cloud and ignite it.

### Sources

https://imgur.com/3NjaOvT
https://imgur.com/o8wQG8v
https://imgur.com/9WPc1MN
https://imgur.com/KQp7DiA
M91 fuze:
https://imgur.com/FixZFZx

**Comment by PygmalionOfCyprus** [comment]
Added 494.
