### ISSUE TITLE
AN/APG-56 Range is to great

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1004]
### DB Selector

CWDB

### Affected DBID(s)

Sensor 1159

### Summary of Changes

AN/APG-56 is a Fire Control Radar (similar to AN/APG-30); used in F-86 (only Australian models with A-4 gun sight). CUrrent in the DB it is an air and surface search radar with a 20nm range.

### Sources

http://www.designation-systems.net/usmilav/jetds/an-apg.html

https://en.wikipedia.org/wiki/List_of_radars#AN/APG_Series

**Comment by Jkryos** [comment]
Updated CWDB 494.
