### ISSUE TITLE
Correction to Sapfir-21 aka JAY BIRD aka RP-22M

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1006]
### DB Selector

Both

### Affected DBID(s)

Sensor_189 (WDB); Sensor_887 (DB3k)

### Summary of Changes

1) Nomenclature correction: Database names the radar the Sapfir-**22**.  According to Jane's, it is a Sapfir-**21** (see attached).  Mladenov concurs with this nomenclature.
2) Database identifies this as a  "I" band radar (NATO).  Jane's lists the frequency range as 12.88-13.2 GHz, making it a "J" band. (see attached
![2022-04-27_14-28-31](https://user-images.githubusercontent.com/99547401/165642471-46fa4749-b2a0-4c06-83d6-1c14d82a479c.jpg)
)

### Sources

Mladenov, Alexander. Soviet Cold War Fighters. Fonthill Media, 2017, location 3123  (Kindle ed.) ; Jane's Radar and Electronic Warfare Systems, "Sapfir Series Radars," 19 October 2000;  Mladenov, Alexander, Mikoyan-Gurevich MiG-21 (Air Vanguard 14)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. (Change also applied to the Ms; I did that w/ the other radar update you posted but forgot to mention it.)
