### ISSUE TITLE
Yugoslavia - FAB-250 M79 [Retarded]

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1008]
### DB Selector

DB3K

### Baseline

1502 FAB-250M-62

### Hypothetical

No

### Name

FAB-250 M79 [Retarded]

### Length (m)

2.2

### Width/Span (m)

0.46

### Diameter (m)

0.32

### Weight (kg)

259

### Range (nm)

1

### Launch Altitude / Depth (ft)

180ft AGL - 65000ft ASL

### Warhead

FAB-250 M79 [105kg HE]

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

50

### Sensors

-

### Weapon Codes

Is Retarded Munition

### Sources

page 29,30:
https://kupdf.net/download/catalogue-bdquo-kru-scaron-ik-rdquo_5af94e8fe2b6f5c80d882868_pdf
https://imgur.com/rG4vHXv

**Comment by PygmalionOfCyprus** [comment]
Added 494.
