### ISSUE TITLE
Add MLS-ER Quad Spike NLOS Launcher to Shaldag V #3418

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#101]
### DB Selector

DB3K

### Affected DBID(s)

3418

### Summary of Changes

Israeli Shaldag V seems to have a 4x NLOS mount at IOC. Back top of boat's cabin in pictures. Mount called **MLS ER**. Looks like Azerbaijan has Shaldag IV's configured his way too.  

### Sources

https://www.rafael.co.il/wp-content/uploads/2019/03/Typhoon-MLS-ER.pdf
https://twitter.com/REjercitos/status/1392735404407808000/photo/1
https://twitter.com/MaghsoudiNavid/status/1395650814832779265/photo/1
https://twitter.com/D__Mitch/status/843721594988060672/photo/1

**Comment by PygmalionOfCyprus** [comment]
Added 493. Also added the Azerbaijan CG Mk Vs with their modified fitting.
