### ISSUE TITLE
Yugoslavia - FAB-100 M80 [Retarded]

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1010]
### DB Selector

DB3K

### Baseline

705 FAB-100M-62

### Hypothetical

No

### Name

FAB-100 M80 [Retarded]

### Length (m)

1.62

### Width/Span (m)

0.23

### Diameter (m)

0.23

### Weight (kg)

132

### Range (nm)

1

### Launch Altitude / Depth (ft)

180ft AGL - 65000ft ASL

### Warhead

FAB-100 M80 [39kg HE]

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

50

### Sensors

-

### Weapon Codes

Is Retarded Munition

### Sources

page 25,26:
https://kupdf.net/download/catalogue-bdquo-kru-scaron-ik-rdquo_5af94e8fe2b6f5c80d882868_pdf
https://imgur.com/mnOSxzJ

**Comment by PygmalionOfCyprus** [comment]
Added 494.
