### ISSUE TITLE
#2805 P222 HMS Forth [River Class, Batch 2], United Kingdom, 2018 - Update

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#1011]
### DB Selector

DB3K

### Affected DBID(s)

#2805 P222 HMS Forth [River Class, Batch 2], United Kingdom, 2018

### Personel

-  Increase Crew from 30 to 45. [1], [10]

"_The vessel can accommodate a crew of 45 as well as up to 50 Royal Marines._" [1]

### Communications Equipment and Sensors

**1. Communications**

-  Add High Frequency (HF) Secure/Unsecure. [1], [10]
-  Add Very High Frequency (VHF) Unsecure. [1], [10]
-  Add  INMARSAT-B satellite communications. [1]

"_The OPV is equipped with a Rhode and Schwarz military communications suite operating in high frequency (HF)/very high frequency (VHF) and ultra-high frequency (UHF) bands, Furuno maritime VHF communications set, INMARSAT-B satellite communications and global maritime distress and safety system (GMDSS) Area A3 military communications._" [1]

**2. Sensors**

- Add Fe700 echo sounder supplied by Furuno. [1], [2]

"_The navigation suite includes a SafeMarine electronic chart display, Kelvin Hughes Nucleus navigation radar operating at I-band, Leica MXXX420/2 global positioning system, Raytheon Annschutz gyro compass, Lilley and Gillie Sesterline Mk X magnetic compass, Fe700 echo sounder supplied by Furuno, Walker 7070 log and wind system, navigational telex (NAVTEX), and weather fax._" [1]

-  Add Chess Dynamics' Sea Eagle Optronics Director. [1], [3], [4]

"_The Batch 2 vessels are fitted with Terma’s SCANTER 4100 radar system, which provides target detection and situational awareness, and Chess Dynamics’ Sea Eagle optronic director._" [1], [3], [4]

### Weapons

-  Add 2x additional 7.62mm MG (#1415 7.62mm MG Burst [20 rnds]). [1]
-  Add 2x Mk 44 Miniguns. [1], [6], [7]

"_Each Batch 2 vessel is equipped with an automated small calibre gun (ASCG) 30mm Bushmaster gun, two Mk 44 miniguns and four 7.62mm GPMGs._" [1]

The MK 44 Minigun is a version of the M134D minigun, naval version GAU-17/A. [5], [8]

"_A [United States Army Green Beret] covers his sector with a [MK 44 minigun] mounted atop a MRAP vehicle during an operation in Tagab, Afghanistan, November 2010.

The MK44 is a variant of the M134 Minigun that can be found on U.S. Army helicopters.

The MK44 was originally adapted for mounting on British Royal Navy warships to protect against small boat attacks and was later adopted by U.S. Special Operations Forces and mounted on various vehicles._" [5]

### Docking Facilities

-  Add 1x Davit (2x Very Small Dock/Davit (0-11m Long)). [1], [9]

"_The vessel carries two Halmatic Jet Pacific 22 rigid inflatable boats (RIB)._" [1]

### Sources

[1]   https://www.naval-technology.com/projects/river_class/
[2]   https://www.marinsat.com/en/product/fe700-echosounder
[3]   https://www.chess-dynamics.com/storage/resources/fceo-datasheet-1562143533.pdf
[4]   https://www.chess-dynamics.com/naval
[5]   https://www.americanspecialops.com/photos/special-forces/mk44-minigun.php
[6]   https://www.americanspecialops.com/special-ops-weapons/minigun.php
[7]   https://weaponsystems.net/system/953-M134
[8]   http://www.navweaps.com/Weapons/WNUS_30-cal_GAU17.php
[9]   http://www.hamiltonmarine.co.nz/includes/files_cms/file/JetBrief/JB%20323%20-%20Pacific%2022.pdf
[10] https://www.baesystems.com/en-uk/product/offshore-patrol-vessels - See 90m OPV datasheet

**Comment by PygmalionOfCyprus** [comment]
Fixed 494.
