### ISSUE TITLE
Yugoslavia - BR-20-57 Rocket

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1012]
### DB Selector

DB3K

### Baseline

S-5K

### Hypothetical

No

### Name

BR-20-57 57mm Rocket [HEAT+FRAG]

### Length (m)

1.2

### Width/Span (m)

0.24

### Diameter (m)

0.06

### Weight (kg)

4.5

### Range (nm)

2

### Warhead

BR-20-57 57mm Rocket, 1.8kg HEAT/FRAG [0.32 HE]

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

20

### Sensors

-

### Comments

Combined HEAT/FRAG 57mm rocket, 200mm RHA penetration vs 130mm of S-5.

### Sources

page 18:
https://kupdf.net/download/catalogue-bdquo-kru-scaron-ik-rdquo_5af94e8fe2b6f5c80d882868_pdf

**Comment by PygmalionOfCyprus** [comment]
Added 494.
