### ISSUE TITLE
Yugoslavia - BR-128 M74 Rocket

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1014]
### DB Selector

DB3K

### Hypothetical

No

### Name

BR-128 M74 128mm Rocket [HE]

### Length (m)

1.83

### Width/Span (m)

-

### Diameter (m)

0.13

### Weight (kg)

43.7

### Range (nm)

2

### Warhead

BR-128 M74 128mm Rocket, 15 kg HE [4kg HE]

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

20

### Sensors

-

### Comments

Four are carried in one rocket pod

### Sources

https://www.yugoimport.com/en/proizvodi/br-vz-128-mm-aircraft-rocket-family
http://www.vti.mod.gov.rs/cms/images/actualites_pictures/munja_130505639287040e1c8.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 494.
