### ISSUE TITLE
Hypothetcial - USN Cruiser Baseline (CGBL)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1015]
### DB Selector

DB3K

### Baseline

CG-52 Ticonderoga CG VLS

### Hypothetical

Yes

### Name

Cruiser Baseline (CGBL)

### Class

Cruiser Baseline (CGBL)

### Country

United States

### Service

Navy

### In Commission

~2000-

### Length (m)

189.0 m

### Beam (m)

21.0 m

### Draft (m)

Not Stated

### Standard Displacement (t)

Not Stated

### Full Displacement (t)

13,894 t

### Empty Displacement (t)

Not Stated

### Complement

Same as CG-52

### Max Sea State

Same as CG-52

### Primary Propulsion Type

Gas Turbine

### Propulsion

4 × General Electric LM2500 gas turbines, two shafts, 105,000 shp (78 MW)

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

30.5 knots

### Range (nm) at Speed (kt)

Not Stated

### Sensors

Same as CG-52

### Mounts

Same as CG-52

### Aircraft & Docking Facilities

Same as CG-52

### Comms/Datalinks

Same as CG-52

### Ship Codes

Prairie Masker, Helo In-Flight Refuel (HIFR) Capable

### Comments

The cruiser baseline (CGBL) was a design study for a ship that has the combat capabilities of VLS-capable Ticonderoga-class cruiser (CG-52 onwards) while designing the hull to DDG-51 (Arleigh Burke-class destroyer) standards and technology. The resulting design was considerably larger than the Ticonderoga-class design, owing to increased margins and allowances for weight and mission growth.

### Sources

https://en.wikipedia.org/wiki/Cruiser_Baseline

http://www.navalengineers.org/SiteCollectionDocuments/2008%20Proceedings%20Documents%20%28Papers%20and%20Presentations%29/ASNE%20Day%202008/paper21.pdf

https://www.navalengineers.org/Publications/Symposia-Proceedings/Proceedings2008/Pages/ASNEDay2008Proceedings

Friedman, Norman (1984). U.S. CRUISERS An Illustrated Design History. Annapolis, Maryland: Naval Institute Press.

![image](https://user-images.githubusercontent.com/99599482/165753744-b8d86dde-9ba3-4380-9702-b188137abb9f.png)

![image](https://user-images.githubusercontent.com/99599482/165754363-637e3bf8-3b2c-464b-836a-ed07be206494.png)

![image](https://user-images.githubusercontent.com/99599482/165754430-656090a5-cb7a-414b-a250-def7bc25f1e5.png)

![image](https://user-images.githubusercontent.com/99599482/165754489-a30b4e1c-e382-4a79-a9b3-66cafd814f73.png)

![image](https://user-images.githubusercontent.com/99599482/165754578-25ff05ae-6c28-4879-a5ea-1f3f8a43a79e.png)

**Comment by KushanGaming** [comment]
Done for DB495.
