### ISSUE TITLE
CSGN 9 Long Beach - Aegis Strike Cruiser Prototype Conversion 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1016]
### DB Selector

DB3K

### Baseline

CGN 9 Long Beach

### Hypothetical

Yes

### Name

CSGN 9 Long Beach

### Class

Long Beach

### Country

United States

### Service

Navy

### In Commission

~1996-

### Length (m)

216.28 m

### Beam (m)

23.29 m

### Draft (m)

6.81 m

### Standard Displacement (t)

16,292 t

### Full Displacement (t)

17,561 t

### Empty Displacement (t)

Not Stated

### Complement

454

### Max Sea State

As CGN 9

### Primary Propulsion Type

Steam

### Propulsion

 pressurized water D2G General Electric nuclear reactors, two shafts, 60,000 shp (45 MW) 2 × 2,000 kW (2,700 hp) diesel generators 6 × ship service turbo generators

### Fuel Capacity (kg)

N/A

### Flank Speed (kt)

30 knots

### Range (nm) at Speed (kt)

Unlimited (Nuclear)

### Sensors

AN/SPY-1A multi-function radar
AN/SPS-49 air search radar
AN/SPS-10F surface search radar
AN/SPS-64 navigation radar
AN/SPG-62 (x4) fire control radar
AN/SQS-53 bow-mounted sonar
AN/SLQ-32 ECM suite
AN/UYK-7 computer processing

### Mounts

2 × Mk-26 missile launchers
RIM-66 Standard and ASROC
64 missiles forward
64 missiles aft
2 × quad Mk-143 ABL launchers
BGM-109 Tomahawk (8 total)
4 × quad Mk-141 tube launchers
RGM-84 Harpoon (16 total)
1 × 8"/55 cal MCLWG (forward)
2 × Mk-15 Phalanx CIWS (amidships)
2 × triple Mark 32 SVTT
Mark 46 torpedo

### Aircraft & Docking Facilities

Facilities for 2 x SH-2F LAMPS I helicopters

### Comms/Datalinks

As CG-47

### Ship Codes

Prairie Masker, Helo In-Flight Refuel (HIFR) Capable

### Comments

Conversion of CGN-9 to a prototype strike cruiser.

### Sources

https://en.wikipedia.org/wiki/USS_Long_Beach_(CGN-9)#Decommissioning

https://en.wikipedia.org/wiki/Strike_cruiser

![image](https://user-images.githubusercontent.com/99599482/165756977-af2c0b8b-9126-4b95-b5f2-74e8c78a5257.png)

![image](https://user-images.githubusercontent.com/99599482/165757034-e7ac5ba2-9b75-4ed8-9d8d-5365e312e4d1.png)

![image](https://user-images.githubusercontent.com/99599482/165757088-85a1bd91-125a-46a2-b903-81350290a56b.png)

**Comment by KushanGaming** [comment]
Done for DB495.

**Comment by Loki1701e** [comment]
some things are wrong about this boat in the DB
