### ISSUE TITLE
Add FN-16 Manpad

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1017]
### DB Selector

DB3K

### Baseline

3075- FN-6

### Hypothetical

No

### Name

FN-16

### Length (m)

1.6m

### Width/Span (m)

.18

### Diameter (m)

.072m

### Weight (kg)

11.5kg

### Range (nm)

3.2nm

### Target Altitude / Depth (ft)

32 ft AGL to 13123.36 ft AGL

### Warhead

3k frag (likely)

### Targets

Aircraft, Helicopter, Missile

### Sensors

Standard dual spectral IR seeker #1636. 

### Weapon Codes

Anti-Air All-Aspect

### Comments

Sales literature says 90% pok but unlikely. I'd match all other MANPADS-65%

### Sources

https://en.wikipedia.org/wiki/FN-6
http://www.military-today.com/missiles/fn_6.htm
http://gielladesign.com/2006/11/0010513.pdf

**Comment by PygmalionOfCyprus** [comment]
Added 494.
