### ISSUE TITLE
Add SAM Sec (FN-16 MANPAD) for China 2008, Bangladesh 2016,Cameroon 2013

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1019]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Sec (FN-16 MANPAD)

### Facility Type

SAM

### Country

China, Bangladesh, Cameroon, Pakistan

### Service

Army

### In Commission

China 2008, Bangladesh 2016,Cameroon 2013, Pakistan 2018

### Crew

6

### Dispersion Radius (m)

40

### Sensors

IR Site

### Mounts

3 FN-16 MANPAD Mounts

### Magazines

6 FN-16 Reloads

### Comments

No pictures of PLAN until 2020. I'd adjust IOC to that.

### Sources

https://en.wikipedia.org/wiki/FN-6

China:
https://twitter.com/IiiTango/status/1303276970164342785
https://twitter.com/stoa1984/status/1430872643310399493/photo/1
Bangladesh
https://twitter.com/DefenseDtb/status/1336900761268056065/photo/1

Pakistan
https://twitter.com/IiiTango/status/1181546726219534336
https://inf.news/en/military/d30bad1ee2ed6cb75289aaff145c2947.html

Sipri Lines
Bangladesh (100)	FN-6	portable SAM	(2015)	2017-2020	(100)	FN-16 version; possibly incl assembly in Bangladesh
Cameroon (50)	FN-6	portable SAM	2012	2013	(50)	FN-16 version
Pakistan (295)	FN-6	portable SAM	(2017)	2018	(295)	FN-16 version

**Comment by bostonmyk** [comment]
See this request for the missile stats

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1017

**Comment by PygmalionOfCyprus** [comment]
Added 494.
