### ISSUE TITLE
Add 2021 out of service date #302 431 Kharg

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#102]
### DB Selector

DB3K

### Affected DBID(s)

Ship _302

### Summary of Changes

Add 2021 out of service date. Ship sunk in 2021.

### Sources

https://twitter.com/AmirIGM/status/1400006584097443840
https://twitter.com/Pataramesh/status/1400043179018231811/photo/1
http://www.matrixgames.com/forums/upfiles/61749/1BD2B4B347B14CFFB06AB28D607603EF.jpg

**Comment by Jkryos** [comment]
Updated.
