### ISSUE TITLE
Denmark SRC 90E Class Landing Craft x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1020]
### DB Selector

DB3K

### DBID to Copy

1763

### Hypothetical

No

### Name

LCP 1-4

### Country

Denmark

### Service

Navy

### In Commission

2003-

### Sensors

- 1x Mk1 Eyeball
- 1x Generic Navigation Radar

### Mounts

- 1x 12.7mm machine gun
- 1x Stinger MANPAD

### Other Changes

- Ordered for use on Abasalon (L-16)
- 10 fully equipped troops +3crew

### Sources

https://en.wikipedia.org/wiki/Storebro_SB90E
https://web.archive.org/web/20070220051814/http://www.storebro.se/Nav.aspx?pageid=79
http://navalhistory.dk/English/TheShips/Classes/LCP_Class%282004%29.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also added the 2x SAR versions which appear to be unarmed, more visible (obviously), and w/ a presumably-IR camera mounted next to the radar.
