### ISSUE TITLE
Denmark MHV 900 Class Patrol Boats x12

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1021]
### DB Selector

DB3K

### Hypothetical

No

### Name

MHV 901 Eno

### Class

MHV 900 Class

### Country

Denmark

### Service

Navy

### In Commission

2003-

### Length (m)

27.2

### Beam (m)

5.6

### Draft (m)

2.5

### Standard Displacement (t)

87

### Full Displacement (t)

97

### Complement

12

### Primary Propulsion Type

Diesel

### Propulsion

2x Scania DSI16V8 diesels

### Flank Speed (kt)

13

### Range (nm) at Speed (kt)

1800@11

### Sensors

- 1x Furuno FR-1505 DA navigation radar

### Mounts

- 2x 7.62mm MG

### Aircraft & Docking Facilities

- 1x davit for RHIB 

### Comments

Improved version of MHV 800.

### Sources

http://www.navypedia.org/ships/denmark/dk_cg_eno.htm
https://en.wikipedia.org/wiki/MHV900_class_patrol_boats
https://www.navalhistory.dk/English/TheShips/Classes/MHV900_Class(2003).htm

![FAENOE](https://user-images.githubusercontent.com/99632305/165812176-40ad5f56-ef9f-4d40-ba2c-c84641608b3b.jpg)
![450px-Danish_navy_home_guard_vessel_MHV_906](https://user-images.githubusercontent.com/99632305/165811978-d6b11c3c-5112-4be9-89e8-47a2119a6cdd.jpg)
![BMfyDYvCcAA7DcI](https://user-images.githubusercontent.com/99632305/165812098-ff2eaf8e-ce95-4978-a14c-826ed1c3f778.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
