### ISSUE TITLE
Denmark MHV 800 Class Patrol Boats x18

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1022]
### DB Selector

DB3K

### Hypothetical

No

### Name

MHV 801 Aldebaran

### Class

MHV 800 Class

### Country

Denmark

### Service

Navy

### In Commission

1992-

### Length (m)

23.7

### Beam (m)

5.6

### Draft (m)

2.2

### Standard Displacement (t)

80

### Full Displacement (t)

83

### Complement

12

### Primary Propulsion Type

Diesel

### Propulsion

2x Scania DSI14V8 diesels

### Fuel Capacity (kg)

7,800 litres

### Flank Speed (kt)

12

### Range (nm) at Speed (kt)

990@11

### Sensors

- 1x Furuno 1505 radar

### Mounts

- 1x 20mm/70 Oerlikon AA 
- 2x 7.6/92 MG

### Aircraft & Docking Facilities

- 1x davit for 7m RHIB

### Comments

Provision for carrying 1x 20mm/70 Oerlikon AA gun, added above already just because I like more guns not less. :-)

### Sources

http://www.navypedia.org/ships/denmark/dk_cg_aldebaran.htm
https://www.navalhistory.dk/English/TheShips/Classes/MHV800_Class(1992).htm
Combat Fleets of the World, 16th edition, pg 157

![mhv809Antares_Flotille114](https://user-images.githubusercontent.com/99632305/165813930-20b5004d-4bf3-401a-b581-31a08b44d4a6.jpg)
![download](https://user-images.githubusercontent.com/99632305/165813999-7e3aa3c0-e3b9-4a20-84c8-783c5852a285.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494 + a hypothetical ver. w/ the 20mm.
