### ISSUE TITLE
Denmark MRD Class x6

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1025]
### DB Selector

DB3K

### Hypothetical

No

### Name

MRD1

### Class

MRD Class

### Country

Denmark

### Service

Navy

### In Commission

1991-

### Length (m)

18.5

### Beam (m)

4.8

### Draft (m)

1.3

### Standard Displacement (t)

32

### Complement

3

### Primary Propulsion Type

Diesel

### Propulsion

2x General Motors Detroit Diesel diesel

### Fuel Capacity (kg)

??

### Flank Speed (kt)

12

### Range (nm) at Speed (kt)

??

### Sensors

- 1x Furuno navigation radar 
- 1x TSM2054 sonar

### Mounts

-1x Mini-Dyad magnetic minesweeping gear

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

The MRD Class was originally a part of the mine clearance module for the ships of the FLYVEFISKEN Class, each module consisted of 2 MRD's. The MRD's was equipped with a towed sonar and could be remotely controlled from the mother ship

![MRD1(1991)_2 HAVKATTEN(1990)](https://user-images.githubusercontent.com/99632305/165818588-6ec9d2af-535c-45e7-b48c-ef9be179d2c7.jpg)

MRD3 and MRD4 are now based at Frederikshavn and Korsør (resp.) for use as support vessels.

### Sources

https://www.navalhistory.dk/English/TheShips/Classes/MRD_Class(1991).htm
http://www.navypedia.org/ships/denmark/dk_ms_mrf1.htm

![MRD1(1991)](https://user-images.githubusercontent.com/99632305/165819133-245968a7-e137-4108-a279-47622a80ad21.jpg)
![MRD1(1991)_3](https://user-images.githubusercontent.com/99632305/165819149-47c050b2-36c8-4d2b-acb0-d81e59e21095.jpg)
![download](https://user-images.githubusercontent.com/99632305/165819247-e3104626-bcb3-41bc-9952-fe5d47ce666c.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
