### ISSUE TITLE
Ecuador Vigilante Class Patrol Craft x3 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1026]
### DB Selector

DB3K

### Baseline

2737 DB3k

### Hypothetical

No

### Name

LG-39 Isla Fernandina

### Class

Vigilante Class

### Country

Ecuador

### Service

Coast Guard

### In Commission

2006-

### Length (m)

45

### Beam (m)

9.8

### Draft (m)

2.5

### Standard Displacement (t)

300

### Complement

27

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 16V4000M90, 1x MTU 12v 4000 M90 

### Flank Speed (kt)

35

### Range (nm) at Speed (kt)

3000@12kn

### Sensors

- 2x Furuno navigation radar

### Mounts

- 42x 7.62mm/90 mg

### Aircraft & Docking Facilities

- 1x davit for 7m RHIB (Stern ramp)

### Comments

FBM Babcock Marine design, derived from the Protector class. Not sure it is the correct one noted above but can't find any others except NZ one that was designed by Tenix.

### Sources

http://www.navypedia.org/ships/ecuador/ecu_cf_6_de_diciembre.htm

![images_2013_01_07_ecuador](https://user-images.githubusercontent.com/99632305/165826989-277993e5-3bfe-4157-800b-669bc034c78d.jpg)
![download](https://user-images.githubusercontent.com/99632305/165826740-0ca484d5-7664-4cdd-84fb-d20f82de6d1d.jpg)
![fsm s a_GalExp_aboard_09-05-20_003 epc-S](https://user-images.githubusercontent.com/99632305/165826795-d0511b11-52c0-4e60-ace7-4ef0efefe9f4.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494. I gave it 2x MGs. I assume 42x was a typo because it doesn't look like a porcupine in the pictures.
