### ISSUE TITLE
Copy  Armored Plt (Leopard 2A4TR MBT) Turkey 2007

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1027]
### DB Selector

DB3K

### DBID to Copy

2333

### Hypothetical

No

### Name

Armored Plt (Leopard 2A4TR MBT)

### Country

Turkey

### Service

Army

### In Commission

2007

### Mounts

3 tank Mounts per platoon

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Turkish_Land_Forces
https://en.wikipedia.org/wiki/Leopard_2#Leopard_2A4
https://twitter.com/NoorNahas1/status/830196885268942848
https://twitter.com/Ozkok_A/status/1189608490593128449
Sipri Lines
Leopard-2A4	tank	2005	2006-2010	(298)	Second-hand (but modernized to Leopard-2NG after delivery in Turkey); EUR365 
56	Leopard-2A4	tank	2009	2010-2014	(56)	Second-hand (but probably modernized to Leopard-2NG version in Turkey after delivery)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
