### ISSUE TITLE
Yugoslavia & Romania - J-22 Orao II and IAR-93B Vultur (double GSH-23L and flare dispensers)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1029]
### DB Selector

DB3K

### Affected DBID(s)

1652, 2335, 398

### Summary of Changes

Mounts:
2x Gsh-23L [400 rounds]

POJR-L/D/S [96 Cartridges]: 4x Generic Chaff Salvo [4x Cartridges], 20x Generic Flare Salvo [4x Cartridges, Single Spectral] 
(only Yugoslavia and Serbia, IAR-95 didn't have these)

The J-22 Orao II has 2x twin barreled Gsh-23L 23mm guns on the left and right side of the fuselage each with 200 round for a total of 400 rounds.

J-22 Orao II carries one POJR-L and one POJR-D container each with 20 flares and 8 chaff bundles on the RATO hardpoints and one POJR-S container under the fuselage with another 40 flares. 

### Sources

First post, above the long text:
https://www.mycity-military.com/Avioni/J-22-Orao.html
https://imgur.com/nY7wHzv
https://imgur.com/teNLFU6
https://imgur.com/pKM0bVY

Flare & Chaff Dispensers:
https://imgur.com/gdq3uya
https://imgur.com/EJbwJ2b
https://imgur.com/Rjl3wrJ
https://imgur.com/A0QxQOT

picture at the bottom left:
https://imgur.com/khExIHD

**Comment by Jkryos** [comment]
Update DB3K 494.
