### ISSUE TITLE
Please add #461 SPICE-2000 to F-15I Ra'am (#4776)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#103]
### DB Selector

DB3K

### User(s)

F-15I #4776

### Weapons Carried

4 Spice-2000 (both warhead types likely)
2 sidewinders/Python 4
Litening III Pod
EL/802

,

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

I'd match the configuration used for the Heavy GBU-31 (18158)

### Sources

http://www.matrixgames.com/forums/upfiles/61749/FE450CC958C240FCBDA78814F6A0B6B8.jpg
https://defencehub.live/threads/israeli-air-force-%D7%96%D6%B0%D7%A8%D7%95%D6%B9%D7%A2%D6%B7-%D7%94%D6%B8%D7%90%D6%B2%D7%95%D6%B4%D7%99%D7%A8-%D7%95%D6%B0%D7%94%D6%B6%D7%97%D6%B8%D7%9C%D6%B8%D7%9C%E2%80%8E.702/

**Comment by PygmalionOfCyprus** [comment]
Added standard & long-range options identical to equivalent GBU-31 loadouts. 493.
