### ISSUE TITLE
Yugoslavia - LORAP KA-112A (Long Range Aerial Panoramic Photographic System) - Side Looking

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1030]
### DB Selector

DB3K

### Baseline

454 AN/ASD-12 Sharp

### Hypothetical

No

### Name

KA-112A LORAP [1800mm Long-Range]

### Sensor Generation

Late 1970s

### Range (nm)

60

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition]

### Scan Interval (s)

10

### Comments

The Lorap sensor is used in the LORAP Side looking visual recon pod. The system is side looking and has a range of 110km.
It has a 1800mm focal length. It was state of the art in the late 70s.

Role: Visual, Reconaissance Frame Camera
Ability: Visual, Second Generation TV Camera, I don't know what the Visual Zoom would be, the SLOS Visual Observation System with similar range, produced in the 80s has zoom detection 80.

The KA-112A LORAP pod has weight of 600kg.

"The long-range aerial panoramic photographic system (LORAP) has been developed to meet the requirements for an operational system which can acquire reconnaissance intelligence from a long-range side-looking vantage point. The heart of the LORAP airborne system is a KA-112A panoramic camera. The airborne portion of the system program encompassed the KA-112A, a pod, pylon, cockpit control, and aircraft modification as well as AGE (pod/camera handling and electronic test equipment), handbooks, aircraft certification data, training, spares, flight tests, and field service."

### Sources

https://ui.adsabs.harvard.edu/abs/1979SPIE..175...53M/abstract
"Second Generation panoramic imaging system:
https://defence.pk/pdf/threads/lorap-pod-information-needed.153945/
110km range:
http://forums.airforce.ru/foto-video/printfriendly2217-7/
Second post, 1800mm focal length:
http://il2forum.pl/index.php?topic=12081.300
used by Yugoslav Mig-21R:
https://www.tmbbooks.com/de/airm_MiG03.html
600kg weight post by braca75:
https://www.mycity-military.com/Avioni/MIG-21-Fishbed_1438.html

https://www.mycity-military.com/imgs2/139754_47821884_01_LORAP_MiG-21MF_867_1_detail.jpg
https://media.tangosix.rs/2015/10/IMG_2175.jpg
https://www.mycity-military.com/slika.php?slika=139754_155689104_recafa5m.jpg

**Comment by claudejdev** [comment]
@nuk92 
According to the link you've posted, it also has been carried by the Pakistani Mirage 5 and Chinese JZ-8 and FR-8.

For your further request :
Source : _Dimitrijevic, Bojan. 2020. SILVER BIRDS over the ESTUARY : The Mig-21 in Yugoslav and Serbian Air Force Service, 1962-2019_.:
> The converted MiG-21MFs were known as _L-15M_ (modified) rather than L-15i (izvidjač, reconnaissance). They were _stripped of radar and guns_ to enable better usage of the LORAP and to maintain proper flyability. A total of four MiG-21MFs (Nos. 22865 – 22868) were converted to LORAP carriers, while the L-14i continued to be used as platforms for Soviet reconnaissance pods.
> On 1 August 1984, a photographic laboratory was set-up in the underground facility at Bihać and, finally, the system became operational. Officially it was known as the “L” container and in the beginning of its usage only four pilots were converted to fly the LORAP-equipped MiGs, later expanding this number to most of the pilots in No. 352 Squadron. This system marked a significant step in equipping the Yugoslav aerial reconnaissance and it was used for wide and slope photography of the territories of the neighbouring countries. The camera did not have a horizontal limit and it could take images up to the end of the horizon. In practice, taken **at an altitude of 10,000 metres it could cover up to some 110 kilometres** of territory of Yugoslavia’s neighbours. In practice however, weather conditions limited the effective usage of LORAP to some 50-60 kilometres.


Pic 
![image](https://user-images.githubusercontent.com/35732829/165875071-4dcce2a6-d971-482d-9b07-6a77a8d10451.png)
![image](https://user-images.githubusercontent.com/35732829/165875339-f0074494-2017-4ce0-ab44-a31f3573755a.png)
![image](https://user-images.githubusercontent.com/35732829/165875729-dc092b10-b696-4687-bbad-3a4c5fe52a69.png)

In 1997
![image](https://user-images.githubusercontent.com/35732829/165875557-86feda64-783f-437b-8563-6367a2a4047a.png)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
