### ISSUE TITLE
NZ - C-130J-30 - Wescam MX-20 and satcom

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1035]
### DB Selector

DB3K

### Affected DBID(s)

5137 - C-130J-30 Hercules (New Zealand - 2024)

### Summary of Changes

Please add some value to these platforms by adding 1x 5524 _MX-20 Turret [FLIR/CCD/Laser Designator]_  and SATCOM comm device.
I'm not sure which one to pick in the DB.
There's no Inmarsat Global Xpress network I could find.

### Sources

Update: NZ C-130Js to get specialist equipment, advanced sensors

> The five Lockheed Martin C-130J-30s Super Hercules to be procured by New Zealand will have specialist equipment and sensors.
> 
> Janes has learned that the aircraft will be fitted with L3 WESCAM MX-20 electro-optical/infrared (EO/IR) cameras and a Honeywell JetWave Ka-band wide bandwidth, high-speed satellite communications (satcom) system.
> 
> The MX-20 system is designed for high-altitude intelligence, surveillance, target acquisition, and reconnaissance (ISTAR) operations. It has been deployed aboard long-range maritime patrol aircraft (MPA) and GA-ASI MQ-9B SkyGuardian unmanned aerial vehicles (UAVs).
> 
> Able to provide more than x400 magnification in the EO sensor and more than x75 magnification in the IR sensor, the MX-20 also uses Enhanced Local Area Processing (ELAP) to improve feature recognition.
> 
> Janes

[Update: NZ C-130Js to get specialist equipment, advanced sensors](https://www.janes.com/defence-news/update-nz-c-130js-to-get-specialist-equipment-advanced-sensors/)

[JetWave - Satellite Communications System for Military Operators](https://aerospace.honeywell.com/content/dam/aerobt/en/documents/landing-pages/brochures/N61-1623-000-000-JetWaveSatelliteCommunicationsSystemForMilitaryOperators-bro.pdf) (PDF)

**Comment by PygmalionOfCyprus** [comment]
Already handled in an internal news roundup!
