### ISSUE TITLE
Gambia ex-Hai Ou class x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1036]
### DB Selector

DB3K

### DBID to Copy

2321 DB3K

### Hypothetical

No

### Name

FPB Taipei

### Country

Gambia

### Service

Navy

### In Commission

2009-

### Sensors

- 1x generic navigation radar

### Mounts

- 4x single 12.7/90mg

### Other Changes

- Aluminum construction 
- Max speed now only 25-30kt
- Transferred by Taiwanese Navy without armament and electronics

### Sources

https://en.wikipedia.org/wiki/Dvora-class_fast_patrol_boat
https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjXl-T5q7j3AhWbhIkEHSyRDYA4ChAWegQIAhAB&url=https%3A%2F%2Fwww.globalsecurity.org%2Fmilitary%2F%2F%2Fworld%2Ftaiwan%2Fhai-ou-specs.htm&usg=AOvVaw2jTp1QxwaGvtEsdbxjqBUa
http://www.navypedia.org/ships/gambia/gam_cf_taipei.htm

![gam_cf45](https://user-images.githubusercontent.com/99632305/165882124-ebf7693d-0d88-4ce1-b9c4-7c5750a31907.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
