### ISSUE TITLE
Georgia MRTP 33 Class x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1038]
### DB Selector

DB3K

### DBID to Copy

3284 DB3k

### Hypothetical

No

### Name

P 24 Sokhumi

### Country

Georgia

### Service

Coast Guard

### In Commission

2008-

### Sensors

- 1x Generic Navigation radar

### Mounts

- 1 x 1 - 30/80 SMASH
- 2 x 1 - 7.6/90

### Other Changes

- GRP hull

### Sources

Combat Fleets of the World, 16th edition, pg 227
http://www.navypedia.org/ships/georgia/geo_cg_sokhumi.htm

![geo_cg54](https://user-images.githubusercontent.com/99632305/165882791-4a94ea0f-c3bc-4ebf-bded-e1650fbfd76e.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
