### ISSUE TITLE
Add GBU-12 and GBU-49 Loadouts to Israeli F-35A Adir #4700

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#104]
### DB Selector

DB3K

### User(s)

#4700

### Weapons Carried

Israeli's have the same beastmode GBU-12/GBU-49 combination as most client states.

4 GBU-12/49
2 Aim-9X

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

May want to consider a 2021 or 2022 version for this capability. 

### Sources

https://twitter.com/TheDeadDistrict/status/1461365038325776399

**Comment by PygmalionOfCyprus** [comment]
Added GBU-12/49 internal, internal long-range, and external ("beast mode") loadouts w/ Python 5 instead of 9X to AC 4700. Holding off on a new 2021/22 Adir variant since attached source is from testing and it could be some time yet before they clear it.
