### ISSUE TITLE
Jordan - Mi-26T2

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1041]
### DB Selector

DB3K

### DBID to Copy

4950 - Mi-26T2 Halo [Pemon] (Algeria - 2015)

### Hypothetical

No

### Name

Mi-26T2

### Country

Jordan

### Service

Air Force

### In Commission

2018

### Sources

[Largest airlift helicopter MI-26T2 joins RJAF | Jordan Times](http://www.jordantimes.com/news/local/largest-airlift-helicopter-mi-26t2-joins-rjaf)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
