### ISSUE TITLE
Norway - A530 Maud

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1042]
### DB Selector

DB3K

### DBID to Copy

2581 - A 136 Tidespring [MARS Tide Class] (United Kingdom - 2017)

### Hypothetical

No

### Name

A530 Maud

### Country

Norway

### Service

Navy

### In Commission

2019

### Other Changes

- Displacement=27500
- Length=183
- Beam=25.9
- Draft=8.62
- Complement=43
- TroopCapacity=116
- CargoCapacity=200
- 1x Hangar (2x Medium Aircraft (12.1-18m Long)) 
- 1x Pad (1x Large Aircraft (18.1-26m Long))
- Diesel Fuel=7000 (ID 1517)
- Aviation Fuel=300 (ID 595)

### Sources

[Nytt logistikk- og støttefartøy - Forsvaret.no](https://web.archive.org/web/20170307123805/https://forsvaret.no/forsvarsmateriell/nytt-logistikk-og-st%C3%B8ttefart%C3%B8y)
[KNM «Maud» visits Flåm - The Armed Forces](https://www.forsvaret.no/aktuelt-og-presse/presse/pressemeldinger/knm-maud-besoker-flam)
Waters, Conrad. Seaforth World Naval Review 2020. S.L.: Naval Inst Press, 2019.
[Norway's New Replenishment Oiler HNoMS Maud in First at-sea Fuel Transfer - Naval News](https://www.navalnews.com/naval-news/2021/02/norways-new-replenishment-oiler-hnoms-maud-in-first-at-sea-fuel-transfer/)

Source for pictures :
https://www.forsvaret.no/aktuelt-og-presse/presse/pressemeldinger/knm-maud-gjennomgar-tekniske-utredninger

**Comment by cdnice55** [comment]
Requested earlier https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/524 . Can combine requests and info.

**Comment by claudejdev** [comment]
> Requested earlier #524 . Can combine requests and info.

Good call cdnice! Silly of me, I didn't check beforehand.

**Comment by cdnice55** [comment]
Even when I check it happens to me! Never hurts to have more references for them to look at though, so still a good add.
