### ISSUE TITLE
Jordan - Il-76MF (2011-2019)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1043]
### DB Selector

DB3K

### DBID to Copy

4442 - Il-76MD-90A Candid B [Il-476] (Russia [1992-] - 2016)

### Hypothetical

No

### Name

Il-76MF

### Country

Jordan

### Service

Air Force

### In Commission

2011

### Other Changes

Length=53.2

Cargo hold length = 31.1 (versus 25.5). Thus, an area of 107 m² versus 88 m².

### Sources

[Rosoboronexport | Aerospace systems | Catalog](https://web.archive.org/web/20101231195452/http://www.roe.ru/cataloque/air_craft/aircraft.pdf) (PDF)
[Air Force Technology - IL-76 - Medium Range Transport Aircraft](https://web.archive.org/web/20061205192847/http://www.airforce-technology.com/projects/il76/)
[Jordan Buys 2 Russian Transport Aircraft, Interested in Choppers](https://web.archive.org/web/20061220145725/http://www.mosnews.com/money/2005/08/17/jordanaircraft.shtml)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Cargo cap increased to 60 tons.
