### ISSUE TITLE
Egypt - Il-76MF (2019)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1044]
### DB Selector

DB3K

### DBID to Copy

#1043

### Hypothetical

No

### Name

Il-76MF

### Country

Egypt

### Service

Air Force

### In Commission

2019

### Other Changes

Comments= x2

### Sources

[Russia Allows Jordan to Resale Two Il-76MF Transporters to Egypt | Israel Defense](https://www.israeldefense.co.il/en/node/39658)
[Egyptian Air Force acquires two Il-76MFs](https://www.key.aero/article/egyptian-air-force-acquires-two-il-76mfs)

> Mahmoud Gamal@Major_Gamer·Feb 20 Two and they were the only two new IL-76 aircraft built specially for Jordan
> Ghost of Cheras@ashraffzx·Feb 20 So.. Its leased from Jordan?
> Mahmoud Gamal@Major_Gamer·Feb 20 Nope, Egypt bought them from Jordan in 2019 after getting Russia approval
https://twitter.com/mahmouedgamal44/status/1495355047777083396/photo/3

![image](https://user-images.githubusercontent.com/35732829/165894701-dbda771f-106f-49d8-8338-3361e3e5bf5e.png)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
