### ISSUE TITLE
[WIP] Iran - "358" loitering SAM

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1045]
### DB Selector

DB3K

### Hypothetical

No

### Name

358

### Length (m)

*

### Width/Span (m)

*

### Diameter (m)

*

### Weight (kg)

*

### Range (nm)

*

### Warhead

*

### Targets

Aircraft, Helicopter, Missile

### Sensors

Imaging Infra-Red seeker
Laser-proximity fuze

### Weapon Codes

Anti-Air All-Aspect, Lock-On After Launch (LOAL), Loiter Capability, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation

### Comments

Not much datas for now, just though the request could be opened to start collecting details as they come. Given it is, as far as I know, the first of its kind.

### Sources

> Though a maximum speed or altitude has not been officially released it is thought that the missile is capable of cruising at around 500 KPH (c.300MPH) at an altitude of between 8000-12000 metres (c.26,000ft-39,000ft).
> Guidance is via an Imaging Infra-Red seeker and the 358 has a laser-proximity fuze for engaging aerial targets. It is also possible that the weapon may have an operator in the loop for mid-course guidance, which would make the 358 more akin to a suicide drone than an anti-aircraft missile. That seems likely as that way the weapon could be put into the air before an aircraft is in the vicinity, loiter and then be moved by the operator to where its guidance system can acquire the target.

[358 vs. Scan Eagle – Anti-Drone Action - Defense News - Military Matters](https://militarymatters.online/defense-news/358-vs-scan-eagle-anti-drone-action/)

- AMT Netherlands Titan engine, which weighs 3.6 kg, can generate 393 N of thrust
- MTi-100 inertial sensor modules

[Suspected Iranian loitering SAM powered by Dutch minijet](https://www.janes.com/defence-news/news-detail/suspected-iranian-loitering-sam-powered-by-dutch-minijet)
[New Iranian missile reported to be loitering SAM](https://www.janes.com/defence-news/news-detail/new-iranian-missile-reported-to-be-loitering-sam)

![image](https://user-images.githubusercontent.com/35732829/165895741-884b517d-051b-46a7-8ee2-ff447ff8f53e.png)
![image](https://user-images.githubusercontent.com/35732829/165895862-7a3ee63d-9c99-4418-beb6-fad23e315a1c.png)

[Iraqi Militias Show Off Iranian Anti-Air Missile | The Washington Institute](https://www.washingtoninstitute.org/policy-analysis/iraqi-militias-show-iranian-anti-air-missile)

**Comment by Jkryos** [comment]
Added DB3K 509.
