### ISSUE TITLE
Add 4 GBU Teber loadout to Akinci

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1047]
### DB Selector

DB3K

### User(s)

4998

### Weapons Carried

Copy 27960 reduce bombs 4 and swap paveways for GBU-TEBER[Mk 82] Weapon #3732

### Requires Buddy Illumination

No

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Not sure if the director is wired for TEBER

### Sources

https://www.navalnews.com/naval-news/2022/04/turkeys-akinci-engages-sea-target-for-the-1st-time/
https://postlmg.cc/PLcLfWZm

**Comment by tbrandon517** [comment]
Related to request #223

**Comment by PygmalionOfCyprus** [comment]
Added 495.
