### ISSUE TITLE
Add Radar [ELM-2084 MMR] To Czech Republic 2022 x8

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1048]
### DB Selector

DB3K

### DBID to Copy

2485

### Hypothetical

No

### Name

Radar [ELM-2084 MMR] 

### Country

Czech Republic

### Service

Army

### In Commission

2022

### Sensors

same

### Loadout Options

same 

### Sources

https://www.thedefensepost.com/2022/04/11/israel-air-defense-czech-republic/
https://twitter.com/ArmyRecognition/status/811532665312710656

**Comment by PygmalionOfCyprus** [comment]
I actually added this weeks ago but forgot to close it. So, added 494.
