### ISSUE TITLE
Georgia Iveria (Dilos) Patrol Boats x2 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1050]
### DB Selector

DB3K

### Baseline

#3264 DB3k

### Hypothetical

No

### Name

P 201 Iveriya

### Class

Dilos Class

### Country

Georgia

### Service

Coast Guard

### In Commission

1998-

### Length (m)

29

### Beam (m)

5

### Draft (m)

1.62

### Standard Displacement (t)

75

### Full Displacement (t)

86

### Complement

15

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 12V 331 TC81 diesels, 2 props, 2, 720 bhp

### Flank Speed (kt)

27

### Range (nm) at Speed (kt)

1600@25

### Sensors

- 1x Decca 1226C

### Mounts

- 2x twin 23/82 ZU-23-2
- 2x single 20mm/70mg
- 2x single 7.6mm/90

### Comments

2004, both: - 2 x 1 - 20/70, Decca 1226C radar; + , 2 x 1 - 7.6/90, radar

### Sources

http://www.navypedia.org/ships/georgia/geo_cf_iberia.htm (Denotes  Adamis but pic is of Dilios)
Combat Fleets of the World, 16th Edition, pg. 227 (Denotes Dilos)
Janes 2003-04, pg 250 (Denotes Dilos)

![1347434934_01](https://user-images.githubusercontent.com/99632305/166088900-ec1f2746-51b2-42cc-b235-4f31ff2e2838.jpg)
![geo_cf46](https://user-images.githubusercontent.com/99632305/166088742-8b7e8c08-fdbe-447b-a8ad-68e50256686e.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
