### ISSUE TITLE
Georgia Dauntless Class x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1051]
### DB Selector

DB3K

### DBID to Copy

3477

### Hypothetical

No

### Name

P 001

### Country

Georgia

### Service

Coast Guard

### In Commission

1998-

### Sensors

- 1x Raytheon R40X

### Mounts

- 2x single 12.77mm mg
- 2x single 7.62mm mg

### Sources

http://www.navypedia.org/ships/georgia/geo_cg_p208.htm

![geo_cg52](https://user-images.githubusercontent.com/99632305/166089148-8b137308-7af4-49fb-a59c-f2aa793eaccf.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
