### ISSUE TITLE
Georgia Zhuk (Pr.1400M Gryf) x8

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1052]
### DB Selector

DB3K

### DBID to Copy

2529 DB3k

### Hypothetical

No

### Name

P 102

### Country

Ge

### Service

Coast Guard

### In Commission

1997-

### Sensors

- 1x Lotsiya Navigation radar

### Mounts

- 1x twin 23mm ZU-23-2 87 cal AA

### Other Changes

- P204 and P205 were destroyed by Russian troops at Poti 14.8.2008.

### Sources

http://www.navypedia.org/ships/georgia/geo_cg_fazisi.htm
Combat Fleets of the World, 16th Edition, pg 228

![geo_cg50](https://user-images.githubusercontent.com/99632305/166089420-1d1c0a05-8d69-414a-89e6-58ec4c0b5859.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495 w/ 2x ZU-23-2s based on picture.

**Comment by cdnice55** [comment]
Wish I could ID weapons based on pics, will have to work on that!
