### ISSUE TITLE
Georgia Point Class x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1053]
### DB Selector

DB3K

### DBID to Copy

2729 DB3k

### Hypothetical

No

### Name

P 210 Tsotne Dadiani

### Country

Georgia

### Service

Coast Guard

### In Commission

2000-

### Sensors

- 1x Hughes-Furuno SPS-73

### Mounts

- 2x single 12.7mm Colt M2 mg

### Sources

http://www.navypedia.org/ships/georgia/geo_cg_tsotne_dadiani.htm
Combat Fleets of the World, 16th Edition, pg.228

![geo_cg53](https://user-images.githubusercontent.com/99632305/166089821-40795919-41d3-443f-a058-e1c4d26bf76c.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
