### ISSUE TITLE
Georgia Vydra Class (Pr.106k)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1054]
### DB Selector

DB3K

### DBID to Copy

3067 DB3k

### Hypothetical

No

### Name

001 Guria

### Country

Georgia

### Service

Coast Guard

### In Commission

2001-13

### Sensors

- 1x Chernomore MR 2512 navigation radar

### Mounts

- 2x twin 23mm/87cal ZU-23-2 AA

### Other Changes

To Coast Guard 2009, stricken 2013

### Sources

http://www.navypedia.org/ships/georgia/geo_ls_guria.htm

![geo_ls48](https://user-images.githubusercontent.com/99632305/166090067-c540bd65-1946-4bc1-87e1-0184d877b3ff.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Also did a pass on the Pr.106s, which had some wild numbers. They were marked as being almost 200m long...
