### ISSUE TITLE
Georgia Ondatra (Akula Class Landing Craft Pr.1176)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1055]
### DB Selector

DB3K

### DBID to Copy

2073 DB3K

### Hypothetical

No

### Name

01 MDK-01

### Country

Georgia

### Service

Navy

### In Commission

1993-2002

### Sensors

- 1x Mius (Spin Trough) navigation radar

### Mounts

- 2x 12.7mm MG

### Sources

https://weaponsystems.net/system/1234-Project%201176%20Akula%20class
http://russianships.info/eng/warships/project_1176.htm
Combat Fleets of the World, 16th Edition, pg. 229

![930ef9fc4c12ab97d90d24bd3807b2cb](https://user-images.githubusercontent.com/99632305/166090187-ac0f5c6e-b35d-4421-8f5a-d46e44e35e98.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
