### ISSUE TITLE
Georgia Kutaisi (AB 25 Class) Patrol Boat x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1056]
### DB Selector

DB3K

### DBID to Copy

1539 DB3k

### Hypothetical

No

### Name

202 Kutaisi

### Country

Georgia

### Service

Coast Guard

### In Commission

1998-

### Sensors

- Racal Decca TM1226
- Transferred from Turkey with ASW gear removed

### Mounts

- 1x Single 40/60
- 1x Single 20/70
- 2x Single 12.7/90

### Other Changes

- Mounts noted are for early 1998-2004?
- Second version with 1x Twin - 25/82 2M-3M, 1 x Twin - 23/82 ZU-23-2, 2 x Single - 12.7/79, with JRC radar

### Sources

https://en.wikipedia.org/wiki/AB-25-class_patrol_
Jane's 2003-04, page 250

![1024px-TurkeyNavyAB29](https://user-images.githubusercontent.com/99632305/166091088-01f1662a-b7bf-4d55-9724-55f49f584e07.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495 in both versions, one thru 2004 w/ 40mm & 20mm and one post-2004 w/ the 2M-3M & Zu-23-2.
