### ISSUE TITLE
Georgia Stenka (Pr.205P) Class

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1057]
### DB Selector

DB3K

### DBID to Copy

2536 DB3k

### Hypothetical

No

### Name

301 Batumi 

### Country

Georgia

### Service

Navy/Coast Guard

### In Commission

1998-

### Sensors

- Surface Search: 1x Pot/Drum; H/I band
- Navigation: 1x Palm Frond; I band

### Mounts

- 2x 37/73 70k

### Other Changes

Batumi - Navy (retired 2006)
Georgi Toreli - Coast Guard (in service as of 2020)

### Sources

http://www.navypedia.org/ships/georgia/geo_cf_batumi.htm
Janes 2003-04, pg 250

![geo_cf43](https://user-images.githubusercontent.com/99632305/166091669-a4827ee2-792d-42dc-80bb-7eeedb1d111c.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
