### ISSUE TITLE
Georgia Matka (PR.206MP) Class

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1058]
### DB Selector

DB3K

### DBID to Copy

2473 DB3K

### Hypothetical

No

### Name

302 Tbilisi

### Country

Georgia

### Service

Navy

### In Commission

1999-

### Sensors

- ESM: Clay Brick; intercept
- Weapons Control: Hood Wink optronic directors
- Air/Surface: Plank Shave; E-band
- Navigation: SRN 207
- Fire Control: Bass Tilt; H/I band 

### Mounts

- 2 x 1 P-15M Termit SSM (2 4K51)
- 1 x 4 Strela-3M SAM (16 9M36M)
- 1 x 1 - 76/59 AK-176M
- 1 x 6 - 30/54 AK-630M
- 2x PK-16 decoy RL

### Sources

http://www.navypedia.org/ships/georgia/geo_cf_tbilisi.htm
Jane's 2003-04, pg 250

![geo_cf42](https://user-images.githubusercontent.com/99632305/166092013-d6644b0a-2bd6-4027-b630-d22ff87138a8.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
