### ISSUE TITLE
Yugoslavia - NJ-21M Jastreb Maritime Reconnaissance Aircraft (Ericsson SLAR)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1059]
### DB Selector

DB3K

### DBID to Copy

1654 J-21 Jastreb

### Hypothetical

No

### Name

NJ-21M Jastreb

### Country

Yugoslavia

### Service

Air Force

### In Commission

1990-1992

### Sensors

1x Ericsson SLAR (sidelooking: arcs PMF1, PMA2, SMF2, SMA1)

### Loadout Options

- add unarmed recon loadout
- remove all armed loadouts

### Other Changes

change crew to 2 (twin seater)

### Sources

Ericsson SLAR below the fuselage:
https://www.mycity-military.com/slika.php?slika=123381_42784880_NJ-21M.jpg
https://www.mycity-military.com/imgs4/476830_75056469_NJ-21M%20Mornar_1.png
https://www.mycity-military.com/slika.php?slika=476830_63509321_NJ-21M%20Mornar_2.png
07:55:
https://www.youtube.com/watch?v=xLycoFMowBk
Four Erisccon SLAR purchased (post by gavrinem):
http://www.paluba.info/smf/index.php?topic=20.1220;imode

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
