### ISSUE TITLE
Add 8 Hellfire/JAGM USAF USMC MQ-9A Reaper Loadout 2020

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#106]
### DB Selector

DB3K

### User(s)

USAF and Marine Reapers

### Weapons Carried

8 Hellfires

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Software update in 2020 increased capacity to 8. Will likely be same for JAGM.

### Sources

https://www.creech.af.mil/News/Article-Display/Article/2366202/mq-9-reaper-takes-flight-with-8-hellfire-missiles/
https://www.airforcemag.com/mq-9-software-upgrade-doubles-hellfire-capacity/

**Comment by PygmalionOfCyprus** [comment]
Added 493.
