### ISSUE TITLE
Malaysia - A.400M

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1061]
### DB Selector

DB3K

### DBID to Copy

5470 A.400M Atlas [Grizzly] (Indonesia Air Force 2022)

### Hypothetical

No

### Name

A.400M

### Country

Malaysia

### Service

Air Force

### In Commission

2015

### Other Changes

Comments=x4

### Sources

> The operational history of the A400M transport aircraft began on 5 January **2015** with the acquisition of the A400M aircraft for the RMAF and officially No. 22 Skn operating the new aircraft. Since then, various tactical and strategic flight assignments have been implemented such as Air-to-Air Refueling, Medical Evacuation (MEDEVAC), Humanitarian Assistance Disaster Relief (HADR) as well as participation in exercises with foreign countries that have borne the name of ATM in general and RMAF in particular. . It even played a particularly important role for air delivery assistance when the Covid-19 pandemic hit the country when commercial airline aircraft were not operating.

http://www.airforce.mil.my/index.php/bm/component/search/?searchword=400M&searchphrase=all&Itemid=291

[Airbus - Orders, Deliveries, In Operation Military aircraft by Country - Worldwide](https://airbus.web.factory.eu.airbus.com/sites/g/files/jlcbta136/files/2022-04/2022-03_MRS_GEN_Ord-Deliv%20by%20country.pdf)(PDF)
[A400M customer profile: Royal Malaysian Air Force | Airbus](https://www.airbus.com/en/newsroom/stories/2020-06-a400m-customer-profile-royal-malaysian-air-force)

Question : will the _DataLoadout.Cargo_Volume_ column be used in a near future ?

**Comment by PygmalionOfCyprus** [comment]
Added 495.

> Question : will the DataLoadout.Cargo_Volume column be used in a near future ?

No. Actually, all the cargo loadouts are going to be deprecated soonTM.

**Comment by claudejdev** [comment]
Now I'm intrigued! :D
Looking forward to discover the clever solution you guys are implementing.

Le ven. 13 mai 2022 à 07:26, Ethan Hermanson ***@***.***> a
écrit :
