### ISSUE TITLE
ELT-555 DECM Pod - weight

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1062]
### DB Selector

DB3K

### Affected DBID(s)

2240 ELT-555 DECM Pod

### Summary of Changes

weight: 140kg

### Sources
https://de.scribd.com/document/138402215/ELT-555

吊艙尺寸：長度3000mm，直徑340mm
重量：140kg

Pod size: length 3000mm, diameter 340mm
Weight: 140kg

https://www.newton.com.tw/wiki/MB339%E6%95%99%E7%B7%B4/%E6%94%BB%E6%93%8A%E6%A9%9F/10594864

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
