### ISSUE TITLE
Loadouts - A.400M - 37 tons, Cargo Type fix

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1063]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

> The Cargo_Type value for the heaviest load A.400M cargo loadout is set to 3000 (APC, Towed Arty, Cruise Missiles), while the lighter loadouts, of 30 tons and lower, are set to 4000 (Tank, TEL, Trailer).
> As per Airbus documents, this cute flying whale can transport type 4000 cargo.
> Ergo, the 37 tons loadout should have a Cargo_Type of 4000.
> Peace.

Cargo, 37 tons
```
SET DataLoadout.Cargo_Type = 4000
WHERE DataLoadout.ID IN (3539, 13779, 13784, 13789, 13794, 13799, 27612, 29713, 30031);
```

### Sources

DB3k_493
https://aulaairbus.etsiae.upm.es/wp-content/uploads/2018/09/A400M-Design-Requirements-Conceptual-Definition.pdf

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
