### ISSUE TITLE
Saudi Arabia – the Herculean update, (K)C-130 fleet

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1064]
### DB Selector

DB3K

### DBID to Copy

*

### Hypothetical

No

### Name

*

### Country

Saudi Arabia

### Service

Air Force

### In Commission

*

### Other Changes

**Copy**

- [ ] ID 3121 C-130E Hercules, IOC 1965, Comments= x9
- [ ] ID 2009 KC-130H Hercules, IOC 1973,  Comments= x8
- [ ] ID 4544 C-130H Hercules, IOC 1974, Comments= x41
- [ ] ID 4391 C-130H-30 Hercules, IOC 1984,  Comments= x3
- [ ] ID 4584 KC-130J Hercules, IOC 2016,  Comments= x2

### Sources

[SIRPI World to Saudi Aurabia Aicrafts_Trade-Register-1950-2021.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8598387/World-Saudi-AC_Trade-Register-1950-2021.pdf)
[Royal Saudi Air Force](https://www.key.aero/article/royal-saudi-air-force)
[Hercules and Saudi Arabia: A historic partnership | Arab News](https://www.arabnews.com/node/1466991/saudi-arabia)
[Serving Saudi ambitions](https://www.key.aero/article/serving-saudi-ambitions)
[Lockheed C-130H Hercules (L-382) of 16th Squadron based at Riyadh seen arriving at IAT 79. 20 June 1979](https://commons.wikimedia.org/wiki/File:Lockheed_C-130H_Hercules_(L-382),_Saudi_Arabia_-_Air_Force_AN2223056.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
