### ISSUE TITLE
Add Indian Astra BVR missile 

### ISSUE THREAD

**Issue by Matharox** [PygmalionOfCyprus/cmo-db-requests#1065]
### DB Selector

DB3K

### Baseline

#273

### Hypothetical

No

### Name

Astra Mk.1

### Length (m)

3.84

### Width/Span (m)

0.68

### Diameter (m)

0.178

### Weight (kg)

154

### Range (nm)

2.0-48.0

### Target Altitude / Depth (ft)

30ft AGL - 80000 ASL

### Launch Altitude / Depth (ft)

200ft AGL - 65000 ASL

### Warhead

15kg HE

### Targets

Aircraft, Helicopter, Missile

### Sensors

1x Active Radar Seeker (~12nm range)

previously, a russian seeker was used, now indigenously produced seeker is used 

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer

### Comments

Air PoH 90% would suffice 

Tested and operational on IAF Su-30 MKIs, will be integrated with Mirage 2000s, Tejas and Mig-29 in the future.

### Sources

https://en.wikipedia.org/wiki/Astra_(missile)

For range: https://www.business-standard.com/article/news-ani/iaf-drdo-carry-out-test-firing-of-astra-air-to-air-missile-119091801432_1.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496 along with the Astra Mk2; also added loadouts for the Su-30MKI and Tejas (which has also been overhauled in 496).
