### ISSUE TITLE
Mine M70 update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1067]
### DB Selector

DB3K

### Affected DBID(s)

3402 Mine M70

### Summary of Changes

rename to: Mine AIM-M.70 [Bottom, Simple Magnetic, Passive Acoustic] -- Yugoslavia
add weight: 1100kg
warhead: AIM-M.70 [725kg HE]
has both broadband acoustic and simple magnetic fuze
-> properties: add magnetic fuze, simple magnetic

These could be layed by ships or submarines

### Sources

7th post
http://www.paluba.info/smf/index.php?topic=7990.msg51339;topicseen#msg51339
www.paluba.info/smf/index.php?action=dlattach;topic=7990.0;attach=392980;image

**Comment by tbrandon517** [comment]
Related request #367

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
