### ISSUE TITLE
Yugoslavia - AIM-M.82 bottom mine

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1068]
### DB Selector

DB3K

### Baseline

3402 Mine M70

### Hypothetical

No

### Name

Mine AIM-M.82 [Bottom, Simple Magnetic, Passive Acoustic] -- Yugoslavia

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

800

### Range (nm)

-

### Target Altitude / Depth (ft)

-492ft - -16ft

### Warhead

AIM-M.82 [480kg TAH] (720 DP)

### Targets

Surface Vessel, Submarine

### Sensors

-

### Weapon Codes

Mine - Magnetic Fuze, Simple Magnetic, Mine - Passive Acoustic Fuze, Broad-Band (Simple), Mine - Delay Counter, Mine - Arming Delay

### Comments

used by Yugoslav submarines

### Sources

7th post
http://www.paluba.info/smf/index.php?topic=7990.msg51339;topicseen#msg51339

**Comment by PygmalionOfCyprus** [comment]
Added 495.
