### ISSUE TITLE
Add 2020 retirement date to USMC AH-1W

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#107]
### DB Selector

DB3K

### Affected DBID(s)

#2924

### Summary of Changes

Add 2020 retirement date to USMC AH-1W. All Z now.

### Sources

https://www.thedrive.com/the-war-zone/37149/the-ah-1w-super-cobra-has-been-retired-from-the-marine-corps-after-34-years-of-service
https://www.helis.com/database/news/marine-ah-1w-retirement/

**Comment by Jkryos** [comment]
Updated.
