### ISSUE TITLE
Correction to Martadinata: Add LINK-Y datalink capability

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1070]
### DB Selector

DB3K

### Affected DBID(s)

Ship_3019

### Summary of Changes

The Indonesian frigate Martadinata should have a LINK Y datalink (roughly comparable to LINK 11)

### Sources

(https://www.naval-technology.com/projects/sigma-10514-pkr-guided-missile-frigates/)
https://www.thalesgroup.com/en/link-y-mk2-tactical-datalink#:~:text=Reliable%20exchange%20of%20tactical%20data,%3A%20reliable%2C%20secure%20and%20simple.
https://military-wiki.com/kri-raden-eddy-martadinata-the-power-of-the-sigma-frigate-built-by-indonesia/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
