### ISSUE TITLE
Indonesia, Add Krait class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1072]
### DB Selector

DB3K

### Baseline

#2752 PC-40 = KAL-40, differences with Krait class

### Hypothetical

No

### Name

Patrol Boat (PB), 827, Krait

### Class

Krait (PC-40)

### Country

Indonesia

### Service

Navy

### In Commission

2009 - present

### Length (m)

40

### Beam (m)

7.2

### Draft (m)

2

### Standard Displacement (t)

Not found

### Full Displacement (t)

100

### Complement

Not Found

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN diesels, 2 shafts

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

2500 @ ?

### Sensors

1 x Furuno navigation radar

### Mounts

1x twin 25mm/82 2M-3M
2x single 12.7mm/79

### Aircraft & Docking Facilities

2x RHIB

### Ship Codes

All Aluminum Construction

### Comments

A different class than the Viper whin is called KAL-40 in several sources.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/indonesia/ino_cf_krait.htm
3: http://indotoptech.blogspot.com/2011/09/kri-krait-827-kri-pertama-di-indonesia.html
4: https://majalahmiliter.blogspot.com/2008/12/kri-krait-827.html
![1](https://user-images.githubusercontent.com/99532490/166307649-c93b85ef-a5c3-450d-ac64-6f3efb14a634.jpg)
![2](https://user-images.githubusercontent.com/99532490/166307653-f9ab1a31-f2c8-4d99-aac8-3f35a24840d6.jpg)
![3](https://user-images.githubusercontent.com/99532490/166307655-6b2efd9b-3af5-4762-83cb-78fc779d257c.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
