### ISSUE TITLE
Yugoslavia - G-4 Super Galeb loadout overhaul

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1073]
### DB Selector

DB3K

### User(s)

397, 2894 G-4 Super Galeb [Yugoslavia & Serbia]

### Weapons Carried

-4x BL.755 No.1 CB
-1x Gsh-23L gun pod (optional)
--------------------------
-2x BL.755 No.1 CB
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x Mk82 500lb
-1x Gsh-23L gun pod (optional)
--------------------------
-2x Mk82 500lb
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x Mk82 500lb Snake Eye
-1x Gsh-23L gun pod (optional)
--------------------------
-2x Mk82 500lb Snake Eye
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x RAB-250 M91 Prefragmented Airburst
-1x Gsh-23L gun pod (optional)
--------------------------
-2x RAB-250 M91 Prefragmented Airburst
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x FAB-275 M91 FAE [Retarded] Proximity Fuze
-1x Gsh-23L gun pod (optional)
--------------------------
-2x FAB-275 M91 FAE [Retarded] Proximity Fuze
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-64x BR-20-57 57mm Rocket [HEAT+FRAG]
-1x Gsh-23L gun pod (optional)
--------------------------
-16x BR-128 M74 128mm Rocket [HE]
-1x Gsh-23L gun pod (optional)
--------------------------
-16x BR-128 M80 128mm Rocket [HEAT]
-1x Gsh-23L gun pod (optional)
--------------------------
-4x PLAB-200 M71 Incendiary Bomb
-1x GSh-23L gun pod (optional)
--------------------------

### Requires Buddy Illumination

No

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

No

### Comments

These loadouts should replace the current loadouts.

The centerline hardpoint can only carry the gun pod. The inner wing hardpoints can actually carry slightly more than 375kg.

### Sources

post by Bojank:
https://www.mycity-military.com/Avioni/G-4-Supergaleb_375.html
drop tanks - post by Berkut:
https://www.mycity-military.com/Avioni/G-4-Supergaleb_6.html

https://imgur.com/iWUWoAl
https://imgur.com/x7bPU9z
https://imgur.com/7Jj4m1O
https://imgur.com/u1VtHsk
https://imgur.com/n8fYmMQ
https://imgur.com/XSUz6Gs
https://i28.photobucket.com/albums/c226/Zivojin/Untitled3.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
