### ISSUE TITLE
Yugoslavia - G-4 Super Galeb update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1076]
### DB Selector

DB3K

### Affected DBID(s)

397, 2894, 4666 G-4 Super Galeb [Yugoslavia & Serbia & Myanmar]

### Summary of Changes

-remove Gsh-23L, it carried a Gsh-23L gun pod instead on the centerline hardpoint (optional weapon)
-POJ-264 [96 Cartridges]: 4x Generic Chaff Salvo [4x Cartridges], 20x Generic Flare Salvo [4x Cartridges, Single Spectral]
(only Yugoslavia and Serbia, Myanmar Super Galeb didn't have these)

### Sources

https://imgur.com/iWUWoAl
post by frangible cover:
https://www.matrixgames.com/forums/viewtopic.php?p=4508628#p4508628
G-4 Super Galeb flare and chaff dispensers, 2 carried, each with 40 flares and 8 chaff bundles
https://fotkica.com/phpbb/uploadsN/18848_IC%20levo.JPG
https://imgur.com/Wylu0Wo

**Comment by PygmalionOfCyprus** [comment]
Related to #1073

**Comment by PygmalionOfCyprus** [comment]
Didn't mean to close, whoops. Was just tagging to fix with the other one.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
