### ISSUE TITLE
Yugoslavia - Gsh-23L gun pod

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1077]
### DB Selector

DB3K

### Hypothetical

No

### Name

Gsh-23L gun pod

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

.

### Weight (kg)

200

### Range (nm)

1

### Warhead

1x 23mm Gsh-23L [200 rnds]

### Targets

Aircraft, Helicopter, Missile, Surface Vessel, Land Structure - Soft, Mobile Target - Soft

### Sensors

-

### Sources

post by djole-81:
https://www.mycity-military.com/Avioni/G-4-Supergaleb_229.html

**Comment by PygmalionOfCyprus** [comment]
Due to how we simulate weapons / weapon records on loadouts we actually don't need this, we just assign the bursts as a loadout "weapon."
