### ISSUE TITLE
Add 2017 retirement date to Peruvian Cruiser Almirante Grau #2707

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#108]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2707

### Summary of Changes

Ship retired in 2017.

### Sources

https://en.wikipedia.org/wiki/BAP_Almirante_Grau_(CLM-81)
https://www.navalanalyses.com/2015/06/almirante-grau-cruiser-of-peruvian-navy.html

**Comment by Jkryos** [comment]
Updated.
