### ISSUE TITLE
Indonesia, Add Cucut class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1081]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), 866, Cucut (ex-Jupiter)

### Class

Cucut

### Country

Indonesia

### Service

Navy

### In Commission

1991 - 2002 Singapore Navy, 2002 - present Indonesian Navy

### Length (m)

35.8

### Beam (m)

7.1

### Draft (m)

2.3

### Standard Displacement (t)

140

### Full Displacement (t)

170

### Complement

33

### Primary Propulsion Type

Diesel

### Propulsion

2x Deautz-MWM TBD234 V12, 2 shafts

### Flank Speed (kt)

14

### Range (nm) at Speed (kt)

200 @ 14

### Sensors

1x Decca 1226 I-band navigation radar

### Mounts

1x single 20mm/90 GAM-B01
2x single 12.7mm/90

### Aircraft & Docking Facilities

1x RHIB (10 pax)

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/indonesia/ino_cf_cucut.htm
![1](https://user-images.githubusercontent.com/99532490/166507321-fcc7ffe7-41e4-4e7e-a290-5be879eb4a9f.jpg)
![2](https://user-images.githubusercontent.com/99532490/166507327-fb9aab1f-f42e-404e-a528-a678911b1acb.jpg)
![3](https://user-images.githubusercontent.com/99532490/166507332-cacb1902-b588-49a5-af15-dd1aeedcc37d.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
