### ISSUE TITLE
Georgia Lindau (Type 331 Class) x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1082]
### DB Selector

DB3K

### DBID to Copy

845 CWDB

### Hypothetical

No

### Name

P 22 Ayety

### Country

Georgia

### Service

Coast Guard

### In Commission

1998-2008

### Sensors

- 1x Atlas Elektronic TRS: I-band

### Mounts

- 1x Bofors 40mm/70
- 2x 12.7mg

### Other Changes

Formerly the Germanminesweeper Minden (M-1085). Was in maintenance status when war with Russian Federation began in August 2008. Vessel was scuttled by Russian Federation forces at the dock in Poti. Subsequently refloated in September 2008. Returned to active duty as an at-the-dock training platform.

### Sources

https://en.wikipedia.org/wiki/Coast_Guard_of_Georgia#Georgian_Coast_Guard_vessels
Jane's 2003-04, Pg 251

**Comment by PygmalionOfCyprus** [comment]
Handled 503 as part of Georgia review.
