### ISSUE TITLE
Georgia Ochamchire (Island C-Series Class) x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1083]
### DB Selector

DB3K

### DBID to Copy

1301 DB3k

### Hypothetical

No

### Name

P 23 Ochamchire

### Country

Georgia

### Service

Coast Guard

### In Commission

2016-

### Sensors

- SPS-64(v)1 or SPS-73 radar

### Mounts

- Remove 25/75 Mk 38 Bushmaster as per attached pics?
- Add third 7.62 mg in the forward position

### Sources

https://en.wikipedia.org/wiki/Coast_Guard_of_Georgia#Georgian_Coast_Guard_vessels
https://en.wikipedia.org/wiki/Island-class_patrol_boat
https://agenda.ge/en/news/2016/2273

![georgian-coast-guard-vessels-ochamchire-p-23-110-island](https://user-images.githubusercontent.com/99632305/166517750-7d92fe91-1765-4cf7-92dc-429d93861ceb.jpg)
![boat](https://user-images.githubusercontent.com/99632305/166517811-9808b500-2c3e-4178-823a-d749804b98c5.jpg)
![1539876992-11-1024x593](https://user-images.githubusercontent.com/99632305/166517884-6e8bcf49-e884-41d3-a645-79f97afe65e4.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
