### ISSUE TITLE
Georgia Sokhumi (KANN 33 Class) x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1085]
### DB Selector

DB3K

### DBID to Copy

3285 DB3k

### Hypothetical

No

### Name

P 24 Sokumi

### Country

Georgia

### Service

Coast Guard

### In Commission

2008-

### Sensors

- 2x Furuno radars

### Mounts

- 1x single 30/80 SMASH
- 2x single 7.6/90

### Other Changes

GRP hull

### Sources

http://www.navypedia.org/ships/georgia/geo_cg_sokhumi.htm
https://en.sg.gov.tr/kaan-33-class-cg-boats
http://warshipsresearch.blogspot.com/2015/08/georgian-coast-guard-vessel-sokhumi-p.html

![geo_cg54](https://user-images.githubusercontent.com/99632305/166520378-7f21ee50-c05d-440b-a0ba-90c06d59c54c.jpg)
![georgian_coast_guard_vessel_sokhumi__p_24__2008__by_dolfijn1962-d97pf83](https://user-images.githubusercontent.com/99632305/166520813-aea5274b-67e5-4635-aada-14bb02a915d3.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
