### ISSUE TITLE
Canada R 16 Crescent  (C Class Destroyer) x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1088]
### DB Selector

CWDB

### DBID to Copy

16 CWDB

### Hypothetical

No

### Name

R 16 Crescent

### Country

Canada

### Service

Navy

### In Commission

1945-55

### Other Changes

Began refit to type 15 in 1953.

### Sources

https://en.wikipedia.org/wiki/HMCS_Crescent
Janes 1950-51, page 96
Janes 1954-55, page 96

![300px-HMCS_Crescent_R16](https://user-images.githubusercontent.com/99632305/166572554-87ce4c84-14cc-4454-a336-83149e9da726.jpg)
![CRS0001](https://user-images.githubusercontent.com/99632305/166572658-103b47ce-d0c5-4f31-a394-151437583afb.jpg)

**Comment by Jkryos** [comment]
Added CWDB 496.
