### ISSUE TITLE
Canada R 17 Algonquin (V Class Destroyer) x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1089]
### DB Selector

CWDB

### DBID to Copy

1718 CWDB

### Hypothetical

No

### Name

R 17 Algonquin

### Country

Canada

### Service

Navy

### In Commission

1943-55

### Sources

http://www.forposterityssake.ca/Navy/HMCS_ALGONQUIN_R17_224.htm
https://en.wikipedia.org/wiki/HMCS_Algonquin_(R17)

![300px-HMCS_Sioux_AWM_P05890 046](https://user-images.githubusercontent.com/99632305/166573592-183d39ab-68c3-468a-a228-868458faf23d.jpg)

**Comment by Jkryos** [comment]
Added CWDB 496.
