### ISSUE TITLE
Ghana Stephen Otu (Chamsuri Class - Sea Dolphin) x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1094]
### DB Selector

DB3K

### DBID to Copy

197 DB3k

### Hypothetical

No

### Name

P 33 Stephen Otu

### Country

Ghana

### Service

Navy

### In Commission

2011-

### Sensors

- 1x Raytheon 1645

### Mounts

- 1x 1 40/60 Mk 3
- 1x 3 20/76 Sea Vulcan
- 2x 1 20/70 Mk 10
- 2x 12.7/50 mg

### Sources

http://www.navypedia.org/ships/ghana/gha_cf_stephen_otu.htm
Combat Fleets of the World, 16th Edition, pg 247

![gha_cf37](https://user-images.githubusercontent.com/99632305/166624787-5531482c-47ab-4fba-ad56-fdb07620c5fe.jpg)
![Naval-command2-750x563](https://user-images.githubusercontent.com/99632305/166624931-369019de-d3eb-45dd-904a-e1a2c262ca1e.jpg)
![1008267_472883406132920_1323119966_o](https://user-images.githubusercontent.com/99632305/166624996-ba4e0527-9056-4e1e-aee6-8ed1e57e240f.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
