### ISSUE TITLE
Marte ER 

### ISSUE THREAD

**Issue by Venom63it** [PygmalionOfCyprus/cmo-db-requests#1095]
### DB Selector

DB3K

### Baseline

MARTE MK2/S

### Hypothetical

No

### Name

Marte ER

### Length (m)

3.6

### Width/Span (m)

1

### Diameter (m)

0.316

### Weight (kg)

340

### Range (nm)

62

### Warhead

70 Kg SAP

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened

### Sensors

1x Active Ku Band radar
1x IIR 

### Weapon Codes

Terrain Following, Uses GPS

### Comments

Marte ER is a sea-skimming, high subsonic anti-ship and land attack missile.  range to over 100 km, The missile is fire-and-forget capable and designed to operates in all weather conditions. The Eurofighter Typhoon can carries up to 6 Marte ER anti-ship missiles.
The MArte ER integrtion on Typhoon was founded by Kwait currently Italy and Kwait have planned to use it on their Typhoon.
The missile is also integrted for use on NH 90 Helicopter for Italian Navy and Quatar NAvy
Quatar has bought 12 land Batteries armed with Marte ER

### Sources

https://www.mbda-systems.com/product/marte-er/
https://en.wikipedia.org/wiki/Sea_Killer_/_Marte
https://www.janes.com/defence-news/news-detail/dimdex-2022-mbdas-marte-er-achieves-full-scale-production
https://newsroom.mbda-systems.com/strongmbda-signs-contract-to-supply-more-marte-er-anti-ship-missile-to-qatarnbsp-strong/marte-er-su-nh90-sarzana-c-mbda-jpg-2/

**Comment by tbrandon517** [comment]
Weapon already in the DB

https://cmano-db.com/weapon/3925/

**Comment by Venom63it** [comment]
I discover that there was same problem in my local file, Stem dawnload all again and now is appers.
