### ISSUE TITLE
SAM Battery Grifo Italian Army

### ISSUE THREAD

**Issue by Venom63it** [PygmalionOfCyprus/cmo-db-requests#1097]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM bty (Grifo [Camm ER army]

### Facility Type

SAM

### Country

Italy

### Service

Esercito EI

### In Commission

2023

### Sensors

Rheinmetall Italia X-TAR 3D radar X band

### Mounts

6 x tel (8 Camm Er)

### Sources

https://www.laran.it/wp-content/uploads/2019/02/Dossier-CAMM-ER.Omississ.pdf
https://www.esercito.difesa.it/comunicazione/Pagine/Nuove-tecnologie-per-l-Esercito-Italiano20200113.aspx
https://www.analisidifesa.it/2020/05/lesercito-italiano-ed-i-recenti-programmi-di-acquisizione-ed-ammodernamento/

**Comment by PygmalionOfCyprus** [comment]
Added 495 along w/ X-TAR3D family.
