### ISSUE TITLE
SAM bty (MAADS (CAMM ER)

### ISSUE THREAD

**Issue by Venom63it** [PygmalionOfCyprus/cmo-db-requests#1098]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM bty (MAADS)

### Facility Type

SAM

### Country

Italy

### Service

Air Force

### In Commission

2023

### Sensors

1x Kronos Land

### Mounts

3 x Tecne 8x8TEL ( 8 xCAMM ER)

### Sources

https://aresdifesa.it/medium-advanced-air-defence-system-per-la-aeronautica-militare/
https://www.laran.it/wp-content/uploads/2019/02/Dossier-CAMM-ER.Omississ.pdf
https://www.senato.it/service/PDF/PDFServer/BGT/01330775.pdf
https://www.portaledifesa.it/forum/showthread.php?tid=649&page=26&highlight=spada

**Comment by PygmalionOfCyprus** [comment]
Added 495, along with the KRONOS Land radar and CAMM-ER itself.
