### ISSUE TITLE
Dutch MQ-9 are to be armed

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1099]
### DB Selector

DB3K

### DBID to Copy

#5286

### Hypothetical

No

### Name

MQ-9A BLock-5 UAV (Netherlands 2023)

### Country

The Netherlands

### Service

Air force

### In Commission

2023

### Mounts

Same as #5286

### Other Changes

Because of the war in the Ukraine the parliament voted to arm the MQ-9A Reaper UAV's

https://intimacies-of-remote-warfare.nl/perspectives/dutch-house-of-representatives-to-vote-on-use-of-armed-drones/
https://wnl.tv/2022/04/13/kamermeerderheid-wil-killerdrones-militair-gezien-kunnen-zij-bijzonder-effectief-zijn/
https://curacao.nu/mq-9-reaper-drone-defensie-ook-voor-ukraine/

### Sources

Because of the war in the Ukraine the parliament voted to arm the MQ-9A Reaper UAV's

https://intimacies-of-remote-warfare.nl/perspectives/dutch-house-of-representatives-to-vote-on-use-of-armed-drones/
https://wnl.tv/2022/04/13/kamermeerderheid-wil-killerdrones-militair-gezien-kunnen-zij-bijzonder-effectief-zijn/
https://curacao.nu/mq-9-reaper-drone-defensie-ook-voor-ukraine/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
