### ISSUE TITLE
Add Heavy 6 PGM 500lb Bomb loadout to ROCAF F-16V #4912

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#11]
### DB Selector

DB3K

### User(s)

Aircraft #4912

### Weapons Carried

2 Sidewinder, 2 Amraam, 6 Bombs, 2 Fuel tanks, Sniper Pod

### Requires Buddy Illumination

- [X] Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

- [ ] Yes

### Sources

https://www.scramble.nl/military-news/rocaf-4th-tfw-foc-ceremony

**Comment by Jkryos** [comment]
Added DB3K 493.
