### ISSUE TITLE
Replace 370 Gallon with 600 Gallon Drop tanks to all external F-22 Long Range Loadouts

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#110]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2201, 4972, 4858, 3821,4975

### Summary of Changes

F-22 uses 2 600 Gallon Tanks for non stealthy LR loadouts.

### Sources

https://twitter.com/kadonkey/status/1321670829525139461
https://www.thedrive.com/the-war-zone/37219/this-f-22-raptor-wing-tank-storage-facility-looks-like-a-science-fiction-movie-set
https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104506/f-22-raptor/

**Comment by Jkryos** [comment]
Updated relevant loadouts DB3K 493.
