### ISSUE TITLE
Colombia to retire their Kfir fighters

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1100]
### DB Selector

DB3K

### Affected DBID(s)

4746, 5306, 2228, 1253, 5309, 5308

### Summary of Changes

The Fuerza Aérea Colombiana (Colombian Air Force) will withdraw the Kfir fleet by 2022, according to local media reports in recent days. The service seems to have decided to hasten the decommissioning of the jets due to the high maintenance and operating costs, as well as the difficulty of finding spare parts.

Kfir fighters have been the backbone of the Colombian Air Force since they were introduced in 2011. They were acquired second hand by the Israeli Air Force and have been in service for over 30 years (1989). Colombia bought 24 Kfirs, two of which were lost in accidents.

This decision is surprising, however, as the fighters were updated a few years ago. The Colombian Air Force completed the modernization process of its Kfirs in 2017, which received more advanced flight systems that allow the use of weapons of greater range and precision. The process, carried out by Israel Aircraft Industries (IAI), also involved the replacement of the aircraft's engines.

For some years Colombia has been considering equipping its air force with 15 more advanced fighters. Possible options include buying second-hand Lockheed Martin F-16 Fighting Falcon aircraft from Denmark or new Saab Gripen E/F fighters from Sweden (which could be manufactured in Brazil, according to pevious statements by Saab CEO Micael Johansson).

### Sources

https://www.blogbeforeflight.net/2022/02/colombia-to-retire-kfir-fighters-by-2022.html
https://www.airdatanews.com/colombia-to-retire-its-kfir-fighter-jets-in-2022-report/
https://www.aviacionline.com/2021/05/replacement-of-colombian-iai-kfirs-cancellation-rumors-amid-social-unrest/
https://twitter.com/DarkEdge357hawk/status/1517532997104373766
https://twitter.com/cosorioa/status/1501764383344676866
https://twitter.com/360RadioCo/status/1501196045719465986

**Comment by PygmalionOfCyprus** [comment]
Updated 495.
