### ISSUE TITLE
Vinten Model 753A Panoramic Camera

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1101]
### DB Selector

DB3K

### Baseline

5332 Vinten Model 547

### Hypothetical

No

### Name

Vinten Model 753A Panoramic Camera

### Sensor Generation

Late 1970s

### Range (nm)

5

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition]

### Comments

The Vinten 750 is early 70s technology, the 753A is a newer model.
Used in the Vinten recon pod of the J-22 Orao I.
Change the technology to 1980s/1990s AXX-1.

### Sources

https://www.aviationancestry.co.uk/Humm/Sites/Main/Views/Database/Images/Vinten/Role%20Equipment-Vinten-1972-57148.jpg

Page 55, the older Vinten 750, the Vinten 753A is both a newer model and probably modified/upgraded because of the A designation.
https://theses.gla.ac.uk/1151/

Stated as modern recon equipment, page 15 bottom left:
https://de.scribd.com/doc/255544921/NA%C5%A0-ORAO

**Comment by PygmalionOfCyprus** [comment]
Added 495.
