### ISSUE TITLE
Vinten Model 880 Frame Camera

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1102]
### DB Selector

DB3K

### Baseline

5332 Vinten Model 547

### Hypothetical

No

### Name

Vinten Model 880 Frame Camera

### Sensor Generation

Early 1980s

### Range (nm)

5

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition]

### Scan Interval (s)

10

### Comments

The Vinten 880 was considered to be a relatively modern system by the Yugoslav Airforce. It was used in the Vinten recon pod of the J-22 Orao I.

Change the technology to 1980s/1990s AXX-1

### Sources

https://www.mycity-military.com/imgs/113795_68816145_scan0023.jpg
https://www.mycity-military.com/imgs/113795_68816145_scan0024.jpg

Stated as modern recon equipment, page 15 bottom left:
https://de.scribd.com/doc/255544921/NA%C5%A0-ORAO

The Vinten isn't listed in this Thesis on Reconnaissance Camera from the University of Glasgow from 1978 whereas some older Vinten cameras are listed (page 96 onwards) including the 750. The 880 is likely a newer development:
https://theses.gla.ac.uk/1151/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
