### ISSUE TITLE
AFA A-39 frame camera

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1103]
### DB Selector

Both

### Baseline

AFA A-100 Oblique Camera

### Hypothetical

No

### Name

AFA A-39 Frame Camera [100mm]

### Sensor Generation

Early 1960s

### Range (nm)

5

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition]

### Scan Interval (s)

10

### Comments

AFA A-39 Frame Camera for supersonic aircraft.

Role: Visual, Frame Camera
Generation: Visual, 1st Generation TV Camera (1960s/1970s, TISEO), zoom level: 4

### Sources

middle part of the text:
https://tangosix.rs/2015/02/11/istorija-domace-upotrebe-lovca-presretaca-mig-21/

https://www.ostron.de/Sammeln-Seltenes/Russische-Luftbildkamera-Spionage-AFA-39.html

https://www.16va.be/3.4_la_reco_part1_eng.html

**Comment by PygmalionOfCyprus** [comment]
Added 495.
