### ISSUE TITLE
ICLS-401 Infrared Line Scanner

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1105]
### DB Selector

DB3K

### Baseline

892 - Generic Infrared Line Scanner

### Hypothetical

No

### Name

ICLS-401 Infrared Line Scanner

### Sensor Generation

Late 1970s

### Range (nm)

5

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition]

### Comments

The ICLS-401 is a part of the ICLS recon pod used by the J-22 Orao I. It can be used for night time recon.

### Sources

Post by gavrinem:
http://www.paluba.info/smf/index.php?topic=20.1220;imode

Stated as modern recon equipment, page 15 bottom left:
https://de.scribd.com/doc/255544921/NA%C5%A0-ORAO

**Comment by PygmalionOfCyprus** [comment]
Added 495.
