### ISSUE TITLE
#3217 FFG 818 Daegu Datalinks

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1108]
### DB Selector

DB3K

### Affected DBID(s)

3217

### Summary of Changes

Currently FFG 818 Daegu only has HF/VHF/UHF Radios. According to Hanwha Systems' brochure and You and Choi (2017), Naval Shield CMS of Daegu-class frigates (FFX-II) has Link-11 Datalink. I think Link-11 should be added to FFG 818.

### Sources

![img](https://user-images.githubusercontent.com/104970911/166883397-8285104f-7a95-49d7-acac-737011d0cd5c.jpg)

https://www.econovill.com/news/articleView.html?idxno=335921

![20220505_173940](https://user-images.githubusercontent.com/104970911/166889446-16f7c128-45a8-4141-8d06-3562637d48ea.jpg)

You, Hojeong and Byeonggon Choi, "Message Analysis and Development Situation on the Tactical Data Link of Combat Management System in Naval", Journal of Satellite, Information and Communications Vol.12 No.2, 2017
https://www.koreascience.or.kr/article/JAKO201761242144559.pdf

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
