### ISSUE TITLE
Indonesia, Add Pari class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1109]
### DB Selector

DB3K

### Baseline

#2644

### Hypothetical

No

### Name

Patrol Boat (PB), 849, Pari

### Class

Pari class, PC-43 design

### Country

Indonesia

### Service

Navy

### In Commission

2013 - present

### Length (m)

44

### Beam (m)

7.4

### Draft (m)

1.8 (#2644)

### Standard Displacement (t)

200 (#2644)

### Full Displacement (t)

250

### Complement

33 + 17

### Primary Propulsion Type

Diesel

### Propulsion

3x MAN, 3 shaft

### Fuel Capacity (kg)

50k ltr

### Flank Speed (kt)

29

### Range (nm) at Speed (kt)

1632 @ ?

### Sensors

1x Navigation radar

### Mounts

1x single 30mm/82 Marlin WS (bow)
2x single 12.7mm/90 (aft)

### Comments

4 units in class in batch 1, 13 in Batch 2 (Tatihu)
Similar as the KCR 40

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/indonesia/ino_cf_pari.htm
3: https://en.wikipedia.org/wiki/Pari-class_patrol_boat
4: https://defense-studies.blogspot.com/2016/03/tni-al-luncurkan-kapal-patroli-cepat-43.html
5: https://www.wikipe.wiki/wiki/id/KRI_Sidat_(851)
![1](https://user-images.githubusercontent.com/99532490/167009841-324a4e40-416b-4423-beae-6d972bdac43a.jpeg)
![2](https://user-images.githubusercontent.com/99532490/167009844-56abb170-ff90-4d73-8c5a-4a7d0483480f.jpg)
![3](https://user-images.githubusercontent.com/99532490/167009847-41d90010-06ec-4a78-af8f-8a21a0d8a8e9.jpg)
![4](https://user-images.githubusercontent.com/99532490/167009848-e1231e7f-c585-4117-b083-ae1a76cf3f2a.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Were there any significant differences between Batch 1 and 2 potentially warranting an entry for the other batch?

**Comment by Parel803** [comment]
I'll look it up, ASAP
