### ISSUE TITLE
#681 R 33 Vikramaditya needs weapons and sensors added 2016

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#111]
### DB Selector

DB3K

### Affected DBID(s)

Ship 681

### Summary of Changes

**On Delivery:** Sperry Bridgewater Nav Radar,Fregat M2EM and Prodberezovik Radars for air and surface search.
**From 2016:**Add 2 AK-230 CIWS either side of fantail. Arcs go port-aft, Starboard-aft. Blindspot forward. .2 EO/IR sensor on aft with Gun 3 Barak-I 8 cell launcher on island. Elta EL/M-221 STGR fire control on aft mast). Systems pulled off Godvaris at retirement.

### Sources

https://www.navyrecognition.com/index.php/news/defence-news/year-2015-news/july-2015-navy-naval-forces-defense-industry-technology-maritime-security-global-news/2910-indian-navy-aircraft-carrier-ins-vikramaditya-finally-fitted-with-defensive-weapon-systems.html
https://defence.pk/pdf/threads/ins-vikramaditya-refitted-with-barak-1-pdms-ak-630-ciws.386123/page-2
https://www.defenseindustrydaily.com/ins-vikramaditya-may-hit-delay-cost-increases-03283/

**Comment by PygmalionOfCyprus** [comment]
Added/fixed 493.
