### ISSUE TITLE
Greece Kortenaer Class Frigates

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1110]
### DB Selector

DB3K

### Affected DBID(s)

1578, 1341, 948, 969, 407, 1686, 957, 963, 409 DB3k

### Summary of Changes

1578, 1341, 948, 969, 407 F 450 Elli - All entries appear to be the same except for a difference in Mk36 ammo and the magazine having an AS.12 in one and not the other between 1341 and 948

168, 957, 963, 409 F 459 Adrias - All entries appear to be duplicates

Suggest that as per posters attached below the entries be replaced by the following: 

- Original 1981/2 loadout
- SSM: 2x 4 Harpoon
- SAM: RIM-7 NATO Sea Sparrow PDMS (Aspide missiles)
- Guns: 2x 76mm/62 Compact
- A/S Weapons: 4 (twin) Mk.32 TT for Mk 46 torpedoes
- Helicopters: 2x AB.212 ASW Helicopters
- Surface Search: 1x DA.05
- F/C: 1x LW.08, 1x WM 25, 1x STIR
- Navigation Radar: 1x ZW.06
- Sonar: SQS-505 (bow mounted)
- EW: SLQ-1 (Newton Gamma ESM/ECM)

- Batch I - 459, 460, 461, 462 (1994, 1993, 1995, 1997) Attached graphic
- Batch II - 450, 451 (1981, 82) Attached graphic (seems to have some upgrades from original as delivered)
- Batch III - 463, 464, 465, 466 (2001, 2002, 2002, 2003) Attached graphic

- Batch I & II Upgraded - Mid-Life Modernization program (229GR) 2004-10
- Addition of MIRADOR optronic observation and weapon control system
- Addition of  SCOUT Mk2 LPI radar, a sensor that equips also the ships of the Batch III, while the old ZW06 surface search and navigation radar was removed
- Upgrade of WM25 combined surface search and fire control radar
- Upgrade of STIR 1.8 tracking and illumination radar
- Upgrade of LW08 long range air-search radar
- Installation of the EDO CS-3701 Electronic Support Measures (ESM)(RWR?); the old  SPHINX is removed
- Integration of the terminal data Link 11 from Rockwell Collins in the combat management system
- Installation of INMARSAT FLEET 77 on three ships (Nikiforos Fokas, Themistocles and Kountouriotis)
- Installation of V/UHF SATURN featuring Electronic Communications anti-Counter Measure (ECCM)

F-463 was the last frigate to be built (October 1983) but it is the first ship of the class that was decommissioned. The decommissioning ceremony took place on 18 February 2013. This was the only ship of the class that was never equipped with a Phalanx CIWS. Today, the ship is being used as a source of spare parts for the rest of the ships in the class.

Notes from Naval Analyses Article:
- CIWS: The block that belongs the Phalanx of the Batch II and III ships, is the old Block 1. The vessels of the Batch II are equipped with the Block 1A Baseline 0 models while some of the vessels of Batch I have an upgraded Block 1A Baseline 1 model similarly with the Hydra class frigates of Hellenic Navy. The Batch III frigates received Block 0 systems from the retired Knox frigates; these models have been upgraded also to Block 1A standards.
- The Mk36 SRBOC consists of the Mk137 launcher, each vessel of the Batch I and II is equipped with four Mk137 launchers while the Batch III with two.
- Batch I and II were initially equipped with SLQ-01(Dutch variant of Elettronica's Newton Gamma ESM/ECM system). The system has been removed from the modernized ships.  The next Batch III frigates keep the Signaal's I/J-band Reprogrammable Advanced Multimode Shipborne ECM System (RAMSES) or else SLQ-02.
- Vessels are equipped with Canadian Westinghouse SQS-505 or SQS-509 (last four ships) hull-mounted; active search and attack sonar.
- Each frigate carry one helicopter; the modernized frigates carry either an AB212 ASW helicopter or an a S70 Aegean Hawk while the non-modernized frigates only the AB212. Both types are specialized in ASW operations with the appropriate equipment (dipping sonar, radar etc.) and weapons. The S70 helicopters can carry up to three Mk46 Mod5 ASW torpedoes and AB212 can carry two. In addition, S70 helicopters can carry one Penguin Mk2 Mod 7 air-to-surface missile or four AGM-114 Hellfire missiles. The AB212 may also be armed with a MG3 mount to perform a variety of operations. Main missions for the AB212 and S70  are antisubmarine warfare (ASW), antisurface warfare (ASuW), and surface surveillance. Secondary missions include SAR, MEDEVAC, VERTREP and Special Operations (Fast Roping, Parachuting, etc.).
- All the non-modernized frigates of the class, have received the new electro-optical sensor MLT-TDR-10A made by Miltech Hellas.

### Sources

https://www.navalanalyses.com/2015/03/elli-class-frigates-of-hellenic-navy.html
Combat Fleets of the World 2016, pg. 248
http://www.navypedia.org/ships/greece/gr_es_elli.htm
https://en.wikipedia.org/wiki/Elli-class_frigate

Batch I
![Elli class Batch I](https://user-images.githubusercontent.com/99632305/166978968-bbfb3d76-0d12-4722-9de0-e795f42c57d7.jpg)

Batch II
![Elli class Batch II](https://user-images.githubusercontent.com/99632305/166979017-e359f02d-017a-4691-93e9-1cb243930dac.jpg)

Batch III
![Themistocles](https://user-images.githubusercontent.com/99632305/166979071-01a6a73d-8ae6-4259-ac68-8a1acee55dc9.jpg)
![Elli class Batch III](https://user-images.githubusercontent.com/99632305/166979088-5199b4b9-ab17-4eb6-a017-867ff521943f.jpg)

![Elli (Kortenaer) class](https://user-images.githubusercontent.com/99632305/167015012-baf7fe9a-c51f-4f32-9417-eec1a2f15850.jpg)

**Comment by Jkryos** [comment]
Updated DB3K 497.
