### ISSUE TITLE
Greece Etna Class Replenishment Ship x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1111]
### DB Selector

DB3K

### DBID to Copy

819 DB3k

### Hypothetical

No

### Name

A 374 Prometheus

### Country

Greece

### Service

Navy

### In Commission

2003-

### Sensors

- 1x AN/SPS-10D (G band)
- 2x GEM LD-1825 nav

### Mounts

- 1x 20mm Mk15 Block IA CIWS fwd (+1 to be fitted on hangar?)
- 2x single 20 mm AA
- 1x AN/SLQ-25 Nixie-decoy

### Sources

https://en.wikipedia.org/wiki/Etna-class_replenishment_oiler
Combat Fleets of the World, 16th Edition pg. 255
https://www.naval-technology.com/projects/etna/
https://www.hellenicnavy.gr/en/fleet/general-support-ships/hs-prometheus-a-374.html

![250px-Prometheus_A374](https://user-images.githubusercontent.com/99632305/167029391-e889ac62-01ad-4207-bdd8-be40fb0d26e4.jpg)
![200700702-Faliron-HS_Promitheus-A374](https://user-images.githubusercontent.com/99632305/167029439-2b60b8c1-2309-4cb8-930a-19bbc4fdcd80.jpg)

**Comment by PygmalionOfCyprus** [comment]
Already in DB as Ship 3064. But did a pass with edits.
