### ISSUE TITLE
Indonesia KAL-40-Class Patrol Boats x9

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1117]
### DB Selector

DB3K

### Affected DBID(s)

2752

### Summary of Changes

Listed as PC-40 in platform entry but should be KAL-40. The PC-40  is noted as the KRAIT class as per earlier request to add to DB.

### Sources

KRAIT CLASS
http://www.navypedia.org/ships/indonesia/ino_cf_krait.htm

VIPER CLASS
http://www.navypedia.org/ships/indonesia/ino_cf_viper.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
