### ISSUE TITLE
Indonesia Tanjung Nusanive Troop Transports x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1119]
### DB Selector

DB3K

### Hypothetical

No

### Name

973 Tanjung Nusanive

### Class

Tanjung Nusanive Class

### Country

Indonesia

### Service

Navy

### In Commission

2005-

### Length (m)

144.5

### Beam (m)

23.4

### Draft (m)

6.0

### Standard Displacement (t)

14178

### Complement

119

### Primary Propulsion Type

Diesel

### Propulsion

2x MaK 6MU101 diesels

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

5500@12

### Sensors

- 2x Navigation Radars

### Mounts

- 2× 20mm Rheinmetall Mk 20 Rh-202 in single mount

### Comms/Datalinks

Standard

### Comments

1600 passengers

### Sources

http://www.navypedia.org/ships/indonesia/ino_ls_tanjung_nusanive.htm
Combat Fleets of the World, 16th Edition, pg 299
https://en.wikipedia.org/wiki/KRI_Tanjung_Nusanive_(973)

http://www.navypedia.org/ships/indonesia/ino_ls_tanjung_nusanive.htm

![KRI_Tanjung_Nusanive_(973)](https://user-images.githubusercontent.com/99632305/167222223-8ac29ea2-3b8d-4991-9022-211955943a53.jpg)
![download](https://user-images.githubusercontent.com/99632305/167222329-3aebd12c-0045-4e8d-bb45-6fc177d4ed45.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
