### ISSUE TITLE
Update Chilean Type 23 with CMS 330, TRS-4D Radar and CAMMS Missile system 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#112]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2875

### Summary of Changes

Chilean Duke Frigates #2875 get uprades from Canada and UK.  CAMM VLS, TRS-4D and CMS-330

### Sources

https://www.defencetalk.com/military/forums/t/chilean-navy-today.14985/
https://twitter.com/papakia_mantola/status/1332957779859005446
https://www.navalnews.com/naval-news/2019/05/lockheed-martin-details-chilean-navy-type-23-frigates-upgrade/
https://en.wikipedia.org/wiki/CAMM_(missile_family)#Maritime_variant

**Comment by Jkryos** [comment]
Added DB3K 493.
