### ISSUE TITLE
Indonesia Tanjung Kambani Troop Transport x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1120]
### DB Selector

DB3K

### Hypothetical

No

### Name

971 Tanjung Kambani

### Class

Tanjung Kambani Class

### Country

Indonesia

### Service

Navy

### In Commission

2000-

### Length (m)

114.5

### Beam (m)

19.8

### Draft (m)

6

### Standard Displacement (t)

7253

### Complement

119

### Primary Propulsion Type

Diesel

### Propulsion

2x Makita Diesels

### Flank Speed (kt)

18

### Range (nm) at Speed (kt)

?? 

### Sensors

- 2x Navigation radars

### Mounts

 - 2x 25/80 2M-3M
 - 2x Single 20/85 S.20

### Aircraft & Docking Facilities

- Fitted with a landing deck for two helicopters (AS.332 Super Puma)
- Davits for 4x LCVP

### Comms/Datalinks

Standard

### Ship Codes

Built to Mercantile Standards

### Sources

http://www.navypedia.org/ships/indonesia/ino_ls_tanjung_kambani.htm
https://en.wikipedia.org/wiki/KRI_Tanjung_Kambani
Combat Fleets of the World, 16th Edition, pg 299-300

![KRI_Tanjung_Kambani_971](https://user-images.githubusercontent.com/99632305/167223010-e37976e3-4b2c-4e70-8799-46868421c030.jpg)
![kri-tanjung-kambani-image3](https://user-images.githubusercontent.com/99632305/167223033-9e2f56db-9fa4-42c9-87c0-0687dd2b898b.jpg)
![WhatsApp-Image-2021-04-23-at-10 29 47-4-1024x682](https://user-images.githubusercontent.com/99632305/167223071-7ede9788-04f9-40fd-a5e4-aabd1c5e5bf9.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
