### ISSUE TITLE
CAPTOR radar not supposed to be an AESA?

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#1121]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 225

### Summary of Changes

The CAPTOR has the petal-shaped sensor coverage zone as if it is and AESA/PESA, but my understanding is that AESA wasn't introduced until the later CAPTOR-E (CAESAR).

### Sources

https://en.wikipedia.org/wiki/Euroradar_CAPTOR

**Comment by PygmalionOfCyprus** [comment]
Hmm...sensor 225 isn't an AESA radar in the DB. Might be worth a post in the tech support forum for this one.

**Comment by boogaboogaCMO** [comment]
You can't see the sensor property list from within CMO, but cmano-db.com definitely lists 'Active Electronically Scanned Array (AESA)' as one of the various properties of sensor 225:

 http://cmano-db.com/sensor/225/

**Comment by PygmalionOfCyprus** [comment]
Which version of the DB are you using?

**Comment by boogaboogaCMO** [comment]
493

**Comment by PygmalionOfCyprus** [comment]
Aha. Okay, this must have gotten ninja'd in 494. We did a big review of AESA radars to adjust swashplate arcs. Probably got fixed then.

**Comment by boogaboogaCMO** [comment]
Okay, cool 👍
