### ISSUE TITLE
AIM-4G [IR] - Vietnam Mod: Target Altitude Too High

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#1122]
### DB Selector

CWDB

### Affected DBID(s)

Weapon 1534

### Description of Problem

This seems to represent a Vietnam-era experiment to turn the AIM-4 into an ad-hoc air-to-ground missile, which is cool. However, one cannot currently use the missile in the air-to-ground role because the minimum Target Altitude is set to 30ft AGL.

### Recommended Fix

Reduce the minimum Target Altitude from 30 ft to 0 ft AGL.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
