### ISSUE TITLE
B-36s Should Not Have Probe Refueling Capability

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#1123]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 404-411, 2240

### Summary of Changes

As far as I know, B-36s never had any air refueling capability. The 'Probe Refuelling' Property should be removed from all of these aircraft.

### Sources

https://www.smithsonianmag.com/air-space-magazine/b-36-bomber-at-the-crossroads-134062323/
https://en.wikipedia.org/wiki/Convair_B-36_Peacemaker#World_War_II_and_after

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
