### ISSUE TITLE
Indonesia Sorong Class Replenishment Oiler x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1125]
### DB Selector

DB3K

### Hypothetical

No

### Name

911 Sorong

### Class

Sorong Class

### Country

Indonesia

### Service

Navy

### In Commission

1965-2021

### Length (m)

112.17

### Beam (m)

15.4

### Draft (m)

6.6

### Standard Displacement (t)

5100

### Full Displacement (t)

8700 (with fuel)

### Empty Displacement (t)

4090

### Complement

110

### Primary Propulsion Type

Diesel

### Propulsion

1x Deutz diesel

### Flank Speed (kt)

15

### Range (nm) at Speed (kt)

??

### Sensors

- 1x Navigation Radar

### Mounts

- 4x 12.7mm MG

### Aircraft & Docking Facilities

- 2x davits for RHIBS

### Comms/Datalinks

Standard

### Comments

- 3000 tons fuel
- re-fuel to starboard/port/stern

### Sources

https://en.wikipedia.org/wiki/KRI_Sorong_(911)
Combat Fleets of the World, 16th Edition, page 302
https://www.indomiliter.com/kri-sorong-911-kapal-tanker-pendukung-operasi-pendaratan-amfibi-di-dili/

![KRI_Sorong_911](https://user-images.githubusercontent.com/99632305/167233747-38ef306f-d4b9-4fba-ab7d-c1bf63e859c8.jpg)
![images](https://user-images.githubusercontent.com/99632305/167233749-e6ae6736-0610-4fdc-8a1d-07cf5a289b40.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
