### ISSUE TITLE
Indonesia Teluk Amboina Class Tank Landing Ship

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1126]
### DB Selector

DB3K

### DBID to Copy

1242 DB3K

### Hypothetical

No

### Name

503 Teluk Amboina

### Country

Indonesia

### Service

Navy

### In Commission

1961-

### Sensors

- 1x Generic Navigation radar

### Mounts

- 6x single 37mm/63 Soviet V-47M AA

### Sources

Combat Fleets of the World, 16th Edition, page 303
http://www.navypedia.org/ships/indonesia/ino_ls_teluk_amboina.htm
https://en.wikipedia.org/wiki/KRI_Teluk_Amboina

![KRI_Teluk_Amboina_503](https://user-images.githubusercontent.com/99632305/167234203-d1dd89c5-2794-4fc3-96fb-06e948b280f9.jpg)
![ino_ls1](https://user-images.githubusercontent.com/99632305/167234175-1701e6cb-d64b-403d-8333-f6389650edf7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added to DB3K, need to copy over to CWDB.

**Comment by PygmalionOfCyprus** [comment]
Handled as part of ongoing nat. review for Indonesia in CWDB.
