### ISSUE TITLE
Iran PF-103 Class

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1127]
### DB Selector

DB3K

### DBID to Copy

1696

### Hypothetical

No

### Name

82 Naghdi

### Country

Iran

### Service

Navy

### In Commission

2009-

### Sensors

- Mk 34 FC removed (was associated with former Mk 63 control system previously removed)
- 1x Decca 1226 navigation radar
- 1x Raytheon 1650 navigation radar
- 1x SPS-6E air search

### Mounts

- aft 76mm mount removed
- 2x 2 C802 Noor SSM missiles added
- 2x triple 324mm ASW TT

### Sources

Combat Fleets of the World, 16th Edition, pg 309
https://en.wikipedia.org/wiki/Bayandor-class_corvette

![download](https://user-images.githubusercontent.com/99632305/167236778-a6306fc6-acd1-40f2-8206-94796b06b774.jpg)
![13931120121446295_PhotoL](https://user-images.githubusercontent.com/99632305/167236787-0c69f477-8c25-40fc-ac69-5c35b564d96c.jpg)
![13931208164145538_PhotoL](https://user-images.githubusercontent.com/99632305/167236791-cea8815e-1f1e-422e-8950-97652ffe1769.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
