### ISSUE TITLE
Add Russia Sopka-2 Surveillance Radar (2016)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#113]
### DB Selector

DB3K

### Hypothetical

No

### Name

Sopka-2

### Sensor Generation

Early 2010s

### Sensor Capabilities

Air Search

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Passive Electronically Scanned Array (PESA)

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm

### Scan Interval (s)

10

### Target Altitude (ft)

36000

### Comments

In service 2016. Seems like many fixed sites around now. Lot in the Arctic.

3D dual-use S-band air-route radar with a range of 350km

### Sources

https://lemz.ru/wp-content/uploads/2019/10/ARRC-%E2%80%9CSOPKA-2%E2%80%9D-ENG.pdf
https://www.csis.org/analysis/ice-curtain-why-there-new-russian-military-facility-300-miles-alaska
https://www.newsweek.com/russia-deploys-air-radar-arctic-wrangel-island-538527
https://ru-pvo.livejournal.com/228182.html
https://function.mil.ru/news_page/country/more.htm?id=12142898@egNews
https://twitter.com/CSIS/status/1258485503600418817
https://twitter.com/halmiso1/status/1137955745209683973
https://twitter.com/AlRFORCEFREAK/status/779749732658868224
https://twitter.com/Russian_Defence/status/864955166268817411

**Comment by bostonmyk** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1373

**Comment by HVAA** [comment]
Any idea which one we are tracking on this issue.  It's one of the few RF ATC radars in production and is appearing as far apart as Novaya Zemlya in the far north, to Ay-Petri (near Yalta) in the South.  Big powerful multipurpose radar with a lot of capability that should (IMO) be in the game.
NATO = SNOW FACE but still lacking a source

**Comment by bostonmyk** [comment]
https://www.armadainternational.com/2023/04/russian-air-defence-analysis-part-2/?utm_source=twitter

_According to EW Analytics, the 12A6 is an S-band (2.7 gigahertz/GHz to 2.85GHz) ground-based air surveillance radar. It has a range of circa 243 nautical miles/nm (450 kilometres/km). Open-source information says the radar can detect a target at over 328,084 feet/ft (100,000 metres/m) at circa 65nm (120km) range. Targets at circa 32,808ft (10,000m) can be detected at ranges of 216nm (400km). Importantly, these figures do not specify the radar cross section of the target which will influence detection ranges and altitudes._

_Russian sources stated that the RASF planned to acquire enough 12A6 radars to cover the whole country with an initial 20 being delivered by the end of 2014. Belarus activated a single 12A6 radar in January 2021 at Baranovichi airbase. This facility is around 150km (93 miles) north of the country’s border with Ukraine. Taking the radar’s location into account, it could look 162nm (300km) miles into Ukraine’s airspace. EW Analytics’ information says that an ACP is collocated at the airbase. The radar almost certainly feeds track data into this ACP._
