### ISSUE TITLE
Iran Shahid Roudaki Intelligence and Support Ship x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1130]
### DB Selector

DB3K

### DBID to Copy

1599 and 2641

### Hypothetical

No

### Name

L110-1Shahid Roudaki

### Country

Iran

### Service

Navy 

### In Commission

2020-

### Sensors

- 1x Navigation radar
- 1x Surface radar
- Intelligence fit out

### Mounts

- 1x 23mm AA gun
- 3x Heavy MG over bow

### Other Changes

- Length 150m
- Beam 22 m
- 12,000 tonnes
- Built to commercial standards

### Sources

http://www.hisutton.com/Iranian-IRGC-Forward-Base-Shahid-Roudaki.html
https://en.wikipedia.org/wiki/IRIS_Shahid_Roudaki
https://news.usni.org/2020/11/19/video-iran-inducts-new-special-operations-ship

![1ef4b737693f74e6c4d85d0d0e97d898](https://user-images.githubusercontent.com/99632305/167238837-0f5cc9ae-4860-4f34-b004-acd0c225caa9.jpg)
![2222](https://user-images.githubusercontent.com/99632305/167238843-fa656643-83c0-4192-8787-31278b3ca9f2.jpg)
![shaheed-rodaki-image04-m](https://user-images.githubusercontent.com/99632305/167238847-eb53c66f-563c-494e-af36-9bfe732d74ed.jpg)
![EnPuyrMXIAAcuQv](https://user-images.githubusercontent.com/99632305/167238857-946b5f39-5ef3-4ff3-b6ae-8784c378541e.jpg)
![Iran-Shahid-Roudaki-Intelligence-Ship](https://user-images.githubusercontent.com/99632305/167238921-d782a5b3-e130-48cf-88c1-19d50f5fa844.jpg)

**Comment by tbrandon517** [comment]
Additional Source

https://www.thedrive.com/the-war-zone/37726/iran-unveils-its-new-sea-base-warship-that-looks-like-a-floating-arms-bazar

**Comment by cdnice55** [comment]
Thank you!

**Comment by PygmalionOfCyprus** [comment]
Added 495. Its "default load" is the guns + 4x twin Ghader missile boxes; I figure if scenario designers want to add the SAM vehicles, etc. they can.
