### ISSUE TITLE
MF-10/F3D Skynight aircraft are missing the 'Reserve [Available]' loadout

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#1131]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 2224, 2225, 2228, 2229

### Description of Problem

These are missing the standard loadout 'Reserve [Available]', so there are issues in scenarios where these aircraft need to be readied. 

### Recommended Fix

Add the 'Reserve [Available]' loadout to these aircraft, Loadout DBID 3.

**Comment by PygmalionOfCyprus** [comment]
How on earth did that happen? Fixed for 495.
