### ISSUE TITLE
Russia - FAB-250ShN-54 GPB, Parabrake

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1132]
### DB Selector

DB3K

### DBID to Copy

1505 FAB-250M-54 GPB (CWDB ID = 513)

### Hypothetical

No

### Name

FAB-250ShN-54 GPB

### Country

Russia

### Service

Air Force

### In Commission

late seventies

### Other Changes

- Length = 1.99
- Weight = 275
- LaunchSpeedMin = 270
- LaunchSpeedMax = 540
- LaunchAltitudeMin = 30
- LaunchAltitudeMax = 500
- Comments = Parabrake
- WeaponCodes.CodeID = 8002 (Is Retarded Munition)

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- Gordon, Yefim (2004). Soviet / Russian aircraft weapons : since World War Two. Hinkley: Midland Publishing.
- Lennox, D. (2001). Jane's air-launched weapons. Coulsdon, Surrey, UK: Jane's Information Group
- NATO Explosive Ordnance Disposal Centre of Excellence - Former Warsaw Pact ammunition handbook, volume 3 Air Forces Ammunition Aerial projectiles, bombs, rockets and missiles.

**Comment by PygmalionOfCyprus** [comment]
Added 495.

**Comment by claudejdev** [comment]
RIP 494! 🥳 
Hurrah for 495, "Due by May 09, 2022" No pressure, eh
