### ISSUE TITLE
Russia - FAB-500ShN-54 GPB (Correction to Update #658)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1133]
### DB Selector

DB3K

### Affected DBID(s)

3458 - FAB-500ShN-54 GPB -- Parabrake

### Summary of Changes

> That one is on me! 
> In #658 I previously suggested changes to ID 3458 - FAB-500ShN-54 GPB -- Parabrake that I now know to be wrong. So, here we go again, if you don't mind.

- Length = 2.19
- Weight = 518
- LaunchSpeedMin = 270
- LaunchSpeedMax = 540
- LaunchAltitudeMin = 30
- LaunchAltitudeMax = 500

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- Gordon, Yefim (2004). Soviet / Russian aircraft weapons : since World War Two. Hinkley: Midland Publishing.
- Lennox, D. (2001). Jane's air-launched weapons. Coulsdon, Surrey, UK: Jane's Information Group
- NATO Explosive Ordnance Disposal Centre of Excellence - Former Warsaw Pact ammunition handbook, volume 3 Air Forces Ammunition Aerial projectiles, bombs, rockets and missiles.

Note :
_Information released in 1992 credited the FAB-500ShN with a destructive area of 1,500 m2._

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
