### ISSUE TITLE
Russia - PBK-500U (JSOW like). Data, Warhead.

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1134]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

- [x] **DataWeapon**

ID | Name
---|---
3086 | PBK-500U SPBE-K [INS + GLONASS]
3087 | PBK-500U Unitary [INS + GLONASS]
- Comments = 2016?
- Length = 3.1
- Weight = 540
- LandRangeMax = 16.2
- LaunchSpeedMin = 378 kts (700 km/h)
- LaunchSpeedMax = 594 kts (1100 km/h)
- LaunchAltitudeMin = 100
- LaunchAltitudeMax = 14000

- [x] **DataWarhead**

ID | Name
---|---
1032 | PBK-500U SPBE-K (8 x SPBE-K) Anti-Tank
- Name = PBK-500U SPBE-K (15 x SPBE-K) Anti-Tank
- Type = 6012	(Cluster Bomb, Guided Submunitions, Anti-Tank (Shaped Charge))
- NumberOfWarheads = 15

_The SPBE-K is a 15 Kg ATk sub-munition with a radar seeker (in millimeter wavelength) and an IFF channel._

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
