### ISSUE TITLE
Spain - BRP-250 LDGP [250kg HE, Retarded] (DataWeaponCodes)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1135]
### DB Selector

DB3K

### Affected DBID(s)

3484

### Summary of Changes

**DataWeaponCodes**
please add a new line :

- DataWeaponCodes.ID = 3484 (BRP-250 LDGP [250kg HE, Retarded])
- DataWeaponCodes.CodeID = 8002 (Is Retarded Munition)

### Sources

DB3K_493

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
