### ISSUE TITLE
Indonesia, Add Kupang (LC) class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1136]
### DB Selector

DB3K

### Baseline

#1455, #3470

### Hypothetical

No

### Name

Utility Landing craft (LC), 582, Kupang

### Class

Kupang (Based on US LCU 1610 class)

### Country

Indonesia

### Service

Navy

### In Commission

1978 - present

### Length (m)

42.9

### Beam (m)

9.14

### Draft (m)

1.8

### Standard Displacement (t)

Not found

### Full Displacement (t)

400

### Complement

17

### Primary Propulsion Type

Diesel

### Propulsion

4 diesels, 2 shafts

### Flank Speed (kt)

11

### Range (nm) at Speed (kt)

700 @ 11

### Sensors

1x Navigation radar

### Mounts

2x single 12.7mm/90

### Comments

1 unit (of 3) believed to be in service
200 t. Cargo for military load

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/indonesia/ino_ls_kupang.htm
![1](https://user-images.githubusercontent.com/99532490/167311963-1d312524-6394-4052-aa39-587aa3b1c69c.gif)
![3](https://user-images.githubusercontent.com/99532490/167311970-f6dc23fb-352f-4620-b3ba-38f86a3b9599.jpg)
![4](https://user-images.githubusercontent.com/99532490/167311972-0651c8c7-fb1b-4371-b017-69ed64ee7856.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
