### ISSUE TITLE
Indonesia, Add Tarakan (AOR) class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1137]
### DB Selector

DB3K

### Hypothetical

No

### Name

Replenishment Tanker (AOR), 905, Tarakan

### Class

Tarakan

### Country

Indonesia

### Service

Navy

### In Commission

2014 - present

### Length (m)

122.4

### Beam (m)

16.5

### Draft (m)

6.1

### Standard Displacement (t)

2400

### Complement

108

### Primary Propulsion Type

Diesel

### Propulsion

2x diesels, 2 shafts

### Fuel Capacity (kg)

5500 m3 

### Flank Speed (kt)

18

### Range (nm) at Speed (kt)

7680 @ 12

### Sensors

2x navigation radar. I-band & E/F-band

### Mounts

2x single 20mm
2x single 12.7mm

### Aircraft & Docking Facilities

Platform for 1 medium helo (Bell-412)

### Comments

2 of 3 units in service and 1 tbd, the 2nd unit (Bontang 907 is slightly longer)
2 refuel stations for RAS
Solid stores. 

### Sources

1: JFS 2015-2016
2: https://www.defencetalk.com/military/forums/t/indonesia-green-water-navy.3897/page-41
3: https://defense-studies.blogspot.com/2014/09/menhan-resmikan-kapal-oiler-untuk-tni-al.html
4: https://www.navyrecognition.com/index.php/news/defence-news/2018/november-2018-navy-naval-defense-news/6662-indodefence-2018-bmc-shipyard-shocases-latest-tanker-for-tni-al.html
5: https://www.facebook.com/watch/?v=1043887882470553
6: http://www.terafulk.com/index.php?r=news&id=13
7: https://militaryleak.com/2022/03/25/indonesian-navy-tanker-ship-kri-bontang-conducted-ras-exercise-with-corvette-kri-usman-harun
![1](https://user-images.githubusercontent.com/99532490/167313115-345cbb0b-6308-419e-ae6e-32d310dbc3a7.png)
![2](https://user-images.githubusercontent.com/99532490/167313116-6e8f7715-8fe2-4ae0-83be-f1c56ccec799.png)
![3](https://user-images.githubusercontent.com/99532490/167313119-715c38d5-58c9-4e4a-9797-9a1b7a13aa74.png)

**Comment by Jkryos** [comment]
Added  DB3K 496.
