### ISSUE TITLE
Addition of JY-27A radar facility for PLA/Pakistan 

### ISSUE THREAD

**Issue by HyperGopher** [PygmalionOfCyprus/cmo-db-requests#114]
### DB Selector

CWDB

### Hypothetical

No

### Name

JY-27a

### Sensor Generation

Late 2010s

### Sensor Capabilities

Air Search, Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Active Electronically Scanned Array (AESA)

### Search/Track Frequencies

B Band (250-500 MHz) [Old P Band (VHF)] 60-100 cm

### Peak Power (W)

100-300?

### Comments

Newer solid state 3D VHF AESA radar of the PLA that was unveiled at an airshow in the past few years. Claimed to be able to detect stealth targets at a max range of 500km (270nm).

The antenna is smaller than the 55Zh6U “NEBO-U” but appears larger than the Nebo-SVU and Box Spring. 
![Screenshot (133)](https://user-images.githubusercontent.com/99625872/154002466-aa87527e-b519-4340-8d0e-83b5d3cd5d5e.png)

Nebo-SVU most recent upgrade has an estimated range of 420km for a 1m2 target at an altitude of 20km. Given this info,
the JY-27a may have an estimated range of 500km for a 1m2 target at the same altitude. See table below 
![Screenshot (134)](https://user-images.githubusercontent.com/99625872/154002447-d1a1647f-4112-417d-8429-e4d681512f12.png)

No available information about detailed specs or peak power. My guess is lower than the Nebo-U but higher than the Nebo-SVU (so between 100-300kW)

### Sources

https://aviationweek.com/defense-space/closer-look-stealth-part-4-counterstealth-radars-zhuhai-2016

https://www.radartutorial.eu/19.kartei/02.surv/karte029.en.html

https://www.globaltimes.cn/page/202104/1221629.shtml

https://www.popularmechanics.com/military/weapons/a23846/china-anti-stealth-radars-detect-f-22/

http://ausairpower.net/APA-Nebo-SVU-Analysis.html

https://www.globalsecurity.org/military/world/russia/nebo-svu.htm

**Comment by PygmalionOfCyprus** [comment]
Already added from the old tracker for 493.
