### ISSUE TITLE
Iran Shahin Class Minesweeper x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1143]
### DB Selector

DB3K

### Baseline

685

### Hypothetical

No

### Name

M 111 Shahin

### Class

Shahin Class

### Country

Iran

### Service

Navy

### In Commission

2021-

### Length (m)

33

### Beam (m)

11

### Draft (m)

1.8

### Standard Displacement (t)

180?

### Full Displacement (t)

200?

### Complement

??

### Primary Propulsion Type

Diesel

### Propulsion

??

### Fuel Capacity (kg)

??

### Flank Speed (kt)

15?

### Range (nm) at Speed (kt)

??

### Sensors

- 'DP1', high-precision minesweeper sonar system
- Generic Navigation radar
- Generic Surface search radar?

### Mounts

- OV long-range underwater remote control robotic minesweeper system
- Clearance divers

### Aircraft & Docking Facilities

- 1x RHIB

### Comms/Datalinks

Standard

### Ship Codes

Catamaran/Trimaran Multihull, Glass Reinforced Polyester (GRP) Construction

### Comments

ROV: With a length of 2.25 meters and a weight of 320 kg with a maximum speed of 11 km per hour, this device has a small sonar and is controlled by a light cable two thousand meters from the ship. The maximum depth for this device is 400 meter

### Sources

https://www.globalsecurity.org/military/world/iran/irins-saba.htm
http://www.hisutton.com/Iranian-Navy-Surface-Effect-Ship-Saba.html
https://www.navalnews.com/naval-news/2021/01/update-on-iranian-navy-surface-effect-ship-ses/
https://iranpress.com/content/55652/shahin-iran-first-homemade-minesweeper-ship

![Iran-Navys-Saba-minesweeper](https://user-images.githubusercontent.com/99632305/167504171-a75b55b2-eff8-4ff8-8db2-66137a53328f.jpg)
![irins-saba-image04](https://user-images.githubusercontent.com/99632305/167504196-68bea62b-791b-46f8-bd09-b36f4f9a2667.jpg)
![irins-saba-image01](https://user-images.githubusercontent.com/99632305/167504230-e1fb57a3-8fdd-4766-94d8-43f43338bf48.jpg)
![images](https://user-images.githubusercontent.com/99632305/167504328-9a7d2603-24a3-42c5-8505-6cd2d59fabc0.jpg)
![irins-saba-image03](https://user-images.githubusercontent.com/99632305/167504361-ee535f79-d225-4fbe-92df-df8c96ee3fa2.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. I didn't give it a RHIB davit because its RHIB appears to me more a rescue/lifeboat than a deployable vehicle. Also gave it the Hovercraft/SES flag instead of Catamaran/Trimaran, which will penalize it more DP-wise.

**Comment by cdnice55** [comment]
This was a tough one, I was surprised at how little is out there still about it. I guess with only one copy so far details are a bit hard to come by. Interesting concept.
