### ISSUE TITLE
Italy Modified San Giorgio Class LPD x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1146]
### DB Selector

DB3K

### DBID to Copy

853 DB3k

### Hypothetical

No

### Name

L 9894 San Giusto

### Country

Italy

### Service

Navy

### In Commission

1994-

### Sensors

- 1x GEM SPN-753 ARPA navigation
- 1x SMA SPS-702 surface search
- 1x AMS SPG-70(RTN-10x) f.c.

### Mounts

- 1x 76mm/62 Oto Melara Compact DP
- 2x twin 20mm/70cal Mk24 Oerlikon AA

### Other Changes

- 3x CH-47 Chinook or 3 x SH-3D Sea King or 5x AB-212
- Link 11 noted
- Modified version of the San Giorgio class, intended to act as training ship for the naval academy at Livorno in peacetime. Authorized in 1990 and ordered in 1991. Has a broader island superstructure than the earlier San Giorgio class, and the boats are stowed on a sponson to port to restore flight deck area, providing a taxiway between the landing area at the stern and a smaller one to port at the bow. Up to six medium-sized helicopters can be accommodated on deck. There is no bow vehicle ramp, but the side doors and ramps are larger than on the earlier units. Is able to carry 34 combat vehicles totaling up to 1200t below decks, and additional light vehicles can be carried on the flight deck. About 85t (80m³) of combat stores and 30t (80m³) of provisions can be accommodated. Landing craft include three 63t MTM-series medium landing craft in the 20.5x7.0m stern docking well and three 14t MTP-series personnel landing craft in davits to port, plus one 9t motor launch.

### Sources

http://www.navypedia.org/ships/italy/it_am_san_giusto.htm
https://en.wikipedia.org/wiki/Italian_ship_San_Giusto

![San_Giusto_L9894](https://user-images.githubusercontent.com/99632305/167538417-fc907b22-6252-4fd5-b3b7-70a39b1140f4.jpg)
![download](https://user-images.githubusercontent.com/99632305/167538459-e4ec8c5d-0b1f-497b-a080-5ea1e1f795fe.jpg)
![277_9894](https://user-images.githubusercontent.com/99632305/167538536-29e3dfd8-9dd9-43f2-a460-355076fac030.jpg)

**Comment by Jkryos** [comment]
Added DB3K 501.
