### ISSUE TITLE
Addition of SLC-7 radar facility to PLA

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#115]
### DB Selector

CWDB

### Hypothetical

No

### Name

SLC-7 L-Band AESA 

### Sensor Generation

Late 2010s

### Sensor Capabilities

Air Search, Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

AESA (Active Electronically Scanned Array)

### Search/Track Frequencies

D Band (1-2 GHz) [Old L Band] 15-30 cm

### Target Altitude (ft)

100000ft+?

### Comments

Recently unveiled UHF/L-Band radar system of the PLA. In active service since 2016 according to Deagel

Reported max range of 450km (~243nm) for a ballistic target of 0.05m2) and 300km for a ballistic target of 0.01m2 (no altitude info given)

No other detailed specs are known or available.

It appears to have a larger antenna than the Protivnik-GE, and similar to the L-Band component of the Nebo-M (RLM-D) but shorter max range.

"China’s SLC-7 anti-stealth radar is better in function than Israel’s EL/M-2080S multifunction phased array radar. It is able to tract more than 300km a ballistic target of 0.01 square meter radar cross section (RCS) and 450km, a ballistic target of 0.05 square meter RCS. Its maximum track altitude exceeds 30,000 meters. The radar’s high maneuverability enables it to move to a new site within 15 minutes." Source: (Tiananmenstremendousachievements.com)

### Sources

https://www.radartutorial.eu/19.kartei/02.surv/karte066.en.html

https://www.deagel.com/Sensor%20Systems/SLC-7/a003383

https://www.globaltimes.cn/page/202104/1221825.shtml

https://tiananmenstremendousachievements.wordpress.com/tag/slc-7/

**Comment by PygmalionOfCyprus** [comment]
DB3K is for 1980-future; CWDB is 1945-1980.

**Comment by HyperGopher** [comment]
Sorry!

**Comment by Jkryos** [comment]
Added DB3K 501.
