### ISSUE TITLE
FF 811 Incheon Datalinks

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1151]
### DB Selector

DB3K

### Affected DBID(s)

#2294, #3137

### Summary of Changes

According to Kang (2018) citing Defense Acquisition Program Administration's article and FFX-I CMS brochure, Incheon-class frigates (FFX-I) has Link-11 TDL. I think Link-11 should be added to FF 818 Incheon.

### Sources

![samsungthales_com_20110509_195741](https://user-images.githubusercontent.com/104970911/167659799-b1614254-4dcb-4bdc-8a56-7e116fb7f4df.jpg)
https://m.blog.naver.com/gold829921/60129703167

![20220505_153031](https://user-images.githubusercontent.com/104970911/167659901-e84703ee-d555-4b48-942a-b2b0b36f3a7a.jpg)
Kang, Moon-Seog, Design and Implementation of Effective Monitoring platform for Combat System (Master's thesis), Kumoh National Institute of Technology, 2018, p.4
http://nsl.kumoh.ac.kr/include/download.htm?menu_class=3&usr_file=20167001.pdf&file_size=1665206&sys_file=L3VzcjMvcHJvZmVzc29yL25zbGxhYi93d3dfaG9tZS9zdXBlcnZpc29yL1VwbG9hZEZpbGVzL2JvYXJkL2JpMDAwMS8xNTMyNjU4NTcwMTYwMDAwMDEucGRm&MOD_DIR=L3VzcjMvcHJvZmVzc29yL25zbGxhYi93d3dfaG9tZS9tb2R1bGVz

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
