### ISSUE TITLE
Ivory Coast Patra Class Patrol Boats x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1153]
### DB Selector

DB3K

### Baseline

325 DB3k

### Hypothetical

No

### Name

L'Ardent 

### Class

Patra Class

### Country

Ivory Coast

### Service

Navy

### In Commission

1978-2003

### Length (m)

40.7

### Beam (m)

5.9

### Draft (m)

1.55

### Standard Displacement (t)

125

### Full Displacement (t)

148

### Complement

19

### Primary Propulsion Type

Diesel

### Propulsion

2x AGO 195 V12CZ SHR diesels

### Flank Speed (kt)

26.3

### Range (nm) at Speed (kt)

750@20, 1750@10

### Sensors

- 1x Decca 1226 navigation radar

### Mounts

- 1x 40mm/70cal Bofors AA
- 1x 20mm/70cal Oerlikon Mk 10 AA
- 2x 7.62mm MG
- mid-1980s, both: - 2 x 3 SS-12M SSM

### Comms/Datalinks

- VHF/UHF radio

### Comments

- L'Ardent decommissioned 2003
- L'Intrepide non-operational by 1999, remains pierside, very poor condition

### Sources

Combat Fleets of the World, 16th Edition pg. 355
Janes, 2003-04
https://www.navypedia.org/ships/cote_divoire/cdi_cf_lardent.htm

![cdi_cf2](https://user-images.githubusercontent.com/99632305/167760096-bd133276-7b3e-4751-bf13-2622292d13fd.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495 in both its "normal" fit and w/ the SS.12(M)s. On that note, I also did a pass on the SS/AS.12s, adding more fidelity to the different variants.

**Comment by cdnice55** [comment]
That picture makes the ship look barely see worthy!
