### ISSUE TITLE
Ivory Coast Yuqin Class (Project 069) Landing Craft x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1154]
### DB Selector

DB3K

### DBID to Copy

1828 DB3k

### Hypothetical

No

### Name

Atchan

### Country

Ivory Coast

### Service

Navy

### In Commission

2003-

### Sensors

- N/A

### Mounts

- 1x twin 14.5mm/93cal AA

### Sources

Combat Fleets of the World, 16th Edition, pg. 355

**Comment by PygmalionOfCyprus** [comment]
I copied the 068 and made an 069 for China (w/ aluminum construction), then copied that to make Atchan for 495.
