### ISSUE TITLE
PSU-1-2 Passive Sonar (Yugoslavia - Una Class Midget Submarine)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1155]
### DB Selector

DB3K

### Hypothetical

No

### Name

PSU-1-2

### Sensor Generation

Early 1980s

### Range (nm)

13

### Sensor Capabilities

Surface Search, Submarine Search

### Search/Track Frequencies

LF Sonar (1-5 KHz, 3 KHz Center Frequency)

### Scan Interval (s)

15

### Comments

The PSU-1-2 digital passive sonar has a 64 beam cylindrical transducer. It presents data on the screen in true or relative bearing. It can autotrack 4 targets, 2 can be transferred to the fire control system and one to the plotting table. The oeprator classifies the target by listening on the audio channel.

> "The passive sonar can detect and automatically track multiple targets simultaneously with a 2 degree accuracy. It is not affected by its own noise interference up to a speed of 7 knots. Ranges depended on the hydrological conditions, size and type of target and ranged from 8 to 15 M. Larger submarines in low-noise driving mode were detected by the passive sonar at a distance of 3.5 to 4.5 M."

I guess 15M is 15 miles which would be 13NM.
Role: Passive Only Search & Track

### Sources

Slovenian source for the quote:
https://i.imgur.com/Mo6yOko.jpg

https://imgur.com/Lzkf8oE

https://imgur.com/GqUTgJi
https://www.mycity-military.com/imgs2/54436_62742094_100_2791.jpg

**Comment by nuk92** [comment]
The Una Class midget sub was allready requested a few months ago.

**Comment by PygmalionOfCyprus** [comment]
Added 495. Gave it a clean 15nm range since passive sonar ranging is fuzzy anyway.
