### ISSUE TITLE
Decca RM 1290A

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1157]
### DB Selector

DB3K

### Baseline

3779 - Decca 1220

### Hypothetical

No

### Name

Decca RM 1290A

### Sensor Generation

Early 1980s

### Range (nm)

20

### Sensor Capabilities

Surface Search, Range Information, Speed Information, Heading Information, Navigation Only

### Sensor Codes

Pulse-Only Radar

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

9,380,000,000

### Upper Frequency (Hz)

9,440,000,000

### Scan Interval (s)

2

### Horizontal Beamwidth (deg)

1.3

### Vertical Beamwidth (deg)

23.00

### Processing Gain/Loss (dB)

28.5

### Peak Power (W)

16000

### Pulse Width (ms)

0,0005

### Blind Time (ms)

0,00027

### PRF (Hz)

1300

### Comments

The radar has horizontal polarisation.

### Sources

page 4:
https://www.researchgate.net/figure/Specifications-of-the-RM-1290-marine-radar-HH-horizontally-RF-radiofrequency_tbl1_334369369

(Pulse width 0.5-10 us stated in the full text)

20nm range post by jordi:
http://www.portierramaryaire.com/foro/viewtopic.php?f=4&t=3987&st=0&sk=t&sd=a

**Comment by PygmalionOfCyprus** [comment]
Should this be an update to/copy of Sensor 1744?

**Comment by nuk92** [comment]
Oh I've completely missed it. Yes this should be an update of the Decca 1290 Master then. A whole bunch of ships is using it.
