### ISSUE TITLE
RDL-13/T ESM/Elint/RWR (used by Yugoslav modernised Heroj and Sava class subs)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1158]
### DB Selector

DB3K

### Baseline

6592 ALR-400FD

### Hypothetical

No

### Name

RDL-13/T [RWR/ESM]

### Sensor Generation

Early 1980s

### Range (nm)

500

### Sensor Capabilities

Air Search, Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit

### Sensor Codes

Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition]

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm, G Band (4-6 GHz) [Old C Band] 5-7.5 cm, H Band (6-8 GHz) [Old C Band] 3.75-5 cm, I Band (8-10 GHz) [Old X Band] 3-3.75 cm, J Band (10-20 GHz) [Old X Band] 1.5-3 cm

### Scan Interval (s)

20

### Comments

By classification I meant specific emitter ID, I can't find it though. This one was used by the modernised Heroj and Sava Class subs. Apparently the old Nakat was replaced by this one in fact. The RDL series is stated to be both an ESM and RWR system.

Therefore the RDL-13 would be a sensor group with the Elint entry and with a 120nm early 80s rwr entry.

### Sources

British Submarines use RDL-4 (2-18GHZ) stated as esm/elint system able to track numerous targets and automatic source id:

https://archive.org/stream/DTIC_ADA356017/DTIC_ADA356017_djvu.txt

Source from 1975 on RDL-1 and RDL-2:
https://www.google.de/url?sa=t&source=web&rct=j&url=https://apps.dtic.mil/sti/pdfs/ADA028210.pdf&ved=2ahUKEwinqIS5q9b3AhWGR_EDHYpNC8wQFnoECAoQAQ&usg=AOvVaw2Gc-Typxkcq9ZDvCnQnL7r

Museum Submarine P 821, post by Oricareb:
http://www.paluba.info/smf/index.php?topic=3870.1050

> "He also shows the radar detector indicator, on which 42 targets could be monitored at the same time, but he also notes that it was rarely used because it served only during the surface driving."

Closer view of the sensor masts: from the left, Snorkel, RDL, Decca, Zeiss Periscope
https://i.imgur.com/xQ4rKrO.jpg

Submariners talking about the radar detector which was rarely used in peace time but it wasn't completely thrown out after Nakat was replaced by the RDL-13/T, the ability to track radar sources on land is stated here:

post by karlo:
http://www.paluba.info/smf/index.php?topic=3870.msg306357;topicseen#msg306357
> As for the device itself, I think it would be interesting to say that it is better for work than a radar detector. However, every attack in the world and then first involved the destruction of radar stations, so a radar detector would still have its role and I believe that maybe that's why they didn't throw it out.

post by karlo:
http://www.paluba.info/smf/index.php?topic=3870.msg304490;topicseen#msg304490
> As for the radar detector operator, while I was on P, the device was somehow neglected, which was not very logical for me. other radars at twice the distance from the radar that irradiates it. So it is not clear to me whether this device was dropped because there is no operator. It is true that the radar detector can only be used at periscope depth and snorkeling, but when I was on P and that fell under scuba diving.

post by plavnik:
http://www.paluba.info/smf/index.php?topic=3870.msg304531;topicseen#msg304531
> True, the radar detector was poorly used. In my practice we may have used it a couple of times (no more than 5). A radar officer was in charge of serving. Serving was reduced to raising and lowering, and during the work itself he did not have to serve it, but only read the data on the control panel that was on the partition towards the command center.

**Comment by nuk92** [comment]
Close up picture of the RDL-13/T

https://imgur.com/a/4u3Q5Un

**Comment by PygmalionOfCyprus** [comment]
Added 495. The "ESM + RWR sensor group" is actually unnecessary; ESM doubles as RWR. So I just added it as a single ESM sensor.
