### ISSUE TITLE
Ivory Coast Batral-E Class LSM x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1159]
### DB Selector

DB3K

### DBID to Copy

1261

### Hypothetical

No

### Name

L'Elephant

### Country

Ivory Coast

### Service

Navy

### In Commission

1977-2000

### Sensors

- 1x DRBN-32 radar

### Mounts

- 2x single 40/60 Mk 7
- 2x single 81/12 mortars
- 2x single 12.7/90 mg

### Other Changes

None

### Sources

https://www.navypedia.org/ships/cote_divoire/cdi_ls_lelefant.htm

![cdi_ls4](https://user-images.githubusercontent.com/99632305/167759676-94c3b133-c25b-4c17-8ff0-b993aa8f853b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
