### ISSUE TITLE
Jamaica Cornwall [Damen Stan Patrol 4207]

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1160]
### DB Selector

DB3K

### Affected DBID(s)

3578

### Summary of Changes

Ships joined the Defence Force Coast Guard in 2005 (Cornwall) and 2006 (Surrey and Middlesex) not 2021. 

### Sources

Combat Fleets of the World, 16th Edition, page 356.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
