### ISSUE TITLE
Jamaica Guardian Class x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1161]
### DB Selector

DB3K

### DBID to Copy

2961

### Hypothetical

No

### Name

P 8 Paul Bogle

### Country

Jamaica

### Service

Coast Guard

### In Commission

1985-

### Sensors

- 1x Furuno 2400 navigation

### Mounts

- 2x single 12.7mm M2 mg

### Sources

Combat Fleets of the World, 16th edition, page 356

**Comment by PygmalionOfCyprus** [comment]
Added 495. So, the "Guardian Class" is Jamaica's domestic designation for the 65ft Swift boats?

**Comment by cdnice55** [comment]
That is what it seems to be yes. I did a visual comparison in Jane's and Combat Fleets of the world and the websites and they look identical to me and the dimensions fit.
