### ISSUE TITLE
Jamaica Dauntless Class patrol Boats x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1162]
### DB Selector

DB3K

### DBID to Copy

3451 DB3k

### Hypothetical

No

### Name

CG 121

### Country

Jamaica

### Service

Coast Guard

### In Commission

1992-

### Sensors

- 1x Raytheon R40x nav.

### Mounts

- 2x single 7.62mm/90 mg

### Sources

Combat Fleets of the World, 16th Edition, page 35
https://www.navypedia.org/ships/jamaica/jam_cg_cg121.htm

![jam_cg10](https://user-images.githubusercontent.com/99632305/167761521-0d90f2e2-7daf-49b9-a627-83d1fdf17c04.jpg)
7

**Comment by PygmalionOfCyprus** [comment]
Added 495. Now _this_ is the sort of major surface combatant that wins wars.

**Comment by cdnice55** [comment]
Those slingshots can leave quite the welt you know..... :)
