### ISSUE TITLE
Jamaica Point Class x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1163]
### DB Selector

DB3K

### DBID to Copy

2729 DB3k

### Hypothetical

No

### Name

CG 251 Savannnah Point

### Country

Jamaica

### Service

Coast Guard

### In Commission

1999-2008

### Sensors

- No changes

### Mounts

- No changes

### Sources

https://www.navypedia.org/ships/jamaica/jam_cg_savannah_point.htm

![jam_cg11](https://user-images.githubusercontent.com/99632305/167761962-c4abc550-1be4-4166-a01f-f6ce552b81b7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
