### ISSUE TITLE
Brazil - R99B (MX-15 FLIR UPDATE)

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#1164]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2103

### Hypothetical

No

### Name

EMB-145 RS [R-99B] - 2021

### Country

Brazil

### Service

Air Force

### In Commission

2020 - Present

### Sensors

1 x Skyball Sensor replaced by MX-15 FLIR Sensor.

### Other Changes

Replared FLIR by Wescam MX-15

Sensor 5434 in DB ID

### Sources

https://www.fab.mil.br/noticias/mostra/37717/OPERA%C3%87%C3%83O%20SAMA%C3%9AMA%20-%20R-99%20utiliza%20sensor%20modernizado%20em%20Opera%C3%A7%C3%A3o%20no%20norte%20do%20Pa%C3%ADs

https://aeroin.net/o-diferente-embraer-r-99-estreia-novo-sensor-em-operacao-no-norte-do-pais/

https://www.l3harris.com/all-capabilities/wescam-mx-15-air-surveillance-and-reconnaissance

**Comment by PygmalionOfCyprus** [comment]
Added 495.
