### ISSUE TITLE
KDX-2/KDX-2 Mod Datalinks

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1165]
### DB Selector

DB3K

### Affected DBID(s)

885, 2163, 2165, 2166, 2167, 2385

### Summary of Changes

Link-11 should be added to KDX-2 and KDX-2 Mod.

According to Jane's Fighting Ships 2009-2010, KDX-2 has Link-11 TDL. Also, a research report from Republic of Korea Ministry of National Defense mentioned that "ships equipped with KNTDS use Link-11A (TADIL-A) to send tactical information to fleet."

![20220511_193205](https://user-images.githubusercontent.com/104970911/167829838-8850cbba-31f3-4fb1-a686-ae4f6bab3a81.jpg)

And KDCOM-II CMS of KDX-2 includes KNTDS (Korean Naval Tactical Data System).

### Sources

![20220511_050658](https://user-images.githubusercontent.com/104970911/167830040-2a5fb368-072b-4255-839a-5d253a1f70a6.jpg)
Jane's Fighting Ships 2009-2010, p.461

![20220511_195257](https://user-images.githubusercontent.com/104970911/167833258-adbaffd3-e304-4f99-896b-f7993ed520f7.jpg)
Republic of Korea Ministry of National Defense, Research Report on Naval Command and Control System Performance Improvement and Development, 2012, p.72
http://dl.nanet.go.kr/law/SearchDetailView.do?cn=MONO1201314480#none

![Popup_img_03KDX-1](https://user-images.githubusercontent.com/104970911/167830703-524b1424-2d75-4cfd-a0de-c2161afbbea9.jpg)
http://pds15.cafe.daum.net/download.php?grpid=SO0&fldid=5q1&dataid=382&fileid=1&regdt=20070118002556&disk=20&grpcode=NTDS&dncnt=N&.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
