### ISSUE TITLE
Iran Pluto Plus MCM ROV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1166]
### DB Selector

DB3K

### DBID to Copy

submarine/486/DB3K

### Hypothetical

No

### Name

Pluto Plus ROV

### Country

Iran

### Service

Navy

### In Commission

2021-Present

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

First sighted via OSINT in 2021 on the new Saba/Shahin SES MCM vessel. Possibly a locally produced copy.

### Sources

http://www.hisutton.com/Iran-Pluto-Plus-Minehunting-ROV.html

![image](https://user-images.githubusercontent.com/99599482/167855016-d80c1c05-57b0-47b6-b4c9-af0694200593.png)
![image](https://user-images.githubusercontent.com/99599482/167855052-67490921-cd69-489f-99eb-9444b236cb5b.png)
![image](https://user-images.githubusercontent.com/99599482/167855091-69fc57c2-807d-43db-a03d-697119b9130c.png)
![image](https://user-images.githubusercontent.com/99599482/167855120-cb1ef811-92ec-4d64-8379-ab1bd9130762.png)

**Comment by tbrandon517** [comment]
Related to request #1143

**Comment by PygmalionOfCyprus** [comment]
Added 495.
