### ISSUE TITLE
Brazil - EC.725 Caracal - Air Force

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#1167]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2953

### Hypothetical

No

### Name

EC.725 Caracal [H-36, Super Cougar] - 2015, 16x

### Country

Brazil

### Service

Air Force

### In Commission

2015 - Present

### Sources

https://www.flickr.com/photos/portalfab/albums/72157627059353056

https://www.fab.mil.br/noticias/mostra/32663/REAPARELHAMENTO%20-%20Esquadr%C3%A3o%20Puma%20recebe%20aeronave%20H-36%20Caracal,%20o%20FAB%208515

https://www.fab.mil.br/noticias/mostra/37257/ANIVERS%C3%81RIO%20-%20Esquadr%C3%A3o%20Falc%C3%A3o%20comemora%20dez%20anos%20de%20implanta%C3%A7%C3%A3o%20do%20H-36%20Caracal%20na%20FAB

**Comment by PygmalionOfCyprus** [comment]
Added 495.
