### ISSUE TITLE
Brazil - H60L Blackhawk - Air Force

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#1168]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2952

### Hypothetical

No

### Name

H-60L Blackhawk

### Country

Brazil

### Service

Air Force

### In Commission

2006 - Present

### Sources

https://www.flickr.com/photos/portalfab/albums/72157626934798745

https://www.helis.com/database/modelorg/1020/

https://www.fab.mil.br/noticias/mostra/22185/OPERACIONAL%20-%20Esquadr%C3%A3o%20Harpia%20treina%20resgate%20em%20combate%20no%20sul%20do%20Par%C3%A1

https://www.fab.mil.br/noticias/mostra/30665/ASAS%20ROTATIVAS%20-%20Helic%C3%B3ptero%20Black%20Hawk%20chega%20a%2030%20mil%20horas%20de%20voo%20na%20FAB

**Comment by PygmalionOfCyprus** [comment]
Added 495.
