### ISSUE TITLE
ELT-156, ELT-400 series update, frequency bands

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1169]
### DB Selector

DB3K

### Affected DBID(s)

904, 903, 902, 901, 4325

### Summary of Changes

- ELT-457: 2-3.9 GHz (E,F Band)
- ELT-458: 3.9-7.5 GHz (G,H Band)
- ELT-459: 7.5-20 GHz (H,I,J Band)
- ELT-460: 20-60 GHz (K,L Band)

- ELT-156, 2-18 GHz (E,F,G,H,I,J Band), specific emitter id (for all ELT-156 versions), early 80s technology

### Sources

Actually I wanted to update my ELT-400 request from a few weeks ago but I saw that it was recently closed, now that I found the only detailed source for these pods that went down the memory hole :sweat_smile:

Orao - pogled iz jugoslovenskog ugla, Aleksandar Radić, ISBN: 9788633503563, page 144

frequency bands, ELT-460 is not included but the EW directory states that the series covers the K and L bands too, 460 fills that gap. (There's a typo in the 459 frequencies):

https://imgur.com/0aoWWEH
https://www.mycity-military.com/imgs4/476830_54689796_79915967-EW-Directory-1990-005.jpg

ELT-156 has a library ("biblioteka") of 90 different parameter sets for different radars. It determines the bearing and identifies them. The ELT-156 forms a system with the jammer pods of the ECM J-22 Orao.

https://imgur.com/XpzkRJ7

**Comment by PygmalionOfCyprus** [comment]
Updated 495. Great work on all this stuff, by the way. I love this sort of obscure research; it's  exactly what I hoped for when I created the Github.
