### ISSUE TITLE
Add 271 Gagah Samudera Training ship/Offshore patrol vessel

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#117]
### DB Selector

DB3K

### Hypothetical

No

### Name

271 Gagah Samudera

### Class

Gagah Samudera-Class

### Country

Malaysia

### Service

Navy

### In Commission

2018

### Length (m)

76

### Beam (m)

11

### Draft (m)

3.15

### Standard Displacement (t)

1270

### Complement

45

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN 9L 27/38 Diesel engines

### Flank Speed (kt)

22

### Range (nm) at Speed (kt)

2500nm @ 12kts

### Sensors

1x Kelvin Hughes SharpEye
1x EO sensor

### Mounts

1x MSI DS30M
2x Browning 12.7 mm machine guns

### Aircraft & Docking Facilities

2x Davits for 7m RHIB
1x Pad for Medium Helicopter

### Comms/Datalinks

VHF/UHF Radio

### Ship Codes

Dual or Triple Stabilizers

### Comments

The Gagah Samudera is a class of training ships of the Royal Malaysian Navy The two ships were built jointly by Malaysia and South Korea under a shared development programme, with one ship built in South Korea and the other in Malaysia, The ships, named KD Gagah Samudera and KD Teguh Samudera are currently in service with Royal Malaysian Navy. The ship commissioned in 2018 and mainly served as training ship but can also served as an OPV if necessary. 

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2018/april-2018-navy-naval-defense-news/6170-royal-malaysian-navy-commissioned-two-naval-training-ships.html
https://www.malaysiandefence.com/teguh-and-gagah-samudera-commissioned/
https://en.wikipedia.org/wiki/Gagah_Samudera_Class
https://www.thestar.com.my/news/nation/2018/04/26/navy-adds-two-new-vessels-on-voyage-towards-a-world-class-fleet
https://sediaberkorban.wordpress.com/2013/05/22/kapal-latihan-tldm-kd-gagah-samudera/
![image](https://user-images.githubusercontent.com/99646926/154050895-a8bd3230-7741-4ec8-b348-239214796d38.png)
![image](https://user-images.githubusercontent.com/99646926/154051075-f5ae9068-3e10-434d-8150-11bdf109cbaa.png)
![image](https://user-images.githubusercontent.com/99646926/154051222-75a4e4c3-2b27-447b-af66-0a2b6d665386.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
