### ISSUE TITLE
ELT/457-460 OECM pods

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1170]
### DB Selector

DB3K

### Baseline

ELT-555 DECM Pod

### Hypothetical

No

### Name

ELT-457 OECM pod, ELT-458 OECM pod, ELT-459 OECM pod, ELT-460 OECM pod

### Length (m)

3.1

### Width/Span (m)

-

### Diameter (m)

0.35

### Weight (kg)

150

### Range (nm)

-

### Warhead

-

### Sensors

- ELT-457
- ELT-458
- ELT-459
- ELT460

### Comments

multiple of these can be carried by aircraft to jam different frequency bands

### Sources

https://imgur.com/CSWJYuk

**Comment by PygmalionOfCyprus** [comment]
Added 495 (+assoc. weapon records).
