### ISSUE TITLE
Japan Coast Guard Mizuho Class x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1173]
### DB Selector

DB3K

### Baseline

3026

### Hypothetical

No

### Name

PLH 21 Mizuho

### Class

Mizuho Class

### Country

Japan

### Service

Coast Guard

### In Commission

1986-

### Length (m)

130

### Beam (m)

15.5

### Draft (m)

5.25

### Standard Displacement (t)

4960

### Full Displacement (t)

5317

### Complement

130

### Primary Propulsion Type

Diesel

### Propulsion

2x IHI-SEMT-Pielstick 16 PC2.5 V400

### Flank Speed (kt)

23.3

### Range (nm) at Speed (kt)

8500@22

### Sensors

- 1x JMS 1596 navigation radar
- 1x JMA 3000 helicopter control
- 1x JMA 8303 surface search radar

### Mounts

- 1x 35mm/90 Oerlikon AA
- 1x 20mm JM-61-MB Sea Vulcan gatling AA

### Aircraft & Docking Facilities

- 1x landing pad
- 2x hangar for Kawasaki-Bell 212/412 Helo's
- 2x RHIBS

### Comms/Datalinks

Same as Shikishima

### Ship Codes

Passive or Single Stabilizers

### Sources

https://en.wikipedia.org/wiki/Mizuho-class_patrol_vessel
Combat Fleets of the World, 16th Edition page 383

![Japan_Coast_Guard_vessel_Yashima_(PLH_22)](https://user-images.githubusercontent.com/99632305/168151669-75888cf4-b3fc-4250-a6f0-3e22f7d269c2.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
