### ISSUE TITLE
Japan Coast Guard Tsugaru Class x7

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1174]
### DB Selector

DB3K

### Baseline

3026

### Hypothetical

No

### Name

PLH 02 Tsugaru Class

### Class

Tsugaru Class

### Country

Japan

### Service

Coast Guard

### In Commission

1979-

### Length (m)

105.4

### Beam (m)

14.6

### Draft (m)

4.85

### Standard Displacement (t)

3730

### Full Displacement (t)

4037

### Empty Displacement (t)

3221

### Complement

56+15

### Primary Propulsion Type

Diesel

### Propulsion

2x SEMT-Pielstick 12 PC2.5 V400

### Fuel Capacity (kg)

864tons

### Flank Speed (kt)

21.5

### Range (nm) at Speed (kt)

5700@18

### Sensors

- 1x JMA 1596 navigation
- 1x JMA 1576 surface search
- 1x JMA 3000 helicopter control

### Mounts

- 1x 35mm 90-cal Oerlikon AA
- 1x 20mm 70-cal Oerlikon AA

### Aircraft & Docking Facilities

- 2x davits for RHIBS
- 1x landing pad
- 1x hangar for Kawasaki-bell 212/412

### Comms/Datalinks

Same

### Ship Codes

Passive or Single Stabilizers

### Comments

These ships are operated as command ships of each Regional Coast Guard Headquarters flotilla or task force, and conducting many search and rescue operations.

In the Incident of Suspicious Boats off the Coast of Noto Peninsula, Chikuzen acted as a forward operating base of the Special Security Team. She also fired warning shots by her JM61-M.

With their high-endurance and aviation patrol capability, these ships also attend to overseas dispatch including counter-piracy operations in the Strait of Malacca.

### Sources

https://en.wikipedia.org/wiki/Tsugaru-class_patrol_vessel
Combat Fleets of the World, 16th Edition page 383-4

![300px-JCG_Settsu(PLH-07)_right_front_view_at_Port_of_Kobe_July_22,_2017_03](https://user-images.githubusercontent.com/99632305/168155151-5a283544-82e8-43bd-8835-958506ee6daf.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495 in initial 40mm + 20mm Oerlikon variant and later 35mm + JM61-M variant.
