### ISSUE TITLE
Japan Coast Guard Ryukyu Class (Modified Tsugaru) x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1175]
### DB Selector

DB3K

### Baseline

3026

### Hypothetical

No

### Name

PLH 09 Ryukyu

### Class

Ryukyu Class (Modified Tsugaru)

### Country

Japan

### Service

Coast Guard

### In Commission

2000-

### Length (m)

105

### Beam (m)

15

### Draft (m)

4.85

### Standard Displacement (t)

3100

### Full Displacement (t)

3900

### Complement

56+15

### Primary Propulsion Type

Diesel

### Propulsion

2x SEMT-Pielstick 12 PC2.5 V400

### Fuel Capacity (kg)

864tons

### Flank Speed (kt)

22

### Range (nm) at Speed (kt)

5700@18

### Sensors

- 1x JMA 1596 navigation
- 1x JMA 1576 surface search
- 1x JMA 3000 helicopter control

### Mounts

- 1x 35mm/90
- 1x 20mm JM-61 MB Sea Vulcan gatling AA (RWS)

### Aircraft & Docking Facilities

- 2x davits for RHIBS
- 1x landing pad
- 1x hangar for Kawasaki-Bell 212/412

### Comms/Datalinks

Same + Marisat UHF SATCOM

### Ship Codes

Passive or Single Stabilizers

### Comments

Intended to operate 100 n.m. or more out to sea. Design is modernized Tsugaru with finer hull lines and bulbous forefoot to the bow. 

### Sources

https://en.wikipedia.org/wiki/Tsugaru-class_patrol_vessel
Combat Fleets of the World, 16th edition, page 383

![download](https://user-images.githubusercontent.com/99632305/168157688-7660160d-b3bc-4267-9a15-0a54b2071730.jpg)
![download](https://user-images.githubusercontent.com/99632305/168157706-8f1a0ec3-2f05-41fd-9cb3-a4c90545d6e9.jpg)
![9197167](https://user-images.githubusercontent.com/99632305/168157720-6a967d98-f9cc-4ff2-9431-cfb949435a07.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
