### ISSUE TITLE
Japan Coast Guard Souya Class x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1176]
### DB Selector

DB3K

### Baseline

3026

### Hypothetical

No

### Name

PLH 01 Souya

### Class

Souya Class

### Country

Japan

### Service

Coast Guard

### In Commission

1978-

### Length (m)

98.6

### Beam (m)

15.6

### Draft (m)

5.2

### Standard Displacement (t)

3562

### Full Displacement (t)

4089

### Empty Displacement (t)

3139

### Complement

71

### Primary Propulsion Type

Diesel

### Propulsion

2x Nippon Kokan-Pielstick 12 PC 2.5 V400

### Fuel Capacity (kg)

650tons

### Flank Speed (kt)

21

### Range (nm) at Speed (kt)

5700@18

### Sensors

- 2x navigation radar (one x and one s band) JMS 1596 is one of them
- 1x JMA 8303 surf. search
- 1x JMA 3000 helicopter control

### Mounts

- 1x 40mm/60 Bofors AA
- 1x 20mm/70cal Oerlikon AA

### Aircraft & Docking Facilities

- 2x davits for RHIBS
- 1x pad for heli
- 1x hangar for Kawsaki-Bell 212/412/Sikorsky 76C++

### Comms/Datalinks

Same as others

### Ship Codes

Passive or Single Stabilizers

### Comments

Icebreaking bow

### Sources

https://ja.wikipedia.org/wiki/%E3%81%9D%E3%81%86%E3%82%84_(%E5%B7%A1%E8%A6%96%E8%88%B9)
Combat Fleets of the World, 16th Edition, page 384

![JapanCoastGuard-PLH01_SOUYA](https://user-images.githubusercontent.com/99632305/168167115-c5dcc605-7d97-429b-9422-1fff5cc201d4.jpg)
![plh01souyacrs](https://user-images.githubusercontent.com/99632305/168167162-beb669f6-75ef-4df0-892d-5f7278638a52.jpg)
![maxresdefault](https://user-images.githubusercontent.com/99632305/168167200-f2d88b2a-8e65-4bfe-9338-804561260a45.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
