### ISSUE TITLE
Japan Coast Guard Ojika Class x7

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1177]
### DB Selector

DB3K

### Hypothetical

No

### Name

PL 02 Erimo

### Class

Ojika Class

### Country

Japan

### Service

Coast Guard

### In Commission

1991-

### Length (m)

91.4

### Beam (m)

11

### Draft (m)

3.5

### Standard Displacement (t)

1268

### Full Displacement (t)

2006

### Empty Displacement (t)

1883

### Complement

38

### Primary Propulsion Type

Diesel

### Propulsion

2x Fuji S540B Diesels

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

4400@19

### Sensors

- 1x JMA 1596 navigation radar
- 1x surface search radar

### Mounts

- 1x KDC 35mm gun
- 1x 20mm JM-61-MB Sea Vulcan gatling AA

### Aircraft & Docking Facilities

- 1x pad for Super Puma
- 2x davits for 7m RHIBs

### Sources

https://en.wikipedia.org/wiki/Ojika-class_patrol_vessel
Combat Fleets of the World, 16th Edition, page 385

![Japan_Coast_Guard_PL04](https://user-images.githubusercontent.com/99632305/168175746-14054043-cdbe-42b5-929b-13bbb0987df8.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
