### ISSUE TITLE
Belgium - F 930 Leopold I [Karel Doorman] - 2018, Harpoon Block 2

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1178]
### DB Selector

DB3K

### DBID to Copy

2737

### Hypothetical

No

### Name

F 930 Leopold I [Karel Doorman]

### Country

Belgium

### Service

Navy

### In Commission

2018 ?

### Mounts

Harpoon is now _ID 589 RGM-84L Harpoon II_
I would recommend datamount.ID=739 (Mk141 "2002, 4x RGM-84L")

### Sources

_Procured in late 2017 ?_
https://govtribe.com/opportunity/federal-contract-opportunity/procurement-of-harpoon-integrated-logistics-support-ils-for-missile-upgrade-n0001916p2pma2010123-2

Note : However, I couldn't find a trace neither in the Federal Register, nor in the SIRPI database. Probably second hand from Luxembourg or Liechtenstein.😉

_Tested in 2022_ (Gorgeous pics, by the way. Looking your way, Dwight)
https://www.navaltoday.com/2022/05/12/watch-belgian-navys-frigate-leopold-i-fires-harpoon-missile/

**Comment by PygmalionOfCyprus** [comment]
Added 495.

**Comment by claudejdev** [comment]
Late to the party here.

Mk54 is the current lightweight torpedo :
> The Belgian Navy is phasing out its inventory of MK 46 torpedoes. The MK 54 will give them the ability to engage submarines from its fleet of NH-90 helicopters and the new generation of Multi-Mission Frigates. Belgium will have no difficulty absorbing this equipment into its armed forces.
https://www.federalregister.gov/documents/2020/08/26/2020-18791/arms-sales-notification

_Given that the NH90 are not carrying torpedoes, it's for the frigates._

From SIPRI Arms Transfers Database, it's getting RIM-162 ESSM Block-2. [Trade-Register-2020-2021.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8711995/Trade-Register-2020-2021.pdf)

From Jane's Fighting Ships 21 : Thales was awarded a contract in July '20 to update the Scout radar to its Mk.3 version.
(The picture is blurred AF. Had too much coffee.)
![IMG_20220516_142217 (2)](https://user-images.githubusercontent.com/35732829/168924442-645f2ac8-33da-4b1b-8406-70f0736c2814.jpg)
