### ISSUE TITLE
France - SNECMA M88-2/3/4 (New source)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1179]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

**DataPropulsion**

| #    | Name                     |
|------|--------------------------|
269 | 2x SNECMA M88-2/3/4
2405 | 2x SNECMA M88-2/3/4
- ThrustPerEngineMilitary = 4967.0
- ThrustPerEngineAfterburner = 9202.0
- SFCMilitary = 0.78
- SFCAfterburner = 1.75

### Sources

Daly, Mark. 2015. IHS Jane's aero-engines: 2015-2016.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
