### ISSUE TITLE
Japan Coast Guard Hateruma Class x9

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1180]
### DB Selector

DB3K

### Hypothetical

No

### Name

PL 61 Hateruma

### Class

Hateruma Class

### Country

Japan

### Service

Coast Guard

### In Commission

2008-

### Length (m)

89

### Beam (m)

11

### Draft (m)

4.0

### Standard Displacement (t)

1350

### Full Displacement (t)

1350

### Complement

30

### Primary Propulsion Type

Diesel

### Propulsion

4 diesels

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

??

### Sensors

- 1x navigation radar
- 1x surface search radar

### Mounts

- 1x Mk44 Bushmaster Mk II 30mm gun with Optical FCS

### Aircraft & Docking Facilities

- 1x pad for helicopter (able to refuel)
- no hangar

### Ship Codes

Passive or Single Stabilizers

### Sources

https://en.wikipedia.org/wiki/Hateruma-class_patrol_vessel
Combat Fleets of the World, 16th Edition, page 384-5

![300px-JCG_PL61_hateruma](https://user-images.githubusercontent.com/99632305/168177102-e0d3eb86-5859-4d00-89e7-5266552638aa.jpg)
![250px-Plhakata](https://user-images.githubusercontent.com/99632305/168198768-553a344b-7a24-41cf-82ef-e2cc4be53b5b.jpg)
![250px-JCG-Ishigaki-PL62](https://user-images.githubusercontent.com/99632305/168198780-54a3fd68-905a-4cb3-b8ac-a7b8d871c5a4.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.

**Comment by PygmalionOfCyprus** [comment]
...aaaaaaaand I just realized that it's already in the DB as Ship 3027. 😢

**Comment by cdnice55** [comment]
Sorry, thought I had checked for all of them. I feel shame.......

**Comment by PygmalionOfCyprus** [comment]
Not entirely your fault, it was spelled wrong. It was also very incorrect in other ways, so I overwrote it with the new version. Will be better now!
