### ISSUE TITLE
Japan Coast Guard Hida Class x3

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1181]
### DB Selector

DB3K

### Hypothetical

No

### Name

PL 51 Hida

### Class

Hida Class

### Country

Japan

### Service

Coast Guard

### In Commission

2006-

### Length (m)

95

### Beam (m)

12.6

### Draft (m)

4.0

### Standard Displacement (t)

1800

### Full Displacement (t)

2000

### Complement

??

### Primary Propulsion Type

Diesel

### Propulsion

4x diesels

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

??

### Sensors

- 2x Navigation radar

### Mounts

- 1× Bofors 40 mm L/70 gun with optical FCS
- 1× JM61 20 mm gun with RFS

### Aircraft & Docking Facilities

- 2x davits for RHIBS
- 1x pad for helicopter (Sea King/Super Puma size)

### Comms/Datalinks

Add SATCOM

### Comments

The vessels carry a [Bofors 40 mm](https://en.wikipedia.org/wiki/Bofors_40_mm_Automatic_Gun_L/70) L/70 [autocannon](https://en.wikipedia.org/wiki/Autocannon) with a laser-optical [fire-control system](https://en.wikipedia.org/wiki/Fire-control_system), and are able to safely deal with heavily armed spy boats of the DPRK which intrude into Japanese waters. The hull of this class is [bulletproof](https://en.wikipedia.org/wiki/Bulletproof) in cases of close-range firefights using small arms.

Ships of this class are among the leading vessels of flotillas intended for spy boat interception. With the helicopter deck of this class, a [Special Security Team](https://en.wikipedia.org/wiki/Special_Security_Team) can arrive at the scene aboard [Eurocopter EC225](https://en.wikipedia.org/wiki/Eurocopter_EC225) helicopters. The [broadband](https://en.wikipedia.org/wiki/Broadband) [SATCOM](https://en.wikipedia.org/wiki/Communications_satellite) system of this class can relay video data from helicopters to the ground station or the HQ of the JCG. This class is equipped with a [LIDAR](https://en.wikipedia.org/wiki/LIDAR) system to acquire targets with high accuracy, and at the same time, this system enables them to perform [search and rescue](https://en.wikipedia.org/wiki/Search_and_rescue) mission more safely.

### Sources

https://en.wikipedia.org/wiki/Hida-class_patrol_vessel
Combat Fleets of the World, 16th ediition, page 385

![300px-Japan_Coast_Guard_PL51_Hida](https://user-images.githubusercontent.com/99632305/168203139-ec468102-d346-4636-b127-ec2446c32ae2.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
