### ISSUE TITLE
France - M53-P2 (New source)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1182]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

**DataPropulsion**

| # | Name |
|---|----|
1461 | 1x M53-P2
1972 | 1x M53-P2
2407 | 1x M53-P2
- ThrustPerEngineAfterburner = 9700.0

### Sources

Beaumont, Hervé. 2021. Mirage 2000: l'histoire dans l'armée de l'air de 1974 à nos jours. Antony: ETAI.
Daly, Mark. 2015. IHS Jane's aero-engines: 2015-2016.

**Comment by PygmalionOfCyprus** [comment]
I already have the AB thrust at 9700 for all three of those engines, did we handle this with the earlier request?

**Comment by claudejdev** [comment]
Well, ID 1971 was at 9700. Maybe you did go ahead and normalized the whole
thing. Anyway, well done. ;)

Le ven. 13 mai 2022 à 06:22, Ethan Hermanson ***@***.***> a
écrit :
