### ISSUE TITLE
Japan Coast Guard Nojima Class x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1183]
### DB Selector

DB3K

### Hypothetical

No

### Name

PL 01 Oki

### Class

Najima Class

### Country

Japan

### Service

Coast Guard

### In Commission

1989-

### Length (m)

85

### Beam (m)

10.5

### Draft (m)

3.5

### Standard Displacement (t)

993

### Full Displacement (t)

1500

### Empty Displacement (t)

820

### Complement

39

### Primary Propulsion Type

Diesel

### Propulsion

2x Fuji S540B Diesels

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

4400@19

### Sensors

- 2x JMA 1596 Navigation radar
- 1x side scan HF sonar

### Mounts

- 1x 20mm JM-61-MB Sea Vulcan gatling AA

### Aircraft & Docking Facilities

- 2x davits for RHIBS
- 1x pad for helicopter (medium)

### Comms/Datalinks

Add UHF SATCOM

### Ship Codes

Passive or Single Stabilizers

### Sources

Combat Fleets of the World, 16th edition, page 385

![download](https://user-images.githubusercontent.com/99632305/168204167-d996db1a-a3b1-47d1-a27a-94811985a205.jpg)
![download](https://user-images.githubusercontent.com/99632305/168204175-9cac231f-4979-42aa-9aee-74911a0c8125.jpg)
![download](https://user-images.githubusercontent.com/99632305/168204292-237370da-25e6-4c68-884c-c55eeda2a524.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Found a little more info on JP Wikipedia.
