### ISSUE TITLE
Japan Coast Guard Shiretoko Class x28

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1184]
### DB Selector

DB3K

### Hypothetical

No

### Name

PL 101 Shiretoko

### Class

Shiretoko Class

### Country

Japan

### Service

Coast Guard

### In Commission

1978-2016

### Length (m)

77.8

### Beam (m)

9.6

### Draft (m)

3.42

### Standard Displacement (t)

974

### Full Displacement (t)

1360

### Complement

41

### Primary Propulsion Type

Diesel

### Propulsion

2x Niigata 8MA 40

### Fuel Capacity (kg)

191tons

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

4406@17

### Sensors

- 1x JMA 1596 navigation radar
- 1x JMA 1576 surface search

### Mounts

- 1x Oerlikon KDC 35mm
- 1x JM61-M 20mm

### Aircraft & Docking Facilities

- 2x davits for RHIBS

### Sources

Combat Fleets of the World, 16th edition page 385-6
https://en.wikipedia.org/wiki/Shiretoko-class_patrol_vessel

![300px-PL101_Shiretoko](https://user-images.githubusercontent.com/99632305/168205091-c12e1ce6-01f6-4e40-b562-ec7a6ecb79e6.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
