### ISSUE TITLE
North Korea Sang-O II (K-300) Class x6

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1186]
### DB Selector

DB3K

### Baseline

200

### Hypothetical

No

### Name

Sang-O II

### Class

Sang-O II (K-300) Class

### Country

North Korea

### Service

Navy

### In Commission

2011-

### Length (m)

39

### Beam (m)

3.8

### Draft (m)

3.5

### Standard Displacement (t)

300

### Submerged Displacement (t)

340

### Max Depth (m)

-180

### Complement

25

### Primary Propulsion Type

Diesel/Electric

### Propulsion

1 diesel-generator / 1 electric motor 300hp

### Flank Speed at Surface (kt)

7

### Flank Speed Submerged (kt)

13

### Range (nm) at Speed (kt)

2700@8

### Sensors

- Furuno radar
- Feniks-M sonar

### Mounts

- 4x 533mm TT (4 CHT-02D) or 16 mines

### Magazines

?

### sub Codes

Snorkel

### Comments

Lengthened version of Sang-O class with improved machinery.

### Sources

Combat Fleets of the World, 16th Edition, page 401
http://www.navypedia.org/ships/korea_north/kon_ss_sango2.htm

**Comment by PygmalionOfCyprus** [comment]
Added 495. Is K-300 the class type for both the Sang-Os or just the Sang-O II?

**Comment by cdnice55** [comment]
Yes, you are correct, the K-300 is listed in CFW. There is no such notation for the Sang-O listed.
