### ISSUE TITLE
A/A: APKWS IIA- Sensors do not make sense/no weapon director available to illuminate target

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#1187]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3661

### Description of Problem

The guidance type says it uses passive IR guidance, but the properties say it uses terminal illumination. This weapon has an IIR Seeker and a laser **designator** (6015).  The latter sensor does not makes sense; I suspect that it was supposed to be a laser **seeker** or only the IIR was intended? However, I have not seen any info that the real weapon uses anything other that SALH- like its ground attack counterpart. 

It seems that any launch platform that lacks Sensor 6015 itself (and several supposed launch platforms for this weapon do) is unable to  actually employ this weapon due to "no weapon director available to illuminate target" with the weapon's sensors setup as they are.  

### Recommended Fix

Perhaps give the weapon a laser _seeker_ or just leave the IIR seeker and remove all the SALH characteristics.

**Comment by KLABDB3K** [comment]
I was curious if this was a bug fix at some point theres a few laser guided anti Air that have this issue? I noted Starstreak ATASK has IIR when its actually a laser beam rider some time back and forgot to request a fix? 
The APKWS Air to Air DB variant is adrift of reality in having IIR. The test report link pretty much implies its a "normal" laser guided APKWS with the F16 using a Sniper pod to illuminate a cruise missile style target with a laser. The speculative part is if a proximity fuse was used. For a target flying pretty much straight and level the laser guided weapon would appear to be sufficient. 
https://www.thedrive.com/the-war-zone/31615/air-force-tests-laser-guided-rockets-in-the-air-to-air-role-to-shoot-down-cruise-missiles

**Comment by tbrandon517** [comment]
> I was curious if this was a bug fix at some point theres a few laser guided anti Air missiles that have this issue? I noted Starstreak ATASK has IIR when its actually a laser beam rider some time back and forgot to request a fix? The APKWS Air to Air DB variant is adrift of reality in having IIR. The test report link pretty much implies its a "normal" laser guided APKWS with the F16 using a Sniper pod to illuminate a cruise missile style target with a laser. The speculative part is if a proximity fuse was used. For a target flying pretty much straight and level the laser guided weapon would appear to be sufficient. https://www.thedrive.com/the-war-zone/31615/air-force-tests-laser-guided-rockets-in-the-air-to-air-role-to-shoot-down-cruise-missiles The ADATS DB entry accurately uses a Laser spot tracker so it must work??

ADATS was previously radar guided in the DB. It was updated when I put in an update request to make ground targets valid. There may have been some SIM issue previously where guidance was altered for expediency.

**Comment by PygmalionOfCyprus** [comment]
Yes, to my knowledge there's no reason for these entries to use inaccurate guidance. There may have, at some point, been a problem requiring a workaround, but if that should be the case  then the solution is to fix the problem, not to corrupt the DB.

A/A APKWS has been on my radar for a while now; it's a bit of a pain to fix, since it's also going to require going in and retrofitting every aircraft equipped with it with a valid laser designator (I suspect the presence of a designator on the weapon itself was originally an attempt to get around this) but it's gotta be done.

**Comment by PygmalionOfCyprus** [comment]
Finally dealt with this f*ing thing 508.
