### ISSUE TITLE
Decca 426

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1188]
### DB Selector

Both

### Baseline

4690 - Decca 303

### Hypothetical

No

### Name

Decca 426

### Sensor Generation

Early 1960s

### Range (nm)

48

### Sensor Capabilities

Surface Search, Range Information, Speed Information, Heading Information, Navigation Only

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

9,300,000,000

### Upper Frequency (Hz)

9,500,000,000

### Scan Interval (s)

2

### Comments

Navigation and Surface Search Radar

"The RM 426 had a range accuracy of plus or minus 50 yards, but could discriminate between objects located at least ten yards apart in range, provided that each object was at least ten square meters in size. The bearing accuracy of the RM 426 was plus or minus one degree."

### Sources

page 34:
https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwj7xp2Bo9z3AhVdQ_EDHbJxCBwQFnoECAcQAQ&url=https%3A%2F%2Fwww.dco.uscg.mil%2FPortals%2F9%2FDCO%2520Documents%2F5p%2FCG-5PC%2FINV%2Fdocs%2Fboards%2Farizonoregon.pdf&usg=AOvVaw1pXFOkUzdwnyBjk0kfI0bK

notes [3]:
https://law.justia.com/cases/federal/district-courts/FSupp/455/1043/1416063/

https://books.google.de/books/content?id=z5NWAAAAMAAJ&hl=de&pg=RA1-PA66&img=1&zoom=3&sig=ACfU3U3M66RAx830cdJ_VMiv3EcsmywjwQ&ci=9%2C8%2C984%2C1314&edge=0

unfortunately nothing more can be found

**Comment by PygmalionOfCyprus** [comment]
Added 495.
