### ISSUE TITLE
KDX-1 Datalinks

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1189]
### DB Selector

DB3K

### Affected DBID(s)

882, 2384, 2164, 3541

### Summary of Changes

KDX-1s should have Link-11.

According to Jane's Fighiting Ships 2009-2010 and Global Security, Gwanggaeto Daewang (KDX-1)-class destroyer's TDL is Link-11.

### Sources

![20220511_050723](https://user-images.githubusercontent.com/104970911/168328173-3a670893-3374-41b2-8c2a-986e4db9f2a7.jpg)
Jane's Fighting Ships 2009-2010, p.463

![20220514_013948](https://user-images.githubusercontent.com/104970911/168328965-e45429dd-7eea-4d32-8531-77978656453e.jpg)
https://www.globalsecurity.org/military/world/rok/kdx-1-specs.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
