### ISSUE TITLE
Izumo's received RAM Block II missiles (2021)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#119]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2442

### Summary of Changes

Japan upgraded RAM systems to RAM Block II. Izumo class #2442 is the first. So swap out RAM A for RAM C mount

### Sources

https://www.dsca.mil/press-media/major-arms-sales/japan-ram-block-2-tactical-missiles
https://www.reddit.com/r/MilitaryPorn/comments/nuytbz/a_raytheon_ram_block_2_sam_system_launching_a/
https://www.navalnews.com/naval-news/2020/09/us-oks-japan-requests-for-additional-ram-block-2-tactical-missiles/
https://www.defenseworld.net/news/29243/Raytheon_to_Manufacture_RAM_Block_2_Missiles_for_Japan__Turkey__U_A_E_

**Comment by PygmalionOfCyprus** [comment]
Handled earlier in the cycle as part of our work on the old tracker.
