### ISSUE TITLE
North Korea Amnok Class x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1190]
### DB Selector

DB3K

### Hypothetical

No

### Name

Amnok

### Class

Amnok Class

### Country

North Korea

### Service

Navy

### In Commission

2015-

### Length (m)

77

### Beam (m)

8.0

### Draft (m)

2.5 from Nampo

### Standard Displacement (t)

1300

### Full Displacement (t)

1300

### Complement

180 from Nampo

### Primary Propulsion Type

Diesel

### Propulsion

2x diesels

### Fuel Capacity (kg)

17.1 tons

### Flank Speed (kt)

24

### Range (nm) at Speed (kt)

Same as Nampo

### Sensors

- nav. radar
- surf. search radar
- air search radar
- MR-104 Rys' radars
- sonar
- ECM suite
- decoy RL
- Use similar to Nampo?

### Mounts

- 2x 4 KN-19 Kumsong-3 SSM (8 KN-19)
- 1x 6 FN-6? SAM
- 1x 1 76/59 HJ-26?
- 2x 2 30/71 AK-230
- 2x 2 - 533 TT
- 4x 5 RBU-1200 ASWRL

### Aircraft & Docking Facilities

None seen

### Comms/Datalinks

Same as Nampo

### Comments

- Possibly built using Krivak class hull.

### Sources

https://www.globalsecurity.org/military/world/dprk/c-amnok.htm
http://www.navypedia.org/ships/korea_north/kon_es_amnok.htm
https://natoassociation.ca/north-koreas-mystery-frigates/

![download](https://user-images.githubusercontent.com/99632305/168384310-6313b925-aab0-4fd7-8d23-6a53dc78667e.jpg)
![download](https://user-images.githubusercontent.com/99632305/168384319-9a9b12ff-cbfd-41ef-bb20-153de721d92b.jpg)
![GLSiakR](https://user-images.githubusercontent.com/99632305/168384338-d4a95307-e052-4f4d-9aa8-8e1c5988440b.jpg)
![tuman-20040420-image01](https://user-images.githubusercontent.com/99632305/168384388-c81ff431-2ebf-47a9-8465-6ba04eb39470.jpg)

**Comment by Jkryos** [comment]
Added DB3K 505.
