### ISSUE TITLE
Belgium - NH90 quick fixes (Name, Sensor, Loadouts)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1195]
### DB Selector

DB3K

- [ ] **ID 2355 | NH90 NFH** [Caiman Marine] - 2012
- Name : please delete "[Caiman Marine]" This is the French nickname and is not used in Belgian service.[^1]
- OperatorService = 2001 Air Force [^3]
- YearCommissioned = 2015 [^3]
- Crew = 5
- Sensor : please drop the ID 2732 TSM 8260 FLASH (AN/AQS-22, Type 2095) [^4]
- Loadouts :
  - please drop the loadout ID 9284 MU-90 Impact, TSM 8050B, TSM 8062 [^4]
  - please add an ID 9270 Search And Rescue (SAR) loadout [^3]
---

- [ ] **ID 2356 | NH90 TTH** [Caiman] - 2012
- Name : please delete "[Caiman]" [^2]
- Comments = x4 [^3]
- OperatorService = 2001 Air Force [^3]
- YearCommissioned = 2014 [^3]

### Sources

[^1]: [NH90 NFH NATO Frigate Helicopter | Belgian Defence ](https://web.archive.org/web/20190927172215/https://www.mil.be/fr/materiel/nh90-nfh-nato-frigate-helicopter)
[^2]: [NH90 TTH Tactical Transport Helicopter | Belgian Defence](https://web.archive.org/web/20200815145357/https://mil.be/fr/materiel/nh90-tth-tactical-transport-helicopter)
[^3]: [Le nouvel NH90 NFH prend son envol à Coxyde | Belgian Defence](https://web.archive.org/web/20191108003626/https://www.mil.be/fr/article/le-nouvel-nh90-nfh-prend-son-envol-coxyde)
[^4]: **Like its French counterparts in the NH90 NFH (Nato Frigate Helicopter) version, it is designed to be used on frigates, even in very poor wind and sea conditions. However, it is **not yet rigged for anti-submarine warfare**, like the "Caiman" of the naval air force. "This should be the case within two or three years," explains Major Tom. The Belgian NH90 NFHs, which _in the future will be able to deploy hardened sonar, sonobuoys and torpedoes_, will be one of the main weapons systems of the two future Belgian frigates, which will replace the Leopold I and Louise Marie at the end of the decade. With this in mind, training of Belgian aircrew is continuing. Today, the **Belgian NH90 is operated by five people**: a pilot, a co-pilot, a sensor operator (Senso), a diver and a flight engineer. In the future, to reinforce anti-surface warfare and when ASW capability is added, a Taco (tactical coordinator) will replace the co-pilot, as is the case for the French NH90. "We are two pilots now qualified to embark on ships, and our first Taco is currently completing his training in the Netherlands.**
© Mer et Marine https://www.meretmarine.com/fr/defense/integration-reussie-pour-le-premier-nh90-belge-embarque-sur-une-fregate-francaise

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
