### ISSUE TITLE
Belgium - SA.316B Alouette III

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1196]
### DB Selector

DB3K

### DBID to Copy

1448 SA.316B Alouette III (Ecuador Navy 1975) [Helicopter-Naval Utility]

### Hypothetical

No

### Name

SA.316B Alouette III

### Country

2011 Belgium

### Service

2002 Navy

### In Commission

1971

### Other Changes

- Comments= x3

### Sources

[Sud Aviation 316 B Alouette III | Belgian Defence](https://web.archive.org/web/20200808195041/https://mil.be/fr/materiel/sud-aviation-316-b-alouette-iii)
[Belgian Wings | Aerospatiale Alouette III](https://www.belgian-wings.be/aerospatiale-alouette-iii)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
