### ISSUE TITLE
Armed Orlan-10 Drone

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#1197]
### DB Selector

DB3K

### Hypothetical

No

### Name

Orlan-10 UCAV

### Country

Russia

### Service

Army

### In Commission

2010

### Length (m)

2

### Wingspan (m)

3.1

### Height (m)

0.4

### Empty Weight (kg)

12

### Maximum Takeoff Weight (MTOW) (kg)

16.5

### Payload Weight (kg)

6

### Crew

0

### Propulsion

1 × Saito Manufacturing FA-62B single-cylinder four-stroke gasoline piston engine, 0.71 kW (0.95 hp

### Service Ceiling (ft)

15000

### Military/Afterburner Speed (kt)

150kph max speed

### Cruise Speed (kt)

??

### Supercruise

No

### Ferry Range (nm)

300

### Endurance (min)

360min

### Sensors

Thermal imaging: TM2005016-F19
Optical imaging: Canon EOS 750D/EOS 800D digital SLR camera
Laser designator

### Mounts

Generic oecm

### Loadout Options

4x air dropped explosive containers
Oecm

### Comments

Orlan-10 combat drone, currently being used in Ukraine with explosive containers added. Orlan-10 has OECM variant aswell.  New variant has a laser designator, used to guide krasnopol artillery rounds to their target.

### Sources

![Screenshot_20220515-193418_YouTube](https://user-images.githubusercontent.com/99824301/168467475-9f3fcba7-f53e-41f7-a48a-5625f2b4f60a.jpg)
![Screenshot_20220515-193417_YouTube](https://user-images.githubusercontent.com/99824301/168467480-2b53251d-7d23-4381-8ba5-08fed595bb29.jpg)
![Screenshot_20220515-193421_YouTube](https://user-images.githubusercontent.com/99824301/168467484-35f94c85-2447-440e-ba27-727a852885a4.jpg)

Uploading VID_20220515_195637_733.mp4…

https://www.airforce-technology.com/projects/orlan-10-unmanned-aerial-vehicle-uav/

**Comment by TTZ32** [comment]
https://user-images.githubusercontent.com/99824301/168747426-f0ce79a4-b02d-4008-8d57-a66f9a1e9087.mp4

**Comment by PygmalionOfCyprus** [comment]
Added 495.
