### ISSUE TITLE
#2219 - SSM Plt (AT-14 Spriggan [9N133 Kornet]) (Russia [1992-] - 1995) Correction to designation 9M133, and weapon range and command data link?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1198]
### DB Selector

DB3K

### Affected DBID(s)

#2219 - SSM Plt (AT-14 Spriggan [9N133 Kornet]) (Russia [1992-] - 1995) Correction to designation 9M133

### Summary of Changes

#2219 - SSM Plt (AT-14 Spriggan [9N133 Kornet]) (Russia [1992-] - 1995) 
Currently described as 9**N**133 in the facility but the weapon itself is correctly designated #2938 - AT-14 Spriggan [9M133 Kornet]
9M133
Please amend designation to 9M133.
Plus the weapon itself is not accurate:
Currently has a UHF weapon data link but is actually ACLOS laser beam rider similar in general concept to ADATS.
NOT capable of "buddy lasing" as the weapon flies along a coded set of laser beam(s) providing command data from the launch platform.
Range from most open sources and manufacturer (before the website was taken down) is 5km or 2.7*nm not 3.7km or 2nm currently shown in DB. 

### Sources

DB493 WEAPON v Facility
https://en.wikipedia.org/wiki/9M133_Kornet
https://military-history.fandom.com/wiki/9M133_Kornet
https://www.militaryfactory.com/smallarms/detail.php?smallarms_id=973
http://[www.kbptula.ru](http://www.kbptula.ru/en/)/en/ * Dead link - No longer active.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
