### ISSUE TITLE
Mogami Frigates

### ISSUE THREAD

**Issue by JFS737** [PygmalionOfCyprus/cmo-db-requests#12]
### DB Selector

DB3K

### Affected DBID(s)

Japan FFM 1  FFM 3 Mogami

### Description of Problem

Your description of FFM 1 and FFM3 is backwards as far as your inclusion of each entries  Mk41 VLS  Mounts/Stores/Weapons goes...   (You have it listed for FFM 1 in the top line descriptor and not for FFM 3... but the FFM 3 has it and the FFM 1 does not in the Mounts/Stores/Weapons).

FFM 1  is 3292
FFM 3 is 3293

### Recommended Fix

Either
1.  Change the description of the ship in the top row of 3392 to 
FFM 1 Mogami -- Japan (Maritime Self-Defense Force), 2022 30DX, FFBNW
          (Simply deletes Mk41 VLS comment)
and...     Add "Mk 41 VLS" to entry 3393   FFM 3 Mogami

or 
2.  Since Both are listed as having Mk41 VLS by wiki...   just add a Mk41 VLS to 3292 and add the "Mk41 VLS" text descriptor to 3293. 
See wiki 
FFM 1 https://en.wikipedia.org/wiki/JS_Mogami
FFM 3   https://en.wikipedia.org/wiki/JS_Noshiro

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
