### ISSUE TITLE
EL/M 2080 radar is a sector not 360 deg + variant EL/M 2080S Super Green Pine

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1201]
### DB Selector

DB3K

### DBID to Copy

#1600 Radar (EL/M-2080 Green Pine)

### Hypothetical

No

### Name

Radar (EL/M-2080 Green Pine)

### Country

Israel

### Service

Air Defense

### Other Changes

The Elta Green Pine early warning and fire control radar, designated EL/M 2080, is a vital part of the Arrow missile defense system. Green Pine was developed in Israel but has also been sold to and deployed in India and South Korea.[[i]](https://missiledefenseadvocacy.org/defense-systems/green-pine-radar-elm-2080-israel/#_edn1)It operates at L-Band in the range of 500MHz – 1000MHz and can simultaneously search, detect, track and operate in missile guidance mode.[[ii]](https://missiledefenseadvocacy.org/defense-systems/green-pine-radar-elm-2080-israel/#_edn2)It can track up to 30 targets traveling at 10,000 ft/s, and advanced tracking technology allows Green Pine to guide Arrow-2 interceptors within 4 m of the target—discriminating between decoys and true threats—before detonating their fragmentation warhead for intercept.[[iii]](https://missiledefenseadvocacy.org/defense-systems/green-pine-radar-elm-2080-israel/#_edn3)

**An upgraded version of the EL/M 2080 is called the EL/M 2080S** or the “Super Green Pine.” The Super Green Pine is made up of smaller sensor modules that are more powerful than those used by its predecessor. The EL/M 2080S has an approximate range up to 900 km, compared to 500 km on the original EL/M 2080.

The Green Pine early warning and fire control radar has a proven success record of over 20 missile intercepts so far.[[iv]](https://missiledefenseadvocacy.org/defense-systems/green-pine-radar-elm-2080-israel/#_edn4)**It is currently deployed in Israel, India, and South Korea**. The Green pine system currently works with the Arrow-1 and Arrow-2 interceptors. The Super Green Pine works with the latest Arrow system, Arrow-3 and can intercept targets traveling through Space.[[v]](https://missiledefenseadvocacy.org/defense-systems/green-pine-radar-elm-2080-israel/#_edn5)

### Sources

https://missiledefenseadvocacy.org/defense-systems/green-pine-radar-elm-2080-israel/
https://www.ajudaily.com/view/20181127182413926

There is also information that the EL / M-2080 Green Pine early missile warning radar operates in Azerbaijan. According to the Stockholm Peace Institute (SIPRI), the contract for the supply of anti-missile radar was concluded in 2011 year. The main purpose of the radar EL / M-2080 Green Pine is the detection of attacking operational tactical missiles and the issuance of target designation of Barak 8 SAMs and С-300PMU 2 SAMs.
https://en.topwar.ru/137819-sovremennoe-sostoyanie-sistemy-pvo-azerbaydzhana.html

The Green Pine radar or ELM-280 operates at L band in the range 500 MHz to 1,000 MHz, or 1,000 MHz to 2,000 MHz. It works in search, detection, tracking, and missile guidance modes simultaneously. It is capable of detecting targets at ranges of up to about 500 km (310 mi) and is able to track more than 30 targets at speeds over 3,000 m/s. The radar illuminates the target and guides the Arrow missile to within 4 m of the target.
Features
- Autonomous long range detection and acquisition of TBMs
- Digital AESA technology
- Multi-mode operation
- Simultaneous tracking of dozens of TBMs
- Wide and flexible spatial coverage
- Discrimination between TBMs and other target types
- Satellite detection and tracking
- Accurate impact and launch point estimation
- Interoperability with complementary Air Defense Systems
- Data recording and analysis capabilities
- Transportable configuration
- Field proven
https://www.armyrecognition.com/israel_israeli_military_missile_vehicles_systems_u/green_pine_elm-2080_elm-2080s_radar_arrow_missile_technical_data_sheet_specifications_pictures_video_12201175.html

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. SGP is already in the DB as Sensor 5663 and used in the Israeli Arrow 3 battery. I did update the designation, though.
