### ISSUE TITLE
PKG 711 Datalinks

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1203]
### DB Selector

DB3K

### Affected DBID(s)

2454

### Summary of Changes

Link-11 should be added to PKG 711 Yoon Young Ha.

According to Republic of Korea Agency for Defense Development's press release images, PKG 711 (Gumdoksuri-A)'s CMS has Link-11.

### Sources

![53273fb2d6491a2b25a1e5c564e55d16](https://user-images.githubusercontent.com/104970911/169171262-9820bd3f-b257-4475-b327-6e90a5dc84c2.jpg)
https://m.korea.kr/special/policyFocusView.do?newsId=148620101&pkgId=49500278#policyFocus

![191](https://user-images.githubusercontent.com/104970911/169171332-b4607957-1dc1-4795-a757-6aee24e32631.jpg)
https://m.blog.daum.net/inyeon33/8198563

**Comment by PygmalionOfCyprus** [comment]
Added 495.
