### ISSUE TITLE
#1058 - AT-16 Scallion [9K127 Vikhr] please amend typo as the correct index is 9M127 not 9K127. Thanks

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1205]
### DB Selector

DB3K

### Affected DBID(s)

#1058 - AT-16 Scallion [9K121 Vikhr]

### Summary of Changes

Please amend single letter in title should be **9M127**.

**As a side note due to various issues with the design of the missile (circa 1997) and an eventual production order (circa 2013-2015) the system designation is 9K121 but the missile itself is designated the 9M127.  

### Sources

As previous. The loadout listing is accurate. Your patience is appreciated.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
