### ISSUE TITLE
Cuba - Torpedo Raft

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1206]
### DB Selector

DB3K

### Baseline

N/A

### Hypothetical

No

### Name

Improvised Torpedo Raft

### Class

Improvised Torpedo Raft

### Country

Cuba

### Service

Navy

### In Commission

2005 - Present

### Length (m)

9

### Beam (m)

3.5

### Draft (m)

.5

### Standard Displacement (t)

not stated

### Full Displacement (t)

not stated

### Empty Displacement (t)

2.3

### Complement

1

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

1-2x Marine Outboard Motor(s)

### Fuel Capacity (kg)

314

### Flank Speed (kt)

16?

### Range (nm) at Speed (kt)

Not Stated

### Sensors

mk 1 eyeball

### Mounts

1x 533cm TT

### Aircraft & Docking Facilities

None

### Comms/Datalinks

Basic radio

### Ship Codes

Catamaran/Trimaran Multihull, All Aluminum Construction, Built to Mercantile Standards, Low Construction Standards

### Comments

At the other end of the spectrum the Cuban Navy has figured out the smallest boat possible to carry a torpedo. Taking leftover torpedo tubes from scrapped Cold War era boats, they have combined them with a pontoon raft. Basically it uses two steel tubes as floats with a torpedo tube mounted between them. The pilot perches on the back controlling both the outboard motor and the firing mechanism. Several of these were built around 15 years ago and they appear to still be in service. They might be the smallest warships in the world.

### Sources

https://www.forbes.com/sites/hisutton/2020/03/15/5-unique-weapons-of-cubas-garage-built-navy/?sh=6d7b2a372acc
https://www.secretprojects.co.uk/threads/cuban-naval-projects-post-1959.38623/

![image](https://user-images.githubusercontent.com/99599482/169415637-07438c8b-c61b-4d37-a9c7-56fd839eeb86.png)
![image](https://user-images.githubusercontent.com/99599482/169415664-cb9cd8e6-21aa-49a2-a8a3-352e2069a26a.png)
![image](https://user-images.githubusercontent.com/99599482/169415676-704a1405-c3c6-40e4-a420-dff9ab18f040.png)
![image](https://user-images.githubusercontent.com/99599482/169415685-3bb3ac78-20a8-4340-8e9d-f258b76b5aeb.png)

**Comment by PygmalionOfCyprus** [comment]
lmao, this made my day. Added 495.

**Comment by tbrandon517** [comment]
> lmao, this made my day. Added 495.

Strapping a TT on a party barge pontoon. Half my high school class is jealous for this feat of DIY garage engineering.

**Comment by tbrandon517** [comment]
I must say I was inspired by the "sea technical" comment.

**Comment by PygmalionOfCyprus** [comment]
Well, if you should ever find any export customers for your own homemade naval abominations, do make sure to put in a new platform request. 😛
