### ISSUE TITLE
DDG 991 Sejong Daewang Datalinks

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1207]
### DB Selector

DB3K

### Affected DBID(s)

1749, 2168, 2386

### Summary of Changes

Link-16 JTIDS should be added to DDG 991 (KDX-III).

### Sources

![20220520_120358](https://user-images.githubusercontent.com/104970911/169442193-f603146f-fccc-44ef-82c0-ea708cc1382e.jpg)
https://www.navyrecognition.com/index.php/132-republic-of-korea-navy-vessels-ships-and-equipment/rok-navy-frigates-a-destroyers/844-sejong-the-great-sejongdaewang-kdx-iii-class-aegis-destroyer-republic-of-korea-rok-navy-yulgok-yi-i-seoae-yu-seong-ryong-hyundai-heavy-industries-hhi-dsme-datasheet-pictures-photos-video-specifications.html

![20220520_120539](https://user-images.githubusercontent.com/104970911/169442373-df589b47-d5c0-4be9-bd07-9b3c2d54f5d8.jpg)
Lee, Hyeong-hun et al, "Establishment for Efficiency Air-To-Ground Air Operation Model in Link-16",  Journal of the Korea Institute of Military Science and Technology Vol.13 No.5, 2010, p.861
https://jkimst.org/m/journal/view.php?number=828

![20220520_121111](https://user-images.githubusercontent.com/104970911/169443038-eef1556b-6b79-4d4f-a6b9-ffca58505ccc.jpg)
(Korean)
![20220520_121147](https://user-images.githubusercontent.com/104970911/169443072-ac525e69-3bbb-44db-b1ca-8b0726641335.jpg)
(Google translation)
Republic of Korea Defense Acquisition Program Administration press release, December 6, 2019
https://m.korea.kr/news/pressReleaseView.do?newsId=156364836#pressRelease

![img](https://user-images.githubusercontent.com/104970911/169443946-b1841499-a2af-4406-ae82-d0efacfcc7ab.gif)
https://stock-market.tistory.com/m/entry/005870-%ED%9C%B4%EB%8B%88%EB%93%9C-1-%ED%9A%8C%EC%82%AC%EC%86%8C%EA%B0%9C-%EC%82%AC%EC%97%85%EB%B6%84%EC%95%BC-%EC%97%B0%EA%B5%AC%EA%B0%9C%EB%B0%9C

**Comment by PygmalionOfCyprus** [comment]
Added 495.
