### ISSUE TITLE
Indonesia, Add Trisula (OPV) class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1208]
### DB Selector

DB3K

### Hypothetical

No

### Name

Offshore Patrol Vessel (OPV/FISV), P 111, Trisula

### Class

Trisula (Damen FISV 6210)

### Country

Indonesia

### Service

KPLP (Indonesian Coastguard)

### In Commission

2004 - present

### Length (m)

61.8

### Beam (m)

9.7

### Draft (m)

3.2

### Standard Displacement (t)

Not found

### Full Displacement (t)

878

### Complement

18 

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 16V4000 M70, 2 shafts

### Fuel Capacity (kg)

198m3

### Flank Speed (kt)

18

### Range (nm) at Speed (kt)

Not found

### Sensors

1x nav radar I-band (Trisula - Scanter 6000)
1x nav radar E/F-band

### Mounts

Only small calibre.

### Aircraft & Docking Facilities

1x Rescue boat by davits
1x RHIB by crane

### Comments

2 units in class. 
DWT: 310t. 
Differs from Agola Damen 6210. 

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/indonesia/ino_ls_trisula.htm
3: https://www.militer.or.id/264/indonesia-orders-terma-scanter-6000-radars-for-five-patrol-vessels
4: https://www.marinetraffic.com/en/ais/details/ships/shipid:702814/mmsi:525001015/imo:9049750/vessel:SAROTAMA
5: https://products.damen.com/en/ranges/fishery-research-vessel/frv-6210
Source 5 is generic

![1](https://user-images.githubusercontent.com/99532490/169550651-8fd099ee-8362-41f7-9979-812a39e165f0.jpg)
![2](https://user-images.githubusercontent.com/99532490/169550652-912bf20a-7313-49fd-a8a3-966cc3b8c9cd.jpg)
![3](https://user-images.githubusercontent.com/99532490/169550655-b843883e-9e4d-4347-aa63-a48dd3d8dcd7.jpg)

**Comment by Parel803** [comment]
entry on this site #580 is the Angolan 6210 by tbrandon517.

**Comment by PygmalionOfCyprus** [comment]
Added 495.
