### ISSUE TITLE
Orca XLUUV Range / Endurance too short

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1209]
### DB Selector

DB3K

### Affected DBID(s)

665

### Summary of Changes

The Orca XLUUV range at the moment is very short (DB493). Even with its hybrid propulsion system, it runs out of fuel after less than several hundred nautical miles. Instead, its range should be 6,500nm according to the sources posted below.

"It has a top speed of eight knots (14.8 kilometers/9.2 miles per hour) and a maximum range of 6,500 nautical miles (12,038 kilometers)."

### Sources

https://www.thedefensepost.com/2022/05/10/us-navy-orca-submarine/#:~:text=The%20Orca%20XLUUV&text=It%20has%20a%20top%20speed,nautical%20miles%20(12%2C038%20kilometers).

https://www.naval-technology.com/projects/orca-xluuv/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Orca will need a major pass at some point but since it's still unclear what exactly goes on the thing I can probably hold off on that for now.
