### ISSUE TITLE
AIM-132A ASRAAM range too short

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1210]
### DB Selector

DB3K

### Affected DBID(s)

1755

### Summary of Changes

The range of the RAF's / RAAF's AIM-132A ASRAAM is listed as 15 nautical miles which is the same as the AIM-2000. While the latter missile was designed for agility first and foremost, the ASRAAM's philosophy involves a longer range than its competitors. Because of this, it has a larger motor which gives it a range closer to 50km (26.9nm) than the current 15nm. It is also able to hit targets 180 degrees behind the launching aircraft, albeit at shorter ranges, as demonstrated 

"The missile body is wider than Sidewinder or IRIS-T and this gives a clue to the underlying operating concept for ASRAMM in comparison with other similar missiles.

The missile can be fired singly or in salvos., cued by any of the aircraft sensors and pilots helmet.

The range is stated to be ‘in excess of 25km’ and variously reported to be around **50km**.

It is this long range that makes ASRAAM different, instead of focussing on the extremely short-range or within visual range manoeuvrability, the larger rocket motor on ASRAAM enables much longer range shots to be taken.

See first, shoot first, kill first, as the marketing blurb goes.

The focal plane array allows ASRAAM to be highly resistant to countermeasures and detect targets at extended ranges. 

ASRAAM can also be cued by the Typhoon’s PIRATE IRST or Helmet Mounted Sight or Display (HMS/D) for a total passive engagement sequence.

ASRAAM can also be fired at very high speeds and G loading, locking on to the target before or after launch.

Although many like to compare it to IRIS-T or Sidewinder, the fact is they are different, with different concepts of employment.

Unlike IRIS-T, MICA or Sidewinder, it is designed to be used at beyond visual range, using its seeker, mid course correction and large motor."

---------------
"In a world first for an Air Force and an infra-red guided missile, Air Combat Group (ACG) of the Royal Australian Air Force has successfully carried out the first in-service 'Lock After Launch' firing of an ASRAAM (Advanced short-range air-to-air missile) at a target located behind the wing-line of the ‘shooter’ aircraft. The firing was conducted from an F/A-18 fighter aircraft, at low level and typical fighter speed, at a target located behind the fighter at a range in excess of 5km. The result was a direct hit on the target."

### Sources

https://www.thinkdefence.co.uk/advanced-short-range-air-to-air-missile-asraam/

https://www.timesaerospace.aero/features/defence/asraams-six-appeal

https://www.military-today.com/missiles/asraam.htm

https://web.archive.org/web/20170613231321/http://www.yourindustrynews.com/raaf+has+successfully+fired+asraam+at+a+target+located+behind+the+wing-line+of+the+%E2%80%98shooter%E2%80%99+aircraft_26109.html

**Comment by PygmalionOfCyprus** [comment]
Gave it a clean 25nm range for 495.

**Comment by TempestII** [comment]
Thanks!
