### ISSUE TITLE
EL-8222 ECM Pod for MiG-21bis [Bison]

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#1216]
### DB Selector

DB3K

### User(s)

1186

### Weapons Carried

Assume pod carried on an outer pylon like in photo?

-1 x AA-11 [R-73]
-1 x  EL/L-8222 ASSP DECM Pod  (weapon 822)
-2 x AA-12 Adder A [R-77, RVV-AE]
-1 x 800 liter Drop Tank

Might be used in Strike loadouts, too. I don't know.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

40 minutes  @ 150 nm CAP

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Or just change the Generic ECM Sensor to EL/L-8222? 

### Sources

https://youtu.be/vET6wz6j2dA?t=337

**Comment by PygmalionOfCyprus** [comment]
Just confirming this is only for the Indian MiG-21bis?

**Comment by boogaboogaCMO** [comment]
I think so- and specifically for the Bison upgrade at that. But I'm just going on the photographs in the video.

**Comment by PygmalionOfCyprus** [comment]
I removed the generic DECM from the aircraft sensors (I don't think it has any organically) and added two A:A loadouts w/ the pods. I don't _think_ they use them for ground attack loadouts -- I doubt they'd want to burn a pylon on a capability that's really not necessary when bombing ground targets -- but if someone knows better they can always correct me.
