### ISSUE TITLE
F-15K Datalinks

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1217]
### DB Selector

DB3K

### Affected DBID(s)

1748, 3658, 4514, 4982

### Summary of Changes

F-15K should have Link-16 JTIDS.

### Sources

![20220523_193624](https://user-images.githubusercontent.com/104970911/169802296-fb42ed89-3ccb-4603-a22d-0058e7bdad38.jpg)
(Korean)

![20220523_193723](https://user-images.githubusercontent.com/104970911/169802371-41124798-7411-4898-bb77-924a6511617f.jpg)
(Google translation)

Boeing Korea
https://www.boeing.co.kr/%EC%A0%9C%ED%92%88-%EB%B0%8F-%EC%84%9C%EB%B9%84%EC%8A%A4/%EB%B3%B4%EC%9E%89-%EB%94%94%ED%8E%9C%EC%8A%A4-%EC%9A%B0%EC%A3%BC-%EC%95%88%EB%B3%B4-%EB%B6%80%EB%AC%B8/F-15K-%EC%8A%AC%EB%9E%A8-%EC%9D%B4%EA%B8%80-%28Slam-Eagle%29.page

![20220523_194022](https://user-images.githubusercontent.com/104970911/169802532-5484fc92-9d33-44f9-9cee-4a97b8db57ff.jpg)
https://www.airforce-technology.com/projects/f-15k-slam-eagle/

![20220520_120539](https://user-images.githubusercontent.com/104970911/169802619-5f1826fc-a83b-4404-bcdd-2e2d341ac8ac.jpg)
Lee, Hyeong-hun et al, "Establishment for Efficiency Air-To-Ground Air Operation Model in Link-16", Journal of the Korea Institute of Military Science and Technology Vol.13 No.5, 2010, p.861
https://jkimst.org/m/journal/view.php?number=828

![20220523_193923](https://user-images.githubusercontent.com/104970911/169802937-04ffef2b-aff9-43b1-8807-a7ecff919c20.jpg)
(Korean)

![20220523_193933](https://user-images.githubusercontent.com/104970911/169802731-2b19c2b0-8966-48f1-9da1-79670062f30a.jpg)
(Google translation)

Kim, Seonggeol, "Anatomy of F-15K", The Hankyoreh, October 31, 2005
https://m.hani.co.kr/arti/politics/defense/75702.html#cb

**Comment by PygmalionOfCyprus** [comment]
Added 495. I also gave all the F-15Ks the Helmet Mounted Sight / Display flag to reflect the JHMCS.
