### ISSUE TITLE
US Navy MH-60R Sensor and Comms updates since 2015

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#122]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4356, 4796, 5037 and 5338

### Summary of Changes

US MH-60R's need update due to upgrades. Radar-AN/APS-153 Radar since 2015. Include Periscope detection capability. EO/IR-Had AAS-44C(V) Multi-Spectral Targeting Systems starting in 2011-2012. Comms are Link-16 by 2006.

Looks like AN/APS-153 in database on Indian and Greek MH-60R

### Sources

https://www.telephonics.com/soft-gate/gated-assets/uploads/39845-TC-AN-APS-153V-Brochure.pdf
https://tealgroup.com/index.php/teal-group-media-news-briefs-2/teal-group-news-media/item/end-of-mh-60r-seahawk-and-an-aps-153-radar-procurement-could-see-telephonics-acquired-and-end-competitive-u-s-radar-market
https://www.deagel.com/news/n000008462
https://www.afcea.org/content/?q=taxonomy/term/4027
https://www.cae.com/news-events/press-releases/lockheed-martin-awards-cae-contract-to-provide-mad-xr-for-us-navy-mh-60r-helicopters
https://www.thedrive.com/the-war-zone/37704/navy-mh-60r-seahawks-to-get-magnetic-anomaly-detectors-to-help-hunt-enemy-submarines
https://www.militaryaerospace.com/home/article/16712529/lockheed-martin-to-integrate-link16-sincgars-on-mh60-helicopters
https://www.defenseindustrydaily.com/the-wonders-of-link-16-for-less-midslvts-updated-02471/

**Comment by PygmalionOfCyprus** [comment]
Added new versions of the MH-60R and updated extant entries accordingly. 493.
