### ISSUE TITLE
Mistral MANPADS speed and target altitude

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1220]
### DB Selector

DB3K

### Affected DBID(s)

851, 1409, 2768, 730, 3116, 3890, 1336

### Summary of Changes

Mistral 1 and 2 have a top speed of Mach 2.5-2.6, while Mistral 3 has a top speed of Mach 2.7, also the max target altitude is much too high.

- [x] Mistral 1 propulsion: change max **speed to 1650kts**, change performance details to just **Band 1: 1650kts**, max target **alt 10000ft**, **range: 3.2nm**, applies to (851, 1409, 1336 [ATAM: don't change max target alt])

- [ ] Mistral 2 propulsion: change max **speed to 1700kts**, **Band 1: 1700kts**, max target **alt 10000ft**, **range: 3.5nm**, applies to (2768, 730, 3116 [ATAM: don't change max target alt])

- [ ] Mistral 3 propulsion: change max **speed to 1800kts**, change performance details to **Band 1: 1800kts**, maximum target **alt 13500ft**, **range: 4nm**, applies to (3890)

Mistral is the fastest manpads missile.

### Sources

max altitude and speed:
https://weaponsystems.net/system/773-Mistral
https://en.missilery.info/missile/mistral

This one lists Mistral at 4000m estimated, it's probably somewhere in the middle between 3-4km in height.
https://archive.org/details/history-of-the-electro-optical-guided-missiles/Army%20air%20defence/page/58/mode/2up?q=stinger&view=theater

https://www.mbda-systems.com/product/mistral-atlas/

Information regarding the Mistral 3 is somewhat conflicting... it is faster so the range should be higher. MBDA lists the range as 7.5km and alt as 4000 meters, however there seems to be an extended range version which has a max alt of 6000m.

**Comment by claudejdev** [comment]
Hey there,
I haven't had the time yet to process everything, I've had the opportunity to record lately.
However, here are pictures of a recent Jane's publications about that weapon system.
![IMG_20220503_143032 (2)](https://user-images.githubusercontent.com/35732829/170504168-57fe5c36-6b87-49eb-a481-e39c5e77bfe1.jpg)
![IMG_20220503_143036 (2)](https://user-images.githubusercontent.com/35732829/170504634-7a97718a-2729-4494-b838-0b50e2ab2299.jpg)

**Comment by nuk92** [comment]
Very interesting, the speed is even stated as M 2.6 at sea level.
Honestly, we might as well go for the range stated by MBDA for the Mistral 3.
Thanks, edited!

**Comment by KLABDB3K** [comment]
https://www.bing.com/videos/search?q=mistral+against+ships+video&view=detail&mid=10C17468E1000284BA9A10C17468E1000284BA9A&FORM=VIRE

Or targets down to an altitude of zero if the back ground is cool enough?

**Comment by nuk92** [comment]
The naval Mistral 3 that is currently in the db can be fired at ships. It's a good question whether the manpads version can do the same. :thinking:

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
