### ISSUE TITLE
Type 214 Son Won-Il Torpedo Wire Control

### ISSUE THREAD

**Issue by 17thFighterWing** [PygmalionOfCyprus/cmo-db-requests#1221]
### DB Selector

DB3K

### Affected DBID(s)

670

### Description of Problem

Currently Son Won-Il (2020) has no torpedo wire control. As a result, it cannot control its Tiger Shark wire-guided torpedo.

### Recommended Fix

Like other Type 214s, Torpedo Wire Control [4 Wires] should be added to it.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
