### ISSUE TITLE
Dutch, Add Geosea (minewarfare test platform)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1224]
### DB Selector

DB3K

### Hypothetical

No

### Name

Geosea

### Class

Research (supply) vessel, -, Geosea

### Country

Netherlands

### Service

Navy (leased)

### In Commission

Build in 2002, leased by dutch Navy in 2020 - present

### Length (m)

84.8

### Beam (m)

15.03

### Draft (m)

4.9

### Standard Displacement (t)

3253

### Complement

25+35

### Primary Propulsion Type

Diesel

### Propulsion

4x Cummings 1200 pk

### Flank Speed (kt)

13

### Range (nm) at Speed (kt)

? @ 7

### Sensors

2x Furuno Navigation radar 

### Mounts

Only mine warfare test equipment

### Aircraft & Docking Facilities

Mine warfare equipment: 
A-18M, 
Inspector 125, 
Seascan, 
K-STER, 
Skeldar UAV

1x Rescue boat. 2x RHIB (navy). 2x Crane. 

### Comments

DWT is 1853t. Was used to map seadottom now used to test minewarfare equipment that will be used on new NLD/BEL MM ships.

### Sources

1: https://www.marinetraffic.com/en/ais/details/ships/shipid:373923/mmsi:245406000/imo:9242431/vessel:GEOSEA
2: https://marineschepen.nl/dossiers/Reportage-testen-van-mijnenbestrijdingsdrones-op-Geosea.html
3: https://marineschepen.nl/nieuws/Civiel-testschip-voor-mijnenbestrijding-140220.html
4: https://www.offshore-energy.biz/n-sea-begins-contract-with-royal-netherlands-navy
5: https://www.navalnews.com/naval-news/2021/08/royal-netherlands-navy-started-evaluation-of-its-future-mine-warfare-toolbox
6: https://www.fleetmon.com/vessels/geosea_9242431_46435
![1](https://user-images.githubusercontent.com/99532490/170537705-185786ca-6f22-40ec-a909-bd4438653524.jpg)
![2](https://user-images.githubusercontent.com/99532490/170537716-240f3388-2406-4d34-9fa4-feb6967bff26.jpg)
![3](https://user-images.githubusercontent.com/99532490/170537718-79074ba3-cd5d-4462-a355-5bc52c476cb0.jpg)
![4](https://user-images.githubusercontent.com/99532490/170537720-0da5021b-e813-4c6b-b0c5-2e9cc9c8c402.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
