### ISSUE TITLE
Myanmar, Add PB 90 class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1226]
### DB Selector

DB3K

### Baseline

#187

### Hypothetical

No

### Name

Coastal Patrol Craft(PB), 424, -

### Class

PB 90

### Country

Myanmar

### Service

Navy

### In Commission

1986 - 1990 layed-up Yugoslavian manufacturer, 1990 - present

### Length (m)

27.4

### Beam (m)

6.6

### Draft (m)

2.2

### Standard Displacement (t)

80

### Full Displacement (t)

93

### Complement

17

### Primary Propulsion Type

Diesel

### Propulsion

3x Diesel, 3 shafts

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

400 @ 25

### Sensors

Decca 1226 I-band SS radar

### Mounts

2x quad 20mm/70 M75
2x 128mm launcher for illuminants

### Comments

Yugoslavian build, 3 units in class

### Sources

1: JFS 2015 - 2016
2: https://www.navypedia.org/ships/myanmar/mya_cf_336.htm
![1](https://user-images.githubusercontent.com/99532490/170554586-a506de54-7987-46d3-81c5-0dbd15994e3c.jpg)

**Comment by PygmalionOfCyprus** [comment]
You can save yourself a lot of trouble by using the Copy Entry form for situations like this where the class is already in the DB. 🙂

**Comment by PygmalionOfCyprus** [comment]
Added 495.

**Comment by Parel803** [comment]
Apologies for the xtra work and I'll try to comply with the advice
regards GJ
