### ISSUE TITLE
Matis MP3 Flir (Mistral)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1227]
### DB Selector

DB3K

### Baseline

1034 - EDIR

### Hypothetical

No

### Name

Matis MP3 [FLIR]

### Sensor Generation

Late 2000s

### Range (nm)

20

### Sensor Capabilities

Air Search, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Continuous Tracking Capability

### Scan Interval (s)

10

### Comments

12.5 to 2.5 degree fov that's around 5x optical zoom multiplied with 8x electronic zoom = 40x infrared zoom. The detection range is stated as around 10nm for a fighter jet sized target, it's probably more for bigger targets. The 20nm range is just an estimation, since I don't really know how optical sensors are simulated in cmano. You can have a Crotale with a DB range of 80nm (which btw sounds/is insane for ground based flir) but then spots a fighter jet flying at 2000 feet at less than 10 nm. So I don't really know what to make of it 😅

### Sources

https://www.yumpu.com/en/document/view/10854873/mp-sights

**Comment by PygmalionOfCyprus** [comment]
Personally I prefer FLAC, but MP3 is okay for streaming, I suppose.

Added 495.
