### ISSUE TITLE
USA - AIM-9X-2 Sidewinder Blk III (Extended range, 2019), rename

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1229]
### DB Selector

DB3K

### Affected DBID(s)

3664

### Summary of Changes

**DataWeapon**

ID | Name
--- | ---
3664 | AIM-9X-2 Sidewinder Blk III (Extended range, 2019)

- Name= AIM-9X Block II+

### Sources

I believe the "AIM-9X-2 Sidewinder Blk III" would benefit from being renamed "AIM-9X Block II+", to match the current official lingo.

![image](https://user-images.githubusercontent.com/35732829/170664611-57e182a7-8319-4deb-89b3-3268fbd64d2d.png)
https://www.esd.whs.mil/Portals/54/Documents/FOID/Reading%20Room/Selected_Acquisition_Reports/FY_2019_SARS/20-F-0568_DOC_08_AIM-9X_Blk_II_SAR_Dec_2019_Full.pdf

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Also updated loadout names.
