### ISSUE TITLE
Indian Kalvari (Scorpene) Submarines #108 only have SUT 1 torpedoes.

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#123]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 108

### Summary of Changes

Replace Blackshark's with same SUT 1's on #203

Black Shark deal fell through

### Sources

https://thediplomat.com/2019/01/indias-submarine-fleet-still-lacks-modern-heavyweight-torpedoes/
https://economictimes.indiatimes.com/news/defence/india-likely-to-go-for-govt-to-govt-german-deal-for-torpedos/articleshow/52958741.cms
https://en.wikipedia.org/wiki/INS_Kalvari_(S21)
https://www.rediff.com/news/report/ins-kalvari-a-toothless-shark/20171216.htm

**Comment by Jkryos** [comment]
Fixed DB3K 493.
