### ISSUE TITLE
Netherlands - F-16BM Falcon MLU - 2022, AIM-9X Blk 2+

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1230]
### DB Selector

DB3K

### DBID to Copy

3273

### Hypothetical

No

### Name

F-16BM Falcon MLU

### Country

Netherlands

### Service

Air Force

### In Commission

2022

### Loadout Options

Please duplicate all loadouts in which there is a Sidewinder and replace it by the ID 3664  AIM-9X Block II+ (cf. #1229 )

### Other Changes

- Comments= AIM-9X Block II+

### Sources

https://www.dsca.mil/press-media/major-arms-sales/netherlands-aim-9x-block-ii-missiles

**Comment by PygmalionOfCyprus** [comment]
Added 495.
