### ISSUE TITLE
France - AS.15TT, data

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1232]
### DB Selector

DB3K

### Affected DBID(s)

1894

### Summary of Changes

**DataWeapon**
- Diameter=0.18
- Weight=100
- SurfaceRangeMax=1.6
- SurfaceRangeMin=9.2

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![image](https://user-images.githubusercontent.com/35732829/170704476-c796a133-484b-4cd9-abf4-e555829a928e.png)

- IOC : 1985

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. I assume you mixed up the min and max ranges. 😛
