### ISSUE TITLE
France - ARMAT, Guidance

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1233]
### DB Selector

DB3K

### Affected DBID(s)

205

### Summary of Changes

- Guidance Type: Inertial (INS) mid-course plus Passive Radar Homing (ARM) terminal guidance 
(I don't know in which table it's set)

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![image](https://user-images.githubusercontent.com/35732829/170709793-8d775d98-6e6f-4c17-9bf3-f6ad11defe4e.png)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Guidance flags are added through DataWeaponCodes.
