### ISSUE TITLE
China - YJ-91 (ARM), data, code

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1234]
### DB Selector

DB3K

### Affected DBID(s)

2875

### Summary of Changes

**DataWeapon**
- Span=0.914
- SurfaceRangeMax=8.1
- SurfaceRangeMin=64.8

 **WeaponCode**
I am uncertain if it's capable of BOL

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![image](https://user-images.githubusercontent.com/35732829/170714162-35c456cc-38a1-45a8-8185-a8f7f95d1f15.png)

_Question :_ is the signature automatically set relatively to the dimensions, or is it picked manually from the signatures tables? I've noticed, possible, discrepancies in missiles of similar shape and was wondering if it's worth investigating.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Signatures are calculated automatically from dimensions + effects of modifiers (though our weapon modifiers are quite basic). I don't think it's worth investigating unless you find something truly egregious.
