### ISSUE TITLE
China - YJ-91A (ASM), data, code

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1235]
### DB Selector

DB3K

### Affected DBID(s)

2874

### Summary of Changes

**DataWeapon**
- Span=0.914
- SurfaceRangeMin=27.0

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![image](https://user-images.githubusercontent.com/35732829/170714162-35c456cc-38a1-45a8-8185-a8f7f95d1f15.png)

_Question_
Its attack profile is sea-skimming, instead of popping up.
Is it set with the Terrain Following WeaponCode ?

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. (Also adjusted the min range in line with the other YJ-91 based on the picture.)

>Is [sea-skimming] set with the Terrain Following WeaponCode?

Yes, in addition to weapon cruise altitude.
