### ISSUE TITLE
China - HJ-8 ATGM, data, warhead (A to F variants)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1237]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

**DataWeapon**

- [x] 2124 | HJ-8B ATGM
- Name=HJ-8A/C
- Comments=Red Arrow, AGM, 1991
- Length=1.57
- Span=0.15
- SurfaceRangeMax/LandRangeMax=1.9
- SurfaceRangeMin/LandRangeMin=0.1

- [x] 2836 | HJ-8E ATGM
- Name=HJ-8E/F
- Comments=Red Arrow, ATGM, 1996
- Length=1.57
- Span=0.15
- Weight=14.0
- CruiseAltitude=0.0
- ClimbRate=0.0
- SurfacePoK/LandPoK=90.0
- SurfaceRangeMax/LandRangeMax=2.2
- SurfaceRangeMin/LandRangeMin=0.1

**DataWarhead**
- [x] 739 | HJ-8 Shaped Charge
- DamagePoints=4.0
- ExplosivesWeight=4.0

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![IMG_20220516_143547 (2)](https://user-images.githubusercontent.com/35732829/170762161-04ade12b-be6c-4796-a93b-115d478d5704.jpg)
![IMG_20220516_143550 (3)](https://user-images.githubusercontent.com/35732829/170764458-9062e69a-e89d-46d6-8f2b-500faf357ec6.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
