### ISSUE TITLE
China - HJ-10 ATGM

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1238]
### DB Selector

DB3K

### Affected DBID(s)

2125 - HJ-10 ATGM

### Summary of Changes

- Name=AKD-10
- Comments=Blue Arrow 7, AGM, 2011
- Length=1.78
- Diameter=0.17
- Weight=47.0
- SurfaceRangeMax/LandRangeMax=4.3
- SurfaceRangeMin/LandRangeMin=1.1

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![IMG_20220516_143544 (2)](https://user-images.githubusercontent.com/35732829/170775012-b7a9d775-6565-4f8e-a50b-0676ece542e7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
