### ISSUE TITLE
China - AR-1 Air Ranger ATGM

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1239]
### DB Selector

DB3K

### Affected DBID(s)

3225 - AR-1 Air Ranger ATGM

### Summary of Changes

- [x] **DataWeapon**

- Name=AR-1
- Comments=AGM, 2008
- Length=1.5
- Span=0.4
- Diameter=0.18
- CEP/CEPSurface=2
- SurfaceRangeMax/LandRangeMax=4.3
- SurfaceRangeMin/LandRangeMin=1.1
- LaunchAltitudeMax=5000.0
- LaunchAltitudeMin=500.0

- [ ] **DataWeaponCodes**

- 2012 Lock-On After Launch (LOAL)

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![IMG_20220516_143538 (2)](https://user-images.githubusercontent.com/35732829/170776129-642120a5-5017-4ecb-bd7b-1b0e0a1fe0e1.jpg)
![IMG_20220516_143541 (2)](https://user-images.githubusercontent.com/35732829/170777858-33a0f43c-ab3c-416b-a768-066bd1ed8d53.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
