### ISSUE TITLE
Brazil - MAR-1 [ARM]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1240]
### DB Selector

DB3K

### Affected DBID(s)

2702 - MAR-1 [ARM]

### Summary of Changes

- [x] **DataWeapon**
- SurfaceRangeMax/LandRangeMax=27.0

- [x] **DataWeaponCodes**
- 2012 Lock-On After Launch (LOAL)

- [x] Guidance Type: GPS-Updated Inertial (INS) and Datalink (DL/INS) mid-course Passive Radar Homing (ARM) terminal guidance

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![IMG_20220516_143536 (2)](https://user-images.githubusercontent.com/35732829/170780704-b1c7ff5e-0001-487b-8e60-76b11f1e6159.jpg)
![IMG_20220516_143538 (3)](https://user-images.githubusercontent.com/35732829/170780865-a8aa774f-8bbf-41af-a0a2-2c4cd3afa6dd.jpg)

**Comment by PygmalionOfCyprus** [comment]
I also gave the weapon the "Acts as Sensor" property and tweaked some dimensions based on the source.
