### ISSUE TITLE
AEGIS Command Datalink [APAR] not able to share data with US/other NATO assets

### ISSUE THREAD

**Issue by Olafseisler** [PygmalionOfCyprus/cmo-db-requests#1241]
### DB Selector

DB3K

### Affected DBID(s)

188

### Summary of Changes

The Aegis datalink on Dutch De Zeven Provinciën-class frigates should be CEC-capable with US naval assets for guiding either SM-3 or SM-6 missiles. Its SMART-L radar is a huge asset in any battle group when combating either ballistic missiles or stealthy adversaries.  Currently it this is not possible in-game whilst having been demonstrated in reality. 

Logically the same would apply to other NATO vessels but I'm not sure they have the necessary datalink equipment installed. The British seem to have given up on this capability.

### Sources

https://navalpost.com/uss-paul-ignatius-intercepts-bm-smart-l-assistance/
https://www.navylookout.com/upgrading-the-royal-navys-type-45-destroyers/

**Comment by PygmalionOfCyprus** [comment]
Could you elaborate on what specifically you're trying to do? What weapon specifically (with a DBID) you were trying to guide, etc. Datalink stuff is complicated and there's not a single switch for me to flip, so I'll need to dig into the specific case.
