### ISSUE TITLE
Taiwan - TC-2 [Tien Chien II]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1242]
### DB Selector

DB3K

### Affected DBID(s)

1768 - TC-2 [Tien Chien II]

### Summary of Changes

- [x] **DataWeapon**
- AirRangeMax=32.4

- [x] **DataWarhead**
I would suggest using this one, to match with its actual 30 Kg warhead :
- 196 A/RIM-7E (Mk38) 30kg Continuous Rod

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![IMG_20220516_143512 (2)](https://user-images.githubusercontent.com/35732829/170786121-a4d4b007-111a-4e04-984c-8905d0ca83df.jpg)

**Comment by PygmalionOfCyprus** [comment]
Gave it Warhead 691 instead since that one is fragmentation vs. 196 which is continuous rod.
