### ISSUE TITLE
Taiwan - TC-2C [Tien Chien IIC]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1243]
### DB Selector

DB3K

### DBID to Copy

1768 - TC-2 [Tien Chien II]

### Hypothetical

No

### Name

TC-2C [Tien Chien IIC]

### Country

Taiwan

### Service

Air Force

### In Commission

2017

### Other Changes

#1242 

**DataWeapon**
- AirRangeMax=54.0

### Sources

[Extended-range missiles ready for use - Taipei Times](https://www.taipeitimes.com/News/front/archives/2017/12/25/2003684599)
IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![IMG_20220516_143512 (2)](https://user-images.githubusercontent.com/35732829/170786121-a4d4b007-111a-4e04-984c-8905d0ca83df.jpg)

**Comment by claudejdev** [comment]
I don't see the TC-2C in the DB v493 here.
![image](https://user-images.githubusercontent.com/35732829/171037353-dfbcfc07-2280-4e00-855f-21e8dccdb9ad.png)
Cheers

**Comment by PygmalionOfCyprus** [comment]
Oh, you know what, I think I added it in 494 as part of an internal news roundup. I'm gonna close the ticket but if it's not in there when the DB releases soonTM come back and yell at me.

**Comment by claudejdev** [comment]
Hey there Ethan,

I don't see the TC-*2**C *in the DB v493 here.
[image: image.png]
Cheers

Le lun. 30 mai 2022 à 11:01, Ethan Hermanson ***@***.***> a
écrit :
