### ISSUE TITLE
South Africa - V4A R-Darter [Derby]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1244]
### DB Selector

DB3K

### Affected DBID(s)

863 - V4A R-Darter [Derby]

### Summary of Changes

- [x] **DataWeapon**
- Name=V4A R-Darter
- Comments=2000
- Weight=120.0
- AirRangeMax=34.0

- [x] **DataWeaponCodes**
- 2012 Lock-On After Launch (LOAL)

- [x] **DataWeaponComms**
Unlike the Derby, the current version wouldn't have a datalink.

### Sources

IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![IMG_20220516_143510 (2)](https://user-images.githubusercontent.com/35732829/170789081-05ab5fbc-1d3f-4e4b-a8d1-b1f475fd3fe9.jpg)

**Comment by PygmalionOfCyprus** [comment]
Also added INS navigation.
