### ISSUE TITLE
Russia - AA-12 Adder A [R-77, RVV-AE], data, sensor

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1245]
### DB Selector

DB3K

### Affected DBID(s)

273 - AA-12 Adder A [R-77, RVV-AE]

### Summary of Changes

- [x] **DataWeapon**
- Name=AA-12A Adder [R-77, RVV-AE]*
- Comments=1994, Izdeliye 170
- AirRangeMax=43.2
- AirRangeMin=0.2
- LaunchSpeedMin=741.0
- TargetAltitudeMin=20.0

* _(Version letter appended to the missile number enhances readability. And it's thus in line with other NATO and US designation systems)_

- [x] **DataWeaponFuel** (ID 273) (So it has 100 seconds of fuel time)
- ComponentID=950

- [x] **DataSensor** 656 - Active Radar Seeker (AA-12A, 9B-1348E)
- Generation=2009 Early 1990s

- [x] **DataSensorFrequencySearchAndTrack** 656 - Active Radar Seeker (AA-12A, 9B-1348E)
- Frequency=1010 J Band (10-20 GHz) [Old X Band] 1.5-3 cm

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![IMG_20220516_143504 (2)](https://user-images.githubusercontent.com/35732829/170792556-aee7bb01-4f18-426c-97bc-fb5da2914556.jpg)
![IMG_20220516_143507 (2)](https://user-images.githubusercontent.com/35732829/170791270-f2f73633-c01b-4417-8ff8-7ed0e567c074.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.

**Comment by PygmalionOfCyprus** [comment]
I should note I have _not_ changed the name since the current system is actually NATO convention for Russian equipment.

**Comment by claudejdev** [comment]
> I should note I have _not_ changed the name since the current system is actually NATO convention for Russian equipment.

Fair enough. The only open source I have here quoted both convention, so I thought it would be worth suggesting.
[Designations of Soviet and Russian Military Aircraft and Missiles](https://www.designation-systems.net/non-us/soviet.html#_System_NATO)
Would you know a more authoritative source on that?

**Comment by PygmalionOfCyprus** [comment]
I don't have a source off the top of my head, but if the current designation is valid (which it is) it's a lot easier to maintain rather than go through and retroactively change every Russian weapon in the DB. Especially since we don't have weapons sortable by country.
