### ISSUE TITLE
Russia - AA-12 Adder B [R-77-1, RVV-SD]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1246]
### DB Selector

DB3K

### Affected DBID(s)

2056 - AA-12 Adder B [R-77-1, RVV-SD]

### Summary of Changes

- [x] **DataWeapon**
- Name=AA-12B Adder [R-77-1, RVV-SD]*
- Comments=2009, Izdeliye 170-1
- AirRangeMin=0.2
- TargetAltitudeMin=20.0

* _(Version letter appended to the missile number enhances readability. And it's thus in line with other NATO and US designation systems)_

- [x] **DataWeaponFuel** (ID 2056) (So it has 100 seconds of fuel time)
- ComponentID=950

- [x] **DataSensor** 5955 - Active Radar Seeker (AA-12B, 9B-1103M)
- Generation=2011	Early 2000s

- [x] **DataSensorFrequencySearchAndTrack** (ID 5955)
- Frequency=1010 J Band (10-20 GHz) [Old X Band] 1.5-3 cm

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![IMG_20220516_143504 (2)](https://user-images.githubusercontent.com/35732829/170792556-aee7bb01-4f18-426c-97bc-fb5da2914556.jpg)
![IMG_20220516_143507 (2)](https://user-images.githubusercontent.com/35732829/170791270-f2f73633-c01b-4417-8ff8-7ed0e567c074.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
