### ISSUE TITLE
Russia - AA-6s Acrid (data, guidance, warhead)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1247]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

**DataWeapon**

- [x] _ID 147 | AA-6 Acrid D [R-40TD, IR]	1980_
- Name=AA-6D Acrid [R-40TD, IR] *
- Weight=470.0
- AirRangeMax=27.0
- Guidance Type: Inertial (INS) mid-course plus Passive Infrared (IR) terminal guidance

* _(Version letter appended to the missile number enhances readability. And it's thus in line with other NATO and US designation systems)_

- [x] _ID 148 | AA-6 Acrid C [R-40RD, SARH] 1980_
- Name=AA-6C Acrid [R-40RD, SARH]
- Length=6.38
- Weight=470.0
- AirRangeMax=27.0
- Guidance Type: Inertial (INS) mid-course plus Semi-Active Radar Homing (SARH)

- [x] _ID 757 | AA-6 Acrid B [R-40T, IR]	-_
- Name=AA-6B Acrid [R-40T, IR]
- Comments=1974
- Length=6.36
- Weight=468.0
- AirRangeMax=16.2
- Guidance Type: Inertial (INS) mid-course plus Passive Infrared (IR) terminal guidance

- [x] _ID 759 | AA-6 Acrid A [R-40R, SARH]	-_
- Name=AA-6A Acrid [R-40R, SARH]
- Comments=1974
- Length=6.76
- Weight=455.0
- AirRangeMax=16.2
- Guidance Type: Inertial (INS) mid-course plus Semi-Active Radar Homing (SARH)

---
- [x] **DataWarhead**
- COPY ID 339 70kg Frag (SA-N-7/12, AS-11/17, AA-6)
- Name=38kg Frag (R-40/AA-6)
- DamagePoints=13.0 (I guess?)
- ExplosivesWeight=38.0

---
- [x] **DataWeaponWarheads**
SET DataWeaponWarheads.ComponentID= That new Warhead ID
WHERE DataWeaponWarheads.ID IN (147, 148, 437, 438, 757, 759);

### Notes
ID 438 AA-6 Acrid E [R-40RD _1_, SARH] and ID 437 AA-6 Acrid F [R-40TD _1_, IR] are not mentioned in my ref. books.

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![IMG_20220516_143502 (2)](https://user-images.githubusercontent.com/35732829/170820356-89dffcbc-193e-4f04-a9dc-3859cfcaa7e5.jpg)
![IMG_20220516_143504 (3)](https://user-images.githubusercontent.com/35732829/170822931-34fd783d-6ecb-4d9c-a79f-4859d8786fea.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
