### ISSUE TITLE
Russia - AA-13 Arrow [R-37M, RVV-BD]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1248]
### DB Selector

DB3K

### Affected DBID(s)

915

### Summary of Changes

- [x] **DataWeapon**
- Comments=2019, izdelie 610M
- Weight=510.0
- AirRangeMax=108.0
- AirRangeMin=2.0 [^1]

- [x] **DataSensor** ID 509 - Active Radar Seeker (AAM MR, AA-13)
- Comments += AGAT 9B-1103M-350
- Generation=2011	Early 2000s [^2]
- RangeMax=21.6

- [x] **DataSensorFrequencySearchAndTrack** ID 509 - Active Radar Seeker (AAM MR, AA-13) [^3]
- Frequency=1010 J Band (10-20 GHz) [Old X Band] 1.5-3 cm, 1011 K Band (20-40 GHz) [Old Ku Band] 0.75-1.5 cm

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
[^1]:[R-37 long-range aircraft missile (RVV-BD) | Missilery.info](https://en.missilery.info/missile/r37)
[^2]:[Agat shows active radar seeker | News | Flight Global](https://www.flightglobal.com/agat-shows-active-radar-seeker/33545.article)
[^3]:[Homing head 9B-1103M-350 | Missilery.info](https://en.missilery.info/missile/r37/9b-1103m-350)

![IMG_20220516_143455 (2)](https://user-images.githubusercontent.com/35732829/170824997-40e4e8bb-8379-48cb-8d77-4dcb4af9fc42.jpg)
![IMG_20220516_143458 (2)](https://user-images.githubusercontent.com/35732829/170824965-509a197b-9d64-4d01-9996-a0faea503f23.jpg)
![IMG_20220516_143502 (3)](https://user-images.githubusercontent.com/35732829/170825582-ba85d288-3749-4094-b7a6-4f1a69247dd3.jpg)

Note : some sources mention the NATO reporting name of "Axehead". As far as I know, it's an urbanet myth.
What I believe to be an official source confirms it's Arrow : https://odin.tradoc.army.mil/WEG/Asset/R-37M_(AA-X-13::AA-13_Arrow)_Russian_Air-to-Air_Missile

Also: [Info about the R-37 - Matrix Games Forums](https://www.matrixgames.com/forums/viewtopic.php?p=4267682)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Kept Axehead in the comments since even though we know it's wrong, it may still pop up and be useful for searching/clarification.
