### ISSUE TITLE
Add EC-130V Hercules AEW

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#125]
### DB Selector

DB3K

### Hypothetical

No

### Name

EC-130V Hercules AEW

### Country

United States

### Service

Coast Guard (as EC-130V), Air Force and Navy (as NC-130H)

### In Commission

1991-1993 (USCG), 1993-1998 (USAF), 1998-2002 (Navy)

### Length (m)

Same As C-130H Hercules DB ID 251

### Wingspan (m)

Same As C-130H Hercules DB ID 251

### Height (m)

Same As C-130H Hercules DB ID 251

### Empty Weight (kg)

Same As C-130H Hercules DB ID 251

### Maximum Takeoff Weight (MTOW) (kg)

70307 kg

### Payload Weight (kg)

Same As C-130H Hercules DB ID 251

### Crew

10

### Propulsion

Same As C-130H Hercules DB ID 251

### Rate of Climb (ft/min)

Same As C-130H Hercules DB ID 251

### Service Ceiling (ft)

Same As C-130H Hercules DB ID 251

### Military/Afterburner Speed (kt)

Same As C-130H Hercules DB ID 251

### Cruise Speed (kt)

Same As C-130H Hercules DB ID 251

### Supercruise

No

### Ferry Range (nm)

Same As C-130H Hercules DB ID 251

### Endurance (min)

690 minutes on station at loiter

### Takeoff / Landing Distance (m)

Same As C-130H Hercules DB ID 251

### Fuel Capacity (kg)

Same As C-130H Hercules DB ID 251

### Sensors

Same As C-130H Hercules DB ID 251 plus:

APS-125 Radar as EC-130V

APS-145 Radar as NC-130H

### Mounts

Same As C-130H Hercules DB ID 251

### Loadout Options

- AEW

### Comms/Datalinks

Same As C-130H Hercules DB ID 251 plus 

Same P-3B Orion AEW DB ID 1240 and 4942

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

1 aircraft converted in 1991 for USCG AEW for Counter-Narcotics missions requiring greater endurance than the E-2 could provide, but also been for Search and Rescue, Fisheries Patrols, EEZ enforcement, and as a support aircraft for NASA Space Shuttle launches. Used with AN/APS-125 system from E-2C similar to P-3B AEW conversions. Later transferred to USAF as a range control aircraft and upgraded to an AN/ASP-145 and designated NC-130H. Also used from 1999 as Hawkeye 2000 program testbed. After US Navy use modified at some point to HC-130H standard and transferred to the U.S. Forest Service

### Sources

https://fas.org/man/dod-101/sys/ac/ec-130v.htm
https://www.globalsecurity.org/military/systems/aircraft/ec-130v.htm
https://www.c-130.net/aircraft-database/C-130/airframe-profile/7620/
https://en.wikipedia.org/wiki/Lockheed_EC-130#Variants

![download](https://user-images.githubusercontent.com/99599482/154353989-fdb7a795-b67a-4094-bbe7-78d2b9077f9a.jpg)
![download](https://user-images.githubusercontent.com/99599482/154354005-393207e6-c991-42eb-accf-88ab858b4700.jpg)
![download](https://user-images.githubusercontent.com/99599482/154354014-d238f0ac-1381-4268-b9ef-8408da38c6e8.jpg)
![download](https://user-images.githubusercontent.com/99599482/154354020-7a63ae5f-311a-4e03-92b6-c61ceeff87c3.jpg)
![download](https://user-images.githubusercontent.com/99599482/154354077-a8d26346-5268-4655-98b1-3f15f2936a5f.jpg)
![download](https://user-images.githubusercontent.com/99599482/154354089-096f7c4e-7138-4bd1-ba54-76a02535d00a.jpg)
![images](https://user-images.githubusercontent.com/99599482/154354137-0dc30f4f-23a7-49c5-9068-ef3802826d61.jpg)

![download](https://user-images.githubusercontent.com/99599482/154354122-ee33312a-a066-4c93-a17a-706b18539170.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 493.
