### ISSUE TITLE
Russia - AA-9s Amos [R-33]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1251]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

 **DataWeapon** 
- [x] 1747 | AA-9 Amos [R-33, SARH] -
- Comments=1981, izdelie 410
- Length=4.25
- AirRangeMax=64.8
- AirRangeMin=1.3

- [x] 352 | AA-9 Amos [R-33S, SARH] 1999
- Name=AA-9B Amos [R-33S, SARH]
- Comments=1991, izdelie 520
- AirRangeMax=86.4
- AirRangeMin=1.3

---
- [x] **DataSensor** COPY ID 815 SARH Seeker (AA-9)
- Comments=AA-9B
- Generation=2009 Early 1990s
---
- [x] **DataWeaponSensors** to ID 352 AA-9B Amos
-ComponentID= NEW  SARH Seeker (AA-9B)

Note : R-33S could be a nuclear tipped variant, produced from 1988 to 1995 at the TMZ plant in Moscow.

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![IMG_20220516_143452 (2)](https://user-images.githubusercontent.com/35732829/170874313-9927c854-ae1c-461f-a035-7439fbd9cca0.jpg)
![IMG_20220516_143455 (3)](https://user-images.githubusercontent.com/35732829/170874903-7a315a9d-277a-4b82-a3f9-696fa54cff6e.jpg)
![IMG_20220516_143455 (4)](https://user-images.githubusercontent.com/35732829/170875270-68bf2b7e-405c-4dbe-b877-6937590c595c.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Pursuant to my earlier comment the AA-9B has been named the "AA-9 Amos B".
