### ISSUE TITLE
United States - AIM-120s

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1252]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

 **DataWeapon**

- [x] A to C-4

ID | Name Comments
--- | ---
1383 | AIM-120A AMRAAM	1992
446 | AIM-120B AMRAAM	1996
946 | AIM-120C AMRAAM P3I.1	1999
53 | AIM-120C-4 AMRAAM P3I.2	2001
417 | RB 99 AMRAAM [AIM-120B]	-

```
SET DataWeapon.Weight=157.8,DataWeapon.AirRangeMax=27.0,DataWeapon.AirRangeMin=1.1
WHERE DataWeapon.ID IN (53,417,446,946,1383);
```
_Note : ID 1338, early IOC on F-15 in Sept. 1991_

- [x] C-5 to C-7

ID | Name Comments
--- | ---
897 | AIM-120C-5 AMRAAM P3I.2	2003
52 | AIM-120C-6 AMRAAM P3I.2	2005
718 | AIM-120C-7 AMRAAM P3I.3	2007

```
SET DataWeapon.Weight=161.5,DataWeapon.AirRangeMax=56.7,DataWeapon.AirRangeMin=1.1
WHERE DataWeapon.ID IN (52,718,897);
```

- [ ] Delta

ID | Name Comments
--- | ---
51 | AIM-120D AMRAAM P3I.4	2016

- Comments=2015
- Weight=162.4
- AirRangeMax=86.4
- DataWeapon.AirRangeMin=1.1

- GuidanceType +=GPS-Updated Inertial (INS)

### Sources

- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![100-101 (2)](https://user-images.githubusercontent.com/35732829/170878165-18b7cdd6-7f4e-48fb-9da3-3471bb22d407.jpg)
![102-13 (2)](https://user-images.githubusercontent.com/35732829/170879102-d01b169d-059d-4759-9d86-e06c13cf99aa.jpg)
![104-105 (4)](https://user-images.githubusercontent.com/35732829/170879158-3cdad72c-0db6-444d-921e-26bc3a16f72b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. SQL worked a dream, BTW. Just needs the `UPDATE DataWeapon` before the `SET` statement to work right out of the box.
