### ISSUE TITLE
Russia - MR10-M1E Coastal Surveillance Radar

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1253]
### DB Selector

DB3K

### Baseline

Nayada or Palm Frond

### Hypothetical

No

### Name

MR10-M1E

### Sensor Generation

Early 2010s

### Range (nm)

27

### Sensor Capabilities

Surface Search

### Sensor Codes

Continuous Tracking Capability, Moving Target Indicator (MTI), Pulse-Only Radar

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

9,350,000,000

### Upper Frequency (Hz)

9,400,000,000

### Horizontal Beamwidth (deg)

0.19

### Comments

Range based on source, 32 miles, or more likely 50km.  Its a surface search radar (coastal surveillance).  Very common along coastlines of Russian Federation.
2 examples in Crimea at Mys Tarkhantut and Mys Khersones clearly evident on Streetview phots's near the lighthouses on the respective Capes.

### Sources

1. http://roe.ru/eng/catalog/naval-systems/stationary-electronic-systems/mr-10m1e/
2. http://roe.ru/eng/catalog/naval-systems/stationary-electronic-systems/mys-m1e/
3. Google Earth Pro (including street view photo's where available)

**Comment by PygmalionOfCyprus** [comment]
Added 495. I think the domestic designation would just be MR10-M1. 

Where did you get the .19 figure for horizontal beamwidth? I see a bearing accuracy of 13deg in the sources which would translate to about .13. 

Also, do you happen to have a year in-service? (Not a huge deal if not, just a nice-to-have.)

**Comment by HVAA** [comment]
Apologies, dont know how I wrote 19 instead of 13.

**Comment by PygmalionOfCyprus** [comment]
Happens to the best of us. Lemme know if you do dig up a year in service.

**Comment by bostonmyk** [comment]
Might be a domestic version of facility #3062-64. IOC prior to 2010 when the exports were delivered.

**Comment by PygmalionOfCyprus** [comment]
You're right. I've merged the two sensor entries.

**Comment by HVAA** [comment]
Cant find anything definitive, but there seems to be nothing about it prior to around 2013 in the older copies of the catlogs and online sources.  It starts to become more noticeable in search engines after 2016.

Sent from Mail for Windows
