### ISSUE TITLE
Russia - AA-10s Alamo [R-27]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1254]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

- [x] 1900 | AA-10 Alamo B [R-27T, MR IR] 1984?
- Name= AA-10B Alamo [R-27T, MR IR]
- Comments=1987, izdeliye 470-3
- AirRangeMax=35.1
- TargetAltitudeMax_ASL=24000.0

- [x] 1901 | AA-10 Alamo A [R-27R, MR TSARH] 1984
- Name= AA-10A Alamo [R-27R, MR TSARH]
- Comments=1987, izdeliye 470-1
- TargetAltitudeMax_ASL=25000.0

- [x] 2055 | AA-10 Alamo E [R-27P, MR ARM] 1994
- Name= AA-10E Alamo [R-27P, MR ARM]
- Comments=1987, izdeliye 470-4
- Weight=248.0
- AirRangeMin=1.08
- AirRangeMax=38.9
- TargetAltitudeMax_ASL=20000.0

- [x] 1899 | AA-10 Alamo C [R-27ER, LR TSARH] 1987
- Name= AA-10C Alamo [R-27ER, LR TSARH]
- Comments=1990, izdeliye 470-1E
- TargetAltitudeMax_ASL=27000.0

- [x] 1101 | AA-10 Alamo D [R-27ET, LR IR] 1987
- Name= AA-10D Alamo [R-27ET, LR IR]
- Comments=1990, izdeliye 470-3E
- AirRangeMax=43.2
- TargetAltitudeMax_ASL=30000.0

- [x] AirRangeMin
```
SET DataWeapon.AirRangeMin=0.3
WHERE DataWeapon.ID IN (1101, 1899, 1900, 1901);
```
(Basically, all but the P version.)

---
**DataSensor**
- [x] 2845 | TSARH Seeker (AA-10)
- Comments=AA-10, AGAT 9B-1101K
- RangeMax=16.2
- [x] 2844 | IR Seeker (AA-10)
- Comments=AA-10, Geofizika 36T
- RangeMax=27.0
- [x] 4118 | Passive Radar Seeker (AA-10)
- Comments=AA-10, 9B-1032
- RangeMax=45.0
---
- [x] **DataSensorFrequencySearchAndTrack** ID 2845 | TSARH Seeker (AA-10)
- Frequency=1010	J Band (10-20 GHz) [Old X Band] 1.5-3 cm
---

### Notes
- On names : Version letter appended to the missile number enhances readability. And it's thus in line with other NATO and US designation systems

- There's no documented differences between national and export version I could find. DB maintenance wise, I'm not sure the export version entries are worth their weight. Likewise, the ID 1319 "AA-10 Alamo F [R-27AE, LR ARH] (Cancelled)" and ID 2054 "AA-10 Alamo C [R-27EM, LR TSARH] (Cancelled, Naval, Anti-SSCM)" could be dropped.

> R stands for Radiynaya. Radiolocation/Radar
> T stands for Teplovaya. Heat/Thermal
> P stands for Passivnaya.
> E stands for Energeticheskaya. Energy/Power, Energetic.

Interestingly, as of 2017, and since 1983, all R-27 were produced at the Artem factory in Kiev, Ukraine. (Butowski) That factory would have been destroyed in late April 2022 : [Russia says struck Kyiv rocket plant with missiles | Reuters](https://www.reuters.com/world/europe/russia-says-struck-kyiv-rocket-plant-with-missiles-2022-04-29/)

### Sources

- Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![80-81 (2)](https://user-images.githubusercontent.com/35732829/170882608-c6875e31-8a39-4262-8614-6c9b31cf98c3.jpg)
![80-81 (3)](https://user-images.githubusercontent.com/35732829/170884326-ab3a6cf3-ac83-4e93-aa23-2b4ec12f3727.jpg)
![82-83 (2)](https://user-images.githubusercontent.com/35732829/170884856-8ca3de98-3fa4-4847-a953-fc4bf926fd13.jpg)
![84-85 (2)](https://user-images.githubusercontent.com/35732829/170888380-2b4a3f9a-290b-45df-9d23-7297ad13c064.jpg)

[GosMKB Vympel » Guided air-to-air missiles](https://web.archive.org/web/20121031134053/http://vympelmkb.com/products/prod01/)
[Artem - Air-to-air missile R-27](https://web.archive.org/web/20150906130134/http://www.artem.ua/en/produktsiya/aviation-means-of-attack-and-defense/air-to-air-missiles-r-27r1)

Cool illustrations from Artem's :
![image](https://user-images.githubusercontent.com/35732829/170884659-8d38adf4-e768-4134-8f38-2ba8d516de1e.png)
![image](https://user-images.githubusercontent.com/35732829/170888180-3757b1b3-96fe-48f7-ae5c-a712bdb11d46.png)![image](https://user-images.githubusercontent.com/35732829/170888183-afb7dfce-a542-48fb-b4e4-8980ba9a55b7.png)
![image](https://user-images.githubusercontent.com/35732829/170888257-0bc4950f-39ff-4194-92a0-18e2ea91371b.png)
![image](https://user-images.githubusercontent.com/35732829/170888271-0163ad2e-9f36-4e0c-9931-925fed061990.png)
![image](https://user-images.githubusercontent.com/35732829/170888279-10c9be43-7183-4fae-8758-6377f9d7790d.png)
![image](https://user-images.githubusercontent.com/35732829/170888286-da8ca56d-9f68-437f-8e50-e993c7f7309f.png)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.

Re: the deletions and things not worth their weight, I agree, but I can't remove anything from the database once a new version has been released for reasons of backwards compatibility w/ pro client custom DBs and older scenario migration.

**Comment by claudejdev** [comment]
> Fixed for 495.
> 
> Re: the deletions and things not worth their weight, I agree, but I can't remove anything from the database once a new version has been released for reasons of backwards compatibility w/ pro client custom DBs and older scenario migration.

Understandable. You would then flag and comment them as _Depreciated_?

**Comment by KLABDB3K** [comment]
The only observation I would make is that the R-27R1 etc export variants are "different" in terms of their ECCM, and codes for datalinks etc which are not immediately obvious as being modelled in the current CMO. 
It seems prudent to keep them not just for backward compatibility and ease of administration but also in case of a future incarnation of the sim starts to effectively model comms jamming or a more elaborate ECCM model?

**Comment by PygmalionOfCyprus** [comment]
^ I believe this is why they're in there. I'm generally in favor of modeling export variants even if just as copies because there are usually differences even if they aren't immediately modelable/apparent -- and it's way easier to change a single weapon entry down the line than go through and replace every loadout for foreign aircraft w/ export variants later.

**Comment by claudejdev** [comment]
That makes senses. Thanks for elaborating.

Would you want me to post suggested changes for the export variants too? The same as on the national version, though.

As for the P1, I've asked around to know if it actually has been exported. Waiting for an answer.
