### ISSUE TITLE
Loadout for Serbian H145M

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#1255]
### DB Selector

DB3K

### User(s)

Serbia H145M

### Weapons Carried

2x 12.7mm Gun pods
2x 80mm S-8k rocket pods
2x 57mm rocket pods

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Serbian H145Ms in the air force are equipped with Hforce and locally developed weapons have been integrated. The helicopters are also equipped with flir. The unarmed variant in the current DB reflects the version the Serbian Police are using.

### Sources

![images - 2022-05-30T203326 158](https://user-images.githubusercontent.com/99824301/170974702-932c6555-c31c-471f-880a-deda1a85ed56.jpeg)
https://www.flightglobal.com/helicopters/serbia-adds-locally-produced-weapons-to-h145m-fleet/135894.article

**Comment by TTZ32** [comment]
https://youtu.be/-6IV_w3oGdc

**Comment by PygmalionOfCyprus** [comment]
Added 495. I also did a minor rework of the H145Ms across the DB, replacing generic flare dispensers with (what appear to me to be) quad AN/ALE-47s, adding an advanced bombsight (for HForce), and standardizing NVGs.
