### ISSUE TITLE
Update PL-15 AAM's propulsion and range

### ISSUE THREAD

**Issue by ywturbo** [PygmalionOfCyprus/cmo-db-requests#1256]
### DB Selector

DB3K

### Affected DBID(s)

3413 & 3896

### Summary of Changes

Propulsion:  Engines changed from "Rocket Boost/Sustainer" to "Dual Pulse Rocket Motor"; Type changed from "Rocket [Boost & Coast]" to "Turbojet". For both PL-15 & PL-15E. 
Max range: changed from 94nm to 107nm for PL-15 (#3413).

Chinese PL-15 AAM reportedly uses a dual-pulse rocket motor, and its kinetic range  is up to 200km (107nm).

### Sources

https://en.wikipedia.org/wiki/PL-15
https://www.globalsecurity.org/military/world/china/pl-15.htm
http://chinese-military-aviation.blogspot.com/p/missiles-i.html

**Comment by PygmalionOfCyprus** [comment]
Is a dual pulse rocket motor not a sustained rocket booster? It's definitely not a turbojet.

**Comment by PygmalionOfCyprus** [comment]
I did adjust the max range on the domestic PL-15 to 108nm to put it in that 200km class. Keeping the export version down at 78.3nm as per the Zhuhai Air Show figures until we get info indicating otherwise.

**Comment by ywturbo** [comment]
In DB3K v493 AIM-120D AMRAAM (#51) with "Dual-Pulse Rocket  Motor" has a type tag of "Turbojet". I think PL-15 is similar to it.

![image](https://user-images.githubusercontent.com/104237162/171159845-ece181ba-2d46-4653-9e46-089fb2404062.png)

**Comment by PygmalionOfCyprus** [comment]
Aha, I see. I think that's an error, or potentially remnants of an old propulsion workaround from before we implemented the new boost-coast model. I've changed the AIM-120D's propulsion to type "Rocket [Boost & Coast]" and will update the PL-15's accordingly.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
