### ISSUE TITLE
Russia -1L122-1 or 2 Harmonium Target Acquistion Radar

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1257]
### DB Selector

DB3K

### Baseline

AN/UPS-3 Sentry or TDAR

### Hypothetical

No

### Name

1L122

### Sensor Generation

Late 2000s

### Range (nm)

43

### Sensor Capabilities

Air Search, Range Information, Speed Information, Heading Information

### Sensor Codes

Continuous Tracking Capability, Track While Scan (TWS), Moving Target Indicator (MTI), Low Probability of Intercept (LPI), Passive Electronically Scanned Array (PESA), Generates AAW Fire-Control Data

### Search/Track Frequencies

D Band (1-2 GHz) [Old L Band] 15-30 cm

### Lower Frequency (Hz)

1,215,000,000

### Upper Frequency (Hz)

1,400,000,000

### Scan Interval (s)

10 to 15 RPM

### Comments

This appears to be anagolous to Dog Ear, but updated to digital electronics.  Of course the band is different to Dog Ear (NATO D, as opposed to NATO F).  The quoted RFs are based on the available bandwidth in the D band, avoiding other emitters used by Russia.  D band would make sense as it lowers the 1st lobe so as to provide coverage as near to the surface as possible.  It used to be in the Rosoboronexport catalog, but alas no more.

From Source 1.

 The 1L122-1E (1L122-2E) radar makes it possible to detect the indicated types of air targets flying at a speed of up to 700 m / s at a range of 1-40 (1-80) km in a height range of at least 10 (20) km. In the detection zone of the station 360 deg. in azimuth and -5 (0) - +45 (60) degrees. in elevation, the mean square errors of determining the coordinates of a single target with an effective dispersion area (EPR) of 1 square m. under interference do not exceed 100 m in range, 0.5 (0.3) and 1.5 (1.0) degrees. in azimuth and elevation, respectively.

The data update rate for the 1L122-1E and 1L122-2E radars can be 2 (4) or 4 (10) s. respectively. The station is protected from local (55 dB), active noise (18 dB) and passive (40 dB) interference, which is quite high for a radar of this class. With a mass of 150 (900) kg the radar 1L122-1E (1L122-2E) has a fairly low power consumption, not exceeding 800 (5000) W, the power is supplied from a DC source with a voltage of 22-30 V. The dimensions of the antenna radar of both versions are 1200 x 800 mm.

Would therefore be suitable for cueing short range systems such as Pantsyr, TOR, Tungusta etc as well as MANPADS.

### Sources

1. https://www.globalsecurity.org/military/world/russia/garmon.htm
2. https://medium.com/indrastra/russia-unveils-new-1l122e-series-air-defense-radars-a53408989c81

**Comment by PygmalionOfCyprus** [comment]
Added 495. You can see the old Rosoboronexport pages using the Wayback Machine.
