### ISSUE TITLE
Corrections to SS-6 Sapwood (R-7) ICBM

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1258]
### DB Selector

CWDB

### Affected DBID(s)

Facility 1673, Weapon 1590

### Summary of Changes

Changes for the unit itself (DBID 1673 SSM Bn (SS-6 Sapwood) (Soviet Union [-1991] - 1959)-)

- Rename to **SSM Launch Pad (SS-6 Sapwood [R-7]) -- Soviet Union [-1991] (Strategic Rocket Forces), 1959-1965**
- Reduce number of mounts (DBID 2777 SS-6 Sapwood [R-7] TEL) to 1

Reasoning: The current description of "battalion" (Bn) does not accurately describe the way the R-7 was deployed. R-7s were deployed with units called Combat Launch Stations, which consisted of hundreds of personnel and support facilities. This was due to the primitive nature of the R-7 as an ICBM and weapon (it was effectively a space launch vehicle, with the associated complex and time costly preparations for firing).

Changes for the mount's weapon (DBID 1590 SS-6 Sapwood [R-7, 3.0mT Nuclear])

- Length should be changed to 31.07 meters
- Span should be changed to 11.2 meters
- Diameter should be changed to 11.2 meters
- Anti-land range should be increased to 4,266 nautical miles
- Rename to **SS-6 Sapwood [R-7, 3.0 mT Nuclear] -- 1959-1965**, that is, change the comment after the name from 1959-1968 to 1959-1965

Reasoning: For 1-3) These are simply inaccuracies in the technical characteristics of the weapon in real life, for 4) The R-7 currently does not actually have intercontinental range despite being an ICBM. This is the accurate anti-land range, for 5) The name of the weapon should be changed to reflect the change in the name of the unit.

### Sources

Information on the R-7's dimensions, anti-land range, and service history- **The Kremlin's Nuclear Sword: The Rise and Fall of Russia's Strategic Nuclear Forces, 1945-2000** by Steven J. Zaloga, page 232

Information on the deployment method of the R-7- **Soviet Armed Forces Order of Battle 1945-1991**, Strategic Rocket Forces, Combat Starting Stations, 42nd Combat Launch Station http://www.ww2.dk/new/rvsn/42bss.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. I basically converted the existing SS-6 entry to the Sapwood A (which was the actually operational version) -- note that because of this I've kept the out-of-service date to 1968 since that's when they retired it. The range is also now up to 4775nm.

One interesting thing I discovered is that these behemoths had a launch time of _8-12 hours_ from the go order. I've adjusted the mount ROF to 10hr as a result.
