### ISSUE TITLE
Increase (correct) the range of the SS-7 Saddler (R-16) ICBM

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1259]
### DB Selector

CWDB

### Affected DBID(s)

Weapon 1591

### Summary of Changes

- Increase anti-land range to 5,940 nautical miles

Reasoning: The R-16 ICBM currently does not actually have intercontinental range. This is the accurate anti-land range.

### Sources

For the R-16's anti-land range- **The Kremlin's Nuclear Sword: The Rise and Fall of Russia's Strategic Nuclear Forces, 1945-2000** by Steven J. Zaloga, page 232

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
