### ISSUE TITLE
Correct USN Trident D5 Loads

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#126]
### DB Selector

DB3K

### Affected DBID(s)

26, 28, 395, 396, 397, 398, 399, 400

### Summary of Changes

All the pre-2019 USN Trident D5 SSBN's have the newer 2019+ missile/warhead configurations.

### Sources

https://cmano-db.com/submarine/26/
https://cmano-db.com/submarine/28/
https://cmano-db.com/submarine/395/
https://cmano-db.com/submarine/396/
https://cmano-db.com/submarine/397/
https://cmano-db.com/submarine/398/
https://cmano-db.com/submarine/399/
https://cmano-db.com/submarine/400/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Also brought a little bit of order to chaos in the Trident D5 mounts.
