### ISSUE TITLE
SS-N-2 Styx [P-15] series correction

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1260]
### DB Selector

Both

### Affected DBID(s)

1365, 1364, 1477, 1597, 997

### Summary of Changes

- [x] SS-N-2a Styx [P-15] and SS-N-2b Styx [P-15U]:
- weight: 2100 kg
- length: 6.15 m
- diameter: 0.76 m
- cruise altitude: 656ft AGL, 200m AGL
- properties: remove terrain following (barometric altimeter)
- warheads: P-15 500kg Shaped Charge [390kg TGAG-5] (585 DP)
- propulsion: max speed 600 kts
- fuel, quantity: 3.3 minutes (estimated)*

- [x] SS-N-2c Improved Styx [P-15M]:
- name: **SS-N-2c Improved Styx [P-20]**
- weight: 2600 kg
- length: 6.75 m
- diameter: 0.76 m
- properties: add Terminal Maneuver Pop-up
- warheads: P-20 480kg Shaped Charge [370kg TGAG-5] (555 DP) /or more? **
- propulsion: max speed 600 kts
- fuel, quantity: 6.5 minutes*

- [x] SS-N-2d Improved Styx [P-20M], SSC-3 Styx [P-15M]:
- name: **SS-N-2d Improved Styx [P-21], SSC-3 Styx [P-21]**
- weight: 2600 kg
- length: 6.75 m
- diameter: 0.76 m
- cruise altitude: 82ft AGL, 25m AGL (<-- over sea, 820ft AGL, 250m AGL over land if possible)
- properties: add Terminal Maneuver Pop-up
- warheads: P-20 480kg Shaped Charge [370kg TGAG-5] (555 DP) /or more? **
- propulsion: max speed 600 kts
- fuel, quantity: 6.5 minutes*
- launch altitude: 0ft-2624ft ASL (for land based version)

*(although the max firing range of P-20/21/22 is 80km they have enough fuel to fly 120km if they don't find the target, that should be around 6.5 min worth of fuel)

**TGAG-5 probably also has 1.5x TNT equivalency. The missile has a considerable incendiary effect because it has much fuel left even at max range. Also P-20/21/22's warhead is at an angle of 45° which causes even more damage. During it's terminal approach on a target the shaped charge points down at almost 90° punching straight down through the deck causing flooding. Can this be modeled or would it just have more damage points?

### Comments

The SS-N-2 Styx series is often regarded as antiquated, but the newer versions are not that bad and have a few surprises.
Let's have a quick run through. There isn't much new to say about the original P-15 (SS-N-2a Styx). It is indeed very antiquated. It has a barometric altimeter which means that it isn't terrain following. The radar is susceptible to jamming (separate update request). The main difference of the P-15U (SS-N-2b Styx) are it's foldable wings, thus it can be stored in a more compact launcher. Apparently there were a few more upgrades but I couldn't find anything. These are the 1960s P-15 versions.

The 1970s P-20 and it's P-21 and P-22 versions are a different story. Despite similarities in appearance the SS-N-2c Improved Styx wasn't a mere upgraded version of the P-15. These are actually completely different missiles. Everything was redesigned, only the propulsion section is simmilar to the old one. It is 500kg heavier, has foldable wings, a new autopilot, the max firing range was increased to 80km but it has enough fuel to fly 120km. It has a radar altimeter enabling terrain following cruise flight at 50m AGL. The warhead is new and slanted by 45° to punch through the deck and cause flooding. The new solid state radar was very resistant to jamming and could tell when it's being jammed. It also has a few electronic tricks up its sleeve against jamming (which aren't further discussed in the sources). In it's terminal flight phase it makes a pop-up maneuver and dives down. The P-21 and 22 have all these features + a completely new autopilot and solid state radar altimeter which enables them to fly at 25m AGL over sea and 250m over land. These are fired by Rubezh launchers and ships. The main difference of the P-22 is it's dual spectral infrared seeker (separate request).

To explain the name changes: It is actually unclear where the P-15M and P-20M designations come from. Probably 30, 40 years ago these came into circulation for the lack of better sources and were cited again and again. P-20, P-21, P-22 are the real life designations and can be found engraved into some components.

### Sources

Yugoslav source pages 1, 2 and 6:
http://www.paluba.info/smf/index.php?topic=8506.msg52673;topicseen#msg52673

German Source:
https://www.parow-info.de/g/ga/P15M.html

https://imgur.com/a45xHp0

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
