### ISSUE TITLE
SS-N-2d Improved Styx [P-22, IR] and SSC-3 Improved Styx [P-22, IR]

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1261]
### DB Selector

DB3K

### Hypothetical

No

### Name

SS-N-2d Improved Styx [P-22, IR] and SSC-3 Improved Styx [P-22, IR]

### Length (m)

6.75

### Width/Span (m)

2.4

### Diameter (m)

0.76

### Weight (kg)

2600

### Range (nm)

4-45

### Launch Altitude / Depth (ft)

0ft-2624ft ASL (for land based version)

### Warhead

P-20 480kg Shaped Charge [370kg TGAG-5] (555 DP)

### Targets

Surface Vessel

### CEP (m)

6

### Sensors

1x IR Seeker (SS-N-2d [P-22])

### Weapon Codes

Terrain Following, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS Navigation, Weapon - Pre-Briefed Target Only, Terminal Maneuver - Pop-up, Level Cruise Flight

### Sources

http://www.paluba.info/smf/index.php?topic=8506.msg53290;topicseen#msg53290

https://www.parow-info.de/g/ga/P15M.html

**Comment by PygmalionOfCyprus** [comment]
Added 495.
