### ISSUE TITLE
Add 4 Nimrod missile loadout to Israeli Hermes 450 Ziq #2578

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1266]
### DB Selector

DB3K

### User(s)

2578

### Weapons Carried

4 Nimrod Missiles (Weapons 3494 and 3493)

### Requires Buddy Illumination

No

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

IDF is very secretive but pretty good evidence that Zik/hermes 450 is carrying Nimrods (see first IDF twitter picture). Wreckage of Ziq had missiles on 2 occasions. Spotters occasionally catch them. Looks like first pictures 2014.  Mikholit is Israeli name for Nimrod missile.

### Sources

https://twitter.com/IAFsite/status/1420373399046610946/photo/1
https://www.jforum.fr/experts-le-drone-disrael-crashe-au-liban-etait-arme.html
https://twitter.com/mansourtalk/status/1395804043365257217
https://southfront.org/israeli-hermes-450-armed-drone-spotted-over-hezbollah-stronghold-in-lebanon/
https://theaviationist.com/2014/07/30/weaponized-hermes-gaza/
https://www.forbes.com/sites/sebastienroblin/2021/05/26/israels-bombardment-of-gaza-methods-weapons-and-impact/?sh=7dda5c382f44

**Comment by PygmalionOfCyprus** [comment]
Added 495.
