### ISSUE TITLE
IR Seeker Styx P-22 data

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1267]
### DB Selector

DB3K

### Baseline

2596

### Hypothetical

No

### Name

IR Seeker (SS-N-2d [P-22])

### Sensor Generation

Late 1970s

### Range (nm)

10

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Speed Information, Heading Information

### Sensor Codes

Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Continuous Tracking Capability

### Scan Interval (s)

1

### Horizontal Beamwidth (deg)

0.8

### Vertical Beamwidth (deg)

0.8

### Comments

The PbS IR Seeker of the P-22 is dual spectral with 3.2-4.2 um (midwave ir) and 2-2.7 um (shortwave ir) sensitivity. It is cooled at -170°C and very smart as it can tell apart a target ship because of it's ir spectrum and size from ir flares which it would disregard as false targets. It's hard to spoof. The field of view is 0.8 degrees which is somewhere around 800mm focal length. The sensor then scans left and right. A fast missile boat could be tracked at 20km. It could also aquire fixed land targets. The sensor is called Snegir-M irl.

### Sources

http://www.paluba.info/smf/index.php?topic=8506.msg53290;topicseen#msg53290

**Comment by PygmalionOfCyprus** [comment]
Edited the entry I created earlier when I added the P-22s.
