### ISSUE TITLE
Add Altius 600 UAV loadout to the XQ-58 Valkyrie UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#127]
### DB Selector

DB3K

### User(s)

DBID 5168

### Weapons Carried

- 2x Altius 600 Recon UAV

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

1100nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Altius 600 was previously added in the DB as a weapon and aircraft. Valkyrie has successfully deployed the Altius 600 from the same launch tube as used for existing Viper Strike and SGM loads. Currently 2 Viper Strike in the DB so 2 Altius UAVs in a recon loadout is suggested

### Sources

https://www.thedrive.com/the-war-zone/40068/xq-58a-valkyrie-uses-weapons-bay-for-first-time-to-launch-smaller-drone
https://www.thedefensepost.com/2021/04/08/usaf-valkyrie-launches-drone/
https://theaviationist.com/2021/04/06/ever-seen-a-drone-dropping-another-drone-take-a-look-at-the-xq-58-valkyrie-releasing-an-altius-600-uas/
https://www.flightglobal.com/defence/unmanned-valkyrie-releases-altius-600-drone-in-sixth-test-flight/143193.article
https://www.defensenews.com/air/2021/04/05/the-valkyrie-drone-launches-an-even-smaller-drone-from-inside-its-payload-bay/

**Comment by PygmalionOfCyprus** [comment]
Already added as part of an earlier news roundup. Will be present 493.
