### ISSUE TITLE
Active Radar Seeker (SS-N-2c/d) update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1270]
### DB Selector

Both

### Baseline

4044 - Active Radar Seeker (ASM MR, SS-N-2c/d, SS-N-7)

### Hypothetical

No

### Name

unchanged

### Sensor Generation

Early 1970s

### Range (nm)

10

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Range Information, Speed Information, Heading Information

### Sensor Codes

Pulse-Only Radar, Frequency Agile

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

8,800,000,000

### Upper Frequency (Hz)

9,200,000,000

### Scan Interval (s)

1

### Peak Power (W)

50000

### Pulse Width (ms)

0,0005

### Comments

DSM-AE is the real life name of this seeker. It could aquire and track a target the size of a small missile boat at more than 15km. The peak power is higher than 40kW, the frequency is around 9GHz. It is described as having narrow radar lobes, is frequency agile and the pulse repetition frequency varies (not sure if this can be found under sensor codes) which makes it difficult to jam. It is very resistant to noise jamming and pulse jamming is very effectively recognised and disregarded as a false target. The pulse width is less than 0.5 us. This radar is an electronic conical-scan receive-only (COSRO) system.

### Sources

http://www.paluba.info/smf/index.php?topic=8506.msg52673;topicseen#msg52673

http://www.paluba.info/smf/index.php?topic=8506.msg56790;topicseen#msg56790

http://www.paluba.info/smf/index.php?topic=33669.msg590522#msg590522

see COSRO and jamming:
https://en.wikipedia.org/wiki/Conical_scanning

**Comment by PygmalionOfCyprus** [comment]
Done 495.
