### ISSUE TITLE
Add Spanish Heavy AAW 4 Meteor+2 Amraam, 2 IRIS-T, 2 Fuel Tank loadout for EF-2000

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1271]
### DB Selector

DB3K

### User(s)

3229,5507,3629,5508

### Weapons Carried

4 Meteors
2 Amraam C-5
2 IRIS-T
2 Drop Tanks

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Picture of 2022 Baltic Patrol below.

### Sources

https://www.reddit.com/r/WarplanePorn/comments/v36vgp/spanish_air_force_ef2000_during_nato_enhanced_air/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
