### ISSUE TITLE
Navy cancelled LCS ASW Module- Remove Captas VDS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1272]
### DB Selector

DB3K

### Affected DBID(s)

2594, 3089, 3155, 2595

### Summary of Changes

Remove sensor 5647 Type 2087 [Captas Mk4)

Doesn't look like it ever worked. 

### Sources

https://news.usni.org/2022/05/13/navys-cancellation-of-asw-mission-package-for-littoral-combat-ship-triggers-nunn-mccurdy-breach
https://www.janes.com/defence-news/news-detail/pentagon-budget-2023-us-navy-looks-to-cut-lcs-asw-module-decommission-9-freedom-class-ships
https://www.navalnews.com/naval-news/2022/05/admiral-gilday-explains-lcs-asw-and-mcm-module-decisions/

**Comment by PygmalionOfCyprus** [comment]
Removed for 495.
