### ISSUE TITLE
Decca 1216 update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1274]
### DB Selector

DB3K

### Affected DBID(s)

5643

### Summary of Changes

9380-9440 GHz
range to: 48nm

### Sources

https://imgur.com/lGY8uOM

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Though, following the source, I set the frequence to 9380-9440 _MHz_, not _GHz_, which would make for quite the radar. 😛

**Comment by nuk92** [comment]
whoops, this would be a what, lidar :joy:
