### ISSUE TITLE
Corrections to Project 71 aircraft carrier

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1275]
### DB Selector

CWDB

### Affected DBID(s)

Ship 310

### Summary of Changes

- Length should be changed to 199 meters
- Standard displacement should be changed to 10,600 tons and change damage points to an appropriate corresponding figure (I don't know how that works so I will leave it up to the DB manager)
- Crew should be changed to 580
- _Soviet Carrier Steam_ currently used on the unit should be replaced by _2x GTZA TV-7 Boilers & Steam Turbines_, like the ones on DBID 163 KR Chapaev. The Project 71 used the same hull as the Chapayev class cruisers. The max speed for the _GTZA TV-7 Boilers & Steam Turbines_ should be changed to 33.5 knots (this will also fix the max speed of the Chapayev in the DB, which is currently a bit low)
- Rename to **AN Project 71A CV -- Soviet Union [-1991] (Naval Fleet [V-MF]), 6x planned** (that is, change the name of the unit and the comment that comes after)
- Change year of entry into service to 1960

Reasoning: 1-4) these characteristics are incorrect currently, 5) This is the correct designation (Project 71A), while the Pr. 71A was referred to as an aircraft carrier (Avianosets), rather than an "aviation cruiser", so this is the correct type prefix, 6) This change is an estimate I created based on the actual state of the Soviet shipbuilding industry after the war as described in the source I listed, so it isn't strictly a factual error, but as someone who has read a lot about the Soviet Navy of that era, I feel that 1957 (the current in service date) is rather quick to establish an operational light carrier capability. This is based on known historical delays in the construction of large Soviet warships of that era (Sovetsky Soyuz, Stalingrad class, and Chapayev and Sverdlov class) and the challenges of creating a functioning carrier force from scratch that China's development with the Liaoning has shown us. However, as it isn't a historical fact, the change is entirely up to the DB manager ("a request") rather than an alert of a factually incorrect error.

### Sources

**Stalin's Ocean-Going Fleet: Soviet Naval Strategy and Shipbuilding Programmes 1935-1953** by Jurgen Rohwer and Mikhail S. Monakov, page 185 and 200

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. I opted just to remove the IS date altogether, since it was never commissioned and as far as I can tell there wasn't even a stated "goal date" -- it didn't make it far enough for one.
