### ISSUE TITLE
Corrections to Project 72 aircraft carrier

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1276]
### DB Selector

CWDB

### Affected DBID(s)

Ship 315

### Summary of Changes

- Length should be changed to 273 meters
- Beam should be changed to 33.5 meters
- Draft should be changed to 8.7 meters
- Standard displacement should be changed to 30,700 tons and change damage points to an appropriate corresponding figure (I don't know how that works so I will leave it up to the DB manager)
- Crew should be changed to 2,300
- Remove both _Hangar (18x Large Aircraft (18.1-26m Long))_ and replace with two _Hangar (20x Medium Aircraft (12.1-18m Long))_
- Rename to **AN Project 72 II-B CV -- Soviet Union [-1991] (Naval Fleet [V-MF]), 2x planned** (that is, change the name of the unit and the comment that comes after)

Reasoning: 1-5) these characteristics are currently incorrect, 6) This roughly brings it to the real life aircraft capacity (62x Tu-91 sized aircraft, in CMO "Medium Aircraft"). The current configuration allows it to carry 168x Tu-91 sized aircraft, which would have been physically impossible, 7) This is the correct designation (Project 72 II-B), while the ship was referred to as an aircraft carrier (Avianosets) and not an "aviation cruiser", and therefore AN would be the correct prefix.

### Sources

**Stalin's Ocean-Going Fleet: Soviet Naval Strategy and Shipbuilding Programmes 1935-1953** by Jurgen Rohwer and Mikhail S. Monakov, page 185 and 200

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Removed the IS date as w/ the Pr.71A.
