### ISSUE TITLE
Changes to Oktoberskaya Revolutsiya

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1277]
### DB Selector

CWDB

### Affected DBID(s)

Ship 266

### Summary of Changes

- Length should be changed to 282 meters
- Standard displacement should be changed to 72,950 tons and change damage points to an appropriate corresponding figure (I don't know how that works so I will leave it up to the DB manager)
- The max speed be lowered to 30 knots. The full throttle setting should become 25 knots
- Rename to **BB Project 24 -- Soviet Union [-1991] (Naval Fleet [V-MF]), 2x planned** (that is, change the name of the unit and the comment that comes after)
- Change the year of entry into service to 1959
- Although I don't actually have information for it, presumably an HE shell existed for the 406mm guns of the Project 24 class battleship. I would like to request the creation of an HE salvo for the 406mm/50 Mk1 Triple Soviet mounts on the unit, but as I don't have details for the HE shell the specifications and parameters of the HE salvo may be decided by the DB manager. I am putting this here instead of as a weapon request because of the lack of information

Reasoning: 1-3) these characteristics are currently incorrect, 4) The current name is rather confusing as it doesn't list the project number, while "Oktyabrskaya Revolutsiya" is the name of an actual Gangut class battleship, creating further confusion. Like other canceled Soviet ships in the DB, I suggest the name be changed to the project number alone, 5) This change is an estimate I created based on the actual state of the Soviet shipbuilding industry after the war as described in the source I listed, so it isn't strictly a factual error, but as someone who has read a lot about the Soviet Navy of that era, I feel that 1951 (the current in service date) is a completely unrealistic year for the Soviets to complete an Iowa sized battleship by. This is based on known historical delays in the construction of large Soviet warships of that era (like the Chapayev class) and historical problems with the construction of the pre-war Sovetsky Soyuz class battleships. However, as it isn't a historical fact, the change is entirely up to the DB manager ("a request") rather than an alert of a factually incorrect error, 6) it is highly likely the main guns would have HE shells. However, as there isn't any info for the shell (the Project 24 itself has scant information, not only because of Soviet secrecy but because the project did not progress to the same degree the Sovetsky Soyuz did), the change is entirely up to the DB manager ("a request") rather than an alert of a factually incorrect error

### Sources

**Stalin's Ocean-Going Fleet: Soviet Naval Strategy and Shipbuilding Programmes 1935-1953** by Jurgen Rohwer and Mikhail S. Monakov, page 185 and 195

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Removed date as with all the others.
