### ISSUE TITLE
Inf Plt (Netherlands Army)

### ISSUE THREAD

**Issue by saradedot** [PygmalionOfCyprus/cmo-db-requests#1278]
### DB Selector

DB3K

### Hypothetical

No

### Name

Inf Plt (Netherlands Army)

### Facility Type

Inf

### Country

Netherlands

### Service

Army

### In Commission

N/A

### Crew

16

### Dispersion Radius (m)

N/A

### Sensors

1x Mk1 Eyeball
4x Generic Binoculars

### Mounts

4x Infantry Section (7.62mm MG/Unguided Infantry Anti Tank Weapon)

### Magazines

N/A

### Aircraft & Docking Facilities

N/A

### Comments

Since it is the only infantry brigade within the Netherlands Army, I would suggest that the 11th Airmobile Brigade would be used as the template for the unit, when you look for a picture for example.

![miPycVX](https://user-images.githubusercontent.com/106709554/171948203-8054b3df-8f4f-49d9-96b6-e4ff07f8e7c5.jpg)

![Germany-Netherlands-sending-anti-tank-weapons-to-Ukraine](https://user-images.githubusercontent.com/106709554/171948338-92432b5a-bc14-44f5-bd03-6d817bffb6e0.jpg)
![d140520ge1131](https://user-images.githubusercontent.com/106709554/171948788-4ee02567-068c-40a2-9946-7618019fa4b3.jpg)

### Sources

* https://english.defensie.nl/topics/materiel/arms
* https://en.wikipedia.org/wiki/List_of_equipment_of_the_Royal_Netherlands_Army
* I suppose the pictures above are proof of them using the relevant equipment.

**Comment by PygmalionOfCyprus** [comment]
We're generally trying to move away from adding country/unit specific infantry facilities; I'm aware that some exist in the DB, but I think it makes more sense to use generics for these and add mounts/sensors/etc. + rename them in-editor rather than to create new DB entries.
