### ISSUE TITLE
Inf Plt (Netherlands Korps Mariniers)

### ISSUE THREAD

**Issue by saradedot** [PygmalionOfCyprus/cmo-db-requests#1279]
### DB Selector

DB3K

### Hypothetical

No

### Name

Inf Plt (Netherlands Korps Mariniers)

### Facility Type

Inf

### Country

Netherlands

### Service

Navy

### In Commission

N/A

### Crew

16

### Dispersion Radius (m)

N/A

### Sensors

1x Mk1 Eyeball
4x Generic Binoculars

### Mounts

4x Infantry Section (7.62mm MG/Unguided Infantry Anti Tank Weapon)

### Magazines

N/A

### Aircraft & Docking Facilities

N/A

### Comments

Additional to their other duties, in wartime the Korps Mariniers are supposed to operate within the umbrella of the British Royal Marines as a combined amphibious force (likely in Norway, which is why they regularly exercise there), because of this I would suggest that unit would be a copy of the British Royal Marines (DB3K no. 211) unit.

![korps mariniers](https://user-images.githubusercontent.com/106709554/171947332-b3dc1614-36fe-47b9-bccb-a5dc22a501e1.jpg)

![d150310ge2045](https://user-images.githubusercontent.com/106709554/171947278-da6f1a1e-6971-4a2a-97a3-118f3d8b7ec9.jpg)

![korps marinier-2](https://user-images.githubusercontent.com/106709554/171946074-606535b9-5e1c-473f-a6f3-387e37df3ea6.jpg)

![mariniers-in-actie-in-de-woestijn](https://user-images.githubusercontent.com/106709554/171949050-4333e54b-ccbe-425b-8dfa-16df7560f190.jpg)

### Sources

* https://english.defensie.nl/topics/materiel/arms
* https://en.wikipedia.org/wiki/Netherlands_Marine_Corps#Equipment
* Likewise to the Army, the above pictures should suffice as proof of them using the relevant weapons.

**Comment by PygmalionOfCyprus** [comment]
See [#1278](https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1278#issuecomment-1147199800)
