### ISSUE TITLE
Add River Class OPV to Bahrain

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#128]
### DB Selector

DB3K

### Hypothetical

No

### Name

RBNS Al-Zubara (80)

### Class

DBID 2806 transferred from UK in 2020

### Country

Bahrain

### Service

Navy

### In Commission

2020-Present

### Length (m)

Copy DBID 2806

### Beam (m)

Copy DBID 2806

### Draft (m)

Copy DBID 2806

### Standard Displacement (t)

Copy DBID 2806

### Full Displacement (t)

Copy DBID 2806

### Empty Displacement (t)

Copy DBID 2806

### Complement

Copy DBID 2806

### Max Sea State

Copy DBID 2806

### Primary Propulsion Type

Diesel

### Propulsion

Copy DBID 2806

### Fuel Capacity (kg)

Copy DBID 2806

### Flank Speed (kt)

Copy DBID 2806

### Range (nm) at Speed (kt)

Copy DBID 2806

### Sensors

Copy DBID 2806

### Mounts

Copy DBID 2806

### Aircraft & Docking Facilities

Copy DBID 2806

### Comms/Datalinks

Copy DBID 2806

### Comments

HMS Clyde P-257 transferred to Bahrain in 2020 as RBNS Al-Zubara (80)

### Sources

https://ukdefencejournal.org.uk/hms-clyde-sold-to-bahrain/?fbclid=IwAR2uFy5eWrpmlhLzCdDm6INmEkP-6yIGNk5t3Wkh2qF7grO4ZabO_HL2vS0

**https://www.janes.com/defence-news/news-detail/bahrain-commissions-new-naval-vessels**

![download](https://user-images.githubusercontent.com/99599482/154353920-8dc4700b-34b5-4401-a98c-62985ce12119.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 493. Adjusted mounts in new version; the Bahranis evidently swapped out her guns.
