### ISSUE TITLE
Russia - AA-7s Apex [R-23, R-24]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1280]
### DB Selector

Both

### Affected DBID(s)

*

### Summary of Changes

**DataWeapon**

- [x] ID 789 | AA-7 Apex B [R-23T, IR] - 
- [x] _<also applies to CWDB ID 747 - AA-7 Apex B [R-23T, IR]>_
- Comments=1974, izdeliye 360
- AirRangeMax=5.1

- [x] ID 790 | AA-7 Apex A [R-23R, SARH] 1974
- [x] _<also applies to CWDB ID 746 AA-7 Apex A [R-23R, SARH]>_
- Comments=1974, izdeliye 340
- AirRangeMax=14.6

- [x] ID 151 | AA-7 Apex D [R-24T, IR] 1981
- [x] _<also applies to CWDB ID 1499 - AA-7 Apex D [R-24T, IR]>_
- Comments=1981, izdeliye 160
- Length=4.6
- Weight=250.0
- AirRangeMax=27.0

- [x] ID 152 | AA-7 Apex C [R-24R, SARH] 1981
- [x] _<also applies to CWDB ID 1498 - AA-7 Apex C [R-24R, SARH]>_
- Comments=1981, izdeliye 140
- Weight=270.0
- AirRangeMax=27.0

- [x] TargetAltitude DB3K
```
UPDATE DataWeapon SET DataWeapon.TargetAltitudeMax_ASL=25000.0, DataWeapon.TargetAltitudeMin_ASL=40.0
WHERE DataWeapon.ID IN (151,152,789,790);
```
- [x] TargetAltitude CWDB
```
UPDATE DataWeapon SET DataWeapon.TargetAltitudeMax_ASL=25000.0, DataWeapon.TargetAltitudeMin_ASL=40.0
WHERE DataWeapon.ID IN (746,747,1498,1499);
```

---
**DataSensorFrequencySearchAndTrack**
- [x] DB3K ID 708 | SARH Seeker, AA-7 Apex A [R-23R, SARH] (N/A - 0)
- [x] ID 4086 - SARH Seeker AA-7 Apex C [R-24R] operates in that band too. _Estimate_
- [x] CWDB ID 879 | SARH Seeker AA-7a
- [x] CWDB ID 2449 - SARH Seeker AA-7c
- Frequency=1010 (J Band (10-20 GHz) [Old X Band] 1.5-3 cm)

---

### Notes
- DB3K ID 2064 | AA-7 Apex E [R-24MR, SARH] is not mentioned in my ref book.
- I haven't been able to find a documented minimal range. Could it be a DB design/gameplay decision?
- Would there be guidelines for AirPoK ? It seems to be “generational”.
- I'm not confident on how to input a "command guidance in the mid-course".

### Sources

- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![78-79 (2)](https://user-images.githubusercontent.com/35732829/171955528-f2d4191e-e11a-4642-a9dd-d68b2eaef50a.jpg)
![78-79 (3)](https://user-images.githubusercontent.com/35732829/171955515-16338382-dc2b-495a-aafb-07190e0736ec.jpg)
![80-81 (2)](https://user-images.githubusercontent.com/35732829/171955489-54c931b5-14ab-4145-905a-f12bd564cb47.jpg)

**Comment by PavelNovak79** [comment]
On www.secretprojects.co.uk forum is cited russian source for R-24R and R-24T and giving same max range for both missiles and that is 50 km (27 nm).

See forum here: https://www.secretprojects.co.uk/threads/r-23-r-24-r-27-aam.60/page-3

And here directly detailed graph: https://www.secretprojects.co.uk/attachments/r-24-jpg.666554/

**Comment by PavelNovak79** [comment]
I am not aware of such graph for R-23R and R-23T but I think that these missiles has same maximum range similarly to R-24R and R-24T. For R-23R/T maximum range of 25 km (14 nm) is probably correct.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. I suspect the Janes numbers are reflecting seeker capability. The engine on the R-23s was probably capable of the same range but the seeker may well not have been.
