### ISSUE TITLE
Japan - AAM-4B Kai [Type 99]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1284]
### DB Selector

DB3K

### Affected DBID(s)

1199 - AAM-4B Kai [Type 99]

### Summary of Changes

**DataWeapon**
- Comments=2011?
- AirRangeMax=64.8

### Sources

- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![76-77 (2)](https://user-images.githubusercontent.com/35732829/171965866-9819e13b-0a87-45e9-b6fe-a1235ca2b458.jpg)
![78-79 (2)](https://user-images.githubusercontent.com/35732829/171966082-ebf18f7d-8327-4383-808d-b0559715d849.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Also made a number of other small changes incl. to the sensor.
