### ISSUE TITLE
Japan - AAM-4 [Type 99]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1285]
### DB Selector

DB3K

### DBID to Copy

1199 - AAM-4B Kai [Type 99]

### Hypothetical

No

### Name

AAM-4 [Type 99]

### Country

na

### Service

na

### In Commission

2001

### Other Changes

**DataWeapon**
- Comments=2001
- AirRangeMax=54.0

### Sources

- IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global.

![76-77 (2)](https://user-images.githubusercontent.com/35732829/171965866-9819e13b-0a87-45e9-b6fe-a1235ca2b458.jpg)
![78-79 (2)](https://user-images.githubusercontent.com/35732829/171966082-ebf18f7d-8327-4383-808d-b0559715d849.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Couple more tweaks as well.
