### ISSUE TITLE
WC-135W Constant Phoenix, 2022-  Complete (COMP)

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#1288]
### DB Selector

DB3K

### DBID to Copy

#.1984 KC-135R Stratotanker, United States, Air Force, 1997

### Hypothetical

No

### Name

WC-135R Constant Phoenix, 2022-

### Country

United States

### Service

Air Force

### In Commission

2022-

### Sensors

_"The WC-135W Constant Phoenix atmospheric collection aircraft supports national level consumers by collecting particulate and gaseous effluents and debris from accessible regions of the atmosphere in support of the Limited Nuclear Test Ban Treaty of 1963."_ [1]

_"The WC-135’s sampling and collection suite allows mission crew to detect radioactive “clouds” in real time. The collection system uses external flow-through devices to collect particles on filter paper for later analysis. The podded particulate sampler/Radiation Monitoring and Analysis System (RMAS) detects radiation contact, and the Directional Gamma Sensor System (DGSS) guides the crew toward the plume for collection. The Whole Air Collection System (WACS) captures and stores radioactive samples from the aircraft’s bleedair system."_ [4]

**1. Sensors/EW.**

Data is not really available for this just guessing here.
 
-  Remove **AN/APN-59 Radar #.2678**.
-  Add same **Radar** as #1282.
-  Add **Generic ESM [Advanced] #.6570**.
-  Add **Generic Atmospheric Collection Suite** (This will have no function currently but who know what the future holds).

**2. Comms/Datalinks.**

Very little data on this plane so going with the same as the RC-135 Planes.

-  **Add** #.187 UHF/VHF Radio [Secure], Radio. 
-  **Add** #.72 HF Radio [Secure], Radio.
-  **Add** #.217 Link 11, Type - Link 11, Tactical Digital Information Link TADIL/A.
-  **Add** #.52 Link 16 JTIDS (MIDS on Ship), Type - Link 16.
-  **Add** AEHF SATCOM Uplink.  _(Currently does not exist in DB but as stated below its been fitted to all RC-135 and B-52)_

### Mounts

**N/A**

### Loadout Options

-  **Ferry** (Not sure if this calculated differently to the range), (Currently **DB ID #.8836**)
-  **Maintenance** [Unavailable], (**DB ID #.4**)
-  **Reserve** [Available], (**DB ID #.3**)
-  **Air Sampling** [Area Surveillance], (Currently **DB ID #.19801**), _Range of this is possibly decreased given Range of 3900nm unrefueled_

### Other Changes

**1. General Data.**

-  Change **Aircraft type** from Tanker (Air Refueling) to Nuclear Air Sampling (Area Surveillance).
-  **Max Ceiling** 15,240m (50,000 feet). [4]
-  Increase **Crew** from 3 to 3x Flight Crew (2x Pilots, 1x Navigator), up to 31x Special Equipment Operators/Observers. [4]
-  **Range:** 3900nm. [4]

**2. Properties.**

-  Remove **Wing Drogue**.
-  Remove **Centerline Boom**.
-  Add **Boom Refuelling**.

### Sources

[1]   https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104494/wc-135-constant-phoenix/
[2]   https://www.dacis.com/budget/budget_pdf/FY20/PROC/F/DARP01_55.pdf
[3]   https://www.af.mil/News/Article-Display/Article/1058221/kc-135-mod-program-closes-out-year-with-magic-number-block-45/
[4]   https://www.airforcemag.com/weapons-platforms/wc-135/
[5]   https://en.wikipedia.org/wiki/Boeing_WC-135_Constant_Phoenix
[6]   https://irp.fas.org/program/collect/constant_phoenix.htm
[7]   https://www.globalsecurity.org/intell/systems/constant_phoenix.htm
[8]   https://nationalinterest.org/blog/buzz/united-states-deploys-nuclear-sniffing-aircraft-europe-201164
[9]   https://www.key.aero/article/usafs-nuclear-particle-hunter

**Comment by PygmalionOfCyprus** [comment]
Added 496, sans the placeholder Atmospheric Collection Suite. We don't even have a sensor role to support that, so rather than create a bunch of new enums for a placeholder that likely won't ever become functional I'll just let people use their imagination.

I anticipate any use of this in-game will be supported by Lua or used purely as window dressing so it should be okay.

**Comment by PygmalionOfCyprus** [comment]
I also added a 1965- version with downgraded sensors and less gizmos.

**Comment by 5th-Domain** [comment]
Yer i agree with that i always envisioned using this with Events and/or Lua.
