### ISSUE TITLE
TC-135W Rivet Joint, 2x Training Aircraft for RC-135V/W Rivet Joint, 2020-  Complete (COMP)

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#1289]
### DB Selector

DB3K

### DBID to Copy

RC-135W Rivet Joint, Baseline 13, 2020- Complete (COMP) #1282

### Hypothetical

No

### Name

TC-135W Rivet Joint Trainer, 2020-

### Country

United States

### Service

Air Force

### In Commission

2020-

### Sensors

**N/A**

### Mounts

**N/A**

### Loadout Options

-  **Ferry** (Not sure if this calculated differently to the range), (Currently **DB ID #.8825**)
-  **Maintenance** [Unavailable], (**DB ID #.4**)
-  **Reserve** [Available], (**DB ID #.3**)
-  **SIGINT** [Area Surveillance, Training], (Currently **DB ID #.8824**), _Range of this is possibly decreased given Range of 3500 nm unrefueled_

### Other Changes

**N/A**

### Sources

[1]   https://en.wikipedia.org/wiki/Boeing_RC-135

**Comment by PygmalionOfCyprus** [comment]
Are we certain the trainers have also received the upgrades that the main aircraft have, e.g. re-engine, etc.? The TC-135W was apparently first in service in 1987 so I'm going to at least create a version off of the older RC-135; whether we can confirm there were in fact upgrades to the trainer will determine whether I also create another version.

**Comment by 5th-Domain** [comment]
From what i remember reading the Training versions do not contain all the equipment but it does not say what is or in not fitted. I think they will probably received upgrades but not at the rate of the Inservice planes (this is just a guess). Maybe just give them ESM and the new radar. I've not come across anything saying there are newer training versions available. 

_"Training at Offutt is supported by three TC-135Ws. Like the tankers, the Stratolifter-based RC/TC-135s have all been re-engined with F108 turbofans. The use of dedicated trainer aircraft was first introduced in July 1985 when the 6th Strategic Aerospace Wing at Eielson AFB, Alaska, accepted a TC-135S to augment Cobra Ball aircrew training. To maintain the Cobra Ball mystique, the TC-135S featured the same black wing and engine nacelles, despite this feature not being necessary. The success of the trainer enabled sister unit, the 55th Strategic Reconnaissance Wing (SRW), to follow, with a single TC-135W entering service in April 1988. Periods of regular maintenance and major overhaul resulted in a single TC-135W being unable to fulfil the training mission and a second was funded, then delivered in August 2005. All three are now known as TC-135Ws and remain pure trainers with no mission equipment installed, although TC-135Ws serials 62-4127 and 62-4129 feature dummy ‘cheeks’ and the extended ‘hog nose’ for aerodynamic reasons, whereas former TC-135S serial 62-4133 features the ‘hog nose’ but no ‘cheeks’."_ [1]

[1] https://www.keymilitary.com/article/still-going-strong-special-mission-aircraft

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
