### ISSUE TITLE
TC-135S Cobra Ball, 1x Training Aircraft for RC-135S Cobra Ball, 2020- Complete (COMP)

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#1290]
### DB Selector

DB3K

### DBID to Copy

RC-135U Combat Sent, Baseline 6, 2020- Complete (COMP) #1286

### Hypothetical

**No**

### Name

TC-135S Cobra Ball Trainer, 2020-

### Country

United States

### Service

Air Force

### In Commission

2020-

### Sensors

**N/A**

### Mounts

**N/A**

### Loadout Options

-  **Ferry** (Not sure if this calculated differently to the range), (Currently **DB ID #.14464**)
-  **Maintenance** [Unavailable], (**DB ID #.4**)
-  **Reserve** [Available], (**DB ID #.3**)
-  **TECHINT** [Area Surveillance, Training], (Currently **DB ID #.8826**), _Range of this is possibly decreased given Range of 4000 nm unrefueled_
### Other Changes

**N/A**

### Sources

[1]   https://en.wikipedia.org/wiki/Boeing_RC-135

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
