### ISSUE TITLE
Rubezh launchers (P-21 and P-22)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1291]
### DB Selector

DB3K

### Affected DBID(s)

301, 649, 914, 2131, 963, 651, 652, 765, 1346, 900, 1345, 816, 826, 894 - all Rubezh launchers

### Summary of Changes

Change weapons per mount to:
1x SSC-3 Improved Styx [P-21]
1x SSC-3 Improved Styx [P-22, IR]

Change magazines to one combined P-21,P-22 magazine if possible:
SSC-3 Improved Styx [P-21/P-22] (max 4):
stores: 2x SSC-3 Improved Styx [P-21] & 2x SSC-3 Improved Styx [P-22, IR]

SSC-3 Improved Styx [P-21], SSC-3 Improved Styx [P-22,IR] and SS-N-2d Improved Styx [P-22,IR]:
-add valid targets: Land Structures Hard & Soft

A mix of P-21 and P-22 missiles was usually carried and fired by Rubezh launchers and ships which were able to use these missiles. This would further decrease the effectiveness of ECM vs a Styx missile attack. It was also specifically stated (by the manufacturer) that P-21 and P-22 missiles could be used to strike large land structures; better than the P-15 (where it wasn't stated but it was still used to strike the port of Karachi in 1971).

### Sources

http://www.paluba.info/smf/index.php?topic=8506.msg56790;topicseen#msg56790

google translate:
> In the case of P-21 and P-22 missiles, shooting at targets on land is also mentioned as an additional purpose.
What is it about: the radar and IR head of these missiles could capture certain targets on land and with a high probability bring the missile to them... In the case of a stationary target, and well-calculated initial elements for shooting, a fairly stable ground target lock on could be achieved. We tried this in practice and it worked, although it turned out that the lock on was never as stable as with surface targets at sea.

http://www.paluba.info/smf/index.php?topic=8506.30

> According to Soviet instructions, there were always missiles of various types in the missile salvo, which were set to approach the target at various altitudes. Usually a combination of 1 IR and 1 active radar homing or 1 IR and 2 active radar homing were used. In the latter case, the frequencies of the radar head were always different.

**Comment by PygmalionOfCyprus** [comment]
What are those DBIDs for? Are they mounts, or...? None of them point to relevant mounts in DB3K.

**Comment by nuk92** [comment]
The ID for the mount is 696 (SSC-3 Styx TELAR [3P51]). I gave you the IDs for the SSM Plt (SSC-3 Styx [4K51 Rubezh]), didn't think it through. This applies to CWDB too.

**Comment by nuk92** [comment]
The magazine 156 -  SSC-3 Styx would have to be updated as well to allow for both the P-21 and P-22 to be stored.

**Comment by PygmalionOfCyprus** [comment]
Derp. That's on me. Not sure why I didn't think to try the IDs in Facilities...anyway, fixed 495.
