### ISSUE TITLE
Current Venezuelan satellite entries are actually Australian? Australia has no satellites available in the DB and Venezuela has launched 3 satellites to date.

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#1292]
### DB Selector

DB3K

### Affected DBID(s)

116

### Summary of Changes

I will be making separate entries for the 3 Venezuelan satellites. Currently in DB3K, Venezuela has 2 satellites listed as in orbit: Centauri 1 and Centauri 2. 

Both of these satellites are operated by Australia. See sources below. I'm not sure how this happened in the first place, but swapping their control from Venezuela to Australia seems to be the obvious way forward. 

Venezuela has launched 3 satellites itself (1 of which is disabled as of 2020) which will be covered in further DB requests. 

### Sources

https://sky-brokers.com/satellite/centauri-1/

https://space.skyrocket.de/doc_sdat/centauri-1.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
