### ISSUE TITLE
Corrections to Soviet battlecruisers (Kronshtadt and Stalingrad classes)

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1296]
### DB Selector

CWDB

### Affected DBID(s)

Ship 619, Ship 617, Ship 623, Ship 618

### Summary of Changes

There a some inaccuracies with the canceled Soviet battlecruisers (Kronshtadt and Stalingrad classes). The biggest one is that all four have a much larger displacement than in real life.

Changes to DBID 619 KR Kronshtadt -- Soviet Union [-1991] (Naval Fleet [V-MF]), 1949, Cancelled Project
- Draft should be changed to 8.9 meters
- Standard displacement should be changed to 35,240 tons with a corresponding change in damage points. I don't know how that is calculated so it can be decided by the DB manager
- Crew should be changed to 1037
- The armor thickness' to be changed are as follows, and should be changed to the corresponding level (light, medium, etc.) within the database- Belt: 230 millimeters, Bulkhead: 330 millimeters, Deck: 120 millimeters, Engineering: 275 millimeters, Bridge: 50 millimeters, CIC: 330 millimeters
- Rename to **TKR Pr. 69K Kronshtadt -- Soviet Union [-1991] (Naval Fleet [V-MF]), x1, never completed** (that is, change the name and the comment that comes after)
- Change year of entry into service to 1955

Reasoning: 1-4) The current characteristics are incorrect, 5) The Kronshtadt class were classified as heavy cruisers (Tyazheliye Kreisera), and thus TKR would be the correct prefix. Because the Kronshtadt class has the same weapons as the Stalingrad class, instead of its pre-war weapons, and the Kronshtadt class could indeed have had these fitted as it was in an early stage of construction when the war started, I suggest giving it the project designation "Project 69K" (K for "corrected"). This would be similar to the actually completed Chapayev class, which was designated Project 68K after having its weapons updated when construction of the class resumed following the end of the war. The Kronshtadt class had two examples laid down but only one survived the war in a state allowing for construction to resume after the war, 6) This change is an estimate I created based on the actual state of the Soviet shipbuilding industry after the war as described in the source I listed, so it isn't strictly a factual error, but as someone who has read a lot about the Soviet Navy of that era, I feel that 1949 (the current in service date) is a completely unrealistic year for the Soviets to complete the ship by. This is based on known historical delays in the construction of large Soviet warships of that era (like the Chapayev class) and historical problems with the construction of the pre-war Sovetsky Soyuz class battleships. However, as it isn't a historical fact, the change is entirely up to the DB manager ("a request") rather than an alert of a factually incorrect error

Changes to all three Stalingrad class cruisers in the DB (DBID 617, DBID 623, and DBID 618)
- Draft should be changed to 8.7 meters
- Standard displacement should be changed to 36,500 tons with a corresponding change in damage points. I don't know how that is calculated so it can be decided by the DB manager
- The crew is actually 1710, currently it is 1712, because it is such a small difference the DB manager can decide whether to actually implement this change or not
- The armor thickness' to be changed are as follows, and should be changed to the corresponding level (light, medium, etc.) within the database, Belt: 180 millimeters, Bulkhead: 140 millimeters, Deck: 95 millimeters, Bridge: 250 millimeters, CIC: 250 millimeters
- Max speed should be changed to 35.2 knots. Cruise throttle should be changed to 17 knots, full throttle should be changed to 30 knots. Fuel consumption should remain the same for all. A new engine DB entry will probably need to be made as it appears the Kronshtadt (DBID 619) uses the same one currently, but it not need to have its speed parameters changed
- For DBID 618 only: The _Hangar (1x Medium Aircraft)_ should be removed. _Open Parking Spot (1x Medium Aircraft)_ should replace it
- For DBID 617 only: Rename to **TKR Pr. 82 Stalingrad -- Soviet Union [-1991] (Naval Fleet [V-MF]), 7x planned, 2x laid down, never completed** (that is, change the name and the comment that comes after)
- For DBID 623 only: Rename to **TRKR Pr. 82R Arkhangelsk -- Soviet Union [-1991] (Naval Fleet [V-MF]), 1961, SS-N-2, 1x laid down, never completed** (that is, change the name and the comment that comes after)
- For DBID 618 only: Rename to **TRKR Project 82Rbis -- Soviet Union [-1991] (Naval Fleet [V-MF]), 1963, SS-N-3, 4x proposed** (that is, change the name and the comment that comes after)

Reasoning: 1-6) the current characteristics are incorrect, 7) The Stalingrad class were classified as heavy cruisers (Tyazheliye Kreisera), and thus TKR would be the correct prefix. Project 82 is the project number and 7x were planned to be built, 8) The actual project designation of this conversion was Project 82R, while the "TRKR" is based on the real life designation of the Project 58 class cruisers as "Raketniye kreisera" (rocket cruisers) and the fact that the Stalingrad class were heavy cruisers (thus "heavy rocket cruisers"), while the first ship to be converted had been given the name Arkhangelsk, 9) Modifications with more powerful anti-ship missiles were only given cursory attention before the Stalingrad class were canceled, unlike how the SS-N-2 modification actually had work begin, and therefore "Proposal" were be a better description of the unit, while as no ships actually had this modification, it would make more sense to give the unit a project number only and not a name, the "bis" (improved) designation is based on how the actually completed Project 58 (Kynda class) cruisers were designated Project 58bis upon receiving improvements

### Sources

**Stalin's Ocean-Going Fleet: Soviet Naval Strategy and Shipbuilding Programmes 1935-1953** by Jurgen Rohwer and Mikhail S. Monakov, pages 96, 196, 197, 230, 276

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
