### ISSUE TITLE
Philips 9KR409 surface surveillance radar

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1297]
### DB Selector

DB3K

### Baseline

3234

### Hypothetical

No

### Name

9GA205 [9KR409] (9KR400 Mareld)

### Sensor Generation

Early 1980s

### Range (nm)

0.1-65.0

### Sensor Capabilities

Air Search, Surface Search, Periscope Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Track While Scan (TWS), Periscope/Surface Search - Fine Range Resolution + Rapid Scan [1980+], Pulse Doppler Radar (Full LDSD Capability), Frequency Agile

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

8,700,000,000

### Upper Frequency (Hz)

9,500,000,000

### Scan Interval (s)

2

### Target Altitude (ft)

0ft - 10500ft ASL (estimated)

### Horizontal Beamwidth (deg)

0.6

### Vertical Beamwidth (deg)

4.5

### Processing Gain/Loss (dB)

40

### Peak Power (W)

200000

### Pulse Width (ms)

0.001

### PRF (Hz)

1200

### Comments

The Philips 9KR409 is a surface surveillance radar from the family of Swedish 9LV radars. It incorporates solid state technology. It was used by the Yugoslav Navy as a mobile radar mounted on a TAM 150 truck. The range is (120km) 65nm - 1nm (this can be seen, there are buttons for different range settings). This radar is hard to jam since it is frequency agile and has a band width of 450MHz (sometimes described as freqeuncy agility of 450MHz). The pulse repetition frequency also varies (algorithm) which also makes jamming more difficult. It has a very fine range resolution and precision. As an example how precise it is: after an exercise it was used to locate a training torpedo that was lost and floating on the sea surface. Would this also count as periscope search? It also has an MTI mode (however I'm not sure how this would influence it's capability if added since this is a mode that you can turn on and off if needed). The radar can detect low flying objects and has a missile warning mode. The detection height is an estimation based on the 5000 meter max detection alt of the 9LV search radar which has 7° vertical beamwidth vs 4.5° of this radar. The 9KR409 was used with the Swedish 9CSI 600 Stina C3I system (Stina Jadran version made for Yugoslavia). Radar data could be shared with datalinks between ships and different surveillance radars and could be used as targeting data (separate request).

-------

There isn't much information if you disregard ex Yugo and Montenegrine sources, simply because a search for the 9KR409 yields no other results. However there is the 9KR400 and on the paluba forum it is stated that these radars are allmost if not completely the same. The Philips 9GR600 seems to be the common transmitter of all or most 9LV surveillance radars but they have different antennas: 9GA209 antenna (2.1x0.3m), 9GA202 (2.1x0.56m), 9GA205 (4.5x0.625m). There seems to be some commonality between the the 9LV209 fire control system (or some part of it) and the 9KR409. (The 9LV209 has the 9LV200 Mk2 targeting sensor group). However the 9KR409 doesn't have the 2 meter 9GA209 antenna but rather a 4.5m antenna, maybe the 9GA205. So as you see it isn't quite clear and gets complicated. I can make a seperate requests for the other radars in the 9LV series, there just isn't much info on the radar range.

### Sources

https://imgur.com/APN7Ac7

https://imgur.com/MmfPTNj

https://imgur.com/9M192yq

https://imgur.com/7e4FZ91

http://www.paluba.info/smf/index.php?topic=19029.0

http://www.paluba.info/smf/index.php?topic=19029.msg368017#msg368017

> The maximum range of the radar was 60 miles and its precision was great, after one exercise it found a training torpedo that was fired and lost floating on the surface of the sea.

page 10, 120km range:
https://www.etf.bg.ac.rs/uploads/files/javni_uvid/izvestaji/doktorske/2016/Zoran_Djordjevic_doktorska_disertacija.pdf

https://imgur.com/lZz0qVe

https://imgur.com/b39uC61

http://www.paluba.info/smf/index.php?topic=20881.msg284585;topicseen#msg284585

> U KIS Stina Jadran važan dio sačinjava radar tipa 9KR409. Osmatrački je radar za otkrivanje i praćenje kako površinskih objekata na moru, tako i niskoletećih objekata u vazduhu.

> In KIS Stina Jadran an important part is the radar type 9KR409. It is an observation radar for detecting and tracking both surface objects at sea and low-flying objects in the air.

> MISSILE SURVEILLANCE
With the help of this command, a form is called on the screen of the text of the terminal, in which data on the areas where the automatic monitoring of the appearance of missile weapons will be performed are entered. The center of the missile surveillance area can be determined as a geographical position or by entering your own designation of the object that is a potential carrier of missile weapons.
In this way, the extractor automatically reacts to the appearance of a missile projectile and sends an alarm about the immediate missile danger.

**Comment by nuk92** [comment]
Here is a picture for this sensor and for the 9KR400 Mareld:
![](https://i.imgur.com/ORhvaP9.png)

**Comment by PygmalionOfCyprus** [comment]
You're gonna have to break down "9GA205 [9KR409] (9KR400 Mareld)" for me a little. I want to move some of that to the comments, if I can -- or even better, omit some of it entirely. Just reading it is driving me into a fit of rage.

What is the relationship between these three designations? What is the difference between this and the existing 9GA205, also ostensibly part of the Mareld?

You say in #1298 that they seem to be the same radar. Why not just add a comment to the existing entry instead of making a separate entry that now has to be independently maintained? I am incredibly confused. Does 9KR409 denote a sub-variant of the 9GA205? Is it a special antenna? System designation? Is it part of the Mareld, or the 9KA410 FCS? Or both? Is this different from the 9KA400 Kastell FCS, which is already indicated in the comments?

**Comment by PygmalionOfCyprus** [comment]
Added 495.
