### ISSUE TITLE
9GA205 [9KR400 Mareld] update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1298]
### DB Selector

DB3K

### Affected DBID(s)

3234

### Summary of Changes

Name change:  add "9KA410 FCS" between the round brackets. This one is or was used by Spain's coastal artillery.

Sensor data same as the 9KR409. These two indeed seem to be the same radar. However the 9KR400 is used more as part of coastal artillery fire control systems. It would probably be better to keep them seperated if any differences between the 2 versions can be found in the future.

### Sources

https://i.imgur.com/u9q453w.png

**Comment by PygmalionOfCyprus** [comment]
Done.
