### ISSUE TITLE
Add Aft Phalanx CIWS to ODIN Armed Burkes #3209

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#13]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3209

### Summary of Changes

Add aft Phalanx CIWS on the #3209 DDG 105. Current Odin ships are Dewey, Stockdale and Spruance. Picture one Stockdale, two Spruance, three Dewey

### Sources

https://i.redd.it/qmmuw6pg2a681.jpg
https://i.redd.it/cj0tl80l07j71.jpg
https://i.redd.it/jbyeyoq0hjl71.jpg

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
