### ISSUE TITLE
Add S-75 Dvina/SA-2 Guideline based Ballistic Missiles used by PRC, Houthis

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#130]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM BN (DF-7/Dongfeng 7/M-7/Project 8610/CSS-8) -PLA, SSM BN (Qaher-1, S-75 Mod) - Terrorists

### Facility Type

SSM

### Country

China, Terrorists

### Service

Army

### In Commission

China 1980s-?, Terrorists 2015-Present

### Crew

Can Copy DBID 2594

### Dispersion Radius (m)

Can Copy DBID 2594

### Sensors

Can Copy DBID 2594

### Mounts

Can Copy DBID 2594

### Magazines

Can Copy DBID 2594

### Aircraft & Docking Facilities

Can Copy DBID 2594

### Comments

DF-7/Dongfeng 7/M-7/Project 8610/CSS-8
Chinese surface-to-surface tactical ballistic missile converted from HQ-1/2/3/4. M-7 missile is the only Chinese ballistic missile that can be launched at a slant angle. The rear section of the HQ SAMs are retained, but the forward half is greatly enlarged into a shuttle shape to house bigger warhead and more fuel, while the control surfaces on the forward section are deleted. Armed with a 500 kg warhead (two and half a time of that of the original SAM version) the maximum range of M-7 is 200 km (more than four times of that of the original SAM version).

Qaher-1
The Qaher-1 is originally a Soviet SA-2 missile that was developed locally by the Houthis to be a surface to surface missile that works on two stages, liquid fuel and solid fuel. It was unveiled in December 2015. The Houthis have fired many Qaher-1's into Saudi Arabia during the course of the Yemeni Civil War.

### Sources

https://en.wikipedia.org/wiki/S-75_Dvina#Major_variants
https://www.globalsecurity.org/wmd/world/china/m-7.htm
http://military.china.com/zh_cn/bbs2/11018521/20040617/11735607.html
https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/china/m-7-8610css-8/
https://www.csis.org/analysis/iranian-missile-threat
https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/iran/css-8-m-7/#:~:text=The%20Iranian%20CSS%2D8%20(M,carries%20a%20payload%20of%20190kg.
https://en.wikipedia.org/wiki/Tondar-69
https://en.wikipedia.org/wiki/Qaher-1
https://web.archive.org/web/20180806181419/http://en.farsnews.com/newstext.aspx?nn=13940922000452

![download](https://user-images.githubusercontent.com/99599482/154353289-4606cc45-0b0a-4da6-b83d-24000a3270bf.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Holding off on the "Terrorists" entry since I'd like to look into actually creating a proper DB OperatorCountry for some major terror groups.

**Comment by tbrandon517** [comment]
> Handled 509. Holding off on the "Terrorists" entry since I'd like to look into actually creating a proper DB OperatorCountry for some major terror groups.

Totally onboard with that. I just went with the existing "terrorists" country for some of the present units.

**Comment by PygmalionOfCyprus** [comment]
In the past we've avoided it due to concerns about image/legitimization/etc. We saw how ArmA got pilloried for "letting you play as the terrorists" by idiots and we weren't looking to open the same can of worms. But I'll ask about it at the weekly meeting and see what the larger team thinks.
