### ISSUE TITLE
Spain - Radar + Sensor Group (9KA410) Coastal Artillery

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1300]
### DB Selector

DB3K

### Hypothetical

No

### Name

Sensor (9KA410) -- Spain (Coastal Artillery)

### Facility Type

Radar

### Country

Spain

### In Commission

1985-

### Sensors

1x 9GA205 [9KR400 Mareld]
1x 9LV200 Mk2 [IR]
1x 9LV200 Mk2 [Laser Rangefinder]
1x 9LV200 Mk2 [TV Camera]

### Mounts

-

### Comments

The radarwas mounted on one vehicle while the optical sensors were on another vehicle. Since I can't find any sources for the optical sensors I'm assuming that it has 9LV200Mk2 optical sensors. Perhaps someone can find a better source.

### Sources

These radars are used by Spain's coastal defence: Regimiento de Artillería de Costa (RACTA) nº 4

https://www.diariodecadiz.es/sanfernando/Fuerzas-Armadas-Regimiento-Artilleria-Costa-san-fernando-Alicante_0_1572744230.html

https://imgur.com/u9q453w

page 12:
https://imgur.com/3tHFewA
https://studylib.es/doc/6339152/el-nuevo-orden-de-batalla-del-ej%C3%A9rcito-de-tierra

unit picture:
https://imgur.com/JqiNtc3

**Comment by PygmalionOfCyprus** [comment]
Added 495.
