### ISSUE TITLE
Brazil - IAI Heron

### ISSUE THREAD

**Issue by AlexandreAvz** [PygmalionOfCyprus/cmo-db-requests#1305]
### DB Selector

DB3K

### DBID to Copy

Heron UAV #3448

### Hypothetical

No

### Name

IAI Heron

### Country

Brazil

### Service

Air Force

### In Commission

2019

### Sensors

Two units have different configurations:

1x 
ELINT Equipment added

1x
Radar removed

### Other Changes

They have two units, each in a different configuration (see sensors)

### Sources

https://www.youtube.com/watch?v=X1QeG5WFG74

https://forcaaerea.com.br/arp-heron-i-e-oficialmente-incorporado-ao-1o-7o-gav/

https://www.aereo.jor.br/2020/09/18/aviacao-de-patrulha-da-fab-incorpora-aeronaves-remotamente-pilotadas-iai-heron-i/

https://www.aereo.jor.br/2019/06/19/iai-assina-acordo-com-a-fab-para-operacao-do-uav-heron/

![heron](https://user-images.githubusercontent.com/107009855/172288136-20a705b2-998b-49b2-809e-054d08794589.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Just to confirm, one of them has only the FLIR -- no radar or anything -- and the other has FLIR, radar, _and_ ESM?

**Comment by AlexandreAvz** [comment]
> Added 495. Just to confirm, one of them has only the FLIR -- no radar or anything -- and the other has FLIR, radar, _and_ ESM?

Based on the pictures and video of the "operation" where they used them together with the hermes 450s (1st link in the sources), one of them has nothing in the way of fairings/external sensors other than the FLIR ball and SATCOM antenna (in the background in the picture I annexed). The other one (pic annexed to this reply) meanwhile has the FLIR ball, the bump/radome under the fuselage that is very likely for a radar and the bump on the nose. I couldn't find exact information on what it houses, but I think a Generic ESM system (as present in israeli #2287 & #4381 and greek #4987) is by far the best bet. I have no idea to what extent those sensors can be interchanged between units.

<img width="821" alt="heron cheio" src="https://user-images.githubusercontent.com/107009855/172753047-f9bdb9f1-06bf-436c-9a73-094cad4a9eed.PNG">
