### ISSUE TITLE
Brazil - SH-16 (S-70B Seahawk)

### ISSUE THREAD

**Issue by AlexandreAvz** [PygmalionOfCyprus/cmo-db-requests#1306]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4353 DB3K

### Hypothetical

No

### Name

SH-16 (S-70B)

### Country

Brazil

### Service

Navy

### In Commission

2012-Present

### Sensors

1x AN/ALR-606(V) replaced by LR-100 MAGE with ELINT and Added RWR capacity
1x AN/APS-143B(V)3 replaced with AN/APS-143C(V)3

### Mounts

Hellfire missiles removed
Sonobuoys Removed
Mk54 Mod 0 Torpedoes added
2x ALE-47 CMDS Added

![ale47](https://user-images.githubusercontent.com/107009855/172297087-48ae5a47-67e1-44fd-b455-4f962a495d0e.jpg)

### Loadout Options

- 2x 120USG Drop Tank
- 2x Mk46 Neartip
- 2x Mk54 Mod 0
- 1x Mk46 NEARTIP + 1x 120 USG Drop Tank
- 1x Mk54 Mod 0 + 1x 120 USG Drop Tank
- 1x RB 12 Penguin Mk2 + 120 USG Drop Tank

### Other Changes

The best article I found states that the LR-100 Mage has RWR capabilities, and I believe it makes sense due to the addition of the ALE-47 CMDS. However, I have not been able to find information on range and etc.

### Sources

https://www.defesaaereanaval.com.br/artigos/sh-16-seahawk-o-guerreiro-da-marinha-do-brasil

https://www.defenseworld.net/news/28443/Brazilian_S_70B_Seahawks_to_be_armed_with_MK_54_Leightweight_Torpedoes#.YKhFfaFv8dU

https://www.defesaaereanaval.com.br/aviacao/esquadrao-hs-1-realiza-curso-para-operacao-de-sonar

https://www.marinha.mil.br/comforaernav/enc_ope_helras

https://www.telephonics.com/product/aps-143cv3-oceaneye

https://www.naval.com.br/blog/2013/10/31/anunciado-contrato-para-mais-dois-s-70b-para-a-marinha-do-brasil-via-fms/

https://www.defesaaereanaval.com.br/aviacao/esquadrao-hs-1-atinge-marca-de-8-000-horas-de-voo-em-aeronaves-seahawk

https://www.marinha.mil.br/ehs-1/historia

https://www.dsca.mil/press-media/major-arms-sales/brazil-mk-54-lightweight-torpedoes

<img width="751" alt="marinha" src="https://user-images.githubusercontent.com/107009855/172297294-014be2b3-841d-461a-8e92-5c8275b345fc.PNG">

**Comment by PygmalionOfCyprus** [comment]
Conveniently I added the MAGE-RWR during 494 for use w/ Brazil's upgraded Wild Lynx helos, so no problem. 😎

**Comment by PygmalionOfCyprus** [comment]
Added 495.
