### ISSUE TITLE
F11-1F Super Tiger missing bombsight

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#1307]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 4119

### Summary of Changes

CWDB Aircraft 4119, the F11F Super Tiger Export, is missing a bombsight despite having two loadouts that contain bombs and being designed as a multirole aircraft. 

Bombsight should probably be "Ballistic Computing" as that's the standard for American aircraft of a similar time period. 

### Sources

Grumman F11-1F Super Tiger, by Corwin "Corky" Meyer, pg. 44

**Comment by PygmalionOfCyprus** [comment]
Fixed 495.
