### ISSUE TITLE
Request for SSM Bn (SS-3 Shyster [8K51 R-5M Pobeda] TEL)

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1308]
### DB Selector

CWDB

### Hypothetical

No

### Name

SSM Bn (SS-3 Shyster [8K51 R-5M Pobeda] TEL)

### Facility Type

SSM

### Country

Soviet Union

### Service

Strategic Rocket Forces

### In Commission

1956-1966

### Crew

1

### Dispersion Radius (m)

120 meters

### Sensors

1x Mk1 Eyeball

### Mounts

3x **SS-3 Shyster TEL**

### Magazines

None

### Aircraft & Docking Facilities

None

### Comments

Each SS-3 Shyster TEL has 1x **SS-3 Shyster [R-5M, 300kT Nuclear]**

Characteristics of the **SS-3 Shyster [R-3M, 300kT Nuclear]**

General Data-
- Type: Ballistic Missile
- Length: 20.75 meters
- Span: 1.66 meters
- Diameter: 1.66 meters
- Weight: 28,600 kilograms
- Burnout weight: N/A
- Cruise altitude: 500 kilometers
- Climb rate: 1,500 meters per second
- Launch altitude: N/A
- Launch speed: N/A
- Target altitude: N/A
- Target speed: N/A
- Range for anti-air, anti-surface and anti-submarine is not applicable
- Range (anti-land): 648 nautical miles
- Air PoH, Sub PoH, and Surface PoH/Reliability is not applicable
- Land PoH/Reliability: 70%
- CEP, Surface (nominal): N/A
- CEP, Land (nominal): 3,700 meters

Signatures-
- Dimensions are very similar to the R-12 missile (R-5M length: 20.75, R-12 length: 22.77, R-5M diameter: 1.66, R-12 diameter, 1.65, all meters) so possibly similar to the R-12 (DBID 617 SS-4 Sandal Mod 2 [R-12U, 2.3mT Nuclear])

Properties-
- Ballistic Missile (ICBM/IRBM/SRBM)
- Weapon - INS Navigation
- Warhead - Single Reentry Vehicle (RV)
- Level Cruise Flight

Warheads-
- SS-3 Shyster RV [300kT Nuclear]

Valid targets-
- Land Structures (Hard)
- Land Structures (Soft)
- Mobile Units (Hard)
- Mobile Units (Soft)
- Runways

Weapon Release Authorization [DEFAULT], Propulsion, and Performance Details are identical to DBID 617 SS-4 Sandal Mod 2 [R-12U, 2.3mT Nuclear], i.e. using **MRBM Boost Phase** for the engine

Fuel should be amended so as to allow for the range given in the General Data section

### Sources

**The Kremlin's Nuclear Sword: The Rise and Fall of Russia's Strategic Nuclear Forces, 1945-2000** by Steven J. Zaloga, page 238

R-5M at Astronautix http://www.astronautix.com/r/r-5m.html

For the missile's climb rate, I used the same value as the R-12 and R-14 missiles from their DB entries in the game. This is because I could not find any info on it- real life missile/rocket "climb rates" are constantly changing as they have complex flight profiles, throttling, etc., not a fixed number, so I am assuming CMO uses a fixed value for it- and a variety of similar missiles (R-12 and R-14) and even the R-7 ICBM have the same value, so I thought it made sense to use that one. Likewise the land PoH probability was copied from the R-12 and R-14, because there really isn't anyway to figure this out and because those two missiles have the same value, I am assuming they used a fixed one.

EDIT- Crew was also set to "1" based on the value used for the R-12 and others ballistic missile facilities

**Comment by PygmalionOfCyprus** [comment]
Added 495.
