### ISSUE TITLE
Request for SSM Silo (SS-8 Sasin [8K75 R-9A])

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1309]
### DB Selector

CWDB

### Hypothetical

No

### Name

SSM Silo (SS-8 Sasin [8K75 R-9A])

### Facility Type

SSM

### Country

Soviet Union

### Service

Strategic Rocket Forces

### In Commission

1964-1978

### Crew

0

### Dispersion Radius (m)

0

### Sensors

None

### Mounts

1x **SS-8 Sasin [R-9A] Silo**

### Magazines

None

### Aircraft & Docking Facilities

None

### Comments

Each SS-8 Sasin [R-9A] Silo has 1x **SS-8 Sasin [R-9A, 2.5mT Nuclear]**

Characteristics for **SS-8 Sasin [R-9A, 2.5mT Nuclear]**

General Data-
- Type: Ballistic Missile
- Length: 26.5 meters
- Span: 2.68 meters
- Diameter: 2.68 meters
- Weight: 74,389 kg
- Burnout weight: N/A
- Cruise altitude: 1,000 kilometers
- Climb rate: 1,500 meters per second
- Launch altitude: N/A
- Launch speed: N/A
- Target altitude: N/A
- Target speed: N/A
- Range for anti-air, anti-surface and anti-submarine is not applicable
- Range (anti-land): 5,562 nautical miles
- Air PoH, Sub PoH, and Surface PoH/Reliability is not applicable
- Land PoH/Reliability: 70%
- CEP, Surface (nominal): N/A
- CEP, Land (nominal): 8,000 meters

Signatures-
- The R-9A was of roughly similar size to the R-14 (R-14 length/width in meters: 24.3, 1.65, R-9A length/width in meters: 26.5, 2.68), so possibly roughly similar to those of DBID 612 SS-5 Skean

Properties-
- Ballistic Missile (ICBM/IRBM/SRBM)
- Weapon - INS Navigation
- Warhead - Single Reentry Vehicle (RV)
- Level Cruise Flight

Warheads-
- SS-8 Sasin RV [2.5mT Nuclear]

Valid targets-
- Land Structures (Hard)
- Land Structures (Soft)
- Mobile Units (Hard)
- Mobile Units (Soft)
- Runways

Weapon Release Authorization [DEFAULT], Propulsion, and Performance Details are identical to DBID 1591 SS-7 Saddler [R-16, 5.0mT Nuclear] because they are both ICBMs and should use the same engine (ICBM RV/MRV/MIRV Re-Entry Phase) for the engine.

Fuel should be amended so as to allow for the range given in the General Data section

### Sources

**The Kremlin's Nuclear Sword: The Rise and Fall of Russia's Strategic Nuclear Forces, 1945-2000** by Steven J. Zaloga, page 232

R-9A at Astronautix http://www.astronautix.com/r/r-9a.html

Climb rate and land PoH were copied from DBID 1591 SS-7 Saddler [R-16, 5.0mT Nuclear] because there is no data available for either (climb rate is complex for rockets with a complex flight profile, throttling etc. while missile reliability is difficult to ascertain for early missiles) and also these two values are shared with other missiles of the same era in the game (R-12, R-14, R-7) and therefore I am assuming a fixed value is used for the same reasons I couldn't get data on either.

**Comment by PygmalionOfCyprus** [comment]
Added 495.
