### ISSUE TITLE
HH-3F Aeronautica Militare Italiana

### ISSUE THREAD

**Issue by Ironduke28** [PygmalionOfCyprus/cmo-db-requests#1311]
### DB Selector

Both

### Baseline

HH-3E USAF

### Hypothetical

No

### Name

HH-3F (AS-61R)

### Country

Italy

### Service

AMI

### In Commission

1977

### Length (m)

22.3

### Wingspan (m)

18,9

### Height (m)

5,51

### Empty Weight (kg)

6200

### Maximum Takeoff Weight (MTOW) (kg)

10000

### Crew

6

### Propulsion

2x GE T58-GE-5 1500 CV

### Service Ceiling (ft)

11482

### Military/Afterburner Speed (kt)

263

### Cruise Speed (kt)

222

### Supercruise

No

### Ferry Range (nm)

1200

### Endurance (min)

750

### Fuel Capacity (kg)

2427

### Sensors

radar APN-215
LORAN-C

### Mounts

2x7,62mm 

### Loadout Options

Marine Patrol
C/SAR
x16 Troops

### Sources

https://it.wikipedia.org/wiki/Sikorsky_S-61

**Comment by PygmalionOfCyprus** [comment]
Added 495. Also added the USCG version.

**Comment by Ironduke28** [comment]
Thanks, but being a novice I would like to know where I can find the helicopter.

**Comment by PygmalionOfCyprus** [comment]
You'll have to wait for DB 495 to release first. (You can see the end-of-cycle date by checking the milestones in Github and looking for the 495 due date -- that's when I pass it to the other devs for pack-up, so it usually comes out a couple weeks after.) Then it's just a matter of installing the update -- either as a beta or, if you're willing to wait, as a stable release -- and making sure your scenario is running the most recent DB.
