### ISSUE TITLE
Add BRO 2/3/4/5/6/7

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1312]
### DB Selector

DB3K

### Hypothetical

No

### Series Name

BRO

### Satellite Type

ELINT

### Country

France

### Service

Unseen Labs

### In Commission

2018

### Is Geostationary

No

### TLE

BRO2:
1 46940U 20085M   22159.43483742  .00003952  00000-0  16632-3 0  9992
2 46940  97.4472 296.3013 0012739 116.6048 315.3325 15.23896059 85968

BRO3:
1 46943U 20085Q   22159.62022083  .00006312  00000-0  25030-3 0  9998
2 46943  97.4306 295.7092 0012595 120.9541 301.7066 15.25664486 86010

BRO4:
1 49066U 21073A   22159.55344834  .00002981  00000-0  18580-3 0  9998
2 49066  97.5245 233.1524 0027397 316.2098 150.6091 15.10016751 44542

BRO5:
1 51061U 22002CF  22159.58344789  .00002992  00000-0  17160-3 0  9996
2 51061  97.4897 226.7328 0011325 112.1787 358.0915 15.13279872 22064

BRO6:
1 52422U 22047AE  22159.58980021  .00001287  00000-0  77718-4 0  9994
2 52422  97.4504 244.6635 0007514 210.3777 256.7843 15.12434781  7008

BRO7:
1 52174U 22033T   22159.50956344  .00002427  00000-0  10707-3 0  9997
2 52174  97.3847 241.1745 0014311  38.8724  19.0725 15.22639929 10323

### Sensors

1x generic ESM (advanced) (same as BRO 1)

### Comments

Sun-synchronous orbits would be better modelled as altitude + inclination + Local Time of descending node instead of TLE, because TLE needs to be constantly updated to keep the local time constant due to Earth oblateness effects.

### Sources

https://www.space-track.org/#catalog

https://space.skyrocket.de/doc_sdat/bro-1.htm

**Comment by PygmalionOfCyprus** [comment]
Added 495.
