### ISSUE TITLE
Add Pleiades Neo

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1313]
### DB Selector

DB3K

### Hypothetical

No

### Series Name

Pleiades Neo

### Satellite Type

IMGSAT

### Country

Civilian

### Service

Airbus Defense and Space

### In Commission

2021

### Is Geostationary

No

### TLE

Pleiades Neo 3:
1 48268U 21034A   22159.47652691 -.00000219  00000-0 -21275-4 0  9992
2 48268  97.8925 234.3333 0001303  88.5084 271.6259 14.81671557 60026

Pleiades Neo 4
1 49070U 21073E   22159.57781843 -.00000318  00000-0 -33798-4 0  9993
2 49070  97.8923 234.4284 0001016  91.6495 268.4845 14.81669747 43758:

### Sensors

1x generic satellite visual camera (same as worldview-2)

### Comments

They have real-time datalinks, which would be an interesting field in the DB (for future downlink delay modelling for instance)

### Sources

https://space.skyrocket.de/doc_sdat/pleiades-neo.htm

https://www.space-track.org/#catalog

**Comment by PygmalionOfCyprus** [comment]
Added 495.
