### ISSUE TITLE
Add GM-60 radar

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1314]
### DB Selector

DB3K

### Hypothetical

No

### Name

GM-60

### Facility Type

Radar

### Country

France

### Service

Army

### In Commission

2025

### Dispersion Radius (m)

0, only 1 vehicle per unit

### Sensors

1x Ground Master 60 radar

### Mounts

None

### Magazines

None

### Aircraft & Docking Facilities

None

### Comments

See sensor request  #1315 for details on the radar

### Sources

Hearing disclosing 5 will be purchased by 2025
https://www.nosdeputes.fr/15/intervention/155792
"Nous avons également prévu des moyens de coordination des interventions dans la troisième dimension avec cinq radars Ground Master 60 (GM60) qui seront livrés d'ici à 2025. Ces radars permettront de garantir la défense sol-air d'accompagnement des troupes au contact et la coordination de la manoeuvre aéroterrestre au sol et près du sol."

"We have also planned means of coordinating interventions in the third dimension with five Ground Master 60 (GM60) radars which will be delivered by 2025. These radars will guarantee the ground-air defense of support for troops in contact and coordination of air-land maneuver on the ground and near the ground."

Thales page on the GM-60:
https://www.thalesgroup.com/en/ground-master-60

**Comment by PygmalionOfCyprus** [comment]
Added 495.
