### ISSUE TITLE
Archange SIGINT planes

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1316]
### DB Selector

DB3K

### Baseline

5220 (Falcon 7X, archange is a 8X)

### Hypothetical

No

### Name

Archange - Falcon 8X SIGINT

### Country

France

### Service

Air Force

### In Commission

2025

### Length (m)

24.5

### Wingspan (m)

26.3

### Height (m)

7.9

### Empty Weight (kg)

17000

### Maximum Takeoff Weight (MTOW) (kg)

33000

### Payload Weight (kg)

0

### Crew

2

### Propulsion

3x Pratt & Whitney Canada PW307-D

### Service Ceiling (ft)

51000

### Military/Afterburner Speed (kt)

500

### Cruise Speed (kt)

450

### Supercruise

No

### Ferry Range (nm)

6450

### Takeoff / Landing Distance (m)

1829 (MTOW) / 656(empty)

### Fuel Capacity (kg)

15830

### Sensors

1x Generic EXM (early 2020s)
1x generic SIGINT (early 2020s)

### Mounts

None

### Loadout Options

- Ferry
- SIGINT

### Comms/Datalinks

UHF radio
Link 16
Link 22
military SATCOM

### Aircraft Codes

Fly-by-Wire, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Range/speed/endurance are for the Falcon 8X without the EW payload, they have to be reduced

### Sources

https://www.dassault-aviation.com/en/group/press/press-kits/the-falcon-8x-archange-to-serve-the-french-air-force/

https://www.dassault-aviation.com/en/civil/falcon-family/falcon-8x/

French Air Force pdf (attached): https://www.defense.gouv.fr/sites/default/files/ministere-armees/Fiche%20LPM%20-%20A%C3%A9ronef%20sp%C3%A9cialis%C3%A9%20de%20recueil%20de%20renseignement%20et%20de%20surveillance%20%C3%A9lectronique%20%28ARCHANGE%29.pdf

[Fiche LPM - Aéronef spécialisé de recueil de renseignement et de surveillance électronique (ARCHANGE).pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8865263/Fiche.LPM.-.Aeronef.specialise.de.recueil.de.renseignement.et.de.surveillance.electronique.ARCHANGE.pdf)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
