### ISSUE TITLE
Add Heavy 4 GBU-48 Loadout to Italian and German Eurofighters

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1317]
### DB Selector

DB3K

### User(s)

2601, 3228,3636,3637,1583,3227,5213,3633,3634,5214

### Weapons Carried

4 GBU-48
2 IRIS-T
1 Litening III Pod
2 1000 liter drop tanks

### Requires Buddy Illumination

No

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

german
https://defense-update.com/20171219_gbu-48.html
Italian
https://www.reddit.com/r/WarplanePorn/comments/v7wi9k/an_italian_eurofighter_typhoon_of_the_4th_stormo/
https://zephyrnet.com/italian-eurofighter-typhoon-flew-in-full-load-configuration-for-the-first-time-last-week/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
