### ISSUE TITLE
SS-N-2d Improved Styx mount update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1318]
### DB Selector

Both

### Affected DBID(s)

912, 1320, 2350 (CW), 2351 (CW)

### Summary of Changes

add option to load SS-N-2d Improved Styx [P-22, IR] to mounts SS-N-2d Styx Single and Styx Twin

### Sources

http://www.paluba.info/smf/index.php?topic=8506.30

> According to Soviet instructions, there were always missiles of various types in the missile salvo, which were set to approach the target at various altitudes. Usually a combination of 1 IR and 1 active radar homing or 1 IR and 2 active radar homing were used. In the latter case, the frequencies of the radar head were always different.

**Comment by PygmalionOfCyprus** [comment]
Fixed 495. The double now carries the P-21 and P-22; the single has an empty record for the P-22.
