### ISSUE TITLE
Add decommission date of 2021 for #2525 U 206 Vinnitsya

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1319]
### DB Selector

DB3K

### Affected DBID(s)

2525

### Summary of Changes

Sunk during the war but retired by last year

### Sources

https://twitter.com/UAWeapons/status/1535260368548909058
https://twitter.com/spriteer_774400/status/1535186848481435650

**Comment by PygmalionOfCyprus** [comment]
Updated 495.
