### ISSUE TITLE
Out of service date of 2022 for #2533 Hetman Sayahdachniy

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1320]
### DB Selector

DB3K

### Affected DBID(s)

2533

### Summary of Changes

Scuttled in Feb-March 2022

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/march/11526-list-of-ukrainian-navy-ships-would-have-been-destroyed-or-captured-by-russian-armed-forces.html
https://en.wikipedia.org/wiki/Ukrainian_frigate_Hetman_Sahaidachny
https://twitter.com/josephhdempsey/status/1499458503185993730

**Comment by PygmalionOfCyprus** [comment]
I think either I or someone else on the DB team ninja'd this because it's already done. Anyway, updated for 495. Or potentially back in 494.
