### ISSUE TITLE
Yugoslavia - G-4M Super Galeb (modernised)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1322]
### DB Selector

DB3K

### Baseline

397

### Hypothetical

Yes

### Name

G-4M Super Galeb - 1992

### Country

Yugoslavia

### Service

Air Force

### Length (m)

11.9

### Wingspan (m)

9.9

### Height (m)

4.3

### Empty Weight (kg)

3260

### Maximum Takeoff Weight (MTOW) (kg)

6700 

### Payload Weight (kg)

1800

### Crew

2

### Propulsion

Viper Mk.680-43 #1

### Rate of Climb (ft/min)

6100

### Service Ceiling (ft)

unchanged

### Military/Afterburner Speed (kt)

unchanged

### Cruise Speed (kt)

unchanged

### Supercruise

No

### Ferry Range (nm)

1566

### Endurance (min)

180 (at 8000m, internal fuel)

### Takeoff / Landing Distance (m)

600 / 800

### Fuel Capacity (kg)

1370

### Sensors

1x Iskra SO-1
1x Mk1 Eyeball

### Mounts

-POJ-264 [96 Cartridges]: 4x Generic Chaff Salvo [4x Cartridges], 20x Generic Flare Salvo [4x Cartridges, Single Spectral]

### Loadout Options

-2x AGM-65B Maverick
-2x AA-8 Aphid [R-60M] (optional)
-2x 500 liter Drop Tank
-1x 300 liter Conformal Tank **(would have to be added to the DB)**
--------------------------
-4x BL.755 No.1 CB
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-2x BL.755 No.1 CB
-2x AA-8 Aphid [R-60M] (optional)
-2x 500 liter Drop Tank
-1x 300 liter Conformal Tank
--------------------------
-4x Mk82 500lb
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-2x Mk82 500lb
-2x AA-8 Aphid [R-60M] (optional)
-2x 500 liter Drop Tank
-1x 300 liter Conformal Tank
--------------------------
-4x Mk82 500lb Snake Eye
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-2x Mk82 500lb Snake Eye
-2x AA-8 Aphid [R-60M] (optional)
-2x 500 liter Drop Tank
-1x 300 liter Conformal Tank
--------------------------
-4x RAB-250 M91 Prefragmented Airburst
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-2x RAB-250 M91 Prefragmented Airburst
-2x AA-8 Aphid [R-60M] (optional)
-2x 500 liter Drop Tank
-1x 300 liter Conformal Tank
--------------------------
-4x FAB-275 M91 FAE [Retarded] Proximity Fuze
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-2x FAB-275 M91 FAE [Retarded] Proximity Fuze
-2x AA-8 Aphid [R-60M] (optional)
-2x 500 liter Drop Tank
-1x 300 liter Conformal Tank
--------------------------
-64x BR-20-57 57mm Rocket [HEAT+FRAG]
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-16x BR-128 M74 128mm Rocket [HE]
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-16x BR-128 M80 128mm Rocket [HEAT]
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------
-4x PLAB-350 M73 Incendiary Bomb
-2x AA-8 Aphid [R-60M] (optional)
-1x 300 liter Conformal Tank
--------------------------

### Comms/Datalinks

UHF Radio [Secure]
VHF Radio [Secure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Bombsight - Ballistic Computing

### Comments

- radar cross section should be reduced by a very tiny amount because composite materials were used.
- agility should be increased considerably for all G-4s to 4 probably.
They are very agile trainer aircraft which were also used by the national aerobatics team. The G-4 competed for a new trainer aircraft of the US Airforce in the late 80s when it was praised for it's good maneuverability.

### Sources

https://www.yugoimport.com/en/proizvodi/super-galeb-g-4m
> Achieves high operational performance and maneuverability (mst. turn rate; 27°/s, sustained turn rate: 17°/s)

http://www.vti.mod.gov.rs/index.php?view=actuality&type=reference&category=3&id=125
few bits and pieces that were missing (variants G-4M and specs G-4M):
https://en.wikipedia.org/wiki/Soko_G-4_Super_Galeb

https://www.mycity-military.com/Avioni/G-4-Supergaleb_235.html

google translate:
> 9. What's new with the G-4M?
New on the G-4M
Expanded armament and increased payload for the aircraft through:
-integration of IR missiles V-V, R-60,
-integration of TV self-guided missiles MAVERIK,
-increasing the carrying capacity of external weapons lines from 250 kg to 350 kg,
-increasing the carrying capacity of internal weapons lines from 350kg to 500kg,
-introduction of new wingtip missile rails.
-installation of electronic sighting system (ENS), gyro platform, IFF, flight data registrar
-introduction of cryptographic protection in radio communications, which achieves the following effects: ....
-introduction of a sub-body suspension tank, which allows increasing the tactical radius and range of G-4 aircraft.
-application of composite materials to part of the secondary elements structures, which would gain experience in prototyping production and application of composites.
-we considered the possibility of installing the VIPER 680 engine, which compared to the existing one has about 10% higher ground pressure and at slightly higher altitudes even slightly less.

production planned for 1992:

https://imgur.com/w2xLuDf

The war prolonged the development into the late 90s although the G-4 which was converted into the M variant prototype was sent to the aircraft plant in 1990:

https://imgur.com/gxVLJSP

https://imgur.com/xsRVRBN

https://imgur.com/dKCZREJ

Circular Maverick guidance screen:
https://imgur.com/LGT5MvK

New HUD which was developed locally:
https://imgur.com/hvUrpI1

A conformal tank similar to this one would have been used:
https://imgur.com/G9NfsRs

turn rate G-4 with Viper Mk 680:
https://upload.wikimedia.org/wikipedia/sr/0/09/Uporedjenje_G-4%2C_s_motorom_VP680%2C_s_drugim_avionima_u_manevru.jpg

G-4 at JPATS:
https://img.photobucket.com/albums/v666/pics678/g41.jpg
https://img.photobucket.com/albums/v666/pics678/g42.jpg
https://img.photobucket.com/albums/v666/pics678/g43.jpg

**Comment by nuk92** [comment]
Unit db picture:
![](https://i.imgur.com/EBx7ghd.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Only for Yugoslavia? Also, does it no longer take the loadouts from the Super Galeb (e.g. w/ the gun pod, etc.) or should those be available as well?

**Comment by nuk92** [comment]
Honestly the Super Galeb loadouts should be available as well, I just didn't want to pile up too many loadouts. The gun pod is carried instead of the conformal fuel tank on the centerline hardpoint. The G-4M can also be added to Serbia, but it remained a prototype until this day.

**Comment by PygmalionOfCyprus** [comment]
Don't worry about "pil[ing] up too many loadouts"; I'd rather spend an extra five minutes and get it right the first time. Loadouts that already exist for other aircraft -- especially versions of the same aircraft -- are very easy to add. I'll port the standard G-4 loadouts over to the G-4M.

Another question: the PLAB-350 M73 loadout, is there a reason that wasn't listed for the standard G-4? Same with the Mk82s.

**Comment by nuk92** [comment]
The PLAB-350 M73 is a too heavy loadout for the standard G-4. The Mk82s is actually listed as a loadout for the standard G-4 but it should also have a 4x FAB-250 M79/2x Fab-250 +droptanks and 4x FAB-100 M80/2x FAB-100 + droptanks loadout (only Myanmar has those Chinese bomb racks to put 2x 100kg bomb on one pylon). Sorry about that, it's hard to keep track of so many requests. If you mean Mk82 for Myanmar, only Yugoslavia imported those specifically for the G-4.

**Comment by PygmalionOfCyprus** [comment]
Added 495. For real this time!
