### ISSUE TITLE
Yugoslavia, Serbia - G-4T Super Galeb

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1323]
### DB Selector

DB3K

### Baseline

397

### Hypothetical

No

### Name

G-4T Super Galeb - 1984 (Target Tow)

### Country

Yugoslavia, Serbia

### Service

Air Force

### In Commission

1984-1992, 1992- (Serbia)

### Length (m)

11.9

### Wingspan (m)

9.9

### Height (m)

4.3

### Empty Weight (kg)

3260

### Maximum Takeoff Weight (MTOW) (kg)

6300

### Payload Weight (kg)

1420

### Crew

2

### Propulsion

Viper Mk.632-46 #1

### Rate of Climb (ft/min)

5700

### Service Ceiling (ft)

unchanged

### Military/Afterburner Speed (kt)

unchanged

### Cruise Speed (kt)

unchanged

### Supercruise

No

### Ferry Range (nm)

1080

### Endurance (min)

180 (at 8000m, internal fuel)

### Takeoff / Landing Distance (m)

600 / 800

### Fuel Capacity (kg)

1370

### Sensors

1x Iskra SO-1
1x Mk1 Eyeball

### Mounts

-

### Loadout Options

-1x Aerial Towed Target
-2x 375 liter Drop Tank
----------------------------------
-2x PRM-200
-2x 375 liter Drop Tank
-----------------------------------
-4x BL.755 No.1 CB
-1x Gsh-23L gun pod (optional)
--------------------------
-2x BL.755 No.1 CB
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x Mk82 500lb
-1x Gsh-23L gun pod (optional)
--------------------------
-2x Mk82 500lb
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x Mk82 500lb Snake Eye
-1x Gsh-23L gun pod (optional)
--------------------------
-2x Mk82 500lb Snake Eye
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x RAB-250 M91 Prefragmented Airburst
-1x Gsh-23L gun pod (optional)
--------------------------
-2x RAB-250 M91 Prefragmented Airburst
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-4x FAB-275 M91 FAE [Retarded] Proximity Fuze
-1x Gsh-23L gun pod (optional)
--------------------------
-2x FAB-275 M91 FAE [Retarded] Proximity Fuze
-2x 375 liter Drop Tank
-1x Gsh-23L gun pod (optional)
--------------------------
-64x BR-20-57 57mm Rocket [HEAT+FRAG]
-1x Gsh-23L gun pod (optional)
--------------------------
-16x BR-128 M74 128mm Rocket [HE]
-1x Gsh-23L gun pod (optional)
--------------------------
-16x BR-128 M80 128mm Rocket [HEAT]
-1x Gsh-23L gun pod (optional)
--------------------------
-4x PLAB-200 M71 Incendiary Bomb
-1x GSh-23L gun pod (optional)
--------------------------

### Comms/Datalinks

UHF/VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Bombsight - Basic

### Comments

The G-4T is a target towing version which can also be armed. It is used to launch the unique PRM-200 programmable target missile which is equipped with radar reflectors and flares to increase the rcs and ir signature. It is used to simulate combat planes for air defense unit or fighter squadron training. The PRM-200 has a programable flightpath.

- the agility should be increased to 4 as with other G-4s

### Sources

data:
http://www.vti.mod.gov.rs/index.php?view=actuality&type=reference&category=3&id=125

G-4T db unit picture:
https://www.mycity-military.com/imgs/65178_97245018_Clip.jpg

PRM-200, programmable target missile (Target Drone):
https://www.yugoimport.com/en/proizvodi/programmable-drone-prm-200

https://www.mycity-military.com/imgs2/52022_44881040_25gxw61.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
