### ISSUE TITLE
PRM-200 target drone

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1324]
### DB Selector

DB3K

### Baseline

1175 - Samson TALD

### Hypothetical

No

### Name

PRM-200 [Target Missile]

### Length (m)

2.24

### Width/Span (m)

0.8

### Diameter (m)

0.2

### Weight (kg)

90

### Range (nm)

1-26

### Launch Altitude / Depth (ft)

984ft ASL - 22966ft ASL

### Warhead

-

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

-

### Sensors

-

### Weapon Codes

Bearing-Only Launch (BOL), Weapon - INS Navigation, Level Cruise Flight

### Comments

Type: Decoy (Vehicle)

Propulsion
Engine: Rocket Boost/Sustainer
Type: Rocket [Boost & Coast]
Max Speed: 467 kts

range from launch alt of 22966ft: 26nm
range from launch alt of 984ft: 12nm

The radar signature is enhanced by passive radar reflectors (Luneberg lens)

Front Signature
A-D Band: 6.5 sqm
E-M Band: 2.4 sqm

Side Signature (estimated)
A-D Band: 13 sqm
E-M Band: 4.8 sqm

This missile has a barometric altimeter and two gyroscopes, the flightpath can be programmed (plot flightpath).

### Sources

picture for db entry:
https://i.imgur.com/Nx6ViZt.jpg

https://www.mycity.rs/uploads/18848_43880641_PRM-200%20sa%20p07%201.jpg
https://www.mycity.rs/uploads/18848_43880641_PRM-200%20sa%20p07%202.jpg
https://fotkica.com/phpbb/uploadsN/18848_PRM.jpg

specs:
https://www.mycity-military.com/imgs4/120566_61250772_PRM_200%20-%20PRM_200.png

this source is very wrong about the range though:
https://www.mycity-military.com/imgs2/123381_99955589_prm200.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
