### ISSUE TITLE
HY-2, HY-4 and Ra`ad AShM correction

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1325]
### DB Selector

DB3K

### Affected DBID(s)

1100 , 1087 & 2392

### Summary of Changes

- Add Terminal Maneuver - Pop - up to HY-2(1100), HY-4(1087) and Ra`ad AShM (2392) 
- Add valid targets: Land Structures Hard & Soft to HY-2(1100), HY-4(1087) and Ra`ad AShM (2392) 

The first 2 missiles were reportedly to have similar terminal maneuver capability as the improved Styx missiles, which is diving towards its target during terminal phase. The missiles also have been reported to have struck Iraqi land target too. Third missile is the development of these 2 missiles so it supposed to have this capability too at least.

### Sources

https://www.washingtonpost.com/archive/politics/1988/01/14/more-silkworm-missiles-reported-in-iran/e0076e24-8b1d-4b8e-99c1-0dd00a8636bd/
http://ae.sharif.edu/~rocket_design/ssm/hy-4.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed 495. Also applied to the HY-2 in CWDB.
