### ISSUE TITLE
Japan 07 VL-ASROC (Weapon)

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1326]
### DB Selector

DB3K

### Affected DBID(s)

3705

### Summary of Changes

Type 07 VL-ASROC has a Type 97 (Weapon ID 314)  torpedo as a payload.

This is used for  
DD 115 Akizuki (Ship ID 2293)
DD  119 Asahi (Ship ID 3128)
DDG 179 Maya (Ship ID 3211)
FFM 1 Mogami (Ship ID 3293)

so, we can replace RUM-139 with this weapon. 
For Akizuki class, 07 VLA is used from 2nd ship, DD 116 Teruzuki, so we might can make separate unit. (= Akizuki use RUM-139)

And, please add [Type 97] in comment section, because we likely have Type 07 VLA with newer Type 12 torpedo.  

### Sources

Here is a wiki, but what I commented is in Japanese version of this wiki page.

https://en.wikipedia.org/wiki/Type_07_Vertical_Launch_Anti-submarine_rocket

**Comment by PygmalionOfCyprus** [comment]
Fixed 495, incl. creation of a new entry for Teruzuki.
