### ISSUE TITLE
Yakhont/Oniks Missile Radar Cross Section 

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1328]
### DB Selector

DB3K

### Affected DBID(s)

#2685 and #1173 and various PJ-10 Brahmos variants

### Summary of Changes

I saw this RCS measurements and maybe this is usefull for the DB?

For more info on other RCS measurements look at [https://twitter.com/search?lang=nl&q=rcs%20(from%3AFlankerchan)&src=typed_query](url)

### Sources

https://twitter.com/Flankerchan/status/1404312740580052992/photo/2

**Comment by PygmalionOfCyprus** [comment]
To the extent that I have control over the RCS, our numbers for the Yakhont are actually pretty close!

**Comment by Huib18** [comment]
Nice -;)
