### ISSUE TITLE
HY-2 and Ra`ad coastal battery correction

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1329]
### DB Selector

DB3K

### Affected DBID(s)

905 & 1811

### Summary of Changes

- Change from 3 launchers per battery to 4 launchers instead. 
- add magazine for the HY-2 and Ra`ad coastal battery with each magazine is to have 8 extra missiles.

The HY-2 system were first reportedly to be seen at the Iranian port on July 1987 with 4 launchers, a radar and 20 missile crates which suggested this is the battery`s composition. HY-4/Ra`ad`s battery composition is also probably the same.
![image](https://user-images.githubusercontent.com/99646926/173190309-4c849996-69e3-419b-9878-10dab26ab3f8.png)

![image](https://user-images.githubusercontent.com/99646926/173190327-66c46225-b818-48d3-b688-26a5788554bd.png)

### Sources

https://www.globalsecurity.org/military/world/iran/saeqeh-cm.htm
https://web.archive.org/web/20130425014108/http://www.sinodefence.com/navy/navalmissile/hy3.asp

**Comment by PygmalionOfCyprus** [comment]
Fixed 495.
