### ISSUE TITLE
Rezonans OTH radar 

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1330]
### DB Selector

DB3K

### DBID to Copy

#2611 Ghadir OTH-B (Iran-2013)

### Hypothetical

No

### Name

Rezonans NE OTH radar

### Country

Russia, Algeria and Egypt

### Service

Air Defense

### Sensors

See tech description @ https://twitter.com/charly0153/status/1510314541200064514/photo/2

### Sources

**Egypt::**
https://twitter.com/muh_Alqahtani/status/1307610160685342721 
https://twitter.com/wpnexp/status/1185067232545726464
https://twitter.com/carlosruedae/status/1307166039239585793
**Russia:**
https://twitter.com/charly0153/status/1508071405245673473 
**Iran::**
https://twitter.com/pjonesbilly/status/1300781682048540678
**Algeria:**
https://twitter.com/YahiRauf/status/1441417781900099584

**Overall:**
https://charly015.blogspot.com/2021/12/la-foto-del-rezonans-n.html

**Tech specs**
https://twitter.com/charly0153/status/1510314541200064514/photo/2 (also for the Podsolnukh-E OTH)

**Comment by HVAA** [comment]
Theres one located at 38WMA6552727172.
Google Earth shows it under construction in 2016 and completed over the following years.  Last uploaded pass on that location was in 2019 and it looks operational.
Pity github doesnt allow KMZ uploads or I would have sent the pushpin.  Its on the 'Emu's Head' on the mouth of the White Sea. So this confirms the Russians have it too.

**Comment by Huib18** [comment]
[http://roe.ru/pdfs/pdf_2012.pdf](url)

**Comment by Huib18** [comment]
Tnx

Op za 11 jun. 2022 om 16:55 schreef HVAA ***@***.***>:

**Comment by PygmalionOfCyprus** [comment]
Already in DB as Facilities 3319-22. Pretty sure this was pre-494 so it should be public.

**Comment by Huib18** [comment]
Srry I searched wrong with an -s- instead of a -z-
Is it possible to add OTH in the title, that would help?


Op zo 12 jun. 2022 om 05:12 schreef Ethan Hermanson <
***@***.***>:

**Comment by PygmalionOfCyprus** [comment]
>Is it possible to add OTH in the title, that would help?

Done. 👍
