### ISSUE TITLE
UVision Hero-400EC loitering munition

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1331]
### DB Selector

DB3K

### Baseline

none

### Hypothetical

No

### Name

UVision Hero-400EC loitering munition

### Length (m)

2.1 meter

### Width/Span (m)

2.4 meter

### Diameter (m)

unkown or use the wingspan?

### Weight (kg)

MTOW 40 Kg

### Range (nm)

120 km+ / 120 minutes

### Target Altitude / Depth (ft)

Operational altitude is 18,000ft

### Launch Altitude / Depth (ft)

A line-of-sight two-way data link with a range of 40km (low) -150km (high)

### Warhead

10 kg (tandem, high explosive

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Radar, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

< 1 meter

### Sensors

stabilized electro-optic/infrared (EO/IR) payload, a line-of-sight two-way
data link with a range of 40km-150km, a man-in-the-loop capability

### Weapon Codes

Lock-On After Launch (LOAL), Loiter Capability, Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Weapon Altitude Control Possible, Uses GPS

### Comments

The Hero-400EC is an innovative all-electric precision Electro-Optical/Infra-Red (EO/IR) guided, man-in-the-loop Loitering Munition system that can locate, track and strike static and moving targets with high accuracy and surprise. With these precision strike capabilities, a large multi-purpose warhead and extended endurance, the Hero-400EC has been proven effective against a wide variety of targets, including fortified positions and main battle tanks. 

Controlled by a single operator, the Hero-400EC can be either rail-launched or launched from a modular multitube canister which can be integrated on the user’s platform of choice. 

Equipped with a electric motor that delivers high-speed transit and low-speed loitering with much lower acoustic and thermal signatures.

Possibly in use from 2018 on.

### Sources

https://uvisionuav.com/portfolio-view/hero-400ec/
https://twitter.com/AbraxasSpa/status/1531868888455159808?t=JadbqT4v8US3XXQVfhPVBQ&s=19
https://uvisionuav.com/wp-content/uploads/2018/01/Hero-400EC-Demonstration.pdf

**Comment by Huib18** [comment]
loitering/transit speeds of 50-150kts

the weapon has a unique strike abort capability that enables automatic dive recovery and re-entry into the loitering mode, mission re-assignment or return to the recovery area using a parachute.
https://defense-update.com/20180109_hero400es.html

**Comment by PygmalionOfCyprus** [comment]
We actually already added this one independently. 😄

**Comment by Huib18** [comment]
Whooohaa
