### ISSUE TITLE
UVision Hero-120 OPF-M (Organic Precision Fires-Mounted)

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1332]
### DB Selector

DB3K

### Baseline

none

### Hypothetical

No

### Name

UVision Hero-120 OPF-M

### Length (m)

1.5 m

### Width/Span (m)

1.41

### Diameter (m)

unk

### Weight (kg)

Empty 12 kg, MTOW 15 kg

### Range (nm)

40-60+ km / 65 min (40 with parachute, and 60-65 without)

### Warhead

3.5 - 4.5 (the latter for the USMC)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

<1 meter

### Sensors

stabilized electro-optic day/night cameras

### Weapon Codes

Lock-On After Launch (LOAL), Loiter Capability, Loiter Capability (Parachute), Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Re-Attack Capability, Weapon Altitude Control Possible, Uses GPS

### Comments

Users Israel and USMC.

The loitering munition is to be integrated into the USMC’s amphibious Light Armored Vehicle-Mortar, Joint Light Tactical Vehicle and Long Range Unmanned Surface Vessel. The weapon will be shot out of a multi-canister launcher. 

The HERO-120 can be fitted with a recovery parachute, however this will impact the terminal effect, a smaller warhead being installed to give room for the chute. In its standard version the HERO-120 has an antitank capability; adopted by the US Marine Corps for its Organic Precision Fire Mounted (OPF-M) programme, the US decided to install the same warhead in use on their Javelin antitank missiles

### Sources

https://uvisionuav.com/portfolio-view/hero-120/
https://www.armyrecognition.com/defense_news_may_2022_global_security_army_industry/uvision_usa_highlights_its_hero-120_opf-m_aerial_loitering_munitions_at_modern_day_marine_2022.html
https://www.youtube.com/watch?v=4ISVv9FePrc
https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=1654
https://www.edrmagazine.eu/rheinmetall-and-uvision-team-to-propose-hero-loitering-munitions-on-the-european-market
https://www.janes.com/defence-news/news-detail/hero-120-loitering-munition-selected-for-usmc-opf-m-system-requirement
https://weaponews.com/weapons/65356949-loitering-munitions-search-seizure-destruction.html

Maybe this one is useful if you have holes in other loitering munitions:
https://www.sciencedirect.com/science/article/pii/S221491472100146X

**Comment by PygmalionOfCyprus** [comment]
Hero-120 is already in the DB; we've added it to the USMC's JLTV-LV for 495 and a couple other platforms.

**Comment by Huib18** [comment]
Good!
