### ISSUE TITLE
Add Plt IRIS-T SLM Egypt and Germany [FRG/Reunified] Air Force 2022? + Add new SLM missile with enhanced range etc

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1333]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Plt (IRIS-T SLM) (Egypt Air Force) 2022 and SAM Plt (IRIS-T SLM) (Germany [FRG/Reunified] Air Force) 2022 (Hypothetical?) 

### Facility Type

SAM

### Country

Egypt and possibly Germany [FRG/Reunified]?? 

### Service

Air Force

### In Commission

2022 to present. Commissioning 2017.

### Crew

8

### Dispersion Radius (m)

80m

### Sensors

Mk1 Eyeball
Acquisition Radar - 2018 Thales Ground Master 200 was demonstrated on 8x8 vehicle. 
Acquisition Radar - 2014 CEA Australia CEAFAR on 8x8 vehicle. Used during range tests in 2014.  

*Also demonstrated with small Giraffe X mounted on BV-410.
and with IRIS-T SLM S band AESA (GBMMR)

### Mounts

2 x Armoured MAN-SX 8x8 Truck 8 cell VLS - HF datalink. *
1 x Armoured MAN-SX 8x8 C3I command post - V/HF/HF datalink.
1 x Armoured MAN 8x8 Radar FCR acquisition system. *Thales Ground Master 200

### Magazines

24 x IRIS-T SLM missiles - trans loader (Estimate)

### Aircraft & Docking Facilities

Default quadcopter UAV capability but otherwise nil. 

### Comments

IRIS-T SLM has a significantly better range and performance envelope than the DB3k existing SLS entry. 
Exports of SLS and SLM to a number of countries not least recent "promised" deliveries to Ukraine. 

**key QUOTES FROM LINKS BELOW**
The missile has a pre-fragmented warhead and offers 360° defence against air attacks in homeland defence or international missions. The missile is propelled by an advanced rocket motor fitted with an integrated thrust vector control system. It is equipped with an aerodynamic hood to achieve **extended range of about 40km**. It can engage targets flying at an **altitude of around 20km.**

The new surface-to-air guided missile IRIS-T SL (Surface Launched) is an upgraded version of the IRIS-T air-to-air guided missile. Contracted by the Bundeswehr, it was developed for Tactical Air Defence and was qualified for **in-service use in 2017.**
Compared with the basic version, IRIS-T SL features an **enhanced rocket motor for extended range**. The newly introduced data link, in connection with a GPS-based inertial navigation system, allows controlling the missile from a combat center. During terminal approach the missile guides itself directly to the target.

The IRIS-T SL missile is launched from a multi-function container (for storage, transport and firing) providing 360° protection against aircraft, helicopters, drones and other missiles. It can easily be integrated into various existing and future air defence systems through connection to fire control systems via standardized and software-based interfaces.

### Sources

https://www.airforce-technology.com/projects/iris-t-sl-surface-to-air-guided-missile/
https://www.19fortyfive.com/2022/06/a-game-changer-germany-to-send-iris-t-sl-air-defense-system-to-ukraine/
https://esut.de/2019/01/fachbeitraege/ruestung/10119/us-exportkontrolle-itar/attachment/diehl-defence-iris-t-sl/
https://www.diehl.com/defence/en/press-and-media/downloadcenter/?p=3
https://www.diehl.com/defence/en/products/guided-missiles/#iris-t-sl
https://www.diehl.com/defence/en/products/air-defence-systems/
http://upload.wikimedia.org/wikipedia/commons/thumb/2/24/BGT_IRIS-T_SL-2-2.png/859px-BGT_IRIS-T_SL-2-2.png Shows significantly altered SLM version to reduce drag. 
https://www.cea.com.au/!Global/Directory.php?Location=ProductsServices:PhasedArrayTechnologies:CEAFAR
https://www.thalesgroup.com/en/markets/defence-and-security/air-forces/airspace-protection/mid-range-radars/ground-master-200

**Comment by Huib18** [comment]
Also add IRIS-T for Egypt:
https://twitter.com/mahmouedgamal44/status/1471492790513127424
https://twitter.com/mahmouedgamal44/status/1471442240627118080
https://twitter.com/mahmouedgamal44/status/1471435118111866892
https://twitter.com/PosiTroll/status/1531929802176864256
https://twitter.com/magedmahmoudEGY/status/1474784338529198089
https://www.youtube.com/watch?v=bH-hCpU4SLs

**Comment by KLABDB3K** [comment]
The more you dig Ukraine seems to ne getting Egyptian systems amd Egypt seems to more likely to get it before Germany (if at all). Egypt appears to be using the GM200 radar?

**Comment by PygmalionOfCyprus** [comment]
I think it's the TRM-L 4D. They (the Egyptians) ordered them along with the launchers/missiles. PR video shows three launchers + radar + C2 vic as far as I can see?

Anyway, added 495 for Egypt. Holding off on Germany, and on Ukraine, until we get further confirmation.
