### ISSUE TITLE
South Korea P-3CK

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1335]
### DB Selector

DB3K

### Baseline

P-3B/C 

### Hypothetical

No

### Name

P-3CK

### Country

South Korea

### Service

Navy

### In Commission

2010

### Length (m)

35.6

### Wingspan (m)

30.4

### Height (m)

10.3

### Empty Weight (kg)

27890

### Maximum Takeoff Weight (MTOW) (kg)

61235

### Payload Weight (kg)

9070

### Crew

10

### Propulsion

T-56-A-14

### Service Ceiling (ft)

28000

### Military/Afterburner Speed (kt)

410 @ 0.68

### Cruise Speed (kt)

330 @ 2800

### Supercruise

No

### Ferry Range (nm)

?

### Sensors

1x EL/M-2022A(V)3 (ID 448)
1x AN/AAS-36 IRDS
1x AN/ALR-95 (upgraded ALR-66?)
1x AN/ALQ-157
1x AN/ASQ-81(V)1
1x Mk1 Eyeball

### Mounts

AGM-84L Harpoon2
AN/SSQ-53D(3) DIFAR
AN/SSQ-62E DICASS
K-745 Blue Shark

### Loadout Options

- ASW+ASuW loadout
4x AGM-84L (ID 816)
8x K-745 (ID 315)
100x AN/SSQ-53D
40x AN/SSQ-62E DICASS

-ASW loadout
8x K-745
100x AN/SSQ-53D(3)
40x AN/SSQ-62E DICASS

-Maritime Surveillance (15288)

### Comms/Datalinks

P-3C Orion Update 3+ equivalent

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

this P-3CK is heavily modified from old USN P-3B with new sensor and weapon system.  So I believe where I did not write could filled by other P-3Cs.

it is ignored but actual max number of sonobuoys in P-3s are 84, so 54 DIFAR + 30 DICASS might be better... 

### Sources

Korean Wiki
https://ko.wikipedia.org/wiki/P-3_%EC%98%A4%EB%9D%BC%EC%9D%B4%EC%98%A8

DIFAR Sonobuoys
http://metanetworks.co.kr/03_pro/PDF/ANSSQ-53D(3)_META_SONOBUOY_CATALOG(ENG).pdf

**Comment by PygmalionOfCyprus** [comment]
Added 495. I've made a private ticket for the incorrect sonobuoy number on the P-3s and will handle that separately.

You can't see this, but just as a reference for myself: PygmalionOfCyprus/cmo-db-dev#532
