### ISSUE TITLE
Please add Yarmook-class corvette of Pakistani Navy

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1336]
### DB Selector

DB3K

### Hypothetical

No

### Name

F-271 Yarmook

### Class

Yarmook-class

### Country

Pakistan

### Service

Navy

### In Commission

2020-present

### Length (m)

91.3

### Beam (m)

14.4

### Draft (m)

4

### Standard Displacement (t)

2,300

### Complement

138 

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

4 × Caterpillar 3516 diesel engines

### Flank Speed (kt)

22

### Range (nm) at Speed (kt)

6,000nm at 12 knots

### Sensors

1x MR-36A I-band surface search radar
2x generic navigation radar
1x generic EO

### Mounts

1x 30mm Aselsan Smash
1x Type 730 CIWS
2x 12.7mm
2x chaff/flare launcher

### Aircraft & Docking Facilities

2x davits for 7m RHIB
1x pad/hangar for medium helicopter and 1x small  hangar for UAV
![image](https://user-images.githubusercontent.com/99646926/173398124-b78c8d39-bfb2-4290-af92-c660d593b004.png)

### Comms/Datalinks

-VHF/UHF radio
-SATCOM

### Comments

Slightly longer Damen 1900 OPV model

![image](https://user-images.githubusercontent.com/99646926/173398338-44023e12-4bd0-4c28-8bfb-4445f3dab83c.png)
![image](https://user-images.githubusercontent.com/99646926/173398406-ac76e198-0b37-423b-b66d-167e90e6d31a.png)
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/99646926/173398238-43909834-4218-4d09-87ee-d305a8613f93.png)

### Sources

https://www.facebook.com/609232009210847/posts/pakistan-navy-first-ever-corvette-yarmook-classin-2017-pakistans-ministry-of-def/2022145751252792/
https://en.wikipedia.org/wiki/Yarmook-class_corvette
https://www.janes.com/defence-news/news-detail/pakistan-navy-commissions-second-and-final-yarmook-class-corvette
https://www.facebook.com/609232009210847/posts/pakistan-navy-first-ever-corvette-yarmook-classin-2017-pakistans-ministry-of-def/2022145751252792/
https://www.pakdefense.com/blog/pakistan-navy/pakistan-navy-inducts-cutting-edge-damen-2300-tons-offshore-patrol-vessel-pns-yarmook-in-its-arsenal/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
