### ISSUE TITLE
G-4 Super Galeb basic information update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1337]
### DB Selector

DB3K

### Baseline

397, 2894, 4666 G-4 Super Galeb [Yugoslavia & Serbia & Myanmar]

### Hypothetical

No

### Name

-

### Length (m)

11.9

### Wingspan (m)

9.9

### Height (m)

4.3

### Empty Weight (kg)

3260

### Maximum Takeoff Weight (MTOW) (kg)

6300

### Payload Weight (kg)

1420

### Crew

2

### Propulsion

Viper Mk.632-46 #1

### Rate of Climb (ft/min)

5700

### Service Ceiling (ft)

unchanged

### Military/Afterburner Speed (kt)

unchanged

### Cruise Speed (kt)

unchanged

### Supercruise

No

### Ferry Range (nm)

1080

### Endurance (min)

180 (at 8000m, internal fuel)

### Takeoff / Landing Distance (m)

600 / 800

### Fuel Capacity (kg)

1370

### Sensors

1x Iskra SO-1
1x Mk1 Eyeball

### Mounts

-

### Loadout Options

seperate requests

### Comms/Datalinks

UHF/VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Bombsight - Basic

### Comments

the agility should be increased to 4 as with other G-4s

### Sources

data:
http://www.vti.mod.gov.rs/index.php?view=actuality&type=reference&category=3&id=125

**Comment by PygmalionOfCyprus** [comment]
Fixed 495.
