### ISSUE TITLE
CH-53E Super Stallion U.S.Navy

### ISSUE THREAD

**Issue by Ironduke28** [PygmalionOfCyprus/cmo-db-requests#1339]
### DB Selector

DB3K

### Baseline

CH-53E Super Stallion UCMC #516

### Hypothetical

No

### Name

CH-53E Super Stallion

### Country

USA

### Service

US Navy

### In Commission

1981

### Length (m)

30,188

### Wingspan (m)

24,08

### Height (m)

8,46

### Empty Weight (kg)

15071

### Maximum Takeoff Weight (MTOW) (kg)

33339

### Payload Weight (kg)

15000

### Crew

5

### Propulsion

3x General Elettric T64-GE-416

### Rate of Climb (ft/min)

2,5

### Service Ceiling (ft)

18500

### Military/Afterburner Speed (kt)

150

### Cruise Speed (kt)

120

### Supercruise

No

### Ferry Range (nm)

1140

### Endurance (min)

540

### Sensors

1x AN/APN-217
1X GENERIC fLIR
1X AN/APR-39
1X Mk1 Eyeball

### Mounts

2x .50 BMG (12.7x99mm) GAU-21 window-mounted
1x 50 BMG (12.7x99mm) GAU-21 ramp mounted
chaff anf flares dispensers

### Loadout Options

2x600 USG Drop Tank
cargo, 10 tons Slung Load (Cargo Trasport)

### Comms/Datalinks

VHF Radio
UHF radio

### Comments

aircraft Loadouts as #516 in BD3K

### Sources

https://en.wikipedia.org/wiki/Sikorsky_CH-53E_Super_Stallion

**Comment by PygmalionOfCyprus** [comment]
Added 495.
