### ISSUE TITLE
SSM Flt (Rail Based Peacekeeper)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#135]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

SSM Flt (Rail Based Peacekeeper)

### Facility Type

SSM

### Service

Air Force

### In Commission

1990

### Crew

42

### Dispersion Radius (m)

238.68m long (complete train)

### Sensors

1x mk1 eyeball

### Mounts

2x locomotives
2x launch cars (1x LGM-118A Peacekeeper each)
2x Security Force Cars
1x Launch Control Car
1x Fuel Car
1x Maintenance Car

### Magazines

No Reloads

### Aircraft & Docking Facilities

None

### Comments

Proposed Mobile Launch Platform for Peacekeeper ICBMs. 2 missiles per train.

### Sources

https://en.wikipedia.org/wiki/Peacekeeper_Rail_Garrison

https://en.wikipedia.org/wiki/LGM-118_Peacekeeper#Basing_options

https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/197554/peacekeeper-rail-garrison-car/

![download](https://user-images.githubusercontent.com/99599482/154351770-2cc3043a-3ee1-468f-92c4-bf64230ff4e9.jpg)

![download](https://user-images.githubusercontent.com/99599482/154351790-3b3c45ba-4921-47b8-b65c-928705b9ca75.jpg)

![download](https://user-images.githubusercontent.com/99599482/154351843-30e5b574-922f-4309-a620-84e44f03a84b.jpg)

![download](https://user-images.githubusercontent.com/99599482/154351804-3d710cba-d340-4bea-b2d4-9ebec7254b2f.jpg)

**Comment by KushanGaming** [comment]
Done for DB495.
