### ISSUE TITLE
ODAB-500PM/ShL FAE update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1351]
### DB Selector

DB3K

### Affected DBID(s)

3459, 664

### Summary of Changes

add: airburst (these have proximity fuzes)
change warhead to: ODAB-500 FAE [193kg FAE] (965 DP)
weight: 525kg
length: 2.39m
diameter: 0.5m
add retarded weapon to ODAB-500PM they both seem to have a parachute
the effectivenes of FAE is about 5x it's mass in TNT, the equivalency for the ODAB-500PM is described as around 1000kg TNT.

### Sources

Basalt Product Catalogue. Edition 2008, page 32–33

https://imgur.com/JCD48T6

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
