### ISSUE TITLE
FAB-275 and FAB-575 FAE update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1352]
### DB Selector

DB3K

### Affected DBID(s)

new entries in 494

### Summary of Changes

add: airburst (these have laser proximity fuzes)
change warhead to: FAB-275 M91 FAE [103kg FAE] (412 DP)
change warhead to: FAB-575 M91 FAE [215kg FAE] (860 DP) (estimated)
change launch altitude to: 650ft AGL - 39370ft AGL

These have less advanced FAEs with a 4x estimated equivalency 

### Sources

https://imgur.com/o8wQG8v

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
