### ISSUE TITLE
Japan Type 97 torpedo

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1353]
### DB Selector

DB3K

### Affected DBID(s)

314

### Summary of Changes

Kinetic Range
5nm to 7nm at 60kt

(Because this Type 97 has same type of engine of Mk50 (Weapon ID 1645), I believe the spec will be similar to it.)

Japanese Type 97 torpedo equipped by following,

DD 115 Akizuki (Ship ID 2293)
DD 119 Asahi (Ship ID 3128)
DDG 179 Maya (Ship ID 3211)
FFM 1 Mogami (Ship ID 3293)

This is same as
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1326

and also for 

DDH 181 Hyuga (Ship ID 480)

All of HOS 303 torpedo launcher can use Type 97.

DDG 179 Maya (Ship ID 3211) already has it, however, the Magazine only has Mk46 torpedo.

edited on June 18, for Izumo does not have HOS 303. This is incorrectly added to Izumo.

### Sources

wiki
https://en.wikipedia.org/wiki/Type_97_light_weight_torpedo_(G-RX4)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Also removed the HOS 303 from Izumo.
