### ISSUE TITLE
Generic Moblie Jammer

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1356]
### DB Selector

DB3K

### Hypothetical

No

### Name

Vehicle Moblie Jammer

### Facility Type

Mech

### Country

Generic

### Sensors

1x Generic Mobile Jammer (2000 tech version of 2539)

### Mounts

unarmed

### Aircraft & Docking Facilities

none

### Comments

Almost same as Iranian army's Mobile Jammer(Facility ID 764) but I want to use it for North Korea or other side with slightly newer systems.
I believe this is useful for some scenarios.

### Sources

**Comment by PygmalionOfCyprus** [comment]
I've just converted the Iranian one into a generic entry; I don't see any reason for Iran to have a monopoly on a generic jammer. Also, I added an "advanced" (early 2000s") version.
