### ISSUE TITLE
FAB-500ShL GPB

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1357]
### DB Selector

DB3K

### Baseline

3458

### Hypothetical

No

### Name

FAB-500ShL GPB -- Parabrake, 1986

### Length (m)

2.22

### Width/Span (m)

0.57

### Diameter (m)

0.45

### Weight (kg)

515

### Range (nm)

1

### Launch Altitude / Depth (ft)

100ft AGL - 3900ft AGL

### Warhead

FAB-500ShL [220kg TGAF-5M] (330DP)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

50

### Sensors

-

### Weapon Codes

Is Retarded Munition

### Comments

Modern thin cased blast bomb specifically designed for very low altitudes.

### Sources

http://www.airwar.ru/weapon/ab/fab-500sh.html

DB picture:
http://www.airwar.ru/image/idop/weapon/fab500sh/image006.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
