### ISSUE TITLE
US A/A: AIM-120 AN/ALQ-184 Pod, Heavy Loadout

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1358]
### DB Selector

DB3K

### Affected DBID(s)

A/C Loadout ID:11218

### Summary of Changes

USAF's F-16C - A/A: AIM-120 AN/ALQ-184 Pod, Heavy Loadout(ID:11218) has A/A: APKWS 2A instead of AIM-9X. Other Heavy A/A loadouts have AIM-9X so it should have that, too.

### Sources

none

**Comment by PygmalionOfCyprus** [comment]
This must have been fixed at some point because it's Sidewinders as of 508
