### ISSUE TITLE
KAB-500Kr-OD FAE

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1359]
### DB Selector

DB3K

### Hypothetical

No

### Name

KAB-500Kr-OD TV/EO [FAE]

### Length (m)

3.05

### Width/Span (m)

0.75

### Diameter (m)

0.35

### Weight (kg)

370

### Range (nm)

-

### Target Altitude / Depth (ft)

-

### Launch Altitude / Depth (ft)

-

### Warhead

KAB-500Kr-OD FAE [140kg FAE] (700DP)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

4

### Sensors

-

### Comments

I saw the Russian ordnance range request request by claudejdev. Most specs can be copied from the KAB-500Kr.

### Sources

http://roe.ru/eng/catalog/aerospace-systems/air-bombs/kab-500-od/

**Comment by nuk92** [comment]
DB picture:
https://i.imgur.com/wyMDuwv.png

**Comment by PygmalionOfCyprus** [comment]
Added 495.
