### ISSUE TITLE
SSM Flt (Mobile Minuteman)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#136]
### DB Selector

CWDB

### Hypothetical

Yes

### Name

SSM Flt (Mobile Minuteman)

### Facility Type

SSM

### Country

United States

### Service

Air Force

### In Commission

1960

### Crew

15 USAF plus Civilian Train Crew

### Dispersion Radius (m)

Variable

### Sensors

1x Mk 1 Eyeball

### Mounts

10-14 Rail cars including

3x or 5x Lauch Cars with 1 (LGM-30 Minuteman each)
1x Maintenance Car
1x Launch Control Car
4x Accommodation Cars

### Magazines

No Reloads

### Aircraft & Docking Facilities

None

### Comments

 would like to request the Train Based Minuteman ICBM as a hypothetical platform with two variants. Latest December 1960 plan called for 3 planned missile train squadrons, each with 10 trains carrying 3 missiles per train. Later plans called for 600 missiles to be placed in service, 450 in silos and 150 on special trains, each train carrying 5 missiles.

### Sources

https://en.wikipedia.org/wiki/LGM-30_Minuteman#:~:text=Mobile%20Minuteman%20was%20a%20program,details%20on%2012%20October%201959.

https://en.wikipedia.org/wiki/Minuteman_Mobility_Test_Train#:~:text=A%20Minuteman%20Mobility%20Test%20Train,by%20the%20Soviet%20missile%20force.

https://www.secretprojects.co.uk/threads/minuteman-deployment-concepts.8619/

https://fas.org/nuke/guide/usa/icbm/lgm-30_1.htm

![1421376035_800px-mobile_minuteman_artist_conception](https://user-images.githubusercontent.com/99599482/154351489-e3b45ef7-54bb-401f-a24c-ecae7e59784e.png)

![images](https://user-images.githubusercontent.com/99599482/154351527-0a8ab1b8-5270-47b2-8034-4180ed73a6a3.jpg)

**Comment by tbrandon517** [comment]
Consider for DB3K as if fully deployed probably would have served past 1980 before being replaced by rail based Peacekeepers or Midgetman.

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
