### ISSUE TITLE
Laser-Guided Sidewinder Missiles

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1360]
### DB Selector

DB3K

### Baseline

1401

### Hypothetical

No

### Name

LaGS (Laser Guided Sidewinder)

### Length (m)

2.85

### Width/Span (m)

0.63

### Diameter (m)

0.13

### Weight (kg)

86?

### Range (nm)

10

### Warhead

AGM-122A (WDU-31) (This should be closest warhead)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### Sensors

1x Laser Spot Tracker

### Weapon Codes

Terminal Illumination, Terrain Following, Weapon - INS Navigation, Level Cruise Flight

### Comments

Germany bought this for tornado in 2018 but Loadout is unclear.

### Sources

https://www.thedrive.com/the-war-zone/33797/watch-a-jas-39-gripen-fighter-fire-a-new-ground-attack-version-of-the-sidewinder-missile

https://www.armadainternational.com/2018/07/german-air-force-procures-300-laser-guided-sidewinder-missiles/

**Comment by tbrandon517** [comment]
Copy of request #206

**Comment by PygmalionOfCyprus** [comment]
Closed as duplicate, but OG issue handled. Added 495.
