### ISSUE TITLE
KAB-1500Kr-OD FAE

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1361]
### DB Selector

DB3K

### Baseline

641

### Hypothetical

No

### Name

KAB-1500Kr-OD TV/EO [FAE]

### Length (m)

4.63

### Width/Span (m)

0.85

### Diameter (m)

0.58

### Weight (kg)

1525

### Range (nm)

-

### Target Altitude / Depth (ft)

-

### Launch Altitude / Depth (ft)

-

### Warhead

KAB-500Kr-OD FAE [650kg FAE] (3250DP)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

4

### Sensors

-

### Comments

Most specs can be copied from the KAB-1500Kr. This one has a FAE warhead. The ODAB-500 mixture has a TNT equivalency of 5x it's weight.

### Sources

http://roe.ru/eng/catalog/aerospace-systems/air-bombs/kab-1500kr-od/

**Comment by nuk92** [comment]
DB picture:
https://i.imgur.com/wyMDuwv.png

**Comment by PygmalionOfCyprus** [comment]
Added 495.
