### ISSUE TITLE
BUG: US M109A7 Arty (2020)

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1362]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3228

### Description of Problem

ERROR: The requested object has been deprecated in the database.
Cannot place this with the message.

**Comment by PygmalionOfCyprus** [comment]
Oh, _weird_. Facility deprecation isn't even on the forms; it's a totally unused data field buried deep inside the Facility table. To deprecate something you have to know where to look and then you have to dig for it.

Somehow this is the only Facility in the entire database that's been deprecated. One of the DB's many mysteries.

Anyway, fixed for 495.
