### ISSUE TITLE
Japan DD 110 Takanami

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1364]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1148, 2488, 1742

### Summary of Changes

RIM-7P Sea Sparrow Missile (Weapon ID 1003) for 2003 and 2004 version

Phalanx CIWS 1"B" (ASuW capable CIWS), for 2004 and 2015 version

### Sources

https://ja.wikipedia.org/wiki/%E3%81%9F%E3%81%8B%E3%81%AA%E3%81%BF%E5%9E%8B%E8%AD%B7%E8%A1%9B%E8%89%A6

**Comment by PygmalionOfCyprus** [comment]
Fixed/added 495. Also changed the 2015 VLS into two separate 16-cell VLSes rather than a single blob to reflect their different positioning on the ship.

**Comment by KC45jp** [comment]
hmm...
Unlike Murasame class with separate Mk41 in bow and Mk48 in back, Takanami Class have all 32cell mk41 vls in the front.
Here is a pic. I would say it is one set of mk41, instead of two separate. 
http://gunnzihyouronn.web.fc2.com/kaizi/dd/takanami/vls.jpg

**Comment by PygmalionOfCyprus** [comment]
Aha, I misread this:

>またVLSの統合化も、艦内設計に大きな変更を必要とした。03DDでは、艦首甲板に埋め込むかたちで垂直発射型アスロック（VLA）用のMk.41（16セル）を、また第2煙突直前の甲板上にシースパロー用のMk.48（16セル）を設置していたのに対して、本型では、Mk.41を両者兼用として、32セルに増やしている。ただし艦内区画の関係上、主船体内に完全に収容することができずに、1甲板分装備位置を上げることとなった。なお、ここから運用される個艦防空ミサイル（短SAM）としては、従来はRIM-7M(PIP)シースパローが用いられていたが、平成26・27年度予算において、「たかなみ型護衛艦の短SAMシステムの能力向上」として、ESSM（発展型シースパロー）運用能力の付与が決定され、以後順次改装された。

I skimmed it and assumed it was talking about the Takanami but actually it was describing the Murasame layout. Fixed: now the 2003-4 versions have a single 32-cell Mk41 w/ 16x VLA and 16x RIM-7P, while the 2015 version retains the 32-cell Mk41 but has those 16x RIM-7P replaced w/ 32x (quad-packed) ESSM.
