### ISSUE TITLE
RBK-500 SPBE-D

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1369]
### DB Selector

DB3K

### Baseline

802

### Hypothetical

No

### Name

RBK-500 SPBE-D [15 x SPBE-D Anti-Tank Bomblets]

### Length (m)

2.49

### Width/Span (m)

0.57

### Diameter (m)

0.45

### Weight (kg)

500

### Range (nm)

1

### Launch Altitude / Depth (ft)

1312ft AGL - 16404ft AGL

### Warhead

RBK-500 SPBE-D (15 x SPBE-D) 5.8kg Anti-Tank (87 DP)

### Targets

Surface Vessel, Land Structure - Soft, Mobile Target - Soft

### CEP (m)

50

### Sensors

-

### Comments

launch speed: 270kts - 650kts

### Sources

https://armamentresearch.com/rbk-500-spbe-cargo-munitions-employed-in-syria/

DB pictures:
https://armamentresearch.com/wp-content/uploads/2015/10/RBK-500-SPBE-D.jpg
https://i.imgur.com/LFjFQyW.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
