### ISSUE TITLE
RCN - AOR 500 HMCS Provider

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#137]
### DB Selector

CWDB

### Affected DBID(s)

1285, 233, 235

### Summary of Changes

#1285 – 500 Provider (Canada – 1963) 
# 233 – 500 Provider (Canada – 1967) 
# 235 – 500 Provider (Canada – 1972)]

- Unit number should be 508 not 500, AOR designation missing
- 7,400t light, 22,000t full 
- beam, draft, displacement varies between versions, please correct, 1963 version seems to have the correct dimensions but missing the displacement
- missing 1x LCVP and 1x 11m RHIB

Confused by #2558 entry for same ship covering 1964-98. Was it intended to replace the above three mentioned? Commissioning date is 1963, not 1964

### Sources

https://en.wikipedia.org/wiki/HMCS_Provider_(AOR_508)
https://www.rcnhistory.org/berbeck-shiplist-provider.htm 
[www.hazegray.org/navhist/canada/postwar/provider/](http://www.hazegray.org/navhist/canada/postwar/provider/) 
http://readyayeready.com/ships/shipview.php?id=1337

**Comment by Jkryos** [comment]
Okay this was a bear. As far as anyone can tell 233, 235, and 1285 are just wrong with 2558 actually be the Provider added properly. 233, 235, and 1285 have been marked as deprecated and 2558 has been updated to change the in service date and add the docking facilities. CWDB 497.
