### ISSUE TITLE
Japan DE 229 Abukuma 1989, 2000

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1375]
### DB Selector

DB3K

### Affected DBID(s)

SHIP 79, 537

### Summary of Changes

Sensor
-Delete J/OPS-24
-Add J/OPS-28C (ID 1180)

-Delete J/NOLR-6 
-Add J/NOLR-8 (Sensor ID 3999, plz change it to Early 1980 tech)

-Add J/OAX-1B (1970 tech FLIR, Similar to Sensor ID 930)

Mounts
-2x 12.7mm/50 MG (one for right and another for left side, 180 degree for each, local control)

Magazines
-1x Mk46 Mod 5 [external tubes] (with 12x Mk46 Mod5)
-12.7mm/50 MG

2000 version of Abukuma (ID 573) has OQR-2 TASS. This was actually planned, however, cancelled. Thus we should mark this as Hypothetical.
Perhaps we can add 1x Mk 31 RAM (Short Range SAM) for 2000 because it was planned as adding TASS.

### Sources

https://ja.wikipedia.org/wiki/%E3%81%82%E3%81%B6%E3%81%8F%E3%81%BE%E5%9E%8B%E8%AD%B7%E8%A1%9B%E8%89%A6

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. For the hypothetical 2000 entry, does the Mk31 replace the Mk15 or supplement it? And if it's an addition rather than a replacement, bow or aft?

**Comment by KC45jp** [comment]
Mk31 is addition to Abukuma, and  It will place just back of the 76mm Cannon.

https://twitter.com/kh840124/status/1002534561731891203

**Comment by PygmalionOfCyprus** [comment]
Brilliant, great reference. Thanks!
