### ISSUE TITLE
Japan FFM 1 Mogami

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1376]
### DB Selector

DB3K

### Affected DBID(s)

SHIP 3292, 3293

### Summary of Changes

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/12

> Originally, the first vessels in-class were not going to be fitted with the Mk41 (hence FFBNW until FFM-3); this appears to have changed with the supplementary FY2021 budget. We'll mark #3292 as a hypothetical and rename #3293 to "FFM 1 Mogami" as well to represent the newly VLS-equipped first-in-class.

I do not see any resource suggesting this change, please revise it.

FFM 1 thru 6 does not equip VLS. VLS will likey added from 7th Ship by FY2021 budget, thus ID 3293 with VLS could be a placeholder.

Other Changes

Sensors
J/NOLQ-3D-1[ESM] (ID 6267)→ J/NOLQ-3E[ESM] (Name Change, + late 2010 tech)
J/NOLQ-3D[ECM] (ID 6267)→ J/NOLQ-3E[ECM] (Name Change, + late 2010 tech, can attack I band only)
J/OAX-3 → J/OAX-3[TV] (Name Change)
J/OAX-2→J/OAX-3[IR] (Name Change)

Mounts
HOS-303 add Type 97 capability as requested at #1353
Delete AN/SLQ-25 Nixie

Magazines
Type 97 torpedo [External Tubes] as requested at #1353

### Sources

Budget for VLS of FFM 7 and 8
https://www.ships-net.co.jp/%e2%96%a0%e9%98%b2%e8%a1%9b%e7%9c%81%e6%89%80%e7%ae%a1%e3%81%ae%e4%bb%a4%e5%92%8c%ef%bc%93%e5%b9%b4%e5%ba%a6%e8%a3%9c%e6%ad%a3%e4%ba%88%e7%ae%97%e3%81%ae%e6%a6%82%e8%a6%81/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
