### ISSUE TITLE
S-300V4 SA-23 FCR Name and Range

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1378]
### DB Selector

DB3K

### Affected DBID(s)

4819

### Summary of Changes

NATO name is not Grill Pan, which only applies to SA-12, instead it should be referred to as Grill Screen.
Just looking at the radar it can be seen that it is of a highly modified design.
The ranges need to be looked at too, as whats the point of having a Fire Control Radar who's range is less than the missile that it is providing tracking and guidance for.  Common error with the S-300V family. The intercept point (for the Pershing II) is quoted as max range, it's not, it's just the range at which it will intercept the incoming missile.  Against aerodynamic targets the range is much greater.

### Sources

https://www.radartutorial.eu/19.kartei/06.missile/karte015.en.html
http://www.ausairpower.net/APA-Giant-Gladiator.html

**Comment by PygmalionOfCyprus** [comment]
Radar now has a range of 300km (may be too high, probably too low, who knows) w/ suitable power to detect fighter-sized targets at 250km. I also upped the range on the 9M82M to 250km as per the AAP article.
