### ISSUE TITLE
Russia Nebo-SVU

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1379]
### DB Selector

DB3K

### DBID to Copy

1849

### Hypothetical

No

### Name

1L119 Nebo-SVU

### Country

Russia

### Service

Air Force (VVS)

### In Commission

2000's to present

### Other Changes

Just found it odd to find this only under Iran, when the user customers appear from the sources to be Russia and Algeria

### Sources

http://www.ausairpower.net/APA-Nebo-SVU-Analysis.html

**Comment by PygmalionOfCyprus** [comment]
Added 495 for Russia and Algeria.
