### ISSUE TITLE
RCN - R 22 Bonaventure - 1967

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#138]
### DB Selector

CWDB

### Affected DBID(s)

4

### Summary of Changes

- Full load displacement is 20,000t, length 214.6m (see fact sheet)
- AN/SPS-12 replaced by [AN/SPS-501](http://cmano-db.com/sensor/693/) during midlife refit (1967)

### Sources

http://www.hazegray.org/navhist/canada/postwar/carriers/ 
http://cmano-db.com/sensor/693/ 
https://www.friends-amis.org/index.php/en/document-repository/english/fact-sheets/45-hmcs-bonaventure/file

**Comment by Jkryos** [comment]
Updated CWDB 494.
