### ISSUE TITLE
Correction for UMS Tabinshwehti (773) 

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1384]
### DB Selector

DB3K

### Affected DBID(s)

3113 UMS Tabinshwehti (773)

### Summary of Changes

-change the 2x AK-630M CIWS(DBID 460) to H/PJ-13 CIWS(3447).

-Add another Type 347G FCR (DBID 3028) radar as it do have another FCR directly above the hangar, facing aft. Most probably to control the 2x H/PJ-13 CIWS
![image](https://user-images.githubusercontent.com/99646926/174464553-eeb9f75f-e95a-4bfa-bf59-e2fce69d9fbd.png)

-Add LW.08 radar(DBID 1191) . It were seen to be fitted with it just like UMS Kyan Sittha (DBID 3109)
![image](https://user-images.githubusercontent.com/99646926/174464558-10cda41b-a8b5-4055-ae90-258e7ee91832.png)

-Increase the missile defence against 1 missile to 2 missiles as it have better armament and sensors compared to older 771 UMS Anawrahta(DBID 3110, 3111, 3112)

-Add SATCOM communication as it have those directly behind the FCR above the hangar.

### Sources

https://defence.pk/pdf/threads/myanmar-navy-commissions-first-corvette-with-reduced-rcs.469625/
https://warsearcher.com/shipsearcher/navy-of-myanmar-current-and-retired/myanmar-corvettes-and-patrol-ships/
https://thaimilitaryandasianregion.wordpress.com/2016/12/30/myanmar-navy-commissions-first-stealth-corvette/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
