### ISSUE TITLE
Name update Type 003 - 2023 PLACEHOLDER DBID 3466

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1385]
### DB Selector

DB3K

### Affected DBID(s)

DB3K #3466

### Summary of Changes

Named Fujian

### Sources

Multiple. 
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/june/11831-china-launches-the-type-003-aircraft-carrier-fujian.html

**Comment by PygmalionOfCyprus** [comment]
Already done. 😉
