### ISSUE TITLE
Add Uganda MI-28NE 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1391]
### DB Selector

DB3K

### DBID to Copy

3785

### Hypothetical

No

### Name

MI-28NE Havoc

### Country

Uganda

### Service

Air Force

### In Commission

2022

### Number in Service

3+

### Sensors

default export

### Mounts

default export

### Loadout Options

Default export

### Sources

https://www.scramble.nl/military-news/uganda-acquires-mi-28ns
https://twitter.com/RALee85/status/1537946951894765570
https://bmpd.livejournal.com/4542920.html

**Comment by PygmalionOfCyprus** [comment]
Added 495.
