### ISSUE TITLE
MIG-39

### ISSUE THREAD

**Issue by B-30F9** [PygmalionOfCyprus/cmo-db-requests#1393]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

MIG-39

### Country

Russia

### Service

Air Force

### In Commission

Never into service

### Number in Service

1

### Length (m)

DNS

### Wingspan (m)

DNS

### Height (m)

DNS

### Empty Weight (kg)

DNS

### Maximum Takeoff Weight (MTOW) (kg)

DNS

### Payload Weight (kg)

DNS

### Crew

1

### Propulsion

AL41-F

### Service Ceiling (ft)

DNS

### Military/Afterburner Speed (kt)

DNS

### Cruise Speed (kt)

DNS

### Supercruise

Yes

### Ferry Range (nm)

1620

### Sensors

1xAP-77
1xN-014
1xN-011

### Mounts

DNS

### Loadout Options

R-77PD

### Sources

DNS

**Comment by PygmalionOfCyprus** [comment]
My view as well. However, I've edited the name to be clearer (the MiG-35 designation in the DB has since been reassigned to a different aircraft): it is now called the "MiG 1.42 Foxglove" w/ "MiG-39, MFI" in the comments.
