### ISSUE TITLE
Update Z-10 Rocket Loadouts 30162 and 17478

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1395]
### DB Selector

DB3K

### Affected DBID(s)

Loadout 30162 and 17478

### Summary of Changes

Z-10 rocket loadouts were optimistic when made. Have only found 7-tube rocket pods. Type 90-1

Heavy loadout 30162 is 4 pods- 28 rockets
Light loadout 17478 is 28 rockets , typically with fuel tanks for range

### Sources

https://www.sinodefenceforum.com/t/z-10-thread.2879/page-283
https://live.staticflickr.com/65535/51531919438_8d36d0b3b0_h.jpg
https://www.sinodefenceforum.com/t/z-10-thread.2879/page-282
https://live.staticflickr.com/65535/51210985370_f162ec6371_o.jpg
https://www.sinodefenceforum.com/t/z-10-thread.2879/page-276
https://www.sinodefenceforum.com/t/z-10-thread.2879/page-270#post-666031

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. All the other rocket loadouts for the Z-10 were assuming 7-rnd launchers anyway so this makes more sense.
