### ISSUE TITLE
Add LJ-7/ LJ-9 Loadout to Z-10

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1396]
### DB Selector

DB3K

### User(s)

2493

### Weapons Carried

LJ-7/LJ-9 Seems to be common ATGM loadout on Z-10. Pylons are quad launchers.

All ATGM
16 LJ-9

### Requires Buddy Illumination

No

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://2.bp.blogspot.com/-4yc2N4zcNH0/VaphpEpcGsI/AAAAAAAALrM/QhFwJGLj7JM/s1600/Z-10_KD-9.jpg
https://live.staticflickr.com/65535/51210985370_f162ec6371_o.jpg
https://www.sinodefenceforum.com/attachments/z-10x2-jpg.74739/
https://live.staticflickr.com/65535/50188608921_2b67ae92ab_h.jpg
https://www.sinodefenceforum.com/attachments/a-jpg.54107/
https://live.staticflickr.com/65535/48748483626_6db0b1f65f_o.jpg
https://live.staticflickr.com/65535/48781412181_24fae80810_o.jpg
https://live.staticflickr.com/65535/32722287687_751fa89724_k.jpg
https://www.sinodefenceforum.com/attachments/z-10a-mod-lh962182-2-xs-jpg.49016/

**Comment by PygmalionOfCyprus** [comment]
Handled w/ 1399.
