### ISSUE TITLE
Add TY-90 AAM

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1397]
### DB Selector

DB3K

### Hypothetical

No

### Name

TY-90

### Length (m)

1.9m

### Width/Span (m)

.216

### Diameter (m)

.09

### Weight (kg)

20

### Range (nm)

.27-3.24

### Target Altitude / Depth (ft)

19685 ft

### Target Speed (kts)

0-700kts

### Launch Altitude / Depth (ft)

0-19685 ft

### Warhead

3kg 

### Targets

Aircraft, Helicopter

### Sensors

IIR Seeker

### Weapon Codes

Anti-Air All-Aspect

### Sources

https://en.wikipedia.org/wiki/TY-90
https://en.missilery.info/missile/ty-90
https://twitter.com/aviation07101/status/1308431940165480450

**Comment by PygmalionOfCyprus** [comment]
Handled this with #1402
