### ISSUE TITLE
Add TY-90 Loadout to Z-10

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1398]
### DB Selector

DB3K

### User(s)

2493

### Weapons Carried

4 TY-90 per pylon. 

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Didn't see any pictures of other AAM's integrated.
First TY-90 pics 2018

### Sources

https://live.staticflickr.com/65535/51763611262_bcf471f489_k.jpg
https://live.staticflickr.com/65535/51531919553_0ea3e74aa2_h.jpg
https://live.staticflickr.com/65535/51531919523_80e7b2faa3_h.jpg
https://www.sinodefenceforum.com/t/z-10-thread.2879/page-267#post-634697
https://twitter.com/detresfa_/status/1308429524665688064
https://twitter.com/stoa1984/status/1034992001077272576
https://live.staticflickr.com/65535/49953236573_c79910c444_k.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled with #1399.
