### ISSUE TITLE
Add additional Mk-13 loadouts to #418 Tejas

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#14]
### DB Selector

DB3K

### User(s)

418 Tejas

### Weapons Carried

1)Heavy 6 Mk-13 1000lb bombs, 2 Archers, 1 725kg drop tank
2)Long range 2 Mk-13, 3 725kg drop tanks, 2 Archers, 1 Lightening Pod
3)Standard 4 Mk-13, 2 725Kg drop tanks, 2 Archers, 1 Lightening Pod

### Requires Buddy Illumination

- [ ] Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

- [ ] Yes

### Sources

https://twitter.com/warplane_porn/status/1456656937504890887
https://thebharatmilitaryreview.blogspot.com/2013/12/indian-light-combat-aircraft-lca-tejas.html
https://defenceforumindia.com/threads/lca-tejas-mk1-mk1a-news-and-discussion.81401/page-213#lg=attachment49623&slide=0
https://twitter.com/JaidevJamwal/status/1402898829851054080/photo/1
https://thebharatmilitaryreview.blogspot.com/2012/10/indian-air-forces-lca-light-combat.html

**Comment by Jkryos** [comment]
Added DB3K 493.
