### ISSUE TITLE
Add LJ-7/ LJ-9 Loadout to Z-19

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1401]
### DB Selector

DB3K

### User(s)

3305

### Weapons Carried

Z-19 seems to use LJ-7/LJ-9 ATGM Operationally

4 Missiles per pylon.

Full loadout 16.
Generally 8 + rocket pods or Fuel Tanks

### Requires Buddy Illumination

No

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://twitter.com/zspcl/status/1509831146959519763/photo/4
https://twitter.com/zspcl/status/1509831146959519763/photo/2
https://live.staticflickr.com/65535/51713306709_178a0d7341_h.jpg
https://www.sinodefenceforum.com/attachments/harbin-z-19-199-jpg.74627/
https://live.staticflickr.com/65535/48895184887_1f08c2a993_k.jpg
https://i.imgur.com/2pIwuik.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
