### ISSUE TITLE
Update Z-19

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1402]
### DB Selector

DB3K

### Affected DBID(s)

3305

### Summary of Changes

Add version with MMR and one without. Few have the MMR at the top of the rotor .
Add LJ-7/LJ-9 loadouts (separate request)
Do have helmet displays
Add TY-90 AAM loadout (separate requests)

Suggestions:

There has been different mast mounted radars. I wouldn't go there just yet. Just have or have not.
https://www.sinodefenceforum.com/t/z-19-armed-recon-helicopter.5428/page-44#post-503694

Did not come across pictures of HJ-8 ATGM

External fuel Tanks look like 500 liter (130 Gallons)

### Sources

Some with MMR some without
https://twitter.com/AlexLuck9/status/1482958151792328704/photo/1
https://www.sinodefenceforum.com/attachments/z-19-1-jpg.88552/
https://www.sinodefenceforum.com/t/z-19-armed-recon-helicopter.5428/page-47
https://www.sinodefenceforum.com/t/z-19-armed-recon-helicopter.5428/page-44#post-503694

helmet displays
https://live.staticflickr.com/65535/51163032112_490933f121_k.jpg
https://live.staticflickr.com/65535/51164480454_5bf3a66613_k.jpg

**Comment by PygmalionOfCyprus** [comment]
Fixed/added 495.
