### ISSUE TITLE
Add TY-90 AAW Loadout to Z-19

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1403]
### DB Selector

DB3K

### User(s)

3305

### Weapons Carried

4 TY-90 per pylon

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

IOC likely 2020-2021

### Sources

https://live.staticflickr.com/65535/51200161699_5c4b7f6e9b_o.jpg
https://www.sinodefenceforum.com/t/z-19-armed-recon-helicopter.5428/page-48#post-703797
https://www.sinodefenceforum.com/t/z-19-armed-recon-helicopter.5428/page-49

**Comment by PygmalionOfCyprus** [comment]
Added 495.
