### ISSUE TITLE
Netzahualcoyotl (D-102) (Mexican Navy)

### ISSUE THREAD

**Issue by RevanstheBomb** [PygmalionOfCyprus/cmo-db-requests#1406]
### DB Selector

DB3K

### Baseline

#2850 D 25 Marcilio Diaz [Gearing FRAM I] (Brazil - 1974) 

### Hypothetical

No

### Name

D-102

### Class

Gearing-Class

### Country

Mexico

### Service

Mexican Navy

### In Commission

1982-2014

### Number in Service

1x

### Length (m)

118.8m

### Beam (m)

12.5m

### Draft (m)

3.97m

### Standard Displacement (t)

3516t

### Complement

290

### Primary Propulsion Type

Steam

### Propulsion

4x Boilers, 2x General Electric Steam Engines

### Flank Speed (kt)

36.8

### Range (nm) at Speed (kt)

4500 @ 20

### Sensors

1x AN/SQS-23
1x AN/SPS-10B
1X AN/SPS-40
1x AN/SPG-35
1x AN/WLR-1
1x Mk1 Eyeball

### Mounts

1x Mk46 LWT Mod 2
1x Mk16 ASROC
1x Mk9 Depth Charge
1x 127mm/38 Mk38 Twin
1x 35mm/90 Twin Oerlikon
1x Mk11 Hedgehog ASW Mortar Salvo

### Aircraft & Docking Facilities

1x Pad for Medium Helicopter

### Sources

https://es.wikipedia.org/wiki/ARM_Netzahualc%C3%B3yotl_(D-102)
http://www.navsource.org/archives/05/helpers/fram.htm
http://www.navsource.org/archives/05/863.htm

**Comment by PygmalionOfCyprus** [comment]
This can be classed as a "copy" since it's a Gearing class and we have oodles of those in the DB to build from.

**Comment by PygmalionOfCyprus** [comment]
Where are you getting your info on ship armament? This is different from what I'd expect of a Gearing FRAM IB and not verifiable through what images I can find.

**Comment by RevanstheBomb** [comment]
My apologies - Used differing sources, whether it's from the links I provided or the CMANOdb.com
https://cmano-db.com/

**Comment by PygmalionOfCyprus** [comment]
Using the CMO DB as a source for changes to the CMO DB...bit incestuous, isn't it? 😆

Do we have any specific information about the Netzahualcoyotl herself, rather than generic info about the Gearings? Her sister ship and class nameship, E 03/10/D 101 Quetzalcoatl/Ilhuicamina (good grief, pick a name, Mexico!) has more info available, and her fit changed dramatically over the years. For example, by '94 she'd lost her ASW armament (ASROC, torpedoes) entirely.

If we don't have any evidence that D 102 differed significantly from her sister, it'd be better to just add the nameship. If you're alright with that I can do that instead and close this ticket when I have.

**Comment by RevanstheBomb** [comment]
Again, sorry about that. I'll not use CMO DB for info next time.

I was able to find this bit of info on how individuals dedicated to the Gearing-class were able to observe the Netzahualcoyotl in action during her service in the Mexican Navy. Apparently her ASW weaponry was retained, even before her retirement. (plus, it has a link to a YT video about the Netza - Heads up, the vid's text is in Spanish! However, as one who's taken Spanish before and tinkered with it, I can tell it's generally about the ship and its history)
http://www.ussbordelon.org/contents/en-us/d241.html

As for how it differs from the ex-Vogelgesang (man, it's easy to miss the "ge" before the "sang" part!), the Quetzalcoatl...

Judging by this Wikipedia article on the Vogelgesang, you're right about the Quetzalcoatl getting rid of her ASW mounts in '94.
https://en.wikipedia.org/wiki/USS_Vogelgesang_(DD-862)

Aside from that, information on how they differ is incredibly limited. (Especially with what I learned from this here about any information on the Mexican Military)
https://nsarchive2.gwu.edu/NSAEBB/NSAEBB120/index.htm
So, we might as well settle for the nameship.

**Comment by PygmalionOfCyprus** [comment]
That old salt is actually a really useful source, good find. It indicates the Netza doesn't seem to have received any of the swap-outs, changes, etc. her big sister did and, in his words, was "an almost unmodified GEARING-class FRAM Mk I ship, complete with all her ship handling, weapon systems, and sensors intact." So, I can probably pretty safely base her off info on the Steinaker, which is more readily available (at least in English).

I'm more comfortable now that I have enough information to add both.

**Comment by PygmalionOfCyprus** [comment]
Added 495.
