### ISSUE TITLE
YJ-21/YJ-XX Anti-ship ballistic missile

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1416]
### DB Selector

DB3K

### Baseline

2106

### Hypothetical

No

### Name

YJ-21/YJ-XX ASBM (ship-based vertical launch)

### Length (m)

9.00

### Width/Span (m)

1.00

### Diameter (m)

0.85

### Weight (kg)

3800

### Range (nm)

50.0-800.0

### Target Altitude / Depth (ft)

-

### Target Speed (kts)

-

### Launch Altitude / Depth (ft)

-

### LaunchSpeed (kts)

-

### Warhead

800kg 

### Targets

Surface Vessel

### CEP (m)

2

### Sensors

1x Active Radar Seeker (~50nm Range), late 2010s techology
1x Passive Radar Seeker (~10nm Range), late 2010s technology

### Weapon Codes

Home On Jam (HOJ), Ballistic Missile or Rocket Booster, Weapon - INS w/ GNSS Navigation, Terminal Maneuver - Zig-Zag, Uses BeiDou/COMPASS, Level Cruise Flight

### Comments

1. Launch paltform: type 052d DDG & type 055 CG, China VLS Type GJB 5860-2600A(32/64 cells)
2. Surface PoH/Reliability: 90%

### Sources

https://zh.wikipedia.org/wiki/%E9%B9%B0%E5%87%BB21%E5%8F%8D%E8%88%B0%E5%AF%BC%E5%BC%B9
https://en.wikipedia.org/wiki/Maneuverable_reentry_vehicle
https://www.navalnews.com/naval-news/2022/04/china-test-fires-new-yj-21-hypersonic-missile/
https://www.sinodefenceforum.com/t/plan-anti-ship-surface-missiles.6345/page-107
https://www.sinodefenceforum.com/t/055-ddg-large-destroyer-thread.6480/page-952

**Comment by PygmalionOfCyprus** [comment]
Added 495. Obviously a lot of info is unknown so this will need to be revisited over time as/if more data becomes available.

**Comment by LuigiP57** [comment]
> 

Yeah, continuous effort needed.
