### ISSUE TITLE
J-20S require

### ISSUE THREAD

**Issue by B-30F9** [PygmalionOfCyprus/cmo-db-requests#1417]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

J-20S

### Country

China

### Length (m)

the same as J-20 maybe

### Wingspan (m)

the same as J-20 maybe

### Height (m)

the same as J-20 maybe

### Empty Weight (kg)

the same as J-20 maybe

### Maximum Takeoff Weight (MTOW) (kg)

the same as J-20 maybe

### Crew

2

### Propulsion

2 x WS-10

### Service Ceiling (ft)

the same as J-20 maybe

### Military/Afterburner Speed (kt)

the same as J-20 maybe

### Cruise Speed (kt)

the same as J-20 maybe

### Supercruise

Yes

### Ferry Range (nm)

the same as J-20 maybe

### Endurance (min)

the same as J-20 maybe

### Takeoff / Landing Distance (m)

the same as J-20 maybe

### Sensors

the same as J-20 maybe

### Mounts

the same as J-20 maybe

### Loadout Options

the same as J-20 maybe

### Comments

It is worth making because two people operates this plane.
It seems that the back one operate Chinese UAS -- FH-97
![Uploading image.png…]()

### Sources

https://cn.bing.com/search?q=J-20S&form=QBLH&sp=-1&pq=j-20s&sc=0-5&qs=n&sk=&cvid=EB3706595DF24B1A9F50F386C6B6155E

**Comment by PygmalionOfCyprus** [comment]
This is already in the DB as AC #5454; however, it's named incorrectly. The J-20S designation must be new! Fixed for 495.

Also, you shouldn't use the addition form for copies of existing aircraft. If you're just going to write "same as X" for all the entries you may as well use the Copy Entry form and save yourself the trouble.
