### ISSUE TITLE
tethered quadcopter UAV

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1418]
### DB Selector

DB3K

### Hypothetical

No

### Name

tethered quadcopter UAV

### Facility Type

Inf

### Country

Generic

### Service

Generic

### In Commission

2020

### Crew

1

### Dispersion Radius (m)

0

### Sensors

1x generic TV camera
1x generic IR camera
1x generic laser rangefinder

(same as generic FLIR turret (weapon #3787)
(ranges for these are 30nm which is far too high for a UAV turret, but that's what the generic quadcopter UAV (#5416) has. Maybe make a lightweight version of them with only 10 or 15nm max range?

Sensor height is 100m

### Mounts

none

### Magazines

none

### Aircraft & Docking Facilities

none

### Comments

These systems usually require a diesel generator of around 6kW, that could be modelled in the IR signature

### Sources

https://elistair.com/orion-tethered-drone/

**Comment by PygmalionOfCyprus** [comment]
What an interesting idea.

I don't think this is worth attempting to model in Command, though. We don't have a good way of simulating a "tethered" aircraft that isn't a blimp, and at the end of the day this is just another of a trillion different quadcopter variants. (There's a reason I just created a generic and didn't bother trying to simulate every marginally different version.) 

In the grand scheme of things this capability can be simulated with a quadcopter attached to any facility (remember the new version will allow you to base small UAVs on anything regardless of aircraft facilities), with a bit of Lua to model any unique restrictions/advantages if they're essential to the scenario.

**Comment by PygmalionOfCyprus** [comment]
Oh, I didn't actually realize it can't move. I thought it was just a normal quadcopter with a giant extension cord for increased endurance. 😆

Good thinking on implementation. Reopening.

**Comment by PygmalionOfCyprus** [comment]
Added 495, basically treating it like we do aerostats.
