### ISSUE TITLE
RCN - DDH 265 Annapolis – 1967

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#142]
### DB Selector

CWDB

### Affected DBID(s)

184

### Summary of Changes

-	Crew drops from 228 on 1964 unit to 210 on this entry and back to 228 on 1972 unit. The crew did not decrease to 210 until the DELEX which took place in 1984 (Nipigon) and 1986 (Annapolis)
-	Mk46 LWT Mod 2 - (1972) Torpedo is fitted on this unit while Mk46 LWT Mod 1 - (1969, Major version) Torpedo is fitted on 1972 unit in CWDB and DB3000, should this be flipped?

### Sources

http://www.hazegray.org/navhist/canada/postwar/annapoli/

**Comment by Jkryos** [comment]
Updated.
