### ISSUE TITLE
French Overseas OPV (POM)

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1420]
### DB Selector

DB3K

### Hypothetical

No

### Name

P779 Auguste Bénébig OPV

### Class

Patrouilleur Outre-Mer

### Country

France

### Service

Navy

### In Commission

2023

### Number in Service

6

### Length (m)

80

### Beam (m)

11

### Draft (m)

3.5

### Standard Displacement (t)

1300

### Complement

30

### Primary Propulsion Type

Diesel

### Propulsion

2x Hybrid Diesel Egines

### Flank Speed (kt)

24

### Range (nm) at Speed (kt)

5500nm @ 12 kt

### Sensors

-1x Kelvin Hughes Mk11 SharpEye surface search radar
-1x MSSR 2000 IFF
-1x generic TV camera
-1x generic infrared camera

### Mounts

1x 20mm Narwhal RWS
4x .50 machine gun

### Aircraft & Docking Facilities

1x pad for small helicopter
2x 8m davit
1x catapult for ALIACA UAV

### Comms/Datalinks

VHF/UHF
military SATCOM
Link 22

### Sources

https://www.navalnews.com/naval-news/2021/09/french-navys-new-pom-opvs-take-shape-at-socarenam-shipyard/

**Comment by Jkryos** [comment]
Added DB3K 505.
