### ISSUE TITLE
add magazine for HQ-17 battery

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1422]
### DB Selector

DB3K

### Affected DBID(s)

2515 HQ-17(SA-15 copy) & 3036 PGZ-07/HQ-17(SA-15 copy)

### Summary of Changes

add magazine for extra 16 missiles as each launcher probably have its own reloading vehicles as per pics below. 
![image](https://user-images.githubusercontent.com/99646926/175056073-66fd663e-3ef4-4b3d-adb3-8805fc2db780.png)
![image](https://user-images.githubusercontent.com/99646926/175056977-36833c1a-4b2a-4adb-81cd-636268379a9d.png)

### Sources

http://www.military-today.com/missiles/hq_17_images.htm
https://www.reddit.com/r/Warthunder/comments/kyfjqi/gaijin_please_hq17_shortrange_air_defense_missile/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
