### ISSUE TITLE
Latvia Storm Class x4 (ex-Norwegian)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1426]
### DB Selector

DB3K

### DBID to Copy

3099 DB3K

### Hypothetical

No

### Name

P-01 Zibens

### Country

Latvia

### Service

Navy

### In Commission

1994-2013

### Number in Service

4

### Sensors

- Decca 1226 (P-04)
- Furuno navigation radar (P-01-03)
- TVT300 optical director

### Mounts

- P-04 1x 40mm 60cal Bofors Mk33 AA
- P-01-03 1x 76.2mm 50cal Bofors low angle (fwd)
- 1x 40mm 70cal Bofors L70 AA (aft)

### Other Changes

P-01 Zibens (ex P 966 Djerv)
P-02 Lode (ex P 972 Hvass)
P-03 Linga (ex P 979 Gnist)
P-04 Bulta (ex P 973 Traust)

### Sources

Combat Fleets of the World, 16th Edition page 422
https://en.wikipedia.org/wiki/Latvian_patrol_boat_Linga_(P-03)

![image](https://user-images.githubusercontent.com/99632305/175129629-ea9d9c65-26e2-4cc2-9556-0a8e855ee009.png)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
