### ISSUE TITLE
Malta Marine Protector Class x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1428]
### DB Selector

DB3K

### DBID to Copy

2437

### Hypothetical

No

### Name

P 51

### Country

Malta

### Service

Navy

### In Commission

2002-

### Number in Service

2x

### Sensors

- 1x SPS-73 navigaion

### Mounts

- 2x single 12.7mm M2 mg

### Sources

Combat Fleets of the World, 16th Edition, pg 443
https://en.wikipedia.org/wiki/Maritime_Squadron_of_the_Armed_Forces_of_Malta#Current_fleet

![Malta_-_Gzira_-_Lazzaretto_Creek_(MSTHC)_02_ies](https://user-images.githubusercontent.com/99632305/175140416-720a04bf-ef1a-45f9-877b-1f1ab1326833.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
