### ISSUE TITLE
Malta ex-Emer-class OPV x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1429]
### DB Selector

DB3K

### DBID to Copy

2637 DB3K

### Hypothetical

No

### Name

P 62

### Country

Malta

### Service

Navy

### In Commission

2015-

### Number in Service

1

### Mounts

- remove Rh202 20mm cannons

### Sources

https://en.wikipedia.org/wiki/L%C3%89_Aoife_(P22)

![Malta_-mix-_2019_by-RaBoe_197](https://user-images.githubusercontent.com/99632305/175141900-e7f59331-afdb-44a6-b2cc-6601a8bfe4e2.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Also updated the OOS on the Irish Emer-class.
