### ISSUE TITLE
Type 055 Nanchang CG (Renhai Class), 2022, YJ-21/YJ-XX

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1432]
### DB Selector

DB3K

### DBID to Copy

Ship 2834

### Hypothetical

No

### Name

Type 055 Nanchang CG (Renhai Class), 2022, YJ-21/YJ-XX

### Country

China

### Service

Navy

### Mounts

YJ-21/YJ-XX added

### Other Changes

Platform to carry YJ-21/YJ-XX

### Sources

https://www.sinodefenceforum.com/t/055-ddg-large-destroyer-thread.6480/page-952

**Comment by LuigiP57** [comment]
Sorry for constantly changing, I'm not so familiar with this “issue” page yet.

**Comment by yehanactivated** [comment]
indeed YJ XX is an incredible new weapon, but I don't think we have enough credible and specific information to create one for CMO database (such as its range, warhead,guidance...there's no way but GUESS

**Comment by PygmalionOfCyprus** [comment]
Dependent on #1416

**Comment by PygmalionOfCyprus** [comment]
Added 495.
