### ISSUE TITLE
Mexico Halcon Class x6

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1433]
### DB Selector

DB3K

### Hypothetical

No

### Name

P 121 Virgilio Uribe

### Class

Halcon Class

### Country

Mexico

### Service

Navy

### In Commission

1982-

### Number in Service

6

### Length (m)

67

### Beam (m)

10.5

### Draft (m)

3.5

### Standard Displacement (t)

845

### Full Displacement (t)

988

### Complement

52

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 20V956 TB91

### Flank Speed (kt)

21

### Range (nm) at Speed (kt)

5000@18

### Sensors

- 1x Decca AC 1226 Nav
- 1x TACAN: SRN-15
- 1x E/O: Matra Defence Naja optronic gun F.C.
- 1x Optical fire director CSEE Model 74 NAJA

### Mounts

- 1x 40mm/70cal Bofors AA

### Aircraft & Docking Facilities

- 1x hangar/pad for 1x BO105CB Liason helicopter

### Comms/Datalinks

Standard

### Sources

https://en.wikipedia.org/wiki/Uribe-class_patrol_vessel
Combat Fleets of the World, 16th Edition page 450-51

![ARM_Bretón_(PO-124)](https://user-images.githubusercontent.com/99632305/175192722-570b2e62-204f-4dd3-b9ea-2b237bc49d6e.jpg)

**Comment by Parel803** [comment]
Name giver might be decom in 2013
https://www.navypedia.org/ships/mexico/mex_es_virgilio_uribe.htm
JFS 2015-2016 also mention 5 in class.

**Comment by Jkryos** [comment]
Added DB3k 505
