### ISSUE TITLE
YJ-21/YJ-XX Anti-ship ballistic missile's RV

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1434]
### DB Selector

DB3K

### Baseline

2106

### Hypothetical

No

### Name

YJ-21/YJ-XX ASBM (ship-based vertical launch) RV

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

1.0-800.0nm

### Warhead

800kg Penetrator (800 DP)

### Targets

Surface Vessel

### CEP (m)

2

### Sensors

1x Active Radar Seeker (~50nm Range), late 2010s techology
1x Passive Radar Seeker (~10nm Range), late 2010s technology

### Weapon Codes

Home On Jam (HOJ), Ballistic Missile or Rocket Booster, Weapon - INS w/ GNSS Navigation, Terminal Maneuver - Random (Advanced), Uses BeiDou/COMPASS, Level Cruise Flight

### Comments

1. Surface PoH/Reliability: 90%

### Sources

https://zh.wikipedia.org/wiki/%E9%B9%B0%E5%87%BB21%E5%8F%8D%E8%88%B0%E5%AF%BC%E5%BC%B9
https://en.wikipedia.org/wiki/Maneuverable_reentry_vehicle
https://www.navalnews.com/naval-news/2022/04/china-test-fires-new-yj-21-hypersonic-missile/
https://www.sinodefenceforum.com/t/plan-anti-ship-surface-missiles.6345/page-107
https://www.sinodefenceforum.com/t/055-ddg-large-destroyer-thread.6480/page-952

**Comment by LuigiP57** [comment]
[https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1416](url)

**Comment by LuigiP57** [comment]
#1416

**Comment by LuigiP57** [comment]
I forgot something. Maybe we need an Reentry Vehicle for YJ-21/YJ-XX since it's obviously a ballistic missile.

**Comment by LuigiP57** [comment]
I have edited the description of the #1416, hope it's not too late.

**Comment by PygmalionOfCyprus** [comment]
Already added it with #1416, I assumed it was implied. 😛
