### ISSUE TITLE
Add 2021 out of service date for Hatakaze destroyer

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1436]
### DB Selector

DB3K

### Affected DBID(s)

5

### Summary of Changes

Both Hatakaze converted to training ships by 2021,

### Sources

https://en.wikipedia.org/wiki/Hatakaze-class_destroyer
https://en.wikipedia.org/wiki/JS_Hatakaze_(DDG-171)

**Comment by PygmalionOfCyprus** [comment]
It's not technically "out-of-service" if it's a training ship, especially if she's still armed. We've got a fair few of those in the DB.

**Comment by bostonmyk** [comment]
gross

**Comment by bostonmyk** [comment]
Up to you really. The JMSDF seems to use a 4-digit hull number schema to mark training ships. Never really asked a Japanese Navy person what state these ships are really in. Seems if WW3 breaks out they can be regenerated quicker but not sure if its all dummy rounds etc.
Historically the db strategy was to add decommissioned dates to help players (who don't research much) not add weird stuff to scenarios they want to be realistic. Seen some things back in the day..hehe
