### ISSUE TITLE
#2812 - MPK Gremyashchy [Pr.20385, Improved Steregushchiy] (Russia [1992-] - 2022 Update) Otvet 91R1 ASW Missile UKSK launcher.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1437]
### DB Selector

DB3K

### Affected DBID(s)

#2812

### Summary of Changes

Update mount to accept 91RT ASW missile - could be left as a 0 weapon record for scenario designer to load out?

UKSK 3R14 universal VLS is capable of accepting 91RT ASW Missile - #3339 - SS-N-27 Sizzler [91RT Kalibr, Paket-NK]

MPK Gremyashchy fired the weapon in tests as per press release of 06.05.22 from UKSK 8 cell VLS. 

The missile itself uses the Russian Navy name Otvet (Response/Answer) so it could be renamed also. 
To follow #1465 - SS-N-16 Stallion ["RPK-7 Veter, UMGT-1 Torpedo] naming convention - 
#3339 - SS-N-27 Sizzler [91RT Otvet, Paket Nk Torpedo]

### Sources
https://seawaves.com/?p=18224
https://www.navalnews.com/naval-news/2020/12/russia-completes-trials-of-new-otvet-anti-submarine-missile/
https://topwar.ru/uploads/posts/2021-12/otvet-1.jpg - The missile demonstrated on land is compatible with the still from the video.
https://eng.mil.ru/en/news_page/country/more.htm?id=12420049@egNews
![OTVET ASW](https://user-images.githubusercontent.com/99494755/175312906-03a35b31-fbaa-4d42-8c51-6ff61f0f8404.JPG)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Do you know if the Otvet name applies to the 91RE1/E2 missiles, or are those Klub?

**Comment by KLABDB3K** [comment]
Otvet seems to apply to all the 91R ASW weapons. If its exported there could be a different name but I've not found evidence yet.
Thanks.
