### ISSUE TITLE
Mexico Valle (ex U.S. Auk Class) x17

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1438]
### DB Selector

DB3K

### DBID to Copy

2167 CWDB or 2166 CWDB

### Hypothetical

No

### Name

P 101 Leandro Valle

### Country

Mexico

### Service

Navy

### In Commission

1973-

### Number in Service

17, 10 by 2013

### Sensors

- 1x Kelvin Hughes 14/9 (I-band)

### Mounts

- 1x 76.2mm 50 cal U.S. Mk 22 DP
- 2x twin 40mm/60cal Mk1 Mod 2 Bofors AA
- some also with 2x single 20mm 70 cal Oerlikon Mk 10 AA (not noted which ones or how many)
- some also with 2x 12.7mm MG on quarterdeck (not noted which ones or how many-Jane's)

### Other Changes

- all ASW and minesweeping gear except winch removed, used as OPV's
- 3x (P103, P104 and P110) modified with helo platform aft (Bo105 capable), also fitted with a 9ton 12.2m Pirahna patrol craft (Built by Boston Whaler) capable of 26kts, crew of 5 and armed with 2x single 12.7mm mg and U.S. Mk19 40mm grenade launcher
- Noted there seem to be many navies that used these, maybe a generic entry would be useful as well

### Sources

https://en.wikipedia.org/wiki/Auk-class_minesweeper
Jane's 2003-04,
Combat Fleets of the World, 16th Edition, page 451

![download](https://user-images.githubusercontent.com/99632305/175333442-ea8ff7b6-055e-4446-8e03-317d559f232f.jpg)
![istockphoto-1151214741-170667a](https://user-images.githubusercontent.com/99632305/175333900-3903ed0b-7610-4cc6-862e-df03dc0dfbc9.jpg)

Pics with Helo pad and small patrol craft
![former-auk-class-minesweeper-in-mexican-navy-note-helicopter-pad-for-bo105](https://user-images.githubusercontent.com/99632305/175332686-d2f316fe-5c2d-4b8e-b7ef-5cf2c4fe45f7.jpg)
![former-auk-class-minesweeper-in-mexican-navy](https://user-images.githubusercontent.com/99632305/175332797-116405a1-6066-4936-8ae8-9ca63e74a5e6.jpg)
![Ep9rskyXAAAH5Pp](https://user-images.githubusercontent.com/99632305/175332844-761d2994-ab61-463c-b8a3-3fc279093d93.jpg)
![arm-valentin-gomez-farias](https://user-images.githubusercontent.com/99632305/175333141-121d7af0-e2b3-4a33-a0bf-b16acdc43d73.jpg)
![arm-valentin-gomez-farias](https://user-images.githubusercontent.com/99632305/175337695-0f2da18e-98a2-455f-a107-e841389a3444.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
