### ISSUE TITLE
Mexico Tenochtitlan (Damen Stan 4207) Class Patrol vessel x10 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1439]
### DB Selector

DB3K

### DBID to Copy

2962 DB3K

### Hypothetical

No

### Name

PC-331 Tenochtitlan

### Country

Mexico

### Service

Navy

### In Commission

2012-

### Number in Service

x10

### Sensors

- 1x JCR JMAS5310-6X BAND radar

### Mounts

- 2x 12.7mm MG

### Other Changes

- Stern launched RHIB

### Sources

https://en.wikipedia.org/wiki/Tenochtitlan-class_patrol_vessel
Combat Fleets of the World, 16th edition, pg 452

![300px-Patrulla_Costera_ARM_Teotihuacan](https://user-images.githubusercontent.com/99632305/175342146-4c29e529-6553-4774-8e0d-91b16a4f426b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
