### ISSUE TITLE
RCN - 509 Protecteur (Canada – 1990)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#144]
### DB Selector

DB3K

### Affected DBID(s)

722

### Summary of Changes

It seems as if this entry is meant to be the Gulf War build, if not I would request a new entry be added for the Gulf War build.

-Armament:
--- Add Twin 3”50 (76mm/50 Twin, same as St. Laurent) on bow (See pic in source 2) 
--- 2x Bofors 40mm guns fitted forward (See pic in source 2 and attached picture)
--- 6 x 0.5inch (12.7mm) machine guns
--- Blowpipe (most likely on hangar roof see pic in source 2)
--- Javelin MANPADS (most likely on hangar roof see pic in source 2)

### Sources

![image](https://user-images.githubusercontent.com/99632305/154199905-7483480e-70f7-408f-835a-efe6e64a3b65.png)

https://en.wikipedia.org/wiki/HMCS_Protecteur_(AOR_509) 
https://www.thecanadianencyclopedia.ca/en/article/persian-gulf-war-1990-91/

**Comment by Jkryos** [comment]
Added DB3K 494.
