### ISSUE TITLE
Mexico  Polaris II Class x14

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1443]
### DB Selector

DB3K

### Baseline

1763 DB3K

### Hypothetical

No

### Name

1401 Miaplacidus

### Class

Polaris II Class

### Country

Mexico

### Service

Navy

### In Commission

2005-

### Number in Service

14x

### Length (m)

16

### Beam (m)

3.4

### Draft (m)

0.9

### Standard Displacement (t)

19

### Full Displacement (t)

19

### Complement

4

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN

### Flank Speed (kt)

50

### Range (nm) at Speed (kt)

240@30

### Sensors

- 1x Decca Bridgemaster E Navigation

### Mounts

- 1x 12.7mm MG

### Comms/Datalinks

Standard

### Ship Codes

All Aluminum Construction

### Comments

Modified version of Acuario and Swedish 90H classes.

### Sources

Combat Fleets of the World, 16th Edition, pg 453

![images](https://user-images.githubusercontent.com/99632305/175369375-79a2c387-4dc2-4305-96b4-1ec57f7b528f.jpg)
https://images.pond5.com/mexican-navy-interceptor-boat-sails-footage-167193663_prevstill.jpeg
https://images.pond5.com/mexican-navy-interceptor-boat-sails-footage-167193653_prevstill.jpeg

**Comment by Jkryos** [comment]
Added DB3K pre-506.
