### ISSUE TITLE
ASI-315 Pacific Class Patrol Boat x22

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1445]
### DB Selector

DB3K

### DBID to Copy

2502

### Hypothetical

No

### Name

ASI-315 Pacific Class

### Country

Generic

### Service

Navy/Police

### In Commission

1987-

### Number in Service

22

### Sensors

- 1x Furuno 1011 surface search radar; I band

### Mounts

- May include Oerlikon 20 mm cannon, 7.62 mm machine guns, and/or 12.7 mm machine gun. Not all ships are permanently armed.

### Other Changes

Papua New Guinea - 4 ships
Fiji - 3
Federated States of Micronesia - 3
Tonga - 3
Solomon Islands - 2
Cook Islands - 1
Kiribati - 1
Marshall Islands - 1
Palau - 1
Samoa - 1
Tuvalu - 1
Vanuatu - 1

### Sources

Combat Fleets of the World, 16th Edition, pg 458 (Micronesia)
https://en.wikipedia.org/wiki/Pacific-class_patrol_boat

![220px-HMPNGS_Seedler](https://user-images.githubusercontent.com/99632305/175375841-d87e0a7c-3d6c-44b3-bd91-345a9debc372.jpg)
![220px-RSIPV_Lata](https://user-images.githubusercontent.com/99632305/175375857-1df8e098-313a-46f2-bb53-343baf13bf42.jpg)
![220px-RVS_Tukoro,_Vanuatu's_Police_Patrol_Boat](https://user-images.githubusercontent.com/99632305/175376487-e6f69052-cb86-4650-bcfe-de1e3c3c9582.jpg)
![220px-VOEA_Savea_(P203)_-_VAV-Patroulienboot_2](https://user-images.githubusercontent.com/99632305/175376498-81f9e9fd-0a75-4fc1-ae0c-7516f4657739.jpg)

**Comment by PygmalionOfCyprus** [comment]
Have added as individual units for a lot of these countries. Few of them won't get DB entries b/c they don't actually have militaries, just police forces. If I've missed any they'll get added on national reviews, but the entries currently in should be more than sufficient for any scenarios using them, esp. since they're fairly simple boats.

**Comment by cdnice55** [comment]
You are more energetic than I would be! I thought about making individual entries but did not want to burden you with so many for a pretty generic platform.

**Comment by PygmalionOfCyprus** [comment]
Don't give me credit I don't deserve, they were all already added during past reviews. 😛

By my count we have the custom Pacific-class boats for Papua New Guinea, Micronesia, Solomon Islands, Tonga, and Fiji. All the other countries just have police forces AFAIK.

I actually did a full national (continental?) review for all of Oceania a few DB versions ago, IIRC. So the little guys in that part of the Pacific should be covered. 👍
