### ISSUE TITLE
Struct Curve [MR-302 Rubka/ Fut-B] name correction

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1447]
### DB Selector

Both

### Affected DBID(s)

1555, 616 (CWDB)

### Summary of Changes

- change name to: Struct Curve [MR-302 Rubka]

The Fut-B is a seperate fire control radar for naval guns which is mounted above the bridge and also has a camera. It is in the DB as Hawk Screech [Yakor] which also requires a name change and camera to be added.

### Sources

numbers 6 and 8

https://i.imgur.com/fOegwRV.jpg

https://i.imgur.com/xw2ZaBq.png

https://www.radartutorial.eu/19.kartei/07.naval/karte092.en.html

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
