### ISSUE TITLE
Hawk Screech [Yakor] name correction and update

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1449]
### DB Selector

Both

### Affected DBID(s)

1540, 611

### Summary of Changes

- rename to: Hawk Screech [Fut-B] (GFCR, 45mm, 57mm, 76mm, 100mm)

- change range
vs air targets: 54nm
vs surface and land targets: 10nm

- add sensor:  Generic Gun Director [TV Camera] (1st Gen Anti-Air & Surface)

The Fut-B is a seperate fire control radar for naval guns which is mounted above the bridge and also has a camera. It is in the DB as Hawk Screech [Yakor] which requires a name change and camera to be added. It can receive data from the MR-302 radar.

### Sources

https://www.militaryperiscope.com/weapons/sensorselectronics/naval-radars/hawk-screech

https://i.imgur.com/DCj6yK2.png

http://foto-i-mir.ru/radar-artillery-foot-b/

> The Fut-B artillery control radar of the centimeter wave range made it possible to determine the range, direction (angular coordinates) and track air, surface and coastal targets to control the firing of 57-mm caliber universal artillery guns. The radar worked in sector mode according to data from the target designation radar. It automatically tracked air targets at speeds up to 300 m/s at ranges up to 100 km, and surface targets at ranges up to 18 km.

https://i.imgur.com/fOegwRV.jpg

https://i.imgur.com/xw2ZaBq.png

**Comment by PygmalionOfCyprus** [comment]
Fixed 495, mostly. I can't give a single sensor such wildly divergent ranges for air and ground without modelling it as two separate sensors (currently), so I think leaving it as-is is an acceptable sacrifice.

I have, however, converted all the Fut-B installations into sensor groups w/ an attached optical sensor and also configured the linked mounts accordingly. And of course renamed it.
