### ISSUE TITLE
RCN - 508 Provider (Canada – 1964)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#145]
### DB Selector

DB3K

### Affected DBID(s)

3018

### Summary of Changes

- Missing Corvus Chaff Group (Seduction/Distraction/Flare) as noted in CWDB 1972 unit (#235)
- Missing 1x LCVP and 1x 11m RHIB

### Sources

CWDB 1972 unit (#235)

**Comment by Jkryos** [comment]
Updated DB3K 494.
