### ISSUE TITLE
H-6K YJ-12 Loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1451]
### DB Selector

DB3K

### User(s)

H-6K Badger [God of War] (China - 2011) (Aircraft #1731)

### Weapons Carried

4x YJ-12

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

1500nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Image has proved this loadout. The image shows the aircraft belongs to the 10th Bomber Division in Anqing

### Sources

https://twitter.com/rupprechtdeino/status/1306986692558151681
https://www.scramble.nl/planning/orbats/china/china-air-force

**Comment by PygmalionOfCyprus** [comment]
Added 495.
