### ISSUE TITLE
F XX Nilgiri's Barak-8 Channel

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1452]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3564

### Summary of Changes

It only got 1 Barak-8 missle Datalink channel. It's definitely a serious Bug.
The number of channels should be higher than F 47, but lower than D 66. 16 Channels will be fine.

### Sources

https://www.iai.co.il/p/elm-2248-mf-star

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495. Ship mistakenly had the missile datalink instead of the command datalink.
