### ISSUE TITLE
Japan BQM-74E Chuker3 UAV

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1456]
### DB Selector

DB3K

### DBID to Copy

A/C ID 2691

### Hypothetical

No

### Name

BQM-74E Chuker3 UAV

### Country

Japan

### Service

Navy

### Sources

http://rightwing.sakura.ne.jp/equipment/jmsdf/other/chukar3/chukar3.html

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
