### ISSUE TITLE
Morocco ex Newport News LST x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1458]
### DB Selector

DB3K

### DBID to Copy

375

### Hypothetical

No

### Name

407 Sidi Mohammed Ben Abdallah

### Country

Morocco

### Service

Navy

### In Commission

1994-

### Number in Service

1x

### Sensors

- 1x Decca Navigation
- 1x SPS-64(V)9 Navigation
- 1x SPS 10F

### Mounts

- 1x 20mm mk15 Phalanx CIWS
- 4x single 12.7mm mg

### Sources

https://en.wikipedia.org/wiki/Newport-class_tank_landing_ship
Combat Fleets of the World, 16th Edition, pg 465

![140px-407_Sidi_Mohammed_Ben_Abdallah_(ex-Bristol_County,_LST_1198)](https://user-images.githubusercontent.com/99632305/175647696-6fbc9f2a-6e94-444c-8826-c59e6d34ca22.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
