### ISSUE TITLE
New Zealand Anzac Class 2020 x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1459]
### DB Selector

DB3K

### Affected DBID(s)

2645 DB3K

### Summary of Changes

1. Link 16/DLPS
2. Kelvin Hughes Sharp Eye 2D
3. Thales Smart-S 3D
4. Elbit/Elisra ESM
5. Furuno FAR-3320W x2
6. Sagem VAMPIR IRST
7. Mk45 Mod 4 gun
8. Phalanx CIWS Block 1B Baseline 2
9. Sea Sentor Surface Ship Torpedo Defence system
10. MASS x2
11. Spherion B hull mounted sonar (upgrade) BSAPS
12. SAAB Grintek LWS
13. Toplite
14. Mk46 Mod 5 Torpedo

### Sources

https://www.nzdf.mil.nz/nzdf/our-equipment/ships-and-watercraft/hmnzs-te-mana/ (Mk46 Mod 5 Torp noted)
https://www.navalnews.com/naval-news/2019/02/new-zealands-second-anzac-class-frigate-underway-for-mid-life-upgrade-in-canada/
https://www.navalnews.com/naval-news/2022/06/new-zealand-frigate-sails-home-following-upgrade/
https://www.navalnews.com/naval-news/2020/09/royal-new-zealand-navys-te-kaha-frigate-starts-post-upgrade-sea-trials/

![Anzac Upgrade](https://user-images.githubusercontent.com/99632305/175661681-7531e27f-5836-4386-80cc-c12348f15fa8.jpg)

![anzac-poster jpg pc-adaptive 480 high](https://user-images.githubusercontent.com/99632305/175660797-c99f5ebc-dfcb-4beb-9ba5-82b7a5dbc483.jpg)

![images](https://user-images.githubusercontent.com/99632305/175660814-79fdda9c-a3c3-40e5-8c1c-1bc3cff0c6fa.jpg)

![image](https://user-images.githubusercontent.com/99632305/175660750-16280769-c537-4c23-afbc-bd2512d893b5.png)

**Comment by PygmalionOfCyprus** [comment]
Already implemented as part of an internal news roundup, but good catch on the Mk46 Mod 5 -- we missed that. Will ship correct in 495.
