### ISSUE TITLE
RCN - 700 Kingston Class 1996/1999

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#146]
### DB Selector

DB3K

### Affected DBID(s)

1534, 2678

### Summary of Changes

Should have basic minesweeping capabilities due to ISO container system 
o	Mine warfare capability is provided by three alternate modular payloads. These are: a deep mechanical   minesweeping system (MMS), similar to the UK Royal Navy Explosive Deep Armed Team Sweep; a route survey package (RSP), based on a Bendix AQS-17(V) towed sonar; and a mine inspection package (MIP), using a SUTEC Double Eagle unmanned underwater vehicle. (Forecast International Link below)
-Sensors
--- 1x CA/SQS-511 Towfish VDS, Active-Only Mine Hunting 
-Mounts 
--- #4657 - Generic Mechanical Cable Cutter Mine Sweep 
--- #4654 - Generic Magnetic & Acoustic Mine Sweep
--- #4681 - Generic Mine Disposal Diver 

Other:
- Add 1x Davit (very small dock/davit) with 7m RHIB (pics below)

### Sources

https://www.forecastinternational.com/archive/disp_old_pdf.cfm?ARC_ID=1749 
https://en.wikipedia.org/wiki/Kingston-class_coastal_defence_vessel#Modular_payload 
https://www.naval-technology.com/projects/kingston/
http://jgmjgm516.blogspot.com/2014/04/a-future-for-royal-canadian-navy-may-be.html 

![kingston-vessel](https://user-images.githubusercontent.com/99632305/156263339-fd695bd8-bc1b-4724-b0cc-7883fa739a96.jpg)
![canadian-kingston-class-coastal-defence-vessel-with-RHIB](https://user-images.githubusercontent.com/99632305/156263462-498b15e2-be89-4d0c-8362-9f7ed84e4e67.jpg)
![king4](https://user-images.githubusercontent.com/99632305/156263522-f415ca6b-920e-4fc2-96ee-d97cd4cf3b1e.jpg)
![HMCS-Glace-Bay-701-seen-form-HMCS-Shawinigan-704-both-Kingston-class-during](https://user-images.githubusercontent.com/99632305/156263636-d3462d75-c2c8-40ef-aa5e-9c6954d7da4d.jpg)

**Comment by Jkryos** [comment]
Updated DB3K 497.
