### ISSUE TITLE
SQ-3D/SF sonar

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1460]
### DB Selector

Both

### Affected DBID(s)

4525

### Summary of Changes

high frequency
frequency: 24kHz
typical detection range of a submarine when at 0kts: 1800m (1 nautical mile)

### Sources

https://i.imgur.com/nEJ4zU5.png
https://archive.org/details/navalinstitutegu0000unse_j3x1/page/758/mode/2up?q=wire-guided

https://www.paluba.info/smf/index.php?topic=598.msg37360;topicseen#msg37360

> I found that "Mirna" used Norwegian sonar Simrad SQS-5Q3D / SF (developed from commercial sonar). It could be used to detect submarines at a distance of up to 1800 m, but the ship had to rest because the noise in the ride was too much of a nuisance. According to this, if they were on a ride they probably couldn’t even hear her.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
