### ISSUE TITLE
Canada AOR 520 Protecteur 2023

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1463]
### DB Selector

DB3K

### Affected DBID(s)

3645

### Summary of Changes

1. Combat System Should be CS Gen 6 as this will be a new ship, not a modernized one.

### Sources

https://en.wikipedia.org/wiki/Protecteur-class_auxiliary_vessel
https://www.naval-technology.com/projects/protecteur-class-joint-support-ships-jss-canada/
https://www.canada.ca/en/navy/corporate/fleet-units/surface/joint-support-ships.html
https://www.canada.ca/content/dam/rcn-mrc/migration/assets/navy_internet/docs/en/jss_factsheet_8x11_eng.pdf

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
