### ISSUE TITLE
Russia Buk M3 Name Correction- Should be SA-27

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1465]
### DB Selector

DB3K

### Affected DBID(s)

2276

### Summary of Changes

Sorry this will make a mess of your naming, but the DOD/Nato system designation for Buk M3 is SA-27.
The radar is not Chair Back either, it got a new name, which I am trying to locate on a source you can use, as most sources state that is has a completely enhanced antenna and tracking parameters to enable it to support the more advanced 9K317M missiles.

### Sources

SA-27 reference

- https://odin.tradoc.army.mil/WEG/Asset/9K317M_Buk-M3_(SA-27)_Russian_Medium-Range_Air_Defense_Missile_System

**Comment by HVAA** [comment]
![image](https://user-images.githubusercontent.com/106485930/175774230-fa2b76bd-0681-42ea-8270-23aad44a9e20.png)
'Not Chair Back' - two arrays, one small, one standard
![image](https://user-images.githubusercontent.com/106485930/175774335-d337fa05-7000-4883-95cb-eb6b66b53702.png)
Chair Back - single array

**Comment by KLABDB3K** [comment]
https://www.armyrecognition.com/november_2019_global_defense_security_army_news_industry/images/stories/north_america/united_states/Equipment_identification_card_Russia_from_US_Army.pdf
From 2019 December

**Comment by HVAA** [comment]
404 on your link and so I dont know if it supported my name or the DB name?  Given that the source I found is an army.mil site, I would have hoped it would stand scrutiny

**Comment by HVAA** [comment]
Finally found it after some serious digging.  SA-X-27, which has now lost the X.
Prefer my source given that the Ace of Spades clearly shows missiles with long wings and a radar with a cassegrain antenna....

**Comment by PygmalionOfCyprus** [comment]
Name changed for the facility and all linked components. Closing the ticket, but chime in whenever when/if you find the new radar name.

I propose "Chair Headrest" for the little one on top.

**Comment by HVAA** [comment]
Thanks.  As soon as I see the name in something I can quote here I will do so.
