### ISSUE TITLE
Chinese OTH-SW radar has OTH-B range instead

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1467]
### DB Selector

DB3K

### Affected DBID(s)

5050

### Summary of Changes

China OTH SW sensor has wrong range. It currently has 1600nm, same as the OTH-B radars with sky bounce. However it is a surface Wave radar, so its range is much more limited. It should be 200nm, same as 5956

### Sources

Internal DB consistency
Also 
https://www.globalsecurity.org/wmd/world/china/oth-swr.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
