### ISSUE TITLE
RCN - HMCS Harry DeWolf -2018

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#147]
### DB Selector

DB3K

### Affected DBID(s)

2797

### Summary of Changes

- designation is Artic Offshore Patrol Vessel (AOPV)
- ship is Royal Canadian Navy, not Coast Guard. Coast guard will get 2 unarmed versions, feel free to add them as well! :-)

### Sources

http://www.navy-marine.forces.gc.ca/en/fleet-units/aops-home.page 
https://en.wikipedia.org/wiki/Harry_DeWolf-class_offshore_patrol_vessel 
https://www.naval-technology.com/projects/harry-dewolf-class-arcticoffshore-patrol-ships-aops/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493. Also added unarmed CG variant.
