### ISSUE TITLE
Romania - A-921 radio command guided missile

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1472]
### DB Selector

DB3K

### DBID to Copy

218

### Hypothetical

No

### Name

A-921 [Kh-23]  -- 1992

### Country

Romania

### Service

Air Force

### In Commission

1992

### Other Changes

This missile has a 111kg HEAT/FRAG warhead and requires the Delta NG datalink pod to be carried by the launch aircraft.
Name: A-921 Command Datalink, Type: A-921 Weapon Link, Send-only

Range: 1-5.5 NM

### Sources

https://rumaniamilitary.wordpress.com/2011/11/28/racheta-aer-sol-a-921/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
