### ISSUE TITLE
Meteor Missile Range

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1473]
### DB Selector

DB3K

### Affected DBID(s)

961 / 371

### Summary of Changes

The Meteor / RB107 missile range seems to be currently estimated on the harsher side, but this is understandable considering the variation of sources. However, it is widely believed to be longer than the AIM-120D. It would possibly be more sensible to extend the range to somewhere between 150-200km as opposed to the current range (circa 139 km)

"The Meteor has a combat range of 200 km (124 miles)..."

"The weapon has a range of over 150 kilometers (90 miles)"

"You can find range estimates for the AIM-120D from about 40 miles to nearly 100 miles. Info on the Meteor is just as inconsistent, with range claims form from around 60 to 130 miles."

The CMO DB494 Meteor missile's dimensions appear to be consistent with the MBDA website, but the RB107 has slightly different values; albeit this is a very minor issue.

### Sources

https://www.defensenews.com/global/europe/2021/08/02/german-air-force-declares-meteor-missile-ready-for-eurofighter-fleet/

https://www.aerotime.aero/articles/29984-spain-eurofighter-mbda-meteor-missile

https://www.thedrive.com/the-war-zone/4678/is-the-european-meteor-air-to-air-missile-really-the-best-in-the-world

https://www.mbda-systems.com/product/meteor/

**Comment by PygmalionOfCyprus** [comment]
Very fair. I've given the Meteors a range of 100nm, which is undershooting in the vicinity of some ~8-10nm but still outshoots the AIM-120D (at least based on what we know) by about 15nm.

Also, re: the dimensions, I assume you were referring to the weight discrepancy. That's fixed too, so both versions now weight 190kg.

**Comment by TempestII** [comment]
All sounds good and makes sense, thanks!
