### ISSUE TITLE
A-12A Avenger to take advantage of new weapons and possibly sensors (AARGM-ER, JATM, Superfrags etc)

### ISSUE THREAD

**Issue by ER5013** [PygmalionOfCyprus/cmo-db-requests#1486]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4177 (A-12A Avenger II, United States (Navy), 2020)

### Hypothetical

Yes

### Name

A-12A Avenger II, United States (Navy), 2022 or 2023

### Country

United States

### Service

Navy

### Sensors

AN/APQ-183 to receive AESA upgrade (Optional)

### Loadout Options

-HAWC (2 or 4x)
-4x GBU-136 SuperFrags 
-8x GBU-134 Superfrag
-GBU-56 LJDAMs (4x)
-AGM-179 JAGM
-JSOW-ER (4x)
-AIM-260 JATM (10x, Misileer)

### Other Changes

After seeing the completed requests for the F-24 and F-14 Hypothetical variants, I decided to throw in a request for the A-12A Avenger to have updated weapons. I looked at the weapons plotted for future use by the F-35C and F/A-18E/F and tried to approximate loadouts for the A-12A. I would also like the loadouts for the light internal and light internal + external fuel to be added. I may have missed a  few weapons, but I think that's everything.

The request mainly focuses on sensors but I don't think anything needs to be changed except maybe for the APQ-183 to receive an AESA upgrade but I'm not sure if that's necessary.

### Sources

DB3K v494 Comparisons with F-35C and F/A-18E/F Super Hornets.

**Comment by KushanGaming** [comment]
Done for DB497.
