### ISSUE TITLE
Missing Tu-4 bomb loadouts

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1489]
### DB Selector

CWDB

### User(s)

Tu-4 (Aircraft_401)

### Weapons Carried

- 48x FAB-100M-62 GPB
-
- 48x FAB-250M-46 GPB
-
- 4x FAB-3000M-46 GPB

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

For FAB-100: 2,754 nm For FAB-250: 2,214 nm For FAB-3000M-46: 1,404 nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

The Tu-4 is missing some of its conventional bomb loadouts.

### Sources

**Tupolev Tu-4: The First Soviet Strategic Bomber** by **Yefim Gordon**, **Dmitry Komissarov**, and **Vladimir Rigmant**, pages 76 (for range info) and 161 (for bomb loadouts)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
