### ISSUE TITLE
RCN - DDE 257 Restigouche - 1983/84, DELEX

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#149]
### DB Selector

DB3K

### Affected DBID(s)

871, 1464

### Summary of Changes

-	CA/SQS-505(V)1 - (Limbo Director) Hull Sonar, Active/Passive appears on 1984 unit but not on 1983 unit
-	CA/ALR-502 [AN/ALR-47] - (AN/SLQ-26) ESM appears on 1983 unit but not on 1984 unit

### Sources

http://cmano-db.com/ship/1464/ 
http://cmano-db.com/ship/871/ 
http://www.hazegray.org/navhist/canada/postwar/restigou/ 
https://en.wikipedia.org/wiki/Restigouche-class_destroyer

**Comment by Jkryos** [comment]
Updated DB3K 494.
