### ISSUE TITLE
Add RN-42 nuclear bomb loadout for Tu-95M

### ISSUE THREAD

**Issue by SunlitZelkova** [PygmalionOfCyprus/cmo-db-requests#1493]
### DB Selector

CWDB

### User(s)

Tu-95M (Aircraft_200)

### Weapons Carried

- 1x RN-42 Strategic Bomb [200kT Nuclear]

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

7020

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

The Tu-95 is missing its primary nuclear bomb loadouts. It was capable of carrying the RP-30/32 nuclear bomb with a 200 kiloton yield. I have simply used the RN-42 bomb as it has the same performance. This was one of the Tu-95's premier weapon loadouts during the late 1950s and early 1960s, and is thus a major loadout missing from the DB.

### Sources

The Kremlin's Nuclear Sword: The Rise and Fall of Russia's Strategic Nuclear Forces, 1945-2000 by Steven J. Zaloga, page 30

**Comment by PygmalionOfCyprus** [comment]
Handled 503. Went ahead and added the RP-30/32 as a copy of the RN-42.
