### ISSUE TITLE
Oscar III post modernisation update and missile load amendment. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1496]
### DB Selector

DB3K

### Affected DBID(s)

Oscar III 2018 mod will update with DB ID in due course. 

### Summary of Changes

 The Oscar's III rebuilds are still undergoing trials following modernisation so in-service of 2018 is optimistic, change to 2021 and more importantly the missile load for the Kalibr, Onyx is 48 not 72.  2 for 1 in the Granit tubes is dimensionally much more likely, the Granit is a big missile but not a wide as three Kalibr tubes etc. 

### Sources

https://rg.ru/2022/06/24/reg-dfo/apl-irkutsk-s-novym-oruzhiem-vyshla-na-ispytaniia.html

The 48 load was referenced a while ago on RG and I requested it on the old forum.
Given the propensity for "optimistic" reporting from some sources 48 tubes seems very likely. Looking at diameters of the Shipwreck/Granit versus the Kalibr, Onyx, Zircon there would be significant design challenges to get 3 tubes in the space of one Granit where as a 2 for 1 seems do able with modern design materials etc.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
