### ISSUE TITLE
Add Ethiopian SU-25 TK

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1497]
### DB Selector

DB3K

### DBID to Copy

2513

### Hypothetical

No

### Name

SU-25 TK Frogfoot

### Country

Ethiopia

### Service

Air Force

### In Commission

2000

### Number in Service

4 -1

### Loadout Options

No AT-16 [Vikhr] ever in pictures so not likely delivered.

### Sources

https://www.oryxspioenkop.com/2021/08/tankovy-busters-russian-su-25tk-attack.html
http://www.airvectors.net/avsu25.html#m5

**Comment by Jkryos** [comment]
Added DB3K 496.
