### ISSUE TITLE
Add Ethiopian SU-27 SK

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1498]
### DB Selector

DB3K

### DBID to Copy

355

### Hypothetical

No

### Name

SU-27SK Flanker

### Country

Ethiopia

### Service

Airforce 

### In Commission

1999

### Number in Service

x4, +4

### Other Changes

Bought in 2 groups

4 in 98-99, 4 more in 2002, lost one in 1999

### Sources

https://en.wikipedia.org/wiki/Sukhoi_Su-27#:~:text=The%20Su%2D27%20has%20replaced,over%20the%20skies%20of%20Mekelle.
https://twitter.com/gerjon_/status/1409448673625452546?lang=en
https://www.oryxspioenkop.com/2021/11/su-27-fighters-deployed-as-bombers-in.html
http://www.sukhoi.mariwoj.pl/su-30-et.htm
https://www.reddit.com/r/MilitaryPorn/comments/5ivw19/su27_of_the_ethiopian_air_force_1600_x_1078/
https://www.rbth.com/history/334639-how-flankers-fought-fulcrums
https://m.facebook.com/destakeremeladc/photos/ethiopian-female-su-27-pilot-capt-aster-tolossa-the-first-female-pilot-in-the-wo/508869179143289/
http://aces.safarikovi.org/victories/ethiopia-1999-2000.html

**Comment by Jkryos** [comment]
Added DB3K 496.
