### ISSUE TITLE
ADD Swedish LVS-103[Patriot PAC-3 MSE]SAM x4 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#15]
### DB Selector

DB3K

### Hypothetical

- [ ] Yes

### Name

ADD Swedish LVS-103[Patriot PAC-3 MSE]SAM 

### Facility Type

SAM

### Country

Sweden

### Service

Army

### In Commission

2022

### Sensors

AN/MPQ-65

### Mounts

3 MIM-901 each with MIM-104F Missiles

### Magazines

Patriot Magazine

### Comments

Configuration similar to export variants. Copy existing PAC-3 MSE. Replace MANPAD with something Swedish.

### Sources

https://www.dsca.mil/press-media/major-arms-sales/sweden-patriot-configuration-3-modernized-fire-units
https://www.youtube.com/watch?v=1NoXkZwWEis&t=3s
https://www.armyrecognition.com/defense_news_november_2021_global_security_army_industry/sweden_officially_introduces_us_patriot_pac-3_mse_air_defense_missile_system_into_service.html
https://www.dsca.mil/press-media/major-arms-sales/sweden-patriot-configuration-3-modernized-fire-units
https://www.army-technology.com/news/sweden-acquires-patriot-defence-missile-system/

**Comment by PygmalionOfCyprus** [comment]
Added 493. I've built it out in pretty much the same way as the USA ver. (DBID 2506) since it looks like they picked up both the GEM and MSE missiles; that said, I did swap out the MSE launchers for their 12-round versions (as shown in the pictures) and the Stingers for RBS 70 Mk2s.
