### ISSUE TITLE
RCN - DDH 280 Iroquois [Tribal Class] - 1984

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#150]
### DB Selector

DB3K

### Affected DBID(s)

202

### Summary of Changes

- unit is missing AN/WLR-1F - (AN/SLQ-26) ESM that appears on prior 1976 unit
- 1984 unit is missing CA/UPD-501 ESM - (1952-1998) ESM that appears on prior unit

### Sources

http://www.hazegray.org/navhist/canada/postwar/tribal/ 
https://en.wikipedia.org/wiki/Iroquois-class_destroyer

**Comment by PygmalionOfCyprus** [comment]
Looks like the AN/WLR-1F was replaced by the CA/SLQ-501; I've added the CA/UPD-501 through 1999.
