### ISSUE TITLE
Add Ethiopian Bayraktar TB-2

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1500]
### DB Selector

DB3K

### DBID to Copy

5398

### Hypothetical

No

### Name

Bayraktar TB2 UCAV

### Country

Ethiopia

### Service

Air Force

### In Commission

2022

### Sources

https://twitter.com/JosephHDempsey/status/1541020724449648640
https://twitter.com/mahmouedgamal44/status/1540789251503050752

**Comment by tbrandon517** [comment]
Additional Source Article

https://www.oryxspioenkop.com/2021/10/from-mohajer-6s-to-wing-loong-is.html

**Comment by Jkryos** [comment]
Added DB3K 496.
