### ISSUE TITLE
Add Ethiopian SA-2 [S-75 Dvina]

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1502]
### DB Selector

DB3K

### DBID to Copy

1773

### Hypothetical

No

### Name

Sam Bn (SA-2b Guideline [S-75 Dvina]) 

### Country

Ethiopia

### Service

Airforce 

### In Commission

1978

### Number in Service

4

### Sources

https://twitter.com/islamicworldupd/status/1438819305873936384
https://twitter.com/TheIntelLab/status/1326531558652702720
https://twitter.com/oryxspioenkop/status/1431947682818502656?lang=en
https://twitter.com/MapEthiopia/status/1435607803427688453
https://www.cia.gov/readingroom/docs/CIA-RDP81T00034R000100580001-3.pdf
Sipri Lines
(4)	S-75 Dvina	SAM system	(1976)	1977-1978	(4)	Probably second-hand
(100)	V-750	SAM	(1976)	1977-1978	(100)	Possibly second-hand

**Comment by PavelNovak79** [comment]
SA-2 in Ethiopia has to be second hand. There was no export of SA-2 from the USSR.

**Comment by tbrandon517** [comment]
Additional Source

https://www.oryxspioenkop.com/2021/09/tigray-defence-forces-display-surface.html

**Comment by Jkryos** [comment]
Added DB3K 496.
