### ISSUE TITLE
Add Ethiopian Strela SA-7

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1504]
### DB Selector

DB3K

### DBID to Copy

2763

### Hypothetical

No

### Name

SAM Sec (SA-7b Grail [9k32M Strela-2M] MANPADS x3)

### Country

Ethiopia 

### Service

Army

### In Commission

1978

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP81T00034R000100580001-3.pdf

Sipri Lines
(1500)	Strela-2	portable SAM	1977	1977-1982	(1500)

**Comment by Jkryos** [comment]
Added DB3K 496.
