### ISSUE TITLE
Add Ethiopian Shilka

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1505]
### DB Selector

DB3K

### DBID to Copy

1833

### Hypothetical

No

### Name

AAA Plt/2 (23mm ZSU-23-4 Shilka x 2)

### Country

Ethiopia

### Service

Army

### In Commission

1978

### Sources

https://en.wikipedia.org/wiki/ZSU-23-4_Shilka
https://www.oryxspioenkop.com/2021/09/list-of-aircraft-losses-of-tigray-war.html
https://www.istockphoto.com/photo/damaged-tank-at-the-border-of-somalia-and-ethiopia-gm157440950-9069736
https://odin.tradoc.army.mil/mediawiki/index.php?title=ZSU-23-4_Shilka_Russian_23mm_Self-Propelled_Anti-Aircraft_Weapon_System&printable=yes

Sipri Lines
(60)	ZSU-23-4 Shilka	SPAAG	(1977)	1978-1982	(60)

**Comment by Jkryos** [comment]
Added DB3K 496.
