### ISSUE TITLE
Add Ethiopian MI-25 Hind

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1507]
### DB Selector

DB3K

### DBID to Copy

1381

### Hypothetical

No

### Name

Mi-25 Hind D

### Country

Ethiopia

### Service

Air Force

### In Commission

1980

### Sources

https://books.google.com/books?id=tlW1CwAAQBAJ&pg=PA31&lpg=PA31&dq=Ethiopia,+Mi-25&source=bl&ots=l7vlVPN05L&sig=ACfU3U1xrJeOdJUTok4YqmGlo7pJ3bG_1g&hl=en&sa=X&ved=2ahUKEwjTq6PZ4M74AhV6hYkEHeC_CcEQ6AF6BAgoEAM#v=onepage&q=Ethiopia%2C%20Mi-25&f=false
https://military-history.fandom.com/wiki/Ethiopian_Air_Force
https://www.globalsecurity.org/military/world/ethiopia/air-force-equipment.htm
Sipri Line
(30)	Mi-24D/Mi-25	combat helicopter	1980	1980-1982	(30)	No. could be up to 36

**Comment by Jkryos** [comment]
Added DB3K 496.
