### ISSUE TITLE
RCN - DDH 280 Iroquois [Tribal Class] - 1991, Gulf War Mod, HMCS Athabaskan

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#151]
### DB Selector

DB3K

### Affected DBID(s)

1953

### Summary of Changes

- Missing 20mm/85 Mk15 Phalanx Blk 1 Burst [300 rnds] – Gun (weapon #1630)
- Missing Blowpipe - (1976, MANPADS) Guided Weapon (weapon #841)

### Sources

http://www.cntha.ca/articles/trump.html 
http://www.hazegray.org/navhist/canada/current/iroquois/

**Comment by PygmalionOfCyprus** [comment]
Added 494.
