### ISSUE TITLE
Japan UH-2 correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1512]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5290

### Summary of Changes

SUBARU/BELL 412EPX is the commercial name of UH-2

Length: 17.1m
Wingspan:14.0m

Empty Weight: 3091kg
Max Gross Weight: 5897kg
payload capacity:2443kg

Max Speed: 140kts
Cruise Speed: 123kts

Max Range:361@3.8hrs

Fuel: 331US gal = approx. 1000kg

Loadout: 
13x Troops/ Passengers
Cargo, 2 ton

Comment Section
"SUBARU Bell 412 EPX" (it might can help people to search)

Copy data to
SUBARU Bell 412 EPX (Coast Guard, 2025)

### Sources

https://aerospace.subaru.co.jp/412epx/en/spec.html

**Comment by PygmalionOfCyprus** [comment]
Fixed/added 495.
