### ISSUE TITLE
RCAF CT-142 Dash 8-100 "Gonzo" x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1513]
### DB Selector

DB3K

### Baseline

1521 db3k

### Hypothetical

No

### Name

CT-142 Dash 8 "Gonzo"

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1987-

### Number in Service

4x

### Length (m)

23.63

### Wingspan (m)

25.89

### Height (m)

7.44

### Empty Weight (kg)

10024

### Maximum Takeoff Weight (MTOW) (kg)

15650

### Payload Weight (kg)

4200

### Crew

2+ 2 trainers +4 students

### Propulsion

2x P&W 120A Turboprop

### Rate of Climb (ft/min)

1340

### Service Ceiling (ft)

25000

### Military/Afterburner Speed (kt)

295

### Cruise Speed (kt)

270

### Supercruise

No

### Ferry Range (nm)

1300

### Takeoff / Landing Distance (m)

451-900m TOD/LAD

### Fuel Capacity (kg)

2530

### Sensors

- 1x Litton Maritime search/navigation radar

### Mounts

None

### Loadout Options

None

### Comms/Datalinks

Standard

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Navigation training aircraft

### Sources

https://defence.frontline.online/article/2011/3/1896-1-Canadian-Forces-Flying-Training-School
https://planeman.tripod.com/CT142.html
https://www.ottosenphotography.com/blog/2015/3/de-havilland-canada-ct-142-dash-8-gonzo
http://www.airvectors.net/avdash7.html

![Gonzo](https://user-images.githubusercontent.com/99632305/176215009-9d1f6527-4cf1-4fd4-8469-8bc25d4cea49.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
