### ISSUE TITLE
Japan KC-130H Copy

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1514]
### DB Selector

DB3K

### DBID to Copy

2975

### Hypothetical

No

### Name

KC-130H

### Country

Japan

### Service

Air Force

### In Commission

2010

### Number in Service

limited

### Sensors

Same

### Mounts

None

### Loadout Options

Cargo/Troops loadout from C-130H Aircraft ID 3388
+
Tanker Mission loadout

### Other Changes

Converted from existing C-130H.
This is for UH-60J in SAR mission

I believe we can add Cargo/Troops Mission loadout for all existing KC-130Hs. I cannot see the reason KC-130J can do both but not with KC-130H.

### Sources

https://www.mod.go.jp/asdf/asc/equipment/kc/KC-130H/index.html

**Comment by Jkryos** [comment]
Added DB3K 498.
