### ISSUE TITLE
Japan UH-60J Blachhawk correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1515]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4313

### Summary of Changes

add SAR mission loadout
Maybe it is better to consider deleting other loadouts because Japan Air Force use UH-60J in (C)SAR mission only.

### Sources

https://www.mod.go.jp/asdf/equipment/kyuunanki/UH-60J/index.html

**Comment by PygmalionOfCyprus** [comment]
Fixed 495.
