### ISSUE TITLE
Japan, UH-60J(SP) Blackhawk, 2009

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1516]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4313

### Hypothetical

No

### Name

UH-60J(SP) Blackhawk

### Country

Japan

### Service

Air Force

### In Commission

2009

### Number in Service

5x

### Sensors

1x AN/AAR-54(Sensor ID 2236)
1x AN/AAQ-15 [FLIR] (replace Generic FLIR, unkown details, perhaps better to copy AN/AAQ-14[FLIR] (Sensor ID1253))

### Mounts

1x ALE-47 CMDS x4 [120 cartridges]
2x 5.56 MG

### Loadout Options

SAR loadout only

### Other Changes

SP stands for Self Protection

Air to Air Refueling capable
(there is 2005 variant with same equipment but No AAR capability, not sure needs in the game)

Related to
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1515

### Sources

AAR-54
https://www.njss.info/offers/view/16676054/

AN/AAQ-15 
https://www.njss.info/offers/view/1888304/

**Comment by Jkryos** [comment]
Added DB3K 498.
