### ISSUE TITLE
Japan, UH-60J II Blackhawk, 2015

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1517]
### DB Selector

DB3K

### DBID to Copy

UH-60J II Blachhawk

### Hypothetical

No

### Name

UH-60J II Blackhawk

### Country

Japan

### Service

Air Force

### In Commission

2015-

### Sensors

2x AN/AAR-60(V)2 (Front and Back)
1x J/APR-7 (RWR Early 2000s tech)
1x Talon MMS [FLIR] (2000 tech FLIR)

### Mounts

1x ALE-47 CMDS x4 [120 cartridges]
2x 5.56 MG

### Loadout Options

SAR loadout only

### Other Changes

Air to Air Refueling capable

Engine
2x T700-IHI-701D

IR signiture reduced by Hover Infrared Suppressor Subsystem

Related to
#1515
and 
#1516 

### Sources

AAR-60 and J/APR-7
https://commons.wikimedia.org/wiki/File:JASDF_UH-60J%2858-4598%29_AN_AAR-60%28V%29_and_J_APR-7_at_Komaki_Air_Base_March_13,2016.JPG

https://ja.m.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:JASDF_UH-60J%2858-4598%29_AN_AAR-60%28V%29_at_Komaki_Air_Base_March_13,2016.JPG

Talon MMS
https://www.infrared.ro/docs/Talon-MMS-Datasheet-US.pdf
https://commons.wikimedia.org/wiki/File:JASDF_UH-60J(78-4604)_Talon_FLIR_left_front_view_at_Komatsu_Air_Base_September_17,_2018.jpg

Other
http://kwat01.web.fc2.com/list/jasdf/uh-60ja.htm
https://ja.wikipedia.org/wiki/UH-60J_(%E8%88%AA%E7%A9%BA%E6%A9%9F)

Used wiki and blog level sources but confirmed by pictures and supply log of MoD.

**Comment by Jkryos** [comment]
Added DB3K 498.
