### ISSUE TITLE
RCN - DDH 280 Iroquois TRUMP [Tribal Class] – 1992

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#152]
### DB Selector

DB3K

### Affected DBID(s)

723

### Summary of Changes

-	Missing SLQ-503 Jammer (Sensor #3943 CA/SLQ-503 RAMSES [ECM] (Scimitar))
-	Torpedos were not removed as part of TRUMP please add back 6 × 12.75 in (324 mm) tubes firing Mark 46 Mod 5 torpedoes

### Sources

http://www.cntha.ca/articles/trump.html 
http://www.hazegray.org/navhist/canada/current/iroquois/

**Comment by PygmalionOfCyprus** [comment]
Added SLQ-503 to all TRUMP Tribals. Not sure what you mean re: the TTs -- they appear to still be on the ships? Not removed in my version of the DB.
