### ISSUE TITLE
GMLRS ER Unitary

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1521]
### DB Selector

DB3K

### Baseline

2699

### Hypothetical

No

### Name

GMLR ER unitary

### Length (m)

3.9

### Width/Span (m)

0.23

### Diameter (m)

0.23

### Weight (kg)

300

### Range (nm)

15-80

### Warhead

#751 90kg HE

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Radar, Mobile Target - Soft, Mobile Target - Hardened

### Sensors

None

### Weapon Codes

Ballistic Missile or Rocket Booster, Weapon - INS w/ GNSS Navigation, Uses GPS

### Sources

https://www.lockheedmartin.com/en-us/products/guided-mlrs-unitary-rocket.html
https://www.dsca.mil/press-media/major-arms-sales/finland-extended-range-guided-multiple-launch-rocket-system

On warhead:
https://u0v052dm9wl3gxo0y3lx0u44wz-wpengine.netdna-ssl.com/wp-content/uploads/2021/07/Extended-Range-GMLRS.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
