### ISSUE TITLE
M270 for Finland

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1523]
### DB Selector

DB3K

### DBID to Copy

156

### Hypothetical

No

### Name

Arty Plt [MLRS] 298 RSRAKH 06 (M270)

### Country

Finland

### Service

Army

### In Commission

2011

### Other Changes

Remove ATACMS weapon option

### Sources

https://puolustusvoimat.fi/en/equipment#/asset/view/id/501

https://www.prnewswire.com/news-releases/lockheed-martin-receives-453-million-contract-to-upgrade-finlands-precision-fires-capability-122148484.html

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
