### ISSUE TITLE
M270 with ER GMLRS for Finland

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#1525]
### DB Selector

DB3K

### DBID to Copy

2445

### Hypothetical

No

### Name

Arty Plt [MLRS] 298 RSRAKH 06 (M270) w ER GMRLS

### Country

Finland

### Service

Army

### In Commission

2022

### Other Changes

Remove ATACMS and add ER GMRS with unitary and alternative warheads instead (issues #1521 and #1520 )

### Sources

https://militaryleak.com/2022/02/13/finland-to-acquire-munition-for-extended-range-guided-multiple-launch-rocket-system/

https://www.dsca.mil/press-media/major-arms-sales/finland-extended-range-guided-multiple-launch-rocket-system

No IOC date found so I put 2022 but it's likely later

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
