### ISSUE TITLE
Ship Combat System Generation Updates (DB3K)

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#1526]
### DB Selector

DB3K

### Affected DBID(s)

All Ticonderogas, Many Burkes, Many Nimitzs, Assorted Others.

### Summary of Changes

Currently, in gameplay AND in the DB viewer, #3129 - LHA 8 Bougainville [America Flight I] (United States - 2024) has a CS Gen 4-appropriate 55-second OODA time (10-second detection, plus 45-second targeting). There is no dispute this should be a modern CS Gen 6, as the ship is yet to be finished, and will have the fancy AN/SPY-6 radar.

The DB viewer and testing indicate #604- D 32 Daring [Type 45 Batch I] (United Kingdom - 2011) CS is currently generation 4, when it clearly demands generation 6, based on comparable ships in its and other navies. All Type 45s of both Batches are similarly affected:
**#604, #1442, #2642, #2318, #3438, #3200, #3437.**

All NTU ships naturally need CS Gen 5, for it is in the spreadsheet guidance, and they have the fitting 'Late 1980s' NTU sensors. The DB reads CS Gen 4, and their response times match it, at 55 seconds to launch against a VAMPIRE. Includes applicable Leahy-, Mahan [Farragut]-, Kidd-, Virginia [Semi-NTU]-, California-, Truxton-, Bainbridge-, Josephus Daniels [Belknap]-classes, and carriers:
**#1904, #1905, #265, #113, #2000, #1250, #1997 #960, 1906, #744, #1130, #473, #562, #1247, #1028, #1382, #483, #1669, #900, #779, #1069, #1203, #1674, #573, #776, #666, #221, #1672, #1624, #414, #1625, #1623, #1628, #1631, #1632, #1670, #898, #778, #1209, #1210, #1211, #747, #1633, #1671, #903, #905, #1208, #1634, #422, #1983, #1635, #662, #272, #907, #741, #1070, #780, #1102, #1212, #1636, #886, #1665, #910, #447, #1666, #1664, #1638, #1639, #1640, #678, #1662, #913, #450, #1072, #246, #37, #1667, #914, #454, #1074, #381, #1108, #1644, #1668, #1645, #1646, #1647, #1648, #1649, #657, #916, #658, #1075, #659, #1651, #1652, #1653, #1654, #1657, 1658, 1659, 1660.**

2001 is the earliest refit that installs the AN/SPQ-9B on the Nimitz-class. This is described in the DB viewer as 'Early 2000s technology', when other sensors are 'Early 1990s', fifth generation, at best. As far as I can divine, this is the upgrade that awards the 2001-refit USS Nimitz the quickest OODA score in the old system on the DB viewer. I cannot assess the merit of this justification for improving the response time, and this alone seems a small adjustment to bestow the best combat system. On the other hand, since this is the only relevant sensor change in the Nimitz-class carriers from the late 1990s to the present day, ignoring this change might mean leaving the whole class at fifth generation to current times. That seems lacklustre, and would be a departure from current precedent in the old system, yet still plausible, and more investigation may be in order. The stated CS generation in the DB viewer, and that observed in testing, is CS generation four, with a 55-second delay. If they indeed need changing, these are the ones going by the SPQ-9B refit (whatever the case, these later refit Nimitz-classes should all at least be changed from the current CS Gen 4 to CS Gen 5, as in the previous section):
**#1071, #341, #1642, #1656, #1217, #1205, #1661, #1650, #1215, #1643, #1213, #505, #1901, #1214, #2484, #1902, #2481, #2482, #2483, #1984, #2720, #2722, #2721, #2585, #3225, #3226, #2587, #3228, #3227, #3558, #3557, #3556, #3555, #3554, #3553, #3552, #3551, #3550, #3549.**

All Arleigh Burkes have generation five OODA speed in-game and labelling in the DB viewer, even the future DDG 125 Jack H. Lucas (2024). They share the same OODA numbers, so it is not possible to infer the DB's intent for where the sixth generation starts. The first 2000s-era sensor comes with the 2002 ships, like entry #1939 - DDG 81 USS Winston S. Churchill--the Mk46 Mod 1 designated '2000s/2010s'. It seems questionable the Mk46 truly changed the combat-responsiveness by a whole generation. The source below gives DDGs 79-84, 85-90, and 91-112 as three major tranches of combat computers, which corresponds to selecting between Oscar Austin, McCampbell, or Pinckney as the first ship of CS Gen 6. It comes down to picking where to draw the line. #661 - DDG Oscar Austin, 2002 (launched 1998), seems too early to call sixth generation: it has only the first stage of adjunct COTS processors, designed 1994 to 1999, and no sensors more recent than 'Early 1990s'. The first '2000s' listed radar is the AN/SPY-1D(V) MFR [ABM Mod] fire control radar (and the less relevant Bridgemaster E ATA navigation radar), on #1023 - DDG 85 McCampbell in 2003. McCampbell is the first Build 6, Phase III with more developed COTS. Maybe the 'Early 2010s' AN/SPG-62 [Mk99 FCS, ABM Mod] 'Early 2010s' fire control radar on all the 2008 refits is a better match? The source finally indicates the first ship with no AN/UYK-43/44, and only COTS is #1150 - DDG 91 Pinckney, dated to 2005, with the combat computer developed between 1999 and 2002. This cleaves well to the outline of where you want the generations to fall. Since the assessment is complex, although I would submit Pinckney fits best, I will leave it to your judgement. If #1150 is the delimiter, the DBIDs to change are (I estimate a major upgrade to sensors after 2005 authorizes CS Gen 6 for ships older than Pinckney; a new 2005 DB entry for adding the MK54 torpedo does not count):
**#1150, #1194, #1195, #1151, #445, #1941, #443, #442, #438, #1874, #2378, #2377, #2376, #2375, #2374, #2491, #2490, #3194, #2349, #2348, #3150, #3147, #2347, #2346, #2345, #2344, #2343, #2067, #2951, #2953, #2716, #2873, #3148, #2872, #2871, #2870, #2869, #2868, #2954, #2867, #3201, #2952, #2717, #2866, #3151, #2865, #3209, #3140, #2718.**

Ticonderoga-class ships have the same issue, fielding and displaying only CS Gen 4 ability, even when they sport better equipment. The written OODA numbers in the DB viewer are the second-fastest tier in game, but actual speed is 55 seconds to target a VAMPIRE, corresponding to CS Gen 4. Maybe their internal combat systems remained antiquated? It would make things simple. From the table, the then-new Aegis Combat System (ACS) of the first 1983 Ticonderogas sit happily between the NTU--designed to be a cheaper ACS imitator--and the UKY-43 processor upgrade for Aegis, starting with CG 65, and DDG 61, thus right in the middle of CS Gen 5.![CS Table](https://user-images.githubusercontent.com/87087226/175849810-7f9c38e1-158c-48b5-af81-8efec2ab67ac.png)Clearly, Ticonderoga-class cruisers should start at CS Gen 5. Their DBIDs:
**#525, #42, #512, #513, #110, #977, #40, #547, #1996, #1995, #954, #628, #515, #736, #1054, #702, #532, #754, #583, #582, #579, #523, #431, #1860, #1859, #1858, #1095, #1856, #1857, #756, #551, #550, #549, #548, #527, #546, #545, #1065, #1063, #1062, #1060, #1059, #1058, #973, #503, #309, #535, #978, #767,#516, #411, #795, #971, #786, #781, #770, #763.**

For generation six, Ticonderogas start to get hardware labelled 2000s or better in 2008 with the 2010s-design AN/SPG-62 [Mk99 FCS, ABM Mod] radar from above, concurrently with '2000s/2010s' C-Lite IR things on the 25 mm cannon mounts, and a new Phalanx. #602 CG 70 Lake Erie [Ticonderoga Baseline 4, VLS] (United States - 2008) is the earliest on the insert unit selector. If you go with the radar criterion, and ignore ships that receive C-Lite sensors but no radar (nowadays, C-Lite may refer to a battle management system in some products, but here I do not think the ships with new small cannon gun directors need a CS generation increase), these are the DBIDs to go to **CS Gen 6**, which accounts for all Ticonderogas:
**#602, #599, #2156, #2158, #2159, #2160, #2161, #2128, #2126, #2125, #2124, #2123, #2342, #2341, #3152, #2340, #2339, #2338, #2337, #3149, #2864, #2863, #2862, #2861, #2860, #2859.**

This is probably enough to be getting on with.

### Sources

Testing in 494.

C-Lite may be a BMS, although it is doubtful that this applies to Ticonderogas:
https://defaiya.com/news/Products/Products/2014/05/07/c2-unveils-c-lite-gen-3-tactical-mission-system-at-sofex

More than you ever wanted to know about AN/UYK-43/44 circuits. Ctrl+F "Adjunct COTS" for outline of computer configurations in destroyer and cruiser building: https://ethw.org/First-Hand:Legacy_of_NTDS_-_Chapter_9_of_the_Story_of_the_Naval_Tactical_Data_System#Aegis

**Comment by PygmalionOfCyprus** [comment]
Beautiful. Great work, thanks for this.

**Comment by PygmalionOfCyprus** [comment]
Having read it more deeply I can safely say I agree with all your conclusions here. All changes made as per your suggestion.

**Comment by Zomorudas** [comment]
Fantastic. You are very welcome.
