### ISSUE TITLE
AN/APQ-104 ( for F-8E(FN) Crusader ) needs to be an illuminator for the AIM-9C

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#1528]
### DB Selector

CWDB

### Affected DBID(s)

Weapon 247. Aircraft 668 and 2847. Loadout 594.

### Description of Problem

I appreciate that you fixed the AIM-9C and the loadouts for the F-8E(FN). However, it appears that the F-8E(FN) Crusader's radar is unable to actually illuminate for the AIM-9C SARH. 

(P.S. I have not checked yet, but while you are in there, could you please make sure that the R.530 can be illuminated by the F-8E(FN) as well ?) 

### Recommended Fix

Add the AN/APQ-104 as an illuminator for the AIM-9C (and possibly the R.530).

**Comment by PygmalionOfCyprus** [comment]
Whoops! Fixed for 495. (And yes, the R.530 can take designation from the F-8E.)
