### ISSUE TITLE
Add Ethiopian Fly Dragon UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1533]
### DB Selector

DB3K

### Hypothetical

No

### Name

FLY Dragon FLY-330

### Country

Ethiopia

### Service

Air Force

### In Commission

Seen Since 2021

### Number in Service

unknown

### Length (m)

2.1m

### Wingspan (m)

3.3m

### Height (m)

0.7m

### Empty Weight (kg)

Not Stated

### Maximum Takeoff Weight (MTOW) (kg)

35kg

### Payload Weight (kg)

10kg

### Crew

0

### Propulsion

60cc-100cc Gasoline Engine + 4x Electric

### Rate of Climb (ft/min)

Not Stated

### Service Ceiling (ft)

4500m

### Military/Afterburner Speed (kt)

120km/h

### Cruise Speed (kt)

100km/h

### Supercruise

No

### Ferry Range (nm)

not Stated

### Endurance (min)

5-8 hours

### Takeoff / Landing Distance (m)

VTOL

### Fuel Capacity (kg)

8L

### Sensors

Various commercial optics

### Mounts

N/A

### Loadout Options

Internal Recon

### Comms/Datalinks

Satellite navigation w/ real-time GPS/GLONASS/Galileo/B Multi-system signal reception

### Sources

https://www.oryxspioenkop.com/2021/10/from-mohajer-6s-to-wing-loong-is.html

http://www.dronefromchina.com/product/FLY-330-Gasoline-Engine-VTOL-KIT-Frame.html

![image](https://user-images.githubusercontent.com/99599482/176479932-d0ea427a-a7da-4b33-ae72-26a6dc9dd27b.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
