### ISSUE TITLE
Qaem-5 Loadout for Mohajer-6

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1534]
### DB Selector

DB3K

### User(s)

Iran/Ethiopia

### Weapons Carried

2x Qaem-5

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Match Loadout 28102

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Replaced IIR Qaem-1 with EO guided Qaem-5. Seen in use by Ethiopia, Iranian aircraft can probably use as well.

### Sources

https://www.oryxspioenkop.com/2022/01/drone-warfare-turns-hot-over-ethiopias.html

https://en.wikipedia.org/wiki/Qaem

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
