### ISSUE TITLE
Add Ethiopian HW-V230 VTOL drone

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1535]
### DB Selector

DB3K

### Hypothetical

No

### Name

HW-V230 VTOL drone

### Country

Ethiopia

### Service

Air Force

### In Commission

Seen since 2021

### Number in Service

unknown

### Length (m)

2.2m

### Wingspan (m)

4.0m

### Height (m)

0.6m

### Empty Weight (kg)

Not Stated

### Maximum Takeoff Weight (MTOW) (kg)

38kg

### Payload Weight (kg)

5kg

### Crew

0

### Propulsion

1x Pistion + 4x Electric

### Rate of Climb (ft/min)

Not Stated

### Service Ceiling (ft)

3500m

### Military/Afterburner Speed (kt)

140km/h

### Cruise Speed (kt)

80~110km/h

### Supercruise

No

### Ferry Range (nm)

50km

### Endurance (min)

6h

### Takeoff / Landing Distance (m)

VTOL

### Fuel Capacity (kg)

Not Stated

### Sensors

Various Commerical Fits for EO/IR

### Mounts

N/A

### Loadout Options

Recon

### Comms/Datalinks

Radio LOS Datalink

### Sources

https://www.oryxspioenkop.com/2021/10/german-drones-in-ethiopia.html

https://www.oryxspioenkop.com/2021/10/from-mohajer-6s-to-wing-loong-is.html

https://www.oryxspioenkop.com/2021/09/made-in-china-ethiopias-fleet-of.html

https://www.militarydrones.org.cn/hw-v230-vertical-takeoff-and-landing-fixed-wing-uav-p00194p1.html

![image](https://user-images.githubusercontent.com/99599482/176484407-0ee5301c-d6ea-49dd-9b3f-44d9d558aac8.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
