### ISSUE TITLE
Add Ethiopian ZT-3V Drone

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1536]
### DB Selector

DB3K

### Hypothetical

No

### Name

ZT-3V VTOL UAV

### Country

Ethiopia

### Service

Air Force

### In Commission

see since 2021

### Number in Service

unknown

### Length (m)

3.6ft

### Wingspan (m)

7.87ft

### Height (m)

Not Stated

### Empty Weight (kg)

8 lbs

### Maximum Takeoff Weight (MTOW) (kg)

17.85 Ibs

### Payload Weight (kg)

2.2 Ibs

### Crew

0

### Propulsion

Electric

### Rate of Climb (ft/min)

Not Stated

### Service Ceiling (ft)

4500M

### Military/Afterburner Speed (kt)

Not Disclosed

### Cruise Speed (kt)

37.80 knots

### Supercruise

No

### Ferry Range (nm)

30km

### Endurance (min)

1H

### Takeoff / Landing Distance (m)

VTOL

### Fuel Capacity (kg)

Battery

### Sensors

EO Sensor Turret

### Mounts

N/A

### Loadout Options

Recon

### Comms/Datalinks

Radio Datalink

### Comments

Commerical type drone pressed into military service

### Sources

https://www.oryxspioenkop.com/2021/09/made-in-china-ethiopias-fleet-of.html
https://www.oryxspioenkop.com/2021/10/from-mohajer-6s-to-wing-loong-is.html
https://www.oryxspioenkop.com/2021/10/german-drones-in-ethiopia.html
https://www.zerotech.com/uav-uas/zt-3v/
https://blog.dronetrader.com/vtol-vertical-take-off-and-landing-hybrid-drones-available-for-sale/

![image](https://user-images.githubusercontent.com/99599482/176485520-fc5541ca-4a22-408c-9f9a-03aa076c6b30.png)
![image](https://user-images.githubusercontent.com/99599482/176485606-53e20783-3a99-499f-8c82-b8403065c9bb.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
