### ISSUE TITLE
Add Ethiopian Mugin F300 UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1539]
### DB Selector

DB3K

### Hypothetical

No

### Name

Mugin F300

### Country

Ethiopia

### Service

Air Force

### In Commission

Since at least 2020

### Number in Service

unknown

### Length (m)

3.5m

### Wingspan (m)

5m

### Height (m)

Not Stated

### Empty Weight (kg)

33.64kg

### Maximum Takeoff Weight (MTOW) (kg)

85kg

### Payload Weight (kg)

25kg

### Crew

0

### Propulsion

DLA 180cc EFI Engine with Starter & Alternator x 1

### Rate of Climb (ft/min)

Not Stated

### Service Ceiling (ft)

not stated

### Military/Afterburner Speed (kt)

150km/hr

### Cruise Speed (kt)

120km/hr

### Supercruise

No

### Ferry Range (nm)

not stated

### Endurance (min)

>7 Hours

### Takeoff / Landing Distance (m)

60/85m

### Fuel Capacity (kg)

27 Liters

### Sensors

Various based on fit. 1000mmx345mmx350mm payload bay

### Mounts

Ethiopian aircraft seen with 1 hardpoint on each wing for some kind of pod..

### Loadout Options

Ferry
Recon
ELINT/ECM with Pods?

### Comms/Datalinks

Command Datalink

### Comments

Agricultural drone pressed into military service stats based on current Mugin 5 model

### Sources

https://www.oryxspioenkop.com/2021/10/from-mohajer-6s-to-wing-loong-is.html
https://www.muginuav.com/product/mugin-5-pro-5000mm-carbon-fiber-uav-platform/

![image](https://user-images.githubusercontent.com/99599482/176496081-aa3c32d5-b5f8-4cc0-8a64-2c27b7ee18c2.png)

**Comment by tbrandon517** [comment]
Tagged as Hypothetical in error. Fixed.

**Comment by Jkryos** [comment]
Added DB3K 496.
