### ISSUE TITLE
Add Ethiopian M20 (DF-12) SRBM

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1541]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM BN DF-12

### Facility Type

SSM

### Country

Ethiopia

### Service

Army

### In Commission

Late 2010's

### Number in Service

uncertain

### Crew

Same as DBID 2142

### Dispersion Radius (m)

Same as DBID 2142

### Sensors

Same as DBID 2142

### Mounts

Same as DBID 2142 plus A200 MLRS Capability

### Magazines

Same as DBID 2142 plus A200 MLRS Capability

### Aircraft & Docking Facilities

Same as DBID 2142

### Comments

DF-12/M20 confirmed in Ethiopian Serviced.

### Sources

https://www.oryxspioenkop.com/2021/09/go-ballistic-tigrays-forgotten-missile.html
https://www.oryxspioenkop.com/2021/09/from-friend-to-foe-ethiopias-chinese.html
https://www.oryxspioenkop.com/2021/11/a-deterrent-undone-tigrays-last-missile.html

![image](https://user-images.githubusercontent.com/99599482/176498818-eff03e03-ee3a-45ba-8753-27b016c07527.png)

**Comment by Jkryos** [comment]
Added DB3K.
