### ISSUE TITLE
Japan, Type 12, G-RX5

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1543]
### DB Selector

DB3K

### Baseline

Type 97 (Weapon 314)

### Hypothetical

No

### Name

Type 12

### Length (m)

2.83

### Width/Span (m)

0.324

### Diameter (m)

0.324

### Weight (kg)

320

### Range (nm)

7

### Warhead

copy Mk50's HE Shaped Charge

### Targets

Submarine

### Sensors

1x Active Torpedo Seeker, late 2000 tech, Shallow water capable (Sensor Role 5712)

Type 12 has also side Scan sonar and Magnetic sonar, but while I cannot find in CMO, may better to wait for sim update.

### Weapon Codes

Search Pattern, Bearing-Only Launch (BOL), Re-Attack Capability

### Comments

This is upgraded version of Type 97 Torpedo.

Related to #1353 
I forgot to request change the Warhead. Type 97 and 12 uses same sharped Charge HE warhead. Weight ifs unknown, so I believe we can copy from mk50.

current users are SH-60K, P-1, Asahi class DD (ID 3128) and Maya class DDG (SHIP 3211). I guess will make separate request for that.

### Sources

https://ja.wikipedia.org/wiki/12%E5%BC%8F%E9%AD%9A%E9%9B%B7

**Comment by PygmalionOfCyprus** [comment]
Added 496, added to listed units (along with magazine upgrades, etc.), and tweaked both its and the Type 97 warhead (same ID) accordingly.
