### ISSUE TITLE
Denmark, Iver Huitfeldt, Harpoon quantity

### ISSUE THREAD

**Issue by MarkLJRDDC** [PygmalionOfCyprus/cmo-db-requests#1544]
### DB Selector

DB3K

### Affected DBID(s)

2331

### Summary of Changes

Standard loadout of the Huitfeldt Class is 4 mk141 Harpoon launchers, for a total of 16 Harpoons, rather than just 8.

### Sources

The frigates are built up around a number of swappable weapon platform, of which the standard loadout contains 4 mk141 launchers, 1 mk41 launcher and 2 mk56.

https://www.seaforces.org/marint/Danish-Navy/Frigate/F-363_DAT/F-363-HDMS-Niels-Juel-25.jpg shows a pic of Niels Juel (Huitfeldt Class), with a fully loaded missile deck.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
