### ISSUE TITLE
RIM-66M-2 SM-2MR Blk IIIA Range increase

### ISSUE THREAD

**Issue by MarkLJRDDC** [PygmalionOfCyprus/cmo-db-requests#1545]
### DB Selector

DB3K

### Affected DBID(s)

1195

### Summary of Changes

The SM-2 Block IIIA (and possibly others), need to have their max range upped to 90nm instead of the current 50.

### Sources

https://missilethreat.csis.org/defsys/sm-2/#:~:text=SM%2D2%20Block%20III,and%20weigh%20around%201%2C558%20pounds.

https://www.navy.mil/DesktopModules/ArticleCS/Print.aspx?PortalId=1&ModuleId=724&Article=2169011

**Comment by PygmalionOfCyprus** [comment]
Weapon ID 1195 (RIM-66M-2 SM-2MR Blk IIIA) has had a maximum anti-air range of 90nm for at least the last several years.
