### ISSUE TITLE
Correction for Type 730 CIWS and Type 1130 CIWS

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1548]
### DB Selector

DB3K

### Affected DBID(s)

862 H/PJ-12 [Type 730] & 2176 H/PJ-14[Type 1130]

### Summary of Changes

-Both CIWS is fully automated, thus it were supposed to have "no OODA delay" capability just like H/PJ-11 (DBID 3089)

![image](https://user-images.githubusercontent.com/99646926/176559257-7bde9608-705a-42e6-8e3c-12b91506851f.png)

-the Type 730 CIWS uses OFC-3 EO system alongside its FCR to guide the gun which include laser rangefinder, IR & TV camera. (DBID 6324, 6325 & 6323) . Same is true for Type 1130 as well as per pics below.

![image](https://user-images.githubusercontent.com/99646926/176558720-49989d44-c467-42a5-b0a3-144f1cd1dc74.png)

![image](https://user-images.githubusercontent.com/99646926/176558876-b95f9d92-dd3c-4744-8fd3-173451336d76.png)
Type 730 firing with its OFC-3 EO system visible.

### Sources

https://en-academic.com/dic.nsf/enwiki/2202486
https://en.topwar.ru/63769-korabelnye-zenitnye-artilleriyskie-kompleksy-type-730-i-type-1130-kitay.html

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
