### ISSUE TITLE
Switzerland - Hermes 900 UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1552]
### DB Selector

DB3K

### DBID to Copy

DBID #2576

### Hypothetical

No

### Name

ADS-15 Reconnaissance Drone System (Hermes 900 UAV)

### Country

Switzerland

### Service

Air Force

### In Commission

2022

### Number in Service

6

### Sensors

None Indicated

### Mounts

None Indicated

### Loadout Options

No Change Indicated

### Other Changes

None Indicated

### Sources

https://www.flightglobal.com/defence/switzerland-receives-first-two-hermes-900-uavs-from-elbit/148542.article?utm_source=rss&utm_medium=Sendible&utm_campaign=RSS&fbclid=IwAR3fOhkyLPQeRBUF8ubI49XoX5SRIQIEnp1L4x4uv76mdE9-p5WVgquZ3i0

![image](https://user-images.githubusercontent.com/99599482/176682640-ea7c98b6-d8bb-47f1-a610-1a6a1cec463d.png)

**Comment by tbrandon517** [comment]
Looks like this got picked up for V495.

**Comment by PygmalionOfCyprus** [comment]
Good to know our weekly news roundups are working!
