### ISSUE TITLE
Camcopter S-100 UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1553]
### DB Selector

DB3K

### DBID to Copy

DBID #5238

### Hypothetical

No

### Name

Camcopter S-100 UAV

### Country

Romania and Thailand

### Service

Romanian Border Police, Royal Thai Navy

### In Commission

2021 (Romania), 2019 (Thailand)

### Number in Service

1 (Romania), 4 (Thailand, 2x 2019 + 2x 2022)

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.navalnews.com/naval-news/2022/05/schiebel-camcopter-s-100-performs-maritime-survellience-in-romania/?fbclid=IwAR01fMjAGaug5mVdiCm-MEaBEsvbXZpam5k0Yu_AwUB8utEFgerThsGGIiA

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/april/11632-schiebel-to-equip-royal-thai-navy-with-camcopter-s-100-uav.html?fbclid=IwAR06awD8t05qTTlp4iCeOJICiGAGJkOgOULqD3mePLDpSy1bqBMtMFnXnrI

https://www.shephardmedia.com/news/naval-warfare/thailand-confirms-additional-camcopter-s-100-procu/

![image](https://user-images.githubusercontent.com/99599482/176684259-f5aa1ae8-851b-481d-9b5f-bd8c8ed07df0.png)

**Comment by tbrandon517** [comment]
Looks like the Romanian portion got picked up for V495.

**Comment by PygmalionOfCyprus** [comment]
Added Thai 'copters to 496.
