### ISSUE TITLE
South Africa - Hamerkop (Nuclear H-2 SOW) Strike Loadout

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1555]
### DB Selector

DB3K

### User(s)

South African Buccaneer DBID # 1553

### Weapons Carried

Replace conventional H-2 SOW [Raptor 1] with nuclear variant Hamerkop (10-20KT)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as Conventional H-2

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

No

### Sources

https://en.wikipedia.org/wiki/Blackburn_Buccaneer#South_African_Air_Force_2

https://www.thedrive.com/the-war-zone/38646/this-is-the-jet-that-would-have-carried-south-africas-nuclear-bomb

**Comment by FrangibleCover** [comment]
Related to #2213

**Comment by tbrandon517** [comment]
Aircraft 7037
