### ISSUE TITLE
Brazil F-5M MICLA-BR Loadout

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1557]
### DB Selector

DB3K

### User(s)

Brazil F-5EM and F-5FM DBID #'s 2102 and 3606

### Weapons Carried

2-4x AAM, MAA-1 Piranha and/or Python-4 or Derby
2x 275 USG Drop Tanks
1x MICLA-BR

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

470nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Images of test loadouts. Actual load guessed based on hardpoint capabilities. Looks like the F-5M's should have HMD flag as well.

### Sources

https://www.thedrive.com/the-war-zone/37151/brazils-upgraded-tiger-iis-might-be-the-most-capable-f-5s-in-the-world

https://tecnodefesa.com.br/micla-br-ou-missil-de-cruzeiro-de-longo-alcance-do-brasil-confirmado/

https://en.wikipedia.org/wiki/AV-TM_300

https://www.globalsecurity.org/military//world//brazil/micla-br.htm

https://military-wiki.com/brazils-f-5m-tiger-ii-no-doubt-these-are-the-most-capable-f-5s-in-the-world/

https://twitter.com/ninja998998/status/1419569431840268288

![image](https://user-images.githubusercontent.com/99599482/176706192-fcc5ff94-a4e4-45a1-80dc-b88bbcb761f2.png)

![image](https://user-images.githubusercontent.com/99599482/176706657-f2b4851e-02c9-4c26-b0e0-465ca680e21d.png)

![image](https://user-images.githubusercontent.com/99599482/176706840-494c87e8-3f4c-479a-bcb2-0da9f24f5bfe.png)

![image](https://user-images.githubusercontent.com/99599482/176706263-d36a5a8f-3bb2-4847-bfad-580fb85b9437.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
