### ISSUE TITLE
Portugal Tejo (ex-Flyvefisken) Class x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1558]
### DB Selector

DB3K

### DBID to Copy

295 DB3K

### Hypothetical

No

### Name

590 Tejo

### Country

Portugal

### Service

Navy

### In Commission

2015-

### Number in Service

4x

### Sensors

- 2x Furuno Radars

### Mounts

- No weapons

### Other Changes

Ship project history: Danish Stanflex 300 design, transferred unarmed after decommission by Danish Navy in 2010 as replacement for cancelled five project LFC 2005 ships and Cacine class patrols. Purchased in October 2014 and transferred in 2015. Fifth ship, Gribben, was transferred for cannibalization.

Modernizations: None.

### Sources

http://navypedia.org/ships/portugal/pr_es_tejo.htm
https://en.wikipedia.org/wiki/Flyvefisken-class_patrol_vessel

![Portuguese_Navy_sends_Tejo-class_NRP_Douro_to_Desertas_Islands](https://user-images.githubusercontent.com/99632305/176714162-043393f5-b664-4422-9272-cccc952c2f6f.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
