### ISSUE TITLE
S-400, S-300 360 Degree Concurrent Missile Launches - Not Possible IRL.

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1559]
### DB Selector

Both

### Affected DBID(s)

Space Fed Russian Fire Control Radars

### Description of Problem

Space fed arrays CANNOT guide missiles in multiple split axes ever.  They have a live side and a dead side.  Dead side may be up to 300 degrees, system dependent.
I can demonstrably and repeatedly show this fault that cannot ever happen IRL
I have called it out before (in CMANO) and I am hoping the answer is not the same as I got way back.
You continue to make S-400 and S-300 god like, which they are not.  They can, IRL, be beaten by multiple axis attacks of guided weapons (Tomahawk, JASSM etc) without breaking the bank.  But in Command many more weapons are needed as you need to force a full reload cycle.  Not realistic.  As an aside I tried to take out just the FCR, after all no FCR no guidance, but thats just pot luck it would seem (even when using a weapon which is ballistic and with a CEP of 3 metres).
I am aware that the FCR's sit on a mechanical 360 rotating base, but this is only part of the story, they are highly directional and they MUST face the target for the entirety of the ongoing engagement (unless you want to give us 9M96 ;-) )

### Recommended Fix

Unsure.  I think you will tell me that it cannot be done without swinging the balance the other way, but at least acknowledge that (respectfully) its a fudge to the rank and file users who are struggling to kill this system within the confines of RL weapon stocks...

**Comment by TTZ32** [comment]
Then modify EVERY other sam so that it can't attack targets in a 360° arc because NONE can do it, don't single out the S-300/400.

**Comment by HVAA** [comment]
Oh dear, you have completely missed the point of my request.

- MIM-104 can fire 9 missiles into a 120 sector IRL and in the game.
- SA-2 can fire 2 to 3 missiles at a single target anywhere its radar can point.
- SM2, 3, 6 with Aegis can fire 18 missiles ish anywhere the SPY can look (360 continuous radar coverage).
- S-300, 400 with a space fed array, with a 60, 90 or 120 sector (depends where you read) can pop 8 or 12 missiles into that sector to engage up to 6 targets. 

What they cannot do is fire 6 missiles at 3 targets coming in from 270 Deg whilst simultaneously firing 6 missiles at 6 targets coming in from 090 Deg, physically impossible, yet thats what they do in the game.
So I am picking on S-400/300 for a valid reason, it cant do what it does in the game IRL, whereas the others I have quoted above ,most certainly can.  I havent even tried the Buk, Tor, Pantsyr systems, because they too use a similar form of tracking and guidance to get multi target abilities and they too have sector limits in which they can perform this, but because they range is shorter, the missile count is lower, they are not 'fingers of god' whereas the S-300/400 are (but only in the game).

**Comment by gosnold** [comment]
That depends on the missile seeker right? It only impossible for command guidance and SARH?

**Comment by HVAA** [comment]
Its also impossible for TVM where there is not FCR illumination of the target.  TVM relies on comparison from the 'picture' from the seeker and the 'picture' from the FCR.  SAGG is a simplified version of TVM.  If a radar can track targets in a 360 fashion, then missiles can be 'spat' in all directions.  If a radar points in a fixed direction, then targets can only be tracked by it in that direction (or sector).  Before anyone says 'Cheeseboard' it also has a live side and a dead side.

**Comment by PavelNovak79** [comment]
HVAA is right here. Problem is that SA-10 engagement radar in game doesn't distinguish between search and track mode. In search it can scan 360° but once starts to track a target it can continue scan and engage targets only in about that 60° to 120°. In game currently it can attack two targets flying from opposite direction (see picture).

This is not an issue wiht Patriot due to its limited search angle and it is not issue with older type of SAMs which can engage only one target.

![sa-10 test](https://user-images.githubusercontent.com/106174580/177006504-150da2e5-dd7d-4a5b-854f-7afa268a11e1.jpg)

**Comment by ddranidis** [comment]
We are looking into this. It is a challenging item.

**Comment by ddranidis** [comment]
Currently testing a change in sensor/engagement modeling that addresses this: https://i.imgur.com/8yFstnH.mp4

This change affects any radar that performs both volume-search and weapon guidance/illumination against multiple targets (e.g. AWG-9/APG-71 on F-14).
