### ISSUE TITLE
Kh-32 Range and Warhead Correction

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1560]
### DB Selector

DB3K

### Affected DBID(s)

3122

### Summary of Changes

The range of the Kh-32 should be 1000km (so at least double of the original).
The warhead should be reduced to 500Kg (to allow for the extra fuel).

### Sources

https://www.navyrecognition.com/index.php/focus-analysis/naval-technology/6088-new-kh-32-antiship-missile-becomes-operational-in-russia-part-1.html
https://lenta.ru/news/2018/05/15/tu22/
https://www.rbth.com/defence/2016/08/30/new-russian-cruise-missiles-to-hit-targets-from-the-stratosphere_625441

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
