### ISSUE TITLE
Add 12.7mm Anti-Material Sniper Rifle to USCG MH-68A Helos

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#157]
### DB Selector

DB3K

### Affected DBID(s)

DBID 2051 MH-68A

### Summary of Changes

Please add weapon Weapon #3736 12.7mm Anti-material rifle as USCG HITRON helicopters carry these for disabling shots.

### Sources

https://en.wikipedia.org/wiki/Helicopter_Interdiction_Tactical_Squadron#Weapons
https://special-ops.org/us-coast-guard-hitron/
https://images.guns.com/wordpress/2013/05/hitron_gunner_with_tools_of_the_trade.jpg
![hitron](https://user-images.githubusercontent.com/99599482/154348730-2cc6731b-ff1b-4f01-930d-857c87514ff7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 493.

**Comment by tbrandon517** [comment]
Looks like 12.7mm missed out in V493

![image](https://user-images.githubusercontent.com/99599482/164277798-f64ee1cc-8d29-4dfa-b80a-868589ee1b93.png)

**Comment by PygmalionOfCyprus** [comment]
No idea how that happened. Added...again...for 494...?

**Comment by tbrandon517** [comment]
> No idea how that happened. Added...again...for 494...?

Gremlins
