### ISSUE TITLE
#4223, #5134 Japanese F-35 Lightning II A/A Loadouts error

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#1575]
### DB Selector

DB3K

### Affected DBID(s)

#4223, #5134

### Summary of Changes

#4223 F-35A Lightning II Loadouts DB ID - 28477, 28478
#5134 F-35B Lightning II Loadouts DB ID - 28486, 28487

It needs to change right A/A missile. [AIM-120D > AIM-120C-7 AMRAAM (#718)]

### Sources

from DB3K v494

**Comment by KC45jp** [comment]
Japan does actually have AIM-120D(C-8), however, the number is limited. (Only 32)
https://www.dsca.mil/node/1378

**Comment by PygmalionOfCyprus** [comment]
Fixed for 496. Japan may have an extremely limited AIM-120D capability but these particular loadouts weren't intended to reflect that...I just forgot to swap out the AMRAAMs when I copied them from the US F-35s.
