### ISSUE TITLE
B-49 Armament Corrections

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#1577]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 3439

### Summary of Changes

Even though it's a hypothetical, the B-49's loadouts are inaccurate compared to the Standard Aircraft Characteristics and bomb bay dimensions. From the SAC, bomb loadouts were:

2x 4,000 pound bomb (Likely M56 blockbusters, not currently in database)
5x 2,000 pound bomb 
10x 1,600 pound bomb (Likely AP Mk 1, not currently in database)
10x 1,000 pound bomb
30x 500 pound bomb 

For nuclear bombs, the most it could carry would be one Mk1 "Little Boy" (Weapon #811). For anything bigger of the time, the bomb bay was just too narrow. 

### Sources

B-49 SAC: http://www.alternatewars.com/SAC/YB-49_Flying_Wing_SAC_-_20_December_1949.pdf

M56 4,000 pound bomb: https://bulletpicker.com/bomb_-4000-lb-lc_-an-m56_-an-m.html
Mk1 1600 pound AP Bomb: https://bulletpicker.com/bomb_-1600-lb-ap_-an-mk-1.html
Bomb bay width issues: http://www.joebaugher.com/usaf_bombers/b49_3.html

**Comment by tbrandon517** [comment]
Guessing these loadouts would also apply to the B-35 as well.

**Comment by Coiler12** [comment]
> Guessing these loadouts would also apply to the B-35 as well.

Yep, I don't see why not.

**Comment by PygmalionOfCyprus** [comment]
Fixed/added for 496 (and removed from AC, if not deleted, the errant loadouts).
