### ISSUE TITLE
#4097 S-92 - 2012, 5x Ireland Coastguard add EO system and searchlight. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1578]
### DB Selector

DB3K

### Affected DBID(s)

#4097

### Summary of Changes

The DB aircraft currently lacks the EO turret and searchlights the real aircraft has.
Please add what I beleive it is an L3 Teledyne FLIR Star Safire 380HD with a 360° turret.
Searchlight probably SX16 or similar.
Once added could the entry also be copied as a UK HMCG Coastguard version as well, please? 
UK version appears identical to Irish. In service UK from 2007. 

### Sources

https://www.flir.co.uk/products/star-safire-380-hd/ Safire 380.
https://afloat.ie/safety/coastguard/item/32055-irish-coast-guard-sar-service-using-new-s92-helicopters-reaches-10-000-hour-milestone - EO Turret and searchlights are clealry visible in the photos.
https://www.helis.com/database/modelorg/HM-Coastguard-S-92/ UK version appears identical to Irish. In service UK from 2007.

**Comment by PygmalionOfCyprus** [comment]
Fixed/added 496.
