### ISSUE TITLE
Add USCG MH-60T Jayhawk

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#158]
### DB Selector

DB3K

### Hypothetical

No

### Name

MH-60T Jayhawk

### Country

United States

### Service

Coast Guard

### In Commission

2007-Present

### Length (m)

As DBID 2050 HH-60J Jayhawk

### Wingspan (m)

As DBID 2050 HH-60J Jayhawk

### Height (m)

As DBID 2050 HH-60J Jayhawk

### Empty Weight (kg)

As DBID 2050 HH-60J Jayhawk

### Maximum Takeoff Weight (MTOW) (kg)

As DBID 2050 HH-60J Jayhawk

### Payload Weight (kg)

As DBID 2050 HH-60J Jayhawk

### Crew

As DBID 2050 HH-60J Jayhawk

### Propulsion

As DBID 2050 HH-60J Jayhawk

### Rate of Climb (ft/min)

As DBID 2050 HH-60J Jayhawk

### Service Ceiling (ft)

As DBID 2050 HH-60J Jayhawk

### Military/Afterburner Speed (kt)

As DBID 2050 HH-60J Jayhawk

### Cruise Speed (kt)

As DBID 2050 HH-60J Jayhawk

### Supercruise

No

### Ferry Range (nm)

As DBID 2050 HH-60J Jayhawk

### Endurance (min)

As DBID 2050 HH-60J Jayhawk

### Takeoff / Landing Distance (m)

As DBID 2050 HH-60J Jayhawk

### Fuel Capacity (kg)

As DBID 2050 HH-60J Jayhawk

### Sensors

As DBID 2050 HH-60J Jayhawk plus:

### Mounts

- 1x 7.62mm LMG
- 1x 12.7mm anti-material sniper rifle

### Loadout Options

As DBID 2050 HH-60J Jayhawk

### Comms/Datalinks

As DBID 2050 HH-60J Jayhawk plus:

Other similar US glass cockpit H-60 models

### Aircraft Codes

HIFR Capable, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Medium range recovery helicopter. 39 surviving HH-60J airframes received upgraded avionics and operational capabilities, including armaments, from 2007 to 2014. Three SH-60Fs were converted to MH-60T specifications as attrition replacements.

### Sources

https://en.wikipedia.org/wiki/Sikorsky_MH-60_Jayhawk
https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Acquisitions-CG-9/Programs/Air-Programs/MRR-MH-60T/
https://www.military.com/equipment/mh-60-jayhawk
https://www.homelandsecurity-technology.com/projects/mh-60t-medium-range-recovery-helicopter/
https://www.navalnews.com/naval-news/2021/07/u-s-coast-guard-orders-five-additional-new-mh-60t-hulls-from-sikorsky/

![images](https://user-images.githubusercontent.com/99599482/154349450-527abeee-d451-4cfb-b0f9-2653c50b75d8.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 493.
