### ISSUE TITLE
Japan, FAJ,  anti-torpedo decoy

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1580]
### DB Selector

DB3K

### Baseline

CANTO (Weapon ID 3762)

### Hypothetical

No

### Name

FAJ (stands for "Floating Acoustic Jammer")

### Length (m)

1.38

### Width/Span (m)

= diameter

### Diameter (m)

0.13

### Weight (kg)

25

### Range (nm)

0.5

### Warhead

N/A

### Targets

Surface Vessel

### Sensors

N/A

### Comments

Anti torpedo Decoy launched from Akizuki (ID 2293), Asahi (ID 3128), Izumo (ID 3619, 2442) class.
FAJ Launcher has 4x FAJ, each ships have one FAJ launcher.

### Sources

https://minkara.carview.co.jp/image.aspx?src=https%3a%2f%2fcdn.snsimg.carview.co.jp%2fminkara%2fuserstorage%2f000%2f052%2f003%2f911%2fc0a503040e.jpg?ct=72c8340e13fb

**Comment by KC45jp** [comment]
Teruzuki (akizuki) class, added for 07 VLA have one, too.
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1326

**Comment by PygmalionOfCyprus** [comment]
Added 496 and applied to listed ships.
