### ISSUE TITLE
Japan, MOD, anti-torpedo decoy

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1581]
### DB Selector

DB3K

### Baseline

None

### Hypothetical

No

### Name

MOD (stands for Mobile Decoy)

### Length (m)

1.60

### Width/Span (m)

=diameter

### Diameter (m)

0.152

### Weight (kg)

25.6

### Range (nm)

max 3-4 nm?

### Warhead

None

### Targets

Torpedo

### Sensors

None

### Comments

Torpedo decoy vehicle. once launched, it deceive torpedo and guide it to safe zone, so this may add as expendable decoy or decoy vehicle.

2x MOD stored in MOD launcher.
Equipped by Akizuki (ID 2293), Asahi (ID 3128), Izumo (ID 3619, 2442) class.
Teruzuki (akizuki) class, added for 07 VLA have one, Ship ID 3862.

### Sources

https://twitter.com/yankeesierra00/status/1129732751387746306/photo/1

http://www.pcpulab.mydns.jp/main/images/mod.jpg

**Comment by PygmalionOfCyprus** [comment]
Seems like there are four tubes for the MOD launcher? At least based on pic 3 in that Twitter post.

**Comment by KC45jp** [comment]
Yep, that's typo. 4x stored in a launcher

**Comment by PygmalionOfCyprus** [comment]
Added 496 and applied to listed ships.
