### ISSUE TITLE
Japan, DDG 180 Haguro [Maya], 2021

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1583]
### DB Selector

DB3K

### DBID to Copy

DDG 179 Maya (SHIP ID 3211)

### Hypothetical

No

### Name

DDG 180 Haguro [Maya]

### Country

Japan

### Service

Navy

### In Commission

2021

### Sensors

None

### Mounts

Exchange 2x SSM-1B Quad to 2x SSM-2 [Type 17] (mount ID 3361) launcher.

### Loadout Options

N/A

### Other Changes

COMMUNICATION
SSM-2 datalink

Maya and Haguro use different SSM,and Haguro use newer SSM-2.
BTW... Maya class does not have ECM... 
delete NOLQ-2[ECM] 

### Sources

https://ja.wikipedia.org/wiki/17%E5%BC%8F%E8%89%A6%E5%AF%BE%E8%89%A6%E8%AA%98%E5%B0%8E%E5%BC%BE

https://twitter.com/hunini181202/status/1441972855227387909

**Comment by PygmalionOfCyprus** [comment]
Added 496. Plus removed ECM from the Mayas.
