### ISSUE TITLE
DDG 177, Atago, correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1585]
### DB Selector

DB3K

### Affected DBID(s)

SHIP ID 1748, 1838, 3046

### Summary of Changes

For all Atago class,

Mount
VLS cell
29 → 32 cell
61→ 64 cell

Sensor
SQS-53C(sensor ID 1381) instead of OQS-102

Atago class, 2007 version
J/OPS-28E (Requested as #1588)  instead of J/OPS-28C

Atago class 2008 version should convert to 2017. Because Atago class got BMD update in 2017.
Atago 2017 version
delete J/OPS-28 and exchange it with AN/SPQ-9B(Sensor ID 2314)
delete OQR-2 and exchange it with AN/SQR-20 (Sensor ID 6099)

### Sources

https://ja.wikipedia.org/wiki/%E3%81%82%E3%81%9F%E3%81%94%E5%9E%8B%E8%AD%B7%E8%A1%9B%E8%89%A6

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
