### ISSUE TITLE
Japan, DD 119 Asahi, 2019

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1587]
### DB Selector

DB3K

### DBID to Copy

Asahi (Ship ID 3128)

### Hypothetical

No

### Name

DD 119 Asahi

### Country

Japan

### Service

Navy

### In Commission

2019

### Sensors

delete J/OPS-10 (delete from 2018 version, too, plz. because it does not exist)
add 4x J/OPS-48 #1586 

### Mounts

following Weapon added to this unit
#1543 Type12
Type 12 for HOS303 Torpedo Tube. But HOS 303 still can use Type 97 and Mk46.
#1326 07VLA
#1353 Type 97
#1580  FAJ
#1581  MOD

### Sources

https://twitter.com/crazyquail_BT/status/1282556274400354304
https://ja.wikipedia.org/wiki/%E3%81%82%E3%81%95%E3%81%B2%E5%9E%8B%E8%AD%B7%E8%A1%9B%E8%89%A6_(2%E4%BB%A3)

**Comment by KC45jp** [comment]
sorry, This is not Hypothetical unit

**Comment by PygmalionOfCyprus** [comment]
Shouldn't we make a new entry for Shiranui instead? Seems like she has the new gizmos but I don't think Asahi has been upgraded yet (would be quite a lot to install just a year after commissioning)...

**Comment by KC45jp** [comment]
OK, that is true but there is a reason I did not make request as separate unit.
 I needed to add more sources; actually Asahi got OPS-48 in 2019. 
https://twitter.com/faceoff1103/status/1100925575143686145
As shown in tweeted picture, DD 119 Asahi equipped Radar.

Shiranui is in commission in 2019, thus I do not think we need separate unit although Shiranui got the radar first.

**Comment by PygmalionOfCyprus** [comment]
Oh, brilliant. In that case, I agree.

**Comment by PygmalionOfCyprus** [comment]
Added 496.
