### ISSUE TITLE
J/OPS-28E, Radar

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1588]
### DB Selector

DB3K

### Baseline

J/OPS-28D 3576

### Hypothetical

No

### Name

J/OPS-28E

### Sensor Generation

Late 1990s

### Range (nm)

110

### Sensor Capabilities

Air Search, Surface Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Pulse Doppler Radar (Full LDSD Capability), Frequency Agile

### Search/Track Frequencies

G Band (4-6 GHz) [Old C Band] 5-7.5 cm

### Scan Interval (s)

2

### Comments

G band, IFF identification, Frequency Agile

Used by Atago(2007ver, SHIP ID 1748)

### Sources

https://ja.wikipedia.org/wiki/OPS-28

**Comment by PygmalionOfCyprus** [comment]
Added 495.
