### ISSUE TITLE
Standard Missile 6 (SM-6) Speed Too Slow

### ISSUE THREAD

**Issue by KJohnston11** [PygmalionOfCyprus/cmo-db-requests#1589]
### DB Selector

DB3K

### Affected DBID(s)

3772, 3714

### Summary of Changes

A GAO report on Dept. of Defense hypersonic missile programs states the SM-6 Blk IB as being a hypersonic missile (Mach 5+) capable of air and surface attacks. Currently, the SM-6 Blk IB is sitting at cruise speed at roughly Mach 4.6. Is Mach 4 the baseline for hypersonic in the DB, or can this be changed to reflect the GAO report?

Changed entries:

Cruise speed Mach 3.82/4.62 --> Mach 5.XX 

### Sources

![image](https://user-images.githubusercontent.com/108648489/177085158-c298d177-7ba1-4881-9562-40f9a51da04f.png)

https://www.gao.gov/assets/gao-21-378.pdf (p. 12 of document)

**Comment by PygmalionOfCyprus** [comment]
If there's a "baseline" for hypersonic speed short of Mach 5 no one ever told me. I've tweaked the engine on the SM-6 Blk 1B to push it over the edge at optimum altitude. (This is almost certainly a significant under-model, but I don't want to seesaw too far in the opposite direction.)
