### ISSUE TITLE
Add USCG MH-65C Dolphin

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#159]
### DB Selector

DB3K

### Hypothetical

No

### Name

MH-65C Dolphin

### Country

United States

### Service

Coast Guard

### In Commission

2008-Present

### Length (m)

As DBID 1858 HH-65A

### Wingspan (m)

As DBID 1858 HH-65A

### Height (m)

As DBID 1858 HH-65A

### Empty Weight (kg)

As DBID 1858 HH-65A

### Maximum Takeoff Weight (MTOW) (kg)

As DBID 1858 HH-65A

### Payload Weight (kg)

As DBID 1858 HH-65A

### Crew

3

### Propulsion

As DBID 1858 HH-65A

### Rate of Climb (ft/min)

As DBID 1858 HH-65A

### Service Ceiling (ft)

As DBID 1858 HH-65A

### Military/Afterburner Speed (kt)

As DBID 1858 HH-65A

### Cruise Speed (kt)

As DBID 1858 HH-65A

### Supercruise

No

### Ferry Range (nm)

As DBID 1858 HH-65A

### Endurance (min)

As DBID 1858 HH-65A

### Takeoff / Landing Distance (m)

As DBID 1858 HH-65A

### Fuel Capacity (kg)

As DBID 1858 HH-65A

### Sensors

As DBID 1858 HH-65A and DBID 2051 MH-68A

### Mounts

1x 7.62mm LMG
1x 12.7mm Anti-Material Sniper rifle

### Loadout Options

As DBID 1858 HH-65A and DBID 2051 MH-68A

### Comms/Datalinks

As DBID 1858 HH-65A and DBID 2051 MH-68A

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

HH-65 upgrades replaced the MH-68A in HITRON use from 2008 with MH-67C. 1 7.62mm LMG and 1 12.7mm anti-material rifle

### Sources

https://en.wikipedia.org/wiki/Eurocopter_MH-65_Dolphin
https://en.wikipedia.org/wiki/Helicopter_Interdiction_Tactical_Squadron
https://www.helis.com/database/sqd/HITRON/
https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Acquisitions-CG-9/Programs/Air-Programs/SRR-MH-65/

![download](https://user-images.githubusercontent.com/99599482/154349729-c6da14ce-b088-4349-a9dc-f638837c6293.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added. It clearly has a radar, but I can't figure out what it is. For now, I've given it the AN/APN-215 as with the MH-60T.
