### ISSUE TITLE
RIM-174A ERAM SM-6 Blk IB Never Connects w/ Surface Target (Ship)

### ISSUE THREAD

**Issue by KJohnston11** [PygmalionOfCyprus/cmo-db-requests#1590]
### DB Selector

DB3K

### Affected DBID(s)

3772, 3714

### Description of Problem

Firing the SM-6 Blk IB at a surface vessel, the missile seems to land consistently short of target by almost 10m, or about 30 feet. The missile has onboard radar (ARH) as well as a two way datalink for midcourse updates. a miss of that distance seems outlandish to me, especially when it happens at a 100% rate! I believe it may be a bug :)

### Recommended Fix

Check out the SM-6 Blk IB and fix the massive misses it has (or don't, if it's a legitimate feature and I am just unaware!)

**Comment by PygmalionOfCyprus** [comment]
Well, they don't call it a "hittile," now do they?

Jokes aside, this is obviously not WAD (even if you were extraordinarily unlucky the Blk IBs have a CEP of 4m, so you really shouldn't be out at 10m 100% of the time. You're likely right that this is a bug; however, as there's nothing technically wrong in the DB (at least so far as I can tell) you'll need to go post in the Tech Support forum -- with a save -- so it can get handled appropriately.
