### ISSUE TITLE
South Korean Navy Type 214 submarine request

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#1591]
### DB Selector

DB3K

### Affected DBID(s)

420, 669, 670

### Summary of Changes

Minor weirdness, not critical
South Korean Type 214 have 2x and 6x torpedo launchers. I do not know why, but while other Type 214 class have 8x torpedo launchers, I believe this is a bug.

Bug became bit critical for 2020 version (ID 670). This class can load Harpoon, White Shark, and Tiger Shark for any torpedo launcher, not only 2 tube can shoot white shark nor other 6 can shoot Tiger Shark. Type 214 Magazine should able to hold all three types of weapon.

### Sources

https://en.wikipedia.org/wiki/SUT_torpedo

https://www.naval-technology.com/projects/type_212/

**Comment by KC45jp** [comment]
overlapped with this request
 #1584

**Comment by PygmalionOfCyprus** [comment]
This one has sources, so I'll close the OG and treat this as the parent.

**Comment by PygmalionOfCyprus** [comment]
Can you clarify what you mean by "Type 214 have 2x and 6x torpedo launchers [...] while other Type 214 class have 8x torpedo launchers"? The SK 214s look to me like they have 8x torpedo tubes just like every other Type 214.

**Comment by KC45jp** [comment]
In SK one, it has separate 2x tube and 6x tube as mount while other 214 have one 8x tube as mount. 
This is not big deal in most of the SK type 214, but In 2020 one, the 2x tube and 6x tube can shoot different torpedo where they should can shoot both of White and Tiger shark (and Harpoon).

**Comment by PygmalionOfCyprus** [comment]
AHA, I see what you mean.

The tubes are identical, it's just that 2x of them come with the Harpoons pre-loaded and the other 6x come with torpedos already in the tube. It's not a bug so much as attempting to reflect a more realistic "cruise load."

I do, however, note the point about those 2x tubes not having been updated on the 2020 variant. Fixed for 496. I've also given them the ability to shoot White Shark torpedoes if the Tiger Shark isn't available, and fixed the magazines.

**Comment by KC45jp** [comment]
thx
