### ISSUE TITLE
Correction to max depth/nomenclature and acoustic signature of Type 093 aka SHANG I submarine (China)

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1592]
### DB Selector

DB3K

### Affected DBID(s)

Submarine_164

### Summary of Changes

The Type 093 is denoted as the "SHANG I" by NATO, vice merely "SHANG" .  See OSD "Report to Congress, May 2021" at page 49, located here: https://media.defense.gov/2021/Nov/03/2002885874/-1/-1/0/2021-CMPR-FINAL.PDF   Additionally, the maximum depth is denoted as -300 meters in the database.  However, https://www.military-today.com/navy/shang_class.htm gives the depth as -400 meters, which is more likely, as the 1970's era VICTOR III SSN has a 400 meter max depth in the database, despite being 30 years older than the SHANG I.  (see https://www.military-today.com/navy/victor_iii_class.htm).

Finally, the acoustic signature of the SHANG I is reported by ONI to be louder than the VICTOR III. In the game, the VICTOR III has a 110 db, so the SHANG should be 115 or 120 db.  See https://irp.fas.org/agency/oni/pla-navy.pdf on page 22.

### Sources

https://media.defense.gov/2021/Nov/03/2002885874/-1/-1/0/2021-CMPR-FINAL.PDF
https://www.military-today.com/navy/shang_class.htm
 https://irp.fas.org/agency/oni/pla-navy.pdf  **( page 22).**

**Comment by CV60LCC19** [comment]
One other possible source: https://digital-commons.usnwc.edu/nwc-review/vol60/iss1/6/ at page 67 gives the SHANG I a noise signature of 110 db, but cites unnamed Chinese sources for this data.  However, this articles, while in a professional journal, is dated 2007.  Based on that, I would still go with the 2017 ONI report at https://irp.fas.org/agency/oni/pla-navy.pdf , and increase its signature.

**Comment by PygmalionOfCyprus** [comment]
Is it fair to assume, based on this, that the "Shang I" is therefore designated the "Type 039A" and the Type 039B is the "Shang II"?

**Comment by PygmalionOfCyprus** [comment]
At any rate, updated 496; I also adjusted the max depth on the Type 039Bs (since it doesn't make sense that they'd be less capable in that regard than their predecessor) but kept them at ~110 dB since they're reportedly quieter than the Shang Is.

**Comment by CV60LCC19** [comment]
Thanks for updating the Shang II.  Reviewing them was going to be my project today.  In my very quick look of the database, the other PLA submarines seemed to generally track the relative noise signatures in the 2017 ONI report.  However, I want to drill down a bit more on that.
