### ISSUE TITLE
Nike Hercules SSM Mission

### ISSUE THREAD

**Issue by TestPilotKerman** [PygmalionOfCyprus/cmo-db-requests#1593]
### DB Selector

Both

### Affected DBID(s)

1645

### Summary of Changes

The nuclear variant of the Nike Hercules (MIM-14) should be able to strike surface targets up to 114 miles from the launcher.

### Sources

http://ed-thelen.org/CraneClinton-HerculesWarheadSectionRev01.pdf
https://nikemissile.org/capabilities.shtml
http://ed-thelen.org/TM9-1440-250-10-1.html
http://ed-thelen.org/NikeMissions.html
http://ed-thelen.org/TM9-1440-250-10-2-Dec1960-7.pdf
http://www.astronautix.com/n/nikehercules.html
http://www.themilitarystandard.com/missile/nike/overview.php

**Comment by PygmalionOfCyprus** [comment]
Added to nuclear MIM-14 in CWDB.
