### ISSUE TITLE
Portugal Baptiste de Andrade Frigate

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1596]
### DB Selector

DB3K

### Affected DBID(s)

DB3K: 1243, 2052, 1732 CWDB: 1105

### Summary of Changes

All sources that I could find show Baptiste de Andrade Frigate at F 486 and not F 487 as noted in the DB's.

### Sources

Jane's 2003-04, pg. 559
Combat Fleets of the World, 16th Edition, page 552
https://en.wikipedia.org/wiki/Baptista_de_Andrade-class_corvette (referencing Conway's 1947-95)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
