### ISSUE TITLE
Portugal Bombarda Class LCU x3

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1597]
### DB Selector

DB3K

### DBID to Copy

DB3k 2106

### Hypothetical

No

### Name

LDG 201 Bombarda

### Country

Portugal

### Service

Navy

### In Commission

1985-2014

### Number in Service

1x

### Sensors

- 1x Decca RM 316P

### Mounts

- 2x single 20mm/70 Oerlikon AA

### Other Changes

- Based on French EDIC class, 350t cargo
- LDG 105 Bombarda (1975-LDG 201) discarded 1997
- LDG 106 Alabarda (1975-LDG 202) discarded 1997
- LDG 203 Bacamarte completed in 1985-2014

### Sources

https://web.archive.org/web/20170708203957/http://navypedia.org/ships/portugal/pr_ls_bombarda.htm
https://www.wikiwand.com/pt/Classe_Bombarda
Jane's 2003-04, pg 561
Combat Fleets of the World, 16th Edition, pg 554

![1661083](https://user-images.githubusercontent.com/99632305/177211991-d3a5abf7-19fb-4374-8b47-8b1778b1025c.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
