### ISSUE TITLE
Japan, DD 116 Teruzuki, correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1598]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3862

### Summary of Changes

Mount
HOS 303: add Type 97 capability
Magazine
Type 97 external tube

same as this change
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1353

### Sources

https://en.wikipedia.org/wiki/Type_97_light_weight_torpedo_(G-RX4)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
