### ISSUE TITLE
Add USCG HH-65B/C and MH-65D/E Dolphin

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#160]
### DB Selector

DB3K

### Hypothetical

No

### Name

HH-65B/C and MH-65D/E Dolphin

### Country

United States

### Service

Coast Guard

### In Commission

HH-65B (2001-)/C (2004-) and MH-65D (2011-)/E (2017-) Dolphin

### Length (m)

As DBID 1858 HH-65A

### Wingspan (m)

As DBID 1858 HH-65A

### Height (m)

As DBID 1858 HH-65A

### Empty Weight (kg)

As DBID 1858 HH-65A

### Maximum Takeoff Weight (MTOW) (kg)

As DBID 1858 HH-65A for 65B, 4,300 kg from HH-65C on

### Payload Weight (kg)

As DBID 1858 HH-65A

### Crew

As DBID 1858 HH-65A

### Propulsion

2x Arriel 2C2-CG 

### Rate of Climb (ft/min)

As DBID 1858 HH-65A

### Service Ceiling (ft)

As DBID 1858 HH-65A

### Military/Afterburner Speed (kt)

As DBID 1858 HH-65A

### Cruise Speed (kt)

As DBID 1858 HH-65A

### Supercruise

No

### Ferry Range (nm)

As DBID 1858 HH-65A

### Endurance (min)

As DBID 1858 HH-65A

### Takeoff / Landing Distance (m)

As DBID 1858 HH-65A

### Fuel Capacity (kg)

As DBID 1858 HH-65A

### Sensors

As DBID 1858 HH-65A plus

HH-65B/C, MH-65D - NVGs

MH-65E - Digital Weather Radar

### Mounts

HH-65 B/C as HH-65A

MH-65D/E as MH-65C, MH-60T, MH-68A, MH-90

1x 7.62mm LMG
1x 12.7mm Anti-material sniper rifle

### Loadout Options

As DBID 1858 HH-65A

### Comms/Datalinks

As DBID 1858 HH-65A plus

MH-65D - as MH-65C

MH-65E - As MH-60T

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

HH-65 upgrades in use from 2001 for HH-65B, 2004 for HH-65C, 2011 for MH-65D, and 2017 for MH-65E. Upgraded lift/cargo capabilities and sensors

### Sources

https://en.wikipedia.org/wiki/Eurocopter_MH-65_Dolphin
https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Acquisitions-CG-9/Programs/Air-Programs/SRR-MH-65/
https://www.naval-technology.com/projects/hh65-dolphin/
https://www.airbus.com/us/en/helicopters/military-helicopters/mh65.html
https://www.helis.com/database/news/mh-65e_rss/
https://www.militaryaerospace.com/computers/article/16718628/coast-guard-chooses-weather-radar-from-rockwell-collins-for-future-mh65e-utility-helicopters
https://www.flightglobal.com/helicopters/us-coast-guard-mh-65-helicopter-upgrades-start-full-rate-production/136329.article
https://www.nhahistoricalsociety.org/coast-guard-hh-65a-mh-65c-d-e-dolphin-helicopter/
https://verticalmag.com/news/u-s-coast-guard-prepares-mh-65e-upgrade/

![download](https://user-images.githubusercontent.com/99599482/154349893-ece09600-7b43-4b7c-8958-3ba3fe4cb07c.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 493.
