### ISSUE TITLE
Romania Tarantul I, Pr.1241E x3

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1600]
### DB Selector

DB3K

### DBID to Copy

DB3k 2174

### Hypothetical

No

### Name

188 Zborul

### Country

Romania

### Service

Navy

### In Commission

1990-

### Number in Service

3x

### Sensors

- 1x Kivach-2 nav
- 1x Garpun-E (Plank Shave) E-band
- 1x MR-123 Vympel (Bass Tilt) H band
- 1x Spin Trough I band
- 1x Hood Wink
- 2x Watch Dog (ESM) intercept

### Mounts

- 4x P20/21 Termit(SS-N-2C Styx)
- 1x 76.2mm/59 AK-176 DP
- 1x 4 round MTU-40S (SA-N-8) SAM system (x12 Strela 9K-32m)
- 2x single 30mm/54 AK-630 gatling AA
- 2x PK 16 chaff

### Other Changes

Jane's noted similar to those built for Poland, India and Yemen

### Sources

Combat Fleets of the World, 16th Edition, page 561
Jane's 2003-04, page 569

![download](https://user-images.githubusercontent.com/99632305/177215326-49863c3e-8ef4-4bae-8701-d690b5a71f0b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
