### ISSUE TITLE
Romania OSA I, Pr.205 Fast Attack x6

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1601]
### DB Selector

DB3K

### DBID to Copy

CWDB 1823

### Hypothetical

No

### Name

194 Soimul

### Country

Romania

### Service

Navy

### In Commission

1964-2004

### Sensors

- 1x Square Tile I band (Surface search)
- 1x Drum Tilt H/I band (f.c.)
- 1x High Pole IFF
- 1x Square Head IFF

### Mounts

- 4x SS-N-2 Styx
- 2x twin 30mm/65

### Other Changes

- 3x stricken 1997, 3x stricken 2004

### Sources

https://web.archive.org/web/20170708172719/http://navypedia.org/ships/romania/ro_cf_vpr70.htm
Janes 2003-04, page 570

**Comment by PygmalionOfCyprus** [comment]
Added 496.
