### ISSUE TITLE
Japan, FFM-1 Mogami

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1603]
### DB Selector

DB3K

### Affected DBID(s)

SHIP 3292

### Summary of Changes

Can I ask to remove hypothetical tag from this unit, as I requested in #1376? 

### Sources

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1376

**Comment by PygmalionOfCyprus** [comment]
Oof, sorry. I must have forgotten while handling all the other stuff in #1376. Fixed for 496. (For real this time!)
