### ISSUE TITLE
Bf 110 Changes

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#1605]
### DB Selector

CWDB

### Affected DBID(s)

#3868

### Summary of Changes

The Messerschmidt Bf 110 C-4 in the DB currently has 5000x 50 rnd 7.92mm Single MG Bursts, 1000 bursts per gun for an unlikely total of 250,000 rounds. It's an unfortunate mix-up between rounds per gun (1000x) and bursts per gun (20x).
![Bf110 DB Mounts](https://user-images.githubusercontent.com/101542189/177253114-d4b2e727-5c77-4842-a345-9abc724e758d.jpg)
Please change to 20 bursts per 7.92mm MG mount.

I also believe the rear mounted turret, at least in the C-4, only had 1 MG, with 4 forward firing, whereas currently there is three  forward firing and two in the turret. I think the turret MG only had 750x rnds, unlike the forward four with 1000x.

The C-4 had twin MG FF/Ms, not MG-151s, but that's really semantics. They did have 360x rnds, consisting of three 30x rnd drums per gun, for a total of 360x rnds. They currently have six 50x rnd bursts in the DB to give 300x rnds. Maybe add a seventh burst just to make it closer.

The propulsion section also lists 2x 2 x Daimler-Benz DB-601 #1. Just a minor detail, I'm assuming only one of those 2x's is meant to be there. I'm not sure if that has also affected the rest of the propulsion on it.
 
![Bf110 DB Propulsion](https://user-images.githubusercontent.com/101542189/177258884-7e5c82c2-25f5-47ad-8e22-295bfa53d21e.jpg)

The main distinguishing feature of the C-4 from the earlier models was its' armoured cockpit, while there currently isn't any armour on it  now. I'm not sure if that's something completely necessary to change.

Finally the C-4 variant would not have been equipped with 900 liter/230 US gallon drop tanks. Drop tanks for the 110 were only introduced with the D-1 variant. Even more technically, the C-4s with bomb racks would be called a C-4/B. 

### Sources

https://en.wikipedia.org/wiki/Messerschmitt_Bf_110
https://weaponsandwarfare.com/2018/05/02/messerschmitt-bf-110-c-and-d/

**Comment by 52Novembers** [comment]
The Focke-Wulf Fw 190 A-8 (DBID #3842) also has an issue with its weapons, having 950x 13mm MG 50x rnd bursts

**Comment by PygmalionOfCyprus** [comment]
Fixed for 496 (and renamed to C-4B to indicate its bomb loadouts). Also fixed the FW. If this wasn't a rump WW2 AC I'd build out the other variants, etc. but WW2 stuff is a hole I definitely don't want to get sucked down.
