### ISSUE TITLE
South Korea, DDG 991 Sejong Daewang KDX 3

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1607]
### DB Selector

DB3K

### Affected DBID(s)

SHIP 2168, 2386

### Summary of Changes

Mount
KDX3 has 48cell+ 32cell(=80vell) of Mk41 AND  48 cells of K-VLS. Total of 128 cells (Wow).
In DB, we have 2x Mk41 VLS(48 cells) = bit too many, so need to remove one and replaced by 32cell one.

### Sources

https://www.defenseindustrydaily.com/drs-wins-multiplexing-contract-for-korean-aegis-destroyers-0431/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 496.
