### ISSUE TITLE
YJ-21 performance

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1611]
### DB Selector

DB3K

### Affected DBID(s)

weapon #4059

### Description of Problem

1. [SM-6 interception problem] 
1.1 The weapon travels at a speed where sm-6 blk1a/1B/dual 1 should not be able to intercept it. However, the latter did engage the former
1.2 When the weapon entered SM-6's ARH range, the game stuck (like some programs collapsed）

2. [mult-targets engagement]
When performing a salvo against multipule targats, the game sometimes stuck.

3. [ballistic-like trajectory and miss the target]
The weapon sometimes travels in a trajectory like a ballistic missile and then it flies over the target and miss it.

More to be added

### Recommended Fix

I assumed it is an already existed HGV weapon simulation bug, isn't it?

**Comment by PygmalionOfCyprus** [comment]
Not a DB issue (to my knowledge). Please post with a save in the Tech Support forum so that it can be handled appropriately.
