### ISSUE TITLE
ZQS-4, sonar

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1612]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 4693

### Summary of Changes

ZQS-4 is not VDS, it is hull sonar.= thus not a copy of AN/SQQ-32.
likely early 2000 tech because Hirashima class (first class using this sonar) is in commission from 2008.

### Sources

https://www.mod.go.jp/msdf/mf/2md/takashima/img/image6.png

**Comment by PygmalionOfCyprus** [comment]
Fixed for 496.
