### ISSUE TITLE
J/OQQ-10, sonar

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1613]
### DB Selector

DB3K

### Baseline

ZQS-4 Sensor ID 4693

### Hypothetical

No

### Name

J/OQQ-10

### Sensor Generation

Early 2010s

### Range (nm)

0.5

### Sensor Capabilities

Mine & Obstacle Search

### Search/Track Frequencies

HF Sonar (10-500 KHz, 20 KHz Center Frequency)

### Scan Interval (s)

15

### Comments

Used by Awaji class[Ship ID 304] instead of ZQS-4.
Modified, VDS version of ZQS-4 as requested in #1612 .

Deep search capable for finding mines targeting submarines. 

### Sources

https://ssl.bsk-z.or.jp/kenkyucenter/pdf/HITACHI031129.pdf

**Comment by PygmalionOfCyprus** [comment]
Added 496 (and added/replaced ZQS-4 on Awaji).
