### ISSUE TITLE
Japan, MSC 681 Sugashima

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1614]
### DB Selector

DB3K

### Affected DBID(s)

Ship 843

### Summary of Changes

Sensor
--------------------------
Remove ZQS-4
add Type 2093

you can delete the comment, (J/ZQS-3) in Type 2093.
ZQS series are sonars based on Type 193M.

### Sources

https://ja.wikipedia.org/wiki/%E3%81%99%E3%81%8C%E3%81%97%E3%81%BE%E5%9E%8B%E6%8E%83%E6%B5%B7%E8%89%87

**Comment by PygmalionOfCyprus** [comment]
Fixed for 496.
