### ISSUE TITLE
Thailand - Hermes 450 UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1618]
### DB Selector

DB3K

### DBID to Copy

DBID #5101

### Hypothetical

No

### Name

Hermes 450 UAV

### Country

Thailand

### Service

Royal Thai Army

### In Commission

2017-Present

### Number in Service

4x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.shephardmedia.com/news/uv-online/thai-army-flying-hermes-450/

https://www.ainonline.com/aviation-news/defense/2018-06-25/thailand-introduces-elbits-hermes-450-uas

https://www.armyrecognition.com/defense_news_april_2022_global_security_army_industry/royal_thai_army_demonstrates_hermes_450_uav.html

https://www.asiapacificdefensejournal.com/2022/07/hailand-selects-elbit-systems-hermes.html?fbclid=IwAR3JJxhxUAzCYRBwm7pF6XckZejbYDCYKjAnxPcx0aAAtau8cEAt8m9O1_A

![image](https://user-images.githubusercontent.com/99599482/177551196-00d6b06c-28b8-490c-909b-c3133ae0956f.png)

**Comment by PygmalionOfCyprus** [comment]
Added 496.
