### ISSUE TITLE
Armenia - Orlan-10 UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1619]
### DB Selector

DB3K

### DBID to Copy

Orlan-10 UAV -- Russia [1992-] (Army), 2010

### Hypothetical

No

### Name

Orlan-10 UAV 

### Country

Armenia

### Service

Air Force

### In Commission

IOC Unknown, Used 2021

### Number in Service

uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 496.
