### ISSUE TITLE
Add BLU-137/B 2000lb penetrator warhead for modified GBU-31 JDAM kit

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#162]
### DB Selector

DB3K

### Hypothetical

No

### Name

GBU-31 JDAM (BLU-137/B 2000lb penetrator warhead)

### Length (m)

As DBID 89

### Width/Span (m)

As DBID 89

### Diameter (m)

As DBID 89

### Weight (kg)

As DBID 89

### Range (nm)

As DBID 89

### Target Altitude / Depth (ft)

As DBID 89

### Launch Altitude / Depth (ft)

As DBID 89

### Warhead

2000lb penetrator

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway

### CEP (m)

As DBID 89

### Sensors

As DBID 89

### Weapon Codes

Weapon - INS w/ GNSS Navigation

### Comments

Updated penetrator warhead with modified JDAM tail assembly for greater reliability

### Sources

https://www.thedrive.com/the-war-zone/11871/the-u-s-air-force-wants-to-buy-more-reliable-bunker-buster-bombs
https://insidedefense.com/insider/air-force-looking-increase-production-quantities-blu-137b-penetrator-bombs
https://www.aerodefensetech.com/component/content/article/adt/features/articles/38531
https://www.saffm.hq.af.mil/Portals/84/documents/FY22/PROCUREMENT_/FY22%20DAF%20J-Book%20-%203011%20-%20Ammunition%20Proc.pdf?ver=PaFt7rWf7aiKYJhI-cpv9w%3D%3D

**Comment by PygmalionOfCyprus** [comment]
Handled 501 and added loadouts for 2018+ F-15Es and B-52s.
