### ISSUE TITLE
Skynight SPECOPS Drop

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1622]
### DB Selector

CWDB

### User(s)

USMC F3D/F-10 Skynights

### Weapons Carried

Internal Guns
1x SPECOPS Paratroop

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

430nm w/o tanks, 560nm w/ tanks

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Skyknights would each carry a Marine reconnaissance commando instead of an AIO, dropping them behind enemy lines in a clandestine night-time insertion.

### Sources

https://www.thedrive.com/the-war-zone/40452/with-no-ejection-seats-skyknight-fighter-crews-slid-down-a-tunnel-to-salvation?fbclid=IwAR3EVaxC3JwuQg9GcJjcjS66saWaE3keLmHJX_NcJZhE_SMxM9zAN1ls-wE

**Comment by PygmalionOfCyprus** [comment]
Added 496.
