### ISSUE TITLE
Mi-2 gunships have pure AA cannon only

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#1624]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 1500 1502

### Summary of Changes

The Mi-2US (Aircraft 1500 ) and Mi-2URP have a purely air-to-air version of the 23mm gun (Weapon 380 ). They only share this with the IL-76's tail gun. A ground or general purpose one like Weapon 197 would make more sense. 

### Sources

https://www.armedconflicts.com/Mil-Mi-2US-Kod-NATO-Hoplite-t218732

**Comment by PygmalionOfCyprus** [comment]
Fixed for 496.
