### ISSUE TITLE
Falco UAV - Jordan, Turkmenistan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1626]
### DB Selector

DB3K

### DBID to Copy

DBID #4382

### Hypothetical

No

### Name

Falco UAV

### Country

Jordan, Turkmenistan

### Service

Air Force

### In Commission

2010-2018 (Jordan), 2011-Present (Turkmenistan)

### Number in Service

4x, @x Lost (Jordan), 3x Turkmenistan,

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Selex_ES_Falco
https://www.army-technology.com/news/news70843-html/
https://www.oryxspioenkop.com/2022/01/operational-failure-ch-4bs-short-lived.html
https://www.oryxspioenkop.com/2022/02/turkmenistans-path-to-drone-power.html
https://www.oryxspioenkop.com/2021/09/snaps-from-ashgabat-turkmenistans-2021.html
https://www.oryxspioenkop.com/2021/12/Berdimuhamedow-birds-of-prey-italian.html

![image](https://user-images.githubusercontent.com/99599482/177600519-6bc3eb70-e86e-46da-a8bd-a3b3a3a1aef9.png)
![image](https://user-images.githubusercontent.com/99599482/177600825-0b640a02-508b-4b2f-866a-63c442d5909a.png)

**Comment by PygmalionOfCyprus** [comment]
Added 496.
