### ISSUE TITLE
KDC-10 - Omega Air Refueling

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1627]
### DB Selector

DB3K

### DBID to Copy

DBID #3861

### Hypothetical

No

### Name

KDC-10

### Country

Commerical

### Service

Omega Air Refueling

### In Commission

2019-Present

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

In 2019, Omega agreed to purchase the Netherlands' two KDC-10s, with one being received in November 2019, and the second delivered in October 2021.

These differ from DBID #4886 KDC-10 conversions used by Omega and Global Airtanker which only have drogues.

### Sources

https://www.thedrive.com/the-war-zone/31168/the-first-boom-equipped-tanker-for-a-private-aerial-refueling-company-has-arrived
https://en.wikipedia.org/wiki/McDonnell_Douglas_KC-10_Extender#Netherlands

![image](https://user-images.githubusercontent.com/99599482/177605226-e04c25eb-bc1f-403a-87e5-5a91e8ae29be.png)

**Comment by PygmalionOfCyprus** [comment]
Added 496.
