### ISSUE TITLE
U-2 BACN Loadout

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1628]
### DB Selector

DB3K

### User(s)

U-2S

### Weapons Carried

special communications package in Q-Bay

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

2000nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Special Communications Package for BACN operations.

### Sources

https://www.thedrive.com/the-war-zone/10500/u-2-flies-in-alaska-exercise-for-first-time-but-not-as-a-spy-plane

![image](https://user-images.githubusercontent.com/99599482/177608956-6f932d52-1962-49a6-ba02-5641999eb429.png)

**Comment by PygmalionOfCyprus** [comment]
We don't currently have any way to simulate or even place-hold BACN at this time. When ~someone pays us to~ we decide to do a comms overhaul this will definitely be something we revisit.
