### ISSUE TITLE
Add Adelaide (Upgraded O.H. Perry) FFG to Chile

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#163]
### DB Selector

DB3K

### Hypothetical

No

### Name

FFG-11 Capitan Prat

### Class

Copy DBID 2608 

### Country

Chile

### Service

Navy

### In Commission

2020-Present

### Length (m)

Copy DBID 2608 

### Beam (m)

Copy DBID 2608 

### Draft (m)

Copy DBID 2608 

### Standard Displacement (t)

Copy DBID 2608 

### Full Displacement (t)

Copy DBID 2608 

### Empty Displacement (t)

Copy DBID 2608 

### Complement

Copy DBID 2608 

### Max Sea State

Copy DBID 2608 

### Primary Propulsion Type

Gas Turbine

### Propulsion

Copy DBID 2608 

### Fuel Capacity (kg)

Copy DBID 2608 

### Flank Speed (kt)

Copy DBID 2608 

### Range (nm) at Speed (kt)

Copy DBID 2608 

### Sensors

Copy DBID 2608 

### Mounts

Copy DBID 2608 

### Aircraft & Docking Facilities

Copy DBID 2608 

### Comms/Datalinks

Copy DBID 2608 

### Ship Codes

Nuclear Shock Resistant, Degaussed Steel Hull, Prairie Masker

### Comments

Australia has officially transferred two Adelaide (Oliver Hazard Perry)-class guided-missile frigates to the Chilean Navy.

The ex-Royal Australian Navy (RAN) frigates, Melbourne (FFG 05) and Newcastle (FFG 06), were formally handed over during a ceremony held at HMAS Watson naval base in Sydney on 15 April, 2020.

Names and Hull Numbers Reused from decommissioned Jacob van Heemskerck class FFGs.

### Sources

https://www.janes.com/defence-news/news-detail/australia-transfers-adelaide-class-frigates-to-chile
https://en.wikipedia.org/wiki/HMAS_Newcastle
https://en.wikipedia.org/wiki/HMAS_Melbourne_(FFG_05)

![download](https://user-images.githubusercontent.com/99599482/154346997-8e66f462-09b9-48f7-98ee-1c778332d772.jpg)

![download](https://user-images.githubusercontent.com/99599482/154347432-d0b3746a-ea9c-4559-87e7-f3817350fc39.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 493.
