### ISSUE TITLE
Max range correction to "Low Altitude Guard II" laser

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1630]
### DB Selector

DB3K

### Affected DBID(s)

Facility_3230

### Summary of Changes

The Chinese "Low Altitude Guard II" is listed in the database as having a range of 10nm.  All sources I have found indicate its range is 4 km/2.16 nm. See https://www.globalsecurity.org/military/world/china/laser.htm; https://www.airdefence.in/weapons/low-altitude-guard-ii/.  One other possible issue: Facility_3230 does not list drones as a separate target, although that is what it is primarily used for.   Does the database model separate drones as a different target category from aircraft? 

### Sources

China sells a new laser gun. (2021, April 26). Popular Science. https://www.popsci.com/china-sells-new-laser-gun/ ; 
Low altitude guard II. (n.d.). All About Air Defence. https://www.airdefence.in/weapons/low-altitude-guard-ii/ ; 
New Chinese laser weapon stars on TV. (2021, April 26). Popular Science. https://www.popsci.com/new-chinese-laser-weapon-stars-on-tv/ ; Pike, J. (2021, April 11). 
Chinese laser weapons. GlobalSecurity.org. https://www.globalsecurity.org/military/world/china/laser.htm ;
The Chinese military now has laser weapons. (2021, December 19).

**Comment by PygmalionOfCyprus** [comment]
Fixed range for 496.

Re:
>Facility_3230 does not list drones as a separate target, although that is what it is primarily used for. Does the database model separate drones as a different target category from aircraft?

It doesn't, but the weapon in question only has WRA for UAVs, helicopters, guided weapons, and CRAM.
