### ISSUE TITLE
Czechoslovak MiG-23UB

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#1633]
### DB Selector

Both

### Baseline

2611 in DB3000 (MiG-23M)

### Hypothetical

No

### Name

MiG-23UB Flogger C

### Country

Czechoslovakia

### Service

Air Force

### In Commission

1978-1992

### Number in Service

8

### Length (m)

17.1 m - sources are inconsistent but it is longer than single seater which has 16.7 m

### Wingspan (m)

14 m (maximum swing wing)

### Height (m)

4.8 m

### Empty Weight (kg)

10920 kg

### Maximum Takeoff Weight (MTOW) (kg)

18000 kg

### Payload Weight (kg)

1600 kg - it is possible that it is more but still less than 2000 kg

### Crew

2

### Propulsion

R-27F2M-300

### Rate of Climb (ft/min)

28500 to 34500 ft - second number probably max

### Service Ceiling (ft)

51800 to 53800 ft

### Military/Afterburner Speed (kt)

max speed in height is M 2,35 (1350 kt) - in game as other limit to 920 kt

### Cruise Speed (kt)

probably like MiG-23M - MiG-23UB has less powerful engine and has slower acceleration but could probably still reach same speed

### Supercruise

No

### Ferry Range (nm)

650 to 750 nm (without drop tanks)

### Endurance (min)

no idea

### Takeoff / Landing Distance (m)

650 / 900 m

### Fuel Capacity (kg)

3520 - less fuel than MiG-23M

### Sensors

1x SPO-10 Sirena 3M

### Mounts

1x 23mm Gsh-23L [200 rnds]

### Loadout Options

* (Ferry) - 3x 800 liter Drop Tank

* AA-2 Atoll [R-3S] (Air Superiority, WVR AAMs) - 4x R-3S, 1x 800 liter Drop Tank

* AS-7 Kerry [Kh-23], Hi-Lo-Hi (Strike, Land/Naval) - 2x Kh-23, 1x 800 liter Drop Tank
* AS-7 Kerry [Kh-23], Lo-Lo-Lo (Strike, Land/Naval) - 2x Kh-23, 1x 800 liter Drop Tank

* FAB-250M-54 GPB, Hi-Lo-Hi (Strike, Land/Naval) - 4x FAB-250M-54 GPB
* FAB-250M-54 GPB, Lo-Lo-Lo (Strike, Land/Naval) - 4x FAB-250M-54 GPB
* FAB-250M-54 GPB, Hi-Lo-Hi, Long-Range (Strike, Land/Naval) - 2x FAB-250M-54 GPB, 1x 800 liter Drop Tank
* FAB-250M-54 GPB, Lo-Lo-Lo, Long-Range (Strike, Land/Naval) - 2x FAB-250M-54 GPB, 1x 800 liter Drop Tank

* FAB-500M-54 GPB, Hi-Lo-Hi (Strike, Land/Naval) - 2x FAB-500M-54 GPB
* FAB-500M-54 GPB, Lo-Lo-Lo (Strike, Land/Naval) - 2x FAB-500M-54 GPB

* FAB-500M-62 GPB, Hi-Lo-Hi (Strike, Land/Naval) - 2x FAB-500M-62 GPB
* FAB-500M-62 GPB, Lo-Lo-Lo (Strike, Land/Naval) - 2x FAB-500M-62 GPB

* OFAB-100-120 Frag, Hi-Lo-Hi (Strike, Land/Naval) - 16x OFAB-100-120 Frag
* OFAB-100-120 Frag, Lo-Lo-Lo (Strike, Land/Naval) - 16x OFAB-100-120 Frag
* OFAB-100-120 Frag, Hi-Lo-Hi, Long-Range (Strike, Land/Naval) - 8x OFAB-100-120 Frag, 1x 800 liter Drop Tank
* OFAB-100-120 Frag, Lo-Lo-Lo, Long-Range (Strike, Land/Naval) - 8x OFAB-100-120 Frag, 1x 800 liter Drop Tank

* OFAB-250-270 Frag, Hi-Lo-Hi (Strike, Land/Naval) - 4x OFAB-250-270 Frag
* OFAB-250-270 Frag, Lo-Lo-Lo (Strike, Land/Naval) - 4x OFAB-250-270 Frag
* OFAB-250-270 Frag, Hi-Lo-Hi, Long-Range (Strike, Land/Naval) - 2x OFAB-250-270 Frag, 1x 800 liter Drop Tank
* OFAB-250-270 Frag, Lo-Lo-Lo, Long-Range (Strike, Land/Naval) - 2x OFAB-250-270 Frag, 1x 800 liter Drop Tank

* RBK-250 Cluster Bombs Anti-Tank, Hi-Lo-Hi (Strike, Land/Naval) - 4x RBK-250-PTAB CB [30 x PTAB-2.5]
* RBK-250 Cluster Bombs Anti-Tank, Lo-Lo-Lo (Strike, Land/Naval) - 4x RBK-250-PTAB CB [30 x PTAB-2.5]

* RBK-250 Cluster Bombs Frag, Hi-Lo-Hi (Strike, Land/Naval) - 4x RBK-250-AO CB [60 x AO-2.5RT]
* RBK-250 Cluster Bombs Frag, Lo-Lo-Lo (Strike, Land/Naval) - 4x RBK-250-AO CB [60 x AO-2.5RT]

* RBK-250 Cluster Bombs Incendiary, Hi-Lo-Hi (Strike, Land/Naval) - 4x RBK-250-ZAB [48 x ZAB-2.5M]
* RBK-250 Cluster Bombs Incendiary, Lo-Lo-Lo (Strike, Land/Naval) - 4x RBK-250-ZAB [48 x ZAB-2.5M]

* RBK-500 Cluster Bombs Anti-Tank, Hi-Lo-Hi (Strike, Land/Naval) - 2x RBK-500-PTAB CB [268 x PTAB-1M]
* RBK-500 Cluster Bombs Anti-Tank, Lo-Lo-Lo (Strike, Land/Naval) - 2x RBK-500-PTAB CB [268 x PTAB-1M]

* RBK-500 Cluster Bombs Frag, Hi-Lo-Hi (Strike, Land/Naval) - 2x RBK-500-AO CB [108 x AO-2.5RT]
* RBK-500 Cluster Bombs Frag, Lo-Lo-Lo (Strike, Land/Naval) - 2x RBK-500-AO CB [108 x AO-2.5RT]

* RBK-500 Cluster Bombs Incendiary, Hi-Lo-Hi (Strike, Land/Naval) - 2x RBK-500-ZAB [117 x ZAB-2.5SM]
* RBK-500 Cluster Bombs Incendiary, Lo-Lo-Lo (Strike, Land/Naval) - 2x RBK-500-ZAB [117 x ZAB-2.5SM]

* S-24B 240mm Rockets, Hi-Lo-Hi (Strike, Land/Naval) - 4x S-24B 240mm Rocket
* S-24B 240mm Rockets, Lo-Lo-Lo (Strike, Land/Naval) - 4x S-24B 240mm Rocket

* S-5K 57mm Rockets, Hi-Lo-Hi (Strike, Land/Naval) - 64x S-5K 57mm Rocket
* S-5K 57mm Rockets, Lo-Lo-Lo (Strike, Land/Naval) - 64x S-5K 57mm Rocket
* S-5K 57mm Rockets, Hi-Lo-Hi, Long-Range (Strike, Land/Naval) - 32x S-5K 57mm Rocket, 1x 800 liter Drop Tank
* S-5K 57mm Rockets, Lo-Lo-Lo, Long-Range (Strike, Land/Naval) - 32x S-5K 57mm Rocket, 1x 800 liter Drop Tank

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Bombsight - Basic

### Comments

Regarding bombsight - in database MiG-23 fighter bombers (MiG-23B/BN) and interceptors (MiG-23M/etc.) has bombsight with ballistic computing - however fighter bomber has better bombsight in reality so I think that interceptors (MiG-23M/MS/ML etc.) should have only basic bombsight. MiG-23UB has same bombsight as MiG-23M.

### Sources

http://www.airvectors.net/avmig23_2.html
https://ruslet.webnode.cz/technika/ruska-technika/letecka-technika/a-i-mikojan-a-m-i-gurjevic/mig-23ub-flogger-c-/
http://www.airwar.ru/enc/fighter/mig23ub.html
http://aviaros.narod.ru/mig-23ub.htm
https://www.valka.cz/Ceskoslovensko-c513404

**Comment by Jkryos** [comment]
Added DB3K 510.
