### ISSUE TITLE
Ukraine Tu-160

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1635]
### DB Selector

DB3K

### DBID to Copy

#280

### Hypothetical

No

### Name

Tu-160

### Country

Ukraine

### Service

Air Force

### In Commission

1992-1999

### Number in Service

19x, 1x scrapped January 1999, 8x Sold to Russia November 1999, remaining 8x Scrapped

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.thedrive.com/the-war-zone/43560/ukraine-once-had-the-worlds-largest-tu-160-blackjack-bomber-fleet

![image](https://user-images.githubusercontent.com/99599482/177649807-85368a92-c801-4eb1-a67f-7a67f103777b.png)

**Comment by PygmalionOfCyprus** [comment]
Added 496.
