### ISSUE TITLE
Correction to frequency band of JY-27A radar and adding to Venezuela

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1639]
### DB Selector

DB3K

### Affected DBID(s)

Facility_3419; Facility_3420

### Summary of Changes

The JY-27A WIDE MAT is listed in the database as being in the NATO "B" radar band.  In fact, it is a VHF radar, which puts in predominately in the NATO "A" band.  (https://www.radartutorial.eu/19.kartei/02.surv/karte029.en.html). Although a very small part of the VHF band crosses over into the NATO "B" band, the vast majority of the band resides in the NATO "A" band.  

 I have been unable to confirm the exact frequency it operates in, so I can not conclusively state that it is an "A" band radar, although the odds are excellent that it is.  Notably, Chinese advertising brochures claim it operates in the "Meter band" (see https://www.strategicfront.org/forums/threads/jy-27a-radar-spotted-in-pakistan-janes-defence-weekly.3652/), placing it entirely in the NATO "A" band , which has an upper limit of 300 Mhz  see https://www.ahsystems.com/notes/frequency%20band%20designations.php

Finally, the JY-27A was sold to Venezuela in 2019-20, so you may want to add it to that country.  see https://www.pakdefense.com/blog/china/chinese-made-venezuelan-air-defense-jy-27a-radar-detects-us-f-22-stealth-jets-approaching-countrys-airspace/

### Sources

https://www.radartutorial.eu/19.kartei/02.surv/karte029.en.html
https://www.strategicfront.org/forums/threads/jy-27a-radar-spotted-in-pakistan-janes-defence-weekly.3652/

**Comment by PygmalionOfCyprus** [comment]
Fixed/added 496.
