### ISSUE TITLE
Update Zumwalt DDG VLS Options

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#164]
### DB Selector

DB3K

### Affected DBID(s)

DBID 765, 3100, 3343

### Summary of Changes

MK 57 PVLS and Zumwalt can carry Fire SM-2

### Sources

https://www.navsea.navy.mil/Media/News/SavedNewsModule/Article/2386284/uss-zumwalt-successfully-completes-first-standard-missile-shot/
https://m.youtube.com/watch?feature=emb_title&v=Xxe6oexgYeQ
http://dtic.mil/descriptivesum/Y2014/Navy/stamped/0604366N_5_PB_2014.pdf
https://www.thedrive.com/the-war-zone/37148/the-navys-stealth-destroyer-has-fired-a-missile-for-the-first-time
https://www.raytheonmissilesanddefense.com/news/feature/uss-zumwalt-test-fires-first-standard-missile
https://www.defensenews.com/naval/2020/10/19/the-us-navys-stealth-destroyer-conducts-its-first-missile-test/

![201013-N-N2201-002_694x463](https://user-images.githubusercontent.com/99599482/154346696-09c11475-e0d4-4466-ab93-360307f7cc69.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added new version of the Zumwalt w/ empty record for SM-2 Blk IIIAZ in the PVLS. Also modified the existing PVLS to remove all SMs and stripped the Zumwalts of their Aegis datalinks. They now have a Zumwalt-only (for now) TSCE datalink that can guide the Blk IIIAZs.
