### ISSUE TITLE
SAAM-400K Seabow

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#1642]
### DB Selector

DB3K

### Affected DBID(s)

3938

### Summary of Changes

The name of K-SAAM should be changed to SAAM-400K sea bow. It is also available on the LPH-6112 Marado, daegu class FFG, KDX-3 batch 2.  Like ESSM, it can be mounted on K-VLS in quad pack format with 4 shots per cell. And The warhead is also a close-knit warhead unrelated to the AIM-9 series.

### Sources

http://news.tf.co.kr/read/ptoday/1906069.htm
https://en.wikipedia.org/wiki/K-SAAM

**Comment by PygmalionOfCyprus** [comment]
We already have Sea Bow / Haegung in the comments. Where are you seeing the SAAM-400K designation? I can't see it in either of those sources.

**Comment by clerara10** [comment]
> We already have Sea Bow / Haegung in the comments. Where are you seeing the SAAM-400K designation? I can't see it in either of those sources.

In database v493, sea bow is long range anti air missile, that range 2~110nm (DBID #3869). However, the sea bow is a short-range air defense missile developed to replace RAM.  Long range SAM for ROK navy is L-SAM and it is diffrent missile with sea bow. 
I think #3869 K-SAAM is L-sam. This request is for weapon ID #3938

and I read SAAM-400K is formal name of K-SAAM, But I can't find any reference for that, sorry for that

**Comment by PygmalionOfCyprus** [comment]
3938 has been deprecated/unused since at least 494. I recall fixing a similar issue with the K-SAAM in a prior version; the current K-SAAM entry (3869) is much more accurate, with a max range of 10nm, etc.

Could you check to see if the issue you're referring to still exists in 494/495?

**Comment by PygmalionOfCyprus** [comment]
Closing for now since it appears reporter is using an outdated version of the DB.

**Comment by clerara10** [comment]
> Reference in new

Yes. In DB v493 #3869 is not fixed. If the problem is caused by an old version, please let me know where I can download the latest version (I'm useing steam version)
