### ISSUE TITLE
KM-SAM request

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#1643]
### DB Selector

DB3K

### Affected DBID(s)

3596

### Summary of Changes

KM-SAM block 2 is not used for naval SAM

### Sources

https://ko.wikipedia.org/wiki/%EC%B2%9C%EA%B6%81_(%EB%AF%B8%EC%82%AC%EC%9D%BC)

**Comment by PygmalionOfCyprus** [comment]
...and it isn't used as a naval SAM anywhere in the DB.

**Comment by clerara10** [comment]
> ...and it isn't used as a naval SAM anywhere in the DB.

In database v493, it is used as Naval SAM for Daegu class FFG, DBID #3217

**Comment by KC45jp** [comment]
it means already fixed, doesn't it? newest is 495 (or 494 for public version)

**Comment by PygmalionOfCyprus** [comment]
Yeah, in 494/495 Daegu 3217 has a KVLS w/ K-SAAM & K-ASROC loaded, plus capability for SSM-700K Haeryong & Hyunmoo 3C -- no KM-SAM Blk 2.

**Comment by clerara10** [comment]
> it means already fixed, doesn't it? newest is 495 (or 494 for public version)

where can I download databae v495??

**Comment by KC45jp** [comment]
it is in public beta...
https://www.matrixgames.com/forums/viewtopic.php?p=5013560#p5013560
