### ISSUE TITLE
Daegu class FFG request

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#1644]
### DB Selector

DB3K

### Affected DBID(s)

3217

### Summary of Changes

Daegu class did not use RIM-116 RAM, KM-SAM. It use SAAM-400K sea bow for SAM.

### Sources

https://en.wikipedia.org/wiki/Daegu-class_frigate

**Comment by PygmalionOfCyprus** [comment]
Fixed a while back in #3217.
