### ISSUE TITLE
S-300 series minimum altitude request

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#1646]
### DB Selector

DB3K

### Affected DBID(s)

1156, 1831, 1113, 12, 

### Summary of Changes

I'd like to change S-300 series's intercepter's minimum altitude to 25m.  While newer 9M96E missile, and 48N6E missile's minimum altitude is 10~7m, 5V55 series, and 48N6,48N6E missile's minimul altitude is 25m.

### Sources

http://www.ausairpower.net/APA-Grumble-Gargoyle.html

**Comment by KLABDB3K** [comment]
![image](https://user-images.githubusercontent.com/99494755/178066666-731f6b97-2570-4bf8-9216-be784cb04fb6.png) TASS 48N6 says 10m
https://www.globalsecurity.org/military/world/russia/s-400-missiles.htm Global Security 48N6 says 10m
Data is too inconsistent. 
Singel source of Aus Airpower from 2006 - Last Updated: Mon Jan 27 11:18:09 UTC 2014. Actually, has a chart which doesn't specify the minimum altitudes of the missiles listed and mentions the 9M96 as being as low as 15ft - circa 5m.

**Comment by PygmalionOfCyprus** [comment]
See comment above, conflicting data.
