### ISSUE TITLE
Add YJ-18 loadout to 039B and 039C

### ISSUE THREAD

**Issue by rushgg** [PygmalionOfCyprus/cmo-db-requests#1647]
### DB Selector

DB3K

### User(s)

Submarine #577- Type 039B Yuan (China - 2014)

### Weapons Carried

Weapon #2868 - YJ-18 [3M54E Klub Copy]

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

N/A

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

i'm not sure how to add new loadout to submarines, so i raise the issue here.

This issue also applies for 
Submarine #580- Type 039B Yuan (China - 2016)
Submarine #695- Type 039C Yuan (China - 2021)

Or just change the status of the 533mm TT of chinese submarines capable of launching YJ-18.

### Sources

https://twitter.com/dafengcao/status/1517369684236341248

Eight of the PLAN’s 12 Kilo class SSs are equipped with the Russian-built RS-SS-N-27b ASCM (120-nm, 220-km). The PRC’s Song class  SS,  Yuan  class  SSP,  and  Shang  class  SSN  will  field  the  PLAN’s  newest  domestic  submarine-launched  YJ-18  and  its  variants,  which  constitute  an  improvement  over  the  RS-SS-N-27b ASCM.  _Military and Security Developments Involving the  People’s Republic of China,2021, DoD_ https://media.defense.gov/2021/Nov/03/2002885874/-1/-1/0/2021-CMPR-FINAL.PDF

**Comment by claudejdev** [comment]
Amazing picture!

**Comment by Jkryos** [comment]
Added DB3K 505.
