### ISSUE TITLE
Add Spanish SH-60F S-70B-4[HT.23] 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1649]
### DB Selector

DB3K

### DBID to Copy

1136

### Hypothetical

No

### Name

S-70B-4[HT.23] 

### Country

Spain

### Service

Navy

### In Commission

2020

### Number in Service

x4

### Loadout Options

No asw
2 and 4.5 ton cargo
Commando

### Sources

https://www.scramble.nl/military-news/armada-says-farewell-to-the-sea-king
https://www.airliners.net/photo/Spain-Navy/Sikorsky-SH-60F-Ocean-Hawk-S-70B-4/6646283
https://www.key.aero/article/spanish-navy-receives-sh-60fs
https://www.helis.com/database/news/spain-sh-60f-seahawk-2018/

**Comment by PygmalionOfCyprus** [comment]
Added 496.
