### ISSUE TITLE
MD-530F Cayuse Warrior Afghanistan - April 2015 -(out of service 2021?), Kenya 2020-Present

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#165]
### DB Selector

DB3K

### Hypothetical

No

### Name

MD-530F Cayuse Warrior

### Country

Afghanistan, Kenya

### Service

Air Force

### In Commission

2015-2021? (Afghanistan), 2020- (Kenya)

### Length (m)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Wingspan (m)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Height (m)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Empty Weight (kg)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Maximum Takeoff Weight (MTOW) (kg)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Payload Weight (kg)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Crew

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Propulsion

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Rate of Climb (ft/min)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Service Ceiling (ft)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Military/Afterburner Speed (kt)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Cruise Speed (kt)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Supercruise

No

### Ferry Range (nm)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Endurance (min)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Takeoff / Landing Distance (m)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Fuel Capacity (kg)

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Sensors

1x Mk1 Eyeball
1x NVG

### Mounts

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Loadout Options

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Comms/Datalinks

As DBID 5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021)

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Bombsight - Basic

### Comments

MD-530F Cayuse Warrior (Little Bird Lite) helicopters were supplied to the Afghan air force in some numbers (60+) from April 2015.
Armament was limited to FN 2 x HMP-400 12.7mm gun pods or twin 7 rocket Hydra pods.
Electronics and EW systems appear very limited although it may have had NVG compatibility it does not appear to have been used.
Basic air frame is a straight lift of DB3k entry #1593 - AH-6M Little Bird MELB [MD-530F] (United States - 0) but lacking optronic systems, guided weapons and EO turret.
Numbers still in service are conjecture post Taliban but are likely to be small and decreasing, plus some may be amalgamated into the air arms of the countries to which the air force relocated, significant numbers went to Uzbekistan.

According to Colonel Qalandari, Afghan Air Force pilot, “It’s unsafe to fly, the engine is too weak, the tail rotor is defective and it’s not armored. If we go down after the enemy we’re going to have enemy return fire, which we can’t survive. If we go up higher, we can’t visually target the enemy".

Indeed, the helicopters lack proper gun sights for their two .50 caliber machine guns, The helicopters periodically appeared in the sky over contested mountains, but had difficulties locating and attacking ISIS positions with their weapons.

Extracts from above references of interest:

In service 8th April 2015.
Afghan Air Force unveils its newest Close Air Attack Helicopter. HD Video by Airman 1st Class Eric Mann | U.S. Air Forces Central Command Public Affairs | Date: 04.08.2015. Afghan Air Force MD-530F Cayuse Warrior helicopter pilots and their advisors from the Train, Advise, Assist Command - Air, prep and practice for the MD-530F Rollout ceremony to be conducted the following day at Kabul Afghanistan International Airport, Apr. 08, 2015.

From product info from manufacturers:

Max Gross Weight: Int. 3,300 lb / 1,496 kg
Useful Load 2,159 lb / 979 kg
Service Ceiling 16,000 ft / 4,876 m
Max Cruise Speed 110 kt / 203 kph
HOGE 14,400 ft / 4,389 m
HIGE 16,000 ft / 4,877 m
Range 235 nm / 435 km

MD 530F Cayuse Warrior helicopter can be armed with FN HMP400 LCC (link and case collector) coaxial air weapon system developed by FN Herstal. The machine gun pod is equipped with a M3P .50cal FN machine gun. The weapon system supports all types of NATO ammunition 12.7 mm x 99 mm. The FN HMP400 has a full weight of 138 kg and a storage capacity of 400 rounds of ammunition. The weapon system can shoot at speeds of around 1,100 revolutions per minute.

Thanks for considering, also supplied to KENYA.

### Sources

https://www.airforce-technology.com/projects/md-530f-cayuse-warrior-helicopter/
https://youtu.be/KSrRF65o-MU
https://fnamerica.com/products/fn-airborne-pod-systems/fn-hmp400-pod/
https://youtu.be/py6H_5EyYOo
https://youtu.be/uUvtMSj3908 Shows Hydra 2 x 7 pods. And 1 x HMP400 1 X Hydra
https://www.mdhelicopters.com/afghan-air-force-to-expand-fleet-of-md-530f-cayuse-warrior-helicopters.html Seems only supporting HMP-400 AND Hydra.
https://www.maceaviation.com/case-studies
https://en.wikipedia.org/wiki/McDonnell_Douglas_MD_500_Defender
https://thediplomat.com/2015/09/afghanistans-newest-attack-helicopter-a-total-mess/
https://thediplomat.com/2016/01/afghanistan-to-receive-12-new-attack-helicopters/
https://www.flightglobal.com/download?ac=75345
https://www.helis.com/database/modelorg/Kenya-MD530F/
https://southfront.org/afghan-air-force-criticize-us-made-md-helicopters/
https://www.dsca.mil/press-media/major-arms-sales/kenya-md-530-aircraft

![FCF87782F69E46AFA573BE68EC0B46B4](https://user-images.githubusercontent.com/99599482/154346419-0e9739d5-5cfc-4f32-95f7-c21c540f77b4.jpg)

**Comment by KLABDB3K** [comment]
Load outs are Not the same as Lebanon MD530. Afghans only ever got Hyrda rocket pods and HMP gun pods.

**Comment by tbrandon517** [comment]
Additional Source for Kenyan Little Birds

https://www.thedrive.com/the-war-zone/24069/kenya-and-lebanon-will-get-little-bird-choppers-that-can-carry-up-to-six-weapons-at-once

**Comment by PygmalionOfCyprus** [comment]
Added 493 for Afghanistan & Kenya, with the former having slightly modified loadouts. Also added an APKWS loadout option to the Lebanese version.
