### ISSUE TITLE
Add SH-3H[HS.19] Transport Version

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1652]
### DB Selector

DB3K

### DBID to Copy

674

### Hypothetical

No

### Name

SH-3H[HS.19]

### Country

Spain

### Service

Navy

### In Commission

2001-2022

### Number in Service

x7

### Sensors

Wescam 15

### Mounts

7.62mm door gun

### Loadout Options

Remove ASW
Add 1.5 and 3 ton cargo
Marine
SAR
Commando

### Other Changes

7 converted from ASW to Transport

### Sources

https://aviationphotodigest.com/naval-station-rota/
https://www.helis.com/database/modelorg/Armada-Sea-King/
https://www.helis.com/database/news/gruflex61/
https://www.scramble.nl/military-news/armada-says-farewell-to-the-sea-king
https://www.milavia.net/specials/centenario-aviacion-naval-espanola/view.php?f=46

**Comment by PygmalionOfCyprus** [comment]
Added 496.
