### ISSUE TITLE
AGM-114R on an older AH-64A? Change it to an AGM-114A, please.

### ISSUE THREAD

**Issue by RevanstheBomb** [PygmalionOfCyprus/cmo-db-requests#1654]
### DB Selector

DB3K

### Affected DBID(s)

#1605 - AH-64A Apache (United States - 1987)

### Summary of Changes

I was crafting a compact scenario of US vs. Warsaw Pact in Fulda when I noticed that the '87 US Apache has a Hellfire II variant that didn't come into view until the 2010s for US allies, and later the US Army in the 2020's. Namely, the AGM-114A [8x A Model Hellfires] Loadout for some reason has AGM-114R Hellfire IIs as opposed to AGM-114As. This is a rather anachronistic choice for such a loadout. Can it be changed to the appropriate Hellfire variant, please? [AGM-114A, don't forget]

### Sources

https://www.thedefensepost.com/2021/03/22/agm-114-hellfire-missile/
http://www.fi-aeroweb.com/Defense/Brochures/AGM-114R-HELLFIRE-II.pdf
https://www.military-today.com/missiles/hellfire.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 496.
