### ISSUE TITLE
Iceland - Camcopter S-100

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1656]
### DB Selector

DB3K

### DBID to Copy

Romanian S-100 with PT-6 Oceanwatch

### Hypothetical

No

### Name

Camcopter S-100

### Country

Iceland

### Service

Coast Guard

### In Commission

2022-

### Number in Service

2x

### Sensors

Trakka TC-300 Electro-Optical / Infra-Red (EO/IR) camera gimbal
PT-8 Oceanwatch wide-area camera
Becker Avionics BD406 Emergency Beacon Locator
Automatic Identification System (AIS) receiver.

### Loadout Options

-Ferry
-Maritime Recon

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/july/11892-icelandic-coast-guard-deploys-camcopter-s-100-unmanned-aerial-vehicle.html?fbclid=IwAR0ZEGKAxTndoNgm148XFyWEkBAzFvMhJQE5A8xhjHX1kA83RppoMOy_-PE
https://www.navalnews.com/naval-news/2022/07/camcopter-s-100-improves-maritime-surveillance-capacity-of-icelandic-coast-guard/?utm_source=rss&utm_medium=rss&utm_campaign=camcopter-s-100-improves-maritime-surveillance-capacity-of-icelandic-coast-guard
https://www.unmannedsystemstechnology.com/2022/07/camcopter-s-100-uav-enhances-situational-awareness-for-icelandic-coast-guard/
https://www.aviation-defence-universe.com/schiebel-camcopter-s-100-delivers-enhanced-maritime-situational-awareness-for-the-icelandic-coast-guard/
https://gbp.com.sg/stories/icg-deploys-schiebels-camcopter-s-100-uavs/

![image](https://user-images.githubusercontent.com/99599482/177993940-6d048455-db16-4c4a-8be5-32350c631833.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
