### ISSUE TITLE
Add new AIM-120D-3 missile (IOC 2023)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#166]
### DB Selector

DB3K

### Hypothetical

No

### Name

AIM-120D-3 AMRAAM

### Length (m)

As DBID 51

### Width/Span (m)

As DBID 51

### Diameter (m)

As DBID 51

### Weight (kg)

As DBID 51

### Range (nm)

greater than DBID 51

### Target Altitude / Depth (ft)

As DBID 51

### Launch Altitude / Depth (ft)

As DBID 51

### Warhead

As DBID 51

### Targets

Aircraft, Helicopter, Missile

### CEP (m)

N/A

### Sensors

As DBID 51

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer, Lock-On After Launch (LOAL) - CEC-Capable, Level Cruise Flight

### Comments

AMRAAM’s new AIM-120D-3 missile variant will deliver additional capabilities, including hardware and software upgrades, to address advanced threats.

The F3R program has been developed for the existing AIM-120C-8 and AIM-120D-3 AMRAAMs, which already represent the ‘top of the line’ for these missiles. Of these, the D-model already offers some significant advantages, including a two-way datalink with third-party targeting capabilities.

In particular, the company pointed to the enhanced seeker performance that the F3R provides to the AIM-120D-3, which is now better able to target enemy aircraft and missiles in adverse weather, even when threats are employing advanced electronic warfare systems.

AIM-120D-3 production deliveries beginning in 2023

### Sources

https://www.thedrive.com/the-war-zone/43483/latest-amraam-air-to-air-missile-aims-to-keep-pace-with-china
https://seapowermagazine.org/new-amraam-variant-completes-two-free-flight-test-shots/
https://twitter.com/MIL_STD/status/1406359957902143492
https://www.janes.com/defence-news/news-detail/amraam-joint-program-office-completes-second-live-firing-of-new-aim-120d-3?linkId=121135738

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
