### ISSUE TITLE
NSM for Australian DDG/FFG 2024

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1660]
### DB Selector

DB3K

### Affected DBID(s)

Aussie Hobarts and ANZACs, probably Hunter Class as well

### Summary of Changes

NSM selected to replace Harpoon from 2024

### Sources

https://www.australiandefence.com.au/defence/joint/new-missile-strike-capabilities-announced
https://aviationweek.com/defense-space/missile-defense-weapons/australia-signs-contract-naval-strike-missile
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/july/11890-kongsberg-signs-initial-contract-with-australia-for-the-naval-strike-missile.html
https://www.navalnews.com/naval-news/2022/07/kongsberg-signs-contract-with-australia-for-nsm-capability/?fbclid=IwAR04CI86yeL099VJtjJf91m9WRRCQBofscpbEEw7ySJnGyk413Dn683P-3w
https://www.edrmagazine.eu/kongsberg-signs-initial-contract-with-the-commonwealth-of-australia-for-naval-strike-missile-capability
https://www.naval-technology.com/news/kongsberg-strike-missile-australian-navy/
https://www.janes.com/defence-news/news-detail/australia-fast-tracks-nsm-block-1a-for-ran-surface-fleet

![image](https://user-images.githubusercontent.com/99599482/178002141-92dfafee-8bcd-4ea3-8958-df548bcc5214.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
