### ISSUE TITLE
Greece - MQ-9B SeaGuardian

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1661]
### DB Selector

DB3K

### DBID to Copy

DBID #5174

### Hypothetical

No

### Name

MQ-9B SeaGuardian

### Country

Greece

### Service

Air Force

### Number in Service

3x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

Unclear if ASW pods being purchased

Multiple sources indicate strike capability using Paveway IV and Brimstone 2

### Sources

https://www.overtdefense.com/2022/07/04/greek-parliament-to-set-aside-budget-for-mq-9s/
https://bulgarianmilitary.com/2022/07/06/greece-buys-short-takeoff-landing-mq-9b-seaguardian-version/
https://www.defenceview.in/greece-to-buy-mq-9b-uav-a-reply-to-turkey-growing-aggression/
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/july/11887-greece-to-purchase-seaguardian-mq-9b-uav-amid-tensions-with-turkey.html
https://www.navalnews.com/naval-news/2020/09/mq-9b-seaguardian-maritime-uav-which-missions-which-customers/

![image](https://user-images.githubusercontent.com/99599482/178003276-41383fe7-ffb8-4ab7-84b3-468916db3cea.png)

**Comment by tbrandon517** [comment]
New source. Looks like no armament actually.

https://www.oryxspioenkop.com/2022/08/asw-at-premium-greece-purchases-mq-9b.html?m=1

**Comment by Jkryos** [comment]
Added DB3K 496.
