### ISSUE TITLE
Type 056 Corvettes To The China Coast Guard

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1664]
### DB Selector

DB3K

### DBID to Copy

DBID 2295

### Hypothetical

No

### Name

Type 056 Jiangdao (China Coast Guard) 511 Baoding

### Country

China

### Service

Coast Guard

### In Commission

2021-Present

### Number in Service

Up to 21x

### Sensors

Remove sonars

### Mounts

remove the missile and torpedo launchers

### Loadout Options

N/A

### Other Changes

N/A

### Sources

https://www.navalnews.com/naval-news/2021/12/china-transferring-navy-type-056-corvettes-to-the-coast-guard/?fbclid=IwAR0MA-XrmwjhGsip1IeYisoRC5Y2lTd41hYYNqBiUVPV2feQkqUGMqLkSMk

![image](https://user-images.githubusercontent.com/99599482/178010499-b5a40c3e-493a-42a5-8e99-0a458408860d.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
