### ISSUE TITLE
110-3 Shahid Mahdavi (IRGC-Navy)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1665]
### DB Selector

DB3K

### Baseline

DBID 2028

### Hypothetical

No

### Name

110-3 Shahid Mahdavi

### Class

110-3 Shahid Mahdavi

### Country

Iran

### Service

IRGC-Navy

### In Commission

2023-

### Number in Service

2x

### Length (m)

240.2m

### Beam (m)

32.2m (original hull)

### Draft (m)

AS DBID 2028

### Standard Displacement (t)

41,971

### Full Displacement (t)

not stated

### Empty Displacement (t)

not stated

### Complement

Similar to Saviz, Makran, and Shahid Roudaki

### Max Sea State

AS DBID 2028

### Primary Propulsion Type

Diesel

### Propulsion

AS DBID 2028

### Fuel Capacity (kg)

AS DBID 2028

### Flank Speed (kt)

AS DBID 2028

### Range (nm) at Speed (kt)

AS DBID 2028

### Sensors

Similar Capabilities to Saviz, Makran, and Shahid Roudaki

### Mounts

4x Crewed AAA Guns seens

### Aircraft & Docking Facilities

Deck area fitted for large scape helo and uav operations as a flight deck with new sponson on port side to create and angled deck fir drone ops.

### Comms/Datalinks

Similar Capabilities to Saviz, Makran, and Shahid Roudaki

### Ship Codes

Built to Mercantile Standards

### Comments

Similar Capabilities to Saviz, Makran, and Shahid Roudaki

### Sources

http://www.hisutton.com/Iran-IRGC-Shahid-Mahdavi.html?fbclid=IwAR2xKrEtBeIp_37Wmk78TcQukaNsaHGAk0dzfhqVDwH635oqBRDn4Jczrqc
https://www.dailypost27.com/2022/05/iris-shahid-mahdavi-becomes-fourth.html
https://maritime-executive.com/article/iran-s-irgc-turns-a-panamax-boxship-into-a-warship
https://www.voanews.com/a/ship-expands-iran-revolutionary-guard-s-reach-to-new-waters-/6592651.html
https://www.marinetraffic.com/en/ais/details/ships/shipid:4660758/mmsi:422031800/imo:9209348/vessel:SARVIN

![image](https://user-images.githubusercontent.com/99599482/178012974-5433e589-0882-4756-a22f-9fc739139c28.png)
![image](https://user-images.githubusercontent.com/99599482/178013435-7b9e6cfe-48fa-422e-a470-239a1b77383c.png)

**Comment by tbrandon517** [comment]
Update: 2x units which will be helo/UAV carriers.

http://www.hisutton.com/Iran-IRGC-Drone-Carrier-Update.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus 

On February 13 2024 'Dezful' medium range ballistic missiles were launched from shipping containers on the forward deck.

http://www.hisutton.com/Iran-Navy-IRGC-Forward-Base-Ships.html

![17360887223945484775749467772553](https://github.com/user-attachments/assets/eb77396e-431c-40aa-9fee-e3caee3c36b5)
