### ISSUE TITLE
Japan - MQ-9B SeaGuardian

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1666]
### DB Selector

DB3K

### DBID to Copy

DBID 5174

### Hypothetical

No

### Name

MQ-9B SeaGuardian UAV

### Country

Japan

### Service

Coast Guard

### In Commission

2022-

### Number in Service

Not Stated

### Sensors

No Changes

### Mounts

No Changes

### Loadout Options

Ferry
Maritime Surveillance

### Sources

https://www.navalnews.com/naval-news/2022/04/japan-selects-mq-9b-seaguardian-for-coast-guard-rpas-project/?fbclid=IwAR3cR3wk-hF7SE8o7Ndz3GH7jSUPKRht6eya-PFPAkL-ewOQAKuOh0nc4EY
https://www.navaltoday.com/2022/04/08/japan-coast-guard-picks-ga-asis-mq-9b-seaguardian-to-support-rpas-project/
https://www.ga.com/ga-asi-selected-for-japan-coast-guard-rpas-project
https://www.autoevolution.com/news/mq-9b-seaguardian-drone-to-carry-out-maritime-surveillance-missions-in-japan-185895.html
https://www.flightglobal.com/civil-uavs/japan-coast-guard-to-start-mq-9b-operations-in-october/148182.article
https://www.unmannedsystemstechnology.com/2022/04/mq-9b-seaguardian-selected-for-japanese-coast-guard-rpas-project/

![image](https://user-images.githubusercontent.com/99599482/178017001-3857aafc-d70d-4954-bd23-5b9f33df4d4f.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
