### ISSUE TITLE
Jordan - Camcopter S-100

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1667]
### DB Selector

DB3K

### DBID to Copy

DBID #3171

### Hypothetical

No

### Name

Camcopter S-100

### Country

Jordan

### Service

Air Force

### In Commission

2011-Present

### Number in Service

2x Intially, >10 by 2022

### Sensors

MX-10

### Mounts

No Change

### Loadout Options

Ferry
Recon

### Other Changes

None

### Sources

https://www.oryxspioenkop.com/2022/01/operational-failure-ch-4bs-short-lived.html
https://www.flightglobal.com/jordan-gets-schiebel-camcopter-s-100/98524.article
https://en.wikipedia.org/wiki/Schiebel_Camcopter_S-100#Operators

**Comment by Jkryos** [comment]
Added DB3K 496.
