### ISSUE TITLE
Kazakhstan - ANKA UCAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1668]
### DB Selector

DB3K

### DBID to Copy

DBID 4978

### Hypothetical

No

### Name

Anka+A UCAV

### Country

Kazakhstan

### Service

Air Force

### In Commission

2022-

### Number in Service

3x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/01/guardians-of-steppe-kazakhstans-uavs.html?fbclid=IwAR1ctuZqKiPd2A3kLdkb03ChxfKL_9qxVnoBx155woCFY_A4Q4VkQJnieMg
https://www.dailysabah.com/business/defense/kazakhstan-buys-3-turkish-aerospace-made-anka-ucavs-report

![image](https://user-images.githubusercontent.com/99599482/178020670-8d520be5-a424-4052-973f-8345c0c18019.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
