### ISSUE TITLE
Kazakhstan - Orlan-10E

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1669]
### DB Selector

DB3K

### DBID to Copy

Orlan-10 UAV -- Russia [1992-] (Army), 2010

### Hypothetical

No

### Name

Orlan-10E UAV

### Country

Kazakhstan

### Service

Air Force

### In Commission

IOC Uncertain

### Number in Service

Few

### Sensors

No Changes

### Mounts

No Changes

### Loadout Options

No Changes

### Other Changes

No Changes

### Sources

https://www.oryxspioenkop.com/2022/01/guardians-of-steppe-kazakhstans-uavs.html?fbclid=IwAR1ctuZqKiPd2A3kLdkb03ChxfKL_9qxVnoBx155woCFY_A4Q4VkQJnieMg

![image](https://user-images.githubusercontent.com/99599482/178021176-0775392f-b6ef-46f1-a426-a3ce71f18f05.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
