### ISSUE TITLE
Add new Gulfstream G550 ORON of the IDF

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#167]
### DB Selector

DB3K

### Hypothetical

No

### Name

Gulfstream G550 ORON

### Country

Israel

### Service

Air Force

### In Commission

2021-

### Length (m)

As DBID 676 and 2955

### Wingspan (m)

As DBID 676 and 2955

### Height (m)

As DBID 676 and 2955

### Empty Weight (kg)

As DBID 676 and 2955

### Maximum Takeoff Weight (MTOW) (kg)

As DBID 676 and 2955

### Payload Weight (kg)

As DBID 676 and 2955

### Crew

As DBID 676 and 2955

### Propulsion

As DBID 676 and 2955

### Rate of Climb (ft/min)

As DBID 676 and 2955

### Service Ceiling (ft)

As DBID 676 and 2955

### Military/Afterburner Speed (kt)

As DBID 676 and 2955

### Cruise Speed (kt)

As DBID 676 and 2955

### Supercruise

No

### Ferry Range (nm)

As DBID 676 and 2955

### Endurance (min)

As DBID 676 and 2955

### Takeoff / Landing Distance (m)

As DBID 676 and 2955

### Fuel Capacity (kg)

As DBID 676 and 2955

### Sensors

Combines capabilities of DBID 676 and 2955

### Mounts

Combines capabilities of DBID 676 and 2955

### Loadout Options

Combines capabilities of DBID 676 and 2955

### Comms/Datalinks

Combines capabilities of DBID 676 and 2955

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

The new G550 “Oron” combines the capabilities of several different ISR (Intelligence Surveillance Reconnaissance) aircraft in a single platform.

Though the "Oron" looks similar to the "Eitam", its systems are more advanced and allow for a wider range of missions. "The big improvement is in its overall capabilities and diversity of the tasks it can perform", says Maj. I.

The “Oron” received today appears to be a new variant of the G550. “The aircraft combines several capabilities including aerial imaging, control and radar, and maritime intelligence gathering for the Navy”, explains Maj. I, Deputy Commander of the 122nd Squadron. “The majority of these capabilities already exist in our squadron and the ‘Maof Rahav’ unit, however, with the new aircraft, we managed to condense them all onto a single flight platform”.

Externally, the “Oron” is similar to the “Eitam”, the G550 CAEW. This is a sort of mini-AWACS equipped with 2 L-band antennas, on both sides of the fuselage, and 2 S-band antennas, on the nose and tail of the aircraft. The antennas are part of a EL/W-2085, a Phalcon and Green Pine (used for the Arrow Anti-Tactical Ballistic Missile Missile, ATBMM) derivative. However, its systems are more advanced and allow for a wider range of missions, says the IAF on its website. “The big improvement is in its overall capabilities and diversity of the tasks it can perform”, says Maj. I. “The aircraft combines the capabilities of the ‘Eitam’ and the ‘Shavit’, reconnaissance aircraft from the Fighter Division, and advanced air-to-surface radar.

### Sources

https://iaf.org.il/9327-52847-en/IAF.aspx
https://www.thedrive.com/the-war-zone/40065/israelis-new-surveillance-jet-combines-two-other-aircrafts-missions-into-a-single-airframe
https://theaviationist.com/2021/04/04/the-israeli-air-force-officially-introduces-the-oron-a-highly-modified-g550-with-unprecedented-isr-capabilities/
https://twitter.com/IAFsite/status/1378710877281660929

![download](https://user-images.githubusercontent.com/99599482/154346337-8c82773a-df00-4b51-bb95-8cc4b8cc868e.jpg)

**Comment by Jkryos** [comment]
Added DB3K 493.
