### ISSUE TITLE
Israel F-15I Raam A/A correction

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#1670]
### DB Selector

DB3K

### Affected DBID(s)

#2703, #3903, #4776

### Summary of Changes

DBID - 27402 : 2 x AIM-120D > 2 x AIM-120C-7 (Only #4776)
DBID - 30254 : 1 x AIM-120C-5 > 1 x AIM-120C-7 (Including #2703, #3903, #4776) 

It needs correction into consistent A/A Loadouts.

### Sources

DB3K

**Comment by KushanGaming** [comment]
Done for DB497.
