### ISSUE TITLE
Tunisa - T-6C Texan II

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1671]
### DB Selector

DB3K

### DBID to Copy

5150

### Hypothetical

No

### Name

T-6C Texan II

### Country

Tunisa

### Service

Air Force

### In Commission

2026

### Number in Service

8x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.ainonline.com/aviation-news/defense/2019-10-15/t-6c-texan-ii-sale-possible-tunisia
https://www.scramble.nl/military-news/contract-awarded-for-tunisian-air-force-t-6c-training-aircraft?fbclid=IwAR2JF3omuF7D3h3_a-lGl9Y5izDuJBTBzO3jeoJ72lx2F8_xeOYTCP-Teh0
https://en.wikipedia.org/wiki/Beechcraft_T-6_Texan_II#Tunisia

![image](https://user-images.githubusercontent.com/99599482/178025386-1f05daa1-09ee-4b7c-bc3b-97aca2cf4a62.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
