### ISSUE TITLE
88 Xu-Xiake (Daguan-class barracks ship)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1672]
### DB Selector

DB3K

### Baseline

DBID 2024

### Hypothetical

No

### Name

88 Xu-Xiake

### Class

barracks ship

### Country

China

### Service

Navy

### In Commission

2011-Present

### Number in Service

2x

### Length (m)

196 m

### Beam (m)

28 m

### Draft (m)

8 m

### Standard Displacement (t)

23,000 t

### Full Displacement (t)

30,000 t

### Empty Displacement (t)

Not Stated

### Complement

Not Stated

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

2 × marine diesel engines, 7,200 hp (5,369 kW)

### Flank Speed (kt)

20 knts

### Range (nm) at Speed (kt)

8,000 nmi 

### Sensors

Navigation Radars

### Mounts

25 mm (0.98 in) and/or 37 mm (1.5 in) guns

### Aircraft & Docking Facilities

Helipad for 1 × Changhe Z-8 helicopter
2x large davits for Landing craft/transfer Barges

### Comms/Datalinks

VHF/UHF Radio
Probably SATCOM

### Comments

Barracks ship/Training ship/Troop ship

Built as part of the Project 048 aircraft carrier program, the primary task of Daguan class is to provide accommodation for staff working on aircraft carrier trials so that staff can remain on station to continue trials the following day, instead of returning to port and going out for the next trial, thus greatly shortening the time required. The ship is designed to support 2,500 people for three weeks at sea before needing resupply. When not operating as a, Daguan class can also be deployed as training ships, and when necessary, deployed as troopships, or to evacuate oversea Chinese from flashpoints.

### Sources

https://en.wikipedia.org/wiki/Daguan-class_barracks_ship
https://www.globalsecurity.org/military/world/china/xu-xiake-accomodation.htm
http://www.hisutton.com/China-Sanya-Carrier.html

![image](https://user-images.githubusercontent.com/99599482/178027518-a4b4a5c5-d7b1-436b-a9c0-7bc641a473bd.png)
![image](https://user-images.githubusercontent.com/99599482/178028196-a97a615c-5b1b-4b5f-82c9-732e8f925bbe.png)

**Comment by PygmalionOfCyprus** [comment]
Handled as part of the PLAN portion of the China review.
