### ISSUE TITLE
KDX-3, Batch-2 Standard Missiles

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1675]
### DB Selector

DB3K

### Affected DBID(s)

DBID 3622

### Summary of Changes

The KDX-III Batch II MK 41 VLS will be fitted with 
Raytheon’s SM-3 Block IB interceptors 
SM-2 Block IIIB a
SM-6 “multi-mission missile” 

### Sources

https://www.navalnews.com/naval-news/2022/04/south-korea-to-acquire-sm-6-missiles-for-kdx-iii-batch-ii-destroyers/?fbclid=IwAR1_NJW3U7T8g9XeDPrF0LNeXio39NDIBima_WlFRhMLWsFYBfWWz5EYJ-M
https://aviationweek.com/defense-space/missile-defense-weapons/south-korea-acquire-sm-6-missiles-upgrade-black-hawks
https://en.yna.co.kr/view/AEN20220426009500325
https://defbrief.com/2022/04/26/south-korea-approves-purchase-of-sm-6-missiles-for-its-aegis-destroyers/
https://www.defensenews.com/naval/2018/10/12/south-korea-to-buy-ship-based-interceptors-to-counter-ballistic-missile-threats/
https://missilethreat.csis.org/south-korea-to-purchase-sm-3-interceptors/
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/april/11663-south-korea-to-purchase-standard-missile-6-interceptors.html
https://www.naval-technology.com/uncategorised/newssouth-korea-requests-sale-of-sm-2-block-iiib-standard-missiles-from-us-4942199/
https://www.naval-technology.com/news/us-approves-possible-sale-of-sm-2-block-iiib-missiles-to-korea/
https://thediplomat.com/2019/05/us-state-department-approves-sale-of-94-sm-2-block-iiib-missiles-to-south-korea/
https://www.dsca.mil/press-media/major-arms-sales/republic-korea-sm-2-block-iiib-standard-missiles-and-containers
https://www.dsca.mil/press-media/major-arms-sales/korea-sm-2-block-iiib-standard-missiles

**Comment by PygmalionOfCyprus** [comment]
Either I fixed this in an older ticket that I now can't find or I ninja'd this on my own initiative as part of a news roundup or something. Anyway, already done, will be in 496!
