### ISSUE TITLE
United States Camcopter S-100

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1676]
### DB Selector

DB3K

### DBID to Copy

DBID 5238

### Hypothetical

No

### Name

Camcopter S-100

### Country

United States

### Service

Navy

### In Commission

2021-Present

### Number in Service

1x

### Sensors

Remove MX-10 and replace with

Pushbroom Imaging Lidar for Littoral Surveillance, or PILLS

### Mounts

N/A

### Loadout Options

Littoral Surveillance
Aerial Topography
hydrographic mapping

### Sources

https://www.thedrive.com/the-war-zone/41902/small-unmanned-helicopters-used-lasers-to-map-littorals-in-recent-u-s-navy-tests
https://seapowermagazine.org/schiebel-camcopter-s-100-successfully-completes-trials-for-u-s-navy/
https://militaryembedded.com/unmanned/test/sensor-enabled-camcopter-s-100-uas-demoed-for-the-us-navy
https://navalpost.com/u-s-navy-completes-trials-of-camcopter-s-100/
https://www.naval-technology.com/news/schiebel-completes-camcopter-s-100-flight-trials/
https://www.navalnews.com/naval-news/2021/08/schiebel-camcopter-s-100-successfully-completes-flight-trials-for-u-s-navys-onr/

![image](https://user-images.githubusercontent.com/99599482/178064416-d0aab679-fe86-4fcb-93a6-11823282b206.png)
![image](https://user-images.githubusercontent.com/99599482/178064810-b76bad1a-89ae-4567-a3c2-48d956683e8e.png)
![image](https://user-images.githubusercontent.com/99599482/178064898-718bab9c-1d17-4a35-bab1-d15f8a1f3475.png)

**Comment by PygmalionOfCyprus** [comment]
Just demoed/trialed, not commissioned.
