### ISSUE TITLE
Update to band of JY-26 radar and possible nomenclature and change to 3-D  radar

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1679]
### DB Selector

DB3K

### Affected DBID(s)

Facility_2537

### Summary of Changes

The PRC's JY-26 radar operates is also known as the "Skywatcher-U" and it is reported to work in the UHF/VHF range, making in an NATO "A/B" band radar.  See https://asiatimes.com/2019/11/nowhere-to-hide-has-china-won-the-stealth-war/.  The one source I found that gave specific frequencies stated it operates in the  250-350 MHz range, placing it in the A/B band.  https://forceindia.net/feature-report/the-tech-route/

It is also reported to be a 3-D, vice a 2-D radar as reported in the database. https://www.deagel.com/Sensor%20Systems/JY-26/a003064.  See also http://fullafterburner.weebly.com/next-gen-weapons/military-balance-india-vs-china-air-defense-systems-part-2-chinese-radars

### Sources

https://asiatimes.com/2019/11/nowhere-to-hide-has-china-won-the-stealth-war/
https://www.deagel.com/Sensor%20Systems/JY-26/a003064.  
 http://fullafterburner.weebly.com/next-gen-weapons/military-balance-india-vs-china-air-defense-systems-part-2-chinese-radars
https://forceindia.net/feature-report/the-tech-route
[Facility_2537.txt](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/9075429/Facility_2537.txt)
/

**Comment by CV60LCC19** [comment]
One proviso: NATO "A" band goes to 250 MHz, so this would place it at the extremely high end of the A band.  However, since multiple sources say the radar is a VHF/UHF radar, calling it an A/B band radar would more accurately (IMHO) capture its frequency range.

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
