### ISSUE TITLE
Update SLBM armament for Indian Arihant SSBN

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#168]
### DB Selector

DB3K

### Affected DBID(s)

656 INS Arihant SSBN

### Summary of Changes

Public Sources indicate either 12 K-15 SLBM (quad packed) or 4 K-4 SLBM, propose to add the new weapons to the DB3K and update SSBN armament from the current Agni III.

### Sources

http://www.hisutton.com/Vanquisher%20of%20Enemies%20-%20INS%20Arihant.html
http://www.hisutton.com/Revealed%20-%20INS%20Arihant%20SSBN.html
https://www.navalnews.com/naval-news/2021/05/5-years-of-submarine-secrecy-indias-unique-arihant-class-is-still-in-hiding/?fbclid=IwAR1T2n2-QEjRH-M-cLzhBF-gNiapoH1Zl7cl8DZG3aUQVvSDhYDSHS4dN8c
http://www.military-today.com/navy/arihant_class.htm
https://warontherocks.com/2019/01/angles-and-dangles-arihant-and-the-dilemma-of-indias-undersea-nuclear-weapons/
https://www.naval-technology.com/projects/arihant-class/
https://en.wikipedia.org/wiki/K-4_(missile)
https://en.wikipedia.org/wiki/Sagarika_(missile)
https://en.wikipedia.org/wiki/Arihant-class_submarine
https://www.naval-technology.com/news/newsindian-navys-k-15-slbm-successfully-completes-development-trials/
http://www.ipcs.org/comm_select.php?articleNo=3870
https://www.armscontrol.org/act/2020-03/news/india-tests-submarine-launched-missile
https://thediplomat.com/tag/k-15-submarine-launched-ballistic-missiles/
https://thediplomat.com/tag/k-4-slbm/
https://www.globalsecurity.org/wmd/world/india/k-4.htm

![INS_Arihant_updated940](https://user-images.githubusercontent.com/99599482/154345719-86e13c31-7dea-40d7-a304-b2cfe09fd04b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Actually already handled this earlier in the cycle as part of a deeper review of the Arihant-class (spurred by a news roundup flagging the new S 4).
