### ISSUE TITLE
Pantsir-SM acquisition radar RLM-SOC increase range to 40nm(75km)

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#1683]
### DB Selector

DB3K

### Affected DBID(s)

3250

### Summary of Changes

Currently in game Pantsir-SM acquisition radar RLM-SOC has a max range of 30nm, the same as older Pantsir-S1

However Pantsir-SM acquisition radar has max reported radar range of 75km (40nm), which is 10nm more than regular Pantsir-S1 at 30nm

So RLM-SOC acquisition should be increased to 40nm for Pantsir-SM

Wikipedia: "The Pantsir-SM variant incorporates a multi-functional targeting station, increasing target detection range from 40 to 75 km (25 to 47 mi) and engagement range from 20 to 40 km (12 to 25 mi)."

globalsecurity: "The latest “Shell-SM”, thanks to the multifunctional aiming radar with a phased array, is now capable of detecting air targets at ranges up to 75 kilometers"

armyrecognition: "The Pantsir-SM-SV is equipped with a multi-functional targeting radar station, increasing target detection range from 40 to 75 km"

### Sources

https://www.globalsecurity.org/military/world/russia/pantsyr-sm.htm

https://www.armyrecognition.com/weapons_defence_industry_military_technology_uk/russian_pantsir-sm-sv_tracked_version_of_pantsir_air_defense_system_will_be_completed_in_2022.html

https://en.wikipedia.org/wiki/Pantsir_missile_system#Pantsir-SM

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
Handled 496.

**Comment by TheBagelInhaler** [comment]
> Handled 496.

thank you!!!!!!
