### ISSUE TITLE
Serbia Pantsir-S2E missing Hot Shot acquisition radar

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#1684]
### DB Selector

DB3K

### Affected DBID(s)

3432

### Summary of Changes

Serbian Pantsir-S2E missing acquisition radar which should be SOTS hot shot with max range of 30nm

Pantsir-S2 have newer SOTS acquisition Hot Shot upgraded acquisition radar with ranges of up to 30nm. Radar is janus faced 2 sided

here is Serbia's Pantsir-S2, you can see larger newer acquisition radar than what the Pantsir-S1 uses
![Serbia-receives-first-Pantsir-S1-systems-from-Russia](https://user-images.githubusercontent.com/108960393/178085532-eaf6796f-caa7-4b25-8f9b-2a9c24968f51.jpg)

here is Pantsir-S1 with older smaller acquisition radar
![Pantsir-S1](https://user-images.githubusercontent.com/108960393/178085554-2fdb2a88-3776-46d3-9400-5bede91fdeeb.jpg)

2x SOTS acquisition radar should be added to the Serbian Pantsir-S2E unit to realistically reflect

here is the SOTS acquisition radar for Pantsir-S2 with max range of 55km
![psr-3](https://user-images.githubusercontent.com/108960393/178085862-6369ab0b-ad44-45c6-8bc7-27ea8f9aca61.jpg)

### Sources

https://twitter.com/GuyPlopsky/status/1256602701523062788

https://twitter.com/PeterVoinovich/status/1256551099768508416

http://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/pantsir-s2_short-range_cannon_missile_air_defense_system_technical_data_sheet_specifications_pictures_video_12205164.html

**Comment by TheBagelInhaler** [comment]
Just noticed that the Hot Shot is actually included in the mounts but doesn't show up under sensors. Still the range is too short at 17nm for the SOT-S S-Band acquisition radar - it is 55-60km so 30nm is more realistic.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
