### ISSUE TITLE
Add Belarusian 59N6 Protivnik-GE Radar 2017

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1689]
### DB Selector

DB3K

### DBID to Copy

3149

### Hypothetical

No

### Name

Radar (59N6 Protivnik-GE)

### Country

Belarus

### Service

Air Force

### In Commission

2017

### Sources

https://twitter.com/Ukropo4kA/status/765660011947290624
https://twitter.com/ArmyRecognition/status/766203248567025664
https://www.shephardmedia.com/news/digital-battlespace/protivnik-3d-radar-enters-service-belarus/

Sipri Line
(7)	Protivnik-GE	air search radar	(2014)	2016-2020	(7)

**Comment by Jkryos** [comment]
Added DB3K 496.
