### ISSUE TITLE
Add Trophy APS to German 2A7 Leopard MBT 2021, US M1 Abrams 2017

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#169]
### DB Selector

DB3K

### Affected DBID(s)

2954 Leopard 2A7 Germany,  2719 M1A2 SEP United States

### Summary of Changes

German 2A7 Leopard (Facility #2954) fleet has received Trophy APS from 2021. Matters as it makes a harder target to hit. Trophy MAWS exists in DB as does weapon in facility #2447. Sighted on US M1A2s from 2017.

### Sources

https://twitter.com/nicholadrummond/status/1395733489543176193
https://taskandpurpose.com/news/army-m1-abrams-trophy-active-protection-system-europe/
https://www.thedrive.com/the-war-zone/14966/images-emerge-of-m1a2-abrams-tank-equipped-with-trophy-active-protection-system
https://breakingdefense.com/2018/02/261-m1-tanks-getting-trophy-anti-missile-system-as-army-reorients-to-major-wars/
https://taskandpurpose.com/military-tech/m1-abrams-active-protection-system/
https://www.popularmechanics.com/military/weapons/news/a28576/us-army-tanks-to-get-active-protection-systems-by-2020/
https://www.thedrive.com/the-war-zone/14748/us-army-buys-israeli-trophy-system-so-its-tanks-can-blast-incoming-projectiles
https://www.strategypage.com/htmw/htarm/articles/20200814.aspx

<img width="488" alt="message-editor_1507541688114-screenshot2017-10-09at1 55 50am" src="https://user-images.githubusercontent.com/99599482/154345091-52d0e442-d1db-4253-8666-c0d325642120.png">

![maxresdefault](https://user-images.githubusercontent.com/99599482/154345545-8a13bb93-d5cd-4c79-b0a0-8d69ec26987a.jpg)

**Comment by PygmalionOfCyprus** [comment]
Ironically we did actually model this on the M1A2C/Ds (SEPv3/4) in the _Ground Units_ annex...but fat lot of good that does anyone until that gets pushed to Commercial. I'll see about creating some new armored elements in the Facility annex to represent this.

**Comment by tbrandon517** [comment]
You all are the best!

**Comment by PygmalionOfCyprus** [comment]
Added 494.
