### ISSUE TITLE
Spoon Rest D OODA Cycle too Short

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1690]
### DB Selector

DB3K

### Affected DBID(s)

265

### Summary of Changes

Spoon Rest D  OODA cycle is set at 15 seconds.  This is an MTI radar using an old fashioned delay line canceller.
With a scan of 3 to 6 RPM, an OODA cycle of 15 seconds is far too quick.  It would be 25 seconds at best (2 scans plus a few seconds for the processing and the operator to declare a contact), possibly much longer.

The 'so what' of this reuest is that it isn't only this radar that is overgenerous on the OODA cycle.

### Sources

Not sure this one requires a source, it seems to be just an interpretation issue of the maths of radars.

**Comment by PygmalionOfCyprus** [comment]
All current OODA values are effectively moot for 496 due to upcoming CSGen implementation. Would welcome your response to this comment as I tweak the generation values, but whatever I settle on it's going to be equal or greater to 25s for old mechanical radars.
