### ISSUE TITLE
Add Belarusian Mig-29BM (2004), 9-13 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1692]
### DB Selector

DB3K

### DBID to Copy

5795

### Hypothetical

No

### Name

Mig-29BM

### Country

Belarus

### Service

Airforce 

### In Commission

2004

### Number in Service

8

### Other Changes

Upgraded Mig-29, 9-13 to BM in 2015. Sources say close to SMT. 

### Sources

https://twitter.com/CombatAir/status/1270035472060989443
https://www.scramble.nl/planning/orbats/belarus/belarus-air-force
https://twitter.com/Defense_Talks/status/1386009761288699904
https://twitter.com/BelarusInSweden/status/1396491289642819594
https://www.4aviation.nl/wp-content/uploads/2020/01/Belarus-jun19-Air-Forces-Monthly-2020-01-Stefan-Goossens.pdf

**Comment by bostonmyk** [comment]
Couldn't find any pictures of them mounting Adders in Belarussian service so weapon was not likely bought.

**Comment by PavelNovak79** [comment]
This upgrade is from MiG-29 (9.13), not 9.13S which I doubt Belarus had any.

**Comment by bostonmyk** [comment]
Updated. Thanks!

Mike

**Comment by Jkryos** [comment]
Added DB3K 496.
