### ISSUE TITLE
Add Belarusian Mig-29S Fulcrum C,  9-13

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1693]
### DB Selector

DB3K

### DBID to Copy

741

### Hypothetical

No

### Name

Mig-29 Fulcrum C, 9-13

### Country

Belarus

### Service

Airforce

### In Commission

1991

### Other Changes

4 to 8 Modernized to BM. See separate entry

### Sources

https://twitter.com/CombatAir/status/1269678851308879873
https://commons.wikimedia.org/wiki/File:Belarus_Air_Force_Mikoyan-Gurevich_MiG-29_%289-13%29_Pichugin-1.jpg
https://theaviationist.com/2013/09/26/belarus-migs/
https://www.airplane-pictures.net/photo/1029391/45-belarus-air-force-mikoyan-gurevich-mig-29/

**Comment by PavelNovak79** [comment]
Here I would allow myself to oppose a little. Belarus surely had MiG-29 (9.13) which was produced for Soviet AF from about 1986/87 but I doubt that they got any MiG-29S (9.13S) which is later modification produced in minimal number.

None of the listed sources shows 9.13S variant, only basic 9.13. So correct version should be added to Belarus in database.

**Comment by PavelNovak79** [comment]
Web page with info about Belarus MiG-29 strength since 1991:

http://mig.mariwoj.pl/mig-29-bg.htm

**Comment by bostonmyk** [comment]
Thanks Pavel. Fixed
