### ISSUE TITLE
Add Belarusian SU-24MR Fencer E

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1696]
### DB Selector

DB3K

### DBID to Copy

2647

### Hypothetical

No

### Name

SU-24MR Fencer E

### Country

Belarus

### Service

Airforce 

### In Commission

1992-2012

### Number in Service

x12

### Sources

https://www.4aviation.nl/wp-content/uploads/2020/01/Belarus-jun19-Air-Forces-Monthly-2020-01-Stefan-Goossens.pdf
https://www.jetphotos.com/photo/9317321
https://www.airliners.net/photo/Belarus-Air-Force/Sukhoi-Su-24M/2323756/L
https://www.milavia.net/airforces/reports/belarusian-air-force/

**Comment by Jkryos** [comment]
Added DB3K 496.
