### ISSUE TITLE
Add Belarusian SU-24M Fencer D

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1697]
### DB Selector

DB3K

### DBID to Copy

470

### Hypothetical

No

### Name

SU-24M Fencer D

### Country

Belarus

### Service

Air Force

### In Commission

1992-2012

### Number in Service

30x

### Sources

https://www.4aviation.nl/wp-content/uploads/2020/01/Belarus-jun19-Air-Forces-Monthly-2020-01-Stefan-Goossens.pdf
https://commons.wikimedia.org/wiki/File:Belarusian_Su-24_Fencer_at_Radom_AS_2009.JPG
https://www.airplane-pictures.net/photo/142628/42-belarus-air-force-sukhoi-su-24m/
https://www.milavia.net/airforces/reports/belarusian-air-force/

**Comment by Jkryos** [comment]
Added DB3K 496.
