### ISSUE TITLE
Update #5136 P-8 LSRS to carry AN/APS-154 AAS replacing AN/APS-149

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#17]
### DB Selector

DB3K

### Affected DBID(s)

5136

### Summary of Changes

US integrated a larger LSRS radar starting in 2020. Its an AESA, definitely periscope spotting flag. Murky details and there is some suggestion it could detect submarines (which probably means high power and frequency although sub detection is not impossible but questionable) I'd upgrade it to something close to E-8 and give it the advanced flags.

### Sources

https://www.thedrive.com/the-war-zone/33289/behold-these-awesome-shots-of-a-navy-p-8a-poseidon-carrying-its-big-secretive-radar-pod
https://www.thedrive.com/the-war-zone/33482/navy-p-8-with-secretive-radar-pod-surveils-massive-chinese-naval-base-in-south-china-sea
https://www.thedrive.com/the-war-zone/33289/behold-these-awesome-shots-of-a-navy-p-8a-poseidon-carrying-its-big-secretive-radar-pod
https://112.international/politics/submarines-may-have-nowhere-to-hide-with-us-navy-set-to-field-radical-new-radar-56830.html
https://www.globalsecurity.org/intell/systems/aas.htm
https://www.forbes.com/sites/davidhambling/2020/11/16/new-us-navy-airborne-radar-may-spot-submerged-submarines/?sh=18ce1f0e55d4
https://twitter.com/cvvhrn/status/1420909541743501320
https://twitter.com/BackyardSpotter/status/1421841597268905984/photo/1
https://www.jetphotos.com/photo/9402206

**Comment by PygmalionOfCyprus** [comment]
Added 493. (Obviously with estimated stats, mostly just changing up the flags on the 149.) Also added comments to all the US P-8s to better distinguish the changes in each year.
