### ISSUE TITLE
Update to DBID 303 PL-20120 Sarov mounts

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#170]
### DB Selector

DB3K

### Affected DBID(s)

DBID 303 PL-20120 Sarov

### Summary of Changes

OSINT indicates Sarov has one launch tube for Poseidon/Status-6/Kanyon torpedo as a test vessel.

Request the addition of a single launch tube and weapon for the unit in the DB3K

### Sources

http://www.hisutton.com/Sarov_Submarine_update.html
http://www.hisutton.com/SAROV-Class_Submarine.html

![Sarov_schematic](https://user-images.githubusercontent.com/99599482/154344834-12418df9-79e7-432a-a164-031f873e260d.jpg)

**Comment by tbrandon517** [comment]
I think you meant to add the submarine label and not ship.

**Comment by PygmalionOfCyprus** [comment]
So I did! Anyway, added 493.
