### ISSUE TITLE
Add Belarusian Mi-8MT Hip H

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1700]
### DB Selector

DB3K

### DBID to Copy

616

### Hypothetical

No

### Name

Mi-8MT Hip H

### Country

Belarus

### Service

Air Force

### In Commission

1992

### Sources

https://www.scramble.nl/planning/orbats/belarus/belarus-air-force
https://www.4aviation.nl/wp-content/uploads/2020/01/Belarus-jun19-Air-Forces-Monthly-2020-01-Stefan-Goossens.pdf
https://www.airliners.net/photo/Belarus-Air-Force/Mil-Mi-8MT/1553741

**Comment by Jkryos** [comment]
Added DB3K 496.
