### ISSUE TITLE
Romania - PRN-122 122mm Rocket

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1707]
### DB Selector

DB3K

### DBID to Copy

2907 - S-13OF 122mm Rocket [HE/FRAG]

### Hypothetical

No

### Name

PRN-122 122mm Rocket

### Country

Romania

### Service

Air Force

### Other Changes

Again not much information available. What is known is that the double launch rail with 2 rockets has a mass of 160kg.

### Sources

https://www.rumaniamilitary.ro/proiectile-reactive-nedirijate-prnd#prettyPhoto

![](https://rumaniamilitary.files.wordpress.com/2012/01/9g.jpg)

![](https://rumaniamilitary.files.wordpress.com/2012/01/9c.jpg)

![](https://rumaniamilitary.files.wordpress.com/2012/01/9a-prn-122.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
