### ISSUE TITLE
Yasen-M with SS-N-33/3M-22 Zircon in VLS

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1711]
### DB Selector

DB3K

### Affected DBID(s)

submarine #677

### Summary of Changes

Evidence has shown that Pr 885M (Yasen-M) SSN has already been able to carry Zircon hypersonic AShM by its VLS.

### Sources

https://www.youtube.com/watch?v=KsDLvHO05MU
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2021/november/10938-russian-project-885m-submarine-perm-will-be-the-first-tsirkon-sub-carrier.html

**Comment by PygmalionOfCyprus** [comment]
Added 2024 version of Yasen-M w/ Zircon-capable VLS for 496.
