### ISSUE TITLE
Canada CU-175 Puma II AE (RQ-20B) 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1713]
### DB Selector

DB3K

### DBID to Copy

5561 DB3K

### Hypothetical

No

### Name

CU-175 Puma II AE

### Country

Canada

### Service

Navy

### In Commission

2018-

### Sensors

- 1x Mantis i45 sensor suite consisting of electro-optical (EO), infrared (IR) and low-light cameras and a laser illuminator and a 360 degrees antenna system

### Other Changes

For use on Kingston Class MCDV's, hand launched.

### Sources

https://web.archive.org/web/20210616175558/https://www.navy-marine.forces.gc.ca/en/news-operations/news-view.page?doc=advanced-unmanned-aircraft-to-provide-eye-in-the-sky-for-kingston-class-ships/jsagj4mt
https://connexdrones.com/the-royal-canadian-navys-puma-ae-drone/
https://www.avinc.com/images/uploads/product_docs/PumaAE_Datasheet_2017_Web_v1.1.pdf
https://www.cfc.forces.gc.ca/259/290/405/305/kenward.pdf
![8bsuzqffacj41](https://user-images.githubusercontent.com/99632305/178334742-de2ef83d-4843-4334-a639-304acaac3473.jpg)

![8bsuzqffacj41](https://user-images.githubusercontent.com/99632305/178334749-d5d9402e-8a99-4039-81fa-acf3e3233023.jpg)

![drone-puma3](https://user-images.githubusercontent.com/99632305/178335258-509a1dc5-f130-4691-acde-148b2fcfde78.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
