### ISSUE TITLE
Canada CU-173 Raven B (RQ-11B)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1714]
### DB Selector

DB3K

### Hypothetical

No

### Name

Canada CU-173 Raven B

### Country

Canada

### Service

Army 

### In Commission

2014-

### Length (m)

0.9

### Wingspan (m)

1.4

### Height (m)

.225

### Empty Weight (kg)

.906

### Maximum Takeoff Weight (MTOW) (kg)

.906

### Crew

0

### Propulsion

1x Aveox 27/26/7-AV electric motor

### Service Ceiling (ft)

500 typical operating, max 14000

### Military/Afterburner Speed (kt)

44

### Cruise Speed (kt)

16

### Supercruise

No

### Ferry Range (nm)

5.3

### Endurance (min)

90

### Takeoff / Landing Distance (m)

Hand launched

### Sensors

- Raven Gimbal is a rotating camera with a 360-degree gimbal, which replaces the fixed camera that required maneuvering the aircraft to observe. The new camera can be switched between day and night settings without landing and swapping sensors.

### Mounts

- No weapons

### Loadout Options

- recon EO/IO

### Sources

https://canadianarmytoday.com/blackjack-army-hits-21-with-new-ace-in-the-sky/
https://web.archive.org/web/20151117122747/https://www.avinc.com/downloads/AV_RAVEN-DOM_V10109.pdf
https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104533/rq-11b-raven/
https://en.wikipedia.org/wiki/AeroVironment_RQ-11_Raven
![300px-Raven_UAV_flying](https://user-images.githubusercontent.com/99632305/178338621-7e0d27ef-fe6f-4577-980a-5bbfec6fde63.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
