### ISSUE TITLE
Correct the Chinese shipboard radars on Type 052D/DL DDG and 055 CG 

### ISSUE THREAD

**Issue by ywturbo** [PygmalionOfCyprus/cmo-db-requests#1719]
### DB Selector

DB3K

### Affected DBID(s)

#2296; #3586; #3587; #2834; #3883; #5127; #6093

### Summary of Changes

In DB3K, Chinese shipboard radar Type 346A and 346B are single X-band radars for both search/track and FC/illumination; however, the two radars should be dual-band, S-band for search/track and X-band for FC/illumination.
In additon, there are no China Type 349A, Type 364, Type 517H-1 and Type 760 radars on Type 055 CG. Instead an "Integrated RF System" was utilized, including C-band and L-band radars, although their model and performance with little detailed sources.

### Sources

https://www.globalsecurity.org/military/world/china/type-055-radars.htm
https://en.wikipedia.org/wiki/Type_055_destroyer#cite_note-Joe_2018-06-08-8
https://en.wikipedia.org/wiki/Type_346_radar

**Comment by cdnice55** [comment]
Additional resources that may help:
https://www.navyrecognition.com/index.php/focus-analysis/naval-technology/5374-analysis-sensor-and-electronic-warfare-suites-aboard-china-s-type-055-destroyer.html
https://thediplomat.com/2018/06/all-you-need-to-know-about-chinas-new-stealth-destroyer/

**Comment by PygmalionOfCyprus** [comment]
All PLAN vessels ripped out and totally rebuilt as part of the China review.
