### ISSUE TITLE
VB-1 and VB-2 AZON

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#172]
### DB Selector

CWDB

### User(s)

US B-17 and B-24 bombers

### Weapons Carried

4x VB-1 or VB-2 AZON (B-24)

2x VB-1 or VB-2 AZON (B-17)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as existing M66 2000 lb bomb loads

### Weather Restrictions

Clear Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

No

### Comments

Name: VB-1 and VB-2 AZON

Purpose: Command Guided Glide Bomb

Platforms: When used in combat, it was dropped from a modified Consolidated B-24 Liberator (the 458th Bombardment Group in Europe and the 493rd Bomb Squadron in the CBI Theater), with earlier development test drops of the AZON in the United States sometimes using the B-17 Flying Fortress as the platform.

Summary Details: AZON (AZimuth ONly guidance kit for a standard 1000lb bomb (VB-1) or 2000lb bomb (VB-2). The ability to only control the path of the bomb in the azimuth direction, made AZON bombs most suitable for long and narrow targets, such as bridges or railways. A disadvantage of using an AZON bomb was that after a bomb was dropped the bomber could not break way immediately because the bombardier had to keep the bomb in view so he could guide it. The bombardier used a BC-1156 joystick control to adjust the course left or right. The directional commands were sent to the guidance package via a special-purpose radio system.

Size of the guidance kits limited use to the 2000lb bomb racks even for the 1000lb VB-1 so loadouts for both would carry the same number of weapons. VB-1 would see a performance increase from reduced payload weight. (1 source indicates occasionally 5-6 were carried, this seems possible as the source agrees in the reason for limits as others. Another source states carriage was 8 vb-1 or 4 vb-2 as per regular bombs, I think that is the least reliable, it seems to assume based on weight)

### Sources

https://en.wikipedia.org/wiki/Azon

https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196234/vb-1-azon-guided-bomb/

https://www.designation-systems.net/dusrm/app1/vb.html

https://www.criticalpast.com/video/65675037317_Testing-of-AZON_dimensions-of-VB1_AZON-Impacting_first-smart-bomb

https://bulletpicker.com/guided-missile_-air-to-surfa32.html

[The Azimuth “Smart” Bombs of World War II - Warfare History Network](https://warfarehistorynetwork.com/2016/12/12/the-azimuth-smart-bombs-of-world-war-ii/)

http://michaelhiske.de/Allierte/USA/USNBD/USA/BombsAndFuzesUS/Section01/Part04/Page055.htm

https://forum.warthunder.com/index.php?/topic/449171-b-24j-liberator-with-vb-1-and-vb-2-azon-bombs/

https://www.researchgate.net/publication/261808009_Near_Miss_The_Army_Air_Forces%27_Guided_Bomb_Program_in_World_War_II_review

https://www.jstor.org/stable/resrep13886.6?seq=1#metadata_info_tab_contents
https://media.defense.gov/2017/Dec/28/2001861715/-1/-1/0/T_BLACKWELDER_ROAD_TO_DESERT.PDF

http://www.alternatewars.com/WW2/Papers/Case_History_AZON.htm

https://books.google.com/books?id=MisjEAAAQBAJ&pg=PT168&lpg=PT168&dq=vb-1+azon&source=bl&ots=dO4TVwSnKW&sig=ACfU3U3HLerHu3_BRJdjvyYW8KVA9VvUMg&hl=en&sa=X&ved=2ahUKEwjexvLo_az0AhVeTjABHQDEBMc4ChDoAXoECCIQAw#v=onepage&q=vb-1%20azon&f=false

https://weaponsandwarfare.com/2021/07/31/guided-bombs-in-korea/

https://web.archive.org/web/20120306191038/http://www.netcore.us/1/afm/azonbomb.html

https://web.archive.org/web/20101018222453/http://8thafhs.org/combat1944b.htm

https://www.458bg.com/azonproject.htm

http://www.ausairpower.net/WW2-PGMs.html#mozTocId939018

https://www.youtube.com/watch?v=3WDDpCQVRag

https://www.youtube.com/watch?v=WkJdlxG_6Aw

![Azon_-_the_worlds_first_smart_bomb](https://user-images.githubusercontent.com/99599482/154344241-cbb4db56-7027-4f66-bc62-c98f74771d33.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
