### ISSUE TITLE
Maximum range of the fifth generation RADS Spike NLOS missile

### ISSUE THREAD

**Issue by trujillocorreo** [PygmalionOfCyprus/cmo-db-requests#1721]
### DB Selector

DB3K

### Affected DBID(s)

2788

### Summary of Changes

Please increase the maximum range of the fifth generation RADS Spike NLOS missile to 30 kms. Well-known user, Colombia in its ARPIA IV helicopters as of 2018.

### Sources

https://www.matrixgames.com/forums/viewtopic.php?p=4534563#p4534563
https://www.rafael.co.il/wp-content/uploads/2019/03/Spike-NLOS.pdf
https://www.infodefensa.com/texto-diario/mostrar/3129463/fuerza-aerea-colombiana-emplea-misiles-spike-nlos-5-generacion
![MSPO_2019_anti-aircraft_and_anti-tank_missiles_from_RAFAEL_Advanced_Defense_Systems_LTD_925_003](https://user-images.githubusercontent.com/109195286/178648472-1619ff8a-f60b-40b5-8035-4f447487bef5.jpg)

**Comment by PygmalionOfCyprus** [comment]
Tweaked range for 496; Arpia IV already has Spike NLOS loadouts.
