### ISSUE TITLE
Update/correction for BUK M2/3 and HQ-16A/16B missiles

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1725]
### DB Selector

DB3K

### Affected DBID(s)

9M317 (1144), HQ-16A (2449), HQ-16B ( 3392) & 9M317M  (2970)

### Summary of Changes

-Increase the maximum targeting speed from 1600 knot to 2330 knot (1200 m/s) for 9M317 (DBID 1144)/HQ-16A (DBID 2449) / 
 HQ-16B (DBID 3392) and 5832 knot(3000 m/s) for 9M317M (DBID 2970). The missiles can engage at least Tactical Ballistic 
 Missile(TBM) around that speed.

![image](https://user-images.githubusercontent.com/99646926/178731003-dcad528d-9f12-4c71-8035-f3b43d1a0e07.png)

![image](https://user-images.githubusercontent.com/99646926/178731620-03fe2e7d-1de6-497b-b74c-0bfc0bfd165c.png)

### Sources

https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/buk-m3_9k317m_medium-range_air_defense_missile_system_technical_data_sheet_specifications_11312154.html#:~:text=The%20Buk-M3%20is%20able%20to%20destroy%20any%20type,but%20can%20also%20engage%20ground%20and%20sea%20targets.

https://www.globalsecurity.org/military/world/russia/buk-m3.htm

https://www.globalsecurity.org/military/world/russia/sa-17-specs.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
