### ISSUE TITLE
Update for KM-SAM Block 2 missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1726]
### DB Selector

DB3K

### Affected DBID(s)

3596 KM-SAM Block 2

### Summary of Changes

Increase the target speed from 2300 knot to at least 4500 knot and add "guided weapon - ballistic missile" into WRA just like SA-N-21C(2695). The missile is intended for anti-missile role to complement KM-SAM block 1.

![image](https://user-images.githubusercontent.com/99646926/178738415-6ba8972e-ad9a-4ab3-befd-fb42fbe34dfa.png)

### Sources

https://missiledefenseadvocacy.org/defense-systems/km-sam-cheolmai-2/

https://en.wikipedia.org/wiki/KM-SAM

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
