### ISSUE TITLE
UAE - UH-60M Blackhawk Gunship, Group 18 Special Operations Squadron

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1729]
### DB Selector

DB3K

### DBID to Copy

#4671

### Hypothetical

No

### Name

UH-60M Blackhawk Gunship, Group 18 Special Operations Squadron

### Country

UAE

### Service

Air Force

### In Commission

2011-

### Number in Service

Uncertain # of units fitted gunships

### Sensors

EO/IR Turrets

### Mounts

2x 7.62mm Miniguns mounted in their crew chief windows

### Loadout Options

Fitted for

2-4x 70mm rocket pods and launch rails for Hellfire missiles on stub wings
2x .50 caliber GAU-19/B rotary-barrel machine guns 

### Other Changes

This is similar to the configuration the U.S. Army 160th SOAR uses for its MH-60 Direct Action Penetrators (DAP).

### Sources

https://www.thedrive.com/the-war-zone/33564/uae-special-operations-gunships-train-on-the-navys-huge-sea-base-in-the-persian-gulf

![image](https://user-images.githubusercontent.com/99599482/178768050-8bbd0be8-b77f-46eb-9e8f-17a45f581cc5.png)
![image](https://user-images.githubusercontent.com/99599482/178768205-cf0e0410-62d0-4798-9b61-9c48ec7eda26.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
