### ISSUE TITLE
VB-3 and VB-4 RAZON

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#173]
### DB Selector

CWDB

### User(s)

US B-29 (operationally) B-17 (testing)

### Weapons Carried

Testing
1x VB-3 or VB-4 RAZON (B-17)
2x VB-3 or VB-4 RAZON (B-17)

Operationally
8x VB-3 or VB-4 RAZON (B-29)

Guidance Kit Size limited use to the 2000lb bomb racks even for 1000lb VB-3s. Performance increase for VB-3 from reduced payload. 

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as 2000lb M66 Loadouts

### Weather Restrictions

Clear Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

No

### Comments

Name: VB-3 and VB-4 RAZON

Purpose: Command Guided Glide Bomb

Platforms: When used in combat during Korea, it was dropped by the 19th Bomb Group from B-29 Superfortresses, with earlier development test drops of the in the United States using the MB-17 Flying Fortress as the platform.

Summary Details: standard 1000lb (VB-3) or 2000lb (VB-4) fiited with a radio command guidance kit. RAZON (for RAnge and AZimuth ONly) was based on the gudance kit used for its AZON (AZimuth-Only) predecessor.

### Sources

https://en.wikipedia.org/wiki/VB-3_Razon

https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196093/vb-3-razon-bomb/

http://www.designation-systems.net/dusrm/app1/vb.html

https://bulletpicker.com/guided-missile_-air-to-surfa33.html

https://447bg.org/artillary/vb3-razon/

http://michaelhiske.de/Allierte/USA/OrdnancePamphlets/OP1664/Volume02/Part07/Chapter21/Section04/Section04_02.htm

http://michaelhiske.de/Allierte/USA/USNBD/USA/BombsAndFuzesUS/Section01/Part04/Page057.htm

https://www.youtube.com/watch?v=U8aiVpaXOcw

https://media.defense.gov/2017/Dec/28/2001861715/-1/-1/0/T_BLACKWELDER_ROAD_TO_DESERT.PDF

https://www.michaelraska.de/research/PGM_History_M_Raska_2012.pdf

http://svsm.org/gallery/vb3

http://www.ausairpower.net/WW2-PGMs.html

https://www.airvectors.net/avsmw2.html

![VB-3-Razon-NMoUSAF-2018-05-17-0782 jpg-nggid0527870-ngg0dyn-700x392-00f0w010c010r110f110r010t010](https://user-images.githubusercontent.com/99599482/154343994-3e911ac7-e59f-401c-ae3c-7e75eb96374a.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
