### ISSUE TITLE
Libya - Il-78 Midas

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1730]
### DB Selector

DB3K

### DBID to Copy

#870

### Hypothetical

No

### Name

IL-78 Midas

### Country

Libya

### Service

Air Force

### In Commission

1989-

### Number in Service

1x, 6x planned

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2017/06/probe-and-drogue-story-of-libyas-ill.html

![image](https://user-images.githubusercontent.com/99599482/178775058-5c106c7b-32e3-400b-ac99-7ee2cf42db38.png)
![image](https://user-images.githubusercontent.com/99599482/178775092-bdad2738-e7b5-4f5e-ba5c-c23acd07ab92.png)

**Comment by tbrandon517** [comment]
Article recently updated. New Link.

https://www.oryxspioenkop.com/2022/08/probe-and-drogue-story-of-libyas-ill.html?m=1

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
