### ISSUE TITLE
Libya - C-130H Hercules

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1732]
### DB Selector

DB3K

### DBID to Copy

#2219

### Hypothetical

No

### Name

C-130H Hercules

### Country

Libya

### Service

Air Force

### In Commission

1971-Present

### Number in Service

8x, 16x Ordered, 1x in service with Air Force in 2022 with 3x in unknown condition, 1x with Libyan Dawn in 2022

### Sensors

No Change

### Mounts

1x converted in 1987-1988 by West German company Intec Technical Trade und Logistic (ITTL) as an Aerial Tanker with 2x Wing Drogues.

### Loadout Options

No Change

Plus 

1x Converted Tanker

### Other Changes

No Changes 

### Sources

https://www.oryxspioenkop.com/2017/06/probe-and-drogue-story-of-libyas-ill.html
https://www.flightglobal.com/download?ac=83735
https://en.wikipedia.org/wiki/List_of_Lockheed_C-130_Hercules_operators#Libya
https://en.wikipedia.org/wiki/Libyan_Air_Force#Aircraft

**Comment by tbrandon517** [comment]
Article recently updated.

New Link

https://www.oryxspioenkop.com/2022/08/probe-and-drogue-story-of-libyas-ill.html?m=1

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
