### ISSUE TITLE
Libya - An-124

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1733]
### DB Selector

DB3K

### DBID to Copy

#891

### Hypothetical

No

### Name

An-124 Condor

### Country

Libya

### Service

Libyan Arab Air Cargo

### In Commission

2001-2019

### Number in Service

2x; 1x seized by Ukraine in 2017, and 1x destroyed 2019

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Operator: Libyan Air Cargo (itself a de-facto part of the LAAF).

### Sources

https://www.oryxspioenkop.com/2020/09/an-124-article.html
https://en.wikipedia.org/wiki/Libyan_Arab_Air_Cargo
https://en.wikipedia.org/wiki/Antonov_An-124_Ruslan#Former_military_operators

![image](https://user-images.githubusercontent.com/99599482/178785221-9f896556-9b2c-4cbe-b098-9af675f6588f.png)
![image](https://user-images.githubusercontent.com/99599482/178785276-8a1b66da-933a-45b0-b92c-955ac3b7e7be.png)
![image](https://user-images.githubusercontent.com/99599482/178785311-48b1cfaf-ecb6-48f6-ac59-178120690afe.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
