### ISSUE TITLE
UAE - Arty Bty (M1989 240mm MLRS x 6)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1736]
### DB Selector

DB3K

### DBID to Copy

2352

### Hypothetical

No

### Name

Arty Bty (M1989 240mm MLRS x 6)

### Country

UAE

### Service

Army

### In Commission

1989-

### Number in Service

Unknown

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

As with MLRS supplied to the LNA in Libya, any reatined by the UAE likely converted to Turkish TR-122 122mm munitions.

### Sources

https://www.oryxspioenkop.com/2020/11/inconvenient-arms-north-korean-weapons.html

![image](https://user-images.githubusercontent.com/99599482/178790456-7d559e4c-9f5c-43f6-93bf-73624892f6c7.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
