### ISSUE TITLE
UAE - Arty Bty M1989 Koksan 170mm SPG x 6

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1737]
### DB Selector

DB3K

### DBID to Copy

2269

### Hypothetical

No

### Name

Arty Bty M1989 Koksan 170mm SPG x 6

### Country

UAE

### Service

Army

### In Commission

1989-

### Number in Service

Unknown

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/11/inconvenient-arms-north-korean-weapons.html

![image](https://user-images.githubusercontent.com/99599482/178791982-b9bbc666-3e00-4716-aab7-51e35b0b343f.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
