### ISSUE TITLE
Correction to Sound Levels of ROMEO (PL-633) class submarines

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1739]
### DB Selector

Both

### Affected DBID(s)

Submarine_339, 340, 250, 342, 409, 410, 408, 344, 266, 245, 679

### Summary of Changes

My recent discovery of the attached "Relative Detectability of PLAN submarines" from Office of Naval Intelligence , The People’s Liberation Army Navy, A Modern Navy with Chinese Characteristics (Aug 2009 at page 22) at https://irp.fas.org/agency/oni/pla-navy.pdf![Relative Detectability PLAN subs](https://user-images.githubusercontent.com/99547401/178790299-3585d37e-2095-4358-b863-d18e66816193.jpg) has led me to think we can possibly improve the overall modeling of many submarines using this chart.  To begin with, I am starting the the ROMEO SS, as that is one of the submarines that we have some actual sound level data on.  Over the next few posts, using the ROMEO as a benchmark, I'll try to refine other submarines classes:

According to Wikipeda the last upgrade to the Romeo was the ES5B, an upgrade package from the mid-1980's.   This upgrade reduced the noise level from 160 db to 140db. See  https://en.wikipedia.org/wiki/Romeo-class_submarine   This noise reduction figure was cited, but the link is now dead, so I can't confirm the 160 db level.  However, other sources repeat the 160 db level, but I can't be certain that they are merely quoting Wikipedia.  See  https://military-history.fandom.com/wiki/Romeo-class_submarine; https://odin.tradoc.army.mil/mediawiki/index.php/Type_033_Class_(Romeo_Class)_Chinese_Diesel-Electric_Submarine  Of note, the 160 db level was quoted for the ROMEO class aquired by the PLAN, so these may have been unusually noisy due to downgrades in equipment, manufacturing issues or poor maintenance. In any case, the Romeo was essentially a noisy WWII submarine design.  See https://naval-encyclopedia.com/cold-war/ussr/romeo-class-submarines.php.  

In E.V. Miasnikov The Future of Russia's Strategic Nuclear Forces: Discussions and Arguments (1995)
Center For Arms Control, Energy And Environmental Studies, Moscow Institute of Physics and Technology, Appendix 1 "What is known about the character of noise created by submarines?" (available at https://spp.fas.org/eprint/snf03221.htm), the author provides Table A1, describing a noisy submarine as having a level of 140 db in the 5-200 Hz range, and claims that WWII designs were om the 125-145 range (citing Urick, "Principles of Underwater Sound").  If this is the case, then the 160 db level for a baseline PLAN ROMEO becomes believable (due to maintenance and production issues) and a baseline 140 db level for newer/modified or Soviet ROMEOS.  This tracks relatively close with the 130-135 db level of the ZULU V (Project AV-611) given by  Miasnikov in Table A2.  See  https://spp.fas.org/eprint/snf03221.htm

All of this is consistent with the Soviet lack of understanding pre-Walker spy ring of the importance of submarine quieting.  Based on this, I would recommend increasing the noise levels of the above ROMEO class submarines to 135-160 db, from their current 115 db.  Here's the question: If you agree with my logic, I can do a correction request for the WHISKEY/ZULU/GOLF series of submarines, and then begin using this as a baseline, start to go through the PLAN submarines listed in the attached Relative Detectability of PLAN submarines"  chart to make guestimates of the noise levels.  Let me know if that plan works for you.

### Sources

https://irp.fas.org/agency/oni/pla-navy.pdf
https://en.wikipedia.org/wiki/Romeo-class_submarine
ttps://military-history.fandom.com/wiki/Romeo-class_submarine; 
https://odin.tradoc.army.mil/mediawiki/index.php/Type_033_Class_(Romeo_Class)_Chinese_Diesel-Electric_Submarine
https://spp.fas.org/eprint/snf03221.htm

**Comment by PygmalionOfCyprus** [comment]
>If you agree with my logic, I can do a correction request for the WHISKEY/ZULU/GOLF series of submarines, and then begin using this as a baseline, start to go through the PLAN submarines listed in the attached Relative Detectability of PLAN submarines" chart to make guestimates of the noise levels.

Let's do it.

**Comment by PygmalionOfCyprus** [comment]
Closed as redundant to #1858
