### ISSUE TITLE
VB-13 (later ASM-A-1) TARZON

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#174]
### DB Selector

CWDB

### User(s)

US B-29s, Potentially B-50 and/or B-36

### Weapons Carried

1x VB-13 (later ASM-A-1) TARZON (B-29/50)

2x VB-13 (later ASM-A-1) TARZON (B-36)

Guidance kit meant bomb was carried semi-recessed in an open bomb bay. Increased drag limited the carriage to 1 bomb (possible 2 for B-36 for a corresponding 50% ordnance reduction as 1 from 2 for Superfortress)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as existing Tallboy bomb loads

### Weather Restrictions

Clear Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

No

### Comments

Name: VB-13 (later ASM-A-1) TARZON

Purpose: Command Guided Glide Bomb

Platforms: When used in combat during Korea, it was dropped by the 19th Bomb Group from B-29 Superfortresses, Potentially also could have been used by B-36 bombers..

Summary Details: 12,000lb Tallboy bomb fitted with a RAZON command guidance kit.

### Sources

https://en.wikipedia.org/wiki/ASM-A-1_Tarzon

https://web.archive.org/web/20101225221858/http://www.nationalmuseum.af.mil/factsheets/factsheet.asp?id=1049

http://www.designation-systems.net/dusrm/app1/asm-a-1.html

https://www.britishpathe.com/video/selected-originals-bomb-with-a-brain

https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196092/vb-13-tarzon-bomb/

https://airandspace.si.edu/collection-objects/bomb-tarzon/nasm_A19680017000

https://dbpedia.org/page/ASM-A-1_Tarzon

https://media.defense.gov/2017/Dec/28/2001861715/-1/-1/0/T_BLACKWELDER_ROAD_TO_DESERT.PDF

https://weaponsandwarfare.com/2021/07/31/guided-bombs-in-korea/

https://apps.dtic.mil/sti/pdfs/ADA406542.pdf

https://www.jstor.org/stable/26275055

https://bulletpicker.com/guided-missile_-air-to-surfa35.html

![Bell_YASM-A-1_Tarzon](https://user-images.githubusercontent.com/99599482/154343479-878be933-e71d-4479-9d56-a304258275ff.png)

![220px-Tarzon_loaded_on_B-29](https://user-images.githubusercontent.com/99599482/154343850-fe3737d7-3b79-41be-9389-dd03313fe1a5.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
