### ISSUE TITLE
Update for DBID 3419 Shaldag Mk5 - Philippines

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1740]
### DB Selector

DB3K

### Affected DBID(s)

3419

### Summary of Changes

Looks like the current Spike ER are for the Multipurpose Assault Crafts while the missile armed Shaldags received NLOS, although the launcher should accommodate both I believe.

### Sources

https://www.jpost.com/israel-news/the-philippines-to-acquire-eight-shaldag-fast-patrol-boats-634783?fbclid=IwAR05_kyx12jxJd6iipxqCeQwD7L5qzQxY9SZBlwNPVTCN200MYMO_1sqej8
https://navalpost.com/philippine-navy-to-procure-shaldag-patrol-crafts/
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/july/11874-future-philippine-navy-s-shaldag-class-patrol-boat-tests-its-typhoon-30mm-cannon.html
https://www.navalnews.com/naval-news/2022/06/israel-shipyards-launches-first-two-fast-patrol-craft-for-philippine-navy/
https://www.philstar.com/headlines/2021/10/31/2137941/philippine-navy-tests-spike-er-missile
https://en.wikipedia.org/wiki/Spike_(missile)#Operators

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
