### ISSUE TITLE
Qatar - Coast Defense Battery

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1741]
### DB Selector

DB3K

### DBID to Copy

1677

### Hypothetical

No

### Name

SSM Bty (Exocet Blk III/ Marte ER)

### Country

Qatar

### Service

Navy

### In Commission

2022

### Number in Service

unknown

### Sensors

As 1677

### Mounts

As 1677

### Loadout Options

Update Missiles from Exocet Blk II to Exocet Blk III and Marte ER

### Sources

https://www.navalnews.com/naval-news/2022/05/qatars-coastal-defense-system-exocet-and-marte-er-by-mbda/?fbclid=IwAR1zKmGuZ8z-UDJgRbdsdxyiZZXxXRqx3-OdmzWAKjD0WYptZVAeD5xOFGM

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
