### ISSUE TITLE
Qatar - Air Defense LPD

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1742]
### DB Selector

DB3K

### DBID to Copy

DBID 2843

### Hypothetical

No

### Name

Modified Kalaat Béni Abbès LPD

### Country

Qatar

### Service

Navy

### In Commission

IOC 2026 or 2017

### Number in Service

1x

### Sensors

Kronos multifunction radar (similar to the one fitted on the corvettes) 
a new L-Band radar by Leonardo known as Kronos Power Shield
SAAM-ESD air-defence system
a secondary three dimensional search radar. This could be the same European Multifunction Phased Array Radar (EMPAR) found on the Kalaat Béni Abbès or a different unit.
Similar ECM to the Algerian units

### Mounts

1x 76mm Super Rapido
2x 8-cell VLS Sylver A50 for the Aster 30 Block 1
4x 25mm OtoBreda KBA
Sylena MK2  decoy launching systems

### Loadout Options

As 2843

### Other Changes

The main mission of the vessel will be air defense. It will work in conjunction with the Al Zubarah-class air defense corvettes and share long range air picture with them. Will provide a tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T.

### Sources

https://www.navalnews.com/naval-news/2022/05/fincantieri-lays-keel-of-qatars-air-defense-lpd/?fbclid=IwAR1_VnNb4yAQm85Bt1lRITk5yzf9WRii_wtXUF08Q7U8dO579lG4dg2bJPI
https://www.thedrive.com/the-war-zone/19394/qatar-is-getting-this-unique-amphibious-mother-ship-and-radar-picket-vessel-mash-up
https://www.naval-technology.com/news/fincantieri-begins-construction-of-qatari-emiri-navys-lpd/
https://www.navaltoday.com/2022/05/17/fincantieri-lays-keel-for-qatars-new-lpd/
https://www.globalsecurity.org/military/world/gulf/qenf-lpd.htm
https://www.navyrecognition.com/index.php/naval-news/naval-exhibitions/2018/dimdex-2018/6056-dimdex-2018-qatari-navy-showcasing-its-future-air-defense-lpd.html
https://en.wikipedia.org/wiki/Qatari_Emiri_Navy#Future_acquisitions

![image](https://user-images.githubusercontent.com/99599482/178804493-ee68fb01-da0d-403b-be07-410b20ed5ad4.png)
![image](https://user-images.githubusercontent.com/99599482/178807085-cb61127b-e990-4e89-8f55-12ac522b8cda.png)
![image](https://user-images.githubusercontent.com/99599482/178807106-592c5359-b9c3-439b-becf-3e81c400951d.png)
![image](https://user-images.githubusercontent.com/99599482/178807166-051c4bf2-2cb7-40f7-ba7a-b25e0f8841b6.png)
![image](https://user-images.githubusercontent.com/99599482/178807187-e52db7df-634b-4125-bfdc-af8a81c1af32.png)

**Comment by KushanGaming** [comment]
Done for DB497.

**Comment by tbrandon517** [comment]
@KushanGaming @PygmalionOfCyprus 

Al-Fulk as of dv v509 does.not have datalinks to share targeting information to the Doha class (ship 3272) as intended based on the TWZ article. The Doha class dies have Link 11 and Link 16 which I think are needed by the Al-Fulk to act as a sensor provider for AD/BMD.

**Comment by tbrandon517** [comment]
> @KushanGaming @PygmalionOfCyprus
> 
> Al-Fulk as of dv v509 does.not have datalinks to share targeting information to the Doha class (ship 3272) as intended based on the TWZ article. The Doha class dies have Link 11 and Link 16 which I think are needed by the Al-Fulk to act as a sensor provider for AD/BMD.

Capabilities would be useful in this scenario in testing 

https://www.matrixgames.com/forums/viewtopic.php?f=10233&t=408305
