### ISSUE TITLE
Il-96-400T freighter

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#1743]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4440 (DB3K)

### Hypothetical

No

### Name

IL-96-400T

### Country

Commercial

### Service

Commercial

### In Commission

2009

### Number in Service

Limited Production

### Sensors

No changes

### Mounts

No changes

### Loadout Options

Cargo (No Drop) 92 Tons, range 2700nm
Cargo (No Drop) 88 Tons, range 3000nm
Remove tanker loadouts

### Other Changes

Remove all aerial refueling capability in either direction from the base tanker model. 

### Sources

http://brinkley.cc/AC/il96t.htm

https://www.aircharterservice.com/aircraft-guide/cargo/ilyushin-russia/ilyushinil-96-400t

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
