### ISSUE TITLE
Boeing 747-8ZV BBJ VVIP

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1744]
### DB Selector

DB3K

### DBID to Copy

2537

### Hypothetical

No

### Name

Boeing 747-8ZV BBJ VVIP

### Country

Qatar, Turkey, Morroco

### Service

Qatar Amiri Flight, Turkish Airlines Government Flight, Moroccan Air Force

### In Commission

Qatar 2015-, Turkey 2018-, Morocco 2011-

### Number in Service

5x Qatar, 1x gifted to Turkey, 1x sold to Morocco, 1x Sold on the commerciall market

### Sensors

AN/AAQ-24(V) DIRC for 2x Qatari jets from 2019.

### Mounts

None

### Loadout Options

VIP Transport, 18 Crew, 89 PAX

### Sources

https://www.thedrive.com/the-war-zone/34649/this-qatari-747-8i-jumbo-jet-for-sale-may-be-the-worlds-most-lavish-flying-palace
https://www.thedrive.com/the-war-zone/23520/that-qatari-royal-flight-747-8i-thats-up-for-sale-just-made-a-very-strange-flight-to-istanbul
https://www.thedrive.com/the-war-zone/23001/qatari-royal-flight-747-8i-jumbo-jet-is-up-for-sale-and-yes-there-are-interior-pictures
https://www.thedrive.com/the-war-zone/24075/that-vvip-747-8i-jumbo-jet-qatar-gifted-to-erdogan-has-reemerged-wearing-turkish-colors
https://www.oryxspioenkop.com/2020/08/turkeys-presidential-fleet.html
https://en.wikipedia.org/wiki/Qatar_Amiri_Flight
https://en.wikipedia.org/wiki/Boeing_Business_Jet#Operators
https://www.planespotters.net/airline/Morocco-Government

Qatar VVIP Livery
![image](https://user-images.githubusercontent.com/99599482/178812491-b322208d-b89c-429d-a4b0-01088ad05208.png)

Qatar VIP Livery
![image](https://user-images.githubusercontent.com/99599482/178812756-9162cbef-e9cb-4abf-8922-e0a9815e9b8a.png)

Turkish Republic One
![image](https://user-images.githubusercontent.com/99599482/178814175-348857ce-7355-4fc8-97ac-82a62bbf410f.png)
https://1.bp.blogspot.com/-xIIYYZrzLuw/YFxY2VTkZUI/AAAAAAAAS8E/a9TpIofv6E8Zb0QZq-ggrtNjtjp2RUfSwCLcBGAsYHQ/s2048/47517744192_85b7a9bd5f_o.jpg

Moroccan Air Force
![image](https://user-images.githubusercontent.com/99599482/178814763-568e1e6d-8baa-49ca-9bff-6acaa4499b67.png)

**Comment by PygmalionOfCyprus** [comment]
Added as generic commercial 497.
