### ISSUE TITLE
GBU-53/B StormBreaker Seeker Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1746]
### DB Selector

DB3K

### Affected DBID(s)

2855

### Summary of Changes

Stormbreaker stated as having Millimeter wave Active radar homing / Semi-active laser guidance / Imaging Infrared homing.

Currently it is missing the laser seeker.

### Sources

https://en.wikipedia.org/wiki/GBU-53/B_StormBreaker
https://www.thedrive.com/the-war-zone/37050/stormbreaker-mini-glide-bomb-that-can-hit-moving-targets-in-any-weather-is-ready-for-war
https://www.thedrive.com/the-war-zone/43529/stormbreaker-mini-glide-bombs-take-longer-to-load-onto-strike-eagles-due-to-their-data-links

The tri-mode seeker for the StormBreaker smart weapon., Raytheon
![image](https://user-images.githubusercontent.com/99599482/178825246-35ab0eb1-0238-4a18-972e-a28758004e51.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
