### ISSUE TITLE
Russia - PL-877V Kilo - Kalibr Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1748]
### DB Selector

DB3K

### Affected DBID(s)

507

### Summary of Changes

Sole PL-877V Kilo completed Kalibr missile upgrade refit in 2022 followed by builders trials. Likely return to active service in 2023.

### Sources

https://www.thedrive.com/the-war-zone/russias-only-pump-jet-kilo-class-submarine-is-back-to-attack-ukraine?fbclid=IwAR3HXVN74aGR9gvbPBF209U_Qa4M_4zYU6hSwFmh0oEaZzFdsk1wNbO7NAA
http://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/june/11864-russian-black-sea-fleet-oldest-submarine-alrosa-armed-with-kalibr-missiles-to-undergo-sea-trials-soon.html

**Comment by HVAA** [comment]
Been in refit for the best part of 8 years, probably wont be 'match fit' till next year at the earliest.

**Comment by tbrandon517** [comment]
> Been in refit for the best part of 8 years, probably wont be 'match fit' till next year at the earliest.

Updated to reflect trials this year and probable return to active service in 2023.

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Not knowing much beyond the Kalibrs I've just given it the tubes/magazine from the 636.3 Kilo, giving it UGST/TEST 71M torps in addition to the cruise missiles. I figure they would have updated the torpedoes as well as giving it Kalibr capability.
