### ISSUE TITLE
BDK Kherson (Pr.11780)

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#1749]
### DB Selector

DB3K

### Baseline

150

### Hypothetical

Yes

### Name

BDK Kherson (Pr. 11780), Ivan Tarawa

### Class

Kherson-class

### Country

Soviet Union

### Service

Naval Fleet

### In Commission

1990

### Number in Service

2x planned

### Length (m)

196

### Beam (m)

35

### Draft (m)

8

### Standard Displacement (t)

25000

### Full Displacement (t)

30000

### Complement

1200

### Max Sea State

6

### Primary Propulsion Type

Steam

### Propulsion

4x Boilers, 2x Steam Turbines

### Fuel Capacity (kg)

20000

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

8000nm at 18 kts

### Sensors

Top Plate (MR-760 Fregat-MA)
Navigation:
3 Palm Frond (Volga)
Fire control:
Cross Sword (MR-360 Podkat)
Kite Screech (MR-123-02)
Tacan:
Cake Stand

### Mounts

1x AK-130
6x 8 cell SA-N-9 Gauntlet
4x CADS-N-1

### Aircraft & Docking Facilities

Pads and hangars for up to 25 Ka-27 sized helicopters
Dock for 4 Pr. 1176 or 2 Pr. 1206 landing craft 

### Comms/Datalinks

VHF/UHF/LF/HF Radio

### Ship Codes

Nuclear Shock Resistant, Degaussed Steel Hull

### Comments

Cargo ability: Up to 1,000 troops, 40 tanks, and 15 BTRs or 70 "pieces of equipment".

Someone with better radar recognition than me could see what's on the models in the linked sources, the sensors I put were what I found written down in one. 

### Sources

https://alternathistory.com/avianesushhij-universalnyj-desantnyj-korabl-dok-proekta-11780-nash-mistral-1980-h/

http://nevskii-bastion.ru/11780-udk/

https://raigap.livejournal.com/867498.html

https://www.reddit.com/r/WarshipPorn/comments/bdxnbl/project_11780_kherson_more_aptly_known_as/

**Comment by HVAA** [comment]
A pair of Strut Pair 2 radars each side of the superstructure, a bit like Kuznetsov.

**Comment by KushanGaming** [comment]
Done for DB497.
