### ISSUE TITLE
F-35's radar signature should be less than F-22's

### ISSUE THREAD

**Issue by Matharox** [PygmalionOfCyprus/cmo-db-requests#175]
### DB Selector

DB3K

### Affected DBID(s)

All F-35s and F-22s

### Summary of Changes

Adjust the radar signatures of the two accordingly 

### Sources

https://www.reddit.com/r/Dragon029/comments/30fa43/f35_vs_f22_b2_stealth_claims/

**Comment by PygmalionOfCyprus** [comment]
On hold pending completion of https://github.com/PygmalionOfCyprus/cmo-db-dev/issues/178

**Comment by PygmalionOfCyprus** [comment]
Handled w/ modifier overhaul.
