### ISSUE TITLE
Replace LST/Laser Spot Trackers of Indian Mig-27 (Klen) and Darin 2, Darin 3 (ARI-12321)Jags with Thales TVM-36

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1750]
### DB Selector

DB3K

### Affected DBID(s)

3815,3814,1187,2702

### Summary of Changes

Couldn't find much on a capability upgrade but TVM-36 is at least one generation newer and timing is paired with western laser-guided weapons integration. Probably a connection (literally ha!)

Check to be sure CPU-123 (955), Griffin (2403) work with these. Will need to add a CPU-123 loadout to the 2006 Mig-27

Replace ARI.to Indian Jaguar IS from Darin 2 on.
Later Mig-27's had this from 2002 too.(add to 1187 and change IOC to 2002)

### Sources

Darin 2 Jaguar IS
https://twitter.com/_devildog_rv_/status/1439240152497356800/photo/2
https://forums.bharat-rakshak.com/viewtopic.php?t=7787&start=40
https://twitter.com/RAFIndia_/status/1482047153468067848/photo/2

Mig-27
https://www.strategicfront.org/forums/threads/mikoyan-mig-27-bahadur-of-india-air-force.3612/page-2

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
