### ISSUE TITLE
Radar Update for D66 Visakhapatam [Pr.15b] 2361

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1751]
### DB Selector

DB3K

### Affected DBID(s)

2361

### Summary of Changes

Replace Nucleus with Add Scanter 6002

### Sources
https://www.everythingrf.com/News/details/5180-Terma-Tata-Advanced-Systems-to-Provide-Surface-Surveillance-Radar-for-the-Indian-Navy
https://fccid.io/N9MSC5000/User-Manual/User-Manual-MAM-606002-HT-1-E2-1-Volume-1-4479596
http://trishul-trident.blogspot.com/2021/11/garpun-bal-e-makes-way-ffor-scanter.html
https://en.wikipedia.org/wiki/Visakhapatnam-class_destroyer#/media/File:Visakhapatnam_(D66)_-_P15B_destroyer_of_Indian_Navy_during_sea_trials.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
