### ISSUE TITLE
Scanter 6002 Update

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1752]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5652

### Summary of Changes

Its an x-band 
Scan rate is 10-48 RPM or 40 RPM
ceiling is 6000 ft
can do IFF

### Sources

https://www.terma.com/media/sbxli2k2/termascanter6002_a4_dec2021.pdf
https://www.terma.com/media/jcvfkhrw/navalradarsurveillance_flyer_nov2021.pdf
https://fccid.io/N9MSC5000/User-Manual/User-Manual-MAM-606002-HT-1-E2-1-Volume-1-4479596
https://fccid.io/N9MSC5000/User-Manual/User-Manual-606002-HT-1-E2-1-Volume-2-4479648

**Comment by PygmalionOfCyprus** [comment]
All of these are currently reflected in the DB (at least my version). Either I ninja'd it while doing something else and don't remember or no change necessary.
