### ISSUE TITLE
Please modify entry # 565-SU-30MK2: (Venezuela)

### ISSUE THREAD

**Issue by trujillocorreo** [PygmalionOfCyprus/cmo-db-requests#1754]
### DB Selector

DB3K

### Affected DBID(s)

565

### Summary of Changes

Please modify entry # 565-SU-30MK2: (Venezuela):

-Designator laser mounted in the IRST-OEPS 30Mk, for the guide of air-ground precision weapons. Ex KH-29L
-Replace the DECM L-203 with the KNIRTI SPS-171 / L005S Sorbtsiya-S.
-Add missiles KH-29L.
-Add ARM KH-31P.
-Add R-27ET ALAMO-D.

### Sources

https://www.matrixgames.com/forums/viewtopic.php?p=4421442&sid=fedd3d04f990a7ae555db9b70fc0dc02#p4421442
![aa2002su30mk15](https://user-images.githubusercontent.com/109195286/179066027-9785e096-6e2b-4776-8956-54814a9a8137.jpg)
![su-30_19](https://user-images.githubusercontent.com/109195286/179066379-1b7b9cba-6e7c-4820-9e69-c9d4640155d1.jpg)
![Cg7Fd_hH](https://user-images.githubusercontent.com/109195286/179091414-3c5db253-880c-49be-8baa-7e40d5c1a780.jpg)
![BbZdgAS](https://user-images.githubusercontent.com/109195286/179091469-47fd306d-6b32-4f77-a420-ede17a109d2a.jpg)
![Oz5ussK](https://user-images.githubusercontent.com/109195286/179091527-25af80d4-63c0-4bbe-ab24-19c64617a138.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
