### ISSUE TITLE
Remove AAR capability on old variants of Su-27

### ISSUE THREAD

**Issue by rickywild69** [PygmalionOfCyprus/cmo-db-requests#1755]
### DB Selector

DB3K

### Affected DBID(s)

2155, 2156, 603, 2370, 134, 353

### Summary of Changes

All mass-produced variants of Su-27 for the local market except Su-27SM/SM3 don't have AAR capability

### Sources

https://en.wikipedia.org/wiki/Sukhoi_Su-27
https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=71

(you can find that AAR appeared only on demonstrator Su-27PD. Actually, AAR wasn't 'popular' in USSR/Russia tactical aviation, mostly used for strategic bombers)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
