### ISSUE TITLE
Add 4 Missile Heavy Loadouts to Mohajer-6 UCAVS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1756]
### DB Selector

DB3K

### User(s)

5021,5022, 5020, 5355,

### Weapons Carried

4 Qaem class weapons (Qaem 1, Qaem 5)

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://twitter.com/mhmiranusa/status/1482015648536571907
https://iranpress.com/content/52970/mohajer-6-uav-powerful-tactical-reconnaissance-and-combat-drone
https://twitter.com/ConflictsW/status/1335003088235663363/photo/1

**Comment by tbrandon517** [comment]
Related to request #1534

**Comment by PygmalionOfCyprus** [comment]
Already available as optional weapons on the Qaem 1 (and new Qaem 5) loadouts.
