### ISSUE TITLE
Further Ship Combat System Generation Updates (DB3K)

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#1757]
### DB Selector

DB3K

### Affected DBID(s)

#3866, #3867, #3868, #3871, #3872, and #3873

### Summary of Changes

**#3866 - BB 61 Iowa [Phase II] (United States - 1989)**: increase CS Gen 4 to CS Gen 5, unless already done in 496, because they have NTU and other late 1980s sensors, and to harmonize with other verions.
Ditto for #3867, #3868, #3871, and #3872.

**#3873 - CGBL Cruiser Baseline (United States - 2000)**: decrease CS Gen 6 to CS Gen 5. It has at best 1990s sensors.

**3875 - NApAnt (Brazil - 2025)**: reduce CS Gen 6 to None (Large Vessel) because it has no armament? Uncertain whether this is the rubric. Useful to know for further recommendations. Or it might be possible to set all unarmed ships to a 'None' type with a script.

### Sources

DB 495.

**Comment by nuk92** [comment]
This might be interesting: #1761

**Comment by tbrandon517** [comment]
In regards to the CGBL, since I don't have the beta installed, what are the comparable Ticos/Burkes from ~2000 timeframe rated as? The CGBL should match a contemporary Tico/Burke.

**Comment by PygmalionOfCyprus** [comment]
It's mostly Gen 5 for turn-of-the-century Burkes.
