### ISSUE TITLE
Add Qaem 5

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1758]
### DB Selector

DB3K

### Baseline

Qaem 1

### Hypothetical

No

### Name

Qaem 5

### Length (m)

1.41

### Width/Span (m)

.46m

### Diameter (m)

.15

### Weight (kg)

19

### Range (nm)

1-3.24

### Warhead

#202

### Targets

Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

1m

### Sensors

Optical/TV Guided

### Comments

The optically guided variant of Qiam. Little actual info but only slightly larger than Qiam 1 in photos. TV/Optical guidance seems to be the key difference. Later on, this should be restricted to day ops.
There is a Qaem 9 which is a larger variant of this missile. Can see it in the arms display photos.
Likely need an optical/TV datalink to the drones that use
Reliably of both Qiams probably ok but maybe lower. 

### Sources

https://twitter.com/mhmiranusa/status/1533292929518903296
https://www.janes.com/defence-news/news-detail/iran-holds-unveiling-event-for-precision-guided-bombs
https://www.tasnimnews.com/en/news/2019/08/06/2070274/iran-unveils-new-smart-bombs
https://twitter.com/BabakTaghvaee/status/1158812301031550976
https://www.globalsecurity.org/military/world/iran/qaem.htm

**Comment by tbrandon517** [comment]
Related to request #1534

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
