### ISSUE TITLE
KH-31A/AD flight pattern

### ISSUE THREAD

**Issue by trujillocorreo** [PygmalionOfCyprus/cmo-db-requests#1759]
### DB Selector

DB3K

### Affected DBID(s)

1309

### Summary of Changes

Please modify the flight pattern of the ASM KH-31A. Currently this missile presents a sea skimming attack pattern and that is a feature that only the KH-31AD has. The attack pattern of the KH-31A is similar to that of the KH-31P.

### Sources

https://www.matrixgames.com/forums/viewtopic.php?p=4419573#p4419573
https://www.youtube.com/watch?v=ZAls0Fi9FPQ&ab_channel=Yukikazehalo
![PfzhB5S](https://user-images.githubusercontent.com/109195286/179156604-976f587a-8610-4810-b39e-e5f7261beea4.jpg)
![gIzK1Ro](https://user-images.githubusercontent.com/109195286/179156629-c798b4e3-5a1a-4682-b430-f925dde342b7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
