### ISSUE TITLE
GB-1, also known as the "Grapefruit bomb" and as XM-108

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#176]
### DB Selector

CWDB

### User(s)

US B-17 bombers

### Weapons Carried

- 2x GB-1, also known as the "Grapefruit bomb" and as XM-108

Underwing carriage of 2 weapons.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as existing 2000lb bomb load

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Name: GB-1, also known as the "Grapefruit bomb" and as XM-108

Purpose: INS Guided Glide Bomb

Platforms: Deployed by B-17 Flying Fortresses with 2 bombs, 1 carried under each wing.

Summary Details: The GB-1 mated a 12-foot (3.7 m) wing and twin-tail empennage of conventional small-aircraft design to a standard M34 2,000-pound (910 kg) bomb. A gyrostabilizer-based autopilot controlling azimuth was used, allowing the bomb to be set to a specific course following release at a specific altitude and target distance; gliding at a speed of 230 miles per hour (370 km/h), range from a release height of 15,000 feet (4,600 m) was 20 miles (32 km). Over 1,000 were used during the war.

### Sources

https://en.wikipedia.org/wiki/GB-1

https://www.aftc.af.mil/News/On-This-Day-in-Test-History/Article-Display-Test-History/Article/2409759/december-8-1941-gb-1-glide-bomb-testing/

https://dbpedia.org/page/GB-1

https://media.defense.gov/2017/Dec/28/2001861715/-1/-1/0/T_BLACKWELDER_ROAD_TO_DESERT.PDF

https://www.jstor.org/stable/resrep13886.6?seq=1#metadata_info_tab_contents

https://www.criticalpast.com/video/65675036015_Glide-Bomb-GB-8_B-17-bomber_United-States-Army-Air-Corps_target-of-bomb-in-sea

https://www.youtube.com/watch?v=Is8iqj_JLhc

https://www.governmentattic.org/vonK/GuideHomingMissilesPilotlessAcft_VKarman_V9.pdf

https://www.reddit.com/r/MilitaryGfys/comments/f09h4z/b17_drops_a_gb1_glide_bomb_during_tests/

http://www.303rdbg.com/bombs.html

![download](https://user-images.githubusercontent.com/99599482/154343158-aee8fb8f-1831-4897-9c2b-95c25e82cf5b.jpg)
s.html
![8q3uzx8s6t111 jpg ae7d987856c1fa507baa7b5601ac6a81](https://user-images.githubusercontent.com/99599482/154343174-c94886bb-168c-4de1-a6bd-cc6386caf903.jpg)

![image](https://user-images.githubusercontent.com/99599482/154688959-d97e7fad-051c-4da2-a13a-194119c252d3.png)

**Comment by PygmalionOfCyprus** [comment]
We actually got a good kick out of looking into this, but unfortunately I think this is wontfix: it's out of scope even for CWDB (really it was only used in WW2) and even during the war it was more of an experiment than an actual fielded weapon, with such horrible results as to be practically useless.

We may one day cycle around and add it as a hypothetical just for kicks but for now we're going to bypass.

(Future WW2 DB maybe...!)

**Comment by tbrandon517** [comment]
Understood. No worries! Thought I'd show the B-17 some love since I requested the Korean era VB's. That and everyone always thinks of German Fritz-X and V weapons and don't really realize other belligerent were doing guided weapons as well.
