### ISSUE TITLE
Czech JAS 39 Gripen correction

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#1762]
### DB Selector

DB3K

### Affected DBID(s)

5714 (JAS 39C) and 5715 (JAS 39D)

### Summary of Changes

Remove Generic ECM [Advanced] from internal sensors from first iteration of Czech JAS 39C and JAS 39D (2005) - entries 5714 and 5715.

When JAS 39 was rushed in service in 2005 it doesn't have functional EWS 39 internal DECM. This is actually reflected in database in further iterations of Czech JAS 39 which has EWS 39 instead of generic ECM.

### Sources

The information comes from original post here:
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/553

**Comment by PygmalionOfCyprus** [comment]
Man, those early Gripens really were garbage. Fixed 496.
