### ISSUE TITLE
ARRW CEP Issues and Not Enough Kinetic Energy Released

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1765]
### DB Selector

DB3K

### Affected DBID(s)

3822 and others I am sure

### Summary of Changes

Trying out the ARRW using 1265.1, just to see if I could get better results with this weapon than some of the others I have been trying to take down AD/AA.  

Where to start.

Well as I said CEP in the title, lets start with that.

CEP from DB is 30 metres or just under 100 feet
Definition of CEP is that 50% of the weapons fired will fall within that area. Only one did.  The issue here is that's for ballistic weapons with no guidance.  

DRMS says 95% should fall within the CEP, clearly if using that model things went very awry.  Maybe for 6 weapons (albeit on 2 goes) the sample is too small for classic CEP analysis.

OK when they actually struck the target or nearby they were doing Mach 9 and change with a 1000 ish kg warhead.  Think the explosive force of a miss with that size of warhead at that speed is going to make a big hole, a big shockwave and a lot of collateral frag.  To take out one 2 TEL's and 3 Igla sections is so off that I don't know where to start.

I accept that there could be many things at play here and I cannot imagine how many factors you have to plug in to the equations, but, based upon kinetic energy alone, there should be no last man standing from a single strike within the CEP of the target. The target should have been obliterated.  

**Based on the weight of the penetrator alone without the explosive force, almost 10 GJ of energy is in play, or if you like a Magnitude 3.5 earthquake**

I think I may have uncovered a raft of issues here that are interplaying to cause problems. Bit like finding a fault in a wiring loom I guess.

### Sources

DB3K 495 and Beta Build 1265.1 

DB defines damage.
Build makes them 'work'

Iskander and Killjoy have both been shown to completely obliterate any thing they hit, from non-reinforced military targets to softer civillian structures, with a similar sized missile going at about 1/2 to 2/3 the speed of ARRW.

**Comment by PygmalionOfCyprus** [comment]
Sim-side issues. Lack of KE consideration bugs me too.
