### ISSUE TITLE
Convair R3Y Tradewind - Tanker/Transport

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#177]
### DB Selector

CWDB

### Hypothetical

No

### Name

R3Y Tradewind

### Country

United States

### Service

Navy

### In Commission

1956-1958

### Length (m)

R3Y 42.578 m, R3Y-2 43 m

### Wingspan (m)

44.442 m

### Height (m)

14.94 m keel to fin tip/ 16 m on beaching gear

### Empty Weight (kg)

Not Listed

### Maximum Takeoff Weight (MTOW) (kg)

74,843 kg

### Payload Weight (kg)

21772.43

### Crew

7

### Propulsion

4 × Allison T40-A-10 turboprop engines, 5,332 shp (3,976 kW) each

### Rate of Climb (ft/min)

1,910 ft/min

### Service Ceiling (ft)

30,300 ft 

### Military/Afterburner Speed (kt)

 299 kn at MTOW, 308 kn at normal gross weight

### Cruise Speed (kt)

300 kn

### Supercruise

No

### Ferry Range (nm)

2,420 nmi

### Endurance (min)

486

### Fuel Capacity (kg)

29,937 kg

### Sensors

mk 1 eyeball

### Mounts

4x Wing Drogues

### Loadout Options

R3Y:
- 80 Troops
- 72 litter patients with 8 medical staff
- Tanker - 4x Wing Drogues

R3Y-2: 
- 103 troops
- 92 litter patients with 12 medical staff
- Tanker - 4x Wing Drogues

### Comms/Datalinks

UHF/VHF Unsecure

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Wing Drogue

### Comments

Short lived USN flying boat tanker transport. It's big wing tanking and waterborne operation would be interesting to play with in scenarios as the concept has been brought up in regard to current US/China relations and potential pacific conflict.

Probably should assume regular use of beaching gear for land base use in a semi-amphibian manner.

### Sources

https://en.wikipedia.org/wiki/Convair_R3Y_Tradewind
http://www.thehangardeck.com/news/2019/4/8/the-short-storied-history-of-the-convair-xp5yr3y-tradewind
https://weaponsandwarfare.com/2017/03/04/convair-r3y-tradewind/
https://en-academic.com/dic.nsf/enwiki/11575876
https://military-history.fandom.com/wiki/Convair_R3Y_Tradewind
http://www.aviation

![6+Lockheed+Martin+Tradewind+4-ship+Refuel](https://user-images.githubusercontent.com/99599482/154343027-43004e00-8e2b-4664-835b-5154c95677d4.jpg)
-history.com/convair/tradewind.html

**Comment by tbrandon517** [comment]
In DB493

**Comment by Jkryos** [comment]
Added DB3K 493 but forgot to mark complete.
