### ISSUE TITLE
Correction/update for SY-400 battery

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1774]
### DB Selector

DB3K

### Affected DBID(s)

1679 & 3179

### Summary of Changes

-each mount(1879) can only carry 4x SY-400(weapon/2123) and 1x BP-12A(weapon/3021) missile instead of 2x BP-21A and 6x SY-400 as in current DB v495.
![image](https://user-images.githubusercontent.com/99646926/179379888-d81ec799-8ea9-4dc5-9e14-c00637b52ad0.png)

-add magazine of 60x SY-400 and 15x BP-21A for each battery as it have its reload vehicles
![image](https://user-images.githubusercontent.com/99646926/179379990-2e5fd0b3-680d-4e00-a189-5eba0cd40faa.png)

### Sources

https://www.military-today.com/missiles/sy_400.htm#:~:text=The%20SY-400%20is%20supported%20by%20a%20reloading%20vehicle%2C,which%20carries%20a%20full%20set%20of%20reload%20containers.

http://defence-blog.com/news/myanmar-looks-to-buy-chinese-sy-400-ballistic-missile-systems.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
