### ISSUE TITLE
Yugoslavia - Ka-28PL 1992 version with Mk46

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1776]
### DB Selector

DB3K

### DBID to Copy

5325

### Hypothetical

Yes

### Name

Ka-28PL Helix A [HP-46] -- Yugoslavia (Air Force), ASW, Maritime AEW, Yugoslavia 1992+

### Country

Yugoslavia

### Service

Air Force

### Number in Service

12

### Sensors

unchanged

### Mounts

unchanged

### Loadout Options

add:
1x Mk46 NEARTIP Mod 5
18x RGB-NM-1

### Other Changes

Yugoslavia planned to acquire 12 Ka-28PL to replace the aging Ka-25 fleet and expand the squadron. The Mi-14PL wouldn't have been retired. The Ka-28PL would be equipped with the Mk46 torpedo, probably the newest version available at that time, the Mod 5 since it was also exported to other countries like Brasil in the late 80s.

### Sources

https://www.paluba.info/smf/index.php?topic=11465.msg493330#msg493330

> .......Kupljeni su u SSSR-u PP helikopteri tipa Ka-25PL (HP-43) i Mi-14PL (HP-44). Najpre su 1974.g. u naoružanje 784.eskadrile uvedeni sovjetski helikopteri sa koaksijalnim rotorima Ka-25PL. Uvođenjem u upotrebu PP helikoptera Ka-25PL a radi povećanja njegovih napadnih mogućnosti u PP dejstvima, nabavljen je u SAD pod povoljnim uslovima protivpodmornički torpedo MK-44. Taj torpedo u perspektivi je trebalo da bude zamenjen američkim torpedima MK-46. Protivpodmornička helikopterska 784.eskadrila je 1980.godine ojačana helikopterima Mi-14PL.......

> ......Ka-25PL (HP-43) and Mi-14PL (HP-44) type PP helicopters were purchased in the USSR. First, in 1974. Soviet Ka-25PL helicopters with coaxial rotors were introduced into the armament of the 784th squadron. With the introduction into use of the Ka-25PL PP helicopter and in order to increase its attack capabilities in PP actions, the MK-44 anti-submarine torpedo was acquired in the USA under favorable conditions. That torpedo was supposed to be replaced by American MK-46 torpedoes in the future. In 1980, the 784th anti-submarine helicopter squadron was strengthened with Mi-14PL helicopters.......

The Naval Institute Guide to World Naval Weapons Systems 1997-1998, Norman Friedman, page 693:
![20220717_042742](https://user-images.githubusercontent.com/104227721/179381527-b3c8583b-c76a-4265-875b-331e12bc1b60.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
