### ISSUE TITLE
Yugoslavia - Mi-14PL 1992 version with Mk46

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1777]
### DB Selector

DB3K

### DBID to Copy

1476

### Hypothetical

Yes

### Name

Mi-14PL Haze A [HP-44] -- Yugoslavia (Air Force), ASW, Yugoslavia 1992+

### Country

Yugoslavia

### Service

Air Force

### Number in Service

3

### Sensors

unchanged

### Mounts

unchanged

### Loadout Options

add:
1x Mk46 NEARTIP Mod 5
36x RGB-NM-1

### Other Changes

Yugoslavia planned to acquire 12 Ka-28PL to replace the aging Ka-25 fleet and expand the squadron. The Mi-14PL wouldn't have been retired. The Mi-14PL which allready used the Mk44 torpedo, would be equipped with the Mk46 torpedo, probably the newest version available at that time, the Mod 5 since it was also exported to other countries like Brasil in the late 80s.

### Sources

https://www.paluba.info/smf/index.php?topic=11465.msg493330#msg493330

> .......Kupljeni su u SSSR-u PP helikopteri tipa Ka-25PL (HP-43) i Mi-14PL (HP-44). Najpre su 1974.g. u naoružanje 784.eskadrile uvedeni sovjetski helikopteri sa koaksijalnim rotorima Ka-25PL. Uvođenjem u upotrebu PP helikoptera Ka-25PL a radi povećanja njegovih napadnih mogućnosti u PP dejstvima, nabavljen je u SAD pod povoljnim uslovima protivpodmornički torpedo MK-44. Taj torpedo u perspektivi je trebalo da bude zamenjen američkim torpedima MK-46. Protivpodmornička helikopterska 784.eskadrila je 1980.godine ojačana helikopterima Mi-14PL.......

> ......Ka-25PL (HP-43) and Mi-14PL (HP-44) type PP helicopters were purchased in the USSR. First, in 1974. Soviet Ka-25PL helicopters with coaxial rotors were introduced into the armament of the 784th squadron. With the introduction into use of the Ka-25PL PP helicopter and in order to increase its attack capabilities in PP actions, the MK-44 anti-submarine torpedo was acquired in the USA under favorable conditions. That torpedo was supposed to be replaced by American MK-46 torpedoes in the future. In 1980, the 784th anti-submarine helicopter squadron was strengthened with Mi-14PL helicopters.......

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
