### ISSUE TITLE
Mushroom [RPB-2KM Initsiativa] (Ka-27)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1779]
### DB Selector

DB3K

### Baseline

2923

### Hypothetical

No

### Name

Mushroom [RPB-2KM Initsiativa] (Ka-27)

### Sensor Generation

Late 1970s

### Range (nm)

0.2-130

### Sensor Capabilities

Surface Search, Range Information, Speed Information, Heading Information

### Sensor Codes

Periscope Search - Basic Capability, Pulse Doppler Radar (Limited LDSD Capability)

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

9,300,000,000

### Upper Frequency (Hz)

9,500,000,000

### Scan Interval (s)

5

### Peak Power (W)

100000

### Pulse Width (μs)

1.2

### PRF (Hz)

585

### Comments

Range: 130nm instrumented range
Accuracy: ±2% (range); ±2° (azimuth)
polarization: horizontal

related to this request: #1778
DBIDs of KA-27/28 which would require their radar to be changed from Mushroom [RPB-2K Initsiativa] (Ka-25) to Mushroom [RPB-2KM Initsiativa] (Ka-27): 629, 21, 371, 4, 2615, 5325

also in the request #1485 it is stated that the Mushroom [RPB-1 Initsiativa] (Tu-95RT) radar (ID: 1922) doesn't exist. Could it be changed into Mushroom [RPB-2KM Initsiativa] (Ka-27) since the sensor in this DB entry is non existent?

### Sources

Credit to CV60 for finding this information:
https://www.matrixgames.com/forums/viewtopic.php?f=10201&p=4997590

Friedman, The Naval Institute Guide to World Naval Weapons Systems 1997-98, pg. 199.;
NATO "Current Soviet Bloc Electronic Equipment, Vol B: Airborne, 12 Feb 1968, pg. I-B-1.
page 26 of this document:
https://archives.nato.int/uploads/r/nato-archives-online/a/7/7/a77acfea6fe1accb0f9f55c6d8ab8f399a40d17ca9efc0fdcc9b0211e989463a/MC_0262_B_68_FINAL_ENG_PDP.pdf

I'm making this request because I found the instrumented range of the Initsiativa-2KM radar used by the KA-27PL and some KA-28PL (for example Yugoslavia). This should more or less apply to the Ka-25 and Mi-14 Initsiativa radars and probably the Beriev Be-12. Not sure about the Yak-28 though. The instrumented range is 240km (130nm) for the Initsiativa-2KM radar. This is corroborated by ex Yugoslav sources which state that the Ka-28 could cover the entire southern Adriatic Sea with it's radar and a good chunk of southern Italy, almost 250km in range. The Ka-28 wasn't just used by the Yugoslav Air Force for the ASW role but also as a sort of maritime AEW aircraft although it wasn't built for this purpose. The Ka-28 would operate at an altitude of 4000m to maximise it's radar coverage. Which btw I have tested in cmano, at 12000ft Initsiativa can see up to 150nm. The Kamovs can't even utilize the current 180nm range at 12000ft. So the 130nm downgrade isn't that bad.

http://www.airwar.ru/enc/sh/ka27.html

> Радиолокационная подсистема представлена РЛС "Инициатива -2КМ".
Подсистема индикации тактической обстановки (ИНТО) обеспечивает отображение первичной и вторичной информации о целях, взаимодействующих силах, и других данных, необходимых для оценки обстановки и принятия решения. К первичной информации относится радиолокационое изображение надводной обстановки, которая воспроизводится на экране в виде яркостных отметок, ко вторичной - данные от ВГС-3 и канала привязки информационно-вычислительной подсистемы (ИВП), воспроизводимые символами, буквенно-цифровыми формулярами и графиками траекторий движения, линий пеленгов, векторов скорости и пр. Экран индикатора имеет диаметр 25,4 см, масштабы изображения переменные: 8, 16, 32, 120 и 240 км. Первичная и вторичная информация отображаются только на первых трех масштабах. Информационно-вычислительная подсистема предназначена для расчета параметров по данным ВГС-3, радиолокационной подсистемы и сопряженного с ППС оборудования, и выдачи в ИНТО вторичной информации о цели и взаимодействующих вертолетах.

>Тhe radar subsystem is represented by the **Initiative-2KM radar**.
The tactical situation indication subsystem (INTO) provides display of primary and secondary information about targets, interacting forces, and other data necessary for assessing the situation and making a decision. The **primary information includes the radar image of the surface environment**, which is reproduced on the screen in the form of brightness marks, the secondary information is data from the VGS-3 and the link channel of the information and computing subsystem (ICS), reproduced by symbols, alphanumeric forms and graphs of movement trajectories, lines bearings, velocity vectors, etc. **The indicator screen has a diameter of 25.4 cm, image scales are variable: 8, 16, 32, 120 and 240 km.** Primary and secondary information is displayed only on the first three scales. The information-computing subsystem is designed to calculate the parameters according to the VGS-3 data, the radar subsystem and the equipment associated with the PPS, and to issue secondary information about the target and interacting helicopters to the INTO.

post by Charlie:
https://www.mycity-military.com/Helikopteri/Protivpodmornicki-helikopteri-HP-43-HP-44-i-HP-46_6.html

> Još jedna od nedoumica je domet radara za Ka-25 i Ka-27/8... Nikako nisam uspeo da nađem podatke za dotične, ali sam od jednog visokog oficira naše vojske uspeo da saznam da su Ka-28 1999 korišćeni kao mini avaksi i da su po dobrim vremenskim uslovima mogli da prate poletane NATO aviona sa južnih Italijanskih aerodroma koji su korišćeni za napad na tadašnji SRJ. Prema karti to je 150-250km

> Another one of the uncertainties is the radar range of the Ka-25 and Ka-27/8... I have not been able to find data for them at all, but I managed to find out from a high-ranking officer of our army that the Ka-28 was used as a mini-AWACS in 1999 and that in good weather conditions they could follow the take-off of NATO planes from the southern Italian airports that were used for the attack on the then FRY. According to the map it is 150-250KM.

https://www.paluba.info/smf/index.php?topic=1618.msg6439;topicseen#msg6439

> Najmodernija letelice u arsenalu JRV. Primera radi, Ka-28 su stigli otprilike u isto vreme kao i MiG-29. Elektronska oprema u Kamovu bila je jednu generaciju ispred one na MiG-29. Jako kvalitetne, u svoje vreme moderne i robusne mašine. Služili ne samo za traganje i uništavanje podmornica, već i za izviđanje, otkrivanje i praćenje ciljeva na moru iza horizonta, navođenje avijacije (J-22 s AGM-65B) na neprijateljske brodove, otkrivanje površinskih ciljeva za posredno raketno gađanje jedinica flote itd. U neku ruku - pravi mali AWACS-i (mogao je otkrivati i pratiti ciljeve sve do italijanske obale).

> The most modern aircraft in the JRV arsenal. For example, the Ka-28s arrived around the same time as the MiG-29s. The electronic equipment in the Kamov was one generation ahead of that on the MiG-29. Very high-quality, modern and robust machines for their time. They were used not only for the search and destruction of submarines, but also for reconnaissance, detection and tracking of targets at sea beyond the horizon, guidance of aviation (J-22 with AGM-65B) to enemy ships, detection of surface targets for indirect missile targeting of fleet units, etc. In a way - real little AWACS (could detect and track targets all the way to the Italian coast).

**Comment by PygmalionOfCyprus** [comment]
Handled 497. Replaced RPB-1 as requested and swapped out radars on the Ka-27s.
