### ISSUE TITLE
RCN - Anticosti Class MSA 1989

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#178]
### DB Selector

DB3K

### Hypothetical

No

### Name

MSA 110 HMCS Anticosti, MSA 112 HMCS Moresby

### Class

Anticosti Class

### Country

Canada

### Service

Royal Canadian Navy

### In Commission

1989-2000

### Length (m)

58.27

### Beam (m)

13.14

### Draft (m)

5.18

### Standard Displacement (t)

1,076t

### Full Displacement (t)

1,076t

### Complement

23

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

4 Nohab Polar diesels, 2 shafts, 4,600 bhp, 1 × 575 bhp (429 kW) azimuth bow thruster

### Flank Speed (kt)

13.5kt

### Range (nm) at Speed (kt)

12,000 nmi (22,000 km; 14,000 mi) at 13 knots (24 km/h; 15 mph)

### Sensors

2 × [Racal Decca](https://en.wikipedia.org/wiki/Racal_Decca) navigation radar (I band)
1x Towed VDS side scan sonar

### Mounts

1x Mechanical Sweep

### Aircraft & Docking Facilities

2x davits for 7m RHIBS

### Comms/Datalinks

Unable to locate, assume similar to Kingston class

### Ship Codes

Built to Mercantile Standards

### Comments

From Hazegray.org: ANTICOSTI was used in the East Coast MARCOT exercise as a minelayer on at least one occasion. ANTICOSTI was also fitted with astern refueling gear in 1995. 

From Jane's 1990-91: Former offshore towing/supply vessels Ice class 3, suitable for navigation in light ice. 

### Sources

https://en.wikipedia.org/wiki/Anticosti-class_minesweeper 
http://www.hazegray.org/navhist/canada/postwar/anticost/ 

![9503-22 HMCS Anticosti](https://user-images.githubusercontent.com/99632305/154307309-4e22165c-a9cb-4cf2-9143-2f399531c59e.jpg)

![9549-11 HMCS Anticosti](https://user-images.githubusercontent.com/99632305/154307336-5bd63540-b186-4105-a77d-a90ef8d8ff44.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
