### ISSUE TITLE
SU-35S is Flanker M not Flanker E

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1781]
### DB Selector

DB3K

### Affected DBID(s)

All SU-35S

### Summary of Changes

The designator Flanker E was only applied to the Su-27M (cannards, early IRBIS etc) that served as a prototype to the actual production SU-35S (Flanker M).  Only 12 or so were converted before the focus eventually switched to new build.  The new build SU-35S have a NATO name of Flanker M.  The visible, external differences are the cannards on the E, no cannards on the M.  Both have the offset IRSTS (as do the 27SM's)

I note that under SU-35S you include the SU-27M as an alt name.  This appears to reflect the wiki entries which are woefully dated, as are their sources.  I'll try and find your a more sutiable source than the one I have below, but he is correct.  Of course the Russians dont use these names, just adding a series of letters after the mods.

You might want to consider breaking out the conversions here as you have done with other aircraft, if you accept my submission on the naming.

### Sources

https://forum.warthunder.com/index.php?/topic/543335-sukhoi-su-35s-flanker-m-the-last-flanker/

**Comment by PygmalionOfCyprus** [comment]
Fixed the naming and removed the misleading reference to the Su-27M. Someday I will break out the prototype version as its own entry, but it is not this day. If it's important to you that it be done sooner rather than later, could you open a separate ticket for it? You can provide more info about differences that way.

**Comment by HVAA** [comment]
To be honest, IRL, the whole Flanker thing is a mess of different models vs NATO names, some based on fact, the rest on conjecture or just plain wrong and this affects all sources and publications out there.  It wasnt aided by the draw down of R&D funds after the collapse of the Soviet Union, where it seems that the Air Force seemed to suffer more than most.  If I find something that you can use for the SU-27M (early SU-35) I will certainly raise a ticket for you.  But no rush, its only 12 airframes max and I cant even recall if they are still in service or whether they were truly just stopgaps...
