### ISSUE TITLE
SU-35 Wing 'Radar'

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1782]
### DB Selector

DB3K

### Affected DBID(s)

5714

### Summary of Changes

This didnt sit right with me at all. Radar physics screamed that it could not work this way.

Ok, so I finally found it.  This is not a radar per se, but PAROL, the IFF system.

This matches with some sources and certainly matches the source below in terms of operating band.
Images show that this is in the LERX area of the SU-35S  Probably unable to embed it in the PESA of IRBIS.

Again I will search for more sources, but I hope I have thrown sufficient doubt as to this being a radar in the classic sense of a radar.

In any case there is no way that an array of that size at that band could do all that it is described in DB as the wavelength is wrong for JEM/NCTR alone.

For info  PAROL is an extemely widely used system alonside SRO-2/SRZO, a source for that is included for completeness.

### Sources

https://www.mil-airfields.de/equipment/soviet-russian-iff-parol.htm
https://www.secretprojects.co.uk/threads/soviet-russian-iff.792/

**Comment by PygmalionOfCyprus** [comment]
I agree. I've seen Russian marketing materials mistranslating their IFF transponders as "radar" (probably because it technically sends/receives signals, or something) so whoever added this one probably got confused.

Removed the "wing radar" from all the Su-35s for 496.
