### ISSUE TITLE
Pleas add upgraded Atlas Oryx

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1784]
### DB Selector

DB3K

### DBID to Copy

4482 SA.330 Puma[Oryx] (South Africa - 1992)

### Hypothetical

No

### Name

SA.330 Puma[Oryx] South Africa (Air Force), 2012, Upgraded

### Country

South Africa

### Service

Air Force

### Sensors

1x generic LWR
1x generic RWR
1x generic navigation radar
1x night vision goggle(3rd gen)

### Mounts

add generic flare dispenser (32 cartridges) 
![image](https://user-images.githubusercontent.com/99646926/179403377-395dd292-4073-4ada-ac70-729dbb4ae973.png)

### Other Changes

change the steam gauge cockpit to at least Glass Cockpit (Partial). 
![image](https://user-images.githubusercontent.com/99646926/179403425-8dc95eeb-9ae0-48b7-af4f-ee650ad127b7.png)

### Sources

https://www.airforce-technology.com/projects/atlas-oryx/
https://www.airliners.net/photo/South-Africa-Air-Force/Aerospatiale-Atlas-TP-1-Oryx/1790696

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
