### ISSUE TITLE
RF-100As missing Recon sensors

### ISSUE THREAD

**Issue by TestPilotKerman** [PygmalionOfCyprus/cmo-db-requests#1785]
### DB Selector

CWDB

### Affected DBID(s)

2200,2201

### Summary of Changes

Add recon sensors to recon aircraft
Source indicates 3x K-17 in trimetrogon (one straight down, one on either side depressed 30 degrees from horizontal), 2x K-38 was the operational configuration
Sensors permanently fixed to airframe

### Sources

https://www.skytamer.com/North_American_RF-100A.html

**Comment by PygmalionOfCyprus** [comment]
>Add recon sensors to recon aircraft

Whatever will they ask for next?

Fixed 496.
