### ISSUE TITLE
Japan, SH-60K, update + add

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1786]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2058

### Summary of Changes

General
----
Length 19.8m
Wingspan: 16.4m (3.3m if rotors are folded) 
Height:5.4m
Max Weight: 10900kg (=24000lb)
Crew: 4

Sensor
---
Generic FLIR → AN/AAS-44-N (there are few variants... -N1(SH-60K),-N2(SH-60J),-N3(SH-60K) but not sure the difference. I do not think there are any big changes so I will request it as -N... or this is just a AN/AAS-44(Sensor 1779) so you might not make new entry)
AN/ALR-66 + Generic MAWS → AN/AAR-60(V)(= AN/AAR-60: Sensor ID209) (No RWR for SH-60K while they have HLR-108 ELINT) 

Loadout
---
2005ver:
Sonobuoys: HQS-13F
Mk46 and Type 97

2013ver: (Type 12, HQS-13G-1) (plz add it as new variant of SH-60K)
Sonobuoys: HQS-13G-1
Mk46 and Type 97 (they are still available)
+ Type 12 torpedo (requested as: https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1543)

Properties
---
NO HIFR capability

Speed
---
Max Speed: 139knts (slow down)

### Sources

Generic info:
https://www.mod.go.jp/msdf/equipment/rotorcraft/patrol/sh60k/
https://www.mhi.com/jp/products/defense/sh60k_patrol_helicopter.html

AN/AAS-44-N(1 and 3)
https://www.njss.info/offers/view/202574/
https://www.njss.info/offers/view/18494935/

AN/AAR-60(V)
https://www.njss.info/offers/view/17008747/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
