### ISSUE TITLE
Type 07 VL-ASROC [Type 12]

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1788]
### DB Selector

DB3K

### DBID to Copy

Weapon 3705

### Hypothetical

No

### Name

Type 07 VL-ASROC [Type 12]

### Country

Japan

### Service

Navy

### In Commission

2013 or around

### Sensors

-

### Mounts

-

### Loadout Options

-

### Other Changes

Warhead is Type 12 (Requested as: https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1543)

Used by Asahi (SHIP ID 3128), Maya (3211), FFM 7 (3293), Haguro (Requested: https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1583).
I believe they are not losing 07VLA [type97] and RUM-139 capability, so for Asahi class Mk41 VLS, the loadout would be 32x ESSM + 16x Type 07 [Type 12] + 0x Type 07 [Type 97] + 0x RUM-139 [Mk46 (No Mk54 for Japan)] .

### Sources

https://ja.wikipedia.org/wiki/12%E5%BC%8F%E9%AD%9A%E9%9B%B7

https://ja.wikipedia.org/wiki/07%E5%BC%8F%E5%9E%82%E7%9B%B4%E7%99%BA%E5%B0%84%E9%AD%9A%E9%9B%B7%E6%8A%95%E5%B0%84%E3%83%AD%E3%82%B1%E3%83%83%E3%83%88

**Comment by KC45jp** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1587
There is another ship. Asahi 2019

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
