### ISSUE TITLE
Martin P6M SeaMaster

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#179]
### DB Selector

CWDB

### Hypothetical

Yes

### Name

P6M SeaMaster

### Country

United States

### Service

Navy

### In Commission

1955-1959

### Length (m)

40.94 m

### Wingspan (m)

31.27 m

### Height (m)

10.31 m

### Empty Weight (kg)

44,198 kg

### Maximum Takeoff Weight (MTOW) (kg)

86,183 kg in calm water, 72,575 kg in rough water

### Payload Weight (kg)

14,000 kg

### Crew

4

### Propulsion

4 × Pratt & Whitney J75-P-2 turbojet engines, 17,500 lbf (78 kN) thrust each

### Rate of Climb (ft/min)

 7,380 ft/min

### Service Ceiling (ft)

50,000 ft

### Military/Afterburner Speed (kt)

596 kn

### Cruise Speed (kt)

 465 kn

### Supercruise

No

### Ferry Range (nm)

1,810 nmi

### Endurance (min)

Uncertain

### Takeoff / Landing Distance (m)

Uncertain

### Fuel Capacity (kg)

Uncertain

### Sensors

Fire-Control System: Aero X-23B AGL Tail Turret, 
ASQ-29 Automatic Navigation & Minelaying System

### Mounts

2 × 20 mm in rear remote operated turret (1,000 RDS/20mm)

### Loadout Options

Mines: 28 x MK36 Mod 1 (1,001 lb/ea, 454 kg/ea) - 28,028 lb/Tot (12,713 kg)
Mines: 15 x MK25 Mod 2 (2,030 lb/ea, 921 kg/ea) - 30,450 lb/Tot (13,812 kg)
Mines: 36 x MK50 Mod 0 (504 lb/ea, 228 kg/ea) - 18,144 lb/Tot (8,230 kg)
Mines: 15 x MK52 Mod 0,1,2,3,4,5,6 (1,348 lb/ea, 611 kg/ea) - 20,220 lb/Tot (9,172 kg)
Mines: 8 x MK39 Mod 0 (2,025 lb/ea, 919 kg/ea) - 16,200 lb/Tot (7,348 kg)
Mines: 15 x MK19 Mod 2 (540 lb/ea, 245 kg/ea) - 8,100 lb/Tot (3,674 kg)
Mines: 5 x MK10 Mod 9 (1,960 lb/ea, 889 kg/ea) - 9,800 lb/Tot (4,445 kg)
Reconnaissance: High Altitude Reconnaissance Camera 4,050 lb/Tot (1,837 kg)
Reconnaissance: 27 x M120(T9E8) Photoflash (154 lb/ea, 70 kg/ea) 4,158 pounds (1,886 kg)
Bomb: 2 x MK91 (3,500 lb/ea, 1,588 kg/ea) - 7,000 lb/Tot (3,175 kg)
Bomb: 1 x MK28 (1,800 lb/ea, 817 kg/ea) - 1,800 lb/Tot (817 kg)

### Comms/Datalinks

UHF/VHF Secure
UHF/VHF Unsecure

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Ballistic Computing, Probe Refuelling

### Comments

1950s Jet Flying Boat Bomber for the USN. An interesting concept worth exploring in CW scenarios. 

Assuming frequent use of beaching gear for land based semi-amphibian operation.

### Sources

https://en.wikipedia.org/wiki/Martin_P6M_SeaMaster
http://www.aviation-history.com/martin/p6m.html
https://www.smithsonianmag.com/air-space-magazine/cancelled-the-navys-seamaster-21166697/
https://www.defensemedianetwork.com/stories/what-might-have-been-the-martin-p6m-seamaster/
https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=1207
https://military-history.fandom.com/wiki/Martin_P6M_SeaMaster
http://www.aviastar.org/air/usa/martin_seamaster.php

![download](https://user-images.githubusercontent.com/99599482/154342915-97ace54f-e870-4024-8f4f-38e2db2e8f38.jpg)

**Comment by Jkryos** [comment]
Added DB3K 493.
