### ISSUE TITLE
Japan, P-3C, correction (loadout name + etc)

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1790]
### DB Selector

DB3K

### Affected DBID(s)

A/C 351

### Summary of Changes

Loadout
some of the loadout out name show incorrect sonobuoys
J/HQS-12→J/HQS-13F
J/HQS-33B→J/HQS-33C

+
Could you add AGM-84D Naval Strike loadout for 1990's and later version?

### Sources

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1327

**Comment by PygmalionOfCyprus** [comment]
Handled 496. For some reason I added the AGM-84D loadout earlier (probably while doing the initial pass on #1327) and even dated it correctly but forgot to actually apply it to the other aircraft. Oops.
