### ISSUE TITLE
Sensor SQR-20 active/passive sonar (Name, Sensor)

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1791]
### DB Selector

DB3K

### Affected DBID(s)

6099, 4490, 4808

### Summary of Changes

Name:
AN/SQR-20 TACTAS → AN/SQR-20 MFTA (Sensor ID 6099)

Sensor:
This is Active/Passive sonar

### Sources

https://www.militaryaerospace.com/sensors/article/14034453/towedarray-sonar-antisubmarine-warfare-asw

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
