### ISSUE TITLE
Please add air-to air missiles for Denel Rooivalk

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1792]
### DB Selector

DB3K

### User(s)

4414 AH-2 Rooivalk 

### Weapons Carried

All existing aircraft loadout (except Ferry, Maintenance and Reserve) also included:

4x Mistral 1 ATAM(weapon/1336)

![image](https://user-images.githubusercontent.com/99646926/179500986-f65003f2-9c10-489e-a363-aacbb6f46f3d.png)
![image](https://user-images.githubusercontent.com/99646926/179501227-625c1325-1c03-4467-b0b1-58dbcf3c0010.png)

or 

2x V3B Kukri (weapon/1045)
![image](https://user-images.githubusercontent.com/99646926/179501307-c943e9fd-d516-423e-8f18-0fa113e15ce0.png)

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

http://plane-encyclopedia.com/modern/denel-rooivalk/
https://en.wikipedia.org/wiki/Denel_Rooivalk

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
