### ISSUE TITLE
F-15K GBU-31, GBU-24 loadout

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#1793]
### DB Selector

DB3K

### User(s)

ROKAF F-15K 2007-2020

### Weapons Carried

same as USAF F-15E, except missile. (F-15K is using AIM-120C-7, AIM-9X)

Because the F-15K is an improvement to the F-15E, it matches the GBU-31, GBU-24 loadout of the F-15E.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

same as F-15E

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://www.airforce-technology.com/projects/f-15k-slam-eagle/
![KakaoTalk_20220718_135937626](https://user-images.githubusercontent.com/66541619/179559788-1f5be5fd-8c03-4860-965e-c0e6a578086a.jpg)

**Comment by PygmalionOfCyprus** [comment]
Which F-15E loadouts are you referencing?

**Comment by clerara10** [comment]
> 

F-15E


> Which F-15E loadouts are you referencing?

It means the loadout of GBU-31(V)3/B JDAM, CBU-105 WCMD, GBU-24 of F-15E However, the F-15K uses the AIM-120C-7 instead of the AIM-120D
