### ISSUE TITLE
Hyunmoo 4 missile request

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#1794]
### DB Selector

DB3K

### Affected DBID(s)

3818

### Summary of Changes

Hyunmoo 4 is a ballistic missile. Currently, DB is implemented as a cruise missile.

It's a ballistic missile that rises from 500 to 1,000 kilometers and then descends to Mach 10.

### Sources

https://www.joongang.co.kr/article/23788693#home
https://en.wikipedia.org/wiki/Hyunmoo#Hyunmoo-4
https://thediplomat.com/2020/05/report-south-korea-tested-hyunmoo-4-ballistic-missile/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
