### ISSUE TITLE
Correction for Kfir COA/C.10/C.12 & TC.10

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1795]
### DB Selector

DB3K

### Affected DBID(s)

2018, 2228, 4746, 5308, 5309, 5306, 5307

### Summary of Changes

-Change the cockpit from Glass Cockpit(Partial) to Glass cockpit to all Kfir COA/C.10/C.12 & TC.10

![image](https://user-images.githubusercontent.com/99646926/179556865-07acea5d-9231-44b5-849c-24de5ea96927.png)

-Add EL/M-2001B(sensor/671) only to Kfir C.12(aircraft/5308 & 5309). And also add Link 16 to all Kfir COA/C.10/C.12 & TC.10
![image](https://user-images.githubusercontent.com/99646926/179563672-386246f1-7441-4763-8b6b-bbffc66db097.png)

-Add night vision google(3rd gen) to all Kfir COA/C.10/C.12 & TC.10
![image](https://user-images.githubusercontent.com/99646926/179563248-3c1e2035-2d34-4b3b-a7ac-d1446b5ec0b4.png)

### Sources

https://defense-update.com/20131006_at-40-years-of-age-kfir-turns-into-a-networked-fighter.html
https://www.f-16.net/forum/viewtopic.php?t=5995#:~:text=Developed%20by%20IAI%20for%20the%20export%20market%2C%20the,containing%20a%20highly%20optimized%20set%20of%20advanced%20avionics.
https://www.antaresmagazine.com/colombian-deltas

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
