### ISSUE TITLE
AN/SSQ-53G DIFAR, GPS capability

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1796]
### DB Selector

DB3K

### DBID to Copy

Weapon 2496

### Hypothetical

No

### Name

AN/SSQ-53G DIFAR

### Country

US/NATO

### Service

Likely Navy

### In Commission

2014

### Sensors

1x Sonobuoy, Passive-Only DIFAR,  VLF (from5 to 2400Hz), Early 2000 tech, 

Basically SSQ-53F + XCO, GPS capability.
(While sonobuoys won't flow in CMO, not much meaning)

US Navy started buying from 2014, thus P-8 is likely a main user of this sonar.   

There is a sub-type called SSQ-53G(GPS) for recommended "international" customers requiring GPS capability by using National Maritime Electronics Association. (International... such a Canada)

I believe HQS-13G-1(ID 3882) is equivalent (but not copy I guess) with this one.

### Sources

US Navy FY 2014
https://www.secnav.navy.mil/fmc/fmb/Documents/14pres/OPN_BA3-4_BOOK.pdf (Page 112)

AN/SSQ-53G
https://fdocuments.in/document/anssq-53g-difar-anssq-53g-difar-sonobuoy-passive-directional-the-anssq-53g.html

AN/SSQ-53G(GPS)
https://sonobuoytechsystems.com/wp-content/uploads/2019/08/Q53G-GPS.pdf

AN/SSQ-53G(GPS) for Canada?
https://buyandsell.gc.ca/cds/public/2021/05/17/2c14179a3f5ad14589fc6c50d7795387/en-acan_w8485-195329_-an_ssq-53g_gps_difar_sonbuoys_procurement.pdf

AN/SSQ-53F (For reference-compaire purpose)
https://www.yumpu.com/en/document/read/25976994/an-ssq-53f-difar-sonobuoy

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
