### ISSUE TITLE
AN/SSQ-53D(3)、High Performance DIFAR, Sea State 6 Capable

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1797]
### DB Selector

DB3K

### DBID to Copy

Sensor 1885

### Hypothetical

No

### Name

AN/SSQ-53D(3)

### Country

South Korea?

### Service

Likely Navy

### Sensors

SSQ-53D(3) sonobuoy sonar- Passive-only, VLF, Early 200 tech. 
Focusing on 5Hz (LF) passive level. 

### Other Changes

Sea State 6 capable but not simulated in CMO. (maybe in future?)

AN/SSQ-53D(4) has GPS like SSQ-53G(GPS) does.

### Sources

Original? Canadian company?
https://www.ultra.group/media/2448/anssq-53d3-datasheet_final.pdf

License Production? South Korea
http://www.metanetworks.co.kr/03_pro/PDF/ANSSQ-53D(3)_META_SONOBUOY_CATALOG(ENG).pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
