### ISSUE TITLE
J/HQS-43 High Performance DIFAR (VLAD)

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1798]
### DB Selector

DB3K

### DBID to Copy

Weapon 4055, 2497

### Hypothetical

No

### Name

J/HQS-43

### Country

Japan

### Service

Navy

### In Commission

2009

### Sensors

J/HQS-43, sonobuoy, passive only, VLF, late 2000 tech.

### Other Changes

----
Comments
Japan MoD is buying this from 2009 and replace HQS-42B VLAD sonobuoys with this.
Likely for P-1 started service from 2011.
----

### Sources

https://www.amazon.co.jp/gp/product/B09HSLKDH5/ref=ppx_yo_dt_b_d_asin_title_o01?ie=UTF8&psc=1 (amazon link and quote down below)
![reference 1](https://user-images.githubusercontent.com/107294450/179636150-7ff10a7d-29bb-4a33-9890-bcd1ca956acf.PNG)
![reference 2](https://user-images.githubusercontent.com/107294450/179636156-28d6ca6b-8d1f-4b2d-8e4c-520b1a4cb8ac.PNG)
I only could find Japanese Source...

It does not contain a lot of information about HQS-43.
We can see, HQS-43 is VLAD but unlike normal VLAD which has fixed beam bearing,  it can direct the beam by operator. 
The function is not found in SSQ-77C or other DIFAR sonobuoys.
https://www.yumpu.com/en/document/read/25976992/an-ssq-77c-vlad-sonobuoy

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
