### ISSUE TITLE
J/HQS-35 LF DICASS

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1799]
### DB Selector

DB3K

### Baseline

Weapon 4039

### Hypothetical

No

### Name

J/HQS-35 LF DICASS

### Length (m)

1 (by Nato A size standard)

### Width/Span (m)

-

### Diameter (m)

0.1 (By NATO A size standard)

### Weight (kg)

10?

### Range (nm)

5+

### Warhead

none

### Targets

Submarine

### Sensors

HQS-35 use Low Frequency Active only sonar.
By source, it said 1/2-1/3 frequency of HQS-33, thus operating band will be LF.
LF tends to reach more longer range then MF of HF, + by the development period, I believe this has slightly longer range of detection. (like 8nm)

### Comments

GPS capability like AN/SSQ-53G.

### Sources

https://www.amazon.co.jp/gp/product/B09HSLKDH5/ref=ppx_yo_dt_b_d_asin_title_o01?ie=UTF8&psc=1 (amazon link and quote down below)
![reference 1](https://user-images.githubusercontent.com/107294450/179636150-7ff10a7d-29bb-4a33-9890-bcd1ca956acf.PNG)
![reference 2](https://user-images.githubusercontent.com/107294450/179636156-28d6ca6b-8d1f-4b2d-8e4c-520b1a4cb8ac.PNG)
I only could find Japanese Source...

Closest is this one, while it use LF sonar and supports monostatic operatrion.
https://www.ultra.group/media/2663/anssq-565-datasheet_final.pdf

**Comment by KC45jp** [comment]
Sorry, this is not Hypo weapon

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
