### ISSUE TITLE
Replace Sparrows in Sufa AGM-142 Loadout #26623 with Amraams

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#18]
### DB Selector

DB3K

### Affected DBID(s)

Loadout #26623

### Description of Problem

Current Popeye loadout of F-16I Sufa loadout carries Sparrow III which isn't correct. This was likely over a copy over error. Should be the equivalent Amraam for the generation of Sufa build. Sparrow Guidance and Popeye may not work well together and there is no other Sufa loadout that includes a Sparrow III.

### Recommended Fix

Replace Sparrows with Amraams

**Comment by Jkryos** [comment]
Fixed DB3K 493.
