### ISSUE TITLE
USS 51 Arleigh Barke [Arleigh Barke Flight 1], 2015, SLQ-59, 7th Fleet(DESRON15) only

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1801]
### DB Selector

DB3K

### DBID to Copy

SHIP 2343, 2867

### Hypothetical

No

### Name

USS 51 Arleigh Barke [Arleigh Barke Flight 1]

### Country

US

### Service

Navy

### In Commission

2015

### Sensors

1x AN/SLQ-59 [SWEIP Blk 3T) (ID 5964)

### Other Changes

AN/SLQ-59 is added exclusively for 7th Fleet(Pacific Fleet, DESRON 15), just like SLQ-62 is added to 6th Fleet. (Related Topic: https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/702)

Naming,
SLQ-59 added to DDG 69 Milius in 2015, and later added to other Flight 1 include DDG 52 Barry.
I am not sure how do we name them in this case, we can either name  "DDG 69 Milius" because it is the first one, or "DDG 52 Barry" because of the number. 
So I will make request as "USS 51 Arleigh Barke [Arleigh Barke Flight 1]" for name, and  "SLQ-59, 7th Fleet(DESRON15) only" for comment. I think any way is OK.

### Sources

Japanese detailed source
https://orca-oruka.hatenablog.com/entry/2021/05/16/050150

English Source
https://www.thedrive.com/the-war-zone/29626/shadowy-new-electronic-warfare-system-has-been-installed-on-u-s-navy-7th-fleet-ships

**Comment by KC45jp** [comment]
I might want to hold this request until mentioned problem solve or it was not a problem.

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Named it after Milius.
