### ISSUE TITLE
BUG: DEFAULT SENSOR CARRIER PLATFORMS list does Not match:  SLQ-32 and SLQ-59 

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1802]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5964 and Listed platforms

### Description of Problem

I found this problem when I was researching this in DB but...
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1801

In DB viewer, AN/SLQ-59[SEWIP blk3T] equipped by several DDG, CG, and CVN of US Ships.
However, on Platforms, for example, DDG 125 Jack H. Lucas [Arleigh Burke Flight III] (Ship ID 2718), they have 2x each of SLQ-32 [ECM]/[ESM], SLQ-59 [ESM]/[ECM](which is other SLQ-59 entry, duplicated?). 
And  these SLQ-32 [ECM]/[ESM], SLQ-59 [ESM]/[ECM] do not have any platform in their sensor Window.

I am sorry if this is how DB works and I just did not know, but this seems very strange for me.

AN/SLQ-59[SEWIP blk3T]  window shows this but...
![SLQ-59 listed](https://user-images.githubusercontent.com/107294450/179667814-ee181598-ef3d-4761-973a-4270ecc4c6eb.PNG)
Not in DDG 125 Jack H. Lucas [Arleigh Burke Flight III]
![SLQ-59 actual](https://user-images.githubusercontent.com/107294450/179667829-25ced4f0-3fb8-4746-835d-f24e19959191.PNG)
and the ship Not listed in actual sensor  AN/SLQ-59[ESM] (and other sensors I listed)
![SLQ-59 not listed for actual one](https://user-images.githubusercontent.com/107294450/179667840-96d2a17e-0cc3-433f-bd3a-bd86d66ad582.PNG)

### Recommended Fix

please make Sensor Platform listed and actual installed unit match.

**Comment by tbrandon517** [comment]
I believe what you are seeing on the ship entries is the individual components of the SLQ-59 which make up the group. In the sensor lists you can see the group (and what units have it in its entry) as well as the individual components. I might be wrong. The DB gurus cab clarify.

**Comment by PygmalionOfCyprus** [comment]
@tbrandon517 is correct. The SLQ-59 ESM/ECM components are modelled as separate sensors because we can't currently do dual/multi-role sensors in the DB, but they're grouped together into a single "sensor group" because there's no situation in which you'd have one without the other.
