### ISSUE TITLE
Serbian MI-35M

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#1803]
### DB Selector

DB3K

### DBID to Copy

3744 (DB3K)

### Hypothetical

No

### Name

MI-35M

### Country

Serbia

### Service

Air force

### In Commission

2019

### Number in Service

4x, 4 more on order

### Mounts

23mm gsh

### Loadout Options

1250 liter Ferry Tank - Drop Tank
AT-9 Spiral-2 [9M120 Ataka-V] - Guided Weapon
Surface Max: 9.3 km. Land Max: 9.3 km.
S-8KO 80mm Rocket [HEAT] - (1985) Rocket
Surface Max: 3.7 km. Land Max: 3.7 km.
Trooper - Troops

### Sources

https://youtu.be/pKR2VGLU7g0

https://www.mod.gov.rs/eng/14960/obuka-na-borbenim-helikopterima-mi-35-14960

![images - 2022-07-20T005035 113](https://user-images.githubusercontent.com/99824301/179780996-d88f5ee9-55ee-4adb-bb91-d820338b3d42.jpeg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
