### ISSUE TITLE
Japan, EP-3, update

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1804]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 119

### Summary of Changes

Name
---
EP-3C Orion → EP-3

General Data
---
length:32.7
Crew: 15 (Based on JMSDF website)

Sensor
---
Delete
ALD-9(V)1 DF
ALR-44
ALR-76
ALR-81
ALR-84
(I guess they are added because American EP-3E has those but I cannot find any resource that Japanese EP-3 has those or in Japanese government procurement record.

Add
NH/HLR-107, SIGINT, late 1980 tech
NH/HLR-108, SIGINT, late 1980 tech

Properties
---
Max speed: 370kts

### Sources

https://www.jedonline.com/2020/05/20/unknowable-unknowables/

https://www.mod.go.jp/msdf/equipment/aircraft/utility/ep-3/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
