### ISSUE TITLE
SAM-1C Tan-SAM Kai [IR], updates, copy, etc...

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1808]
### DB Selector

DB3K

### DBID to Copy

Weapon 424

### Hypothetical

No

### Name

SAM-1C Tan-SAM Kai [IR]

### Country

Japan

### Service

Ground Force

### Sensors

IR seeker instead of ARH seeker

### Other Changes

SAM-1C have 2 types of missiles like MICA, IR and ARH seeker. 
Current CMO has ARH version only so plz add IR version.

Please add word [ARH] for original SAM-1C(ID424).

Mid course Guidance is done only by INS, because SAM-1 series can use optical aiming system. 

omit Capable vs Sea Skimmer, and target altitude could 100 ft minimal, because Air Defense force refused to accept this by low capability of shooting down cruise missiles.

### Sources

two types of weapons, one with round head has IR seeker and sharper head has ARH seeker.
https://ja.wikipedia.org/wiki/81%E5%BC%8F%E7%9F%AD%E8%B7%9D%E9%9B%A2%E5%9C%B0%E5%AF%BE%E7%A9%BA%E8%AA%98%E5%B0%8E%E5%BC%BE#/media/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:JGSDF_Type_81C_SAM_04.jpg

English Source does not mention about IR seeker.
https://en.wikipedia.org/wiki/Type_81_(missile)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
