### ISSUE TITLE
SAM-1C Tan-SAM Kai

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1809]
### DB Selector

DB3K

### Affected DBID(s)

Facility 868

### Summary of Changes

Comment section.
Service in Ground Self-Defence Force, not Air. 

Should use both ARH and IR version(Requested in #1808 )
Amount is 2x IR and 2x ARH for each mount.

### Sources

https://ja.wikipedia.org/wiki/81%E5%BC%8F%E7%9F%AD%E8%B7%9D%E9%9B%A2%E5%9C%B0%E5%AF%BE%E7%A9%BA%E8%AA%98%E5%B0%8E%E5%BC%BE

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
