### ISSUE TITLE
Add Iranian Arash Loitering Munition

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1812]
### DB Selector

DB3K

### Baseline

3271

### Hypothetical

No

### Name

Arash [Kian]

### Length (m)

4.5m

### Width/Span (m)

3.5m

### Diameter (m)

.75

### Weight (kg)

50kg (guesstimate)

### Range (nm)

540 nm

### Warhead

Unknown but 23kg warhead fine (payload is spec'd at 30kg)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

4m

### Sensors

EO Seeker

### Weapon Codes

Loiter Capability, Bearing-Only Launch (BOL), Weapon - INS Navigation, Re-Attack Capability, Weapon Altitude Control Possible, Attitude Control - Combined, Level Cruise Flight

### Comments

This has shown up enough to be in production. Lot of pictures of them in bulk on flightlines, caves and now ships. Range characteristics are close to Harop although less capable sensors. Seems like command-guided data linked to somebody elses EO

Looks like the army/irgc uses trucks with 2 launchers. The picture has a 3 truck grouping.

Cruise speed should be a bit higher (maybe for Harop too)

### Sources

https://www.thedrive.com/the-war-zone/iran-unveils-ominous-new-naval-drone-carrier-division
https://iranpress.com/content/53734/kian-combat-and-defense-drone
https://twitter.com/auroraintel/status/1346746832077156354?lang=en
https://www.youtube.com/watch?v=k2j1SgDjR-k
https://www.oryxspioenkop.com/2019/09/the-oryx-handbook-of-iranian-drones.html
https://www.thedefensepost.com/2019/09/02/iran-kian-drone/
https://www.militaryfactory.com/aircraft/loitering-munition-uavs.php

**Comment by PygmalionOfCyprus** [comment]
Handled 499 as part of ongoing Iran review. I don't think the Arash 1 has an EO sensor, I'm pretty sure it's just coord-driven. Arash 2 apparently has (or can be fitted with) a passive radar sensor for SEAD.
