### ISSUE TITLE
Queen Elizabeth Class CV (CATOBAR) 

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1813]
### DB Selector

DB3K

### Baseline

#1008

### Hypothetical

Yes

### Name

R 08 Queen Elizabeth [CATOBAR] 

### Class

Queen Elizabeth CV

### Country

UK

### Service

Royal Navy

### In Commission

2018+

### Number in Service

2

### Length (m)

Same as #1008

### Beam (m)

Same as #1008

### Draft (m)

Same as #1008

### Standard Displacement (t)

Same as #1008

### Full Displacement (t)

Same as #1008

### Empty Displacement (t)

Same as #1008

### Complement

Likely similar to Same as #1008, although some sources believe more crew would be required for CATOBAR Ops. 

### Max Sea State

Same as #1008

### Primary Propulsion Type

Gas Turbine

### Propulsion

Same as #1008

### Fuel Capacity (kg)

Same as #1008

### Flank Speed (kt)

Same as #1008

### Range (nm) at Speed (kt)

Same as #1008

### Sensors

Same as #1008

### Mounts

Same as #1008 but also with Sea Ceptor (CAMM) SAMs. As these are a hypothetical / possible future update to the QE Class, the exact number carried is not known but circa 24 CAMMs would likely be realistic. 

### Aircraft & Docking Facilities

Hangar space and elevators would be similar to #1008. The main difference is the addition of X2 EMALS and arrestor gear with the removal of the "ski jump" used for Short Take-Off operations by the F-35B. Instead, the UK would operate CATOBAR F-35C and E-2Ds (UK versions has also been requested in Github). 

### Comms/Datalinks

Same as #1008

### Ship Codes

Nuclear Shock Resistant, Degaussed Steel Hull

### Comments

Ship codes would likely match those of Same as #1008. Due to the added complexity of building the QE vessels with CATOBAR, their entry to service date for the CV may have slipped to 2020. 

![unknown-1](https://user-images.githubusercontent.com/99649251/180036148-b85fb995-5a50-4a27-87d4-cf18383cc6ea.png)

![unknown-3](https://user-images.githubusercontent.com/99649251/180036228-dcfdecfe-020e-48d2-b6e5-b77f5eedddd0.png)

### Sources

https://www.navylookout.com/cats-traps-and-claptrap-why-the-royal-navys-new-aircraft-carriers-operate-vstol-aircraft/

https://www.telegraph.co.uk/business/2022/07/17/how-13-whitehall-mandarins-crippled-britains-aircraft-carriers/

https://www.navylookout.com/should-hms-queen-elizabeth-be-fitted-with-her-own-missile-defences/

https://www.cmano-db.com/ship/1008/

**Comment by KushanGaming** [comment]
Done for DB496.
