### ISSUE TITLE
China - Type 927 oceanographic surveillance ship

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1815]
### DB Selector

DB3K

### Baseline

DBID #854

### Hypothetical

No

### Name

Type 927 oceanographic surveillance ship

### Class

Type 927 oceanographic surveillance ship

### Country

China

### Service

Navy

### In Commission

2018-Present

### Number in Service

3x

### Length (m)

90m

### Beam (m)

30m

### Draft (m)

Not Stated

### Standard Displacement (t)

5000t

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

Not Stated

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

Not Stated

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

Not Stated

### Range (nm) at Speed (kt)

Not Stated

### Sensors

Navigation Radar
SINO-SURTASS

### Mounts

Small Arms

### Aircraft & Docking Facilities

1x Small Helipad

### Comms/Datalinks

VHF/UHF
SATCOM

### Ship Codes

Advanced Quieting, Catamaran/Trimaran Multihull

### Comments

SWATH SURTASS ship similar to US and Japanese vessels.

### Sources

http://www.hisutton.com/Chinese-Navy-Type-927-Anti-Submarine-Sonar-Ship.html
https://en.wikipedia.org/wiki/Type_927_oceanographic_surveillance_ship
https://www.navyrecognition.com/index.php/focus-analysis/naval-technology/7426-three-types-of-927-surveillance-ship-entered-china-navy-in-2018-and-2019.html
https://www.globalsecurity.org/military/world/china/type-927.htm

![image](https://user-images.githubusercontent.com/99599482/180043193-46fbc906-7962-4b9a-8a6d-60ade7d6ecbe.png)

**Comment by PygmalionOfCyprus** [comment]
Handled during Pt.1 of our China review, which added all PLAN vessels (not counting stuff like tugs, etc. but you get the idea) and total ripout-rebuilds of every Chinese ship already in the DB.
