### ISSUE TITLE
F-35C Lightning II (UK) 

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1816]
### DB Selector

DB3K

### Baseline

#4935

### Hypothetical

Yes

### Name

Lightning II (F-35C)

### Country

UK

### Service

Royal Navy / RAF

### In Commission

2018+

### Number in Service

Potentially upto 138

### Length (m)

Same as #4935

### Wingspan (m)

Same as #4935

### Height (m)

Same as #4935

### Empty Weight (kg)

Same as #4935

### Maximum Takeoff Weight (MTOW) (kg)

Same as #4935

### Payload Weight (kg)

Same as #4935

### Crew

1

### Propulsion

Same as #4935

### Rate of Climb (ft/min)

Same as #4935

### Service Ceiling (ft)

Same as #4935

### Military/Afterburner Speed (kt)

Same as #4935

### Cruise Speed (kt)

Same as #4935

### Supercruise

No

### Ferry Range (nm)

Same as #4935

### Endurance (min)

Same as #4935

### Takeoff / Landing Distance (m)

Same as #4935

### Fuel Capacity (kg)

Same as #4935

### Sensors

Same as #4935, apart from the OECM. That will be the same as the UK's F-35B's (#1095) Export OECM. 

### Mounts

Same as #4935

### Loadout Options

Similar to #1095 with AIM-120Ds, ASRAAMs, Paveway IVs and the 25mm gunpod. 

### Comms/Datalinks

Same as #4935

### Aircraft Codes

Terrain Avoidance, Fly-by-Wire, Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Navigation (INS/GPS), Helmet Mounted Sight / Display (HMS/HMD), Probe Refuelling

### Comments

UK purchased F-35C, which, for several years (circa 2010-12) looked possible on a CATOBAR Queen Elizabeth CV.
This F-35C would be the UK's IOC variant with a later FOC variant also included. 
A 2025 UK F-35C Block 3I/4 variant based off of #4699 and #3836 would make sense, with the full array of UK weapons including X6 Meteors (with Sidekick), ASRAAMs, SPEAR 3, SPEAR EW, Storm Shadow, Paveway IVs etc. 

### Sources

https://www.cmano-db.com/aircraft/1095/

https://www.cmano-db.com/aircraft/4935/

https://www.cmano-db.com/aircraft/4699/

https://www.cmano-db.com/aircraft/3836/

"The SDSR announced the government's intention to switch its purchase of F-35Bs to the carrier-variant F-35C to allow for a wider range and weapons to be used. However, in May 2012 this decision was reversed, and the F-35B was chosen instead, as the previous government had intended. This was because the cost of converting the Queen Elizabeth-class aircraft carriers to accommodate the carrier-variant F-35C had risen to twice the original estimate."

https://en.m.wikipedia.org/wiki/Strategic_Defence_and_Security_Review_2010

**Comment by KushanGaming** [comment]
Done for DB 496.
