### ISSUE TITLE
E-2D Hawkeye (UK Royal Navy) 

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1818]
### DB Selector

DB3K

### Baseline

#4293

### Hypothetical

Yes

### Name

Hawkeye AEW.1

### Country

UK

### Service

Royal Navy

### In Commission

2021+

### Number in Service

Hypothetical - likely a small number 8-12 platforms

### Length (m)

#4293

### Wingspan (m)

#4293

### Height (m)

#4293

### Empty Weight (kg)

#4293

### Maximum Takeoff Weight (MTOW) (kg)

#4293

### Payload Weight (kg)

#4293

### Crew

#4293

### Propulsion

#4293

### Rate of Climb (ft/min)

#4293

### Service Ceiling (ft)

#4293

### Military/Afterburner Speed (kt)

#4293

### Cruise Speed (kt)

#4293

### Supercruise

No

### Ferry Range (nm)

#4293

### Endurance (min)

#4293

### Takeoff / Landing Distance (m)

#4293

### Fuel Capacity (kg)

#4293

### Sensors

Same as #4293

### Mounts

Same as #4293

### Loadout Options

Same as #4293

### Comms/Datalinks

Same as #4293. Possibly offboard Aster  / Meteor missile datalinks for CEC. 

### Aircraft Codes

Probe Refuelling

### Comments

Hypothetical UK Royal Navy E-2D Hawkeye for use on a CATOBAR capable QE CV. 

### Sources

https://www.cmano-db.com/aircraft/4293/

https://www.navylookout.com/cats-traps-and-claptrap-why-the-royal-navys-new-aircraft-carriers-operate-vstol-aircraft/

**Comment by KushanGaming** [comment]
Done for DB496.
