### ISSUE TITLE
MiG-29 SM+ for Serbia

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#182]
### DB Selector

DB3K

### Hypothetical

No

### Name

MIG29SM+

### Country

Serbia

### Service

Airforce

### In Commission

2021

### Length (m)

17.32

### Wingspan (m)

11.36

### Height (m)

4.73

### Empty Weight (kg)

11000

### Maximum Takeoff Weight (MTOW) (kg)

18000

### Crew

1

### Propulsion

2x RD-33

### Service Ceiling (ft)

45000

### Military/Afterburner Speed (kt)

920?

### Cruise Speed (kt)

480

### Supercruise

No

### Ferry Range (nm)

1100

### Sensors

N019M1 Radar (120km vs 5m2 target)
L-150 Pastel RWR
Talisman DECM pod? (Photos have surfaced with jamming pods under wings on outer pylon but too blurry to tell, suspect talisman as aircraft are modernized by Belarussian teams)

### Mounts

1x Gsh30 autocannon

### Loadout Options

2x RVV-AE (some sources state RVV-SD variant?)
4x R-73E
2x KH-31 ARM
2x KH-29
2x R-27R
2x R-27T
2x R-27ER
S-8 rockets
S-25 rockets
Kab-500 guided bombs

### Comms/Datalinks

Aa-10/12 datalink

### Aircraft Codes

Helmet Mounted Sight / Display (HMS/HMD)

### Comments

New variant introduced in Serbian Airforce in 2021. N019M1 radar only keeps standard N019 antenna, all other parts are replaced and range is stated to be weapons quality track for 5m2)(https://balk.hu/en/2021/05/18/a-total-of-14-in-serbia-have-received-two-more-while-29-have-received-game-machines-from-whitewasher/

https://srbin.info/en/drustvo/mig-29sm-ce-biti-okosnica-srpskog-ratnog-vazduhoplovstva/?lang=lat)

https://en.topwar.ru/183254-uznavaemyj-standartnyj-radar-dlja-istrebitelej-vvs-rf-opublikovany-pervye-izobrazhenija-serbskogo-mig-29sm.html

![EvTqS2WXYAEKAlm](https://user-images.githubusercontent.com/99824301/154723201-f3352b30-4d16-4a11-bfb7-fc9ed2e4a91d.jpeg)
https://www.key.aero/article/belarusian-mig-29s-bound-serbia

**Comment by TTZ32** [comment]
Update. Serbian MiG-29SM at batajnica today.

![Screenshot_20220430-175657_YouTube](https://user-images.githubusercontent.com/99824301/166097248-06094f67-bb97-4d60-93e3-0856f9e7f738.jpg)
![Screenshot_20220430-175652_YouTube](https://user-images.githubusercontent.com/99824301/166097257-fdbf8da7-abeb-4899-9267-4e92388e8b20.jpg)

**Comment by TTZ32** [comment]
Another update. 

They are calling this modernization MiG29SM+, the radar is also capable of detecting ground targets at 40km away. 

The man speaking in the video(in Serbian) is Nenad Miloradovic, who is the assistant minister for material resources for the ministry of Defense. 
https://youtu.be/0IJ-AZQHkRQ

**Comment by TTZ32** [comment]
https://youtu.be/laYdIb_pSpM

**Comment by Jkryos** [comment]
Added DB3K 495.
