### ISSUE TITLE
MH-6M Side Gunner

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1822]
### DB Selector

DB3K

### User(s)

US Army

### Weapons Carried

1x 7.62mm LMG
3x Troops

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

85nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Troop carrying MH-6Ms can now mount 7.62mm LMGs on side planks

### Sources

https://www.thedrive.com/the-war-zone/check-out-the-mh-6-little-birds-plank-mounted-machine-gun-setup?fbclid=IwAR36YcbRL_6kC4vQMURkDpynECyMLp6eEM-soFJyu5yOefw8Wz5cLCKiZ2A

![image](https://user-images.githubusercontent.com/99599482/180059373-31998843-fce4-4ca1-9019-40c94a585ee7.png)
![image](https://user-images.githubusercontent.com/99599482/180059394-ca913a95-7072-4850-bfe2-6de9bb8ea838.png)
![image](https://user-images.githubusercontent.com/99599482/180059474-0e20d01c-1997-438f-b283-a5e5da103c44.png)

**Comment by PygmalionOfCyprus** [comment]
Creates a lot of problems in Command. The weapon presumably comes off and goes with the troops when deployed, etc. More stable, but same idea as just having the guys on the side shoot, which is a "passengers can fire from vehicles" thing, which is currently out of scope. Gonna skip for now.
