### ISSUE TITLE
United States - EC-130J TACAMO

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1824]
### DB Selector

DB3K

### DBID to Copy

DBID #2880

### Hypothetical

Yes

### Name

EC-130J TACAMO

### Country

United States

### Service

Navy

### In Commission

First flight FY2026

### Number in Service

potentially up to 16

### Sensors

Similar to E-6B

### Mounts

None

### Loadout Options

Ferry
Airborne Command Post/TACAMO

### Other Changes

Additional fairings possibly for extra fuel.

### Sources

https://www.thedrive.com/the-war-zone/45086/this-is-our-first-look-at-the-navys-next-doomsday-plane?fbclid=IwAR02m8L7iEBQNX7vDLPKcbVFvFXH2jenKMhwxFkrDDLSBFIBUDNtDtomRXI

![image](https://user-images.githubusercontent.com/99599482/180064160-21811912-6052-4edc-883c-33805afb4e28.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
