### ISSUE TITLE
Irish P 41 Orla [Peacock]decommissioned 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1826]
### DB Selector

DB3K

### Affected DBID(s)

2634

### Summary of Changes

Add out of service date of 2022 for ship #2634

LÉ Orla (P 41) and LÉ Ciara (P 42) decommissioned July 7th

### Sources

https://www.janes.com/defence-news/irish-naval-service-decommissions-three-patrol-ships-as-part-of-modernisation-effort/
https://www.irishtimes.com/ireland/2022/07/08/irish-navy-decommissions-a-third-of-its-fleet/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
