### ISSUE TITLE
Irish P 31 Eithne out of service date 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1827]
### DB Selector

DB3K

### Affected DBID(s)

1289

### Summary of Changes

Add out of service date of 2022 for #1289

### Sources

https://www.janes.com/defence-news/irish-naval-service-decommissions-three-patrol-ships-as-part-of-modernisation-effort/
https://www.irishtimes.com/ireland/2022/07/08/irish-navy-decommissions-a-third-of-its-fleet/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
