### ISSUE TITLE
Add 20mm Narwhal 20B mounts to French Horizon Forbins from 2020

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1829]
### DB Selector

DB3K

### Affected DBID(s)

3214, 2793

### Summary of Changes

Narwhal mounts exist in db-used on FREMM

Add 3 mounts to Horizon (aft center, port and starboard). Remove 20mm Giats

### Sources

https://www.navalnews.com/naval-news/2020/03/nexter-naval-group-to-upgrade-narwhal-rws-on-all-french-navy-vessels/

https://twitter.com/D__Mitch/status/1231916772497948674?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1231916772497948674%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.navalnews.com%2Fnaval-news%2F2020%2F03%2Fnexter-naval-group-to-upgrade-narwhal-rws-on-all-french-navy-vessels%2F

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
