### ISSUE TITLE
Type 075 Yushen CIWS, Decoy and HQ-10 mount fixes

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1831]
### DB Selector

DB3K

### Affected DBID(s)

3153

### Summary of Changes

Need a few updates and corrections. 

Add 4 Decoy Launchers (2 mounts on each side of ship) Type 726-4A DL

PJ-11 730 CIWS
Arcs should be port 180 degrees for one and starboard 270 degrees

HQ-10
The forward arc should be 180 and aft mount 270 degrees

Add 4 12.7mm machine gun mounts. 2 Port and starboard.

Looks like it has FQF-6000 Mounts port and starboard as well

### Sources

CIWS, HQ-10 and Decoy launcher positions
https://www.sinodefenceforum.com/attachments/075-guangxi-6-jpg.88629/
https://twitter.com/sugar_wsnbn/status/1517011183462617089/photo/2
https://twitter.com/sugar_wsnbn/status/1517011183462617089/photo/2
https://live.staticflickr.com/65535/51747824879_83d668e6c0_k.jpg
https://live.staticflickr.com/65535/51271845356_f6e7e6e842_o.jpg

FQF-6000
https://twitter.com/sugar_wsnbn/status/1524375973395075072

12.7mm machine gun
https://live.staticflickr.com/65535/52020554162_d3410ca06e_k.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
