### ISSUE TITLE
Add Pakistani YLC-6M Radar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1834]
### DB Selector

DB3K

### DBID to Copy

2461

### Hypothetical

No

### Name

YLC-6M

### Country

Pakistan

### Service

Air Force

### In Commission

2005

### Sources

https://twitter.com/FarooqB90714421/status/1506607298181210119
http://www.ausairpower.net/APA-PLA-IADS-Radars.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
