### ISSUE TITLE
Add Egyptian YLC-6M

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1835]
### DB Selector

DB3K

### DBID to Copy

2461

### Hypothetical

No

### Name

YLC-6M

### Country

Egypt

### Service

Air Force

### In Commission

2015

### Sources

http://www.ausairpower.net/APA-PLA-IADS-Radars.html
https://world-defense.com/attachments/r7l4qri-jpg.1211/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
