### ISSUE TITLE
RCAF CH-130H - Missing SAR Loadout

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#184]
### DB Selector

DB3K

### User(s)

#3106, #3107, #1695

### Weapons Carried

Missing SAR loadouts for RCAF Hercules

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

3200?

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night Capable

### Capable of Quick Turnaround

Yes

### Comments

The CC-130H Hercules is primarily used for search and rescue operations. While it also carries out transport missions, its main focus is saving lives through the Canadian Armed Forces’ search and rescue mandate.

It has a range of more than 7,200 kilometres and can transport approximately 80 passengers, operate on short unpaved runways and fly in severe weather conditions. These capabilities make the CC-130H an excellent aircraft for search and rescue operations over the vast span of Canada’s central and northern regions.

Possible to use DBID#8038 from HC-130H USCG as SAR loadout while also retaining its regular cargo loadouts.
Not sure if 

### Sources

https://en.wikipedia.org/wiki/Canadian_Armed_Forces_Search_and_Rescue 
http://www.rcaf-arc.forces.gc.ca/en/article-template-standard.page?doc=an-overview-of-our-search-and-rescue-aircraft/kffs07ge

**Comment by Jkryos** [comment]
Added DB3K 494.
