### ISSUE TITLE
Canada City Class Frigate (RWS to replace 50cal)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1840]
### DB Selector

DB3K

### Baseline

1898 and 3569 DB3K

### Hypothetical

No

### Name

330 HMCS Halifax

### Class

City Class

### Country

Canada

### Service

Navy

### In Commission

2018 first unit installed on HMCS Winnipeg

### Number in Service

12x

### Length (m)

135.5

### Beam (m)

16.4

### Draft (m)

4.9

### Standard Displacement (t)

4305

### Full Displacement (t)

4761

### Empty Displacement (t)

3922

### Complement

227

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

Same as 2012 entry

### Flank Speed (kt)

29

### Range (nm) at Speed (kt)

Same as 2012 entry

### Sensors

Same as 2012 entry

### Mounts

4x #2205 12.7mm/50 Mini-Typhoon RWS (1x port bridge wing, 1x starboard bridge wing, 1x port aft corner, 1x starboard aft corner behind helicopter pad)

### Comments

1) According to [Timothy Choi](https://twitter.com/TimDotChoi), naval analyst at the University of Calgary in Canada, the mid-life refit work will focus on the hull, mechanical, and electrical works that were not included as part of the FELEX upgrades. “The only substantial new component that I’m aware of are the four .50cal remote weapons system” Choi added.

The NRWS are .50 cal Mini typhoon RWS by Israeli company Rafael, modified and adapted by Raytheon.2) 

The Naval Remote Weapon Station project will acquire remotely operated, stabilized weapon mounts and their associated operator consoles to replace the manually-fired Heavy Machine Gun mounts currently in service.

Requirements
"The Naval Remote Weapon Stations will be fitted on all 12 HALIFAX Class ships and at training facilities for shore based training. Additionally, the project will procure stations to be provided as Government Furnished Equipment to the Joint Support Ship project. Each ship will be fitted with four stations in order to provide all-around coverage, for a total of 58 stations. The project also includes provision of initial spares for all stations and installation of each system for HALIFAX Class, as well as delivery of initial cadre training, technical data package and all associated manuals.

A contract for this project was awarded to Raytheon Canada Limited in 2016. The contract value for this project is $40.5 million.

Anticipated Timeline (Fiscal Year)
Completed Start Options Analysis
Completed Start Definition
Completed Start Implementation
2019/2020 Initial Delivery (HMCS Winnipeg is due to be the first ship outfitted with the new stations in early 2018.)
2022/2023 Final Delivery

### Sources

http://dgpaapp.forces.gc.ca/en/defence-capabilities-blueprint/project-details.asp?id=1745
https://www.naval-technology.com/uncategorised/newsraytheon-to-equip-canadian-halifax-frigates-with-new-weapon-stations-4841433/
https://www.lookoutnewspaper.com/ministers-announce-new-remote-naval-weapons-stations-install-halifax-class-ships/
"HMCS Winnipeg is due to be the first ship outfitted with the new stations in early 2018."
https://sdquebec.ca/en/news/davie-shipyard-begins-halifax-class-frigate-mid-life-refit-program

2 stations visible on bridge starboard/port wings, other two are on aft corners behind the landing pad.
https://laststandonzombieisland.files.wordpress.com/2022/04/hmcs-montreal-ffh-336-ch-148-april-2022.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
