### ISSUE TITLE
Sukhoi S-70: Change in radar signature with internal loadout

### ISSUE THREAD

**Issue by leostun** [PygmalionOfCyprus/cmo-db-requests#1841]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #4906

### Summary of Changes

The radar signature of the drone is increased for two of the loadouts that should be internal.
Judging by the "Ready Aircraft" menu some of the missiles are not set as internal in the DB.

### Sources

![4906](https://user-images.githubusercontent.com/77802333/180376185-091ce80f-55f7-44fe-892e-3e9c734d9962.png)

**Comment by PygmalionOfCyprus** [comment]
>Judging by the "Ready Aircraft" menu some of the missiles are not set as internal in the DB.
You are correct! Fixed for 496.
