### ISSUE TITLE
China - Tianlei 500 (Sino-JSOW)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1842]
### DB Selector

DB3K

### Baseline

JSOW

### Hypothetical

No

### Name

Tianlei 500

### Length (m)

As JSOW

### Width/Span (m)

As JSOW

### Diameter (m)

As JSOW

### Weight (kg)

500Kg

### Range (nm)

32

### Target Altitude / Depth (ft)

As JSOW

### Target Speed (kts)

As JSOW

### Launch Altitude / Depth (ft)

As JSOW

### LaunchSpeed (kts)

As JSOW

### Warhead

 240 individual submunitions

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

As JSOW

### Sensors

1x Laser Seeker referenced

### Weapon Codes

Terminal Illumination, Supports Buddy Illumination, Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Attitude Control - Aerodynamic Only, Uses GPS, Uses GLONASS, Uses BeiDou/COMPASS, Level Cruise Flight

### Comments

The Tianlei 500 is a 500-kilogram bomb, or the equivalent of 1,100 pounds. The bomb carries 240 individual submunitions about the size of a tennis ball, and is designed to spread them across an area of 6,000 square meters. The bomblets, each with the explosive power of a hand grenade.

Sources reference it cratering runways. I'm skeptical about a CB with 240 hand grenades cratering runways. Didn't list Runways as a target as such.

The Post claims the weapon is also laser-guided, but no laser seeker is visible in the example missile shown, though it could be a mockup or different version, so included in the guidance options.

Seen being dropped from J-8 Finback

### Sources

https://www.popularmechanics.com/military/weapons/a33635662/china-glide-bomb-tianlei-500/
https://www.thedrive.com/the-war-zone/35778/new-chinese-air-launched-glide-weapon-designed-to-be-an-airfield-killer

![image](https://user-images.githubusercontent.com/99599482/180438706-d48a937d-471c-4e34-aa02-e2154abf5348.png)
![image](https://user-images.githubusercontent.com/99599482/180438739-52d03f10-703f-4603-be84-bd11307a6aca.png)
![image](https://user-images.githubusercontent.com/99599482/180439234-9c0661ab-6242-45f8-945f-8185e38dd7ce.png)

**Comment by LuigiP57** [comment]
Maybe this GB 500C is a powered ER version of it?
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/645cac03-9947-4805-8878-5083edf8a4c6)

**Comment by LuigiP57** [comment]
Platforms include at least: J-10C, JF-17, JH-7
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/df9c7122-5908-400f-94bc-e52dada42350)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/e66e2718-1bfa-40ea-a5ea-eee5de728372)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/498a6c21-6483-4357-b02f-8789d3a3fd76)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/e5e2292d-d47c-4efa-ba83-45f546b65a5a)

**Comment by yU2187sie** [comment]
In fact, according to the current outflow of pictures, J-11, J-15,J-16 series fighters also have the ability to mount the weapon.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/75aa5b2c-70ba-49f1-a557-7943c240804d)
![DM_20240501135828_001](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/bb1cbe8f-fd30-4ba0-89cf-c8a82827faec)
↑Above is a video of the J-8F firing the ammunition.：）

**Comment by yU2187sie** [comment]
@PygmalionOfCyprus @Jkryos According to the information I have, the Tianlei500 has the ability to load multi-seed ammunition, and can choose different submunitions according to different types of targets. In summary, I question the description in your comment that the Tianlei500 submunitions are not effective at disabling the runway.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/3ac6dd68-f275-409c-91aa-e1a433ece7b6)
![QQ20240501135230](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/a2cc2148-e29c-4348-a89e-be93d28064f5)
According to the CCTV Military Channel program, the Tianlei500 can be loaded with multi-seed ammunition.

**Comment by tbrandon517** [comment]
> @PygmalionOfCyprus @Jkryos According to the information I have, the Tianlei500 has the ability to load multi-seed ammunition, and can choose different submunitions according to different types of targets. In summary, I question the description in your comment that the Tianlei500 submunitions are not effective at disabling the runway. ![image](https://private-user-images.githubusercontent.com/130222813/327058145-3ac6dd68-f275-409c-91aa-e1a433ece7b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzA2MzgsIm5iZiI6MTcxNDU3MDMzOCwicGF0aCI6Ii8xMzAyMjI4MTMvMzI3MDU4MTQ1LTNhYzZkZDY4LWYyNzUtNDA5Yy05MWFhLWUxYTQzM2VjZTdiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMzMyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWRlZjM2MzZjNDA1NGJlYzE3ZTExODg3YzFkMjkwMDkwNTVjYzQyODMzNWVlNWY1NDNkM2ZkNzM5NjA4N2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tViN4t6LmROzcTTMGG8gH6p2D6Ny5uqf02a3ZD58T0w) ![QQ截图20240501135230_译图](https://private-user-images.githubusercontent.com/130222813/327059330-a2cc2148-e29c-4348-a89e-be93d28064f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzA2MzgsIm5iZiI6MTcxNDU3MDMzOCwicGF0aCI6Ii8xMzAyMjI4MTMvMzI3MDU5MzMwLWEyY2MyMTQ4LWUyOWMtNDM0OC1hODllLWJlOTNkMjgwNjRmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxMzMyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTc2Y2Q0MzAyZDZkOGRjYmZkN2ZiNzIxZWYyMDNkYjk3NjI3YWEzYWFlNzRkMjMyMTFkZjkxM2FlYmU3NjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dXcjeiuGPM9_1bxqNdgYnpqNT2WWsJylr645zuJDfWY) According to the CCTV Military Channel program, the Tianlei500 can be loaded with multi-seed ammunition.

That was with limited information from two years ago. I welcome any revisions based on more updated information.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
