### ISSUE TITLE
Armed Quadcopter - Rotary Mortar Drum Magazine

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1844]
### DB Selector

DB3K

### User(s)

Armed Quadcopter

### Weapons Carried

8x - 60 mm Mortar Rounds

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

4.3nm (8 km)

### Weather Restrictions

Clear Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

20 Minute Endurance indicated

### Sources

https://www.thedrive.com/the-war-zone/now-theres-a-drum-magazine-for-dropping-multiple-bombs-from-commercial-drones?fbclid=IwAR1QsRxeYDdDQxY4ioLaemawm213imUqsrkfQ3KS41wgoPsxF579DnfK6xY
https://twitter.com/DefMon3/status/1525448394159931394?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1525448411436175360%7Ctwgr%5E%7Ctwcon%5Es2_&ref_url=https%3A%2F%2Fwww.thedrive.com%2Fthe-war-zone%2Fnow-theres-a-drum-magazine-for-dropping-multiple-bombs-from-commercial-drones

![image](https://user-images.githubusercontent.com/99599482/180448261-e2079877-99e0-41d4-bca6-bdf999eac73a.png)

**Comment by PygmalionOfCyprus** [comment]
Not yet fielded by anyone and remains a very niche setup. Quadcopter mods also sort of fall under the "technical rule," i.e. there's gonna be a gazillion different variants and we'll go crazy trying to cover them all.

I am, however, gonna add a generic armed loadout w/ some 60mm mortar rounds for the quadcopter.
