### ISSUE TITLE
Ukraine - RQ-20B Puma UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1845]
### DB Selector

DB3K

### DBID to Copy

aircraft 5448

### Hypothetical

No

### Name

RQ-20B Puma UAV

### Country

Ukraine

### Service

Army

### In Commission

2022-

### Number in Service

Not Disclosed

### Sensors

No Changes

### Mounts

No Changes

### Loadout Options

No Changes

### Other Changes

No Changes

### Sources

https://i-hls.com/archives/114049?utm_source=dlvr.it&utm_medium=facebook&fbclid=IwAR1KB_k6n6041mY1NR3pzfq54MMWfAq0pzjlqZtQ9OJPotFR5ta6hceQ3YA
https://defence-blog.com/ukraine-receives-rq-20-unarmed-aerial-vehicles-donated-by-us/
https://mil.in.ua/en/news/rq-20-puma-ukrainian-military-will-be-receiving-modern-uavs-from-the-united-states/
https://www.armyrecognition.com/defense_news_april_2022_global_security_army_industry/aerovironment_from_us_to_provide_ukraine_with_rq-20_puma_ae_uas_unmanned_aerial_systems.html
https://defbrief.com/2022/04/15/aerovironment-gets-19-7m-to-deliver-rq-20-puma-drones-for-ukraine-by-end-of-may/
https://alert5.com/2022/04/15/aerovironment-delivering-rq-20s-to-ukraine-by-end-of-may/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
