### ISSUE TITLE
Ukraine - SAM Technical (2x Mistral)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1846]
### DB Selector

DB3K

### DBID to Copy

DBID #1981 - Technical

### Hypothetical

No

### Name

Vehicle (Truck, Armed Technical [Mistral] x 2)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

unknown

### Sensors

mk 1 eyeball

### Mounts

2x Mistral

### Loadout Options

Mistral Reloads

### Sources

https://www.thedrive.com/the-war-zone/ukraine-turned-fiat-trucks-into-mobile-surface-to-air-missile-systems?fbclid=IwAR06awD8t05qTTlp4iCeOJICiGAGJkOgOULqD3mePLDpSy1bqBMtMFnXnrI

![image](https://user-images.githubusercontent.com/99599482/180450760-3a069bdc-5ded-402b-9c0c-02be6cedfe68.png)

**Comment by PygmalionOfCyprus** [comment]
We're trying not to get sucked down a route of adding DB entries for every new technical variant someone spots out in the wild. I think it's better to just have those be created in-editor with mount additions/removals.

**Comment by tbrandon517** [comment]
> We're trying not to get sucked down a route of adding DB entries for every new technical variant someone spots out in the wild. I think it's better to just have those be created in-editor with mount additions/removals.

Not applicable here since a 2x Mistral mount exists, but I'm guessing a request for a weapon mount, if seen, with no corresponding DB entry would be OK. That way it can just be added in the editor.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus could a regular manpad unit be added to Ukraine?

**Comment by PygmalionOfCyprus** [comment]
>could a regular manpad unit be added to Ukraine?

Handled 505.
