### ISSUE TITLE
GMLRS CEP Fix

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#1847]
### DB Selector

DB3K

### Affected DBID(s)

#3136, #50

### Summary of Changes

Regarding M270 MLRS, M142 HIMARS, MARS II, etc. ammunition.

Unguided MLRS rockets #773 - M26 MLRS [644 x M77 DPICM Dual Purpose], #772 - M27A1 MLRS ER [518 x M85 DPICM Dual Purpose], and #770 - MLRS AT2 [28 Anti-Tank Mines] have 80 m CEP against land and surface targets (where applicable).

New GMLRS, like #2699 - M31 GMLRS [90kg HE], has 10 m CEP against land and surface targets, representing guidance.

However, whilst **#50 - M30 GMLRS [404 x M85 DPICM Dual Purpose]** has 10 m CEP against land targets, it has only 80 m CEP against surface targets. Additionally, **#3136 - M30A1 GMLRS [Alternative Warhead]** has 80 m CEP against both land and surface targets.

These appear to be oversights, and both **#50** and **#3136** should have 10 m CEP in all cases, to represent the 'G' in GMLRS.

### Sources

DB 495.

**Comment by PygmalionOfCyprus** [comment]
Whoops. Handled 496.
