### ISSUE TITLE
United States - Riverine Assault Boast (RAB)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1848]
### DB Selector

DB3K

### DBID to Copy

ship 2314

### Hypothetical

No

### Name

Riverine Assault Boast (RAB)

### Country

United States

### Service

Navy

### In Commission

2003-

### Number in Service

uncertain

### Sensors

Furuno navigation radar

Later

sensor turrets with electro-optical and infrared cameras
smoke grenade launchers at the rear
Some even had electronic warfare jammers to defeat improvised explosive devices along the shoreline.

### Mounts

The standard configuration for the Navy included five weapons stations, two on either side of the bow, two on either side amidships, and one at the stern. The mounts in each of these positions could accommodate a variety of weapons, including .50 caliber M2 machine guns, 7.62mm Miniguns, and 7.62mm M240 machine guns. 

Several images show a configuration of 1x M2 .50 cal at stern, 2x M240 P/S amidships, 2x Miniguns P/S at Bow stations.

The boats also had armored shields that can be placed along their sides to offer additional protection, which appear to be missing from the example that is up for auction now.

### Loadout Options

N?A

### Other Changes

The RABs themselves are variants of the Special Operations Craft-Riverine (SOC-R). 6 crew vs 5 Crew/8 PAX for SOC-R per manufacturer. RAB can carry additional personnel as shown in photos.

### Sources

https://usmi.com/portfolio/33-riverine-assault-boat/
https://www.thedrive.com/the-war-zone/30138/you-can-buy-this-u-s-navy-high-speed-riverine-assault-boat

Full Kit with Radar top by EO/IR and flanked by ECM, 4x Quad smoke launders at stern
![image](https://user-images.githubusercontent.com/99599482/180455639-34beebb8-37ea-4070-8108-274c379bb8f7.png)

![image](https://user-images.githubusercontent.com/99599482/180455776-7be7de25-64f3-452d-9199-199f99e0a6f4.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
