### ISSUE TITLE
United States - Riverine Command Boat (CB90 Variant)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1849]
### DB Selector

DB3K

### DBID to Copy

ship 3266

### Hypothetical

No

### Name

Riverine Command Boat

### Country

United States

### Service

Navy

### In Commission

2007-

### Number in Service

6x

### Sensors

Radar

### Mounts

1x Remote-controlled weapon mount for a .50-caliber machine gun — or other weapon — on a mast behind the cockpit. 
4x mounts for crew-served weapons elsewhere on the boat. 

All mounts include electrical power supply to allow the use of mini-guns. 

Weapon Options are M2HB .50 Cal HMG, M240 7.62mm LMG, GAU-17 7.62mm Minigun, GAU -19 12.7mm Gatling Gub, Mk19 40mm AGL

A mortar or Hellfire missiles can be deployed from the deck.

### Other Changes

N/A

### Sources

https://en.wikipedia.org/wiki/CB90-class_fast_assault_craft#Operators
https://web.archive.org/web/20160116124341/https://www.archive.militarytimes.com/article/20070801/NEWS/708010326/New-riverine-boats-fast-lethal-flexible
https://archive.ph/20120805113826/http://www.navy.mil/view_single.asp?id=81689
https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2171638/riverine-command-boat/
https://www.militaryfactory.com/ships/detail.php?ship_id=riverine-command-boat-united-states

![image](https://user-images.githubusercontent.com/99599482/180459746-4c4b5cde-3415-4b9a-a17c-e5dd9c841973.png)
![image](https://user-images.githubusercontent.com/99599482/180459812-b77c1c0e-00fd-462a-a006-059d4fb99cf6.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
