### ISSUE TITLE
RCAF CC-130HT Tanker 1992, x5

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#185]
### DB Selector

DB3K

### Hypothetical

No

### Name

CC-130HT

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1992-

### Length (m)

29.3

### Wingspan (m)

40.4

### Height (m)

11.9

### Empty Weight (kg)

34400

### Maximum Takeoff Weight (MTOW) (kg)

70300

### Payload Weight (kg)

19090

### Crew

5

### Propulsion

4x T56-A-15 #1

### Rate of Climb (ft/min)

1140

### Service Ceiling (ft)

32000?

### Military/Afterburner Speed (kt)

230/250/325

### Cruise Speed (kt)

200/220/290

### Supercruise

No

### Ferry Range (nm)

4270

### Takeoff / Landing Distance (m)

451-900m TOD/LAD

### Fuel Capacity (kg)

28540

### Sensors

1x AN/APN-59
1x Mk1 Eyeball

### Mounts

No weapons

### Loadout Options

- Ferry DB ID #15876
- Maintenance
- Reserve
- Tanker [Wing Drogue] (Air Refueling) DB ID #15877

### Comms/Datalinks

1x VHF Radio [Unsecure]
1x HF radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Wing Drogue

### Comments

Looks like it would be a copy of the info in DB#2975. 
Canada ordered x5

### Sources

http://www.rcaf-arc.forces.gc.ca/en/squadron/435-squadron.page
http://espritdecorps.ca/army-articles/fueling-the-fire-435-squadron-delivers-air-to-air-refueling-for-a-quarter-century
https://skiesmag.com/news/435-squadron-delivers-air-to-air-refuelling-for-a-quarter-century/
https://skiesmag.com/features/435-transport-and-rescue-squadron-double-mission-single-focus/

![8053796827_7388712d2b_o](https://user-images.githubusercontent.com/99632305/154343649-04589707-6912-485a-9d95-b8d8fef9bb03.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
