### ISSUE TITLE
United States, Philippines, Ukraine - Small Unit Riverine Craft (SURC)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1850]
### DB Selector

DB3K

### Baseline

RHIB 2313

### Hypothetical

No

### Name

Small Unit Riverine Craft (SURC)

### Class

Small Unit Riverine Craft (SURC)

### Country

United States, Philippines, Ukraine

### Service

US Navy/Marine Corps, Filipino Marines, Ukraine Navy

### In Commission

US 2004-, Philippines 2013-, Ukraine 2022 -

### Number in Service

US 100x. +24 RPB variant, Philippines 6x, Ukarine 2x

### Length (m)

12m

### Beam (m)

3.1m

### Draft (m)

0.61m

### Standard Displacement (t)

not stated

### Full Displacement (t)

10 t

### Empty Displacement (t)

Not Stated

### Complement

2 crew 16 PAX

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2x Yanmar 6LY2A-STP diesel engines, 440 bhp (330 kW) at 3300 RPM; 2xHamilton waterjets HJ292

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

39 kts

### Range (nm) at Speed (kt)

250 nm @ 35 kts

### Sensors

Ritchie magnetic compass
Integrated AN/PSN-11 GPS (PLGR)
[Raymarine](https://en.wikipedia.org/wiki/Raymarine) SL72 LCD radar
ST 60 depth sounder
Raymarine RAY53
VHF marine band radio
AN/VIC-3 internal stations
SINCGARS (VHF tactical) radio

### Mounts

3x mounts for heavy machine gun and smoke launchers, 2x P/S bow, 1x Stern, 4x Quad Smoke Grenade Launchers

Normal fit seems to be 2 M240 Forward and 1 M2HB at Stern,

### Aircraft & Docking Facilities

N/A

### Comms/Datalinks

Ritchie magnetic compass
Integrated AN/PSN-11 GPS (PLGR)
Raymarine SL72 LCD radar
ST 60 depth sounder
Raymarine RAY53
VHF marine band radio
AN/VIC-3 internal stations
SINCGARS (VHF tactical) radio

### Ship Codes

All Aluminum Construction

### Comments

Hull is beachable with landing ramp in the bow.

### Sources

https://en.wikipedia.org/wiki/Small_unit_riverine_craft
https://news.usni.org/2013/09/26/u-s-gives-philippine-marines-six-riverine-boats-counter-terrorism-missions
https://globalnation.inquirer.net/86545/us-gives-ph-6-patrol-boats-to-fight-moro-militants-in-mindanao
https://www.globalsecurity.org/military/systems/ship/surc.htm
https://web.archive.org/web/20160116124341/https://www.archive.militarytimes.com/article/20070801/NEWS/708010326/New-riverine-boats-fast-lethal-flexible
https://pdf.nauticexpo.com/pdf/safe-boats/surc/20867-21298.html
https://web.archive.org/web/20160116124341/https://www.archive.militarytimes.com/article/20070801/NEWS/708010326/New-riverine-boats-fast-lethal-flexible
https://marinejetpower.com/case/surc-by-safe-boats-international/
https://www.thedrive.com/the-war-zone/these-are-the-riverine-patrol-boats-ukraine-is-getting-from-the-u-s
http://www.navypedia.org/ships/usa/us_aws_surc.htm
https://www.navypedia.org/ships/usa/us_aws_rpb.htm

![image](https://user-images.githubusercontent.com/99599482/180462738-01b108ee-1728-4973-98fb-77e26e97cae3.png)
![image](https://user-images.githubusercontent.com/99599482/180462800-6cf3f89e-a707-4ade-b801-6b9c24521f60.png)
![image](https://user-images.githubusercontent.com/99599482/180464605-f180d260-fda6-4f69-963e-7e63469e9925.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
