### ISSUE TITLE
Large HIMARS and MLRS Ammunition Discrepancy

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#1851]
### DB Selector

DB3K

### Affected DBID(s)

Modern M270 and all M142 entries.

### Summary of Changes

Forgive my misinterpretation of the response given to issue #1780 if this is already resolved, however, current implementation permits unintended ammunition loading for the M270 entries with PrSM integration (#3267, #3377, #3378, #3379), and all M142 entries.

Observing the final entry in the image below, the weapons tab shows that, in the original M270 configuration, ammunition comes as '6x/cell', and crucially fits into two slots, representing two pods, seen in the image as '(2/2)' in the second column. The DB viewer calls this 'Capacity' under the Mounts/Stores/Weapons section. This works marvellously, and should provide a format for expansion.

However, the three prior examples show where this format has been shifted, and now creates problems. Since MLRS and GMLRS (and soon GMLRS ER) rockets get the '6x/cell' feature, having more than one 'slot' for HIMARS, and two 'slots' for MLRS allows one to load far more rockets than intended. Note the image displays a HIMARS that has been given two slots in error, to accommodate the PrSM. It should have just one slot, and the PrSM should become '2x/cell'. Otherwise, we a single HIMARS TEL occupied by six GMLRS rockets in one slot, and a PrSM in the other slot. The other two weapon mounts included show more of the same excessive ordnance.

![image](https://user-images.githubusercontent.com/108229956/180463531-0f1e4244-e6dd-4e61-b5ae-abb7245bc370.png)

Again, the simple fix is to make HIMARS one slot, or one capacity; MLRS two slots, or two capacity; and PrSM 2x/cell. This would mean six rockets or two PrSM per HIMARS, and a combination of twelve rockets/four PrSM/six rockets + two PrSM for MLRS, which is how it should work.

The weapon mount IDs (as appear in the 'Add Mount' dialogue for the Weapon Tab in the Editor) for affected M270 mounts are
**#3433, #3434, #3435, #3436**.
For M142, they are all the HIMARS mounts in the list:
**#3437, #3438, #3439, #3440, #3084, #3453, #2308, #2701**. The Singaporean one mentioned in the previous issue is #3084.

The Facility unit IDs for M270 to go to two capacity are:
**#3267, 3377, #3378, #3379**.
For M142 going to one capacity:
**#3268, #3380, #3381, #3382, #3384, #2446, #2807, #3204 (the Singaporean one), #1968**. If Ukrainian, Polish, Finnish, or other acquisitions of HIMARS are freshly included in 496, they may need attention, too.

If all this was already fixed in the reply to capcop98's issue, I am sorry. Currently, however, capcop98 is correct. I realise in normal play these errors will affect precisely nothing because manual editing or reloading would have to happen to take advantage of the flaws.

### Sources

DB 495.

**Comment by PygmalionOfCyprus** [comment]
You are completely correct. @capcop98, you were right in #1780 and I fugged it.

Fixed, for real this time, for 496.
