### ISSUE TITLE
Japan, SAM-1B, facility

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1852]
### DB Selector

DB3K

### DBID to Copy

Facility 756

### Hypothetical

No

### Name

SAM-1B Tan-SAM[Type 81]

### Country

Japan

### Service

Navy

### In Commission

1992-2006

### Other Changes

Basically a original SAM-1A but for JMSDF(Navy).

### Sources

https://ja.wikipedia.org/wiki/81%E5%BC%8F%E7%9F%AD%E8%B7%9D%E9%9B%A2%E5%9C%B0%E5%AF%BE%E7%A9%BA%E8%AA%98%E5%B0%8E%E5%BC%BE

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Also, looking at the Wikipedia, shouldn't we change the current SAM-1A to JGSDF rather than JASDF since it was the JGSDF providing security for JASDF bases?

**Comment by KC45jp** [comment]
Actually, SAM-1 is for JGSDF, SAM-1A for JASDF, and SAM-1B is for JMSDF. (SAM-1C is only for JGSDF)

I forgot to request SAM-1 (not with A) for JGSDF service. Year from 1982.

Unlike US military, JASDF has full responsibility to defend their own bases + ABM(PAC-3). JMSDF was used to do Air Defense but they giving it up around 2000, and now either JGSDF or JASDF helps it.
