### ISSUE TITLE
update 1L119 Nebo SVU to 3D, is not 2D like the older Nebo-SV 

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#1854]
### DB Selector

DB3K

### Affected DBID(s)

1849

### Summary of Changes

Nebo SVU is a 3D radar, so should be updated. The older Nebo-SV 1L13-3 is a 2D

"The Nebo SVU is a critically important technological development as it provides a mobile 3D VLO/LO target acquisition and midcourse tracking capability for modern air defence missile systems like this S-300PMU2 Favorit" -Ausairpower
![nebo-svu 2](https://user-images.githubusercontent.com/108960393/180598530-1ad4e9f5-c584-4a53-9f46-9097b71fae63.png)

![nebo-svu 1](https://user-images.githubusercontent.com/108960393/180598537-471baeff-47fc-4c31-9bac-65363829e1ed.png)

### Sources

http://ausairpower.net/APA-Rus-Low-Band-Radars.html#mozTocId6430

http://ausairpower.net/APA-Nebo-SVU-Analysis.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496, also tweaked some values.

**Comment by TheBagelInhaler** [comment]
Thank you! :)
