### ISSUE TITLE
DF-100 Active Radar Seeker added to

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1855]
### DB Selector

DB3K

### Affected DBID(s)

weapon #3669

### Summary of Changes

1x Active Radar Seeker （same as the one on kh-47m2, for example）
Added for its anti-ship capability (surface ships has already on the valid targets list

### Sources

https://en.wikipedia.org/wiki/CJ-100
http://www.military-today.com/missiles/df_100.htm
https://nationalinterest.org/blog/buzz/df-100-chinas-biggest-threat-us-navy-145172

**Comment by PygmalionOfCyprus** [comment]
It's not clear that the DF-100 actually has a seeker. It well might, but considering its stated purpose as being for use against land structures and "large ships," it's also wholly possible that it relies solely on GNSS guidance. That wouldn't be unusual for a hypersonic weapon; the incredibly high speeds at which they travel (generating plasma, etc.) make onboard sensor usage very difficult.

I'm not going to give it a seeker until we get firm evidence that it has one, but I have made some minor changes to the platform to account for the info you provided (e.g. giving it onboard DECM and BeiDou nav).
