### ISSUE TITLE
German EF2000 CAP loadout - AMRAAM and Meteor combined

### ISSUE THREAD

**Issue by redgreybeard** [PygmalionOfCyprus/cmo-db-requests#1856]
### DB Selector

DB3K

### User(s)

#3227, #3634, #5213, #5214

### Weapons Carried

- 2x AIM-2000A IRIS-T
- 2x AIM-120B AMRAAM
- 4x Meteor
- 2x 1000l Drop Tank

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Luftwaffe still uses AMRAAM alongside Meteor. Please see vid in sources.

### Sources

(In German) Neu bewaffnet | Eurofighter mit modernster Rakete der Welt | Bundeswehr
https://www.youtube.com/watch?v=TjCbbgyGQkE

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
