### ISSUE TITLE
Czechoslovakia - Avia S-92 Turbina

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1857]
### DB Selector

CWDB

### DBID to Copy

aircraft 3843

### Hypothetical

No

### Name

Avia S-92 Turbina

### Country

Czechoslovakia 

### Service

Air Force

### In Commission

1947-1951

### Number in Service

nine S-92 and three CS-92

### Sensors

Same as Me 262 A-1a

### Mounts

Same as Me 262 A-1a

### Loadout Options

Ferry
Internal Guns

Some sources indicate they could carry the 24x R4M Rocket loadouts like Luftwaffe Me 262 A-1a's.

Some sources indicate it could carry loadouts of 2× 250 kg (550 lb) bombs or 2× 500 kg (1,100 lb) bombs like the Me 262 A-2a variant.

### Other Changes

None

### Sources

https://en.wikipedia.org/wiki/Messerschmitt_Me_262#Postwar_variants
http://www.military.cz/czech/air/avia/s92/default.htm (In Czech)
https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=1884
https://acesflyinghigh.wordpress.com/2019/02/16/the-survivors-czechoslovakias-avia-s-92-turbina-me-262/
https://wwiiafterwwii.wordpress.com/2015/08/12/the-s-92-czechoslovakias-me-262/
http://www.aviastar.org/air/czech/avia_s-92.php
https://tanks45.tripod.com/Jets45/Histories/Avia-S_92/Avia-S_92.htm

![image](https://user-images.githubusercontent.com/99599482/180619672-2c9410b3-dde4-404b-b05b-d139fb4cfd7f.png)
![image](https://user-images.githubusercontent.com/99599482/180619673-befd9b8c-3cf1-4cd9-945a-4a976b6a06d2.png)
![image](https://user-images.githubusercontent.com/99599482/180619695-95e1cdc2-9041-4d58-b81c-1cb7fc282baf.png)
![image](https://user-images.githubusercontent.com/99599482/180619700-61293d38-2349-4d49-aedf-84bc43208b30.png)
![image](https://user-images.githubusercontent.com/99599482/180619733-c17ff599-1bab-46c3-bf82-c22a189c16df.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
