### ISSUE TITLE
Add Chinese Type 052DL Luyang III [156 Zibo] x8++

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#186]
### DB Selector

DB3K

### Hypothetical

No

### Name

156 Zibo

### Class

Type 052DL

### Country

China

### Service

Navy

### In Commission

2020

### Length (m)

161

### Beam (m)

18

### Draft (m)

6.5

### Standard Displacement (t)

7200

### Full Displacement (t)

7600

### Complement

280

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

Combined Diesel or Gas (CODOG) 2 x QC-280 gas turbines (28 MW / 38000 hp, each) 2 x MTU-20 V956 TB92 diesel engines (3.82 MW / 10250 hp, each)

### Flank Speed (kt)

30 kts

### Range (nm) at Speed (kt)

Same as 52D

### Sensors

China Type 346A
Type 518B or 520 . NATO A to C Band
Type 344 Radar, Firecontrol OTH (this is the Chinese copy designation of Bandstand/Mineral)
Bull Nose MGK-335MS-E hull-mounted sonar
China SKDX VDS
China SGJ-206 TASS
NRJ-6a ECM and ESM
Type 760 Pea Sticks Nav Radar
Type 349A Radar
Type 754 Air Search- Helo approach Radar
3 IR/EO elements

### Mounts

H/PJ-45 Deck Gun (Similar to H/PJ-38 but higher rate of fire)
VLS and HQ-10 same as #2296. I think HHQ-9B are likely at this point
2x Type 7424B Triple torpedo launchers 324mm (for Yu-7 Torpedoes)
4 726-4 Decoy Launchers: 2 Each side
Type 1130H/PJ-11 close-in weapon system (CIWS) (instead of 730 on earlier units)
2 China towed decoys likely

### Aircraft & Docking Facilities

1 Pad and 1 Hanger for Medium Aircraft (must fit Z-20F)
2 Small Davits

### Comms/Datalinks

HF, VHF, UHF, Secure
SA-10 Missile Datalink (24 Channel)
Satcom

### Ship Codes

Degaussed Steel Hull, All Aluminum Construction

### Comments

Can probably copy #2296 and modify
Key differences between base model

- PJ-45 Deck Gun although #2296 should be corrected to add the PJ-45 vs the PJ-38
- Slightly longer to support Z-20 helicopters
- 518B/520 VHF Radar to better detect stealthy stuff. Replaces 517H-1 Knife Rest on plain 052D. . Looks a lot like first JY-27. 
- Type 11 1130H/PJ-11 CIWS replaces 730 on 52D

Update mags to support helicopter Yu-7 and Yu-11 loadouts.

### Sources

https://www.seaforces.org/marint/China-Navy-PLAN/Destroyers/Type-052D-Luyang-III-class-DDG.htm
https://en.wikipedia.org/wiki/Type_052D_destroyer
https://www.defenseworld.net/news/27401/China_s_Upgraded_052DL_Warship_has_Anti_stealth_Radar__Longer_Helicopter_Deck#.Yg1KHN_MJD8
https://inf.news/en/military/1ac78c2645bc29449ee6575a97aa1f28.html
https://twitter.com/vcdgf555/status/1448205700098772997
Radar:
https://www.sinodefenceforum.com/t/type-052c-052d-class-destroyers.6881/page-444
https://twitter.com/evazhengll/status/1419915102933897216
https://www.radartutorial.eu/19.kartei/02.surv/karte027.en.html

Deck Gun
https://daydaynews.cc/en/military/945024.html
http://china-defense.blogspot.com/2017/07/correcting-internet-130mm-naval-gun.html
IR/EO
https://www.sinodefenceforum.com/t/type-052c-052d-class-destroyers.6881/page-464

**Comment by PygmalionOfCyprus** [comment]
Added off the old tracker!
