### ISSUE TITLE
hq-9b ABM Capability

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1860]
### DB Selector

DB3K

### Affected DBID(s)

weapon #3763

### Summary of Changes

target speed: 0~4500kt
warhead: ABM-optimized frag

### Sources

https://en.wikipedia.org/wiki/HQ-9
https://twitter.com/i/web/status/1442527427620605966

**Comment by LuigiP57** [comment]
It says that the missile can tackle 1000km range SRBM/MRBM
![image](https://user-images.githubusercontent.com/107970049/180628940-7f9e035d-7429-42e9-aca7-bab5681fe097.png)

**Comment by KC45jp** [comment]
Isn't it say HQ-9BE?
Then it should add as different entry, isn't it?

**Comment by LuigiP57** [comment]
> Isn't it say HQ-9BE? Then it should add as different entry, isn't it?

Hello, well, it is acknowledged that "E" represents "Export variant". And I'm not sure whether there is a current user of this type of weapon, thus I haven't opened an issue about it. However, I made a request of HQ-9/P (FD-2000, Pakistan).

**Comment by LuigiP57** [comment]
> > Isn't it say HQ-9BE? Then it should add as different entry, isn't it?
> 
> Hello, well, it is acknowledged that "E" represents "Export variant". And I'm not sure whether there is a current user of this type of weapon, thus I haven't opened an issue about it. However, I made a request of HQ-9/P (FD-2000, Pakistan).

Oh,I think I have found the user : 
https://northafricapost.com/54458-morocco-receives-chinese-anti-aircraft-defense-system-fd-2000b.html

**Comment by LuigiP57** [comment]
#1893

**Comment by PygmalionOfCyprus** [comment]
Changed max target speed but not warhead as I don't believe the missile has been ABM _optimized_ so much as it possesses a limited ABM capability.
