### ISSUE TITLE
China, HHQ-9B, SAM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1861]
### DB Selector

DB3K

### Baseline

weapon #3763

### Hypothetical

No

### Name

HHQ-9B

### Length (m)

6.8

### Width/Span (m)

1

### Diameter (m)

0.52

### Weight (kg)

1800kg

### Range (nm)

2.0 - 125.0

### Target Speed (kts)

0kt - 4500kt

### Warhead

180kg ABM-Optimized Frag (63 DP)

### Targets

Aircraft, Missile, Surface Vessel

### Sensors

Same as hhq-9

### Weapon Codes

Anti-Air All-Aspect, Capable vs Seaskimmer, Lock-On After Launch (LOAL) - CEC-Capable, Level Cruise Flight

### Comments

Platform: Ship 2296, 3586, 3587, 2834, 3883 (all type 052d and type 055)

### Sources

https://en.wikipedia.org/wiki/HQ-9
https://weaponsystems.net/system/947-HHQ-9
![image](https://user-images.githubusercontent.com/107970049/180628791-71dfd9b5-eca7-4dd7-8b24-60f0b2751c5c.png)

**Comment by LuigiP57** [comment]
#1860

**Comment by KC45jp** [comment]
Target Altitude- min 25m -max 30,000m
https://www.guancha.cn/military-affairs/2017_05_08_407286.shtml

it is questionable for me to add Lock-On After Launch (LOAL) - CEC-Capable...
HQ series develop around 90's-00's tech, I cannot see any resource suggesting this.

**Comment by LuigiP57** [comment]
HHQ-9 intercepting sea-skimming targets: 
https://www.youtube.com/watch?v=_pezJKg4M98

> Target Altitude- min 25m -max 30,000m (This should also applied to base unit, HQ-9B(Weapon ID 3763)) https://www.guancha.cn/military-affairs/2017_05_08_407286.shtml

Because of the simulation flaws, if you make the effective minimum target altitude at 25m (about 75ft), the missile won't be able to engage a wide range of sea-skimming missiles (LRASM, YJ-12, SS-N-26 etc.). The "sea-skimming interception capability" is a dynamic concept, not a still one in this game. In conclusion, it would be better to remain the target altitude as it is now.

> it is questionable for me to add Lock-On After Launch (LOAL) - CEC-Capable...
HQ series develop around 90's-00's tech, I cannot see any resource suggesting this.

No valid evidence found either.

**Comment by KC45jp** [comment]
I agree with you. They are ARH Missiles, if they have reduce Sea Clutter capability (especially with -9B, which has IR Guidance), they should not have difficulty with shooting down. I forgot about it.

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
