### ISSUE TITLE
Update/correction of JH-7A/A2/B

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1862]
### DB Selector

DB3K

### Affected DBID(s)

2071, 4653, 254, 3312, 5596, 4905, 4329

### Summary of Changes

-Add Properties: Fly-by-Wire and Helmet Mounted Sight / Display (HMS/HMD)  as JH-7A/A2/B does have the FBW and HMD capability.
![image](https://user-images.githubusercontent.com/99646926/180648660-c7615f21-679f-4d31-9454-fbf7f826b2d2.png)
![image](https://user-images.githubusercontent.com/99646926/180649077-6587862b-d571-4e20-809e-24d15297240a.png)

-Add Properties: Probe Refueling to JH-7B(Aircraft/4329) only 
![image](https://user-images.githubusercontent.com/99646926/180648620-80436771-ed3a-414d-91cc-6c1ef61b3943.png)

-Add illumination capability (Operating bands (FC / Illumination) : I) to JL-10A(Sensor/2298) and JL-10A+(Sensor/6004) radar just like China Type 1492(Sensor/4171). Also add Maximum targets illumination to 6 targets.
![image](https://user-images.githubusercontent.com/99646926/180648590-c8634d41-8d5b-4b7e-a948-10244dff13ed.png)

-Add  PL-11 missile loadout for all JH-7A/A2/B as it does have the capability to guide and fire the missiles. Each aircraft can carry: 4x PL-11, 2x PL-5/8A and 3x 1400 liter drop tank.
![image](https://user-images.githubusercontent.com/99646926/180648556-d6133c58-059c-4bfa-88a6-3f112d9fb130.png)

-Add Pl-12 missile loadout for all JH-7A/A2/B as it does have the capability to guide and fire the missiles. Each aircraft can carry: 4x PL-12, 2x PL-5/8A and 3x 1400 liter drop tank. Unlike previous request #400 , i have recently found a picture that showed PL-12 were really fitted on JH-7A and few other sources that indicates PL-12 can be fired from JH-7A.
![image](https://user-images.githubusercontent.com/99646926/180648713-d5654ae9-126f-4a05-9a26-5084e5283331.png)
![image](https://user-images.githubusercontent.com/99646926/180648952-14907c3a-13e0-406b-bc7d-b9d06c7e851d.png)

### Sources

https://www.sinodefenceforum.com/t/jh-7-jh-7a-jh-7b-thread.912/
http://www.airvectors.net/avcnft.html#m2
https://en.wikipedia.org/wiki/JL-10A
http://mail.ausairpower.net/APA-Zhuhai-2014.html
http://aviadejavu.ru/Site/Arts/Art6188.htm (in Russian)
https://www.globalsecurity.org/military/world/china/jh-7b.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
