### ISSUE TITLE
Japan, CH-47J/JA, correction, copy

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1863]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4304, 756, 4310, 4305

### Summary of Changes

Sensor
---
For All
Delete
AN/AAQ-16
AN/APR-39

For
CH-47JA(ID 4305)
Generic LLTV, 3rd Gen, (sensor ID 401) (I know this is made in Japan, but the name is unknown.)

Copy to
----
CH-47JA (Early 2000, so I would say just 2000), PKO service capable
Base: CH-47JA(ID 4305)
Sensor:
AN/AAR-47A(V2) (ID 2017)
Mounts:
AN/ALE-47 x4 (AN/ALE-47(H) in record)
2x 12.7mm HMG

### Sources

CH-47JA + AN/ALE-47 + 12.7mm HMG
https://trafficnews.jp/post/99737/2

CH-47JA AN/AAR-47 procurement record 
https://www.njss.info/offers/view/246163/

CH-47JA AN/ALE-47(H)
https://www.njss.info/offers/view/544425/

**Comment by PygmalionOfCyprus** [comment]
This image would seem to imply the presence of the AN/APR-39 on at least some versions of the JGSDF Chinooks.

![image](https://user-images.githubusercontent.com/87087226/180697960-2c47e0cd-3970-40e0-a675-a1ef69ebb6c9.png)

**Comment by PygmalionOfCyprus** [comment]
Otherwise, handled 496.

**Comment by KC45jp** [comment]
Thanks for correction.

**Comment by KC45jp** [comment]
It was actually a AN/APR-L12, I search the record by APR-39 and that was the why I could not find it.
https://judgit.net/projects/19949

**Comment by PygmalionOfCyprus** [comment]
Aha! So, I ought to create an entry for the J/APR-L12 and put that on the new "2000" version of the CH-47JA, yeah?

**Comment by KC45jp** [comment]
Yep, APR-39 is not appear in official procurement record, so that is the right RWR.
