### ISSUE TITLE
Mirage 5 Recce Updates

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#1864]
### DB Selector

DB3K

### Affected DBID(s)

3065, 3067, 3070

### Summary of Changes

The second Mirage 5BR in the database, with LORAL Rapport II jammers, has accidentally lost the 4x Generic Visual Reconnaissance Cameras of the #3064 Mirage 5BR and is unable to carry out reconnaissance missions. This, unfortunately, renders the aircraft completely useless since it also has no non-recce loadouts.

Upon further inspection, the related DB entries 3067 and 3070 suffer from the same issue.

### Sources

https://www.belgian-wings.be/dassault-mirage-5br

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
