### ISSUE TITLE
Mirage 5BR for Chile

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#1865]
### DB Selector

DB3K

### DBID to Copy

3065

### Hypothetical

No

### Name

Mirage 5BR

### Country

Chile

### Service

Air Force

### In Commission

1995

### Number in Service

4x

### Sensors

Per issue #1864, needs reconnaissance cameras

### Other Changes

Presumed retired, one known to be preserved at the National Air and Space Museum in Santiago as of 2015, which looks like it might have been there a while.
![image](https://user-images.githubusercontent.com/109925704/180669057-7d59b17d-6c9c-41c3-87d8-6e0e9b07c779.png)

### Sources

http://www.sbap.be/archivalia/mirsip/mirsip.htm
https://www.mirage5.be/History-Belgian%20Mirage%205B.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
