### ISSUE TITLE
Add Retirement date of 2022 to AC-130W Stinger II

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1869]
### DB Selector

DB3K

### Affected DBID(s)

3105

### Summary of Changes

Add an out of service date of 2022. Replaced by Js

### Sources

https://www.scramble.nl/military-news/going-out-with-a-bang
https://www.youtube.com/watch?v=-yyf4l3KnHY
https://www.dvidshub.net/video/846963/ac-130w-stinger-ii-retirement

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
