### ISSUE TITLE
RCAF CC-115 Buffalo (de Havilland Canada DHC-5)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#187]
### DB Selector

Both

### Hypothetical

No

### Name

CC-115 Buffalo

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1968-2022

### Length (m)

24

### Wingspan (m)

8.53

### Height (m)

8.7

### Empty Weight (kg)

11412

### Maximum Takeoff Weight (MTOW) (kg)

22316

### Payload Weight (kg)

8164

### Crew

6 SAR, 4 Transport

### Propulsion

2x General Electric CT64-820-3 turbine engines (3060hp)

### Rate of Climb (ft/min)

1970

### Service Ceiling (ft)

31000

### Military/Afterburner Speed (kt)

250

### Cruise Speed (kt)

200

### Supercruise

No

### Ferry Range (nm)

1150

### Takeoff / Landing Distance (m)

1-450m TOD/LAD

### Fuel Capacity (kg)

4990

### Sensors

1x Mk1 Eyeball

### Mounts

No Weapons

### Loadout Options

- Ferry DB ID #22129
- Maintenance
- Reserve
- Cargo 5 tons DB ID #22130
- Cargo 8 tons DB ID #22131
- Troops 40x DB ID #22132
- SAR **NEEDS TO BE CREATED**

### Comms/Datalinks

- UHF/VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

- Main details can be copied from DB ID #5054, #4339
- The first CC-115s performed a medium tactical transport role, such as transportation of troops and equipment. In the 1970s, most of the Buffalo fleet were transitioned to search and rescue (SAR) operations

### Sources

https://www.rcaf-arc.forces.gc.ca/en/aircraft-current/cc-115.page
https://www.va3kgb.com/milac/cc115_buffalo.htm

![cc-115-buffalo-fact-sheet-image](https://user-images.githubusercontent.com/99632305/154352330-39027487-42d8-4813-a7ee-a349d081af9d.png)

**Comment by Jkryos** [comment]
Added CWDB 494.
