### ISSUE TITLE
Add Ukrainian Stormer SAM

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1870]
### DB Selector

DB3K

### DBID to Copy

1722

### Hypothetical

No

### Name

SAM Plt (Starstreak II Stormer)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

x5

### Sources

https://twitter.com/oryxspioenkop/status/1550896775325679618

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
