### ISSUE TITLE
Add Ukrainian Stinger MANPAD

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1871]
### DB Selector

DB3K

### DBID to Copy

1267

### Hypothetical

No

### Name

SAM Sec (Stinger MANPAD x5)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Other Changes

Looks like E variants (RMP)

### Sources

https://twitter.com/FunkerActual/status/1509942430082256898
https://twitter.com/islamicworldupd/status/1494319462572462092
https://twitter.com/DF_AJ/status/1492953506092929029
https://twitter.com/baz2000/status/624352384597233664/photo/1
https://en.wikipedia.org/wiki/FIM-92_Stinger

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
