### ISSUE TITLE
Add Ukrainian M-777 155mm Artillery

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1872]
### DB Selector

DB3K

### DBID to Copy

2299

### Hypothetical

No

### Name

Arty Bty (155mm/39 M777 Towed Howitzer)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Sources

https://twitter.com/DefenceU/status/1548622966040182786
https://twitter.com/RALee85/status/1551515836422258695
https://twitter.com/anno1540/status/1551517991724093440
https://twitter.com/Taurevanime/status/1550974755968278528

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
