### ISSUE TITLE
Add Ukrainian 155mm Krab Self Propelled Artillery

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1873]
### DB Selector

DB3K

### DBID to Copy

2048

### Hypothetical

No

### Name

Arty Bty (155mm/52 Self-Propelled Krab Howitzer)

### Country

Ukraine 

### Service

Army

### In Commission

2022

### Sources

https://twitter.com/Osinttechnical/status/1550289956299542528
https://twitter.com/UAWeapons/status/1541863828387946497
https://twitter.com/UAWarNews/status/1551605424302030850
https://twitter.com/Exen/status/1542602654014226435

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
