### ISSUE TITLE
Add Ukrainian PZH-2000 Self Propelled Howitzer

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1874]
### DB Selector

DB3K

### DBID to Copy

2133

### Hypothetical

No

### Name

Arty Bty (155mm/52 PzH 2000 Self-Propelled Howitzer)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Other Changes

Ex German and Dutch

### Sources

https://twitter.com/war_noir/status/1544803029429501952
https://twitter.com/bealejonathan/status/1548300196714467329
https://twitter.com/AZmilitary1/status/1542109980685488128
https://twitter.com/Rinegati/status/1549111476840972288
https://twitter.com/UAWeapons/status/1542152495836930048

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
