### ISSUE TITLE
Add Ukrainian M109A3GN 155mm Self Propelled Artillery

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1875]
### DB Selector

DB3K

### DBID to Copy

618

### Hypothetical

No

### Name

Arty Bty (155mm/39 M109A3GN Self-Propelled Howitzer)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Other Changes

Norway and the UK sent or are sending these

### Sources
https://twitter.com/UAWeapons/status/1533150302265810945
https://twitter.com/UAWeapons/status/1535013884100239361
https://twitter.com/sfcdavidpeters/status/1551335097617600513
https://twitter.com/TheBaseLeg/status/1538115675293552640
https://twitter.com/UkrWarReport/status/1550096952045539328
https://twitter.com/UAWeapons/status/1534148275581894659

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
