### ISSUE TITLE
Add Ukrainian HIMARS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1876]
### DB Selector

DB3K

### DBID to Copy

2446

### Hypothetical

No

### Name

Arty Plt (HIMARS)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

~20

### Other Changes

No indication they got ATACM yet

### Sources

https://twitter.com/BlogUkraine/status/1551572063508373504
https://www.washingtonpost.com/national-security/2022/07/24/ukraine-himars-russia-us/?utm_campaign=wp_main&utm_medium=social&utm_source=telegram
https://twitter.com/Ukrainy_1991/status/1550867159697354752
https://twitter.com/UAWeapons/status/1551667064338784258

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
