### ISSUE TITLE
#3429 - SA-25 Verba [9K333] - Change to SA-29 Gizmo [9M336 Verba] and change facility #3037 - SAM Sec (SA-25 Verba [9K333] MANPADS x 3) (Russia [1992-] - 2014) 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1878]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #3429 - SA-25 Verba [9K333] and facility #3037 - SAM Sec (SA-25 Verba [9K333] MANPADS x 3) (Russia [1992-] - 2014) 

### Summary of Changes

Weapon #3429 - SA-25 Verba [9K333] - Change name and convention to 
SA-29 Gizmo [9M336] -- 2014, 9K333 Verba. The missile is the 9M336 the entire system is the 9K333.

Change facility to match convention of. 
#3037 - SAM Sec (SA-25 Verba [9K333] MANPADS x 3) (Russia [1992-] - 2014) 
Change  to:
#3037 - SAM Sec (SA-29 Gizmo [9K333] MANPADS x 3) (Russia [1992-] - 2014)

(This will also resolve the issues with the duplicated **SA-25 9M96 entry? #2825 - SA-25 [9M96]?**)

### Sources

https://www.globaldefensecorp.com/2020/12/11/russia-supplied-verba-manpad-to-hezbollah-violating-arms-trade-treaty/ refers SA-29.

 **SA-25 is not used by Verba MANPADS contrary to a lot of websites.**** 
SA-25 designation for Verba MANPADS appears wrong. IISS has referred to Verba 9M336 as **SA-29 Gizmo** for two consecutive editions 2021 and 2022 of the Military Balance (they have been known to be wrong but...)
cannot at the moment find a free and non-copyrighted link to the relevant part of the military balance but it is in there as follows:
9K310 Igla-1 (SA-16 
Gimlet); 9K34 Strela-3 (SA-14 Gremlin); 9K38 Igla (SA-18 
Grouse); 9K333 Verba (SA-29 Gizmo); 9K338 Igla-S (SA-
24 Grinch)
Pp.193 Military Balance 2021.

https://weaponsystems.net/system/772-9K333+Verba
https://www.bing.com/search?q=sa-29+gizmo&qs=n&form=QBRE&sp=-1&pq=sa-29+gizmo&sc=8-11&sk=&cvid=E208EF1491854806B71D918904454A63&ghsh=0&ghacc=0&ghpl=
https://en.wikipedia.org/wiki/List_of_NATO_reporting_names_for_surface-to-air_missiles
https://youtu.be/CF2H5MdifDc?t=28 clip shows Verba crate being offloaded in Ru forces in Syria 9M336 markings are clear on the box.

**Comment by KLABDB3K** [comment]
As an aside there are also the following references in the Military Balance to:
SA-28 For S-350 Vityaz and SA-N-28 for corresponding Redut Poliment naval system. Pp194. 
SS-C-7 Southpaw for Iskander GLCM 9M728.
SS-N-30A Sagaris, Kalibr 3M14 LACM.

**Comment by PygmalionOfCyprus** [comment]
Handled 496, including bonus name changes in the comment.
