### ISSUE TITLE
Type 18, Torpedo

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1879]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3904

### Summary of Changes

Reliability/PoH
---
This should be increased, from current 80% which is same as old Type 89.
This torpedo has Magnetic Proximity Fuze, which increased the Reliability of hit. (Or you might can make another code for Sensor or weapon to simulate?)

Year:
---
2022

Depth
---
0-900m

Sensor
---
**Range**
Extended by using LF sonar: I would say 3nm

**Frequency**
VLF By it assert they made it wide band sonar

**Generation**
Late 2010

**Code**
- Classification [Class Info] / Brilliant Weapon [Automatic Target Aquisition] (Code 1002, This is because the sonar with imaging capability. OR if it is not correct code, perhaps we might need new sensor code?)
- Shallow water capable

### Sources

Wiki
https://ja.wikipedia.org/wiki/18%E5%BC%8F%E9%AD%9A%E9%9B%B7

some detail info for the Proximility Fuze
https://web.archive.org/web/20150831182823/http://www.mod.go.jp:80/trdi/news/0402_02.html

Wide Band Sensor
https://ja.wikipedia.org/wiki/18%E5%BC%8F%E9%AD%9A%E9%9B%B7#/media/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:Type18-Torpedo-01(Japan).png

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
