### ISSUE TITLE
RCAF C-295 Kingfisher x16

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#188]
### DB Selector

DB3K

### Hypothetical

No

### Name

C-295 Kingfisher 

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2022-

### Length (m)

24.5

### Wingspan (m)

25.81

### Height (m)

8.65

### Empty Weight (kg)

9600

### Maximum Takeoff Weight (MTOW) (kg)

23,200

### Payload Weight (kg)

9,250

### Crew

6

### Propulsion

2x Pratt & Whitney Canada (PWC)  PWC 127G turboprop engines, rated at 2,750 shp each

### Rate of Climb (ft/min)

1410/4240

### Service Ceiling (ft)

30000

### Military/Afterburner Speed (kt)

310

### Cruise Speed (kt)

260

### Supercruise

No

### Ferry Range (nm)

2900

### Takeoff / Landing Distance (m)

451-900m TOD/LAD

### Fuel Capacity (kg)

6150

### Sensors

- 1x MX-15 multi-sensor imaging system beneath its nose to localize, track, identify and detect targets in day / night and difficult weather conditions.
- 6x high-definition imaging and laser sensors such as laser rangefinder, laser illuminator, and Electro-Optical / Infrared (EO / IR) cameras. Developed by L-3 Wescam
- 1x multi-mode search radar is fitted under the fuselage to provide an unobstructed 360° field of view. It can detect, recognize, classify and track both land and water-based objects such as fishing vessels, merchant ships, inflatable boats and small craft up to a distance of 200nm.

### Mounts

No weapons

### Loadout Options

- Ferry DB ID #28191
- Maintenance 
- Reserve
- Cargo 
- SAR **Needs to be created**

### Comms/Datalinks

- VHF [Unsecure]
- HF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Sensors:
Search Radar
- Multi-mode radar for detection, localization, classification, and tracking of targets 
over water and land – all weather, day or night
- Maximum range of 200 nm, tracking 100+ surface targets while scanning
- Detects: Ocean-going fishing vessels or merchant ships between 80-200 nm; Small 
craft or inflatable boats up to 35 nm; and, SAR mode provides the capability of 
distinguishing and recognizing ground contacts
Electro-Optical/Infrared sensors
- Stabilized, high magnification imaging sensors greatly extend detection, recognition, and identification range
- Multi-spectral imaging (daylight, low light, and thermal) enables search operations 
under sub-optimal conditions, such as overcast, dusk, and even complete darkness
- Target geo-location eases handoff to ground personnel
- EO/IR sensors lend themselves to search automation

### Sources

https://static1.squarespace.com/static/5ce2eac378733900016331b2/t/5e9a192a78a37700d788feae/1587157292287/CC-295_Airforce_43No4_09Feb2020_V2.pdf
https://theaviationist.com/2020/10/06/canada-has-received-the-first-cc-295-kingfisher-search-and-rescue-aircraft/
https://www.canada.ca/en/department-national-defence/services/procurement/fixed-wing-search-and-rescue-procurement-project.html
www.rcaf-arc.forces.gc.ca/en/aircraft-current/cc-295.page
https://skiesmag.com/features/king-northern-skies-cc295-kingfisher/

**Comment by Jkryos** [comment]
Added DB3K 494.
