### ISSUE TITLE
Canada Provider AOR

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1880]
### DB Selector

Both

### Affected DBID(s)

CWDB: 1285, 233, 235

### Summary of Changes

Named as unit "500 Provider" when they should be named as "AOR 508 Provider". The ship was always 508.

### Sources

Janes, Combat Fleets of the World

https://en.wikipedia.org/wiki/HMCS_Provider_(AOR_508)
http://www.forposterityssake.ca/Navy/HMCS_PROVIDER_508.htm
https://www.readyayeready.com/ships/shipview.php?id=1337

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #137
