### ISSUE TITLE
Canada DDE Restigouche

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1881]
### DB Selector

CWDB

### Affected DBID(s)

CWDB: 6, 662

### Summary of Changes

Entry should be with hull number 257 for HMCS Restigouche instead of 236 which was HMCS Gatineau like it is for DBID#279.

### Sources

Janes, Combat Fleets of the World

https://en.wikipedia.org/wiki/Restigouche-class_destroyer
http://www.forposterityssake.ca/Navy/HMCS_RESTIGOUCHE_257.htm
https://www.seaforces.org/marint/Canadian-Navy/Destroyer/DDE-257-HMCS-Restigouche.htm
https://www.canada.ca/en/navy/services/history/ships-histories/restigouche.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
