### ISSUE TITLE
Add Ukrainian NASAMS III (copy of DB3K ID #3127) 

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#1883]
### DB Selector

DB3K

### Hypothetical

No

### Name

NASAMS-III

### Facility Type

SAM

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

1-2

### Crew

4-8

### Sensors

[AN/MPQ-64 Sentinel](http://cmano-db.com/sensor/2803/) - (NASAMS II) Radar
Radar, Air Search, 3D Short-Range
Max Range: 74.1 km

copy of #3127

### Mounts

copy of #3127
 2x NASAMS-III (capacity 6) 

### Magazines

x18 MIM-120B

### Comments

just a copy of NASAMS-III using MIM-120B (16nm) range missiles for Ukraine - 30km range missiles

### Sources

https://www.defensenews.com/pentagon/2022/07/01/us-to-send-ukraine-advanced-nasams-air-defense-weapons-in-820-million-package/

https://en.wikipedia.org/wiki/NASAMS#Operators

https://www.reuters.com/world/europe/us-sending-ukraine-two-surface-to-air-missile-systems-pentagon-2022-07-01/

**Comment by PygmalionOfCyprus** [comment]
Could have saved yourself a fair bit of data entry by using the "Copy Entry" form. 😛

**Comment by PygmalionOfCyprus** [comment]
Handled 496.

**Comment by TheBagelInhaler** [comment]
Thanks!! Somehow I completely didn't notice the copy entry form lol
