### ISSUE TITLE
Tweak/Correct range values for Gamma-D/DE radars

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#1886]
### DB Selector

DB3K

### Affected DBID(s)

3218, 3219

### Summary of Changes

Noticed when doing some tests in flat open land using the Gamma-DE AESA radar for many different type of small targets (low observable combat drones, camcopters, JAS-39 Gripen) that the range values were inconsistent with the range chart shown on AusAirPower / seems to underperform and even be outmatched by less powerful PESA radars like the 96L6/64N6 big bird c
![Rus-L-band-Radar-Params-2008](https://user-images.githubusercontent.com/108960393/180942199-7d7da197-1f30-41f0-8ea9-823da9c65feb.png)

I tested the Jas-30 Gripen (~1.2m2) at 4 different altitudes (10973m, 7620m, 3658m and 650m). According to the chart the gripen should be detected at least 216nm (400km) at the highest altitude of (10973m). Since the radar is shown to have a 216nm range for a 1m2 target. Instead for high altitudes between 7620-10973m, Gamma-DE detected the Gripen at 57nm (105km) and at 45nm/83km for lower altitudes of 650-1000m which makes sense since they are much lower, and this system has a more high altitude scan function. I also tested a 0.01m2 drone at medium/high altitudes and Gamma-D only detected at 20nm when it should (according to available info) detect that size target at 70nm. Smallest target I tested was 0.007m2 at very high altitudes and range detected was 11.3nm when it should be closer to 40nm.

According to the Ausairpower range chart, the 67N6E Gamma D1E (domestic variant) detection range (most likely for medium-high altitude crafts 8000-10m/25,000-36,000ft high) is 
~216nm for 1m2 target
~130nm for 0.1m2 
~70nm for 0.01m2
~40nm for 0.001m2
~22nm for 0.0001m2
consistent with the export catalog range descriptions

A tweak to correct these range values would be great

### Sources

https://www.radartutorial.eu/19.kartei/02.surv/karte063.en.html

http://www.ausairpower.net/APA-Rus-Low-Band-Radars.html#mozTocId228464

**Comment by HVAA** [comment]
Your 1m2 range is not backed up by your source.  216nm is 400km.  The Russian and the translation both say that the range is 360km (scope limited), elsewhere it contradicts even this stating that the range for all 3 variants is 315km, again looks like an instrumented range (as in scope range).  You have to be careful with radars, they have a MUR  (maximum unabmbiguous range) which is based on PRI (if present), peak and average power, system gain and, if Pulse Doppler' the number of 'bins'in the array amongst other parameters. Scope range is what the display is set to and what the radar can display to.  It may be able to detect targets further than the scope is set to, but it cannot display these, nor will it create tracks for them.
