### ISSUE TITLE
Swap out ESSM for Mica VLS on Saudi Al Jubail #3721

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1887]
### DB Selector

DB3K

### Affected DBID(s)

3721

### Summary of Changes

Swap put ESSM VLS mount for Mica
Got launch pictures-16 VLS module. Square tail fins so Mica.

### Sources

https://www.navalnews.com/naval-news/2022/07/navantia-delivers-2nd-avante-2200-corvette-to-saudi-arabia/

**Comment by PygmalionOfCyprus** [comment]
Closing in favor of relabeled #917
