### ISSUE TITLE
Please add LCA Tejas Mk1 Twin seater version

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1889]
### DB Selector

DB3K

### DBID to Copy

418 Tejas Mk1

### Hypothetical

No

### Name

LCA Tejas Mk1(Twin Seater) - India(Air Force), 2014

### Country

India

### Service

Air Force

### In Commission

2014 - 

### Sensors

same as Aircraft/418

### Mounts

same as Aircraft/418

### Loadout Options

same as Aircraft/418 and also add training loadout (2x 500 liter drop tank as opposed to its ferry loadout)

### Other Changes

-Change the crew from 1 to 2

-Remove Probe Refueling capability as it didn`t have those as per below picture
![image](https://user-images.githubusercontent.com/99646926/181020429-af3ffce0-436a-48bc-99aa-c9f8ec54fa82.png)

### Sources

https://www.newindianexpress.com/nation/2018/feb/07/french-air-force-chief-general-andre-lanata-takes-sortie-on-tejas-fighter-jet-1769808.html
https://en.wikipedia.org/wiki/HAL_Tejas#Production_variants

**Comment by PygmalionOfCyprus** [comment]
Good timing: I just did a deep review of the Tejas for 496. Fun fact, the aircraft in your picture is not the twin-seater Mk1 trainer, but actually a prototype for the aborted naval variant. You can tell by the serial number. KHN-T3001 was one of two before the Navy pulled out.

As far as I can tell there are only two of the trainers -- or, at least, I've only ever seen KHT-2009 and KHT-2010 in pictures. They must have been based on the IOC-1/2 version of the Tejas, hence the lack of AAR probe. The Indians have apparently ordered 10; time will tell if the other 8 are also in IOC configuration or FOC (my money's on the latter, which would explain the delay). First flight for the IOC Tejas Trainer was 2009, when it also received its serial number, but I don't know when the IAF officially "commissioned" them: Tejas got IOC-1 in 2011, but it's wholly possible they were training pilots on the platform beforehand considering its tortuous development.

Anyway, added 496 w/ the IOC-2 build and loadouts + training. IS 2009 barring further info.

**Comment by capcop98** [comment]
Noted with thanks!
