### ISSUE TITLE
Romeo SSB Conversion

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#189]
### DB Selector

DB3K

### Hypothetical

No

### Name

Romeo SSB Conversion

### Class

Romeo SSB

### Country

North Korea

### Service

Navy

### In Commission

2019

### Length (m)

76.6

### Beam (m)

6.7

### Draft (m)

7.5

### Standard Displacement (t)

Unknown

### Submerged Displacement (t)

2000

### Empty Displacement (t)

1615

### Max Depth (m)

270

### Complement

52

### Primary Propulsion Type

Diesel/Electric

### Propulsion

Same as DBID 386

### Flank Speed at Surface (kt)

15

### Flank Speed Submerged (kt)

12

### Range (nm) at Speed (kt)

Less than DBID 386

### Range (nm) on AIP

N/A

### Fuel Capacity (kg)

Less than DBID 386

### Sensors

Same as DBID 386

### Mounts

Torpedoes Same as DBID 386

3x Pukguksong 3/4 SLBM

### Magazines

Same as DBID 386

### Comms/Datalinks

Same as DBID 386

### Comments

Recent North Korean conversion of an existing Romeo SS to an SSB. Conversion includes lengthening the sail to accommodate 3 Pukguksong-3 or Pukguksong-4 SLBM's at the cost of endurance from a reduced battery compartment as hull was not lengthened.

### Sources

http://www.hisutton.com/ROMEO-Mod_Submarine.html
http://www.hisutton.com/Korean-KSS-III-And-ROMEO-Mod-Class-Submarines.html
http://www.hisutton.com/North-Korea-Pukguksong-SLBM.html?fbclid=IwAR2NU-5eLsOY1_pbjzV7NcjLjphJLO5iy_4ow5k8Q1ul2Qer16T1swb90vw
https://www.navalnews.com/naval-news/2020/10/unusual-submarine-likely-to-increase-threat-from-north-korea/?fbclid=IwAR1nEPgptctI_YQ9jh_jZ_KnQuDv7PfA6blmXElj45o-dlEjYE20FGvsgnI
https://www.navalnews.com/naval-news/2021/10/north-korea-fires-possible-pukguksong-ballistic-missile/
https://www.thedrive.com/the-war-zone/29122/north-koreas-new-ballistic-missile-submarine-is-a-refurbished-antique
https://www.thedrive.com/the-war-zone/42803/north-korea-tests-pint-sized-submarine-launched-ballistic-missile

![North-Korea-DPRK-ROMEO-MOD-Submarine-Cutaway-940](https://user-images.githubusercontent.com/99599482/154362387-713df7b8-2e73-4fe7-a858-7931b0fa97b2.jpg)
![North-Korea-DPRK-ROMEO-MOD-Submarine-profile](https://user-images.githubusercontent.com/99599482/154362431-86ce2b61-b35a-4596-83f9-59a79cc0f5d4.jpg)
![DPRK_Romeo-Mod_schem940](https://user-images.githubusercontent.com/99599482/154362461-5a7dc121-2e9f-4bcb-bea5-fb4f2c752b31.jpg)

**Comment by tbrandon517** [comment]
Source Update

**Comment by PygmalionOfCyprus** [comment]
Added 494. Slashed submerged fuel/endurance by ~50% to reflect loss of aft battery compartment. Also swapped out the torpedoes for CHT-02Ds, and applied "Double Hull" property to all Type 033s.
