### ISSUE TITLE
China, HHQ-9A Update

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1890]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3763

### Summary of Changes

General
---
**Name**
HHQ-9 → HHQ-9A
**Target Altitude**
25m to 3000m
**Guidance**
Detalink (TVM)+ ARH (no need to change?)

Sensor
---
ARH only (Should be late 90's tech)
No IR for HHQ-9A

### Sources

Target Altitude
https://www.guancha.cn/military-affairs/2017_05_08_407286.shtml

Guidance
https://www.army-technology.com/projects/hong-qi-9-hq-9-air-defence-missile-system/

**Comment by KC45jp** [comment]
Relate to
#1861 HHQ-9B

**Comment by PygmalionOfCyprus** [comment]
Fixed 496, though did not adjust min altitude as per comment in #1861 (and also glad I checked the source, since I'm pretty sure you meant to write _30,000m_ and not _3,000m_ 😛 ).

**Comment by KC45jp** [comment]
Oh, no. Sry and Thanks.
