### ISSUE TITLE
China, HQ-9A

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1891]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 1225

### Summary of Changes

General
---
**Target Altitude**
25m to 3000m
**Guidance**
Detalink (TVM) + ARH

Sensor
---
Active Radar Horming (As requested in #1890 )

### Sources
Same as HHQ-9A's

Target Altitude
https://www.guancha.cn/military-affairs/2017_05_08_407286.shtml

Guidance
https://www.army-technology.com/projects/hong-qi-9-hq-9-air-defence-missile-system/

**Comment by LuigiP57** [comment]
#1892

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
