### ISSUE TITLE
HQ-9/P, Pakistan, SAM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1892]
### DB Selector

DB3K

### DBID to Copy

Facility 1276

### Hypothetical

No

### Name

HQ-9/P

### Country

Pakistan

### Service

Army, Air Force

### In Commission

2021

### Sources

https://en.wikipedia.org/wiki/HQ-9
https://www.janes.com/defence-news/news-detail/pakistan-army-commissions-hq-9p-air-defence-system

**Comment by PygmalionOfCyprus** [comment]
Weapons are not assigned operator countries; this is a request for an ADS and should be referencing Facilities.

**Comment by LuigiP57** [comment]
> 

Fixed in DBID

**Comment by PygmalionOfCyprus** [comment]
Thanks! 🙂

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
