### ISSUE TITLE
HQ-9BE (FD-2000B), Morocco, SAM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1893]
### DB Selector

DB3K

### DBID to Copy

Facility 3280

### Hypothetical

No

### Name

HQ-9BE (FD-2000B)

### Country

Morocco

### Service

Army

### In Commission

2021

### Sources

https://northafricapost.com/54458-morocco-receives-chinese-anti-aircraft-defense-system-fd-2000b.html

**Comment by PygmalionOfCyprus** [comment]
Weapons are not assigned operator countries; this is a request for an ADS and should be referencing Facilities.

**Comment by PygmalionOfCyprus** [comment]
Weapons are not assigned operator countries; this is a request for an ADS and should be referencing Facilities.

**Comment by LuigiP57** [comment]
> Weapons are not assigned operator countries; this is a request for an ADS and should be referencing Facilities.

Fixed

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
