### ISSUE TITLE
Type 1 Electric Jammer

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1894]
### DB Selector

DB3K

### Baseline

Weapon 1208

### Hypothetical

No

### Name

Type 1 Electric Jammer

### Length (m)

1.2

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

1nm

### Warhead

-

### Targets

Surface Vessel

### Sensors

-

### Comments

Expendable decoy, in service from 1995.
Launched from Mk36 SRBOC
So Loadout for Mk36 SRBOCs of JMSDF's DD,DDH,DDG (after 1995) will be 2x Flare, 2x Chaff, 2x Type 1 Electric Jammer.

### Sources

I got only Japanese Source...
https://dl.ndl.go.jp/view/download/digidepo_1283286_po_TRDI50_05.pdf?contentNo=5&alternativeNo=

**Comment by PygmalionOfCyprus** [comment]
Added 496, created new SRBOC ver., and added to all JP DD/G/H w/ IS >= 1995.
