### ISSUE TITLE
Japan DDG 179 Maya

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1895]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3211

### Summary of Changes

General Data
---
Length:170m
Beam:21m
Draft: 6.2m

Sensor
---
Delete J/OPS-20
Delete J/OPS-28C
Replace SPQ-9 with SPQ-9B (ID 2314) (Cloud you check SPQ-9B has Frequency Agile code? it is difficult to check it by SQL)
Add Mk20 Mod 0 EOSS (Sensor ID 4643)

Mount
---
delete AN/SLQ-25 Nixie, (While Kaijin-sha (a Japanese Magazine publisher I used for reference) reported that we cannot find this decoy launcher) 
MK36 SRBOC Requested as #1894

COMM
---
USC-42 (SATCOM)

Comments
---
This Changes also need to apply to Request #1583 .

### Sources

![Maya class](https://user-images.githubusercontent.com/107294450/181139150-75f5f7e7-3324-4828-ab4b-df2687d3f180.PNG)
Picture from 海人社, 世界の艦船増刊 第192集 精鋭自衛艦のすべて⑦「まや」型護衛艦

Wiki for reference
https://ja.wikipedia.org/wiki/%E3%81%BE%E3%82%84%E5%9E%8B%E8%AD%B7%E8%A1%9B%E8%89%A6

**Comment by PygmalionOfCyprus** [comment]
Handled all 496 except the new dimensions, I think these "clean" numbers have been rounded from the "true, dirty" numbers currently in the DB and reported elsewhere.
