### ISSUE TITLE
Japan, Atago class

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1896]
### DB Selector

DB3K

### Affected DBID(s)

SHIP ID 1748, 1838, 3046

### Summary of Changes

For all Atago class
General
---
Length: 165m
Beam: 21m
Draft: 6.2m

Standard Displacement: 7750 ton

Sensor:
---
Mk46 Mod1 OSS (Sensor ID 4639)

Mount:
---
**Mk41 VLS**
SM-2 blk3B (Weapon 1194)
Mk36 SRBOC requested as https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1894

COMM:
---
Link16
USC-42 (SATCOM)

### Sources

![Atago1](https://user-images.githubusercontent.com/107294450/181154595-0821ca3e-47a9-4aa8-acd5-3dafec6a5ff5.PNG)

![Atago2](https://user-images.githubusercontent.com/107294450/181154654-588a06c7-d9d9-4fed-879e-96ff76e9bca4.PNG)

Link16
https://motor-fan.jp/mf/article/53529/

wiki
https://ja.wikipedia.org/wiki/%E3%81%82%E3%81%9F%E3%81%94%E5%9E%8B%E8%AD%B7%E8%A1%9B%E8%89%A6

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
