### ISSUE TITLE
Japan, AMS 4301 Hiuchi

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1899]
### DB Selector

DB3K

### Baseline

-

### Hypothetical

No

### Name

AMS 4301 Hiuchi

### Country

Japan

### Service

Navy

### In Commission

2002-

### Number in Service

5x

### Length (m)

65

### Beam (m)

12

### Draft (m)

3.5

### Standard Displacement (t)

980

### Full Displacement (t)

1400

### Complement

40

### Primary Propulsion Type

Diesel

### Propulsion

2x 6MG28HX

### Flank Speed (kt)

15

### Range (nm) at Speed (kt)

3000nm at 12kt (Previous class was 2500nm at 12kts, but Hiuchi is bigger))

### Sensors

J/OPS-26　(short range, Surface Search, Navigation, 00's tech)

### Mounts

None (except for water gun)

### Aircraft & Docking Facilities

4x Boats

### Comms/Datalinks

HF/VHF/UHF [Un/Secure]

### Comments

auxiliary ship, utility service

2006 version has...
2x 12.7mm HMG (Right\Left side of Bridge)
Added from AMS-4304 Genkai, but later added to all ships. I could not find any resources when (and while it is not big weapon), I guess we can add them as 2008 ver.

### Sources

https://ja.wikipedia.org/wiki/%E3%81%B2%E3%81%86%E3%81%A1%E5%9E%8B%E5%A4%9A%E7%94%A8%E9%80%94%E6%94%AF%E6%8F%B4%E8%89%A6

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Also added 2020 lo-vis version.
