### ISSUE TITLE
#1748 Aerostat mooring can't host or land aerostats

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#19]
### DB Selector

DB3K

### Affected DBID(s)

Facility 1748

### Description of Problem

#1748 Aerostat mooring can't host or land aerostats Save file attached to this post-http://www.matrixgames.com/forums/fb.asp?m=5066625

### Recommended Fix

Add needed subfacilities

**Comment by PygmalionOfCyprus** [comment]
This is a weird one. It's basically a symptom of how we originally used to handle aerostats.

Long story short, aerostats used to be facilities: we treated them as sensors on top of really, really, really tall masts. (You can still see these: Facility 1043, 1181, 2302/3, etc.) The "Aerostat Mooring" facility was intended as a generic aerostat that people could add their own sensors to. It has a Mast Height of 4500m, an aerostat line, etc. -- just like the other aerostats-as-facilities. It's not really supposed to be used as a "dock," though the name could make that clearer.

At some point we switched to handling them as "static" aircraft, which makes a lot more sense. They don't really land, or moor, or anything though. At some point we'll improve how they're handled...

Anyway, not really a DB issue so much as a weird bit of history. I will change the name to "Generic Aerostat" so it's less confusing though.

**Comment by bostonmyk** [comment]
I know. I was one of the founding 4...

**Comment by PygmalionOfCyprus** [comment]
Was commenting for the benefit of those not aware. ;)
