### ISSUE TITLE
Add Hypothetical Lightweight Battleship (BBL)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#190]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

Hypothetical Lightweight Battleship (BBL)

### Class

Lightweight Battleship (BBL)

### Country

United States

### Service

Navy

### In Commission

1989

### Length (m)

121.92

### Beam (m)

25.6

### Draft (m)

6.7

### Standard Displacement (t)

~ 9000 tons

### Full Displacement (t)

Undetermined

### Empty Displacement (t)

undetermined

### Complement

320

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

4x Diesels

### Fuel Capacity (kg)

undetermine

### Flank Speed (kt)

25 kts

### Range (nm) at Speed (kt)

undetermined

### Sensors

Most sensors aren't mentioned but possibly NTU set-up for SM-1/2.

### Mounts

1 16 "/ 50 triple turret with 270 degrees of train.
Three to five 5 inch Mk 45 guns, some possibly replaced by 8 inch MK 71 guns or brackets for 155 mm/50 vertical guns that fire standard Army/Marine 155 mm. (Based on concept image 3-4x 127mm mounts 1 each side of superstructure 1-2 at aft deck house behind mk26)
Two Mk 26 launchers for Standard Missiles/ASROC (fore and aft)
Two Phalanx CIWS.

### Aircraft & Docking Facilities

Virgina CGN style elevator/hangar space for two helicopters.

### Comms/Datalinks

Similar to Modernized Iowa

### Ship Codes

Nuclear Shock Resistant, Degaussed Steel Hull, Prairie Masker, Helo In-Flight Refuel (HIFR) Capable

### Comments

In November 1982, as the Iowa-class reactivation had just begun and elaborate Phase II conversions still seemed possible, a naval architect named Gene Anderson wrote proposed a class of ′′ light battleships ′′ built around the four turrets that would be removed from Iowas in the process of Phase II.

The proposed design
~ 9000 tons
400 feet long
84 feet beam
22 feet draught
The shape of the hull is heavily inspired by contemporary merchant ships (cruising bow above water and bulbous underwater prow)
protection consisting of an unspecified armored deck and box around the machinery and command/control spaces, torpedo blisters, and a triple bottom.
Propulsion would be 4 to 6 diesel engines. Speed of up to 25 knots to escort 20 knots amphibs.
Armament as described:
1 16 "/ 50 triple turret with 270 degrees of train.
Three to five 5 inch Mk 45 guns, some possibly replaced by 8 inch MK 71 guns or brackets for 155 mm/50 vertical guns that fire standard Army/Marine 155 mm.
Two Mk 26 launchers for Standard Missiles/ASROC
Two Phalanx CIWS.
Most sensors aren't mentioned but possibly NTU set-up for SM-1/2.
Virgina CGN style elevator/hangar space for two helicopters.
Crewis estimated at 320.
This ' lightweight battleship ' (BBL) as suggested by naval architect Gene Anderson was essentially an ocean-capable monitor that would double the number of artillery support warships available for the cost of ~ four frigates, which could be used to show the flag in peacetime and to support amphibious missions in war time.

### Sources

https://www.facebook.com/groups/946315158890663/permalink/1667107696811402/
![155378-a9f1a5e259757b15b072400c4f0a88be](https://user-images.githubusercontent.com/99599482/154363695-fa600bf0-a0ef-4202-b5dc-64f769f70562.png)

**Comment by tbrandon517** [comment]
Updated mount info.

**Comment by KushanGaming** [comment]
Done for DB495.

**Comment by tbrandon517** [comment]
That's awesome 👌
