### ISSUE TITLE
Australia - HIMARS

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1906]
### DB Selector

DB3K

### DBID to Copy

facility/3268/

### Hypothetical

No

### Name

Arty Plt (HIMARS) (3x pr Bty)

### Country

Australia

### Service

Army

### In Commission

2024

### Number in Service

30x Launchers

### Sensors

None

### Mounts

No Changes

### Loadout Options

The approved package consists of: 

30x M30A2 Guided Multiple Launch Rocket Systems.
30x Alternative Warhead (AW) Pods with Insensitive Munitions Propulsion System.
30x M31A2 GMLRS Unitary (GMLRS-U) High Explosive Pods with IMPS.
30x XM403 Extended Range (ER)-GMLRS AW Pods.
30x EM404 ER GMLRS Unitary Pods.
10x M57 Army Tactical Missile System (ATACMS)

Australia is a partner for PrSM and is expected to deploy PrSM from their launchers.

### Other Changes

N/A

### Sources

https://www.overtdefense.com/2022/05/27/australia-fast-tracks-himars-buy/
https://www.asiapacificdefensejournal.com/2022/05/australia-gets-us-approval-to-purchase.html?fbclid=IwAR2d7iYWb-rs2M3j9UMZBFgowtJUkQb5j7OR81yELyMGM7hhta_TwwKC29Y
https://www.asianmilitaryreview.com/2022/06/australia-signals-himars-interest/
https://www.reuters.com/world/us-oks-potential-sale-himars-launchers-australia-pentagon-says-2022-05-26/
https://www.australiandefence.com.au/defence/land/army-selects-himars
https://adbr.com.au/australia-approved-to-buy-himars-long-range-fires/
https://www.janes.com/defence-news/news-detail/australian-army-makes-himars-procurement-bid
https://defbrief.com/2021/08/12/australia-joins-us-armys-precision-strike-missile-program/
https://www.navalnews.com/naval-news/2021/09/australia-to-procure-tomahawk-and-hypersonic-missiles/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
