### ISSUE TITLE
Australia - MQ-4C Triton UAV [Global Hawk Mod]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1907]
### DB Selector

DB3K

### DBID to Copy

aircraft/2846/

### Hypothetical

No

### Name

MQ-4C Triton UAV [Global Hawk Mod]

### Country

Australia

### Service

Air Force

### In Commission

IOC 2023, full delivery by 2025

### Number in Service

6x, Option for 7x

### Sensors

No Change Indicated

### Mounts

No Change Indicated

### Loadout Options

No Change Indicated

### Other Changes

No Change Indicated

### Sources

https://en.wikipedia.org/wiki/Northrop_Grumman_MQ-4C_Triton#Operators
https://www.thedrive.com/the-war-zone/21779/australia-seals-deal-to-buy-mq-4c-drones-as-military-competition-in-the-pacific-heats-up
https://www.northropgrumman.com/what-we-do/air/triton/
https://news.northropgrumman.com/news/releases/australias-first-mq-4c-triton-takes-shape
https://www.airforce.gov.au/technology/aircraft/intelligence-surveillance-and-reconnaissance/mq-4c-triton-unmanned-aircraft
https://www.defenseworld.net/news/31018/Australia___s_first_MQ_4C_Triton_Drone_Completes_Production_Milestone#.YhY5_YrMLrc

![image](https://user-images.githubusercontent.com/99599482/181267493-268a1012-54ed-470b-b8c8-1ba91560a718.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
