### ISSUE TITLE
Austrailia - M1A2 SEPv3

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1908]
### DB Selector

DB3K

### DBID to Copy

US M1A2 SEPv3

### Hypothetical

No

### Name

M1A2 SEPv3

### Country

Australia

### Service

Army

### In Commission

Deliveries from 2025, IOC 2025

### Number in Service

75x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Includes Trophy APS

### Sources

https://www.thedrive.com/the-war-zone/43820/australia-buys-m1a2-sepv3-advanced-abrams-tanks-to-lead-its-major-armor-upgrade?fbclid=IwAR3k3Y0LylpRqbjlEw1n5BNM8GExbaJthxou3em6e8Lud7OHVowsco8NObA
https://www.overtdefense.com/2022/01/14/australia-signs-for-75-m1a2-sepv3-abrams-main-battle-tanks/
https://militaryleak.com/2022/01/11/australian-government-confirms-order-for-m1a2-sepv3-abrams-and-tank-supporting-systems/

![image](https://user-images.githubusercontent.com/99599482/181270127-04ad977f-b965-468b-9471-4bfb84293e30.png)

**Comment by PygmalionOfCyprus** [comment]
Technically I'm not doing GU requests at the moment, but I added this one to 496 'cause we already have the M1A2 SEPv3 built for USA and it was easy to copy.
