### ISSUE TITLE
RCAF CH-146 Griffon Escort Loadout

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#191]
### DB Selector

DB3K

### User(s)

#4610

### Weapons Carried

- 1x M134D "Minigun" (port side)
- 2x (1 each side) Generic Chaff/Flare Dispenser) 30 Catridges? See pic

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

170

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

- please add an Escort loadout with 2xM134 miniguns only

### Sources

http://www.rcaf-arc.forces.gc.ca/en/aircraft-current/ch-146.page
https://en.wikipedia.org/wiki/Bell_CH-146_Griffon#Afghanistan
www.forfreedom.ca/?p=1364

![ch-146_griffon_060_of_115](https://user-images.githubusercontent.com/99632305/155216850-6e0fc258-ffe1-475a-be96-aad9a1848b51.jpg)

![ch-146_griffon_044_of_115t](https://user-images.githubusercontent.com/99632305/155217213-4e9f869d-a875-4e94-a371-25d515b7c33a.jpg)

![688684](https://user-images.githubusercontent.com/99632305/154365196-6f0d4110-0930-4be0-b482-bf43cb5503a9.jpg)
https://en.wikipedia.org/wiki/Bell_CH-146_Griffon#Afghanistan

**Comment by PygmalionOfCyprus** [comment]
Added 494. Tweaked the chaff dispenser to be 2x AN/ALE-47s w/ 30 flares each.
