### ISSUE TITLE
Pasars-16 SAM/AAA for Serbia

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#1910]
### DB Selector

DB3K

### Hypothetical

No

### Name

Pasars-16

### Facility Type

SAM

### Country

Serbia

### Service

Army

### In Commission

2018

### Number in Service

18

### Crew

3

### Dispersion Radius (m)

Unsure

### Sensors

.

### Mounts

6x Pasars SAM

### Comments

40mm L/70 Bofors with 3P ammunition mounted on a truck chassis. Each pasars battery can be integrated with a giraffe radar.

Pasars can carry:
4x Strela-2M
4x Mistral 3 
4x Igla 
2x RLN/IC Missiles (modified K-13 for all aspect and 12km range) 
2x 9M37M w/ booster motor (10km range)

### Sources

https://www.mod.gov.rs/eng/16367/modernizovani-pasars-znacajno-jaca-protivvazduhoplovnu-odbranu-16367

https://en.m.wikipedia.org/wiki/PASARS-16

https://militaryleak.com/2021/12/30/serbian-army-to-receive-pasars-16-spaag-armed-with-mistral-3-manpad/?amp

https://tangosix.rs/2021/28/10/partner-2021-novi-i-unapredjeni-pvo-sistemi/

![images - 2022-07-28T011443 865](https://user-images.githubusercontent.com/99824301/181285378-e6c8bbfd-86d3-4b4b-8a0e-410238c148cd.jpeg)
![PASARS_16_-_VS_-_04](https://user-images.githubusercontent.com/99824301/181285397-f00ab3b2-53cb-43ee-8201-096e46c98af6.jpg)

**Comment by bostonmyk** [comment]
Gun mechanically is licensed copy of L70 #2574
https://twitter.com/AndreiBtvt/status/1313606144309559296
https://militaryleak.com/2020/06/14/serbia-tests-pasars-40mm-self-propelled-anti-aircraft-gun/
https://www.janes.com/defence-news/serbia-test-fires-indigenous-pre-fragmented-ammunition-from-pasars-spaag/

**Comment by nuk92** [comment]
Honestly I would go for the weapons that are currently available first, like the Mistral-3 before adding RNL-IC or the extended range Strela-10 missile. They can allways be added later on.

**Comment by TTZ32** [comment]
Closed as this has been added
