### ISSUE TITLE
C-17 Rapid Dragon Loadout Addition

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1911]
### DB Selector

DB3K

### User(s)

5468

### Weapons Carried

5 x 3916 (AGM-158B x 9)
5 x 3917 (AGM-158C x 9)

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Might suggest any number of pallets from 1 to 5 loaded on the C-17, which is what the source appears to suggest.
Hopefully the other issues I reported in tech support with the Rapid Dragon loadout get fixed too.

### Sources

https://www.popularmechanics.com/military/weapons/a38584553/air-force-turns-cargo-plane-into-bomber/

**Comment by PygmalionOfCyprus** [comment]
Updated extant loadouts in 497.
