### ISSUE TITLE
Request to add new external 1RL-123E "Istra-E" AESA target acquisition radar (Used with Pantsir)

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#1916]
### DB Selector

DB3K

### Baseline

3131

### Hypothetical

Yes

### Name

1RL-123E (Istra-E)

### Sensor Generation

Late 2010s

### Range (nm)

135

### Sensor Capabilities

Air Search, Range Information, Altitude Information, Speed Information, Heading Information, 3D, AESA

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Active Electronically Scanned Array (AESA)

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm

### Lower Frequency (Hz)

2,000,000,000

### Upper Frequency (Hz)

3,000,000,000

### Scan Interval (s)

3 to 6 per minute (~every 10 seconds)

### Target Altitude (ft)

16ft AGL - 98,000ft ASL (0.005-30km)

### Comments

3D L-band AESA acquisition radar meant for Pantsir-SM/S2/S1/S and potentially Tor, designed to cue fire control radar for longer range tracks and engagement for low-RCS targets. Seen deployed in Sevastapol, known to exist, visually confirmed to exist. No visual proof it has been fielded/widely used however. 

VNIIRT catalog describes it as an L-band AESA with 350km max search range, but also says 250km max tracking range (need translator please!)
![1RL-123E radar spec sheet new](https://user-images.githubusercontent.com/108960393/181694098-7629360f-0f0f-439e-a30f-8cd13d0d8d8f.jpg)
130km range for 1m2 target >1.5km altitude
110km for 0.5m2 target >1km  altitude
71km for 0.1m2 target > 0.5km  altitude
54km for 0.03m2 target > 0.3km  altitude
40km for 0.01m2 target > 0.2km  altitude

Spec chart from expo shows 250km max range, 130km for 1m2 target, 71km for 0.1m2 target
![1rL-123E specs](https://user-images.githubusercontent.com/108960393/181426606-3f296e5e-8fb3-477d-913c-32bed88eed9f.jpg)

details from this export catalog match specs shown on this site, max range 200km and 130km for a 1m2 target https://thaimilitaryandasianregion.wordpress.com/2015/10/30/pantsir-s1/
![1rL-123E specs 2](https://user-images.githubusercontent.com/108960393/181429356-55494160-a8da-49f4-971f-23822e51ac53.png) 
according to above source
Max range: 200km (108nm)
Altitude: 0.005km - 30km (16ft AGL-98,000ft ASL) 
Radar band: L (2-3 Ghz)
Suppression of clutter reflections: 50-55 dB
Max targets: 150
Rotation Azimuth: 360 degrees
Accuracy: 20-50meters / 0.42°
Beamwidth:  β= 4° ;ε= 5.5°
radar beam resolutions technically accurate enough for midcourse guidance/accurate enough for cueing FCR radar of Pantsir

Range values for VLO targets:
0.001m2 target: 23km/12nm
0.0001m2 target: 13km/7nm

![1rL-123E](https://user-images.githubusercontent.com/108960393/181430482-2af091e1-8d90-4321-b5e1-cde9f3e8eba7.jpg)

deployed in Sevastopol 
![Eg0JhVQXkAAGDuu](https://user-images.githubusercontent.com/108960393/181692977-e4132f50-b6bc-4fea-808c-9c8969bde300.jpg)

CORRECTION:
after analyzing the more detailed spec sheet, it seems
Max search range: 350km for larger air targets
Max tracking range: 250km for fighter jets

### Sources

https://thaimilitaryandasianregion.wordpress.com/2015/10/30/pantsir-s1/

https://commons.wikimedia.org/wiki/File:MSh-12_Svetlitsa_-_InnovationDay2013part1-08.jpg

https://www.radartutorial.eu/19.kartei/02.surv/karte076.en.html

https://twitter.com/halmiso1/status/1300706452131246080

https://twitter.com/pir34/status/1283006380589428736

**Comment by TheBagelInhaler** [comment]
I made a request before but it had outdated/incorrect specs/info. So did a new one here with accurate info.

**Comment by Huib18** [comment]
Quoted source( see below), is incorrect. No visual conformation of use in Russia or in Syria. Would be hypothetical radar.

So far only in service with Russia. Seen deployed in Syria's Hmeimim Airbase https://informnapalm.org/en/russian-propagandists-disclose-air-defense-positions-at-khmeimim-air-base/

**Comment by TheBagelInhaler** [comment]
> Quoted source( see below), is incorrect. No visual conformation of use in Russia or in Syria. Would be hypothetical radar.
> 
> So far only in service with Russia. Seen deployed in Syria's Hmeimim Airbase https://informnapalm.org/en/russian-propagandists-disclose-air-defense-positions-at-khmeimim-air-base/

good catch. I'll edit the link out and rename to hypothetical. thanks!
I wonder if it is actually in service though? And not just a new radar that was made in limited number by a company hoping military or foreign countries would buy it?

**Comment by TheBagelInhaler** [comment]
If anyone wants to translate this detailed spec sheet I would greatly appreciate it. Would greatly help explain the radar. Thank you!
![1RL-123E radar spec sheet new](https://user-images.githubusercontent.com/108960393/181694773-9e71ce5c-6a5e-4303-9547-7c4f299f5de9.jpg)

**Comment by TheBagelInhaler** [comment]
After reading a the VNIRT spec sheet, it seems the radar has a maximum probably unambiguous range of 350km (189nm) for large air targets. But 250km is the maximum tracking range for fighter jet size targets.
