### ISSUE TITLE
China, Type 056, Coast Guard Version

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1920]
### DB Selector

DB3K

### DBID to Copy

SHIP 2295

### Hypothetical

No

### Name

Type 056 Jiangdao

### Country

China

### Service

Coast Guard

### In Commission

2021?

### Sensors

Possibly removed Hull sonar, while they removed Torpedo launchers

### Mounts

Delete
324mm Triple
HQ-10
YJ-83
and likely Type 946 because only few coast Guard ships have those self-defense system.

### Loadout Options

-

### Sources

https://www.navalnews.com/naval-news/2021/12/china-transferring-navy-type-056-corvettes-to-the-coast-guard/

**Comment by tbrandon517** [comment]
Duplicate of #1664 already completed

**Comment by KC45jp** [comment]
Ooops... thanks

**Comment by tbrandon517** [comment]
> Ooops... thanks

No worries!
