### ISSUE TITLE
Kazakhstan - Elbit Skylark I-LEX UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1923]
### DB Selector

DB3K

### DBID to Copy

Skylark 3

### Hypothetical

No

### Name

Elbit Skylark I-LEX

### Country

Kazakhstan 

### Service

Air Force

### In Commission

2014-Present

### Number in Service

uncertain, local production in Kazakhstan

### Sensors

Eo/IR Turret

### Mounts

None

### Loadout Options

Ferry
Internal Recon

### Other Changes

Slightly smaller than Skylark 3.

Type: Mini Unmanned Aerial System
Take-off Weight: 7.5 kg (17 lb)
Payload Weight: 1.2 kg (2.6 lb)
Service Ceiling: 4,600 m (15,000 ft)
Range: 40 km (25 mi)
Endurance: 3 hours

### Sources

https://www.oryxspioenkop.com/2022/01/guardians-of-steppe-kazakhstans-uavs.html?fbclid=IwAR1ctuZqKiPd2A3kLdkb03ChxfKL_9qxVnoBx155woCFY_A4Q4VkQJnieMg
https://en.wikipedia.org/wiki/Elbit_Skylark#Skylark_I_2
https://elbitsystems.com/products/uas/skylark-i-lex/
https://elbitsystems.com/uas-skylark-i-lex-mini-uas/

![image](https://user-images.githubusercontent.com/99599482/181575450-5d468f1c-14e2-4901-9aa4-ccfa4f96da28.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
