### ISSUE TITLE
India - P XXX Mahe, Anti-Submarine Warfare Shallow Water Craft (ASW-SWC)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1924]
### DB Selector

DB3K

### Hypothetical

No

### Name

P XXX Mahe

### Class

Anti-Submarine Warfare Shallow Water Craft (ASW-SWC)

### Country

India

### Service

Navy

### In Commission

2022-

### Number in Service

16x Planned, 9x Under Construction

### Length (m)

74m (CSL), 77.6m (GRSE)

### Beam (m)

10.5m (Both Models)

### Draft (m)

2.7m (Both Models)

### Standard Displacement (t)

700 tons (CSL), 750 tons (GRSE)

### Full Displacement (t)

not stated

### Empty Displacement (t)

not stated

### Complement

57 (7 officers + 50 sailors)

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

3x Water-jet propulsion

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

1,800 nautical miles at 14 knots

### Sensors

Nav Radar
SS Radar
Hull-Mounted Sonar
Low Frequency Variable Depth Sonar (LFVDS)

### Mounts

Anti-Submarine Warfare:
1x RBU-6000 anti-submarine rocket launcher
2x Triple Lightweight ASW Torpedo (presumably the Advanced Light Weight Torpedo (ALWT)
Mine-laying rails for ASW and ASuW mines

Guns:
1x CRN-91 30mm naval gun
2 x OFT 12.7 mm M2 Stabilized Remote Controlled Gun

### Aircraft & Docking Facilities

N/A

### Comms/Datalinks

Datalinks to Coordinate between ASW aircraft and surface vessels

### Ship Codes

Advanced Quieting

### Comments

The Indian Navy’s (IN) Anti-Submarine Warfare Shallow Water Craft (ASWSWC) project of 16 hulls will be split evenly between two shipbuilders, Cochin Shipyard Limited (CSL) and Garden Reach Shipbuilders & Engineers (GRSE).

Each shipyard will build its own variant of a 700t waterjet-powered ASW corvette working to common IN-issued specifications. The ASWSWC is intended for coastal ASW missions, minelaying and maritime security operations within 200nm of the coastline.

### Sources

https://en.wikipedia.org/wiki/Anti-Submarine_Warfare_Shallow_Water_Craft_(ASW-SWC)_corvette#:~:text=The%20Anti%2DSubmarine%20Warfare%20Shallow,Shipbuilders%20%26%20Engineers%20(GRSE).
https://www.shephardmedia.com/news/naval-warfare/details-grses-small-anti-submarine-corvette-emerge/
https://eurasiantimes.com/touted-as-game-changer-what-are-indian-navys-anti-submarine-warfare-shallow-water-crafts/
https://www.naval-technology.com/projects/anti-submarine-warfare-shallow-water-craft-asw-swc/
https://www.navalnews.com/naval-news/2021/12/first-steel-cutting-for-indias-4th-and-5th-asw-shallow-water-crafts/
https://www.globalsecurity.org/military/world/india/asw-swc.htm
https://diligentias.com/anti-submarine-warfare-shallow-water-crafts-2/
https://www.navyrecognition.com/index.php/news/defence-news/2019/may/7037-india-to-acquire-8-new-asw-shallow-water-vessels.html
https://www.militaryperiscope.com/weapons/ships/small-combatants/mahe-class-asw-shallow-water-craft-aswswc

CSL Variant
![image](https://user-images.githubusercontent.com/99599482/181606023-b5953fc0-a2d3-4ec9-8ad7-17914d182e10.png)
![image](https://user-images.githubusercontent.com/99599482/181606149-fcc1b813-fb0a-44e0-b511-37201e5b386f.png)

GRSE
![image](https://user-images.githubusercontent.com/99599482/181606262-e9ea7e51-26b5-4e56-b71e-2d074ebfaf49.png)

**Comment by tbrandon517** [comment]
1st GRSE ship P68 Arnala launched.

https://navyrecognition.com/index.php/naval-news/naval-news-archive/2022/december/12633-india-launches-first-arnala-class-asw-shallow-water-craft-corvette.html

**Comment by tbrandon517** [comment]
Image of INS Arnala at launch.

https://www.sunyaias.com/blogs/ins-arnala

**Comment by tbrandon517** [comment]
Program update

https://www.navalnews.com/naval-news/2023/06/indias-asw-shallow-water-craft-project-progresses-amidst-uncertainties/

**Comment by Jkryos** [comment]
Added DB3K 504.

**Comment by tbrandon517** [comment]
@Jkryos 

Mahe class type from CSL are starting to be launched. Armaments appear to match the GRSE Arnala Class

https://www.armyrecognition.com/news/navy-news/2024/indian-navy-launches-malpe-and-mulki-new-anti-submarine-warfare-ships-from-cochin-shipyard?fbclid=IwY2xjawGkNm1leHRuA2FlbQIxMQABHaOhkHR7pX3_3vstDP6oApIbfRwK7qZp2fkxjB7pwcYsdp_06dzyRXM6Gg_aem_955uxWP5zZlyk9Fs6fnTXw

**Comment by tbrandon517** [comment]
> [@Jkryos](https://github.com/Jkryos)
> 
> Mahe class type from CSL are starting to be launched. Armaments appear to match the GRSE Arnala Class
> 
> https://www.armyrecognition.com/news/navy-news/2024/indian-navy-launches-malpe-and-mulki-new-anti-submarine-warfare-ships-from-cochin-shipyard?fbclid=IwY2xjawGkNm1leHRuA2FlbQIxMQABHaOhkHR7pX3_3vstDP6oApIbfRwK7qZp2fkxjB7pwcYsdp_06dzyRXM6Gg_aem_955uxWP5zZlyk9Fs6fnTXw

@PygmalionOfCyprus 

Mahe variant delivered. Armament is supposed to be the same so not sure if a separate entry is needed, more information needed on performance to determine if differences are significant and more than just aesthetic of the two builders designs. Sensors seem to the the same too.

https://www.armyrecognition.com/news/navy-news/2025/indian-navy-receives-anti-submarine-corvette-ins-mahe-to-strengthen-coastal-defense?fbclid=IwdGRzaAN4I-xjbGNrA3gj5GV4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHmp6d9iZO0gFfnacVOdis_PCH5MrGuQTGvXC6cfHES2G5Ill99cpLrgCa_06_aem_vfFSRg3OINfyOZvgQsUe6Q

**Comment by bostonmyk** [comment]
Mahe launched. Hull number is P80 and its the ASW-SWC class

Deck gun ins 12.7mm Elbit EO/IR turret
Sonar is Hull + Small MF VDS

https://x.com/NewsIADN/status/1992880582997708808
https://x.com/PIB_India/status/1992564825776586814/photo/2
