### ISSUE TITLE
P102 Karaduwa - Nigera

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1925]
### DB Selector

DB3K

### Baseline

Andoni (Modified Town) class, Nigeria Request #386

### Hypothetical

No

### Name

P102 Karaduwa

### Class

Andoni (Modified Town)

### Country

Nigeria

### Service

Navy

### In Commission

2016-Present

### Number in Service

1x

### Length (m)

40m

### Beam (m)

6.1m

### Draft (m)

1.4m

### Standard Displacement (t)

110

### Full Displacement (t)

150

### Empty Displacement (t)

not stated

### Complement

25

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar C32 diesels, 2 shaft

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

39 kts

### Range (nm) at Speed (kt)

Not Stated

### Sensors

1x Furuno I-band Navigation radar

### Mounts

1x 30 mm RWS
2x 12.7 mm HMG
2x 40 mm grenade launchers

### Aircraft & Docking Facilities

1x small crane for small RHIB at the aft.

### Comms/Datalinks

VHF/UHF

### Comments

Larger and improved version of NNS Andoni P-100 Request #386

### Sources

https://en.wikipedia.org/wiki/NNS_Karaduwa_(P102)
https://www.military.africa/2017/12/nns-karaduwa-p102-made-in-nigeria-warship-nigerian-navys-pride-and-joy/
https://newsnaira.net/91811/nns-karaduwa-second-largest-indigenously-built-gun-boat/2
https://www.nairaland.com/5877937/construction-nns-karaduwa-p102-nigerias

![image](https://user-images.githubusercontent.com/99599482/181610287-6feaad13-2b4a-4cf3-8051-03cf9b2824ca.png)
![image](https://user-images.githubusercontent.com/99599482/181610321-e5b127cd-a010-41a0-9047-1cde8c7423d7.png)

**Comment by Jkryos** [comment]
Added DB3K 501.
