### ISSUE TITLE
Japan, F-35A/B, AIM-120C-8(D) loadout

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1930]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4223, 5134

### Summary of Changes

Japan got considerable amount of AIM-120C-7 and C-8 which is D.

We can have both AIM-120C-7 and D(C-8) loadout for Japanese F-35.

### Sources

https://www.dsca.mil/press-media/major-arms-sales/japan-aim-120c-78-advanced-medium-range-air-air-missiles-amraams

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
