### ISSUE TITLE
SAM-4 Chu-SAM

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1934]
### DB Selector

DB3K

### Affected DBID(s)

Facility 867

### Summary of Changes

Sensor
---
Chu-SAM FCR 
 -Has both Pulse Doppler and AESA code. only need AESA
 -Max Air Track Number = 100
 -Max illumination = 12

Magazine
----
Truck with 6x Chu-SAM Missile *3

### Sources

Max Track Number
https://thediplomat.com/2015/11/100-percent-of-targets-destroyed-japan-is-testing-new-missile-in-us/

**Comment by PygmalionOfCyprus** [comment]
Handled 496. The dual Pulse Doppler / AESA flags are actually intentional and required by the DB; the PD flags grant clutter discrimination and LDSD capability. Bit of a quirk.
