### ISSUE TITLE
SAM-4 Chu-SAM Kai [Type 03 Kai/Mod], Missle

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1935]
### DB Selector

DB3K

### DBID to Copy

Weapon 1257

### Hypothetical

No

### Name

SAM-4 Chu-SAM Kai [Type 03 Kai/Mod]

### Country

-

### Service

-

### Other Changes

General
---
Length:4.9m
Diameter:0.28m
Weight:460Kg

### Sources

Defence of Japan, 2018 (Japanese ver)
http://www.clearing.mod.go.jp/hakusho_data/2018/html/ns011000.html

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
