### ISSUE TITLE
SAM-4 Chu-SAM Kai [Type 03 Kai/Mod]

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1936]
### DB Selector

DB3K

### DBID to Copy

Ground 867

### Hypothetical

No

### Name

SAM-4 Chu-SAM Kai [Type 03 Kai] 

### Country

Japan

### Service

Army

### In Commission

2019?

### Sensors

Add
Chu SAM Kai-FTR
Radar, Short Range, For detecting skimming cruise missiles.

### Mounts

[SAM-4 Chu-SAM Kai [Type 03 Kai] ](https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1935)

### Loadout Options

N/A

### Sources

Chu SAM Kai-FTR  (Page 10)
https://warp.da.ndl.go.jp/info:ndljp/pid/11623291/www.mod.go.jp/j/approach/agenda/meeting/materials/bouei_gijutsu/sonota/pdf/sonota_02_a.pdf

https://twitter.com/chageimgur/status/1210869956268552199/photo/1

NEWS
https://thediplomat.com/2015/11/100-percent-of-targets-destroyed-japan-is-testing-new-missile-in-us/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
