### ISSUE TITLE
J/OPY-2 VSR

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1937]
### DB Selector

DB3K

### Affected DBID(s)

6264

### Summary of Changes

Capability
---
Surface Search

Code
---
Periscope Search Advanced
SAR (OPS-48 derived from HPS-106 with SAR)

OPY-2 integrated both OPY-1 Air search and OPS-48 Surface search radar for make it smaller and cheaper.
I believe NO OTH capability available for OPY-2.

### Sources

![opy2](https://user-images.githubusercontent.com/107294450/181855141-e3fa8c78-8669-4795-9eb5-32ca9bfd6e36.PNG)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
