### ISSUE TITLE
SAR code for following Radars + fixed for some codes when I requested.

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1938]
### DB Selector

DB3K

### Affected DBID(s)

4978

### Summary of Changes

J/HPS-106 - add SAR instead of Classification [Class Info] / Brilliant Weapon [Automatic Target Aquisition] (classification code is too OP). 
J/HPS-105B - add SAR instead of NCTR-NBIST
HPQ-101B/C - delete ISAR(= NCTR-NBILST) capability SAR is enough　(Requested incorrectly)
OPS-48 requested in https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1586 (HPS-106, the original version have it the this hould have it, too)

I actually misunderstood about the ISAR and NCTR capability in CMO. I did not know NCTR is only for Air contacts in this game, and believed NVTR and ISAR is same but actually not. I am sorry about it. + I guess CMO did not distinguish SAR and ISAR capability, thus I requested all of them as SAR.

### Sources

HPS-106
https://ja.wikipedia.org/wiki/P-1_(%E5%93%A8%E6%88%92%E6%A9%9F)#%E3%82%A2%E3%83%93%E3%82%AA%E3%83%8B%E3%82%AF%E3%82%B9

HPS-105B
https://ja.wikipedia.org/wiki/SH-60K_(%E8%88%AA%E7%A9%BA%E6%A9%9F)#%E3%82%BB%E3%83%B3%E3%82%B5

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
