### ISSUE TITLE
Japan EC-2... Not exist?

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1939]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5794

### Summary of Changes

EC-2 does not exist for now. I believe this unit should put in Hypothetical Section as placeholder.
Japan-MoD budgeted to develop stand-off electronic warfare aircraft in 2022.
This is the aircraft that will be EC-2, I guess... No info for now.

### Sources

Page 8
https://www.mod.go.jp/en/d_act/d_budget/pdf/220330a.pdf

**Comment by PygmalionOfCyprus** [comment]
Marked hypothetical for now. I believe this was added during a news roundup in response to [this article](https://www.janes.com/defence-news/news-detail/japan-to-use-c-2-airlifter-for-stand-off-ew-aircraft).
