### ISSUE TITLE
Airbus A.330-200 MRTT, cargo loadouts, properties

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#194]
### DB Selector

DB3K

### Affected DBID(s)

Airbus A.330-200 MRTT

### Summary of Changes

Airbus A.330-200 MRTT, primarily a Tanker, also have a dual transport capacity. In the DB3K_492, that ability is missing, but for the RAF's Voyager KC.2 and Voyager KC.3.
While other platforms could be used as a placeholder, it prevents scen designers and players to benefit from that specific platforms' flexibility. 

RAF's Voyager KC.2 and Voyager KC.3 could also benefit from a few more loadouts to give their capabilities some more granularity.

---
- [ ] Please add the following weapons :

- #2189 'Cargo [No Drop, 45 tons]'
- #2589 'Cargo [No Drop, 20 tons]'
- #2612 'Cargo [No Drop, 10 tons]'
- #2624 'Passenger'

To these platforms :

- #1827 - Airbus A.330-200 MRTT [KC-30A] (Australia - 2012)
- #2935 - Airbus A.330-200 MRTT (Saudi Arabia - 2013)
- #3888 - Airbus A.330-200 MRTT [Phenix] (France - 2018)
- #4513 - Airbus A.330-200 MRTT (South Korea - 2019)
- #4605 - Airbus A.330-200 MRTT (UAE - 2014)
- #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)
- #4861 - Airbus A.330-200 MRTT [Phoenix] (Singapore - 2018)
- #5084 - Airbus A.330-200 MRTT (Turkey - 2021)
- #5181 - Airbus A.330-200 MRTT (Canada - 2029)
- #5251 - Airbus A.330-200 MRTT (India - 2022)

 

- [ ] Please add the following weapons :
- #2189 'Cargo [No Drop, 45 tons]'
- #2589 'Cargo [No Drop, 20 tons]'

To  :
- #1850 - Voyager KC.2 [Airbus A.330-200 MRTT] (United Kingdom - 2012)
- #4276 - Voyager KC.3 [Airbus A.330-200 MRTT] (United Kingdom - 2014)

- [ ] Please create the following loadouts, then assign them to the platforms mentioned above, including #1850 and #4276 :

I would suggest for each :
- MissionProfile = #8001 'Transport, one-way distance. Cruise at optimum altitude and speed. No form-up time. 10% reserves.'
- Role = #7201 'Cargo Transport'
- TimeOfDay = #2001 'Day and night'
- Weather = 2001 'All-weather'

_"Cargo, 10 tons"_
- Weapons Carried : 
- #2189 'Cargo [No Drop, 45 tons]' x 1
- Default Combat Radius (nm) : 7500

"Cargo, 20 tons"
- Weapons Carried : #2189 'Cargo [No Drop, 45 tons]' x 1
- Default Combat Radius (nm) : 6500

"Cargo, 45 tons"
- Weapons Carried :  #2189 'Cargo [No Drop, 45 tons]' x 1
- Default Combat Radius (nm) : 3800

_"Troops"_
- Weapons Carried : #2624 'Passenger' x 300
- Default Combat Radius (nm) : 4500

"Deployment" (mixed Tanker / Cargo / Transport)
- Weapons Carried : #2224 'Cargo [No Drop, 12 tons]' x 1 and #2624 'Passenger' x 50
- Default Combat Radius (nm) : 2800

- [ ] Nota : the Korean MRTT's specifications are off, such as its dimensions and size code. Copy the data from the other MRTT to fix that minor typo issue. (aircraft #4513)

### Sources

https://www.airbus.com/en/products-services/defence/military-aircraft/a330-mrtt
https://web.archive.org/web/20160424031754/http://militaryaircraft-airbusds.com/Aircraft/A330MRTT/A330MRTTAbout.aspx
[A330MRTTBrochure2014.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8084161/A330MRTTBrochure2014.pdf)

Re. deployment loadout :
Another typical mission is the deployment of fighter aircraft over a long distance. The A330 MRTT can support the deployment of four fighter aircraft plus 50 personnel and 12 tonnes of freight (luggage, spare parts and equipment) in one direct flight over 5200 km, e.g. from Europe to Afghanistan.

**Comment by PygmalionOfCyprus** [comment]
Added 493. Thanks for your detailed, in-depth request!
