### ISSUE TITLE
Japan, F-35B, Commission year

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1942]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5134

### Summary of Changes

commission year
---
2021→2024

### Sources

LM's factsheet
https://www.f35.com/content/dam/lockheed-martin/aero/f35/documents/FF_July%202022.pdf

Japanese News
https://www.the-miyanichi.co.jp/kennai/_54697.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
