### ISSUE TITLE
South Korea, F-35A, AIM-120D & AIM-9X Blk2 loadout

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1943]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4224

### Summary of Changes

For all loadout,
AIM-9X→AIM-9X Blk2(Weapon 2780)

Add
AIM-120D (C-8, Weapon 51) version for each loadout or AAW only.
Korea bought 120 of AIM-120C-7/C-8, while C-8 is AIM-120D, we can assume They have numbers of AIM-120D to use in the operation.

### Sources

AIM-9X2
https://www.dsca.mil/press-media/major-arms-sales/republic-korea-aim-9x-2-sidewinder-missiles
https://www.dsca.mil/press-media/major-arms-sales/republic-korea-aim-9x-block-ii-tactical-sidewinder-missiles

AIM-120C-7/C-8
https://www.dsca.mil/press-media/major-arms-sales/korea-aim-120c-advanced-medium-range-air-air-missile-amraam

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Removed the KGGB loadouts while I was at it because there's no way those fit in the internal bay and I didn't see anything about F-35 integration.

**Comment by clerara10** [comment]
> Handled 496. Removed the KGGB loadouts while I was at it because there's no way those fit in the internal bay and I didn't see anything about F-35 integration.

KGGB does not require any additional integration. If it can be physically attached to the pylon, it can be used, and a separate tablet is used.

**Comment by KC45jp** [comment]
I do not see any source suggesting integration to F-35. For F-5s, indeed it can operate by tablet with Bluetooth connection, but no reference for F-35.
F-35 has more advanced weapon system compared to F-5s... perhaps it is hard to modify system just for "releasing" one weapon type.
+ They have SDB bombs anyway... They have weak reason to use it.
