### ISSUE TITLE
South Korea, P-8A, Mk54 loadout

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1944]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5585

### Summary of Changes

South Korea likely use Mk 54 LWT for their P-8.
I'm not sure they will use their Blue Shark LWT in P-8 or not, but while they can use it in P-3C, they likely can use it?

### Sources

https://www.dsca.mil/press-media/major-arms-sales/republic-korea-mk-54-lightweight-torpedoes

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
