### ISSUE TITLE
P-8A, some of  Export version, AN/AAR-54 Missile Warning System and some more

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1945]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4742, 4709, 5585, 2706

### Summary of Changes

P-8 of Following country has **AN/AAR-54** as MAWS (instead of generic or ALQ-213)
India
New Zealand
Norway
South Korea

In addition, 

**AN/AAQ-24** is **NOT** on
India
South Korea

ADD **AN/APR-39D**
India

**ARES-1000** ESM for India is currently unknown... ALQ-128 is the right ESM?

### Sources

South Korea
https://www.dsca.mil/press-media/major-arms-sales/korea-p-8a-aircraft-and-associated-support

India
https://www.dsca.mil/press-media/major-arms-sales/india-p-8i-and-associated-support

New Zealand
https://www.dsca.mil/press-media/major-arms-sales/new-zealand-p-8a-aircraft-and-associated-support

Norway
https://ottawacitizen.com/news/national/defence-watch/norway-to-buy-boeing-p-8-surveillance-aircraft-canadian-firms-to-supply-equipment

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
