### ISSUE TITLE
Loadout, Germany P-8A, name is incorrect

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1946]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5097, loadout 28387

### Summary of Changes

it has Mk54 LWT but loadout name displays mk46 mod2. same for sonobuoys.

### Sources

-As loadout contents have

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
