### ISSUE TITLE
Remove Tomahawk Blk IV Multi mission ASuW capability or make it hypothetical

### ISSUE THREAD

**Issue by Thewood1** [PygmalionOfCyprus/cmo-db-requests#1949]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #2943, 2942, 2941

### Summary of Changes

The ASuW capability was never funded and not deployed.  

### Sources

The Military Balance write up on Tomahawk blk V.
https://www.deagel.com/Offensive%20Weapons/Tomahawk/a001146  Makes no reference to ASuW capability for blk IV.

**Comment by tbrandon517** [comment]
Looking around the interwebs the projected time tables for Block IV MMT from several sources line up with the those now shown for Block V. From somes sources (like this one here) it looks like MMT morphed into MST. There does seem to have been some test units in 2016-2018 timeframe so the missile could remain as is in the DB but marked as the test article for Blk V and MST.

[https://www.dote.osd.mil/Portals/97/pub/reports/FY2017/navy/2017tomahawk.pdf?ver=2019-08-19-113709-897](https://www.google.com/url?sa=i&source=web&cd=&ved=0CAQQw7AJahcKEwjgqY_vy6X5AhUAAAAAHQAAAAAQAg&url=https%3A%2F%2Fwww.dote.osd.mil%2FPortals%2F97%2Fpub%2Freports%2FFY2017%2Fnavy%2F2017tomahawk.pdf%3Fver%3D2019-08-19-113709-897&psig=AOvVaw1wAdKzfdNwwLRAfYHEfeVC&ust=1659441119760287)

**Comment by PygmalionOfCyprus** [comment]
Marked hypothetical. My research concurs with @tbrandon517. It appears that, after a number of delays getting the Blk IV MMT to IOC, they just rolled it up into the Blk Va MST.
