### ISSUE TITLE
China, DF-100 cruise altitude

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1950]
### DB Selector

DB3K

### Affected DBID(s)

weapon #3669

### Summary of Changes

[ cruise altitude change to 120000ft, about 36576m (if this is not a hard DB code editing work for you) ]

(This is the third issue I have opened about this "mysterious" weapon. Quite annoying huh)

I have checked two (should be) similar-type missiles' cruise altitude in DB. One is RGM-109Z Fasthawk which cruise at 100000ft, the other is SS-N-33 Zircon which cruise at 130000ft. I believe there is someting wrong with the current DF-100's cruise altitude (which is 24000ft, about 7315m, mid-troposphere)

It is acknowledged that these three (near-) hypersonic cruise missiles need a thin-air aerosphere to cut down drag and allow their ramjet/scramjet to work effectively, thus the missiles can achieve a high speed. Besides, they are designed to cruise at a high altitude to avoid aerodynamic surface-to-air missiles' interception when they are in mid-course flight.

### Sources

https://www.globalsecurity.org/wmd/world/china/df-100.htm
https://www.iiss.org/blogs/military-balance/2019/10/hypersonics-arms-control

**Comment by PygmalionOfCyprus** [comment]
Agreed. Fixed 496!
