### ISSUE TITLE
Mexico, Add Reformador class, LROPV

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1951]
### DB Selector

DB3K

### Baseline

#3019 IDN Martadinata, #3567 GRC Sigma 10514HN

### Hypothetical

No

### Name

Long Range Ocean Patrol Vessel, F101, Reformador

### Class

Reformador (POLA) ( Damen 10514)

### Country

Mexico

### Service

Navy

### In Commission

2020 - Present

### Number in Service

1

### Length (m)

107.1

### Beam (m)

14.1

### Draft (m)

3.75

### Standard Displacement (t)

2600

### Full Displacement (t)

2950

### Complement

122 + 20 extra

### Primary Propulsion Type

Diesel

### Propulsion

CODOE: 2 SEMT-Pielstick 20PA6BSTC diesels, 6x diesel generator. 2 shafts

### Fuel Capacity (kg)

300 tons diesel

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

5000 @ 14

### Sensors

1x SMART-S Mk2 TA radar
2x Raytheon NA radar (I & E/F)
STIR 1.2 Mk2 FC radar
CAPTAS-2 sonar
Rigel RESM

### Mounts

2x2 Harpoon Block II SSM (RGM-84L) 
1x8 ESSM SAM (RIM162A)
1x21 RAM BLock II (RIM-116)
1x1 57mm/70 Bofors SAK-57 Mk3
1x1 25mm/75 Mk38 mode 2
6x1 12.7mm/90
2x3 324 Mk32 TT (mk54)
Ragel RECM
2x SKWS decoy RL

### Aircraft & Docking Facilities

Hanger & Deck for 10t helo
2x RHIB in davits

### Comments

Due to the differences from the other 10514, made a new entry.

### Sources

1: https://www.navypedia.org/ships/mexico/mex_es_reformador.htm
2: https://en.wikipedia.org/wiki/Sigma-class_design
3: https://www.damen.com/catalogue/defence-and-security/sigma-frigates?view=models&model=SIGMA-Multi-Mission-Frigate-10514#sigma-multi-mission-frigate-10514
4: https://www.globalsecurity.org/military/world/mexico/arm-reformador.htm
5: https://marineschepen.nl/nieuws/Damen-levert-patrouilleschip-op-in-Mexico-120220.html
![1](https://user-images.githubusercontent.com/99532490/182040580-d137c25a-64dc-49f2-8367-abdbdab49b07.jpg)
![2](https://user-images.githubusercontent.com/99532490/182040583-18afab9a-1014-4320-a91b-df91fa427ef8.jpg)
![3](https://user-images.githubusercontent.com/99532490/182040584-5833b12e-8904-4ceb-bbfd-0d35267acc6a.jpg)
![4](https://user-images.githubusercontent.com/99532490/182040586-db296648-2ccb-429e-a3bd-6708ce627690.jpg)
![5](https://user-images.githubusercontent.com/99532490/182040587-fa622f25-d305-4cea-a373-0aa51da5f4f0.jpg)

**Comment by Parel803** [comment]
I believe this coulb be the Sigma 10514 entry in DB 497 as #4040 TBD [SIGMA 10514]. 
https://archive.damen.com/en/news/2019/12/sea_trials_of_damen_mexican_navy_frigate_complete

**Comment by tbrandon517** [comment]
> I believe this coulb be the Sigma 10514 entry in DB 497 as #4040 TBD [SIGMA 10514]. https://archive.damen.com/en/news/2019/12/sea_trials_of_damen_mexican_navy_frigate_complete

The new entry is for the Colombian navy. I don't have the new DB yet but it looks like some key differences in sensor and weapons fit.

https://www.navalnews.com/naval-news/2022/09/cotecmar-and-damen-inks-deal-for-colombias-new-frigate/

**Comment by Parel803** [comment]
Apologise, my stupidity. Thx

**Comment by tbrandon517** [comment]
@Parel803 you might want to check the new DB v502 entry against this request.

**Comment by Parel803** [comment]
I've seen it, thx. Very nice.
regards GJ
I'll close it then, correct?

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus DB entry seems to be missing CAPTAS sonar.

@Parel803 not sure if that's correct. I didn't see anything about it not being installed or removed.

**Comment by Parel803** [comment]
I'll reopen just to be sure.

**Comment by PygmalionOfCyprus** [comment]
Added the CAPTAS Mk2 503.
