### ISSUE TITLE
Brimstone 2 Seeker Correction

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1952]
### DB Selector

DB3K

### Affected DBID(s)

#3035, #3589

### Summary of Changes

There are two versions of Brimstone 2 in the DB495, 3035 fitted only with an Active Radar Seeker; the other 3589 fitted with both an Active Radar Seeker and a Laser Spot Tracker. 
However, all Brimstone 2s are dual-mode by default. Therefore, these weapons can be merged. 

[Brimstone2-Data-Sheet_Nov-2015.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/9229523/Brimstone2-Data-Sheet_Nov-2015.pdf)

### Sources

https://www.army-technology.com/projects/brimstone/

**Comment by PygmalionOfCyprus** [comment]
I can't delete/merge entries (backwards compat and all that), but I've deprecated the erroneous Brimstone 2 entry and replaced it in the couple of weapon records it was being used.
