### ISSUE TITLE
A-4SU, the Singaporean Super Skyhawk

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#1953]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 185, 3621

### Summary of Changes

Sensors:
- Add Pave Penny LST.

Mounts:
- Add Generic Chaff/Flare dispenser, pending information on the precise type.

Weapons:
- Add AGM-65B (Assumed B model, same as F-5Es which are given B model in the DB currently).
- Add GBU-12 and GBU-16 Paveway. No onboard designator, as far as I can tell.
- Add Generic Buddy Store. I think this is a Douglas D-704, but it's a buddy store.
![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/147742_cn-_12506_Singapore_TA-4SU_900.JPG/1280px-147742_cn-_12506_Singapore_TA-4SU_900.JPG)
- _Tentatively_ add AGM-45 Shrike. The FlightGlobal source attached below talks about the RSAF intending to replace their Shrikes with HARMs in 1998. The two aircraft in RSAF service prior to this article that are theoretically capable of Shrike carriage are the F-16A and the A-4S/S1/SU, but there's no way of telling which of the two it was on.

Properties:
- Add... something. A new HUD and weapons delivery system probably justifies Advanced Bombsight, I don't know if an INS alone is enough to add the Advanced Navigation INS/GPS tag.

Engine:
- Not really sure what to do with this. The datasheets all claim a significantly higher top speed from the new F404, but the game gives a higher cruise speed than the A-4S and keeps the top speed the same. I know the speeds in the game aren't the literal top speeds of the aircraft... I've also seen a source but can't find it again with a Singaporean pilot saying that in combat conditions the A-4SU could keep pace with the F-5E on the deck, which is 580kts military power in game?

### Sources

https://en.wikipedia.org/wiki/ST_Aerospace_A-4SU_Super_Skyhawk
http://skyhawk.org/article/douglas-a4-skyhawk-production-history#sing
http://www.nas.gov.sg/archivesonline/data/pdfdoc/MINDEF_20021027001/MINDEF_20021027003_2.pdf

https://www.flightglobal.com/singaporean-f-16d-block-52s-reveal-israeli-design-heritage/20663.article - Tentative Shrike evidence

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Adjusted speed on engine to 580 on the deck, which gets it to its stated max speed of 600kts at cruise alt. Seems fair to me.
