### ISSUE TITLE
Japan, SAM-1, facility

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1954]
### DB Selector

DB3K

### DBID to Copy

Facility 756, SAM-1B requested in #1852

### Hypothetical

No

### Name

SAM-1 Tan-SAM[Type 81]

### Country

Japan

### Service

Army

### Sensors

-All SAM-1 Sensor can illuminate 2 target, number can track is unknown

### Other Changes

JGSDF (army) version of SAM-1A. SAM-1 is original and A/B is Air Force and  Navy version.

### Sources

https://ja.wikipedia.org/wiki/81%E5%BC%8F%E7%9F%AD%E8%B7%9D%E9%9B%A2%E5%9C%B0%E5%AF%BE%E7%A9%BA%E8%AA%98%E5%B0%8E%E5%BC%BE

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1852#issuecomment-1195058426

**Comment by PygmalionOfCyprus** [comment]
The random blob of information left to me by a predecessor says of the Tan-SAM radar:

>In the omnidirectional search mode, the antenna is angled at 15 degrees elevation scanning at 10 rpm. Detection range is about 20-30 km (12.5-18.7 miles). The system can simultaneously track up to six targets. Each target is displayed and classified as to range, azimuth and elevation. The data are relayed to a computer, which then prioritizes the degree of threat lethality of each acquired target. Two targets can then be selected by the battery commander for engagement. Once the most threatening targets have been designated, the system switches to its tracking mode (CW) to obtain more precis e data. More definitive information and the latest location data for each threat are transmitted automatically to each of two launcher systems. 

So, adjusted to allow for 6-target search and 2-target direction.
