### ISSUE TITLE
SAM-1 Weapon Update

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1955]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 425

### Summary of Changes

Name
---
Original missile is SAM-1 and if db use same weapon for SAM-1, SAM-1A, and SAM-1B, then the weapon name should be  original SAM-1.

Code
----
LOAL capability

### Sources

https://ja.wikipedia.org/wiki/81%E5%BC%8F%E7%9F%AD%E8%B7%9D%E9%9B%A2%E5%9C%B0%E5%AF%BE%E7%A9%BA%E8%AA%98%E5%B0%8E%E5%BC%BE

**Comment by PygmalionOfCyprus** [comment]
Handled 496 and added comment to indicate it representing 1, 1A, and 1B designations.
