### ISSUE TITLE
J/ALQ-9 Electric Jammer

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1956]
### DB Selector

DB3K

### Baseline

Weapon 3662

### Hypothetical

No

### Name

J/ALQ-9

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

0.2 (based on ALE-70)

### Warhead

-

### Targets

Aircraft

### Sensors

-

### Comments

ECM device launched from ALE-45. Other than Communication Jamming, this works similar to ALE-70(Weapon 3662).

Contents of ALE-70 would be...
8x ALQ-9
8x Flare
16x Chaff

Carried by F-15J/DJs from 1990.

### Sources

https://aobamil.sakura.ne.jp/mil-dic/J.html
http://mmsdf.sakura.ne.jp/public/glossary/pukiwiki.php?J%2FALQ-9

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
