### ISSUE TITLE
JSTARS Radar (AN/APY-3/7 Pave Mover) Corrections

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1957]
### DB Selector

Both

### Affected DBID(s)

2725, 5000

### Summary of Changes

Pave Mover is an I band radar, not E/F.  Not sure if this makes a difference or not.  What will make a difference is that it is directional and can only look one side at a time, not sure if or how you would model that especially as the platform will move and turn.
It also has SAR capabilities, all part of what it is designed for.
Using its SAR and GMTI, it can give quite good target class ID.  It can detect static targets, if they have doppler, which a rotating item such as a radar antenna would give. Again not sure how you would model this.
The range would be around 250km, various sources state 230 to 250 plus, but not seen 380 quoted anywhere.

### Sources

https://www.radartutorial.eu/19.kartei/08.airborne/karte061.en.html

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
