### ISSUE TITLE
B-29 lacks Little Boy loadout

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#1959]
### DB Selector

CWDB

### Affected DBID(s)

CWDB 388 CWDB 2193

### Summary of Changes

Despite the B-29 famously dropping Little Boy/Mk 1 nuclear bomb (CWDB Weapon 811) , it lacks the ability to do so in current versions of the database. 

Add loadout: 1x Mark-1 Strategic Nuclear Bomb. 

Can use the same 2000nm strike radius as the existing nuke loadouts. 

### Sources

https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196219/little-boy-atomic-bomb/

**Comment by PygmalionOfCyprus** [comment]
Jeez, how'd that get missed? Added 496.

**Comment by boogaboogaCMO** [comment]
Any chance of adding mines to the B-29 loadout while you're under the hood?
