### ISSUE TITLE
LCS 2 CS Gen Correction

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#1961]
### DB Selector

DB3K

### Affected DBID(s)

#1840, #3155 #2595

### Summary of Changes

LCS 2 Independence class vessels currently have CS Gen 3 settings. While these vessels are known to be somewhat limited, seeing as the LCS 1 ships have CS 6, shouldn't LCS 2 vessels share the same generation of tech?

![20220801 - LCS CS Gen Issue](https://user-images.githubusercontent.com/99649251/182213552-773a5b1e-acbd-414a-b635-66b3df03717a.jpg)

### Sources

CMO DB495

**Comment by Zomorudas** [comment]
In case this seems like déja vu, and merits wider enquiry, this was part of issue #1567. It looks like I messed up some of the IDs, causing this to be missed. You are obviously correct.

**Comment by PygmalionOfCyprus** [comment]
1840 and 2595 were handled in #1567 as mentioned, but fixed 3155 as well for 496.
