### ISSUE TITLE
Mexico, Add Punta Morro (Point) class, Patrol

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1962]
### DB Selector

DB3K

### DBID to Copy

#2729 WPB 82301 Point Caution [Point Class] (DB3K)

### Hypothetical

No

### Name

Large Patrol Craft, PC281, Punta Morro

### Country

Mexico

### Service

Navy

### In Commission

1991 (recomissioned) - present

### Number in Service

2

### Mounts

1x single 20mm/70 Mk 10
2x single 12.7mm/90 (src1, src2 states 1x)

### Other Changes

From src1:
Speed much reduced from original.
Pennant numbers changed in 2001.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/mexico/mex_cf_punta_morro.htm
![1](https://user-images.githubusercontent.com/99532490/182222363-d6296b47-e9db-4acc-981f-9ad18759c5cc.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
