### ISSUE TITLE
Mexico, Add Montes Azules class, Landing Ship

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1963]
### DB Selector

DB3K

### Hypothetical

No

### Name

Amphibious Transport, BAL01, Montes Azules

### Class

Montes Azules

### Country

Mexico

### Service

Navy

### In Commission

2011 - present

### Number in Service

2

### Length (m)

99.8

### Beam (m)

15.2

### Draft (m)

3.4

### Standard Displacement (t)

Not found

### Full Displacement (t)

3666

### Complement

89

### Primary Propulsion Type

Diesel

### Propulsion

2x diesel, 2 shafts

### Flank Speed (kt)

12

### Range (nm) at Speed (kt)

Not found

### Sensors

2x NA radar (I & E/F) [prob Furuno]

### Mounts

4x single 40mm/60 Mk 3 (src2), scr3 gives 5x single.

### Aircraft & Docking Facilities

helicopter platform for 1 medium helo. 
Bowramp. 
2x LCVP. 
Crane

### Comments

Military load: 850t cargo + 178 troops

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/mexico/mex_ls_montes_azules.htm
3: https://en.wikipedia.org/wiki/Montes_Azules-class_logistics_ship
![1](https://user-images.githubusercontent.com/99532490/182232025-a2e23ca7-37a4-45e7-9074-54355f410198.jpg)
![2](https://user-images.githubusercontent.com/99532490/182232028-5b0b69e9-ad44-4fd9-89ba-322249fe4884.jpg)
![3](https://user-images.githubusercontent.com/99532490/182232030-4abb8658-1247-4e3f-a156-dd894aa48da5.jpg)
![4](https://user-images.githubusercontent.com/99532490/182232035-6cd3ed84-f42f-4269-a1dd-6d2e2b3ed7af.jpg)
![5](https://user-images.githubusercontent.com/99532490/182232037-06570adf-513c-4e64-b770-2361015a1806.jpg)

**Comment by Jkryos** [comment]
Added pre 507
