### ISSUE TITLE
Iran has only one variant of the SA-15, this is the SA-15B. In the DB Iran has the more modern SA-15D

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1964]
### DB Selector

DB3K

### Affected DBID(s)

#481 – SAM Plt (SA-15d Gauntlet [9K330 Tor-M2E]

### Summary of Changes

Please correct #481 – SAM Plt (SA-15d Gauntlet [9K330 Tor-M2E] to #435 – SAM Plt (SA-15b Gauntlet [9K330 Tor-M1K]
Sources:
The picture in de DB of the Iranian SA-15 system represents the SA-15b, and also the internet links in the sources tab show that Iran has the SA-15b variant.
**Sipri arms export database:**

(750)	9M338	SAM missiles	2006-2007	For Tor-M1 (SA-15) SAM systems
     		
(29)	Tor-M1	mobile SAM system	2006-2007	(29)	$700m deal (part of $1 b deal); incl for protection of Iranian nuclear plant

### Sources

https://armstrade.sipri.org/armstrade/page/trade_register.php
https://www.washingtonpost.com/world/2020/01/10/what-is-sa-15-air-defense-system-that-may-have-shot-down-ukrainian-plane/
https://www.key.aero/forum/modern-military-aviation/missiles-and-munitions/71030-iranian-sa-15-pictured-at-natanz
https://www.defenseindustrydaily.com/iran-buying-sa15tor-m1-sam-systems-from-russia-01572/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
