### ISSUE TITLE
NH90 Norway cancelled 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#1967]
### DB Selector

DB3K

### Affected DBID(s)

#559 #2350 NH90 Norway all variants

### Summary of Changes

Contract cancelled after delivery of only 8 airframes. Norwegian MoD asking for money back.
Given that its never acheived satisfactory service capacity it may be worth a note to that effect or hypothetical tag and/or an out of service date of 2022.
MH60 to follow?? 

### Sources

https://verticalmag.com/news/norway-cancels-nh90/?amp
https://theaviationist.com/2022/06/19/norway-permanently-terminates-nh90-ops/amp/

But many others. Plus it assumes it all doesn't descend into a legal battle.
Noted Australian DB3K #2352 NH90 Taipan binned for similar issues. https://www.thedefensepost.com/2021/12/16/australia-mrh-90s-black-hawks/amp/

**Comment by PygmalionOfCyprus** [comment]
OOS added 496. Opted not to mark hypothetical since they did technically fly/operate the thing.
