### ISSUE TITLE
Rafale Loadout: Damocles LDP Sensor Pod

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#1968]
### DB Selector

DB3K

### Affected DBID(s)

Thirteen Rafales.

### Summary of Changes

The (usually six) loadout options including the sensor ID **#479 - Damocles LDP Pod [FLIR + LRMTS, 40K ft]** do not actually use it, but instead have the sensor ID **#3149 - Talios LDP-NG Pod [FLIR + LRMTS, 40K ft]**. I have no idea if the label needs changing, or the loadout needs the listed pod.

Rafales: **#5588, #5485, #5589, #5486, #5274, #5275, #5276, #5271, #5272, #5273, #3643, #3230, #3231**.

### Sources

DB 495.

**Comment by PygmalionOfCyprus** [comment]
Handled 496. I assume the Rafale's Talios loadouts were copied to make them but not actually updated.
