### ISSUE TITLE
#611 MEX Azteca: Class name & Sidnr

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#1969]
### DB Selector

DB3K

### Affected DBID(s)

#611

### Summary of Changes

First unit in class: Andres Quitana Roo, Cordova was second unit in class.
Original Sidenr is P 01.
31 units in class, first commissioned in 1974.
Names changed in 1993; AQ Roo to Azteca, renamed back to original in 2001.
Sidenrs change in 2001
Updated on weapon started in 2000: - 1 x 1 - 20/70; + 1 x 1 - 7.6/90

### Sources

1: https://www.navypedia.org/ships/mexico/mex_cf_azteca.htm
2: JFS 2015-2016
3: JFS 1984-1985
4: JFS 1998-1999

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Spent a good five minutes trying to figure out what a "Sidenr" was... 😅

**Comment by Parel803** [comment]
Sorry about that :-)
