### ISSUE TITLE
RCAF CC-144 Challenger 604B x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#197]
### DB Selector

DB3K

### Hypothetical

No

### Name

RCAF CC-144 Challenger 604B

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2002-xxxx

### Length (m)

20.85

### Wingspan (m)

19.61

### Height (m)

6.3

### Empty Weight (kg)

9292

### Maximum Takeoff Weight (MTOW) (kg)

19618

### Payload Weight (kg)

1814

### Crew

2

### Propulsion

2x CF-34-3B

### Rate of Climb (ft/min)

2470/7400

### Service Ceiling (ft)

41000

### Military/Afterburner Speed (kt)

470

### Cruise Speed (kt)

460

### Supercruise

No

### Ferry Range (nm)

4400

### Takeoff / Landing Distance (m)

1401-2000m

### Fuel Capacity (kg)

Kanata

### Sensors

1x Generic Weather Radar
1x Mk1 Eyeball

### Mounts

None

### Loadout Options

- Ferry DB ID #22563
- Maintenance 
- Reserve
- Passengers, 8x VIP DB ID #28709
- Medevac 3x Litters **Needs to be created**

### Comms/Datalinks

UHF/VHL [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Copy of Australian 604 DB ID #5221

### Sources

http://www.rwrwalker.ca/CF_Challenger_detailed.html
https://www.va3kgb.com/milac/cc144_challenger.htm
https://en.wikipedia.org/wiki/Bombardier_Challenger_600_series#Military_and_government_operators
http://www.rcaf-arc.forces.gc.ca/en/aircraft-current/cc-144.page

**Comment by Jkryos** [comment]
Added DB3K 494.
