### ISSUE TITLE
Czech Republic - Jas 39C Gripen

### ISSUE THREAD

**Issue by BlackHoundCZ** [PygmalionOfCyprus/cmo-db-requests#1970]
### DB Selector

CWDB

### DBID to Copy

Aircaft 1498 CWDB

### Hypothetical

No

### Name

JAS 39C Gripen

### Country

Czech Republic

### Service

Air Force

### In Commission

2005

### Number in Service

12

### Sources

https://acr.army.cz/technika-a-vyzbroj/letecka/-jas-39-gripen-89934/
https://www.valka.cz/SAAB-JAS-39C-Gripen-t33782
https://en.wikipedia.org/wiki/Saab_JAS_39_Gripen

**Comment by PavelNovak79** [comment]
Czech Gripens were added to new DB2000 database (available in beta now). It should not be added to CWDB which is for timeframe to about 1980.
