### ISSUE TITLE
Please add dedicated Nebo-M (55Zh6M) S-400 battery

### ISSUE THREAD

**Issue by Nuclear-Monkeys** [PygmalionOfCyprus/cmo-db-requests#1971]
### DB Selector

DB3K

### DBID to Copy

SAM bn #2029 (DB3K)

### Hypothetical

No

### Name

SAM Bn (SA-21 a/b Growler) (NEBO-M) 48N6DM + 40N6 [S-400 Triumf] Russia[1992]-2017 12x TEL

### Country

Russia

### Service

Air Force

### In Commission

2015-Present

### Number in Service

6x batteries active, (100 batteries ordered in 2011)

### Sensors

keep 92N6 grave stone FCR

keep 96L6 cheese board all-altitude acquisition radar

-Add RLM-D (# 1878)

-Add RLM-S (# 1848)

-Add RLM-M (# 1846)

keep Mk1 Eyeball

### Mounts

-keep 3x SA-16 Gimlet

-keep 12x SA-21a/b growler TEL

-keep vehicle cheese board [96L6]

-add vehicle RLM-D

-keep vehicle (grave stone [92N2])

-add vehicle RLM-S

-add vehicle RLM-M

### Loadout Options

-24x SA-21b 40N6 
-24x SA-21a 48N6DM 

### Other Changes

The S-400 is a daunting yet interesting challenge to go up against in this game. But there is no way to set up a properly functioning Nebo-M system that operates with the current in game S-400 batteries. Only its separate radars that cannot guide any missiles. Currently the SA-21 can only fire a missile using 96L6 or 92N2, but cannot be guided by RLM-D or RLM-S which are the Nebo substitutes. So to address this issue, I've introduced a way to add an extra even more challenging unit to the game. The S-400 NEBO-M battery that uses both long range and very long range missiles 48N6DM + 40N6, that has much longer missile engagement ranges than what the standard S-400 battery can achieve.

**In a nutshell:**
-RLM-S (S-band) FCR replaces the 92N2 FCR, able to fully guide 48N6DM missiles.
-RLM-D (L-band) acquisition radar replaces the 96L6 Cheese Board, able to fully guide 40N6 missiles.
-RLM-M radar plays same role as 91N6 Big Bird D, early warning and target acquisition
-NEW COMMAND POST (RLM-KU) replaces SA-21/25 datalink. Offers compatibility to fully guide 48N6DM/40N6 missiles from RLM-D/RLM-S radar tracks. Similar to how SA-25/21 command datalink works with 92N2 and 96L6 radars
(RLM-S functions similar to 92N2 gravestone, RLM-D functions similar to 96L6 cheese board, RLM-M functions similar to 91N6 Big Bird D)
**Mounts/Missiles:**
12x TEL SA-21a/b (48 missiles total)
-6x TEL (48N6DM) 24 missiles total
-6x TEL (40N6) 24 missiles total

**_IMPORTANT NOTE:_** 1. RLM-S in game is capped at 160nm (300km) which is the old range for the original gamma-c1 that its based on. However, the RLM-S has a range of at least 400km/216nm (similar to 92N2) in order for it to guide the very long range 40N6. RLM-S is a much newer AESA with larger antenna size than the older 92N2, having even longer range and better tracking capabilities. Finally, its function and abilities should be same if not better than the standard S-400 FCR, thus the range needs to be increased to a minimum of 217nm and given better range values than the grave stone 92N2. Here grave stone shown as having ~20nm range for 0.001m2 target, 42nm for 0.01m2, and 75nm for 0.1m2. RLM-S should surpass this since **_1)_** it uses longer wavelength S-band (not X-band like 92N2 grave stone), **_2)_** is AESA not PESA like grave stone , **_3)_** larger aperture. But same max range of 400km (217nm).
![SA-21 radar](https://user-images.githubusercontent.com/110662764/183223228-92b9cb97-1154-4e5c-9851-34710e9a1247.png)

Please consider this idea, as most of the radars are already in the game, just needs update of the RLM-S, and addition of a compatible command post/RLM-KU to enable missile guidance. This would be the most challenging of all SAM systems in game to go up against as a player or AI. Would offer a very cool experience if added to the game. Thank you

### Sources

http://www.ausairpower.net/APA-Nebo-SVU-Analysis.html

https://en.wikipedia.org/wiki/Nebo-M

https://www.deagel.com/Sensor%20Systems/55Zh6M%20Nebo-M/a002724

https://www.deagel.com/Sensor%20Systems/RLM-S/a003718

**Comment by Huib18** [comment]
Quote:
-24x SA-21b 40N6 (able to be guided by RLM-D, similarly to how 96L6 guides 40N6 in standard battery)
Question:
The 96L6 acquisition radar does not guide the missile, the 92N2 does. 

Quote:
-24x SA-21a 48N6DM (able to be guided by RLM-S only, similarly to how 92N2 only guides 48N6DM in standard battery)
Question:
Where in this case is a 48N6DM missile getting its semi-active radar/TVM guidance from?

**Comment by TheBagelInhaler** [comment]
> Quote: -24x SA-21b 40N6 (able to be guided by RLM-D, similarly to how 96L6 guides 40N6 in standard battery) Question: The 96L6 acquisition radar does not guide the missile, the 92N2 does.
> 
> Quote: -24x SA-21a 48N6DM (able to be guided by RLM-S only, similarly to how 92N2 only guides 48N6DM in standard battery) Question: Where in this case is a 48N6DM missile getting its semi-active radar/TVM guidance from?

good question. If RLM-S is an S-band similar to 96L6 (2-4 GHz), then it should also be capable of guiding 40N6 ARH missile and not just 48N6DM.

**Comment by TheBagelInhaler** [comment]
Should correct this entry: Both RLM-D and RLM-S should in theory be both able to guide either the 40N6E or the 48N6E3 missiles used by SA-21a/b. RLM-D being AESA has more accuracy than the older PESA protivnik-ge, which already has fairly good accuracy for an L-band up to 50 meters. Likewise RLM-S is the S-band AESA upgrade of the older PESA Gamma-S1, which again, has even better resolution due to being shorter wavelength. So RLM-D should be able to guide all S-400 missiles regardless of type (semi-active/active radar guidance).

**Comment by HVAA** [comment]
You are mistaking target quality tracking with the actual guidance of a missile. 
 
What is happening in game, IMO, is what happens IRL with the shared awareness model. However, once the FCR is 'dead' the battery is not able to fire because (and this is a really important distinction) the data links it needs are on the front of the FCR array.  None of these missiles are 'fire and forget' all need initial and midcourse data linking plus being commanded into the 'seek and destroy' mode.

RLM-S and NEBO-M are nothing like 96L6. The latter has a very specific set of roles that are not replicated by the former 2.  And where is the I band CW coming for the 48N6??

**Comment by Nuclear-Monkeys** [comment]
> You are mistaking target quality tracking with the actual guidance of a missile.
> 
> What is happening in game, IMO, is what happens IRL with the shared awareness model. However, once the FCR is 'dead' the battery is not able to fire because (and this is a really important distinction) the data links it needs are on the front of the FCR array. None of these missiles are 'fire and forget' all need initial and midcourse data linking plus being commanded into the 'seek and destroy' mode.
> 
> RLM-S and NEBO-M are nothing like 96L6. The latter has a very specific set of roles that are not replicated by the former 2. And where is the I band CW coming for the 48N6??

If you're right about this (not doubting it) then that would mean either the Nebo-M (all the other extra radars) only offer detection (awareness/early warning only), which helps situational awareness but cannot achieve longer range engagement for SAM missiles. Or does Nebo-M work via bi-static effects to help cue the I/X band 92N2 ? I'm confused how this is supposed to work.

**Comment by Nuclear-Monkeys** [comment]
> Quote: -24x SA-21b 40N6 (able to be guided by RLM-D, similarly to how 96L6 guides 40N6 in standard battery) Question: The 96L6 acquisition radar does not guide the missile, the 92N2 does.
> 
> Quote: -24x SA-21a 48N6DM (able to be guided by RLM-S only, similarly to how 92N2 only guides 48N6DM in standard battery) Question: Where in this case is a 48N6DM missile getting its semi-active radar/TVM guidance from?

It seems  I misunderstood each radar's specific role and function. According to HVAA (other user) , only FCR can authorize a missile launch (and guide the missile) since its arrays have the datalink necessary for such a missile launch/TVM. All other radars, big bird, 96l6, nebo, etc, do not have these data links so they can provide tracking/high quality tracks/updates, but not 100% trajectory guidance. 

This begs the question of how Nebo-M manages to extend engagement ranges for the SA-21 missiles. Either through bi-static effects, sensor fusion, or a combination of both. RLM-D, RLM-S, RLM-M, Protivnik-GE, Gamma-DE apparently uses some of these methods to "cue" the 92N6 FCR of the SA-21 against low observable targets at longer ranges than it normally could detect/track on its own. So I'm guessing this is how the NEBO-M can enable the SA-21 to engage targets at further ranges.

**Comment by HVAA** [comment]
It provides target quality tracks to the system, which can then launch the missiles using off board data, bit like some 5 gen can control each others missiles (and indeed compatible ones from 4 Gen - beautifully modelled in CMO). The guidance commands still come from the FCR no matter what.

**Comment by Nuclear-Monkeys** [comment]
> It provides target quality tracks to the system, which can then launch the missiles using off board data, bit like some 5 gen can control each others missiles (and indeed compatible ones from 4 Gen - beautifully modelled in CMO). The guidance commands still come from the FCR no matter what.

Ok, I understand now. In order to authorize a launch, does the FCR still itself need to illuminate that certain target directly or via bi-static/sensor fusion? Or can it authorize a launch just based off the data from external radars without itself illuminating that exact target? I'm still confused how Nebo-M would be able to engage stealth targets at further ranges in this case working with the FCR.

**Comment by HVAA** [comment]
The overall problem is that there is a need for the system to track its missiles as well as the target.  So a high quality track could be passed to the command post but would it need the Gravestone to 'light up' - probably, if only to track the missiles. Also updates from off board would be much slower as you need to factor in the scan period of the radar providing the track and any inherent latency in the datalink between the off board radar and the command post.  A good example of latency is in Link 16 where things occur in a 12 second time frame, so max latency (assuming messages are in every time frame) would be 12 seconds in the case of this particular datalink.  Any system has this as the data has to be sent in a predetermined sequence to keep bandwidths practical.

**Comment by HVAA** [comment]
Not saying all this is modelled in CMO, but IRL, this is a reason that things cant always perform exactly as you might think.  Cant get round the laws of physics ;-)

**Comment by HVAA** [comment]
Another note for you as this seems a common place misconception in CMO.  12 Tels S-400 (or S-300PMU2) should only be utilised in SAM rings (so Moscow C and St Petersburg).  The run of the mill sites run by (ex) PVO should have 8 Tels.  Likewise the taller masts are utilised with the 12 Tel Systems (40 m vice 24 m)

**Comment by Nuclear-Monkeys** [comment]
I see now. 

> Another note for you as this seems a common place misconception in CMO. 12 Tels S-400 (or S-300PMU2) should only be utilised in SAM rings (so Moscow C and St Petersburg). The run of the mill sites run by (ex) PVO should have 8 Tels. Likewise the taller masts are utilised with the 12 Tel Systems (40 m vice 24 m)

Gothca, makes more sense now. I'll probably close this request then as there are already Nebo-M radar systems in the game which can work with the SA-21 batteries.
However, I still think the ranges for the RLM-S should be increased to 216nm since the older system its based on had a 160nm range (meant for PMU/PMU2 missiles with max range of 250km). Also the RLM-D range values should be tweaked as its almost always outperformed by the older PESA version Protivnik-GE. RLM-D has max range of 270nm while Protivnik-GE is 215nm, however being full AESA upgrade it should have much better resolution and tracking ranges against low RCS targets than the PESA protivnik-GE. When I test this out, it;s not the case. Protivnik-GE beats it by tens of kilometers every time no matter what the target or altitude of the target is.

 RLM-D should surpass Protivnik-GE
