### ISSUE TITLE
add 40N6 missile guidance capability for Protivnik-GE, Gamma-DE, RLM-D radars

### ISSUE THREAD

**Issue by Nuclear-Monkeys** [PygmalionOfCyprus/cmo-db-requests#1972]
### DB Selector

DB3K

### Affected DBID(s)

 2104, 1847, 2257, 3219, 3149

### Summary of Changes

Please add the ability for Protivnik-GE/Gamma-DE/RLM-D radars to guide and launch 40N6 ARH missile for SA-21b.
These radars are substitutes and optional  components for the standard 96L6 acquisition radars, but have more counter-stealth features and longer ranges and are accurate enough for mid-course updates/trajectory missile guidance via UHF/L-band uplink. VNIIRT table below shows gamma-de/protivnik-ge as substitutes
![S-400-Battery-Composition-Diagram](https://user-images.githubusercontent.com/110662764/183224870-c1e0384e-6c47-4f7d-9c37-475b4267a630.gif)

The Protivnik-GE has a minimum range accuracy of 50 meters, 0.2 deg azimuthal and 0.17 deg elevation, being accurate enough for ARH missile guidance. ![Protivnik-GE accuracy](https://user-images.githubusercontent.com/110662764/183225396-1ce752c9-4d1b-4c64-9f0e-273267d38644.png)

Similarly the AESA upgrade of Protivnik-Ge used in NEBO-M system, designated RLM-D, achieves even better accuracy. Used to accurately guide ARH 40N6 missiles in the Nebo-M battery.

Gamma-DE also accurate enough for midcourse updates/ cueing/ trajectory guidance of ARH missiles. Minimum accuracy 60 meters, azimuthal accuracy of 0.17-0.2 deg and elevation accuracy of 0.2-0.3 deg.
![Gamma-DE accuracy](https://user-images.githubusercontent.com/110662764/183225486-1282b21c-571f-4f37-903c-d5ef1d14cda0.png)

Here Protivnik-GE is shown as having a minimum range measurement of 12 meters although 50m is more likely.
![protivnik-GE accuracy #2](https://user-images.githubusercontent.com/110662764/183225778-8deecf08-bda8-46e2-8eac-0fa5d966f576.png)

### Sources

http://www.ausairpower.net/APA-Rus-Low-Band-Radars.html#mozTocId829681

http://www.ausairpower.net/APA-Nebo-SVU-Analysis.html

https://www.radartutorial.eu/19.kartei/02.surv/karte063.en.html

https://www.deagel.com/Sensor%20Systems/Protivnik-GE/a003677

**Comment by HVAA** [comment]
Cant guide. Can only provide Target quality tracking.  IRL this is a HUGE distinction and not well explained or translated from the source material (not blaming the OP for this, its just the way it is).
40N6, 48N6, 9M96 all require a dedicated FCR and do not NEED any of the these option radars, which only add to the air picture and play no part in physical guidance as the data links are on the Fire Control Radar.  Kill the FCR and all the optional radars in the world advertised by the manufacturer changes nothing, the system cannot fire.

**Comment by Nuclear-Monkeys** [comment]
> Cant guide. Can only provide Target quality tracking. IRL this is a HUGE distinction and not well explained or translated from the source material (not blaming the OP for this, its just the way it is). 40N6, 48N6, 9M96 all require a dedicated FCR and do not NEED any of the these option radars, which only add to the air picture and play no part in physical guidance as the data links are on the Fire Control Radar. Kill the FCR and all the optional radars in the world advertised by the manufacturer changes nothing, the system cannot fire.

Do we know for certain that none of the Nebo-M constituents cannot guide a missile? I get that it's standard for a designated FCR to be the only capable piece to launch  missiles for most SAM systems. If none of these radars can extend missile engagement range against aircraft, they seem to be pretty pointless then apart from detection. Unless they extend the range of the FCR through bi-static effects?

**Comment by HVAA** [comment]
Indeed that is what they state, because that is what Rosoboronexport claim.  Looked all over on GE and when finding a S-400 site, there is only an SSR, FCR and BMR anywhere near them...  The Russians dont (from satellite evidence) appear to use them this way, so may I suggest they are options (perhaps because Big Bird is so expensive) to reduce costs...  bit like Tin Shield with SA-10.  This does not mean they are hard coded to the site, only that they may be nearby providing an air picture to suppplement the BMR.
