### ISSUE TITLE
SA-15, All Variants Modelled WIth Dog Ear As Inherent TA Radar (which is incorrect)

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#1973]
### DB Selector

DB3K

### Affected DBID(s)

SA-15 All

### Summary of Changes

SA-15 Platoons are modelled, if I have read this right, as having either 2 or 3 vehicles.
They have 2 TELARs which, coupled with the stated sensors would indicated that the Dog Ear is on the mount.  It is not.
Scrum Half has two elements.  
1. A TA radar, with up to 8 stacked beams to provide rudimentary 3D coverage of a 32 degree sector and a 1 second scan (as illustrated in Aus Air Power). 
2. A multifunction fire control radar which has a 15 degree sector to track and control. 

Dog Ear is an up-echelon add in.  Certainly there would not be one per TELAR, more likely one per battalion (4 x Telar plus its associated Rangir).

Please remove the hard association between Dog Ear and SA-15.

You kindly included 1L122 at my request in the DB. A single Dog Ear or a single 1L122 would be a better fit for the battalion (if you modelled a battalion). Your alternative would be to have a 'left' and 'right' platoon, one having 2TELAR plus a command post and a up echelon TA, the other just the 2 TELARs.  Of course this would presuppose that community scenario designers would use them as intended.

### Sources

http://www.ausairpower.net/APA-9K331-Tor.html

**Comment by bostonmyk** [comment]
Not sure if this will help.
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/605

**Comment by HVAA** [comment]
It probably does, but the issue I spotted is two vehicles, each with 2 distinct radars, which is wrong. Dog Ear is not fitted to the TELAR as the DB entiries infer. Scrum Half is a two radar system, a bit like Land Roll and Straight Flush

**Comment by PygmalionOfCyprus** [comment]
Handled 496. I also edited the comments on the SA-15s to indicate that higher echelons (in this case Btns) should ideally have an attached Dog Ear.
