### ISSUE TITLE
Japan, LR-2 Hayabusa [King Air 350]

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1975]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5162

### Hypothetical

Yes

### Name

LR-2 Hayabusa [King Air 350]

### Country

Japan

### Service

JGSDF

### In Commission

2000-

### Number in Service

9x, 1x crashed in 2017

### Sensors

Mk1 Eye Ball
Generic Visual Reconnaissance Camera(sensor ID 910)

### Mounts

-

### Loadout Options

Same as Base + Recon/ISR Mission 

### Sources

https://ja.wikipedia.org/wiki/LR-2#cite_ref-1

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
