### ISSUE TITLE
China, 370mm BRE8 Guided Rocket

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1976]
### DB Selector

DB3K

### Baseline

weapon 4359

### Hypothetical

No

### Name

370mm BRE6 Rocket

### Length (m)

7.8

### Width/Span (m)

0.12

### Diameter (m)

0.37

### Weight (kg)

800

### Range (nm)

10-220nm

### Warhead

220kg HE

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

10

### Sensors

-

### Weapon Codes

Ballistic Missile or Rocket Booster, Weapon - INS Navigation, Uses BeiDou/COMPASS, Level Cruise Flight

### Comments

What confuses me is the accurate CEP data of this weapon. According to multiple sources, I decided to give that one above.
280km for export version (according to MTCR). It should have a longer range when comes to self-use version (400km will be reasonable, since we have 300km A-300).

### Sources

https://en.wikipedia.org/wiki/BRE_(rocket)
https://www.globalsecurity.org/military/world/china/ar-3.htm
https://en.wikipedia.org/wiki/PHL-16
Seen from a Chinese video website: 
![Screenshot_20220807_173035](https://user-images.githubusercontent.com/107970049/183284904-8edef2ae-4c58-4e31-8a58-472ba2d13f84.jpg)

**Comment by LuigiP57** [comment]
According to MTCR, its range is reduced to no more than 300km. However, it is believed that the self-use version should be over 300km range (400km will be reasonable).

**Comment by LuigiP57** [comment]
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/feaa7568-0400-43d7-a06a-cfd0f4ddc20c)
The figures in the chart refer to the data of the export version of the weapon series. Selfuse versions are supposed to have a longer range

**Comment by PygmalionOfCyprus** [comment]
This was added in 508.
