### ISSUE TITLE
China, Fire Dragon 480 Ballistic missile, export version of BRE8

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1978]
### DB Selector

DB3K

### Baseline

weapon 779

### Hypothetical

No

### Name

Fire Dragon 480

### Length (m)

same as BRE8

### Width/Span (m)

same as BRE8

### Diameter (m)

same as BRE8

### Weight (kg)

same as BRE8

### Range (nm)

30-150

### Warhead

same as BRE8

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

same as BRE8

### Sensors

-

### Weapon Codes

Ballistic Missile or Rocket Booster, Weapon - INS Navigation, Uses BeiDou/COMPASS, Level Cruise Flight

### Sources

https://en.wikipedia.org/wiki/BRE_(rocket)
![image](https://user-images.githubusercontent.com/107970049/183286007-3bb00e2f-55dc-498d-b595-06a7110ee8c7.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
