### ISSUE TITLE
CCG Bell 412 EPI x7

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#198]
### DB Selector

DB3K

### Hypothetical

No

### Name

Bell 412 EPI

### Country

Canada

### Service

Canadian Coast Guard

### In Commission

2017-

### Length (m)

17.1

### Wingspan (m)

14.0

### Height (m)

4.6

### Empty Weight (kg)

3674

### Maximum Takeoff Weight (MTOW) (kg)

5397

### Payload Weight (kg)

2040

### Crew

2

### Propulsion

2x P&WC PT6T-3BE Twin-Pac Turbo Shafts

### Rate of Climb (ft/min)

1350

### Service Ceiling (ft)

15000

### Military/Afterburner Speed (kt)

140

### Cruise Speed (kt)

122

### Supercruise

No

### Ferry Range (nm)

402

### Takeoff / Landing Distance (m)

0m (VTOL) TOD/LAD

### Fuel Capacity (kg)

655

### Sensors

1x Generic Weather Radar
1x Mk1 Eyeball
1x Generic Surface Search Radar

### Mounts

None

### Loadout Options

- Ferry
- Maintenance
- Reserve
- SAR
- Maritime Surveillance 

### Comms/Datalinks

UHF/VHF Radio [Unsecure]

### Sources

https://www.ccg-gcc.gc.ca/fleet-flotte/helicopters/bell-textron-412-epi-eng.html
https://www.bellflight.com/-/media/site-specific/bell-flight/documents/products/412/bell-412epi-product-specifications.pdf
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Canadian_Coast_Guard#Light_and_medium-lift_helicopters

![b412_ccg_dart](https://user-images.githubusercontent.com/99632305/154410832-20894512-beb7-4d5e-90cc-27fd23da18e2.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
