### ISSUE TITLE
AR3 MLRS, export version of PHL-16

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1980]
### DB Selector

DB3K

### Hypothetical

No

### Name

AR3 MLRS

### Facility Type

Arty

### Country

United Arab Emirates, UAE

### Service

Army

### In Commission

-

### Dispersion Radius (m)

80

### Sensors

-

### Mounts

6x AR3 MLRS (each of 8x 370mm BRE6 Rocket /2x Fire Dragon 480)

### Magazines

24x Fire Dragon 480
144x 370mm BRE6 Rocket

### Sources

https://www.globalsecurity.org/military/world/china/ar-3.htm
https://twitter.com/Defence_IDA/status/1629011378261446656

**Comment by LuigiP57** [comment]
#1978

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
