### ISSUE TITLE
South Korea, KDX-3 Batch 2 rename

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1981]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3622

### Summary of Changes

Name change: DDG 995 Jeongjo the Great [KDX-3 Batch 2]

### Sources

https://en.wikipedia.org/wiki/Sejong_the_Great-class_destroyer
https://www.thedefensepost.com/2022/07/29/south-korea-aegis-destroyer/

**Comment by tbrandon517** [comment]
May have been handled by #1607 for v496.

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
