### ISSUE TITLE
R-77-1 missile

### ISSUE THREAD

**Issue by Test229** [PygmalionOfCyprus/cmo-db-requests#1987]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2056 

### Summary of Changes

Update the range to be 39nm and maybe add lofting to its property. (Sorry but not quite sure which flag controls the lofting behavior for the missiles.)

### Sources

https://www.youtube.com/watch?v=vD98yrCqUVQ
https://www.reddit.com/r/aviation/comments/v34dws/su35s_firing_r771_revealing_the_range_of_the/
Given that the launch parameters are already kinda optimal, 
![R-77-1-1](https://user-images.githubusercontent.com/74587714/183568402-4014409e-b9be-41b5-8559-d066cd79c392.png)
 (Shooter: M1.1 35000fts Target: about 35000fts Max range (left side label): slightly above 70)FWIW we can use this as the max range for the missile.
And in this picture, you can see the missile going up.
![R-77-1-2](https://user-images.githubusercontent.com/74587714/183563845-d5a1cd4b-bb71-4031-abcf-ed6de931f9a0.png)

**Comment by LuigiP57** [comment]
Maybe the DLZ/NEZ range, not the Max range.

**Comment by LuigiP57** [comment]
![image](https://user-images.githubusercontent.com/107970049/183564713-938ad594-a8bb-42f2-8845-18075bcaeaca.png)

**Comment by LuigiP57** [comment]
When countering targets with different agility, the so called "Max range" changes, it can't be easily defined.

**Comment by Test229** [comment]
I don't think so, if you take a look at the bottom right corner, it says TTT about 80 secs, that's already just slightly below the max battery life for missiles. (Usually 80-90secs IIRC)

**Comment by LuigiP57** [comment]
> I don't think so, if you take a look at the bottom right corner, it says TTT about 80 secs, that's already just slightly below the max battery life for missiles. (Usually 80-90secs IIRC)

I got it

**Comment by KLABDB3K** [comment]
Leave it at 110 km as per every open source document about the system . The simulations physics model will recreate the true range based on target amd launcher patameters and if you are going to alter it so dramatically for the R-77-1 standby to have to revisit and alter every AAM missile in the DB whose exact specifications and performance are state secrets.

**Comment by Test229** [comment]
> Leave it at 110 km as per every open source document about the system . The simulations physics model will recreate the true range based on target amd launcher patameters and if you are going to alter it so dramatically for the R-77-1 standby to have to revisit and alter every AAM missile in the DB whose exact specifications and performance are state secrets. 

"Leave it at 110 km as per every open source document about the system"

- But now we have better open sourced data?

"The simulations physics model will recreate the true range based on target amd launcher patameters" 

- I don't think the the range is quite correct now. But will double check.

"if you are going to alter it so dramatically for the R-77-1 standby to have to revisit and alter every AAM missile"

- Sorry but I don't quite get it? Yes other missiles might be wrong, but at least we can try to get this one correct? Maybe it's a big change but I think as long as we are correcting this then it doesn't matter.

**Comment by HVAA** [comment]
Mistaking launching range, for actual max range.  Plus he employs 'shoot, shoot, shoot, dont bother to look', so half his BVR loadout against a single target and doesnt even bother to support the missiles in flight like he could with his sophisticated SU-35S and IRBIS.  Seems like they have a whacky doctrine than any use of the missiles Vympel might recognise. Nor is it any engagement strategy a decent fighter pilot would recognise.

**Comment by KLABDB3K** [comment]
> > Leave it at 110 km as per every open source document about the system . The simulations physics model will recreate the true range based on target amd launcher patameters and if you are going to alter it so dramatically for the R-77-1 standby to have to revisit and alter every AAM missile in the DB whose exact specifications and performance are state secrets.
> 
> "Leave it at 110 km as per every open source document about the system"
> 
> * But now we have better open sourced data?
> 
> "The simulations physics model will recreate the true range based on target amd launcher patameters"
> 
> * I don't think the the range is quite correct now. But will double check.
> 
> "if you are going to alter it so dramatically for the R-77-1 standby to have to revisit and alter every AAM missile"
> 
> * Sorry but I don't quite get it? Yes other missiles might be wrong, but at least we can try to get this one correct? Maybe it's a big change but I think as long as we are correcting this then it doesn't matter.
The whole issue is the "it depends" quandary of the mutliple variables which determine how far "max range" really is. 
This isnt better data, its a single source interpretation of a HUD read out which we are assuming hasn't been through a censor to ensure that exactly the sort of critical secret information isn't divulged.

**Comment by Test229** [comment]
> > > Leave it at 110 km as per every open source document about the system . The simulations physics model will recreate the true range based on target amd launcher patameters and if you are going to alter it so dramatically for the R-77-1 standby to have to revisit and alter every AAM missile in the DB whose exact specifications and performance are state secrets.
> > 
> > "Leave it at 110 km as per every open source document about the system"
> > 
> > * But now we have better open sourced data?
> > 
> > "The simulations physics model will recreate the true range based on target amd launcher patameters"
> > 
> > * I don't think the the range is quite correct now. But will double check.
> > 
> > "if you are going to alter it so dramatically for the R-77-1 standby to have to revisit and alter every AAM missile"
> > 
> > * Sorry but I don't quite get it? Yes other missiles might be wrong, but at least we can try to get this one correct? Maybe it's a big change but I think as long as we are correcting this then it doesn't matter.
> 
> -The whole issue is the "it depends" quandary of the mutliple variables which determine how far "max range" really is. 
> This isnt better data, its a single source interpretation of a HUD read out which we are assuming hasn't been through a censor to ensure that exactly the sort of critical secret information isn't divulged.
> By example the R73 saga is well documented by Polish tests which have e become open source, from memory in the worse case its range drops to as low. as 6km low level stern chase against a small target but best case high altitude high speed release at a big target it rises to the "advertised" 30km.  
> Its an opinion not a criticism of the request. 
> 

Thanks for the clarification. Yeah I understand your point, yes we do not have a launch envelop chart for this missile, the reason I think we could use this range is that for the AAM ranges we are using in game, if the shooter is at 36000ft and 480kts, it should be the max range for a target flying towards you at 36000ft and 350kts, which is very similar to the parameters in the given source. And I tried to replicate the shot in the game, it only takes 42 sec for the missile to hit the target, which is kinda a huge difference compared to the 80ish sec TTT in the video. That's why I am proposing this.

**Comment by PygmalionOfCyprus** [comment]
I have to agree with the others, I don't think this on its own is enough to change the missile max range. Assuming the video is unedited, there are still a lot of unknowns here. IMO this is an example of a pilot firing at/beyond max range with intentionally trash shots purely to try and get the enemy to evade and bleed energy/break lock/etc. (I'm giving the pilot the benefit of the doubt -- it's also possible he's just incompetent.) That could also explain why he doesn't bother trying to support the missiles, @HVAA. 

Or, maybe he's firing at greater-than-max range against a closing target -- a sort of "kinematic range" for missiles. Who knows. The point is, a HUD video alone isn't enough to warrant changing numbers on an otherwise well-documented system.

I do appreciate the enterprising spirit and attempt to glean some useful info from the video, though. Markings of an OSINT researcher! Keep it up. 😃

...And, if we're wrong down the line, you get the greatest prize of all: being able to smugly say "I told you so." 😉
