### ISSUE TITLE
PL-15/PL-15E AAM radar seeker update

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1989]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3413 3896, sensor 5790

### Summary of Changes

**Active radar seeker range change to: 12nm (same as R-77M)**
As a late 2010s tech "cutting edge" air-to-air missile, I have surprisingly found that its radar seeker performance (just 7.5nm) is inferior to the one on early 1990s tech R-77, way behind the contemporary AIM-120D/Meteor/R-77-1/R-77M. From my perspective, making a 20km+ range radar seeker won't be a problem for China.

### Sources

https://www.globalsecurity.org/military/world/china/pl-15.htm
(Most from reasonable speculation)

**Comment by PygmalionOfCyprus** [comment]
Yeah, fair enough. Probably a remnant from an early base copy-over. Fixed 496.

**Comment by LuigiP57** [comment]
#2081
