### ISSUE TITLE
China, YJ-83B SSM, Shipborne CM-802B, IIR Seeker installed

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1991]
### DB Selector

DB3K

### Baseline

weapon 3943

### Hypothetical

No

### Name

YJ-83B

### Length (m)

same as yj-83kb

### Width/Span (m)

same as yj-83kb

### Diameter (m)

same as yj-83kb

### Weight (kg)

same as yj-83kb

### Range (nm)

same as yj-83kb

### Launch Altitude / Depth (ft)

-164ft~65000ft

### Warhead

same as yj-83kb

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### Sensors

same as yj-83kb

### Sources

https://www.sinodefenceforum.com/t/plan-anti-ship-surface-missiles.6345/page-107
![image](https://user-images.githubusercontent.com/107970049/183821208-084d7783-f0bc-488f-bcbe-be77872aefa5.png)
![image](https://user-images.githubusercontent.com/107970049/183821262-03d2db7c-8757-42b6-aa00-895acd7dbdae.png)
![image](https://user-images.githubusercontent.com/107970049/183821231-9054e646-78c2-4ae4-b82a-069c6b7047b4.png)

**Comment by LuigiP57** [comment]
#1992 #1993

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
