### ISSUE TITLE
China, Type 054A++ FFG, 2021, with YJ-83B onboard

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1992]
### DB Selector

DB3K

### DBID to Copy

ship 2495

### Hypothetical

No

### Name

Type 054A++ Jiangkai II, YJ-83B

### Country

China

### Service

Navy

### In Commission

2021

### Loadout Options

SSM Change to 8x YJ-83B

### Sources

https://en.wikipedia.org/wiki/Type_054A_frigate
https://www.sinodefenceforum.com/t/plan-anti-ship-surface-missiles.6345/page-107

**Comment by PygmalionOfCyprus** [comment]
For all the Type 054s or just the 054++?

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Big mess with the YJ-83B versions. But handled.
