### ISSUE TITLE
China, Type 056A FFL, 2021, with YJ-83B onboard

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1993]
### DB Selector

DB3K

### DBID to Copy

ship 2703

### Hypothetical

No

### Name

Type 056A Jiangdao, YJ-83B

### Country

China

### Service

Navy

### In Commission

2021

### Loadout Options

SSM change to 4x YJ-83B

### Sources

https://en.wikipedia.org/wiki/Type_056_corvette
https://www.sinodefenceforum.com/t/plan-anti-ship-surface-missiles.6345/page-107

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Big mess with the YJ-83B versions. But handled. Also added the IIR version to the Type 022 as of 2023.
