### ISSUE TITLE
China, WZ-8, currently unusable.

### ISSUE THREAD

**Issue by HoneyFox** [PygmalionOfCyprus/cmo-db-requests#1995]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3720, Comm 366, Comm 367, Sensor 910, Sensor 5771

### Summary of Changes

WZ-8 now uses WZ-8 datalink (100nm range) which only connects to its launching aircraft. Due to its high velocity (2255kts), the datalink will simply break connection after ~3 minutes unless the launching aircraft launches it towards a location close enough (~100nm) and player controls the drone to stay inside the range. I assume that the broken datalink will stop it from sending back info of contacts it detected, is that correct?

Potential fixes:
- Increase datalink max range to a more "reasonable" value. (but no source available)
- WZ-8 should be able to store target info it detects when datalink is not available. and later when it flies back closer to friendly platforms, make it possible to re-establish datalink and share the info (although aged). (Don't know if CMO supports this?)

---

WZ-8 can hardly detect any surface contact even if player controls it to do multiple passes above the target. (with datalink connected)

Potential reasons:
- Does sensor max range take altitude difference into account? Since it flies at 135,000ft altitude (~22nm), if the sensor's max range is smaller than that, it will never be able to detect surface contacts.
- Does CMO have min/max elevation angle limit for sensors so that one sensor cannot look downwards a lot?

### Sources

No source available. This is only reporting that it's unusable in the game.

**Comment by Jkryos** [comment]
This was fixed with the addition of units as payload and the creation of a "Aircraft" WZ-8.
