### ISSUE TITLE
GMLRS-Extended Range missile for Himars and MLRS

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#1996]
### DB Selector

DB3K

### Baseline

#3136 - M30A2 GMLRS ER [Alternative Warhead]

### Hypothetical

No

### Name

ERGMLRS

### Length (m)

from #3136 - M30A2 GMLRS ER

### Width/Span (m)

from #3136 - M30A2 GMLRS ER

### Diameter (m)

> than #3136 - M30A2 GMLRS ER The proposed ER GMLRS ECP expands the rocket motor diameter to increase range, modifies the control section for enhanced maneuverability, and incorporates a side-mounted proximity sensor to enable higher height-of-burst.

### Weight (kg)

from #3136 - M30A2 GMLRS ER

### Range (nm)

150 km

### Target Speed (kts)

Mach 3.8 @ burnout and hit the ground at a little over Mach 1.3

### Launch Altitude / Depth (ft)

31km @ 70 seconds after launch

### LaunchSpeed (kts)

Mach 3.8 @ burnout

### Warhead

 The ER GMLRS uses either a Unitary or AW warhead variant to engage point and area targets.

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway, Radar

### CEP (m)

<1 meter (https://twitter.com/MIL_STD/status/1551223890201874437)

### Sensors

 The ER GMLRS uses a GPS-aided inertial navigation system,
aft-mounted control actuation system, 

### Weapon Codes

Bearing-Only Launch (BOL), Ballistic Missile or Rocket Booster, Weapon - INS w/ GNSS Navigation

### Comments

While the GMLRS-Extended Range ⬆️the range of the current Guided MLRS from 84 to 150 km, it does not reduce the number of rounds per pod (still 6).

"Flight 1 [#TCGMLRS](https://twitter.com/hashtag/TCGMLRS?src=hashtag_click) (precursor to [#ERGMLRS](https://twitter.com/hashtag/ERGMLRS?src=hashtag_click)) was 112 km [112.9km].. We had burnout at Mach 3.8, hit apogee at the 70 second mark/31 km high..we hit the ground at a little over Mach 1.3" ~ 2018

Production ERGMLRS has since demonstrated 135km in testing & has a max range of 150km.

The US Army has requested 4,674 [#GMLRS](https://twitter.com/hashtag/GMLRS?src=hashtag_click) rounds as part of its Fiscal Year 2023 budget request. FY-2023 is also when Lockheed Martin is expected to cut the ER-GMLRS into production with the first LRIP lot (FY-2023) production of 120 rounds.

Finland is getting the 150 km ranged Extended Range-GMLRS for its M-270 MLR system. Deliveries are expected to begin in **2025**.  

Estonia becomes the second [#FMS](https://twitter.com/hashtag/FMS?src=hashtag_click) customer to be approved for the 150 km Extended Range

### Sources

https://lockheedmartin.com/en-us/products/guided-mlrs-unitary-rocket.html
https://twitter.com/MIL_STD/status/1551218545467437057
https://twitter.com/MIL_STD/status/1550988224608157696
https://twitter.com/MIL_STD/status/1541752280625557504
https://twitter.com/MIL_STD/status/1492147665206972419
https://twitter.com/MIL_STD/status/1548135352526786562
https://twitter.com/MIL_STD/status/1551223890201874437
![FLUsSHKXMAgSvsT](https://user-images.githubusercontent.com/60408110/183925318-4b8e7145-612c-48df-9da3-49c57c646e91.jpg)
https://image2.slideserve.com/4254608/slide3-n.jpg (see also dud-rate for earlier versions)
https://www.dote.osd.mil/Portals/97/pub/reports/FY2020/army/2020gmlrs.pdf?ver=SfzIiCDdq9xYX1cPWKkUBg%3d%3d

**Comment by PygmalionOfCyprus** [comment]
Related to #1521, #1520

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
