### ISSUE TITLE
Propulsion Performance, Batteries, 0 consumption at full throttle

### ISSUE THREAD

**Issue by HoneyFox** [PygmalionOfCyprus/cmo-db-requests#1997]
### DB Selector

DB3K

### Affected DBID(s)

Propulsion 3107, 3176, 3177, 3178, 3179

### Summary of Changes
Current:
Creep - 1.0 consumption
Cruise - 4.0 consumption
Full - 0.0 consumption

Expected:
Creep - 1.0 consumption
Cruise - 4.0 consumption
Full - 10.0 consumption
### Sources

Thrust power usually has nearly cubic relationship to speed. 10.0 is a rough estimation based on that and the relationship of speed & consumption rate of the previous two throttle settings.

Propulsion 3177 "Variable Buoyancy Propulsion" works differently from other propulsion systems:
It works by using piston to squeeze in/push out water to/from its buoyancy tank or to use external bladder tank to change its buoyancy, and using glide fins to get propulsion force when vessel dives/rises due to buoyancy change.
Still it needs larger buoyancy-force adjustment range to achieve higher speed so it will still consume more battery when running fast.

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Re: 3177, yeah, we have an internal ticket open for proper modelling of undersea gliders, etc. but at the moment they're handled...well, as you see, in sort of a rudimentary fashion.
