### ISSUE TITLE
Add Hypothetical Phase II Iowa BB Conversions

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#200]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

Iowa BB Phase II Amphibious Conversion

### Class

Iowa 

### Country

United States

### Service

Navy

### In Commission

1989

### Length (m)

As DBID 1161 BB-61 Iowa

### Beam (m)

As DBID 1161 BB-61 Iowa

### Draft (m)

As DBID 1161 BB-61 Iowa

### Standard Displacement (t)

As DBID 1161 BB-61 Iowa

### Full Displacement (t)

As DBID 1161 BB-61 Iowa

### Empty Displacement (t)

As DBID 1161 BB-61 Iowa

### Complement

As DBID 1161 BB-61 Iowa

### Max Sea State

As DBID 1161 BB-61 Iowa

### Primary Propulsion Type

Steam

### Propulsion

As DBID 1161 BB-61 Iowa

### Fuel Capacity (kg)

As DBID 1161 BB-61 Iowa

### Flank Speed (kt)

As DBID 1161 BB-61 Iowa

### Range (nm) at Speed (kt)

As DBID 1161 BB-61 Iowa

### Sensors

As DBID 1161 BB-61 Iowa plus NTU SAM fire control

### Mounts

All Concepts
-Six Mk7 16-inch/50 guns that could fire a variety of modern munitions

Martin Marrietta Concept:
- A 320-tube vertical launch system (VLS) capable of firing Tomahawks, Standard Missiles, ballistic missiles, and the Army Tactical Missile System family
- 6x 5-inch/38-caliber twin mounts (3x port, 3x starboard retained
- 4x Phalanx CIWS (1 port, 1 starboard, 1 centerline behind stacks above flight deck, 1 centerline above bridge)

Gene Anderson’s Concept 
- 1x Mk26 Launcher Forward (as on Virginia CGN)
- 4x 5"/54 caliber Mark 45 gun (2 port, 2 starboard)
- 2x 8"/55 caliber Mark 71 gun (1 port, 1 Starboard)
- 4x Phalanx CIWS (2 port, 2 starboard)
- 2x Sea Sparrow Launcher (port and starboard stern)

Harold Pulver’s Concept:
- 1x Mk26 Launcher Forward (as on Virginia CGN)
- 4x 5"/54 caliber Mark 45 gun (2 port, 2 starboard)
- 3x Phalanx CIWS (1 port, 1 starboard, 1 centerline behind stacks above flight deck)
- 2x Sea Sparrow Launcher (port and starboard stern)

### Aircraft & Docking Facilities

Martin Marrietta Concept:
2 angled decks both with ski jumps for V/STOL ops port and starboard.
1 Elevator on Centerline behind VLS.

Gene Anderson’s Concept:
1 Deck Edge Elevator Starboard
1 Main Angled Deck to port with Catapult for CATOBAR ops
1 Secondary angled deck to starboard with ski jump for V/STOL ops.

Harold Pulver’s Concept:
1 Deck Edge Elevator Starboard
1 Main Angled Deck to for V/STOL ops as on US LHA/LHD types
5 Spots for Large assault helos.

Could use CWDB DBID #669 Amphibious Iowa for capacity for A/C and boats davits/capacity.

### Comms/Datalinks

As DBID 1161 BB-61 Iowa and NTU ships.

### Ship Codes

Degaussed Steel Hull

### Comments

Phase II would have been dramatic and transformative. As Myers described later, among other modifications, the converted interdiction/assault ships would have offered:

Six 16-inch guns that could fire a variety of modern munitions
A 320-tube vertical launch system (VLS) capable of firing Tomahawks, Standard Missiles, ballistic missiles, and the Army Tactical Missile System family
Flight and hangar decks in place of the after turret, for various mixes of AV-8B Harriers, heavy-lift and attack helicopters, and MV-22 Ospreys
Accommodations for SEALs and 800 Marines for short periods
Logistics spaces and machine shops
Medical facilities and operating rooms

Could use CWDB DBID #669 Amphibious Iowa for capacity for A/C and boats.

### Sources

https://ipmsusa.org/reviews/features/Heavy_Assault_Ship_Conversion/Heavy_Assault_Ship_Conversion.htm
https://www.navalhistory.org/2019/06/28/the-iowa-class-battlecarrier-a-design-that-never-took-off
https://www.facebook.com/groups/946315158890663/permalink/1667107696811402/
https://www.globalsecurity.org/military/systems/ship/bb-61-av.htm

Gene Anderson’s Concept:
![img021](https://user-images.githubusercontent.com/99599482/154508579-c264f0e7-1d8b-41a9-b328-781e469083bc.jpg)

Harold Pulver’s Concept:
![Untitled](https://user-images.githubusercontent.com/99599482/154510415-ac78aae1-2bb1-4d51-a389-d40989cc9c8a.jpg)

Martin Marrietta Concept:
![US-MdAnUSNI-158023004-1](https://user-images.githubusercontent.com/99599482/154511497-b6ba5a4f-7ef9-426e-a321-696e4628c313.jpg)
![US-MdAnUSNI-158023002-1](https://user-images.githubusercontent.com/99599482/154512366-9b6e4556-37b0-4b1d-b258-c5a6f3dafc6b.jpg)
![img014](https://user-images.githubusercontent.com/99599482/154512447-8141e088-f101-457e-87b0-b8a724856602.jpg)
![img016](https://user-images.githubusercontent.com/99599482/154512668-afaaec72-8894-4ccc-a8e2-40daf08c8e34.jpg)

**Comment by tbrandon517** [comment]
Ballistic missiles for Martin-Marietta's posdibly RGM-109Z as used in current Arsenal Ship in DB.

**Comment by KushanGaming** [comment]
![post-30410-0-83657800-1327022848](https://user-images.githubusercontent.com/62118287/173683572-7c74c530-8471-4f09-9a30-643a99fb5e3b.jpg)

**Comment by KushanGaming** [comment]
Completed for DB495.

**Comment by tbrandon517** [comment]
Just a note that in game the Martin Marrietta has the 320 VLS cells per the source but it is labeled as having 360 cells.

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=385869&p=5013767#p5013767
