### ISSUE TITLE
SS 508 Sekiryu [Soryu class]

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2001]
### DB Selector

DB3K

### DBID to Copy

Submarine509, 603

### Hypothetical

No

### Name

SS 508 Sekiryu 

### Country

Japan

### Service

Navy

### In Commission

2017

### Sensors

-

### Mounts

Add 1x "TCM" launcher with 4x MoD requested in  #2000 
Signal ejector should have ZLQ-2B requested in  #1999

### Other Changes

We have two variants for this, one with Harpoon IC and another with Harpoon2.

### Sources

https://www.sankei.com/article/20170329-FTK2ZN7JUFKTJMTX2KH72WXLV4/

https://ja.wikipedia.org/wiki/%E3%81%9D%E3%81%86%E3%82%8A%E3%82%85%E3%81%86%E5%9E%8B%E6%BD%9C%E6%B0%B4%E8%89%A6

**Comment by PygmalionOfCyprus** [comment]
Slightly confused, is the Sekiryu thus supposed to be carrying Harpoon IC or Harpoon 2? Or should all the Soryus be able to carry both? Basically the main difference here is the addition of the TCM launcher, right?

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
