### ISSUE TITLE
Iran - Qiam-1 SRBM/SSM updates

### ISSUE THREAD

**Issue by Halberx** [PygmalionOfCyprus/cmo-db-requests#2003]
### DB Selector

DB3K

### Affected DBID(s)

Facility 2593

### Summary of Changes

Name change from Qiam-1 to Qiam-2 (MaRV-variant), increase of range from 400 nm to 540 nm, velocity increase from 4500 kts to 5700 kts, length from 10.6 m to 11.8 m, weight from 6155 kg to 7029 kg, CEP from 10 m to 50 m and warhead is a (unitary) conventional, 600 kg HE as of latest Iranian Ministry of Defence data. The length increased while the warhead decreased compared to the previous production model. Current representation of the Qiam-1 in the simulator requires additional information which I have shared here, with additional validation of specifications on previous Qiam-1 production model ready to be sent if needed.

### Sources

https://t.me/iran_militarynews/2507 (specifications under BM-1000 (=Qiam-2) designation)

**Comment by PygmalionOfCyprus** [comment]
Whoops, I'm a little confused. Is this a request to change the current Qiam-1 to the Qiam-2, or to add a new weapon to represent the Qiam-2 based on the Qiam-1 (which is how I read it)?

**Comment by Halberx** [comment]
I would add the Qiam-2 as a new weapon based on the Qiam-1 with the specifications listed above and if it's worth the effort you could alter the current Qiam-1 with the following specifications;
- Length from 10.6m to 11.5m
- Warhead is 650kg HE
- CEP is 450m

As a positive effect, the Houthi Burkan-2H SSM Bn (Facility 3178) in the database also benefits from this change as well. I would like to contribute more for the database if you may :)

**Comment by PygmalionOfCyprus** [comment]
Handled 499 as part of our ongoing major review of Iran.
