### ISSUE TITLE
Cuban OSA II 212 [Pr.205ER] Square Tie Radar arc is broken

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2004]
### DB Selector

DB3K

### Affected DBID(s)

2175

### Summary of Changes

Make cuban square tie radar arc 360.

### Sources

![OsaIIRadarArc](https://user-images.githubusercontent.com/7115648/184495162-97c3a696-a8da-425a-a72b-2fc400c392d1.jpg)

**Comment by PygmalionOfCyprus** [comment]
Looks like the radar arcs got swapped with the Bell Tap's for some reason. Fixed 496.
