### ISSUE TITLE
Cuban Osa I has no fuel

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2005]
### DB Selector

DB3K

### Affected DBID(s)

2013

### Summary of Changes

Add fuel

### Sources

![OsaFuel](https://user-images.githubusercontent.com/7115648/184495245-41421cd5-4ce9-4ce1-8d0b-c9c8133fc42b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Whoops...cross-DB copy-over error. It _had_ fuel, but the CWDB ID, so in DB3K it had avgas instead of diesel. Fixed 496.
