### ISSUE TITLE
Add hypothetical Wartime SSM fit for Legend Class Cutters

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#201]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

WMSL 750 Bertholf [Legend Class, National Security Cutter] United States - 2008), Potential wartime SSM Fit

### Class

Legend Class NSC

### Country

United States

### Service

Coast Guard

### In Commission

2008

### Length (m)

As DBID 2431

### Beam (m)

As DBID 2431

### Draft (m)

As DBID 2431

### Standard Displacement (t)

As DBID 2431

### Full Displacement (t)

As DBID 2431

### Empty Displacement (t)

As DBID 2431

### Complement

As DBID 2431

### Max Sea State

As DBID 2431

### Primary Propulsion Type

Diesel

### Propulsion

As DBID 2431

### Fuel Capacity (kg)

As DBID 2431

### Flank Speed (kt)

As DBID 2431

### Range (nm) at Speed (kt)

As DBID 2431

### Sensors

As DBID 2431

### Mounts

As DBID 2431
plus

2x Quad SSM (Harpoon or NSM)

### Aircraft & Docking Facilities

As DBID 2431

### Comms/Datalinks

As DBID 2431

### Comments

Request potential wartime fitting for Legend class cutters with SSM such as NSM or Harpoon. May also be applicable for new Heritage Class Offshore Patrol Cutters or Older Famous/Bear class WMECs which sources indicate the WMECs were designed as FFBNW Harpoonand Phalanx. Applicable as some other CG or Border guard ship entries have potential wartime fit variants.

### Sources

https://www.thedrive.com/the-war-zone/30604/coast-guard-cutters-once-carried-harpoon-anti-ship-missiles-and-they-could-again

https://www.wearethemighty.com/mighty-trending/coast-guards-new-cutters/

https://blog.usni.org/posts/2021/01/05/modern-day-beach-patrol-add-coastal-defense-cruise-missiles-to-the-coast-guards-inventory

https://chuckhillscgblog.net/2016/09/29/what-might-a-wartime-opc-weapons-fit-look-like/

https://chuckhillscgblog.net/2019/09/29/navy-this-is-coast-guard-we-need-to-talk/

**Comment by KushanGaming** [comment]
Done for DB495.
