### ISSUE TITLE
Japan, YS-11EB, update

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2011]
### DB Selector

DB3K

### Affected DBID(s)

3387

### Summary of Changes

General
---
Year: 1995-
Number: 4x
Service ceiling: 9000m (approx 30,000ft) This is because YS-11EA/EBs have upgraded engines)

Sensor
---
J/ALR-2 is the name of the ELINT/COMINT sensor, Early 1990's tech (because YS-11EB's commission year is 1996)  
J/ALR-2 got upgrade in 2015, for BMD capability... I believe it is for telemetry trucking?

Comms
---
add secured/unsecured HF Radio
Secured UHF/VHF Radio (while this is military Aircraft)

### Sources

Wikipedia
https://ja.wikipedia.org/wiki/YS-11#%E8%88%AA%E7%A9%BA%E8%87%AA%E8%A1%9B%E9%9A%8A

ALR-2 BMD upgrade
https://www2.njss.info/offers/view/10404257

Commission Year
http://hikokikumo.net/His-C&M-YS-000-12-JASDF.JMSDF-.htm#55

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
