### ISSUE TITLE
Japan, YS-11EA, Correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2013]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3386

### Summary of Changes

General
---
Year: 1991-
Service ceiling: 9000m (approx 30,000ft) This is because YS-11EA/EBs have upgraded engines)

COMMS
---
J/ALQ-7 is the name for OECM system, Early 90's tech

Comms
---
add secured/unsecured HF Radio
Secured UHF/VHF Radio (while this is military Aircraft)

### Sources

Wikipedia
https://ja.wikipedia.org/wiki/YS-11#%E8%88%AA%E7%A9%BA%E8%87%AA%E8%A1%9B%E9%9A%8A

Commission Year
http://hikokikumo.net/His-C&M-YS-000-12-JASDF.JMSDF-.htm#62

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
