### ISSUE TITLE
Japan, add MST 464 Bungo, update MTS 463 Uraga

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2014]
### DB Selector

DB3K

### DBID to Copy

Ship 842

### Hypothetical

No

### Name

MST 464 Bungo

### Country

Japan

### Service

Navy

### In Commission

1998

### Number in Service

1x

### Sensors

Delete OPS-14C and replace by OPS-14B(ID 2993), should fit for MST 463 Uraga

Delete OPS-18 and replace by OPS-39C(Base: ID 2434), should fit for MST 463 Uraga

add FCS-2-22F(low type, Gun Director, Sensor Group)
Requested in #2022

### Mounts

1x 76mm/62 OTO Melara Compat (Mount ID 550?)

### Other Changes

Uraga/Bungo can store and lay 230x mines... not sure the what they are... I'll make separate request once I got information.

Difference between Uraga and Bungo is 76mm Gun. Uraga is FFBNW 76mm but she did not get it until this day.

FCS-2 FCS is actually sensor group of Radar, TV, and Rangefinders, which is actually I did not know, so I guess I'll make request once I gather necessary information.

### Sources

wikipedia
https://ja.wikipedia.org/wiki/%E3%81%86%E3%82%89%E3%81%8C%E5%9E%8B%E6%8E%83%E6%B5%B7%E6%AF%8D%E8%89%A6

FCS-2 wikipedia
https://ja.wikipedia.org/wiki/FCS-2

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
