### ISSUE TITLE
AGM-88B For Ukrainian Fighters

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#2025]
### DB Selector

DB3K

### User(s)

Ukrainian SU-24, Su-27, MiG-29

### Weapons Carried

- 2 x AGM-88B (to replace inboard pylon weapon from a suitable loadout

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As per the load you copy from

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Looking at the photos of them being launched from more traditional carriers, these would only be suitable for wing pylons. As the inners on all aircraft requested are stressed for the heavier weapons, this would be the probable location.

### Sources

https://www.thedrive.com/the-war-zone/new-evidence-of-agm-88-anti-radiation-missile-use-by-ukraine-emerge
https://edition.cnn.com/2022/08/08/politics/anti-radar-missiles-ukraine-russia-pentagon/index.html (read down)
https://www.forbes.com/sites/davidaxe/2022/08/11/ukrainian-jets-are-firing-american-anti-radar-missiles/?sh=b77d58131a98
https://mezha.media/en/2022/08/09/agm-88-harm-anti-radar-missile-a-solution-or-more-questions/

**Comment by tbrandon517** [comment]
Confirmation of use from Ukrainian Mig-29s

https://www.thedrive.com/the-war-zone/ukrainian-mig-29s-are-firing-agm-88-anti-radiation-missiles

**Comment by KLABDB3K** [comment]
Just an observation but this is a very swift turn round for weapon integration but the MiG-29 has been in the NATO inventory as an active type for decades so plenty of time for this to have been tried out semi secretly for users like Poland. The Su-24 and Su-27 on the other hand are much less likely candidates for HARM integration as they are not overtly in service in a NATO air arm and making it not time or cost effective to have trialled in advance? I have of course been known to be wrong! 😁

**Comment by PygmalionOfCyprus** [comment]
Closing as duplicate despite earlier posting, see comment on #2057.
