### ISSUE TITLE
Add 96L6-tsp acquisition radar to S-350 Battery (Visually Confirmed in 2022 and 2020)

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2031]
### DB Selector

DB3K

### Affected DBID(s)

2089

### Summary of Changes

Airbase in Taganrog is defended by S-350 launchers with a visually confirmed 96L6-TSP (upgraded 96L6) in active service as an acquisition radar for the battery. Just as 96L6 acts as acquisition radar and cues 92N6 FCR of S-400, 96l6-tsp acts similarly and cues main FCR of S-350 50N6A.
![96l6 with s-350](https://user-images.githubusercontent.com/108960393/185262098-ac5dc7f6-6edc-4e5a-ae76-e7c129e5ae2b.jpg)

96L6-tsp is assumed to be an AESA upgrade to the 96L6 meant for the S-500 system but can work with S-350, S-300, and S-400 batteries as well. Confirmed to be working with S-350 system. 

(SINCE 96L6-tsp is not in the game yet, I will create a separate request for it)

1.It is presumed the 96L6 has a max range of 500km since  S-500 has a max ANTI-AIR range of 500km. So a max range of 270nm would be appropriate. I will use copy/entry form for the 96L6-tsp. 
2. We can also presume it has the same operating frequencies (2-3 GHZ) old S-band and is E band similar to standard 96L6. Only differences being longer range and having an AESA antenna design.

Once estimated specs become more readily available it can always be updated.

Here is the 96L6-TSP confirmed with S-350 battery in 2020
![96L6-tsp with S-350 (2020)](https://user-images.githubusercontent.com/108960393/185262741-764f0de1-bd79-4534-be55-3f1844f3b087.png)

Here is a news article about 96L6-tsp
![ER8DjegU0AAaS8e](https://user-images.githubusercontent.com/108960393/185262804-4d85e40f-f62b-43c1-b65e-652e9230490a.jpg)

https://www.ibtimes.com/russia-sends-its-new-ready-fire-s-350-defense-system-protect-air-base-near-ukraine-3602359

### Sources

https://twitter.com/KwasekTomasz/status/1559631980756717574

https://twitter.com/RALee85/status/1558892433437609985

https://twitter.com/owarino_outsuke/status/1558999177937694720/photo/1

https://twitter.com/guyplopsky/status/1233708740513132544?lang=en

https://www.ibtimes.com/russia-sends-its-new-ready-fire-s-350-defense-system-protect-air-base-near-ukraine-3602359

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
