### ISSUE TITLE
Add 96L6-tsp (UPGRADED 96L6 Cheese Board)

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2032]
### DB Selector

DB3K

### DBID to Copy

3131

### Hypothetical

No

### Name

96L6-tsp

### Country

Russia

### Service

Airforce

### In Commission

2020-present

### Number in Service

unknown

### Other Changes

96L6-tsp is an upgraded 96L6 variant designed for S-500, but has recently been spotted in active service deployed with S-350 battery guarding Taganrog Airbase. It can also act as acquisition radar for S-300, S-400.

It is most likely an AESA antenna (looks to be such since it has a much larger thicker antenna than the standard 96L6) and since S-500 components are thought to be all AESA.
It also should have a max range of at least 500km (270nm) since the max REPORTED anti-air range of S-500 is 500km.
Also it is most likely E band (old S-band) just like the standard 96L6.
Changes can always be made once more details are known but this is a good start.

Summary of changes to be made:
-increase range to 270nm
-add AESA function
-also add to S-350 battery to act as an acquisition radar to cue 50N6A FCR (separate request made)

Here is 96L6-tsp deployed with active S-350 battery in 2022 
![96l6 with s-350](https://user-images.githubusercontent.com/108960393/185263615-c318f84e-6d7a-48bc-88bc-6dce3cef068a.jpg)

Here is 96L6-tsp positioned alongside S-350 launchers in 2020
![96L6-tsp with S-350 (2020)](https://user-images.githubusercontent.com/108960393/185263650-b38d7e7c-b02a-43c8-924a-050acb82f4f3.png)

Here is an article about 96L6-tsp. Apparently it has 3 other passive sensors called 96l6-VP but that is a request for another day ;)
![ER8DjegU0AAaS8e](https://user-images.githubusercontent.com/108960393/185263756-126ae709-3f51-4cb1-a52d-ea9d6f341d0a.jpg)

### Sources

https://www.ibtimes.com/russia-sends-its-new-ready-fire-s-350-defense-system-protect-air-base-near-ukraine-3602359

https://twitter.com/KwasekTomasz/status/1559631980756717574

https://twitter.com/RALee85/status/1558892433437609985

https://twitter.com/guyplopsky/status/1233708740513132544?lang=en

**Comment by PygmalionOfCyprus** [comment]
Thanks for opening the separate ticket! In this particular case I'm gonna close this and just use #2031 since you supplied the same info there.
