### ISSUE TITLE
Increase KH-47M2 Khinzal max speed to Mach 10

### ISSUE THREAD

**Issue by Nuclear-Monkeys** [PygmalionOfCyprus/cmo-db-requests#2033]
### DB Selector

DB3K

### Affected DBID(s)

3532

### Summary of Changes

Currently max speed of Khinzal missile is 4600 kts (Mach 6.85)

Please increase to 6670 kts (Mach 10). 

Majority of online forums and news sources estimate Mach 10 is the maximum reported speed. Wikipedia says Mach 12 but Mach 10 is more likely as most sources indicate it unlike the mach 12 figure.

### Sources

https://www.republicworld.com/world-news/russia-ukraine-crisis/what-is-kinzhal-hypersonic-missile-all-about-kremlins-latest-deployment-in-kyiv-articleshow.html

https://www.indiatimes.com/explainers/news/russias-advanced-hypersonic-kinzhal-missile-565510.html

https://theaviationist.com/2018/03/12/russia-test-fires-new-kh-47m2-kinzhal-hypersonic-missile/

https://www.cnbc.com/2022/03/22/hypersonic-missiles-why-would-russia-use-the-kinzhal-in-ukraine.html

https://missilethreat.csis.org/missile/kinzhal/

https://english.elpais.com/international/2022-03-23/russias-kinzhal-hypersonic-missile-what-is-it-and-how-does-it-work.html#:~:text=Once%20launched%2C%20a%20Kinzhal%20rapidly,maneuverability%2C%20make%20interception%20extremely%20difficult.

https://tass.com/defense/1425271

**Comment by PygmalionOfCyprus** [comment]
Handled 496.

**Comment by Nuclear-Monkeys** [comment]
> Handled 496.

Thank you
