### ISSUE TITLE
Increase Zircon max missile speed to mach 9

### ISSUE THREAD

**Issue by Nuclear-Monkeys** [PygmalionOfCyprus/cmo-db-requests#2034]
### DB Selector

DB3K

### Affected DBID(s)

3361

### Summary of Changes

Max speed in game is 4300 kts or mach 6.44
However most sources indicate Mach 8-9 is a max speed (5334-6000 kts)
Missile advocacy reports mach 8, while most other sources report mach 9.
The curreny estimate is anywhere between mach 8-9 
Maybe mach 8.5 for now?

### Sources

https://www.pbs.org/newshour/world/russian-navy-conducts-test-on-hypersonic-zircon-missile

https://www.reuters.com/world/europe/russia-says-its-completed-testing-hypersonic-zircon-cruise-missile-2022-06-01/

https://www.reuters.com/world/europe/russia-shows-off-zircon-hypersonic-cruise-missile-test-launch-sea-2022-05-28/

https://www.euronews.com/2022/05/29/russia-tests-hypersonic-zircon-missile-in-latest-display-of-military-capability

https://www.voanews.com/a/russia-says-latest-zircon-hypersonic-missile-test-successful/6331758.html

https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/russia/3m22-zircon/

https://www.business-standard.com/article/international/russian-forces-to-get-zircon-hypersonic-missiles-in-coming-months-putin-122073100924_1.html#:~:text=%22The%20duty%20area%20of%20the,of%20more%20than%201%2C000%20km.

https://en.wikipedia.org/wiki/3M22_Zircon

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
