### ISSUE TITLE
Patriot battery with LTAMDS (GhostEye) has secondary radars pointing at the wrong direction

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2035]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3546

### Summary of Changes

![ghost eye arcs](https://user-images.githubusercontent.com/111351574/185363835-3f08578e-3044-424e-ba32-59a849de8850.png)

Seems both primary array and secondary arrays are facing exactly in the same direction. 

The manufacturer mentions any direction (which implies 360). The photos on the site also confirm that. This radar is for example fulfilling Polish 'Wisla' armament program requirements and was selected for it's next stage (which requires 360 coverage).

So secondary arrays have to start pointing in such a way that they provide 360 coverage together with the main array. All of them (i.e. with a primary) are 120 degrees AESAs, which seems to be properly marked in the database, so only 'arc' positioning has to be fixed.

### Sources

https://www.raytheonmissilesanddefense.com/what-we-do/missile-defense/air-and-missile-defense-systems/ghosteye
https://defence24.pl/technologie/pierwszy-docelowy-radar-wisly-w-us-army

**Comment by PygmalionOfCyprus** [comment]
This is a limitation of ground-units-as-facilities. We don't have a way to handle a mount with multiple sensors that have different arcs. If I give it 360 coverage the main array will also get 360 coverage.

As a workaround I've added an extra mount to hold the secondary array. This will create more realistic coverage, but at the expense of now being an extra "vehicle" that needs to be destroyed (as opposed to real life, where a single vehicle carries both the main and secondary arrays and its destruction would blind the battery). It's not ideal, but we can't have it both ways so long as it's a facility and not a proper ground unit.

**Comment by rob76pl** [comment]
Ack and thank you. As a side effect of an extra vehicle now separate array damage is emulated (I guess).

Would you also mind fixing these new GhostEye arrays - they do not seem to be able to guide PAC-2 GEM+, which is a part of the battery. Unsure if they are capable of doing that IRL, but as GhostEye is a replacement for previous radar I would assume so.

**Comment by PygmalionOfCyprus** [comment]
>As a side effect of an extra vehicle now separate array damage is emulated (I guess).

True, though IRL pretty much any hit on the radar vehicle would probably knock out the whole set of arrays unless you were attacking with an exceptionally small warhead and got very unlucky (maybe only a single cluster bomblet hits the main array or something). This implementation will make that extremely rare event much more common, even effectively guaranteeing it if you strike with a single munition...but ah well. Can't be helped, as mentioned.

>Would you also mind fixing these new GhostEye arrays - they do not seem to be able to guide PAC-2 GEM+, which is a part of the battery.

Fixed, thanks for pointing it out.

**Comment by rob76pl** [comment]
Thank you.
