### ISSUE TITLE
New Polish SAM Bty (Patriot [PAC-3 MSE]) 2022-

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2036]
### DB Selector

DB3K

### DBID to Copy

Facility 3223

### Hypothetical

No

### Name

SAM Bty (Patriot [PAC-3 MSE]) (12x Lnchr)

### Country

Poland

### Service

Air Force

### In Commission

2022 - Present

### Number in Service

2

### Sensors

2x AN/MPQ-65

Also unsure about arc configuration of these 2 radars. The source claims primary/backup but 2 radars may be there to improve coverage (let's say to 180 degree with some radar overlap) or may be facing the same direction to allow for more interceptions of ballistic threats at the same time. That is why it may be better to split this into mini batteries with 1 radar each.

### Mounts

8x M901 launchers with 12 x MIM-104F Patriot PAC-3 MSE (Weapon 3207) each.

Stinger missiles removed, if MANPADS will be present they will certainly be Polish Piorun MANPADs (Weapon 3977)

### Other Changes

Polish Patriot configuration is not typical. One Battery has 2 fire units (each with 1 radar) and 8 TELs. So in essence you may want to model it as mini batteries (1 Radar + 4 TELs x 12 PAC-3 MSE each), i.e. split in half.

Magazines are unknown, as the original order has more or less 1:1 ratio of launchers to missiles. I would presume the same as in US Patriot (which is 96 (or 48 if we split battery)). This can be fixed later when this becomes known.

The chassis on which TELs will be mounted is not known yet (high chances of Polish Jelcz chassis). Same for magazines. We can keep M901 as TEL.

208 PAC-3 MSE missiles were bought as part of this order.

MANPADS/SHORAD unknown for now, possibly Piorun or Pilica system. I recommend we replace Stinger with Piorun.

Rumours about possible transfer from Air Force to Army (not confirmed). I recommend Air Force for now.

### Sources

https://defence24.com/technology/us-ibcs-configuration-for-the-polish-patriot-system

https://historia.org.pl/2022/04/20/system-patriot-jeszcze-w-tym-roku-trafi-do-polskiej-armii/
https://defence24.pl/sily-zbrojne/polska-konfiguracja-systemu-patriot-z-ibcs-analiza

**Comment by rob76pl** [comment]
Also unsure about arc configuration of these 2 radars. The source claims primary/backup but 2 radar may be there to improve coverage (let's say to 180 degree with some radar overlap) or may be facing the same direction  to allow for more interceptions at the same time. That is why it may be better to split this into mini batteries with 1 radar each.

**Comment by PygmalionOfCyprus** [comment]
Added 496 as a "SAM Plt" (w/ comments indicating 2x / bty); each Plt has its own MPQ-65, 4x TELs, and 2x Piorun teams.

**Comment by rob76pl** [comment]
Thank you.
