### ISSUE TITLE
Japan, P-1, 2022

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2037]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2936

### Summary of Changes

P-1

Sensor
---
HPS-106 → HPS-106B
HAQ-2 →　HAS-2B
HLQ-4 → HLQ-4B
HLR-109 →  HLR-109C
HSQ-102 → HSQ-102B

Japan MoD stated the upgrade P-1 is to improve " Target identifying ability, flight performance and intelligence
processing capability", and those equipment budgeted from 2020-2022.
I believe HPS-106B(Radar), HLR-109C(ELINT) and HAQ-2B(IR/EO)'s tech is improved to Early 2020's tech for sure, but HLQ-4B(MAWS), and HQS-102B(MAD) are not directly related to the upgrade project, so tech era is same as original one.

COMMS
---
HRC-122 → HRC-122B
HRC-123 → HRC-123C-1
HRC-124 →HRC-124B (Actually, 2011's P-1 has HRC-124, and HRC-124B for 2022 and later)

for sensors, it's just names... I'm not sure they are worth to add it, but FYI.

Sonobuoy
---
This is about loadouts,so I will make another entry.

Related Request
---
last update request for original one
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1882

Loadout
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1372

### Sources

HPS-106B(First year)
https://www2.njss.info/offers/view/17696667

HAQ-2B
https://www2.njss.info/offers/view/16995895

HLQ-4B(first year)
https://www2.njss.info/offers/view/17008605

HLR-109C
https://www2.njss.info/offers/view/15413514

HSQ-102B
https://www2.njss.info/offers/view/15587300

Defense Budget Request, Japan MoD
Page 10,  Target identifying ability, flight performance and intelligence
processing capability improved compared to conventional P-1
aircraft.
https://www.mod.go.jp/en/d_act/d_budget/pdf/200330a.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
