### ISSUE TITLE
Polish Air Force F-35A Blk 4 TR3

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2038]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3835

### Hypothetical

No

### Name

F-35A Lightning II - 2025, Block 4

### Country

Poland

### Service

Air Force

### In Commission

2025 - 

### Number in Service

32

### Other Changes

Same configuration as US Air Force. Block 4 TR3.

Ammo contract to be signed soon, details unknown. Before new ammo is delivered the assumption is they can use existing Polish F-16 Blk 52 ammo (loadouts already modeled in DB3000) (Aircraft 4373).

IOC in 2028. First deliveries 2024 but pilots will train in US (first 8 units/Luke Base/Arizona). Delivery to Poland is 2025/2026.

Home base for first squadron will be in Lask.

### Sources

https://defence24.com/harpia-fighter-procurement-details-polish-f-35-deal-unveiled
https://breakingdefense.com/2021/09/likely-base-for-second-polish-f-35-squadron-identified/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.

**Comment by rob76pl** [comment]
Thank you.
