### ISSUE TITLE
Add air-launched version of Standard Missile for Iranian F-4E

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2039]
### DB Selector

DB3K

### User(s)

1309, 3896

### Weapons Carried

2x Air launched Standard Missile
2x AIM-9N
2x 370 USG drop tank
1x 600 370 USG drop tank

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

450nm (similar as AGM-78D loadout)

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

The Air launched Standard Missile were noted to also being able to engage ground/surface target. The range is probably up to 50nm, due to its were launched from the air. Below pic is for the references
![image](https://user-images.githubusercontent.com/99646926/185393326-163aa8ee-a68a-4f80-9454-01036acfdc42.png)

### Sources

https://medium.com/war-is-boring/in-1980s-battle-with-america-iran-held-back-its-deadliest-missiles-2fc05c4a991d

**Comment by KushanGaming** [comment]
Done for DB 496.
