### ISSUE TITLE
update/correction/addition for HESA Karrar drone loadouts

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2040]
### DB Selector

DB3K

### Affected DBID(s)

4906, 5591 HESA Karrar

### Summary of Changes

-Add generic IR camera to the Azarakhsh loadout, something like MS-177 Camera module (weapon/3768) but make it only cover up to 60 degree angle forward facing at best. This particular loadout have some sort of camera module attached on top of the rail as per pic below:
![image](https://user-images.githubusercontent.com/99646926/185400974-bf09ba52-1f12-4285-91bf-9a6fb3667989.png)

-Reduce the C-704/Nasr-1(weapon/2390) loadout from 2x missile to just only 1x.
![image](https://user-images.githubusercontent.com/99646926/185409845-0be5cbc8-bca1-4aa5-9eef-aa0a8b97346d.png)

-Add 1x BL.755 no.1 CB (weapon/1562) loadout to the UCAV.
![image](https://user-images.githubusercontent.com/99646926/185402480-59db7602-e0b6-4442-808e-54ada6aebd74.png)

-Add 1x Yasin satellite guided bomb loadout. The bomb is similar to Balaban(weapon/3647) except it have more range (30-32nm instead of 15nm) with CEP up to 10 meter.
![image](https://user-images.githubusercontent.com/99646926/185412462-cba2c0ef-af65-4038-8357-9beb6caec92f.png)

### Sources

https://www.oryxspioenkop.com/2019/09/the-oryx-handbook-of-iranian-drones.html
https://twitter.com/fab_hinz/status/1406912705366216708/photo/3
http://www.navaldrones.com/Karrar.html
https://www.globalsecurity.org/military/world/iran/yasin.htm#:~:text=Yasin%20Satellite%20Guided%20Glide%20Bomb%20The%20missile%20named,kilometers%20%2830%20miles%29%20from%20manned%20or%20unmanned%20aircraft.

**Comment by PygmalionOfCyprus** [comment]
Handled 496. Are we positive that's a camera module, and not just some sort of electronic system? Couldn't see anything indicating as such in the source.

**Comment by capcop98** [comment]
Most probably yes, as per source below:

"In recent exercises, several truck-mounted launchers have fired a wave of Karrars. The drones take off with the assistance of a rocket and land with a parachute. Little is known about their sensors, but the latest version is said to have cameras and infrared sensors."

https://opflsoft.net/why-iran-is-arming-its-drones-with-air-to-air-missiles/

**Comment by PygmalionOfCyprus** [comment]
Fair enough. Already added, but wanted to make sure!
