### ISSUE TITLE
Add HESA Karrar as loitering munitions

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2041]
### DB Selector

DB3K

### Baseline

Aircraft 4904

### Hypothetical

No

### Name

HESA Karrar - Loitering Munition version

### Length (m)

same as Aircraft 4904

### Width/Span (m)

same as Aircraft 4904

### Diameter (m)

same as Aircraft 4904

### Weight (kg)

same as Aircraft 4904

### Range (nm)

320nm

### Target Altitude / Depth (ft)

300ft AGL

### Warhead

250kg HE

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

10 m

### Sensors

1x EO Seeker (2nd generation)

### Weapon Codes

Terrain Following, Loiter Capability, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Uses GPS

### Comments

![image](https://user-images.githubusercontent.com/99646926/185424345-d9d89902-5f8a-429b-a436-ee409b66146b.png)

### Sources

https://www.oryxspioenkop.com/2019/09/the-oryx-handbook-of-iranian-drones.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499 as part of ongoing Iran review. This is actually a "loitering" SAM, but I did give it a SSM capability as well.

https://twitter.com/fab_hinz/status/1406912655714140163
