### ISSUE TITLE
Sadegh-1 recon loadout correction

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2042]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5028

### Summary of Changes

-Swap the QW-1 MANPADS with Misagh-1/2 MANPADS
![image](https://user-images.githubusercontent.com/99646926/185427788-fffa5146-afd8-46b3-b7e9-e257373d1ebd.png)

-Change from 1x MANPADS to 2x MANPADS. The UAV were seen with the 2x MANPADS instead of just 1x.
![image](https://user-images.githubusercontent.com/99646926/185427696-908519ca-89dd-4c59-a9c3-82936513a9b2.png)

### Sources

https://www.uasvision.com/2014/10/02/irans-sadegh-ucav-armed-with-air-to-air-missiles/

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
