### ISSUE TITLE
Mohajer-6 UCAV Qaem-1 loadout correction

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2043]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5355, 5020, 5021, 5022

### Summary of Changes

Increase the Qaem-1 loadout from 2x missiles to 4x missiles.
![image](https://user-images.githubusercontent.com/99646926/185432757-cca00b2e-c79d-40ab-89bb-cb8749ab91a1.png)

### Sources

https://www.oryxspioenkop.com/2021/08/iranian-mohajer-6-drones-spotted-in.html

**Comment by PygmalionOfCyprus** [comment]
Added an optional extra 2 missiles to the current loadout, so you can launch w/ 2 or 4 missiles depending on preference. 496.
