### ISSUE TITLE
Propulsion - Viper Mk.633-41

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2044]
### DB Selector

DB3K

### DBID to Copy

Viper Mk.633-47 (can't find DBID for propulsion)

### Hypothetical

No

### Name

Viper Mk.633-41

### Country

-

### Service

-

### Other Changes

The Viper Mk.633-41 engine with afterburner is used by the newer J-22 Oraos, while the Mk.633-47 (also with afterburner) was used by the IAR-93B. All values for both engines are exactly the same, thus the 633-41 should be a copy of the 633-47.

### Sources

Turbofan and Turbojet Engines: Database Handbook
https://books.google.com/books?id=_5vA_5XK33sC&pg=PA37&lpg=PA37&dq=viper+mk+633-41&source=bl&ots=oRXlS9uXt_&sig=ACfU3U0lha2pdnBGEv7XVkQqeb3h8IJW7A&hl=de&sa=X&ved=2ahUKEwjGtY3c19H5AhW_VfEDHQf8CScQ6AF6BAgnEAM#v=onepage&q=viper%20mk%20633-41&f=false

![](https://i.imgur.com/cSglWsr.png)

![](https://i.imgur.com/p61ebGE.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
