### ISSUE TITLE
Vampire Trainers for Austria

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2047]
### DB Selector

CWDB

### DBID to Copy

CWDB Aircraft 4110

### Hypothetical

No

### Name

Vampire T.55

### Country

Austria

### Service

Air Force

### In Commission

1957-1972

### Number in Service

x4+x5 refurbished T.11, not all simultaneous

### Loadout Options

No RP-3 rockets, otherwise identical

### Other Changes

Technically this is an entry for two aircraft as one because half of the Austrian Vampire trainer fleet was T.55s and the other half was refurbished British T.11s, but given that the two types are identical except for the initial owner I think it's better to just represent them as the same aircraft, so that the mission AI can launch a T.55 and a T.11 as a flight of two.

For a lot of countries the training aircraft are kind of irrelevant, for Austria they're the best strike aircraft available in their period of service.

### Sources

http://www.airvectors.net/avvamp_2.html#m2
http://www.doppeladler.com/oebh/airreg.htm

**Comment by Jkryos** [comment]
Added CWDB 496.
