### ISSUE TITLE
Vampire Trainers for Ireland

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2048]
### DB Selector

CWDB

### DBID to Copy

CWDB Aircraft 4110

### Hypothetical

No

### Name

Vampire T.55

### Country

Ireland

### Service

Air Corps

### In Commission

1956-1976

### Number in Service

x3+x3

### Loadout Options

Suspect no RP-3 rockets

### Other Changes

Again, this is Ireland's best and only fighter-bomber despite being a two seater.

### Sources

https://www.irishtimes.com/opinion/letters/hunting-vampires-1.242698
http://www.airvectors.net/avvamp_2.html#m2

**Comment by Jkryos** [comment]
Added CWDB 496
