### ISSUE TITLE
Rename #3869 K-SAAM

### ISSUE THREAD

**Issue by Ma-ryang** [PygmalionOfCyprus/cmo-db-requests#2051]
### DB Selector

DB3K

### Affected DBID(s)

#3869 K-SAAM Rename

### Summary of Changes

Currently, #3869 is implemented under the name K-SAAM, however the official name during development stage was SAAM and K-SAAM was a name that was called in the civillan, media and so on, but as the K-SAAM name is frequently used by everyone, it seems to have been also used by officials

and It was designated SAAM-400K after the development was completed
It looks good to follow the example of SSM-700K Hae Sung and name it K-SAAM to SAAM-400K Hae Gung

### Sources

![1660981320](https://user-images.githubusercontent.com/99650102/185736049-228c450e-7bdf-4b4f-be75-be36eefce568.png)
![1660905794](https://user-images.githubusercontent.com/99650102/185736082-4de7fbfa-05d0-4b56-8ede-76fb953253db.jpg)
SAAM-400K mentioned in the Integrated Logistics Support chart

**Comment by PygmalionOfCyprus** [comment]
Handled 497. Kept K-SAAM as an alternate designation in the name since that's what most people are familiar with.

**Comment by Ma-ryang** [comment]
> Handled 497. Kept K-SAAM as an alternate designation in the name since that's what most people are familiar with.

Thank you
