### ISSUE TITLE
#3217, #3622 Missing missile Command Datalink

### ISSUE THREAD

**Issue by Ma-ryang** [PygmalionOfCyprus/cmo-db-requests#2052]
### DB Selector

DB3K

### Affected DBID(s)

#3217 #3622

### Summary of Changes

Currently #3217 Daegu Class and #3622 KDX-III Batch II (Jeongjo the Great) are currently inoperable the K-SAAM Missiles due to the lack of a datalink

K-SAAM Command Datalink should given these two unit (#3217 and #3622)

### Sources

![Desktop Screenshot 2022 08 20 - 17 37 02 49](https://user-images.githubusercontent.com/99650102/185742006-74912aa0-1c2a-4837-b2a3-fffcdd7e1cd5.png)
#3622 with no Sky bow Command Datalink

![Desktop Screenshot 2022 08 20 - 17 36 44 93](https://user-images.githubusercontent.com/99650102/185742010-1835bb3a-303a-4ea1-95b2-35a3a0a4855f.png)
#3217 with no Sky bow Command Datalink

![Desktop Screenshot 2022 08 20 - 19 26 06 16](https://user-images.githubusercontent.com/99650102/185742056-66156074-c014-479a-b265-d79fcb9aeb95.png)
No datalink alert

![Desktop Screenshot 2022 08 20 - 19 29 05 32](https://user-images.githubusercontent.com/99650102/185742063-3268eae9-815c-4557-a7da-0097a5b1361a.png)

**Comment by KushanGaming** [comment]
Done for DB496.

**Comment by Ma-ryang** [comment]
Thank you
