### ISSUE TITLE
Senegal Improved Osprey 55 PG  Fouta Class x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2053]
### DB Selector

DB3K

### DBID to Copy

DB3k #2562

### Hypothetical

No

### Name

Fouta

### Country

Senegal

### Service

Navy

### In Commission

1987-

### Number in Service

1x

### Sensors

- delete TRS 3050
- add 1x Furuno FR-1411 surface search
- add 1x Furuno FR 1221 nav

### Mounts

- Combat Fleets 1x 40mm/70 Bofors (same as copied entry) and 1x 20mm/90 GIAT F2 AA instead of 2x 20mm GAM-BO1
- or Janes 2012-13 shows 1x 30mm Hispano Suiza and 1x 20mm/90 GIAT F2 AA (Weapon recognition not my forte)

### Other Changes

- stern docking well for 6.5m watercraft RI-22 inspection/rescue boat can be modelled by RHIB

### Sources

Combat Fleets of the World 2013, pg 652
Janes 2012-13, pg 726
http://www.navypedia.org/ships/senegal/sen_cf_fouta.htm
https://fr.wikipedia.org/wiki/Fouta_(patrouilleur)

![image](https://user-images.githubusercontent.com/99632305/185752311-58589423-a375-4827-b52e-d9f9773cf599.png)
![image](https://user-images.githubusercontent.com/99632305/185752393-0d376b48-bf1a-4a76-adcb-72dbf217a84a.png)

**Comment by Jkryos** [comment]
Added DB3K 497.
