### ISSUE TITLE
Aircraft Loadouts 612 and 1180 please add the "Un/Load cargo" function

### ISSUE THREAD

**Issue by deagu1** [PygmalionOfCyprus/cmo-db-requests#2054]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft Loadouts #612 and #1180

### Summary of Changes

Both loadout's contain 16x Trooper but it is not possible to load cargo for the aircraft. The button "Un/Load Cargo" in the F6 Air Ops menu is gray. The related Aircraft is the Ka-29TB Helix B Russia ID #370.

### Sources

No resources needed. The Troops in the loadouts might have been overseen because the loadout names don't contain the word "Troops" as in loadout #4545 for example.

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
