### ISSUE TITLE
Correct range and band on Type 346B radar 

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#2056]
### DB Selector

DB3K

### Affected DBID(s)

Sensor_6093 (range); Sensor_ 5127; Sensor_ 2116; Sensor_6093 (Band)

### Summary of Changes

Recommend increasing the range of the Type 346B radar, used in the Type 055 (PLAN) destroyers.  Currently, the Type 346B has the same range of 175nm as the Type 346A (Sensor_5127).    Sources (Cited below) claim the Type 346B is analogous to the SPY-6(V) (Sensor_5360) which in game has a range of 250nm.  See https://www.deagel.com/Sensor%20Systems/Type%20346/a002976    270-324 nm/500-600 nm; https://asiatimes.com/2022/04/china-russia-blast-superweapon-warnings-at-us/ (claiming Type 346B is analogous to the SPY-6).  Based on this, and the larger sized of the Type 055 destroyer (which gives it the power output needed to take advantage of a SPY-6 type radar), I recommend increasing the Type 346B to 270 nm.  

Additionally,  sources give the Type 346, 346A and 346B (Sensor_ 5127; Sensor_ 2116; Sensor_6093) radars as dual band systems, operating in NATO F and G bands . https://www.radartutorial.eu/19.kartei/07.naval/karte054.en.html claims the Type 346 series operates in 3.0 - 3.4 GHz (NATO "F" and 5.25-5.95 GHz (NATO "G") bands.  https://warpill.com/index.php/2022/05/20/the-type-346-radar-chinas-answer-to-spy-1/ estimates a center frequency around 3.6 GHz.  **NOTE: The "G" band designation for the fire control may be challenged, as the HHQ-9 missile is a derivative of the S-300 system, whose FC radar operates in the "I" band (as is currently reflected in the DB3K database).**

### Sources

https://www.deagel.com/Sensor%20Systems/Type%20346/a002976
https://warpill.com/index.php/2022/05/20/the-type-346-radar-chinas-answer-to-spy-1/
https://asiatimes.com/2022/04/china-russia-blast-superweapon-warnings-at-us/ 
https://www.radartutorial.eu/19.kartei/07.naval/karte054.en.html

**Comment by Jkryos** [comment]
Updated DB3K 504.
