### ISSUE TITLE
Najm-802 PESA radar cannot detect ballistic missile 

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2059]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3236, Sensor 6020

### Description of Problem

The Najm-802 PESA radar cannot detect ballistic missile, in this case DF-12 ballistic missile, while Tombstone (Sensor/2788) and El/M-2080 Green Pine (Sensor/1943) can detect it. 

Isnt the Najm-802 PESA have the capability to detect ballistic missile? Even in Database Viewer it were described to have "ABM & Space Search" just like Tombstone (Sensor/2788) and El/M-2080 Green Pine (Sensor/1943).

![image](https://user-images.githubusercontent.com/99646926/185776400-4ac77e05-d69a-44d3-b955-6f7e42562816.png)

![image](https://user-images.githubusercontent.com/99646926/185776324-665d0fbc-9b10-40db-87b8-d9c995cedc92.png)

below is the screenshot for the issue:
for this scenario, i have put Najm-802 radar and turned it on alongside Tomstone or Green Pine
![image](https://user-images.githubusercontent.com/99646926/185776337-a93f13ed-678f-43e1-aaa8-90ebe8ccde06.png)

but only Tombstone that were able to detect the incoming ballistic missile, same as when i put the Green Pine radar instead. If i only turned on the Najm-802, the radar wont detect the missile at all.
![image](https://user-images.githubusercontent.com/99646926/185776374-af9285a6-9398-41c4-a571-e4755d1332b5.png)

### Recommended Fix

sorry if this is way to general, but please make it to be able to detect ballistic missile as the Najm-802 PESA radar were described to be able to detect ballistic missile as well

source: https://www.deagel.com/Sensor%20Systems/Najm-802/a003745

**Comment by PygmalionOfCyprus** [comment]
Handled 499, max alt. was set too low.
