### ISSUE TITLE
Diehl Defense Laser Guided Sidewinder (LaGS)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#206]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

Diehl Defense Laser Guided Sidewinder (LaGS)

### Length (m)

AS AIM-9L

### Width/Span (m)

AS AIM-9L

### Diameter (m)

AS AIM-9L

### Weight (kg)

AS AIM-9L

### Range (nm)

AS AIM-9L

### Target Altitude / Depth (ft)

Surface Targets

### Launch Altitude / Depth (ft)

AS AIM-9L

### Warhead

AS AIM-9L

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

AS AIM-9L

### Sensors

1x Laser Seeker

### Weapon Codes

Supports Buddy Illumination

### Comments

A2G missiles created by modifying Sidewinder AAMs, Possible platforms are German Tornadoes/Eurofighters (and potential new aircraft like F/35 or Super Hornet) and Swedish Gripen fighters (was test platform).

### Sources

https://www.thedrive.com/the-war-zone/33797/watch-a-jas-39-gripen-fighter-fire-a-new-ground-attack-version-of-the-sidewinder-missile?fbclid=IwAR3fB07-F8UbFxd07RN50gGHQlHnW67o7hMosDy3uGS19NGdTw3GFtelw4s

https://www.diehl.com/defence/en/press-and-media/news/convincing-sidewinder-air-to-ground-mission/

https://militaryleak.com/2021/05/11/diehl-defence-complete-successful-test-firings-of-new-laser-guided-sidewinder-lags/

https://www.deagel.com/Defensive%20Weapons/LaGS/a002800

https://frontierindia.com/diehl-tests-laser-guided-sidewinder-for-air-to-ground-mission/

https://euro-sd.com/2021/05/articles/exclusive/22920/lags-tests-successful/

https://esut.de/en/2019/05/meldungen/ruestung2/12926/sidewinder-fuer-luft-boden-einsatz/

http://www.mycity-military.com/uploads2/112604_1120725012_Diehl%20-%20Sidewinder%20LaGS.pdf

http://www.indiandefencereview.com/news/laser-guided-sidewinder-lags-for-air-to-surface-missions-of-combat-aircraft/

https://superexpo.com/en/exhibitor/26294/diehl-defence-holding-gmbh/product/20024/laser-guided-sidewinder-lags

**Comment by PygmalionOfCyprus** [comment]
Added 495.
