### ISSUE TITLE
Update/Correction for SA.532U2 Cougar Mk.II and SA.322L Super Puma

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2062]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4069, 2556

### Summary of Changes

-Add Generic MAWS and RWR for (Aircraft/4069)
![image](https://user-images.githubusercontent.com/99646926/185795779-b2326e11-9c4d-4250-9a34-ea572e64df27.png)

-Add Alkan Elips x2 [72 Cartridges] (Mount/1822) to (Aircraft/4069)
![image](https://user-images.githubusercontent.com/99646926/185795807-0651785e-ee8c-4bc0-98f4-938702ed90a9.png)

-Add generic FLIR and 3rd Generation NVG to (Aircraft/4069)
![image](https://user-images.githubusercontent.com/99646926/185796438-c31a5002-1e9a-4757-8c98-35e7abdd97cf.png)

-Add Generic navigation radar to both aircrafts and change the cockpit from Steam Gauge to Glass cockpit(Aircraft/4069) and Partial Glass cockpit(Aircraft/2556)
![image](https://user-images.githubusercontent.com/99646926/185795928-481fadd8-6cf6-478f-ac49-8aafae4b8162.png)

### Sources

https://www.airdominance.nl/index.php/as-532u2-cougar-mk-ii.html
https://www.army-technology.com/projects/cougar/
http://all-aero.com/index.php/35-helicopters/copters/407-as532-cougar
https://aeropedia.com.au/content/aerospatiale-sa-332-super-puma/

**Comment by PygmalionOfCyprus** [comment]
Handled 497. Also applied to the other 322L variants.
