### ISSUE TITLE
Update/Correction for Fateh-class submarine

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2063]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 450 & 682

### Summary of Changes

-Reduce the torpedo in the magazine from 8x to just 2x. The magazine can only fit 2x torpedo at best.
![image](https://user-images.githubusercontent.com/99646926/185801733-d8234a1c-4d75-49f7-81c3-1069e7cf549d.png)

-Add Jask submarine-launched ASHM to the submarine. It is a submarine-launched version of C-704/Nas-1(Weapon/2390). Also add it into the magazine but make it as 0x instead.
![image](https://user-images.githubusercontent.com/99646926/185801869-6a23fe74-515c-4c2c-992d-1839050b0819.png)

-Change the beam from 3.5m to 4.4m and max depth to 200m
![image](https://user-images.githubusercontent.com/99646926/185801717-dc551614-837d-4964-8868-916bcd21e64d.png)

### Sources

https://www.globalsecurity.org/military/world/iran/nasr.htm
http://www.hisutton.com/Fateh-Class_Submarine.html
http://www.hisutton.com/Iran_SLCM_video_analysis.html

**Comment by PygmalionOfCyprus** [comment]
Handled 497. Also adding Jask to the Ghadir.
