### ISSUE TITLE
RAF Typhoon radar change

### ISSUE THREAD

**Issue by Anon9944** [PygmalionOfCyprus/cmo-db-requests#2064]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4704, Aircraft 4703, Aircraft 3625, Aircraft 1033, Aircraft 4799, Aircraft 4800, Aircraft 4948

### Summary of Changes

Change sensor 1349 CAPTOR-E AESA [CAESAR] to the correct CAPTOR mechanically scanned radar as used on the previous entries for the RAF Typhoon. RAF Typhoons currently all fly with the CAPTOR mechanically scanned radar and an AESA has not been fielded yet.

### Sources

https://www.defensenews.com/global/europe/2022/05/26/british-air-force-pushes-really-big-contract-for-typhoon-radar-upgrades/

"Typhoon is currently equipped with a mechanically scanned radar."

https://www.key.aero/article/depth-look-eurofighters-next-gen-radar

Article above talks about the AESA radar under development for RAF Typhoons

https://www.thedrive.com/the-war-zone/34940/eurofighters-new-radar-is-nearly-ready-but-royal-air-force-wants-an-even-better-one

"RAF pilots have always been swift to praise the legacy mechanically-scanned Captor, but procurement chiefs have robustly laid out ambitious plans to retrofit a small fleet of Tranche 3 jets with the new “Radar 2.”

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
