### ISSUE TITLE
SPEAR EW Aircraft Targets Only? 

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#2068]
### DB Selector

DB3K

### Affected DBID(s)

3690

### Description of Problem

Spear EW has only aircraft as valid target type.  This causes the following observed issues:

1. Cannot be used in the suppression role
2. Will not launch other than BOL
3. Does not loiter when it reaches the 'victim' system
4. Cannot set realistic or even useable WRA

### Recommended Fix

Correct the target type

**Comment by tbrandon517** [comment]
Currently SPEAR EW is modeled as a EW jammer/decoy like a MALD which matches the datasheet I fo on the MBDA website below. For decoy weapons the target type is what the decoy replicates as per the Command Mega FAQ.

"For decoys, the “valid target” value represents the type of contact they will represent to enemy sensors."

https://www.mbda-systems.com/product/spear/

https://command.matrixgames.com/?page_id=2920

**Comment by HVAA** [comment]
Sorry, not how MALD is modelled. 
MALD has a whole host of valid targets. Spear EW does not.
 It messes big time with the WRA because of it.
For valid targets - read valid victim.
This is not WAD at all, MALD approaches, then circles the target at a stand off range messing with its sensors.  Spear just flys on by.  If Spear EW = upadated MALD or at least equivalent then it is not WAD right now.

**Comment by tbrandon517** [comment]
I double check and you are right. For category Decoy (Vehicle) the target list is various for MALD and TALD but not for SPEAR EW or Kipper OECM.

From a glance it would appear the Perdix and WZ-8 drones in this category should probably be recategorized as aircraft like the Altius 600 you can launch from the XQ-58s.

**Comment by HVAA** [comment]
Thanks for double checking that. I was beginning to doubt myself too. I have a test scenario (sandbox) where I do this and when I had MALD and SPEAR EW in the various loads I just assumed SPEAR EW would behave as if it were a MALD.  4 Typhoons later...

**Comment by HVAA** [comment]
This still seems not to be addressed in the latest Db Build. It messes big time with anything you try to do with this decoy as it remains essentially useless.  The Showcase QE includes this weapon/decoy and as the point of that was to 'showcase' stuff, there is at least one new capability that does not work...

**Comment by KushanGaming** [comment]
Fixed for DB497.
