### ISSUE TITLE
Senegal OPV 45 Kédougou x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2070]
### DB Selector

DB3K

### Baseline

DB3k #2541

### Hypothetical

No

### Name

Kédougou

### Class

OPV-45

### Country

Senegal

### Service

Navy

### In Commission

2015-

### Number in Service

1x

### Length (m)

45.9

### Beam (m)

8.4

### Draft (m)

1.9

### Standard Displacement (t)

450

### Complement

21

### Primary Propulsion Type

Diesel

### Propulsion

2x Cummins KTA 50 M2

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

2000@12

### Sensors

- 2x Furuno radars

### Mounts

- 1x single 20mm/90 F2
- 4x single 12.7mm/90

### Aircraft & Docking Facilities

-  semi-rigid Ufast RIB 6.20 of 6.2 meters (via stern launch ramp)

### Ship Codes

Aluminum Superstructure Only

### Sources

http://www.navypedia.org/ships/senegal/sen_cf_kedougou.htm
https://fr.wikipedia.org/wiki/K%C3%A9dougou_(patrouilleur)

![image](https://user-images.githubusercontent.com/99632305/186016037-33fe27b7-9dc3-422a-90e1-b261f354374b.png)
![image](https://user-images.githubusercontent.com/99632305/186016380-b9ee2850-b18c-41b8-9a39-e9f44a86ddfc.png)
![image](https://user-images.githubusercontent.com/99632305/186016469-db979bc6-5cd0-446b-80d9-0206502041e7.png)

**Comment by Jkryos** [comment]
Added DB3K 507.
