### ISSUE TITLE
Senegal 841 Karabene (Edic 700 LCU) x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2072]
### DB Selector

DB3K

### DBID to Copy

2106

### Hypothetical

No

### Name

841 Karabene

### Country

Senegal

### Service

Navy

### In Commission

1986-

### Number in Service

2x

### Sensors

- Furuno RDP 118

### Mounts

- fitted for 2x single 20mm/90 GIAT F2 AA
- 2x 12.7mm mg

### Other Changes

- Gorée was transferred to Senegal after service under French flag
- 

### Sources

http://www.navypedia.org/ships/senegal/sen_ls_karabane.htm
Combat Fleets of the World 16th Edition, pg 653
Jane's 2012-13, pg 727

![image](https://user-images.githubusercontent.com/99632305/186021258-6a579960-a0b1-4dd1-9b2e-ec2937dc00a9.png)
![image](https://user-images.githubusercontent.com/99632305/186021312-4835dc75-bdf9-4c51-86cf-b3c34ebe26be.png)

**Comment by Jkryos** [comment]
Added DB3K 497.
