### ISSUE TITLE
AN/SSQ-62F, GPS-capability

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2074]
### DB Selector

DB3K

### DBID to Copy

Weapon 2496

### Hypothetical

No

### Name

AN/SSQ-62F

### Country

-

### Service

-

### In Commission

2019?

### Sensors

AN/SSQ-62F - DICASS Sonobuoy, cannot see any improvements from AN/SSQ-62E from the sources. but the tech could be late 2010's.

### Sources

I say the commission year is 2019 because of this pdf.   
https://sonobuoytechsystems.com/wp-content/uploads/2019/08/Q62F-GPS.pdf

**Comment by PygmalionOfCyprus** [comment]
I think I must have added this back in 496 and forgot to close the ticket, 'cause it's in there already.
