### ISSUE TITLE
Update/correction for AOE 532 Panshih of RoC Navy

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2076]
### DB Selector

DB3K

### Affected DBID(s)

ship 3077

### Summary of Changes

The Panshih-class AOE of RoC Navy were said to be able to refuel 2 ships at one time, but in the game it cant fully refuel even a single Kang Ding class frigate that have maximum diesel capacity of 350 tons. Nor that it carry any aviation fuel to support the helicopter operation as well.
![image](https://user-images.githubusercontent.com/99646926/186168359-7e702eb3-27a9-4988-b522-131e419e0dee.png)

Unfortunately, there is little to none info on exactly of how much fuel it can carry, but given of its size, probably it can carry more or less same fuel diesel & aviation fuel as Tide-class AOE(Ship/2581).

And also add hangar for 3 medium helicopters as it were observed to have the hangar and based on a few sources indicates that it can fit up to 3 medium helicopters.
![image](https://user-images.githubusercontent.com/99646926/186168681-ffecc38a-bcfa-430e-b687-774a77680304.png)
![image](https://user-images.githubusercontent.com/99646926/186168801-49015fc1-0e1c-4d74-bcfa-75fc318de983.png)

### Sources

https://www.navyrecognition.com/index.php/newsb/defence-news/year-2015-news/january-2015-navy-naval-forces-defense-industry-technology-maritime-security-global-news/2362-roc-navy-commissioned-its-new-fast-combat-support-ship-aoe-532-qpanshihq.html

http://www.dmitryshulgin.com/tag/panshih-aoe-532/

https://en.wikipedia.org/wiki/Panshih-class_fast_combat_support_ship

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
