### ISSUE TITLE
Japan, UP-3D, Stand-off ECM trainer

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2077]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4761

### Hypothetical

No

### Name

UP-3D

### Country

Japan

### Service

MSDF

### In Commission

1998

### Number in Service

3x

### Sensors

1998 version
---
-APS-115
-HLQ-3-T(OECM, late 1990's tech, sounds like and -T stands for training, perhaps J/ALQ-5 (Sensor ID 5913) could be used as reference)
-Mk 1 eyeball

2019 version
---
APS-115
HLQ-5-T(OECM, late 2010's tech)
Mk1 eyeball

### Loadout Options

Stand-off ECM Training
-100x chaff (by Chaff pod):I do not know the exact number of stored chaff in the pod.
http://rightwing.sakura.ne.jp/equipment/jmsdf/aviation/up-3d/up3d_06.jpg

Target Tow
-2x Aerial Towed Target
https://www.mod.go.jp/msdf/equipment/aircraft/utility/up-3d/img/up-3d_02l.jpg

### Other Changes

General
Category: Electronic Warfare

COMMS
---
HRC-120 (HF Radio)
HRC-112 (VHF Radio)
AN/HRC-187(V) (UHF Radio)

### Sources

General
---
Website of JMSDF,, basic info + picuture(Target tow loadout)
https://www.mod.go.jp/msdf/equipment/aircraft/utility/up-3d/

Pictures (Chaff pod, target tow)
http://rightwing.sakura.ne.jp/equipment/jmsdf/aviation/up-3d/up-3d.html

Sensor
---
HLQ-3-T
https://www2.njss.info/offers/view/1480934
HLQ-5-T
https://www2.njss.info/offers/view/11508975

COMMS
---
HRC-120
https://www2.njss.info/offers/view/584043
HRC-112
https://www2.njss.info/offers/view/584059
AN/ARC-187(V)
https://www2.njss.info/offers/view/648333

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
