### ISSUE TITLE
HIMARS Poland 2022-

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2082]
### DB Selector

DB3K

### DBID to Copy

Facility 2446

### Hypothetical

No

### Name

Arty Bty (HIMARS) (3x pr Bn)

### Country

Poland

### Service

Army

### In Commission

2022 - 

### Number in Service

18

### Loadout Options

Purchased ammo is: (so no first gen ATACMS with shorter range (can be removed from loadout list)).

36 x 6 = 216 GMLRS Unitary
9 x 6 = 54 GMLRS Alternative Warhead
30 x  ATACMS Unitary (quoted range in all sources is 300 km so MGM-104B Block IA).

### Other Changes

Should be an exact copy of US HIMARS. 

Total number of launchers is 18 (+2 for training).

Battalion structure is 3xBty. Bty is 6 launchers. No lower level hierarchy is known.

36 x 6 = 216 GMLRS Unitary
9 x 6 = 54 GMLRS Alternative Warhead
30 x  ATACMS Unitary (quoted range in all sources is 300 km so MGM-104B Block IA).

Vehicles are the same as in US Army.

First deliveries are in 2022.

### Sources

https://defence24.com/poland-to-acquire-the-first-himars-squadron-pricetag-usd-414-million-agreement-expected-on-wednesday
https://www.defensenews.com/global/europe/2019/02/11/poland-to-sign-414-million-deal-for-rocket-launchers/

https://defence24.pl/polityka-obronna/pierwszy-dywizjon-himars-za-414-mln-dolarow-umowa-w-srode
https://milmag.pl/himars-dla-polski/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
