### ISSUE TITLE
FOV update for Pantsir (HotShot FCR radar)

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2083]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6055

### Summary of Changes

Radar is PESA.

In the wikipedia video (link in sources) it is visible that the FCR arc (I think that what it is) is 60 (standard for PESA).

According to the other source HORIZONTAL FOV is 90 degrees (that is how I understand the below quote of ±45° of arc). This is probably only for search.

So I think we should keep it at 60 (standard for PESA).

Quote from source:
Beamsteering angles of up to ±45° of arc;
Mechanical PESA boresight steering in elevation between -5° and 82°;

### Sources

http://www.ausairpower.net/APA-Engagement-Fire-Control.html#mozTocId659890

https://en.wikipedia.org/wiki/File:%D0%97%D0%B5%D0%BD%D0%B8%D1%82%D1%87%D0%B8%D0%BA%D0%B8_%D0%91%D0%B0%D0%BB%D1%82%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D1%84%D0%BB%D0%BE%D1%82%D0%B0_%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D0%BB%D0%B8_%D1%81%D1%82%D1%80%D0%B5%D0%BB%D1%8C%D0%B1%D1%8B_%D0%B8%D0%B7_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81%D0%BE%D0%B2_%C2%AB%D0%9F%D0%B0%D0%BD%D1%86%D0%B8%D1%80%D1%8C-%D0%A11%C2%BB_%D0%B2_%D1%80%D0%B0%D0%BC%D0%BA%D0%B0%D1%85_%D1%82%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F_%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F_%D0%9F%D0%92%D0%9E.ogv

**Comment by rob76pl** [comment]
You may also want to consider 90 degrees FOV based on and ±45° of arc claim;
http://www.ausairpower.net/APA-Rus-PLA-PD-SAM.html#mozTocId944172

The new engagement radar is claimed to have a 45° off boresight deflection angle, yielding coverage inside a 90° solid angle, with mechanical elevation to provide up to 85° of vertical angular coverage. It can track 20 targets and automatically prioritise the top three for engagement, and four missiles can be concurrently gathered and tracked.

**Comment by Huib18** [comment]
90 degrees FOV
![Clipboard01](https://user-images.githubusercontent.com/60408110/186929474-de5db986-2547-400d-9d07-623631f49197.jpg)
[https://www.youtube.com/watch?v=UOHQteNdzmk](url)
@10 seconds in de video

**Comment by rob76pl** [comment]
Yep, it does like like 90. Upon closer examination the Wikipedia video link also shows 90 degree arc (and not 60 degree as I originally thought).

**Comment by rob76pl** [comment]
Hi,

Is there anything pending this relatively straightforward update to be integrated with DB?

**Comment by PygmalionOfCyprus** [comment]
Mount sensors have 360deg arcs to indicate their ability to turn; scan interval is covered in a separate field. This limitation is now modelled as of the sim-side update that restricts arcs for illuminating FCRs.
