### ISSUE TITLE
(1/3) AS.550C2 Fennec for the Royal Danish Army

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2085]
### DB Selector

DB3K

### DBID to Copy

DB3k Aircraft 1530

### Hypothetical

No

### Name

AS.550C2 Fennec

### Country

Denmark

### Service

Army

### In Commission

1990-Present

### Number in Service

12x

### Sensors

Emerson HeliTOW sight (Visual + IR)
Remove Generic FLIR

### Mounts

None

### Loadout Options

- 4x BGM-71D TOW-2
- Unarmed Surveillance

### Other Changes

Crew should be 2, on the Singaporean one as well. You'd need four arms otherwise.
No other weapons fits known to be purchased, although a whole pile are available.

### Sources

http://www.airbushelicopters.com/w1/jrotor/80/Transoriental.html
https://en.wikipedia.org/wiki/Royal_Danish_Army#Army_Aviation_Troops
https://en.wikipedia.org/wiki/Eurocopter_Fennec#Specifications_(AS550_C3)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
