### ISSUE TITLE
(2/3) AS.550C2 Fennec for the Royal Danish Air Force

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2086]
### DB Selector

DB3K

### DBID to Copy

DB3k Aircraft 1530

### Hypothetical

No

### Name

AS.550C2 Fennec

### Country

Denmark

### Service

Air Force

### In Commission

2003-Present

### Number in Service

12x

### Sensors

Retain Generic FLIR (it's not on the aircraft in some images so this might actually be role fit?)

### Mounts

None

### Loadout Options

- Unarmed Surveillance
- 4x Troops
![image](https://user-images.githubusercontent.com/109925704/186522026-e2ab66b4-814a-4af7-9599-7f143f44ba7f.png)

### Other Changes

TOWs removed. Some sources say 12 aircraft, some say 8, I suspect that 8 is the current number after attrition and 12 is the number transferred in 2003.

### Sources

http://www.airbushelicopters.com/w1/jrotor/80/Transoriental.html
https://en.wikipedia.org/wiki/Royal_Danish_Army#Army_Aviation_Troops
https://en.wikipedia.org/wiki/Eurocopter_Fennec#Specifications_(AS550_C3)
https://web.archive.org/web/20110926161849/http://forsvaret.dk/FTK/omflyvev%C3%A5bnet/Factsheets/Documents/hwkar_rettet.pdf
https://www.forsvaret.dk/en/organisation/airforce/structure-of-the-air-force/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
Handled 497.
