### ISSUE TITLE
(3/3) AS.550C2 Fennec Iraq Mod for the Royal Danish Air Force

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2087]
### DB Selector

DB3K

### DBID to Copy

DB3k Aircraft 1530

### Hypothetical

No

### Name

AS.550C2 Fennec

### Country

Denmark

### Service

Air Force

### In Commission

2005-2006

### Number in Service

x3

### Sensors

Generic FLIR

### Mounts

None

### Loadout Options

- 2x Terma FASE (AN/AAR-54 MAWS + Countermeasures), Unarmed Surveillance
- 4x Troops

### Other Changes

Two ridiculously large pods on the old TOW stubs to provide protection for the aircraft during the RDAF Fennec deployment to Iraq. It looks like there's a more advanced variant of this system on Dutch Apache, I should also write that up...

### Sources

https://moam.info/amase-dircm-pod-during-flight-certification-testing-in-the-terma_5a3286b41723dd8944ed4103.html

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
