### ISSUE TITLE
171 Kedah OPV have hangar instead of just a helipad. And also it have 2x davit for RHIB.

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#209]
### DB Selector

DB3K

### Affected DBID(s)

1483 Kedah [Meko 100]

### Summary of Changes

Kedah-class have a hangar facilities that can hold a medium-sized helicopter instead of just a helipad. Please change the "open parking" into a hangar that can hold a medium helicopter, alongside a helipad that can hold a medium helicopter instead of small one. As per Naval Technology:

"The OPV has a helicopter landing deck to support a medium-sized helicopter. The helideck is equipped with a landing system for locking and sliding the helicopter for stability. A hangar facility is also provided for a single helicopter."

below is the screenshot from CMO:
![image](https://user-images.githubusercontent.com/99646926/154538422-8e92f2aa-8032-478f-94ad-0e022f6ee068.png)

And here is the pics of the hangar and the location of the davits:
![image](https://user-images.githubusercontent.com/99646926/154539165-acc7496b-0cb6-4466-997c-f8eafc12eb20.png)
![image](https://user-images.githubusercontent.com/99646926/154539277-d8dfd8e5-cb28-4548-b3f9-9c07d7677197.png)

### Sources

https://www.naval-technology.com/projects/kedah-class-patrol/
http://ilovesabah.info/tldm-open-day/
https://daisetsuzan.blogspot.com/search/label/Kedah-class?m=0

**Comment by Jkryos** [comment]
Fixed DB3K 493.
