### ISSUE TITLE
China, BZK-005 Sensor package [ISAR]

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2095]
### DB Selector

DB3K

### Baseline

sensor 6073

### Hypothetical

No

### Name

BZK-005 UAV Sensor package [ISAR]

### Sensor Generation

Late 2010s

### Range (nm)

100nm

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Range Information, Speed Information, Heading Information

### Search/Track Frequencies

D Band (1-2 GHz) [Old L Band] 15-30 cm, E Band (2-3 GHz) [Old S Band] 10-15 cm

### Sources

https://en.wikipedia.org/wiki/Harbin_BZK-005
https://twitter.com/RupprechtDeino/status/1241321199717801985/photo/3
![image](https://user-images.githubusercontent.com/107970049/186796372-7f76068f-2733-4ca4-bc78-4e78ad825fc9.png)

**Comment by LuigiP57** [comment]
#2094

**Comment by PygmalionOfCyprus** [comment]
Covered by generic rn.
