### ISSUE TITLE
Aircraft entry #4894 Isreali F-15E is incorrect

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#21]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4894

### Description of Problem

Looks like somebody started this but didn't finish. Should be F-15I with Israeli systems and weapons beyond the Rampage. US never sold them an E variant but C's, D's and I's. (I is export variant of E).

### Recommended Fix

 Maybe delete the entry and just add a Rampage loadout to #4776

**Comment by tbrandon517** [comment]
Sorry to zombie this but kind of shower thought and maybe not worth a new request but could this possibly have be intended to be the 2919 D model counterpart to this DB entry for the 2019 Israeli F-15C?

https://cmano-db.com/aircraft/4819/
