### ISSUE TITLE
HTMS Pattani P 511 have a helicopter hangar instead of a helipad

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#210]
### DB Selector

DB3K

### Affected DBID(s)

3235 P 511 Pattani

### Summary of Changes

HTMS Pattani P 511 have a hangar that can hold at least one Lynx ASW helicopter. Please change the "open parking" into a hangar instead.

Below is the screenshot from CMO:
![image](https://user-images.githubusercontent.com/99646926/154541657-312341c9-be8d-4196-a625-e91ae3533127.png)

And below is the pics of the hangar of her sister ship HTMS Narathiwat with hangar:
![image](https://user-images.githubusercontent.com/99646926/154542267-b723d1d9-94cd-4f60-be63-f1bbd34f33b2.png)
![image](https://user-images.githubusercontent.com/99646926/154542354-9c652b06-9e9b-40f3-b960-3f0d16ba61ae.png)

### Sources

https://www.sinodefenceforum.com/t/type-056-class-opv-corvette.5339/page-296
https://en.wikipedia.org/wiki/HTMS_Pattani#/media/File:HTMS_Narathiwat_(512)_during_Milan_2018_exercise.jpg

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
