### ISSUE TITLE
HESA Karrar consume too much fuel

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2102]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4904, 4903, 5591

### Description of Problem

The aircraft consume way too much fuel relative to its size. The engine is Toloue-5 which is based on Microturbo TRI 60 engine. So its fuel consumption isn`t supposed to be a lot higher than BQM-167A Skeeter(Aircraft/5281) which also used the Microturbo TRI 60 engine. Below pics is for the references:

HESA Karrar`s fuel consumption:
![image](https://user-images.githubusercontent.com/99646926/187027762-bee35ded-24c7-4736-a7c2-1aa7a02db344.png)

BQM-167A Skeeter`s fuel consumption
![image](https://user-images.githubusercontent.com/99646926/187027780-455749b2-7008-48fe-b3de-6de71450f04c.png)

### Recommended Fix

Make HESA Karrar`s (Aircraft 4904, 4903 & 5591) fuel consumption similar to BQM-167A Skeeter(Aircraft/5281)

**Comment by PygmalionOfCyprus** [comment]
Recalculated values, much more reasonable now.
