### ISSUE TITLE
#3108 #3109 Hyunmoo 2A and B request

### ISSUE THREAD

**Issue by PKMDECK358** [PygmalionOfCyprus/cmo-db-requests#2103]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #3108, #3109

### Summary of Changes

The Hyunmoo 2A and Hyunmoo 2B are ballistic missiles, but they are implemented as Guided Weapon.

Their range is 300 km and 500 km, respectively.

### Sources

https://missilethreat.csis.org/missile/hyunmoo-2b/
https://missilethreat.csis.org/missile/hyunmoo-2a/
https://en.wikipedia.org/wiki/Hyunmoo#Hyunmoo-2
https://kookbang.dema.mil.kr/newsWeb/20170929/26/BBSMSTR_000000010026/view.do - the Defense Daily of South Korea. The last photo shows the words 'Hyunmoo-2A Ballistic Missile'

**Comment by PygmalionOfCyprus** [comment]
Removed Level Cruise Flight flag. Should fly ballistic trajectory now. 497.
