### ISSUE TITLE
NLD Add CG Biesheuvel

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2108]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Ship, -, Barend Biesheuvel

### Class

Barend Biesheuvel

### Country

Netherlands

### Service

Coastguard

### In Commission

2001 - present

### Number in Service

1

### Length (m)

61.43

### Beam (m)

11

### Draft (m)

4

### Standard Displacement (t)

1240

### Complement

11 (+ 9 extra)

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3516BHD TA. 2 shafts.

### Flank Speed (kt)

18 (src1), 17 (src2)

### Range (nm) at Speed (kt)

unk @ 8.5 kts

### Sensors

2x generic NAV rdars (I & E/F)

### Mounts

None

### Aircraft & Docking Facilities

2x 8m RHIB (35kts) in davits (one on each side). 
Small rescue boat with 1.5t crane.

### Comments

SDWT=200t.

### Sources

1: https://kustwacht.nl/eenheden/barend-biesheuvel
2: https://www.navypedia.org/ships/netherlands/nl_cg_barend_biesheuvel.htm
3: https://www.fleetmon.com/vessels/barend-biesheuvel_9226255_45107
4: https://www.vesselfinder.com/vessels/BAREND-BIESHEUVEL-IMO-9226255-MMSI-245155000
5: https://www.shipspotting.com/photos/3417843
6: https://www.damenshiprepair.com/en/projects/2014/08/coast-guard-vessel-barend-biesheuvel-maintenance
![1](https://user-images.githubusercontent.com/99532490/187272845-8fa684d7-2dba-49a8-8b57-e20f54b1a3b2.jpg)
![2](https://user-images.githubusercontent.com/99532490/187272849-f3f971ef-c9ea-441e-bb20-2866f1bf610d.jpg)
![3](https://user-images.githubusercontent.com/99532490/187272853-2e54c136-8913-42ad-bd61-affae85c6fb7.jpg)
![4](https://user-images.githubusercontent.com/99532490/187272856-5df1caf9-10fa-41fe-9d70-82da7d2a9f04.jpg)
![5](https://user-images.githubusercontent.com/99532490/187272857-4b4c0b44-ab26-40b0-8eb3-8b9ac4413919.JPG)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
