### ISSUE TITLE
EL/M-2022A(V)3, correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2109]
### DB Selector

DB3K

### Affected DBID(s)

Sensor ID 448

### Summary of Changes

Capability
---
Air Search
Altitude info

Code
---
IFF identification capability
SAR capability

### Sources

https://www.iai.co.il/p/elm-2022

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
