### ISSUE TITLE
Add AN/APG-77(V)1 OECM for F-22A Blk 35 Onward

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#211]
### DB Selector

DB3K

### Hypothetical

No

### Name

AN/APG-77(V)1 OECM

### Sensor Generation

Late 2000s

### Sensor Capabilities

Air Search, Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Non-Cooperative Target Recognition (NCTR) - Narrow Beam Interleaved Search and Track [Class Info], Continuous Tracking Capability, Track While Scan (TWS), Low Probability of Intercept (LPI), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA)

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm, J Band (10-20 GHz) [Old X Band] 1.5-3 cm

### Comments

*I filled AN/APG-77(V)1 AESA's properties in capabilities section, because it's mandatory.

I noticed the lack of electronic jamming capability of the F-22 with the (somewhat) new AN/APG-77(V)1 radar, even though the introduction of such capability is publicly well-known.

It should be very similar in performance to the AN/APG-81 OECM, as they are both developed at around the same time by Northrop Grumman, and both influenced another (AN/APG-81 was developed from the earlier AN/APG-77, and the AN/APG-77(V)1 introduced capabilities from AN/APG-81. 

Assuming electronics and software are the same, the AN/APG-77(V)1's larger number of transmitters should in theory makes it slightly more powerful than AN/APG-81's, which is reflected well in the DB (max range). However, this is just a speculation for further consideration, and not a confirmation of whether AN/APG-77(V)1 is a more capable jammer. 

Also, this may impacted the DB of any F-22s that has AN/APG-77(V)1 AESA, as the electronic attack capability was absent for a long time.

### Sources

1. https://news.northropgrumman.com/news/releases/northrop-grumman-delivers-enhanced-radar-for-f-a-22-raptor
2. https://web.archive.org/web/20161123201252/https://www.forecastinternational.com/archive/disp_pdf.cfm?DACH_RECNO=942
3. https://web.archive.org/web/20150924005256/http://www.f22-raptor.com/media/documents/aviation_week_010807.pdf 
(Page 3)
4. https://www.deagel.com/Sensor%20Systems/ANAPG-77/a001562

**Comment by PygmalionOfCyprus** [comment]
Added 494.
