### ISSUE TITLE
NZ, P-3K series and P-8, updates

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2110]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 176, 1478, 3661, 4742

### Summary of Changes

P-3K2
----
**Sensor**
Delete ALR-66, Replace with CS-3054 (ELINT, no detail info)

**COMM**
Link 16

Loadout -Sonobuoys/torpedoes
---
NZ MPA's using Mk46 mod2, Jezebel, and Julie sonobuoys. Those are 70's equipment and they are unlikely used in 90's or later.
Mk46 mod 5 is active in 1979 (based on wikipedia, not C:MO DB), thus it is likely that NZ has it in 1986, as well as AN/SSQ-53/62 sonobuoys. I believe it is no problem with upgrade AN/SSQ-53/62 based on US's P-3Cs until -53D derive to -53D(2) and -53F.

Thus I recommend that,
P-3K (1986): Mk46 mod5 + AN/SSQ-53A + AN/SSQ-62A
P-3K (2001): Mk46 mod5 + AN/SSQ-53D + AN/SSQ-62C
P-3K2 (2012): Mk46 mod 5 + AN/SSQ-53D(3) + AN/SSQ-62E

P-8: Mk54 LWT + AN/SSQ-53G + AN/SSQ-62F

### Sources

http://www.kiwiflyer.co.nz/KiwiFlyer-Issue-17-Orion-P3K2-Upgrade-for-RNZAF.pdf

AN/SSQ-53D(3)
https://youtu.be/9uhS0P12tS4?t=26

NZ buy Mk54 via FMS
https://navalpost.com/ultra-awarded-23-million-for-mk-54-torpedoes/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
