### ISSUE TITLE
Add NLD CG Arca

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2112]
### DB Selector

DB3K

### Hypothetical

No

### Name

Pollution Control Vessel, -, Arca

### Class

Arca

### Country

Netherlands

### Service

Coastguard

### In Commission

1998 - present

### Number in Service

1

### Length (m)

83.2

### Beam (m)

13.1

### Draft (m)

5.7

### Standard Displacement (t)

Not found

### Complement

9 (+ 12 extra)

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3508TA, 2 shafts, fixed pitch

### Flank Speed (kt)

13

### Range (nm) at Speed (kt)

unk @ 8.5 kts

### Sensors

3x unknown NAV radars.

### Mounts

None

### Aircraft & Docking Facilities

3x RHIB or 2x RHIB and small patrol boat (see image)

### Comments

GrossTonnage: 2388, deadweight :2034, Net Tonnage: 716. 
The Arca's funtions are oil slick cleanup (2 sweeparms 15mtr each), Seafloor research, environmental and other coastguard tasks.

### Sources

1: https://kustwacht.nl/eenheden/arca
2: https://www.marinetraffic.com/en/ais/details/ships/shipid:229588/mmsi:244454000/imo:9167966/vessel:ARCA
3: https://www.vesseltracking.net/ship/arca-9167966
4: https://ships.jobmarineman.com/arca-9167966
5: https://www.balticshipping.com/vessel/imo/9167966

![1](https://user-images.githubusercontent.com/99532490/187519325-d9a0ef3a-d496-4956-9037-f526e1357ed7.jpg)
![2](https://user-images.githubusercontent.com/99532490/187519332-0a981d4d-a1ef-4bc1-8ffb-ac12ec952907.jpg)
![3](https://user-images.githubusercontent.com/99532490/187519335-108c6b6a-2b07-4fda-a638-82aedb262ff2.jpg)
![4](https://user-images.githubusercontent.com/99532490/187519337-9d1ab0e5-f44f-4ad4-81c4-7eff7817dca5.jpg)
![5](https://user-images.githubusercontent.com/99532490/187519339-e9405ee1-fa94-48fd-aac2-088b04e67e56.jpg)
![6](https://user-images.githubusercontent.com/99532490/187519342-0717e049-3687-4fa2-a48d-b4a1477251b4.jpg)
![7](https://user-images.githubusercontent.com/99532490/187519350-ad106c24-aefa-4116-a826-34356f60cfb4.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
