### ISSUE TITLE
Add NLD CG Rotterdam

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2113]
### DB Selector

DB3K

### Hypothetical

No

### Name

Buoy Tender, -, Rotterdam

### Class

Rotterdam

### Country

Netherlands

### Service

Coastguard

### In Commission

1987 - present

### Number in Service

3

### Length (m)

44.23

### Beam (m)

10.27

### Draft (m)

3.1

### Standard Displacement (t)

Not found

### Complement

6

### Primary Propulsion Type

Diesel

### Propulsion

2x Brons-MAN

### Flank Speed (kt)

12

### Range (nm) at Speed (kt)

Not found

### Sensors

3x Nav radar (2x I-band, 1x E/F-band)

### Mounts

None

### Aircraft & Docking Facilities

1x RHIB

### Comments

GrossT:514. 
Buoy/Lighthouse vessel, salvage vessels, icebreaker, Oil Pollution cleanup and other coastguard tasks. 
Rotterdam, Terschelling & Frans Naerebout.

### Sources

1: https://kustwacht.nl/eenheden/frans-naerebout
2: https://www.vesselfinder.com/nl/vessels/FRANS-NAEREBOUT-IMO-8802674-MMSI-245387000
3: https://www.vesselfinder.com/vessels/TERSCHELLING-IMO-8802662-MMSI-245384000
4: https://www.fleetmon.com/vessels/frans-naerebout_8802674_57852/photos/150100
5: https://www.fleetmon.com/vessels/rotterdam_8609888_58122

![1](https://user-images.githubusercontent.com/99532490/187526187-1a39d819-198c-4f25-b5b5-5387970ef53b.jpg)
![2](https://user-images.githubusercontent.com/99532490/187526191-03d4eb71-ecb7-40d7-a354-737059c798f3.jpg)
![3](https://user-images.githubusercontent.com/99532490/187526193-3997f4f9-b655-444e-bc35-860e2af6bb0d.jpg)
![4](https://user-images.githubusercontent.com/99532490/187526200-f8c42cba-ae2a-4d97-867c-bc7a421b6c95.JPG)
![5](https://user-images.githubusercontent.com/99532490/187526203-e34f5cc6-9274-4ed9-b98e-dc938473b1a8.jpg)
![6](https://user-images.githubusercontent.com/99532490/187526205-b51ac580-64f6-4cf4-831f-83820ad1d032.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
