### ISSUE TITLE
USSOCOM Sky Warden Armed Overwatch programme copy #4472 - IOMAX Blk 2 [AT-802U] (UAE - 2013)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2118]
### DB Selector

DB3K

### DBID to Copy

#4472

### Hypothetical

No

### Name

AT-802USky Warden

### Country

USA

### Service

USAF

### In Commission

2026

### Number in Service

75

### Sensors

As copy.

### Mounts

Chaff/Flare dispensers?

### Loadout Options

As copied aircraft plus: 

Add 14 x APKWS  + 2 x Mk-82 - fixed wing loadout.

Add 38 x APKWS .

2 X HMP-400 gun pods and 4 x Mk-82(?) LDGP bombs. / 

Six pylons' combinations of gun pods bombs GBU-12 and APKWS and GBU possibly including
#2259 - GBU-54(V)1/B LJDAM [Mk82]
#617 - AGM-114M Hellfire II
#2855 - GBU-53/B StormBreaker

Also shown with 2 x SCAR Self contained aerial reconnaissance pods. 

### Other Changes

Probable SATCOM link 16 etc. Secure HF VHF comms. 

### Sources

https://strikehold.net/2021/05/08/presenting-the-at-802u-sky-warden-isr-strike-aircraft/#:~:text=The%20AT-802U%20Sky%20Warden%20is%20based%20on%20the,by%20the%20company%E2%80%99s%20extensive%20turnkey%20ISR%20operation%20experience.

https://www.key.aero/article/ussocom-orders-75-802u-sky-wardens-armed-overwatch-duty

https://802u.com/

https://www.airbornetechnologies.at/airborne-technologies/isr-turnkey-solutions/s-c-a-r-pod

**Comment by tbrandon517** [comment]
Additional source 

https://www.thedrive.com/the-war-zone/modified-crop-duster-chosen-for-special-ops-armed-overwatch-mission

**Comment by PygmalionOfCyprus** [comment]
Already added 496 as part of a routine weekly news roundup.

**Comment by KLABDB3K** [comment]
May not be the US official title but apparently the marketing term O/A-8 Skywarden has been spun by the company?
Also noted that the DB entry does not have armoured protection, but it should be at least 7.62 NATO AP resistant over cockpit and key areas?
https://802u.com/aircraft-capabilities/aircraft-survivability/
