### ISSUE TITLE
Project 12700 Aleksandrit

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#212]
### DB Selector

DB3K

### Hypothetical

No

### Name

Project 12700 Aleksandrit

### Class

Project 12700 Aleksandrit

### Country

Russia

### Service

Navy

### In Commission

2016-Present

### Length (m)

61.0 m

### Beam (m)

10.2 m

### Draft (m)

2.70 hull 3.68 max

### Standard Displacement (t)

620

### Full Displacement (t)

890

### Complement

44-45

### Primary Propulsion Type

Diesel

### Propulsion

2 M-503M1 diesels

### Flank Speed (kt)

16.5 knots

### Range (nm) at Speed (kt)

1,600 nmi at 10 knots

### Sensors

Pal-N radar, MTK-201M3.1, SP-520M-2 E/O detectors, MG-757 Anapa sonar

### Mounts

1st in Class: 2 x 1 Igla SAM (8 9M39), 1 x 6 - 30/54 AK-306, 1 x 1 - 12.7/79, mines, Aleksandrit-ISPUM, Diamand mine countermeasures systems, OUKT-B, PKT-B mechanical, Zhelatin multispectre, ShAT-U acoustic minesweeping gear

others: 2 x 1 Igla SAM (8 9M39), 1 x 6 - 30/54 AK-306, 1 x 1 - 14.5/89, mines, Aleksandrit-ISPUM, Diamand mine countermeasures systems, OUKT-B, PKT-B mechanical, Zhelatin multispectre, ShAT-U acoustic minesweeping gear

### Aircraft & Docking Facilities

The vessel features a mine countermeasures automated control system. Each vessel is capable of employing traditional mine-sweeping equipment, including Diamond mine countermeasures systems, OUKT-B, PKT-B, Zhelatin and ShAT-U.

The vessel also deploys remotely operated vehicles (ROVs), autonomous underwater vehicles (AUVs) and unmanned surface vessels (USVs).

### Comms/Datalinks

Struktura-35 underwater [communication](https://www.naval-technology.com/contractors/navigation/) system and Ruberoid communication complex

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

New class of minesweepers, original design presumed French-designed and built mine countermeasures systems. Completion of the lead ship was delayed due to French refusing of delivery contract and the need to rebuild a ship for Russian equipment

### Sources

https://en.wikipedia.org/wiki/Alexandrit-class_minesweeper
https://www.naval-technology.com/projects/project-12700-mine-countermeasures-vessels/
https://www.navypedia.org/ships/russia/ru_ms_aleksandr_obukhov.htm
![Тральщик__Александр_Обухов_](https://user-images.githubusercontent.com/99599482/154544161-b4470a1a-46ec-48fb-9c5a-3b91beb76d54.jpg)

**Comment by PygmalionOfCyprus** [comment]
We actually already tackled this one earlier in the cycle as part of our work on the old tracker. :)
