### ISSUE TITLE
Add NLD CG Guardian

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2121]
### DB Selector

DB3K

### DBID to Copy

1002 (DB3K)

### Hypothetical

No

### Name

Emergency Towing Vessel, - ,Guardian

### Country

Netherlands

### Service

Coastguard

### In Commission

(2013 build (Ievoli Amaranth), Rented by NLD CG from 2016 and named Guardian.

### Number in Service

1

### Sensors

2x NA RADAR (I-band & E/F-band)

### Mounts

None

### Other Changes

Offshore Tug/Supply Ship specially in bad weather. 
GrossT: 2637, (S)DWT: 1456. 
Previous (civilian) name IEVOLI AMARANTH.

### Sources

1: https://kustwacht.nl/eenheden/guardian
2: https://www.vesselfinder.com/nl/vessels/GUARDIAN-IMO-9637363-MMSI-246911000
3: https://www.marinetraffic.com/en/ais/details/ships/shipid:272999/mmsi:246911000/imo:9637363/vessel:GUARDIAN
4: https://nlflag.nl/index.php/two-dutch-flagged-tugs-bring-container-vessel-safety

![1](https://user-images.githubusercontent.com/99532490/187746984-374a5884-18c0-42f1-a49b-14653c1d175d.jpg)
![2](https://user-images.githubusercontent.com/99532490/187746987-4029c8ef-a397-4269-8138-ab5534c3d44b.jpg)
![3](https://user-images.githubusercontent.com/99532490/187746988-9e3c3d4e-ab40-4538-9e9e-41cdf1bd0b52.jpg)
![4](https://user-images.githubusercontent.com/99532490/187746990-833c819b-8ca9-462c-babd-906dcf7b2e5d.JPG)
![5](https://user-images.githubusercontent.com/99532490/187746991-fcfa5f6c-f5d0-47cd-bd80-41ab66667cc7.jpg)

**Comment by Parel803** [comment]
+ One small RHIB in a crane

**Comment by Parel803** [comment]
Complement=12. 
2xMAK 8M32C diesels.

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
