### ISSUE TITLE
Add NLD CG Multraship Commander

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2122]
### DB Selector

DB3K

### Hypothetical

No

### Name

Emergency Response Towing Vessel (ERTV), -, Multraship Commander

### Class

Multraship

### Country

Netherlands

### Service

Coastguard

### In Commission

Build 2006 (as civil) name Magnas, 2015 (civil) name Alp Ace, 2022 (rent) NLD CG name Multraship Commander

### Number in Service

2

### Length (m)

58.55

### Beam (m)

14.8

### Draft (m)

7.65

### Standard Displacement (t)

GrossT: 1767, (S)DWT: 3480t

### Complement

24

### Max Sea State

5+

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN B&W 14V32/40

### Flank Speed (kt)

17.5

### Range (nm) at Speed (kt)

unk @ 11.6

### Sensors

2x Furuno NA Radars (I-band & E/F-band)

### Mounts

None

### Aircraft & Docking Facilities

1x RHIB/Rescue boat by crane

### Comments

Offshore / Achor handling Tug.
198 ton Bollard Pull.
2nd unit is the ex-(civilian) Alp Ippon.
Both units are rented from a civilian company.

### Sources

1: https://kustwacht.nl/eenheden/multraship-commander
2: https://kustwacht.nl/nieuws/multraship-commander-de-nieuwe-noodhulpsleper-van-de-kustwacht
3: https://www.marinetraffic.com/en/ais/details/ships/shipid:362750/mmsi:244830809/imo:9344966/vessel:MULTRASHIP_COMMANDER
4: https://www.vesselfinder.com/nl/vessels/MULTRASHIP-COMMANDER-IMO-9344966-MMSI-244830809

![1](https://user-images.githubusercontent.com/99532490/187752816-aa990953-ba1f-41fb-b415-d2a7eb3982d0.jpg)
![2](https://user-images.githubusercontent.com/99532490/187752821-094211b6-c824-44cf-981e-8cf8d9592548.jpg)
![3](https://user-images.githubusercontent.com/99532490/187752822-def5e1e6-c2e1-4996-af52-1b9e50656333.jpg)
![4](https://user-images.githubusercontent.com/99532490/187752823-2122f616-3876-48fc-8bb9-339ee2ded70b.jpg)
![5](https://user-images.githubusercontent.com/99532490/187752829-34ec1aa5-4f2b-42b8-8fbf-7469a8634161.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
