### ISSUE TITLE
Add Kenya Archangel (Safe boats) PC

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2124]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Craft, , Archangel

### Class

Archangel (Safe Boats)

### Country

Kenya

### Service

Navy

### In Commission

2006 - present

### Length (m)

12.8

### Beam (m)

4

### Draft (m)

0.8

### Standard Displacement (t)

11

### Full Displacement (t)

13

### Complement

4

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar C9

### Flank Speed (kt)

40

### Range (nm) at Speed (kt)

300 nm @ 25 kts

### Sensors

1x NA Furuno radome I-band

### Mounts

1x single 12.7mm/90

### Ship Codes

All Aluminum Construction

### Comments

High Speed inshore craft
Possible the Safe boats Full Cabin Inboard

### Sources

1: JFS 2015/2016
2: https://www.navypedia.org/ships/kenya/ken_cf_archangel.htm
3: https://pdf.nauticexpo.com/pdf/safe-boats/catalog/20867-107932.html
4: https://safeboats.com/wp-content/uploads/SAFE-Boats-Catalog.pdf

![1](https://user-images.githubusercontent.com/99532490/187779106-e2aec96c-1b63-4a6b-8eef-b80d911ceb75.jpg)

**Comment by Parel803** [comment]
by images looks like Bahamas 3589 (SAFE 44) but slighter differ in specs (iaw sources)

**Comment by Jkryos** [comment]
Added DB3K 497.
