### ISSUE TITLE
Name rationalisation for UK Apache

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2127]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4842

### Summary of Changes

The name of the AH-64E in UK service should match the format of the WAH-64D's name so that they appear next to each other in the database and for consistency. New suggested name:

Apache AH.Mk.2 [AH-64E]

### Sources

Internal renaming, although I don't think the AH.2 name for AH-64E is actually technically confirmed.

**Comment by PygmalionOfCyprus** [comment]
Handled 497. I'll leave the AH.2 name for now but we can always remove it later.
