### ISSUE TITLE
Canada, CH-148, update

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2128]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2779

### Summary of Changes

General
---
Name: CH-148A→CH-148
Belongs to Royal Air Force (not navy)

Mounts
----

2x AN/ALE-39 (30x chaff + 30x Flare? for each)

Sensors
---
Generic MAWS→2x AN/AAR-47
Ganeric LWR?- no source, does it exist?
Safire 3, It looks like Safire 3 can look all 360 angle.
APS-143B(V)3 (Sensor ID 2679)- add code SAR, IFF

Code
---
Fly-by Wire

COMMS
---
HF-9087D (HF Radio)
AN/ARC-210 (VHF/UHF)
Link 11

Loadouts
---
ASW Sonobouys: 16x AN/SSQ-53F DIFAR + 8xAN/SSQ-62E DICASS

### Sources

https://en.wikipedia.org/wiki/Sikorsky_CH-148_Cyclone

http://jproc.ca/rrp/rrp3/ch148_electronics.html

APS-143
https://www.telephonics.com/product/aps-143cv3-oceaneye

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
