### ISSUE TITLE
Increase Seeker range to 21.5nm (9B-1388 type) for 40N6 Missile S-400

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2129]
### DB Selector

DB3K

### Affected DBID(s)

2104

### Summary of Changes

40N6 has a larger seeker housing nose cone than the smaller R-77-1 or 9M96 active radar missiles. It doesn't make sense having a smaller range than the R-77 let alone the R-37 that has a larger size nose cone.

9B-1388 used on R-37 which is similar in size to the 40N6 has a 40km range for 5m2 target (21.5nm).  But the 40N6 nose cone seeker housing is even larger than the R-37, but a fair start would be to assume a similar performance the the 9B-1388 design.

40N6 just like the R-37 is meant for anti-AWAC, anti-EW and factoring in the larger size compared to R-77/9M96 should have a larger ARF seeker like the 9B-1388 with an increased range. 
![download](https://user-images.githubusercontent.com/108960393/188044355-51ce7b77-768e-4284-9ac3-666ef39ad230.jpg)
![Capture](https://user-images.githubusercontent.com/108960393/188044356-c5999b12-3371-44f1-b4e6-3713f5d983e2.PNG)

Currently there is no known figure for the exact range, this is just based off the nose cone size compared to other active radar missiles and the types of targets its meant for similar to the R-37 (EW platforms, AWAC, ELINT, etc). But 10nm is even less than the much smaller R-77 seeker range.

### Sources

https://en.missilery.info/missile/r37

https://www.globalsecurity.org/military/world/russia/izdeliye-610.htm

http://www.ausairpower.net/APA-Rus-BVR-AAM.html

https://www.google.com/search?q=9B-1388+range&rlz=1C1CHBF_enUS778US778&oq=9B-1388+range&aqs=chrome..69i57.1540j0j4&sourceid=chrome&ie=UTF-8

**Comment by PygmalionOfCyprus** [comment]
Okay, fair enough. Usually I'm not keen on making changes without stronger evidence but you're right that, logically, it doesn't make much sense for the seeker to be outclassed by smaller missiles, esp. those with similar roles. Handled 497.

**Comment by TheBagelInhaler** [comment]
> Okay, fair enough. Usually I'm not keen on making changes without stronger evidence but you're right that, logically, it doesn't make much sense for the seeker to be outclassed by smaller missiles, esp. those with similar roles. Handled 497.

Gdoesn't make much sense for the seeker to be outclassed by smaller missiles, esp. those with similar roles. Handled 497.

Great, thank you! Also please consider adding EL-2090 Terra (consists of 2 radars UHF and S Band). It might be simple to add since you may be able to do a copy entry for each radar (UHF is based of green pine A and S band is based of EL-2084 with much longer range and 100% anti-ballistic role. Whereas UHF is anti-ballistic and anti-air to a max range of 500km. Check it out, I just discovered India was using it since early 2021, and it looks like a beast of an ABM and air defense radar system
