### ISSUE TITLE
Add Georgia Dioskuria (FPB)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2132]
### DB Selector

DB3K

### DBID to Copy

#936 [La comabttante II]

### Hypothetical

No

### Name

Fast Attack Craft, 303, Dioskuria

### Country

Georgia

### Service

Navy

### In Commission

Greece 1971-2004, Georgia 2004-2014

### Number in Service

1

### Sensors

 Castor is mentioned instead of Pollux, prob same serie FCR

### Mounts

2 twin - 35mm/90 GDM-A instead of 2x twin 30mm/75 Oerlikon Emerlec-30

### Other Changes

cf source 1 some minor changes:
Displacement standard - 345
Displacement - 265
Complement - 40

### Sources

1: https://www.navypedia.org/ships/georgia/geo_cf_dioskuria.htm
![1](https://user-images.githubusercontent.com/99532490/188261131-77fca5cd-cbbd-466d-8ff2-5db0f4812d82.jpg)
![2](https://user-images.githubusercontent.com/99532490/188261132-c0eef96c-97fe-4ddf-b537-c7823caf356e.jpg)
![3](https://user-images.githubusercontent.com/99532490/188261133-0e2bd1ab-4e79-4602-9e36-9950f2635903.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
