### ISSUE TITLE
M64 500lb, M65 1000lb, M66 200lb GPB correction (CWDB)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2134]
### DB Selector

CWDB

### Affected DBID(s)

1567, 1568, 1569

### Summary of Changes

The old American general purpose bombs in CWDB actually had more powerful warheads. "Approximately 50 percent of the complete weight of the bomb consists of explosive filler." "The AN series of designs used a lighter-weight higher-strength steel casing with the goal of having up to 65% of the finished bomb weight be explosive material." They were also filled with Tritonal in the 50s and 60s.

M64:
length: 1.5m
span: 0.48m
diameter: 0.36m
weigth: 247kg
warhead: [128kg/283lb Tritonal] (192 DP)

M65:
length: 1.7m
span: 0.645m
diameter: 0.48m
weigth: 472kg
warhead: [270kg/595lb Tritonal] (405 DP)

M66:
length: 2.3m
span: 0.8m
diameter: 0.59m
weigth: 988kg
warhead: [536kg/1181lb Tritonal] (804 DP)

reduce CEP to 50m as with the other GPBs in CWDB.

### Sources

https://bulletpicker.com/bomb_-500-lb-gp_-an-m64a1.html
https://bulletpicker.com/bomb_-1000-lb-gp_-an-m65a1.html
https://bulletpicker.com/bomb_-2000-lb-gp_-an-m66.html

http://michaelhiske.de/Allierte/USA/USNBD/USA/BombsAndFuzesUS/Section01/Part04/Page059.htm
https://en.wikipedia.org/wiki/Mark_65_bomb#cite_ref-3

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
