### ISSUE TITLE
Add Japan ShinMaywa US-2

### ISSUE THREAD

**Issue by arrag** [PygmalionOfCyprus/cmo-db-requests#2137]
### DB Selector

DB3K

### Baseline

PS-1

### Hypothetical

No

### Name

US-2

### Country

Japan

### Service

JMSDF

### In Commission

2003-Present

### Number in Service

6

### Length (m)

33.46

### Wingspan (m)

33.15

### Height (m)

9.8

### Empty Weight (kg)

25630

### Maximum Takeoff Weight (MTOW) (kg)

47700

### Crew

11

### Propulsion

4 X Rolls-Royce AE 2100J Turboprop, 3,424 kW

### Service Ceiling (ft)

23606

### Military/Afterburner Speed (kt)

300

### Cruise Speed (kt)

260

### Supercruise

No

### Ferry Range (nm)

2300

### Sensors

1x Mk1 Eyeball
1x Generic MAD
1x Generic Surface Search Radar 

### Mounts

Generic Active Sonobuoy
Generic Passive Sonobuoy
Generic Torpedo Mount [US-1 had type 73 torp mount]

### Loadout Options

Ferry
Maritime Surveillance
Sonobuoys, Search-only (ASW Patrol) [40 Passive sonobuoys, 40 Active sonobuoys]
Search & Rescue (SAR)

### Comms/Datalinks

Generic Sonobuoy Receiver
UHF/VHF Radio Unsecure
UHF/VHF Radio Secure
HF Radio Secure
HF Radio Unsecure
Link16

### Aircraft Codes

Fly-by-Wire

### Comments

This is a STOL amphibious platform with upgraded avionics from the US-1. This platform can land in 3m seas.

### Sources

https://www.shinmaywa.co.jp/english/news/pdf/09-02-19.pdf
https://en.wikipedia.org/wiki/ShinMaywa_US-2
https://www.shinmaywa.co.jp/aircraft/english/us2/index.html

**Comment by KC45jp** [comment]
US-1/2 is SAR only Aircraft (no ASW mission, PS-1 did ASW) + while flying boat does not simulated in C:MO, I do not think this aircraft is worth to add for now.  PS-1 in CWDB has this problem already... and not working correctly.

**Comment by arrag** [comment]
> US-1/2 is SAR only Aircraft (no ASW mission, PS-1 did ASW) + while flying boat does not simulated in C:MO, I do not think this aircraft is worth to add for now. PS-1 in CWDB has this problem already... and not working correctly.

There is an amphib C-130 in the database that can drop LRASM out the cargo door using the Rapid Dragon system - A modern ASW seaplane using an existing platform is not a huge leap. As far as modeling flying boat mechanics goes I hope that comes in the future but that shouldn't prevent other amphibs from being added as the US-2 has gear.
