### ISSUE TITLE
Add Senegal Archangel (fm SAFE Boats)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2139]
### DB Selector

DB3K

### Baseline

As request: Generic #930, Kenya #2124

### Hypothetical

No

### Name

Patrol Craft, -, -

### Class

Archangel (SAFE Boats)

### Country

Senegal

### Service

Navy

### In Commission

2010 - present

### Number in Service

1

### Length (m)

12.8

### Beam (m)

4.1

### Draft (m)

0.8

### Standard Displacement (t)

Not found

### Full Displacement (t)

13

### Complement

6 (src1), 3 (src2)

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar C9, 2 RR FF3753 waterjets

### Flank Speed (kt)

36

### Range (nm) at Speed (kt)

300 @ 25 (src1), 400 @ 21 (src2)

### Sensors

I-Band Furuno NA RADAR

### Mounts

2x single 7.62mm/90 MG's

### Comments

Alu & RIB construction

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/senegal/sen_cf_archangel.htm
3: https://pdf.nauticexpo.com/pdf/safe-boats/full-cabin-archangel/20867-13183.html

![1](https://user-images.githubusercontent.com/99532490/188490825-97566143-10a5-439f-9914-e9647cadba5c.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
