### ISSUE TITLE
Vehicle (1x Milos Unmanned Ground Combat Vehicle)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#214]
### DB Selector

DB3K

### Hypothetical

No

### Name

Vehicle (1x Milos Unmanned Ground Combat Vehicle)

### Facility Type

Mech

### In Commission

2017-Present

### Crew

0

### Dispersion Radius (m)

0

### Sensors

thermal camera, a day and night camera, and a laser ranger. Two day/night cameras are installed on front and back for driving.

### Mounts

It has one or two weapons attached on its turret.

1x Zastava M86 7.62mm machine-gun 

and

1x M11 grenade launcher, 
or 
1x RBR M90 Stršljenand 
or
other armament options including smoke grenades

### Magazines

No Reloads

### Aircraft & Docking Facilities

N/A

### Comments

Serbian unmanned ground combat vehicle. Can be deployed via helicopter. Trial from 2017, IOC 2020, 5 units initially.

### Sources

https://www.thedrive.com/the-war-zone/37034/serbian-helicopters-blowing-up-targets-is-among-the-best-anti-tank-missile-footage-weve-seen
https://en.wikipedia.org/wiki/Milo%C5%A1_(unmanned_ground_vehicle)
https://www.janes.com/defence-news/news-detail/serbia-advances-milos-ugv-development
https://defence-blog.com/serbia-to-launch-mass-production-of-new-milos-unmanned-ground-vehicles/
https://www.armyrecognition.com/defense_news_september_2020_global_security_army_industry/serbian_army_demonstrates_efficiency_of_milos_n_armed_ugv.html
https://www.forbes.com/sites/kelseyatherton/2020/09/21/serbias-robot-tanklet-can-ride-helicopters-into-battle/?sh=f3a30f277d96
https://www.army-technology.com/projects/milos-unmanned-ground-vehicle/
https://www.youtube.com/watch?v=dzwrbISnSBM

![275px-Miloš_robotizovana_platforma](https://user-images.githubusercontent.com/99599482/154549434-001d8c99-8be8-496c-b261-7726d489fc12.jpg)
![DUBP_Miloš_-_Takovo_2020_-_02](https://user-images.githubusercontent.com/99599482/154549446-1c3d4e94-1a33-44f3-9a51-7e8508a9e5c7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Little robot tankettes are, like quadcopters, etc. a little too small/generic to warrant specific addition IMO. If more of these start to appear as anything more than a novelty/police aid then we can look at adding a generic entry like we did w/ the quadcopters.
