### ISSUE TITLE
Add Senegal Ferlo (Raidco RPB 33)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2140]
### DB Selector

DB3K

### DBID to Copy

3672 Togo, 3678 Ivory Coast. Req: #679 Togo, #784 IC

### Hypothetical

No

### Name

Patrol Boat, -, Ferlo

### Country

Senegal

### Service

Navy

### In Commission

2013 - present

### Number in Service

1

### Mounts

1x single 12.7mm/90 MG
2x single 7.6/90 MG

### Other Changes

Class: Ferlo (Raidco RPB 33)

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/senegal/sen_cf_ferlo.htm
3: https://www.naval-technology.com/projects/rpb-33-offshore-patrol-boat

![1](https://user-images.githubusercontent.com/99532490/188492848-6f978adf-f43d-4419-8e14-ae66c17d021f.jpg)
![2](https://user-images.githubusercontent.com/99532490/188492850-efde9537-b2aa-44f5-af16-5d326ffcafd8.jpg)
![3](https://user-images.githubusercontent.com/99532490/188492852-66ed914b-b0f3-408b-a16a-a3c9e620679d.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
