### ISSUE TITLE
Add Senegal navy Alphonse Fay (Raidco RPB 20)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2141]
### DB Selector

DB3K

### Baseline

Req: #574 Gabon

### Hypothetical

No

### Name

Patrol Boat, -, Enseigne de Vaisseau Alphonse Faye

### Class

Alphonse Faye (Raidco RPB20)

### Country

Senegal

### Service

Navy

### In Commission

2004 - present

### Number in Service

2 navy (+2 Customs)

### Length (m)

20

### Beam (m)

5.29

### Draft (m)

1.45

### Standard Displacement (t)

32

### Full Displacement (t)

42

### Complement

8

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN V12, 2 shafts

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

530 @ 15 (src1), 600 @ 18 (src2)

### Sensors

1x Furuno I-band NA RADAR

### Mounts

1x single 7.6mm/90 MG

### Aircraft & Docking Facilities

4.7 m RHIB Aft

### Comments

Images are from Navy & Customs versions

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/senegal/sen_cf_alphonse_faye.htm
3: https://www.nauticexpo.com/prod/raidco-marine/product-22737-264115.html
4: https://www.homelandsecurity-technology.com/projects/vedette-cotiere-de-surveillance-maritime-boats

![1](https://user-images.githubusercontent.com/99532490/188495825-ace0ab93-9a83-461c-81a0-f9cc920c7c85.jpg)
![4](https://user-images.githubusercontent.com/99532490/188495826-bc212da6-632b-45c1-9d0b-4b6e9726778b.jpg)
![Custom-3](https://user-images.githubusercontent.com/99532490/188495827-07c07122-b537-4258-9902-8fe6a53850e3.jpg)
![Custum-2](https://user-images.githubusercontent.com/99532490/188495829-70f84943-d632-4338-b09c-7d0ffd4aa58e.jpg)

**Comment by Parel803** [comment]
shipcode: GRP hull

**Comment by Parel803** [comment]
Src2 calls Customs version RPB20E. Sangomar class.

**Comment by Jkryos** [comment]
Added DB3K 497.
