### ISSUE TITLE
Add Senegal CTM (Landing Craft)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2142]
### DB Selector

DB3K

### DBID to Copy

3697 (Ivory Coast), Req: #786

### Hypothetical

No

### Name

Landing Craft, -, - (CTM Class)

### Country

Senegal

### Service

Navy

### In Commission

French 1965 - 1999, Senegal 1999 - present

### Number in Service

1

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/senegal/sen_ls_ctm2.htm
3: https://en.wikipedia.org/wiki/Chaland_de_transport_de_mat%C3%A9riel

![1](https://user-images.githubusercontent.com/99532490/188558959-771070e8-9398-4f04-b978-3dd67aecfefc.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
