### ISSUE TITLE
Add Morocco CTM class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2143]
### DB Selector

DB3K

### DBID to Copy

DB: 3697 (IC), Req: #786, #2142

### Hypothetical

No

### Name

Landing Craft, -, -. CTM class

### Country

Morocco

### Service

Navy

### In Commission

France 1965 - 2000, Morocco 2000 - present

### Number in Service

1

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/morocco/mo_ls_ctm.htm

![1](https://user-images.githubusercontent.com/99532490/188596770-8b684ad5-f553-4b78-b528-7953b8779b1e.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
