### ISSUE TITLE
Range Issue or Yemen 126 [Hounan Class] - 1995, 3x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2144]
### DB Selector

DB3K

### Affected DBID(s)

ship 2471

### Summary of Changes

Ranges is much less that the other Osa and Osa Clone missile boats. Sources indicates range should be 800nm at 30 kts. Currently ships have about a 300nm range at 30kts. Looks like fuel is less that the other Osa type boats.

### Sources

https://www.globalsecurity.org/military/world/china/huangfeng-specs.htm

http://navypedia.org/ships/yemen_south/yes_cf_126.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
