### ISSUE TITLE
Vietnam - HQ 375 [Pr.1241.8 Tarantul V] - 2013 - Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2145]
### DB Selector

DB3K

### Affected DBID(s)

ship 2418

### Summary of Changes

Vietnamese Tarantul V's are armed with a AK-176M 76 mm gun rather than the 57mm/75 A-220M.

### Sources

http://navypedia.org/ships/vietnam/vie_es_hq375.htm

https://en.wikipedia.org/wiki/Tarantul-class_corvette#Project_1242.1/1241.8_'Molniya'

![image](https://user-images.githubusercontent.com/99599482/188628781-c4ef150a-e65d-4bac-a37a-529ddfa5bc64.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
