### ISSUE TITLE
Scout RADARS are FMCW

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2146]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 1836, 2637, 5683

### Summary of Changes

Listed as a Pulsed-Only radars.
Believe it to be a FMCW LPI radars.

### Sources

1: https://www.radartutorial.eu/19.kartei/07.naval/karte026.en.html
2: https://www.navyrecognition.com/index.php?option=com_content&view=article&id=1568
3: https://www.thalesgroup.com/sites/default/files/database/document/2021-04/SCOUT%20Mk3-V04.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
