### ISSUE TITLE
Canada Bird Class Patrol Vessel x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2147]
### DB Selector

CWDB

### Hypothetical

No

### Name

PCS 780 HMCS Loon

### Class

Bird Class

### Country

Canada

### Service

Navy

### In Commission

1955-65

### Number in Service

4

### Length (m)

28

### Beam (m)

5.2

### Draft (m)

1.6

### Standard Displacement (t)

66

### Complement

21

### Primary Propulsion Type

Diesel

### Propulsion

2x Diesels

### Flank Speed (kt)

14

### Range (nm) at Speed (kt)

1200@14

### Sensors

- Radar: Canadian Marconi LN27 navigation radar
- Sonar: Type 163A (common to 164AAO)

### Mounts

- 1x 20mm Oerlikon AA (aft?)
- 1x Hedgehog A/S fwd (port/stb launchers)
- Depth charges

### Comms/Datalinks

-  Five sloping flattop wire antennas between the foremast and the support on the aft end of the funnel. This gave the vessel HF CW capability.
- Three UHF antennas, type AT-150SRC, positioned on the port,  starboard and aft positions of the foremast yardarms. This suggests three UHF voice circuits so in all likely hood the URR-35 receiver and URT-502 (TED3) combination was fitted which was the norm for that era.
- One VHF vertical dipole mounted in the forward position, foremast yardarm. This Implies VHF aeronautical distress capability

### Ship Codes

Wooden Hull Construction

### Comments

Pictures are unclear on where the AA is placed, attached a few below.

### Sources

- http://jproc.ca/rrp/bird.html
- Janes 1959-60, pg 88
 
![image](https://user-images.githubusercontent.com/99632305/188711268-b8760adf-d50f-4979-bbee-d1bf290e126a.png)
http://www.forposterityssake.ca/JPGs/PHOTO-DIR/SWNG/00197.jpg
https://www.naval-encyclopedia.com/wp-content/uploads/2020/12/Mallard-PCS783.jpg
[(https://hamiltonnaval.ca/wp-naval-content/uploads/2020/01/Cormorant-781.png)](https://hamiltonnaval.ca/wp-naval-content/uploads/2020/01/Cormorant-781.png)

**Comment by Jkryos** [comment]
Added CWDB 497.
