### ISSUE TITLE
Add Morocco P107 (RPB20)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2148]
### DB Selector

DB3K

### Baseline

Req: #574, #2141

### Hypothetical

No

### Name

Patrol Boat, P107, -

### Class

P107 (Raidco RPB20TE)

### Country

Morocco

### Service

Navy

### In Commission

2006 - present

### Number in Service

11

### Length (m)

20

### Beam (m)

5.29

### Draft (m)

1.5

### Standard Displacement (t)

42

### Full Displacement (t)

32

### Complement

8

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN 2842 LE413

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

660 @ 18

### Sensors

1x Furuno M1932 NA RADAR

### Mounts

1x single 12.7mm/90 MG
2x single 7.6mm/90 MG

### Aircraft & Docking Facilities

4.9 mtr RHIB at stern ramp

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/morocco/mo_cf_107.htm
3: https://www.losbarcosdeeugenio.com/barcos/en/ma/mor_115.html
4: https://www.nauticexpo.com/prod/raidco-marine/product-22737-264115.html

![1](https://user-images.githubusercontent.com/99532490/188718889-800f6487-0b5b-4cce-9ebe-0821150c3545.jpg)
![2](https://user-images.githubusercontent.com/99532490/188718894-f35ddf7e-58d2-41d3-b894-465d4d741574.JPG)
![5](https://user-images.githubusercontent.com/99532490/188718897-9d360c4c-c045-4c7d-81b3-1b9eb335acbc.jpg)
![6](https://user-images.githubusercontent.com/99532490/188718899-59b32d99-a296-4a2e-8466-00bdbc7aa913.jpg)
![8](https://user-images.githubusercontent.com/99532490/188718902-39522191-f958-4490-9bda-9475dc889a97.jpg)
![9](https://user-images.githubusercontent.com/99532490/188718905-024079c1-c0ae-4acd-873e-6999b620f7c8.jpg)
![10](https://user-images.githubusercontent.com/99532490/188718911-8bd99f6c-999b-47ac-b4c7-1c7abc1d99e3.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
