### ISSUE TITLE
VAMPIRE (Vehicle-Agnostic Modular Palletized Isr Rocket Equipment)

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#2152]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

VAMPIRE (Vehicle-Agnostic Modular Palletized Isr Rocket Equipment)

### Facility Type

SAM

### Country

United States

### Service

unknown

### In Commission

expected 2023

### Number in Service

none

### Crew

1

### Dispersion Radius (m)

unknown

### Sensors

Distributed Aperture Semi-Active Laser Seeker (DASALS)
Mk I Eyeball

### Mounts

NTV (Non-Tactical Vehicles), anything with a flatbed

### Magazines

4 x APKWS II

### Aircraft & Docking Facilities

none

### Comments

Surface to surface
Surface to Air
Anti-UAS

### Sources

https://militaryleak.com/2022/05/10/l3harris-unveils-vehicle-agnostic-modular-palletized-isr-rocket-equipment-vampire/
https://www.c4isrnet.com/newsletters/2022/08/25/vampire-to-transform-ukraine-pickups-into-deadly-missile-launchers/
https://www.l3harris.com/sites/default/files/2022-08/L3Harris_ims-isr-Vampire_SellSheet_2022_A.pdf
https://news.yahoo.com/american-vampire-weapon-could-crush-085156928.html

**Comment by tbrandon517** [comment]
Additional

https://www.defensenews.com/newsletters/2022/08/25/vampire-to-transform-ukraine-pickups-into-deadly-missile-launchers/?utm_source=facebook&utm_medium=social&utm_campaign=fb_c4isrnet&fbclid=IwAR2V1uvfMEzNvZt_soixSf4IXNtsN5sv6zYa46AcBtR6pwtMVZln19PueMg

**Comment by PygmalionOfCyprus** [comment]
Wait, this is already in the DB. Ground Unit 374.
