### ISSUE TITLE
A/A: APKWS IIA Could delete some loadout

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2155]
### DB Selector

DB3K

### Affected DBID(s)

a lot

### Summary of Changes

Aircraft
---
We can think that this loadout available only for F-16?
 
Loadout
---
As far as I know, A/A APKWS ⅡA is likely only available for A/A mission, but not for any A/G mission. This is not a replacement of AIM-9 sidewinder, thus any A/G loadout with A/A APKWS 2A could be deleted.

At the same time, A/A loadout could be modified by adding AIM-9, because, as I wrote, it is not the replacement.
I believe we should make loadout based on A/G Hydra mission loadout, thus  2x AIM-120, 2x AIM-9, 14x or 28x (or 56x?) APKWS, sensor/targeting pod and droptanks is should be better.

DB could be deleted
----
27538-27570
27573-27596

relate
---
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1358
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1187
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1833

### Sources

https://www.military.com/daily-news/2019/12/23/f-16-shoots-down-drone-test-new-cruise-missile-defense.html

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Loadouts were not deleted (for backwards compat) but removed from aircraft.

**Comment by KC45jp** [comment]
Thank you very much!
