### ISSUE TITLE
OQQ-21 Hull sonar

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2157]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5088

### Summary of Changes

Operating Band
---
VLF

Capability
---
Mine & Obstacle Search

### Sources

https://ja.wikipedia.org/wiki/%E6%B5%B7%E4%B8%8A%E8%87%AA%E8%A1%9B%E9%9A%8A%E3%81%AE%E3%82%BD%E3%83%8A%E3%83%BC#OQQ-21

**Comment by KC45jp** [comment]
For note (for future),
multi-static capability added in 2017
https://www2.njss.info/offers/view/8995831

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
