### ISSUE TITLE
OQQ-21 Frank Array

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2158]
### DB Selector

DB3K

### Hypothetical

No

### Name

J/OQQ-21 Frank Array

### Sensor Generation

Late 2000s

### Range (nm)

40? (unknown)

### Sensor Capabilities

Submarine Search, Mine & Obstacle Search, Range Information, Speed Information, Heading Information

### Search/Track Frequencies

VLF Sonar (0-1000 Hz, 200 Hz Center Frequency)

### Comments

Used by Hyuga class (DB Ship 480)
Frank Array is exclusively used by Hyuga class in JMSDF 

### Sources

https://ja.wikipedia.org/wiki/%E6%B5%B7%E4%B8%8A%E8%87%AA%E8%A1%9B%E9%9A%8A%E3%81%AE%E3%82%BD%E3%83%8A%E3%83%BC#OQQ-21

**Comment by Jkryos** [comment]
Added DB3K 505.
