### ISSUE TITLE
Add Morocco Rodman 101

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2163]
### DB Selector

DB3K

### DBID to Copy

#2842 (Cameroon)

### Hypothetical

No

### Name

Patrol Boat, 130, - (Rodman 101 class)

### Country

Morocco

### Service

Navy

### In Commission

2009 - present

### Number in Service

10

### Sensors

2x (instead of 1x) Furuno NA radar

### Mounts

3x (instead of 1x) 12.7mm/90 MG

### Other Changes

Engines: 2x Caterpillar 3412C, 2 waterjets.
Flank speed 30 kts with 800nm @ 12 kts (iaw src1&2).
1x Small RHIB at stern.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/morocco/mo_cf_130.htm
3: https://www.losbarcosdeeugenio.com/barcos/en/ma/mor_133.html
4: https://rodman.es/en/producto/professional-nautical/patrol-boats/rodman-101

![1](https://user-images.githubusercontent.com/99532490/189065070-a4d1e1ff-a99d-41ac-803b-f3cbd1a0fb6f.jpg)
![3](https://user-images.githubusercontent.com/99532490/189065075-4b26826b-a8cb-4b65-b9d7-7d3f398ab657.jpg)
![6](https://user-images.githubusercontent.com/99532490/189065080-5872e06b-6a17-4054-8ef5-9df64f0953b7.jpg)
![7](https://user-images.githubusercontent.com/99532490/189065083-7588ceec-0be4-4bf9-8467-4c6c458ae3b9.jpg)
![8](https://user-images.githubusercontent.com/99532490/189065086-2ee19965-c1b7-4277-b8bb-72e41479eccd.jpg)
![9](https://user-images.githubusercontent.com/99532490/189065088-eab95ee5-18ca-4884-a37a-37710556a40d.jpg)
![13](https://user-images.githubusercontent.com/99532490/189065089-a9a38baf-2220-4bf4-9802-0939e4480f36.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
