### ISSUE TITLE
Add Morocco 323 (RN Bird class)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2164]
### DB Selector

DB3K

### DBID to Copy

#1526 UK

### Hypothetical

No

### Name

Patrol Boat, 323, - (Bird class)

### Country

Morocco

### Service

Navy

### In Commission

2004 - present

### Number in Service

1

### Mounts

Replace both with 2x single 7.6mm/90 MG

### Other Changes

Some minor differnce with sources on dimensions and speed.
UK 1976-1997, 1997 - 2004 privat owned.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/morocco/mo_cf_323.htm

![1](https://user-images.githubusercontent.com/99532490/189092338-489d266d-a2b0-4f88-8b84-5f328dfc049f.jpg)
![2](https://user-images.githubusercontent.com/99532490/189092344-8f98e808-21b9-426b-adf0-944c7468aa85.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
