### ISSUE TITLE
#4248 - AH-64A Apache (UAE - 2015) Hellfire and out of service date updates

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2169]
### DB Selector

DB3K

### Affected DBID(s)

#4248 - AH-64A Apache (UAE - 2015)

### Summary of Changes

Add AGM-114 Variant loadouts various date to AH-64A/D orders:
Possibly add out of service date 2016 as most upgraded from A to D  models - following 2008/2009 FMS order?
#683 - AGM-114K Hellfire II
#527 - AGM-114N Hellfire II [Thermobaric]
#2736 - AGM-114R Hellfire II

All ordered via FMS.

### Sources

https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-apache-ah-64e-helicopters-and-services
https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-agm-114-rk-hellfire-category-iii-missile - 2016 order.
https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-agm-114r3-hellfire-missiles -2011 order.
https://www.dsca.mil/press-media/major-arms-sales/uae-hellfire-missiles-aircraft-survivability-equipment - 2009 order

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
