### ISSUE TITLE
Copy AH-64D Apache Longbow and add to UAE from 2008/2009 please. x 30 AH-64A upgrade. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2170]
### DB Selector

DB3K

### DBID to Copy

#503 - AH-64D Apache Longbow (Kuwait - 2000) or similar AH-64D

### Hypothetical

No

### Name

#503 - AH-64D Apache Longbow (UAE - 2009)

### Country

UAE

### Service

Army

### In Commission

2009

### Number in Service

30 (possibly some lost in Yemen - will check)

### Sensors

As base model.

### Mounts

No change from copy.

### Loadout Options

loadouts to include 3 x AGM-114 variants. See linked request for AH-64A
#683 - AGM-114K Hellfire II
#527 - AGM-114N Hellfire II [Thermobaric]
#2736 - AGM-114R Hellfire II
To include APKWS- loadouts. 
#2597 - HYDRA APKWS II 70mm Rocket [WGU-59/B, Rotary Wing Launch]

### Other Changes

See AH-64A UAE load outs requests.

AH-64A were upgraded to D standard. So possibly amend out of service date for A models due to phased changeover?

### Sources

https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-agm-114r3-hellfire-missiles
https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-apache-ah-64e-helicopters-and-services
https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-agm-114-rk-hellfire-category-iii-missiles

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
