### ISSUE TITLE
Copy #4434 - AH-64E Apache Guardian (Qatar - 2020) and add to UAE Army 2018 30+ units. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2171]
### DB Selector

DB3K

### DBID to Copy

#4434 - AH-64E Apache Guardian (Qatar - 2020)

### Hypothetical

No

### Name

AH-64E Apache Guardian (UAE - 2018/19) Army

### Country

UAE

### Service

ARMY

### In Commission

2018-2019?

### Number in Service

37?

### Sensors

NIL - AS COPY

### Mounts

No change 

### Loadout Options
#683 - AGM-114K Hellfire II
#527 - AGM-114N Hellfire II [Thermobaric]
#2736 - AGM-114R Hellfire II

Various AGM-114/Hydra/APKWS
AGM-114K
AGM-114R
AGM-114N
APKWS

### Other Changes

NIL Suggested in service date from 2018 to 2019 based on order date of December 2017. 
Upgrades of AH-64D and new builds. 

### Sources

https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-apache-ah-64e-helicopters-and-services
https://www.dsca.mil/press-media/major-arms-sales/united-arab-emirates-agm-114-rk-hellfire-category-iii-missiles

**Comment by Jkryos** [comment]
Added DB3K 497.
