### ISSUE TITLE
Ukrainian Su-27s viewed with HARMs

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#2173]
### DB Selector

DB3K

### User(s)

UKR Su-27S, DBID 353

### Weapons Carried

2x AGM-88B HARM
2x AA-10 Alamo
2x AA-11 Archer

(From what I could tell from the picture)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As per loadout ID 26877

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

-Could be wrong about the photo, but it's what I saw. 
-Used four-Alamo loadout as a baseline for endurance as it's what it's the most similar to. 

### Sources

https://twitter.com/UAWeapons/status/1568199283278548995/photo/1

**Comment by Jkryos** [comment]
Added DB3K 497.

**Comment by tbrandon517** [comment]
@Jkryos @PygmalionOfCyprus these loadouts seem to have disappeared in v502

**Comment by PygmalionOfCyprus** [comment]
My dumbass removed them from the Su-27s when reworking the S/S1M/UB/UB1M distinctions and forgot to add them back. Fixed 503.

In the interim, they're still available in the DB as Loadout 32033, so you can add w/ Lua in a pinch.
