### ISSUE TITLE
Zambia - FT-6 [Export JJ-6] Missing guns in DB3k

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2174]
### DB Selector

DB3K

### Affected DBID(s)

DB3K aircraft 5058

### Summary of Changes

Add missing internal guns. Guns present in CWDB version of the aircraft, CWDB aircraft 4101.

### Sources

DB 495

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
