### ISSUE TITLE
Peruvian MI-26T out of service date of 2008

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#219]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1433

### Summary of Changes

Out of service by 2008. Peru had a hard time selling them for scrap.

### Sources

https://www.scramble.nl/military-news/peru-finds-scrap-dealer-for-army-mi-26ts
https://www.airway1.com/peruvian-army-puts-on-sale-three-mi-26s-the-largest-helicopter-in-the-world/

**Comment by Jkryos** [comment]
Fixed DB3K 493.
