### ISSUE TITLE
South Korea F-15K GBU-31 Loadout Request

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#2190]
### DB Selector

DB3K

### User(s)

ROKAF F-15K 2007-2020

### Weapons Carried

GBU-31(v)
GBU-31(v) [BLU-109/B]

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

The ROKAF's F-15K can operate the GBU-31(V) JDAM as well as the F-15E. Similarly, GBU-31(V) BLU-109 is also operational.

### Sources

https://youtu.be/bFXBkXrb4sI
![KakaoTalk_20220916_023307263](https://user-images.githubusercontent.com/66541619/190472308-5c92dafa-b05a-49ab-a73a-f6ae6320a7e2.jpg)
![KakaoTalk_20220916_023339490](https://user-images.githubusercontent.com/66541619/190472318-99a6eeff-5cb3-4712-a848-c5443eb0d124.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.

**Comment by clerara10** [comment]
> Added DB3K 497.

Thanks Can you also add CBU-105 WCMD loadout in F-15K?
