### ISSUE TITLE
AB.212 for Austria

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2193]
### DB Selector

DB3K

### DBID to Copy

DB3k Aircraft 5120

### Hypothetical

No

### Name

AB.212

### Country

Austria

### Service

Air Force

### In Commission

1980-Present

### Number in Service

26x

### Loadout Options

Honestly I struggle with how the 'new' cargo system works. They're used as utility helicopters, troop transports, mountain rescue aircraft and just about anything else you can make a Huey do. They need Cargo loadouts, I'm not clear if they need Troop loadouts any more or if people are now a cargo and they need an 'empty' SAR loadout like the Canadian 212's 30528.

### Sources

https://www.bundesheer.at/waffen/waf_bell212.shtml
https://www.helis.com/database/org/Austrian-Air-Force/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
