### ISSUE TITLE
OH-58B Kiowa for Austria

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2194]
### DB Selector

DB3K

### DBID to Copy

DB3k Aircraft 2908

### Hypothetical

No

### Name

OH-58B Kiowa

### Country

Austria

### Service

Air Force

### In Commission

1976-Present

### Number in Service

12x

### Mounts

7.62mm Minigun retained

### Sources

https://www.bundesheer.at/waffen/waf_belloh.shtml
https://www.helis.com/database/org/Austrian-Air-Force/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
