### ISSUE TITLE
OH-58B Kiowa for Austria - Border Patrol Fit

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2195]
### DB Selector

DB3K

### DBID to Copy

Issue #2194

### Hypothetical

No

### Name

OH-58B Kiowa (Border Patrol)

### Country

Austria

### Service

Air Force

### In Commission

1998?

### Number in Service

2x

### Sensors

Generic FLIR
Nitesun Searchlight
![image](https://user-images.githubusercontent.com/109925704/190519326-cb75449a-9daa-476e-9699-404ae4d12168.png)

### Sources

https://www.flightglobal.com/austria-ready-to-modernise/28971.article
https://www.oesterreich.gv.at/en/themen/leben_in_oesterreich/oesterreich_in_der_eu/Seite.249203.html - Austria had to enforce Schengen Treaty obligations since 1998, best guess at a date

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
