### ISSUE TITLE
Alouette III for Austria

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2196]
### DB Selector

DB3K

### DBID to Copy

DB3k Aircraft 3097

### Hypothetical

No

### Name

SA.316B Alouette III

### Country

Austria

### Service

Air Force

### In Commission

1967-Present

### Number in Service

29x

### Loadout Options

Cargo, troops and SAR. Primary Austrian Mountain Rescue type.

### Sources

https://www.bundesheer.at/waffen/waf_alouette.shtml
https://www.helis.com/database/org/Austrian-Air-Force/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
