### ISSUE TITLE
JH-7 A2A loadouts lack datalink

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#2199]
### DB Selector

DB3K

### Affected DBID(s)

All JH-7s with air to air loadouts

### Description of Problem

JH-7s with the new air to air loadouts in DB3K 496 cannot fire PL-12s as they lack the necessary datalink. The semi-active PL-11s launch without any issue. 

### Recommended Fix

Add the same datalink that other PL-12 capable platforms have.

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
