### ISSUE TITLE
Add new J-15 heavy AAW loadout. 4 PL-12, 4 PL-8B, Wingtip Jammers

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#22]
### DB Selector

DB3K

### User(s)

2496, 3311

### Weapons Carried

 4 PL-12, 4 PL-8B, Wingtip Jammers

### Requires Buddy Illumination

- [ ] Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

- [ ] Yes

### Comments

Carrier deck photo circulating with new AAW loadout. 4 PL-12, 4 PL-8B, Wingtip Jammers

### Sources

https://twitter.com/RupprechtDeino/status/1392134991937683460

**Comment by Jkryos** [comment]
Added DB3K 493.
