### ISSUE TITLE
AS-2 Kipper AS-10P OECM Drone (Aircraft #1687) throws and exception error in the viewer

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2200]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 1687

### Description of Problem

If you select the Kipper OECM drone in the viewer the game throws an exception error. Developer reports it may be a propulsion error of some sort so reporting here.

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=388383&p=5035185#p5035185

**Comment by PygmalionOfCyprus** [comment]
Was an issue in the code re: displaying certain propulsion types, handled in dev builds.

**Comment by bostonmyk** [comment]
Yeah its fixed in latest release. Thanks!
