### ISSUE TITLE
LandCeptor Bty can engage 1 target at a time due to a single datalink channel

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2201]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3269

### Summary of Changes

Land Ceptor Bty has only 1 datalink, hence only able to engage 1 target at a time. According to MDAA it is able to engage 24 targets at a time (all effectors can be used simultaneously). This was a design principle behind the system (to defend against saturation attacks). So I think datalink channels number should be increased to 24.

Quote:
'Ultimately, the Sky Sabre system is capable of controlling 24 missiles simultaneously under saturation attacks of up to 24 separate targets, a major upgrade from the Rapier system.'

'The computer system can control 24 missiles simultaneously and guide them to intercept 24 separate targets.'

### Sources

https://missiledefenseadvocacy.org/defense-systems/sky-sabre/
https://www.army-technology.com/projects/sky-sabre-air-defence-system-united-kingdom/

**Comment by PygmalionOfCyprus** [comment]
Deisgnator mistakenly had a missile DL instead of the command DL. Handled 497.
