### ISSUE TITLE
Hypothetical, PLAAF, J-16 Flying Shark, PL-21 VLRAAM Platform

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2204]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4926

### Hypothetical

Yes

### Name

J-16 Flying Shark, 2024

### Country

China

### Service

PLAAF

### In Commission

2024

### Sensors

-

### Mounts

-

### Loadout Options

New Loadout:
A/A 6x PL-21, 2x PL-10, DECM Pod, Standard CAP
A/A 2x PL-21, 2x PL-15, 2x PL-10, DECM Pod
A/A 2x PL-21, 2x PL-10, DECM Pod, Light

### Sources

https://en.wikipedia.org/wiki/PL-21
![image](https://user-images.githubusercontent.com/107970049/190884849-c7f649f6-e071-49b9-b091-f1351988eaaa.png)

**Comment by PygmalionOfCyprus** [comment]
How does this differ from just adding PL-17 loadouts to the J-16?

**Comment by LuigiP57** [comment]
> How does this differ from just adding PL-17 loadouts to the J-16?

No. It's just a legacy issue
