### ISSUE TITLE
PL-21 Loadout for J-16 Flying Shark, 2024

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2205]
### DB Selector

DB3K

### User(s)

J-16 Flying Shark, 2024

### Weapons Carried

A/A 6x PL-21, 2x PL-10, DECM Pod, Standard CAP
A/A 2x PL-21, 2x PL-15, 2x PL-10, DECM Pod
A/A 2x PL-21, 2x PL-10, DECM Pod, Light

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://en.wikipedia.org/wiki/PL-21
https://militarywatchmagazine.com/article/world-s-top-seven-most-dangerous-standoff-air-to-air-missiles-from-european-meteors-to-russian-r-37s

**Comment by LuigiP57** [comment]
#2204

**Comment by PygmalionOfCyprus** [comment]
Gonna close this one as a duplicate since the loadout is described in the main ticket.
