### ISSUE TITLE
Most RAF Victors have 25kg fuel capacity

### ISSUE THREAD

**Issue by TestPilotKerman** [PygmalionOfCyprus/cmo-db-requests#2206]
### DB Selector

CWDB

### Affected DBID(s)

603, 3916, 3917, 2127, 2128, 2129, 2130, 3918

### Description of Problem

Most Victor bomber DBIDs have 25kg fuel capacity. That's not enough for them to have a shot at fulfilling their mission.

### Recommended Fix

Give it fuel.
Working backwards from Wikipedia's info, which is backed up by a direct citation to literature, the B.1 MTOW is 205000 lbs, the max bomb load is 35000 lbs and the empty weight is approximately 89000 lbs. The hard cap on the fuel load for this variant then is 81000 lbs. I couldn't find data for other variants.

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
