### ISSUE TITLE
Hypothetical, J-20B Mighty Dragon, 2024, PL-21 Platform

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2207]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2463

### Hypothetical

Yes

### Name

J-20B Mighty Dragon

### Country

China

### Service

PLAAF

### In Commission

2024

### Sensors

-

### Mounts

-

### Loadout Options

A/A: 4x PL-21(External), 2x PL-10
A/A: 4x PL-21(External), 4x PL-15, 2x PL-10

### Other Changes

I hope you could read this: 
Yesterday, when I was browsing in DB viewer, I happened to find the range of PL-21 (which is 216nm) is almost twice as much as the J-16's radar detection range (which is 120nm).
According to multiple rumors, The PL-21 VLRAAM mainly features AWACS-and-Tanker-killer capability which requires extremely long detection range of a fire control radar. I think J-16's AESA is far from achieving this, but J-16 can still using PL-21 to have an advantage in BVR combat.
However, J-20's AESA makes it possible. With a 200nm detection range, J-20 is able to take full advantage of PL-21. Presently, there is no solid evidence indicating that PLAAF intergrates CEC on its aircraft or weapon. Thus, J-20 should be the best user of this deadly AAM.

### Sources

https://en.wikipedia.org/wiki/PL-21
https://militarywatchmagazine.com/article/u-s-pacific-air-force-chief-evaluates-future-of-china-s-j-20-fighter-an-air-superiority-or-multirole-jet

**Comment by yulianglie** [comment]
saw it in DB496 too, tried to test it by adding it on a random jet, but couldn't find it in neither in add mount or add weapon record list.

**Comment by Jkryos** [comment]
Added DB3K 498.
