### ISSUE TITLE
PL-21 loadut for J-20 Mighty Dragon, 2024

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2208]
### DB Selector

DB3K

### User(s)

J-20 Mighty Dragon, 2024

### Weapons Carried

A/A: 4x PL-21(External), 2x PL-10
A/A: 4x PL-21(External), 4x PL-15, 2x PL-10

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://en.wikipedia.org/wiki/PL-21
https://militarywatchmagazine.com/article/u-s-pacific-air-force-chief-evaluates-future-of-china-s-j-20-fighter-an-air-superiority-or-multirole-jet

**Comment by LuigiP57** [comment]
#2207

**Comment by PygmalionOfCyprus** [comment]
Same deal as #2205, closing as duplicate. (It's not technically, but it's not necessary.)
