### ISSUE TITLE
UK Merlin Helicopters of all variants need a Search and Rescue Loadout please.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#221]
### DB Selector

DB3K

### User(s)

#45 - Merlin HM.1 (United Kingdom - 2000) #1077 - Merlin HM.1 (United Kingdom - 2006) #4279 - Merlin HM.1 (United Kingdom - 2009) #4278 - Merlin HM.1 (United Kingdom - 2009) #3336 - Merlin HM.2 (United Kingdom - 2014) #595 - Merlin HC.3 (United Kingdom - 2002) #4272 - Merlin HC.3 (United Kingdom - 2015) #4274 - Merlin HC.3A (United Kingdom - 2008) #4273 - Merlin HC.4 (United Kingdom - 2018)

### Weapons Carried

Existing weapons mounts for type. Internal fuel. 

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

470

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

**Use or direct copy the existing Danish SAR load out #29538 from #5319 - AW.101 Merlin Mk.512 SAR (Denmark - 2007)
Search And Rescue (SAR)**
Spec is (Search And Rescue (SAR))  470 nm Search And Rescue (SAR) radius. Cruise at 1k ft. No form-up time. 10% reserves. 30 min Day/Night
All-Weather Winchester: Return to base when mission-specific weapons have been expended. Disengage immediately. #29538 

As it stands the UK has NO SAR load outs for any of its modern land or maritime helicopters despite having two sophisticated carriers carrying state of the art F-35B's. The RAF and Royal Navy routinely train all crews for SAR operations and the helos have the requisite NVG compatibility and winches etc. 

### Sources

"Beyond searching for submarines the helicopter is capable of much more, including round-the-clock maritime patrol and interdiction – armed with Sting-Ray Torpedoes, Mk11 Depth Charges and the M3m .50 Calibre Machine Gun; troop ferrying, casualty evacuation, medium lift under-slung loads, **Search and Rescue**, and other contingency tasks."
https://www.royalnavy.mod.uk/the-equipment/aircraft/helicopters/merlin-mk2
https://www.royalnavy.mod.uk/the-equipment/aircraft/helicopters/merlin-mk4 -- Image clearly shows side mounted winch over starboard door.
https://www.flickr.com/photos/rn_topten/6628099407/in/set-72157628698680309/
https://www.royalnavy.mod.uk/news-and-latest-activity/news/2019/october/22/191022-search-and-rescue

**Comment by PygmalionOfCyprus** [comment]
Added 495.
