### ISSUE TITLE
Uruguayan Protector WPB Name Update 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2210]
### DB Selector

DB3K

### Affected DBID(s)

ship 3634

### Summary of Changes

The vessels will be named ROU 14 Rio Arapey, ex Albacore (WPB-87309), ROU 15 Rio de la Plata (ex Cochito - WPD-87329), and ROU 16 Rio Yaguaron (ex Gannet - WPB-87334) and are expected to arrive in Uruguay in November to join the Sea Forces Command.

Update for #338

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/september/12208-uruguayan-navy-receives-three-protector-class-patrol-boats-from-us.html

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
