### ISSUE TITLE
Advance Brazilian Scorpene Riachuelo in service date to 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2211]
### DB Selector

DB3K

### Affected DBID(s)

628

### Summary of Changes

Advance in service date to 2022.

### Sources

https://www.navalnews.com/naval-news/2022/09/video-brazil-commissions-its-first-scorpene-type-submarine/
https://tecnodefesa.com.br/submarino-riachuelo-sera-incorporado-a-marinha-na-proxima-semana/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
