### ISSUE TITLE
Add Iraqi Ground Master 403 Radar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2212]
### DB Selector

DB3K

### DBID to Copy

2182

### Hypothetical

No

### Name

Radar (GM 403 Ground Master)

### Country

Iraq

### Service

Air Force

### In Commission

2022

### Number in Service

x2

### Sources

https://twitter.com/IiiTango/status/1569674486437511173
https://www.janes.com/defence-news/news-detail/iraq-inaugurates-first-gm403-radar
https://youtu.be/hF_Ycmgcjjw?t=54

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
