### ISSUE TITLE
Hamerkop nuclear glide bomb for South Africa 

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2213]
### DB Selector

DB3K

### Baseline

DB3k Weapon 2238

### Hypothetical

No

### Name

Hamerkop

### Length (m)

As H-2

### Width/Span (m)

As H-2

### Diameter (m)

As H-2

### Weight (kg)

As H-2

### Range (nm)

As H-2

### Target Altitude / Depth (ft)

As H-2

### Target Speed (kts)

As H-2

### Launch Altitude / Depth (ft)

As H-2

### LaunchSpeed (kts)

As H-2

### Warhead

20kT nuclear warhead (gun type?)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

As H-2

### Sensors

EO Seeker

### Comments

Fundamentally, it's an H-2 with a nuclear weapon in it. There are even suggestions that H-2 stands for Hamerkop 2. Intended for use on the Buccaneers, presumably using the same loadouts as the H-2 except with the Hamerkops. I'm happy to put together a ticket for that loadout if it's needed.

### Sources

https://www.armscontrolwonk.com/archive/1200544/revisiting-south-africas-bomb/

**Comment by tbrandon517** [comment]
Duplicate of #1555

**Comment by FrangibleCover** [comment]
Added 504!
