### ISSUE TITLE
Add Shahed-136 Kamikaze Drone (Guided Weapon)

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2214]
### DB Selector

DB3K

### DBID to Copy

3271

### Hypothetical

No

### Name

Shahed-136

### Country

Iran

### Service

IRGC

### In Commission

2019-present

### Number in Service

200+

### Sensors
GLONASS/GPS/SATCOM (fixed targets)
Semi-Active Laser (able to be guided by drones/ground laser designator, similar to Krasnopol) (mobile targets)

### Mounts

1x 36kg Warhead

### Loadout Options

-1x Warhead 36kg -1800km max range

### Other Changes

**SPECIFICATIONS:**
Will create separate request for SSM battery similar to HARPY
length: 3.5m
wingspan: 2.5m
combat weight: 200kg with warhead
service ceiling (similar to harop/harpy): 15,000 feet (4.6km)
cruise speed: 120 km/hr, (65 kts)
low altitude: 200 feet
kamikaze speed: 200km/hr (108 kts)
combat range: 1800km
Warhead weight: 36kg
Guidance: GNSS/SATCOM/INERTIAL/Laser Designator (targets pre-determined)
Types of targets: Soft, hard, mobile, fixed
![shahed](https://user-images.githubusercontent.com/108960393/191387829-bcde647c-0833-472f-8e35-9f87eb577251.jpg)

RCS front (A-D bands) - 0.0631m2 / -13 dBsm        RCS side (A-D bands): -10 dBsm      RCS A-D rear: -13 dBsm
RCS front (E-M bands) - 0.009m2 / -21 dBsm        RCS side (E-M bands): -17 dBsm   RCS E-M rear: -21 dBsm
![shahed 136 RCS](https://user-images.githubusercontent.com/108960393/191387743-dc1c918d-fea5-4f02-9e47-69c19a3bfc47.png)

Frontal RCS was calculated using averages of this RCS model from [Dhimas Afihandarin](https://twitter.com/Flankerchan) from Twitter @Flankerchan. side and rear RCS is just an estimate based off Harop/Harpy and mobin
Average of A-D bands was 0.06309573 so 0.0631 rounded up
Average of E-M is 0.0089 so 0.009 rounded up
![rcs](https://user-images.githubusercontent.com/108960393/191387723-c7c7d031-7ba5-40d0-a02f-d36c6d4bc29e.jpg)

![shahed 136 2](https://user-images.githubusercontent.com/108960393/191387846-f30eeffa-b5d3-42ce-865f-c69722596166.jpg)

### Sources

![shahed infographic](https://user-images.githubusercontent.com/108960393/191388116-a5fe6074-e0ff-4391-b8b7-454376e5f4b7.jpg)

https://twitter.com/Flankerchan/status/1572046756657135616

https://news.yahoo.com/ukraines-air-force-explains-shoot-182013394.html

https://www.nytimes.com/2022/09/18/world/europe/iran-attack-drones-ukraine.html

**Comment by Huib18** [comment]
Also used by Russia in the Ukraine.
Called Geran-2 in Russia
https://twitter.com/BNNUkraine/status/1573614584103022592

BTW no evidence that a anti-radar variant is in use in Iran or Russia of the Shahed-136

Also the pictures of www.msai.ir feature net based operations. There is no visible proof of a datallink between the UAS but maybe in the future.

**Comment by Huib18** [comment]
Some details of the engine:
[https://en.defence-ua.com/weapon_and_tech/iranian_shahed_136_kamikaze_drones_already_used_by_russia_first_photos_and_specs-4207.html](url)

**Comment by TheBagelInhaler** [comment]
> Also used by Russia in the Ukraine. Called Geran-2 (Герaнь-2) in Russia [https://twitter.com/josephhdempsey/status/1569616062911549442](url) [https://twitter.com/BNNUkraine/status/1573614584103022592](url)
> 
> Called Wa'id by the Houtis in Yemen. [https://defence.pk/pdf/attachments/1663778724127-png.881479/](url) [https://defence.pk/pdf/attachments/1663778724127-png.881479/](url) ![1663778724127](https://user-images.githubusercontent.com/60408110/192095482-d7d15bec-7bc6-48d4-b2a8-e963803d9547.png)
> 
> BTW no evidence that a anti-radar variant is in use in Iran or Russia of the Shahed-136.
> 
> The pictures of [www.msai.ir](http://www.msai.ir) feature net based operations. There is no visible proof of a datalink between the Shahed-136 UAS but maybe in the future. So no net-based operations yet.
> 
> Attached a picture of the Wa'id

was confirmed to be used on Aramco Facility 2019 attack as well by Houthis using Wa'id variant

Nose cone does look large enough to accommodate in addition to warhead, a passive radar seeker or active radar seeker/maybe even a combination of both. 

Until further proof is known for anti-radar usage, I will edit out for only EO/IR sensors

**Comment by PygmalionOfCyprus** [comment]
Does it actually have EO sensors? I can't see any, and I'm not seeing mention of them in any articles beyond a vague intimation that a "recon payload" is possible. The GNSS/Inertial guidance implies that these things have to have a target plugged in beforehand. They seem more like suicide drones than true "loitering munitions."

**Comment by TheBagelInhaler** [comment]
> Does it actually have EO sensors? I can't see any, and I'm not seeing mention of them in any articles beyond a vague intimation that a "recon payload" is possible. The GNSS/Inertial guidance implies that these things have to have a target plugged in beforehand. They seem more like suicide drones than true "loitering munitions."

I began to notice that upon further scrutiny. Based off recent evidence of usage, the targets used against are mostly stationary/fixed (buildings for example). So a GPS guidance with predeterminted coordinates is more likely.
 Considering there is no visual proof of video evidence leaked to indicate any EOS/IR/TV cam sensors.

However, they were used to strike artillery batteries which may also mean laser designation (since GPS for mobile units like artillery aren't accurate and cam move in short amount of time). So that makes me wonder what sensor were used for that.

Nose cone looks just like Harpy so it can also house a passive radar seeker. But no proof of anti-air defense usage yet. So this needs more info until sensors can be established. But for now no doubt GPS/GLONASS/SATCOM

**Comment by PygmalionOfCyprus** [comment]
Handled 497.

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
