### ISSUE TITLE
Add SSM Shahed-136 Loitering Drone

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2215]
### DB Selector

DB3K

### DBID to Copy

2620

### Hypothetical

No

### Name

Shahed-136

### Country

Iran

### Service

IRGC

### In Commission

2019-present

### Number in Service

200+

### Sensors

1x Mk1 Eyeball (50nm)

### Mounts

3x shahed-136 TEL

capacity: 5

launch interval: 5

Weapons per mount: shahed-136
Targets: Surface ships, land structures hard/soft, mobile units hard/soft. Max speed: 108 kts
Warhead: 36kg
Max Range: 1800km (3333nm)

### Other Changes
2 loadout options:
-attack (1x WARHEAD, GLNASS/SATCOM/Semi-Active Laser)

![images](https://user-images.githubusercontent.com/108960393/191390975-c044160e-9ca4-40cd-b845-0aa30f0967c7.jpg)

### Sources

https://www.jpost.com/international/article-717402

https://eurasiantimes.com/iranian-combat-drones-used-by-russia-are-become-big-irritant-for-ukraine/

https://www.timesofisrael.com/iran-to-launch-country-wide-military-drill-showcasing-its-drone-power/

https://www.nytimes.com/2022/09/18/world/europe/iran-attack-drones-ukraine.html

**Comment by tbrandon517** [comment]
Being used by Russia in Ukraine

https://www.thedrive.com/the-war-zone/russia-has-begun-using-iranian-kamikaze-drones-on-ukraine

**Comment by TheBagelInhaler** [comment]
Was used by Houthis variant Wa'id in Aramco 2019 attack

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
