### ISSUE TITLE
Remove AGM-84E SLAM Loadout

### ISSUE THREAD

**Issue by Tdhla1** [PygmalionOfCyprus/cmo-db-requests#2218]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1118

### Summary of Changes

The F/A-18A cannot operate the AGM-84E SLAM.

### Sources

VFA-203 and VFA-204 which operated the F/A-18A in 1996 were not allocated resources to the operate the SLAM as they operated the F/A-18A not the F/A-18C.

[https://man.fas.org/dod-101/sys/smart/docs/ntsp-agm-84e_slam.pdf](https://man.fas.org/dod-101/sys/smart/docs/ntsp-agm-84e_slam.pdf)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
