### ISSUE TITLE
S-3B Viking -- United States (Navy), 1994, Outlaw Viking

### ISSUE THREAD

**Issue by Tdhla1** [PygmalionOfCyprus/cmo-db-requests#2219]
### DB Selector

DB3K

### Baseline

9

### Hypothetical

No

### Name

S-3B Outlaw Viking

### Country

United States

### Service

Navy

### In Commission

1994-1998

### Number in Service

1

### Length (m)

16.3

### Wingspan (m)

20.9

### Height (m)

6.9

### Empty Weight (kg)

12060

### Maximum Takeoff Weight (MTOW) (kg)

23830

### Crew

4

### Propulsion

2x TF34-GE-2

### Rate of Climb (ft/min)

5120

### Service Ceiling (ft)

40900

### Military/Afterburner Speed (kt)

440

### Cruise Speed (kt)

350

### Supercruise

No

### Ferry Range (nm)

3000

### Takeoff / Landing Distance (m)

451/900

### Fuel Capacity (kg)

5850

### Sensors

1x AN/APS-137(V)1
1x OR-89/AA
1x AN/ALR-76
1x AN/ASQ-81(V)3
1x OASIS III
1x Mk1 Eyeball

### Mounts

- 300 USG Drop Tank
- ADM-141A TALD [Active RF]
- AGM-84D Harpoon IC
- AN/SSQ-53B DIFAR
- AN/SSQ-62B DICASS
- Generic Buddy Store
- Mk46 NEARTIP Mod 5
- Mk50 Barracuda Mod 0 ALWT

### Loadout Options

Tanker [Wing Drogue]
- 1x 300 USG Drop Tank
- 1x Generic Buddy Store

Maritime Surveillance
- 1x 300 USG Drop Tank

AGM-84D Harpoon IC
- 2x AGM-84D Harpoon IC

Mk46 NEARTIP Mod 5
- 2x 300 USG Drop Tank
- 4x Mk46 NEARTIP Mod 5
- 12x AN/SSQ-53B DIFAR
- 12x AN/SSQ-62B DICASS

Mk50 Barracuda
- 2x 300 USG Drop Tank
- 4x Mk50 Barracuda Mod 0 ALWT
- 12x AN/SSQ-53B DIFAR
- 12x AN/SSQ-62B DICASS

ADM-141A TALD [Active RF]
- 2x ADM-141A TALD [Active RF]

### Comms/Datalinks

Generic NATO Sonobuoy Receiver [99 Channels]
UHF/VHF Radio [Secure]
OTCIXS
GPS
SATCOM

### Aircraft Codes

Probe Refuelling, Wing Drogue

### Comments

Aircraft has same loadouts as S-3B Viking, 1990

### Sources

BuNo 160124 was modified as the 'Outlaw Viking'. It was fitted with the OASIS III system as well as GPS, OTCISX and SATCOM. Initally deployed with VS-37 in 1994.
[Airborne Log, Outlaw Viking, Spring 1995](https://p-3publications.com/PDF/S-3Vikings-SpecialProjects.pdf)

**Comment by KushanGaming** [comment]
Done for DB497. Gave it a slightly better OODA Detection/Targeting vs the standard S-3B to account for the better processing, but a lot of what made this unique we don't simulate.
