### ISSUE TITLE
Update and possibly split Polish FA-50

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2222]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5944

### Summary of Changes

There will be two different versions of FA-50 for Poland.

Both versions should be a copy of Aircraft 4955 (Korean FA-50 with Link-16). It seems the current FA-50 (Aircraft 5944) is a copy from the older Korean FA-50 (Aircraft 3183).

First batch of 12 planes should be renamed to Block 10 and will be delivered in 2023. There will be based in Minsk Mazowiecki (not to be confused with the capital of Belarus) Air Base.

Link 16 has been confirmed for first batch in the interview (link in sources). NATO IFF is also confirmed in the first batch.

Sniper Pod has also been confirmed (probably #459 AN/AAQ-33 Sniper XR Pod [FLIR + LRMTS, 40k ft] (2005) - it is unclear in all the sources I found, but XR seems like a good bet. 

Now I see there is both Sidewinder-9S and Sidewinder-9X in the database. Sidewinder-9S is very unlikely to get purchased as it is an old weapon. Based on all the sources it is likely the Block 10 will not have Air-To-Air missiles at all, second best guess would be limited integration if Sidewinder-9X.  So I suggest they are removed from the load out options or it is normalized to use Sidewinder-9X.

Note sniper pod uses the middle pylon. I think we should add it to all loadouts and remove one USG Drop Tank (reduction from 1>0 or 3>2 for loadouts).

Second batch will be 32 aircraft and should be called Block 20, deliveries 2025-2028. Then a conversion of 12 Block 10 AC will be done to Block 20 standard.

Block 20 will have Sidewinder-9X and Weapon #897 AIM-120C-5 AMRAAM P3I.2 (2003) integrated for AtA missions (I guess 2xSidewinder 2x AMI120C loadout needs to be added).

Block 20 will have aerial refueling option: Probe-and-drogue.

### Sources

Interview by gen. Ireneusz Nowak, chief of Air Assets Directorate, deputy inspector of Polish Air Force (link in sources in Polish).
http://www.polska-zbrojna.pl/home/articleshow/37927

Polish government announcement:
https://www.gov.pl/web/obrona-narodowa/samoloty-fa-50-wzmocnia-zdolnosci-sil-powietrznych

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
