### ISSUE TITLE
Sensor - CK032 Periscope (LLTV, EO)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2228]
### DB Selector

DB3K

### DBID to Copy

5882, 5884, 5883

### Hypothetical

No

### Name

CK032 Periscope (LLTV, EO)

### Country

-

### Service

-

### Sensors

1x CK032 EO Component (1980s, 1.5x/12x Zoom)
1x CK032 LLTV Component (1.5x/8x Zoom)

### Other Changes

copy ID 5884 "CK035/CH085 EO Component"
rename/change to: CK032 EO Component (1980s, 1.5x/12x Zoom)

copy ID 5883 "CK035/CH085 LLTV Component"
rename/change to: CK032 LLTV Component (1.5x/6x Zoom)

New Sensor Group CK032 Periscope (LLTV, EO)

image intensifier gain: 30,000

### Sources

The Naval Institute Guide to World Naval Weapons Systems 1997-1998, Norman Friedman, pages 641-642

![c2ec69cc15_62235688](https://user-images.githubusercontent.com/104227721/191860670-b6829317-38b3-4227-b0ef-4b1c93d270ac.jpg)

https://imgur.com/uDeUDsv

> Periskop Barr&Stroud CK032 opremljen za nocno opazovanje

> Periscope Barr & Stroud CK032 equipped for night observation

![20220923_003200](https://user-images.githubusercontent.com/104227721/191863337-d04de54d-253d-4768-aa4c-cbe089a869cb.jpg)
![20220923_003221](https://user-images.githubusercontent.com/104227721/191863341-145eb425-aab6-4e91-99b8-403e213e62d8.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
