### ISSUE TITLE
Patriot MIM-104A/B range correction

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#2232]
### DB Selector

DB3K

### Affected DBID(s)

#1835

### Summary of Changes

Patriot Baseline missile currently has a wrong range - MIM-104A/B(PAC-1) has a range of around 70km [38nm; In-game around 55nm], But MIM-104A missile has a range of 160km (almost 86nm).  MIM-104A should be changed a range of 40nm(70km) ~ 55nm(100km).

### Sources

http://www.designation-systems.net/dusrm/m-104.html
https://defencedb.com/profile_page.php?item_id=9
https://www.globalsecurity.org/space/systems/patriot-specs.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
