### ISSUE TITLE
Add Larger TC-2N mounts to Yu Shan #3397

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2233]
### DB Selector

DB3K

### Affected DBID(s)

3397

### Summary of Changes

TC-2N Mounts are two 16-tube mounts

### Sources

https://twitter.com/stoa1984/status/1573904858029211648/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
