### ISSUE TITLE
CETC - Ocean E-Stations

### ISSUE THREAD

**Issue by HardLuck13** [PygmalionOfCyprus/cmo-db-requests#2234]
### DB Selector

DB3K

### Hypothetical

No

### Name

CETC

### Facility Type

Radar

### Country

China

### Service

Navy

### In Commission

early 2016

### Number in Service

8

### Crew

autonomous

### Dispersion Radius (m)

single unit

### Sensors

Air-search radar
Electronic Intel
Ku-band SATCOM
L-band SATCOM
VHF-band
ADS-B
AIS

### Mounts

None

### Magazines

None

### Aircraft & Docking Facilities

None

### Comments

China has deployed a network of sensors and communications capabilities between Hainan Island and the Paracel Islands in the northern South China Sea. These capabilities are part of a “Blue Ocean Information Network” (蓝海信息网络) developed by China Electronics Technology Group Corporation (CETC), a state-owned company, to aid in the exploration and control of the maritime environment using information technology. 

### Sources

https://amti.csis.org/exploring-chinas-unmanned-ocean-network/

https://www.forbes.com/sites/hisutton/2020/08/05/china-builds-surveillance-network-in-international-waters-of-south-china-sea/?sh=1e9e201374f3

**Comment by PygmalionOfCyprus** [comment]
These have been in the DB for several years under the generic "Offshore Surveillance Platform" ships/facilities under China. The names are generic but I modelled them on the E-Stations.
