### ISSUE TITLE
Add Chinese HQ-17A SAM Sec

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2235]
### DB Selector

DB3K

### DBID to Copy

2515

### Hypothetical

No

### Name

SAM Sec HQ-17A [SA-15-M2E] Copy

### Country

China

### Service

PLAGF

### In Commission

2021

### Other Changes

Similar to Russian M2E variant of Tor. Wheels instead of tracks. 

Mags looks like 16 still. Looks like 4x4 reload blocks

### Sources

HQ-17A
https://twitter.com/TheDeadDistrict/status/1367868988441657344
https://twitter.com/SilingWu/status/1419696703305879554
https://twitter.com/stoa1984/status/1572239993241993219
https://twitter.com/AlexLuck9/status/1285927722108153856
https://twitter.com/SilingWu/status/1383170015902507014
https://twitter.com/SilingWu/status/1419696703305879554/photo/1
https://twitter.com/IiiTango/status/1333518371393048576
https://twitter.com/Defense785/status/1287400631045586944
https://twitter.com/Ricky779399901/status/1561422650253029377
Reloads
https://twitter.com/jesusfroman/status/1560900397111312384
https://twitter.com/71Arifin/status/1569436737700790272/photo/1

**Comment by bostonmyk** [comment]
More loading etc.
https://twitter.com/jesusfroman/status/1574811612783017986

**Comment by bostonmyk** [comment]
https://twitter.com/HenriKenhmann/status/1661017786448220165/photo/1

**Comment by bostonmyk** [comment]
General
https://odin.tradoc.army.mil/WEG/Asset/HQ-17A_(FM-2000)_Chinese_Short-Range_Air_Defense_Missile_System

Radars 2x E/F Band AESA 25km while on the move
https://twitter.com/someplaosint/status/1672824026245234689

OOB Structure
https://twitter.com/someplaosint/status/1672827550131793920

Active Units
https://twitter.com/nuwangzi/status/1694792406917345704
https://twitter.com/Sam_Cranny/status/1285670809617432582
https://twitter.com/stoa1984/status/1572239993241993219

Firing while moving
https://twitter.com/someplaosint/status/1672830208062128128

**Comment by Jkryos** [comment]
Added DB3K 507
