### ISSUE TITLE
AS-332 Super Puma for Swiss Airforce

### ISSUE THREAD

**Issue by beat578** [PygmalionOfCyprus/cmo-db-requests#2237]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2555

### Hypothetical

No

### Name

AS-332 Super Puma (TH06)

### Country

Switzerland

### Service

Air Force

### In Commission

1987

### Number in Service

15

### Sensors

Montable FLIR

### Mounts

Ski for Glacier Landings, Rescue Wind

### Sources

https://www.vtg.admin.ch/de/organisation/kdo-op/lw/mehr/einsatzmittel-luftwaffe.detail.operatingresources.html/luft/super-puma--th06-.html

**Comment by beat578** [comment]
![1920px-AS332M1_Super_Puma_-_RIAT_2014_(center)](https://user-images.githubusercontent.com/114402560/192267947-53567bf5-5ea4-4db0-b1d0-80a6e32abbb4.jpg)

**Comment by FrangibleCover** [comment]
A few questions to help the Devs:
- Are the FLIRs role fit equipment or are they functionally always on the same helicopters?
- Do we know how many FLIR kits exist?
- What roles are performed by Swiss Pumas? I assume Mountain SAR with the FLIR fitted and general cargo/troop transport without the FLIR?

**Comment by beat578** [comment]
Swiss Army has 4 FLIR III Systems. They can be mounted on any helicopter. 
One Flir is mounted all of the time for Mountain SAR or Police support. The others are mounted as needed, but not only on deisgnated Helicpoter, they can be on any of them. 
It's true, Super Puma is for general cargo / troop transport and SAR / Police support with FLIR.

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
