### ISSUE TITLE
AS-532UL Cougar MK

### ISSUE THREAD

**Issue by beat578** [PygmalionOfCyprus/cmo-db-requests#2238]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4734

### Hypothetical

No

### Name

Eurocopter AS532 UL Cougar MK

### Country

Switzerland

### Service

Air Force

### In Commission

2001

### Number in Service

ex. 12x (2 destroyed by accident)

### Mounts

Ski for Glacier Landings, Rescue Wind

### Sources

https://www.vtg.admin.ch/de/organisation/kdo-op/lw/mehr/einsatzmittel-luftwaffe.detail.operatingresources.html/luft/cougar.html
![image cougar_01](https://user-images.githubusercontent.com/114402560/192268986-68c86a26-7231-479f-9e38-e3ad9cc447ff.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
