### ISSUE TITLE
Adding Picture to Swiss Airforce F-5E Tiger II

### ISSUE THREAD

**Issue by beat578** [PygmalionOfCyprus/cmo-db-requests#2239]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2279

### Summary of Changes

Number in Service:  20 (12 Colored in red with "Patrouille Suisse" liveries)

Adding Picture:
![K19](https://user-images.githubusercontent.com/114402560/192270750-bb8a0dac-9061-449a-a7d3-dfc1f0a26462.jpg)

### Sources

https://www.vtg.admin.ch/de/organisation/kdo-op/lw/mehr/einsatzmittel-luftwaffe.detail.operatingresources.html/luft/f-5e-tiger-ii.html

**Comment by tbrandon517** [comment]
Image pack updates should be submitted on the forum here.

https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=244450

**Comment by beat578** [comment]
Ok sorry, will move it over there.
