### ISSUE TITLE
CCG Bell 212 x6

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#224]
### DB Selector

Both

### Hypothetical

No

### Name

Bell 212

### Country

Canada

### Service

Canadian Coast Guard

### In Commission

1972-2017

### Length (m)

12.7

### Wingspan (m)

4.4

### Height (m)

4.4

### Empty Weight (kg)

2720

### Maximum Takeoff Weight (MTOW) (kg)

4763

### Payload Weight (kg)

2038

### Crew

2

### Propulsion

1x T400-CP-400 Turbo Twin Pac

### Rate of Climb (ft/min)

1580/4760

### Service Ceiling (ft)

15000

### Military/Afterburner Speed (kt)

125

### Cruise Speed (kt)

110

### Supercruise

No

### Ferry Range (nm)

250

### Takeoff / Landing Distance (m)

0m (VTOL) TOD/LAD

### Fuel Capacity (kg)

655

### Sensors

1x Mk1 Eyeball

### Mounts

None

### Loadout Options

- Ferry
- Maintenance
- Reserve
- Cargo 1 ton
- Maritime Surveillance
- SAR

### Comms/Datalinks

UHF/VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Sources

https://en.wikipedia.org/wiki/Bell_212 
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Canadian_Coast_Guard 
https://www.helis.com/database/org/Canadian-Coast-Guard/

**Comment by Jkryos** [comment]
Added both CWDB and DB3K 494.
