### ISSUE TITLE
Picture for Swiss Air Force F-5F Tiger II

### ISSUE THREAD

**Issue by beat578** [PygmalionOfCyprus/cmo-db-requests#2240]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3600

### Summary of Changes

Still in Service 4, (8 are grounded for replacement)

Picture:
![image f_5_f_02](https://user-images.githubusercontent.com/114402560/192271497-22141bfd-957c-4741-980f-da067d521650.jpg)

### Sources

https://de.wikipedia.org/wiki/Mittel_der_Schweizer_Luftwaffe

**Comment by tbrandon517** [comment]
Image pack updates should be submitted on the forum here.

https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=244450

**Comment by beat578** [comment]
Ok sorry, will move it over there.
