### ISSUE TITLE
Adding Picture for Swiss Airforce FA-18C

### ISSUE THREAD

**Issue by beat578** [PygmalionOfCyprus/cmo-db-requests#2241]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft Entries #925, #1575 and #4705

### Summary of Changes

![FA-18C_Hornet_Swiss-Air-Force](https://user-images.githubusercontent.com/114402560/192271950-a1b09fd1-286a-4c73-b06a-1fef7ae3b1c0.jpg)

Number in Service: 25 (Was 26, one lost in accident)

### Sources

https://de.wikipedia.org/wiki/Mittel_der_Schweizer_Luftwaffe
https://www.vtg.admin.ch/de/organisation/kdo-op/lw/mehr/einsatzmittel-luftwaffe.detail.operatingresources.html/luft/f-a-18-hornet.html

**Comment by tbrandon517** [comment]
Image pack updates should be submitted on the forum here.

https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=244450

**Comment by beat578** [comment]
Ok sorry, will move it over there.
