### ISSUE TITLE
Adding Picture for Swiss Air Force FA-18D

### ISSUE THREAD

**Issue by beat578** [PygmalionOfCyprus/cmo-db-requests#2242]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft Entries #3415, #3416 and #4706

### Summary of Changes

Number in Service 5 (was 8, 3 lost in Accidents)

![McDonnell_Douglas_F-A-18D_Hornet,_Switzerland_-_Air_Force_JP6677339](https://user-images.githubusercontent.com/114402560/192273237-e4ee3fa0-9501-4c9c-897f-ed681b6a517a.jpg)

### Sources

https://de.wikipedia.org/wiki/Mittel_der_Schweizer_Luftwaffe

**Comment by tbrandon517** [comment]
Image pack updates should be submitted on the forum here.

https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=244450

**Comment by beat578** [comment]
Ok sorry, will move it over there.
