### ISSUE TITLE
Correct RCS Front and Rear F-35A to -32dBsm (E-M bands) recently updated In RCS Model by @Flankerchan

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2246]
### DB Selector

DB3K

### Affected DBID(s)

278 , 3497 , 3498 , 3835

### Summary of Changes

According to @Flankerchan RCS models assuming no advanced RAM, or stealth ram treated inlet cavities:

F-35A has estimated rcs of 0.02 in X-band which is most accurate for 8-12 GHz wavelengths)
RAM used according to @Flankerchan typically reduces RCS 5-10 dBsm, but in this case it would decrease 15 dBsm to account for unaccounted for inlet valves, etc. https://twitter.com/buchmaru/status/1456235823075004422

**_So 0.02m2 is about -17 dBsm, reduced by -15 dBsm is ( -32 dBsm) around 0.0006m2 for X-Band (8-12GHz)_** 

**Correction**(
![FDhFxjtVUAoCDvs](https://user-images.githubusercontent.com/108960393/192501685-f6b1a16d-aad0-4106-80c6-165781667f3f.jpg)
_**E-M bands) front and rear for ferry/internal loadout should be -32 dBsm / 0.0006m2**_ 

applies only to all USAF (F-35A) Does not apply to European/Allied F-35A. 
**Only applies to DBID listed**

### Sources

https://twitter.com/Flankerchan/status/1456053819792453633

![FDhFuv9UUAA7vNQ](https://user-images.githubusercontent.com/108960393/192501587-37d195b2-645b-4b78-9eec-725348e3597f.jpg)
![FDhFwN6VQAESOHg](https://user-images.githubusercontent.com/108960393/192501601-3e51fee5-68dd-4023-9dec-11b5d63fb272.jpg)
![FDhFxjtVUAoCDvs](https://user-images.githubusercontent.com/108960393/192501628-48a70aea-0201-4136-b133-d370553a2d7b.jpg)
![FDhFyeuVgAcT6DC](https://user-images.githubusercontent.com/108960393/192501636-99def4d2-4871-442b-af62-ba5de8caf00f.png)
![RAM PROOF TWITTER](https://user-images.githubusercontent.com/108960393/192501946-cc41498b-651e-44df-bc2c-472f4af06395.png)

**Comment by KLABDB3K** [comment]
To clarify this is just one source saying the RCS is less? Plus, why not all the allied F-35A's ?

**Comment by TheBagelInhaler** [comment]
> To clarify this is just one source saying the RCS is less? Plus, why not all the allied F-35A's ?

Out of all RCS models out there, his is the most detailed and thorough I think.

I'd believe export F-35A would have slight reduction in RAM coating to not be as stealthy as domestic F-35A? Or is that not a western thing? If not I can change DBID to include all F-35A

**Comment by PygmalionOfCyprus** [comment]
>Plus, why not all the allied F-35A's?

The US F-35s are stealthier than export versions, except probably the UK + Israeli aircraft. This is actually currently represented in the DB.

That said, I'm not going to make any adjustments based purely on civilian RCS "modelling." I've spoken about this before and don't want to type up a whole writeup on VLO features again, but plugging a 3D model into an RCS analyzer is faaaaaaaaaar from a complete analysis of aircraft stealth.
