### ISSUE TITLE
Add Colombian Navy Narino Cl (Dong Hae)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2247]
### DB Selector

DB3K

### DBID to Copy

140

### Hypothetical

No

### Name

FS, CM55, Narino

### Country

Colombia

### Service

Navy

### In Commission

Colombia: 2014 - present

### Number in Service

1

### Sensors

Change sonar to PHS-32

### Mounts

Delete the 76mm Oto Melara,
2 x twin 40mm/60 Mk1 mod2 (instead of 1 twin)

### Other Changes

Is the ex-Anyang 755

### Sources

1: JFS2015-2016
2: https://www.navypedia.org/ships/colombia/col_es_narino.htm
3: https://en.wikipedia.org/wiki/Donghae-class_corvette

![1](https://user-images.githubusercontent.com/99532490/192613030-9f2711e9-ade4-4363-968f-eaecbe2875aa.jpg)
![2](https://user-images.githubusercontent.com/99532490/192613034-f04a952c-3e75-482f-b84e-92bb4728e621.jpg)
![3](https://user-images.githubusercontent.com/99532490/192613038-5f2ad68c-7916-41ab-9fc4-2357ef7022b9.jpg)
![4](https://user-images.githubusercontent.com/99532490/192613041-643728da-2517-4ea9-82cf-9398b59c683d.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
