### ISSUE TITLE
Add Colombian Navy Alm Tono Cl (Pohang)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2248]
### DB Selector

DB3K

### DBID to Copy

2259 (2258/2257)

### Hypothetical

No

### Name

FFL, CM56, Almirante Tono

### Country

Colombia

### Service

Navy

### In Commission

2020-present (COL)

### Number in Service

1

### Sensors

WM-28 instead of S1810 (cf sources)
Liod optronics for Radamec (cf sources)

### Mounts

Add 2x2 AGM-84 Blk1B
Mistram Manpad
2x K6 12.7mm MG
2x M60 7.62 MG

### Other Changes

Ex-ROKS IKSAN 769

### Sources

1: https://navyrecognition.com/index.php/news/defence-news/2020/november/9346-colombian-navy-new-pohang-class-missile-corvette-almirante-tono-arrived-in-cartagena.html
2: https://www.navalnews.com/naval-news/2020/10/colombian-navys-pohang-class-corvette-begins-journey-to-colombia/

![1](https://user-images.githubusercontent.com/99532490/192618905-6b8f0949-cd96-422c-b30a-e2a21d909cbd.jpg)
![2](https://user-images.githubusercontent.com/99532490/192618910-895cd45c-1bbb-4157-88a6-f0aa9350ccc6.jpg)
![3](https://user-images.githubusercontent.com/99532490/192618911-510cab1d-d7b5-4b08-8890-2dcf34d0306a.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
