### ISSUE TITLE
Add Colombia San Andres cl (Balsam)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2249]
### DB Selector

DB3K

### DBID to Copy

3670

### Hypothetical

No

### Name

Offshore Patrol Ship, PO44, San Andres

### Country

Colombia

### Service

Navy

### In Commission

2007 - present (COL)

### Number in Service

1

### Sensors

Based on images radar looks like 2x Furuno nav (possible I & E/F)

### Other Changes

Combat system: found no evidence of upgrade to CS Gen6, ship(s) original from 1942. 
 same might be for #3681 & #3670 (Nigeria & Ghana)

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/colombia/col_es_san_andres.htm

**Comment by Parel803** [comment]
![1](https://user-images.githubusercontent.com/99532490/192623857-aac6394e-9cdf-4dcf-9308-ce80d3029b20.jpg)
![2](https://user-images.githubusercontent.com/99532490/192623859-9d65ab73-afb3-40b0-9457-c0701863d6ff.jpg)
![3](https://user-images.githubusercontent.com/99532490/192623863-a5912c7d-4020-4d04-ae26-0a78dabb04b8.jpg)
![4](https://user-images.githubusercontent.com/99532490/192623864-72a9754d-d563-4c4b-b086-7eb919ce396b.jpg)
![5](https://user-images.githubusercontent.com/99532490/192623869-0274653d-0ecf-49a4-9e1b-2ec6e98eeffc.jpg)
![6](https://user-images.githubusercontent.com/99532490/192623870-8cb34bbd-b269-42f8-a6cb-b18990e6ef30.jpg)
![7](https://user-images.githubusercontent.com/99532490/192623875-ce37073e-44fa-475f-bf88-9499167c8a2a.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
