### ISSUE TITLE
Copy Generic Submarine Periscopes from DB3k to CWDB

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2250]
### DB Selector

CWDB

### DBID to Copy

5840, 5841, 5842, 5850

### Hypothetical

No

### Name

Generic Submarine Periscope, Optical 
Generic Submarine Periscope, LLTV (1970s)

### Country

-

### Service

-

### Other Changes

Copy the 40s/50s, 60s and 70s generic submarine periscopes from DB3K to CWDB. There are currently no submarine periscopes in CWDB.

### Sources

-

**Comment by PygmalionOfCyprus** [comment]
This was handled at some point. By me. But I don't remember. It's a black hole. A black hole of submarine periscopes and terrible Python scripts. We must imagine the database manager happy.
