### ISSUE TITLE
Greek FDI FFG's 1-3 Named - Kimon Class

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2251]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3173 & 3636

### Summary of Changes

Update unit name to F XXX Kimon

### Sources

https://www.navalnews.com/naval-news/2022/09/hellenic-navy-reveals-the-names-of-its-fdi-hn-frigates/?fbclid=IwAR2LeMHiEnlRZyWPSnBsbiWjoaiWABk4ezUFP6wbvjDt4nlK2yKfzqMPixA

![image](https://user-images.githubusercontent.com/99599482/192806802-455fe8fb-e9fc-40da-a02d-8cb19966ca08.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
