### ISSUE TITLE
Zaire - P16 Kiala, Swift Mk II patrol boats (1971)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2253]
### DB Selector

DB3K

### DBID to Copy

ship 319

### Hypothetical

No

### Name

P16 Kiala, Swift Mk II patrol boats

### Country

Zaire/Congo

### Service

Navy

### In Commission

1971-1997, 2x united disposed 1984

### Number in Service

6x

### Sensors

No Change

### Mounts

1x Twin - 12.7/90 HMG
4x Single - 12.7/90 HMG

### Loadout Options

N/A

### Other Changes

Former US Swift Mk II class.

For CWDB as well.

### Sources

https://www.navypedia.org/ships/zaire/zai_cf_swift.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
