### ISSUE TITLE
Zaire -Sin Hung patrol boats (1987)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2254]
### DB Selector

DB3K

### DBID to Copy

ship 2577

### Hypothetical

No

### Name

Sin Hung - 1987, 2x

### Country

Zaire/Congo

### Service

Navy

### In Commission

1987-early 1990s

### Number in Service

2x

### Sensors

No Change

### Mounts

Remove Torpedos

### Loadout Options

N/A

### Other Changes

Ex- North Korean

### Sources

https://www.navypedia.org/ships/zaire/zai_cf_sin_hung.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
