### ISSUE TITLE
Yugoslavia - PBR581 Udarnik Submarine Chaser

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2258]
### DB Selector

CWDB

### DBID to Copy

ship 2402 

### Hypothetical

No

### Name

Yugoslavia - PBR581 Udarnik

### Country

Yugoslavia

### Service

Navy

### In Commission

1956-1984

### Number in Service

1x

### Sensors

Decca radar
DUBA-2 sonar

### Mounts

2 x 1 - 40mm/60 Mk 3
2 x 1 - 20mm/70 Mk 10
1 x 24 - 178 Hedgehog Mk 11 ASWRL
4 DCT
2 DCR

### Loadout Options

N/A

### Other Changes

One unit (ex-US PC1615) designated P6 was delivered by French Yard for the Yugoslav Government thanks to US 'offshore' procurement funds. Decommissioned in 1984. Sunk as a target in 1988.

### Sources

https://www.navypedia.org/ships/yugoslavia/yu_cf_udarnik.htm
https://en.wikipedia.org/wiki/List_of_ships_of_the_Yugoslav_Navy#Patrol_boats
http://www.navsource.org/archives/12/01idx.htm
http://www.navsource.org/archives/12/011615.htm

![image](https://user-images.githubusercontent.com/99599482/192840486-37f9164e-7ee6-4df0-b3f2-9f7db54ce8f5.png)

**Comment by nuk92** [comment]
2x Bofors 40mm/60: 1496 rounds each
2x Bofors 20mm/70: 1496 rounds each
1x Mk11 Hedgehog ASW Mortar: 264 rounds/rockets carried

**Comment by Jkryos** [comment]
Added CWDB 501.
