### ISSUE TITLE
Yugoslavia/Serbia - TC 211 Pionir (Pr.206)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2259]
### DB Selector

CWDB

### DBID to Copy

ship 713

### Hypothetical

No

### Name

TC 211 Pionir (Pr.206)

### Country

Yugoslavia/Serbia

### Service

Navy

### In Commission

1965-1992

### Number in Service

4x (ex-Soviet)

### Sensors

MR-102 Baklan, MR-104 Rys' radars

### Mounts

2 x 2 - 30/71 AK-230, 4 - 533 TT, 2 DC, 6 mines

### Loadout Options

N/A

### Other Changes

Additional units built in Yugoslavia. For both CWDB and DB3K.

### Sources

https://www.navypedia.org/ships/yugoslavia/yu_cf_topchider.htm
https://en.wikipedia.org/wiki/List_of_ships_of_the_Yugoslav_Navy#Torpedo_boats

![image](https://user-images.githubusercontent.com/99599482/192844440-520368ef-f1d1-4f5b-a343-153ef4a84508.png)

**Comment by PygmalionOfCyprus** [comment]
As far as I can tell this is functionally identical to #2261 other than being the domestic version, so barring any info that there were actual differences between the import and domestically produced ships I'm just gonna let the one entry stand for both. (I did name it after the Pionir to follow first-of-class convention.)
