### ISSUE TITLE
Adcom Yabhon United 40 ''El-Djazair-54'' UCAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#226]
### DB Selector

DB3K

### Hypothetical

No

### Name

United 40 ''El-Djazair-54'' UCAV

### Country

Algeria

### Service

Air Force

### In Commission

2018

### Length (m)

As DBID 4375 United 40

### Wingspan (m)

As DBID 4375 United 40

### Height (m)

As DBID 4375 United 40

### Empty Weight (kg)

As DBID 4375 United 40

### Maximum Takeoff Weight (MTOW) (kg)

As DBID 4375 United 40

### Payload Weight (kg)

As DBID 4375 United 40

### Crew

0

### Propulsion

As DBID 4375 United 40

### Rate of Climb (ft/min)

As DBID 4375 United 40

### Service Ceiling (ft)

As DBID 4375 United 40

### Military/Afterburner Speed (kt)

As DBID 4375 United 40

### Cruise Speed (kt)

As DBID 4375 United 40

### Supercruise

No

### Ferry Range (nm)

As DBID 4375 United 40

### Endurance (min)

As DBID 4375 United 40

### Takeoff / Landing Distance (m)

As DBID 4375 United 40

### Fuel Capacity (kg)

As DBID 4375 United 40

### Sensors

As DBID 4375 United 40

### Mounts

As DBID 4375 United 40

### Loadout Options

As DBID 4375 United 40

plus

-Recon (SAR Pod)
-10x Nimrod
-20x 120mm Mortar Rounds

### Comms/Datalinks

As DBID 4375 United 40

### Aircraft Codes

Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Navigation (INS/GPS)

### Comments

Adcom Yabhon United 40 ''El-Djazair-54'' UCAV aquired by Algeria from the UAE. Armed with up to ten Nimrod AGMs or twenty 120mm mortar rounds. Additionally, the United 40 can be equipped with a six-unit rotating dispenser mounted in the fuselage or mount a synthetic-aperture radar (SAR).

### Sources

https://www.oryxspioenkop.com/2021/12/algiers-calling-assessing-algerias.html?m=1&fbclid=IwAR1kcEMGuvMaN369Fz3JhgQUNz0A6HYUPHa4ik3Ss2Kjjikwao5bCXlpR6M

![DDICSt-FW0-AE0uy9](https://user-images.githubusercontent.com/99599482/154560806-7b8b936e-9f4c-48c9-bd7b-3eb6492556c4.jpg)

![image](https://user-images.githubusercontent.com/99599482/154561321-1482b314-b6f8-43b0-b2bb-e1ea903578d2.jpg)

![image](https://user-images.githubusercontent.com/99599482/154561348-88df22de-975a-478a-b84a-f14222b1b4f3.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
