### ISSUE TITLE
Yugoslavia - TC=101 [Type 108 Class], Yugoslavian Higgins boat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2260]
### DB Selector

CWDB

### DBID to Copy

ship 2702

### Hypothetical

No

### Name

TC=101

### Country

Yugoslavia

### Service

Navy

### In Commission

1951-1970s

### Number in Service

96 Boats

### Sensors

Remove Radar

### Mounts

1 x 1 - 40mm/60 Mk 3
2 x 1 - 12.7mm/90
2x - 450mm TT

### Loadout Options

N/A

### Other Changes

1963, 24 boats modified as type 158 remove 2x - 450 TT; add 1 x 1 - 40mm/60 Mk 3, add 2 - 4 mines,  withmax speed 24-26kts

### Sources

https://www.navypedia.org/ships/yugoslavia/yu_cf_tch101.htm

![image](https://user-images.githubusercontent.com/99599482/192846161-644d8fcf-f809-4e68-9ab7-c7c1e33ba06c.png)

**Comment by nuk92** [comment]
TČ-101 (Higgins) torpedo boats used TR-45/II torpedoes. In commission 1945-1965. Number in service: 8 boats

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
