### ISSUE TITLE
Yugoslavia/Serbia - TC 213 Proleter (pr.206)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2261]
### DB Selector

CWDB

### DBID to Copy

ship 713 

### Hypothetical

No

### Name

TC 213 Proleter (pr.206)

### Country

Yugoslavia/Serbia

### Service

Navy

### In Commission

1968-1995

### Number in Service

10x

### Sensors

MR-102 Baklan, MR-104 Rys' radars

### Mounts

2 x 2 - 30mm/71 AK-230, 4 - 533mm TT

### Loadout Options

N/A

### Other Changes

License-built variant of Soviet Project 206 craft.

### Sources

https://www.navypedia.org/ships/yugoslavia/yu_cf_proleter.htm
https://en.wikipedia.org/wiki/List_of_ships_of_the_Yugoslav_Navy#Torpedo_boats

![image](https://user-images.githubusercontent.com/99599482/192847202-59d92c32-2238-4d7f-82e9-353a349121f9.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
