### ISSUE TITLE
UK Lynx HAS/HMA Naval helicopters of all variants would benefit from a Search and Rescue Load out please

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#227]
### DB Selector

DB3K

### User(s)

#392 - Lynx HAS.2 (United Kingdom - 1979) #2089 - Lynx HAS.2 (United Kingdom - 1982) #2600 - Lynx HAS.2 (United Kingdom - 1983) #757 - Lynx HAS.3 (United Kingdom - 1983) #33 - Lynx HAS.3 (United Kingdom - 1986) #2213 - Lynx HAS.3 (United Kingdom - 1988) #1989 - Lynx HAS.3 (United Kingdom - 1992) #1988 - Lynx HAS.3(GM) (United Kingdom - 1991) #515 - Lynx HMA.8 (United Kingdom - 1993) #1987 - Lynx HMA.8 (United Kingdom - 2004) #954 - Lynx HMA.8 (United Kingdom - 2006)

### Weapons Carried

Existing weapons mounts. Internal Fuel.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

150

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Can copy the existing load #15702 out for the #1955 - Lynx SH-14B [Mk27] (Netherlands - 1980)
Search And Rescue (SAR)
(Search And Rescue (SAR))  150 nm Search And Rescue (SAR) radius. Cruise at 1k ft. No form-up time. 10% reserves. 1 hr Day/Night
All-Weather Winchester: Return to base when mission-specific weapons have been expended. Disengage immediately. #15702 

![image](https://user-images.githubusercontent.com/99494755/154562366-01e2074d-0ce5-4bf3-bb5c-1c6b2174f6bc.png)
RN Lynx winching fishermand from Japanese fishing vessel Wakashio Maru No 82 published 18 March 2013 UK MoD

### Sources

UK Royal Navy routinely trained for and conducted S.A.R operations using Lynx naval variants.

https://en.wikipedia.org/wiki/Westland_Lynx#:~:text=The%20Lynx%20went%20into%20operational%20usage%20in%201977,with%20the%20ability%20to%20perform%20loops%20and%20rolls.

http://www.aiai.ed.ac.uk/project/cosar-ts/img/uk-sar-3-600x800.jpg image links to article 
http://www.aiai.ed.ac.uk/project/cosar-ts/
https://www.gov.uk/government/news/royal-navy-warship-rescues-injured-fisherman
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/image_data/file/7368/s300_MM130040144.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
