### ISSUE TITLE
Yugoslavia - M141 MLET inshore minesweepers (1964-2003)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2279]
### DB Selector

CWDB

### DBID to Copy

ship 264

### Hypothetical

No

### Name

M141 MLET (Ham Class)

### Country

Yugoslavia/Serbia

### Service

Navy

### In Commission

1964-2003

### Number in Service

4x

### Sensors

Decca 45 radar

### Mounts

1 x 1 - 40mm/60 Mk 3, LL mechanical/magnetic/acoustic minesweeping gear

### Loadout Options

N/A

### Other Changes

License British 'Ham' class, built under the MS MDAP. For both CWDB and DB3K

### Sources

https://www.navypedia.org/ships/yugoslavia/yu_ms_brsec.htm
https://en.wikipedia.org/wiki/List_of_ships_of_the_Yugoslav_Navy#Mine_warfare
https://en.wikipedia.org/wiki/Ham-class_minesweeper

![image](https://user-images.githubusercontent.com/99599482/192894062-959540cf-00d6-45d0-8a67-6902c0e0ba29.png)

**Comment by nuk92** [comment]
CWDB & DB3K
ML-141 Maun [Ham Class]
complement: 20
standard displacement: 158 tons
full: 180 tons
propulsion: 2x Paxman YH XM
fuel: 15600kg
range: 1674nm @ 12kts
weapons:
1x 20mm twin (CWDB) (bow, 3960 rounds)
1x 20mm M71 Single (DB3K) (bow, 2200 rounds)
radar: Decca 110 

minesweeping gear: MDL (mechanical), AEL (acoustic), PEML (magnetic) #2314
ship codes add: onboard degaussing gear

![ML141](https://user-images.githubusercontent.com/104227721/194347535-d4af390f-74e8-484f-bf4a-f495f79e7a2e.png)
