### ISSUE TITLE
SA-5C outperforming all modern SAM systems against VLO/drones/stealth targets?

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#2284]
### DB Selector

DB3K

### Affected DBID(s)

SA-5C (Vega-M, S-200, V-880M)

### Summary of Changes

I did some tests in vast open low level terrain against quadcopters and F-35B/C against S-200V (Vega-M) using its P-14, PRV-13 and square pair FCR. It averaged an engagement range of 14-15nm against a 0.0001m2 (-40dbsm) target.

I did the same test using PAC-2 GEM+ with AN/TPS-43 or 77 as an acquisition radar, and max engagement range averaged 8-9nm against same target using AN/MPQ-65 FCR. I even tried other (radar only) medium/long range SAM, similar results, smaller engagement ranges than S-200.

As with the S-300PM2 using Big Bird C and 96L6E, max engagement range was 9nm although the 96l6e was able to track it at 18nm. Same for SA-21 using 48N6DM missile, Big Bird D and 96L6E were able to track at 22nm and 18.5nm respectively, yet max engagement range was an average of 9nm. 

Not sure if the saying "old but gold" applies, sounds like it might. Of course there was no jamming involved. But still not sure if a system whose radars designed in 1950's are supposed to outperform almost every single advanced modern SAM today whose radars are fully digital and electronically scanned arrays as opposed to pulse doppler.

I do believe the SARH missiles of PAC-2 GEM+, S-300 and S-400 including 48N6E2 and 48N6DM all have mid-course uplink receivers to assist in tracking/cueing from external acquisition radars. That being said, 48N6E and 48N6DM engagement ranges against this VLO target should be closer to the range at which the 96L6E acquires the target but not exactly. For example a 30N6E or 92N6 by itself will lock onto a stealth target at a lesser range than if cued by an external acquisition radar into a smaller engagement box. Same with the PAC-2 and most other western/eastern SAM systems using SARH missiles.

I suppose moral of the story is when you go up against S-200 (despite its old age and 1950's design) ALWAYS USE RADAR JAMMING :)

### Sources

in game testing of S-200 against stealth targets. S-200 super OP if not jammed.

**Comment by tbrandon517** [comment]
SEE: Long Wavelength Legacy Radars vs Small and LO Aircraft 

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=387002&p=5023007&hilit=Old+radar+vs+stealth#p5023007

**Comment by TheBagelInhaler** [comment]
> SEE: Long Wavelength Legacy Radars vs Small and LO Aircraft
> 
> https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=387002&p=5023007&hilit=Old+radar+vs+stealth#p5023007

I understand vhf/uhf/l band radars are very effective against VLO but my point is, how is an inaccurate radar like P-14 and PRV-13 able to cue the FCR of the SA-5 Gammon to engage a 0.0001m2 target at 15nm, meanwhile a S-400 is unable to cue FCR no more than 9nm using 48N6DM missiles? Doesn't make much sense considering Big Bird D and 96L6 are S band (4Ghz) and lower S-band (2-3Ghz) and much more accurate than the P-14 tall king (VHF) or the PRV-13 (same wavelength as 96L6 but much older and less accurate).

**Comment by PavelNovak79** [comment]
P-14 provides azimuth and distance to S-200 [SA-5] FCR (5N62 [Square Pair]. Square Pair itself has display showing P-14 results and from this FCR's target acquisition officer hand overs target to target tracking officer. Alternatively regiment's IADS could feed target data to Square Pair as it simply looks in direction where was the target detected.
So SA-5 needs at first get data about target from P-14 or IADS and then target needs to be in detection range of Square Pair.

I don't know if S-400 should be better in detecting and targeting stealth targets than S-200.

**Comment by TheBagelInhaler** [comment]
> P-14 provides azimuth and distance to S-200 [SA-5] FCR (5N62 [Square Pair]. Square Pair itself has display showing P-14 results and from this FCR's target acquisition officer hand overs target to target tracking officer. Alternatively regiment's IADS could feed target data to Square Pair. So SA-5 needs at first get data about target from P-14 or IADS and then target needs to be in detection range of Square Pair as Square Pair simply looks in direction where was the target detected.
> 
> I don't know if S-400 should be better in detecting and targeting stealth targets than S-200.

This does makes sense. upper S band Big bird and lower S band cheese board are a compromise between anti-stealth, better accuracy and long range.

However, shouldn't that mean S-400 system FCR 92n6 (using active radar homing missile 40N6E) can engage a VLO stealth target at longer ranges when paired with Protivnik-GE/Nebo-SVU or newer Nebo-M RLM series radars? For example standard S-400 battery using TVM guided missile has max engagement range of 9nm against a VLO target using big bird and cheese board radars. But using ARH 40n6 missile, this range increases to 17nm launch range against 0.0001m2 target.
This is because the active homing missiles don't need a continuous X-band track for engagement/interception since they rely on homing head.

That being said, Nebo-M VHF radar RLM-M in game detects VLO at 45-50nm and RLM-D (L-band) detects at 25-30nm for a 0.0001m2 target, should this in theory be able to cue the 96L6 cheese board and 92n6 FCR to longer engagement range as well, similarly to how P-14 works in S-200 battery?

**Comment by PavelNovak79** [comment]
We have to distinguish between acquisition capability and engagement radar capability. Example from Yugoslavia in 1999. P-18 deployed as acquisition radar for S-125 [SA-3] battery was able to detect and track F-117 at some 30 to 40 km. But at this range the operators could try anything but engagement radar (SNR-125 [Low Blow] would not detect that F-117 even if aimed the most precisely at it. Only when that F-117 closed to some 15 km than was SNR-125 able to detect it and engage it.

So just changing acquisition radar in SAM battery has no effect on maximum range in which engagement radar could see target. 

"But shouldn't that mean S-400 system FCR 92n6 + 96l6E (using active radar homing missile 40N6E) can engage a VLO stealth target at longer ranges when paired with Protivnik-GE/Nebo-SVU or newer Nebo-M RLM series radars?"
- Thus no. The SAM unit will just detect stealth target in longer range but FCR radar limitation is still same. However there can be change if acquisition radar is able to feed data directly to ARH missiles and thus circumvent FCR limitation.

"That being said, Nebo-M VHF radar RLM-M in game detects VLO at 45-50nm and RLM-D (L-band) detects at 25-30nm for a 0.0001m2 target, should this in theory be able to cue the 96L6 cheese board and 92n6 FCR to longer engagement range than 17nm as well, similarly to how P-14 works in S-200 battery?"
- No. As said above if FCR ability against stealth aircraft is 15 km than acquisition radar could try to give data about stealth target at 30 km but FCR will not see it no matter what.

"... without those the Square Pair has a detection range of barely 2-4nm against the same VLO target, and sometimes doesn't even detect it at all"
- FCR of S-200 system doesn't know where to look for target without data from acquisition radar or IADS. Theoretically the operator of FCR could just randomly scan sky but chance to find something this way is close to zero. (Interestingly older FCR in SA-2 and partially also SA-3 and SA-4 has limited capability for searching targets on its own but SA-5 doesn't have it.)

**Comment by TheBagelInhaler** [comment]
> 



> We have to distinguish between acquisition radar capability and engagement radar capability. Example from Yugoslavia in 1999. P-18 deployed as acquisition radar for S-125 [SA-3] battery was able to detect and track F-117 at some 30 to 40 km. But at this range the operators could try anything but engagement radar (SNR-125 [Low Blow] would not detect that F-117 even if aimed the most precisely at it. Only when that F-117 closed to some 15 km than was SNR-125 able to detect it and engage it.
> 
> So just changing acquisition radar in SAM battery has no effect on maximum range in which engagement radar could see target.
> 
> "But shouldn't that mean S-400 system FCR 92n6 + 96l6E (using active radar homing missile 40N6E) can engage a VLO stealth target at longer ranges when paired with Protivnik-GE/Nebo-SVU or newer Nebo-M RLM series radars?"
> 
> * Thus no. The SAM unit will just detect stealth target in longer range but FCR radar limitation is still same. However there can be change if acquisition radar is able to feed data directly to ARH missiles and thus circumvent FCR limitation.
> 
> "That being said, Nebo-M VHF radar RLM-M in game detects VLO at 45-50nm and RLM-D (L-band) detects at 25-30nm for a 0.0001m2 target, should this in theory be able to cue the 96L6 cheese board and 92n6 FCR to longer engagement range than 17nm as well, similarly to how P-14 works in S-200 battery?"
> 
> * No. As said above if FCR ability against stealth aircraft is 15 km than acquisition radar could try to give data about stealth target at 30 km but FCR will not see it no matter what.
> 
> "... without those the Square Pair has a detection range of barely 2-4nm against the same VLO target, and sometimes doesn't even detect it at all"
> 
> * FCR of S-200 system doesn't know where to look for target without data from acquisition radar or IADS. Theoretically the operator of FCR could just randomly scan sky but chance to find something this way is close to zero. (Interestingly older FCR in SA-2 and partially also SA-3 and SA-4 has limited capability for searching targets on its own but SA-5 doesn't have it.)

This fcr limitation applies to TVM/semi-active more-so than ARH.
What I'm talking about is the FCR illuminating in the same direction of the VLO target acquired by a more accurate anti-stealth L-band/UHF radar feeding the 3D data coordinates to the FCR. In this sense, the FCR doesn't need to lock onto the target or "acquire it", but radiate the target location which is being accurately tracked by the UHF/L-band radars. This way it can authorize a missile launch for an ARH and guide it along the beam trajectory which follows the external acquisition track, as shown in the picture previously posted.

This should extend engagement ranges for ARH missiles like 9m6d and 40n6, but not the TVM guided 48n6 series.

**Comment by PavelNovak79** [comment]
"Even in game the SA-5 battery doesn't show the fcr radar detecting the VLO at 15nm when engaged, only the PRV-13 and P-14 had acquired it, yet the fcr is still radiating the target."

I have tested SA-5 against F-117 and your description is wrong and it behaves in game as it should (note however that I don't know what are realistic detecting ranges for SA-5 against F-117):

Tall King C detected F-117 at  106 nm and I have manually marked it as hostile. But SA-5 cannot launch missiles as FCR has note "imprecise target".

At 41 nm PRV-13 [Odd Pair] starts to see target and provide height. But SA-5 still cannot launch missiles - "imprecise target".

Only at 31 nm finally 5N62 [Square Pair] finally sees target and finally launches missiles.


![1-detection](https://user-images.githubusercontent.com/106174580/193641398-0fe880a5-69ba-4718-a8da-2ea77878e6b9.jpg)

![2-height](https://user-images.githubusercontent.com/106174580/193641425-973ebc53-7d0c-40eb-8c56-cb0e4ee4aaa8.jpg)


![3-FCR](https://user-images.githubusercontent.com/106174580/193641445-d68e232d-f177-4888-bfd8-e312fd89b1c7.jpg)

**Comment by TheBagelInhaler** [comment]
> "The way you describe the SA-3 in Serbia is exactly what I mean for the Nebo-M with S-400. The S-125 low blow on its own has barely a 1nm engagement range against the f-117 without external radars (15km was achievable only from sensor fusion, being cued by P-18 and PRV-16 height finder)."
> 
> * I do not agree. Range of Low Blow against F-117 is about that 15 km no matter what. But without knowledge of where the target is (provided by P-18 in that historical case) the operator of Low Blow simply don't know where to aim Low Blow's narrow radar beam. He could theoretically aimlessly scan 0.000001 % of sky hoping by sheer luck to spot the F-117 but that is not practical.
> 
> The sensor fusion here with SA-3 (SA-2, SA-4, SA-5) is simply that acquisition radar tells to FCR where to look and that is all.
> 
> Now some modern radars could have more advanced methods of fusion thanks to modern computing equipment like one radar radiates target and different radar actually pick bounced beam but I thing this is not modelled in game.
> 
> "What I'm talking about in this case using ARH for s400 is the FCR after acquiring accurate coordinates from both VHF and L-band radars, it can radiate the VLO target with beams.. In this sense, the FCR doesn't need to lock onto the target or "acquire it" in terms of reflections, but instead just saturate the target location which is being accurately tracked by the UHF/L-band radars and data shared with fcr at the same time. This way it can authorize a missile launch for an ARH and guide it along its beam trajectory which follows the external acquisition track of uhf/l-band, as shown in the picture previously posted."
> 
> * I think that such behaviour is not modelled in game with S-400 system now and FCR of S-400  needs to see target on its own to fire missiles. I don't know if it have such capability.
> 
> "Even in game the SA-5 battery doesn't show the fcr radar detecting the VLO at 15nm when engaged, only the PRV-13 and P-14 had acquired it, yet the fcr is still radiating the target." and "Same with the SA-3 when used against stealth with external radars p-18/prv-16, the low blow doesn't show up as having locked onto the target, only the other radars have a lock, yet a launch is still possible at 8nm for a f-117."
> 
> * Interesting. It should not work this way. SA-5 FCR definitely needs to see target on its own as otherwise it cannot provide flight data to missile before launch. SA-3 has in reality command guided missiles (not modelled in game currently) here seeing target by FCR is not debatable at all.
> 
> "Even with non-ARH missile like the 48n6 series, using bistatic effects, the missile should still be able to launch towards a VLO target if the FCR is radiating the VLO target using accurate coordinates from external UHF/L-band radars. But it would probably need both VHF/L-band and S-band track for optimal accuracy since it has no active radar homing. This wouldn't be as accurate and long range against a stealth target as the ARH 40N6 but possible nonetheless not as likely."
> 
> * Yeah, I think this is not modelled in game now.

True, I don't believe this is modeled either completely. However, it might be for the 96l6E cheese. When I use the 40N6 missile system with 96L6 turned off, engagement range against a VLO is barely 10nm. But with 96L6E turned on, engagement range is 16-17nm against the same target with rcs of 0.0001.

**Comment by ddranidis** [comment]
So, this looks like WAD then?

**Comment by PavelNovak79** [comment]
I see no issue with SA-5 so yes I think this is WAD.
