### ISSUE TITLE
#5820 - Bell 505 Jet Ranger X (Civilian - 2017) it is carrying Troops, 4x (Troop Transport) 4x Trooper not passengers? 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2285]
### DB Selector

DB3K

### Affected DBID(s)

#5820 - Bell 505 Jet Ranger X (Civilian - 2017)

### Summary of Changes

Loadout #30994
It is carrying **Troops, 4x (Troop Transport) 4x Trooper** so should it not be passengers for a civilian helicopter? 

### Sources

DB496

**Comment by PygmalionOfCyprus** [comment]
Changed loadout to Passengers for all the Bell 505s. Not really a troop transport helicopter even in military service.
