### ISSUE TITLE
Yugoslavia - TR-45/II torpedo

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2289]
### DB Selector

CWDB

### Baseline

2293

### Hypothetical

No

### Name

TR-45/II [Gyro, Straight Runner] -- 1946, Torpedo Rijeka

### Length (m)

5.65

### Width/Span (m)

0.45

### Diameter (m)

0.45

### Weight (kg)

1007

### Range (nm)

3.2

### Launch Altitude / Depth (ft)

66ft depth and up to 328ft height

### Warhead

TR-45/II [200kg HE]

### Targets

Surface Vessel

### Sensors

-

### Weapon Codes

Bearing-Only Launch (BOL), Torpedo - Straight-Running, Level Cruise Flight

### Comments

Can be launched from submarines, torpedo boats or aircraft

4.3nm @ 28.5kts
2.1nm @ 40kts

### Sources

Riječki torpedo - prvi na svijetu, 2010, ISBN 9789536587537
https://www.muzej-rijeka.hr/rijecki-torpedo-prvi-na-svijetu/
https://www.muzej-rijeka.hr/zbirke/rijecki-torpedo/
https://www.paluba.info/smf/index.php?topic=2953.msg162841;topicseen#msg162841
Podmornicarstvo Jugoslavije (Yugoslav Submariners), 2012, ISBN: 9788691542900, page: 315

![Screenshot_20220930-001714_Samsung Internet](https://user-images.githubusercontent.com/104227721/193157837-30a21f08-f807-4a34-a966-d1884cbf66e0.jpg)
![Screenshot_20220930-001539_Samsung Internet](https://user-images.githubusercontent.com/104227721/193157840-74079a43-6509-4d5b-8855-67617e6ae9b6.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
