### ISSUE TITLE
Add anti-air capabilities to Hellfire missile

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#229]
### DB Selector

DB3K

### Affected DBID(s)

Radar Guided Hellfires

### Summary of Changes

Apparently they can target aerial threats and that dual use capability seems to be part of the reason it was initially chosen to equip the M-SHORAD. Seems the Israelis have downed a Lebanese Cessna and an Iranian UAV.

As an aside I had put in a feature request for "Use AAM in ASuW mode" similar to SAM's as many AAM can be employed against surface or ground targets and a doctrine flag like for SAMs seemed to be the best long term solution rather than a specific specialized DB entry. Perhaps a similar type flag for other such ATGM that have a secondary AA capability would be useful?
https://www.matrixgames.com/forums/tm.asp?m=4709794&mpage=7&key=AAM%2CASUW&#4880361

### Sources

https://www.army-technology.com/projects/hellfire-ii-missile/
https://www.army-technology.com/projects/stryker-a1/
https://www.thedrive.com/the-war-zone/40311/the-army-has-started-fielding-its-first-new-short-range-air-defense-system-in-decades
http://edition.cnn.com/2001/WORLD/meast/05/24/israel.plane.02/index.html?_s=PM:WORLD
https://www.youtube.com/watch?v=E0Jt_Vy4Mj0
https://www.ynet.co.il/articles/1,7340,L-761410,00.html

**Comment by PygmalionOfCyprus** [comment]
The AGM/RGM/MGM-114Ls are now capable of hitting air targets below 16000ft and <175kts (this will put helicopters and slow-flying aircraft in their envelope but exclude most everything else), albeit with only a 75% PoK. By default their WRA is set to "Do not use weapon against this target type" so players will have to "opt-in" to engaging air targets with these weapons.
