### ISSUE TITLE
CCG CCGS Private Robertson V.C.Hero Class Mid-Shore Patrol Vessel x9

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#230]
### DB Selector

DB3K

### Hypothetical

No

### Name

CCGS Private Robertson V.C.

### Class

Hero Class

### Country

Canada

### Service

Canadian Coast Guard

### In Commission

2012-

### Length (m)

42.8

### Beam (m)

7.0

### Draft (m)

2.8

### Standard Displacement (t)

220

### Full Displacement (t)

253

### Empty Displacement (t)

-

### Complement

9

### Max Sea State

5

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU - 4000M

### Fuel Capacity (kg)

9000

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

2000 @ 14kn

### Sensors

1x Sperry Marine - Visionmaster FT - X Band
1x Sperry Marine - Visionmaster FT - S Band

### Mounts

- None

### Aircraft & Docking Facilities

3x Davit for 7m RHIB

### Comms/Datalinks

- SATCOM
- VHF AM: 1 x Jotron - TR7725
- VHF FM: 2 x Sailor - RT-4800
- HF: 1 x Motorola - Micom

### Comments

The Hero-class [patrol vessels, previously the Mid-Shore Patrol Vessel Project, is a series of nine patrol vessels constructed by Halifax Shipyards for the Canadian Coast Guard. Based on the Dutch Damen Stan 4207 patrol vessel, construction began in 2011 and the first vessel entered service in 2012. The vessels are assigned to the Atlantic and Pacific coasts of Canada, used for coastal patrol duties.

### Sources

https://inter-j01.dfo-mpo.gc.ca/fdat/vessels/142
https://en.wikipedia.org/wiki/Hero-class_patrol_vessel#Vessels_in_class

![450px-CCGS_Private_Robertson_V C](https://user-images.githubusercontent.com/99632305/154564205-ee364c4d-55a9-4a78-8827-613f102ebcc6.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
