### ISSUE TITLE
Add Moroccan F-5F

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#2300]
### DB Selector

DB3K

### DBID to Copy

3604

### Hypothetical

No

### Name

F-5F Tiger II (Morocco - 1981)

### Country

Morocco 

### Service

Air force

### In Commission

1981 - present

### Mounts

AIM-9J sidewinders and AGM-65B's were used by the aircraft in addition to the standard bombs.

### Sources

https://www.the-northrop-f-5-enthusiast-page.info/AirForces/MoroccoAF.html
https://armstrade.sipri.org/armstrade/page/trade_register.php

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
