### ISSUE TITLE
Yugoslavia, Croatia -  RB-15B Anti Ship Missile (RBS-15 variant)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2303]
### DB Selector

DB3K

### DBID to Copy

368 RB 15M Mk1

### Hypothetical

No

### Name

RB 15B

### Country

Yugoslavia, Croatia

### Service

Navy

### In Commission

1989

### Sensors

unchanged

### Other Changes

This is the version Yugoslavia and Croatia use. It can be fired from ships as well as coastal launchers. Basically the same as the RB 15M Mk1 missile.

### Sources

https://c7.alamy.com/compde/k50c55/zagreb-kroatien-28-mai-2017-anti-schiff-rakete-rb-15b-ausgesetzt-am-26-jahrestags-der-grundung-der-kroatischen-streitkrafte-auf-see-jarun-i-k50c55.jpg

https://obris.org/hrvatska/rbs-15-oruzje-hrvatske-prevlasti-na-moru-u-domovinskom-ratu/

https://www.paluba.info/smf/index.php?topic=5995.msg78693#msg78693

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
