### ISSUE TITLE
Croatia - MOL Coastal Anti Ship Missile Battery

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2304]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Bty (MOL)

### Facility Type

SSM

### Country

Croatia

### Service

Navy

### In Commission

1994

### Number in Service

3

### Crew

12

### Dispersion Radius (m)

80

### Sensors

-

### Mounts

3x MOL TEL (4x RB 15B missiles each)

### Magazines

-

### Comments

Relates to: #2303 

### Sources

https://en-academic.com/dic.nsf/enwiki/11756220

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
