### ISSUE TITLE
Ocean Eagle 43 has too powerful a radar 

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#2306]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3203

### Summary of Changes

The Generic Ocean Eagle 43 has three (!) bizarre super-radars on it that can do NCTR recognition and ballistic missile tracking. Nont only does it not make sense for a small patrol boat but none of the stated features in the customizable version have that. 

Suggest removing that radar and replacing it with the surface radar found on the Mozambican versions (Ships 3744 and 3745) as well as a short generic air search radar (Sensor 2958)

### Sources

https://www.naval-technology.com/projects/ocean-eagle-43-trimaran-maritime-surveillance-vessel/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
