### ISSUE TITLE
Indirect Fires Protection Capability-High Energy Laser (IFPC-HEL) 300kw laser

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#2316]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

Indirect Fires Protection Capability-High Energy Laser (IFPC-HEL)

### Facility Type

SAM

### Country

United States

### Service

Army

### In Commission

First unit delivered September 2022, first platoon of 4 projected 2024

### Number in Service

1?

### Crew

unknown

### Dispersion Radius (m)

unknown

### Sensors

unknown

### Mounts

4 x IFPC-HEL vehicle platoon

### Magazines

unlimited

### Aircraft & Docking Facilities

none

### Sources

https://www.defensedaily.com/topic/indirect-fire-protection-capability-ifpc/
https://eurasiantimes.com/us-military-gets-most-powerful-laser-weapon-till-date-lockheed/
https://www.popularmechanics.com/military/weapons/a28636854/powerful-laser-weapon/#:~:text=The%20Indirect%20Fires%20Protection%20Capability-High%20Energy%20Laser%20%28IFPC-HEL%29,destroy%20targets%20as%20large%20as%20incoming%20cruise%20missiles.

**Comment by PygmalionOfCyprus** [comment]
Already handled as part of a news roundup.
