### ISSUE TITLE
Yugoslavia - PAP 104 Mk3 ROV

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2321]
### DB Selector

DB3K

### DBID to Copy

463

### Hypothetical

No

### Name

PAP 104 Mk3 ROV

### Country

Yugoslavia

### Service

Navy

### In Commission

1983-1992

### Sensors

1x Generic LLTV
1x Generic Mechanical Cable Cutter Mine Sweep
1x Generic Explosive Charge Mine Disposal

### Sources

https://www.paluba.info/smf/index.php?topic=8532.msg461636#msg461636
https://obris.org/wp-content/uploads/2015/08/DSC_4914_ronilice_zorja.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
