### ISSUE TITLE
Japan, Loadout, F-35A, JSM External 

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2323]
### DB Selector

DB3K

### DBID to Copy

Loadout 17599

### Hypothetical

No

### Name

JSM, EOTS, External

### Country

Japan

### Service

Air Force

### Sensors

-

### Mounts

-

### Loadout Options

there are two (AIM-120C-7 and )D variants

### Other Changes

This is for Japanese F-35A(Aircraft 4223)

### Sources

existing Database

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
