### ISSUE TITLE
Philippines, J/FPS-3ME, Radar Site

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2325]
### DB Selector

DB3K

### DBID to Copy

Facility 662

### Hypothetical

No

### Name

J/FPS-3ME

### Country

Philippines

### Service

Air Force

### In Commission

2022

### Number in Service

1x in 2022, 4x total

### Sensors

-Same as original ,J/FPS-3 Radar, not much difference, (plz check if original has AESA code or not... they are AESA Radars)
However, I think J/FPS-3ME does not have BMD capability.

-J/FPS-3 Short Range Radar, Range ~=100nm?

### Mounts

-

### Loadout Options

-

### Other Changes

DECM? system for Anti Radar Missiles. (I am not sure DECM can spoof ARM or not... but there is the system for original one, too) 

### Sources

https://www.asiapacificdefensejournal.com/2020/03/philippines-to-order-4-long-range-air.html

https://ja.wikipedia.org/wiki/J/FPS-3

**Comment by PygmalionOfCyprus** [comment]
Handled 497.

**Comment by bostonmyk** [comment]
Hmm. Did this one make it in?

**Comment by KC45jp** [comment]
Somehow it is in as Japanese Radar (ID 3656). we should send change request to change it from Japan to Philippines.

**Comment by PygmalionOfCyprus** [comment]
Fixed 503. 3656 is now a PAF facility.
