### ISSUE TITLE
DLO-1 Laser Warning Receiver

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2327]
### DB Selector

DB3K

### Baseline

6723

### Hypothetical

No

### Name

DLO-1 (Laser Warning Receiver)

### Sensor Generation

Late 1980s

### Range (nm)

6

### Vertical Arc (deg)

60

### Sensor Capabilities

Air Search, Surface Search

### Search/Track Frequencies

A Band (30-250 MHz) [Old P Band (HF)] 100-300 cm

### Scan Interval (s)

5

### Comments

400nm - 1600nm

### Sources

RTOP-411 class missile boats and Kotor class frigates are equipped with this LWR:
https://www.paluba.info/smf/index.php?topic=18469.msg217432#msg217432

![Screenshot_20220611-173423_Samsung Internet](https://user-images.githubusercontent.com/104227721/193934384-6ac83e98-d879-4e06-a3de-66af6e314fad.jpg)
![Screenshot_20220611-173334_Samsung Internet](https://user-images.githubusercontent.com/104227721/193934388-e09d1f86-13c2-4226-90ca-c1913e307dfc.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
