### ISSUE TITLE
Sky Sabre Has 3 Tels Not 2.

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#2329]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3269

### Summary of Changes

Add an extra TEL to Sky Sabre batteries so it brings it up to the currently deployed systems. 
A 24 channel datalink, that can control 24 missiles isnt a lot of use if the system is actually constrained to 16 missiles in 2 x TELs.

### Sources

https://missiledefenseadvocacy.org/defense-systems/sky-sabre/
https://defence24.com/defence-policy/uk-mod-sky-sabre-system-deployed-to-poland
https://defence.nridigital.com/global_defence_technology_apr18/sky_sabre_inside_the_uks_missile_defence_system
https://www.army-technology.com/projects/sky-sabre-air-defence-system-united-kingdom/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
