### ISSUE TITLE
UK Wildcat HMA.2 of all entries would benefit from a SAR load out please.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#233]
### DB Selector

DB3K

### User(s)

#3372 - Wildcat HMA.2 [AW.159] (United Kingdom - 2016) #4221 - Wildcat HMA.2 [AW.159] (United Kingdom - 2021)

### Weapons Carried

Existing M.3 HMG mount and internal fuel. NVG compatible cockpit. 

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

150

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Wildcats essentially took over SAR as a default role from the Lynx. RAF/RN routinely train from SAR operations.

### Sources

https://twitter.com/NavyLookout/status/1046302157467799552

![image](https://user-images.githubusercontent.com/99494755/154564399-ebf26a89-0821-4b2c-8148-73e0cfacb2a4.png)
HMS Monmouth Wildcat providing plane guard SAR for F-35 operations on HMS Queen Elizabeth II. 

http://ukarmedforcescommentary.blogspot.com/2013/11/the-evolving-budget-situation.html
Imagery from 2013. 
![image](https://user-images.githubusercontent.com/99494755/154564808-6af193cd-af10-46bd-af84-93e2303c2cca.png)
Winch operations during initial trials.
![image](https://user-images.githubusercontent.com/99494755/154565353-00290428-cfcf-4357-88ac-313a702f024d.png)
Schematic of Wildcat internal SAR operations cabin layout, not exactly capacious but enough for one stretcher casualty.

**Comment by PygmalionOfCyprus** [comment]
Added 495 w/ #227.
