### ISSUE TITLE
CAMM Too Slow

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#2330]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3735

### Summary of Changes

CAMM (Land Ceptor) should have a max speed of 1998 Kts (2300 MPH) as per the source quoted

### Sources

https://www.army-technology.com/projects/sky-sabre-air-defence-system-united-kingdom/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
