### ISSUE TITLE
TC-2C loadout for F-CK-1C/D

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2331]
### DB Selector

DB3K

### User(s)

ROKAF F-CK-1C/D (Aircraft 3795/3796)

### Weapons Carried

4x TC-2C(weapon/3983)
2x TC-1(weapon/1767)
2x 275 USG drop tank

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

50 minutes at 150nm CAP

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Below Pics is for the references:
![image](https://user-images.githubusercontent.com/99646926/194074934-5e590aae-273a-4c22-b3e4-d5d43ede5697.png)
![image](https://user-images.githubusercontent.com/99646926/194075359-619a1da5-5238-4216-869b-a955619ac740.png)

### Sources

https://newtalk.tw/news/view/2021-08-03/614849
https://www.taipeitimes.com/News/front/archives/2017/12/25/2003684599
https://alert5.com/2019/04/25/rocaf-tactical-evaluation-of-tc-2c-air-to-air-missile/
https://asianmilitaryreview.com/2021/08/taiwan-readies-extended-range-sky-sword-2-missile-for-production/
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1243

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
