### ISSUE TITLE
Correction for Sayyad-4 missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2333]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3625

### Summary of Changes

-Add active radar seeker to the missile. Probably Early 2010 Technology.
![image](https://user-images.githubusercontent.com/99646926/194091676-5e3ee018-b049-4838-9d6e-ace9dfa80a58.png)

-Add inertial midcourse and change from "illuminate at launch" to "terminal illumination" capability to the missile
![image](https://user-images.githubusercontent.com/99646926/194091878-e6a22c0a-6053-4024-88fe-0633f53a08cb.png)

-Change the minimum target altitude to just 30ft as it have the capability to engage cruise missiles as well.
![image](https://user-images.githubusercontent.com/99646926/194096234-b05a5c33-5560-405f-8eb7-d41c802cd895.png)
![image](https://user-images.githubusercontent.com/99646926/194096414-3a95735e-010e-4ac4-a528-3f2c4d4edf41.png)

### Sources

https://irangeomil.blogspot.com/2019/08/irans-bavar-373-profile.html

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
