### ISSUE TITLE
Add AD-08 Majid SAM system of Iranian Army

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2334]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Sec (AD-08 Majid)

### Facility Type

SAM

### Country

Iran

### Service

Army

### In Commission

2021 -

### Dispersion Radius (m)

40m 

### Sensors

1x Kashef-99 3d AESA Radar
![image](https://user-images.githubusercontent.com/99646926/194100398-2338436e-bdc9-4a84-aaa2-8bd1e1ac715d.png)
![image](https://user-images.githubusercontent.com/99646926/194101063-5500d13d-ca9d-45ff-b57e-a0b5a00cb8e6.png)
![image](https://user-images.githubusercontent.com/99646926/194101446-ce9bc590-c124-454c-a472-6a0ca977da7d.png)

Per mount/launcher:
1x Seraj-1 TV camera
1x Seraj-1 IR camera
![image](https://user-images.githubusercontent.com/99646926/194100572-3ce2cdc6-86a9-481f-8e64-6637ace2069e.png)

### Mounts

2x AD-08 Majid launcher (8x missiles each)
![image](https://user-images.githubusercontent.com/99646926/194102028-5a70986a-a9d7-49ac-9972-917a7012c296.png)

### Magazines

16x AD-08 missiles

### Comments

The specification of the missile is as below:
![image](https://user-images.githubusercontent.com/99646926/194100759-e4cd420c-5174-4452-b816-165ce507793b.png)

Below pics is for the references:
![image](https://user-images.githubusercontent.com/99646926/194101733-a7cf2945-6c7d-40e8-8c87-467acb07f05e.png)
![image](https://user-images.githubusercontent.com/99646926/194101919-388a9132-d089-4f0f-8957-67a08945da47.png)

### Sources

https://iranpress.com/content/50074/majid-air-defense-system-ultimate-iranian-low-altitude-defensive-solution
https://www.armyrecognition.com/defense_news_january_2022_global_security_army_industry/iran_has_developed_ad-08_majid_new_short-range_air_defense_missile_system.html
https://www.defenceview.in/iran-majid-air-defence-system-keep-it-simple-make-it-work/

**Comment by capcop98** [comment]
As per Oryxspioenkop.com, the system is indeed already operational with Iranian forces.
![image](https://user-images.githubusercontent.com/99646926/194381394-c79965f3-9af7-4968-8eb7-e03f003078c9.png)
![image](https://user-images.githubusercontent.com/99646926/194381238-5e723148-d685-4c65-9f8b-57a4008bf9c7.png)
https://postlmg.cc/RJ5BCZ8t
https://www.oryxspioenkop.com/2020/01/the-oryx-handbook-of-iranian-fighting.html

**Comment by Jkryos** [comment]
Added DB3K 499.
