### ISSUE TITLE
Add Colombia Rafael Rada (Swift 105)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2336]
### DB Selector

DB3K

### DBID to Copy

2959

### Hypothetical

No

### Name

Large Patrol Craft, PM102, Rafael Del Castillo Y Rada

### Country

Colombia

### Service

Coast Guard

### In Commission

1981 - pressent (as the Olaya Herrera class)

### Number in Service

2

### Sensors

1x Raytheon I-band Nav radar,
1x COAC Optronic director

### Mounts

Delete the 2 x 20mm,
Add 1x Single 40mm/60 Mk3 (PM102)

### Other Changes

4 instead of 2 MTU diesels (MTU 1 2V 331 TC92).
Max speed 25 kts.
1200nm @ 18 (src1), 2400 @ 15 (src2).
US Swiftships: Swift 105.

Delivered for the Customs service. PM 1 02 is part of the Coast Guard. PM 1 1 5 was paid off, but returned unarmed as part of the resurrected Customs service until being transferred back to the Coast Guard in 1 997

### Sources

1: JFS 2015/2016
2: https://www.navypedia.org/ships/colombia/col_cf_olaya_herrera.htm

![1](https://user-images.githubusercontent.com/99532490/194145817-c3e0457b-a9dc-40a9-b1fb-cf8f2cbf03bb.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
