### ISSUE TITLE
Add Colombia Jaime Gómez (Sea Spectre PB Mk III)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2346]
### DB Selector

DB3K

### DBID to Copy

ship 322

### Hypothetical

No

### Name

Coastal Patrol Craft, PM105, Jaime Gomez Castro

### Country

Colombia

### Service

Coast Guard

### In Commission

1975 - present

### Number in Service

2

### Sensors

Remove radar LN-66 and RWR APR-39.
Add 2x Furuno FR1510D I-band NA radar

### Mounts

Remove 2x single 12.7mm and 40mm
Add 2x single 7.6mm/90 MG, 1x single 40mm/19 Mk 19 Grenade launcher

### Other Changes

Full displacement: 37 t.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/colombia/col_cf_jaime_gomez_castro.htm

![1](https://user-images.githubusercontent.com/99532490/194584815-3cf18fd1-a4d6-43bc-8521-03032d8a7fe6.jpg)
![2](https://user-images.githubusercontent.com/99532490/194584819-019d2f1e-ab7d-44d8-9328-5e26938c13aa.jpg)
![3](https://user-images.githubusercontent.com/99532490/194584825-963e1f73-61ae-4592-9744-5207bff22f0b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 497. I don't see any Mk19 so I left it off.

**Comment by Parel803** [comment]
Rgr, thx.
