### ISSUE TITLE
4 MAM-L Loadouts for Turkey, Azerbaijan, and Ukraine

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2347]
### DB Selector

DB3K

### User(s)

Aircraft 5397, 4820, 5400, 5401, 4735, 5394, 4749

### Weapons Carried

4x MAM -L

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

70nm

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Loadout 29905 as basis

### Sources

Bayraktar TB2 at 2020 Victory Parade Baku, Azerbaijan
![image](https://user-images.githubusercontent.com/99599482/194593037-32df3ab7-7e42-49f4-b761-d859583a623e.png)

Ukrainian TB2 with 4 MAM loadout
![image](https://user-images.githubusercontent.com/99599482/194593878-c80d4147-9629-429c-a2d6-24613ec40f1c.png)

Turkish TB2 with 4 MAM-L
![image](https://user-images.githubusercontent.com/99599482/194598070-89282e12-7270-481b-bde4-8a0c58727099.png)

**Comment by PygmalionOfCyprus** [comment]
Instead of creating a separate loadout, I added 2x MAM-L to the extant loadout as optional weapons. So now you can use the 4x loadout by default or 2x optionally. I did the same thing with the MAM-C loadouts.
