### ISSUE TITLE
2x MAM-L, 2x MAM-C TB2 Loadout

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2348]
### DB Selector

DB3K

### User(s)

Bayraktar TB2

### Weapons Carried

2x MAM-C
2x MAM-L

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

70nm

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

Manufacturer Sheet
![image](https://user-images.githubusercontent.com/99599482/194596750-d4f4f9a0-6d09-44b2-9dfe-c316c774a91f.png)

Manufacturer Display
![image](https://user-images.githubusercontent.com/99599482/194596866-0d8de615-6577-4259-84b9-34d56375f43c.png)

Manufacturer  Images
![image](https://user-images.githubusercontent.com/99599482/194596920-849c0769-2e34-481f-8eb3-6b02e242aa52.png)

![image](https://user-images.githubusercontent.com/99599482/194597133-384f8d73-33b7-4ea1-a871-7f16cbd6c225.png)

Turkish TB2
![image](https://user-images.githubusercontent.com/99599482/194597743-cd675e32-ad75-4ee9-8d6d-6347a4585c4d.png)

**Comment by PygmalionOfCyprus** [comment]
Already in DB, loadout 31834.
