### ISSUE TITLE
Brazil - A330 MRTT/KC-30

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2349]
### DB Selector

DB3K

### DBID to Copy

DBID 4276

### Hypothetical

No

### Name

KC-30 (A.330-200 MRTT)

### Country

Brazil

### Service

Air Force

### In Commission

2023-

### Number in Service

2x

### Sensors

No Change

### Mounts

Centerline Drouge
Wing Drouges

### Loadout Options

Same as existing unit

Add

VIP Transport

### Other Changes

Conversion work into A330 MRTTs is at Airbus' plant in Getafe, Spain, fitted with two Cobham 905E under-wing pods and a Cobham FRU-805E fuselage refuelling unit, and will be based at the Galeão Air Force Base in Rio de Janeiro. VIP transport is also a possibility, in order to replace the Airbus A319ACJ in presidential trips necessitating intercontinental range.

### Sources

https://aviationweek.com/defense-space/multi-mission-aircraft/brazil-takes-delivery-first-a330-mrtt-conversion
https://aviationweek.com/defense-space/multi-mission-aircraft/brazil-acquires-two-a330s-mrtt-conversions
https://www.aviacionline.com/2022/07/the-first-kc-30-a330-200-mrtt-for-the-brazilian-air-force-completes-paint-job-in-ireland/
https://www.thedefensepost.com/2022/04/21/brazil-a330-conversion/
https://defbrief.com/2022/04/19/brazil-orders-two-a330s-for-conversion-into-mrtt-multi-role-tankers/
https://www.airdatanews.com/future-a330-mrtt-of-the-brazilian-air-force-is-unveiled/
https://en.wikipedia.org/wiki/Airbus_A330_MRTT#Brazil
https://www.scramble.nl/military-news/fab-s-first-kc-30-arrives-in-brazil?fbclid=IwAR0XXPrTNfLAMWw_lAXQ1GrLyQjk-IdhxuhRUSWk6Fj8G-bF9p5PM_X8OTw

![image](https://user-images.githubusercontent.com/99599482/194601648-941e6c3c-f615-4e2f-8c26-da4ad6a34d5c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 497. No VIP transport role since the extant passengers loadout should suffice w/ same range, etc.
