### ISSUE TITLE
Sensor 6345 Ground Fire (GaN AESA) should be ABM capable

### ISSUE THREAD

**Issue by smcclaire** [PygmalionOfCyprus/cmo-db-requests#2355]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6345

### Summary of Changes

Sensor 6345 has a maximum altitude defined in the DB and, despite being part of a purpose-designed ABM system, does not have the 'ABM/space search' sensor capability.  I think it probably should have the ABM/Space Search capability, or at the very least have it's maximum altitude increased significantly.

See this forum thread where ballistic missile detection issues caused by these values are discussed: https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=388777&p=5040900#p5040900

### Sources

https://www.thalesgroup.com/en/worldwide/news/ground-fire-enter-age-digital-radar says ABM capable and up to 90 degree coverage in elevation.

**Comment by Huib18** [comment]
[
[Groundfire 300 radar.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/9740094/Groundfire.300.radar.pdf)
](url)
Range is now 110 Nm, and in the brochure 215 NM

Maybe helpful in the discussion:
Air surveillance coverage: 400 km
Coverage: 360° in azimuth, 90° in elevation
Tracking capacity: > 1000 targets
Track update up to 1 Hz in rotating mode, and up to10 Hz in staring mode
SRR/IFF (acc. STANAG 4193) with Mode S and Secure Mode
Enhanced surveillance capability on all targets: slow moving & very low RCS, fast to hypersonic, or highly maneuvering targets
**Range performance is sufficient to autonomously engage short range BMs in rotating mode and medium range BMs in staring mode when cued**

**Comment by PygmalionOfCyprus** [comment]
Sensor now has space search capability, 215nm range, and no altitude cap. Also tweaked track capacity, etc. Should be more suitable for ABM now.
