### ISSUE TITLE
RDL-13/T rename

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2367]
### DB Selector

DB3K

### Affected DBID(s)

6824

### Summary of Changes

rename to: Iskra RDL-13

This seems to have been designed by the Yugoslav company Iskra. You can see it being tested in the last picture.

### Sources

Podmornicarstvo Jugoslavije (Yugoslav Submariners), 2012, ISBN: 9788691542900, page: 237

![20221009_001942](https://user-images.githubusercontent.com/104227721/194729769-f7b781a0-ffbe-42f0-b9a0-af31b6c529a9.jpg)

![RDL13](https://user-images.githubusercontent.com/104227721/194729410-e93d9839-b795-407d-b4bc-bf19c4329d30.jpg)

![RDL-13](https://user-images.githubusercontent.com/104227721/194729365-e280f3eb-3465-4ede-a1de-01ab9dd47a86.jpg)

![RDL_BI](https://user-images.githubusercontent.com/104227721/194729260-f0001b19-45e2-4425-97e6-4da978186ea3.png)

**Comment by PygmalionOfCyprus** [comment]
We don't generally put the manufacturer names in front of sensors unless it's essential to distinguish the platform. (I know this convention is pretty inconsistently applied in the DB.) For now I'm gonna leave it, unless it's causing confusion with another entry in the DB.
