### ISSUE TITLE
BUG: Type 1 Electric Jammer does not deploy

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2368]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4089

### Description of Problem

Target type is Aircraft but should be Ship. This is causing this decoy does not deploy as jammer.

### Recommended Fix

Target type is Aircraft but should be Ship.

**Comment by PygmalionOfCyprus** [comment]
Rookie mistake, sorry about that. Fixed 497.
