### ISSUE TITLE
Increase 9M317 max target speed to 1200 m/s

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2369]
### DB Selector

DB3K

### Affected DBID(s)

1144

### Summary of Changes

Export catalog states max target speed for ballistic missiles to be 1200 m/s (2330 kts)
![9m137 missile](https://user-images.githubusercontent.com/108960393/194747360-39a5cedd-47c7-4af1-98c3-680c84e18757.png)

Changes: increase from 1600 kts to 2330 kts (~mach 3.5)

This applies to missiles used in BUK-M2E (export) and BUK-M1-2 (domestic)
Most other sources including Ausairpower report the same max speed of 1200m/s
![9m137 missile 2](https://user-images.githubusercontent.com/108960393/194747371-57c5a006-617d-441d-8e8b-a4194763dedf.png)

### Sources

https://roe.ru/eng/catalog/air-defence-systems/air-defense-systems-and-mounts/%22Buk-M2E%22%20%289K317E%29/

http://www.ausairpower.net/APA-9K37-Buk.html

**Comment by PygmalionOfCyprus** [comment]
This is already reflected in my version of the DB.

![image](https://user-images.githubusercontent.com/87087226/195148570-1d2f7140-6c77-48cb-be37-ffc75ed16a1d.png)
