### ISSUE TITLE
JL-8 Karakorum

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#237]
### DB Selector

DB3K

### Hypothetical

No

### Name

JL-8 Karakorum

### Country

Zimbabwe

### Service

Air Force

### In Commission

2006-

### Length (m)

aircraft/2229/

### Wingspan (m)

aircraft/2229/

### Height (m)

aircraft/2229/

### Empty Weight (kg)

aircraft/2229/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/2229/

### Payload Weight (kg)

aircraft/2229/

### Crew

aircraft/2229/

### Propulsion

aircraft/2229/

### Rate of Climb (ft/min)

aircraft/2229/

### Service Ceiling (ft)

aircraft/2229/

### Military/Afterburner Speed (kt)

aircraft/2229/

### Cruise Speed (kt)

aircraft/2229/

### Supercruise

No

### Ferry Range (nm)

aircraft/2229/

### Endurance (min)

aircraft/2229/

### Takeoff / Landing Distance (m)

aircraft/2229/

### Fuel Capacity (kg)

aircraft/2229/

### Sensors

aircraft/2229/

### Mounts

aircraft/2229/

### Loadout Options

aircraft/2229/

### Comms/Datalinks

aircraft/2229/

### Comments

Copy preexisting db units to Zimbabwe, K-8's serve as a Hawk replacement and may employ similar armaments so the PRC entry was selected as the closest match.

### Sources

https://[cmano-db.com](https://cmano-db.com/aircraft/2229/)/aircraft/2229/
https://en.wikipedia.org/wiki/Air_Force_of_Zimbabwe#Aircraft
https://www.flightglobal.com/download?ac=75345
https://d1fmezig7cekam.cloudfront.net/VPP/Global/Flight/Airline%20Business/AB%20home/Edit/WorldAirForces2015.pdf

**Comment by PygmalionOfCyprus** [comment]
Added 494.
