### ISSUE TITLE
Protivnik-GE increase altitude range/max range

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2371]
### DB Selector

DB3K

### Affected DBID(s)

3149 , 2257

### Summary of Changes

-export/manufacturer shows 200km as being maximum altitude. **Increase max altitude detection from 100,584m to 200,000m**
-max range is shown as 450km in rosboronexport catalogue **(increase max detection range from 215nm to 243nm)**
![protivnik-ge ](https://user-images.githubusercontent.com/108960393/194752058-64040cbd-bb7f-4d4a-abf5-5dd0ccfcf6a8.png)

Thank you!!

### Sources

https://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/59N6-%D0%A2%D0%95/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
