### ISSUE TITLE
Please fix GhostEye coverage arcs of Secondary Arrays in US Patriot battery and the data link

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2372]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3546

### Summary of Changes

It seems that changes done previously in:

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2035

possibly caused in game issues with range circles.

Current state:
![sensor_range_not_ok](https://user-images.githubusercontent.com/111351574/194758028-040736fc-2bcc-4f1c-b6b9-ee5b3774219e.png)

Expected state (after manual modifications).
![sensor_range_ok](https://user-images.githubusercontent.com/111351574/194758054-9df3f84a-6737-4bf5-aa1c-33079c763806.png)

I also reported this via Matrix games forums:
https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=388425&p=5041457#p5041457

Please also look into the datalink. Currently the DB models the legacy one but I do not have details about new one and if the number of channels per array has been increased. I however see GhostEye datalink in the database, but it is not associated with the GhostEye based Patriot battery.

### Sources

Sources provided in original request:
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2035

**Comment by HunterDNiu** [comment]
In many instances I have had this issue while customizing sensors.

**Comment by PygmalionOfCyprus** [comment]
Not a DB issue, seems to be a bug. I think it's been fixed, I haven't seen this w/ GhostEye sensors recently.
