### ISSUE TITLE
Correct magazines for SAM Plt Patriot (Poland).

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2374]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3653

### Summary of Changes

This entry in DB has wrong magazines. Current magazines has wrong quantities and also contain PAC-2 GEM missiles which are not part of the Plt/Bty.

I presume this is just a copy+paste mistake. We have correct magazine with the correct entries ID 1801.

In reality magazine is 2 Jelcz trucks (12 PAC3-MSE each) and two trailes (also 12 PAC3-MSE each). This is per Plt (our unit in DB).

So ID 1801 has 2x24/24 magazines which is correct and should be added to the Plt.

Probably we should rename Magazine ID 1801 so it has the right date in it which is 2022.

The source is a very detailed interview with col. Marciniak, who is responsible for Air Defence procurement program (Wisla & Narew). The interview contains a photo of a loader truck with the description. 8 loader trucks he mentions are for 2 Btys ordered , so 4 Plts (firing units) - that gives 2x24/24 magazines per Plt.

### Sources

http://dziennikzbrojny.pl/artykuly/art,9,52,11700,inne,wywiady,przyszlosc-polskiej-naziemnej-obrony-powietrznej-rozmowa-z-plk-michalem-marciniakiem

**Comment by PygmalionOfCyprus** [comment]
Looks like I added the magazine as 1801 but forgot to actually put it on the facility. Oops. Handled 497.
