### ISSUE TITLE
China, YJ-62S SSM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2376]
### DB Selector

DB3K

### Baseline

weapon 1708

### Hypothetical

No

### Name

YJ-62S

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

-

### Warhead

-

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### Sensors

1x active radar seeker 5nm
1x passive radar seeker 10nm
1x iir seeker 25/10nm

### Weapon Codes

Home On Jam (HOJ), Terrain Following, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS Navigation, Terminal Maneuver - Pop-up, Re-Attack Capability, Level Cruise Flight

### Comments

IIR-Seeker under the nose

### Sources

https://www.sinodefenceforum.com/t/052c-052d-class-destroyers.6881/page-498
![image](https://user-images.githubusercontent.com/107970049/194763214-37c95062-51a3-4399-a618-49e82121ab3c.png)

**Comment by Jkryos** [comment]
Added DB3K 498.
