### ISSUE TITLE
China, Type 052C DDG, SSM update

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2377]
### DB Selector

DB3K

### Affected DBID(s)

Ship 696

### Summary of Changes

SSM change to YJ-62S

### Sources

https://www.sinodefenceforum.com/t/052c-052d-class-destroyers.6881/page-498

**Comment by LuigiP57** [comment]
#2376

**Comment by PygmalionOfCyprus** [comment]
Is the YJ-62S a separate missile from what you earlier described as the YJ-62B, or is it just the confirmed designation? I couldn't see authoritative sources christening the YJ-62B.

**Comment by Jkryos** [comment]
Added DB3K 498.
