### ISSUE TITLE
Add Anka-S for RMAF(Malaysia)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2378]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4977

### Hypothetical

No

### Name

Anka-S

### Country

Malaysia

### Service

Air Force

### In Commission

2025

### Sensors

similar as Aircraft/4977

### Sources

https://www.flightglobal.com/military-uavs/malaysia-to-acquire-male-uav-by-2025/149720.article
https://www.malaysiandefence.com/leonardo-atr-mpa-and-tai-anka/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
