### ISSUE TITLE
Add ATR-72MP for RMAF(Malaysia)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2379]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2598

### Hypothetical

No

### Name

ATR-72 ASW

### Country

Malaysia

### Service

Air Force

### Sensors

similar as Aircraft/2598

### Sources

https://www.malaysiandefence.com/leonardo-atr-mpa-and-tai-anka/
https://www.freemalaysiatoday.com/category/nation/2022/10/09/mindef-finalises-deal-to-buy-maritime-aircraft-and-drones/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
