### ISSUE TITLE
Mi-24V Hind E [Mi-35]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#238]
### DB Selector

DB3K

### Hypothetical

No

### Name

Mi-24V Hind E [Mi-35]

### Country

Zimbabwe

### Service

Air Force

### In Commission

2000

### Length (m)

aircraft/4466/

### Wingspan (m)

aircraft/4466/

### Height (m)

aircraft/4466/

### Empty Weight (kg)

aircraft/4466/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/4466/

### Payload Weight (kg)

aircraft/4466/

### Crew

aircraft/4466/

### Propulsion

aircraft/4466/

### Rate of Climb (ft/min)

aircraft/4466/

### Service Ceiling (ft)

aircraft/4466/

### Military/Afterburner Speed (kt)

aircraft/4466/

### Cruise Speed (kt)

aircraft/4466/

### Supercruise

No

### Ferry Range (nm)

aircraft/4466/

### Endurance (min)

aircraft/4466/

### Takeoff / Landing Distance (m)

aircraft/4466/

### Fuel Capacity (kg)

aircraft/4466/

### Sensors

aircraft/4466/

### Mounts

aircraft/4466/

### Loadout Options

aircraft/4466/

### Comms/Datalinks

aircraft/4466/

### Comments

Copy preexisting db units to Zimbabwe, closest existing DB match.

### Sources

aircraft/4466/
https://web.archive.org/web/20071112052601/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af_current_inventory.htm
https://web.archive.org/web/20070704065635/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af-all-time.htm
https://d1fmezig7cekam.cloudfront.net/VPP/Global/Flight/Airline%20Business/AB%20home/Edit/WorldAirForces2015.pdf
https://en.wikipedia.org/wiki/Air_Force_of_Zimbabwe#Aircraft
https://www.flightglobal.com/download?ac=75345

**Comment by PygmalionOfCyprus** [comment]
Added 494.
