### ISSUE TITLE
add ScanEagle UAV for RMN(Malaysia)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2380]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3347

### Hypothetical

No

### Name

ScanEagle UAV(Malaysia)

### Country

Malaysia

### Service

Navy

### In Commission

2019

### Number in Service

12x

### Sensors

Similar as Aircraft/3347

### Sources

https://www.malaysiandefence.com/a-dozen-scaneagle-drones-for-malaysia/
https://www.navalnews.com/naval-news/2021/03/royal-malaysian-navy-launches-scaneagle-uas-squadron/
https://www.navalnews.com/naval-news/2020/05/royal-malaysian-navy-took-delivery-of-six-scaneagle-uav/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
