### ISSUE TITLE
Add Indian Ch-46F(I) Chinook

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2384]
### DB Selector

DB3K

### DBID to Copy

5819

### Hypothetical

No

### Name

CH-46F(I) Chinook

### Country

India

### Service

Air Force

### In Commission

2019

### Number in Service

15x

### Sources

https://www.boeing.co.in/products-and-services/defense-space-and-security/boeing-defense-space-and-security-in-india/ch-47-chinook.page
https://twitter.com/IAF_MCC/status/1110037527702974464?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1110037527702974464%7Ctwgr%5Eeadebbb8b43570c42baf2a9055b2ffe6a4a88a44%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.strategicfront.org%2Fforums%2Fthreads%2Ftransport-helicopters-of-iaf-ch-47f-chinook-mi-17v-5-dhruv-alh-etc.83%2Fpage-4
https://www.hindustantimes.com/india-news/in-a-first-women-pilots-to-run-chinook-supply-sorties-101663351144906.html
https://thediplomat.com/2019/03/indian-air-force-inducts-first-2-us-made-chinook-heavy-lift-helicopters/
Sipri Line
15	CH-47F Chinook	transport helicopter	2015	2019-2020	(15)	$1 b deal (part of $2.4 b deal); CH-47F(I) version

**Comment by bostonmyk** [comment]
Does have chaff and flares and PAWS
https://www.reddit.com/r/WarplanePorn/comments/lik2j1/chaff_and_flare_dispensers_on_a_chinook/
https://www.thedrive.com/the-war-zone/31712/night-stalker-chinook-special-operations-helicopters-have-new-laser-countermeasures-system
https://elbitsystems.com/product/music/

**Comment by bostonmyk** [comment]
Elbit PAWS #1921

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
