### ISSUE TITLE
Change the motor burning time for aim9x and amraams

### ISSUE THREAD

**Issue by Test229** [PygmalionOfCyprus/cmo-db-requests#2386]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 945,897,52,718,51,3567

### Summary of Changes

Currently the motor of the 9x only burns for 2 sec, but in the given video we can see the motor burns from 0:36 to 0:41, also for the amraam c-5,6,7 and 8, and jatm, the motor (WPU-16) only burns for 5 secs,  in the provided pdf (page 8) it says 7-9 sec, I suggest we use a 9 sec. The pdf is not an official doc but given the 5 sec for a sidewinder, I would say it's a reasonable guess.

### Sources

https://www.youtube.com/watch?v=4g4_jzqBJnA
https://zaretto.com/sites/zaretto.com/files/missile-aerodynamic-data/AIM120C5-Performance-Assessment-rev2.pdf

**Comment by PygmalionOfCyprus** [comment]
This should have been fixed in 497, just forgot to close the ticket.

**Comment by Test229** [comment]
Hmm, sorry but I checked db497a, and I don't think you have changed the sidewinders? And so are the AMRAAMs(except AMRAAM-D).

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
