### ISSUE TITLE
German AS.400 Grizzly will use Elbit J-Music DIRCM

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2388]
### DB Selector

DB3K

### Affected DBID(s)

4918

### Summary of Changes

Replace generic DIRCM with Elbit J-Music/ Sensor #6535
IOC probably 2023. 

### Sources
https://elbitsystems.com/media/j_music_2018_letter_1.pdf
https://youtu.be/J2lQQkaqsoE
https://www.israeldefense.co.il/en/node/38848
https://www.diehl.com/defence/en/press-and-media/news/diehl-and-elbit-systems-continue-successful-cooperation-for-dircm-protection-system/

**Comment by PygmalionOfCyprus** [comment]
Handled 497. That's Sensor 6585. :P
