### ISSUE TITLE
Update Indian AH-64E MAWS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2390]
### DB Selector

DB3K

### Affected DBID(s)

4856

### Summary of Changes

Swap out AN/AAR 57 for #1921 Elbit PAWS

### Sources

https://twitter.com/Parthu_Potluri/status/1421472670126800901
https://twitter.com/thedeaddistrict/status/1292695836997165058?lang=en

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
