### ISSUE TITLE
Visby class new Anti ship missiles

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#2395]
### DB Selector

DB3K

### Affected DBID(s)

3345

### Summary of Changes

Add RB15M Gungnir to the ships loadout from mid 2020's

### Sources

https://www.saab.com/sv/newsroom/press-releases/2017/saab-far-bestallning-fran-fmv-pa-nasta-generations-sjomalsrobot

**Comment by PygmalionOfCyprus** [comment]
Will also require addition of RB 15M Mk4 Gungnir.

**Comment by PygmalionOfCyprus** [comment]
Are we sure this is a distinct entry, or is it just that the Visbys are receiving the Gungnir instead of the Mk3 for their MLU?
