### ISSUE TITLE
Add AN/AAR-47, AN/ALR-56M and AN/ALE-47 Chaff-Flare Dispensers to US C-130J #1723

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2397]
### DB Selector

DB3K

### Affected DBID(s)

1723

### Summary of Changes

Add to C-130J (1723), 
Missile Warning System, AN/AAR-47: Sensor #728
Countermeasures Dispensing System, AN/ALE-47 Same mount on aircraft #3173
Radar Warning Receiver, AN/ALR-56M: Sensor #2417

### Sources

https://www.lockheedmartin.com/content/dam/lockheed-martin/aero/documents/C-130J/C130JPocketGuide.pdf pg.29
https://www.af.mil/About-Us/Fact-Sheets/Display/Article/1555054/c-130-hercules/
https://www.edwards.af.mil/News/Article/396199/new-c-130j-radar-warning-receiver-put-to-test/
https://www.baesystems.com/en-us/product/an-alr-56-radar-warning-receivers#section2
C-130J Pictures:
Visible stuff (box cameras below front windows next to nose, chaff/flare dispensers)
https://upload.wikimedia.org/wikipedia/commons/a/a1/C-130J_135th_AS_Maryland_ANG_in_flight.jpg
https://www.airrecognition.com/images/stories/news/2022/january/US_approves_foreign_military_sale_of_12_C-130J-30_Super_Hercules_to_Egypt-01.jpg
https://www.146aw.ang.af.mil/News/Photos/igphoto/2000182672/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
