### ISSUE TITLE
Add US C-130J Version with AN/AAQ-24(V) DIRCM LAIRCM

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2398]
### DB Selector

DB3K

### DBID to Copy

1723

### Hypothetical

No

### Name

C-130J

### Country

United States

### Service

Airforce

### In Commission

2010

### Sensors

Add Sensor 2312 AN/AAQ-24(V) DIRCM/AIRCM
Add changes in ticket below.
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2397

### Other Changes

Looks like funded for AMC C-130J since 2010-11

### Sources

https://www.dacis.com/budget/budget_pdf/FY12/RDTE/F/0401134F_219.pdf
https://defbrief.com/2022/01/25/algeria-receives-first-of-four-c-130j-airlifters-from-the-us/
https://twitter.com/withinsyriablog/status/881565616200499200

**Comment by bostonmyk** [comment]
HC-130J #3215 has same defensive gear
https://www.lockheedmartin.com/en-us/news/features/2020/air-force-reserve-receives-first-hc-130j-combat-king-II.html

**Comment by bostonmyk** [comment]
Same for UK C-130 C-6
https://www.eliteukforces.info/air-support/47-Squadron/c130j-hercules.php
https://www.britmodeller.com/forums/index.php?/topic/234970376-lockheed-martin-c-130j-super-hercules/

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
