### ISSUE TITLE
Add AU C-130J-30 Version with AN/AAQ-24(V) DIRCM LAIRCM 2019

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2399]
### DB Selector

DB3K

### DBID to Copy

1701

### Hypothetical

No

### Name

C-130J-30

### Country

Australia

### Service

Air Force

### Sensors

Add Sensor 2312 AN/AAQ-24(V) DIRCM/LAIRCM

### Sources

https://www.airforce-technology.com/news/raaf-final-operational-capability-c-130j-laircm/
https://www.dst.defence.gov.au/projects/c-130j-large-aircraft-infrared-countermeasures

**Comment by PygmalionOfCyprus** [comment]
I used the Wayback Machine to find the [original project page](https://web.archive.org/web/20140303200035/http://www.defence.gov.au/dmo/id/dcp/html_dec10/air/AIR5416.html).

Based on that info, I've added a variant in 2005 w/ MAWS & CMDS, 2009 w/ RWR, and 2015 as IOC for the LAIRCM installation (corroborated by [this article](https://www.shephardmedia.com/news/digital-battlespace/laircm-spotted-australian-c-130j/)).

**Comment by bostonmyk** [comment]
Good work!
