### ISSUE TITLE
Qatar Sea King #1688 retired 2021, sold to Pakistani Navy

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#24]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1688

### Summary of Changes

Qatar Sea King #1688 retired 2021, sold to Pakistani Navy. Copy and Add variant to Pakistani Navy. Qatar using NFH-90 now

### Sources

https://twitter.com/NasserF15QA/status/1422193494827978754
https://www.dawn.com/news/1671271

**Comment by Jkryos** [comment]
Added end of service date and copied both entries over to Pakistani Navy.
