### ISSUE TITLE
Add USAF C-130J-30

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2400]
### DB Selector

DB3K

### DBID to Copy

1701

### Hypothetical

No

### Name

C-130J-30

### Country

United States

### Service

Air Force

### Sensors

Add:
Missile Warning System, AN/AAR-47: Sensor https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/728
Radar Warning Receiver, AN/ALR-56M: Sensor #2417

### Mounts

Countermeasures Dispensing System, AN/ALE-47 Same mount on aircraft #3173

### Loadout Options

Add standard C-130J-30 entries from other entries

### Other Changes

Looks like it does have DIRCM/LAIRCM. Likely grouped with C-130J integrations (2010-11)

https://www.planespotters.net/photo/1250348/08-3176-united-states-air-force-lockheed-martin-c-130j-30-hercules
https://www.planespotters.net/photo/1233474/08-5683-united-states-air-force-lockheed-martin-c-130j-30-hercules

### Sources

https://www.af.mil/About-Us/Fact-Sheets/Display/Article/1555054/c-130-hercules/
https://www.planespotters.net/photo/1250348/08-3176-united-states-air-force-lockheed-martin-c-130j-30-hercules
https://www.planespotters.net/photo/1246315/07-8614-united-states-air-force-lockheed-martin-c-130j-30-hercules

**Comment by PygmalionOfCyprus** [comment]
Handled 497. In-service 1999 as per AF site so first variant uses the 47(V) instead of the (V)2.

**Comment by bostonmyk** [comment]
Thanks for getting all these done. Not the most exciting updates, for sure.
