### ISSUE TITLE
US/Japanese KC-46A DIRCM and RWR Updates 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2401]
### DB Selector

DB3K

### Affected DBID(s)

3687, 4517

### Summary of Changes

Add Sensor 2312 AN/AAQ-24(V) DIRCM/LAIRCM
Add Sensor 829 ALR-69 or new ALR-69A (Newer generation-digital)

Flying operationally but no US IOC just yet.

### Sources

DIRCM
https://www.dote.osd.mil/Portals/97/pub/reports/FY2020/af/2020kc46a.pdf?ver=A8amoNv566NMJp2mMfXf3w%3D%3D
https://www.mcconnell.af.mil/News/Article/2313951/laircm-testing-for-the-kc-46/
https://news.northropgrumman.com/news/releases/northrop-grumman-continues-support-for-us-air-force-infrared-countermeasures-systems

RWR
https://www.airforce-technology.com/news/raytheon-alr-69a-radar-warning-kc-46/
https://www.raytheonintelligenceandspace.com/news/2022/03/03/ris-upgrading-air-force-f-16s-to-detect-more-advanced-threats
https://www.dote.osd.mil/Portals/97/pub/reports/FY2012/af/2012alr-69a_rwr.pdf?ver=2019-08-22-111753-863

**Comment by PygmalionOfCyprus** [comment]
Handled 497. Also added to the Israeli KC-46 since I assume they're getting them as well. Could be wrong.
