### ISSUE TITLE
F-35A for Finland

### ISSUE THREAD

**Issue by Sardaukar67** [PygmalionOfCyprus/cmo-db-requests#2404]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4876

### Hypothetical

No

### Name

F-35A

### Country

Finland

### Service

Finnish Air Force

### In Commission

2026-

### Number in Service

64

### Other Changes

Should be newest Batch coming to service in 2025-2026, same as USAF version.

https://ilmavoimat.fi/en/-/the-lockheed-martin-f-35a-lightning-ii-is-finland-s-next-multi-role-fighter

"The procurement object is 64 F-35A multi-role fighters in the newest Block 4 configuration. The procurement encompasses multi-role fighter weaponry. The offered F-35 package includes the following weapon types: AMRAAM, Sidewinder, SDB I and II, JDAM-family weaponry, JSM and JASSM-ER. "

### Sources

https://thebarentsobserver.com/en/security/2022/05/finlands-first-f-35-will-be-based-north
https://www.defensenews.com/interviews/2022/02/14/finnish-air-force-commander-on-running-the-f-35-through-a-time-of-isolation/
https://www.reuters.com/world/europe/finland-set-sign-deal-with-us-64-f-35-jets-sources-2022-02-10/
https://ilmavoimat.fi/en/-/the-lockheed-martin-f-35a-lightning-ii-is-finland-s-next-multi-role-fighter

**Comment by tbrandon517** [comment]
Additional

https://www.thedrive.com/the-war-zone/36990/heres-the-full-list-of-kit-offered-to-finland-if-it-chooses-f-35-or-super-hornet
https://www.thedrive.com/the-war-zone/43458/heres-how-finland-justified-its-decision-to-buy-64-f-35-stealth-fighters

**Comment by Jkryos** [comment]
Added DB3K 498.
