### ISSUE TITLE
Update/correction for Spyder-SR/MR SAM batteries.

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2407]
### DB Selector

DB3K

### Affected DBID(s)

Facility 2486, 2484, 2487, 3010

### Summary of Changes

-Add Magazine that contained 8x Derby and 8xPython-5 for Spyder-SR batteries
![image](https://user-images.githubusercontent.com/99646926/195386988-d98f5227-f6d2-4c54-b7cd-d6823ca8d93b.png)

-Add Magazine that contained 16x Derby(Spyder-MR) and 16x Python-5(Syder-MR) to Spyder-MR batteries.
![image](https://user-images.githubusercontent.com/99646926/195387050-559b5b92-68ee-4e23-91cd-9b0243f1f5ee.png)

### Sources

https://www.youtube.com/watch?v=9mRNMIeUIMk

**Comment by PygmalionOfCyprus** [comment]
Handled 497.
