### ISSUE TITLE
BN-2A Islander

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#241]
### DB Selector

DB3K

### Hypothetical

No

### Name

BN-2A Islander

### Country

Zimbabwe

### Service

Air Force

### In Commission

1976-

### Length (m)

aircraft/5381/

### Wingspan (m)

aircraft/5381/

### Height (m)

aircraft/5381/

### Empty Weight (kg)

aircraft/5381/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/5381/

### Payload Weight (kg)

aircraft/5381/

### Crew

aircraft/5381/

### Propulsion

aircraft/5381/

### Rate of Climb (ft/min)

aircraft/5381/

### Service Ceiling (ft)

aircraft/5381/

### Military/Afterburner Speed (kt)

aircraft/5381/

### Cruise Speed (kt)

aircraft/5381/

### Supercruise

No

### Ferry Range (nm)

aircraft/5381/

### Endurance (min)

aircraft/5381/

### Takeoff / Landing Distance (m)

aircraft/5381/

### Fuel Capacity (kg)

aircraft/5381/

### Sensors

aircraft/5381/

### Mounts

aircraft/5381/

### Loadout Options

aircraft/5381/

### Comms/Datalinks

aircraft/5381/

### Comments

Copy preexisting db units to Zimbabwe, picked closest DB match.

### Sources

https://www.flightglobal.com/download?ac=75345
https://en.wikipedia.org/wiki/Air_Force_of_Zimbabwe#Aircraft
https://[cmano-db.com](https://cmano-db.com/aircraft/5381/)/aircraft/5381/
https://web.archive.org/web/20071112052601/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af_current_inventory.htm
https://web.archive.org/web/20070704065635/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af-all-time.htm
https://d1fmezig7cekam.cloudfront.net/VPP/Global/Flight/Airline%20Business/AB%20home/Edit/WorldAirForces2015.pdf

**Comment by PygmalionOfCyprus** [comment]
Added 494.
