### ISSUE TITLE
Add Elbit J-Music and Paws to Nato Airbus A.330-200 MRTT Tankers

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2410]
### DB Selector

DB3K

### Affected DBID(s)

4708

### Summary of Changes

Add sensor 6585 Elbit J-Music and sensor 1921 PAWS

### Sources

https://www.joint-forces.com/defence-equipment-news/42564-j-music-dircm-for-ninth-nato-airbus-a330-mrtt
https://www.militaryaerospace.com/commercial-aerospace/article/14229454/elbit-systems-to-deliver-infrared-selfprotection-systems-to-nato-for-airbus-a330-aircraft
https://elbitsystems.com/product/music/
https://www.airforce-technology.com/news/elbit-systems-to-equip-dircm-and-ew-on-additional-european-air-force-mrtt/

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
