### ISSUE TITLE
Update/correction for HESA Karrar

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2412]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4904, 4903, 5591

### Summary of Changes

-Increase the agility from 1 to 4. The UAV/UCAV have improved flight control to evade potential threat.
![image](https://user-images.githubusercontent.com/99646926/195613293-469e1d79-3283-41ce-93fd-84429525a9f2.png)

-Add 7.62mm minigun loadout to aircraft/5591 . After looking it up for a bit from the comment down below at Source(3)(4), the IR camera were fitted to guide the minigun as well. Based on the picture, the minigun were used to engage airborne target and probably can be used to engage land/surface target as well.
![image](https://user-images.githubusercontent.com/99646926/195618005-ef10de39-1415-4d36-a28b-bc8734abdbcf.png)
![image](https://user-images.githubusercontent.com/99646926/195617952-a26c12fe-fb1e-4dfb-b705-2840898b8c3f.png)

### Sources

https://www.globalsecurity.org/wmd/world/iran/karrar.htm
https://www.oryxspioenkop.com/2019/09/the-oryx-handbook-of-iranian-drones.html
https://twitter.com/mhmiranusa/status/1562873446841090048
https://twitter.com/ResindScientist/status/1563154011532193794

**Comment by Jkryos** [comment]
Added DB3K 499.
