### ISSUE TITLE
Nomenclature correction for the MiG-29M series

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#2414]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft_5628, _4868, 2841, 2613

### Summary of Changes

The MiG-29M aka Izdeliye 9-15 is a substantial modification of the MiG-29/MiG-29S airframe and systems, and was consequentially designated by NATO as the "Fulcrum-E" .  The database currently lists it as a "Fulcrum-C".  See 
https://odin.tradoc.army.mil/mediawiki/index.php/MiG-29_(Fulcrum)_Russian_Multirole_Fighter_Aircraft
https://en.wikipedia.org/wiki/Mikoyan_MiG-29M

### Sources

https://odin.tradoc.army.mil/mediawiki/index.php/MiG-29_(Fulcrum)_Russian_Multirole_Fighter_Aircraft

https://www.globalsecurity.org/military/world/russia/mig-29-variants.htm

https://en.wikipedia.org/wiki/Mikoyan_MiG-29M

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
