### ISSUE TITLE
Japan, UH-60J, JMSDF

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2416]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4314

### Summary of Changes

Loadout
---
Same as this one, 
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1515

Number of units
---
19x

### Sources

https://ja.wikipedia.org/wiki/UH-60J_(%E8%88%AA%E7%A9%BA%E6%A9%9F)

**Comment by Jkryos** [comment]
Updated, by the looks of it same time as #1515 so DB3K 495.
