### ISSUE TITLE
Japan, V-107, JASDF

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2417]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5695

### Hypothetical

No

### Name

V-107 [KV-107II-5]

### Country

Japan

### Service

JASDF

### In Commission

1976 - 2009

### Sensors

add 
2x Search light (DBID 251), right and left side

### Loadout Options

same as base

### Other Changes

There is a variant "V-107A [KV-107IIA-5]" which replaced engine with CT58-IHI-140-1. Commission year is 1973- 2009.

### Sources

https://ja.wikipedia.org/wiki/V-107

**Comment by Jkryos** [comment]
Added DB3K 497.
