### ISSUE TITLE
Japan, V-107A, JMSDF

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2418]
### DB Selector

DB3K

### DBID to Copy

Aircraft 58

### Hypothetical

No

### Name

V-107A [KV-107IIA-3]

### Country

Japan

### Service

JMSDF

### In Commission

1970 - 1990

### Number in Service

7x

### Loadout Options

base + 

Mine Sweep
---
MK-101 (could be similar to MK103, Weapon ID 2430)
MK-104 (Acoustic Mine sweep, Weapon ID 2431))

### Other Changes

Engine is CT58-IHI-140-1

There is a original V-107 [KV-107II-3], which use original T-58-GE-10. only 2 was build as this model and has limited (almost - No) Mine sweep capability.   

### Sources

https://ja.wikipedia.org/wiki/V-107

**Comment by Jkryos** [comment]
Added DB3K 497.
