### ISSUE TITLE
Japan, V-107, JGSDF

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2419]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5695

### Hypothetical

No

### Name

V-107 [KV-107II-4]

### Country

Japan

### Service

JGSDF

### In Commission

1966 - 2002

### Number in Service

42x

### Sources

https://ja.wikipedia.org/wiki/V-107

**Comment by Jkryos** [comment]
Added DB3K 497.
