### ISSUE TITLE
C-212-200 Aviocar

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#242]
### DB Selector

DB3K

### Hypothetical

No

### Name

C-212-200 Aviocar

### Country

Zimbabwe

### Service

Air Force

### In Commission

1983-

### Length (m)

aircraft/3739/

### Wingspan (m)

aircraft/3739/

### Height (m)

aircraft/3739/

### Empty Weight (kg)

aircraft/3739/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/3739/

### Payload Weight (kg)

aircraft/3739/

### Crew

aircraft/3739/

### Propulsion

aircraft/3739/

### Rate of Climb (ft/min)

aircraft/3739/

### Service Ceiling (ft)

aircraft/3739/

### Military/Afterburner Speed (kt)

aircraft/3739/

### Cruise Speed (kt)

aircraft/3739/

### Supercruise

No

### Ferry Range (nm)

aircraft/3739/

### Endurance (min)

aircraft/3739/

### Takeoff / Landing Distance (m)

aircraft/3739/

### Fuel Capacity (kg)

aircraft/3739/

### Sensors

aircraft/3739/

### Mounts

aircraft/3739/

### Loadout Options

aircraft/3739/

### Comms/Datalinks

aircraft/3739/

### Sources

https://[cmano-db.com](https://cmano-db.com/aircraft/3739/)/aircraft/3739/
https://en.wikipedia.org/wiki/Air_Force_of_Zimbabwe#Aircraft
https://www.flightglobal.com/download?ac=75345
https://d1fmezig7cekam.cloudfront.net/VPP/Global/Flight/Airline%20Business/AB%20home/Edit/WorldAirForces2015.pdf
https://web.archive.org/web/20070704065635/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af-all-time.htm
https://web.archive.org/web/20071112052601/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af_current_inventory.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
