### ISSUE TITLE
Japan, V-107A, JGSDF

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2420]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5695

### Hypothetical

No

### Name

V-107 [KV-107IIA-4]

### Country

Japan

### Service

JGSDF

### In Commission

late 1970's

### Number in Service

18

### Sensors

add
Navigation Radar

### Sources

https://ja.wikipedia.org/wiki/V-107

**Comment by Jkryos** [comment]
Added DB3K 497.
