### ISSUE TITLE
Add Shahed-285(AH-85A/B/C) light attack helicopter

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2422]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5713

### Hypothetical

No

### Name

Shahed-285(AH-85A/B/C)

### Country

Iran

### Service

IRGC

### Sensors

AH-85A
1x Mk1 Eyeball

AH-85B
1x Mk1 Eyeball
1x Generic IR camera
1x Generic TV/EO camera
1x Generic Laser Rangefinder
1x Generic RWR
![image](https://user-images.githubusercontent.com/99646926/195847285-52381808-7086-47fd-b276-393f9506d056.png)

AH-85C
1x Mk1 Eyeball
1x Generic IR camera
1x Generic TV/EO camera
1x Generic Laser Rangefinder
1x Generic RWR
1x Surface Search radar(96nm)
![image](https://user-images.githubusercontent.com/99646926/195847380-2eb70e72-1d3f-4fb2-850f-ff20d6f73da1.png)

### Mounts

AH-85A
1x 7.62mm gun(fixed, forward-facing)
1x Generic chaff/flare dispenser
![image](https://user-images.githubusercontent.com/99646926/195845770-a06aca92-ac72-4bee-a2dc-b60d78755c8b.png)

AH-85B
1x 12.7mm gun(rotatable left/right chin turret up to 270 degree)
1x Generic chaff/flare dispenser
![image](https://user-images.githubusercontent.com/99646926/195991165-a9ed78c2-2f22-4ec6-8f40-7f9365ab9f0f.png)

AH-85C
1x Generic chaff/flare dispenser

### Loadout Options

AH-85A
(Rocket loadout)
14x Hydra 70mm rocket(Weapon/1929)
![image](https://user-images.githubusercontent.com/99646926/195846459-fe006eaa-5ffe-41b3-97dd-600a68154b03.png)

AH-85B
(Rocket loadout)
14x Hydra 70mm rocket(Weapon/1929)
![image](https://user-images.githubusercontent.com/99646926/195846389-6dd70838-985f-4b82-890a-dd8c24b06fb0.png)

(ATGM Loadout)
8x Sadid-1(Based on Toophan ATGM,Weapon/2931)
![image](https://user-images.githubusercontent.com/99646926/195846238-30fb8a0b-4833-4176-9ab6-4efea6041e68.png)

AH-85C
(ATGM Loadout)
8x Sadid-1(Based on Toophan ATGM,Weapon/2931)
![image](https://user-images.githubusercontent.com/99646926/195846109-5cf50602-36eb-4f4f-8831-805608583f03.png)

(AShM Loadout)
2x Kowsar(Weapon/3769)
![image](https://user-images.githubusercontent.com/99646926/195846143-c6c3eddd-0423-443b-926a-6aebfed07088.png)

### Other Changes

-AH-85A will have Steam Gauge cockpit, while AH-85B/C have Glass Cockpit(Partial)
![image](https://user-images.githubusercontent.com/99646926/195845654-268ec8b8-443e-4d09-8a25-fe813d48928f.png)
![image](https://user-images.githubusercontent.com/99646926/195845715-a8c05196-c4e2-493d-991c-a4ae3a006edb.png)

-All AH-85 family were to have reduced RCS/IR signature due to the stealthy design

### Sources

https://en.wikipedia.org/wiki/HESA_Shahed_285
https://www.youtube.com/watch?v=ySBz3uex4G8
https://www.globalsecurity.org/military/world/iran/shahed-285.htm
https://www.airliners.net/photo/Iran-Revolutionary-Guard-Navy/HESA-Shahed-AH-85C-285C/1832814
https://www.airrecognition.com/index.php/world-air-force-aircraft/middle-east-countries-air-force-aircrafts-military-equipment/iran-iranian-air-force-------military-aircraft-fighter-aviation-equipment-intelligence-information-description-technical-data-sheet-identification-pictures-photos-video-defence-industry-military-technology-islamic-republic/iranian-air-force-helicopters/390-shahed-285-ah-85a-ah-85b-ah-85c-helicopter-technical-data-sheet-specifications-intelligence-description-information-identification-pictures-photos-images-attack-reconnaissance-maritime-video-iran-iranian-air-force-defence-aviation-industry-military-.html
https://iranpress.com/content/33824/shahed-285-iran-great-step-build-light-attack-helicopters

**Comment by capcop98** [comment]
Dimension wil be as follow:
- Length: 12.94 m
- Height: 3.42 m
- Empty weight: 820 kg
- Maximum weight 1450 kg
![image](https://user-images.githubusercontent.com/99646926/195851014-462c49c4-0ed4-47c2-88b5-feb08694e176.png)
![image](https://user-images.githubusercontent.com/99646926/195851490-07f1940c-192d-4ebe-8360-d739ee31c6cf.png)

**Comment by capcop98** [comment]
Below is the pic of the helicopter fitted with EO sensors. Based on the picture, the aircraft`s EO system cover up to 270 or 300 degree at best.
![image](https://user-images.githubusercontent.com/99646926/195983722-6f54aff7-55e0-444f-a91d-180be80ec393.png)
https://defence.pk/pdf/threads/iran-shahed-278-helicopter.271451/page-4

**Comment by Jkryos** [comment]
Added DB3K 498.
