### ISSUE TITLE
Add  AN/AAR-54 MAWS, LWS-20. and ALR-2001 (Elta EL/M-8300), ALE-47 Chaff and Flare Dispenser to AU Wedgetail

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2423]
### DB Selector

DB3K

### Affected DBID(s)

940

### Summary of Changes

Add to 940.
AN/AAR-54 #2236
LWS-20 : 
ALR-2001 (Elta EL/M-8300)
ALE-47 chaff and flare mounts

Aussie Airpower has stats for ALR-2001. 
Israeli Elta EL/M-8300 (8382) series ESM/ELINT system, which employs a suite of four antenna systems for the microwave bands, mounted under nose, tail and wingtip radomes, and a suite of ventral antennas for the lower bands. Cited EL/M-8300 (8382)  performance parameters are a DF accuracy under 1°, instantaneous bandwidth of ~4 GHz, sensitivity between -70 and -85 dBm, and band coverage between 500 MHz and 18 GHz.

LWS-20 is normally a subcomponent of other systems. Can probably get away with copying a newer generation generic. See 4th link.

Fit for AN/AAQ-24 DIRCM but not yet installed (see 2022 video).

### Sources

https://www.key.aero/article/more-wedgetail-boeing
http://www.ausairpower.net/APA-Wedgetail-Antennas.html
https://www.youtube.com/watch?v=38AOntTJJrE
https://elbitsystems.com/media/Spectrolite-SPS65V5.pdf
https://www.australiandefence.com.au/D70DC507-5056-B05D-570296AA5618F272

**Comment by PygmalionOfCyprus** [comment]
Handled 498. It actually already has the El/ALR-2001 but for some reason the entry was renamed to an IR sensor? I fixed that and added the AAR-54 + generic LWR.
