### ISSUE TITLE
Add AN/AAR-47 to Post 2010 US A-10Cs

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2424]
### DB Selector

DB3K

### Affected DBID(s)

3889, 4821, 3890,4822

### Summary of Changes

Add sensor #2017 to US A-10s post 2010. 

### Sources

https://warthognews.blogspot.com/2009/10/new-warning-system-has-been-identified.html
https://www.af.mil/News/Photos/igphoto/2000540078/
https://manualzz.com/doc/36209088/an-aar-47-v-1-2-sensor-upgrade-program

**Comment by Jkryos** [comment]
Updated DB3K 497.
