### ISSUE TITLE
Dutch KDC-10 Out of Service Date 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2425]
### DB Selector

DB3K

### Affected DBID(s)

3861

### Summary of Changes

Aircraft retired in Oct. 2021. Sold to Omega.

### Sources

https://twitter.com/NATO_AIRCOM/status/1445352994254598144
https://www.aerotime.aero/articles/29098-netherlands-retires-kdc-10-tanker#:~:text=The%20final%20McDonnell%2DDouglas%20KDC,Netherlands%20on%20October%207%2C%202021.
https://www.key.aero/article/rnlafs-final-kdc-10-tanker-leaves-netherlands

**Comment by tbrandon517** [comment]
Just a note that I submitted these for Omega as #1627

**Comment by Jkryos** [comment]
Updated DB3K 497.
