### ISSUE TITLE
AIM-120C-8, AGM-158B and SDB-II for German F-35A

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2427]
### DB Selector

DB3K

### User(s)

5705

### Weapons Carried

4x AIM-120D
-
4x AIM-120D 
2x AIM-9X-2 (External) 
-
2x AGM-158B (External) 
4x AIM-120D 
2x AIM-9X-2 (External) 
-
8x SDB-II 
4x AIM-120D 

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://www.dsca.mil/press-media/major-arms-sales/germany-f-35-aircraft-and-munitions

**Comment by KLABDB3K** [comment]
GBU-31 BLU-109 is amongst this as well.
Not exactly lavish numbers.

**Comment by HunterDNiu** [comment]
> KLABDB3K

Oh yep I saw this sale months ago and wrote it out of memory.

**Comment by HunterDNiu** [comment]
#3561
