### ISSUE TITLE
#1676 - Bell 214A Huey Plus (Iran - 1974) Can a SAR loadout be added please?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2428]
### DB Selector

Both

### Affected DBID(s)

#1676 - Bell 214A Huey Plus (Iran - 1974)

### Summary of Changes

Add SAR option for loadouts please. 
Appreciate this can be modified by LUA but it makes it simpler and the 214's are used predominantly for SAR ops assigned to each IIRAF air base. 

Copy SAR load out 30528 from Canadian Bell 212?

### Sources

DB3K 496 
https://en.wikipedia.org/wiki/Bell_214
https://www.scramble.nl/planning/orbats/iran
https://www.scramble.nl//images/stories/countries/ir/photos/bell214-orbat.jpg

**Comment by Jkryos** [comment]
Updated DB3K 498.
