### ISSUE TITLE
Limit Iskander (SS-26 Stone) flight altitude to 50 (or 40) km due to quasi-ballistic flight path

### ISSUE THREAD

**Issue by rob76pl** [PygmalionOfCyprus/cmo-db-requests#2429]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 1235, 567, 2900

### Summary of Changes

Iskander uses semi/quasi balistic flight path. Various sources contain its flight altitude to 40 or 50 km.

Quote from wikipedia:
'Variant for the [Russian Armed Forces](https://en.wikipedia.org/wiki/Russian_Armed_Forces) with two 9M723 quasi-ballistic missiles with published range 415 km, rumoured 500 km. Speed Mach 6–7, flight altitude up to 6–50 km`

'Iskander-E has a maximum range up to 280 km, to comply with [Missile Technology Control Regime](https://en.wikipedia.org/wiki/Missile_Technology_Control_Regime) restrictions for export,[[81]](https://en.wikipedia.org/wiki/9K720_Iskander#cite_note-38north-20190508-82) and is fitted with a simplified inertial guidance system. It flies on a flattened trajectory under 50 km altitude, allowing aerodynamic steering using tail fins, permitting a less predictable flight path and accurate delivery.'

Quote from rusi.org:
'By contrast, the 9M723 variants rely on a combination of speed, a quasi-ballistic trajectory and penetration aids. With exhaust discharge speeds of roughly 2.5 km/s ([comparable](https://www.centennialofflight.net/essay/SPACEFLIGHT/rockets/SP6.htm#:~:text=The%20Solid%20Rocket%20Boosters%20of,(4%2C447%20meters%20per%20second).) to a space shuttle booster), the 9M723 is powerful enough to fly on a quasi-ballistic trajectory that allows it to use aerodynamic drag to manoeuvre without sacrificing either range or speed to an unacceptable degree. The ability to travel on a quasi-ballistic trajectory represents a significant challenge, both because the missile can spend a longer part of its trajectory under the horizon of air defence radar, and because at altitudes of 40 km the missile flies above the intercept envelope of most air defence systems, such as the PAC-3, but below the envelope of ballistic missile defence interceptors.'

### Sources

https://en.wikipedia.org/wiki/9K720_Iskander
https://rusi.org/explore-our-research/publications/commentary/iskander-m-and-iskander-k-technical-profile

**Comment by rob76pl** [comment]
Detailed analysis of Iskander possible trajectories.
https://github.com/rafal9820/9M723-Iskander-missile-trajectory

**Comment by Huib18** [comment]
Comments on [https://twitter.com/M51_4ever/status/1699097476341411868](url) also valueable!

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
