### ISSUE TITLE
MiG-23MS Flogger E

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#243]
### DB Selector

DB3K

### Hypothetical

No

### Name

MiG-23MS Flogger E

### Country

Zimbabwe

### Service

Air Force

### In Commission

200

### Length (m)

aircraft/199/

### Wingspan (m)

aircraft/199/

### Height (m)

aircraft/199/

### Empty Weight (kg)

aircraft/199/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/199/

### Payload Weight (kg)

aircraft/199/

### Crew

aircraft/199/

### Propulsion

aircraft/199/

### Rate of Climb (ft/min)

aircraft/199/

### Service Ceiling (ft)

aircraft/199/

### Military/Afterburner Speed (kt)

aircraft/199/

### Cruise Speed (kt)

aircraft/199/

### Supercruise

No

### Ferry Range (nm)

aircraft/199/

### Endurance (min)

aircraft/199/

### Takeoff / Landing Distance (m)

aircraft/199/

### Fuel Capacity (kg)

aircraft/199/

### Sensors

aircraft/199/

### Mounts

aircraft/199/

### Loadout Options

aircraft/199/

### Comms/Datalinks

aircraft/199/

### Comments

Copy preexisting db units to Zimbabwe. 3 donated by Libya. Model unknown but I think it's most likely the less capable Mig-23MS Flogger E was passed on.

### Sources

https://[cmano-db.com](https://cmano-db.com/aircraft/199/)/aircraft/199/
https://en.wikipedia.org/wiki/Air_Force_of_Zimbabwe#Aircraft
https://www.flightglobal.com/download?ac=75345
https://d1fmezig7cekam.cloudfront.net/VPP/Global/Flight/Airline%20Business/AB%20home/Edit/WorldAirForces2015.pdf
https://web.archive.org/web/20071112052601/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af_current_inventory.htm
https://web.archive.org/web/20070704065635/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af-all-time.htm
https://web.archive.org/web/20060926225914/http://www.aeroflight.co.uk/waf/aa-africa/zim/mig-23.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.

**Comment by PygmalionOfCyprus** [comment]
Added 494.
