### ISSUE TITLE
Weapon & Mount - 20/3 mm M-55 A4 Triple Burst (Hispano-Suiza HS.804)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2434]
### DB Selector

Both

### Baseline

2204

### Hypothetical

No

### Name

20/3 mm M55A4 Triple Burst (HS.804) [20 rnds]

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

1

### Warhead

20mm Burst [20 rnds]

### Targets

Aircraft, Helicopter, Missile, Surface Vessel, Land Structure - Soft, Mobile Target - Soft, Mobile Target - Personnel

### Sensors

(sensors for ships/vehicles/facilities using this gun):

-Galileo J171 [EO] Gun Director (2nd Gen)

### Comments

20mm triple gun built in Yugoslaviawith the HS.804 license. Please add a mount with the same name to the DB. Used by BOV-3 air defence vehicles and as towed air defence. Equipped with Galileo J171 ballistic computer. Could you please add the weapon, mount and the sensor?

### Sources

https://en.wikipedia.org/wiki/Zastava_M55

https://atutco.com.tr/savunma/upload/AircraftGun20-3M55.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
