### ISSUE TITLE
Weapon & Mount - 20/3 mm M-55 Triple Burst (Hispano-Suiza HS.804)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2435]
### DB Selector

Both

### Baseline

2204

### Hypothetical

No

### Name

20/3 mm M55 Triple Burst (HS.804) [20 rnds]

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

1

### Warhead

20mm Burst [20 rnds]

### Targets

Aircraft, Helicopter, Missile, Surface Vessel, Land Structure - Soft, Mobile Target - Soft, Mobile Target - Personnel

### Sensors

-

### Comments

20mm triple gun built in Yugoslaviawith the HS.804 license. Please add a mount with the same name to the DB. Used by some ships of the Yugoslav/Serbian/Croatian Navy.

### Sources

https://en.wikipedia.org/wiki/Zastava_M55

https://atutco.com.tr/savunma/upload/AircraftGun20-3M55.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
