### ISSUE TITLE
Yugoslavia - AAA Plt 20/3 mm Triple M55

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2438]
### DB Selector

Both

### Hypothetical

No

### Name

AA Plt (20/3 mm M55A4 Triple Towed x 2) -- Yugoslavia

### Facility Type

AAA

### Country

Yugoslavia

### Service

Army

### Dispersion Radius (m)

40

### Sensors

2x Galileo J171 [EO] (only DB3K)
Eyeball Mk1

### Mounts

2x 20/3 mm M55A4 Triple (or 20/3 mm M55 Triple for CWDB)

### Magazines

1200 rounds 20mm each

### Comments

Towed 20mm AAA gun
#2435

### Sources

http://www.balkanwarhistory.com/2017/06/the-zastava-m55-triple-barreled.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
