### ISSUE TITLE
Increase the range of the sensors on various Exoatmospheric ballistic interceptors

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2439]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2609, and others, if applicable

### Summary of Changes

Apparently the interceptor can discriminate&track an exoatmospheric target about 40 nm away. 

### Sources

https://youtu.be/sbv-Vky1aVM?t=1396

**Comment by HunterDNiu** [comment]
With the fixes in 1285.1 this appears to be irrelevant.

**Comment by PygmalionOfCyprus** [comment]
Still irrelevant or has this been intentionally reopened?

**Comment by HunterDNiu** [comment]
> Still irrelevant or has this been intentionally reopened?

I literally don't know what to do... I'll go to the forum to state the situation.

**Comment by PygmalionOfCyprus** [comment]
Roger, feel free to double back if it does turn out to be a DB issue! 🙂
