### ISSUE TITLE
UK Wildcat Defensive update- AN/AAR-57, Sky Guardian and Vicon Chaff and Decoy Launchers

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2440]
### DB Selector

DB3K

### Affected DBID(s)

3372,4221,3374

### Summary of Changes

Wildcat uses the UK version of HIDAS-15
Add Sensors:
#2484 AN/AAR-57
#2209 Sky Guardian 2000
Add Mount
Vicon chaff and decoy launchers on WAH-64

### Sources

https://www.baesystems.com/en-media/uploadFile/20210404053858/1434584248887.pdf
http://www.jetwashaviationphotos.com/825-nas-fleet-air-arm.html
https://monch.com/ebooks/military-technology/2019/04oqs5pk/56/
https://www.youtube.com/watch?v=me0nP2Qfa_g
https://www.key.aero/article/different-beast
https://electronics.leonardo.com/documents/16277707/18390725/HIDAS_15_LQ_mm07744_.pdf?t=1538987440383
Link more for the picture
https://electronics.leonardo.com/en/products/hidas-15-1

**Comment by bostonmyk** [comment]
Looks like South Korea has the same. The Phillipines did not get it.
https://www.seaforces.org/marint/Republic-Korea-Navy/Aviation/AW159-Wildcat-ROKN.htm
https://www.leonardo.com/en/press-release-detail/-/detail/leonardo-selected-by-south-korea-s-lig-nex1-as-a-strategic-technology-partner
https://www.facebook.com/MaxDefense/photos/a.214163865420945/842304162606909/?type=3

**Comment by Jkryos** [comment]
Updated DB3K 497.
