### ISSUE TITLE
Defensive Update Merlin HC.4 and Puma HC.2

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2441]
### DB Selector

DB3K

### Affected DBID(s)

4201,4273

### Summary of Changes

Uses HIDAS suite

Add sensors:
AN/AAR-57 #2484
SG200-D [SEER] #5662
*Merlin HC.3 used Skyguardian #2209
Type 1223 #1330

Mounts
Add vicon chaff and flare mounts (like WAH-64D)

### Sources

https://monch.com/ebooks/military-technology/2019/04oqs5pk/56/#zoom=z
https://www.baesystems.com/en-media/uploadFile/20210404053858/1434584248887.pdf
https://www.leonardo.com/en/press-release-detail/-/detail/leonardo-to-provide-uk-defensive-aids-suite-for-british-army-s-new-apache-ah-64e-helicopters
https://ukdefencejournal.org.uk/exclusive-inside-look-at-the-royal-navys-upgraded-merlin-helicopter/
https://www.reddit.com/r/WarplanePorn/comments/k2kqaf/raf_puma_launching_flares_2048x1282/

**Comment by Jkryos** [comment]
Updated DB3K 497.
