### ISSUE TITLE
Add Chaff and Flare Dispensers to all Army MH-60s

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2442]
### DB Selector

DB3K

### Affected DBID(s)

1597,1599,1598,1606,1609,1602,3711,5254,4464

### Summary of Changes

Add AN/ALE-47 Mount to all MH-60 blackhawk (A,K,L,M, X), 

### Sources

http://www.airvectors.net/avs70_1.html
https://youtu.be/tHVOGhH4o3c?t=21
https://www.americanspecialops.com/night-stalkers/helicopters/mh-60.php
https://www.dstorm.eu/pictures/nose-arts/h-60/mh-60a_2.jpg
https://en.wikipedia.org/wiki/AN/ALE-47

**Comment by bostonmyk** [comment]
Looks like ALE-47 became a product in 1998. Anything before that ALE-40.

**Comment by Jkryos** [comment]
Updated DB3K 497.
