### ISSUE TITLE
Add AN/AAQ-24 LAIRCM to UK Voyager Tanker 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2443]
### DB Selector

DB3K

### Affected DBID(s)

1850,4276

### Summary of Changes

Add DIRCM sensor AN/AAQ-24 #2312 to UK Voyager

### Sources

https://www.airforce-technology.com/projects/a330_200/
http://www.sfte-ec.org/node/798
https://www.airforce-technology.com/news/newsuk-mod-awards-laircm-support-services-contract-to-northrop/https://twitter.com/Swisscheese80/status/1483747036730204160/photo/4

**Comment by PygmalionOfCyprus** [comment]
Handled 498. I also went through and changed our LAIRCM to a sensor group (NEMESIS) composed of both the AN/AAQ-24(V) and AN/AAR-54, since we (and by we, I mean me) were stupidly adding just the IRCM instead of the IRCM and associated MAWS...which would be useful to have...
