### ISSUE TITLE
Israeli Sea Stallion Defensive updates (MAWS, DIRCM, Chaff and Flares)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2444]
### DB Selector

DB3K

### Affected DBID(s)

4732, 5336

### Summary of Changes

Sensors
Add ELM-2160 MAWS  #142
Add Mini Music DIRCM.  Derivative of J-Music DIRCM #6585. Not seen in pictures until 2022

Mounts
AN/ALE-47

### Sources

https://mobile.twitter.com/ElbitSystemsLtd/status/1534876261792862208
https://www.iai.co.il/sites/default/files/2020-02/ELM-2160%20-%20Missile%20Approach%20Warning%20System%20-%20MAWS%20Brochures.pdf
https://twitter.com/idf/status/1362764664267022344
https://elbitsystems.com/product/music/

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
