### ISSUE TITLE
Update MQ-9B STOL to Carrier Capable

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#2445]
### DB Selector

DB3K

### Affected DBID(s)

#.5812 MQ-9B SeaGuardian STOL UAV

### Summary of Changes

Can we update #.5812 MQ-9B SeaGuardian STOL UAV to have Carrier Capable status same as #.4774 XQ-58 Valkyrie as it currently can't take off from CVN or LHA/LHD unless you add runways to the ships.

Thanks

### Sources

DB3K_496

**Comment by FrangibleCover** [comment]
Honestly, I'd counterpropose that anything with STOL capability should be able to take off from a carrier, but you need the carrier-capable tag to land. That would allow for some neat latter-day Doolittle Raid or Club Run scenarios.

**Comment by 5th-Domain** [comment]
Agreed

**Comment by Jkryos** [comment]
Updated DB3K 497. An associated update to LHD and LHA will have to follow to give them the proper "Runway" facilities.

**Comment by 5th-Domain** [comment]
I agree do you want me to do a separate request for that?
