### ISSUE TITLE
Add Sea King ASaC7.AEW Defensive Equipment (AN/AAR-57, ALQ-157, ALE-47 Chaff and Flare Mounts)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2446]
### DB Selector

DB3K

### Affected DBID(s)

506

### Summary of Changes

Add Sensors
Add AN/AAR-57 #2484
ALQ-157 #2295

Add ALE-47 Mount

### Sources

https://books.google.com/books?id=d887DAAAQBAJ&pg=PT446&lpg=PT446&dq=Sea+King+AN/ALQ-157+IR+jammer&source=bl&ots=MWyUNMDX2z&sig=ACfU3U1Ar_ORPU35mbQEVyvcjUquMPibvw&hl=en&sa=X&ved=2ahUKEwipmoa_9Of6AhVnFFkFHQ19BVU4HhDoAXoECB0QAw#v=onepage&q=Sea%20King%20AN%2FALQ-157%20IR%20jammer&f=false

"other modification to the basic sea king including the fitting of an AN/AAR-57 missile warning system, ALQ-157 IR Jammer and M 147 chaff and flare dispenser"

https://commons.wikimedia.org/wiki/File:Westland_WS-61_Sea_King_ASaC7,_UK_-_Navy_AN1290600.jpg
chaff launchers visible and AN/AAR-57 dimples and ALQ-157 temple zits

https://books.google.com/books?id=nntiBwAAQBAJ&pg=PT837&lpg=PT837&dq=Sea+King+AN/ALQ-157+IR+jammer&source=bl&ots=_0y0-GVXsk&sig=ACfU3U0f8nk3jYrHGd1J3QP934PRH9ZBeA&hl=en&sa=X&ved=2ahUKEwjarpyg-Of6AhWUF1kFHXwQAqs4KBDoAXoECBwQAw#v=onepage&q=Sea%20King%20AN%2FALQ-157%20IR%20jammer&f=false

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
