### ISSUE TITLE
Add AN/ALQ-157 IR Jammers and ALE-47 Chaff and Flare Dispensers to Sea King HAS.5 and HAS.6 and Commando HC.4

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2447]
### DB Selector

DB3K

### Affected DBID(s)

1632,2885,2212, 3088, 39, 3089 

### Summary of Changes

Add Sensor ALQ-157 #1492 on both HAS.6-6 and HC.4 1990 (Gulf War).
Add ALE-47 Chaff and Flare Mounts
HC.4 received for Gulf war
HAS.5 and HAS.6 . Added some 1985 or 1986 pictures but not sure how common. Had these for sure Gulf War and beyond.

### Sources

https://www.dstorm.eu/pages/build_instructions/seaking_airfix_en.html
https://www.dstorm.eu/pages/en/gb/seaking.html
https://www.aircraftresourcecenter.com/Fea1/101-200/Fea117-SeaKing-Wong/00.shtm
http://www.aviastar.org/helicopters_eng/west_king.php
https://books.google.com/books?id=ew5CAwAAQBAJ&pg=PA73&lpg=PA73&dq=Sea+King+HC.5,+Chaff+and+Flares&source=bl&ots=tnnUyW5Wqr&sig=ACfU3U2l9yIQ4I6tTy8VYZo1HkvZXUaIyw&hl=en&sa=X&ved=2ahUKEwjSvvmV--f6AhWSF1kFHeFcBH84HhDoAXoECB8QAw#v=onepage&q=Sea%20King%20HC.5%2C%20Chaff%20and%20Flares&f=false

**Comment by bostonmyk** [comment]
Looking over my paper references I'd definitely hold decoys until 1990

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
