### ISSUE TITLE
Add emitter locator (96l6-VP/clone of vega/orion) for S-350 battery

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2448]
### DB Selector

DB3K

### Affected DBID(s)

2089

### Summary of Changes

confirmed via satellite
![96l6-vp deployment satellite](https://user-images.githubusercontent.com/108960393/196601887-417283e6-f985-416c-89f9-a47ec8ee6673.png)

Upon further scrutiny of recent s-350 battery images I noticed a new type of ELINT system integrated within the battery being used in a group of 3, it looks similar to or even an upgrade to the system 85V6 Vega/Orion. For the sake of simplicity it would make sense just to add 1 Vega/Orion clone to the S-350 battery under sensor/vehicle category and just rename it 96l6-VP (using stored dbid for orion/vega). In the future when more detailed info is ever known about the 96l6-vp system (for example military expositions) there can always be changes and tweaks to it, but keeping the base characteristics of orion system is a fair and simpler option  for now.
![s-350 battery #1](https://user-images.githubusercontent.com/108960393/196350618-00cd3205-2a4e-4a51-9f5f-4b1b5e281e06.jpg)

![S-350 battery #2](https://user-images.githubusercontent.com/108960393/196350844-9b35decd-04e5-4e96-87d6-ccd222d7d81f.jpg)

Emitter was shown next to battery back in 2020 or 2019
![battery s350](https://user-images.githubusercontent.com/108960393/196351166-658756ee-089e-4734-95e4-dd6f745707b2.jpg)

3 passive systems and the 96l6-TSP radar form the complex called 96l6-AP (combination and integration of all 4 separate systems into one) which is linked to the command post of the S-350 battery (linked with 50N6A fire control radar)
To make things easier no need to add 3x elint systems, 1 is ok for now. Truth is each system can be a separate passive sensor entirely working on distinct radar bands. For example 1 may be VHF/UHF and HF comms, other may be centimeter bands, and last one may be a command post to merge both together (similar to rlm-k command post in nebo-m system). We don't know, but a fair start would be to assume an upgraded orion variant for now.

Changes: add 1x clone of dbid #2532 (orion/vega) to S-350 battery as sensor and vehicle under new name 96l6-vp. 
Thank you!

Here we see 96l6-tsp with s-350 battery deployed at active airbase in 2022 earlier this fall/summer. The presence of 96l6-tsp indicates the most likely prescience of the 96l6-vp passive locator which is integrated in the battery as shown at military expos and drills, but is not in the image since it can be located up to 7-10km away from 96l6-tsp active radar.
![newvpspspsps](https://user-images.githubusercontent.com/108960393/196898028-38398552-239b-466c-9052-53ae381dcd21.png)

 

### Sources
https://twitter.com/benreuter_IMINT/status/1513128176662290432

https://twitter.com/guyplopsky/status/1233708740513132544

https://twitter.com/Ninja998998/status/1383268221864660992

https://twitter.com/GuyPlopsky/status/1558691787862331392

**Comment by Jkryos** [comment]
Updated DB3K 497.
