### ISSUE TITLE
Hypo cruiser combat gens off.

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#2449]
### DB Selector

CWDB

### Affected DBID(s)

Ships 2189 , 750

### Summary of Changes

Two hypothetical cruiser upgrades in the CWDB still have the combat system generations of their older, unupgraded, real version. (

2819 CAG Boston Hypo: Change combat gen to 4 (1970s) to symbolize the refit and upgraded fire control for its new missiles. (current gen 2)
750 CG Albany Hypo: Change combat gen to 4, similar reason (current gen 3)

### Sources

https://en.wikipedia.org/wiki/USS_Boston_(CA-69)#Decommissioning
Moore, John (1991). Jane's American Fighting Ships of the 20th Century, pg. 126
https://en.wikipedia.org/wiki/Albany-class_cruiser#Weapons_and_systems

**Comment by Jkryos** [comment]
Updated CWDB 497.
