### ISSUE TITLE
Cessna 421 Golden Eagle

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#245]
### DB Selector

DB3K

### Hypothetical

No

### Name

Cessna 421 Golden Eagle

### Country

Zimbabwe

### Service

Air Force

### In Commission

1976-1980?

### Length (m)

aircraft/4968/

### Wingspan (m)

aircraft/4968/

### Height (m)

aircraft/4968/

### Empty Weight (kg)

aircraft/4968/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/4968/

### Payload Weight (kg)

aircraft/4968/

### Crew

aircraft/4968/

### Propulsion

aircraft/4968/

### Rate of Climb (ft/min)

aircraft/4968/

### Service Ceiling (ft)

aircraft/4968/

### Military/Afterburner Speed (kt)

aircraft/4968/

### Cruise Speed (kt)

aircraft/4968/

### Supercruise

No

### Ferry Range (nm)

aircraft/4968/

### Endurance (min)

aircraft/4968/

### Takeoff / Landing Distance (m)

aircraft/4968/

### Fuel Capacity (kg)

aircraft/4968/

### Sensors

aircraft/4968/

### Mounts

aircraft/4968/

### Loadout Options

aircraft/4968/

### Comms/Datalinks

aircraft/4968/

### Comments

Copy preexisting db units to Zimbabwe, picked closest DB match

### Sources

https://[cmano-db.com](https://cmano-db.com/aircraft/4968/)/aircraft/4968/
https://web.archive.org/web/20060926233412/http://www.aeroflight.co.uk/waf/aa-africa/zim/cessna421.htm
https://web.archive.org/web/20070704065635/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af-all-time.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
