### ISSUE TITLE
2 Updates for RLM-D Radar

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2451]
### DB Selector

DB3K

### Affected DBID(s)

1847

### Summary of Changes

1. change band to C/D (0.5-2GHz) combination UHF/L-band - labeled as decametric by multiple sources (higher portion of UHF band/lower-mid portion of L-band) Since it is an upgrade to the previous protivnik-g which is also a UHF band radar operating in upper C band. Most refer to it as L-band but it works on both UHF and L-band. As stated by sources and even manufacturer labeling it as both L-band and UHF on different occasions. Here in this source it is shown as decimeter which includes UHF and lower parts of L-band. Being an upgrade and given the larger transmitter sizes on the antenna UHF would make sense.
![rlm-d proof 5](https://user-images.githubusercontent.com/108960393/196543672-e9c95a76-be58-4434-8f40-836654dd963e.png)
2. increase max range to 600km (320nm) - as shown from this source.  both rlm-m and rlm-d have 320nm max range.
![rlm-d proof 2 (range)](https://user-images.githubusercontent.com/108960393/196543971-04113857-f525-4a85-ac63-36fed6ba949b.png)
It would make sense the rlm-d would have greater range than the protivnik-ge which has a range of 450km for export and up to 500km for domestic version. rlm-d is a AESA upgrade to the PESA protivnik-ge so it has more power and greater range.
![rlm-d proof 4](https://user-images.githubusercontent.com/108960393/196544225-e567b652-8e52-4ab0-8435-e46e1f3831f5.png)
![rlm-d proof 1](https://user-images.githubusercontent.com/108960393/196544228-77a19db9-8222-404d-916b-550f6a871efe.png)

**_summary of changes:
 -change frequency bands to C/D
-increase max range to 320nm_**

thank you! 👍

### Sources

https://www.deagel.com/Sensor%20Systems/RLM-D/a003717

https://en.wikipedia.org/wiki/Nebo-M

https://www.globalsecurity.org/military/world/russia/nebo-m.htm

**Comment by Jkryos** [comment]
Added DB3K 497.
