### ISSUE TITLE
Add ALE-47 Decoy Launchers to US P-3C/EP-3 from 1996 on

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2453]
### DB Selector

DB3K

### Affected DBID(s)

1578,318,2191,4766

### Summary of Changes

Add ALE-47 Chaff and Flare Dispensers to US P-3s from 1996 on. Can use same mount as Aircraft #3335
US received starting from 1996 (first US Link page i)(Alamy photo in last link dated 1996).

### Sources

https://www.globalsecurity.org/military/library/policy/navy/ntsp/ale-47-p_v2_2002.pdf
https://www.designation-systems.net/usmilav/jetds/an-ala2aln.html
https://commons.wikimedia.org/wiki/File:US_Navy_060618-N-9377B-030_Aviation_Ordnanceman_3rd_Class_Cary_Buel_installs_a_MJU-49-B_Decoy_Flare_bucket_into_the_ALE-47_Counter_Measure_Dispensing_system_on_a_P-3C_Orion.jpg
https://www.alamy.com/stock-photo-960900-n-0000f-001-bosniaherzegovina-sep-09-1996-a-p-3c-orion-attached-130350865.html?imageid=F33B3327-03BC-40FF-BBDE-20
https://man.fas.org/dod-101/sys/ac/p-3.htm
https://books.google.com/books?id=dOk6AQAAIAAJ&pg=PA46&lpg=PA46&dq=P-3+Orion,+ALE-47&source=bl&ots=-hqyp-MT5f&sig=ACfU3U0F4qpTAriKvLoae_YX_cglZBqCjg&hl=en&sa=X&ved=2ahUKEwi0qMyLxO_6AhVxMlkFHfcQCbY4HhDoAXoECCIQAw#v=onepage&q=P-3%20Orion%2C%20ALE-47&f=false

**Comment by bostonmyk** [comment]
Looks like Germany got with their P-3s as well
https://www.p3orion.nl/gn-2.pdf pg.41
https://hyperscale.com/2007/features/p3cid_1.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Scale modelers are seem to consistently be someof the most reliable sources out there... 😛
