### ISSUE TITLE
[CWDB] F-4EJ, correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2454]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2370, 2831

### Summary of Changes
**Sensors** 
F-4EJ (1979, ID2831) is using correct equipment; APQ-120, APR-2 and ALQ-6. 

**Loadout**
1973 version is OK
1979 version,  change the commission year to 1975, use same loadout of 1973 version but change sidewinder to AIM-9P-3 (ID 1635).
And add AIM-4D loadout (loadout ID 10322, 10323).  This is because AIM-7F capability added in 1980's, and CWDB lacks AIM-4D capability of F-4EJ which added in 1975. 

### Sources

https://ja.wikipedia.org/wiki/F-4_(%E6%88%A6%E9%97%98%E6%A9%9F)#%E6%B5%B7%E5%A4%96%E3%81%AE%E6%8E%A1%E7%94%A8%E5%9B%BD%E3%81%A8%E6%B4%BE%E7%94%9F%E5%9E%8B%E4%B8%80%E8%A6%A7

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
