### ISSUE TITLE
Add ALE-39 Chaff and Flare Dispenser to S-3B 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2455]
### DB Selector

DB3K

### Affected DBID(s)

9,2007,420,462,465,3841

### Summary of Changes

Add ALE-39 Mounts to S-3B Vikings (same mount as A-6E)

Might want to add the ALE-47, AAR-47 and LAIRCM combo to hypotheticals.

### Sources

http://www.airvectors.net/avs3.html
http://www.clubhyper.com/reference/updatingyourvikingbs_1.htm
https://commons.wikimedia.org/wiki/File:US_Navy_040713-N-7090S-011_As_part_of_an_air-power_demonstration_performed_for_visiting_Moroccan_military_officials_an_S-3B_Viking_assigned_to_the_Maulers_of_Antisubmarine_Thirty_Two_(VS-32)_releases_flares_near_USS_Enterprise.jpg

**Comment by Jkryos** [comment]
Updated DB3K 497.
