### ISSUE TITLE
HESA Shahed 136

### ISSUE THREAD

**Issue by blu3ser** [PygmalionOfCyprus/cmo-db-requests#2456]
### DB Selector

DB3K

### Baseline

4904 

### Hypothetical

No

### Name

HESA Shahed 136

### Country

Iran

### Service

Air Force

### In Commission

2022

### Length (m)

3.5m

### Wingspan (m)

2.5

### Height (m)

1.25

### Empty Weight (kg)

160

### Maximum Takeoff Weight (MTOW) (kg)

200

### Payload Weight (kg)

40

### Crew

0

### Propulsion

MD-550 piston engine

### Service Ceiling (ft)

19685

### Military/Afterburner Speed (kt)

108

### Cruise Speed (kt)

89

### Supercruise

No

### Ferry Range (nm)

1350

### Sensors

None

### Mounts

Aerial Target Drone

### Loadout Options

Aerial Target Drone

### Comms/Datalinks

Autonomous GLONASS

### Aircraft Codes

Terrain Following, Night Navigation/Attack (Incl. Bomb, Rocket Delivery)

### Sources

https://en.wikipedia.org/wiki/HESA_Shahed_136
https://www.barrons.com/news/the-iranian-drone-shahed-136-01666019709

**Comment by KLABDB3K** [comment]
#2214 Duplicate - already closed and actioned.

**Comment by Jkryos** [comment]
Added DB3K 497.
