### ISSUE TITLE
Nigerian and Pakistani JF-17 Aselpod + LGB Loadouts

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2457]
### DB Selector

DB3K

### Affected DBID(s)

5261, 3298,4827,4729,4828

### Summary of Changes

Add Aselpod to Nigerian and Pakistani smart bomb loadouts
Looks like
Aselpod
2- LGB
2- Fuel tank
2 AAM

### Sources

Pakistan
https://twitter.com/RupprechtDeino/status/1236682971245133824/photo/1
https://www.youtube.com/watch?v=mwU9aE4vAcU
Bomb is GBU-12 or Al-Battar (GBU-12 clone) 
https://twitter.com/omer_harry/status/1387142169597825025

Nigeria
https://twitter.com/Jakepor21/status/1583083581387440129
Received GBU-12 with Super Tucano
https://www.defenceweb.co.za/aerospace/aerospace-aerospace/nigerian-super-tucano-sale-includes-guided-bombs-rockets-sensors/

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Was already on the Nigerian one.
