### ISSUE TITLE
Add AC-130J GBU-69 Loadout

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2462]
### DB Selector

DB3K

### User(s)

5697

### Weapons Carried

10 GBU-69 Small Glide Munitions

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Add 10 weapon loadout similar to Griffin, Viper Strike

### Sources

https://www.af.mil/About-Us/Fact-Sheets/Display/Article/467756/ac-130j-ghostrider/
https://www.dote.osd.mil/Portals/97/pub/reports/FY2020/af/2020ac130j.pdf?ver=VGvsp5nR60QRIR__sJKVMw%3D%3D

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
