### ISSUE TITLE
AIM-7E Sparrow, not E-2

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2463]
### DB Selector

Both

### Affected DBID(s)

Weapon 431(DB3K), 321 (CWDB)

### Summary of Changes

Name should be AIM-7E not E-2.
E-2 is short range, high maneuverability Sparrow.

### Sources

https://www.military-today.com/missiles/aim_7_sparrow.htm

**Comment by FrangibleCover** [comment]
How sure are you about this one? My impression has always been that the 7E was completely replaced by the 7E-2 (and then E-3) in service, with the range reduction being accepted in return for increasing the Pk. 

https://en.m.wikipedia.org/wiki/AIM-7_Sparrow

The wiki article indicates that the 7E-2 was widely used in Vietnam, and the further development of the missile into E-3 and E-4 variants based on the E-2 indicates that it was considered the primary developmental pathway for the missile. The question is therefore who got which missile and when.

**Comment by KC45jp** [comment]
I guess the main issue is... We have only AIM-7E-2  in DB, which is considered AIM-7E based on its firing range (16nm).
We should have AIM-7E-2 and other variants in different entries with their spec values.

In my understanding... AIM-7E-2, E-3 and E-4 (Dogfight sparrows, entered service in 1969) are not exported... It is a customized model for the Vietnam war and was soon replaced by AIM-7F (1976).
Based on the book I got about Japanese F-4E.
It clearly stated that the Japanese MoD only purchased AIM-7E and did not buy variants like E-2 or E-4.

Given that AIM-7E in CMO, which is named AIM-7E-2, is used by many units other than US forces, I believe It is better to rename the current entry and make new variants for the workload.

 I am not 100% sure that I answered your question...  But that was my intention for this request.

**Comment by PygmalionOfCyprus** [comment]
I agree w/ KC45jp on this one, it appears that the E-2 entry was added by / used by someone who didn't know the difference between the E, E-2, etc. and just became sort of a catchall for the AIM-7E. In fact, a lot of loadouts using it are even just named w/ "AIM-7E." I've renamed the entry accordingly since I think that's the better option in this situation.
