### ISSUE TITLE
increase EL/M-2248 MF-Star max range to 240nm for Kolkata class destroyer

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2464]
### DB Selector

DB3K

### Affected DBID(s)

2321 , 2360

### Summary of Changes

increase range from 175-240nm

can detect traditional fighter size targets and large aircraft/bombers up to 450km away (240nm) for the destroyers and frigates variants. Kolkata class uses the upgraded 240nm max range version since it's a destroyer.
![star star](https://user-images.githubusercontent.com/108960393/197248797-efb6e7ac-eb00-4901-b414-8d083cf89151.png)

### Sources

https://en.wikipedia.org/wiki/EL/M-2248_MF-STAR

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Also changed it on the other Indian/SK vessels using it.
