### ISSUE TITLE
[DB] PL-21, No Weapon Carrier Platform

### ISSUE THREAD

**Issue by DarkMedic249** [PygmalionOfCyprus/cmo-db-requests#2465]
### DB Selector

Both

### Affected DBID(s)

#4110

### Summary of Changes

Hello there, 

The PL-21 or PL-XX is an active radar-guided long-range beyond-visual-range air-to-air missile that is currently in the weapon database.  However,  there is no current Weapon Carrier Platform for the missile. 

According to sources, the likely Platform to carry the Pl-21/Pl-XX is J-31/J-20/J-16. 

### Sources

[PopSci](https://www.popsci.com/chinas-new-ramjet-engine-triple-range-missiles/#page-3)
[Business Insider](https://www.businessinsider.in/defense/the-us-wants-to-arm-fighters-with-these-new-long-range-missiles-to-hunt-down-china-and-russias-best-jets/articleshow/69931475.cms)
[National Intrest](https://nationalinterest.org/blog/reboot/china%E2%80%99s-new-fighter-jet-problem-australia-199821)
[The Drive](https://www.thedrive.com/the-war-zone/6108/shadowy-new-missile-appears-under-the-wing-of-chinese-j-16-fighter)
[Wikipedia](https://en.wikipedia.org/wiki/PL-21)

**Comment by KLABDB3K** [comment]
Are we even sure this is called PL-21.
Twitter link to follow (when I can find it again!) but PL-17 has apparently been referenced in an 'official' document.

**Comment by PygmalionOfCyprus** [comment]
Nevertheless this has been fixed for a while, the PL-17 (ex-PL-21 entry) is loaded on J-16s, J-20s, etc. and will have more platforms still in 506
