### ISSUE TITLE
Change PL-15&PL-15E propulsion type to "Rocket [Long Burn]" or increase its top speed

### ISSUE THREAD

**Issue by ywturbo** [PygmalionOfCyprus/cmo-db-requests#2469]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3413, 3896

### Summary of Changes

The Chinese AAM PL-15 & PL-15E are propelled with "Dual-Pulse Rocket Motor " in current DB , however the "Rocket [boost&coast]" engine type giving unrealistically low boost time for only 5-6 seconds, making the missile always peters out too early from reaching the envelop.
According to Japanese AAM-4B with the similar "Dual-Thrust Rocket Motor" and "Rocket [Long Burn]" of 20-second boosting time, it is suggested to change the engine type of PL-15/PL-15E to "Rocket [Long Burn]" and increase boosting time to reflect a more realistic performance. 

### Sources

No source but refer to the similar AAM-4B missile engine type in DB.

**Comment by ywturbo** [comment]
As the comment by Dimitris, it might be controversial on whether the PL-15 utilizes Dual-Pulse Rocket Motor OR just uses very high speed up to 5 Mach.  see [https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=389307](url). However, the top speed of PL-15 in current DB is much lower (4.14 Ma) and lost its speed very early. 
Anyway, it is necessary to increase either the boosting time or the top speed to fix the problem.

**Comment by PygmalionOfCyprus** [comment]
Changed rocket engine type. Top speed should already be Mach 5...?
![image](https://user-images.githubusercontent.com/87087226/200915816-aac640bb-c819-440c-bc6b-65c3b6a42740.png)
