### ISSUE TITLE
change frequency bands to E/F for all Big Bird C,D series radars

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2470]
### DB Selector

DB3K

### Affected DBID(s)

2444, 2443, 439, 2169, 2168, 655, 2028, 1638, 1639, 1626, 1636, 1637, 1640, 1625, 39

### Summary of Changes

**summary of changes:**

**_change operating bands for all Big Bird series radars to E/F (2.5-3.3 GHZ)_**

multiple sources indicate the original big bird A radar operated in the 2Ghz range at a minimum, the upgrades such as Big Bird C and D eventually showed a max frequency of 3.3GHZ. Here ausairpower states the 64n6e2 as being a 2GHZ range radar, which evolved into the 91n6e.
![91n6e update 3](https://user-images.githubusercontent.com/108960393/197318688-c817faee-3e6f-4e01-a5fa-146cfc2a2b1a.png)

Here the 91n6E is shown as operating on the high end of 2GHZ spectrum, although other sources claim it operates on the entire spectrum of 2GHz. 
![91n6e update 2](https://user-images.githubusercontent.com/108960393/197318727-2dda353b-0bdd-4643-8945-ae8206794d54.png)

Here is another confirmation from internet that displays operating range in the 2GHZ spectrum. 
![91n6e update 1](https://user-images.githubusercontent.com/108960393/197318730-8c5cdd8f-1e7d-4370-a3ac-c63aeb94b5c6.png)

**At most, the big bird series encompass the higher end of the (E-band) spectrum. Maybe 2.5-2.8GhZ. Therefore an update for minimum Hz from either 2500000000 to 3300000000hz would be reasonable.
I doubt they operate at very low end of 2GHZ entirely otherwise they'd border on L-band and be more longer ranged/anti-stealth. But there's little doubt they operate on the 2GHZ band at some part of it (most likely medium-higher portion).

### Sources

https://twitter.com/lan_D3f/status/1290620303903723520

http://www.ausairpower.net/APA-Acquisition-GCI.html#mozTocId420074

https://www.radartutorial.eu/19.kartei/06.missile/karte014.en.html

https://www.radartutorial.eu/19.kartei/06.missile/karte013.en.html

**Comment by Jkryos** [comment]
Updated DB3K 497.

**Comment by TheBagelInhaler** [comment]
> Updated DB3K 497.

thank you!
