### ISSUE TITLE
LCS reload time for main gun 

### ISSUE THREAD

**Issue by donnie67** [PygmalionOfCyprus/cmo-db-requests#2473]
### DB Selector

DB3K

### Affected DBID(s)

Littoral Combat Ship #2590.   

### Summary of Changes

Correction needed to reload time of main gun,   Currently 12 hours for reloads of main gun

### Sources

No specific source but the reload time appears to be excessive

**Comment by donnie67** [comment]
possible resource for all mk 57 varaints   http://www.navweaps.com/Weapons/WNSweden_57-70_mk123.php

**Comment by PygmalionOfCyprus** [comment]
Fixing this w/ a code-side change, so no DB change necessary. Should see it out in a couple builds.

**Comment by donnie67** [comment]
Hi
Can you pls recheck the fix?

When the mk 57 rounds are expended  the reload is shown at 18 to 20 hours to reload 250 rounds.

Thank you!

**Comment by PygmalionOfCyprus** [comment]
It looks like the code-side change never got completed / pushed. I'll bring it up at our team meeting and see if we can expedite a fix.
