### ISSUE TITLE
IRAN HESA Shahed 136

### ISSUE THREAD

**Issue by yehanactivated** [PygmalionOfCyprus/cmo-db-requests#2483]
### DB Selector

DB3K

### Hypothetical

No

### Name

HESA Shahed 136

### Length (m)

3.56

### Width/Span (m)

2.95

### Diameter (m)

2.95

### Weight (kg)

200

### Range (nm)

0-1350

### Warhead

50kg HE

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

10

### Sensors

Inertially Guided

### Weapon Codes

Terrain Following, Loiter Capability, Bearing-Only Launch (BOL), Weapon - INS Navigation, Weapon - INS w/ GNSS Navigation, Weapon - Pre-Briefed Target Only, Re-Attack Capability, Weapon Altitude Control Possible, Uses GPS, Level Cruise Flight

### Comments

cruise altitude:200fts
PROPULSION:
engine: MD 550
type: piston
max speed: 80kts
guidance type: Inertially Guided

### Sources

https://www.youtube.com/watch?v=-U0usQ-g9GM
https://eurasiantimes.com/deadly-drones-israeli-experts-explains-what-makes-iranian-shahed-136/
https://defence.pk/pdf/threads/russia-inflicted-serious-damage-to-ukrainian-army-by-deploying-iranian-drones-report.751189/
https://en.wikipedia.org/wiki/HESA_Shahed_136

**Comment by capcop98** [comment]
Duplication of #2215 ?

**Comment by KLABDB3K** [comment]
And 2214 and 2456

**Comment by KLABDB3K** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2215#issuecomment-1271847498

**Comment by Jkryos** [comment]
Added DB3K 497.
