### ISSUE TITLE
Shahed-136  drone launcher

### ISSUE THREAD

**Issue by yehanactivated** [PygmalionOfCyprus/cmo-db-requests#2484]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Bty (Shahed-136  launcher)

### Facility Type

SSM

### Country

Iran

### Service

Islamic Revolutionary Guard Corps Aerospace Force

### In Commission

2021-

### Sensors

1× Mk1 eyeball

### Mounts

1×Shahed-136 TEL or 1×Shahed-136（ARM capable）TEL
(5×Shahed-136 or 5×Shahed-136（ARM capable)

### Sources

https://en.defence-ua.com/weapon_and_tech/wsj_states_iranian_kamikaze_drones_used_by_russians_creates_new_dangers_for_ukraines_troops-4257.html

**Comment by Jkryos** [comment]
Added DB3K 497.
