### ISSUE TITLE
Increase the range of all non-powered AGM-154 JSOW glide bombs to 60 NM.

### ISSUE THREAD

**Issue by parkourwalurs** [PygmalionOfCyprus/cmo-db-requests#2485]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 828, 1301, 827, 826, 1342

### Summary of Changes

Currently, the AGM-154 JSOW's range, between all variants, is 45NM. According to the US navy's profile of the missile, its range is in excess of 60 nautical miles when released at high altitude. The Wikipedia article cited in the DB places its range between 12 and 70 nmi based on release profile, which could explain some splitting the difference, but similar glide bombs like the SDB seem to have their database max range based on an optimistic high altitude drop.

### Sources

https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2166748/agm-154-joint-standoff-weapon-jsow/#:~:text=The%20weapon's%20standoff%20range%20of,1B%20and%20B%2D2%20aircraft.

Navy profile of the JSOW, which states that "The weapon's standoff range of 12 to 63 nautical miles allows JSOW to remain outside the threat envelopes of enemy point defenses while effectively engaging and destroying targets."

**Comment by Jkryos** [comment]
Updated DB3K 497.
