### ISSUE TITLE
range corrections for domestic/export variants of Protivnik-GE Radar

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2486]
### DB Selector

DB3K

### Affected DBID(s)

2257 , 3149

### Summary of Changes

Egypt uses the export version of 59N6-TE (Protivnik-GE) with a max range of 450km (~243nm). Reduced from domestic.

Russia uses the 59N6-T Protivnik-G (Domestic version) with a max range of 500km (270nm). 

Egypt's export version shown by exporter 
![59nt-6e range export protivnik-ge](https://user-images.githubusercontent.com/108960393/198510927-29d54642-4563-457f-ab37-b646c4ec6bf3.png)

Russia's domestic version
![59n6-e range domestic protivnik-g](https://user-images.githubusercontent.com/108960393/198510969-fd0121fe-17cf-4929-9879-e876a06c1c42.png)

**summary of changes:**
_for DBID 2257: increase max range to 270nm / 500km
for DBID 3149: set max range to 243nm / 450km_

Thank you! 👍
TheBagelInhaler

### Sources

https://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/59N6-%D0%A2%D0%95/ 

https://www.radartutorial.eu/19.kartei/02.surv/karte013.en.html

**Comment by PygmalionOfCyprus** [comment]
I don't know that I trust RadarTutorial to have an accurate number. 270 just reads to me like they rounded up to a standard Max Instrumented Range. They've been pretty sloppy with a lot of radar entries before.

**Comment by PygmalionOfCyprus** [comment]
I don't dispute that the domestic version probably has better performance but it's probably more subtle than "we limited the instrumented range". Without a better source/confirmation I'm not gonna touch it.

**Comment by TheBagelInhaler** [comment]
> I don't dispute that the domestic version probably has better performance but it's probably more subtle than "we limited the instrumented range". Without a better source/confirmation I'm not gonna touch it.

understandable
