### ISSUE TITLE
Correction: B61-12 bombs for F-35A 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2488]
### DB Selector

DB3K

### User(s)

Aircraft 3491, 4876, 3835

### Weapons Carried

2x AIM-120D 
2x B61-12 

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://www.thedrive.com/the-war-zone/new-b61-12-bombs-precision-unusable-by-some-nuclear-strike-jets

**Comment by KushanGaming** [comment]
Done for DB498.
