### ISSUE TITLE
SA.532UL Cougar Horizon

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#249]
### DB Selector

DB3K

### Hypothetical

No

### Name

SA.532UL Cougar Horizon

### Country

Zimbabwe

### Service

Air Force

### In Commission

1995-

### Length (m)

aircraft/4734/

### Wingspan (m)

aircraft/4734/

### Height (m)

aircraft/4734/

### Empty Weight (kg)

aircraft/4734/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/4734/

### Payload Weight (kg)

aircraft/4734/

### Crew

aircraft/4734/

### Propulsion

aircraft/4734/

### Rate of Climb (ft/min)

aircraft/4734/

### Service Ceiling (ft)

aircraft/4734/

### Military/Afterburner Speed (kt)

aircraft/4734/

### Cruise Speed (kt)

aircraft/4734/

### Supercruise

No

### Ferry Range (nm)

aircraft/4734/

### Endurance (min)

aircraft/4734/

### Takeoff / Landing Distance (m)

aircraft/4734/

### Fuel Capacity (kg)

aircraft/4734/

### Sensors

aircraft/4734/

### Mounts

aircraft/4734/

### Loadout Options

aircraft/4734/

### Comms/Datalinks

aircraft/4734/

### Comments

Copy preexisting db units to Zimbabwe.

### Sources

https://www.flightglobal.com/download?ac=75345
https://en.wikipedia.org/wiki/Air_Force_of_Zimbabwe#Aircraft
https://[cmano-db.com](https://cmano-db.com/aircraft/4734/)/aircraft/4734/
https://d1fmezig7cekam.cloudfront.net/VPP/Global/Flight/Airline%20Business/AB%20home/Edit/WorldAirForces2015.pdf
https://web.archive.org/web/20060926230200/http://www.aeroflight.co.uk/waf/aa-africa/zim/as532.htm
https://web.archive.org/web/20070704065635/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af-all-time.htm
https://web.archive.org/web/20071112052601/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af_current_inventory.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
