### ISSUE TITLE
PL-21 PL-X is actually PL-17. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2490]
### DB Selector

DB3K

### Affected DBID(s)

DB3K weapon 4110 PL-X PL-21 AAM

### Summary of Changes

Appears PL-X PL-21 is in fact named / designated PL-17.
'Official' PLAAF documents on Twitter are using the PL-17 nomenclature.
This is sequentially more logical than the big leap between 15 and 21.
Apparently AFAIK it is an official briefing in which the PL-17 is referenced on screen just after reference to the PL-15 and in the context of it being a 300km+ anti key asset weapon anti AEWAC etc. 
It also seems to be indicating it's an in-service weapon. 
Presumably any Flanker derived platform with a good enough radar to make use of the range could carry it? 
2 x on inner wing pylon? 

### Sources

https://twitter.com/sugar_wsnbn/status/1585582124010156032?t=y1Tb7WVmA6nVR-D9RIs58A&s=19
https://min.news/en/military/f42113fff8bdb2c013e997430e9a62bb.html
But just enter PL-17 in the search engine and there's a number of threads.
https://www.thedrive.com/the-war-zone/a-guide-to-chinas-increasingly-impressive-air-to-air-missile-inventory
PL-17 seems to have been rumoured for some time but the 'document leak' comfirms it.

**Comment by PygmalionOfCyprus** [comment]
Changed the main name to PL-XX, added PL-17, PL-20, PL-21 to comments until this is confirmed-confirmed. (People are still gonna search with the other names, anyway...)
