### ISSUE TITLE
IRIS-T SLM Range and Comms Correction

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#2491]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3581

### Summary of Changes

You show 8 DL channels total? If I read this correctly, then it is incorrect. It is 8 channels per launcher inasmuch as it can put all 24 missiles in the air at the same time, in the same way as Sky Sabre can.  Look at the truck, each has a DL antenna, therefore each has your 8 channels - 8 channels x 3 trucks. This is a very capable system and is more in keeping with a) similar systems and b) German government claims made back when the offer was made.

From a range perspective it is actually 40km, which is 25nm.

All the sources below say its in Ukraine, so given it was being built for Egypt, I would say these are their systems, re-allocated and getting a good OT&E workout in Kiev

### Sources

www.reuters.com/world/europe/ukraine-has-received-iris-t-air-defence-system-germany-spiegel-2022-10-11/
https://www.janes.com/defence-news/news-detail/ukraine-conflict-germany-delivers-first-iris-t-gbad-system-to-kyiv
https://www.ukrinform.net/rubric-ato/3595906-german-irist-already-integrated-into-ukraines-air-defense.html

**Comment by PygmalionOfCyprus** [comment]
Did fix the range, though.
