### ISSUE TITLE
Japan, C-2, Boom Refueling

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2492]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2937 5794 4744

### Summary of Changes

Change their probe Refueling code to Boom Refueling.

### Sources

https://youtu.be/OaqnbC9PNkI?t=75

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
