### ISSUE TITLE
JSOW for F-35A(2025) 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2496]
### DB Selector

DB3K

### User(s)

Aircraft 3835

### Weapons Carried

2x AGM-158C 
2x AIM-120D 
-
2x AGM-158C-1
2x AIM-120D 

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

Aircraft 4876

**Comment by KushanGaming** [comment]
Done for DB498.
