### ISSUE TITLE
SBIRS-GEO 6

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2497]
### DB Selector

DB3K

### Hypothetical

Yes

### Series Name

USA 336

### Satellite Type

MASINT

### Country

United States

### Is Geostationary

No

### COSPAR ID

2022-092A

### Launch/Comm. & Decom./Deorbit Date(s)

USA 336: 2022-08-04

### TLE

1 53355U 22092A   22302.66292769  .00000114  00000-0  00000-0 0  9998
2 53355   6.4310 312.0880 0002728 309.1506 230.6275  1.00267510   931

### Sensors

Sat #34

### Sources

https://www.space-track.org/basicspacedata/query/class/satcat/NORAD_CAT_ID/53355/format/html/emptyresult/show
https://www.space-track.org/basicspacedata/query/class/gp/NORAD_CAT_ID/53355/format/tle/emptyresult/show

**Comment by HunterDNiu** [comment]
With others in this series in GEO the same shall apply. Also the sensor shall be  6263 as fixed in DB 498.

**Comment by KushanGaming** [comment]
Done for DB498.
