### ISSUE TITLE
SBIRS HEO 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2498]
### DB Selector

DB3K

### Hypothetical

No

### Series Name

SBIRS HEO 

### Satellite Type

MASINT

### Is Geostationary

No

### COSPAR ID

USA 184: 2006-027A
USA 200: 2008-010A
USA 259: 2014-081A

### Launch/Comm. & Decom./Deorbit Date(s)

USA 184: 2006-06-28
USA 200: 2008-03-13
USA 259: 2014-12-13

### TLE

USA 184: 
1 29250U 06027B   22297.04802824  .00000078  00000+0  00000+0 0  9996
2 29250  64.2992  78.6202 6433376 260.1603  26.8025  2.17600233 28756
USA 200: 
1 32706U 08010A   22297.44731214 0.00000000  00000-0  00000-0 0    08
2 32706  63.6464 126.2794 6853093 268.8404  91.1596  2.00612210    01
USA 259: 
1 40344U 14081A   22179.92576680 0.00000000  00000-0  00000-0 0    06
2 40344  63.2115 233.1918 6837574 271.4435  17.7233  2.00615000    05

### Sensors

1x Sensor 6263

### Sources

https://en.wikipedia.org/wiki/Space-Based_Infrared_System
https://www.space-track.org/basicspacedata/query/class/satcat/NORAD_CAT_ID/29249/format/html/emptyresult/show
https://celestrak.org/NORAD/elements/gp.php?INTDES=2006-027
https://www.space-track.org/basicspacedata/query/class/satcat/NORAD_CAT_ID/32706/format/html/emptyresult/show
https://www.n2yo.com/satellite/?s=32706

**Comment by KushanGaming** [comment]
Already exist. These are packages on the Trumpet II [Advanced Trumpet, Jumpseat II] satellites.

**Comment by HunterDNiu** [comment]
They don’t have the correct sensors. In highly elliptical orbit they need the longer range ones to be functional.
Also please check the TLIs as the Trumpet, NOSS and skysat series seems to have several  sats at the same place.

Niu

On Dec 10, 2022, at 11:37 PM, Kushan ***@***.***> wrote:

﻿

Already exist. These are packages on the Trumpet II [Advanced Trumpet, Jumpseat II] satellites.
