### ISSUE TITLE
Sensors on the SBIRS Satellites

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2499]
### DB Selector

DB3K

### Affected DBID(s)

Satellite 34

### Summary of Changes

Change the sensors to Sensor 6263. 

### Sources

"The SBIRS program is designed to provide key capabilities in the areas of missile warning, missile defense, battlespace characterization and technical intelligence via satellites in geosynchronous Earth orbit(GEO), sensors hosted on satellites in highly elliptical orbit(HEO), and ground-based data processing and control." 
https://en.wikipedia.org/wiki/Space-Based_Infrared_System

Considering that HEO SBIRSs(#2498) are intended to provide early warning while high overhead to provide continuous coverage to areas of high latitude, this change will also fit them.

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Also changed sat category to Geo-Stationary.
