### ISSUE TITLE
Chinese Type 54 Jiangkai MLU #1682 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#25]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1682

### Summary of Changes

Only a class of 2 shops but #1682 Type 54 Jiangkai I [525 Manshan] completed MLU in 2021. Replace HQ-7 with 24 round HQ-10. ESM and ECM updated to 726 which seems to be standard ECM for most Chinese Combatants now. New decoy launchers 8x3 (current fit probably ok). CIWS is PJ-13 which is a copy of AK-630M (look at Type 022) very small CIWS not beefy. PJ-13 is the Chinese designation. Likely has the VDS (same as other 054/056). First one seems completed, Manshan.

### Sources

https://www.sinodefenceforum.com/t/type-054-a-ffg-thread-ii.4149/page-499
https://www.sinodefenceforum.com/t/type-054-a-ffg-thread-ii.4149/page-502
https://www.sinodefenceforum.com/t/type-054-a-ffg-thread-ii.4149/page-501
https://twitter.com/stoa1984/status/1401920382098104326/photo/1
</evidence>

**Comment by PygmalionOfCyprus** [comment]
Actually handled this off of the old tracker earlier in the cycle. Added 493.
