### ISSUE TITLE
O-2A Super Skymaster

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#250]
### DB Selector

DB3K

### Hypothetical

No

### Name

O-2A Super Skymaster

### Country

Zimbabwe

### Service

Air Force

### In Commission

aircraft/3907/

### Length (m)

aircraft/3907/

### Wingspan (m)

aircraft/3907/

### Height (m)

aircraft/3907/

### Empty Weight (kg)

aircraft/3907/

### Maximum Takeoff Weight (MTOW) (kg)

aircraft/3907/

### Payload Weight (kg)

aircraft/3907/

### Crew

aircraft/3907/

### Propulsion

aircraft/3907/

### Rate of Climb (ft/min)

aircraft/3907/

### Service Ceiling (ft)

aircraft/3907/

### Military/Afterburner Speed (kt)

aircraft/3907/

### Cruise Speed (kt)

aircraft/3907/

### Supercruise

No

### Ferry Range (nm)

aircraft/3907/

### Endurance (min)

aircraft/3907/

### Takeoff / Landing Distance (m)

aircraft/3907/

### Fuel Capacity (kg)

aircraft/3907/

### Sensors

aircraft/3907/

### Mounts

aircraft/3907/

### Loadout Options

aircraft/3907/

### Comms/Datalinks

aircraft/3907/

### Comments

Ex-US, Acquired to supplement Reims Cessna FTB.337G 'Lynx'  fleet.

### Sources

https://[cmano-db.com](https://cmano-db.com/aircraft/3907/)/aircraft/3907/
https://web.archive.org/web/20060926232950/http://www.aeroflight.co.uk/waf/aa-africa/zim/lynx.htm
https://web.archive.org/web/20071112052601/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af_current_inventory.htm
https://web.archive.org/web/20070704065635/http://www.aeroflight.co.uk/waf/aa-africa/zim/zim-af-all-time.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
