### ISSUE TITLE
Increase FoV to 90°  for Stunner Missile Radar Seeker (David's Sling)

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2502]
### DB Selector

DB3K

### Affected DBID(s)

5918

### Summary of Changes

Stunner missile uses an AESA radar seeker which have a minimum FOV of 90 degrees. (source: wikipedia)
![stunner 2](https://user-images.githubusercontent.com/108960393/199191946-31732417-76e2-46cc-a4f6-59fad56b9552.png)

Currently the seeker has only a 45 degree FOV which is standard for mechanically scanned pulse doppler active radar seekers. Also I'm not sure if AESA function is added to the missile properties. If it isn't, please do so.

AESA radars typically have a FOV of 90-120 °. Smaller seekers would have a 90°   whereas larger aircraft radars using AESA antennas would have 120 ° or sometimes even greater (for example 5th gen, rafale, typhoon, etc) Exceptions to this wide FoV are some advanced PESA hybrid radars like the snow leopard irbis-E.
![stunner 1](https://user-images.githubusercontent.com/108960393/199192094-9219a407-78b5-4a42-bf6d-f9a739d0acf0.png)

Changes To Be Made:
1. Increase FoV to 90 ° for missile seeker 
2. Add AESA function to missile seeker properties (if not already added)

Thank you!

### Sources

https://en.wikipedia.org/wiki/David%27s_Sling

https://radausa.com/blog/pesa-radar-vs-aesa-radar

**Comment by PygmalionOfCyprus** [comment]
Handled 498.

**Comment by TheBagelInhaler** [comment]
Thank you! please also update the seeker FoV for other AESA air-air missiles including Japan AAM-4B, China PL-15, and Russian K-77M. They all should be 90 degree FoV since they are also AESA seekers
