### ISSUE TITLE
Adding an underwater pipeline facility

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2503]
### DB Selector

Both

### Hypothetical

No

### Name

Underwater Pipeline

### Facility Type

Supply

### Country

Generic

### Sensors

None

### Mounts

None

### Comments

May include multiple lengths(40nm, 100nm etc.)as is in the case of the runways. 

### Sources

https://en.wikipedia.org/wiki/Nord_Stream_1

**Comment by KushanGaming** [comment]
Added to DB3K in DB498.
