### ISSUE TITLE
USMC F/A-18C still in service and APG-79 Upgrade

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2505]
### DB Selector

DB3K

### Affected DBID(s)

4688

### Summary of Changes

Delete the out of service date as they're still deploying. It looks like 2018 was the last F/A-18C carrier deployment but all land-based now.

Add sensor APG-79v4 #6368 starting in 2022

### Sources

https://theaviationist.com/2022/03/30/usmc-legacy-hornets-eastern-europe/
https://www.usafe.af.mil/News/Article-Display/Article/3058799/marine-hornets-swap-nato-enhanced-air-policing-role/
https://www.reddit.com/r/aviation/comments/swylul/us_marine_corps_fa18c_hornet_over_the_united_arab/

APG-79
https://seapowermagazine.org/raytheon-flies-apg-79v4-gan-aesa-radar-in-marine-corps-f-a-18/
https://www.thedrive.com/the-war-zone/19508/the-best-of-the-usmcs-aging-f-a-18-hornets-to-receive-aesa-radar-upgrade

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
