### ISSUE TITLE
SG-1 naval surface and low air search radar

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2508]
### DB Selector

CWDB

### Hypothetical

No

### Name

SG-1 (USN WW2)

### Sensor Generation

Early 1950s

### Range (nm)

0.3-37

### Sensor Capabilities

Air Search, Surface Search, Periscope Search, Range Information, Speed Information, Heading Information, Navigation Only

### Sensor Codes

Periscope Search - Basic Capability, Pulse-Only radar

### Search/Track Frequencies

F Band (3-4 GHz) [Old S Band] 7.5-10 cm

### Lower Frequency (Hz)

3,000,000

### Upper Frequency (Hz)

3,100,000

### Scan Interval (s)

4

### Target Altitude (ft)

0ft ASL - 3000ft ASL

### Horizontal Beamwidth (deg)

5

### Vertical Beamwidth (deg)

15

### Processing Gain/Loss (dB)

23

### Peak Power (W)

50000

### Pulse Width (μs)

2

### PRF (Hz)

775

### Comments

search & navigation
37nm (75,000 yards) instrumented range

max detection range:
-  would pick up task groups at up to 37nm (75,000 yards)
- battleship sized ships, aircraft carriers, large auxilliaries up to 27nm (55,000 yards)
- cruiser sized ships (ww2 era), medium auxiliaries up to 20nm (40,000 yards)
- destroyer sized ships (ww2 era), large patrol ships up to 17nm (35,000 yards)
- submarines (ww2 era sized) up to 7.5nm (15,000 yards)
- submarine periscopes up to 2nm (4,000 yards)

- large planes (1000-3000ft alt) up to 20nm (40,000 yards)
- small planes (1000-3000ft alt) up to 10nm (21,000 yards)

min detection range:
- ships 0.3nm (600 yards)
- planes 0.6nm (1200 yards)

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient4/karte056.en.html

https://www.smecc.org/mcmahon's_radars!.htm

SG-1 type of target:
https://archive.hnsa.org/doc/radar/part4.htm#pgSG-4

page 106, antenna 66abj
https://archive.org/details/DTIC_AD0323191/page/n105/mode/1up?q=%22Sg+1%22&view=theater

**Comment by nuk92** [comment]
used by #2257 and a lot of other ships in cwdb for sure

**Comment by nuk92** [comment]
Added sources

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
