### ISSUE TITLE
Remove GBU-38 integration loadout #27829 on AV-8B #836 as 2002 too early to have

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#251]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 836

### Summary of Changes

Spain didn't get GBU-38 for Harrier until 2018. Not sure the US got it until 2005ish

### Sources

https://www.nato.int/cps/en/natohq/news_139432.htm
http://www.matrixgames.com/forums/fb.asp?m=4789414

**Comment by Jkryos** [comment]
(DB3K 493) Updated loadout name to reflect in service year but left on ID# 836 as the 2002 variant is the most recent in service model for the Spanish air force.
