### ISSUE TITLE
China, PLAAF, AKF98A, stealth cruise missile

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2511]
### DB Selector

DB3K

### Baseline

weapon 2378

### Hypothetical

No

### Name

AKF98A ALCM

### Length (m)

4

### Width/Span (m)

2

### Diameter (m)

0.75

### Weight (kg)

1000

### Range (nm)

430

### Warhead

400kg he/penetrator/submunition

### Targets

Surface Ships, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

2

### Sensors

1x IIR Seeker
1x passive radar seeker
1x DECM (Late 2010s)

### Weapon Codes

Home On Jam (HOJ), Terrain Following, Weapon - INS w/ GNSS Navigation, Uses BeiDou/COMPASS, Level Cruise Flight, Terminal Maneuver - Random, Re-Attack Capability, Supports Waypoint

### Comments

It may have a low observable air intake integrated into the body of missile.
RCS front/rear: 0.0003-0.00003 or just same as weapon 333
RCS side: 0.0006-0.00006 or just same as weapon 333
Speed: 550kt
A datalink is needed

Affected DBID: **Aircraft 4905 5596 4926 6450 6098**

### Sources

https://www.sinodefenceforum.com/t/plaaf-munitions-ii.6652/page-35
https://www.janes.com/defence-news/news-detail/update-airshow-china-2022-new-airborne-stand-off-weapons-unveiled
![image](https://user-images.githubusercontent.com/107970049/213899193-71dccdb0-7e91-458c-9582-38e899c3b7d0.png)

**Comment by LuigiP57** [comment]
#2512

**Comment by LuigiP57** [comment]
#2520

**Comment by LuigiP57** [comment]
More on its characteristics (mainly stealth and power). Through more image comparison, I think it is possible that the stealth performance of this missile is better than that of SCALP or Taurus (it has a cleaner shape and internal air intakes), and the most reasonable estimate should be between them and JASSM/LRASM.
https://en.rattibha.com/thread/1589295074692993028

I really don't want to overpraise the Chinese but I can't find any other reason to disparage them. Its shape is almost perfect for radar stealth (although not as perfect as JASSM/LRASM).

**Comment by LuigiP57** [comment]
Maybe consider adding same loadout as J-16 to the J-15B (**Aircraft_6098**)? Image from CCTV military channel.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/859a0d80-d5c6-49da-966a-8afa954b3584)

**Comment by LuigiP57** [comment]
https://www.sinodefenceforum.com/t/chinese-air-to-ground-weapons-missiles-pgms-etc.6652/page-38
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/fa2489bf-abb8-4418-a1ee-b91a223dd193)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/80485ec7-722f-4abd-8a66-494314d3b821)

@PygmalionOfCyprus @Jkryos 
As the above photos show, this weapon was not the first to appear at the 2022 Zhuhai Air Show, and has already been mass-installed in PLAAF combat units (AKF088C "Sino-SLAM-ER").

At the same time, from the PLAAF's ammunition arrangement in the figure, it is clear that this weapon is different from the GB6 sub-munition dispenser

**Comment by PygmalionOfCyprus** [comment]
This is a good-looking missile. I like it.

Handled 506.
