### ISSUE TITLE
China, PLAAF, JH-7A2, AKF98A Loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2512]
### DB Selector

DB3K

### User(s)

JH-7A2, PLAAF

### Weapons Carried

Long range:
2x AKF-98A
2x PL-8A
2x drop tank

Heavy:
4x AKF98A
2x PL-8A
2x drop tank

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://www.sinodefenceforum.com/t/plaaf-munitions-ii.6652/page-35

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
