### ISSUE TITLE
Sky Bow III missile target altitude problem

### ISSUE THREAD

**Issue by WoodZou** [PygmalionOfCyprus/cmo-db-requests#2513]
### DB Selector

DB3K

### Affected DBID(s)

Guide Weapon #888

### Summary of Changes

In DB3K v492 - target altitude: 100000 ft- 80000 ft

This altitude window makes it impossible to counter any target, too high for aircraft targets, and too narrow for ballistic missiles.
The minimum altitude should be changed to 30ft(refer to PAC II GEM+)

I reported this problem since 3yrs ago, and this problem affected almost all Taiwan war scenarios, I hope this time it can be fixed. 

### Sources

https://www.ncsist.org.tw/eng/csistdup/products/product.aspx?product_Id=11&catalog=28

**Comment by PygmalionOfCyprus** [comment]
This problem has been fixed since DB 493.
