### ISSUE TITLE
Please add HESA Kowsar(F-5F copy) of Iranian Air Force

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2514]
### DB Selector

CWDB

### DBID to Copy

3591 F-5F Tiger II (Iran -1990)

### Hypothetical

No

### Name

HESA Kowsar

### Country

Iran

### Service

Air Force

### In Commission

2018

### Number in Service

4

### Sensors
1x Mk1 Eyeball

1x BAYYENAT II (copy of  Grifo-346, Sensor/6437)
Below is the specification of the radar. The radar also probably have illumination capability to guide R-27R(Weapon/1901) (from Mig-29 stock).
![image](https://user-images.githubusercontent.com/99646926/197724433-46f44e20-0c6d-408e-8c72-0c1adf5352ae.png)

IEI SAIRAN Electronic Warfare suite that included:
1x RWR(Sensor/2919)
1x MAWS(Sensor/2216)
1x ECM Jammer (Sensor/825)
![image](https://user-images.githubusercontent.com/99646926/197724901-9d5f1a17-8774-438b-86dd-644ddad70e41.png)

### Mounts

1x 20mm M39 revolver cannon
1x generic chaff/flare dispenser

### Loadout Options

**Air to Air Loadout**
(WVR Loadout)
4x Fatter/Azarakhsh(Weapon/3941)
 or
4x R-73(Weapon/1896)
![image](https://user-images.githubusercontent.com/99646926/197732153-bf20c88e-88b3-49da-b1e5-70ec46883738.png)

(BVR Loadout)
4x R-27R(Weapon/1901)
 or
(possible procurement)
4x R-77(Weapon/273) or PL-12(Weapon/1116)
![image](https://user-images.githubusercontent.com/99646926/197732239-642ff3f9-828b-400c-8b15-e076bf791923.png)

**Air to Land/Surface Loadout**
(Rocket Loadout)
76x Hydra 76mm rocket
2x Fatter/Azarakhsh(Weapon/3941)
![image](https://user-images.githubusercontent.com/99646926/197732449-2d6b6eaf-26b5-4828-969e-11901c797069.png)

(Guided bomb)
5x Yasin GPS guided bomb(Weapon/4120) with 2x Fatter/Azarakhsh(Weapon/3941)
 or
12x Balaban GPS guided bomb(Weapon/3647) with 2x Fatter/Azarakhsh(Weapon/3941)
![image](https://user-images.githubusercontent.com/99646926/197732515-2ba854fe-a3b0-456c-825b-9278695c2954.png)

(Land Attack missile)
3x Ghassed/Qassed-3(100km range/basically rocket-powered Qassed-1,Weapon/3090) with 2x Fatter/Azarakhsh(Weapon/3941)
![image](https://user-images.githubusercontent.com/99646926/197732597-7efca148-2e04-4cba-ae6c-3c24bf471092.png)

(Maritime Strike Loadout)
2x Ghadir(Weapon/2408) with 2x Fatter/Azarakhsh(Weapon/3941)
 or
3x Nasr-1(Weapon/2390) with 2x Fatter/Azarakhsh(Weapon/3941)
![image](https://user-images.githubusercontent.com/99646926/197732800-af61fdf4-13f5-4968-8723-26caf36dbd4d.png)

**Other Loadout**
Ferry /Training(Similar to Aircraft/3591)

Buddy-illumination (probably based on Taiwan`s F-5E/F AN/AVQ-27 loadout)
1x TLS-99(Weapon/3089)
2x Fatter/Azarakhsh(Weapon/3941)

EW Loadout
1x Shahin ECM(probably similar as the one carried Mohajer-6, Weapon/3760)
![image](https://user-images.githubusercontent.com/99646926/197732952-b19015dd-6d8d-47e9-ae51-0a7c67fce228.png)

### Other Changes

- Comms/Datalinks:
  VHF Radio[Secure]
  UHF Radio[Secure]
  PL-12 Datalink

- Aircraft Codes
  Terrain Avoidance, Terrain Following, Fly-by-Wire, Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced 
  Navigation (INS/GPS)

- The aircraft have Glass Cockpit
![image](https://user-images.githubusercontent.com/99646926/197734141-8b18ea97-4262-4fd5-9f2c-df960f2eaecd.png)
![image](https://user-images.githubusercontent.com/99646926/197735400-5d303427-2c83-4858-9682-8f3143786efe.png)

- Aircraft`s Agility increased from 3.5 o 4 as it have FBW system
![image](https://user-images.githubusercontent.com/99646926/197734747-601c6054-589c-4f7f-a346-fe7f8bca23f3.png)

- The aircraft is akin to FA-50(fighter-attacker/advanced trainer), so Multirole(Fighter/Attack) fit the aircraft`s category better.
![image](https://user-images.githubusercontent.com/99646926/197735207-2afdac43-0cf7-4e22-8136-126c8724d516.png)

- Engine renamed to J90-OWJ(Iranian copy of J-85)

### Sources

https://defence.pk/pdf/threads/hesa-fighter-kowsar-program-current-and-next-generation.743327/
https://en.wikipedia.org/wiki/HESA_Kowsar
https://www.youtube.com/watch?v=IHJnyYm3_YM

**Comment by capcop98** [comment]
The aircraft also have HMD system
![image](https://user-images.githubusercontent.com/99646926/200171755-54149ea7-a370-402f-8f5e-9cf4973530b8.png)

and apparently some of the model have refueling probe too
![image](https://user-images.githubusercontent.com/99646926/200171708-a8b7fb4f-7ae3-4eb1-bb6f-fc504c4e37c6.png)

so  Aircraft Codes: "Helmet Mounted Sight/Display (HMS/HMD)" and "Probe Refueling" can be added in as well

**Comment by capcop98** [comment]
I rechecked this request again and apparently i put the wrong DB category 😅

**Comment by capcop98** [comment]
The aircraft should have existing loadouts from Aircraft/3591

The aircraft were said to also being able to fire carry and fire Fakour-90. SO the BAYYENAT-II should be able to illuminate the missile as well.
![image](https://user-images.githubusercontent.com/99646926/203264165-240a1da8-18ed-497b-8b86-98c8c6ff30a0.png)
(In Indonesian)
![image](https://user-images.githubusercontent.com/99646926/203264233-6172b5f2-8a88-480c-b7c6-04f77f6bb81b.png)

So the loadout`s configuration can be:
Fakour-90(Heavy)
2x Fakour-90(Weapon/2784)
1x 275 USG drop tank(Weapon/2607)

Fakour-90(light)
1x Fakour-90(Weapon/2784)
2x2x Fatter/Azarakhsh(Weapon/3941)
2x 275 USG drop tank(Weapon/2607)

Source:
- https://jakartagreater.com/2018/12/16/iran-dikabarkan-akan-ekspor-kowsar-kemana/
- https://defence.pk/pdf/threads/iriaf-news-and-discussions.358559/page-511
- https://defence.pk/pdf/threads/irans-new-fighter-jets-ready-for-export-who-might-buy.736182/page-5
- https://theaviationist.com/2020/06/25/iranian-air-force-delivered-three-kowsar-jets-domestically-upgraded-f-5fs-destined-to-its-new-aerobatic-team/ (Additional info regarding the aircraft being delivered to IRIAF)

**Comment by Jkryos** [comment]
Added DB3K 498
