### ISSUE TITLE
Please Add Upgraded AH-1J Sea Cobra (Project TOOPHAN II) of IRGC

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2515]
### DB Selector

DB3K

### DBID to Copy

1675 AH-1J Sea Cobra

### Hypothetical

No

### Name

AH-1J TOOPHAN II

### Country

Iran

### Service

IRGC

### In Commission

2017

### Sensors
1x Mk1 Eyeball
1x AN/APR-39(V)2 RWR (Sensor/1375)
Oqab EO/IR targeting turret (Probably also included laser designator and rangefinder as well)

### Mounts

Retain the 20mm M197

### Loadout Options

all existing Iranian AH-1J Sea Cobra`s loadout and also included:

- Toophan-2 Loadout
   8x Toophan-2 (Weapon/2931)
   32x Hydra 70mm rocket (Weapon/1929)
![image](https://user-images.githubusercontent.com/99646926/200149226-cd5ede4a-b23b-43f1-9b14-5cd1083c46ca.png)

- Qaem-114(Iranian copy of AGM-114 Hellfire, 4 different seekers were produced)
   8x Qaem-114 laser version(copy of Weapon/683)
   or
   8x Qaem-114 IIR version
   or
   8x Qaem-114 TV/EO version
   or
   8x Qaem-114  millimeter wave radar seeker(copy of Weapon/966)
![image](https://user-images.githubusercontent.com/99646926/200149179-0a5e21d5-6bf0-4dae-811e-dbc0960db6d8.png)
![image](https://user-images.githubusercontent.com/99646926/200149185-9587d372-ff12-4f61-a70c-1d13e3b013f4.png)
![image](https://user-images.githubusercontent.com/99646926/200149211-1f55037f-4588-4d67-aec9-4e442e19f410.png)

### Other Changes

- It were upgraded with glass cockpit
![image](https://user-images.githubusercontent.com/99646926/200149164-7677f2c8-c68f-4ef4-8f72-ee76fc8c9b0c.png)

- The aircraft`s code is to be replaced with below due to the upgrade:
  Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Computing

### Sources

https://www.key.aero/article/depth-irans-recently-upgraded-ah-1j-cobra-fleet
https://daydaynews.cc/en/military/948601.html
https://twitter.com/BabakTaghvaee/status/858135096318205952
https://twitter.com/mhmiranusa/status/1412708257496547330
https://thedeaddistrict.blogspot.com/2020/12/close-up-of-newest-iranian-a2g-qaem-114.html
http://www.airvectors.net/avcobra_2.html

**Comment by capcop98** [comment]
Some Iranian upgraded AH-1J also have chaff/flare dispenser. 
![image](https://user-images.githubusercontent.com/99646926/200437346-276ac37a-6859-4e3b-87e3-34d051fbc5ed.png)
![image](https://user-images.githubusercontent.com/99646926/200437442-bb9c3049-4241-4cbc-aca7-854c630bbca4.png)

and also Almas loadout(Weapon/3994)
![image](https://user-images.githubusercontent.com/99646926/200437498-899c4425-a542-448f-9977-1753baf67e5e.png)

Source: https://twitter.com/AmirIGM/status/1568327590527516672/photo/4

**Comment by PygmalionOfCyprus** [comment]
Handled 499 as part of ongoing Iran review.

**Comment by KLABDB3K** [comment]
https://x.com/IranDefense/status/1753835155595116749?t=M79AHIrMCLKfDIUOxDkRIg&s=19
There is a new three station pylon enabling loads of  6 Shafaq (all variant) missiles versus 4.
