### ISSUE TITLE
Please add upgraded Bell-214A of Iranian Army

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2516]
### DB Selector

DB3K

### DBID to Copy

Aircraft 1676 Bell-214A Huey Plus

### Hypothetical

No

### Name

Bell 214A/C Isfahan (Upgraded)

### Country

Iran

### Service

Army

### In Commission

2019

### Sensors

1x Generic IR camera
1x Generic TV camera
1x Generic Laser rangefinder
1x Generic laser designator
1x Mk1 Eyeball

### Loadout Options

 all existing Iranian Bell-214`s loadout and also included:

Qaem-114(Iranian copy of AGM-114 Hellfire, 4 different seekers were produced)
   4x Qaem-114 laser version(copy of Weapon/683)
   or
   4x Qaem-114 IIR version
   or
   4x Qaem-114 TV/EO version
   or
   4x Qaem-114  millimeter wave radar seeker(copy of Weapon/966)
![image](https://user-images.githubusercontent.com/99646926/200150017-798b52f8-18fc-4ba2-a991-56cff33e825d.png)
![image](https://user-images.githubusercontent.com/99646926/200149185-9587d372-ff12-4f61-a70c-1d13e3b013f4.png)
![image](https://user-images.githubusercontent.com/99646926/200149211-1f55037f-4588-4d67-aec9-4e442e19f410.png)

- Gun/Rocket loadout
30x 20mm M197(Weapon/629)
19x Hydra 70mm rocket (Weapon/1929)
![image](https://user-images.githubusercontent.com/99646926/200150195-cc591bbb-5b22-42a8-8c83-9bba6aa7a742.png)
![image](https://user-images.githubusercontent.com/99646926/200150209-dcfc6e33-8c8d-44a2-8a9c-634023eec37e.png)

- Rocket only loadout
 38x Hydra 70mm rocket (Weapon/1929)
![image](https://user-images.githubusercontent.com/99646926/200150245-52507e87-828c-4b98-a5d4-b67be77184e3.png)

### Other Changes

- The aircraft is at least glass cockpit[Partial]
![image](https://user-images.githubusercontent.com/99646926/200150259-4c34abaa-7948-4946-b9c0-0b68a28aae91.png)

- The aircraft`s code is to be replaced with below due to the upgrade:
Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Computing

### Sources

https://twitter.com/PePo_25/status/1256123754150838272
https://twitter.com/maysam21901/status/1089087164766437376
https://www.scramble.nl/military-news/eqtedar-99-shows-modified-and-repainted-bell-214s
https://daydaynews.cc/en/military/948601.html

**Comment by capcop98** [comment]
And apparently Iranian Police also operated Bell-214.
![image](https://user-images.githubusercontent.com/99646926/200152588-6c87f4ac-a8e3-4f48-8297-ea4ec461a69f.png)
https://www.jetphotos.com/photo/440585

and based on the pics below, the cockpit is at least Glass Cockpit [Partial]
![image](https://user-images.githubusercontent.com/99646926/200152680-104c3271-725b-4e17-832f-b1d1a5441ac2.png)
https://www.airliners.net/aircraft-data/bell-204205214b/73

**Comment by KLABDB3K** [comment]
Plus a SAR/CSAR option as per Scramble DB they are assigned to each airbase for search and rescue purposes.

**Comment by capcop98** [comment]
The helicopter were apparently fitted with 12.7mm gun at helicopter`s sides. The gun is slightly visible at the screenshot below: 

![image](https://user-images.githubusercontent.com/99646926/207356535-41524202-d5e5-4572-8fa3-0909b072cef0.png)

Source: https://www.youtube.com/watch?v=OamwDU6xosE

**Comment by PygmalionOfCyprus** [comment]
Added 499 during larger Iran review.
