### ISSUE TITLE
Please add Shahed 171 Simorgh of IRGC

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2517]
### DB Selector

DB3K

### DBID to Copy

Aircraft/2787 RQ-170A Wraith[Sentinel]

### Hypothetical

No

### Name

Shahed 171 Simorgh

### Country

Iran

### Service

IRGC

### In Commission

2014

### Sensors

similar to Aircraft/2787 except remove AN/APY-8 Lynx as there is nothing indicated that it have surface-search radar like the Sentinel.

### Loadout Options

similar to Aircraft/2787 with addition to:

4x Sadid-1(Based on Toophan ATGM,Weapon/2931)
![image](https://user-images.githubusercontent.com/99646926/200151688-c7a9c481-68ce-43e9-b616-5dc46a12d859.png)

### Other Changes

Below pic is for the references
![image](https://user-images.githubusercontent.com/99646926/200151708-0790f49e-30dd-439a-8401-00c4273e3c6a.png)

### Sources

https://en.wikipedia.org/wiki/Shahed_171_Simorgh
https://www.bellingcat.com/news/mena/2018/02/13/sentinels-saeqehs-simorghs-open-source-information-irans-new-drone-syria/
https://defence.pk/pdf/threads/meet-shahed-171-simorgh-iranian-multi-role-jet-powered-stealth-un-manned-combat-aerial-vehicle-ucav-of-iran.719049/

**Comment by Jkryos** [comment]
Added DB3K 499.
