### ISSUE TITLE
Update/Correction for Balaban PGM

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2518]
### DB Selector

DB3K

### Affected DBID(s)

Weapon/3647

### Summary of Changes

- Rename the Balaban INS/GPS[500lb Glide PGM] into Balaban SDB [INS/GPS, 45kg HE] .The bomb is supposed to be Iranian version of SDB

- Change the warhead from Mk82`s to 45kg Penetrator(similar to SDB II, Weapon/2855). 
![image](https://user-images.githubusercontent.com/99646926/200154944-dd8b6531-2e9f-4bc3-848d-319d7195c651.png)
![image](https://user-images.githubusercontent.com/99646926/200154932-10a18994-2efe-4e20-b002-91f2ab97fe9f.png)

- Change the weapon`s profile into similar as FT-10(Weapon/3895)
Length: 1.8m
Span: 1.4m
Diameter: 0.2m
Weight: 135kg

![image](https://user-images.githubusercontent.com/99646926/200154913-e176ee81-8ba2-467e-9106-b8a60239d9c4.png)
Balaban(left) can been seen as way smaller than Yasin(Right), which is derived from MK82 bomb.
![image](https://user-images.githubusercontent.com/99646926/200154965-8ddf395e-285c-42d2-8306-e770f8ac2e90.png)

### Sources

- https://twitter.com/maysam21901/status/1158770525176586241
- https://twitter.com/fieldmarshalpso/status/1158678639753519105?lang=en (Even though this source doesn`t show Karrar with Yasin PGM, Oryxspioenkop did posted a picture of Karrar carrying it.)
![image](https://user-images.githubusercontent.com/99646926/200155190-be73bbbb-7768-4439-9660-7aba32eab169.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
