### ISSUE TITLE
Please add F-4E/D [Upgraded, Project Dowran] of Iranian Air Force

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2519]
### DB Selector

DB3K

### DBID to Copy

Aircraft/3896

### Hypothetical

No

### Name

F-4E/D Phantom II [Upgraded, Project Dowran]

### Country

Iran

### Service

Air Force

### Sensors

1x Bayyenat-I (Iranian Copy of JL-10A with 150km search range)
1x AN/APR-37
1x Mk1 Eyeball
![image](https://user-images.githubusercontent.com/99646926/200165491-8a20dee4-349c-4c71-972f-13e9883ebb1c.png)
![image](https://user-images.githubusercontent.com/99646926/200165511-7046f66d-6170-4464-8f67-1cc2a3107ea5.png)

### Mounts

Similar as Aircraft/3896

### Loadout Options

All existing loadout from Aircraft/3896 with addition to:

- Ghader loadout:
2x Ghader
2x AIM-7E2
2x 370 USG drop tank
1x 600 USG drop tank
![image](https://user-images.githubusercontent.com/99646926/200165864-cd3cb26f-08d5-4a5d-9f1d-507202107204.png)

- PL-12(Hypothetical):
4x PL-12
4x PL-7/AIM-9S
2x 370 USG drop tank
1x 600 USG drop tank
![image](https://user-images.githubusercontent.com/99646926/200165894-c4792e64-21cc-4aaf-9689-f211c1f07cd1.png)

### Other Changes

-The Cockpit is at least Glass Cockpit[Partial]
![image](https://user-images.githubusercontent.com/99646926/200165915-14943484-3b5d-4ee2-94dc-a25812176160.png)

-It probably have AA-12 datalink to guide hypothetical PL-12 loadout

### Sources

https://defence.pk/pdf/threads/iriaf-news-and-discussions.358559/page-509
https://defence.pk/pdf/threads/iriaf-news-and-discussions.358559/page-549#post-13956281

**Comment by KLABDB3K** [comment]
PL-7 is a Matra Magic 1 knock off, not likely at all as a loadout as its performance was poor and I'd be sceptical it was still offered for export when PL-9C etc is the preferred export offering with better performance and physical fit. Single threads in a forum speculating on hypothetical upgrades don't exude authority amd as it states PL-12 has never been seen on an Iranian aircraft?

**Comment by capcop98** [comment]
Yes, hence the loadout were quoted as hypothetical. No PL-12 is being seen in Iran so far, their mainstay BVR is mostly Fakour-90, Sparrow and R-27R.

**Comment by capcop98** [comment]
On the second thought, I think i got the name wrong. the SM names were given by one of the account in the forum and not the legit/confirmed name of these upgraded F-4E/D. So the name for now should be F-4E/D [Upgraded, Project Dowran]
![image](https://user-images.githubusercontent.com/99646926/200234407-d25b30c0-9e92-4a52-9c6d-e5bb4f59b23e.png)

Here is the another source about the upgrade:
https://www.keymilitary.com/article/ancient-rhinos

**Comment by capcop98** [comment]
Another source that indicated that PL-7 were chosen to be used alongside PL-12 for the Dorwan Project. Probably because PL-7 is already in Iranian`s stock (for F-7N and F-5).
![image](https://user-images.githubusercontent.com/99646926/200236038-3640df9c-c727-4a4f-b0ad-c930c2c367f8.png)
https://www.sinodefenceforum.com/t/china-helping-iran-to-upgrade-f-4-phantoms.6568/page-3

**Comment by capcop98** [comment]
Replaced with request #2575 since the upgraded aircraft already in the DB but needed some corrections
