### ISSUE TITLE
RCN FFH Type 26 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#252]
### DB Selector

DB3K

### Affected DBID(s)

3192

### Summary of Changes

- I have attached the latest graphic from the RCN which updates the ships weapons and components from what is entered currently for the platform. It seemed like overkill to enter them all here line by line since there are so many changes. Would it be easier if I request a new platform with the latest updates for CSC since there are so many?

### Sources

https://www.navalnews.com/naval-news/2020/11/royal-canadian-navy-unveils-new-details-on-csc-frigates/
http://www.navy-marine.forces.gc.ca/en/fleet-units/csc-home.page
https://en.wikipedia.org/wiki/Type_26_frigate

![CSC-option-img-05](https://user-images.githubusercontent.com/99632305/154574844-b714ef8c-6142-4e5c-b582-5b3b449e02bd.jpg)

**Comment by tbrandon517** [comment]
Additional Source

https://www.thedrive.com/the-war-zone/37506/canadas-new-frigate-will-be-brimming-with-missiles?fbclid=IwAR1j4WHdOp24gm3y1ZxProXcsl-pRFM6myxyTPCKDUxoEpwRTyU3QpOBdD8

**Comment by cdnice55** [comment]
Updated Graphic with some changes, notably 24 MK141 VLS instead of 32, change in weight and crew.

[csc-fact-sheet-eng.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8192000/csc-fact-sheet-eng.pdf)

**Comment by PygmalionOfCyprus** [comment]
I ripped out its guts and rebuilt it. It should now be much, much better. Pretty much as accurate as it can be at this stage of development (though I have no idea what the "Solid State AESA Target Illuminator" by MDA is, so that's not in there yet.

**Comment by cdnice55** [comment]
I have emailed a Canadian Navy expert that I know to see what he thinks, will share if any clarity is found. I did find this, might help a bit or not:

https://www.defencetalk.com/military/forums/t/macdonald-detwiller-associates-mda-canada-to-develop-x-band-illuminator-for-csc-frigate.14984/

**Comment by cdnice55** [comment]
I just heard back, he says it is a new x-band radar, on the graphic it is the smaller square array under/above the SPY 7 antennas. One for each SPY 7. He says he doesn't have any information on performance though.

Hope that helps.

**Comment by PygmalionOfCyprus** [comment]
That's actually quite useful. Based on that, I'm assuming its vaguely similar to the KRONOS StarFire, so I've copied that to create a new sensor; as we get more info, of course, we can implement it.

**Comment by KLABDB3K** [comment]
https://x.com/ReadyAyeReady/status/1898767365204238467?t=KKNieNRDIvqjG0sArSkuPQ&s=19

Got a name now.

**Comment by cdnice55** [comment]
Updates:

https://defence-industry.eu/canada-unveils-updated-design-for-river-class-destroyers/
