### ISSUE TITLE
China, J-16 PLAAF 2018, AKF98A Loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2520]
### DB Selector

DB3K

### User(s)

PLAAF J-16 2018

### Weapons Carried

Long range:
2x AKF98A
2x PL-12
2x PL-10

Heavy:
4x AFK98A
2x PL-10

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://www.sinodefenceforum.com/t/plaaf-munitions-ii.6652/page-37#post-910306

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
