### ISSUE TITLE
Please add Abu Mahdi long-range Anti-Ship Missile (Soumar Mod)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2521]
### DB Selector

DB3K

### DBID to Copy

Weapon/3258

### Hypothetical

No

### Name

Abu Mahdi ASCM (Soumar Mod)

### Country

Iran & Hezbollah

### Service

-

### In Commission

2020-Present

### Sensors

1x Active radar seeker (Late 2000 gen)
1x Passive radar seeker (Late 2000 gen)

### Mounts

4x TELs with 3 missiles each (just like Soumar`s)
![image](https://user-images.githubusercontent.com/99646926/200177371-359711ff-28c6-48ac-a6a2-4c0523b6893a.png)
![image](https://user-images.githubusercontent.com/99646926/200177387-0ad5f3b6-549f-44b5-84f8-849748c7c667.png)

### Other Changes

-Weapon`s range is around 540 nautical miles(1000KM)
![image](https://user-images.githubusercontent.com/99646926/200177040-b6c64ef2-c67c-4623-afab-dc65c803cece.png)
![image](https://user-images.githubusercontent.com/99646926/200177198-d3dad26b-3c08-4582-b412-35fdf091f641.png)

-Weapon`s cruise altitude should be around 30ft, like most of the AShM.
![image](https://user-images.githubusercontent.com/99646926/200176969-a4cfd0f0-b408-4bfa-b5c7-2a03aa782c83.png)

-Weapon`s valid target should be as below:
Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway

-Weapon`s CEP would be around 4 meter.

-The weapon`s code should be as below: 
Home On Jam (HOJ), Flight Profile - Terrain Following, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Terminal Maneuver - Zig-Zag, Re-Attack Capability, Flight Profile - Level Cruise Flight

### Sources

https://twitter.com/inbarspace/status/1576285507788546048
https://twitter.com/Ukraine66251776/status/1549291847167737858
https://twitter.com/Shahed_136_/status/1530183375142666244
https://en.wikipedia.org/wiki/Abu_Mahdi_(missile)
https://defence.pk/pdf/threads/iranian-missiles-news-and-discussions.227673/page-322#post-12657425

**Comment by PygmalionOfCyprus** [comment]
Handled 499 as part of ongoing Iran review.
