### ISSUE TITLE
Mk12 fire control radar - Mk 37 GFCS

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2524]
### DB Selector

CWDB

### Baseline

639 (mk25)

### Hypothetical

No

### Name

Mk12 [Mk 37 GFCS]

### Sensor Generation

Early 1950s

### Range (nm)

22

### Sensor Capabilities

Air Search, Surface Search, Range Information, Altitude Information, Speed Information

### Sensor Codes

Continuous Tracking Capability, Pulse Doppler Radar (Limited LDSD Capability), Generates AAW Fire-Control Data

### Search/Track Frequencies

C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm

### Lower Frequency (Hz)

920,000,000

### Upper Frequency (Hz)

970,000,000

### Scan Interval (s)

1

### Vertical Beamwidth (deg)

10

### Peak Power (W)

100000

### Pulse Width (μs)

1

### PRF (Hz)

480

### Comments

used as fcr for 5 inch guns

fire control radar, weapon director
range resolution 460m

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient5/karte023.en.html

**Comment by nuk92** [comment]
#2257

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
