### ISSUE TITLE
Mk22 fire control radar - Mk 37 GFCS

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2525]
### DB Selector

CWDB

### Baseline

639 (mk25)

### Hypothetical

No

### Name

Mk22 [Mk 37 GFCS]

### Sensor Generation

Early 1950s

### Range (nm)

10

### Sensor Capabilities

Air Search, Surface Search, Range Information, Altitude Information, Speed Information

### Sensor Codes

Continuous Tracking Capability, Pulse Doppler Radar (Limited LDSD Capability), Generates AAW Fire-Control Data

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

9,345,000,000

### Upper Frequency (Hz)

9,405,000,000

### Scan Interval (s)

1

### Peak Power (W)

35000

### Pulse Width (μs)

0.5

### PRF (Hz)

1639

### Comments

Auxiliary radar for the Mk37 fire control system. Provides the fcs with accurate range and altitude data for angles lower than 10 degrees since this is a limitation of the Mk12 radar. Usually a ship is equipped with both radars mounted on the same mk37 gfcs turret.

fire control radar, weapon director
range resolution 90 meters

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient5/karte024.en.html

**Comment by nuk92** [comment]
#2257

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
