### ISSUE TITLE
GARC-ASuW Needs HERO 120 Datalink Comm Device?

### ISSUE THREAD

**Issue by smcclaire** [PygmalionOfCyprus/cmo-db-requests#2529]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3845

### Description of Problem

The ship employs the Hero 120 loitering munition but does not have a comms device capable of datalinking with the weapon, so  Hero 120s launched by the ship can't be controlled via F1/F3.  Possibly intentional, but I assume not as the weapons themselves do have a datalink comms device.

### Recommended Fix

Add comms device "Hero missile datalink" to ship.

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
