### ISSUE TITLE
Airbus A.330-200 MRTT, Spain

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#253]
### DB Selector

DB3K

### Hypothetical

No

### Name

Airbus A.330-200 MRTT

### Country

Spain

### Service

Air Force

### In Commission

2023

### Length (m)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Wingspan (m)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Height (m)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Empty Weight (kg)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Maximum Takeoff Weight (MTOW) (kg)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Payload Weight (kg)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Crew

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Propulsion

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Rate of Climb (ft/min)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Service Ceiling (ft)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Military/Afterburner Speed (kt)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Cruise Speed (kt)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Supercruise

No

### Ferry Range (nm)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Endurance (min)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Takeoff / Landing Distance (m)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Fuel Capacity (kg)

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Sensors

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Mounts

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Loadout Options

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Comms/Datalinks

same as #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019)

### Comments

Please clone #4708 - Airbus A.330-200 MRTT [MFF] (NATO - 2019), ideally after Airbus A.330-200 MRTT, cargo loadouts, properties #194 have been closed.

3 aircraft will be converted to MRTT, from airliner A.330-200. "The handover of the first fully converted aircraft is scheduled in 2023 and the third and final unit in 2025"

### Sources

https://www.airbus.com/en/newsroom/press-releases/2021-11-spanish-ministry-of-defence-signs-order-for-three-airbus-a330-mrtt

**Comment by PygmalionOfCyprus** [comment]
Added 493. Will tackle the matter of cargo loadouts, etc. shortly.
