### ISSUE TITLE
DDG-125 Jack H. Lucas SLQ-59

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#2530]
### DB Selector

DB3K

### Affected DBID(s)

#2718

### Summary of Changes

Jack H. Lucas' starboard AN/SLQ-59 is missing a sector
![DDG-125 SLQ-59 Sectors](https://user-images.githubusercontent.com/101542189/200729443-3c365138-aec4-4f65-ab86-6f303c9f728d.PNG)

### Sources

Using the port one as a guide

**Comment by PygmalionOfCyprus** [comment]
This is actually WAD, this simulates Ensign Schmuckatelli standing in front of the array.

Threw Ensign Schmuckatelli overboard in 498.
