### ISSUE TITLE
HPQ-101B/C Should detect surface contact

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2531]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5915 5916

### Description of Problem

Should detect surface contact, while it is area surveillance aircraft of Navy. Perhaps you can delete Ground search ability.

### Recommended Fix

Add Surface Search Capability.

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
