### ISSUE TITLE
Long Range Discrimination Radar

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2532]
### DB Selector

DB3K

### Baseline

6673

### Hypothetical

No

### Name

Long Range Discrimination Radar(LRDR)

### Sensor Generation

Early 2020s

### Range (nm)

2800

### Sensor Capabilities

Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Non-Cooperative Target Recognition (NCTR) - Narrow Beam Interleaved Search and Track [Class Info], Continuous Tracking Capability, Track While Scan (TWS), Moving Target Indicator (MTI), Pulse Doppler Radar (Limited LDSD Capability), Active Electronically Scanned Array (AESA), Interrupted Continuous Wave Illumination, Frequency Agile

### Search/Track Frequencies

F Band (3-4 GHz) [Old S Band] 7.5-10 cm

### Scan Interval (s)

5

### Target Altitude (ft)

1400000-15800000

### Horizontal Beamwidth (deg)

1.5

### Vertical Beamwidth (deg)

1.5

### System Noise Level (dB)

2.0

### Processing Gain/Loss (dB)

-1.8

### Peak Power (W)

900000.0

### Pulse Width (μs)

0.4

### Blind Time (μs)

6.4

### PRF (Hz)

267

### Comments

240deg coverage at Clear SFS, IOC 2021. 
SPY-7 is derived from this system. 
"LRDR will address hypersonic missiles in future configurations." https://www.mda.mil/video/LRDR%20Introduction_21-MDA-10996.mp4, at 69s. 
LRDR may discriminate&track objects "as small as bolts, []decoies and countermeasures". Id, at 117s. 
LRDR "merge[s] the long reach capabilities of lower frequency radars with the high resolution of higher frequency radars". Id, at 156s. 
"OCTOBER 2015, LOCKHEED MARTIN WAS AWARDED THE PRIME CONTRACT TO DEVELOP, BUILD, INSTALL AND TEST THE RADAR." https://www.mda.mil/video/LRDR%20MILCON%20Construction_21-MDA-10996.mp4 at 107s. 

### Sources

https://en.wikipedia.org/wiki/Long_Range_Discrimination_Radar
https://www.lockheedmartin.com/en-us/products/long-range-discrimination-radar.html
https://missilethreat.csis.org/defsys/lrdr/
https://www.defensenews.com/land/2018/12/09/heres-the-latest-on-lockheeds-massive-long-range-anti-ballistic-missile-radar/
https://www.mda.mil/video/LRDR%20Introduction_21-MDA-10996.mp4
https://www.mda.mil/video/LRDR%20MILCON%20Construction_21-MDA-10996.mp4

**Comment by KushanGaming** [comment]
Done for DB498.
