### ISSUE TITLE
GhostEye(LTAMDS) 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2536]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6746, 6747

### Summary of Changes

The sensor is Active Electronically Scanned Array. 
The secondary array shall have 9x2 illumination capability. The secondary array comprises two faces. 

### Sources

https://www.raytheonmissilesanddefense.com/what-we-do/missile-defense/air-and-missile-defense-systems/ghosteye
https://www.defensenews.com/native/raytheon-missiles-defense/2021/10/21/ghosteye-nothing-goes-unseen/
https://www.raytheonmissilesanddefense.com/news/2020/10/02/soldiers-see-and-touch-full-scale-ltamds

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
