### ISSUE TITLE
C-1, Engine Type

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2538]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 814 4753 4759

### Summary of Changes

ALL
---
Use Turbofan engine, not Turboprop
Max Speed: 440kn (M0.76)
Cruise Speed: 350kn (M0.65)

C-1 (DBID 814)
--- 

**loadout**
Change) Ferry - Max Range 1300 nm
Add) Cargo 2.6 tons - Max Range = 920nm (one way distance)

### Sources

https://www.mod.go.jp/asdf/equipment/yusouki/C-1/index.html

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
