### ISSUE TITLE
Please consider adding KH-15S to available in-game weapons...

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#254]
### DB Selector

DB3K

### Hypothetical

No

### Name

KH-15S

### Length (m)

4.78

### Width/Span (m)

0.92

### Diameter (m)

0.455

### Weight (kg)

1200

### Range (nm)

80

### Target Altitude / Depth (ft)

0 ASL

### Launch Altitude / Depth (ft)

1000 Ft. AGL - 65000 Ft. ASL

### Warhead

150 Kg SAP

### Targets

Surface Vessel

### CEP (m)

4

### Sensors

1x L-Band (NATO) Active Radar Seeker (•5nm Range•) + (•Arcs: PB2, SB1•) + (•Illuminates: PB1, PB2, PMF2, SB1, SB2, SMF1•) >>> "• •" = Suggested

1x •Passive Radar Seeker• (•10nm Range•) + (•Arcs: PB1, PB2, SB1, SB2•) >>> "• •" = Suggested

### Weapon Codes

Home On Jam (HOJ), Search Pattern, Bearing-Only Launch (BOL), Weapon - INS Navigation, Level Cruise Flight

### Comments

--Maximum Speed: 3300 Knots 
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

--Cruise/Max Altitude: 130,000 Ft. 
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

--Propulsion: SRM-160 solid fuel rocket engine
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

--Launch Platforms: 
-Tu-22M-3 (DBID's: 1669, 1670, 1671, 2438, & 2456)
-Tu-22M-3M (DBID's: 2837 & 4951)
-Tu-95MS/MSM (DBID's: 62, 447, 520, 773 & 1611)
-Tu-160 (DBID's: 280, 357, 408, & 1465)
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

### Sources

1. (https://www.glrobalsecurity.org/military/world/russia/as-16.htm)
2. (https://www.globalsecurity.org/military/world/russia/as-16-specs.htm)
3. (https://military-history.fandom.com/wiki/Kh-15)
4. (http://astronautix.com/k/kh-15s.html)
5. (https://web.archive.org/web/20140806154247/http://www.ktrv.ru/about/structure/458/459/)
6. (https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15))

**Comment by KLABDB3K** [comment]
An observation but I have never seen any real image of an operational SU-30/35etc with this missile despite spending hours checking for RuAF VKS armament updates.

**Comment by nkocevar** [comment]
> An observation but I have never seen any real image of an operational SU-30/35etc with this missi

Do you suggest I add the "hypothetical" tag to the weapon request until photographic evidence is obtained? I provided a source that gives a full detailed history of the "State Machine-Building Design Bureau "Raduga", which is the original Soviet-era manufacturer of the X-15 (a.k.a Kh-15) missile. The page is all in Russian so you may have to use the translate feature. If you search "KH-15S", it will bring you down to the point in the article that lists all the different launch platforms for the upgraded version of the KH-15, the KH-15S...

**Comment by nkocevar** [comment]
@PygmalionOfCyprus Please reconsider this issue being assigned an addition label rather than a copy label, because I believe this weapon is different enough to have its own entry in the database... Or am I misunderstanding how this works?

**Comment by PygmalionOfCyprus** [comment]
"Copy" just means it's less work for us to add it because there's a similar entry in the DB we can work off of (as opposed to an addition where we need to add it from scratch). In this case I can copy the extant KH-15 entry and make changes to that.

Being tagged as a copy is a good thing! :)

**Comment by nkocevar** [comment]
> "Copy" just means it's less work for us to add it because there's a similar entry in the DB we can work off of (as opposed to an addition where we need to add it from scratch). In this case I can copy the extant KH-15 entry and make changes to that.
> 
> Being tagged as a copy is a good thing! :)

Ah, okay. Thanks!

**Comment by claudejdev** [comment]
Hey there, according to Butowski, Piotr. Russia's Air-Launched Weapons: Russian-Made Aircraft Ordnance Today. Houston, Harpia Publishing, 2017. Page 10.

Name would be Kh-15P (izdeliye 115P). Kh-15 has a nuclear warhead. Kh-15S (izdeliye 117) is the anti-shipping version.
Launch Altitude / Depth (ft) would be 984-72178 ft (due to conversion from 300-22 000 m).
Its Passive Radar Seeker would be the PRK-15.

**Comment by nkocevar** [comment]
> Hey there, according to Butowski, Piotr. Russia's Air-Launched Weapons: Russian-Made Aircraft Ordnance Today. Houston, Harpia Publishing, 2017. Page 10.
> 
> Name would be Kh-15P (izdeliye 115P). Kh-15 has a nuclear warhead. Kh-15S (izdeliye 117) is the anti-shipping version. Launch Altitude / Depth (ft) would be 984-72178 ft (due to conversion from 300-22 000 m). Its Passive Radar Seeker would be the PRK-15.

Are you sure you aren't referring to the Kh-15P ARM missile I submitted a request for in issue #261? This request isn't for the Kh-15P ARM missile with passive radar seeker, but the Kh-15S anti-ship missile with an active radar seeker...

**Comment by claudejdev** [comment]
> > Hey there, according to Butowski, Piotr. Russia's Air-Launched Weapons: Russian-Made Aircraft Ordnance Today. Houston, Harpia Publishing, 2017. Page 10.
> > Name would be Kh-15P (izdeliye 115P). Kh-15 has a nuclear warhead. Kh-15S (izdeliye 117) is the anti-shipping version. Launch Altitude / Depth (ft) would be 984-72178 ft (due to conversion from 300-22 000 m). Its Passive Radar Seeker would be the PRK-15.
> 
> Are you sure you aren't referring to the Kh-15P ARM missile I submitted a request for in issue #261? This request isn't for the Kh-15P ARM missile with a passive radar seeker, but the Kh-15S anti-ship missile with an active radar seeker...

Hey Noah, the details I quoted can be applied to both of your requests as it brings elements for both.
Here that the Kh-15A is not mentioned, thus that "Kh-15S" would be suggested on my end. And the launch latitude.
Yeah, I kinda was too lazy to post in both ;)

**Comment by nkocevar** [comment]
@PygmalionOfCyprus , I submitted an update request to change the 2 existing Kh-15's Max Speed and Propulsion, so for this issue #254 and issue #261 , it would be probably be best to address the existing Kh-15's change of speed & propulsion in issue #801 ***before*** copying the database entries to create the Kh-15S and Kh-15P...

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also did a general review of the Kh-15s. I think when they were originally added there was some confusion between the Kh-15 and the Kh-15A/S because the Kh-15s as currently (previously) present in the DB were set up as anti-ship missiles (only surface targets). They're now set up to engage land targets whereas the Kh-15A/S is set up to fire on surface targets, as it should.

I couldn't find any mention of a passive seeker on the Kh-15S or see one in diagrams, only on the Kh-15P; I only gave it an active seeker as a result. (The Kh-15P of course has its PRK-15.) If I missed something in one of your sources let me know.

Finally, added their loadouts to all the aircraft mentioned.

**Comment by claudejdev** [comment]
For clarification’ sake, and sorry that I didn't make it clearer before : yes, only the Kh-15P have a passive seeker.

**Comment by PygmalionOfCyprus** [comment]
OP also indicated a passive seeker on the Kh-15S, hence my double-check.

**Comment by nkocevar** [comment]
@PygmalionOfCyprus Thanks for taking care of this for me! I hadn't noticed until now. I'm not sure if this is the right way to link issues that are related to this same weapon, but I also submitted 3 loadout requests for this weapon, and will link them below for convenience...

1. Issue 287: #287
2. Issue 311: #311
3. Issue 314: #314

**Comment by nkocevar** [comment]
^^^Whoops! I guess I already linked them to this issue a while back. Sorry, didn't remember doing that :/ ...

**Comment by PygmalionOfCyprus** [comment]
Oof, I actually handled all those back when I first closed this issue but forgot to mark them closed. Whoops.

**Comment by nkocevar** [comment]
> Oof, I actually handled all those back when I first closed this issue but forgot to mark them closed. Whoops.

@PygmalionOfCyprus In that case you may need to re-check #287 because I just added the Tu-160M as a platform that was released in v493 to that page/form this morning, as the Tu-160M didn't exist in the DB when I initially opened that issue. Sorry...

**Comment by PygmalionOfCyprus** [comment]
One step ahead of you. Already added it to the 160M back when I handled the original tickets.

**Comment by nkocevar** [comment]
> One step ahead of you. Already added it to the 160M back when I handled the original tickets.

Sweet, thank you! You're the bomb.com...
