### ISSUE TITLE
Update/correction for Azarakhsh missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2540]
### DB Selector

DB3K

### Affected DBID(s)

Weapon/3941

### Summary of Changes

- Change the seeker into all-aspect IIR seeker. The seeker`s coverage might be around 180 degree based on the pic.
![image](https://user-images.githubusercontent.com/99646926/201456447-636ac803-d5a8-4095-98df-507292f89fed.png)
![image](https://user-images.githubusercontent.com/99646926/201456763-e1c11041-f2b3-4a59-b09d-4784348586bb.png)
![image](https://user-images.githubusercontent.com/99646926/201456897-c844157b-8d84-4644-99bb-1747d77d9033.png)
![image](https://user-images.githubusercontent.com/99646926/201457243-302bda01-0187-4371-93d2-20c1cc2a2c70.png)

- Change the missile`s dimension into as below
Length: 3.1 M
Diameter: 0.127 M
Weight: 70 KG
![image](https://user-images.githubusercontent.com/99646926/201456510-c3c84d04-e9cc-4a13-8ce7-c2e7a0661e84.png)

- Change the Guidance type into : .All-Aspect, High Off-Boresight midcourse plus Passive Infrared (IR) terminal guidance
![image](https://user-images.githubusercontent.com/99646926/201457336-d128968c-b8d3-45e0-913b-4502c395c47b.png)

- And also Change the properties into: Anti-Air Dogfight (High Off-Boresight), Capable vs Seaskimmer

### Sources

- https://twitter.com/imp_navigator/status/1560891011844509696?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1560891011844509696%7Ctwgr%5E9878a185ba0ede302e77ee41a8d90d51cb971c96%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fdefence.pk%2Fpdf%2Fthreads%2Firiaf-news-and-discussions.358559%2Fpage-540
- https://twitter.com/Pataramesh/status/1562192809201123328
- https://defence.pk/pdf/threads/iranian-aviation-products-military-and-civilian.735886/page-5#post-13920028
- https://iranpress.com/content/67561/azarakhsh-air-to-ground-missile

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
