### ISSUE TITLE
Add Algerian El Kasseh MCM

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2545]
### DB Selector

DB3K

### DBID to Copy

Finland #3012 Katanpaa

### Hypothetical

No

### Name

MCM, 501, El Kasseh

### Country

Algeria

### Service

Navy

### In Commission

2017 - present

### Number in Service

2 (third under contruction)

### Sensors

Radar: Furuno nav
EO: MSP-500
Sonar: SQS-12M

### Mounts

1x single 40mm/70 Bofors 315
2x single 12.7/90
Sea fox
Double Eagle Mk2
USV's

### Sources

1: https://www.navypedia.org/ships/algeria/alg_ms_el_kasseh_1.htm
2: https://www.navalnews.com/naval-news/2020/08/italian-shipyard-intermarine-delivers-2nd-el-kasseh-class-mcm-vessel-to-algeria

![1](https://user-images.githubusercontent.com/99532490/201493745-907b3d7d-b198-4c9e-a5c7-6756ca662327.jpg)
![2](https://user-images.githubusercontent.com/99532490/201493749-0dcf7e3e-6e47-42e3-a3db-97371f4b457b.jpg)
![3](https://user-images.githubusercontent.com/99532490/201493750-e49b33ed-9fa2-45bc-a188-9d7671e1c815.jpg)
![4](https://user-images.githubusercontent.com/99532490/201493752-95c67e08-bdfa-4019-8613-3f0ccb10296d.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
