### ISSUE TITLE
Add Surinam FPB-98 P201

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2547]
### DB Selector

DB3K

### DBID to Copy

Ship Ukraine #3603 (+3)

### Hypothetical

No

### Name

Patrol Craft (PC), P 201, -

### Country

Suriname

### Service

Coast Guard

### In Commission

2013 - present

### Number in Service

1

### Sensors

2x NA RADAR Fununo FAR 2117

### Mounts

1x 12.7mm/90 

### Other Changes

1x RHIB

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/suriname/sur_cf_p201.htm
3: https://www.meretmarine.com/fr/defense/ocea-un-patrouilleur-destine-au-suriname-charge-sur-un-cargo

![1](https://user-images.githubusercontent.com/99532490/201519011-d5ea3d5e-7f27-4145-86d0-bc95a96baa5b.jpg)
![2](https://user-images.githubusercontent.com/99532490/201519014-26ea227f-d91a-4209-a8e5-823dac232029.jpg)
![3](https://user-images.githubusercontent.com/99532490/201519018-24eb76ab-53ca-4bbe-96d1-99f482e40e95.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
