### ISSUE TITLE
11 Cells Mk41 VLS

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2548]
Offered on the Lockheed MCS under the Hellenic Future Frigate Program by Lockheed Martin. 
Provisions for CAMM(2783), CAMM-ER(4019), and other Mk41 compatiables. 

https://www.defensenews.com/digital-show-dailies/dsei/2021/09/16/lockheed-refines-bid-to-modernize-the-greek-frigate-fleet-heres-what-its-offering/
https://www.defensenews.com/naval/2022/03/17/lockheed-martin-making-final-push-for-greek-frigate-construction-modernization-work/
https://youtu.be/uIO8JvUX0rI?t=503

**Comment by PygmalionOfCyprus** [comment]
I'm not gonna add it yet, just 'cause there's no reason to add orphan mounts, but if the HN actually picks this up and this version of a VLS [is slated to] appears on a ship then OFC I'll add it as needed.

**Comment by HunterDNiu** [comment]
Well I think they've chosen the Franch FDI so this has no chance now. Thanks.

**Comment by PygmalionOfCyprus** [comment]
It'll probably pop up again eventually.

You can also request LM's offering as a hypothetical vessel and get the whole cannoli.

**Comment by HunterDNiu** [comment]
> It'll probably pop up again eventually.
> 
> 
> 
> You can also request LM's offering as a hypothetical vessel and get the whole cannoli.

I think it's similar to the Saudi LCS derived MMC. 
Also it was quite a competition. There were UK, Italy and Netherlands' offers.
