### ISSUE TITLE
Add Suriname FPB-72 Mk II

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2549]
### DB Selector

DB3K

### DBID to Copy

Nigeria #3604

### Hypothetical

No

### Name

Patrol Craft (PC), P101, -

### Country

Suriname

### Service

Coast Guard

### In Commission

2013 - present

### Number in Service

2

### Sensors

2x NA RADAR Furuno (1x Radome)

### Mounts

1x single 12.7mm/90

### Other Changes

1x Small RHIB with crane

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/suriname/sur_cf_p101.htm
3: https://www.naval-technology.com/projects/fpb-72-mkii-fast-patrol-boat
4: https://www.marinetraffic.com/nl/ais/details/ships/shipid:785188/mmsi:765690000/imo:0/vessel:P101

![1](https://user-images.githubusercontent.com/99532490/201528626-bbf02ab6-63f3-4acf-b2a6-6e60849eeec0.jpg)
![2](https://user-images.githubusercontent.com/99532490/201528628-1e0a8aac-3fa1-4e4c-a62e-da00eac08597.jpg)
![3](https://user-images.githubusercontent.com/99532490/201528629-b41ac240-5a0c-4a0e-bf1e-180b6828274c.jpg)
![4](https://user-images.githubusercontent.com/99532490/201528630-62b10fcd-2d17-4195-81d1-9c60110e95f5.jpg)
![5](https://user-images.githubusercontent.com/99532490/201528631-c47b5528-686f-4021-a990-66d7ac7e155d.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
