### ISSUE TITLE
Add Defensive Sensors and Chaff and Flare Dispenser to Z-20As

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2551]
### DB Selector

DB3K

### Affected DBID(s)

4720, 5434

### Summary of Changes

See picture. 
Add Generic MAWS, and Generic LWR
Add Generic Chaff and Flare Dispenser

### Sources

https://twitter.com/Defence_IDA/status/1591760175614267392
https://www.army-technology.com/projects/z-20-utility-helicopter/ (picture)
https://www.janes.com/defence-news/news-detail/more-details-emerge-about-chinas-z-20-helicopter

**Comment by bostonmyk** [comment]
https://www.sinodefenceforum.com/t/z-20.6294/page-156

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Also added to the other variants.
