### ISSUE TITLE
Export SU-30 Alamo loadout has 120 Amraams C-7s in it instead of R27ER1

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2557]
### DB Selector

DB3K

### Affected DBID(s)

Export SU-30s

### Description of Problem

Looks like the weapons record in the R27ER1 (Export Alamo C) was replaced with a mag entry.

**Comment by bostonmyk** [comment]
Guys the Indian Flankers are in the DLC so owners will that will see it at update.

**Comment by PygmalionOfCyprus** [comment]
Fixed. We're putting out a 497 hotfix, 497a.
