### ISSUE TITLE
Add Tunisia La Galite class (La Combattante IIIM)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2558]
### DB Selector

DB3K

### DBID to Copy

Ship Greece #930, Qatar #1048, en more

### Hypothetical

No

### Name

PCFG, P501, La Galite

### Country

Tunisia

### Service

Navy

### In Commission

1985

### Number in Service

3

### Sensors

RADAR: Triton-S, Castor IIB, unk NA radar
EO: 2x Naja EO/IR
ESM: DR2000

### Mounts

2x4 Exocet MM40
1x singel 76mm/62 Oto-melara compact
1x twin 40mm/70 Breda bofors compact 40
2x twin 30mm/75 GCM-A03
DR2000 ECM
Dagaie decot RL

### Other Changes

Reported in need of refit but no evidence found of a refit.

### Sources

1: JFS 2015/2016
2: https://www.navypedia.org/ships/tunisia/tun_cf_la_galite.htm
3: https://www.hazegray.org/worldnav/africa/tunisia.htm

![1](https://user-images.githubusercontent.com/99532490/201955630-734f64a7-90db-42da-9f21-bba050a4c660.jpg)
![2](https://user-images.githubusercontent.com/99532490/201955647-3abd1e37-3d5e-4f54-8c1b-960c8383c186.jpg)
![3](https://user-images.githubusercontent.com/99532490/201955656-400b4966-8530-44ff-931d-530f7dadff34.jpg)
![4](https://user-images.githubusercontent.com/99532490/201955659-156e2f86-7b2f-47ac-a04e-3d3d731f165b.jpg)
![5](https://user-images.githubusercontent.com/99532490/201955663-3aa79a5f-d72c-45bd-8a38-7a7a3599e482.jpg)
![6](https://user-images.githubusercontent.com/99532490/201955664-6e347c07-5a97-4a22-a7cf-388d3096318f.jpg)
![7](https://user-images.githubusercontent.com/99532490/201955670-a6811411-4014-4533-a20c-f1f7814204ee.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
