### ISSUE TITLE
Add Tunisia Hamilcar class (Type 143B)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2559]
### DB Selector

DB3K

### DBID to Copy

Ship Germany #568, Ghana #3669, and more

### Hypothetical

No

### Name

PCF, P505, Hamilcar

### Country

Tunisia

### Service

Navy

### In Commission

2005 - present (Tunisia)

### Number in Service

5 of 6 (1 is stricken)

### Sensors

RADAR: SMA3RM, WM27
EO: OGR-713
ESM: Cutlass 

### Mounts

2x2 Exocet canisters are empty
2x single 76mm/62 Oto-Melara Compact
2x single 12.7mm/90 MG
2x 533 TT (SST4)
2x Hot Dog/Silver Dog docoy RL

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/tunisia/tun_cf_hamilcar.htm
3: https://www.seaforces.org/marint/German-Navy/Patrol-Vessel/Type-143-Albatros-class.htm

![1](https://user-images.githubusercontent.com/99532490/201961994-873b282a-500e-47ee-ae28-f948d90afd6b.jpg)
![2](https://user-images.githubusercontent.com/99532490/201962001-fed4e35c-afbe-4a36-b5d5-77c89362a56e.jpg)
![3](https://user-images.githubusercontent.com/99532490/201962006-9cee3adc-503f-49e2-9902-08e1ff3ca4f2.jpg)
![4](https://user-images.githubusercontent.com/99532490/201962009-544873fc-b445-445a-8023-812e8bf8eb81.jpg)
![5](https://user-images.githubusercontent.com/99532490/201962022-9bc57369-3be3-4b75-aa78-26018507a6d0.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
