### ISSUE TITLE
Add CBU-105 Loadouts to Saudi F-15SA 4884 2780

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#256]
### DB Selector

DB3K

### User(s)

 4884,2780

### Weapons Carried

Same as CB-103 loadout

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Saudi's used CBU-105 in Yemen in 2015. It looks like a CBU/87 loadout was added but was likely meant to be CBU-105. First text picture of the F-15SA carrying 10. Sipri says the weapons were procured in 2014-2015.The two videos are definitely CBU-105, as you can see the parachute deployed munitions and casings. CBU-103's don't have parachutes but dump like normal cluster bombs. Update #4884, #2780 load-outs.

### Sources

https://www.dsca.mil/press-media/major-arms-sales/saudi-arabia-f-15sa-aircraft
https://www.youtube.com/watch?v=ThUB1R6Tpkw
https://www.rt.com/news/255233-saudi-yemen-cluster-bombs/
https://en.wikipedia.org/wiki/CBU-97_Sensor_Fuzed_Weapon
https://armstrade.sipri.org/armstrade/page/trade_register.php

**Comment by PygmalionOfCyprus** [comment]
Agree the CBU/87 was probably a mistake or an erroneous copy-over. I've modified those loadouts to represent the CBU-105, killing two birds with one stone for 495.
