### ISSUE TITLE
Add Tunisia Joumhouria class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2562]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat, P202, Joumhouria

### Class

Joumhouria (P270)

### Country

Tunisia

### Service

Navy

### In Commission

2012 - present

### Number in Service

6

### Length (m)

27.3

### Beam (m)

6.7

### Draft (m)

not found

### Standard Displacement (t)

Not Found

### Full Displacement (t)

80

### Complement

14

### Primary Propulsion Type

Diesel

### Propulsion

3x MTU 12V400 M84, 3x waterjets

### Flank Speed (kt)

38

### Range (nm) at Speed (kt)

1400 @ 15

### Sensors

1x generic NA radar

### Mounts

1x single 20mm/70 mk10

### Ship Codes

All Aluminum Construction

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/tunisia/tun_cf_joumhouria.htm
3: https://www.analisidifesa.it/2014/08/la-tunisia-riceve-in-dono-altri-pattugliatori-italiani

![1](https://user-images.githubusercontent.com/99532490/202022446-4413eb84-d5df-4d90-85cf-f1ef3b892c3a.jpg)

**Comment by Jkryos** [comment]
Added DB3K 498.
