### ISSUE TITLE
Update RCS for Shahed-136 (new info on RAM design)

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2563]
### DB Selector

DB3K

### Affected DBID(s)

entry #2214

### Summary of Changes

New evidence shows RAM of the honeycomb multilayer metasurface type from wreckage of downed/destroyed shahed-136 drones. This RAM is hypothesized to significantly reduce radar signature against higher frequency radars especially but also lower frequency ones.
Up to 10 dbsm reduction for low and high radar bands. One twitter user claimed up to 20 dbsm reduction with honeycomb RAM, but that is unlikely since such a reduction is used in the much more advanced 5th gen f-35. So at maximum an appropriate guess would be 10 db reduction. So I wouldn't take the 20 figure as solid until there is enough evidence to support it. 
IMPORTANT NOTE: consider how none of the Shahed-136 have been show down with S-300PS/PT/PM systems which have very capable anti-stealth radars especially against cruise missiles. So this shows that the RCS of these drones must be much smaller than 0.06 and 0.01m2 for low/high bands respectively. Nor have the recently upgraded Pechora SA-3 been able to shoot them down. Meaning these drones have a very reduced X-band radar profile and reduced even against low band radars. **_HOWEVER, some have been downed by autocannons, so that means low band surveillance radars must have spotted them and guided AAA units towards the drones location. Most likely 36D6 Tin Shield, P-18, P-40. Meaning it's really stealthy primarily against FCR frequency bands and even low bands, but not stealthy enough to evade low band detection entirely._**
![honeycomb1](https://user-images.githubusercontent.com/108960393/202119233-4823a0b7-1370-42ac-876e-c58b2d627fe7.png)

Currently the RCS of the drone alone (EXCLUDING ANY RAM) is listed as follows based off 3D plots and advanced computer software from twitter user @FlankerChan
RCS front (A-D bands) - 0.0631m2 / -13  dBsm RCS side:    -10 dBsm    RCS  rear:   -13 dBsm
RCS front (E-M bands) - 0.009m2 /   -21  dBsm RCS side:    -17 dBsm   RCS rear:     -21 dBsm

**Changes to be made:**
_(UPDATED RCS W/ HONEYCOMB RAM)
RCS front (A-D bands) - 0.005m2 /   -23 dBsm    RCS Side   -20 dBsm     RCS Rear:     -23 dBsm
RCS front (E-M bands) - 0.0008m2 / -31 dBsm    RCS Side   -27 dBsm       RCS Rear:   -31 dBsm_

This is based off academic papers which demonstrate through electromagnetic research lab tests effects of honeycomb and metasurface against varying radar bands, usually reducing anywhere from up to 8-12 dBsm for x bands and 4-8 dBsm for VHF-S bands. Taking averages for each band segments (A-D/E-M) I rounded up to 10dbsm reduction for each. Which would make some sense considering the difficulties the highly capable S-300 tombstone and 76L6 clamshell radars are having acquiring these targets. It is still possible the RCS is closer to -35 or even -40 dBsm for x bands. But not enough proof for that yet to corroborate honeycomb having those larger reductions.

### Sources

https://twitter.com/Pataramesh/status/1571147829812531200
https://twitter.com/Pataramesh/status/1572221429965525000
https://twitter.com/Flankerchan/status/1572046756657135616

**Comment by PygmalionOfCyprus** [comment]
Bumped it up to "Heavy Shaping," which might make it a little _too_ stealthy, but the next highest level was too low.
