### ISSUE TITLE
Avenger Air Defense Systems - Ukraine

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2565]
### DB Selector

DB3K

### DBID to Copy

facility 286

### Hypothetical

No

### Name

SAM Sec (Avenger) (2x pr Plt)

### Country

Ukraine

### Service

Army

### In Commission

2022-

### Number in Service

4x systems initially

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.thedrive.com/the-war-zone/avenger-air-defense-systems-headed-to-ukraine?fbclid=IwAR0axamQONT4LW1c2w9RN9oRx17ivdQXYDEcsK_leO5FJLBwjxGb9Me4NEY
https://gagadget.com/en/186533-the-united-states-will-transfer-to-ukraine-the-antwq-1-avenger-surface-to-air-missile-systems-with-stinger-missiles-to-de/
https://www.wionews.com/world/us-announces-400-million-security-assistance-to-ukraine-sums-total-aid-over-186-billion-533076
https://militaryleak.com/2022/11/12/us-defense-department-supplies-ukraine-with-hawk-and-avenger-air-defense-systems/
https://www.washingtonpost.com/national-security/2022/11/10/ukraine-avenger-air-defenses/
https://www.defense.gov/News/News-Stories/Article/Article/3216745/400-million-security-package-headed-to-ukraine/

![image](https://user-images.githubusercontent.com/99599482/202297261-aee314f1-c428-4dc9-8235-ad935e28d8f6.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
