### ISSUE TITLE
Italy - KC-46

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2567]
### DB Selector

DB3K

### DBID to Copy

aircraft 3687

### Hypothetical

No

### Name

KC-46A Pegasus (KC-767B)

### Country

Italy

### Service

Air Force

### In Commission

2026/2027

### Number in Service

6x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://theaviationist.com/2022/11/03/italy-will-buy-six-kc-46-tankers/?fbclid=IwAR2D6EUwR3QdwjRH7mEooSxCkGLMGiSlLgSGU3kFq4Wdz61maxDAGcI8Aek

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
