### ISSUE TITLE
Spain - NSM for F101 and F110 frigates from 2030.

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2568]
### DB Selector

DB3K

### Affected DBID(s)

ships 827, 3014, 3864

### Summary of Changes

Spain Selects Naval Strike Missile As Harpoon Replacement

According to the Spanish Navy, the Naval Strike Missiles will be fitting on two classes of ships:

The F-100 Álvaro de Bazán-class frigates following their mid-life update
The future F-110 frigates

Regarding deliveries, the Spanish Navy explained that “We expect to receive the [new] missile well in advance [before] the Harpoon missile is retired from the active service around 2030”.

### Sources

https://www.navalnews.com/naval-news/2022/09/spain-selects-naval-strike-missile-as-harpoon-replacement/?fbclid=IwAR04p2m9O9ISqpIQssS-b7iwegXlFamW4zHwj5BmR_RG9UyB7Sz79OyCk7M

**Comment by PygmalionOfCyprus** [comment]
We actually already caught this in an internal news roundup. You'll notice the F110 already has them. As for the F101s, I'll C/P what I posted in the private GH just for reference:

>Holding off on F-100 because I have no idea when the MLU will be and there will presumably be other upgrades/changes between now and then. It's better to wait until the MLU is actually announced IMO.

**Comment by tbrandon517** [comment]
Makes sense for the F100s. I'm behind so I didn't know the F110 was updated.
