### ISSUE TITLE
UAV Hermes 900 seems to have incorrect fuel consumption

### ISSUE THREAD

**Issue by K1l0tangoDef3nce** [PygmalionOfCyprus/cmo-db-requests#2569]
### DB Selector

DB3K

### Affected DBID(s)

2576

### Description of Problem

Fuel consumption is abnormal during cruise speed which gives "very short legs" for the uav while its endurance is up to 36 hours.
Moreover there is an extremely low fuel consumption when is in military speed
https://elbitsystems.com/product/hermes-900/
![image](https://user-images.githubusercontent.com/99611473/202495421-b547e604-306d-4c34-977c-83a40c98634d.png)

### Recommended Fix

Perhaps there should be an adjustment in the various fuel consumptions

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
