### ISSUE TITLE
RCN Protecteur-class (Joint Support Ship) x2 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#257]
### DB Selector

DB3K

### Baseline

#1698

### Hypothetical

No

### Name

AOR 520 HMCS Protecteur

### Class

Protecteur-class (Joint Support Ship)

### Country

Canada

### Service

Royal Canadian Navy

### In Commission

2023-

### Length (m)

173.7

### Beam (m)

24

### Draft (m)

7.4

### Standard Displacement (t)

20240

### Full Displacement (t)

20240

### Complement

239

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

2 × MAN 12V32/44CR propulsion engines, 1 × bow thruster, 4 × MAN diesel generators

### Fuel Capacity (kg)

7600 Diesel, 490 Aviation

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

10,895kn @15kn

### Sensors

- 1x Mk1 Eyeball
- 1x Saab Sea Giraffe AMB
- 2x Pathfinder DT Mk2 Navigation Radar
- 2x Rattler OECM & DECM ??
- 1x Sirius ??
- 1x HF/DF ??

### Mounts

- 2 x Phalanx CIWS BLK 1B CIWS
- 4 x .50 calibre RWS
- 1x Nixie Torpedo Decoy
- 4x MASS

### Aircraft & Docking Facilities

- 2x Davits (0-11m)
- 1x Hangar (2x Medium Aircraft)
- 1x Pad (1x Medium Aircraft)

### Comms/Datalinks

- HF Radio [Secure]
- VHF Radio [Secure]
- UHF Radio [Secure]

### Ship Codes

Onboard Degaussing Gear (Magnetometer)

### Sources

https://www.canada.ca/en/department-national-defence/services/procurement/joint-support-ship.html
http://www.navy-marine.forces.gc.ca/en/fleet-units/jss-home.page
![Seaspan_lays_Keel_for_Royal_Canadian_Navys_First_Joint_Support_Ship_HMCS_Protecteur_925_001](https://user-images.githubusercontent.com/99632305/154612595-6a4971f3-38b2-4f4f-aa00-d5b198641893.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
