### ISSUE TITLE
Mirage III based recce aircraft - Camera numbers

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2571]
### DB Selector

Both

### Affected DBID(s)

Aircraft: DB3k 4500, 3770, 682; CWDB 41, 1094, 655, 3598

### Summary of Changes

Currently all of these aircraft have a single reconnaissance camera. Up to five cameras could be fitted, one in the chisel nose and a number looking sideways or vertically behind it. The transparencies for these cameras can be seen in many images, including the photo below. 'Up to five' sounds suspiciously like 'not 5' to me, the Revell Mirage IIIR kit has four cameras included and the Mirage 5 recce variants have four cameras in what looks like much the same nose, so I'm saying:

4x Generic Visual Reconnaissance Camera

### Sources

http://www.airvectors.net/avmir3_1.html#m3
https://www.britmodeller.com/forums/index.php?/topic/235046901-dassault-mirage-iiierdo-132/

![image](https://user-images.githubusercontent.com/109925704/202818693-e6b0adc2-5caf-4b3e-bbdc-014302e5a583.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
