### ISSUE TITLE
Mirage IIIRZ for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2572]
### DB Selector

CWDB

### DBID to Copy

CWDB 41, or other

### Hypothetical

No

### Name

Mirage IIIRZ

### Country

South Africa

### Service

Air Force

### In Commission

1967-1990

### Number in Service

4x

### Sensors

Note #2571

### Loadout Options

![P1010819](https://user-images.githubusercontent.com/109925704/203648953-43b0d14a-88c9-4cdd-9bb9-689e48c541de.jpg)
This datasheet indicates that the RZs were qualified for AAMs, so I would suggest both an unarmed recce loadout like other Mirage IIIRs and an armed one with R.550 Magic/V3A/V3B in accordance with date of introduction, which requires three different aircraft. Not to worry though, I'm still chasing the countermeasures.

### Other Changes

I feel sure that these aircraft were fitted with countermeasures in later life like the rest of the SAAF's Mirage fleet, but I can't prove anything right now.

### Sources

https://www.saairforce.co.za/the-airforce/aircraft/143/mirage-iiirz
http://www.mirage4fs.com/slides15.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
