### ISSUE TITLE
Mirage IIIR2Z for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2573]
### DB Selector

CWDB

### DBID to Copy

CWDB 41, or other

### Hypothetical

No

### Name

Mirage IIIR2Z

### Country

South Africa

### Service

Air Force

### In Commission

1974-1990

### Number in Service

4x

### Sensors

Note #2571 

### Other Changes

R2Z aircraft were fitted with the SNECMA Atar 9K-50 engine used on the Mirage 50 and Mirage F.1. Both databases have this engine on a Mirage III airframe in the CWDB 1999/DB3k 1819 Mirage 50FC, so you can just use that. At the moment there are no performance differences, saairforce.co.za claims the R2Z variant was the fastest Mirage III in the SAAF but doesn't say by how much or at what height or anything useful like that.

### Sources

https://www.saairforce.co.za/the-airforce/aircraft/50/mirage-iiir2z
http://www.mirage4fs.com/slides15.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
