### ISSUE TITLE
Update/correction for F-14A Tomcat [F-14AM] -- Iran (Air Force), 2012

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2574]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft/1312

### Summary of Changes

- Change the cockpit from "Steam Gauge" to "Glass Cockpit".
![image](https://user-images.githubusercontent.com/99646926/202835268-de32c125-82a9-4459-92e9-7358582d2abb.png)
![image](https://user-images.githubusercontent.com/99646926/202835163-4b038705-8e75-4a1b-8af7-45ebbfdb97d1.png)

- Replaced existing RWR and DECM with Generic DECM(Sensor/825) and Generic RWR(Sensor/2919) 
![image](https://user-images.githubusercontent.com/99646926/202835708-2a9633fb-e495-40c0-abfe-5d978847fd6a.png)

- Add upgraded AN/AWG-9. The radar were said to be digitalized version and it also have ground search capability as well(which original AN/AWG-9 doesn`t have) while retains the capability to guide the existing missiles, Including Fakour-90(Weapon/2784). Kinda comparable to AN/APG-71(Sensor/5201). Late 1990 or Early 2000 generation is possible.
![image](https://user-images.githubusercontent.com/99646926/202835396-1c2473e9-bac8-45bf-a6bf-98ab58880407.png)
![image](https://user-images.githubusercontent.com/99646926/202835439-fda9df07-9f5a-4fa2-86f8-79778e95c6db.png)

- Add Mk82, Mk83 and Mk84 loadout, should be similar(in both weapon`s quantity and range) as Bombcat(Aircraft/417)
![image](https://user-images.githubusercontent.com/99646926/202835939-fcf2ff58-1596-4ed2-9130-548064127045.png)

-Add "Bombsight - Ballistic Computing" into aircraft`s properties.

### Sources

- https://www.facebook.com/Scramblemagazine/posts/crash-in-iranone-of-the-few-remaining-islamic-republic-of-iran-air-force-iriaf-f/2795353507157832/
- https://theaviationgeekclub.com/iriaf-upgraded-f-14-tomcat/
- https://defence.pk/pdf/threads/persian-bombcats-on-the-way-f-14-upgrade-program.360799/
- https://theboresight.blogspot.com/2015/08/iran-satellites-and-tomcats.html
- https://www.uskowioniran.com/2014/02/iriaf-exhibitions-isfahanshahid-babaie.html
- https://medium.com/war-is-boring/in-the-1980s-iran-outfitted-f-14s-as-heavy-bombers-c9f05be6e6a0

**Comment by capcop98** [comment]
And apparently F-14AM were also probably equipped with Fatter missile (basically Azarakhsh with 40km range)

![image](https://user-images.githubusercontent.com/99646926/202843576-0100dd02-1242-499e-8ca8-41b214884d94.png)

https://forum.dcs.world/topic/187459-iranian-f-14a-am-a-a-loadout/
https://en.wikipedia.org/wiki/Fatter

**Comment by capcop98** [comment]
Below is the spec of Fatter missile:
![image](https://user-images.githubusercontent.com/99646926/202863931-82b98408-c3a7-4108-b01d-88aef476eeaf.png)
Length: 2.7 M
Diameter: 0.127 M
Weight: 88 KG
Seeker: All-Aspect Imaging Infrared (IIR)
Range: 40 KM (21 NM)

https://defence.pk/pdf/threads/iranian-aviation-products-military-and-civilian.735886/page-5#post-13920028

**Comment by capcop98** [comment]
Apparently, the aircraft were seen with anti-ship missile too. Based on the size, its probably Nasr-1(Weapon/2390)
![image](https://user-images.githubusercontent.com/99646926/203032565-1b75f9ec-ffbb-4f4e-9055-6e99faeb1368.png)
![image](https://user-images.githubusercontent.com/99646926/203032682-55888d24-d6a2-42d7-9d12-7df227c1a09d.png)

Ghader`s loadout is also possible
![image](https://user-images.githubusercontent.com/99646926/203034193-1e6b74b2-eb73-448b-9d08-997ad3540eca.png)

Source:
- https://www.youtube.com/shorts/rvCKTMgmVkg
- https://airrecognition.com/index.php/archive-world-worldwide-news-air-force-aviation-aerospace-air-military-defence-industry/global-defense-security-news/global-news-2016/february/2382-iranian-air-force-receives-overhauled-mig-29-fighter-jet-and-new-nasr-missiles.html
- https://www.tasnimnews.com/en/news/2013/10/01/155374/iran-to-equip-f-14-fighters-with-home-made-missiles/amp

**Comment by tbrandon517** [comment]
> Updated DB3K 498. I have held off on the ASM loadouts until we know a little more.

Probably not much chance now.
