### ISSUE TITLE
Update/correction for F-4E Phantom II (Iran - Air Force), 2015

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2575]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft/3896

### Summary of Changes

- Change the name to "F-4E Phantom II [Upgraded, Project Dowran]". Apparently this 2015 model is the one upgraded under Dowran Project.
![image](https://user-images.githubusercontent.com/99646926/202836767-5d6934ab-7032-47c9-9577-cf7c702a7021.png)

- Replace existing radar with Bayyenat-I (Iranian Copy of JL-10A with 150km search range). Probably have illumination capability to guide AIM-7E2 and Fakour-90 too.
![image](https://user-images.githubusercontent.com/99646926/200165491-8a20dee4-349c-4c71-972f-13e9883ebb1c.png)
![image](https://user-images.githubusercontent.com/99646926/200165511-7046f66d-6170-4464-8f67-1cc2a3107ea5.png)

- Add below loadouts:

  1. Ghader loadout(Day/Night All-Weather.):
  Range: 400 nm (similar to C-801 loadout)
2x Ghader(Weapon/2408)
2x AIM-7E2(Weapon/181)
2x 370 USG drop tank
1x 600 USG drop tank
![image](https://user-images.githubusercontent.com/99646926/200165864-cd3cb26f-08d5-4a5d-9f1d-507202107204.png)

  3. Fakour-90(Hypothetical)(Day/Night All-Weather.):
  Range: 450 nm (based on AGM-78`s loadout) 
2x Fakour-90(Weapon/2784)
2x AIM-7E2(Weapon/181)
2x 370 USG drop tank
1x 600 USG drop tank
(Sources and references at the comment section)

   5. Yasin loadout(Day/Night All-Weather):
      Range: 325 nm(Similar to KGGB`s loadout from Aircraft/5954).
       4x Yasin PGM(Weapon/4120)
       2x AIM-7E2(Weapon/181)
       1x AN/ALQ-101 DECM
       2x 370 USG drop tank
       1x 600 USG drop tank

     
 ![image](https://user-images.githubusercontent.com/99646926/202837225-2467f973-d7f7-4aa5-b0d8-4db85a3f9c66.png)     

- Change the cockpit from "Steam Gauge" to "Glass Cockpit[Partial]"
![image](https://user-images.githubusercontent.com/99646926/200165915-14943484-3b5d-4ee2-94dc-a25812176160.png)

       

### Sources

- https://www.sinodefenceforum.com/t/china-helping-iran-to-upgrade-f-4-phantoms.6568/page-3
- https://www.airliners.net/photo/Iran-Air-Force/McDonnell-Douglas-F-4E-Dowran/2476813
- https://www.globalsecurity.org/military/world/iran/yasin.htm
- https://defence.pk/pdf/threads/iriaf-news-and-discussions.358559/page-509
- https://defence.pk/pdf/threads/iriaf-news-and-discussions.358559/page-549#post-13956281

**Comment by capcop98** [comment]
Replaced PL-12 loadout with Fakour-90 since the Iran doesn`t have access to PL-12 so far as source indicates. But were said the aircraft can possibly carry and fire Fakour-90.

Regarding PL-12:
![image](https://user-images.githubusercontent.com/99646926/203035661-66d2d429-2289-4806-bf45-2636452f4392.png)

Regarding Fakour-90:
![image](https://user-images.githubusercontent.com/99646926/203036036-ecc82cfe-0d35-450e-bffa-dccee6b8ac4d.png)
![image](https://user-images.githubusercontent.com/99646926/203035889-05cddff9-eaff-44dc-bc93-34e33f0a4f5a.png)

Source:
- https://defence.pk/pdf/threads/irans-new-fighter-jets-ready-for-export-who-might-buy.736182/page-5
- https://defence.pk/pdf/threads/iriaf-news-and-discussions.358559/page-549#post-13956281

**Comment by Jkryos** [comment]
Updated DB3K 498.
