### ISSUE TITLE
Add Aim-120 2-way datalink to USAF MQ-9A Blk5 Reaper so Aim-9x2 loadout works

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2576]
### DB Selector

DB3K

### Affected DBID(s)

5595

### Summary of Changes

Please add the Aim-120 2 way datalink. Sidewinder X2 can't fire wihout it.

Be interested to see if the USAF adds AAW radar or MAW type sensors. Optical sensor on bottom really limits the arcs.

### Sources

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=390272

**Comment by FrangibleCover** [comment]
Does the MQ-9 have such a datalink? An alternative solution if it doesn't would be a copy of the AIM-9X-2 without the datalink capability.

**Comment by bostonmyk** [comment]
Probably not and it is not likely the AIM-120 unless it can be guided from another platform (F-35).

**Comment by PygmalionOfCyprus** [comment]
Added the DL as a quick-fix. IIRC the AIM-9X-2 actually _can_ be guided from another platform, but don't quote me on that. Obviously data on the DL capabilities are a little lacking these days, hence the placeholder.
