### ISSUE TITLE
RCAF MAISR King Air 350ER x3

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#258]
### DB Selector

DB3K

### Baseline

#3221

### Hypothetical

No

### Name

MAISR King Air 350ER (not named by Canada yet)

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2020-

### Length (m)

14.2

### Wingspan (m)

17.7

### Height (m)

4.37

### Empty Weight (kg)

4321

### Maximum Takeoff Weight (MTOW) (kg)

7430

### Payload Weight (kg)

2530

### Crew

3

### Propulsion

2x PT6A-60A

### Rate of Climb (ft/min)

1990/5970

### Service Ceiling (ft)

35000

### Military/Afterburner Speed (kt)

300

### Cruise Speed (kt)

280

### Supercruise

No

### Ferry Range (nm)

1765

### Takeoff / Landing Distance (m)

901-1400

### Fuel Capacity (kg)

1640

### Sensors

- 1x L-3 Wescam’s MX-15D electro-optic/infrared (EO/IR) imager
- 1x Northrop Grumman’s AN/AAR-47B(V)2 missile and laser warning system
- 1x L-3 Communications Systems - West’s Vortex transceiver
- 1x Raytheon’s AN/APX-119 IFF transponder
- 1x Rockwell Collins AN/ARC-210 transceiver
- 1x KGV-135A communications security module
- 1x Mk1 Eyeball
- 1x AN/APY-8 Lynx
- 1x AN/AAS-52 MTS Laser Designator

### Mounts

1- 1x BAE Systems/Extant Aerospace AN/ALE-47 countermeasures dispenser system

### Loadout Options

- Ferry
- Maintenance
- Reserve
- ISR

Same as MC-12W

### Comms/Datalinks

- UHF/VHF [Unsecure]
- HF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Sources

https://www.dsca.mil/press-media/major-arms-sales/canada-king-air-350er-isr-aircraft-manned-airborne-intelligence
https://www.tpsgc-pwgsc.gc.ca/app-acq/amd-dp/air/snac-nfps/renseignement-airborne-eng.html
https://skiesmag.com/news/canada-gets-green-light-to-buy-king-air-surveillance-aircraft/
![CMAISR_Illustration1220x684_0](https://user-images.githubusercontent.com/99632305/154617221-d93763a3-8445-45a8-9002-c259c6585ce6.jpg)

**Comment by PygmalionOfCyprus** [comment]
Just to save you the time and trouble on future entries: since this is technically a "copy" of something already in the DB (i.e., the King Air 350ER) you can file a "Copy Entry" request instead and just supply the sensor/mount/loadout info.

**Comment by cdnice55** [comment]
Thanks, still getting used to the different forms. Loving the new system by the way.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by PygmalionOfCyprus** [comment]
Hopefully getting better all the time; I just added the "Copy Entry" form an hour or so ago!

Anyway, we're tracking your Canadian requests. You've probably noticed I'm grouping them all in a milestone. Once you've submitted everything you want in this "group," let us know in a comment on the final issue; we'll swoop in and handle them all in one big blob.

**Comment by cdnice55** [comment]
I saw that tag added, thanks! I am just working through what was submitted under the old threads on the forum and have a few others that I never submitted. I will let you know once they are all done, probably by Sunday night.

Have a great day,

dl

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cdnice55** [comment]
Hi Ethan,

So, I think I am done for now. I am going to look into aircraft/helicopters for the CWDB but that will take some time to confirm details so will post those later. Let me know if you have any questions and if you need any help at all.

Thanks,

Dale

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Jkryos** [comment]
Added DB3K 494.
