### ISSUE TITLE
USN & USMC F/A-18A (1994 / 1999) Sparrow Missile Correction

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#2582]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1118,1119,2320,2321

### Summary of Changes

USN & USMC F/A-18A [Aircraft ID 1118, 1119, 2320, 2321]

- Aircraft Loadouts ID 1621, 1623 needs to correct the Sparrow with TALD or ITALD loadouts from AIM-7M to AIM-7P.

### Sources

DB3K database

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
