### ISSUE TITLE
Sea Venom [FASGW(H) /ANL] missing two-way datalink

### ISSUE THREAD

**Issue by Anon9944** [PygmalionOfCyprus/cmo-db-requests#2583]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3158

### Summary of Changes

The current Sea Venom missile is missing a two-way datalink which would enable the helicopter launching it to maximise its range compared to its current range which is limited by its onboard IIR seeker

### Sources

https://www.mbda-systems.com/product/sea-venom-anl/

**Comment by Jkryos** [comment]
Updated DB3K 498.
