### ISSUE TITLE
EC-46D, ECM trainer

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2586]
### DB Selector

CWDB

### DBID to Copy

Request of https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2585

### Hypothetical

Yes

### Name

EC-46D

### Country

Japan

### Service

JASDF

### In Commission

1964 - 1978

### Number in Service

3x

### Sensors

J/ALQ-1 :OECM with unknown details, early 1960's tech  (could use Generic OECM, Sensor ID 1176 as reference)

### Other Changes

Loadout
---
intstead of cargo missions, Standoff ECM Training mission could added

### Sources

https://ja.wikipedia.org/wiki/C-46_(%E8%88%AA%E7%A9%BA%E6%A9%9F)

https://aobamil.sakura.ne.jp/mil-dic/J.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
