### ISSUE TITLE
612 Badr of Saudi Arabia Navy incorrect MK141 launchers

### ISSUE THREAD

**Issue by Sputnikod** [PygmalionOfCyprus/cmo-db-requests#2588]
### DB Selector

DB3K

### Affected DBID(s)

ship/323

### Summary of Changes

In all pictures i found in internet have 2 Mk141 launchers with 4 Harpoons per mount.

But in DB have 2 launchers but only 2 missiles pero mount

### Sources

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Saudi_Arabian_missile_corvette_Tabuk_%28618%29_underway_during_Operation_Desert_Shield.jpg/1280px-Saudi_Arabian_missile_corvette_Tabuk_%28618%29_underway_during_Operation_Desert_Shield.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
