### ISSUE TITLE
Correction: 96L6 Radar is C-Band, not S-Band

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#2589]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 3204, 5054, 6904

### Summary of Changes

96L6, including S-500 and export variants, is a IEEE C-band (NATO G/H-band) radar. 

As of DB3K_497a, the operating bands (search & track) came up as NATO E-band, which corresponds to IEEE's lower half of the S-band. This is where the mistake is.

![96L6Error](https://user-images.githubusercontent.com/99858862/203571530-1998e102-f36e-4d05-905e-a7e85b10556e.png)

According to GlobalSecurity.org, the wavelength is listed as "centimetric," which checks out with the wavelength of NATO G/H-bands (IEEE C-band) of ~3.7 to 7.5cm. Which is safe to rule out the E-band (2-3 GHz), which is at least ~10 cm and longer (decimeter band). Unfortunately I'm unable to get an exact detail on whether the radar's bandwidth extended across both G and H bands or just one of it.

Worse yet, while trying to verify the information, I can't access official Russian sources at least since the conflict started (cyberattack probably has something to do with it), so the only sources I have are secondary sources that cited it. I'll list the URL in the sources section so that anyone that can access it can verify it.

### Sources

[Missile Threats CSIS Missile Defense Project](https://missilethreat.csis.org/defsys/s-500-prometheus/) --- Page last updated: July 1, 2021

> The system features four radar vehicles per battery, including the 91N6E(M) S-band acquisition radar, **96L6-TsP C-band acquisition radar,** 76T6 multi-mode engagement radar, and 77T6 anti-ballistic missile engagement radar.[9](https://missilethreat.csis.org/defsys/s-500-prometheus/#easy-footnote-bottom-9-1916) This radar complex reportedly allows the S-500 to detect ballistic and airborne targets at up to 2,000 and 800 km, respectively.[10](https://missilethreat.csis.org/defsys/s-500-prometheus/#easy-footnote-bottom-10-1916)

---------------------------------------------------------------------------------------------------------------------------------------------

[GlobalSecurity.org](https://www.globalsecurity.org/military/world/russia/96l6.htm) --- Page last modified: 28-07-2019 18:55:50 ZULU

> **Specifications**
> Band | C band
> Wavelength | Centimetric
---------------------------------------------------------------------------------------------------------------------------------------------

[Missilery.info](https://en.missilery.info/missile/c300pmu2/96l6e) --- Page indexed by Google in May 2020

> **Tactical and technical characteristics**
> Radiation frequency range | "C"
---------------------------------------------------------------------------------------------------------------------------------------------

**Official Source I Can't Access**

[Almaz-Antey Corporation Official Site](https://www.almaz-antey.ru/catalogue/millitary_catalogue/53/281/648)

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Thanks for fighting with the sources!

**Comment by sr71xx** [comment]
@SolomonDread @PygmalionOfCyprus  

The original E band was correct
According to the DoD radar bands allocation, the military classifies the 96l6 as S-band. The Russian brochures say "C" which translates in Cryllic to S band centimetric (2-4 GHz), hence the confusion with NATO C band (UHF).
Based off the antenna dimensions of 4.5m and brochure reported 1.5deg beamwidth, the frequency is calculated to be ~3.113GHz, roughly F band, so E/F NATO is most accurate to reflect the frequencies depending on verticlal and horizontal beamwidth and corresponding vertical/horizontal antenna dimensions, from the frequency/antenna equations
main source https://x.com/Flankerchan/status/1868522684449251775

will elaborate and show more evidence in a future ticket. @Flankerchan on X.com explains it very well
