### ISSUE TITLE
RCAF F/A-18A/B Hornet [CF-188A/B] 2010

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#259]
### DB Selector

DB3K

### Affected DBID(s)

#4510, 4511

### Summary of Changes

Upgrade the current ALR-67 V2 to ALR-67V3.
-------CF-18's from the previous life extension program should have the ALR-67 V2 instead of V1 unit (#4510 and #4511)

### Sources

http://dgpaapp.forces.gc.ca/en/defence-capabilities-blueprint/project-details.asp?id=1770

**Comment by PygmalionOfCyprus** [comment]
Added 494. Changed the 2010 versions to have the (V)2 and added a 2020 version with the (V)3 before the 2023 version (which already had it).
