### ISSUE TITLE
UK Royal Navy FFG DDG Hypothetical RB15 equipped replace with real NSM surface warfare missile. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2592]
### DB Selector

DB3K

### Affected DBID(s)

DB3K 3199 FFG T.23 3200 DDG T.45 which both have RB15M

### Summary of Changes

NSM has been selected for Royal Navy, as a Harpoon replacement, presumably like for like with 8 on the Type 23 45 etc. Doesn't elaborate on wether this is to be the interim weapon pending something faster. 
Replace RB15  hypothetical fit with "real" NSM in DB3K Type 23 and Type 45 entries DBID 3199 3200

### Sources

UK MOD https://twitter.com/DefenceHQ/status/1595443079326179331?t=Ppm2AQCX1LliSV7ooT6Zyg&s=19
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/november/12521-uk-royal-navy-to-purchase-naval-strike-missile-produced-by-kongsberg.html

**Comment by PygmalionOfCyprus** [comment]
Handled 498.
