### ISSUE TITLE
Italy - PD.808GE2 update (wip)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#2599]
### DB Selector

DB3K

### Affected DBID(s)

1267

### Summary of Changes

In commission: 

sensors:
1x ARIES-A [ECM] (ELT/ALQ-1,2,3,4,5)
1x ARIES-A [ELINT] (ELT/RMB-6M, ELT-113/213, ELT-777)
1x FAST JAM [COMJAM & COMINT] (VHF/UHF, ARIES-A suite)

mounts:
chaff dispenser (24 cartriges), visible in second picture

### Sources

http://www.loneflyer.com/2021/03/18/velivoli-da-guerra-elettronica-italiani/

The PD.808GE2 has a black cover over the rear ECM transmitting antenna:
![PD 808GE2](https://user-images.githubusercontent.com/104227721/204040698-cfd3f303-2289-4bbb-83ff-5dcd0bdd0585.jpg)
![PD808GE2](https://user-images.githubusercontent.com/104227721/204040701-357e043c-d989-4633-8bc7-5b91e19e1e2d.jpg)
![PD 808GE2](https://user-images.githubusercontent.com/104227721/204040949-2a7a6f66-dcd1-4b80-a320-4b42d9d780ca.jpg)

**Comment by Jkryos** [comment]
Updated DB3K 498.
