### ISSUE TITLE
Flat Face Radars can't see contacts likely due to Mast Height

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#26]
### DB Selector

DB3K

### Affected DBID(s)

All Flat Face Radars

### Description of Problem

Load scenario and observe from Red side. You have 4 Flat Face Radars and a SA-6. A B-52 and A-6 approach and are never detected by the flat faces. You'll eventually get a side aspect visual detection from the SA-6 much farther away. Test is at 36K but I've dropped down to medium/low and same results. They do eventually spot visual contacts.
[FlatFace.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8051246/FlatFace.zip)
t

### Recommended Fix

Add Mast Height. I think

**Comment by PygmalionOfCyprus** [comment]
I can't reproduce this: I'm having absolutely no trouble detecting targets with the P-18 provided said targets are within its target altitude, which is <20000ft. In the scenario you gave me, the aircraft don't actually descend to altitude until they're quite close, which probably accounts for the behavior you describe. If you teleport them out of range, let them get to altitude, and then have them enter the radar's search zone, there's no issue.

**Comment by bostonmyk** [comment]
You're absolutely and I'm a dolt. Sorry about that!

**Comment by PygmalionOfCyprus** [comment]
Happens to the best of us!
