### ISSUE TITLE
RCAF F/A-18A/B Hornet [CF-188A/B] HEP 2 x36

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#260]
### DB Selector

DB3K

### DBID to Copy

4510 and 4511 DB3000

### Hypothetical

No

### Name

F/A-18A Hornet [CF-188A] HEP 2

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2023-

### Sensors

- 1x APG-79(V)4 Active Electronically Scanned Array (AESA) replaces AN/APG-73
- 1x AN/ALR-67 (V)3 replaces AN/ALR-67(V)1

### Mounts

- 1x ADM-141C Improved Tactical Air-Launched Decoys replaces AN/ALE-47

### Loadout Options

- Sidewinder AIM-9X Block II air-to-air short-range missile
- AIM-120D advanced medium range air-to-air missile
- AGM-154 Joint Standoff Weapon (JSOW)

### Sources

https://skiesmag.com/news/major-upgrades-canada-fleet-cf-188-hornets/
https://www.canada.ca/en/department-national-defence/services/procurement/fighter-jets/hornet-extension-project.html
https://www.canadiandefencereview.com/Featured_content?blog/183
https://www.thedrive.com/the-war-zone/34139/canada-is-looking-to-give-its-cf-18-hornets-new-radars-aim-9x-sidewinders-and-more
http://dgpaapp.forces.gc.ca/en/defence-capabilities-blueprint/project-details.asp?id=1770

**Comment by tbrandon517** [comment]
Additional Source

https://www.thedrive.com/the-war-zone/42501/its-official-canadas-cf-18-hornet-fighters-are-set-to-get-new-advanced-radars

**Comment by Jkryos** [comment]
Added DB3K 494. Also corrected Canadian service tags to reflect their royal status.
