### ISSUE TITLE
Japan, HSS-2/A CWDB

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2607]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft CWDB 2354 2373 2856  2355 2855

### Summary of Changes

Rename/Commission year & comment (Dipping sonar, torpedo, etc...)
----
HSS-2 (1963) → No Change (AN/AQS-10)
HSS-2 (1967) → HSS-2 (1965?, AN/AQS-13)
HSS-2 (1974-1987) → No Change (AN/AQS-10, Type 73)
HSS-2A (1967) → HSS-2 (1974 - 1987, AQS-13, Type 73) 
HSS-2A (1974 - 1991) →No Change (Engine upgrade, HPS-101 Radar)

So there are two type of HSS-2, and one type for HSS-2A.
HSS-2 with AQS-10 from 1963 and AQS-13 dipping sonar from 1965?(detail unknown). I assume both got Type 73 in early 1970 while Type 73 is modified version of Mk44. 

Sensor
----
**Dipping sonar**
as I commented,
AQS-10 for 1963 and one of 1974-1987 version.
AQS-13 for 1965? and one of 1974-1987 version of HSS-2. as well as HSS-2A

**Radar**
AN/APN-130, for HSS-2
J/HPS-101,  for HSS-2A (Navigation Radar with unknown detail, likely modified APN-130)

### Sources

https://ja.wikipedia.org/wiki/%E4%B8%89%E8%8F%B1-%E3%82%B7%E3%82%B3%E3%83%AB%E3%82%B9%E3%82%AD%E3%83%BC_S-61

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
