### ISSUE TITLE
Update/correction for Malaysia`s AW-139

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2609]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft/5571

### Summary of Changes

- Add Generic IR(Sensor/5771), Generic Weather radar(Sensor/863) and RDR-1700(Sensor/6528) to the aircraft.
![image](https://user-images.githubusercontent.com/99646926/204118392-936513dd-1c03-481c-abd9-b057fe5095bd.png)
![image](https://user-images.githubusercontent.com/99646926/204118582-4bb0e2c9-68a2-4fd4-8255-99859df330cc.png)
![image](https://user-images.githubusercontent.com/99646926/204118665-5b1b2193-f960-4254-809b-308aa7f61b0f.png)

- Add right-facing 12.7mm Machinegun(Mount/2281)
![image](https://user-images.githubusercontent.com/99646926/204118408-4d194195-5a94-459a-b986-b913a4239755.png)

-  Add AW-139 for Malaysia Coast Guard. The sensor suite is probably similar as Royal Malaysia Navy version, except the RDR-1700 (it did not have the bulging nose like the RMN`s version)
![image](https://user-images.githubusercontent.com/99646926/204118456-4db4c0b4-5c21-415a-a744-ce386e402d9a.png)
![image](https://user-images.githubusercontent.com/99646926/204118761-e3f44b00-a02c-4e40-b9be-67fe0bde2db9.png)

- Add SAR loadout for both aircraft
![image](https://user-images.githubusercontent.com/99646926/204118511-8a4fe218-103f-43df-929e-6eb26e13c86f.png)
![image](https://user-images.githubusercontent.com/99646926/204118531-73baf16f-4b14-41ca-ac18-ed9be0bedfb6.png)

- Add Maritime surveillance only to Aircraft/5571
![image](https://user-images.githubusercontent.com/99646926/204118833-8268cb16-e92d-4538-b536-7276859bdf0d.png)

### Sources

- https://www.helis.com/database/news/aw139_mmea/
- https://helicoptermaintenancemagazine.com/article/avionics-system-epic-proportions
- https://www.msn.com/en-my/news/national/navy-needs-more-copters/ar-AA14AWjX?ocid=msedgntp&cvid=e9b00dc559f34c67be781b40fa380304
- https://ms-my.facebook.com/maritimmalaysia/photos/a.503049696453617/4205087076249842/
- https://www.malaysiandefence.com/third-aw139-moh-delivered/

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Do you know how many are in service with the Coast Guard specifically, and when they entered service? I have 4x leased by the AF late 2021 (effectively 2022), 3x to the Navy in 2022, but can't find anything on the CG even though the pictures obviously show those aircraft in their service.

**Comment by capcop98** [comment]
Sorry for the late reply (been busy for the whole week). As per some sources, the Coast Guard have around 3 units of AW-139 (M72-01 until M72-03) currently.

Source:
- https://verticalmag.com/news/the-malaysian-maritime-enforcement-agency-takes-delivery-of-its-first-aw139-helicopter-html/
- https://www.helis.com/database/modelorg/Maritim-Malaysia-AW139/
