### ISSUE TITLE
Please consider adding KH-15P (ARM) to available in-game weapons...

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#261]
### DB Selector

DB3K

### Hypothetical

No

### Name

KH-15P

### Length (m)

4.78

### Width/Span (m)

0.92

### Diameter (m)

0.455

### Weight (kg)

1200

### Range (nm)

80

### Target Altitude / Depth (ft)

0 AGL

### Launch Altitude / Depth (ft)

1000 Ft. AGL - 65000 Ft. ASL

### Warhead

150 Kg SAP

### Targets

Radar

### CEP (m)

4

### Sensors

1x Passive Radar Seeker (•80nm Range•) + (•Arcs: PB1, PB2, SB1, SB2•) >>> "• •" = Suggested

### Weapon Codes

ARM Target Memory, Bearing-Only Launch (BOL), Level Cruise Flight

### Comments

--Maximum Speed: 3300 Knots
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

--Cruise/Max Altitude: 130,000 Ft.
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

-Propulsion: SRM-160 solid fuel rocket engine
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

--Launch Platforms:
-Tu-22M-3 (DBID's: 1669, 1670, 1671, 2438, & 2456)
-Tu-22M-3M (DBID's: 2837 & 4951)
-Tu-95MS/MSM (DBID's: 62, 447, 520, 773 & 1611)
-Tu-160 (DBID's: 280, 357, 408, & 1465)
https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

### Sources

1. (https://www.glrobalsecurity.org/military/world/russia/as-16.htm)
2. (https://www.globalsecurity.org/military/world/russia/as-16-specs.htm)
3. (https://military-history.fandom.com/wiki/Kh-15)
4. (http://astronautix.com/k/kh-15s.html)
5. (https://web.archive.org/web/20140806154247/http://www.ktrv.ru/about/structure/458/459/)
6. https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

**Comment by nkocevar** [comment]
@PygmalionOfCyprus , I submitted an update request to change the 2 existing Kh-15's Max Speed and Propulsion, so for this issue #261 and issue #254 , it would be probably be best to address the existing Kh-15's change of speed & propulsion in issue #801 ***before*** copying the database entries to create the Kh-15S and Kh-15P...

**Comment by PygmalionOfCyprus** [comment]
Added 494 w/ #254
