### ISSUE TITLE
Correct A/C Hanger (1 x Large Aircraft) Area size

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#2610]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3413

### Summary of Changes

Facility #3413 A/C Hanger (1 x Large Aircraft) is very large size (4800m2) compared to Facility #41 A/C Hanger (2 x Large Aircraft).

A/C Hanger (2 x Large Aircraft) has 1800m2 area, I think A/C Hanger (1 x Large Aircraft) is change half of that.

### Sources

DB3K database

**Comment by PygmalionOfCyprus** [comment]
Hangar sizes are all kinda weird and genericized it seems, so I brought the size down to match.
