### ISSUE TITLE
Ground Based Interceptors

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2612]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 1197, 3143, 3144

### Summary of Changes

The GBI target altitude is restricted to ~1000km, this renders it unusable for anti-ICBM engagements even when provided with accurate target data. This is also inconvincible given that the delta-v the motors combined have at least more than 4000m/s delta-v. 
The GBI often launches while the target is over Canada, and after reaching cruise altitude, exhibit high pitch angles without ascending/descending and low(~2000kt) ground speed. 
May also want to remove the minimum range considering that GBI is known to be able to do a burn-burn-release two-stage mode. 

### Sources

https://en.wikipedia.org/wiki/Ground-Based_Interceptor
https://www.nasaspaceflight.com/2013/06/orbital-pegasus-launch-iris-spacecraft/
https://www.northropgrumman.com/wp-content/uploads/Orion-Motor-Series.pdf
https://boeing.mediaroom.com/news-releases-statements?item=130917

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
