### ISSUE TITLE
SkySat C2, C5 and C12

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2614]
### DB Selector

DB3K

### Affected DBID(s)

Sat 111

### Summary of Changes

It appears these three has identical position in the current db. 
SkySat C2: 
2016-058D 
2016-09-16
1 41773U 16058D   22331.70831203  .00008451  00000-0  22256-3 0  9995
2 41773  97.1003  32.3758 0002554 128.5656 231.5819 15.38764747346072
SkySat C5: 
2016-058C
2016-09-16
1 41772U 16058C   22331.90991104  .00004890  00000-0  18018-3 0  9997
2 41772  97.2452  31.0284 0001547  85.4446 274.6970 15.28273630344720
SkySat C12:
2018-099AR
2018-12-03
1 43797U 18099AR  22331.68464165  .00008888  00000-0  23323-3 0  9996
2 43797  97.1077  33.7069 0001330  80.7102 279.4294 15.38862918222572

### Sources

www.space-track.org

**Comment by PygmalionOfCyprus** [comment]
Handled 498. Thanks for the TLEs!

**Comment by HunterDNiu** [comment]
I‘m curious, how do you usually track the launch/reentry of mil sats and their capabilities in the db? Like some are quite old/wrong/had new ones in the series?

Niu

On Dec 2, 2022, at 3:05 PM, Ethan Hermanson ***@***.***> wrote:

﻿

Handled 498. Thanks for the TLEs!

**Comment by HunterDNiu** [comment]
(Dang it why email reply is so messy.)
I mean, changing sats one by one in the order of battle is painful...
