### ISSUE TITLE
Ground Launched Small Diameter Bomb (GLSDB)

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2617]
### DB Selector

DB3K

### Baseline

Weapon 773, 484, 2855

### Hypothetical

No

### Name

Ground Launched Small Diameter Bomb

### Length (m)

5.8

### Width/Span (m)

0.46

### Diameter (m)

0.23

### Weight (kg)

With SDB: 440, with SDB-II: 400

### Range (nm)

0-80

### Warhead

1x SDB or 1x SDB-II

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Radar, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### Sensors

Sensors on the warheads. 

### Weapon Codes

Bearing-Only Launch (BOL), Ballistic Missile or Rocket Booster, Weapon - INS w/ GNSS Navigation, Uses GPS, Level Cruise Flight

### Comments

This issue represents 2 weapons. One has the SDB as the payload and the other SDB-II. 
The GLSDB combines the motor of the Mk26 rocket(Weapon 773) and the _separating_ SDB or SDB-II. 

These may help model the flight profile: 
"After the motor launches it to a high enough altitude and speed, the [SDB's] wings will deploy and glide the bomb to its target." 
"While typical MLRS systems follow a ballistic trajectory, the rocket-launched SDB can be launched to altitude and glide on a selected trajectory."
"[The GLSDB can f]lying around terrain to hit targets on the back of mountains, or circling back around to a target behind the launch vehicle. "

This may require tweaks on the SDB/SDB-II themselves, as there being evidence of "weapon datalink allows post-launch tracking and control", "weapon datalink _network_ to provide in-flight target updates"(https://www.dote.osd.mil/Portals/97/pub/reports/FY2020/af/2020sdbii.pdf?ver=LH1GttQNyuH6VW4W-cUJoA%3D%3D). 

Launchers capable of launching MLRS(M270, HIMARS) shall be capable of launching this. 
Dimensions and weights placeholder, as they are calculated based on the data of Mk26 and SDB. 

### Sources

https://boeing.mediaroom.com/2015-03-10-Boeing-Saab-Adapt-Air-Launched-Small-Bomb-for-Ground-Launch
https://en.wikipedia.org/wiki/GBU-39_Small_Diameter_Bomb#Ground_Launched_Small_Diameter_Bomb_(GLSDB)

**Comment by bostonmyk** [comment]
Vid

Boost up and glide down. So can probably design like CMO BM with the SDB as the Mirv. Step-2 harder. How do you get them to boost up in one direction and glide down in another to hit reverse slope targets and things like that? If the model isn't available yet, just a rocket-launched SDB is probably fine. SAAB,, Boeing and Norwegian Subcontractors and this system is really good for mountain terrain so guessing at least Sweden and Norway will buy as well unless they don't work.

https://www.youtube.com/watch?v=kkkfE5yHejc

The Drive

https://www.thedrive.com/the-war-zone/ground-launched-small-diameter-bomb-would-double-ukraines-precision-strike-range
"The GLSDB has a range of around 94 miles, or 150 kilometers,"

Jane's
https://www.janes.com/defence-news/news-detail/saab-expects-first-contract-soon-for-new-glsdb-artillery-weapon
"The GLSDB combines an M26 ground-based rocket motor from the Multiple Launch Rocket System (MLRS) with Boeing's air-launched GBU-39B SDB. It has a range of 150 km (93 mile), can attack both stationary and moving targets, and can be “ground-launched from a wide variety of launchers and configurations”, according to Saab."

SAAB Site
https://www.saab.com/products/ground-launched-small-diameter-bomb-glsdb

Boeing Sheet for Korea

https://www.boeing.co.kr/resources/ko_KR/Seoul-International/2015/GLSDB.pdf

Stats

Dimensions – GLSDB All-Up Round
 Length: 154 in.
 Diameter: 9.5 in
 Weight: 600 lbs.
Dimensions – SDB
 Size: 71 in. (L) x 7.75 in. (H) x 7.5 in. (W)
 Weight: 285 lbs.
 Wingspan: 63.3 in. (open), 7.5 in. (stowed)
Airframe – SDB
 Warhead: Penetrating blast fragmentation
 Weight: 205 lbs.
 Explosive Fill: 36 lbs. Insensitive Munition Certified
 Fuze: Integrated Electronic Safe/Arm Fuze System Impact and Delayed Settings
with Height of Burst Sensor
Guidance Set:
 Inertial Navigation System (INS)/Global Positioning System
 Anti-jam and Selective Availability Anti-Spoofing Module
 Advanced Core Processor Two Module

Reuters Business Section
https://www.reuters.com/business/aerospace-defense/100-mile-strike-weapon-weighed-ukraine-arms-makers-wrestle-with-demand-sources-2022-11-28/

**Comment by HunterDNiu** [comment]
https://www.thedrive.com/the-war-zone/ukraine-situation-report-kyiv-officially-getting-long-range-rocket-boosted-bomb

**Comment by PygmalionOfCyprus** [comment]
Was added...500? IIRC?

**Comment by HunterDNiu** [comment]
Please deem this as a correction. The current weapon has a confusing range(only the boost phase was accounted for) and doesn’t have datalink(with SDB II).

**Comment by PygmalionOfCyprus** [comment]
This is a slightly larger issue since we need a way to get the weapon to "detach" mid-flight. Will look into it. Also, Ukraine doesn't have the SDB-II ver. so removing from the milestone.
