### ISSUE TITLE
Addition: QR-SAM (India)

### ISSUE THREAD

**Issue by KJohnston11** [PygmalionOfCyprus/cmo-db-requests#2618]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Plt (QRSAM)

### Facility Type

SAM

### Country

India

### Service

Army

### In Commission

2023

### Number in Service

N/A

### Crew

N/A

### Dispersion Radius (m)

10

### Sensors

Active Array Battery Surveillance Radar (360 degree FOV, 4 arrays)

Active Array Battery Multifunction Radar (360 degree FOV, 4 arrays)

### Mounts

3x QRSAM TEL

1x QRSAM Radar Vehicle

### Magazines

6x QRSAM per TEL, no reloads

### Aircraft & Docking Facilities

N/A

### Sources

https://twitter.com/defencedecode/status/1368952058489933826

https://missilethreat.csis.org/india-completes-surface-to-air-missile-trials/

https://en.wikipedia.org/wiki/QRSAM

https://www.defenceview.in/qr-sam-indian-new-generation-air-defence-cover-for-tanks/

**Comment by bostonmyk** [comment]
Here's a scan of DRDO stats on radars. Seems reasonable. 4 BMSR array which #3655 has. Should be x band. Then the BSR on the top).
![QR-SAM BMFR](https://user-images.githubusercontent.com/7115648/204839810-ba8068b9-9e8b-40cd-bd0b-b0231864ebe9.jpg)

**Comment by bostonmyk** [comment]
Hmm. Looks like radar at top not the bsr and never mounted. An EOTS turret is in its place in more modern pictures. Each system has 4 panels.

https://twitter.com/living4hind/status/1132870910162214913/photo/1
https://twitter.com/DefenceDecode/status/1327300978115104770/photo/1

DRDO seems to have better info Both are BEL. There is a EOTS turret (makes sense as they can only be angled so far).
https://www.drdo.gov.in/labs-establishment/technologies/electronics-radar-development-establishment-lrde

I think adding the second radar and EOTS turret is fine.

**Comment by Jkryos** [comment]
Added DB3K 505.
