### ISSUE TITLE
RCN SSK Victoria Class Submarine 2022

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#262]
### DB Selector

DB3K

### DBID to Copy

165 DB3k

### Hypothetical

No

### Name

876 HMCS Cornerbrook

### Country

Canada

### Service

Royal Canadian Navy

### In Commission

2022-

### Sensors

* BQQ-10 Sonar Suite----- (same as Virginia class)----- replaces 2040

### Mounts

* Mk48 7AT torpedoes----- replaces Mk48 4M torpedoes

### Other Changes

* L3 Calzoni Universal Modular Mast (UMM)
----- (same as Virginia class)
----- allows high-speed, highly-secure, jam-resistant satellite communications with shore (please add applicable comms)

### Sources

https://www.lookoutnewspaper.com/canadas-modern-submarine-returns-water/
http://www.navy-marine.forces.gc.ca/en/news-operations/news-view.page?doc=game-changing-mast-installation-underway-for-submarines/jq71ub2

![COR-Load-Out-HR-2](https://user-images.githubusercontent.com/99632305/154716785-29ecf2ad-cd66-48a7-852f-ba3864e8b65f.jpg)
2

**Comment by Jkryos** [comment]
Added DB3K 494.
