### ISSUE TITLE
Hilda Tigercat for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2622]
### DB Selector

CWDB

### DBID to Copy

Both, DB3k Facility 12

### Hypothetical

No

### Name

SAM Plt/2 Hilda (Tigercat)

### Country

South Africa

### Service

Air Force

### In Commission

1974-1993

### Number in Service

54x fire units

### Other Changes

The source implies that 'the system' consists of a single launcher controlled by the director. This seems like a somewhat odd way to operate, but I think the system should have only one Tigercat Triple launcher. Also, while you're in there, Triple is misspelled.

### Sources

https://www.saairforce.co.za/the-airforce/weapons/88/hilda-tigercat-sam

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
