### ISSUE TITLE
Correction to G5 towed howitzer

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2623]
### DB Selector

DB3K

### Affected DBID(s)

Facility 822

### Summary of Changes

The G5 howitzer is listed as self-propelled, but it is a towed system. The G6 (DB3k 821) is its towed sibling.

### Sources

https://en.wikipedia.org/wiki/G5_howitzer

**Comment by Jkryos** [comment]
Updated DB3K 498.
