### ISSUE TITLE
Please change name of weapon #1058 Vikhr to correct GRAU index 9M127 which refers to Vikhr-1 and amend range. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#263]
### DB Selector

DB3K

### Affected DBID(s)

#1058 - AT-16 Scallion [9K121 Vikhr]

### Summary of Changes

**#1058 - AT-16 Scallion [9K121 Vikhr] - The overall system is known as the 9K121 but the correct GRAU index for the missile itself is actually 9M127 for the first version intoduced in very limited numbers in the 1990's.**

There is a difference between the first Vikhr and the Vikhr-M in terms of range and the bulk of production is of the later version. The DB entry has 5.4nm miles which is reasonably accurate for the Vikhr-M model at 10-12km were as the first Vikhr version had in fact a range of 8km or 4.3nm. 

This is a throw back to the fact that the Vikhr actually entered only limited trials service in the 1990's and it was then dropped when the KA-50 Hokum A was abandoned in the economic fall out at the end of the Soviet Union for being too costly. 
Production quantities started to be manufactured only after orders were placed in 2013 for the Vikhr-M. 
The Hokum B KA-52 had to adopt the AT-9 as an expedience because the Vikhr production was in stasis. 

“The 9K121M "Vikhr-M" missile system with the 9M127-1 "Vikhr-1" missile was developed at the end of the eighties at the Tula Instrument Design Bureau (KBP), was officially adopted in 1992, but mass production began only in 2013. when a contract was signed for the production of missiles in the amount of 13 billion rubles. Rearmament to a new missile system was carried out in the period from 2013 to 2015.”

This greatly confuses the indexing of load outs which inaccurately refer to 
#15679 AT-16 Scallion [9M120 Vikhr-M], S-8KO 80mm Rockets (BAI/CAS)
#15670 AT-16 Scallion [9M120 Vikhr-M], S-8KO 80mm Rockets (BAI/CAS)

Update weapon to reflect correct index and amend linked load outs please. 

### Sources

https://en.topwar.ru/183270-prishlas-po-nravu-egiptjanam-zarubezhnaja-pressa-o-zakaze-rossijskoj-ptur-vihr-1.html
https://en.topwar.ru/185232-protivotankovuju-aviacionnuju-raketu-vihr-adaptirujut-k-vertoletam-mi-28nje-i-mi-35p.html
https://bs.atomiyme.com/vihor-raketa-protivoklopna-raketni-sistem/
https://muzruno.ru/biznes/126218-vihrushka-raketa-sistema-za-protivoraketna-raketa.html
https://tr.topwar.ru/186157-udary-po-slabym-mestam-bronetehniki-izlishni-ispanskij-obozrevatel-o-rossijskoj-rakete-vihr-1.html
https://youtu.be/DobAdQEaBmY

**Comment by Jkryos** [comment]
Loadouts corrected, name and ranges fixed DB3K 493.

**Comment by KLABDB3K** [comment]
That is brilliany thank you, appreciated.

**Comment by KLABDB3K** [comment]
There is a typo in DB493, Sorry 🙏 It should be 9M127 not 9K127.
The Russian system index precursor is 9K the missile or munition precursor is 9M.
