### ISSUE TITLE
South Korea Navy Type 214 request

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#2631]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 420, 669

### Summary of Changes

ROK Navy purchased torpedoes during the 1990s SUT and is also used for Type 214 SUT heavy torpedo is a wire guided torpedo, so you need to add Torpedo wire to Type 214 datalink

### Sources

https://en.wikipedia.org/wiki/SUT_torpedo

https://www.naval-technology.com/projects/type_212/

**Comment by PygmalionOfCyprus** [comment]
Can you clarify the source where you see that the SUT is used on the Type 214s? I can only find reference to the White Sharks being used onboard those subs; seems like only the KSS-1s used the SUTs.
