### ISSUE TITLE
Add B-21 Raider (specs subject to change) HYPOTETHICAL

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2634]
### DB Selector

DB3K

### DBID to Copy

5450

### Hypothetical

Yes

### Name

B-21 Raider

### Country

United States

### Service

Air Force

### In Commission

2027

### Number in Service

1 prototype

### Sensors

please bear with me (these are just guesses based on previous 5th gen) for all we know it can use new radars/sensors. But these are good starts for now I believe. Basically combining all the advanced radar/elint/comint/sigint/oecm/decm systems of 5th gen together to form 1 major new 6th gen system

1x AN/APG-77v1 AESA LPI radar (400km range/anti-air/surface search)
1x AN/ASQ-239 Barracuda (ELINT) 500nm range
1x COMINT 500nm range similar to AN/USQ-113v3
1x OECM mid band jammer (A-D bands) similar to AN/ALQ-249 NGJ
1x OECM high band jammer (E-M bands) using an/apg-77v1 FCR
1x DECM (E, F, G, H, I, J bands) similar to AN/ALQ-214v2
1x COMMUNICATIONS JAMMER (HF,VHF,UHF) AN/USQ-113v3
1x DAS AN/AAQ-EEQ-37 EO MAWS 5nm
1x AN/AAQ-37 EO-DAS (>60nm) longer range than f35
1x AN/AAQ-40 EOTS IRST 100nm
1x DIRCM
1x Generic FLIR, 4th gen 100km
1x Generic TV cam 4th gen 100km

RCSS - Active Cancellation
IRSS - Peak Temp Reduction (Cool-Air-Mix)

*Increase the service ceiling to 60/65kft.
SDB/SDB-II loadout, 4x the number of 500lb JDAMs.
Distributed aperture system, longer range than F-35's.*

### Loadout Options

keep all loadouts from B-2 the same for now but reduce quantity by half since B-21 carries half as much payload capacity at 30,00lbs as opposed to the B-2 at 60,000lbs

add JASSM-XR loadout

add hypersonic weapons loadout

reduce specific loadout quantity by half

### Other Changes

Sixth generation, improved stealth, combining long range radar detection, long range ELINT/SIGINT, multi-band Electronic Warfare, Comms Jamming/Monitoring, hypersonic weapons carrying ability
Type: Bomber | Crew: 2
Min Speed: 280 kt | Max Speed: 540 kt
Wingspan: 46m | Height: 5.33m
Length: 17.16m | Max Payload: 14,000 kg
Empty Weight (25% smaller than B-2): 53755 kg | Max Weight: 127950 kg
Operator: Air Force | Commissioned: 2027
Propulsion: 2x F-135-PW-100

RADAR SIGNATURE: compared to B-2 it is improved by ten fold against high frequency/fire control radars and LO against VHF/UHF. We can infer a RCS of 0.00001m2 (-50 dBsm) for E-M bands and 0.001m2 for A-D bands (-30 dBsm)
(A-D bands) front -35 dBsm    side: -30 dBsm   rear: -35 dBsm
(E-M bands) front: -50 dBsm  side: -45 dBsm   rear: -50 dBsm

IR/VISUAL SIGNATURE: remain the same for now

Sixth gen B-21 will have long range powerful FCR, long range ELINT/SIGINT/COMINT monitors, all band spectrum OECM electronic warfare ability, all band spectrum DECM, DIRCM, chaff/flares, COMS jamming ability, command node, and possibly a DAS similar to the F-35

I understand this is very hypothetical

### Sources

https://en.wikipedia.org/wiki/Northrop_Grumman_B-21_Raider
https://twitter.com/Pataramesh/status/1598987498210099200
https://twitter.com/ForumStrategic/status/1598947091824664576
https://twitter.com/USAS_WW1/status/1598794554156752897
https://www.wsj.com/articles/u-s-unwraps-b-21-bomber-designed-to-deter-china-11669983794
https://abcnews.go.com/Politics/new-21-stealth-bomber-unveiled/story?id=94353024

**Comment by HunterDNiu** [comment]
Is this serious? I would have a lot to say if these can get accepted.

**Comment by tbrandon517** [comment]
> Is this serious? I would have a lot to say if these can get accepted.

Why? There are plenty of Hypothetical units and the DB can be updated as new data seeps into the public domain.
The Su-75 Checkmate is already in the DB and at least the B-21 is a real thing.

**Comment by FrangibleCover** [comment]
The correct amount of effort to be focused on hypothetical platforms is up to the devs, but I think given that the B-21 will enter USAF service, adding a quasi-hypothetical placeholder for now isn't a bad idea. Future DB updates can clarify the features and capabilities as we get more information on the B-21 and eventually this entry will become the B-21 IOC entry when it enters service.

That being said I am data gathering for the Atlas Carver right now, so if you want to write hypotheticals for systems that almost definitely wouldn't have entered service I, for one, will not stand in the way.

**Comment by 5th-Domain** [comment]
Should probably have Properties the same as the B-2A Spirit Blk 30 as well.

**Comment by TheBagelInhaler** [comment]
> Should probably have Properties the same as the B-2A Spirit Blk 30 as well.
> 
> Link from Matrix Forum with some figures for the plane.
> 
> https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=1525

well said. Sensors can always be updated. But it no doubt has long range ELINT/SIGINT capability like the B-2 and F-35, multiple band jamming (both offensive/defensive ecm), and comint monitoring/jamming (very probable)
apart from that it is a generation and possibly ten fold better stealth against targeting radars (that's where the -50 dBsm figure comes from) and very good LO against VHF (-30 dBsm) approx
however as for weapons and loadouts I'm not too sure, similar to B-2 blk 30 for now

**Comment by TheBagelInhaler** [comment]
to keep it simple, I've left out other properties that B-21 has including controlling drones, changing radar signature to other crafts (advanced EW techniques) and others.

**Comment by 5th-Domain** [comment]
I was thinking of these properties from the B-2A for now which are as follows:

- Terrain Avoidance (Land: 300ft [91.4m], Sea: 100ft [30.5m])
- Fly-by-Wire
- Night Navigation/Attack (Incl. Bomb, Rocket Delivery)
- Bombsight - Advanced Navigation (INS/GPS)
- Boom Refueling
- RCSS - Exposed Fan Blocker(s)
-  IRSS - Heavily Masked/Slit-Shaped Exhaust

Additional to this probably the following:

- RCSS - Active Cancellation
- IRSS - Peak Temp Reduction (Cool-Air-Mix)

**Comment by HunterDNiu** [comment]
Ok three points:
1. Increase the service ceiling to 60/65kft. 
2. SDB/SDB-II loadout, 4x the number of 500lb JDAMs. 
3. Distributed aperture system, longer range than F-35's.

**Comment by Jkryos** [comment]
It goes without saying we are all guessing in the dark here on most of these details. We have added the B-21 with details we at the DB Team have collected along with some of the info in this thread we agree with. Thanks everyone for the input. Added DB3K 498.
