### ISSUE TITLE
RCAF CP-140M Aurora [P-3C Orion] BLK IV x14

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#264]
### DB Selector

DB3K

### DBID to Copy

4355 DB3K

### Hypothetical

No

### Name

CP-140M Aurora [P-3C Orion] BLK IV

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2022

### Sensors
ADD:
*AN/ARC-511 and AN/ARC-513 very high frequency (VHF) radios, used for line of sight air traffic management and marine communications
*AN/ARC-210 and AN/ARC-234 very and ultra high frequency (V/UHF) radios, used for line of sight data communications and two-way radio communication
*ARC-512 high frequency (HF) radios and Link-11 tactical data Link, used to transmit, relay and receive long range tactical data and communication

Data management system that integrates information and displays it from the following sensors:

*MX-20 electro-optics/infrared sensor package that allows day and night visual surveillance at extended ranges
*AN/ALQ-507 electronic support measures (ESM) system, used to identify and locate sources of radio frequency emission

### Sources

https://www.navalnews.com/naval-news/2020/02/canadas-cp-140-aurora-mpa-upgraded-to-block-iv-takes-first-flight/
https://www.canada.ca/en/department-national-defence/services/procurement/cp-140-aurora.html
https://skiesmag.com/news/upgraded-block-iv-aurora-flight-testing/

![20200221AEA0004D010-768x420](https://user-images.githubusercontent.com/99632305/154718484-68aba197-4a1d-40d6-9f56-0240ccba1a44.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
