### ISSUE TITLE
Hero 120 twirling at waypoint

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2640]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3953

### Description of Problem

If you  fire a Hero 120 a waypoint will be added short of target and it'll twirl. Hero 420 and Shahed seem to work fine.

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=390867&p=5059291#p5059291

**Comment by Jkryos** [comment]
Should be fixed.
