### ISSUE TITLE
Add Ukrainian Army  SAM Bn (SA-3b Goa [S-125SC Neva-SC] WZT-1 Tracked TEL Upgrade 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2642]
### DB Selector

DB3K

### DBID to Copy

Facility 2606

### Hypothetical

Yes

### Name

 SAM Bn (SA-3b Goa [S-125SC Neva-SC] WZT-1 Tracked TEL Upgrade

### Country

Ukraine

### Service

Army

### In Commission

2022

### Sources

https://twitter.com/UAWeapons/status/1599850612774285312
https://mil.in.ua/en/news/polish-s-125-newa-sc-sam-are-already-operating-in-ukraine/

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
