### ISSUE TITLE
Add su-30sm2 

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#2643]
### DB Selector

DB3K

### DBID to Copy

4959

### Hypothetical

No

### Name

Su-30SM2 Flanker

### Country

Russia

### Service

Navy, Airforce

### In Commission

2022-present

### Number in Service

10-20+

### Sensors

-ADD slot-back IRIBS-E PESA FCR (remove N011M bars-R FCR)
-ADD OLS-35 IRST (remove OLS-30)
-keep L-175V khibiny-10V RWR
-keep L-175 Khibiny-10V DECM
-keep mk1 eyeball

### Mounts

same/keep

### Loadout Options

same/keep

### Other Changes

2 main changes:
-replace fcr with irbis-e pesa
-replace irst with ols-35

~10 delivered to navy since 2021 with possibly 2-4 additional (22 total to be delivered) to navy and an additional 10-20 to be delivered to VKS

### Sources

https://twitter.com/GuyPlopsky/status/1598750301196259329?cxt=HHwWgsDQtbW7868sAAAA
https://twitter.com/GuyPlopsky/status/1595039897441734657
https://twitter.com/AZgeopolitics/status/1598025564383809541
https://www.19fortyfive.com/2022/09/meet-russias-su-30sm2-fighter-a-two-seat-su-30sm-with-the-guts-of-an-su-35/
https://en.wikipedia.org/wiki/Sukhoi_Su-30

**Comment by TheBagelInhaler** [comment]
not sure why hypo is affixed. maybe a glitch. it is in service though

**Comment by KLABDB3K** [comment]
Not sure why its only Navy either? Its going to both VKS and Navy?

**Comment by TheBagelInhaler** [comment]
> Not sure why its only Navy either? Its going to both VKS and Navy?

sources indicate deliveries to navy aviation only for a total of 22 aircraft

**Comment by KLABDB3K** [comment]
https://eurasiantimes.com/russia-gets-cutting-edge-su-30-sm2-fighters-with-powerful-new-radars/
REF the engines, 
"The initial lot of Su-30SM2 aircraft being delivered to the RuMoD does not feature the AL-41F-1S engines. According to Interfax sources, deliveries of Su-30SM2s with AL-41F-1S engines could begin no earlier than 2023."
https://bulgarianmilitary.com/2022/11/28/su-30sm2-fighter-is-in-serial-production-a-new-batch-is-expected/
The initial order is going to the Baltic fleet but overall it is the intention to equip both Navy and VKS. There is already another batch on order.

**Comment by TheBagelInhaler** [comment]
> https://eurasiantimes.com/russia-gets-cutting-edge-su-30-sm2-fighters-with-powerful-new-radars/ REF the engines, "The initial lot of Su-30SM2 aircraft being delivered to the RuMoD does not feature the AL-41F-1S engines. According to Interfax sources, deliveries of Su-30SM2s with AL-41F-1S engines could begin no earlier than 2023." https://bulgarianmilitary.com/2022/11/28/su-30sm2-fighter-is-in-serial-production-a-new-batch-is-expected/ The initial order is going to the Baltic fleet but overall it is the intention to equip both Navy and VKS. There is already another batch on order.

just updated it!

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
