### ISSUE TITLE
Zhuk-ME radar on MIG-29K, KUB, UPG, SM2 (SMT?)

### ISSUE THREAD

**Issue by dadizonline** [PygmalionOfCyprus/cmo-db-requests#2645]
### DB Selector

DB3K

### Affected DBID(s)

Sensor #4830 Zhuk-ME on MiG-29K, KUB, UPG, M2 (SMT?)

### Summary of Changes

Please correct the following details, I am attaching broucher pictures below 
Properties: TWS mode tracks 10 targets and engages 4, Vertical search; head-up display search; wide-angle search; boresight, and automatic terrain avoidance for low-altitude combat operations, Real beam ground-mapping; Doppler beam sharpening; synthetic aperture; display enlargement/freeze; TWS on four targets; ground target Moving Target Indicator (MTI)/tracker; air-to-surface ranging and navigation update

![image](https://user-images.githubusercontent.com/98509471/205890765-da7d6b23-ebc9-4f03-af47-77204567ffab.png)
![image](https://user-images.githubusercontent.com/98509471/205891329-ae272237-475c-45cc-8cb7-3fa97588e674.png)

### Sources

https://toad-design.com/migalley/index.php/jet-aircraft/mig29/mig29-zhuk-radar/
http://trishulgroup.blogspot.com/2009/11/iafs-mig-29upg-upgrade-package-detailed.html
![image](https://user-images.githubusercontent.com/98509471/205892863-45db8c72-3a48-4262-901c-d14e2ca46dd8.png)

**Comment by Jkryos** [comment]
Updated DB3K 498.
