### ISSUE TITLE
DC-4 ELINT for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2647]
### DB Selector

CWDB

### DBID to Copy

Issue #2646

### Hypothetical

No

### Name

DC-4 Skymaster (ELINT)

### Country

South Africa

### Service

Air Force

### In Commission

70s?-1994

### Number in Service

2x

### Sensors

Generic ELINT
Suspect Generic COMINT - "A far lesser known role of the DC-4 was that of electronic warfare. This involved electronic reconnaissance and real time support of aerial strikes during the Bush and Angolan wars." - I would expect, given the relatively limited use of radars in the early stages of the Bush War, that the support to air strikes included at least some COMINT monitoring.

### Other Changes

See note on #2646 regarding shrouded exhausts.

### Sources

http://www.dc-4.co.za/SAAF.htm
http://www.pilotspost.com/arn0000313

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
