### ISSUE TITLE
Australia - Skylark I-LEX

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2650]
### DB Selector

DB3K

### DBID to Copy

DBID 6062

### Hypothetical

No

### Name

Skylark I-LEX UAV

### Country

Australia

### Service

Army

### In Commission

2023-

### Number in Service

uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

None

### Sources

https://airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/december/8832-australian-army-selects-israeli-skylark-i-lex-unmanned-aerial-system.html?fbclid=IwAR0WNIQa7IvosuTG1KhcFaJ4bEQDEvE5xwwA00Fft2GFlZk9cqDVgVI7JpA

![image](https://user-images.githubusercontent.com/99599482/206267760-f9fa02fe-60ca-434c-b80b-1ec58b07537c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
