### ISSUE TITLE
Add S-350 facility to Algeria

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2653]
### DB Selector

DB3K

### DBID to Copy

2089

### Hypothetical

No

### Name

S-350 Vityaz 

### Country

Algeria

### Service

Army

### In Commission

2022-present

### Number in Service

>1

### Sensors

-remove 96L6-TSP acquisition radar (replace with dbid #3204)
-Add 96L6E Cheese Board to replace TSP

export s-350 use standard 96l6e. only domestic s-350 use upgraded 96l6-TSP variant

### Other Changes

satellite pics show at least 4 S-350 TEL and a 96L6E radar deployed

### Sources

https://twitter.com/S_flanker1993/status/1550103439656587265
https://twitter.com/GUAN_FAHRANZAYD/status/1550137227849744385
https://twitter.com/zspcl/status/1559756880431439878

**Comment by KLABDB3K** [comment]
It does show S350 in the ast source. Intrestingly it's mounted on a tracked chassis, the Viking system is in the same photo on the same chassis . Only ever seen it with the BAZ 8x8 before.

**Comment by Huib18** [comment]
The first post does not show S-350 but empty S-300PMU-2 launchers. 
Compare the radar and the launcher with this picture which are totally different: [https://www.ainonline.com/aviation-news/defense/2020-01-09/first-s-350-vityaz-sam-delivered-russia](url)

The last source is just a regular Buk-M3 reloader not a S-350.
You can compare it with this picture [https://www.thedefensepost.com/wp-content/uploads/2021/09/1331871.jpg](url)
So no evidence yet.

**Comment by TheBagelInhaler** [comment]
> The first post does not show S-350 but empty S-300PMU-2 launchers. Compare the radar and the launcher with this picture which are totally different: [https://www.ainonline.com/aviation-news/defense/2020-01-09/first-s-350-vityaz-sam-delivered-russia](url)
> 
> The last source is just a regular Buk-M3 reloader not a S-350. You can compare it with this picture [https://www.thedefensepost.com/wp-content/uploads/2021/09/1331871.jpg](url) So no evidence yet.

upon closer inspection you may be right about 1 twitter source. However for the second, are you sure that is BUK-M3 because usually it only comes with 6 launchers not 12?

**Comment by Huib18** [comment]
The Buk-M3 has new missiles compared to the Buk-M2  These are in tubes. But they are rarely seen because they are so new.
And the Buk-M3 can fire also the older missiles.

You can read about it here [https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/buk-m3_9k317m_medium-range_air_defense_missile_system_technical_data_sheet_specifications_11312154.html](url)

In the picture settings on this page you can see the reloader with the high amount of missiles. In the Missile section you will find that it is not a S-350 missile. You can also compare the launchtubes of the S-350 and the Buk-M3.

But I agree, it gets confusing with all those tubes indeed! And also good that you try to improve the game!

PS. the  reloader of the Buk-M2 comes with eight missiles and not six.
![images](https://user-images.githubusercontent.com/60408110/209106504-3dc359a9-5723-4f15-ba75-659eb9b34025.jpg)

**Comment by TheBagelInhaler** [comment]
> I agree, it gets confusing with all those tubes indeed! And also good that you try to improve the game!
> 
> The Buk-M3 has new missiles compared to the Buk-M2 These are in tubes. But they are rarely seen because they are so new. And the Buk-M3 can fire also the older missiles.
> 
> You can read about it here [https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/buk-m3_9k317m_medium-range_air_defense_missile_system_technical_data_sheet_specifications_11312154.html](url)
> 
> In the picture settings on this page you can see the reloader with the high amount of missiles. In the Missile section you will find that it is not a S-350 missile. You can also compare the launchtubes of the S-350 and the Buk-M3.
> 
> PS. the reloader of the Buk-M2 comes with eight missiles and not six. ![images](https://user-images.githubusercontent.com/60408110/209106504-3dc359a9-5723-4f15-ba75-659eb9b34025.jpg)

thanks mate! I suppose we can hold off on this for now until there's solid evidence of any deployment for algeria side 👍

**Comment by TheBagelInhaler** [comment]
> I agree, it gets confusing with all those tubes indeed! And also good that you try to improve the game!
> 
> The Buk-M3 has new missiles compared to the Buk-M2 These are in tubes. But they are rarely seen because they are so new. And the Buk-M3 can fire also the older missiles.
> 
> You can read about it here [https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/buk-m3_9k317m_medium-range_air_defense_missile_system_technical_data_sheet_specifications_11312154.html](url)
> 
> In the picture settings on this page you can see the reloader with the high amount of missiles. In the Missile section you will find that it is not a S-350 missile. You can also compare the launchtubes of the S-350 and the Buk-M3.
> 
> PS. the reloader of the Buk-M2 comes with eight missiles and not six. ![images](https://user-images.githubusercontent.com/60408110/209106504-3dc359a9-5723-4f15-ba75-659eb9b34025.jpg)

thanks mate! I suppose we can hold off on this for now until there's solid evidence of any deployment for algeria side 👍
