### ISSUE TITLE
China, Fire Dragon 300 ballistic missile

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2654]
### DB Selector

DB3K

### Baseline

weapon 1717

### Hypothetical

No

### Name

Fire Dragon 300

### Length (m)

3.98

### Width/Span (m)

1.4

### Diameter (m)

0.61

### Weight (kg)

1420

### Range (nm)

30-162

### Warhead

200kg HE

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

30m

### Sensors

1x IIR Seeker
1x Passive Radar Seeker

### Weapon Codes

Uses Beidou/COMPASS, INS/GNSS, Level cruise flight, Ballistic missile or rocket booster

### Sources

https://twitter.com/nuwangzi/status/1595059879081050112?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1595059884625633280%7Ctwgr%5Eb6d5e13de835bd6a676f20b3d233550dabce054a%7Ctwcon%5Es2_&ref_url=https%3A%2F%2Fwww.sinodefenceforum.com%2Ft%2F2022-zhuhai-airshow-land-systems.9014%2Fpage-31
![image](https://user-images.githubusercontent.com/107970049/206887252-98355cb2-918e-402c-9440-1e1060a44326.png)
![image](https://user-images.githubusercontent.com/107970049/206887281-33362f19-e3ce-4c27-9e15-bc31961e15ba.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
