### ISSUE TITLE
China, SR-5 MLRS, Fire Dragon 300

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2655]
### DB Selector

DB3K

### Affected DBID(s)

ground unit 351, facility 3623

### Summary of Changes

Add weapon record: 2x fire dragon 300

### Sources

![image](https://user-images.githubusercontent.com/107970049/206887621-4387eb17-276d-481f-9ee4-2611bf29d99f.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
