### ISSUE TITLE
Correction: AN/APG-78 Longbow MMR is Actually K-Band, not J-Band

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#2656]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 602

### Summary of Changes

AN/APG-78 Longbow MMR's operating band as listed in DB3K 497a is J-band, but according to the manufacturer, it is actually K-band (IEEE Ka-band to be specific). According to NATO's radio frequencies band designation, J-band has a frequency spanning from 10-20 GHz, where K-band spans 20-40 GHz. The obsolete NATO designation assigned Ka-band with a frequency ranging from 20-36 GHz. So even if the manufacturer refers to the old NATO Ka-band, J-band would be right on 20 GHz, a transitional edge between old NATO Ku and Ka-band. 

But since Northrop Grumman's official AN/APG-78 leaflet was published in 2007 and Lockheed Martin published one in 2019, they're definitely referring to IEEE's Ka-band (27-40 GHz) as NATO no longer use Ku and Ka letters in its nomenclature. Also, AN/APG-78 is advertised as a millimeter-wave radar, which would mean its wavelength must be between 1-10 millimeter, J-band's wavelength at its shortest is 15 millimeter, which means the radar can't be operating in J-band.

![APG78BandCorrection](https://user-images.githubusercontent.com/99858862/206912460-336d00a3-b9e7-407a-90a5-8f61865b4141.png)

### Sources

[EU, NATO, US ECM Frequency Designations](https://awt-global.com/wp3/resources/eu-nato-us-ecm-frequency-designations/) --- Page indexed by Google more than 10 years ago

>![IEEELetterBands](https://user-images.githubusercontent.com/99858862/206914117-6f5e2256-fe88-4382-84a7-80c7aabda3b1.png)
![NATOEWLetterBands](https://user-images.githubusercontent.com/99858862/206914119-5cfb52f3-52e9-43d8-bd82-a670e2c93868.png)

------------------------------------------------------------------------------------------------------------------------------------------------

[Official Northrop Grumman and Lockheed Martin Longbow Leaflet](https://www.radartutorial.eu/19.kartei/08.airborne/pubs/longbow.pdf) --- Page indexed by Google more than 10 years ago, archived by radartutorial.eu

>![NGLMAPG-78](https://user-images.githubusercontent.com/99858862/206914407-668126e3-0f16-4daf-8eb9-5cdc4fd38186.png)

------------------------------------------------------------------------------------------------------------------------------------------------

[Lockheed Martin Official Product Card - Lowbow FCR](https://www.lockheedmartin.com/content/dam/lockheed-martin/mfc/pc/longbow-fcr/mfc-longbow-fcr-pc-01.pdf) --- Page indexed by Google more than 10 years ago

>![LMAPG-78](https://user-images.githubusercontent.com/99858862/206914470-ce6e5591-88ac-43a3-a667-ade43a3e189f.png)

**Comment by Jkryos** [comment]
Updated DB3K 498.
