### ISSUE TITLE
Add YJ-18 loadout to SONG class SS, YUAN class SSP, and SHANG class SSN

### ISSUE THREAD

**Issue by rushgg** [PygmalionOfCyprus/cmo-db-requests#2657]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #2868 YJ-18 [3M54 Klub Copy]

### Summary of Changes

Add YJ-18 as loadout for the following submarines:
Submarine #153- Type 039 Song (China - 2000)
Submarine #252- Type 039G Song (China - 2002)
Submarine #124- Type 039G1 Song (China - 2007)
Submarine #403- Type 039A Yuan (China - 2008)
Submarine #577- Type 039B Yuan (China - 2014)
Submarine #580- Type 039B Yuan (China - 2016)
Submarine #695- Type 039C Yuan (China - 2021)
Submarine #164- Type 093 Shang (China - 2007)

You can just replace all submarine-launched YJ-82 with YJ-18, as YJ-18 can be launched from 533mm TT.

### Sources

"The PRC’s **SONG class SS, YUAN class SSP, and SHANG class SSN** field the PLAN’s newest domestic submarine-launched YJ-18 and its variants, which constitute an improvement over the SS-N-27b ASCM"  from page 74 of China Military Power Report 2022. https://media.defense.gov/2022/Nov/29/2003122279/-1/-1/1/2022-MILITARY-AND-SECURITY-DEVELOPMENTS-INVOLVING-THE-PEOPLES-REPUBLIC-OF-CHINA.PDF

**Comment by Jkryos** [comment]
Added DB3K 505.
