### ISSUE TITLE
Rch 155 Barrel Length

### ISSUE THREAD

**Issue by TheDarkCaesar** [PygmalionOfCyprus/cmo-db-requests#2658]
### DB Selector

DB3K

### Affected DBID(s)

#367 Boxer RCH 155

### Summary of Changes

The RCH 155 shoots 155mm/39 HE instead of 155mm/52 HE like the PzH 2000. They booth use the same Rheinmetall 
155 mm L52 gun. By the way, to my knowledge the Bundeswhr doesn´t use RAP projectiles, they use the Rh 40 DM 131, a base bleed shell. This shell can also be shoot by the RCH 155.

### Sources

https://www.kmweg.com/systems-products/wheeled-vehicles/artillery/rch-155/
https://en.wikipedia.org/wiki/Artillery_Gun_Module
https://www.deagel.com/Defensive%20Weapons/Rh%2040%20DM%20131/a000930
https://de.wikipedia.org/wiki/Liste_von_Bundeswehrmunition#Artillerietruppe

**Comment by Jkryos** [comment]
Updated DB3K 498.
