### ISSUE TITLE
Correction: Sensors on SBIRS HEO

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2659]
### DB Selector

DB3K

### Affected DBID(s)

Satellite 68

### Summary of Changes

Satellites in the HEO orbit need the long-range IR sensor to provide missile warning. 
Change the sensors to 6263. 

### Sources

https://en.wikipedia.org/wiki/Highly_elliptical_orbit

**Comment by Jkryos** [comment]
Updated DB3K 498.
