### ISSUE TITLE
A 136 Tidespring [MARS Tide Class] United Kingdom (Royal Navy), 2017. 4x 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#266]
### DB Selector

DB3K

### Affected DBID(s)

2581

### Summary of Changes

The fuel levels carried look too low. It is showing that the ship only carries 123 tones of diesel fuel and 26 tons of Aviation fuel.

Source: "Mobile filling station
17 separate tanks can hold 19,000 tonnes of F76 marine diesel, F44 aviation fuel and a further 1,300 tonnes of fresh water for issue to other vessels. The dual-use fuel tanks can be filled with F76 or F44, depending on the mission. Supporting the carriers, for example, will usually require a larger proportion of F44."

### Sources

https://www.navylookout.com/supporting-the-royal-navy-at-sea-in-focus-the-tide-class-tankers/
https://www.bmt.org/industries/defence-and-security/surface-systems/bmt-aegir-logistic-support-vessels/

**Comment by tbrandon517** [comment]
Duplicate of #192

**Comment by cdnice55** [comment]
Thanks, missed that since it was closed already.
