### ISSUE TITLE
Correction: Signature of F-35Cs with sidekick. 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2660]
### DB Selector

DB3K

### Affected DBID(s)

3836, 4872, 4873, 4874

### Summary of Changes

The 6x AIM-120D(27222) loadout should have their signature unaffected. 

### Sources

https://www.navalnews.com/naval-news/2021/01/update-f-35-block-4-upgrades-and-new-f-35b-at-sea-users/

**Comment by Jkryos** [comment]
Updated DB3K 498.
