### ISSUE TITLE
Update: SDB II

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2661]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2855

### Summary of Changes

_"The weapon datalink allows post-launch tracking and control of the weapon"_
_"[T]he weapon receiv[es] valid targeting data (through) Link 16 datalink []and the [] JTAC ultrahigh frequency (UHF) datalink"_

1. Add a datalink to enable target update, control and CEC by aircrafts. 
2. Add reattack capability. 

"[The SDB can] [fly] around terrain to hit targets on the back of mountains, or circling back around to a target behind the launch vehicle." #2617
3. Add level cruise flight. 
4. Can plot course. 

### Sources

https://www.dote.osd.mil/Portals/97/pub/reports/FY2020/af/2020sdbii.pdf?ver=LH1GttQNyuH6VW4W-cUJoA%3D%3D
https://en.wikipedia.org/wiki/GBU-39_Small_Diameter_Bomb
https://en.wikipedia.org/wiki/GBU-53/B_StormBreaker

**Comment by Jkryos** [comment]
Updated DB3K 498.
