### ISSUE TITLE
Japan, Bell 212, Coast Guard

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2662]
### DB Selector

Both

### DBID to Copy

DB3K 5698

### Hypothetical

No

### Name

Bell 212

### Country

Japan

### Service

Coast Guard

### In Commission

1973-2014

### Number in Service

38x

### Sensors

-Generic Weather & Navigation Radar
-LLTV
-Generic Search Light

### Mounts

-same

### Loadout Options

-same

### Other Changes

Comment:for PLH (Large Helicopter Patrol Vessel)

### Sources

https://www.kaiho.mlit.go.jp/info/books/report2016/html/ninmu/ninm16_03_clm03.html
http://www1.cts.ne.jp/fleet7/Jcgt/JCGtapB212.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
