### ISSUE TITLE
(Relatively) New KH-11s

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2665]
### DB Selector

DB3K

### Hypothetical

No

### Series Name

KH-11 Blk V

### Satellite Type

IMGSAT

### Country

United States

### Service

Space Force

### Is Geostationary

No

### COSPAR ID

USA 314: 2021-032A 
USA 338: 2022-117A

### Launch/Comm. & Decom./Deorbit Date(s)

USA 314: 2021-04-26
USA 338: 2022-09-24

### TLE

USA 314: 
1 48247U 21032A   22255.00624420 0.00000000  00000-0  00000-0 0    00
2 48247  97.9980   6.7526 0159180 278.4167  81.5831 14.70150721    08
USA 338: 
1 53883U 22117A   22316.76140039 0.00012000  00000-0  17921-3 0    03
2 53883  73.6042 302.2879 0017309 279.7436  80.6064 15.54732487    00

### Sensors

Satellite 94

### Comments

Also, some KH series sats are in the MASINT type.(Blk III and IV)

### Sources

https://en.wikipedia.org/wiki/KH-11_KENNEN

**Comment by Jkryos** [comment]
Added DB3K 498.
