### ISSUE TITLE
Update: Sky Bow III

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2667]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 888

### Summary of Changes

The maximum target altitude is 45km.  

### Sources

https://web.archive.org/web/20220528141912/https://opinion.udn.com/opinion/story/120746/4521682
https://web.archive.org/web/20220528141912/https://www.upmedia.mg/news_info.php?Type=1&SerialNo=47765
https://forum.ettoday.net/news/1893383

**Comment by Jkryos** [comment]
Updated DB3K 498.
