### ISSUE TITLE
Add Algerian Mig-29M2 2021 x14

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#267]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4868

### Hypothetical

No

### Name

Mig-29M Fulcrum C

### Country

Algeria

### Service

Airforce

### In Commission

2021

### Sensors

Same as Egyptian export model.

Looks like they did buy an advanced Russian helmet for target queueing but not sure CMO models that.

https://twitter.com/DarikMk/status/1468195047510360067

### Loadout Options

Similar as Egyptian for now.

### Other Changes

Can add M2/UBM-2 seat version too if still doing that. Bought 14

### Sources

https://www.scramble.nl/military-news/first-mig-29m-m2-fighter-aircraft-delivered-to-algeria
https://www.scramble.nl/military-news/brand-new-algerian-mig-29m2
https://twitter.com/warplane_porn/status/1458529374873997324
https://twitter.com/RealAirPower1/status/1359203797613092871
https://twitter.com/AlgerianAircra1/status/1483094932806148097
https://en.wikipedia.org/wiki/Mikoyan_MiG-29M

**Comment by PygmalionOfCyprus** [comment]
@Jkryos HMD code.

**Comment by Jkryos** [comment]
Added DB3K 493.
