### ISSUE TITLE
Correction: Long Mountain Radar for Fixed Site Sky Bow III

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2670]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6366, Facility 395

### Summary of Changes

Sensor 6366
Range: 540nm
Max Power: 1000000kw
Max Altitude: 100km
Generation: Early 2000s 
Band: F/G
-
Facility 395
1x120 deg sensor 6366 for facility 395. 

### Sources

https://zh.wikipedia.org/w/index.php?title=%E5%A4%A9%E5%BC%93%E4%B8%89%E5%9E%8B%E9%98%B2%E7%A9%BA%E9%A3%9B%E5%BD%88&oldid=74546002
https://forum.ettoday.net/news/1893383
https://forum.ettoday.net/news/1893383

**Comment by Jkryos** [comment]
Updated DB3K 498.
