### ISSUE TITLE
Advance New Zealand P-8 in service date to 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2672]
### DB Selector

DB3K

### Affected DBID(s)

4742

### Summary of Changes

Replace 2020 in service date to 2023. There will be 4 of them

### Sources

https://www.scramble.nl/military-news/first-rnzaf-poseidon-handed-over
https://www.navalnews.com/naval-news/2022/12/boeing-delivers-first-p-8a-poseidon-to-new-zealand/#:~:text=New%20Zealand%20received%20the%20first,8s%20to%20six%20global%20customers

**Comment by Jkryos** [comment]
Updated DB3K 498.
