### ISSUE TITLE
Add out of service date of 2022 for French Navy Alouette III

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2673]
### DB Selector

DB3K

### Affected DBID(s)

1973

### Summary of Changes

Add out-of-service date of 2022. 

Kind of a shocker these were still used by the FN.

### Sources

https://www.scramble.nl/military-news/marine-nationale-withdraws-final-alouette-3

**Comment by Jkryos** [comment]
Updated DB3K 498.
