### ISSUE TITLE
SA.321L Super Frelon for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2675]
### DB Selector

CWDB

### DBID to Copy

CWDB Aircraft 3014 or 1651 (they have different numbers of troops?)

### Hypothetical

No

### Name

SA.321L Super Frelon

### Country

South Africa

### Service

Air Force

### In Commission

1967-1990

### Number in Service

16x

### Loadout Options

I dunno what to do with the troops, 3014 says 24, 1615 says 20, Wikipedia/SAairforce says 27!

### Other Changes

Yet another one for both databases and the DBTwools tag. I'd put it on myself if I could.

### Sources

https://www.saairforce.co.za/the-airforce/aircraft/37/sa321l-super-frelon
https://en.wikipedia.org/wiki/A%C3%A9rospatiale_SA_321_Super_Frelon#South_Africa

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
