### ISSUE TITLE
change frequency to C/D for protivnik-ge radars

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2676]
### DB Selector

DB3K

### Affected DBID(s)

3608 , 3149 , 2257

### Summary of Changes

Most sources agree that it operates on the UHF, is decametric but also on L-band. So It should border on the lower end of the L-band as well at approx ~1.3GHz (23cm wavelength). official export source below (decametric) 
![decametric protivnik-ge](https://user-images.githubusercontent.com/108960393/207761500-97eb2c61-d4bf-4acf-9b53-e1167107fa97.png)

globalsecurity source shows it having a max wavelength of 23cm which borders L-band at around 1.3ghz, while also maintaining it operates at the UHF decimeter spectrum as well.
![23cm protivnik-ge ](https://user-images.githubusercontent.com/108960393/207761533-ca45b377-df8d-4afe-9916-56d166313904.png) 

Similarly, the RLM-D (AESA upgrade used in nebo complex) is listed as a C/D band from varying sources that imply both UHF and L band properties. So this should be the same since it is the precursor that the later was developed from. 

**summary of changes: change frequencies to encompass the range from 0.5-1.3GHz (C/D) bands
Given most sourcing either state both a combination of UHF and L-band, or just one or the other, it's a safe bet to say it operates on the UHF/L-band spectrum up to a max frequency of 1.3Ghz**
The long range detection comes from UHF while the high accuracy fine tracking comes from the L-band

### Sources

https://www.globalsecurity.org/military/world/russia/protivnik.htm
https://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/59N6-%D0%A2%D0%95/

**Comment by Jkryos** [comment]
Updated DB3K 498.
