### ISSUE TITLE
Add SA-21 batteries with optional acquisition radars

### ISSUE THREAD

**Issue by TheBagelInhaler** [PygmalionOfCyprus/cmo-db-requests#2677]
### DB Selector

DB3K

### Affected DBID(s)

2104

### Summary of Changes
for russian side, create 2 copy/entry of SA-21a/b battery (dbid#1937) but with 96l6 cheese board swapped out for the following acquisition radars(confirmed deployed/confirmed compatible by almaz-antey and exporter):
-Gamma DE (dbid# 3219)
-Protivnik-GE (dbid# 3608)
also 2 copy/entry of SA-21a (2007) with 96l6 removed and substituted with gamma-D/protivnik-Ge

![ausairpower rlc](https://user-images.githubusercontent.com/108960393/207764782-cf98aedb-0739-4a34-8fe1-60760018b168.png)
here an almaz brochure shows Gamma-de/protivnik-ge as optional replacements over the 96l6 for the S-400 battery. 

Almaz Antey/Rosboronexport both state that each of these 2 radars can substitute the 96L6E cheese board at the battery level and can be integrated using 55k6e or Baikal-E command post. Russia uses this configuration in limited deployment confirmed in Crimea nearby s400 batteries.

![gamma-de compatibility ](https://user-images.githubusercontent.com/108960393/207764868-65ccbe01-f463-4e6a-906c-ecb103508d32.png) pic shows Gamma-DE measurement accuracy

![protivink compatibility 1](https://user-images.githubusercontent.com/108960393/207764877-f6d037f1-df45-47c1-9604-03cd9633d558.png) similar high precision measurements for a UHF/L-band. Almaz Antey states any of which can replace and substitute the 96l6e for improved anti-stealth roles in the battery

![GE-gamma-rlm #1](https://user-images.githubusercontent.com/108960393/207764887-88ef6344-c9f4-47c0-9412-b1f54c3d398b.png)

RLM-D and Protivnik-GE have been confirmed via satellite deployed in Crimea near S-400 batteries. They can be separated far distances using radio link or up to 1000m using fiber optic cable.

**summary of changes:
-add SA-21a/b battery with Gamma-D, swap out 96L6 cheese
-add SA-21a/b battery with Protivnik-GE, swap out 96L6 cheese
-add SA-21a battery with Gamma-D, swap out 96l6 cheese
-add SA-21a battery with protivnik-GE, swap out 96l6 cheese

### Sources

http://www.ausairpower.net/APA-Rus-Low-Band-Radars.html#mozTocId988574

https://en.wikipedia.org/wiki/S-400_missile_system

**Comment by HVAA** [comment]
Step too far, sorry. They may plug into the GCP, but the datalink signals come from the FCR. No FCR, no datalink channels period.

**Comment by TheBagelInhaler** [comment]
> Step too far, sorry as AFAIK (in the game sense) 96L6 does not possess datalinks. These other radars may plug into the GCP, but the (TVM/SAGG) datalink signals come from the FCR. No FCR, no datalink channels period, no datalink channels, no missile firing other than Active all the Way (with reduced pk due to the lack of comparison with the FCR TQ tracks). Also, as I have posted elsewhere (with visual proof), 9M96 is part of this system and is deployed (at least in China and likely elsewhere).

I misunderstood the functions of 96l6. I corrected my request as follows:
batteries of SA-21a/b using gamma-d or protivnik-g as substitute acquisition radars. So just swapping out the 96l6 and replacing with the others.

**Comment by Huib18** [comment]
Quote: as the 9m96 you mentioned, there should be battery in the game using 9m96 and 48n6/40n6e missiles **since sat pics have shown this type of deployment**. similar to how there's a Patriot bttry using pac-2 GEM and Pac-3 missiles in one setup._

Can you provide a source of this kind of deployment?
I agree it is in the pipeline but haven't seen it yet, except for Turkey. But where the tubes empty or loaded, if even Russia does not use them yet..?
If programmed, IMHO it should be under hypothetical.

**Comment by Huib18** [comment]
_Quote:  2 batteries of SA-21a and a/b using gamma-d or protivnik-g as substitute acquisition radars instead of C band 96l6. So just swapping out the 96l6 and replacing with the others instead. Leaving everything else the same. 2 copies of dbid#1937 with cheese board swapped for gamma/protivnik. 8x launchers since those are what's deployed Crimea near protivnik-ge/rlm-d radars.
-I'm sure due to the sensitivity and high cost of these systems it is not a common acquisition radar deployment for a typical S-400 battery. Limited deployment in key areas like crimea, far east, karelia, kaliningrad, etc. As for the NEBO-M system, the RLM-D can also substitute for the 96l6 in an S-400 battery and can be deployed far away from the 92N6A FCR, as Crimea shows._

gamma-d or protivnik-g radars or other type of search radars provide early warning and cueing for command posts and SAM sites. Also a Barlock or a P-18 Spoonrest wil do this.
This does not mean it belongs with the S-400 unit or another SAM. It supports the network. That is why you will find several types of early warning radars around the area. 
You can read about them here: [https://en.wikipedia.org/wiki/Russian_Radio-Technical_Troops](url)
or here:
[https://www.globalsecurity.org/military/world/russia/pvo-rtv.htm](url)


In CMO, if you put a Gamma radar somewhere it will always support your S-400, due to the programming of this game.

**Comment by TheBagelInhaler** [comment]
> _Quote: 2 batteries of SA-21a and a/b using gamma-d or protivnik-g as substitute acquisition radars instead of C band 96l6. So just swapping out the 96l6 and replacing with the others instead. Leaving everything else the same. 2 copies of dbid#1937 with cheese board swapped for gamma/protivnik. 8x launchers since those are what's deployed Crimea near protivnik-ge/rlm-d radars. -I'm sure due to the sensitivity and high cost of these systems it is not a common acquisition radar deployment for a typical S-400 battery. Limited deployment in key areas like crimea, far east, karelia, kaliningrad, etc. As for the NEBO-M system, the RLM-D can also substitute for the 96l6 in an S-400 battery and can be deployed far away from the 92N6A FCR, as Crimea shows._
> 
> gamma-d or protivnik-g radars or other type of search radars provide early warning and cueing for command posts and SAM sites. Also a Barlock or a P-18 Spoonrest wil do this. This does not mean it belongs with the S-400 unit or another SAM. It supports the network. That is why you will find several types of early warning radars around the area. You can read about them here: [https://en.wikipedia.org/wiki/Russian_Radio-Technical_Troops](url) or here: [https://www.globalsecurity.org/military/world/russia/pvo-rtv.htm](url)
> 
> In CMO, if you put a Gamma radar somewhere it will always support your S-400, due to the programming of this game.



> Quote: as the 9m96 you mentioned, there should be battery in the game using 9m96 and 48n6/40n6e missiles **since sat pics have shown this type of deployment**. similar to how there's a Patriot bttry using pac-2 GEM and Pac-3 missiles in one setup._
> 
> Can you provide a source of this kind of deployment? I agree it is in the pipeline but haven't seen it yet, except for Turkey. But where the tubes empty or loaded, if even Russia does not use them yet..? If programmed, IMHO it should be under hypothetical.

shown here deployed on quad launcher with 40n6/48n6 series
https://twitter.com/benreuter_IMINT/status/1594340893791686656

**Comment by TheBagelInhaler** [comment]
https:

> Quote: as the 9m96 you mentioned, there should be battery in the game using 9m96 and 48n6/40n6e missiles **since sat pics have shown this type of deployment**. similar to how there's a Patriot bttry using pac-2 GEM and Pac-3 missiles in one setup._
> 
> Can you provide a source of this kind of deployment? I agree it is in the pipeline but haven't seen it yet, except for Turkey. But where the tubes empty or loaded, if even Russia does not use them yet..? If programmed, IMHO it should be under hypothetical.

deployed somewhere domestically in RU using quad rail 9m96 alongside combo of 40n6/48n6 series
https://twitter.com/benreuter_IMINT/status/1594340893791686656
https://twitter.com/DylanMalyasov/status/1172448506826698752

**Comment by TheBagelInhaler** [comment]
> _Quote: 2 batteries of SA-21a and a/b using gamma-d or protivnik-g as substitute acquisition radars instead of C band 96l6. So just swapping out the 96l6 and replacing with the others instead. Leaving everything else the same. 2 copies of dbid#1937 with cheese board swapped for gamma/protivnik. 8x launchers since those are what's deployed Crimea near protivnik-ge/rlm-d radars. -I'm sure due to the sensitivity and high cost of these systems it is not a common acquisition radar deployment for a typical S-400 battery. Limited deployment in key areas like crimea, far east, karelia, kaliningrad, etc. As for the NEBO-M system, the RLM-D can also substitute for the 96l6 in an S-400 battery and can be deployed far away from the 92N6A FCR, as Crimea shows._
> 
> gamma-d or protivnik-g radars or other type of search radars provide early warning and cueing for command posts and SAM sites. Also a Barlock or a P-18 Spoonrest wil do this. This does not mean it belongs with the S-400 unit or another SAM. It supports the network. That is why you will find several types of early warning radars around the area. You can read about them here: [https://en.wikipedia.org/wiki/Russian_Radio-Technical_Troops](url) or here: [https://www.globalsecurity.org/military/world/russia/pvo-rtv.htm](url)
> 
> In CMO, if you put a Gamma radar somewhere it will always support your S-400, due to the programming of this game.

I wasn't aware of this programming feature which will work with S-400 batteries. Interesting to note! So far there is no solid photographic evidence showing RLM-D/protivnik/gamma alongside 92n6 FCR in a battery formation. So it would be hypothetical I'd assume. Fakel/Almaz insist they are indeed substitutes for the 96l6 and they are in use. But if they function similarly in game already as you mentioned, there is maybe not a need to incorporate them in their own separate batteries.

**Comment by TheBagelInhaler** [comment]
45°19'23.20"N, 36°21'44.78"E kerch looks to be thinner tubes similar to the quad rail housing 9m96D

64°29'44.56"N 39°38'45.27"E at sverdvinsk looks to be a quad rail on one of the TEL on the left side 

As you notice the quadrails appear darker and thinner, while standard 48n6/40n6 are lighter color

**Comment by HVAA** [comment]
> Quote: as the 9m96 you mentioned, there should be battery in the game using 9m96 and 48n6/40n6e missiles **since sat pics have shown this type of deployment**. similar to how there's a Patriot bttry using pac-2 GEM and Pac-3 missiles in one setup._
> 
> Can you provide a source of this kind of deployment? I agree it is in the pipeline but haven't seen it yet, except for Turkey. But where the tubes empty or loaded, if even Russia does not use them yet..? If programmed, IMHO it should be under hypothetical.

Beijing SAM ring - clearly on GE, dating back to 2019 -Several locations in Russia and Occupied Crimea, dating back to 2020 - what more proof is required. You're not going to get panoramic 'obliques' in open source, so this is the best you will ever get at this level.  I have no idea why this system so divides the players and the devs, there are 'hypotheticals' in the DB which would never see the light of day - yet something that is clearly deployed and exported is resisted at every mention of it, even when rock solid evidence is provided.

**Comment by Huib18** [comment]
> 
As I commented above, the Turkish S-400 has been shown to have the 9M96 tubes. 
Source: [https://twitter.com/RALee85/status/1313534012112199680](url)
Allegedly, photos of two of Turkey's S-400 TELs, one 5P85TE3 and one 51P6E. Notably, the 51P6E TEL appears to be equipped with two 48N6-series missile cannisters and 4 (or possibly 8) 9M96E or 9M96E2 missile cannisters.

About the Chinese: here is a sat image from [https://twitter.com/benreuter_IMINT/status/1513805503809429509](url)
which does not show any 9m96E. 
![FQIdzDhX0AclZFN](https://user-images.githubusercontent.com/60408110/209484850-4044a15c-afed-46f9-991a-ce201fdb5c18.jpg)


Thirdly, the coordinates mentioned by @TheBagelInhaler do not shown the 51P6 TEL but the 5P85, which do not carry the 9M96.. You can compare the images with the Turkish 51P6 with the tubes on the left with the 5P85s on the right. 
![Clipboard06](https://user-images.githubusercontent.com/60408110/209484933-e86d9a33-1ab7-4a5e-a48d-ee1eb57753d9.jpg)
Don't confuse an empty 51P6 with a 96M6 missile. Check for the bulb at the back of the tube:
![Clipboard04](https://user-images.githubusercontent.com/60408110/209485452-4be9ca3b-16f7-4497-ab21-72d017b3a002.jpg)

So no Russian launcher, no Chinese, only Turkish tubes. 
This makes me think the whole setup is still a future idea and not a operational setup.
But it is in the pipeline, as I mentioned earlier ;-) 
And I don't care if it is hypothetical or not. But the sources must be right. And I would be happy to see them!
