### ISSUE TITLE
Correction: IFPC-HEL's Weapon

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2678]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3651

### Summary of Changes

Target: Aircraft, Helicopter, Missile, C-RAM. 
Add Capable vs Seaskimmer, C-RAM Capable

### Sources

https://www.army.mil/article/233346/scaling_up_army_advances_300kw_class_laser_prototype
https://www.dynetics.com/directed-energy/

**Comment by Jkryos** [comment]
Updated DB3K 498.
