### ISSUE TITLE
Update/Correction for Fakour-90 missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2680]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2784

### Summary of Changes

- Increase burn time from 5 seconds to 17 second. This is due to the missile used M112 rocket motor, same as AIM-23 Sedjil(Weapon/748)
![image](https://user-images.githubusercontent.com/99646926/207868650-874d0c9f-21f5-49b2-8bd0-b4155da4ca6d.png)

- Increase the max range of the missile to 150km (81 nm). Also increase missile`s flight endurance to match the range.

- Increase missile`s top speed to Mach 5 (3220 knot).
![image](https://user-images.githubusercontent.com/99646926/207868876-3cd793ad-cacb-4f95-be2b-8d2ba8fd3228.png)

Notes: The seeker remain unchanged. As per quote below: 
"Minor correction - the AIM-54 use a semi-active guidance mode for it's midcourse, the active guidance component is only for the last 20,000 yards or so during terminal guidance. (Launches within this range band can, of course, begin in active guidance.) Given the Iranian claims that the missile has at least some active component, the Fakour probably functions similarly.

Further, if you compare the nosecones between the HAWK, the AIM-54, and the Fakour, the Fakour's more closely matches the AIM-54. As it happens, the shape of the nosecone can greatly impact the effectiveness of a radar inside the nose, with longer ogives attenuating the radar emission more. Thus, the fact that the Fakour has a nose cone which shares the same shape as the AIM-54 and which is more conducive to an active emitter lends credence to the missiles having at least some active guidance component. "

### Sources

- https://irangeomil.blogspot.com/2018/07/analysis-fakour-air-to-air-missile.html
- https://web.archive.org/web/20190414110848/https://www.janes.com/article/81942/iran-announces-mass-production-of-fakour-air-to-air-missile

**Comment by Jkryos** [comment]
Updated DB3K 498.
