### ISSUE TITLE
Advance Bremen decommission date to 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2681]
### DB Selector

DB3K

### Affected DBID(s)

832

### Summary of Changes

Change the decommission date from 2019 to 2022

Lubeck was the last and it decommissioned this week.

### Sources

https://twitter.com/naval_gazing/status/1603317466842767361
https://twitter.com/AlexLuck9/status/1548556216221442048
https://defbrief.com/2022/01/19/last-of-germanys-bremen-class-frigates-begins-swan-song-deployment/

**Comment by FrangibleCover** [comment]
Should that be 2022?

**Comment by bostonmyk** [comment]
Sure. Updated.

**Comment by Jkryos** [comment]
Updated DB3K 498.
