### ISSUE TITLE
CORRECTION: THAAD CEC Facility

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2683]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3215

### Summary of Changes

Currently it has only 1 missile per launcher, with 6 launchers it only has 6 THAAD C-2s.  Also there lacks an 8x THAAD C-2 weapon round. 
The datalink prevents 8 rounds plus engagements. 

### Sources

DB 497a

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
