### ISSUE TITLE
Update for Tien Chien II as ship-launched SAM

### ISSUE THREAD

**Issue by platoonthrasher** [PygmalionOfCyprus/cmo-db-requests#2686]
### DB Selector

DB3K

### Affected DBID(s)

3346

### Summary of Changes

The MLU program of Taiwanese La Fayette-class frigate confirmed to select Tien Chien II ( TC-2 N ) missile with local produced 32 turbo VLS instead of Sea Bow 3. The TC-2 N #3831 is already available with #3441 Ta Chiang PGM. It will be **32 cells** on VLS.

### Sources

https://en.wikipedia.org/wiki/Kang_Ding-class_frigate
https://www.taipeitimes.com/News/taiwan/archives/2021/09/02/2003763662
https://en.wikipedia.org/wiki/Sky_Sword_II#Variants
https://www.upmedia.mg/news_info.php?Type=1&SerialNo=161265

**Comment by Jkryos** [comment]
Added DB3K 498.
