### ISSUE TITLE
Add IAIO Qaher-313 (HYPOTETHICAL)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2688]
### DB Selector

DB3K

### Baseline

Aircraft 1905

### Hypothetical

Yes

### Name

IAIO Qaher-313

### Country

Iran

### Service

Air Force

### Number in Service

1x (prototype)

### Length (m)

15.5

### Wingspan (m)

8.0

### Height (m)

4.08

### Empty Weight (kg)

4400

### Maximum Takeoff Weight (MTOW) (kg)

9000

### Crew

1

### Propulsion

2x J-90 OWJ

### Rate of Climb (ft/min)

25000

### Service Ceiling (ft)

49213

### Military/Afterburner Speed (kt)

810 kt

### Cruise Speed (kt)

480

### Supercruise

No

### Ferry Range (nm)

1080

### Sensors

(Hypothetical)
From Request #2514 
1x Mk.1 Eyeball
1x IEI BAYYENAT I

IEI SAIRAN Electronic Warfare suite that included:
1x RWR(Sensor/2919)
1x MAWS(Sensor/2216)
1x ECM Jammer (Sensor/825)

With addition to:
1x Generic IR camera
1x Generic laser designator
![image](https://user-images.githubusercontent.com/99646926/208232703-7891f047-62c8-4f97-a46f-dfcc8d1e5fac.png)

### Mounts

1x Generic chaff/flare dispenser

### Loadout Options

**Air-to-Air**
The aircraft were claimed to be able to carry up to 6x missiles like PL-12. So the loadout is probably
![image](https://user-images.githubusercontent.com/99646926/208232380-c965c9cd-1cf3-4ac0-8472-6168e94f0587.png)

4x PL-12 and 2x Fatter AAM
or
4x R-77 and 2x Fatter AAM
or 
R-27R and 2x Fatter AAM
or
2x Fakour-90 and 2x Fatter

**Air-to Ground**
And the aircraft were also claimed to be able to carry maximum of up to 2x 2000lb bombs and many more for smaller guided bombs.
![image](https://user-images.githubusercontent.com/99646926/208232363-36dd8a87-d8c7-4863-9038-d2b98edcb2bb.png)
Hypothetically speaking, it probably can carry:

2x Qassed-1 and Qassed-3(Copy of AGM-130, 100km range + INS/GPS midcourse instead of datalink) with 2x Fatter AAM
and
4x Yasin guided bomb with 2x Fatter AAM
and
4x Sattar-4 guided bomb with 2x Fatter AAM
and
8x Balaban SDB with 2x Fatter AAM

It were claimed to have Internal weapon bays, so RCS will probably remain the same for all loadouts.
![image](https://user-images.githubusercontent.com/99646926/208232262-fdf855a8-f75a-4c1f-965d-0e2ca6476816.png)
![image](https://user-images.githubusercontent.com/99646926/208232286-9882e539-2d0e-4420-aeff-aa849fc45372.png)

### Comms/Datalinks

UHF Radio [Secure]
VHF Radio [Secure]
AA-10/12 Datalink

### Aircraft Codes

Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Navigation (INS/GPS)

### Comments

Yes i know this is not a real jet (its a meme even), but would be a nice addition for Iran`s aircraft line and OPFOR jets (alongside J-20, SU-57 and SU-75).

The original mockup showed it have 1x medium-sized engine but the prototype model were seen to have 2x smaller engine, some sources has indicated its probably J-90 OWJ, same engines that were used on HESA Kowsar. So its IR signatures is definitely not on par with proper 5th Gen jets at very least.

(original mockup)
![image](https://user-images.githubusercontent.com/99646926/208232099-d23b0edb-147b-493e-a7c4-4aa6844ddac1.png)

(prototype model)
![image](https://user-images.githubusercontent.com/99646926/208232124-f36df8d9-bc60-4109-a9bb-e887141220ab.png)
![image](https://user-images.githubusercontent.com/99646926/208232181-28a9f08c-6db4-4cca-8307-5293e7d09b97.png)

And unfortunately, there is no info regarding its RCS and since it were claimed to be similar to F-117 so its probably a good baseline for the aircraft.
![image](https://user-images.githubusercontent.com/99646926/208232081-4a3f4725-5d97-46ac-80d8-85926f4dd597.png)

### Sources

- https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=1311
- https://en.wikipedia.org/wiki/IAIO_Qaher-313
- https://www.youtube.com/watch?v=dGd0EU-1uYc
- https://fighterjetsworld.com/air/analysis-of-iran-f-313-qaher-stealth-aircraft-is-it-real-or-fake-fifth-generation-fighter/14593/
- https://www.flightglobal.com/iran-reveals-new-qaher-313-stealth-fighter/108652.article
- https://www.globalsecurity.org/military/world/iran/qaher-313.htm
- https://www.airrecognition.com/index.php/news/defense-aviation-news/global-news-2017/april/3407-new-pictures-of-iran-s-qaher-f-313-stealth-fighter-jet-emerged.html

**Comment by capcop98** [comment]
And the "cockpit: Glass cockpit" is possible. Though tbh it`s kinda dissapointing to say at least.
![image](https://user-images.githubusercontent.com/99646926/208233430-f8a1c1af-cab8-4e2d-939a-fa1b383b9706.png)
![image](https://user-images.githubusercontent.com/99646926/208233159-e9c131b7-7835-4339-8b5e-c1a6e2619f43.png)

more image of its internal weapon bay.
![image](https://user-images.githubusercontent.com/99646926/208233280-6577af6a-f511-4ba8-955b-0df99f662d8c.png)

Source: 
- https://www.businessinsider.com/iran-desperately-to-defend-stealth-jet-non-flying-2013-2
- https://www.f-16.net/forum/viewtopic.php?t=22096&p=244979

**Comment by PygmalionOfCyprus** [comment]
As funny as I find this, I don't think it's really worth adding. It's obviously not a real aircraft, just a mockup made to make them look competent. It'd be on par with adding any other fake aircraft proposal scrawled up by a wannabe on the internet. By that standard I have to add a Gundam for Japan:

![image](https://github.com/user-attachments/assets/ee4446c5-48b8-4df5-ac61-d09d861227e3)

**Comment by capcop98** [comment]
Noted, but thanks for checking out this request either way👍
