### ISSUE TITLE
Supercruise

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2689]
### DB Selector

DB3K

### Affected DBID(s)

F-22 variants and some hypothetical aircraft

### Summary of Changes

Super-cruise has also an effect on weapon employment.
When a F-22 flies at Mach 1.7 it can drop a bomb earlier than a F-15E at 520 kts.

Former F-22 Raptor pilot Jim "JB" Brown President & CEO National Test Pilot School describes a rule of thumb at a video:
![Supercruise](https://user-images.githubusercontent.com/60408110/208237261-83e2e890-9e0f-4d88-82d8-48878fb834ef.jpg)

Improved Missile range x1.5
Improved bomb range x2

At present (DB 497) this is not implemented. 
A JDAM is being dropped at the same range for a supercruising F-22 as a normal 520 kts F-15E. Same for AMRAAM employment

Is it possible to program this, because it also influences the survivablilty of these platforms in high threat environments in the air-to-air and A-G realms.

### Sources

https://www.youtube.com/watch?v=lltMfkj1yPU @ 58 minutes in the video

**Comment by PygmalionOfCyprus** [comment]
This is more a sim logic request than a DB request, recommend you post on the main forums.
