### ISSUE TITLE
RPS-42 TASRS radar specs

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2690]
### DB Selector

DB3K

### Affected DBID(s)

#5396

### Summary of Changes

Max detection ranges for UAV's to ships.
[mini_magick20190115-17501-boc9y4.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10251539/mini_magick20190115-17501-boc9y4.zip)

### Sources

https://twitter.com/awes_spad/status/1604022673767649280
https://www.academia.edu/35239235/RPS-42_Radar_System_for_Tactical_Air_Surveillance_RADA_Innovative_Defense_Electronics

**Comment by Jkryos** [comment]
Updated DB3K 498.
