### ISSUE TITLE
RWS and CRWS (RIMS system) for South African aircraft

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2691]
### DB Selector

DB3K

### Hypothetical

No

### Name

RWS or CRWS

### Sensor Generation

Early 1980s

### Range (nm)

-

### Sensor Capabilities

Air Search, Surface Search

### Search/Track Frequencies

C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm, D Band (1-2 GHz) [Old L Band] 15-30 cm, E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm, G Band (4-6 GHz) [Old C Band] 5-7.5 cm, H Band (6-8 GHz) [Old C Band] 3.75-5 cm, I Band (8-10 GHz) [Old X Band] 3-3.75 cm, J Band (10-20 GHz) [Old X Band] 1.5-3 cm

### Lower Frequency (Hz)

700,000,000

### Upper Frequency (Hz)

18,000,000,000

### Comments

This is a preparatory request for a pair of systems that I'm going to refer back to repeatedly. There are two different systems, the **RWS** with a recording function and the **CRWS** without a recording function. I'm not sure what qualifies sensors as 'specific emitter ID', I guess that if you had a recorder then once you had the aircraft home and pulled the tape and gave it to the EWO for a listen, you could get a specific emitter ID, but that's not exactly the prompt in-air identification that Command gives.

The source mentions a button antenna focusing on specific CW threats, I would be very surprised if these threats are not SA-8's Land Roll, SA-6's Straight Flush and SA-3's Low Blow illumination radars. These were the three most significant threats to SAAF tactical air operations in Angola, while SA-2s mostly ended up around the major cities. I don't know if that helps.

I appreciate that my only source for these systems is a single forum post, but that's genuinely all I could find on them after looking for some time.

### Sources

https://www.saairforce.co.za/forum/viewtopic.php?f=2&t=9010

**Comment by PygmalionOfCyprus** [comment]
Handled 502.

**Comment by FrangibleCover** [comment]
To be reopened @PygmalionOfCyprus, sensor 7200 is misspelled "CWRS" instead of "CRWS". Sorry, the rest of the update looks really good! Congratulations to you and your team.

**Comment by PygmalionOfCyprus** [comment]
Fixed 503.
