### ISSUE TITLE
Canada MM 700 Kingston Class

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2697]
### DB Selector

DB3K

### DBID to Copy

2678

### Hypothetical

No

### Name

MCDV 700 Kingston

### Country

Canada

### Service

Royal Canadian Navy

### In Commission

2012

### Number in Service

12x

### Mounts

- remove 40mm/70

### Loadout Options

- Add ability to launch PUMA AE UAV as of 2018 (Additional entry needed for 2018 version)

### Other Changes

- Designation should be MCDV for all entries, not MM
- Onboard degaussing systems added, contract awarded 2011
- Sonar systems upgraded 2012 and comprises:
- L3/Klein K 5500 high definition side scan sonars
- L3/Klein K 3000 dual frequency side scan sonars 
- Deep Ocean Engineering Inc. Phantom 4 remotely operated vehicles

- 2018 - PUMA AE UAV 

-2022 - SEAFOX Mine Disposal Vehicle

### Sources

https://www.naval-technology.com/contractors/simulators/l-3-mapps/pressreleases/pressl-3-mapps-contract/
https://web.archive.org/web/20140316034136/http://blogs.ottawacitizen.com/2012/11/02/sonar-on-the-royal-canadian-navys-mcdvs-to-be-upgraded/
https://stema-systems.nl/wp-content/uploads/2015/08/Klein_System_3000.pdf
https://stema-systems.nl/equipment/klein-5000/
https://mind-technology.com/klein/klein-auv-uuv-system-5000-v2/

PUMA AE UAV
https://www.bloomberg.com/press-releases/2018-02-28/royal-canadian-navy-to-field-aerovironment-puma-ii-ae-with-mantis-i45-sensor-aboard-coastal-defence-vessels

Kraken Minehunting Upgrade
https://www.thedefensepost.com/2022/12/09/canada-navy-minehunting-drone/
https://www.navalnews.com/naval-news/2022/12/kraken-wins-royal-canadian-navy-contract-for-minehunting-program
https://krakenrobotics.com/kraken-awarded-50-million-navy-contract-for-royal-canadian-navy-minehunting-program/
https://www.defenseadvancement.com/news/new-remote-minehunting-disposal-systems-for-royal-canadian-navy/

**Comment by Jkryos** [comment]
Added DB3K 498.

**Comment by cdnice55** [comment]
Just found this article that states that they have access to Wideband Global SATCOM (WGS) system with fitted (AN/USC-69(V3)) 

https://publications.gc.ca/collections/collection_2019/mdn-dnd/D12-21-88-eng.pdf pg 13 article begins, Kingston mention on page 15.
