### ISSUE TITLE
ATGMs Cannot Shoot

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#2699]
### DB Selector

DB3K

### Affected DBID(s)

Ground Units 332 and 333, and Facilities 3473, 3474, and 2219.

### Description of Problem

The FGM-148 Javelin missiles in the two ground units, and the AT-14 Spriggan missiles in the facilities show the following, and cannot shoot: "Automatic fire is NOT possible, Weapons must detect target prior to firing."

Unless I am making a silly error, this is a bug. A Javelin section, Facility 2216, with the same (weapon ID 2937), CAN shoot under the same conditions. A generic infantry platoon with the same (weapon ID 2937) added to it CAN shoot, however it CANNOT shoot an added AT-14 Spriggan (weapon ID 2938). Having tested similar missiles, they all claim to be able to shoot happily.

See scenario hopefully attached.

[ATGM_test.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10282791/ATGM_test.zip)

### Recommended Fix

Investigation required.

**Comment by PygmalionOfCyprus** [comment]
Under investigation.

**Comment by PygmalionOfCyprus** [comment]
Sorry for the stupid long wait on this. Passed to devs as this doesn't appear to be a DB bug and the issue is getting worse (now none of the platforms can fire).
