### ISSUE TITLE
#3568 Tughril Pennant and Mount Correction

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#270]
### DB Selector

DB3K

### Affected DBID(s)

3568

### Summary of Changes

Pennant number is FFG-261 (1st link)
Missile fit is export YJ-12 export designation CM-302. See link 1-3 on that.

### Sources

https://twitter.com/aviation07101/status/1464772498923442183/photo/1
https://twitter.com/aviation07101/status/1464774433072156675
https://en.wikipedia.org/wiki/YJ-12

**Comment by Jkryos** [comment]
Updated DB3K 493. I'm going to keep an eye on this sources cant decided if loads YJ-83 or YJ-12, the YJ-12 has been added.
