### ISSUE TITLE
Bradley TOW Reload Time

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#2700]
### DB Selector

DB3K

### Affected DBID(s)

All Ground Unit Bradley IFVs.

### Summary of Changes

Ground Unit Bradley IFVs take about twelve minutes to reload their TOWs. This should be 30 seconds, or a minute, or whatever you think suitable.

Incidentally, the Facility versions have no magazines, hence never reload. A different can of worms, perhaps.

### Sources

See attached scenario. Set to fire speed, playing as target side, with missile contact creating a pop-up message and pausing the game for quick results.
[Bradley_IFV_TOW_test.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10282819/Bradley_IFV_TOW_test.zip)

**Comment by Jkryos** [comment]
Fixed DB3K 499.
