### ISSUE TITLE
Increase ZIF-122 (SA-N-4 twin launcher) reload time

### ISSUE THREAD

**Issue by ddranidis** [PygmalionOfCyprus/cmo-db-requests#2701]
### DB Selector

Both

### Affected DBID(s)

Mounts #405, #891 & #894 in DB3K - Mounts #277 & #2711 in CWDB

### Summary of Changes

See related discussion on MG Tech Support: https://www.matrixgames.com/forums/viewtopic.php?p=5063611#p5063611

Current mount-mag ROF is 6 for all applicable mounts (ie. 12 sec reload time for both missiles?). Public sources suggest a 16-21 sec reload time.

### Sources

https://weaponsystems.net/system/464-M-4%20Osa-M

**Comment by Quark73CMO** [comment]
If not already implemented please please consider "A single target is engaged at a time." from Guidance section in source above.
acc. https://www.army-technology.com/projects/9k33-osa-air-defence-missile-system-russia/ 
it is able to shoot up to two misslies on a single target. (at least the army version).

additional source:

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
