### ISSUE TITLE
Wrong warhead for some Grad rockets

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2704]
### DB Selector

DB3K

### Affected DBID(s)

A number of DB3k rockets.

### Summary of Changes

The standard 122mm rocket should have a 6.4kg TGAF-5 fragmentation warhead, with the entire warhead unit weighing 18.4kg, Warhead 970 on Weapon 2752's Grad rocket seems suitable.

The following weapon entries are 122mm ground launched rockets with a warhead that seems wrong:
- 261, Generic 122mm - 100kg, definitely wrong! Generally its stats are weird, it's not 122mm, it's very short and it's very heavy
- 468, Type 81H - Clone of Generic
- 3711, Sakr - Has the BK 90 glide bomb warhead
- 1359, 9M22U Grad - Has the BK 90 warhead too
- 3887, Fire Dragon - Has a 20kg warhead, possibly a generous rounding of the 18.4kg warhead all-up weight, appears to be a normal 122mm rocket
- 3631, LYNX - As Fire Dragon
- 2847, Roketsan Jobaria - Has an 18kg warhead, again I think this is the all-up weight
- 2753, Type 81 - As Fire Dragon
- 2824 Langusta, as Jobaria

### Sources

http://characterisationexplosiveweapons.org/studies/annex-a-122-mm-mbrl/
https://www.armyrecognition.com/china_artillery_vehicles_and_weapon_systems_uk/sr5_sr-5_guided_multiple_launch_rocket_system_gmlrs_mlrs_122mm_220_mm_technical_data_sheet_specifications_pictures_video_11601162.html
Database

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
