### ISSUE TITLE
Taiwan Blk 20's out of service date

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2708]
### DB Selector

DB3K

### Affected DBID(s)

2185, 3424

### Summary of Changes

Final Blk 20 shipped to the factory for upgrade. Add the out-of-service date of 2022 to 2185 and 3424

### Sources

https://www.scramble.nl/military-news/final-rocaf-block-20-f-16-to-aidc

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
