### ISSUE TITLE
UAE Falcon Eye satellite

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2711]
### DB Selector

DB3K

### Hypothetical

No

### Series Name

Falcon Eye 2

### Satellite Type

IMGSAT

### Country

UAE

### In Commission

3 dec 2020

### Weight (kg)

1190 kg

### Is Geostationary

No

### COSPAR ID

COSPAR ID 2020-090A

NORAD ID 47226

### Launch/Comm. & Decom./Deorbit Date(s)

Launch date: 3 dec 2020
[https://middle-east-online.com/en/uae-launches-falcon%E2%80%99s-eye-satellite-space](url)

### TLE

Inclination	97.848°
Eccentricity	0.00016
RA ascending node	4.729 hr
Argument perihelion	100.441°
Mean anomaly	259.763°
Orbital period	96.977 min
Epoch of osculation	24 Dec 2022, 22:53

Min Altitude | 620.0 km
Mean Altitude | 621.1 km
Peak Altitude | 622.2 km

### Sensors

Probably based on helios-2 of France (DB61 - Helios France-2004)
[https://thepeninsulaqatar.com/article/23/07/2013/uae-buys-2-french-helios-surveillance-satellites](url)
[https://www.business-standard.com/article/pti-stories/uae-buys-two-french-surveillance-satellites-113072200988_1.html](url)

### Comments

Falcon Eye 1 failed to get into orbit in 2019.

### Sources

[https://in-the-sky.org/spacecraft.php?id=47226](url)
[https://space.skyrocket.de/doc_sdat/falcon-eye-1.htm](url)

**Comment by PygmalionOfCyprus** [comment]
Added 508 along with every single other satellite currently in orbit.
