### ISSUE TITLE
#3245 Cobra

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2712]
### DB Selector

DB3K

### Affected DBID(s)

#3245 Cobra

### Summary of Changes

frequency: | C-Band 4-8 GHz
beamwidth: | β=1,8° ε=1,4°
[https://www.radartutorial.eu/19.kartei/04.battle/karte003.en.html](url)

The COBRA antenna can be mechanically rotated in azimuth by ± 90 degrees with respect to
the longitudinal axis of the vehicle and in elevation from –5° to + 35° relative to a plane perpendicular to the shelter bottom surface .
![Clipboard02](https://user-images.githubusercontent.com/60408110/209726415-99d76e55-5854-467c-ad86-66b266f3a6ee.jpg)

COBRA can be brought into action in less than 15 minutes. The encamp time includes the time
taken to load the Digital Terrain Map (DTM) from hard disk, and to complete COBRA Initialisation
and mission parameter definition. It is possible to come out of action within 5 minutes.

**Location of Jammers**
 During passive non-transmitting periods, COBRA provides azimuth and elevation direction for
jammers within the passive observation search sector using the antenna mainlobe; in addition,
information on jamming mode, jamming strength, presence of mainlobe or sidelobe jamming,
and jammed frequency channels is gathered and stored.
 During radar transmissions a second means of gathering information on non-responsive and
responsive and moving jammer platforms is provided.

**COBRA Configuration (See 3.1)**
Single vehicle, no levelling or stabilisation required
Operator cabin complete with Operator and C3 Consoles
On-board Prime Power Unit
On-board, User Artillery Integrated Command and Control System
On-board Inertial Navigation System (Laser Gyro) with GPS option
Air-conditioner with NBC filtration (Gas, Chemicals and Particles)
Shelter protected against shell fragments and small arms fire
**COBRA Missions (See 3.2.1)**
Hostile Battery Location:
Location of Battery Centre / Battery width and Orientation /
Weapon Classification / Impact Area / Weapon and Area Priority
Friendly Fire Registration and Adjustment:
Location of fall of shot / Adjustment parameters
Range Modes (See 3.2.2.1)
Short / Standard / Long 20, 30, 40 Km
Coverage 1200 Km2 / Detection Coverage is 90 Degrees out to >40 kilometres, corresponding to 1200 Km2
Operating Modes
Automatic – missions directed and results transmitted via C3
 link
Autonomous – no connection with C3
 link, Operator defines
missions
COBRA Deployment (See 3.2.4)
Crew size 1–3 soldiers
Encamp time 5–15 minutes
Decamp time 3–5 minutes
Use of on-board Inertial Navigation System
Background Digital Maps and Digital Terrain Maps (DTM)
Computation of Terrain Mask from DTM
Priorities (See 3.2.5)
Mission Priority
Location Zone Priority
Weapon System Class Priority
Location of Batteries See (3.2.6)
Battery Location Criteria
Number of Weapons 1–8
Correlation Radius 100–200m
13
Correlation Time 10–999secs
Location Rate >40 batteries in 2minutes
Location Rate Modes Normal, High
Adjustment/Registration of Friendly Fire (See 3.2.7 )
Adjustment mission simultaneously with Location Mission
Accuracy <15Km – 50m CEP
>15Km – 0.35% range
Transportability (See 3.2.9)
By air, sea and rail (or using a suitable spare flat-bed vehicle)
EURO-ART INTERNATIONAL PROPRIETARY INFORMATION Page 13
Additional Data
Shelter size 600x250x210 cm
Prime Power Unit Size 80x250x200 cm
Vehicle platform (Interface Frame) dimensions 750x250 cm
Vehicle Payload 10 tons
Shelter weight Approx 8000
Prime Power Unit Weight 1900 Kg

**Processing:**
Agility in waveform and frequency (C-band)
Digital pulse compression / doppler filtering
Clutter map, CFAR and censor map
Target recognition – weapon classification
Battery location, Impact locations, Battery width and orientation
Priority of weapons and area
Rate of acquisition greater than 240 weapons in less than 2 minutes

All better readable here: [https://www.hensoldt.net/fileadmin/HENSOLDT_2019/Products/Radar_IFF_Datalink/0407_15_Cobra_16S_EN.pdf](url) 
This Pdf is also attached as .zip file.

**Users extra from DB497:**
Qatar 2x from 2020 onwards
UAE 3x from 2010 and 3 extra from 2019 onwards, six in total.
Turkey 2x (second hand from Germany from 2006 onwards)
Source: Sipri Arms Register
[https://www.edrmagazine.eu/hensoldt-modernizes-cobra-artillery-location-radars-2](url)

Ukraine 1x from Germany
[https://www.armyrecognition.com/defense_news_may_2022_global_security_army_industry/germany_plans_to_supply_a_cobra_counter-artillery_radar_to_ukraine.html](url)
[https://www.oryxspioenkop.com/2022/09/fact-sheet-on-german-military-aid-to.html](url)

[Trade-Register-1990-2021.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10310961/Trade-Register-1990-2021.zip)
[0407_15_Cobra_16S_EN.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10310963/0407_15_Cobra_16S_EN.zip)

### Sources

[https://www.hensoldt.net/fileadmin/HENSOLDT_2019/Products/Radar_IFF_Datalink/0407_15_Cobra_16S_EN.pdf](url)
[https://www.occar.int/programmes/cobra](url)
Sipri Arms Trade registers

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
