### ISSUE TITLE
QUICKSINK GBU-31 guidace kit

### ISSUE THREAD

**Issue by Karthex** [PygmalionOfCyprus/cmo-db-requests#2714]
### DB Selector

DB3K

### Baseline

GBU-31

### Hypothetical

Yes

### Name

QUICKSINK

### Length (m)

3.77

### Width/Span (m)

64.3

### Diameter (m)

37

### Weight (kg)

981

### Range (nm)

~13

### Target Altitude / Depth (ft)

45,000 ASL

### Warhead

2000lbs 

### Targets

Surface Vessel

### Sensors

1x visual seeker
1x GPS guidance
1x INS system

### Weapon Codes

Weapon - INS Navigation, Uses GPS

### Comments

Specifically, this weapon is designed to land a few meters off the keel of a surface vessel, and detonate just under the surface of the water. This creates a powerful shockwave under the water that is designed to crack the hull of the target vessel.

### Sources

https://afresearchlab.com/technology/quicksink/
https://afresearchlab.com/news/afrl-technology-makes-new-weapon-for-sinking-ships-a-reality/
https://www.acc.af.mil/News/Article/3016733/afrl-technology-makes-new-weapon-for-sinking-ships-a-reality/

**Comment by tbrandon517** [comment]
Quicksink is already in the DB

**Comment by Karthex** [comment]
Thanks for the links. My numerous DB searches came up fruitless.
