### ISSUE TITLE
PL-15 Climb Rate and performance details

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2716]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3413 3896

### Summary of Changes

Though pl-15's top speed has changed, its cruise speed in band 1~3 and climb rate remains unchanged which might cause problem in simulation.

It might be suitable to change these figures:

Band 1, cruise speed: 1540 to 1910kt
Band 2, cruise speed: 1680 to 2070kt
Band 3, cruise speed: 2070 to 2560kt
climb rate: 1949ft/min 594m/s to 2175ft/min 663m/s

### Sources

No specific source. Just reasonable speculation on speed variation after change of top speed

**Comment by LuigiP57** [comment]
#2469

**Comment by PygmalionOfCyprus** [comment]
Fair, handled 499.
