### ISSUE TITLE
Provide Missile Approach & laser Warning to CH-47F of Spain

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2719]
### DB Selector

DB3K

### Affected DBID(s)

#5556 CH-47F Chinhook Spain 2022

### Summary of Changes

The solution also incorporates Indra’s new InWarner sensor, equipped with a missile alerter and a laser alerter, which detects whether any designator has acquired the helicopter as a target. The integration of both elements makes it possible to achieve full situational awareness and increases the effectiveness in activating countermeasures to neutralize the attack.

### Sources

[https://www.edrmagazine.eu/indra-to-supply-chinook-ch-47f-with-the-maximum-survival-capability](url)

[https://www.army-technology.com/news/spanish-army-ch47f-helicopter/](url)

**Comment by PygmalionOfCyprus** [comment]
Fixed 499, InWarner sensor group was already present but pointing accidentally to the ALR-400 components instead of the actual LWR/MAWS.
