### ISSUE TITLE
New Weapon AT-16 Scallion B [9M127-1 Vikhr-M] will require amended post 2013 Russian KA-52 loadouts.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#272]
### DB Selector

DB3K

### User(s)

#2929 - Ka-52 Hokum B [Alligator] (Russia [1992-] - 2012) #5072 - Ka-52M Hokum B (Russia [1992-] - 2022) #4988 - Ka-52 Hokum B [Nile Crocodile] (Egypt - 2018) 

### Weapons Carried

12x AT-16 Scallion B [9M127-1 Vikhr-M]
40x S-8KO 80mm Rocket [HEAT]

**To replace load out #15679 or just copy over with new weapon?**
 *AAM Igla-V are rarely if ever used although it is within the load capacity.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

220

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

This is a straight update to the existing Vikhr load outs to replace the old Vikhr 9M127 with the Vikhr-M 9M127-1 which has improved range (up from 8km to 10-12km) and an improved warhead.  
As production started in the 2013 region the platforms effected are circa 2012 KA-52's including the exported Egyptian versions.

### Sources

https://en.topwar.ru/183270-prishlas-po-nravu-egiptjanam-zarubezhnaja-pressa-o-zakaze-rossijskoj-ptur-vihr-1.html
https://en.topwar.ru/185232-protivotankovuju-aviacionnuju-raketu-vihr-adaptirujut-k-vertoletam-mi-28nje-i-mi-35p.html
https://bs.atomiyme.com/vihor-raketa-protivoklopna-raketni-sistem/
https://muzruno.ru/biznes/126218-vihrushka-raketa-sistema-za-protivoraketna-raketa.html
https://tr.topwar.ru/186157-udary-po-slabym-mestam-bronetehniki-izlishni-ispanskij-obozrevatel-o-rossijskoj-rakete-vihr-1.html
https://youtu.be/DobAdQEaBmY

**Comment by PygmalionOfCyprus** [comment]
Had to add the Vikhr-1!

Anyway, new ~2015 version of the Ka-52 built with the new Vikhrs and loadouts replaced on all the helicopters after that date (which is all except DBID 2929). Russians still have the old Vikhr loadouts in the DB but I just edited the existing Egyptian ones since I figure they didn't buy old kit.
