### ISSUE TITLE
Radar for AMX A-11

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2720]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Aircraft 605, 946, 1762, 947

### Summary of Changes

Italian AMXs are fitted with a radar, a locally manufactured EL/M-2001B unit used for gunnery control and ground attack. Some sources claim it's modified, but the capabilities look basically the same as Sensor 671 so...

That being said, both the 2001B and 2001 have the exact same stats in the database, perhaps the 2001B should be improved.

### Sources

https://nibbio14.altervista.org/radar.php
https://janes.migavia.com/inter/amx/amx.html
https://www.airforce-technology.com/projects/amx-fighter-bomber/

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
