### ISSUE TITLE
UPDATE: Trumpet Series

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2724]
### DB Selector

DB3K

### Affected DBID(s)

Sat 68

### Summary of Changes

USA 278 
2017-09-24
2017-056A
1 42941U 17056A   22059.64722120 0.00000000  00000-0  00000-0 0    04
2 42941  63.4519 325.7473 7170680 267.7174  92.2825  2.00619834    05

### Sources

www.space-track.org

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
