### ISSUE TITLE
ASM HAWC Subsonic

### ISSUE THREAD

**Issue by EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE2** [PygmalionOfCyprus/cmo-db-requests#2729]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3663

### Summary of Changes

ASM HAWC has a speed of Mach ~2.5 even though it is a "Hypersonic airbreathing weapon concept"

### Sources

![Screenshot_20230102_103415](https://user-images.githubusercontent.com/121797658/210220093-e091d3e2-059a-4a05-9ce0-2a9682f78d0f.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499. Also changed engine to scramjet and warhead to kinetic.
