### ISSUE TITLE
Wellington BH.7 PCF for Britain

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2735]
### DB Selector

CWDB

### DBID to Copy

CWDB Ship 2392

### Hypothetical

No

### Name

Wellington BH.7

### Country

United Kingdom

### Service

Royal Navy

### In Commission

1970-1973

### Number in Service

1x, Trials

### Sensors

1x Decca (Generic)

### Mounts

Same

### Other Changes

When first acquired, the Royal Navy's BH.7 was trialled as a fisheries protection vessel and coastguard patrol craft.

### Sources

https://link.springer.com/content/pdf/bbm:978-1-4614-0869-7/1.pdf
https://web.archive.org/web/20090502200342/http://www.hovercraft-museum.org/bh7.html
https://en.wikipedia.org/wiki/British_Hovercraft_Corporation_BH.7

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
