### ISSUE TITLE
Hypothetical Wellington BH.7 PCFG

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2736]
### DB Selector

CWDB

### DBID to Copy

CWDB Ship 2392

### Hypothetical

Yes

### Name

Wellington BH.7

### Country

United Kingdom

### Service

Royal Navy

### In Commission

1970

### Number in Service

Not Built

### Sensors

1x Decca (Generic)
1x RTN-10X
1x Generic TV Director
1x UA-8/9 Porker

### Mounts

12.7mm removed
7.62mms removed

2x MM.38 Dual-Box Exocet (on sides, as Iranian BH.7 missile mod)
1x GWS.24 Seacat Triple (on midships superstructure, can't fire aft)
1x 20mm/70 Oerlikon Mk.7 (in nose, replacing ramp, forward arcs only)
2x Corvus launcher

### Other Changes

This is a fairly suppositional option, based on BHC proposals for a combat armed BH.7 which was shopped around in the early 70s but never actually built. I've said this is for the UK, but Iran were the most significant operator of the BH.7, the design appears to have been aggressively marketed towards the US and as an export system it could turn up just about anywhere. Sensors and weapons are systems exported by the UK in the period.

Remove the cargo capacity, all of that area is now the ops room.

### Sources

https://web.archive.org/web/20090502200342/http://www.hovercraft-museum.org/bh7.html
https://link.springer.com/content/pdf/bbm:978-1-4614-0869-7/1.pdf
https://books.google.co.uk/books?id=1GqN4QA7taMC&pg=RA10-PA30&redir_esc=y#v=onepage&q=hovercraft&f=false

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
