### ISSUE TITLE
Wellington BH.7 PCFG for Iran

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2737]
### DB Selector

DB3K

### DBID to Copy

DB3k ship 2975

### Hypothetical

No

### Name

Wellington BH.7

### Country

Iran

### Service

Navy

### In Commission

2006-present

### Number in Service

4x

### Mounts

Add 2x Dual C-802 launchers
Cargo capacity might be retained?

### Sources

https://www.globalsecurity.org/military/world/iran/wellington.htm
https://twitter.com/Kobaz4/status/1150678304611078144

**Comment by PygmalionOfCyprus** [comment]
Was added as part of our ongoing flashpoint review for Iran, should be in 498/498a.
