### ISSUE TITLE
Update - Romania - F 221 Regele Ferdinand [Type 22 Batch 2] - 2005

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2738]
### DB Selector

DB3K

### Affected DBID(s)

ship 2021

### Summary of Changes

Add Oto Melera Super Rapido 76mm gun

### Sources

https://www.seaforces.org/marint/Romanian-Navy/F221-Regele-Ferdinand.htm

![image](https://user-images.githubusercontent.com/99599482/210278889-bc8ce944-8f7d-4124-bb99-6ce12fdda7d2.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
