### ISSUE TITLE
Reduce damage points of Surveillance and NGS Buoys 

### ISSUE THREAD

**Issue by qrk** [PygmalionOfCyprus/cmo-db-requests#2739]
### DB Selector

DB3K

### Affected DBID(s)

3107, 347

### Summary of Changes

Surveillance Buoy (LLTV) and NSG Buoy (Generic) seem to have abnormally high damage points. Request this value be reduced to 10 damage points to more accurately reflect the size and lack of armor of the units. An image, with persons for size reference, are attached. In the references, ocean-ops.org provides an overview of ocean moored buoys (with pictures), and the attached PDF has technical specifications of OSSM buoys, which indicate the size of the devices. 

<img width="882" alt="db examples 2" src="https://user-images.githubusercontent.com/3251556/210364024-bca6912e-46a9-4939-8b37-77f950437f4b.png">
<img width="875" alt="db examples" src="https://user-images.githubusercontent.com/3251556/210364026-c169406f-bcd2-49e8-99ae-0d35c705f51c.png">
![TAO_Service_small](https://user-images.githubusercontent.com/3251556/210364027-827173ee-d0bc-43e1-b668-321ffc3d9681.png)

### Sources

https://www.ocean-ops.org/dbcp/platforms/types.html
https://www.whoi.edu/cruiseplanning/files/1507916982140_12962_3204-00901_Cruise_Plan_Coastal_Pioneer-9_2017-10-12_Ver_0-04_DRAFT.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
