### ISSUE TITLE
CA Radar (EL/M-2084 STAR) x10

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#274]
### DB Selector

DB3K

### DBID to Copy

2485

### Hypothetical

No

### Name

Radar (AN/MPQ-504 Medium Range Radar) x10

### Country

Canada

### Service

Canadian Army

### In Commission

2020

### Other Changes

Canada has purchased ten MMR Radars. They are expected to enter operational service late 2020 with the designation AN/MPQ-504.[[11]](https://en.wikipedia.org/wiki/EL/M-2084#cite_note-11)

### Sources

https://en.wikipedia.org/wiki/EL/M-2084#ELM-2248_MF-STAR
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Canadian_Army#Field_artillery

**Comment by PygmalionOfCyprus** [comment]
Added 494.
