### ISSUE TITLE
South Africa Meko A-240SAN Valour Class

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2741]
### DB Selector

DB3K

### Affected DBID(s)

1439

### Summary of Changes

- Denel Umkhonto-IR VLS SAM showing as 16 cell but should be 32. Combat Fleets of the World is showing 4x8 cell and Janes 2012-13 shows 32 cells.

### Sources

- Naval Institute Guide to Combat Fleets of the World 16th Edition, pg. 665
- Janes 2012-13, pg 744

**Comment by KLABDB3K** [comment]
https://thaimilitaryandasianregion.wordpress.com/2015/11/26/valour-class-frigate-south-african-navy/
![20230104_172332](https://user-images.githubusercontent.com/99494755/210613572-3755a6ea-ed0a-4d1f-86c0-484f46d422f3.jpg)

**Comment by cdnice55** [comment]
I saw the torpedo tubes referenced in Combat Fleets like in your link but Jane's did not have them listed so I did not add them. Double source now for 2 twin 324mm TT.

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
