### ISSUE TITLE
US Block 4 F-35s will be equipped with the "AN/APG-85" new radar

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#2742]
### DB Selector

DB3K

### Affected DBID(s)

US F-35A/B/C Block 4

### Summary of Changes

The new AN/APG-85 advanced active electronically scanned array radar will be compatible with all variants of the new Block 4 

![This is an image](https://www.thedrive.com/uploads/2022/12/31/FlFNBMfaEAAaGxm-scaled.jpeg?auto=webp&optimize=high&quality=70&width=1200)

![This is an image](https://pbs.twimg.com/media/FlFI6RqakAAnVAG?format=jpg&name=900x900)

### Sources

https://www.thedrive.com/the-war-zone/f-35-will-get-new-radar-under-massive-upgrade-initiative

**Comment by HunterDNiu** [comment]
Blk 4 Lot 17.

**Comment by jun5896** [comment]
https://theaviationist.com/2023/01/09/the-f-35-will-get-a-new-radar/
https://twitter.com/MIL_STD/status/1610621839797276678?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1610622523624030208%7Ctwgr%5E11396043b6e2dbbee20add1a3cf08a9efe4a8dd2%7Ctwcon%5Es2_&ref_url=https%3A%2F%2Ftheaviationist.com%2F2023%2F01%2F09%2Fthe-f-35-will-get-a-new-radar%2F

Updated news about AN/APG-85 radar.

**Comment by ddranidis** [comment]
https://www.airandspaceforces.com/northrop-grumman-reveals-its-developing-the-f-35s-new-radar/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
