### ISSUE TITLE
Add CIRCM to US AH-64E from 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2743]
### DB Selector

DB3K

### Affected DBID(s)

5280

### Summary of Changes

Swap out the AN/ALQ-212 ATIRCM with sensor 6412 CIRCM

### Sources

https://www.thedrive.com/the-war-zone/army-apaches-are-now-flying-with-new-infrared-missile-thwarting-lasers

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
