### ISSUE TITLE
Add C-704 Loadout to Iranian F-4E- 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2744]
### DB Selector

DB3K

### User(s)

Iranian F-4E 

### Weapons Carried

Can Copy #601 and swap in the C-704
2 C-704
2 AAM 
1 AN/ALQ-101 ECM
2 370 Gallon Tanks

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://twitter.com/mhmiranusa/status/1609259884234657800?cxt=HHwWkMC-8dTVntUsAAAA
https://twitter.com/i/status/1609259884234657800
https://twitter.com/missilito/status/698513098622312448

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
