### ISSUE TITLE
Add 4 Maverick Loadout to Iranian F-4Es

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2745]
### DB Selector

DB3K

### User(s)

1308,1309, 

### Weapons Carried

4 AGM-65A
2 370 Gallon Droptanks
1 AN/101 ECM Pod

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

Yes

### Sources

https://commons.wikimedia.org/wiki/File:Iranian_F-4E_Phantom_II_armed_with_AGM-65_Maverick.jpg
https://hushkit.net/2020/09/11/flying-fighting-the-f-4-phantom-ii-in-the-iran-iraq-war-interview-with-iranian-air-force-brig-general-rtd-alireza-namaki/
http://aviadejavu.ru/Images6/AN/AN19-5/87-1.jpg

**Comment by Jkryos** [comment]
Added DB3K 499.
