### ISSUE TITLE
Iranian Alvand Frigate SSM update 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2746]
### DB Selector

DB3K

### Affected DBID(s)

3753

### Summary of Changes

Swap out twin  C-802 mounts for quads

### Sources

https://twitter.com/IranDefense/status/1609612425380171777/photo/1
https://twitter.com/IranDefense/status/1609612425380171777/photo/2
https://twitter.com/IranDefense/status/1573366982124228608?cxt=HHwWgMC-7eS73NUrAAAA

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
