### ISSUE TITLE
Canada CT-146 Outlaws [Bell 412CF]

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2748]
### DB Selector

DB3K

### DBID to Copy

4610 DB3K

### Hypothetical

No

### Name

CT-146 Outlaws [Bell 412CF]

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2007-

### Number in Service

9x

### Sensors

- 1x Generic Weather Radar
- 1x Mk1 Eyeball

### Loadout Options

- Ferry 250nm
- Training 190nm

### Other Changes

CH-146's transferred to Allied Wings, on civil register, on 26 January 2007, for use as trainers at No. 3 Canadian Forces Flying Training School at Southport, Manitoba.

### Sources

http://www.rwrwalker.ca/post_int.html
https://en.wikipedia.org/wiki/Bell_412#Variants
https://www.canada.ca/en/air-force/services/aircraft/412cf.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
