### ISSUE TITLE
Canada CH-139 Jet Ranger III

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2750]
### DB Selector

DB3K

### DBID to Copy

5298

### Hypothetical

No

### Name

CH-139 Jet Ranger III [AB.206B-3]

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1981-

### Number in Service

13x

### Sensors

- 1x Mk1 Eyeball

### Mounts

- None

### Loadout Options

Same as #5298

### Sources

http://www.rwrwalker.ca/CH139_detailed.htm
https://www.canada.ca/en/air-force/services/aircraft/ch-139.html

![1649047802732](https://user-images.githubusercontent.com/99632305/210710963-3db294d7-9c8b-422a-892e-56aa8abfe69b.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
