### ISSUE TITLE
Canada Grob G 120A

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2751]
### DB Selector

DB3K

### DBID to Copy

5743 DB3K

### Hypothetical

No

### Name

CT-102 Grob Astra [Grob G 120A]

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1999-

### Number in Service

13x

### Sensors

- Mk1 Eyeball

### Mounts

None

### Loadout Options

- Training

### Other Changes

The Grob-G120A is the primary flight aircraft used in the RCAF for pilot training. This low-wing, aerobatic aircraft is the aircraft of choice in the first phase of flying for pilot candidates of the RCAF. 

### Sources

https://www.silverhawkauthor.com/post/canadian-warplanes-5-kf-aerospace-grob-120-a
https://www.canada.ca/en/air-force/services/aircraft/g120a.html

![1649047837389](https://user-images.githubusercontent.com/99632305/210712145-e356c129-5180-4f05-a96b-b2e8f143d353.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
