### ISSUE TITLE
Canada King Air 350

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#2752]
### DB Selector

DB3K

### DBID to Copy

3243

### Hypothetical

No

### Name

BE-350 King Air

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2

### Sensors

- Mk1 Eyeball

### Mounts

- None

### Loadout Options

- Ferry, 1765km
- Passengers 8x, 1400km
- Cargo 1 ton,  1400km

### Other Changes

The BE-350 King Air is used for passenger transport and pilotproficiency missions. These leased aircraft are primarily used by new pilots to gain valuable air mobility–operations experience before being posted to an operational squadron in Canada.

The BE-350 King Air provides flexible transport services for Royal Canadian Air Force personnel and light cargo.

### Sources

https://www.canada.ca/en/air-force/services/aircraft/be-350.html

![be-350-king-air-fact-sheet-image](https://user-images.githubusercontent.com/99632305/210715493-31c13c5b-6d83-43a3-afa0-b0bbb3c939fb.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
