### ISSUE TITLE
ADDITION: Dove Satellites of Planet Lab

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2753]
### DB Selector

DB3K

### Affected DBID(s)

Satellite 111

### Summary of Changes

Add the Dove series satellites of Planet lab, similar to the Skysat. 
[Planet Lab Dove(01-05-23).csv](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10357309/Planet.Lab.Dove.01-05-23.csv)

### Sources

www.space-track.org
https://en.wikipedia.org/wiki/Planet_Labs#Dove

**Comment by PygmalionOfCyprus** [comment]
Should this be a new satellite entry rather than additions to the SkySat series? Seems so.

**Comment by HunterDNiu** [comment]
> Should this be a new satellite entry rather than additions to the SkySat series? Seems so.

Oh yep that's right.
