### ISSUE TITLE
CORRECTION: Improper Weapon Codes

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2754]
### DB Selector

DB3K

### Affected DBID(s)

Various. 

### Summary of Changes

-SM-3 series, incl. weapons 906, 1198, 2692, 3256; 
GBI series, incl. weapons 1197, 3143, 3144; 
SC-19, 3447
Arrow 3, Weapon 3278: 
Add weapon codes, if missing: 2003, 4010, 6111, 6130, 6132, 6201, 9999, and delete any conflicting ones. 

-THAAD series, 857, 893, 3590; 
PAC-3, 1150 and 3207: 
Add weapon codes, if missing: 2003, 6129, 6130, 6133, 9999, and delete any conflicting ones. 

### Sources

DB 497a.

**Comment by PygmalionOfCyprus** [comment]
Not all of these codes do what you think they do and some of them are contradictory, so I didn't add those, but I did implement the requested capabilities where possible.
