### ISSUE TITLE
AM.3CM Bosbok for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2756]
### DB Selector

Both

### Baseline

CWDB 1991, Bird Dog

### Hypothetical

No

### Name

AM.3CM Bosbok

### Country

South Africa

### Service

Air Force

### In Commission

1973-1992

### Number in Service

40x

### Length (m)

8.73

### Wingspan (m)

11.73

### Height (m)

2.72

### Empty Weight (kg)

1080

### Maximum Takeoff Weight (MTOW) (kg)

1700

### Payload Weight (kg)

360

### Crew

2

### Propulsion

1x Lycoming O-480 340hp (GSO-480-B1B6)

### Rate of Climb (ft/min)

1400

### Service Ceiling (ft)

27600

### Military/Afterburner Speed (kt)

150

### Cruise Speed (kt)

133

### Supercruise

No

### Ferry Range (nm)

530

### Endurance (min)

345

### Takeoff / Landing Distance (m)

85

### Fuel Capacity (kg)

?

### Sensors

Mk.1 Eyeball

### Mounts

-

### Loadout Options

- Forward Observer
- Target Marking - 68mm SNEB smoke rockets used, I suspect 12x (two pods of 6, same as the ones on Impala)
- Light Strike - 4x Weapon 1692, Generic 100kg GPB

### Comments

Very heavily used by the SAAF throughout the Border War, and allegedly horribly underpowered for the job it was asked to do.

### Sources

https://www.saairforce.co.za/the-airforce/aircraft/10/am-3c-bosbok
https://en.wikipedia.org/wiki/Aermacchi_AM.3

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
