### ISSUE TITLE
Atlas C.4M Kudu for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2757]
### DB Selector

Both

### Baseline

CWDB 4079, AL-60B

### Hypothetical

No

### Name

C.4M Kudu

### Country

South Africa

### Service

Air Force

### In Commission

1974-1991

### Number in Service

40x or more

### Length (m)

9.04

### Wingspan (m)

13

### Height (m)

3.25

### Empty Weight (kg)

1230

### Maximum Takeoff Weight (MTOW) (kg)

2040

### Payload Weight (kg)

650

### Crew

1

### Propulsion

1x Lycoming O-480 340hp (GSO-480-B1B3)

### Service Ceiling (ft)

27600?

### Military/Afterburner Speed (kt)

129

### Cruise Speed (kt)

111

### Supercruise

No

### Ferry Range (nm)

700

### Takeoff / Landing Distance (m)

260 landing

### Sensors

1x Mk.1 Eyeball

### Mounts

-

### Loadout Options

- Transport, 7x passengers
- Cargo, 0.5 ton no drop
- Cargo, Dangerously Overloaded!, 1 ton no drop
- Forward Observer

### Sources

https://en.wikipedia.org/wiki/Aermacchi_AL-60
https://www.saairforce.co.za/the-airforce/aircraft/45/c-4m-kudu
EQUIPMENT OF THE BORDER WAR by Helmoed Römer Heitman, p.105
![image](https://user-images.githubusercontent.com/109925704/211034212-93bbf98d-cb9e-4366-b0d5-2984e27a907e.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
