### ISSUE TITLE
Atlas Oryx quick correction

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2758]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4482 and 6067

### Summary of Changes

The Oryx is not, precisely, an AS.332 Super Puma. It uses the same engines but is slightly structurally different from the Puma or the Super Puma, being shorter than one and longer than the other. It also uses composite components which might be original South African developments, and the fuselage structures may have been provided by IAR in Romania rather than Aerospatiale. In short, nobody agrees what it is, but it's not an AS.332. I would recommend a name change to:

"Oryx -- South Africa (Army), 1987, Super Puma equivalent"

or something similar.

### Sources

https://en.wikipedia.org/wiki/Atlas_Oryx
https://www.airforce-technology.com/projects/atlas-oryx/
https://www.saairforce.co.za/the-airforce/aircraft/53/oryx
https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=1522

**Comment by PygmalionOfCyprus** [comment]
Handled 499. It's now:
`Oryx -- South Africa (Army), 1987, AS.332 Super Puma Equivalent`
`Oryx -- South Africa (Army), 2006, AS.332 Super Puma Equivalent, Drummer II Upgrade`

**Comment by FrangibleCover** [comment]
This change has been reverted with the addition of #3237, could the issue be reopened please?

**Comment by PygmalionOfCyprus** [comment]
Fixed 502.
