### ISSUE TITLE
#220 - Airbus A.310-304 MRTT (Germany), cargo and passenger loadouts

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#276]
### DB Selector

DB3K

### User(s)

#220 - Airbus A.310-304 MRTT -- Germany [FRG/Reunified] (Air Force), 2009

### Weapons Carried

#2624 'Passenger'
#3147 'Cargo [No Drop, 39 tons]'

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Please add Loadouts #20209 and #20211 used by the #4073 CC-150 Polaris.
It would allow to make the mulyirole nature of the #220 - Airbus A.310-304 MRTT.

### Sources

https://www.bundeswehr.de/de/ausruestung-technik-bundeswehr/luftsysteme-bundeswehr/airbus-a310

**Comment by PygmalionOfCyprus** [comment]
Added 494.
