### ISSUE TITLE
Spain F18A new 2021 version

### ISSUE THREAD

**Issue by Martin11258** [PygmalionOfCyprus/cmo-db-requests#2760]
### DB Selector

DB3K

### DBID to Copy

#28 F/A-18A Hornet [EF-18M, C.15A] - 2010

### Hypothetical

No

### Name

F/A-18A Hornet [EF-18M, C.15A] - 2021

### Country

Spain

### Service

Air Force

### In Commission

2021-Present

### Number in Service

54x

### Loadout Options

AIM-2000A IRIS-T - (2007) Guided Weapon
330 USG Drop Tank - Drop Tank
AIM-120C-7 AMRAAM P3I.3 - (2007) Guided Weapon
AGM-65G Maverick IR - (1991) Guided Weapon
Litening II Pod [FLIR + LRMTS, 40k ft] - Sensor Pod
GBU-10E/B Paveway II LGB [Mk84] - (USAF) Guided Weapon
AGM-84D Harpoon IC - (1986) Guided Weapon
AGM-88B HARM - (1990) Guided Weapon
Mk20 Rockeye II CB [247 x Mk118 Dual Purpose Bomblets] - (1969, Mk7 Dispenser) Bomb
Mk82 500lb LDGP - (1954) Bomb
Mk84 2000lb LDGP - (1955) Bomb
GBU-24/B Paveway III LGB [BPG-2000 PGM, CPE-800 Penetrator] - (Spain, 1988) Guided Weapon
GBU-16B/B Paveway II LGB [Mk83] - (USN) Guided Weapon
Taurus KEPD 350P - Guided Weapon
RECCELITE Pod [IR] - Sensor Pod
GBU-48/B Paveway II GPS/LGB [Mk83] - Guided Weapon

### Other Changes

The only important difference is that the new version of the F18 uses the Amraam C7 while the older(2010) was using the amraam B
Same loadouts as the old version just replacing the amraam B with the C7
The F18B was also modified and now uses the amraam C7 too

### Sources

https://www.infodefensa.com/texto-diario/mostrar/3077977/ejercito-aire-ultima-nueva-modernizacion-f-18 the new upgrade is going to recive the amraam C7 source
https://www.infodefensa.com/texto-diario/mostrar/3123086/cazas-f-18-espanoles-estrenan-mejoras-avionica-nuevas-capacidades the upgrade process was started
https://www.dsca.mil/node/1381 spain buys amraam c7 as now they can use them
https://www.infodefensa.com/texto-diario/mostrar/4080336/eel-gobierno-autorizara-contratos-472-millones-misiles-amraam-nsm-brimstone-bombas-guiadas ministry of defense confirms that 35 amraam C7 were bought for their use in the F18

**Comment by KLABDB3K** [comment]
Cluster bombs in 2021? Spain signed the Oslo treaty to not use them which came into force in 2010. https://www.un.org/disarmament/convention-on-cluster-munitions/

**Comment by Martin11258** [comment]
> Cluster bombs in 2021? Spain signed the Oslo treaty to not use them which came into force in 2010. https://www.un.org/disarmament/convention-on-cluster-munitions/

yes, but the aircraft still has the weapon integrated and It can carry them, despite not being politicaly posible it is tecnically posible
I doubt to add them or not but in the end because the database 2010 F18 still have them I decide to keep them

**Comment by Jkryos** [comment]
Added Pre-507.
