### ISSUE TITLE
Correction: PRA3000 radar facility using wrong sensor

### ISSUE THREAD

**Issue by haapmik** [PygmalionOfCyprus/cmo-db-requests#2761]
### DB Selector

DB3K

### Affected DBID(s)

Facility 2053

### Summary of Changes

DB3K_492a database has Radar PRA3000 facility (ID 2053) using sensor 18045X (ID 5071) instead of the correct sensor PRA3000 (ID 5072).

### Sources

18045X and PRA3000 are two different radar systems: https://www.navielektro.fi/radar-antennas.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
