### ISSUE TITLE
Change r-60m to r-60 for Yak-38 1977

### ISSUE THREAD

**Issue by EmperorRoosevelt** [PygmalionOfCyprus/cmo-db-requests#2762]
### DB Selector

Both

### Affected DBID(s)

Aircraft 1210, 1856

### Summary of Changes

The 1977 Yak-38 entries in the CWDB and DB3K should be changed to use period-accurate r-60 missiles instead of r-60M missiles which entered service five years later in 1982. Additionally, the r-60M loadouts listed for the CWDB 1977 Yak-38 are empty and if they are equipped on an aircraft it will launch with no weapons.

### Sources

DB3K (DBID 1856)
![image(1)](https://user-images.githubusercontent.com/116467425/211168018-005f3de9-58bf-4605-8332-d9372284b829.png)

CWDB (DBID 1210)
![image](https://user-images.githubusercontent.com/116467425/211168012-a5cc273c-372f-49a4-959a-39983b59c33f.png)

R-60M service date:
https://weaponsystems.net/system/218-Molniya%20R-60
https://www.polot.net/en/r_60_guided_missile_2020

**Comment by jun5896** [comment]
Duplicate #2578
I think It will progress on the next batch.

**Comment by jun5896** [comment]
Actually, It is a bug, before Old DB version(~478), Yak-38 was equipped with R-60. Several scenario were affected by this problem. Yak-38 can't use A/A role because R-60 is empty in-game from over 49X CWDB database.

**Comment by EmperorRoosevelt** [comment]
Thanks, I didn't see that, the DB3K version still needs to be changed though. I'll edit the issue.

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
