### ISSUE TITLE
South African Mk.81 and Mk.82 Pre-Fragmentation bombs

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2763]
### DB Selector

DB3K

### DBID to Copy

Weapons 275 and 1814

### Hypothetical

No

### Name

Mk.81 Pre-Fragmentation/Traan and Mk.82 Pre-Fragmentation/Traan

### Country

South Africa

### Service

Air Force

### In Commission

Unclear, possibly 1985 during the Mavinga offensive.

### Sensors

-

### Mounts

-

### Loadout Options

-

### Other Changes

Mk.81 equipped with a 45kg HE warhead surrounded by 11000 8.7mm steel ball bearings.
Mk.82 equipped with a 125kg HE warhead surrounded by 7000 16mm steel ball bearings.
HE in both suspected to be Composition H6.
Used in standard LDGP and parachute retarded variants, parachute retarded bombs appear to be called 'Traan'.

LDGP variants should have the Airburst tag, they were fitted with Jupiter proximity fuzes.

### Sources

https://www.saairforce.co.za/the-airforce/weapons/50/mk-81-250-lb-bomb
https://www.saairforce.co.za/the-airforce/weapons/78/mk-82-500lb-pre-fragmentation-bomb
![image](https://user-images.githubusercontent.com/109925704/211170182-f1baa982-2771-4370-8fab-783fc4c419ad.png)
From EQUIPMENT OF THE BORDER WAR by Helmoed Römer Heitman, p.103

WAR OF INTERVENTION IN ANGOLA, VOLUME 4: ANGOLAN AND CUBAN AIR FORCES, 1985-1987 by Fontanellaz, Cooper & Matos, p.27

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
