### ISSUE TITLE
CWDB R-40(AA-6 A~D) change the range

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#2767]
### DB Selector

CWDB

### Affected DBID(s)

Weapon 732, 749, 751, 752

### Summary of Changes

AA-6 Acrid A/B [R-40R/T]            30 nm (CWDB Value) > 16.2 nm (DB3K Value)
AA-6 Acrid C/D [R-40RD/TD        45 nm (CWDB Value) > 27 nm (DB3K Value)

from here : https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1247

It fixed in 495, Also It needs to change for CWDB.

### Sources

Closed issues https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1247

In-game database from CWDB, DB3K

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
