### ISSUE TITLE
Mirage F.1AZ for Gabon

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2770]
### DB Selector

DB3K

### DBID to Copy

1548

### Hypothetical

No

### Name

Mirage F.1AZ

### Country

Gabon

### Service

Air Force

### In Commission

2006-

### Number in Service

6x

### Loadout Options

Unknown

### Other Changes

Aerosud provided an avionics upgrade of some sort. I can't get any confirmation or any images, but I suspect this to be the Aerosud avionics upgrade that was also part of the Thompson-CSF package for the Spanish Mirage F.1M, which are Partial Glass Cockpits.

### Sources

https://www.defenceweb.co.za/aerospace/aerospace-aerospace/gabon-celebrates-50-years-of-independence-with-5-ship-mirage-f1-flypast/
http://www.saairforce.co.za/news-and-events/468/mirage-f1-azs-delivered-to-gabon
https://www.defenceweb.co.za/aerospace/aerospace-aerospace/paramount-confirms-mirage-f1azs-delivered-to-congo-brazzaville-eyes-future-customers/
https://www.sa-transport.co.za/aircraft/mirage_f1_saaf_service.html
https://www.thedrive.com/the-war-zone/25927/check-out-cockpit-in-draken-internationals-private-mirage-f-1m-aggressor-jet

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
