### ISSUE TITLE
Upgraded avionics for Spanish Mirage F.1Ms

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2771]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 16

### Summary of Changes

Cockpit should be Partial Glass, bombsight should be INS/GPS, Radios should be Have Quick 2 secure comms. Some sort of chaff/flare dispensers added, type unknown.
![image](https://user-images.githubusercontent.com/109925704/211216562-c5b84167-8bc7-447b-a620-7484b33285f7.png)

### Sources

https://www.thedrive.com/the-war-zone/25927/check-out-cockpit-in-draken-internationals-private-mirage-f-1m-aggressor-jet
https://www.key.aero/forum/modern-military-aviation/67550-spanish-f1s

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
