### ISSUE TITLE
498 containers pallets etc not showing up in cargo options?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2772]
### DB Selector

DB3K

### Affected DBID(s)

DB3K 498

### Description of Problem

https://www.matrixgames.com/forums/viewtopic.php?p=5067193#p5067193

The cargo container options which are visible for 497a such as 40ft ISO container etc are not visible for options in cargo for the 498 version?

This is with 1302.1 installed?

Not sure is it the DB OR the version but with 497a installed with 1302 the containers are back and fillable?

### Recommended Fix

Is it a DB visibility issue?

**Comment by PygmalionOfCyprus** [comment]
This is my fault, I'll spare the technical explanation as to why but the container annex didn't actually ship with 498. I pushed a 498a version this morning so it should be released shortly. Sorry about that!

**Comment by KLABDB3K** [comment]
Much obliged.
