### ISSUE TITLE
XF-108 ghost properties

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2773]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 3118

### Summary of Changes

Currently claimed to belong to the US Navy in the short description and selection box. As much fun as Sea Rapier sounds, it was a USAF project. The aircraft also has the night bombing and probe refuelling tags, which I suspect to be left over from the aircraft being based on the A-5 Vigilante. The Max Payload of 3450kg is also identical to the Vigilante. Might be worth checking the whole aircraft over.

### Sources

https://en.wikipedia.org/wiki/North_American_XF-108_Rapier

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
