### ISSUE TITLE
#1299 - AB.412SP (Saudi Arabia - 0) Update also used by A/F and please Add SAR loadout.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2774]
### DB Selector

DB3K

### Affected DBID(s)

#1299 - AB.412SP (Saudi Arabia - 0)

### Summary of Changes

Please add SAR loadout and expand to include Army and A/F as users please. 

The image used in DB498 is for an air force AB.412 which even has a winch visible and searchlight. 
Don't need a winch for fast roping and its also got a searchlight?

### Sources

![image](https://user-images.githubusercontent.com/99494755/211221509-a79df964-c9e6-439a-af75-608b8f948b67.png)

**Comment by PygmalionOfCyprus** [comment]
Added for the AF and added SAR loadout + searchlight + generic EO/IR turret. The OperatorService should say "Royal Army," not "0," so we're looking at that too.
