### ISSUE TITLE
Correction for USMC A-4M Skyhawk II

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#2778]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft ID 658

### Summary of Changes

![This is an image](https://imgproc.airliners.net/photos/airliners/2/1/3/2452312.jpg?v=v40)
Marietta - Dobbins ARB (Atlanta NAS) (MGE / KMGE)
Georgia, USA - January 7, 1993
https://www.airliners.net/photo/USA-Marines/McDonnell-Douglas-A-4M-Skyhawk-II/2452312/L

- Change Name : A-4M Skyhawk II

- Change Sensors/EW
(1976)
1 x AN/APG-53A
1 x AN/ALR-45 Compass Tie
1 x AN/ALR-50 Charger Blue
1 x AN/ALQ-100
1 x Mk1 Eyeball
(1981)
Change 1 x AN/ALQ-100 >> AN/ALQ-126A

- Add Weapon Stores / Loadouts
AIM-9L Sidewinder (1981)
AIM-9M Sidewinder (1984)

### Sources

https://www.airliners.net/photo/USA-Marines/McDonnell-Douglas-A-4M-Skyhawk-II/2452312/L
https://en.wikipedia.org/wiki/Douglas_A-4_Skyhawk

Naval Fighters 55 - McDonnell Douglas A-4M Skyhawk
https://media.oiipdf.com/pdf/035f4066-8e43-498d-812c-54986dd34ce8.pdf
> from (https://oiipdf.com/naval-fighters-55-mcdonnell-douglas-a-4m-skyhawk-pdf)

**Comment by PygmalionOfCyprus** [comment]
Handled 499. Added 2 new Skyhawk versions for '81 and '84.
