### ISSUE TITLE
CA LAV II Coyote Reconnaissance Vehicle x85

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#278]
### DB Selector

DB3K

### DBID to Copy

1898 DB3k

### Hypothetical

No

### Name

Mech Inf Plt (LAV-II x 4) -- Canada 1996

### Country

Canada

### Service

Canadian Army

### In Commission

1996-

### Sensors

ADD:
- 1x AN/PPS-5C MSTAR (https://en.wikipedia.org/wiki/MSTAR) Version 3
- 1x Generic Laser Rangefinder
- 1x Generic TV Camera

### Mounts

ADD:
- 8 × 76mm grenade launchers (2 × cluster of 4)
- 1 × [C6] 7.62mm machine gun coaxial
- 1 × C6 7.62mm machine gun
 pintle

### Other Changes

- The turret also features a laser-warning receiver and mounts a total of eight grenade launchers in two clusters capable of firing smoke and fragmentation grenades.
- The main gun is equipped with dual ammunition feeds that allow for separate weapons effects, selectable by the gunner/crew commander; the standard load is a belt of armour-piercing sabot rounds and a belt of HE-T explosive/fragmentation rounds.
- The turret is equipped with a laser rangefinder, but no ballistic computer; elevation and lead corrections are applied manually by the gunner using multi-stadia reticules in the day, thermal, and image intensification sights.

### Sources

https://en.wikipedia.org/wiki/Coyote_Reconnaissance_Vehicle#Bison
https://en.wikipedia.org/wiki/MSTAR
http://www.army-armee.forces.gc.ca/en/equipment/vehicles/coyote.page

![Canadian_Light_Armored_Vehicle_at_the_Calgary_Stampede,_2007](https://user-images.githubusercontent.com/99632305/164865596-2c0e69db-68b8-4c4e-9504-ecc1f80af27d.jpg)
![Coyote_LAV-1_wheeled_armoured_reconnaissance_vehicle_Canada_Canadian_army_640](https://user-images.githubusercontent.com/99632305/164865706-d79bef29-60e1-43a2-becd-5efa9ef371d9.jpg)
![m02010091900007](https://user-images.githubusercontent.com/99632305/164865830-9766d3c7-8712-4a1f-91df-0864bbf4d33b.jpg)
![vbl3--lav3](https://user-images.githubusercontent.com/99632305/164865842-c07df26d-012d-4195-9434-ba682eb2feab.jpg)
![images](https://user-images.githubusercontent.com/99632305/164865851-866f683c-1900-4416-8487-c5902609d415.jpg)

**Comment by Jkryos** [comment]
Added DB3K 507.
