### ISSUE TITLE
Update SAM Bn HQ-22/FK-3 Target Speed

### ISSUE THREAD

**Issue by 1019204633** [PygmalionOfCyprus/cmo-db-requests#2780]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3281/3282

### Summary of Changes

Update SAM Bn HQ-22/FK-3 Target Speed Mach 6，FK-3 is a Chinese air-to-air missile specifically for export and it can be seen as a predecessor of the HQ-22 air defense missile system. Chinese FK-3 medium to long range air-defense system is designed to handle all kind of airborne threats, including fighter jets, cruise missiles, tactical missiles. 

### Sources

https://[www.globalsecurity.org](https://www.globalsecurity.org/military/world/china/hq-22-specs.htm)/military/world/china/hq-22-specs.htm

https://[en.wikipedia.org](https://en.wikipedia.org/wiki/HQ-22#:~:text=FK-3%3A%20Original%20export%20variant.%20Has%20a%20speed%20of,6%20and%20range%20of%20100%20kilometres%20%2862%20mi%29.)/wiki/HQ-22#:~:text=FK-3%3A%20Original%20export%20variant.%20Has%20a%20speed%20of,6%20and%20range%20of%20100%20kilometres%20%2862%20mi%29.

https://www.armyrecognition.com/defense_news_april_2022_global_security_army_industry/china_delivers_fk-3_medium_range_air_defense_missiles_to_serbia.html

https://militaryleak.com/2020/08/03/serbia-buys-chinese-fk-3-surface-to-air-missile-system/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.

**Comment by 1019204633** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。常联系喔

**Comment by PygmalionOfCyprus** [comment]
https://www.youtube.com/watch?v=r7wTiBk8smE
