### ISSUE TITLE
C.160D Transall -- Turkey (Air Force), 1971, 20x

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#279]
### DB Selector

DB3K

### Baseline

#1696 - C.160D Transall -- Germany

### Hypothetical

No

### Name

C.160D Transall

### Country

Turkey

### Service

Air Force

### In Commission

1971

### Length (m)

Please copy #1696 - C.160D Transall -- Germany

### Wingspan (m)

Please copy #1696 - C.160D Transall -- Germany

### Height (m)

Please copy #1696 - C.160D Transall -- Germany

### Empty Weight (kg)

Please copy #1696 - C.160D Transall -- Germany

### Maximum Takeoff Weight (MTOW) (kg)

Please copy #1696 - C.160D Transall -- Germany

### Payload Weight (kg)

Please copy #1696 - C.160D Transall -- Germany

### Crew

Please copy #1696 - C.160D Transall -- Germany

### Propulsion

Please copy #1696 - C.160D Transall -- Germany

### Service Ceiling (ft)

Please copy #1696 - C.160D Transall -- Germany

### Military/Afterburner Speed (kt)

Please copy #1696 - C.160D Transall -- Germany

### Cruise Speed (kt)

Please copy #1696 - C.160D Transall -- Germany

### Supercruise

No

### Ferry Range (nm)

Please copy #1696 - C.160D Transall -- Germany

### Sensors

Please copy #1696 - C.160D Transall -- Germany

### Mounts

Please copy #1696 - C.160D Transall -- Germany

### Loadout Options

Please copy #1696 - C.160D Transall -- Germany

### Comms/Datalinks

Please copy #1696 - C.160D Transall -- Germany

### Comments

Turkey : bought 20 aircraft from the Luftwaffe, delivered in 1971, operated by the 221 Filo from Kayseri Erkilet Airport.

Please copy #1696 - C.160D Transall -- Germany [FRG/Reunified] (Air Force), 1969-0.

### Sources

https://www.scramble.nl//images/stories/countries/tr/photos/orbat-c160d.jpg
https://www.key.aero/article/european-airlift-capabilities-part-four
https://www.flightglobal.com/reports/world-air-forces-directory-2022/146695.article

**Comment by PygmalionOfCyprus** [comment]
Added 493.
