### ISSUE TITLE
Angolan Mi-25 corrections

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2793]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4467

### Summary of Changes

Angola acquired their first Mi-25s in 1983 and lost their first airframe in the first days of January 1984, so the service date should be changed to 1983.

The aircraft were equipped with Hot Brick jammers but didn't get countermeasures dispensers until late 1987.

### Sources

WAR OF INTERVENTION IN ANGOLA, VOLUME 3: ANGOLAN AND CUBAN AIR FORCES, 1975-1985 by Fontanellaz, Cooper & Matos, p.52-53

WAR OF INTERVENTION IN ANGOLA, VOLUME 4: ANGOLAN AND CUBAN AIR FORCES, 1985-1987 by Fontanellaz, Cooper & Matos, p.iii

Does it show that I've got some new books?

**Comment by PygmalionOfCyprus** [comment]
Fixed ISD and added new 1987 entry w/ CMDS 500.
