### ISSUE TITLE
F-35A/B/C 2025 with new radar AN/APG-85

### ISSUE THREAD

**Issue by blu3ser** [PygmalionOfCyprus/cmo-db-requests#2795]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft: 3836,3835,4701

### Summary of Changes

The F-35 Block 4 will update to a new radar: AN/APG-85

### Sources

https://www.thedrive.com/the-war-zone/f-35-will-get-new-radar-under-massive-upgrade-initiative

**Comment by tbrandon517** [comment]
Duplicate of #2742
