### ISSUE TITLE
United States - WC-135R Constant Phoenix

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2797]
### DB Selector

DB3K

### DBID to Copy

DBID #5878 & 6066

### Hypothetical

No

### Name

WC-135R Constant Phoenix

### Country

United States

### Service

Air Force

### In Commission

2022-

### Number in Service

3x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

KC-135R's modified for Constant Phoenix mission with greater reliability to replace existing WC-135Ws. Remove refueling gear but keep upgraded engines.

### Sources

https://www.thedrive.com/the-war-zone/air-forces-first-wc-135r-constant-phoenix-nuke-sniffing-jet-has-flown
https://www.thedrive.com/the-war-zone/18472/the-us-air-force-wants-a-trio-of-more-modern-wc-135r-nuke-sniffing-planes
https://militaryleak.com/2022/07/13/us-air-force-55th-wing-offutt-air-force-base-receives-first-wc-135r-constant-phoenix/
https://www.airforce-technology.com/news/usaf-55th-wing-first-wc135r/
https://www.overtdefense.com/2022/06/29/new-wc-135-constant-phoenix-takes-flight/
https://en.wikipedia.org/wiki/Boeing_WC-135_Constant_Phoenix#Variants

![image](https://user-images.githubusercontent.com/99599482/211849403-39fa9e82-4567-44dd-b36d-f7d9d357592a.png)

![image](https://user-images.githubusercontent.com/99599482/211849264-692b88d7-58c6-4da1-928d-1fbd1f6d5317.png)

**Comment by 5th-Domain** [comment]
This exists in the Database: DB3K_498a, # 5878 Its labeled as 135W but it the most recent version.  See ticket WC-135W Constant Phoenix, 2022- Complete (COMP) #1288

**Comment by tbrandon517** [comment]
> This exists in the Database: DB3K_498a, # 5878 Its labeled as 135W but it the most recent version. See ticket WC-135W Constant Phoenix, 2022- Complete (COMP) #1288. Just needs renaming with the R my fault i titled it with the W but named it with the R.

Per above please change to an update request based on name and engine type from KC-135R

**Comment by PygmalionOfCyprus** [comment]
Renamed 5878 to WC-135R DB 503.
