### ISSUE TITLE
KC-135R Stratotanker - Commercial, ex-Singapore, Meta Aerospace 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2799]
### DB Selector

DB3K

### DBID to Copy

DBID 1854

### Hypothetical

No

### Name

KC-135R Stratotanker - Commercial, ex-Singapore, Meta Aerospace 

### Country

Commercial

### Service

Meta Aerospace 

### In Commission

2020-

### Number in Service

4x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

4x ex-SIngapore KC-135R acquired by commercial operator Meta Aerospace for contractor air tanker services.

### Sources

https://www.thedrive.com/the-war-zone/36851/heres-whos-bought-those-retired-singapore-air-force-kc-135r-tankers

![image](https://user-images.githubusercontent.com/99599482/211856352-5e521bc1-b631-430f-9ccf-c5b5024a1033.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
