### ISSUE TITLE
Morocco - Wander B VTOL UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2801]
### DB Selector

DB3K

### DBID to Copy

DBID 5927

### Hypothetical

No

### Name

Wander B VTOL UAV

### Country

Morocco

### Service

Air Force

### In Commission

2022-

### Number in Service

150x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Morocco has purchased the newer VTOL version of the Wander B. DBID for Copy is the Ethiopian unit which is the older CTOL version.

### Sources

https://www.airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/september/8721-morocco-purchases-150-israeli-vtol-drones-manufactured-by-bluebird.html?fbclid=IwAR2dFFBESJYxxf7RFQGYLWfCSeI8YnZoCTu9QWK1WAxAiS_re7rHX_S8o10
https://www.oryxspioenkop.com/2021/10/operating-from-shadows-moroccos-uav.html

![image](https://user-images.githubusercontent.com/99599482/211860407-6ecee774-c119-4286-a009-db9f01b942b6.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
