### ISSUE TITLE
Kyrgyzstan  - TB2 UCAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2802]
### DB Selector

DB3K

### DBID to Copy

DBID 5923

### Hypothetical

Yes

### Name

TB2 UCAV

### Country

Kyrgyzstan

### Service

Air Force

### In Commission

2022-

### Number in Service

3x

### Sensors

CATS + a 2nd tail mounted camera for night ops

### Mounts

No Change

### Loadout Options

Has both MAM-L and MAM-C loadouts

### Other Changes

None

### Sources

https://www.oryxspioenkop.com/2022/10/mountain-drones-kyrgyzstans-bayraktar.html
https://www.hurriyetdailynews.com/kyrgyzstan-orders-turkeys-bayraktar-tb2-drones-168841
https://thediplomat.com/2022/10/kyrgyz-security-chief-flaunts-turkish-drone-connection/
https://www.overtdefense.com/2022/09/16/a-bayraktar-tb2-ucav-base-has-been-opened-in-kyrgyzstan/

![image](https://user-images.githubusercontent.com/99599482/211863980-bc14803b-e8ec-4bca-9e27-09effd6d05a5.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
