### ISSUE TITLE
Add Laksamana-class, 2022, re-hull, CMS + FCS upgrades and missiles removed.

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2809]
### DB Selector

DB3K

### DBID to Copy

Ship 1022

### Hypothetical

No

### Name

F 136  Laksamana Muhammad Amin, 2022 [Re-hull]

### Country

Malaysia

### Service

Navy

### In Commission

2022

### Sensors

- Remove RTN-10X FCR system
- Add GEM Elettronica EOFCS115A fire control system. It should be able to guide both 76mm and 40mm Dardo. (Source 4)
![image](https://user-images.githubusercontent.com/99646926/212126554-1b0ca162-d2e0-4ee9-a764-1eb28db4d017.png)

### Mounts

- Remove Otomat and Aspide launchers. (Source 6)
![image](https://user-images.githubusercontent.com/99646926/212126106-7dd9b53b-d762-4156-883a-a90279b0f0bb.png)

- Remove torpedo launchers (the launchers is now installed on Kasturi-class corvette to replace the Bofor ASW mortar) (Source 7)
![image](https://user-images.githubusercontent.com/99646926/212125792-d6f250fa-605e-44b5-84c6-994303e1648d.png)

### Other Changes

- The re-hull program were also included CMS upgrade so the Combat System should be "CS Gen 6 (2001-2029)" .
_"Initially planned to be replaced by the Keris class Littoral Mission Ship (LMS), the four Laksamana class corvettes will continue to serve the RMN albeit as Fast Attack Craft. A plan to fit locally develop mini Combat Management System (CMS) for all of the FAC squadrons is also in the pipeline"_ (Source 1)

- Currently only F 136  Laksamana Muhammad Amin has completed the re-hull program so far from out of 4 Laksamana-class corvettes. (Source 2)
![image](https://user-images.githubusercontent.com/99646926/212127501-ace43a1f-5393-4ba4-a2eb-552763327feb.png)

### Sources

1. http://defense-studies.blogspot.com/2020/09/long-live-for-laksamana-class.html
2. http://defense-studies.blogspot.com/2022/12/goms-shipyard-rilis-hasil-re-hull.html (In Indonesian)
3. https://www.malaysiandefence.com/new-hull-for-kd-laksamana-muhammad-amin/
4. https://www.malaysiandefence.com/back-to-the-future-ii/
5. https://militaryleak.com/2022/01/13/new-hull-for-royal-malaysian-navy-corvette-kd-laksamana-muhamad-amin-f136/
6. https://www.asiapacificdefensejournal.com/2019/01/malaysia-revises-naval-fleet-retirement.html
7. https://www.malaysiandefence.com/no-new-torps/

**Comment by Jkryos** [comment]
Added DB3K 501.
