### ISSUE TITLE
Add Z-8C Transport Helicopter Chinese Navy 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#281]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3708

### Hypothetical

No

### Name

Z-8C Super Felon 

### Country

China

### Service

Chinese Navy

### In Commission

2021

### Sensors

Add generic nose mounted weather radar

### Loadout Options

Trooper
3 ton cargo
5 Ton Cargo

### Other Changes

Additional built for Chinese Marine corps for Navy LHD, LPD
Designation is more C then CJ. Only PLAN knows.
Its maximum TO weight is 13t, cruise speed 248km/hr, ferry range 1,400km, service ceiling 3,050m. Its power plant are 3 WZ-6 turboshafts (WZ-6 is licensed built TurmoIII-you've got these on existing version).

### Sources

http://chinese-military-aviation.blogspot.com/p/helicopters-i.html
https://twitter.com/rupprechtdeino/status/1296479440722157568
https://www.scramble.nl/military-news/china-marines-corps-expands-with-an-aviation-brigade
https://china-defense.blogspot.com/2021/04/those-z-8c-helicopters-onboard-at.html
https://www.sinodefenceforum.com/t/plan-marine-corps-aviation-units-and-helicopters.8760/
https://defence.pk/pdf/threads/z-8-and-z-18-transport-helicopter-thread.466117/page-31
https://militaryleak.com/2019/12/08/peoples-liberation-army-navy-changhe-z-8cj-helicopter/
http://all-aero.com/index.php/contactus/64-engines-power/12716-turbomeca-turmo-changzhou-dongan-wz-6

**Comment by PygmalionOfCyprus** [comment]
Added 493.
