### ISSUE TITLE
Update/correction for Narco-Submarine, FSV version (Fully Submerged Vessel)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2810]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 520

### Summary of Changes

- Reduce the crew from 15 to just 4
![image](https://user-images.githubusercontent.com/99646926/212313848-e327fdb0-47f3-404e-b7d9-3185c2f40897.png)

- Add ability to carry cargo. The sub were noted to be able to carry up to 15 tonnes of cargo
![image](https://user-images.githubusercontent.com/99646926/212313949-c1f03a2d-808c-4f7d-8f3c-73995dec0e5b.png)

- Add EO system to the sub.
![image](https://user-images.githubusercontent.com/99646926/212313129-8f29c824-32a8-433a-84a2-da15464bcc45.png)

- Reduce max depth from -180m to just -100m.
_"The double-hulled steel vessel could have traveled 3,700 kilometers, dived 100 m"_

Below pics is for the references:

![image](https://user-images.githubusercontent.com/99646926/212314545-aaacf07d-454f-4adc-bd80-b481c54932a7.png)
![image](https://user-images.githubusercontent.com/99646926/212314598-6ef1b30b-858a-43f8-a07c-f129fdcc0b95.png)

### Sources

- https://en.wikipedia.org/wiki/Narco-submarine
- http://www.hisutton.com/Narco%20Subs%20101.html

**Comment by capcop98** [comment]
More source regarding the FSV.

https://legionmagazine.com/en/capture-of-22-metre-transatlantic-narco-sub-marks-new-era-in-war-on-drugs/
_"Narco-submarines were considered an oddity until 2000, when Colombian police discovered a half-built, 36-metre true submarine in a warehouse outside of Bogotá. The double-hulled steel vessel had a range of 3,700 kilometres, a capacity for about 15 tonnes of cocaine, and the capability to dive to 100 metres."_

**Comment by PygmalionOfCyprus** [comment]
Handled 499. Didn't add the cargo capacity, though, because Command doesn't currently model cargo for subs.
