### ISSUE TITLE
171 Kedah [Meko 100] - 2025, NSM Upgrade

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2811]
### DB Selector

DB3K

### DBID to Copy

ship 1483

### Hypothetical

Yes

### Name

171 Kedah [Meko 100]

### Country

Malaysia

### Service

Navy

### In Commission

2025-

### Number in Service

at least 2 of 6 ships

### Sensors

Not Stated

### Mounts

Add 2x quad NSM

### Loadout Options

N/A

### Other Changes

Not Stated

### Sources

https://www.asiapacificdefensejournal.com/2022/08/malaysia-plans-to-arm-kedah-class.html?fbclid=IwAR1jCAxXMVP6NexpEzoHV4ZSDz8l7Mowbw7yYV61-fLINePGO03BknTbCOk
https://www.janes.com/defence-news/news-detail/malaysian-navy-proposes-to-equip-kedah-class-corvettes-with-naval-strike-missile
https://militaryleak.com/2022/08/02/royal-malaysian-navy-to-equip-kedah-class-corvettes-with-naval-strike-missile-nsm/

![image](https://user-images.githubusercontent.com/99599482/212341003-1086197b-b88d-40e6-94d2-ed2cbec7a3f0.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
