### ISSUE TITLE
Mega Yacht - Based on MY Nord Analysis

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2812]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

Civilian Motor Yacht [140m] - 460 feet, Mega Yacht

### Class

Mega Yacht

### Country

Civilian

### Service

Civilian

### In Commission

0

### Number in Service

N/A

### Length (m)

141.63

### Beam (m)

22.5

### Draft (m)

5.15

### Standard Displacement (t)

3,047

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

40+36 PAX

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

4 x Rolls Royce MTU 20V 4000 M93L Diesels, 2x Screws plus 2x bow and 2x stern thrusters

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

18 knots

### Range (nm) at Speed (kt)

Not Stated

### Sensors

2x Navigation Radars
 
Possibly sonars

### Mounts

None

### Aircraft & Docking Facilities

1x size 17, 70t capacity helicopter pad at bow.
1x size 17, 70t capacity helicopter pad with telescoping hangar amidships compatible with AW139

2x Lifeboat Hangars at bow between helipad and superstructure. 
2x Upper side hangars (port and starboard) for RHIBS. 
1x Main Hangar (Central and full width of ship with port and starboard access) for 2x Guest Tenders, 1x Amphibious Tender, 1x Landing Craft. 
1x Aft starboard side hangar with Storage for 4x quad bikes, 1x Utility RIB tender and 1x Sports utility vehicle (SUV). 
1x Aft port side hangar with storage for 1x Submersible and 1x Hovercraft.

For reference Nord is known to carry
Life Boat Hangars 
- 2x Lifeboats (1x each)

Main Hangar
- 1x Iguana Yachts Transforming Tender (Tracked Amphibious Boat) (9.44 M L,  3.4 M B)
- 2x Windy SR52 Blackbird Tenders (16.1m L, 4.5m B, 1.23m d)
- 1x Munsun 44-6 Tender (Landing Craft) (13.4 m L, 4.25 m B)

Secondary Port Hangar
1x Triton Submarine
1x Griffon 995ED Hovercraft (8.6m L, 5.2m b)

Secondary Starboard Hangar
-1x Utility RHIB
Vehicles

Small RHIB Hangars (P &S)
- 1-3x RHIBS (ie 2x 11m or 3x 7m)

Known to carry.
3x Toyota Land Cruiser SUVs
4x Quadbikes
Jet skis

Possibly
ROVs
Dive Scooters

### Comms/Datalinks

VHF/UHF
SATCOM

### Ship Codes

Dual or Triple Stabilizers, Built to Mercantile Standards

### Comments

Large mega yachts with vehicles storage, especially those belonging to citizens of states like Russia (used Nord as a reference based on OSINT analysis) offer a potential base for espionage and special operations. This could be used with several interesting scenario ideas.

### Sources

http://www.hisutton.com/Russian-Oligarch-Yacht-Nord.html?fbclid=IwAR08CBl2pilxxOLFS5cn7R3PTe4q1GF7ZFXqN1_CjuvSlicb1xib8ZKlQJ8

![image](https://user-images.githubusercontent.com/99599482/212356942-7085d6c8-dd64-4127-b5f5-554782cbcbc6.png)
![image](https://user-images.githubusercontent.com/99599482/212357465-e0ca528e-e1bd-4c7c-bb3b-1f318aa0b93e.png)
![image](https://user-images.githubusercontent.com/99599482/212357524-39582cc3-6e68-4f94-a5a6-166da29ce61a.png)

Sources for Known "Toys"
https://tritonsubs.com/subs/t1650-7-c/
https://www.griffonhoverwork.com/products/hovercraft/995ed-hovercraft/
https://www.iguana-yachts.com/models/iguana-knight/
https://www.munsonboats.com/models/44-series/
https://www.windyboats.com/range/sr-line/sr52/

**Comment by Jkryos** [comment]
Added DB3K 506.

**Comment by tbrandon517** [comment]
> Added DB3K 506.

Super. This should be fun!
