### ISSUE TITLE
Mali - Bayraktar TB2 UCAV - 2022, CATS

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2814]
### DB Selector

DB3K

### DBID to Copy

6045

### Hypothetical

No

### Name

Bayraktar TB2 UCAV - 2022, CATS

### Country

Mali

### Service

Air Force

### In Commission

2022-

### Number in Service

3x

### Sensors

CATS

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/december/8847-mali-receives-turkish-built-bayraktar-tb2-ucavs.html?fbclid=IwAR0KfRwsSLYRWPCSP1hZeO6QUmTQa7q_5u1cTT2qq9HiCO7bj-rETwFQpGc
https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4
https://www.military.africa/2023/01/mali-bayraktar-tb2-arrives-but-without-canadian-sub-system/

![image](https://user-images.githubusercontent.com/99599482/212365293-66050d51-e3b1-4c8b-8781-846a4204f046.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
