### ISSUE TITLE
Mali - A-29B Super Tucano [EMB-314] - 2018

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2815]
### DB Selector

DB3K

### DBID to Copy

aircraft 5361

### Hypothetical

No

### Name

A-29B Super Tucano [EMB-314]

### Country

Mali

### Service

Air Force

### In Commission

2018-Present

### Number in Service

^x planned, 4x delivered, 1x lost 2020

### Sensors

Remove Sensor Turret

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

N/A

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4
https://www.airforce-technology.com/uncategorized/newsmali-to-buy-six-embraer-a-29-super-tucano-aircraft-4602826/
https://en.wikipedia.org/wiki/Embraer_EMB_314_Super_Tucano#Operators
https://web.archive.org/web/20180715190042/http://www.janes.com/article/81726/mali-receives-four-super-tucanos

![image](https://user-images.githubusercontent.com/99599482/212368389-2019d844-5133-43bc-b5d8-fbcc44948e3d.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
