### ISSUE TITLE
Mali - Mi-35M Hind - 2017, 4x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2816]
### DB Selector

DB3K

### DBID to Copy

aircraft 4509

### Hypothetical

No

### Name

Mi-35M Hind

### Country

Mali

### Service

Air Force

### In Commission

2017-

### Number in Service

4x, delivered 2017 and 2021

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4
https://www.aviationpros.com/aircraft/rotorcraft/press-release/12372462/russian-helicopters-russian-helicopters-produce-two-mi35m-for-mali
https://www.military.africa/2021/01/mali-receives-additional-mi-35m-hind-e-helicopter-from-russia/

![image](https://user-images.githubusercontent.com/99599482/212370015-ea6bb0a6-18e0-4ada-a0af-cdf120f72131.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
