### ISSUE TITLE
Mali - Cessna 208B Grand Caravan EX - 2019, ISR Upgrade

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2817]
### DB Selector

DB3K

### DBID to Copy

aircraft 5693

### Hypothetical

No

### Name

Cessna 208B Grand Caravan EX - 2019, ISR Upgrade

### Country

Mali

### Service

Air Force

### In Commission

2019-

### Number in Service

1x

### Sensors

No Change, unable to ascertain exact model.

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4
https://www.key.aero/article/new-isr-cessna-208-caravan-mali

![image](https://user-images.githubusercontent.com/99599482/212371483-3ab35e47-1ccc-42c3-ba7d-fc6ca64842fc.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
