### ISSUE TITLE
Mali - Mi-24D Hind D - 2009

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2818]
### DB Selector

DB3K

### DBID to Copy

aircraft 456

### Hypothetical

No

### Name

Mi-24D Hind D

### Country

Mali

### Service

Air Force

### In Commission

2009-

### Number in Service

3, deliver 2009 and 2012

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212372220-0bb15001-f077-446c-8f39-7f472747142c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
