### ISSUE TITLE
Mali - AS.332 Super Puma - 2016, 2x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2819]
### DB Selector

DB3K

### DBID to Copy

aircraft 4629

### Hypothetical

No

### Name

AS.332 Super Puma

### Country

Mali

### Service

Air Force

### In Commission

2016-

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212373270-53dcc817-c242-47e8-80f1-a152aaad5da2.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
