### ISSUE TITLE
Mali - C-295W - 2016

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2820]
### DB Selector

DB3K

### DBID to Copy

aircraft 6174

### Hypothetical

No

### Name

C-295W

### Country

Mali

### Service

Air Force

### In Commission

2016-

### Number in Service

2x, 1x 2016, 1x 2022

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212373998-5fd590f3-4982-4d5e-b2b9-1d001e1090f4.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
