### ISSUE TITLE
Mali - Mi-24P Hind F

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2821]
### DB Selector

DB3K

### DBID to Copy

aircraft 4264

### Hypothetical

No

### Name

Mi-24P Hind F

### Country

Mali

### Service

Air Force

### In Commission

2022-

### Number in Service

4x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212374695-bd323272-8ed7-408b-bf49-bae99060e59c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
