### ISSUE TITLE
Mali - Mi-171 Hip H

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2822]
### DB Selector

DB3K

### DBID to Copy

aircraft 2489

### Hypothetical

No

### Name

Mi-171 Hip H

### Country

Mali

### Service

Air Force

### In Commission

2021-

### Number in Service

4x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212375240-2a86af2e-4788-4779-b8c9-b372b949c8b6.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499. Apparently 171Sh.
