### ISSUE TITLE
Mali - Mi-8MT Hip H

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2823]
### DB Selector

DB3K

### DBID to Copy

aircraft 393

### Hypothetical

No

### Name

Mi-8MT Hip H

### Country

Mali

### Service

Air Force

### In Commission

2022

### Number in Service

1x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212375843-7db10027-fe5a-4b05-9089-b69b61d78969.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
