### ISSUE TITLE
Mali - L-39C Albatros

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2824]
### DB Selector

DB3K

### DBID to Copy

aircraft 400

### Hypothetical

No

### Name

L-39C Albatros

### Country

Mali

### Service

Air Force

### In Commission

2022-

### Number in Service

6x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212376549-8b720f05-d2e6-4722-8532-90f5de08c1da.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
