### ISSUE TITLE
Mali - Su-25 Frogfoot A

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2825]
### DB Selector

DB3K

### DBID to Copy

aircraft 2378

### Hypothetical

No

### Name

Su-25 Frogfoot A

### Country

Mali

### Service

Air Force

### In Commission

2022-2022

### Number in Service

1x, Crashed 2 months after delivery

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212377211-8ada2600-566e-428c-aff4-867e91ccde3d.png)

**Comment by PygmalionOfCyprus** [comment]
>**In Commission**
2022-2022

I laughed. Handled 499. (Removed the Russian AS-12s, etc. since I highly doubt those were given to Mali.)
