### ISSUE TITLE
Mali - Y-12

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2826]
### DB Selector

DB3K

### DBID to Copy

aircraft 5062

### Hypothetical

No

### Name

Y-12

### Country

Mali

### Service

Air Force

### In Commission

2017-

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212377691-da399dc2-cfe7-4912-86d3-139d4e860363.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
