### ISSUE TITLE
Mali - Basler BT-67A

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2827]
### DB Selector

DB3K

### DBID to Copy

aircraft 3370

### Hypothetical

Yes

### Name

Basler BT-67A (Turbo DC-3)

### Country

Mali

### Service

Air Force

### In Commission

1998-

### Number in Service

1x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212378159-a6f85f80-fa8a-4c88-af2d-69e085ad7c93.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
