### ISSUE TITLE
Mali - Boeing 737-7BC BBJ

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2828]
### DB Selector

DB3K

### DBID to Copy

aircraft 3245

### Hypothetical

No

### Name

Boeing 737-7BC BBJ:

### Country

Mali

### Service

Air Force

### In Commission

2015-

### Number in Service

1x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

![image](https://user-images.githubusercontent.com/99599482/212378646-e75ba6dc-8c63-434e-8930-335ce918eee6.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
