### ISSUE TITLE
Mali - Orlan-10 UAV - 2021

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2829]
### DB Selector

DB3K

### DBID to Copy

aircraft 5808

### Hypothetical

No

### Name

Orlan-10 UAV

### Country

Mali

### Service

Air Force

### In Commission

2021-

### Number in Service

Unknown

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
