### ISSUE TITLE
Add Myanmar Makassar class LPD 1501 Moattama 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#283]
### DB Selector

DB3K

### DBID to Copy

Ship 2706

### Hypothetical

No

### Name

1501 Moattama [Makassar]

### Country

Myanmar

### Service

Navy

### In Commission

2021

### Sources

https://www.youtube.com/watch?v=dTeK5IXM9Sg
https://en.wikipedia.org/wiki/UMS_Moattama
https://twitter.com/CollinSLKoh/status/1364032130573983748
https://www.janes.com/defence-news/news-detail/myanmar-deploys-amphibious-ship-to-malaysia-as-part-of-repatriation-operations
https://aagth1.blogspot.com/2019/12/lpd-ums-moattama.html?spref=tw

**Comment by PygmalionOfCyprus** [comment]
Added 494.
