### ISSUE TITLE
Mali - Radar (Spoon Rest D [P-18])

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2830]
### DB Selector

DB3K

### DBID to Copy

facility 1317

### Hypothetical

No

### Name

Radar (Spoon Rest D [P-18])

### Country

Mali

### Service

Air Force

### In Commission

2022-

### Number in Service

uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2022/08/russias-african-offensive-russia-builds.html?m=1&fbclid=IwAR3KRCyD1jeeNOl9tgJgMZntdqNJuspv5YFKMb2uRJuTyaxO6AHaF9FrgJ4

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
