### ISSUE TITLE
Morocco -  R4E SkyEyes UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2831]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

 R4E SkyEyes 

### Country

Morocco

### Service

Air Force

### In Commission

Late 1980s, OOS Unknown

### Number in Service

uncertain

### Length (m)

4.10 m

### Wingspan (m)

7.32 m

### Height (m)

not stated

### Empty Weight (kg)

570 kg

### Maximum Takeoff Weight (MTOW) (kg)

Not Stated

### Payload Weight (kg)

82 kg

### Crew

0

### Propulsion

1 × UEL , 52 hp (39 kW)

### Rate of Climb (ft/min)

not stated

### Service Ceiling (ft)

15,000 ft

### Military/Afterburner Speed (kt)

109 kn

### Cruise Speed (kt)

Not Stated

### Supercruise

Yes

### Ferry Range (nm)

Not Stated

### Endurance (min)

>8 hours

### Takeoff / Landing Distance (m)

Catapault/Skid or parachute

### Fuel Capacity (kg)

Not Stated

### Sensors

EO/IR Turret

### Mounts

2x hardpoints

### Loadout Options

- Ferry
- Internal Recon

### Comms/Datalinks

UAV Datalink

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Service shrouded in secrecy. Uncertain of IOC and OOS.

### Sources

https://www.oryxspioenkop.com/2021/10/operating-from-shadows-moroccos-uav.html
https://en.wikipedia.org/wiki/BAE_Systems_SkyEye
https://en.ruvsa.com/catalog/skyeye_r4e_50_and_r4e_100/
https://www.designation-systems.net/dusrm/m-149.html

![image](https://user-images.githubusercontent.com/99599482/212381761-b81ca8d7-bd70-4802-88cf-4aa3c32244c5.png)

![image](https://user-images.githubusercontent.com/99599482/212381359-4016abd3-7595-4ed5-8d59-36cdb4e90c48.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
