### ISSUE TITLE
Morocco - Heron UAV - 2014

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2832]
### DB Selector

DB3K

### DBID to Copy

aircraft 2572

### Hypothetical

No

### Name

Heron UAV

### Country

Morocco

### Service

Air Force

### In Commission

2014-

### Number in Service

3x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Supplemented by 3x Harfang currently in DB from 2020

### Sources

https://www.oryxspioenkop.com/2021/10/operating-from-shadows-moroccos-uav.html

![image](https://user-images.githubusercontent.com/99599482/212382991-e88c1428-0490-4cfa-9edd-e07eef9f9ea9.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
