### ISSUE TITLE
Morocco - WD-1K Wing Loong [Pterodactyl] I UAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2833]
### DB Selector

DB3K

### DBID to Copy

aircraft 3310

### Hypothetical

No

### Name

WD-1K Wing Loong [Pterodactyl] I UAV

### Country

Morocco

### Service

Air Force

### In Commission

2020-

### Number in Service

3-4x, ex-UAE

### Sensors

No Changes

### Mounts

No Changes

### Loadout Options

No Changes

### Other Changes

No Changes

### Sources

https://www.oryxspioenkop.com/2021/10/operating-from-shadows-moroccos-uav.html

![image](https://user-images.githubusercontent.com/99599482/212385602-cc8e2fb8-ea61-4dba-a67c-c4ba30b5b945.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
