### ISSUE TITLE
Bayyenat-II missing illumination capability

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2834]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6998

### Description of Problem

The radar didn`t have illumination capability, thus Kowsar cannot use R-27R and Fakour-90 loadout.
![image](https://user-images.githubusercontent.com/99646926/212386969-983c75a8-6fe5-473e-96ec-b40a5d04f7c0.png)

### Recommended Fix

Add illumination capability to the radar to allow Kowsar to use R-27R and Fakour-90 loadout.

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
