### ISSUE TITLE
Dominican Republic - A-29B Super Tucano [EMB-314]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2836]
### DB Selector

DB3K

### DBID to Copy

aircraft 5361

### Hypothetical

No

### Name

A-29B Super Tucano [EMB-314]

### Country

Dominican Republic

### Service

Air Force

### In Commission

2009-

### Number in Service

8x

### Sensors

Remove Sensor Turret

### Mounts

No Change

### Loadout Options

Add Internal Guns

### Other Changes

N/A

### Sources

https://en.wikipedia.org/wiki/Embraer_EMB_314_Super_Tucano#Operators
https://en.wikipedia.org/wiki/Dominican_Air_Force
https://www.flightglobal.com/download?ac=90688

![image](https://user-images.githubusercontent.com/99599482/212391260-cba60b02-470e-455c-bfd3-46f769f06beb.png)
![image](https://user-images.githubusercontent.com/99599482/212391323-4df0bb05-6539-4b90-8d20-6a98b104bf03.png)
![image](https://user-images.githubusercontent.com/99599482/212391346-d11de6b1-120d-4373-8e47-2f7fe87821b0.png)
![image](https://user-images.githubusercontent.com/99599482/212391378-f082a1e1-201e-4019-9a33-5e10fab39f03.png)
![image](https://user-images.githubusercontent.com/99599482/212391399-6c039dde-0cce-4ffb-a501-87c9a3cdf8b4.png)
![image](https://user-images.githubusercontent.com/99599482/212391425-b24726a3-62ec-4d22-a2bf-a6c34da18281.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499. Added internal guns loadouts to all the Super Tucanos.
