### ISSUE TITLE
CA Motor Inf Plt (LAV-6.0 Upgrade x4) 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#284]
### DB Selector

DB3K

### DBID to Copy

2382 DB3K

### Hypothetical

No

### Name

Motor Inf Plt (LAV-6.0 x4)  x622

### Country

Canada

### Service

Canadian Army

### In Commission

2021

### Sensors

ADD:
- 1x Generic TV camera
- 1x Thermal Imaging System

### Mounts

- 1x C6 7.62-millimetre coaxial, medium machine gun
- 1x C9A2 5.56-millimetre light machine gun
- 1x 76-millimetre multi-barrel grenade discharger (MBGD) (smoke granades)

### Sources

https://en.wikipedia.org/wiki/LAV_III#LAV_6
http://www.army-armee.forces.gc.ca/en/equipment/vehicles/light-armoured-vehicle-upgrade.page

**Comment by Jkryos** [comment]
Added DB3K 501.
