### ISSUE TITLE
Dominican Republic - UH-1H Huey - 1996, Bell 205A-1

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2840]
### DB Selector

DB3K

### DBID to Copy

aircraft 1441

### Hypothetical

No

### Name

UH-1H Huey - 1996, Bell 205A-1

### Country

Dominican Republic

### Service

Air Force

### Number in Service

14x, 11x in service as of 2023

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://www.flightglobal.com/download?ac=90688
https://web.archive.org/web/20060720234958/http://www.aeroflight.co.uk/waf/americas/dominican_rep/DomRep-af-UH1.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
