### ISSUE TITLE
Dominican Republic - Piper PA-31 Navajo

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2842]
### DB Selector

DB3K

### DBID to Copy

aircraft 5351 

### Hypothetical

No

### Name

Piper PA-31 Navajo

### Country

Dominican Republic

### Service

Air Force

### In Commission

1988-present

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://www.flightglobal.com/download?ac=90688
https://web.archive.org/web/20060720235109/http://www.aeroflight.co.uk/waf/americas/dominican_rep/DomRep-af-PA31.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
