### ISSUE TITLE
Dominican REpublic - C-212-400E Aviocar

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2843]
### DB Selector

DB3K

### DBID to Copy

aircraft 3740

### Hypothetical

No

### Name

C-212-400E Aviocar

### Country

Dominican Republic

### Service

Air Force

### In Commission

2000-

### Number in Service

3x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://www.flightglobal.com/download?ac=90688
https://web.archive.org/web/20060721060959/http://www.aeroflight.co.uk/waf/americas/dominican_rep/DomRep-af-C212.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
