### ISSUE TITLE
Dominican Republic - OH-58A Kiowa [CH-136]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2844]
### DB Selector

DB3K

### DBID to Copy

aircraft 5774

### Hypothetical

Yes

### Name

OH-58A Kiowa [CH-136]

### Country

Dominican Republic

### Service

Air Force

### In Commission

2005-

### Number in Service

20x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://www.flightglobal.com/download?ac=90688
https://web.archive.org/web/20071203173344/http://www.aeroflight.co.uk/waf/americas/dominican_rep/DomRep-af-EscHel.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
