### ISSUE TITLE
Dominican Republic - O-2A Super Skymaster

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2846]
### DB Selector

DB3K

### DBID to Copy

aircraft 3907

### Hypothetical

Yes

### Name

O-2A Super Skymaster

### Country

Dominican Republic

### Service

Air Force

### In Commission

1988-2000

### Number in Service

5x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://web.archive.org/web/20071203173339/http://www.aeroflight.co.uk/waf/americas/dominican_rep/DomRep-af-EscCombate.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
