### ISSUE TITLE
Dominican Republic - A-37B Dragonfly [Super Tweet]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2847]
### DB Selector

DB3K

### DBID to Copy

aircraft 1428

### Hypothetical

Yes

### Name

A-37B Dragonfly [Super Tweet]

### Country

Dominican Republic

### Service

Air Force

### In Commission

1984-2002

### Number in Service

8x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Cessna_A-37_Dragonfly#Former
https://web.archive.org/web/20071203173339/http://www.aeroflight.co.uk/waf/americas/dominican_rep/DomRep-af-EscCombate.htm

![image](https://user-images.githubusercontent.com/99599482/212405469-cfbe7d77-ba6c-463a-970f-af919cb4ae40.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
