### ISSUE TITLE
Dominican Republic -OH-6A Cayuse [MD-500D]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2848]
### DB Selector

DB3K

### DBID to Copy

aircraft 2907

### Hypothetical

Yes

### Name

OH-6A Cayuse [MD-500D]

### Country

Dominican Republic

### Service

Air Force

### In Commission

1971-2000

### Number in Service

11x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No CHanges

### Sources

http://www.aeroflight.co.uk/waf/americas/dominican_rep/DomRep-af-EscHel.htm
https://en.wikipedia.org/wiki/Hughes_OH-6_Cayuse#Former_operators

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
