### ISSUE TITLE
Dominican Republic - R44 Raven II

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2849]
### DB Selector

DB3K

### DBID to Copy

aircraft 5531

### Hypothetical

No

### Name

R44 Raven II

### Country

Dominican Republic

### Service

Air Force

### In Commission

Uncertain

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Robinson_R44#Military_and_government_operators
https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://www.flightglobal.com/download?ac=90688

![image](https://user-images.githubusercontent.com/99599482/212411707-d4a8dabd-3ecd-4fdb-bb16-cfd96c690386.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
