### ISSUE TITLE
Dominican Republic - Cessna 208B Grand Caravan EX

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2851]
### DB Selector

DB3K

### DBID to Copy

aircraft 5379

### Hypothetical

No

### Name

Cessna 208B Grand Caravan EX

### Country

Dominican Republic

### Service

Air Force

### In Commission

2022-

### Number in Service

1x delivered total planned not disclosed

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://www.flightglobal.com/download?ac=90688
https://www.janes.com/defence-news/news-detail/dominican-republic-to-receive-grand-caravan-ex-aircraft

![image](https://user-images.githubusercontent.com/99599482/212409121-c94b5d4e-a2a2-4983-8ec7-070886bc3b4c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
