### ISSUE TITLE
Dominican Republic - Cessna 404 Titan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2852]
### DB Selector

DB3K

### DBID to Copy

aircraft 5350

### Hypothetical

No

### Name

Cessna 404 Titan

### Country

Dominican Republic

### Service

Air Force

### In Commission

SEIZED 2016 from Drug Smugglers

### Number in Service

1x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://en.wikipedia.org/wiki/Cessna_404_Titan#Military_operators
https://www.flightglobal.com/download?ac=90688

![image](https://user-images.githubusercontent.com/99599482/212410245-40024526-f902-4c00-ae66-3b8eeb05790f.png)
![image](https://user-images.githubusercontent.com/99599482/212411274-95aa96a5-1941-4b30-8c23-d7ce91e16624.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
