### ISSUE TITLE
Dominican Republic - Turbo Commander 690B

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2853]
### DB Selector

DB3K

### DBID to Copy

aircraft 5779

### Hypothetical

Yes

### Name

Turbo Commander 690B

### Country

Dominican Republic

### Service

Air Force

### In Commission

Impounded 2009

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Dominican_Air_Force#Equipment
https://www.flightglobal.com/download?ac=90688

![image](https://user-images.githubusercontent.com/99599482/212410970-c5394a41-ee70-4cf1-84b3-134d4e3c13f0.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
