### ISSUE TITLE
F9F-8T / TF-9J Cougar

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2855]
### DB Selector

CWDB

### DBID to Copy

aircraft 424

### Hypothetical

No

### Name

TF-9J (F9F-8T) Cougar

### Country

United States

### Service

Navy, Marine Corps

### In Commission

1956-

### Sensors

No Change

### Mounts

Reduce 20mm from 4x to 2x

### Loadout Options

Same as for F9F-8

plus

-Training
-Battlefield Observation (Unarmed) - USMC only
-Battlefield Observation (Armed), 2x rocket pods as below image. - USMC Only

### Other Changes

Update crew to 2

"The Navy acquired 377 two-seat F9F-8T trainers between 1956 and 1960. They were used for advanced training, weapons training, and carrier training, and served until 1974. They were armed with twin 20 mm (.79 in) cannon and could carry a full bombs or missiles load. In the 1962 redesignation, these were later called TF-9J."

"The only version of the Cougar to see combat was the TF-9J trainer (known as F9F-8T until 1962) during the Vietnam War. Detachments of four Cougars served with US Marines Headquarters and Maintenance Squadron 11 (H&MS-11) at Da Nang and H&MS-13 at Chu Lai, where they were used for fast-Forward Air Control and the airborne command role, directing airstrikes against enemy positions in South Vietnam between 1966 and 1968."

### Sources

https://en.wikipedia.org/wiki/Grumman_F-9_Cougar#Variants
https://en.wikipedia.org/wiki/Grumman_F-9_Cougar#F9F-8
https://www.history.navy.mil/content/history/museums/nnam/explore/collections/aircraft/f/f9f-8-cougar.html
http://www.joebaugher.com/navy_fighters/f9_14.html

![image](https://user-images.githubusercontent.com/99599482/212422825-07fb7335-54d9-4eee-9159-80ba6f32ef16.png)
A TF-9J (F9F-8T) of H&MS-13 at Chu Lai, Vietnam 1967

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
