### ISSUE TITLE
Reduce Loiter Speed of HC-130J Combat King II

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#2860]
### DB Selector

DB3K

### Affected DBID(s)

# 3215 HC-130J Combat King II, United States, 2013-

### Summary of Changes

- Reduce Minimum Speed from **210 Kts** to **140 Kts** same MC-130J Commando II as it currently not able to slow enough to refuel helicopters. [1]

_"The HC-130J replaces HC-130P/Ns as the only dedicated fixed-wing Personnel Recovery platform in the Air Force inventory. It is an extended-range version of the C-130J Hercules transport. Its mission is to rapidly deploy to execute combatant commander directed recovery operations to austere airfields and denied territory for expeditionary, all weather personnel recovery operations to include airdrop, airland, helicopter air-to-air refueling, and forward area ground refueling missions. When tasked, the aircraft also conducts humanitarian assistance operations, disaster response, security cooperation/aviation advisory, emergency aeromedical evacuation, and noncombatant evacuation operations."_ [1]

- Change Type from **Transport** to **Combat Search and Rescue (CSAR)**.
- Reduce Length from **29.8m** to **29.57m**. [1]
- Reduce Height from **11.8m** to **11.58m**. [1]
- Reduce Max Weight from **79,200 Kg** to **74,389 Kg**. [1]
- Increase Empty Weight from **34,200 Kg** to **40,369 Kg**. [1]
- Reduce Max Payload from 20,000 Kg to 15,875 Kg. [1]

### Sources

[1] https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104468/hc-130j-combat-king-ii/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
