### ISSUE TITLE
Update/correction for Tarlan/Ya Mahdi Unmanned Surface Vessel

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2861]
### DB Selector

DB3K

### Affected DBID(s)

Ship 4108

### Summary of Changes

-  Reduce the crew from 3 to 0. The vessel is described as unmanned.
_"The Iranian Revolutionary Guard Corps Navy's "Ya Mahdi" (a reference to Shia Islam's 12th Imam) unmanned surface vessel was first publicly described in 2010 as a remotely controlled fast attack craft."_

- Change the vessel`s category from "PT - Patrol Torpedo Boat" to "USV -  Unmanned Surface Vessel"

- Change the 2x 324mm single torpedo tube to 2x 533mm single torpedo tube that only contained Hoot torpedo (Weapon/4158). 
![image](https://user-images.githubusercontent.com/99646926/212474568-f02fe443-e3f7-4d69-93a5-9d6f9d3a251a.png)

- Change Pier/Dock/Davits Size from Medium Pier to Very Small Dock/Davit, same as similar-sized Seagull USV.

### Sources

- http://www.navaldrones.com/Ya-Mahdi.html
- https://www.youtube.com/watch?v=rLdsvfBWLrI
- https://www.youtube.com/watch?v=3hYxTTmtNu0

**Comment by Jkryos** [comment]
Updated DB3K 499.
