### ISSUE TITLE
Update/correction for IRIS Makran

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2862]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3769

### Summary of Changes

- Change the 1x Davit (6x Very Small Vessel) to 1x Davit(8x Medium Dock). The ship have the capacity to carry up to 7-8 Peykaap-II missile boats at least.
![image](https://user-images.githubusercontent.com/99646926/212476496-02ca4b2b-758b-4d86-ba5a-3c80d6461e8d.png)

- Add Davit/Crane/Shelter (4x ROV/UUV). The ship can carry at least 4x Al-Sabehat 15 SDV.
_"Among the boats seen on board are fast infantry landing craft, rocket armed RIBs are Swimmer Delivery Vehicles (SDVs). Four Al-Sabehat 15 SDVs were aboard in December 2020"_
![image](https://user-images.githubusercontent.com/99646926/212476686-a3bf78a9-fa73-4aca-8dc1-5b64a9983092.png)

- Add aviation fuel to the vessel since the ship can support helicopter operation. 
_" All helicopters can sit on it and perform helicopter operations and even have the possibility of maintenance and refueling"_

### Sources

- http://www.hisutton.com/OSINT-Update-Makran-Iran-Venezuela.html
- https://news.usni.org/2021/06/01/iranian-warship-thought-to-be-headed-to-venezuela-left-port-with-7-high-speed-missile-boats-aboard
- https://twitter.com/mhmiranusa/status/1400817028513124359?lang=en
- https://www.globalsecurity.org/military/world/iran/irins-makran.htm

**Comment by Jkryos** [comment]
Added DB3K 499.
