### ISSUE TITLE
Update/correction of Pier/Dock/Davits Size for Peykaap series boat

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2863]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2093, 2097, 2098, 4102, 4103

### Summary of Changes

- Change the "Pier/Dock/Davits Size" from "Small Pier" to "Small Dock/Davit". The boat can be carried by IRIS Makran.
![image](https://user-images.githubusercontent.com/99646926/212480597-b335e832-5f51-417e-b6a1-89b2ee279783.png)

### Sources

- http://www.hisutton.com/OSINT-Update-Makran-Iran-Venezuela.html
- https://news.usni.org/2021/06/01/iranian-warship-thought-to-be-headed-to-venezuela-left-port-with-7-high-speed-missile-boats-aboard
- https://twitter.com/mhmiranusa/status/1400817028513124359?lang=en

**Comment by Jkryos** [comment]
Updated DB3K 499.
