### ISSUE TITLE
Addition: China, PLAAF/PLANAF, WZ-10, Wing Loong-10 UCAV

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2864]
### DB Selector

DB3K

### Baseline

aircraft 5385

### Hypothetical

No

### Name

WZ-10, Wing Loong-10

### Country

China

### Service

Air Force

### In Commission

2023

### Length (m)

9

### Wingspan (m)

20

### Height (m)

3.66

### Empty Weight (kg)

2300

### Maximum Takeoff Weight (MTOW) (kg)

3200

### Payload Weight (kg)

600

### Crew

0

### Propulsion

2 × AEF-50E

### Service Ceiling (ft)

45000

### Military/Afterburner Speed (kt)

480

### Cruise Speed (kt)

330

### Supercruise

No

### Ferry Range (nm)

6600

### Sensors

1x AESA
1x ISAR
1x ELINT
1x EO/IR
1x Laser Designator

### Mounts

-

### Loadout Options

- 8x LS-6-50/100 GPS/INS
- 4x YJ-9
- 8x AG-300M AGM
- 8x FT-7A/W LG SDB
- 8x LJ-7 ATGM
- 8x TY-90 AAM
- 4x TL-20 LGB
- Recon
- 1x Generic OECM [Advanced] (2020s)

### Sources

https://en.wikipedia.org/wiki/Chengdu_WZ-10#Specifications_(Cloud_Shadow)
https://www.janes.com/defence-news/news-detail/airshow-china-2022-avic-displays-wing-loong-10-in-plaaf-colour
https://www.airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/november/8813-airshow-china-2022-china-displays-wing-loong-10-electronic-warfare-uav-entering-service-with-pla-air-force.html
https://www.janes.com/defence-news/news-detail/wds-2024-avic-wl-10b-to-be-delivered-to-royal-saudi-air-force

**Comment by PygmalionOfCyprus** [comment]
I don't think the PLA version is armed or has an EO/IR ball or AESA radar. It's widely reported as being an EW platform, there's little room in the front for an AESA (looks like [camera for the remote pilot](https://pbs.twimg.com/media/Fg7vuUeUoAAoTPT?format=jpg&name=large) instead?), and definitely no EO ball visible unless I'm stupid.

Grant that the export version is armed, has EO, etc. but the PLA isn't using that version.

Added with tweaks 506.
