### ISSUE TITLE
Add military version of IrAn-140 (Iranian version of AN-140).

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2865]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4025

### Hypothetical

Yes

### Name

IrAn-140MP, IrAn-140AEW and IrAn-140T

### Country

Iran

### Service

Air Force

### Sensors

IrAn-140T
- Retains existing Generic Navigation Radar
- Add Generic RWR and MAWS
![image](https://user-images.githubusercontent.com/99646926/212533819-c448147c-70fe-4ea3-9db4-cc8cb8f23155.png)

IrAn-140AEW
- Retains existing Generic Navigation Radar
- Add Generic 3D Search Radar [Long Range] (AWACS)
- Add Generic RWR and MAWS
![image](https://user-images.githubusercontent.com/99646926/212532222-82d697f9-4fe6-462c-825f-e639777e43fc.png)

IrAn-140MP [HMS-200]
- Retains existing Generic Navigation Radar
- Add Generic Surface Search Radar
- Add Generic FLIR
![image](https://user-images.githubusercontent.com/99646926/212532094-0b6521b4-6d93-4fba-87aa-d3fdfea39a91.png)

IrAn-140MP [HMS-400]
- Retains existing Generic Navigation Radar
- Add Generic Surface Search Radar
- Add Generic FLIR
- Add Generic ESM
- Add Generic RWR and MAWS
![image](https://user-images.githubusercontent.com/99646926/212532115-c210422f-96c0-4d32-a827-5f00bfc9d3fb.png)

IrAn-140MP [HMS-500]
- Retains existing Generic Navigation Radar
- Add Generic Surface Search Radar
- Add Generic FLIR
- Add Generic MAD
- Add Generic RWR and MAWS
![image](https://user-images.githubusercontent.com/99646926/212532205-f9c9a502-854c-40aa-9555-cab205a3b6b3.png)

### Mounts

IrAn-140T
- Add Chaff/Flare dispenser

IrAn-140AEW
- Add Chaff/Flare dispenser

IrAn-140MP [HMS-200]
- Add Chaff/Flare dispenser

IrAn-140MP [HMS-400]
- Add Chaff/Flare dispenser

IrAn-140MP [HMS-500]
- Add Chaff/Flare dispenser

### Loadout Options

IrAn-140T
1. Troop Transport Loadout:  
    - 38x Troopers
    
2. Paratrooper Transport Loadout:  
    - 38x paratroopers

3. Cargo loadout
   - Cargo  6 tons [Air Drop] & [No Drop]

IrAn-140AEW
1. AEW Probably same as ferry range)

IrAn-140MP [HMS-200]
1. Area Surveillance 

IrAn-140MP [HMS-400]
1. ELINT Surveillance 

IrAn-140MP [HMS-500]
1. AShM + Torpedo Loadout
  - 2x C-704
  - 2x Mk46 LWT Mod 2
  - 80x Generic Passive Directional Sonobouy
  - 20x Generic Active Directional Sonobouy
 
2. Torpedo-only Loadout
  - 4x Mk46 LWT Mod 2
  - 80x Generic Passive Directional Sonobouy
  - 20x Generic Active Directional Sonobouy
  
_"HESA will eventually offer four variants of the Oghab. (HMS-100; HMS-200; HMS-400; HMS-500) The one that has just been unveiled is reported to be the "HMS-200" variant and doesn't have any offensive capabilities. Other versions will sports submarine detection systems, pollution detection system and offensive weapons such as torpedoes and anti-ship missiles according to models showcased in the past by HESA."_

### Sources

- https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/year-2012-news/may/450-iran-unveils-new-qoghabq-maritime-patrol-aircraft-based-on-antonov-an-140-.html
- https://www.key.aero/forum/modern-military-aviation/65329-the-balance-of-iranian-air-forces?p=1564701&page=1
- https://www.secretprojects.co.uk/threads/iranian-indigenous-fighter-projects-saeqeh-etc.732/page-4
- https://www.dropbox.com/sh/r4zt23du7ho8w3l/AACJpyPzC8BIwHWEP0ZI6pETa?dl=0
- https://www.globalsecurity.org/military/world/iran/iran-140.htm
- https://defence-blog.com/iran-has-developed-a-new-military-transport-aircraft-faraz-140t/

**Comment by capcop98** [comment]
All IrAn-140, including the commercial version should have Glass Cockpit[Partial] instead of Steam Gauge. The aircraft were seen with at least one MFD.
![image](https://user-images.githubusercontent.com/99646926/212540219-e8bdfbb2-c885-4a9d-8d3a-c2d13e45a806.png)

**Comment by PygmalionOfCyprus** [comment]
Added 499. I don't think that puny little screen counts as "partial glass." :P
