### ISSUE TITLE
Please consider adding KH-15S Loadout to the Tu-160 & Tu-160M

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#287]
### DB Selector

DB3K

### User(s)

1. Tu-160 (DBID's: 280, 357, 408, & 1465) 
2. Tu-160M (DBID: 5554) 

### Weapons Carried

12x Kh-15S Anti-Ship Missiles in 2x *Internal* MKU-6-1 Rotary Launcher Pods

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

3000

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

The Kh-15S is not currently part of the database, but a new weapon DB request has been submitted in issue #254 ...

### Sources

1. https://www.weaponsystems.net/system/99-Raduga+Kh-15
2. https://military-history.fandom.com/wiki/Kh-15

**Comment by PygmalionOfCyprus** [comment]
Added w/ #254.
