### ISSUE TITLE
Addition: Iran, Su-35SE Flanker M

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2873]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2689

### Hypothetical

No

### Name

Su-35SE Flanker M

### Country

Iran

### Service

Islamic Republic of Iran Air Force / IRIAF

### In Commission

2023

### Number in Service

24x

### Sources

https://www.bloomberg.com/news/articles/2023-01-15/iran-expects-delivery-of-russian-sukhoi-fighter-jets-by-march-tasnim-says
https://eurasiantimes.com/leaving-the-west-baffled-iran-confirms-purchasing-24-russian/
https://theaviationgeekclub.com/iranian-minister-of-defense-has-confirmed-that-iriaf-will-receive-the-sukhoi-su-35se-flanker-e-fighter-jets-originally-ordered-by-egypt/

**Comment by PygmalionOfCyprus** [comment]
Was already added in a prior DB release.
