### ISSUE TITLE
Addition: China, PLAAF, YJ1000-1 "bunker buster" LGB

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2874]
### DB Selector

DB3K

### Baseline

weapon 3077

### Hypothetical

No

### Name

YJ1000-1 LGB [KAB-1500Kr-Pr copy]

### Length (m)

same as KAB-1500

### Width/Span (m)

same as KAB-1500

### Diameter (m)

same as KAB-1500

### Weight (kg)

same as KAB-1500

### Range (nm)

same as KAB-1500

### Warhead

FAB-1500 penetrator (750kg HE) (750 DP)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### Sensors

same as KAB-1500

### Comments

Once China imported Russian KAB-1500 for its Su-30MKK. This weapon is believed to be the tech origin of YJ1000-1.

### Sources

https://de.wikipedia.org/wiki/KAB-1500#cite_note-10
http://chinese-military-aviation.blogspot.com/p/missiles-iii.html
![image](https://user-images.githubusercontent.com/107970049/212875894-578e7614-f662-4059-8401-406441a2009f.png)
![image](https://user-images.githubusercontent.com/107970049/212875983-0c78359c-b82f-46bf-91a3-9e615b50408b.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
