### ISSUE TITLE
Loadout: PLAAF, JH-7A2, J-16, YJ1000-1 Loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2875]
### DB Selector

DB3K

### User(s)

PLAAF J-16, 2018 (aircraft 4926); PLAAF JH-7A2, 2019 (aircraft 4905)

### Weapons Carried

For J-16:
2x YJ1000-1, 2x PL-15, 2x PL-10, 1x K/JDC-1A FLIR, 1x KG-600

For JH-7A2:
2x YJ1000-1, 2x PL-8, 1x KG-600, 1x K/JDC-1A FLIR, 2x 1400 liter drop tank

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

#

**Comment by LuigiP57** [comment]
#2874

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
