### ISSUE TITLE
Tu-22M-3M Kh-22 Ukraine War loadouts

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2878]
### DB Selector

DB3K

### User(s)

Aircraft 4951

### Weapons Carried

2x or 3x Kh-22 (AS-4)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

2096nm (3x missiles), 2270nm (3x missiles)

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Older Kh-22 missiles returned to service in Ukraine War. Apparently anti-ship models being launched using INS guidance only with accordingly poor accuracy.

### Sources

https://www.thedrive.com/the-war-zone/ukraine-situation-report-kyiv-says-it-has-no-defense-against-russias-kh-22-missiles?fbclid=IwAR0jDJCOHX-JgO440VI5CKZykQwcTKWaGqgwLW0f6wIFjh_TyT27_iWX8SY
https://www.thedrive.com/the-war-zone/we-may-have-our-first-sight-of-a-russian-bomber-launching-missiles-at-ukraine
https://www.thedrive.com/the-war-zone/russias-secretive-long-range-bomber-operations-against-ukraine
https://www.thedrive.com/the-war-zone/ukraine-situation-report-u-s-confirms-nasams-air-defense-system-transfer

![image](https://user-images.githubusercontent.com/99599482/213203089-c9ffcba7-6c8e-4aaa-9ae7-997c27c0f0e9.png)
![image](https://user-images.githubusercontent.com/99599482/213203246-50d4343e-71f9-41a2-b0ee-8aaa95f20f79.png)
![image](https://user-images.githubusercontent.com/99599482/213204713-7aed554b-8b91-4c9c-bb70-23e1db5726c7.png)

**Comment by HVAA** [comment]
All the open source imagery in your links suggest no more than two missiles per aircraft.  The strain and risk of carrying 3 missiles probably (almost certainly) isnt worth the risk of carriage on this ageing and irreplaceable fleet of bombers. Couple the fact now that the Ukr actions have almost certainly forced them further afield makes this load unlikely even if they were prepared to accept the risk.

**Comment by tbrandon517** [comment]
> All the open source imagery in your links suggest no more than two missiles per aircraft. The strain and risk of carrying 3 missiles probably (almost certainly) isnt worth the risk of carriage on this ageing and irreplaceable fleet of bombers. Couple the fact now that the Ukr actions have almost certainly forced them further afield makes this load unlikely even if they were prepared to accept the risk.

I'd say that's fair enough pending any additional photographic evidence.

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
