### ISSUE TITLE
Add Ukrainian 9M79-1 Tochka-U Missile 1992

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#288]
### DB Selector

DB3K

### DBID to Copy

Facility #840 and 627

### Hypothetical

No

### Name

SS-21b Scarab/9M79-1 Tochka-U SSM BN

### Country

Ukraine

### Service

Army

### In Commission

1992

### Sources

https://twitter.com/RALee85/status/1421557453167153152
https://frontierindia.com/ukraine-modifies-tochka-u-short-range-ballistic-missile/
https://www.youtube.com/watch?v=G8g3eTM6i8o
https://petrimazepa.com/goddot.html

**Comment by PygmalionOfCyprus** [comment]
Added 493. Slava Ukraini.

We don't have time to slip a national review of Ukraine into 493 but I'd like to get them cleaned up for 494.

**Comment by bostonmyk** [comment]
Dyakuyu. This second generation Uke here is very happy with that. Lets hope Ukraine lasts until then.
