### ISSUE TITLE
Update Tu-160 AS-16 Loadouts

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2880]
### DB Selector

DB3K

### Affected DBID(s)

Tu-160 Blackjacks

### Summary of Changes

Request update to make As-17 loadouts consistent. Original nuclear loadouts for AS-16 have 24x missiles while the newer addition ASM, ARM, and conventional loadouts have 6x missiles which match the Tu-95 loadouts.  

### Sources

![image](https://user-images.githubusercontent.com/99599482/213219900-27bbcb68-0093-4d1a-b2a5-a1c30e6395d1.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
