### ISSUE TITLE
Ukraine - Tu-141 and Tu-143 Cruise Missile Mods

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2882]
### DB Selector

DB3K

### Baseline

Aircraft 2568 and 2569

### Hypothetical

No

### Name

Tu-141 Cruise Missile Mod, tu-143 Cruise Missile Mod

### Length (m)

Same as Tu-141 or Tu-143

### Width/Span (m)

Same as Tu-141 or Tu-143

### Diameter (m)

Same as Tu-141 or Tu-143

### Weight (kg)

Same as Tu-141 or Tu-143

### Range (nm)

640nm (Tu-141) 220nm (Tu-143)

### Target Altitude / Depth (ft)

Ground

### Target Speed (kts)

Fixed

### Launch Altitude / Depth (ft)

Ground

### LaunchSpeed (kts)

Stantionary

### Warhead

75kg warhead replaced cameras

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway

### CEP (m)

uncertain

### Sensors

INS Guidance

### Weapon Codes

Terrain Following, Bearing-Only Launch (BOL), Weapon - INS Navigation, Weapon - Pre-Briefed Target Only, Level Cruise Flight

### Comments

Reconnaissance drone conversions probably have low level and high level attack profiles based on recon drone profiles.

### Sources

https://www.forbes.com/sites/davidaxe/2022/12/05/ukraine-pulled-ex-soviet-recon-drones-out-of-storage-added-bombs-and-sent-them-hurtling-toward-russia/?sh=7f11ee1f3348&fbclid=IwAR2oqC94oij-DR7jMkoI3TCK7nM-CrXoKPVHsrgyLe2fZCfEKUJ5iBaCKB4
https://www.thedrive.com/the-war-zone/44753/croatians-say-mysterious-crashed-tu-141-drone-tied-to-the-ukraine-conflict-carried-a-bomb
https://www.thedrive.com/the-war-zone/russian-airfield-in-kursk-set-ablaze-by-apparent-ukrainian-drone-strike?fbclid=IwAR1Rjpt38sclIkg3wwKPBCE7bFiy0sLwL43rVieLAtRcsh5Dl3kHo93fD1g
https://www.thedrive.com/the-war-zone/ukraine-modified-soviet-era-jet-drones-to-hit-bomber-bases-russia-claims?fbclid=IwAR3nXpCd2iUWHLrno4Wbzx_FLc2WATlS98IA2x2Y7n701jrd6iVBU6eYXzQ

![image](https://user-images.githubusercontent.com/99599482/213231323-aecd7502-4b26-4055-9200-8b7e81b6e9bf.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
