### ISSUE TITLE
Ukraine - USV Suicide Boat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2883]
### DB Selector

DB3K

### Baseline

Ship 3849 GARC-FS

### Hypothetical

No

### Name

USV Suicide Boat

### Class

USV

### Country

Ukraine

### Service

Navy

### In Commission

2022-

### Number in Service

100+

### Length (m)

5.5 meters

### Beam (m)

Not Stated

### Draft (m)

Not Stated

### Standard Displacement (t)

Not Stated

### Full Displacement (t)

1,000 kg

### Empty Displacement (t)

Not Stated

### Complement

0

### Primary Propulsion Type

Diesel

### Propulsion

1 Waterjet powered by 3 cylinder Rotax gasoline engine

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

43 knots

### Range (nm) at Speed (kt)

430 NM

### Sensors

1x EO Sensor top amidships
1x EO Sensor at bow

### Mounts

1x USV Suicide Charge, 2x FAB-500 Fuses

### Aircraft & Docking Facilities

None

### Comms/Datalinks

Starlink SATCOM

### Ship Codes

All Aluminum Construction

### Sources

https://news.usni.org/2022/10/11/suspected-ukrainian-explosive-sea-drone-made-from-jet-ski-parts?fbclid=IwAR0kvsuFXWKrAA_VwrLnDuP5buPdk8qZ3604Oe7ETlxJVoyvXPe8g_vRvU4
http://www.hisutton.com/Ukraine-Maritime-Drones.html?fbclid=IwAR2sRdQRIbRIgRsv2dr8Ow85Yxwf0uIGtYRKpd5QBxbrjZa4Gg_Sy0Mf_M4
https://www.thedrive.com/the-war-zone/ukraines-shadowy-kamikaze-drone-boats-officially-break-cover?fbclid=IwAR1zsb_ozO06GaFN00UNPh0BQNRrxICu9JP_vUKcMfwapyA-cDyT2YKoz9A

![image](https://user-images.githubusercontent.com/99599482/213234609-77b12e37-4232-4739-a509-ac8167e06b06.png)
![image](https://user-images.githubusercontent.com/99599482/213234679-da8e4f65-7573-4137-8a2e-3514d1f69f34.png)
![image](https://user-images.githubusercontent.com/99599482/213235754-87dda798-5822-4d44-bf90-aa4a22204256.png)

**Comment by tbrandon517** [comment]
Design evolution plus Russian "clone"

http://www.hisutton.com/Ukraine-Maritime-Drones-Evolution.html

**Comment by tbrandon517** [comment]
Update 

http://www.hisutton.com/Ukraine-Maritime-Drones-JetSki.html

**Comment by tbrandon517** [comment]
Sea Baby model

http://www.hisutton.com/Ukraine-USV-Sea-Baby.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
