### ISSUE TITLE
China - Hunting Eagle Strike Gyrocopter

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2885]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

Hunting Eagle Strike Gyrocopter

### Country

China

### Service

PLA Special Forces, People’s Armed Police (PAP)

### In Commission

2015-

### Number in Service

uncertain

### Length (m)

not stated

### Wingspan (m)

8.4 m

### Height (m)

not stated

### Empty Weight (kg)

290 kg

### Maximum Takeoff Weight (MTOW) (kg)

560 kg

### Payload Weight (kg)

220 kg

### Crew

1 pilot, 1-2x passengers

### Propulsion

1 × Rotax 914 four cylinder, liquid and air-cooled, four stroke turbocharged aircraft engine, 75 kW (100 hp)

### Rate of Climb (ft/min)

490 ft/min

### Service Ceiling (ft)

17388 ft

### Military/Afterburner Speed (kt)

97 kn

### Cruise Speed (kt)

81 kn

### Supercruise

No

### Ferry Range (nm)

217nm

### Endurance (min)

Not Stated

### Takeoff / Landing Distance (m)

10-70m/0-10m

### Fuel Capacity (kg)

70 litres

### Sensors

1x EO/IR Turret

### Mounts

N/A

### Loadout Options

-Ferry
-Training
-Unarmed Reconissance
-4x ATGM HJ-8?
-2x small missiles AR-2?

### Comms/Datalinks

VHF/UHF

### Aircraft Codes

Bombsight - Basic

### Comments

The Falcon was designed for police and military use as a surveillance aircraft.

The basic model of the aircraft is a two-seater. An upgraded three-seater version of the aircraft also exists. The three-seat variant feature a 135 hp (101 kW) engine, a larger fuel tank made from different materials, to give greater range, and allow the transportation of more cargo, as well as for parachuting operations.

### Sources

https://en.wikipedia.org/wiki/Shaanxi_Baojii_Special_Vehicles_Lie_Ying_Falcon#:~:text=The%20Shaanxi%20Baojii%20Special%20Vehicles,of%20Baoji%20in%20Shaanxi%20province.
https://www.thedrive.com/the-war-zone/china-touts-gyrocopters-armed-with-anti-tank-missiles?fbclid=IwAR1kqFawQq3DcNSFAbBl4cZW6Hd-KXLQNri5R8vab2Dwmx3baQ4Dm6xgnQE
https://gagadget.com/en/weapons/159616-china-unveiled-a-gyrocopter-with-anti-tank-guided-missiles/
https://www.defenseworld.net/2019/10/08/bizarre-looking-rotorcraft-is-chinas-special-ops-stealth-gyroplane.html
https://sofrep.com/news/chinas-hunting-eagle-stirke-gyrocopters-boasts-of-anti-tank-missiles/

![image](https://user-images.githubusercontent.com/99599482/213251614-6f782a49-5d95-49f4-a47b-e13d8c9fe449.png)
![image](https://user-images.githubusercontent.com/99599482/213252573-a05f90fd-5b20-4187-a421-061c023d3e3e.png)
![image](https://user-images.githubusercontent.com/99599482/213252609-98429d93-d92c-455a-9b78-45408e96096a.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
