### ISSUE TITLE
Update - B-52 Hercules troop capacity

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2887]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1423

### Summary of Changes

Update troop capacity from 25 to 238.

### Sources

https://en.wikipedia.org/wiki/ARA_H%C3%A9rcules_(B-52)

**Comment by PygmalionOfCyprus** [comment]
Handled 500, also updated crew count.
