### ISSUE TITLE
United States - WPB 87367 SEA DRAGON [Marine Protector] 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2888]
### DB Selector

DB3K

### DBID to Copy

Ship 2437

### Hypothetical

No

### Name

WPB 87367 SEA DRAGON [Marine Protector] 

### Country

United States

### Service

Coast Guard

### In Commission

2007-

### Number in Service

4x

### Sensors

No Change

### Mounts

In addition to the existing 12.7mm HMGs

ADD

1x 12.7mm in a gyro stabilized Protector RWS forward on a raised platform to increase field of fire and accuracy.

### Loadout Options

N/A

### Other Changes

Increase crew to 15

4x units funded by the US Navy for 2 Maritime Force Protection Units. 1 unit with 2 cutters assigned to each SSBN base for escort of SSBNs in and out of port.

SEA DRAGON    WPB 87367    Delivered NOV 2007   Kings Bay, GA
SEA DEVIL          WPB 87368    Delivered Feb 2008    Bangor, WA
SEA DOG            WPB 87373    Delivered April 2009   Kings Bay, GA
SEA FOX             WPB 87374    Delivered May 2009    Bangor, WA

### Sources

https://chuckhillscgblog.net/2012/10/29/cg-maritime-force-protection-units/
https://en.wikipedia.org/wiki/USCGC_Sea_Fox
https://en.wikipedia.org/wiki/USCGC_Sea_Devil
https://en.wikipedia.org/wiki/USCGC_Sea_Dragon
https://en.wikipedia.org/wiki/Protector_RWS

![image](https://user-images.githubusercontent.com/99599482/213274519-31042a81-2891-464e-b6b5-01fa9685cd94.png)
![image](https://user-images.githubusercontent.com/99599482/213275047-f5be0e1e-362a-4e61-8e9c-2ce2fe1f571d.png)
![image](https://user-images.githubusercontent.com/99599482/213275410-78dde1db-89da-41c0-bc3f-7dc483e7dce5.png)
![image](https://user-images.githubusercontent.com/99599482/213275447-ace4cea6-3539-4281-9270-ce2051e6492f.png)
![image](https://user-images.githubusercontent.com/99599482/213275936-adb6344f-7d49-46c0-acfc-db6a4228101b.png)

**Comment by Jkryos** [comment]
Added DB3K 501.
