### ISSUE TITLE
Add S3V Zagon KAB-250 depth charge to Russian and Chinese helo's and MPA's. Russia IOC at least 2016

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#289]
### DB Selector

DB3K

### User(s)

Russian and Chinese ASW Helo and MPA.

### Weapons Carried

Copy older Depth Charge configurations for most.
2 for each helo

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Zagon S3V is a guided depth charge with effective depths of 150m to 600m. 4th and 5th link. Zagon on Y-8Q. 7th link Z-30F (4). 9th and 10th link IL-38

### Sources

http://eng.ktrv.ru/production/military_production/smart_bombs/zagon-1.html
https://en.wikipedia.org/wiki/S3V_Zagon
https://www.matrixgames.com/forums/tm.asp?m=4310894
https://www.janes.com/defence-news/news-detail/planaf-conducts-live-fire-exercise-with-new-guided-depth-charge
https://www.china-arms.com/2020/05/y8q-aircraft-depth-charge/
https://defense-update.com/20160624_mi14_asw.html
https://twitter.com/RupprechtDeino/status/1359899664221425667
https://books.google.com/books?id=g3yNDAAAQBAJ&pg=PT235&lpg=PT235&dq=S3V+Zagon+Depth+Charge&source=bl&ots=UMsBkcIPQ_&sig=ACfU3U2pHO0hdqVQvawBFj5oV9BLgT0pGg&hl=en&sa=X&ved=2ahUKEwj3nIf3q-_uAhWKMVkFHZsHDhQQ6AEwE3oECBoQAg#v=onepage&q=S3V%20Zagon%20Depth%20Charge&f=false
https://twitter.com/Russian_Defence/status/882230804444831745
https://thaimilitaryandasianregion.wordpress.com/2016/01/15/ilyushin-il-38n-maritime-patrol-aircraft/

**Comment by bostonmyk** [comment]
https://www.janes.com/amp/planaf-conducts-live-fire-exercise-with-new-guided-depth-charge/ZnlJK3dHVU9mZ28xajRJVkc5dVI5VFp1cVMwPQ2
http://www.matrixgames.com/forums/fb.asp?m=4814326
https://twitter.com/RupprechtDeino/status/1315614461068181509

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
