### ISSUE TITLE
Update - Falaj 2 Missile Boat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2890]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2922

### Summary of Changes

Remove Large Helo Deck.  

### Sources

![image](https://user-images.githubusercontent.com/99599482/213286009-a06ca03a-d2ca-4ace-a962-f9064d68863e.png)
![image](https://user-images.githubusercontent.com/99599482/213286067-7a442767-fe47-43eb-8231-23b69f1d7962.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
