### ISSUE TITLE
Trinidad & Tobago CG 25 Speyside (Damen Stan Patrol 5009)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2891]
### DB Selector

DB3K

### DBID to Copy

Ship 3232

### Hypothetical

No

### Name

CG 25 Speyside (Damen Stan Patrol 5009)

### Country

Trinidad & Tobago

### Service

Coast Guard

### In Commission

2015-

### Number in Service

4x

### Sensors

1x Kelvin Hughes X-Band Sharp Eye
MU602CLW FLIR
Saab R5 data link was also fitted along with a Rotheta RT-500M radio direction finder

### Mounts

Rheinmetall/ MSI Seahawk LW20A1 20mm system for main gun

### Loadout Options

N/A

### Other Changes

replacement of the  C32 engines with Caterpillar 3516C engines with D ratings.

Combat Information Centre (CIC). The CIC housed displays – Transas NS4100s surveillance workstations-  showing the radar, WECDIS and FLIR input with repeaters on the bridge. It was also envisaged that the CIC would house a dedicated secure communications suite supplied by Harris.

To enhance the interdiction capabilities of the SPa 5009, the standard stern-launched MST 750SR 7.5m RHIB was supplemented by a davit launched DI 1102 interceptor.

### Sources

https://en.wikipedia.org/wiki/Trinidad_and_Tobago_Defence_Force#Fleet
https://chuckhillscgblog.net/2018/03/18/how-the-spa-was-chosen-the-trinidad-and-tobago-coast-guards-damen-spa-5009-fleet/
https://www.navypedia.org/ships/trinidad_tobago/trt_cg_speyside.htm

![image](https://user-images.githubusercontent.com/99599482/213288641-08d80883-d70f-40a3-940c-998e1f08320d.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
