### ISSUE TITLE
Trinidad & Tobago - CG 23 Point Lisas [Damen Stan Patrol 5009)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2892]
### DB Selector

DB3K

### DBID to Copy

Ship 3576

### Hypothetical

No

### Name

CG 23 Point Lisas [Damen Stan Patrol 5009)

### Country

Trinidad & Tobago

### Service

Coast Guard

### In Commission

2015-

### Number in Service

2x

### Sensors
2x sharp eye radars

A Voyager II FLIR system was installed to provide a modicum of additional surveillance capability;

### Mounts

An adaptor for a GAM-B01 20mm gun was fitted forward

### Loadout Options

A Heila hydraulically operated knuckle-boom crane was installed which had the secondary function of being able to lower and recover a DI 1102 interceptor.

### Other Changes

5009 Patrol/Utility Vessel Crew Supply Ship Variant, is slightly longer and possesses a more austere equipment fit but is well suited to the task of being a utility vessel. To meet the TTCG’s requirements for a vessel capable of undertaking disaster relief operations in other parts of the Caribbean archipelago.

### Sources

https://en.wikipedia.org/wiki/Trinidad_and_Tobago_Defence_Force#Fleet
https://en.wikipedia.org/wiki/TTS_Brighton
https://chuckhillscgblog.net/2018/03/18/how-the-spa-was-chosen-the-trinidad-and-tobago-coast-guards-damen-spa-5009-fleet/
https://www.navypedia.org/ships/trinidad_tobago/trt_cg_point_lisas.htm

![image](https://user-images.githubusercontent.com/99599482/213290324-4de1d68e-bf63-486e-99f2-6b0a57ed7cc6.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
