### ISSUE TITLE
Trinidad & Tobago - CG 20 Nelson [Island Class]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2893]
### DB Selector

DB3K

### DBID to Copy

Ship 1521

### Hypothetical

No

### Name

CG 20 Nelson [Island Class]

### Country

Trinidad & Tobago

### Service

Coast Guard

### In Commission

2001-2016

### Number in Service

1x,  ex-HMS Orkney

### Sensors

None Indicated

### Mounts

None Indicated

### Loadout Options

None Indicated

### Other Changes

None Indicated

### Sources

https://en.wikipedia.org/wiki/Trinidad_and_Tobago_Defence_Force#Fleet
https://en.wikipedia.org/wiki/HMS_Orkney_(P299)
https://web.archive.org/web/20070607035110/http://www.ttdf.mil.tt/ttcg/cg3.htm
https://www.navypedia.org/ships/trinidad_tobago/trt_cg_nelson.htm

![image](https://user-images.githubusercontent.com/99599482/213291838-b223aaa9-1b4f-4baf-b85e-b9345906e277.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
