### ISSUE TITLE
Hypothetical - USAF ADCOM F-14

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2896]
### DB Selector

DB3K

### DBID to Copy

Aircraft 693

### Hypothetical

Yes

### Name

F-14C Tomcat ADCOM

### Country

United States

### Service

USAF

### In Commission

1979/1980

### Number in Service

170 in one study

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Based on original F-14B project with P&W F401 engines. Used C designation (originally planned as avionics upgrade of original B program) since the unit is Hypothetical and would avoid db confusion with existing versions.
Boom Refueling
Increased Fuel capacity by cutting weight of carrier gear plus missile launcher adjustments.

### Sources

https://theaviationgeekclub.com/heres-why-the-f-14-tomcat-rather-than-the-f-15-eagle-would-have-been-the-most-effective-interceptor-for-usaf/
https://theaviationgeekclub.com/the-adcom-f-14-the-tomcat-that-usaf-never-bought/
https://en.m.wikipedia.org/wiki/Grumman_F-14_Tomcat
https://www.oocities.org/capecanaveral/8629/14var.htm
https://www.globalsecurity.org/military/systems/aircraft/f-14-variants.htm

![image](https://user-images.githubusercontent.com/99599482/213299725-a54f419e-2841-4e82-9259-26fd4ed0b94d.png)

**Comment by KushanGaming** [comment]
Done for DB498.
