### ISSUE TITLE
Further Correction: IFPC-HEL's Weapon

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2898]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3606 of Facility 3651

### Summary of Changes

Target: Aircraft, Helicopter, Missile, C-RAM.
Add Capable vs Seaskimmer, C-RAM Capable

### Sources

https://www.army.mil/article/233346/scaling_up_army_advances_300kw_class_laser_prototype
https://www.dynetics.com/directed-energy/
Unfulfilled #2678.

**Comment by PygmalionOfCyprus** [comment]
WRA was added but not actual targets. Fixed 500.
