### ISSUE TITLE
Kuwait Army/AF Bayraktar TB2 from 2023/2024. #2229

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#2900]
### DB Selector

DB3K

### DBID to Copy

Any Bayraktar TB2 MX15 

### Hypothetical

No

### Name

Kuwait Bayraktar TB2 2023/24 

### Country

Kuwait

### Service

Air Force 

### In Commission

2023/2024

### Number in Service

To be confirmed

### Sensors

Probably MX-15 

### Mounts

As others. 

### Loadout Options

Direct copy of existing version. 

### Other Changes

Nil

### Sources

To follow. https://worlddefencenews.blogspot.com/2023/01/baykar-wins-contract-to-deliver.html

**Comment by PygmalionOfCyprus** [comment]
Already in DB as Aircraft 6297.
