### ISSUE TITLE
Error Made In Correction to 96L6 Radar Band (in closed request 2589)

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#2901]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 3204, 5054, 6904

### Summary of Changes

Original author asked for it to be changed to IEEE C Band, which is High F, Low G Nato - you agreed, but have actually put it as Nato C (500 to 1000 MHZ).  It makes a big difference as it can now pick up LO at ranges it should not. It was confusing me as I was trying to find sources I could use when I noticed this 'problematic mistake'.  
This has completely 'upgraded' the S-400 such that it can wipe the the floor with LO weapons, something it has resolutely failed to do in the current conflict. 

### Sources

See original request.

**Comment by PygmalionOfCyprus** [comment]
Whatever genius decided that NATO should use a completely different radio band allocation system -- _but with the same lettering_ -- as the IEEE should be dragged out of whatever headquarters they sit in and shot. 

Handled 499.

**Comment by HVAA** [comment]
Thanks.  I'll be honest when I started (some 40 odd years ago), (L), S, C, X were the band descriptors we used. When the more modern equipment arrived we started using ABCD etc and the band breaks made more sense and were easier to remember.  The first is a 'engineers' scale - they design, build and fix them.  The other is an operators scale - we use them in anger and in the case of the military, report using them.  When you look at other numbers, Navy use PRF and Air Force uses PRI.  PRI is a number a radar designer would recognise, PRF is not (it's derived).  EW is full of anomalies like this.

**Comment by sr71xx** [comment]
@HVAA @PygmalionOfCyprus @Jkryos It's a common translation error. "C" is in Cryllic and is "S-band" in Russian. 96L6 series are NOT a UHF or C-band radar. Bandwidth and antenna size calculations confirm it to be 3.1GHz S-band. looked into this and recently saw a post by FlankerChan on X.com who confirmed it via sources and calculations
He showed an official Russian 96L6 brochure source with the horizontal and vertical beamwidth and with its horitonzal/vertical antenna size, calculated the cheese board to operate at 3.1 GHz (NATO F band), so yes, it is an S band radar and NOT C or UHF 
96l6, 96l6-tsp and 96l6E should be changed from G/H to F band based off this
**CORRECTION: F BAND (NATO) for all 96L6 type radars**
