### ISSUE TITLE
Zumwalt Class w/ IR-CPS and ZEUS

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2908]
### DB Selector

DB3K

### DBID to Copy

Ship 765, etc. (DB3K 498a)

### Hypothetical

No

### Name

DDG 1000 Zumwalt

### Country

USA

### Service

USN

### In Commission

2025-

### Number in Service

3x

### Sensors

Keep original, except: 

1. Change each SPY-3 to SPY-6(V)3. 
2. Change each SLQ-32(V)6 to SLQ-32(V)7. 
3. Add SQQ-89. 

### Mounts

Keep original, except: 

1. Remove AGSs. 
2. Add APM, with provisions for 12 IR-CPS. 
3. 80 cells Mk57 VLS, with provisions for: 
80x RGM-109C, D, J(V, Va, Vb), or
320x RIM-162A, E, or
80x RIM-174A, or 
80x RIM-66M-2, -5, -6, or
80x RUM-139C. 

### Loadout Options

N/A

### Other Changes

Change SPY-3 datalink to SPY-6 AEGIS datalink. 
Add CEC datalink. 
Same or smaller RCS. 

### Sources

https://sam.gov/opp/e32b38af72304655a645e4e2c8340790/view
https://www.navalnews.com/naval-news/2021/03/raytheon-delivers-first-batch-of-block-v-tomahawk-missiles-to-us-navy/
https://news.usni.org/2023/01/09/navy-awards-hii-planning-contract-for-zumwalt-hypersonic-upgrades

**Comment by tbrandon517** [comment]
See existing DB entry

https://cmano-db.com/ship/3343/

**Comment by HunterDNiu** [comment]
> See existing DB entry
> 
> https://cmano-db.com/ship/3343/

Baseline.

**Comment by HunterDNiu** [comment]
Please keep ships 3100, 3343, 3737 as they provide valuable information as to the evolution of the Zumwalt class. This request is merely a further update.

**Comment by KushanGaming** [comment]
Updated DBID 3343 for DB499.
