### ISSUE TITLE
CORRECTION: Number of IR-CPS on Hypothetical SSGN

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2909]
### DB Selector

DB3K

### Affected DBID(s)

Sub 667

### Summary of Changes

The original Trident D5 tube is 88 inches in diameter. The Tubes about to be installed on DDG 1000s are 87 inches, holding 3 IR-CPSs each. 
Change the number of IR-CPS to 66. 

### Sources

https://news.usni.org/2023/01/09/navy-awards-hii-planning-contract-for-zumwalt-hypersonic-upgrades

**Comment by KushanGaming** [comment]
Done for DB499.
