### ISSUE TITLE
Addition: India, S-400 Triumf SAM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2910]
### DB Selector

DB3K

### DBID to Copy

Facility 1937

### Hypothetical

No

### Name

SAM Bn (SA-21a/b Growler [S-400 Triumf]), 8x TEL

### Country

India

### Service

Air Force

### In Commission

2021

### Sources

https://en.wikipedia.org/wiki/S-400_missile_system
https://www.indiatoday.in/india/story/india-third-s-400-air-defence-missile-system-russia-supply-feb-2023-2313139-2022-12-24

**Comment by PygmalionOfCyprus** [comment]
Already in DB as Facility 3807.
