### ISSUE TITLE
MH-60X Noy stealthy

### ISSUE THREAD

**Issue by EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE2** [PygmalionOfCyprus/cmo-db-requests#2911]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4464

### Summary of Changes

The RCS of the MH-60x to be reduced to below RCS of a UH-60

### Sources

![Screenshot_20230121_051106](https://user-images.githubusercontent.com/121797658/213878570-e050f054-0e24-462d-b557-8b4e6f32f812.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
