### ISSUE TITLE
Grom-2 SRBM TEL has two missiles (in DB one)

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2913]
### DB Selector

DB3K

### Affected DBID(s)

#3709 - Grom-2 SRBM

### Summary of Changes

#3709 consists of two TELs, each with one ballistic missile.
Photo's show two missiles per TEL.

### Sources

https://www.tacticalreport.com/news/article/59220-saudi-ukrainian-cooperation-on-hrim-short-range-ballistic-missiles-srbms
[http://www.military-today.com/missiles/grom_ballistic_missile.htm](url)
[https://www.thedrive.com/the-war-zone/does-ukraine-have-a-stash-of-domestically-developed-ballistic-missiles](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
