### ISSUE TITLE
SOM-C1[HE]

### ISSUE THREAD

**Issue by Slanger88** [PygmalionOfCyprus/cmo-db-requests#2915]
### DB Selector

DB3K

### Affected DBID(s)

3759

### Summary of Changes

SOM-C1 is an anti ship stand of munition. It's able to attack both land targets and surface targets. After latest database updates SOM C1 lost its ability to engage to surface targets. 

### Sources

https://www.sage.tubitak.gov.tr/en/urunler/stand-missile-som-0

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
