### ISSUE TITLE
Roketsan MBRL 230

### ISSUE THREAD

**Issue by Slanger88** [PygmalionOfCyprus/cmo-db-requests#2916]
### DB Selector

DB3K

### Hypothetical

No

### Name

MBRL-230 Battery (Roketsan)

### Facility Type

Arty

### Country

Turkey

### Service

Army

### In Commission

2014

### Number in Service

Unknown

### Crew

48

### Dispersion Radius (m)

100

### Sensors

No sensor

### Mounts

6x MBRL System (each 12xTRG-230 or 12xTRLG-230)

### Magazines

72x TRG-230 or 72x TRLG-230

### Comments

Multi-Barrel Rocket Launcher [MBRL], is capable of providing precise fire on critical targets between the ranges of 10-280 km. The MBRL is a highly maneuverable fire support system that can fire TR-122 & TRB-122 Unguided Rockets, TRG-122, TRLG-122, TRG-230, TRLG-230, TRG-300 and KHAN Missiles. A MBRL battery is composed of a Command & Control Vehicle, 6x Launching Vehicles, 6x Ammunition Supply Vehicles, a Meteorology Vehicle and a Maintenance & Repair Vehicle, as well as other mission vehicles that are needed.

### Sources

https://www.roketsan.com.tr/en/products/multi-barrel-rocket-launcher
https://www.roketsan.com.tr/uploads/docs/kataloglar/ENG/1628389066_multi-barrell-rocket-launcher.pdf
https://www.roketsan.com.tr/en/products/trg-230-guided-missile
https://www.roketsan.com.tr/uploads/docs/kataloglar/ENG/1628389230_trg-230-en.pdf
https://www.roketsan.com.tr/en/products/trlg-230-laser-guided-missile
https://www.roketsan.com.tr/uploads/docs/kataloglar/ENG/1628388942_trlg-230.pdf
https://eurasiantimes.com/better-than-himars-ukraine-gets-new-laser-guided-mlrs/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
