### ISSUE TITLE
Update & Correction: Japan, Aegis System-Equipped Vessel, datalink issue

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2918]
### DB Selector

DB3K

### Affected DBID(s)

Ship 4044

### Summary of Changes

1. It only has one channel aegis weapon link.
2. Add 24 channel generic CEC weapon link. Source confirms it has CEC capability.

### Sources

https://www.jiji.com/sp/article?k=2023012100303&g=soc
![image](https://user-images.githubusercontent.com/107970049/213913824-3c0dfd8b-5812-412d-b392-e5ccb5ddb9f7.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
