### ISSUE TITLE
Addition: China, J-11BHG, PLA Naval Aviation Force, J-11BH Mid-life Upgrade

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2919]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4900

### Hypothetical

No

### Name

J-11BHG [J-11BH MLU]

### Country

China

### Service

PLANAF

### Other Changes

Similar to PLAAF J-11BG (J-11B MLU) with AESA and PL-15 & PL-10 equipped.

### Sources

https://www.sinodefenceforum.com/t/china-flanker-thread-ii.3720/page-905
https://twitter.com/rickjoe_pla/status/1504741969633095682
Color of its nose changed from black to grey, and you can also see a PL-10 on wingtip pylon:
![image](https://user-images.githubusercontent.com/107970049/214194700-567795d0-4be8-4475-bd67-7bab3c69a595.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
