### ISSUE TITLE
Add SSM Plt (SSC-1 Sepal TEL [4k44B Redut] to Vietnam. IOC 1980

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#292]
### DB Selector

DB3K

### DBID to Copy

Facility 1505

### Hypothetical

No

### Name

SSC-1 Sepal TEL [4k44B Redut]

### Country

Vietnam

### Service

Army

### In Commission

1980-Present

### Sources
https://twitter.com/AnnQuann/status/1223320724149956609
sipri.org/armstrade/page/trade_register.php
https://twitter.com/AnnQuann/status/1309428720373956608
https://twitter.com/AnnQuann/status/1308267240844791808
https://twitter.com/AnnQuann/status/1308266720344170496
https://twitter.com/BlairGrub/status/891068767496658944

**Comment by PygmalionOfCyprus** [comment]
Added 494.
