### ISSUE TITLE
IAR.330L Naval (2015)

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2923]
### DB Selector

DB3K

### DBID to Copy

Issue #2922

### Hypothetical

No

### Name

IAR.330L NAVAL

### Country

Romania

### Service

Navy

### In Commission

2015-

### Number in Service

3x

### Loadout Options

Add ASW loadout with 12x sonobuoys. Processor is the Thales TMS 2000, the buoys themselves are unknown. If we use the generic buoys then the helicopter will never hear anything, because the generics are from the 60s, so I'd say assume Thales provided the whole package and load up six TSM 8050Bs and six TSM 8062s.

### Other Changes

Crew increased to 4

### Sources

https://www.keymilitary.com/article/black-sea-knights
http://kr-media.ru/en/return-of-the-black-sea-knights/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
