### ISSUE TITLE
IAR.330L Naval with torpedoes

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2924]
### DB Selector

DB3K

### DBID to Copy

Issue #2923

### Hypothetical

Yes

### Name

IAR.330L NAVAL

### Country

Romania

### Service

Air Force

### In Commission

2017

### Number in Service

3x

### Loadout Options

Add 2x Stingray Mod 0 to the ASW loadout.

Romania flew practice missions with big orange practice Stingrays and it was an ambition to have it qualified on the helicopter properly, but this doesn't appear to have happened. The Type 22s the helicopters operate from already have Stingrays in the magazines for their deck launchers, so frankly this is barely a hypothetical capability. This entry can be converted into a non-hypothetical version if they get around to doing it.

### Sources

http://kr-media.ru/en/return-of-the-black-sea-knights/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
