### ISSUE TITLE
IAR.330M (2019) for Romania

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2926]
### DB Selector

DB3K

### DBID to Copy

Issue #2925

### Hypothetical

No

### Name

IAR.330M Puma

### Country

Romania

### Service

Air Force

### In Commission

2019

### Number in Service

At least four?

### Sensors

Remove generic weather radar.

Add Generic IR turret.

Add BriteNite staring IR system. Big, high quality IR system using the HMD to give better capabilities in dark of brownout conditions. Makes it easier to fly at low level at high speed in poor weather or darkness, I'm not sure if Command simulates that?

### Sources

https://www.military.africa/2020/07/mali-romanian-pumas-lights-up-with-brightnite-situational-awareness-system/
https://www.youtube.com/watch?v=a1Y70mD7a4k

**Comment by PygmalionOfCyprus** [comment]
That's some cool tech! We do have/handle IR navigation cameras in Command so I've modelled it similarly to that. Handled 500.
