### ISSUE TITLE
IAR.330L SOCAT attack helicopter for Romania

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#2927]
### DB Selector

DB3K

### DBID to Copy

Issue #2922

### Hypothetical

No

### Name

IAR.330L SOCAT

### Country

Romania

### Service

Air Force

### In Commission

2005-

### Number in Service

25x

### Sensors

Remove radar, Link 11.

### Mounts

1x 20mm THL-20 chin gun with 750 rounds (actually a GIAT M621, copy the Rudra)

### Loadout Options

- 32x S-5, 8x Spike-ER
- 64x S-5
- 64x S-5, 12x troops

### Sources

https://en.wikipedia.org/wiki/IAR_330
https://www.airforce-technology.com/projects/iar-330l-puma-helicopter-romania/
http://www.roaf.ro/?page_id=2237

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
