### ISSUE TITLE
Qatar Air Defense LPD Name Update - L 141 Al Fulk

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2928]
### DB Selector

DB3K

### Affected DBID(s)

Ship 4073

### Summary of Changes

Ship launched and name revealed as L 141 Al Fulk

### Sources

https://www.navalnews.com/naval-news/2023/01/fincantieri-launches-qatars-air-defense-lpd/
https://navyrecognition.com/index.php/naval-news/naval-news-archive/2023/january/12745-fincantieri-officially-launches-lpd-al-fulk-for-qatari-emiri-navy.html

![image](https://user-images.githubusercontent.com/99599482/214440923-eda2494d-42aa-45fb-b4a1-be9d37699e25.png)

**Comment by Huib18** [comment]
Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side).
The DB has 1x8 cell.

Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. 
Source same as above and this one:
[https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)

**Comment by tbrandon517** [comment]
> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)



> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)



> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)



> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)

Good catch. I had put 2x 8 cells in the original request but hadn't noticed after it was added.

**Comment by tbrandon517** [comment]
> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)



> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)



> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)



> Please note that the VLS system has been upgraded to 2x8 cell. (bix add-on box on the right front side). The DB has 1x8 cell.
> 
> Another unique feature of this LPD is the fact it is fitted with two 8-cell VLS Sylver A50 for medium-range surface-to-air missile system which MBDA has indicated as the Aster 30 Block 1 munitions as part of the SAAM-ESD air-defence system. Although Fincantieri hasn’t released information or commented the AAW capabilities of the LPD, the combination of the MBDA SAAM-ESD with Aster 30 Block 1 missile system, the Leonardo Kronos AESA multifunction radar and the early-detection information from the Kronos Power Shield, all together can provide tactical ballistic missiles defense as similarly offered by the ground-based SAMP/T but with enhanced capabilities, Naval News understood. Source same as above and this one: [https://twitter.com/VivekSi85847001/status/1618281747480997889/photo/2](url)

Good catch. I had put the 2x 8 cells in the original request but hadn't noticed after it was added.

**Comment by tbrandon517** [comment]
I checked and I do see 2x 8 cell VLS in db 498a

**Comment by PygmalionOfCyprus** [comment]
Already handled as part of an ongoing national review of Qatar.
