### ISSUE TITLE
Add Yak-130 Aircraft to Myanmar 2017. x18

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#293]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3952

### Hypothetical

No

### Name

Yak-130

### Country

Myanmar

### Service

Airforce 

### In Commission

2017

### Loadout Options

Definitely rockets see vid.

### Sources

Used in combat against rebels in 2020. Look like bombs and rockets loadouts and R-73 AAMs

https://southfront.org/myanmar-air-force-uses-yak-130-trainer-aircraft-in-combat-for-first-time-ever-video/
https://twitter.com/PatilSushmit/status/1266229224232202240
https://thaimilitaryandasianregion.blogspot.com/2020/06/video-of-first-combat-use-of-yak-130.html
https://en.wikipedia.org/wiki/Yakovlev_Yak-130
https://twitter.com/nawapon10/status/1267634548654788609/photo/1

**Comment by KLABDB3K** [comment]
#3953 - Yak-130 Mitten (Algeria - 2015) is better to copy as the OSA radar IS NOT FITTED to export or the Russian version. That was a demonstrator for potential customers that wasn't adopted. The Algerian Yak could do with being updated too.

Weapon loads :
23mm SNPU-130 gun pod with 23mm GsH-23L and 120 rounds on centreline.
Air to ground combinations of the following:
2 to 4 x 20 round S-8 80mm rocket pods,
2 to 4 x 5 round S-13 122mm rockets,
2 to 4 x 100kg FAB/ZAB/OFAB
2 to 4 x 250kg FAB/ZAB/OFAB
2 to 4 x 500kg FAB/ZAB/OFAB/RBK
Air to air
2 to 4 R-73 / AA-11 Archer AAM
Plus combinations of two 450l drop tanks and a centreline Yak-130 specific 23mm SNPU-130 gun pod with 23mm GsH-23L and 120 rounds.
http://eng.mil.ru/en/news_page/country/more.htm?id=12340128@egNews
https://sputniknews.com/military/201703211051796154-yak130-russia-myanmar-supplies/ Delivery summary.
https://southfront.org/wp-content/uploads/2020/05/EK7gNAFXYAEJPrm.jpg Armed Yak-130 2 x S-8 RP 2 X 450 drop tanks.
https://1.bp.blogspot.com/-6Sncd9CJ4Hs/Xc_ftKF2_CI/AAAAAAABIt4/5u3W17nDfTgKfs-TTRwXmO1QgL1kXAkywCLcBGAsYHQ/s1600/Yak-130%2BMyanmar-22.jpeg
Armed Mynamar Yak-130 in flight 2 x S-13 rockets and 2 x R-73 (inert) plus centreline 23mm gun pod and 450 litre PTAB drop tanks.
https://thaimilitaryandasianregion.blogspot.com/2020/06/video-of-first-combat-use-of-yak-130.html Yak-130 firing rockets.
https://thaimilitaryandasianregion.files.wordpress.com/2015/10/yak_130_arma1.jpg?w=625 Schematic of typical stores arrangements.

**Comment by KLABDB3K** [comment]
Very likely that Laos (10 from ordered 2019) Bangladesh (15 give or take from 2015) Belarus (12 as of 2019) Vietnam (12 as of 2020) all use armed trainer variant minus radar with at least R73 AAM and the aforementioned Russian/Soviet bombs rocket pods and 23mm gun pod with PTAB 450 drop tanks options.

**Comment by PygmalionOfCyprus** [comment]
Added 493. Also reworked the loadouts / removed the radar.
