### ISSUE TITLE
ARRW Loadouts

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2930]
### DB Selector

DB3K

### User(s)

B-52H, J, K, 2023-; B-1B, w/ welded pylon, 2023-; B-21; F-15E, EX, 2023-

### Weapons Carried

-B-52s: 

1. 6x ARRW, 
2. 10x ARRW, 
3. 18x ARRW. 

-B-1Bs: 

1. 25x ARRW, conventional variant only. 

-B-21s: 

1. 16x ARRW. 

-F-15:

1. 1x ARRW, 
2. 2x ARRW, 
3. 4x ARRW, 
4. 5x ARRW. 

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://en.wikipedia.org/wiki/AGM-183_ARRW
https://www.airandspaceforces.com/arrw-beat-hcsw-because-its-smaller-better-for-usaf/
https://crsreports.congress.gov/product/pdf/R/R45811/33

**Comment by KushanGaming** [comment]
B-1, B-2, B-21, and B-52s done for DB499.

Added a single ARRW loadout to the F-15E. I want to see evidence that it can carry more then that before adding.
