### ISSUE TITLE
Update: China, DF-26B IRBM/ASBM (presently named DF-26D)

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2936]
### DB Selector

DB3K

### Affected DBID(s)

WEAPON 3371 3372

### Summary of Changes

1. Rename DF-26D (ASBM) as DF-26B
2. Change warhead payload from 600kg penetrator to 1500kg penetrator (1500 DP, pick an average between 1200~1800kg). It is larger than DF-21’s 600kg payload.
3. Length change to 14m, weight change to 20000kg

### Sources

https://en.wikipedia.org/wiki/DF-26
https://missilethreat.csis.org/missile/dong-feng-26-df-26/

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
