### ISSUE TITLE
Update: China, DF-26 (presently named DF-26C)

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2937]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3373 3374 3375 3376

### Summary of Changes

Rename as DF-26
Length change to 14m
weight change to 20000kg

### Sources

https://missilethreat.csis.org/missile/dong-feng-26-df-26/

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
