### ISSUE TITLE
Addition: AEGIS Ashore w/ SPY-7

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2938]
### DB Selector

DB3K

### Hypothetical

No

### Name

AEGIS Ashore

### Facility Type

SAM

### Country

United States, Japan

### Sensors

- SPY-7, two faces for Japan. 
- SPY-7, four faces for Guam. 

### Mounts

3x 8 cells Mk41 VLS, w/ provision for: 
8x RIM-161E, loaded, or 
8x RIM-161C. 

### Magazines

None

### Aircraft & Docking Facilities

None

### Comments

Add SPY-7 datalink. 

### Sources

https://crsreports.congress.gov/product/pdf/RL/RL33745/245
https://www.lockheedmartin.com/en-us/products/aegis-combat-system.html

**Comment by KushanGaming** [comment]
Done for DB399.
