### ISSUE TITLE
Add Chinese BL-755 to loadouts to Q-5, JH-7, JH-7A

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#294]
### DB Selector

DB3K

### User(s)

q-5 and JH-7

### Weapons Carried

Q-5
Similar to 500KG bomb loadouts 2x
Pakistan A-5 loadout #18323
JH-7
Similar to500 KG bomb loadouts 4x

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Chinese manufacture BL-755 340kg cluster bomb clone. Q-5s use JH-7 and JH-7A as well. Likely receive in 1990s when relation with UK arms established or when exporting arms to Zimbabwe or Pakistan

### Sources

https://twitter.com/HaoGao12/status/1294521804246065153
https://i.imgur.com/P8asU.jpg
http://the-monitor.org/en-gb/reports/2015/china/cluster-munition-ban-policy.aspx

**Comment by FrangibleCover** [comment]
I'm not sure these are 340kg weapons. They're called 250s, and look at the image of the Chinese woman next to one:
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/58b5b9f8-a7c4-43bd-9336-ac72d01ee1d6)
Compared to a (probably physically larger) British maintainer:
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/c18d33ef-79e3-436e-8996-91d9ae38f674)
Tough to tell, but I reckon the original is bigger.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
