### ISSUE TITLE
New Zealand P-3s retired 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2944]
### DB Selector

DB3K

### Affected DBID(s)

3661

### Summary of Changes

Add 2023 retirement date. 

### Sources

https://www.scramble.nl/military-news/farewell-tour-rnzaf-p-3k2-orions
https://www.janes.com/defence-news/air-platforms/latest/royal-new-zealand-air-force-retires-p-3k2-orion-aircraft
https://www.reuters.com/business/aerospace-defense/new-zealand-defence-force-retire-p-3-orion-planes-5-months-early-2022-12-12/#:~:text=WELLINGTON%2C%20Dec%2013%20(Reuters),operations%20until%20at%20least%20July.
https://www.flightglobal.com/defence/new-zealand-moves-up-retirement-of-p-3k2-orions/151312.article

**Comment by PygmalionOfCyprus** [comment]
Handled during routine news roundup.
