### ISSUE TITLE
Update: TR 1700 Sonar Suite

### ISSUE THREAD

**Issue by Red-88** [PygmalionOfCyprus/cmo-db-requests#2945]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 37

### Summary of Changes

According to Jane's, Conway's and Rössler TR 1700 [S 41 Santa Cruz] are fitted with CSU 3-4 sonar suite instead of TSM 2233 Eledone. Intercept function is integrated with CSU 3-4 (see: Rössler and Jane's Underwater Warfare Systems). 
Please modify sonar sensors,
Remove:
DBID 1725 - TSM 2233 Eledone [DSUV 2H + DUUA 2D]
DBID  4405 - TSM 2243

Add:
DBID  1347 - CSU 3-4
DBID  4406 - IPS CSU 3

### Sources

Robert Gardiner, ed., _Conway's All the World's Fighting Ships 1947-1995_ (London: Conway Maritime Press, 1995), 11.

Richard Sharpe, ed., _Jane’s Fighting Ships 1990-91_ (Coulsdon, Surrey: Jane’s Information Group, 1990), 10.

Anthony J. Watts, ed., _Jane's Underwater Warfare Systems 2000-2001_ (Coulsdon, Surrey: Jane's Information Group Limited, 2000), 127.

Eberhard Rössler, _Die Sonaranlagen der deutschen Unterseeboote_ (Bonn: Bernard & Graefe Verlag, 2006), 182-185.

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
