### ISSUE TITLE
CORRECTION: SSN 774 Blk V w/ VPM

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2946]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 668

### Summary of Changes

1. Respecting VPM: 
Change the VPM onboard to 4 separate mounts, with provisions each, for: 

- 7x RGM-109C, D, J(V, Va, Vb), or
- 7x RIM-174A, or
- 3x IR-CPS. 
Make a tube occupied when docked with a UUV. 

2. Respecting VLS:
Change the provisions for: 

- 12x RGM-109C, D, J(V, Va, Vb), or
- 12x RIM-174A. 

### Sources

https://news.usni.org/2018/11/14/navy-looking-use-virginia-payload-module-deploy-new-missiles-uuvs
http://www.dmitryshulgin.com/tag/virginia-payload-module/

**Comment by PygmalionOfCyprus** [comment]
Handled 499. Is there a particular reason why the VPM would need to be split into 4 distinct mounts rather than just treating them as one and using weapon records to set it up as desired, as currently?
