### ISSUE TITLE
Thailand Chao Pria Frigates get C-802 by 2014

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#295]
### DB Selector

DB3K

### Affected DBID(s)

#1009 and #188

### Summary of Changes

Entry #1009 and #188 replace C-801 Mounts with C-802 (4 Dual Launcher)

### Sources

https://www.flickr.com/photos/acstudio/9361662863/lightbox/
https://i.imgur.com/kbWitAj.jpg

**Comment by Jkryos** [comment]
Added new entry DB3K 493.
