### ISSUE TITLE
Add Finnish Hämeenmaa class frigates

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#2951]
### DB Selector

CWDB

### DBID to Copy

 SKR Riga Mod (Ship 550)

### Hypothetical

No

### Name

Hämeenmaa class

### Country

Finland

### Service

Navy

### In Commission

1964-1985

### Number in Service

2

### Sensors

Change Sun Visor FCR to Hawk Screech [Yakor] GFCR, 45mm, 57mm, 76mm, 100mm #1540
Change Don Kay [Volga] Radar to Decca 707 #3760
Add Drum Tilt [MR-104 Rys] 25mm & 30mm GFCR #1545
Add Watch Dog B [Bizan] -- Jug Pair, adds omni #1100
Remove Generic ESM

### Mounts

Change 2 x 37 mm/63 V-47M to 2 x 40mm/70 m/48 Single Bofors #1792
Add 1 x AK-230 30mm/65 Twin #234 in the bow (fire arc 10 to 4)
Add 2 x Mk15 Hedgehog Trainable ASW Mortar #1988 

### Sources

https://fi.wikipedia.org/wiki/Saattaja_H%C3%A4meenmaa
https://en.wikipedia.org/wiki/Finnish_frigate_H%C3%A4meenmaa
https://merivoimat.fi/documents/1951215/11124014/Merivoimat+100+-kirja/

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
