### ISSUE TITLE
Bismarck Class BB

### ISSUE THREAD

**Issue by KonigLars** [PygmalionOfCyprus/cmo-db-requests#2952]
### DB Selector

CWDB

### Baseline

#153 Vanguard Class

### Hypothetical

No

### Name

Bismarck/Tirpitz

### Class

Bismarck Class

### Country

Nazi Germany

### Service

Kriegsmarine

### In Commission

1940-1944

### Number in Service

2

### Length (m)

251

### Beam (m)

36

### Draft (m)

9.30

### Standard Displacement (t)

41,700

### Full Displacement (t)

50,300

### Complement

103 Officers, 1,962 Enlisted Men

### Max Sea State

6

### Primary Propulsion Type

Steam

### Propulsion

X3 Blohm & Voss Geared Steam Turbines

### Fuel Capacity (kg)

7,400

### Flank Speed (kt)

31.5

### Range (nm) at Speed (kt)

8,525 NMI @ 19 Knots

### Sensors

X3 FuMO 23 _Matratzen_ Search Radar Sets
X7 Zeiss 10.5 Meter Stereoscopic Rangefinders
X4 Zeiss 4 Meter Stereoscopic Rangefinders
X2 Zeiss 3 Meter Night Steroscopic Rangefinders

### Mounts

X8 38cm SK C/34 Guns w/AP, HE and Fragmentation Shells
X12 15cm SK C/28 Guns w/AP, HE and Fragmentation Shells
X16 10.5cm SK C/33 Anti Aircraft Guns w/HE and Star Shells
X12 2cm MG C/30 Anti Aircraft Guns  w/HE Shells
X16 3.7cm Anti Aircraft Guns w/HE Shells

### Aircraft & Docking Facilities

X1 Double-Ended Steam Catapult For Launching Aircraft

### Sources

https://en.wikipedia.org/wiki/German_battleship_Bismarck
https://www.kbismarck.com/

**Comment by FrangibleCover** [comment]
Probably worth having two requests here, one for Bismarck and the other for Tirpitz. They ended up being noticeably different ships.

**Comment by PygmalionOfCyprus** [comment]
CWDB is not a WW2 DB.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/5623dcb4-b3af-4ab2-8212-b45593b24b45)
