### ISSUE TITLE
AGR-1 Guardian class radar picket ship

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2953]
### DB Selector

CWDB

### DBID to Copy

ship 2285

### Hypothetical

No

### Name

AGR-1 Guardian

### Country

United States

### Service

Navy

### In Commission

1954-1965

### Number in Service

16x

### Sensors

AN/SPS-8 height finding radar
AN/SPS-12 air/surface search radar 
AN/SPS-17 long range air search radar
AN/UPA-22 IFF

The AN/SPS-8 was later replaced on some ships by the AN/SPS-30

### Mounts

2x 3 in (76 mm)/50 caliber guns (1x at bow, 1x at stern)

### Loadout Options

N/A

### Sources

https://en.wikipedia.org/wiki/Guardian-class_radar_picket_ship
https://en.wikipedia.org/wiki/USS_Guardian_(YAGR-1)
https://en.wikipedia.org/wiki/USS_Lookout_(YAGR-2)
https://en.wikipedia.org/wiki/USS_Skywatcher_(AGR-3)
https://en.wikipedia.org/wiki/USS_Searcher_(AGR-4)
https://en.wikipedia.org/wiki/USS_Scanner_(AGR-5)
https://en.wikipedia.org/wiki/USS_Locator_(AGR-6)
https://en.wikipedia.org/wiki/USS_Picket_(YAGR-7)
https://en.wikipedia.org/wiki/USS_Interceptor_(AGR-8)
https://en.wikipedia.org/wiki/USS_Investigator_(AGR-9)
https://en.wikipedia.org/wiki/USS_Outpost_(AGR-10)
https://en.wikipedia.org/wiki/USS_Protector_(AGR-11)
https://en.wikipedia.org/wiki/USS_Vigil_(AGR-12)
https://en.wikipedia.org/wiki/USS_Interdictor_(AGR-13)
https://en.wikipedia.org/wiki/USS_Interpreter_(AGR-14)
https://en.wikipedia.org/wiki/USS_Tracer_(AGR-15)
https://en.wikipedia.org/wiki/USS_Watchman_(AGR-16)
https://www.radomes.org/museum/ThePicketShips.php
https://www.yagrs.org/

![image](https://user-images.githubusercontent.com/99599482/215336382-fc69eea0-7725-4f29-8cb0-38ff42278002.png)
![image](https://user-images.githubusercontent.com/99599482/215336509-15db99f3-f521-4a55-9d64-3dd642db241f.png)
![image](https://user-images.githubusercontent.com/99599482/215336549-bd08d9b7-16cc-4de0-8476-73be892f299d.png)
![image](https://user-images.githubusercontent.com/99599482/215336583-a2fa67d5-aa1d-4fdc-a996-52a5846964a0.png)
![image](https://user-images.githubusercontent.com/99599482/215336722-a4b52836-0924-4eff-908a-380ec5de55d9.png)
![image](https://user-images.githubusercontent.com/99599482/215336781-2f351b92-a64e-4ca4-bf5e-5216999e5d73.png)
![image](https://user-images.githubusercontent.com/99599482/215336885-2783fc10-64f9-42ee-b975-1d3a4850608e.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
