### ISSUE TITLE
United States - B-24D "Pathfinder"

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2955]
### DB Selector

CWDB

### DBID to Copy

aircraft 387

### Hypothetical

No

### Name

B-24D Liberator "Pathfinder"

### Country

United States

### Service

Air Force

### In Commission

1943-

### Number in Service

Aircraft of the 814th Bombardment Squadron

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

"Those missions where bombing was done by H2X were called "Pathfinder missions" and the crews were called "Pathfinder crews", after the RAF practice of using highly trained Pathfinder crews to go in before the main bomber stream and identify and mark the target with flares."

"American practice used their Pathfinder crews as lead bombers, with radar equipped aircraft being followed by formations of radar-less bombers, which would all drop their loads when the lead bomber did."

### Sources

https://en.wikipedia.org/wiki/H2X
https://en.wikipedia.org/wiki/482nd_Operations_Group#World_War_II
https://en.wikipedia.org/wiki/814th_Troop_Carrier_Squadron

Ball turret install
https://images.app.goo.gl/xNDenPu3y8FURKiZA

**Comment by PygmalionOfCyprus** [comment]
See question on #2956.

**Comment by tbrandon517** [comment]
> See question on #2956.

Yes this was meant to complement the standard B-24s without radar as the Pathfinder.

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
