### ISSUE TITLE
United States - B-17G "Pathfinder"

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2956]
### DB Selector

CWDB

### DBID to Copy

aircraft 2028

### Hypothetical

No

### Name

B-17G Flying Fortress "Pathfinder"

### Country

United States

### Service

Air Force

### In Commission

1943-

### Number in Service

Aircraft of the  812th and 813th Bombardment Squadrons

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

"Those missions where bombing was done by H2X were called "Pathfinder missions" and the crews were called "Pathfinder crews", after the RAF practice of using highly trained Pathfinder crews to go in before the main bomber stream and identify and mark the target with flares."

"American practice used their Pathfinder crews as lead bombers, with radar equipped aircraft being followed by formations of radar-less bombers, which would all drop their loads when the lead bomber did."

### Sources

https://en.wikipedia.org/wiki/H2X
https://en.wikipedia.org/wiki/482nd_Operations_Group#World_War_II
https://en.wikipedia.org/wiki/812th_Fighter-Bomber_Squadron
https://en.wikipedia.org/wiki/813th_Fighter-Bomber_Squadron

Ball turret install 
https://images.app.goo.gl/DCrhPadXc99X4TiK8

Chin install (I think the currently equipped db version is this)
https://images.app.goo.gl/PH1gD2YNREpnwBn36

**Comment by PygmalionOfCyprus** [comment]
The US already has a B-17G. Is this meant to include the extra sensors to represent the Pathfinder capability?

**Comment by tbrandon517** [comment]
> The US already has a B-17G. Is this meant to include the extra sensors to represent the Pathfinder capability?

Yes this was meant to complement the standard B-17s without radar as the Pathfinder.

**Comment by PygmalionOfCyprus** [comment]
>### Sensors
>No Change

https://www.youtube.com/watch?v=MSRCoAgpQ3g

**Comment by tbrandon517** [comment]
> > ### Sensors
> > No Change
> 
> https://www.youtube.com/watch?v=MSRCoAgpQ3g

https://giphy.com/gifs/bullettrainmovie-bullet-train-movie-bullettrain-spSNe53kQFBJJEwmCc

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
