### ISSUE TITLE
Slovenian patrol boat P11 Triglav

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2957]
### DB Selector

DB3K

### DBID to Copy

ship 2568

### Hypothetical

No

### Name

P11 Triglav [Svetlyak, Pr.1041.2]

### Country

Slovenia

### Service

Navy

### In Commission

2011-

### Number in Service

1x

### Sensors

FR-2150W navigational radar
Gorizont-25 integrated navigation system
LEMM-2-2 electromagnetic log with echosounder functions

### Mounts

1x AK-306 gun mount
2x 14.5mm machine guns
6x 9M120 anti-ship missile system
16x Igla-type MANPADS
PK-10 anti-missile projectiles

### Loadout Options

N/A

### Other Changes

place for two inflatable boats

### Sources

https://en.wikipedia.org/wiki/Slovenian_patrol_boat_Triglav
https://en.wikipedia.org/wiki/Project_10412_patrol_boat

![image](https://user-images.githubusercontent.com/99599482/215339784-6b15a632-652c-4b5d-b574-75e767d9fbf5.png)
![image](https://user-images.githubusercontent.com/99599482/215339883-4e775280-0583-4430-9442-5f83a95a901c.png)
![image](https://user-images.githubusercontent.com/99599482/215339907-c1e3201c-6c75-462d-a4d7-a50fb82baa43.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus is it possible to add some reloads for the SA-16? Currently there is only 1 missile onboard.

**Comment by Jkryos** [comment]
Updated DB3K 503.
