### ISSUE TITLE
Slovenian fast patrol boats HPL-21 Ankaran [Super Dvora MK II]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2958]
### DB Selector

DB3K

### DBID to Copy

ship 500

### Hypothetical

No

### Name

HPL-21 Ankaran [Super Dvora MK II]

### Country

Slovenia

### Service

Navy

### In Commission

1996-

### Number in Service

1x

### Sensors

No Change

### Mounts

2x Oerlikon 20 mm cannon instead on Typhoon 25mm

### Loadout Options

N/A

### Other Changes

N/A

### Sources

https://en.wikipedia.org/wiki/Slovenian_Navy
https://en.wikipedia.org/wiki/Super_Dvora_Mk_II-class_patrol_boat

![image](https://user-images.githubusercontent.com/99599482/215340150-b7716c41-8e2c-4440-99d0-685156d5d82c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
