### ISSUE TITLE
United States - K-Class Airship

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2959]
### DB Selector

CWDB

### Baseline

Aerostat

### Hypothetical

No

### Name

 K-Class Airship (see designations below)

### Country

United States

### Service

Navy

### In Commission

1938-1959

### Number in Service

134x

### Length (m)

76.73 m (K-14)

### Wingspan (m)

17.63 m diameter (K-14)

### Height (m)

Variable by block/model

### Empty Weight (kg)

Variable by block/model

### Maximum Takeoff Weight (MTOW) (kg)

Variable by block/model

### Payload Weight (kg)

Variable by block/model

### Crew

10x

### Propulsion

2 × Pratt & Whitney R-1340-AN-2 radials , 425 hp (317 kW) each

### Rate of Climb (ft/min)

Variable by block/model

### Service Ceiling (ft)

14000 ft

### Military/Afterburner Speed (kt)

68 kn

### Cruise Speed (kt)

50 kn

### Supercruise

No

### Ferry Range (nm)

1,916 nm

### Endurance (min)

38 hours 12 minutes

### Takeoff / Landing Distance (m)

VTOL

### Fuel Capacity (kg)

6000  lbs

### Sensors

ASG radar  
magnetic anomaly detection (MAD) equipment.
Recon cameras
Searchlight
Binoculars

Towed sonar fitted in some units post war

### Mounts

1 × .50 in (12.7 mm) M2 Browning machine gun
2x .30 (7.62) Browning machine guns optional in aft of control car

Bomb bay (2x depth charges)
External Hardpoints (2x depth charges)

### Loadout Options

Ferry
Standard ASW - 4 × 350 lb (160 kg) AN-Mk 47 depth charges, Sonobuoys, 2x Drop tanks
Maritime Patrol - 4x M-17 Bombs (500lb cluster so probably other 500 lb or smaller bombs)
Mixed ASW - 2x AN-Mk-47 Depth Charges, 2x M-17 Bombs
Mine hunting - Internal Guns
SAR- Life Raft
ASW - 2x FIDO ASW Torpedo or mk44 in the 50s
Minelaying
Cargo
Para-drop

Late in the war, some also carried 7.2 inch anti-submarine rocket bombs. 

### Comms/Datalinks

UHF/VHF

### Aircraft Codes

HIFR Capable, Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Basic

### Comments

Designations

ZNP-K - The original designation of the K-class blimps.

ZPK - Revised designation of the ZNP-K series from 1947.

ZP2K - A larger envelope with the volume increased to 527,000 cu ft (14,900 m3), sensors and other improvements re-designated ZSG-2 from 1954.

ZP3K  - A larger envelope with the volume increased to 527,000 cu ft (14,900 m3), with systems and controls even more advanced than the ZP2Ks, re-designated ZSG-3 from 1954.

ZP4K - Delivered in 1953, retaining the 527,000 cu ft (14,900 m3) envelope volume and length of 266 ft (81.08 m), re-designated ZSG-4 in 1954. 15x units

ZP5K - Delivered in 1955, redisgnatied the ZS2G-1 in 1954 before delivery. 15x units

### Sources

https://en.wikipedia.org/wiki/K-class_blimp
https://www.history.navy.mil/research/histories/naval-aviation-history/navys-lighter-than-air-experience-monograph/pre-ww-ii-blilmps-and-the-evolution-of-the-k-class-and-ww-ii-airships-and-their-operations-pages-34-46.html
https://www.patriotspoint.org/news-and-events/first-practical-sonobuoy-1942/#:~:text=A%20K%2D5%20blimp%20used,NC%2C%20in%20World%20War%20II.
https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/media/airship_pilot_manual.pdf
https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/media/airship_pilot_manual.pdf
https://www.blimpinfo.com/history-2/this-mo-in-hist/this-mo-in-hist-jan/k-class-airships/
https://neam.org/pages/goodyear-znpk-28-blimp-control-car#
https://lynceans.org/wp-content/uploads/2021/08/Goodyear_N-class-blimps-converted-compressed.pdf
https://laststandonzombieisland.com/tag/k-class-blimp/
https://militaryhistorynow.com/2013/10/23/the-other-silent-service-u-s-navy-airships-of-world-war-two/
https://airandspace.si.edu/stories/editorial/k-ships-vs-u-boats
https://www.wearethemighty.com/mighty-history/zeppelins-hard-to-shoot-down/
https://discover.hubpages.com/education/World-War-2-History-The-Goodyear-Blimp-Goes-to-War
http://lompochistory.org/wp-content/uploads/2015/06/memories-of-a-wwii-blimp-pilot.pdf
https://www.theifod.com/war-blimps/
http://www.303rdbg.com/bombs.html
https://en.m.wikipedia.org/wiki/Airship (see WWII section)
https://www.usni.org/magazines/naval-history-magazine/2021/october/blimps-versus-u-boats
https://www.history.navy.mil/content/history/museums/nnam/explore/collections/aircraft/k/k-47-control-car.html
https://man.fas.org/dod-101/sys/ac/asw.htm
https://archive.navalsubleague.org/2010/book-reviews-forgotten-weapon-u-s-navy-airships-and-the-u-boat-war
https://www.history.navy.mil/content/dam/nhhc/research/histories/naval-aviation/navys-lighter-than-air-experience-monograph/pdfs/lta-09.pdf
https://www.navairdevcen.org/PDF/THE%20EVOLUTION%20OF%20THE%20SONOBUOY.pdf
https://www.naval-airships.org/wwii
https://www.naval-airships.org/post-war-cold-war
https://airshiphistory.com/wp/1-page-world-war-ii/
https://airshiphistory.com/wp/1-page-postwar-era/

![image](https://user-images.githubusercontent.com/99599482/215341070-de29ee73-1450-4658-97d7-feb68f4d8367.png)
![image](https://user-images.githubusercontent.com/99599482/215341080-7e2869d9-de7b-4b49-95f5-88b716b8ae70.png)
![image](https://user-images.githubusercontent.com/99599482/215342152-417ca460-0cd0-40e3-a4ce-0d3500ca19cf.png)
![image](https://user-images.githubusercontent.com/99599482/215343611-2633a5e8-e848-41a4-b8ac-f9901ac2e9f4.png)
![image](https://user-images.githubusercontent.com/99599482/215343644-d2cf2b48-e42e-412a-89c4-69ba718e8fc9.png)
![image](https://user-images.githubusercontent.com/99599482/216101951-bc47c413-e5cf-4adb-a50a-986d97dae5f9.png)
![image](https://user-images.githubusercontent.com/99599482/216102534-2323b755-0f58-4a5d-a011-5266cad92ed8.png)
![image](https://user-images.githubusercontent.com/99599482/216102702-ee18bddb-1994-4312-b5b0-bb10f4e1b3ae.png)
![image](https://user-images.githubusercontent.com/99599482/216103102-266a8cc7-ad9f-4f0b-abe9-aafa01b6ce05.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499. This was a fun one. I like blimps.

**Comment by tbrandon517** [comment]
> Handled 499. This was a fun one. I like blimps.

Me too. Diesel boats beware! LTA will outlast your batteries!

**Comment by tbrandon517** [comment]
Only tweaks to recommend right now is to add a spotlight to the ASW blimps. K Class flight manual above from FAA indicates on pages 103-104, 111-113 indicates a spotlight/Landing light in the electronical load chart and circuit/fuse listing. Flight manual fir the K-class indicates 55 lbs of photographic equipment so possibly add a reconnaissance camera.

I will do some more research in the postwar equipment including the Towed sonar fish if that's something potentially operable in CMO.
