### ISSUE TITLE
RCN CU-176 Gargoyle UAV

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#296]
### DB Selector

DB3K

### Hypothetical

No

### Name

CU-176 Gargoyle UAV

### Country

Canada

### Service

Royal Canadian Navy

### In Commission

2019-

### Length (m)

4.0

### Wingspan (m)

1.2

### Height (m)

1.3

### Empty Weight (kg)

195

### Maximum Takeoff Weight (MTOW) (kg)

235

### Payload Weight (kg)

40

### Crew

0

### Propulsion

1x two-cylinder, in-line, two-stroke, liquid cooled internal combustion engine

### Service Ceiling (ft)

4500

### Military/Afterburner Speed (kt)

130

### Cruise Speed (kt)

100

### Supercruise

No

### Ferry Range (nm)

150

### Endurance (min)

300

### Takeoff / Landing Distance (m)

0m (VTOL) TOD/LAD

### Sensors

1x Generic LLTV, Surveillance Camera
1x Generic Infared Surveillance Camera

### Mounts

None

### Loadout Options

- Ferry
- Maintenance
- Reserve
- Maritime Surveillance

### Comms/Datalinks

UHF/VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Sources

https://www.helis.com/database/news/ums-skeldar-canada/?noamp=1
https://www.saab.com/products/skeldar-v-200
https://en.wikipedia.org/wiki/Royal_Canadian_Navy#Warships

![V-200 2](https://user-images.githubusercontent.com/99632305/154765199-6a0fb3b1-1c52-4749-ab65-f7e51a063931.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
