### ISSUE TITLE
United States - M-Class Airship

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2960]
### DB Selector

CWDB

### Baseline

Aerostat

### Hypothetical

No

### Name

M-Class Airship (see designations below)

### Country

United States

### Service

Navy

### In Commission

1944-1956

### Number in Service

4x

### Length (m)

92.07 m

### Wingspan (m)

21.19 m

### Height (m)

28.20 m

### Empty Weight (kg)

Not Stated (greater than K-Class)

### Maximum Takeoff Weight (MTOW) (kg)

Not Stated (greater than K-Class)

### Payload Weight (kg)

4,356 kg

### Crew

10-14x

### Propulsion

2 × Pratt & Whitney R-1340-AN-2 radials , 550 hp (410 kW) each

### Rate of Climb (ft/min)

not stated

### Service Ceiling (ft)

14000 ft

### Military/Afterburner Speed (kt)

70 kn

### Cruise Speed (kt)

50 kn

### Supercruise

No

### Ferry Range (nm)

Not Stated (greater than K-Class)

### Endurance (min)

50 hours 30 minutes

### Takeoff / Landing Distance (m)

VTOL

### Fuel Capacity (kg)

Not Stated (greater than K-Class)

### Sensors

Radar
MAD
Searchlight
Binoculars

### Mounts

1 × .50 M2 machine gun

### Loadout Options

- Ferry
- Standard ASW - 8 × 350 lb (159 kg) AN-Mk 47 depth charges, sonobuoys
- Loadouts similar to K-Class but with similar payload increase.

### Comms/Datalinks

UHF/VHF

### Aircraft Codes

HIFR Capable, Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Basic

### Comments

Intended for tropical use and volume increased by 50% based on experience with K-Class.

Originally designated ZNP-M to ZPM in 1947.

### Sources

https://en.wikipedia.org/wiki/M-class_blimp
https://www.patriotspoint.org/news-and-events/first-practical-sonobuoy-1942/#:~:text=A%20K%2D5%20blimp%20used,NC%2C%20in%20World%20War%20II.
https://www.history.navy.mil/research/histories/naval-aviation-history/navys-lighter-than-air-experience-monograph/pre-ww-ii-blilmps-and-the-evolution-of-the-k-class-and-ww-ii-airships-and-their-operations-pages-34-46.html
https://lynceans.org/wp-content/uploads/2021/08/Goodyear_N-class-blimps-converted-compressed.pdf
https://www.naval-airships.org/post-war-cold-war
https://airshiphistory.com/wp/1-page-world-war-ii/
https://airshiphistory.com/wp/1-page-postwar-era/

![image](https://user-images.githubusercontent.com/99599482/215344438-7f37faac-1856-406c-ab76-e5a6d8bdda24.png)
![image](https://user-images.githubusercontent.com/99599482/216108441-d08b3087-b0bf-4acd-8d09-62db1a7a4a08.png)
![image](https://user-images.githubusercontent.com/99599482/216108821-72bed974-0127-40ab-90eb-5d85b0cf8645.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
