### ISSUE TITLE
United States - N-Class Airships

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2961]
### DB Selector

CWDB

### Baseline

Aerostat

### Hypothetical

No

### Name

N Class Airship (See Designations Below)

### Country

United States

### Service

Navy

### In Commission

1952-1962

### Number in Service

18x total across all variants

### Length (m)

104.57 m

### Wingspan (m)

23.17 m

### Height (m)

32.62 m

### Empty Weight (kg)

Not Stated (greater than M-Class)

### Maximum Takeoff Weight (MTOW) (kg)

Not Stated (greater than M-Class)

### Payload Weight (kg)

Not Stated (greater than M-Class)

### Crew

21-15x

### Propulsion

2 × Wright R-1300-4,-4A Cyclone 7 radials , 800 hp (600 kW) each

### Rate of Climb (ft/min)

Not Stated

### Service Ceiling (ft)

14000 ft

### Military/Afterburner Speed (kt)

70 kn

### Cruise Speed (kt)

50 kn

### Supercruise

No

### Ferry Range (nm)

Not Stated (greater than M-Class)

### Endurance (min)

over 200 hours

### Takeoff / Landing Distance (m)

VTOL

### Fuel Capacity (kg)

Not Stated (greater than M-Class)

### Sensors

ZPG-2W 
AN/APS-20 radar with its antenna installed beneath the gondola. 
AN/APS-69 height-finding radar antenna was mounted on top of the envelope.

ZPG-3W Vigilance
AN/APS-70 Radar with its antenna installed ab ovethe gondola in the envelope. 
AN/APS-69 height-finding radar antenna was mounted on top of the envelope.

Patrol Models 
AN/APS-20 radar with its antenna installed beneath the gondola. 
Others as per K & M-Class

### Mounts

Patrol Models Only
1x M2 12.7mm HMG

### Loadout Options

- Ferry

SZ-1 Aircraft as following K and M Class
ASW
Maritime Patrol
SAR
Minespotting
Minelaying
Cargo

EZ-1 Series
-AEW

### Comms/Datalinks

UHF/VHF

### Aircraft Codes

HIFR Capable, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Basic

### Comments

Follow on to M-Class with 50% increase in volume.

Initial Designation - ZPN-1, to ZPG-1 in 1954, and then to SZ-1A in 1962, 1x Unit

Initial Desination - ZP2N, re-designated in 1954 as the ZPG-2, 12x units total, 3x Units converted to AEW, 1x used as testbed for ZPG-3W. to SZ-1B in 1962

Initial Designation - ZP2N-1W (but at delivery were designated ZPG-2W). Their designation was changed to EZ-1B in 1962. 5x units total, 3x converted from ZPG-2.

Initial Designation - ZPG-3W Vigilance, to EZ-1C 1962, 4x United Total

### Sources

https://en.wikipedia.org/wiki/N-class_blimp
https://lynceans.org/wp-content/uploads/2021/08/Goodyear_N-class-blimps-converted-compressed.pdf
https://www.patriotspoint.org/news-and-events/first-practical-sonobuoy-1942/#:~:text=A%20K%2D5%20blimp%20used,NC%2C%20in%20World%20War%20II.
https://www.globalsecurity.org/wmd/systems/zpg-2.htm
https://www.defensemedianetwork.com/stories/a-very-short-history-of-postwar-military-airships/
http://www.blimpinfo.com/wp-content/uploads/2012/01/Images-of-ZPG-3W-Blimps.pdf
https://www.thisdayinaviation.com/tag/goodyear-zpg-2/
https://www.history.navy.mil/content/dam/nhhc/research/histories/naval-aviation/navys-lighter-than-air-experience-monograph/pdfs/lta-10.pdf
https://www.naval-airships.org/post-war-cold-war
https://airshiphistory.com/wp/1-page-postwar-era/

![image](https://user-images.githubusercontent.com/99599482/215345925-ecbee848-dbf1-4bc3-8a12-de2c608521da.png)

ZPG-3W
![image](https://user-images.githubusercontent.com/99599482/215345967-6cffd7b6-f661-479f-90c0-f89775a7de04.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
