### ISSUE TITLE
LARC-LX Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2963]
### DB Selector

DB3K

### Affected DBID(s)

LARC-LX

### Summary of Changes

Unit Should be amphibious

### Sources

https://en.wikipedia.org/wiki/LARC-LX
https://www.thedrive.com/news/39228/the-us-armys-largest-4x4-ever-the-gigantic-1000-hp-larc-lx-amphibious-vehicle
https://www.thedrive.com/news/giant-vietnam-era-amphibious-vehicles-land-on-another-nj-beach

**Comment by PygmalionOfCyprus** [comment]
Handled 499.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus seems S if only land stats are available again for the LARC LX as of v503.

**Comment by PygmalionOfCyprus** [comment]
For the ground unit? My DB still shows the amphib code and water range/speed.

**Comment by tbrandon517** [comment]
> For the ground unit? My DB still shows the amphib code and water range/speed.

Will grab an image of what my display shows when I get home.

**Comment by tbrandon517** [comment]
This is what I see. Just Land SPECs

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/42209552-7e4a-40f1-a79f-e2ce3ce44cf5)

I checked some other Ground Units (AAV-7 Below) to see if it was a display issues with details just not appearing for amphibious units but I do see both for others.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/034e211e-87a4-49bf-961a-bf5fba068692)

**Comment by PygmalionOfCyprus** [comment]
Found it. The propulsion entry didn't have a band defined for water and there wasn't a max sea state set. Fixed 505.
