### ISSUE TITLE
Increase Bayraktar TB2 Endurance

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#2966]
### DB Selector

DB3K

### Affected DBID(s)

#5403, #5397, #5951, #6045, #5875, #5923, #5396, #5402, #5476, #6043, #5708, #5395, #5398, #6044, #4736, #5394, #4749, #5399, #4820, #5400, #5401   

### Summary of Changes

Currently the endurance of the TB2 at loiter speed is around 4 hours and 20 minutes. This is most likely based of the max range of the drone, but the max range of the TB2 in real life is not based on the maximum endurance, but the maximum range from the ground control station. The actual endurance of the TB2 is around 24 hours. The current endurance has a massive impact on the use of the TB2 in game and is unrealistic.

### Sources

https://www.janes.com/defence-news/news-detail/update-kuwait-orders-bayraktar-tb2-uavs
https://www.dailysabah.com/defense/2019/07/19/turkeys-indigenous-bayraktar-drone-breaks-endurance-record

**Comment by PygmalionOfCyprus** [comment]
Weirdly, about half of them do have an endurance of 24 hours set, but the other half don't. Anyway, handled 499.
