### ISSUE TITLE
Fuel consumption MQ-88 Fire Scout

### ISSUE THREAD

**Issue by Quark-73** [PygmalionOfCyprus/cmo-db-requests#2968]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #4784, #1006, #3458, #3455

### Summary of Changes

see: https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=391873

According Performance Details it has the loweset fuel consumption at max speed. Regarding to all other helo-type drones and helicopters I've looked so far in CMO have the lowest consumption in loiter.

According to the stated 5 h mission time (fully loaded) and 150 kg fuel capacity acc. CMO-DB it should be .5 l/min in loiter for 8 h endurance (170 lb payload) it should be only .3125 kg/min.

It was more reasonable some build numbers before but I cant give information in wich DB-version it changed since I don't know how to rollback just the DB.

### Sources

https://en.wikipedia.org/wiki/Northrop_Grumman_MQ-8_Fire_Scout

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
