### ISSUE TITLE
Meteor Missile Burn needs to go longer to sustain

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2969]
### DB Selector

DB3K

### Affected DBID(s)

961

### Summary of Changes

See these posts. The Meteor propulsion should burn longer to take advantage of its sustain feature. This missile is used a lot in NEZ chit-chat because it is supposed to sustain and have a better NEZ than missiles without the capability.

### Sources

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=392358&p=5073245#p5073245
https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=391209&p=5062649&hilit=meteor#p5062649
https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=389723&p=5047757&hilit=meteor#p5047757

**Comment by PygmalionOfCyprus** [comment]
This should be fixed in 499, we've added a new "Ramjet" propulsion type with behavior similar to the "Rocket [Long Burn]' propulsion which Meteor will be using (among other weapons).
