### ISSUE TITLE
CA Inf Plt (Canadian Army) 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#297]
### DB Selector

DB3K

### Affected DBID(s)

2385

### Summary of Changes

Replace generic AT weapon with 84mm Carl Gustav M3

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Canadian_Army
https://canadianarmytoday.com/whats-next-for-the-carl-g/

**Comment by Jkryos** [comment]
Updated DB3K 494.
