### ISSUE TITLE
China - Type 625E SHORAD

### ISSUE THREAD

**Issue by usarmyjoe** [PygmalionOfCyprus/cmo-db-requests#2973]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

Type 625E SHORAD

### Facility Type

AAA

### Country

China

### Service

Army

### In Commission

2023

### Sensors

AESA Radar UNK Type yet

### Mounts

HQ-10 Missile  x 8
25mm Gatling Gun with explosive rounds

### Comments

Anti-Drone Wheeled 8x8

![image](https://user-images.githubusercontent.com/12349678/216425820-39dd79a4-910b-4c1d-9648-7c84b1f4f8a1.png)

### Sources

https://www.thedrive.com/the-war-zone/this-is-chinas-beastly-new-chinese-air-defense-vehicle
https://www.scmp.com/news/china/military/article/3201007/china-has-unveiled-new-short-range-air-defence-systems-target-drones
https://eurasiantimes.com/edited-china-unveils-new-shorad-system-armed-with-missiles/

**Comment by bostonmyk** [comment]
More imagery and PLAGF seems to be operating them. Little less fancy than the export version..hehe

Most sites say 6 barrel 35mm + 4 FN-6/16. EO director for sure. Radar FC on some. Seems to be a mix, so if you're matching the [2] mount pattern of CMO facilities maybe 1 with FCR and 1 without. Maybe they're all getting at some point??? Open question

https://twitter.com/Nickatgreat1220/status/1648903487743492099
https://twitter.com/Nickatgreat1220/status/1679137114951237633
https://twitter.com/Nickatgreat1220/status/1677611818683072513/photo/1
https://www.sinodefenceforum.com/t/pla-anti-air-gun-systems.872/page-30
https://www.sinodefenceforum.com/t/pla-anti-air-gun-systems.872/page-27
https://www.sinodefenceforum.com/t/pla-anti-air-gun-systems.872/page-31
https://www.armyrecognition.com/weapons_defence_industry_military_technology_uk/china_army_receives_new_cs/sa5_spaag_gun/missiles_air_defense_vehicles.html
https://en.wikipedia.org/wiki/Type_08

**Comment by bostonmyk** [comment]
https://twitter.com/kt396/status/1646864060938596354

**Comment by bostonmyk** [comment]
More:
https://twitter.com/jesusfroman/status/1739929353671037356

**Comment by bostonmyk** [comment]
More

https://twitter.com/jesusfroman/status/1775791961254903953

**Comment by Jkryos** [comment]
Added DB3K 507.
