### ISSUE TITLE
Correction: China, Type 022 Houbei PCFG, Fuel quantity issue

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#2974]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2002

### Summary of Changes

Happened to find that it only has 0.8t fuel storage which is unreasonably low. Maybe a long-existed DB error? Change to 8t will be better, take P 960 Skjold (ship 627) or Pr.205u Osa II (ship 134) for reference.

### Sources

![image](https://user-images.githubusercontent.com/107970049/216547269-366fafb2-39cf-4f8f-91be-430fcc9e7a56.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
