### ISSUE TITLE
Aerostar Tactical UAS - Azerbaijan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2976]
### DB Selector

DB3K

### DBID to Copy

aircraft 5931

### Hypothetical

No

### Name

Aerostar Tactical UAS

### Country

Azerbaijan

### Service

Air Force

### In Commission

2009-

### Number in Service

~60x

### Sensors

EO/IR Turret w/ laser designator

Synthetic Aperture Radars (SAR)\GMTI and various electronic intelligence sensors (COMINT, ELIINT) and other advanced payloads can be equipped in a large payload bay.

### Mounts

N/A

### Loadout Options

-Ferry
-Internal Recon
-ELINT
-Recon - SAR Payload

### Other Changes

UAV Datalink + SATCOM

### Sources

https://www.oryxspioenkop.com/2021/12/death-from-above-azerbaijans-killer.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.armyrecognition.com/adex_2022_news_official_show_daily/azerbaidjan_displays_aerostar_bp_unmanned_aircraft_system_at_adex.html
https://www.suasnews.com/2011/10/azeris-get-israel-uavs-built-under-license/
https://www.flightglobal.com/civil-uavs/azerbaijan-requires-more-israeli-uavs-for-border-conflict/120411.article
https://armenpress.am/eng/news/1059473.html

Aerostar
![image](https://user-images.githubusercontent.com/99599482/216630036-961f12e3-5c11-44bd-b918-6522c33aa0d7.png)

Shahin (Locally Produced Copy)
![image](https://user-images.githubusercontent.com/99599482/216630171-4ddb0f41-3f56-45a6-a86d-cb086fd629dd.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
