### ISSUE TITLE
Turkmenistan - FAC 33

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2977]
### DB Selector

DB3K

### Baseline

ship 4011

### Hypothetical

No

### Name

SG119 Nayza

### Class

FAC 33

### Country

Turkmenistan

### Service

Navy

### In Commission

2015-

### Number in Service

6x

### Length (m)

33.05 meters

### Beam (m)

7.1 meters

### Draft (m)

1.4 meters

### Standard Displacement (t)

Not Stated

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

Not Stated

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU M93L diesel engines with 2x Hamilton water jets

### Fuel Capacity (kg)

400

### Flank Speed (kt)

43 knots

### Range (nm) at Speed (kt)

350 nm @ 35 knots

### Sensors

radar, ASELFLIR e/o system

### Mounts

4x Marte Mk2 Anti-Ship Missiles (2 missiles is the standard fit)
1x 25mm ASELSAN STOP RWS
2x 12.7mm Machine Gun

### Aircraft & Docking Facilities

1x Stern ramp for RHIB

### Comms/Datalinks

VHF/UHF

### Sources

https://www.oryxspioenkop.com/2021/03/small-but-deadly-turkish-fast-attack.html
https://en.wikipedia.org/wiki/Turkmen_Naval_Forces
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/year-2015-news/may-2015-navy-naval-forces-defense-industry-technology-maritime-security-global-news/2710-turkish-shipyard-dearsan-will-deliver-six-33-meters-fast-attack-craft-to-turkmenistan.html
https://www.newscentralasia.net/2022/11/21/turkmenistan-navy-qualitative-development/
https://www.navypedia.org/ships/turkmenistan/turk_cg_sg121.htm

![image](https://user-images.githubusercontent.com/99599482/216637263-9be8d536-3bd1-4d34-ba7d-4d7b3875c240.png)
![image](https://user-images.githubusercontent.com/99599482/216640390-2714d95c-83ff-4d62-8b49-805df9756505.png)
![image](https://user-images.githubusercontent.com/99599482/216638097-0d0c62b0-1a9e-47cc-8206-e5a4fa427249.png)
![image](https://user-images.githubusercontent.com/99599482/216641586-99ab03ac-6bab-454d-b3eb-27460c36c1a6.png)
![image](https://user-images.githubusercontent.com/99599482/216642029-85c88e96-677d-4455-abd6-a823c72bd019.png)

**Comment by Jkryos** [comment]
Added DB3K 507.
