### ISSUE TITLE
Turkmenistan - Tuzla-class patrol boat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2978]
### DB Selector

DB3K

### DBID to Copy

ship 3250

### Hypothetical

No

### Name

SG111 Arkadag

### Country

Turkmenistan

### Service

Navy

### In Commission

2015-

### Number in Service

10x

### Sensors

Scout/Variant 2D radar, 
ASELFLIR e/o system, S
P-92 Mk 2 sonar, 
Genesis CCS

### Mounts

4x Otomat Mk2 Anti-Ship Missiles or 4x Marte Mk2 Anti-Ship Missiles
1 x 2 - 40mm/70 Breda-Bofors Compact Twin 40
2 x 1 - 25mm/92 STOP, 
2x 12.7mm ASELSAN STAMP RWS
2 x 6 ASRLS ASWRL, 
1 DCT

2016-2018, all: + 2 x 2 SIMBAD-RC SAM (12 Mistral 2)

### Loadout Options

N/A

### Sources

https://en.wikipedia.org/wiki/Tuzla-class_patrol_boat
https://en.wikipedia.org/wiki/Turkmen_Naval_Forces
https://www.navypedia.org/ships/turkmenistan/turk_cg_arkadag.htm
https://www.newscentralasia.net/2022/11/21/turkmenistan-navy-qualitative-development/
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2017/january-2017-navy-naval-forces-defense-industry-technology-maritime-security-global-news/4846-turkmenistan-s-coast-guard-patrol-boat-spotted-with-simbad-rc-short-range-naval-air-defence-system.html

![image](https://user-images.githubusercontent.com/99599482/216644466-38c05849-af9e-4cde-8190-9924b3e3cab3.png)
![image](https://user-images.githubusercontent.com/99599482/216644601-7ff7608d-85b7-437c-88fb-2b8e7fb1fe57.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501. Navypedia is wrong about the two ASWRL launchers. There's only one; you can see it on the bow just behind the main mount.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus is ot possible to make the SSM launchers dual capable for Otomat and Marte Mk2 similarly to this facility? I couldn't find a source that contradicted the posted ones stating they can fire both. NP if I'm wrong though!

https://cmano-db.com/facility/3638/

**Comment by PygmalionOfCyprus** [comment]
Are the launchers themselves dual-capable, or is it that some of the ships may/have Marte instead of Otomat? I was going off the NavyRecognition link that said "Otomat Mk 2 are likely fitted on the Turkmen NTPB patrol vessels."

**Comment by tbrandon517** [comment]
> Are the launchers themselves dual-capable, or is it that some of the ships may/have Marte instead of Otomat? I was going off the NavyRecognition link that said "Otomat Mk 2 are likely fitted on the Turkmen NTPB patrol vessels."

Maybe some are fitted differently? The News Central Asia piece says...

"Ten large 400-ton, 57-meter NTPB (New Type Patrol Boat) missile-artillery boats were assembled there, based on Turkish Tuzla patrol ships with a maximum speed of 25 knots and a range of 1,000 miles. On the superstructure they are equipped with two dual-package Italian Otomat Mk 2 anti-ship missile launchers with a range of up to 180 km and 210 kg fragmentation and shaped charge warheads or the same number of compact Marte Mk 2/N Sea Killer anti-ship missiles with a 70-kg warhead and a range of 30 km."

But I initially assumed dual capability based on "they ate equipped with two dual package" wording.

**Comment by PygmalionOfCyprus** [comment]
I read that as an awkward translation of "twin launcher": that is, two twin launchers, which is what they have. I don't think the missiles are hot-swappable, I think it's more "you could theoretically put boxes for either missile on there," which isn't saying very much.

I'm going to leave it for now because it's a little fuzzy. Replacing the mounts isn't hard in ScenEdit and there is a mount for dual Marte Mk2/N, so it's relatively trivial to do if necessary for a scenario. If we get info that they are putting to sea with Marte then I can make a new entry for that variant.

**Comment by tbrandon517** [comment]
> I read that as an awkward translation of "twin launcher": that is, two twin launchers, which is what they have. I don't think the missiles are hot-swappable, I think it's more "you could theoretically put boxes for either missile on there," which isn't saying very much.
> 
> I'm going to leave it for now because it's a little fuzzy. Replacing the mounts isn't hard in ScenEdit and there is a mount for dual Marte Mk2/N, so it's relatively trivial to do if necessary for a scenario. If we get info that they are putting to sea with Marte then I can make a new entry for that variant.

Sound good to me!
