### ISSUE TITLE
Add Myanmmar Kilo submarine. Minye Theinkhathu [PL-877E].2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#298]
### DB Selector

DB3K

### DBID to Copy

Submarine 166

### Hypothetical

No

### Name

71 Minye_Theinkhathu [PL-877E Kilo]

### Country

Myanmar

### Service

Navy

### In Commission

2021

### Mounts

Likely don't have Sizzlers.

### Sources

https://twitter.com/CollinSLKoh/status/1342218879561388032
https://twitter.com/Crimson249996/status/1342011353477758976
https://twitter.com/aag_th/status/1342153312343244802
https://dambiev.livejournal.com/2168511.html
https://en.wikipedia.org/wiki/UMS_Minye_Theinkhathu

**Comment by PygmalionOfCyprus** [comment]
Added 493.
