### ISSUE TITLE
T-AGM-22 Range Sentinel (ex-Sherburne APA-205, Haskell Class)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2981]
### DB Selector

CWDB

### DBID to Copy

ship 484

### Hypothetical

No

### Name

T-AGM-22 Range Sentinel

### Country

United States

### Service

Navy

### In Commission

1971-1997

### Number in Service

1x

### Sensors

2x Navigation Radars
4x Tracking Radars (AN/FPQ-4 based on American Mariner caption photo)

### Mounts

None

### Loadout Options

N/A

### Other Changes

Can be added to DB3K as well.
4x boat davits 

### Sources

https://en.wikipedia.org/wiki/USS_Sherburne_(APA-205)
https://vesselhistory.marad.dot.gov/documents/2624bbe7-30bb-4661-ac92-a3b56b31db22.pdf
http://www.navsource.org/archives/10/03/03205.htm
http://mail.afspacemuseum.org/ccafs/ships/

![image](https://user-images.githubusercontent.com/99599482/216670491-8d8fc4ce-01fd-4415-9775-522baf370c8a.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
