### ISSUE TITLE
T-AGM-12 American Mariner - Tracking Ship

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2983]
### DB Selector

CWDB

### DBID to Copy

ship 2285

### Hypothetical

No

### Name

T-AGM-12 American Mariner

### Country

United States

### Service

Army (1958-1963), Air Force (1963-1964), Navy (1964-1966)

### In Commission

1959-1966

### Number in Service

1x

### Sensors

RCA C-band-frequency narrow-beam tracking radar 
RCA L-band-frequency narrow-beam tracking radar 
RCA UHF-band-frequency narrow-beam tracking radar 
Infra-red systems, 
optics 70 mm cameras, 
AGAVE

The primary tracking radars were CBAND radars, which once locked onto their target were accurate within 6.1 metres (20 ft) at a distance of 2,000 kilometres (1,200 mi).  The L-Band radar dish was straddled by the twin C-Band radar dishes.

### Mounts

None

### Loadout Options

N/A

### Sources

https://en.wikipedia.org/wiki/USAS_American_Mariner
https://en.wikipedia.org/wiki/DAMP_Project
https://vesselhistory.marad.dot.gov/ShipHistory/Detail/210
http://www.navsource.org/archives/09/53/09531201.jpg

![image](https://user-images.githubusercontent.com/99599482/216688990-8f9eeca8-ef77-403b-b34a-9b4b460d3466.png)
![image](https://user-images.githubusercontent.com/99599482/216689577-d71da92e-7ddb-4a3f-98b3-cf10bec08f56.png)

**Comment by PygmalionOfCyprus** [comment]
Can you try to dig up a little extra data for the AN/FPQ-4 and the mysterious "L Band radar"? Range and power at a bare minimum, just something to build off of. I can also take a similar contemporary platform if you find info for something that came before/after. Sensor data is all that's stopping me from easily handling this and the other tracking ship request(s).

**Comment by PygmalionOfCyprus** [comment]
Yeah, the L-band is the real challenging one.

**Comment by tbrandon517** [comment]
https://www.wikiwand.com/en/Project_DAMP

I think the combined L/UHF Band array may be akin to a scaled down (30 ft vs 60 ft dish) AN/FPS-80

https://en.wikipedia.org/wiki/United_States_Space_Surveillance_Network
https://en.wikipedia.org/wiki/AN/FPS-17
https://www.radartutorial.eu/19.kartei/01.oth/karte013.en.html
https://www.history.navy.mil/research/library/online-reading-room/title-list-alphabetically/f/from-sea-stars.html
https://apps.dtic.mil/sti/tr/pdf/ADA995287.pdf - This one how power/frequency for the L/UHF set
https://ntrs.nasa.gov/api/citations/19660007629/downloads/19660007629.pdf
https://core.ac.uk/download/pdf/217147896.pdf
https://ntrs.nasa.gov/api/citations/19680025550/downloads/19680025550.pdf

**Comment by tbrandon517** [comment]
Sources also indicate a AN/FPS-12 for local air control

**Comment by PygmalionOfCyprus** [comment]
When convenient, can you open separate sensor requests for the AN/FPQ-4 and not-AN/FPS-80 with info filled in as possible or guesstimated based on similar platforms / estimations where possible? Bonus points for the AN/FPS-12, although I'm more comfortable just copying a generic ATC radar for that one since local air control isn't exactly the major selling point of these ships. :P

**Comment by tbrandon517** [comment]
> When convenient, can you open separate sensor requests for the AN/FPQ-4 and not-AN/FPS-80 with info filled in as possible or guesstimated based on similar platforms / estimations where possible? Bonus points for the AN/FPS-12, although I'm more comfortable just copying a generic ATC radar for that one since local air control isn't exactly the major selling point of these ships. :P

Sure probably on Wednesday

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus submitted as #3935 and #3937 for radars. My first real attempt at a radar item so be gentle.

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
