### ISSUE TITLE
C-145A Combat Coyote

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#299]
### DB Selector

DB3K

### DBID to Copy

aircraft 3341 (DB3K)

### Hypothetical

No

### Name

C-145A Combat Coyote

### Country

United States

### Service

Air Force

### In Commission

2007-

### Sensors

Remove Existing Sensors and reduce to transport role only.

### Mounts

None

### Loadout Options

Ferry
Reserve
Maintenance
Troop Transport
Paratroopers
Cargo

### Sources

https://www.af.mil/About-Us/Fact-Sheets/Display/Article/467765/c-145a/
https://www.afsoc.af.mil/About-Us/Fact-Sheets/Display/Article/2547290/c-145a-combat-coyote/
https://www.afsoc.af.mil/About-Us/Fact-Sheets/Indextitle/C/
https://www.airforce-technology.com/projects/c-145a-skytruck-light-twin-engine-aircraft/
https://en.wikipedia.org/wiki/PZL_M28_Skytruck#Variants
https://www.thedrive.com/the-war-zone/9638/these-unassuming-planes-have-been-key-players-in-americas-war-on-terror

![image](https://user-images.githubusercontent.com/99599482/154772318-348c9962-31f7-440f-a14c-f590ed9d24cc.png)

**Comment by PygmalionOfCyprus** [comment]
Also looks like the C-145As had engines replaced w/ PT6A-65Bs.

**Comment by Jkryos** [comment]
Added DB3K 493.
