### ISSUE TITLE
F 110 Bonifaz - 2025 #3864

### ISSUE THREAD

**Issue by Sten1314** [PygmalionOfCyprus/cmo-db-requests#2991]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3864

### Description of Problem

The unit F 110 Bonifaz - 2025 #3864 does not move.

**Comment by PygmalionOfCyprus** [comment]
I can't replicate this on my version of Command using 498a. Can you attach a save?

**Comment by Sten1314** [comment]
Yes, of course.



Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Ethan ***@***.***>
Enviado: lunes, 6 de febrero de 2023 16:40
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [PygmalionOfCyprus/cmo-db-requests] F 110 Bonifaz - 2025 #3864 (Issue #2991)


I can't replicate this on my version of Command using 498a. Can you attach a save?

**Comment by PygmalionOfCyprus** [comment]
Still waiting on that save; if you attached it via email, it didn't come through. You'll need to attach it here, through the proper Github website.

**Comment by Sten1314** [comment]
[Testeo.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10711391/Testeo.zip)
Ok

**Comment by PygmalionOfCyprus** [comment]
Bonifaz had no fuel in v495, apparently (the DB used in the scenario); was fixed at some point and is no longer an issue.
