### ISSUE TITLE
F 110 Bonifaz - 2025 without CAPTAS 4

### ISSUE THREAD

**Issue by Sten1314** [PygmalionOfCyprus/cmo-db-requests#2992]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3864

### Summary of Changes

The ship lacks the CAPTAS 4 towed sonar, which is its raison d'être as a modern anti-submarine frigate.

### Sources

https://www.revistaejercitos.com/2020/01/02/captas-4/
https://www.infodefensa.com/texto-diario/mostrar/3126943/unibaso-thales-f-110-tendran-capacidades-guerra-antisubmarina-ultima-generacion
https://www.buquesdeguerra.com/es/buques-armada-espanola/fragatas/fragatas-f-110.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
