### ISSUE TITLE
Possible Error in fuel payload and fuel consumption for Alpha 900 UAV

### ISSUE THREAD

**Issue by K1l0tangoDef3nce** [PygmalionOfCyprus/cmo-db-requests#2994]
### DB Selector

DB3K

### Affected DBID(s)

5899, 5463

### Description of Problem

UAV has 200kg of fuel in DB instead of 4 kg in company's site
Moreover, fuel consumption is abdnormal high compared to other VTOL UAV eg. Camcopter. According to constructor's site the Alpha 900 UAV seems to have up to 4hr endurance while in DB has only over an hour
![image](https://user-images.githubusercontent.com/99611473/216780897-3d5ec924-3296-4815-8075-59bb5f64c45f.png)
![image](https://user-images.githubusercontent.com/99611473/216780933-2cbd8738-9d50-4e23-b4fc-1a0af88c935d.png)
https://alphaunmannedsystems.com/product/uav-helicopter-alpha-900/

### Recommended Fix

Adjust fuel quantity and fuel consumption  accordingly

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
