### ISSUE TITLE
FDI fregate for france

### ISSUE THREAD

**Issue by PatrioticFR** [PygmalionOfCyprus/cmo-db-requests#2996]
On command v1.05 Build 1307
DB3K 498a

The FDI fregate have only Aster 15 while they should have instead Aster 30.

Source:
https://www.latribune.fr/entreprises-finance/industrie/aeronautique-defense/pourquoi-la-france-lance-le-fregate-belh-arra-608783.html

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
