### ISSUE TITLE
R91 Charles de Gaulle EW equipment

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#2999]
### DB Selector

DB3K

### Affected DBID(s)

Ship #1734 #440 #469 #2787 #2754

### Summary of Changes

Add the folowing electronic warfare equipment to the French aircraft carrier Charles de Gaulle:
1 x ARBR 21 #2286
2 x ARBB 33 #1081

### Sources

https://www.naval-technology.com/projects/gaulle/
https://www.seaforces.org/marint/French-Navy/Aircraft-Carrier/R-91-FS-Charles-de-Gaulle.htm
https://www.navypedia.org/ships/france/fr_cv_charles_de_gaulle.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
