### ISSUE TITLE
LVSR 20ft Containers

### ISSUE THREAD

**Issue by fmachanda** [PygmalionOfCyprus/cmo-db-requests#3000]
### DB Selector

DB3K

### Affected DBID(s)

Ground Unit 149

### Summary of Changes

I think the Mk.18 LVSR is able to transport 20ft ISO containers in real life (see sources). However, in the game, the Mk.18 LVSR has a cargo area capacity of 16.00 sq m. which is just slightly too small to transport any of the ISO 20ft containers (area: 16.04), making US military ground logistics difficult to simulate. Could you please increase the LVSR's capacity or decrease the container size by 0.04 sq m. to make these compatible with each other?

### Sources

https://man.fas.org/dod-101/sys/land/mk48.htm
https://midwestmilitaryequipment.com/1987-oshkosh-mk48-mk18-container-handler-lvs-8x8-cargo-truck/

**Comment by PygmalionOfCyprus** [comment]
See #3002
