### ISSUE TITLE
M1074 PLS

### ISSUE THREAD

**Issue by fmachanda** [PygmalionOfCyprus/cmo-db-requests#3001]
### DB Selector

DB3K

### Hypothetical

No

### Name

M1074 PLS

### Facility Type

Supply

### Country

United States

### Service

Army

### In Commission

1992-

### Crew

2

### Sensors

1x Mk1 Eyeball

### Comments

Ideally, make this a ground unit and not facility (I couldn't find an issue option for ground units). Also, please put at least 16.04 sq m. cargo area capacity to fit 20ft ISO containers (unlike current Ground Unit #340 which is 0.04 sq m. too small).

### Sources

https://man.fas.org/dod-101/sys/land/pls.htm
https://man.fas.org/dod-101/sys/land/wsh2013/266.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
