### ISSUE TITLE
HEMTT 20ft Containers

### ISSUE THREAD

**Issue by fmachanda** [PygmalionOfCyprus/cmo-db-requests#3002]
### DB Selector

DB3K

### Affected DBID(s)

Ground Unit 340, 341, 342, 343

### Summary of Changes

Right now all HEMTT variants have a cargo area capacity of 16.00 sq m., which is just slightly too small to carry ISO 20ft containers (area: 16.04 sq m.). Technically, real life HEMTTs would need a PLS to carry ISO 20ft containers (see issue #3001), but this 0.04 sq m. difference seems unintentional and prevents users from using some of the new Cargo 2.0 features with US Army ground units.

Could you please increase the HEMTT cargo capacity or decrease the ISO 20ft containers' size by 0.04 sq m. to make these compatible?

### Sources

https://man.fas.org/dod-101/sys/land/hmett.htm
http://www.military-today.com/trucks/oshkosh_pls.htm

**Comment by PygmalionOfCyprus** [comment]
I've passed this onto our Cargo 2.0 guys; the DB doesn't take sub-metric values for cargo capacity so we're going to have the sim round cargo sizes appropriately to avoid issues like this. Closing since it's out of the DB team's hands, but this should be fixed shortly.
