### ISSUE TITLE
HMD/HMS for modernized Brazilian F-5s - Missiles for Brazilian F5s

### ISSUE THREAD

**Issue by AlexandreAlvzre** [PygmalionOfCyprus/cmo-db-requests#3003]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #3606 and #2102

### Summary of Changes

Since their modernization to F5-BR standard, both aircraft have been equipped with Elbit DASH IV HMDs integrated with Python 3 and 4 missiles. This is missing in both their DB entries. #2102 F-5EM lacks the Python 3 missile and corresponding loadouts, even though those missiles are/were deployed way more often than the MAA-1 Piranha. Also, #3606 F-5FM lacks the Python 3, Python 4 and Derby missiles and the corresponding loadouts (can be copied from #2102). 

### Sources

https://www.aeroflap.com.br/as-garras-do-tigre-conheca-os-armamentos-dos-f-5-da-fab/

https://iae.dcta.mil.br/index.php/slideshow/697-iae-realiza-revalidacao-de-misseis-python-4-e-derby-com-transferencia-de-tecnologia-para-o-brasil

https://www.aereo.jor.br/2010/11/04/f-5em-com-missil-python-iv/

![F-5EM-Python-4](https://user-images.githubusercontent.com/19693957/217403701-4f8186be-e824-4a03-ac31-71394c47ec9a.jpg)

**Comment by tbrandon517** [comment]
Related to request #1557 in regards to HMDs.

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
