### ISSUE TITLE
Sensor #2451 Cobra Dane upgraded to support firing-quality missile tracking 

### ISSUE THREAD

**Issue by Thewood1** [PygmalionOfCyprus/cmo-db-requests#3005]
https://missilethreat.csis.org/defsys/cobra-dane/

https://www.mda.mil/global/documents/pdf/cobradane.pdf

The Cobra Dane was upgraded to turn 2000 mile detection into a firing-quality track for interceptor launch.  It might the piece of the US ABM tracking we've been looking for.  Not sure on the accuracy of the info on the 2000 mile range for launching a missile, but the US has declared to be part of the overall Pacific BMDS.  Should be either 1990s or 2000s tech.  I think the upgrade in 2004 made it an L band radar.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
