### ISSUE TITLE
Kh-55 / Kh-555 Air launched Decoy? 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3007]
### DB Selector

DB3K

### DBID to Copy

Weapon AS-15 Kent  Kh-55/555 nuclear? 

### Hypothetical

No

### Name
 AS-15 decoy (Kh-55 Kh-555)

### Country

Russia 

### Service

VKS AF

### In Commission

2022

### Number in Service

To be confirmed

### Sensors

Nil

### Mounts

Chaff dispenser? 

### Loadout Options

N/A but loadout to match om Tu-95 Tu-160? 

### Other Changes

Inert warhead 

### Sources

https://twitter.com/UAWeapons/status/1624075218384830466?t=_zcjR7Ly77Nzxhma9pgHig&s=19
https://twitter.com/_davemorrison/status/1624082106283352064?t=vM-S3K-rSJ03-n7aO_F5gg&s=19
This and many others.

**Comment by PygmalionOfCyprus** [comment]
Handled 501. Added to Tu-160, Tu-160M, and Tu-95 as both a fully inert loadout and a mixed live/inert loadout.
