### ISSUE TITLE
Venezuelan Satellites VRSS-1 and VRSS-2 Error

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#3009]
### DB Selector

DB3K

### Affected DBID(s)

Satellite 153

### Description of Problem

Receive this error when trying to insert into a scenario:

![image](https://user-images.githubusercontent.com/99509408/218330906-43784050-0cdb-413c-b1d7-8020975c86d8.png)

### Recommended Fix

Work your magic.

**Comment by PygmalionOfCyprus** [comment]
Can you post this in the Tech Support forums? It may well be a DB issue but I don't have access to the debugger or the source code to chase down the root cause of the exception.
