### ISSUE TITLE
Dutch Caribbean Coast Guard AW139

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#3010]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5863, 6155, 6106

### Hypothetical

No

### Name

AW139

### Country

Netherlands

### Service

Coast Guard

### In Commission

2012

### Number in Service

2x

### Sensors

Everything should be the same, the only visible sensor onboard the Dutch CG AW139 is the FLIR/IR turret, which is already accounted for on the other entries. 

### Mounts

Unchanged

### Loadout Options

Unchanged

### Sources

https://web.archive.org/web/20130601192153/http://www.kustwacht.an/newsitem.php?id=196

https://kustwacht.org/fleet/?lang=en

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
