### ISSUE TITLE
UK F-35b 2021 Radar signature

### ISSUE THREAD

**Issue by Swaant** [PygmalionOfCyprus/cmo-db-requests#3014]
### DB Selector

DB3K

### Affected DBID(s)

UK F-35B 2021  DB 4947

### Summary of Changes

The loadout 25645 is internal. 2 x AIM 120 c-5, 2 x Paveway IV
The radar signature should be the same as the other internal loadouts?

### Sources

![f-35](https://user-images.githubusercontent.com/124871574/218335344-91b9ff15-dba7-482c-bf59-845cf3d1434a.gif)

**Comment by PygmalionOfCyprus** [comment]
The AIM-120s weren't marked as internal. Handled 499.
