### ISSUE TITLE
Hypothetical E-9 Joint STARS

### ISSUE THREAD

**Issue by CollectivelyCode** [PygmalionOfCyprus/cmo-db-requests#3018]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

E-9 Joint STARS

### Country

United States

### Service

Air Force

### In Commission

2022

### Length (m)

29.39

### Wingspan (m)

28.50

### Height (m)

9

### Empty Weight (kg)

21909

### Maximum Takeoff Weight (MTOW) (kg)

41275

### Crew

12

### Propulsion

2x Rolls-Royce BR710 C4-11

### Rate of Climb (ft/min)

1200

### Service Ceiling (ft)

51000

### Military/Afterburner Speed (kt)

580

### Cruise Speed (kt)

525

### Supercruise

Yes

### Ferry Range (nm)

6750

### Endurance (min)

600

### Takeoff / Landing Distance (m)

1800/845

### Fuel Capacity (kg)

18750

### Sensors

1x AN/ZPY-2 MP-RTIP
1x Generic ESM [Advanced] (2010s, Precise Emitter ID)
1x 

### Mounts

N/.A

### Loadout Options

N/A

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Probe Refuelling

### Sources

https://www.ainonline.com/aviation-news/defense/2017-07-25/jstars-contenders-argue-merits-business-jet-versus-airliner
https://www.airandspaceforces.com/gulfstreams-vision-for-a-militarized-bizjet-future/
https://www.spokesman.com/stories/2017/jun/01/boeing-puts-737-up-against-small-business-jets-for/
https://www.defenseindustrydaily.com/jumped-up-jstars-mp-rtip-technology-for-ground-surveillance-planes-05156/

**Comment by CollectivelyCode** [comment]
Will edit comms in a bit.

**Comment by KushanGaming** [comment]
Done for DB499.
