### ISSUE TITLE
Add Dornier 228-212 to Finland, 1995-2009

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3019]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2131

### Hypothetical

No

### Name

Do 228 Dornier

### Country

Finland

### Service

Border Guard

### In Commission

1995-2009

### Number in Service

2

### Other Changes

The planes had an MLU in 2009 where all systems, including avionics, radars and coms were upgraded.

### Sources

https://raja.fi/en/surveillance-aircraft-must-be-replaced

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
