### ISSUE TITLE
Add AS332 Super Puma to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3021]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4555

### Hypothetical

No

### Name

AS332L1 Super Puma

### Country

Finland

### Service

Border Guard

### In Commission

1986-2021

### Number in Service

3

### Sources

https://www.helis.com/database/modelorg/Finnish-Border-Guard-Super-Puma/

**Comment by Andratenor** [comment]
The sensor used wass the Decca/Racal Nav-1

The in commission date should end in 1998, as then the helis were updated with new equipment according to this table of all acknowledged upgrades to Finnish civilian aircraft, from the Finnish Transport Safety Agency.

The Nav-1 radar was replaced with the Marconi Seaspray 2000 and a IR/TV turret was also added.

https://www.traficom.fi/sites/default/files/media/file/9008-Suomessa_hyvaksytyt_muutostyot_20090901.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
