### ISSUE TITLE
Add H215 Super Puma to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3022]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4597

### Hypothetical

No

### Name

H215 Super Puma

### Country

Finland

### Service

Border Guard

### In Commission

2015-Present

### Number in Service

5

### Sensors

Add Generic Surface Search Radar (Sensor 6527)
Add Wescam MX-RSTA (Sensor 6929), in reality a Wescam MX-15 HDi

### Other Changes

Modern cockpit with digital avionics and fly by wire

### Sources

https://raja.fi/ilmassa
https://www.airbus.com/en/products-services/helicopters/civil-helicopters/h215/h215-missions
https://www.helis.com/database/modelorg/Finland-H215/

**Comment by Andratenor** [comment]
The radar installed is the Marconi Seaspray 2000/3000 (Sensor 2718)

Also, the dates in commision from 1998 according to this table of all acknowledged upgrades to Finnish civilian aircraft, from the Finnish Transport Safety Agency.
https://www.traficom.fi/sites/default/files/media/file/9008-Suomessa_hyvaksytyt_muutostyot_20090901.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
