### ISSUE TITLE
Add AB.412 to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3023]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6178

### Hypothetical

No

### Name

AB/B 412

### Country

Finland

### Service

Border Guard

### In Commission

1985-2015

### Number in Service

5

### Sources

https://raja.fi/ilmassa
https://www.helis.com/database/modelorg/Finland-Coast-Guard-Bell-412/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
