### ISSUE TITLE
Add AB. 412 MLU for Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3024]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5654

### Hypothetical

No

### Name

AB/B 412

### Country

Finland

### Service

Border Guard

### In Commission

2015-Present

### Number in Service

2

### Sensors

Remove Surface Search Radar
Add Night Vision Goggles 3rd Gen (Sensor 4235)
Add Generic EO/IR Turret (Sensor 6492)

### Sources

https://raja.fi/ilmassa
https://www.helis.com/database/news/ab412_border_fi/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
