### ISSUE TITLE
Add AW119 Koala for Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3025]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5519

### Hypothetical

No

### Name

AW119 Koala

### Country

Finland

### Service

Border Guard

### In Commission

2010-Present

### Number in Service

4

### Sensors

Add Generic FLIR, 3rd Gen (Sensor 1727)
Add Generic Searchlight (Sensor 251)
Add Generic Night Vision Goggles (Sensor 4235)

### Sources

https://raja.fi/ilmassa
https://www.helis.com/database/modelorg/Finland-Border-Guard-AW119/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
