### ISSUE TITLE
Update KN-25 TEL to support 4 and 6 missile Mounts

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3028]
### DB Selector

DB3K

### Affected DBID(s)

3261

### Summary of Changes

They have tracked 6 tube tracked launchers and wheeled 4 tube launchers

### Sources

6 tube
https://twitter.com/stoa1984/status/1244382598492815361
https://twitter.com/OpenNuclear/status/1625095727721644033/photo/1
https://21stcenturyasianarmsrace.files.wordpress.com/2023/01/north-korean-600mm-tracked-rocket-artillery-2022.jpg
4 Tube
https://missilethreat.csis.org/missile/kn-25/
http://www.military-today.com/artillery/kn_25.htm

**Comment by bostonmyk** [comment]
https://twitter.com/JosephHDempsey/status/1609165172190642177?cxt=HHwWgoDUldnM89QsAAAA
https://twitter.com/JosephHDempsey/status/1609546549218136064

**Comment by PygmalionOfCyprus** [comment]
Handled 500.

**Comment by bostonmyk** [comment]
Thanks for you all your updates the last couple days!

**Comment by tbrandon517** [comment]
> Thanks for you all your updates the last couple days!

2nd that. Yall are fantastic!
