### ISSUE TITLE
Add KN-24/Hwasong-11 Na North Korea 2020, Russia 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3029]
### DB Selector

DB3K

### Baseline

ATACMS 1717

### Hypothetical

No

### Name

Hwasong-11 Na [KN-24]

### Length (m)

5.7 m

### Width/Span (m)

.8

### Diameter (m)

.97

### Weight (kg)

1670

### Range (nm)

221.4 nm

### Warhead

400kg

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

30m

### Sensors

none

### Weapon Codes

Ballistic Missile or Rocket Booster, Weapon - INS w/ GNSS Navigation, Uses GLONASS, Uses BeiDou/COMPASS

### Comments

twin and quad launcher TELS
single stage
KN-23 and KN-24 Do not maneuver and no pentrator warheads (HE) see Dempsey Link

### Sources

https://www.38north.org/2020/03/melleman032520/
https://www.38north.org/2020/03/melleman032520/
https://www.38north.org/2019/10/melleman100919/
https://opennuclear.org/sites/default/files/2022-06/Xu-Increasing%20Nuclear%20Risk%20on%20the%20Korean%20Peninsula-The%20DPRK%27s%20Pursuit%20of%20Tactical%20Nuclear%20War-Fighting%20Capabilities-25%20Apr%202022_0.pdf
https://missilethreat.csis.org/missile/kn-24/
https://www.globalsecurity.org/wmd/world/dprk/kn-24.htm
https://en.wikipedia.org/wiki/KN-24
https://twitter.com/stoa1984/status/1253353450848563201
https://twitter.com/JosephHDempsey/status/1747688545253196182

**Comment by bostonmyk** [comment]
https://www.nonproliferation.eu/hcoc/north-korean-short-range-systems/

Looks like Russia Received some of these as well. 
https://www.iiss.org/online-analysis/missile-dialogue-initiative/2024/01/north-koreas-ballistic-missiles-transfer-to-russia-operational-constraints-thwart-objectives/
https://en.wikipedia.org/wiki/KN-24

**Comment by bostonmyk** [comment]
KN-24 TELs are 2 or 4 Tubes
https://twitter.com/Aryan_warlord/status/1634975212608585731/photo/2
https://twitter.com/dressler_w/status/1516100001797218304

**Comment by Jkryos** [comment]
Added DB3K 505.
