### ISSUE TITLE
Fuel Consumption Hermes UAV

### ISSUE THREAD

**Issue by Quark-73** [PygmalionOfCyprus/cmo-db-requests#3031]
### DB Selector

DB3K

### Affected DBID(s)

aircraft #5645, #5323, #5324, #4646, #5413, #5102, #5330, #5811, #5892,  #2576

### Summary of Changes

Same issue like in #2968 with MQ-8B Drone lowest fuel consumption is on max. speed. There seems to be a systematic failure.

### Sources

I have no source but it was was fine some versions ago.

**Comment by Quark-73** [comment]
Is it possible for regular users to label issues?

**Comment by K1l0tangoDef3nce** [comment]
This issue has already been handled for the next DB update
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2569

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #2569
