### ISSUE TITLE
Add 7X Talayieh [Moudge-class] Frigate

### ISSUE THREAD

**Issue by zulualpha91** [PygmalionOfCyprus/cmo-db-requests#3035]
### DB Selector

DB3K

### DBID to Copy

Ship 4128

### Hypothetical

No

### Name

7X Talayieh [Moudge-class] 

### Country

Iran

### Service

Navy

### In Commission

TBA

### Number in Service

TBA, Accidentally overturned during construction and is being repaired

### Sensors

Probably similar as Ship 4128

### Mounts

Probably similar as Ship 4128 except remove Fajr 40mm gun

### Other Changes

- The ship have hangar (probably can fit a medium-sized helicopter), unlike other Moudge-class ships.
![image](https://user-images.githubusercontent.com/122736922/219033311-b2c3ce35-44df-445e-8736-8a2057c6fd45.png)

- It probably also have EO system as seen on IRIS Sahand.
![image](https://user-images.githubusercontent.com/122736922/219035516-f49078ff-d30f-4a9a-b2c2-d97ad1cc261b.png)

### Sources

- http://www.hisutton.com/Iranian-Navy-Accident-Talayieh.html
- https://www.thedrive.com/the-war-zone/43400/irans-newest-warship-has-fallen-on-its-side-in-a-dry-dock
- https://www.youtube.com/watch?v=Vz8l3UikCZc
- https://en.wikipedia.org/wiki/Moudge-class_frigate#:~:text=Iranian%20Navy%20commissioned%20%22Dena%22%20with,%2D2%20anti%2Daircraft%20missiles.

**Comment by PygmalionOfCyprus** [comment]
Added 501 as a hypothetical entry (not necessarily because I don't believe the ship will eventually be commissioned, just b/c its final fit, etc. is not clear).
