### ISSUE TITLE
Add Hughes MD500D to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3037]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2907

### Hypothetical

No

### Name

Hughes MD500D

### Country

Finland

### Service

Army

### In Commission

2008-Present

### Number in Service

3

### Sensors

Night Vision Goggles

### Mounts

Nones

### Loadout Options

None

### Sources

https://puolustusvoimat.fi/en/equipment#/asset/view/id/235

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
