### ISSUE TITLE
Add Hughes MD500E to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3038]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5558

### Hypothetical

No

### Name

Hughes MD500E

### Country

Finland

### Service

Army

### In Commission

1975-Present

### Number in Service

4

### Sensors

Add Night Vision Goggles

### Mounts

Remove all armament

### Loadout Options

None

### Sources

https://puolustusvoimat.fi/en/equipment#/asset/view/id/235

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
