### ISSUE TITLE
Add Remus 100 UUV to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3039]
### DB Selector

DB3K

### DBID to Copy

Submarine 696

### Hypothetical

No

### Name

Remus 100 UUV

### Country

Finland

### Service

Navy

### In Commission

2012-Present

### Number in Service

3

### Sources

https://en.wikipedia.org/wiki/REMUS_(AUV)
https://en.wikipedia.org/wiki/Katanp%C3%A4%C3%A4-class_mine_countermeasure_vessel

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
