### ISSUE TITLE
Add Kongsberg Hugin AUV

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3040]
### DB Selector

DB3K

### Baseline

Submarine 582

### Hypothetical

No

### Name

Kongsberg Hugin-1000 AUV

### Class

Kongsberg Hugin-1000 AUV

### Country

Finland, Norway among others

### Service

Navy

### In Commission

2012-Present

### Length (m)

5.2

### Beam (m)

0.75

### Draft (m)

0.5

### Standard Displacement (t)

1

### Submerged Displacement (t)

1.55

### Empty Displacement (t)

1

### Max Depth (m)

6000

### Complement

0, AUV

### Primary Propulsion Type

Electric (UUVs)

### Propulsion

1-2x 24 kWh Lithium Polymer Batteries

### Flank Speed at Surface (kt)

6

### Flank Speed Submerged (kt)

6

### Range (nm) at Speed (kt)

400nm @ 4kn

### Range (nm) on AIP

400

### Sensors

HISAS (High Resolution Iterferometric Synthetic Aperture Sonar)
EM2040 Multibeam Echosounder
Sidescan sonar
Sub-bottom profiler
Still image camera

### Mounts

None

### Magazines

None

### Comms/Datalinks

cNODE acoustic command and data link
Wi-Fi
Iridium SATCOM
UHF Secure

### sub Codes

Lithium-Ion Batteries

### Sources

https://www.kongsberg.com/maritime/products/marine-robotics/autonomous-underwater-vehicles/AUV-hugin/
https://www.kongsberg.com/globalassets/maritime/km-products/product-documents/hugin-product-specification
https://puolustusvoimat.fi/en/equipment#/asset/view/id/321
https://commons.wikimedia.org/wiki/File:Katanp%C3%A4%C3%A4_Hugin_1000_Merivoimien_vuosip%C3%A4iv%C3%A4_2014_01.JPG

**Comment by PygmalionOfCyprus** [comment]
Handled 499.
