### ISSUE TITLE
Update sensors for MHC Katanpää, Ship #3012

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3041]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3012

### Summary of Changes

The MHC Katanpää class needs some fixes.

-The Gun director is the Atlas MSP-500 IR/EO/Laser turret, Sensor 3548
-The Docking facilities should support 2x UUV (Kongsberg Hugin and Remus 100) + 2x ROV (Seafox I and SAAB Double Eagle)
-There should be an added crane and dock for a 7m RHIB
-All mine sweeps should be removed, as the class does not use those and destroyes found mines either by ROV or diverplaced explosive charges

.Also, it has got five different kinds of sonars, not one as currently is logged

1x The EM 710 (Sensor 5774) hull sonar is correct, but in addition these are also mounted:

1x Klein 5500 Towed Side Scan Sonar (Sensor 5787)
1x Atlas HMS-12M Integrated Mine Countermeasures System (Sensor 5263) 
1x Kongsberg TOPAS Topographic Sedimentary Sonar
1x Kongsberg HiPAP High precision acoustic positioning system

### Sources

https://puolustusvoimat.fi/en/equipment#/asset/view/id/321
https://www.rannikonpuolustaja.fi/archive/2009_4.pdf (Pages 12-18)

**Comment by PygmalionOfCyprus** [comment]
Handled 499. I didn't add either TOPAS or HiPAP since those are kind of out of scope for _Command_.
