### ISSUE TITLE
Add Rh 202 Zwillingsflak To Germany 

### ISSUE THREAD

**Issue by Walshe42** [PygmalionOfCyprus/cmo-db-requests#3042]
### DB Selector

DB3K

### DBID to Copy

AAA 1790 

### Hypothetical

No

### Name

Rh 202 Zwillingsflak , Feldkanone FK 20-2  

### Country

GDR Germany 

### Service

Luftwaffe and Bunderwehr

### In Commission

1972-1992

### Number in Service

1015

### Other Changes

The base unit in the Luftwaffe was (16x Flak 20mm Zw) per Flugabwehrkanonenbatterie 

### Sources

The Rh 202 was used by the Luftwaffe from 1972 to 1992 as a twin anti-aircraft gun LAAG for active airfield and property protection. The Jägertruppe, the pioneers, the artillery, the army aviation troop as well as supply and repair troops used the Rh 202 as FK 20-2 on a field carriage for both ground combat and anti-aircraft defense. During troop testing, the field gun was also loaded onto the loading area of ​​a Unimog. 

https://en.wikipedia.org/wiki/Rheinmetall_Mk_20_Rh-202
https://de.wikipedia.org/wiki/Rh_202
https://www.relikte.com/_basis/docs/bw_3-4.pdf 

Artillery of the world - Christopher F.Foss (Ian Allan Ltd) ISBN 0711005052

**Comment by PavelNovak79** [comment]
User country should be West Germany (BRD) not East Germany (GDR alias DDR).

**Comment by PygmalionOfCyprus** [comment]
In the future please precede your "DBID to Copy" with a proper annex name (e.g. "Facility") so that the auto-labeler can parse it correctly.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
