### ISSUE TITLE
JY-27A Corrections

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3045]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3419, 3420, 3607, Sensor 6572

### Summary of Changes

Remove Wide Mat Designation. The JY-27 is side but the JY-27A is tall (and NATO doesn't appear to have a designation yet). Pedantic yup but confusion exists IRL.
Increase the Facility mast height to 20m-this matters.  (see link below)
Sensor flags: Maybe brilliant but definitely IFF Side Info

### Sources

https://apps.dtic.mil/sti/pdfs/AD1128253.pdf  pg5

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
