### ISSUE TITLE
Protivnik GE Dimension Corrections

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3046]
### DB Selector

DB3K

### Affected DBID(s)

2257, 3149, 3608

### Summary of Changes

Mast height should be 12m. 60m (120 ft) is much taller than pictures (likely copy over stuff)
Facility itself is tractor-trailer (8m length, 5.5 meter width (the array is 5.5 should use this).

### Sources

https://defence-blog.com/egypt-received-new-protivnik-ge-3d-surveillance-radar/

**Comment by bostonmyk** [comment]
The Nebo M-D (1847)and Nebo M-RLM-S (1848) mast heights should be corrected down from 60m as well (probably close to 12m above

**Comment by bostonmyk** [comment]
Cheese Boards have a high mast height as well.

**Comment by PygmalionOfCyprus** [comment]
Please precede the "Affected DBID(s)" with an annex name going forward so the auto-labeler can parse it. 🙂

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
