### ISSUE TITLE
Add Kuha class MLU minesweepers to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3048]
### DB Selector

DB3K

### Baseline

Ship 2917

### Hypothetical

No

### Name

Kuha 21-26

### Class

Kuha class

### Country

Finland

### Service

Navy

### In Commission

1998-Present

### Number in Service

6, 2 scrapped in 2012

### Length (m)

32

### Beam (m)

7

### Draft (m)

2

### Standard Displacement (t)

127

### Full Displacement (t)

150

### Complement

14

### Max Sea State

5

### Primary Propulsion Type

Diesel

### Propulsion

2x Cummins NT-380M diesel (600 hp in total) with hydrostatic transmission to one shaft and two controllable pitch propellers

### Fuel Capacity (kg)

3000

### Flank Speed (kt)

12

### Range (nm) at Speed (kt)

450 nm @ 10 kt

### Sensors

Decca Racal (Sensor 1480) 
Reson Seabat 6012 (Sensor 4661)
Generic Mine Hunting Sonar (Sensor 5701, in reality a Patria SONAC HF)
Generic Magnetic and Acoustic Mine Swep (Sensor 4654)
Generic Mechanical Cutter Mine Sweep (Sensor 4657)

### Mounts

1x ZU-23-3 (Weapon 357) mounted towards the stern, arc 2-10
1x 12.7mm/50 MG (Weapon 1695), in the bow, arc 9-3

### Comms/Datalinks

VHF Secure
UHF Secure

### Ship Codes

Advanced Quieting, Glass Reinforced Polyester (GRP) Construction

### Comments

The ships were buil in the 70's and completely rebuilt 10 meters longer in the late 90's.

The ships were built with very hight emphasis on being quiet and anti-magnetic. The hull is made out of fibre-glass plastic and there is no propeller shaft as the two propellers are 360 degree pods powered by hydraulics. In addition the engine room is built on the deck above the water line as a separate block on rubber dampeners to minimize acoustic signals.

Before the MLU the main mine countermeasures were cutter sweeps and divers, but after the diver equipment was removed and the ships given new acoustic and magnetic sweeps, along with a digital sweeping control system.

According to the English Wiki they should have been deactivated after 2012, but due to delays of the Katanpää class and the deteriorated securiy situation in the Baltic Sea  4 of 6 have been preserved and are still active.

### Sources

https://puolustusvoimat.fi/en/equipment#/asset/view/id/323
https://en.wikipedia.org/wiki/Kuha-class_minesweeper_(1974)#cite_note-FOOTNOTEWertheim2013188-2

**Comment by Jkryos** [comment]
Added DB3K 507.
