### ISSUE TITLE
Add Pilatus PC-12 to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3052]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5365

### Hypothetical

No

### Name

Pilatus PC-12 NG

### Country

Finalnd

### Service

Air Force

### In Commission

2009-Present

### Number in Service

6

### Sources

https://puolustusvoimat.fi/en/equipment#/asset/view/id/206

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
