### ISSUE TITLE
Add Leopard 2A6 to Finnish Army

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3054]
### DB Selector

DB3K

### DBID to Copy

Facility 2381

### Hypothetical

No

### Name

Armored Plt (Leopard 2A6 MBT x4)

### Country

Finland

### Service

Army

### In Commission

2014-Present

### Sources

https://puolustusvoimat.fi/kalusto#/asset/view/id/242

The Finnish tanks were, as the Canadian, purchased used from the Netherlands, but Finland purchased five times more than Canada (100 vs 20)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
