### ISSUE TITLE
Add datalink on Spyder batteries or associated radars (EL/M-2084 MMR) to guide Derby

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3056]
### DB Selector

DB3K

### Affected DBID(s)

All Derby capabile Spyders, All ELM-2084s

### Summary of Changes

Derby can't be fired without data link to EL/M-2084 MMR. Need to add datalink to all radars so it can be. Doubt ATARS units have capability.

### Sources

Attached Files
[kalibre test-Derbynodatalink.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10777212/kalibre.test-Derbynodatalink.zip)

**Comment by Jkryos** [comment]
Fixed DB3K 503.
