### ISSUE TITLE
CAMM, Sceptor missiles should all be capable against high speed supersonic missiles

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3057]
### DB Selector

DB3K

### Affected DBID(s)

2783, 4019, 3735

### Description of Problem

CAMM can't engage high-speed missiles (Krypton, Kickback) due to a low-speed limitation. 

See file
[kickback-kryptontestvsCeaandLandSceptor.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10777612/kickback-kryptontestvsCeaandLandSceptor.zip)
high-speed

### Recommended Fix

Raise Target speed to Mach 3. 

https://www.seaforces.org/wpnsys/SURFACE/Sea-Ceptor-CAMM.htm#:~:text=CAMM%20is%20a%20point%20defence,and%20other%20high%2Dperformance%20targets.
https://www.mbda-systems.com/product/camm/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
