### ISSUE TITLE
IRIS-T should be capable against high speed supersonic missiles

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3058]
### DB Selector

DB3K

### Affected DBID(s)

4041

### Description of Problem

IRIS-T has too low of a legal target speed to hit supersonic missiles. It should be able too.
[IRIS-Tkickbacktest and Krypton.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10777658/IRIS-Tkickbacktest.and.Krypton.zip)

### Recommended Fix

Increase the target speed to Mach 3.

https://en.wikipedia.org/wiki/IRIS-T
https://www.armyrecognition.com/germany_missile_systems_vehicles_uk/iris-t_slm_medium-range_air_defense_missile_system_technical_data

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
