### ISSUE TITLE
Reduce KM-SAM Block 2 2nm minimum range- Can't defend

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3059]
### DB Selector

DB3K

### Affected DBID(s)

3423

### Summary of Changes

Minimum range of 2nm might be a typo. Reduce to 1nm.

### Sources

Want to test this fire against a KH-101. You'll get a detection 5nm out and then won't be able to fire because OODA puts it within 2nm.

[KH-101-KNSAM test.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10778257/KH-101-KNSAM.test.zip)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
