### ISSUE TITLE
Italian sonar Wass Atas wrong type

### ISSUE THREAD

**Issue by Tobias02** [PygmalionOfCyprus/cmo-db-requests#3060]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6308

### Summary of Changes

The Italian Wass Atas sonar is considered in game as a towed array (TASS), while in reality it is a Variable depth sonar (VDS), I think.
Thanks!
[BROCHURE_2018_Scheda_ATAS 2018.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10786166/BROCHURE_2018_Scheda_ATAS.2018.pdf)

### Sources

https://electronics.leonardo.co
![original_ATAS_R](https://user-images.githubusercontent.com/125903334/220157503-05a60b2d-c279-4162-a78f-d9b274b26a83.jpg)
[BROCHURE_2018_Scheda_ATAS 2018.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/10786119/BROCHURE_2018_Scheda_ATAS.2018.pdf)
m/en/products/atas

**Comment by PygmalionOfCyprus** [comment]
Handled 500. I love how they called a VDS the "Active Towed Array Sonar"... 🙃
