### ISSUE TITLE
Iron Dome cannot engage rockets

### ISSUE THREAD

**Issue by fmachanda** [PygmalionOfCyprus/cmo-db-requests#3063]
### DB Selector

DB3K

### Affected DBID(s)

Facility 2607, 3652

### Summary of Changes

Iron Dome units should be able to shoot down rockets (eg., Palestinian Fajr-5 or Qassam 4 rockets)

### Sources

https://en.wikipedia.org/wiki/Iron_Dome
https://www.timesofisrael.com/rocket-fired-from-gaza-at-southern-israel-intercepted-by-iron-dome/
https://www.jns.org/irone-dome-intercepts-one-rocket-fired-from-gaza-at-israel/

**Comment by PygmalionOfCyprus** [comment]
This is not so much a DB error as a larger issue with how the sim currently handles rockets, etc. Closing ticket since I can't do anything about it DB-side but rest assured we are aware of this.
