### ISSUE TITLE
LPD-29 Richard M. McCool Jr. will be first Blk I San Antonio to get Spy-6(V2)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3064]
### DB Selector

DB3K

### Affected DBID(s)

2599

### Summary of Changes

Add sensor fits similar to Flight II Harrisburg #3230. IOC 2024. Cool huh!

### Sources

https://twitter.com/surflant/status/1626401046716383232?cxt=HHwWgIDUvdHIkZItAAAA
https://twitter.com/DrDmitryShulgin/status/1625609432456474624

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
