### ISSUE TITLE
Add reclassed Absalon class as frigates.

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3065]
### DB Selector

DB3K

### DBID to Copy

Ship 800

### Hypothetical

No

### Name

F341 Absalon

### Country

Denmark

### Service

Navy

### In Commission

2020-2026

### Number in Service

2

### Sensors

Replace Scanter 2001 (Sensor 2615) with Scanter 6002 (Sensor 5652)

### Other Changes

The ships were reclassified as frigates in 2020.

### Sources

https://en.wikipedia.org/wiki/Absalon-class_frigate
https://web.archive.org/web/20201026170031/https://www.dr.dk/nyheder/politik/med-malerpensler-har-soevaernet-slettet-et-20-aar-gammelt-underligt-ord

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
