### ISSUE TITLE
Add Absalon class as ASW frigates

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3066]
### DB Selector

DB3K

### DBID to Copy

Ship 800

### Hypothetical

No

### Name

F341 Absalon

### Country

Denmark

### Service

Navy

### In Commission

2026-

### Number in Service

2

### Sensors

Change Scanter 2001 to Scanter 6002 (Sensor 5652)
Add VDS/TAS

### Sources

https://www.mercell.com/en/tender/141455310/towed-array-sonar-tas-for-the-royal-danish-navy-tender.aspx

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
