### ISSUE TITLE
Add ASW weapons for Danish MH-60R Seahwak

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3067]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4553

### Hypothetical

No

### Name

MH-60R Seahawk

### Country

Denmark

### Service

Navy

### In Commission

2023

### Number in Service

9

### Sensors

Add AN/AQS-22 ALFS (Sensor 625)

### Mounts

Add Mk 54 Lightweigh Hybrid Torpedo (Weapon 902)
Add AN/SSQ-36/53/62 sonobuoys (Weapons  2475, 4094, 4124)

### Loadout Options

Similar to USN and RAAN loadouts.

### Sources

https://defbrief.com/2020/04/06/denmark-orders-low-frequency-sonars-sonobuoys-for-seahawk-fleet/
https://www.facebook.com/FMI/posts/sonarer-og-torpedoer-til-seahawk-helikopterne-som-et-led-i-forsvarets-evne-til-a/2627626564126055/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
