### ISSUE TITLE
AIM-120C-7 should have longer range than AIM-120C-5

### ISSUE THREAD

**Issue by Swaant** [PygmalionOfCyprus/cmo-db-requests#3068]
### DB Selector

DB3K

### Affected DBID(s)

#718  AIM-120C-7

### Summary of Changes

Currently the AIM-120C-7 has the same range as the AIM-120C-5, but one improvement is a bigger engine bay.

### Sources

https://en.missilery.info/missile/aim120

'In 2004, a more advanced modification of the AMRAAM missile - AIM-120C-7 (P3I-3) was created. It received new software that further improves the resolution and interference immunity of the WGSN. The use of a more modern and compact element base made it possible to once again increase the length of the engine bay. The improved RGSN and the power plant provide an increase in the range of the upgraded missile up to 120 km'

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
