### ISSUE TITLE
Add Pansio class minelayer MLU for Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3070]
### DB Selector

DB3K

### DBID to Copy

Ship 3013

### Hypothetical

No

### Name

MLI Pansio

### Country

Finland

### Service

Navy

### In Commission

2016-Present

### Number in Service

3

### Sensors

Replace Generic Surface Search Radar with Furuno FAR-2117 (Sensor 6514)
Add Generic TV Camera Weapon Director (Sensor 4604), arc 7-5
Add Generic IR Camera Weapon Director (Sensor 4618), arc 7-5
Add Generic Laser Range Finder for Gun Director (Sensor 4231), arc 7-5

### Mounts

Remove both ZU-23-2
Add another manual 12.7mm/50 MG, one on each bridge wing. Port side with fire arc 8-1, starboard side arc 11-4.
Add RWS with 40mm H&K GMG + co-ax. 7.62mm MG and above gun directors, arc 7-5
Replace mine magazine (moored) with mine magazine (bottom mine) with 50x PM04

### Other Changes

2 x 880 hp Diesel engines
Secure UHF and VHF radios
SATCOM

Also, the ships are built from steel not GRP as they are mine layers, not magnetically sensitive mine-sweepers.
The ships are ro-ro capable for transporting 100 tons of goods or 200 troops.

### Sources

https://puolustusvoimat.fi/en/equipment#/asset/view/id/325
https://www.naval-technology.com/news/atlas-completes-mid-life-refit-finlands-pansio-class-ships/
https://www.furuno.fi/fin/viranomaisalukset/ratkaisut/case_study_pansio_luokan_retrofit/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
