### ISSUE TITLE
Update: China, LXUUV, weapon and battery issue

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3071]
### DB Selector

DB3K

### Affected DBID(s)

submarine 733

### Summary of Changes

1. Add 4x 533mm torpedo tubes. (able to carry Yu-7/Yu-10, 1x/tube)
2. Change battery endurance to 3500 hrs at creep throttle. (this is an Orca-XLUUV size AUV, 100 hrs endurance presently must be bug again)
3. Standard displacement change to 45t, Full change to 55t. (reasonable speculation)

### Sources

https://www.navalnews.com/event-news/navdex-2023/2023/02/china-reveals-new-heavily-armed-extra-large-uncrewed-submarine/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
