### ISSUE TITLE
Cargo Issue - Airbus A.330-200 MRTT [KC-30] - Brazil  

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3072]
### DB Selector

DB3K

### Affected DBID(s)

DB3K Aircraft 6065

### Summary of Changes

Airbus A.330-200 MRTT [KC-30] - Brazil cannot carry cargo with its cargo loadouts.

### Sources

DB 498a

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
