### ISSUE TITLE
Cargo Issue - USMC Skyknight Air Drop

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3073]
### DB Selector

CWDB

### Affected DBID(s)

CWDB Aircraft 453, 2226, 2227, 2224, 2228 

### Summary of Changes

Aircraft with spec ops airdrop loadout cannot load a paratrooper. 

### Sources

DB 498

**Comment by PygmalionOfCyprus** [comment]
Handled 500. Removed AAR capability.
