### ISSUE TITLE
Cargo Issue - R3Y-2 Tradewind

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3074]
### DB Selector

CWDB

### Affected DBID(s)

CWDB Aircraft 4191

### Summary of Changes

R3Y-2 Tradewind 103x PAX loadout has same cargo capacity limits as R3Y-1 80x PAX loadout.

### Sources

DB 498

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
