### ISSUE TITLE
Iran - Mi-17 helicopters with Maham-II mines

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3075]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 4843

### Summary of Changes

New Loadout

Minelaying - 2x Maham-II mines

### Sources

https://navyrecognition.com/index.php/naval-news/naval-news-archive/2023/february/12835-iran-navy-equips-its-mil-mi-17-helicopters-with-maham-ii-mines.html?fbclid=IwAR1PVCEGjnGukCufWX2jmHxwhRboemyb7ae-jaGr4jYEEGO4F71z22F4gjw
https://www.presstv.ir/Detail/2023/02/15/698275/Iran%C3%A2%E2%82%AC%E2%84%A2s-IRGC-Navy-furnishes-its-helicopters-with-locally-developed-naval-mines
https://www.globalsecurity.org/wmd/library/news/iran/2023/iran-230215-presstv02.htm
https://news.am/eng/news/745007.html

![image](https://user-images.githubusercontent.com/99599482/221197150-c13061c4-ce57-4bbe-9672-6d845230beac.png)

**Comment by bostonmyk** [comment]
Here's a stat sheet on the Maham II mine 

https://twitter.com/imp_navigator/status/1606199558572109825/photo/3

**Comment by PygmalionOfCyprus** [comment]
Handled 500. And added all of the Maham family of mines for Iran.
