### ISSUE TITLE
United Kingdom - Peregrine [Camcopter S-100] UAV 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3076]
### DB Selector

DB3K

### DBID to Copy

aircraft 3445

### Hypothetical

No

### Name

Peregrine [Camcopter S-100] UAV 

### Country

United Kingdom

### Service

Royal Navy, HM Coast Guard

### In Commission

2024-

### Number in Service

uncertain

### Sensors

Add

I-Master radar

### Mounts

N/A

### Loadout Options

- Sonobuou datalink Pod for ASW
- Radar Recon with I-Master
- Tested with PT-8 Oceanwatch similar to Icelandic/Romanian models. 

### Sources

https://www.navylookout.com/peregrine-rotary-wing-uav-to-enter-service-with-the-royal-navy/?fbclid=IwAR3lT2sbI9EOJrslZC-RgQMaN2g9DbUvlOItVQuyhjmDg9HrLDY7IwV9n-c
https://www.navalnews.com/naval-news/2023/02/thales-and-schiebel-win-royal-navy-peregrine-competition-with-s-100/
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/october/12391-royal-navy-successfully-operates-schiebel-camcopter-s-100-uas-during-nato-exercise.html
https://www.defenseadvancement.com/news/royal-navy-ships-to-deploy-camcopter-s-100-surveillance-drone/
https://www.thedefensepost.com/2023/02/13/uk-navy-drone-helicopter/
https://www.unmannedsystemstechnology.com/2023/02/camcopter-s-100-supports-royal-navy-ships-on-operational-tasks/
https://defbrief.com/2023/02/10/schiebel-lands-deal-to-supply-camcopter-s-100-uas-for-royal-navys-peregrine-program/
https://www.navalnews.com/naval-news/2022/08/bristow-to-provide-schiebel-camcopter-uas-capability-to-uksar2g/?fbclid=IwAR3p51e7FgMW9zqQ4S0UbqDIAdoQvsLxx8c6ia2JUeneXdEqirbmYVrH-mI
https://www.navalnews.com/naval-news/2022/10/camcopter-s-100-relays-sonobuoy-data-during-nato-exercise/?fbclid=IwAR0FJIHpQcS6NZT-oa1mvZSMhmfihk1fK5DnTpHUJOmKPf4rSbU24KdSWNU

![image](https://user-images.githubusercontent.com/99599482/221200670-4debd5e4-1b70-4927-890c-1039cf6c9b70.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
