### ISSUE TITLE
Yemen - BILQIS [Pr.NS-722, Improved Polnochny} medium landing ship (2002)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3081]
### DB Selector

DB3K

### Baseline

ship 2191

### Hypothetical

No

### Name

BILQIS medium landing ship

### Class

Polish project NS-722 medium landing ship

### Country

Yemen

### Service

Navy

### In Commission

2002-2016

### Number in Service

1x

### Length (m)

88.6

### Beam (m)

9.90

### Draft (m)

2.36

### Standard Displacement (t)

1150

### Full Displacement (t)

1410

### Empty Displacement (t)

Not Stated

### Complement

49

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3516B diesels

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

17

### Range (nm) at Speed (kt)

3600 @ 12

### Sensors

surf. search, nav. radars, ORLO, Sarmat-1 e/o systems,

### Mounts

2 x 4 Fasta-4M SAM (16 2M32M Strela-2M), 
1 x 6 - 30/54 AK-630, 
1 x 2 - 23/87 ZU-23-2 Wrobel-1, 
2 x 1 - 12.7/79, 
2 x 20 - 122 WM-122/20 RL,
Jastrzab-2 decoy RL

### Aircraft & Docking Facilities

11.7x9.8 helicopter deck can receive AB-205 helicopter.

Military load | 5 tanks, 111 troops or 290 t cargo

### Comms/Datalinks

VHF/UHF

### Comments

Polish project NS-722 medium landing ship. Developed for India but not purchased. Intended for use as cadet training ship and for disaster relief in addition to amphibious warfare role. 11.7x9.8 helicopter deck can receive AB-205 helicopter.

### Sources

http://navypedia.org/ships/yemen_south/yes_ls_bilqis.htm
https://en.wikipedia.org/wiki/Polnocny-class_landing_ship
https://warsearcher.com/shipsearcher/small-navies-of-the-world-great-ships/small-navies-of-the-world-landing-ships/
http://warshipsresearch.blogspot.com/2015/05/yemen-medium-landing-ship-lsm-bilqis.html
http://www.shipbucket.com/drawings/512

![image](https://user-images.githubusercontent.com/99599482/221215400-24d2a7e1-e312-4d61-8b62-39cabd8bbf2b.png)

**Comment by tbrandon517** [comment]
Added for unified Yemen in DB3K 499,

**Comment by tbrandon517** [comment]
Can the unit be updated with the helipad?

**Comment by PygmalionOfCyprus** [comment]
Helipad added 505.
