### ISSUE TITLE
Yemen - JIBLA [Ham Class] inshore minesweepers (1967)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3082]
### DB Selector

CWDB

### DBID to Copy

cwdb ship 1753 and db3k ship 3378

### Hypothetical

No

### Name

JIBLA  [Ham Class] inshore minesweeper

### Country

Yemen

### Service

Navy

### In Commission

1968-1984

### Number in Service

3x

### Sensors

type 978 radar

### Mounts

1 x 1 - 20mm/70 Mk 7, 
LL magnetic/acoustic/mechanical minesweeping gear

### Loadout Options

N/A

### Other Changes

For both CWDB and DB3K

### Sources

http://navypedia.org/ships/yemen_south/yes_ls_jihla.htm

![image](https://user-images.githubusercontent.com/99599482/221217752-92c8c29c-4f58-4d36-91e3-0ff964c3a847.png)

**Comment by Jkryos** [comment]
Added CWDB 500.
