### ISSUE TITLE
Yemen - No 111 [Pr.183] fast attack craft (torpedo)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3083]
### DB Selector

DB3K

### DBID to Copy

DB3K ship 245

### Hypothetical

No

### Name

111 [Pr.183]

### Country

Yemen

### Service

Navy

### In Commission

1966-1984

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Unit already in Yemen CWDB.

### Sources

http://navypedia.org/ships/yemen_south/yes_cf_111.htm

**Comment by Jkryos** [comment]
Added DB3K 507.
