### ISSUE TITLE
Yemen - No134 [Soviet Project T-4] tank landing craft

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3085]
### DB Selector

CWDB

### DBID to Copy

CWDB ship 2607

### Hypothetical

No

### Name

No134 [Soviet Project T-4] tank landing craft

### Country

Yemen

### Service

Navy

### In Commission

1970-2005

### Number in Service

3x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

N/A

### Other Changes

For CWDB and DB3K

### Sources

http://navypedia.org/ships/yemen_south/yes_ls_t4.htm
http://navypedia.org/ships/yemen_north/yen_ls_t4.htm

**Comment by PygmalionOfCyprus** [comment]
Added for unified Yemen in DB3K 499, but keeping the ticket open for when we do the split Yemens.
