### ISSUE TITLE
Yemen - No139 [Pr.775] tank landing ship (1979)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3086]
### DB Selector

CWDB

### DBID to Copy

CWDB ship 715 and DB3K ship 136

### Hypothetical

No

### Name

No139 [Pr.775] tank landing ship

### Country

Yemen

### Service

Navy

### In Commission

1979-2002

### Number in Service

1x

### Sensors

MR-302 Rubka, Don or Mius, MR-103 Bars radars

### Mounts

2 x 2 - 57mm/50 AK-725

### Loadout Options

N/A

### Other Changes

No SAMs

### Sources

http://navypedia.org/ships/yemen_south/yes_ls_139.htm
https://en.wikipedia.org/wiki/Ropucha-class_landing_ship

**Comment by tbrandon517** [comment]
Added for unified Yemen in DB3K 499, keeping open for split Yemens.

**Comment by Jkryos** [comment]
Added CWDB 500.
