### ISSUE TITLE
Yemen - pr. 123K fast attack craft (torpedo) 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3089]
### DB Selector

DB3K

### DBID to Copy

DB3K ship 247 and CWDB ship 2092

### Hypothetical

No

### Name

P-4 pr. 123K fast attack craft

### Country

Yemen

### Service

Navy

### In Commission

1966-1984

### Number in Service

4x

### Sensors

No Changes

### Mounts

1 x 2 - 14.5mm/89, 
2 x 1 - 450mm TT, 
6 DC

### Loadout Options

N/A

### Other Changes

For both CWDB and DB3K

### Sources

http://navypedia.org/ships/yemen_north/yen_cf_123k.htm

**Comment by Jkryos** [comment]
Added DB3K 507.
