### ISSUE TITLE
Yemen - pr. 1400E patrol boats (1975)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3090]
### DB Selector

CWDB

### DBID to Copy

DB3K ship 3749 and CWDB ship 2773

### Hypothetical

No

### Name

pr. 1400E Zhuk patrol boats

### Country

Yemen

### Service

Navy

### In Commission

1975-1990

### Number in Service

2x

### Sensors

Lotsiya or Liman or MR-241 Pechora-1 radar

### Mounts

1 x 2 - 12.7mm/79

### Loadout Options

N/A

### Other Changes

For both CWDB and DB3K

### Sources

http://navypedia.org/ships/yemen_north/yen_cf_1400e.htm

**Comment by Jkryos** [comment]
Added CWDB 500.
