### ISSUE TITLE
Yemen - pr. 1400ME Zhuk patrol boats

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3091]
### DB Selector

CWDB

### DBID to Copy

DB3k ship 3749 and CWDB ship 2773

### Hypothetical

No

### Name

pr. 1400ME Zhuk patrol boats

### Country

Yemen

### Service

Navy

### In Commission

1978-2008

### Number in Service

9x Total (4x 1978, 2x 1984, 3x 1987)

### Sensors

Lotsiya radar

### Mounts

2 x 2 - 12.7mm/79

### Loadout Options

N/A

### Other Changes

For both CWDB and DB3K

### Sources

http://navypedia.org/ships/yemen_south/yes_cf_1400.htm

![image](https://user-images.githubusercontent.com/99599482/221231434-c81cf04d-f888-4e5b-9acd-e40b49ac6f68.png)

**Comment by PygmalionOfCyprus** [comment]
Added for unified Yemen in DB3K 499, keeping open for split Yemens.

**Comment by Jkryos** [comment]
Added DB3K 500.

**Comment by Jkryos** [comment]
Added CWDB 500.
