### ISSUE TITLE
Yemen - pr. 201M patrol craft

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3092]
### DB Selector

DB3K

### DBID to Copy

CWDB ship 1828 (or best DB3k equivalent for Pr.201M) 

### Hypothetical

No

### Name

pr. 201M patrol craft

### Country

Yemen

### Service

Navy

### In Commission

1972-1982

### Number in Service

2x

### Sensors

Reya radar, Tamir-11 sonar

### Mounts

2 x 2 - 25mm/82 2M-3M, 
4 x 5 RBU-1200 Uragan ASWRL, 
2 DCR (24 DC) or 18 mines

### Loadout Options

N/A

### Sources

http://navypedia.org/ships/yemen_south/yes_cf_201.htm

**Comment by Jkryos** [comment]
Added DB3K 507.
