### ISSUE TITLE
USAF - E-9A Widget [Dash-8-100]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3094]
### DB Selector

DB3K

### DBID to Copy

aircraft 4340

### Hypothetical

Yes

### Name

E-9A Widget [Dash-8-100]

### Country

United States

### Service

Air Force

### In Commission

1988-present

### Number in Service

2x

### Sensors

1x AN/APS-143(V) -1
1x Telemetry/Tracking Array

### Mounts

None

### Loadout Options

- airborne ocean surface surveillance

### Other Changes

2x Pratt & Whitney PW-120A turboprop engines 

### Sources

https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104559/e-9a/
https://www.military.com/equipment/e-9-widget
https://militarymachine.com/e-9a-widget/
https://www.airandspaceforces.com/weapons-platforms/e-9a/
https://www.tyndall.af.mil/News/Features/Display/Article/669737/e-9a-widget-one-of-a-kind/
https://www.globalsecurity.org/military/systems/aircraft/e-9.htm
https://en.wikipedia.org/wiki/De_Havilland_Canada_Dash_8

![image](https://user-images.githubusercontent.com/99599482/221238670-b3b714d7-5e49-4f22-a742-de0dbe9d99af.png)
![image](https://user-images.githubusercontent.com/99599482/221238726-c4374da2-af13-4b82-aafb-e14acebfa403.png)
![image](https://user-images.githubusercontent.com/99599482/221238900-16c7d77e-7487-4179-a3f7-92525d64b8a8.png)
![image](https://user-images.githubusercontent.com/99599482/221239167-6fdb96c9-ec69-4f67-9a8d-f7d6a11977df.png)

**Comment by tbrandon517** [comment]
Not Hypo, checked yes in error.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
