### ISSUE TITLE
Update/Clarification - FM 01 Presidente Eloy Alfaro [Type 12I Leander Batch 2] - 1992

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3095]
### DB Selector

DB3K

### Affected DBID(s)

ship 72 and ship 728

### Summary of Changes

These two ships Presidente Eloy Alfaro FM01 (ex-Penelope F127) and Morán Valverde FM02 (ex-Danae F47) were Former RN Leander class frigates, acquired as replacements for former USN destroyer and destroyer escort. The Ships were transferred without Seacat and Exocet missiles (empty launchers), Exocets were transferred later (but no Seacat missiles). Active from 1991-2008 and were replaced by ex-Chilean Leanders with the same names and pennants (will submit new request). Recommend updating name to add (ex-Penelope) for clarification. 

Update in service and OOS date to 1991 and 2008. 

2001, both: 
remove 2 x 4 Sea Cat SAM, type 993, 2x type 904 radars, US-8/9 ECM suite, CAAIS CCS; 
add 3 x 2 Simbad SAM (36 Mistral), 2 x 2 - 20mm/70 Mk 12, 2 x 3 - 324 ILAS-3 TT (A-244S), type 994 radar, NS9010 ECV2 ECM suite, SP100 CCS

### Sources

https://www.navypedia.org/ships/ecuador/ecu_es_presidente_eloy_alfaro91.htm
https://en.wikipedia.org/wiki/HMS_Penelope_(F127)
https://en.wikipedia.org/wiki/HMS_Danae_(F47)

![image](https://user-images.githubusercontent.com/99599482/221244898-86c6e0cc-d4d6-42fb-b440-2388fe15eecf.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
