### ISSUE TITLE
Add 7.62mm Sniper Rifles

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#31]
### DB Selector

DB3K

### Hypothetical

- [ ] Yes

### Name

7.62mm Sniper Rifle Volley [5 rnds]

### Length (m)

0

### Width/Span (m)

0

### Diameter (m)

0

### Weight (kg)

0

### Range (nm)

0.7

### Target Altitude / Depth (ft)

-

### Launch Altitude / Depth (ft)

-

### Warhead

7.62mm Sniper Rifle Volley [5 rnds] (0.1 DP)

### Targets

Land Structure - Soft, Mobile Target - Soft, Mobile Target - Personnel

### CEP (m)

1

### Sensors

1x Mk 1 Eyeball
1x Generic Binoculars 
1x Generic Laser Designator
1x Generic IR Designator 
1x Generic Night Vision Goggles

### Comments

Basically just a direct copy of the 12.7mm Sniper Section entries but with a 7.62mm Sniper Rifle. Some nations do not have 12.7mm Anti-Material Rifles in their inventories (for example, Venezuela). The 7.62mm Burst has similar accuracy but slightly less damage than the 12.7mm, possibly higher rate of fire to a 10 round burst instead of 5 to add some differntiation between it and the 12.7mm.

Can also be included in the CWDB.

### Sources

Doesn't really need sources since it is generic. Here is some sources on Venezuelan sniper inventory however.

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Venezuelan_Army

https://www.nytimes.com/2007/08/16/world/europe/16russia.html?_r=1&oref=slogin

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
