### ISSUE TITLE
United States AFSOC M-8/17 Hip

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3100]
### DB Selector

DB3K

### DBID to Copy

aircraft 5660

### Hypothetical

No

### Name

Mi-8/17 Hip

### Country

United States

### Service

Air Force, Army

### In Commission

2002-2012 (6th Special Operations Squadron)

### Number in Service

uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Sources

https://en.wikipedia.org/wiki/Air_Force_Special_Operations_Command
https://web.archive.org/web/20170902183932/http://www.afsoc.af.mil/About-Us/Fact-Sheets/Display/Article/877958/6th-special-operations-squadron/
https://www.thedrive.com/the-war-zone/42409/russian-made-mi-17-helicopter-flown-by-secretive-u-s-group-lands-in-farmers-field

![image](https://user-images.githubusercontent.com/99599482/221262728-c5e2656c-6165-4f2f-9079-437d403a552a.png)

![image](https://user-images.githubusercontent.com/99599482/221260992-94537cb3-58f5-4e50-b0e4-2a99f7cdb82e.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
