### ISSUE TITLE
United States AFSOC An-26 Curl A

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3101]
### DB Selector

DB3K

### DBID to Copy

aircraft 3127

### Hypothetical

No

### Name

An-26 Curl A

### Country

United States

### Service

Air Force

### In Commission

2003–2007

### Number in Service

uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://en.wikipedia.org/wiki/Air_Force_Special_Operations_Command
https://en.wikipedia.org/wiki/Antonov_An-26
https://web.archive.org/web/20170902183932/http://www.afsoc.af.mil/About-Us/Fact-Sheets/Display/Article/877958/6th-special-operations-squadron/

![image](https://user-images.githubusercontent.com/99599482/221263309-b3e0a975-a77b-4fd9-a1d9-eaebbc61a545.png)
![image](https://user-images.githubusercontent.com/99599482/221263559-40829bd8-3102-4e9e-b78f-06fd641b4a90.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
