### ISSUE TITLE
Hurricane Aircat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3107]
### DB Selector

CWDB

### Baseline

Small Boat

### Hypothetical

No

### Name

Hurricane Aircat

### Class

Airboat

### Country

United States, South Vietnam, SOuth Korea, Cambodia

### Service

US, Vietnam, Korea (Army), Cambodia (Navy)

### In Commission

1964-1972 (1967-1973 - Cambodia)

### Number in Service

84+ (2x Cambodia)

### Length (m)

5.2 m

### Beam (m)

2.21 m

### Draft (m)

0.10 m

### Standard Displacement (t)

520 kg

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

5–6

### Max Sea State

not stated

### Primary Propulsion Type

Gasoline

### Propulsion

180 hp (130 kW) Lycoming O-360 aircraft engine with Fan

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

42–65 knots 

### Range (nm) at Speed (kt)

87 nm

### Sensors

mk 1 Eyeball

### Mounts

1x bow position for 
1x M1919 .30 caliber (7.62 mm) machine gun (bow) 
or
1× M2HB .50 caliber (12.7 mm) machine gun (bow)

Crew small arms, M31 rifle grenades, and/or M79 grenade launchers

The 106mm M40 recoilless rifle was used on airboats “frequently” by the 7th Armored Squadron, 1st Air Cavalry Division , who and “proven very valuable.”

### Aircraft & Docking Facilities

None

### Comms/Datalinks

AN/PRC-25 radio for short-range communication or AN/VRC-12 or [AN/VRC-16

### Ship Codes

Catamaran/Trimaran Multihull, Glass Reinforced Polyester (GRP) Construction, Built to Mercantile Standards

### Comments

Crew + PAX + Cargo up to 910 kg

### Sources

https://en.wikipedia.org/wiki/Hurricane_Aircat

![image](https://user-images.githubusercontent.com/99599482/221282942-c69e2db8-a570-4bae-83de-8a73d7132e07.png)
![image](https://user-images.githubusercontent.com/99599482/221284392-571dc60d-160e-479f-80cc-c9f5a333c74f.png)
![image](https://user-images.githubusercontent.com/99599482/221284477-9801553c-fd21-4596-83ac-8a311b4aacdb.png)
![image](https://user-images.githubusercontent.com/99599482/221284522-9f83f4d4-d244-4b3e-afa3-bbe3974081e2.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 503. Not adding for ROK because as far as I can tell they just "borrowed" US Aircats and often operated them w/ mixed US crews during their ops in Vietnam. Did add for Cambodia and South Vietnam though.
