### ISSUE TITLE
F-35 Agility / Block modifications

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3108]
### DB Selector

DB3K

### Affected DBID(s)

4222, 5705, 5869, 6180, 4699, 4701

### Summary of Changes

F-35A / B Agility changes due to Block 4:

4222, 5705, 5869, 6180 = (F-35As) update to Block 4 standards with 9G capability (CMO Agility 5.0). These aircraft should also be updated with Block 4 avionics as per:
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2905

4699, 4701 = (F-35Bs) Block 4 standards will not increase the 9G capability of the F-35B due to the STOVL lift fan. Therefore downgrade the CMO Agility to 4.5 as to match earlier F-35Bs.

### Sources

https://www.cbc.ca/news/politics/canada-f35-fighter-jet-deal-1.6707769

https://www.airforce.gov.au/aircraft/f-35a-lightning-ii

https://www.af.mil/About-Us/Fact-Sheets/Display/Article/478441/f-35a-lightning-ii/

https://aviationweek.com/defense-space/sensors-electronic-warfare/weekly-debrief-f-35-program-sneaks-major-radar-upgrade

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
