### ISSUE TITLE
Please consider adding KH-15S Loadout to Tu-22M-3 & Tu-22M-3M

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#311]
### DB Selector

DB3K

### User(s)

Tu-22M-3/3M (DBID's: 1669, 1670, 1671, 2438, 2456, 2837, & 4951)

### Weapons Carried

1. Long-Range Loadout: 6x Kh-15S Anti-Ship Missiles in 1x Internal MKU-6-1 Rotary Launcher Pods
2. Short-Range Loadout: 6x Kh-15S Anti-Ship Missiles in 1x Internal MKU-6-1 Rotary Launcher Pods PLUS 4x Kh-15A Anti-Ship Missiles on 2x *External* Under-Wing Pylons

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

1. 1570 nm for Long-Range Loadout
2. Unknown nm for Short-Range Loadout

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

The Kh-15S is not currently part of the database, but a new weapon DB request has been submitted in issue #254 ...

### Sources

1. https://www.weaponsystems.net/system/99-Raduga+Kh-15
2. https://military-history.fandom.com/wiki/Kh-15

**Comment by PygmalionOfCyprus** [comment]
Added w/ #254.
