### ISSUE TITLE
Italian Helicopter SH-101A ASW

### ISSUE THREAD

**Issue by Tobias02** [PygmalionOfCyprus/cmo-db-requests#3111]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2162, 1969, 649

### Summary of Changes

In the current database this helicopter carries two MK46 or MU90 torpedoes, while in reality it carries four torpedoes. I enclose the Italian Navy technical data sheet.
Thanks!
![EH101 ASW](https://user-images.githubusercontent.com/125903334/221365888-0d4821e4-637c-4fd5-89b3-fb410ed7795d.JPG)

### Sources

![EH101 ASW](https://user-images.githubusercontent.com/125903334/221365905-5e35258a-7efc-4a73-9e0b-f88f15c51e53.JPG)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
