### ISSUE TITLE
TAL-1 vs TAL-2 cluster bombs on Venezuelan F-16s

### ISSUE THREAD

**Issue by Lafayette-II** [PygmalionOfCyprus/cmo-db-requests#3113]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft_2215, 1983, 2098, 3439, 3440, 3441

### Summary of Changes

Hi. Please change the TAL-2 loadouts to TAL-1 loadouts on mentioned DBIDs.  From the mid-late 1990s until 2011, Venezuela possessed a stockpile of Israeli-made TAL-1 Cluster Bombs. In-game the aircraft are assigned TAL-2 loadouts but I couldn't find any information on TAL-2 munitions used by the FAV, maybe these where mixed up? 

In 2011, Venezuela announced the destruction of cluster munition stocks. This will necessitate new DB entries for the 2011 F-16A/B. Thanks!

### Sources

https://www.infodefensa.com/texto-diario/mostrar/3144768/ministerio-defensa-venezuela-destruye-bombas-racimo

http://www.the-monitor.org/en-gb/reports/2016/venezuela/cluster-munition-ban-policy.aspx

https://books.google.md/books?id=-uVY1Blgu4IC&pg=PA20&lpg=PA20&dq=Exports+of+Cluster+Bombs+authorized+in+the+years+1991%E2%80%932001,%E2%80%9D+dated+23+June+2009,+taken+during+Monitor+meeting+with+Juan+Pablo+Jara,+Desk+Officer,+Ministry+of+National+Defense,+Santiago,+11+April+2012.&source=bl&ots=r81j-_UatK&sig=ACfU3U2f5II83mKDlwTF7JALxa_EU3abKA&hl=de&sa=X&ved=2ahUKEwjG-4engbP9AhVW8bsIHWmHDPwQ6AF6BAgGEAM#v=onepage&q&f=false (page 21)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
