### ISSUE TITLE
#2610 SAM Bty (I-HAWK [Mersad Upgrade] has only 3 launchers instead of 6 in the DB

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#3118]
### DB Selector

DB3K

### Affected DBID(s)

#2610

### Summary of Changes

Please reduce the amount of the HAWK launchers of #2610 from 6 to 3.
Some Hawk sites still have 6 positions but all of them have only 3 present, the rest is empty.

### Sources

I can give you more but this summs it up:
![Clipboard04](https://user-images.githubusercontent.com/60408110/222169025-510e9281-53f4-4397-b261-0719f1157248.jpg)
![Clipboard02](https://user-images.githubusercontent.com/60408110/222169028-c9d271fc-ffe7-4c66-81ab-841aded9a603.jpg)
![Clipboard03](https://user-images.githubusercontent.com/60408110/222169030-4bb5b22a-a225-411b-a421-1b12edaa5393.jpg)

**Comment by tbrandon517** [comment]
Maybe do a 3x launcher version and mark the 6x launcher version as Hypothetical wartime variant?

**Comment by Huib18** [comment]
That is a nice solution, thanks.

**Comment by tbrandon517** [comment]
Thanks, I just happened to recall the Chinese HQ-9s have 2x launcher peacetime configurations as well as full 8x launcher units in the DB so it seemed to make sense here where we can see a site setup for 6x launchers but only 3x deployed.

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
