### ISSUE TITLE
Add AW101 to Norway

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3120]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5319

### Hypothetical

No

### Name

AW101 SAR Queen

### Country

Norway

### Service

Air Force

### In Commission

2017

### Number in Service

16 (12 delivered hus far, 1 crashed)

### Sensors

Remove Generic Weather Radar
Add Osprey 30 AESA (Sensor 6011)
Add Star Safire 380-HDc (Sensor 5617)
Add Searchlight (Sensor 251)

### Sources

https://uk.leonardo.com/en/news-and-stories-detail/-/detail/aw101-sar-queen-helicopters-operational-in-norway
https://www.helis.com/database/news/aw101_no_flir/
https://uk.leonardo.com/en/news-and-stories-detail/-/detail/aw101-sar-queen-the-squadron-viewpoint

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
