### ISSUE TITLE
Update EH101 for Denmark 

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3121]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5319 and 798

### Summary of Changes

Update sensors:

Remove Generic Wather Radar
Add AN/ALQ-213 MAWS (Sensor 5682)
Add RDR-1600 (Sensor 1974)
Add Star Safire II (Sensor 4122)

### Sources

https://www.forsvaret.dk/da/materiel2/eh101-merlin/
https://www.helis.com/database/news/eh101_dk_terma2/
https://www.telephonics.com/uploads/standard/46049-TC-RDR-1600-Brochure_2023-02-07-142002_jmmm.pdf
https://www.flightglobal.com/nordic-special-great-danes/71078.article

**Comment by PygmalionOfCyprus** [comment]
I can't find any mention of any of these platforms in any of the sources you provided?

**Comment by Andratenor** [comment]
The MAWS are described here, sixth paragraph:
https://www.helis.com/database/news/eh101_dk_terma2/

The FLIIR is descibed here, middle of he article under the headline AW101 Cockpit, where it is mentioned that it is the same as Portuguese helis:
https://www.airforce-technology.com/projects/aw101-helicopter/

The radar is mentioned here, under Avionics (with the archived article that is referenced). Must have forgot to add this as a source:
https://en.wikipedia.org/wiki/AgustaWestland_AW101
https://web.archive.org/web/20140408214018/http://www.aviationtoday.com/av/rotocraft/Agusta-Westlands-EH101_733.html

**Comment by PygmalionOfCyprus** [comment]
Good to know I can't read. Handled 500; I made separate 2014 entries for the MAWS since they weren't installed initially.
