### ISSUE TITLE
Please add AB-25 (aka Turk) patrol boat to Kazakhstan

### ISSUE THREAD

**Issue by Mark-Gellis** [PygmalionOfCyprus/cmo-db-requests#3122]
### DB Selector

DB3K

### DBID to Copy

Ship 3641 (DB3K)

### Hypothetical

No

### Name

Turk

### Country

Kazakhstan

### Service

Kazakh Naval Forces

### In Commission

1999-present

### Number in Service

2

### Sensors

None known

### Mounts

None known

### Loadout Options

None known

### Other Changes

None known -- sorry, very little information available.  It seems like it should be pretty close to the ones transferred to Azerbaijan, though.

### Sources

https://en.wikipedia.org/wiki/Kazakh_Naval_Forces
![From Trade Registers at Armstrade sipri org](https://user-images.githubusercontent.com/124533607/222321617-fcf450a6-f9ab-4a63-a796-53a30125b61a.JPG)

**Comment by PygmalionOfCyprus** [comment]
Handled 500. Found more info at good ol' Navypedia: https://www.navypedia.org/ships/kazakhstan/kaz_cg_naygazny.htm
