### ISSUE TITLE
Correction: Remove the J-15D wingtip jammer on J-15 & J-15B

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3124]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 2496, 6098

### Summary of Changes

Remove the wingtip jammer on their A/A loadout. No info indicates PLANAF uses this EW equipment on combat ac except J-15D EW fighter. The wingtip pylons are used for WVRAAMs. Maybe another "tiny" DB update error.

### Sources

![image](https://user-images.githubusercontent.com/107970049/222619307-99bc2ba1-ce93-4e20-9bf2-38d26e1d192c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
