### ISSUE TITLE
Please add Mi-35M Hind to Kazakhstan

### ISSUE THREAD

**Issue by Mark-Gellis** [PygmalionOfCyprus/cmo-db-requests#3127]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5672

### Hypothetical

No

### Name

Mi-35M Hind

### Country

Kazakhstan

### Service

Kazakh Air Defense Forces

### In Commission

2016-present

### Number in Service

12

### Other Changes

Wikipedia says 22 are in service, with 4 more on order, but SIPRI only appeared to list 12.

### Sources

https://en.wikipedia.org/wiki/Kazakh_Air_Defense_Forces
https://en.wikipedia.org/wiki/List_of_Mil_Mi-24_variants

![Mi-35M for Kazakhstan](https://user-images.githubusercontent.com/124533607/222630965-0a388237-d2b6-4eef-8386-6d793f6bb376.JPG)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
