### ISSUE TITLE
Please add Su-25 Frogfoot A for Kazakhstan

### ISSUE THREAD

**Issue by Mark-Gellis** [PygmalionOfCyprus/cmo-db-requests#3128]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2378

### Hypothetical

No

### Name

Su-25 Frogfoot A

### Country

Kazakhstan

### Service

Kazakh Air Defense Forces

### In Commission

1997-present

### Number in Service

14

### Other Changes

This appears to be a group of Russian aircraft transferred to Kazakhstan to pay off a debt, so I used the Russian version listed in the database.  

### Sources

https://en.wikipedia.org/wiki/Kazakh_Air_Defense_Forces
https://en.wikipedia.org/wiki/Sukhoi_Su-25

![Su-25 for Kazakhstan](https://user-images.githubusercontent.com/124533607/222632904-9a243654-e05f-4064-a763-12f8db1e0e5a.JPG)

**Comment by Mark-Gellis** [comment]
Sorry...it's not hypothetical; I forgot to select that to "No."

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
