### ISSUE TITLE
Addition: Hypo J-20 w/ LO

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3129]
### DB Selector

DB3K

### DBID to Copy

AC 2463

### Hypothetical

Yes

### Name

J-20B

### Country

PRC

### Service

AF

### Sensors

Keep original. 

### Mounts

Keep original. 

### Loadout Options

Keep original. 

### Other Changes

Change signature to that comparable to F-22. 

### Sources

https://csis-website-prod.s3.amazonaws.com/s3fs-public/publication/230109_Cancian_FirstBattle_NextWar.pdf?

**Comment by PygmalionOfCyprus** [comment]
Beyond a hypothetical "just for kicks" addition -- which is not inherently bad -- is there any reason to suspect that this may be the case? The source you provide does not support the idea, even notionally, that the J-20 has stealth near that of an F-22:

>However, most analysts believe that [the J-20] will also have a higher radar cross-section (i.e., less stealth) than either the F-22 or F-35.
