### ISSUE TITLE
Fix: LRDR

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3131]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6999

### Summary of Changes

Increase peak power to 32000000
Change to Full LDSD.
Add air search capability. 

### Sources

Mistakes in #2532, also generic air search capability on BMD radars.

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
