### ISSUE TITLE
Update: PL-15/PL-15E sensor tech level

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3134]
### DB Selector

DB3K

### Affected DBID(s)

sensor 5790

### Summary of Changes

Main request: Change its tech level from early 2000s to **early 2010s**.

Reason: For an AAM entered service in late 2010s (2016 or 2018+) using GaN AESA Radar, there is no doubt that it has an early 2010s tech sensor.  The current tech level must be a DB update legacy.

### Sources

https://en.wikipedia.org/wiki/PL-15

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
