### ISSUE TITLE
Hypo: China, DF-27 HGV

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3135]
### DB Selector

DB3K

### Baseline

weapon 3373, 3374

### Hypothetical

Yes

### Name

DF-27 HGV

### Length (m)

same as DF-26

### Width/Span (m)

same as DF-26

### Diameter (m)

same as DF-26

### Weight (kg)

same as DF-26

### Range (nm)

50-4320

### Warhead

1000kg HE

### Targets

Surface vessel, Land Structure - Soft, Land Structure - Hardened, Runway

### Sensors

same as DF-26B

### Sources

https://www.defense.gov/CMPR/
![image](https://user-images.githubusercontent.com/107970049/222940464-c2d60b48-f699-47a5-8973-5f913f62d9c2.png)

**Comment by LuigiP57** [comment]
@KushanGaming Do consider the anti-ship variant mentioned in the other issue, plz.

**Comment by KushanGaming** [comment]
Done for DB501.
