### ISSUE TITLE
Hypo: China, PLARF, DF-17B AShHGV

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3136]
### DB Selector

DB3K

### Baseline

weapon 3574, 3575

### Hypothetical

Yes

### Name

DF-17B AShHGV

### Length (m)

same as DF-17

### Width/Span (m)

same as DF-17

### Diameter (m)

same as DF-17

### Weight (kg)

same as DF-17

### Range (nm)

same as DF-17

### Warhead

same as DF-17

### Targets

Surface Vessel

### CEP (m)

2

### Sensors

Same as other ASBM

### Comments

US DoD mentioned that it might have an ability to target surface warships.

### Sources

https://www.defense.gov/CMPR/
![image](https://user-images.githubusercontent.com/107970049/222940670-12134903-afbd-48f7-bfc6-162ac762ea63.png)

**Comment by LuigiP57** [comment]
Not having enough information. We already got DF-27 and KF-21 HGV.

**Comment by RickDNiu** [comment]
There is a rocket force ASBM brigade that transitioned to DF-17 IIRC

**Comment by Luigi-II** [comment]
> There is a rocket force ASBM brigade that transitioned to DF-17 IIRC

That's surprising. I want to see what the source is.

**Comment by RickDNiu** [comment]
Maybe it’s just DF-26, but could also be DF-27. The margin for effective DF-17 is too small.

Niu

On Sep 23, 2024, at 3:48 AM, Luigi-II ***@***.***> wrote:

﻿

There is a rocket force ASBM brigade that transitioned to DF-17 IIRC

That's surprising. I want to see what the source is.
