### ISSUE TITLE
Please consider adding KH-15S Loadout to Tu-95MS/MSM

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#314]
### DB Selector

DB3K

### User(s)

Tu-95MS/MSM (DBID's: 62, 447, 520, 773 & 1611)

### Weapons Carried

6x Kh-15S Anti-Ship Missiles in 1x Internal MKU-6-1 Rotary Launcher Pods

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Unknown

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

The Kh-15S is not currently part of the database, but a new weapon DB request has been submitted in issue #254 ....

### Sources

1. https://www.weaponsystems.net/system/99-Raduga+Kh-15
2. https://military-history.fandom.com/wiki/Kh-15

**Comment by PygmalionOfCyprus** [comment]
Added w/ #254.
