### ISSUE TITLE
HADR HR-3000 might be double

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3140]
### DB Selector

DB3K

### Affected DBID(s)

Sensor #3141, #1771

### Summary of Changes

Both entries looks like same emitter, as far as can be seen in the in-game DB.
HADR (HR-3000) & HR-3000 (HADR)

### Sources

They have different units connected.

**Comment by Parel803** [comment]
Same might be for Sensor: #2187 AN/FPS-130 (ARSR-4) & ARSR-4 (AN/FPS-130, W-2100)?

**Comment by PygmalionOfCyprus** [comment]
Yeah, I think back in the day when someone else was in charge of the DB they had the idea to make multiple identical sensor entries depending on what the local name was. That's no longer precedent but that's why those are there. Can't delete 'em, but they're not harming anyone.

**Comment by Parel803** [comment]
Understood and no problem just thought I mention it,
thx for answering, regards.
