### ISSUE TITLE
Corrections for German Type 126

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3141]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3756

### Summary of Changes

-The 16 cell Mk,41 cell can handle up to 64 ESSM missiles, as they are quad-packed in the cells.
-The ships will be primarily used for ASW and equipped with an Active/passive low frequency variable depth towed sonar from Atlas Elektronik

### Sources

https://en.wikipedia.org/wiki/F126_frigate
https://defence-industry.eu/german-f126-frigate-to-be-equipped-with-anti-submarine-warfare-technology-from-atlas-elektronik/

**Comment by PygmalionOfCyprus** [comment]
Fixed the quad-pack thing, any idea what the actual sonar model is?

**Comment by Andratenor** [comment]
It has unfortunatly not been officiall confirmed yet as far as I know, but I would be extremely surprised if it is not some version of the ACTAS, Sensor 6120.

However, the range of that one seems to be slightly OP as the 200 NM is almost three times the range of the Type 2087 Mk.4, widely considered the best towed sonar in the World.

https://www.atlas-elektronik.com/solutions/anti-submarine-systems/actas.html

**Comment by PygmalionOfCyprus** [comment]
Well, ACTAS does advertise as being effective to "over the horizon" ranges. That said, "range" on sonar is kind of nonsense, because it's entirely dependent ocean conditions anyway (we model this in Command -- I challenge anyone to make a sonar detection at 200nm regardless of instrumented range).

**Comment by PygmalionOfCyprus** [comment]
Added ACTAS to the F126 for now until/unless we get info otherwise. Handled 500.
