### ISSUE TITLE
Add HNoMS Nordkapp to Norwegian Navy as flagship of NATO SNMCMG1

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3143]
### DB Selector

DB3K

### DBID to Copy

Ship 1876

### Hypothetical

No

### Name

A531 Nordkapp

### Country

Norway

### Service

Navy

### In Commission

2022-Present

### Number in Service

1

### Other Changes

As new NATO flagship for SNMCMG1, upgraded with LINK 16 and LINK 22.

### Sources

https://en.wikipedia.org/wiki/Nordkapp-class_offshore_patrol_vessel
https://www.forsvaret.no/aktuelt-og-presse/aktuelt/fra-kystvakt-til-marinefartoy-na-er-knm-nordkapp-klar-for-nato-oppdrag?q=knm%20nordkapp

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
