### ISSUE TITLE
Add Fokker F.27 Mk.400 to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3145]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4017

### Hypothetical

No

### Name

Fokker F.27

### Country

Finland

### Service

Air Force

### In Commission

1981-2013

### Number in Service

3, 1 converted to SIGINT aircraft in 1991.

### Mounts

Add Paratroopers

### Sources

https://en.wikipedia.org/wiki/List_of_Fokker_F27_operators#Military_operators
https://fi.wikipedia.org/wiki/Fokker_F.27

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
