### ISSUE TITLE
Add Fokker F.27 SIGINT to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3146]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4017

### Hypothetical

No

### Name

Fokker F.27

### Country

Finland

### Service

Air Force

### In Commission

1991-2016

### Number in Service

1

### Sensors

Add Generic 1970's SIGINT (Sensor 2317)

### Mounts

Remove all transportable goods

### Other Changes

Exactly what kind of equipment was in use is still highly classified, but it is known that they were used for ELINT and COMINT along the Russian border.

### Sources

https://www.britmodeller.com/forums/index.php?/topic/235066465-ilmavoimat-fokker-f27-400m-ff-3/
https://www.facebook.com/Scramblemagazine/posts/finnish-fokker-f27-on-displaylate-december-2018-the-former-ilmavoimat-finnish-ai/2594062723953579/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
