### ISSUE TITLE
Flanker -What's in a Name

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#3149]
### DB Selector

DB3K

### Affected DBID(s)

4696, 847, 4741, 4958, 4959, 5910, 3819, 4582

### Summary of Changes

Su-27SM2/SM3 are Flanker J (not B as in the DB)
Su-30SM/SM2 (in Russian use) are the Flanker H
Su-35S found 2 that are still marked as Flanker E, they should be Flanker M as per the 2 that were corrected

These names apply to all of these aircraft used by VKS and by Belarus

I'll leave the actual fits for now until I can find sources that can be utilised by the team

### Sources

Wikipedia is, in fact, correct for these designators now (I am not sure it was this time last year)
Lot of primary sources to follow over the 3 articles, the main areas of conjecture remain the avionics fit in each version.
If anyone has the archived Rosenboronexport catalogues, then the actual fits may be in them (just overlooked).

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
