### ISSUE TITLE
Update Finnish CASA C-295M SIGINT sensors

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3155]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4570, and tangentially also all other C-295

### Summary of Changes

The Dragon Shield system manufactured my Lockheed Martin amd installed on the C-295M named CC-1 is more than just ESM. 

Exactly what is highly classified, but what is known from open sources is that it can handle SIGINT, ELINT, COMINT and IMINT through an EO/IR pod under the fuselage, and follow more than 100 different elecromagnetic sources at the same time.

Changes:
Replace Generic ESM (Advanced) with Generic 2000's SIGINT (Sensor 5731)
Add Generic EO/IR Turret (Sensor 6492)

Also, all C-295M are equipped with RWR, MAWS, LWR and chaff/flares dispensers. So add the following to Aircraft #2948, #3232, #3233, #3235, #3236, #3237, #3238, #3868, #3942,  #4569, #5071, #5382, #5437, #5549, #5550,  #5666, #5735, #5948, #6174, :

Generic RWR (Sensor 2919)
Generic MAWS (Sensor 2216)
12x Generic Chaff Salvo, 4x Cartridges (Weapon 524)
12x Generic Flare Salvo, 4x Cartridges Dual Spectral (Weapon 2050=, 

### Sources

https://maanpuolustus.net/media/dragon-shield-kontti-sigint-elint-comint-imint.13/
https://maanpuolustus.net/media/ilmavoimien-casa-c-295m-sigint-elint-comint-imint-tiedustelukone.12/
https://www.lentoposti.fi/uutiset/puolustusvoimien_dragon_shield_valvontaj_rjestelm_t_ydess_foc_valmiudessa
https://tangentlink.com/lockheeds-dragon-scout-gulfstream-iii/
https://www.airrecognition.com/index.php/world-air-force-military-equipment-aircraft/west-europe-air-force-military-aircraft-planes-equipment/spain-spanis-air-force-military-aircraft-planes-equipment-aviation-defence-industry-military-technology/spain-spanish-air-force-military-transport-aircraft-aviation-defence-industry-technology/61-c-295-c295-military-transport-aircraft-technical-data-sheet-specifications-intelligence-description-information-identification-pictures-photos-images-video-spain-spanish-air-force-defence-industry-technology.html

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
