### ISSUE TITLE
Add Odin Mount to USS John Finn 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3156]
### DB Selector

DB3K

### Affected DBID(s)

2866

### Summary of Changes

Add Odin mount similar to Dewey's #3209 configuration. 1 mount forward.

### Sources

https://twitter.com/CavasShips/status/1632259382485426179?cxt=HHwWhoC9pdTQ-aYtAAAA
https://www.dvidshub.net/image/7573156/uss-john-finn-ddg-113-commemorates-navy-chief-petty-officer-last-living-medal-honor-recipient-attack
https://en.wikipedia.org/wiki/USS_John_Finn

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
