### ISSUE TITLE
Saudi Arabia - HSI-32 Interceptor

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3157]
### DB Selector

DB3K

### DBID to Copy

DB3K Ship 3901 and 3911

### Hypothetical

No

### Name

HSI-32 Interceptor

### Country

Saudi Arabia

### Service

Navy

### In Commission

2020-

### Number in Service

58x

### Sensors

No Change Apparent

### Mounts

No Change Apparent

### Loadout Options

N/A

### Other Changes

No Change Apparent

### Sources

https://www.navalnews.com/naval-news/2023/03/cmn-and-zamil-shipyards-deliver-the-last-batch-of-58-hsi-32-fpb-to-saudi-arabia/?fbclid=IwAR3mS1W3FR95vE4QOYTtK06nku01JRkXDJxeJhx-EEF_RFBdOVxgq4x_IdQ
https://www.navalnews.com/naval-news/2020/09/cmn-hands-over-2nd-and-3rd-batches-of-hsi32-interceptors-to-royal-saudi-navy/
https://www.thenationalnews.com/gulf-news/saudi-arabia/2023/03/01/saudi-arabia-completes-project-to-make-hsi32-fast-interceptor-boats/
https://www.zawya.com/en/economy/gcc/saudi-arabia-takes-complete-delivery-of-first-home-made-hs132-speed-interceptor-boats-kq5ldstm

![image](https://user-images.githubusercontent.com/99599482/223885003-0531ac30-8634-4f3d-8d84-ac78b02c2f2c.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
