### ISSUE TITLE
Ukraine - Mugin 5 Suicide Drone

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3159]
### DB Selector

DB3K

### Baseline

DB3K Aircraft 5934

### Hypothetical

No

### Name

Mugin 5 Suicide Drone

### Length (m)

3.5m

### Width/Span (m)

5m

### Diameter (m)

0.375m

### Weight (kg)

90kg

### Range (nm)

Similar to UAV ferry range

### Target Altitude / Depth (ft)

Ground

### Target Speed (kts)

Unknown

### Launch Altitude / Depth (ft)

Ground

### LaunchSpeed (kts)

Stationary

### Warhead

up to 25Kg

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### Sensors

Possible EO/IR Terminal Guidance automatically or via man in the loop

### Weapon Codes

Terrain Following, Loiter Capability, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Re-Attack Capability, Weapon Altitude Control Possible, Attitude Control - Aerodynamic Only, Uses GPS, Level Cruise Flight

### Comments

Modified Commerical UAVs

### Sources

https://www.thedrive.com/the-war-zone/our-best-look-at-ukraines-shadowy-alibaba-drone-used-for-long-range-strikes?fbclid=IwAR2K7K8BjUnQLRoIzZCCyJYLCcy3qgAmaM3U1QrDhCJNtd6j0GuDv7Mj_hI
https://www.thedrive.com/the-war-zone/kamikaze-drones-strike-russian-oil-refinery-looks-like-model-sold-on-alibaba
https://www.muginuav.com/product/mugin-5-pro-5000mm-carbon-fiber-uav-platform/
https://www.thedrive.com/the-war-zone/ukraine-situation-report-shadowy-long-range-kamakaze-drone-strikes-again

![image](https://user-images.githubusercontent.com/99599482/223889612-e9d023e3-8137-4807-8ab1-9358552c4185.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
