### ISSUE TITLE
Replace all AA-11 (R-73) with AA-8 (R-60) in iraqi MiG-29 loadouts

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#316]
### DB Selector

DB3K

### Affected DBID(s)

#1347 and #3342

### Summary of Changes

According to the book Desert Storm Volume 1: the Iraqi invasion of Kuwait and operation Desert Shield 1990-1991, Iraq never received R-73E for their MiG-29, they were instead armed with R-60M/MK. The SIPRI arms transfer database also does not mention R-73E being trasferred to Iraq.
Please replace all AA-11 (R-73)(DB ID: #1896) with AA-8 (R-60) (DB ID: #1897) in Iraqi MiG-29(ID: #1347 and #3342) loadouts 

### Sources

Hooton, E. R., & Cooper, T. (2019). Desert Storm. Volume 1: The Iraqi Invasion of Kuwait & Operation Desert Shield 1990–1991 (Middle East@War). Helion and Company. Page 22 
![Scan_20220219 (2)](https://user-images.githubusercontent.com/100023323/154797733-79a4ce6b-aa60-4cf5-b229-41ce2204856f.jpg)

**Comment by Jkryos** [comment]
Corrected DB3K_493.
