### ISSUE TITLE
Copy 5557 for MD-530F Cayuse Warrior Nigeria Army x 12

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3160]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5557 or any MD-530F Cayuse Warrior

### Hypothetical

No

### Name

MD-530F Cayuse Warrior Nigeria Army 2023 x 12

### Country

Nigeria 

### Service

Army

### In Commission

2024-2023

### Number in Service

12

### Sensors

Exact sensor fit TBC. The Cayuse Warrior Plus scout/attack helicopter is mentioned in the press release, this Plus version has the FLIR EO system turret with a laser etc although it may be the MX-10 not MX-15. 

### Mounts

Nil

### Loadout Options

Hydra
HMP400 

### Other Changes

Nil. 

### Sources

https://www.mdhelicopters.com/md-helicopters-ramps-up-production;-receives-award-to-deliver-12-cayuse-warrior-plus-helicopters-to-nigerian-army.html

**Comment by PygmalionOfCyprus** [comment]
Please preface your "DBID to Copy" w/ an annex name (e.g. "Aircraft 5557") so the auto-labeler can parse it.

**Comment by KLABDB3K** [comment]
> Please preface your "DBID to Copy" w/ an annex name (e.g. "Aircraft 5557") so the auto-labeler can parse it.

Will do. Not near a PC but will be once some snow melts.

**Comment by PygmalionOfCyprus** [comment]
You don't have to on these issues, I did it manually; just bear in mind going forward. 🙂

**Comment by Jkryos** [comment]
Added DB3K 500.
