### ISSUE TITLE
XQ-58 Valkyrie, UTAP-22 Mako datalink missing

### ISSUE THREAD

**Issue by pfgpb** [PygmalionOfCyprus/cmo-db-requests#3161]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 5186, 4775

### Summary of Changes

XQ-58 Valkyrie, UTAP-22 Mako can both be armed with GBU-53/B Stormbreakers but cannot fire them due to lack of AIM-120 Command Datalink

### Sources

Command Database

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
