### ISSUE TITLE
Iran - Zulfiqar Air Defense Small Boat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3164]
### DB Selector

DB3K

### DBID to Copy

DB3k Ship 4110

### Hypothetical

No

### Name

Zulfiqar [Bladerunner Mod]

### Country

Iran

### Service

IRGC-N

### In Commission

2023-

### Number in Service

uncertain

### Sensors

1x Navigation Radar
1x Nawab FCR Radar

### Mounts

1x 14.7mm HMG at bow
1x 6 Cell Nawab SHORAD VLS

### Loadout Options

N/A

### Sources

http://www.hisutton.com/Iran-IRGC-Air-Defense-Fast-Boat.html?fbclid=IwAR1O0qEPWfqf6Sz_eDKthzmxucN8cwqKvTCnpUq905POWnfqqjvGBFGcNMs
https://eurasiantimes.com/worlds-first-air-defense-boat-capable-of-firing-deadly-missiles-from-its-vertical-launch-system-experts/
https://ho1.us/2023/03/iran-reveals-worlds-first-air-defense-small-boat/

![image](https://user-images.githubusercontent.com/99599482/224373662-1e9b3e63-b26b-4ff2-97d5-4806aa538ed7.png)
![image](https://user-images.githubusercontent.com/99599482/224373689-a4f9e88d-671d-49f4-84f7-10ddbfb79b83.png)

**Comment by PygmalionOfCyprus** [comment]
This is not a Seraj copy, although it is obviously based on a Bladerunner hull. And, infuriatingly, it's not a Zolfaghar copy either, despite sharing a name (Iran loves to do that). I think this is an entirely new platform, albeit one using some design elements from other vessels.

See how the Seraj is much smaller:

![image](https://user-images.githubusercontent.com/87087226/224404019-4468df97-72cd-417e-88fa-00ba4fd6a989.png)

And see the Peykaap III / Zolfaghar, which is also shorter (and notably has no Bladerunner hull):

![image](https://user-images.githubusercontent.com/87087226/224404272-766d8393-00a9-4be3-a78d-a5bb284e75cc.png)

**Comment by tbrandon517** [comment]
Yeah, the more voluminous shape is apparent when you see both from the lower angle.

**Comment by Jkryos** [comment]
Added DB3K 503.
