### ISSUE TITLE
Soviet Union - Pr.629R Golf SSQ

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3165]
### DB Selector

CWDB

### DBID to Copy

CWDB Sub 68

### Hypothetical

No

### Name

Pr.629R Gold SSQ

### Country

Soviet Union

### Service

Navy

### In Commission

1973-1991

### Number in Service

3x

### Sensors

No indicated change to sonars or radars, just comms fit.

### Mounts

Remove Missile and Torpedo Tubes

### Loadout Options

N/A

### Other Changes

3x Golf I SSBs converted to Command & Control Submarines with weapon systems removed and the addition of various communication systems and command spaces. 

For CWDB and DB3K

### Sources

https://nuke.fas.org/guide/russia/slbm/629.htm
https://en.wikipedia.org/wiki/Golf-class_submarine
https://www.hazegray.org/features/russia/sub-spec.htm
https://archive.org/stream/CIADocuments/CIA-483_djvu.txt
https://apps.dtic.mil/sti/pdfs/ADA151290.pdf
https://naval-encyclopedia.com/cold-war/ussr/soviet-submarines.php

![image](https://user-images.githubusercontent.com/99599482/224379542-ded584cd-8a04-4ea1-ac8f-911188b44a02.png)
![image](https://user-images.githubusercontent.com/99599482/224377191-c5972192-6b53-469c-a4ea-6cfadc93e82f.png)
![image](https://user-images.githubusercontent.com/99599482/224378320-e80957b5-658c-4a17-89e8-3613dfdd149b.png)
![image](https://user-images.githubusercontent.com/99599482/224377436-bad152b0-53ec-43dc-80d6-4d2187cdb915.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
