### ISSUE TITLE
Soviet Union - Pr.619 Golf V SSB

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3166]
### DB Selector

CWDB

### DBID to Copy

CWDB Sub 68

### Hypothetical

Yes

### Name

Pr.619 Golf V SSB

### Country

Soviet Union

### Service

Navy

### In Commission

1978-1992

### Number in Service

1x

### Sensors

Uncertain of any sonar changes.

### Mounts

1x SS-N-20 SLBM

### Loadout Options

N/A

### Other Changes

Golf V - Conversion started in 1976 (return to service 1978) of one submarine ("K-153") was outfitted with a launcher to carry out tests of the R-39 (SS-N-20 SLBM) missile. The submarine received the new designation Project 619.

For CWDB and DB3K

### Sources

https://nuke.fas.org/guide/russia/slbm/629.htm
https://en.wikipedia.org/wiki/Golf-class_submarine
https://www.navypedia.org/ships/russia/ru_ss_b41.htm

![image](https://user-images.githubusercontent.com/99599482/224381828-9bf86e4e-ec1f-4350-a457-221d88e610ee.png)

**Comment by tbrandon517** [comment]
Not Hypo, marked yes in error.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus unit in CWDB v503 has the original Sark SLBMs rather than the single R-39.

**Comment by PygmalionOfCyprus** [comment]
Handled 505. I started to add it back in 503 and then forgot to finish it.
