### ISSUE TITLE
Add North Korean F-5a (MiG-17 copy) with extra hardpoints 

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#317]
### DB Selector

DB3K

### DBID to Copy

Aircraft #3897

### Hypothetical

No

### Name

F-5A Fresco (MiG-17PF copy) extra hardpoints

### Country

North Korea

### Service

Air Force

### In Commission

Specific year unknown but program started in the 1960's

### Loadout Options

- 4 x 100kg GPB #3020
- 2 x 250kg GPB #1581
- 32 x 57mm rocket #217

Or a combination of the above mounted on 4-6 hardpoints.

### Sources

Mitzer, S., &amp; Oliemans, J. (2020). The Armed Forces of North Korea: On the path of Songun. Helion et Company. page 125-126
![125](https://user-images.githubusercontent.com/100023323/154799962-d4053bae-a565-4123-a647-91e80ee32c30.jpg)
![126](https://user-images.githubusercontent.com/100023323/154799964-07779ed2-d905-4704-8c44-ac2b7ba4c826.jpg)

**Comment by Jkryos** [comment]
Added DB3K 493.
