### ISSUE TITLE
Update 01 Deniz Han [C92] SSM Fit

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3170]
### DB Selector

DB3K

### Affected DBID(s)

DB3K Ship 3426

### Summary of Changes

Add 8 Otomat Mk2 Blk IV SSM
In 4x2 amidship launchers hidden by doors/covers

### Sources

https://www.navalnews.com/naval-news/2021/08/turkmenistan-comissions-its-first-turkmen-class-corvette-deniz-han/
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/october/12398-turkmenistan-unveils-its-new-corvette-deniz-han-during-a-parade.html
https://www.janes.com/defence-news/news-detail/turkmenistan-navy-commissions-new-corvette
https://militaryleak.com/2021/08/18/turkmen-naval-forces-commissions-its-first-turkmen-class-corvette-deniz-han/
https://www.dearsan.com/en/products/naval-vessels/corvette-c92
https://en.wikipedia.org/wiki/Turkmen_Naval_Forces
https://www.globalsecurity.org/military/world/europe/dearsan-c92.htm

Open Launchers Exposed
![image](https://user-images.githubusercontent.com/99599482/224423400-5f715d70-fe4e-406e-a8ff-38afee9e32f9.png)

Launchers Hidden
![image](https://user-images.githubusercontent.com/99599482/224423509-0e0a84f0-3ebb-4f11-8f69-55d00106e28f.png)
![image](https://user-images.githubusercontent.com/99599482/224423567-7ba3d7a1-09b7-4fae-8d75-b7af88db2d40.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
