### ISSUE TITLE
Add HMS Artemis to Sweden

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3172]
### DB Selector

DB3K

### Baseline

Ship 2556

### Hypothetical

Yes

### Name

AGI, A202 Artemis

### Class

Artemis class

### Country

Sweden

### Service

Navy

### In Commission

2022-Present

### Number in Service

1

### Length (m)

74

### Beam (m)

14

### Draft (m)

3.8

### Standard Displacement (t)

2200

### Complement

About 35

### Primary Propulsion Type

Diesel

### Propulsion

Unknown

### Flank Speed (kt)

14

### Range (nm) at Speed (kt)

Unknown

### Sensors

Generic Navigation Radar (Sensor 1916)
Generic 2020's SIGINT (Sensor 6544)

### Mounts

None

### Aircraft & Docking Facilities

1x Davit for MOB/Life Boat

### Comms/Datalinks

Unknown and classified

### Ship Codes

Degaussed Steel Hull, Advanced Quieting, Aluminum Superstructure Only

### Sources

https://en.wikipedia.org/wiki/HSwMS_Artemis
https://www.thedefensepost.com/2022/11/04/swedish-spy-ship-artemis-sea-trials/

**Comment by Jkryos** [comment]
Added DB3K pre-507.
