### ISSUE TITLE
PG 140 Emilio Aguinaldo service dates

### ISSUE THREAD

**Issue by Lafayette-II** [PygmalionOfCyprus/cmo-db-requests#3173]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1039

### Summary of Changes

According to Wikipedia the first ship, BRP Emilio Aguinaldo, was commissioned towards the end of 1990. In mid-2016, both ships were decomissioned.

### Sources

https://en.wikipedia.org/wiki/BRP_General_Emilio_Aguinaldo_(PG-140)
http://maxdefense.blogspot.com/2017/06/unannounced-and-upcoming-ship.html
https://www.facebook.com/permalink.php?story_fbid=1382111355147772&id=231970423495210

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
