### ISSUE TITLE
Add Folland Gnat FR.1 to Finland

### ISSUE THREAD

**Issue by Andratenor** [PygmalionOfCyprus/cmo-db-requests#3175]
### DB Selector

CWDB

### DBID to Copy

Aircraft 2324

### Hypothetical

No

### Name

Folland Gnat FR.1

### Country

Finland

### Service

Air Force

### In Commission

1960-1972

### Number in Service

2

### Sensors

Add 3x Vinten Model 547 cameras (Sensor 2603)

### Mounts

2x ADEN 30mm autocannons with 115 rounds each

### Sources

https://en.wikipedia.org/wiki/Folland_Gnat#Variants

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
