### ISSUE TITLE
Addition: DDG 51 Blk IIA with sensors and weapons upgrade

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3177]
### DB Selector

DB3K

### DBID to Copy

2717, 2865, 2866, 2869-2873, 3148, 3151. 

### Hypothetical

Yes

### Name

DDG 79 Oscar Austin, and so forth

### Country

Arleigh Burke-class

### Service

Navy

### Sensors

Keep respective originals, except: 
1. Change each SPY-1 to SPY-6(V)4, 
2. Change each SLQ-32 to (V)7. 
3. On DDG-119 and onwards, add SPQ-9B+. 

### Mounts

Keep respective originals, except on Mk41 VLS mounts, add: 
1. RGM-109J(V, Va, Vb(#3176 )), 
2. RIM-162E, 
4. RIM-66M-6, 
5. RIM-174, Blk IB, 
6. MIM-104F, PAC-3 MSE, 
7. LRASM. 

### Loadout Options

N/A

### Sources

https://www.raytheonmissilesanddefense.com/what-we-do/missile-defense/sensors/spy6-radars
https://www.secnav.navy.mil/fmc/fmb/Documents/22pres/SCN_Book.pdf, https://seapowermagazine.org/rear-adm-okano-modern-sensors-making-navy-ships-data-providing-monsters/
https://www.navalnews.com/naval-news/2021/11/us-navy-awards-raytheon-contract-for-maritime-strike-tomahawk-block-va/
https://www.militaryaerospace.com/sensors/article/14211359/shipboard-missiles-antiair
https://www.militaryaerospace.com/sensors/article/14195475/missile-radarguided-shiplaunched
https://www.thedrive.com/the-war-zone/patriot-missiles-paired-with-naval-vertical-launchers-pitched-by-lockheed

**Comment by PygmalionOfCyprus** [comment]
Please provide an actual DBID in the "DBID to Copy" section... 😢

**Comment by tbrandon517** [comment]
Additional 

https://www.navalnews.com/event-news/sea-air-space-2023/2023/04/lockheed-martins-aegis-patriot-pac-3-mse-update/

**Comment by HunterDNiu** [comment]
#4484
