### ISSUE TITLE
#3663 ASM HAWC and #3449 HAWC - Add plot course feature

### ISSUE THREAD

**Issue by KJohnston11** [PygmalionOfCyprus/cmo-db-requests#3178]
### DB Selector

DB3K

### Affected DBID(s)

Weapons 3663 and 3449

### Summary of Changes

Add the ability to plot the course of HAWC missiles before launch in the weapon allocation menu (if applicable? as it stands, ASM HAWCs are intercepted the same as basic Tomahawks when facing something like a Type 052  which doesn't sit right with me... it should have in flight maneuvering IMO).

### Sources

N/A

**Comment by LuigiP57** [comment]
Have you noticed that this AShM even doesn't got an Active radar sensor on it?

**Comment by KJohnston11** [comment]
yeah, it does hit targets though so i assumed it was intended.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
