### ISSUE TITLE
#3953 - Yak-130 Mitten (Algeria - 2015) Please update with weapons and consider many other users of armed version please? 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#318]
### DB Selector

DB3K

### Affected DBID(s)

#3953 - Yak-130 Mitten (Algeria - 2015)  

### Summary of Changes

#3953 - Yak-130 Mitten (Algeria - 2015)
Is currently just has a trainer load out but in reality has a significant air to ground and short range Air to air capability from the outset.
Dumb weapons definitely and probably the KAB-500 as a test seeker pod has been demostrated in a Twitter post from Algerian AF.
Weapon loads:
Air to ground:
2 to 4 x 20 round S-8 80mm rocket pods,
2 to 4 x 5 round S-13 122mm rockets,
2 to 4 x 100kg FAB/ZAB/OFAB
2 to 4 x 250kg FAB/ZAB/OFAB
2 to 4 x 500kg FAB/ZAB/OFAB/RBK

Air to air

2 to 4 R-73 / AA-11 Archer AAM

Plus combinations of two 450l drop tanks and a centreline Yak-130 specific 23mm SNPU-130 gun pod with 23mm GsH-23L and 120 rounds.
Algerian Yak-130 have also been carrying weapons and filmed deploying chaff/flares.

### Sources

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/293#issue-1143747914

https://dfnc.ru/en/aviazcia/the-yak-130-used-as-a-fighter-in-algeria/#:~:text=The%20ten%2Dton%20Yak%2D130,to%2Dair%20rockets%20are%20provided. 

https://twitter.com/DarikMk/status/1444594094144163841

![image](https://user-images.githubusercontent.com/99494755/154800827-6b0074a0-22df-4c2f-979f-abea1040edfb.png)
If it isn't used with weapons why would it have pylons fitted?

**Comment by tbrandon517** [comment]
Algerian Yak-130 with weapons.

https://images.app.goo.gl/JDAS1D9eDyxPP6gg8

**Comment by KLABDB3K** [comment]
Phot with weapons shows the tail end of the KAB-500Kr TV captive seeker head near the standing figure in addition to S-13,S-8 rocket pods and various FAB/OFAB 100kg and 250kg bombs.

**Comment by KLABDB3K** [comment]
Myanmar Vietnam Belarus Bangladesh all have Yak-130 and very likely using it in some form of armed capcity at least with R73 AAM and usual Soviet/Russian rocket pods and FAB/OFAB/RBK bombs.

**Comment by PygmalionOfCyprus** [comment]
Updated loadouts on all Yak-130s.

**Comment by KLABDB3K** [comment]
Thank you
