### ISSUE TITLE
PL-15 Internal Carriage on J-20

### ISSUE THREAD

**Issue by BigHardHorns** [PygmalionOfCyprus/cmo-db-requests#3182]
### DB Selector

DB3K

### Affected DBID(s)

GuidedWeapon #3413 (Sorry, don't really know what the 'annex' is)

### Summary of Changes

"The missile's length (5.8 meters) means it can't be carried internally by the Chengdu J-20 "stealth" fighter." I believe this statement is incorrect and should be deleted. It contradicts its inclusion in the "Internal Long-Range" and "Standard Intercept" loadout information for the J-20.

### Sources

key.aero article December 6 2018 - "J-20 Shows its teeth" (includes photo of PL-15s in weapons bay): [https://www.key.aero/article/j-20-shows-its-teeth](url) - requires subscription, screenshot showing photo and relevant part of article available free from: [https://1drv.ms/u/s!ArWNi1su36_0gbZ7FmlWTzrt9jB-dA?e=EvQK0O](url)
Air Forces of the World: Pacific Asia photo p.8-9 - screenshot available free from: [https://1drv.ms/i/s!ArWNi1su36_0gbZ842ni8acfdVECeQ?e=DsQoCk](url)
Hush-Kit Book of Warplanes p.201 (shows as part of standard loadout, does not specify internal or external carriage)

**Comment by PygmalionOfCyprus** [comment]
Are you referring to the DB item description? Those are made by the community; we don't have direct access.

**Comment by BigHardHorns** [comment]
Oh ok. Are they editable by the community, ie if I retain the supporting documentation can I go in and edit that description, or should I speak to someone else about it?Thanks for seeing to this stuff, much appreciatedJustinSent from my iPhoneOn 8 Apr 2023, at 3:00 am, Ethan Hermanson ***@***.***> wrote:﻿
Are you referring to the DB item description? Those are made by the community; we don't have direct access.

**Comment by PygmalionOfCyprus** [comment]
Yeah, you can go make a suggestion in CV90's thread here: https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=373623

He's the guy in charge of that so he'll know what to do with it!
