### ISSUE TITLE
Please add MiG-21 for Mozambique

### ISSUE THREAD

**Issue by Mark-Gellis** [PygmalionOfCyprus/cmo-db-requests#3186]
### DB Selector

DB3K

### DBID to Copy

Aircraft #2060

### Hypothetical

No

### Name

MiG-21bis Fishbed L

### Country

Mozambique

### Service

Air Force

### In Commission

1982-present

### Number in Service

48 delivered; 18 in service in 1990; 8 currently in service

### Other Changes

I honestly don't know if the Mozambique aircraft is the Fishbed L or the Fishbed N, but one source says they were delivered from Cuba, and the ones listed for Cuba in the database is the Fishbed L, so that's why I suggested the L.  Apologies in advance if I'm wrong.  Apparently the only air-to-air victory for Mozambique Fishbeds was a South African UAV in 1983.  

### Sources

https://en.wikipedia.org/wiki/Mozambique_Air_Force
https://www.skytamer.com/MiG-21bis.html
https://www.jetphotos.com/photo/10890838

**Comment by FrangibleCover** [comment]
I can't find any images of a Mozambican MiG-21bis with the Polyot ILS antenna under the nose, so I agree that they are almost certainly Fishbed L interceptor variants.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
