### ISSUE TITLE
MIM-146A ADATS (1990)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#319]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 996 DB3K

### Summary of Changes

MIM-146A ADATS (air defense anti-tank system) is currently only anti-air. Should also be able to engage surface targets as.

### Sources

https://en.wikipedia.org/wiki/Air_Defense_Anti-Tank_System

https://man.fas.org/dod-101/sys/land/adats.htm

http://www.designation-systems.net/dusrm/m-146.html

https://www.designation-systems.net/dusrm/m-146.html

**Comment by PygmalionOfCyprus** [comment]
Slipped into 493. Also tweaked the ADATS system to better reflect real-world capabilities: made it laser-guided (instead of radar-guided), adjusted weapon warhead, tweaked radar/sensor stats, etc.
