### ISSUE TITLE
United Stated - IX-529 Sea Shadow

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3192]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

IX-529 Sea Shadow

### Class

IX-529 Sea Shadow

### Country

United States

### Service

Navy

### In Commission

1985-2006

### Number in Service

1x

### Length (m)

50 m

### Beam (m)

21 m

### Draft (m)

4.6 m

### Standard Displacement (t)

563 tons

### Full Displacement (t)

572 tons

### Empty Displacement (t)

499 tons

### Complement

4 normal (but with 12 Bunks)

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

2x Diesel-Electric, 2x Propellers

### Fuel Capacity (kg)

N/A

### Flank Speed (kt)

14.2 Knts

### Range (nm) at Speed (kt)

Not Stated

### Sensors

1x Navigation Radar

### Mounts

none

### Aircraft & Docking Facilities

none

### Comms/Datalinks

VHF/UHF

### Ship Codes

Dual or Triple Stabilizers, Catamaran/Trimaran Multihull

### Sources

https://en.wikipedia.org/wiki/Sea_Shadow_(IX-529)
https://www.nvr.navy.mil/SHIPDETAILS/SHIPSDETAIL_IX_529.HTML
https://vesselhistory.marad.dot.gov/ShipHistory/Detail/6432
https://www.militaryfactory.com/ships/detail.php?ship_id=Sea-Shadow-IX529
https://www.navysite.de/ships/shadow.htm
http://www.navsource.org/archives/09/46/46529.htm
http://www.hisutton.com/Lockheed-Sea-Shadow-Stealth-Ship.html

![image](https://user-images.githubusercontent.com/99599482/225352425-ead6a1ec-6f8a-4e5b-9b16-07a5e8c218d1.png)

**Comment by Jkryos** [comment]
Added DB3K 501.
