### ISSUE TITLE
Copy Aircraft #4553 MH-60R Seahawk (Norway) AF for Navy 2025 x 6

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3198]
### DB Selector

DB3K

### DBID to Copy

AIRCRAFT #4553

### Hypothetical

No

### Name

MH-60R Seahawk (Norway) 2025 x 6 

### Country

Norway

### Service

Navy operated by AF

### In Commission

2025 ish

### Number in Service

6

### Sensors

As Danish MH60R

### Mounts

Same as Danish but with:
Probably 12.7mm M3 pintle door mount capable as USN.

### Loadout Options

As Danish for ASuW, Troops cargo.
ASW Load  out TBC
Highly likely to be Mk-54? 
(Logistically MU-90 is in the inventory but would most likely not be cost effective for integration reasons and given Australias issues with the Mu-90 it seems unlikely?)
Linked request:
#3067 Request is for Danish MH-60R to be updated with Mk-54 and related sonar buoys from 2023.  

### Other Changes

Replaces NH-90

### Sources

https://www.regjeringen.no/en/aktuelt/styrker-forsvaret-med-kjop-av-nye-helikoptre/id2966519/
Norwegian Government etc

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
