### ISSUE TITLE
AN/ASQ-239 Missing From 2025 & 2028 USN F-35C

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#320]
### DB Selector

DB3K

### Affected DBID(s)

3836, 4874

### Summary of Changes

Confirmed by Dimitris offsite. AN/ASQ-239 was supposed to be presented in two USN F-35C entries, but it was missing in the game DB. 

ID: 3836 - F-35C Lightning II - 2025, 6x JATM, Block 3I/4, ESM

ID: 4874 - F-35C Lightning II - 2028, AARGM-ER, JATM

### Sources

![image](https://user-images.githubusercontent.com/99858862/154811366-44227cc2-3c52-45bb-a8d8-64d7d9fd795f.png)

Credit: Demitris

**Comment by PygmalionOfCyprus** [comment]
I took that screenshot.

You can literally see the AN/ASQ-239? It's right there. Sensor #1.

**Comment by PygmalionOfCyprus** [comment]
(Tentatively closing on account of there being no issue DB-side AFAIK, but if this turns out to be somehow wrong, I'll of course reopen it.)

**Comment by SolomonDread** [comment]
I forgot to include the in-game image here, the same screenshots that prompted other players and Dimitris to investigate in the game.

![Band2_5MissingASQ239](https://user-images.githubusercontent.com/99858862/154876525-ac6a4756-fc67-4909-baa3-760e1bccaa76.png)

And here is his confirmation. 

![Confirmation](https://user-images.githubusercontent.com/99858862/154876919-b0cf60d8-7eca-4ce8-ad86-6a714d96601a.PNG)

**Comment by PygmalionOfCyprus** [comment]
I don't doubt it's not showing up in-game, but I've got the DB open in front of me and I'm staring right at the thing.

This is certainly a bug of some kind. If I had to hazard a guess, I'd say it's probably triggered by some faulty value that's causing the engine to reject the sensor. But it's not a matter of it being "missing," at least not where the DB is concerned.

Can you post on the Tech Support thread in the MG forums with a save file? That'll generate a dev ticket.

**Comment by SolomonDread** [comment]
Sorry for not clarifying the issue well. But thank you for looking into it.

**Comment by PygmalionOfCyprus** [comment]
So, it turns out we were both right.

You're correct: the Barracuda is not on those F-35Cs as of 492. But they are on those F-35Cs as of my most recent version of the DB.

It appears that this issue was "ninja'd" at some point this cycle: namely, it got fixed, but without a ticket being filed and so I didn't realize that it had been dealt with (or that there was a problem at all). So, to make a long story short -- 493 will have the F-35's ESM back to working as expected!
