### ISSUE TITLE
AV-MTC 300 (Matador)

### ISSUE THREAD

**Issue by Potiguara69** [PygmalionOfCyprus/cmo-db-requests#3201]
### DB Selector

DB3K

### Affected DBID(s)

#4074

### Summary of Changes

O atual ranje de 162nm é apenas para a versão de exportção. A versão de uso proprio alcança 550nm.

Até este momento no database DB3k 498a, a unica plataforma capaz de carregar o AV-MTC é o Arty Bty (ASTROS II - Brazil 2016).
Solicito disponibilizar o carregamento também para:
 #2102 F-5EM Tiger II, (F-5BR /Brazil 2007),
 #2945 AMX (A-1M), (Brazil 2015),
 #5003 JAS 39F Gripen NG (Brazil 2021)
 #5004 JAS 39E Gripen NG (Brazil 2021)

### Sources

Planejamento da Força Aérea.
Avaliações do EB
https://www.avibras.com.br/site/en/

**Comment by PygmalionOfCyprus** [comment]
Can you give a specific link or citation where the 550nm range is mentioned?

**Comment by Potiguara69** [comment]
Em sex., 7 de abr. de 2023 às 15:03, Ethan Hermanson <
***@***.***> escreveu:

**Comment by Potiguara69** [comment]
Sorry for the delay in responding.
Unfortunately I didn't find written documents about the possible range
increase of the AV-MT-300.
However, there are some videos with interviews with the army officer
responsible for managing the project.
Here is a video with a summary of the missile and which points to a range
of 1000 KM.

https://youtu.be/ZB78c <https://youtu.be/ZB78cLleHhI>LleHhI
<https://youtu.be/ZB78cLleHhI>



Em sex., 7 de abr. de 2023 às 15:25, Leder Assumpcao <
***@***.***> escreveu:

**Comment by PygmalionOfCyprus** [comment]
I have created new ~2030 versions of the Brazilian Gripens w/ MICLA-BR loadouts. (The F-5s were already done.) I don't think it's going to be integrated on the AMX considering the age of the plane; if it is down the line we can always add the loadouts later, of course.

I am holding off on the 1000km number. I see your source and Wikipedia also "confirms" that the weapon is technically capable (with certain engines) of going >1000km; however, it's not clear that this capability is actually fielded or only theoretical.
