### ISSUE TITLE
SGDC - I, Satelite Geoestacionario Defesa Comunicação (Brasil 2017)

### ISSUE THREAD

**Issue by Potiguara69** [PygmalionOfCyprus/cmo-db-requests#3204]
### DB Selector

DB3K

### Hypothetical

No

### Series Name

SGDC - I

### Satellite Type

ELINT

### Country

Brazil

### Service

Força Aerea Brasileira

### In Commission

2017 até agora/Spacebuss-400

### Length (m)

2.5

### Width/Span (m)

2.5

### Height (m)

5

### Is Geostationary

Yes

### COSPAR ID

2017-023B

### Launch/Comm. & Decom./Deorbit Date(s)

In 05/04/2017// out 05/04/2035

### TLE

146321U 20171A 49824642 00000220

### Sensors

1 x Camera Visual de Satélite Generico (3ª Geração)
1 x SIGINT/ELINT de Satelite Generico 

### Comments

Osatelite faz orbita de polo Sul a polo note em cada ciclo, cobrindo toda America e o Oceano Atlantico e Parte da Africa Ocidental.

### Sources

https://pt.wikipedia.org/wiki/SGDC-1
https://www.gov.br/aeb/pt-br/programa-espacial-brasileiro/objetos-espaciais-brasileiros
https://www.fab.mil.br/noticias/mostra/35703/ESPA%C3%87O%20-%20Sat%C3%A9lite%20Geoestacion%C3%A1rio%20de%20Defesa%20e%20Comunica%C3%A7%C3%B5es%20Estrat%C3%A9gicas%20completa%203%20anos%20no%20espa%C3%A7o

**Comment by PygmalionOfCyprus** [comment]
Added 508 along with every single other satellite currently in orbit.
