### ISSUE TITLE
BMPT terminator

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#321]
### DB Selector

DB3K

### Hypothetical

No

### Name

BMPT terminator

### Facility Type

Armored

### Country

Russia

### Service

ARMY

### In Commission

2017

### Crew

5

### Dispersion Radius (m)

80m

### Sensors

1x Thermal camera
1x lwr
1x laser range finder

### Mounts

4x BMPT terminator

Each Armed with
 4x 9M120 Ataka atgm
2x 2a42 30mm cannons
2x ags-30 grenade launcher

### Comments

Armoured IFV based on T-72 chassis

### Sources

https://en.m.wikipedia.org/wiki/BMPT_Terminator

![images - 2022-02-20T054106 632](https://user-images.githubusercontent.com/99824301/154814518-7e786ada-e4e2-487f-8dbd-a3ea5a0aec45.jpeg)

**Comment by Jkryos** [comment]
Added DB3K 494.
