### ISSUE TITLE
US Cyclone Patrol Boats out of service date 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3210]
### DB Selector

DB3K

### Affected DBID(s)

2555

### Summary of Changes

Add an out-of-service date of 2023. Boo:(

### Sources

https://twitter.com/D__Mitch/status/1637729188231761921?cxt=HHwWgsC-7aCBsbotAAAA
https://news.usni.org/2021/02/18/navy-decommissions-3-cyclone-patrol-craft-looking-to-shelve-mark-vi-patrol-boat
https://seapowermagazine.org/navy-begins-retirement-of-cyclone-class-patrol-ships-without-replacement/

**Comment by tbrandon517** [comment]
Looks like 3x Cyclones transferred to Egypt.

https://www.navalnews.com/naval-news/2023/03/u-s-navy-transfers-three-patrol-craft-to-egyptian-navy/

**Comment by bostonmyk** [comment]
- a few awesome parts. 

https://twitter.com/D__Mitch/status/1639185226482974720/photo/1

**Comment by tbrandon517** [comment]
Additional units going to the Philippines 

https://www.navalnews.com/naval-news/2023/03/u-s-to-transfer-cyclone-class-patrol-ships-to-philippine-navy/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
