### ISSUE TITLE
B-21 Raider AAM and SDB Loadouts

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3216]
### DB Selector

DB3K

### User(s)

B-21 Raider

### Weapons Carried

If one assumes that the B-21 Raider carries roughly half the payload of the B-2, the following individual loadouts should be possible:

60-80 GBU-39 / GBU-53 SDBs..
24-48 AIM-120D AMRAAMs
24-48 AIM-260 JATMs

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

4000+ nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://www.thedrive.com/the-war-zone/the-b-21-raider-is-and-isnt-a-b-2-spirit-2-0

https://www.thedrive.com/the-war-zone/29690/b-21s-with-air-to-air-capabilities-drones-not-6th-gen-fighters-to-dominate-future-air-combat

**Comment by KushanGaming** [comment]
Done for DB501.
