### ISSUE TITLE
Add Chilean SAM Plt (Crotale 2000) 1982

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3218]
### DB Selector

DB3K

### DBID to Copy

1839

### Hypothetical

Yes

### Name

SAM Plt (Crotale 2000)

### Country

Chile

### Service

Airforce

### In Commission

1982

### Number in Service

x2

### Sensors

same

### Mounts

Same

### Loadout Options

Same

### Other Changes

no

### Sources

https://www.reddit.com/r/MilitaryPorn/comments/11vrs3a/first_chilean_air_force_crotale_unit_commanding/
https://en.wikipedia.org/wiki/Crotale_(missile)
Sipri 
     		2	Crotale	mobile SAM system	1981	1982	2	
     		(60)	R-440 Crotale	SAM	1981	1982	(60)

**Comment by Jkryos** [comment]
Added DB3K 500.
