### ISSUE TITLE
Add Chilean SAM Sec (Blowpipe MANPADS x4) 1982

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3219]
### DB Selector

DB3K

### DBID to Copy

3047

### Hypothetical

Yes

### Name

SAM Sec (Blowpipe MANPADS x4)

### Country

Chile

### Service

Army

### In Commission

1982

### Sensors

same

### Mounts

same

### Loadout Options

same

### Other Changes

same

### Sources

Sipri
48	Blowpipe	portable SAM	1982	1982	48	Deal incl also 8 launchers
(100)	Blowpipe	portable SAM	(1983)	1983	(100)	
(100)	Blowpipe	portable SAM	(1987)	1988	(100)

**Comment by Jkryos** [comment]
Added DB3K 500.
