### ISSUE TITLE
NSM/JSM load out for USAF F-35A from 2024 - initial small quantity

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3220]
### DB Selector

DB3K

### User(s)

USAF F-35A ( USN/USMC F-35C/B to follow?) 

### Weapons Carried
Copy existing Norwegian F-35A NSM/JSM loadouts across to USAF. 
Loadout DB3K 17598 & DB3K 17599

Internal
2 x NSM JSM? Internal
2 x AMRAAM Internal

External.
2 on pylons  plus 2 internal and 2 BVR AAM and 2 WVR AAM.
Combinations of same with drop tanks etc. Loadout DB3K 17598

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as internal NSM/JSM loadouts as Norwegian F-35A. 
Loadout DB3K 17598 & DB3K 17599

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

NSM/JSM Entry weapon 2885 may need to be appended or copied to create new weapon with new nomenclature AGM-184A NSM Block 1 to match terms for DB3K weapon 299?
Only 48 being procured in fiscal year 2024 for IOC in 2025. 
F-35B internal bay cannot carry it so USMC would be limited to external carriage.. 

### Sources

https://www.airrecognition.com/index.php/news/defense-aviation-news/2023-news-aviation-aerospace/march/8938-us-air-force-to-buy-jsm-cruise-missiles-to-arm-f-35-lightning-ii-fighters.html

https://www.defencetoday.com/air/air-weapons/us-air-force-to-buy-jsm-cruise-missiles-for-f-35-jets/

**Comment by Jkryos** [comment]
Added DB3K 501.
