### ISSUE TITLE
Copy #3432 - SAM Plt (SA-22 Greyhound [Pantsir-S2E]) (Serbia [1992-] - 2019) for Russia from 2016. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3223]
### DB Selector

DB3K

### DBID to Copy

Facility #3432

### Hypothetical

No

### Name

#3432 - SAM Plt (SA-22 Greyhound [Pantsir-S2]) (Russia [1992-] - 2016)

### Country

Russia

### Service

Air Force PVO

### In Commission

2016 some sources 2015

### Number in Service

Many but less than there were in January 2022

### Sensors

#6649 - SOT-S [1RS1-3E-RLM] twin faceted. 360 ARC - ROTATING 
#4618 - Generic IR Camera 3rd gen Weapon director and Target search track and ID. 360 ARC gimballed mount on turret roof
#2258 - Generic LLTV 3rd gen Weapon director and Target search track and ID. 360 ARC gimballed mount on turret roof

### Mounts

2 x SA-22 Greyhound [96K6 Pantsir-S2, KAMAZ-6560 8x8] TELAR (COPY AND AMEND S2 mount)

### Loadout Options

NOT APPLICABLE

### Other Changes

Reports indicate that this version also uses an improved missile interim between the 57S6 and 57S6ER with a 30km versus 20km range. 

This version is now probably more common than the S1. Even before the losses in Ukraine. 

### Sources

https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/pantsir-s2_short-range_cannon_missile_air_defense_system_technical_data_sheet_specifications_pictures_video_12205164.html
https://twitter.com/JonHallin/status/1583786150657142784/photo/1
The above tweet illustrates that the S1  is obviously different from the S2 from the radar layout. Both are in service.
https://twitter.com/muh_Alqahtani/status/484879858422390784?t=YROUfs3hwuVe7F1Ya4euZA&s=19
Despite the caption this is clearly an S2 with the pyramid radar and is enroute to Algeria.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
