### ISSUE TITLE
Chinese Type 37mm Type 65 Updates: Radar + Ammo stats

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3225]
### DB Selector

DB3K

### Affected DBID(s)

70

### Summary of Changes

Add fire control radar mount and links. See Jane's info below.

Adjust altitudes and range to Jane's states below

### Sources

FC radar info:  Jane's Land Based Air Defense 1992-93. pg. 166

_All the 37 mm towed systems can be coupled to a fire control radar. Known
as the Type 311 A. this uses a tour-wheel trailer van with an l/J-band
search, acquisition and tracking radar antenna on a roof-mounted pedestal.
The set operates on three preselected frequencies which can be manually
switched without any adjustments. Minimum and maximum ranges are 500
and 30 000 m respectively, against low radar cross-section fighter sized
targets with speeds of less than 550 m/s. An 8 t truck is needed to tow the
4 t trailer and this carries the ancillary equipment and the power supply
generator. The radar is also used with the 57 mm towed systems. Further
development of the Type 311 has led to the Type 31 1B and Type 31 1C
models. The Type 31 1B introduces an integral IFF system, increased
frequency coverage and a maximum detection range of 35 000 m using a
new antenna design. The Type 31 1C goes one stage further and has a
frequency agile capability radar with a maximum range of 40 000 m. The
minimum range stays the same in both cases._

Ammo Stats: pg. 165 (rounds are called T55)
Maximum slant range 8500 m 
Maximum firing altitude 6700 m 
Effective firing altitude 3000 m

(b) AP-T round will penetrate 40 mm armour at an angle of 30°
(c) AP/HE round will penetrate 25 mm of armour at an angle of 30°.

**Comment by Jkryos** [comment]
Updated DB3K 506.
