### ISSUE TITLE
Updated North Korean SA-5 Info

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3226]
### DB Selector

DB3K

### Affected DBID(s)

Facility 473

### Summary of Changes

Update in service to 1987
Add 2x Barlock A/B (1 for every 6 launchers)
Replace Tall King with Big Back. 

### Sources

Jane's Land Based Air Defense 1992-93.  pg. 263-265

IOC stuff:
_In late 1987 North Korea took delivery of SA-5 systems for use in the
Korean People's Air Force (KPAF) Air Defence Command.
The first SA-5 regiment of two six-launcher battalions was deployed to
the Sarlwon-Pyonsan area, some 40-100 km north of the DMZ, with the
second regiment located on the east coast in the Wonsang-Hamhung
region. Both units can reach into the northern sectors of South Korea's
airspace threatening both AWACS aircraft and strategic stand-off
reconnaissance assets like the Lockheed TR-1/U-2R and Boeing RC-135
ELINT/COMINT aircraft._

Batallion make up:
_The HQ unit of an S-200 Regiment has a radar section with a single NATO
designation Big Back L-band 500 km range plus early warning radar.
Each missile battalion has one P-35M (NATO designation Barlock-B)
E/F-band 320 km range target search and acquisition radar with an integral
D-band IFF system, one H-band NATO designation Square Pair 270 km
range missile guidance radar, and six trainable semi-fixed single rail
launchers._

**Comment by bostonmyk** [comment]
Further IOC evidence

http://geimint.blogspot.com/2010/06/north-korean-sam-network.html

_There are currently two active S-200 sites inside of the DPRK. These sites are placed near the east and west coasts in the southern portion of the nation, allowing them to range far offshore and deep into the ROK. The S-200 represents the longest-range strategic SAM system in the DPRK's arsenal. Four S-200 batteries were supplied to the DPRK between 1987 and 1988, and two batteries are likely co-located at each location_

**Comment by PavelNovak79** [comment]
If you anybody can get through Russian language there is list of soviet export of some type of SAMs including number of missiles, radar and IADS systems during Cold war:
http://historykpvo.narod2.ru/
- specifically these:
             Поставки СССР имущества ПВО страны за рубеж  (по странам): http://[поставки1.djvu.html](http://narod.ru/disk/29272530001/%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B81.djvu.html)

             Поставки СССР имущества ПВО страны за рубеж  (по видам вооружения): ﻿http://[поставки -2.djvu.html](http://narod.ru/disk/30564757001/%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B8%20-2.djvu.html)
- this one is better because it has data till 1991 while the previous one has data only till 1988/89

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
