### ISSUE TITLE
Add Argentine, India, Jordanian, Kenyan and Qatari Tigercat SAM Batteries

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3229]
### DB Selector

DB3K

### DBID to Copy

12

### Hypothetical

No

### Name

SAM Plt (Tigercat)

### Country

Argentina, India, Jordan, Kenya and Qatar

### Service

Argentina (Army, Marines), India (Army), Iran (Airforce), Kenya (Airforce), Qatar (Airforce)

### In Commission

Argentina 1971, India 1974, Jordan 1971, Kenya 1978 (Not used into 87 see Jane's' note), Qatar 1970

### Number in Service

Argentina 10 (Army, Marine Corps), India 40, Iran 15, Kenya 1, Qatar 1

### Sensors

Same with exception of Kenyan Version. See below

### Mounts

Same. Except Kenyan version has a van with l/J-band Marconi S860 radar, tv camera and better FC. See below. 

### Loadout Options

Same

### Sources

Sipri Lines
Argentina: (250)	Seacat	SAM	1968	1970-1971	(250)	Tigercat version
India: 40	Tigercat	SAM system	1971	1972-1974	(40)	Part of $10.4 m deal
Jordan: Jordan	(555)	Seacat	SAM	(1969)	1970-1971	(555)	Part of $16 m deal (financed by Saudi Arabia); Tigercat version
Qatar: (75)	Seacat	SAM	1970	1970	(75)	Part of $1.4 m deal; Tigercat version

Jane's Air Defense Weapons Systems 1992-93 pg. 272

_* Note: These Kenyan missile systems were supplied in kit form in 1978.
stored and not assembled and checked until early 1987. First trial firings
were successfully completed from 18 to 28 May 1987._

Kenyan Version
_As far as is known only one export customer. Kenya, has the all-weather
Radar Enhanced Mk 2 Tigercat version which uses the Marconi ST850/M
radar with its associated TV system. The ST850/M is mounted in a fully
enclosed mobile cabin and could also be integrated with the l/J-band
Marconi S860 mobile surveillance radar.
The ST850/M gives Tigercat an all-weather capability as well as enhancing
the clear weather performance via a TV auto-gather facility. In conditions
where the missile is visible, it is automatically gathered within a few
seconds of launch after which the engagement is completed automatically
or manually using the TV monitor
The radar may assume control of either of two Tigercat units, providing
fully automatic control of the channel while the second channel reverts to
optical control.
The fully enclosed cabin is air-conditioned with the director mounted on
the roof. This carries a 1 m diameter antenna and the TV camera and
covers an elevation arc from -25 to +85 ._

**Comment by bostonmyk** [comment]
850 4 Targets
860 20km range

Marconi Data Sheet
https://themarconifamily.pbworks.com/w/file/fetch/108790666/1979%20Radar%20-%20Section%203.pdf
https://marconiradarhistory.pbworks.com/w/file/fetch/89794991/800%20Series%20X-Band%20Weapon%20Radar%20systems.pdf

**Comment by FrangibleCover** [comment]
At least 7 Argentinian fire units captured in the Falklands, possible OOS 1982?

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
