### ISSUE TITLE
Add Malaysian Marconi S-600 Radar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3230]
### DB Selector

DB3K

### DBID to Copy

Facility 930

### Hypothetical

No

### Name

S-600

### Country

Malaysia

### Service

Air Force

### In Commission

1971

### Number in Service

x3

### Sensors

Same

### Mounts

Same

### Loadout Options

Same

### Sources

Jane's Air Defnse Systems 1992-93 pg. 12 

_With the withdrawal of the UK forces from the Far East in 1971, the Malaysian Government procured three Marconi S600 mobile radar units to meet the country's immediate needs and support the RAAF detachment of rotated F-18 aircraft through the base._

https://marconiradarhistory.pbworks.com/w/page/30050230/S600%20radar

Sipri Line
2	S-600	air search radar	(1969)	1971-1972	(2)	'Malaysia' project; S-654 or S-605 version; incl for civilian air traffic control

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
