### ISSUE TITLE
Add Japan SSM Coy (Type12 SSM Capacity Improvement Type)

### ISSUE THREAD

**Issue by Taiga157654** [PygmalionOfCyprus/cmo-db-requests#3232]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Coy (12SSM KAI Capacity Improvement Type)

### Facility Type

SSM

### Country

Japan

### Service

Ground Self-Defense Force

### In Commission

2025-

### Dispersion Radius (m)

40

### Sensors

Mk1 Eyeball

### Mounts

3x Type12 SSM Capacity Improvement Type

### Magazines

18x Type12 SSM Capacity Improvement Type

### Comments

Stealth cruise missile launcher based on the 12SSM, development of which began in 2020. Most of the systems other than the missile are shared with the 12SSM.

### Sources

-Japan starts to extend range of its missiles to over 1,000 km; https://asia.nikkei.com/Politics/Japan-starts-to-extend-range-of-its-missiles-to-over-1-000-km
-Current Status of Type 12 Surface-to-Ship Guided Missile (Improved Capability Type) Development; http://tokyoexpress.info/2022/08/15/12%E5%BC%8F%E5%9C%B0%E5%AF%BE%E8%89%A6%E8%AA%98%E5%B0%8E%E5%BC%BE%EF%BC%88%E8%83%BD%E5%8A%9B%E5%90%91%E4%B8%8A%E5%9E%8B%EF%BC%89%E9%96%8B%E7%99%BA%E3%81%AE%E7%8F%BE%E6%B3%81/
-2022 White Paper on Defense Technology [58.2MB], Part IV: Defense Equipment and Technology Policies, 439 pages; https://www.mod.go.jp/j/approach/agenda/guideline/plan/pdf/plan.pdf
-Order and 4 years defense white paper "12 types of ground opposing ship induced elasmobar capability up type (reference data); https://www.mod.go.jp/j/approach/hyouka/rev_suishin/r04/pdf/r04_sankousiryou_01.pdf

**Comment by Jkryos** [comment]
Added DB3K 501.
