### ISSUE TITLE
Agusta A-109 Various Entries - Sensor issues load outs and max speed for type in general. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3234]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #1111 #4483 #1462 #4762 #1485 #2992 #5138

### Summary of Changes

All the below entries have a FLIR when IRL they did not / do not. Remove FLIR Please. 
A lot of users kept these simple and relatively "cheap" to operate. 
The max speed in the DB on military is 140kts - IRL max speed is generally given as being in the region of 154kts. 
DB propulsion entry for 2x 250-C20R/1 and 2x PW206C

#1111 - A-109 Agusta (Argentina - 1980) - Mk1 eyeball only no FLIR. 
https://desarrolloydefensa.blogspot.com/2008/04/el-helicptero-agusta-109-hirundo.html 
Image used in DB3k also shows both a rocket pod and 7.62mm gun pod in use simultaneously?

#4483 - A-109LUH Agusta (South Africa - 2004) - Mk1 eyeball only no FLIR. 
https://www.airliners.net/photo/South-Africa-Air-Force/Agusta-A-109E-LUH/368488 
No FLIR But also shows it with a gun pod suspected 20mm and winch for SAR missions.

#1462 - A-109K2 Agusta (Peru - 1991) - Mk1 eyeball only no FLIR.  
15 Feb 2017 https://youtu.be/i_-d3ZIjQAo

#4762 - Agusta A-109E Power (Australia - 2008) - Mk1 eyeball only no FLIR. Out of service 2012? Replaced Bell 429. 
https://www.navy.gov.au/aircraft/agusta-a109e-power

#1485 - A-109EOA Agusta [MRH-109A] (Italy - 1990) - Mk1 eyeball no FLIR. 
https://cdn.planespotters.net/07986/mm81238-esercito-italiano-italian-army-agusta-a-109eoa_PlanespottersNet_1144094_527aefe735_o.jpg

#2992 - A-109BA Agusta [HO, Scout] (Belgium - 1994) Out of service 2020. No FLIR. 
https://www.aviation24.be/military-aircraft/belgian-air-component/last-flight-of-belgian-air-force-agusta-a109-helicopter-h22-to-its-future-home-at-vloc/

#5138 - A-109LUH Agusta (New Zealand - 2008) No FLIR. Does have NVG compatible cockpit and winch for SAR mission which is listed in NZ government official site as a role for the type. Please add SAR  LOAD OUT
https://www.nzdf.mil.nz/nzdf/our-equipment/aircraft/a109-light-utility-helicopter/

### Sources

Attached to entries above. I have checked a lot of images of each type and cannot see any FLIR type appendages in addition to checks on official websites and blogs.

This is a would like to have as always.

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
