### ISSUE TITLE
Add Agusta A-109LUH / AW-109M (Nigeria - 2018) x 6 AF and 2 Navy(?)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3235]
### DB Selector

DB3K

### DBID to Copy

Aircraft #4483 A-109LUH Agusta (South Africa - 2004)

### Hypothetical

No

### Name

A-109LUH Agusta (Nigeria - 2018)

### Country

Nigeria

### Service

Army and Navy

### In Commission

2018 ordered

### Number in Service

6 -1 one lost in crash

### Sensors

In majority of images the Army A-109 do not appear to have any FLIR sensor etc 
The Navy A-109 at least one has a FLIR type sensor at the nose but most images do not show any FLIR at delivery. 
They are NVG compatible cockpits and Nigeria has pilot type NVG.
Basic bomb sight for gun pods and rockets.
Navy version appears to have winch for SAR in some images. 

### Mounts

Army variant probably has facility for one or two pintle 7.62mm guns but with loss of passenger space.
M3 12.7mm HMG Starboard passenger door pintle mount option but not typically fitted. 

### Loadout Options

As loadout #25896 - Combined Hydra 70mm rocket and 12.7mm gun pod forward facing fixed. Appears to be FN RMP gun pod x2. 
Also 2 x 7rnd 70mm rocket pods. 
Also load out #25898 - used for SAR in naval configuration AND probably CSAR by army. 
Cargo copy #22664 1 ton air drop
Troops  4x Copy #22665
Gun loadout? Starboard door pintle mount M3 12.7mm.
### Other Changes

These were the last Leonardo A-109LUH/E 

### Sources

https://www.africanmilitaryblog.com/2019/05/nigerian-air-force-acquires-two-agusta-a109-power-light-attack-helicopters/
https://www.military.africa/2018/12/nigerian-air-force-orders-six-leonardo-aw109-helicopters/
http://www.combataircraft.com/aircraft/ha109_p_01_l.jpg This image of a NAVY A-109 Appears to have a small FLIR/EO turret sensor at the nose.  
https://fnamerica.com/products/fn-airborne-pod-systems/fn-rmp/
https://twitter.com/HammerOfWar5/status/1641127512678842386?t=xdjfx97LN-rQszsm5DeevQ&s=19
7 round 70mm RP x 2.

**Comment by KLABDB3K** [comment]
Checking SIPRI DB and think the total is 6 with 4 AF and 2 Navy? Less one which crashed which is an AF/Army version. These are referred to as AW.109M using the new nomenclature since a rebranding by Agusta Westland but appear largerly A.109LUH's..

**Comment by KLABDB3K** [comment]
https://twitter.com/milnewsng/status/1645738460773244934?t=KxgsBbI7WRHsHb6EUDBfUA&s=19

Seems the AW-109 is more common name now amd one Stbd cabin mounted M3 HMG on pintle. Not much cargo space left.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
