### ISSUE TITLE
Atlas Oryx EW Helicopters (2 Versions) - South Africa

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#3237]
### DB Selector

DB3K

### DBID to Copy

6067

### Hypothetical

No

### Name

AS.332 Super Puma [Oryx] -- South Africa (Army), 2000, OECM/ELINT
AS.332 Super Puma [Oryx] -- South Africa (Army), 2000, COMJAM/COMINT

### Country

South Africa

### Service

2000

### In Commission

2000-present

### Number in Service

4 (COMINT/COMJAM), 4 (ELINT/ECM)

### Sensors

1x Oryx Stand-Off Jammer [ELINT]
1x Oryx Stand-Off Jammer [ECM]

-----------------------------
1x GSY-1501 [COMINT]
1x GSY-1501 [COMJAM]

### Other Changes

I'm unsure wether the COMINT and ELINT variants are actually the same helicopter. Supposedly there is only one helicopter of this type, but in one picture there seems to be a conformal antenna where the door is supposed to be. On the other hand there are some pictures where 1208 is used in a transport configuration.

### Sources

https://www.saairforce.co.za/gallery-and-media/44/oryx#

> Oryx 1208 of 17 Squadron configured for EW missions in 2000.

![Oryx EW](https://user-images.githubusercontent.com/104227721/227743211-9f0c8121-4fa8-446c-a53c-2c19dbd6b51b.jpg)

![Oryx EW 2](https://user-images.githubusercontent.com/104227721/227743342-d94d9140-a269-4ba0-a258-ca05d38375e9.jpg)

![image006](https://user-images.githubusercontent.com/104227721/227743220-ef3744a2-48e2-44aa-832c-b8daa0c03a94.jpg)

https://www.saairforce.co.za/seed/public/files/gallery/3/10/44/4634a44451bf2_large.jpg

http://skycam-aviation-photography.blogspot.com/2012/11/unique-saaf-atlas-oryx-spotted-in-cape.html

https://www.airforce-technology.com/projects/atlas-oryx/

https://www.defenceweb.co.za/joint/science-a-defence-technology/grintek-ewation-wins-major-ew-maintenance-deal/

http://www.saairforce.co.za/news-and-events/900/saaf-investing-in-ew

https://www.saairforce.co.za/news-and-events/812/tenders-awarded-during-august-2009

https://www.sysdel.co.za/Prior_Del_4.htm

(you have to zoom in to see the text)

> STAND OFF JAMMER
Helicopter deployed high power stand-off jammer using mechanically steered phased array. Integrated with ESM system for power managed spot and barrage jamming of multiple radars. DRFM (Digital RF Memory Loop) deception techniques optional.

**Comment by nuk92** [comment]
#3238

**Comment by nuk92** [comment]
Found another source:

https://www.saairforce.co.za/news-and-events/627/south-africa-lifts-lid-on-oryx-special-mission-platforms

> The South African Air Force (SAAF) has displayed for the first time two Denel Oryx helicopters, separately fitted as communications interception (COMINT) and jammer platforms.
The jammer aircraft is fitted with twin flat antenna arrays mounted sideways across the cabin on a steerable platform supported on air-cushion bearings. The main jammer array operates in L-band with the secondary array in S-band. The helicopter's side doors have been replaced by sliding blisters enabling steering of the antenna across an arc of around 110¹.
A steerable electronic support measures (ESM) antenna is located beneath the rear fuselage on a mechanically retractable mount. The rear of the cabin houses a twin operator console supporting separate ESM and techniques roles.
The COMINT Oryx features a Grintek-developed fold-away dipolar antenna array projecting from the starboard side of the aircraft with a palletised signals processing and analysis suite fitted into the cabin. The system has a single operator.
The Oryx jammer is primarily designed to support strike operations against enemy air defence sites by SAAF Denel Cheetah fighters. An initial version was probably in operational service during the final twelve months of operations against Angola in 1989.
The proposed upgrade programme will see the introduction of digital RF memory based signals processing and to provide improved performance against low probability of intercept radar emitters. The upgrade will also introduce a co-processing capability to handle more sophisticated signals environments.
The SAAF has only one Oryx fitted with the jammer suite, but the upgrade may see additional aircraft converted. According to the chief of the SAAF, Lt Gen Roelf Beukes: "We are looking at a certain number for specialised roles only and that programme is well on its way."

**Comment by PygmalionOfCyprus** [comment]
Handled 501. I'm using 1989 as an in-service data because of the line about initial versions being used in 1989.
