### ISSUE TITLE
GSY-1501 COMINT / COMJAM

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#3238]
### DB Selector

DB3K

### Hypothetical

No

### Name

GSY-1501 [COMINT] & GSY-1501 [COMJAM]

### Sensor Generation

Early 1990s

### Range (nm)

500

### Sensor Capabilities

Air Search, Surface Search

### Search/Track Frequencies

A Band (30-250 MHz) [Old P Band (HF)] 100-300 cm, B Band (250-500 MHz) [Old P Band (VHF)] 60-100 cm, C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm

### Lower Frequency (Hz)

20,000,000 (COMINT) / 20,000,000 (COMJAM)

### Upper Frequency (Hz)

1,000,000,000 (COMINT) / 500,000,000 (COMJAM)

### Scan Interval (s)

20

### Peak Power (W)

1000 (COMJAM)

### Comments

Request for 2 sensors

COMINT:
1.5° accuracy
direction finding sensor code

COMJAM:
ECM targets: 3
1kW

### Sources

https://www.avcom.co.za/phpBB3/viewtopic.php?t=104692

> An electronic warfare version equipped with Grinaker systems Technologies (GST) and GSY 1501 jamming systems is one variant of the helicopter. The EW platform can interrupt communication during air, land and sea battles. Another variant of the Oryx featured dome shaped antennas which were substituted for the main cabin door.

> The system provides full COMINT/EW capability from detection and interception, through direction finding and recording, to disruption by deception or jamming. It covers the frequency spectrum from 20-1000Mhz, with optional extension to 1.45Mhz,and can be used against voice and data links. DSP techniques are used to perform noise-riding signal detection for rapid scanning with a high probability of detection.

https://archive.org/details/janesavionics1990000unse/page/284/mode/2up

**Comment by PygmalionOfCyprus** [comment]
Handled 501. I've used some of the values for COMINT from the other source you indicated which was a bit more explicit as to the system used on the Oryxes: https://dziennikzbrojny.pl/artykuly/art,6,27,1658,lotnictwo,smiglowce,od-pumy-do-caracala-czi-a
