### ISSUE TITLE
RCN R 31 HMCS Warrior

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#324]
### DB Selector

CWDB

### DBID to Copy

444 CWDB

### Hypothetical

No

### Name

R 31 HMCS Warrior [Colossus Class] 

### Country

Canada

### Service

Royal Canadian Navy

### In Commission

1946-48

### Sources

http://www.hazegray.org/navhist/canada/postwar/carriers/
https://en.wikipedia.org/wiki/1942_Design_Light_Fleet_Carrier#Ships
https://readyayeready.com/ships/shipview.php?id=145

![warrior](https://user-images.githubusercontent.com/99632305/154828833-f24adb87-de91-42cf-8407-352f17e30c7c.jpg)
9

**Comment by Jkryos** [comment]
Added CWDB 494.
