### ISSUE TITLE
Starstreak II change - capability to engage guided weapons/suicide drones

### ISSUE THREAD

**Issue by Anon9944** [PygmalionOfCyprus/cmo-db-requests#3241]
**DB Selector**
DB3K

**Affected DBID(s)**
Weapon 2241

**Summary of Changes**
Starstreak II should be capable of engaging guided weapons/drones e.g. Shahed 136 (Weapon 4142)
Starstreak II is already capable of engaging the similar in size and speed Orlan-10 (Aircraft 5809)

**Sources**
https://twitter.com/UAWeapons/status/1558411984479158274?s=20
https://twitter.com/UAWeapons/status/1587795318799835136?s=20

**Comment by Jkryos** [comment]
Updated DB3K 501.
