### ISSUE TITLE
Amendment #6365 - Calidus B-250 (UAE - 2019) Guns only loadout but no guns??

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3243]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #6365 - Calidus B-250 (UAE - 2019)

### Summary of Changes

#6365 - Calidus B-250 (UAE - 2019)

Has load out 32494 Internal Guns
(Guns Only) -- but the Calidus does not have any mounts - so no internal guns?
Plus the loadout has just drop tanks. 
Is this a left over from the A-29 being copied perhaps?

Please amend. (Spent some time wondering why it wasnt attacking anything!)
There are photos with gun pods and drop tanks, will keep checking what calibre weapon but it appears at least 20mm, but loadout title needs to be altered and 2 x 20mm cannon pods added? 

### Sources

DB499 

http://www.novaer.ind.br/b-250/ Design team web site. No guns.

**Comment by PygmalionOfCyprus** [comment]
Yeah, that was def. supposed to be a gun pod loadout. Whoops. Handled 500.
