### ISSUE TITLE
Global 6500

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#3244]
### DB Selector

DB3K

### Baseline

4946

### Hypothetical

No

### Name

Global 6500

### Country

None

### Service

Commercial

### In Commission

2020-

### Length (m)

30.3

### Wingspan (m)

28.7

### Height (m)

7.8

### Empty Weight (kg)

23691

### Maximum Takeoff Weight (MTOW) (kg)

45132

### Payload Weight (kg)

2617

### Crew

4

### Propulsion

2x BR700-710D5-21

### Service Ceiling (ft)

51000

### Military/Afterburner Speed (kt)

600

### Cruise Speed (kt)

566

### Supercruise

No

### Ferry Range (nm)

6600nm

### Takeoff / Landing Distance (m)

1942/681

### Fuel Capacity (kg)

20434

### Sensors

- 1x mk1 Eyeball
- 1x MultiScan Weather radar

### Mounts

- Passengers/Cargo

### Loadout Options

- Passengers x17

### Comms/Datalinks

- UHF/VHF Radio (unsecure)
- SATCOM (commercial)

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Sources

https://businessaircraft.bombardier.com/en/aircraft/global-6500#bba-pdp-section-5
https://en.wikipedia.org/wiki/Bombardier_Global_Express#Specifications

https://businessaircraft.bombardier.com/sites/default/files/styles/retina_1060x750/public/2020-10/Global_6500_range_0.jpg?itok=TSTxrfIY

**Comment by Jkryos** [comment]
Added DB3K 501.
