### ISSUE TITLE
MHTK Dimensions

### ISSUE THREAD

**Issue by blu3ser** [PygmalionOfCyprus/cmo-db-requests#3247]
### DB Selector

DB3K

### Affected DBID(s)

Weapons 3504

### Summary of Changes

Looking at this model I notice it has an unusual RCS for his size. Looking through wikipedia specs, there's a little variation that fits better with his RCS:

Length = 0.76m
Span = 0.071m
Diameter = 0.041m
Weight = 2.2 Kg

### Sources

https://en.wikipedia.org/wiki/Miniature_Hit-to-Kill_Missile
https://news.lockheedmartin.com/2018-06-13-Lockheed-Martins-Miniature-Hit-to-Kill-Interceptor-Matures-to-Development-Stage

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
