### ISSUE TITLE
Copy - Aircraft #4069 to create AS 532A2 Cougar (Combat Search and Rescue Helicopter) Saudi Arabia x 12 (1998)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3248]
### DB Selector

DB3K

### DBID to Copy

Aircraft #4069 - AS.532U2 Cougar Mk2 (Netherlands - 1996)

### Hypothetical

No

### Name

AS.532A2 Cougar (Saudi Arabia - 1998) x 12 AF CSAR

### Country

Kingdom of Saudi Arabia

### Service

Air Force

### In Commission

1998 to present

### Number in Service

12

### Sensors

NVG compatible cockpit. 
Sensor #4833 - Euroflir 350 EOS Tri-Sensor Turret [FLIR/CCD/Laser Rangefinder] 360*
Sensor #1916 - Generic Navigation Radar
Sensor #4991 - Sherloc-SF
Sensor #4992 - MWS-20 Damien MAWS

### Mounts

2 x Mount #439 - 7.62mm MAG-58M MG Burst [20 rnds] Pintle door mount. 
1x Alkan Elips-NG x 2 [72 Cartridges]

### Loadout Options

Copy Load outs...
#20190 1 x Cargo air drop 3 tons.
#20192 4.5 ton cargo
#20193 CSAR
#20194 SAR
#20191 Troops

e.g 2 x 20mm cannon pods. 2 x 70mm Hydra pods each of 19 rounds.

### Other Changes

This has been extensively used in CSAR missions in the Yemen. 
Also in service with 
French Army, 
Bulgarian Air Force, 
Slovenian Army, 
Saudi Arabia and Turkey armed forces. Will request these in due course. 

### Sources

https://www.airforce-technology.com/projects/as532-cougar-helicopter/#as%20532%20Cougar%20Csar%20Helciopter%20Orders%20and%20Deliveries
Good synopsis. 
From SIPRI arms transfer database as follows:
12	AS-532U2 Cougar	transport helicopter	1996	1998-2001	12	$508 m 'Al Fahd'; armed AS-532A2 CSAR version

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
