### ISSUE TITLE
Multiple issues with the #6028 - AS.532UL Cougar Horizon (Turkey - 0) Never used by Turkey or Zimbabwe!

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3249]
### DB Selector

DB3K

### Affected DBID(s)

#6028 - AS.532UL Cougar Horizon (Turkey - 0) #5763 - AS.532UL Cougar Horizon (Zimbabwe - 1995) #6059 - AS.532UL Cougar Mk1 [TH98] (Switzerland - 2001) 

### Summary of Changes

Multiple Issues with the AS.532UL Cougar Horizon - Turkey Zimbabwe 

Small Issue with the Swiss AS.532UL is just a change to its type.
#6059 - AS.532UL Cougar Mk1 [TH98] (Switzerland - 2001)

For all versions
Change Type: to Transport (WRA: Helicopter - Unspecified)  
The existing Type: Area Surveillance (WRA: Helicopter - Unspecified)  is wrong. 

Turkey 
#6028 - AS.532UL Cougar Horizon (Turkey - 0) 
**Turkiye has never used the Horizon battlefield surveillance radar version.**
Rename the entry to #6028 AS.532UL Cougar (Turkiye/Turkey) x 50 1997
As Turkey does use the AS-532UL Cougar and the AL version- 
Phoenix 2 program meant 28 produced in Turkiye including 18 AS-532UL SAR and 6 AS-532AL CSAR Armed versions* will make seperate request for 532AL.
Remove all sensors and add #1487 - AN/ALQ-144 - the DB image shows these are prominent along the dorsal fairing. 
The Turkish UL should also have the same load outs as the Swiss version including SAR. 

Change - over-wright the Horizon version with the AS-532UL unarmed transport version details are as copy #6059 - AS.532UL Cougar Mk1 [TH98] (Switzerland - 2001)

Zimbabwe
#5763 - AS.532UL Cougar Horizon (Zimbabwe - 1995) likewise Horizon was never used by Zimbabwe, it could barely maintain in a serviceable condition the basic transport unarmed version.
Rename to #5763 AS.532UL Cougar (Zimbabwe) x 2 1995 copy details from Swiss Mk1 version but keep VIP load out. 

### Sources

https://www.airforce-technology.com/projects/as532-horizon-helicopter/
French Horizons retired in 2008 - the only operator of the system. 
SIPRI DATABASE from 1990 to 2022 shows NO Turkiye deliveries of the Horizon system or to Zimbabwe - this appears to be that the wrong version of the Cougar (Alias Super Puma) has been copied over. 

The image used in the DB 499 is of the Turkish AF AS.532UL unarmed transport version. 

The Horizon radar is a very obvious large hanging object which descended below the air frame and was a complex service and support intensive bit of kit.  Images used in the DB itself are of the basic UL transport version -not Horizon version.

**Comment by KLABDB3K** [comment]
I noticed this during a scenario, think it was Aegean in Flames, the Cougar is the go to CSAR SAR asset for Turkey and its not accurately represented in the Sim. 
If the error with the Horizon radar is present and as its in a scenario it may be easier to over wright than delete and add a new version?

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
