### ISSUE TITLE
RCN Cape Class x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#325]
### DB Selector

CWDB

### DBID to Copy

539

### Hypothetical

No

### Name

100 HMCS Cape Breton

### Country

Canada

### Service

Royal Canadian Navy

### In Commission

1959-70

### Other Changes

1x Helicopter Landing Pad (Medium Aircraft 12.1-18m)

### Sources

http://www.hazegray.org/navhist/canada/postwar/cape/
https://readyayeready.com/ships/shipview.php?id=1064
https://readyayeready.com/ships/shipview.php?id=1063
https://en.wikipedia.org/wiki/Cape-class_maintenance_ship

![capebreton](https://user-images.githubusercontent.com/99632305/154829023-ceae094f-8cca-420c-90fb-253525425db9.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
