### ISSUE TITLE
#6059 - AS.532UL Cougar Mk1 [TH98] (Switzerland - 2001) change type to Transport - then use as template to update other AS.532UL's?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3250]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #6059 - AS.532UL Cougar Mk1 [TH98] (Switzerland - 2001)

### Summary of Changes

Currently showing as Type: Area Surveillance (WRA: Helicopter - Unspecified)  

Should be Type: Transport (WRA: Helicopter - Unspecified)

With the new prioritisation feature for weapons handling this becomes more relevant - not just me being picky. Sorry.  

### Sources

DB499 Uses image of basic transport AS.532UL NO Surveillance capability etc.

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
