### ISSUE TITLE
Copy Aircraft #4069 -to create AS 532AL Cougar (Combat Search and Rescue Helicopter) Turkey / Turkiye x 6 (2000)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3251]
### DB Selector

DB3K

### DBID to Copy

Aircraft #4069 - AS.532U2 Cougar Mk2 (Netherlands - 1996)

### Hypothetical

No

### Name

AS 532AL Cougar (Combat Search and Rescue Helicopter) Turkey / Turkiye x 6 (2000)

### Country

Turkey

### Service

Air Force

### In Commission

ordered 1997 in service 2000

### Number in Service

6 of CSAR version

### Sensors

#4833 - Euroflir 350 EOS Tri-Sensor Turret [FLIR/CCD/Laser Rangefinder] but copying existing sensors from NL Cougar Mk2 would give same functionality including the generic MAWS and RWR. 

### Mounts

Keep existing CHAFF FLARE dispenser. 1x Alkan Elips x 2 [72 Cartridges]
2x 7.62mm MG [400 rnds]

### Loadout Options

Copy load outs from NL Cougar.
Load out
#20190 Cargo 3t
#20192 Cargo 4.5t
#20191 Troops x 20
#20193 CSAR RP and 20mm gun pods.
#20194 SAR Unarmed

### Other Changes

6 procured. 

### Sources

https://www.airforce-technology.com/projects/as532-cougar-helicopter/#as%20532%20Cougar%20Csar%20Helciopter%20Orders%20and%20Deliveries

SIPRI DB search transfers 1990 to 2022 All world to Turkiye.
https://armstrade.sipri.org/armstrade/page/trade_register.php

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
