### ISSUE TITLE
DB3000 v499 Wrong ship armaments

### ISSUE THREAD

**Issue by Nite920** [PygmalionOfCyprus/cmo-db-requests#3253]
### DB Selector

DB3K

### Affected DBID(s)

Ships #1145 and #1120

### Summary of Changes

Both are former Fletcher class destroyers and have the wrong main guns assigned to them. They both have the 127mm/38 Mk12 Twin mounts, when they should have the 127mm/38 Mk30 single mounts.

### Sources

Other former Fletcher class destroyers in the DB itself.  
https://en.wikipedia.org/wiki/Fletcher-class_destroyer
https://destroyerhistory.org/fletcherclass/arm_5/
https://en.wikipedia.org/wiki/Zerst%C3%B6rer_1-class_destroyer
Combat Fleets of the World 1980/1981 edition pg 172

**Comment by PygmalionOfCyprus** [comment]
Handled 500.

**Comment by Nite920** [comment]
Awesome.  Thank you!
