### ISSUE TITLE
Fiddling with SAR 511 Arun-class lifeboat

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3254]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3978

### Summary of Changes

The ship is rated up to Sea State 6, the same as most other vessels in the game. She's a self-righting all-weather lifeboat designed to go out into conditions where most other vessels are foundering and save the crews. I'm not sure if Sea State does anything yet but the weather modelling is improving all the time and it will eventually.

She's also rated 33 tons and 13 DP, minus 20% for GRP construction. The Dabur-class PB of 25 tons is also 13 DP. I would suggest that the deliberately very survivable design, full of watertight compartments and redundant equipment, should give her greater survivability for her tonnage than other boats.

Troop/Cargo Capacity is not listed anywhere I can find, but from the Arun design's slightly larger successor, the Severn, having a capacity of 47 with self-righting, I'm going to guess about 40 pax?

### Sources

https://en.wikipedia.org/wiki/Arun-class_lifeboat
https://en.wikipedia.org/wiki/Severn-class_lifeboat

**Comment by PygmalionOfCyprus** [comment]
Re: Sea State, this fits very well into some new schema we've just added to the DB, which now discerns between Full Operational Capacity (FOC) Sea State and Max Sea State. Basically, ships are fine up to FOC; between FOC and Max, they'll slow down the worse conditions get; past Max, they are effectively unable to maneuver and risk flooding/damage, etc.

So, I've given the Arun Class a FOC SS of 6 -- which will let it chug happily along where other ships are at the max of their capabilities -- and a Max SS of 8, which should let it persevere safely even in conditions where other ships are taking damage/sinking. Go rescue them!

While DPs are tied to tonnage, the default calculations actually assume things like watertight compartments, etc. The "Built to Commercial Standards" flag removes these assumptions (commercial vessels are generally not built for "survivability" beyond basic maritime requirements, unlike combat-rated vessels). So the absence of that flag is creating your desired effects. Recall that our DP model is meant primarily for modelling combat effects: a missile vs. GRP will have a far more destructive effect regardless of any other design considerations.

Tweaked the troop/cargo capacity as requested.

Handled 500.

**Comment by FrangibleCover** [comment]
> While DPs are tied to tonnage, the default calculations actually assume things like watertight compartments, etc. The "Built to Commercial Standards" flag removes these assumptions (commercial vessels are generally not built for "survivability" beyond basic maritime requirements, unlike combat-rated vessels). So the absence of that flag is creating your desired effects. Recall that our DP model is meant primarily for modelling combat effects: a missile vs. GRP will have a far more destructive effect regardless of any other design considerations.

Ah, that makes sense to me. I thought that Commercial Standards and GRP were mutually exclusive flags, but if they're additive then leaving off Commercial Standards seems like a reasonable compromise. I suspect that they're still going to be more survivable than normal PBs just because of their boxy construction, but honestly at 13DP what difference does it even make? You're still going to get evaporated by anything intended to sink a ship.

Really pleased to hear about the new sea state mechanics, sounds like something that could add a lot to less kinetic scenarios and make a real difference between FIAC/skiff forces and actual light patrol boats, and then between Soviet style PCFGs and NATO light frigates. Comparing a Nanuchka to an Annapolis looks a lot fairer when both vessels are taking green water over the bow!
