### ISSUE TITLE
Arun-class Lifeboat (Halmatic 52)

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3255]
### DB Selector

Both

### DBID to Copy

DB3k ship 3978

### Hypothetical

No

### Name

ALB 52-01 Arun (Arun-class)

### Country

UK/Civilian

### Service

Royal National Lifeboat Institution/Civilian

### In Commission

1971-

### Sensors

-

### Mounts

-

### Loadout Options

-

### Other Changes

15.8m long x 5.2m beam x 1.5m draft

Caterpillar diesels instead of MAN

Note changes from #3254

Type was mainly used by the British RNLI, but could be a generic Civilian boat given its operation by Australia, Chile, China, the Faeroes, Finland, Russia and Iceland as a civilian rescue boat.

### Sources

https://en.wikipedia.org/wiki/Arun-class_lifeboat
https://lifeboatmagazinearchive.rnli.org/volume/52/514/looking-at-lifeboats-the-arun-class?searchterm=Yacht+Gan&page=2358
https://www.novi-marine.com/boot/halmatic-arun-52-class-lifeboat-ex-rnli-for-sale/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
