### ISSUE TITLE
Update #3299 - A 725 Jacques Chevallier [Modified Vulcano Class] (France - 2022) ADD 2 x SIMBAD RC Mistral 3

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3256]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3299 - A 725 Jacques Chevallier [Modified Vulcano Class] (France - 2022)

### Summary of Changes

Add 2 x SIMBAD RC Mistral 3 dual launchers #3890 - Mistral 3 dual remote control mount. 
Position would give near roughly 240 arc for air targets on front mount and circa 240 degrees for rear hangar mounting?
Appear to be just aft of the 40 mm mounts fwd and above the helicopter hangar. 
There are also L-RAD distraction devices near the SIMbads. 

### Sources

https://youtu.be/jFwUHrC504Q?t=112

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
