### ISSUE TITLE
Severn-class Lifeboat

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3260]
### DB Selector

DB3K

### Baseline

DB3k ship 3978

### Hypothetical

No

### Name

ALB 17-02 The Will

### Class

Severn-class

### Country

UK/Civilian

### Service

Royal National Lifeboat Institution/Civilian

### In Commission

1996-

### Length (m)

17.3

### Beam (m)

5.9

### Draft (m)

1.78

### Standard Displacement (t)

40

### Complement

6

### Max Sea State

10

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3412 TA

### Fuel Capacity (kg)

4500kg-ish, 5500lt

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

250 @ ?, likely flank

### Sensors

1x Decca Bridgemaster navigational radar (Decca Generic?)
2x Searchlight (role-fit)

![image](https://user-images.githubusercontent.com/109925704/230484857-e64a4907-d7a0-4699-a6a6-fe48b4e94443.png)
Searchlights visible on flying bridge in this image.

### Mounts

-

### Aircraft & Docking Facilities

1x crane for Y-class Lifeboat (3m RHIB) - Model as Civilian 7m RHIB, very little reason to add a tiny RHIB in my view.

### Comms/Datalinks

VHF radio
MF radio
VHF direction finder - little info, likely to be short range, surface search only, no specific ID
GPS

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

Equipped with bow thrusters. Cargo capacity 47 pax.

I'm adding this as a semi-generic modern, fast rescue lifeboat suitable for scenarios in the mid 90s to today and quite probably beyond. Paired with #3255 it provides coverage of most of CMO's operational period. I reckon there are a few decent scenarios in these things, or else they're an interesting bit of naval traffic that pops out of a port and charges to sea at 25kts after the shooting has just started, which for a lot of players is a Harpoon-first, ask-questions-later sort of threat.

ALB 17-02 _The Will_ has been selected as the name ship because ALB 17-01 is kept for trials and has had two different names.

### Sources

https://en.wikipedia.org/wiki/Severn-class_lifeboat
https://rnli.org/what-we-do/lifeboats-and-stations/our-lifeboat-fleet/severn-class-lifeboat
https://rnli.org/about-us/our-history/timeline/1996-the-severn-class-lifeboat
https://rnliarchive.blob.core.windows.net/media/1542/0545.pdf - pp.16, indicates training on Decca Bridgemaster

**Comment by Jkryos** [comment]
Added DB3K 501.
