### ISSUE TITLE
Additional Generic Facilities

### ISSUE THREAD

**Issue by Goshawk-1** [PygmalionOfCyprus/cmo-db-requests#3262]
- Ferry crossings
- Rail tunnel entrance and exit (through mountains)
- Manned roadblocks/checkpoints

**Comment by PygmalionOfCyprus** [comment]
A ferry crossing would just be a port...

We already have a Structure (Tunnel) and Structure (Tunnel Entrance).

Roadblocks can easily be represented by one/several of the existing Building facilities, e.g. "Guard Post".
