### ISSUE TITLE
Aircraft #6347 - Z-242L Guru (Yemen [1990-] - 2002) - Should be unarmed 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3266]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #6347 - Z-242L Guru (Yemen [1990-] - 2002)

### Summary of Changes

DB entry has one 1x 12.7mm/50 UBS x 2 [400 rnds] - IRL aircraft is unarmed with no stores capacity.

On a linked theme for #6346 - Yak-11 Moose (Yemen [1990-] - 1957)
Yemen the Yak-11 Moose Yemen (et al) has two 100kg bomb rated stores pylons in addition to the single 12.7mm in the nose. 

### Sources

https://www.airforce-technology.com/projects/zlin-z-242-l-guru-trainer/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
