### ISSUE TITLE
Add F-15I GBU-38, Amraam, Sparrow, Python and Lantirn Pod loadout

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3267]
### DB Selector

DB3K

### User(s)

aircraft 2703, 3903, 4776

### Weapons Carried

x2 GBU-38 {Mk 82, MPR-500]
x2 Amraam C5/C7
x2 Python-4/5
x2 Sparrow
AAQ-13 navigation pod 
AAQ-14 targeting pod

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://twitter.com/IAFsite/status/1644213870746034177?cxt=HHwWgoCzybrztdEtAAAA
https://twitter.com/GuyPlopsky/status/1644296777196253184?cxt=HHwWgMDR4Z_N29EtAAAA

**Comment by KushanGaming** [comment]
Done for DB501.
