### ISSUE TITLE
ASM-N-2 Bat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3277]
### DB Selector

CWDB

### Baseline

AN-M66 as warhead payload

### Hypothetical

No

### Name

ASM-N-2 Bat

### Length (m)

3.63 m

### Width/Span (m)

3.0 m

### Diameter (m)

as AN-M66

### Weight (kg)

727 kg total (warhead plus airframe)

### Range (nm)

17 nm

### Target Altitude / Depth (ft)

0 Ft AGL/ASL

### Target Speed (kts)

Capable vs Surface ships

### Launch Altitude / Depth (ft)

15,000 to 25,000 feet

### LaunchSpeed (kts)

140 to 210 knts

### Warhead

AN-M66 2000 lb bomb

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened

### CEP (m)

Not Stated

### Sensors

1x Active Radar Seeker

### Weapon Codes

Illuminate at Launch, Terminal Illumination, Bearing-Only Launch (BOL), Weapon - INS Navigation, Weapon Altitude Control Possible, Attitude Control - Aerodynamic Only

### Comments

In service from 1945-1953

Release from 15,000 to 25,000 feet at airspeeds of 140 to 210 knts, 260 knts glide speed.

Several Bats were also fitted with modified radar systems (SWOD Mark 9 Model 1) and dropped on Japanese-held bridges in Burma

The Privateer was the primary launch platform for the Bat, but other aircraft were also modified to launch the weapon, including the Vought F4U Corsair, Curtiss SB2C Helldiver, and Grumman TBF Avenger. The primary post-World War II aircraft to carry the weapon was the P-2 Neptune.

Old Designation | September 1947 | ca. February 1948

SWOD MK 9 MOD 0 | ASM-2 | ASM-N-2
SWOD MK 9 MOD 1 | ASM-2a | ASM-N-2a

2x BAT per loadout for;
PB4Y Privateer
P-2 Neptune
PV-1

1x BAT per loadout for;
SB2C Helldiver
TBF Avenger
F4U Corsair

### Sources

https://en.wikipedia.org/wiki/ASM-N-2_Bat
https://www.designation-systems.net/dusrm/app1/asm-n-2.html
https://pimaair.org/museum-aircraft/u-s-navy-asm-n-2-bat/
http://www.aviation-history.com/consolidated/b24.html
https://www.smithsonianmag.com/air-space-magazine/restoration-the-bat-2925632/
https://www.asisbiz.com/il2/Corsair/NAS/pages/Vought-F4U-1D-Corsair-carries-an-upgraded-version-of-the-Bat-(ASM-N-2A)-1953-03.html
https://www.youtube.com/watch?v=CIYWCuehGmk
https://www.youtube.com/watch?v=eCOHe29cdmk
http://ufxufo.org/images/BatHead.pdf
http://[bathead.com/insignia.html](http://bathead.com/insignia.html)

Bat guided bomb mated to PB4Y Privateer
![image](https://user-images.githubusercontent.com/99599482/230958057-19113cf8-299d-4fd7-a11e-40a2b45ba903.png)
![image](https://user-images.githubusercontent.com/99599482/230961182-938936d1-19f8-4959-be22-8113b0d480e3.png)

A PB4Y-2B carrying ASM-N-2 Bat
![image](https://user-images.githubusercontent.com/99599482/230960926-f19abc91-ed3f-43a5-b4d3-2ac1e3478100.png)
![image](https://user-images.githubusercontent.com/99599482/230962679-c528994e-cf99-430f-89b4-6414252bee10.png)

SB2C dropping ASM-N-2 guided bomb 1946
![image](https://user-images.githubusercontent.com/99599482/230961457-07de2076-1ce2-42f5-b344-c5a5ad47fd79.png)
![image](https://user-images.githubusercontent.com/99599482/230963252-c99be1f1-83b8-442a-bf5f-c4757dcc1883.png)

Vought F4U-1D Corsair carries an upgraded version of the Bat (ASM N 2A) March 1953
![image](https://user-images.githubusercontent.com/99599482/230962201-52bbc399-53ee-4680-aea5-edd4852a6cf9.png)
![image](https://user-images.githubusercontent.com/99599482/230963466-cbd2b5bc-d9e3-4054-b137-6f767cd24e31.png)

Grumman TBM Avenger in flight with ASM-N-2 Bat missile
![image](https://user-images.githubusercontent.com/99599482/230962540-650754f4-b216-44c9-911e-c5bd899366c3.png)

Lockheed PV-1 Ventura
VP-152 and VP-153 were initially trained to use PELICAN/BAT 
![image](https://user-images.githubusercontent.com/99599482/230963166-5dde9a89-3030-4677-a63d-82818b3f1c76.png)

P2V Neptune
![image](https://user-images.githubusercontent.com/99599482/230964820-5d692514-28e0-482d-9418-2562ed82051d.png)

**Comment by PygmalionOfCyprus** [comment]
Yeah, "bathead.com" might be the weirdest source we've gotten so far.

Handled 503.

**Comment by tbrandon517** [comment]
> Yeah, "bathead.com" might be the weirdest source we've gotten so far.
> 
> Handled 503.

Sometimes you need something that batty.

**Comment by 1103CA** [comment]
nice to see WW2 weapon

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus please consider a loadout for the PV-1 Ventura

**Comment by PygmalionOfCyprus** [comment]
PV-1 loadout added 505.
