### ISSUE TITLE
Bahrain - 23x ex-USMC AH-1W SuperCobras

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3278]
### DB Selector

DB3K

### DBID to Copy

DB3K aircraft 2924

### Hypothetical

No

### Name

https://airrecognition.com/index.php/news/defense-aviation-news/2023-news-aviation-aerospace/april/8954-bell-to-supply-24-refurbished-ah-1w-supercobra-attack-helicopters-to-bahrain.html?fbclid=IwAR0zVHTu6RxCfd8sSUpZINfH4InbAkseT0Q5UWTejylKtqVWFCNoCn-FPSc

### Country

Bahrain

### Service

Air Force

### In Commission

2024-

### Number in Service

24x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Not Stated 

### Sources

https://airrecognition.com/index.php/news/defense-aviation-news/2023-news-aviation-aerospace/april/8954-bell-to-supply-24-refurbished-ah-1w-supercobra-attack-helicopters-to-bahrain.html?fbclid=IwAR0zVHTu6RxCfd8sSUpZINfH4InbAkseT0Q5UWTejylKtqVWFCNoCn-FPSc
https://www.aviacionline.com/2023/03/bahrain-authorized-to-acquire-24-ah-1w-super-cobra-helicopters/
https://defbrief.com/2023/03/31/bahrain-emerges-as-potential-first-customer-for-surplus-us-ah-1w-supercobras/
https://www.janes.com/defence-news/news-detail/bahrain-approved-for-24-surplus-supercobra-attack-helos-from-us

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
