### ISSUE TITLE
United States - GARC AAW Hypothetical 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3279]
### DB Selector

DB3K

### DBID to Copy

DB3k ship 3843

### Hypothetical

Yes

### Name

DB3K ship 3843

### Country

United States

### Service

Navy

### In Commission

2023-

### Number in Service

N/A

### Sensors

Similar to DB3K facility 3415

### Mounts

Similar to single Stinger launcher for DB3K facility 3415

### Loadout Options

N/A

### Other Changes

N/A

### Sources

https://www.thedrive.com/the-war-zone/stinger-missile-toting-drone-boats-could-protect-navy-logistics-ships?fbclid=IwAR1b0KudIit3HoNMZ9q5uGyMkd6UA4Wid17-vFb2GJ4UUd6-2g4aFAT8m1k

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
