### ISSUE TITLE
Fix Pantsir SM radar

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#328]
### DB Selector

DB3K

### Affected DBID(s)

3250

### Summary of Changes

Pantsir SM Fire control radar is worse than the Pantsir S1E radar. Tested these next to each other and the S1E radar consistently out performs the SM which is completely incorrect. 

### Sources

Tested in game.

**Comment by KLABDB3K** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/46#issue-1133428445

Think the fix / upgrade has already been asked for.
