### ISSUE TITLE
Update/Correction: Orca XLUUV

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3281]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 655

### Summary of Changes

1. Remove all mounts and the magazine. 
2. Add a mount named "Orca Payload Bay", with provisions for: 
40x Mk48 torpedo, or
40x UGM-109I, or
40x UGM-109J(Blk V and Va), or
40x Mk67 SLMM. 
3. Add a forward-looking mine-hunting sonar. 
4. Add a side-looking echo sounder. 

### Sources

https://en.wikipedia.org/wiki/Orca_(AUV)
https://www.navalnews.com/naval-news/2022/05/here-is-our-first-look-at-the-us-navys-orca-xluuv/
http://www.hisutton.com/USN_XLUUV.html

**Comment by transientSG** [comment]
40 Mk48s or Tomahawks are definitely waaay too excessive. 

Probably in the order of 10 to 12 of each maximum.? And maybe around 20 to 24 SLMM (2x SLMM for each torp/tomahawk?)

**Comment by PygmalionOfCyprus** [comment]
Handled 501. Agree w/ transient that 40 is way too much. All existing literature points to 12x tubes.
