### ISSUE TITLE
Ship #3271 UK RN Type 31 radar update to Thales NS110 (WIP) 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3282]
### DB Selector

DB3K

### Affected DBID(s)

Ship Type 31 Arrowhead UK Royal Navy 

### Summary of Changes

WIP
Main radar designated NS110.
Not clear but this is probably a derivation of thr NS100.
Haven't got access to the full DB3K so cant check what other platforms use the existing NS100. 
Also in line for use on the Brazilian Tamandare. 
### Sources

https://www.thalesgroup.com/en/countries-europe/united-kingdom/news/thales-delivers-significant-milestone-uks-type-31-inspiration

https://www.defesaaereanaval.com.br/dan-tv/dan-tv-fragata-tamandare-podera-ser-equipada-com-radar-ns-110-4d-da-thales

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
