### ISSUE TITLE
Add 2023 MC-130H retirement date

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3283]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #2280

### Summary of Changes

Add 2023 retirement date to MC-130H. Replaced by MC-130J.

### Sources

https://www.thedrive.com/the-war-zone/retirement-of-mc-130h-speeds-up-mc-130j-low-flying-radar-upgrade
https://www.airandspaceforces.com/final-mc-130h-boneyard/

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
