### ISSUE TITLE
Update: PL-15/PL-15E, NATO callsign & property addition

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3286]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3413, 3896

### Summary of Changes

1. Add NATO callsign to its DB name: CH-AA-10 Abaddon.

2. Add "Lock-On After Launch (LOAL) - CEC Capable" to its DB properties (same as AIM-120D, Meteor and AAM-4B).

The cooperative engagement capability of this weapon has been long rumored. And now we have sufficient evidence (including confirmation from a leader of Missile Institude in China) to give it this ability in game.

### Sources

https://en.wikipedia.org/wiki/PL-15
https://www.iiss.org/online-analysis//military-balance/2023/02/chinas-air-force-modernisation-gaining-pace
https://www.globalsecurity.org/military/world/china/pl-15.htm
https://www.sinodefenceforum.com/t/chinese-aam.1481/page-58
https://www.airuniversity.af.edu/Portals/10/CASI/documents/Research/Infrastructure/2020-11-%2030%20Air-to-Air%20Missiles%20and%20Guidance%20Systems.pdf
![image](https://user-images.githubusercontent.com/107970049/231718477-5fc88ea4-e8bf-498a-bf5c-1d0d01c2bdff.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 500. Also did the PL-10 (CH-AA-9) and PL-12 (CH-AA-7 Adze) while I was at it.
