### ISSUE TITLE
AN-32B Cline - Iraq (Air Force) 2011-

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#329]
### DB Selector

DB3K

### DBID to Copy

aircraft/4269/DB3K

### Hypothetical

No

### Name

AN-32B Cline - Iraq (Air Force) 2011-

### Country

Iraq

### Service

Air Force

### In Commission

2011-Present

### Sensors

As existing plus Add NKPB-7 optical bombsight

### Mounts

Four-beamed BDZ-34 bomb racks on four pylons, two on each side of the fuselage.

removable roller conveyor on the guide rails in the cargo bay. The conveyor could fit four 500-pound bombs. 

### Loadout Options

As existing plus Add

4x Unguided Bombs of 250-500Kg Class (external)
4x Unguided Bombs of 250-500Kg Class (Internal)

### Other Changes

More recent images show Iraqi aircraft with what appears to be a new, single, long pylon on either side of the aircraft that might be able to accommodate multiple 500-pound class bombs or larger munitions. It is also possible this new configuration could be some kind of sensor system, further highlighting the versatility of the aircraft. The mount also appears to hold a large dispenser for decoy flares, another important addition given reports that ISIS has obtained infrared-homing shoulder-fired, man-portable surface-to-air missiles in the past. Specifics unclear.

Apparently bomb mods for An-26/An-32 date to the Soviet invasion of Afghanistan and have been similarly employed by the Indian Air Force (An-32) in exercises and by the Ukrainian Air Force (An-26) in Donbass.

### Sources

https://en.wikipedia.org/wiki/Antonov_An-32#Military_operators

Delalande, Arnaud (2016). Iraqi Air Power Reborn, The Iraqi air arms since 2004. Houston: Harpia Publishing. [ISBN](https://en.wikipedia.org/wiki/ISBN_(identifier)) [978-0-9854554-7-7](https://en.wikipedia.org/wiki/Special:BookSources/978-0-9854554-7-7).

https://www.thedrive.com/the-war-zone/20330/iraqs-an-32-cargo-planes-turned-bombers-flew-nearly-twice-as-many-strikes-as-its-f-16s

https://warisboring.com/the-iraqi-air-force-just-got-new-bomber-planes-by-arming-transports/

![image](https://user-images.githubusercontent.com/99599482/154845550-3fef1160-cf05-426e-8c91-83bb18411029.png)
![image](https://user-images.githubusercontent.com/99599482/154845708-a3f4d389-7f2b-406d-b4d1-a7e0b26e7d63.png)
![image](https://user-images.githubusercontent.com/99599482/154845775-9b3b53f7-f2f8-4977-8df6-698c83af85cb.png)

**Comment by PygmalionOfCyprus** [comment]
Added 493.
