### ISSUE TITLE
UMPK FAB-500M62 Glide bomb (WIP) 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3291]
### DB Selector

DB3K

### Baseline

Weapon FAB-500M62 500kg bomb

### Hypothetical

No

### Name

UMPK FAB-500M62 (FAB-500M62 Glide bomb). Russia 2023.*

### Length (m)

TBC 

### Width/Span (m)

TBC 

### Diameter (m)

TBC

### Weight (kg)

550kg 

### Range (nm)

Low altitude 3-4nm at 200m upto 30nm launched at altitude. 

### Target Altitude / Depth (ft)

Land static only. 

### Target Speed (kts)

0

### Launch Altitude / Depth (ft)

Min 200 m up to 10k ft? 

### LaunchSpeed (kts)

Upto 650kts

### Warhead

500kg HE

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway

### CEP (m)

10-20

### Sensors

GPS/GLONASS/Beidou 

### Weapon Codes

Weapon - INS w/ GNSS Navigation, Weapon - Pre-Briefed Target Only, Uses GPS, Uses GLONASS, Uses BeiDou/COMPASS

### Comments

UMPK Kit is rough analogue to JDAM range extension pop out wings.
Images thus far have been enigmatic as to how this achieves 3D guidance  due to absence of some relevant moving vertical control surfaces. 
https://raigap.livejournal.com/570890.html This is the most interesting article I have found as the initial schematics from 2009 have a version with pop out wings and a drop down vertical fin which would solve one of the control surface issues. As the weapon is designed to be carried inverted and flip on launch the fin wouldn't be visible until the bomb flipped over after release.
https://ic.pics.livejournal.com/raigap/40496274/1823224/1823224_original.jpg

Still ambiguous but could be fitted to any dumb bomb in Russian service and there are dialogues about it being fitted to the FAB-1500 as well. 
*From various Russian channels the naming convention seems to be UMPK FAB-500M62 Glide bomb. Russia 2023.

### Sources

https://t.me/kramnikcat/3290
https://rg.ru/2023/04/14/pvo-ukrainy-okazalas-bessilna-pered-planiruiushchimi-bombami-rf.html
Not advocating or endorsing the ethics of the sources above. 
https://www.businessinsider.com/russias-success-at-equipping-simple-bombs-with-guidance-systems-report-2023-4?r=US&IR=T
https://www.thedrive.com/the-war-zone/russian-bomb-with-mysterious-range-extending-wing-kit-emerges
https://t.me/fighter_bomber/11841
https://raigap.livejournal.com/570890.html [This is the most interesting article as the initial schematics from 2009 have a drop down vertical fin which would solve one of the control surface issues and wouldnt be visible until the bomb flips over after release and the fin drops down. 
https://www.globalsecurity.org/military/world/russia/umpk.htm

Ukraine sources are stating 20-30 attacks per day by these weapons and ranges of up to 70km from SU-34 and Su-35 and SU-24, clearly dependant upon launch aircraft height and velocity.

**Comment by bostonmyk** [comment]
https://twitter.com/RALee85/status/1620968852799754242
https://twitter.com/RALee85/status/1644121828204462080
https://twitter.com/RALee85/status/1640876191602159617
https://twitter.com/Trollstoy88/status/1646935881180237824
https://twitter.com/Dmojavensis/status/1635055289300054017

**Comment by KLABDB3K** [comment]
https://rg.ru/2023/04/17/primenenie-rf-planiruiushchej-bomby-vesom-v-poltonny-pokazali-na-video.html
Sort of confirmation of the UMPK designation and guidance mode.

**Comment by ddranidis** [comment]
More info:
https://www.globalsecurity.org/military/world/russia/umpk.htm
https://www.globalsecurity.org/military/world/russia/umpk-specs.htm
https://www.globalsecurity.org/military/world/russia/umpk-pics.htm
https://kyivindependent.com/russias-smart-bombs-pose-increasingly-serious-threat-to-ukraine/

Initial appearance (prototype?) : https://eurasiantimes.com/loaded-on-su-34-fighter-images-of-russian-fab-500m-62-bomb/

**Comment by KLABDB3K** [comment]
https://www.popularmechanics.com/military/weapons/a43571893/how-dumb-are-russias-winged-smart-bombs/

A further proposition that they aren't guided per-se but rely on an SVP-24 type system on board the launch aircraft to predict an impact point in combination with an inertial navigation system on the weapon. My understanding of the  SVP-24 is that it functions more like a ground controlled intercept system than a predicted point of impact bomb aiming system, that is it guides the aircraft into an optimal launch parameter position and then gives a bomb release instruction to the pilot / WSO.  In this case the CEP would be a lot higher but not beyond the point that a 500kg bomb would hit close enough to cause significant damage to the intended target, especially if you have no regard to collateral casualties.

**Comment by PygmalionOfCyprus** [comment]
Handled 500; added w/ loadouts for Su-34/35s.

**Comment by KLABDB3K** [comment]
https://xn--b1aga5aadd.xn--p1ai/2023/%D0%90%D0%B2%D0%B8%D0%B0%D1%86%D0%B8%D1%8F9/
Apparently a 250kg version too, its not a request at this stage.

**Comment by KLABDB3K** [comment]
https://twitter.com/AndrewPerpetua/status/1655536566171779074?s=20
Its vague but possibly visible is a tail surface?

**Comment by PygmalionOfCyprus** [comment]
Added the 250kg version too, but that ver. will be in 501.
