### ISSUE TITLE
Hatsuyuki-class out-of-service dates

### ISSUE THREAD

**Issue by Lafayette-II** [PygmalionOfCyprus/cmo-db-requests#3292]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1746, 1747

### Summary of Changes

Ship_1746: Last two ships of this class, JS Isoyuki and JS Haruyuki,  were both decomissioned on March 13th, 2014. (JS Shirayuki continued to serve until 2016, although she was converted to training vessel (TV-3517) in 2011)
Ship_1747: Last ship of this subclass was decomissioned on April 7th, 2021.

### Sources

https://en.wikipedia.org/wiki/Hatsuyuki-class_destroyer

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
