### ISSUE TITLE
Alouette III for Angola

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3294]
### DB Selector

Both

### DBID to Copy

Any SA.316B, 6049 why not

### Hypothetical

No

### Name

SA.316B Alouette III

### Country

Angola

### Service

Air Force

### In Commission

1975-

### Sensors

-

### Mounts

-

### Loadout Options

-

### Other Changes

Sourced from all over, including ex-Portuguese abandoned aircraft, purchases from France and from Romania (meaning that IAR were selling their French designed helicopters to both sides of the Border War)

### Sources

WAR OF INTERVENTION IN ANGOLA, VOLUME 3: ANGOLAN AND CUBAN AIR FORCES, 1975-1985 by Fontanellaz, Cooper & Matos
https://aviation-safety.net/wikibase/267966 - if they're still crashing, they're still going!

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
