### ISSUE TITLE
BN-2A Islander for Angola

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3296]
### DB Selector

Both

### DBID to Copy

DB3k Aircraft 6260

### Hypothetical

No

### Name

BN-2A Islander

### Country

Angola

### Service

Air Force

### In Commission

1975-today

### Sensors

-

### Mounts

-

### Loadout Options

- Unarmed passengers
- Unarmed recce
- BAI, Improvised beer bottle bombs, 330ml incendiary?? - CWDB only if you want to add it
- Defoliant spray - Not represented?

### Other Changes

Again, some Romanian built aircraft.

### Sources

WAR OF INTERVENTION IN ANGOLA, VOLUME 3: ANGOLAN AND CUBAN AIR FORCES, 1975-1985 by Fontanellaz, Cooper & Matos, p.17, p.26

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
