### ISSUE TITLE
AN/FPS-118 OTH RadarPeakPower

### ISSUE THREAD

**Issue by yiyuezhuo** [PygmalionOfCyprus/cmo-db-requests#3297]
### DB Selector

DB3K

### Affected DBID(s)

2425

### Description of Problem

In the current version, the radar `AN/FPS-118` has `RadarPeakPower` value `100000` (100KW) while it should be `1000000` (1MW). So I guess there's a tiny typo.

References:
https://www.radartutorial.eu/19.kartei/01.oth/karte009.en.html
https://nuke.fas.org/guide/usa/airdef/an-fps-118.htm

### Recommended Fix

Change `RadarPeakPower` value of `AN/FPS-118` from `100000` to `1000000`

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
