### ISSUE TITLE
Bring Recoilless Rifles to DB3K 

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#33]
### DB Selector

DB3K

### Affected DBID(s)

Anti-Tank Sect, Recoilless Rifles

### Summary of Changes

Recoilless rifles still see use in modern conflict, and are even still in the inventories of several professional militaries. For example, the Venezuelan Army still uses the M40A1 106mm Recoilless rifle today, and other entries found in the CWDB can still be seen in use in various low intensity conflicts across the world.

No reason not to just transfer them all over and mark them as generic in my opinion.

### Sources

https://en.topwar.ru/190082-pricelami-ot-vintovki-dragunova-osnascheny-novye-samohodnye-pushki-ontos-venesujely.html

https://www.globalsecurity.org/military/world/venezuela/army-equipment.htm

**Comment by Jkryos** [comment]
Added M40A1 106mm to DB3K 494.
