### ISSUE TITLE
AIM-9X for Italy

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#330]
### DB Selector

DB3K

### User(s)

Italian F-35s

### Weapons Carried

From 2026 AIM-9X will be integrated to F-35 to match capability of IRIS-T on other Italian aircraft.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

AIM-9X Block II/II+ missiles for F-35 from 2026.

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/february/11359-italy-joins-air-intercept-missile-aim-9x-program-of-us-navy.html?fbclid=IwAR3X-v6E7qje7ipcvOfixI28yG_k-xNis4jDPlvF77H2NLmzo3gAe2La8C0

https://theaviationist.com/2022/02/04/italian-f-35s-will-get-aim-9x-block-ii-air-to-air-missiles/?fbclid=IwAR0kiaG0EDK-s2GODfDWBqbXBrri2ViJXxsSffvdT69MOsSqvcwIcKRbgTE

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
