### ISSUE TITLE
Add S-8 and S-13 Rocket Loadouts to Ukrainian Hips

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3303]
### DB Selector

DB3K

### User(s)

Aircraft 2632,2671,2629

### Weapons Carried

S-8
40 S-8 Rockets (2x 20 tube Pods)

S-13
10 S-13 Rockets (2x 5 Round Pods)

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

Yes

### Sources

S-8
https://twitter.com/Osinttechnical/status/1645275988807303168
https://twitter.com/Osinttechnical/status/1632250819666911232
https://twitter.com/Osinttechnical/status/1645384216518033409/photo/1

S-13
https://twitter.com/Osinttechnical/status/1537190789133967360
https://twitter.com/Osinttechnical/status/1644779897649332227?cxt=HHwWhoC80cemt9MtAAAA
https://twitter.com/Osinttechnical/status/1643024089613828096?cxt=HHwWgIC8rYrtmM0tAAAA
https://twitter.com/Osinttechnical/status/1624242174240907265

**Comment by Jkryos** [comment]
Added DB3K 500.
