### ISSUE TITLE
ROCAF S-70C Update

### ISSUE THREAD

**Issue by Lafayette-II** [PygmalionOfCyprus/cmo-db-requests#3304]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4757

### Summary of Changes

Please rename the platform to "S-70C-6 Super Bluehawk".

The Taiwanese Air Force does not operate any variant of the S-70 designated C-3. The sensor suite and commissioning date of the aircraft closely resemble that of the S-70C-6. Only four aircraft of this variant were acquired. The aircraft database of Scramble.nl reports that almost all ROCAF S-70C were withdrawn by May 2019.

Below are some excerpts from an Key.Aero article:

"_The Republic of China Air Force (ROCAF) retired its fleet of S-70C- 1 Bluehawk and S-70C-6 Super Bluehawk helicopters by May 9. Employed in the search and rescue (SAR) and utility roles, the Taiwanese S-70s will be replaced by the UH-60M._"

"_Taiwan purchased ten S-70C-1As and four C-1s to replace the 1970s-era Bell HH-1H in the SAR role. Deliveries took place from June 1986. The four S-70C-1s were not fitted for SAR duties but were delivered as utility helicopters. From April 1988 onwards, four additional all-weather SAR S-70C-6 Super Bluehawks were purchased (of which two were used as utility helicopters with leather seats in the main cabin)._"

"_Beginning in December 2017, the ROCAF received 15 UH-60Ms originally planned for the Taiwanese Army. The last was due for handover in December 2018._"

### Sources

http://www.taiwanairpower.org/af/s70c.html
https://www.key.aero/article/rocaf-s-70c-retirement
https://www.scramble.nl/database/military/tw#results

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
