### ISSUE TITLE
Update/Correction for B-70A Valkyrie

### ISSUE THREAD

**Issue by Halberx** [PygmalionOfCyprus/cmo-db-requests#3306]
### DB Selector

Both

### Affected DBID(s)

Aircraft #348 (CWDB) & Aircraft #4869 (DB3K)

### Summary of Changes

**GENERAL DATA:**
- Length = 56.6 m
- Wingspan = 31.4 m
- Height = 9.3 m
- Crew = 4 (namely the pilot, co-pilot, bombardier-navigator and defense operator)
- Empty Weight = 85427 kg
- Max Weight = 252473 kg (max T.O.)
- Max Payload = 28.000 kg
- Average Climb Rate = 10800 ft/min, 54,9 m/sec
- Instantaneous Climb Rate, S/L: 24550 ft/min, 124 m/sec
- Damage Points = 10 (it is 5 for the DB3K entry)

**MOUNT/STORES/WEAPONS:**
- Adding a Generic Chaff Salvo with no specified capacity, as was required by the WS-110A program
- 20x AGM-69A SRAM (ID:998 for DB3K and ID:291 for CWDB)
- 1x AGM-48 Skybolt (ID:1799 for CWDB)

**PROPULSION:**
- 6x YJ93-GE-3 (name change)

**Technical Details:**
- ThrustPerEngineMilitary (S/L) : 9979 kg per engine
- ThrustPerEngineAfterburner (S/L) : 14061 kg per engine
- SFCMilitary (S/L) : 0.7 kg/h
- SFCAfterburner (S/L) : 1.8 kg/h

**Performance Details for 6x YJ93-GE-3:**
- Velocity limit constraints for operational loadouts to aid to the performance table of the engines; 
Mach 1.0 at 10.000ft
Mach 2.0 at 35.000ft
Mach 3.0 at 70.000ft

**FUEL:**
- Aviation Fuel = 51890.0 kg

This jet is not capable of supercruise, as is currently the case!

### Sources

- https://archive.aoe.vt.edu/mason/Mason_f/XB70PresS07.pdf
- https://www.secretprojects.co.uk/threads/north-american-b-70-valkyrie.16322/
- https://www.flickr.com/photos/kurtsmocs/13836223253/in/photostream/ and The Big Book of X-Bombers & X-Fighters: USAF Jet-Powered Experimental Aircraft and Their Propulsive Systems by Steve Pace for Skybolt integration plausability
- https://www.joebaugher.com/usaf_bombers/b70.html
- https://jet-engine.net/miltfspec.htm
- Turbofan and Turbojet Engines Database Handbook by Élodie Roux
- X-Planes from the X-1 to the X-60: An Illustrated History [illustrations by Giuseppe de Chiara]
- NASA publications and archives on the WS-110A/B-70A R&D and bomber program

**Comment by PygmalionOfCyprus** [comment]
Handled 500. Thanks for all the sources and info!
