### ISSUE TITLE
Addition: China, YLC-8E Anti-stealth Radar

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3307]
### DB Selector

DB3K

### Baseline

sensor 6572

### Hypothetical

No

### Name

China YLC-8E

### Sensor Generation

Early 2020s

### Range (nm)

0.2-378

### Horizontal Arc (deg)

360 deg

### Sensor Capabilities

Air Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Continuous Tracking Capability, Track While Scan (TWS), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA), Frequency Agile

### Search/Track Frequencies

B Band (250-500 MHz) [Old P Band (VHF)] 60-100 cm, C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm

### Scan Interval (s)

6

### Sources

https://divsightintel.com/ylc-8e-chinas-anti-stealth-radar-60b444975f43
https://pdj.quora.com/Chinese-advancement-in-Ground-Radars-YLC-8E-Anti-Stealth-Radar
https://twitter.com/GCAbdulRehman/status/1443188088294027265?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1443188088294027265%7Ctwgr%5Ebf3f1aae761bc2051cf2971eeca1b6818ce1db79%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fpdj.quora.com%2FChinese-advancement-in-Ground-Radars-YLC-8E-Anti-Stealth-Radar

**Comment by Jkryos** [comment]
Added DB3K 500.
