### ISSUE TITLE
Addition: China, Radar (China YLC-8E)

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3308]
### DB Selector

DB3K

### Hypothetical

No

### Name

Radar (China YLC-8E)

### Facility Type

Radar

### Country

China

### Service

Air Force

### In Commission

2022

### Sensors

1x China YLC-8E

### Mounts

-

### Comments

#

### Sources

https://divsightintel.com/ylc-8e-chinas-anti-stealth-radar-60b444975f43
![image](https://user-images.githubusercontent.com/107970049/232963404-214bba09-723a-4e3e-b95e-dc5e62aff923.png)

**Comment by Jkryos** [comment]
Added DB3K 500.
