### ISSUE TITLE
MiG-35 aka MiG-29M/M2? (WIP)? 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3309]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft MiG-35 Fulcrum Egypt 

### Summary of Changes

Seems the nomenclature MiG-29M/M2 is in use rather than export designation MiG-35.?
Wait ten minutes and it will probably change... Same goes for Russian MiG-35?

### Sources

https://www.key.aero/article/egyptian-mig-29s-feared-be-destroyed-sudan-slides-war?utm_campaign=KA-Email-General&utm_medium=email&_hsmi=254793222&_hsenc=p2ANqtz-9FxG6gET2r-z0pRV_B32jKc7RvObJqbN8M_hFr-uRA4AyKCmZEKgiixBT5idPfGWvEeoUevNSkhihxCvplpM-4lGlrLw&utm_content=254789512&utm_source=hs_email
The images show the long cockpit MiG-35 so is it nomenclature or reporting issues??

**Comment by PygmalionOfCyprus** [comment]
AFAIK there are some differences between the MiG-35 and M2, albeit not many, and this may have been further muddled during a period where Mikoyan and co. couldn't quite decide what they were selling and used new designations a bit more liberally than perhaps they should have.

I don't think we need to jump anything in the DB at this stage based on this reporting.

**Comment by KLABDB3K** [comment]
The images show the long cockpit MiG-35 so suspwct this is a reporting issue.
