### ISSUE TITLE
Add Ukrainian 40mm L70 Gun 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3311]
### DB Selector

DB3K

### DBID to Copy

Facility 475

### Hypothetical

No

### Name

AAA Sec (40mm/70 Bofors)

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

x36

### Sensors

Same. No flycatcher radar seen in pictures. 

### Other Changes

same

### Sources

https://twitter.com/front_ukrainian/status/1644645257806585861?cxt=HHwWioC90b6J-tItAAAA
https://kyivindependent.com/first-batch-of-lithuanian-anti-aircraft-guns-arrives-in-ukraine/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
