### ISSUE TITLE
Add Ukrainian Gepard SPAAG 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3312]
### DB Selector

DB3K

### DBID to Copy

Facility #67

### Hypothetical

No
### Name

AAA Sec (35mm Twin Gepard x2)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

x37

### Sensors

Same

### Loadout Options

Same

### Other Changes

Same

### Sources

https://www.forbes.com/sites/davidaxe/2022/09/26/ukraines-ex-german-air-defense-guns-are-in-action-supporting-the-counteroffensive/?sh=27da7fba110a
https://apnews.com/article/russia-ukraine-politics-germany-1a46d55d1325f4f2210dc1cb35b32137
https://www.thedrive.com/the-war-zone/ukraine-situation-report-gepard-anti-aircraft-systems-now-in-the-fight

**Comment by FrangibleCover** [comment]
Related #2652

**Comment by HVAA** [comment]
Why hypo, this was annouced as part of the defensive aid being given to Ukraine?

**Comment by bostonmyk** [comment]
Thanks and Fixed. Made a data entry error.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
