### ISSUE TITLE
Add Ukrainian S-60 AAA Gun

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3313]
### DB Selector

DB3K

### DBID to Copy

Facility 98

### Hypothetical

No

### Name

AAA Bty (57mm S-60 x 2)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Sensors

Don't see FCR so unlikely.

### Mounts

Reduce to 2.

### Other Changes

Brought out of retirement. Poland sent some as well.

### Sources

https://twitter.com/TDF_UA/status/1608815959263039488
https://twitter.com/ukraine_osint/status/1581165363235942401
https://en.defence-ua.com/weapon_and_tech/kharkiv_civil_defense_got_57mm_azp_s_60_anti_aircraft_gun_to_withstand_enemy_uavs_and_armored_vehicles-2892.html
https://gagadget.com/en/140339-the-ukrainian-military-told-how-the-rare-1947-s-60-anti-aircraft-gun-works-in-tandem-with-a-modern-drone/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
