### ISSUE TITLE
Kameelperd air search radar for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3315]
### DB Selector

DB3K

### DBID to Copy

Facility 2676

### Hypothetical

No

### Name

ESR-220 Kameelperd

### Country

South Africa

### Service

Army

### In Commission

1992-2006

### Number in Service

4x

### Sensors

1x ESR-220, based on the Thutlhwa but early 90s tech.

### Other Changes

The actual ESR-220 radars entered service in 1992, what happened in 2006-2007 is an upgrade (I think to work with Umkhonto?) and a symbolic renaming from the Afrikaans word for giraffe to the Zulu word for giraffe.

They also appear to have entered service again in 2015?

### Sources

https://www.reutechradar.com/news-events/thutlwa-official-handover-to-the-air-defence-artillery-formation/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
