### ISSUE TITLE
South African GDF-005 correction

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3317]
### DB Selector

DB3K

### Affected DBID(s)

Facility 1090

### Summary of Changes

Remove Skyguard FCR, change weapon to optically directed (note #3316)
Add LPD/20 Super Fledermaus acquisition radar.

### Sources

ALTA PETE AIR DEFENCE ARTILLERY: SOUTH AFRICA 1939-2016 by L. Crook, p.477

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
