### ISSUE TITLE
Correction to YLC-8B radar

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#332]
### DB Selector

DB3K

### Affected DBID(s)

Facility_2538

### Summary of Changes

Database shows this to be a 2D radar. PRC claims it has 3D capability. Additionally, it operates in the B/C (NATO) band (UHF), vice the "A" (HF/VHF) band.

### Sources

"Ancile." Ancile. Accessed September 21, 2021. https://www.deagel.com/Sensor%20Systems/YLC-8B/a003069. ;"A Closer Look At Stealth, Part 4: Counterstealth Radars At Zhuhai 2016." Aviation Week Network - Portal Aviation Week Network. Accessed September 21, 2021. https://m.aviationweek.com/defense-space/closer-look-stealth-part-4-counterstealth-radars-zhuhai-2016. ; Pike, John. "Chinese Military Radar." GlobalSecurity.org. Last modified January 5, 2021. https://www.globalsecurity.org/military/world/china/radar-intro.htm. ;"YLC-8B - Radartutorial." Grundlagen Der Radartechnik. Accessed September 21, 2021. https://www.radartutorial.eu/19.kartei/02.surv/karte065.en.html. ; "Military Balance India Vs China, Air Defense Systems Part 2- Chinese Radars." Full Afterburner. Accessed September 21, 2021. https://fullafterburner.weebly.com/next-gen-weapons/military-balance-india-vs-china-air-defense-systems-part-2-chinese-radars.

**Comment by Jkryos** [comment]
Fixed DB3K 493.
