### ISSUE TITLE
Mk46 torpedo loadout for HESA Karrar

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3322]
### DB Selector

DB3K

### User(s)

 HESA Karrar

### Weapons Carried

- 1x MK46 LWT Mod.2 Torpedo (Weapon 1688)
![image](https://user-images.githubusercontent.com/99646926/233386255-15daae7c-dd82-44ed-b6be-567c3fd4a5b8.png)
![image](https://user-images.githubusercontent.com/99646926/233386314-ce17c89d-b501-4f6d-aa43-f64874d51264.png)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

100

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://twitter.com/mhmiranusa/status/1649003759609978880

**Comment by Jkryos** [comment]
Added DB3K 500.
