### ISSUE TITLE
Generic - Radome

### ISSUE THREAD

**Issue by blu3ser** [PygmalionOfCyprus/cmo-db-requests#3323]
### DB Selector

DB3K

### Hypothetical

No

### Name

Building (Radome)

### Facility Type

Radar

### Country

Generic

### Sensors

None, the user add the sensor he wants.

### Mounts

None

### Magazines

None

### Comments

A Dome building is used to place radars inside it so that they are not identified by optical means.

### Sources

https://en.wikipedia.org/wiki/Radome

**Comment by PygmalionOfCyprus** [comment]
Good idea. Handled 500.
