### ISSUE TITLE
Add X-Band Radar to China LPAR

### ISSUE THREAD

**Issue by blu3ser** [PygmalionOfCyprus/cmo-db-requests#3324]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3060

### Summary of Changes

Add a X-Band radar to LPAR China Radar. The narrowly focused X band radar can focus on a specific object, and could be used to determine which objects are is a threat and which are decoys. The higher-frequency X-band radar is more accurate than UHF, and can concentrate energy on a target to make successful detection and tracking more likely. 

### Sources

https://www.globalsecurity.org/wmd/world/china/lpar-x.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Added as new sensor and facility.
