### ISSUE TITLE
Cyrano II bis and Cyrano I radar corrections

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#3327]
### DB Selector

Both

### Affected DBID(s)

Sensor_907 (DB3K) ; Sensor_195 (CWDB)

### Summary of Changes

The Cyrano II bis radar (equipping the Mirage IIIE) is listed as having a 30nm range.  According to the official Australian Air Force flight manual, it has a range of 27nm (RAAF "Flight Manual Mirage IIIO and IIID (AAP 7213.003-1 dtd 01Jun78, pgs.  1-93.    Available here: https://mega.nz/folder/CJEh1SxL#EY5iBc-FCk9h8PhJ4hbsnw.  

The radar is listed in the database as being a pulse doppler radar with full LDSD capability.  I believe this is incorrect.  The pulse doppler portion of the Mirage was the navigation radar, which is separate from the Cyrano system. See 1-121 of the RAAF manual above and section 1.3 of http://www.airvectors.net/avmir3_1.html.    The first Cyrano radar to have limited LD/SD was the Cyrano IV-1.  See https://www.wikiwand.com/en/Dassault_Mirage_F1 citing Jackson World Air Power Journal Volume 17 Summer 1994  p. 56.  Further, the book "Sea Harrier FRS 1 vs Mirage III/Dagger: South Atlantic 1982. London: Bloomsbury Publishing, 2017., pp 37-38." also claims the Cyrano in the Mirage IIIE had no LD/SD capability (pages attached to this update request)
![pg 37B](https://user-images.githubusercontent.com/99547401/233801711-221f0fa0-19e6-4787-9de3-4fa69c492618.jpg)
![pg 37A](https://user-images.githubusercontent.com/99547401/233801713-f84b74ad-d7c9-4f29-90b4-2a2b35af1296.jpg)  Accordingly, I believe both the pulse doppler and the LD/SD characteristic of the Cyrano II should be removed.

### Sources

 RAAF "Flight Manual Mirage IIIO and IIID (AAP 7213.003-1 dtd 01Jun78, pgs.  1-90A, 1-93, 1-98 ; https://mega.nz/folder/CJEh1SxL#EY5iBc-FCk9h8PhJ4hbsnw

Dildy, Douglas C., and Pablo Calcaterra. Sea Harrier FRS 1 vs Mirage III/Dagger: South Atlantic 1982. London: Bloomsbury Publishing, 2017., pp 37-38.

https://www.wikiwand.com/en/Dassault_Mirage_F1

**Comment by CV60LCC19** [comment]
One additional comment: The Cyrano II was IOC in 1964, so it should be listed as a 1960's radar, not a 1970's radar.  See page 41 of attached (in French).
[histoire.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/11304615/histoire.pdf)

**Comment by CV60LCC19** [comment]
For the same reason, the earlier (1958-era) Cyrano I radar (DB3K sensor_908; CWDB sensor_196) should be listed as a early 1960's radar, with no LD/SD or Doppler capability. Although the 1960 era AN/ASG-18 prototype radar had a LD/SD  capability, (see https://en.wikipedia.org/wiki/AN/ASG-18)  the first operational LD/SD radar was AWG-10/APG-59 combination in the F-4J, IOC in 1966. https://en.wikipedia.org/wiki/McDonnell_Douglas_F-4_Phantom_II

**Comment by PygmalionOfCyprus** [comment]
Handled 500.
