### ISSUE TITLE
Iranian Bavar-373 SAM, parameters update

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#333]
### DB Selector

DB3K

### Affected DBID(s)

#3229, 5997, 6035 and 3625

### Summary of Changes

Please update the Bavar-373 SAM of Iran with the following data, see sources.

Also increase the Bn setup of four vehicles to six.

### Sources

https://irangeomil.blogspot.com/2019/08/irans-bavar-373-profile.html
![Bavar](https://user-images.githubusercontent.com/60408110/154852178-42fa5656-4774-42da-92ff-0815f6c65759.jpg)

Bn setup of 6 vehicles instead of 4
![photo_2019-08-22_09-23-30](https://user-images.githubusercontent.com/60408110/154852312-01a9d1a9-f874-4810-9f27-592511d893b8.jpg)

**Comment by Huib18** [comment]
And maybe some suitable pictures for the database.
![637413062700850986](https://user-images.githubusercontent.com/60408110/154853689-89033fd7-a3ed-4c7f-929b-627eb7372792.jpg)
![iranian-bavar-373-sam-analysis-2019](https://user-images.githubusercontent.com/60408110/154853694-6d199248-479f-41d1-a437-5eb45c762b29.jpg)
![ECaGZ7eX4AItJIU](https://user-images.githubusercontent.com/60408110/154853733-a5c18d80-25a8-4ec1-86a1-d8f709743170.jpg)

**Comment by Huib18** [comment]
I will post a new item for the Meraj-4 Search radar attached to the Bavar-373 Bn in a new facility issue.

**Comment by PygmalionOfCyprus** [comment]
Handled as part of an earlier news roundup.
