### ISSUE TITLE
Update/correction for Mi-17 helicopter family

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3331]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5900 & all MI-17/M171

### Summary of Changes

- Add 1x 7.62mm facing starboard as most of MI-17 were seen with below configuration.
![image](https://user-images.githubusercontent.com/99646926/233815857-0b06ce54-54de-4f7b-a498-4f8420e24735.png)

- Add SAR loadout to all MI-17, the helicopter were seen to be equipped with winch on the port side.
![image](https://user-images.githubusercontent.com/99646926/233820190-9b32e815-74f3-41b2-82e8-1847bb89420b.png)

- Some MI-17 do have flare dispenser like (Aircraft 5660), like the one owned by India, Ukraine and Poland. Syrian and Iranian Mi-17 were also believed to be fitted with such system.
![image](https://user-images.githubusercontent.com/99646926/233815749-290ee6d5-207d-445d-be26-94fb098fb280.png)
![image](https://user-images.githubusercontent.com/99646926/233815792-d9ac0db1-ab19-4eef-9221-a3d93f34536f.png)
![image](https://user-images.githubusercontent.com/99646926/233814857-4c93c503-4682-4822-877f-5d23d333b514.png)

- Glass cockpit, IRCM, LWR,MAWS and flare dispenser were available to some MI-17V5 models like Indian Airforce one. Canadian CH-178 is also probably the same. This configuration also applied to MI-171V5/MI-8MTV-5 variant like (Aircraft 5900 & 2223).
![image](https://user-images.githubusercontent.com/99646926/233819820-69d2022a-a237-46c8-95fe-f6ba02bcd577.png)

- Starboard-facing 12.7mm gun, Glass Cockpit[partial], LWR, RWR and MAWS is available for Chinese MI-171(Aircraft 2489)
![image](https://user-images.githubusercontent.com/99646926/233820470-5a4b728f-a6c4-49dd-adda-291193774d83.png)
![image](https://user-images.githubusercontent.com/99646926/233820500-51fec96a-3c8b-4976-8a9a-4b70f2e1a85a.png)
![image](https://user-images.githubusercontent.com/99646926/233820397-0c5a471b-c770-4807-82cb-5fce88b4a8a6.png)
![image](https://user-images.githubusercontent.com/99646926/233820510-79c746ce-2eab-4d2b-b6c0-db19ac92a169.png)

 
- Add civilian variant of MI-171A2. This variant have Glass Cockpit and can carry up to 24 passengers while retains cargo capacity of military version. 
![image](https://user-images.githubusercontent.com/99646926/233820744-0d94daa7-0c02-4ccf-acaa-233b68d57ba5.png)
![image](https://user-images.githubusercontent.com/99646926/233820750-f2b2bf67-54c7-49b2-847b-638b1fe3e661.png)
![image](https://user-images.githubusercontent.com/99646926/233820779-b5a2e0af-20d7-4ae6-8b0f-c9f398c8507a.png)

### Sources

- https://www.123rf.com/photo_82140433_velika-gorica-croatia-may-13-2017-a-boy-playing-with-a-machine-gun-in-the-mi-171-sh-military-helicop.html
- https://aviagraphers.net/index.php/armed-forces-reports/61-ukraine-army-aviation
- https://www.oryxspioenkop.com/2018/10/flying-under-radar-syrias-special.html
- https://www.dreamstime.com/stock-photo-mil-mi-17-image1993460
- http://www.airvectors.net/avmil8_1.html
- https://twitter.com/sureshseshadri1/status/1468967181626929166
- https://twitter.com/IAF_MCC/status/1073060045255073793
- http://chinese-military-aviation.blogspot.com/p/helicopters-ii.html
- https://www.aerospace-technology.com/projects/mil-mi-171a2-helicopter-russia/
- https://www.rhc.aero/en/catalog/mi-171a2

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
