### ISSUE TITLE
Joint Precision Approach and Landing System (JPALS)

### ISSUE THREAD

**Issue by Goshawk-1** [PygmalionOfCyprus/cmo-db-requests#3332]
Joint Precision Approach and Landing System, or JPALS, is a software-based, high-integrity differential GPS navigation and precision approach landing system that guides aircraft onto carriers and amphibious assault ships in all weather and surface conditions. It uses an anti-jam encrypted datalink to communicate between the aircraft and an array of GPS sensors, antennas and shipboard equipment.    

**Joint Precision Approach and Landing System (JPALS)**
https://www.raytheonintelligenceandspace.com/what-we-do/air-dominance/jpals

**Comment by PygmalionOfCyprus** [comment]
Currently we assume aircraft are capable of navigating back to homeplate and landing without modelling distinct assistance tools. If we ever move into explicitly modelling these capabilities, e.g. as part of the larger comms overhaul (which you'll hear about soon), we'll revisit.
