### ISSUE TITLE
Addition: DF-21 and 26 w/ submunition warheads 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3334]
### DB Selector

DB3K

### DBID to Copy

Weapon 569, 3373

### Hypothetical

Yes

### Name

DF-21, DF-26

### Country

PRC

### Service

PLARF

### Sensors

NA

### Mounts

NA

### Loadout Options

NA

### Other Changes

Change the respective warheads to submunitions. 

### Sources

https://www.csis.org/analysis/first-battle-next-war-wargaming-chinese-invasion-taiwan

**Comment by KushanGaming** [comment]
Done for DB501.
