### ISSUE TITLE
Mirage III C overpowered

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#3338]
### DB Selector

Both

### Affected DBID(s)

Aircraft_1875, 1258, 93, 1259, 1546, 1550 (DB3K); 607, 1369, 3506, 3525, 1092, 3507, 1372, 525, 1373

### Summary of Changes

The game database lists the The Mirage IIIC's  SNECMA Atar 9B turbojet engine as producing 4281 kg thrust (military) and 6205 (afterburner).  This is too much power.  According to  
Roux, Élodie. Turbofan and Turbojet Engines: Database Handbook. Elodie Roux, 2007.  https://ptabdata.blob.core.windows.net/files/2017/IPR2017-00999/v20_GE-1019%20Turbofan%20and%20Turbojet%20Engines%20Database%20Handbook.pdf (Image below) _See also_ Mirage III v. Mig-21 (Osprey Dual Series), pg 21 (image below)

The Atar 9B produced 13,228 lb. (6012 kg) of thrust (afterburner), and 9200 lb (military static) at Sea Level.  This 
converts to 6000 kg (afterburner) and 4173 kg (military)

![2023-04-25_12-24-48](https://user-images.githubusercontent.com/99547401/234356986-f498de12-0392-410b-af43-4150d061cd83.jpg)
![2023-04-25_12-28-38](https://user-images.githubusercontent.com/99547401/234356990-14876431-901a-4ef9-b9f9-dc0a9da0ab86.jpg)

### Sources

Roux, Élodie. Turbofan and Turbojet Engines: Database Handbook. Elodie Roux, 2007.  https://ptabdata.blob.core.windows.net/files/2017/IPR2017-00999/v20_GE-1019%20Turbofan%20and%20Turbojet%20Engines%20Database%20Handbook.pdf

 Mirage III v. Mig-21 (Osprey Dual Series), pg 21

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
