### ISSUE TITLE
Addition: China, H-6K, YJ-21 Loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3339]
### DB Selector

DB3K

### User(s)

H-6K Badger

### Weapons Carried

-2x YJ-21
-2x KG-800 ECM Pod

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

1500

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

It is believed that YJ-21 has an air-launched platform and the H-6K bomber showed up on Zhuhai Air Show nailed it.

### Sources

https://en.wikipedia.org/wiki/YJ-21
https://www.thedrive.com/the-war-zone/chinas-h-6k-bomber-spotted-with-new-air-launched-ballistic-missile
https://gagadget.com/en/weapons/185882-china-showed-the-latest-hypersonic-yj-21-missile-with-a-launch-range-of-over-2000-km/
YJ-21 without booster carried by H-6K:
![image](https://user-images.githubusercontent.com/107970049/234461570-902cb6c2-0ac5-4ed1-89b9-66b6c7ca4c75.png)

**Comment by Jkryos** [comment]
Added DB3K 501.
