### ISSUE TITLE
Update of the range of the Iranian Fakour-90 Air-Air Missile.

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#334]
### DB Selector

DB3K

### Affected DBID(s)

#2784

### Summary of Changes

#2784 AIM-54A Phoenix [Fakour-90] Mod seems to have the engine of the HAWK SAM missile.

Quote of https://irangeomil.blogspot.com/2018/07/analysis-fakour-air-to-air-missile.html:
Various markings and features on the missile indicate that it is more than just an improved AIM-54 copy. In fact, it is something else entirely.

The first indication I saw that this may not be a simple copy is a marking that says "M112 ROCKET MOTOR".
The M112 Rocket Motor is the same one [used in the MIM-23 Hawk](http://spaceref.com/news/viewpr.html?pid=10428) missile, which Iran has in abundance, and manufactures as the Shahin/Salamche missile.

On another revealing stencil (below), I can just about make out "AIM-23B". AIM-23, aka Sedjil is the IRIAF designation for the air launched MIM-23 Hawk that Iran attempted to make as a substitute for low AIM-54 Phoenix stocks during the Iran-Iraq war.

The final and most physically obvious piece of evidence is the long cable duct/fuse on the side of the missile, which is not present on the AIM-54 but is a prominent feature on the MIM-23.

**The first issue with the Fakour is that it is actually worse than the AIM-54 in range performance. It has a range of 160 km compared to the AIM-54's 190 km.**

Minor correction - the AIM-54 use a semi-active guidance mode for it's midcourse, the active guidance component is only for the last 20,000 yards or so during terminal guidance. (Launches within this range band can, of course, begin in active guidance.) Given the Iranian claims that the missile has at least some active component, the Fakour probably functions similarly.

Further, if you compare the nosecones between the HAWK, the AIM-54, and the Fakour, the Fakour's more closely matches the AIM-54. As it happens, the shape of the nosecone can greatly impact the effectiveness of a radar inside the nose, with longer ogives attenuating the radar emission more. Thus, the fact that the Fakour has a nose cone which shares the same shape as the AIM-54 and which is more conducive to an active emitter lends credence to the missiles having at least some active guidance component.

### Sources

https://irangeomil.blogspot.com/2018/07/analysis-fakour-air-to-air-missile.html
https://www.youtube.com/watch?v=JFW-WaaKt90
https://twitter.com/maysam21901/status/1447658640605908994
![Fakour parameters](https://user-images.githubusercontent.com/60408110/154852885-31b6f86f-3e6d-4a10-afa5-d93d6313eafa.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Also renamed to "Fakour-90 [Mod. AIM-54A/MIM-23 HAWK]" to better reflect its origins.
