### ISSUE TITLE
No launch altitude on Blk Va Tomahawk

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#3341]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4071

### Summary of Changes

UGM-109J Tomahawk Blk Va MST has no launch altitude listed and so can only be launched on the surface. This hampers usability somewhat.

### Sources

Behavior of other Tomahawks in the database.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
