### ISSUE TITLE
SAAF CRV-7 elimination

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3344]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Aircraft 1550, 1546 and 2866

### Summary of Changes

Change CRV-7 loadouts back to 68mm SNEB pods. South Africa never operated the CRV-7. Note that the CWDB version of the same aircraft is correct and the loadout itself is called 'SNEB'.

Also, correct designation for the Mirage IIIE is 'Mirage IIIEZ'
### Sources

Database
https://www.saairforce.co.za/the-airforce/weapons/out-of-service

**Comment by PygmalionOfCyprus** [comment]
Handled 501. I went through all the SA "SNEB" loadouts and found a few other cases where the SNEB loadouts inexplicably had CRV-7s. Replaced w/ SNEB in all cases.

**Comment by FrangibleCover** [comment]
Yeah, there are actually a whole bunch of weird CRV-7 loadouts, I think there was a screwed up batch change at some point. I'm trying to get the research for the Harriers sorted out before I submit a general ticket for all of them. Some Gen 1 Harriers/Sea Harriers should have 2" Microcell rockets instead of SNEB because SNEB wasn't cleared for ship use.
