### ISSUE TITLE
Canada Hermes 900 StarLiner RPAS (NASP) x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#3345]
### DB Selector

DB3K

### DBID to Copy

5811 DB3k

### Hypothetical

No

### Name

Hermes 900 StarLiner RPAS (NASP)

### Country

Canada

### Service

Transport Canada

### In Commission

2023-

### Number in Service

1x

### Sensors

- 1x MX-15HDi EO/IO
- 1x Synthetic Aperture Radar (0.6m resolution from 20kn)
- Mapping camera
- SATCOM
- UHF/VHF (Unsecure)

### Loadout Options

- Ferry
- Maintenance
- Reserve
- Surveillance

### Sources

https://www.canada.ca/en/public-services-procurement/news/2020/12/contract-awarded-to-acquire-a-remotely-piloted-aircraft-system-for-transport-canada.html
https://nunatsiaq.com/stories/article/transport-canada-to-put-new-eyes-in-arctic-skies-with-36m-drone/
https://buyandsell.gc.ca/procurement-data/tender-notice/PW-CAG-004-27603
https://elbitsystems.com/landing/starliner-specs/
https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiLh9-Qq8j-AhX5kIkEHaqiBdMQFnoECBIQAQ&url=https%3A%2F%2Fwww.naadsn.ca%2Fwp-content%2Fuploads%2F2021%2F01%2FQuick-Impact-Canadas-New-Arctic-Drone-in-Context-Jan2021.pdf&usg=AOvVaw18xqPRtHNNeFI9eAR_etnC
https://insideunmannedsystems.com/canadas-new-drone-can-better-surveil-its-challenging-arctic-environment/

![image](https://user-images.githubusercontent.com/99632305/234689498-0fb9e514-7880-4990-a0eb-8c080be76fd6.png)
![image](https://user-images.githubusercontent.com/99632305/234689839-e2ed535b-a2eb-492a-92b2-334311fb2769.png)

**Comment by cdnice55** [comment]
Not hypothetical, sorry missed that field.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
