### ISSUE TITLE
Update: SM-6 Blk IB

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3347]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3714, 3772

### Summary of Changes

Change the target speed limit to 7000kts. 

### Sources

https://breakingdefense.com/2023/04/heres-3-future-missiles-indopacom-says-it-needs-quicker/
https://defbrief.com/2023/04/01/software-upgraded-sm-6-missile-intercepts-medium-range-ballistic-missile-in-latest-mda-test/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
