### ISSUE TITLE
Add Sonar at Corvett V-34 Barroso (Marinha do Brasil)

### ISSUE THREAD

**Issue by Potiguara69** [PygmalionOfCyprus/cmo-db-requests#3349]
### DB Selector

DB3K

### Affected DBID(s)

#2847

### Summary of Changes

Add the Hull sonar( EDO997C ) for this corvette, because in the game database this ship has no sonar. This is not correct.

### Sources

https://pt.wikipedia.org/wiki/Cv_Barroso_(V-34)

**Comment by cdnice55** [comment]
Electronic equipment:
V34: RAN-20S, RTN-30X, Scanter 4100 radars, EOS 400 e/o system, EDO997(F) sonar, SLQ-2, SLR-1X ECM suites, 2x MDLS-101 decoy RL, Siconta 3 CCS

http://www.navypedia.org/ships/brazil/br_es_barroso.htm

Confirmed sonar in Jane's 2012-13, Page 74

**Comment by Jkryos** [comment]
Updated DB3K 501.
