### ISSUE TITLE
Iranian Meraj-4 seach radar subsystem of the #3229 Bavar-373 SAM Bn

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#335]
### DB Selector

DB3K

### Hypothetical

No

### Name

Meraj-4

### Sensor Generation

Late 2010s

### Sensor Capabilities

Air Search

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info]

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm

### Scan Interval (s)

24 (3 or 6 rnds per minute)

### Target Altitude (ft)

300'- 82021 AGL

### Horizontal Beamwidth (deg)

1.4

### Vertical Beamwidth (deg)

2.5-4

### Processing Gain/Loss (dB)

Antenne gain 40 dB

### Comments

See attached image with a lot of tech specs, maybe you can extract more data than only the parameters provided above.
Like detection quality 300km of a 2m RCS Pd=0.8 and more.

Image for the database
![image](https://user-images.githubusercontent.com/60408110/154854695-89a02d5d-1381-4b03-a881-ef0390049c2a.png)
Or
https://twitter.com/muslimturk1/status/998159249229406209

### Sources

https://www.youtube.com/watch?v=DBtdCwz8VSM
https://www.youtube.com/watch?v=Wq0L_KoW9R0
https://iranpress.com/content/29939/bavar-373-air-defense-system-symbol-belief-iranian-capability
https://irangeomil.blogspot.com/2019/08/irans-bavar-373-profile.html
![mp7x_capture](https://user-images.githubusercontent.com/60408110/154854341-914ca7f4-bf85-45fc-8e68-1a350fa21eb3.jpg)
https://i.pinimg.com/originals/b7/3e/60/b73e60bca23c14dfd8c4639244359d7b.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 493, and added to the Bavar-373 facility. Great source...statdumps like this bring a tear to my eye. Beautiful.
