### ISSUE TITLE
Incorrect warhead,  weight and range of AS.20 missile

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#3350]
### DB Selector

CWDB

### Affected DBID(s)

Weapon_445

### Summary of Changes

The AS.20 missile is listed as having 

-  weight of 520kg 
- warhead of 240kg,
- range of 9nm.  

In fact, the missile weighed only 143 kg, and had a 33 kg. warhead.  _See_ "[8.0] Guided Air-To-Surface Missiles." Wayback Machine. Accessed April 27, 2023. https://web.archive.org/web/20111211034704/www.vectorsite.net/twbomb_08.html#m2. and "AS.20." Encyclopedia Astronautica. Accessed April 27, 2023. https://www.astronautix.com/a/as20.html.  _See also_ Flight, 4 November 1960 (giving warhead weight as 73 lbs/33kg)(image attached) The range of the AS.20 was only 4 or 5 nm.  _See_ Bill Gunston,  "An Illustrated Guide to Modern Airborne Missiles (Salamander, 1983)" (image attached), _accord_: https://en.wikipedia.org/wiki/AS-20.  See also Aviation Week 16 March 1964 (attached)
![Aviation Week 16 March 1964](https://user-images.githubusercontent.com/99547401/234945114-087c3e53-8ffa-4d97-843f-52c6532c3c47.PNG)
![AS 20 Modern Airborne Missiles]
![Flight 1960 - 2525](https://user-images.githubusercontent.com/99547401/234945525-4a466047-d446-4295-83b9-03186418e4bc.jpg)
(https://user-images.githubusercontent.com/99547401/234945158-db7b9f83-1027-4c88-ad1a-d896e6facc23.PNG)

### Sources

 Guided Air-To-Surface Missiles." Wayback Machine. Accessed April 27, 2023. https://web.archive.org/web/20111211034704/www.vectorsite.net/twbomb_08.html#m2
Flight, 4 November 1960 (attached)
Aviation Week 16 March 1964 (attached)
Bill Gunston,  "An Illustrated Guide to Modern Airborne Missiles (Salamander, 1983)" (image attached)
https://en.wikipedia.org/wiki/AS-20.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
