### ISSUE TITLE
Addition: ROC Indigenous Defense Submarine

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3352]
### DB Selector

DB3K

### Hypothetical

No

### Name

1168 TBD

### Class

Indigenous Defense Submarine

### Country

ROC

### Service

Navy

### In Commission

Planned 2025-

### Number in Service

Planned 8

### Length (m)

70

### Beam (m)

8

### Draft (m)

9

### Standard Displacement (t)

2100

### Submerged Displacement (t)

2500

### Complement

60

### Primary Propulsion Type

Diesel/Electric

### Propulsion

MTU 16V 396 SE, Electric Motor

### Flank Speed at Surface (kt)

12/12

### Flank Speed Submerged (kt)

12/20

### Range (nm) at Speed (kt)

15000

### Fuel Capacity (kg)

80000

### Sensors

Sensors 5861, 5862, 5863
Sensors 4822, 4895, 4896, 4897, 4898
Sensors 1593, 4533 
Side-facing Bow array. 

### Mounts

-6x 533mm, w/ provisions for: 
Mk48 Mod 6, 
UGM-84L, 
Mines.  

-2x Signal ejector: 
2x Torpedo decoy each. 

### Magazines

Torpedo: 
14x Mk48 Mod 6, or
14x UGM-84L, or
14x Mines. 
Torpedo Decoy: 
20x Decoy. 

### Comms/Datalinks

Torpedo wire. 
UHF, VHF, HF, LF radio. 

### sub Codes

Shock Resistant, Lithium-Ion Batteries, Snorkel

### Comments

The lead ship is a prototype. Many numbers are placeholder given the secrecy. 
Uses Naval Group&Navantia S-80 optical periscope, comms, power, sonar, diesel engine etc. Uses Lockheed Martin's combat system. 
AIP not included pending evaluation of the lead ship. 
X-stern. 
Li-ion battery. 
The number of torpedo tubes is placeholder. 
The long bulge on each side indicates side facing bow array. 

### Sources

https://zh.wikipedia.org/zh-cn/%E8%87%AA%E8%A3%BD%E9%98%B2%E7%A6%A6%E6%BD%9B%E8%89%A6
https://en.wikipedia.org/wiki/Indigenous_Defense_Submarine

**Comment by LuigiP57** [comment]
Update: Name: Hai Kun SS-711

**Comment by tbrandon517** [comment]
Additional 

http://www.hisutton.com/Taiwan-Hai-Kun-Submarine.html
