### ISSUE TITLE
EF-4EJ Phantom II OECM - Japan

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#3354]
### DB Selector

DB3K

### DBID to Copy

1194

### Hypothetical

No

### Name

F-4EJ Phantom II [EF-4EJ] -- Japan (Air Self-Defense Force), 1982, 4x, OECM Training

### Country

Japan

### Service

Air Force

### In Commission

1982

### Number in Service

4

### Loadout Options

OECM loadout:

2x J/ALQ-6 OECM Pod
2x 370 USG Drop Tank
1x 600 USG Drop Tank

-------------------------

other loadouts same as F-4EJ Kai (1979, ID 1194) in #2523

### Sources

related to topics:
#2523
#2584

http://www.f-4ej.com/encyc/g-z.htm

**Comment by KC45jp** [comment]
"F-4EJ Phantom II [EF-4EJ]" with comment of "OECM Training" might be better. This is because EF-4EJ is not legal or documented name. I know this is picky but I prefer "Documented name [common name]" while this is used for other type of aircrafts.

**Comment by Jkryos** [comment]
Added DB3K 501.
