### ISSUE TITLE
Zuni rocket for SU-25 Ukraine

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3355]
### DB Selector

DB3K

### User(s)

Aircraft SU-25 Ukraine 

### Weapons Carried

4 x 4 LAU-10 127mm Zuni rocket pods
2 x 1150 litre tanks.*

### Requires Buddy Illumination

No

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Assumes LAU-10 pod. 

### Sources

https://www.thedrive.com/the-war-zone/evidence-of-american-zuni-rockets-arming-ukrainian-su-25s-emerges
Twitter image is included in this article.

**Comment by bostonmyk** [comment]
Picture now available. 

https://twitter.com/TheBaseLeg/status/1656195879416758273?cxt=HHwWgoDQ8ZPY_vstAAAA
