### ISSUE TITLE
UK Rotary assets to get APKWS loadouts. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3357]
### DB Selector

DB3K

### User(s)

AH-64 All UK Army Air Corps variants post 2023. 

### Weapons Carried

APKWS Hydra rockets so assumed in 14 round pods as per CRV Loadouts.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As existing APKWS loads for AH-64E D etc

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

AH-64 both variants are very likely Wildcat AH Army and HM Navy  also possibility.
Outside chance NMH candidate helicopter may have it but unlikely given UK doctrine.

### Sources

https://worlddefencenews.blogspot.com/2023/05/us-state-department-clears-sale-of-768.html

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
