### ISSUE TITLE
Addition: KJ-600 AESA Radar

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3358]
### DB Selector

DB3K

### Baseline

sensor 2181

### Hypothetical

No

### Name

KJ-600 AESA Radar

### Sensor Generation

Early 2020s

### Range (nm)

350nm (regular DB AEW radar search range)

### Horizontal Arc (deg)

360 deg

### Sensor Capabilities

Air Search, Surface Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Non-Cooperative Target Recognition (NCTR) - Jet Engine Modulation [Class Info], Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA)

### Search/Track Frequencies

D Band (1-2 GHz) [Old L Band] 15-30 cm

### Scan Interval (s)

12

### Comments

The current type 88 for KJ-600 must be another DB legacy. Based on reasonble speculation and reality, China has made considerable advance on developing their air-borne early warning radar system. Thus, I think a new type of AEW radar should be added.

### Sources

https://www.forbes.com/sites/hisutton/2020/09/13/chinas-new-carrier-plane-is-more-than-a-hawkeye-clone/?sh=39f295c17a5b
https://newsletter.chinadailyhk.com/top_headlines/newsletter/issue/1135/articles/8/175/88/1552892631708.html
KLC-7 may be an airborne and upgraded version of SLC-7 L Band radar:
https://www.militarydrones.org.cn/slc-7-radar-p00657p1.html

**Comment by PygmalionOfCyprus** [comment]
Handled 501. Also added the classification flag to the AN/APY-9 which was missing for some reason.
