### ISSUE TITLE
Update/Correction: China, KJ-600 AEW&C, Radar replacement

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3359]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 5420

### Summary of Changes

Repalce the 3-Phased type 88 AESA radar with KJ-600 AESA radar.

### Sources

https://en.wikipedia.org/wiki/Xi%27an_KJ-600
https://www.thedrive.com/the-war-zone/our-first-clear-look-at-chinas-kj-600-carrier-based-radar-planes-nose
Obviously a rotary single-phased radardome on its back:
![image](https://user-images.githubusercontent.com/107970049/236172821-85dec109-4b2e-4a46-be3b-b5ec1ed981d2.png)

**Comment by LuigiP57** [comment]
#3358

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
