### ISSUE TITLE
Correction: Taiwan, PGG 619 Ta Chiang & PFG 1202 Kang Ding, sensor correction

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3360]
### DB Selector

DB3K

### Affected DBID(s)

ship 3441, 4149

### Summary of Changes

Replace the current Long Mountain Radar (provide long range air surveillance for TK-3 battery) with CS/MPQ-90 Bee Eye (sensor 6381, provide guidance for TC-2N). In reality, They are not equipped with TK-3 SAM let alone its surveillance radar.

### Sources

https://en.wikipedia.org/wiki/Kang_Ding-class_frigate
https://en.wikipedia.org/wiki/Tuo_Chiang-class_corvette
https://en.wikipedia.org/wiki/CS/MPQ-90_Bee_Eye
https://www.navalnews.com/naval-news/2022/12/taiwan-selects-first-kang-ding-class-frigate-for-upgrade/
Bee Eye PESA on Ta Chiang:
![image](https://user-images.githubusercontent.com/107970049/236372659-0fb0c403-0ee6-481e-ac08-cccfb86fb8dc.png)

**Comment by Jkryos** [comment]
Updated DB3K 501.
