### ISSUE TITLE
Piaggio P.166S Albatross for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3364]
### DB Selector

Both

### Baseline

-

### Hypothetical

No

### Name

P.166S Albatross

### Country

South Africa

### Service

Air Force

### In Commission

1969-1993

### Number in Service

20x

### Length (m)

11.9

### Wingspan (m)

14.69

### Height (m)

5

### Empty Weight (kg)

2650

### Maximum Takeoff Weight (MTOW) (kg)

3680

### Crew

6

### Propulsion

2x Lycoming GSO-480-B1C6 (340hp each)

### Rate of Climb (ft/min)

1240

### Service Ceiling (ft)

28000

### Military/Afterburner Speed (kt)

193

### Cruise Speed (kt)

151 (economical)

### Supercruise

No

### Ferry Range (nm)

1043

### Endurance (min)

approx 510

### Takeoff / Landing Distance (m)

451-900 range

### Fuel Capacity (kg)

1166l fuel capacity

### Sensors

Currently very notional

- 1x Generic Surface Search Radar, 60s, forward arcs only (nose extended for additional radar gear, surely this would be a surface search set?)
- 3x Recce Camera, Left/Right/Down (might be better as only two since there's no down arc?)
- 1x Searchlight

### Mounts

-

### Loadout Options

- Maritime Patrol
- SAR

### Comms/Datalinks

?

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Sources

https://www.saairforce.co.za/the-airforce/aircraft/5/p166s-albatross
https://en.wikipedia.org/wiki/Piaggio_P.166
https://www.airliners.net/aircraft-data/piaggio-p-166/294
AIRCRAFT OF THE SOUTH AFRICAN AIR FORCE by H. Potgieter and W. Steenkamp, p. 108-111

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
