### ISSUE TITLE
Piaggio P.166-DL3/SEM for Italian civilian agencies

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3367]
### DB Selector

DB3K

### Baseline

Issue #3364

### Hypothetical

No

### Name

P.166-DL3/SEM Orca

### Country

Italy

### Service

Coast Guard + Customs (two entries?)

### In Commission

1988-

### Number in Service

12+10

### Length (m)

11.88

### Wingspan (m)

14.69

### Height (m)

5

### Empty Weight (kg)

2650

### Maximum Takeoff Weight (MTOW) (kg)

4300

### Payload Weight (kg)

1073

### Crew

6

### Propulsion

2x Lycoming LTP 101-700 (600hp each)

### Rate of Climb (ft/min)

2198.2

### Service Ceiling (ft)

28000

### Military/Afterburner Speed (kt)

220

### Cruise Speed (kt)

160

### Supercruise

No

### Ferry Range (nm)

750

### Endurance (min)

420

### Takeoff / Landing Distance (m)

451-900 range

### Fuel Capacity (kg)

1166l fuel capacity

### Sensors

1x RDR-1500 radar, 360 scan
1x Generic FLIR turret, 0.3C temperature difference, gen 2?
1x Searchlight
1x Daedalus DS 1268 - I think this is an IRLS system? The Coastguard use it to detect pollutants on the water.

### Mounts

-

### Loadout Options

- Ferry (with 1x 236l fuselage tank, 2x 284l/75 USGal drop tanks)
- Maritime Patrol
- SAR (droppable rafts, 2x?)

### Comms/Datalinks

GPS

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Sources

https://en.wikipedia.org/wiki/Piaggio_P.166
http://www.aviobook.com/military/I.CGAS/I.CGAS.ENG.html
https://www.key.aero/article/european-maritime-patrol-aircraft-0
https://www.osti.gov/servlets/purl/204019 - p.15 for stats on the Daedalus system
![image](https://user-images.githubusercontent.com/109925704/236671621-6ae1ee77-c731-425f-af46-d7e985b2ec6f.png)
Daedalus DS 1268 imagery

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
