### ISSUE TITLE
Self Protection Systems for SAAF Oryx helicopters (unripe)

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3368]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4482 and 6067, Issue #3237

### Summary of Changes

Equip all aircraft with CRWS radar warning receiver #2691 
Equip the basic Oryx with the Generic Weather Radar
Rename the Drummer II's CMDS to a generic option with 120 shots

Introduction of CMDS not yet clear.
MAWS fit not yet clear.
Claim of 'EWSPS' (suspected to be the same SPJ-200 RWR as Cheetah?) not substantiated.

### Sources

http://www.saairforce.co.za/the-airforce/aircraft/53/oryx
Images show a black dot above the cockpit door windows and another at the root of the tail boom, these are CRWS.
![image](https://user-images.githubusercontent.com/109925704/236706047-3af2e8d1-2907-4e3d-8dd6-f9b01a4ae28d.png)
Image from 2000 shows CMDS on pre-Drummer Oryx. No date on how far back it should go.
https://www.baesystems.com/en-uk/product/ale-47-airborne-countermeasures-dispenser-system - BAE Systems does not claim South Africa to be an ALE-47 operator

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
