### ISSUE TITLE
Black Snake towed array turn off the Sonar button.

### ISSUE THREAD

**Issue by Tobias02** [PygmalionOfCyprus/cmo-db-requests#3370]
### DB Selector

DB3K

### Affected DBID(s)

sensor 5777

### Description of Problem

In the latest generation Italian ships, such as L 9890 Trieste and P 433 Marcantonio Colonna, I noticed that the blue button of the "active" sonar in the unit emcom (inherit from parent) goes off after clicking on another unit and returning on the ship in question. After some tests I noticed that the problem comes from the Black Snake sensor [Wass/Morpheus]. If I remove this sensor from the ships in question, the problem disappears. I apologize if I explained myself badly!

**Comment by PygmalionOfCyprus** [comment]
Could you post this in the tech support forums? This sounds like a UI/sim-side problem rather than a DB issue.
