### ISSUE TITLE
Add PLARF TB-001 Twin-Tailed Scorpion Drone

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3373]
### DB Selector

DB3K

### Baseline

aircraft #5441

### Hypothetical

No

### Name

TB-001 Twin-Tailed Scorpion

### Country

China

### Service

PLARF

### In Commission

2021

### Length (m)

10m

### Wingspan (m)

20m

### Height (m)

3.3m

### Empty Weight (kg)

1400

### Maximum Takeoff Weight (MTOW) (kg)

2,800 kg

### Payload Weight (kg)

1,000 kg

### Crew

0

### Propulsion

Piston Type

### Service Ceiling (ft)

26000

### Military/Afterburner Speed (kt)

190 kt

### Cruise Speed (kt)

115

### Supercruise

No

### Ferry Range (nm)

6,000 km (3,700 mi, 3,200 nmi)

### Endurance (min)

2100

### Sensors

EO/IR Sensor 3rd Generation, Illuminator for laser-guided weapons

### Mounts

5 hardpoints on each wing, 2 center line 

### Loadout Options

Standard Recon
Strike 10-12 AKD-10, FT-10, LJ-7 Blue Arrow ATGM, TL-2 ATGM

### Comments

Dimensions similar to Turkish Aksungur
Might be in service with PLARF 

### Sources

Stats
https://en.wikipedia.org/wiki/Tengden_TB-001
https://twitter.com/intel1osint100/status/1599754127273492481?lang=en
https://gagadget.com/en/uav/241719-chinas-tb-001-scorpion-male-drone-with-a-6000km-range-and-35-hours-of-flight-time-has-completed-an-unprecedented-miss/
https://twitter.com/intel1osint100/status/1599754127273492481/photo/1
IOC stuff:
https://www.thedrive.com/the-war-zone/chinese-tb-001-scorpion-drone-encircled-taiwan
https://twitter.com/jointstaffpa/status/1430467773356855297
https://www.janes.com/defence-news/air-platforms/latest/airshow-china-2021-tengden-debuts-three-engine-twin-tailed-scorpion-a-armed-reconnaissance-uav
https://twitter.com/RupprechtDeino/status/1614579311721254912
https://twitter.com/dafengcao/status/918323912181661696?lang=en

**Comment by LuigiP57** [comment]
Might better add a surface search radar (SAR?) since there is a radome like thing under its nose.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/592b8c87-6ede-40e1-9321-e9ebc606f632)

**Comment by bostonmyk** [comment]
https://www.hsdl.org/c/view?docid=874944

**Comment by tbrandon517** [comment]
Quite a loadout.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/7ff5ec02-c682-4ed2-be3a-999c0f437582)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/4bc14b05-10fb-4ef8-9060-9c67b1f3927f)

**Comment by Jkryos** [comment]
Added DB3K 504.
