### ISSUE TITLE
A44 Torpedo (Modified Mk.44 for South Africa)

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3374]
### DB Selector

DB3K

### Baseline

DB3k Weapon 1025

### Hypothetical

No

### Name

A44

### Length (m)

as basis

### Width/Span (m)

as basis

### Diameter (m)

as basis

### Weight (kg)

as basis

### Range (nm)

2?

### Target Altitude / Depth (ft)

as basis

### Target Speed (kts)

Torpedo speed improved to 32kts

### Warhead

New 45kg shaped charge

### Targets

Submarine

### CEP (m)

improved

### Sensors

1x torpedo seeker, early 80s, 0.5nmi

### Weapon Codes

Search Pattern, Bearing-Only Launch (BOL), Re-Attack Capability

### Comments

Could receive surface vessel tag, on the basis of the marketing brochure? Are surface vessels a usual thing to quote range and lethality against for lightweight torpedoes?

Annoyingly, no date beyond 'during the 1980s'.

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/0a477dfd-72ce-4c6b-92f9-34893cd07328)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/13c9b9ec-3a24-4d42-a1b5-34366d5986e9)
https://www.secretprojects.co.uk/threads/south-african-indigenous-naval-projects.8895/page-3#post-207347
https://www.saairforce.co.za/the-airforce/weapons/49/mk-44-torpedo
https://en.wikipedia.org/wiki/Mark_44_torpedo - totally unsourced but has a bit on the South African upgrade

**Comment by PygmalionOfCyprus** [comment]
I'll bet the "surface target" is primarily for snorkelling/surface-travelling submarines, esp. with an ASW-optimized warhead. Handled 501.
