### ISSUE TITLE
Aircraft #5861 - AW.149 (Poland - 2022) Update all the AW.149 with a SAR/CSAR loadout?. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3377]
### DB Selector

DB3K

### User(s)

Aircraft #5861 - AW.149 (Poland - 2022) 

### Weapons Carried

Pintle 7.62mm GPMG  port and starboard.
Update with SAR and CSAR loadouts please.
The headline article for the AW.149 "Battlefield Born" Air International May 2023 pp. 34 to 48. Goes into depth on SAR CSAR capability including the fact it has pre-programmed flight profiles for search and rescue in its autopilot.
The linked image below shows AW.149 with a winch fitted.
SAR could be added to most AW.149 users as well as Poland?

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

300nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The aircraft will also probably have an extensive self defence aid suite MAWS DIRCM chaff flares laser warning etc.

### Sources

https://www.airplane-pictures.net/photo/586395/csx81890-agusta-westland-agusta-westland-aw-149/
https://helicopters.leonardo.com/en/products/aw149 -- the manufacturer stuff. 
Very nice photo complete with winch and EO turret plus search light. 
Also old school magazine article: AW.149 "Battlefield Born" Air International May 2023 pp. 34 to 48. Glen Sands.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.

>The aircraft will also probably have an extensive self defence aid suite MAWS DIRCM chaff flares laser warning etc.

These are definitely possible, but not always installed. I don't see dispensers, DIRCM, etc. on the Thai helos for instance.

**Comment by Huib18** [comment]
New photo's have been shown of the Polish AW-149
Please add sensor #5617 STAR Safire 380
Missile Approach Sensors 
RWR(2x front and 2x aft).
Chaff/flare box on both sides of the tailboom.
Laser warners near the gun doors.

No DIRCM visible
No winch visible.

Source:
[https://polska-zbrojna.pl/home/articleshow/40317?t=Debiut-polskiego-AW149](url)
[https://twitter.com/scramble_nl/status/1719388299226226758?newtwitter=true](url)
![AW149-Polonia-entrega-1-](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/df98ecc3-e96e-428b-9944-6ffb3bfa1560)
![Poland_Army_Aviation_AW149_delivery_credit_Poland_MoD](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/23579a9c-baeb-4dc0-85f2-fe9efd739947)

**Comment by PygmalionOfCyprus** [comment]
Good looking helicopter.

Added sensor suite, M60s, chaff/flares, and updated loadouts for 505.

**Comment by Huib18** [comment]
Awesome, thanks for the update!

Op di 30 jan 2024 om 19:57 schreef PygmalionOfCyprus <
***@***.***>:
