### ISSUE TITLE
Marine Protector WPB's transferred to Uruguay and Lebanon

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#338]
### DB Selector

DB3K

### DBID to Copy

ship/2437/DB3K

### Hypothetical

No

### Name

WPB Marine Protector

### Country

Uruguay, Lebanon

### Service

Navy

### In Commission

2022-

### Sensors

No Change Known

### Mounts

No Change Known

### Loadout Options

No Change Known

### Other Changes

No Change Known

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2021/december/11163-navy-of-uruguay-takes-delivery-of-three-us-protector-class-patrol-vessels.html?fbclid=IwAR2-DRv8a_y7BWzTjF-OqgwTvXviAXjLeBEzObBlzjxdPyENhQ06f3x76NA

https://www.navalnews.com/naval-news/2022/02/u-s-coast-guard-to-hand-over-protector-class-boats-to-uruguay/?fbclid=IwAR3Ano6WQPVqZZoiNLxzKyNKjvQrVgieGZaTOK9S0ZUxL3jzKFjflx_Ukhg

https://www.defensenews.com/naval/2022/02/14/lebanons-navy-to-receive-multipurpose-boats-from-italy-patrol-boats-from-united-states/?utm_medium=social&utm_source=facebook_Defense_News&fbclid=IwAR089P_CJsY-e5WvPGUdppizJnBlM-fEITyNGvdUTbYUHzkkC0pDyDAag90

**Comment by PygmalionOfCyprus** [comment]
Added 493. Using the USCG name/designation until we get info on what the Uruguayans are calling it.
