### ISSUE TITLE
Australia -MV Sycamore training vessel

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3380]
### DB Selector

DB3K

### Baseline

DB3K ship 4084

### Hypothetical

No

### Name

MV Sycamore

### Class

Damen OPV 2400

### Country

Australia

### Service

Navy

### In Commission

2017-

### Number in Service

1x

### Length (m)

94 m

### Beam (m)

14.4 m

### Draft (m)

3.9 m

### Standard Displacement (t)

2,400 t

### Full Displacement (t)

2,935 t

### Empty Displacement (t)

Not Stated

### Complement

22

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

2x Deisel Engines, 2x Shafts

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

17.8 kts

### Range (nm) at Speed (kt)

 5,550 nm @ 16.2 knots

### Sensors

Terma Scanter Radar

### Mounts

FFBNW 76mm main gun and up to two 20mm secondary guns.

### Aircraft & Docking Facilities

Flight Deck and Hangar (able to support up to MH-60R)
2x Davits for lifeboats 
2x Davits for RHIBs

### Comms/Datalinks

VHF/UHF
SATCOM

### Ship Codes

Passive or Single Stabilizers

### Sources

https://en.wikipedia.org/wiki/MV_Sycamore
https://www.navy.gov.au/mv-sycamore
https://www.naval-technology.com/projects/mv-sycamore-multi-role-aviation-training-vessel-matv/
https://www.globalsecurity.org/military/world/australia/mv-sycamore.htm

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/233f551f-6fa0-4f8f-baf6-7e274e6e5797)

**Comment by Jkryos** [comment]
Added DB3K 501.
