### ISSUE TITLE
India - A40 Dhruv Tracking Ship

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3381]
### DB Selector

DB3K

### Hypothetical

No

### Name

A40 Dhruv 

### Class

Dhruv 

### Country

India

### Service

Navy

### In Commission

2021-

### Number in Service

1x

### Length (m)

175 m

### Beam (m)

22 m

### Draft (m)

6 m

### Standard Displacement (t)

15,000 t

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

300

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

2 × diesel engines in CODAD, 9,000 kW (12,000 hp) each 3 × auxiliary generators 1,200 kW (1,600 hp) each 15 MW power

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

21 kn

### Range (nm) at Speed (kt)

Not Stated

### Sensors

X-Band AESA Radar
S-Band AESA Radar
ELINT
Sea floor mapping sonars

### Mounts

None stated.

### Aircraft & Docking Facilities

Flight deck for 1x Helicopter
Davits for lifeboats and RHIBs

### Comms/Datalinks

VHF/UHF
SATCOM

### Sources

https://en.wikipedia.org/wiki/INS_Dhruv
https://www.hindustantimes.com/india-news/ins-dhruv-india-gets-its-first-nuclear-missile-tracking-ship-today-details-here-101631233967587.html
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2021/september/10658-india-to-commission-ins-dhruv-first-long-range-ballistic-missile-tracking-ship.html
https://unacademy.com/content/upsc/study-material/national-security/ins-dhruv/
https://www.forbes.com/sites/sebastienroblin/2021/03/17/india-quietly-deploys-huge-spy-ship-designed-to-track-nuclear-missiles/?sh=3b085b61179b
https://navalpost.com/india-commissions-ins-dhruv/

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/895c28bb-6f80-4afa-82a8-c1d43225df1d)

**Comment by Jkryos** [comment]
Added DB3K 501.
