### ISSUE TITLE
India - A41 Anvesh

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3382]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

A41 Anvesh

### Class

Anvesh

### Country

India

### Service

Navy

### In Commission

2022-

### Number in Service

1x

### Length (m)

118.40 m

### Beam (m)

20 m

### Draft (m)

7.1 m

### Standard Displacement (t)

11,300 t

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

150

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

2 × 5,000 kW (6,705 hp) prop motor 2 x 4,200 mm (165 in) CPP-Contra-Rotaing Pod Propeller 1 × 1,000 kW (1,341 hp) Forward Tunnel Thruster

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

18.5 Knts

### Range (nm) at Speed (kt)

Not Stated

### Sensors

LRDE Long-Range Multi Function Radar
electro-optical missile tracking
S-band radar tracking
Sonars

### Mounts

4 x Ship launch systems for AD-1 and AD-2 BMD test missiles

### Aircraft & Docking Facilities

Lifeboat and RHIB davits

### Comms/Datalinks

VHF/UHF
SATCOM

### Ship Codes

Passive or Single Stabilizers

### Sources

https://en.wikipedia.org/wiki/INS_Anvesh_(A41)
https://www.hindustantimes.com/india-news/sea-trials-for-floating-missile-test-range-ins-anvesh-begin-this-month-101630984781024.html
https://www.navalnews.com/naval-news/2023/04/india-conducts-first-test-of-new-ship-based-bmd-system/
https://pib.gov.in/PressReleasePage.aspx?PRID=1873179
https://www.outlookindia.com/national/all-about-india-s-ad-1-missile-interceptor-whose-trial-was-successfully-conducted-on-wednesday-news-234287
https://en.wikipedia.org/wiki/Indian_Ballistic_Missile_Defence_Programme

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/1cd5117d-b485-4bb7-903e-9b6a6f8d6846)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/022b24a6-a1b9-4bef-8c23-9f0803a4c7d0)

**Comment by Jkryos** [comment]
Added DB3K 501.
