### ISSUE TITLE
#4937 - CH-47F Chinook (Germany [FRG/Reunified] - 2022) -- Not HYPOTHETICAL UNIT ?? DASS and other equipment updated

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3383]
### DB Selector

DB3K

### Affected DBID(s)

AIRCRAFT #4937 - CH-47F Chinook (Germany [FRG/Reunified] - 2022) -- HYPOTHETICAL UNIT

### Summary of Changes

https://www.dsca.mil/press-media/major-arms-sales/germany-ch-47f-chinook-helicopters

More information on proposed sale including defensive suite, armour, minigun mounts radios etc. 
Most notable:
1x AN/AAR-57 CMWS
1x AN/ALQ-212 ATIRCM
1x AN/APR-39(V)1
1 x AN/AVR-2B Laser Detecting Sets
AN/AVS-6 Night Vision Devices (NVD) #2241

M134 gun mounts weapon #3901

### Sources

https://www.dsca.mil/press-media/major-arms-sales/germany-ch-47f-chinook-helicopters

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
