### ISSUE TITLE
Please add General Atomics Mojave UAS

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#339]
### DB Selector

DB3K

### Baseline

MQ-9?

### Hypothetical

Yes

### Name

General Atomics Mojave UAS

### Country

United States

### Service

In development

### In Commission

Is In development

### Length (m)

9

### Wingspan (m)

16

### Height (m)

3.2

### Empty Weight (kg)

1542

### Maximum Takeoff Weight (MTOW) (kg)

3175

### Payload Weight (kg)

1633

### Crew

Unmanned

### Propulsion

Rolls Royce M250 (450 SHP)

### Service Ceiling (ft)

Possibly same as MQ-9

### Military/Afterburner Speed (kt)

Possibly same as MQ-9

### Cruise Speed (kt)

Possibly same as MQ-9

### Supercruise

No

### Ferry Range (nm)

Possibly same as MQ-9

### Endurance (min)

Max 1500 min. In ISR role 

### Takeoff / Landing Distance (m)

ISR payload 122m. For the rest see diagram @ https://www.overtdefense.com/wp-content/uploads/2021/12/gaasi-mojave-fact-sheet-875x1024.jpg

### Sensors

High defenitinon EO/IR, SAR/ GMTI and SIGINT can be included.

### Mounts

12x Hellfire missiles at the maximum.
Hardpoints:
4x 650 lbs  hardpoints
1x 500 lbs hardpoint on the centreline (maybe for the SIGINT pod?
2x 350 lbs hardpoints.

See:  https://www.overtdefense.com/wp-content/uploads/2021/12/gaasi-mojave-fact-sheet-875x1024.jpg

### Loadout Options

12x Hellfire missiles or ISR only or SIGINT pod.
6x Hellfire is probably also possible.

### Comms/Datalinks

Possibly same as MQ-9

### Aircraft Codes

Fly-by-Wire, Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Navigation (INS/GPS)

### Sources

https://twitter.com/TheDeadDistrict/status/1469223234050658306
https://twitter.com/Ch_Ru_GER/status/1469219261126217728
https://www.overtdefense.com/2021/12/09/general-atomics-unveils-stol-capable-mojave-uav/
https://www.youtube.com/watch?v=cAEKNVpnGC4&feature=youtu.be
https://www.ga-asi.com/ga-asi-announces-new-mojave-uas

**Comment by PygmalionOfCyprus** [comment]
Related to PygmalionOfCyprus/cmo-db-dev#50 and Mantis [2857](https://cmano.net/view.php?id=2857).

**Comment by tbrandon517** [comment]
Additional Sources 

https://www.thedrive.com/the-war-zone/43438/general-atomics-rough-field-capable-mojave-drone-breaks-cover
https://www.thedrive.com/the-war-zone/43936/check-out-the-gun-pods-on-the-rugged-mojave-unmanned-aircraft?fbclid=IwAR0WNxI6YUBXOlFqQGT9pNSK6D33IW98RG6PQ_E_3zFbDgKsdWABN3tIAy0

**Comment by PygmalionOfCyprus** [comment]
Added 494.
