### ISSUE TITLE
Latvia - SSM Bty (Naval Strike Missile (NSM))

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3396]
### DB Selector

DB3K

### DBID to Copy

DB3k facility 3510

### Hypothetical

No

### Name

SSM Bty (Naval Strike Missile (NSM))

### Country

Latvia

### Service

Navy

### In Commission

2024-

### Number in Service

uncertain

### Sensors

No known change

### Mounts

No known change

### Loadout Options

N/A

### Other Changes

No known change

### Sources

https://navyrecognition.com/index.php/naval-news/naval-news-archive/2023/may1/13118-us-approves-sale-to-latvia-of-naval-strike-missile-coastal-defense-system.html?fbclid=IwAR24oaMiQXSzlS9E69dWvWbla5lR5RL5M21tmhGIc2fdwXHqXMvUb26hUfY
https://www.defensenews.com/global/europe/2023/05/05/latvian-government-approves-110-million-naval-strike-missile-buy/
https://www.thedefensepost.com/2023/05/04/anti-ship-missile-system-latvia/

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/c6c545f2-7fe4-4b32-98c3-35833f73dcfe)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
