### ISSUE TITLE
Romania - TB2 UCAV

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3397]
### DB Selector

DB3K

### DBID to Copy

db3k aircraft 5403

### Hypothetical

No

### Name

Bayraktar TB2 UCAV

### Country

Romania

### Service

Air Force

### In Commission

2024-

### Number in Service

18x

### Sensors

Uncertain ATM

### Mounts

Uncertain ATM

### Loadout Options

Uncertain ATM

### Other Changes

Sensor and weapon details uncertain, used the Albanian model as a placeholder pending new data.

### Sources

https://airrecognition.com/index.php/news/defense-aviation-news/2023-news-aviation-aerospace/april/8984-romania-to-acquire-turkish-bayraktar-unmanned-combat-aerial-vehicles.html?fbclid=IwAR0L3JJbO8GTpusqBIWV_xP94QHT4PymFvnZVTCQt9YB44bMKUfpPH9oBic
https://www.defensenews.com/global/europe/2023/04/25/romania-awards-321-million-contract-for-turkish-tb2-combat-drones/
https://www.airforce-technology.com/news/romania-turkish-tb2-combat-drones/
https://defbrief.com/2023/04/25/romania-signs-321m-deal-to-procure-turkish-tb2-combat-drones/#google_vignette

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
