### ISSUE TITLE
USN - Fountain HSB (High Speed Boat)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3398]
### DB Selector

DB3K

### DBID to Copy

db3k ship 2696

### Hypothetical

No

### Name

Fountain HSB (High Speed Boat)

### Country

United States

### Service

Navy

### In Commission

lates 80s to the late 90s

### Number in Service

uncertain

### Sensors

Mk 1 Eyeball
NVG goggles
Navigation Radar

### Mounts

Various fits to (4x?) side weapons stations.

Most commonly the M60 7.62mm LMG

but also see with
 Single and Twin 12.7mm HMGs

an AT-4 can be carried lashed in the aft station.

### Loadout Options

N/A

### Other Changes

small Zodiac can be carried on the bow.

### Sources

http://www.hisutton.com/World%20survey%20of%20Special%20Operations%20Craft.html
https://www.warboats.org/Eschbuagh.htm
https://laststandonzombieisland.com/tag/fountain-hsb/

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/21175325-c9d9-43cc-86bf-e7d54537cc08)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
