### ISSUE TITLE
New Facility - Ground based aircraft catapults, ski-jumps, arrestor gear

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3399]
### DB Selector

Both

### Hypothetical

No

### Name

Short Airfield for Tactical Support (SATS) System

### Facility Type

Supply

### Country

Generic

### Service

Generic

### In Commission

1950s-Present

### Number in Service

N/A

### Crew

N/A

### Dispersion Radius (m)

N/A

### Sensors

None

### Mounts

None

### Magazines

None

### Aircraft & Docking Facilities

aircraft catapults and/or ski-jumps and arrestor gear

### Comments

What I am thinking is a distinct facility that could be added to a complex airbase to allow aircraft with longer take-off and landing rolls (most likely carrier-based aircraft) to use airbases with shorter runways rather than distinct single unit airbase type facilities. That way should the facility be damaged/destroyed the airbase could still be functional for helicopters or fixed wing aircraft normally capable of using the airfield.

Examples would be the testing centers at INS Hansa, JB McGuire-Dix-Lakehurst, NAS Patuxent River, or Chu Lai Air Base in Vietnam where catapults and arrestor gear enabled operational airfields where terrain did not permit longer runways. Historically, by the early 1960s, there were experimental SATS sites at Bogue Field, North Carolina, and Quantico, Virginia. At one stage it was planned for SATS to accept a range of carrier-capable naval aircraft, including the A-6 Intruder, F-4 Phantom II, F-8 Crusader, and even the ultimately abortive F-111B.

### Sources

https://www.thedrive.com/the-war-zone/41401/marines-had-an-aircraft-carrier-on-land-with-catapults-and-arresting-gear-in-vietnam
https://www.aviacionline.com/2022/01/rafale-m-to-begin-ski-jump-take-off-trials-for-indian-navy/
https://www.aviacionline.com/2022/07/super-hornet-demonstrates-its-ski-jump-takeoff-capability-in-india/
https://en.wikipedia.org/wiki/Shore-based_test_facility
https://en.wikipedia.org/wiki/Ski-jump_(aviation)
https://www.thedrive.com/the-war-zone/38324/watch-a-super-hornet-launch-off-of-a-ski-jump-during-testing-aimed-at-the-indian-navy
https://theaviationgeekclub.com/rf-14a-tomcat-taking-off-ski-jump/

Arrested Landing at Chu Lai
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/c4b3c4af-9b63-4da7-848e-50b5714b973d)

Catapult hook up at Chu Lai
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/f2fbf0c4-3636-4230-88b0-7287265012b3)

Test Ramp at INS Hansa in Goa, India
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/b0eb02bc-d78e-4af8-b9fa-dddcab6f152d)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/9ed143c6-de16-46b1-8554-2ac02100a3a8)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/3acda496-4717-4984-be96-dc91ed25a534)

Arrested Landing
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/dbcb2687-5d38-478a-a453-969f27ad9a70)

Catapult Launch at Naval Air Station Patuxent River
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/4c88ab6f-ef62-4385-9a72-cfb1f3aecdf8)

Ski-Jump Launch at Naval Air Station Patuxent River
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/afb7bd32-f0c3-4c49-acd9-a526954d8b09)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/3db62124-081b-4a0d-8098-116e4a5d2ceb)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/92194a95-4206-4443-be90-c9b824fd69c7)

Catapult Launch at McGuire-Dix-Lakhurst
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/272b253a-8501-43f1-9495-1bf5636ff741)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
