### ISSUE TITLE
Add Ethiopian Tin Shield Radar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3400]
### DB Selector

DB3K

### DBID to Copy

Facility 1634

### Hypothetical

No

### Name

Radar (Tin Shield B [5X59S/36D6])

### Country

Ethiopia

### Service

Army

### In Commission

2019

### Sensors

same

### Mounts

same

### Loadout Options

same

### Sources

35ish seconds into video:
https://twitter.com/HammerOfWar5/status/1658164683369504780?cxt=HHwWmICztdD__YIuAAAA
https://twitter.com/mahmouedgamal44/status/1657429256027217920
https://twitter.com/TheIntelLab/status/1325093742664163329?lang=en
https://twitter.com/africaken1/status/928191139328462848?lang=en

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
