### ISSUE TITLE
Add Ethiopian P-18 Spoon Rest Radar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3401]
### DB Selector

DB3K

### DBID to Copy

Facility 1653

### Hypothetical

No

### Name

Radar (Spoon Rest [P-18])

### Country

Ethiopia

### Service

Army

### In Commission

2019

### Sensors

Same

### Mounts

Same

### Sources

https://twitter.com/mahmouedgamal44/status/1657435127029325825
https://twitter.com/oryxspioenkopJP/status/1449337170292973569

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
