### ISSUE TITLE
Romanian Mig-21 Lancer Variants out of Service 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3402]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4398, 4399, 4400

### Summary of Changes

Add out of service date of 2023

### Sources

https://www.janes.com/defence-news/defence/latest/update-romania-retires-mig-21#:~:text=The%20Romanian%20Air%20Force%20(RoAF,officially%20withdrawn%20on%2015%20May.
https://twitter.com/AviatiaMagazin/status/1658132524026011649?cxt=HHwWgoC90dqv74IuAAAA
https://twitter.com/Rotorfocus/status/1658051217723981827?cxt=HHwWhoC8vYezyoIuAAAA

**Comment by PygmalionOfCyprus** [comment]
Already handled during routine news roundup.
