### ISSUE TITLE
CWDB blimp endurance too short

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#3403]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 4574-4582

### Summary of Changes

Endurance is set to 2 days and 2 hours on all these blimps. See #2959, #2960 and #2961 for correct endurance: 38h12m for the K-class ships, 200h+ for the N-class ships, and 50h30m for the M-class ships. These ships also don't have a hover band, which should probably have 0 kg/min or a similarly very, very low fuel burn rate to allow for actually just floating.

### Sources

Same as mentioned issues

**Comment by PygmalionOfCyprus** [comment]
Marking as bug because the blimps actually do have the correct endurance values in the DB. Must be something weird happening somewhere.

**Comment by PygmalionOfCyprus** [comment]
Endurance was fine on the K and M Class blimps, but I fixed it on the N Class. Will add a new propulsion type  for the hovering blimps shortly and close the ticket when I do.

**Comment by PygmalionOfCyprus** [comment]
Loiter speed is currently 0kts. It's a bit hacky, but it does work. Adding a distinct hover band for blimb types is a sim-side thing so I'm gonna close the ticket. Did bring it up with the devs though.
