### ISSUE TITLE
Update: US, ASM HAWC, active radar sensor missing

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3404]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3663

### Summary of Changes

Add 1x active radar sensor (early 2020s may be fine) cauz its available target is surface ship. It can't hit targets without sensor.

### Sources

No source needed.

**Comment by PygmalionOfCyprus** [comment]
Handled 501. AFAIK HAWC doesn't actually have a radar seeker but since the AShM version is a hypothetical of a hypothetical I don't mind giving it the capability.
