### ISSUE TITLE
Update: China, YJ-21 & DF-26B AShM, sensor tech level

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3405]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3371, 4059

### Summary of Changes

1. Give DF-26B an early 2010s tech active radar seeker and  a passive one with same level. (weapon entered service in 2015)
2. Give YJ-21 an early 2020s tech active radar seeker and a passive one with same level. (weapon first showed up in 2022)

Based on the current DF-21D sensors.

### Sources

DB legacy and reasonable speculation.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
