### ISSUE TITLE
Blackwing SL-UAV Endurance Error

### ISSUE THREAD

**Issue by transientSG** [PygmalionOfCyprus/cmo-db-requests#3406]
### DB Selector

DB3K

### Affected DBID(s)

3490. Blackwing SL-UAV

### Summary of Changes

The battery endurance given cannot reach the specified range of 500nm for the UAV. It battery lasts only 60 sec!
Edit: Realised the issue, battery endurance should be 60 min instead of sec. That way its range will be correct. 

### Sources

No source, just assuming that the range of 500nm is correct, and that the UAV is unlikely to last just 60 sec.

**Comment by FIM43-Redeye** [comment]
This was partially handled in #3285 but the endurance is now only 10 minutes, which, at 50kts, doesn't seem to make sense. Endurance of 10 hours would work, but it's currently set to 10 minutes (another typo?)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.

Target endurance is ~1hr based on this slide:
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/b00a1b66-b111-48a4-8153-98b8bceb1232)

**Comment by willpope697** [comment]
DB still has it with 60 secs of battery life

https://news.usni.org/2016/05/16/aerovironment-to-supply-blackwing-mini-uavs-for-navy-attack-guided-missile-submarines

there's another source pointing towards 1 hour ish of endurance

**Comment by PygmalionOfCyprus** [comment]
I'm not really sure what's happening here. The propulsion has a fuel consumption of 1 kg/min and the entry has 3600 units of fuel (which really should be knocked down to 60 to get that 1hr endurance). But if it's still showing as 60 seconds, then something weird is going wrong. Recommend a tech support request on the forums as this is no longer a DB issue.
