### ISSUE TITLE
US XQ-58, X-47B and MQ-25A Datalinks

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3407]
### DB Selector

DB3K

### Affected DBID(s)

4774, 5186, 3169, 4916

### Summary of Changes

It seems as though the XQ-58, X-47B, and MQ-25A UCAVs have lost their ability to deploy several munitions, such as GBU-53 Stormbreakers. This is due to the lack of Datalink required to use these weapons. Therefore, I'd recommend that the AIM-120 Missile Datalink [One-Way] comms links to the aforementioned units.

### Sources

DB499

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
