### ISSUE TITLE
Add PAC-2 GEM+ and PAC-3 ERINT Battery for Ukraine

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3408]
### DB Selector

DB3K

### DBID to Copy

2228

### Hypothetical

No

### Name

SAM Bty Patriot PAC-2 GEM+/PAC-3 ERINT

### Country

Ukraine

### Service

Air Force

### In Commission

2023-present

### Number in Service

2 batteries (12-16 launchers?)

### Other Changes

2 batteries in service (at least 1 PAC-3 ERINT and 1 PAC-2 type or a combo of both.
Delivery of a battery from Germany and 1 battery from the USA. Recent documented usage against ballistic missiles (PAC-3 ERINT interceptors used), but also shown to have PAC-2 type launchers in service (most likely GEM+) 
![UKRAINE PATRIOT](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/27a37b13-3023-4820-9e2f-cc29eaf7dd0c)
![pac-3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/d1246f13-ef22-4b70-ab8c-d3e8f5ca7965)
![pac-3 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/f124da70-b72d-4ff1-92fe-9bb4c24de229)

### Sources

https://twitter.com/clashreport/status/1658415739533967360
https://twitter.com/stellarman22/status/1658879378275590145
https://en.wikipedia.org/wiki/MIM-104_Patriot#Operators

**Comment by PygmalionOfCyprus** [comment]
Handled 501.

**Comment by GIGANTO-pithecus** [comment]
thank you

**Comment by GIGANTO-pithecus** [comment]
> Handled 501.

thank you
