### ISSUE TITLE
Correction to Zaslon-M Radar (increase range and max illuminated targets)

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3409]
### DB Selector

DB3K

### Affected DBID(s)

5193

### Summary of Changes

-increase max instrumented range 215nm
-increase max number of targets illuminated/engaged to 6 (max detected targets 24)

original zaslon had max targets of 4 and max range of 300km with a ~1m antenna. newer zaslon-m has max target illumination of 6 and max range of 400km for larger air targets with a larger 1.4m antenna and updated electronics. plus increase in max detected targets from 10 to 24.

![zaslon 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/f0938aeb-ba63-4eaa-af85-15114937b9eb)
![zaslon 1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/d868b1df-43e5-4cc6-8688-3c05a9cbb18e)

### Sources

https://www.deagel.com/Sensor%20Systems/Zaslon/a003152
https://military-history.fandom.com/wiki/Zaslon_radar
https://en.wikipedia.org/wiki/Zaslon#cite_note-milrus.com-8

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
