### ISSUE TITLE
KARA ATMACA GLCM Turkey 2025-

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#341]
### DB Selector

DB3K

### DBID to Copy

facility/1729/DB3K

### Hypothetical

No

### Name

KARA ATMACA GLCM Turkey 2025-

### Country

Turkey

### Service

Army

### In Commission

2025-

### Sensors

No Change Known

### Mounts

Remove WS-1B MLRS and replace 1 for 1 with KARA ATMACA GLCM.

### Loadout Options

No Change Known

### Sources

https://www.oryxspioenkop.com/2022/01/the-kara-atmaca-glcm-aegean-game-changer.html?m=1&fbclid=IwAR3ubxRvCiZ_T--vG4FGzYdzCPqfdZhFOnzD1MIXhNGP6SHuMEjJFsO2KwI

https://www.savunmasanayist.com/karadan-karaya-seyir-fuzesi-projesinde-kara-atmaca-imzalar-atildi/

https://www.roketsan.com.tr/en/products/kara-atmaca-surface-surface-cruise-missile 

https://navalpost.com/turkey-one-step-closer-to-develop-indigenous-cruise-missile/

![image](https://user-images.githubusercontent.com/99599482/154859815-e3bd2719-02ca-40fa-a9d6-7ac5d18ce177.png)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
