### ISSUE TITLE
increase max range from 108 to 162nm~300km for R-37M missile

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3411]
### DB Selector

DB3K

### Affected DBID(s)

915

### Summary of Changes

Test in 1994 (older model original R-37) hit a large target at 300km. Newer R-37M supposedly has max range 350 or 400km for AWAC or large bomber sized targets. Based off given test data from an older model, 300km is reasonable as a max range for the newer current model. current set 108nm max range in game is for fighter jet size targets (200 kilometers). 
![zaslon 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/7ae4f23e-ff5d-483b-b906-4da66353a65b)

### Sources

https://military-history.fandom.com/wiki/Zaslon_radar
https://en.wikipedia.org/wiki/R-37_(missile)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
