### ISSUE TITLE
Add SA-6/KWADRAT 2D (2K12 KUB UPGRADE) SAM for Ukraine

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3412]
### DB Selector

DB3K

### DBID to Copy

133

### Hypothetical

No

### Name

SA-6 2K12 KUB

### Country

Ukraine

### Service

Air Force

### In Commission

1991-present

### Number in Service

89

### Other Changes

Ukraine inherited many KUB 2K12 after 1991. Majority upgraded to Kwadrat 2D standard. Article elaborates  https://defence24.com/kwadrat-2d-digitalized-ukrainian-kub-sam-system-in-kielce in service 
~40-89 TEL/launchers in service
![KUB 3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/bba0460a-db9c-413a-a035-add9cd794052)
![kub 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/f26e6c4c-5a76-4902-8ff2-2d3fc52f4f68)
![kub 1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/bff263e7-172f-4fb6-b412-43f330f943b7)
 active

### Sources

https://en.wikipedia.org/wiki/Ukrainian_Air_Defence_Forces
https://en.wikipedia.org/wiki/Ukrainian_Air_Force
https://en.wikipedia.org/wiki/2K12_Kub

**Comment by HVAA** [comment]
Source 1 does not support this.
Source 2 whilst suggesting this, falls down when drilling down into the primary source (something that should always be done with wikipedia articles - they are of course peer edited and moderated and therefore not in and of themselves primary sources).
Source 3 suggests this and more, but the single primary source is a 'pay' site, which cant be checked (naughty wikipedia for allowing this).

Evidence to date of kills attributed to UKR AD missiles, suggests just SA-10, SA-11 and SA-8 (plus SA-7, 14, 16) up till the western equipment started to arrive.  After that point we are looking at adding Stinger, Starstreak, IRIS, NASAMS, SAMP/T and Patriot to the list.

**Comment by GIGANTO-pithecus** [comment]
> Source 1 does not support this. Source 2 whilst suggesting this, falls down when drilling down into the primary source (something that should always be done with wikipedia articles - they are of course peer edited and moderated and therefore not in and of themselves primary sources). Source 3 suggests this and more, but the single primary source is a 'pay' site, which cant be checked (naughty wikipedia for allowing this).
> 
> Evidence to date of kills attributed to UKR AD missiles, suggests just SA-10, SA-11 and SA-8 (plus SA-7, 14, 16) up till the western equipment started to arrive. After that point we are looking at adding Stinger, Starstreak, IRIS, NASAMS, SAMP/T and Patriot to the list.

Ukraine inherited many of 2K12 KUB after 1991. Lots have been upgraded to Kwadrat 2D (digitalized version) since 2015 https://defence24.com/kwadrat-2d-digitalized-ukrainian-kub-sam-system-in-kielce

Also, Slovakia and Czech Republic donating 2-4 batteries of KUB 2K12 to Ukraine in 2023
https://www.armyrecognition.com/defense_news_march_2023_global_security_army_industry/slovakia_announces_donation_to_ukraine_of_2_2k12_kub_sa-6_air_defense_missile_systems.html
https://bnr.bg/en/post/101821892/the-czech-republic-provides-ukraine-with-two-soviet-era-2k12-kub-air-defense-systems

It would make sense to add KUB to Ukraine side under name Kwadrat-2D at least.

**Comment by PavelNovak79** [comment]
I think that Oryx is wrong and that should be whole batteries not just launchers. Also designation is 2K12M3 as these batteries were modernized to this standard in 1980s to be able to use 3M9M3E missiles.

**Comment by PygmalionOfCyprus** [comment]
Oryx was specifically referring to Slovak deliveries, not to their total supply. Anyway, they almost certainly do have/had these, crummy Wikipedia sourcing aside. Added an OG version and the Kwadrat upgrade 502.

**Comment by GIGANTO-pithecus** [comment]
> Oryx was specifically referring to Slovak deliveries, not to their total supply. Anyway, they almost certainly do have/had these, crummy Wikipedia sourcing aside. Added an OG version and the Kwadrat upgrade in 502.

thank you!
