### ISSUE TITLE
IRIAF Upgraded Mig-29 (Fakour-90 capable)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3413]
### DB Selector

DB3K

### DBID to Copy

Aircraft 1346

### Hypothetical

No

### Name

Mig-29 Fulcrum A , Fakour-90 capable

### Country

Iran

### Service

Air Force

### Sensors

- Remove existing Slot Back radar (Sensor 3892)

- Add Bayyenat-I(Sensor 6997) radar to guide Fakour-90(Weapon 2784). The Mig-29`s nose is probably too small to accept AN/AWG-9 (Sensor 6993)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/58d18213-f957-42b9-a001-58f69390549f)

### Mounts

same as Aircraft 1346

### Loadout Options

same as Aircraft 1346 with addition to:

(Fakour-90 loadout)
4x Fakour-90 (Weapon 2784)
2x Fatter (Weapon 4159)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/d9dd57dd-9e0f-473f-b2ac-c95961f54384)

### Other Changes

- Change the cockpit from Steam Gauge to Glass cockpit (partial)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/2f4b9c2e-e02a-4438-bc83-44a4c33eed36)

- Update the C-704`s loadout to carry 2x Fatter (Weapon) as well

### Sources

https://stephensanford.substack.com/p/irans-f-14-fleet

**Comment by Huib18** [comment]
Must be (super) hypothetical aircraft then..?

There is no scratch of evidence of a MiG-29 and Fakour-90 let alone the radar updates..
The mentioned (single) website is full of wishes and no single piece of evidence except a photo-shopped black and white picture on the website.
(As you can see here:).
![Clipboard01](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/9687a643-65a4-420a-9c66-5df823a6b069)


Only two quotes of the website:
“The Fakour-90 not only matches the capabilities of the AIM-54 but improves on them considerably - with Iranian sources putting the range at 300km and Western experts estimating a range of around 220km - compared to the original platform’s 180km range. Like the original platform, the Fakour-90 retains a guidance system capable of providing a radar lock independently of the launch aircraft’s own radar - a key capability lacked by modern Western combat aircraft and most of those fielded by Russia (**really**?)?)

In addition to the digital upgrades to the AWG-9 radar, Iran also claims to have given the radar an improved look down-shoot down capability as well as a synthetic aperture mapping mode. (no scratch of evidence).

And please show one Iranian MiG-29 with a C-704 missile please to convince.

**Comment by capcop98** [comment]
C-704 loadout is already added . I just requesting the loadout to be added with Fatter for self-defence.  Though there is at least a source that indicates the IRIAF`s mig-29 can fire those Nasr-1 missiles 
 https://www.ruaviation.com/news/2016/2/11/4991/?h
 
 Plus how do you check whether the pics is photoshopped or not? I am just quite curious though

**Comment by Huib18** [comment]
You can try different programs online to check for photoshop signatures. Very interesting to try.

About the C-704 loadout, I personally think this is an error in the DB. I could not find photographic evidence on google and the source says this:

Technicians and experts of the Islamic Republic of Iran Air Force (IRIAF) successfully overhauled a MiG-29 fighter aircraft that had been grounded for five years, the Iranian newspaper Tasnim said on Feb. 8, 2016. T**he Iranian defense ministry also delivered** its home-made and high-precision air-launched cruise missile, ‘Nasr', to the IRIAF on Tuesday Feb. 9, 2016.

The words say two projects one the C-704 (You see it on the Phantom) and the other project is the overhaul of the MiG-29.
But what the heck. We can leave it like it is.

**Comment by capcop98** [comment]
Retitled as (Hypothetical)
