### ISSUE TITLE
Fajr-4CL & Fajr-5C seeker`s and range issue

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3416]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4242 & 4244

### Description of Problem

- Fajr-5C petered out before they reached the target. Probably also applied to Fajr-4CL as well since both have similar fuel quantity
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/81e1a9e6-74b2-475a-b785-4661fb8592f7)

- Fajr-4CL cannot engage target at max range since the weapon required the seeker to get a lock first.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/c99822f6-40d1-4508-b1f9-e19a0824e894)

### Recommended Fix

Fajr-4CL and Fajr-5
- Probably change the fuel`s quantity

Fajr-4CL only
- Add "Lock-On After Launch", "Weapon - INS/GNSS Navigation" into weapon`s property

- Change the current Guidance` type "Passive Electro-Optical (EO)" to "Inertial (INS) midcourse plus Passive terminal guidance" in order to give it the ability to properly strike targets around its max range.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/f7afcd55-30e6-481d-96a4-452c59ab20fd)
https://twitter.com/imp_navigator/status/1565761446197313536

- Also reduce its CEP 10 meters. Current CEP for Fajr-4CL is the same as unguided Fajr-4, which is 300 meters.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
