### ISSUE TITLE
Add reloads for Zelzal-series rocket system

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3417]
### DB Selector

DB3K

### Affected DBID(s)

Facility 2595, 2596, 3763, 3800, 3798, 3801

### Summary of Changes

Add magazine and reloads for Zelzal-series facilities, single launcher version like Facility 2595, 2596, 3763, 3800 will probably have 12x rockets per facility, while triple launcher version like Facility 3798, 3801  will probably have around 36x rocket per facility. ROF for this reloads probably can be around 600.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/b4d4f444-2919-4ad1-86c5-1a3fdc30594d)

### Sources

https://www.youtube.com/watch?v=6_z-NRVmVKM

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
