### ISSUE TITLE
Update/correction for Heidar-1/2 cruise missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3419]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4181, 4182

### Summary of Changes

- Change the missile`s specification to below:
Length: 3.7 m
Weight: 60 kg
Warhead weight: 13-25 kg
Dual CCD/IIR seeker
Speed: 450-500 km/h
Range: 200km

Note: current specification in DB 499 is both too heavy and long to be able to be carried by Kaman-22 and Fotros  UAV. Below is the picture of the missile next to the Fotros.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/12985464-fac6-486c-afa5-51efcb82db38)

- Add surface ship as valid target since it do have CCD/IIR seeker
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/5f92d6f4-ba63-4d85-a298-4a8a8679928f)

- Change the Guidance Type to "Inertial (INS) midcourse plus Passive terminal guidance" due to the seeker.

- Change the Kaman-22(Aircraft 6430) and Fortos`s (Aircraft 5190) Heidar loadout from 1x missile to 2x missiles.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/a79447fb-f56e-46d0-b95a-6cd104907bdf)

- Add Heidar`s missile loadout to Bell-214A as well (Aircraft 6434)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/bb090a17-c2d7-4038-ab9f-a2950c370ff2)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/49103d0b-b68b-4e29-b061-136fe814ed9b)

### Sources

- https://twitter.com/IranDefense/status/1530538263886319616
- https://twitter.com/mhmiranusa/status/1636037115891916800
- https://twitter.com/IranDefense/status/1634965286171586560
- https://www.washingtoninstitute.org/policy-analysis/insecurity-prompts-irans-deceptive-show-force

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
