### ISSUE TITLE
KC-46A Pegasus - 2023

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#342]
### DB Selector

DB3K

### DBID to Copy

aircraft/3687/DB3K

### Hypothetical

No

### Name

KC-46A Pegasus - 2023

### Country

Israel

### Service

Air Force

### In Commission

2023

### Sensors

No Changes Known At This TIme

### Mounts

No Changes Known At This TIme

### Loadout Options

No Changes Known At This TIme

### Other Changes

No Changes Known At This TIme

### Sources

https://www.thedrive.com/the-war-zone/39375/its-official-kc-46-tankers-and-more-f-35s-for-israel-but-no-advanced-f-15s-for-now

https://en.wikipedia.org/wiki/Boeing_KC-46_Pegasus#Export_bids

https://www.boeing.com/features/2022/02/boeing-kc-46a-tanker-is-a-multirole-aerial-refueling-aircraft-ideal-for-the-asia-pacific-region.page

https://www.defensenews.com/air/2022/01/04/israel-inks-3-billion-deal-for-kc-46-tankers-ch-53-helos/

https://strategypage.com/htmw/htproc/articles/20211225.aspx

https://www.defensenews.com/digital-show-dailies/idex/2021/02/23/israel-to-buy-two-kc-46-tankers-with-plans-for-more-f-35s-and-weapon-systems/

https://www.msn.com/en-us/news/world/israel-s-endless-saga-of-kc-46-refuelers-and-iran/ar-AARM9jT

https://www.jpost.com/israel-news/israel-air-force-asks-to-swap-four-kc-46-tanker-aircraft-instead-of-two-681730

https://www.jpost.com/opinion/article-689279

https://www.aerotime.aero/articles/29708-israel-early-kc-46-rejected

https://www.aerotime.aero/articles/29176-israel-wants-to-speed-up-kc-46-deliveries

**Comment by PygmalionOfCyprus** [comment]
Added as part of an earlier news roundup.
