### ISSUE TITLE
Increase Harop`s top speed and datalink range

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3420]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3271

### Summary of Changes

- Increase Harop`s top speed from 95 knot to 225 Knot
- Increase datalink from 45 nm to 108 nautical miles (200 km)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/c92e1726-9b63-496a-b7e4-239600452ed5)

### Sources

https://www.iai.co.il/p/harop

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
