### ISSUE TITLE
Mohajer-6`s endurance issue

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3421]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5020, 502, 5022, 6196, 5355

### Description of Problem

Aircrafts only have endurance of 4 hours and 42 minutes instead of 12 hours as per multiple sources
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/ce244817-2969-4525-863a-348df0aa3693)

Source:
- https://www.thedrive.com/the-war-zone/the-drones-russia-is-reportedly-receiving-from-iran-for-its-ukraine-war
- https://www.armyrecognition.com/ukraine_-_russia_conflict_war_2022/ukrainian_mod_confirms_the_use_of_iranian-made_mohajer-6_drones_in_ukraine_by_russian_army.html
- https://militarywatchmagazine.com/article/mohajer6-ukraine-strikes-odessa

### Recommended Fix

Probably can adjust the fuel`s consumption?

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
