### ISSUE TITLE
IRIAF Upgraded Mig-29 (Fakour-90 capable) (Hypothetical) 

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3425]
### DB Selector

DB3K

### DBID to Copy

Aircraft 1346

### Hypothetical

Yes

### Name

Mig-29 Fulcrum A , Fakour-90 capable

### Country

Iran

### Service

Air Force

### Sensors

- Remove existing Slot Back radar (Sensor 3892)

- Add Bayyenat-I(Sensor 6997) radar to guide Fakour-90(Weapon 2784). The Mig-29`s nose is probably too small to accept AN/AWG-9 (Sensor 6993)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/58d18213-f957-42b9-a001-58f69390549f)

### Mounts

same as Aircraft 1346

### Loadout Options

same as Aircraft 1346 with addition to:

(Fakour-90 loadout)
4x Fakour-90 (Weapon 2784)
2x Fatter (Weapon 4159)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/d9dd57dd-9e0f-473f-b2ac-c95961f54384)

### Other Changes

- Change the cockpit from Steam Gauge to Glass cockpit (partial)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/2f4b9c2e-e02a-4438-bc83-44a4c33eed36)

### Sources

https://stephensanford.substack.com/p/irans-f-14-fleet

**Comment by Jkryos** [comment]
Added DB3K 501.
