### ISSUE TITLE
Increase max target speed to 2000 m/s for 9M96D missile

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3426]
### DB Selector

DB3K

### Affected DBID(s)

3220

### Summary of Changes

9m96d max target speed is set at 2300 kts. should be 3887 kts 
Exporter/manufacturer lists 2000 m/s (mach 5.83) / 3887 kts as max target speed on website. Should be capable of intercepting tochka, scud, and psrm (mach 3-4) but not iskander (mach 6-7)
Changes: increase max tgt speed to 3887 kts
![Screenshot (114)](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/22bd7073-c89a-4d89-875a-2b0e970f6fe6)

### Sources

http://roe.ru/eng/catalog/air-defence-systems/air-defense-systems-and-mounts/s-350e-vityaz/

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
