### ISSUE TITLE
SSM-2 [Type 17] Land Attack Capability

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#3429]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3792

### Summary of Changes

It has attack Capability to Fixed Land Target [Hard/Soft].

These missiles should have newer seeker, not same as SSM-1B. It is likely same as Type-12 SSM, so Early 2010's.

### Sources

https://t.co/NtAFfCI96Y (Page 76)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
