### ISSUE TITLE
SR-72A Aurora Overhaul 

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3433]
### DB Selector

DB3K

### Affected DBID(s)

3318

### Summary of Changes

The SR-72A Aurora in CMO (DB500) has an RCS considerably higher than the SR-71, which was developed circa 30 years earlier.

It might be worth overhauling the entire DB entry to update it, or creating an entirely new entry with a different SR-72 while mostly leaving the "legacy" Aurora alone. Obviously, being a secretive / hypothetical aircraft, there is room for educated guesses. It seems likely that even an 1990s Aurora would have a smaller RCS than the Blackbird - perhaps similar to, or slightly larger than, the F-117 Nighthawk.

Should a new entry be created, or 3318 totally overhauled to 2020s+ standards, the following information could be used:

Top Speed - Mach 6; 4,000 mph; 6,400 km/h; 3,500 kn. 

Ceiling - 80,000+ feet (24,400+ metres) 

The SR-72 is to be similar in size to the SR-71 at over 100 ft (30 m) long and have the same range, with entry into service by 2030. In November 2018, Lockheed Martin stated that a prototype of the SR-72 was scheduled to fly by 2025. The aircraft is to be capable of firing hypersonic missiles.
It's also plausible, if not highly likely, that this SR-72 will be unmanned. 

The sensors would likely be similar to modern units like the XQ-58s camera system, RQ-180 equipment and possibly even similar to the F-35 / B-21 Raider. 

Darkstar could be a possible alternative name should it be decided to go more down the Top Gun: Maverick route.

### Sources

https://en.m.wikipedia.org/wiki/Lockheed_Martin_SR-72

https://www.thedrive.com/the-war-zone/lockheed-hints-heavily-again-at-existence-of-secret-high-speed-jet

**Comment by ddranidis** [comment]
What sources or evidence suggest that RCS reduction has been a design feature on Aurora/SR-72 ?

**Comment by Jkryos** [comment]
The existing platform is missing any signature modifiers. Judging by the picture and existing info I figured it was at least worth giving it a similar modifiers to the SR-71 in DB3K 501.

**Comment by PygmalionOfCyprus** [comment]
SR-72A entry currently in DB is not the same as the hinted-at hypersonic UAV SR-72 currently in development. It refers to the "Senior Citizen", the hypothesized Blackbird replacement in the 80s/90s. 

The hypersonic UAV one does warrant a new entry but not an "overhaul" to the existing entry.
