### ISSUE TITLE
Hydra-70 loadout for Mohajer-6

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3434]
### DB Selector

DB3K

### User(s)

Aircraft 5020, 502, 5022, 6196, 5355

### Weapons Carried

Rocket & Qaem-5 loadout:
6x Hydra-70 (Weapon/1929)
2x Qaem-5 (Weapon/4143)

Rocket-only loadout
12x Hydra-70 (Weapon/1929)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

100

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

No

### Comments

Below pics is for the references:
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/c49efa49-71e5-4727-b34f-bc4d1f9302c8)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/05ecfaa8-4250-4507-b55d-ff9c8369d53f)

### Sources

- https://twitter.com/IranDefense/status/1530541849278042114/photo/1
- https://twitter.com/mhmiranusa/status/1531673138072899584

**Comment by PygmalionOfCyprus** [comment]
Handled 501. Also added the Fadek family of 80mm rockets.
