### ISSUE TITLE
Ukraine Su-24 Storm Shadow Loadout 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3435]
### DB Selector

DB3K

### User(s)

Ukraine Su-24s 2023-

### Weapons Carried

2x Storm Shadow

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Probably similar to Kazoo,Kingbolt,Krypton loadouts

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://www.thedrive.com/the-war-zone/ukraine-situation-report-su-24-spotted-carrying-two-storm-shadows

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
