### ISSUE TITLE
Add Marlin RD09 USV

### ISSUE THREAD

**Issue by mdktos** [PygmalionOfCyprus/cmo-db-requests#3438]
### DB Selector

Both

### Hypothetical

Yes

### Name

Marlin RD09 USV

### Class

Marlin USV

### Country

Turkiye

### Service

Navy

### In Commission

2021-

### Length (m)

14.75

### Beam (m)

3.85

### Draft (m)

0.85

### Standard Displacement (t)

26

### Complement

Unmanned

### Max Sea State

5

### Primary Propulsion Type

Diesel

### Propulsion

2x Generic diesel engines

### Flank Speed (kt)

36

### Range (nm) at Speed (kt)

700nm @ 10kt

### Sensors

1x ANS-510D Inertial Navigation System
1x Anti-Jamming GNSS
1x SEA EYE KIRLANGIÇ Electro-optical reconnaissance & surveillance system
1x  Dipping Sonar
1x Obstacle Avoidance Sonar
1x Automatic Identification System
1x ASELSAN ARES-2NC R-ES System (ESM)
1x ASELSAN AREAS-2NC Compact R-EA System (jammer)

### Mounts

1x 12.7mm machine gun mount
4x KUZGUN surface-to-surface guided missile
2x lightweight torpedoes

### Comms/Datalinks

VHF/UHF radios
SATCOM
 4G/LTE Communication Unit

### Comments

The MARLIN RD09 Unmanned Surface Vessel is being developed by ASELSAN and SEFİNE under the coordination of the Turkish Defense Agency (SSB). It has ASuW, ASW and EW capabilities.

### Sources

https://www.defenceturkey.com/en/content/mir-usv-marlin-ausv-5296
https://www.navalnews.com/naval-news/2022/09/marlin-usv-meet-turkiyes-latest-drone-ship/
https://www.bairdmaritime.com/work-boat-world/maritime-security-world/unmanned-systems/vessel-review-marlin-turkish-multi-role-usv-for-coastal-and-offshore-naval-use/
https://www.defensehere.com/en/for-the-first-time-an-rf-guided-missile-has-been-successfully-fired-from-an-unmanned-surface-vessel

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
