### ISSUE TITLE
Sentry AEW.1 [E-3D] -2022

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#344]
### DB Selector

DB3K

### DBID to Copy

aircraft/587/DB3K

### Hypothetical

No

### Name

Sentry AEW.1 [E-3D] -2022

### Country

Chile

### Service

Air Force

### In Commission

2022

### Sensors

No Changes Known

### Mounts

No Changes Known

### Loadout Options

No Changes Known

### Other Changes

No Changes Known

### Sources

https://ukdefencejournal.org.uk/british-e-3d-sentry-awacs-aircraft-to-be-sold-to-chile/?fbclid=IwAR36uQ7X3yGY4MW2QM8LN3OcUGu3QiQPyYhPhQ7CExf-F3WJ6j3mPrAAuBA

https://www.thedrive.com/the-war-zone/43960/chile-has-bought-a-trio-of-retired-e-3d-sentry-radar-planes-from-britain-reports#:~:text=The%20Chilean%20government%20has%20reportedly%20purchased%20three%20ex-U.K.,Warning%20And%20Control%20System%2C%20or%20AWACS%2C%20radar%20aircraft.

https://www.thedefensepost.com/2022/01/21/chile-buys-awacs-uk/

https://defbrief.com/2022/01/19/chile-buys-three-retired-british-e-3d-sentry-aircraft/

**Comment by PygmalionOfCyprus** [comment]
Handled during an earlier news roundup. 493.
