### ISSUE TITLE
update 48N6DM max target speeds

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3442]
### DB Selector

DB3K

### Affected DBID(s)

2103 

### Summary of Changes

The 48n6dm has max target speed of 4800 m/s (or mach 14) according to various sources. in game is capped at 4500 kts

Correction: increase tgt max speed to 9334 kts for 48n6dm
![48n6dm](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/3cfddd37-2849-4bc4-83e2-f8cacd5e78e7)
![48n6dm3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/ca18c985-05c4-4a6c-91c2-581e8b6473f4)
![48n6dm2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/204465dc-3067-4eb1-ad57-0cf6e3ef6259)

### Sources

https://www.deagel.com/Defensive%20Weapons/48N6/a000994

https://www.ausairpower.net/APA-S-400-Triumf.html#mozTocId636925

https://military-history.fandom.com/wiki/S-400_missile_system

https://weaponsystems.net/system/1417-%3E%3E48N6

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
