### ISSUE TITLE
LSV-7 SSGT Robert T. Kuroda (General Frank S. Besson Mod)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3443]
### DB Selector

DB3K

### DBID to Copy

DB3K ship 2450

### Hypothetical

No

### Name

LSV-7 SSGT Robert T. Kuroda (General Frank S. Besson Mod)

### Country

United States

### Service

Army

### In Commission

2005-Present

### Number in Service

2x

### Sensors

No Change

### Mounts

No Change

### Loadout Options

N/A

### Other Changes

The Robert T. Kuroda is the lead vessel of a new subclass of the Frank S. Besson class called LSV (MOD). The Kuroda, named after Robert T. Kuroda, and its sister ship, the Smalls, named after Robert Smalls, are generally similar to the rest of the class except that the ships are 42 feet (13 m) longer than the other ships of the class. This is due to a more streamlined "visor" bow that hides the front ramp and allows for the vessels to move through rough water more easily. While these ships have the same main deck area as the rest of the class—10,500 square feet (980 m2)— however they displace 6,000 short tons (5,400 t), can make 10,000 U.S. gallons (38,000 L) of water a day, have incinerators for burning trash, are taller than the traditional Besson-class LSVs, and have 25% more horsepower. The ship has a range of more than 5,500 nautical miles (10,200 km) and can deploy fully provisioned worldwide at a speed of 12 knots (22 km/h) carrying a standard port-opening package weighing 1,000 short tons (910 t).

### Sources

https://en.wikipedia.org/wiki/General_Frank_S._Besson-class_support_vessel
https://en.wikipedia.org/wiki/USAV_SSGT_Robert_T._Kuroda
https://en.wikipedia.org/wiki/USAV_Major_General_Robert_Smalls

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/f3e19691-16ea-444e-ba88-9a4c3ee546c4)

Standard Besson compared to Kuroda sub-class
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/d0b1f970-8898-4ffb-a50f-e53f2dc3d733)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
