### ISSUE TITLE
LT-801 MGen Nathanael Greene

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3444]
### DB Selector

DB3K

### Baseline

db3k ship 2889

### Hypothetical

No

### Name

LT-801 MGen Nathanael Greene

### Class

MGen. Nathanael Greene-class large coastal tugs

### Country

United States

### Service

Army

### In Commission

1994-Present

### Number in Service

6x

### Length (m)

39 m

### Beam (m)

11 m

### Draft (m)

4.4 m (light), (5.2 m) (loaded), 4.9m (median)

### Standard Displacement (t)

939 t

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

24

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 diesels, 2 shafts, 2,550 bhp (1,900 kW)

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

12/13.5 knots (loaded/light)

### Range (nm) at Speed (kt)

5,000 nm at 13.5 knots (light) 5,000 nm at 12 knots (loaded)

### Sensors

Navigation Radar

### Mounts

N/A

### Aircraft & Docking Facilities

None

### Comms/Datalinks

HF/VHF/UHF
SATCOM

### Comments

Class of large US Army tugs

### Sources

https://en.wikipedia.org/wiki/MGen._Nathanael_Greene-class_tugboat
https://en.wikipedia.org/wiki/USAV_MG_Winfield_Scott

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/460451dc-0275-408c-a2fa-c0b881397070)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
