### ISSUE TITLE
F-104S interceptors can't guide Sparrows with radar

### ISSUE THREAD

**Issue by GPVR86** [PygmalionOfCyprus/cmo-db-requests#3445]
### DB Selector

Both

### Affected DBID(s)

DB3K aircraft #1728 & #2674, CWDB aircraft #2105

### Summary of Changes

Was playing the community scenario Albania Airstrike, but my F-104S fighters wouldn't launch their MRAAMs. Looking in the database, I saw that the MRAAM entry didn't have the "Can be guided by: XXX" string, as shown in the attached picture. Noticed the same thing in other F-104S fighters, both in DB3K_499 and CWDB_499. Scenario and Autosave zipped and uploaded for your consideration.

### Sources

[Sparrow won't fire.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/11682262/Sparrow.won.t.fire.zip)
![f-104s #1728](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/135907878/7f5efbb9-79b5-44af-9b9f-bfba48364418)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
