### ISSUE TITLE
Atago Class DDG with SM-6 does not exist → hypothetical 

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#3448]
### DB Selector

DB3K

### Affected DBID(s)

Ship 4085

### Summary of Changes

Please make Atago class ship 2022 into hypothetical section while this ship does not exist, not even FFBNW.

### Sources

No source while this is not exist... I wonder where does this come from originally...

**Comment by PygmalionOfCyprus** [comment]
>In 2018 the MoD indicated that the Atago class would be fitted with SM-6, although – initially at least – this plan will not progress.

https://www.janes.com/defence-news/news-detail/japan-plans-sm-6-deployment-from-2026

So a couple years ago there was reason to add this entry; plans changed, but it lives on as a hypothetical!

**Comment by PygmalionOfCyprus** [comment]
Also added new versions of Maya and Hagura w/ the SM-6s.
