### ISSUE TITLE
Light recon drones ASL altitude limited

### ISSUE THREAD

**Issue by fmachanda** [PygmalionOfCyprus/cmo-db-requests#3449]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5446, 5447, 6008, 6184, and other light drones

### Description of Problem

Not sure if this is a DB or core bug, but light recon drones like the RQ-28, RQ-20, and RQ-11 are limited to around 400-1000ft ASL in the game. In real life however, these drones are only limited to 400-1000ft AGL (not ASL) and can operate at much higher ASL altitudes (like in the mountains).

### Recommended Fix

Change the ASL limits on light drones to be much higher (and reflect ASL limits rather than AGL limits). I grouped this as one bug given that it affected so many aircraft, but here is the max ASL data I found for the specific drones I was concerned about:

RQ-11: 15000ft (https://www.avinc.com/images/uploads/product_docs/Raven_Datasheet_05_220825.pdf)

RQ-20: 10500ft (https://www.globalsecurity.org/intell/systems/rq-20.htm)

RQ-28: 15000ft (https://support.skydio.com/hc/en-us/articles/4407530253211-Understanding-Height-Limits-on-your-Skydio-2-2-Enterprise)

**Comment by PygmalionOfCyprus** [comment]
Handled 501 for the specified AC (RQ-11/20/28).
