### ISSUE TITLE
F-16AM/BM Falcon MLU Have Glass V - 2021

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#345]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 3268 and 3799 DB3K

### Summary of Changes

Danish F-16's updated with Have Glass V RCS reduction

### Sources

https://theaviationist.com/2021/04/28/rdaf-f-16s-have-glass/?fbclid=IwAR3WeiKDIexFOtjEck8Kx9BONreyd6NjC0z6LJm6uyQX58bL4HeUaN24p7o

https://theaviationist.com/2020/10/01/danish-f-16-gets-have-glass-grey-paint-its-the-same-that-will-be-applied-to-the-rdaf-f-35s/#:~:text=Danish%20F-16%20Gets%20Have%20Glass%20Grey%20Paint.%20It%E2%80%99s,70th%20anniversary%20of%20the%20Royal%20Danish%20Air%20Force.

**Comment by PygmalionOfCyprus** [comment]
Should have labelled this "on hold" ages ago with all the other RCS stuff as I dealt with the radar/IR/visual modifier rework, but it slipped under the radar. 😉 

That's done now -- and with it, I was able to create fancy new Have Glass V F-16s for the Danes. Added 494.

**Comment by tbrandon517** [comment]
I'm sure the bevy of new NATO v Russia scenarios in the forums for testing will benefit greatly.
