### ISSUE TITLE
Sturgeon Class Flank Speed Submerged should be lower

### ISSUE THREAD

**Issue by Red-88** [PygmalionOfCyprus/cmo-db-requests#3450]
### DB Selector

Both

### Affected DBID(s)

Submarine CWDB# 133, 25, 293, 294, 295, 453 DB3K# 133, 121, 116, 62, 20, 176, 328, 178, 368, 201, 197, 91, 372, 204, 330, 207

### Summary of Changes

Sturgeon Class Flank Speed Submerged is to fast (30kt) . Norman Friedman list submerged Flank Speed as 25-26kt and Norman Polmar as 26-27kt. Suggest using the middle value 26kt.

### Sources

Friedman, Norman. _U.S. Submarines Since 1945, Revised Edition_. Annapolis: Naval Institue Press, 2018. P.259, 270.

Polmar, Norman, and Kenneth J. Moore. _Cold War Submarines_. Potomac Books, 2004. P.165

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
