### ISSUE TITLE
Permit Class Flank Speed Submerged should be lower

### ISSUE THREAD

**Issue by Red-88** [PygmalionOfCyprus/cmo-db-requests#3451]
### DB Selector

Both

### Affected DBID(s)

Submarine CWDB# 222, 21, 22, 308, 309, 310 DB3K# 356, 19, 18, 17, 376

### Summary of Changes

Permit Class Flank Speed Submerged is too high (30kt). Norman Friedman list submerged Flank Speed as 28-29kt and Norman Polmar as 27-28kt. Suggest using the middle value 28kt.

### Sources

Friedman, Norman. _U.S. Submarines Since 1945, Revised Edition_. Annapolis: Naval Institue Press, 2018. P.259, 270.

Polmar, Norman, and Kenneth J. Moore. _Cold War Submarines_. Potomac Books, 2004. P.165

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
