### ISSUE TITLE
S 192 U 13 [Type 206] wrong sensors

### ISSUE THREAD

**Issue by Red-88** [PygmalionOfCyprus/cmo-db-requests#3452]
### DB Selector

Both

### Affected DBID(s)

Submarine CWDB# 59, 395 DB3K# 48

### Summary of Changes

According to Rössler Type 206 never had CSU 3-4 sonar suite. Instead it had analog unintegrated sonar set (AN 410 Active Sonar, AN 5039 Passive Sonar, DUUX 2C Passive Ranging Sonar, DUUG 1A Acoustic Intercept). EDO-900 Mine Avoidance Sonar was aquired by germany but not fitted. 

Sensors to Remove:
PRS 3-4 Hull Sonar Passive-Only CWDB# 1481 DB3K# 1805
CSU 3-4 Hull Sonar Active/Passive CWDB# 372 DB3K# 1347
IPS CSU 3 Acoustic Intercept CWDB# 1480 DB3K# 4406
EDO-900 Hull Sonar Active-Only CWDB# 2123 DB3K# 4709

Sensors to Add:
AN 410 Hull Sonar Active-Only CWDB# 716 DB3K# 4028
AN 5039 Hull Sonar Passive-Only CWDB# 1931 DB3K# 4029
DUUX 2C Hull Sonar Passive-Only CWDB# 360 DB3K# 1295
DUUG 1A Acoustic Intercept CWDB# 361 DB3K# 2423

### Sources

Rössler, Eberhard. _Die Sonaranlagen der deutschen Unterseeboote_. Bonn: Bernard & Graefe Verlag, 2006. P. 166-182; 191.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
