### ISSUE TITLE
Add ROK Navy AW159 Wildcat sonobouy loadout

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#3454]
### DB Selector

DB3K

### User(s)

ROKN AW159 Wildcat Mk.210

### Weapons Carried

10x sonobouy
1x K-745 Blue shark

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

ROKN Aw.159 can carry 10 Sonobouy

### Sources

https://m-en.yna.co.kr/view/AEN20170131011151315

https://militaryleak.com/2021/01/22/republic-of-korea-navy-aw-159-wildcat-helicopter-conducts-live-firing-of-spike-nlos-missile/?amp=1

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
