### ISSUE TITLE
Full name for British 540lb bomb

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3455]
### DB Selector

Both

### Affected DBID(s)

CWDB Weapon 1443, DB3k Weapon 2253

### Summary of Changes

Currently 'MkXX' in game, should be Mk1.
The full name is on the data sheet below, you can use whatever elements of it you like. The Mk2 is just a different fill.

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/1da9a536-f3f3-408b-893b-05f9d4ebe72f)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
