### ISSUE TITLE
RAuxAF GDF Copy/Update

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3457]
### DB Selector

DB3K

### DBID to Copy

Issue 3318

### Hypothetical

No

### Name

AAA Flt (35mm Twin Oerlikon x3, Skyguard FCR)

### Country

United Kingdom

### Service

Royal Auxiliary Air Force

### In Commission

1985-1987

### Number in Service

4x Flight

### Mounts

Add additional Oerlikon mount, initially the stolen guns didn't have their full complement of Skyguards (one destroyed by Shrike at Stanley Airfield, one destroyed by Paras at Goose Green) so they were run in flights of three.

#3318 is still a valid request but should be 1987-1993, after replacement Skyguards were procured and the flights were rearranged to the standard two gun config. It should also be a Flight.

### Sources

THE FALKLANDS GUNS by Fonfé

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
