### ISSUE TITLE
Independent Skyguard for UK

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3458]
### DB Selector

DB3K

### DBID to Copy

Issue #3318

### Hypothetical

No

### Name

Skyguard

### Country

United Kingdom

### Service

Royal Air Force

### In Commission

1993-current

### Number in Service

6x

### Mounts

Remove the Oerlikons and leave the Skyguard vehicle, with its gun director.

### Other Changes

Used after the retirement of the GDFs for adversary training and speed policing of training areas.

### Sources

THE FALKLANDS GUNS by Fonfé

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
