### ISSUE TITLE
Please add GBU-31 to the DB #1071 and #3547 the F-16E/F of the UAE

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#346]
### DB Selector

DB3K

### Affected DBID(s)

#1071 and #3547

### Summary of Changes

The F-16E/F of the UAE are also equipped with the GBU-31 which is currently not in the loadouts.

### Sources

https://www.defenseindustrydaily.com/the-uaes-f-16-block-60-desert-falcon-fleet-04538/
https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.worldwide-military.com%2FMilitary%2520Aircraft%2FUS%2520Fighters%2520plaatjes%2FGroot%2FF-16E%2520(UAE)_004.jpg&imgrefurl=http%3A%2F%2Fwww.worldwide-military.com%2FMilitary%2520Aircraft%2FUS%2520Fighters%2FF-16%2520Falcon_Algemene_info_Nederlands.htm&tbnid=_t1p7tMsgxvGBM&vet=12ahUKEwiwupz51qnzAhXB0KQKHZAtAewQMyhPegQIARB3..i&docid=YBEbUeKpeRrh8M&w=1024&h=680&q=f-16E%20UAE%20GBU-32%20Desert%20Falcon&ved=2ahUKEwiwupz51qnzAhXB0KQKHZAtAewQMyhPegQIARB3
https://www.airliners.net/photo/United-Arab-Emirates-Air-Force/Lockheed-Martin-F-16E-Fighting-Falcon/1684042

**Comment by PygmalionOfCyprus** [comment]
Final change for 493, congrats!
