### ISSUE TITLE
Karrar UCAV cannot launch from pad

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3462]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4903, 4904, 5591, 6429

### Description of Problem

The drone cannot being launch from land-based facility that have any kind of pad, but can be launched from ships just fine. Land-based facility need runway to launch it. The drones were capable of being launched via JATO method IRL so it should be able to be launched from in-game pad .
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/8a2d9228-2d37-4c51-91ed-95e1cb93ce6d)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/a2af485f-4941-4a8f-910a-2ebc19a9555c)

### Recommended Fix

Make the drones can be launched from land-based facility`s pad as well

**Comment by PygmalionOfCyprus** [comment]
This is a sim-side bug, as catapult launchers should be able to launch from land facility pads just like naval pads. Please post in the tech support forums.
