### ISSUE TITLE
Minor Corrections to TOP PLATE MR-710 Fregat M2EM radar

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#3465]
### DB Selector

DB3K

### Affected DBID(s)

Sensor_2755

### Summary of Changes

The TOP PLATE MR-710 is an "E" band, not an "E/F" band radar.  _See_ https://www.radartutorial.eu/19.kartei/11.ancient4/karte021.en.html (note: this site calls the MR-710 the TOP STEER, which is an older designation for the TOP PLATE).  _See also_ Jane's Radar and Electronic Warfare Systems 2002-03, "Fregat series surveillance radars (02 July 2001) (Images of the 2 pages attached) _See also_ https://www.deagel.com/Sensor%20Systems/Fregat/a001879

The Data base also gives it the Doppler Radar property.  The TOP PLATE series is not a Doppler, but a serially fed frequency scanning phased-array type radar.  _See_ https://www.radartutorial.eu/19.kartei/07.naval/karte091.en.html

![Jane's pg1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99547401/fd48c359-ea65-40d9-92d6-0b87e193a83c)
![Jane's pg2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99547401/2c4e4b55-816b-4c81-a21b-bef14b1f8383)

### Sources

Friedman, The Naval Institute Guide to World Naval Weapons Systems 1997-98, pg. 336 ; Jane's Radar and Electronic Warfare Systems 2002-03, "Fregat series surveillance radars (02 July 2001); "Fregat Family of Naval Radars." Key Aero. Accessed June 12, 2023. https://www.key.aero/forum/modern-military-aviation/naval-aviation/72995-fregat-family-of-naval-radars.; "MR-750 “Top Plate” - Radartutorial." Grundlagen Der Radartechnik. Accessed June 12, 2023. https://www.radartutorial.eu/19.kartei/07.naval/karte091.en.html.

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
