### ISSUE TITLE
increase S-300 Fort-M (48N6M) and 48N6E2 max target speeds

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3466]
### DB Selector

DB3K

### Affected DBID(s)

3105 , 878

### Summary of Changes

A derivative of the 48n6e2 missile and an upgrade to the 48n6m, the 48n6FM upgrade has longer range of 110nm but also a higher max target speed of mach 8.5. While 48n6e2 has max target speed of mach 8.2

Changes:
-increase Fort-M max tgt speed (dbid 3105) to 5667 kts (mach 8.5)
-increase 48N6E2 max tgt speed (dbid 878) to 5467 kts (mach 8.2)

![48n6fm2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/e0d820f2-ee38-4207-a612-2be5ec85d6a6)
![48n6fm](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/27113805-429e-4e69-9011-efea61dd3324)

### Sources

https://en.wikipedia.org/wiki/S-300_missile_system
https://en.wikipedia.org/wiki/S-400_missile_system#Specifications

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
