### ISSUE TITLE
Please add Maritime targets for GBU-31 JDAM

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#347]
### DB Selector

DB3K

### Affected DBID(s)

#90, #554 or maybe create a new variant?

### Summary of Changes

According to the 53rd Wing, partnering with the Air Force Research Laboratory, the F-15E crews developed and demonstrated new tactics, techniques, and procedures for employing modified GBU-31s on both moving and static maritime targets.

The GBU-31s in the photographs released by the U.S. Air Force appear to be GBU-31(V)1/B, using the guidance kit on an MK-84. It would be interesting to learn a bit more about the “modification” mentioned in the public release and how the JDAMs were used to engage “moving maritime targets” as JDAMs are not Laser Guided (unless they are Laser JDAMs – mentioned later) hence more suitable for use against fixed/stationary targets.

Anyway, building on a previous 53rd Wing test conducted last year (where the B-52H Stratofortress from the 49th TES dropped JDAMs in order to assess the viability of specific maritime impact conditions), the latest testing activity was carried out as part of the QUICKSINK Joint Capability Technology Demonstration, whose aim is to develop a low-cost method of achieving torpedo-like seaworthy kills from the air: a U.S. Navy submarine has the ability to launch and destroy a ship with a single torpedo at any time, but by launching that weapon it gives away the location of the vessel.

### Sources

https://theaviationist.com/2021/09/02/f-15e-gbu-31-maritime-targets/
https://www.eglin.af.mil/News/Article-Display/Article/2764143/f-15e-completes-first-successful-maritime-jdam-test/
https://www.businessinsider.com/the-air-force-is-testing-new-ship-killer-bomb-2021-9

**Comment by tbrandon517** [comment]
Additional Source

https://www.thedrive.com/the-war-zone/42234/the-air-force-is-developing-smart-bombs-with-torpedo-like-ship-killing-capability

**Comment by tbrandon517** [comment]
Updated program details

https://www.navalnews.com/naval-news/2022/03/usaf-quicksink-sudden-death-for-enemy-ships/

**Comment by tbrandon517** [comment]
From AFRL

https://afresearchlab.com/technology/quicksink/

**Comment by PygmalionOfCyprus** [comment]
Added 494. Have not created aircraft entries with it but have created the appropriate weapon records so they can be added (or so that we can add them to the F-35, F-15, etc. if this gets out of testing).

**Comment by ddranidis** [comment]
More details: https://www.thedrive.com/the-war-zone/new-look-at-air-forces-ship-killing-smart-bomb-in-action-seeker-details-revealed
* Seeker is dual-mode radar + IIR
* Method of impact confirmed as "dive right next to hull and detonate right under it or next to it".
