### ISSUE TITLE
RCS measurements

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#3471]
### DB Selector

DB3K

### Affected DBID(s)

#957 Storm Shadow and more

### Summary of Changes

On this thread multiple RCS measurements are mentioned which might be helpful for the DB. Not only the Storm Shadow but also others. 
I do not know the accuracy of course but it looks much better than a best guess of mine ;-)
If its not useful, pls disregard.

### Sources

[https://twitter.com/Flankerchan/status/1668593696525402112](url)
A thread with multiple entries
![FygDk9vaQAMgy5J](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/4c671dd5-eef3-47dd-8315-d199eb0b3d0c)
![FygEzmtaEAE76p5](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/8eb4b53f-ba63-481d-be61-7ff939ac5f21)
![FygFrd0aUAIj3fi](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/5a7528fd-8133-451a-a2b2-9521c3c396c5)
![FygBz7taAAIWrbv](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/87f49175-b164-4b6b-a211-99c394bf04b6)

**Comment by GIGANTO-pithecus** [comment]
Good catch. @Flankerchan is a great source and brilliant analyst

**Comment by PygmalionOfCyprus** [comment]
Neat info indeed. I'm closing as "wontfix" because this information is a few degrees removed from what we plug into the DB (a really neat square peg, but no less able to fit into a round hole), but thanks for the post nevertheless.
