### ISSUE TITLE
Incorrect nomenclature on Tamir-11 series sonars

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#3475]
### DB Selector

Both

### Affected DBID(s)

CWDB: Sensor_ 1019; 732; 2163; 1915; DB3K Sensor_2712, 4698, 2195, 4813

### Summary of Changes

The Tamir -11/11M series sonars are known as STAG HOOF vice STAG EAR.  This affects CWDB Sensor_1019, 732, 2163 and (arguably) 1915 (arguably since 1915 is the PLAN SJD-3, which is a copy of the Tamil-11.

Similarly, DB3K Sensors _2712, 4698, 2195, 4813 should also be similarly redesignated.

### Sources

Friedman, The Naval Institute Guide to World Naval Weapons Systems 1997-98, pg. 607 ; 
[Tamir Sonar.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/11752195/Tamir.Sonar.pdf)

**Comment by Jkryos** [comment]
Updated DB3K and CWDB 501.
