### ISSUE TITLE
Mistral for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3482]
### DB Selector

DB3K

### DBID to Copy

DB3k Facility 71

### Hypothetical

No

### Name

SAM Sec (Mistral)

### Country

South Africa

### Service

Army

### In Commission

1988

### Number in Service

50x missiles, field trials

### Other Changes

Supplied through the DGSE before the missile even entered French service, to be used in Angola in return for data on their use.

### Sources

https://www.news24.com/news24/declassified-apartheid-profits-pretorias-beehive-in-paris-20170914

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
