### ISSUE TITLE
Add M-117 750lb Bomb Loadouts to Indonesian F-16s

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3483]
### DB Selector

DB3K

### User(s)

173, 3425, 4083,4635.4084,4636

### Weapons Carried

Copy 2 existing Mk84 loadouts (25240 and 25241) and swap in M117

Add Very Heavy
x8 M117 750lb bombs
No AAMs, pods etc.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://twitter.com/AbdNav2K2/status/1667224284559986688
https://twitter.com/AbdNav2K2/status/1667225092038983680

**Comment by bostonmyk** [comment]
IDF F-16Is as well https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4355

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
