### ISSUE TITLE
Bina ASM cannot be fired for some reason

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3486]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4161

### Description of Problem

The missile cannot be fired from SU-22M even thought targeting pod like TLS-99 is already included in the loadout.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/75405e07-a32d-438a-8551-2f486511cc08)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/b3c3e324-88f5-49c4-a8b3-fdc0e67fafd5)

### Recommended Fix

Change the guidance type and add weapon`s property similar to AGM-65E Maverick Laser(Weapon/1875)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/8fa84285-44d0-4b8e-bd25-9babfc8dbe60)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/aa85863d-fa6f-4735-b88d-f4ecce7880b2)

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
