### ISSUE TITLE
Buffel MRAP for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3490]
### DB Selector

Both

### DBID to Copy

DB3k Facility 2284

### Hypothetical

No

### Name

Motor Inf Plt (Buffel)

### Country

South Africa

### Service

Army

### In Commission

1978-1995

### Sensors

-

### Mounts

Downgrade armour to Rifle-resistant, the Buffel is less armoured than a Casspir and open-topped

### Loadout Options

-

### Sources

https://tanks-encyclopedia.com/coldwar/south_africa/buffel-apc-mpv

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
