### ISSUE TITLE
Casspir redating

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3491]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Facility 2284

### Summary of Changes

Change the date for the Casspir's intro to service to 1984. The vehicle was in service with 32 Battalion of the SADF during the Border War and was also used by the 101 Battalion and Reaksiemag of the SWATF, which was a South African puppet-army. The vehicle is still in service with the SANDF.

### Sources

https://tanks-encyclopedia.com/coldwar/south_africa/casspir

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
