### ISSUE TITLE
Casspir for SAP and SWAPOL

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3492]
### DB Selector

DB3K

### DBID to Copy

DB3k Facility 2284

### Hypothetical

No

### Name

Casspir

### Country

South Africa

### Service

Police

### In Commission

1982-

### Sensors

-

### Mounts

Two variants:
- [x] No changes
- [ ] Add 20mm cannon

### Loadout Options

-

### Other Changes

The Casspir was originally designed for the South African Police, for counterinsurgency work in South Africa and in the colony of South West Africa, present day Namibia. The most notable uses of the Casspir were by the South West African Police COIN unit, the infamous 'Koevoet'. This unit was staffed almost entirely by both black and white Namibians (and Rhodesian exiles), but fell under the jurisdiction of the SAP and therefore I'm just calling them South Africans.

### Sources

https://tanks-encyclopedia.com/coldwar/south_africa/casspir

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
