### ISSUE TITLE
British Tomcat renames

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3497]
### DB Selector

DB3K

### Affected DBID(s)

All UK Tomcat (Aircraft 6116-6141 inclusive)

### Summary of Changes

British aircraft designations are a bit tricky, or possibly completely made up as the RAF goes along. They're not helped by the refusal of the air community to actually use any of the designations (find any pilot who calls the A400 the Atlas, for example). However, the following are my guesses for the 'true' designations of the British Tomcats if they entered service:

- RAF F-14A: Tomcat FR.1 (No trainer version so we start from 1, Fighter and Reconnaissance from the TARPS pod)
- FAA F-14A: Tomcat FR.2 (Presumably RN fit would be slightly different in some way, so they get a different number)
- F-14B: Tomcat FR.3/4
- F-14D: Tomcat FR.5/6
- Proposed strike F-14D #3112: Tomcat FGR.5/FA.6
- Proposed AST-21 #3117: Tomcat FGR.7/FA.8

These number are, of course, for the ridiculous universe in which the UK buys all four models of Tomcat for both services, which I don't think was ever on the cards, but it makes it easier to keep track of which aircraft in your scenario are the carrier capable ones (even numbers), which calling everything Tomcat FR.1 would not.

The split between FGR for the RAF and FA for the FAA is very strange, but the precise reasoning for the Sea Harrier FRS.2 being redesignated the FA.2 instead of the FGR.2 or FG.2 when the nuclear strike role was removed has never been clear to me, so I will assume whatever temporary madness afflicted the FAA in the early 90s would apply no matter what aircraft they had.

### Sources

Internal renaming
https://en.m.wikipedia.org/wiki/British_military_aircraft_designation_systems

**Comment by KushanGaming** [comment]
Updated the names for DB501. Not adding ground attack loadouts at this time.
