### ISSUE TITLE
Aircraft #6645 - Su-35S Flanker M (Russia [1992-] - 2022) UPMK (UMPK) loadout is missing?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3499]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #6645 - Su-35S Flanker M (Russia [1992-] - 2022) UPMK

### Summary of Changes

Aircraft doesn't have any "UPMK" Load outs despite the title?

As a linked point the most common acronym given in Russian sources is UMPK not UPMK ref Weapon #4277 - UPMK FAB-500M-62 Glide Bomb.
Cross ref request #3291.
Loose translation is Unified module for planing and correction   = унифицированный модуль для полета и коррекции. 

Thanks
K

### Sources

https://www.popularmechanics.com/military/weapons/a43571893/how-dumb-are-russias-winged-smart-bombs/

**Comment by PygmalionOfCyprus** [comment]
[I was hoping no one would notice this one.](https://www.youtube.com/watch?v=SYCP71qcYZw)

I actually spotted this goof and fixed it like two days after 500 release. So, handled 501. The loadouts should still be in DB500 as 32902 and 32889 if you desperately need to test something. Sorry!
