### ISSUE TITLE
Add GBU-31 [BLU-109) Penetrator Variants to Israeli GBU-31 Capable Aircraft

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#35]
### DB Selector

DB3K

### User(s)

F-15I, F-16C/D, F-16I, F-15CD, F-35

### Weapons Carried

Same GBU-31 loadouts with HE bomb types swapped for Penetrator

### Requires Buddy Illumination

- [ ] Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

- [ ] Yes

### Comments

Pictures below show pointy"er" GBU-31's which are the BLU-109 types. 

### Sources

https://twitter.com/alexgarcialonso/status/1394303547907493892
https://www.defensenews.com/global/mideast-africa/2018/03/20/just-declassified-how-an-israeli-operation-derailed-syrias-nuclear-weapons-drive/
https://ifamericansknew.org/images/Israeli-F-16-with-BLU-109.jpg
https://i.imgur.com/mIRY860.png

**Comment by bostonmyk** [comment]
Found another picture. Check out the nose of that GBU-31. Its a penetrator variant.

https://twitter.com/GuyPlopsky/status/1394585120544153602/photo/1

**Comment by bostonmyk** [comment]
Another one. That a GBU-31 109 variant

https://twitter.com/Defensa_Israel/status/1536725310384783360/photo/1

**Comment by KushanGaming** [comment]
Done for DB502.
