### ISSUE TITLE
Add Ukrainian 155mm Caesar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3500]
### DB Selector

DB3K

### DBID to Copy

Facility 2401

### Hypothetical

No

### Name

Arty Bty (155mm/52 Caesar Self-Propelled Howitzer)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

x49

### Sources

French Models x30
https://twitter.com/Osinttechnical/status/1671720870027444224?cxt=HHwWgIC-2cXRkrMuAAAA
https://www.thedefensepost.com/2023/01/31/france-caesar-howitzers-ukraine/
https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
Danish x19
https://twitter.com/Misfit4Ukr68491/status/1671232274107604993
https://www.newsweek.com/howitzers-arrive-ukraine-russia-attack-1797342
https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://twitter.com/UAWeapons/status/1672339498775052289

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
