### ISSUE TITLE
Add Leopard 2A4 to Ukraine

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3501]
### DB Selector

DB3K

### DBID to Copy

Facility 2333

### Hypothetical

No

### Name

Armored Plt (Leopard 2A4 x 3)

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

50+

### Sources

https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://twitter.com/clashreport/status/1670536235251560449
https://twitter.com/Osinttechnical/status/1666791354058301441

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
