### ISSUE TITLE
Add Leopard 2A6 to Ukraine

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3502]
### DB Selector

DB3K

### DBID to Copy

Facility 2341

### Hypothetical

No

### Name

Armored Plt (Leopard 2A6 x 3)

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

x21

### Sources

https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://twitter.com/clashreport/status/1668927428528422912
https://twitter.com/Archer83Able/status/1668624459488690192

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
