### ISSUE TITLE
Add Ukrainian Marine AMX-10RC

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3503]
### DB Selector

DB3K

### DBID to Copy

Facility 2198

### Hypothetical

Yes

### Name

Armored Plt (AMX-10RC x3)

### Country

Ukraine

### Service

Marines

### In Commission

2023

### Number in Service

x40

### Sources

https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://twitter.com/clashreport/status/1648381084164390919
https://twitter.com/clashreport/status/1668979449306439685

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
