### ISSUE TITLE
Add Ukrainian Bradley M2A2-ODS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3504]
### DB Selector

DB3K

### DBID to Copy

Facility 2784

### Hypothetical

No

### Name

Mech Inf Plt (M2A2 Bradley AFV x 3)

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

x124

### Sources

https://www.thedrive.com/the-war-zone/ukraine-situation-report-u-s-sending-more-bradleys
https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://twitter.com/thewarzonewire/status/1667226420693835776

**Comment by bostonmyk** [comment]
Reduce to 3 mounts. No evidence using 4 IFV platoon

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
