### ISSUE TITLE
Add Ukrainian M-113 Mech Platoons

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3505]
### DB Selector

DB3K

### DBID to Copy

Facility 2009

### Hypothetical

No

### Name

Mech Inf Plt (M-113A3 AFV x 3)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

400+

### Sources

https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://twitter.com/UAWeapons/status/1581002280522121216
https://twitter.com/UAWeapons/status/1567167584327327745

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
