### ISSUE TITLE
Update Sea Gull USV MCM Configuration and create a second ASW configuration with VDS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3507]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3142

### Summary of Changes

Remove VDS.  The Side scan is on a towfish and can't tow the VDS at the same time.  

ASW version of Seagull with VDS uses HELRAS.

TRAPS-USV is a compact VDS. Stats are below. IOC 2020

### Sources

https://seapowermagazine.org/elbit-integrates-active-towed-array-sonar-onboard-seagull-usv/
https://geospectrum.ca/wp-content/uploads/2022/01/GEOSPECTRUM-TECHNOLOGIES-INC.-BROCHURE-TRAPS-USV-2020-06-v1-email-copy.pdf
https://www.edrmagazine.eu/geospectrum-technologies-launches-game-changing-lf-active-vds-deployable-by-usvs

**Comment by tbrandon517** [comment]
Related request #2566

**Comment by Jkryos** [comment]
Added DB3K 509.
