### ISSUE TITLE
Add Ukrainian S/AMPT SAM

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3508]
### DB Selector

DB3K

### DBID to Copy

Facility 3366

### Hypothetical

Yes

### Name

SAM Bty (Mamba [SAMP/T]

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

x1 +1

### Sources

https://www.yahoo.com/lifestyle/macron-says-samp-t-air-222917109.html
https://www.thedefensepost.com/2023/05/18/italy-samp-t-air-ukraine/

Radar stuff
https://mil.in.ua/en/news/ukraine-will-receive-two-gm200-radars-for-samp-t-sams/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
