### ISSUE TITLE
Add 91N6E for Turkey

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3509]
### DB Selector

DB3K

### DBID to Copy

2443

### Hypothetical

No

### Name

91N6E Big Bird D

### Country

Turkey

### Service

Air Force

### In Commission

2019-present

### Number in Service

1-4?

### Other Changes

Seen photographed during testing. Shipped in 2019, in limited service. Maybe 1 per battery
![f-16-s-400-2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/88b6897d-46c2-4250-9094-82cf3b1b907b)

### Sources

https://www.thedrive.com/the-war-zone/31187/turkey-tests-f-16s-and-f-4s-against-s-400-radars-in-defiance-of-u-s-sanctions-threats

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
