### ISSUE TITLE
HU-25B Falcon Sensor Update

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3511]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2054

### Summary of Changes

The notes for the aircraft say it has the Aireye system fitted, but it has no associated sensors and so is pretty useless as a patrol aircraft. The Aireye consists of:
- 'New Generation' AN/APS-94 SLAR pod (ID 320?) - Parameters provided in link
- UV/IRLS used for spotting oil spills (see #3367) - Parameters provided in link
- 'Active Gated Television' sensor with 2nd Gen LLTV and weird active search - Parameters provided in link, 220 degree arc
- KS-87B Recce Camera

The active mode of the AGT seems to be a very strange system, enhancing the LLTV sensor not with an IR searchlight but with a near-IR laser that pulses rapidly while the camera switches on and off rapidly to selectively accept only the reflected light from the laser target. While the document calls this a laser illuminator, it is not what you or I would call a laser illuminator, I'm almost sure it can't guide bombs.

### Sources

http://meridian.allenpress.com/iosc/article-pdf/1979/1/301/1738286/2169-3358-1979-1-301.pdf - source
https://www.defensemedianetwork.com/stories/iconic-coast-guard-aircraft/ - proof the B is the aircraft in question

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
