### ISSUE TITLE
China, Synthetic-aperture radar (SAR) for Y-9DZ [GX-12]

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3513]
### DB Selector

DB3K

### Baseline

sensor 6639

### Hypothetical

No

### Name

Y-9DZ SAR

### Sensor Generation

Early 2020s

### Range (nm)

0.1-200nm

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Range Information, Speed Information, Heading Information

### Sensor Codes

Track While Scan (TWS), Periscope/Surface Search - Advanced Processing [2000+], Moving Target Indicator (MTI), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA), Can Classify Ground Targets (SAR)

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Sources

https://en.wikipedia.org/wiki/Shaanxi_Y-9
https://eurasiantimes.com/first-time-chinas-cutting-edge-y-9dz-electronic-warfare/
https://thediplomat.com/2023/06/japan-photographs-chinas-new-y-9dz-electric-warfare-aircraft-for-first-time/
SAR on its bottom:
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/ea71f76f-1875-4aa7-9d97-8996f98a7d13)

**Comment by Jkryos** [comment]
Added DB3K 506.
