### ISSUE TITLE
Update: China, J-20B, electronic capability upgrade

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3515]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 2463

### Summary of Changes

add 1x Generic ESM [Advanced] (2020s, DF, Precise Emitter ID)

There is a refinement on the rear section behind the cockpit which provides enough space for J-20B to install some EW devices. 

### Sources

https://en.wikipedia.org/wiki/Chengdu_J-20
https://www.thedrive.com/the-war-zone/this-could-be-our-first-glimpse-of-chinas-enhanced-j-20-stealth-fighter
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/3d14a928-2e4a-4a5c-8f21-124778bf4d20)

**Comment by PygmalionOfCyprus** [comment]
"Space to install" does not necessarily mean any are being installed. Adding ESM to a fighter is more than just tossing it behind the pilot. This looks like a change drawn mostly from aerodynamic/stealth(?) concerns; it's _possible_, of course, that they are going to use the extra space for something fun, but without more evidence I'm not going to add it based on the extension alone.
