### ISSUE TITLE
Correction: North Korea, KN-25 SRBM/MLRS, speed problem

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3517]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3718 3719

### Summary of Changes

change speed band to generic SRBM 4000-4500kt (current max speed for booster is 10000kt and RV is 11000kt-12000kt)

### Sources

No source needed.

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
