### ISSUE TITLE
SMART-L EWC Missing AESA Property

### ISSUE THREAD

**Issue by gorillabond** [PygmalionOfCyprus/cmo-db-requests#3518]
### DB Selector

DB3K

### Affected DBID(s)

#5195 - SMART-L EWC [BMD Mod]

### Summary of Changes

The SMART-L EWC needs to have the property AESA radar.

### Sources

https://www.thalesgroup.com/en/markets/defence-and-security/naval-forces/above-water-warfare/smart-l-multi-mission

**Comment by PygmalionOfCyprus** [comment]
Welcome to the Github! In the future please preface your DBIDs with the annex, e.g. `Sensor 5195', so that the auto-triage can pick it up I don't have to manually tag it.

Handled 502.
