### ISSUE TITLE
Update max target speed for and SM-6 Blk IA+ and SM-6 Dual I

### ISSUE THREAD

**Issue by gorillabond** [PygmalionOfCyprus/cmo-db-requests#3519]
### DB Selector

DB3K

### Affected DBID(s)

Guided Weapons #3357 #3541 #3714 #3772

### Summary of Changes

I propose an increase in max target speed for SM-6s Blk IA and above. Currently, they are unable to intercept HGVs, however there are sources that state they are able to intercept these targets.

I propose an increase in max target speed for the SM-6 Blk IA and Dual I to 8250 kts and an increase to 10000 kts for the IB, which, according to the Missile Defense Agency (MDA), will have an increased capacity for HGV interception.

### Sources

https://news.usni.org/2021/11/19/guam-needs-sm-6-missile-for-hypersonic-defense-navy-admiral-says

https://www.thedrive.com/the-war-zone/44142/sm-6-missiles-are-americas-only-defense-against-hypersonic-weapons-missile-defense-chief-says

https://missiledefenseadvocacy.org/defense-systems/standard-missile-6-sm-6/

**Comment by tbrandon517** [comment]
See requests #3347 and #3441 completed for db v501.

**Comment by gorillabond** [comment]
7000kts for SM-6 Blk IB is not high enough to intercept HGVs before impact.

**Comment by HunterDNiu** [comment]
> 7000kts for SM-6 Blk IB is not high enough to intercept HGVs before impact.

Blk IB being hypersonic midcourse were meant for glide phase intercept.

**Comment by ddranidis** [comment]
HGVs do not have a uniform speed throughout their glide phase. They usually start at quite high speeds (M 6-10+) and towards the end of their nominal range the speed may drop to even below Mach 1.

It is my understanding that the comments that have been made on various sources that several in-service US/NATO systems (and especially SM-6) are able to intercept HGVs, refer to a marginal capability towards the end of their flight. Counter-HGV development programs like GPI etc. specificaly aim to expand the engagement envelope to cover a greater portion of the HGV flight (ie. intercept them at greater standoff from the protected asset, where their velocity & altitude are much greater).

**Comment by PygmalionOfCyprus** [comment]
Will do some independent research / consult with SMEs on this. For now marking as "not planned" just because I'm not guaranteeing what is going to be changed to what, but there will be a larger review of the SM-6 speeds.
