### ISSUE TITLE
HeliTOW for Belgian A.109s

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3523]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1512 and 2992

### Summary of Changes

Replace generic FLIR with Sensor Group 6948, the HeliTOW sight. 

### Sources

https://inf.news/en/military/cd52cdc32d4c3f00b319cbbec4adf571.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502. HeliTOW not present on the scout models, they had a Saab camera.
