### ISSUE TITLE
HeliTOW for Hkp 9A

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3524]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4525

### Summary of Changes

Replace generic FLIR with Sensor Group 6948, the HeliTOW sight. 

### Sources

https://inf.news/en/military/cd52cdc32d4c3f00b319cbbec4adf571.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
