### ISSUE TITLE
Add Algerian Wing Loong II UCAV

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3527]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4788

### Hypothetical

Yes

### Name

Wing Loong [Pterodactyl] II UCAV

### Country

Algeria

### Service

Air Force

### In Commission

2023

### Sources

https://twitter.com/kmldial70/status/1673050748261924864?cxt=HHwWgIDU1dKy77cuAAAA
https://twitter.com/fares4302/status/1673262848196349952?cxt=HHwWgMDQqb7sz7guAAAA
https://twitter.com/fab_hinz/status/1669679408909565952?cxt=HHwWgIC2je-k8qsuAAAA

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
