### ISSUE TITLE
Finland F-35 JSOW & JASSM loadout

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3531]
### DB Selector

DB3K

### User(s)

USAF F-35's use this 

### Weapons Carried

2x AGM-154C JSOW
2x AIM_120D AMRAAM
Internal
----------------------
2x AGM-158A JASSM
2x AIM-120D AMRAAM
2x AIM-9X
External

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

740 nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

These weapons are currently on the F/A-18 Hornets but will surely be fitted to the new F-35's

### Sources

https://en.wikipedia.org/wiki/Finnish_Air_Force
https://www.janes.com/defence-news/news-detail/us-approves-air-launched-weapons-package-for-finland
https://www.flightglobal.com/lockheed-moves-forward-with-finlands-jassm-integration/112142.article

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
