### ISSUE TITLE
Copy aircraft #2705 - P-8A Poseidon (United States - 2014) for Canada (Royal Canadian Air Force) - up to 16 from circa 2024

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3533]
### DB Selector

DB3K

### DBID to Copy

Aircraft #2705

### Hypothetical

No

### Name

CP-15X Poseidon RCAF 2024

### Country

Canada

### Service

Air Force for Navy

### In Commission

2024

### Number in Service

16 = Possibly up to!

### Sensors

AN/ALQ-213 Electronic CM
AN/ALQ-240 Electronic Support Measures; 
NexGen Missile Warning Sensors?

### Mounts

AN/AAQ-24(V)N LAIRCM
AN/ALE-47 Countermeasures Dispenser Systems

### Loadout Options

Work in progress. Presumably just Mk54 and sonobuoys at minimum IOC. 

### Other Changes

Work in progress. Basic copy of 2014 version would appear safe 

### Sources

https://www.dsca.mil/press-media/major-arms-sales/canada-p-8a-aircraft

**Comment by PygmalionOfCyprus** [comment]
Handled 502. Do you have a source on the CP-15X designation?

**Comment by KLABDB3K** [comment]
No source but going through designators used already the next iteration is going to be in the CP-15X region. It will have to be a placeholder.
