### ISSUE TITLE
Weapons  #1058 - AT-16 Scallion [9M127 Vikhr] #3987 - AT-16 Scallion [9A1472 Vikhr-1] Warhead is not realistic.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3534]
### DB Selector

DB3K

### Affected DBID(s)

Weapons  #1058 - AT-16 Scallion [9M127 Vikhr] #3987 - AT-16 Scallion [9A1472 Vikhr-1]

### Summary of Changes

Current warhead for both these weapons is Warhead #201 - AT-6 HEAT (1 DP) - this is way to old and ineffective. 
Suggest create new warhead based on starting point of warhead #1347 - AT-15 Tandem HEAT (8 DP).
New warhead  - AT-16 Tandem HEAT (6 DP).

The Vikhr Missile "has a tandem warhead with a weight of 12kg , - 6kg of which is explosive capable of penetrating over 1000mm of reactive armour dealing with dynamic protection at a 90* angle of arrival". 
Gator on the Rise - pp146. Alexander Mladenov ISBN-978-1-911096-45-0  
Evidence is the number of relatively well protected platforms being destroyed over the frontal arc in Ukraine by Vikhr's fired by Ka-52.  

### Sources

Multiple.
https://rostechnologiesblog.wordpress.com/2013/08/09/russia-to-test-vikhr-1-guided-missile-later-this-year/amp/
https://www.airinternational.com/article/mean-havoc-rising-part-2
https://www.airinternational.com/article/mean-havoc-rising

The Vikhr Missile "has a tandem warhead with a weight of 12kg , 6kg of which is explosive capable of penetrating over 1000mm of reactive armour dealing with dynamic protection at a 90* angle of arrival". 
Gator on the Rise - pp146. Alexander Mladenov ISBN-978-1-911096-45-0

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
