### ISSUE TITLE
Weapon #1241 - AT-9 Spiral-2 [9M120 Ataka-V] Warhead is inaccurate.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3535]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #1241 - AT-9 Spiral-2 [9M120 Ataka-V] 

### Summary of Changes

Missile currently uses AT-6 warhead #201 - AT-6 HEAT (1 DP) which is 1 DP HEAT. 
Not sure how the armour penetration model works but the baseline 9M114 Shturm can penetrate non ERA protected RHA to circa 600mm? 

The 9M120 Ataka has a 7.4 kg Tandem HEAT warhead capable of penetrating about 800mm of armour after ERA . 

Create new warhead # AT-9 Tandem HEAT (5 DP). or use the AT-8 Songster warhead #1374 - AT-8 HEAT (4.5 DP)??

### Sources

https://en.wikipedia.org/wiki/9M120_Ataka
There area multiple other sources and performance estimates vary but the AT-9 has superior armour penetration to the baseline AT-6.

**Comment by KLABDB3K** [comment]
Noticed a lot of the common ATGM are using 1DP generic warheads, are these place holders? The entire TOW series dont seem to model the specific variant warheads? Tandem, precursor, EFP, top attack etc?

**Comment by PygmalionOfCyprus** [comment]
Handled 502.

>Noticed a lot of the common ATGM are using 1DP generic warheads, are these place holders? The entire TOW series dont seem to model the specific variant warheads? Tandem, precursor, EFP, top attack etc?

Yeah, these were probably added a gazillion years ago before the armor and ground unit overhauls. Should still be fine for purpose, though. If you hit a "mount" (i.e., a tank) with an explosive missile that penetrates it won't whine about the DP.
