### ISSUE TITLE
Update Ready Time Under Surge Options for J-15D Roaring Shark

### ISSUE THREAD

**Issue by yilin-zhou-USTC** [PygmalionOfCyprus/cmo-db-requests#3538]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft#4817, Loadout#25212, Loadout#25444

### Summary of Changes

The ready time of surge options of J-15D Roaring Shark is too long. It takes 10 hr for one sortie. 
I suggest 3 hr when J-15D only takes OECM device and 6 hr when it takes YJ-91 missiles.

### Sources

For comparison, it only takes 3 hrs for EA-18G to takeoff when it does not carry air-to-ground or anti-radar missiles.
If it carries air-to-ground or anti-radar missiles like AGM-88, it still only takes 6 hr to takeoff. 
Therefore, 10 hr may be too long for J-15D.

**Comment by PygmalionOfCyprus** [comment]
Fair. Handled 502.
