### ISSUE TITLE
Antenna height of P-80 radar 

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#3539]
### DB Selector

Both

### Affected DBID(s)

#1876, #1613, #1155, #2244

### Summary of Changes

In the Database the antenna height of these four radar is 30 meters.
I could not find exact data but looking at the pictures it must be around 3 meters. This will reduce the detection ranges of low flying objects.

![i-MCtvR7N-X2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/bb1b24e0-6a39-4663-9e3a-1f6d0eb08221)

### Sources

[https://www.radartutorial.eu/19.kartei/11.ancient3/karte092.en.html](url)
[https://www.recomonkey.com/Land-Platforms/Air-defence/Radars/P-80-1RL118](url)

**Comment by PygmalionOfCyprus** [comment]
Please preface at least the first ID with the annex, e.g. `Facility 1876, 1613, etc.` so I don't have to manually tag them.

**Comment by Huib18** [comment]
Oh sure, I was not aware, will adjust next time, thanks for the patience up till now.

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
