### ISSUE TITLE
OC-135B Open Skies

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#354]
### DB Selector

DB3K

### DBID to Copy

aircraft/159/DB3K

### Hypothetical

No

### Name

OC-135B Open Skies - United States (Air Force) 1993-2021

### Country

United States

### Service

Air Force

### In Commission

1993-2021

### Sensors

3x Boeing KS-87B cameras
1x Recon/Optical KA-91B panoramic camera
Loral AN/UPD-8 Synthetic aperture radar
Improved navigation and communications equipment

### Mounts

None

### Loadout Options

Ferry
Maintenance
Reserve
Open Skies Observation Flight [Internal EO/IR]

### Sources

https://en.wikipedia.org/wiki/Boeing_OC-135B_Open_Skies
https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104496/oc-135b-open-skies/
https://www.acc.af.mil/About-Us/Fact-Sheets/Display/Article/199181/oc-135b-open-skies/
https://www.military.com/equipment/oc-135b-open-skies
https://www.globalsecurity.org/intell/systems/oc-135.htm
https://theaviationgeekclub.com/usaf-retired-final-oc-135b-open-skies-observation-aircraft/
https://www.dm.af.mil/Media/News/Article/2657190/oc-135b-retirement/
https://www.offutt.af.mil/News/Article/2659450/oc-135b-retirement/
https://www.overtdefense.com/2021/06/04/us-air-force-retires-its-final-oc-135b-open-skies-aircraft/
https://www.acc.af.mil/News/Article-Display/Article/2650565/end-of-an-era-as-final-oc-135-aircraft-officially-retired/
https://www.airforcetimes.com/news/your-air-force/2021/05/16/offutt-airmen-say-goodbye-to-troubled-but-beloved-jets/?utm_source=facebook.com&utm_medium=social&utm_campaign=Socialflow+AIR&fbclid=IwAR1yM_K5-ALH55M59eo67pvXoQAE_Md1a_eWXnQQU705N9MhMAzeRuMEMpQ
https://www.thedrive.com/the-war-zone/20844/u-s-lawmakers-want-to-axe-funding-for-new-surveillance-planes-to-monitor-russia
https://www.thedrive.com/the-war-zone/25343/usaf-flies-sudden-open-skies-recon-flight-over-ukraine-as-russia-and-ukraine-hold-missile-drills
https://www.thedrive.com/the-war-zone/30212/house-foreign-affairs-committee-chairman-raises-alarm-trump-may-axe-the-open-skies-treaty
https://www.thedrive.com/the-war-zone/33212/air-force-is-down-to-one-tired-old-jet-to-fly-open-skies-surveillance-flights

![image](https://user-images.githubusercontent.com/99599482/155004185-08f039e4-482b-4347-b3d6-cab0b29732ba.png)

**Comment by Jkryos** [comment]
Added DB3K 494.
