### ISSUE TITLE
1L119 Nebo radar antenna height

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#3540]
### DB Selector

DB3K

### Affected DBID(s)

facilty 3592, facilty 3593, facilty 1849

### Summary of Changes

The antenna height of the 1L119 radar in the DB is set at 60 meters.
Looking at the person just behind the radar my measurements is around 8 meters high. Because of the influence of detecting low flying objects I request this to be adjusted. 

![7574046010_58e4769639_z](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/a1610651-eeb6-4d6e-ae2c-b1b7d2e46954)

### Sources

[https://imp-navigator.livejournal.com/168763.html](url)
[https://imp-navigator.livejournal.com/168763.html](url)
[https://www.youtube.com/watch?v=Vpm2sjPHFuY&t=30s](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
