### ISSUE TITLE
Add 2023 Retirement date to Norwegian P-3C

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3541]
### DB Selector

DB3K

### Affected DBID(s)

aircraft #362

### Summary of Changes

Add out of service date of 2023

### Sources

https://twitter.com/Forsvaret_no/status/1674805638352740354
https://www.thedefensepost.com/2023/05/31/norway-retire-orion-fleet/
https://twitter.com/thenewarea51/status/1675076422681886720

**Comment by PygmalionOfCyprus** [comment]
Handled 502.

**Comment by KLABDB3K** [comment]
Add 3 to Argentina?
