### ISSUE TITLE
Update Poseidon Loadouts #.28499 & #.28501

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#3542]
### DB Selector

DB3K

### Affected DBID(s)

All P-8A Poseidon

### Summary of Changes

Update loadout #.28499 & #.28501 to Day/Night All-Weather to match all other loadouts. Nothing in the loadouts is different to other loadouts and they all have Day/Night All-Weather capability.

### Sources

In game Database

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
