### ISSUE TITLE
Update ScanEagle UAV Loadout

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#3543]
### DB Selector

DB3K

### Affected DBID(s)

All ScanEagle UAV's

### Summary of Changes

- Update Loadout #.17673 to Day/Night All Weather.

"ScanEagle provides persistent daytime and nighttime ISR in some of the world’s most extreme environments." [1]

The link for this will get you all the datasheets for drones they do as well as the various sensors that can be fitted. 

### Sources

[1] https://www.insitu.com/products/scaneagle#:~:text=Persistent%20ISR,the%20world's%20most%20extreme%20environments.

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
