### ISSUE TITLE
Add IFF/PESA to Protivnik-GE Radar Properties

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3544]
### DB Selector

DB3K

### Affected DBID(s)

3819

### Summary of Changes

Protivnik-GE has an IFF array, uses PESA antenna with10-20 pencil beams

-Add to radar properties: IFF, PESA

Thank you :)

![protivnik](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/195507cc-488d-44b1-b05b-ab2d415922bb)
![protivnik IFF](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/fa86f0e8-eb62-4f19-8e67-94d7d137cb23)
![protivnik-PESA](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/bfd8816f-df17-47c5-9c48-6e9f2c1c2868)

### Sources

https://www.ausairpower.net/APA-Rus-Low-Band-Radars.html#mozTocId397234

**Comment by PygmalionOfCyprus** [comment]
Please preface the DBID with the annex, e.g. `Sensor 3819`, so I don't have to manually tag it.

**Comment by PygmalionOfCyprus** [comment]
Handled 502.

**Comment by GIGANTO-pithecus** [comment]
> Please preface the DBID with the annex, e.g. `Sensor 3819`, so I don't have to manually tag it.

understood, I appreciate it!
