### ISSUE TITLE
Italian Piaggio P.1HH Hammerhead UCAV

### ISSUE THREAD

**Issue by Tobias02** [PygmalionOfCyprus/cmo-db-requests#3545]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5424

### Summary of Changes

Hi, the autonomy of the unit in question in the V500 database is about six hours, while in the technical specifications in the official Piaggio Aerospace website it appears to be 16 hours, with 500 lbs payload, or 10.5 hours (500 lbs payload) @ 1,500 km from takeoff & landing base.
Thank you!

### Sources

https://p1hh.piaggioaerospace.it/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
