### ISSUE TITLE
Add 2023 out of service date for Taiwanese I-Hawks

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3546]
### DB Selector

DB3K

### Affected DBID(s)

Facility 802

### Summary of Changes

Add 2023 out of service date 

### Sources

https://alert5.com/2023/06/30/taiwan-has-retired-its-mim-23-hawk-gbad-system-after-63-years-of-service/
https://www.overtdefense.com/2023/06/30/taiwan-retires-last-hawk-surface-to-air-missiles/
https://www.defense.gov/News/Transcripts/Transcript/Article/3444912/pentagon-press-secretary-air-force-brig-gen-pat-ryder-holds-a-press-briefing/
https://missiledefenseadvocacy.org/missile-defense-news/military-deploys-skybow-patriot-missiles-to-northern-taiwan/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
