### ISSUE TITLE
Armour for ItPsv 90 Marksman SPAAG

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3548]
### DB Selector

DB3K

### Affected DBID(s)

Facility 1580

### Summary of Changes

Currently, each mount has Armor_Handgun. The Marksman turret is supposedly armoured against 14.5mm HMG fire, and the T-55AM hull obviously has up to 200mm of solid steel depending on where you hit it. Mostly I think this will manifest in Command as better fragmentation protection, iron bombs shouldn't going to worry the ItPsv unless they hit pretty near it.

There's also a newer Leopard based one but honestly I don't think it's usefully different from this one, except for exact speed and hull armour.

### Sources

https://i16.photobucket.com/albums/b24/hybenamon/LAND/ANTI-AIR/MARKSMAN/brochure3.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
