### ISSUE TITLE
SAS Tafelberg initial fit

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3549]
### DB Selector

CWDB

### Baseline

Ship 144

### Hypothetical

No

### Name

AOR - A 243 Tafelberg

### Country

South Africa

### Service

Navy

### In Commission

1967-1980

### Number in Service

1x

### Length (m)

170.5

### Beam (m)

21.9

### Draft (m)

8.3

### Standard Displacement (t)

18980

### Empty Displacement (t)

6484? See fuel section.

### Complement

127

### Max Sea State

6?

### Primary Propulsion Type

Diesel

### Propulsion

Unknown Turbodiesel

### Fuel Capacity (kg)

Unknown. Tafelberg had a displacement of 18,980 tons and started life as the tanker Annam, which had a rated capacity of 12,496gt. Therefore, in the ballpark of 12,500 tons of Diesel fuel? Plus a calculated empty weight?

### Flank Speed (kt)

16

### Range (nm) at Speed (kt)

?

### Sensors

1x Generic Nav Radar

### Mounts

4x Oerlikon - half each side?
6x .50 - half each side?
Twin Bofors L/60 - Aft?

### Aircraft & Docking Facilities

-

### Comms/Datalinks

?

### Ship Codes

Built to Mercantile Standards

Refuel Starboard x2
Refuel Port x2
Refuel Aft x1

Replen Starboard x1
Replen Port x1

### Comments

First of three fits, eventually converted into a weird AOR-LHA.

### Sources

https://en.wikipedia.org/wiki/SAS_Tafelberg
http://www.warinangola.com/Default.aspx?tabid=1239&Parameter=1744
http://www.navy.mil.za/Pages/History.aspx
https://www.shipsnostalgia.com/media/annam.378692/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
