### ISSUE TITLE
Add AESA function to RLM-M

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3552]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 4556, Facility 1846

### Summary of Changes

Add to properties: AESA function, Frequency Agile, and Track While Scan (TWS)

![nebo-m](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/11e34113-583d-4dac-8adb-b3c5abc15951)

### Sources

http://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/nebo-svu/
https://www.ausairpower.net/APA-Nebo-M-Annex.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
