### ISSUE TITLE
Add AESA function to RLM-S, E/F Band

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3553]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 4557, Facility 1848

### Summary of Changes

Add to properties: AESA function, Frequency Agile, Track While Scan (TWS)
Change operating bands to: E/F
Increase Max Range to 215nm (similar to Gamma-S1T)

RLM-S is an AESA upgrade to the Gamma-S1T (which has a 400km max range/and 500km in special mode). Original Gamma-S1 from 1990's had max range of 300km and 400km in special mode. So it follows the RLM-S should at minimum have 400km max range (possibly 500km but 400km for now is a good guess). Also, Gamma-S1T is an S-band (encompasses entire E/F bands). Looking at sheer size of antenna, RLM-S antenna is larger than 96L6 and similar in size to the 96L6-TSP which has 500km range.

![gamma-c1 range](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/884afddc-2588-4c57-a9f6-381741d76cc5)
![rlm0s](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/25e1cf68-a7ac-4c52-a843-dde59acffe4e)
sheer size of antenna (greater/similar to 96l6 cheese board that has a range of 220nmi) considering rlm-s is AESA it would have similar if not longer range, especially to accommodate accurate target tracking for the 40N6E missile that has a 400km range. Being AESA should have continuous track, TWS and frequency agility as well.

### Sources

https://www.youtube.com/watch?v=eM6QVQ8JMrM

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
