### ISSUE TITLE
9S32M Grill Pan FCR Altitude Correction

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3554]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 4819

### Summary of Changes

Currently in game max altitude is set to ~30km.
**Changes:** 
1. Increase max radar altitude to 250km in height
2. Increase max target speed detectable to 4500 m/s (mach 13)

![antey-4000 grill pan](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/43c80ff9-9c37-4877-b83a-aa78f9fe2731)
IMPORTANT: max range in this picture of 400km and max tgt speed 4800m/s is for newest Antey-4000 export version featuring 9M82MD missile with max range of 380km. Currently only Russia has few batteries, as Venezuela and Egypt only have Antey-2500. However max FCR search altitude is guessed to be the same for Antey-2500 and Antey-4000.

https://www.youtube.com/watch?v=zzumXb07NJY
export video showing all antey-4000 radars/missile specs

### Sources

https://www.youtube.com/watch?v=zzumXb07NJY

thank you!

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
