### ISSUE TITLE
625 Ship name, IOC, Quantity details

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3557]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3431

### Summary of Changes

Add Kapak name
Add 2023 IOC
Quantity x2
Everything else looks good.

### Sources

https://www.bairdmaritime.com/work-boat-world/maritime-security-world/naval/ships-naval/vessel-review-panah-indonesian-navy-acquires-two-locally-built-fast-attack-craft/
https://www.navalnews.com/naval-news/2023/07/sinkex-indonesian-navy-fires-exocet-mm40-block-3/
https://www.shephardmedia.com/news/naval-warfare/indonesia-commissions-next-kcr-60m-missile-boats-and-constructs-new-opvs/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
