### ISSUE TITLE
Umkhonto-R missile

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3562]
### DB Selector

DB3K

### Baseline

Weapon 2770, Umkhonto-IR 2

### Hypothetical

Yes

### Name

Umkhonto-R

### Length (m)

as Umkhonto

### Width/Span (m)

as Umkhonto

### Diameter (m)

as Umkhonto

### Weight (kg)

as Umkhonto

### Range (nm)

11

### Target Altitude / Depth (ft)

?

### Target Speed (kts)

?

### Launch Altitude / Depth (ft)

ground based

### Warhead

as Umkhonto

### Targets

Aircraft, Helicopter, Missile

### Sensors

1x active radar seeker, early 2010s

### Weapon Codes

Anti-Air All-Aspect

### Comments

Slightly extended range version of Umkhonto-IR, with an active radar seeker. To be used on ground based Umkhonto.

Wiki has range at 60km, which I just don't believe if it still fits in a standard Umkhonto launch box. It also mentions tests in which two targets were destroyed at 15km (max range of IR Mk.2) and one destroyed at 20km, which is what the Army Technology source says. Ergo, 20km range.

### Sources

https://www.army-technology.com/projects/umkhonto-ground-based-launcher-system/
https://en.wikipedia.org/wiki/Umkhonto_(missile)

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
