### ISSUE TITLE
Umkhonto GBLS

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3563]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

Umkhonto GBLS (Project Protector, GBADS)

### Facility Type

SAM

### Country

South Africa

### Service

Army

### In Commission

not yet

### Number in Service

120x mounts planned

### Sensors

1x Giraffe AMB, Sensor 2991
3?x One way command datalink, 4 missiles at a time. Possibly what's on the mast in the below image.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/115af2fb-3460-47d1-a365-0ac334efe460)
(No idea what the test radar is, it's not an EL/M-2106, it's not any Giraffe and it's not a Thutlwa)

### Mounts

3?x 8-round Umkhonto VLS (can use 2770 Umkhonto-IR Mk.2 or #3562 Umkhonto-R)
Unclear how many launchers will be in a battery, I'm going to take a random stab at 3
1x control vehicle with the Giraffe. The Army Technology source says the radar will be on the launcher, I don't think the launcher has the space or power supply to do that, and it's a waste of time for this sort of application.

### Magazines

16x per mount? Does that sound fair?

### Comments

Supposed to be baselined in 2021, doesn't seem to have been. Test fired ten years ago, so it works, they just don't have the money to buy any.

This reminds me of Sky Sabre/CAMM, actually. Same small missile sharing a body with a naval SAM and an AAM, same Giraffe AMB radar, same odd looking mast mount.

### Sources

http://www.deneldynamics.co.za/products/missiles/air-defence-missiles/umkhonto-gbl
https://www.army-technology.com/projects/umkhonto-ground-based-launcher-system/
https://en.wikipedia.org/wiki/Umkhonto_(missile)
https://www.defenceweb.co.za/featured/armscor-reports-progress-with-gbads/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
