### ISSUE TITLE
Add Ukrainian RBS70 SAM

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3568]
### DB Selector

DB3K

### DBID to Copy

Facilityi #1196

### Hypothetical

No

### Name

SAM Plt (RBS 70 Bolide MANPADS x 3)

### Country

Ukraine

### Service

Army

### In Commission

2023

### Sources

https://twitter.com/Osinttechnical/status/1677764324415135744
https://mil.in.ua/en/news/military-shows-rbs-70-air-defense-system-in-service-with-armed-forces-of-ukraine/
https://twitter.com/UAWeapons/status/1633466407748009985

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
