### ISSUE TITLE
MK48 Mod 6/7 533mm Torpedo Range data

### ISSUE THREAD

**Issue by HudsonCW** [PygmalionOfCyprus/cmo-db-requests#357]
### DB Selector

DB3K

### Affected DBID(s)

905,1712 (MK48 Mod 6/7)

### Summary of Changes

Range increase to 38 km (20.5 nm) at 55 kt or 50 km (27 nm) at 40 kt [1]
or
Range increase to 15 nm (27.8km) at 65 kt, 22.6 nm (41.9km) at 40 kt, or 25nm at 28 kt[2]

### Sources

1: https://web.archive.org/web/20010401035621/http://www.janes.com/defence/naval_forces/news/juws/juws010202_1_n.shtml [2001]
2: America’s Navy, U.S Naval Ships, 1955 - 2020, edited by Larry Bond, Chris Carlson, Peter Grining, & Andy Doty [2021] Annex F Page 2

**Comment by HudsonCW** [comment]
Here is the data from source 2 so you may avoid purchasing the book if yo do not already own it
![image](https://user-images.githubusercontent.com/38671925/155058312-ef4363b0-f1ed-4c83-856f-b41222bb4294.png)

**Comment by Jkryos** [comment]
Correct DB3K 493.
