### ISSUE TITLE
AIM-120C-8 (D?) for Swedish Air Force JAS 39C/E Gripen

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3575]
### DB Selector

DB3K

### User(s)

Unknown

### Weapons Carried

JAS 39C
2x RB 101 Meteor  
2x RB 99B(?) AMRAAM (AIM-120c-8 or D)
2x RB 98 IRIS-T
1x 1275 liter drop tank

JAS 39E
4x RB 101 Meteor  
2x RB 99B(?) AMRAAM (AIM-120c-8 or D)
2x RB 98 IRIS-T
1x 1275 liter drop tank

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

15 minutes at 350 nm CAP

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

All Swedish JAS 39C/E will probably use this missile in tandem with the Meteor missile so all current loadouts with Meteor should be duplicated and use AIM-120C-8 (D?) instead.
The Meteor loadouts should be kept in place.
There should also in my opinion be a mixed loadout like the one above with Metor and AIM-120C-8 missiles for CAP. Both for JAS 39C and JAS 39E, There are pictures of this online. Se sources.

If I'm correct the AIM-120C-8 is the same missile as AIM_120D. Unclear why the US government use the C-8 designation in the brief.

In the database Meteor Swedish designation is RB 107. I think the Swedish designation is **RB 101** Meteor.

Unclear what the new AMRAAM designation will be RB99B maybe or RB 102.

### Sources

https://www.dsca.mil/press-media/major-arms-sales/sweden-aim-120c-8-advanced-medium-range-air-air-missile-amraam

https://www.facebook.com/story.php?story_fbid=1981174952123453&id=1419017168339237&m_entstream_source=permalink

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
