### ISSUE TITLE
SA-23 missiles max target speed correction

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3578]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2586, Weapon 2585

### Summary of Changes

for 9M83M (db 2586) increase max tgt speed to 3km/s (5831 kts)
for 9M82M (db 2585) increase max tgt speed to 4.5km/s (8747 kts), 
also for 9M82M increase max missile speed to 2600m/s (5054 kts)

![antey speeds ](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/1777d591-6d90-4c28-b427-d75c76dac521)

### Sources

https://www.army-technology.com/projects/s-300vm-antey-2500-anti-ballistic-missile-defence-system/
https://roe.ru/eng/catalog/air-defence-systems/air-defense-systems-and-mounts/%22Antey-2500%22%20(S-300VM)/
https://www.ausairpower.net/APA-Giant-Gladiator.html#mozTocId627173
https://en.missilery.info/missile/c300v/9m83

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
