### ISSUE TITLE
Update/correction for Karrar UCAV

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3582]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4903, 4904, 5591, 6429

### Summary of Changes

- Adjust Karrar fuel consumption. Current fuel consumption is too high compared to BQM-167A Skeeter(Aircraft/5281) which used TRI-60 engine (what Toloue-4 based on)
**BQM-167A Skeeter fuel consumption**
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/01a9552d-a983-4f14-915f-579f1424533d)
**HESA Karrar`s fuel consumption**
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/49ad6f86-aad9-44dc-a51b-5b32d1775a20)
**Toloue-4**
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/b3f7c0e6-196a-48ba-9406-122e699a181a)

- Add IR camera to Aircraft/5591. It probably can cover up to 270 degree FOV
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/0d6c54b4-02e5-424f-9986-1349b8e8759b)

- Increase altitude from 25k ft ceiling height to 40k ft and also increase top speed from 460 knots to 485 knots
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/5ba8a734-ae3a-4865-93c3-6e449c4535fd)

- Replace the aircraft`s properties from "Bombsight - Basic" to "Bombsight - Advanced Navigation (INS/GPS)" 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/fa563028-aef9-4302-a7a7-9ef72f469abd)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/6f7101d8-a8f3-41e5-bbd5-506458810ed6)

### Sources

- https://english.iswnews.com/28611/military-knowledge-karrar-drone/
- https://en.wikipedia.org/wiki/TEM_Toloue-4

**Comment by PygmalionOfCyprus** [comment]
Handled 502. Leaving the fuel consumption mostly as-is because it looks like the Skeeter is the one that's wrong. Mil speed should not burn less fuel than cruise...
