### ISSUE TITLE
Add Argentine RBS-70NG 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3583]
### DB Selector

DB3K

### DBID to Copy

Facility 3612

### Hypothetical

No

### Name

SAM Plt (RBS 70 NG MANPADS x 3)

### Country

Argentina

### Service

Army

### In Commission

2023

### Sources

https://twitter.com/SA_Defensa/status/1677349048334811136
https://www.saab.com/newsroom/press-releases/2022/the-armed-forces-of-the-argentine-republic-places-order-for-rbs-70-ng
https://www.defenseindustrydaily.com/saab-to-deliver-rbs-70-ng-to-argentina-plasan-sasa-to-provide-armor-package-for-spanish-vcr-dragon-philippine-mrrv-underwent-sea-trials-046550/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
