### ISSUE TITLE
Add Czech RBS-70 NG

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3584]
### DB Selector

DB3K

### DBID to Copy

Facility 3612

### Hypothetical

No

### Name

SAM Plt (RBS 70 NG MANPADS x 3)

### Country

Czech Republic

### Service

Army

### In Commission

2023

### Sources

https://twitter.com/ArmyRecognition/status/666196301231620096
https://www.saab.com/newsroom/press-releases/2018/saab-receives-rbs-70-ng-order-for-the-czech-republics-armed-forces
https://twitter.com/ArmadaCR/status/1641807961348620289
https://twitter.com/ArmadaCR/status/1532037003868483586

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
