### ISSUE TITLE
Swedish Navy new Surface ships

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3585]
### DB Selector

DB3K

### Baseline

3345 Visby class

### Hypothetical

Yes

### Name

Corvette/Frigate, pennant numbers unknown, HMS Luleå, HMS Norrköping, HMS Trelleborg, HMS Halmstad

### Class

Luleå class

### Country

Sweden

### Service

Navy

### In Commission

2030

### Number in Service

4, maybe more

### Length (m)

117

### Beam (m)

16

### Draft (m)

5

### Standard Displacement (t)

4100

### Full Displacement (t)

4300

### Complement

73

### Max Sea State

5

### Primary Propulsion Type

Diesel

### Propulsion

(CODLAG); 29 MW (39,000 hp) (total) Two shafts; controllable pitch propellers Two bow thrusters

### Fuel Capacity (kg)

12000

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

3500 nm

### Sensors

Saab 9LV combat management system
Saab Sea Giraffe 4A FF AESA 3D rada
Saab Sea Giraffe 1X short-range 3D radar
2 × Saab Ceros 200 radar and optronic tracking fire control directors
Dual-tow Patria Sonac DTS sonar
Kongsberg SS2030 hull-mounted sonar
Kongsberg SD9500 sonar

### Mounts

1x 57mm/70 Bofors Mk3 Gun (Front)
1x 35mm Rheinmetall Oerlikon Millenium Gun (Rear)
8x RBS 15 Mk4 Gungnir
1x Mk41 VLS, 32x RIM-162B ESSM 
4x400 mm Saab Lightweight Torpedoes Torpedo 47
4x MASS Dual TRAP Chaff/Flare
2x Seafox C ROV

### Aircraft & Docking Facilities

1x pad for medium helicopter
Docking for ROV & RIB

### Ship Codes

Degaussed Steel Hull, Advanced Quieting

### Comments

The future Surface ship for the Swedish Navy. A lot is not decided yet so the above is a guess just to have something to use in 2030 scenarios.
I've taken most of it from the Visby corvette and the new Finish Pohjanmaa-class and made it into a new ship type. It's hypothetical for now but I think most of it will be on the real ship. If its not enough for you we can wait for more info to be reveled.

### Sources

https://www.navalnews.com/naval-news/2023/06/swedens-future-surface-combatant-to-be-known-as-lulea-class/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
