### ISSUE TITLE
Swedish Navy Stridsbåt 90 HSM

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3586]
### DB Selector

DB3K

### Affected DBID(s)

Surface Ship 3468

### Summary of Changes

Add a 7.62mm MG parallel to the 12,7 HMG on the RWS
The boat have 5 gun mounts on the middle and aft decks, 2 to port, 2 to starboard and 1 facing aft. They are crew served.
These gun mounts can accommodate 12,7 HMG, 7,62 MG or 40mm Grenade launchers
Maybe a mix of 1 12,7 and 1 Grenade launcher on each side and a 12,7 or 7,62 facing aft?

The RWS is also able to facilitate a 40mm grenade launcher so a version of the boat with that would be appreciated.

The gun mounts are mentioned in the film in the link below.

### Sources

https://www.hamnen.se/nya-stridsbat-90-snabbare-starkare-och-farligare/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
