### ISSUE TITLE
AIM-9X for Norweigan F-35A

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3587]
### DB Selector

DB3K

### User(s)

US F-35A

### Weapons Carried

Make it possible for the Norweigan F-35s to carry AIM-9X Sidewinder

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Norway bought 90 AIM-9X Sidewinders in 2015 according to SIPRI arms transfer database

If it can carry them on outside pylons as on the picture in the link below it probably can carry them internally as well. 

### Sources

https://www.reddit.com/r/WarplanePorn/comments/otcy41/royal_norwegian_air_force_f35a_with_external/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
