### ISSUE TITLE
GBU-38 JDAM for Norwegian F-35A

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3588]
### DB Selector

DB3K

### User(s)

Unknown

### Weapons Carried

Add GBU-38 JDAM to Norweigan F-35A loadout

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

2015 to 2020 Norway bought almost 300 GBU-38 JDAM acording to SIPRI arms transfer database. It is most likely carried by the F-35.

In the link below GBU-38 can be carried by the F-15A.

### Sources

https://www.key.aero/article/what-weapons-can-f-35-carry-global-armaments-list

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
