### ISSUE TITLE
RCAF Lancaster B.1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#359]
### DB Selector

CWDB

### DBID to Copy

776 CWDB

### Hypothetical

No

### Name

Lancaster B.1 (Canada)

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1944-65

### Sources

https://en.wikipedia.org/wiki/List_of_aircraft_of_Canada%27s_air_forces
https://en.wikipedia.org/wiki/Avro_Lancaster
http://www.rwrwalker.ca/Cdn_RAF_AA100.htm

**Comment by Jkryos** [comment]
Added CWDB 494.
