### ISSUE TITLE
R-27R and ER Missile range

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#3590]
### DB Selector

DB3K

### Affected DBID(s)

R-27 & R-27ER

### Summary of Changes

Change
R-27R missile range upto 75km(40nm) current is 32nm

R27ER range upto 100km(54nm) current is 50nm

### Sources

http://roe.ru/eng/catalog/aerospace-systems/air-to-air-missile/r-27r1/

http://roe.ru/eng/catalog/aerospace-systems/air-to-air-missile/r-27er1/

**Comment by KLABDB3K** [comment]
....... Much argued/discussed..... This has been changed about four tines already....
