### ISSUE TITLE
Venezuelan Guaiqueri 2023 SSM Update

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3591]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2542

### Summary of Changes

Add 2 C-802 quads to Guaiqueri class. 
First ship to get this seems to be PO-14 Karina

### Sources

https://twitter.com/SA_Defensa/status/1679722020177690624
https://twitter.com/SA_Defensa/status/1659984660246458370
https://twitter.com/SA_Defensa/status/1659984660246458370/photo/3

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
