### ISSUE TITLE
Ship 3460 Ukrainian Sandown MCM naming details

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3592]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3460

### Summary of Changes

Add class and pennant number M 310 Chernihiv [Sandown Class]

M 310 Chernihiv
M 311 Cherkasy 

### Sources

https://www.navalnews.com/naval-news/2023/07/ukraine-commissioned-two-mcm-vessels/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
