### ISSUE TITLE
SU-30SM1 and 2 CAP+SEAD Loadout

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3593]
### DB Selector

DB3K

### User(s)

Aircraft 3819, Aircraft 6210

### Weapons Carried

Two R-73K short-range AAMs, four R-77-1 medium-range AAMs, one Kh-31P/PK ARM and two wingtip ECM pods (518-LSM1 and 518-PSM port and starboard wingtip pods.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The 1 Krypton pattern seems standard for CAP for VDK SU-35, SU-30 and SU-34 from mid-late 2022 on.  See https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2552

### Sources

https://twitter.com/GuyPlopsky/status/1669605005610074112

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
