### ISSUE TITLE
AN/TPY-4 radar

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#3594]
### DB Selector

DB3K

### Affected DBID(s)

Facility #3660

### Summary of Changes

Mast height is now set at 2 m. See picture [https://twitter.com/AirPowerNEW1/status/1653160400903368704/photo/3](url) Center of the radar is at least 4 meters.

Sensor Capabilities: please include TBM, satellite track

Range is now 300Nm but in staring mode a range of 540 Nm is mentioned. 
BTW is a staring mode programmable for you guys?

Norway can be added as user. Deliveries from 2025-2030.
[https://www.armyrecognition.com/defense_news_november_2022_global_security_army_industry/norwegian_air_force_selects_lockheed_martin_tpy-4_radar_to_enhance_homeland_defense.html](url)
[https://news.lockheedmartin.com/2022-11-17-Royal-Norwegian-Air-Force-Selects-the-Lockheed-Martin-TPY-4-Radar-to-Enhance-Homeland-Defense#.Y3Y4nUtsyCw.twitter](url)
[https://www.fma.no/aktuelt-og-media/2020/nye-radarer-til-forsvaret](url)

### Sources

[https://twitter.com/AirPowerNEW1/status/1653160400903368704/photo/3](url)

**Comment by HunterDNiu** [comment]
Yep as the original request author led like to see programmable radars. Perhaps better resolver with a forum entry.

**Comment by PygmalionOfCyprus** [comment]
Fixed mast height. Space search is already added. Max target alt of 100k ft, see: https://www.lockheedmartin.com/content/dam/lockheed-martin/rms/documents/ground-based-air-surveillance-radars/2024_BRO_59181-02_TPY-X_TPY-4_brochure_LETTER%20SIZE_v1.pdf

Programmable radars is on our wishlist as well.
