### ISSUE TITLE
SA.321L Super Frelon

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3595]
### DB Selector

DB3K

### DBID to Copy

CWDB Aircraft 4538 or DB3k Aircraft 1630

### Hypothetical

No

### Name

SA.321L Super Frelon

### Country

South Africa

### Service

Air Force

### In Commission

1967-1990

### Other Changes

Missed this one too, helpful for the Tafelberg LHA fit

### Sources

Issue #2675

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
