### ISSUE TITLE
ASM-3A Missile

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3598]
### DB Selector

DB3K

### Baseline

722

### Hypothetical

No

### Name

ASM-3A

### Length (m)

Likely the same as 722

### Width/Span (m)

Likely the same as 722

### Diameter (m)

Likely the same as 722

### Weight (kg)

Likely the same as 722

### Range (nm)

220nm

### Target Altitude / Depth (ft)

Likely the same as 722

### Target Speed (kts)

Likely the same as 722

### Launch Altitude / Depth (ft)

Likely the same as 722

### LaunchSpeed (kts)

Likely the same as 722

### Warhead

Likely the same as 722

### Targets

Surface Vessel

### CEP (m)

Likely the same as 722

### Sensors

Likely the same as 722

### Weapon Codes

Home On Jam (HOJ), Terrain Following, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS Navigation, Terminal Maneuver - Zig-Zag, Re-Attack Capability, Level Cruise Flight

### Comments

A new and upgraded version of the ASM-3 missile. It has a longer range than the original but other upgrades (if there have been any) are unknown. It was apparently undergoing testing  2020 but it isn't clear if it has already entered service on the F-2A/B fighters.

"On December 25, Japan’s Ministry of Defense announced it would begin mass production of the ASM-3A, an air-launched supersonic antiship missile. Japan began developing the ASM-3 in FY 2010 and completed a flight test in 2017. Following a review of defense requirements, Tokyo postponed acquisition of the ASM-3 in favor of an upgraded variant."

### Sources

https://en.wikipedia.org/wiki/ASM-3

https://www.navalnews.com/naval-news/2020/12/japan-to-field-new-asm-3a-long-range-supersonic-anti-ship-missile/

https://www.janes.com/defence-news/news-detail/japan-to-begin-mass-production-of-new-asm-3a-supersonic-anti-ship-missile

https://missilethreat.csis.org/tag/asm-3/

**Comment by KC45jp** [comment]
Duplicate:
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1940
