### ISSUE TITLE
Please consider increasing PoH% to 90% on the Chinese Type 1130 CIWS

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#360]
### DB Selector

DB3K

### Affected DBID(s)

2602

### Summary of Changes

Please consider increasing PoH% to 90% on the Chinese Type 1130 CIWS (DBID#: 2602). The Type 1130 CIWS puts out around 10,000-11,000 RPM, compared to the Type 730's (DBID#: 535) ~5500 RPM, but the PoH%'s are set to the same 70% in the database. Logically, the 1130 should have a higher default PoH% than the 730, due to the increase in RPM. I have cited sources that claim the Type 1130 CIWS is capable of intercepting threats up to a speed of Mach 4 with a 96% success rate, however, I recommend only increasing the PoH% to a max of 90% to prevent overpowering the weapon.. 

### Sources

1. http://www.navyrecognition.com/index.php/news/defence-news/year-2013-news/march-2013-navy-world-naval-forces-maritime-industry-technology-news/951-chinese-navy-liaoning-aircraft-carriers-hpj-14-type-1130-new-generation-ciws-.html
2. https://en.wikipedia.org/wiki/Type_730_CIWS#Type_1130

**Comment by PygmalionOfCyprus** [comment]
Slipped into 493. I increased the PoK to 80%, since going up to 90% would make it more effective than any other CIWS and I have significant doubts about the veracity of claims made on Chinese state TV.

**Comment by nkocevar** [comment]
Thanks!
