### ISSUE TITLE
Add Ukrainian Sapsan [Grom-2] Bn

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3600]
### DB Selector

DB3K

### DBID to Copy

Facility 3256

### Hypothetical

No

### Name

SSM Bn (Grom-2)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

few

### Other Changes

Domestic name is Sapsam, exported as Grom-2 [Hrim-2]
Does have cluster and unitary warheads (copied from Tochka) according to source
There is some skepticism that the Saudi's received there's and instead the battery was sucked into the war which makes sense.

### Sources

https://twitter.com/John_A_Ridge/status/1596988914220249088
https://www.thedrive.com/the-war-zone/does-ukraine-have-a-stash-of-domestically-developed-ballistic-missiles
https://en.wikipedia.org/wiki/Hrim-2
https://tass.com/politics/1608557
https://twitter.com/NOELreports/status/1667412877051822081

**Comment by FrangibleCover** [comment]
Should probably use Hrim instead of Grom, since it's the Ukrainian word.

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
