### ISSUE TITLE
Add Ukrainian Mech Inf Plt (M1126 Stryker IFV x3) 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3601]
### DB Selector

DB3K

### DBID to Copy

Facility 1899

### Hypothetical

No

### Name

Mech Inf Plt (M1126 Stryker IFV x3)

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

x90

### Sources

https://twitter.com/front_ukrainian/status/1648669019816296448
https://twitter.com/UAWeapons/status/1644089200390848512
https://twitter.com/NewsUkrainian24/status/1680112125237231618
https://twitter.com/NOTINAFO/status/1662826178900635649
https://twitter.com/JTranchee/status/1645072919540776961

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
