### ISSUE TITLE
Add Mech Inf Plt (M1224 MaxxPro x3)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3605]
### DB Selector

DB3K

### DBID to Copy

Facility 1899

### Hypothetical

No

### Name

Mech Inf Plt (MaxxPro x3)

### Country

Ukraine

### Service

Army

### In Commission

2022

### Number in Service

x440

### Mounts

copy and change name

### Other Changes

Ukraine use this in Motorized formations
Weapons fits are about the same
Increase armor maybe one level up (maybe..hehe)

### Sources

https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://en.wikipedia.org/wiki/International_MaxxPro
https://www.businessinsider.com/us-mine-resistant-maxxpro-armored-fighting-vehicles-indestructible-ukraine-russia-2023-6?utm_source=reddit.com
https://twitter.com/oryxspioenkop/status/1660729246581510147

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
