### ISSUE TITLE
Update/correction for IRIAF MIG-29 [Fakour-90 capable]

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3607]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 6728

### Summary of Changes

- Change the cockpit from Glass Cockpit [Partial] to Glass Cockpit. Based on the description below, it were supposed to looks like Mig-29M cockpit (second pic). Wrongly mistaken as partial glass cockpit in #3425 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/2f4b9c2e-e02a-4438-bc83-44a4c33eed36)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/1a18acad-493b-41fd-845c-375879b05e1a)

- Add Probe Refueling. IRIAF`s Mig-29UB have such capability, so hypo aircraft like Aircraft 6728 should probably have such capability as well
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/86ada6b5-a95b-4498-879d-67a31c2de3a0)

- Add guided weapon loadout as below:
**Qassed loadout**
2x Qassed (Weapon 3090)
4x Fatter (Weapon 4159)

**Sattar-4 loadout**
4x Sattar-4 (Weapon)
1x TLS-99 (Weapon 3089)
4x Fatter (Weapon 4159)

**Bina loadout**
6x Bina (Weapon 4161)
1x TLS-99 (Weapon 3089)
4x Fatter (Weapon 4159)

**Yasin loadout**
4x Yasin (Weapon 4120)
4x Fatter (Weapon 4159)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/921d5e31-ce8a-43b1-9572-d920b879212a)

### Sources

- https://stephensanford.substack.com/p/irans-f-14-fleet
- https://www.youtube.com/watch?v=YIt0ij1CsVI
- https://www.quora.com/Which-variants-of-MiG-29-are-used-by-Iran-9-12A-or-9-12B-variant

**Comment by zulualpha91** [comment]
I just assumed they will probably have dual/triple pylon taken from existing F-4 Phantom. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/2d2865d4-4b22-400c-aaea-532f4cab2137)

And for targeting pod, some Mig-29 have it right under air intake
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/2b8674d8-57eb-4d67-8a6d-7882c0237bf4)

**Comment by capcop98** [comment]
I just assumed they will probably have dual/triple rail/ejector taken from existing F-4 Phantom. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/2d2865d4-4b22-400c-aaea-532f4cab2137)

And for targeting pod, some Mig-29 have it right under air intake(near landing gear). So integrating TLS-99 targeting pod should not take up the pylon`s space.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/2b8674d8-57eb-4d67-8a6d-7882c0237bf4)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/6eb57319-b9f5-48bf-b524-890ef5ced9dc)

**Comment by FrangibleCover** [comment]
I'm not sold on this, where are the Fatters being carried if the strike payload is on the big Alamo pylons? They can't go on the little heatseeker pylons.

**Comment by capcop98** [comment]
Sorry if this is a stupid question, but isn't Fatter is basically AIM-9 copy, which itself is in the same category as R-60 and R-73? So I don't see the issue if it can't be installed at the pylon that can only accept FOX-2 missiles.  Or did I get it wrong?

**Comment by Jkryos** [comment]
Updated DB3K 509. I left the Bina loadout with only 2 as I would like to see the tri-rail system being flown first.
