### ISSUE TITLE
Add boat 7m and 11 davits to Famous Cutters

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3609]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1739, 303

### Summary of Changes

Looks like it can support 1 7m aft and 1 11m on the side (although looks like 1 typically carried)

### Sources

https://commons.wikimedia.org/wiki/File:USCGC_Thetis_WMEC910.JPG

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
