### ISSUE TITLE
Increase cargo capacity of US CCM Mk1

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3610]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2910, 4372

### Summary of Changes

Looks like the cargo capacity of 1 square meters prevents loading SEAL mobile units. 

Vigor says: 
4 Crew, 19 Passengers, Gear 10,000 lbs (5T)

I'd go 2-3 square meters (ships width is 4)

### Sources

https://vigor.net/projects/combatant-craft-medium-ccm
https://www.americanspecialops.com/boats/combatant-craft-medium/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
