### ISSUE TITLE
Denmark upgrades MH-60R helicopters

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3612]
### DB Selector

DB3K

### Affected DBID(s)

Helicopter #4553

### Summary of Changes

Danish MH-60R are ordering ASW equipment from the US.

ALFS dipping sonar
Sonobouys
Mk54 torpedos 

### Sources

https://www.navalnews.com/naval-news/2020/04/royal-danish-navy-enhancing-mh-60r-helicopters-asw-capabilities/

https://www.businesswire.com/news/home/20210427005026/en/Thales-Selected-by-Lockheed-Martin-to-Deliver-Airborne-Anti-submarine-Warfare-Sonars-to-the-U.S.-Indian-Greek-and-Danish-Navies

https://www.militaryaerospace.com/sensors/article/14179903/torpedo-upgrade-antisubmarine-warfare-asw

**Comment by tbrandon517** [comment]
Look like this was taken care of for db v501

https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=396598&sid=fc295b79411806d9778b31645b1a0af3
