### ISSUE TITLE
Add Yings III [Type 330,360,390] Targeting Pod

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3613]
### DB Selector

DB3K

### Baseline

weapon 459

### Hypothetical

Yes

### Name

Yings III [Type 330,360,390] Targeting Pod

### Length (m)

Don't think this is needed.

### Width/Span (m)

Don't think this is needed.

### Diameter (m)

Don't think this is needed.

### Weight (kg)

230kg

### Range (nm)

0

### Warhead

none

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway

### Sensors

CCD TV camera (gen 3)
FLIR (gen 3)
Laser designator

### Weapon Codes

Supports Buddy Illumination

### Comments

Most definitely looks Sniper or Litening III'ish. Same role. Likely replaces Blue sky pods in Pakistani and Chinese LGB loadouts. 

Looks like there are three sizes for pod and naming is about that. 330 (330mm), 360(360mm) and 390 (390mm)

Seems to be 2 variants. One very sniper looking with angled nose or some reasons sniper has it. Second is an older variant with round nose (might of been called WMD-7) in the past

### Sources

https://twitter.com/sohailahmedsa/status/1504351995699810305/photo/1
https://defence.pk/threads/avic-showcases-yings-iii-airborne-targeting-pod.461734/?utm_source=dlvr.it&utm_medium=twitter

To add to aircraft strike loadouts

J-16 from 2023 (360 model)
https://twitter.com/RupprechtDeino/status/1680939466154704897

J-10C (330 model)

https://twitter.com/RupprechtDeino/status/1654492242382340101

JH-7A
https://twitter.com/foolsball/status/1631276244363780098/photo/1

JF-17 Block III (390 model)
https://twitter.com/RelatedPakistan/status/795180810462699521/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
