### ISSUE TITLE
Finish NH-90 cant transport troops

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3614]
### DB Selector

DB3K

### Affected DBID(s)

Helicopter #2354

### Summary of Changes

Add Troop loadout to the helicopter, 15 soldiers in anti-crash seats or 20 without the seats

Add  7.62 mm Dillon 134 miniguns as a self-defense weapon

### Sources

https://verticalmag.com/features/a-look-at-the-only-helicopter-battalion-of-finland-natos-newest-member/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
