### ISSUE TITLE
M134 Mini gun on Swedish Stridsbåt 90

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3615]
### DB Selector

DB3K

### Affected DBID(s)

Surface ship #3468

### Summary of Changes

add 2 M134D 7,62 Mini Guns to the Stridsbåt 90HSM, 1 to port and 1 to starboard instead of 7,62 MG as requested in an earlier post. 

### Sources

https://www.defense-aerospace.com/sweden-orders-dillon-minigun-for-amphibious-battalion-combat-boats/

https://www.dagensps.se/weekend/bat-sjoliv/cb90-ng-marinens-nya-stridsbat-snabbare-och-tystare/

**Comment by PygmalionOfCyprus** [comment]
Don't write "Surface Ship", it confuses the bot. Just write "Ship". 😛

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
