### ISSUE TITLE
Ohio SSGN DDS Update

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3616]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 182, 565,667

### Summary of Changes

When you have some time please adjust:

Add out of service date of 2028 (boo!)
Currently can't add units as cargo. Maybe cargo stats aren't in yet?
Cargo space for 100 SEALS
Cargo space for up to DDS sized USV/UUV/ Seal Delivery Vehicles. Additional visilities for small drones (1-2 modified tubes and torpedo tube launched vehicles)
Tomahawks: Warzone soure says 100, which makes sense as DDS covers tubes, Looks like a couple tubes launch sea drones as well.
Adjust the mount weapons count to 100. Add possibly for UGM-109J variants to mounts and mags.
Add 1-2 more docking components to add small USV (modeling the tube deployments)
Add 1-2 facilities for Blackwings or other small air drones to be launched.

### Sources

Sources: Out of service, troop capacity, tomahawk counts and tube usage.
https://www.thedrive.com/the-war-zone/31121/how-the-ohio-class-guided-missile-sub-was-born-and-why-theyre-much-more-than-meets-the-eye
https://www.thedrive.com/the-war-zone/31121/how-the-ohio-class-guided-missile-sub-was-born-and-why-theyre-much-more-than-meets-the-eye

SSGN Tube mod 
https://www.engineering.com/story/navy-begins-test-of-uuv-launch-system

Air launched drones
http://www.navaldrones.com/SSGN.html
https://www.navy.mil/Resources/Photo-Gallery/igphoto/2002520668/

**Comment by dleake14** [comment]
Was hoping no one else would say anything - going to miss those 54 tomahawks!

**Comment by KushanGaming** [comment]
Partially done for DB502.

Submarines currently do not have cargo capability.

Reduced the number of Tomahawks to 98; 14 tubes x 7. Was 22 full cells. Figured the DDS would cover 8 of them. IR-CPS similarly adjusted. Also added Tomahawk Blk V TACTOM and MST to the mount 2016 variants mount.

Added 2 ROV/UUB Davit/Crane/Shelters.

Added Blackwing to 2016 and 2024 variants 3-inch decoy ejector.
