### ISSUE TITLE
Add Blk I and Blk III Virginia Class DDS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3617]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 651, 675

### Summary of Changes

Add Virginia Class DDS variants.

### Sources

Block III USS North Dakota 2019

https://www.seaforces.org/usnships/ssn/SSN-784-USS-North-Dakota.htm
https://twitter.com/ScotlandDX/status/1081990593025359873

Block I USS North Carolina 2022

https://www.reddit.com/r/submarines/comments/t48smi/uss_north_carolina_ssn_777_virginiaclass_block_1/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
