### ISSUE TITLE
Possible Issue IRT datalink on J-20/J-15/J-10 series of aircraft

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#3618]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft_5012, 5014, 5013, 2463, 5454

### Summary of Changes

The J-20 series of aircraft are likely intended to operate in a "system of systems" concept.  To do this, it is highly likely to have some form of datalink, similar to LINK 16.   See generally https://www.eurasiantimes.com/acting-as-eyes-ears-chinas-j-20s-role-to-guide-direct-jets/  Wikipeda similarly indicates a probable datalink capability https://en.wikipedia.org/wiki/Chengdu_J-20  **"Prototypes after application "2011" and production models feature a revised nose section with an electro-optical/infra-red targeting system and an advanced communications suite on top of the aircraft, enabling it to [datalink](https://en.wikipedia.org/wiki/Datalink) with other friendly platforms in service, such as airborne early-warning drones."**  See also https://airpowerasia.com/2020/08/15/chengdu-j-20-overhyped-or-reality-a-comprehensive-story/

To allow for players to use the J-20 as part of the "system of systems" approach, I recommend consideration given to equipping it with a datalink.  Similarly, post-2016 models of the J-10  (Aircraft_ 4617, _2057, 5259) and J-15 (AIrcraft_2496, 6098, 4817, 3311) the  should also be considered to have a LINK 16-type datalink

### Sources

See above

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
