### ISSUE TITLE
Add out of service date of 2014 for Ukrainian Grisha 5

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3619]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2526

### Summary of Changes

Add an out-of-service date of 2014.

They were never returned post-invasion. Ternopil was recently destroyed as a target ship. Russian Sunburn missiles still work.

### Sources

https://en.wikipedia.org/wiki/List_of_former_warships_of_the_Ukrainian_Navy
https://twitter.com/MrFrantarelli/status/1682299382572503040

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
