### ISSUE TITLE
Can you add vehicles to the DB as below?

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3623]
**BvS10** & BvS10 CATV
UK (Viking), Sweden (Bv410), Netherlands, France, Austria (BvS10), US (Beowulf)
https://en.wikipedia.org/wiki/BvS_10
https://www.armyrecognition.com/defense_news_december_2022_global_security_army_industry/swedish_army_to_get_bae_systems_bv410_articulated_vehicles_under_european_catv_programme.html

Patria AMW APC
https://en.wikipedia.org/wiki/Patria_AMV
https://www.militarytoday.com/apc/patria_amv_xp.htm
Sweden (Patgb 360)

Patria 6x6 APC
https://en.wikipedia.org/wiki/Patria_6%C3%976
Sweden (Patgb 300)

RG-32 Scout
Sweden (Tgb 16)

**Comment by og0172peli** [comment]
https://en.wikipedia.org/wiki/RG-32_Scout

**Comment by PygmalionOfCyprus** [comment]
We're not taking Ground Unit requests at this time.
