### ISSUE TITLE
Generic Mooring Buoy

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#3624]
### DB Selector

DB3K

### Baseline

#.347 NGS Buoy

### Hypothetical

No

### Name

Generic Mooring Buoy

### Class

N/A

### Country

Generic

### Service

N/A

### In Commission

N/A

### Number in Service

N/A

### Length (m)

N/A

### Beam (m)

N/A

### Draft (m)

N/A

### Standard Displacement (t)

N/A

### Full Displacement (t)

N/A

### Empty Displacement (t)

N/A

### Complement

N/A

### Max Sea State

N/A

### Primary Propulsion Type

Sail

### Propulsion

N/A

### Fuel Capacity (kg)

N/A

### Flank Speed (kt)

N/A

### Range (nm) at Speed (kt)

N/A

### Sensors

N/A

### Mounts

N/A

### Aircraft & Docking Facilities

N/A

### Comms/Datalinks

N/A

### Comments

I think just a clone of #.347 with Mk1 Eyeball removed would be fine. If we start sizing them all the list will be endless.

### Sources

[1] https://en.wikipedia.org/wiki/Single_buoy_mooring

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
