### ISSUE TITLE
Add Egyptian FREMM(GP) 1002 Al Galala[FREMM GP] 2021 x2

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#363]
### DB Selector

DB3K

### DBID to Copy

Ship #2169

### Hypothetical

No

### Name

1002 Al Galala[FREMM GP]

### Country

Egypt

### Service

Navy

### In Commission

2021

### Sensors

remove ESM and ECM suite

### Other Changes

Not the same as the French ASW they bought that is in the db. These are the italian general purpose variant

### Sources

https://twitter.com/mahmouedgamal44/status/1331611873444323329
https://twitter.com/mahmouedgamal44/status/1344598555978293251
http://navyrecognition.com/index.php/news/defence-news/2020/february/8081-egyptian-navy-to-buy-two-italian-european-multi-purpose-frigates.html
https://www.defensenews.com/global/europe/2020/02/18/italy-in-talks-to-sell-frigates-to-egypt/
https://twitter.com/D__Mitch/status/1336662455443918848
https://www.shephardmedia.com/news/digital-battlespace/italian-naval-ew-equipment-exports-tell-a-tale-of/

**Comment by PygmalionOfCyprus** [comment]
Whoops, sorry I left this one open for so long. We actually added this earlier in the cycle as part of a news roundup. My bad!

**Comment by bostonmyk** [comment]
No worries. Thank you!
