### ISSUE TITLE
Add Venezuelan Peykapp III [Zolfaghar] x2 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3633]
### DB Selector

DB3K

### DBID to Copy

Ship 2098

### Hypothetical

No

### Name

Peykapp III [Zolfaghar]

### Country

Venezuela

### Service

Navy

### In Commission

2023

### Number in Service

x2

### Sensors

same

### Mounts

Missiles are Nasr-1 which are C-704

### Sources

https://twitter.com/imp_navigator/status/1683839205569626113
https://twitter.com/SA_Defensa/status/1683824295410122752

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
