### ISSUE TITLE
Add Chaff and Flare to Y-20A

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3635]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4609

### Summary of Changes

Add 2 generic chaff/flare mounts similar to C-17 or other transports

### Sources

https://twitter.com/type36512/status/1684245448394145792
https://twitter.com/aviation07101/status/1541792817432903683
https://www.reddit.com/r/WarplanePorn/comments/y09sew/y20_unleashing_flares_760x1140/

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
