### ISSUE TITLE
Angolan Mi-35 update, second delivery

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3637]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4466

### Summary of Changes

Redate to 1990
Add 64x S-5 loadout, as #2792

### Sources

WAR OF INTERVENTION IN ANGOLA, VOLUME 5: ANGOLAN AND CUBAN AIR FORCES, 1987-1992 by Fontanellaz, Cooper & Matos p.i

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
