### ISSUE TITLE
Angolan Mi-35s, first delivery

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3638]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4466

### Hypothetical

No

### Name

Mi-24V Hind E [Mi-35]

### Country

Angola

### Service

Air Force

### In Commission

1987

### Number in Service

10x

### Mounts

Remove countermeasures dispenser

### Other Changes

In service in parallel to #3637, which had countermeasures.

### Sources

WAR OF INTERVENTION IN ANGOLA, VOLUME 5: ANGOLAN AND CUBAN AIR FORCES, 1987-1992 by Fontanellaz, Cooper & Matos p.i

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
