### ISSUE TITLE
Angolan Su-22M-4 date change

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3639]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1890

### Summary of Changes

Change date to 1989, the first delivery of fourteen strike aircraft and two trainers took place direct from the Soviets at the tail end of the Border War

### Sources

WAR OF INTERVENTION IN ANGOLA, VOLUME 5: ANGOLAN AND CUBAN AIR FORCES, 1987-1992 by Fontanellaz, Cooper & Matos p.57-58

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
