### ISSUE TITLE
Walker Bulldog gun fix

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3645]
### DB Selector

CWDB

### Affected DBID(s)

Facility 1494, 1953, 1531, 1643, 1954

### Summary of Changes

Change primary weapon from 37mm Nudelmann N-37 to the 76mm M32A1 with 32rds AP and 33rds HE ammo. I don't have any stats for it, at the scale that Command operates I'm not sure it matters. Mostly it's about removing the 50% accuracy autocannon. Clone the Weapon 1629 off the PT-76?

Remove two 7.62 MGs
Add a 12.7 MG, 20 shots, Weapon 154

### Sources

https://en.wikipedia.org/wiki/M41_Walker_Bulldog

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
