### ISSUE TITLE
Canada CC-330 Husky (A.330-200 MRTT) x9

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#3647]
### DB Selector

DB3K

### Affected DBID(s)

5181

### Summary of Changes

Updated designation and information for RCAF Strategic Tanker Transport Capability (STTC) project.

### Sources

https://www.canada.ca/en/department-national-defence/news/2023/07/the-strategic-tanker-transport-capability-project-and-norad-modernization0.html

![CC-330 Husky DND Info Brochure](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99632305/b6cea305-8b6e-47bd-a65f-92fe9f910c64)

https://defence-industry.eu/wp-content/uploads/2023/07/Canada-orders-4-new-A330-MRTTs-from-Airbus-Defence-and-Space-02.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
