### ISSUE TITLE
Casspir SIGINT

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3648]
### DB Selector

DB3K

### DBID to Copy

DB3k Facility 2284

### Hypothetical

No

### Name

Casspir SIGINT

### Country

South Africa

### Service

Army

### In Commission

1988

### Sensors

Unclear, but at a guess:
1x Casspir with Generic 80s ESM
1x Casspir with Generic 80s COMINT

### Mounts

2x Casspir

### Other Changes

Crew included a Chilean Mirage pilot who spoke Spanish, so they could intercept Cuban and Angolan GCI instructions.

### Sources

WAR OF INTERVENTION IN ANGOLA, VOLUME 5: ANGOLAN AND CUBAN AIR FORCES, 1987-1992 by Fontanellaz, Cooper & Matos p.23

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
