### ISSUE TITLE
Reduce Nebo-SV max range to 215nm,change bands to A/B

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3649]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 3006

### Summary of Changes

Changes: 
-decrease max range to 215nm  (400km)
-change frequency bands to A/B 

1L13 nebo-SV has a reported range of 320km at 20km altitude, 360km at 26km and I'm estimating around 400km for 30-36km altitude approximately. while figure isn't shown, the figures typically go from 500m to 36,000km.(an improvement/upgrade over the p-18). Also operates from 180-330MHz (0.18-0.3 GHz) A/B band
P-18 is thought to have a range of 300-360km (probably somewhere in between) so makes sense the Nebo-SV being a direct upgrade would have at least a 50-100km
![radartutorial nebo-sv](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/ca85aa15-7cef-4e75-bc34-a52eda2b942d)

![nebo-sv and svu max range](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/7180914f-477b-46b8-a8f2-50e20c77153f)

![nebo-sv and svu max range at 20km alt](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/6efdf2d5-2a20-4428-88f2-8c1c69547bb5)
pic showing approximate ranges for SV vs SVU for different altitudes. 320km for SV at 20km alt and 420km for SVU at 20km alt. Max alt is 36km for SV for a max range of around 400km. Whereas max range for SVU would be 500km for 36km alt given a max range of 450km at 30km in alt. Just approximations from given data. But SV would certainly have less range than the SVU upgrade.

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient3/karte071.en.html
https://www.globalsecurity.org/military/world/russia/nebo-svu.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
