### ISSUE TITLE
ScanEagle UAV unable to take off/land on aircraft carrier

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#365]
### DB Selector

DB3K

### Affected DBID(s)

#5237, #3349, #5392, #4818, #4292, #3347 ScanEagle UAV

### Description of Problem

The ScanEagles are currently experiencing the issue previously resolved for the XQ-58 Valkyrie where they can take off from ships but not aircraft carriers. 
If loaded on a CVN they get stuck on the constant waiting for runway loop. 
I have not tried it with all aircraft carriers but it will land on say #3129 LHA 8 Bougainville or #1008 R 08 Queen Elizabeth but will not land on #3197 CVN 81 Doris Miller.

### Recommended Fix

Make carrier capable. Thanks

I have included a link for the ScanEagles as well its a fantastic source of information on them, seems there are multiple variants and types available now. It is also very detailed on dimensions, sensor and datalinks etc.

https://www.insitu.com/products/scaneagle

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493. Also made some tweaks based on that source.
