### ISSUE TITLE
Change Nebo-SVU frequencies to A/B

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3650]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 3822

### Summary of Changes

-set operating frequency to A/B bands

operates on 1-2 meter wavelengths. As an upgrade to the SV L131 model, SVU operates on same frequencies ranging from 180-220mhz. ~1 meter wave is used for more precise track, whereas longer ~1.5-2m wavelengths used for detection. Dual mode

Here wavelengths of previous SV are shown
![radartutorial nebo-sv](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/d139b584-a5c6-4d4b-8b14-07eaa76784ad)

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient3/karte071.en.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502. A Band is 30-250 MHz so using the frequencies you provided I have switched it solely to that band and applied the exact frequencies to the sensor.

**Comment by GIGANTO-pithecus** [comment]
> Handled 502. A Band is 30-250 MHz so using the frequencies you provided I have switched it solely to that band and applied the exact frequencies to the sensor.

thanks !
