### ISSUE TITLE
change frequencies to A/B for RLM-M radar

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3651]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 4556

### Summary of Changes

-change operating bands to A/B

like the predecessor 1L31 nebo-sv and 1L119 nebo-svu, Nebo-M operates within the 180-330MHz range (1-2 meter wavelengths)
(upper part of A and low/mid part of B band)

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient3/karte071.en.html
https://www.globalsecurity.org/military/world/russia/nebo-svu.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 502.

**Comment by HVAA** [comment]
Missed this one, pity. Not above 225, military UHF comm band starts there, so to avoid being cheaply jammed (or at least having un-needed thermal noise put into the RX, these radars operate outside of comm band. So if your happy with 180 being RF Min, then you should conside 225 as RF Hi, which makes it (NATO) A band only.

**Comment by GIGANTO-pithecus** [comment]
> Missed this one, pity. Not above 225, military UHF comm band starts there, so to avoid being cheaply jammed (or at least having un-needed thermal noise put into the RX), these radars operate outside of comm band. So if your happy with 180 being RF Min, then you should conside 225 as RF Hi, which makes it (NATO) A band only.

So the NEBO series including SV, SVU, RLM-M and all Tall Rack uye should be only A band?

**Comment by HVAA** [comment]
Yes. VHF Comms precludes 88.5 to around 140 MHz from being available to radars. Then the UHF comm band cuts out 225 to 399.99 MHz

**Comment by GIGANTO-pithecus** [comment]
> Yes. VHF Comms precludes 88.5 to around 140 MHz from being available to radars. Then the UHF comm band cuts out 225 to 399.99 MHz

In this case, the radars mentioned above should be changed to A band in a separate request
