### ISSUE TITLE
 KM-SAM MFR radar range is too short

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#3656]
### DB Selector

DB3K

### Affected DBID(s)

Sensor_5696

### Summary of Changes

The KM-SAM radar is listed as having a range of 45nm.   It is likely closer to 54 nm range.  See  "KM-SAM Medium Range Surface-to-air Missile (SAM)." MilitaryLeak. Last modified November 9, 2017. https://militaryleak.com/2017/11/09/km-sam-medium-range-surface-air-missile-sam/.  See also https://battle-updates.com/update/contract-news-in-brief-912/, citing 

### Sources

See above

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
