### ISSUE TITLE
China, PLANAF, Y-9Q GX-14, Maritime Patrol Aircraft

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3659]
### DB Selector

DB3K

### Baseline

aircraft 3301

### Hypothetical

No

### Name

Y-9Q Cub [GX-14]

### Country

China

### Service

PLANAF

### In Commission

2022

### Length (m)

same as y-8q

### Wingspan (m)

same as y-9q

### Height (m)

same as y-9q

### Empty Weight (kg)

same as y-9q

### Maximum Takeoff Weight (MTOW) (kg)

same as y-9q

### Crew

same as y-9q

### Propulsion

same as y-9q

### Service Ceiling (ft)

same as y-9q

### Military/Afterburner Speed (kt)

same as y-9q

### Cruise Speed (kt)

same as y-9q

### Supercruise

No

### Ferry Range (nm)

same as y-9q

### Sensors

Change the ESM to Generic ESM [Advanced] 2020s.

### Mounts

same as Y-8Q

### Loadout Options

same as Y-8Q

### Sources

http://chinese-military-aviation.blogspot.com/p/surveillance-aircraft-ii.html
https://en.wikipedia.org/wiki/Shaanxi_Y-9

**Comment by PygmalionOfCyprus** [comment]
Y-9Q is the Y-8Q is the KQ-200. The KQ-200/Y-8Q is based on the stretched Y-8F which later received the new designation Y-9.

There may be some minor differences between the old/new variants but they have the same designation and for all intents and purposes this entry is covered by 3301.
