### ISSUE TITLE
Update: China, Y-9G, ECM Update

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3660]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4204

### Summary of Changes

Change the current Y-9G ECM to Generic Advanced 2010s since it was developed in early 2010s

### Sources

http://chinese-military-aviation.blogspot.com/p/surveillance-aircraft-ii.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
