### ISSUE TITLE
Add Hydra Rocket Loadouts to Ukrainian Hinds

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3663]
### DB Selector

DB3K

### User(s)

Aircraft 2637

### Weapons Carried

Swap out Soviet Rocket Pods with US 17 shot Hydra pods

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Czech-Republic donated Mi-24V seems to be what's pictured. 

### Sources

https://www.thedrive.com/the-war-zone/ukraines-mi-24-hinds-now-armed-with-u-s-70mm-hydra-rockets

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
