### ISSUE TITLE
Add Mech Inf Plt (CV90 IFV x 3) Ukraine 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3664]
### DB Selector

DB3K

### DBID to Copy

Facility 2056

### Hypothetical

No

### Name

Mech Inf Plt (CV90 IFV x 3) 

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

x50 

### Sensors

same

### Mounts

3 instead of 4

### Loadout Options

same

### Sources

https://twitter.com/Osinttechnical/status/1687963741936115712
https://www.kyivpost.com/post/19235
https://www.oryxspioenkop.com/2022/04/answering-call-heavy-weaponry-supplied.html
https://www.forbes.com/sites/davidaxe/2023/07/29/ukraine-has-lost-its-first-swedish-made-cv90-fighting-vehicle/?sh=59f8ae09157e
https://en.wikipedia.org/wiki/Combat_Vehicle_90

**Comment by bostonmyk** [comment]
https://twitter.com/bayraktar_1love/status/1685613408693972992

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
