### ISSUE TITLE
Add Ukrainian SCALP Loadout

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3665]
### DB Selector

DB3K

### User(s)

Aircraft 6725 and 6726

### Weapons Carried

2 SCALP EG
2 Aphid

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Little tomato/tomatoe but SCALP and Stormshadow could prove different someday.

Copy and Modify loadout 32996 for SU-24M Fencer D 6725
and
add same loadout to SU-24 MR Fencer E 6726

### Sources

https://twitter.com/oryxspioenkop/status/1688179762609426432

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
