### ISSUE TITLE
Add Ukrainian Magura V USV 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3666]
### DB Selector

DB3K

### Hypothetical

No

### Name

Magura V

### Class

Magura V

### Country

Ukraine

### Service

Navy

### In Commission

2022

### Length (m)

5.5 m

### Beam (m)

1.5m

### Draft (m)

.4m

### Standard Displacement (t)

2t

### Full Displacement (t)

2.5t

### Complement

0

### Primary Propulsion Type

Diesel

### Propulsion

2x Diesel

### Flank Speed (kt)

42 kt

### Range (nm) at Speed (kt)

450nm at 22 kt

### Sensors

Generic 3rd generation FLIR

### Mounts

1 Explosives mount like on vessel 607
200-300kg HE warhead

### Comms/Datalinks

SATCOM

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

Suicide craft but not always
Add flag to be carried by other things

### Sources

http://www.hisutton.com/Ukraine-Maritime-Drones-Evolution.html
https://en.defence-ua.com/weapon_and_tech/media_reveal_magura_v5_the_ukrainian_naval_drone_features_and_specifications-7471.html
https://navyrecognition.com/index.php/naval-news/naval-news-archive/2023/july/13391-idef-2023-ukraine-firm-ste-unveils-maritime-drone-usv-magura-v5.html

**Comment by PygmalionOfCyprus** [comment]
I'm just gonna roll up all the suicide USV tickets into #2883 (but this one does have a lot of stats so I may give the Magura V its own entry, or use it as the baseline for a generic...we'll see).
