### ISSUE TITLE
DDG 125 Jack H. Lucas Has Duplicate Weapons in MK41 VLS

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#3667]
### DB Selector

DB3K

### Affected DBID(s)

#.2718 DDG 125 Jack H. Lucas [Arleigh Burke Flight III], United States, Navy, 2024

### Summary of Changes

The **MK41 VLS [64 Cells] #.3989**  has a Duplicate of the **_(xx/64 RIM-174A ERAM SM-6 Blk 1A #.3541)_** Loadout. Should one of those be _**(xx/64 RIM-174A ERAM SM-6 Blk 1B #.3714)**_ or just **removed**. It is also duplicated in the **Database** entry.

Also when adding this in Editor it gets a missing Data Link Warning despite it already existing. This happens when adding new Aegis weapons to Ships or Subs even if you have already added the Data Link before hand.

### Sources

In Game

**Comment by PygmalionOfCyprus** [comment]
Handled 502. Not only did I fix the duplicate WR but I also swapped the VLS on the Jack H. Lucas to the correct Flight III / 2023 versions, which were in the DB but for some reason not added to the ship.
