### ISSUE TITLE
Vikrant should have 32 VLS cells not 64

### ISSUE THREAD

**Issue by Matharox** [PygmalionOfCyprus/cmo-db-requests#3668]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2515

### Summary of Changes

Currently Vikrant has 2x 32 cell Barak 8 VLS for a total of 64 cells but based on available information it's supposed to only have 32 cells in total. So one 32 cell should be removed.

### Sources

https://en.wikipedia.org/wiki/INS_Vikrant_(2013)
https://defenceforumindia.com/threads/ins-vikrant-aircraft-carrier-iac.77/post-2005933
https://defenceforumindia.com/threads/ins-vikrant-aircraft-carrier-iac.77/post-2330984
https://defenceforumindia.com/threads/ins-vikrant-aircraft-carrier-iac.77/post-2330999

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
