### ISSUE TITLE
Add DECM to Storm Shadow/SCALP-EG 

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3669]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 957, 333

### Summary of Changes

There is a growing consensus among researchers that Stormshadow/Scalp have some built in DECM pod against high band frequencies which interfere with RF proximity fuse command links

Add: dbid 228 (DASS DECM) but limited only for I/J band

 in vid below, pantsir-S1 Search/FCR and RF proximity fuse on missile seems to malfunction indicating a DECM built in to the STORMSHADOW. Target was locked on at close range by both acquisition and FCR successfully and launch was made twice, but missiles veered away from targets each time just before impact indicating presence of DECM that interfered with RF proximity fuse on each missile's semi-active radar seekers https://www.reddit.com/r/ukraine/comments/14gdyid/russian_pantsirs_attempting_to_shoot_down_a_storm/?rdt=50467

### Sources

https://www.reddit.com/r/ukraine/comments/14gdyid/russian_pantsirs_attempting_to_shoot_down_a_storm/?rdt=50467
https://twitter.com/lilspillz69420/status/1672009912250150917

**Comment by PygmalionOfCyprus** [comment]
This is plausible, but we don't have enough evidence to support it. Also, IR missiles aren't seduced by DECM. It is just as plausible that the Pantsir sucks. 🤷

If we get more corroborating evidence of DECM on SS/SCALP I'm happy to add it, but random Twitter dudes and Reddit comments do not a reliable source make.

**Comment by GIGANTO-pithecus** [comment]
> This is plausible, but we don't have enough evidence to support it. Also, IR missiles aren't seduced by DECM. It is just as plausible that the Pantsir sucks. 🤷
> 
> If we get more corroborating evidence of DECM on SS/SCALP I'm happy to add it, but random Twitter dudes and Reddit comments do not a reliable source make.

understandable, might be too much of a stretch to assume any built in EW whether defensive or offensive. But one was recently captured fully intact so who knows what discoveries the research institutes will make
