### ISSUE TITLE
OSF IR for Rafale F4/ Indian Rafale 

### ISSUE THREAD

**Issue by PatrioticFR** [PygmalionOfCyprus/cmo-db-requests#3670]
### DB Selector

DB3K

### Affected DBID(s)

Rafale F4 and Indian Rafale

### Summary of Changes

The Rafale F4 and the Indian Rafale (with ISE) got a new IRST/FLIR with early 2020 tech (similar to the Skyward-G) named the OSF IR.
Just need to change the #5498 OSF-IT [FLIR/IRST] present on those aircraft to the OSF IR [FLIR/IRST].
To change the capabilities of the sensor you can change the "Infrared Zoom Detection/Classification" from 20 to 30 like the Pirate / Skyward-G witch are the same generation.

### Sources

http://defens-aero.com/2019/01/rafale-standard-f4-lance.html
https://omnirole-rafale.com/avionique/evolutif/
https://omnirole-rafale.com/avionique/optronique-secteur-frontal/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
