### ISSUE TITLE
Spectra strd for Rafale F4 planes

### ISSUE THREAD

**Issue by PatrioticFR** [PygmalionOfCyprus/cmo-db-requests#3671]
### DB Selector

DB3K

### Affected DBID(s)

Spectra [DECM, F4 Std]; Spectra [LWR, F4 Std]; Spectra [RWR/ELINT, F4 Std]

### Summary of Changes

The new Rafale F4 has a new upgrade for Spectra.

You would just need to ass the same as the "Spectra F3R std" but with "Early 2020s Technology" instead of "Late 2010s Technology"

That's the same you did for other standard of the Rafale.

### Sources

https://omnirole-rafale.com/avionique/evolutif/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
