### ISSUE TITLE
Add Gamma-DE (Falaq) Radar for Iran

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#3674]
### DB Selector

DB3K

### DBID to Copy

Facility 3219

### Hypothetical

No

### Name

67N6E (Falaq)

### Country

Iran

### Service

Air Force

### In Commission

2019-present

### Number in Service

limited, few

### Sensors

-increase max range to 400km
-increase max altitude range to 120km

### Other Changes

limited number in service with Iran. 400km max reported range according to exporter site and 120km max height search/track range

-max range 215nm (currently set at 195nm)
-max altitude 120km (currently set at 30km)
![hqdefault](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/f340c897-ef3d-4b9c-ab37-3c99bba8aaa6)
![gamma-de range](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/20427dc0-9816-4989-a550-029e14c9fc4a)

![gamma radar](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/3b34b37c-7758-4f50-8537-662a439a5820)

### Sources

https://www.youtube.com/watch?v=0mjqz4r6Z24
https://en.wikipedia.org/wiki/Falaq_(radar)

https://www.radartutorial.eu/19.kartei/02.surv/karte063.en.html
https://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/%22Gamma-DE%22%20%2867N6E%29/

**Comment by bostonmyk** [comment]
Looks like it. The metal flap on the side and Array at the top are the same.  Not on a telescopic mass so shorter.

https://www.youtube.com/watch?v=0mjqz4r6Z24

**Comment by GIGANTO-pithecus** [comment]
> Looks like it. The metal flap on the side and Array at the top are the same. Not on a telescopic mass so shorter.
> 
> https://www.youtube.com/watch?v=0mjqz4r6Z24

Agree, without mast height looks to be about 9m? I believe only using telescopic mast 40v6m the height is around 24m or tallest mast 40v6md (40 m) in height

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
