### ISSUE TITLE
Decrease P-18 Max Range to 300km / 160nm

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3676]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 2693

### Summary of Changes

Decrease Spoon Rest D max range to 160nm (300km) or at very least 270km

P-18 Range figures for fighter type target 
500m alt       at least 60km
10,000m alt   at least 250km
27,000m alt  at least 270km
assuming max alt of 30-36km, it would be reasonable to guestimate a max range of 300km. Considering it says "at least 270km" for the corresponding altitude of 27km.
guess for 30,0000m alt   at least 300km? There's only a 20km increase in detection range from 10,000-27,000m in alt. So another 3-9km in alt wouldn't yield too much based off that. So 300km is more than a generous guess for max range.
![P-18-2-RLS-Spec](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/6666206d-92c2-4235-bfbd-11d31470b893)

Plus, having a 370km range would be a minor decrease from the upgrade Nebo-SV which has a 400km range. P-18 having a 270-300km range is much more likely considering Nebo-SV (upgrade has improved range of up to 400km).

### Sources

https://www.ausairpower.net/APA-Rus-Low-Band-Radars.html#mozTocId29312

**Comment by GIGANTO-pithecus** [comment]
Sensor 2693 (Spoon Rest D) P-18

**Comment by HVAA** [comment]
Really?  Please dont. Not all targets are fighters (RCS circa 2.5m2). There are the 'big boys' out there, like my jet with a 150 m2 RCS (at least).  The MTUR of this radar is circa 600km - the limit to this would be scope range, receiver sensitivity and radiated power - do we know all of this? Or are we trusting to a source which is often less than reliable.  What's the point of an 'up echelon', Early Warning radar that cannot see as far as the A2AD network it is supporting. Spoon Rest D is a modernised Spoon Rest with digital electronics and upgraded componets (albeit it looks like it was made from spare TV aerials and scaffold poles still...)
