### ISSUE TITLE
Island Class WPB's to Cameroon

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#368]
### DB Selector

DB3K

### DBID to Copy

ship/1738/DB3K

### Hypothetical

No

### Name

TBD (Island Class)

### Country

Cameroon

### Service

Navy

### In Commission

2022-

### Sensors

AN / SPS-73

### Mounts

Mk 38 Mod 0 25mm Bushmaster and two 12.7 mm M2NV machine guns

### Loadout Options

1x RHIB

### Other Changes

Not Known

### Sources

https://www.navyrecognition.com/index.php/news/defence-news/2020/june/8630-navy-of-cameroon-plans-to-purchase-two-island-class-american-patrol-boats.html?fbclid=IwAR0NlkqbpvZjhNqJCCCWK9KF-Ppf-ZIWMBk-tEK2qR6VT6ibj1DAIw1lZek

https://channel16.dryadglobal.com/navy-of-cameroon-plans-to-purchase-two-island-class-patrol-boats

https://www.defenceweb.co.za/featured/cameroon-to-receive-ex-us-island-class-patrol-boats/

**Comment by Jkryos** [comment]
Added DB3K 494.
