### ISSUE TITLE
Add Chinese and Saudi Arabian Silent Hunter 30 kw laser system

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3680]
### DB Selector

DB3K

### DBID to Copy

Facility 3230

### Hypothetical

No

### Name

Silent Hunter [30kw laser]

### Country

China, Saudi Arabia

### Service

PLA, Army

### In Commission

China 2016, Saudi Arabia 2022

### Number in Service

x8 Saudi Arabia

### Sensors

firing unit has optical and IR sensor and a small search radar at top. (maybe YLC-48)
separate search radar mount 3D S-Band called TWA. 

### Mounts

1x Mount similar to facility 3230.
1x tlwa Radar

### Sources

https://en.wikipedia.org/wiki/Silent_Hunter_(laser_weapon)

Saudi System
https://pdf.defence.pk/threads/saudi-arabia-deploys-chinese-laser-air-defences-silent-hunter-alongside-twa-low-altitude-surveillance-radars.754306/
https://twitter.com/benreuter_IMINT/status/1689254104961294336
https://twitter.com/FarooqB90714421/status/1428247453619326978
https://mil.in.ua/en/news/saudi-arabia-uses-laser-against-iranian-drones/
https://www.menadefense.net/mideast/larabie-saoudite-deploie-un-nouveau-radar-anti-drones-chinois/
https://defense-arab.com/vb/threads/166416/
https://twitter.com/China_Arms/status/1501017302417874965

China
https://militaryleak.com/2022/10/26/saudi-arabia-deploys-silent-hunter-laser-air-defense-systems-against-houthi-drones/
https://www.uscc.gov/sites/default/files/Fisher_Combined.pdf      pg8

3D-TWA
https://www.armyrecognition.com/defense_news_april_2021_global_security_army_industry/new_chinese_drone_countermeasures_unveiled_at_world_radar_expo_in_nanjing.html
https://www.globaltimes.cn/page/202104/1221903.shtml

YLC-48
https://www.radartutorial.eu/19.kartei/04.battle/karte044.en.html

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
