### ISSUE TITLE
Submarines Missing Datalinks

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#3681]
### DB Selector

DB3K

### Affected DBID(s)

Submarine #.554 & #.668

### Summary of Changes

The following Submarines are missing **Comm Device #.365 AEGIS Missile Datalink [Two-Way] (SSN)**

1. #.554 SSN 802 Oklahoma [Virginia Class, Flight V], United States, Navy, 2024
2. #.668 SSN 804 Barb [Virginia Class, Flight V], United States, Navy, 2027

### Sources

In game DB, the Flight III and Flight IV already have it installed, looks like it's just been missed on the Flight V's.

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
