### ISSUE TITLE
Change Voronezh-DM Frequency to B Band (lower portion of UHF)

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#3686]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5183

### Summary of Changes
change to B band
3 sources report Voronezh-DM to be decimetric at LOWER PORTION UHF (B Band)

![voronezh-dm uhf 3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/5bc16700-24ea-4da3-953a-4ed275c31fb3)

![voronezh-dm UHF ](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/b7b27b6d-fe51-4cae-8b8c-f804a7ac2bff)

decimetric translated below (UHF) usually B-C.
![voronezh-dm UHF decimetric](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/64b5896a-1d6a-4f33-bf09-c36c65896338)

### Sources

https://www.behance.net/gallery/13383435/77YA6-Voronezh-MDM
https://www.globalsecurity.org/wmd/world/russia/voronezh-variants.htm
https://en.wikipedia.org/wiki/Voronezh_radar
https://military-history.fandom.com/wiki/Voronezh_radar

**Comment by HVAA** [comment]
Has to be above 399.95 (top frequency of mil UHF comms) to avoid interferrence (from the busy UHF comm band). Has to be above 406 (SAR Frequency which the Russians pioneered and now the whole world use). It has to be below 500 or it goes into other busy bands with commercial stuff (old TV signals etc). So it has to be a B Band (NATO) system.

**Comment by GIGANTO-pithecus** [comment]
> Has to be above 399.95 (top frequency of mil UHF comms) to avoid interferrence (from the busy UHF comm band). Has to be above 406 (SAR Frequency which the Russians pioneered and now the whole world use). It has to be below 500 or it goes into other busy bands with commercial stuff (old TV signals etc). So it has to be a B Band (NATO) system.

fixed the title. Changed to B band only (which is the lower portion of UHF)
