### ISSUE TITLE
Add AESA property to DON-2NP Radar

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#3688]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 2520

### Summary of Changes

Upgraded/major overhaul for DON-2NP is known to be to AESA antenna design based on multiple sources 
![don-2n aesa 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/54338be8-4fc5-404b-84e7-90ea660d837b)
![DON-2N AESA](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/90938c22-bcc8-4ed2-b465-1ee573f2816e)
![don-2n aesa 3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/6ab264a4-3cbc-44f1-95d3-4c1592efe09d)

### Sources

https://www.globalsecurity.org/wmd/world/russia/pill_box.htm
https://www.wikiwand.com/en/Don-2N_radar
https://en.wikipedia.org/wiki/Don-2N_radar

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
