### ISSUE TITLE
Add AESA Property to Daryal Radar

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3689]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 3816, Sensor 3815

### Summary of Changes

Daryal (pechora) radar uses an AESA array 
![daryal aesa 3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/a6f09fe7-9f5a-4e3d-b523-b89c202c8c56)
![daryal aesa 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/3424eb37-a317-44fe-af9e-f03184424830)
![daryal aesa 1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/ec32d3e7-0901-4af8-ab56-161fbe7d2edc)

### Sources

https://en.wikipedia.org/wiki/Daryal_radar
https://military-history.fandom.com/wiki/Daryal_radar

**Comment by GIGANTO-pithecus** [comment]
Not AESA. Confused sources, apparently was never upgraded to AESA. PESA similar to the AN/FPQ-16 PARCS

**Comment by HVAA** [comment]
If you are still following this one, then look online, the suggestion on the site is that the AESA was developed and fielded in the 70's whereas AESA's werent a thing until the late 80s, mid 90's.  As the link in the wiki is smack next to the claim, following the link is a cautionary tale as to why wikipedia is often wrong and contradicts itself.

**Comment by GIGANTO-pithecus** [comment]
> If you are still following this one, then look online, the suggestion on the site is that the AESA was developed and fielded in the 70's whereas AESA's werent a thing until the late 80s, mid 90's. As the link in the wiki is smack next to the claim, following the link is a cautionary tale as to why wikipedia is often wrong and contradicts itself.

Yes, true. Wikipedia is usually wrong in many cases. Radartutorial as well
