### ISSUE TITLE
Add Dipikar class Ship, Cameroon Navy

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#369]
### DB Selector

DB3K

### Baseline

2541

### Hypothetical

No

### Name

Patrol Boat (PBO), P107, Dipikar

### Class

Dipikar (Flamant, OPV 54)

### Country

Cameroon

### Service

Navy

### In Commission

2012 - present

### Length (m)

54.8

### Beam (m)

10

### Draft (m)

2.8

### Standard Displacement (t)

319

### Full Displacement (t)

396

### Complement

19 + 4 extra (scr4)

### Primary Propulsion Type

Diesel

### Propulsion

CODAD, 2x Deutz/MWM 16V TBD 620 diesels

### Fuel Capacity (kg)

55000 (55t)

### Flank Speed (kt)

22 (src1), 24 (src2)

### Range (nm) at Speed (kt)

4500 @ 14

### Sensors

1x Navigation Radar: DRBN38A,
Unkown EO sensor (images),

### Mounts

2x Single 12.7mm MG

### Aircraft & Docking Facilities

1x 6.7 mtr Zodiac RHIB, launched astern

### Comments

1 unit in class. Ex- Grebe P679 (French navy 1991-2010).
Update in 2016: 2x Consilium-Selesmar Nav radars (?I & E/F), 1x twin 20/70 Mk24 (src2).
Can make 8kts under electric motors(cf src2). 

### Sources

1: JFS 2017-2018;
2: https://www.navypedia.org/ships/cameroon/came_cf_dipikar.htm;
3: https://en.wikipedia.org/wiki/Flamant-class_patrol_vessel;
4: https://wikimonde.com/article/Marine_nationale_%28Cameroun%29;
5: https://aviationsmilitaires.net/v3/forum/forces-navales-7/topic/marine-nationale-du-cameroun-2657/?post=94483#post-94483;
6: https://www.meretmarine.com/fr/content/toulon-le-patrouilleur-dipikar-ex-grebe-embarque-pour-le-cameroun;
![3Posted](https://user-images.githubusercontent.com/99532490/155283219-a9c43a52-1866-41dd-82e0-75e72873a24a.jpg)
![5Posted](https://user-images.githubusercontent.com/99532490/155283234-4c9120dd-1479-491f-9193-c17e4f8a3b2d.jpg)
![9Posted](https://user-images.githubusercontent.com/99532490/155283253-609dceb0-4e5a-40fc-af98-ee76041a053c.jpg)
![11Posted](https://user-images.githubusercontent.com/99532490/155283262-7a1d2e32-61ee-4fcc-9e39-60e78de82645.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
