### ISSUE TITLE
Add PESA property to N-011M Bars-R Radar

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#3694]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5298

### Summary of Changes

N-011M, unlike its predecessor N011, uses a PESA hybrid antenna. It has much less phase shifters and transceivers on its antenna that the Irbis-E has, which is why the N-011M has a SAR resolution of 10m, whereas the Irbis-E has a SAR resolution of 1m. Also, N-011M can engage 4 targets, unlike the earlier N-011 which could only engage 2.

**Changes: 
-Add PESA to properties
-Increase # of engaged targets to 4**

![n011m-r 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/5ae7de80-8ed2-44e7-a8bc-b11130e03793)

![n011m-r](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/90b5a7e6-2bbb-47e2-a0ed-962f10cc6577)

### Sources

https://www.ausairpower.net/APA-Flanker.html#mozTocId332358
https://en.wikipedia.org/wiki/Bars_radar
https://www.globaldefensecorp.com/2021/03/12/bars-a-glorified-soviet-era-phased-array-radar/

**Comment by GIGANTO-pithecus** [comment]
apparently it's almost a PESA. It's a combination of standard mechanically steered pulse doppler with elements of a PESA. So not a true PESA. More like a primitive, hybrid PESA

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
