### ISSUE TITLE
Fix Anka A #4978 CIRIT loadout and add laser designator to EO device

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#37]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #4978 Loadout 27888

### Description of Problem

Loadout has 38 which is far too many. Looks like 4 per launcher. EO device does have a laser designator for weapons. This may be needed for All Anka variants that will fire laser-guided weapons.

https://quwa.org/wp-content/uploads/2017/04/Anka-armed-Turkish-MoD.png
https://en.wikipedia.org/wiki/Roketsan_Cirit

### Recommended Fix

Adjust number to 4 per wing. Wire up datalink between EO and Missile for designation

**Comment by PygmalionOfCyprus** [comment]
Fixed (and renamed) loadout and swapped AselFLIR to designator variant on armed Anka. Should be able to laze for its Cirits now. DB 493.
