### ISSUE TITLE
Loadouts for BL.755 with No.2 bomblets

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3701]
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

Change the following RAF loadouts to use Weapon 526, the upgraded BL.755:
- [x] 3924
- [x] 141
- [x] 3154
- [x] Clone of 2578 for Aircraft 36
- [x] 3633
- [x] Clone of 23291 for Aircraft 100 and 101
- [x] Clone of 191 for Aircraft 100 and 101

I suppose these could all be cloned loadouts to maintain backwards compatibility with basic BL.755, I'm not sure how quickly they were retired or if they were retained for soft-targets.

### Sources

Database
https://www.armedconflicts.com/GBR-BL-755-t64335

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
