### ISSUE TITLE
China, HQ-9B and HHQ-9B surface to air missile, air probability of hit

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3703]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3763 4090

### Summary of Changes

Change the current Air PoH to 90%. (Same as the SA-21 and SM-6, they are all on the same level of tech)

### Sources

https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/china/china-anti-access-area-denial/hq-9/
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/4a2e7027-de51-4ba0-9d84-68777e27de3e)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
