### ISSUE TITLE
China, Type 095 Sui SSGN, overall upgrade

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3704]
### DB Selector

DB3K

### Affected DBID(s)

submarine 676

### Summary of Changes

For a long time, this type of sub is just a copy-paste of type 093 Shang class SSN but with GLCM.

Here I think there should be some change on it:

- [x] 1. Change the signatures to the same level with SSN 774 virginia flight I (the signatures of [DBID submarine 40] for reference, I think you can just copy it). Early 2000s US tech, Adm. Samuel Paparo said "by generation, think 10 or 20 years" between the gap of China and US sub technology.

- [ ] 2. Change the mount VLS number to 18.

- [ ] 3. Add YJ-18 and YJ-21 to the VLS magazine. Keep CJ-10A SLCM in the magazine too.

- [x] 4. Remove the Yu-6 from the current magazine and torpedo mount. Increase the number of Yu-10 in the magazine to 28.

- [x] 5. Add [Nonmagnetic Hull] [shrouded Propulsor] [Advanced Propulsor] [shock Resistant] to properties.

- [x] 6. Change the standard displacement to 8000t, the full displacement to 10100t

More to be added in the future, I will then open other threads.

### Sources

https://en.wikipedia.org/wiki/Type_095_submarine
https://digital-commons.usnwc.edu/cmsi-maritime-reports/30/
https://www.cbsnews.com/news/u-s-navy-readiness-as-china-builds-up-naval-force-threatens-taiwan-60-minutes-transcript-2023-07-02/
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/f4c19518-a80c-4546-a1ac-b04143d8fff8)

**Comment by Jkryos** [comment]
Added DB3K 505.

**Comment by LuigiP57** [comment]
@Jkryos May I ask why 2 and 3 are not marked as completed?
