### ISSUE TITLE
Add Belarussian Mi-35M

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3705]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5857

### Hypothetical

No

### Name

MI-35M

### Country

Belarus

### Service

Air Force

### In Commission

2023

### Number in Service

x4 +

### Sensors

Same. 

A little bit of eyestrain but does look like they've got the Vibetsk gear.

### Mounts

Same

### Loadout Options

Same

### Sources

https://twitter.com/GuyPlopsky/status/1692522593616908609
https://tass.com/defense/1661793
https://www.facebook.com/Scramblemagazine/posts/belarus-orders-first-batch-of-mi-35m-combat-helicoptersa-delegation-of-the-armed/3941899202503251/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
