### ISSUE TITLE
JF-17 block 3 corrections

### ISSUE THREAD

**Issue by Matharox** [PygmalionOfCyprus/cmo-db-requests#3706]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4827

### Summary of Changes

- Change from "JF-17A" to "JF-17C", as that is the actual designation
- Remove IRST (it was originally planned but did not make it to production)

Loadout changes:
- It carries the KG-600 DECM pod and not the KG-300
- Change A/A loadouts to 4x PL-12s

### Sources

https://twitter.com/Defence_IDA/status/1592432081183080450?s=20

https://pbs.twimg.com/media/F0B0HXAacAAHY5_?format=jpg&name=4096x4096 

https://live.staticflickr.com/65535/53053634932_5b80f63feb_k.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
