### ISSUE TITLE
Copy Facility and update SA-21 S-400 Growler Indian AF

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3710]
### DB Selector

DB3K

### Affected DBID(s)

Cooy Facility SA-21 Growler facility any post 2017

### Summary of Changes

Add to Indian AF also quad pack 9M96D missile option for each S400 launch position. 

### Sources

https://twitter.com/krakek1/status/1692920298251637096?t=06x7EFLNd-fSLKt-TYtSWg&s=19

https://www.armyrecognition.com/defense_news_august_2023_global_security_army_industry/s-400_air_defense_system_arrives_in_india.html

Indian AF. 2023 per X.

**Comment by PygmalionOfCyprus** [comment]
Facility already exists in DB3K as 3807. Gonna tackle the quadpack with a larger overview (read: unfucking) of the S-400s in #2016
