### ISSUE TITLE
Type 21 minor edits

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3712]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Ship 1779, 991, 933, 1966, 1254, 1257, 1255, 1256; CWDB Ship 126, 2518, 2519, 127, 2323

### Summary of Changes

- [x] The Database includes a tag for ships with an aluminium superstructure, giving -20% DP. The Amazon class very famously had aluminium superstructures. While I'm not totally convinced by the penalty being that significant, they should have the tag if anything should.

- [x] CWDB 2323 is not marked as a hypothetical when it should be.

Three of the Amazons were not initially fitted with Exocet, which is represented in the database but the naming is quite confusing. I suggest the following changes.
- [x] The RN ships marked [Type 21 Amazon Class] should be 'x3, one lost in Falklands' or similar.
- [ ] The RN ships marked Exocet should be 'x5', except the 1983 one which should be 'x4', and renamed F 171 Active after the first ship with Exocet when commissioned.
- [ ] The final RN ship, DB3k 1966, should be marked 'x6' after Amazon and Ambuscade were refitted with Exocet. This refit took place between 1984-1986 so there's no need to adjust dates.

### Sources

https://en.wikipedia.org/wiki/Type_21_frigate

**Comment by PygmalionOfCyprus** [comment]
Handled 503. I'm just not bothering with tracking ship numbers for the various ups and downs of when what was converted. The DB isn't really meant to track those minutia, and when things like upgrades over time or casualties come into the mix we just don't.

**Comment by FrangibleCover** [comment]
Yeah, that's fine. Mostly this suggestion was because I find the current naming scheme actively confusing.
