### ISSUE TITLE
V-247 Vigilant Sonobuoy Datalink 

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3715]
### DB Selector

DB3K

### Affected DBID(s)

6722, 6723

### Summary of Changes

Add Sonobuoy datalink to USMC and USN V-247 Vigilant. 

### Sources

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=397535

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
