### ISSUE TITLE
Add CIRCM and MAWS to MH-47G Block II

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3719]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5292

### Summary of Changes

CIRCM replacing the previous AN/AAQ-24 LAIRCM on the fuel sponsons as well as 2x AN/AAR-47 MAWS

### Sources

https://twitter.com/monarchiav/status/1694341740499439935
https://www.dote.osd.mil/Portals/97/pub/reports/FY2020/army/2020ch47f.pdf?ver=_IUI_wy1G1gmmW03q-CJZg%3D%3D
https://5abe1488a536b7d66554-40ebbf4e472cfd77f5021bc42c60f8a3.ssl.cf1.rackcdn.com/b3wa38lufdjoumxilffcoezyiqzy5m-optimized-pub.pdf pg. 43

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
