### ISSUE TITLE
Type 26 - Unable to add boats to 3 out 4 of the type 26

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#372]
### DB Selector

DB3K

### Affected DBID(s)

#2514 (UK), #2795 (UK), #3192 (Canada), Type 26 City Class

### Summary of Changes

Should be able to carry boats and UUV's in Integrated Mission Bay. The Australian version (#3414 - FXX Hunter [Type 26 City], 2027) already has this.

### Sources

https://www.baesystems.com/en-uk/productfamily/type-26-global-combat-ship

https://www.baesystems.com/en-uk/product/global-combat-ship

**Comment by PygmalionOfCyprus** [comment]
Brought all Type 26 docking facilities in line w/ Australian version.
