### ISSUE TITLE
F-117 radar signature

### ISSUE THREAD

**Issue by C7M3s0g1T8** [PygmalionOfCyprus/cmo-db-requests#3720]
### DB Selector

DB3K

### Affected DBID(s)

1905, 1906, 1217, 245, 2524, 272, 1129, 6738, 4647, 4648, 4649, 4680, 4650, 4679, 4651, 

### Summary of Changes

Radar, A-D Band (30-2000 MHz) Front: -10 dBsm    Side: +10 dBsm    Rear: -10 dBsm
Radar, E-M Band 2-100 GHz)  Front: -40 dBsm    Side: +5 dBsm    Rear: -30 dBsm

### Sources

Empirical Study of Flight-Dynamic Influences on Radar Cross-Section Models (DOI: 10.2514/1.C033566) page 2
Calculation of Aircraft Target’s Single-Pulse Detection Probability (DOI: 10.5028/jatm.v7i3.470) page 318

**Comment by C7M3s0g1T8** [comment]
![Capture](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/142176007/b3d4e5ae-653f-419f-83eb-319af7adecff)
![Capture2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/142176007/9299b502-f613-44bd-9d8b-13d61180efbc)

**Comment by PygmalionOfCyprus** [comment]
These numbers are all guesswork without info on the RAM composition. Our numbers have so far generally matched historical and unclassified information so I'm going to assume they're good enough for unknown specifications as well.
