### ISSUE TITLE
MK 23 "Katie" nuclear shells for Iowa Class 16in main guns

### ISSUE THREAD

**Issue by Loki1701e** [PygmalionOfCyprus/cmo-db-requests#3721]
### DB Selector

CWDB

### Baseline

#781 - 406mm/50 Triple HiCap Salvo [3 rnds]

### Hypothetical

No

### Name

MK23 "Katie" Nuclear shell

### Length (m)

1.626

### Width/Span (m)

0

### Diameter (m)

.406

### Weight (kg)

862

### Range (nm)

21nmi

### Target Altitude / Depth (ft)

ground level

### Launch Altitude / Depth (ft)

sea level 

### LaunchSpeed (kts)

34 knots

### Warhead

15-20kt equivalent nuclear warhead  

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

140

### Sensors

no sensors

### Comments

mk23 katie is essentially a nuclear 16 in shell derived from the w19 atomic cannon shell.  Has the same weight, length, and characteristics as the mk13 and mk14 HE shells but instead of the HE filler its a thermonuclear warhead. Was made and put in inventory but never known if it was actually deployed or not due to us policy. only 1 turret on the ships were capable of housing the shells due to security reasons. iirc it was turret 2 but dont quote me. only in inventory to the early to mid 80s where it was believed to be dismantled. If they did carry them it would probably only be 3-5 shells. Picture below. It is also in the source below. Source is pretty credible for the long time i have been using it.  

![WNUS_16-50_mk7_Nuclear_pic](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/143149165/b67be0c2-780f-4f35-9f1d-f1fee571c07e)

### Sources

http://www.navweaps.com/Weapons/WNUS_16-50_mk7.php

**Comment by Loki1701e** [comment]
> 

ah my bad

**Comment by Loki1701e** [comment]
closed

**Comment by tbrandon517** [comment]
> > 
> 
> ah my bad

It's totally possible the entry could need to be tweaked.

**Comment by Loki1701e** [comment]
> > > 
> > 
> > 
> > ah my bad
> 
> It's totally possible the entry could need to be tweaked.

that is true

**Comment by Loki1701e** [comment]
"USS Iowa, USS New Jersey and USS Wisconsin had an alteration made to Turret II magazine to incorporate a secure storage area for these projectiles. USS Missouri was not so altered as she had been placed in reserve in 1955. This secure storage area could contain ten nuclear shells plus nine Mark 24 practice shells. "

**Comment by Loki1701e** [comment]
also my source states the shells were withdrawn from service by 67 which iirc complements other sources. but nuclear stockpiles are always vauge at best

**Comment by PygmalionOfCyprus** [comment]
Took a quick glance at the entry just to see if anything was obviously wrong. Guns are pretty sparing when it comes to DB-side data so not too much to fill in. I did rename it to "406mm/50 Mk.23 Nuke Salvo" and added "Katie" to the comments so it's not as generic.

**Comment by Loki1701e** [comment]
oh cool thanks
