### ISSUE TITLE
Add Vietnam CG Ship Stan Patrol 4100

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3737]
### DB Selector

DB3K

### DBID to Copy

Ship #3582 (Jaguar)

### Hypothetical

No

### Name

SAR-411 (Stan Patrol 4100)

### Country

Vietnam

### Service

Coastguard

### Number in Service

3

### Sensors

2x Nav RADAR (Probably 1x I & 1X E/F)

### Mounts

No mounts (images)

### Other Changes

Believe this class differ from #3582 with the slipway. The #3582 has a slipway to launch a RHIB. It looks like the SAR-411 has not. This differ the launch and recover times of thoses RHIBs.
The Stan Patrol 4100 is from same origin as the 4207 but reported slightly larger.

### Sources

https://en.wikipedia.org/wiki/Damen_Stan_Patrol_4100
https://vi.wikipedia.org/wiki/Trung_t%C3%A2m_Ph%E1%BB%91i_h%E1%BB%A3p_t%C3%ACm_ki%E1%BA%BFm,_c%E1%BB%A9u_n%E1%BA%A1n_h%C3%A0ng_h%E1%BA%A3i_Vi%E1%BB%87t_Nam
https://www.baogiaothong.vn/chum-anh-ben-trong-tau-cuu-nan-tren-bien-hien-dai-nhat-viet-nam-192411643.htm
https://www.vesselfinder.com/vessels/details/9287259

![SAR-411_1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/ff177d94-6934-4cb4-bd99-3a66650b67b3)
![SAR-411_2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/4d223b1a-67de-4d16-8796-d997bf832c45)
![SAR-411_3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/cb48715e-76e8-41fc-b4be-29e505e722ac)
![SAR-411_4](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/362d9ecb-fe17-4f1d-b650-4fa3d5deb7ec)
![SAR-411_5](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/d9744d6c-15a7-4b03-86ed-83f4c30b7fb4)
![SAR-411_6](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/f5c7669a-f0e6-44ec-b256-4ba2630ba634)

* Vietnam Maritime search and Rescue Coordination Center

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
