### ISSUE TITLE
MV-22 range with troop loadout is ridiculously low

### ISSUE THREAD

**Issue by transientSG** [PygmalionOfCyprus/cmo-db-requests#3738]
### DB Selector

DB3K

### Affected DBID(s)

#4317, #297, #3709, #4307, #5318

### Summary of Changes

Please change the range radius of the MV-22 when using 24x troop loadout from current range radius of 245nm to somewhere between 500nm to 550nm. 

As it is currently, the range radius with a plain 24x troop loadout is less than the current MV-22 range radius with a 9 ton loadout. Not quite likely yes?

Also, the CV-22 range with troop loadout is 600nm, the disparity is glaring.

### Sources

https://nps.edu/documents/103424733/107333295/V22+Easterly+presentation+Oct+14+2004.pdf/4acefce6-89a0-486b-9117-2debf8ff779b

https://books.google.com.sg/books?id=W1B7d9eKY14C&pg=PA22&lpg=PA22&dq=mv-22+range+radius&source=bl&ots=1Fso3GhUVW&sig=ACfU3U3giDh_XWjXrwQ1f_Vmgztx-GYzbg&hl=en&sa=X&ved=2ahUKEwjo1umJ0_yAAxUhxzgGHdT2Cv84FBDoAXoECCkQAw#v=onepage&q=mv-22%20range%20radius&f=false

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
