### ISSUE TITLE
Add Barbados CG SP4207 (Trident)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3739]
### DB Selector

DB3K

### DBID to Copy

Ship #3578 

### Hypothetical

No

### Name

Trident class (Stan Patrol 4207) - P01

### Country

Barbados

### Service

Coastguard

### In Commission

2008

### Number in Service

3

### Sensors

2x Navigation RADAR (?i & E/F)

### Mounts

2x 12.7mm (both sides on image)

### Sources

https://citizendium.org/wiki/HMBS_Leonard_C_Banfield
https://www.homelandsecurity-technology.com/projects/damen-stan-4207-patrol-vessel

![SP4207_1(Barbados)](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/cbd98b63-fff5-452d-be79-d7f30ee1651b)
![SP4207_2(Barbados)](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/98eee7cb-2559-4afd-9228-ead22aa762da)
![SP4207_3(Barbados)](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/71316d8e-22c3-4e42-b929-a13b50a3212b)
![SP4207_4(Barbados)](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/92573053-bad6-463b-8cc9-3d258cacffd1)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
