### ISSUE TITLE
Add Kombo A Janea class, Cameroon navy

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#374]
### DB Selector

DB3K

### Baseline

1829

### Hypothetical

No

### Name

Landing Craft (LCU), L0202, Kombo A Janea

### Class

Kombo A Janea (Yunnan, Type 067)

### Country

Cameroon

### Service

Navy

### In Commission

2002 - Present

### Length (m)

28.6

### Beam (m)

5.4

### Draft (m)

1.5

### Standard Displacement (t)

Not found

### Full Displacement (t)

137

### Complement

10 + 12 (src3)

### Primary Propulsion Type

Diesel

### Propulsion

Unknown type, 2 shafts

### Flank Speed (kt)

12 (src1)

### Range (nm) at Speed (kt)

500 @ 10

### Sensors

Surface Search radar Fuji I-band (src1), or
Navigation radar Anritsu (src2)

### Mounts

1x twin 14.5mm/93 MG

### Comments

Cargo 45t, 1 tank or 2 light vehicles (src2)
No Cameroon image found on class

### Sources

Src3 is CHN version.
1: JFS 2015/2016;
2: https://navypedia.org/ships/cameroon/came_ls_kombo_a_janea.htm;
3: https://en.wikipedia.org/wiki/Type_067_utility_landing_craft
![1](https://user-images.githubusercontent.com/99532490/155329454-3f6e8944-57a5-4cf7-9a9a-8ead1957f7e8.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
