### ISSUE TITLE
Add Nicaragua Navy Soberania I (SP4207)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3740]
### DB Selector

DB3K

### DBID to Copy

Ship #3578

### Hypothetical

No

### Name

Soberania I (Stan Patrol 4209), 409

### Country

Nicagarua

### Service

Navy

### In Commission

2019 - present (?ex-Jamaica)

### Number in Service

2

### Sensors

2x Navigation RADAR (?I & E/F)

### Mounts

2x small calibre MG (port/SB)
2x 14.5mm KPVT MG (port/SB)
1(2)x 23mm Gun ADS-N 23mm  (ZSU-23-2 based) at aft

### Other Changes

1x crane for small RHIB
1x slipway for fast RHIB

### Sources

https://www.webinfomil.com/2019/07/nicaragua-fortalece-su-fuerza-naval-con.html
https://en.wikipedia.org/wiki/Damen_Stan_Patrol_4207
https://www.infodefensa.com/texto-diario/mostrar/3128256/nicaragua-presenta-nuevas-patrulleras-damen-stan-patrol-4207
https://navyrecognition.com/index.php/news/defence-news/2019/august/7367-nicaraguan-navy-commissions-two-more-damen-stan-patrol-4207-vessels.html
https://www.youtube.com/watch?v=-kh_G_5UG7Y
https://www.infodefensa.com/texto-diario/mostrar/3130498/nicaragua-incorpora-nuevas-damen-stan-patrol-4207
https://www.defensa.com/centro-america/asi-son-patrulleras-soberania-ejercito-nicaragua
https://www.arsenal-bg.com/c/air-defence-system-ads-30/23x152-mm-ads-n-25
https://www.facebook.com/el19digital/posts/10157512182258724

![1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/adb4e4f1-4136-465c-9a21-4e105c3a2996)
![2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/a4980d32-f747-45f4-9eff-a34e39409bf9)
![4](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/cf032a5e-1f12-4830-8202-d75293f187c7)
![5](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/3e64dfd4-f210-4982-8fdc-78a04a05b51b)
![6](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/cdca757d-cd5f-4af6-b105-759dced10d8e)
![7](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/482aae20-7084-4ace-ae33-dec1f0ad0bca)

**Comment by FrangibleCover** [comment]
The ZU-23-2 is on the front in those photos?

**Comment by Parel803** [comment]
You are absolutly right, my bad. on the front, sorry

**Comment by Jkryos** [comment]
Added DB3K 506.
