### ISSUE TITLE
Add JDAM-ER Loadout to Ukrainian SU-27s

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3744]
### DB Selector

DB3K

### User(s)

Aircraft 353

### Weapons Carried

2 Alamo-A
2 JDAM-ER
2 Archers

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Likely the same rules as Mig-29. Replaces sturdier wired pylons under the wings.

### Sources

https://www.thedrive.com/the-war-zone/ukraines-su-27s-are-launching-jdam-er-winged-bombs-too
https://en.defence-ua.com/weapon_and_tech/adjusting_jdam_er_to_fit_onto_ukrainian_su_27_turned_out_more_difficult_than_expected-7733.html

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
