### ISSUE TITLE
AGM-158B-2 JASSM-ER (Extreme Range) name change request from AGM158D JASSM-XR

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#3746]
### DB Selector

DB3K

### Affected DBID(s)

3906

### Summary of Changes

AGM-158D JASSM-XR is now called AGM-158B-2 JASSM-ER.

### Sources

https://www.janes.com/defence-news/news-detail/lockheed-martin-set-to-commence-jassm-agm-158b-2-lrip

**Comment by PygmalionOfCyprus** [comment]
Aw, that's less fun. Handled 503.

**Comment by tbrandon517** [comment]
> Aw, that's less fun. Handled 503.

It really is
