### ISSUE TITLE
Sea Control Ship

### ISSUE THREAD

**Issue by Loki1701e** [PygmalionOfCyprus/cmo-db-requests#3747]
### DB Selector

Both

### Hypothetical

Yes

### Name

Sea Control Ship

### Class

Sea Control Ship

### Country

United States

### Service

Navy

### In Commission

never but probably would be in service

### Length (m)

190 m

### Beam (m)

24 m

### Draft (m)

24 m

### Standard Displacement (t)

9,773 tons

### Full Displacement (t)

13,736 tons

### Complement

700

### Primary Propulsion Type

Gas Turbine

### Propulsion

2 × General Electric LM2500+ gas turbines  one shaft, 45,000 shp

### Fuel Capacity (kg)

861,825.503 kg of jp5

### Flank Speed (kt)

26

### Range (nm) at Speed (kt)

unknown but similar to the ships based off sea control ship

### Sensors

unknown
but most likely given contemporary sensors of the era a flattop would have
sps49
sps48
slq25 nixie
slq-32 
LAMPS system for helicopters

### Mounts

mk36 srboc
2 mk15 phalanx ciws

### Aircraft & Docking Facilities

166 m × 32 m flight deck
1 elevator
2 heli landing spots 
stovl capability 
2 aircraft lifts
space for up to 25 fixed wing(harriers) and rotary wing aircraft. 

### Comms/Datalinks

similar com and datalinks to flattops of the ara plus lamps datalink

### Ship Codes

Nuclear Shock Resistant, Degaussed Steel Hull, Prairie Masker

### Comments

HTMS Chajru Naruebet and spanish aircraft carrier Príncipe de Asturias are based off the sea control ship but with a ski ramp.

### Sources

https://en.wikipedia.org/wiki/Sea_Control_Ship
https://en.wikipedia.org/wiki/HTMS_Chakri_Naruebet
https://en.wikipedia.org/wiki/Spanish_aircraft_carrier_Pr%C3%ADncipe_de_Asturias

**Comment by Loki1701e** [comment]
proposed ship to fill the gap of needed escorts in the 1970s by elmo zumwalt. essentially a light helicopter destroyer

**Comment by tbrandon517** [comment]
A version of the SCS in the CWDB. It might have ski jump.

https://cmano-db.com/cw/ship/2588/

**Comment by Loki1701e** [comment]
need to start looking at these more i seem to miss them
