### ISSUE TITLE
MiG-23Us for... Everyone?

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3750]
### DB Selector

DB3K

### DBID to Copy

DB3k Issue #1633

### Hypothetical

No

### Name

MiG-23UB

### Country

-

### Service

Air Force

### In Commission

-

### Other Changes

For:
- [x] Algeria (1979-2004)
- [x] Angola (1984-current)
- [x] Belarus (1992-2001)
- [x] Bulgaria (1978-2004)
- [x] Cuba (1979)
- [x] Czech Republic (1994-1998)
- [x] Egypt (1975)
- [x] Ethiopia (1978)
- [x] German Democratic Republic (1979-1990)
- [x] Hungary (1980-1996)
- [x] India (1982-current)
- [x] Kazakhstan (1992-current)
- [x] Libya (1975-who the hell knows what's happening in Libya)
- [x] North Korea (1985-current)
- [x] Poland (1979-1999)
- [x] Romania (1979-2003)
- [x] Russia (1992-1997)
- [x] Soviet Union (1971-1991)
- [x] Sri Lanka (2007-2019) 1x
- [ ] Sudan (?)
- [x] Syria (1976-current)
- [x] Turkmenistan (1992-2000)
- [x] Ukraine (1992-2001)

### Sources

https://en.wikipedia.org/wiki/List_of_MiG-23_operators
https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-23#Operators
WAR OF INTERVENTION IN ANGOLA, VOLUME 3: ANGOLAN AND CUBAN AIR FORCES, 1975-1985 by Fontanellaz, Cooper & Matos p.61
DB (Some 23U acquisitions assumed at the date of intro of other MiG-23s)

**Comment by Jkryos** [comment]
Added DB3K 510.
