### ISSUE TITLE
MiG-27M for Sri Lanka

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3751]
### DB Selector

DB3K

### DBID to Copy

DB3k Aircraft 2258

### Hypothetical

No

### Name

MiG-27M Flogger J

### Country

Sri Lanka

### Service

Air Force

### In Commission

2000-2019

### Number in Service

few

### Loadout Options

Remove all nuclear weapons

### Sources

https://en.wikipedia.org/wiki/Mikoyan_MiG-27#Sri_Lanka
https://en.wikipedia.org/wiki/No._12_Squadron_SLAF

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
