### ISSUE TITLE
China, Type 054B Frigate

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3756]
### DB Selector

DB3K

### Hypothetical

No

### Name

Type 054B 

### In Commission

2025

### Length (m)

147

### Beam (m)

18

### Draft (m)

4

### Standard Displacement (t)

5000

### Full Displacement (t)

6000

### Complement

same as type 054a

### Primary Propulsion Type

Diesel

### Propulsion

same as 054a

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

5000nm at 18kt

### Sensors

1x 2-Phased rotate AESA (2020s tech)
More advanced OECM, DECM, ELINT, VDS and TASS (2020s tech)

others remain same as type 054a

### Mounts

Change from type 054a:

1x 100mm H/PJ-87 Gun (same on type 052C)
1x 30mm H/PJ-14 [Type 1130] (front)
1x HQ-10 FL-3000N, 24x round (rear)
2x YJ-12 SSM Quad launcher
replace the HQ-16A in the VLS with **HQ-16FE**

Others remain same

### Aircraft & Docking Facilities

Change the hangar and pad to [Medium arcraft 12.1-18m] to accommodate Z-20F ASW heli.

### Comms/Datalinks

Increase the sa-17/sa-n-12 weapon link channel from current 8 on type 054a to more, maybe [16 channel], since this ship has an AESA radar to provide fire control.

### Sources

https://en.wikipedia.org/wiki/Type_054B_frigate
https://www.navalnews.com/naval-news/2023/08/first-new-type-054b-frigate-for-chinese-navy-launched-in-shanghai/
https://www.thedrive.com/the-war-zone/this-is-chinas-new-type-054b-frigate-could-become-backbone-of-navy

**Comment by LuigiP57** [comment]
Unreasonable for a brand new warship without new weapon
![Uploading image.png…]()

**Comment by Jkryos** [comment]
Updated DB3K 504. Very little information exists on what is replacing Top Plate so I have opted to leave Top Plate on until we have a few more details.

**Comment by LuigiP57** [comment]
> Updated DB3K 504. Very little information exists on what is replacing Top Plate so I have opted to leave Top Plate on until we have a few more details.

Definately A rotate phased radar. Generic AESA on S.Korea FFX-III will be suitable.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/c2e915fb-8524-4ad2-806b-1c95def5f9ae)

**Comment by LuigiP57** [comment]
> Updated DB3K 504. Very little information exists on what is replacing Top Plate so I have opted to leave Top Plate on until we have a few more details.

Also, If there won't be HQ-16FE in the next version database, please update its SAM to the newest HQ-16C.
