### ISSUE TITLE
Tomahawk Range Review

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3757]
### DB Selector

DB3K

### Affected DBID(s)

Weapons # 230, 231, 378, 379, 380, 382, 744, 808, 809, 811, 812, 1131, 3331

### Summary of Changes

There was some tweaking of the Tomahawk missile ranges a few DB's back. Since then, while most ranges make sense based on sources available, I have noticed the TLAM-Ds seem to have a generally much too great range, whereas they once had a range shorter than TLAM-C they now generally can match TLAM-N for range which is incorrect based on source materials. Comparative list below.

Weapon # 44 BGM-109G Tomahawk GLCM - Max Range 1350nm
Weapon # 3727 BGM-109J Tomahawk Blk Va MST - Max Range 899nm
Weapon # 228 RGM-109A Tomahawk TLAM-N - Max Range 1350nm
Weapon # 229 RGM-109B TASM - Max Range 217nm
Weapon # 230 RGM-109C Tomahawk Blk II TLAM-C - Max Range 900nm (seems switched with Blk III)
Weapon # 1131 RGM-109C Tomahawk Blk III TLAM-C - Max Range 700nm (seems switched with Blk II)
Weapon # 231 RGM-109D Tomahawk Blk II TLAM-D - Max Range 1350nm (Seems to long)
Weapon # 3331 RGM-109D Tomahawk Blk II TLAM-D [Kit-2 Carbon Filaments] - Max Range 460nm (seems about right for Blk II TLAM-D)
Weapon # 744 RGM-109D Tomahawk Blk III TLAM-D - Max Range 700nm (seems right for Blk III TLAM-D)
Weapon # 586 RGM-109E Tomahawk Blk IV TACTOM - Max Range 864nm
Weapon # 434 RGM-109H Tomahawk Blk IV TTPV - Max Range 864nm
Weapon # 2941 RGM-109I Tomahawk Blk IV MMT [Multi-Mission] - Max Range 864nm
Weapon # 4070 RGM-109J Tomahawk Blk Va MST - Max Range - 899nm
Weapon # 818 UGM-109A Tomahawk TLAM-N [TT] - Max Range 1350nm
Weapon # 376 UGM-109A Tomahawk TLAM-N [VLA] - Max Range 1350nm
Weapon # 814 UGM-109B Tomahawk TASM [TT] - Max Range 217 nm
Weapon # 373 UGM-109B Tomahawk TASM [VLS] - Max Range 217nm
Weapon # 812 UGM-109C Tomahawk Blk II TLAM-C [TT] - Max Range 1350nm (Matches TLAM-N not other TLAM-Cs)
Weapon # 380 UGM-109C Tomahawk Blk II TLAM-C [VLS] - Max Range 1350nm (Matches TLAM-N not other TLAM-Cs)
Weapon # 811 UGM-109C Tomahawk Blk III TLAM-C [TT] - Max Range 900nm (Matches expected TLAM-C)
Weapon # 382 UGM-109C Tomahawk Blk III TLAM-C [VLS] - Max Range 700nm (Matches expected TLAM-D)
Weapon # 809 UGM-109D Tomahawk Blk II TLAM-D [TT] - Max Range 1350nm (Matches TLAM-N )
Weapon # 379 UGM-109D Tomahawk Blk II TLAM-D [VLS] - Max Range 1350nm (Matches TLAM-N )
Weapon # 808 UGM-109D Tomahawk Blk III TLAM-D [TT] - Max Range 700nm (Matches expected TLAM-D)
Weapon # 378 UGM-109D Tomahawk Blk III TLAM-D [VLS] - Max Range 700nm (Matches expected TLAM-D)
Weapon # 377 UGM-109E Tomahawk Blk IV TACTOM [VLS] - Max Range 864nm
Weapon # 810 UGM-109E Tomahawk Blk IV TACTOM [TT] - Max Range 864nm
Weapon # 1180 UGM-109H Tomahawk Blk IV TTPV [VLS] - Max Range 864nm
Weapon # 1165 UGM-109H Tomahawk Blk IV TTPV [TT] - Max Range 864nm
Weapon # 2942 UGM-109I Tomahawk Blk IV MMT [Multi-Mission] [TT] - Max Range 864nm
Weapon # 2943 UGM-109I Tomahawk Blk IV MMT [Multi-Mission] [VLS] - Max Range 864nm
Weapon # 4033 UGM-109J Tomahawk Blk V TACTOM - Max Range 899nm
Weapon # 4071 UGM-109J Tomahawk Blk Va MST - Max Range 899nm

### Sources

https://en.wikipedia.org/wiki/Tomahawk_(missile)
https://missilethreat.csis.org/missile/tomahawk/
https://www.seaforces.org/wpnsys/SURFACE/BGM-109-Tomahawk.htm

**Comment by PygmalionOfCyprus** [comment]
Can you clarify exactly what you want changed to what here?

**Comment by tbrandon517** [comment]
> Can you clarify exactly what you want changed to what here?

Will provide clarification within the next day.

**Comment by tbrandon517** [comment]
> Can you clarify exactly what you want changed to what here?

Hopefully this will be clearer. Not sure what DB version the changes occurred on but ranges for TLAM blocks are off from previously.

From the sources out there the TLAM-Ds should all be shorter ranged than the TLAM-Cs and the Block IIIs should outrange the Block IIs. 

Currently 3 of the 4 Block II TLAM-D models can fly father than the TLAM-C's and match the range of TLAM-N. The Block III models all look right.

Currently 3 of the 3 Block II TLAM-C models can fly father than the Block III TLAM-C's with 2 matching the range of TLAM-N. While 2 of the 3 Block III TLAM-C models have ranges seemly more fit for the Block IIs.


TLAM-N models used as Baseline for Comparison
Weapon # 44 BGM-109G Tomahawk GLCM - Max Range 1350nm 
Weapon # 228 RGM-109A Tomahawk TLAM-N - Max Range 1350nm 
Weapon # 376 UGM-109A Tomahawk TLAM-N [VLA] - Max Range 1350nm 
Weapon # 818 UGM-109A Tomahawk TLAM-N [TT] - Max Range 1350nm


TLAM-C Block II Models With change notes
Weapon # 230 RGM-109C Tomahawk Blk II TLAM-C - Max Range 900nm (seems switched with Blk III model, should be 700nm)
Weapon # 380 UGM-109C Tomahawk Blk II TLAM-C [VLS] - Max Range 1350nm (Matches TLAM-N, should be 700nm)
Weapon # 812 UGM-109C Tomahawk Blk II TLAM-C [TT] - Max Range 1350nm (Matches TLAM-N, should be 700nm)


TLAM-C Block III Models With change notes
Weapon # 382 UGM-109C Tomahawk Blk III TLAM-C [VLS] - Max Range 700nm (Should be 900nm similar to Weapon # 811)
Weapon # 811 UGM-109C Tomahawk Blk III TLAM-C [TT] - Max Range 900nm (Matches expected TLAM-C, no change)
Weapon # 1131 RGM-109C Tomahawk Blk III TLAM-C - Max Range 700nm (seems switched with Blk II model, should be (900nm)


TLAM-D Block II Models With change notes
Weapon # 231 RGM-109D Tomahawk Blk II TLAM-D - Max Range 1350nm (Seems to long, should be 460nm)
Weapon # 379 UGM-109D Tomahawk Blk II TLAM-D [VLS] - Max Range 1350nm (Matches TLAM-N, should be 460nm)
Weapon # 809 UGM-109D Tomahawk Blk II TLAM-D [TT] - Max Range 1350nm (Matches TLAM-N, should be 460nm)
Weapon # 3331 RGM-109D Tomahawk Blk II TLAM-D [Kit-2 Carbon Filaments] - Max Range 460nm (seems about right for Blk II TLAM-D, no change recommended)


TLAM-D Block III Models, These alll look right, no changes
Weapon # 744 RGM-109D Tomahawk Blk III TLAM-D - Max Range 700nm (seems right for Blk III TLAM-D)
Weapon # 808 UGM-109D Tomahawk Blk III TLAM-D [TT] - Max Range 700nm (Matches expected TLAM-D)
Weapon # 378 UGM-109D Tomahawk Blk III TLAM-D [VLS] - Max Range 700nm (Matches expected TLAM-D)



TASM Models for reference, all of these look correct.
Weapon # 229 RGM-109B TASM - Max Range 217nm - This is okay
Weapon # 373 UGM-109B Tomahawk TASM [VLS] - Max Range 217nm - This is okay
Weapon # 814 UGM-109B Tomahawk TASM [TT] - Max Range 217 nm - This is okay

Block IV Models for reference, all of these look correct.
Weapon # 377 UGM-109E Tomahawk Blk IV TACTOM [VLS] - Max Range 864nm
Weapon # 434 RGM-109H Tomahawk Blk IV TTPV - Max Range 864nm
Weapon # 586 RGM-109E Tomahawk Blk IV TACTOM - Max Range 864nm
Weapon # 810 UGM-109E Tomahawk Blk IV TACTOM [TT] - Max Range 864nm
Weapon # 2941 RGM-109I Tomahawk Blk IV MMT [Multi-Mission] - Max Range 864nm
Weapon # 1165 UGM-109H Tomahawk Blk IV TTPV [TT] - Max Range 864nm
Weapon # 1180 UGM-109H Tomahawk Blk IV TTPV [VLS] - Max Range 864nm
Weapon # 2942 UGM-109I Tomahawk Blk IV MMT [Multi-Mission] [TT] - Max Range 864nm
Weapon # 2943 UGM-109I Tomahawk Blk IV MMT [Multi-Mission] [VLS] - Max Range 864nm

Block V Models for reference, all of these look correct.
Weapon # 3727 BGM-109J Tomahawk Blk Va MST - Max Range 899nm
Weapon # 4033 UGM-109J Tomahawk Blk V TACTOM - Max Range 899nm
Weapon # 4070 RGM-109J Tomahawk Blk Va MST - Max Range - 899nm
Weapon # 4071 UGM-109J Tomahawk Blk Va MST - Max Range 899nm

**Comment by tbrandon517** [comment]
Simplified form.

TLAM-C Block II Model Changes: Update the range for weapon # 230, 380, and 812 to 700nm.

TLAM-C Block III Model Changes: Update the range for weapon # 382 and 1131 to 900nm to match weapon # 811.

TLAM-D Block II Model Changes: Update the range for weapon # 231, 379, and 809 to 460 nm to match weapon # 3331.

This should reconcile and align TLAM ranges.

**Comment by PygmalionOfCyprus** [comment]
Went through and brought the TLAM ranges in line w/ CSIS ranges (and each other, excepting reduced ranges for sub-launched where applicable).

**Comment by tbrandon517** [comment]
> Went through and brought the TLAM ranges in line w/ CSIS ranges (and each other, excepting reduced ranges for sub-launched where applicable).

Thanks! I'm sure I'm not the only one who's was scratching their head about some of those TLAM-Ds. 
Thanks for all the awesome work you all do!
