### ISSUE TITLE
Add person in water (alive & dead)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3759]
### DB Selector

DB3K

### Baseline

#3725, 1.8m life raft single person ?

### Hypothetical

No

### Name

Person in Water (Alive & Dead)

### Class

Unspecified

### Country

Unknown

### Service

None

### Length (m)

0.15

### Beam (m)

0.15

### Draft (m)

1.8

### Standard Displacement (t)

0

### Complement

1

### Primary Propulsion Type

Sail

### Propulsion

None

### Flank Speed (kt)

Drift

### Range (nm) at Speed (kt)

Drift

### Sensors

Alive Mk1

### Mounts

None

### Comms/Datalinks

None

### Comments

Not sure if this is oké for the game but it is fact of live at sea. Drop if not appropriate.
If I missed it in the DB already, I do apologize, couldn't find it.
Propulsion: none
Maybe a dead drifting person little different on dimensions.
Alive person Mk1, no comms

### Sources

None

**Comment by FrangibleCover** [comment]
There's a "downed pilot" unit which is often used for this, but I think they have a SARBE, so a generic person in the water could be useful. I think a corpse is a bit macabre, and the way that I'd do it in Lua it's probably better to shunt the person in the water from side Alive to side Dead anyway (preserving the GUID and position).

**Comment by GIGANTO-pithecus** [comment]
Schrodinger's life raft? kind of like Schrodinger's air defense - both best and at same time operators on 24/7 smoke breaks

**Comment by Parel803** [comment]
Thanks for the side option. I like to use for Coastguard like scen.

**Comment by Parel803** [comment]
Maybe it is wise to replace person for a Man-In-Water dummy? Sort of in-between, just thinking out load.

**Comment by PygmalionOfCyprus** [comment]
I have no problem adding a unit to represent a person in the water. This is a highly complex, realistic simulation widely used by defense clients as well as commercial users; I trust our audience is fairly mature (though the behavior of some people on the forums may challenge that assumption, hehe). I don't think anyone playing CMO will be somehow shocked/traumatized by the idea that sometimes there are dead people in the water alongside all the ships they've just blown up with anti-ship missiles.

**Comment by Jkryos** [comment]
Added DB3K 506.
