### ISSUE TITLE
Brazilian AH-2 Mi-35M Out of service by Dec 2022

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#376]
### DB Selector

DB3K

### Affected DBID(s)

Brazil AH-2 Sabre Mi-35M.

### Summary of Changes

Brazil is apparently retiring its AH-2 Mi-35M which have only been in service since 2008. It will be withdrawn by December 2022. 
Spares and maintenance issues. Not sure of any replacement or if they will be sold to someone else?
*Will update Db ID in due course. 

### Sources

https://airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/february/8231-brazilian-air-force-to-decommission-its-mi-35m-ah-2-sabre-helicopters.html

**Comment by PygmalionOfCyprus** [comment]
Updated for 493.
