### ISSUE TITLE
Japan UH-60J Probe Refueling

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#3760]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 6186, 6187

### Summary of Changes

They should use Probe Refueling instead of Bom Refueling

### Sources

https://www.mod.go.jp/asdf/arw/syoukai/soubi/UH60J/UH60J.html

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
