### ISSUE TITLE
 Add KH-50/X-50 Stealth Cruise Missile (Confirmed Usage August 2023) stealthier/smaller KH-101 derivative

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#3761]
### DB Selector

DB3K

### DBID to Copy

Weapon 16

### Hypothetical

No

### Name

KH-50 (X-50)

### Country

Russia

### Service

Air Force

### In Commission

2023-present

### Number in Service

unknown, presumably few, very recent

### Sensors

1x Otblesk (identical to TERCOM/DSMAC mapping/navigation system)
1x Sproot (EO seeker) db 7192

### Loadout Options
TU-160M (2021) - 12 KH-50 total
TU-22M-3-M (2021) - 8 total (or 6 in revolving bay) short range
TU-95MS (2011) - 14 total (or 6 in revolving bay) short range
### Other Changes

Summary of Changes:

**-6m in length, weighs 1600kg (smaller than KH-101)
-HE 450kg penetrator warhead
-Stealthier than current KH-101, similar to Storm Shadow missiles. -35dBsm for A-D band and -45 dBsm for E-M band
-cruise speed 377 kts, max speed 512 kts (700kph - 950kph)
-810 nmi range (1500km)

**_### confirmed in two separate attacks recently in Zaporizhzhia and also Chernihiv regions._**

![kh-50](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/403a261b-6966-4ab7-9748-c08f0f67cc1a)
https://twitter.com/ADFCLEB/status/1692918485179920424?ref_src=twsrc%5Etfw

### Sources

https://www.defensemirror.com/news/34855/Russia_Deploys__Top_Secret__KH_50_Cruise_Missile_in_Attack_on_Ukrainian_Weapons_Depot
https://sofrep.com/news/is-the-russian-kh-50-missile-really-a-game-changer-in-cruise-missile-technology/
https://www.eurasiantimes.com/russias-deadliest-missile-kh-50-gets-operational-can-penetrate/
https://www.globalsecurity.org/military/world/russia/kh-50.htm
https://www.youtube.com/watch?v=3NkWB9OhN7Y
https://www.youtube.com/watch?v=YTNn8aVT9iQ
https://twitter.com/ADFCLEB/status/1692918485179920424?ref_src=twsrc%5Etfw

**Comment by GIGANTO-pithecus** [comment]
(Hypothetical long range bomber loadouts)
TU-160M (2021) - 12 KH-50 total
TU-22M-3-M (2021) - 8 total (or 6 in revolving bay)
TU-95MS (2011) - 14 total (or 6 in revolving bay)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
