### ISSUE TITLE
VLS Barge - Towed

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3762]
### DB Selector

DB3K

### Baseline

3218

### Hypothetical

Yes

### Name

VLS Barge (Towed) 

### Class

USV

### Country

USA

### Service

Navy

### In Commission

2020+

### Length (m)

100

### Beam (m)

17.5

### Draft (m)

4.1

### Standard Displacement (t)

1800

### Full Displacement (t)

2000

### Empty Displacement (t)

Similar to 3218

### Complement

0

### Max Sea State

Similar to 3218

### Primary Propulsion Type

Sail

### Propulsion

None

### Fuel Capacity (kg)

0

### Flank Speed (kt)

Same as the ship towing it

### Range (nm) at Speed (kt)

Same as the ship towing it

### Sensors

None. 

### Mounts

Multiple VLS Cells -
~x64 MK41 VLS cells, with 2020s era missiles. 

### Aircraft & Docking Facilities

None

### Comms/Datalinks

Link 16 and CEC will be necessary to allow the barge's missiles to fire using nearby vessel's sensors.

### Comments

I'm not sure if there's an option for towed vessels in CMO currently, so it may require the creation of a new class. There may also have to be a new option what type of ship can tow another - something similar to, and bigger than, an FFG or DDG could most likely tow a missile barge (although smaller specialised ships like tug boats may also be able to). 

Not sure what Ship Codes it could be given, but it'd be unlikely to be particularly damage resistant.

""Some kind of barge that has missile tubes,” is how Eric Wertheim, author of [Combat Fleets of the World], characterized it.

Missile barges could motor into a battle zone under their own power. Or auxiliary vessels could tow them. Once on station, they’d plug into the manned-unmanned sensor-and-missile network the fleet is developing.

Other vessels would spot targets for the barge. A human operator on a nearby ship or at some base on land then would order the barge to open fire. With the press of a button, scores of missiles could arc toward an enemy fleet. Cheaply."

### Sources

https://www.google.com/amp/s/www.forbes.com/sites/davidaxe/2021/05/03/the-us-navy-needs-missile-launchers-a-cheap-robot-could-be-just-the-thing/amp/

https://www.eaglespeak.us/2017/04/lets-talk-arsenal-ships-and-missile.html?m=1

**Comment by TempestII** [comment]
![2lcqypi](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99649251/689ba540-4061-4589-9089-18b6152c8436)

**Comment by tbrandon517** [comment]
I know ship towing was one of the options on the old feature poll. I did submit it on the new thread but it's not on the poll ATM.

**Comment by Jkryos** [comment]
Added DB3K 509
