### ISSUE TITLE
VLS Barge (Powered) 

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#3763]
### DB Selector

DB3K

### Baseline

3218

### Hypothetical

Yes

### Name

VLS Barge (Powered) 

### Class

USV

### Country

USA

### Service

US Navy

### In Commission

2020+

### Length (m)

100

### Beam (m)

17.5

### Draft (m)

4.1

### Standard Displacement (t)

1800

### Full Displacement (t)

2000

### Empty Displacement (t)

Similar to 3218

### Complement

0

### Max Sea State

Similar to 3218

### Primary Propulsion Type

Gas Turbine

### Propulsion

Similar to 3218

### Fuel Capacity (kg)

Similar to 3218

### Flank Speed (kt)

Similar to 3218

### Range (nm) at Speed (kt)

Similar to 3218

### Sensors

Similar to 3218, minus the towed array and, to keep costs down, probably no radars (except a Generic Navigation Radar).

### Mounts

Multiple VLS Cells -
~x64 MK41 VLS cells, with 2020s era missiles.

### Aircraft & Docking Facilities

None

### Comms/Datalinks

Similar to 3218. Link 16 and CEC will be necessary to allow the barge's missiles to fire using nearby vessel's sensors. 

### Comments

This version of the vessel would be able to move under its own propulsion system, but would likely be towed over longer distances as its top speed and range would unlikely to match that of FFGs and DDGs. 

I'm not sure if there's an option for towed vessels in CMO currently, so it may require the creation of a new class. There may also have to be a new option what type of ship can tow another - something similar to, and bigger than, an FFG or DDG could most likely tow a missile barge (although smaller specialised ships like tug boats may also be able to).

Not sure what Ship Codes it could be given, but it'd be unlikely to be particularly damage resistant.

""Some kind of barge that has missile tubes,” is how Eric Wertheim, author of [Combat Fleets of the World], characterized it.

Missile barges could motor into a battle zone under their own power. Or auxiliary vessels could tow them. Once on station, they’d plug into the manned-unmanned sensor-and-missile network the fleet is developing.

Other vessels would spot targets for the barge. A human operator on a nearby ship or at some base on land then would order the barge to open fire. With the press of a button, scores of missiles could arc toward an enemy fleet. Cheaply."

### Sources

https://www.google.com/amp/s/www.forbes.com/sites/davidaxe/2021/05/03/the-us-navy-needs-missile-launchers-a-cheap-robot-could-be-just-the-thing/amp/

https://www.eaglespeak.us/2017/04/lets-talk-arsenal-ships-and-missile.html?m=1

https://www.snafu-solomon.com/2012/08/blast-from-past-towed-missile-barges.html?m=1

**Comment by Jkryos** [comment]
Added DB3K 509.
