### ISSUE TITLE
TSR-2 Loadout Data Errors

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3764]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 2239

### Summary of Changes

The TSR.2 loadouts in the database are split between standard and long-range variants. In the actual game they work fine, with the additional fuel in the drop tanks adding additional range, but in the database they all quote a range of 900nmi regardless of fuel quantity or drag. This hinders mission planning with the aircraft.

### Sources

DB

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
