### ISSUE TITLE
Aircraft Yak-140 Iran 2023 Numbers?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3767]
### DB Selector

DB3K

### DBID to Copy

Copy Aircraft 3953 Yak-130  Algeria.

### Hypothetical

No

### Name

Yak-130 Mitten Iran AF 2023

### Country

Iran

### Service

Air Force

### In Commission

2023

### Number in Service

2+ TBC 

### Sensors

RWR. 

### Mounts

Chaff Flare dispensers probably.

### Loadout 
Straight copy.

Weapons / Loadouts:
 - 450 liter Drop Tank - Drop Tank. 
 - RBK-500-BetAB CB [12 x BetAB-20 Anti-Runway Penetrator Bomblets] - Bomb. Land Max: 1.9 km. 
 - AA-11 Archer [R-73] - (1986) Guided Weapon. Air Max: 18.5 km. 
 - 23mm Gsh-23L Burst [40 rnds] - (Aircraft) Gun. Air Max: 1.5 km. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - FAB-100M-62 GPB - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - FAB-250M-54 GPB - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - FAB-250M-62 GPB - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - FAB-500M-54 GPB - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - FAB-500M-62 GPB - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - KAB-500Kr TV/EO - (1984) Guided Weapon. Surface Max: 9 km. Land Max: 9 km. 
 - OFAB-100-120 Frag - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - OFAB-250-270 Frag - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - RBK-250-PTAB CB [30 x PTAB-2.5 Anti-Tank Bomblets] - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - RBK-500-PTAB [268 x PTAB-1M Anti-Tank Bomblets] - Bomb. Surface Max: 1.9 km. Land Max: 1.9 km. 
 - S-13B 122mm Rocket [Penetrator] - (1984) Rocket. Surface Max: 3.7 km. Land Max: 3.7 km. 
 - S-24B 240mm Rocket - (V-24A Fuze) Rocket. Surface Max: 3.7 km. Land Max: 3.7 km. 
 - S-8KO 80mm Rocket [HEAT] - (1985) Rocket. Surface Max: 3.7 km. Land Max: 3.7 km.

### Other Changes

No.seems standard copy of any existing entry Algerian version?

### Sources

https://twitter.com/GuyPlopsky/status/1697928648995828170?t=jyT2NdnHlrDN6hS5Jk0YkQ&s=19

https://twitter.com/AmirIGM/status/1697913758771765250?t=y_HjJ45yQ9XJXgMao4KbKw&s=19

Photo and video apparently from Isfahan and two serials at least delvierred so far.  Weapons Pylons are visible but livery is distinctly high visibility for training.

**Comment by PygmalionOfCyprus** [comment]
I think this was added back in DB 502. Aircraft 6899.
