### ISSUE TITLE
Schrödinger's Pantsir (Quantum SHORAD anomaly)

### ISSUE THREAD

**Issue by GIGANTO-pithecus** [PygmalionOfCyprus/cmo-db-requests#3768]
### DB Selector

DB3K

### Hypothetical

Quantum Mechanically Determined 

### Name

Pantsir-Stronk

### Sensor Generation

Both 2012 and 1970 simultaneously

### Range (nm)

40

### Sensor Capabilities

Air Search

### Search/Track Frequencies

A Band (30-250 MHz) [Old P Band (HF)] 100-300 cm

### Comments

Is both BEST SHORAD in existence, yet cannot intercept rockets, low flying drones or cruise missiles at the same time. BEST 21ST CENTURY SHORAD with groundbreaking tech, but uses a late 1970's pulse doppler fire control radar. SIMULTANEOUSLY :)

### Sources

none needed - Schrodinger's Pantsir has proven itself to be a quantum perfection

**Comment by GIGANTO-pithecus** [comment]
In all seriousness, as an individual with an extensive technical background and more hours in this game than in real life (ok, I'm joking (or am I) ). just want to interject some humor despite the serious environment this simulator exhibits (for good reason - it's a phenomenal game) - one which I wish to continue participating in and adding to its development here on github. 

A laugh is good once in a while :)

**Comment by PygmalionOfCyprus** [comment]
Until you check it this ticket is both open and closed. 😝
