### ISSUE TITLE
Change NLD Reaper aremd

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3769]
### DB Selector

DB3K

### Affected DBID(s)

#5791

### Summary of Changes

GBU-12 guided bombs instead of GBU-49/B

Add SIGINT/ESM Pod

### Sources

Not sure if the previous is been intended and so now hypothetical making this a new version. Or this is just the change to 5791.

https://breakingdefense.com/2023/08/netherlands-to-double-mq-9a-order-to-eight-aircraft/?_hsmi=271329468&_hsenc=p2ANqtz--uq2kziR8QbHvSZGIjNlIK968th9ygmtu8401nr_FfSSI04xsSq95FAdO9iBGRh9WNIeoV3bZbfRTILK2y3LuZMB1rug
https://www.defensie.nl/actueel/nieuws/2023/01/18/nieuwe-sensoren-voor-onbemande-reaper-toestellen
https://www.shephardmedia.com/news/air-warfare/dutch-double-down-by-adding-another-four-more-reapers-to-those-in-service/
https://www.defensenews.com/global/europe/2023/08/29/netherlands-doubles-order-of-mq-9-reaper-drones-plans-to-arm-them/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
