### ISSUE TITLE
Add Ariel Refuelling to RAF Atlas

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#3774]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft/Fixed Wing #.1420 Atlas C.1 [A.400M] Grizzly, United Kingdom, 2016

### Summary of Changes

Add loadout #.17340 Air Refuelling Tanker, 2x Buddy Stores

While the UK doesn't use this feature the aircraft is still capable of doing it. [1]

### Sources

[1] https://www.airtattoo.com/the-airshow/aircraft-and-pilots/aircraft-updates-news/aircraft/airbus-atlas-c1-uk/#:~:text=In%20addition%20to%20the%20transport,aircraft%20or%20for%20medical%20evacuation.

**Comment by FrangibleCover** [comment]
The UK doesn't use the feature so don't add it for the UK A400M, IMO

**Comment by 5th-Domain** [comment]
It is still capable of it thought it's got all the internal plumbing for this requirement and not every scenario in command is set in the here and now or in reality. All it needs is the underwing pods attaching and the bladders loading in and it's a tanker. It's possible it is not done due to the Air Tanker Contract the UK currently has. 


> "Finally, the absurdity of the RAF possessing twenty-two Airbus A400M Atlas aircraft which are delivered equipped with fuel lines to attachment points for under-wing refuelling pods and yet not being able to utilise that capability, highlights again the shortcomings of the Air Tanker contract. This is illustrated no more so than in the necessity to base both a Voyager and an Atlas in the Falklands to support four Typhoons." [1]

[1] https://ukdefencejournal.org.uk/the-future-of-uk-aerial-refuelling-needs-part-2/

**Comment by FrangibleCover** [comment]
Right, but does the UK have the pods or the bladders to activate this capability, or is this Fitted For But Not With? I don't have any problem with a Hypothetical Atlas entry that can do this, but the baseline aircraft shouldn't get it.

**Comment by 5th-Domain** [comment]
A clone marked as Hypothetical would be fine.

**Comment by PygmalionOfCyprus** [comment]
Not gonna add it until the UK pursues this capability more broadly, if we were adding hypo entries for every AC capable of AAR then everyone would get a hypo AAR-capable C-130, etc...
