### ISSUE TITLE
Update for YJ-21

### ISSUE THREAD

**Issue by Test229** [PygmalionOfCyprus/cmo-db-requests#3780]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4059

### Summary of Changes

"The missile is claimed with a flight speed of Mach 6, and a terminal speed of Mach 10."
Update the max speed to Mach 10. Change other speed settings accordingly. 

### Sources

https://en.wikipedia.org/wiki/YJ-21

**Comment by PygmalionOfCyprus** [comment]
This is broadly in line with its current generic MRBM speed settings based on altitudes, air thickness, etc.
