### ISSUE TITLE
Add Frequency Agility Property for AN/MPQ-65 and 92N6A FCR

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#3787]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 4155, Sensor 2498

### Summary of Changes

AN/MPQ-65 (db 4155) is an advanced upgrade to the original AN/MPQ-53 incorporating extra TWT, frequency hopping ability, new ECCM countermeasures to suppress sidelobe and main lobe jamming. This works against noise jamming.

92N6A (db 2498) FCR uses similar ECCM with automated frequency hopping along a large bandwidth and sidelobe/main-lobe suppression/minimization to combat spot/noise jamming.

![92n6a ECCM #1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/52533ddc-f62b-409b-896a-2b72a727e362)
![an-mpq-65 eccm #2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/1e286e7b-4794-4ae9-b759-007ee981721c)
![AN-MPQ-65 ECCM #1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/134186902/760e110c-3d32-4b3a-a388-dca090909ffe)

### Sources

https://en.wikipedia.org/wiki/MIM-104_Patriot
https://missiledefenseadvocacy.org/defense-systems/anmpq-5365-radar/
https://www.radartutorial.eu/19.kartei/06.missile/karte007.en.html
https://www.radartutorial.eu/19.kartei/06.missile/karte006.en.html
https://www.ausairpower.net/APA-S-400-Triumf.html

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
