### ISSUE TITLE
Add Strike Rodeo Loadout for AGM-158A JASSM

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#379]
### DB Selector

DB3K

### User(s)

#4973 - F-15E Strike Eagle -- United States (Air Force, 2021, Project Strike Rodeo

### Weapons Carried

Sam as Loadout 29049

switch 

5x AGM-158B JASSM-ER 

for 

5x AGM-158A JASSM

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Sam as Loadout 29049

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Unit - #4973 - F-15E Strike Eagle -- United States (Air Force, 2021, Project Strike Rodeo - currently has single missile loadouts for JASSM and JASSM-ER but only a five missile Strike Rodeo loadout for JASSM-ER. Requesting a loadout addition so 1 and 5 missile options are available for both JASSM versions.

### Sources

https://www.thedrive.com/the-war-zone/40559/five-jassm-stealth-missiles-have-been-loaded-on-an-f-15e-strike-eagle-for-the-first-time?fbclid=IwAR0ZYXvDADU_l0ws9grUur9FUXPq63U_l6KtrKg8_ayvT1Hr3o3EsIwbjUs

**Comment by PygmalionOfCyprus** [comment]
Added 493.
