### ISSUE TITLE
Netherlands facility TRM-L 3D & SMART-L

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3792]
### DB Selector

DB3K

### Affected DBID(s)

#980, 2734

### Summary of Changes

Facility #2734 - Radar (TRM-L 3D) has the sensor #5195 SMART-L EWC (BMD Mod). This might be incorrect. While facility #980 Radar (TRM-L 3D) looks as the correct one. 
The SMART-L is next to the Navy also in use by the NLAF and sold to Sweden
Also found as the SMART-L Multi Mission Fixed (MM/F) 

### Sources

https://en.wikipedia.org/wiki/SMART-L
https://www.armyrecognition.com/defense_news_july_2023_global_security_army_industry/thales_supplies_sweden_with_smart-l_multi_mission_long-range_radars_to_reinforce_air_surveillance_capabilities.html
https://www.asdnews.com/news/defense/2023/07/06/thales-reinforces-air-surveillance-capabilities-sweden-with-smartl-multi-mission-longrange-radars
https://www.defensie.nl/downloads/rapporten/2021/06/07/stralingsrapportage-smart-l-radar-in-wier

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
