### ISSUE TITLE
Bob Hope cargo

### ISSUE THREAD

**Issue by rvseydlitz** [PygmalionOfCyprus/cmo-db-requests#3793]
### DB Selector

DB3K

### Affected DBID(s)

Ship 834

### Summary of Changes

This class has the ability and was actually designed specifically to carry an entire armored task force of 58 M1 MBT and 46 M2 IFVs and a thousand other vehicles. In game, 14 M1s fill it, making a requirement to use many ships in game to do what the 4 did in Desert Storm,
I am trying to work these into a campaign showcasing many of the new features.
### Sources

https://en.wikipedia.org/wiki/Bob_Hope-class_vehicle_cargo_ship

**Comment by PygmalionOfCyprus** [comment]
Drastically increased cargo area, that should do it. Handled 503.
