### ISSUE TITLE
Add Pakistani Akinci Drone 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3795]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4998

### Hypothetical

No

### Name

Bayraktar Akinci UCAV

### Country

Pakistan

### Service

Air Force

### In Commission

2024

### Number in Service

x1+5

### Sensors

Same

### Mounts

Same

### Loadout Options

Same with the exception of the OECM and ESM Pod loadouts

### Sources

https://www.janes.com/defence-news/news-detail/pakistan-air-force-personnel-train-to-operate-akinci-uavs
https://www.janes.com/defence-news/news-detail/update-saudi-arabia-signs-for-akinci-uavs-in-record-deal-with-turkey
https://en.wikipedia.org/wiki/Baykar_Bayraktar_Ak%C4%B1nc%C4%B1
https://greekcitytimes.com/2023/04/05/pakistan-inducts-turkish-drones/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
