### ISSUE TITLE
Add South Korean Green Pine Radar 2012 x 2

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3799]
### DB Selector

DB3K

### DBID to Copy

Facility #1600

### Hypothetical

No

### Name

Radar (EL/M-2080 Green Pine)

### Country

South Korea

### Service

Air Force

### In Commission

2012

### Number in Service

x2

### Sensors

None

### Mounts

None

### Loadout Options

None

### Sources

https://en.wikipedia.org/wiki/EL/M-2080_Green_Pine
https://www.janes.com/article/84858/south-korea-to-procure-additional-green-pine-radars
https://en.topwar.ru/173481-sistema-pvo-respubliki-koreja-radiolokacionnye-sredstva-kontrolja-vozdushnogo-prostranstva-i-raketnye-kompleksy-obektovoj-pvo-i-pro.html
https://www.timesofisrael.com/south-korea-buys-israeli-radar-tech-likely-to-counter-norths-missiles/
https://alert5.com/2018/11/28/south-korea-buying-two-more-israeli-green-pine-radars/

Sipri Line
aircraft produced in South Korea
     		2	EL/M-2080 Green Pine	air search radar	2009	2012	2	For use with Patriot SAM

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
