### ISSUE TITLE
Aircraft Iran - F-5E/F - 1990 - Are armed the Fatter AAM which is about twenty years before it existed? 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3801]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #1310 - F-5E Tiger II (Iran - 1990) #3591 - F-5F Tiger II (Iran - 1990)#6167 - HESA Saeqeh [F-5E Tiger II Copy] (Iran - 2007)

### Summary of Changes

Remove the existing Fatter AAM load out DBID 32342 from the 1990 version of F-5E/F and Saeqah as the missile did not enter production until 2009 per Wikipedia via FARS news.

Please create 2010 version of the F-5's with the Fatter and add an additional load out:
4 x Fatter and 3 x 275 gal drop tank.
The Fatter is a straight swap for the AIM-9 so it could carry four in or just modify the record for the existing load out #32342 which strangely has only two AAM. 

### Sources

DB3K 501
https://en.wikipedia.org/wiki/Fatter

https://web.archive.org/web/20110710224753/http://english.farsnews.com/newstext.php?nn=8808231430

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
