### ISSUE TITLE
North Korea Su-35? Iran maybe not? 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3803]
### DB Selector

DB3K

### DBID to Copy

Aircraft Iranian Su-35?

### Hypothetical

Yes

### Name

Su-35K NORTH Korea 2024

### Country

DPRK

### Service

2024 

### In Commission

2024

### Number in Service

12?

### Sensors

As standard Su-35

### Mounts

As normal. 

### Loadout Options

Minus UPMK? 

### Other Changes

Nil

### Sources

https://twitter.com/JosephHDempsey/status/1702827646025949594?t=lQbwegJwH_8mFjP5_XnyOQ&s=19

Wonder why he'd visit?

**Comment by bostonmyk** [comment]
Russia needs his munitions, and he's going to get the red carpet-treatment. 

Russia's change in strategy has certainly minimized their fighter losses (at least in the air..hehe). They can probably afford to trade stuff. This reminds me of the car part swap meets that occurred when I was a teen (and probably still do).

I'd hold on this one to see what actually materializes. He could decide booze, hookers, and a pack of smokes is a better option. It's good to be king!

**Comment by PygmalionOfCyprus** [comment]
Unripe for now. We can reopen if any news actually materializes.
