### ISSUE TITLE
Update: SDA

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3807]
### DB Selector

DB3K

### Affected DBID(s)

Satellite 162

### Summary of Changes

[SDA_20230917_53600070.csv](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/12642444/SDA_20230917_53600070.csv)

### Sources

www.space-track.org

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
