### ISSUE TITLE
SS-1d Scud C with submunitions crashes program

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#3809]
### DB Selector

CWDB

### Affected DBID(s)

I can't tell

### Description of Problem

I have absolutely no idea what's happening, but the anti-runway submunitions Scud in CWDB just BREAKS the game. Click it and your session is forfeit.

### Recommended Fix

I'm not sure how this is to be fixed.

**Comment by PygmalionOfCyprus** [comment]
Post this in the tech support forum, any game crashes are fundamentally sim-side issues.
