### ISSUE TITLE
Ukraine 6x6 Supacat SHORAD System

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3813]
### DB Selector

DB3K

### Hypothetical

No

### Name

Supacat SHORAD System

### Facility Type

Radar

### Country

Ukraine

### Service

Army

### In Commission

2023-

### Number in Service

"a handful"

### Crew

Unkown

### Dispersion Radius (m)

Unknown

### Sensors

Telescopic EO/IR Turret

### Mounts

1x twin rail launcher per truck for AIM-132 ASRAAM, could also be fitted with AIM-9Ms

### Magazines

Unknown magazine supply

### Aircraft & Docking Facilities

N/A

### Comments

these systems “are deployed primarily to intercept swarms of Russia’s Iranian-supplied Shahed suicide drones, but some of the systems are also supporting Ukraine’s counteroffensive.”

At this point, it’s unclear what type of sensors, beyond the EO/IR turret seen on the truck, can be used to detect and acquire the targets in the first place, although it’s certainly possible that targeting cues are provided by other platforms. Importantly, the ASRAAM is also capable of being used in lock-on after launch (LOAL) mode, meaning targeting data can also be sent to the missile, via datalink, once it has left the rail. This would be key for a system like this. Even just the EO/IR turret could provide basic targeting vectors for the missiles to lock onto once they have left the rail and the target has entered their [high off-boresight (HOBS) seeker's acquisition envelope.

### Sources

https://www.thedrive.com/the-war-zone/asraam-air-to-air-missiles-from-uk-being-used-by-ukraine-as-sams?fbclid=IwAR1QJrEKxeFeSHmZXliPAE4cOodFWww71D00FQyvtJsrfUS-lZeE0oZwirQ

https://www.thedrive.com/the-war-zone/ukraines-aim-9m-sidewinders-can-be-used-in-multiple-ways?fbclid=IwAR17Yjpg04Hq_MA_ByuW8VaD2TxoLAPMG5o4RnaNjh7tNg1OPwudLJrsyCU

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/b37b1552-fe69-45d9-9f79-b558445077a5)

**Comment by bostonmyk** [comment]
https://twitter.com/Osinttechnical/status/1709369867088916615

**Comment by tbrandon517** [comment]
Looks like added for v502

**Comment by tbrandon517** [comment]
Facility 3988
