### ISSUE TITLE
Liana Radar (TU-126 MOSS) Corrections

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#3814]
### DB Selector

CWDB

### Affected DBID(s)

709

### Summary of Changes

RF is 880 MHz so NATO C band not E band
It has no proper lookdown capability
It has no altitude info whatsoever - its a 2D radar
It is 1950's tech, not 1970's

I think a lot of this will reduce it to what it was, an airborne radar station and not an AWACS at all.

### Sources

https://www.globalsecurity.org/military/world/russia/tu-126.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
