### ISSUE TITLE
WS-1B Description is wrong

### ISSUE THREAD

**Issue by Stonie-github** [PygmalionOfCyprus/cmo-db-requests#3817]
### DB Selector

DB3K

### Affected DBID(s)

2249

### Summary of Changes

WS-1B is a ballistic MLRS but its general description is the text for the MIM-104C patriot, perhaps a placeholder durings its creation. 

### Sources

I will just report that the description is wrong for this item. It is obvious.

**Comment by KLABDB3K** [comment]
Text and images (counter intuitively) are not on these forums they are a separate thread still on the main CMO pages.

**Comment by PygmalionOfCyprus** [comment]
Yeah, we don't actually maintain those, they're technically a community project.
