### ISSUE TITLE
Loadout #20193 Combat Search And Rescue (CSAR) (Combat Search And Rescue (CSAR)) for Aircraft #6672 - AS.532A2 Cougar [Al Fahd] CSAR (Saudi Arabia - 1998) CSAR loadout should be DAY/NIGHT not day only. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3819]
### DB Selector

DB3K

### Affected DBID(s)

Loadout #20193 Combat Search And Rescue (CSAR) (Combat Search And Rescue (CSAR))

### Summary of Changes

Loadout #20193 Combat Search And Rescue (CSAR) (Combat Search And Rescue (CSAR)) is currently showing as DAY only, this is in contrast to the SAR load which is DAY/Night all weather.

The Cougars in this configuration are dedicated CSAR aircraft and would definitely be round the clock all weather capable.
It has multiple sensors for this purpose NVG FLIR etc. 

Please amend CSAR loadout setting to DN All weather. 

This will also update the Turkish CSAR cougar aircraft #6673 - AS.532AL Cougar CSAR (Turkey - 2000)
and Dutch aircraft #4069 - AS.532U2 Cougar Mk2 (Netherlands - 1996)

Didnt notice until I updated the scenario to use DAY NIGHT etc and the aircraft would not take off!

### Sources

See DB3k - if the aircraft can do SAR in any time any weather it can do also CSAR. Thanks.

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
