### ISSUE TITLE
China, Active radar seeker (ASM LR DF-27)

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3824]
### DB Selector

DB3K

### Baseline

sensor 7151

### Hypothetical

No

### Name

Active radar seeker (ASM LR DF-27)

### Sensor Generation

Early 2020s

### Range (nm)

80nm

### Sensor Capabilities

Surface Search, Range Information, Speed Information, Heading Information

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Comments

Current sensors on DF-27 ASBM version is just a copy of DF-26B which is developed at least 5 yrs earlier.

Please upgrade the sensor on **weapon 4318 (DF-27 ASBM RV)**.

a passive radar seeker of same tech level is also requested.

### Sources

https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/china/df-27/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
