### ISSUE TITLE
Out of service dates for Pakistani Type 21 Frigates 2022-23

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3825]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1256, 1257

### Summary of Changes

1256 Babur-Harpoon Armed out of service 2022 
1257 Tariq- LY-60N Armed add out of service 2023

### Sources

https://en.wikipedia.org/wiki/Tariq-class_destroyer

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
