### ISSUE TITLE
KRI Oswald Siahaan (354) were modernized with diesel engine to replace the steam engine.

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#383]
### DB Selector

DB3K

### Affected DBID(s)

2041 Oswald Siahaan [Van Speijk]

### Summary of Changes

As of 2006 the steam engine on KRI Oswald Siahaan were replaced with diesel engine as part of modernization programme by PT Mulia and PT PAL. Please change the propulsion from Babcock steam engine on KRI Oswald Oswald Siahaan to 2x SEMT Pielstick 12PA6B diesel engine.

### Sources

(in Indonesian)
http://maritimnews.com/2016/05/mengenal-kri-oswald-siahaan-sang-penangkap-kapal-penyelinap-asal-china/

(In english)
http://www.milpower.org/shipclass.asp?class=Leander
https://en.wikipedia.org/wiki/KRI_Oswald_Siahaan_(354)

**Comment by PygmalionOfCyprus** [comment]
Added 493.
