### ISSUE TITLE
E-8C Retirement date and count

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3830]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 290

### Summary of Changes

Add out of service date of 2024

There were 16 operational J-Stars

### Sources

https://www.airandspaceforces.com/jstars-e-8-museum-final-divestment-draws-near/
https://comptroller.defense.gov/Portals/45/Documents/defbudget/FY2024/FY2024-28_Force_Structure_Changes_Exhibit.pdf
pg. 32

https://en.wikipedia.org/wiki/Northrop_Grumman_E-8_Joint_STARS

https://www.thedrive.com/the-war-zone/e-8-jstars-has-flown-its-last-operational-mission

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
