### ISSUE TITLE
Ticonderoga VLS retirement dates

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3831]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2859

### Summary of Changes

Add out-of-service date of 2023 for Ship 2859 as CG-62 Bunker Hill decommissioned  in 2022 and CG-63 Mobile Bay in 2023

### Sources

Currently Decommissioned
CG-52 Bunker Hill (2022) https://en.wikipedia.org/wiki/USS_Bunker_Hill_(CG-52)
CG-53 Mobile Bay (2023) https://en.wikipedia.org/wiki/USS_Mobile_Bay
CG-56 San Jacinto (2023) https://en.wikipedia.org/wiki/USS_San_Jacinto_(CG-56)
CG-57 Lake Champlain (2023) https://en.wikipedia.org/wiki/USS_Lake_Champlain_(CG-57)
CG-61 USS Monterey (2022) https://en.wikipedia.org/wiki/USS_Monterey_(CG-61) 
CG-66 USS Hué City (2022) https://en.wikipedia.org/wiki/USS_Hu%C3%A9_City
CG-68 Anzio (2022) https://en.wikipedia.org/wiki/USS_Anzio_(CG-68)
CG-72 USS Vella Gulf (2022) https://seapowermagazine.org/ticonderoga-class-cruiser-uss-vella-gulf-decommissioned/
CG-73 USS Port Royal (2022) https://en.wikipedia.org/wiki/USS_Port_Royal_(CG-73)

Still in Service
CG-54 Antietam
CG-55 Leyte Gulf
CG-58 Philippine Sea
CG-59 Princeton
CG-60 Normandy
CG-62 Chancellorsville/Robert Smalls
CG-63 USS Cowpens
CG-64 USS Gettysburg
CG-65 USS Chosin
CG-66 USS Shiloh
CG-69 Vicksburg 
CG-70 Lake Erie
CG-71 USS Cape St. George

**Comment by bostonmyk** [comment]
There is a reasonable 2024 list, and Princeton might go in the coming months but will update to what actually decommissions. Political hot potatoes.

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
