### ISSUE TITLE
Aircraft MRH-90 Taipan Australia OOS Date officially December 2024 but not in use from 2023?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3836]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #2352 - NH90 TTH [MRH90 Taipan] (Australia - 2011)

### Summary of Changes

Withdrawn from use 2023 due to crash with scheduled out of service December 2024. *credit bostonmyk. (thanks)

### Sources

https://twitter.com/AirRecognition/status/1707678340629270744?t=b5F6KNL2Au1MQeFE_5Jymw&s=19
#2352 - NH90 TTH [MRH90 Taipan] (Australia - 2011)

**Comment by bostonmyk** [comment]
Another link:

https://www.defence.gov.au/news-events/news/2023-09-29/taipans-withdrawn-service

**Comment by KLABDB3K** [comment]
Of note is the UH-60M replacement comment in the above link "The first three Black Hawks have arrived in Australia and commenced flying in September, with remaining Black Hawks continuing to be delivered."
Aircraft #5488 - UH-60M Blackhawk (Australia - 0) in service date September 2023 for early 2024?
https://www.defence.gov.au/news-events/news/2023-09-29/taipans-withdrawn-service

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
