### ISSUE TITLE
Add Polish S100B Argus AEW 2023 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3837]
### DB Selector

DB3K

### DBID to Copy

Aircraft 563

### Hypothetical

No

### Name

S100B Argus [SAAB 340] 

### Country

Poland

### Service

Airforce

### In Commission

2023

### Number in Service

x2

### Loadout Options

Ferry
Airborne Early Warning (AEW)

### Other Changes

Add a 2020 out of service date of UAE Argus. These were leased until Global eye sent. See scramble link.

### Sources

Pictures
https://twitter.com/Saab/status/1707774129288458266/photo/1
https://aviationweek.com/defense-space/aircraft-propulsion/first-polish-erieye-saab-340-rolled-out

Info
https://www.scramble.nl/military-news/poland-orders-saab-airborne-early-warning-control-aircraft

**Comment by PygmalionOfCyprus** [comment]
Was added in DB 502.
