### ISSUE TITLE
Pakistani Babur [Ada] Frigate Updates

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3838]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3570

### Summary of Changes

IOC 2024
SAM armament is  [2] 6 tube VLS of Albatross NG [CAMM-ER] SAM
CAMM-ER is weapon #4019 in DB. 
Fire control sensor group is STIR 1.2 (above the bridge already)
Genesis Advent is CMS
No pictures of Torpedoes just yet.

### Sources

Links
https://www.navalnews.com/naval-news/2023/09/turkiye-delivers-corvette-to-pakistan-launches-2-opvs-for-turkish-navy/
https://www.navalnews.com/event-news/dimdex-2022/2022/03/dimdex-2022-asfat-sheds-light-on-pakistans-pn-milgem-corvette/
VLS Pictures
https://twitter.com/Defence_IDA/status/1706268181474763174/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
