### ISSUE TITLE
Tornado F.3 RAM Tiles

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3839]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 308 and others

### Summary of Changes

I am very surprised by this, but apparently Tornado F.3s were fitted with RAM in the intakes, RAM paint on the leading edges and a couple of other quick-win signature reduction tricks for the Gulf War. These modifications appear to have been rolled out across the fleet after the war. The source rates an 'up to 20%' detection range reduction from the frontal aspect, with no effect on any other aspects.

- [ ] Aircraft 945
- [ ] Aircraft 308
- [ ] Aircraft 483
- [ ] "Tornado F.3 (1996) (#3832)
- [ ] Aircraft 1149
- [ ] Aircraft 1586
- [ ] Aircraft 1684
- [ ] Aircraft 1685

### Sources

https://www.raf.mod.uk/our-organisation/units/air-historical-branch/post-coldwar-studies/tornado-f3-operations/
https://www.slideshare.net/TahirSadikovi/tornado-f3-in-focus-part-2

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
