### ISSUE TITLE
Kri Ahmad Yani were modernized with diesel engine to replace the steam engine

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#384]
### DB Selector

DB3K

### Affected DBID(s)

2683 Ahmad Yani [Van Speijk]

### Summary of Changes

Like the Oswald Siahaan (354) [DBIB #2041], the rest of Ahmad Yani-class were modernized and have its Babcock steam engine replaced with diesel engine. But only Oswald Shiahaan were fitted with 2x SEMT Pielstick 12PA6B diesel engine, the rest have 2x Caterpiller 3616 diesel engines for each ship instead.

### Sources

https://en.wikipedia.org/wiki/HNLMS_Tjerk_Hiddes_(F804)
https://military-history.fandom.com/wiki/Van_Speijk-class_frigate
http://www.milpower.org/shipclass.asp?class=Leander
https://en.wikipedia.org/wiki/Ahmad_Yani-class_frigate

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
