### ISSUE TITLE
Update APG-82(v)1 to have SAR

### ISSUE THREAD

**Issue by gorillabond** [PygmalionOfCyprus/cmo-db-requests#3841]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5483

### Summary of Changes

Add the synthetic aperture radar property to the APG-82(v)1

### Sources

https://www.govinfo.gov/content/pkg/FR-2023-09-27/html/2023-21066.htm
https://www.thedrive.com/the-war-zone/40098/we-talk-f-15exs-new-radar-with-the-woman-who-runs-the-program-behind-it

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
