### ISSUE TITLE
Update S300V, VM Combat System

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3842]
### DB Selector

DB3K

### Affected DBID(s)

Facility 38, 1860, 2425,2277

### Summary of Changes

Change the Combat System to a more modern variant than Analog

### Sources

theWood post with Osprey/Vanguard Citation:

[thewood1](https://www.matrixgames.com/forums/memberlist.php?mode=viewprofile&u=102229) wrote: [↑](https://www.matrixgames.com/forums/viewtopic.php?p=5125470#p5125470)Sat Sep 30, 2023 10:56 am
Not much research needed. The S-300 was developed specifically to take advantage of early digital electronics.

The Russian S-300 and S-400 Missile Systems (New Vanguard, 315)...its discussed through out the lifecycle of the S-300 and its upgrades. It doesn't detail the actual systems, but makes considerable reference to the initial semiconductor development for the original S-300 and the advancements in electronics and digital scanning being the drive behind upgrades.

Matrix String
https://www.matrixgames.com/forums/viewtopic.php?p=5125470#top

**Comment by bostonmyk** [comment]
Buks should be upgraded as well.

**Comment by PygmalionOfCyprus** [comment]
![perhaps_i_treated_you_too_harshly](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/a6ae5b2e-3835-437e-b9a4-e43cd3a3594c)

Handled 503.
