### ISSUE TITLE
Add Optional Belly Mounted Radar to USCG HC-130J

### ISSUE THREAD

**Issue by gorillabond** [PygmalionOfCyprus/cmo-db-requests#3843]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 6632

### Summary of Changes

USCG HC-130Js are equipped/being equipped with an APY-11 (I will link to the DB request once this one is posted). 

- [ ] Add APY-11 Radar to newest HC-130Js

### Sources

https://www.dcms.uscg.mil/Portals/10/CG-9/Acquisition%20PDFs/Factsheets/HC-130_0721.pdf

https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Acquisitions-CG-9/Newsroom/Latest-Acquisition-News/Article/3184330/coast-guard-awards-contract-for-radar-systems-for-new-c-130js/

**Comment by gorillabond** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/3844

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
