### ISSUE TITLE
Add APY-11 Radar

### ISSUE THREAD

**Issue by gorillabond** [PygmalionOfCyprus/cmo-db-requests#3844]
### DB Selector

DB3K

### Baseline

448

### Hypothetical

No

### Name

AN/APY-11

### Sensor Generation

Early 2020s

### Range (nm)

0.1-200

### Sensor Capabilities

Air Search, Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Track While Scan (TWS), Periscope/Surface Search - Advanced Processing [2000+], Moving Target Indicator (MTI), Low Probability of Intercept (LPI), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA), Can Classify Ground Targets (SAR), Shallow Water Capable (Partial), Shallow Water Capable (Full) [Classification Flag Required]

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Comments

According to the sources I've found, the APY-11 appears to be a modified and slightly modernized EL/M-2022, with added air search capability. This will be equipped to USCG HC-130Js. 

### Sources

https://www.l3harris.com/all-capabilities/anapy-11-multimode-radar

https://www.flightglobal.com/elta-announces-new-radar-deals-elint-enhancement/110063.article

https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Acquisitions-CG-9/Newsroom/Latest-Acquisition-News/Article/3184330/coast-guard-awards-contract-for-radar-systems-for-new-c-130js/

https://www.iai.co.il/p/elm-2022es

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
