### ISSUE TITLE
Ton-class Minesweepers for South Africa

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3846]
### DB Selector

DB3K

### DBID to Copy

Ship 1607

### Hypothetical

No

### Name

M 1499 Durban

### Country

South Africa

### Service

Navy

### In Commission

1955-2002

### Number in Service

10x, few after 1989

### Other Changes

Fit seems to be identical to RN fit. Could be cloned from the South African version in the CWDB but why bother?

### Sources

https://en.wikipedia.org/wiki/Ton-class_minesweeper#South_African_Navy
https://en.wikipedia.org/wiki/List_of_decommissioned_ships_of_the_South_African_Navy#Minesweepers
https://www.flickr.com/photos/kleinz/3009217073
DB

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
