### ISSUE TITLE
multiple helicopter landing pads/open parking spots

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#3847]
For specifically helo bases - multiple helicopter landing pads/open parking spots example Wattisham Airfield in UK

**Comment by PygmalionOfCyprus** [comment]
The thing is this doesn't really work with the damage model. If you hit a multiple-landing-pads spot does that mean all the landing pads no longer work? Not in real life. So you're better off just modelling it with multiple individual pads to try and get closer to reality. And if damage isn't a consideration, then just use a single-unit airfield.
