### ISSUE TITLE
Add Kyanwa (Balsam) class, Nigeria

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#385]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Vessel (PBO), A501, Kyanwa

### Class

Kyanwa (Balsam)(Cat)

### Country

Nigeria

### Service

Navy

### In Commission

2002 - present

### Length (m)

54.9

### Beam (m)

11.3

### Draft (m)

3.8

### Standard Displacement (t)

700

### Full Displacement (t)

1051

### Complement

42 + 11

### Primary Propulsion Type

Diesel

### Propulsion

2x General motors EMD645 diesel generators

### Flank Speed (kt)

13

### Range (nm) at Speed (kt)

8000 @ 12 (src1), 12000 @ 7 (src2)

### Sensors

1x Raytheon SPS-64(V)1 navigation radar
or SPS-73 (src2)

### Mounts

2x single 12.7mm/90 MG

### Aircraft & Docking Facilities

2x Davits (both sides) for small boat of life boat.

### Comments

Former USCG Balsam-class buoy tenders. Intended for general logistic support duties, transferred unarmed

### Sources

1: JDS 2015-2016;
2: https://www.navypedia.org/ships/nigeria/nig_es_kyanwa.htm;
![2Posted](https://user-images.githubusercontent.com/99532490/155524004-457ad0fb-4e98-458f-bd7a-bd3a238e6d70.jpg)
![4Posted](https://user-images.githubusercontent.com/99532490/155524009-e5970696-8fee-4c8e-8cc1-58035d2769bd.jpg)
![9Posted](https://user-images.githubusercontent.com/99532490/155524010-632eb8f0-4898-4c07-8e62-279d4616f91d.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
