### ISSUE TITLE
Add Andoni (Modified Town) class, Nigeria

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#386]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), 100, Andoni

### Class

Andoni (Modified Town)

### Country

Nigeria

### Service

Navy

### In Commission

2012 - present

### Length (m)

31.3

### Beam (m)

6.1

### Draft (m)

1.4

### Standard Displacement (t)

100

### Full Displacement (t)

140

### Complement

20 + 5

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar C32 diesels, 2 shaft

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

Not found

### Sensors

1x Furuno I-band Navigation radar

### Mounts

1x single 20mm/70,
2x single 12.7mm/90

### Aircraft & Docking Facilities

1x small crane for small RHIB at the aft.

### Comments

Based on the BrookE Manne Town-class patrol craft.
2 unit in class but based on images they are different build (NNS KAraduwa P102) and might need separate entry.

### Sources

1: JFS 2015/2016;
2: https://www.navypedia.org/ships/nigeria/nig_cf_andoni.htm;
3: https://www.defenceweb.co.za/sea/sea-sea/nigerian-navy-commissions-first-locally-built-warship-nns-andoni;
![2Posted](https://user-images.githubusercontent.com/99532490/155529768-a9072513-9a32-4f74-ade7-2168be670b25.jpg)
![4Posted](https://user-images.githubusercontent.com/99532490/155529772-4226ada0-9880-4238-8434-36067644f451.jpg)

**Comment by Jkryos** [comment]
Added DB3K 501.
