### ISSUE TITLE
Update/correction for Joshan SAM system & Sayyad-3

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3861]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3780, Weapon 4127

### Summary of Changes

- Remove HPI, CWAR and PAR mount on Facility 3780 and replace it with a new mount that contains a new radar instead. Joshan used a much modern and capable Joshan PESA radar to guide Sayyad-3 missiles. Unknown spec but it were said to be a 30N6E2 Tombstone derivatives 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/0cbb0c78-98c9-4974-be7d-b4acf544a2ae)

- Change/modify Sayyad-3`s seeker to be able to be guided by the new PESA radar

- Add "capable vs seaskimmer" to the Sayyad-3
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/6ad138a4-dcf6-46e2-a164-a7f1f3aeea02)

### Sources

- https://en.wikipedia.org/wiki/Sayyad_(missile)
- https://twitter.com/Fath_ol_Mobin/status/1457474765300637697
- https://twitter.com/IranDefense/status/1609249441030045696

**Comment by PygmalionOfCyprus** [comment]
Handled 503. Didn't add the seaskimmer flag though, "capable of detecting cruise missiles" is not the same as "can engage a seaskimmer target".
