### ISSUE TITLE
Ababil-2 Munition has Imaging IIR Seeker

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3862]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4175

### Summary of Changes

IIR weapon footage released 

### Sources

https://twitter.com/imp_navigator/status/1709530452451639754
https://twitter.com/mhmiranusa/status/1500527383815892995

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
