### ISSUE TITLE
Increase max launch altitude for various weapons

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#3865]
### DB Selector

CWDB

### Affected DBID(s)

Weapons 1799, 291, 552, 550, 409, 20, etc.

### Summary of Changes

These weapons specifically are loaded on the B-70, which has a max altitude of 90,000 feet. The Skybolt is only launchable from 55,000 feet AGL down, the SRAM from 65,000 ASL, and the dumb bombs are just the same. This limits the usefulness of the aircraft's incredible capabilities somewhat. Generally, dumb bombs and inertially guided weapons probably shouldn't have an upper altitude launch limit.

### Sources

Common sense - a dumb bomb should not care what altitude it's launched from. This is a terrible source and I apologize.

**Comment by PygmalionOfCyprus** [comment]
Handled 503.

**Comment by PygmalionOfCyprus** [comment]
I handled it specifically for those weapons, I agree that dumb bombs should not have an alt limit but I need to do some further digging to make sure I'm not wiping out legitimate data, so for now I'm just tackling the ones on the B-70 and I'll double back to do everything else in a big query later.
