### ISSUE TITLE
Iowa IRBM Monitor Scheme 1 missing an SPG-51

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#3868]
### DB Selector

CWDB

### Affected DBID(s)

Ship 2224

### Summary of Changes

This ship has 15 AN/SPG-51s, eight port and seven starboard. It should likely have eight port and eight starboard.

### Sources

This seems like a very simple misinput. I've never seen a ship designed asymmetrically like that - basically just needs a check if it's correct or not.

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
