### ISSUE TITLE
Add Dorina (Ocea FPB98) class, Nigeria

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#387]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Craft (PB), P101, Dorina

### Class

Dorina (Ocea FPB 98

### Country

Nigeria

### Service

Navy

### In Commission

2014 - present

### Length (m)

35.2

### Beam (m)

6.8

### Draft (m)

1.2

### Standard Displacement (t)

100

### Full Displacement (t)

116

### Complement

12

### Primary Propulsion Type

Diesel

### Propulsion

2 MTU 12V2000 M84, 2 waterjets

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

1000 @ 12 (src1), 900 @ 14 (src2)

### Sensors

1x Furuno FAR 2117 I-band navigation radar

### Mounts

Src1: 1x single 20mm, 2x single 12.7mm
Src2: 1 x 1 - 20/90 Super Sea Rogue

### Aircraft & Docking Facilities

1x small RHIB aft

### Comments

Also in use for the algerian Navy.

### Sources

Source 3 & 4 general info on type
1: JFS 2015-2016;
2: https://www.navypedia.org/ships/nigeria/nig_cf_dorina.htm;
3: https://www.ocea-ssm.com/fpb-98;
4: https://www.wikiwand.com/uk/Ocea_FPB_98;
![3Posted](https://user-images.githubusercontent.com/99532490/155534210-85d64078-1dd9-4731-b8b3-3b5e49ee78c2.jpg)
![2Posted](https://user-images.githubusercontent.com/99532490/155534213-af9a77b8-748b-4beb-8bb4-0319e19528e6.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
