### ISSUE TITLE
Lanza 3D Radars for Uruguay

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3871]
### DB Selector

DB3K

### DBID to Copy

Facility 1872

### Hypothetical

No

### Name

S-763 Lanza 3D

### Country

Uruguay

### Service

Air Force

### In Commission

2010-

### Number in Service

1x fixed, 1x mobile

### Mounts

- [ ] One exact clone
- [ ] One fixed installation with identical stats

### Sources

https://www.indracompany.com/sites/default/files/lanza_3d.pdf
https://es.wikipedia.org/wiki/Radar_LANZA

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
