### ISSUE TITLE
Lanza 3D Radars for Guatemala

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3872]
### DB Selector

DB3K

### DBID to Copy

Facility 1872, #3871

### Hypothetical

No

### Name

S-763 Lanza 3D

### Country

Guatemala

### Service

Army

### In Commission

2015

### Number in Service

3x

### Mounts

All fixed installations

### Sources

https://web.archive.org/web/20161024221425/http://www.efeempresas.com/noticia/guatemala-comenzara-a-instalar-tres-radares-adquiridos-a-indra/

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
