### ISSUE TITLE
Revetted ammo shelters

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#3877]
### DB Selector

Both

### Hypothetical

No

### Name

Revetted Ammo Shelter

### Facility Type

Ammo

### Country

all

### Service

all

### Sensors

none

### Mounts

none

### Magazines

n/a

### Aircraft & Docking Facilities

n/a

### Comments

I have seen many ammo shelters at bases that are placed in revetments 

### Sources

Observations from Google maps etc imagery

**Comment by FrangibleCover** [comment]
DB3k Facility 320 is what you want

**Comment by trevor99999** [comment]
Nope. I've seen actual buildings that are in revetment in munitions dumps and depots, not pallets sitting in the open air in a revetment.
I'm not trying to be a "rivet counter" but in my mind if you're going to include a/c weather shelters, then a shelter/shed in a revetment is just as valid. Although I'm skeptical a fabric weather(?) shelter has 300 DP's of protection, when an underground aircraft shelter is 1600 DP's.

By the way, why is there an image of a Russian SAM battery attached to the Weather Shelter for 1x Very Large Aircraft (#1387)? 

Thanks & regards

    On Tuesday, October 10, 2023 at 05:01:26 p.m. EDT, FrangibleCover ***@***.***> wrote:  
 
 


DB3k Facility 320 is what you want

**Comment by Parel803** [comment]
For this:
By the way, why is there an image of a Russian SAM battery attached to the Weather Shelter for 1x Very Large Aircraft ([#1387]

Check this:
https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=244450&start=880

It is all hobby in free time by these people.
regards GJ

**Comment by PygmalionOfCyprus** [comment]
Handled 503. The Ammo Shelter facility is now also treated as a surface building instead of an open structure (previously it was identical to the Ammo Pad facility). So now you can put things on an open pad, a reveted pad, a surface building, a reveted building, a surface bunker, or an underground bunker. Eat your heart out.

**Comment by trevor99999** [comment]
Outstanding. Thanks!

    On Thursday, October 26, 2023 at 01:59:02 p.m. EDT, Ethan Hermanson ***@***.***> wrote:  
 
 


Closed #3877 as completed.
