### ISSUE TITLE
VIP's/VIP group(s)/VIP passengers/Command Staff/Leadership group

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#3878]
The above for all platforms including vehicles. Example - Air Force One or national equivalent, E-4 and Airborne Command Posts, Looking Glass, motorcades, LCC's, etc)

**Comment by PygmalionOfCyprus** [comment]
I don't understand what this is requesting. A new Type for aircraft, etc.? We already have an ACP type for aircraft.

**Comment by tbrandon517** [comment]
> I don't understand what this is requesting. A new Type for aircraft, etc.? We already have an ACP type for aircraft.

I'm guessing they would like VIP PAX included in the loadouts like in the open skies recon aircraft loadouts.
