### ISSUE TITLE
Please consider AAM load out for #1847 - Hawk 60 (Zimbabwe - 1982) & #1848 - Hawk 60A (Zimbabwe - 1992)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#388]
### DB Selector

DB3K

### User(s)

#1847 - Hawk 60 (Zimbabwe - 1982) #1848 - Hawk 60A (Zimbabwe - 1992)

### Weapons Carried

2 x #1046 - PL-7 [R.550 Magic 1]
5 x #1795 - 30mm Burst [20 rnds] central gun pod
2 x  #1532 - 190 ImpG Drop Tank

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

150

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

Yes

### Comments

Please consider adding 1998 variant of the Hawks armed with the PL-7.
Zimbabwean MK60 an Mk60A Hawks were apparently deployed with PL-7 AAM as a direct drop in replacement for AIM-9'S  over the Congo during the 1998-2003 conflict. AIM-9's were embargoed.
Add 2 x PL-7 AAM and drop tanks as an air defence load out for Zimbabwean Mk60/A Hawks from circa 1998.
Existing load outs for Finish Hawk #17106 with 2 x AA2 could be used as baseline to copy and just swap AA-2 for the PL-7
Ready time 3hrs.
120 minutes at 150 nm CAP. Transit at 36k ft, on-station loiter, 2 minutes combat in Mil. Form-up 2 min at 2k ft. 10% reserves.

### Sources

Books Great Lakes Conflagration - Second Congo War 1998-2003. Tom Cooper - Helion Publishing - Africa at War Series ISBN 978-1-909384-66-8 PP.38
"_Initially AFZ Hawks flew armed reconnaissance sorties, some of them armed with Chinese PL-7 air to air missiles_"
Imagery wise there is nothing I can find so far to show PL-7 in use with the Hawks but Zimbabwe did take delivery of J-7/F-7 in the same time frame and they came with the PL-7, but they were busting sanctions, so not surprising it wasn't in the press release!
http://aviadejavu.ru/Images6/HI/HI-11/45-1.jpg - Hawk Mk60 was capable of using AIM-9 when delivered by BAe. Matra Magic used a similar interface to the AIM-9 and THE PL-7 is a blatant copy of Magic, so the ZAF had the means motive and method.

**Comment by PygmalionOfCyprus** [comment]
Sorry I missed this when it first came in! Added 495.
