### ISSUE TITLE
S3V Zagon Depth Bomb

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#3881]
### DB Selector

DB3K

### Baseline

DB3k Weapon 1015

### Hypothetical

No

### Name

Zagon-1 [S3V]

### Length (m)

1.3

### Width/Span (m)

0.211

### Diameter (m)

0.211

### Weight (kg)

94

### Range (nm)

Glide

### Target Altitude / Depth (ft)

-500 to 2600 - I don't like these numbers, I don't think it really needs to fall for 500ft to start homing?

### Launch Altitude / Depth (ft)

Parachute Retarded - 160-3280

### Warhead

19kg ASW Optimised Shaped Charge

### Targets

Submarine

### Sensors

1x Active Sonar, 120m range

### Weapon Codes

Lock-On After Launch (LOAL), Bearing-Only Launch (BOL), Attitude Control - Aerodynamic Only

### Comments

An absolutely wacky weapon - A guided depth bomb. It can fall through the water at a 60 degree angle (cross range of Depth/SQRT 3) and sinks at 16.2m/s. The tag 'Attitude Control, Hydrodynamic' may apply. I'm not exactly sure how it works, but I would imagine that the fuzing is combined impact/proximity: If it hits it hits, if it misses it tries to go off at closest approach like a normal depth charge. Claimed to be used by Russia and China on a variety of platforms including Ka-27/28, Il-38, Tu-142 and possibly also KQ-200 and Z-20F.

I note the existence of Weapon 1015, "KAB-250PL [S3V]", which shares some properties with the Zagon such as the S3V designation and the approximate size and weight. This weapon isn't used on anything and it has probably been in the database for a while to have such a small DBID as 1015 (between 1014, the C-802, and 1016, the Generic ESM Pod Average, both of which I would imagine have been in the DB since before the CMANO days). I think the Zagon is the weapon that the KAB-250PL is supposed to be, so this might be an update rather than a new weapon request.

### Sources

https://en.wikipedia.org/wiki/S3V_Zagon
https://www.heliopsfrontline.com/helix-rejuvenated-new-avionics-give-kamovs-ka-27-new-life
Janes
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/8cc9c3ed-2b07-43b8-ae74-dc825dee749c)
(The slightly larger Zagon-2E)

**Comment by FrangibleCover** [comment]
Related to #289

**Comment by claudejdev** [comment]
1015, "KAB-250PL [S3V]" would be the "KAB-250-100PL Zagon-1 [S3V]".

That new weapon could be the "KAB-250-100PL Zagon-2 [S3V]", or even "KAB PL Zagon-2 [S3V]"
2E is the export designation.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/a938bf68-3cc9-46d8-8ebc-576a9fae1c7f)
_IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global._

Butowksi mentions a maximum depth of 600m.
_Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today._

**Comment by FrangibleCover** [comment]
Thanks for these sources, I think they clarify a few things, although of course they also muddle them.

KAB-250PL is a very strange designation for a 94kg weapon, but it does seem to at least be connected to the S3V. This request is currently only covering Zagon-1, Zagon-2 is... Well, you know what the Russians are like about announcing equipment and then building either three or none. On the other hand, my source on the Ka-27M says that they carry six S3V depth bombs and your sources imply that the possible choices are eight Zagon-1 or six Zagon-2, so maybe it is in service. For depth we now have three numbers: 600m, 800m and More Than 600m. Pick whichever. For the cross range, Bukowski is taking 60 degrees from the vertical but I think the quoted 60 degrees is from the horizontal instead.

**Comment by PygmalionOfCyprus** [comment]
So, "Handled 509," with the caveat that this requires some sim-side implementation as well since I've built it as a new weapon type and also requires a new downward-facing sonar type. I'll push for implementation but obviously this is a fairly low-priority addition right now, though my hope is that it wouldn't be too hard and so could get snuck in.
