### ISSUE TITLE
RQ-180 is likely more capable than the current DB data suggests

### ISSUE THREAD

**Issue by caelunshun** [PygmalionOfCyprus/cmo-db-requests#3882]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #4328

### Summary of Changes

While the RQ-180 is barely confirmed to even exist, and little is publicly known about its design, all reporting I have found suggests its sensors and stealth should be greater than what the DB currently provides. (See source list for corroboration of the claims I make below.)

Of course, most of these suggestions are merely speculation, but we have nothing better to work off of than educated guesses. If more information is revealed about the aircraft, the DB can of course be updated later. The changes below should at least bring us closer.

### Flight altitude

Based on the few photographs available, as well as its large wingspan, the RQ-180 is speculated to have a flight altitude of ~70,000 ft. or more. Currently, the DB lists only 50,000 ft.

### Sensors

A platform centered around stealth and reconnaissance needs a sensor payload that matches this mission (i.e. sophisticated AESA/LPI radar, IRST, and EOTS). However, the DB RQ-180 has only:
* in terms of radar, an AN/ZPQ-1 (which is actually only deployed on non-stealthy assets such as the MQ-1). This is not an LPI radar, nor is it an AESA; this means that its use will almost immediately reveal the RQ-180's location to modern ELINT assets, cancelling out the aircraft's other stealth characteristics. It is very unlikely the actual aircraft has this flaw. I suggest changing the radar to something like the F-35's AN/APG-81 at minimum, and probably with 360 degree coverage as well, given the much greater size/weight/power capacity of the RQ-180.
* a basic FLIR system, though IRST/EOTS is lacking, which may be worth changing.

### Radar cross-section

The RQ-180 is currently listed as having an RCS of -23.7 / -33.7 dBsm for low and high frequency bands, respectively. For comparison, the B-2 is listed with -30.0 / -40.0 dBsm, the F-35 with -29.5 / -40.0, and the B-21 with -37.6 / -48.1 (!). 

Being a flying-wing design developed several decades after the B-2, and by the same company at that, it seems pretty unlikely that the RQ-180 has _worse_ stealth capabilities than the B-2. Its RCS should be closer to aircraft of the same modern generation (F-35 and B-21) than it should be to the soon-to-be-replaced B-2.

With the RQ-180 having a penetration ISR role where it should never be detected, and with there being evidence of its deployment near China, it seems logical that its stealth should be state-of-the-art. Thus, unless there is a good source to counter this, I suggest reducing the RCS of the RQ-180 closer to that of the B-21/F-35.

### Infrared detection range

The current DB claims an IR detection range of 3.81/6.99/18.87 nm (front/side/rear) for the RQ-180. For comparison, the B-2 has 2.35/4.65/13.49, while the B-21 has 0.39/0.75/2.25 (!). Similarly to what I said above, the range for the RQ-180 should fall somewhere between B-2 and B-21, rather than being worse than both as is currently the case. A proportional change should also be made to the IR classification range.

### Countermeasures

The DB RQ-180 has only chaff. But given the enormous size and probable cost of the platform, there should be plenty of room for more countermeasures, such as DECM, DIRCM, and towed decoys like what is deployed on the F-35. It may make sense to add these.

### Sources

https://www.thedrive.com/the-war-zone/39882/how-the-rq-180-drone-will-emerge-from-the-shadows-as-the-centerpiece-of-a-warfighting-revolution

Claims from the article:

> Its overall design is largely motivated by highly advanced, broadband, all-aspect, very low-observable (stealth) requirements.

> It is meant to fly at very high altitudes in contested airspace, at or in excess of 70,000 feet.

These are, of course, speculations, but given that guesses are all we know about the aircraft, I argue that if the DB includes the aircraft at all, it should match what is speculated. (Note that the claim about maximum altitude is grounded in evidence from the two photographs of what are believed to be RQ-180s flying at high altitude.)

https://web.archive.org/web/20201006080532/https://aviationweek.com/defense-space/usaf-unit-moves-reveal-clues-rq-180-ops-debut

> an operational ISR UAV with an unprecedented combination of extreme low-observable (LO) features and aerodynamic efficiency.

https://www.thedrive.com/the-war-zone/42261/mystery-flying-wing-aircraft-photographed-over-the-philippines

(Evidence of RQ-180 deployment near China)

**Comment by Kobu7** [comment]
Hi 

I agree with this especially in the sensors section.
In a scenario that I am simulating, the Global Hawk far exceeds the RQ-180 as a reconnaissance platform.

Regards

**Comment by 5th-Domain** [comment]
The article below from Aviation Geek Club [1] talks a bit about its stealth properties and also the possibility of aerial refueling as well. Although i didn't find a second source on that, the Smithsonian article does talk about aerial refuelling of drones and possibly RQ-170. [2]

- I would suggest **Boom Refuelling** Flag. [2]

- I would also recommend giving it similar **Properties** Flags as the B-21 or at least the B-2. [1]

[1] https://theaviationgeekclub.com/427th-reconnaissance-squadron-is-operating-the-rq-180-uas-aviation-week-says/
[2] https://www.smithsonianmag.com/air-space-magazine/x-47-missing-link-180955249/

**Comment by PygmalionOfCyprus** [comment]
Agree on all points, nice work with these estimated guesses. Handled 503.
