### ISSUE TITLE
Sikorsky VH-92A Patriot (Marine One)

### ISSUE THREAD

**Issue by Laqueesha** [PygmalionOfCyprus/cmo-db-requests#3884]
### DB Selector

DB3K

### Baseline

6276

### Hypothetical

No

### Name

Sikorsky VH-92A Patriot (Marine One)

### Country

United States

### Service

Marine Corps

### In Commission

2021–present

### Number in Service

21

### Length (m)

17.12

### Wingspan (m)

5.23

### Height (m)

4.70

### Empty Weight (kg)

7031

### Maximum Takeoff Weight (MTOW) (kg)

12565

### Crew

2x pilots, 1x communication system operator, 1x crew chief 

### Propulsion

2x General Electric CT7-8A 

### Service Ceiling (ft)

14000

### Military/Afterburner Speed (kt)

165

### Cruise Speed (kt)

151

### Supercruise

No

### Ferry Range (nm)

539

### Sensors

4x Mk1 Eyeball

### Mounts

Ferry

### Loadout Options

14x passengers

### Comments

Essentially a militarized S-92.

### Sources

https://en.wikipedia.org/wiki/Sikorsky_VH-92_Patriot
https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2809749/vh-92a/
https://www.dote.osd.mil/Portals/97/pub/reports/FY2022/navy/2022vh-92a.pdf?ver=k6I8xM0kV0KSRt2-infDFA%3D%3D

**Comment by PygmalionOfCyprus** [comment]
Agree, I expect it's probably LAIRCM (or a mod of that). Handled 503.
