### ISSUE TITLE
Typo for Canadian infantry unit

### ISSUE THREAD

**Issue by Laqueesha** [PygmalionOfCyprus/cmo-db-requests#3885]
### DB Selector

DB3K

### Affected DBID(s)

3618 (mount)

### Description of Problem

Canadian mispelled as "Candian".

### Recommended Fix

Change Candian to Canadian.

**Comment by PygmalionOfCyprus** [comment]
Facility #3618 points to an Ethiopian AAA unit, can you check the DB/annex/DBID?

**Comment by Laqueesha** [comment]
Oops, it's a Mount, not a Facility.

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
