### ISSUE TITLE
Bayraktar TB2's endurance is extremely short

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3886]
### DB Selector

DB3K

### Affected DBID(s)

All Bayraktar 2 Loadouts

### Summary of Changes

Imagine this was done to enforce a comms range or something similar.  The issue is you can't loiter or have unique flight paths.

See statsheet below.

Endurance is around 27 hours

### Sources

http://crd.yerphi.am/files/Baykar_catalog_eng.pdf

**Comment by claudejdev** [comment]
The database is missing a _UAS [NATO Class III] (650kg)_ class entry, by the way.

Both JAWA Unmanned 21-22 and Gettinger reports :
- an MTOW of 650 kg
- a Max Payload of 155 kg
- a Ceiling of 25.000 ft (demonstrated, as in 2021: 22 500 ft)
- an endurance of 24 hours (27 hours is a record achieved in testing conditions, correct?) (demonstrated, as in 2021: 20h)

As Myk's source does.

-- Gettinger, Dan. Unmanned Combat Aerial Vehicles- current Types, Ordnance and Operation. Vienna, Harpia Publishing, 2021.
-- Jane's All the World's Aircraft Unmanned 2021-2022. Coulsdon, Surrey, UK: IHS Global.

**Comment by PygmalionOfCyprus** [comment]
Handled 503. The TB2s now have a much more impressive range of 2160nmi. Also made some other adjustments to max/cruise speeds, etc. which were incorrect.

**Comment by PygmalionOfCyprus** [comment]
> The database is missing a _UAS [NATO Class III] (650kg)_ class entry, by the way.

@claudejdev we intentionally did not include a Class III size enum because once you get to class three you're really just talking about small aircraft, and for the purpose of hangar/tarmac space there's no meaningful distinction. We only broke them into smaller UAS classes so we could handle interesting code exceptions.
