### ISSUE TITLE
Sikorsky VH-3D (Marine One)

### ISSUE THREAD

**Issue by Laqueesha** [PygmalionOfCyprus/cmo-db-requests#3887]
### DB Selector

DB3K

### Baseline

3330

### Hypothetical

No

### Name

Sikorsky VH-3D (Marine One)

### Country

United States

### Service

Marine Corps

### In Commission

1976–present

### Number in Service

11

### Length (m)

22.1488 

### Wingspan (m)

22.1488 

### Height (m)

5.1308 

### Empty Weight (kg)

5382 

### Maximum Takeoff Weight (MTOW) (kg)

9752.236

### Crew

2 pilots, 1 crew chief

### Propulsion

2x General Electric T58-GE-400B

### Service Ceiling (ft)

14700

### Military/Afterburner Speed (kt)

144

### Cruise Speed (kt)

118

### Supercruise

No

### Ferry Range (nm)

542

### Sensors

3x Mk1 Eyeball 

### Mounts

 AN/ALQ-144A infrared countermeasures

### Loadout Options

ferry

### Comments

Derived from the SH-3.

### Sources

https://en.wikipedia.org/wiki/Sikorsky_SH-3_Sea_King https://www.navair.navy.mil/product/VH-3D

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
