### ISSUE TITLE
Copy Aircraft #4882 - Z-20S (China - 2019) for Z-20KS Dedicated Search & Rescue Helicopter

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3888]
### DB Selector

DB3K

### DBID to Copy

Aircraft #4882 - Z-20S (China - 2019)

### Hypothetical

No

### Name

Z-20KS (China - 2020) Search & Rescue Helicopter

### Country

China

### Service

PLAAF

### In Commission

2023

### Number in Service

Unknown

### Sensors

Appears to have same Nav/weather radar FLIR MAWS/LWR/RWR as standard ASW version but lacking sonar and long range surface search radar?.

Addition of directional searchlight. 

### Mounts

No weapons seen but probably capable of being equipped with Chaff/Flares

War role probable pintle 7.62mm MG in door positions? 

### Loadout Options

Search And Rescue (SAR)
Cargo [Air Drop, 4.5 tons]
Cargo [Air Drop, 1 ton]
Troops, 6x (Troop Transport)
Maritime Surveillance
(Maritime Surveillance)

### Other Changes

window dressing but would the carriers have a couple for plane guards? 

### Sources

https://x.com/Nickatgreat1220/status/1713222090458107992?s=20
https://x.com/Nickatgreat1220/status/1713213918817255493?s=20

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
