### ISSUE TITLE
Typo in title of Loadout #31012

### ISSUE THREAD

**Issue by Quark-73** [PygmalionOfCyprus/cmo-db-requests#3889]
### DB Selector

DB3K

### Affected DBID(s)

31012

### Summary of Changes

Loadout is called "GBU-48/B GPS/LGB [Mk83], ..."

Should be "GBU-49/B GPS/LGB [Mk82],..."  since it contains only GBU-49/B but no GBU-48/B.

### Sources

DB3000 v. 502 and previous

**Comment by PygmalionOfCyprus** [comment]
Handled 503. Found and fixed a couple other Eurofighter loadouts with the same issue.
