### ISSUE TITLE
Sikorsky S-92A VVIP (South Korea)

### ISSUE THREAD

**Issue by Laqueesha** [PygmalionOfCyprus/cmo-db-requests#3892]
### DB Selector

DB3K

### Baseline

6103

### Hypothetical

No

### Name

S-92A VVIP

### Country

South Korea

### Service

Air Force

### In Commission

2015–present

### Number in Service

At least 3

### Length (m)

20.88 

### Wingspan (m)

5.26

### Height (m)

4.7

### Empty Weight (kg)

7031

### Maximum Takeoff Weight (MTOW) (kg)

12565

### Crew

2

### Propulsion

2 × General Electric CT7-8A turboshaft engines, 2,520 shp (1,880 kW) each

### Service Ceiling (ft)

4300

### Military/Afterburner Speed (kt)

165

### Cruise Speed (kt)

151

### Supercruise

No

### Ferry Range (nm)

539

### Sensors

2x Mk1 Eyeball
1x Star Safire 380

### Mounts

Ferry

### Loadout Options

19x passengers

### Comments

Conflicting info as to whether or not it is an S-92 or a VH-92.

### Sources

https://www.thedrive.com/the-war-zone/check-out-south-koreas-own-vh-92-presidential-helicopter https://www.helis.com/database/modelorg/ROKAF-S-92/ http://www.aero-news.net/index.cfm?do=main.textpost&id=994e7a7c-cb07-404b-bc7e-15944a4df8da http://www.airliners.net/photo/South-Korea--/Sikorsky-S-92A/2059207/L/&sid=361fac6d60e96f9cb5853a5b4fc0aeaf

**Comment by Laqueesha** [comment]
Oops, this is

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
