### ISSUE TITLE
Ship #3100 have wrong datalink

### ISSUE THREAD

**Issue by Hotel2622** [PygmalionOfCyprus/cmo-db-requests#3893]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3100

### Summary of Changes

Zumwalt can't use Hypervelocity Projectiles(155mm/52 AGS HVP) no AEGIS Weapon Link instead it's have TSCE Weapon Link.
I tested add Comms device 'AEGIS Command Datalink [AN/SPY-3, Two-Way](-)' ID.66 then work fine.

Thank you.

### Sources

DB3000 v502

**Comment by PygmalionOfCyprus** [comment]
Take it up with the Navy, they didn't put AEGIS on the Zumwalt!

Fixed the HVPs so that they use the correct datalink, though. 😉 Handled 503.
