### ISSUE TITLE
Add An Additional Missile to Bora Missile Launcher

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3897]
### DB Selector

DB3K

### Affected DBID(s)

Facility #4027

### Summary of Changes

Add a second missile. You get two per launcher

### Sources

https://twitter.com/trdefencenews/status/1500475448391872523/photo/1
https://twitter.com/miguyan2000/status/1309759135324549121/photo/1
https://twitter.com/Saju__302/status/1627617949241442304/photo/2
https://twitter.com/AceJaceu/status/1354122450989178883/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 503. Roketsan's website [refers to "1x pod"](https://www.roketsan.com.tr/en/products/multi-barrel-rocket-launcher) which very confusingly seems to consist of 2x missile canisters. 🤷‍♂️
