### ISSUE TITLE
Italian F-35A and F-35B Loadout Updates. GBU-12 and GBU-49

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#39]
### DB Selector

DB3K

### User(s)

F-35A, F-35B

### Weapons Carried

Pictures are from 2021

F-35B
4 GBU-49 External

F-35A
4 GBU-12, External
2 Amraam Internal

### Requires Buddy Illumination

- [ ] Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

- [ ] Yes

### Comments

Pictures 2021 

### Sources

https://www.scramble.nl/military-news/beast-mode-configuration-for-italian-f-35-lightning-iis
https://theaviationist.com/2021/01/29/italian-f-35a-and-b-carry-out-first-simultaneous-drop-of-gbu-12-laser-guided-bombs/
https://theaviationist.com/2020/11/27/check-out-these-new-photos-of-the-italian-f-35a-and-b-flying-together-in-beast-mode-for-the-first-time/
https://theaviationist.com/2020/11/03/italian-air-force-f-35s-carry-out-sead-and-dead-training-during-exercise-lightning-2020/

**Comment by Jkryos** [comment]
Added DB3K 493.
