### ISSUE TITLE
Follow up to issue #3878

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#3900]
In addition to load outs for passengers on a/c, create VIP's/VIP group(s)/VIP passengers/Command Staff/Leadership group load outs.
Thus, similar to a Airbus A310-200 (#2427) + 200x passengers (#2624), we could have an E-4B 747-200 (#696) with, for example, an Xx, XXx or XXXx VIP's/VIP group(s)/VIP passengers/Command Staff/Political Leadership group on board.

Hopefully this clears up the misunderstanding

Cheers

**Comment by Echoblammo** [comment]
Respectfully, have you played CMO at all?

I fail to see how whatever you are suggesting is worth implementing in any way.

**Comment by trevor99999** [comment]
Then please explain to me the point of loading passengers on a commercial airliner. Seems to me that's about as useless, yet it's been done.

And "respectfully", there's no need to behave like an ass.

    On Monday, October 16, 2023 at 06:00:04 p.m. EDT, Echoblammo ***@***.***> wrote:  
 
 


Respectfully, have you played CMO at all?

I fail to see how whatever you are suggesting is worth implementing in any way.

**Comment by FrangibleCover** [comment]
Far be it from me to say you shouldn't suggest a hundred new things in one request, I certainly have, but if you're going to you should suggest each of them individually in a way that makes it as easy as possible for the database managers to implement it. It might be worth looking at examples of long posts in this way, #641 is the DB managers' favourite.

**Comment by PygmalionOfCyprus** [comment]
Related to #3878 

You can still reply to a closed ticket, you don't need to open a separate followup.

At some point I wrote a really nice comment about why I don't bother to do this stuff, but I can't remember the ticket and I can't find the thread now. TL;DR: adding loadouts is a PITA and it's not worth doing it for stuff like passenger variations because it doesn't matter in Command anyway.

**Comment by PygmalionOfCyprus** [comment]
> Respectfully, have you played CMO at all?
> 
> I fail to see how whatever you are suggesting is worth implementing in any way.

Also, please play nice, @Echoblammo.
