### ISSUE TITLE
Update/correction for Karrar UCAV

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3901]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4903, 4904, 5591, 6429

### Summary of Changes

- All karrar drone have 0 fuel consumption for 36k ft altitude and above.  Probably can set the fuel consumption similar to the Skeeter drone (Aircraft/5281) for this altitude range.
**Karrar`s current fuel consumption above 36k ft**
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/ae9dfca0-abf4-44b5-b520-33fa8ebbe1a2)
**BQM-167A Skeeter fuel consumption above 36k ft**
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/f69dea98-4123-48e3-b491-e6b020934820)

- Increase fuel capacity to around 300kg, similar to Skeeter drone. Karrar is of similar size to Skeeter drone (Aircraft/5281), so they should have similar fuel capacity. Current fuel capacity limits Karrar`s endurance to only around 15-30 mins, compared to other sources that indicates it can flew for more than an hour.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/ddb6ee57-4ef3-4c34-a238-4f20cd12ab56)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/a68b290e-556a-4f40-8c3f-7b5838bbd14f)

- Increase combat range for all loadouts to around 500km(270 nautical miles) except Azarakhsh AAM one. The drone is said to be able to navigate outside radio link range via some sort of terrain radar and TERCOM.
 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/5dec5717-40af-4c35-9830-c5b31ea71182)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/0807b297-9da9-4931-ade0-14369f4f2e86)

- Add AD-08 Majid Loadout. Probably limited to just 100 nautical miles since it probably requires operator`s input to use the weapon. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/fbf0fe64-5ede-42bc-b750-b69179a0ace1)

### Sources

- https://www.iranwatch.org/our-publications/articles-reports/leveling-field-irans-asymmetric-use-conventional-military-capabilities
- https://twitter.com/IranDefense/status/1709225283432149166
- https://twitter.com/IranDefense/status/1709569151725895901
- https://english.iswnews.com/28611/military-knowledge-karrar-drone/

**Comment by Jkryos** [comment]
Added DB3K 509.
