### ISSUE TITLE
SNEB loadout 25197 for Alpha Jet Aircraft #4627 - Alpha Jet E (Nigeria - 1982) has CRV-7 rockets. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3904]
### DB Selector

DB3K

### Affected DBID(s)

Loadout 25197

### Summary of Changes

SNEB loadout 25197 for Alpha Jet Aircraft #4627 - Alpha Jet E (Nigeria - 1982) has CRV-7 rockets. 
 Noticed this with issues with magazine fill in a scenario. 

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99494755/f9327ea6-2802-403b-a122-f8de78f0b6c8)

**Comment by FrangibleCover** [comment]
See #3427, there was a bad batch change at some point I think

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #3427
