### ISSUE TITLE
VDV Spetsnaz completely invisible to naked eye

### ISSUE THREAD

**Issue by Laqueesha** [PygmalionOfCyprus/cmo-db-requests#3906]
### DB Selector

DB3K

### Affected DBID(s)

2976

### Summary of Changes

VDV Spetsnaz completely invisible to naked eye (Mk1 eyeball). 

### Sources

Their visual detection range is 0.0nm; another ground unit right next to it cannot see it even in broad daylight on open terrain. Other Spetsnaz units have a visual detection range of 0.70nm.

**Comment by PygmalionOfCyprus** [comment]
The VDV squad has a "Military Personnel, Heavily Camouflaged" modifier (same as other spec ops units, snipers, etc.). Technically this gives them a detection range of 0.001 nmi, which means you literally have to step on them. While the image of being invisible "in broad daylight on open terrain" does seem a bit comical, it's really not so outlandish if you look at the level of camouflage expected from snipers, etc. History is rife with examples of people literally walking over hidden sniper teams. And of course, Command is doing a ton of abstraction when it comes to "open terrain", so they're not literally sitting in the middle of a parking lot; they can be assumed to be hiding in a bush or something.

If I were to increase their visual modifier then they would be detectable from helicopters, etc. which is just not realistic for the type of unit this is intended to represent. So for lack of a better option, I think we're going to leave it as-is. If it's truly disastrous for your mission you can always set up a simple Lua script to set them to autodetectable if a friendly unit gets within X distance of them.
