### ISSUE TITLE
Decoys

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#3910]
Create decoys for airbase facilities and based aircraft and land units and facilities. I recall (and damned if I can find the source now) that during the Kosovo Conflict NATO hit as many decoys as they did real targets.
https://www.businessinsider.com/russia-fake-tanks-similar-to-army-trick-nato-jets-decoys-2023-10
https://www.businessinsider.com/decoy-arms-race-playing-out-ukraine-harder-fake-tanks-weapons-2023-10
https://www.cnn.com/videos/world/2023/09/11/ukraine-decoy-weapons-russia-bell-vpx.cnn

**Comment by bostonmyk** [comment]
You can create a decoy of any unit of the game by using shift + insert buttons.

Video here.

https://www.youtube.com/watch?v=IqnnWO8Erk8&t=193s

Thanks

M

**Comment by trevor99999** [comment]
Thanks! I never knew! You learn something new everyday.
Cheers

    On Thursday, October 19, 2023 at 04:50:12 p.m. EDT, Mike Mykytyn ***@***.***> wrote:  
 
 


You can create a decoy of any unit of the game by using shift + insert buttons.

Video here.

https://www.youtube.com/watch?v=IqnnWO8Erk8&t=193s

Thanks

M
