### ISSUE TITLE
Falagh-2 333mm MRLS

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3912]
### DB Selector

DB3K

### Hypothetical

No

### Name

Falagh-2 333mm MRLS

### Facility Type

Arty

### Country

Iran

### Service

Army

### In Commission

2014? - 

### Sensors

1x Mk1 eyeball

### Mounts

Unknown, probably 3x launchers per battery.
Each launcher have 2x 333mm rockets ready to fire 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/95300ac8-cbe4-4861-8fa0-829c25a9afaa)

### Magazines

Each launcher carry another 2x spare 333mm rockets so in total it should have 6x rockets per battery 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/e1bfdb36-cd41-4463-92b2-b89d0b852863)

### Comments

333mm Falagh-2 rocket`s specification is as below:
- Length: 1.82 meter
- Diameter: 333mm
- Weight: 256kg
- Warhead: 117kg HE
- Max range: 10.8km
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/5e3bf570-8fd9-4c5f-8854-28573fbc8ca8)

### Sources

- https://rogueadventurer.com/2013/08/29/alleged-cw-munitions-in-syria-fired-from-iranian-falaq-2-type-launchers/
- https://www.armyrecognition.com/october_2014_global_defense_security_news_uk/iran_defense_minister_unveiled_new_falaq_rocket_launcher_and_zafar_8x8_tactical_heavy_truck.html
- https://en.wikipedia.org/wiki/Falaq-2

**Comment by capcop98** [comment]
Reload rate for this rockets should be quite fast due to it have its own integrated crane
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/3a0d185d-2237-485d-a599-6c0449ec8577)

https://forum.warthunder.com/t/falaq-modular-mlrs-punching-way-above-its-weight/22932

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
