### ISSUE TITLE
Aras-2 4x4 artillery variant(s) - Iranian Army

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3915]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

- Aras-2 MRLS, 81mm mortar, 105mm M101

### Facility Type

Arty

### Country

Iran

### Service

Army

### Sensors

1x Mk 1 eyeball

### Mounts

- MRLS variant
1. 3x launchers
2. each launcher have 8x 122mm Grad rockets (Weapon/1359) ready to fire
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/474644d1-78b4-45ff-90a6-efc2c29943af)

- 81mm mortar variant
1. 3x vehicles with 81mm mortar
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/4377c5ff-52eb-4a20-ac92-a8c355eba246)

- 105mm M101 variant
1. 3x vehicles with 105mm M101 artillery
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/d421101f-bb14-4515-8ca2-769ad4bd2d90)

### Magazines

MRLS variant
- 24x 122mm Grad rockets(Weapon/1359)

### Sources

- https://21stcenturyasianarmsrace.com/2023/03/01/iran-makes-so-many-kinds-of-grad-launchers/
- https://21stcenturyasianarmsrace.com/2021/10/05/new-iranian-artillery-may-soon-reach-iraq-and-syria/
- https://21stcenturyasianarmsrace.com/2021/11/29/iran-is-continuously-weaponizing-the-aras-2/
- https://twitter.com/21aar_show/status/1443871687619923968

**Comment by PygmalionOfCyprus** [comment]
The 81mm ver. is specifically using an automatic 81mm, details here:
https://twitter.com/mhmiranusa/status/1424799163447906309?s=03

**Comment by Jkryos** [comment]
Added DB3K 509.

**Comment by tbrandon517** [comment]
> Added DB3K 509.

@Jkryos this request is similar to #1662
