### ISSUE TITLE
Update F-15EX Eagle II Air-to-Air Loadout

### ISSUE THREAD

**Issue by rivatntm64** [PygmalionOfCyprus/cmo-db-requests#3916]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4771, Aircraft 6887

### Summary of Changes

According to sources, F-15EX is able to carry a full loadout of 12 missiles, so its air-to-air loadout configuration should be similar to F-15QA (DBID Aircraft 4770).

DBID# 25957 
Current: 12x AIM-120D AMRAAM, 2x AIM-9X Sidewinder
Update: 6x AIM-120D AMRAAM, 2x AIM-9X Sidewinder

DBID# 25960
Current: 20x AIM-120D AMRAAM, 2x AIM-9X Sidewinder
Update: 12x AIM-120D AMRAAM

DBID# 25953
Current: 6x AIM-120D AMRAAM, 4x AIM-9X Sidewinder
Update: 4x AIM-120D AMRAAM, 4x AIM-9X Sidewinder

DBID# 25958
Current: 12x AIM-120D AMRAAM, 2x AIM-9X Sidewinder
Update: 6x AIM-120D AMRAAM, 2x AIM-9X Sidewinder

DBID# 25959
Current: 20x AIM-120D AMRAAM, 2x AIM-9X Sidewinder
Update: 12x AIM-120D AMRAAM

DBID# 25955
Current: 6x AIM-120D AMRAAM, 4x AIM-9X Sidewinder
Update: 4x AIM-120D AMRAAM, 4x AIM-9X Sidewinder

DBID# 27647
Current: 12x AIM-260 JATM, 2x AIM-9X Sidewinder
Update: 6x AIM-260 JATM, 2x AIM-9X Sidewinder

DBID# 27649
Current: 20x AIM-260 JATM, 2x AIM-9X Sidewinder
Update: 12x AIM-260 JATM

DBID# 27650
Current: 6x AIM-260 JATM, 4x AIM-9X Sidewinder
Update: 4x AIM-260 JATM, 4x AIM-9X Sidewinder

DBID# 27651
Current: 12x AIM-260 JATM, 2x AIM-9X Sidewinder
Update: 6x AIM-260 JATM, 2x AIM-9X Sidewinder

DBID# 27653
Current: 20x AIM-260 JATM, 2x AIM-9X Sidewinder
Update: 12x AIM-260 JATM

DBID# 27654
Current: 6x AIM-260 JATM, 4x AIM-9X Sidewinder
Update: 4x AIM-260 JATM, 4x AIM-9X Sidewinder

### Sources

https://en.wikipedia.org/wiki/Boeing_F-15EX_Eagle_II

Armament
Guns: 1× 20 mm (0.79 in) M61 Vulcan 6-barreled gatling cannon, with 500 rounds of ammunition
Hardpoints: 4 wing pylons with 23 total hardpoints, fuselage pylons, bomb racks on CFTs with a capacity of 29,500 pounds (13,400 kg) of external fuel and ordnance
Missiles:
Air-to-air missiles:
12× AIM-9 Sidewinder
12× AIM-120 AMRAAM
12× AIM-260 JATM (to be integrated)

https://www.airandspaceforces.com/bigger-missile-loadout-new-f-15ex-passes-test/

“Once initial testing is complete, operational units receiving the new F-15EX will be able to carry and employ a full loadout of 12 missiles on the aircraft, upon fielding,” the test wing said.

Boeing, maker of the F-15EX, has previously advertised that the fighter can carry 22 air-to-air weapons, but the Air Force’s armament center wasn’t immediately able to say whether that full capability is being acquired by the service or is an option for future upgrades. Boeing did not respond to queries.

https://www.airandspaceforces.com/weapons-platforms/f-15ex/

Armament: One internally mounted M61A1 20 mm six-barrel cannon (500 rd); combination of up to 12 AIM-9 Sidewinders or AIM-120 AMRAAMs, or combination of up to 24 air-to-ground munitions.

**Comment by tbrandon517** [comment]
I think the existing advertised loads should remain to simulate the aircrafts full potential missile truck capability along with any service loadouts depicted above.

**Comment by PygmalionOfCyprus** [comment]
Rather than reworking the loadouts, I have just added "AMBER" to the comments of the Maximum loadouts to indicate that these are dependent on the AMBER racks (which may not have been acquired). With this in mind players can thus mentally exclude these loadouts if this is a limitation they wish to simulate and just follow the normal light/medium/heavy tiers.
