### ISSUE TITLE
Soumar-family cruise missile update/correction

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3918]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3258, 4239, 4240, 4296

### Summary of Changes

- All missiles under this family contains 410kg HE warhead instead 190kg HE warhead.
- Change Abu Mahdi`s (Weapon 4240)  CEP to 3 meters instead of current 5 meters.
- Add land targets as valid targets for Abu Mahdi (Weapon 4240). It were confirmed to have TERCOM capability as well 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/6cb46103-d386-47b9-ae3c-1d98c0aaf7cd)
- Add Passive radar seeker (Sensor 7210) to Abu Mahdi (Weapon 4240)
- Reduce  Abu Mahdi`s (Weapon 4240) cruise altitude to 164 ft (50 meters)
- Probably can remove (Weapon 4333) since the recently unveiled missile is just the same Abu Mahdi (Weapon 4240) that were first seen back in 2020. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/4c392aec-6c9e-4883-824d-658f19264470)

### Sources

- https://english.iswnews.com/29559/military-knowledge-abu-mahdi-cruise-missile/
- https://en.wikipedia.org/wiki/Abu_Mahdi_(missile)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
