### ISSUE TITLE
China, Type 054A Coast Guard version

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3919]
### DB Selector

DB3K

### Baseline

ship 3050

### Hypothetical

No

### Name

Type 054A Coast Guard

### Length (m)

-

### Beam (m)

-

### Draft (m)

-

### Standard Displacement (t)

-

### Complement

-

### Primary Propulsion Type

Diesel

### Propulsion

-

### Flank Speed (kt)

-

### Range (nm) at Speed (kt)

-

### Sensors

-

### Mounts

remove the VLS, AShM and CIWS

### Sources

https://www.google.com.hk/url?sa=i&url=https%3A%2F%2Fwww.sohu.com%2Fa%2F686062866_121470950&psig=AOvVaw2k3ne7nyxwrh0g3wjGlsaM&ust=1698163265319000&source=images&cd=vfe&opi=89978449&ved=0CBEQjhxqFwoTCPCY5qXFjIIDFQAAAAAdAAAAABBK
https://pdf.defence.pk/threads/type-054b-ffg-news-discussions.774366/
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/3f91db24-4d70-429e-be0b-65f36768fca3)

**Comment by bostonmyk** [comment]
See ship 3050 #818

**Comment by LuigiP57** [comment]
> See ship 3050 #818

For a long time, the Type 818 Coast Guard ship was thought to be based on the Type 054A frigate. This may be true, but this coast guard vessel is a direct Type 054A frigate Coast Guard variant, which is clearly different from the Type 818 Coast Guard vessel.

**Comment by PygmalionOfCyprus** [comment]
Handled DB ~~054~~ 504.
