### ISSUE TITLE
Zambia - LCT(8) tank landing craft (1945/1966)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#392]
### DB Selector

CWDB

### DBID to Copy

Ship 363 CWDB

### Hypothetical

No

### Name

LCT(8) tank landing craft -- Zambia (Navy), 1966, ex-Bastion LCT4040

### Country

Zambia

### Service

Navy

### In Commission

1966-1969

### Sensors

No known changes

### Mounts

3 x 1 - 20mm/70 Mk 3

### Loadout Options

8x 30t tanks and 42x troops

### Other Changes

Former RN LCT(8) type landing craft, ex-Bastion LCT4040. Sold to Zambia on 15 September 1966.

### Sources

https://www.navypedia.org/ships/zambia/zam_ls_lct8.htm

https://en.wikipedia.org/wiki/Mark_8_Landing_Craft_Tank#Other_forces_and_civilian_service

**Comment by PygmalionOfCyprus** [comment]
Added 493.
