### ISSUE TITLE
China, PLAN, Type 076 Landing Helicotper Dock, Drone carrier

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3920]
### DB Selector

DB3K

### Baseline

Ship 3153

### Hypothetical

No

### Name

Type 076 LHD

### Length (m)

252.3 m (flight deck); 257 m (speculate gross)

### Beam (m)

45 m

### Draft (m)

8

### Standard Displacement (t)

45000

### Full Displacement (t)

50000

### Complement

same as type 075

### Primary Propulsion Type

Gas Turbine

### Propulsion

2 × 21 MW gas turbine
6 × 6 MW diesel

### Flank Speed (kt)

Better than type 075

### Range (nm) at Speed (kt)

Better than type 075

### Sensors

same as type 075

### Mounts

same as type 075

### Aircraft & Docking Facilities

1x or 2x carrier catapult
1x carrier arresting gear
2x elevator
Larger hangar and open parking than type 075 LHD

### Comments

Set a placeholder in advance.

### Sources

https://en.wikipedia.org/wiki/Type_076_landing_helicopter_dock
https://www.scmp.com/news/china/military/article/3234109/chinese-military-celebrating-workers-social-media-photo-shows-beijing-likely-building-new-type-076
https://www.forbes.com/sites/hisutton/2020/07/23/stealth-uavs-could-arm-chinas-type-076-assault-carrier/
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/3425905c-9b3a-4dc2-90c3-f46700d81d34)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/bcd90e46-cfe4-4036-aca8-16cdbdb2b55e)

**Comment by Jkryos** [comment]
Added DB3K 506.
