### ISSUE TITLE
China, Type 054A Jiangkai II batch 5 [522 Ziyang]

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3921]
### DB Selector

DB3K

### DBID to Copy

ship 2495

### Hypothetical

No

### Name

Type 054A Jiangkai II [522 Ziyang]

### Country

China

### Service

PLAN

### In Commission

2022

### Number in Service

10x

### Other Changes

Replace the HQ-16A with HQ-16B. There is too little information about HQ-16C so I will not open a request of it. However, this new batch of 054A needs a new type of SAM.

### Sources

https://zh.wikipedia.org/zh-tw/054A%E5%9E%8B%E5%AF%BC%E5%BC%B9%E6%8A%A4%E5%8D%AB%E8%88%B0
https://www.seaforces.org/marint/China-Navy-PLAN/Frigates/Type-054A-Jiangkai-II-class.htm
https://www.janes.com/defence-news/news-detail/china-launches-32nd-type-054a-frigate-for-plan
https://www.sinodefenceforum.com/t/054-a-ffg-thread-ii.4149/page-572
One type 054A batch 5 launching HQ-16C (claimed but not sure, definitely not HQ-16A ) SAM
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/594f34cd-8743-4ddc-8eb4-638700179ddf)
![img-1698114831683fdfe83b9c02c1efd59294bc657b06da5](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/5913bba9-dbe5-4355-9837-580f2553eb63)

**Comment by PygmalionOfCyprus** [comment]
Definitely a HQ-16C. I've added it to the DB, but it's currently just a copy of the HQ-16B. (Ironically most sources seem to describe them in one breath so that might not be so inaccurate.)

Handled 503.

**Comment by LuigiP57** [comment]
> Definitely a HQ-16C. I've added it to the DB, but it's currently just a copy of the HQ-16B. (Ironically most sources seem to describe them in one breath so that might not be so inaccurate.)
> 
> Handled 503.

How about increase its PoH to 90% (same as RIM-162 ESSM) to make it different from original HQ-16B?

**Comment by LuigiP57** [comment]
> Definitely a HQ-16C. I've added it to the DB, but it's currently just a copy of the HQ-16B. (Ironically most sources seem to describe them in one breath so that might not be so inaccurate.)
> 
> Handled 503.

BTW, Love the milestone bro.

**Comment by PygmalionOfCyprus** [comment]
>How about increase its PoH to 90%

Done.
