### ISSUE TITLE
 Philippines, C-130J-30

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3922]
### DB Selector

DB3K

### DBID to Copy

6087 C-130J-30 (United States - 1999)

### Hypothetical

No

### Name

C-130J-30

### Country

 Philippines

### Service

Air Force

### In Commission

2026

### Number in Service

3

### Sources

[Philippines to procure three C-130J-30 transport aircraft](https://www.janes.com/defence-news/terror-insurgent-group/latest/philippines-to-procure-three-c-130j-30-transport-aircraft)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
