### ISSUE TITLE
Argentina, P-3 Orions C && N

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3923]
### DB Selector

DB3K

### DBID to Copy

362 P-3C Orion Update III (Norway - 2001) && 868 P-3N Orion (Norway - 1991) 

### Hypothetical

No

### Name

P-3C Orion Update III && P-3N Orion

### Country

Argentina

### Service

Navy

### In Commission

2023

### Number in Service

3 && 1

### Sources

[Argentina buys four P-3 Orions from Norway - Jane's](https://www.janes.com/defence-news/industry-headlines/latest/argentina-buys-four-p-3-orions-from-norway)

[Argentina to Bolster Naval Surveillance with Acquisition of P-3 Orion Aircraft from Norway](https://www.defensemirror.com/news/34950/Argentina_to_Bolster_Naval_Surveillance_with_Acquisition_of_P_3_Orion_Aircraft_from_Norway)

3x P-3C Orions
1x P-3N Orion

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
