### ISSUE TITLE
Spain, MH-60R

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3927]
### DB Selector

DB3K

### DBID to Copy

4796 MH-60R Seahawk (United States 2020)

### Hypothetical

Yes

### Name

MH-60R

### Country

Spain

### Service

Navy

### In Commission

2025 ?

### Number in Service

8

### Sources

[Lockheed Martin Receives Contract Award For Eight Spanish Navy MH-60R SEAHAWK Helicopters - Lockheed Martin](https://news.lockheedmartin.com/2023-10-12-Lockheed-Martin-Receives-Contract-Award-for-Eight-Spanish-Navy-MH-60R-SEAHAWK-Helicopters)
[Spain – MH-60R Multi-Mission Helicopters with Support | Defense Security Cooperation Agency](https://www.dsca.mil/press-media/major-arms-sales/spain-mh-60r-multi-mission-helicopters-support)

> The Department of State has approved the possible sale to the Government of (...)
> thirty-two (32) AGM-114R(N) Hellfire missiles, all up rounds; two (2) Hellfire II Captive Air Training Missiles (CATM); one hundred (100)
> WGU-59/B Advanced Precision Kill Weapon System (APKWS) II Guidance Sections, all up rounds; eight
> (8) Link 16 Multifunctional Information Distribution Systems Joint Tactical Radio Systems (MIDS JTRS) (8
> installed); and four (4) Airborne Low Frequency Sonars (ALFS) (4 installed on 4 aircraft). Also included are
> M514 impulse cartridge/cartridge actuated devices; MJ20 cartridge actuated thruster/cartridge actuated
> devices; WB53 fire extinguisher cartridge/cartridge actuated devices; CCU-136A/A impulse cartridges; M299 Hellfire missile launchers; GAU-21 crew served guns (including pintle and laser pointer); LAU-61 digital rocket launchers; M152 High Explosive warheads for airborne 2.75 rockets; MK66 MOD 4, 2.75-inch rocket motors; rocket motors, 2.75-inch, MK-66-4 inert; WTU-1B inert warheads (HA23); AN/ARC-210 RT-2036 radios with Communications Security (COMSEC); AN/AAR-47 missile warning systems; AN/SSQ-62F sonobuoys; AN/SSQ-53G sonobuoys; AN/SSQ-36B sonobuoys; SRQ-4 Hawklink radio terminals with Hawklink Crypto Control Modules; AN/APX-123 Identification Friend or Foe (IFF) transponders; AN/ALE-47 dispenser, Electronic Countermeasures; Advanced Data Transfer Systems (ADTS); AN/AAS-44C(V)
> Multi-Spectral Targeting Systems; Identification Friend or Foe Mode 4/5 Cryptographic Applique, KIV-78;
> Joint Mission Planning Systems (JMPS); Embedded Global Positioning System/Precise Positioning Service
> (GPS/PPS)/Inertial Navigation Systems (EGI) with Selective Availability/Anti-Spoofing Module (SAASM);
> Airborne Low Frequency Sonars (ALFS) (aircraft provisions only for 4 aircraft); AN/ARQ-59 Hawklink
> radio terminals; Training Simulators/Operational Machine Interface Assistants (ATS/OMIA); tactical
> operational flight trainer; AN/ALQ-210 Electronic Support Measures (ESM) systems; APS-153(V) multimode
> radars; (...)

**Comment by PygmalionOfCyprus** [comment]
Caught it during our news roundup. 😎
