### ISSUE TITLE
Spain, Patriot PEC-3 MSE

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3928]
### DB Selector

DB3K

### DBID to Copy

3223 SAM Bty (Patriot) (United States - 2016)

### Hypothetical

No

### Name

idem

### Country

Spain

### Service

Army

### In Commission

2024 ?

### Number in Service

4

### Sources

[Spain – PATRIOT Configuration-3+ Modernized Fire Units | Defense Security Cooperation Agency](https://www.dsca.mil/press-media/major-arms-sales/spain-patriot-configuration-3-modernized-fire-units)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
