### ISSUE TITLE
Finland, AGM-88G, F-35

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3929]
### DB Selector

DB3K

### Affected DBID(s)

6180 - F-35A Finland 2026

### Summary of Changes

Loadouts:
- add the ID 27350 && 27351 loadouts (from the US' F-35C ID 3836)

### Sources

[Finland – Advanced Anti-Radiation Guided Missiles-Extended Range (AARGM-ER) | Defense Security Cooperation Agency](https://www.dsca.mil/press-media/major-arms-sales/finland-advanced-anti-radiation-guided-missiles-extended-range-aargm)

_I speculate that they will use it from their F-35, like the Dutch, not from their F-18._

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
