### ISSUE TITLE
Weapons DEPRECATED - DEPRECATED

### ISSUE THREAD

**Issue by Quark-73** [PygmalionOfCyprus/cmo-db-requests#3930]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #3580 and more

### Summary of Changes

There are 32 Weapons Name "DEPRECATED" and Comments "DEPRECATED". If they are needed for database integrity please ignore and close this issue.
Following numbers are affected:
3580
3581
3585
3586
3587
3598
3599
3600
3601
3607
3608
3611
3621
3622
3642
3653
3654
3655
3656
3657
3658
3659
3660
3670
3684
3694
3704
3708
3731
3738
3740
3742 

### Sources

BB3K v 502

**Comment by PygmalionOfCyprus** [comment]
Needed for DB integrity.
