### ISSUE TITLE
Germany, Brandenburg MLU, RBS15 Mk3

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3932]
### DB Selector

DB3K

### Affected DBID(s)

4441 F 215 Brandenburg [Type F123] 2024 MLU

### Summary of Changes

**Mount**
- swap the 2x "3093 Mk141 2002, 4x RGM-84D Harpoon IC" for 2x "106  RBS 15M Mk3 Quad"

### Sources

[German Brandenburg-class frigates to receive RBS-15 Mk.3 Antiship-missiles - Naval News](https://www.navalnews.com/naval-news/2023/10/german-brandenburg-class-frigates-to-receive-rbs-15-mk-3-antiship-missiles/)
[Dienstleistungen - 261041-2023 - TED Tenders Electronic Daily](https://ted.europa.eu/udl?uri=TED:NOTICE:261041-2023:TEXT:DE:HTML&src=0&tabId=0)

_Note:_ according to Alex Luck, the updated class will be designated F123**B**. I couldn't find any other source to back up that statement though.

**Comment by PygmalionOfCyprus** [comment]
Already caught this one during our news roundup. 😉 

Handled 503.
