### ISSUE TITLE
Nebo Wrong Band, Wrong Processing Flags

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#3933]
### DB Selector

DB3K

### Affected DBID(s)

2522

### Summary of Changes

This is not a PD radar. It does not need to be. It is a pulse only radar (albeit with modern standard long and short range waveforms). It uses its inherently high blind speeds (lower the RF, higher the blind speed for any given PRI) and delay line cancellation to provide effective MTI.  If it were PD, it could be notched, it isnt, so it cannot be. 
The band is NATO A for reasons I have explained elsewhere (cheap comms band interferrence jamming otherwise) and sits between 140 (VHF Comms) and 225 (UHF comms).

### Sources

International frequency allocation for the band
Non PD, see EW 101 or similar for an explanation of PD vs Pulse Only Radar

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
