### ISSUE TITLE
Disappearing Carrier Gripens

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#3934]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5004 5003

### Description of Problem

In past DB3Ks (as far back as 487) there was a hypothetical carrier based Gripen for Brazil. Aircraft 5003 and 5004. 

Now the database entries are still there, but at some point (I saw this in DB3K 500-502) they got overwritten by the real, flagged as such pure land Gripens. 

### Recommended Fix

Add in new hypo carrier gripens, duplicates of the current (502) 5003-4 but with the carrier capability flag.

**Comment by PygmalionOfCyprus** [comment]
Is there a good reason to add these as a hypothetical other than the fact that Brazil once operated an aircraft carrier (which was demobilized/decommissioned years before the Gripen buy)? Were they considering a carrier-capable buy at some point?

**Comment by tbrandon517** [comment]
I does look like they were looking at that when they still had some hopes of keeping the carrier in service.

https://web.archive.org/web/20140130230702/http://www.janes.com/article/31778/brazilian-f-x2-deal-gives-fresh-impetus-to-saab-s-sea-gripen-concept
https://archive.ph/20170726145218/http://www.janes.com/article/72490/

**Comment by Coiler12** [comment]
More sources:

[https://www.defense-aerospace.com/brazilian-navy-sees-possible-sea-gripen/](url)

[https://twitter.com/GripenNews/status/717574542865117184](url) (also has a cutaway)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
