### ISSUE TITLE
Aircraft UK Gazelle 1997 version et Al - OOS 24/10/23.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3936]
### DB Selector

DB3K

### Affected DBID(s)

UK Aircraft Gazelle 1997 version etc

### Summary of Changes

Out of service. October 2023.

### Sources

https://twitter.com/ForcesNews/status/1716877218926985531?t=YvHOx7FCtCFcOWc8IC7LJQ&s=19

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
