### ISSUE TITLE
RCA Project DAMP L-band/UHF-band-frequency narrow-beam tracking radar

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#3937]
### DB Selector

Both

### Baseline

CWBD 2612 AN/FPQ-16 PARCS & CWDB 834 AN/FPS-108 COBRA DANE

### Hypothetical

No

### Name

Project DAMP L-band/UHF-band tracking radar

### Sensor Generation

Early 1960s

### Range (nm)

3000 km

### Horizontal Arc (deg)

360 Deg (limited by specific installations ie 180 deg rear are on American Mariner)

### Vertical Arc (deg)

-2 to +183 deg

### Sensor Capabilities

Air Search, Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Continuous Tracking Capability, Pulse-Only Radar

### Search/Track Frequencies

C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm

### Lower Frequency (Hz)

425

### Upper Frequency (Hz)

1300

### Scan Interval (s)

Continuous tracking, refreshed every 3 seconds

### Target Altitude (ft)

Max Altitude 266nm L-Band, 204nm UHF

### Horizontal Beamwidth (deg)

2 L-Band, 6 UHF

### Vertical Beamwidth (deg)

2 L-Band, 6 UHF

### System Noise Level (dB)

4 (UHF) 5 (L

### Processing Gain/Loss (dB)

70

### Peak Power (W)

2 MW

### Pulse Width (μs)

1.7

### Blind Time (μs)

1

### PRF (Hz)

285

### Source Level (dB)

N/A

### Pulse Length (ms)

N/A

### TASS/VDS Length (m)

N/A

### TASS/VDS Depth (m)

N/A

### Convergence Zones

N/A

### Comments

Refer to #2983

The combined L/UHF Band array may be akin to a scaled down (30 ft vs 60 ft dish) AN/FPS-80

Was slaved to the C-Band Radars which were in turn slaved to Optical/IR and other systems to point the radars to the right area.

### Sources

https://en.wikipedia.org/wiki/United_States_Space_Surveillance_Network
https://en.wikipedia.org/wiki/AN/FPS-17
https://www.radartutorial.eu/19.kartei/01.oth/karte013.en.html
https://www.history.navy.mil/research/library/online-reading-room/title-list-alphabetically/f/from-sea-stars.html
https://apps.dtic.mil/sti/tr/pdf/ADA995287.pdf - This one how power/frequency for the L/UHF set
https://ntrs.nasa.gov/api/citations/19660007629/downloads/19660007629.pdf
https://core.ac.uk/download/pdf/217147896.pdf
https://ntrs.nasa.gov/api/citations/19680025550/downloads/19680025550.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
