### ISSUE TITLE
Portugal, C-390, Link-16, Name

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3938]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft ID 5342 C-390 Millenium (Portugal - 2023)

### Summary of Changes

**Name**
- KC-390 [^1]

**Comms**
- add an ID 52	Link 16 JTIDS/MIDS comm device. [^2]

### Sources

[^1]: [PRIMEIRA MISSÃO OPERACIONAL DO KC-390 - Força Aérea Portuguesa](https://www.emfa.pt/noticia-4390-primeira-missao-operacional-do-kc390)
[^2]: [First KC-390 For Portuguese Air Force Enters Service - The Aviationist](https://theaviationist.com/2023/10/20/first-kc-390-for-fap/)

_Q: shouldn't most military radio considered as "Secure" by the way?_

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
