### ISSUE TITLE
France, NH90 Caiman, ferry tank

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3941]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft, ID 653 NH90 TTH [Caiman] (France 2014)

### Summary of Changes

- [ ]  Weapons
> NEW, 400 kg Internal Auxiliary Fuel Tank

- Copy: ID 3886 4000kg Auxillary Fuel Tank
- Name: 400 kg Internal Auxiliary Fuel Tank
- (with its assorted DataFuel, DataWeaponFuel entries I assume)

- [ ]  DataLoadout
> NEW, _(Ferry)_
- Copy: ID 20020	(Ferry)
- Comments: NH90 TTH
- DefaultCombatRadius: 864

- [ ]  DataAircraftLoadouts
You know...

### Sources

[NH90 Main Characteristics - NHIndustries](https://www.nhindustries.com/website/en/ref/Main-Characteristics_158.html)
[NH90 technical information | Airbus](https://www.airbus.com/en/products-services/helicopters/military-helicopters/nh90/nh90-technical-information)
[France deploys NH90 to Mali - IHS Jane's 360](https://web.archive.org/web/20151019163558/http://www.janes.com/article/45450/france-deploys-nh90-to-mali)

**Comment by claudejdev** [comment]
Does an Endurance metric expressed in hours help in any way for aircraft, by the way?

**Comment by PygmalionOfCyprus** [comment]
> Does an Endurance metric expressed in hours help in any way for aircraft, by the way?

Yes.

Also, shouldn't this be for all NH90s? Is there a reason you only requested it for the French?

**Comment by claudejdev** [comment]
The reason is that no other service have documented such an option in their
inventory.
As far as I'm aware of, but only the French actually bought and fielded
these aux tanks. For now
Cheers

Le jeu. 26 oct. 2023, 19:28, Ethan Hermanson ***@***.***> a
écrit :

**Comment by PygmalionOfCyprus** [comment]
Fair. Handled 503.
