### ISSUE TITLE
Germany, Weapon, IDAS (Target Altitude issue)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#3942]
### DB Selector

DB3K

### Affected DBID(s)

Weapon ID 4252 IDAS (IRIS-T Mod, Sub Launched)

### Summary of Changes

 4252	IDAS	IRIS-T Mod, Sub Launched

- [ ]  DataWeapon
- TargetAltitudeMin: 0
(otherwise, it prevents targeting a Land Structure)

- [ ]  DataWeaponCode
- add 6129	Re-Attack Capability  [^1]

### Sources

[^1]: [Guided Missiles | Diehl Defence](https://www.diehl.com/defence/en/products/guided-missiles/#-idas)
[Guided missile system IDAS - self-defense for submarines  - Bundeswehr](https://www.bundeswehr.de/de/organisation/ausruestung-baainbw/ruestungsprojekte/lfk-sys-see-luft-u212a-idas-)
[Interactive Defence and Attack System for Submarines (IDAS) GlobalSecurity.org](https://www.globalsecurity.org/military/world/europe/idas.htm)

_Q: shouldn't its Air PoH value be akin to the Air POH IRIS-T (ID 4041) it's evolved from? 95% ie._ 

One could think its IOC would be 2022.
[Update on IDAS submarine-launched missile with TKMS - Naval News](https://www.navalnews.com/naval-news/2023/05/update-on-idas-submarine-launched-missile-with-tkms/)

**Comment by PygmalionOfCyprus** [comment]
Handled 503. Re-attack is for torpedoes, I don't think it would have any effect on IDAS.
