### ISSUE TITLE
China, 093A/B SSN rename

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3944]
### DB Selector

DB3K

### Affected DBID(s)

submarine 590 665

### Summary of Changes

Rename submarine 590 as [Type 093A Shang II] and submarine 665 as [Type 093B Shang III]

### Sources

https://en.wikipedia.org/wiki/Type_093_submarine
https://media.defense.gov/2023/Oct/19/2003323409/-1/-1/1/2023-MILITARY-AND-SECURITY-DEVELOPMENTS-INVOLVING-THE-PEOPLES-REPUBLIC-OF-CHINA.PDF
![Screenshot_20231027_163220](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/bee2968d-f855-4394-8631-f82ee65ad03f)

**Comment by PygmalionOfCyprus** [comment]
Love these OSD reports. Hopefully one day NATO will actually update their brevity codes for Chyna. Wouldn't that be nice.
