### ISSUE TITLE
China, Type 093B Shang III SSGN update

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3945]
### DB Selector

DB3K

### Affected DBID(s)

submarine 665

### Summary of Changes

1. Change its subtype from to SSGN (designated by US MoD)
2. Add KD-20 [CJ-10A] SLCM (weapon 3716) to its VLS mount (It is believed that it will be equipped with land attack cruise missile)

### Sources

https://en.wikipedia.org/wiki/Type_093_submarine
https://www.janes.com/defence-news/news-detail/china-launches-second-possible-type-093b-hull
https://media.defense.gov/2023/Oct/19/2003323409/-1/-1/1/2023-MILITARY-AND-SECURITY-DEVELOPMENTS-INVOLVING-THE-PEOPLES-REPUBLIC-OF-CHINA.PDF
![Screenshot_20231027_163220](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/0924cce7-fd13-4e99-b426-3969c80e37c3)

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
