### ISSUE TITLE
Eurofighter with Taurus

### ISSUE THREAD

**Issue by Quark-73** [PygmalionOfCyprus/cmo-db-requests#3947]
### DB Selector

DB3K

### User(s)

German Eurofighter Project Quadriga #5213 and #5214

### Weapons Carried

- 2 x AIM 2000A IRIS-T
- 2 x TAURUS KEPT 350
- 1 x 1000 l Drop Tank
- 4 x Meteor

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

440 nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

For drag and range I would assume similar values like loadout 19043 (EF2000 with Stormshadow).

This loadout would be hypothetical (if possible) since even flight trails took place it is not introduced in German Airforce so far.

### Sources

https://esut.de/wp-content/uploads/2019/03/Auch-mit-dem-Eurofighter-sind-bereits-erfolgreiche-Trageversuche-mit.jpg

**Comment by PygmalionOfCyprus** [comment]
Appears to have been tested in 2014, so I added to the 2015+ Eurofighters as a hypothetical loadout. If this goes in-service at some point we will pare it back to just the years where it is actually in use.
