### ISSUE TITLE
Ship #3566 TBD 76 OPV Nigeria armament?  WIP

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3948]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3566 TBD 76 OPV NIGERIA 2025

### Summary of Changes

Mistral and 76mm gun vanishes.
Associated FCS/EO FCS removed? 
 Main gun 30mm Aselsan CWS.
Secondary weapons 12.7mm Aselsan CWS x 2.
Beleive the TBD 76 is the same as the warship referenced in the Twitter sources?

### Sources

https://twitter.com/Jakepor21/status/1717851135141204091?t=Gyy1trteNDMijZA1dqOxnA&s=19
https://twitter.com/Jakepor21/status/1717578695991300175?t=tw50HP47zZO1MhHWpvpYQA&s=19

**Comment by PygmalionOfCyprus** [comment]
If I see one more massively popular weapons system renamed I'm going to throw a fit. WHAT WAS WRONG WITH SMASH, TURKEY?! TOO WESTERN?!

Handled 503.

**Comment by KLABDB3K** [comment]
There's still some STAMP. The same X source also added:
"For everyone asking, NN 76m ships will not be armed with Mistral SAM’s, anti-ship missile (AShM) or a 76mm main gun, NN instead opted for the OTO Marlin 40 (40mm) main gun, ASELSAN 30 mm MUHAFIZ Remote Controlled Stabilized Naval Gun and 12.7 mm STAMP RCWS".

**Comment by PygmalionOfCyprus** [comment]
Yeah, I handled it. STAMP is still STAMP (for now) but MUHAFIZ used to be SMASH, which was way cooler.

**Comment by KLABDB3K** [comment]
https://x.com/DefenseNigeria/status/1588600985588740096

This animation is interesting as it shows the off set configuration of the stabilised 12.7mm RW S and the pintle mounted M2' HMG. There is one RWS on the Stbd bridge forward with an M2 on the same deck level amidships and then an M2 on the port bridge forward and a RWS on the same deck level amidships. I haven't seen images the real thing to check if this is actually what they did?

![OPV76 AMID](https://gith
![OPV76 DECK](https://github.com/user-attachments/assets/e0c7025f-1ebb-4fff-9a20-4f95767b29f9)
ub.com/user-attachments/assets/9f467f40-d28c-4e59-b3d4-70db2d972345)
