### ISSUE TITLE
Hypothetical battleships cannot engage with RIM-66s

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#3949]
### DB Selector

DB3K

### Affected DBID(s)

Ships 3866-3868 and 3871-3872

### Description of Problem

Hypothetical upgraded Iowas and Alaska BBLs have RIM-66 missiles (Weapons 1690 and 660). In AAW test scens, trying to engage with them gives a "weapon cannot connect with mandatory datalink". Manually adding an Aegis datalink allows them to engage fine. 

### Recommended Fix

Add either Aegis datalinks or NTU datalinks and change the default missiles to compatible ones.

**Comment by tbrandon517** [comment]
Should be an NTU set-up.

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
