### ISSUE TITLE
Various hypothetical F-14 modifications

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#395]
### DB Selector

DB3K

### Affected DBID(s)

DB entries for F-14E variants

### Summary of Changes

Being entirely hypothetical, there's not much data, but assuming the F-14E would have maintained feature parity with the Hornet and Super Hornet, especially the AST-21, here are some suggested modifications primarily regarding sensors and deriving from equipment aboard the Super Hornet and F-35:

- Upgrade the APG-71(V) units from 2011 onward to be AESA and NBILST capable on all F-14E variants, or just outright swap them for the NATF APG-77.
- Upgrade DECM and RWR to match later models, such as replacing ALR-67(V)2 with ALR-67(V)3 or even the ALR-94 for the AST-21. Replace ALQ-165 with ALQ-214(V)3 from 2014 on.
- Replace AXX-1 with Generic TV Camera (3rd Gen, Target Tracking and Identification) - ID 4599, as seen on the A-12 and A/F-11X.
- Possible for future variants, none currently available in timeframe: Replace AAS-42(V) with ASG-34.
- Theoretical: Replace Night Owl TGP with ATFLIR.
- Theoretical: AAR-56 PMAWS.
- Theoretical: ALE-55.

I understand this is a bunch of highly specific demands with no sourcing - don't worry about it too much, and if it's a wontfix I understand, but I do think the lack of AESA/NBILST on later models is at least worthy of attention.

### Sources

Comparisons to Super Hornet, F-24A, and A/F-117X as in database.

**Comment by KushanGaming** [comment]
Completed for DB495.
AST-21 gains the NATF radar from 2014 onward, ST-21 and Quickstrike keep their current radars. All variants get appropriate sensor upgrades inline with equivalent Super Hornets. AST-21 and ST-21 gain ATFLIR, Quickstrike keeps the Night Owl. No variant gains the AAR-56.

All variant have new Blk III variant, equivalent to Blk III Super Hornets; AARGM-ER, JATM, and JSOW-ER added.
