### ISSUE TITLE
Add Ethiopia Krasukha-4 facility

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3950]
### DB Selector

DB3K

### DBID to Copy

Facility 2483 (DB3K)

### Hypothetical

No

### Name

1RL257 Krasukha-4

### Country

Ethiopia

### Service

ENDF (National Defence Force)

### In Commission

2023 - present

### Sources

https://www.military.africa/2023/10/ethiopia-showcases-electronic-warfare-gear-at-anniversary-celebration
https://defence-blog.com/ethiopia-unveils-new-russian-made-electronic-warfare-system
https://www.youtube.com/watch?v=83m2Rejo3QY

**Comment by bostonmyk** [comment]
https://twitter.com/i/bookmarks?post_id=1779206296501096647

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
