### ISSUE TITLE
Correction: China, PLAN, JL-2 SLBM, Range issue

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3958]
### DB Selector

DB3K

### Affected DBID(s)

weapon 1089 1974

### Summary of Changes

According to CMPR 2023, JL-2's projection range should be about 3900nm.
Also rename it as CSS-N-14 (Currently CSS-N-4 in DB)

### Sources

https://media.defense.gov/2023/Oct/19/2003323409/-1/-1/1/2023-MILITARY-AND-SECURITY-DEVELOPMENTS-INVOLVING-THE-PEOPLES-REPUBLIC-OF-CHINA.PDF
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/921d0bf3-88ea-4805-b35c-c3339bb68eef)

**Comment by Jkryos** [comment]
Haven't changed the range, sources conflict pretty heavily. Name has been updated DB3K 507.
