### ISSUE TITLE
China, PLAN, JL-3 SLBM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3959]
### DB Selector

DB3K

### Baseline

WEAPON 1089 1974

### Hypothetical

Yes

### Name

JL-3 [3x 150kt Nuclear, CSS-N-20]

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

500-5400

### Warhead

3x 150kt nuclear

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### Sensors

-

### Comments

Upgrading PLA sea based nuclear arsenal.

### Sources

https://en.wikipedia.org/wiki/JL-3
https://www.armscontrol.org/act/2023-05/news/china-deploys-new-submarine-launched-ballistic-missiles
https://media.defense.gov/2023/Oct/19/2003323409/-1/-1/1/2023-MILITARY-AND-SECURITY-DEVELOPMENTS-INVOLVING-THE-PEOPLES-REPUBLIC-OF-CHINA.PDF
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/ab094942-2c5a-4e2d-a9d2-36f41f75158f)

**Comment by HunterDNiu** [comment]
I'm more inclined to believe JL-3 carries one megaton warhead with intercontinental range (i. e. can target CONUS, a good measure is from SSBN base in GA to Bohai Sea) given its developmental record and political motives.

**Comment by Jkryos** [comment]
Added DB3K pre-506.
