### ISSUE TITLE
China, Type 094A Jin class SSBN, JL-3 SLBM equipped

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3960]
### DB Selector

DB3K

### DBID to Copy

submarine 248

### Hypothetical

No

### Name

Type 094A Jin, JL-3 SLBM

### Country

China

### Service

PLAN

### In Commission

2020

### Loadout Options

Replace JL-2 SLBM as JL-3 SLBM

### Sources

https://en.wikipedia.org/wiki/Type_094_submarine
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/c6651891-f77d-454e-9af6-e0738ba83ef8)

**Comment by Jkryos** [comment]
Added DB3K 505
