### ISSUE TITLE
Delete Mk1 Eyeball in Unknown Ship map

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#3964]
### DB Selector

DB3K

### Affected DBID(s)

4351,3122, ...

### Summary of Changes

Delete sensor Mk1 Eyeball on the units in Ship -> Unknown.
Units like Icebergs, Oilslicks, Lost shipping container, Floating Wreakcage and Floating Drugs.
Total DBID list:
4351
3122
4434 through 4438
3270
3612 through 3616

### Sources

nvt

**Comment by PygmalionOfCyprus** [comment]
This is coded sim-side, I can't do anything about it in the DB.

**Comment by Parel803** [comment]
understood
