### ISSUE TITLE
Add Hungarian NASAMS III 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3967]
### DB Selector

DB3K

### DBID to Copy

Facility 3374

### Hypothetical

No

### Name

SAM Plt/2 (NASAMS III)

### Country

Hungary

### Service

Army

### In Commission

2024

### Number in Service

x3

### Loadout Options

Did get Amraam-ER (C/7-C8) missiles for this

### Sources

https://twitter.com/KOGDefence/status/1719980209917571392
https://armyrecognition.com/defense_news_april_2023_global_security_army_industry/hungarian_air_defense_to_take_delivery_of_nasams_missile_systems_soon.html
https://www.kongsberg.com/newsandmedia/news-archive/20202/hungary-selects-kongsberg-and-raytheon-missiles--defense-for-medium-range-air-defense/
https://www.dsca.mil/press-media/major-arms-sales/hungary-advanced-medium-range-air-air-missiles-extended-range-amraam
https://missilethreat.csis.org/hungary-purchases-amraam-nasams/
https://www.globaldefensecorp.com/2023/11/03/hungary-boosts-air-defense-capability-with-nasams-anti-air-system/
https://www.defense-aerospace.com/hungary-to-receive-nasams-air-defense-missiles-by-august/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
