### ISSUE TITLE
BM-21 Grad Warheads

### ISSUE THREAD

**Issue by Kobu7** [PygmalionOfCyprus/cmo-db-requests#3968]
### DB Selector

Both

### Affected DBID(s)

Warhead #970

### Summary of Changes

Hi

The BM-21 Grad uses two types of rockets that in reality have two warheads but in the simulator it is only one, #970, which is fine to simplify because there are no big differences.

The problem is that the explosive charge is 6.4kg when in reality it is between 18kg and 25kg depending on the rocket.

I propose upgrading to one of the two, it doesn't matter which one.

Regards 

### Sources

https://en.wikipedia.org/wiki/BM-21_Grad

https://www.militarytoday.com/artillery/grad.htm

**Comment by FrangibleCover** [comment]
http://characterisationexplosiveweapons.org/studies/annex-a-122-mm-mbrl/

Not so, it's a 6.4kg explosive charge. The 18.4kg number is the full weight of the warhead section with the explosives, the twin steel fragmentation sleeves, the fuze and the ancillaries.

**Comment by Kobu7** [comment]
> http://characterisationexplosiveweapons.org/studies/annex-a-122-mm-mbrl/
> 
> Not so, it's a 6.4kg explosive charge. The 18.4kg number is the full weight of the warhead section with the explosives, the twin steel fragmentation sleeves, the fuze and the ancillaries.

Ok I understand the distinction. I close the ticket then.

Regards
