### ISSUE TITLE
F-24A Hellcat II [NATF, Lockheed Proposal] 2024

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#397]
### DB Selector

DB3K

### Baseline

#4109

### Hypothetical

Yes

### Name

F-24A Hellcat II [NATF, Lockheed Proposal]

### Country

USA

### Service

USN

### In Commission

2024+

### Length (m)

18.9

### Wingspan (m)

19.5

### Height (m)

5.08

### Empty Weight (kg)

14365

### Maximum Takeoff Weight (MTOW) (kg)

38000

### Payload Weight (kg)

4500

### Crew

2

### Propulsion

X2 F-119 PW-100

### Rate of Climb (ft/min)

33110

### Service Ceiling (ft)

60000

### Military/Afterburner Speed (kt)

1000+

### Cruise Speed (kt)

Same as 2016 Model

### Supercruise

Yes

### Ferry Range (nm)

2750

### Endurance (min)

Same as 2016 Model

### Takeoff / Landing Distance (m)

Same as 2016 Model

### Fuel Capacity (kg)

Same as 2016 Model

### Sensors

Same as 2024 F-22A Raptor.

### Mounts

Same as 2016 Model

### Loadout Options

Same as 2016 Model, plus JATMs and newer AIM-9Xs:

CAP:
x6 AIM-260s
x2 AIM-9X Block III

Long Range CAP:
x6 AIM-260s
x2 AIM-9X Block III
x2 370 USG EFTs

### Comms/Datalinks

Same as 2024 F-22A Raptor.

### Aircraft Codes

Supermanouverability, Fly-by-Wire, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Probe Refuelling

### Comments

Not a priority, but it'd be great to have a F-24 able to carry the latest AAMs and with the same two-way data-link as the latest F-22A.

### Sources

CMO 492 DB.

**Comment by tbrandon517** [comment]
Would some ASUW loadouts be possible as some prgram concept art showed GBU-12s? Other fan art has included JSOW, JDAM, etc. Could probably use F-22 and F-35 options as a basis.

![NATF-2S](https://user-images.githubusercontent.com/99599482/155742549-3b23fc38-9897-4427-83ee-cc1fe84f111b.jpg)
![6500963199_e5e9e0f220_b](https://user-images.githubusercontent.com/99599482/155742551-73d12529-91f0-404b-9449-1a05e66a5c57.jpg)
![a47780474b34184ce35d60e419cf6115](https://user-images.githubusercontent.com/99599482/155742552-1d97b81e-2f4b-446f-a5ef-d2b1e243dea5.jpg)
![5511222292_d324b7db82_c](https://user-images.githubusercontent.com/99599482/155742553-5d416ab6-39bc-4893-a902-16caac966460.jpg)

**Comment by KushanGaming** [comment]
Done for DB495.
