### ISSUE TITLE
Add AARGM-ERs to 2023 A-12A

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#3972]
### DB Selector

DB3K

### User(s)

Aircraft 6097, A-12A Avenger II (2023)

### Weapons Carried

As AGM-88E loadouts, (21301, 21302, 21303)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As AARGM loadouts

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

This is BASICALLY just the AARGM loadouts with AARGM-ERs.

### Sources

Other Navy aircraft of this time period have AARGM-ERs, the Avenger just lacks them.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
