### ISSUE TITLE
Japanese Ships using AGM-84D instead of RGM-84D

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#3975]
### DB Selector

DB3K

### Affected DBID(s)

MOUNT 633

### Summary of Changes

It should use RGM-84D(Naval) instead of AGM-84D(Air launched model).

### Sources

https://en.wikipedia.org/wiki/Harpoon_(missile)

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
