### ISSUE TITLE
Add out of service date of 2023 to Indian IL-38SD

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3978]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 1335

### Summary of Changes

Add out of service date of 2023

### Sources

https://www.thedrive.com/the-war-zone/il-38s-retirement-brings-an-indian-maritime-patrol-era-to-an-end
https://www.aviacionline.com/2023/11/indian-navy-withdraws-its-last-il-38-sea-dragon-maritime-patrol-aircraft-from-service/

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
