### ISSUE TITLE
F-23 Black Widow 2024

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#398]
### DB Selector

DB3K

### Baseline

#4107

### Hypothetical

Yes

### Name

F-23 Black Widow II

### Country

USA

### Service

USAF

### In Commission

2024+

### Length (m)

Same as #4107

### Wingspan (m)

Same as #4107

### Height (m)

Same as #4107

### Empty Weight (kg)

Same as #4107

### Maximum Takeoff Weight (MTOW) (kg)

Same as #4107

### Payload Weight (kg)

Same as #4107

### Crew

1

### Propulsion

Same as #4107

### Rate of Climb (ft/min)

Same as #4107

### Service Ceiling (ft)

60000

### Military/Afterburner Speed (kt)

Same as #4107

### Cruise Speed (kt)

Same as #4107

### Supercruise

Yes

### Ferry Range (nm)

Same as #4107

### Endurance (min)

Same as #4107

### Takeoff / Landing Distance (m)

Same as #4107

### Fuel Capacity (kg)

Same as #4107

### Sensors

Same as F-22A Raptor 2024.

### Mounts

x1 20mm M61A2 Cannon.

### Loadout Options

x8 AIM-120D
x2 AIM-9X Block III
Or
x8 AIM-260
x2 AIM-9X Block III

Otherwise, similar to the F-22A Raptor 2024. 

### Comms/Datalinks

Same as F-22A Raptor 2024.

### Aircraft Codes

Supermanouverability, Fly-by-Wire, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Bombsight - Advanced Navigation (INS/GPS), Helmet Mounted Sight / Display (HMS/HMD), Boom Refuelling

### Comments

All variants of the F-23 should be slightly stealthier than the F-22.

_“...the USAF ATF requirements did not require the ATF design to have a lot of agility. The USAF was looking for a stealth fighter that would have a significant time differential between the ATF and the bandit’s discovery of the ATF. For Northrop, the aft deck of the YF-23A was one of the key stealth features of Northrop’s ATF design. Northrop chose stealth over agility to meet the USAF specifications. Northrop’s aft deck design shielded the aircraft from horizontal and look up threats by hiding the exhaust. Lockheed did the opposite, they chose agility over stealth for the design of the aft section of their YF-22A.”_

The F-23 should be able to carry air-to-ground munitions. Later models should also be able to carry a larger complement of air-to-air missiles with rotary or trapeze launches.

_"A big, deep weapons bay is great for air-to-ground applications, but it does invite potentially unwanted complexity for air-to-air applications. By stacking missiles above other missiles, it means that if one jammed, the ones behind it would not be usable—or worse. It also meant that an elaborate missile handling and launching mechanism would be required. This could add substantial weight and complexity to the design, and thus increase risk and possibly cost associated with it. At the same time, a big, deep, trough-like weapons compartment meant that the YF-23 could potentially carry substantial air-to-ground stores, including 2,000lb class weapons, and possibly even larger. Such a bay could also be subdivided for different types of off smaller weapons to be carried at one time.

By most accounts, this configuration would have allowed for four or maybe five AIM-120s and a pair of sidewinders to be carried, but some claim that elaborate and complex AIM-120 carriage contraptions could have drastically increased this to as many as eight or even 10 AIM-120s

Like so many things YF-23, in retrospect, an ATF that could carry a diverse air-to-ground weapons load, including munitions capable of taking out large and well fortified targets—and especially a fighter that had better kinematic, range, and low observable (stealth) performance than even the YF-22—would be a near ideal combat aircraft today."_

### Sources

https://www.thedrive.com/the-war-zone/24911/this-is-what-a-northrop-f-23a-wouldve-looked-like-if-lockheed-lost-the-atf-competition

https://www.thedrive.com/the-war-zone/23993/the-yf-23s-weapons-bay-layout-was-one-of-its-best-features-and-one-of-its-worst

https://reviews.ipmsusa.org/review/northrup-yf-23-atf

https://theaviationgeekclub.com/exclusive-yf-23a-thermal-designer-provides-interesting-details-northrop-atf/

**Comment by KushanGaming** [comment]
Done for DB495.

**Comment by TempestII** [comment]
Legend! Cheers.
