### ISSUE TITLE
Urgent need for PCH-191

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3981]
### DB Selector

DB3K

### Affected DBID(s)

-

### Summary of Changes

PLAGF has now officially released image of its own TBMs launched by PCH-191 which has been in service for at least 4 yrs. And now the relevant issues are just laid aside for more than one year without any update. I think this equipment should be attached enough importance to.
#1979 #988

### Sources

https://twitter.com/BC_Xuanming/status/1722938962778702218
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/25c356ad-feea-4db8-8b8e-268157a9f570)

**Comment by PygmalionOfCyprus** [comment]
We are launching a full national review of China for DB 504/505. All the Chinese tickets will be handled at some point during that process, as well as us conducting significant independent research. You won't have to wait much longer. 🙂
