### ISSUE TITLE
Maybe update for multiple UAVs?

### ISSUE THREAD

**Issue by Test229** [PygmalionOfCyprus/cmo-db-requests#3982]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4773, 6702, 4774

### Summary of Changes

Reduce the RCS value for XQ-58s and Have Raider.

### Sources

Currently, the Have Raider comes with a quite large RCS value (4.7, 4.2 sqm front) Given that in the DB picture that aircraft is basically the same as MQ-28, I suppose they should have a similar RCS? 

Also, the XQ-58s have an RCS of 0.46 for A-D and 0.23 for E and above, but for UTAP-22 in the DB, the RCS value is quite low, they are kinda made by the same company, so the XQ-58s should probably also have a lower RCS value? XQ-58 is bigger but the difference in RCS value is really huge so.

No source, just based on my guess. Feel free to close this if my guess doesn't make sense.

**Comment by TempestII** [comment]
The current CMO Have Raider is a bit of a strange one. My understanding is that the Have Raider II is a unmanned F-16 used for testing in the USAF's CCA programme. Therefore, it makes sense for the aircraft to mostly mirror the stats, RCS, sensors, and possibly weapons load of a USAF F-16. Whether there are any plans to use the Have Raider F-16s in real world combat or even training situations is currently unclear; they may remain as test aircraft, and therefore stepping stones to the CCA and NGAD.
What muddies the waters even more is that the NF-16D VISTA. AKA X-62A, is also involved in the VENOM programme.
I'm not entirely sure if these two programmes are completely separate or heavily related.

That being said, I would love to see a VLO version of the Have Raider in the CMO DB. I can't remember exactly what database update changed the UCAV to having a bigger RCS, but certainly the unit in DB493 had a VLO RCS (I utilised them for that reason in my Strike of the Vampires scenario). The image of the stealth Have Raider seems to have persisted from that era. Of course, whether you'd still call this unit a Have Raider is an interesting one - perhaps Have Raider III, or bringing it under the CCA umbrella could be an option for the Devs. 
While I appreciate there's currently no open source VLO US UCAV that carries air to air weapons (like the AIM-120 or AIM-260), considering the Russians have the S-70 Hunter in the DB, it'd make sense to me to have a similar US platform, if only for the player base to use it for manned-unmanned teaming tests, until more is known about Longshot, CCA etc. 

Sources:
https://www.thedrive.com/the-war-zone/six-f-16s-getting-autonomous-computer-brains-for-combat-drone-trials

https://www.defensenews.com/air/2023/03/28/us-air-force-plans-self-flying-f-16s-to-test-drone-wingmen-tech/

https://www.popularmechanics.com/military/research/a26028/f-16-drone-have-raider-ii/

**Comment by Test229** [comment]
> The current CMO Have Raider is a bit of a strange one. My understanding is that the Have Raider II is a unmanned F-16 used for testing in the USAF's CCA programme. Therefore, it makes sense for the aircraft to mostly mirror the stats, RCS, sensors, and possibly weapons load of a USAF F-16. Whether there are any plans to use the Have Raider F-16s in real world combat or even training situations is currently unclear; they may remain as test aircraft, and therefore stepping stones to the CCA and NGAD.
> What muddies the waters even more is that the NF-16D VISTA. AKA X-62A, is also involved in the VENOM programme.
> I'm not entirely sure if these two programmes are completely separate or heavily related.
> 
> That being said, I would love to see a VLO version of the Have Raider in the CMO DB. I can't remember exactly what database update changed the UCAV to having a bigger RCS, but certainly the unit in DB493 had a VLO RCS (I utilised them for that reason in my Strike of the Vampires scenario). The image of the stealth Have Raider seems to have persisted from that era. Of course, whether you'd still call this unit a Have Raider is an interesting one - perhaps Have Raider III, or bringing it under the CCA umbrella could be an option for the Devs. 
> While I appreciate there's currently no open source VLO US UCAV that carries air to air weapons (like the AIM-120 or AIM-260), considering the Russians have the S-70 Hunter in the DB, it'd make sense to me to have a similar US platform, if only for the player base to use it for manned-unmanned teaming tests, until more is known about Longshot, CCA etc. 
> 
> Sources:
> https://www.thedrive.com/the-war-zone/six-f-16s-getting-autonomous-computer-brains-for-combat-drone-trials
> 
> https://www.defensenews.com/air/2023/03/28/us-air-force-plans-self-flying-f-16s-to-test-drone-wingmen-tech/
> 
> https://www.popularmechanics.com/military/research/a26028/f-16-drone-have-raider-ii/

Hmmm, interesting, so the DB image is actually misleading in this case... If it's a f-16 drone then it makes sense.

Speaking of S-70 just checked in the db and the image is actually a US UCAV...

**Comment by claudejdev** [comment]
@Test229 re the images, the commonly accepted usage is to post in that thread: [Updated DB image & description packs are available! - Page 48 - Matrix Games Forums](https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=244450&start=940)

It has been suggested to migrate it all to Github, like the DBRequest. Well, it has been suggested.
