### ISSUE TITLE
Aircraft NATO E-7A Wedgetail 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3985]
### DB Selector

DB3K

### DBID to Copy

Any Aircraft E-7 Wedgetail

### Hypothetical

No

### Name

E-7A Wedgetail NATO 2030

### Country

NATO

### Service

Air Force

### In Commission

2030

### Number in Service

6

### Sensors

Nil expected. 

### Mounts

Probably something LAIRCM like DECM Chaff Flares etc 

### Loadout Options

AEWAC.
Ferry. 

### Other Changes

None

### Sources

https://twitter.com/GuyPlopsky/status/1724756309697036476?t=0IexsgI3936kVSrEX2uENA&s=19

https://www.nato.int/cps/en/natolive/news_219907.htm?selectedLocale=en

Follow the Boeing links.

**Comment by PygmalionOfCyprus** [comment]
Handled 504 as part of routine news roundup.
