### ISSUE TITLE
K 31 Visby - 2021 MLU change date and add CAMM after Umkhonto cancelled 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#3987]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3345 K 31 Visby - 2021 MLU

### Summary of Changes

Umkhonto was cancelled so not in service by 2021?
CAMM selected 2023. Possibly just remove 12 x Umkhonto and add 36 x CAMM change MLU in service date to 2025?

### Sources

https://worlddefencenews.blogspot.com/2023/11/sweden-navy-to-equip-visby-class.html

https://newsroom.mbda-systems.com/sweden-orders-mbdas-camm-air-defence-missile/

https://twitter.com/D__Mitch/status/1725442744116535706?t=N01oUUKQSCecMY58peYlaw&s=19 
36 CAMM per 9 x Excls launchers in graphic? 

Confirmed

**Comment by KLABDB3K** [comment]
https://twitter.com/pawel_zariczny/status/1724834147133272276?t=v29mLp4hpN0CMzA50x4Xaw&s=19 seems to have been removed from MBDA X twitter Releases

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
