### ISSUE TITLE
Add GBU-39 SDB 1 loadouts to Aussie F-35A

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3988]
### DB Selector

DB3K

### User(s)

aircraft 3601

### Weapons Carried

Copy GBU-39 Internal loadouts from other F-35A

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://twitter.com/TheBaseLeg/status/1725092795034267908

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
