### ISSUE TITLE
Add Romanian PAC-2 GEM, PAC-3 MSE Patriot 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3989]
### DB Selector

DB3K

### DBID to Copy

Facility 2507

### Hypothetical

Yes

### Name

SAM Bty (Patriot [PAC-2 GEM+, PAC-3 MSE])

### Country

Romania

### Service

Air Force

### In Commission

2020

### Sources

https://missilethreat.csis.org/romania-acquires-patriot-missiles/
https://missilethreat.csis.org/system/patriot/
https://ac.nato.int/archive/2020/Romania-PATRIOT
https://www.romania-insider.com/romania-received-second-patriot-missile-system-2022
https://twitter.com/RaduTudor1970/status/1724820017252872428

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
