### ISSUE TITLE
Update RCS Slava class

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#3992]
### DB Selector

DB3K

### Affected DBID(s)

Ship # 593 and #87

### Summary of Changes

The warship Moskva was a guided missile cruiser, belonging to the Slava class. The ship was
designed and constructed during the 1970s and Moskva (originally named Slava) was commissioned
into the Soviet Union navy in 1983. At the time of construction, not much effort was put into
making the ship stealthy. 

With a length of around 186 m and a height of more than 20 m above sea level, the ship’s radar cross section (RCS) is substantial. The RCS varies with aspect angle and the largest RCS is expected from the ship’s broadside (Knott et al. 2004). The broadside RCS for a ship of Moskva’s size is estimated to range from 40 dBsm to 50 dBsm (McGillvray 1994) while the head-on RCS can be around 10 dB lower compared to broadside (Knott et al. 2004).

Now the DB has this numbers:
Front: 30.5
Side: 34.2
Rear: 30.5

I don't know the original source of the DB but I'll just show this data.  34.2 or +/- 45dB is a lot.

And maybe is the height of the ship of 20 meters handy for the mast height measurments?

Thank you.

### Sources

[https://journals.ametsoc.org/view/journals/bams/aop/BAMS-D-23-0113.1/BAMS-D-23-0113.1.xml](url)

**Comment by PygmalionOfCyprus** [comment]
RCS is calculated dynamically from dimensions and modifiers, and the Slava already has no modifier, so it's as low as it's gonna get without reworking the entire RCS model.

Mast height implemented, though.
