### ISSUE TITLE
Add datalink to LRASM #2378 so weapon can be redirected

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3994]
### DB Selector

DB3K

### Affected DBID(s)

weapon #2378

### Summary of Changes

Add the Tomahawk Missile Datalink or create a LRASM-specific datalink with CEC, Secure, and UHF.

First source mentions a waveform comms called Chameleon but not sure if that the entire system or just the relay link. Satellite link is L band via Viasat. Maybe just adding a general LRASM is best for civ CMO to start..hehe,

### Sources

https://twitter.com/ThrustWR/status/1723887465830687200
https://www.lockheedmartin.com/content/dam/lockheed-martin/mfc/documents/business-area-landing/Fast-Facts-LRASM.pdf
https://medium.com/@avipra303/the-dominance-of-agm-158c-lrasm-a-game-changer-in-modern-warfare-94d8399ed3c5

Via sat stuff
https://www.janes.com/defence-news/news-detail/bae-systems-awarded-production-contract-for-additional-lrasm-seekers
https://www.nasdaq.com/articles/viasat-tapped-by-lockheed-to-provide-lrasm-weapon-data-links-2017-06-15

**Comment by PygmalionOfCyprus** [comment]
LRASM already received a Tomahawk DL some time ago but I've created a new LRASM DL entry.
