### ISSUE TITLE
Add AGM-88 Loadout to SU-27S1M 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3995]
### DB Selector

DB3K

### User(s)

#6892

### Weapons Carried

Add Loadout #32033 to aircraft #6892

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Looks like a 2022 Flanker was created with the AGM-88 loadout but then that loadout wasn't added to the later 2023 version. No big deal. 

### Sources

All 4 of my eyes

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
