### ISSUE TITLE
Singapore KC-135R out of service date 2019

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#40]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1854

### Summary of Changes

Singapore replaced #1854 KC-135R aircraft  in 2019

### Sources

https://www.scramble.nl/military-news/first-of-four-former-rsaf-kc-135s-leaves-for-new-home
https://www.flightglobal.com/singapore-pays-tribute-to-retired-kc-135r-fleet/135293.article

**Comment by Jkryos** [comment]
Fixed DB3K 493.
