### ISSUE TITLE
Generic C-UAV jammer Gun, add Suicide Drone as Target

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4000]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3685 Generic C-UAV jammer Gun

### Summary of Changes

**Targets**
- add Missile, 1003

**Weapon Codes**
- add Capable vs Seaskimmer, 2006

_Reasoning:_
in the DB, Suicide Drone are Missiles.
While they can be targeted by a manual allocation, not having missiles in their allowed target type prevents automatic fire in their WRA.

### Sources

DB3K 503, Build 1328.12

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/cead3bf4-b6a6-435a-ae1e-800b0e932388)

**Comment by claudejdev** [comment]
At some point, we will be adding Mobile targets to counter UGV and Surface vessels to counter USV.
Every day is a new day ;)

**Comment by PygmalionOfCyprus** [comment]
This will have unintended consequences, enabling C-UAV jammer guns to shoot down all missiles, etc.

The C-UAV jammer was a stopgap entry added waaaaaay back when and is actually just a laser with a different name. The real solution for this is implementation as a directional comms jammer, which is on the way.

**Comment by claudejdev** [comment]
> (...) The real solution for this is implementation as a directional comms jammer, which is on the way.

Awesome! Looking forward to it 😺
