### ISSUE TITLE
France, NEROD F5 C-UAV Jammer Gun

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4001]
### DB Selector

DB3K

### Baseline

3685 Generic C-UAV jammer Gun

### Hypothetical

No

### Name

NEROD F5

### Length (m)

1.1

### Width/Span (m)

0.2

### Diameter (m)

0.4

### Weight (kg)

8

### Targets, Weapon Codes

- As per #4000

### Comments

- Cargo_Mass: 27 kg (Weight of complete system in logistics packaging)
- Cargo_Volume: 0.2 (Logistics packaging dimensions: 1.458 x 0.469 x 0.285 m)

- It neutralizes conventional or improvised mini and micro UAVs by simultaneously acting on 4 of the 5 [preselected] available remote control frequency bands, [incl. NGSS]
- The jammer allows up to 40 minutes of transmission (all selected bands) with a single battery.

### Sources

[NEROD F5-5 : Brouilleur portatif directionnel anti drones | Ministère des Armées](https://www.defense.gouv.fr/terre/nos-materiels/nos-equipements-terre/nos-armes/nerod-f5-5-brouilleur-portatif-directionnel-anti-drones)
[NEROD RF - MC2-Technologies](https://mc2-technologies.com/en/nerod-rf/)
[Des fusils anti-drones pour l’armée luxembourgeoise | Virgule](https://www.virgule.lu/luxembourg/des-fusils-anti-drones-pour-l-armee-luxembourgeoise/4637244.html)

**Comment by PygmalionOfCyprus** [comment]
See #4000
