### ISSUE TITLE
France, Luxembourg - Inf Plt (C-UAV) (NEROD F5 C-UAV Jammer Gun)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4002]
### DB Selector

DB3K

### DBID to Copy

facility 3247 

### Hypothetical

No

### Name

Inf Plt (C-UAV) (NEROD F5 C-UAV Jammer Gun)

### Country

France, Luxembourg

### Service

Army

### In Commission

2024

### Number in Service

France, 10x Luxembourg

### Mounts

- Generic C-UAV Jammer Gun replaced by #4001

### Sources

[NEROD F5-5 : Brouilleur portatif directionnel anti drones | Ministère des Armées](https://www.defense.gouv.fr/terre/nos-materiels/nos-equipements-terre/nos-armes/nerod-f5-5-brouilleur-portatif-directionnel-anti-drones)
[Des fusils anti-drones pour l’armée luxembourgeoise | Virgule](https://www.virgule.lu/luxembourg/des-fusils-anti-drones-pour-l-armee-luxembourgeoise/4637244.html)
[VIDÉO - Le Nerod, la nouvelle arme anti-drones de l'armée française | TF1 INFO](https://www.tf1info.fr/justice-faits-divers/video-tf1-le-nerod-la-nouvelle-arme-anti-drones-de-l-armee-francaise-2273666.html)

France may had have 50x already in 2021, and an handful already in 2019:
[2023, année charnière pour le bouclier anti-drones des armées - FOB - Forces Operations Blog](https://www.forcesoperations.com/2023-annee-charniere-pour-le-bouclier-anti-drones-des-armees/)
[Mais que sont ces imposantes armes tenues par des militaires lors du défilé du 14 juillet? - rtbf.be](https://www.rtbf.be/article/mais-que-sont-ces-imposantes-armes-tenues-par-des-militaires-lors-du-defile-du-14-juillet-10270625)

Out of interest:
["Méthode d’estimation des valeurs extrêmes des distributions de contraintes induites et de seuils de susceptibilité dans le cadre des études de durcissement et de vulnérabilité aux menaces électromagnétiques intentionnelles" Thomas Houret](https://www.researchgate.net/publication/340261094_Methode_d'estimation_des_valeurs_extremes_des_distributions_de_contraintes_induites_et_de_seuils_de_susceptibilite_dans_le_cadre_des_etudes_de_durcissement_et_de_vulnerabilite_aux_menaces_electromagne)

**Comment by claudejdev** [comment]
As far as I can tell, Luxembourg is not part of the OperatorCountry table.
It should be.
Luxembourg is a NATO member, and, as a coalition partner, brings specialized capabilities.
And who said it couldn't be interested in becoming a Pro user too? 😉

**Comment by PygmalionOfCyprus** [comment]
See #4000
