### ISSUE TITLE
Belgium, Mirage 5BA/R, IOC update

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4003]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 1248 Mirage 5BA - 1984, 3065 Mirage 5BR - 1984

### Summary of Changes

**AircraftData**

Platform | YearCommissioned
--- | ---
1248 Mirage 5BA - 1984 | 1980
3065 Mirage 5BR - 1984 | 1979

### Sources

- Godfurnon, Nicolas. Mali, Charles.  SABCA Vol. 2 - From the Mirage through to the Centenary (1964-2020), Fonds National Alfred Renard, Bruxelles. 2020

63 ECM kits were ordered. The update started in 1979 at the SABCA plant, as witnessed by the author, Charles Mali.

**Comment by PygmalionOfCyprus** [comment]
Handled 504.
