### ISSUE TITLE
Aircraft #4883 EC-37B Compass Call - 2021, Gulfstream G550 - is going to be called EA-37B

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4006]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #4883 

### Summary of Changes

Apparently being retitled to reflect an attack capability as EA-37B.

### Sources

https://twitter.com/thenewarea51/status/1726986988967121101?t=3YLbw1G9vhPCH84oXnkRSQ&s=19 etc

**Comment by 5th-Domain** [comment]
Hope you don't mind if i tag this on with this update too #1859. Just reading the drive post on it now looks like it will have some kind of electronic attack capability as well.


[1] https://www.thedrive.com/the-war-zone/new-attack-ea-37b-moniker-for-usaf-electronic-warfare-jets

**Comment by PygmalionOfCyprus** [comment]
Was already fixed at some point looks like.
