### ISSUE TITLE
(A173) HMS PROTECTOR 

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#401]
### DB Selector

DB3K

### Baseline

#1519 - A 171 Endurance, 1992-2008 (Possibly?), #3402 - ABFC Ocean Shield, 2014. [10]

### Hypothetical

No

### Name

A 173 HMS PROTECTOR, 2011

### Class

Ice Patrol Ship (Polar Class), Survey Ship

### Country

United Kingdom

### Service

Royal Navy

### In Commission

2011-

### Length (m)

89.7m [6]

### Beam (m)

18m [4], [6]

### Draft (m)

8.35 m (Max), 7,3m (As Ice Breaker) [3], [5]

### Standard Displacement (t)

5000 [1]

### Complement

66 (Usual), 100 (Max), A team of RN divers, as well as a detachment of Royal Marine cold weather specialists, support personnel when landed ashore in Antarctica. [8]

### Max Sea State

7

### Primary Propulsion Type

Diesel

### Propulsion

2 × Rolls-Royce Bergen BR-8, 2 x 3,535 kW (4,741 hp) [3], [5]

### Fuel Capacity (kg)

1360 tonnes Diesel/Gas, 215 tonnes Aviation Fuel (Secondary), [6], [7].

### Flank Speed (kt)

15kt [6]

### Range (nm) at Speed (kt)

14,000 nm @ (?kt), 70 days Endurance. [8]

### Sensors

"Survey capability – including multi-beam echo sounding and inshore survey equipment for accessing shallower waters" [1].

"STS Defence was tasked with providing the platform with a full military HF/VHF/UHF ICS25 communications capability. The design solution had to be physically and seamlessly integrated into the platform as a fully operational system without any significant alterations to the vessel." [2]

"To deliver the capability without impacting on the ship’s internal space, STS Defence designed, manufactured and fitted-out a 40’ ISO container, which was installed in the lower cargo hold, with an associated antenna farm on the bridge roof." [2]

"The internal equipment was provided as Government Furnished Equipment (GFE), most of which was recovered from de-commissioned or inactive platforms. This equipment had to be retrieved intact, refurbished, re-built and made functional before being installed and set to work." [2]

"4 Multi-Beam Echo Sounder (MBES) transducers into the box keel for hydrographic surveying, fitting a Sound Velocity Probe and a Ferrybox for water sampling." [8]

Having trouble finding exact sensor fit but reference [10] is a nice piece on overhauling this type of ship. 

"Navigation and Communications;  S-band ARPA radar and X-band ARPA radar, Digital chart system ECDIS, Radio installation according to GMDSS – area A3, Satcom C, Fleet-77, Two V-Sat communication antennas Internal Communication ULSTEIN COM® common distribution of automatic telephone, data network and satellite TV antenna signal to all offices and cabins. Telephone system, separate PA, DECT." [10]

Possible, solid-state SharpEye radar transceivers, S-band radar, X-band radar [11]

### Mounts

4x Miniguns. [5]
5x General Purpose Machine Guns. [5]

### Aircraft & Docking Facilities

Helicopter: 

- 1x Pad (Medium Aircraft 12.1-18m Long).
- Small UAVs have been flown from Protector which can be used for aerial photography, surveying and plotting routes through sea ice. [8]

Boats and UUV's:

- Small work boats – including an 8.5m ramped work boat called the ‘Terra Nova’, and several inflatable and rigid inflatable motor boats. [1]
- 1X Survey Motor Boat. [5] 10.5m Survey Motor Boat (SMB) James Caird IV carried by Protector has a crew of 5 and is fitted with multibeam sonar. Constructed by Mustang Marine, she has 7 watertight compartments giving her a high margin of safety in case of damage. The wheelhouse and space behind for survey recording equipment is insulated and heated for efficient work in the cold environment. She is designed to operate away from the ship for up to 16 hours a day. [8] 
_**Could probably rename and use #3405 SMB 1006 Fantome, Australia, Navy.**_
- 1X Ramped workboat (Terra Nova) a steel hulled fast rescue craft (FRC). [8]
-  2x Pacific 24 RIBs and various inflatable dinghies. [8], [9]

Heavy lifting capability:

- With 2 x cranes capable of lifting a huge 60 tonnes of stores and equipment [1].

Cargo: 

- 3x Holds - Total Capacity 3300 m3. [6]
- 3x Holds - Total Capacity 710 m3. [6]
- Workdeck - 780 m3. [6]
- Container Capacity (20') - 90 Containers. [6] 

### Comms/Datalinks

"STS Defence was tasked with providing the platform with a full military HF/VHF/UHF ICS25 communications capability. The design solution had to be physically and seamlessly integrated into the platform as a fully operational system without any significant alterations to the vessel." [2]

### Comments

Capabilities:

- 0.5m The thickness of ice her hull glides through [1].
- Undertaking hydrographic surveys of the area to improve the safety of navigation [1].
- Providing support to UK and foreign research stations [1].
- Assisting the British Antarctic Survey [1].
- Super manoeuvrable, "There are also two bow and two stern thrusters controlled by a dynamic positioning system capable of holding the ship precisely in place using GPS in winds up to 80 knots. This gives her the ability to come alongside without reliance on tugs or to hold a position for loading operations. There is also a drop-down retractable azimuth thruster under the bow which could provide emergency slow speed propulsion in the event of damage to propellor or main engine failure." [8]
- "The hull was painted with Ecospeed. This environmentally friendly coating is specifically designed to protect the hull from the impacts of ice and is reinforced with glass flake resin so stays bonded to the hull plates as they flex and bend under pressure and impact." [8]

### Sources

[1]   https://www.royalnavy.mod.uk/our-organisation/the-fighting-arms/surface-fleet/survey/antarctic-patrol-ship/hms-protector
[2]   https://www.sts-defence.com/case-studies/hms-protector/
[3]   https://military-history.fandom.com/wiki/HMS_Protector_(A173)
[4]   https://www.multi-maritime.no/hms-protector
[5]   https://en.wikipedia.org/wiki/HMS_Protector_(A173)#cite_note-Steve_Bush_2014-6
[6]   https://web.archive.org/web/20110724181601/http://www.multi-maritime.no/Portals/87/filer/polarbjorn.pdf
[7]   https://www.engineeringtoolbox.com/fuels-densities-specific-volumes-d_166.html
[8]   https://www.navylookout.com/in-focus-hms-protector-the-royal-navys-antarctic-patrol-ship/
[9]   https://www.baesystems.com/en-uk/product/pacific-24
[10] https://www.thinkdefence.co.uk/a-ship-that-still-isnt-a-frigate/
[11] https://ukdefencejournal.org.uk/3560-2/

**Comment by Jkryos** [comment]
Added DB3K 501.
