### ISSUE TITLE
Laser effects

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4010]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3566 and more

### Summary of Changes

Not sure if this is new information but  will sent it anyway. Maybe this helps to classify laser effects. This was a nice sumup:

🔸5-15kW: UAS Group 1 & 2 defeat
🔸20kW: UAS Group 1, 2 & 3 defeat
🔸50-60kW: UAS Group 1,2 & 3 ➕ RAM & some CM
🔸100-300kW: LR Rockets & Cruise Missiles
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/a60287fb-ab21-4656-b42b-d3129f129512)

60kW begins to have an effect on Cruise missiles. Lockheed has demonstrated that recently. 100-300kW class is where you want to be for higher speed rockets, and high performing cruise missiles. Both the Army & Navy are working to field that class.
60kW+ (scalable to 120kW) [#AEGIS](https://twitter.com/hashtag/AEGIS?src=hashtag_click) integrated, operationally deployed High Energy Laser weapon system. [#HELIOS](https://twitter.com/hashtag/HELIOS?src=hashtag_click).
Also against Fast Inshore Attac Crafts
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/1641ac90-d5dd-4438-8ccf-12579efea329)

[#LLD](https://twitter.com/hashtag/LLD?src=hashtag_click) [#HELIOS](https://twitter.com/hashtag/HELIOS?src=hashtag_click) (60kw) [#DEIMOS](https://twitter.com/hashtag/DEIMOS?src=hashtag_click) (50kW) & [#VALKYRIE](https://twitter.com/hashtag/VALKYRIE?src=hashtag_click) (300kW) firmly establish Lockheed Martin as one of the world's leading suppliers of Solid State-High Energy Laser WS. The company is also working on tactical airborne Laser systems for near-term testing with the US Air Force.

To be clear, these are operational requirements balancing things like effect on system, dwell time, range etc. We have demonstrated CRAM even with 5 and 10kW systems. The US Army is now fielding 50kW DE-MSHORAD to support G 1-3 & Mortar defeat capability for maneuver forces.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/9d57f0ce-0ff5-4425-a1b5-7b87d7049fc9)

Below is an example of early SSL testing against  a rocket at very short range (1-4 km) using a 10kW HEL. We've demonstrated similar effects against Cruise Missiles using 60kW HEL (LLD) though US Army (and Navy) is fielding 300kW systems for that need.

US Army's DE-Maneuver [#SHORAD](https://twitter.com/hashtag/SHORAD?src=hashtag_click) & IFPC - High Energy Laser efforts are currently testing 4 50kW and fabricating 4 300kW class lasers to support the CRAM, C-UAS, and Counter Cruise Missile missions. For reference, 👇 a 📹 of 10kW HEL tested in 2013 against  rockets at 1-4 km.
https://twitter.com/i/status/1663241997971509248

### Sources

[
](https://twitter.com/AirPowerNEW1/status/1726587727758627172)
https://twitter.com/AirPowerNEW1/status/1726590123826135220
https://twitter.com/AirPowerNEW1/status/1726591183311544372
https://twitter.com/AirPowerNEW1/status/1678048589774475266
https://twitter.com/AirPowerNEW1/status/1663241997971509248

**Comment by PygmalionOfCyprus** [comment]
Very useful. This isn't really something I can deal with DB-side, this would have to be a sim-side change, but I'll put it in my back pocket for when we improve lasers like we've improved HPMs.
