### ISSUE TITLE
Ship #2645 - F 77 Te Kaha [Anzac] (New Zealand - 2022) Adjust CAMM Sea Ceptor from 32 to 20. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4011]
### DB Selector

DB3K

### Affected DBID(s)

Ship #2645 - F 77 Te Kaha [Anzac] (New Zealand - 2022)

### Summary of Changes

1x Mk41 VLS [8 Cells] 8 2 Medium  32x Sea Ceptor [CAMM(M)] - not fitted.

Appears a bespoke "Mushroom farm" with 20 angled Sea Ceptor cell arrangement is in use. 
https://x.com/D__Mitch/status/1520775212102569985?s=20

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99494755/f4246271-f188-4579-a903-1ec00840ca34)

### Sources

https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2FD__Mitch%2Fstatus%2F1520775212102569985&psig=AOvVaw0JJi2STiITUCBpW01FMb1q&ust=1700859453410000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLCE8r-B24IDFQAAAAAdAAAAABAE
Image attached 

https://x.com/D__Mitch/status/1520775212102569985?s=20

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
