### ISSUE TITLE
Cyprus, Serbia, Mi-35P

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4012]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4625 Mi-35P Hind (Nigeria 2000)

### Hypothetical

No

### Name

 Mi-35P Hind

### Country

Cyprus, Serbia

### Service

Air Force / Army (Cyprus/Serbia)

### In Commission

2001/2023 (Cyprus/Serbia)

### Number in Service

12x, 1 destroyed / 11x  (Cyprus/Serbia)

### Sources

[Serbia buys Cypriot helicopter gunships to bolster air force | Reuters](https://www.reuters.com/business/aerospace-defense/serbia-buys-cypriot-helicopter-gunships-bolster-air-force-2023-11-23/)
Trade Registers  SIPRI
[Cyprus Mi-35s for sale - Scramble](https://www.reuters.com/business/aerospace-defense/serbia-buys-cypriot-helicopter-gunships-bolster-air-force-2023-11-23/)
[Cypriot Gunships - 450 Squadron | Dirk Jan de Ridder](https://www.ridder.aero/article/cypriot-gunships-450-squadron/)
https://irp.cdn-website.com/02989753/files/uploaded/Cyprus.pdf

As for Cyprus' "Air Force"
http://www.army.gov.cy/index.php/el/aeroporias
http://www.army.gov.cy/index.php/el/dioikisi-aeroporias
https://www.jetphotos.com/photo/11011316

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/1281c315-e58b-4967-aa06-c382c7b4638d)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
