### ISSUE TITLE
cmano-db.com - db v. 502 / F 246 Salihreis [Meko 200TN Track IIB] / SMART-S Mk2

### ISSUE THREAD

**Issue by anlgzl** [PygmalionOfCyprus/cmo-db-requests#4018]
### DB Selector

DB3K

### Affected DBID(s)

ship 4440

### Summary of Changes

Should "F 246 Salihr"eis [Meko 200TN Track IIB] - 2021, MLU" has "SMART-S Mk2" ?

### Sources

https://turkishnavy.net/2023/11/18/a-closer-look-to-the-barbaros-mlu-project/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
