### ISSUE TITLE
Ukraine, M1A1 SA Abrams (Ground Unit)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4019]
### DB Selector

DB3K

### DBID to Copy

Ground unit 57 M1A1 SA Abrams MBT (United States - 2008)

### Hypothetical

No

### Name

M1A1 SA Abrams MBT

### Country

Ukraine

### Service

Army

### In Commission

2023

### Number in Service

31x

### Sources

[Ukraine’s M-1 Abrams Tanks Are ‘Situational Awareness’ Models | Forbes](https://www.forbes.com/sites/davidaxe/2023/11/25/ukraines-m-1-abrams-tanks-are-situational-awareness-models-not-the-best-m-1s-but-available-in-large-numbers/?sh=30a330675f31)
[American-Made Abrams Tanks Arrive in Ukraine, U.S. Officials Say - The New York Times](https://www.nytimes.com/2023/09/25/world/europe/us-abrams-tanks-ukraine.html)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/6061bf89-7d0e-4b4a-a861-d9c2c8106ac0)

https://twitter.com/Osinttechnical/status/1728721159749820444/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
