### ISSUE TITLE
Add 78 Deylaman [Moudge-class] (Damavand-2) of Iranian Navy

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#4021]
### DB Selector

DB3K

### DBID to Copy

Ship 4408

### Hypothetical

No

### Name

78 Deylaman [Moudge-class] (Damavand-2)

### Country

Iran

### Service

Navy

### In Commission

2023

### Sensors

- Remove ASR(Sensor 6994) and replace with new Eagle Eye (Chesme Oghab) S-band AESA. Probably can guide Sayyad-2/3 missile
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/42fd1f5d-471f-48cc-a5c0-72a11a30d805)
- Add generic gun director (TV/IIR & Laser Rangefinder, prolly 3rd Gen) and this have to be able to direct both 76mm Fajr(Mount 3835) and 30mm Kamand CIWS (Mount 3635)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/ae95f7cf-123f-45ef-9bf2-7a6a1610f7cc)

### Mounts

- Replace 4x CM-200 launcher(Mount 2508) with 8x launcher and add 30mm Kamand CIWS (Mount 3635)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/c1735c77-10fc-4f0c-82d7-a3c71446a0f8)
- Replace 20mm gun(Mount 1399) with ZU-23 23mm Single gun( Mount 3650)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/79a3cb6b-76d2-481a-bcf0-45e01956d9d9)

### Other Changes

- CMS is probably CS Gen 6 (2001-2029) by now(?)

### Sources

- https://twitter.com/IranDefense/status/1729098228816089314
- https://twitter.com/IranDefense/status/1729098243181551784
- https://twitter.com/IranMilitaryNet/status/1728397602398281896
- https://twitter.com/AmirIGM/status/1281938550024556546

**Comment by claudejdev** [comment]
A promotional video on that ship
https://www.youtube.com/watch?v=OFOOaCTgt3Y

**Comment by Jkryos** [comment]
Added DB3K 507.
