### ISSUE TITLE
Inconsistent loadout for #6454 - Cessna 206 Stationair

### ISSUE THREAD

**Issue by ShelLuser** [PygmalionOfCyprus/cmo-db-requests#4022]
### DB Selector

DB3K

### Affected DBID(s)

Utility 6454

### Summary of Changes

This is a follow up from [a post on Steam](https://steamcommunity.com/app/1076160/discussions/0/4032472980090536986/) where Dimitris requested me to add this to the tracker.

The default loadout of this aircraft is either:
- Cargo, 1 ton
- 5x Passenger
These loadouts should be roughly the same, but it seems a bit far-fetched to me that 5 human passengers would weigh around 1 ton.

Ergo my suggestion: change the description of the cargo into, maybe, 0,5 ton or even 0,4 ton. Nothing would really change, but the descriptions would make a lot more sense.

Hope this could help!

### Sources

https://steamcommunity.com/app/1076160/discussions/0/4032472980090536986/

As well as database entry #6454.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
