### ISSUE TITLE
Ukraine, Neptun Missile name mismatch. (+ Facility not Hypothetical)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4028]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3988 RK-360MC Neptun [Mod. Kh-35U]

### Summary of Changes

While the facility 3537 SSM Bty (RK-360MC Neptun) is named right, the missile itself is reportedly named "R-360 Neptun"
Note: that facility shouldn't be flagged as Hypothetical. As seen on TV... 

DataWeapon
ID | Name
--- | ---
3988  | R-360 Neptun [Mod. Kh-35U]

### Sources

[Ukrainian Defense Review #2 [April-June 2019] by Defense Express - Issuu](https://issuu.com/ukrainian_defense_review/docs/udr2)
[Нептун (крилата ракета) — Вікіпедія](https://uk.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BF%D1%82%D1%83%D0%BD_(%D0%BA%D1%80%D0%B8%D0%BB%D0%B0%D1%82%D0%B0_%D1%80%D0%B0%D0%BA%D0%B5%D1%82%D0%B0))
[Нептун (береговий ракетний комплекс) — Вікіпедія](https://uk.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BF%D1%82%D1%83%D0%BD_(%D0%B1%D0%B5%D1%80%D0%B5%D0%B3%D0%BE%D0%B2%D0%B8%D0%B9_%D1%80%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D0%B8%D0%B9_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81))

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/71448e71-8fd7-41f7-be31-4d009d17c0ed)

**Comment by tbrandon517** [comment]
Should there be a separate missile variant with land attack capabilities or is it the same missile?

https://www.thedrive.com/the-war-zone/ukraine-now-using-land-attack-neptune-anti-ship-missile-variant

**Comment by claudejdev** [comment]
Personally, I didn't find enough data points to feel confident enough in formulating what I deem to be a properly documented suggestion for inclusion.

**Comment by tbrandon517** [comment]
> Hey there @tbrandon517 Personally, I didn't find enough data to post a properly documented suggestion. Have you?

Not really. I have been in the same boat. Was curious if anyone else had.

**Comment by PygmalionOfCyprus** [comment]
Name modified. The facility is marked as hypothetical not because the missile isn't in service, but rather because the facility is modelled after the proposed battalion layout and it's not clear that they actually built enough to put full battalions in service or that the ultimate batt layout looked as initially proposed.
