### ISSUE TITLE
Add Canadian TPS-77 eh

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4029]
### DB Selector

DB3K

### DBID to Copy

Facility 1451

### Hypothetical

No

### Name

Radar (AN/TPS-77)

### Country

Canada

### Service

Airforce

### In Commission

2023

### Number in Service

x3

### Other Changes

Should be C-130 transportable

### Sources

https://twitter.com/RCAF_ARC/status/1729228605018800271
Check out General Teeth. Bad Photo alignment on site..hehe!
https://skiesmag.com/features/aligning-air-force-2035-exclusive-qa-lgen-eric-kenny/

**Comment by PygmalionOfCyprus** [comment]
Handled 507. Smeared a bit of poutine on it too for good measure.
