### ISSUE TITLE
KJ-200A #2487 ESM and IFR Update

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#403]
### DB Selector

DB3K

### DBID to Copy

Aircraft #2487

### Hypothetical

No

### Name

KJ-200A

### Country

China

### Service

PLAAF

### In Commission

2020

### Sensors

KJ-200s being upgraded.

Refueling Probe Added
ESM Arrays on both Sides of aircraft. Looks like same on KJ-500

### Loadout Options

Same as original

### Other Changes

You might want to adjust the ESM arrays to 2 port and starboard arcs similar to what the AEW radars is. These aircraft have to be arrayed side toward what they're looking at.

Doesn't look like the early model had advanced long ranged ESM. Take at the picture in the last link.

### Sources

https://twitter.com/RupprechtDeino/status/1497343967813414919
https://twitter.com/HenriKenhmann/status/1497451360408637440
https://twitter.com/CN_military_21/status/1497562732123414531
https://twitter.com/mirandamu/status/1439530380655161351

**Comment by PygmalionOfCyprus** [comment]
Added 494.
