### ISSUE TITLE
Add out of service date of 2023 to Taiwanese F-5E and F-5F

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4030]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 138,3603

### Summary of Changes

Add an out-of-service date of 2023 for Taiwanese F-5E and F-5F. RF-5E's will be retained until replaced.

### Sources

https://twitter.com/CollinSLKoh/status/1729788643760370078
https://twitter.com/stoa1984/status/1522891063618379776
https://twitter.com/Aviation_Intel/status/1721995009246052496

**Comment by bostonmyk** [comment]
https://www.scramble.nl/military-news/rocaf-tiger-iis-to-be-decommissioned

**Comment by Jkryos** [comment]
Updated DB3K 506.
