### ISSUE TITLE
Commercial Aircraft Corporation of China Ltd C919

### ISSUE THREAD

**Issue by 1103CA** [PygmalionOfCyprus/cmo-db-requests#4033]
### DB Selector

DB3K

### Hypothetical

No

### Name

Comac C919

### Country

Commercial

### In Commission

2023-

### Number in Service

2x

### Length (m)

38.9 m

### Wingspan (m)

35.8 m

### Height (m)

11.95 m

### Empty Weight (kg)

45,700 kg

### Maximum Takeoff Weight (MTOW) (kg)

78,900 kg

### Payload Weight (kg)

18,900 kg

### Crew

2

### Propulsion

2x CFM LEAP-1C

### Rate of Climb (ft/min)

2800ft/min

### Service Ceiling (ft)

39700 ft

### Military/Afterburner Speed (kt)

520

### Cruise Speed (kt)

480

### Supercruise

Yes

### Ferry Range (nm)

3011nm

### Takeoff / Landing Distance (m)

2052/1778

### Sensors

1x Generic Doppler Navigation/Weather
1xMk1 Eyeball

### Mounts

Passenger

### Loadout Options

（Ferry）
Passengers，190x（Cargo，Transport）

### Comms/Datalinks

UHF/VHF Radio（Unscure）

### Aircraft Codes

Fly-by-Wire, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Sources

https://en.wikipedia.org/wiki/Comac_C919
https://baijiahao.baidu.com/s?id=1745432971081514030&wfr=spider&for=pc
http://www.comac.cc/cpyzr/c919/
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/151608074/edd160be-034e-428a-b7a1-d7c4299ca87d)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/151608074/cf4a08b9-6164-4181-b788-217ea95e0a03)

**Comment by PygmalionOfCyprus** [comment]
We're not gonna do commercial airliners as tickets but this will probably get added at some point if we do a pass of newer commercial aircraft. Probably worth doing.
