### ISSUE TITLE
Add 2023 Out of service date for Norwegian Sea Kings 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4034]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 249, 929

### Summary of Changes

Add an out of service date of 2023out-of-service

### Sources

https://www.scramble.nl/military-news/goodbye-to-royal-norwegian-air-force-sea-king
https://defensetalks.com/royal-norwegian-air-force-to-retire-sea-king-helicopters/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
