### ISSUE TITLE
Add Chinese MSA and Nigerian Navy AR-500B Variant

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4036]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4716

### Hypothetical

No

### Name

AR-500B

### Country

China, Nigeria

### Service

China Maritime Safety Administration, Nigerian Navy

### In Commission

2024, 2023

### Number in Service

Few. x4

### Sensors

Generic FLIR and TV Camera 3rd Generation

### Sources

https://twitter.com/RupprechtDeino/status/1729762560440693058
https://www.avionews.it/en/item/1255224-china-first-drones-in-service-to-patrol-the-sea.html

Nigeria
https://airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/september/8722-nigerian-navy-receives-chinese-avic-ar-500b-unmanned-aerial-vehicles.html
https://twitter.com/Jakepor21/status/1573608435849072642

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
