### ISSUE TITLE
Add Chinese, Pakistani and SH-15 Arty Bty (155mm/52 PCL-181 Self-Propelled Howitzer x 6) Facility and Ground Unit 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4039]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

(155mm/52 PCL-181/SH-15 Self-Propelled Howitzer x 6)

### Facility Type

Radar

### Country

China, Pakistan

### Service

PLA, Pakistani Army

### In Commission

China 2018, Pakistan 2022, Ethiopia 2023

### Number in Service

Pakistan and China have hundreds, Ethiopia 32

### Crew

6

### Dispersion Radius (m)

80

### Sensors

Mk.1 Eyeball unless you're me than Mk.075 Eyeball

### Mounts

 Can probably base the mount and ammo on the PZL-05 (facility #2095). 
Rate of Fire is 4-6 rounds of minutes
has digital fire control

### Comments

Weight is 22 tons and can travel at 55 mph (90kph)

### Sources

https://www.militarytoday.com/artillery/pcl_181.htm
https://en.wikipedia.org/wiki/PCL-181
https://twitter.com/zhao_dashuai/status/1640278496118439937
https://twitter.com/jesusfroman/status/1681565661082861568
https://twitter.com/Jakepor21/status/1413853969995210754
https://twitter.com/JanesINTEL/status/1403238088118308865

Guided shell China
https://twitter.com/Nickatgreat1220/status/1564538925619695617
https://twitter.com/wenluomo/status/1534381561784590336

Pakistan
https://www.janes.com/defence-news/news-detail/chinas-norinco-delivers-sh-15-howitzers-to-pakistan
https://twitter.com/ForumStrategic/status/1507830810816229376
https://twitter.com/ForumStrategic/status/1583757709312421889

Ethiopia:
https://twitter.com/mahmouedgamal44/status/1621912438626029569/photo/3
https://www.armyrecognition.com/defense_news_november_2023_global_security_army_industry/ethiopia_showcases_chinese-made_sh-15_155mm_self-propelled_howitzers.html
https://twitter.com/CTNSIS/status/1617462534239571974

**Comment by bostonmyk** [comment]
Chinese Guided Shells for 155mm seem to be GP1 and GP6. GP1 is a Krasnopol clone (Chinese bought Krasnopol in the 90s). GP6 seems to be an improved version.
https://www.militarytoday.com/artillery/krasnopol.htm
https://en.topwar.ru/67454-upravlyaemye-artilleriyskie-snaryady-semeystva-gp155-kitay.html
https://en.defence-ua.com/events/russias_allies_in_libya_got_shelled_by_the_chinese_copy_of_krasnopol_rounds_but_the_supplier_is_unknown-6400.html

**Comment by bostonmyk** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4483

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
