### ISSUE TITLE
Add JG-500 (K/YJG500B/GB500/GB1) LGB to Chinese J-10, JH-7

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4041]
### DB Selector

DB3K

### User(s)

Aircraft 5596, 4905, 4617, 2057,5259,5521

### Weapons Carried

Same as similar LT-2 loadouts

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Ok unlike the US (capitilists huh!), our Chinese buddies compete with each other internally (socialists huh!) So builter of LT, GB and YJ weapons can complete etc within the same classes of weapons.

JG-500 is a second-generation LGB.  IOC 2017. The bomb's weight is 564kg, length 3530mm, diameter 377mm, range>10km, CEP≤6.5m, and warhead 450kg. Maybe Reduce CEP to 2-3m over LT series. 

### Sources

General
https://www.janes.com/defence-news/news-detail/update-image-suggests-plaaf-is-operating-gb-100-precision-guided-bomb
https://chinese-military-aviation.blogspot.com/p/missiles-iii.html
https://twitter.com/RupprechtDeino/status/1193929829076348928

J-10C

https://2.bp.blogspot.com/-gBWXowyyeLg/WalGX9qxcuI/AAAAAAAAVFY/_KRR-gPAZT0Wntx_fL0fm9A3kbCUgVnJwCKgBGAs/s1600/J-10C_TG500.jpg
https://twitter.com/RupprechtDeino/status/1194128507334537216

JH-7
https://3.bp.blogspot.com/-RPcAqSf2Dbg/WVtfWyIKjJI/AAAAAAAATyM/MOKLFim74e81_Hxov85xB4P42hO18ZSIQCKgBGAs/s1600/JH-7A_LGB.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Also added the K/JDC-03A pod.
