### ISSUE TITLE
Add P-8a Poseidon Canada

### ISSUE THREAD

**Issue by Seaside232** [PygmalionOfCyprus/cmo-db-requests#4043]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4427 (DB3K)

### Hypothetical

Yes

### Name

P-8a Poseidon Canada

### Country

Canada

### Service

RCAF

### In Commission

2026-present

### Number in Service

16 to be purchased

### Other Changes

Sounds like they will have Standard U.S. equipment.

### Sources

https://www.canada.ca/en/department-national-defence/news/2023/11/canada-purchasing-up-to-16-p-8a-poseidon-multi-mission-aircraft-for-the-royal-canadian-air-force.html

**Comment by FrangibleCover** [comment]
Duplicate #3533, and in since DB502 as Aircraft 6779
