### ISSUE TITLE
China, PLAAF, J-16 Flying Shark, mix loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4044]
### DB Selector

DB3K

### User(s)

PLAAF J-16 2018

### Weapons Carried

1. PL-21, PL-15, PL-10, DECM Pod: 
2x PL-21
4x PL-15
4x PL-10
1x KG-600 DECM Pod

2. PL-21, PL-15, PL-12, PL-10, DECM Pod:
1x PL-21
4x PL-15
1x PL-12
4x PL-10
1x KG-600 DECM Pod

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

This should be linked with #2204

### Sources

Obviously the J-16 on the far right has two pylons for PL-17
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/fe649817-3f19-49c4-9c68-9c0295f72a95)
https://www.sinodefenceforum.com/t/china-flanker-thread-iii-land-based-exclude-j-15.9002/page-90
https://twitter.com/RupprechtDeino/status/1730920121927925788
https://www.thedrive.com/the-war-zone/massive-pl-17-air-to-air-missile-seen-on-chinese-j-16-fighters

**Comment by PygmalionOfCyprus** [comment]
Handled 506 (using newly-fixed PL-17 instead of hypo PL-21)
