### ISSUE TITLE
China, PLAAF, PL-21 VLRAAM, update

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4045]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4110

### Summary of Changes

1. Rename it as PL-17
2. Add "Lock-On After Launch (LOAL) - CEC-Capable" to its properties. For this very long range air-to-air missile, it can only achieve its effectiveness through  CEC.

Linked with #2903 or just add PL-21 command link to aircraft 5420 6004

### Sources

https://en.wikipedia.org/wiki/PL-17
https://twitter.com/RickJoe_PLA/status/1731070266237993079

**Comment by Matharox** [comment]
Pl-17 and PL-21 are actually two separate missiles. So Pl-21 can be used as a placeholder for Pl-17 for now or Pl-17 can be added separately.

**Comment by LuigiP57** [comment]
PL-21 see https://en.wikipedia.org/wiki/PL-21

**Comment by PygmalionOfCyprus** [comment]
Handled 506. Old "PL-21" entry is now the PL-17. New hypo PL-21 entry was created with a ramjet engine and stuff. Both weapons get generic China CEC and LOAL.
