### ISSUE TITLE
AIM-260 range issue, "mile" rather than "nautical mile"

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4046]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3567

### Summary of Changes

Well, in the process of collecting and comparing PL-17 data today, I found that the distance unit of AIM-260 may have been converted wrong. Reliable sources indicate that the AIM-260's range should be 120 miles rather than the 120 nautical miles in the database. I suspect that the conversion of units may have been mistaken when the database was created.

Therefore, based on reasonable considerations, the maximum range of the AIM-260 in the database should be modified to 108nm (the same level as the PL-15).

In addition, I also recommend upgrading the active radar seeker technology (currently the early 2010s tech level) and year of enter service (2026 may be reasonable) at the same time.

### Sources

https://en.wikipedia.org/wiki/AIM-260_JATM
https://www.globalsecurity.org/military/systems/munitions/lrew.htm

**Comment by tbrandon517** [comment]
Not know what sources exactly the DB used I'll defer to them to decide to change it or leave it alone. At least until the USAF PR team touts the next longest range record shot.

**Comment by claudejdev** [comment]
If that can help
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/0f7f4233-2d23-4a91-b9c1-3be2abf0b7d5)

**Comment by PygmalionOfCyprus** [comment]
120 was put in as sort of a PL-15 (108nmi) + wiggle room since presumably the 260 isn't going for the bare minimum. I'm not gonna bother fiddling with it until we get something a little more concrete or we're just going to be chasing ghosts.
