### ISSUE TITLE
Proximity fuze update pass DB3K

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#4050]
### DB Selector

DB3K

### Affected DBID(s)

Weapons: 51, 52, 53, 133, 134, 242, 371, 457, 516, 578, 642, 647, 681, 718, 829, 861, 863, 897, 945, 946, 961, 964, 1000, 1050, 1128, 1129, 1150, 1199, 1691, 1755, 1756, 1872, 1873, 1896, 2003, 2045, 2053, 2109, 2695, 2768, 2771, 2780, 2783, 2825, 2852, 2853, 2857, 2858, 2891, 2970, 3116, 3127, 3128, 3151, 3152, 3166, 3167, 3168, 3169, 3207, 3220, 3221, 3316, 3474, 3502, 3511, 3567, 3596, 3610, 3664, 3692, 3735, 3739, 3774, 3861, 3862, 3890, 3939, 3950, 3952, 4019, 4032, 4041, 4042, 4290, 4342, 12, 15, 157, 273, 417, 446, 476, 699, 831, 844, 854, 855, 878, 925, 926, 927, 994, 1052, 1113, 1116, 1194, 1257, 1310, 1383, 2056, 2103, 2104, 2108, 2767, 2770, 2915, 3105, 3126, 3138, 3139, 3140, 3141, 3252, 3357, 3413, 3443, 3444, 3536, 3541, 3661, 3714, 3763, 3767, 3772, 3780, 3781, 3842, 3896, 3935, 4078, 4079, 4090, 4110, 4129, 4138, 4295, 4323, 4362, 835, 29, 125, 352, 424, 443, 464, 598, 653, 655, 656, 657, 864, 888, 890, 915, 1021, 1127, 1151, 1152, 1195, 1398, 1401, 1660, 1675, 1749, 1878, 2580, 2603, 2763, 3301, 3310, 3362, 3392, 3764, 3765, 3820, 3869, 3986, 4087, 4251, 13, 14, 71, 112, 182, 183, 234, 237, 302, 390, 391, 444, 511, 654, 659, 659, 660, 891, 917, 931, 1003, 1101, 1102, 1112, 1144, 1145, 1225, 1275, 1319, 1400, 1426, 1427, 1640, 1661, 1690, 1747, 1750, 1752, 1754, 1760, 1767, 1768, 1803, 1826, 1836, 1857, 1858, 1897, 1899, 1900, 1901, 2002, 2046, 2047, 2048, 2049, 2054, 2055, 2064, 2182, 2353, 2362, 2365, 2369, 2449, 2585, 2586, 2690, 2784, 2800, 2802, 2802, 2803, 2804, 2805, 2903, 3123, 3150, 3211, 3383, 3442, 3513, 3693, 3831, 3893, 3941, 3983, 4056, 4159, 4281, 98, 120, 123, 124, 153, 164, 403, 425, 437, 438, 503, 515, 648, 652, 661, 673, 736, 946, 860, 996, 1001, 1045, 1046, 1053, 1097, 1147, 1156, 1313, 1422, 1424, 1582, 1626, 1641, 1662, 1668, 1674, 1687, 1693, 1828, 1831, 1879, 2043, 2097, 2241, 2870, 3395, 3436, 3625, 3779, 3965, 4126, 4127, 4196, 4252, 5, 26, 147, 148, 150, 151, 152, 505, 674, 723, 727, 747, 789, 949, 954, 1164, 1312, 1314, 1315, 1316, 1337, 1642, 1663, 1745, 1855, 2363, 2740, 2940, 3257, 3277, 3356, 3447, 3667, 4075, 4103, 4104, 4234, 121, 203, 329, 542, 574, 618, 675, 677, 730, 748, 877, 970, 1069, 1104, 1324, 1327, 1330, 1416, 1669, 1720, 1746, 1822, 1834, 1850, 2148, 2349, 2350, 2371, 3075, 3224, 3314, 3428, 3429, 3898, 3899, 4014, 4160, 406, 725, 783, 1196, 1238, 1583, 2385, 3000, 111, 181, 431, 445, 631, 672, 740, 757, 759, 790, 850, 1122, 1193, 1317, 1420, 1474, 1743, 1753, 1757, 1821, 1823, 1827, 1829, 1851, 1902, 2346, 2347, 2348, 2351, 2649, 405, 407, 512, 885, 1055, 1109, 1153, 1154, 1163, 1417, 1604, 1609, 1627, 1744, 1824, 2074, 2158, 2159, 2160, 2161, 2345, 2361, 2364, 2366, 2367, 2368, 2672, 2957, 3641, 4197, 4198, 396, 402, 886, 887, 1047, 1849, 1322, 1349, 1628, 1825, 1926, 2100, 2333, 2337, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 1141, 1142, 1419, 2386, 729, 1833, 2334, 3355, 916, 2330, 2331, 2332, 2335, 2336, 3354, 2898, 166, 2396

### Summary of Changes

I went through EVERY missile I could find with any anti-air pK at all in a database viewer and looked up whether it has a prox fuze or not. While some weapons in the DB have proximity fuzes, it's very few, so instead of working to check them all for preexisting fuzes (being on a laptop that melts if I run Command for too long) I've listed every AAW weapon I can verify as having a prox fuze or extremely likely to have one. Some, like MANPADS, were also easy to exclude as only a few of those have prox fuzes. Hit-to-kill weapons, apart from the very odd MIM-104F, have been excluded. Mainly, since nearly every anti-air weapon has a proximity fuze, it's frankly easier to rule out the ones that don't than rule in the ones that do. Nuclear SAMs and AAMs are included.

Command guided weapons are marked as proximity fuzed because that's basically how it works. Some guns are included that may be combination fuzed, and some missiles may be included that are already proximity fuzed; bug report already submitted for the combo fuze not increasing pK.

### Sources

For most modern missiles of appreciable size, like the Meteor and of course AMRAAM, common sense is in use, as well as for modern dogfight missiles like the Python 5 and Magic 2. I've done my best to find sources, but fuzing is a relatively minor thing and very few sources comment on it.

RIM-116: https://www.designation-systems.net/dusrm/m-116.html
MIM-104F: https://web.archive.org/web/20141016125635/http://www.msl.army.mil/Documents/peoWeaponSystems.pdf (PAC-3 is hit to kill but DOES have a proximity-fuzed kinetic warhead)
Mistral: https://www.mbda-systems.com/product/mistral-atam/ (does marketing documentation count?)
AIM-9: https://ausairpower.net/TE-Sidewinder-94.html (even the 9B had a prox fuze!)

Ask for any specific sources and I can try to root them out.

**Comment by PygmalionOfCyprus** [comment]
Fuzes currently only apply for AAA. Missiles are assumed to use prox. fuzes except when explicitely specified (e.g. by getting a kinetic warhead).
