### ISSUE TITLE
Copy Aircraft  #4013 - KC-390 Millennium (Brazil - 2018) for Netherlands and ROK AF Aircraft rename just C-390M (NETHERLANDS  - 2026)&(ROK - 2026)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4052]
### DB Selector

DB3K

### DBID to Copy

Aircraft  #4013 - KC-390 Millennium (Brazil - 2018)

### Hypothetical

No

### Name

Aircraft  #4013 - C-390M Millennium (Netherlands - 2024) C-390M Millenium (ROK - 2025)

### Country

Netherlands / ROK

### Service

AF both NL and ROK

### In Commission

2026

### Number in Service

5 NL ? ROK

### Sensors

Likely similar defensive aids suite to late model C-130 DIRM DECM chaff flares ETC

### Mounts

Chaff Flares

### Loadout Options

As copy - possibly MEDIVAC specific loadout as flying hospital?

### Other Changes

None

### Sources

https://theaviationist.com/2022/06/21/c-390-for-rnlaf/

https://www.shephardmedia.com/news/air-warfare/embraer-c-390-triumphs-in-south-koreas-transport-aircraft-competition/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
