### ISSUE TITLE
Add Indonesian AF H225M 2014

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4053]
### DB Selector

DB3K

### DBID to Copy

aircraft 5130

### Hypothetical

No

### Name

H225M

### Country

Indonesia

### Service

Air Force

### In Commission

2024

### Number in Service

x14

### Sensors

same

### Mounts

same

### Loadout Options

same

### Other Changes

Received 6 starting in 2014 for SAR. Just received 8 more for transport

### Sources

https://www.airbus.com/en/newsroom/press-releases/2019-01-indonesian-air-force-places-order-for-eight-additional-h225ms
https://www.airforce-technology.com/projects/ec-725/?cf-view
https://abpic.co.uk/pictures/view/1818800
https://twitter.com/officialptdi/status/1730521873417634162
https://twitter.com/Defence_IDA/status/1731671535038156881

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
