### ISSUE TITLE
Add Fab-250 Glide bomb to Glide Bomb loadout 32901

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4055]
### DB Selector

DB3K

### Affected DBID(s)

loadout 32901

### Summary of Changes

The glide bomb loadout has the standard 250 FAB instead of the glide bomb model.

### Sources

Caught it in a test

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
