### ISSUE TITLE
Reduce UMPK FAB-500M-62 loadouts to only 2, 4, 6 or 8 bombs

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4056]
### DB Selector

DB3K

### Affected DBID(s)

Loadout 32887,32888,32886,

### Summary of Changes

Social Media has only seen 2 and 4 bomb loadouts but nothing matching normal FAB-500 loads. Could be # of bomb kits they have or an engineering problem to be solved with the chunky design (uniquely Russian isn't it?).  Engineering stuff is bomb footprint or wiring. I'd reduce load-outs to 2,or 4  until there are pictures of 2 per pylon.

### Sources

https://twitter.com/GuyPlopsky/status/1732682660383006767
https://twitter.com/GuyPlopsky/status/1732723440963207626
https://twitter.com/GuyPlopsky/status/1732681048218312946
https://twitter.com/MrFrantarelli/status/1676556576956596224
Take a look at bomb chart in link below (8) 500 stations
https://www.thedrive.com/the-war-zone/russian-su-34-strike-fighter-bombed-one-of-its-own-cities

**Comment by TTZ32** [comment]
Russians are currently launching 4 per aircraft, atleast thats what i have video evidence of.

**Comment by bostonmyk** [comment]
4 bombs on SU-34

https://twitter.com/GuyPlopsky/status/1744293083477667866

**Comment by bostonmyk** [comment]
Another 4 bomb vid

https://twitter.com/MrFrantarelli/status/1751835293781565885

**Comment by bostonmyk** [comment]
4
https://twitter.com/GuyPlopsky/status/1761980688637759668

**Comment by bostonmyk** [comment]
Ok 4 bombs. I haven't seen over 4 yet. 

https://twitter.com/GuyPlopsky/status/1765996270173446331

**Comment by bostonmyk** [comment]
4 bombs
https://twitter.com/GuyPlopsky/status/1767088322063802414

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
