### ISSUE TITLE
Heidar-1/2 cruise missile`s surface target issue

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#4059]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4181, 4182

### Description of Problem

Both missiles have 0% PoH against surface target. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/cd2750ba-db7d-472a-93d7-96583738395e)

### Recommended Fix

Set the PoH against surface target similar to the one for land target.

**Comment by Huib18** [comment]
Weapon 4181 is the Heidar-1. This one is **without** senors and is therefore not capable of engaging a surface target.

![2104_orig](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/de36114b-dd4d-4bc7-929f-80ea9c351f84)
![GDFVG-yacAAI5L4](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/672f6ed4-40cf-4659-977e-022275107391)

![GDFVG-yacAAI5L4](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/bfcaf4f9-da3f-4f04-b704-e499499101ac)
[https://twitter.com/CENTCOM/status/1743268112018047314](url)

**Comment by Huib18** [comment]
The Heidar-2 on the other had has a variant without optical sensors
![3589660](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/8edb9714-a122-46fc-998d-37b610eaddfd)



...and one with EO or IR? 
![download](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/cc4f02ef-f592-48b2-b9e4-8fae6fce5d1b)
![FT1ghEvXwAAIgNf](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/63981ad1-3ca8-4adf-adc0-aeefcdf29c67)

These ones can be carried by the Bell-214 and Kaman-22 and probably have a capability against surface targets like ships.
The missile was also displayed next to a Fotros but has never been seen with one.
Maybe the wings of the missile will interfere with the landing gear. 
 
![fotros_181113_09-1529318497](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/d790c378-4980-4884-a0fd-3acfa1dd459e)
Fotros is doubtful. But whatever.
Please add the air platforms for the Heidar 2 and create one with sensors and one without. The one without will have more negative CEP.

This missile is bigger, has an inernal engine and the wings are placed differently. I could not find any technical data except that during an exercise a range of 30 km was achieved. But 200 km seems resaonable.
[https://twitter.com/KarimRa56178408/status/1718381295862984845](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Fixed the forgotten PoH, disentangled the Paveh/Heidar situation, added TEL for Paveh, and marked Fotros loadouts Hypo.
