### ISSUE TITLE
Update mount for PC 24 Karina [Guaiqueri Class, Avante 2200 Combatant] (Venezula - 2023)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4060]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Ship 4428

### Summary of Changes

OSINT Shows that the 35mm Millenium Gun has been replaced by a Zu-23-2 as seen on C-802 equipped ships.

Update mounts on the 2023 ship to match.

### Sources

http://www.hisutton.com/Venezuelan_Navy_2023.html

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/b068496a-9967-4c97-b945-c7079cf3bacf)

**Comment by trujillocorreo** [comment]
"Hello, there is a caveat to be made.

Only the PO-13 unit (ex PC-23) "Yekuana" had its 35 mm Millenium mount replaced by a Zu-23-2. Also, this unit does not have the SSM 2x4 C-802A mount. Therefore, the remaining two units, PO-11 (ex PC-21) "Guaquerí" and PO-14 "Kariña" (ex PC-24), retain the original Millenium mount plus the SSM 2x4 C-802A as reported in entry #4507.

Therefore, the #4428 database of the year 2023 referring to the Guaqueri Avante 2200 class of the Venezuelan navy would be as follows:
* PO-11 "Guaquerí" and PO-14 "Kariña" = Millenium 35mm cannon and SSM 2x4 C-802A mount.
* PO-13 "Yekuana" = ZU-23-2 cannon.

Regards"
![IMG_20230908_145635](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109195286/74336983-4e76-4293-a8d9-a2261107adea)

"In the photo, on the **right** is the **PO-13** (note the absence of the SSM mount between the chimney and the mast) with the **ZU-23-2** cannon, and on the **left** is the **PO-14** with the **Millenium 35mm** cannon." 😊

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
