### ISSUE TITLE
Capitán de Fragata David Eyama Angue Osa cargo type

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#4063]
### DB Selector

DB3K

### Affected DBID(s)

#3710

### Summary of Changes

The landing ship Capitán de Fragata David Eyama Angue Osa is currently limited to the cargo type 'personnel'. This means the ship can't load or unload any vehicles. The ship's design is apparently based on the Alligator class and seems to have bow and stern ramps/doors. Although I haven't been able to find any pictures of vehicles being loaded/unloaded, based on the ship's design history and the presence of the doors/ramps I would propose changing the cargo type to 'Large cargo'. 

### Sources

https://www.navypedia.org/ships/equatorial_guinea/eqgui_ls_osa.htm
https://www.globalsecurity.org/military/world/africa/gq-fage-armada.htm
https://topwar.ru/uploads/posts/2016-09/1473859929_d63294e0924c440b131d6ec8910147b9.jpg
https://www.pdge-guineaecuatorial.com/wp-content/uploads/2016/07/Durante-la-salida-del-barco-en-el-puerto-de-Malabo-.jpg

**Comment by tbrandon517** [comment]
Also Consider adding the BM-5M.01 Katran-M mounts indicated in #444

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
