### ISSUE TITLE
RAH-66A Comanche RCS Update

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#4065]
### DB Selector

DB3K

### Affected DBID(s)

3818

### Summary of Changes

The RAH-66A has a radar cross section barely smaller than the AH-64D, when sources indicate it was much smaller. The current CMO Comanche lacks any armour, while the sources below suggest it had armour capable of handling heavy machine gun fire. Its Stinger missile loadouts also seem to be on the smaller side, as seen below:

"Stealth characteristics. The Comanche incorporates more low-observable stealth features than any aircraft in Army history. The Comanche radar cross-section (RCS) is less than that of a Hellfire missile. To reduce radar cross-section, weapons can be carried internally, the gun can be rotated aft and stowed within a fairing behind the turret when not in use, and the landing gear are fully-retractable. The all-composite fuselage sides are flat and canted and rounded surfaces are avoided by use of faceted turret and engine covers. The Comanche's head-on RCS is 360 times smaller than the AH-64 Apache, 250 times less than the smaller OH-58D Kiowa Warrior, and 32 times smaller than the OH-58D's mast-mounted sight. This means the Comanche will be able to approach five times closer to an enemy radar than an Apache, or four times closer than an OH-58D, without being detected."

"Infrared (IR) suppression. The Comanche only radiates 25% of the engine heat of current helicopters, a critical survivability design concern in a low-flying tactical scout helicopter. The Comanche is the first helicopter in which the infrared (IR) suppression system is integrated into the airframe. This innovative Sikorsky design feature provides IR suppressors that are built into the tail-boom, providing ample length for complete and efficient mixing of engine exhaust and cooling air flowing through inlets above the tail. The mixed exhaust is discharged through slots built into an inverted shelf on the sides of the tail-boom. The gases are cooled so thoroughly that a heat-seeking missile cannot find and lock-on to the Comanche."

"Finally, a full suite of radar warning systems, electronic warfare systems, and chaff and flare dispensers would help keep the RAH-66’s crew safe while they rode behind Kevlar and graphite armor plating that could withstand direct hits from heavy machine gunfire."

### Sources

https://man.fas.org/dod-101/sys/ac/rah-66.htm

https://coffeeordie.com/comanche-americas-stealth-helicopter

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
