### ISSUE TITLE
China, YJ-91s (Warhead, name, range, seeker, launch, codes)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4068]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2875, 2874

### Summary of Changes

What is widely believed, as the rumor as it, to be an indigenous development, would have appeared in 2007. With mock-ups observed on the Liaoning in 2012.
By using modern microelectronics, and sensors tailored to meet the Aegis challenge, it would have gained lots of room to fit in moar boom, in Goblins parlance, and more juice.
It would be associated with the K/RKL700A EW pod.
However, Butowski, Rupprecht, and Lei report that its status is "not clear", or "unknown".

- [x] YJ-91 2875
- Name: YJ-91 [K/AKJ-91, ARM]
- Weight: 715 kg
- Max Launch Alt: 15000 m
- Max Launch Speed: 674 Kts
- Sensor: Early 2010s generation
- Warhead: 165kg HE, 526
 (based on the Kh-31PM, its Range max could be 135 nm)

- [x] YJ-91A 2874
- Name: YJ-91A [K/AKJ-91A, ASM]
- Weight: 715 kg
- Max Launch Alt: 15000 m
- Max Launch Speed: 674 Kts
- Sensor: Early 2010s generation. No Passive Radar Seeker.
- Warhead: 165kg SAP, 697
- Codes: 2012	Lock-On After Launch (LOAL), 6121 Terminal Maneuver - Pop-Up
 (based on the Kh-31AM, its Range max could be 86.4 nm)

**Note:**
In 1994, the Russians sold an adapted version to with seeker, L112E, specifically designed to attack S-band radars, as per Chinese's requirements, as KR-1 (Kitay-Rossiya). A batch of standard Kh-31P and A were also sold.
So, I would clone Weapon 276 Kh-31P, as updated according to #4067 
- [x] KR-1
- Name: KR-1 [KH-31P, ARM]

Suggestions for loadout will follow accordingly.

### Sources

Cf. #4067 
- Bond, Larry, and Carlson, Chris, and Grining, Peter, _China’s Navy: Ships and Aircraft of the People’s Republic of China 1955 – 2021_, 2021 (err. 2023)
- Friedman, Norman. The Naval Institute Guide to World Naval Weapon Systems, Fifth Edition. Annapolis: Naval Institute Press, 2006. p.533-534
- Lei, Change _Naming Chinese Missiles_, The Naval Sitrep, issues 64 & 65, 2023
- designed 
- Rupprecht, Andreas:
- _Chinese Air Power in the 20th Century – Rise of the Red Dragon_, 2019
- _Dragon’s Wings, Chinese Fighter & Bomber Aircraft Development_, 2013
- _Modern Chinese Warplanes, Chinese Air Force – Aircraft and Units_, 2018
- _Modern Chinese Warplanes, Chinese Naval Aviation – Aircraft and Units_, 2018
- _Red Dragon 'Flanker'_, 2022
- https://www.globalsecurity.org/military/world/china/yj-91.htm
(Could it be that globalsecurity is now just happy to hijack and Google translate foreign articles?)
- https://odin.tradoc.army.mil/WEG/Asset/YJ-91_Chinese_Anti-Radiation_Missile
- https://www.zhihu.com/tardis/zm/art/610762290?source_id=1003

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
