### ISSUE TITLE
No ASMP nuclear missile on UAE's Rafale

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#407]
### DB Selector

DB3K

### Affected DBID(s)

5485 Rafale B and 5486 Rafale C

### Summary of Changes

ASMP-A Nuclear missile removed from the mounts
Loadout #2932 and #2933 should be removed (ASMP-A)

### Sources

The ASMP-A is a nuclear missile, exclusively built in and for France, with no known export.
UAE is not a nuclear-weapon states.
Ergo, that mount and loadouts probably shouldn't be there.

https://www.thalesgroup.com/en/worldwide/aerospace/news/rafale-export-major-contract-signed-united-arab-emirates-80-combat
https://www.mbda-systems.com/product/asmpa/
https://irp.fas.org/threat/missile/rumsfeld/pt3_france.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.

**Comment by claudejdev** [comment]
Quick note :
please apply the same modifications to loadouts 29332 and 2933 assigned to 5588 - Rafale B (Indonesia - 2027)  and 5589 - Rafale C (Indonesia - 2027)

**Comment by PygmalionOfCyprus** [comment]
Done.
