### ISSUE TITLE
China, PLASSF, Ludi Tance 4A, SAR replacement

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4072]
### DB Selector

DB3K

### Baseline

sensor 4471

### Hypothetical

No

### Name

Ludi Tance 4A SAR [3700nm]

### Sensor Generation

Early 2020s

### Range (nm)

0.1-3700

### Horizontal Arc (deg)

360deg

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Range Information, Speed Information, Heading Information

### Sensor Codes

Moving Target Indicator (MTI), Pulse-Only Radar, Can Classify Ground Targets (SAR)

### Search/Track Frequencies

D Band (1-2 GHz) [Old L Band] 15-30 cm

### Horizontal Beamwidth (deg)

1

### Vertical Beamwidth (deg)

1

### System Noise Level (dB)

2

### Processing Gain/Loss (dB)

10

### Peak Power (W)

30000000

### Comments

Multiple sources suggest that this unique high-orbit satellite has an observation capability covering one-third of the Earth's surface area (almost certainly; The negative effect is poor imaging accuracy). However, the current performance of the game does not achieve this effect.

The radius of the satellite is 1/6 of the equatorial circumference.

### Sources

https://space.skyrocket.de/doc_sdat/ludi-tance-4-01.htm
https://www.scmp.com/news/china/science/article/3231313/latest-china-satellite-survey-3rd-earth-high-orbit-breakthrough
https://www.sinodefenceforum.com/t/chinas-space-program-thread-ii.9003/page-225

**Comment by PygmalionOfCyprus** [comment]
Was added in 508.
