### ISSUE TITLE
China, LS-6-500, Extended-Range (specs, launch params, range, propulsion)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4073]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2866, 3226

### Summary of Changes

- [x] 2866 - LS-6-500 Extended-Range Bomb, GPS/INS [500kg HE]
- Length:  3.2 m
- Weight: 585 kg
- Range max: 108 nm (at least)
- Launch Alt Max: 11000 m
- Launch Speed Max: 540 knots

(AusAirPower mentions a min alt of 4000 meters and a launch speed of 600 km/h. Which would be quite outstanding in regards to all similar weapons in the DB. I would thus apply it to all such weapons, or to none)

I _assume_ that the engine would be a micro-turbojet akin to the pictures below.

- [x] 3226 - LS-6-500 GPS/INS [500kg HE] (China)
- Weight: 555 kg
- Range max: 32.4 nm (at least, tossed from max height)
- Launch Alt Max: 11000 m
- Launch Speed Max: 540 knots

### Sources

https://www.ausairpower.net/APA-PLA-GBU.html#mozTocId132067
http://www.globalmil.com/military/air_force/china/systems/strike/2017/0115/381.html#google_vignette

Changchun Air Show 2023
![IMG_20230728_132641](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/a2d6dcc0-4a5c-4f17-a583-c0040ed2bd8a)

Aero Asia Zhuhai 2022
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/efd077fb-67a9-42a3-8202-5f7a5a853c58)

![87dd5684ly1h7ovodko3xj20qy0bfgmq](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/0f4fbecc-62ff-495f-9060-c186f4daca81)

https://www.ixigua.com/7164586102144107022

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
