### ISSUE TITLE
Control Tower Building lacks visual sensors

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#4074]
### DB Selector

Both

### Affected DBID(s)

#3

### Summary of Changes

The air traffic control tower should at least have MK1 Eyeball, and realistically, binoculars too; maybe sensor #1673 or #6029?

### Sources

Worked in RAF air traffic control for 5-6 years.

**Comment by claudejdev** [comment]
Probably that same, sound, logic may apply to the Single-Unit airfields, heliports and ports ?

**Comment by PygmalionOfCyprus** [comment]
Yeah, this is more a sim logic thing; realistically most buildings probably have people in them. I can't add the Mk1 Eyeball in the DB, it's up to Command to add it.
