### ISSUE TITLE
France - CERES 1, 2, 3 (French ELINT formation-flying satellites, 2021)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#408]
### DB Selector

DB3K

### Hypothetical

No

### Series Name

CERES

### Satellite Type

SIGINT

### Country

France

### Service

2021

### In Commission

2021-2029

### Weight (kg)

446

### Is Geostationary

No

### TLE

- CERES 1

> 1 49464U 21105A   22011.19994149 0.00000090  00000-0  16259-4 0    07
> 2 49464  75.0000  44.5780 0000462 135.8964 224.1035 14.66445305    02

- CERES 2

> 1 49465U 21105B   22014.13256944 0.00000095  00000-0  17153-4 0    08
> 2 49465  75.0016  39.2810 0002000 274.9421  85.0578 14.66469133    09

- CERES 3

> 1 49466U 21105C   22013.17634004 0.00000020  00000-0  36092-5 0    01
> 2 49466  74.9991  40.9597 0001001 136.1183 223.8816 14.66493464    06

### Sensors

1x Generic Satellite SIGINT #5101

### Comments

42

### Sources

Krebs, Gunter D. “CERES 1, 2, 3”. Gunter's Space Page. Retrieved February 27, 2022, from https://space.skyrocket.de/doc_sdat/ceres-1.htm
https://ceres.cnes.fr/en/ceres-2
https://www.arianespace.com/mission/vega-flight-vv20/

https://www.defense.gouv.fr/content/download/561970/9709639/s-fiche-lpm-ceres.pdf

https://www.n2yo.com/satellite/?s=49464
https://www.n2yo.com/satellite/?s=49465
https://www.n2yo.com/satellite/?s=49466

Desc
CERES (CapacitÉ de Renseignement Électromagnétique Spatiale) project is conducted by the Directorate General of Armaments (DGA) at the benefit of the armed forces, while the French space agency CNES assists DGA for project management.
The CERES program comprises three satellites flying in formation in low Earth orbit (LEO).

Pic
https://www.arianespace.com/wp-content/uploads/2021/11/ceres.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 495.
