### ISSUE TITLE
Grisha IV Mount Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4081]
### DB Selector

DB3K

### Affected DBID(s)

DB3K Ship 92

### Summary of Changes

Pr.1124K Grisha IV not equipped with the AK-725 57mm. Remove mount from unit.

### Sources

https://www.navypedia.org/ships/russia/ru_es_mpk147.htm

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/203ea933-e9d0-44e9-9469-4398044f7ccd)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/66997232-dbc5-4912-a95d-d528b56377e4)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/7de5c564-5e4d-4223-a16a-967f1935bded)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/01edb107-20d8-434e-bf1c-21ea01ab40c7)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/1807c659-23e9-470b-9d9b-7047c0a852af)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/9dabde81-005c-43b8-9285-2a762a2b0666)

**Comment by Jkryos** [comment]
Updated DB3K 506.
