### ISSUE TITLE
F 047 Bata [SV 01, OPV-88] Mount Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4082]
### DB Selector

DB3K

### Affected DBID(s)

DB3K Ship 2809

### Summary of Changes

Add 2x AK-630M CIWS forwards of Bridge Port and starboard

### Sources

https://www.navypedia.org/ships/equatorial_guinea/eqgui_es_bata.htm

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/c97bb4f0-7793-409a-84b8-2b92d875a66d)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/ddf4d976-c2ed-4c42-9b76-a7a9565a0dd6)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/5e5f6042-7780-4c11-aead-e2f94d0dfc0c)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
