### ISSUE TITLE
China, KJ-600 (Ceiling, Radar name)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4088]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5420 Sensor 7122

### Summary of Changes

- [ ] 5420 - KJ-600
- Ceiling: 15000 m (unverifiable source, ie. Wikipedia)
> I can't find anything that would back up its current limitation at 20 000 ft. Probably that a 30 000 feet ceiling alike similar designs is more fitting.

- Comms: plausible Joint Service Integrated Data Link System

PS: is the comment "Mockeye" really necessary?

- [ ] 7122 - KJ-600 AESA Radar (Sensor)
- Name: KLC-7 [Silk Road Eye]

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/a102f341-386c-4333-928a-dac777546fec)

https://www.navalnews.com/naval-news/2019/04/imminent-roll-out-for-chinas-first-carrier-based-awacs/
https://mil.sina.cn/2018-11-07/detail-ihnprhzv6252386.d.html
https://m.thepaper.cn/newsDetail_forward_2609848
https://inews.gtimg.com/newsapp_bt/0/12399836838/1000

**Comment by tbrandon517** [comment]
Well "Mockeye" is one of those things that gets tossed around in defense circles and the media that I personally feel helps players with less awareness of designations locate and identify a platform. Much like adding "ski" to any Russian equivalent like "hawkeyeski," "harpoonski," or "LCSski."

**Comment by claudejdev** [comment]
Hey @tbrandon517 thanks for providing context.
Maybe that such things should be kept in said circles and out of the commercial DB then.
Cheers

**Comment by PygmalionOfCyprus** [comment]
Handled 506 as part of ongoing China review.
