### ISSUE TITLE
Hypothetical: PLARF, DF-100B, AShM version of DF-100

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4089]
### DB Selector

DB3K

### DBID to Copy

weapon 3669

### Hypothetical

Yes

### Name

DF-100B, AShM

### Country

China

### Service

PLARF

### Sensors

1x Active Radar Seeker [ASM LR] Late 2010s (Copy of sensor 7247)
1x Passive Radar seeker Late 2010s (Copy of sensor 7247)
1x DECM [Advanced] (same as CJ/DF-100)

### Other Changes

Remember a long time ago I mentioned in the database request to add sensors to the DF-100 to achieve its anti-ship capability.

Given the many "hypothetical" weapons I observed in the database, I felt that the idea of making the DF-100 anti-ship could be realized by adding weapons of the same type. I happened to notice in the CMO forum that the concept seemed to have been floated early and accepted by the development team, but we still don't see it in the database.

**The only few OSINT reports also favored it to have anti-ship capabilities/variants**

Need a **facility** to carry it or just add **magazines** to the original CJ/DF-100 TEL.

### Sources

https://www.militarytoday.com/missiles/df_100.htm#:~:text=This%20system%20was%20reportedly%20designed,but%20carries%20more%20capable%20missiles.

https://nationalinterest.org/blog/reboot/df-100-chinas-anti-carrier-missile-system-185018

The more authoritative CASI report also points to this possibility, which fits neatly into a hypothetical entry in the game
https://www.airuniversity.af.edu/Portals/10/CASI/documents/Research/CASI%20Articles/2020-11-04%20656%20Brigade%20CJ-100s.pdf?ver=vG4fQA5fYa8Y5_4yNpfOVg%3D%3D
> If the CJ-100 can target maritime targets, **the 656th Brigade would also be able to threaten vessels** well outside the first island chain north of the Babuyan Channel up to the Sea of Japan. 

Quotes from Chinese media reports
https://armyrecognition.com/news/army-news/2023/china-s-df-100-supersonic-missiles-threaten-taiwan-s-security
> Information from Chinese media reports indicates that the DF-100 is utilized for various strategic purposes. It can effectively target high-value enemy installations, including airports, weapon depots, command centers, and transportation hubs. When equipped with guidance systems, the DF-100 is capable of engaging moving enemy surface ships. **In addition, it plays a role in enhancing carrier anti-aircraft capabilities in coordination with other Chinese missile systems to increase pressure on enemy carrier battle groups, a threat specifically directed against the US Navy.**

**Comment by HunterDNiu** [comment]
#3550

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus 

The more authoritative CASI report also points to this possibility, which fits neatly into a hypothetical entry in the game
https://www.airuniversity.af.edu/Portals/10/CASI/documents/Research/CASI%20Articles/2020-11-04%20656%20Brigade%20CJ-100s.pdf?ver=vG4fQA5fYa8Y5_4yNpfOVg%3D%3D
> If the CJ-100 can target maritime targets, **the 656th Brigade would also be able to threaten vessels** well outside the first island chain north of the Babuyan Channel up to the Sea of Japan. 

Quotes from Chinese media reports
https://armyrecognition.com/news/army-news/2023/china-s-df-100-supersonic-missiles-threaten-taiwan-s-security
> Information from Chinese media reports indicates that the DF-100 is utilized for various strategic purposes. It can effectively target high-value enemy installations, including airports, weapon depots, command centers, and transportation hubs. When equipped with guidance systems, the DF-100 is capable of engaging moving enemy surface ships. **In addition, it plays a role in enhancing carrier anti-aircraft capabilities in coordination with other Chinese missile systems to increase pressure on enemy carrier battle groups, a threat specifically directed against the US Navy.**

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
