### ISSUE TITLE
RCAF CH-136 Kiowa Light Observation and Training Helicopter x74 aka CH-118 Kiowa

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#409]
### DB Selector

DB3K

### DBID to Copy

2908 DB3k

### Hypothetical

No

### Name

CH-136 Kiowa 

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1971-1996

### Sensors

No changes

### Mounts

Add generic chaff/flares

### Loadout Options

Add Training to existing loadouts

### Other Changes

Please copy to CWDB as well due to in service date of 1971

### Sources

https://www.helis.com/database/modelorg/Canada-CH-136/
https://en.wikipedia.org/wiki/Bell_OH-58_Kiowa#Former_operators
https://va3kgb.com/CdnMilAC/search_result_acname.php
http://www.rwrwalker.ca/CF_Kiowa.html
https://www.silverhawkauthor.com/post/canadian-warplanes-7-bell-ch-136-kiowa-helicopter

**Comment by PygmalionOfCyprus** [comment]
Added 494.
