### ISSUE TITLE
Update Hydra Rocket #1929 10k minimum altitude to 200

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4096]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 1929

### Description of Problem

Minimum altitude is high, so accuracy suffers. AtG rockets are low-altitude loadouts more often than not.

### Recommended Fix

Update Hydra Rocket #1929 10k minimum altitude to 200

**Comment by PygmalionOfCyprus** [comment]
But the minimum altitude is already currently 0?

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/b3cace99-3945-40cf-8e4d-65c245532f49)
