### ISSUE TITLE
Ground Master GM-200 for Moldavia

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4097]
### DB Selector

DB3K

### Affected DBID(s)

#4093 Radar (GM 200 Ground Master)

### Summary of Changes

Please add Moldavia to the users of this radar.
Importance is that this country has not much high tech stuff and this changes the overall picture in Ukraine related scenario's.

### Sources

[https://www.armyrecognition.com/defense_news_december_2023_global_security_army_industry/moldavia_receives_french_thales_ground_master_200_radar_system.html](url)
[https://mil.in.ua/en/news/thales-delivers-ground-master-200-radar-to-moldova/](url)
[https://twitter.com/Mark_some_one/status/1737474348238229970](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
