### ISSUE TITLE
Add Davits for small boats to Karel Doorman Class (FFGH)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4099]
### DB Selector

DB3K

### Affected DBID(s)

Ships: 2623,4449,887,166,888,1724,1590,2522,1837,2737,3800.

### Summary of Changes

Add Davits (2x very small dock/davit (0-11m long)) 
(1 port and one staboard side)

### Sources

They are on: #1797 & #3082
Are on Chile classes not on Portugal, Netherland, Belgium.
![1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/00a7608f-7189-4d01-8f23-428d8e6caa0e)
![2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99532490/ddd4474e-2a2e-400b-ac85-9e7ed070def8)

**Comment by Jkryos** [comment]
Updated DB3K 506.
