### ISSUE TITLE
JS Myōkō

### ISSUE THREAD

**Issue by baboeska** [PygmalionOfCyprus/cmo-db-requests#41]
### DB Selector

DB3K

### Hypothetical

- [ ] Yes

### Name

DDG-175 Myōkō

### Class

Kongo-class

### Country

Japan

### Service

Navy

### In Commission

1996-present

### Length (m)

161

### Beam (m)

21

### Draft (m)

6.2

### Standard Displacement (t)

7500

### Full Displacement (t)

9500

### Complement

300

### Primary Propulsion Type

Gas Turbine

### Propulsion

	 4 Ishikawajima Harima/General Electric LM2500-30 gas turbines

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

4500nm at 20kt

### Sensors

AN/SPY-1D
OPS-28 surface search radar
OQS-102 bow mounted sonar
NOLQ-2 intercept / jammer

### Mounts

1 × [127 mm (5 in)/54 Caliber Oto Melara Compact Gun]
8 × [RGM-84 Harpoon Anti-ship Missile]
2 × 20 mm [Phalanx CIWS]
2 × HOS-302 triple [torpedo tubes] Mark 46 torpedo Type 73 torpedoes
90-cell [Mk. 41]
[SM-2MR Surface-to-air missile]
[SM-3 Anti-ballistic missile]
[RUM-139 Anti-Submarine Rocket]
[RIM-162 Surface-to-air missile]

### Aircraft & Docking Facilities

1x Pad/Hanger for Medium helicopter

### Comms/Datalinks

 VHF/UHF Radio
Satcom
Datalink - Aegis capable?

### Comments

Another Kongou class JSDF Destroyer, with a very cool name :)

### Sources

https://en.wikipedia.org/wiki/JS_My%C5%8Dk%C5%8D

**Comment by PygmalionOfCyprus** [comment]
Does this differ at all from the other Kongou-class ships? We generally don't add non-nameships unless they have significantly different fits from the original.

**Comment by tbrandon517** [comment]
Myoko is the 3rd hull in the class. Nothing in my reference books or online indicates her and the 4th hull to have any major differences to the first 2 ships of the class.

**Comment by PygmalionOfCyprus** [comment]
In that case, I'm going to label this "wontfix" because of our aforementioned precedent. But if it turns out she has something special about her that can't be represented just by plunking down the Kongou and renaming it, do please feel free to reopen!
