### ISSUE TITLE
Incorrect range on Chinese Type 381 radar

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#4100]
### DB Selector

DB3K

### Affected DBID(s)

Sensor_1167

### Summary of Changes

According to Friedman, The Naval Institute Guide to World Naval Weapons Systems 1997-98, pg. 278 (scan attached), the Type 381 radar has a maximum range of 180 km (97 nm) vice the 215nm given in the database.
[Type 381 radar.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/13781527/Type.381.radar.pdf)

### Sources

Friedman, The Naval Institute Guide to World Naval Weapons Systems 1997-98, pg. 278

**Comment by Jkryos** [comment]
Updated DB3K 505.
