### ISSUE TITLE
Please add Serbia to the users of the Ground Master GM-400

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4104]
### DB Selector

DB3K

### DBID to Copy

facility # 4094 ( GM 400 Ground Master)

### Hypothetical

No

### Name

facility # 4094 ( GM 400 Ground Master) (Serbia [2023])

### Country

Serbia

### Service

Air Force

### In Commission

2023

### Number in Service

4

### Sources

[https://www.mod.gov.rs/cir/20820/obuka-na-novim-radarima-u-ratnom-vazduhoplovstvu-i-pvo20820](url)
[https://mil.in.ua/uk/news/serbiya-otrymala-frantsuzki-radarni-stantsiyi-thales-gm-400/](url)

**Comment by Jkryos** [comment]
Added DB3K pre-506
