### ISSUE TITLE
Visual pickup ranges with and without binocular

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4106]
### DB Selector

Both

### Affected DBID(s)

Sensor #6029

### Summary of Changes

In a handbook of the Ukraine (ORGANIZATION AND COMBAT PURPOSE SUBDIVISIONS OF LAND AIRCRAFT AIRCRAFT ARMY OF UKRAINE) a table 1 is incorporated with the visual pickup ranges of various air travelers.
In the DB the sensor #6029 Eyball with binoculars has a range of 30 Nm. This is in stark contrast with these data from the Ukraine armed forces. (who have some experience).

Please take a look at this table and see if any changes need to be made to sensor #6029 with binoculars and the normal Mk.1 eyball (no sensor # found).

Disclaimer:
Estimated detection ranges of air targets by means of platoon reconnaissance for flat terrain conditions with zero closing angles and a detection probability of 0.5 are given in the table.

![Table 1 ENG](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/99badf93-4e6f-4e3d-9755-ce81177d9bc2)
At first thought a binocular looks better but the limited Field-Of-View hampers the pick-up.

KP is КР which is probably an Anti-Radiation Missile (ARM)
PTKR is ПТКР which is a Anti-Tank Guided Missile
CAB is Керована авіаційна бомба (КАБ) which is a guided bomb

### Sources

[https://sprotyvg7-com-ua](url)
[Organization and combat assignment of air defense units of the Ground Forces of the Armed Forces of Ukraine.uk.en.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/13794455/Organization.and.combat.assignment.of.air.defense.units.of.the.Ground.Forces.of.the.Armed.Forces.of.Ukraine.uk.en.pdf) 
Translated in English from Ukrainian.

**Comment by ddranidis** [comment]
The max ranges of visual sensors in the DB correspond to the range at which they can detect **contrails** (of aerospace units) or **wakes** (of ships/subs). If you're familiar with such detections then you surely know contrails and wakes can be observed at far greater ranges than the units generating them. For the units themselves (even large ones like B747s or B-52s) the detection ranges are significantly smaller.

For example, in DB3000 v503 (all ranges are for naked eye, slant, nominal perfect-day conditions):
* The B-52H has a 9.28nm head-on detection range.
* The FB-111A has a 4.22nm head-on detection range.
* The A-10A has a 3.35nm head-on detection range.
* The F-16A has a 2.46nm head-on detection range.

So I think the ranges currently in DB do broadly correspond with the data you are presenting.

**Comment by Huib18** [comment]
Thank you for this explanation and all the updating work!

Greatly appriciated


Op ma 1 jan. 2024 12:14 schreef ddranidis ***@***.***>:
