### ISSUE TITLE
Digital SA-5 for Poland

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4114]
### DB Selector

DB3K

### DBID to Copy

Facility 496

### Hypothetical

No

### Name

SAM Grp (SA-5 Gammon [S-200C Wega])

### Country

Poland

### Service

Air Force

### In Commission

2002

### Sensors

Square Pair radars upgraded with digital processing, giving them strong anti-jamming capabilities. Copy and set to Early 00s.

### Mounts

Could swap the ZU-23-2s to ZUR-23-2S Jod mounts like Facility 2474 has. I don't know if that's realistic.

### Other Changes

Note #4112 and #4113

Change OODA Cycle to reflect modern digital fire control systems, probably a new SAM (Fixed, Digital) combat system entry.

I have not been able to find solid information on the number of these systems available other than that all available systems were upgraded. I _think_ only two battalions of SA-5 may have been received from the Soviets, and a fairly limited number of missiles, but then Germany, Slovakia and Hungary all retired their SA-5s so Polish stocks may have been backfilled. I'm sticking with the original Command analysis of one Group of three Battalions. There are also some indications in the source article that the upgrades have allowed greater dispersal of the sites so the correct move might be to have a SAM Bn facility and an independent Odd Pair and Tall King for them.

### Sources

https://sd-magazine.eu/index.php/sd/issue/view/13/12 pp.80-89

**Comment by PavelNovak79** [comment]
Poland originally built its SA-5 base for three battalions but eventually their Vega group received only two battalions in 1986 with total of 38 missiles (24 received in 1986 and 14 in 1987).

No idea if they bought anything more after the end of the Cold war.

**Comment by PygmalionOfCyprus** [comment]
Handled 506. They also went an additional modernization in 2018, so added that w/ a ergo boost.
