### ISSUE TITLE
Heavyweight torpedoes for Egyptian MEKOs

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4118]
### DB Selector

DB3K

### Affected DBID(s)

Ship 4086

### Summary of Changes

It's not usually me doing these hot news item ones...

Add a mount for 2x 533mm torpedoes, carrying Weapon 82, the Seehecht Mod 4. Fixed rear firing, although the Saudi Al-Riyadhs have a pretty wide arc for their similar systems. I suppose reloads are possible but I'd say none for now.

The door on the opposite side is almost definitely for a towed array and I expect a fixed sonar to be fitted, neither of which are on the ship in the DB. It makes no sense to FFBNW sonars while fitting two different kinds of torpedo, and we know that Thales have provided the rest of the sensor suite. Egypt already operates the CAPTAS towed array and the Kingklip hull sonar (as fitted to other MEKOs and offered to the UK) so I would guess:
- Add sensor 4019
- Add sensor 4219

Reference #932, @bostonmyk came to the same conclusions

### Sources

https://twitter.com/D__Mitch/status/1742167153812312234
https://vpk.name/en/593319_the-lead-egyptian-frigate-of-the-german-built-meko-200en-project-at-sea.html
https://www.savetheroyalnavy.org/wp-content/uploads/2019/03/A200-Arrowhead-v-Leander-comparison-1.pdf
https://navalpost.com/egypt-begins-local-manufacturing-of-meko-a200-frigate/

**Comment by bostonmyk** [comment]
Sipri arms trade register has a line item for this as well 

(25)	DM2A4 Seehecht	anti-ship/ASW torpedo	2019	2022	(5)	For MEKO-A200 frigates

They ordered them for Subs as well will put in a request for that as well.

(125)	DM2A4 Seehecht	anti-ship/ASW torpedo	(2015)	2016-2021	(125)	For Type-209 submarines

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
