### ISSUE TITLE
RCAF UH-1D Huey

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#412]
### DB Selector

CWDB

### Affected DBID(s)

2089 CWDB

### Summary of Changes

I don't believe that Canada operated the UH-1D, delete entry

### Sources

https://www.helis.com/database/org/Canadian-Armed-Forces/
https://www.silverhawkauthor.com/post/canadian-warplanes-7-bell-ch-135-twin-huey-helicopter
https://va3kgb.com/CdnMilAC/search_result_acname.php
http://www.rwrwalker.ca/post_int.html

Canadian Combat and Support Aircraft, A Military Compendium. TFJ Leversedge, 2007, Vanwell Publishing Limited

**Comment by Jkryos** [comment]
This [source](http://www.worldairforces.com/Countries/canada/can.html) lists them using 10 from 1968 to 1988. I have updated the comments to reflect the number and end of service date CWDB 494.
