### ISSUE TITLE
Iranian Navy Seaking helicopter with countermeasures

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4123]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #3092

### Summary of Changes

Iranian SH-3D Seaking can be equiped with countermeasures:
laserwarning in six quadrants
4x 30=120 chaff/flares in 4 boxes
and a 1st generation IR jammer (can use data from sensor #1487)
(probably on the left and right side on the helicopter so multiply everything 2x please)

![GCNIx2WXAAAs89n](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/7ad27b55-2a73-4eb6-8fe3-7ff5fc975f15)

### Sources

[https://twitter.com/AmirIGM/status/1739229985338982546](url)
[https://twitter.com/IranDefense/status/1739115362317189250/photo/2](url)
[https://twitter.com/imp_navigator/status/1739246287428456913](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
