### ISSUE TITLE
Pantsir-SM sensors/missile updates

### ISSUE THREAD

**Issue by bqz2801** [PygmalionOfCyprus/cmo-db-requests#4126]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6880, Weapon 3693, Sensor 6055

### Summary of Changes

**max target speed **increased to 2000 m/s (3888 kts) (for weapon db 3693)**
**missile speed decreased to 1500 m/s (mach 4.38)** current max speed of mach 9 is way too fast (db 3693)
RLM-SOC acquisition radar properties changed to: **AESA (db 6880)**
1RS3 FCR tracking radar properties changed to: **PESA, late 2000's technology (db 6055)**
**exclude the mini missiles for now (until more photo evidence)****

New extended range missile has increased max target speed of 2000m/s (mach 5.8) and a max speed of 2915 kts / mach 4.38 (not mach 9) currently in game max missile speed is mach 9 to mach 10. New missile has twice the speed, twice the range, and twice the max target speed of regular Pantsir-S1/S2 variants
New RLM SOC acquisition radar said to be AESA from multiple sources
New FCR is a PESA (late 2000's tech)

![PantsirSMBM png 973f820dbbb46e068333253df2ea4398](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/ca36f8ef-b594-4487-99d4-ed02b5723230)
here brochure in front of the system on display shows 40km engagement range, 2000m/s max target speed

![171702-627f665bdcd2805bb6b0253a9b01787e](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/24665795-d4a8-409b-b34c-af253b5c6775)
in this news article, it is claimed that both the indicator radar is an AESA and the FCR is AESA, however due to presence of feedhorn it is more likely a PESA (for example 91n6 big bird is PESA but has feedhorn) so PESA is good for now until more evidence comes

![pantsir afar](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/7fb84889-5c99-479a-b68e-420dcb1d4c98)
here acquisition radar shown as AFAR (active phased array radar) / AESA (S-band)

here in top right the tracking radar is shown as AFAR (AESA) and the FCR radar 1Rs-3 shown as a reflective PESA
![pantsir sm sm sm](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/e3c4a1eb-94cd-4662-8258-9e3e0419bc26)

### Sources

https://thaimilitaryandasianregion.wordpress.com/2015/10/30/pantsir-s1/
https://thaimilitaryandasianregion.blogspot.com/2020/07/shell-sm-and-its-capabilities.html
https://yandex.com/images/search?img_url=https%3A%2F%2Fsun9-49.userapi.com%2Fc857036%2Fv857036869%2F8518e%2Fgxl30SZKxMw.jpg&lr=20993&pos=2&rpt=simage&text=pantsir-sm%20speed
https://www.secretprojects.co.uk/threads/pantsir-gets-new-sams.34186/
https://gunsfriend.ru/96k6-pancir-s1-zenitnye-raketnye-kompleksy-rls-sprn-i-pvo-vooruzenie/

**Comment by KLABDB3K** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/3222

**Comment by bqz2801** [comment]
> #3222
> 
> There is still also the issue of the "mysterious" mini missiles.

that's true, however the mini missiles have not been confirmed to be deployed, only the new extended range higher speed ones. The mini ones are most likely for FPV drones and quadcopters, but we don't have any proof how much are deployed per TEL and in what configuration (for example if it's 6 regular missiles and 24 mini missiles. We just now each tube can house 4 mini missiles (so 48 total)

Otherwise, the radar type is known for the search radar, and specs are known for max target speed. from what's available. 
Still interested why the FCR is claimed to be AESA but has a feedhorn antenna (maybe for IFF or another frequency band?) that's why I say it's most likely a PESA since big bird series all have feedhorns are are PESA designs.

**Comment by ghost** [comment]
going to repost but summarize it much shorter so not as messy and easier to read through. new info on SM missiles and tracking system (3 radar + 1 optical channel for guidance)

**Comment by sr71xx** [comment]
> #3222
> 
> There is still also the issue of the "mysterious" mini missiles.

I think that the current in game FCR for pantsir-s2 variants (SOTS [1RS1-3E-RLM) is the same radar that Pantsir-SM uses. looks exactly identical. So it would make sense for pantsir-sm to have its FCR replaced with this sensor but with increased range of 40km. Also, mini missiles do not have datalink working with any pantsir FCR variants.
