### ISSUE TITLE
Addition: PrSM Spiral 4

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4128]
### DB Selector

DB3K

### DBID to Copy

3847, 3848

### Hypothetical

Yes

### Name

PrSM Spiral 4 []

### Country

US

### Service

Original 

### Other Changes

Change range to 540nm. 
Change propulsion to rocket booster, ramjet sustainer

### Sources

https://www.defensenews.com/land/2021/06/14/us-army-to-fund-extended-range-precision-strike-missile-starting-in-fy22/
https://www.janes.com/defence-news/news-detail/us-army-conducts-static-test-with-ramjet-for-future-precision-strike-missile

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
