### ISSUE TITLE
Add Manta II ASD class, Nigeria

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#413]
### DB Selector

DB3K

### Hypothetical

No

### Name

Fast Patrol Boat (PB) / Littoral Interceptor, P25, -

### Class

Manta II ASD (Manta III)

### Country

Nigeria

### Service

Navy

### In Commission

2008 - present

### Length (m)

17.95

### Beam (m)

3.6

### Draft (m)

0.95

### Standard Displacement (t)

Not found

### Full Displacement (t)

21

### Complement

6

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU, 2 shafts

### Flank Speed (kt)

45

### Range (nm) at Speed (kt)

250 @ 35

### Sensors

1x Furuno radome I-Band navigation radar

### Mounts

3x 12.7mm/90 (src1&2),
1x 40mm AGL (src1)

### Ship Codes

All Aluminum Construction

### Sources

Src 4 is generic info on class.
1: JFS 2016-2016
2: https://www.navypedia.org/ships/nigeria/nig_cf_p25.htm
3: https://navyclippings.nl/index.php/2021/01/07/malaysias-northern-shipyard-completes-manta-vessels-for-nigeria/
4: http://suncraftgroup.com/84-manta-military.htm
5: https://navyrecognition.com/index.php/news/defence-news/2021/january/9517-northern-shipyard-from-malaysia-finalizes-construction-of-four-manta-mk-ii-patrol-boats-for-nigerian-navy.html
![1Posted](https://user-images.githubusercontent.com/99532490/155875486-a4deda1e-75be-47b0-9bae-c18471da687e.jpg)
![2Posted](https://user-images.githubusercontent.com/99532490/155875487-c31db210-2706-4a73-911c-7513a4b1a639.jpg)
![3Posted](https://user-images.githubusercontent.com/99532490/155875489-2c7a4780-fc72-4951-b3f3-0133b80c6fe6.jpg)

**Comment by Parel803** [comment]
In the Comment: sources differ a little on Manta II and Manta III (Manta II ASD) as on the sidenr of first in class.

**Comment by PygmalionOfCyprus** [comment]
Already added 493 as part of one of our news roundups (when Nigeria took delivery of the new ones earlier). But I made a couple tweaks to incorporate this info.

**Comment by Parel803** [comment]
Thank you
