### ISSUE TITLE
TEL for Abu Mahdi (Talaiyeh) Anti Ship Cruise Missile

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4132]
### DB Selector

DB3K

### Hypothetical

No

### Name

TEL for Abu Mahdi (Talaiyeh) Anti ship Cruise missile 

### Facility Type

SSM

### Country

Iran

### Service

IRGC and Iranian Navu

### In Commission

2023

### Number in Service

Unk

### Crew

3

### Dispersion Radius (m)

Unk

### Sensors

N/A

### Mounts

Two Abu Mahdi CM Weapon #4240
(pls check there is also weapon #4333 but it says suse 4240 instead?)
Antenna mast possibly UHF 

### Magazines

1 possible reload because they are placed in canisters.
Reload time 45 min?

### Aircraft & Docking Facilities

N/A

### Comments

Talaiyeh is the Iranian navy name for the Abu Mahdi missile of the IRGC.
Soumar is the land variant.
[https://twitter.com/mhmiranusa/status/1739165631100891165](url)

Quote: A poster from the Talaiyeh (formerly Abu Mahdi) missile delivery to IRIN shows that the max range of 1000 km is calculated at 4000 m (~12000 ft) altitude. In practice, if the missile is going to do sea skimming to avoid detection, its range would be considerably less.
[https://twitter.com/mhmiranusa/status/1739161159712804922](url)

Quote: I am a bit suspect of the range claim, the sensor package for a good anti-ship missile is generally heavier than a land attack missile's guidance section. The Block VA Tomahawk (new ASCM version) is believed to have a range (700km) 1/2 that of the land attack version, Block VB.
[https://twitter.com/PatrickSchuess1/status/1739169488229281844](url)

### Sources

https://twitter.com/imp_navigator/status/1739242433894899795
[https://www.tasnimnews.com/fa/news/1402/10/03/3011084/%D9%85%D9%88%D8%B4%DA%A9-%DA%A9%D8%B1%D9%88%D8%B2-%D8%B7%D9%84%D8%A7%D8%A6%DB%8C%D9%87-%D9%88-%D8%A8%D8%A7%D9%84%DA%AF%D8%B1%D8%AF%D9%87%D8%A7%DB%8C-%D8%AC%D9%86%DA%AF-%D8%A7%D9%84%DA%A9%D8%AA%D8%B1%D9%88%D9%86%DB%8C%DA%A9-%D8%A8%D9%87-%D9%86%DB%8C%D8%B1%D9%88%DB%8C-%D8%AF%D8%B1%DB%8C%D8%A7%DB%8C%DB%8C-%D8%A7%D8%B1%D8%AA%D8%B4-%D8%A7%D9%84%D8%AD%D8%A7%D9%82-%D8%B4%D8%AF](url)
[https://twitter.com/imp_navigator/status/1683733915880550403](url)

**Comment by Huib18** [comment]
A poster from the Talaiyeh (formerly Abu Mahdi) missile delivery to IRIN shows that the max range of 1000 km is calculated at 4000 m (~12000 ft) altitude.
In practice, if the missile is going to do sea skimming to avoid detection, its range would be considerably less.

[https://twitter.com/mhmiranusa/status/1739161159712804922](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
