### ISSUE TITLE
Abu Mahdi Al-Muhandis PCSG

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4134]
### DB Selector

DB3K

### Baseline

Ship # 3392

### Hypothetical

No

### Name

Abu Mahdi Al-Muhandis PCSG

### Class

N/A

### Country

Iran

### Service

Navy (IRGC)

### In Commission

2024

### Number in Service

1

### Length (m)

48

### Beam (m)

15

### Draft (m)

a little less than Ship # 3392

### Standard Displacement (t)

N/A

### Full Displacement (t)

a little less than Ship # 3392

### Empty Displacement (t)

a little less than Ship # 3392

### Complement

a little less than Ship # 3392

### Max Sea State

Same  as ship # 3392

### Primary Propulsion Type

Diesel

### Propulsion

Same  as ship # 3392

### Fuel Capacity (kg)

Same  as ship # 3392

### Flank Speed (kt)

Same  as ship # 3392

### Range (nm) at Speed (kt)

2000 Nm or 14 days

### Sensors

2 Generic Navigation radars Furuno like.
1x Type 352 Square Tie like radar (sensor #38)

### Mounts

1x 30mm gun (weapon #1431
4x 20 mm (weapon #629) 2x left and right of the 30mm gun and 2x left and right just aft of the torpedo's 
(4 barreled 20mm guns. Non stabilized remotely operated with a TV or IR camera.)
See weapon request [https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4138#issue-2069218604](url)

6x C-802 (weapon #2408) aft in 2x 3 launchers

Is said to have SAMs (maybe MANPADs, but are not located yet.

### Aircraft & Docking Facilities

No docking facilities for helicopters. Maybe a landing facility for drones (unk type) between the torpedos.

### Comms/Datalinks

VHF radio
UHF radio
Satcom
http://www.hisutton.com/Iran-4th-Shahid-Soleimani-class.html

### Sources

[https://twitter.com/projectmeshkat/status/1743542898153410897](url)
https://twitter.com/Military_Tweet1/status/1743538180333150323/photo/2
[https://twitter.com/CovertShores/status/1743549655906959490](url)
[https://twitter.com/projectmeshkat/status/1743504322128691698](url)
[https://twitter.com/partisan_sgroup/status/1743541898462081496](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
