### ISSUE TITLE
Remotely operated 20mm 4 barreled gatling gun Iranian navy

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4138]
### DB Selector

DB3K

### Baseline

Weapon #1630 20mm Phalanx 

### Hypothetical

No

### Name

Remotely operated 20mm 4 barreled Gatling gun

### Length (m)

You can use data of weapon #629

### Width/Span (m)

You can use data of weapon #629

### Diameter (m)

You can use data of weapon #629

### Weight (kg)

You can use data of weapon #629

### Range (nm)

You can use data of weapon #629

### Target Altitude / Depth (ft)

You can use data of weapon #629

### Target Speed (kts)

less than #629 because manually operated

### Warhead

You can use data of weapon #629

### Targets

Aircraft, Helicopter, Missile, Surface Vessel, Mine, Land Structure - Soft, Mobile Target - Soft, Mobile Target - Personnel

### CEP (m)

less than #629

### Sensors

Hard to say if it is a TV or IR camera because of the very small size, but lets say it is IR. But it is attached to the gun so not stabilized like the Phalanx. The FLIR of the Phalanx also has a wiper to clean the window which this one does not have. (details.. hi hi)

It's size will hamper the anti missile capability and also the lack of radar guidance. It is manually search and track insead of autotrack. So scan period will be high and PoH will be low.
![Clipboard01](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/d67aeff8-663b-4d15-8315-205ebe994503)

### Weapon Codes

Anti-Air All-Aspect, No Diving Target, Capable vs Seaskimmer

### Comments

Ammo is much lower than Phalanx
![GDQI93SWkAAHeX1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/64875ff0-5eeb-4c88-b503-19c82889bcaf)
versus
![Clipboard02](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/2e4de89f-b674-4d2b-b9f3-6e949910f148)
My guess is 500 rounds

4x placed on https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4134#issue-2068512558

### Sources

[https://twitter.com/Pataramesh/status/1744029410020229350/photo/1](url)
https://pbs.twimg.com/media/GDQJDS8XcAA9648?format=jpg&name=large

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
