### ISSUE TITLE
MS Asterix doesn't have its refuel capabilities.

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#4139]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3223 MS Asterix Container Vessel, Canada, 2018

### Summary of Changes

- Add to Name [Resolve Class AOR]. [1]
- Change Category to Auxiliary. [1]
- Change Type to AOR - Replenishment Oiler (WRA: Ship - Auxiliary, 10001-25000 tons). [1]
- Update Combat System for the following: "INTEGRATED NAVIGATION, MACHINERY AND DAMAGE CONTROL SYSTEM Fully integrated bridge from which to control and monitor navigation, machinery and damage control systems". [1]
- Add Marine Diesel Storage 8933.4 t. [1]
- Add Aviation Fuel Storage 1040 t. [1]
  
"REPLENISHMENT AT SEA NATO STREAM-type liquid and solid replenishment for alongside replenishment on both sides of the
ship simultaneously (four stations)". [1]

Add the following Properties:

- Refuel to Port x1 (Out)
- Refuel to Starboard x1 (Out)
- Refuel to Port x1 (In)
- Refuel to Starboard x1 (In)
- Replenish to Port x1 (Out)
- Replenish to Starboard (Out)
- Replenish to Port x1 (In)
- Replenish to Starboard (In)

"SMALL CRAFT WITH LAUNCH AND RECOVERY SYSTEMS, 4 x Rigid Hulled Inflatables, 2 x Fast Rescue Craft, 2 x Lifeboats" [1]
"LCVP, 2 x LCVP (Landing Craft, Vehicle and Personnel) for transfer of personnel, stores and vehicles and humanitarian operations" [1]

Changes to Docking Facilities:

- Remove 2x Davit (1x Small Dock/Davit (LCVP, 11.1-17m))
- Add 2x Davit (4x Very Small Dock/Davit (0-11m Long))

### Sources

[1] https://federalfleet.ca/wp-content/uploads/2016/07/Resolve-Pamphlet.pdf

**Comment by Jkryos** [comment]
Added DB3K 505.
