### ISSUE TITLE
Please add chaff/flare dispenser and Tarang RWR for Mig-21 Bison

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#414]
### DB Selector

DB3K

### Affected DBID(s)

1186 Mig-21bis UPG Fishbed N [Bison]

### Summary of Changes

As of CMO, the Mig-21 Bison were not equipped with chaff/flare dispenser but as per sources on the internet the Bison do equipped with conformal chaff/flare dispenser alongside the fuselage and were also seen releasing flares. and it also equipped with Tarang RWR on the tail fins too. Please add the chaff/flare dispenser and Tarang RWR to the Mig-21 Bison.

below is the pics of the conformal chaff/flare dispenser:
![image](https://user-images.githubusercontent.com/99646926/155888911-e7d71ade-2500-403a-90b4-edd69cbabf92.png)
![image](https://user-images.githubusercontent.com/99646926/155888937-092ce092-ad0d-4a4e-a5e9-dbe86a83bd55.png)
![image](https://user-images.githubusercontent.com/99646926/155888974-2f295ec4-f075-4c34-ba50-abe0be5ef898.png)

and here is the pic of Tarang RWR fitted on the tail fin:
![image](https://user-images.githubusercontent.com/99646926/155889026-8ec87112-74e5-4f13-bfe2-74db5af3ac90.png)

### Sources

https://www.reddit.com/r/MilitaryPorn/comments/3udv19/indian_airforce_mig21_bison_popping_flares_not_a/
https://www.bharat-rakshak.com/IAF/Galleries/Aircraft/Walkarounds/MiG21Bison/
https://eurasiantimes.com/iaf-fighter-pilot-speaks-his-heart-out-on-mig-21-jet-crash/
https://www.alamy.com/srinagar-kashmir-26th-sep-2021-an-kashmirn-air-force-iaf-fighter-jet-launches-flares-during-an-air-show-conducted-by-kashmirn-air-force-iaf-in-srinagarthe-show-saw-a-display-by-the-iafs-surya-kiran-aerobatics-team-paramotor-and-powered-hang-glider-display-fly-past-mig-21-bison-aerobatics-by-su-30-aircraft-it-also-included-akashganga-skydiving-display-credit-sopa-images-limitedalamy-live-news-image443580853.html

**Comment by PygmalionOfCyprus** [comment]
Added 493.
