### ISSUE TITLE
Add jet powered Shahed-238 variant

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#4140]
### DB Selector

DB3K

### DBID to Copy

Weapon 4142, Facility 3666

### Hypothetical

No

### Name

Shahed-238 

### Country

Russia

### Service

Air Force

### In Commission

2023-present

### Number in Service

few, limited

### Other Changes

new variant with turbojet engine, faster at almost 800km/hr but has half the range (1000km)
copy of regular geran-2 shahed-136 facility but with tweaked weapon specs::
**-change engine to turbojet
-increase max speed to 432 kts
-reduce max range to 540nmi / 1000km**
keep all else the same

### Sources

https://www.thedrive.com/the-war-zone/evidence-russia-is-now-using-jet-shahed-kamikaze-drones-emerges
https://www.newsweek.com/russia-iran-drone-shahed-238-131-136-air-defense-ukraine-1858895
https://twitter.com/bayraktar_1love/status/1744450465926922683?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1744450618716995888%7Ctwgr%5E175fb70ed48d670678954572482f1112abe902bd%7Ctwcon%5Es2_&ref_url=https%3A%2F%2Fwww.thedrive.com%2Fthe-war-zone%2Fevidence-russia-is-now-using-jet-shahed-kamikaze-drones-emerges
https://twitter.com/clashreport/status/1744454866729120011?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1744454866729120011%7Ctwgr%5E175fb70ed48d670678954572482f1112abe902bd%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.thedrive.com%2Fthe-war-zone%2Fevidence-russia-is-now-using-jet-shahed-kamikaze-drones-emerges

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
