### ISSUE TITLE
Add C-RAM ability for all Pantsir Systems

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#4141]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3250, Facility 1934, Facility 3432

### Summary of Changes

Recently footage showed interceptions of many MLRS smerch/urugan/vikha and other rockets above the city of Belgorod by Pantsir-s1

video shows 8 interceptions above Belgorod (more audible) by multiple Pantsir-s1 systems
https://twitter.com/TobiAyodele/status/1744435042565099831

other vid showing pantsir interceptions of MLRS over Belgorod
https://twitter.com/RandyHiggins757/status/1745032351472644590

This is shown ability to shoot down rockets and salvos similar to CRAM and Iron Dome.

### Sources

https://twitter.com/RandyHiggins757/status/1745032351472644590
https://twitter.com/TobiAyodele/status/1744435042565099831

**Comment by KLABDB3K** [comment]
The detail in the dialogue is stating this isn't Pantsir S1/2 but the SM using a more advanced Missile, so new or updated entry not an amendment to the entire Pantsir range? .

**Comment by bqz2801** [comment]
> 57Э6М

new extended range missile 57Э6М has double the range, velocity, and max target speed of the original 57Э6, so both should be able to engage mlrs/rockets. New M variant with 40km range has a max speed of mach 4.5 and max targeting speed of mach 5.6, coupled with an AESA guidance radar and reflective type PESA tracking radar, the new Pantsir-SM is at least twice as effective on paper at intercepting mlrs/rockets, and that is just for the new extended range missiles.

As for the mini missiles, they don't have boosters and are single stage, so have a range of only 10km (are meant for FPV and quadcopter drones)

**Comment by TTZ32** [comment]
Pantsir s1 has been shown to intercept mlrs rockets and himars projectiles  

https://youtu.be/il9tx2Dh6UI?si=t187vcJubnf8ygKJ

**Comment by Jkryos** [comment]
Updated DB3K 506.
