### ISSUE TITLE
Updates for Osa-AKM-P1 Żądło

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4148]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3985, 3986

### Summary of Changes

The overhaul involves a lot of digital systems, much like other Polish overhauls of Soviet AD systems. I would suggest:
- [ ] Upgrade combat system to full SPAD Digital standard (15 second Detection etc.) - It seems that the system has a custom combat system which makes it _slightly_ better than other Osas, but really not by a lot compared to significantly older TELAR vehicles such as SA-11.
- [x] Upgrade the 969 Land Roll radar to Early 00s tech level to represent ECCM improvements and low RCS detection improvements from digital signal processing.

Additionally, I have a bit more information on the new optronic sensors:
- [x] Upgrade the LLTV to 3rd gen
- [x] Add a laser rangefinder to the sensor group
- [x] Name the thermal imager as "SIC 12/TA"?

### Sources

https://archive.ph/20130126164503/http://articles.janes.com/articles/Janes-Land-Based-Air-Defence/9K33-OSA-AK-Polish-Upgrade-Programme-Poland.html
https://pl.wikipedia.org/wiki/9K33_Osa
https://wzu.pl/sites/default/files/Glowica_optoelektroniczna_en.pdf - This is visibly the tracker on upgraded Osas

**Comment by PygmalionOfCyprus** [comment]
Mostly-handled 505.

>It seems that the system has a custom combat system which makes it slightly better than other Osas, but really not by a lot compared to significantly older TELAR vehicles such as SA-11.

This is why it has "Good" ergonomics, but not the full step up to Digital SPAD.

**Comment by FrangibleCover** [comment]
> Mostly-handled 505.
> 
> 
> This is why it has "Good" ergonomics, but not the full step up to Digital SPAD.

Ah, what I meant is that the system _as currently represented_ has slightly better ergonomics. I think it deserves the full step, although obviously it's hard to tell through all the marketing-speak. Surely with proper early 00s Western microelectronics it should be as good as early 80s Soviet stuff, right?

**Comment by PygmalionOfCyprus** [comment]
Okay, I found some videos from the inside with full MFDs and stuff, so I've changed it to digital. That said, I'm still giving it poor ergo because it's still an old Soviet system at heart and you can still see a lot of analog stuff in there. It wouldn't be fair to treat it the same as a purpose-built modern SAM.
