### ISSUE TITLE
Weird TELs for every SA-6b

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4149]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3450, 4036, 243, 133, 3924, 3925

### Summary of Changes

These facilities have 3x SA-6a TELs and 1x SA-6b TELs, which is odd, and only have reloads for the SA-6b. If they really are operated with mixed TELs then reloads should be provided for both. If not then they should be fixed to full SA-6b standard.

### Sources

DB

**Comment by PavelNovak79** [comment]
This is little bit more tricky.

CIA in their declassified documets distinguish only two major versions of SA-6: SA-6A which corresponds to all standard 2K12 Kub variants up to including 2K12M3 Kub-M3 and SA-6B which is that special hybrid 2K12M4 Kub-M4 alias incomplete Buk [SA-11].

SA-6A SAM standard battery organization has one fire control radar and four launchers. Depending on the variant it can use missiles up to 3M9M3.

SA-6B SAM battery has one fire control radar, three standard launchers and one SA-11 style launcher with engagement radar but still with 3M9M3 missiles. This TELAR is also able to provide illumination for another standard launcher. So the battery have actually two radars for guiding missiles.

In game we have currently only two Gainfull missiles: 3M9 as SA-6a and 3M9M3 as SA-6b. We are lacking anything in between but from gameplay point of view it is not such an issue. I am just using 3M9 for everything before 3M9M3 which is more capable.

What we lack is something to represent 2K12M3 Kub-M3 with 3M9M3 missiles but still with SA-6A organization. And current SA-6B should be all 3M9M3 armed.

**Comment by FrangibleCover** [comment]
Yes, to be honest I didn't feel qualified to dig into the whole Kub variant mess because it means that you have to work out what variants every operator had at every time. Honestly, I thought that the DB SA-6b _was_ Kub-M3.

The more I look at this, the more it becomes apparent that there's a lot more to be done in the representation of Cold War 'red' kit. Well, I suppose I have more or less polished off what I wanted to do with the Border War...

**Comment by PygmalionOfCyprus** [comment]
Russian/Soviet SAMs absolutely need some TLC

**Comment by FrangibleCover** [comment]
Superseded #4251
