### ISSUE TITLE
Italian DDX update

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#4151]
### DB Selector

DB3K

### Affected DBID(s)

3618

### Summary of Changes

Updates following rivista difesa italian Jan 24 article

* length to 197m
* full displacement to 12500t
* 16 Sylver A70 to 32
* 2x 25mm to 3x 30mm (coverages each ~270°, front + full starboard hemisphere, front + port hemisphere, full rear hemisphere+right side)
* 4x teseo quad to 2x teseo quad

* add 3x generic radar gun directors for the 76mm
* 76mm gun mount # 3 has symmetric coverage of the rear
* flat panels radars are angled at 45° instead of front/left/right/back
* add VDS sonar (presumably same as the FREMM so CAPTAS mk 4 # 4019
* delivery is 2029-> IOC to 2030
* I think we can remove the Hypothetical

![GC7gRneXoAAm9yI](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/18752207/9ea31321-d86a-48b0-9786-38b1be893d03)

### Sources

https://twitter.com/phoenix_jz/status/1742591334932783111
Article by Michele Cosentino in RID 01/2024

**Comment by gosnold** [comment]
ping @Tobias02

**Comment by PygmalionOfCyprus** [comment]
Handled 505.

**Comment by Tobias02** [comment]
Thanks!!!
________________________________
Da: PygmalionOfCyprus ***@***.***>
Inviato: mercoledì 31 gennaio 2024 21:06
A: PygmalionOfCyprus/cmo-db-requests ***@***.***>
Cc: Tobias02 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [PygmalionOfCyprus/cmo-db-requests] Italian DDX update (Issue #4151)


Handled 505.
