### ISSUE TITLE
Correction: THAAD

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4152]
### DB Selector

DB3K

### Affected DBID(s)

Weapons 857, 893, 3590

### Summary of Changes

Change max target altitude to 328000ft. 
Change cruise altitude to 328000ft. 
Add valid targets: aircraft. 

### Sources

https://en.wikipedia.org/wiki/Terminal_High_Altitude_Area_Defense#Demonstration_and_validation says flight ceiling is 150km.

**Comment by TTZ32** [comment]
> From most available public data, THAAD does not have ability to target aircrafts, only missiles for now.

Correct, THAAD isnt a conventional air defense system, its a ballistic missile defense system.

**Comment by PygmalionOfCyprus** [comment]
Handled 505, did not add Aircraft to target list as per above comments.
