### ISSUE TITLE
Add CEC to US E-7A Wedgetail (Similar to Australia) 

### ISSUE THREAD

**Issue by dleake14** [PygmalionOfCyprus/cmo-db-requests#4153]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #5436

### Summary of Changes

E-7A Wedgetail (USAF - 2027) lacks CEC COMMS / datalinks that are found on E-7A (RAAF - 2020) Aircraft #6774

### Sources

https://defense.info/defense-systems/royal-australian-navy-and-us-navy-cooperative-engagement-capability/

While it doesn't mention it being on the US version specifically, I believe it's implied that the US will retain CEC capability on all future ABM platforms

**Comment by FIM43-Redeye** [comment]
Probably best to actually add the offboard datalinks from the E-2D (4293 or 6992). I can't see a world in which at least the AIM-120 offboard datalink isn't implemented, but I would expect an AEGIS link too with all this focus on interoperability.

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
