### ISSUE TITLE
USA - GBU-53/B StormBreaker (Comms, IOC, CEP, Range)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4155]
### DB Selector

DB3K

### Affected DBID(s)

weapon 2855

### Summary of Changes

- Comments: 2019 [^0]
- CEP: 1 m[^3]
- Range: min 1.5[^4]; max 40 [^0][^4] ("110 km against stationary targets and 72 km against moving targets" [^3])
- Datalink: add Link 16. Shouldn't the "TacNet Weapon Datalink" be a two-way Datalink? [^0][^1][^2]

---
This request supplement #2661

### Sources

 [^0]:[GBU-53 StormBreaker Archives | Air & Space Forces Magazine](https://www.airandspaceforces.com/weapons-platforms/gbu-53-sdbii/)
 [^1]:[Small Diameter Bomb Increment II (SDB II) | NAVAIR](https://www.navair.navy.mil/product/Small-Diameter-Bomb-Increment-II-SDB-II)
 [^2]:[SDBII_factsheet_0810.pdf](https://www.airandspaceforces.com/PDF/SiteCollectionDocuments/Reports/2010/August%202010/Day25/SDBII_factsheet_0810.pdf)
[^3]:[European Security & Defence journal, 11-12/2023, p. 15 (PDF)](https://euro-sd.com/wp-content/uploads/2023/11/ESD_11_12_2023.pdf)
[^4]:Larry Bond, Chris Carlson, & Peter Grining "Commonwealth Aircraft - Aircraft of the United Kingdom, Australia, Canada, and New Zealand 1955 - 2023", Jan. 2024

**Comment by PygmalionOfCyprus** [comment]
Handled 505. TacNet is already 2-Way in the DB...?

**Comment by claudejdev** [comment]
> Handled 505. TacNet is already 2-Way in the DB...?
@PygmalionOfCyprus 
Yeah, I'm not sure where I can verify it:
the DB viewer doesn't display that ability, and I can't figure out which DB table stores the value.
Cheers
