### ISSUE TITLE
USA - GBU-43 MOAB (Weight, Comment)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4156]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 462

### Summary of Changes

- Comments: 17 procured, 1 used.
- Weight: 9800
- Range: 3 [^1] Edit: or 40 [^0]? 
from Chris Carlson:
> (...) it's our best guess, but it's not a typo. Not sure where the Air Force Museum got its range number, but the low-aspect wings and the grid-type control surfaces on the MOAB strongly argue for a long glide range. Given that your typical Paveway II LGB - without the features just mentioned - has a deployment range of 5 to 15 miles the MOAB's range is very likely larger. The USAF won't even release the altitude the MC-130 deploys the GBU 43/B pallet, so, until we see something more authoritative we'll stay with the 40 nmi glide range.

### Sources

 [^0]:Larry Bond, Chris Carlson, & Peter Grining "America’s Aircraft - U.S Military Aircraft 1955 - 2020", Jan. 2024
 [^1]:[GBU-43/B MOAB - Air Force Armament Museum Foundation](https://www.afarmamentmuseum.com/details-gbu43.html)
[GBU-43 MOAB Archives | Air & Space Forces Magazine](https://www.airandspaceforces.com/weapons-platforms/gbu-43-moab/)
[European Security & Defence journal, 11-12/2023, p. 15 (PDF)](https://euro-sd.com/wp-content/uploads/2023/11/ESD_11_12_2023.pdf)

https://www.defense.gov/Multimedia/Photos/igphoto/2001732840/

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Not adding the procurement numbers because noting weapon stockpile numbers is just a mess we really don't want to get embroiled in.

**Comment by claudejdev** [comment]
Fair enough. It's more of a game(play) design tidbit.
Thanks!
