### ISSUE TITLE
France - Mistral (2) ATAM

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4157]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 1336, 3116

### Summary of Changes

- [x] 1336 Mistral ATAM
- Lnch Alt Max (ft): 15000
- Lnch Speed Max: 200
- Tgt Alt (m): 6000

- [ ] 3116 Mistral 2 ATAM
- Range: 4.3
- Lnch Alt Max (ft): 15000
- Lnch Speed Max: 200
- Tgt Alt (m): 6000
- Warhead: Fuze - Proximity

### Sources

[European Security & Defence journal, 11-12/2023, p. 10 (PDF)](https://euro-sd.com/wp-content/uploads/2023/11/ESD_11_12_2023.pdf)

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
