### ISSUE TITLE
RCS system tweak/update?

### ISSUE THREAD

**Issue by bqz2801** [PygmalionOfCyprus/cmo-db-requests#4158]
### DB Selector

DB3K

### Affected DBID(s)

RCS system

### Summary of Changes

**Create 4 radar band segments for RCS signatures:
(A-B), (C-D), (E-F), (G-M)** and take average rcs of each segment just as is done already
currently in game RCS is only in 2 segments: (A-D) and (E-M)
I recommend segmenting each band individually A-M (13 segments), but that might be a bit too much for now (maybe in the future? ;)

here Raleigh scattering and resonance reflection is shown to amplify RCS in lower bands by up to 30-40 dBsm, so a 0.0001m2 craft is reflected in the A/B bands as a 0.1m2 or 1m2 target. And so on for any other target size. From majority of RCS simulations, VHF/UHF can increase RCS up to 30 to 40dBsm and L-band can increase up to 15-20dBsm. Estimate is RAM reduces RCS of VLO by an average of 5 to 10 dBsm against A-D bands and up to a maximum of 15-20 dBsm against (E-M bands) for the newest VLO planes. 
![rcs 5](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/443f7608-d44a-41bd-92e6-a29bebfe48e9)
_here rcs simulations for F-35A (NO RAM) against VHF(A/B), L-band (C/D), S-band (E/F), and X band (I/J) from the front at vertical polarization._ 
**Results: VHF (W/O RAM=4.92m2, W/RAM=0.2m2) , L-band (W/O=1.08m2, W/=0.15m2), S-band (W/O=0.61m2, W/=0.01m2) , X-band (0.3m2, 0.005m2). So taking average of RCS W/RAM is (A/B bands = -10dBsm), (C/D bands = -15dBsm), (E/F bands = -20dBsm), and (I/J bands=-25 dBsm) and this is only from -60 to 60 degree viewing angle at vertical polarization. RCS fluctuates from different viewing angle, frequency and vertical/horizontal polarization. Vertical polarization creates most resonance and scattering for larger returns.**
![rcs screenshot](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/efc63977-ef64-4aca-af2d-bd3027925506)

as you can see F-35 with RAM coating fluctuates from -16 to -3dBsm (0.3m2-0.01m2) from frontal aspect against VHF
![rcs 7](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/cc30f436-b3b2-4fcc-b38f-67271a51a90f)

![rcs 9](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/2d8998e1-be89-479d-8abc-875ee08aa463)
![rcs 8](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/4a2c5888-06f1-49fb-9352-812b968cce04)

![rcs 6](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/40439ce8-d448-4313-a129-f237f9d7210f)

![293158647-8f81b45f-2c9b-4ace-81a4-c93e67512724](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/b1cdba76-e908-4394-82c6-0ba861a2dd94)
![rcs 3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/3b0c4718-0988-4d8c-81ff-18d3261bbf4c)
![rcs 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/376bb0ec-7bb3-46e5-ae29-21081fe6d2ac)
![rcs](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/5a84906e-1c12-42fe-b8bc-79b175d891f1)

notice how this I/J band simulation for a 6th gen prospective V-wing VLO stealth fighter with RAM coating shows RCS reflections. From the front and rear directly it is -40 to -50 dBsm at 180 degrees and at 0 degrees, but from both sides the RCS spikes to -10 dBsm and even up to 1m2 at 210 and 150 degrees. **The average frontal RCS (150 to 210 degrees) averaging at increments of 5 degrees, is -35 dBsm. Side average RCS from 60 to 150 degrees is -20 dBsm. Rear RCS is similar to front but larger at -30 dBsm.**
![v wing rcs](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/062af7a7-4d3a-4680-9fa7-3f552ee1a5f0)

### Sources
https://twitter.com/flankerchan

https://www.f-16.net/forum/viewtopic.php?f=55&t=14732&start=30

https://www.mdpi.com/2226-4310/9/11/734

https://forums.spacebattles.com/threads/rcs-simulation-of-f-35-with-and-without-aim-9x.1042794/

https://journals.sagepub.com/doi/abs/10.1177/09544100231204378?journalCode=piga

https://www.slideshare.net/javiergismero9/411-radar-cross-section-rcs

https://journals.sagepub.com/doi/abs/10.1177/09544100231204378?journalCode=piga

**Comment by PygmalionOfCyprus** [comment]
This is a pretty gargantuan change and I'm not going to track it through a ticket. Someone has to pay us for this, and if they do it'll enter our PM flow accordingly. That said, I don't disagree that there are improvements that can be made to our RCS system, so don't see this as a shootdown, just a "not now."

Be careful with these numbers though. They're functionally useless because all the information you actually need to run RCS simulations is classified. Creating a 3D model of a stealth fighter and running it through commercial RCS simulation tech is not a reliable source.

But again, there are definitely improvements we can make. Just not as a casual ticket.

**Comment by bqz2801** [comment]
> This is a pretty gargantuan change and I'm not going to track it through a ticket. Someone has to pay us for this, and if they do it'll enter our PM flow accordingly. That said, I don't disagree that there are improvements that can be made to our RCS system, so don't see this as a shootdown, just a "not now."
> 
> Be careful with these numbers though. They're functionally useless because all the information you actually need to run RCS simulations is classified. Creating a 3D model of a stealth fighter and running it through commercial RCS simulation tech is not a reliable source.
> 
> But again, there are definitely improvements we can make. Just not as a casual ticket.

I understand completely, but am interested in contributing for an RCS overhaul for maximum immersion (best we can achieve video game/simulator wise at least). These 3D models are the most accurate information out there that do the best estimates, word of mouth and generalized RCS figures from unknown military sources are better than nothing, but not the best

If there's a way to contact or PM, let me know. I enjoy this game a lot, would $1000 be reasonable to tweak RCS into 4 segments? Let me know, BTC, ETH, Paypal. I am happy to assist you guys with improving this game!

**Comment by PygmalionOfCyprus** [comment]
For any paid work I'd have to direct you to [Command: Professional Edition](https://www.matrixprosims.com/game/command-professional-edition); follow-on pricing for specific features would have to be determined by negotiation with the marketing and development teams directly.

I should clarify a little that by closing this ticket it wasn't my intention to say "never gonna happen without a million-dollar contract, get gud". More just that a rework of this scope is sort of beyond the intention of the DB issue tracker, which is more for "hey, this gun should be changed, etc." not "the fundamental basis of stealth in Command should be torn out and rebuilt from the ground up."

We are aware that there are many things we can improve with our stealth modelling, and it has a spot somewhere on the list of "things we'd like to do one day". But I don't want to keep a ticket open here for it. It's not the sort of job someone on the DB team picks up with their free time; it's something the dev team would all have to orient towards and add to our cyclical project plan.

**Comment by ghost** [comment]
> For any paid work I'd have to direct you to [Command: Professional Edition](https://www.matrixprosims.com/game/command-professional-edition); follow-on pricing for specific features would have to be determined by negotiation with the marketing and development teams directly.
> 
> I should clarify a little that by closing this ticket it wasn't my intention to say "never gonna happen without a million-dollar contract, get gud". More just that a rework of this scope is sort of beyond the intention of the DB issue tracker, which is more for "hey, this gun should be changed, etc." not "the fundamental basis of stealth in Command should be torn out and rebuilt from the ground up."
> 
> We are aware that there are many things we can improve with our stealth modelling, and it has a spot somewhere on the list of "things we'd like to do one day". But I don't want to keep a ticket open here for it. It's not the sort of job someone on the DB team picks up with their free time; it's something the dev team would all have to orient towards and add to our cyclical project plan.

Understood, thank you :)
