### ISSUE TITLE
Add Cabo San Juan (PV50M) class, Eq.Guinea navy

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#416]
### DB Selector

DB3K

### Hypothetical

No

### Name

Offshore Patrol Vessel (PBO), P400, Cabo San juan

### Class

Cabo San Juan (PV50M)

### Country

Equatorial-Guinea

### Service

Navy

### In Commission

2008 - present

### Length (m)

49.1

### Beam (m)

9

### Draft (m)

2.5

### Standard Displacement (t)

320

### Complement

30

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3516C, 2 shafts

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

3000 @ 14

### Sensors

2x generic navigation radar

### Mounts

1x twin 30mm/71 AK320
2x twin 25mm/82 2M-3M

### Aircraft & Docking Facilities

1 platform for small helo
1 small RHIB, launch/recover with small crane

### Comments

2 units in class

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/equatorial_guinea/eqgui_cf_cabo_san_juan.htm
![1](https://user-images.githubusercontent.com/99532490/155959695-8888ea79-4b64-440b-a3d6-fbdd788d90e7.jpg)
![pv-equatorial-guinea-usn-1087963](https://user-images.githubusercontent.com/99532490/155959698-266b056d-0d8c-48af-857f-9acce24f943f.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
