### ISSUE TITLE
P-40 Long Track for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4160]
### DB Selector

Both

### DBID to Copy

DB3k Facility 1763

### Hypothetical

Yes

### Name

as copy

### Country

Hungary

### Service

Army

### In Commission

1976

### Number in Service

10x, SA-6

### Other Changes

All normal

### Sources

SIPRI
Expected from presence of SA-6

**Comment by FrangibleCover** [comment]
Not hypo

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
