### ISSUE TITLE
PRV-9 Thin Skin A for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4161]
### DB Selector

Both

### DBID to Copy

DB3k Facility 1158

### Hypothetical

No

### Name

as copy

### Country

Hungary

### Service

Army

### In Commission

1977

### Number in Service

5x, SA-4 & SA-6

### Other Changes

All normal

### Sources

SIPRI

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
