### ISSUE TITLE
SA-4 Krug for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4162]
### DB Selector

Both

### DBID to Copy

DB3k Facility 1457

### Hypothetical

No

### Name

as copy

### Country

Hungary

### Service

Army

### In Commission

1977

### Number in Service

6x Bty

### Other Changes

All normal, but associated with Thin Skin A, not B

### Sources

SIPRI

**Comment by PavelNovak79** [comment]
Are you sure with year 1977 for Hungarian SA-4?
To my knowledge Hungary got its six batteries (organized in two battalions each with three batteries) only in 1981. The variant was 2K11M1 Krug-M1.

**Comment by FrangibleCover** [comment]
Nope, it's SIPRI info, I don't trust any of my dates that much and was going to go through and edit as I found sources. I wouldn't be surprised if the first TEL arrived in 1977 and actual operational capability was achieved in 1981. What's your source, I'll add it to the request.

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Added only to DB3K for now w/ '81 IS date.

**Comment by FrangibleCover** [comment]
Rapid work!

**Comment by PavelNovak79** [comment]
The year 1981 comes from SAM Simulator documentation. The author of it is from Hungary so probably with best available info.
