### ISSUE TITLE
P-18 Spoon Rest D for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4165]
### DB Selector

DB3K

### DBID to Copy

DB3k Facility 1317

### Hypothetical

No

### Name

as copy

### Country

Hungary

### Service

Army

### In Commission

?

### Other Changes

All normal, not sure when this entered service but to have P-18s to upgrade the Hungarians must have had base P-18s

### Sources

https://mh12.honvedseg.hu/haditechnika/

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
