### ISSUE TITLE
P-18H Spoon Rest for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4166]
### DB Selector

DB3K

### DBID to Copy

DB3k Facility 1317

### Hypothetical

No

### Name

Radar (Spoon Rest D [P-18H] Upgrade)

### Country

Hungary

### Service

Army

### In Commission

2002

### Sensors

Significantly improved sensor with digital processing, as detailed in the Arzenal link. Certainly Early 00s tech

### Other Changes

It is very funny to me how many of these modernisations I'm posting about include air conditioning as a big selling point.

### Sources

http://www.hmarzenal.hu/eng/defense-industry/p-18-radar.html
https://mh12.honvedseg.hu/haditechnika/

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
