### ISSUE TITLE
Tin Shield for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4167]
### DB Selector

DB3K

### DBID to Copy

DB3k Facility 1402

### Hypothetical

No

### Name

as copy

### Country

Hungary

### Service

Army

### In Commission

1986

### Number in Service

11x, final delivery 1990

### Other Changes

All normal. Locally designated SZT-68U because Hungarian uses 'SZ' for an S sound, but no other Tin Shields have the ST-68U name so up to you if you apply it.

### Sources

https://mh12.honvedseg.hu/haditechnika/
https://www.microwavejournal.com/articles/1339-metric-radars-win-reprieve-in-hungary
![ST-68U_02](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/54107da8-9692-4d08-ac78-fd3d63d912ea)
Tin Shield in a Hungarian museum

**Comment by PavelNovak79** [comment]
Hungary got 9 ST-68U [Tin Shield A] radars.

Export in years:
1985 - 1
1986 - 1
1987 - 3
1988 - 2
1990 - 2

I don't know for sure if these years are really years of delivery and not just that the equipment was accepted for export. But delay should not be more than one year at most.

Also to my knowledge Hungary has not received ST-68UM (36D6) [Tin Shield B]. At least not during Warsaw Pact time (I don't have reliable data after the end of the Cold war).

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
