### ISSUE TITLE
Modernised SA-6 for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4168]
### DB Selector

DB3K

### DBID to Copy

DB3k Facility 2563

### Hypothetical

No

### Name

SAM Bn (SA-6a Gainful [2K12 Kub] Upgrade)

### Country

Hungary

### Service

Army

### In Commission

2003

### Number in Service

3x Bn

### Sensors

- Straight Flush modernised to Early 00s standard.
- TV Camera replaced by "WZU-2" sensor group with a modern thermal imager and laser rangefinder (assessed). May also have a modern LLTV camera (note page 292 of the first source states "television or thermal", WZU also produce the #4148 optical sensor with two cameras.)

### Other Changes

Digital Combat System and OODA. The K1P Fire Distribution Centre (probably a single unit) has Link 11B, which could be given to the SAM system given that Command doesn't usually represent intermediate C2 nodes for SAMs.

### Sources

https://epa.oszk.hu/04200/04298/00001/pdf/EPA04298_AARMS_2014_2_283-293.pdf
https://mh12.honvedseg.hu/haditechnika/

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
