### ISSUE TITLE
Wrong Aircraft Loadout setting causes RTB (mission over) immediatelly after take off

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#4169]
### DB Selector

DB3K

### Affected DBID(s)

Aircrafts 2639, 2611, 878, 6835, 1368

### Description of Problem

These aircrafts (MiG-23M and MiG-23MF) have in Aircraft Loadouts for their main air to air weaponry (AA-7 Apex A or AA-7 Apex B) setting "(Air Superiority, **WVR** AAMs)".

This causes problem because actual loadout with AA-7a [R-23R] or AA-7b [R-23T] has BVR logic and when sent to AAW Patrol mission with EMCON/WRA setting "Inherited, Use loadout setting" - i.e. standard setting without any change, the flight will go to "RTB (mission over)" immediatelly after take off.

For comparison all other interceptor variants of MiG-23 equipped with AA-7 Apex missiles has there "(Air Superiority, **BVR** AAMs)" and work correctly.

See also thread on tech support forum here: https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=399885

### Recommended Fix

Change in database setting with their AA-7 Apex missiles (both Apex A [R-23R] and Apex B [R-23T]) from "(Air Superiority, **WVR** AAMs)" to "(Air Superiority, **BVR** AAMs)".

**Comment by PygmalionOfCyprus** [comment]
Now how on Earth did that happen? Handled 505.

**Comment by PavelNovak79** [comment]
No idea but thanks for quick solution!
