### ISSUE TITLE
Missile datalink has bug on China Type 055 Renhai Destroyer and HHQ-9B missile cannot work in DB3K v504

### ISSUE THREAD

**Issue by ywturbo** [PygmalionOfCyprus/cmo-db-requests#4171]
### DB Selector

DB3K

### Affected DBID(s)

Ship #2884, 3883

### Summary of Changes

In new-released DB3K_v504 the HHQ-9B SAM on the Type 055 Destroyer cannot work, possibly because guidance of the new "China CEC" datalink for the missile is missing, which should be a bug.

### Sources

In previous DB, the HHQ-9B was guided by SA-10 Command Datalink.

**Comment by LuigiP57** [comment]
Or just add the current China CEC datalink on the weapon?

**Comment by LuigiP57** [comment]
I also found that the 054B is missing the HQ-16C data link. Add a datalink to the ship or a CEC datalink to the HQ-16C?

**Comment by PygmalionOfCyprus** [comment]
Closing in favor of #4172
