### ISSUE TITLE
Datalink issue of PLAN in DB 504 summary

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4172]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3883 2834 2296 3586 3587 1965 2495 2714 4444; weapon 4090 4362

### Summary of Changes

- [x] 1. The type 055 DDGs (2834 3883) only have 24-channel CEC datalink which can't guide the HHQ-9B. 
- [ ] 2. The type 054B (4444) has no datalink for HQ-16C.
- [ ] 3. The type 052D DDGs (2296 3586 3587) only have 24-channel HHQ-9B(SA-10) datalink but no CEC datalink.
- [ ] 4. The type 054A FFGs (1965 2495 2714) have no HQ-16(SA-17) datalink.
- [ ] 5. I propose to add China CEC datalinks to the HQ-16C and HHQ-9B to enable them to achieve the CEC capability of some of the PLAN ships.
- [ ] 6. Is it necessary to classify China CEC datalink as a datalink of the same type as Aegis weapon datalink? I don't seem to see the description of China datlaink in "type". Can it provide fire control data for weapons?

### Sources

No need

**Comment by LuigiP57** [comment]
#4171

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus @Jkryos  it necessary to classify China CEC datalink as a datalink of the same type as Aegis weapon datalink? I don't seem to see the description of China datlaink in "type". Can it provide fire control data for weapons?

**Comment by PygmalionOfCyprus** [comment]
I fixed the issue with the Type 055s; while I was at it, I finally untethered the HHQ-9s from the Russian DLs and gave them their own proper network.

Re: the HQ-16 issues, the HQ-16 is SARH, so no datalink. The DL on the weapon looks to have been left over from the bad old days where we didn't model SARH. I've not added DLs to the ships for this, but rather removed the DL from the HQ/HHQ-16s, which should fix the problem and make them behave properly.

Re: # 3, do we have any indication that the 052Ds actually have CEC? This is a very nascent capability for China and the 052D is not a brand-new design. I do not see the AESA CEC array that is present on the newer vessels.

Re: # 5/6, it's also not clear to me what the capabilities of China's CEC actually are. Hence the generic at this point -- it's mostly there just to indicate a capability to fill out later once we get more info. I'm quite sure that it doesn't work with the HHQ-16 because, as mentioned, HQ-16s do not use a datalink. It may also not link directly to the HHQ-9, which uses TVM; it's possible the "CEC" is just a "hey, you, shoot the missile here and let it figure it out" capability rather than true best-sensor-best-shooter guidance. True CEC may be waiting for new variants or new missiles.

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus 

> Re:` the HQ-16 issues, the HQ-16 is SARH, so no datalink. The DL on the weapon looks to have been left over from the bad old days where we didn't model SARH. I've not added DLs to the ships for this, but rather removed the DL from the HQ/HHQ-16s, which should fix the problem and make them behave properly.

So how to explain the SM-2 series SARH's Aegis Weapon Link? I think it is reasonable that modern SARH missiles have a datalink mid-course redirect capability. Even if the HQ-16A does not have this function because of the outdated "copy" technology, the HQ-16B/C should be able to.

**Comment by PygmalionOfCyprus** [comment]
>So how to explain the SM-2 series SARH's Aegis Weapon Link?

SM-2 (at least, most variants) is not a purely SARH missile; it also has command guidance. This is widely reported. There is absolutely no indication that the HQ-16 has this capability, even the newer versions.

**Comment by LuigiP57** [comment]
> > So how to explain the SM-2 series SARH's Aegis Weapon Link?
> 
> SM-2 (at least, most variants) is not a purely SARH missile; it also has command guidance. This is widely reported. There is absolutely no indication that the HQ-16 has this capability, even the newer versions.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/387555c5-5b0e-4f7f-bbbb-5afdfc3778ac)
It seems that we can only see information about "medium modified command" directly in the HQ-16FE. So what are you going to do with the HQ-16FE and its "naval variant"? The Pakistan Air Force appears to have announced that it has already operated this system。
https://twitter.com/Defence_IDA/status/1747156963450867724
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/19dcc15c-d526-4e8e-a248-7d123c5e4739)
#3772

**Comment by PygmalionOfCyprus** [comment]
Hm...interesting. I don't put a lot of faith in that machine translation, but I also found [this article](https://www.china-arms.com/2023/10/china-improved-054a-frigate-launches-hq16c-missile/) (not exactly a reliable source, but still) that indicates the B/C variants have "inertial guidance combined with mid-course command updates and terminal active/passive radar guidance." You may be right about the DL after all. I will do a little more hunting to see if I can find a more reliable source, but I'm now leaning towards giving the newer variants a DL as well like you suggeted.

**Comment by LuigiP57** [comment]
> Hm...interesting. I don't put a lot of faith in that machine translation, but I also found [this article](https://www.china-arms.com/2023/10/china-improved-054a-frigate-launches-hq16c-missile/) (not exactly a reliable source, but still) that indicates the B/C variants have "inertial guidance combined with mid-course command updates and terminal active/passive radar guidance." You may be right about the DL after all. I will do a little more hunting to see if I can find a more reliable source, but I'm now leaning towards giving the newer variants a DL as well like you suggeted.

I think that makes sense: the longer the range of the missile, the more likely you are to need a mid-course redirect, because you need more time to reach the target. The early HQ-16A had too short a range to necessarily redirect the data link. However, now the updated version of B/C has achieved the effective range of twice and even further F/FE. Therefore, mid-course updates become necessary.

In addition, a data chain with more channels allows more SARH to stay in the air, waiting for the FCR to change targets to intercept rather than self-destruct. This is necessary for modern warships

**Comment by PygmalionOfCyprus** [comment]
Agreed, then. New DL created/added to the HQ-16B/Cs, and appropriate command DLs added to the carrying ships (4444, 4582, 4593, 4725).
