### ISSUE TITLE
China, YJ-100 ASCM/LACM, capability upgrade

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4178]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3210; Ship 2296 3586 3587

### Summary of Changes

1. Give YJ-100 "Land Structures (Hard), Land Structures (Soft), Runways" in valid targets. It's a LACM with a seeker that makes it anti-ship. Similar to Tomahawk Blk IV MMT.
2. The type 052Ds use the same UVLS as the type 055s. Maybe you can add the YJ-100 record on the 052D UVLS as well. Various sources have long hinted at its land strike capability.

### Sources

https://en.wikipedia.org/wiki/CJ-10_(missile)#cite_note-4
https://navyrecognition.com/index.php/news/defence-news/2020/july/8725-pla-s-upgraded-type-052d-destroyer-sails-for-the-first-time-amid-rising-tensions.html
https://thediplomat.com/2018/08/china-launches-14th-type-052d-guided-missile-destroyer/

**Comment by PygmalionOfCyprus** [comment]
Added land-attack capability with default WRA restricting its use. Seems fair that there'd be some residual capability, but I can't imagine anything but the most desperate situation in which you'd want to slam your nice anti-ship missile in INS mode against a land target.

Disagree on the 052D VLSes. There are different variants of the GJB 5860-2006 standard VLS (3.3m, 7m, or 9m deep) and the 055's is deeper than the one on the 052Ds, which means it can't use the YJ-100 -- at least as of my last research.

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus 
After my investigation, I find that your original statement may be wrong. I think the 052d series can carry the YJ-100 to perform land attack mission.

The YJ-18 was supposed to be an 8.2m long 3M54E instead of a 6.2m long 3m54E1. The 3m54e1 is more likely the technical basis for the long-rumored YJ-18 land-attack version. The 8.2m long YJ-18 can only be loaded into the 9m long UVLS, so the 052d is also naturally capable of carrying the YJ-100, or even the YJ-21 (aprx 8.3m long).

I hope you could reconsider this ticket. Usually, an OSINT article can't cover all the details, so we need to gather more information.

https://en.wikipedia.org/wiki/Kalibr_(missile_family)
https://en.missilery.info/missile/3m54e1
https://en.wikipedia.org/wiki/GJB_5860-2006
@claudejdev Dude, I am hoping you could offer some information, too.

**Comment by claudejdev** [comment]
>  @claudejdev Dude, I am hoping you could offer some information, too.

@LuigiP57 
Not sure to understand the question :/

Please DM me on Discord, it will be much more efficient.

**Comment by LuigiP57** [comment]
> > @claudejdev Dude, I am hoping you could offer some information, too.
> 
> @LuigiP57 Not sure to understand the question :/
> 
> Please DM me on Discord, it will be much more efficient.

I just hope you can provide some reliable information to support/correct my opinion. :)

**Comment by claudejdev** [comment]
I would check the Chinese version of the pages you've mentioned. That usually leads to better source material. (Google translate on right click helps with any language).
I would also check the Sinodefence forum. It's a good place to get a feeling of the current level of open knowledge on a given platform.
Then check the Western think Tanks' publication. (Will drop a link when I'll be back home)
In last resort, check Jane's yearbooks.
PS: forgot to mention the Harpoon 5 data annex by Admiralty Trilogy. The end product is different but they are very knowledgeable and use the same sources as we are.

Right now, that's the best I can do for you mate.

**Comment by claudejdev** [comment]
@LuigiP57 

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/89efdaee-c482-495f-b5b3-0f6a3d2a3c38)
https://www.sinodefenceforum.com/t/chinese-cruise-and-anti-ship-missiles.4368/post-1029137
It remains to be confirmed that the "YJ-100" variant is even real.

None of my sources mentions it, or the YJ-12 for that matter, aboard the 052D [Luyang III] class.

Here's an example of a "Western Think Tank" type of source I was referring to earlier: https://www.andrewerickson.com/

Tell me your Matrix forum ID :)
