### ISSUE TITLE
RCAF CH-178 (Mi-17V5 Hip H) x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#418]
### DB Selector

DB3K

### DBID to Copy

3879 DB3K

### Hypothetical

No

### Name

CH-178 

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2008-2011

### Sensors

- Add 1x Generic Missile Warning System

### Mounts

- Add 1x Generic Flare

### Loadout Options

- Remove Troops/Rocket loadout
- Add SOF Troopers loadout

### Sources

https://army.ca/forums/threads/ch-178.132604/
https://www.silverhawkauthor.com/post/canadian-warplanes-7-mil-17-v5-hip-ch-178-helicopter
https://www.helis.com/database/modelorg/Canada-Mil-17/
https://en.wikipedia.org/wiki/Mil_Mi-17#Former_operators
http://www.rwrwalker.ca/post_int.html

![60fc792891528e70755da4fb_Mi-17-Hip--RCAF--Serial-no--178405---Afghanistan](https://user-images.githubusercontent.com/99632305/156044947-cb945b01-87b7-43c9-9b98-202f50820811.jpg)
![helo jpg 14d84f061645235e32a0c12b4be62551](https://user-images.githubusercontent.com/99632305/156045130-9f1b2b17-bed2-4b75-bb7a-97d601cc51c9.jpg)

![CH-178](https://user-images.githubusercontent.com/99632305/156043791-70104a36-0fdb-4eef-ada8-886b847097e7.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
