### ISSUE TITLE
SA-16 mobile twin mount for Hungary

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4183]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Plt (SA-16 Gimlet [9K310 Igla-1] Láma Twin Mount x2)

### Facility Type

SAM

### Country

Hungary

### Service

Army

### In Commission

1990?-2011

### Sensors

Mk.1 Eyeball

### Mounts

2x Twin SA-16 Gimlet on GAZ-66 - Capacity 2, copy DB3k Mount 2868

The number of mounts is a pure guess based on a mention of these being operated alongside SA-9, which comes in two vehicle sections as well.

### Magazines

Uhhhh 8? Honestly you could set this to nearly anything, but one of the images appears to have two boxes for reloads in the truck, which means 4x reloads per mount.

### Comments

Very little hard info about this thing available. Mention of 1L15-1 display connected by datalink to PU-12 command post but I think that's common to a lot of AD systems and therefore a whole other job.

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109925704/9a04c410-b41b-4075-b3a9-65d309152e2f)
https://szentkoronaradio.com/blog/2015/10/24/legvedelem-alapveto-eszkozok-nelkul-ii-resz/
https://legiero.blog.hu/2008/12/31/lerakos_hianypotlas_mea_culpa

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
