### ISSUE TITLE
China, Type 346A/B, Just one operating band for surveillance?

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4186]
### DB Selector

DB3K

### Affected DBID(s)

sensor 5127 5963 6093

### Summary of Changes

I would like to quote this link https://www.radartutorial.eu/19.kartei/07.naval/karte054.en.html in #2056 to illustrate my opinion. 

As for the "dual-band" issue mentioned in the previous link, I agree that its purpose is to achieve surveillance and fire control. However, now that we have distinguished the surveillance and fire control bands, there is no need to use the "F/G" surveillance bands that still exist in the DB.

Why is it best to have only one surveillance band? Because I found that any sensor using the "X/Y "band, their search range compared to the "X" or" Y "single band sensor, the detection range will be significantly reduced. Maybe it would be better if we just gave 346A/B the "F" band, the common radar surveillance band.

### Sources

common sense

**Comment by PygmalionOfCyprus** [comment]
You're right. #2056 should have been handled by implementing distinct F band frequencies for Search/Track and G band frequencies for Illumination. Handled 505.
