### ISSUE TITLE
China, Y-20U, extra fuel capacity for tanker version

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4187]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4975

### Summary of Changes

Next, you seem to be preparing to review PLAAF equipment. Here's what I just found:

I noticed there was no difference in fuel between the Y-20U and its original version. The KC-10, KC-135, IL-78M and other tankers in the database have increased fuel capacity by about 40% to 50% compared to their basic versions.

Therefore, I think it is possible to add some reasonable fuel capacity to the Y-20U on the basis of the current fuel capacity of the Y-20 series (about 450,00kg /45 tons? Its maximum load is 66 tons).

### Sources

https://en.wikipedia.org/wiki/Xi%27an_Y-20

**Comment by claudejdev** [comment]
• YY-20A: Y-20A converted to tanker, inflight refuel N/3P. Retains transport capability.
Estimated total fuel 105500 kg with 5315 nmi range. _[that is our "radius"]_ In service Aug 2022.
• Y-20A:  Int Fuel: 77500 kg
• Y-20B: Planned version with domestic WS-20 engines, estimated payload 66000 kg. First flight of prototype Nov 20. Possibly in service 2024.
Bond, Larry, and Carlson, Chris, and Grining, Peter, [i]China’s Navy: Ships and Aircraft of the People’s Republic of China 1955 – 2021[/i], 2021(+err. 2023)


Pic:
https://www.sinodefenceforum.com/t/chinas-transport-tanker-heavy-lift-aircraft.197/post-1043607
In the same thread, the opinion is that Y-20B(that is with the domestic WS-20 engine) will be a flexible platform, such as the MRTT.
It's all opinions, no data, as it's the only thing that is safe to say there.


YY-20A Kunpeng/Roc (bottom)
https://chinese-military-aviation.blogspot.com/p/transport-tanker.html


PS: I may have misunderstood something, maybe you can clarify it for me, @LuigiP57 : wasn't the consensus that we just hold on our requests until the DB team has published their own research?

Cheers

**Comment by LuigiP57** [comment]
> • YY-20A: Y-20A converted to tanker, inflight refuel N/3P. Retains transport capability. Estimated total fuel 105500 kg with 5315 nmi range. _[that is our "radius"]_ In service Aug 2022. • Y-20A: Int Fuel: 77500 kg • Y-20B: Planned version with domestic WS-20 engines, estimated payload 66000 kg. First flight of prototype Nov 20. Possibly in service 2024. Bond, Larry, and Carlson, Chris, and Grining, Peter, _China’s Navy: Ships and Aircraft of the People’s Republic of China 1955 – 2021_, 2021(+err. 2023)
> 
> Pic: https://www.sinodefenceforum.com/t/chinas-transport-tanker-heavy-lift-aircraft.197/post-1043607 In the same thread, the opinion is that Y-20B(that is with the domestic WS-20 engine) will be a flexible platform, such as the MRTT. It's all opinions, no data, as it's the only thing that is safe to say there.
> 
> YY-20A Kunpeng/Roc (bottom) https://chinese-military-aviation.blogspot.com/p/transport-tanker.html
> 
> PS: I may have misunderstood something, maybe you can clarify it for me, @LuigiP57 : wasn't the consensus that we just hold on our requests until the DB team has published their own research?
> 
> Cheers

My basic idea is to distinguish the fuel capacity of the basic model and the refueling model, replacing the current no difference in DB. I have stated a rough proportion above, and this number should not exceed the known maximum load. Beyond that, don't get hung up on the numbers.

I am just afraid that this might be missed, so I made an "unnecessary" reminder.

**Comment by PygmalionOfCyprus** [comment]
Handled 506 as part of ongoing China review.
