### ISSUE TITLE
Addition: 052DL no. 30

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4188]
### DB Selector

DB3K

### DBID to Copy

Ship 3586

### Hypothetical

Yes

### Name

052DL

### Country

PRC

### Service

PLAN

### In Commission

2025

### Sensors

Remove Type 364, add sensor 7279. 

### Sources

https://twitter.com/foolsball/status/1749351755714846882
https://zh.wikipedia.org/zh-cn/052D%E5%9E%8B%E5%AF%BC%E5%BC%B9%E9%A9%B1%E9%80%90%E8%88%B0

**Comment by PygmalionOfCyprus** [comment]
Added as the nameship of the Type 052D(L) Batch 4, and added batch numbers to the other Type 052Ds. (Also updated the IS Date of Nanjing to 2018). Handled 505.
