### ISSUE TITLE
P-14 radar [Tall King A] for Hungary

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#4189]
### DB Selector

CWDB

### DBID to Copy

entry 81 in CWDB

### Hypothetical

No

### Name

Radar (Tall King A [P-14])

### Country

Hungary

### Service

Air Force

### In Commission

1967

### Number in Service

2

### Sensors

no changes

### Mounts

no changes

### Other Changes

no changes

### Sources

Soviet export charts. Provided year could be just year of export acceptance with delivery later but I don't have anything better. No idea when they were discarded though here:    https://wikimapia.org/16834227/hu/P-14-radar-helye   is mentioned that on this place one of them was deployed in 1979. So this request is for adding Tall King A only to CWDB database.

Also export chart mentions single Oborona-14 (5N84AE [Tall King C]) in year 1985 to Hungary. This one is already in database including information that only one was there. Maybe date of availability of 1985 could be added as the entry is in both databases - in CWDB as entry 63 and in DB3000 as entry 267.

Sorry for being late with Hungry for Hungary.

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
