### ISSUE TITLE
Add: Isla de Corisco (Shaldag Mk II) class ships, Equatorial-Guinea Navy 

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#419]
### DB Selector

DB3K

### Baseline

#3445(Senegal), #3091(Nigeria), #536(Israel)

### Hypothetical

No

### Name

Patrol Boat (PBF), -, Isla de Corisco

### Class

Isla de Corisco (Shaldag Mk II)

### Country

Equatorial-Guinea

### Service

Navy

### In Commission

2005 - present

### Length (m)

24.8

### Beam (m)

6

### Draft (m)

1.2

### Standard Displacement (t)

50

### Full Displacement (t)

56

### Complement

10 (src1), 15 (src2)

### Primary Propulsion Type

Diesel

### Propulsion

2x Deutz-MWM TBD604 BV16 diesels, 2 waterjets

### Flank Speed (kt)

50

### Range (nm) at Speed (kt)

700 @ 32 (src1), 850 @ 16 (src2)

### Sensors

1x Furuno Navigation radar
MSIS E/O system (src2)

### Mounts

1x twin 23mm/82 ZU-32-2 (src1)
2x single 7.6mm/90 (src1&2)

### Aircraft & Docking Facilities

Can hold 1 RHIB astern

### Ship Codes

All Aluminum Construction

### Comments

No Image found

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/equatorial_guinea/eqgui_cf_isla_de_corisco.htm
3: https://www.naval-technology.com/projects/shaldag-class-fast-patrol-boat
4: https://www.israel-shipyards.com/naval-002.asp

**Comment by PygmalionOfCyprus** [comment]
Added 494.
