### ISSUE TITLE
5N87 [Back Trap] for Hungary

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#4190]
### DB Selector

Both

### DBID to Copy

entry 168 in CWDB and entry 257 in DB3000

### Hypothetical

No

### Name

Radar (Back Trap [5N87E, Kabina-66])

### Country

Hungary

### Service

Air Force

### In Commission

1978

### Number in Service

5

### Sensors

no change

### Mounts

no change

### Loadout Options

no change

### Other Changes

no change

### Sources

Soviet export charts. Hungary got two 5N87E (Kabina-66) [Back Trap A?] radars in 1978 and 1979 respectively (again years could be just acceptance of export) and three improved Kabina-66M [Back trap B?] radars in 1987.

In game we have just one variant of Back Trap and probably no need to create more variants of it so request is for just adding one Back Trap entry for Hungary with 5 radars total and start date of 1978.

Here:    http://www.kozlonyok.hu/kozlonyok/Kozlonyok/13/PDF/2017/1.pdf    - this Hungarian list mentions military instruction for 5N87E from 1979

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
