### ISSUE TITLE
S-200 [SA-5] in Hungary - correction

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#4192]
### DB Selector

DB3K

### Affected DBID(s)

entry 518 in DB3000

### Summary of Changes

1) add starting year of availability 1986 - currently olny 19XX here

2) change name to:    SAM Grp (SA-5b Gammon [S-200VE Vega-E], 2xBn)
--- SAM Simulator documentation gives "Vega-VE" but looking at it in the export chart there is "Vega-E" so that is probably better

3) change missile loadout from current "SA-5c Gammon [5V28M5]" to "SA-5b Gammon [5V28]"
--- see discussion here:    https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4112
--- I think that this will better represent capacity of Cold War export SA-5

### Sources

Soviet export charts and also SAM Simulator documentation which can be downloaded here:   https://sites.google.com/site/samsimulator1972/home

**Comment by PygmalionOfCyprus** [comment]
Changed IS date and name, will handle missile rework w/ #4112
