### ISSUE TITLE
JDS Kuroshio (SS-501)

### ISSUE THREAD

**Issue by Eboreg2** [PygmalionOfCyprus/cmo-db-requests#4193]
### DB Selector

CWDB

### Baseline

SS-214 Gato Class -- United States (Navy), 1941-1954

### Hypothetical

No

### Name

SS-501 Kuroshio

### Class

Gato-class

### Country

Japan

### Service

Navy

### In Commission

1955-1966

### Number in Service

1x

### Length (m)

95

### Beam (m)

8.3

### Draft (m)

5.2

### Standard Displacement (t)

1525

### Submerged Displacement (t)

2424

### Complement

60

### Primary Propulsion Type

Diesel/Electric

### Propulsion

4 × Hooven-Owens-Rentschler (H.O.R.) diesel engines

### Flank Speed at Surface (kt)

21

### Flank Speed Submerged (kt)

9

### Range (nm) at Speed (kt)

11,000 nm at 10 kts

### Sensors

(Unknown)

### Mounts

10 × 21-inch (533 mm) torpedo tubes

### Magazines

24x Torpedoes

### Comments

The submarine in question was the Gato-class submarine USS Mingo which was transferred to the JMSDF in 1955 as an underwater training target

### Sources

https://en.wikipedia.org/wiki/USS_Mingo_(SS-261)

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
