### ISSUE TITLE
Adaptable Deck Launcher

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4194]
[https://www.navalnews.com/naval-news/2023/07/bae-systems-awarded-next-generation-launcher-design-contract/](url)

For a two cell launcher, provision for:
2x SM-2MR Blk IIIC
8x RIM-162E or 
8x RIM-162F (for none-AEGIS carriers)
with 180deg launch arc.

[https://youtu.be/aal4hM2Q7UA?si=K_wjt9xvupt2dpMd](url)
Add hypothetical carriers- 
LCS Freedom (2x) and Independence class (4x), 
LPD 17 class (4x)
FFG 62 class (4x)

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Added the mount so players can manually swap it in, but I'm not gonna make distinct ship entries until this moves a little further along.
