### ISSUE TITLE
Loss of Rapport for Turkey

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4197]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Aircraft 1174, 669, 675, 3521, 3522, 3518

### Summary of Changes

Currently all Turkish F-16s have the RAPPORT III DECM system. This system did not arrive until 1992, so the 1988/1989 aircraft should have it removed completely:
- [ ] 1174
- [ ] 675
- [ ] 3521
- [ ] 3518
And then I'm not really sure what the 1991 aircraft are representing, they don't appear to be different from the base variants, but probably do the same:
- [ ] 669
- [ ] 3522

I'm not sure what the first aircraft to get RAPPORT were, F-16.net says it was the Block 50s which can't be right. Possibly it would be fitted right onto new-build Block 40s as they come off the line, possibly it would go on the oldest Block 30s as they come in for checks?

### Sources

https://www.forecastinternational.com/archive/disp_old_pdf.cfm?ARC_ID=653
Janes JDW 09 May 1992 - says it takes about a month to refit an F-16 to take RAPPORT
https://www.f-16.net/f-16_users_article21.html

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
