### ISSUE TITLE
copy FPS-100 and FPS-89 radar to Iran

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#4198]
### DB Selector

DB3K

### DBID to Copy

362, 1605

### Hypothetical

No

### Name

Radar (AN/FPS-100), Radar (AN/FPS-89 HF)

### Country

Iran

### Service

Air force

### Number in Service

at least 4 of each

### Sources

https://web.archive.org/web/20120315193038/http://www.exreps.com/Photos/PeaceRuby/index.shtml

https://en.topwar.ru/30817-iranskie-sredstva-kontrolya-vozdushnoy-obstanovki.html

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
