### ISSUE TITLE
Jiangkai II SAM Datalinks-SAMS Can't Fire

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4199]
### DB Selector

DB3K

### Affected DBID(s)

All Jiangkai II

### Summary of Changes

Make sure Radar and Missile datalinks match up.

### Sources

Attached Scenario. A lot of units get smacked before they can legally fire due to OODA, but you should be able to see with a couple that you get datalink errors once they clear the OODA restriction.

**Comment by bostonmyk** [comment]
[Jiangkai SSM2.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/14054425/Jiangkai.SSM2.zip)

**Comment by bostonmyk** [comment]
Ah update Pakistani Jiangkai II to match when ready.

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #4172
