### ISSUE TITLE
USS Preble DDG 88 is first HELIOS armed ship IOC 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#42]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3140

### Summary of Changes

USS Preble DDG-88 will be the first Helios armed ships. Add aft Phalanx like ODIN armed ships See second picture for already installed CIWS. There is a separate DB entry for Preble in 2015 #3150 that could be used as well.

### Sources

https://news.usni.org/2021/04/07/navy-installing-more-directed-energy-weapons-on-ddgs-conducting-land-based-laser-testing-this-year
https://i.imgur.com/eDxWymT.jpg

**Comment by PygmalionOfCyprus** [comment]
Replaced the extant McCampbell entry w/ HELIOS-equipped Preble for 493.
