### ISSUE TITLE
RCAF CH-113 Labrador x6

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#420]
### DB Selector

CWDB

### DBID to Copy

667 CWDB

### Hypothetical

No

### Name

CH-113 Labrador

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1963-2004

### Sensors

- Replace Radar with Bendix weather radar or generic weather radar

### Mounts

- Remove gun mounts

### Loadout Options

- Remove CSAR loadout
- Add SAR loadout to existing loadouts
- Remove Troop loadouts 12 and 24
- Add Passenger loadout for 18

### Other Changes

Service period 1963-2004, copy to DB3K as well please.

### Sources

https://documents.techno-science.ca/documents/CASM-Aircrafthistories-BoeingVertolCH-133ALabrador.pdf
https://en.wikipedia.org/wiki/Boeing_Vertol_CH-46_Sea_Knight#Canada
https://www.silverhawkauthor.com/post/canadian-warplanes-7-boeing-vertol-ch-113-labrador-and-ch-113a-voyageur-helicopter
https://www.helis.com/database/modelorg/CH-113-Labrador-Canada/
http://www.rwrwalker.ca/CAF_Vertols_detailed_list.htm

![60fc76f83bfe3aa856c0237a_CH-113-Labrador-11308--YHM--Hamilton--June-5--2004--Andy-Vanderhayden](https://user-images.githubusercontent.com/99632305/156106068-64ed741c-164b-4a80-ada4-863faa970d3b.jpg)

**Comment by Jkryos** [comment]
Added both DB3K and CWDB 494.
