### ISSUE TITLE
Type 055 HHQ-9B SAMS can't fire due to datalinks

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4201]
### DB Selector

DB3K

### Affected DBID(s)

Type 055s

### Summary of Changes

Datalinks missing on ship.
[Type 055 Tests.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/14055916/Type.055.Tests.zip)

### Sources

Testing

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #4172

**Comment by bostonmyk** [comment]
Excuuuuuuse me. Had a few so I tested today. My mistake.
