### ISSUE TITLE
Add hard targets to PrSM Spirals 1/2/3

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#4202]
### DB Selector

DB3K

### Affected DBID(s)

Weapons 3843, 3844, 3845, 3846, 3847, 3848

### Summary of Changes

Add Land Structures (Hard) and Mobile Units (Hard) to valid targets.

### Sources

Original PrSM has these as valid targets.

**Comment by PygmalionOfCyprus** [comment]
Is PRsM even capable against hardened targets? Unless they've changed the warhead plans, LM shows it with a superfrag warhead. They're pretty nifty but I don't think even fancy tungsten frags are gonna penetrate hard targets.

https://www.youtube.com/watch?v=28zfSkhbSFA&t=167s

**Comment by FIM43-Redeye** [comment]
In that case, I feel like the _original_ PrSM should have hardened targets removed. Still, though, M74 submunitions are good for AT work, and tanks are in the DB as mobile hard targets. If not land hard targets, then mobile, at least.

**Comment by HunterDNiu** [comment]
Also, unitary PrSM has no effect to surface ships.

**Comment by PygmalionOfCyprus** [comment]
Removed hard land targets from original PrSM (but added/kept hard mobile targets so you can shoot them at tanks). Also added hypothetical HE warhead variants.

**Comment by FIM43-Redeye** [comment]
Don't know if I can reopen this, but Spiral 2 and 3 HE don't have hard land targets. Looks like just a small oversight to me.
