### ISSUE TITLE
Alteration to the placeholder for Dreadnought SSBN 

### ISSUE THREAD

**Issue by JByfield76** [PygmalionOfCyprus/cmo-db-requests#4205]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 761 in DB v504

### Summary of Changes

I’m really glad that you’ve added a placeholder for the Dreadnought class. I have noticed it’s currently the Vanguard with an increased displacement. Below are the changes that will get the profile closer to the the real vessel. 

Probable Pennant Numbers for the vessels:
S32 to S35

Vessel Names (these have been confirmed by the MoD) 
Dreadnought, Valiant, Warspite, George VI

Changes to weapons:
The number of VLS for Tridents is incorrect, also a new warhead will be deployed on them. 
•	12 x Trident II D5 with improved warheads probably similar to the US' W93
•	4 x Torpedo Tubes, with 20 Spearfish 
•	2 x SSE Mk10, with 2 x SCAD 200, 4 x SCAD 104, 20 rounds in total

Changes to Sensors:
The sensor suite given in the placeholder is the same as the Vanguard class – a whole generation behind what will be availble for this class. The sensor set below matches the same sensors on the Astute class SSN.
•	1 x Type 1007 Radar 
•	1 x UAP-3 ELINT 
•	1 x Type 2072 (Type 2076 Suite)
•	1 x Type 2079 (Type 2076 Suite)
•	1 x Type 2065 (Type 2076 Suite)
•	1 x Type 2082
•	1 x CM1010 LLTV Component (Periscope)
•	1 x CM1010 IR Component (Periscope) 
•	1 x CM1010 QLR IR Component (Periscope) 
•	1 x Mk1 Eyeball

Changes to Noise Levels: 
There are further noise level reduction technologies being implemented on the Dreadnought, it uses a Turbo-Electric drive an uses an X design of rudder. 

### Sources

https://en.wikipedia.org/wiki/Dreadnought-class_submarine
https://en.wikipedia.org/wiki/UGM-133_Trident_II#Warheads
https://www.defensenews.com/global/europe/2020/02/25/britain-confirms-new-nuclear-warhead-project-after-us-officials-spill-the-beans/
https://www.navalnews.com/naval-news/2021/11/first-submarine-to-use-new-stealth-technology/

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Thanks!
