### ISSUE TITLE
China, PLAN, YJ-21, modification in many aspects

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4206]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4058 4059

### Summary of Changes

Since we were talking about the SM-6 Blk IB the other day, it got me thinking about the YJ-21 and wanted to make some changes to the weapon's performance in the database that I thought were more reasonable. As it happens, we just got some news that North Korea has tested a hypersonic missile with a similar warhead configuration (similar to the DF-26, bipyramid both), which may serve as some reasonable evidence.

- [x] Change the YJ-21 warhead back to the HGV category.
- [x] Modified warhead charge to a smaller 250kg penetrator (500 DP). Remember, its diameter is no more than 0.85m, we can refer to the payload of 3M22 Zircon.
- [ ] Speed band modified to more reasonable 4000kt-4500kt-5500kt-6500kt.  (6~10ma)
- [x] Add fix land targets to its valid targets. Consider some special cases, like the YJ-100.
### Sources

Simulation of the flight trajectory of a North Korean hypersonic missile by South Korea's defense agency:
![img-1705808039391b80130cd907f087b1ec511519f672775](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/70734e31-4ad0-4cc9-ac2f-91360adc23f2)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/f30db2b8-2e26-4fca-9a61-e55221d074ae)

https://www.aljazeera.com/news/2024/1/15/north-korea-says-it-tested-solid-fuel-missile-with-hypersonic-warhead
> The missile flew towards the East Sea, travelling approximately 1,000km (621 miles), Seoul’s Joint Chiefs of Staff said in a statement on Sunday, adding that authorities in Seoul, Washington, DC and Tokyo were analysing the specifications. Japan’s Defence Ministry said its maximum altitude was at least 50km (30 miles).

Regarding the maximum flight altitude of this type of short/medium-range missile with similar volume, we may refer to this:
https://missilethreat.csis.org/missile/df-12/
> Reaching a maximum altitude of 50 km, the DF-12 / M20 has a range of 280 km. The missile is also reportedly capable of maneuvering in flight, performing a pull-up maneuver before the terminal phase. Using GPS and inertial guidance, the missile is accurate to a Circular Error Probable (CEP) of 30m, though other reports suggest a 50m CEP.

https://en.wikipedia.org/wiki/YJ-21
> The missile system is reportedly capable of engaging land targets and surface warships with a hypersonic, maneuverable, conventional warhead.

**Comment by Jkryos** [comment]
Updated DB3K 507.
