### ISSUE TITLE
Satellite name issue, carriage return symbol in its name

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4208]
### DB Selector

DB3K

### Affected DBID(s)

Satellite 149, 150, 36

### Description of Problem

**DataSatellite**
_DBViewer_
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/4d27768d-f1ad-408b-8038-252d39c9f774)
```
	COSMOS-SKYMED GEN 2 1
QPS-SAR-1
QPS-SAR-1
```
_DBTable, sqlite format_
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/c8d8db56-7dda-4116-b442-7bc56646519a)

**DataSatelliteOrbits** (doesn't sho ingame, but still)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/0018c85b-a335-4cda-9cee-82319437ec58)

**Comment by claudejdev** [comment]
Cf. https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=400538

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
