### ISSUE TITLE
CA CH-113A Voyageur x12

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#421]
### DB Selector

CWDB

### DBID to Copy

667 CWDB

### Hypothetical

No

### Name

CH-113A Voyageur

### Country

Canada

### Service

Canadian Army

### In Commission

1963-2004

### Loadout Options

- Replace Marine loadouts with Infantry loadouts for 12x and 24x

### Sources

https://en.wikipedia.org/wiki/Boeing_Vertol_CH-46_Sea_Knight#Canada
http://www.rwrwalker.ca/CAF_Vertols_detailed_list.htm
https://www.silverhawkauthor.com/post/canadian-warplanes-7-boeing-vertol-ch-113-labrador-and-ch-113a-voyageur-helicopter

![60fc76fa199f15afffe7a316_Boeing-Vertol-CH-113-Voyageur--Canadian-Army--318---CF-Photo](https://user-images.githubusercontent.com/99632305/156107763-e502fc08-0bf6-4301-aa14-d4cf8d8fc8ef.jpg)

**Comment by Jkryos** [comment]
Added CWDB 494.
