### ISSUE TITLE
United States - WMSL 750 Bertholf [Legend Class, National Security Cutter] (sensor)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4210]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2431, 3885

### Summary of Changes

**Sensors**
- this class should have ID **5226** _AN/SPS-77(V)1 [Sea Giraffe AMB 3D]_, instead of ID 2015 TRS-3D/32.

### Sources

https://www.hensoldt.net/news/hensoldt-provides-us-coast-guard-with-naval-radars/

**Comment by PygmalionOfCyprus** [comment]
It's an AN/SPS-75. Updated 505.
