### ISSUE TITLE
Sweden - Sea Giraffe AMB

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4212]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 2776, 5226

### Summary of Changes

[^WNWS]:Friedman, Norman, [i]The Naval Institute Guide to World Naval Weapon System[/i], Fifth Edition. 2006. p.289-290
[^C4ISR]: Jane's _C4ISR & Mission Systems Maritime_ 2015-2016, p.539-541
[^BCG]: Larry Bond, Chris Carlson, & Peter Grining _Commonwealth Navies - Ships of the United Kingdom, Australia, Canada, and New Zealand 1955 - 2023_, Jan. 2024

 ID | Name
 --- | ---
2776 | Sea Giraffe AMB 3D
5226 | AN/SPS-77(V)1 [Sea Giraffe AMB 3D]

### for each 
ID 2776, 5226

- Scan Interval: 1 or 2 (30 rpm for 60 km+ range) [^C4ISR][^WNWS]
- Frequencies (Hz): 5400000000 to 5900000000 [^C4ISR][^WNWS]
- _Max contacts_: 100 [^WNWS] (>200 air, >400 surface[^C4ISR])
- _Beamwidth, hor.  (deg)_: 2.1 [^C4ISR] [^WNWS]
- _Peak Power (W)_: 25000  [^C4ISR] [^WNWS]
- _Processing Gain/Loss (dB)_: 30 [^WNWS]
- _Pulse Width (μs)_: 0.32 to 20.5 [^WNWS]

- Range, nm [^BCG]:

| Size | air | surface
| -------- | ------- | ------- |
| Large | 95 | 40 |
| Medium  | 67 | 38 |
| Small | 48 | 25 |
| Very Small   | 19 | 13 |
| Stealthy   | 6 | 6 |

> The instrumented range is 97.2 nm (180 km) [^C4ISR] [^WNWS]

**Codes** [^C4ISR] [^WNWS]
- Low Probability of Intercept (LPI)
- Continuous Tracking Capability [Target Tracking Radar]

- Has a Track-on-jame capability
- Can classify helicopters
- Able to detect, track, and classify mortar rockets, and splashes

### Sources

¨
+
https://www.saab.com/products/sea-giraffe-amb
https://www.yumpu.com/en/document/read/47418047/sea-giraffe-amb-presentation-saab

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
