### ISSUE TITLE
Canada - FFH 330 Halifax [City Class ] FELEX refit, 2012 radar upgrade

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4213]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3569

### Summary of Changes

By 2022, the Sea Giraffe AMB radar (ID 2776) replace the previous Sea Giraffe 150 HC (Not a Sea Giraffe "180" HC by the way)

### Sources
[Saab Receives Order for Sea Giraffe AMB from Royal Canadian Navy - Saab](https://www.saab.com/newsroom/press-releases/2021/saab-receives-order-for-sea-giraffe-amb-from-royal-canadian-navy)
Larry Bond, Chris Carlson, & Peter Grining _Commonwealth Navies - Ships of the United Kingdom, Australia, Canada, and New Zealand 1955 - 2023_, Jan. 2024

Cf. #351 and #305

**Comment by PygmalionOfCyprus** [comment]
Agree w/ Captain Canuck, SG 180s are well-documented.

They really like upgrading these things, don't they? FELEX in '12, MLU in '18, new radars purchased '22-26, Pr. Strongbow in '23...

**Comment by claudejdev** [comment]
Still @PygmalionOfCyprus , from 2022, it should be Sea Giraffe AMB. Even if it correctly was a 180 in between the older 150 and that one.

Thank you @cdnice55 for the heads up on that 180.
I'm sure you can find mention of AMB radar too.

https://ottawacitizen.com/news/national/defence-watch/naval-contracts-and-technology-developments-on-display-at-cansec-2019
https://fliphtml5.com/insrc/yopa/Esprit_de_Corps_Volume_29_Issue_1/ page 34
https://sdquebec.ca/fr/nouvelle/saab-receives-order-from-the-us-for-sea-giraffe-mmr

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/a5db2483-42b1-476a-9ce4-2a6f07f8cbd1)

**Comment by PygmalionOfCyprus** [comment]
Yes, sorry, should have been clearer in my comment. I changed it to the AMB on the '23 ship but didn't replace the 180s on older entries.

**Comment by cdnice55** [comment]
Re:"They really like upgrading these things, don't they? FELEX in '12, MLU in '18, new radars purchased '22-26, Pr. Strongbow in '23.."

There are probably going to be more updates coming given the CSC delays and need for frigates into 2040's it seems. Will be interesting to see if they go piece by piece or go in on another HCM/FELEX programme. Maybe fit some of the kit coming for CSC onto them as trials.

**Comment by PygmalionOfCyprus** [comment]
They can appoint [Captain Theseus](https://en.wikipedia.org/wiki/Ship_of_Theseus) as CO.

**Comment by cdnice55** [comment]
@claudejdev Thanks for mentioning those Harpoon resources, I went and grabbed the Commonwealth Navy and Air Force one yesterday!
