### ISSUE TITLE
Changes to J-10C AESA

### ISSUE THREAD

**Issue by Matharox** [PygmalionOfCyprus/cmo-db-requests#4214]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5824

### Summary of Changes

- Increase Max Range to 120 nm or 140 nm
- Add LPI property
- Add SAR property

### Sources

It's hard to find any concrete information on this radar. But this should put it more in line with its contemporaries in the F-16V, Gripen and Rafale.

It should at least be fair to assume it's more capable than the export AESAs offered for the smaller JF-17 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/92672971/35061f8e-31c3-46c8-8fb4-0d93bb3c9c5c)

**Comment by LuigiP57** [comment]
It may also be necessary to increase the illumination number to 4 (according to the picture).

And NCTR-JEM and Continuous Tracking Capability should be added (same as other PLAAF airborne AESA fire control radars)

**Comment by PygmalionOfCyprus** [comment]
Shoot, missed this for the PLAAF review. Handled 507.
