### ISSUE TITLE
Morocco - CH-47 C, D

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4215]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3073 CH-47C, 512 CH-47D

### Hypothetical

No

### Name

CH-47C Chinook, CH-47D Chinook

### Country

Morocco

### Service

Air Force

### In Commission

C= 1979, D= 2015

### Number in Service

C = 9x, D = 3x

### Sources

SIPRI Trade Registers
https://www.facebook.com/moroccanFAR/photos/boeingdefense-ch-47d-chinook-cn-aljalkall-r%C3%A9cement-re%C3%A7uscolumbia-helicoptersmaro/893029520750301/
https://www.chinook-helicopter.com/history/aircraft/morocco/morocco.html
https://www.dsca.mil/press-media/major-arms-sales/morocco-ch-47d-chinook-helicopters

![Rmaf ch-47c](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/cbbd284e-83a7-4180-a6f0-37be75a14962)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/7f06dce2-ca16-48d8-9595-b7cb24e7fe9b)

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
