### ISSUE TITLE
Aircraft #4464 MH-60X has no loadout and cannot be launched

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4216]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #4464 MH-60X Silent Hawk

### Description of Problem

There is no loadout (Seals or whatever) and therefore the helicopter cannot be launched.

### Recommended Fix

Loadout Seals 8x (Troop Transport) & a loadout a Delta Team 8x (Troop Transport

**Comment by PygmalionOfCyprus** [comment]
Is this a scenario issue? The DB has a ferry and troops loadout for the MH-60X.

**Comment by Huib18** [comment]
Yes, it does.

It was related to the amount of helicopters on the ship.
I could add the two MH-60X to the ship but not add any loadout.
When I removed one MV-22 it was WAD.

Sorry for the inconvenience.

Huib18



Op di 30 jan 2024 om 18:30 schreef PygmalionOfCyprus <
***@***.***>:

**Comment by 5th-Domain** [comment]
> Yes, it does. It was related to the amount of helicopters on the ship. I could add the two MH-60X to the ship but not add any loadout. When I removed one MV-22 it was WAD. Sorry for the inconvenience. Huib18 Op di 30 jan 2024 om 18:30 schreef 

They cant load on the landing pads only in hangars currently. If you want to make that work have the MV-22 take off, the two 
MH-60X will then move in to the hangar where they can be loaded. Then land the MV-22. That should work if i remember correctly.
