### ISSUE TITLE
UXV Combatant

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#4218]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

UXV Combatant - Concept Drone Carrier

### Class

CV

### Country

United States

### Service

US Navy

### In Commission

2025+ (Realistically)

### Number in Service

Hypothetical

### Length (m)

152.4

### Beam (m)

21

### Draft (m)

5.5

### Standard Displacement (t)

8,000

### Complement

60 (this seems optimistic) 

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

Likely similar to #3329

### Fuel Capacity (kg)

Unknown

### Flank Speed (kt)

27

### Range (nm) at Speed (kt)

Unknown

### Sensors

Likely similar to #3329 and #3343.

### Mounts

X1 155MM Gun - sources suggest that it would be based on the ERCA rather than the Zumwalt's AGS to keep costs down.
24-32 cell VLS.
Likely the usual decoys, CWIS/RAM and light weapons that ships like the LHAs and FFG-62s carry.

### Aircraft & Docking Facilities

The X2 V-runways can launch and land unmanned drones, rotorcraft, and aircraft. These would likely be limited to Medium aircraft and smaller.
A floodable well deck can launch USVs, UUVs, small boats, and RHIBs.

### Comms/Datalinks

Likely similar to #3329 and #3343.

### Ship Codes

Nuclear Shock Resistant, Degaussed Steel Hull, Prairie Masker

### Comments

The Drone Carrier Warship could remedy these doubts and act as the hybrid warship that the future U.S. Navy needs and desires—a vessel that can multitask in various warfare functions:

Act as a command node, sheepdog, and provide “Armed Overwatch” for the LPD-17s and [Light Amphibious Warships (LAWs),
Provide fire support via gunfire, missiles, potential Hypersonics, and long-range fires from VLS cells and a 155mm cannon independent of frigates, destroyers, and cruisers.
Provide consistently available and present runways and landing pad for unmanned aircraft, rotorcraft, drones, and a floodable well deck for sea and subsurface vessels independent of carriers, warships, Sea bases, and amphibious ships.
Provide expanded space for command, medical, dental, gym, facilities, food, Administration, maintenance, services, and logistics for the LAWs and small boats.
Provide crisis response in-theater closer to hot-spots around the globe.
Act as a Mothership vessel for future drones such as the [MARTAC MANTAS T38]
And be small and cheap enough to be built in large quantities.

### Sources

https://www.navalnews.com/naval-news/2021/04/op-ed-is-it-time-for-the-u-s-navy-to-build-the-drone-carrier-warship/

https://en.wikipedia.org/wiki/UXV_Combatant

**Comment by KushanGaming** [comment]
Done for DB505.
