### ISSUE TITLE
Su-27M

### ISSUE THREAD

**Issue by Tindalos07** [PygmalionOfCyprus/cmo-db-requests#4219]
### DB Selector

DB3K

### Baseline

2370

### Hypothetical

No

### Name

Su-27M

### Country

Soviet Union/Russia

### Service

VVS/PVO

### In Commission

1996+

### Number in Service

3

### Length (m)

22.18

### Wingspan (m)

14.698

### Height (m)

6.34

### Empty Weight (kg)

16300

### Maximum Takeoff Weight (MTOW) (kg)

34000

### Payload Weight (kg)

8000

### Crew

1

### Propulsion

2x AL-37FU

### Rate of Climb (ft/min)

24060

### Service Ceiling (ft)

45000

### Military/Afterburner Speed (kt)

920

### Cruise Speed (kt)

480

### Supercruise

No

### Ferry Range (nm)

2095

### Takeoff / Landing Distance (m)

901/1400

### Fuel Capacity (kg)

10250 

### Sensors

1xN011M Bars (same as Su-30MKI and Su-30SM)
1xOLS-27/32 IRST
1xSPS-171/172 Sorbtsiya [L-005]
1xSPO-29 Pastel

### Mounts

1x GSh-30-1 cannon
APP-50 flare dispenser

### Loadout Options

R-77 (the baseline R-77, not R-77-1)
R-37 (again, baseline R-37, not R-37M)
Kh-29T
Kh-59M Ovod
All variants of R-27
R-73
All Soviet-Russian iron bomb
S-8 and S-13 rocket pod
KAB-500KR
Kh-31P
Kh-31A
copypaste loadout option of Su-27SKM or Su-30MKK already in the DB would do the job

### Comms/Datalinks

UHF
VHF
HF
AA-10/12 command data link

### Aircraft Codes

Supermanouverability, Fly-by-Wire, Helmet Mounted Sight / Display (HMS/HMD), Probe Refuelling

### Comments

It is somewhat similar to a Su-30MKI but with better engines and only one pilot, a modernized Su-27S that was planned to enter service in the '90s, 12 prototypes were made, 3 serial entered service, later transferred to Russkiye Vityaz

### Sources

Flankers: The New Generation by Yefim Gordon pg 16, 20, 22
Sukhoi Su-27 by Yefim Gordon pg 149 (carrying R-77), 150 (carrying Kh-31 and KAB-500KR), 164 (Kh-29T and Kh-59/59M), 452 (dimension)

**Comment by Tindalos07** [comment]
a small correction: 3 serial airframes entered the Russian service in 1996, so this is not a hypo platform but a real one
source: http://sukhoi.mariwoj.pl/su-30-ru-27m.htm

**Comment by FrangibleCover** [comment]
Did you close this in error while trying to reply to it?

**Comment by tbrandon517** [comment]
> Did you close this in error while trying to reply to it?

Looks to be replaced by #4238
