### ISSUE TITLE
RCAF CH-21C Shawnee

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#422]
### DB Selector

CWDB

### Affected DBID(s)

2095 CWDB

### Summary of Changes

- Service period was 1954-1968
- Canadian designation is CH-125 for H-21's

### Sources

Canadian Combat and Support Aircraft, TFJ Leversedge, 2007

https://en.wikipedia.org/wiki/List_of_aircraft_of_Canada%27s_air_forces
https://va3kgb.com/CdnMilAC/search_result_acname.php
https://en.wikipedia.org/wiki/Piasecki_H-21#Canada

**Comment by Jkryos** [comment]
Updated CWDB 494.
