### ISSUE TITLE
Taiwan, Keelung class DDG, combat system should be Gen 5 NTU

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4224]
### DB Selector

DB3K

### Affected DBID(s)

ship 1786 2155

### Summary of Changes

As title.

### Sources

https://man.fas.org/dod-101/sys/ship/ddg-993.htm
https://en.wikipedia.org/wiki/New_Threat_Upgrade

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
