### ISSUE TITLE
Taiwan, Wan Chien missile, update in many aspects

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4226]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3026

### Summary of Changes

1. Considering its shape (mainly the huge exposed turbofan intake, which doesn't show any stealth modifications at all), I think it probably shouldn't have -34~-44dbsm stealth performance. I think it should be somewhere between the level of harpoon and JSOW.
2. Add variants of high-explosive, semi-armor-piercing and submunition.

### Sources

https://airrecognition.com/index.php/news/defense-aviation-news/2023-news-aviation-aerospace/september/9205-taiwan-s-air-force-allocates-additional-budget-for-more-advanced-wan-chien-air-to-ground-missiles.html
https://missilethreat.csis.org/missile/wan-chien/

> The missile is guided by INS/GPS and may have a terminal seeker. The payload is approximately 350 kg with either a high explosive, semi-armor piercing, or submunitions warhead.[7](https://missilethreat.csis.org/missile/wan-chien/#easy-footnote-bottom-7-2515) The submunitions warhead can reportedly be equipped with as many as 100 bomblets.[8](https://missilethreat.csis.org/missile/wan-chien/#easy-footnote-bottom-8-2515)

https://en.wikipedia.org/wiki/Wan_Chien
As you can see from this image, it does not have the typical trapezoidal shape of a stealth munition, and the warhead is also a smooth transition (similar to the common cruise missile and ammunition dispenser). The exposed rivets almost suggest that it is unlikely to have RAM cover (I even suspect that these rivets might increase radar reflection).
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/ee3899a6-4396-48ad-b10f-a5325296772b)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/89293987-cfd9-4b8a-b2b3-37fce435050e)

**Comment by LuigiP57** [comment]
The Chinese ordnance industry seems to have a similar product (with turbofan/turbojet power, different from the unpowered glide Tianlei 500). Maybe you could take that into consideration?
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/2fb644da-f0e3-4988-935a-4765c63442c5)

**Comment by LuigiP57** [comment]
#1842

**Comment by PygmalionOfCyprus** [comment]
Handled 505.
