### ISSUE TITLE
RCAF CE-144 Challenger x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#423]
### DB Selector

DB3K

### DBID to Copy

4460 DB3k

### Hypothetical

No

### Name

CE-144 Challenger

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1983-

### Sensors

- Add 1x Generic Navigation Radar
- Add 1x Generic Comms Monitor [Advanced] #5833
- Add 1x Generic ESM [Advanced] #5834
- Add 1x Generic Comms Jammer [Advanced] #5832
- Add 1x Generic OECM [Average] #1048

### Loadout Options

- Remove Passenger loadouts
- Add Offensive ECM training mission
- Add Offensive ECM mission

### Other Changes

- Add secure VHF/UHF radio

### Sources

http://www.va3kgb.com/milac/cc144_challenger.htm
http://www.shearwateraviationmuseum.ns.ca/aircraft/challenger.htm
https://www.silverhawkauthor.com/post/canadian-warplanes-6-jets-bombardier-cc-144-challenger
http://www.rwrwalker.ca/CF_Challenger_detailed.html
https://va3kgb.com/CdnMilAC/search_result_acname.php

**Comment by Jkryos** [comment]
Added DB3K 494.
