### ISSUE TITLE
Canada P-51D Mustang Mk.4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#4233]
### DB Selector

CWDB

### DBID to Copy

32

### Hypothetical

No

### Name

P-51D Mustang

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1947-56

### Number in Service

130x

### Sensors

Same

### Mounts

Same

### Loadout Options

Same

### Other Changes

- 1x 1,590 horsepower Packard (license-built) V-1650-7 Merlin piston engine

### Sources

https://www.silverhawkauthor.com/post/canadian-warplanes-3-north-american-p-51-mustang-mk-i-ii-and-iv
https://www.canada.ca/en/air-force/services/aircraft/p-51.html

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
