### ISSUE TITLE
Taiwan, Light Frigate

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4237]
### DB Selector

DB3K

### Baseline

ship 4149

### Hypothetical

No

### Name

Light Frigate AAW/ASW

### In Commission

2026

### Number in Service

1x AAW Prototype; 1x ASW Prototype

### Length (m)

115

### Beam (m)

15

### Draft (m)

4

### Standard Displacement (t)

2500

### Full Displacement (t)

3000

### Complement

85

### Primary Propulsion Type

Diesel

### Propulsion

1x GE LM2500+G4

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

2200nm

### Sensors

1x ARTISAN 3D rotating phased array radar
1x Surface search radar
1x Navigation radar
1x TRAPS towed active/passive variable depth sonar (anti-submarine type)
FCR and other sensors are same as Kang Ding or Ta Chiang

### Mounts

For AAW
- Hua Yang VLS (8x cells, each cell with 4x TC-2N)
- 16x HF-3 SSM or 8x HF-3-ER SSM
- 1x Phalanx CIWS
- 2x Mk 44 Bushmaster II 30mm chain gun or 2x XTR-102A2 weapon system

For ASW
- 2x TC-2N canister (8x cells; same as Ta Chiang)
- 16x HF-2 or 16x HF-3 or 8x HF-3-ER
- 2x3 Mk 32 surface ship torpedo tubes (equipped with 6x Mk 46 MOD5 or Mk 54 torpedoes)
- 2x Mk 44 Bushmaster II 30mm chain gun or 2x XTR-102A2 weapon system

### Sources

https://zh.wikipedia.org/zh-tw/%E8%BC%95%E5%9E%8B%E5%B7%A1%E9%98%B2%E8%89%A6
https://www.navalnews.com/naval-news/2024/01/taiwan-starts-construction-of-new-light-asw-frigate/
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/5f9b9a75-d055-4901-9c16-06f64239b963)

**Comment by PygmalionOfCyprus** [comment]
We're tracking internally over on the dev tracker as part of our weekly news roundups; closing this ticket to avoid duplicates but it will be handled 505.
