### ISSUE TITLE
Israel, F-16I, undescriptive GBU-39 loadout name. Quickfix.

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4239]
### DB Selector

DB3K

### Affected DBID(s)

Loadout 2650

### Summary of Changes

Loadout 26050
- name: GBU-39/B SDB, Litening III Pod [FLIR], EL/L-8222 ASSP DECM Pod

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/0412145c-280a-4e2c-aff2-110685f5b4e1)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/8f30fe30-9990-489d-b976-52ad286399b4)

Loadouts 22776 and 26050 are named the same, however, the latter differs in how it has a DECM pod.

Given a similar loadout is different in the interface by having that DECM pod in its name, I do suggest naming 26050 in such a way.

### Sources

DB3K

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
