### ISSUE TITLE
Add:Kie Ntem (OPV-62) class ships, Equatorial-Guinea Navy 

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#424]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Ship (PBO), Q1, Kie Ntem

### Class

Kie Ntem (OPV-62)

### Country

Equatorial-Guinea

### Service

Navy

### In Commission

2011 - present

### Length (m)

61.7

### Beam (m)

7.6

### Draft (m)

2.8

### Standard Displacement (t)

Not found

### Full Displacement (t)

470

### Complement

35 + 24

### Primary Propulsion Type

Diesel

### Propulsion

4x MTU, 4 shafts

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

3200 @ 12 (src1), 3200 @ 15 (src2)

### Sensors

2x generic Navigation Radar
Toplite E/O system
(src2)

### Mounts

1x twin 23mm/82 typhoon
2x single 12.7mm/79
(src2)

### Aircraft & Docking Facilities

Platform for 1 small helicopter
Small crane for two RIB's

### Comments

Appears to on Saar4 design (#465)

### Sources

src3 is generic Saar 62
1: JFS 2015-2016
2: https://www.navypedia.org/ships/equatorial_guinea/eqgui_cf_kie_ntem.htm
3: https://en.wikipedia.org/wiki/Sa%27ar_62-class_offshore_patrol_vesse
![1Posted](https://user-images.githubusercontent.com/99532490/156206467-10586d97-6f29-44b7-9420-0e054cab5621.jpg)
![2Posted](https://user-images.githubusercontent.com/99532490/156206475-c4315a3e-d623-4db0-baac-baf5ebab8b3a.jpg)
![3Posted](https://user-images.githubusercontent.com/99532490/156206476-12bc076f-db5e-4a25-a486-81341161b91b.jpg)
![4Posted](https://user-images.githubusercontent.com/99532490/156206477-80f49b07-bbb0-4bd9-8970-a2cb9d228adb.jpg)
l

**Comment by Jkryos** [comment]
Added DB3K 494.
