### ISSUE TITLE
FFG 36 Underwood [Perry Class] – 1988; Replace SQR-18A with SQR-19

### ISSUE THREAD

**Issue by Red-88** [PygmalionOfCyprus/cmo-db-requests#4242]
### DB Selector

DB3K

### Affected DBID(s)

Ship DB# 715

### Summary of Changes

Remove: Sensor SQR-18A (DB# 1401) Add: SQR-19(V)2 (DB# 4578)

First ship build with SQR-19 comissioned in 1985 (USS Elrod FFG-55).

### Sources

Friedman, Norman. _The Naval Institute Guide to World Naval Weapon Systems, Fifth Edition_. Annapolis: Naval Institute Press, 2006. p.670.

Friedman, Norman. _The Naval Institute Guide to World Naval Weapon Systems_. Annapolis: Naval Institute Press, 1989. p.378-379.

Polmar, Norman. _The Ships and Aircraft of the U.S. Fleet, Fourteenth Edition_. Annapolis: Naval Institute Press, 1987. p.162-166.

**Comment by PygmalionOfCyprus** [comment]
Were these retrofitted on the earlier ships-in-class or only from Elrod onwards? If the latter I'd want to make a new entry rather than just modifying the Underwood.

**Comment by Red-88** [comment]
> Were these retrofitted on the earlier ships-in-class or only from Elrod onwards? If the latter I'd want to make a new entry rather than just modifying the Underwood.

It seems older ships were retrofitted.
Jane's Fighting Ships 1988-1989 mentions that SQR-19 is fitted on OHP Class FFGs and only the ones in the NRF are still fitted with SQR-18. 
Jane's Fighting Ships 1990-1991 lists FFGs with SSQ-89(V)2 (SQS-53B & SQR-19) as FFG 8, 36-61.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
