### ISSUE TITLE
Permit Class SSN missing towed array

### ISSUE THREAD

**Issue by Red-88** [PygmalionOfCyprus/cmo-db-requests#4244]
### DB Selector

DB3K

### Affected DBID(s)

Submarine DB# 19, 18, 17, 376

### Summary of Changes

Add Towed Array TB-16 (Sensor DBID# 1373).

### Sources

https://man.fas.org/dod-101/sys/ship/ssn-594.htm
Polmar, Norman. _The Ships and Aircraft of the U.S. Fleet, Fourteenth Edition_. Annapolis: Naval Institute Press, 1987

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
