### ISSUE TITLE
Lynx SH-14C (Mk81) replace dipping sonar with MAD

### ISSUE THREAD

**Issue by Red-88** [PygmalionOfCyprus/cmo-db-requests#4245]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft DB# 422

### Summary of Changes

Remove dipping sonar (DB# 2930) as SH-14C was not fitted with it.
Add AN/ASQ-81(V)2 (DB# 1076)

### Sources

Lake, Jon, Ed. _World Air Power Journal, Volume 40_. London: Aerospace Publishing Ltd, 2000. p.116.

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
