### ISSUE TITLE
USV (UNMANNED surface vehicles) have the Mk1 Eyeball

### ISSUE THREAD

**Issue by JByfield76** [PygmalionOfCyprus/cmo-db-requests#4248]
### DB Selector

DB3K

### Affected DBID(s)

All/most USVs e.g. #3219 Expeditionary Warfare USV

### Description of Problem

I've notices that many USVs (unmanned surface vessels) have the Mk1 Eyeball. 
I assume that the Mk1 Eyeball represents crew looking with their own eyes. By definition a USV does not have crew! 
I suspect that the Mk1 Eyeball is added as a sensor by default to all ships and aircraft. 
Some USVs can have troops on board though - this could mean some could retain the Mk1 Eyeball. 
This does not affect UAVs, UUVs or ROVs (as far as I can tell - I've only checked a handful)
I'm not sure how much impact this is going to have on a game, but for the #3219 Expeditionary Warfare USV, the Mk1 Eyeball under certain circumstances is its longest ranged sensor. 

### Recommended Fix

Make a decision on whether troops on board a USV means it gains the Mk1 Eyeball. 
Go through all the USVs and remove the Mk1 Eyeball from all USVs or just from those without troop capacity.

**Comment by PygmalionOfCyprus** [comment]
>I suspect that the Mk1 Eyeball is added as a sensor by default to all ships and aircraft.

You are correct. Unfortunately, this means I can't do anything about it DB-side, unless the cause is that the "ship" has the wrong type classification (i.e., not USV, etc.). Please post it as a bug on the forums so that the sim devs can fix it.
