### ISSUE TITLE
RCAF Canadair North Star Mk1 (C-54GM) x24

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#425]
### DB Selector

CWDB

### Baseline

#714 CWDB

### Hypothetical

No

### Name

Canadair North Star Mk1 (C-54GM)

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1947-65

### Length (m)

28.89

### Wingspan (m)

35.81

### Height (m)

8.38

### Empty Weight (kg)

19,731

### Maximum Takeoff Weight (MTOW) (kg)

33,112

### Payload Weight (kg)

5,216

### Crew

7

### Propulsion

4x Rolls-Royce Merlin 622

### Rate of Climb (ft/min)

972

### Service Ceiling (ft)

36000

### Military/Afterburner Speed (kt)

306

### Cruise Speed (kt)

282

### Supercruise

No

### Ferry Range (nm)

2606.9

### Takeoff / Landing Distance (m)

451-900m TOD/LAD

### Fuel Capacity (kg)

2000

### Sensors

1x Mk1 Eyeball

### Mounts

N/A

### Loadout Options

- Passenger x44
- Cargo x 5,216kg
- VIP

### Comms/Datalinks

- UHF Radio [Secure]
- VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

The Canadair North Star was a unique Canadian development of the Douglas C-54/DC‑4 aircraft. Instead of radial piston engines found on the Douglas design, Canadair selected Rolls-Royce Merlin engines to achieve a cruising speed 35 mph faster. The RCAF North Stars were unpressurized and were used on a wide variety of general transport duties.

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007.
http://www.rcaf-arc.forces.gc.ca/en/aircraft-historical/north-star.page
https://ingeniumcanada.org/aviation/artifact/canadair-c-54gm-north-star-1-st
https://en.wikipedia.org/wiki/Canadair_North_Star#Variants
https://www.silverhawkauthor.com/post/canadian-warplanes-5-canadair-cl-2-north-star-and-c-5-north-star-transports
https://va3kgb.com/CdnMilAC/search_result_acname.php

![northstar](https://user-images.githubusercontent.com/99632305/156208519-2b3cbf09-df1c-4e62-9b51-d8ea61f42f08.jpg)

**Comment by Jkryos** [comment]
Added CWDB 494.
