### ISSUE TITLE
Type 095 Sui SSGN updates

### ISSUE THREAD

**Issue by BronskyMcCloud** [PygmalionOfCyprus/cmo-db-requests#4256]
### DB Selector

DB3K

### Affected DBID(s)

Submarine 676

### Summary of Changes

Working on a late-2020s WestPac scenario, therefore I would like to second request #3704 regarding the Type 095 Sui-class. I understand factual data is pretty much non-existent at this point but there are trends that suggest the platform could receive some refurbishment. For the sake of simplicity, I will copy-paste most of LuigiP57's report with the exception of step 6 of his request.

- [ ] 1. Change platform signatures to the same level of the first Russian Yasen-class Boat (DBID submarine_405).
> 
> - [ ]  2. Change the mount VLS number to 18.
> 
>- [ ]  3. Add YJ-18 and YJ-21 to the VLS magazine. Keep CJ-10A SLCM in the magazine too.
> 
> - [x]  4. Remove the Yu-6 from the current magazine and torpedo mount. Increase the number of Yu-10 in the magazine to 28.
> 
> - [x]  5. Add [Nonmagnetic Hull] [shrouded Propulsor] [Advanced Propulsor] [shock Resistant] to properties.

- [x]  6. Change the standard displacement to 8500t, the full displacement to 10700t. (The linked source states that the Type 095 is more probably a double-hull design, thus altering the estimated displacement given by the original requester.)

- [x] 7. Change beam from 12m to 13m.

### Sources

[China Maritime Repor China Maritime Report No. 30: A Brief T t No. 30: A Brief Technical Hist echnical History of PL y of PLAN
Nuclear Submarines](https://digital-commons.usnwc.edu/cgi/viewcontent.cgi?article=1029&context=cmsi-maritime-reports) (p.28)

![261572066-f4c19518-a80c-4546-a1ac-b04143d8fff8](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/a4268619-2b82-4146-8950-19373f938c5e)

**Comment by LuigiP57** [comment]
Why not just comment directly under the original ticket? Wouldn't that be easier?

**Comment by LuigiP57** [comment]
> 1. Change the signatures to the same level with SSN 774 virginia flight I (the signatures of [DBID submarine 40] for reference, I think you can just copy it). Early 2000s US tech, Adm. Samuel Paparo said "by generation, think 10 or 20 years" between the gap of China and US sub technology.

For this, I think my original estimate was too optimistic. Although it was so highly rated by General Paparo, I now think it is not quite comparable to Virginia. Its acoustic performance should be between Virginia and Yasen.

**Comment by LuigiP57** [comment]
And I think the detectability estimates in the document cited are too pessimistic. They appear to have misestimated the age of its manufacture and failed to take into account the use of the shaftless pump propeller.
https://www.globalsecurity.org/military/world/china/type-95-rdt.htm

**Comment by BronskyMcCloud** [comment]
No particular reason why I didn't comment below your post. Didn't think that far ahead I guess. Otherwise I hope that issue get's slightly more prioritized, now that someone else opened another ticket concerning the same issue.

As to your other comments, I agree with what you're saying. Reason why I hdidn't add my own suggestions in that regard was because certainly at some point in the future there will have to be another update to this DB entry as more info becomes available. I have now made some slight adjustment to my request and incoorperated some of the things you added. 

I believe accoustic levels are comparable to the first Project 885 Yasen boat as the author of the document you linked assesses that the most recent Type 093B-class is comparable in noise level to the Soviet Sierra I-class.

**Comment by Jkryos** [comment]
Added DB3K 505
