### ISSUE TITLE
Update: F-15EX EPAWSS replacing other legacy systems

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4259]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4771, 6887

### Summary of Changes

Remove all ESM/ECM unless related to EPAWSS.

### Sources

https://www.dote.osd.mil/News/News-Display/Article/3664092/fy-2023-dote-annual-report-submitted-to-congress/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
