### ISSUE TITLE
RCAF Canadair North Star C-5 (VIP)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#426]
### DB Selector

CWDB

### DBID to Copy

3115 CWDB

### Hypothetical

No

### Name

Canadair North Star C-5

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1950-67

### Sensors

1x Mk1 Eyeball

### Mounts

- None

### Loadout Options

- Delete Air Force 1 loadout
- ADD VIP x27 passengers

### Other Changes

- Engines were Pratt & Whitney Double Wasp R-2800-CA15
- 263kn cruise 278kn Top
- Service ceiling 26,200ft
- Empty weight 22,441kg
- Gross weight 39,008

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://www.silverhawkauthor.com/post/canadian-warplanes-5-canadair-cl-2-north-star-and-c-5-north-star-transports
https://www.aerialvisuals.ca/AirframeDossier.php?Serial=51489
https://en.wikipedia.org/wiki/Canadair_North_Star#Variants

![1420952-large](https://user-images.githubusercontent.com/99632305/156212541-e74bdddd-5596-4d84-ba18-cce70623e68e.jpg)

**Comment by Jkryos** [comment]
Added CWDB 494.
