### ISSUE TITLE
Addition: AGM-158C-3 LRASM-ER, also correction on range of the original

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4262]
### DB Selector

DB3K

### DBID to Copy

Weapon 2378

### Hypothetical

No

### Name

AGM-158C-3 LRASM-ER

### Country

US

### Service

USN/USAF

### In Commission

2026-

### Sensors

Keep original. 

### Loadout Options

N/A

### Other Changes

Change the range of weapon 2378 to 220nm. 
Increase range to 500nm. Remove land attack capability. 

### Sources

https://www.twz.com/air/land-attack-capability-axed-on-agm-158c-lrasm-anti-ship-missile

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
