### ISSUE TITLE
various issues with FTI frigates

### ISSUE THREAD

**Issue by gosnold** [PygmalionOfCyprus/cmo-db-requests#4266]
### DB Selector

DB3K

### Affected DBID(s)

ships 3172 and 3173

### Description of Problem

Ship should not have an Herakles radar
Nor the Najir optical gun director, it should have STIR radar gun director instead (https://www.thalesgroup.com/en/netherlands/news/new-fire-control-radar-7-french-navy-frigates)
3172 should have 2x A-50 (16 cells total, compatible aster 15 and 30) and no MICA-VL cells and 3173 4x A-50 and no Mica VL
3173 has a SeaRAM on top of hangar (https://www.meretmarine.com/fr/defense/reportage-video-sur-le-chantier-des-fregates-de-defense-et-d-intervention-fdi)
IOC for 3172 (French one) is at least 2024, it's not commissioned yet
3172 is called Amiral Ronarc'h (https://www.meretmarine.com/fr/defense/fdi-la-fregate-amiral-ronarc-h-ne-prendra-pas-la-mer-avant-2024) 
3173 is called Kimon

### Recommended Fix

Change sensors, mounts, names and IOC

**Comment by tbrandon517** [comment]
What DB version are you looking at?

CMANO DB has v502 info but names are updated already (I submitted the Kimon name update here #2251 handed for db version 497)

Greeks do not have Herakles, Najir, or Mica and have SeaRam and Stir.
https://cmano-db.com/ship/3173/
https://cmano-db.com/ship/3636/

French match minus SeaRam and have 2924 date.
https://cmano-db.com/ship/3172/
https://cmano-db.com/ship/3487/
https://cmano-db.com/ship/3488/

**Comment by gosnold** [comment]
> What DB version are you looking at?
> 
> CMANO DB has v502 info but names are updated already (I submitted the Kimon name update here #2251 handed for db version 497)
> 
> Greeks do not have Herakles, Najir, or Mica and have SeaRam and Stir. https://cmano-db.com/ship/3173/ https://cmano-db.com/ship/3636/
> 
> French match minus SeaRam and have 2924 date. https://cmano-db.com/ship/3172/ https://cmano-db.com/ship/3487/ https://cmano-db.com/ship/3488/

Yeah sorry I had brain fart, I was using an old scenario to get the ship ID for the Charles de Gaulle and it had an old DB...

**Comment by tbrandon517** [comment]
> > What DB version are you looking at?
> > CMANO DB has v502 info but names are updated already (I submitted the Kimon name update here #2251 handed for db version 497)
> > Greeks do not have Herakles, Najir, or Mica and have SeaRam and Stir. https://cmano-db.com/ship/3173/ https://cmano-db.com/ship/3636/
> > French match minus SeaRam and have 2924 date. https://cmano-db.com/ship/3172/ https://cmano-db.com/ship/3487/ https://cmano-db.com/ship/3488/
> 
> Yeah sorry I had brain fart, I was using an old scenario to get the ship ID for the Charles de Gaulle and it had an old DB...

It happens. I did this one #3162
