### ISSUE TITLE
Orca Payload Bay correction/Orca XLUUV service date

### ISSUE THREAD

**Issue by BronskyMcCloud** [PygmalionOfCyprus/cmo-db-requests#4267]
### DB Selector

DB3K

### Affected DBID(s)

Mount 3096, Submarine 655

### Summary of Changes

Mount 3096:

The Orca Payload Bay that is part of the Orca XLUUV (submarine_655) has it's capacity set to 1, which means the platform can hold only one weapon.

1. Please increase the mount capacity to 12.

2. Add the UGM-109E Tomahawk Blk IV TACTOM TT (DBID weapon_810) as a default weapon record to the mount.

I'm aware that all Tomahawk Blk IVs are slated to be upgraded to Block V standard, however this process will likely take years, therefore I believe it's fairly reasonable to have the Blk IV as a viable option. 

Submarine 655:

1. The first vehicle was deliverd at the end of 2023 so alter the service creation date to possibly 2024

### Sources

https://boeing.mediaroom.com/news-releases-statements?item=131380

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
