### ISSUE TITLE
AGM-183 ARRW cancellation

### ISSUE THREAD

**Issue by JByfield76** [PygmalionOfCyprus/cmo-db-requests#4268]
### DB Selector

DB3K

### Affected DBID(s)

v504

### Summary of Changes

I'm sorry about this one, it's a nit-pick and pretty minor. 
AGM-183 ARRW was cancelled March last year after multiple failed tests. 
All entries for the missile and any aircraft that carry it need to be put to Hypothetical. 
Weapon entries: #3821, #3822, #3823, #3824
Aircraft entries: #4909. #6426, #6158, #4118, #6757, #5456

### Sources

https://www.defensenews.com/air/2023/03/30/us-air-force-drops-lockheed-hypersonic-missile-after-failed-tests/

**Comment by tbrandon517** [comment]
Rather than mark the entire aircraft as Hypothetical and creating a duplicate entry as a new aircraft w/o ARRW I would say just notate the loadouts themselves as Hypothetical and notate the weapon itself as cancelled and Hypothetical.

**Comment by caelunshun** [comment]
[This November 2023 article](https://www.lockheedmartin.com/en-us/news/features/2023/hypersonics-rocket-science-meets-critical-capability.html) seems to suggest the cancellation of ARRW may have been reversed.

Additionally, successful tests of the weapon took place in [August 2023](https://www.c4isrnet.com/battlefield-tech/space/2023/08/21/us-air-force-fires-arrw-hypersonic-in-first-test-since-march-failure/) and [October 2023](https://www.airandspaceforces.com/air-force-arrw-test-new-insights-few-specifics/).

**Comment by tbrandon517** [comment]
> [This November 2023 article](https://www.lockheedmartin.com/en-us/news/features/2023/hypersonics-rocket-science-meets-critical-capability.html) seems to suggest the cancellation of ARRW may have been reversed.
> 
> Additionally, successful tests of the weapon took place in [August 2023](https://www.c4isrnet.com/battlefield-tech/space/2023/08/21/us-air-force-fires-arrw-hypersonic-in-first-test-since-march-failure/) and [October 2023](https://www.airandspaceforces.com/air-force-arrw-test-new-insights-few-specifics/).

Some additional sources referenced on Wikipedia agree. Testing continued as part of the overall hypersonic program and LM is geared towards being ready for low rate production.

https://en.wikipedia.org/wiki/AGM-183_ARRW

**Comment by HunterDNiu** [comment]
> The Air Force currently is producing a limited number of ARRWs. The Air Force will use the AUR flight test results to inform their production decision upon conclusion of the current test series. 

https://s3.documentcloud.org/documents/24400278/2023annual-report.pdf

**Comment by JByfield76** [comment]
It looks like the fate of the ARRW is in the balance.... 
Janes seems to be pretty pessimistic about the program: 
https://www.janes.com/defence-news/news-detail/us-air-force-launches-second-to-last-agm-183a-arrw-all-up-round

Granted the DoD is still willing to carry out tests. Does this mean more of the missiles are going to be manufactured? I understood maybe only one missile was left....

**Comment by tbrandon517** [comment]
> It looks like the fate of the ARRW is in the balance.... Janes seems to be pretty pessimistic about the program: https://www.janes.com/defence-news/news-detail/us-air-force-launches-second-to-last-agm-183a-arrw-all-up-round
> 
> Granted the DoD is still willing to carry out tests. Does this mean more of the missiles are going to be manufactured? I understood maybe only one missile was left....

Seems from LMs page and the DOD report. LM has built additional units to meet testing requirements with the ability to produce as needed for hypersonic testing and move into low rate production if a production order is placed.

**Comment by tbrandon517** [comment]
https://nationalinterest.org/blog/buzz/arrw-hypersonic-missile-may-not-be-rip-afterall-209220

**Comment by PygmalionOfCyprus** [comment]
It appears rumors of its death were greatly exaggerated. 😎
