### ISSUE TITLE
Loadout, Role Mismatch, SAR-CSAR, (Quickfix)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4271]
### DB Selector

DB3K

### Affected DBID(s)

Loadout 26318, 31925

### Summary of Changes

31925 Combat Search And Rescue (CSAR)
26318 Combat Search And Rescue (CSAR)
- Role:  Combat Search And Rescue (CSAR)

33222	Search And Rescue (SAR)
- Role:  Search And Rescue (SAR)

_Note:_
you have a few loadouts named "Search **a**nd Rescue (SAR)", while most are named "Search **A**nd Rescue (SAR)".
They could all be normalized to "Search _A_nd Rescue (SAR)".
`25707, 25713, 28419, 28432, 28570, 28727`

25707	Search and Rescue (SAR)
25713	Search and Rescue (SAR)
28419	Search and Rescue (SAR)
28432	Search and Rescue (SAR)
28570	Search and Rescue (SAR)
28727	Search and Rescue (SAR)

### Sources

DB3K_504

**Comment by KLABDB3K** [comment]
That explains some LUA snags!

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
