### ISSUE TITLE
Update old Ship-Platforms to new Water-Surface Facilities

### ISSUE THREAD

**Issue by dbeagle2** [PygmalionOfCyprus/cmo-db-requests#4275]
### DB Selector

Both

### Affected DBID(s)

DB3K: all Ship (Platform): 3237, 3236, 2100, 1239, 1869, 379, 1586, 378, 484, 377, 3610, 3611, 4451
CWDB: all Ship (Platform): 409, 374, 1872, 2595, 2596

### Summary of Changes

v1.06.1328.13 added water-surface facilities _[(supported only on v504+ DBs). Such facilities are
placed on the water surface (not on the sea bottom) and can be attacked with both land-attack
and anti-ship weapons. Examples of such facilities include bridges (both single-unit and multi-
segment), offshore platforms, piers etc.]_

The old **Type Ship Subtype Platform** should likely be switched to **Type Facility Subtype Water (Surface)**

### Sources

patchnotes v1.06.1328.13

**Comment by PygmalionOfCyprus** [comment]
We can't change ships to facilities and we can't delete entries, so they're staying for backwards compatibility. The facilities annex has already received versions of these.
