### ISSUE TITLE
RCAF CE-133 Silver Star x9

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#428]
### DB Selector

DB3K

### DBID to Copy

1833 DB3k

### Hypothetical

No

### Name

CE-133 Silver Star

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1995-2005

### Sensors

1x Generic Comms Jammer
1x Generic OECM [Average]

### Loadout Options

- Add Offensive ECM Training
- Add Target Tow Training 
- Add Training Exocet Simulation

### Other Changes

9x CT-133's converted to CE-133 for training role

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://va3kgb.com/CdnMilAC/search_result_cdndesig.php
https://en.wikipedia.org/wiki/List_of_aircraft_of_Canada%27s_air_forces
http://www.rwrwalker.ca/post_int.html
https://www.silverhawkauthor.com/post/canadian-warplanes-6-jets-canadair-ct-133a-silver-star
http://www.shearwateraviationmuseum.ns.ca/aircraft/silverstar.htm
https://en.wikipedia.org/wiki/Canadair_CT-133_Silver_Star#Variants
http://nebula.wsimg.com/5fb33fc1767226de7df168bba93f3bbc?AccessKeyId=333C6E3317DD433D51FE&disposition=0&alloworigin=1

**Comment by Jkryos** [comment]
Added DB3K 494.
