### ISSUE TITLE
China, Type 022 Houbei, 2006

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4284]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2002

### Summary of Changes

- [x] _Name_: Type 22 Houbei
> Officially the designation is Type 22[^HJB394]. However, the media and "netizens", dubbed it [i]022[/i], and out of habit, it became commonplace.
- [x] _Year_: 2009
> _Several trusted sources report 2007.[^Meyer][^BCG] eg. However, for the year 2007, only 4 hulls were reported.[^MiBal07] In 2008, 25 hulls were reported.[^MiBal08] And it would be only in July 2009 that "A catamaran brigade from the East Sea Fleet completed full combat capability acceptance, after a one-year work-up of all-weather, integrated training.".[^AMR21] Ergo 2009._
- [ ] _Comments_: 60x
> Most sources are quoting a figure of 60 to 64[^RMSDIPRC23][^MiBal23][^JFS2122][^Meyer][^BCG][^CNSCC][^OROU] et al. Which fits well with 5 fleets of 12 units. A few sources however do quote a figure of 80 units and more.[^WEG][^NVP2201][^ZHIHU][^CT21]
- [x] _Range(nm)/Spd (kts)_: 1200 / 20[^Meyer][^AMD350PB], 300/38[^ANER371][^PATCH286][^BUSS07][^CNSCC][^WEG] _(cruise speed est., based on similar designs)_
> Egorov, in the Foreign military review, mentions a range of 2500 miles. A figure that no other sources came even close to, which I thus disregarded.[^FMR11]
> Note: "Endurance is reduced because watch rotations are impossible with a crew of only twelve; human limitations likely prevent missions beyond roughly twenty-four hours."[^CNSCC]
- [x] _Visual Mod_: Low-viz (military). Efforts have been made to defeat Automatic Recognition/image correlation software and its camouflage would be optimized against air & space detection.[^ROOT] [^pic000]
- [x] _IR Mod_: Shielded exhaust[^ROOT]
- [ ] _Radar Mod_: 2nd Gen heavy shaping.[^ROOT][^CNSCC][^JFS2122]
- _CIC Gen / Ergonomics_: CS Gen 5 (1986-2000)? / Poor?
> Looking at the pictures, I have the feeling that the system could not be on par with current 2001-2029 systems. It also looks to have ergonomy as a distant afterthought. I'm no sailor though, and it's really but a shallow feeling. Your call, as always.
> The system would be designated "H/ZBT-1"[^MDCCIC][^ZHI17][^CNT18]. It would be a derivative of the French Tavitac CIC (federated architecture in LAN), as aboard the La Fayette class, delivered in 1990. It would be an open-architecture system on MIL-STD-1553B standard. [^C4ISR][^WNWS]
- [x] _Troop Cap/Cargo Cap (t)_: 0
> Nothing I have seen or read tends to indicate any kind of cargo capacity whatsoever.
- [x] _Codes_: Built to Mercantile Standards (-30% DP Penalty)
> * Retired naval intelligence officer Mike Dahm mentioned in [Proceedings Podcast Episode 212, March 2021](https://www.usni.org/magazines/proceedings/the-proceedings-podcast/proceedings-podcast-episode-212-chinas-desert-storm), from 33:25, that regarding "Damage Control and thickness of hull", Houbei, and type 56, were built with commercial shipyards technology and would not be made to take a hit. Especially the Type 56, on which he had been underway twice with its frames far apart (further, than USN ships', I assume).
- [x] _Engine_: the name would be "MTU 16V 396 TE74L"[^MTU]. With 2x KaMeWa 21S II and 2x MARIC HL710 waterjets.[^Meyer][^MDC22][^ROOT]
- [ ] _Performance_: 38 knots at flank @ full displacement[^BUSS07][^WKZN] (design speed = 48 knots)[^Meyer][^PATCH286][^CNSCC]

[^kknews]:[中國首型隱身飛彈艇022解析 2018-10-29 由 夢想臨 發表于軍事](https://kknews.cc/military/6z584jp.html)
[^100M]:[造价过亿的022导弹艇，曾被诟病是鸡肋，如今在南海找到用武之地](https://zhuanlan.zhihu.com/p/668416485)
[^AMD350PB]:https://www.sinodefenceforum.com/t/type-022-missile-boat.4076/post-106889
[^AMR21]:Mulberry, John [i]Offshore Patrol Vessels and Fast Attack Craft in the Asia Pacific[/i] in Asian Military Review 21 (December 2009)
[^ANER371]:[Chinese Anti-Ship Cruise Missile Firing as Part of Combined Arms Anti-Carrier Exercises in East China Sea, 30 June-5 July | Andrew S. Erickson, 2010](https://www.andrewerickson.com/2010/07/combined-arms-anti-ship-exercise-in-east-china-sea-30-june-5-july/)
[^ARMEN56][Patrouilleur catamaran type 022 Houbei - Page 3](https://forummarine.forumactif.com/t4239p50-patrouilleur-catamaran-type-022-houbei#245404)
[^BCG]:Bond, Larry, and Carlson, Chris, and Grining, Peter, [i]China’s Navy: Ships and Aircraft of the People’s Republic of China 1955 – 2021[/i], 2021(+err. 2023)
[^BUSEL]Bussert, James, and Elleman, Bruce, [i]People's Liberation Army Navy Combat Systems Technology 1949-2010[/i], 2011
[^BUSS07]:[Catamarans Glide Through Chinese Waters By James C. Bussert | SIGNAL Magazine, Dec.2007(archive)](https://web.archive.org/web/20071216190342/http://www.afcea.org/signal/articles/templates/Signal_Article_Template.asp?articleid=1433&zoneid=222)
[^CDSI]:[A Comprehensive Survey of China's Dynamic Shipbuilding Industry](https://digital-commons.usnwc.edu/cgi/viewcontent.cgi?article=1000&context=cmsi-red-books)
[^CNSCC]:[Erickson, Andrew S. and Martinson, Ryan, "China Near Seas Combat Capabilities" (2014). CMSI Red Books, Study No 11.](https://digital-commons.usnwc.edu/cgi/viewcontent.cgi?article=1010&context=cmsi-red-books)
[^CNT18]:[針對臺灣研發 中共22型飛彈快艇逐步淡出舞臺 - 中時新聞網 - 中時新聞網](https://www.chinatimes.com/amp/realtimenews/20180111004295-260518)
[^FMR11]:[Egorov, V., Main trends in the development of missile boats of foreign navies, Foreign military review. - 2011. - No. 3. - pp. 81-87](http://factmil.com/publ/strana/kitaj/osnovnye_tendencii_v_razvitii_raketnykh_katerov_vms_inostrannykh_gosudarstv_2011/59-1-0-241)
[^HJB394]:[HJB 394-2007 22型导弹快艇规范](https://web.archive.org/web/20190220182723/http://www.zbgb.org/101/StandardDetail1100960.htm)
[^JC4ISRM]:Jane's [i]C4ISR & Mission Systems : Maritime[/i], 2015-2016
[^JFS2122]:Jane's Fighting Ships 2021-2022
[^KIRCH]:Kirchberger, Sarah, [i]Assessing China's Naval Power: Technological Innovation, Economic Constraints, and Strategic Implications[/i], Springer, 2015
[^MARIC][CSSC, MARIC Jet, Waterjet Units Catalagoe (PDF)](https://www.eworldship.com/index.php?m=content&c=readpoint&catid=2549&wid=21130&allow_visitor=1)
[^MDC22]:[22型導彈快艇 - MDC軍武狂人夢 (Taiwan's Military Dream Club)](http://www.mdc.idv.tw/mdc/navy/china/022.htm)
[^MDCCIC]:[中國海軍作戰指揮/編隊指揮/數據傳輸系統](http://www.mdc.idv.tw/mdc/navy/china/china-cms2.htm)
[^MTU]:[MTU 16V396TE74L marine diesel engine-2000kw | CMC-MTU / MTU diesel engine & spare parts imp. & exp. co.,ltd.](http://www.cmc-mtu.com/index.php/mtu-16v396te74l-marine-diesel-engine-2000kw/)
[^Meyer]:Meyer, Manfred, [i]Modern China’s Maritime Forces[/i] Second Edition, 2023
[^MiBal07]:[i]The Military Balance 2007[/i], Volume 107, Issue 1
[^MiBal08][i]:The Military Balance 2008[/i], Volume 108, Issue 1
[^MiBal23]:[i]The Military Balance 2023[/i], Volume 123, Issue 1
[^NVP2201]:[No2201 (project 022) fast attack craft (missile) (2004-2010) - Navypedia](https://www.navypedia.org/ships/china/ch_cf_2201.htm)
[^ONI22]:[Office of Naval Intelligence's PLA Navy Identification Guide (2022)](https://www.oni.navy.mil/ONI-Reports/Foreign-Naval-Capabilities/China/)
[^PATCH286]:[Patch, John Cdr (Ret) A Thoroughbred Ship-Killer | Proceedings - April 2010 Vol. 136/4/1,286](https://www.usni.org/magazines/proceedings/2010/april/thoroughbred-ship-killer)
[^RMSDIPRC23]:[2023 Report on the Military and Security Developments Involving the People's Republic of China (CMPR)-PDF](https://media.defense.gov/2023/Oct/19/2003323409/-1/-1/1/2023-MILITARY-AND-SECURITY-DEVELOPMENTS-INVOLVING-THE-PEOPLES-REPUBLIC-OF-CHINA.PDF)
[^ROOT]:[Root, George PLAN Type 22 “Houbei” Fast Attack Craft (Updated: 14 September 2012)](https://www.scribd.com/document/105941484/PLAN-Type-22-Houbei-FAC-14Sept12-Update)
[^TWI]:[Friction stir welding of aluminium ships - TWI](https://www.twi-global.com/technical-knowledge/published-papers/friction-stir-welding-of-aluminium-ships-june-2007)
[^WEG]:[Type_22 Class (Houbei_Class) | Worldwide Equipment Guided - ODIN](https://odin.tradoc.army.mil/WEG/Asset/Type_22-Class_(Houbei_Class)_Chinese_Fast_Attack_Missile_Boat)
[^WNWS]:Friedman, Norman, [i]The Naval Institute Guide to World Naval Weapon System[/i], Fifth Edition. 2006
[^ZHI17]:[新时代的海上锋刃——中国22型导弹艇 - 知乎](https://zhuanlan.zhihu.com/p/78128514)
[^ZHIHU]:[80艘的022导弹艇未来还有什么作用？网友：赶快出口给别的国家 - 知乎](https://zhuanlan.zhihu.com/p/178710167)
[^OROU]:[O’Rourke’s Latest CRS Report—“China Naval Modernization: Implications for U.S. Navy Capabilities”—USG/N Info on PLAN Ships & Projections of #s Lead thru 2040 | Andrew S. Erickson](https://www.andrewerickson.com/2023/10/orourkes-latest-crs-report-china-naval-modernization-implications-for-u-s-navy-capabilities-usg-n-info-on-plan-ships-projections-of-s-lead-thru/)
[^CT21]:[國戰會論壇》022導彈快艇＋蜂群無人機 大殺器來了（譚傳毅）](https://web.archive.org/web/20220425142943/https://www.chinatimes.com/opinion/20210507000010-262110?chdtv)
[^WKZN]:[22型导弹快艇 - 维基百科，自由的百科全书](https://zh.wikipedia.org/zh-hans/22%E5%9E%8B%E5%AF%BC%E5%BC%B9%E5%BF%AB%E8%89%87)

------

#### Visual Mod: Low-viz (military)
https://cdn.discordapp.com/attachments/1080708193342210058/1180170498945073273/image.png
https://cdn.discordapp.com/attachments/1080708193342210058/1180170751874175027/image.png
https://cdn.discordapp.com/attachments/1080708193342210058/1180170861395841036/image.png

#### Heat exchanger/underside exhaust
https://cdn.discordapp.com/attachments/1080708193342210058/1180172533245431898/image.png
https://cdn.discordapp.com/attachments/1080708193342210058/1180172251790839828/Type022_2.jpg

#### CIC/bridge Pictures
https://cdn.discordapp.com/attachments/557669654055878676/1180135157831843861/image.png
https://cdn.discordapp.com/attachments/557669654055878676/1180134586722811944/image.png
https://cdn.discordapp.com/attachments/557669654055878676/1180134285521453076/image.png
https://cdn.discordapp.com/attachments/557669654055878676/1180135157831843861/image.png
https://cdn.discordapp.com/attachments/1080708193342210058/1180861683741237378/51947905877_3ceac5ee6c_o.png

----

**Trivia**:  In 2023, the cost per unit would be "over 100 million" Yuan, ie. about 14M USD.[^100M]

PS: you guys already fixed about half of the things I was about to suggest, based on 503. Good job! 

### Sources

**Comment by claudejdev** [comment]
By the way, I don't know what the sensors circled in yellow and red are.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/d64d0082-0549-4838-8070-9269a67e33e6)

**Comment by PygmalionOfCyprus** [comment]
\>all those chinese sources

![1514040684262](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/720208a6-9d5c-4c7f-98ff-05e76d9e2c50)

Goddamn, this is why you're one of the best.

>By the way, I don't know what the sensors circled in yellow and red are.

I think the yellow one is a stealth housing for a spotlight/signal lamp. It's not present on all vessels. You can see a head-one view [here](https://www.naval.com.br/blog/2008/12/03/navios-patrulha-lanca-misseis-houbei-type-022/) and [here](https://2.bp.blogspot.com/-qP7ngiSjceM/UE1iXrOtJcI/AAAAAAAAQGk/LXwe75kXybU/s1600/Type+022+(Houbei+Class)+Fast+Attack+Missile+Craft+stealth+catamaran+hulls+People's+Liberation+Army+Navy+(PLAN+or+PLA+Navy)+test+firing+8+YJ-83+anti-ship+missiles+(1).jpg).

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/53ab1998-ef37-4811-871f-68c49a09e625)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/5d35fce8-af9f-488c-b19c-658f391a4ecb)


Red is...comms. I think. IIRC I've seen it on a few other ships. I don't know what it is, though. It's not the HN-900; the HN-900 antenna is the barrel-on-a-stick in the back. I don't think it's CEC (China CEC is phased-array, you can see them on the 055s). Maybe it's some weird Type 22-specific stealth mount (like for the searchlight) for SATCOM or something?

**Comment by PygmalionOfCyprus** [comment]
![sdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/6d3fc968-ddf8-4e09-ab00-bfed35e2a061)

**Comment by claudejdev** [comment]
Thanks, it means a lot! :blush:

Yeah, I had kind of a culture shock on SD :grinning:
(Lesson learned: do NOT quote non-mainland Chinese sources there)

**Comment by PygmalionOfCyprus** [comment]
Handled 506, mostly. Skipping the count because we don't usually worry about ship count when it's above a small number. Also not giving it Zumwalt-tier shaping because there are a lot of exposed antennae, etc. even if they do put some of it in stealth mounts. Gave it 2 Gen Med shaping instead. And going to keep the full/flank 38-42 to account for variation.
