### ISSUE TITLE
add AESA to K-77M ARH seeker (and increase arc)

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#4286]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5955 , Weapon 3126

### Summary of Changes

changes: 
-add AESA property to the arh seeker for the r-77m missile (db3126)
-increase coverage arc to 90 degrees (standard for AESA)

currently seeker is set to mechanically steered doppler mono-pulse with a 45 degree arc

Thank you

![k-77m](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/fba788cb-40cb-4378-ad11-ad74b3450614)

### Sources

https://nationalinterest.org/blog/reboot/russia%E2%80%99s-highly-maneuverable-r-77-missile-bad-news-nato-192380

https://military-history.fandom.com/wiki/R-77#Variants

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
