### ISSUE TITLE
FFG-62  Request to remove Mark 32 Surface Vessel Torpedo Tubes

### ISSUE THREAD

**Issue by ailantic** [PygmalionOfCyprus/cmo-db-requests#4289]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3229 Constellation 

### Summary of Changes

The Constellation class will not have ship-launched Mark 32 Surface Vessel Torpedo Tubes

### Sources

https://www.dote.osd.mil/Portals/97/pub/reports/FY2020/navy/2020ffg62.pdf?ver=Em_f9TAyXHh_kTo0b2pyfw%3D%3D
https://en.wikipedia.org/wiki/USS_Constellation_(FFG-62)

**Comment by KushanGaming** [comment]
Done for DB505.
