### ISSUE TITLE
China, PLAN, Type 346 radar, range and peak power

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4291]
### DB Selector

DB3K

### Affected DBID(s)

sensor 2116 5127 5963

### Summary of Changes

- [x] Reduce the Type 346A's range to a more reliable 236nm (This does not conflict with the estimate of "at least 400km")
- [x] Increase the Type 346's range to 189nm. Type 346B's range to 378nm (236nm x 160%)
- [x] Increase in peak power of sensor 2116 to 476800W; sensor 5127 to 596000W; sensor 5963 to 1192000W
- [ ] Increase in radar gain of sensor 2116 5127 5963 to 45/50/55db

### Sources

https://en.wikipedia.org/wiki/Type_346_radar
https://navyrecognition.com/index.php/focus-analysis/naval-technology/5374-analysis-sensor-and-electronic-warfare-suites-aboard-china-s-type-055-destroyer.html
https://www.janes.com/defence-news/news-detail/more-details-emerge-about-detection-capabilities-of-type-055-destroyers-radar

**Comment by claudejdev** [comment]
If I understand that correctly "source", base 346 had a 100W peak power per 4-unit T/R module ?
https://web.archive.org/web/20160815175813/http://redchinacn.net/portal.php?mod=view&aid=29403


Chinese designation would be H/_LJG-346_. (Jane's C4ISR Maritime 2016, page 476)

Admiralty Trilogy Hapoon 5 Data Annex interpretation is:

Name | max Range, Air | Max Range, Surf | IOC
---  | ---  | --- | ---
LJG-346  | 125 | 30 | 2006
LJG-346A  | 150 | 35 | 2014
LJG-346B  | 250 | 38 | 2020

**Comment by LuigiP57** [comment]
> If I understand that correctly "source", base 346 had a 100W peak power per 4-unit T/R module ? https://web.archive.org/web/20160815175813/http://redchinacn.net/portal.php?mod=view&aid=29403
> 
> Chinese designation would be H/_LJG-346_. (Jane's C4ISR Maritime 2016, page 476)
> 
> Admiralty Trilogy Hapoon 5 Data Annex interpretation is:
> 
> Name	max Range, Air	Max Range, Surf	IOC
> LJG-346	125	30	2006
> LJG-346A	150	35	2014
> LJG-346B	250	38	2020

Once again, I'm impressed by your information-gathering skills.

As for the article you quoted, I feel that this is either another outdated tech leak or an elaborate story. I find this article a bit suspicious because it is so dramatic.

However, from the English translation of this article, I read the following:

> Then, I showed the computer of the search distance that S-band radar and C-band radar can cover when tracking multiple targets with accuracy (the number and accuracy of tracking are in accordance with the military's index requirements) according to Mr. Wang's calculation formula. The simulation results (with charts and graphs) clearly allow the members of the jury to see that the 14 S-band radars can guarantee a search coverage distance of more than 320 kilometers under any circumstances (and except for the +/- 60-degree low angle guarantee of 320KM , the rest of the range is above 350KM, and the center even reaches about 375KM)

If the Chinese researchers' internal simulations are accurate, the range of the Type 346 radar in the database is even underestimated. It should be adjusted to 189nm/350KM (the most representative value in the article) instead of the current 150nm.

By reasonable estimation, the maximum distance of type 346A should be 236nm (189x1.25) and 346B is 378nm (189x1.25x1.6).

AESA's T/R modules enable higher energy utilization efficiency, resulting in better radar gain at lower peak power. Therefore, I take it for granted that the 346 series has a higher radar gain than the SPY-1 PESA.

I will update the ticket according to your information. Thanks again.

Cheers!

**Comment by PygmalionOfCyprus** [comment]
Handled 509. I haven't noodled with the gain/loss since using those values and the stated peak power values would push the detection range up into thousands of nmi. Nevertheless the radars should now perform as expected.

**Comment by RickDNiu** [comment]
#5097
