### ISSUE TITLE
Add land attack capability to 3M22 Zircon

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#4292]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3361

### Summary of Changes

recently debris was found of a 3M22 Zircon hypersonic cruise missile that struck Kiyv city
![322](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/152485563/57c71d27-7beb-41c5-816a-410c4675dbcf)

Changes:
-add land attack capability for hard and soft targets (both mobile and immobile) 

### Sources

https://mil.in.ua/en/news/invaders-shell-kyiv-with-newest-zircon-hypersonic-missile/

https://en.defence-ua.com/news/zircon_missile_used_for_strike_on_kyiv_apparently_the_russian_wunderwaffe_was_shot_down-9439.html

**Comment by tbrandon517** [comment]
Not at home so can't check v504 but v502 shows land attack capabilities already in sim for Zircon just not for mobile units

https://cmano-db.com/weapon/3361/
