### ISSUE TITLE
China, PLAN, YJ-12 & YJ-18, range issue

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4295]
### DB Selector

DB3K

### Affected DBID(s)

weapon 2862 2863 2867 2868

### Summary of Changes

1. Increase weapon 2862 2863 range to 270nm
2. Increase weapon 2867 2868 range to 324nm

### Sources

https://frontierindia.com/china-confirms-yj-12a-missiles-complex-trajectories-and-500-km-supersonic-range/

> A few days ago, the Chinese state-run media outlet CCTV disclosed that the supersonic anti-ship missile known as the Eagle Strike 12A (YJ-12A) ranges up to 500 kilometres and is primarily intended to attack large surface ships belonging to hostile nations. In the past, it was believed to have an operational range of 250 and 400 kilometres. Most available information about the YJ-12 comes from unofficial sources or is estimated; hence this information becomes important. The broadcaster also mentioned in the programme that the YJ-18 missile has a range of 600 kilometres.

https://zh.m.wikipedia.org/wiki/%E9%B7%B9%E6%93%8A12%E5%8F%8D%E8%89%A6%E9%A3%9B%E5%BD%88
https://zh.wikipedia.org/zh-cn/%E9%B9%B0%E5%87%BB18%E5%8F%8D%E8%88%B0%E5%AF%BC%E5%BC%B9

**Comment by LuigiP57** [comment]
Bury myself in learning Chinese. Mamma Mia! It's torture, isn't it?

**Comment by PygmalionOfCyprus** [comment]
Handled 506.

>Bury myself in learning Chinese. Mamma Mia! It's torture, isn't it?

I should have learned Chinese instead of Japanese, but the cartoons are better. :P
