### ISSUE TITLE
Ababil-2 loitering munition version unable to be fired and range issue

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#4296]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4173, 4360

### Description of Problem

- Weapon 4173 cannot be launched
- Weapon 4360 petered out before it got into max range

### Recommended Fix

- Give same Guidance Type as Weapon 4360 to Weapon 4173 to fix launch issue
- Probably need to increase the aviation fuel for both weapon IDs.

**Comment by PygmalionOfCyprus** [comment]
Handled 505. I forgot to give the UHF Radio link to the launcher so 4173 was waiting on a datalink. Increased fuel 10x for both which should get it where it needs to go.
