### ISSUE TITLE
German Typhoon with Brimstone missiles

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4297]
### DB Selector

DB3K

### User(s)

Germany [FRG/Reunified]

### Weapons Carried

Same as present loadout for UK Typhoon:
-Change ASRAAM for IRST
-And change Paveway IV for GBU-49

![Brimstone loadout](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/c71ae088-a9a8-4b33-915f-7470069f99a8)

### Requires Buddy Illumination

Yes

### Default Combat Radius (nm)

Same as UK loadout

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Contract this year, so delivery probably in 2025

### Sources

[https://militaryleak.com/2024/01/21/german-air-force-boosts-arsenal-with-brimstone-missiles-for-eurofighters/](url)
[https://miragec14.blogspot.com/2024/01/germany-to-arm-their-eurofighters-with.html](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
