### ISSUE TITLE
#660 and #2494 Chinese AOEs don't have refuel or replenish properties

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#43]
### DB Selector

DB3K

### Affected DBID(s)

#660 and #2494

### Description of Problem

Tankers need the replenish and refuel too properties/flags to work. 

### Recommended Fix

Add stations for each on each side.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
