### ISSUE TITLE
United States, KC-10A Extender

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4303]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 214

### Aircraft
ID 214 _KC-10A Extender_

- Fuel: 160200 [^AF][^AMC] (or 161510 [^ADTG], or 158290 in Tanker conf.[^JAWA])

> DataFuel ID 750 is only used by K(D)C-10, if think it's safe to edit.

### Loadouts
**Range**

- Tanker (ID 8989): 3800[^AF] (or 4248 [^ADTG], or 3797 [^JAWA])
- Ferry (ID 8990): 10000[^AF] (or 8495 [^ADTG], or 9993 [^JAWA][^AMC])
- Cargo (ID 15038): 3800[^AF] (or 4248 [^ADTG], or 3797 [^JAWA])

### Engine
ID 561 3x F103-GE-101/CF6-50-C2
- ThrustPerEngineMilitary: 23800 [^AF] (F103-GE-101: 23500 [^RX])
- SFCMilitary: 0.37 (F103-GE-101: 0.4) [^RX]

### Sources

[^AMC]: [KC-10 Extender > Air Mobility Command > Display](https://www.amc.af.mil/About-Us/Fact-Sheets/Display/Article/2848919/kc-10-extender/)
[^AF]: [KC-10 Extender > Air Force > Fact Sheet Display](https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104520/kc-10-extender/)
[^JAWA]:Jane's All the World's Aircraft: In Service 2021-2022, p.206
[^ADTG]: Larry Bond, Chris Carlson, & Peter Grining. America’s Aircraft - U.S Military Aircraft 1955 - 2020, Jan. 2024
[^RX]:Roux, Élodie. Turbofan and Turbojet Engines: Database Handbook, Les Editions Elodie Roux, 2007. p.106

**Comment by KushanGaming** [comment]
Done for DB505.

**Comment by claudejdev** [comment]
@KushanGaming 

### Addendum:

Mission command Comms mod:
(you probably don't want to create a specific variant)

**Comms**
- add: ID 33 AN/ARC-164 Have Quick 
- add: ID 234 AFSATCOM

Source: _The Book_, p.91,94.
