### ISSUE TITLE
KF-16 GBU-39 SDB Loadout

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#4304]
### DB Selector

DB3K

### User(s)

ROKAF KF-16C 2017-2020, KF-16D 2017-2020

### Weapons Carried

Same with F-16 SDB Loadout in other countries.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same with F-16 SDB Loadout in other countries.

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The Korean Air Force purchased SDB in 2013 and is currently operated by F-16, F-35, and F-15K.

### Sources

https://youtu.be/sHZ_YuOH2BE?si=60Akgw_TLNSr_OC9
https://en.wikipedia.org/wiki/GBU-39_Small_Diameter_Bomb

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
