### ISSUE TITLE
Add GBU-39 SDB Loadout to ROKAF, Israel Air Force

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#4305]
### DB Selector

DB3K

### User(s)

ROKAF F-35A 2020, Israel F-35I 2018-2025

### Weapons Carried

Same SDB Loadout in other countries F-35

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same SDB Loadout in other countries F-35

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The Korean Air Force purchased SDB in 2013 and is currently operating on KF-16, F-35, and F-15K

The Israeli Air Force has been operating the SDB since 2008, and it is also equipped on the F-35I and is in operation.

### Sources

https://en.wikipedia.org/wiki/GBU-39_Small_Diameter_Bomb
https://www.australiandefence.com.au/defence/air/us-approves-f-35-weapons-sale-to-korea
https://www.dsca.mil/press-media/major-arms-sales/korea-f-35-munitions
https://thaimilitaryandasianregion.blogspot.com/2018/05/arab-news-claimed-that-israeli-f-35i.html

**Comment by PygmalionOfCyprus** [comment]
Handled 506.

**Comment by clerara10** [comment]
> Handled 506.

Thank you I have a request I posted before, but I think it's forgotten, so I'm posting a link. Can you check this request as well?

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/3654#issue-1834748251
