### ISSUE TITLE
Caravelle, civilian, type mismatch

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4306]
### DB Selector

Both

### Affected DBID(s)

Aircraft 31416

### Summary of Changes

> Civilian Caravelle's Type should be Commercial.

- [x] _CWDB ID 3604 SE-210 Caravelle III_

- [x] _DB3k  ID 4444	Sud Aviation SE-210 Caravelle III_

- Type: Commercial (7301)

### Sources

DB3K 504
CWDB 504

**Comment by KushanGaming** [comment]
DB3K fixed for DB505.

**Comment by PygmalionOfCyprus** [comment]
CWDB handled 506.
