### ISSUE TITLE
RCAF De Havilland Mosquito Mk.PR.16 x444

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#431]
### DB Selector

CWDB

### DBID to Copy

516 CWDB

### Hypothetical

No

### Name

Mosquito Mk.PR.16

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1943-51

### Sensors

N/A

### Mounts

N/A

### Loadout Options

N/A

### Other Changes

N/A

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://va3kgb.com/CdnMilAC/search_result_acname.php
https://en.wikipedia.org/wiki/De_Havilland_Mosquito#Operators
https://www.silverhawkauthor.com/post/canadian-warplanes-3-de-havilland-dh-98-mosquito

![60f99112a1b2732f830216fa_de-Havilland-DH-98-Mosquito-aircraft-of-418-Squadron--with-TH-H--NT137--centre](https://user-images.githubusercontent.com/99632305/156235516-e698fed2-132d-4eaf-a75a-a397df71b323.jpg)

**Comment by Jkryos** [comment]
Added CWDB 494.
