### ISSUE TITLE
Increased range of LAMD

### ISSUE THREAD

**Issue by tksfpj** [PygmalionOfCyprus/cmo-db-requests#4317]
### DB Selector

DB3K

### Affected DBID(s)

South Korea LAMD

### Summary of Changes

LAMD is an interception missile developed based on K-SAAM and has a range of 20km like K-SAAM

### Sources

https://m.blog.naver.com/kevin1406/222661937228 
This is a Korean blog related to LAMD and please use a translator

It is also based on what I heard from LIG NEX1 officials at ADEX 2021

**Comment by PygmalionOfCyprus** [comment]
Handled 506.

**Comment by clerara10** [comment]
> Handled 506.
Please take a look at the request as well

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4304#issue-2132390035

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4305#issue-2132397879
