### ISSUE TITLE
Update Poland FA-50GF/PL weapons loadout

### ISSUE THREAD

**Issue by tksfpj** [PygmalionOfCyprus/cmo-db-requests#4318]
### DB Selector

DB3K

### Affected DBID(s)

Poland FA-50GF 2023, FA-50PL

### Summary of Changes

The FA-50 of the Polish Air Force has the same specifications as the FA-50 of the Korean Air Force. Therefore, GBU-38 JDAM, AGM-65 Maverick should be added to the armament that can be used like the FA-50 of the ROKAF

You can copy and apply the FA-50 loadout of the ROKAF

### Sources

https://www.blogbeforeflight.net/2023/05/kai-unveils-first-fa50-poland.html?m=1

https://www.airforce-technology.com/projects/fa-50-light-combat-aircraft-south-korea/

**Comment by Huib18** [comment]
The first variant (12 A/C) is the FA-50GF (Sidewinder and Maverick only) (GF means Gap Filler, no kidding) from 2023 onwards
The second variant as stated in the sources is the FA-50PL block 20 (36 A/C) Delivery 2025-2028 with all the kid mentioned in the sources.
Then the FA-50GF will be upgraded.
Sumup: two variants

**Comment by tksfpj** [comment]
> The first variant (12 A/C) is the FA-50GF (Sidewinder and Maverick only) (GF means Gap Filler, no kidding) from 2023 onwards The second variant as stated in the sources is the FA-50PL block 20 (36 A/C) Delivery 2025-2028 with all the kid mentioned in the sources. Then the FA-50GF will be upgraded. Sumup: two variants

That's right FA-50GF and FA-50PL are different derivatives, but both aircraft can use GBU-38 and AGM-65 Maverick and I was pointing this out

**Comment by PygmalionOfCyprus** [comment]
No, the Gap Fillers and early FA-50PLs are not able to launch these weapons until they are integrated in a later program. See https://www.thedrive.com/the-war-zone/polands-new-fa-50-light-fighter-emerges

> The FA-50PLs will ultimately receive tactical data links, Sniper advanced targeting pods, active electronically scanned array (AESA) radars, advanced self-protection capabilities, more fuel capacity, and the ability to launch precision-guided munitions like the AGM-65 Maverick air-to-ground missile and GBU-38/B Joint Direct Attack Munitions (JDAM).

There's more in the article, but the language clearly implies that this is a capability to be implemented, not a capability available at delivery for the PLs, and certainly not for the GFs.
