### ISSUE TITLE
RCAF De Havilland Vampire F. MK3 x86

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#432]
### DB Selector

CWDB

### DBID to Copy

278 CWDB

### Hypothetical

No

### Name

Vampire F. MK3

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1946-58

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://va3kgb.com/CdnMilAC/search_result_acname.php
https://en.wikipedia.org/wiki/List_of_aircraft_of_Canada%27s_air_forces
https://en.wikipedia.org/wiki/De_Havilland_Vampire#Canada
http://www.rwrwalker.ca/rcaf1_5digit_main.html
https://www.silverhawkauthor.com/post/canadian-warplanes-6-jets-de-havilland-dh-100-vampire

![60fbd939fc34fd0fdcf2248d_de-Havilland-DH-100-Vampire--RCAF--17067---James-Craik](https://user-images.githubusercontent.com/99632305/156236521-03e8b703-c220-4cd2-99a5-a52f5bb1c4de.jpg)

**Comment by Jkryos** [comment]
Added CWDB 494.
