### ISSUE TITLE
Add YJ-18 land-based variant

### ISSUE THREAD

**Issue by KushanGaming** [PygmalionOfCyprus/cmo-db-requests#4320]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Bn (YJ-18)

### Facility Type

SSM

### Country

China

### Service

Coastal Artillery

### In Commission

Unknown

### Number in Service

Unknown

### Crew

N/A

### Dispersion Radius (m)

60

### Sensors

1x China Type 352 Square Tie (provided by mount)

### Mounts

1x Vehicle (China Type 352 Square Tie)
4x YJ-18 (single missile per mount)

### Magazines

None

### Aircraft & Docking Facilities

None

### Comments

This may have a larger booster to increase range. Can't find anything definitive. Maybe add longer range variant as a hypothetical.

### Sources

https://en.wikipedia.org/wiki/YJ-18

https://navalpost.com/wp-content/uploads/2021/08/yj-18-image02.jpeg

https://www.globalsecurity.org/military/world/china/images/yj-18-image04.jpg

**Comment by LuigiP57** [comment]
I think this is the land-based YJ-18 TEL. The link you're referencing is supposed to be a display for military parades. At present, there is no information indicating its entry into the PLAN coastal defense force sequence. So I hope you could define it as hypo.
https://navyrecognition.com/index.php/naval-news/naval-news-archive/year-2015-news/august-2015-navy-naval-forces-defense-industry-technology-maritime-security-global-news/2959-new-mobile-coastal-variant-of-yj-18-supersonic-anti-ship-missile-spotted-in-china.html
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/1e3e7f8b-81dd-4231-b91d-5742d6a793a9)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/4e6c89b6-1430-4329-b4a9-fc9926ef6ac9)

**Comment by LuigiP57** [comment]
> This may have a larger booster to increase range. Can't find anything definitive. Maybe add longer range variant as a hypothetical.

It is true that it has a longer booster, so it is reasonable to think that it has a longer range. Maybe we can simply increase the range of the land-based version of the ticket to 432nm/800km (seems reasonable to me) without adding the hypo version (because the ticket is supposed to be hypo).

**Comment by Jkryos** [comment]
Added DB3K 506.
