### ISSUE TITLE
China, PLAN, YJ-21 on Type 052D DDG

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4321]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4058 4059; ship 3586 & 4719

### Summary of Changes

As I described in another ticket #4178 , the Type 052Ds series have 9m UVLS and is therefore fully capable of equiping the YJ-21 hypersonic weapon on the newer build batches.

Also, I've seen numerous scenarios made by players manually adding such weapon to the type 052Ds. Therefore, I do not think there is anything unreasonable about making such an update.

Or just add a hypothetical platform based on current Type 052DL in DB.

### Sources

https://en.wikipedia.org/wiki/GJB_5860-2006
https://zh.wikipedia.org/wiki/052D%E5%9E%8B%E5%AF%BC%E5%BC%B9%E9%A9%B1%E9%80%90%E8%88%B0
Translation:
> The Type 052D guided missile destroyer is equipped with a universal vertical launch device, including a total of 64 missile universal vertical launch units. Compared with the six-mounted rotating round launch unit of the vertical launch system of the Type 052C destroyer, the new vertical launch system has been changed to a square launch unit. 32 units are arranged on the front deck in front of the bridge, and 32 units are arranged in front of the helicopter hangar. It solves the problem of flexibility in carrying vertical weapons and may have the ability to load multiple missiles in one launch tube. Compared with the round-section compartment vertical launchers of the Type 052D guided missile destroyer, the square-section compartment vertical launchers of the Type 052D guided missile destroyer can be arranged at a higher density. In addition, the new vertical launcher has a higher bomb-carrying base and can complete the "cold-hot" co-launch of HHQ-9B, YJ-18A, CJ-10 and other types of missiles. When performing different combat missions, it can carry The configuration of ammunition type and quantity is more flexible. **It has the capability to launch shipborne YJ-21 hypersonic anti-ship ballistic missiles, which can strike against water and land targets.**

**Comment by LuigiP57** [comment]
#4206 
#4188

**Comment by LuigiP57** [comment]
We've got some up-to-date information here: It is implied (or expected) that the 052D UVLS can accommodate the YJ-20/21 (I wouldn't be surprised it's already equipped).
https://www.sinodefenceforum.com/t/plan-anti-ship-surface-missiles.6345/page-136#post-111
Originated from 3M-54E1, YJ-18 is of high possiblity a 8.9m long missile. Similar to YJ-20/21. The YJ-18 can be accommodated, and the YJ-20/21 can obviously too.
![image](https://github.com/user-attachments/assets/087fcf44-e65d-496c-94d6-572e9a85675c)
https://www.sinodefenceforum.com/t/09v-09vi-095-096-nuclear-submarine-thread.8228/page-130
![image](https://github.com/user-attachments/assets/a743bf23-4d22-40d2-abe3-fd526b350080)

**Comment by PygmalionOfCyprus** [comment]
Handled 509 w/ new 2022 entries for the YJ-21-equipped versions. Also added to the 052DLs. I hope we see a launch video/picture from an 052D soon!
