### ISSUE TITLE
SSN 804 SSN too noisy

### ISSUE THREAD

**Issue by FTBSS** [PygmalionOfCyprus/cmo-db-requests#4324]
### DB Selector

DB3K

### Affected DBID(s)

SSN 668

### Summary of Changes

The noise level is not improved over B;ock 1 version of SSN 774 and one of the pillars of the Block V is advanced sound isolation

### Sources

https://www.defensenews.com/naval/2019/12/06/heres-what-you-need-to-know-about-the-us-navys-deadly-and-expensive-new-attack-submarines/

https://gentleseas.blogspot.com/2016/10/submarine-noise.html?m=1

**Comment by PygmalionOfCyprus** [comment]
It's currently impossible to make these sorts of adjustments with the rudimentary sound modifier system we have. We've got an idea to rework it and will handle this as part of the larger fix tied into #1858.
