### ISSUE TITLE
China, PLAAF, KJ-3000 Airborne Surveillance Radar

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4325]
### DB Selector

DB3K

### Baseline

sensor 7122

### Hypothetical

Yes

### Name

China KJ-3000 AESA Radar

### Sensor Generation

Early 2020s

### Range (nm)

350

### Sensor Capabilities

Air Search, Surface Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Non-Cooperative Target Recognition (NCTR) - Jet Engine Modulation [Class Info], Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA)

### Search/Track Frequencies

B Band (250-500 MHz) [Old P Band (VHF)] 60-100 cm

### Horizontal Beamwidth (deg)

1

### Vertical Beamwidth (deg)

1

### System Noise Level (dB)

2

### Processing Gain/Loss (dB)

15

### Peak Power (W)

1500000

### Comments

This radar is to replace the faulty “KJ-2000 radar” used by the Y-20 AEW (more accurately, KJ-3000).

Based on the available information, the radar is still a rotating array similar to the E-3/E-2D. It may have greater anti-stealth capability, so the band is set to B-band/VHF-UHF-band (450-500MHz, similar to E-2C, The [IEEE] defines the UHF [radar band] as frequencies between 300 MHz and 1 GHz, I did this mainly to **highlight its anti-stealth capabilities**) and other better performance.

However, we still have too little information available, and it is unlikely that we will see it in the near future, so it is categorized as Hypo.

### Sources

https://www.globalsecurity.org/military/world/china/y-20kj.htm
https://www.china-arms.com/2020/02/kj3000-aewc-aircraft/#google_vignette
https://en.wikipedia.org/wiki/KJ-2000
https://twitter.com/RupprechtDeino/status/1736296335668646215

> Up to now, China's advanced low-frequency anti-stealth radar system has been developed from land to sea and from land to air. The new generation of KJ600 early warning aircraft developed by the Navy and Shendiao unmanned aerial vehicle developed by the Air Force are all air detection platforms with advanced low-frequency radar systems.

https://en.wikipedia.org/wiki/Ultra_high_frequency

> The [IEEE] defines the UHF [radar band] as frequencies between 300 MHz and 1 GHz.

**Comment by LuigiP57** [comment]
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/f93cb0c9-a48b-40c7-82eb-fffeaa6385d8)

**Comment by LuigiP57** [comment]
A Chinese article on the development of anti-stealth low frequency radar in China
https://zhuanlan.zhihu.com/p/666299275

> Up to now, China's advanced low-frequency anti-stealth radar system has been developed from land to sea and from land to air. The new generation of KJ600 early warning aircraft developed by the Navy and Shendiao unmanned aerial vehicle developed by the Air Force are all air detection platforms with advanced low-frequency radar systems.

I'm not sure if the KJ-600 has an "advanced low-frequency anti-stealth radar", however, I think we can at least implement it on this platform. Because, with China's advances in radar technology in the 21st century, I think this is highly possible.

**Comment by Jkryos** [comment]
Added DB3K 506.
