### ISSUE TITLE
China, PLAAF, Y-20 AEW aka KJ-3000 AEW&C

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4326]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4976

### Summary of Changes

- [x] Rename it as KJ-3000 AEW&C
- [x] Re-categorize it as Hypothetical
- [x] Replace its radar with KJ-3000 AESA
- [x] Upgrade its other sensor to early 2020s tech
- [x] Add SIGINT and DECM w early 2020s tech to it (Lacking electronic sensors)
- [x] Add PL-15 & PL-17 datalinks that can perform CEC (if available)

### Sources

#4325

**Comment by Jkryos** [comment]
Updated DB3K 506.
