### ISSUE TITLE
Türkiye, TAI TF Kaan Fighter

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4328]
### DB Selector

DB3K

### Baseline

Aircraft 3821

### Hypothetical

No

### Name

TAI TF Kaan

### Country

Türkiye

### In Commission

2028

### Length (m)

21

### Wingspan (m)

14

### Height (m)

6

### Empty Weight (kg)

-

### Maximum Takeoff Weight (MTOW) (kg)

27215

### Crew

1

### Propulsion

2x F110-GE-129

### Service Ceiling (ft)

55000

### Military/Afterburner Speed (kt)

1190

### Cruise Speed (kt)

480

### Supercruise

No

### Ferry Range (nm)

2500

### Fuel Capacity (kg)

9000

### Sensors

- IRFS (AESA Radar, Electronic Warfare (EW))
- Advanced Navigation Features (ICNI)
- Integrated Electro-Optical Systems (IEOS) (Infrared Search and Track (IRST), Electro-Optical Targeting System (EOTS) etc.)
- Advanced Cockpit / Human Machine Interface

Can be replaced by **Generic** sensors

### Mounts

1x 20mm auto cannon (?)
1x Chaff

### Loadout Options

- 4x AIM-120D, 2x AIM-9X-2 (Internal)
- 4x Gökdoğan (Peregrine), 2x AIM-9X-2 (Internal)
- 4x Gökhan (Skykhan), 2x AIM-9X-2 (Internal)
- 2x SOM-A/B1/B2/C1, 2x AIM-9X-2 (Internal)
- 2x KGK-82/83, 2x AIM-9X-2 (Internal)
- 2x KGK-82/83, 2x AIM-9X-2 (Internal), 4x KGK-82/83 (External, Heavy)
- 4x GBU-10 LGB, 2x AIM-9X-2 (Internal)
- 4x GBU-10 LGB, 2x AIM-9X-2 (Internal), 4x GBU-10 LGB (External, Heavy)
- 2x (Light)/4x (Heavy) HGK INS/GPS (External), 2x AIM-9X-2 (Internal)
- 8x SPEAR-3/TolUn SDB, 2x AIM-9X-2 (Internal)

### Comments

Congratulations on Kaan's first flight. Hope to see more and more countries' 5th generation fighters join the DB.

### Sources

https://en.wikipedia.org/wiki/TAI_TF_Kaan#Design
https://web.archive.org/web/20230514093650/https://www.tusas.com/en/products/new-projects/original-development/tf
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/9db495fe-a538-48d1-9109-1f4834a6a861)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/7e0a2751-a1a3-47dc-8691-fd8733c99b00)

**Comment by LuigiP57** [comment]
#4329 #4330

**Comment by tbrandon517** [comment]
Ukraine looks to be interested in this aircraft 

https://www.airrecognition.com/index.php/news/defense-aviation-news/2024-defense-news-aviation/february/9561-ukraine-to-develop-and-purchase-turkish-kaan-fifth-generation-stealth-fighter-jet.html?fbclid=IwAR1BwO6upfMn5DgoIE_RsmncjeF3aYO4kkXMJyEC2x4DekCdGI85T3fWpIE

**Comment by Jkryos** [comment]
Added DB3K 505.
