### ISSUE TITLE
Türkiye, Gökdoğan (Peregrine) BVRAAM, AIM-120 variant

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4329]
### DB Selector

DB3K

### DBID to Copy

weapon 897

### Hypothetical

Yes

### Name

Gökdoğan

### Country

Türkiye

### Service

Air Force

### Sources

https://en.wikipedia.org/wiki/G%C3%96KTU%C4%9E
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/8ff8dd94-6f76-4aa3-8412-0d79c72d3f0f)

**Comment by tbrandon517** [comment]
#223 related

**Comment by Jkryos** [comment]
Added DB3K 505.
