### ISSUE TITLE
RCAF CC-108 De Havilland Caribou x9

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#433]
### DB Selector

CWDB

### DBID to Copy

3272 CWDB

### Hypothetical

No

### Name

CC-108 Caribou

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1960-71

### Sensors

N/A

### Mounts

N/A

### Loadout Options

N/A

### Other Changes

N/A

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://va3kgb.com/CdnMilAC/search_result_acname.php
https://en.wikipedia.org/wiki/List_of_aircraft_of_Canada%27s_air_forces
https://en.wikipedia.org/wiki/De_Havilland_Canada_DHC-4_Caribou
http://www.rwrwalker.ca/RCAF_5300_5349.html
https://www.silverhawkauthor.com/post/canadian-warplanes-5-de-havilland-cc-108-caribou

![60fadfb6f5b058526225174a_Caribou-5320--UN--Fred-Paradie-2](https://user-images.githubusercontent.com/99632305/156238330-e0160811-7164-4577-a556-4f7f66f01dce.jpg)

**Comment by Jkryos** [comment]
Added CWDB 494.
