### ISSUE TITLE
Türkiye, Gökhan (Skykhan) LRAAM, Ramjet BVRAAM like Meteor

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4330]
### DB Selector

DB3K

### DBID to Copy

weapon 961

### Hypothetical

Yes

### Name

Gökhan [Skykhan]

### Country

Türkiye

### Service

Air Force

### Sources

https://en.wikipedia.org/wiki/G%C3%96KTU%C4%9E
https://www.turkishdefencenews.com/turkey-carries-out-ramjet-missile-studies/

**Comment by tbrandon517** [comment]
#223 related

**Comment by Jkryos** [comment]
Added DB3K 505.
