### ISSUE TITLE
Chinese amphibious vehicles not actually amphibious

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4331]
### DB Selector

DB3K

### Affected DBID(s)

235, 236, 237, 240, 241, 243, 247, 248, 249, 250, 251,317, 318, 320

### Description of Problem

As of DB3K ver. 504, the following vehicles are missing movement values on water when they are clearly supposed to be amphibious.
ZBD03, ZBD04, ZBD05, ZBD08, ZTD05, ZBL08, ZTL11, ZSL92, ZSL92A, ZSL92B, ZBD86, ZBD86A, PLZ07B, PLL05

### Recommended Fix

Vehicles based off the ZBD05 chassis (ZBD05, ZTD05, PLZ07B) are designed for high speed open water amphibious operation (ie beach landings) with a max speed of 16knots.

Vehicles based off the ZBL08 Chassis (ZBL08, ZTL11) 
are capable of 5knots and can also operate in open waters given that they are in service with the PLANMC  

the ZBD04 and ZBD08 can reach 10knots and 7knots respectively but is likely only used for fording operations as it is a PLAGF exclusive item

All other vehicles such as the ZBD03, ZBD86, ZBD86A, ZSL92, ZSL92A, ZSL92B, PLL05 have very limited fording capability at around 4knots

Though Im not sure if its modelled in the game, Bad sea states should entire prevent any of these vehicles from operating

**Comment by claudejdev** [comment]
The sources seems to be missing.

**Comment by Siegemiester** [comment]
ZBD05, ZTD05
https://www.armyrecognition.com/china_chinese_light_armored_armoured_vehicle_uk/zbd-05_zbd05_zbd2000_amphibious_armoured_infantry_fighting_vehicle_data_sheet_specifications.html

PLZ07B
https://www.militarytoday.com/artillery/plz_07b.htm
*I assumed it has the same performance as the ZBD05 as it is the same hull and is denoted as 'amphibious'

ZBD04
https://weaponsystems.net/system/397-ZBD04

ZDL92/A/B & PLL05 (Based of WZ551 chassis)
https://www.army-technology.com/projects/wz-551-type-9092-wheeled-armoured-personnel-carriers/
https://en.wikipedia.org/wiki/WZ-551

ZBL08, ZTL11
https://weaponsystems.net/system/1199-ZBL08

ZBD03
https://en.wikipedia.org/wiki/ZBD-03

ZBD86, ZBD86A
https://tank-afv.com/coldwar/China/type-86-IFV-wz-501.php

**Comment by Jkryos** [comment]
I think this may be a game bug, the needed information to make them amphibious is present in the DB

**Comment by claudejdev** [comment]
> I think this may be a game bug, the needed information to make them amphibious is present in the DB
@Jkryos 

Could the vehicle's propulsion need additional entries to allow an amphibious movement?

eg. ID 2946 VTA-903T (AAVP-7's)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/91ff1eec-76ec-4574-85b0-e13f933924b6)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/fb807f50-034e-4cc8-8400-81bb62dc083c)


Whereas ID ZBD-05 doesn't seems to have such entries.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/93e1fc4d-6bb3-4902-b22a-496d182daa87)

(DB3K_505)

**Comment by PygmalionOfCyprus** [comment]
Yes, the engines need a -1 alt band like the ACV (Engine 2978).

**Comment by Jkryos** [comment]
Fixed DB3K 509.
