### ISSUE TITLE
Chinese W90 / VSP203, 203mm SPG

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4334]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

W90 / VSP203 203mm Bty

### Facility Type

Arty

### Country

China

### Service

PLAGF, PLASSF

### Sensors

Naked eye
Generic Binoculars 

### Mounts

6 Guns per Battery, Each gun to Carry either
37rnds of 203mm ERFB-HB, 21nm Range
37rnds of 203mm ERFB-BB , 26nm Range

### Comments

This hypothetical artillery system would have been based off the M110A2 Chassis and would likely have the same performance/ammunition capacity as it.

### Sources

https://www.defenseone.com/threats/2023/04/chinas-secretive-quest-heavier-artillery/385709/

https://www.globalsecurity.org/military/world/china/203mm-prc.htm#:~:text=The%20weapon%20can%20fire%20standard,range%20of%20over%2030%20miles.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
