### ISSUE TITLE
J10D Electronic Warfare Variant

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4336]
### DB Selector

DB3K

### Baseline

J10C

### Hypothetical

Yes

### Name

J10D

### Country

China

### Service

PLAAF

### Length (m)

Same as J10C

### Wingspan (m)

Same as J10C

### Height (m)

Same as J10C

### Empty Weight (kg)

Same as J10C

### Maximum Takeoff Weight (MTOW) (kg)

Same as J10C

### Crew

Same as J10C

### Propulsion

1x WS10B

### Service Ceiling (ft)

Same as J10C

### Military/Afterburner Speed (kt)

Same as J10C

### Cruise Speed (kt)

Same as J10C

### Supercruise

Yes

### Ferry Range (nm)

Same as J10C

### Endurance (min)

Same as J10C

### Takeoff / Landing Distance (m)

Same as J10C

### Fuel Capacity (kg)

Same as J10C

### Sensors

Same as J10C

### Mounts

Same as J10C

### Loadout Options

Same as J10C

### Comms/Datalinks

Same as J10C

### Comments

Essentially a carbon copy of the existing J10C but with integral electronic warfare capability (likely late 2010s or better)

### Sources

https://www.twz.com/chinas-j-10-fighter-spotted-in-new-big-spine-configuration

**Comment by HunterDNiu** [comment]
With PLA vocally reliant on the substantial internal fuel of flankers I have serious doubts about the relevancy of this platform.

**Comment by Jkryos** [comment]
Added DB3K 506 as hypothetical unit.
