### ISSUE TITLE
DECM double up

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4337]
### DB Selector

DB3K

### Affected DBID(s)

Any unit with more than 1 DECM

### Description of Problem

Not sure if this is a bug or intentional, but warships or any unit with more than 1 DECM will do multiple dicerolls upon being hit regardless which direction the DECM is orientated. Meaning By default combining with chaff and other defensive dicerolls all ships have a significantly high chance of spoofing even the best missiles.

### Recommended Fix

Remove the secondary DECMs or limit their dicerolls to once per weapons endgame.

**Comment by PygmalionOfCyprus** [comment]
This is not so much a DB issue as it is a sim bug, but good catch. Please post it in the Tech Support forums so that the sim devs can take a look at it.
