### ISSUE TITLE
CH7 Stealth drone

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4339]
### DB Selector

DB3K

### Baseline

3168

### Hypothetical

No

### Name

CH7

### Country

China

### Service

PLAAF

### In Commission

2022

### Number in Service

Few

### Length (m)

10

### Wingspan (m)

26

### Height (m)

3.2

### Empty Weight (kg)

6500

### Maximum Takeoff Weight (MTOW) (kg)

10000

### Payload Weight (kg)

2000

### Crew

0

### Propulsion

1 x Turbofan engine of unknown make

### Service Ceiling (ft)

49200

### Military/Afterburner Speed (kt)

500

### Cruise Speed (kt)

400 

### Supercruise

No

### Ferry Range (nm)

1890

### Sensors

Similar to GJ11 but no sources on specifics

### Mounts

2x Internal Weapons bays 

### Loadout Options

1x OECM Package (internal, early 2020s)
4x LS-6-500
4x LS-6-600 ER
8x FT7
8x LS-6-50
Unarmed Recon
2x TL500 (Chinese JSOW equivalent)
2x KD88

### Comms/Datalinks

Same as GJ11

### Comments

The primary role of this drone would be reconaissance and standoff ground/naval strike. but Source 2 suggest this drone is possibly able to carry OECM packages internally as well

Physically this drone looks very similar to the X47B with only slightly wider dimensions (thus slower speed but longer range)

Its stealth characteristics are likely to be on par with the best western flying wing UCAVs given its extremely recent manufacture and its similar physical features

### Sources

https://www.militarydrones.org.cn/ch-7-rainbow-stealth-uav-drone-china-price-manufacturer-p00097p1.html

https://www.defenceconnect.com.au/air/13533-ch-7-stealth-uav-ready-by-years-end-says-chinese-state-media

https://www.sae.org/news/2018/11/the-ch-7-china%E2%80%99s-latest-unmanned-combat-air-vehicle

**Comment by PygmalionOfCyprus** [comment]
\>Its stealth characteristics are likely to be on par with the best western flying wing UCAVs given its extremely recent manufacture and its similar physical features

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/4364655b-c7c7-4ac5-9e23-0921b51d2204)

Caaaaaareful with those assumptions. There's more to stealth than looks. Chinese VLO tech, while much better than the Russians (lol) is still known to be behind Western equivalents, especially re: RAM. Shaping is probably good, though.

I will probably give this the same sig as the X-47 anyway, but just something to keep in mind.

**Comment by PygmalionOfCyprus** [comment]
I'm gonna hold off on this until we get proof that this is actually intended for deployment w/ the PLA or it gets some export customers. CASC makes about a billion CH-X drones and only a few of them are actually adopted domestically or successful on the market.

**Comment by Siegemiester** [comment]
I think its due time to revive this now that its pretty much confirmed that this system will enter service.
https://www.globaltimes.cn/page/202411/1322854.shtml
https://www.twz.com/air/chinas-stealth-ch-7-long-endurance-drone-emerges

Also note that the revised design is 26m wide instead of 22, has a 15km service ceiling, is lighter and is marginally faster

**Comment by tbrandon517** [comment]
Additional, looks to be in flight testing but does not necessarily mean it's selected for service.

https://www.twz.com/air/chinas-stealth-ch-7-long-endurance-drone-emerges?fbclid=IwY2xjawGkJHVleHRuA2FlbQIxMQABHfICkDRL1qLTSt22YGhwtay9-FmVEb4rb66hSYcpyQeKw_KD1Di0aaKtpQ_aem_pqbdv1mIDAJnItBHyAd7pA

**Comment by Siegemiester** [comment]
> Additional, looks to be in flight testing but does not necessarily mean it's selected for service.
> 
> https://www.twz.com/air/chinas-stealth-ch-7-long-endurance-drone-emerges?fbclid=IwY2xjawGkJHVleHRuA2FlbQIxMQABHfICkDRL1qLTSt22YGhwtay9-FmVEb4rb66hSYcpyQeKw_KD1Di0aaKtpQ_aem_pqbdv1mIDAJnItBHyAd7pA

Its highly unlikely something this advanced and specialised would be marketed to foreign buyers and Not used by the PLA

**Comment by OrcaOrcaSD** [comment]
CH-7 is now flying.


https://www.twz.com/air/chinas-stealthy-ch-7-long-endurance-drone-is-now-flying
