### ISSUE TITLE
RCAF CC-115 DeHavilland Buffalo x15

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#434]
### DB Selector

CWDB

### DBID to Copy

4097 CWDB

### Hypothetical

No

### Name

CC-115 Buffalo

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1967-1975

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://www.silverhawkauthor.com/post/canadian-warplanes-5-de-havilland-cc-115-buffalo
http://www.rwrwalker.ca/CAF_Buffalso_detailed.htm
https://en.wikipedia.org/wiki/List_of_aircraft_of_Canada%27s_air_forces
https://en.wikipedia.org/wiki/De_Havilland_Canada_DHC-5_Buffalo
https://va3kgb.com/CdnMilAC/search_result_acname.php

![60fb16cad522a351f52c1c95_de-Havilland-CC-115-Bufffalo](https://user-images.githubusercontent.com/99632305/156238680-b408a44a-5969-4e07-9ece-436b4fd1bb54.jpg)

**Comment by Jkryos** [comment]
Added CWDB 494.
