### ISSUE TITLE
China, PLAAF, PL-15C (provisional) BVRAAM, PL-15 with folding fin & better performance

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4341]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

PL-15C [CH-AA-10 Mod-1?]

### Length (m)

same as PL-15

### Width/Span (m)

same as PL-15

### Diameter (m)

same as PL-15

### Weight (kg)

250

### Range (nm)

2-135 ( )

### Warhead

same as PL-15

### Targets

Aircraft, Helicopter, Missile

### Sensors

1x Active Radar Seeker [Early 2020s, AESA] (based on sensor 5790)

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer, Lock-On After Launch (LOAL) - CEC-Capable, Weapon - INS w/ GNSS Navigation, Uses BeiDou/COMPASS, Level Cruise Flight

### Comments

A hypo version of folding fin PL-15 which J-20 #4335  & J-35 (aircraft 2463, 5013, 5014, 2917, 4454) & JH-XX can carry up to 6 (JH-XX is 16+2 estimate) in their weapons bay.
Take an average value of the wide-spread 200-300km estimate as its range, similar to the AMRAAM series upgrade.
Also need a 150nm PL-15 datalink.

Potential Loadouts:
-6x PL-15C, 2x PL-10 (Internal) (J-20B/S)
-6x PL-15C (Internal) (FC-31/J-35)

### Sources

https://twitter.com/RickJoe_PLA/status/1631479966067204103
(Image 3)
https://www.reddit.com/r/LessCredibleDefence/comments/11gp43m/chinese_pl15_aam_confirmed_to_have_a_range_over/

**Comment by LuigiP57** [comment]
#4342

**Comment by Test229** [comment]
I don't see a range increase being mentioned in the refs? It's "folding fin" not a shortened fin.

**Comment by LuigiP57** [comment]
> I don't see a range increase being mentioned in the refs? It's "folding fin" not a shortened fin.

#4046 
My thoughts are based on some of the things I'm trying to convey in this ticket. The AIM-260 has a range of over 200km, so it gets a DB of 120 nautical miles (although I think this may be some sort of unit conversion error). The PL-15 is also believed (and even confirmed by the Chinese military industry) to have a range of "at least" 200km (the common estimate is 200-300km). So why can't we do this in a "highly probable" Hypo category weapon without changing the performance of the PL-15 in the current database?

**Comment by Test229** [comment]
> > I don't see a range increase being mentioned in the refs? It's "folding fin" not a shortened fin.
> 
> #4046 
> My thoughts are based on some of the things I'm trying to convey in this ticket. The AIM-260 has a range of over 200km, so it gets a DB of 120 nautical miles (although I think this may be some sort of unit conversion error). The PL-15 is also believed (and even confirmed by the Chinese military industry) to have a range of "at least" 200km (the common estimate is 200-300km). So why can't we do this in a "highly probable" Hypo category weapon without changing the performance of the PL-15 in the current database?

Hmm, so I think the AIM-260 is designed to counter the PL-15 so it's fine to take a guess that it has a longer range? For the folding fin one I think it does not make sense to make its range different from the original now. I think giving the PL-15 a longer range is not unreasonable, it's just I think it's better to make modifications on the original one. 

Anyway PL-15 already has a far longer range than the JATM in the game. I know the actual range described in the db is 108 vs 120, but I feel that the motor burn time and the speed are the actual things that define range in this game. To me 85sec * 2900kt vs 59sec * 2650kt means it's far more superior.

**Comment by LuigiP57** [comment]
> To me 85sec * 2900kt vs 59sec * 2650kt means it's far more superior.

I found the issue and brought up ticket, however, DB manager shut it down because the issue seemed to have been raised and resolved on the CMO forum as tech support (?). I think, at any rate, the dev team seems to have noticed the problem and is trying to make improvements. Therefore, the maximum range is still important in the future.

**Comment by LuigiP57** [comment]
>  I think giving the PL-15 a longer range is not unreasonable, it's just I think it's better to make modifications on the original one.

If this ticket fails, I will propose another ticket about this.

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Using the range of the PL-15 for now. It's probably true that the PL-15 can go further than 108nmi (though who knows under what conditions) but in general when I get one of those "at least" numbers I use it as the base until I get specific evidence of a higher cap, just because of how Command handles kinematics. There's also a delicate dance happening between the JATM range and the PL-15 as mentioned above.

Not opposed to a discussion on bringing up the PL-15 range, but rec. separate ticket with evidence so we can discuss it there. Wanna give you your 6x internals first and not have it get bogged down in that convo.
