### ISSUE TITLE
Add Latvian and Canadian RBS-70NG Manpads 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4346]
### DB Selector

DB3K

### DBID to Copy

Facility 3913

### Hypothetical

No

### Name

SAM Plt (RBS 70 NG MANPADS x 3)

### Country

Latvia, Canada

### Service

Air Force

### In Commission

2024

### Sensors

same

### Mounts

same

### Loadout Options

same

### Other Changes

Looks like Latvia got Giraffe 1X Radar with it.

### Sources

**Latvia**
https://twitter.com/RyszardJonski/status/1760563246635819390
https://www.saab.com/newsroom/press-releases/2022/saab-receives-orders-for-short-range-air-defence-systems-from-latvia
https://www.shephardmedia.com/news/landwarfareintl/canada-joins-the-rbs-70-club/
**Canada**
https://www.canada.ca/en/department-national-defence/news/2024/02/canada-acquiring-air-defence-and-anti-drone-capabilities-for-canadian-armed-forces-members-deployed-with-nato-in-latvia.html
https://www.saab.com/newsroom/press-releases/2024/saab-receives-order-for-rbs-70-ng-from-canada

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
