### ISSUE TITLE
Addition: PAC-3 VLS loadouts 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4348]
Weapons 1150, 3207: Add AEGIS weapon DL 

- 4x, 32x and 64x PAC-3 MSE, 2s ROF. 
This is the baseline expected capability already demonstrated. 

- 8x, 64x and 128 (2x per cell) PAC-3 MSE, 2s ROF. 
Potential dual pack MSE. 

- 8x, 64x and 128 (2x per cell) PAC-3 ERINT, 2s ROF. 
Alternative ERINT VLS capability, dual pack. 

- 16x, 128x and 256 (4x per cell) PAC-3 ERINT, 2s ROF. 
Alternative potential ERINT VLS capability, quad pack. 

1. https://www.lockheedmartin.com/en-us/news/features/2024/enabling-a-growing-unmatched-iamd-capability-at-sea.html
2. https://x.com/ThrustWR/status/1748438066958623152
3. https://news.usni.org/2024/05/21/lockheed-test-fires-army-patriot-missile-using-aegis-combat-system

**Comment by tbrandon517** [comment]
Additional 

https://www.twz.com/patriot-missiles-paired-with-naval-vertical-launchers-pitched-by-lockheed

https://www.twz.com/sea/successful-patriot-interceptor-test-from-naval-vertical-launcher-is-a-big-deal?fbclid=IwZXh0bgNhZW0CMTEAAR3mvolVy4ynDAsuLwJ5a56q5u_vENfRhZZFVjYhigoJsdSJst9vVGkU-zE_aem_Ad-ArT3vpkEyl7RcPl6cNB6sJvgE3vloi5ECrZ81Ro3GVGYltf3tq8Ni1_kasPOKIBse5LmWWElcSy8tIpx_PDtX

https://www.defensenews.com/land/2024/01/18/lockheed-to-test-patriot-and-aegis-integration-in-live-fire-test/?fbclid=IwZXh0bgNhZW0CMTEAAR2nYsJKsTJWqf2L2ChcFNHDvu92sA98i8zCk9gvS79B9zeFE44rpPvmgwk_aem_Ad_UhlHWjL7arSCz31iopfX6Tp0R9LJZVq5fpllawI3jYBQ06JDmJDjTYIqNPSeP1A9QGCyGWGCJtXCuKnvFgwmO

**Comment by HunterDNiu** [comment]
Closed in favor #4885
