### ISSUE TITLE
United States, KC-135 Stratotankers

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4349]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft :apple: 31416

### Summary of Changes

- [x] 1852 KC-135A Stratotanker
- [x] 1320 KC-135Q Stratotanker (SR-71 JP-7)

#### Loadout, Range 

- Tanker (ID 8828): _4575_ [^ADTG] (or 2086 [^DTIC], 2400[^DTIC], 2932 [^HOP], Each with different transfer fuel figure. Also Boom Drogue Adapter (BDA) induce reduced range.) (was 3900)
- Ferry (ID 8827): _9150_ [^ADTG] (or 9572 [^ACM], 9726[^ACME])  (was 7800)

(also has a Cargo loadout. Seldom used.)

#### Comms
- add: 33	AN/ARC-164 Have Quick[^HOP] (Only to upper UHF 1 antenna. so probably tanker to tanker, same as the mentioned in The Book, p.94)

#### Engine

|ID|Name|
|--|----|
|1361|4x J57-P-59W|
|2414|4x J57-P-59W|
- ThrustPerEngineMilitary: 5080 [^HOP] (5902 is the Water injection rating. Only at T/O)[^FIMA][^RX] 
- SFCMilitary: 0.95[^RX] (was 0.775)

> Re KC-135Q Stratotanker can have full JP-4 or 48990 kg JP-4 and 41730 kg JP-7. Such granularity is not featured in this DB, afaik)

----
- [x] 159 KC-135E Stratotanker
#### Loadout, Range 

- Tanker (NEW, copy  8828): _5000_ [^ADTG] (2086 [^DTIC], 2400[^DTIC], 2932 [^HOP], Each with different transfer fuel figure. Also Boom Drogue Adapter (BDA) induce reduced range.) (was 3900)
- Ferry (NEW, copy  ID 8827): _10000_ [^ADTG] (9572 [^ACM], 9726[^ACME])  (was 7800)

(also has a Cargo loadout. Seldom used.)

#### Comms
- add: 33	AN/ARC-164 Have Quick[^HOP] (Only to upper UHF 1 antenna. so probably tanker to tanker, same as the mentioned in The Book, p.94)

#### Engine

|ID|Name|
|--|----|
|1570|4x TF33-PW-102|
|2412|4x TF33-PW-102|
- ThrustPerEngineMilitary: 7280 [^HOP] (@ Maximum Continuous. T/O is 8165[^RX]) (was 8219)

### Sources

[^FIMA]: [Boeing C-135 Series - Archived 6/2005  - Military Aircraft Forecast (PDF)](https://www.forecastinternational.com/archive/disp_pdf.cfm?DACH_RECNO=248)
[^ACME]: [KC-135E Stratotanker – Air Mobility Command Museum](https://amcmuseum.org/at-the-museum/aircraft/kc-135e-stratotanker/)
[^AMC]:[KC-135 Stratotanker > Air Mobility Command > Display](https://www.amc.af.mil/About-Us/Fact-Sheets/Display/Article/977523/kc-135-stratotanker/)
[^DTIC]: [Air Force Tankers for the Carrier Battle Group - DTIC](https://apps.dtic.mil/sti/citations/ADA253112)
[^HOP]: Hopkins, Robert. Boeing Kc-135 Stratotanker: More Than Just a Tanker. (1998)
[^JAWA]: Jane's All the World's Aircraft: In Service 2021-2022, p.185-187
[^ADTG]: Larry Bond, Chris Carlson, & Peter Grining. America’s Aircraft - U.S Military Aircraft 1955 - 2020, Jan. 2024
[^RX]: Roux, Élodie. Turbofan and Turbojet Engines: Database Handbook, Les Editions Elodie Roux, 2007

@KushanGaming

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
