### ISSUE TITLE
RCAF CC-115 De Havilland Buffalo (SAR)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#435]
### DB Selector

CWDB

### DBID to Copy

4097 CWDB

### Hypothetical

No

### Name

CC-115 Buffalo

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1975-2022

### Sensors

- 1x Generic Weather Radar

### Mounts

N/A

### Loadout Options

- Add SAR Loadout
- Remove Troops x40 Loadout

### Other Changes

Service life for the SAR platform is 1975-2022, please copy to DB3k

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://www.silverhawkauthor.com/post/canadian-warplanes-5-de-havilland-cc-115-buffalo
http://www.rwrwalker.ca/CAF_Buffalso_detailed.htm
https://en.wikipedia.org/wiki/List_of_aircraft_of_Canada%27s_air_forces
https://en.wikipedia.org/wiki/De_Havilland_Canada_DHC-5_Buffalo
https://va3kgb.com/CdnMilAC/search_result_acname.php
https://rcaf-arc.forces.gc.ca/en/aircraft-current/cc-115-fact-sheet.page
https://www.airmedandrescue.com/latest/long-read/rcaf-bids-goodbye-buffalo-aircraft-welcomes-new-era-c-295w

![cc-115-buffalo-fact-sheet-image](https://user-images.githubusercontent.com/99632305/156239834-5dca7fcf-cb0f-4ec6-9e3b-2f2d23ed04d5.png)

**Comment by Jkryos** [comment]
Added both DB3K and CWDB 494.
