### ISSUE TITLE
Add EO Ball sensors to various Chinese Aircraft

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4350]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5608, 3708,5185,2407

### Summary of Changes

Z-8C 5608
Generic FLIR/TV Camera Chin
PLAAF Y-9 
Generic FLIR/TV Chin
MA-60H
Generic FLIR/TV Chin
Z-8J
Generic FLIR/TV Chin

### Sources

Z-8C
https://twitter.com/foolsball/status/1750534669760643524/photo/1
https://twitter.com/foolsball/status/1746597299998912605
Y-9 PLAAF Transport
https://twitter.com/RFl_Ch/status/1674596474796269568/photo/3
MA-60H
https://www.scramble.nl/military-news/china-coast-guard-ma-60h
https://www.jetphotos.com/photo/11042377
Z-8J ASW
https://vertipedia.vtol.org/aircraft/getAircraft/aircraftID/383
https://www.jetphotos.com/photo/10973336

**Comment by PygmalionOfCyprus** [comment]
Handled 506 as part of ongoing China review.
