### ISSUE TITLE
Add Iranian RC-130H Khofash ESM/SIGINT Aircraft

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4353]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3682

### Hypothetical

No

### Name

RC-130H Khofash

### Country

Iran

### Service

Air Force

### In Commission

1970

### Number in Service

x2, -1

### Sensors

Remove SLAR
Add Generic ESM/ELINT Sensor

### Other Changes

H model was received in 1970. Rockwell seem to have built the ESM/Sigint gear and they received a Boeing 707 sigint plane separately by 1978. IOC likely mid 70's.
There were two at first, but the second was converted back to transport after the Iran-Iraq war. Gear probably went kaput.

### Sources

Recent vid: https://twitter.com/mhmiranusa/status/1762530219301171294
https://twitter.com/Kobaz4/status/1296121770525827073
https://www.airliners.net/index/aircraft-types/Lockheed-C-130-Hercules-L-082-182-282-382-100/Lockheed-RC-130H-Khofash-%28L-382%29/8171/32613
https://www.c-130.net/c-130-units-airforce358.html
https://www.scramble.nl/planning/orbats/iran/islamic-republic-of-iran-air-force

**Comment by FrangibleCover** [comment]
Also very important for Iran-Iraq, apparently the two Khoofash (Variant spellings? For Iran? Surely not!) were their best early warning platforms for approaching Iraqi raids.

**Comment by bostonmyk** [comment]
Probably narrative evidence it was/is SIGINT. Just need to get an antenna high enough to receive.

Mike

**Comment by FrangibleCover** [comment]
Yes, definitely SIGINT.

`...return to operational service its two Lockheed (E)C-130H Khoofash SIGINT-gatherers. These leftovers from Project Ibex
 – run in cooperation with the Central Intelligence Agency (CIA) 
and National Security Agency (NSA) of the USA in the 1970s – 
were equipped with powerful, even if inauspicious COMINT and 
SIGINT systems capable of reading and decrypting Iraqi military 
communications in real time. Henceforth, Khoofashs were expected 
to provide timely warnings of incoming Iraqi air strikes.26`

From Cooper's work on Iraqi Mirages, based on interviews with Iraqi personnel. Precisely what make COMINT _inauspicious_ I don't know.

**Comment by PygmalionOfCyprus** [comment]
>Precisely what make COMINT inauspicious I don't know.

Beware the COMINTs of March. Handled 506.
