### ISSUE TITLE
F-15EX (#4771) LEGION IRST-21 Pod

### ISSUE THREAD

**Issue by dleake14** [PygmalionOfCyprus/cmo-db-requests#4354]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #4771

### Summary of Changes

F-15EX contains Lockheed Martin's AN/ASG-34 Legion Pod (IRST-21) [SENSOR #5800] 

NOTE: DB currently ascribes the F-15EX is utilizing Tiger Eyes Pod

### Sources

Alex Hollings of Sanboxx News
Video dated 2/27/2024
https://youtu.be/JOjrCfdgwqQ?t=735 [Link to timesamp 12:18]

**Comment by PygmalionOfCyprus** [comment]
Handled 506.

**Comment by tksfpj** [comment]
> Handled 506.

I think the request for F-15EX needs to be applied as well
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4312#issue-2136100986
