### ISSUE TITLE
Add M-117 750lb Bomb Loadouts to Israeli F-16I

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4355]
### DB Selector

DB3K

### User(s)

Aircraft 4779

### Weapons Carried

Mimic 4 bomb loadouts
4x M117
2 Pythons
2 Amraams
1 Litening III
1x 300 Fuel tank

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

Different dates but all within 2023-2024 time period. 

https://twitter.com/GuyPlopsky/status/1762718257252098465/photo/1
https://twitter.com/GuyPlopsky/status/1751288333249155555
https://twitter.com/GuyPlopsky/status/1734935370171838789
https://twitter.com/Osinttechnical/status/1713471699897700551

**Comment by bostonmyk** [comment]
Indonesian F-16s as well. https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/3483

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
