### ISSUE TITLE
China, PLAAF/PLANAF, GJ-11 AAW loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4356]
### DB Selector

DB3K

### User(s)

Aircraft 4963 (GJ-11 Armed Model)

### Weapons Carried

- [ ] 4x PL-15 (weapon 3413)

- [ ] 6x PL-15C (No rush, just add it after you finish the PL-15C ticket)

- [ ] 6x PL-10 (weapon 2109)

- [ ] 2x PL-15, 2x PL-10

- Need a 4/6/12 Channel PL-15 DL

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Reliable CCTV sources confirm that the GJ-11 has "independent" air combat capability "like J-20".

### Sources

https://www.globaltimes.cn/page/202210/1277745.shtml

> Not only can it fly high and fast, it can also carry out missions including offensive air superiority seizing and suppressive air defense operations under high threats and in highly contested environments just like the J-20 stealth fighter jet, CCTV said.
This is the first time an official media has revealed that the GJ-11 is capable of seizing air superiority, observers said.

**Comment by LuigiP57** [comment]
#4341

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus It is recommended that this GJ-11 ticket be completed no later than 076 LHD launching (expected this year). 076 ticket #3920

**Comment by PygmalionOfCyprus** [comment]
Are we sure about this? Seems like there's some confusion about what exactly they mean by "air superiority seizing".

>It was widely believed that armed reconnaissance drones, including the GJ-11 [...] are not best suited for air superiority missions, which mainly means air-to-air combat [...] but the air superiority seizing ability the GJ-11 is capable of might not be the same concept, said some military experts reached by the Global Times on Sunday.
>
>Since the stealth aircraft can penetrate deep behind hostile air defense, it can conduct precision strike missions on enemy airfields and bases. In this way, the enemy will have to give up air superiority since they have no aircraft in the air in the first place, a Beijing-based military expert who requested anonymity told the Global Times.

They do note the other possible interpretation of this, namely "drones [serving] as external missile carriers and [firing] air-to-air missiles for the J-20 remotely," but even the Global Times article admits that "it is unknown if the GJ-11’s weapons bays could host air-to-air missiles."

This seems to me like a propagandist getting overexcited in describing capabilities. Even Global Times is skeptical. At best this would be a distinct hypothetical capability right now, but I'm not even convinced that A2A combat is actually being hypothesized for this platform by the powers that be...

**Comment by LuigiP57** [comment]
I must stress that this is **not a Global Times propoganda**, but a quote from the **official report of the CCTV military program**.This claim has also been repeated by other foreign websites.
https://www.defensemirror.com/news/32960/China_Projects_Air_Dominance_Role_for_GJ_11_Stealth_UAV
![image](https://github.com/user-attachments/assets/93bb8082-09ce-464b-bd58-4f4498efef0b)
On the question of whether the size of the weapon bay could carry A2A weapon, we can see from the air show model that this space is enough to accommodate 4 rounds of BVRAAM at most.
https://warriormaven.com/air/gj-11-stealthy-drone-attack-china-weapons
![image](https://github.com/user-attachments/assets/b3fb9ef9-44ca-4818-89c9-e88763541af6)

**Comment by PygmalionOfCyprus** [comment]
I know -- I was actually siding with Global Times on this one. The original CCTV report mentioned "offensive air superiority seizing," as you show. But even the Global Times was skeptical of this claim, citing Chinese military experts who said they more likely mean "conduct[ing] precision strike missions on enemy airfields and bases" than actual air-to-air combat and admitting that they aren't sure whether it can actually carry AAMs. If Global Times of all sources is skeptical of a claim...

I'm aware that the bays can *fit* air-to-air missiles, but whether the aircraft is actually wired to use them properly is a different matter altogether. After all, just look at the F-35 or any new aircraft, which will often have to go years before getting access to certain bombs, missiles, etc. simply because the aircraft must be programmed/configured to use the weapon properly. It's not just a matter of space/hardware.

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus My dear fellow , just take a look at US UCAVs/CCAs that could carry AAMs in this game. In real world, they are not mature either, just like GJ-11, a lot of capabilities and functions are in development. But we can’t deny that they probably could have those capabilities and functions. The only difference is that US said publicly while China didn’t.

**Comment by LuigiP57** [comment]
How about this: I propose a compromise solution of creating a new entry (can be a hypothetical) based on the current GJ-11 UCAV as a variant that can perform AAW? If this sounds acceptable enough.

**Comment by PygmalionOfCyprus** [comment]
Yes, I think that's very fair. After all, this is what the hypothetical entries are for. 🙂 

(For the record, I know I've been debating with you a fair bit recently -- please don't misunderstand this as hostility. China is just very opaque and I think it is useful for us all to question each others' assumptions and try to work out the truth from vague or contradictory statements provided to use from CCP. Such is the life of a China watcher. 😝)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
