### ISSUE TITLE
Chinese DK-9 Air Defence System Update

### ISSUE THREAD

**Issue by BronskyMcCloud** [PygmalionOfCyprus/cmo-db-requests#4358]
### DB Selector

DB3K

### Affected DBID(s)

Facility 638

### Summary of Changes

The most practical way to properly portray this platform is to scratch it and use Facility_1682 - AAA Sec (35mm/90 Type 90 x 2) as a foundation while adding the following to the entry. Different sources give different figures regarding battery composition although photographic evidence points to two missile launchers per system.

- Add either 1x or 2x DK-9 launcher(s) (Mount_854)
- Add a magazine for the DK-9 launcher(s)
- Change name to _SAM Plt (DK-9 [35mm Type 90, PL-9C])_
- Add text to side note: _Type 390, 3x Plt + 1x China Type 706 IBIS pr Bty_
- Introduced in the mid-1990s

Beginning in early 2010, Morocco also received the DK-9 system along with 24 launcher units.

### Sources

https://www.armedconflicts.com/DK-9-t38369
https://far-maroc.forumpro.fr/t3765p105-af902-fcs-35mm-anti-aircraft-gun-air-defense-system

![Type 90 - DK-9 SHORAD](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/9714d38e-cc6d-49c4-9fa4-2f63cbdafa03)
![6cdfe66](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/7b91d9d9-ecda-44d1-8ca3-0187a9981dcd)
![yqOiE9R](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/b6c9d3bb-5ccd-4305-a83b-a554d5da56bd)
![12456_zpsddfd7228](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/7ca837b9-8f65-4883-9294-7fce63568e22)

**Comment by Jkryos** [comment]
Added DB3K 507.
