### ISSUE TITLE
Add Sudanese. Cambondian Libyan, Syrian, Myanmarian, Namibian FN-6 Manpads

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4359]
### DB Selector

DB3K

### DBID to Copy

Facility 2351

### Hypothetical

Yes

### Name

SAM Sec (FN-6 Manpads)

### Country

Sudan

### Service

All their Armies and Rebels

### In Commission

Syria/ISIS: 2013, Sudan 2007, Cambodia 2009, Namibia 2016,  Libya 2019, Myanmar 2009

### Sources

Sudan
https://twitter.com/HammerOfWar5/status/1762909155726184554
https://twitter.com/war_noir/status/1653737564430368775
https://twitter.com/war_noir/status/1728497223561056512
Sipri Line: (50)	FN-6	portable SAM	(2005)	2006	(50)

Syria
https://twitter.com/FreeFemboy6050/status/1636853123288317952
https://twitter.com/smmsyria/status/1061540471632248832
https://twitter.com/CalibreObscura/status/1280983588947836930
https://brown-moses.blogspot.com/2013/02/first-sightings-of-foreign-manpads-in.html
https://brown-moses.blogspot.com/2013/08/a-small-delivery-of-arms-to-damascus.html

Myanmar
https://twitter.com/mthaw_mm/status/1464957348196147202
https://twitter.com/mthaw_mm/status/1474070966565163031
https://twitter.com/Crimson249996/status/1198227002861318145
https://m.facebook.com/210114122377899/photos/a.217657894956855/1223346961054605/?type=3
https://asiatimes.com/2019/11/chinas-mobile-missiles-on-the-loose-in-myanmar/
https://militarymatters.online/defense-news/manpad-proliferation-in-burma-and-mena-is-the-sam-genie-out-of-the-bottle/

Libya
https://twitter.com/Oded121351/status/1195282531534458880
https://twitter.com/Oded121351/status/1123220220087238656

Cambodia
https://defense-studies.blogspot.com/2015/11/china-supplies-cambodia-with-anti.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Royal_Cambodian_Army
Sipri Lines (50)	FN-6	portable SAM	(2008)	2009	(50)	Possibly FN-16 version

Namibia
Sipri Line: Namibia	(50)	FN-6	portable SAM	(2016)	2016-2017	(50)	
https://www.defenceweb.co.za/land/land-land/namibia-operating-fn-6-missiles/?catid=50%3ALand&Itemid=105

General
https://smallarmssurvey.medium.com/the-illicit-possession-and-transfer-of-manpads-a-global-assessment-7e2e75ff5fe2
https://en.wikipedia.org/wiki/FN-6

**Comment by PygmalionOfCyprus** [comment]
Handled 506. Didn't add specifically for Syria, Myanmar, or Libya since they are in rebel hands, but I added a generic "Rebels" entry too.
