### ISSUE TITLE
Add:Miguel Ela Edjodjomo (Zhuk(Grif), Pr1400M) class ships, Equatorial-Guinea Navy 

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#436]
### DB Selector

DB3K

### Baseline

#2529(Ukraine), #2858(Syria) and more

### Hypothetical

No

### Name

Patrol Boat (PB), LP039, Miguel Ela Edjodjomo

### Class

Miguel Ela Edjodjomo (Zhuk(Grif), Pr1400M

### Country

Equatorial-Guinea

### Service

Navy

### In Commission

2000 - present

### Length (m)

24

### Beam (m)

5

### Draft (m)

1.2

### Standard Displacement (t)

36

### Full Displacement (t)

40

### Complement

13

### Primary Propulsion Type

Diesel

### Propulsion

2x M-401BT, 2 shafts

### Flank Speed (kt)

30 (src1), 29 (src2)

### Range (nm) at Speed (kt)

1100 @ 15 (src1), 450 @ 13 (src2)

### Sensors

Furuno I-band (src1)
Lotsiya radar (src2)

### Mounts

1x twin 14.5mm & 1x single 12.7mm (src1)
2x twin - 12.7mm/79 (src2)

### Comments

Transferred from Ukraine. 
Export Rus Pr.1400ME

### Sources

Src3 is generic Zhuk class
1: JFS 2015-2016
2: https://www.navypedia.org/ships/equatorial_guinea/eqgui_cf_miguel_ela_edjodjomo.htm
3: https://en.wikipedia.org/wiki/Zhuk-class_patrol_boat

**Comment by PygmalionOfCyprus** [comment]
Added 494.
