### ISSUE TITLE
Ship C 551 Giuseppe Garibaldi - 2006 out of service  2024

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4360]
### DB Selector

DB3K

### Affected DBID(s)

Ship  #845 C 551 Giuseppe Garibaldi - 2006

### Summary of Changes

Out of service date 1st October 2024. 

### Sources

https://twitter.com/Saturnax1/status/1762870469659603125?t=0MvyHTC5bjaFXnp0S5WxyQ&s=19

**Comment by LuigiP57** [comment]
The immortal legend of the Marina Militare !

**Comment by Jkryos** [comment]
Updated DB3K 506.

**Comment by KLABDB3K** [comment]
https://www.armyrecognition.com/news/navy-news/2025/indonesia-approves-450-million-loan-to-acquire-ex-italian-aircraft-carrier-giuseppe-garibaldi transferred to Indonesia?
