### ISSUE TITLE
Generic Cargo in increments of one and half tons

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4361]
Add the following cargo items, in air droppable and none droppable variants: 

- Generic Cargo (1 ton), Mass = 1, Area = 1, PAX = 0

- Generic Cargo (0.5 ton), Mass = 0.5, Area = 0.5, PAX = 0

- Cargo Personal, Mass = 0, Area = 0, PAX = 1

Currently certain carriers cannot reasonably utilize the existing cargo stocks in game. For example the 9-ton loadout for CMV-22.

**Comment by PygmalionOfCyprus** [comment]
I might be misunderstanding the use case, what do we need this for? The "Cargo as weapons" system is just for calculating loadout ranges, actual cargo is handled through Cargo 2.0 now.

**Comment by FrangibleCover** [comment]
I think the idea might be to add generic representations of 'Stuff' to Cargo 2.0, where you don't want any of the specific platforms and don't need the complexity of the pallet system (which I still need to get my head around). I think this would mostly be useful for bulk goods in supply type tasks, get a point per tonne of Generic Stuff delivered to the beachhead/carrier/disaster zone and don't worry about whether it's bullets, beans or bandages.

**Comment by PygmalionOfCyprus** [comment]
Aha, I get it. I was thinking of the weapon entries we use as placeholders in loadouts, you were talking about the mounts for loading. Handled 506.
