### ISSUE TITLE
Add PLAAF H-6J Bomber

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4362]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4816

### Hypothetical

No

### Name

H-6J Badger

### Country

China

### Service

PLAAF

### In Commission

2023

### Number in Service

Few

### Other Changes

Few transferred from PLAN to PLAAF. 

### Sources

https://twitter.com/RupprechtDeino/status/1642503149549125633
https://twitter.com/RupprechtDeino/status/1671923208306540550
https://twitter.com/RupprechtDeino/status/1745705096585879762

**Comment by PygmalionOfCyprus** [comment]
Whole H-6 family was ripped out and rebuilt for 506.
