### ISSUE TITLE
Add Syrian JYL-1 Radar 2009

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4363]
### DB Selector

DB3K

### DBID to Copy

Facility 610

### Hypothetical

No

### Name

Radar (China JYL-1)

### Country

Syria

### Service

Air Force

### In Commission

2009

### Sources

https://twitter.com/Harry_Boone/status/1212027708617691136
https://twitter.com/IiiTango/status/1213442873062023169
https://geimint.blogspot.com/2012/07/i-special-report-chinese-radars-in.html
https://en.wikipedia.org/wiki/Syrian_Air_Defense_Force

Sipri Arms DB Line: (1)	JYL-1	air search radar	(2008)	2009	(1)

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
