### ISSUE TITLE
Add Tanzanian SA-6a SAM 1979

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4364]
### DB Selector

DB3K

### DBID to Copy

Facility 2655

### Hypothetical

No

### Name

SAM Bn (SA-6a Gainful [2K12E Kvadrat])

### Country

Tanzania

### Service

Army

### In Commission

1979

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP81T00034R000100580001-3.pdf

Still in use today
https://twitter.com/HammerOfWar5/status/1587507622319575040
https://twitter.com/africaken1/status/1592148706882891777
https://twitter.com/HammerOfWar5/status/1759281389680177272
https://twitter.com/DefenseNigeria/status/1497452986288717824
https://twitter.com/africaken1/status/1193086112782270464
Sipri Lines
(200)	3M9	SAM	(1978)	1979	(200)	
(3)	Kvadrat	SAM system	(1978)	1979	(3)	
(3)	P-12	air search radar	(1978)	1979	(3)	For use with Kvadrat (SA-6) and probably S-125 (SA-3) SAM systems
     		(3)	PRV-9	height-finding radar	(1978)	1979	(3)	For use with Kvadrat (SA-6)

**Comment by bostonmyk** [comment]
Add P-12 Spoonrest A as well. Copy Facility 1318

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
