### ISSUE TITLE
Add Tanzanian SA-3

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4365]
### DB Selector

DB3K

### DBID to Copy

Facility 3616

### Hypothetical

No

### Name

SAM Bn (SA-3a Goa [S-125 Neva])

### Country

tanzania

### Service

Airforce 

### In Commission

1976

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP78T05162A000400010133-0.pdf
https://www.cia.gov/readingroom/docs/CIA-RDP81T00034R000100580001-3.pdf
https://twitter.com/DefenseNigeria/status/1497452986288717824
https://en.wikipedia.org/wiki/Air_campaign_of_the_Uganda%E2%80%93Tanzania_War
Sipri Lines
(75)	V-601	SAM	(1977)	1978-1979	(75)
(2)	S-125 Pechora	SAM system	(1977)	1978-1979	(2)

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
