### ISSUE TITLE
Add Tanzania SA-7B MANPADS 1977

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4366]
### DB Selector

DB3K

### DBID to Copy

Facility 2657

### Hypothetical

No

### Name

SAM Sec [9K32M Stela-2M] MANPADS x 3

### Country

Tanzania

### Service

Army

### In Commission

1978

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP81T00034R000100580001-3.pdf
https://twitter.com/HammerOfWar5/status/1588958848156827648
https://en.wikipedia.org/wiki/Air_campaign_of_the_Uganda%E2%80%93Tanzania_War

Sipri Line
(200)	Strela-2	portable SAM	(1977)	1977-1978	(200)

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
