### ISSUE TITLE
Add Tanzanian SA-16 Manpad 1996

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4367]
### DB Selector

DB3K

### DBID to Copy

Facility 3886

### Hypothetical

No

### Name

SAM Sec (SA-16 Gimlet [9K310 Igla-1)

### Country

Tanzania

### Service

Army

### In Commission

1996

### Sources

https://twitter.com/africaken1/status/1585546947389263872
https://twitter.com/TimZitter/status/1529924938873786369
Sipri Line
R: Tanzania	(50)	Igla-1	portable SAM	(1995)	1996	(50)

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
