### ISSUE TITLE
Add  Tanzanian and Sudanese FB-6A 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4368]
### DB Selector

DB3K

### DBID to Copy

Facility 2351

### Hypothetical

Yes

### Name

SAM Sec (FB-6A [FN-6A])

### Country

Tanzania, Sudan

### Service

Tanzanian Army, Sudanese Army

### In Commission

Tanzania: 2013 Sudan: 2016

### Other Changes

FB-6A is a Chinese Humvee (Shenyang SFQ2040) with 2 quads of FN-6A Missiles. There appears to be a truck variant (Shaanxi SX2190) that Sudan uses. No evidence of use in the PLA yet. Small  <12km surveillance radar

### Sources

PLA
https://www.ausairpower.net/APA-PLA-Div-ADS.html#mozTocId304546

Tanzania
https://worldmilitaryintel.blogspot.com/2013/05/blog-post_6447.html
Sipri Lines
(1)	FB-6	mobile SAM system	(2012)	2013	(1)	
(50)	FN-6	portable SAM	(2012)	2013	(50)	For FB-6 SAM system

Sudan
http://www.cndefense.com/admws/FB-6A.html
https://twitter.com/HammerOfWar5/status/1425514194443509762
Sipri Lines
(2)	FB-6	mobile SAM system	(2015)	2016	(2)	
(100)	FN-6	portable SAM	(2015)	2016	(100)

**Comment by Jkryos** [comment]
Added DB3K 506.
