### ISSUE TITLE
China, PLAN, FM-3000N Quad pack SAM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4369]
### DB Selector

DB3K

### Baseline

weapon 3138

### Hypothetical

No

### Name

FM-3000N

### Length (m)

3.66

### Width/Span (m)

1

### Diameter (m)

0.25

### Weight (kg)

280

### Range (nm)

1-25

### Warhead

35kg frag

### Targets

Aircraft, Helicopter, Missile

### CEP (m)

1

### Sensors

1x Active Radar Seeker (Late 2010s)

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer, Lock-On After Launch (LOAL), Level Cruise Flight

### Comments

Rumors of a Quad Pack SAM for PLAN have been circulating for a long time, and I think it's possible to add a SAM based on that to PLAN in the game. Although FM-3000N (Naval version of FM-3000, lower the minimum intercepting altitude to tackle sea-skimmer) is considered to be a failed bid, we do not know what the officially used product is, so it's fine to name it FM-3000N as a placeholder.

Due to conservative estimates, I recommend that the platform for using this weapon be a PLAN ship with GJB-UVLS (the HT-1E VLS is based on it) after 2020s. 

Here is the DBIDs: **Ship 2834 3883 3586** and the new **Type 052DL Batch IV**

Need a DL for it and platforms.

### Sources

https://en.wikipedia.org/wiki/HQ-11
https://www.globalsecurity.org/military/world/china/fm-3000.htm
http://www.mdc.idv.tw/mdc/navy/china/china-sam.htm

> Generally speaking, after the PLA's weapons system development projects are competed by different manufacturers, the designs of the unselected manufacturers will be displayed in foreign trade models at the Zhuhai Air Show; therefore, FM-3000N may be the PLA Navy's development of a newer generation of medium-sized shipborne air defense The unsuccessful plan of the missile project was displayed as CM model (foreign trade). Therefore, during the same period, the People's Liberation Army Navy should have been equipped with a newer model of medium-sized air defense missiles than the HQ-16. **The 055 guided missile destroyers in service in the 2020s and the additional batches of improved 054A guided missile frigates have signs of being equipped with updated medium-range air defense missiles.**

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/118c1934-8a55-4853-82e9-5a363faf9154)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/19edfe9b-f0cd-4474-a9a8-de1bf513f047)

**Comment by LuigiP57** [comment]
Now I will add the relevant military branch in the ticket title related to China, so that the DB team can quickly classify and select it when reviewing relevant military branch.

Cheers!

**Comment by LuigiP57** [comment]
#4188

**Comment by clerara10** [comment]
https://www.globalsecurity.org/military/world/china/fm-3000.htm
https://www.globalsecurity.org/military/world/china/ht-1e.htm
https://navalpost.com/china-vls-navy/

According to the above data, FM-3000N was unveiled along with HT-1E VLS at the Zhuhai Air Show 2021. The HT-1E VLS was unveiled in quad pack format along with several missiles. Importantly, HT-1E VLS is a VLS for overseas sales. There is no information that the Chinese navy will carry it. Also, there is no information that FM-3000N will be available in the VLS currently used by the Chinese navy. Rather, considering that officials mentioned that there is a difference between HT-1E VLS and existing VLS, FM-3000N is only possible to launch in HT-1E VLS. Also, considering that Chinese warships are currently equipped with HQ-10 SAM, which overlaps its role with FM-3000N, the possibility of the Chinese navy hiring FM-3000N is even lower. Therefore, I don't think it is right to add FM-3000N to Chinese naval ships

**Comment by LuigiP57** [comment]
> There is no information that the Chinese navy will carry it.

You're right, but, I said it in the description above: “we do not know what the officially used product is, so it's fine to name it FM-3000N as a placeholder”. That is, I “borrowed” the existing export products to realize the possible quad-pack-SAM used by PLAN new-generation vessels. The platforms are strictly limited in 2020s or later, UVLS-equipped warships.

> Also, considering that Chinese warships are currently equipped with HQ-10 SAM, which overlaps its role with FM-3000N, the possibility of the Chinese navy hiring FM-3000N is even lower.

The F124 FFG in German navy is equipped with RAM and ESSM simultaneously. The difference between mid-range SAM and CIWS makes it impossible to replace each other completely.

> Rather, considering that officials mentioned that there is a difference between HT-1E VLS and existing VLS, FM-3000N is only possible to launch in HT-1E VLS.

What do you think the HT-1E's technology comes from? I noticed the end of https://navalpost.com/china-vls-navy/ says "According to CASIC, the HT-1E is compatible to both cold- and hot-launched missiles." PLAN's only cold-and-hot VLS is the GJB-UVLS, and it predates the HT-1E. Since HT-1E can implement "4-shells-in-1cell", why not GJB-UVLS?

By the way, do you think this new missile for the HQ-9BE system means the possibility of "2/4-shells-in-1-cell"?
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/36404198-34b0-47c4-af7b-a72955941559)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/382a70c0-2d12-43b1-90e4-8ce72a0c99ea)

**Comment by HunterDNiu** [comment]
MAy also add quad packed HQ-16C?

**Comment by bostonmyk** [comment]
FM-3000 is the export of the HQ-11 correct?

https://twitter.com/someplaosint/status/1723331848003063872

**Comment by LuigiP57** [comment]
> FM-3000 is the export of the HQ-11 correct?
> 
> https://twitter.com/someplaosint/status/1723331848003063872

Maybe, not really sure

**Comment by PygmalionOfCyprus** [comment]
Weapon and land facility added in #4801, holding off on PLAN integration until we get more info on this. I  know that the PLAN is experimenting and I think you are right to assume it will probably be similar to the FM-3000N (if not just that missile in its entirely) but we have no indication that these are actually deployed yet, certainly not enough that i'd want them to be "standard" in the 055s and 052DL. We've seen no launch footage, no press release, nada AFAIK.
