### ISSUE TITLE
RCAF CSR-110 Albatros (SAR) x10

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#437]
### DB Selector

DB3K

### DBID to Copy

3535 CWDB

### Hypothetical

No

### Name

CC-110 Albatross

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

1960-70

### Sources

Canadian Combat and Support Aircraft: A Military Compendium by T.F.J. Leversedge © 2007
https://www.silverhawkauthor.com/post/canadian-warplanes-5-grumman-csr-110-albatross
http://www.rwrwalker.ca/RCAF_Alberts.html
https://en.wikipedia.org/wiki/Grumman_HU-16_Albatross
https://va3kgb.com/CdnMilAC/search_result_acname.php

![images](https://user-images.githubusercontent.com/99632305/156243502-214613b8-fead-43b5-b1f5-863a54c1aab9.jpg)

**Comment by Jkryos** [comment]
The DB selector says DB3K but the in service dates fall entirely within CWDB only. This was added to a very long time ago under DBID 893. Name has been updated to reflect internal Canadian designation.
