### ISSUE TITLE
China, PLAN, Correction on CS Gen of some ships

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4370]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2714 2495 4582 1806 3041 4146 4593

### Summary of Changes

- [ ] Change CS of Ship 2714 2495 4582 [054A Batch 3,4,5] to Gen 6 (built in 2010s & 2020s)
- [x] Change CS of Ship 1806 [051c] to Gen 5 (Built in 2000s, using Russian S-300F)
- [ ] Change CS of Ship 3041 [051B MLU] to Gen 6 (MLU in 2010s)
- [ ] Change CS of Ship 4593 [052B MLU] to Gen 6 (MLU in 2020s)
- [ ] Change CS of Ship 4146 [052C MLU] to Gen 6 (MLU in 2020s)

### Sources

052c undergoing upgrade in Jiangnan Shipyard in 2022:
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/c2d43702-7e95-42c5-9aa2-8d712d242e3c)
And we have enough evidence and reason for other platforms

**Comment by PygmalionOfCyprus** [comment]
Did the MLUs/batch upgrades actually involve such significant changes to their combat systems as to warrant a whole gen shift? I know there were some improvements to electronics, controls, etc. but it's not clear that the fundamental system itself was ripped out and totally improved. 

For some of these entries where we had evidence of these changes the Ergonomics value was upped to indicate these middle-ground improvements.
