### ISSUE TITLE
Service Ceiling  & Top Speed for Divine Eagle drone Incorrect

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4373]
### DB Selector

DB3K

### Affected DBID(s)

4931 Aircraft

### Summary of Changes

Maximum Altitude for Divine Eagle drone increased to 25km (82000ft)
Maximum speed increased to Mach 0.8

### Sources

https://www.globalsecurity.org/military/world/china/shenying.htm
https://en.wikipedia.org/wiki/SYAC_UAV#:~:text=A%20much%20longer%20high%2Daspect,a%20speed%20of%20Mach%200.8.

**Comment by Jkryos** [comment]
Updated DB3K 506.
