### ISSUE TITLE
SHIP #3721 - 828 Al Jubail [Mod. Avante 2200 Combatant] (Saudi Arabia - 2022) -- Its a FFG/FFL not a PG?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4376]
### DB Selector

DB3K

### Affected DBID(s)

#3721 - 828 Al Jubail [Mod. Avante 2200 Combatant] (Saudi Arabia - 2022)

### Summary of Changes

Al Jubail is Currently categorised as PG - It is far more capable than a PG with a respectable spectrum of ASu/AA/ASW weapons plus a helicopter hangar and most listings describe it as a Corvette which would put it in the FFG/FFL category? 
Becomes relevant for LUA scoring and events etc which is why I first noticed the discrepancy. 
For example Skjold is listed as a FFL but is only 250 tonnes and is basically "only" (no insult intended to RNoN) a fast attack missile boat, admittedly a highly capable one on steroids!

### Sources

https://www.bairdmaritime.com/work-boat-world/maritime-security-world/naval/ships-naval/vessel-review-al-jubail-lead-ship-of-new-corvette-class-for-saudi-arabia/

**Comment by Jkryos** [comment]
Updated, DB3K 506.
