### ISSUE TITLE
Canada CE-145C Vigilance (King Air 350ER) x3

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#4377]
### DB Selector

DB3K

### Affected DBID(s)

5656

### Summary of Changes

Canadian designation of CE-145C Vigilance added. Designation of Manned Airborne Intelligence, Surveillance and Reconnaissance (MAISR) to be added. 427 Squadron out of Trenton as part pf Canadian Special Operations Command.

The 2018 FMS [approval announcement] from Washington lists a number of advanced electronics, including L3Harris Wescam MX electro-optical/infrared sensors, L3Harris Vortex video transmission modules, a laser and missile warning system and several pieces of equipment for encrypted communications.

### Sources

https://www.flightglobal.com/fixed-wing/canada-takes-delivery-of-new-king-air-350er-based-surveillance-aircraft/157263.article

https://www.dsca.mil/press-media/major-arms-sales/canada-king-air-350er-isr-aircraft-manned-airborne-intelligence

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
