### ISSUE TITLE
Canada CH-146 Griffin (Griffin Limited Life Extension) 85x 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#4378]
### DB Selector

DB3K

### DBID to Copy

5290

### Hypothetical

No

### Name

CH-146 Griffin (GLLE) [Bell 412EP]

### Country

Canada

### Service

Air Force

### In Commission

2024-

### Number in Service

85x

### Sensors

- Same
- 1x WESCAM16DS(W) (15 noted but not in DB)

### Mounts

- Same

### Loadout Options

- Same
- Add gunship loadout with Dillon Aero M-134D Minigun's (8x heli fitted). 

### Other Changes

- Pratt & Whitney Canada PT6T-9 Twin-Pac engine replaces PT6T-3D
- New integrated sensor systems and cockpit displays were installed on each helicopter. A number of the CH-146’s older avionics systems – such as communications radios and cryptographic equipment; cockpit voice and flight recorders; navigation systems; control display units and automatic flight control systems were replaced.
- As much as possible, “we are trying to use off-the-shelf products that come from the 412 line,” including the latest evolution, the Bell 412EPX (DB3K platform 5290, 5872, 6480)

### Sources

https://verticalmag.com/news/ch-146-griffon-helicopter-life-extension-what-comes-next/
https://www.canada.ca/en/department-national-defence/services/procurement/ch-146-griffon.html
https://apps.forces.gc.ca/en/defence-capabilities-blueprint/project-details.asp?id=1228
https://verticalmag.com/news/bell-awarded-contract-to-sustain-rcaf-ch-146-fleet/
https://www.cbc.ca/news/canada/the-ch-146-griffon-helicopter-1.852924

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
