### ISSUE TITLE
Canada CH-146 Griffon Update 2001

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#4379]
### DB Selector

DB3K

### DBID to Copy

4610 DB3K

### Hypothetical

No

### Name

CH-146 Griffin [Bell 412EP], -- Canada (Army), 2001, 100x

### Country

Canada

### Service

Royal Canadian Air Force

### In Commission

2001-

### Number in Service

100x

### Sensors

- Same
- Add - SPS-65 integrated Radar and Laser Warning Receiver (RLWR)

### Mounts

- Same
- Add M134D Minigun in gunship loadout

### Loadout Options

- Same
- Add gunship loadout with 2x M134D Minigun

### Sources

https://en.globes.co.il/en/article-498393#!
https://www.airhistory.net/photo/484783/146458

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
