### ISSUE TITLE
RCAF CP-121 Tracker 1956-59 x42

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#438]
### DB Selector

CWDB

### Affected DBID(s)

3066 CWDB

### Summary of Changes

I believe this record should be CS2F-1 instead of CS2F-2, please see below source. It is also missing a searchlight, please add #406 Generic Searchlight. If accepted could you also create a COD version or loadout as mentioned:

CS2F-1

Initial production run was based on the Grumman S2F-1 aircraft design. Fourty-two were built by de Havilland Canada serialled 1502 to 1543 (DH-01 to DH-42). According to both RCN and de Havilland histories, the first CS2F-1 (#1502) was taken on strength on 12 October 1956 and the last CS2F-1 (#1543) taken on strength 17 July 1958.

In 1960, seventeen active-duty CS2F-1's were transferred to the Royal Netherlands Navy.  In 1964, a pair of CS2F-1's  (s/n 1534 and 1540)  were stripped of armament and ASW electronics to reduce weight  and converted to transports used for Carrier Onboard Delivery (COD). These conversions allowed mail and staff to be transported to and from HMCS BONAVENTURE and facilitated the movement of ship's company ashore for compassionate reasons. The COD aircraft included additional seats which allowed it to carry a crew of two and six passengers.

### Sources

http://jproc.ca/rrp/rrp3/tracker.html
https://www.yumpu.com/en/document/view/5100903/grumman-cs2f-cp-121-tracker-royal-canadian-navy-pdf
http://jproc.ca/rrp/rrp3/tracker_equipment_details.html

![60fadc650685611647a8d16c_B-indicates-this-is-an-881-ac-circa--957-58--880--A--didnt-go-to-sea-in-BV-until-Jan-1960-](https://user-images.githubusercontent.com/99632305/156256713-eb1c5e40-17e0-484c-82bd-c7b196b95e13.jpg)

**Comment by Jkryos** [comment]
Added CWDB 497.
