### ISSUE TITLE
Updated range to the The H/LJQ-364 aka Type 364  radar (Sensor_3020)

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#4380]
### DB Selector

DB3K

### Affected DBID(s)

Sensor_3020

### Summary of Changes

The database has the Type 363 radar as having a 70nm range.  However, the following sources give it a shorter range: 
Radar Tutorial gives the radar an instrumented range of 40nm: https://www.radartutorial.eu/19.kartei/07.naval2/karte028.en.html
Wikipedia, citing an advertising brochure, provides a range of 75 km v. a 2 meter square tgt.  _See_ https://en.wikipedia.org/wiki/Type_364_radar **citing** https://www.eo-irsystems.com/sale-7838637-cpc-low-airspace-target-detection-and-surveillance-radar-system-for-fire-control-system.html
Friedman, The Naval Institute Guide to World Naval Weapons Systems (5th ed) 2005-06, pg. 219 claims 54 nm.

Based on the age of the Friedman source, and the authoritative nature of https://www.eo-irsystems.com/sale-7838637-cpc-low-airspace-target-detection-and-surveillance-radar-system-for-fire-control-system.html I would argue that the system should be reduced to a 40 nm range.  This is also consistent with its use as a FC radar for short-range systems.

### Sources

 https://www.radartutorial.eu/19.kartei/07.naval2/karte028.en.html
 https://www.eo-irsystems.com/sale-7838637-cpc-low-airspace-target-detection-and-surveillance-radar-system-for-fire-control-system.html
 https://en.wikipedia.org/wiki/Type_364_radar
 Friedman, The Naval Institute Guide to World Naval Weapons Systems (5th ed) 2005-06, pg. 219

**Comment by CV60LCC19** [comment]
Edit my first line to read "The database has the Type 364 radar as having a 70nm range."

**Comment by Jkryos** [comment]
Updated DB3K 506.
