### ISSUE TITLE
Update numbers of RCAF CC-330 Husky

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4381]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #5181

### Summary of Changes

9 total to be recv'd. Currently 2 + 7. 1x specifically for VIP/strategic transport.  4 new a/c and 5 used. 3 more used a/c by summer 2024, 5x new by 2025.

### Sources

https://en.wikipedia.org/wiki/Airbus_CC-330_Husky
https://www.ctvnews.ca/politics/ottawa-buying-nine-airbus-planes-to-replace-polaris-fleet-including-pm-s-plane-1.6493506
https://globalnews.ca/news/10345491/feds-announce-850m-upgrades-at-cfb-trenton-new-fleet/
https://www.avweb.com/aviation-news/canada-buys-nine-a330-tanker-cargo-planes/
https://skiesmag.com/news/canada-takes-delivery-first-rcaf-cc-330-husky-aircraft/
https://www.canada.ca/en/department-national-defence/news/2023/07/the-strategic-tanker-transport-capability-project-and-norad-modernization0.html

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
