### ISSUE TITLE
SQUARE TIE has Incorrect band

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#4382]
### DB Selector

Both

### Affected DBID(s)

DB3000: Sensor_38; _1556; Facility_1499; _1500;_1348; _1114; _1113; _1030; _1116; _1117;_1118; _1347; _1119; _299; _1120; _1121; _1122; CWDB: Sensor_930; _617

### Summary of Changes

The SQUARE TIE  aka Type 352 aka MR-331 aka H/LJQ352 aka Rangout in CMO is  assigned operating band H (6-8 Ghz).  Multiple refrences instead give it NATO band I (8-10 GHz)

![Square Tie](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99547401/9cc93f2a-a382-476e-8fba-e64c356f829e)

### Sources

Janes Radar and Electonic Warfare Systems, 2002-03, "Square Tie air and surface search radar", 02 July 2001; "Type 352 Radar." Wikipedia, the Free Encyclopedia. Last modified June 25, 2006; Friedman, Norman. The Naval Institute Guide to World Naval Weapons Systems, 1997-1998. Naval Inst Press, 1997, pg. 331 ; NATO, "Current Soviet Block Equipment: Shipborne at page 1-c-22   https://archives.nato.int/uploads/r/nato-archives-online/7/e/7/7e7bdc7569e4f683c39b35e1e3da9fcebf56096cfd1d8f73bc80df03e6b2f014/MC_0262_A_67_FINAL_ENG_PDP.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
