### ISSUE TITLE
Add P-18ML for Ukraine

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4384]
### DB Selector

DB3K

### DBID to Copy

Sensor 2693

### Hypothetical

No

### Name

P-18ML

### Country

Ukraine

### Service

Air Force

### In Commission

2022-present

### Sensors

**Max range 400km / 215nmi
Transmitter pulse power decreased to 8kW 
Frequency Agility: spans entire 200KHz (200 working frequencies)
Detection Accuracy of 180m at 0.4 degrees 
Range Resolution of 1200m at 8 degrees
Clutter Suppression > 40 dB
Range of receiver/digital signal process: up to 100 dB
Power Consumption: 6kW**

![1_1547641339-1ba690d22cf53cd7601a32144b76fa97](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/dc579e1f-eeb8-48de-9566-3be74607a1bb)
before/after upgrade comparison
![upgrade](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/6031db87-39f1-402b-83f5-c88ee513a276)

### Other Changes

late 2010's upgrade using new solid state transmitter components and modern computing processes

### Sources

https://www.altimus-tech.lt/product/radar-systems/P-18ML/

https://www.defenceturkey.com/en/content/p-180u-and-mars-l-radar-purchase-from-ukraine-and-turaf-pyas-project-4061

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
