### ISSUE TITLE
Add ships as targets for SCALP-EG/Storm-Shadow cruise missiles 

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4385]
### DB Selector

DB3K

### Affected DBID(s)

weapon 333. weapon 957

### Summary of Changes

enable surface ships to be targeted by scalp/stormshadow. 
Proof: warship in naval dock hit . submarine hit. at least 3 ships/subs hit so far by storm shadows/ scalp missiles

### Sources

https://news.yahoo.com/images-show-results-successful-storm-170600748.html
https://www.forbes.com/sites/davidaxe/2023/09/18/a-ukrainian-cruise-missile-with-a-special-warhead-blew-up-that-russian-submarine-from-the-inside/?sh=2c05a5fa5efd

**Comment by tbrandon517** [comment]
Is there any source Indicating SCALP can hit a moving ship?

I think this scenario is something CMO doesn't really do since the examples are moored ships being attacked. That's like attacking a building. Right now you can target the pier but not the ship tied to it.

**Comment by sr71xx** [comment]
> Is there any source Indicating SCALP can hit a moving ship?
> 
> I think this scenario is something CMO doesn't really do since the examples are moored ships being attacked. That's like attacking a building. Right now you can target the pier but not the ship tied to it.


At least should be able to target a stationary ship. In theory such a cruise missile with its own IIR/TV seeker and steering fins can definitely hit a moving ship. If a neptune can, so can SCALP-EG or any other advanced cruise missile for that matter
But you're right. Targeting a pier will basically simulate hitting a stationary ship(s)

**Comment by FrangibleCover** [comment]
If you hit the pier the ships moored there will be damaged or destroyed, just the same as hitting a hangar kills planes. This works just fine in CMO, and also models the Whatever It Was in Berdyansk and many other examples of docked ships being sunk. I suppose what it fails to represent is anti-ship weapons against docked vessels, such as aerial torpedoes in WW2 or Exocets in the Tanker War, but I feel like those can mostly be worked around by placing the ships in the correct positions rather than in a dock.

**Comment by sr71xx** [comment]
> If you hit the pier the ships moored there will be damaged or destroyed, just the same as hitting a hangar kills planes. This works just fine in CMO, and also models the Whatever It Was in Berdyansk and many other examples of docked ships being sunk. I suppose what it fails to represent is anti-ship weapons against docked vessels, such as aerial torpedoes in WW2 or Exocets in the Tanker War, but I feel like those can mostly be worked around by placing the ships in the correct positions rather than in a dock.

Yea that makes sense. In that case, until there is evidence any cruise missile can hit a moving ship that is not docked, I'll close this ticket.

**Comment by tbrandon517** [comment]
> If you hit the pier the ships moored there will be damaged or destroyed, just the same as hitting a hangar kills planes. This works just fine in CMO, and also models the Whatever It Was in Berdyansk and many other examples of docked ships being sunk. I suppose what it fails to represent is anti-ship weapons against docked vessels, such as aerial torpedoes in WW2 or Exocets in the Tanker War, but I feel like those can mostly be worked around by placing the ships in the correct positions rather than in a dock.

Well at least there is at least one land attack torpedo, the CWDB Mark 13B Torpedo - (Anti-Dam version) Bomb to do that too.

**Comment by claudejdev** [comment]
Cf. #4146
