### ISSUE TITLE
Ship France - Marine National FREMM/Horizon all variants sensor upgrade. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4386]
### DB Selector

DB3K

### Affected DBID(s)

SHIP # All French FREMM /Horizon 2024+

### Summary of Changes

Add sensor Group 5991 Paseo XLR for USV defence measures. Paseo XLR advanced EO/IR system on all FREMM frigates and Horizon type Air Defense destroyers. Probably the start of a trend along with a lot more small calibre guns RWS and smart ammunition. 

### Sources

https://twitter.com/navalnewscom/status/1767488009912320438?t=1PhlcVkGDGkTZgQORp8SYQ&s=19

https://www.safran-group.com/media/57603/download

Long range EO/IR 360 motion tracking on several spectrums providing a fire control solution and automated alerting ? .

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
