### ISSUE TITLE
64N6 Big Bird C Change To PESA Design

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4387]
### DB Selector

DB3K

### Affected DBID(s)

sensor 973

### Summary of Changes

sensor code change: PESA
the 64n6 is PESA just like 91n6e. very similar to the 91n6e big bird d, same amount of phase shift elements. Only difference is the Big Bird D has upgraded computer software and much higher antenna power output, plus greater signal processing capabilities.

### Sources

https://odin.tradoc.army.mil/WEG/Asset/64N6_
https://www.ausairpower.net/APA-Acquisition-GCI.html#mozTocId420074

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
