### ISSUE TITLE
Add Bahrainian Patriot 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4388]
### DB Selector

DB3K

### DBID to Copy

Facility 4139

### Hypothetical

No

### Name

SAM Bty (Patriot [PAC-2 GEM+, PAC-3 MSE])

### Country

Bahrain

### Service

Air Force

### In Commission

2024

### Number in Service

2x

### Sensors

AN/MPQ-65 Radar

### Mounts

Same

### Loadout Options

Same

### Sources

https://www.janes.com/defence-news/news-detail/bahrain-inaugurates-patriot-air-defence-base
https://breakingdefense.com/2024/03/bahrain-receives-first-pac-3-mse-shipment-from-lockheed-martin/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
