### ISSUE TITLE
Add Bahrainian Crotale 1995

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4389]
### DB Selector

DB3K

### DBID to Copy

Facility 551

### Hypothetical

No

### Name

SAM Plt (Crotale 2000)

### Country

Bahrain

### Service

Army

### In Commission

1995

### Number in Service

x7

### Sources

https://www.militaryimages.net/threads/bahrain-armed-forces.9423/
https://www.jstor.org/stable/resrep22516.14?seq=6

Sipri lines
Bahrain	France	1994	?	30	?	R-440 Crotale	SAM	30	?	1995	New	Supplier uncertain
Bahrain	France	1994	?	1	?	Crotale	mobile SAM system	1	?	1995	New	Supplier uncertain

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
