### ISSUE TITLE
RCAF CP-121 Tracker 1959-1969 x57

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#439]
### DB Selector

CWDB

### Affected DBID(s)

1640 CWDB

### Summary of Changes

This platform should be the CS2F-3 version as noted below. It is also missing a searchlight, please add #406 Generic Searchlight.

CS2F-2

An improved version of the CS2F-1 with Litton Industries tactical navigation equipment,  improved Magnetic Anomaly Detection (MAD), radar systems and minor airframe refinements. There were around 100 improvements overall. Previously, tactical navigation was provided by the co-pilot using a manual plotting board. The inclusion of this first generation automated navigation equipment provided an enhanced level of accuracy over large open ocean areas by providing automatic computations of position when the aircraft was actively pursuing a submarine. This version looked almost identical to its forerunner on the exterior. Fifty-seven were built by de Havilland Canada serialled 1544 to 1600 (DH-43 to DH-99). The first CS2F-2's entered service with the RCN in January 1960. As they were taken on strength, they gradually replaced the older CS2F-1's .

### Sources

http://jproc.ca/rrp/rrp3/tracker.html
https://www.yumpu.com/en/document/read/5100903/grumman-cs2f-cp-121-tracker-royal-canadian-navy-pdf
http://jproc.ca/rrp/rrp3/tracker_equipment_details.html

![60fadc65c8f00d7d8b78cb73_de-Havilland-Canada--Grumman--CS2F-1--CP-121-Tracker---MIKAN-No--4821470](https://user-images.githubusercontent.com/99632305/156256532-2c0ce6cc-f619-47a5-b68f-61a0ca0659db.jpg)

**Comment by Jkryos** [comment]
Updated CWDB 494.
