### ISSUE TITLE
Add Bahraini RBS-70 MANPADS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4390]
### DB Selector

DB3K

### DBID to Copy

Facility 1190

### Hypothetical

Yes

### Name

SAM Plt (RBS 70 Mk1 MANPADS x 3)

### Country

Bahrain

### Service

Army

### In Commission

1981

### Sources

https://www.jstor.org/stable/resrep22516.14?seq=6
https://www.army-technology.com/projects/rbs70/

Sipri Line

Bahrain	Sweden	1979		161		RBS-70	portable SAM	161

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
