### ISSUE TITLE
Add Bahraini AAA Sec (35mm Twin Oerlikon GDF-005, Skyguard FCR) 1986

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4391]
### DB Selector

DB3K

### DBID to Copy

Facility 2852

### Hypothetical

No

### Name

AAA Sec (35mm Twin Oerlikon GDF-005, Skyguard FCR)

### Country

Bahrain

### Service

Airforce

### In Commission

1986

### Sources

Links
https://en.wikipedia.org/wiki/Oerlikon_GDF
https://odin.tradoc.army.mil/WEG/Asset/Oerlikon_GDF-005_Swiss_35mm_Towed_Anti-Aircraft_Gun

Sipri Entry

Bahrain	Switzerland	1985	?	6		Skyguard	fire control radar	6	?	1986	New	For use with GDF AA guns	5	30	30

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
