### ISSUE TITLE
Add Bahraini Stinger MANPADS 1988

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4392]
### DB Selector

DB3K

### DBID to Copy

Facility 2907

### Hypothetical

Yes

### Name

SAM Sec (Stinger MANPADS x 2)

### Country

Bahrain

### Service

Army

### In Commission

1988

### Sources

Sources
https://milinme.files.wordpress.com/2013/03/bbh-503.jpg
https://www.inss.org.il/he/wp-content/uploads/sites/2/systemfiles/(FILE)1302523711.pdf
https://www.upi.com/Archives/1987/12/02/White-House-pushing-missile-for-Bahrain/6918565419600/
https://armyrecognition.com/united_states_american_missile_system_vehicle_uk/stinger_fim-92_fim-92a_man_portable_air_defense_missile_system_manpads_technical_data_sheet_picture.html

Sipri Lines
Bahrain	United States	1987		70	?	Stinger	portable SAM	70	?	1988	New	$7.1 m deal (incl 14 or 16 launchers)	0.08	5.6	5.6

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
