### ISSUE TITLE
Way too many GBU-31 on F-15K

### ISSUE THREAD

**Issue by Ma-ryang** [PygmalionOfCyprus/cmo-db-requests#4393]
### DB Selector

DB3K

### Affected DBID(s)

#1748 , #3658 , #4514 , #4982

### Summary of Changes

Based on DB3000 v504, all F-15K (#1748 , #3658 , #4514 , #4982)'s GBU-31 Loadout are overequipped with GBU-31
(they now carry total 8 GBU-31 (Mk84 and BLU-109/B))

they should have or role back to 2 GBU-31 for long strike mission and 4 GBU-31 for generic loadout

### Sources

![Desktop Screenshot 2024 03 13 - 17 00 51 16](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99650102/3b5ace09-0321-4fa3-bcea-3aabb24f9d7c)
(for a comparison, USAF F-15E GBU-31 Loadout)
![Desktop Screenshot 2024 03 13 - 17 01 28 23](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99650102/60962b01-43f8-4562-bf0d-ba97d2501a83)
_(Gigachad_ F-15K with 8 GBU-31)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
