### ISSUE TITLE
Add Hwasong-8 HGV to DB

### ISSUE THREAD

**Issue by wolfmanpuck** [PygmalionOfCyprus/cmo-db-requests#4395]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Bn (Hwasong-8 TEL)

### Facility Type

SSM

### Country

North Korea

### Service

Army

### In Commission

2017

### Sensors

1x Mk1 Eyeball

### Mounts

1x Hwasong-8 [HGV] TEL

### Comments

 It purportedly has a hypersonic speed of Mach 5+ and a range of at least 3,200km.

### Sources

Characteristics: https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/north-korea/hwasong-8/
Launch + analysis: https://edition.cnn.com/2022/01/10/asia/north-korea-missile-intl/index.html
General overview: https://www.bbc.com/news/world-asia-41174689
https://www.globalsecurity.org/wmd/world/dprk/hwasong-8.htm

**Comment by PygmalionOfCyprus** [comment]
Already in DB as Weapon 4431, Facility 4224.
