### ISSUE TITLE
Add Hwasong-12 (KN-17) IRBM to DB

### ISSUE THREAD

**Issue by wolfmanpuck** [PygmalionOfCyprus/cmo-db-requests#4396]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Bn (KN-17 TEL, Hwasong-12)

### Facility Type

SSM

### Country

North Korea

### Service

Army

### In Commission

2020

### Sensors

1x Mk1 Eyeball

### Mounts

1x KN-17 [Hwasong-12] TEL

### Comments

The missile is 16.5m in length and 1.5m diameter and has an estimated range of at least 4,500km.

### Sources

Characteristics: https://missilethreat.csis.org/missile/hwasong-12/
Characteristics: WMD in Asia Pacific (2022) by Peter Hayes, Tanvi Kulkarni, Chung-in Moon & Shatabhisha Shetty; https://cms.apln.network/wp-content/uploads/2022/03/WMD-in-Asia-Pacific.pdf
Characteristics: https://www.globalsecurity.org/wmd/world/dprk/hwasong-12.htm
Launch + analysis: https://blog.ucsusa.org/david-wright/north-koreas-missile-in-new-test-would-have-4500-km-range/
Launch + analysis: https://www.japantimes.co.jp/news/2022/01/30/asia-pacific/north-korea-missile-launch-seventh/
General overview: https://www.bbc.com/news/world-asia-41174689

**Comment by PygmalionOfCyprus** [comment]
Already in DB as Weapon 4421, Facility 4210.
