### ISSUE TITLE
Add Hwasong-18 ICBM to DB

### ISSUE THREAD

**Issue by wolfmanpuck** [PygmalionOfCyprus/cmo-db-requests#4398]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Bn (Hwasong-18 TEL)

### Facility Type

SSM

### Country

North Korea

### Service

Army

### In Commission

2023

### Sensors

1x Mk1 Eyeball

### Mounts

1x Hwasong-18 [Nuclear] TEL
1x Hwasong-18 [MIRV] TEL

### Comments

The Hwasong-18 demonstrated its potential to travel 15,000 km on an operational trajectory, enough to reach anywhere in the continental United States.

### Sources

Characteristics: https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/north-korea/hwasong-18/
Characteristics: https://www.detailedpedia.com/wiki-Hwasong-18
Launch + analysis: https://www.reuters.com/world/asia-pacific/north-korea-says-it-test-launched-hwasong-18-icbm-wednesday-yonhap-2023-07-12/
General overview: https://www.bbc.com/news/world-asia-41174689
https://www.globalsecurity.org/wmd/world/dprk/hwasong-18.htm

**Comment by PygmalionOfCyprus** [comment]
Already in DB as Weapon 3619, Facility 3226.
