### ISSUE TITLE
Correction to designation of Hwasong-15

### ISSUE THREAD

**Issue by wolfmanpuck** [PygmalionOfCyprus/cmo-db-requests#4399]
### DB Selector

DB3K

### Affected DBID(s)

3226

### Summary of Changes

Change from KN-15 to KN-22

### Sources

https://www.globalsecurity.org/wmd/world/dprk/missile-designation.htm

WMD in Asia Pacific (2022) by Peter Hayes, Tanvi Kulkarni, Chung-in Moon & Shatabhisha Shetty; https://cms.apln.network/wp-content/uploads/2022/03/WMD-in-Asia-Pacific.pdf

**Comment by PygmalionOfCyprus** [comment]
Was already handled, 506 I think.
