### ISSUE TITLE
RCAF CP-121 Tracker 1969 x45

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#440]
### DB Selector

CWDB

### Affected DBID(s)

257 CWDB

### Summary of Changes

This platform should be the CS2F-3 version with a service date starting in 1969. It is missing it's AN/APN-503 which can be represented by #704 Generic Doppler Navigation/Weather radar. The AN/SSQ 47 should also be updated to AN/SSQ-28 as both the Julie and Jezebel systems were updated, the Jezebel is already updated to SSQ-2 from SSQ-1 on this platform. It is also missing a searchlight, please add #406 Generic Searchlight.

CS2F-3

The RCN developed further improvements to the Tracker, which resulted in Fairey Aviation substantially modifying fourty-five CS2F-2's to a new  CS2F-3 designation.. The CS2F-3 featured a second generation AN/ASN-501 tactical navigation computer, a Marconi AN/APN-503 Doppler radar, improved Jezebel and Julie submarine detection systems and an analogue computer to automatically integrate information from the Tracker's anti-submarine sensors. This was called the Anti-Submarine Warfare Tactical Navigation System  (ASWTNS) and is described in more detail elsewhere in this web document. The first CS2F-3 (#1552) conversion was completed on 18 July 1966 and the last CS2F-3 (#1555) was completed on 19 April 1968.

### Sources

https://www.yumpu.com/en/document/read/5100903/grumman-cs2f-cp-121-tracker-royal-canadian-navy-pdf
http://jproc.ca/rrp/rrp3/tracker.html
http://jproc.ca/rrp/rrp3/tracker_equipment_details.html
![60fadc64c2ea6605d3241ed9_Grumman-Tracker--RCN--Serial-No--1595---HMCS-Bonaventure--1969--Mike-Kaehler](https://user-images.githubusercontent.com/99632305/156256444-d6c25f91-989d-49f8-bdad-5584aa277379.jpg)

**Comment by Jkryos** [comment]
Updated 494.
