### ISSUE TITLE
Correction to designation of Hwasong-14

### ISSUE THREAD

**Issue by wolfmanpuck** [PygmalionOfCyprus/cmo-db-requests#4400]
### DB Selector

DB3K

### Affected DBID(s)

3191

### Summary of Changes

Change from KN-14 to KN-20

### Sources

https://www.globalsecurity.org/wmd/world/dprk/missile-designation.htm

WMD in Asia Pacific (2022) by Peter Hayes, Tanvi Kulkarni, Chung-in Moon & Shatabhisha Shetty; https://cms.apln.network/wp-content/uploads/2022/03/WMD-in-Asia-Pacific.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
