### ISSUE TITLE
Correction to Pukguksong-2 designation

### ISSUE THREAD

**Issue by wolfmanpuck** [PygmalionOfCyprus/cmo-db-requests#4401]
### DB Selector

DB3K

### Affected DBID(s)

3462

### Summary of Changes

Change from KN-11 to KN-15
Could also include that it is also known as KN-11 Mod 1

### Sources

https://missilethreat.csis.org/missile/pukkuksong-2/

WMD in Asia Pacific (2022) by Peter Hayes, Tanvi Kulkarni, Chung-in Moon & Shatabhisha Shetty; https://cms.apln.network/wp-content/uploads/2022/03/WMD-in-Asia-Pacific.pdf

https://www.globalsecurity.org/wmd/world/dprk/missile-designation.htm

**Comment by PygmalionOfCyprus** [comment]
Was already handled at some point. Prob 506.
