### ISSUE TITLE
SARH SAM missiles not functioning properly, unable to hit any type of jet/cruise missile target?

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4402]
### DB Selector

DB3K

### Affected DBID(s)

weapon 642, 994, 2103, 1113, 878

### Description of Problem

The following SAM facilities that use SARH missiles without being jammed, are unable to down any type of 4th gen fighters and large, slow moving targets like AWACS, cruise missiles, or glide bombs. Tried building SEAD missions with the following facilities and noticed all of them, no matter how many batteries I placed, kept missing dozens of shots against most air and cruise missile targets even at very close ranges
**PAC-2
PAC-2 GEM / GEM +
SA-20a , SA-20b, SA-21a**
**missiles effected: Patriot M901, 48N6DM, 48N6, 48N6E2** 

unable to hit any cruise missiles at close/medium ranges (5-10nm) regardless of stealth: kh-55, kh-101, tomahawk, JASSM
unable to hit any 4th,5th gen fighters or large slow moving aircraft, or precision guided missile/glide bomb

Only effecting the previously mentioned SAM facilities that use strictly SARH guidance. This is NOT effecting any SAM facilities using ARH or IR guidance for their missiles.

### Recommended Fix

**check the missile datalink? possible broken weapon datalink, or other missile/FCR issue, Not sure but this only started happening since latest build. Don't remember this occurring in December or January**
here is a screenshot showing dozens of PAC-2 GEM+ and 48N6DM Sa-21 missiles missing a small number of standard non-VLO KH-55 cruise missiles. 5 SAM batteries versus 12 kh-55 and still could not down a single one.
![kh55](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/ea730d0e-8acd-4294-9e56-4b384f05473b)

**Comment by tbrandon517** [comment]
What version are you on?

You are describing the TVM missile problem here

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=401623

 that was addressed in this hotfix release.

https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=401912

**Comment by sr71xx** [comment]
> What version are you on?
> 
> You are describing the TVM missile problem here
> 
> https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=401623
> 
> that was addressed in this hotfix release.
> 
> https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=401912

Yes that is the same issue. 
currently on version 1328.14
will try the hotfix 
thanks
