### ISSUE TITLE
Add upgraded Ukrainian 36D6M Radar

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4403]
### DB Selector

DB3K

### DBID to Copy

Sensor 632

### Hypothetical

No

### Name

36D6M 

### Country

Ukraine

### Service

Air Force

### In Commission

2020-present

### Sensors

changes:
**sensor code: early 2010's generation
peak transmitter power= 350 kW
suppression of passive interference > 48 dB
suppression of active noise jammers = 20 dB
Number of Tracked Targets = 300**

Improved target detection: 
**Target detection range with EPR of 1 m²
=42 km at a flight height of 100m
Target detection range with EPR of 1 m²
=115 km at a flight height of 1000m**

![36d6m 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/776f50c9-830f-4232-b9de-9b5f9f7d73bb)
![36d6m 1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/064b7e0c-d976-4199-b7bd-0f1924d7c51e)

### Other Changes

brochure attacked below

in active service

### Sources

https://spetstechnoexport.com/product/36d6m

https://en.defence-ua.com/news/iskra_has_demonstrated_its_new_radar_systems_to_foreign_military_attaches_in_ukraine-1934.html

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
