### ISSUE TITLE
Add Ukrainian AESA 90K6E Radar

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4404]
### DB Selector

DB3K

### DBID to Copy

Sensor 3307

### Hypothetical

No

### Name

90K6E

### Country

Ukraine

### Service

Air Force

### In Commission

2020-present

### Number in Service

few for vital areas

### Sensors

Main Specifications:
 **maximum range = 500 km / 270nmi
 in azimuth 360°
 in elevation 0°-70°
 max altitude = 40 km
S Band (E/F Band NATO)
Target detection range, RCS=2m2
At flight altitude 10-30km = 450 km
Transmitter type Solid State AESA
Antenna type DAPAR (digital active phased array radar)
Number of beams = 16
Clutter suppression More > 50 dB
Jamming canceling More > 20 dB
Simultaneously track capability: 300 targets
Peak Power Output = 32 kW
Late 2010's sensor generation code**

![90k6e 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/79448c36-5961-461b-a714-feda592a9ad3)

### Other Changes
Similar to GM 400 in antenna shape/size/radar band and characteristics
![90k6e](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/dd3c36ad-3779-4565-a5f9-00e73c25dae4)
![90k6e 3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/d835d7df-5e8b-4745-9699-dd0fbb1cb9f0)

### Sources

https://steback.site/storage/files/90K6E.pdf

https://spetstechnoexport.com/product/90k6e

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
