### ISSUE TITLE
China, PLAAF, WS-10 & WS-15 

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4408]
### DB Selector

DB3K

### Affected DBID(s)

Can't find engine DBID, need some help

### Summary of Changes

- [ ] Change the military static SFC of ws-10 series (variant A/B/C) to 0.69kg/h/kg

- [x] Change the military static SFC of ws-15 to 0.66kg/h/kg

### Sources

https://en.wikipedia.org/wiki/Shenyang_WS-15#cite_note-23
https://premium.globalsecurity.org/military///world/china/ws15.htm
https://zh.wikipedia.org/wiki/%E6%B6%A1%E6%89%87-10

**Comment by PygmalionOfCyprus** [comment]
WS-15 specs handled during PLAAF review, do you have a better source on the WS-10s? I've seen the 0.69kg number thrown around, but even the Chinese say they're supposed to basically be equivalent to the Russian AL-31MFs and those have a ~.77-78 SFC.

**Comment by LuigiP57** [comment]
> WS-15 specs handled during PLAAF review, do you have a better source on the WS-10s? I've seen the 0.69kg number thrown around, but even the Chinese say they're supposed to basically be equivalent to the Russian AL-31MFs and those have a ~.77-78 SFC.

Unfortunately, this is yet another thing that only AVIC knows.

Perhaps we can view this figure as the performance of the latest improved (C variant) WS-10 series? Perhaps 0.77/0.73/0.69 SFC could be given to A/B/C variants?

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
