### ISSUE TITLE
China, PLAAF, J-20 empty weight and fuel consumption

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4409]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2463 5012 5013 5014 5454

### Summary of Changes

- [ ] According to the more reliable public information (especially from the Tsinghua University defense website), the J-20's empty weight seems to be too high in the DB, and it should be set to 17000kg.

- [ ] Most OSINT shows that the J-20's combat radius can reach 2,000 km (1200nm). However, the actual performance in the game shows that its combat radius is even less than the F-22. I noticed that its fuel cosumption was much higher than the F-22 at the same level. Therefore, the fuel consumption of the J-20 series may need to be reduced appropriately.

### Sources

https://en.wikipedia.org/wiki/Chengdu_J-20#Specifications_(J-20A)

**Comment by PygmalionOfCyprus** [comment]
Handled 506 as part of PLAAF review. Engine stats should be tweaked, too. I honestly think if there are errors they are more w/ the F-22 than with the J-20 at this point, as we have stated fuel, range, and engine specs for the J-20 (which all go into the fuel consumption calculations) but not AFAIK for the F-22.
