### ISSUE TITLE
Fattah 2 HCM

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4414]
### DB Selector

DB3K

### Baseline

DF17

### Hypothetical

No

### Name

Fattah 2

### Length (m)

12

### Width/Span (m)

1.2

### Diameter (m)

.8

### Weight (kg)

3800

### Range (nm)

755

### Warhead

200kg HE

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway, Radar, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

30m

### Sensors

Inertial Navigation and GPS Guidance (although hard to imagine Iran having access to use GPS for its weapons, possibly uses Glonass or Beidou as an alternative?)

### Weapon Codes

Bearing-Only Launch (BOL), Weapon - INS Navigation, Terminal Maneuver - Random (Advanced), Uses GPS, Uses GLONASS, Uses BeiDou/COMPASS

### Comments

First unveiled in 2023, Technically a hypersonic cruise missile with a liquid fueled 2nd stage and a solid fuelled booster enabling a top speed of at least mach 5 and an aerodynamic flight profile. 

Likely designed in parallel with the Fattah 1 as a means to defeat US/Israeli ABM systems to engage fixed targets

### Sources

https://en.abna24.com/story/1433409

https://armyrecognition.com/defense_news_november_2023_global_security_army_industry/iran_unveils_fattah-2_hypersonic_cruise_missile.html

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
