### ISSUE TITLE
WZ8 Hypersonic Drone Service Ceiling incorrect

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4415]
### DB Selector

DB3K

### Affected DBID(s)

6642

### Summary of Changes

Maximum Altitude increased to 160,000ft

As it uses a rocket engine, its performance isn't limited lack of oxygen.

### Sources

https://en.wikipedia.org/wiki/AVIC_WZ-8

**Comment by PygmalionOfCyprus** [comment]
Handled 506 as part of ongoing China review.
