### ISSUE TITLE
J31/J35 Corrections

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4417]
### DB Selector

DB3K

### Affected DBID(s)

2917, 4454

### Summary of Changes

According to the closest thing to official specs given for the J31/J35

RCS revealed to be around 0.01sqm (which makes much more sense than the current 0.2ish sqm)

Engines replaced 2x WS19 Afterburning turbofans, allowing for:
Maximum speed of Mach 2.2 (although more likely mach 1.8)
MTOW of 35000kg
Max Payload of 8000kg

Supercruise capability (at least over mach 1 without afterburner)
https://www.globalsecurity.org/military/world/china/ws19.htm

### Sources

https://www.china-arms.com/2024/02/j-35-specs-unveiled/
https://www.globalsecurity.org/military/world/china/ws19.htm

**Comment by LuigiP57** [comment]
> Engines replaced 2x WS19 Afterburning turbofans, allowing for:
Maximum speed of Mach 2.2 (although more likely mach 1.8)
MTOW of 35000kg

Forgive me, but I'm actually a little skeptical about this statistic.

The WS-19 is widely considered to be a medium-thrust engine on the same level as the F-414 and EJ200, rather than a high-thrust engine such as the WS-15/F-119/F-135. Achieving Mach 2.2 and a maximum takeoff weight of 35 tons with just two WS-19s (37 tons for the F-22, 2x F-119) seems a little unlikely.

I went to official AVIC website and found thta they did not give any specification of the J-31/J-35 Gyrfalcon.

**Comment by Siegemiester** [comment]
> > Engines replaced 2x WS19 Afterburning turbofans, allowing for:
> > Maximum speed of Mach 2.2 (although more likely mach 1.8)
> > MTOW of 35000kg
> 
> Forgive me, but I'm actually a little skeptical about this statistic.
> 
> The WS-19 is widely considered to be a medium-thrust engine on the same level as the F-414 and EJ200, rather than a high-thrust engine such as the WS-15/F-119/F-135. Achieving Mach 2.2 and a maximum takeoff weight of 35 tons with just two WS-19s (37 tons for the F-22, 2x F-119) seems a little unlikely.
> 
> I went to official AVIC website and found thta they did not give any specification of the J-31/J-35 Gyrfalcon.

Yeah the MTOW does seem rather embellished. Maybe its accomplishing this with the aid of a carrier catapult? 

The top speed would probably lean more on the mach 1.8 side than the mach 2.2 side.

My number 1 gripe with it is that it right now is the RCS, which is basically a that of 4.5gen aircraft when clearly from the start it was designed as a 5th gen.

**Comment by LuigiP57** [comment]
For reference: 

KAAN

> Max takeoff weight: 27,215 kg (60,000 lb)
Powerplant: 2 × General Electric F110-GE-129 Turbofan], 76.31 kN (17,155 lbf) thrust each dry, 131 kN (29,000 lbf) with afterburner

F/A-18E/F

> Max takeoff weight: 66,000 lb (29,937 kg)
Powerplant: 2 × General Electric F414-400, 13,000 lbf (58 kN) thrust each dry, 22,000 lbf (98 kN) with afterburner

**Comment by PygmalionOfCyprus** [comment]
>My number 1 gripe with it is that it right now is the RCS, which is basically a that of 4.5gen aircraft when clearly from the start it was designed as a 5th gen.

What China "designs" something as and what it is actually capable of are two very different things. I respect China, but we also have to be realistic and acknowledge that when it comes to cutting-edge mil fields like VLO, submarine quieting, etc. they are not yet quite on par with the best Western equipment (e.g. F-22/F-35, Virginia Blk V, etc.). This has been acknowledged by serious people on both "sides." Post China-review overhaul it gets the same stealth modifiers as the J-20, which I think is fair.

Anyway, FC-31 has been overhauled with the China review for 506 so consider this ticket handled. Feel free to holler if you find discrepancies after the 506 release though.

**Comment by Siegemiester** [comment]
> > My number 1 gripe with it is that it right now is the RCS, which is basically a that of 4.5gen aircraft when clearly from the start it was designed as a 5th gen.
> 
> What China "designs" something as and what it is actually capable of are two very different things. I respect China, but we also have to be realistic and acknowledge that when it comes to cutting-edge mil fields like VLO, submarine quieting, etc. they are not yet quite on par with the best Western equipment (e.g. F-22/F-35, Virginia Blk V, etc.). This has been acknowledged by serious people on both "sides." Post China-review overhaul it gets the same stealth modifiers as the J-20, which I think is fair.
> 
> Anyway, FC-31 has been overhauled with the China review for 506 so consider this ticket handled. Feel free to holler if you find discrepancies after the 506 release though.

Really the proposed 0.01sqm RCS roughly inline with the J20 and still orders of magnitude less stealthy than either the F22 or F35

**Comment by PygmalionOfCyprus** [comment]
Yes, that's why I changed it:

> Post China-review overhaul it gets the same stealth modifiers as the J-20, which I think is fair.

So it will be more stealthy for 506.
