### ISSUE TITLE
China, PLAAF, WZ-8 SAR equipped

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4418]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 6642; Weapon 4274

### Summary of Changes

According to leaked intelligence from the US Department of Defense, the WZ-8 may be equipped with SAR. In the current game, the WZ-8's sensors are not enough to support its effective detection.

### Sources

https://en.wikipedia.org/wiki/AVIC_WZ-8
https://www.washingtonpost.com/world/2023/04/18/china-supersonic-drone-taiwan-leaks/

**Comment by LuigiP57** [comment]
#4415

**Comment by PygmalionOfCyprus** [comment]
Handled 506 as part of ongoing China review.
