### ISSUE TITLE
Sayyad-4 engagement radar issue

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#4419]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3229

### Summary of Changes

- Its engagement radar is of the older generation. Shouldn`t it supposed to be of the same generation as its air search radar since its also an AESA radar? 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/f732f485-b45c-41c0-8d38-4b59c85dd11d)

### Sources

DB 505

**Comment by sr71xx** [comment]
Also noticed the Sayyad-4 is missing INS/Midcourse datalink, functions more as a TVM missile instead.
Sayyad-4 should have midcourse datalink/INS uplink just like other ARH missiles such as PAC-3, 40N6, HQ-9B, etc

**Comment by capcop98** [comment]
Closed and replaced with #5244
