### ISSUE TITLE
CCGS Cape Roger

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#442]
### DB Selector

DB3K

### Affected DBID(s)

2392&2393

### Summary of Changes

- 2x RHIB missing

### Sources

See Deck Eqipment:
https://inter-j01.dfo-mpo.gc.ca/fdat/vessels/44

**Comment by PygmalionOfCyprus** [comment]
Is this the true end of the Canadian milestone or is there more yet to come?

**Comment by cdnice55** [comment]
I think it is!! Finished my resource crawl. If you need more of something let me know and I will try to find it for you since you already have enough to do I am sure.

**Comment by PygmalionOfCyprus** [comment]
![showtime](https://user-images.githubusercontent.com/87087226/156712817-ef9c9424-6d74-4fe9-9a1e-eeb47f4a3634.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
