### ISSUE TITLE
Update/correction for Zoubin/Nawab missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#4420]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4263

### Summary of Changes

- Change the missiles`s seeker to (Imaging Infrared)IIR seeker. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/a95dd4ba-94e1-47ef-9242-6e999e8cbb84)

- Change the missile`s guidance type to "All-Aspect, High Off-Boresight and Datalink(DL/INS) midcourse plus Passive terminal guidance". Add  two-way datalink for this weapon and its launch platforms(mounts in Facility 3815, Ship 4539/4538/3392)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/435aea30-2a09-4f4b-a34e-af035db92807)

- Remove weapon`s property "illuminate at launch"

- Add magazine that contains 16x Zoubin/Nawab missiles for Facility 3815. Such launcher should have a few reload at least

### Sources

- https://twitter.com/imp_navigator/status/1757310613338964193
- http://www.hisutton.com/Iran-IRGC-Air-Defense-Fast-Boat.html

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
