### ISSUE TITLE
Add Libyan SAM Plt (SA-22 Greyhound [Pantsir S1E) 2019

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4423]
### DB Selector

DB3K

### DBID to Copy

Facilityi 1936

### Hypothetical

No

### Name

SAM Plt (SA-22 Greyhound [Pantsir S1E)

### Country

Libya HoR

### Service

Army

### In Commission

2019

### Number in Service

x2, -1 

### Other Changes

Owned by House of Representatives Faction (HoR)
1 destroyed in 2020
https://twitter.com/ParsKuru/status/1279011483716915201

### Sources

https://twitter.com/MTailamun/status/1768671587077587172
https://twitter.com/MTailamun/status/1769383515668299782

Sipri Line

Libya HoR*	UAE	2019	?	2	?	96K9 Pantsyr-S1	self-propelled AD system	2	?	2019	Second hand	Second-hand; aid	4.4	8.8	8.8

**Comment by PygmalionOfCyprus** [comment]
We're not gonna get sucked into doing subfactions in Libya right now. For now we're sticking to regular militaries. Fortunately this can be easily handled in a scenario just by using another country's entry.
