### ISSUE TITLE
KF-21 Blk1 and Blk2 Boom Refueling Updates

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4424]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5183, 5184

### Summary of Changes

Add Boom Refueling Property

### Sources

Boom Refueling
https://twitter.com/Defence_IDA/status/1770037001523188106
https://twitter.com/Fighterman_FFRC/status/1769988946631840220

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
