### ISSUE TITLE
J11D, J15B, J15D, J16, J16D Composite Airframes

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4426]
### DB Selector

DB3K

### Affected DBID(s)

4039, 6098, 4957, 4817, 2853, 4225, 4927, 6450, 4926, 4632

### Summary of Changes

According to source
https://militarywatchmagazine.com/article/super-flanker-j15b-first-look
https://militarywatchmagazine.com/article/china-researching-means-to-provide-fourth-generation-aircraft-with-advanced-stealth-capabilities-initial-technologies-first-deployed-in-early-2018

Newer (2014 onwards) variants of chinese flankers have some degree of RCS reduction using a combination of stealth coatings and composite airframes in the same vane the Russians did on their SU35s

Reduce RCS of these flanker derivatives to be in line with the SU35 

### Sources

https://militarywatchmagazine.com/article/super-flanker-j15b-first-look

**Comment by PygmalionOfCyprus** [comment]
This is very interesting. I did a little more digging.

The J-10C (which you didn't explicitly list, but nevertheless came up in my research) received some structural changes and RAM/RAM-like coatings, so I've given it the same modifier I use for Typhoon. (Partial Shaping / Lite RAM)

There is lots of evidence, including MSM reporting, of J-16s receiving a Have Glass-type upgrade with RAM paint in 2019, so I've added a new entry + applied the Have Glass V modifier (No Shaping / Adv RAM) to 2019+ J-16. Likewise, I found some reports of a similar stealth coating on the J-11D and J-15B from the beginning of design, so those also get Have Glass V RCS reduction.

Thanks for the ticket! Handled 506.
