### ISSUE TITLE
CM102 ARM internal loadout for stealth aircraft

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4427]
### DB Selector

DB3K

### User(s)

J20, J31, GJ11 and all their variants

### Weapons Carried

J20:
2xPL10 + 4x CM102
2xPL10 + 2xPL15 + 2xCM102
2xPL10 + 2xPL12 + 2xCM102

J31:
2xPL15 + 2xCM102
2xPL12 + 2xCM102

GJ11:
4x CM102

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

According to source, the CM102 appears to have cropped fins meaning it is specifically modified to fit inside the weapons bays of chinese stealth aircraft enabling them to conduct SEAD much more effectively than with existing externally mounted ARMs

### Sources

https://www.twz.com/37513/we-may-just-have-got-the-first-glimpse-of-chinas-new-air-launched-anti-radiation-missile

**Comment by LuigiP57** [comment]
Maybe need to submit an additional [weapon] ticket?
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/d26aa7ee-5b05-4751-ae17-ea4c1d8ca031)

**Comment by Siegemiester** [comment]
> Maybe need to submit an additional [weapon] ticket? ![image](https://private-user-images.githubusercontent.com/107970049/314472175-d26aa7ee-5b05-4751-ae17-ea4c1d8ca031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzM1NzksIm5iZiI6MTcxMDkzMzI3OSwicGF0aCI6Ii8xMDc5NzAwNDkvMzE0NDcyMTc1LWQyNmFhN2VlLTViMDUtNDc1MS1hZTE3LWVhNGMxZDhjYTAzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMTE0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWI4MDlkYjI1ODdiYWE3MDNlNGZmNTI0ZGQxOGEzYTc2MDgwODFjNGFhMGQ2OTQxMGRlMTg3Y2Q1Yjc1MDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VfZI92S89HUiUTdVgPnLqFJkautJ8h6YtLZNkK2dJ3w)

The CM102 is already in game it seems, It just isn't being mounted on any relevant aircraft.

**Comment by PygmalionOfCyprus** [comment]
This image appears to have been Photoshopped. Someone in the Twitter replies made a great spot:

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/eaa87b34-b70e-4139-892d-9c4796be4550)

Look at the missile and the landing gear. The retracting landing gear is somehow behind the missile? 

The CM-102 is an export-only missile, not known to be in PLAAF service. (This is actually a perpetual issue we're having on the PLAAF/PLANAF review: _so much_ stuff flies on PLAAF aircraft for testing, etc. but very little of it is actually in official service. Just look at the litany of guided bombs being produced by Chinese companies, of which almost none are actually widely procured by the PLAAF.) China does have an ARM cooking, but whatever it is, this ain't it.

As of right now the main Chinese ARM remains the YJ-91.
