### ISSUE TITLE
Vador ALSR (France 2021) (French Air Force new ELINT aircraft)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#443]
### DB Selector

DB3K

### DBID to Copy

5464 King Air 350ER MEK [EMARSS-S]

### Hypothetical

No

### Name

Vador ALSR

### Country

France

### Service

Air Force

### In Commission

2021

### Sensors

1x AN/AAS-52 MTS [Laser Designator] #2824 && 1x AN/AAS-52 MTS [IR/EO] #2825
replaced by Star Safire III Multi-Sensor Turret [FLIR/CCD/Laser Designator] #4958

### Sources

Vador stands for "vecteur aéroporté de désignation, d'observation et de reconnaissance".  Best.Acronym.Ever.
ALSR avion léger de surveillance et de renseignement (ALSR), baptisé Vador (

Vador ALSR. 2 delivered in 2020, 1 more in 2023 and 3 others before 2030. (8 in total initially planned)

> https://www.defense.gouv.fr/content/download/600535/10123231/S%20-%20Fiche%20LPM%20-%20ALSR.pdf
> https://www.defense.gouv.fr/air/moyens/avions-de-support-des-operations/alsr
> https://www.defense.gouv.fr/salle-de-presse/communiques/communique_le-ministere-des-armees-recoit-son-premier-avion-leger-de-surveillance-et-de-reconnaissance
> https://www.defense.gouv.fr/var/dicod/storage/images/base-de-medias/images/air/actualites/images-2020/decembre-2020/alsr_3/10124094-1-fre-FR/alsr_3.jpg
> https://www.youtube.com/watch?v=wCBVqyy3cbs
> http://www.opex360.com/2020/12/03/un-second-avion-de-renseignement-vador-a-ete-livre-a-larmee-de-lair-et-de-lespace/
> https://www.senat.fr/basile/visio.do?id=r8111789_2&idtable=r8111051_5|r8111789_2|r8111522_5|r8111988_17&_c=ASLR&rch=gs&de=20210226&au=20220226&dp=1+an&radio=dp&aff=sep&tri=p&off=0&afd=ppr&afd=ppl&afd=pjl&afd=cvn#eltSign0

Star Safire III
https://www.key.aero/article/what-lies-ahead-eea-154-dunkirk-and-frances-covert-isr-assets
https://www.avionslegendaires.net/2021/10/actu/alsr-vador-lavion-de-surveillance-incapable-de-surveiller/

Note
While rumor says that the SAFIRE sensor have been replaced, I couldn't find a convincing open source that concurs.

**Comment by PygmalionOfCyprus** [comment]
@Jkryos recommend "King Air 350ER ASLR [VADOR]" for Name.

**Comment by Jkryos** [comment]
Added DB3K 494.
