### ISSUE TITLE
Skyhawk Stealth UAV

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4433]
### DB Selector

DB3K

### Baseline

RQ170

### Hypothetical

Yes

### Name

Skyhawk

### Country

China

### Service

PLAAF

### In Commission

First Flight in 2017

### Number in Service

Prototypes only

### Length (m)

5.5?

### Wingspan (m)

7

### Height (m)

1?

### Empty Weight (kg)

1500?

### Maximum Takeoff Weight (MTOW) (kg)

4000?

### Payload Weight (kg)

0

### Crew

0

### Propulsion

1x Non afterburning turbofan of unknown type

### Service Ceiling (ft)

40000?

### Military/Afterburner Speed (kt)

420?

### Cruise Speed (kt)

360?

### Supercruise

No

### Ferry Range (nm)

2000

### Sensors

1x Generic FLIR
1x Generic LLTV
1x MAWS
1x Radar Warning Receiver

### Mounts

No mounts

### Loadout Options

Recon only

### Comms/Datalinks

UCAV Datalink

### Comments

Source:
https://www.janes.com/defence-news/news-detail/enhanced-chinese-sky-hawk-stealth-uav-takes-to-flight
States "It is mainly used to carry out long-range tactical reconnaissance missions in close-in or penetration missions in a high-threat battlefield environment, and provide effective comprehensive intelligence for command decision-making and fire strikes"

Indicating it is strictly a reconnaissance platform 

Its sensor suite will likely be limited to those of passive reconnaissance

specs are extremely scarse. Despite this drone being at the flyable prototype stage.

### Sources

https://www.china-arms.com/2024/02/china-uav-skyhawk-maiden-flight/
https://www.janes.com/defence-news/news-detail/enhanced-chinese-sky-hawk-stealth-uav-takes-to-flight

**Comment by PygmalionOfCyprus** [comment]
Not a program of record and not a transformative capability (China already has several other flying wing UAVs). Gonna close unless it becomes clear it's moving towards PLA adoption.
