### ISSUE TITLE
Correction to Gabriel I SSM warhead weight

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#4434]
### DB Selector

DB3K

### Affected DBID(s)

CWDB Weapon_543; Weapon_1748; DB3000 Weapon_1559

### Summary of Changes

The game has a Gabriel 1 with a 100 kg warhead.  Multiple sources claim it is a 180 kg warhead.  See Friedman, Norman. The Naval Institute Guide to World Naval Weapon Systems, 5th ed., Annapolis, Md: Naval Institute Press, 2006, pg. 525-26 (2 images attached); 
![Friedman pg526](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99547401/6a0bdad4-e485-4265-ba7e-3e45b33184b1)
![Friedman pg525](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99547401/1a8e55f8-9eed-4915-a40f-622279f5e00a); Orbis "War Machine" vol 25, No 3 (attached) 
![Gabriel](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99547401/71b34c22-075c-4424-8f11-1edceacbf6ff)

### Sources

Friedman, Norman. The Naval Institute Guide to World Naval Weapon Systems, 5th ed., Annapolis, Md: Naval Institute Press, 2006, pg. 525-26 
Orbis "War Machine" vol 25, No 3 (1984), pg.  483  https://www.scribd.com/document/557616902/Orbis-War-Machine-025-Anti-ship-Missiles

**Comment by CV60LCC19** [comment]
I should have noted that Friedman reports the actual explosive weight is 154 lb (70 kg), so in either event, the weight needs to be adjusted.

**Comment by CV60LCC19** [comment]
I've been doing some more research, and I'm wondering about whether the sources I'm citing are in error.  The 180kg warhead weight seems high for a missile that weighs 400 kg. (Friedman, pg. 525) Also, the "Boats of Cherbourg" doesn't give a warhead weight, but does mention that "The Luz warhead was as devastating as the eight-inch shells of the largest cruiser,", which assuming by this is meant an 8" gun, would be around 108 kg. https://en.wikipedia.org/wiki/8-inch_gun_M1 .

**Comment by PygmalionOfCyprus** [comment]
Since it seems like there is some disagreement, and I can find sources that agree with the 100kg number as well, I'm just going to leave it as-is until we can nail it down definitively. Do feel free to reopen if you get more info.
