### ISSUE TITLE
China, PLAAA, Z-21/Z-XX Attack Helicopter, Z-20 deep derivative?

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4435]
### DB Selector

DB3K

### Baseline

aircraft 7033

### Hypothetical

No

### Name

Z-XX [Z-21] , Z-20 deep derivative?

### Country

China

### Service

Army

### Length (m)

15

### Wingspan (m)

3

### Height (m)

5

### Empty Weight (kg)

5000

### Maximum Takeoff Weight (MTOW) (kg)

10500

### Crew

2

### Propulsion

2x WZ-10

### Service Ceiling (ft)

-

### Military/Afterburner Speed (kt)

165

### Cruise Speed (kt)

150

### Supercruise

No

### Ferry Range (nm)

900

### Fuel Capacity (kg)

1200

### Sensors

SAME AS Z-10ME

### Mounts

1x 30mm Gun (2A42 derivative?)
1x Chaff

### Loadout Options

- 4x 500 liter drop tank (ferry)
- 6x PL-10
- 4x PL-10, 2x 500 liter tank
- 12x TY-90
- 28x Fire Snake 70 Guided Rocket, 2x PL-10
- 28x Fire Snake 70 Guided Rocket, 4x TY-90
- 14x FS 70, 8x AKD-10, 2x PL-10
- 14x FS 70, 8x AKD-10, 4x TY-90
- 16x AKD-10, 2x PL-10
- 16x AKD-10, 4x TY-90
- 14x FS 70, 2x PL-10, 2x 500 liter tank
- 14x FS 70, 4x TY-90, 2x 500 liter tank
- 8x AKD-10, 2x PL-10, 2x 500 liter tank
- 8x AKD-10, 4x TY-90, 2x 500 liter tank
- 6x YJ-9
- 4x YJ-9, 2x PL-10
- 4x YJ-9, 4x TY-90
- 2x YJ-9, 2x PL-10, 2x 500 liter tank
- 2x YJ-9, 4x TY-90, 2x 500 liter tank

### Comments

China's first 10t MTOW heavy attack helicopter

### Sources

https://www.twz.com/land/chinas-new-heavy-attack-helicopter-spotted-for-the-first-time
https://www.sinodefenceforum.com/t/z-21-z-x-heavy-attack-helicopter.9121/

**Comment by Jkryos** [comment]
Added DB3K 506.
