### ISSUE TITLE
revert PL21 back to PL17

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4437]
### DB Selector

DB3K

### Affected DBID(s)

4110

### Summary of Changes

For some reason in DB3K v5.05 the PL17 was changed to the PL21, likely some kind of copy error.

PL21 to be changed back to PL17

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/160735116/9aaed660-8a27-4e11-8252-03fd88d559d7)

**Comment by PygmalionOfCyprus** [comment]
I went all the way back to DB 496 and Weapon 4110 has never been the PL-17, let alone "changed" for 505.

**Comment by PygmalionOfCyprus** [comment]
You may have been trying to address the problem now handled through #4045
