### ISSUE TITLE
Add Generic HF/DF

### ISSUE THREAD

**Issue by BronskyMcCloud** [PygmalionOfCyprus/cmo-db-requests#4439]
### DB Selector

DB3K

### Hypothetical

No

### Name

HF/DF (Generic)

### Facility Type

Building (Surface)

### Country

Generic

### Service

Generic

### Dispersion Radius (m)

0

### Sensors

1x Generic HF/DF

### Mounts

None

### Sources

None

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
