### ISSUE TITLE
Add: Cap D Eyama Angue Osa class ships, Equatorial-Guinea Navy 

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#444]
### DB Selector

DB3K

### Hypothetical

No

### Name

Transport Ship (AK), 106, Capitan David Eyama Angue Osa

### Class

Capitan David Eyama Angue Osa (Cargo RoRo)

### Country

Equatorial-Guinea

### Service

Navy

### In Commission

2009 - present

### Length (m)

91.45

### Beam (m)

14.7

### Draft (m)

3.7

### Standard Displacement (t)

1400

### Full Displacement (t)

4000

### Complement

Not Found

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3516HD diesels, 2 shafts

### Flank Speed (kt)

Not found

### Range (nm) at Speed (kt)

Not found

### Sensors

Delta-M navigation radars (src2)

### Mounts

1x single - 76mm/59 AK-176 
2x (2 Baryer ATGM + 1 - 30mm/100 + 1 - 7.6mm/90) Katran-M (8 Baryer), 
2x twin - 25mm/82 2M-3M, 
2x 17 - 140 BM-14-17 RL 
(all src2)

### Aircraft & Docking Facilities

1 hanger & Platform for helo,

### Comments

Build in China as ro-ro cargo vessel, ex-Salamandra. Outfitted and armed in Ukraine.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/equatorial_guinea/eqgui_ls_osa.htm
3: http://ordendebatallainternacional.blogspot.com/2013/03/guinea-ecuatorial.html
![1Posted](https://user-images.githubusercontent.com/99532490/156335844-83b86b22-8427-462c-8a11-cf604045c69b.jpg)
![2Posted](https://user-images.githubusercontent.com/99532490/156335848-e26e9553-08d7-4ed9-bff0-d1eb8ddfbf6b.jpg)
![4Posted](https://user-images.githubusercontent.com/99532490/156335851-470e8d1a-8bbe-4a95-b006-4745bd578a91.jpg)
![5Posted](https://user-images.githubusercontent.com/99532490/156335853-501119f5-4063-4866-b2d5-7dfa5415b48f.jpg)
![6Posted](https://user-images.githubusercontent.com/99532490/156335854-65ac69f0-2e63-4b7c-a377-d53d088ebccb.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus existing unit missing Katran-M Mounts. Appears fitted in reach beam outboard oif the main crane.

https://images.app.goo.gl/PWKRiJWcYiSfwHnR7

**Comment by PygmalionOfCyprus** [comment]
Fixed/added 505.
