### ISSUE TITLE
Assigning the proper sensors to the generic SIGINT station

### ISSUE THREAD

**Issue by BronskyMcCloud** [PygmalionOfCyprus/cmo-db-requests#4440]
### DB Selector

DB3K

### Affected DBID(s)

Facility 153

### Summary of Changes

- Remove Generic Comms Monitor [Advanced] (DBID 5833)
- Add Generic SIGINT (DBID 2317)

If I understand correctly, the comms monitor capability is included in the SIGINT sensor (2317).

### Sources

DB3K

**Comment by PygmalionOfCyprus** [comment]
See comment on #4441
