### ISSUE TITLE
Assigning the proper sensors to the generic COMINT station

### ISSUE THREAD

**Issue by BronskyMcCloud** [PygmalionOfCyprus/cmo-db-requests#4441]
### DB Selector

DB3K

### Affected DBID(s)

Facility 947

### Summary of Changes

This platform currently lacks any sensor.

- Add Generic COMINT (DBID 4949)

### Sources

DB3K

**Comment by PygmalionOfCyprus** [comment]
I think these are left intentionally sensorless so that scenario designers can fill them out as they like.
