### ISSUE TITLE
Add Chinese HQ-6A

### ISSUE THREAD

**Issue by BronskyMcCloud** [PygmalionOfCyprus/cmo-db-requests#4442]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Bty (HQ-6A [HQ-64, 30mm LD-2000])

### Facility Type

SAM

### Country

China

### Service

Surface-to-Air Missile Corps

### In Commission

2010-ongoing

### Dispersion Radius (m)

60

### Sensors

- 1x Mk1 Eyeball
- All other sensors are organic to specific mounts

### Mounts

- 3x 30mm China LD-2000 [Type 730]
- 3x HQ-64 TEL [Aspide, LY-60]
- 1x Vehicle [China HQ-64 Illuminator]
- 1x Vehicle [China HQ-64 Search Radar]

The HQ-6 aquisition radar can regularly be observed operating in proximity to the other battery components, therefore I think it should be organic to the DB platform.

### Magazines

1x HQ-6A Battery:
- 30x 30mm China H/PJ-12 [Type 730, 240 rnds]
- 24x HQ-64 [Aspide, LY-60N]

### Comments

- Combat System: SAM (SPAD, digital); Mast Height: 8m

- I'm aware that a pseudo-HQ-6A system can be created using existing platforms in the database and editing a number of mounts, however it would be convenient to have the SAM system as a proper platform with the right amount of launchers, radars and magazine.

- Personally, I'd suggest to use Facility_2720 - _AAA Plt (LD-2000 x 2)_ and built upon it as this platform feels a bit misrepresented since the LD-2000 system appears to always be paired with another SAM system but that will probably only create problems with existing scenarios. Just my two cents...

### Sources

Google Earth imagery

22°26'01.41" N 114°04'56.66" E

![HQ-6A Hong Kong](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/63023ced-4e56-4b28-a5bb-725fcf744d2b)

24°34'12.77" N 117°39'05.66" E

![HQ-6A Zhangzhou (1)](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/38ea8991-1369-403a-b0d9-c5ec32a8067d)

24°34'04.17" N 117°40'05.48" E

![HQ-6A Zhangzhou (2)](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/126387102/9a3f19bd-a0c9-42fc-8012-3e95e90c2ea7)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
