### ISSUE TITLE
XQ-58 Valkyrie Air-to-Air Missile Loadout

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#4443]
### DB Selector

DB3K

### User(s)

4774, 5186, 6702

### Weapons Carried

X2 AIM-120D AMRAAMs or X2 AIM-260 JATMs.
(Also, add AIM-120 Command Datalink)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

~1000nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The loadouts a likely hypothetical at this stage, and whether the "standard" is XQ-58 can carry AAMs is unknown; it may only be the future blocks of Valkyrie will have this ability.  
Unlike the other XQ-58A loadouts, these X2 AAMs are carried externally, meaning that an increase in drag (reducing range) and an increase RCS are therefore highly likely.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99649251/70a5fa62-532b-48b3-9295-5bae1b1dbbd2)

### Sources

https://www.twz.com/air/xq-58-valkyrie-drone-family-has-grown-to-five-variants

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
