### ISSUE TITLE
Copy Danish F-16AM Falcon MLU - 2020, Have Glass V Aircraft F-16 for ARGENTINA AF ? WIP

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4444]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5756 F-16 Denmark last model. DBID to follow. 

### Hypothetical

No

### Name

F-16AM Falcon MLU - 2020, Have Glass V Argentina AF 2026

### Country

Argentina 

### Service

Air Force 

### In Commission

2026 - 2030

### Number in Service

24

### Sensors

Straight copy... 

### Mounts

As copy Danish F-16.. 

### Loadout Options
Probably mostly dumb bombs etc but would await confirmation from FMS - Don't expect any long range quasi strategic standoff weapons, anything nuclear etc

### Other Changes

Not sure if Have Glass would be taken off / removed for sensitivity issues? 

### Sources

https://www.armyrecognition.com/defense_news_march_2024_global_security_army_industry/argentina_advances_air_force_with_danish_f-16_multirole_fighter_jets.html

https://twitter.com/Forsvarsmin/status/1772704061608824990?t=T60ljk-p-bBvTEHFslVIqg&s=19

Looks extremely likely given the source on X but
(WIP until I see one actually in Argentinian AF markings given how many different aircraft they have nearly bought and the state of the economy) .

**Comment by KLABDB3K** [comment]
https://twitter.com/SA_Defensa/status/1780220735014731933?t=3wbVrKI-3rQSw51yn2PG0A&s=19

AIM-9X and AIM-120D.

**Comment by KLABDB3K** [comment]
https://www.armyrecognition.com/defense_news_april_2024_global_security_army_industry/argentina_buys_24_danish_f-16_multirole_fighter_jets.html

Starting to look legit.

**Comment by tbrandon517** [comment]
Additional 

https://ukdefencejournal.org.uk/argentina-has-purchased-24-f-16-fighter-jets/?fbclid=IwZXh0bgNhZW0CMTEAAR00pRw1TWe8wajs2Lu2HVICzSmv7HNdYkYGkkm4edL8ocN75b19izPjm_o_aem_Afd1-ie-1ebGCol36gY7T5LgDB95ExdyeMgwJP-926gEttd51dGALHFBemhd0haXXD8grjlT-NKcs7Ff5vXm8UMD

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
