### ISSUE TITLE
Pirate ship in Civilian/Pirate 'Country'

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4448]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2354, 2356

### Summary of Changes

These two shps having , Pirate in name.
They are in Country 'Civilian'. There is a country 'Pirates'.
If possible migth wanna switch for scen building ease?
regards GJ

### Sources

n.v.t.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
