### ISSUE TITLE
V-247 AIM-120 Datalink Missing

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#4449]
### DB Selector

DB3K

### Affected DBID(s)

6723

### Summary of Changes

The US Navy V-247 UAV can carry X2 JSMs (loadout 32992), but this weapon now requires a AIM-120 Command / Missile Datalink [Two-Way] to fire the missile.  Therefore, please add the add Comms Link 294 to the unit. 

### Sources

DB505.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
