### ISSUE TITLE
SAM Bn (RIM-2 Terrier) - United States (Marine Corps), 1955-1960

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#445]
### DB Selector

CWDB

### Hypothetical

No

### Name

SAM Bn (RIM-2 Terrier) - United States (Marine Corps), 1955-1960

### Facility Type

SAM

### Country

United States

### Service

Marine Corps

### In Commission

1955-1960

### Crew

Not Specified 

### Dispersion Radius (m)

Not Specified 

### Sensors

Truck/Trailer mounted Terrier Search and Guidance Radars

### Mounts

Twin Arm Terrier Launchers

### Magazines

2x Reloads per magazine truck

### Aircraft & Docking Facilities

None

### Comments

With the advent of Surface-to-Air Missile (SAM) systems the Marine Corps began to re-evaluate its current force posture. 3d Defense Battalion, which was deactivated in December 1944, was reactivated as 1st Provisional Marine Guided Missile Battalion on 11 October 1951 at Naval Air Weapons Station China Lake, CA. Four years later, on 7 February 1955, the 1st Provisional Marine Guided Missile Battalion was re-designated the 1st Terrier Surface-To-Air Missile Battalion after its newly adopted primary weapon system, the  Convair RIM-2 Terrier. The USMC had two Terrier battalions equipped with specially modified twin sea launchers for land use that fired the SAM-N-7 version of the missile. The launchers were reloaded by a special vehicle that carried two Terrier reloads. The Terrier was the first surface-to-air missile operational with the USMC. On 1 June 1956 the battalion's designation was changed to the 1st Medium Anti-Aircraft Missile Battalion (1st MAAM Battalion). Even as the Terrier Missile System was being fielded the Marine Corps was aware that the system did not meet the expeditionary needs of the service. To that end, the Marine Corps was already pursuing another medium-range SAM that being developed by the Army, the MIM-23 Homing All the Way Killer (HAWK).

The U.S. Army fielded the first HAWK missiles in 1959 with the Marine Corps following suit a year later. A new weapon system meant re-designation for the Terrier Battalions, so 1st MAAM Battalion became the 3rd Light Antiaircraft Missile (LAAM) Battalion.

### Sources

https://en.wikipedia.org/wiki/History_of_ground_based_air_defense_in_the_United_States_Marine_Corps
https://www.secretprojects.co.uk/threads/u-s-marine-corps-ground-based-terrier.9026/?fbclid=IwAR2J5S0LG035g3ib_Wq5F8dcj-72rEQHL8hGoGFiZLbo8OveKVp8YVhX0U4
https://www.facebook.com/groups/57317281497/search/?q=terrier
Rockets & Missiles by Bill Gunston, p. 201, Crescent Books 1979, [ISBN] 0-517-26870-1
https://www.history.navy.mil/content/dam/nhhc/research/histories/naval-aviation/Naval%20Aviation%20News/1950/pdf/nov48.pdf
[out.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8170002/out.pdf)
[out-2.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8170003/out-2.pdf)
[Force_troops_FMF_Pac_report,_P.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8170005/Force_troops_FMF_Pac_report._P.pdf)

![download](https://user-images.githubusercontent.com/99599482/156377339-4eb60d44-eb5f-44b2-9b45-5d719f15c766.jpg)
![download](https://user-images.githubusercontent.com/99599482/156377360-869506e3-62c2-4291-aef2-d874101929d5.jpg)
![download](https://user-images.githubusercontent.com/99599482/156377383-0bdd938e-1558-456c-a4fc-9ea3d17f2003.jpg)
![download](https://user-images.githubusercontent.com/99599482/156377405-d30616d3-d144-4db3-9acc-a38160bbdf26.jpg)
![download](https://user-images.githubusercontent.com/99599482/156377438-6d65e602-dc4a-42af-8a2c-2a5a9923c7af.jpg)
![download](https://user-images.githubusercontent.com/99599482/156377479-31433ac7-ada4-485c-b9e1-5e2eefd1247e.jpg)
![download](https://user-images.githubusercontent.com/99599482/156377483-6f5dc8f9-6c3b-4e92-910c-60dd954d1489.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 496.
