### ISSUE TITLE
Ariel Decoy

### ISSUE THREAD

**Issue by Kobu7** [PygmalionOfCyprus/cmo-db-requests#4450]
### DB Selector

DB3K

### Affected DBID(s)

#427 

### Summary of Changes

Hi

I suggest reducing the Ph of this unit (Ariel Mk1) to 20% since the Ariel Mk2 has a Ph of 25%. To make it more coherent to have the two units.

Regards

### Sources

Logical

**Comment by FrangibleCover** [comment]
All towed decoys have a 25% pH, it's rather odd but I think that specifically targeting the Ariel Mk.1 is the wrong way of sorting this out. It should be part of a systematic change, possibly sorting the decoys into generational/temporal bands like jammers?

Ariel should also be on Tornado, I think? I'll have a look at that.

**Comment by PygmalionOfCyprus** [comment]
The decoys do have generations. Ariel Mk1 is Late 90s and Mk2 is Late 2000s. This should have an effect on the endgame calculations / ability to deceive weapon seekers.

**Comment by FrangibleCover** [comment]
You're quite right, it just doesn't show up in the database viewer. I also found the BOZ-107 Ariel on the Tornado 
but couldn't get it to deploy, I'll check up on if that's a bug or something else.
