### ISSUE TITLE
China, PLAAF, HQ-9BG, Terminal Anti-ballistic-missile missile

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4451]
### DB Selector

DB3K

### Baseline

weapon 3207

### Hypothetical

No

### Name

HQ-9BG

### Length (m)

same as HQ-9B

### Width/Span (m)

0.5

### Diameter (m)

0.26

### Weight (kg)

1000

### Range (nm)

2-81

### Target Altitude / Depth (ft)

30-180000

### Target Speed (kts)

0-6500kt

### Warhead

Kinetic (1 DP)

### Targets

Aircraft, Missile

### CEP (m)

1

### Sensors

1x Active Radar Seeker [Late 2010s tech]

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer, Attitude Control - Combined, Level Cruise Flight, ABM Capable

### Comments

The missile has not entered the game database since its appearance at the Zhuhai Air Show in 2022. Now information indicates that it has been in service in PLAAF air defence units.

Considering that the PLA's adversaries have also accelerated the development of tactical ballistic missiles and hypersonic weapons, the new HQ-9 series SAM may be added to the database as some kind of terminal anti-ballistic missile similar to the PAC-3 MSE.

Out of uncertainty, I categorized it as Hypo.

**Need a facility to carry it, or add to magazine of facility 3279 3280**

### Sources

https://twitter.com/Nickatgreat1220/status/1588113268744212480
https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/page-93
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/b8e93cb2-bf30-41a1-9d15-32cf3d2e777d)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/49b99135-6276-4d7d-a5c5-3ca45705fc1d)

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus Maybe, I mean MAYBE, the "Anti TBM capability" on this board refers to the missile in this ticket?
https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/page-73
![image](https://github.com/user-attachments/assets/61e6f4fa-7537-4442-81f9-7ba9d7fb1d63)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
