### ISSUE TITLE
MQ-58B Valkyrie (EW variant)

### ISSUE THREAD

**Issue by caelunshun** [PygmalionOfCyprus/cmo-db-requests#4454]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6702

### Hypothetical

Yes

### Name

MQ-58B Valkyrie (EW Variant)

### Country

United States

### Service

Marine Corps

### In Commission

Unknown

### Loadout Options

- Offensive ECM: details unknown; for now perhaps 1x AN/ALQ-249 Mid Band?

### Other Changes

If this is added, also remove the OECM loadout from the XQ-58A.

### Sources

https://ir.kratosdefense.com/news-releases/news-release-details/kratos-demonstrates-xq-58a-electronic-warfare-capabilities

https://www.twz.com/air/mq-58b-electronic-attack-enabled-version-of-valkyrie-drone-for-usmc-revealed

**Comment by PygmalionOfCyprus** [comment]
Handled 507. Not removing the EA payload from the XQ-58 because it was tested on that platform.
