### ISSUE TITLE
Weapon AS-13 Kingbolt [Kh-59] cannot be used against runways

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4456]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #1738 AS-13 Kingbolt

### Summary of Changes

According to the DB description this weapon can be used against:
![Clipboard08](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/9ed23c88-22dc-4aa2-bc12-547288d7c20a)

But when I target this weapon against a runway access point I get this message:
![Clipboard06](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/e02077db-9710-4242-bb07-5f8899ce59f9)

The missile defense value of a very large aircraft access point is 1 Harpoon/SLAM/Maverick.
A Kingbolt missile should also be able to hit a target like that as it is comparable to a Maverick.

Weather and day/night settings were off (maybe affecting the EO seeker of the missile?)

### Sources

[Bosphorus Blues (The War That Never Was) Warsaw Pact, 1989 PLANNING.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/14892989/Bosphorus.Blues.The.War.That.Never.Was.Warsaw.Pact.1989.PLANNING.zip)

Mission#3 uses the Kingbolt if you want to check.

**Comment by PygmalionOfCyprus** [comment]
Your mission WRA has the Kingbolt set not to fire at runway facilities.
