### ISSUE TITLE
China, PLAN, Type 041 Zhou-class, "Mini-Nuke" Submarine/SSK/B-N

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4457]
### DB Selector

DB3K

### Baseline

Submarine 695

### Hypothetical

No

### Name

Type 041 Zhou-class [Mini-Nuke Submarine]

### Length (m)

85

### Beam (m)

10

### Draft (m)

7

### Standard Displacement (t)

3500

### Submerged Displacement (t)

4000

### Complement

same as 039c

### Primary Propulsion Type

Nuclear

### Propulsion

AIP (or ignore this for convenience in order to make it easy to create such entry); Nuclear reactor; Li-ion battery (SSK always have battery but this time **charged by nuke reactor rather than diesel**, reasonable longer endurance than 039C)

### Flank Speed at Surface (kt)

20

### Flank Speed Submerged (kt)

25

### Range (nm) at Speed (kt)

N/A

### Range (nm) on AIP

Much longer than 039c

### Fuel Capacity (kg)

N/A

### Sensors

same as 039c

### Mounts

same as 039c but could add **8x VLS** for YJ-18 & CJ-10 & YJ-21 (Similar to ROKN KSS-III An chang-ho class, capable of Hyunmoo 4-4 SLBM)

### Magazines

same as 039c

### Comms/Datalinks

same as 039c

### sub Codes

Shock Resistant, Shrouded Propulsor, Advanced Propulsor

### Comments

- [ ] Requesting **lower noise** than type 039C (copy **Submarine 108** kalvari for example)
- [x] May create a **conventional powered version** of copy entry at the same time (if not sure about its power)

I noticed that the **nuclear submarines** in the game are **not 0 dB** noisy when at rest like the conventional submarines. If it doesn't make sense to just make it as SSN, the 041 isn't a pure nuclear submarine, its power combination we've never seen before - a nuclear reactor can either be responsible for **fueling the battery and AIP** (while the AIP in the game doesn't seem to be refueling), or it can **provide power directly**.

How to set up such an entry phase must be a bit of a hassle. "Nuclear submarines, but theoretically not THAT nuclear submarines."

### Sources

https://www.sinodefenceforum.com/t/rumoured-mini-nuke-diesel-submarine-ssk-n-thread.9091/
https://www.sinodefenceforum.com/t/rumoured-mini-nuke-diesel-submarine-ssk-n-thread.9091/page-5
https://twitter.com/horobeyo/status/1775812769058824199?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1775812769058824199%7Ctwgr%5Eca0af21bd38fab731c45a3b954566dfcac88f19d%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.sinodefenceforum.com%2Ft%2Frumoured-mini-nuke-diesel-submarine-ssk-n-thread.9091%2Fpage-5

> single hull, pump thrust, electromagnetic launch torpedo tube, compatible Fish 533 mine and YJ-18 anti-ship missile.

> Small reactor heat source +4x320KW Stirling engine total power 1715shp, underwater displacement of 2500 tons when the top speed of about 14 knots and this state noise is still very small

> The top speed refers to the top speed that does not rely on air and does not use batteries, and if the battery discharge and motor output are added, the top speed can be increased to 20 or even 25 knots in a short time.

https://twitter.com/tshugart3/status/1817535868640391258
https://www.navalnews.com/naval-news/2024/08/china-launches-its-most-sophisticated-submarine-to-date/#prettyPhoto

> The increased hull length may indicate the addition of a vertical launch system (VLS) for missiles. This is an increasingly important consideration in submarines but is less common in non-nuclear submarines which are generally smaller. The trend in non-nuclear submarines has been set by the South Korean KSS-III and Israeli Drakon Class. If this new submarine does have a VLS behind the sail it can likely accommodate between four and eight missiles, depending on their diameter.

![image](https://github.com/user-attachments/assets/2037bde7-4e0b-4a65-a9ca-3a9eaece9c31)

https://www.twz.com/sea/chinas-latest-submarine-features-x-shaped-stern

> At this stage, we can’t be certain that the lengthened hull of the new Chinese design accommodates VLS cells, but it’s certainly an intriguing possibility. VLS cells could be used to launch additional cruise missiles, for extra overall capacity, while also freeing up the torpedo tubes for their primary weapons. New types of missiles might also be better accommodated by VLS cells, perhaps even including hypersonic weapons that would likely be too large for the torpedo tubes, or potentially smaller types of ballistic missiles, as in the South Korean Dosan Ahn Changho class.  **China is already a pioneer in ship-launched ballistic missiles and it’s conceivable that such weapons could also find their way onto submarines.**

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus Fresh info:
https://x.com/CovertShores/status/1817550568845443459
https://x.com/tshugart3/status/1817535858397810714

**Comment by LuigiP57** [comment]
Or just make it a quieter (90 dB at VLF) and slightly slower nuclear sub? The submarine acoustic simulation of this game may seem a little strange (**the faster the nuclear submarine is relatively quiet, the vice versa is noisier**), but, if nothing changes, we can only **use the existing mechanism** to make it **more reasonable performance**
![image](https://github.com/user-attachments/assets/b8e4e890-744d-48a0-b51e-b6d92085ae8f)
Credit: SDF

**Comment by LuigiP57** [comment]
Or can you set this nuclear sub **0 dB noise at 0 kt - full stop**?

**Comment by LuigiP57** [comment]
https://www.twz.com/air/chinas-latest-submarine-features-x-shaped-stern

**Comment by LuigiP57** [comment]
According to the image released on the People's Liberation Army Day, we can see the VLS on the Type 032 test boat, which can apparently be placed on a Type 041 size submarine.
https://twitter.com/AlexLuck9/status/1819211532460494979/photo/1
![image](https://github.com/user-attachments/assets/d539e538-cefd-40fb-bb06-eb2cb054f273)

**Comment by LuigiP57** [comment]
May the modeling in this paper also point to type 041? They both use Sail Rudder.
https://www.sinodefenceforum.com/t/09v-09vi-095-096-nuclear-submarine-thread.8228/page-130
![image](https://github.com/user-attachments/assets/d9026f82-9ff9-4a54-afec-d3c3facc50da)

**Comment by Luigi-II** [comment]
So the US DoD also considers it a nuclear submarine. And seems to call it "Zhou-class."
https://edition.cnn.com/2024/09/26/politics/chinese-nuclear-powered-submarine-sank/index.html

> The attack submarine was the first of its new Zhou-class line of vessels, the official said, under construction at a shipyard near the city of Wuhan. The Zhou-class submarines have a distinctive X-shaped stern, designed to improve maneuverability underwater.

**Comment by Jkryos** [comment]
Added DB3K 509.
