### ISSUE TITLE
Indian Su-30MKIs Lack the Derby Command Datalink

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#4459]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5489, 5490

### Description of Problem

Both of these aircraft carry the I-Derby ER in loadout 31944. However, without the datalink, the I-Derby can not fire. 

### Recommended Fix

Add the Derby Command Datalink

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
