### ISSUE TITLE
HMS Formidable (Proposed Seaslug Conversion)

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#446]
### DB Selector

CWDB

### DBID to Copy

Ship 534 CWDB

### Hypothetical

Yes

### Name

R 67 Formidable, 1953, Proposed Missile Cruiser Conversion

### Country

United Kingdom

### Service

Royal Navy

### In Commission

1953

### Sensors

Remove all sensors from original base platform unless noted. New sensors are:

Two Type 984 Radar (CWDB Sensor 595)
One Type 960 Radar (on original platform) (CWDB Sensor 295)
One Type 992M Radar (CWDB Sensor 2260)
One Type 974 Radar (CWDB Sensor 627)
Two Type 901 Sea Slug FCR Radars (CWDB Sensor 581)
Mk 1 Eyeball (on original platform) 

### Mounts

All existing mounts on base platform removed

Two Sea Slug Mk. 1 mounts, fore and aft
Six 76mm/70 Mk.6 twin mounts, three on each broadside.

### Other Changes

Remove all aviation facilities from base platform and replace with a small helipad and open parking.
Physical dimensions, performance, and radios as per base platform (CWDB ship 534)
New designation subtype should be CG, Guided Missile Cruiser.  

### Sources

http://www.shipbucket.com/forums/viewtopic.php?t=6281

www.shipbucket.com/drawings/5960/file

**Comment by Jkryos** [comment]
Added CWDB 494.
