### ISSUE TITLE
Bangladesh F-7BGI's use PL-9C AAM instead of PL-7

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4460]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4983

### Summary of Changes

copy Loadout 2543 and update with PL-9C
Copy loadout 13297 and update with PL-9C

### Sources

https://twitter.com/DefenseDtb/status/1766339721628930276
https://en.m.wikipedia.org/wiki/File:2712_Bangladesh_Air_Force_F-7BGI._%2826222834047%29.jpg
https://fft-keymilitary.b-cdn.net/sites/militarykey/files/styles/article_body/public/imported/2020-03-26/img_84_1_0.jpg?itok=S4aP9Yd2

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
