### ISSUE TITLE
Add Bangladeshi SAM Plt (HN-5A MANPADS x 4) 1991

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4461]
### DB Selector

DB3K

### DBID to Copy

Facility 3079

### Hypothetical

Yes

### Name

SAM Plt (HN-5A MANPADS x 4)

### Country

Bangladesh

### Service

Army

### In Commission

1991

### Sources

https://en.wikipedia.org/wiki/HN-5

Sipri Arms DB Line
Bangladesh	China	1990	?	50	?	HN-5A	portable SAM	50	?	1991; 1992	New		0.05	2.5	2.5
Bangladesh	China	2000	?	21	?	HN-5A	portable SAM	21		2001	New	HN-5JA1 version	0.05	1.05	1.05

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
