### ISSUE TITLE
Add Bangladeshi RAT-31DL

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4462]
### DB Selector

DB3K

### DBID to Copy

Facility #3284

### Hypothetical

No

### Name

Radar (RAT-31DL)

### Country

Bangladesh

### Service

Airforce 

### In Commission

2020

### Number in Service

x1

### Sources

https://twitter.com/DefsecaBD/status/1276743237076529153?lang=en
https://www.janes.com/defence-news/news-detail/bangladesh-air-force-orders-leonardos-kronos-land-radar
https://en.wikipedia.org/wiki/Selex_RAT-31DL
Sipri Line
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/myky9/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/myky9/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Bangladesh | Italy | 2016 |   | 1 |   | RAT-31DL | air search radar | 1 |   | 2018 | New | BDT1.5 b ($18 m) deal | 12.5 | 12.5 | 12.5
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body>

</html>

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
