### ISSUE TITLE
Add Bangladeshi YLC-6 Radar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4464]
### DB Selector

DB3K

### DBID to Copy

Facility 2461

### Hypothetical

Yes

### Name

Radar (YLC-6M)

### Country

Bangladesh

### Service

Air Force

### In Commission

2015

### Sources

https://www.daily-sun.com/printversion/details/90183/President-inducts-Air-Defense-Radar-in-Cox%E2%80%99s-Bazar-
https://www.daily-sun.com/printversion/details/90359
https://en.wikipedia.org/wiki/YLC-6_Radar
https://www2.dgmarket.com/Notice/44009393

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
