### ISSUE TITLE
Add Bangladeshi AAA Sec 35mm/90 Type 90 x2) 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4465]
### DB Selector

DB3K

### DBID to Copy

Facility 2123

### Hypothetical

No

### Name

AAA Sec 35mm/90 Type 90 x2)

### Country

Bangladesh

### Service

Air Force

### In Commission

2024

### Mounts

Add 1682. They do have radar trucks

### Sources

https://www.janes.com/defence-news/news-detail/bangladesh-army-test-fires-csaa3-anti-aircraft-guns
https://twitter.com/DefenseDtb/status/1767400123745685906
https://twitter.com/DefenseDtb/status/1767746643536085028
https://twitter.com/DefenseDtb/status/1773310388626481586

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
