### ISSUE TITLE
Add Bangladeshi AAA Sec (35mm Twin Oerlikon) 2019

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4466]
### DB Selector

DB3K

### DBID to Copy

Facility 1091

### Hypothetical

Yes

### Name

AAA Sec (35mm Twin Oerlikon)

### Country

Bangladesh

### Service

Airforce

### In Commission

2019

### Number in Service

x3

### Other Changes

Looks like they followed this purchase by buying Chinese copies as well. Separate entry added for that.

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Bangladesh_Army
https://www.youtube.com/watch?v=XFH-yEqTCc4
Sipri Arms DB
Bangladesh	Switzerland	2017		4		GDF 35mm	anti-aircraft gun	4		2019	New	GDF-009 version; part of Skyguard air-defence system	0.75	3	3
Bangladesh	Switzerland	2017		2		Skyguard	fire control radar	2		2019	New	Skyguard-3 version for use with GDF-009 35mm AA guns	5	10	10

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
