### ISSUE TITLE
Add out of service date of 2020 to Bangladesh Frigate F 18 Osman

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4468]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2689

### Summary of Changes

Add out of service date of 2020

### Sources

https://en.wikipedia.org/wiki/BNS_Osman
https://warsearcher.com/shipsearcher/navy-of-bangladesh-current-and-retired/navy-of-bangladesh-frigates/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
