### ISSUE TITLE
Add Bangladeshi TRG-300 MLRS 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4469]
### DB Selector

DB3K

### DBID to Copy

Facility 3491

### Hypothetical

No

### Name

Arty Plt (WS-1B MLRS [TRG-300 Kasirga]

### Country

Bangladesh

### Service

Army

### In Commission

2023

### Sources

https://twitter.com/DefenseDtb/status/1771411153970937904/photo/1
https://twitter.com/clashreport/status/1620381802690142208
https://twitter.com/MilitaryBMA_BD/status/1560971581244854272

Sipri Arms DB lIne
Bangladesh	Turkiye	2019		200	?	TRG-300	guided rocket	200	?	2021; 2023	New	For T-300 MRL	0.1	20	20

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
