### ISSUE TITLE
AAA Bty (100mm KS-19 x 4, Fire Can FCR)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#447]
### DB Selector

DB3K

### DBID to Copy

facility/714/CWDB

### Hypothetical

No

### Name

AAA Bty (100mm KS-19 x 4, Fire Can FCR)

### Country

Armenia,

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494. Copied from DB3K 1814.
