### ISSUE TITLE
Add Bangladeshi (Rocketsan MBRL x6 [TRG-230])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4470]
### DB Selector

DB3K

### DBID to Copy

Facility 4025

### Hypothetical

Yes

### Name

Arty Plt (Rocketsan MBRL x6 [TRG-230])

### Country

Bangladesh

### Service

Army

### In Commission

2023

### Sources

https://twitter.com/shakirii14/status/1774066893764378912
https://twitter.com/Defense_Talks/status/1620283173547704320
https://twitter.com/shakirii14/status/1774780892713722012
https://twitter.com/DefenseDtb/status/1653247944148291587

Sipri Arms DB Line
Bangladesh	Turkiye	2020	?	500	?	TRG-230	guided rocket/ASM	500	?	2022; 2023	New	For T-300 MRL	0.06	30	30

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
