### ISSUE TITLE
Add out of service date of 2016 to Bangladeshi Frigate F 16 Umar Farooq

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4471]
### DB Selector

DB3K

### Affected DBID(s)

Ship 801

### Summary of Changes

Add out of service date of 2016 

### Sources

https://en.wikipedia.org/wiki/BNS_Umar_Farooq_(1976)
https://warsearcher.com/shipsearcher/navy-of-bangladesh-current-and-retired/navy-of-bangladesh-frigates/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
