### ISSUE TITLE
Add Bangladeshi L-901 Shah Paran [LCU-1466] 1992 x2

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4473]
### DB Selector

DB3K

### DBID to Copy

Ship 4191

### Hypothetical

No

### Name

L-901 Shah Paran [LCU-1466]

### Country

Bangladesh

### Service

Navy

### In Commission

1993

### Number in Service

x2

### Sources

https://www.navsource.org/archives/10/18/181566.htm
https://www.navsource.org/archives/10/18/181512.htm
https://warsearcher.com/shipsearcher/navy-of-bangladesh-current-and-retired/navy-of-bangladesh-landing-ships/
https://www.navypedia.org/ships/usa/us_aws_lcu1466.htm

Sipri Line
Bangladesh	United States	1991		2		LCU-1466	landing craft	2		1992	Second hand but modernized	Second-hand but modernized before delivery; Bangladeshi designation Shah Paran	3.7	7.39	7.39

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
