### ISSUE TITLE
Italian AMX retirement date 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4476]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 947

### Summary of Changes

Add out an of service date of 2024

### Sources
https://www.scramble.nl/military-news/italian-air-force-says-goodbye-to-the-amx
https://theaviationist.com/2024/04/05/the-italian-air-force-bids-farewell-to-the-amx-ghibli/
https://www.janes.com/defence-news/news-detail/italy-retires-amx-light-strike-jet#:~:text=The%20Italian%20Air%20Force%20(Aeronautica,after%2035%20years%20of%20service.
https://aviationweek.com/defense-space/aircraft-propulsion/italy-retires-long-serving-amx

**Comment by PygmalionOfCyprus** [comment]
Handled as per our routine weekly news roundup.
