### ISSUE TITLE
Omid SSM Bty actually has Arash-2

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#4479]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3748

### Description of Problem

SSM Bty (6x Omid) is actually equipped with Arash-2 launchers, not Omid. 

### Recommended Fix

Replace the Arash-2 launchers with the Omid launchers.

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
