### ISSUE TITLE
Non-ARM Arash-2 versions can not target autodetectable facilities

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#4480]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4190, 4298, 4297

### Description of Problem

Trying to manually target autodetectable facilities with these gives the error "Target is auto detectable but not radiating". Auto targeting is impossible as well. I believe that this has to do with the new rules in CMO to prevent ARMs from targeting non-radiating radars, but these aren't supposed to be ARMs.  

### Recommended Fix

Remove 'Radars' from the list of valid targets for these weapons.

**Comment by PygmalionOfCyprus** [comment]
Handled 506, the only Arash that can target "Radars" is now the one with an actual passive radar seeker.
