### ISSUE TITLE
China, CSSC, Thunderer A2000 USV

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4481]
### DB Selector

DB3K

### Baseline

ship 3390

### Hypothetical

No

### Name

Thunderer A2000

### Country

China

### Length (m)

45

### Beam (m)

10

### Draft (m)

2

### Standard Displacement (t)

280

### Complement

-

### Primary Propulsion Type

Diesel

### Propulsion

2x diesels

### Fuel Capacity (kg)

20000

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

3500 at 12kt

### Sensors

1x AESA Air Search radar (4x phases)
1x navigation radar
1x IR/LLTV/TV Camara

### Mounts

1x 8-cell VLS (FM-3000N/4x HQ-10 in one cell)
2x 24-cell Loiter munition launcher (carry CM501GA or FH-901)
1x 30mm H/PJ-17 Autocannon

### Aircraft & Docking Facilities

2x dock for smaller USV
1x deck & hangar for smaller UAV

### Ship Codes

Catamaran/Trimaran Multihull

### Comments

#4369 #4453 

### Sources

https://www.navalnews.com/event-news/wds-2024/2024/02/china-unveils-next-gen-attack-usv-thunderer-a2000-at-wds-2024/
https://twitter.com/knktlw/status/1779450025921110047/photo/1
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/2ac70ca1-e02f-4162-8a61-eb8fab45d1c2)

**Comment by PygmalionOfCyprus** [comment]
Not your fault, just a personal peeve: I fucking *hate* when Defense ReportersTM write headlines like this, where CHINA REVEALS X! No, "China" did not reveal this ship. CSSC showed off a conceptual design at a trade show. It is not in service. It is probably never going to be in service. Just because it's a state-owned company does not mean Xi Jinping personally approved this for the PLA. Gaaaaaaaaaaaaaaah.

...Can you tell I've been dealing with this a lot during this China review? XD

**Comment by LuigiP57** [comment]
> Not your fault, just a personal peeve: I fucking _hate_ when Defense ReportersTM write headlines like this, where CHINA REVEALS X! No, "China" did not reveal this ship. CSSC showed off a conceptual design at a trade show. It is not in service. It is probably never going to be in service. Just because it's a state-owned company does not mean Xi Jinping personally approved this for the PLA. Gaaaaaaaaaaaaaaah.
> 
> ...Can you tell I've been dealing with this a lot during this China review? XD

Thats why I labeled “CSSC” rather than PLAN. CHILL BRO.

**Comment by PygmalionOfCyprus** [comment]
Yeah, you did everything right. Was not directed at you. Was more a general rant at how poorly "defense reporters" (who should know better) report on all things China/PLA/etc. It's something that has become painfully clear to me during the China review. 😅
