### ISSUE TITLE
 China,PLAAF,J-16 AESA update

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4482]
### DB Selector

DB3K

### Affected DBID(s)

sensor 5485

### Summary of Changes

Improved J-16 AESA radar detection range to the level of AN/APG-82(V)1 AESA

### Sources

https://m.163.com/dy/article_cambrian/HV50N6HR05532516.html
https://www.takungpao.com/news/232108/2024/0115/933318.html

**Comment by yU2187sie** [comment]
![QQ截图20240415174959](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/13c1c688-05d9-4536-8dd2-7ce7f792b8b8)
![QQ截图20240415175042](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/3b42eed5-d577-4f8e-9a8d-151d2bc03135)

**Comment by LuigiP57** [comment]
> ![QQ截图20240415174959](https://private-user-images.githubusercontent.com/130222813/322434978-13c1c688-05d9-4536-8dd2-7ce7f792b8b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTA4NzIsIm5iZiI6MTcxMzE5MDU3MiwicGF0aCI6Ii8xMzAyMjI4MTMvMzIyNDM0OTc4LTEzYzFjNjg4LTA1ZDktNDUzNi04ZGQyLTdjZTdmNzkyYjhiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDE2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGVlMzY1OWZmZjQ2NDdkY2I5NTk3MWViY2MyM2MzMDUzNzAxODEzMzIwNTEyYTM0NTk0ZDY3NjMzZjQ5ZDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8YsMPoqIvWWoTjZP50jkpGDTA4utrrDCpUosGMXmvy0) ![QQ截图20240415175042](https://private-user-images.githubusercontent.com/130222813/322435048-3b42eed5-d577-4f8e-9a8d-151d2bc03135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTA4NzIsIm5iZiI6MTcxMzE5MDU3MiwicGF0aCI6Ii8xMzAyMjI4MTMvMzIyNDM1MDQ4LTNiNDJlZWQ1LWQ1NzctNGY4ZS05YThkLTE1MWQyYmMwMzEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDE2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDZiZDgxMWM5OGNjMmZlYzUyZWFiMzE2MDg3OWEwN2IwOThkMjRlODY4NjliMTNiZGJhZGI4NzBmN2ZlNzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OvfEeIB86DAeu2xeQUCjYeFScb7IR3KUoDy4-LO78mg)

“1560km”......Hmm......Is this a translation software error? 

Also, the F-22 RCS number quoted by this source may make some of our American friends here unhappy. : )

**Comment by yU2187sie** [comment]
Yes, there is a problem with the translation software I am using, I am sorry for this situation, the text should be corrected to: 

"**The J-16's gallium nitride fire control radar has a detection range of 400 km against typical fighter targets (RCS=3m')Inside. Therefore, after the gallium nitride fire control radar is equipped,  it can solve the problem of J-16 against F22 and F35 to a large extent.And even the detection of B21.**"

**Comment by HunterDNiu** [comment]
> > ![QQ截图20240415174959](https://private-user-images.githubusercontent.com/130222813/322434978-13c1c688-05d9-4536-8dd2-7ce7f792b8b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTA4NzIsIm5iZiI6MTcxMzE5MDU3MiwicGF0aCI6Ii8xMzAyMjI4MTMvMzIyNDM0OTc4LTEzYzFjNjg4LTA1ZDktNDUzNi04ZGQyLTdjZTdmNzkyYjhiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDE2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGVlMzY1OWZmZjQ2NDdkY2I5NTk3MWViY2MyM2MzMDUzNzAxODEzMzIwNTEyYTM0NTk0ZDY3NjMzZjQ5ZDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8YsMPoqIvWWoTjZP50jkpGDTA4utrrDCpUosGMXmvy0) ![QQ截图20240415175042](https://private-user-images.githubusercontent.com/130222813/322435048-3b42eed5-d577-4f8e-9a8d-151d2bc03135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTA4NzIsIm5iZiI6MTcxMzE5MDU3MiwicGF0aCI6Ii8xMzAyMjI4MTMvMzIyNDM1MDQ4LTNiNDJlZWQ1LWQ1NzctNGY4ZS05YThkLTE1MWQyYmMwMzEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDE2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDZiZDgxMWM5OGNjMmZlYzUyZWFiMzE2MDg3OWEwN2IwOThkMjRlODY4NjliMTNiZGJhZGI4NzBmN2ZlNzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OvfEeIB86DAeu2xeQUCjYeFScb7IR3KUoDy4-LO78mg)
> 
> “1560km”......Hmm......Is this a translation software error?
> 
> Also, the F-22 RCS number quoted by this source may make some of our American friends here unhappy. : )

Original says "increased to 150-160 km". But both pieces appears like blatant propaganda tho

**Comment by PygmalionOfCyprus** [comment]
Yeah, I'm with DNiu on this one: I think this is gobbledegook, even if you discount the laughable claims of the J-16 being able to render the B-21, etc. useless. We're gonna need a more reputable source.
