### ISSUE TITLE
China,PLAGF,PCL-181 Self-Propelled Howitzer

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4483]
### DB Selector

DB3K

### Hypothetical

No

### Name

Arty Bty (155mm/52 PCL-181 Self-Propelled Howitzer x 6)

### Facility Type

Arty

### Country

China

### Service

Army

### In Commission

2018

### Number in Service

50+

### Dispersion Radius (m)

40

### Sensors

1x Mk1 Eyeball
6x Generic Binoculars

### Mounts

6x 155mm/52 PCL-181 Self-Propelled Howitzer

### Magazines

20x 12.7mm/50 MG Burst [10 rnds]
0x 155mm/52 ERFB PCL-181
0x 155mm/52 ERFB-BB-RA  PCL-181
30x 155mm/52 HE PCL-181
0x 155mm/52 KM-1M Krasnopol

### Sources

https://en.wikipedia.org/wiki/PCL-181
https://twitter.com/TheDeadDistrict/status/1416819071056846855
https://twitter.com/rajfortyseven/status/1283229820210442241
![EohApqnVgAERYi2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/a1e3913f-5651-4554-9593-d8266ca28e7d)
![Fu5lmPLWAAYMhrs](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/95c55e4d-27f8-44fb-a6ba-69f634b7725b)

**Comment by bostonmyk** [comment]
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4039

**Comment by yU2187sie** [comment]
🤣
