### ISSUE TITLE
China, PLAAF, CH-AS-X-13 ASBM, sensor tech level

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4485]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3565

### Summary of Changes

update its sensor tech to Late 2010s

### Sources

No need (or it is a weapon that entered the PLAAF in the Late 2010s). It should have been taken care of when I proposed the DF-26/27 sensor tickets, but I slipped up.

**Comment by Jkryos** [comment]
Updated DB3K 506.
