### ISSUE TITLE
PLA Information Support Force

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4486]
On April 9 China disbanded the Strategic Support Force (PLASSF) and established the Information Support Force (PLAISF), the Aerospace and Cyberspace divisions of the SSF are now independent forces under PLACMC, co-equal with Joint Logistical Force and ISF. 

> Transfer all SSF units to Aerospace Force. 

https://web.archive.org/web/20240419114117/http://www.chinaview.cn/20240419/47d811f0ed014225a9ee2ed977298740/c.html
https://web.archive.org/web/20240419122229/https://www.gov.cn/yaowen/liebiao/202404/content_6946295.htm
https://www.zaobao.com.sg/realtime/china/story20240419-3471221

**Comment by LuigiP57** [comment]
Then what about PLA Aerospace Force and Cyberspace Force?

**Comment by HunterDNiu** [comment]
> Then what about PLA Aerospace Force and Cyberspace Force?

Sorry I only read the initial announcement and turned out the "军事航天部队" Military Space Force is now in charge of space assets.
