### ISSUE TITLE
Aircraft Hawk Mk.132 Indian AF/Navy 2009

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4487]
### DB Selector

DB3K

### DBID to Copy

Aircraft Hawk Mk.127 LIFT any armed late model Hawk. 

### Hypothetical

No

### Name

Hawk Mk. 132 Indian AF/Navy 90+ 2009

### Country

India

### Service

Air Force and Navy 

### In Commission

2009

### Number in Service

90+

### Sensors

Doesn't appear to have anything but RWR despite chisel nose. 

### Mounts

None appear integral. 

### Loadout Options

30mm ADEN Gun pod.
2 x Magic Mk.2 AAM* Appears rarely used . 
2 x Drop tanks 190 Imp Gal. 
Later upgrade 2017.
30mm ADEN Gun pod. 
4 x ASRAAM - wingtip pylon. 
2 x Drop tanks. 

LR 
2 x Mk.13 1000lb GPB *
2 x Drop tanks 190 Imp Gal. 

2 x 68mm SNEB 18 rocket. 
2 x Drop tanks 190 Imp Gal. 

SR
4 x 68mm SNEB 18 rocket* Appears rarely used .  

4 x Mk.13 1000lb GPB* Appears rarely used . 

Ferry. 

Training. 

### Other Changes

Has a definite war role although primarily for training. 

### Sources

https://twitter.com/_devildog_rv_/status/1434844257097961474?t=nnMQ9EZ0QTemEPbehEZFLA&s=19 Magic.
https://twitter.com/IAF_MCC/status/1522041614478180352?t=F7AIcC-2jYKlNlXeLu0veA&s=19
SNEB

https://medium.com/@AirPra/scout-the-best-of-the-iaf-hawk-mk-132-advanced-trainer-95c0a764057e

Airshow stock footage from Alamy shows Hawk with arms laid out in front of 2 x 1000lb UK Mk13(?) GP bombs plus various SNEB and practice bombs.

**Comment by FrangibleCover** [comment]
I want to clarify on the UK 1000lb bombs, as covered in #3456 

All British 1000lb bombs are more or less the same, except the Mk.18 which is fitted with the retarded tail. Most of them are redundant weapons that are also unused in any loadout, which means that it will be relatively little work to rationalise the multiple bombs in the DB into only two types: Ballistic and Retarded. Therefore, please don't use the Mk.17 bomb on this aircraft, use the Mk.13 that most aircraft use.

**Comment by KLABDB3K** [comment]
Amended to Mk.13, thanks. 
It is essentially just a low drag dumb bomb and Mk13 matches the Indian Jaguar loadouts.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
