### ISSUE TITLE
Facility #833 Kolchuga ELINT for Ethiopia

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4489]
### DB Selector

DB3K

### DBID to Copy

Facility #833 

### Hypothetical

No

### Name

Vehicle (Kolchuga ELINT) (Ethiopia)

### Country

Ethiopia

### Service

Air Defense

### In Commission

2022

### Number in Service

3

### Sources

[https://twitter.com/HammerOfWar5/status/1606715876237099010](url)
[https://twitter.com/HammerOfWar5/status/1606715888186662914](url)
[https://armstransfers.sipri.org/ArmsTransfer/TransferData/transferResults?logic=on](url)

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/e31db3bd-15ac-46bc-af41-c7d4788a0081)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
