### ISSUE TITLE
Radar AN/TPY-4 for Norway

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4490]
### DB Selector

DB3K

### DBID to Copy

Facility # 3660 Radar AN/TPY-4

### Hypothetical

No

### Name

Radar AN/TPY-4 (Norway - 2024)

### Country

Norway

### Service

Air Force

### In Commission

2024?

### Number in Service

8=3 additional= 11

### Other Changes

Replacement of RAT-31

### Sources

[https://twitter.com/AirPowerNEW1/status/1655415682341953537](url)
[https://twitter.com/AirPowerNEW1/status/1768116572843868520](url)
[https://www.janes.com/defence-news/c4isr-command-tech/latest/norway-exercises-option-for-additional-tpy-4-radars](url)
[https://twitter.com/KwasekTomasz/status/1767653106592989623](url)

**Comment by HunterDNiu** [comment]
#3594

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
