### ISSUE TITLE
#6344 - Hawk 61 (UAE - 1983) Loadout amendments. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4491]
### DB Selector

DB3K

### Affected DBID(s)

AIRCRAFT #6344 - Hawk 61 (UAE - 1983) Loadout amendments. 

### Summary of Changes

Loadout error with AAM's.
Remove Loadout 31546 A/A: PL-7 [R.550 Magic 1] (Air Superiority, WVR AAMs) -- this was a unique expedient for Zimbabwe's Hawks.
Add Loadout A/A: AIM-9L  [1401 - AIM-9L Sidewinder] (Air Superiority, WVR AAMs) 2 X AIM-9L 30mm Aden pod and 2 x 190 Imp Gal drop tanks.
UAE has not ever used the PL-7 and images all show AIM-9L/M in use on Hawk 61. 
Also not sure the generic 250kg bomb load out shouldn't be a US Mk82 load out instead? 

### Sources

https://www.dstorm.eu/pictures/nose-arts/hawk/uae/1004_1.jpg - generic loads at airshow.
They do already have a weapons capability and the use of the PL-7 is erroneous - appears a glitch.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
