### ISSUE TITLE
Add Human Traff Smuggler; Inflatable boat

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4492]
### DB Selector

DB3K

### DBID to Copy

Ship 2552

### Hypothetical

No

### Name

Smuggler Humans Inflatable Boat

### Country

Smugglers

### Service

Human Trafficking

### In Commission

- present

### Other Changes

Propulsion is outboard engine.
Troops = 150

Took Ship 2552 as base for parametrics.

### Sources

https://safety4sea.com/human-trafficking-in-the-andaman-sea-on-the-rise
https://www.dailysabah.com/africa/2019/11/06/nigerian-women-victims-of-human-trafficking-in-europe
https://dailytrust.com/egypt-passes-law-to-curb-europe-bound-human-trafficking

**Comment by PygmalionOfCyprus** [comment]
See #4503
