### ISSUE TITLE
Add Human Traff Smuggler; small boat

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4493]
### DB Selector

DB3K

### DBID to Copy

Ship 1789

### Hypothetical

No

### Name

Smuggler Humans Small Boat

### Country

Smugglers

### Service

Human Trafficking

### In Commission

- present

### Other Changes

Troops = 25
Propulsion is outboard enging
Much slower max speed

### Sources

https://theconversation.com/why-experts-fear-the-eus-new-migration-laws-could-lead-to-more-deaths-at-sea-227988
https://www.opendemocracy.net/en/beyond-trafficking-and-slavery/theres-no-human-trafficking-or-migrant-smuggling-without-organised-crime-the-law-says-and-that-matters
https://worldcrunch.com/migrant-lives-1/who-are-the-migrant-smugglers

**Comment by PygmalionOfCyprus** [comment]
See #4503
