### ISSUE TITLE
Add Human Traff Smuggler; Dhow

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4494]
### DB Selector

DB3K

### DBID to Copy

Ship 1787

### Hypothetical

No

### Name

Smuggler Humans Dhow

### Country

Smugglers

### Service

Human Trafficking

### In Commission

- present

### Other Changes

Troops = 200

Estimations.

### Sources

https://www.cairopeacekeeping.org/combating
https://www.brecorder.com/news/40266714
https://www.nevispages.com/government-of-st-kitts-and-nevis-vows-to-clamp-down-on-human-smuggling

**Comment by PygmalionOfCyprus** [comment]
See #4503
