### ISSUE TITLE
Aircraft #6345 - Hawk 103 (UAE - 1993) Loadout updates armament options. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4495]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #6345 - Hawk 103 (UAE - 1993) Loadout updates armament options. 

### Summary of Changes

Although primarily trainers these do have an armed role and capability:

Add armed loadouts;
A/A: AIM-9L Sidewinder (Air Superiority, WVR AAMs) 4x AIM-9L Sidewinder 2x 190 ImpG Drop Tank
A/A: AIM-9L Sidewinder (Air Superiority, WVR AAMs) 2x AIM-9L Sidewinder 2x 190 ImpG Drop Tank 1 x 30mm ADEN pod
Mk82 LDGP, Short-Range (Strike, Land/Naval) 4x Mk82 500lb LDGP 2x AIM-9L Sidewinder
Mk82 LDGP (Strike, Land/Naval) 2x Mk82 500lb LDGP 2x 190 ImpG Drop Tank 2x AIM-9L Sidewinder
HYDRA 70mm Rockets (Strike, Land/Naval) 38x HYDRA 70mm Rocket 2x 190 ImpG Drop Tank 2x AIM-9L Sidewinder
HYDRA 70mm Rockets, Short-Range (Strike, Land/Naval 76x HYDRA 70mm Rocket 2x AIM-9L Sidewinder

### Sources

https://www.militaryimages.net/media/hawk-uae-air-force.29604/ image has training bomblet pod. 
https://th.bing.com/th/id/OIP.18Cp4aNScL5m1FsEvmGhwAHaFA?rs=1&pid=ImgDetMain 
30mm ADEN pod AIM-9L/M on wingtip pods and training bomb?
https://staticalayam24.mcdn.ma/uploads/1515703884.jpg in flight with AIM-9L
https://en.wikipedia.org/wiki/BAE_Systems_Hawk#cite_note-WAPJ22_p103-117

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
