### ISSUE TITLE
Aircraft #2493 #5856 - Z-10 Fierce Thunderbolt (China - 2012 AND 2020 ) loadout A/A: PL-9 (Intercept, WVR AAMs) is using the ground launched PL-9C SAM in error. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4496]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #2493 Aircraft #5856

### Summary of Changes

Aircraft #2493 #5856 - Z-10 Fierce Thunderbolt (China - 2012/2020) loadout 30152 A/A: PL-9 (Intercept, WVR AAMs) is using 4 x PL-9C #542 SAM - PL-9C in error, this is the ground launched variant,
Change to 4 x AAM #3301 - PL-9
PL-9C load out wont launch due to launch speed.

 *Personally I doubt the Z-10 is using three different types of AAM , maybe the PL-9 but to also to be routinely carrying the obsolete PL-7 or PL-5e seems a bit of an airshow export advertising opportunity not an operational use?

### Sources

DB3k 505 itself - wrong weapon record used.

**Comment by Jkryos** [comment]
Updated DB3K 506.

**Comment by K1l0tangoDef3nce** [comment]
2023-2024.🌱🌿Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.2023-2024.🌱🌿Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.2023-2024.🌱🌿2023-2024.🌱🌿2023-2024.🌱🌿Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.2023-2024.🌱🌿202320232023-2024.🌱🌿Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.2023Το 1ο  Ειδικό Δημοτικό Σχολείο Αχαρνών λαμβάνει μέρος στον Εθνικό και Διεθνή Διαγωνισμό άρθρου, φωτογραφίας, βίντεο Δίκτυο ΠΕ «Νέοι Δημοσιογράφοι για το Περιβάλλον», 2023-2024.🌱🌿Η συμμετοχή είναι φωτογραφία/ ρεπορτάζ και αφορά τις πυρκαγιές στην περιοχή της Πάρνηθας. Η Συμμετοχή μας έχει τον τίτλο: "Η μοναξιά μετά τη φωτιά και η ελπίδα της αναγέννησης (αναδάσωση)"Τέσσερα δέντρα στέκουν ακόμα μόνα και καμένα, έπειτα από τις πυρκαγιές που ξέσπασαν το καλοκαίρι του 2023 στην δασική περιοχή της Πάρνηθας. Αυτή είναι η εικόνα που συναντάνε οι επισκέπτες της περιοχής.  Με φόντο την πόλη της Αθήνας και τον γαλάζιο ουρανό, ο άλλοτε ¨πνεύμονας πρασίνου¨ της Αττικής, στέκει λειψός και καμένος. Ελπίζει στην ανθρώπινη παρέμβαση, μιας και αυτή προκάλεσε την καταστροφή. Ελπίζει στην αναγέννηση του και στην αναδάσωση, ώστε να αποκτήσει την παλαιά του ομορφιά και ζωντάνια. Το ίδιο ελπίζουμε και εμείς οι μαθητές του 1ου Ειδικού Δημοτικού Σχολείου Αχαρνών, ώστε η περιοχή της Πάρνηθας να παραμείνει αυτός ο ζωτικός ¨πνεύμονας¨. Σε μια πόλη που το καυσαέριο μας πνίγει, δεν επιτρέπεται να καίμε την ανάσα μας. ΜΑΘΗΤΕΣ ΣΤ1 & ΣΤ41ο ΕΙΔΙΚΟ Δ.Σ. ΑΧΑΡΝΩΝΚαλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.2023-2024.🌱🌿2023-2024.🌱🌿2023-2024.🌱🌿Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.202320232023Το 1ο  Ειδικό Δημοτικό Σχολείο Αχαρνών λαμβάνει μέρος στον Εθνικό και Διεθνή Διαγωνισμό άρθρου, φωτογραφίας, βίντεο Δίκτυο ΠΕ «Νέοι Δημοσιογράφοι για το Περιβάλλον», 2023-2024.🌱🌿Η συμμετοχή είναι φωτογραφία/ ρεπορτάζ και αφορά τις πυρκαγιές στην περιοχή της Πάρνηθας. Η Συμμετοχή μας έχει τον τίτλο: "Η μοναξιά μετά τη φωτιά και η ελπίδα της αναγέννησης (αναδάσωση)"Τέσσερα δέντρα στέκουν ακόμα μόνα και καμένα, έπειτα από τις πυρκαγιές που ξέσπασαν το καλοκαίρι του 2023 στην δασική περιοχή της Πάρνηθας. Αυτή είναι η εικόνα που συναντάνε οι επισκέπτες της περιοχής.  Με φόντο την πόλη της Αθήνας και τον γαλάζιο ουρανό, ο άλλοτε ¨πνεύμονας πρασίνου¨ της Αττικής, στέκει λειψός και καμένος. Ελπίζει στην ανθρώπινη παρέμβαση, μιας και αυτή προκάλεσε την καταστροφή. Ελπίζει στην αναγέννηση του και στην αναδάσωση, ώστε να αποκτήσει την παλαιά του ομορφιά και ζωντάνια. Το ίδιο ελπίζουμε και εμείς οι μαθητές του 1ου Ειδικού Δημοτικού Σχολείου Αχαρνών, ώστε η περιοχή της Πάρνηθας να παραμείνει αυτός ο ζωτικός ¨πνεύμονας¨. Σε μια πόλη που το καυσαέριο μας πνίγει, δεν επιτρέπεται να καίμε την ανάσα μας. ΜΑΘΗΤΕΣ ΣΤ1 & ΣΤ41ο ΕΙΔΙΚΟ Δ.Σ. ΑΧΑΡΝΩΝΚαλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.2023Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.2023-2024.🌱🌿2023-2024.🌱🌿2023-2024.🌱🌿2023-2024.🌱🌿Το 1ο  Ειδικό Δημοτικό Σχολείο Αχαρνών λαμβάνει μέρος στον Εθνικό και Διεθνή Διαγωνισμό άρθρου, φωτογραφίας, βίντεο Δίκτυο ΠΕ «Νέοι Δημοσιογράφοι για το Περιβάλλον», 2023-2024.🌱🌿Η συμμετοχή είναι φωτογραφία/ ρεπορτάζ και αφορά τις πυρκαγιές στην περιοχή της Πάρνηθας. Η Συμμετοχή μας έχει τον τίτλο: "Η μοναξιά μετά τη φωτιά και η ελπίδα της αναγέννησης (αναδάσωση)"Τέσσερα δέντρα στέκουν ακόμα μόνα και καμένα, έπειτα από τις πυρκαγιές που ξέσπασαν το καλοκαίρι του 2023 στην δασική περιοχή της Πάρνηθας. Αυτή είναι η εικόνα που συναντάνε οι επισκέπτες της περιοχής.  Με φόντο την πόλη της Αθήνας και τον γαλάζιο ουρανό, ο άλλοτε ¨πνεύμονας πρασίνου¨ της Αττικής, στέκει λειψός και καμένος. Ελπίζει στην ανθρώπινη παρέμβαση, μιας και αυτή προκάλεσε την καταστροφή. Ελπίζει στην αναγέννηση του και στην αναδάσωση, ώστε να αποκτήσει την παλαιά του ομορφιά και ζωντάνια. Το ίδιο ελπίζουμε και εμείς οι μαθητές του 1ου Ειδικού Δημοτικού Σχολείου Αχαρνών, ώστε η περιοχή της Πάρνηθας να παραμείνει αυτός ο ζωτικός ¨πνεύμονας¨. Σε μια πόλη που το καυσαέριο μας πνίγει, δεν επιτρέπεται να καίμε την ανάσα μας. ΜΑΘΗΤΕΣ ΣΤ1 & ΣΤ41ο ΕΙΔΙΚΟ Δ.Σ. ΑΧΑΡΝΩΝ2023-2024.🌱🌿2023-2024.🌱🌿20232023Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.2023Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.20232023Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Καλώς ορίσατε στο πρόχειρο του Gboard, εδώ θα γίνεται επικόλληση τυχόν κειμένου που αντιγράφετε.Το 1ο  Ειδικό Δημοτικό Σχολείο Αχαρνών λαμβάνει μέρος στον Εθνικό και Διεθνή Διαγωνισμό άρθρου, φωτογραφίας, βίντεο Δίκτυο ΠΕ «Νέοι Δημοσιογράφοι για το Περιβάλλον», 2023-2024.🌱🌿Η συμμετοχή είναι φωτογραφία/ ρεπορτάζ και αφορά τις πυρκαγιές στην περιοχή της Πάρνηθας. Η Συμμετοχή μας έχει τον τίτλο: "Η μοναξιά μετά τη φωτιά και η ελπίδα της αναγέννησης (αναδάσωση)"Τέσσερα δέντρα στέκουν ακόμα μόνα και καμένα, έπειτα από τις πυρκαγιές που ξέσπασαν το καλοκαίρι του 2023 στην δασική περιοχή της Πάρνηθας. Αυτή είναι η εικόνα που συναντάνε οι επισκέπτες της περιοχής.  Με φόντο την πόλη της Αθήνας και τον γαλάζιο ουρανό, ο άλλοτε ¨πνεύμονας πρασίνου¨ της Αττικής, στέκει λειψός και καμένος. Ελπίζει στην ανθρώπινη παρέμβαση, μιας και αυτή προκάλεσε την καταστροφή. Ελπίζει στην αναγέννηση του και στην αναδάσωση, ώστε να αποκτήσει την παλαιά του ομορφιά και ζωντάνια. Το ίδιο ελπίζουμε και εμείς οι μαθητές του 1ου Ειδικού Δημοτικού Σχολείου Αχαρνών, ώστε η περιοχή της Πάρνηθας να παραμείνει αυτός ο ζωτικός ¨πνεύμονας¨. Σε μια πόλη που το καυσαέριο μας πνίγει, δεν επιτρέπεται να καίμε την ανάσα μας. ΜΑΘΗΤΕΣ ΣΤ1 & ΣΤ41ο ΕΙΔΙΚΟ Δ.Σ. ΑΧΑΡΝΩΝΤο 1ο  Ειδικό Δημοτικό Σχολείο Αχαρνών λαμβάνει μέρος στον Εθνικό και Διεθνή Διαγωνισμό άρθρου, φωτογραφίας, βίντεο Δίκτυο ΠΕ «Νέοι Δημοσιογράφοι για το Περιβάλλον», 2023-2024.🌱🌿Η συμμετοχή είναι φωτογραφία/ ρεπορτάζ και αφορά τις πυρκαγιές στην περιοχή της Πάρνηθας. Η Συμμετοχή μας έχει τον τίτλο: "Η μοναξιά μετά τη φωτιά και η ελπίδα της αναγέννησης (αναδάσωση)"Τέσσερα δέντρα στέκουν ακόμα μόνα και καμένα, έπειτα από τις πυρκαγιές που ξέσπασαν το καλοκαίρι του 2023 στην δασική περιοχή της Πάρνηθας. Αυτή είναι η εικόνα που συναντάνε οι επισκέπτες της περιοχής.  Με φόντο την πόλη της Αθήνας και τον γαλάζιο ουρανό, ο άλλοτε ¨πνεύμονας πρασίνου¨ της Αττικής, στέκει λειψός και καμένος. Ελπίζει στην ανθρώπινη παρέμβαση, μιας και αυτή προκάλεσε την καταστροφή. Ελπίζει στην αναγέννηση του και στην αναδάσωση, ώστε να αποκτήσει την παλαιά του ομορφιά και ζωντάνια. Το ίδιο ελπίζουμε και εμείς οι μαθητές του 1ου Ειδικού Δημοτικού Σχολείου Αχαρνών, ώστε η περιοχή της Πάρνηθας να παραμείνει αυτός ο ζωτικός ¨πνεύμονας¨. Σε μια πόλη που το καυσαέριο μας πνίγει, δεν επιτρέπεται να καίμε την ανάσα μας. ΜΑΘΗΤΕΣ ΣΤ1 & ΣΤ41ο ΕΙΔΙΚΟ Δ.Σ. ΑΧΑΡΝΩΝΤο 1ο  Ειδικό Δημοτικό Σχολείο Αχαρνών λαμβάνει μέρος στον Εθνικό και Διεθνή Διαγωνισμό άρθρου, φωτογραφίας, βίντεο Δίκτυο ΠΕ «Νέοι Δημοσιογράφοι για το Περιβάλλον», 2023-2024.🌱🌿Η συμμετοχή είναι φωτογραφία/ ρεπορτάζ και αφορά τις πυρκαγιές στην περιοχή της Πάρνηθας. Η Συμμετοχή μας έχει τον τίτλο: "Η μοναξιά μετά τη φωτιά και η ελπίδα της αναγέννησης (αναδάσωση)"Τέσσερα δέντρα στέκουν ακόμα μόνα και καμένα, έπειτα από τις πυρκαγιές που ξέσπασαν το καλοκαίρι του 2023 στην δασική περιοχή της Πάρνηθας. Αυτή είναι η εικόνα που συναντάνε οι επισκέπτες της περιοχής.  Με φόντο την πόλη της Αθήνας και τον γαλάζιο ουρανό, ο άλλοτε ¨πνεύμονας πρασίνου¨ της Αττικής, στέκει λειψός και καμένος. Ελπίζει στην ανθρώπινη παρέμβαση, μιας και αυτή προκάλεσε την καταστροφή. Ελπίζει στην αναγέννηση του και στην αναδάσωση, ώστε να αποκτήσει την παλαιά του ομορφιά και ζωντάνια. Το ίδιο ελπίζουμε και εμείς οι μαθητές του 1ου Ειδικού Δημοτικού Σχολείου Αχαρνών, ώστε η περιοχή της Πάρνηθας να παραμείνει αυτός ο ζωτικός ¨πνεύμονας¨. Σε μια πόλη που το καυσαέριο μας πνίγει, δεν επιτρέπεται να καίμε την ανάσα μας. ΜΑΘΗΤΕΣ ΣΤ1 & ΣΤ41ο ΕΙΔΙΚΟ Δ.Σ. ΑΧΑΡΝΩΝΤο 1ο  Ειδικό Δημοτικό Σχολείο Αχαρνών λαμβάνει μέρος στον Εθνικό και Διεθνή Διαγωνισμό άρθρου, φωτογραφίας, βίντεο Δίκτυο ΠΕ «Νέοι Δημοσιογράφοι για το Περιβάλλον», 2023-2024.🌱🌿Η συμμετοχή είναι φωτογραφία/ ρεπορτάζ και αφορά τις πυρκαγιές στην περιοχή της Πάρνηθας. Η Συμμετοχή μας έχει τον τίτλο: "Η μοναξιά μετά τη φωτιά και η ελπίδα της αναγέννησης (αναδάσωση)"Τέσσερα δέντρα στέκουν ακόμα μόνα και καμένα, έπειτα από τις πυρκαγιές που ξέσπασαν το καλοκαίρι του 2023 στην δασική περιοχή της Πάρνηθας. Αυτή είναι η εικόνα που συναντάνε οι επισκέπτες της περιοχής.  Με φόντο την πόλη της Αθήνας και τον γαλάζιο ουρανό, ο άλλοτε ¨πνεύμονας πρασίνου¨ της Αττικής, στέκει λειψός και καμένος. Ελπίζει στην ανθρώπινη παρέμβαση, μιας και αυτή προκάλεσε την καταστροφή. Ελπίζει στην αναγέννηση του και στην αναδάσωση, ώστε να αποκτήσει την παλαιά του ομορφιά και ζωντάνια. Το ίδιο ελπίζουμε και εμείς οι μαθητές του 1ου Ειδικού Δημοτικού Σχολείου Αχαρνών, ώστε η περιοχή της Πάρνηθας να παραμείνει αυτός ο ζωτικός ¨πνεύμονας¨. Σε μια πόλη που το καυσαέριο μας πνίγει, δεν επιτρέπεται να καίμε την ανάσα μας. ΜΑΘΗΤΕΣ ΣΤ1 & ΣΤ41ο ΕΙΔΙΚΟ Δ.Σ. ΑΧΑΡΝΩΝ2023Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Χρησιμοποιήστε το εικονίδιο επεξεργασίας για να καρφιτσώσετε, να προσθέσετε ή να διαγράψετε αποσπάσματα.Χρησιμοποιήστε το εικονίδιο επεξεργασίας για να καρφιτσώσετε, να προσθέσετε ή να διαγράψετε αποσπάσματα.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Χρησιμοποιήστε το εικονίδιο επεξεργασίας για να καρφιτσώσετε, να προσθέσετε ή να διαγράψετε αποσπάσματα.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Πατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.Χρησιμοποιήστε το εικονίδιο επεξεργασίας για να καρφιτσώσετε, να προσΠατήστε σε κάποιο απόσπασμα για να το επικολλήσετε στο πλαίσιο κειμένου.θέσετε ή να διαγράψετε αποσπάσματα.Στις 24 Απρ 2024 7:33 μ.μ., ο χρήστης Jacob Keyes ***@***.***> έγραψε:
Closed #4496 as completed.
