### ISSUE TITLE
Iran - P-3F Orion - Harpoon Capable

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4497]
### DB Selector

Both

### DBID to Copy

DB3K aircraft 848 and CWDB aircraft 2339

### Hypothetical

No

### Name

P-3F Orion Harpoon Capable 1x

### Country

Iran

### Service

Air Force

### In Commission

1978-1985

### Number in Service

1x

### Sensors

No Change 

### Mounts

No Change 

### Loadout Options

Add

AGM-84A Harpooon loadout as used on CWDB aircraft 2899 and DB3K aircraft 293

### Other Changes

Looks like Iran had one P-3F that was harpoon capable. Got certified 1978 and went back to Iran with 18 Harpoon A missiles. Was in service until a crash in February, 1985.

### Sources

https://twitter.com/Kobaz4/status/1314212799451557889
https://twitter.com/Kobaz4/status/1314212809635291140

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/631164ce-b8cf-4757-86f9-d215e9c2d053)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/c1b9b61b-87b6-4dd3-8d0a-382151095140)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/c93ae3f6-a70f-44cb-860a-1ec2d44025a1)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99599482/8a19aebf-0bf9-4a2f-9a45-5fb981097495)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
