### ISSUE TITLE
More PLANAF J-15/J-15B carrier based fighters' air-to-surface loadouts

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4499]
### DB Selector

DB3K

### User(s)

J-15 Flying Shark(China-2017,PLANAF,DBID:2496) ,J-15B Flying Shark(China-2022,PLANAF,DBID:6098) and J-15S Flying Shark(China-2017,PLANAF,DBID:3311)

### Weapons Carried

-2×CH-AA-7(PL-12)-2×PL-8C(Python 3)-4×YJ-83K(C-802AK)-1×China KG-600 DECM pod
-2×CH-AA-7(PL-12)-2×PL-8C(Python 3)-2×KD-88 LACM-1×China KG-600 DECM pod
-2×CH-AA-7(PL-12)-2×PL-8C(Python 3)-4×KD-88 LACM-1×China KG-600 DECM pod
-2×CH-AA-7(PL-12)-2×PL-8C(Python 3)-2×LS-6-500 GPS/INS[500kg HE]-1×China KG-600 DECM pod
-2×CH-AA-7(PL-12)-2×PL-8C(Python 3)-4×LS-6-500 GPS/INS[500kg HE]-1×China KG-600 DECM pod

### Requires Buddy Illumination

Yes

### Default Combat Radius (nm)

1090/1240/1090/1090/1290

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

  J-15 is a heavy multi-role carrier based fighter,so it must have strong ability to attack surface targets as other PLAAF fighters as J-16 or Su-30.But in CMO,it only has guided weapons loutouts as 4×YJ-91(KH-31P)，2×YJ-91(KH-31P)or2×YJ-83K（C-802AK）.While Su-30MKK2 euqipped by PLANAF 4th Division 10th Regiment(PLAAF 804th Brigade now) has loudout as 2 or 4 KH-59MK,2 or 4 KH-31P,2 KH-59M and 1 APK-9 datalink pod.Obviously,J-15's ability to use guided weapons to attack land targets or sea targets is very weak in the game .As is expressed in CCTV programmes,J-15 has 12 hanging points.And 6 of them can load guided weapons as YJ-83K/YJ-91/KD-88/LS-6-500.Because of they could only take off on CV-16 and CV-17,max loadouts as 4 guided weapons and 2 PL-12 and 2 PL-8C should be reasonable.
  CCTV 7 programmes never show out J-15 loadouts as 2 or 4×LS-6-500.It only has a photo as loadouts of 500kg GPBs.But in 
Ukraine War, Russian attacks and fighters use bombs like LS-6-500s.Chinese LS-6-500 isn't a new type weapon,it also doesn't have difficulties loading LS-6-500,so I think this loadout should be added into DB3K 506.
  As KD-88 is modified through YJ-83K,J-16/JH-7A both use this type of loadouts.J-15 should can choose loadouts as 4×YJ-83K or 4×KD-88.
  

### Sources

https://tv.cctv.cn/2021/07/01/VIDED5rQYaTVRLPQLcul1Mu5210701.shtml
In this viedo's 15:00 to 15:12, it said J-15 has 12 hanging points, Maximum range is 3500km.
https://www.bilibili.com/read/cv34050429/
This article told us loadouts most likely to be used by PLANAF J-15 fighters.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/b748b3ea-65f8-4436-bed5-4225bb8db50d)
This picture showed Chinese military fans' judement of J-15 loadouts of each hanging points.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/70625844-91f9-45e7-9dad-871c137f7aaa)
This photo shows two GPBs or satellite guided bombs.

**Comment by KLABDB3K** [comment]
For a carrier ski ramp takeoff with afterburner would it not struggle to have any meaningful range or be safe taking off with the full heavy munition load outs above? The number of hardpoints is irrelevant except when its on land and the J-15 doesn't have a significant engine upgrade ? 
Maybe the J-15T with CATOBAR launch or annotate in the DB entry whether its land use / ski ramp use for each loadout and let the scenario designer choose?
The Su-33 has predominantly had just two heavy munitions for its ski ramp launches?

**Comment by FRF311** [comment]
![0f3159a2b81f0533ec816cd8e6d54e6d](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/d7586f45-2042-47e2-a538-39bb6633db4a)
![708d6d2a25c83249a374a34d7e44660a](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/7c9843fd-ffb9-4498-bc45-17b90f0069eb)
The two pictures are from a magazine called “Shipborne Weapons”(《舰载武器》). It's hosted by Zhenzhou 713 Research institute which is related to China Shipbuilding Industry Group Co., Ltd. It said J-15(2×AL-31F-3) can take off on the first or second(110m) take-off boint with weight of 32800 kg when deck wind is more than 18 knots in a very safe candition.When J-15 takes off by the third take-off point(195m),even the thrust loss is achieve 15%,the fighter is still safe.
In CMO,the weight of YJ-83K or KD-88 LACM is 715kg,LS-6-500 is 555kg,CH-AA-7(PL-12) is 200kg,PL-8C is 120kg.
So the first or third loadout I raised is:
2×CH-AA-7(PL-12) 400kg+2×PL-8C 240kg+4×YJ-83K/KD-88 2860kg +KG-600（disregard）+
weight of J-15 17700kg+fuel 9420kg=30380kg
The second loadout:
2×CH-AA-7(PL-12) 400kg+2×PL-8C 240kg+2×KD-88 1430kg +KG-600（disregard）+
weight of J-15 17700kg+fuel 9420kg=28950kg
The fifth loadout:
2×CH-AA-7(PL-12) 400kg+2×PL-8C 240kg+4×LS-6-500 2220kg +KG-600（disregard）+
weight of J-15 17700kg+fuel 9420kg=29640kg
The fourth load out:
2×CH-AA-7(PL-12) 400kg+2×PL-8C 240kg+2×LS-6-500 1110kg +KG-600（disregard）+
weight of J-15 17700kg+fuel 9420kg=28530kg
These loadouts are obviously very safe to take off on CV-16 or CV-17.

**Comment by FRF311** [comment]
In this article of 2011.9,AL-31F-3's afterburner static thrust is used as 12800kg.In CMO,it's 12480kg.There isn't big differences between these.

**Comment by HunterDNiu** [comment]
> even the thrust loss is achieve 15%,the fighter is still safe.

It literally says prohibited dangerous state.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
