### ISSUE TITLE
Add Serbian SA-22 [Pantsir S2E] 2019 x6

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#45]
### DB Selector

DB3K

### Hypothetical

- [ ] Yes

### Name

 SA-22 [Pantsir S2E]

### Facility Type

SAM

### Country

Serbia

### Service

Army

### In Commission

2019

### Dispersion Radius (m)

40m

### Sensors

2x SOT-S radar
Generic IR
Generic TV
Mk 1 Eye ball

Can copy existing  Pantsir-1E Entry adjust radar

### Mounts

2x SA-22 Greyhound [96k6 Pantsire-S1E, Kamaz-6560 8x8] TELAR

### Comments

Can copy existing entries #2348, #1935

### Sources

https://www.armyrecognition.com/weapons_defence_industry_military_technology_uk/russian-made_pantsir-s2_short-range_air_defense_system_in_service_with_serbian_army.html
https://twitter.com/Cyberspec1/status/1256719757459386368
https://armstrade.sipri.org/armstrade/page/trade_register.php

**Comment by Jkryos** [comment]
Added DB3K 493.
