### ISSUE TITLE
Arty Bty (122mm/36 2S1 Gvozdika M1974 Self-Propelled Howitzer x 6)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#450]
### DB Selector

DB3K

### DBID to Copy

facility/1948/DB3K

### Hypothetical

No

### Name

Arty Bty (122mm/36 2S1 Gvozdika M1974 Self-Propelled Howitzer x 6)

### Country

Armenia, Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
