### ISSUE TITLE
Add Drugs Smuggler; Go-Fast

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4501]
### DB Selector

DB3K

### DBID to Copy

Ship 2696

### Hypothetical

No

### Name

Smuggler, Drugs, Go-fast (open)

### Country

Smugglers

### Service

Drugs

### In Commission

- present

### Sensors

For RADAR: JRC Radome or generic navigation radar.

### Sources

https://www.snopes.com/fact-check/drug-running-boat
https://www.pinterest.co.uk/pin/81909286950502331

**Comment by PygmalionOfCyprus** [comment]
See #4503
