### ISSUE TITLE
Add Drugs Smuggler; Go-Fast low RCS

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4502]
### DB Selector

DB3K

### DBID to Copy

Ship 2696

### Hypothetical

No

### Name

Smuggler, Drugs, Go-fast (closed) Low RCS

### Country

Smugglers

### Service

Drugs

### In Commission

- present

### Sensors

No RADAR

### Other Changes

Lower RADAR & Visual signatures
Cargo: 3t
* the very slender vesion (VSV) might be Ship 3244

### Sources

https://cruisingodyssey.com/2018/02/13/drug-smugglers-now-using-low-fast-camouflaged-boats-but-are-still-getting-caught
https://marsecoutlook.com/2018/12/14/coast-guard-cbig-dea-authorities-seize-30-million-in-cocaine-apprehend-3-suspected-smugglers-from-go-fast-in-the-eastern-caribbean
https://pirateyarns.blogspot.com/2013/09/boats-used-to-smuggle-drugs-in-us.html
https://www.businessinsider.com/coast-guard-navy-half-ton-cocaine-smuggling-2018-4
https://www.popularmechanics.com/military/navy-ships/a26914/colombian-drug-smugglers-boat

**Comment by PygmalionOfCyprus** [comment]
This is the SPSS entries already in the DB
