### ISSUE TITLE
Add Air Search Sensor Ability For Voronezh EW radars

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4504]
### DB Selector

DB3K

### Affected DBID(s)

sensor 5183, Sensor 5182 , Sensor 5184

### Summary of Changes

Voronezh-DM/M/VP radars have airspace monitoring for aerodynamic targets and ballistic targets
**Sensor Capability: add air search**

![voronezh 3](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/6e8980dc-94b7-4a88-b0cc-82fc508c44ad)
![voronezh 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/4f5f444b-9931-49ae-ad95-27e37389a88f)
![voronezh](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/bbf1924f-b5af-4970-ae91-3897bc23344f)

### Sources

https://www.sigidwiki.com/wiki/77Ya6_%27Voronezh%27_radar#google_vignette
https://www.radartutorial.eu/19.kartei/01.oth/karte007.en.html
https://en.wikipedia.org/wiki/Voronezh_radar

**Comment by PygmalionOfCyprus** [comment]
Handled 507 and made some other tweaks.
