### ISSUE TITLE
Increase Cheese Board 96L6-TSP Range

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4505]
### DB Selector

DB3K

### Affected DBID(s)

sensor/facility 3131

### Summary of Changes

96l6-tsp used with S-500 ABM system which has a max range of 600km. 77N6 and 77N6-N1 have max ranges of 600km, TSP variant most likely has a max range of 600km to provide surveillance/early warning for the battery.

**increase max range to 325nmi**

### Sources

https://missilethreat.csis.org/defsys/s-500-prometheus/
https://bulgarianmilitary.com/2024/03/11/almaz-antey-bolsters-s-400s-hit-ratio-using-s-500s-yenisei-radar/
https://twitter.com/JohnH105/status/1765520240622911575?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1765520240622911575%7Ctwgr%5Ecb36381c52cd35dfb1ddb0ae2f1380add6f99865%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fbulgarianmilitary.com%2F2024%2F03%2F11%2Falmaz-antey-bolsters-s-400s-hit-ratio-using-s-500s-yenisei-radar%2F
https://www.deagel.com/Components/77T6/a002733
https://www.globalsecurity.org/wmd/world/russia/77t6.htm
https://www.youtube.com/watch?v=wOUoMFtQ2wU
https://en.wikipedia.org/wiki/S-500_missile_system
https://www.defenseworld.net/2021/07/12/should-the-west-be-afraid-of-the-russian-s-500-air-defense-system.html

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
