### ISSUE TITLE
Aircraft Yak-52 (Ukraine -  AF? ) Armed counter UAV 2024 Copy Armenian Yak-52 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4506]
### DB Selector

DB3K

### DBID to Copy

Aircraft Yak-52 Armenia 1992

### Hypothetical

No

### Name

Yak-52 Ukraine AF 1992 100+?

### Country

Ukraine 

### Service
 
Air Force ex DOSAAF 

### In Commission

1992 

### Number in Service

Unknown but multiple aircarft legacy inherited from USSR

### Sensors

Eyeball

### Mounts

Internal gun possibly 12.7mm rear gun and drop tanks.
Counter UAV AA
Training 

### Loadout Options

Training
Guns
Ferry

### Other Changes

Appears that a rear gun has been mounted for counter OWA drones, presumably a single pintle possibly from the audio in the X clips a slower cycling MG 12.7  or just a handheld weapon from the rear cockpit? Former DOSAAF training organisation. 

### Sources

Yak-52 in action, some reports stating "rear gun" was used. , Sound on it seems a slower cyclic heavy calibre ?
https://twitter.com/clashreport/status/1784178781818679334?t=ebLW7dliXNxamRvontEYjw&s=19
https://en.m.wikipedia.org/wiki/Yakovlev_Yak-52#/media/File%3A07_Yellow_Yakolev_Yak.52B_Russian_Air_Force_(7985640947).jpg
Armed variant does have pylons for Ub-57-16 and MG pods but that wasn't the variant in the imagery?

**Comment by KLABDB3K** [comment]
The more you read the more it's unclear as some sources are stating that this is a volunteer operated aircraft just using the aircraft turbulence to bring down the UAV and that the firing sounds are from ground fire? No clips are unequivocally showing the aircraft with any armament.

**Comment by PygmalionOfCyprus** [comment]
Added the Yak-52 for Ukraine, anyway.
