### ISSUE TITLE
Modify the database entry #4428 (Guaiqueri class AVANTE 2200) Venezuela

### ISSUE THREAD

**Issue by trujillocorreo** [PygmalionOfCyprus/cmo-db-requests#4507]
### DB Selector

DB3K

### Affected DBID(s)

Ship #4428

### Summary of Changes

"Hello guys.

Please modify the database entry #4428 (Guaiqueri class AVANTE 2200) by changing the SSM C-802 missiles of Iranian origin, for the C-802A of Chinese origin which are the ones that really carry the PO-11 "Guaquerí" and the PO-14 "Kariña". Similarly, change the denomination and hull number of the Guaqueri AVANTE 2200 class from "Combat Patrol" (PC-XX) to "Oceanic Patrol" (PO-XX):
PO-11 Guaquerí, PO-13 Yekuana and PO-14 Kariña."

![gaceta reslucion gfcS misiles C803_zpsy8fiipuo](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109195286/ce03e6e1-3218-4bc1-9dfb-31e64f026600)
![GKz8EHjW4AAZ4r5](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109195286/d6412a9f-a411-4047-83ec-06655d2163e6)
![F5h-kW5WUAAySaz](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/109195286/9b3c6507-7ad9-496e-8009-d856906bc770)

### Sources

https://www.infodefensa.com/texto-diario/mostrar/3076420/venezuela-dotara-misiles-antibuque-c802a-avante-2200

https://www.infodefensa.com/texto-diario/mostrar/4421283/armada-venezuela-nuevos-buques-sistemas-misilisticos

**Comment by tbrandon517** [comment]
Related #4060

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
