### ISSUE TITLE
Vietnam Sonya Class (Project 1265E) MSC

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#4510]
### DB Selector

DB3K

### DBID to Copy

1981

### Hypothetical

No

### Name

HQ-861

### Country

Vietnam

### Service

Navy

### In Commission

1987-

### Number in Service

4x

### Sensors

- 1x Mius (Spin Trough) navigation radar
- 1x MG-89 Serna HF hull-mounted sonar

### Mounts

- 1x twin 30mm 65cal. AK-230 AA
- 1x twin 25mm 80cal 2M-3M AA
- 5x mines

### Other Changes

- Wooden construction with GRP hull sheathing
- Sweep winch can tow 10 tones at 9kts. Carry GKT-2 contact sweep, ST-2, AT-2 and PEMT-2 influence sweeps an an IT-3 mine detector/exploder.

### Sources

Combat Fleets of the World, 16th Edition, page 952

https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/HQ-862_HQVN.JPG/1280px-HQ-862_HQVN.JPG

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
