### ISSUE TITLE
PLAAF AKF-88C ALCM

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4511]
### DB Selector

DB3K

### Baseline

2876

### Hypothetical

No

### Name

AKF-88C ALCM

### Length (m)

6.40

### Width/Span (m)

1.80

### Diameter (m)

0.36

### Weight (kg)

720

### Range (nm)

2.0-150.0

### Launch Altitude / Depth (ft)

200ft AGL-65000ft ASL

### Warhead

190kg penetrator

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Radar, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

4

### Sensors

1x passive radar seeker
1×active radar seeker

### Weapon Codes

Home On Jam (HOJ), Terrain Following, Search Pattern, Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Terminal Maneuver - Random (Advanced), Re-Attack Capability, Uses BeiDou/COMPASS, Level Cruise Flight,Supports waypoints

### Comments

RCS：same as KD-88，weapon 2876
Speed: 520kt
Cruise attitude:60ft ASL
Affected DBID: Aircraft 4905 5596 4926 6450 6098 4617 5259 2057

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/704c3ff9-0ee8-4cce-8d1c-42c1b3de5ab8)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/d99fe88c-7c2d-4591-876b-f22eb5d14265)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/1b58419a-ce35-4e58-931c-e40bba885e2a)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/6150f95c-ae97-4887-bc65-43430daa20f0)
In a cctv7 TV show,PLAAF J-16 fighters use a guided weapon to attack a hardened target.It's very to the AKD-88C ALCM which is similar to SLAM-ER. It was once showed on Zhuhai Air Show.

**Comment by PygmalionOfCyprus** [comment]
Handled 506.
