### ISSUE TITLE
PL-12/15 datalink did not support CEC capability

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#4512]
### DB Selector

DB3K

### Affected DBID(s)

1116, 2108,3413, 3896

### Description of Problem

Missiles were supposed to be CEC-capable, but missile`s datalink only support LOS. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/246abd2c-aedb-4f90-bbd8-83259b425a62)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/d877084f-1142-44a2-9d27-32379a21bff0)

### Recommended Fix

- Please update all related datalinks for PL-12/15 missiles to enable their CEC capability like the one for AIM-120D
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/757b3e56-4687-4629-b2bb-224cb6b5180b)

**Comment by LuigiP57** [comment]
Also the PL-17 DL

**Comment by LuigiP57** [comment]
These PLA AAMs‘ DLs need some upgrade

**Comment by PygmalionOfCyprus** [comment]
Should be fixed 508. Issue was not with the datalink itself but that the PL-15 had the link set as Parent Specific
