### ISSUE TITLE
China, PLAMSF, Liao Wang 1, Space Surveillance & Ballistic Missile Early Warning Ship, LPAR Equipped

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4514]
### DB Selector

DB3K

### Baseline

Ship 3102

### Hypothetical

No

### Name

Liao Wang 1

### Country

China

### Service

PLAN, PLAMSF

### In Commission

2025

### Length (m)

240

### Beam (m)

30

### Draft (m)

8

### Standard Displacement (t)

28000

### Complement

same as ship 3102

### Primary Propulsion Type

Diesel

### Propulsion

same as ship 3102

### Flank Speed (kt)

same as ship 3102

### Range (nm) at Speed (kt)

same as ship 3102

### Sensors

Liao Wang 1 LPAR
others are same as ship 3102

### Mounts

same as ship 3102

### Sources

https://chinapower.csis.org/analysis/china-naval-modernization-jiangnan-hudong-zhonghua-shipyard/
https://twitter.com/foolsball/status/1785954055899980076
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/063c5ca3-359d-47c1-a8ae-6dda4d89d08d)
AESA Phased Arrays are adjustable angle and can be folded forward, which enables it to search for targets in the lower atmosphere and surface.

**Comment by LuigiP57** [comment]
According to the latest photo, the correct name is "Liao Wang 1".
https://twitter.com/foolsball/status/1817936241658101896
https://twitter.com/WLR_2678/status/1817944286903619809
![image](https://github.com/user-attachments/assets/ccce07e3-e2e8-4b93-83d8-408f334cd425)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
