### ISSUE TITLE
China, Liao Wang 1 LPAR

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4515]
### DB Selector

DB3K

### Baseline

sensor 5807

### Hypothetical

No

### Name

Liao Wang 1 LPAR

### Sensor Generation

Early 2020s

### Range (nm)

1.4-2800

### Sensor Capabilities

Air Search, Surface Search, Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Continuous Tracking Capability, Track While Scan (TWS), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA), Frequency Agile

### Search/Track Frequencies

B Band (250-500 MHz) [Old P Band (VHF)] 60-100 cm

### Horizontal Beamwidth (deg)

1

### Vertical Beamwidth (deg)

1

### System Noise Level (dB)

2

### Processing Gain/Loss (dB)

10

### Peak Power (W)

60000000

### Pulse Width (μs)

0.1

### Blind Time (μs)

10

### PRF (Hz)

50

### Comments

It has **two phased arrays**, so may add another **L-Band** copy entry of this

### Sources

https://twitter.com/foolsball/status/1785954055899980076/photo/1
https://chinapower.csis.org/analysis/china-naval-modernization-jiangnan-hudong-zhonghua-shipyard/
Technology may be derived from:
https://www.janes.com/defence-news/news-detail/china-displays-transportable-slc-18-space-surveillance-radar
https://www.defensenews.com/global/asia-pacific/2022/04/18/new-chinese-radar-looks-towards-japan-satellite-image-shows/

**Comment by LuigiP57** [comment]
#4514

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
