### ISSUE TITLE
DB (0) on Facility 3730

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4516]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3730

### Summary of Changes

Damage Points on Facility 3730 Command Post (Generic - 0) is 0.
Should this be a higher number?
DB505

### Sources

NA

**Comment by Parel803** [comment]
DP 0 on Fac3730 (instead of DB 0)

**Comment by Parel803** [comment]
If this is WAD I apologize.
I see now more facility with no dimensions, no DP's but with Dispersal Radius.

**Comment by PygmalionOfCyprus** [comment]
When "Mounts Are Aimpoints" is true facilities don't use the DP value.

**Comment by Parel803** [comment]
Thank you, apologise for time wasted.
regards GJ
