### ISSUE TITLE
Aircraft #6932 - Yak-18T (Armenia - 1992) Too many paratroops 64 should be 4. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4517]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #6932 - Yak-18T (Armenia - 1992)

### Summary of Changes

Loadout #33326 Paratroopers, 4x
Has record - (Paratroops) 64x Paratrooper
Change to  (Paratroops) 4x Paratrooper
 

### Sources

DB505 - It would be a bit cramped with 64 paratroops on board?

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
