### ISSUE TITLE
China FX-500 UAV

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4518]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

FX-500 UAV

### Country

China

### Service

PLAGF

### In Commission

2019-

### Length (m)

6.4

### Wingspan (m)

3.0

### Height (m)

0.6

### Empty Weight (kg)

450

### Maximum Takeoff Weight (MTOW) (kg)

500

### Payload Weight (kg)

50

### Crew

0

### Propulsion

1×AEF-20

### Rate of Climb (ft/min)

3000

### Service Ceiling (ft)

29000

### Military/Afterburner Speed (kt)

430

### Cruise Speed (kt)

200

### Supercruise

No

### Ferry Range (nm)

700

### Endurance (min)

180

### Sensors

1×Generic TV camera
1×Generic FLIR
1×Generic Laser Designer

### Mounts

No mounts.

### Loadout Options

-Recon [Internal EO/IR]

### Comms/Datalinks

UHF/VHF Radio[Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

FX-500's a UAV that can launch by generic uav launch truck or a new "FX-500 UAV launch trunk".
He uses rocket to take off，a parachute to recover.

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/295c50f9-522a-4706-bc67-56393e3ee769)
2019 Military Parade
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/0d419155-8ad2-4d9d-9081-e30aebf976ff)
Zhuhai Air Show
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/6d43bc82-a9b5-436a-a6ce-9b4ae9cee4b0)
Social Media，Official account of PLA Southern Theater Command.

**Comment by PygmalionOfCyprus** [comment]
Since this is not known (or frankly, likely) to be in service and we're not getting sucked into adding every single demo drone, etc. from China (because there would be literally hundreds if not thousands) unless they offer a seriously revolutionary/critical capability, I'm gonna close this as wontfix pending actual acquisition.
