### ISSUE TITLE
SHIP #4468 - Generic Suicide USV (Ukraine [1992-] - 2022) - SAM variant? R-73 surface launched. WIP

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4519]
### DB Selector

DB3K

### DBID to Copy

SHIP #4468 - Generic Suicide USV (Ukraine [1992-] - 2022) Magura V5

### Hypothetical

NO

### Name

Magura V5 OWUSV (Ukraine [1992-] - 2022) Magura V5 SAM

### Country

Ukraine 

### Service

Navy

### In Commission

2024

### Number in Service

?

### Hypothetical

NO

### Name

Magura V5 OWUSV (Ukraine [1992-] - 2022) Magura V5 SAM

### Country

Ukraine 

### Service

Navy

### In Commission

2024

### Number in Service

?

### 

As existing ship presumably with an air search function to the EO sensor?. 

### Mounts

Decoys?

### Loadout Options

2 X R-73 Surface launched. 

### Other Changes

Nil apparent

### Sources

https://twitter.com/MilAviaUA
https://x.com/bayraktar_1love/status/1787449315700408321
https://x.com/bayraktar_1love/status/1787436529482125456

**Comment by tbrandon517** [comment]
Additional, looks like R-60s are also a possibility.

https://www.twz.com/news-features/ukrainian-drone-boats-now-armed-with-adapted-air-to-air-missiles?fbclid=IwZXh0bgNhZW0CMTEAAR1H5vATiqkWsWim-oOiYZNW7V0kG52uIEZgnZFJlw3qFmnboB0azJ2Y15E_aem_AYEgV05CQhRzLWUrcgXL-BADze1f-dSXYQQ0oIR_VhyqeZfWjT7TT8l9QzmEnPXNnVjq4z5i_6wWjk4vkw_2Cr7U

**Comment by tbrandon517** [comment]
Additional 

http://www.hisutton.com/Ukraine-USV-FrankenSAM.html

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by KLABDB3K** [comment]
Difficult to keep up these days but apparently they now have a Sea Baby variant which can launch 6 x Grad 122mm rockets.  https://x.com/KyivPost/status/1793234429105549615

**Comment by tbrandon517** [comment]
> Difficult to keep up these days but apparently they now have a Sea Baby variant which can launch 6 x Grad 122mm rockets. https://x.com/KyivPost/status/1793234429105549615

Yes.
https://www.armyrecognition.com/news/navy-news/2024/ukraine-intelligence-service-sbu-equips-sea-baby-naval-drones-with-grad-rocket-launchers?fbclid=IwZXh0bgNhZW0CMTEAAR3s4Fd3E1XUylNJHwmGhn7iE7Mtu1d8GVGYHyd9al_dM6q6Ob22PsBfpho_aem_AbIfepogX1Z_1lZJAVhu8BX8zmQv4HB0WQ-O4sLey6dsrRsOX1r3u133NUNf2EFyJICW53jmTNpWKYp_GYh6ZJcj

Amongst the the growing variety of Attack USVs including 4 to 6 smaller RPV-16 rockets.

http://www.hisutton.com/Russia-Ukraine-USVs-2024.html

http://www.hisutton.com/Ukraine-Sea-Baby-Rockets.html

**Comment by KLABDB3K** [comment]
Ref https://cmano-db.com/ship/4468/
Now Magura V7 + AIM-9M x 2
Different bow, longer 8m presumably better sea keeping and possibly optional warhead.

**Comment by tbrandon517** [comment]
> Ref https://cmano-db.com/ship/4468/ Now Magura V7 + AIM-9M x 2 Different bow, longer 8m presumably better sea keeping and possibly optional warhead.

https://www.twz.com/news-features/two-russian-su-30-flankers-downed-by-aim-9s-fired-from-drone-boats-ukrainian-intel-boss

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus 

Looks like it actually AIM-9X not AIM-9L/M

https://www.twz.com/news-features/aim-9x-being-used-by-ukraines-drone-boats-to-engage-russian-jets-not-aim-9l-ms
