### ISSUE TITLE
Taiwanese F-16V to carry AGM-84H/K (2020)

### ISSUE THREAD

**Issue by HudsonCW** [PygmalionOfCyprus/cmo-db-requests#452]
### DB Selector

DB3K

### User(s)

F-16V

### Weapons Carried

- 2x AGM-84H/K SLAM-ER
- AN/AAQ-33 Sniper XR
- AN/AAQ-13 LANTIRN
- 2x AIM-120D
- 2x AIM-2000A IRIS-T
- 300 USG Drop tank
- 2x 370 USG Drop Tank
- 2x 500 USG Conformal Tank

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

1100 nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://hindustannewshub.com/world-news/how-dangerous-is-taiwans-f-16v-fighter-plane-will-strike-inside-china/
https://www.reuters.com/article/us-taiwan-security-usa-timeline/timeline-u-s-arms-sales-to-taiwan-in-2020-total-5-billion-amid-china-tensions-idUSKBN28I0BF

**Comment by Jkryos** [comment]
Added DB3K 501.
