### ISSUE TITLE
Request to add ABM/Space Surveillance Capability for NEBO-M Complex Radars (RLM-D, M, S)

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#4522]
### DB Selector

DB3K

### Affected DBID(s)

sensor 4556, 4558, 1848

### Summary of Changes

The 3 radars of the 55zh6me Nebo-M complex are shown by the exporter as each having ABM/space search capability up to 600km in height against targets up to 18000km/hr (mach 17), along with 600km in max horizontal range.

Also, given that the maximum range of forward based mode is shown to be 1800km when all 3 radars are synchronized, it's likely provided from the information that the S-band radar component RLM-S has a max horizontal range of 600km as well while on its own.

Requested Changes:
1. add ABM/Space Search sensor abilities for all 3 radars RLM-M, RLM-D, RLM-S up to 600km in altitude (sensors 4556, 4558, 1848)
2. increase maximum range for RLM-S radar to 320nm (sensor 1848)

Documentation/evidence: 
![nebo](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/169417247/6234af5f-bf14-4242-8c10-50d506718d0c)

### Sources

https://roe.ru/pdfs/pdf_6372.pdf 

https://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/55Zh6ME/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
