### ISSUE TITLE
China - SA-2a [SA-75 Dvina]

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#4524]
### DB Selector

CWDB

### DBID to Copy

Facility 708 in CWDB

### Hypothetical

No

### Name

SAM Bn (SA-2a Guideline [SA-75 Dvina])

### Country

China (People's Republic)

### Service

Air Force

### In Commission

1958 - no idea when they stopped using original soviet ones

### Number in Service

5 SAM battalions (each with one SA-75 firing battery) + one training system

### Sensors

no change

### Mounts

if possible reduce number of reload missiles from 12 to just 6 so the whole battalion would have just 12 missiles total (6 on launchers and six as one reload) --- China imported only 62 missiles plus two training ones

### Sources

Soviet export charts. China was the first export user of SA-2 SAM listed here with year 1958 (Warsaw Pact states got their first SA-2 in 1959). The version is really the original SA-75 Dvina i.e. SA-2A with original V-750 (1D) missiles. China was quite succesful with this system as several U-2 were shot down with these missiles (see here: https://en.wikipedia.org/wiki/Black_Cat_Squadron ).

The chart lists these data for chinese SA-2 [SA-75 Dvina]:
1958 - three combat systems, one training one with 36 live missiles and 2 training ones
1959 - two combat systems and 26 live missiles

No further SA-2 deliveries for China are listed here.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
