### ISSUE TITLE
China - Radar Tall King A [P-14]

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#4525]
### DB Selector

CWDB

### DBID to Copy

Facility 81 in CWDB

### Hypothetical

No

### Name

Radar (Tall King A [P-14])

### Country

China (People's Republic)

### Service

Air Force

### In Commission

1964 - up to no idea

### Number in Service

1 - yes only one

### Sensors

no change

### Mounts

no change

### Sources

Soviet export charts. Only single P-14 [Tall King A] radar is mentioned here as exported to China in 1964, no further deliveries of these radars are listed to China. This is interesting as in this year export of this type of radar started also to Warsaw Pact countries which however got more of these.
Together with SA-2a for China this is all I have to add for China update.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
