### ISSUE TITLE
Martlet Missile being used against air targets by royal navy

### ISSUE THREAD

**Issue by willpope697** [PygmalionOfCyprus/cmo-db-requests#4527]
### DB Selector

DB3K

### Affected DBID(s)

weapon #3157

### Summary of Changes

Stumbled across a royal navy article and video showing and describing the use of the martlet missile against low flying air targets.

I was wondering if this could be changed in the DB i think it could make for some interesting scenarios for example targeting houthi drones.

### Sources

https://www.youtube.com/watch?v=wv2dsQP88Pw&ab_channel=ForcesNews

https://www.forces.net/services/navy/wildcat-and-martlet-combination-providing-ring-steel-around-warships

https://www.royalnavy.mod.uk/news-and-latest-activity/news/2023/july/28/230728-martlet-trials

https://uk.leonardo.com/en/news-and-stories-detail/-/detail/aw159-on-target#:~:text=In%20addition%20to%20dealing%20with,when%20the%20Wildcat%20is%20airborne.

**Comment by PygmalionOfCyprus** [comment]
Handled 507. Also added an AA-capable laser designator to the Wildcats so they can use this.
