### ISSUE TITLE
How Strategic Anti-Missile Defense of the United States Could be Made to Work

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4529]
### DB Selector

DB3K

### DBID to Copy

Sensor #6320 TPY-2

### Hypothetical

No

### Name

Ballistic Missile Defense

### Country

United States

### Service

Army and Navy 

### Other Changes

This does not adress a certain update, but maybe it can help somewhere in CMO, if you aren't already aware of this, than disregard please.
Just trying ;-)

https://www.armscontrol.ru/pubs/en/How%20Strategic%20Anti-Missile%20Defense%20of%20the%20%20United%20States%20Could%20be%20Made%20to%20Work%20(Postol,%20March27,2011).pdf

For example, pdf page 69 and 70 but also the trajectories and the amount of minutes.
Did not attach the pdf because it is 15MB

### Sources

[https://twitter.com/awes_spad/status/1790060800331100521/photo/1](url)

**Comment by PygmalionOfCyprus** [comment]
Neat links! Closing as not actionable ticket
