### ISSUE TITLE
China 891 project Carrier

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4530]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

891 project

### Class

891 project

### Country

China

### Service

PLAN

### Length (m)

300

### Beam (m)

12

### Draft (m)

9

### Standard Displacement (t)

45000

### Full Displacement (t)

55000

### Complement

8000

### Primary Propulsion Type

Steam

### Propulsion

4×Steam tuibines

### Fuel Capacity (kg)

1200000

### Flank Speed (kt)

29

### Range (nm) at Speed (kt)

12000nm 15kt

### Sensors

1×Type 517H-1[China H/LJQ-517B]
1×Type 344
2×Type 347G
1×Type 362
1×Type 518 Sea Eye
2×Type 984-1(RWR)
2×Type 984-1(ECM)
1×Piranha[IR]
1×China H/SJD-9
1×China H/SJD-8
1×eye ball

### Mounts

4×HQ-7（FM-80）Naval
4×China Type 945G DL
4×China H/PJ-12(730)

### Aircraft & Docking Facilities

2×elevator
2×carrier catapult

### Comms/Datalinks

VHF/UHF Radio

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/51cd40e7-608b-405d-9035-6eae23cf2e48)
CCTV

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
