### ISSUE TITLE
China 891 project Carrier-based aircraft （J-10A variant）

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4531]
### DB Selector

DB3K

### Baseline

aircraft 715

### Hypothetical

Yes

### Name

J-10A Carrier Variant

### Country

China

### Service

PLAN

### Length (m)

Same as J-10A

### Wingspan (m)

Same as J-10A

### Height (m)

Same as J-10A

### Empty Weight (kg)

Same as J-10A

### Maximum Takeoff Weight (MTOW) (kg)

Same as j-10A

### Payload Weight (kg)

Same as j-10A

### Crew

Same as J-10A

### Propulsion

Same as J-10A

### Rate of Climb (ft/min)

Same as J-10A

### Service Ceiling (ft)

Same as j-10A

### Military/Afterburner Speed (kt)

Same as J-10A

### Cruise Speed (kt)

Same as J-10A

### Supercruise

No

### Ferry Range (nm)

Same as J-10A

### Endurance (min)

Same as J-10A

### Takeoff / Landing Distance (m)

Same as J-15

### Fuel Capacity (kg)

Same as J-10A

### Sensors

Same as J-10A

### Mounts

Same as J-10A

### Loadout Options

Same as J-10A

### Comms/Datalinks

Same as J-10A

### Aircraft Codes

Fly-by-Wire, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Bombsight - Advanced Computing, Probe Refuelling

### Comments

Recently, CCTV exposed China's aircraft carrier project in the last century, its code name is 891 Project, 891 project is China's aircraft carrier development plan after 707 project. On the model, we can see a carrier-based variant of the J-10A envisaged for development.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/0005a6c3-5bc5-4201-90d5-0d5b057fe79f)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/7c4cdf0e-d667-4daf-a381-b92ab88ad326)

### Sources

https://twitter.com/sugar_wsnbn/status/1786251165468147886
https://en.wikipedia.org/wiki/Chinese_aircraft_carrier_programme

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
