### ISSUE TITLE
China Y-7 AEW Radar

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4532]
### DB Selector

DB3K

### Baseline

sensor 920

### Hypothetical

Yes

### Name

Y-7 AEW Radar

### Sensor Generation

Late 1990s

### Range (nm)

0.2-250

### Sensor Capabilities

Air Search, Surface Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Non-Cooperative Target Recognition (NCTR) - Jet Engine Modulation [Class Info], Pulse Doppler Radar (Full LDSD Capability)

### Search/Track Frequencies

C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm

### Scan Interval (s)

5

### Comments

Under the 891 aircraft Carrier Program, China decided to develop a carrier-based early warning aircraft based on the Y-7, which was inferred based on the level of Chinese radar at the time.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/7d52df00-91d6-4aee-90b0-539a061f842f)

### Sources

https://twitter.com/sugar_wsnbn/status/1786251165468147886/photo/3

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
