### ISSUE TITLE
China Y-7 carrier-based early warning aircraft

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4533]
### DB Selector

DB3K

### Baseline

aircraft 2502

### Hypothetical

Yes

### Name

Y-7 AEW

### Country

China

### Service

PLAN

### Length (m)

Same as Y-7H Curl

### Wingspan (m)

Same as Y-7H Curl

### Height (m)

Same as Y-7H Curl

### Empty Weight (kg)

Same as Y-7H Curl

### Maximum Takeoff Weight (MTOW) (kg)

Same as Y-7H Curl

### Payload Weight (kg)

Same as Y-7H Curl

### Crew

5

### Propulsion

Same as Y-7H Curl

### Rate of Climb (ft/min)

Same as Y-7H Curl

### Service Ceiling (ft)

Same as Y-7H Curl

### Military/Afterburner Speed (kt)

Same as Y-7H Curl

### Cruise Speed (kt)

Same as Y-7H Curl

### Supercruise

No

### Ferry Range (nm)

Same as Y-7H Curl

### Endurance (min)

Same as Y-7H Curl

### Takeoff / Landing Distance (m)

Same as Y-7H Curl

### Fuel Capacity (kg)

Same as Y-7H Curl

### Sensors

1x Y-7 AEW Radar
1x Generic ESM [Advanced]
1x Mk1 Eyeball
1x China BM/KJ-8602 [SPS-1000]

### Mounts

none

### Loadout Options

none

### Comms/Datalinks

UHF/VHF Radio [Unsecure]
VHF Radio [Unsecure]
HF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

An early warning aircraft based on the Y-7 is envisaged in the published Project 891 model.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/0a49099b-946c-46a8-bd52-dfad224a3713)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/94e14639-4da1-4857-916a-e88eff1b9d3b)

### Sources

https://twitter.com/sugar_wsnbn/status/1786251165468147886/photo/2

**Comment by yU2187sie** [comment]
#4532

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
