### ISSUE TITLE
AT-802U Sky Warden - 2023 (6x Initially, 75x Planned, Armed Overwatch) designation update OA-1K 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4535]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft USAF AT-802U Sky Warden - 2023 (6x Initially, 75x Planned, Armed Overwatch)

### Summary of Changes

Amend designation to
OA-1K Sky Warden (AT-802U) USAF AFSOC 12 2025.
*Total procurement is set at 69 (+ options) with 12 budgeted for 2025. 

### Sources

June 2024 Combat Aircraft pp.33 Intel Brief FY25 Presidents budget request.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
