### ISSUE TITLE
TCG Derya A1590

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4540]
### DB Selector

DB3K

### Hypothetical

No

### Name

TCG Derya (A-1590)

### Country

Turkey

### Service

Turkish Navy

### In Commission

2024

### Number in Service

1x

### Length (m)

194.8

### Beam (m)

23.4

### Draft (m)

unknown

### Standard Displacement (t)

26 000?

### Full Displacement (t)

26 000?

### Empty Displacement (t)

unknown

### Complement

326

### Max Sea State

unknown

### Primary Propulsion Type

Gas Turbine

### Propulsion

	      2 × General Electric LM2500 gas turbines,     2 × Diesel engines     2 × Electric motors

### Fuel Capacity (kg)

unknown

### Flank Speed (kt)

24

### Range (nm) at Speed (kt)

4,500 nmi @ ? kts

### Sensors

Aselsan MAR-D helicopter detection radar,  Havelsan ADVENT naval combat management system

### Mounts

 2 × Aselsan GOKDENIZ 35 mm Close-in weapon system (CIWS);  2 × 25 mm Aselsan STOP remote weapon stations

### Aircraft & Docking Facilities

Aircraft carried = 3x Helicopters, 
Helipad, hangar

### Comms/Datalinks

unknown

### Comments

9,000 long tons (9,100 t) F-76 fuel;  1,000 long tons (1,000 t) F-44 fuel ;  800 long tons (810 t) fresh water;  48 containers
30 day endurance

### Sources

https://en.wikipedia.org/wiki/TCG_Derya_(A-1590)
https://www.defensenews.com/naval/2024/01/19/turkish-navy-receives-unmanned-surface-vessel-three-crewed-ships/
https://www.overtdefense.com/2023/08/11/turkeys-second-largest-ship-tcg-derya-begins-sea-trials/

**Comment by Jkryos** [comment]
Added DB3K 507.
