### ISSUE TITLE
Tarmac space/hangers/weather hangers

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4541]
Add Tarmac space for 3x small/med/large/xl a/c

Add hanger for 1x med a/c
Add hanger for 1x small a/c
Add hanger for 3x med/small/xl a/c
Add hanger for 6x medium a/c
Add hanger for 6x/7x/8x medium a/c
Add weather shelter 2x small/med/large a/c
Add weather shelter 3x small/med/large a/c
Add weather shelter 4x small/med/large a/c

**Comment by PygmalionOfCyprus** [comment]
You should be able to do some of these with existing platforms, like put 1x med ac in a 2x small AC hangar. In general I think the existing hangar structures are fine, I don't want to add a bunch of entries when the existing ones are perfectly adequate.

**Comment by trevor99999** [comment]
Even just 3x/4x small/med/large weather hangers then. Trying to put in 1x 20 or 30 or 40 of these things on a tarmac/parking area just looks like a mess.
I wasn't aware of this. Is there an "equality" between hanger sizes? Like a 4x medium a/c hanger will accommodate 2 large a/c ? Or a 4x large a/c hanger will accomodate1 vl a/c ?
Regards

    On Tuesday, May 28, 2024 at 12:34:44 p.m. EDT, PygmalionOfCyprus ***@***.***> wrote:  
 
 


Closed #4541 as not planned.

**Comment by PygmalionOfCyprus** [comment]
>Is there an "equality" between hanger sizes? Like a 4x medium a/c hanger will accommodate 2 large a/c ? Or a 4x large a/c hanger will accomodate1 vl a/c

Yes.
