### ISSUE TITLE
MiG-21 Speeds Are Incorrect

### ISSUE THREAD

**Issue by artao5** [PygmalionOfCyprus/cmo-db-requests#4544]
### DB Selector

Both

### Affected DBID(s)

Aircraft 3678, 3001, 1570

### Summary of Changes

I can't list all the DBIDs because this affects every single MiG-21 in both Cold War and DB3K as well as every variant, such as Chengdu J-7 and such. The max speeds are simply wrong.
The DBs list Mach 0.98 at max speed below 12,000 ft. This is untrue. They can easily exceed Mach 1 at that altitude.
The DBs list Mach 1.60 as max speed at max altitude. This is untrue. They can reach at least Mach 1.83 and even up to Mach 2.1 with potential engine damage.
It has a maximum speed of about 1400kph (~750 knts) IAS before the engine flames out.

### Sources

This is according to the actual Russian manual for the airplane translated to English as well as every single source I can find from Jane's to GlobalSecurity.org to simulations of the airplane to Wikipedia (note ever single reference for the Wikipedia article, don't just scoff at Wikipedia)
I can find ZERO sources that back up a max speed of Mach 1.6 at altitude and Mach 0.98 at sea level. I'm baffled as to where that came from.

**Comment by FrangibleCover** [comment]
Are these values clean or loaded? Speeds in CMO can be odd and the methodology for them is frankly opaque, but they're generally significantly lower than the rated max speed for the aircraft to account for payload and operational conditions (lots of aircraft need to do weird climb-dive-climb-dive profiles to actually reach their rated max speeds).

**Comment by tbrandon517** [comment]
I would refer you to the quoted text from Half Life Expert taken from the old CMANO Mega-FAQ regarding most fighter speeds in SIM.

https://steamcommunity.com/app/321410/discussions/0/1470841715938307919/

**Comment by PygmalionOfCyprus** [comment]
See points above. This is a larger "issue" than just for the MiG-21, and is basically WAD.
