### ISSUE TITLE
C-17 Troops

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4546]
### DB Selector

Both

### User(s)

USAF C-17A Globemaster III DBID's 5468/3784/1932/288

### Weapons Carried

Add troop + cargo carrying capacity (134 troops with palletized and sidewall seats or 54 troops with sidewall seats with 13 cargo pallets only ) 
Passengers (ie evacuees?). Overload/emergency passenger capacity? Recall the evacuation from Afghanistan. 
36 litter and 54 ambulatory patients and medical attendants 

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Add troop + cargo carrying capacity (134 troops with palletized and sidewall seats or 54 troops with sidewall seats with 13 cargo pallets only ) 
Passengers (ie evacuees?). Overload/emergency passenger capacity? Recall the evacuation from Afghanistan. 
36 litter and 54 ambulatory patients and medical attendants 

### Sources

https://en.wikipedia.org/wiki/Boeing_C-17_Globemaster_III

**Comment by trevor99999** [comment]
https://www.airandspaceforces.com/kabul-evacuation-flight-c-17-record/
823 people on a C-17A

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
