### ISSUE TITLE
Airport construction

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4548]
1401m-2000m taxi way, very large aircraft

"Nose dock" hanger for VL a/c (a hanger where only the nose portion fore of the wings of the a/c is inside)

**Comment by PygmalionOfCyprus** [comment]
A 1401-2000m taxiway already exists in both DBs. It's the 2000m taxiway.

I don't see value in a nose-dock hangar when a generic hangar works fine. Admittedly IRL there is a recon disadvantage (you can see if there's a plane in the hangar or not) but that would require some extra sim modelling which is just not a priority right now.
