### ISSUE TITLE
Arty Bty (152mm/25 D-20 M1955 Howitzer x 6)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#455]
### DB Selector

DB3K

### DBID to Copy

facility/680/DB3K

### Hypothetical

No

### Name

Arty Bty (152mm/25 D-20 M1955 Howitzer x 6)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
