### ISSUE TITLE
Add LY-402 FAE Bomb Loadout to Myanmar A-5C

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4551]
### DB Selector

DB3K

### User(s)

Aircraft 4661

### Weapons Carried

x2 LY-402
x2 400 Liter Drop tanks

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://twitter.com/KryptonKN96/status/1791421928953221509

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
