### ISSUE TITLE
Russia, Su-30SM2, AA-13 Loadouts

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4552]
### DB Selector

DB3K

### User(s)

Su-30SM2 Flanker G (Aircraft 6209 6210)

### Weapons Carried

- Light: 2x AA-13 Arrow, 2x AA-12 Adder B
- Heavy: 4x AA-13 Arrow, 2x AA-12 Adder B (reasonable speculation)

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://twitter.com/GuyPlopsky/status/1793242596875329683
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/d74cc6b1-f4fd-4032-8d50-4959a370d592)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by KLABDB3K** [comment]
Probably would also have 2 x  R-73??
