### ISSUE TITLE
Correction: KRONOS Quad Radar is IEEE C-Band, Not NATO C-Band

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#4553]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6307

### Summary of Changes

According to Leonardo S.p.A., the manufacturer of the radar, they didn't specify whether the radar band is NATO or IEEE, but in the KRONOS Dual Band brochure, another radar that is supposed to pair with KRONOS Quad, the KRONOS StarFire, is an X-band radar. NATO doesn't use X-band. IEEE X-band is 8.0–12.0 GHz, while NATO I/J-band is 8.0–20.0 GHz, which means IEEE X-band is equivalent to NATO I-band and the lower part of J-band. I think Leonardo is using a consistent nomenclature here, which is IEEE bands. This makes sense because multifunctional radars generally don't operate in low bands, but mid or high bands.

In the CMO DB, the radar is using NATO C-band. So KRONOS Quad would have to be G/H-band in CMO (which uses NATO nomenclature). NATO G and H-band (4.0-6.0 GHz and 6.0-8.0 GHz, respectively) are directly equivalent to half of IEEE C-band (4.0-8.0 GHz).

Unfortunately, I can't find information on whether KRONOS Quad operates in just G or H-band or both, so that's up to CMO's dev discretion.

I think I have to file a separate issue, but given that Leonardo appears to consistently use IEEE bands in all of their product brochures, KRONOS Grand Mobile must also be changed to NATO G or H-band (or both). Like KRONOS Quad, it's also a multifunctional radar.

![CMO_KRONOSQuad](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99858862/8a66f859-9872-4784-8c06-69d2c25b0a22)

![CMO_KRONOSDualBand](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99858862/8ce192f0-aa73-4a3d-b314-3fcc6d77b552)

### Sources

[Leonardo's Official KRONOS Dual Band Brochure](https://electronics.leonardo.com/documents/16277707/18337686/KRONOS+Dual+Band.pdf?t=1671014727544) --- Published in 2022

![KRONOSDualBand_Leonardo_Brochure](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99858862/021af7af-ab53-4dac-9a14-63be06c686cb)

**Comment by PygmalionOfCyprus** [comment]
Thanks for the catch! Fixed the Quad and the Grand Mobile for 507.
