### ISSUE TITLE
Ukraine SDB Load outs. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4558]
### DB Selector

DB3K

### User(s)

Su-27 MiG-29 Ukraine AF 2024

### Weapons Carried

4-8 SDB assuming two quad packed on inner MiG-29 pylons. 
Su-27 would be speculation, could carry more but multiple reasons why it may not? 
Possible 2 * R-73 could be carried but doesn't appear this is used, not because it can't but because of the tactical situation and doctrine?

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As JDAM load out. 

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Seen on MiG-29 but no reason it wouldn't migrate to Su-27 as most western weapons that are added to one seem to be integrated on both platforms eventually (HARM/JDAM/AASM) . 

### Sources

https://x.com/GuyPlopsky/status/1794392218486403424?t=WE2uNUBnMLq2itik9U5urg&s=19

Interesting that bombs and AAM aren't seen together in the load out, could see why R-27 wouldn't due to pylon issue on the 29 but R-73 would appear straightforward?

**Comment by tbrandon517** [comment]
Additional coverage

https://www.twz.com/news-features/ukraine-situation-report-kyiv-says-its-using-air-launched-small-diameter-bombs?fbclid=IwZXh0bgNhZW0CMTEAAR3oMCIRSRUpE_NpRUylDvP42_W9wrIVHsFGla3Z-bHjYfVjqm_BtdCvWfo_aem_Ac_ua3ggSkd9U9TJ2_5TBN1wKs5G0Ms1nGjM-CaSJG5f71KzC-RtwK65GUPGM_KaBiCUZlhO2yvDmHVbvVwWIZ0q

**Comment by bostonmyk** [comment]
https://twitter.com/Osinttechnical/status/1794749516165287996

Answer on the Pylon configuration here:
https://twitter.com/Osinttechnical/status/1794348473460097169/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
