### ISSUE TITLE
Decrease max range to 150km for 50N6A radar (s-350 vityaz)

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#4559]
### DB Selector

DB3K

### Affected DBID(s)

sensor 5075

### Summary of Changes

-decrease max range from 215nmi to 80nmi (~150km) 
Also, some range figures noted to add to radar (see right page of pic)
at height of 5000km, a target of rcs 0.4m2 is detected at 90km
at height of 100 meters, target of rcs 0.1m2 is detected at 45km
at height of 10,000km, target of 13m2 detected at 145km

Upon translating the text, Export catalogue describes the 50n6a multi function radar having 150km maximum range in 360 degree scan mode, and 230km in sector (100 degree) scan mode

![s350 radar](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/169417247/c985513c-bac1-42ed-8145-3029b3df23e7)

### Sources

https://x.com/krakek1/status/1794492206566523343

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
