### ISSUE TITLE
Update 3902 MM.40 Exocet Blk IIIC with newer generation seeker and add to other FREMMS 2024/2025

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4560]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3902

### Summary of Changes

Add a 2020 era seeker to this weapon. Seems to be a selling point feature that should improve the odds against countermeasures and jammers.

### Sources

https://www.navalnews.com/naval-news/2024/05/french-mod-procures-additional-exocet-mm40-b3c-anti-ship-missiles/
https://www.mbda-systems.com/product/exocet-mm40-block3/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
