### ISSUE TITLE
ShinMaywa US-2

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4565]
### DB Selector

DB3K

### Baseline

none

### Hypothetical

Yes

### Name

ShinMaywa US-2

### Country

Japan

### Service

JMSDF

### In Commission

2007-present

### Number in Service

8x + 1 (may already be in service)

### Length (m)

33.46

### Wingspan (m)

33.15

### Height (m)

9.8

### Empty Weight (kg)

25 630

### Maximum Takeoff Weight (MTOW) (kg)

47 700

### Payload Weight (kg)

unknown

### Crew

11

### Propulsion

4 × Rolls-Royce AE 2100J turboprop, 3,424 kW (4,592 hp) each

### Rate of Climb (ft/min)

unknown

### Service Ceiling (ft)

7195

### Military/Afterburner Speed (kt)

300

### Cruise Speed (kt)

260

### Supercruise

No

### Ferry Range (nm)

unknown max range 2300 nm

### Endurance (min)

unknown

### Takeoff / Landing Distance (m)

TOD ground: 490m @ MTOW/LD ground: 1,500m @ MTOW

### Fuel Capacity (kg)

unknown

### Sensors

Unknown. Unable to find details. Would assume typical military sea search and weather radar etc

### Mounts

none

### Loadout Options

SAR

### Comms/Datalinks

Unknown. Would assume typical military comms etc

### Aircraft Codes

Terrain Avoidance, Terrain Following, Fly-by-Wire, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

TOD water: 280m  @ Loaded/ LD water: 330m @ Loaded
1 × LHTEC T800 turbo-shaft, 1,017 kW (1,364 hp) compressor for boundary layer control
Also a civil fire-fighting variant
As of 2018, a total of six US-2s had been delivered while a further two aircraft were under production

### Sources

https://en.wikipedia.org/wiki/ShinMaywa_US-2
https://www.shinmaywa.co.jp/english/products/aircraft/amphibian/us2/capability.html
https://www.naval-technology.com/projects/shinmaywa-us-2-stol-search-and-rescue-amphibian/
https://www.shinmaywa.co.jp/english/products/aircraft/amphibian/us2/

**Comment by tbrandon517** [comment]
Could probably use the PS-1 as a baseline model to build off. DB3K Aircraft # 3317

https://cmano-db.com/aircraft/3317/

**Comment by trevor99999** [comment]
I notices that afterwards (did the US-2 before the US-1. On the other hand I don't know how close they have to be. The two a/c are close but the air-frames are not quite the same.

    On Tuesday, May 28, 2024 at 03:52:16 p.m. EDT, tbrandon517 ***@***.***> wrote:  
 
 


Could probably use the PS-1 as a baseline model to build off. DB3K Aircraft # 3317

https://cmano-db.com/aircraft/3317/

**Comment by tbrandon517** [comment]
> I notices that afterwards (did the US-2 before the US-1. On the other hand I don't know how close they have to be. The two a/c are close but the air-frames are not quite the same. On Tuesday, May 28, 2024 at 03:52:16 p.m. EDT, tbrandon517 ***@***.***> wrote: Could probably use the PS-1 as a baseline model to build off. DB3K Aircraft # 3317 https://cmano-db.com/aircraft/3317/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

As per the submission directions for baselines the PS-1 would probably be the most appropriate unit to use as a starting point.

"Baseline
Is there is an aircraft in the DB you recommend we start from? This is different from a "Copy Entry" in that most of its values will be changed, but we can use this to estimate anything we aren't sure of.

For example, a Boeing 777 is different enough from a 747 that we couldn't simply copy one to make the other -- but it's a fair starting point."

**Comment by PygmalionOfCyprus** [comment]
Added by @tbrandon517 in 507.
