### ISSUE TITLE
Shin Meiwa US-1A

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4566]
### DB Selector

Both

### Baseline

none

### Hypothetical

No

### Name

Shin Meiwa PS-1/US-1/US-1A

### Country

Japan

### Service

JMSDF

### In Commission

1971(PS-1) - 2017

### Number in Service

PS-1: 23/US-1: 6/US-1A: 14 

### Length (m)

33.46

### Wingspan (m)

33.15

### Height (m)

9.95

### Empty Weight (kg)

23 300

### Maximum Takeoff Weight (MTOW) (kg)

43,000 kg from water/45,000 kg from land

### Payload Weight (kg)

unknown

### Crew

7

### Propulsion

4 × Ishikawajima-Harima / General Electric T64-IHI-10J turboprop engines, 2,605 kW (3,493 hp) each

### Rate of Climb (ft/min)

1,601.0 ft/min @ MTOW/2,339.2 ft/min at 36,000 kg

### Service Ceiling (ft)

7,195 m @ MTOW/8,655 m @ 36,000 kg 

### Military/Afterburner Speed (kt)

276 kt

### Cruise Speed (kt)

230 kt

### Supercruise

No

### Ferry Range (nm)

Max range: 2,061 nm @ 230 kn/ at 3,050 m 

### Endurance (min)

unknown

### Takeoff / Landing Distance (m)

see below

### Fuel Capacity (kg)

1,640 L usable fuel in 5x wing tanks + 10,849 L usable fuel in 2x fuselage tanks

### Sensors

APS-80N Ocean search radar

### Mounts

none

### Loadout Options

SAR

### Comms/Datalinks

Unknown. Assuming typical military comms

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Take-off distance to 15 m (49 ft): 655 m (2,149 ft) 30° flap, BLC on, on land
Landing distance from 15 m (49 ft): 810 m (2,657 ft) 40° flap, BLC on, on land
Take-off distance: 555 m (1,821 ft) at 45,000 kg (99,208 lb) 40° flap, BLC on, on water
Landing distance: 220 m (722 ft) at 36,000 kg (79,366 lb) 60° flap, BLC on, on water
1 × Ishikawajima-Harima / General Electric T58-IHI-10-M2 turbo-shaft compressed air generator driving a C-2 compressor

### Sources

https://en.wikipedia.org/wiki/Shin_Meiwa_US-1A
https://simpleflying.com/shin-meiwa-stol-aircraft-story/
https://www.airvectors.net/avps1.html#m2
https://www.seaforces.org/marint/Japan-Maritime-Self-Defense-Force/AIRCRAFT/ShinMeiwa-US-1.htm

**Comment by tbrandon517** [comment]
The PS-1 exists in the and could be used as a baseline model to build US-1 abd any updated PS-1 versions. DB3K Aircraft # 3317

https://cmano-db.com/aircraft/3317/

**Comment by PygmalionOfCyprus** [comment]
Added by @tbrandon517 in 507.
