### ISSUE TITLE
Aircraft Saab 340 early warning and control (AEW&C) aircraft (ASC 890) Ukraine 2025?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4567]
### DB Selector

DB3K

### DBID to Copy

Saab 340 early warning and control (AEW&C) aircraft (ASC 890)

### Hypothetical

No

### Name

Saab 340 early warning and control (AEW&C) aircraft (ASC 890)

### Country

Ukraine 

### Service

Air Force

### In Commission

2025?

### Number in Service

2 

### Sensors

As baseline aircraft

### Mounts

As extant. 

### Loadout Options

AEWAC
Reserve
Ferry 

### Other Changes

Nil
If true? Life expectancy of this aircraft or time frame for crew training unknown. 

### Sources

https://www.regeringen.se/pressmeddelanden/2024/05/inbjudan-till-presstraff-om-militart-stod-till-ukraina/
https://x.com/Osinttechnical/status/1795724163652665813?t=kOKyMvh4NNLGtA0LaS-9Cw&s=19

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
