### ISSUE TITLE
Add out of service date of 2024 for Japanese Type 74 tank facility

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4569]
### DB Selector

DB3K

### Affected DBID(s)

Facility 1982

### Summary of Changes

Add out of service date of 2024

### Sources

https://www.janes.com/defence-news/news-detail/japan-decommissions-type-74-tanks
https://en.wikipedia.org/wiki/Type_74

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
