### ISSUE TITLE
MH-139A Grey Wolf - 2019, AW.139

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#457]
### DB Selector

DB3K

### Affected DBID(s)

aircraft/5277/DB3K

### Summary of Changes

Add 2x 7.62mm M240 machine guns, one on each side of the helicopter.

### Sources

https://www.thedrive.com/the-war-zone/32548/door-gunners-on-the-air-forces-new-grey-wolf-helicopters-need-protection-from-sub-zero-temps
https://www.airforcetimes.com/news/your-air-force/2021/02/21/still-2-years-away-minot-air-force-base-prepares-for-new-helicopters/?utm_campaign=Socialflow+AIR&utm_source=facebook.com&utm_medium=social&fbclid=IwAR1QahvfuJFhEIUJ_-XFgkn6c51I4mV1HSn8aKuno-GMkxDDlrhDj3s1GYI
![MFONW7SAVZDOVAWRALGRXULA3A](https://user-images.githubusercontent.com/99599482/156405098-97b9e6c3-03b4-4257-aac5-14fc150e4394.jpg)

**Comment by PygmalionOfCyprus** [comment]
Snuck into 493 at the last minute.
