### ISSUE TITLE
Change Stunner missile seeker to L band (millimeter wave), increase hit probability to 95% (David's Sling SAM)

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4570]
### DB Selector

DB3K

### Affected DBID(s)

sensor 5918

### Summary of Changes

Stunner missile is reported to use a millimeter wave active radar seeker that operates in the Ka band (30GHz+)

Also, given that the Stunner uses 4 methods of guidance in the terminal stage (SARH, IIR, EO, and ARH) the probability of hit should be higher than 85%, more closer to 90-95%, similar to the PAC-3 or Aster 30 Block 1 NT

Changes:
**-change ARH seeker band to L 
-increase Stunner hit probability to 95%**

![stunner](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/b9802ea4-d3d9-480a-9069-1f66913521e3)

### Sources

https://en.wikipedia.org/wiki/David%27s_Sling

**Comment by PygmalionOfCyprus** [comment]
>Stunner missile is reported to use a millimeter wave active radar seeker that operates in the Ka band (30GHz+)

What is the source for this information? It's not reflected anywhere in the wiki article as far as I can see.

**Comment by sr71xx** [comment]
> > Stunner missile is reported to use a millimeter wave active radar seeker that operates in the Ka band (30GHz+)
> 
> What is the source for this information? It's not reflected anywhere in the wiki article as far as I can see.

That's a good point, I just figured if it's rumored to have a milimeter wave seeker to enable HTK, it should have a similar K or L band seeker like the PAC 3 or Aster 30. But it's possible it doesn't need it since there is an EO and IIR seeker. 

But I do think hit probability should be increased from 85% to 95% since it has 3 seekers, just an estimate.

**Comment by PygmalionOfCyprus** [comment]
Yep, I went ahead and tweaked the PoH. Leaving the radar specs until we get actual data.
