### ISSUE TITLE
Add Chilean NASAMS II SAM 2015

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4572]
### DB Selector

DB3K

### DBID to Copy

Facility 3635

### Hypothetical

No

### Name

Sam Plt/2 (NASAMS II)

### Country

Chile

### Service

Air Force

### In Commission

2015

### Number in Service

x3

### Sensors

MPQ-64 Sentinel version 

### Sources

https://www.defensa.com/contenido-editorial/sistemas-defensa-aerea-fas-chile-poder-disuasion

Sipri Arms DB
Chile	Norway	2011		3		NASAMS-2	SAM system	3	?	2014; 2015	New	Part of $100 m deal

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
