### ISSUE TITLE
Chilean C-101 Aviojets retirement date 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4573]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3364, 3365

### Summary of Changes

Add out of service date of 2022

### Sources

https://twitter.com/SA_Defensa/status/1607891917878226944
https://es.wikipedia.org/wiki/CASA_C-101_Aviojet

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
