### ISSUE TITLE
Add Chilean KC-130R

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4574]
### DB Selector

DB3K

### DBID to Copy

Aircraft 632

### Hypothetical

No

### Name

KC-130R

### Country

Chile

### Service

Air Force

### In Commission

2016

### Number in Service

x2

### Sources

https://twitter.com/SA_Defensa/status/1627758380394708997
https://www.key.aero/article/chilean-kc-130r-fitted-new-np2000-props
Sipri
Chile	United States	2013	?	2		KC-130H Hercules	tanker/transport aircraft	2	?	2015; 2016	Second hand	Second-hand; aid; KC-130R version	15.2	30.4	30.4

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
