### ISSUE TITLE
Add Chilean AF Hermes 900 UAV

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4575]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4646

### Hypothetical

No

### Name

Hermes 900 UAV

### Country

Chile

### Service

Airforce 

### In Commission

2013

### Number in Service

3x,-1

### Sources

https://www.jetphotos.com/photo/10643066
https://www.suasnews.com/2011/06/elbit-systems-has-sold-its-newest-uav-the-hermes-900-to-chile/
https://elbitsystems.com/pr-new/elbit-systems-receives-order-for-the-120th-hermes-900-unmanned-aerial-vehicle/
https://airlive.net/military/2023/02/15/a-chilean-air-forces-drone-has-crash-landed-into-the-catuin-river/
Sipri
Chile	Israel	2011		3		Hermes-900	UAV	3	?	2013	New	$40 m deal	3	9	9

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
