### ISSUE TITLE
Jordanian C-101 Aviojet retired in 2018

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4576]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3666

### Summary of Changes

Add out-of-service date of 2018 

### Sources

https://www.keymilitary.com/article/jordan-modernises
https://en.wikipedia.org/wiki/CASA_C-101_Aviojet

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
