### ISSUE TITLE
Spanish Aviojet out of service in 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4577]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 811

### Summary of Changes

Add out of service date of 2022

### Sources

https://www.blogbeforeflight.net/2022/08/spanish-air-force-casa-c101-ends-trainer-role.html
https://www.key.aero/article/spain-replacing-casa-c-101-trainer-fleet-pilatus-pc-21-key-aero

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
