### ISSUE TITLE
Add Chilean Army Mistral 1992

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4578]
### DB Selector

DB3K

### DBID to Copy

Facility 2859

### Hypothetical

Yes

### Name

SAM Plt (Mistral 1 MANPADS x3)

### Country

Chile

### Service

Army

### In Commission

1992

### Sources

https://www.youtube.com/watch?v=_UEUjg_D6jM
https://en.wikipedia.org/wiki/Mistral_%28missile%29

Sipri
Chile	France	1989		500	?	Mistral	portable SAM	500	?	1991; 1992; 1993; 1994; 1995; 1996; 1997	New	Incl for Mygale SAM systems	0.09	45	45

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by bostonmyk** [comment]
not in 507

**Comment by PygmalionOfCyprus** [comment]
Reopening due to VC issue during DB handover on 31 May. Will have in for 508. Sorry again.

**Comment by PygmalionOfCyprus** [comment]
Re-handled 508.
