### ISSUE TITLE
Add Chilean AF Mygale Mistral SAM system

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4579]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Sec (Mygale [Mistral I] )

### Facility Type

SAM

### Country

Chile

### Service

Airforce

### In Commission

1997

### Number in Service

12x

### Crew

3

### Dispersion Radius (m)

40

### Sensors

TV Camera

### Mounts

2 Mygale Mistral Mounts (4 missiles each) + 1 Thomson CSF 2630P

### Comments

Radar Info from Jane's 

The radar used in the French Army and export versions of the post is
the Thomson-CSF 2D solid-state 2630P model. It is mounted on a
hydraulic mast for raising above the carrier vehicle when stationary so
as to improve the low level detection range coverage. The detection
range is approximately 18 000 m against aircraft and between 8000 and
9000 m against hovering helicopters. Automation of the radar functions
described above is performed through real-time data processing.
The post can monitor up to eight firing units including the Aspic
systems and. if required, other weapon types such MANPADS missile
systems or anti-airciaft guns through tactical terminals. The maximum
distance between the post and the firing unit is 5000 m. Data transmission
Thomson-CSF Samantha VSHORAD mobile command and control post
during trials with the French Armybetween them is via a radio frequency data link. The available firepower
display can be adapted to meet the expected threat and to show the
available anti-aircraft assets.
The Samantha system is the mobile shelter version for carriage on a
truck chassis and is fitted with full NBC and EMI protection

### Sources

Search Radar (its just search)

https://www.radartutorial.eu/19.kartei/04.battle/karte029.en.html

System in Chilean Service

https://www.infodefensa.com/texto-diario/mostrar/3111104/prokurica-constata-preparacion-comandos-artilleros-antiaereos-fach
https://ww2aircraft.net/forum/media/chilean-air-force-aspic-with-mistral-sam.20548/

Sipri Lines
Chile	France	1989		12		Mygale	SAM system	12	?	1997	New	For use with MISTRAL SAM	12.5	150	150

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by bostonmyk** [comment]
Don't see this one in 507

**Comment by PygmalionOfCyprus** [comment]
Reopening due to VC issue during DB handover on 31 May. Will have in for 508. Sorry again.

**Comment by PygmalionOfCyprus** [comment]
Re-handled 508.
