### ISSUE TITLE
212 [Pr.205ER] -- Cuba (Navy), 1979, 20x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#458]
### DB Selector

DB3K

### Affected DBID(s)

2175 and 3509

### Summary of Changes

When the Cuban Navy units were updated for V492 DBID #2175 was duplicated as 3509.

### Sources

DB3K v492

**Comment by KLABDB3K** [comment]
Which entry do you plan to revoke? - Assume its 3509? I have a scenario with Cuban Osa's off Angola.  
Its an easy fix in any event.

**Comment by PygmalionOfCyprus** [comment]
Replaced w/ Pr.1265 from #771.
