### ISSUE TITLE
Add Chilean AAA Plt/2 (20mm/95 Vulcan M163A1

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4580]
### DB Selector

DB3K

### DBID to Copy

Facility 2233

### Hypothetical

No

### Name

AAA Plt/2 (20mm/95 Vulcan M163A1) x 2

### Country

Chile

### Service

Army 

### In Commission

1999

### Sources

https://www.facebook.com/photo/?fbid=3523431047715615&set=pcb.3523432457715474
https://en.wikipedia.org/wiki/M163_VADS

Sipri Line
Chile	United States	1999		44		M-163 VADS	self-propelled AA gun	44	?	1999; 2000	Second hand	Second-hand; aid	0.4	17.6	17.6

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by bostonmyk** [comment]
Not in 507

**Comment by PygmalionOfCyprus** [comment]
Reopening due to VC issue during DB handover on 31 May. Will have in for 508. Sorry again.

**Comment by PygmalionOfCyprus** [comment]
Re-handled 508.
