### ISSUE TITLE
Add Chilean Army AAA Plt/2 (20mm/95 Vulcan M167 Towed) 1997

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4581]
### DB Selector

DB3K

### DBID to Copy

Facility 645

### Hypothetical

No

### Name

AAA Plt/2 (20mm/95 Vulcan M167 Towed) x2

### Country

Chile

### Service

Army

### In Commission

1997

### Sources

https://en.wikipedia.org/wiki/M167_VADS

Sipri Line
Chile	United States	1997		66		M-167 Vulcan	AA gun	66	?	1999; 2000	Second hand	Second-hand; aid	0.16	10.56	10.56

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by bostonmyk** [comment]
Not in 507

**Comment by PygmalionOfCyprus** [comment]
Reopening due to VC issue during DB handover on 31 May. Will have in for 508. Sorry again.

**Comment by PygmalionOfCyprus** [comment]
Re-handled 508.
