### ISSUE TITLE
Add Chilean Navy P-95A [EMB-111AN Bandeirulha] x6 1979

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4582]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2941

### Hypothetical

No

### Name

P-95A [EMB-111AN Bandeirulha]

### Country

Chile

### Service

Navy

### In Commission

1979

### Number in Service

6x

### Other Changes

Aircraft type is MPA

### Sources

https://www.airhistory.net/photo/528272/264
https://en.wikipedia.org/wiki/Embraer_EMB_110_Bandeirante#cite_ref-Pioneer_p170_15-7
https://www.facebook.com/media/set/?set=a.1146945398657506&type=3&_rdr
https://www.airteamimages.com/embraer-emb-110-bandeirante_264_chile---navy_124709
https://www.airliners.net/photo/Chile-Navy/Embraer-EMB-111AN-Bandeirulha/2078504
Sipri
Chile	Brazil	1977		6		EMB-111	maritime patrol aircraft	6		1978; 1979	New	EMB-111A(N) version	5.5	33	33

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by bostonmyk** [comment]
This one may not have made it in.

**Comment by PygmalionOfCyprus** [comment]
Just looked into this. Looks like we had a version control failure on May 31 where the up-to-date DB was mistakenly overwritten by the prior day's version and incorrectly iterated to indicate that it was the current version. I'll re-do all the tickets marked closed on the 31st.

Sorry for the inconvenience.

**Comment by PygmalionOfCyprus** [comment]
Reopening due to VC issue during DB handover on 31 May. Will have in for 508. Sorry again.

**Comment by bostonmyk** [comment]
No worries

**Comment by PygmalionOfCyprus** [comment]
Re-handled 508.
