### ISSUE TITLE
Chilean Hunter out of service date is 1995

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4583]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 88

### Summary of Changes

Add out of service date of 1995

### Sources

https://airvectors.net/avhunt_2.html
https://www.reddit.com/r/WarplanePorn/comments/12z7exe/hawker_hunter_wednesday_chilean_air_force_mk71/
https://www.britmodeller.com/forums/index.php?/topic/235113095-148-hawker-hunter-mk71-fga-9-chilean-air-force-airfix-kit/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by PygmalionOfCyprus** [comment]
Reopening due to VC issue during DB handover on 31 May. Will have in for 508. Sorry again.

**Comment by PygmalionOfCyprus** [comment]
Re-handled 508.
