### ISSUE TITLE
Add Chilean M730 Chaparral SAM

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4584]
### DB Selector

DB3K

### DBID to Copy

Facility 2229

### Hypothetical

No

### Name

SAM Plt/2 (Chaparral x2)

### Country

Chile

### Service

Army

### In Commission

1981-2024

### Number in Service

28x

### Sources

https://en.wikipedia.org/wiki/MIM-72_Chaparral
https://www.defenseindustrydaily.com/chile-buying-american-for-low-level-air-defense-05945/
https://www.militaryfactory.com/armor/detail.php?armor_id=80

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by PygmalionOfCyprus** [comment]
Reopening due to VC issue during DB handover on 31 May. Will have in for 508. Sorry again.

**Comment by PygmalionOfCyprus** [comment]
Re-handled 508.
