### ISSUE TITLE
The R-27ER shouldn't be available for Chinese SU-27s untill after 2000

### ISSUE THREAD

**Issue by billibob1997** [PygmalionOfCyprus/cmo-db-requests#4585]
### DB Selector

DB3K

### User(s)

Chinese SU-27 (1994)

### Weapons Carried

2-4 R-73

4-6 R-27R/T

4-6 R-27ER/ET
(shouldn't be available untill after 2000)

"China ... has expressed interest in the long burn AA-10 and AA-X-12"

AA-X-12 is the prototype R-77

https://www.cia.gov/readingroom/docs/DOC_0005526244.pdf

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

The same as with the 27R or 27T

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The R-27ER/ET should not be available to 
Chinese SU-27s untill after 2000.

### Sources

https://www.cia.gov/readingroom/docs/DOC_0005526244.pdf

**Comment by billibob1997** [comment]
The "long burn AA-10" is a refrence to the extended range R-27ER/ET and not the baseline 27R or 27T.

1996 Taiwan Crisis PLAAF SU-27s should be using the R-27R or 27T as their medium range AAMs.

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
