### ISSUE TITLE
The R-77 should not be available untill after 2000

### ISSUE THREAD

**Issue by billibob1997** [PygmalionOfCyprus/cmo-db-requests#4586]
### DB Selector

DB3K

### User(s)

R-77, 1994 (in older DBs it says 1999 which isn't accurate either)

### Weapons Carried

R-77

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The weapon was designated as AA-X-12 by the CIA in 2000 meaning it was still in development.

### Sources

https://www.cia.gov/readingroom/docs/DOC_0005526244.pdf

**Comment by billibob1997** [comment]
"China plans to acquire advanced air to air missiles and has expressed interest in the long burn AA-10 and the AA-X-12. However negotiations may be tied to China's development of the PL-12."

https://www.cia.gov/readingroom/docs/DOC_0005526244.pdf

**Comment by PygmalionOfCyprus** [comment]
What aircraft have the R-77 before 2000? Despite the erroneous comment on the weapon itself in the DB it seems the loadouts mostly reflect reality.
