### ISSUE TITLE
Add Cameroon MI-35/MI-24V 2016

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4587]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5771

### Hypothetical

Yes

### Name

Mi-24V Hind E [MI-35]

### Country

Cameroon

### Service

Airforce 

### In Commission

2016

### Number in Service

4x

### Sources

Pictures
https://twitter.com/HammerOfWar5/status/1607019250496970756
https://twitter.com/HammerOfWar5/status/1781742084090638470
https://twitter.com/HammerOfWar5/status/1664325656983764992

Sipri Lines
Cameroon	Russia	2015		2	?	Mi-24V/Mi-35	combat helicopter	2	?	2016	Second hand but modernized	Second-hand but modernized before delivery; for use against Boko Haram rebels	5.61	11.22	11.22
Cameroon	Slovakia	2014	?	2		Mi-24V/Mi-35	combat helicopter	2		2016	Second hand	Second-hand (modernized in Poland before delivery)	3.4	6.8	6.8

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
