### ISSUE TITLE
Add Norwegian and Estonian SAM Sec (PPZR Piorun [Grom-M] Manpads x3)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4588]
### DB Selector

DB3K

### DBID to Copy

Facility 3525

### Hypothetical

Yes

### Name

SAM Sec (PPZR Piorun [Grom-M] Manpads x3)

### Country

Estonia, Norway

### Service

Estonian Army, Norwegian Army

### In Commission

2024 (Estonia, Norway)

### Sources

Estonia

https://twitter.com/MoD_Estonia/status/1796902606477930561
https://www.janes.com/defence-news/news-detail/estonia-receives-piorun-manpads
https://breakingdefense.com/2024/01/in-first-estonian-defense-unit-receives-polish-piorun-manpads/

Norway
https://www.mesko.com.pl/en/news/the-company-delivers-first-batch-of-piorun-manpads-to-norway
https://www.janes.com/defence-news/news-detail/norway-orders-polish-piorun-manpads
https://defence-industry.eu/norway-deploys-piorun-air-defence-systems-along-the-russian-border/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
