### ISSUE TITLE
250 [Pr.205] -- Cuba (Navy), 1972-1999, 6x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#459]
### DB Selector

DB3K

### Affected DBID(s)

2013 and 3501

### Summary of Changes

for v492 Cuban Navy updated DBID #2013 duplicated as 3501.

### Sources

DB3K v492

**Comment by PygmalionOfCyprus** [comment]
Replaced w/ Pr.1265 from #771.
