### ISSUE TITLE
Reduce UMPK FAB-250M-62 Loadout sizes to 4 on SU-34s and SU-35

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4590]
### DB Selector

DB3K

### Affected DBID(s)

Loadout 32900,32901, 32902

### Summary of Changes

Reduce loadout to 4 on both SU-34s and SU-35

### Sources

https://twitter.com/GuyPlopsky/status/1797166404934013429

**Comment by bostonmyk** [comment]
https://twitter.com/GuyPlopsky/status/1799028881292447785

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
