### ISSUE TITLE
Add Ecuadorian SAM Bn/2 (SA-8B Gecko Mod-1 [9K33M3 Osa-AKM]) 2001-2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4591]
### DB Selector

DB3K

### DBID to Copy

Facility 3984

### Hypothetical

No

### Name

SAM Bn/2 (SA-8B Gecko Mod-1 [9K33M3 Osa-AKM])

### Country

Ecuador

### Service

Army

### In Commission

2001-2023

### Number in Service

10x, -6

### Sources

https://twitter.com/trip_to_valkiri/status/1750630676385107996
https://mil.in.ua/en/news/ecuador-plans-to-deliver-osa-akm-sam-to-ukraine-through-the-united-states/#google_vignette
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Ecuadorian_Armed_Forces

Sipri Lines
Ecuador	Ukraine	1997	?	250	?	9M33	SAM	250	?	2001	Second hand	Second-hand	0.04	10	10
Ecuador	Ukraine	1997	?	10	?	Osa	mobile SAM system	10	?	2001	Second hand	Second-hand	4	40	40

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
