### ISSUE TITLE
Add Czech Republic SAM Plt (SA-13 Gopher [9k35 Strela-10])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4592]
### DB Selector

DB3K

### DBID to Copy

Facility #1481

### Hypothetical

Yes

### Name

SAM Plt (SA-13 Gopher [9k35 Strela-10])

### Country

Czech Republic

### Service

Army

### In Commission

1992-Present

### Sources

Pictures
https://twitter.com/Danny_elMayor/status/1633573482402291713/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
