### ISSUE TITLE
Add Cambodian SAM Bty (KS-1C [HQ-12])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4593]
### DB Selector

DB3K

### DBID to Copy

Facility 3072

### Hypothetical

Yes

### Name

SAM Bty (HQ-12)KS-1C

### Country

Cambodia

### Service

Army

### In Commission

2023

### Number in Service

1x

### Sources

https://armyrecognition.com/news/army-news/2023/cambodian-army-now-equipped-with-chinese-made-ks-1c-kaishan-1c-air-defense-system
https://twitter.com/Defence_IDA/status/1706892857582473485
Sipri
Cambodia	China	2022	?	40	?	KS-1A	SAM	40	?	2023	New	For KS-1 SAM system; KS-1C version	0.17	6.8	6.8
Cambodia	China	2022	?	1	?	KS-1A	SAM system	1	?	2023	New	KS-1C version	47	47	47

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
