### ISSUE TITLE
Add Cambodian Mig-21bis 1986-1996

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4595]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2722

### Hypothetical

No

### Name

Mig-21bis Fishbed L 

### Country

Cambodia

### Service

Airforce

### In Commission

1986-1996

### Number in Service

18x

### Sources

https://www.airhistory.net/photo/168953/7112
https://www.airhistory.net/photo/82604/7117
https://www.airliners.net/photo/Cambodia-Air-Force/Mikoyan-Gurevich-MiG-21bis/772845
https://www.aeroflight.co.uk/waf/aa-eastasia/cambodia/sqns/ftr_sqn.htm
https://en.wikipedia.org/wiki/List_of_Mikoyan-Gurevich_MiG-21_operators

Sipri
Cambodia	Bulgaria	1986	?	18	?	MiG-21bis	fighter aircraft	18	?	1986	Second hand	Second-hand; supplier uncertain; no. could be 16	5	90	90

**Comment by bostonmyk** [comment]
https://www.facebook.com/375609672631903/photos/a.404630323063171/410723305787206/?type=3

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
