### ISSUE TITLE
Add Cambodian FN-6 MANPADS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4598]
### DB Selector

DB3K

### DBID to Copy

Facility 2799

### Hypothetical

Yes

### Name

SAM Sec (FN-6 Manpads)

### Country

Cambodia

### Service

Army

### In Commission

2009

### Sources

https://defense-studies.blogspot.com/2015/11/china-supplies-cambodia-with-anti.html
https://www.armyrecognition.com/military-products/army/air-defense-systems/man-portable-air-defense-systems/fn-6-china-uk

Sipri
Cambodia	China	2008	?	50	?	FN-6	portable SAM	50	?	2009	New	Possibly FN-16 version	0.08	4	4

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
