### ISSUE TITLE
Add Cambodian F-6C Farmer 1978

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4599]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3010

### Hypothetical

No

### Name

F-6C Farmer 

### Country

Cambodia

### Service

Airforce

### In Commission

1978

### Number in Service

6x

### Sources

https://www.key.aero/article/story-mig-19
https://www.aeroflight.co.uk/waf/aa-eastasia/cambodia/cam-af4-aircraft.htm
https://airfighters.com/photo/127983/M/Cambodia-Air-Force/Shenyang-J-6/30-950/

Sipri
Cambodia	China	1978	?	6	?	F-6	fighter aircraft	6	?	1978	Second hand	Probably Second-hand; aid against Vietnemese invasion	2	12	12

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
