### ISSUE TITLE
SOT-S Radar-Pantsir S2 and M Radar

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#46]
### DB Selector

DB3K

### Hypothetical

- [ ] Yes

### Name

SOT-S Radar

### Sensor Generation

Early 2020s

### Sensor Capabilities

Air Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Generates AAW Fire-Control Data

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm

### Scan Interval (s)

120/RPM

### Vertical Beamwidth (deg)

90

### Comments

Surveillance and Fire Control Radar for Pantsir S2 and Pantsir SM, Adds maybe 4 km range than earlier system but get 360 and better UAV detection.

### Sources

https://twitter.com/Cyberspec1/status/1256719757459386368
https://thaimilitaryandasianregion.wordpress.com/2015/10/30/pantsir-s1/
https://twitter.com/ralee85/status/1234970696138100736?lang=en

**Comment by Jkryos** [comment]
Added DB3K 493.

**Comment by KLABDB3K** [comment]
https://www.defenseworld.net/news/27041/Are_Haftar_Army___s_Pantsir_Missile_Systems_supplied_only_by_UAE_#.YhI76VDP2Cg

“Hard to be sure, but it appears the aquisition radar is the newer octagonal-shaped S-band 1RS1-3-RLM radar. It is not the older rectangular radar which all Emirati Pantsirs have,” the expert [noted](https://twitter.com/RALee85/status/1263211211304382469?s=20).
The Pantsir S2 system that entered Russian military service in 2015 uses the latest S-band radar and KAMAZ 6560 8x8 truck chassis. It is an improved version of S1 with a range of reportedly over 40km. It uses the same missile launcher and anti-aircraft cannons.
