### ISSUE TITLE
Add Cambodian Strela-7B Manpads

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4600]
### DB Selector

DB3K

### DBID to Copy

Facility 1879

### Hypothetical

No

### Name

SAM Sec (SA-7b Grail [9K32M Stela-2M] MANPADS x 3)

### Country

Cambodia

### Service

Army

### In Commission

1978

### Sources

https://amcmuseum.org/history/cambodian-rice-airlift/
Sipri
Cambodia	Soviet Union	1987	?	233	?	Strela-2	portable SAM	233	?	1987; 1988	New		0.04	9.32	9.32

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
