### ISSUE TITLE
Add Cambodian SAM Bn (SA-3b Goa [S-125M Pechora]) 1980-2004

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4602]
### DB Selector

DB3K

### DBID to Copy

Facility 1297

### Hypothetical

No

### Name

SAM Bn (SA-3b Goa [S-125M Pechora])

### Country

Cambodia

### Service

Air Force

### In Commission

1980-2004

### Number in Service

1x

### Sources

https://www.gettyimages.dk/detail/news-photo/cambodian-military-officers-prepare-to-destroy-russian-made-news-photo/56220505?adppopup=true
https://www.flickr.com/photos/xwanna/64514944

Sipri Lines
Cambodia	Soviet Union	1980	?	36	?	V-601	SAM	36	?	1980	New		0.12	4.32	4.32
Cambodia	Soviet Union	1980	?	1	?	S-125 Pechora	SAM system	1	?	1980	New		17.5	17.5	17.5

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
