### ISSUE TITLE
Add Cambodian P 1123 [Pr.206 Shershen] 2006-2015

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4603]
### DB Selector

DB3K

### DBID to Copy

Ship #125

### Hypothetical

No

### Name

P 1123 [Pr.206 Shershen]

### Country

Cambodia

### Service

Navy

### In Commission

2006-2015

### Number in Service

2x

### Mounts

Remove Torpedo Tubes

### Sources

https://en.wikipedia.org/wiki/Royal_Cambodian_Navy
https://www.cpf.navy.mil/Newsroom/News/Article/2745360/us-navy-royal-cambodian-navy-kick-off-carat-cambodia/

Sipri
Cambodia	Viet Nam	2005	?	2		Project-206P	patrol craft	2		2006	Second hand	Second-hand; aid	6.8	13.6	13.6

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
