### ISSUE TITLE
Add Cambodian P 1121 [Pr.206M Turya] 1985-2015

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4604]
### DB Selector

DB3K

### DBID to Copy

Ship 244

### Hypothetical

Yes

### Name

P 1121 [Pr.206M Turya]

### Country

Cambodia

### Service

Navy

### In Commission

1985-2015

### Number in Service

2x

### Sources

https://en.wikipedia.org/wiki/Royal_Cambodian_Navy

Sipri Lines
Cambodia	Soviet Union	1984	?	2		Project-206M Shtorm	FAC	2		1984; 1985	New		25	50	50

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
