### ISSUE TITLE
Add Cambodian P 1102 Koh Pothi [Swift] Patrol Boat

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4606]
### DB Selector

DB3K

### DBID to Copy

Ship 319

### Hypothetical

No

### Name

 P 1102 Koh Pothi [Swift] 

### Country

Cambodia

### Service

Navy

### In Commission

1975

### Number in Service

17x, -15

### Sources

https://cne.wtf/2021/12/05/khmer-rouge-navy-battle-history-1975-79/
https://en.wikipedia.org/wiki/Patrol_Craft_Fast
Combat Fleets 2007 pg 74. Confirms they are Mk.2

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
