### ISSUE TITLE
Add Cambodian L 1401 [Type 069 Luqin] x1 2007

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4607]
### DB Selector

DB3K

### DBID to Copy

Ship 3780

### Hypothetical

No

### Name

L 1401 [Type 069 Luqin]

### Country

Cambodia

### Service

Navy

### Number in Service

x1

### Sources

https://en.wikipedia.org/wiki/Royal_Cambodian_Navy
https://www.stripes.com/theaters/asia_pacific/2022-06-07/cambodia-denies-secret-chinese-naval-facility-6261919.html
https://commons.wikimedia.org/wiki/File:Royal_Cambodian_Military_DVIDS70882.jpg
https://www.navypedia.org/ships/china/ch_ls_68.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
