### ISSUE TITLE
Add Cambodian P 1101 Koh Yor [Zhuk 1400ME] Patrol Boat

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4609]
### DB Selector

DB3K

### DBID to Copy

Ship 4243

### Hypothetical

No

### Name

P 1101 Koh Yor [Zhuk 1400ME]

### Country

Cambodia

### Service

Navy

### In Commission

1985

### Number in Service

2x,-1

### Sources

https://en.wikipedia.org/wiki/Royal_Cambodian_Navy
https://shipshub.com/navy/10-1.html#lg=1&slide=11
https://www.navypedia.org/ships/cambodia/ca_cf_41.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
