### ISSUE TITLE
Add Cambodian KS-19 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4610]
### DB Selector

DB3K

### DBID to Copy

Facility 1885

### Hypothetical

No

### Name

AAA Bty (100mm KS-19 x6, Fire Can FCR]

### Country

Cambodia

### Service

Army

### In Commission

1967

### Sources

Sipri
Cambodia	Soviet Union	1967	?	8		KS-19 100mm	AA gun	8		1967	Second hand	Second-hand; aid	0.24

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
