### ISSUE TITLE
Weapon & Mount Copy  7.62mm Mini gun M134 for Russian GShG-7.62 ground/air pintle  mount. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4611]
### DB Selector

DB3K

### DBID to Copy

M134  type 7.62mm Mini gun. Externally powered multi barrel machine gun

### Hypothetical

No

### Name

GShG-7.62 

### Country

Russia

### Service

Army/Navy/Airforce 

### In Commission

2024 

### Number in Service

Multiple 

### Sensors

Mk 1 eyeball. 

### Mounts

Pintle manual ground Naval mount and air mount. 

### Loadout Options

N/A

### Other Changes

Modification of existing GShG-7.62 used in Ka-29 Assault transport but in pintle mount for cabin and boat use. 

### Sources

https://x.com/RALee85/status/1797639080328704331?t=_XeuICZ8vNKGlAG5XYy-xA&s=19

**Comment by PygmalionOfCyprus** [comment]
We'll just use generic MG/minigun weapon records for this, Command has no difference between different 7.62mm entries and I'm trying to move away from creating new "weapons" for every gun variant.
