### ISSUE TITLE
Update and addition: SM-6 anti CM and SSM

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4612]
- Pending potential sim side tweaks and additions: 

1. Add SARH seeker. 
2. Add passive radar seeker to SSM capable variants (all except Blk I and Dual I and II). 

~- Air launched variant seen on F-15 and F/A-18: 
Assuming upper stage of Blk IA used. Mk104 dual thrust motor (shared by SM-2MR Blk III) has 54 secs burn time in game with max speed of 2900kt. A moderate estimate of range would be 230nm, the same as ground launched variant with Mk72 booster and fits with the 2x to 3x range of that of the SM-2MR Blk III. We may also see its target ceiling expanded to 45km, similar to Sky Bow 3. 
The SSM capability would be retained with a proposed 300nm range. 
Before any indication to the contrary however it's appropriate to limit the target speed to the same 2900kt as SM-2 (with its DEZ allowing limited counter HGV, HCM as an interim GPI and have a chance against WZ-8). 
CEC DL and AIM-120 DL would be needed. 
2x on F/A-18 and option for 2x and 4x for F-15E.~

**Comment by tbrandon517** [comment]
Related #1658

**Comment by tbrandon517** [comment]
Update. Also shared on related request entry.

https://www.twz.com/sea/super-hornet-armed-with-sm-6-missile-spotted-over-california?fbclid=IwZXh0bgNhZW0CMTEAAR2OYxhaeYmvrbiAtZ9fmLj10sBqd9YzgtsumsDwY_N4dGrcW3IRLY5dksY_aem_ATLy3maLne8ahUwCLJV43t-q_fbjoLt8BS-XGNl28GQGu8aX_FILJEu1zrjSp4NnUzgfJq1nVS8V1zwjM0__hIgm

**Comment by tbrandon517** [comment]
More

https://www.navalnews.com/naval-news/2024/06/air-launched-sm-6-spotted-again-on-f-a-18-super-hornet/?fbclid=IwZXh0bgNhZW0CMTEAAR0sMZWPZcXkZLl9icyNQXyIKJVSvZZPzVvpnlMeD7VsGA3FHhPkmnOQTes_aem_ATIZ1wIXnBhqNsUSsCG5tA2817J1I1ITL1lZNB5D9Rgf_vqB87iIBrvl05Go3dluwh5B5l2GwApzd_xZ-qX30Ugv

**Comment by tbrandon517** [comment]
Additional 

https://theaviationist.com/2024/06/04/u-s-navy-super-hornet-with-sm-6/

**Comment by tbrandon517** [comment]
Additional 

https://www.twz.com/air/aim-174-super-hornet-launched-variant-of-sm-6-missile-breaks-cover-in-hawaii?fbclid=IwZXh0bgNhZW0CMTEAAR36YgIPkCRLKoqlAUX2kTlgecqSxohmktMvMXLA0BiQbZoQs0GlydiTQGM_aem_4lbgzTEQWrXJEQQIgkS5ng

**Comment by HunterDNiu** [comment]
Closed in favor of #7404.

**Comment by tbrandon517** [comment]
#4704

**Comment by Huib18** [comment]
Some calculatations which possibly may help.
Mk72 is the booster which is lacking.

![GRlzGT0aUAAgbK5](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/06a3d931-2fb3-45e4-b0b1-715b2aa77f5d)
![GRlzKMpXoAAHCWo](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/60408110/2e23da0d-0a4a-4688-9e67-048c5eafea7e)

The booster should add 830m/s in ∆V, at 40k feet, that's a very non negligible amount... 
If I had to guess a random range, 600ish km.
[https://twitter.com/AWeirdPhysicist/status/1808603356803277137](url)
[https://twitter.com/AWeirdPhysicist/status/1808605347793256534](url)

**Comment by tbrandon517** [comment]
Operationally Deployed 

https://www.navalnews.com/naval-news/2024/07/u-s-navy-confirms-sm-6-air-launched-configuration-is-operationally-deployed/?fbclid=IwZXh0bgNhZW0CMTEAAR3k0OCp7QRakD-qoAY5f10W0J8qI2hfCi-cEUoqR7pFed3XP0ckBLZU5wY_aem_9C6NTWVB8LZuK5FtkwMzGw
