### ISSUE TITLE
Add Cambodian AAA Bty (37mm Type 65 Twin x4) 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4613]
### DB Selector

DB3K

### DBID to Copy

Facility 70

### Hypothetical

No

### Name

AAA Bty (37mm Type 65 Twin x4) 

### Country

Cambodia

### Service

Army

### In Commission

2015

### Sources

https://english.cambodiadaily.com/news/china-donates-heavy-weaponry-to-military-84249/

**Comment by bostonmyk** [comment]
https://defense-studies.blogspot.com/search?q=Cambodia&updated-max=2020-03-17T11:52:00%2B07:00&max-results=20&start=39&by-date=false

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
