### ISSUE TITLE
Add Cambodian AAA Bty(37mm M1939 x6)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4614]
### DB Selector

DB3K

### DBID to Copy

Facility 1886

### Hypothetical

No

### Name

AAA Bty(37mm M1939 x6)

### Country

Cambodia

### Service

Army

### In Commission

1968

### Sources

https://en.wikipedia.org/wiki/37_mm_automatic_air_defense_gun_M1939_(61-K)
https://www.gettyimages.com/detail/news-photo/an-air-defense-system-unit-parades-during-a-ceremony-news-photo/1948411301?adppopup=true

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
