### ISSUE TITLE
Add Cambodian Mi-8T Hip C 1988

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4616]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2342

### Hypothetical

No

### Name

Mi-8T Hip C

### Country

Cambodia

### Service

Airforce

### In Commission

1988

### Number in Service

4x, -2

### Sources

https://www.aeroflight.co.uk/waf/aa-eastasia/cambodia/cam-af-aircraft.htm
https://www.airliners.net/photo/Cambodia-Air-Force/Mil-Mi-8T/1208659

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
