### ISSUE TITLE
increase max target speed to 4800m/s (40N6)

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4620]
### DB Selector

DB3K

### Affected DBID(s)

weapon 2104

### Summary of Changes

The Almaz Antey brochure depicts the 40N6 with a maximum target speed for standard/tactical ballistic missiles is shown as 4800 m/s (~mach 14 / 9334 kts)

Tweaks:
-increase max target speed to mach 14 (9334 kts)
![40n6 4](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/97b73fdd-7cd3-4505-b6d2-99163ee45028)
![39913603_2077380419146430_2721734454946037760_o](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/de3def51-7cd8-4ce3-86d5-0f70d9846540)
![39973370_2077380252479780_9194899856836001792_o](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/b0bee7a0-42f2-49b9-ba1a-254ae7b28570)

### Sources

https://alert5.com/2018/08/24/40n6-3d-image-revealed/
https://kartinki.pibig.info/33990-almaz-antej-kartinki.html#google_vignette
https://123ru.net/mix/173243565/
https://en.wikipedia.org/wiki/S-400_missile_system#Structure
https://www.yandex.com/images/search?cbir_id=6367910%2FvSs9irGRj5MDS71Tf6NjMA2990&rpt=imageview&url=https%3A%2F%2Favatars.mds.yandex.net%2Fget-images-cbir%2F6367910%2FvSs9irGRj5MDS71Tf6NjMA2990%2Forig

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
