### ISSUE TITLE
Add Argentine Navy B-200 Cormoran [TC-12B ] Huron MPA x2 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4621]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5972

### Hypothetical

No

### Name

B-200 Cormoran [TC-12B ] Huron

### Country

Argentina

### Service

Navy

### In Commission

2023

### Number in Service

2x

### Sensors

Ventral radar (bump) is  RDR-1500 (sensor 1974 in DB)

### Sources

https://aviones.com/argentina-se-comprarian-cuatro-beechcraft-huron-mas-dos-para-la-fuerza-aerea-y-dos-para-la-armada/
https://aviones.com/la-armada-argentina-se-prepara-para-recibir-el-proximo-beechcraft-tc-12b-huron/
https://twitter.com/AviacionDefensa/status/1797706152509346094

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
