### ISSUE TITLE
China, PLAN, Type XXX Stealth Corvette, new technology testbed?

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4622]
### DB Selector

DB3K

### Hypothetical

No

### Name

Type XXX Stealth Corvette

### Service

PLAN

### In Commission

2023

### Number in Service

1x

### Length (m)

97

### Beam (m)

12

### Draft (m)

5

### Standard Displacement (t)

1800

### Full Displacement (t)

2000

### Complement

30

### Primary Propulsion Type

Diesel

### Propulsion

same as 056a?

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

5000nm at 18kt

### Sensors

1x Type XXX X-band Radar
others just same as type 056A for the moment?

### Mounts

2x 8-cell UVLS, able to carry: FM-3000N Quad-pack SAM, HHQ-9B, Yu-8 ASROC, YJ-83B (CM-802B)
24x HHQ-10
others just same as type 056A for the moment?

### Comms/Datalinks

datalink for HHQ-9B & FM-3000N
China CEC command link

### Ship Codes

Nuclear Shock Resistant, Degaussed Steel Hull, Advanced Quieting

### Comments

Since this is a test platform, we can in a sense put export products like FM-3000N on it. We have reason to believe that the testbed is testing some products that are not currently introduced to the PLAN.

It’s RCS and IR signature should be at least the same level with Visby **Ship 3345**

### Sources

https://www.sinodefenceforum.com/t/corvette-light-frigate-thread-056a-sub-4000t-ffls.9102/page-14
https://www.navalnews.com/naval-news/2024/05/chinese-experimental-corvette-starts-sea-trials/
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/caabae87-f94c-4af7-aa2d-09a83e545a0c)

**Comment by LuigiP57** [comment]
#4369

**Comment by LuigiP57** [comment]
Should be HT-1/GJB-5860 850mm-UVLS. Doesn't see the sign of uptake hatch, which is the feature of H/AKJ-16 VLS.
https://twitter.com/AlexLuck9/status/1839861789007458527
![image](https://github.com/user-attachments/assets/db8c7343-c510-4d47-b5f5-674d694563ad)

**Comment by PygmalionOfCyprus** [comment]
Handled 509. I don't think the YJ-83B is capable of being fired from a VLS. If it has any anti-ship munitions in there it would be YJ-18s or YJ-100s(?). Alternatively internal YJ-83 launch boxes hidden behind those side panels, like how such ships handle torpedo launchers and the like.
