### ISSUE TITLE
C-5 Aerial Tanker Refuelling

### ISSUE THREAD

**Issue by Quark-73** [PygmalionOfCyprus/cmo-db-requests#4626]
### DB Selector

DB3K

### User(s)

USAF C-5

### Weapons Carried

none

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

4000 nm (?) but depends on fuel given to tanker

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

This loudout should only work for re-fuelling tanker aircrafts with a boom. 

### Sources

https://www.travis.af.mil/News/Display/Article/3620886/team-travis-flyers-conduct-reverse-flow-air-refueling/ 

https://www.airandspaceforces.com/c-5-super-galaxy-refueling/

**Comment by PygmalionOfCyprus** [comment]
This is a cool experiment and potentially an interesting future capability if it becomes a more regular occurrence, but so far it's too experimental to add as an actual "capability" in Command. The refueling logic also can't handle this right now so I don't have a good way to model it.
