### ISSUE TITLE
SAM Bty (SA-4 Ganef [2K11 Krug]) (3x Bty pr Bn, 3x Bn + Long Track + Thin Skin B HF pr Bde)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#463]
### DB Selector

DB3K

### DBID to Copy

facility/295/DB3K

### Hypothetical

No

### Name

SAM Bty (SA-4 Ganef [2K11 Krug]) (3x Bty pr Bn, 3x Bn + Long Track + Thin Skin B HF pr Bde)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Known Changes

### Mounts

No Known Changes

### Loadout Options

No Known Changes

### Other Changes

No Known Changes

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
