### ISSUE TITLE
RCAF Dash-8 Q400 x3 2029-

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#4630]
### DB Selector

DB3K

### DBID to Copy

4009 DB3K

### Hypothetical

No

### Name

Dash-8-400

### Country

Canada

### Service

Royal Canadian Air Force (SkyAlyne)

### In Commission

2029-

### Number in Service

3

### Sensors

1x Generic Surface Search Radar
1x Mk1 Eyeball

### Other Changes

CT-142 Gonzo replacement, same loadouts.

### Sources

https://skiesmag.com/press-releases/skyalyne-awarded-11-2b-contract-for-canadas-future-aircrew-training-program/

https://issues.skiesmag.com/554/766/188784/RCAF-Today-2023/index.html?page=82&_gl=1*me7b2s*_ga*Mzk1NTcxMzgxLjE3MTc5NTgzMTQ.*_ga_WXQK141J8Z*MTcxNzk1ODMxMy4xLjAuMTcxNzk1ODMxMy4wLjAuMA..

https://theaviationist.com/2024/06/04/canada-eyes-acquisition-of-70-trainers/

https://www.avweb.com/aviation-news/canada-awards-8-1-billion-military-flight-training-contract/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
