### ISSUE TITLE
French C.160G Elint Aircraft out of service date 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4632]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3474

### Summary of Changes

Add out of service date of 2021
Name was Gabriel
Quantity end of life was 2x

### Sources

https://www.scramble.nl/military-news/french-gabriels-retires-ahead-of-schedule
https://www.scramble.nl/military-news/interim-electronic-intelligence-aircraft-for-the-french-air-and-space-force

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
