### ISSUE TITLE
Add Iraqi CH-5 UCAV

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4633]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4727

### Hypothetical

Yes

### Name

CH-5 [Rainbow]

### Country

Iraq

### Service

Airforce

### In Commission

2024

### Loadout Options

Not sure if FT-7 SDB exported yet. Missile loadouts fine. 

### Sources

https://www.scramble.nl/military-news/ch-5-ucas-emerges-in-iraq
https://twitter.com/sharif_ali103/status/1783169968143470633/photo/1
https://twitter.com/obretix/status/1784560025521848358

**Comment by PygmalionOfCyprus** [comment]
Already in DB 506. (I know you guys don't have it yet, just marking for record...)
