### ISSUE TITLE
Add Vietnamese Mi-24A x10 1980-1994

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4634]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5920

### Hypothetical

No

### Name

Mi-24A Hind

### Country

Vietnam

### Service

Air force

### In Commission

1980-1994

### Number in Service

10x

### Other Changes

out-of-service date murky but most think mid 90s
Rambo kind of got it right too

### Sources

https://twitter.com/AnnQuann/status/1800394576123052104
http://defense-studies.blogspot.com/2012/09/vietnam-to-improve-us-rocket-equipped.html

Sipri Line
Viet Nam	Soviet Union	1979	?	10	?	Mi-24A	combat helicopter	10	?	1980	Second hand	Probably second-hand	2.65	26.48	26.48

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
