### ISSUE TITLE
Update Vietnamese Svetlak SA-N-5 Mount with SA-N-10 Mount

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4635]
### DB Selector

DB3K

### Affected DBID(s)

Ship 2568

### Summary of Changes

Remove SA-N-5 Mount and replace with Igla-1 Mount (SA-N-10)- Same mount on ship 2963

### Sources

Sipri Line

Viet Nam	Russia	1996	?	400	?	Igla-1	portable SAM	400	?	1999; 2000; 2001; 2002; 2003; 2004; 2005; 2006; 2007; 2008; 2009; 2010; 2011; 2012; 2013; 2014	New	SA-N-10 version for BPS-500 (Ho-A) and Project-10412 (Svetlyak) patrol craft and probably Project-1241 (Tarantul) FAC	0.07	28	28

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
