### ISSUE TITLE
Add Vietnamese SAM Bn (SA-6a Gainful [2K12E Kvadrat]) 10x 1980

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4636]
### DB Selector

DB3K

### DBID to Copy

Facility 1334

### Hypothetical

No

### Name

SAM Bn (SA-6a Gainful [2K12E Kvadrat])

### Country

Vietnam

### Service

Army

### In Commission

1980

### Number in Service

10x

### Sources

https://en.topwar.ru/144266-sistema-pvo-vetnama-chast-3.html
https://en.wikipedia.org/wiki/2K12_Kub
Sipri Line
Viet Nam	Soviet Union	1979	?	10	?	Kvadrat	SAM system	10	?	1979; 1980	New

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
