### ISSUE TITLE
Add Vietnamese SAM Plt (SA-13 Gopher [9k35 Strela-10]) 1986

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4637]
### DB Selector

DB3K

### DBID to Copy

Facility 2654

### Hypothetical

No

### Name

SAM Plt (SA-13 Gopher [9k35 Strela-10])

### Country

Vietnam

### Service

Army

### In Commission

1986-present

### Number in Service

20x

### Sources

https://twitter.com/AnnQuann/status/1238117334448930816
https://www.armyrecognition.com/news/army-news/2023/vietnamese-army-keeps-sa-13-gopher-strela-10-air-defense-missile-in-service

Sipri Line
Viet Nam	Soviet Union	1985	?	20	?	Strela-10	mobile SAM system	20	?	1985; 1986	New		1.25	25	25

**Comment by bostonmyk** [comment]
https://twitter.com/AnnQuann/status/1600805034437926912/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
