### ISSUE TITLE
Add Vietnamese Radar (Spoonrest D [P-18])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4638]
### DB Selector

DB3K

### DBID to Copy

Facility 2656

### Hypothetical

Yes

### Name

Radar (Spoonrest D [P-18])

### Country

Vietnam

### Service

Air Force

### Sources

http://defense-studies.blogspot.com/2014/03/vietnam-upgraded-p-18-radar.html
http://defense-studies.blogspot.com/2018/05/vietnam-digitized-old-generation-radar.html
https://en.topwar.ru/144266-sistema-pvo-vetnama-chast-3.html
https://en.wikipedia.org/wiki/P-18_radar#cite_note-21
https://alert5.com/2018/05/30/vietnam-said-to-have-modernized-its-p-18-radar-system/

**Comment by bostonmyk** [comment]
https://www.flickr.com/photos/38381308@N04/19244619049

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
