### ISSUE TITLE
SAM Bn (SA-6b Gainful [2K12 Kub]) (5x Bn + Long Track + Thin Skin B HF + Spoon Rest D + Flat Face B)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#464]
### DB Selector

DB3K

### DBID to Copy

facility/133/DB3K

### Hypothetical

No

### Name

SAM Bn (SA-6b Gainful [2K12 Kub]) (5x Bn + Long Track + Thin Skin B HF + Spoon Rest D + Flat Face B)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Known Changes

### Mounts

No Known Changes

### Loadout Options

No Known Changes

### Other Changes

No Known Changes

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
