### ISSUE TITLE
Add AN/AAR-57A(V) Common Missile Warning System to Qatar F-15QA 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4640]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4770

### Summary of Changes

Add sensor 6541 (AN/AAR-57A(V) Common Missile Warning System)

### Sources

General
https://theaviationist.com/2024/04/03/f-15s-eagle-pawss-iote/
Qatar:
https://twitter.com/airsuperiorx/status/1800696898778800398
https://theaviationist.com/2021/10/29/qeaf-f-15qa-delivery/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
