### ISSUE TITLE
Add AN/AAR-57 CMWS to Qatar AH-64E

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4641]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4434

### Summary of Changes

Add sensor 2484 AN/AAR-57

### Sources

https://www.federalregister.gov/documents/2019/06/17/2019-12665/arms-sales-notification
https://www.dsca.mil/press-media/major-arms-sales/qatar-ah-64e-apache-helicopters-spare-parts-and-related-equipment

https://airfighters.com/photo/276736/M/Qatar-Emiri-Air-Force/Boeing-AH-64E-Apache-Guardian/QA124/

**Comment by PygmalionOfCyprus** [comment]
Sensor is already present as of current DB. Handled 506 or earlier.
