### ISSUE TITLE
Add Vietnamese HQ-511 [Polnocny B]

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4643]
### DB Selector

DB3K

### DBID to Copy

Ship 2188

### Hypothetical

Yes

### Name

HQ-511 HQ-511 [Polnocny B]

### Country

Vietnam

### Service

Navy

### In Commission

1979

### Number in Service

3x

### Sources

https://warsearcher.com/shipsearcher/vietnamese-navy-current-and-retired/vietnamese-navy-landing-ships/
https://twitter.com/AnnQuann/status/1215503533044191233
https://x.com/AnnQuann/status/1685154661056274432
https://www.facebook.com/VietDefenseVN/photos/a.1256417387849774/1361222867369225/?type=3
https://en.wikipedia.org/wiki/Polnocny-class_landing_ship

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
