### ISSUE TITLE
Add Vietnamese HQ-526 [Damen Stan Lander 5612]x4

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4644]
### DB Selector

DB3K

### DBID to Copy

Ship 2411

### Hypothetical

No

### Name

HQ-526 [Damen Stan Lander 5612]

### Country

Vietnam

### Service

Navy

### In Commission

2021

### Number in Service

4x

### Sources

https://www.janes.com/osint-insights/defence-news/vietnam-launches-third-damen-designed-landing-ship-for-navy
https://www.asiapacificdefensejournal.com/2021/03/vietnam-launches-fourth-locally-built.html
https://en.wikipedia.org/wiki/Damen_Stan_Lander_5612

**Comment by bostonmyk** [comment]
Sipri Lines
Viet Nam	Netherlands	2019		1		Stan Lander-5612	landing ship	1		2021	New	Produced under licence in Viet Nam	14	14	14
Viet Nam	Netherlands	2018	?	3		Stan Lander-5612	landing ship	3		2021	New	Originally produced for Venezuela but delivery cancelled and taken over by Viet Nam; produced under licence in Viet Nam	14	42	42

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
