### ISSUE TITLE
Add BP28-01-01 [Damen Stan Patrol 4207]Vietnamese Border Guard x4

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4645]
### DB Selector

DB3K

### DBID to Copy

Ship 3578

### Hypothetical

Yes

### Name

 BP28-01-01 [Damen Stan Patrol 4207]

### Country

Vietnam

### Service

Border Guard

### In Commission

2019

### Number in Service

4x

### Mounts

2 12.7mm NSV Machine guns

### Sources

https://songthu.com.vn/en/san-pham/tau-tuan-tra-spa-4207/
https://twitter.com/AnnQuann/status/1667398013042692097
https://twitter.com/AnnQuann/status/1667398013042692097
https://en.topwar.ru/134297-vo-vetname-spuscheny-na-vodu-dva-bolshih-storozhevyh-katera.html
https://weaponews.com/news/22117-in-vietnam-launched-two-large-patrol-boats.html

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
