### ISSUE TITLE
Add Vietnamese KA-25BSh Hormone A 1980-1990

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4646]
### DB Selector

DB3K

### DBID to Copy

Aircraft 1808

### Hypothetical

Yes

### Name

KA-25Bsh Hormone A

### Country

Vietnam

### Service

Airforce

### In Commission

1980-1990

### Number in Service

10x

### Sources

https://www.flickr.com/photos/38381308@N04/18602302249/in/photostream/
https://commons.wikimedia.org/wiki/File:Kamov_KA-25Bsh.jpg
Sipri
Viet Nam	Soviet Union	1979		15	?	Ka-25BSh	ASW helicopter	15	?	1979; 1980; 1981	New		10	150	150
Viet Nam	Soviet Union	1984	?	2		Ka-25BSh	ASW helicopter	2	?	1984	New		10	20	20

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
