### ISSUE TITLE
Add Vietnamese C-295M

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4647]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5735

### Hypothetical

Yes

### Name

C-295M

### Country

Vietnam

### Service

Air Force

### In Commission

2016

### Number in Service

3x

### Loadout Options

Add paratrooper loadout

### Sources

https://twitter.com/AnnQuann/status/1801483863849636362
https://www.planespotters.net/airframe/casa-c-295-8902-vietnam-peoples-air-force/e0ggdm
https://www.facebook.com/photo.php?fbid=1585561398268703&id=1256019601222886&set=a.1256417387849774
Sipri
Viet Nam	Spain	2014		3		C-295	transport aircraft	3		2014; 2015	New		12.5	37.5	37.5

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
