### ISSUE TITLE
PLAAF J-10S/J-10SH

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4648]
### DB Selector

DB3K

### Baseline

715

### Hypothetical

No

### Name

J-10S Firebird/J-10SH Firebird

### Country

China

### Service

PLAAF

### In Commission

2008-

### Length (m)

15.5

### Wingspan (m)

9.7

### Height (m)

4.8

### Empty Weight (kg)

9750

### Maximum Takeoff Weight (MTOW) (kg)

19277

### Payload Weight (kg)

4500

### Crew

2

### Propulsion

1×AL-31F

### Rate of Climb (ft/min)

24970(average);74910(instantaneous)

### Service Ceiling (ft)

45000

### Military/Afterburner Speed (kt)

920

### Cruise Speed (kt)

480

### Supercruise

Yes

### Ferry Range (nm)

2000

### Fuel Capacity (kg)

3200

### Sensors

same as J-10A

### Mounts

same as J-10A

### Loadout Options

same as J-10A

### Comms/Datalinks

same as J-10A

### Sources

https://en.m.wikipedia.org/wiki/Chengdu J-10
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/7ac068ee-9a98-4a6a-891a-2138820856d9)

**Comment by PygmalionOfCyprus** [comment]
Was added 506.
