### ISSUE TITLE
HAS with WS3 vault

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4649]
Hardened Aircraft Shelters with Weapons Storage and Security System (WS3)

215x WS3 vaults were built for the USAF at 13x sites in seven countries. Typically hold 4x B61-12. 
34x WS3 vaults were built for the RAF to store the WE.177; 10x at RAF Brüggen and 24x at RAF Marham.

https://en.wikipedia.org/wiki/Weapons_Storage_and_Security_System

**Comment by PygmalionOfCyprus** [comment]
The presence of WS3 does not materially change the performance of the hangar facilities in Command. If someone really wants this capability they can just add the magazines in the mission editor.
