### ISSUE TITLE
Reveyted railway spur

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4652]
Revetted railway spur for 8 - 12 railway box cars

Please see
Military Ocean Terminal Sunny Point & [Military Ocean Terminal Concord
https://en.wikipedia.org/wiki/Military_Ocean_Terminal

https://www.google.com/maps/place/34%C2%B000'25.7%22N+77%C2%B058'33.5%22W/@34.007135,-77.975979,29969m/data=!3m1!1e3!4m4!3m3!8m2!3d34.007135!4d-77.975979?hl=en&entry=ttu

**Comment by PygmalionOfCyprus** [comment]
Because we don't properly model rail lines, railway storage, etc. there's no reason to add these.
