### ISSUE TITLE
Add out of service date of 2024 to Brazilian C-130s and KC-130

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4653]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2951, 2950, 2949

### Summary of Changes

Add out of service date of 2024 to Aircraft 2941, 2950, 2949

### Sources

https://x.com/SA_Defensa/status/1802644463119941657
https://www.riotimesonline.com/brazilian-air-force-bids-farewell-to-the-legendary-c-130-hercules/
https://alert5.com/2024/03/07/fab-bids-farewell-to-the-c-130/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
