### ISSUE TITLE
China,PLAGF,PHZ-11 Extended range ammunition（WS-22）

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4654]
### DB Selector

DB3K

### Baseline

weapon 2752

### Hypothetical

No

### Name

WS-22 122mm extended range Rocket

### Length (m)

2.75

### Width/Span (m)

0.12

### Diameter (m)

0.12

### Weight (kg)

75

### Range (nm)

3-27

### Warhead

same as Type 81/89 122mm Rocket

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

10

### Sensors

none

### Comments

According to the propaganda, we can confirm that the PLA's Type 89 MLRS system is equipped with new rockets at a range of 50 km.

### Sources

https://en.wikipedia.org/wiki/PHL-11

**Comment by yU2187sie** [comment]
http://www.cndefense.com/tgaws/WS-22.html
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/d7885c9b-ad7f-45f3-b1de-6f6e369cf90f)
A similar version of the munition has already been launched for foreign trade, and according to panel data, the PLAGF self-use version should have a longer range. @PygmalionOfCyprus

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
