### ISSUE TITLE
Add out of service date of 2017 for Malaysian Mig-29s

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4655]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 647

### Summary of Changes

Add out-of-service date of 2017

### Sources

https://www.defensenews.com/global/asia-pacific/2024/02/21/malaysia-is-becoming-wary-of-its-russian-made-weapons/
https://en.wikipedia.org/wiki/List_of_aircraft_of_the_Malaysian_Armed_Forces
http://www.mig.mariwoj.pl/mig-29-my.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
