### ISSUE TITLE
Remove JATM from Indonesian F-15E/X Mk.82 Loadouts

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4656]
### DB Selector

DB3K

### Affected DBID(s)

Loadout 27656, 27657

### Summary of Changes

Probably copy-over-typo. Replace with Aim-120D. Check to be sure its not the same as the US loadout.

### Sources

Eyes via optic nerve

**Comment by PygmalionOfCyprus** [comment]
I just removed the JATM loadouts from the Indonesian F-15EXs because they already have identical Mk82/84 loadouts w/ the AIM-120Ds.
