### ISSUE TITLE
China,PLAGF,PHZ- 11 MLRS

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4657]
### DB Selector

DB3K

### Hypothetical

No

### Name

PHZ- 11 MLRS x 6

### Facility Type

Arty

### Country

China

### Service

PLAGF

### In Commission

2011

### Number in Service

150+

### Crew

3

### Dispersion Radius (m)

80

### Sensors

1x Mk1 Eyeball

### Mounts

6x PHZ-11 MLRS

### Magazines

40x Type 81/89 122mm Rocket
40x WS-22 122mm extended range Rocket
(+40 On mount magazine)

### Aircraft & Docking Facilities

none

### Comments

According to the publicity, the PLAGF is equipped with the new 122mm MLRS system. It can carry new long-range munitions.

### Sources

https://armyrecognition.com/news/army-news/2020/new-chinese-army-phz-11-122mm-mlrs-multiple-launch-rocket-system-on-tracked-chassis
https://en.wikipedia.org/wiki/PHL-11
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/db68fc99-96ec-4daf-9d95-a33e0ddebd06)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/5f811249-94fe-4f13-ba0f-1d5797559937)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
