### ISSUE TITLE
Add HMS/HMD for F-23(2024), F-24(2024)

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#4658]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft ID #5852, 5835

### Summary of Changes

Aircraft ID 4875 F-22 Raptor have been equipped with HMD (maybe next-gen helmet?), therefore other NATF fighter(F-23, F-24) add properties with HMS/HMD.

### Sources

https://www.af.mil/News/Article-Display/Article/3358043/f-22a-raptor-pilots-test-next-gen-helmet/
https://theaviationist.com/2023/04/13/next-gen-helmet-tested-by-f-22-raptor-pilots/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
