### ISSUE TITLE
Add Indonesian F-5E and F-5F retirement date of 2005

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4659]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1191, 3589

### Summary of Changes

Add out of service date of 2005

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indonesian_Air_Force
https://www.upi.com/Defense-News/2017/01/23/Indonesian-air-force-considering-F-5-replacement-plans/8621485178215/
https://www.joebaugher.com/usaf_fighters/f5_36.html

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
