### ISSUE TITLE
SAM Sec (SA-16 Gimlet [9K310 Igla-1] MANPADS x 3)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#466]
### DB Selector

DB3K

### DBID to Copy

facility/273/DB3K

### Hypothetical

No

### Name

SAM Sec (SA-16 Gimlet [9K310 Igla-1] MANPADS x 3)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/9K38_Igla#Operators

**Comment by PygmalionOfCyprus** [comment]
Added 494.
