### ISSUE TITLE
Add out of service date of 2007 for Indonesian OV-10F Broncos

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4660]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5016

### Summary of Changes

Add out of service date of 2007.

### Sources

https://en.wikipedia.org/wiki/North_American_Rockwell_OV-10_Bronco
https://en.wikipedia.org/wiki/3rd_Air_Squadron_(Indonesia)#:~:text=In%201990%2C%20the%20Bronco%20was,by%20EMB%2D314%20Super%20Tucano.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
