### ISSUE TITLE
Set Indonesian Mirage 2k as hypothetical or disable

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4661]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 6776, 6777

### Summary of Changes

Set as hypothetical or disable 

### Sources

No budget. Likely going somewhere eventually so can probably save the entries but disable them.
https://aviationweek.com/shownews/singapore-airshow/indonesia-terminates-contract-ex-qatar-mirage-2000s
https://www.reuters.com/business/aerospace-defense/indonesia-scraps-plan-buy-mirage-fighter-jets-qatar-2024-02-11/
https://www.janes.com/osint-insights/defence-news/indonesia-backtracks-on-mirage-2000-5-acquisition

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
