### ISSUE TITLE
Remove R-27R TSARH AAM Loadouts from Mig-29UBs

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4662]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 6851, 6952, 7038,

### Summary of Changes

Three Mig-29UB Fulcrum B entries have loadouts for R-27R missiles despite being the radarless trainer versions. Other Mig-29UBs do not have these loadouts. Just IR AAMs.

### Sources

https://www.cmano-db.com/aircraft/6952/
https://www.cmano-db.com/aircraft/7028/
https://www.cmano-db.com/aircraft/6851/

**Comment by KLABDB3K** [comment]
Also puzzled how they use Azerbaijan LGB given the limitations of the OLS for air to ground designation or is this a CMO DB viewer anomaly. ?

**Comment by tbrandon517** [comment]
> Also puzzled how they use Azerbaijan LGB given the limitations of the OLS for air to ground designation or is this a CMO DB viewer anomaly. ?

Will have to look when I am home. Not sure if the LGB loadouts have the "require buddy lazing" notice.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

The Azeri LGB loadouts require buddy lazing.

**Comment by tbrandon517** [comment]
> Handled 507.
> 
> The Azeri LGB loadouts require buddy lazing.

I thought so but wasn't 100% sure without directly checking in CMO.
