### ISSUE TITLE
Add Peruvian SH-3H Sea King

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4663]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5889

### Hypothetical

No

### Name

SH-3H Sea King

### Country

Peru

### Service

Navy

### In Commission

2023

### Number in Service

6x

### Loadout Options

Initial loadouts great. No evidence it will have a ASW role at all. Based on Makassars.

### Sources

https://www.key.aero/article/peruvian-navy-presses-new-sea-kings-service
https://x.com/WarshipCam/status/1802797856337834079/photo/4
https://x.com/SA_Defensa/status/1729923728492892408
https://www.outono.net/elentir/2023/08/11/the-last-sh-3-sea-kings-of-the-spanish-navy-leave-on-a-ship-for-peru/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
