### ISSUE TITLE
No R-73 A2A loadout for Yemeni Mig-29UB

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4664]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 6333

### Summary of Changes

Yemeni Mig-29UB does not have R-73 air-to-air loadout.

Not sure if this was an oversight or intentional based on Yemeni usage (I didn't find anything to this affect but I could have missed or not had availability).

### Sources

DB 505

https://cmano-db.com/aircraft/6333/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
