### ISSUE TITLE
Facility VL-MICA (France AF) x 2 2024.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4665]
### DB Selector

DB3K

### DBID to Copy

Facility Thai VL-MICA 2020

### Hypothetical

No

### Name

VL-MICA (France AF) x 2 - 2024

### Country

France

### Service

Air Force

### In Commission

2024

### Number in Service

2 - More to follow. Replace Crotale NG donated to Ukraine 

### Sensors

To be confirmed but as existing entry? 

### Mounts

As existing entry but TBC.

### Loadout Options

N/A

### Other Changes

Awaits confirmation of units, fire control etc. 

### Sources

https://www.forcesoperations.com/eurosatory-2024-les-premiers-vl-mica-livres-aux-armees-francaises/

**Comment by KLABDB3K** [comment]
Article also states procured by Omani and Moroccan armed forces.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
