### ISSUE TITLE
South Korean P-8 Update

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4666]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5585

### Summary of Changes

Update in-service date to 2025
Quantity is 6 (3 currently delivered)

### Sources

https://www.navalnews.com/naval-news/2024/06/rok-navys-new-p-8a-poseidon-maritime-patrol-aircraft-arrive-in-south-korea/
https://x.com/hornetysfs/status/1803374010748764352
https://www.flightglobal.com/defence/south-korean-navy-moves-closer-to-deploying-p-8a/158813.article

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
