### ISSUE TITLE
Add 4 Hellfire/4 SDB loadouts to AC-130J Ghostrider

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4667]
### DB Selector

DB3K

### User(s)

Aircraft 5697

### Weapons Carried

-4 Hellfire
-4 GBU-39 SDB or 4 GBU-53

https://www.afsoc.af.mil/About-Us/Fact-Sheets/Display/Article/2547234/ac-130j-ghostrider/

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://www.youtube.com/watch?v=Hph57yI0VAU&t=224s
https://www.afsoc.af.mil/About-Us/Fact-Sheets/Display/Article/2547234/ac-130j-ghostrider/
https://tacairnet.com/2016/12/21/ac-130j-ghostrider-tests-guided-bombs/

**Comment by bostonmyk** [comment]
Related to https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2462

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
