### ISSUE TITLE
Add an out of service date of 2024 for B 52 Hercules [Type 42]

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4668]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1423

### Summary of Changes

Add out of service date of 2024

### Sources

https://x.com/SA_Defensa/status/1803536818199040132
https://www.zona-militar.com/en/2024/03/22/after-years-without-sailing-the-argentine-navy-confirms-the-definitive-decommissioning-of-the-multipurpose-fast-transport-ara-hercules/#google_vignette

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
