### ISSUE TITLE
Loadout - Search and Rescue and Maritime surveillance ref #4013 - KC-390 Millennium (Brazil - 2018) Litening pod fitted -

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4669]
### DB Selector

DB3K

### User(s)

Brazil

### Weapons Carried

Nil.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

3000 nm 

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

C-390 is designed to be a fairly effective SAR and maritime surveillance platform with a hard point for the Litening III pod and the effective surface search function of its radar. 
Weapon item #1292 - Litening III Pod [FLIR + LRMTS, 40k ft]
Also has standard MAWS LWR fitted and the RWR currently fitted is likely to be of a newer generation than the 1970's technology item sensor #2919. Will attempt to identify which is fitted but likely to be Brazilian derived? Sensor #1315 - BOW-21?

### Sources

pp.46 Brazilian Flair - Alan Warnes. Air Forces Monthly July 2024. image of Millenium with Litening pod.
Article references SAR role and modular fire fighting function using a MAFFS system that can be installed in 2hrs 30 minutes.  
Gabbiano Selex T-20 radar is stated to provide "highly accurate intelligence surveillance and reconnaissance for search and rescue and patrol missions over sea land or around coastal areas". pp.54.

**Comment by PygmalionOfCyprus** [comment]
(Mostly) handled 507. Leaving the generic RWR for now; the era shouldn't matter much for evasive action, although it's true it might be work creating multiple eras of the generics.
