### ISSUE TITLE
Aircraft #5860 - C-390 Millennium (Netherlands - 2026) apparently designated MC-390 ?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4670]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #5860 - C-390 Millennium (Netherlands - 2026)

### Summary of Changes

Apparently designated MC-390 by RNLAF. 
Change to Aircraft #5860 - MC-390 Millennium (Netherlands - 2026) C-390.

### Sources

From pp.46 Brazilian Flair - Alan Warnes. Air Forces Monthly July 2024. pp.55
https://www.key.aero/article/how-rnlafs-c-130-unit-transitioning-mc-390

**Comment by PygmalionOfCyprus** [comment]
I'm not seeing this designation used anywhere else. It might just be a Key.Aero mistake.
