### ISSUE TITLE
Add Indian Navy Dhruv Mk.3 2021 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4673]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5206

### Hypothetical

No

### Name

Dhruv Mk3

### Country

India

### Service

Navy

### In Commission

2021

### Sensors

EL/M-2022
See this post
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4677

### Mounts

Same

### Loadout Options

Visibly the same as coast guard variant (5206)
Add SAR load-outs

### Other Changes

Visibly the same role as coast guard variant. 
Shore based

### Sources

https://www.strategicfront.org/forums/threads/the-indian-navys-mh-60r-naval-dhruv-uhm-helicopters.39/page-19
https://www.strategicfront.org/forums/threads/the-indian-navys-mh-60r-naval-dhruv-uhm-helicopters.39/page-20

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
