### ISSUE TITLE
Myanmar Kyan Sittha BEL Revathi Radar Update 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4675]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3109

### Summary of Changes

Replace LW.08 Radar with BEL Revathi Radar (sensor 5533) IOC 2024

### Sources

https://x.com/ThingsNavy/status/1759258734248046997
https://x.com/aag_th/status/1773032236377649551/photo/4

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
