### ISSUE TITLE
Add Philippine Airforce C-130T

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4676]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2883

### Hypothetical

No

### Name

C-130T

### Country

Philippines

### Service

Air Force

### In Commission

2023

### Sensors

SABIR ISR suite

### Loadout Options

Ferry
ISR

### Other Changes

SABIR Pod
L-3 Wescam MX-15 HDi multispectral imaging turret
ELM-2022ML X-Band multimode airborne maritime surveillance radar

### Sources

https://www.facebook.com/MaxDefense/photos/a.119059604931372/789674151203244/?type=3
https://www.facebook.com/rtvmalacanang/videos/inspection-of-the-c-130t-aircraft-clark-air-base-pampanga-march-31-2023/752557899557882/?locale=hi_IN&_rdr
https://globalnation.inquirer.net/169028/news-air-force-c-130-sabir-maritime-patrol-surveillance-galileo-kintanar-jr-delfin-lorenzana-sung-kim
https://www.key.aero/article/philippine-sabir-system
https://www.israeldefense.co.il/en/node/35930

ELM-2022 stats
https://www.iai.co.il/p/elm-2022
https://www.radartutorial.eu/19.kartei/08.airborne/karte037.en.html

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
