### ISSUE TITLE
Add EL/M-2022 Indian Coast Guard and Navy Dhruv Mk3 Radars

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4677]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5206

### Summary of Changes

Swap out nav radar for Elta ELM-2022

### Sources

https://x.com/Rethik_D/status/1736636287283777775/photo/1
https://www.iai.co.il/p/elm-2022
https://www.aerocontact.com/en/virtual-aviation-exhibition/catalog/138-surveillance-radar-elm-2022-a-h-u-brochure#lg=1&slide=1
https://cartenav.com/systems/elta-elm-2022-radar/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
