### ISSUE TITLE
Facility SAM Plt HQ-17E (Serbia) 2024

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4678]
### DB Selector

DB3K

### DBID to Copy

Facility #2515 SAM Plt (HQ-17 [SA-15 Copy]) (2x Plt + Dog Ear pr Bn, 4x Bn pr Regt) Copy any late model Facility SAM PLAAF HQ-17 Bty

### Hypothetical

No

### Name

Facility SAM HQ-17 (Serbia) 2024

### Country

Serbia

### Service

Air Force? 

### In Commission

2024

### Number in Service

Not known

### Sensors

As existing entry. 

### Mounts

As existing battery. Fire control battery area search radar and firing units. 

### Loadout Options

N/A

### Other Changes

Appears to have reloader vehicle. 

### Sources

https://x.com/PeterVoinovich/status/1806336660730245167?t=Y5zF6gQcMUtgPtpfv9N6Xw&s=19
Photo image shows Serbian army/Airforce uniform personnel sat next to it.

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
