### ISSUE TITLE
A US Navy ship checkup 2024

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4679]
### DB Selector

DB3K

### Affected DBID(s)

All US NAVY ships

### Summary of Changes

Posted on https://www.matrixgames.com/forums/viewtopic.php?p=5175301#p5175301 by Nikel gives a updated overview of all the ships in the US Navy anno 2024.
Maybe useful for a checkup of the DB?

### Sources

https://prd-sc102-cdn.rtx.com/-/media/rtx/news-images/2024/03/28/4538063_rtx_2024shipsubposter_digital_v8.pdf

**Comment by KLABDB3K** [comment]
https://www.navalnews.com/naval-news/2024/06/uss-fitzgerald-and-hmas-sydney-show-up-with-nsm-at-rimpac-2024/
Arleigh Burkes with NSM. (I can't access the in game DB3K to check if this has already been updated or requested?)

**Comment by tbrandon517** [comment]
More on NSM Burkes

https://www.twz.com/sea/navy-destroyer-modified-with-naval-strike-missiles-sailing-in-rimpac-wargames?fbclid=IwZXh0bgNhZW0CMTEAAR1wLDVuhEKrynZC0lgpEmB-HUlzliVx0VKrsIkJwQNJhQS5HKIeeB1vllY_aem_0F6dQCAV9xWoPMsjliFx7A

**Comment by PygmalionOfCyprus** [comment]
Thanks for the resource! I'm gonna close this ticket since it's not really "actionable," this would basically be a source in a USA national review.
