### ISSUE TITLE
SAM Bn/2 (SA-8b Gecko Mod-1 [9K33M3 Osa-AKM]) (2x Plt pr Bn, 5x Bn + Long Track + Thin Skin B HF + Flat Face B pr Regt)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#468]
### DB Selector

DB3K

### DBID to Copy

facility/1646/DB3K

### Hypothetical

No

### Name

SAM Bn/2 (SA-8b Gecko Mod-1 [9K33M3 Osa-AKM]) (2x Plt pr Bn, 5x Bn + Long Track + Thin Skin B HF + Flat Face B pr Regt)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

None Known

### Mounts

None Known

### Loadout Options

None Known

### Other Changes

None Known

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.thedrive.com/the-war-zone/36777/everything-we-know-about-the-fighting-that-has-erupted-between-armenia-and-azerbaijan
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
