### ISSUE TITLE
Add Singapore AAA Sec (35mm GDF-02 Twin Oerlikon x2, Super Fledermaus FCR) 1980-2014

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4680]
### DB Selector

DB3K

### DBID to Copy

Facility 3840

### Hypothetical

No

### Name

AAA Sec (35mm GDF-02 Twin Oerlikon x2, Super Fledermaus FCR)

### Country

Singapore

### Service

Airforce

### In Commission

1980-2017

### Number in Service

17x

### Sources

https://m.facebook.com/TheRSAF/photos/35mm-oerlikon-anti-aircraft-guns-the-iconic-ground-based-air-defence-system-oper/1799308993510950/
https://en.wikipedia.org/wiki/Oerlikon_GDF
https://www.pinterest.com/pin/863213453554848951/
https://www.moddb.com/groups/anti-air-lovers/images/oerlikon-35mm-gbad

Sipri
Singapore	Switzerland	1978	?	17	?	Super-Fledermaus	fire control radar	17	?	1979; 1980	New	For use with GDF-002 35mm anti-aircraft guns

**Comment by bostonmyk** [comment]
Phased out 2014

https://coffeenbullets.wordpress.com/2020/06/01/gunners-50/

**Comment by bostonmyk** [comment]
https://coffeenbullets.wordpress.com/2014/08/21/rsafs-35mm-guns-retired-to-museum/comment-page-1/#comment-850

**Comment by PygmalionOfCyprus** [comment]
Handled 507.

**Comment by FrangibleCover** [comment]
@PygmalionOfCyprus sorry, missed this, but as guns associated with Super Fledermaus these are GDF-001s. The coffeenbullets links confirm this.

**Comment by PygmalionOfCyprus** [comment]
Yep, I caught that as well and it's correct in the DB entry.
