### ISSUE TITLE
Add Singapore Heron UAV 2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4681]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3448

### Hypothetical

No

### Name

Heron UAV

### Country

Singapore

### Service

Air Force

### In Commission

2013

### Number in Service

10x

### Sensors

No radar
Add generic Flir 2010 generation

### Sources

https://www.mindef.gov.sg/web/portal/mindef/news-and-events/latest-releases/article-detail/2011/march/2011mar02-news-releases-00039/!ut/p/z1/vVLLUuMwEPyWPfioaPyKbW7mUcAWJiwEiHWhZHv8YG0p2CImf88kgQNVBIoLOmlGPa3ulrjgCy6UXDWVNI1WsqU6FdOHYHZ8dAaecznz5zbEd_P5hX94eX4bTPkdF1ws86bgqWv7RSl9ZKVtR8xzph7LfBkyLMIMMPCmUYYbdK7M0tQ87RpVYMlyrQwqY0GtO7RA4TgwqQqGK-oOFrTS4GBYjy3KAanhgG1b0Mk-r3cFbcFh28F3FAMAN-L338kXdAx7Vgw0L7aQ2T_v1PbAuZgl1z4xRFE4hysHToM3wBccKWkI9msI-P2qwZHfKt13lPjNDwM9A_53K-ELl_SKzePTk4gp_E3aL4YvfiF9utbpk6OkIkPS1KxRpeaLzQxdvyHYFfsJyFjV6mz3D2OVuSFR9Vhij_3kuad2bcxyOLDAgnEcJ5XWVYuTXHcWfDZS64Gcf0TyZdeF7pr9L5MT1xPZeiwT46fxn1cru97M/dz/d5/L2dBISEvZ0FBIS9nQSEh/?urile=wcm%3Apath%3A%2Fmindef-content%2Fhome%2Fnews-and-events%2Flatest-releases%2F2011%2Fmarch%2F2011Mar02-News-Releases-00039

https://www.janes.com/osint-insights/defence-news/air/singapore-airshow-2024-singapore-to-replace-fleet-of-heron-1-hermes-450-uavs

https://www.flightglobal.com/singapore-inaugurates-heron-1-uav/105476.article

Singapore	Israel	2010	?	10	?	Heron	UAV	10	?	2012; 2013	New

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
