### ISSUE TITLE
Add Singapore SAM Sec (RBS-70 Bolide MANPADS x3) 2011

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4682]
### DB Selector

DB3K

### DBID to Copy

Facility 292

### Hypothetical

No

### Name

SAM Plt (RBS-70 Bolide MANPADS x3)

### Country

Singapore

### Service

Air Force

### In Commission

2011

### Sources

https://www.mindef.gov.sg/web/portal/mindef/news-and-events/latest-releases/article-detail/2020/December/17dec20_fs

Sipri Line
Singapore	Sweden	2009	?	50	?	RBS-70 Mk-3 Bolide	portable SAM	50	?	2011	New		0.1	5	5

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
