### ISSUE TITLE
 Add Singapore SAM Sec (RBS-70 NG MANPADS x3) 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4683]
### DB Selector

DB3K

### DBID to Copy

Facilty 3912

### Hypothetical

No

### Name

SAM Plt (RBS 70 NG MANPADS x 3)

### Country

Singapore

### Service

Air Force

### In Commission

2021

### Sources

https://alert5.com/2021/12/16/rbs-70-ng-in-service-with-rsaf/

Sipri Lines
Singapore	Sweden	2018	?	50	?	RBS-70 Mk-3 Bolide	portable SAM	50	?	2019	New	RBS-70NG version	0.1	5	5

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
