### ISSUE TITLE
Add Singapore Searcher II UAV

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4685]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2575

### Hypothetical

No

### Name

Searcher II

### Country

Singapore

### Service

Airforce

### In Commission

1995-2011

### Other Changes

Replaced by Heron

### Sources

https://drones.cnas.org/reports/a-perspective-on-singapore/
Sipri Line
Singapore	Israel	1993	?	40	?	Searcher	UAV	40	?	1994; 1995	New	Searcher-2 version	0.3	12	12

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
