### ISSUE TITLE
Add Israel and Singapore Orbiter 4 UAV 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4686]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6941

### Hypothetical

No

### Name

Orbiter 4

### Country

Singapore

### Service

Airforce

### In Commission

Israel 2023, Singapore 2024

### Sensors

2020 generation FLIR
laser designator

### Other Changes

Similar to orbiter 3, Longer endurance (24 hours and 150km range)

IDF version is called Nitzoz

### Sources

https://www.mindef.gov.sg/web/portal/mindef/news-and-events/latest-releases/article-detail/2022/March/02mar22_fs3
https://www.mindef.gov.sg/web/portal/pioneer/article/cover-article-detail/ops-and-training/2022-Q1/02mar22_news1
https://aeronautics-sys.com/systems/orbiter-4/
https://defense-update.com/20200210_waps.html

IDF service:
https://en.wikipedia.org/wiki/Aeronautics_Defense_Orbiter
https://x.com/AmitLidor/status/1806662176222114005
Sipri Line
Singapore	Israel	2022	?			Orbiter-3	UAV	5	?	2023	New	Orbiter-4 version	0.05	0	0.25

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
