### ISSUE TITLE
Update Singapore Rapier Blindfire In service and out of service date 1983-1999

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4687]
### DB Selector

DB3K

### Affected DBID(s)

Facility 1214

### Summary of Changes

In service date was 1983 and out of service date was 1999 when updated to Rapier-2 (2000)

### Sources

https://en.wikipedia.org/wiki/Rapier_(missile)
https://www.dso.org.sg/Media/Default/Publications/DTC%2050%20-%20Systems%20of%20Systems.pdf  pg.9

https://www.facebook.com/mindefsg/photos/a.380387876058/10156888218826059/?type=3
https://www.facebook.com/media/set/?set=a.486631718112024.1073741955.236424069799458&type=3&_rdr
Sipri
Singapore	United Kingdom	1981		12		Rapier	SAM system	12	?	1982; 1983	New	Part of $60 m deal	7	84	84
Singapore	United Kingdom	1981		250	?	Rapier-1	SAM	250	?	1982; 1983	New		0.1	25	25

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
