### ISSUE TITLE
Update Singapore Rapier B1X in service (2000) and out of service date (2010)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4689]
### DB Selector

DB3K

### Affected DBID(s)

Facility 1225

### Summary of Changes

In service date was 2000. Out of service date was 2010. Replaced by Spyder

### Sources

https://en.wikipedia.org/wiki/Rapier_(missile)
https://www.facebook.com/mindefsg/photos/a.380387876058/10156888218826059/?type=3

Singapore	United Kingdom	1994	?	250		Rapier-2	SAM	250	?	1998; 1999	New	Possibly (incl) Singaporean Rapier-1 missiles rebuilt to Rapier-2	0.14	35	35
Singapore	United Kingdom	1994	?	12	?	Rapier-2000	SAM system	12	?	1998; 1999	New	Singaporean Rapier SAM systems rebuilt to Rapier-2000	9	108	108

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
