### ISSUE TITLE
SAM Sec (SA-24 Grouse [9K338 Igla-S] MANPADS x 3)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#469]
### DB Selector

DB3K

### DBID to Copy

facility/1560/DB3K

### Hypothetical

No

### Name

SAM Sec (SA-24 Grouse [9K338 Igla-S] MANPADS x 3)

### Country

Armenia

### Service

Army

### In Commission

IOC uncertain, After 2005

### Sensors

None Known

### Mounts

None Known

### Loadout Options

None Known

### Other Changes

None Known

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
