### ISSUE TITLE
China, H-6K YJ-21 Heavy loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4693]
### DB Selector

DB3K

### User(s)

H-6K Badger (Aircraft 1731)

### Weapons Carried

4x YJ-21
2x KG-800 ECM Pod

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

1300

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

No need

### Sources

https://www.sinodefenceforum.com/t/h-6-bomber-aircraft-discussions.2326/page-203
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/d28587a8-bc53-4e03-a9d7-ee602a65f121)

**Comment by HunterDNiu** [comment]
I would say its 3: one on centerline and one on each pylon.

**Comment by LuigiP57** [comment]
> I would say its 3: one on centerline and one on each pylon.

Hmm...If under centerline, its position seems too high then...

**Comment by LuigiP57** [comment]
To me, its obvious that there is a pylon under wing with a missile blocking a slim part of the fuselage

**Comment by PygmalionOfCyprus** [comment]
I definitely see four. In fact, I'm not entirely convinced there aren't five/six: definitely two on the wing(s) and one (two?) on the centerline.

<img width="821" alt="image" src="https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/7da8f6d5-6303-4329-aea6-d209d6f600c1">

I didn't even know the H-6 could carry that many. Definitely a very impressive load.

Handled 507.
