### ISSUE TITLE
HQ-17 change FCR to AESA

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4694]
### DB Selector

DB3K

### Affected DBID(s)

Facility 2515, Sensor 

### Summary of Changes

HQ-17's guidance radar is an AESA upgrade from the original TOR-M1 design. Search radar also shown to have range of 45km

Changes: FCR to AESA, increase search radar range to 24nmi

![hq17 aesa](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/3f120591-ea6c-4e4f-9321-e4ab4a2fc5a0)

![hq17 aesa 2](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/163086464/ab4dec35-be3b-46dd-8f4a-dec33cbfdf1e)

### Sources

https://threadreaderapp.com/thread/1672812249860173824.html
https://pbs.twimg.com/media/FzcQjghWIAAxLen.jpg
https://en.wikipedia.org/wiki/HQ-17

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Also made some general adjustments to the HQ-17 facilities based on this info.
