### ISSUE TITLE
Please add Saudi-Arabia as user of KM-SAM Block-2

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#4697]
### DB Selector

DB3K

### Affected DBID(s)

Facility #3423

### Summary of Changes

Saudi Arabia has awarded South Korea's LIG Nex1 a $3.2 billion contract for 10 Cheongung M-SAM II batteries. M-SAM II is a medium ranged surface to air missile system with an advertised capability of intercepting both ballistic & aerodynamic threats.

### Sources

https://www.reuters.com/business/aerospace-defense/saudis-agree-32-bln-deal-buy-south-korean-missile-defence-system-ministry-2024-02-06/
https://www.globaldefenseaerospacepost.com/news/articleView.html?idxno=1272
https://www.defensenews.com/land/2024/02/07/saudi-arabia-signs-32b-deal-for-south-korean-air-defense-systems/

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
