### ISSUE TITLE
Add Pantsir S2/SE2

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#47]
### DB Selector

DB3K

### Hypothetical

- [ ] Yes

### Name

SAM Plt (SA-22 Greyhound [Pantsir SM2]

### Facility Type

SAM

### Country

Russia

### Service

Army

### In Commission

2016

### Crew

3

### Dispersion Radius (m)

40

### Sensors

2x SOT-S radar
Generic IR
Generic TV
Mk 1 Eye ball

### Mounts

2x SA-22 Greyhound [96k6 Pantsire-S1E, Kamaz-6560 8x8] TELAR

### Comments

S2 variant with improved SOTS-S Radar deployed to Syria in 2016 to counter drone threat (getting over the top of the s1's 80 degree radar coverage.)

### Sources

https://twitter.com/AbraxasSpa/status/695156267069935616
https://twitter.com/Russian_Defence/status/916057405720616966
https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/pantsir-s2_short-range_cannon_missile_air_defense_system_technical_data_sheet_specifications_pictures_video_12205164.html

**Comment by Jkryos** [comment]
Added DB3K 493.
