### ISSUE TITLE
PLAAF H-6KG Bomber

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4700]
### DB Selector

DB3K

### Baseline

4816

### real-life

Yes

### Name

H-6KG God of War(H-6J Copy)

### Country

China

### Service

PLAAF

### In Commission

2020-

### Length (m)

34.8

### Wingspan (m)

33

### Height (m)

10.4

### Empty Weight (kg)

38500

### Maximum Takeoff Weight (MTOW) (kg)

79000

### Payload Weight (kg)

13000

### Crew

3

### Propulsion

2×WS-18(D-30KP-2 Copy)

### Service Ceiling (ft)

45000

### Military/Afterburner Speed (kt)

550

### Cruise Speed (kt)

420

### Supercruise

No

### Ferry Range (nm)

5100

### Sensors
Add generic ESM [advances](late 2000s)
same as H-6J

### Mounts

same as H-6J

### Loadout Options

-6×FAB-1000M-62 GPB[FAB-1000M-62 GPB]
-12×FAB-500M-54 GPB[FAB-500M-54 GPB]
-12×Mine(Bottom,Acoustic Narrow-Band Fuze&Target Discrimination)[Generic 500kg Bottom Mine]
-6×YJ-100 ASCM 2×KG-800 ECM Pod[YJ-100,China KG-800 ECM Pods]
-2×YJ-100 ASCM 2×KG-800 ECM Pod[YJ-100,China KG-800 ECM Pods,Long range]
-6×KD-20(CJ-10A) ALCM 2×KG-800 ECM Pod[CJ-10A,China KG-800 ECM Pods]
-2×KD-20(CJ-10A) ALCM 2×KG-800 ECM Pod[CJ-10A,China KG-800 ECM Pods,Long range]
-6×KD-63 2×KG-800 ECM Pod[KD-63,China KG-800 ECM Pods]
-2×KD-63 2×KG-800 ECM Pod[KD-63,China KG-800 ECM Pods,Long range]
-6×YJ-12 2×KG-800 ECM Pod[YJ-12,China KG-800 ECM Pods]
-2×YJ-12 2×KG-800 ECM Pod[YJ-12,China KG-800 ECM Pods,Long range]
-4×YJ-21 2×KG-800 ECM Pod[YJ-21,China KG-800 ECM Pods,Heavy]
-2×YJ-21 2×KG-800 ECM Pod[YJ-21,China KG-800 ECM Pods]
-6×YJ-83K 2×KG-800 ECM Pod[YJ-83K,China KG-800 ECM Pods]
-2×YJ-83K 2×KG-800 ECM Pod[YJ-93K,China KG-800 ECM Pods,Long range]
-6×YJ-83KB 2×KG-800 ECM Pod[YJ-83KB,China KG-800 ECM Pods]
-2×YJ-83KB 2×KG-800 ECM Pod[YJ-83KB,China KG-800 ECM Pods,Long range]
-6×AKF-98A 2×KG-800 ECM Pod[AKF-98A,China KG-800 ECM Pods]
-2×AKF-98A 2×KG-800 ECM Pod[AKF-98A,China KG-800 ECM Pods,Long range]
-18×LS-6-500 Extended-Range Bombs 2×KG-800 OECM pods[LS-6-500 Extended-Range Bombs,China KG-800 ECM Pods]
-18×LT-2(LS-500J) LGB 2×KG-800 OECM pods[LT-2 LGB,China KG-800 ECM Pods]
-6×YJ-1000 LGB[YJ-1000 LGB]
-18×GB-6 2×KG-800 OECM pods[GB-6,China KG-800 ECM Pods]

### Comms/Datalinks

same as H-6J

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/48a8e3b3-d161-4426-a47b-41f6c2d70d9e)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/023573dd-d6cc-4c55-a3a3-9ed01ca7e719)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/1ad0e364-1d37-4877-8e2f-2535b70f35ff)
PLAAF H-6J Copy Bombers,being considered as being combined with PLANAF H-6J and PLAAF H-6K Bomber.
It's currently called as H-6KG.

**Comment by LuigiP57** [comment]
https://chinese-military-aviation.blogspot.com/p/attack-aircraft.html

**Comment by LuigiP57** [comment]
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/0e90e59e-163b-4bca-9f0d-0e2cd398bb6b)
(credit to Wikipedia)

Also notice that there are Blade antennas on the tail, which could be **ESM/ELINT device**

**Comment by LuigiP57** [comment]
You are so quick and tacit understanding with me, I was just about to submit an H-6KG ticket. XD

**Comment by PygmalionOfCyprus** [comment]
I was about to grumble that I had already added this and then I realized you guys still don't have 506 yet.

It was added 506. I did a huge, super-deep dive into the entire H-6 family during the PLAAF review so I hope you will be happy to see it. :)
