### ISSUE TITLE
PLAAF aircraft radar capability adjustment

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4701]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5485 5484 4157 4865 6074

### Summary of Changes

  

- [ ] Add LPI property
- [ ] Add SAR property
- [ ] Add Frequency Agile property

### Sources

To quote a report in China's state-run Global Times, when it reported on the J-16, it mentioned that "the J-16 is a 3.5-generation aircraft that has made great breakthroughs in radar and fire control systems compared to previous aircraft," and we believe that the Chinese have made encouraging progress in radar systems, We can see some technological progress in their foreign trade products. We have reason to believe that the technical level of its own radar will be higher than that of foreign trade products, which has been confirmed in many cases. At least it won't fall too far behind its contemporaries. Due to China's strict secrecy system, please forgive me for so much speculation, but I think it is within reasonable limits.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/ccb55afe-5931-435b-a4c2-b8d456610294)
https://www.globaltimes.cn/page/202103/1219382.shtml

**Comment by yU2187sie** [comment]
#4214

**Comment by yU2187sie** [comment]
In CMO, the SU-35's Irbis-E radar also has a Frequency Agile property, and AESA radars in service with the PLAAF, which are technically more advanced than the Russian Irbis-E radar, should already use this technology.

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
