### ISSUE TITLE
China,PLANAF,J-15B AESA radar improvements

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4702]
### DB Selector

DB3K

### DBID to Copy

Sensor 5485

### Hypothetical

No

### Name

Sensor 5484

### Country

China

### Service

PLANAF

### In Commission

2022

### Other Changes

The J-15B has essentially the same airframe as the J-16, so the radar installed on the J-15B is likely to be a variant based on the J-16 AESA. The development of the J-15B will mainly take place after 2020, so we speculate that its radar level is most likely in the early 2020s.
At the same time, please synchronize the J-15B radar to the same data as the J-16 radar. Forgive me for being lazy :)

### Sources

https://chinese-military-aviation.blogspot.com/p/fighters-ii.html

**Comment by yU2187sie** [comment]
#4699

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Also fixed what looked to be a missed copy-error where there was AESA on some J-15s versions that should not have had them.
