### ISSUE TITLE
China, GJ-11, Remove ISAR package if having AESA SAR mode

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4703]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 4961 4962 4963

### Summary of Changes

remove sensor 6073 ISAR package if add SAR property to GJ-11 AESA.

### Sources

DB itself

**Comment by LuigiP57** [comment]
#4701

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
