### ISSUE TITLE
US Navy, AIM-174B AAM/ASM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4704]
### DB Selector

DB3K

### DBID to Copy

Weapon 3541

### Hypothetical

No

### Name

AIM-174B, Air-Launched SM-6 Blk IA

### Country

US

### Service

USN

### Other Changes

Using SM-6 Blk IA which can perform Air to Surf mission as baseline would be suitable.

### Sources

https://twitter.com/John_A_Ridge/status/1808370955602780337
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/482182fe-ed66-4c3c-8b50-98e9ec92d105)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/e38bc511-28b7-47ba-bd54-9c22e6c589eb)

**Comment by LuigiP57** [comment]
Given that there are a few too many hornet E/F entries in DB, it is best to copy one extra E and one extra F entry each for this weapon.

**Comment by LuigiP57** [comment]
#4612 #1658

**Comment by yU2187sie** [comment]
This is a weapon that the US military has experimented with many times, and I think it is reasonable. By tracking US military intelligence, we can get a better idea of what weapons are being developed.

**Comment by LuigiP57** [comment]
> This is a weapon that the US military has experimented with many times, and I think it is reasonable. By tracking US military intelligence, we can get a better idea of what weapons are being developed.

At the same time, how I wish the Chinese could be **a little less secretive**...

**Comment by yU2187sie** [comment]
> > This is a weapon that the US military has experimented with many times, and I think it is reasonable. By tracking US military intelligence, we can get a better idea of what weapons are being developed.
> 
> At the same time, how I wish the Chinese could be **a little less secretive**...

Oooooo. This was impossible because the PLA had an internal saying that "to keep secrets is to ensure the foundation of victory in war", which made it difficult for me to obtain useful information through PLA media propaganda. So when I was doing OSINT collection and analysis on PLA, I was forced to make assumptions based on OSINT to infer the PLA's true capabilities.

**Comment by LuigiP57** [comment]
https://twitter.com/Doha104p3/status/1808397001941242281
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/bd2ec14b-8ba3-4d8e-aee5-b655dd2fd5b1)
https://twitter.com/se_spotting/status/1808404558319685745
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/0c3361a0-c638-4d29-9101-2e001d69edf8)
Alright, looks like this is a training missile, not a test one. USN is officially equipped with the PL-17 and AA-13 equivalents.

**Comment by KLABDB3K** [comment]
Apparently it's an N not an X, does the fact there's a training round indicate its in service operationally?
https://x.com/Doha104p3/status/1808368864067002651t=UtKfLEiW6qdr2gs4VFKg4A&s=19

*Update (and I forgot to copy the link!) Apparently from USN itself it is a operational system!  Gold star for whoever orchestrated this program and if SM-6 ALC is AIM-174B and I wonder what happened to the A model and how long that's been in service??

**Comment by yU2187sie** [comment]
> Doesn't the X imply it's not yet in service? https://x.com/Doha104p3/status/1808368864067002651?t=UtKfLEiW6qdr2gs4VFKg4A&s=19

By convention, if training ammunition has been mounted, it must mean that the army has been equipped with live ammunition.

**Comment by LuigiP57** [comment]
![3ba02db50217b558fef520fa15eabb35](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/9d29b7b9-c550-4585-91aa-d35e4eda33f9)
![IMG_2773](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/06316352-3186-4d8f-9911-27bc5d6828ba)
OK, according to images I gather, the actual training missile should be CATM not N (at least I haven't seen). This code should have other meaning. Please forgive me for being unprofessional, my strength is in PLA OSINT.

**Comment by tbrandon517** [comment]
Additional 

https://www.twz.com/air/aim-174-super-hornet-launched-variant-of-sm-6-missile-breaks-cover-in-hawaii?fbclid=IwZXh0bgNhZW0CMTEAAR36YgIPkCRLKoqlAUX2kTlgecqSxohmktMvMXLA0BiQbZoQs0GlydiTQGM_aem_4lbgzTEQWrXJEQQIgkS5ng

**Comment by HunterDNiu** [comment]
Cf #4612: 
1. Before more information comes to us I'm proposing the same 230nm range, max altitude to 45km (snap up is 120kft) and max speed 4500kt.
2. CEC DL and likely also AIM-120 DL. 
3. For F-18, 1x (centerline) with 2 drop tanks, 2x (inner hardpoints) with 1 drop tanks, outboard AAM optional (both AMRAAM and JTAM). 
4. For F-15E and EX, if we estimate the AIM-174 weight with SM-2MR all wing pylons could carry one, centerline could carry JASSM so it's also capable. Therefore options for 1x, 2x, 4x, 5x with other AA optional.

**Comment by LuigiP57** [comment]
> Cf #4612:
> 
> 1. Before more information comes to us I'm proposing the same 230nm range, max altitude to 45km (snap up is 120kft) and max speed 4500kt.
> 2. CEC DL and likely also AIM-120 DL.
> 3. For F-18, 1x (centerline) with 2 drop tanks, 2x (inner hardpoints) with 1 drop tanks, outboard AAM optional (both AMRAAM and JTAM).
> 4. For F-15E and EX, if we estimate the AIM-174 weight with SM-2MR all wing pylons could carry one, centerline could carry JASSM so it's also capable. Therefore options for 1x, 2x, 4x, 5x with other AA optional.

For 1. I'm not particularly good at US OSINT. But it seems that only the SM-6 Blk IB will reach hypersonic speeds. My suggestion is 2900kt (though RIM-174B is 2650kt in this game), the same as SM-6 Blk IB in the database. It has a large middle wing, which means it is probably not as fast as the PL-17, which has only tail fins.

For 4. Do we have evidence that this weapon will be on the F-15E/EX? If this is a reasonable estimate (new weapons are definitely likely to be mounted on new platforms), then I should start proposing PL-17 mounts on J-35 and J-15B

**Comment by HunterDNiu** [comment]
> > Cf #4612:
> > 
> > 1. Before more information comes to us I'm proposing the same 230nm range, max altitude to 45km (snap up is 120kft) and max speed 4500kt.
> > 2. CEC DL and likely also AIM-120 DL.
> > 3. For F-18, 1x (centerline) with 2 drop tanks, 2x (inner hardpoints) with 1 drop tanks, outboard AAM optional (both AMRAAM and JTAM).
> > 4. For F-15E and EX, if we estimate the AIM-174 weight with SM-2MR all wing pylons could carry one, centerline could carry JASSM so it's also capable. Therefore options for 1x, 2x, 4x, 5x with other AA optional.
> 
> For 1. I'm not particularly good at US OSINT. But it seems that only the SM-6 Blk IB will reach hypersonic speeds. My recommendation is 2900kt, the same as SM-6 Blk IB in the database. It has a large intermediate wing, which means it is probably not as fast as the PL-17, which has only tail fins.
> 
> For 4. Do we have evidence that this weapon will be on the F-15E/EX? If this is a reasonable estimate (new weapons are definitely likely to be mounted on new platforms), then I should start proposing PL-17 mounts on J-35 and J-15B

So the 4500kt number is the max target speed. Weapon speed would depend on its propulsion (the same Mk104 booster) and flight profile. 
I couldn't get you the exact image but I do believe there was a mock SM-6 upper stage spotted on F-15 inflight

**Comment by LuigiP57** [comment]
> I couldn't get you the exact image but I do believe there was a mock SM-6 upper stage spotted on F-15 inflight

OSINT is always lagging to some extent, and if it can't be given, then it's even more suspicious.

However, I still think that since it is a new air-to-air weapon that can definitely be carried on the new fighter platform, I may be inclined to: AIM-174B for F-15EX & F-35 (external), PL-17 for J-35 (external) & J-15B. What do you think?

I've always thought that we don't have to stick to whether OSINT embodies anything or not, but sometimes we have to rely on **reasonable speculation** for this kind of simulation, right? **Reasonable speculation is not unfounded delusion**.

**Comment by HunterDNiu** [comment]
> > I couldn't get you the exact image but I do believe there was a mock SM-6 upper stage spotted on F-15 inflight
> 
> 
> 
> OSINT is always lagging to some extent, and if it can't be given, then it's even more suspicious.
> 
> 
> 
> However, I still think that since it is a new air-to-air weapon that can definitely be carried on the new fighter platform, I may be inclined to: AIM-174B for F-15EX & F-35 (external), PL-17 for J-35 (external) & J-15B. What do you think?
> 
> 
> 
> I've always thought that we don't have to stick to whether OSINT embodies anything or not, but sometimes we have to rely on **reasonable speculation** for this kind of simulation, right? **Reasonable speculation is not unfounded delusion**.

I would wait for F-35. And for PLA aircrafts I suppose everything could go ahead as they bear legitimate expectations.

**Comment by PygmalionOfCyprus** [comment]
Man, I hate it when world militaries implement paradigm-changing weapons during the DB release freeze. 😅 

Unfortunately 507 is locked down for release but this will be (almost) the first thing we add for 508.

**Comment by tbrandon517** [comment]
> Man, I hate it when world militaries implement paradigm-changing weapons during the DB release freeze. 😅
> 
> Unfortunately 507 is locked down for release but this will be (almost) the first thing we add for 508.

Happy dance!

**Comment by tbrandon517** [comment]
Operationally Deployed

https://www.navalnews.com/naval-news/2024/07/u-s-navy-confirms-sm-6-air-launched-configuration-is-operationally-deployed/?fbclid=IwZXh0bgNhZW0CMTEAAR3k0OCp7QRakD-qoAY5f10W0J8qI2hfCi-cEUoqR7pFed3XP0ckBLZU5wY_aem_9C6NTWVB8LZuK5FtkwMzGw

**Comment by tbrandon517** [comment]
"At its surface-to-air published range, the SM-6 achieves ranges of 130 nmi (240 km) with even higher estimated ranges up to 250 nmi (463 km). An air-launched variant would dramatically increase that range, giving a Carrier Air Wing (CAW) more reach to defeat distant targets."

250 nmi 😳

https://www.navalnews.com/naval-news/2024/06/air-launched-sm-6-spotted-again-on-f-a-18-super-hornet/

**Comment by LuigiP57** [comment]
> "At its surface-to-air published range, the SM-6 achieves ranges of 130 nmi (240 km) with even higher estimated ranges up to 250 nmi (463 km). An air-launched variant would dramatically increase that range, giving a Carrier Air Wing (CAW) more reach to defeat distant targets."
> 
> 250 nmi 😳
> 
> https://www.navalnews.com/naval-news/2024/06/air-launched-sm-6-spotted-again-on-f-a-18-super-hornet/

"The range is reportedly between 300–500 km (190–310 mi) by various media, or 400 km (250 mi) class by Royal United Services Institute"

270 nmi !

https://en.wikipedia.org/wiki/PL-17

When I woke up in the morning light in Perth, the first notification I saw on my phone was your reply. 

Now I am getting closer and closer to agreeing with @PygmalionOfCyprus, especially as we are both inundated with countless OSINT and propoganda. Our dear DB Manager are very wary of OSINT from China, fearing that they are from unofficial propaganda tactics. However, I would like to ask, can the OSINT originated from the non-Chinese/English channel not be propaganda or some kind of "misinformation"?

Regarding the SM-6, I have never been able to find any really reliable source for the "460km/250nm" claim, instead, it's more like some kind of propagation distortion of the more common "400km/250mi" claim. The same is likely to be on the AIM-260 as I mentioned earlier #4046 https://en.wikipedia.org/wiki/AIM-260_JATM.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/e4a7a7fe-2469-46dc-9b07-12ef10a0b344)

I "like" to believe that the US is still ahead of its rivals in missile technology, so I applied for a maximum range of 230nm, just like the SAM version with booster. The initial speed and altitude that the rhino can provide when launching it should be similar to what the mk 72 can provide (it more than doubles the range of the SM-6 compared to its predecessor using same mk 104 motor).

You can think I am defending the PLA or some kind of "don't wanna see US too strong". However, as an OSINT enthusiast with my own principles, I will offer my own opinions on some modifications and methods based on OSINT. I'm sure our DB manager will understand what I mean.

**Comment by LuigiP57** [comment]
In addition, there is little point in obsessing about the maximum range. A reasonable and representative value is enough. Nevertheless, I must say that PLA weapons in this game are always arranged according to the "lowest estimate". For example, the PL-15 with "at least 200km" is set to 200km/108nm maximum range. The AIM-260, with the same standard, is 120nm.

**Comment by tbrandon517** [comment]
Additional 

https://www.twz.com/air/disclosure-of-new-aim-174b-missile-brings-navys-future-air-to-air-strategy-into-focus

**Comment by PygmalionOfCyprus** [comment]
Handled 508. I've also pushed a mod 507a with this change to the devs and requested that it be released instead of the original 507, so you guys will get to play with the AIM-174B sooner rather than having to wait for 508 in two months.

No promises (nor do I know when the 506/507 release is happening) but I'm doing my best!
