### ISSUE TITLE
TB-001 UAV 

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4705]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 7062,7063

### Summary of Changes

change its service ceiling to 26000ft

### Sources

](https://www.tengden.com/product/6.html)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/4c369518-dd70-4972-9f98-cc0f008dae09)

**Comment by PygmalionOfCyprus** [comment]
At least in my current DB version (508 working) the TB-001 already has a max ceiling of 8000m (26247ft), with the 001D getting an extra 1000m due to the extra engine.
