### ISSUE TITLE
Add OFAB-250-270 UMPK SU-34 Loadout

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4706]
### DB Selector

DB3K

### User(s)

SU-34, SU-34M

### Weapons Carried

4x OFAB-250-270 UPMK
2x AA-11 Archer
1x 3000 liter Drop Tank

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://x.com/GuyPlopsky/status/1808802927244681517
https://x.com/GuyPlopsky/status/1801205153191571557
https://x.com/GuyPlopsky/status/1796444303306502328

**Comment by bostonmyk** [comment]
Related 
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/4147

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
