### ISSUE TITLE
China, KJ-700 AESA, VHF Mod

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4707]
### DB Selector

DB3K

### Baseline

sensor 7122

### Hypothetical

No

### Name

KJ-700 AESA [VHF Mod]

### Sensor Generation

Early 2020s

### Range (nm)

0.2-350

### Sensor Capabilities

Air Search, Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Non-Cooperative Target Recognition (NCTR) - Jet Engine Modulation [Class Info], Continuous Tracking Capability, Track While Scan (TWS), Moving Target Indicator (MTI), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA), Can Classify Ground Targets (SAR), Frequency Agile

### Search/Track Frequencies

A Band (30-250 MHz) [Old P Band (HF)] 100-300 cm

### Lower Frequency (Hz)

150MHz

### Upper Frequency (Hz)

200MHz

### Scan Interval (s)

6

### Horizontal Beamwidth (deg)

1

### Vertical Beamwidth (deg)

1

### System Noise Level (dB)

2

### Processing Gain/Loss (dB)

12

### Peak Power (W)

1200000

### Comments

According to OSINT analysis, KJ-700's radar uses a **Digital array - Dual band (presumed VHF & S)**, however, the presence of **different-bands-in-one-sensor** in game will **cause the detection range to be severely degraded** (I mentioned in earlier tickets), so I intend to submit only one mod of this sensor, and for S-band mode, you can just copy the ticket's data and modify the band to E

### Sources

https://chinese-military-aviation.blogspot.com/p/surveillance-aircraft-ii.html
https://www.sinodefenceforum.com/t/pla-aew-c-sigint-ew-and-mpa-thread.951/page-299
(page 299-304)
We can see what the digital VHF radar array looks like from the official model of the WZ-9 UAV
https://twitter.com/RupprechtDeino/status/1604399316776456193

**Comment by PygmalionOfCyprus** [comment]
Sorry, maybe I'm just missing it, but what is the source for the presumed VHF/S-band array? I can't find mention of VHF on the SDF or in the other sources you linked.

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus 

I have to admit, I actually learned about the KJ-700 some time before I proposed the ticket (almost immediately after it was revealed). I did see references to **"Dual band Radar"** from some Chinese OSINT accounts that could be considered reliable, pointing to some kind of **"advanced-low-frequency radar"** technology (I have mentioned this source in other tickets before). But, unfortunately, they were **"blocked"** at the same time I proposed the ticket. Just leave some general paraphrases on X.
https://twitter.com/jpg2t785/status/1804079061175861311
https://twitter.com/_ConflictsWatch/status/1803783937413525824

In fact, the combination of VHF & S band is not difficult to understand, it can meet the needs of anti-stealth, but also to meet the needs of long-range accurate detection and fire control guidance. 

As noted by Aviationist in their article on KJ-700: Modern AWACS have great versatility.
https://theaviationist.com/2024/06/22/kj-700/

> In fact, they are also expected to classify enemy radar emissions with basic EW/ELINT (Electronic Warfare/Electronic Intelligence) capabilities, **track LO (Low Observable) fast maneuvering cruise missiles**, incorporate inputs from satellites, **detect stealth aircraft**, coordinate with ground-based AD (Air Defenses) and trade information with friendly assets over data links.

**Comment by PygmalionOfCyprus** [comment]
Sure, but "dual band radar" much more frequently refers to S/X-band, right? That's also a pairing with more precedent for AEW aircraft.

I don't doubt that it would be _useful_ for them to have a VHF radar on their AWACS for improved anti-stealth capability, but I don't think we can make that assumption just based on vague references to a "dual band radar" alone. It's far more likely IMO that it's just a conventional radar array, maybe L/S or X/S, etc. Of course we can change this in the future if we discover that I'm wrong, but I need stronger evidence.

**Comment by LuigiP57** [comment]
> Sure, but "dual band radar" much more frequently refers to S/X-band, right? That's also a pairing with more precedent for AEW aircraft.
> 
> I don't doubt that it would be _useful_ for them to have a VHF radar on their AWACS for improved anti-stealth capability, but I don't think we can make that assumption just based on vague references to a "dual band radar" alone. It's far more likely IMO that it's just a conventional radar array, maybe L/S or X/S, etc. Of course we can change this in the future if we discover that I'm wrong, but I need stronger evidence.

Well then, considering the needs of anti-LO-target, it would be better to give it L/S(NATO D/E band radar). But do notice that don’t put two band in one sensor in order to keep its best detection performance.

**Comment by PygmalionOfCyprus** [comment]
>it would be better to give it L/S(NATO D/E band radar)

Yep, this is what I did when I added the KJ-700 entry. 🙂 

>But do notice that don’t put two band in one sensor in order to keep its best detection performance.

Mhm. I built it as a sensor group w/ two distinct sub-entries so that should mitigate the problem.
