### ISSUE TITLE
China, PLAAF & PLANAF, KJ-700/H AEW&C

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4708]
### DB Selector

DB3K

### Baseline

Aircaft 3683

### Hypothetical

No

### Name

KJ-700/KJ-700H (For NA)

### Country

China

### Service

PLAAF & PLANAF

### In Commission

2024

### Length (m)

-

### Wingspan (m)

-

### Height (m)

-

### Empty Weight (kg)

-

### Maximum Takeoff Weight (MTOW) (kg)

-

### Crew

-

### Propulsion

-

### Service Ceiling (ft)

-

### Military/Afterburner Speed (kt)

-

### Cruise Speed (kt)

-

### Supercruise

No

### Ferry Range (nm)

-

### Sensors

KJ-700 AESA
SIGINT early 2020s (It uses a highly integrated and versatile ESM system, from the looks)
DECM early 2020s
IR Camara Advanced
Mk1 eyeball

### Mounts

-

### Loadout Options

-

### Sources

https://chinese-military-aviation.blogspot.com/p/surveillance-aircraft-ii.html
https://www.sinodefenceforum.com/t/pla-aew-c-sigint-ew-and-mpa-thread.951/page-299
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/3689fe27-6c1c-498c-9afb-6c7689bab55a)

**Comment by LuigiP57** [comment]
#4707

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
