### ISSUE TITLE
Submarine  #184 - PL-677 Lada [P.1650] (Russia [1992-] - 2011) Lada 'St Petersburg' Russian Navy out of service. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4709]
### DB Selector

DB3K

### Affected DBID(s)

Submarine #184 - PL-677 Lada [P.1650] (Russia [1992-] - 2011)

### Summary of Changes

Out of service. Per TASS. 

### Sources

MOSCOW, February 5. /TASS/. Tass/. The lead non-nuclear submarine of Project 677 (Lada cipher) "St. Petersburg" of the Northern Fleet (SF) has been withdrawn from the Russian Navy (Navy) and will be disposed of. This was reported to TASS by two sources close to the military-industrial complex (MIC) of the Russian Federation.

"The submarine St. Petersburg was withdrawn from the Navy. A decision has been made to dispose of it," said one of the agency's interlocutors. The second interlocutor confirmed this information and added that the enterprise at which the disposal will be carried out will be determined following the results of the tender.

TASS has no official confirmation of this information.

Earlier, a source close to the Navy told TASS that the submarine "St. Petersburg" is planned for write-off, since its modernization is very expensive, with these funds you can build a new boat."

Translated from the TASS announcement. * Subject to confirmation.

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Added new entry to represent the post-redesign subs in class.
