### ISSUE TITLE
AAA Plt/2 (23mm ZSU-23-4 Shilka x 2) (2x pr Bn)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#471]
### DB Selector

DB3K

### DBID to Copy

facility/908/DB3K

### Hypothetical

No

### Name

AAA Plt/2 (23mm ZSU-23-4 Shilka x 2) (2x pr Bn)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

None Known

### Mounts

None Known

### Loadout Options

None Known

### Other Changes

None Known

### Sources

https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
