### ISSUE TITLE
Add Belarus SSM Bty (Shahed-136 [Geran-2] 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4711]
### DB Selector

DB3K

### DBID to Copy

Facility 3666

### Hypothetical

Yes

### Name

SSM Bty (Shahed-136 [Geran-2]

### Country

Belarus

### Service

Air Force

### In Commission

2024

### Sensors

same

### Mounts

same

### Loadout Options

same

### Sources

https://x.com/IranMilitaryNet/status/1808435727677395398
https://x.com/piotr_butowski/status/1808782665992073637/photo/1
https://mil.in.ua/en/news/belarus-arms-military-with-shahed-geran-drones/
https://x.com/JohnH105/status/1808540240849600857

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
