### ISSUE TITLE
Add 4 Bomb Belouga Cluster Bomb loadout to French Jaguars

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4713]
### DB Selector

DB3K

### User(s)

All French Jaguars 1981-2005

### Weapons Carried

4x BLG.66
2x Magic
1x 1200 L Droptank

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://x.com/BaguetteWeapons/status/1809172688402874723/photo/1
https://master194.com/site/photo_avion/jaguar/pages/jaguar_35_jpg.htm
https://www.airvectors.net/avjag.html#m2

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
