### ISSUE TITLE
Add 4x Belouga Cluster Bomb Loadout to Moroccan F.1CH and EH

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4714]
### DB Selector

DB3K

### User(s)

Aircraft 1209, 1210, 1211,3153

### Weapons Carried

4x BG.66 Belougas,
2x Magic 1 R.550
1x 1200 Liter Drop Tank

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Please add ALE-40 chaff and flare dispensers to these aircraft as well.

Doesn't look like they signed on to cluster bomb ban treaty.

### Sources

https://www.airliners.net/photo/Morocco-Air-Force/Dassault-Mirage-F1CH/575861/L
https://www.airvectors.net/avmirf1.html

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
