### ISSUE TITLE
Add Moroccan Radar (AN/TPS-43G) 1983

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4715]
### DB Selector

DB3K

### DBID to Copy

Facility 620

### Hypothetical

Yes

### Name

Radar (AN/TPS-43G)

### Country

Morocco

### Service

Army

### In Commission

1983

### Number in Service

16x

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Royal_Moroccan_Army
https://premium.globalsecurity.org/military/world/morocco/air-force-modernization.htm

Sipri
Morocco	United States	1977	?	6		TPS-43	air search radar	6	?	1981; 1982; 1983	New	$20 m deal (part of $200m deal for air surveillance network)	9	54	54

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
