### ISSUE TITLE
Add Moroccan Arty Bty (PHL-03 MLRS x6)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4717]
### DB Selector

DB3K

### DBID to Copy

Facilty 3622

### Hypothetical

Yes

### Name

Arty Bty (PHL-03 MLRS x6)

### Country

Morocco

### Service

Army

### In Commission

2010

### Number in Service

12x

### Sources

https://x.com/trhdwine/status/1777569620569870387/photo/4
https://x.com/KOMARMIES/status/1495901322951995394

Sipri
Morocco	China	2009	?	12	?	PHL-03 300mm	self-propelled MRL	12		2010	New		1.2	14.4	14.4

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
