### ISSUE TITLE
Add Peruvian Mi-171Sh-P Hip H

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4719]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6768

### Hypothetical

Yes

### Name

Mi-171Sh-P Hip H

### Country

Peru

### Service

Airforce

### In Commission

2016

### Number in Service

24x

### Sources

https://x.com/DefensaCom/status/746212607741198336
https://x.com/DefensaCom/status/1220785873014480896
https://en.wikipedia.org/wiki/Peruvian_Air_Force

Sipri
Peru	Russia	2013		24		Mi-17	transport helicopter	24	?	2014; 2015; 2016	New	$406-540 m 'Project Salkantay' (incl $89 m for assembly/overhaul plant; $180 m offsets); incl 8 assembled in Peru; Mi-171ShP armed version	7.25	174	174

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
