### ISSUE TITLE
Please amend load out for #359 - EC.665 Tigre HAD (France - 2014) as #19726 is inaccurate and consider AGM-114N as well.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#472]
### DB Selector

DB3K

### Affected DBID(s)

#359 EC.665 Tigre HAD (France - 2014)

### Summary of Changes

#19726 AGM-114K Hellfire II, SNEB 68mm Rockets, Mistral 2 ATAM (Strike, Land/Naval) This is not possible. 
Cannot carry 8 Hellfire 1 x 22 tube RP and 4 Mistral.  **Please Amend to 8 Hellfire, 12 Rockets and 2 Mistral.**

France also ordered  #527 - AGM-114N Hellfire II [Thermobaric]
As an aside I do not think the Hellfire was available before 2015 at the very earliest but its a minor point. 

https://www.dsca.mil/search/node?keys=french+hellfire the first DSCA order dates from Nov 2015. 

EC.665 Tigre HAD (France - 2014)
Load out should reflect
The Tigre HAD has a total of four pylons, two port/ two starboard.
The loads can be asymmetric so it is possible to mix and match. 

Each inner pylon can accommodate:
4 x AGM-114K Hellfire (or AGM-114N - ordered May 2, 2016) - so a total of 8 Hellfire Maximum.
or
1 x 22 tube TDA 68mm Rocket pod. so a total of 44 Rockets on inner pylons.
or 
1 x 12 Tube TDA 68mm Rocket Pod
or 
1 x Fuel tank

Each outer pylon can accommodate:
2 x Mistral ATAM - so total of 4 Mistral maximum
or
1 x 12 Tube TDA 68mm Rocket pod so a total of 24 Rockets on outer pylons. 

![Tigre HAD WEAPONS](https://user-images.githubusercontent.com/99494755/156452207-028790b5-c2e7-4039-99a8-96efc223184a.JPG)
 *Plus I am still looking into if reports of a laser guided 68mm rocket actually entered service and evidence of it.

### Sources

https://www.airliners.net/photo/France-Army/Eurocopter-EC-665-Tigre-HAD/2681633/L

http://www.airliners.net/photo/France-Army/Eurocopter-EC-665-Tigre-HAD/2291818
Aysmetric load out of 8 Hellfire with one 12 x 68mm Rocket pod and 2 Mistral on the outer pylon. 

https://www.dsca.mil/press-media/major-arms-sales/government-france-hellfire-missiles-0 
AGM-114N as well as AGM-114K

**Comment by PygmalionOfCyprus** [comment]
Snuck the fix into 493. Also added more loadouts incorporating the AGM-114K and a mixture of both Hellfire types.
