### ISSUE TITLE
Add Peruvian AAA Plt/2 ZSU-23-4 Shilka x2 1978

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4720]
### DB Selector

DB3K

### DBID to Copy

Facility 909

### Hypothetical

No

### Name

AAA Plt/2 ZSU-23-4 Shilka x2

### Country

Peru

### Service

Army

### In Commission

1978

### Sources

https://www.alamy.com/peruvian-soldiers-saludating-on-board-of-the-zsu-23-4-shilka-a-lightly-armored-soviet-self-propelled-radar-guided-anti-aircraft-weapon-system-spaag-at-the-traditional-military-parade-for-the-197th-anniversary-of-peruvian-independence-day-image215843830.html
https://www.youtube.com/watch?v=RZvcJHhCDck
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Peruvian_Army
Sipri
Peru	Soviet Union	1976	?	36	?	ZSU-23-4 Shilka	self-propelled AA gun	36	?	1977; 1978; 1980	New		7	252	252

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
