### ISSUE TITLE
Add Peruvian SAM Sec (SA-7b Grail [9k32M Strela-2M] Manpads x3 1979

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4721]
### DB Selector

DB3K

### DBID to Copy

Facility 1879

### Hypothetical

Yes

### Name

SAM Sec (SA-7b Grail [9k32M Strela-2M] 

### Country

Peru

### Service

Army

### In Commission

1979

### Sources

Sipri
Peru	Soviet Union	1978	?	500	?	Strela-2	portable SAM	500	?	1978; 1979; 1980; 1981	New		0.04	20	20

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
