### ISSUE TITLE
Add Spanish Radar (AN/TPS-43M)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4722]
### DB Selector

DB3K

### DBID to Copy

Facility 431

### Hypothetical

No

### Name

Radar (AN/TPS-43)

### Country

Spain

### Service

Air Force

### In Commission

1976

### Number in Service

5x

### Other Changes

Modernized to AN/TPS-43M in CMO may be a newer generation IFF (can't remember if we make this distinction!)

### Sources

https://emad.defensa.gob.es/en/operaciones/operaciones-en-el-exterior/37-OTAN-EAP/noticias/listado/231121-ni-tigru-8000horas.html
http://www.fuerzaaerea.mil.ar/material/an-tps43.html
https://x.com/EMADmde/status/1773077536072749378
https://en.wikipedia.org/wiki/AN/TPS-43

Sipri Lines
Spain	United States	1982		3		TPS-43	air search radar	3	?	1983; 1984	New		9	27	27
Spain	United States	1975	?	2		TPS-43	air search radar	2	?	1976	New		9	18	18

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
