### ISSUE TITLE
Set AN/TPS-43, AN/TPS-75 Radars as transportable as cargo

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4723]
### DB Selector

DB3K

### Affected DBID(s)

All AN/TPS-43, AN/TPS-75

### Summary of Changes

Set both to be cargo.

I have not found any distinct weights, but the Wikipedia entry says two trucks are for 75 and one C-130. Likely similar for 43. Mobile Radar site seems to support that as 75 is updated to 43

### Sources

AN/TPS-43
https://nara.getarchive.net/media/members-of-the-71st-tactical-control-flight-begin-to-set-up-an-antps-43e-radar-e71668

AN/TPS-75
https://en.wikipedia.org/wiki/AN/TPS-75
https://en.wikipedia.org/wiki/AN/TPS-75#/media/File:Packed_75.jpg
https://www.mobileradar.org/radar_descptn_3.html#tps
https://www.globaldefensecorp.com/2021/09/17/u-s-air-forces-gan-based-3delrr-to-replace-an-tps-75-pesa-air-search-radar/

**Comment by bostonmyk** [comment]
Haha.. Too big for Chinook internally but can be sling loaded.

https://www.facebook.com/EjercitoAire/photos/a.935421663222152/935421963222122/?type=3

**Comment by bostonmyk** [comment]
Found some TPS-43 Stats

https://www.mobileradar.org/Documents/DAR.pdf

Shelter
4.5 x 2.3 x 2.3 meters
3200 KG
Antenna Module
3.8 x 2.3 x 2.3 meters
1800 KG

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
