### ISSUE TITLE
Set AN/TPS-59 to be transportable as Cargo

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4724]
### DB Selector

DB3K

### Affected DBID(s)

All AN/TPS-59

### Summary of Changes

Looks like a 1 C-130 or 3-Trucks space. 

### Sources

https://www.mobileradar.org/Documents/TPS_59.pdf
https://www.mcasyuma.marines.mil/Photos/igphoto/2000011076/
https://www.afcent.af.mil/Units/386th-Air-Expeditionary-Wing/Photos/igphoto/2000070776/

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
