### ISSUE TITLE
Add Malaysian Radar (AN/TPS-77) 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4726]
### DB Selector

DB3K

### DBID to Copy

Facility 1349

### Hypothetical

No

### Name

 Radar (AN/TPS-77

### Country

Malaysia

### Service

Air Force

### In Commission

2024

### Number in Service

1x

### Other Changes

Donated to Malaysia by US specifically for Labuan site (SCS)

### Sources

https://x.com/GardaAramis/status/1796845484788826522
https://www.janes.com/osint-insights/defence-news/c4isr/malaysia-installs-lockheed-martins-long-range-radar-in-labuan
https://www.ang.af.mil/Media/Article-Display/Article/2772150/royal-malaysia-air-force-trains-on-radar-operations-at-wads/

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
