### ISSUE TITLE
Radar (Type 101 [AR-327]) Updates

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4727]
### DB Selector

DB3K

### Affected DBID(s)

Facility 778

### Summary of Changes

Please:
Rename Radar (Type 101 [AR-327 Commander SL])
Reduce range to 253.78 miles (Check stats with the datasheet linked below)
Transportable radar. 1 per C-130 sized aircraft (RAF deployed these to Iraq and Afghanistan)

### Sources

https://woottonbridgeiow.org.uk/decca-legacy/chapter7.php
https://www.baesystems.com/en-media/uploadFile/20210404061448/1434555563319.pdf

Egypt
https://x.com/search?q=Commander-SL%20Radar&src=typed_query&f=top

**Comment by PygmalionOfCyprus** [comment]
Handled 508.

**Comment by PygmalionOfCyprus** [comment]
Bonus points if you can figure out when the Egyptians first started using them. I see they ordered a new batch in ~'21 but can't find the original in-service date.

**Comment by bostonmyk** [comment]
Spent some time on this today and came up empty. Only mention is the Exercise where it appeared and a notice that they were looking to buy more. It looks like this radar did show up at IDEX 2015, but no purchase reporting from that expo and not sure the UK does the same kind of reporting the US does and not in SIPRI.

I'll keep this on my look list, but 2021 is probably ok to start.
