### ISSUE TITLE
US Marine AN/TPS-32 Updates

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4728]
### DB Selector

DB3K

### Affected DBID(s)

Facility 144

### Summary of Changes

Enable for cargo. 
Add out of service date of 1995

### Sources

https://en.wikipedia.org/wiki/AN/TPS-32
http://www.radartutorial.de/19.kartei/11.ancient2/karte008.en.html

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
