### ISSUE TITLE
Add Radar (AN/TPS-15 [AN/TPS-1D])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4729]
### DB Selector

CWDB

### Hypothetical

No

### Name

Radar (AN/TPS-15 [AN/TPS-1D])

### Facility Type

Radar

### Country

United States

### Service

Marines

### Dispersion Radius (m)

40

### Sensors

Same as Sensor #70
Add IFF Flag

### Mounts

1 radar vehicle

### Sources

https://www.mobileradar.org/radar_descptn_3.html
https://www.usmcu.edu/Outreach/Marine-Corps-University-Press/MCH/Marine-Corps-History-Winter-2022-Volume-8-Number-2/Marine-Hawk-Missiles-in-Guant%C3%A1namo-Bay-during-the-Cuban-Missile-Crisis/

**Comment by PygmalionOfCyprus** [comment]
So wait, the MobileRadar site says this is just the AN/TPS-1D with some non-Command-modelled stuff included ("primary power unit, test equipment, [and] maintenance parts"). If that's the case why bother adding a new entry, why not just add TPS-15 to the comments?

**Comment by bostonmyk** [comment]
I was looking at the AN/TPS-15 entry on that site

"Notes: TPS-1 series radars coupled with IFF system makes it a TPS-15 (I'm pretty sure)"

The IFF Flag works right?

M

**Comment by PygmalionOfCyprus** [comment]
Oh weird, so the site is self-contradictory.

Under the TPS-1D entry it says:
> Normally this set would not include a primary power unit, test equipment, or maintenance parts. The nomenclature AN/TPS-15 had been assigned to the set with these items included.

But you're right, under TPS-15 it says:
> TPS-1 series radars coupled with IFF system makes it a TPS-15 (I'm pretty sure)

The IFF flag doesn't currently work in-sim so I think I'm just gonna ignore this for now. Will add TPS-15 to the name, though.
