### ISSUE TITLE
SSM Bn (SS-26 Stone [9K720 Iskander-E] TEL)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#473]
### DB Selector

DB3K

### DBID to Copy

facility/2555/DB3K

### Hypothetical

No

### Name

SSM Bn (SS-26 Stone [9K720 Iskander-E] TEL)

### Country

Armenia

### Service

Army

### In Commission

2016-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.thedrive.com/the-war-zone/37518/video-indicates-armenia-has-fired-its-russian-made-iskander-ballistic-missiles-at-azerbaijan
https://en.wikipedia.org/wiki/9K720_Iskander#Iskander-E

**Comment by PygmalionOfCyprus** [comment]
Added 494.
