### ISSUE TITLE
Add Spanish AAA Sec (35mm Twin Oerlikon GDF-005 x2, Super Fledermaus FCR) 1976

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4730]
### DB Selector

DB3K

### DBID to Copy

Facility 1090

### Hypothetical

No

### Name

AAA Sec (35mm Twin Oerlikon GDF-005 x2, Super Fledermaus FCR)

### Country

Spain

### Service

Army

### In Commission

1976-

### Sensors

Used both Fledermaus FCS (1976)and a few  Skyguard FCS (1980).

### Sources

http://www.armedforces.co.uk/Europeandefence/edcountries/countryspain.htm

Sipri
Spain	Switzerland	1974		92	?	GDF 35mm	anti-aircraft gun	92	?	1975; 1976	New		0.75	69	69
Spain	Switzerland	1974	?	46	?	Super-Fledermaus	fire control radar	46	?	1975; 1976	New	For use with GDF 35mm anti-aircraft guns	3.5	161	161
Spain	Switzerland	2004	?	24		Skyshield	fire control radar	24	?	2006; 2007; 2008	New	EUR82 m deal; for use with GDF 35mm AA guns	6	144	144

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
