### ISSUE TITLE
New loadout - Aircraft Z-9WA #4337 - Z-9WE Haitun (Kenya - 2011) #4395 - Z-9WE Haitun (Cameroon - 2015) #3307 - Z-9WA Haitun (China - 2010)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4731]
### DB Selector

DB3K

### User(s)

Kenya,  Cameroon and Chinese Z-9WA. Army 

### Weapons Carried

57mm Rockets (BAI/CAS) - 19 x 57mm Rocket 1 x 23mm Gun pod. As X link below. 
23mm gun Pod. (CAS) - 2 x 23mm Gun pods* rarer and less useful except for slow mover aircraft interception or counter UAS/OWA.

Weapon #3778 - 23mm Type 23-3 Gun Pod Burst [40 rnds]? 

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

30nm at 180 minutes per loadout 22124

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

#4337 - Z-9WE Haitun (Kenya - 2011)  Has option for fixed forward firing 23mm pylon mounted gun. 
These almost certainly will as well. 
#4395 - Z-9WE Haitun (Cameroon - 2015)
#3307 - Z-9WA Haitun (China - 2010)

### Sources

https://x.com/HammerOfWar5/status/1810729571274178620

**Comment by PygmalionOfCyprus** [comment]
Brought the export loadouts in line w/ the improved loadouts implemented in 508/509.
