### ISSUE TITLE
Copy Aircraft #1304 - AS.550 Fennec (UAE - 2008) for Aircraft AS.550C3 Fennec (Kenya - 2018) Armed light recon Hydra and miniguns. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4732]
### DB Selector

DB3K

### DBID to Copy

Aircraft #1304 - AS.550 Fennec (UAE - 2008)

### Hypothetical

No

### Name

Aircraft AS.550C3 Fennec (Kenya - 2018) Armed light recon

### Country

Kenya (and create Armed UAE variant.?)

### Service

Air Force

### In Commission

2018

### Number in Service

8

### Sensors

None seen. Generic optical gun sight?

### Mounts

Nil

### Loadout Options

- HYDRA 70mm Rockets (Strike, Land/Naval) 14x HYDRA 70mm Rocket
- HYDRA 70mm Rockets (Strike, Land/Naval) 7x HYDRA 70mm Rocket 1 x Weapon #1807 - 7.62mm Minigun Burst [100 rnds]
- Battlefield Surveillance (Unarmed Recon)
- M134 7.62mm Minigun (Strike, Land/Naval) 16x 7.62mm Minigun Burst [100 rnds]
 

### Other Changes

As these were apparently donated by UAE the modified armed recon variant could be copied over as UAE Army armed recon variant?

### Sources

https://www.military.africa/2018/10/kenyan-air-force-acquires-h125-ecureuil-and-an-as550c3-fennec-h125m-from-airbus-helicopter/

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
