### ISSUE TITLE
Update: Improving the weapons known as CH-AS-X-13 and YJ-21

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4733]
- CH-AS-X-13, aka KF-21 etc.

1. Add land targets as valid targets. - _Plausible and illustrated in a propaganda video. [^1] _ - May apply to DF-21D as a conforming amendment. 

2. Change sensor arc to 90-120 - _Mechanical scanned array_[^2].  -May apply along with #4485 to DF-21D as a conforming amendment. 

3. Do not use cruise altitude if possible. 

- YJ-21, aka 2PZD-21 (referring to its unitary propulsive warhead or for VLS, second stage). 

In general, the VLS variant has a booster and a unitary, propulsive warhead. The air launched variant has only the second stage of the former. It is unclear about the effect as to its range, but with a 600mm, ~5m+ booster I would expect it to push the second stage well above the speed and alt of H-6. [^3]

Without knowing whether the game could handle propulsive RV/HGV or release a propulsive second stage from a weapon, I propose two weapon records for YJ-21: 
For air launched variant, use a unitary weapon. 
For VLS variant, use a separating weapon, with the separation mirroring second stage burnout, and the RV should have the same dimensions and weight of an empty air launched variant. 
_But if its feasible sim side:_
For air launched variant, use a unitary weapon. 
For VLS variant, use a separating weapon, with the warhead the second stage as the warhead, thus the air launched variant is the warhead for VLS variant. 

For both of these weapons
1. Add land targets as valid targets. 
2. Change sensor arc to 90-120 - _Mechanical scanned array_.
3. Do not use cruise altitude if possible. 

[^1]: https://www.youtube.com/watch?v=OBOho1AOKYY
[^2]: Shared by Chinese ASBMs, see the cutaway of CM-401. 
[^3]: https://www.twz.com/air/chinas-h-6k-bomber-seen-firing-air-launched-ballistic-missile-for-first-time; https://www.twz.com/this-is-our-best-look-yet-at-chinas-air-launched-carrier-killer-missile; https://crsreports.congress.gov/product/pdf/RL/RL33153/277, at p. 40

**Comment by HunterDNiu** [comment]
@claudejdev @LuigiP57

**Comment by LuigiP57** [comment]
For the A-L YJ-21/2PZD-21, I did consider adding an entry earlier, but I didn't think it would matter if we used the existing entry, as it would achieve the same effect. I must point out that although the VLS version has a long booster, the A-L version has almost the same length as the VLS version, so their performance could be viewed equally.

For the seeker, I think it is perfectly possible to expand its detection angle to 90-135°. Because, in order to achieve a wider detection range and their sufficient internal space, its seeker, at the most conservative estimate, is entirely possible to scan left and right to get a wide enough detection angle.

Regarding cruising altitude, it seems that the performance of the RV/HGV has nothing to do with this feature, so we should be able to just ignore it. : )

**Comment by LuigiP57** [comment]
#4206 In fact, the DB team has already responded to my request and changed the YJ-21/2PZD-21 back to the HGV category

**Comment by HunterDNiu** [comment]
> For the A-L YJ-21/2PZD-21, I did consider adding an entry earlier, but I didn't think it would matter if we used the existing entry, as it would achieve the same effect. I must point out that although the VLS version has a long booster, the A-L version has almost the same length as the VLS version, so their performance could be viewed equally.
> 
> For the seeker, I think it is perfectly possible to expand its detection angle to 90-135°. Because, in order to achieve a wider detection range and their sufficient internal space, its seeker, at the most conservative estimate, is entirely possible to scan left and right to get a wide enough detection angle.
> 
> Regarding cruising altitude, it seems that the performance of the RV/HGV has nothing to do with this feature, so we should be able to just ignore it. : )

I'm not sure about its length: the air launched variant is about 600mm in diameter at its aft.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107474489/6787bebf-8340-4928-85a2-e6be558b85be)
And as to KD-21, the current range is fine with it being launched at a higher altitude and allegedly using lighter materials

**Comment by LuigiP57** [comment]
In fact, you must have seen some claims that the CH-AS-X-13 is also a bypyramid HGV (similar to LRHW) based on the YJ-21. how about we change its type to HGV, by the way?

**Comment by LuigiP57** [comment]
> > For the A-L YJ-21/2PZD-21, I did consider adding an entry earlier, but I didn't think it would matter if we used the existing entry, as it would achieve the same effect. I must point out that although the VLS version has a long booster, the A-L version has almost the same length as the VLS version, so their performance could be viewed equally.
> > For the seeker, I think it is perfectly possible to expand its detection angle to 90-135°. Because, in order to achieve a wider detection range and their sufficient internal space, its seeker, at the most conservative estimate, is entirely possible to scan left and right to get a wide enough detection angle.
> > Regarding cruising altitude, it seems that the performance of the RV/HGV has nothing to do with this feature, so we should be able to just ignore it. : )
> 
> I'm not sure about its length: the air launched variant is about 600mm in diameter at its aft. ![image](https://private-user-images.githubusercontent.com/107474489/347796490-6787bebf-8340-4928-85a2-e6be558b85be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTcxNjcsIm5iZiI6MTcyMDY5Njg2NywicGF0aCI6Ii8xMDc0NzQ0ODkvMzQ3Nzk2NDkwLTY3ODdiZWJmLTgzNDAtNDkyOC04NWEyLWU2YmU1NThiODViZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMTIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTA0ZjQ3NDViNDkxZjY4ZThjMDdlZmVkZmU2Mzg4ODlhYzA3MjIxMTlmYTQxNTk5ZGQ2NzFhMzllZmJhOTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VaoCYHPYBBKOOwjRCmg_VwtKTMKqngBd-keMl_x5wAk) And as to KD-21, the current range is fine with it being launched at a higher altitude and allegedly using lighter materials

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/c3625b28-fbfc-4478-b7c5-e4ed31651ed4)
We can just take a look at Kinzhal

**Comment by LuigiP57** [comment]
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/a4acacb2-acb3-4ddf-bd35-1cc6f91aae04)
No, DF-12 will be suitable

**Comment by LuigiP57** [comment]
Iskander is similar to the DF-12, but their air-launched variants (Kh-47M2 and 2PZD-21) both offer a significant increase in range, except that the MIG-31K offers a better launch condition and thus a range of up to 2,000 km. Both of them have HGV glide range extension capability.

**Comment by LuigiP57** [comment]
Oh and, never try to measure an accurate value with your naked eyes. : )

**Comment by HunterDNiu** [comment]
I'm more leaning towards CH-AS-X-13 as HGV possible given the only view we have is bottom up. But YJ-21 is at best an ASBM. ANd I suppose its not ripe before it has any service history then.

**Comment by LuigiP57** [comment]
> I'm more leaning towards CH-AS-X-13 as HGV possible given the only view we have is bottom up. But YJ-21 is at best an ASBM. ANd I suppose its not ripe before it has any service history then.

Bypyramid HGV can refer to the North Korean toys I mentioned in update YJ-21 ticket. And yes, I really don't want to see YJ-21 have a "combat service history" , for reasons...... Please don't destroy the world, two Superpowers......

**Comment by LuigiP57** [comment]
You remind me of one thing: we need an HGV version of CH-AS-X-13/KF-21
