### ISSUE TITLE
China, PLAAF, KF-21, CH-AS-X-13 Variant/Improved version

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4734]
### DB Selector

DB3K

### Baseline

weapon 3564 3565

### Hypothetical

No

### Name

KF-21 [CH-AS-X-13 with HGV]

### Length (m)

same as CH-AS-X-13

### Width/Span (m)

same as CH-AS-X-13

### Diameter (m)

same as CH-AS-X-13

### Weight (kg)

same as CH-AS-X-13

### Range (nm)

100-3780 (HGV extended range; similar to DF-27 with two-stage but Air-Launched extended range)

### Warhead

same as CH-AS-X-13

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

2

### Sensors

same as CH-AS-X-13

### Weapon Codes

Home On Jam (HOJ), Weapon - INS w/ GNSS Navigation, Terminal Maneuver - Random (Advanced), Attitude Control - Aerodynamic Only, Uses BeiDou/COMPASS, Level Cruise Flight

### Comments

Multiple sources and visual observations indicate that there is an HGV variant of the CH-AS-X-13 aka KF-21.

Carrier :  **Aircraft 4837 4969**

### Sources

https://www.iiss.org/online-analysis/online-analysis/2020/10/mdi-chinese-plaaf-h-6n-missile/

> The imagery suggest that the weapon may have small fins toward the rear of the nose section, perhaps indicative of a manoeuvring re-entry vehicle, or that it is possibly related to the DF-17 hypersonic boost-glide system. The underside of the front section may be flattened, a characteristic of a glide body.

https://en.wikipedia.org/wiki/DF-21#KF-21
https://www.twz.com/this-is-our-best-look-yet-at-chinas-air-launched-carrier-killer-missile
https://www.navalnews.com/naval-news/2020/11/chinas-new-aircraft-carrier-killer-is-worlds-largest-air-launched-missile/

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
