### ISSUE TITLE
French KC-135s purcahsed by Metrea (Formerly Meta Aerospace)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4737]
### DB Selector

DB3K

### DBID to Copy

DB3K IDs 3950 and 3951

### Hypothetical

No

### Name

C-135FR Stratotanker [KC-135FR] and KC-135RG Stratotanker

### Country

Commercial

### Service

Metrea (Formerly Meta Aerospace) see DBID 6198

### In Commission

2024-

### Number in Service

11x KC-135FR and 3x KC-135RG

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.twz.com/air/all-of-frances-kc-135-tankers-bought-by-private-aerial-refueling-company-metrea?fbclid=IwZXh0bgNhZW0CMTEAAR0HuQqvX_3NHxxkPCi0YtAqezDHNaRa6_MaGJHw6TOnsDXaSO_ug62j9l4_aem_0RE7QG4gpKHLlR_u7_3lkg

KC-135FR
![image](https://github.com/user-attachments/assets/f474e5f7-9e55-46b6-a369-28c70989710c)

KC-135RG
![image](https://github.com/user-attachments/assets/4750bac1-bea2-491f-8b29-26a53e14ae3c)

**Comment by PygmalionOfCyprus** [comment]
This capability is already modelled via 6198, the fact that they're French doesn't make them not KC-135Rs.

**Comment by tbrandon517** [comment]
> This capability is already modelled via 6198, the fact that they're French doesn't make them not KC-135Rs.

@PygmalionOfCyprus That's perfectly fair. Perhaps update the note for 6198 that says 4x units to reflect the updated fleet could just be 18x for the total fleet rather than 4x ex-Singpore, 14x ex-French.
