### ISSUE TITLE
Add Indian UH-3H Sea King

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4738]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4711

### Hypothetical

No

### Name

UH-3H Sea King

### Country

India

### Service

Navy

### In Commission

2009-2024

### Number in Service

6x

### Sources

https://www.scramble.nl/military-news/indian-navy-bids-farewell-to-uh-3h-sea-king

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
