### ISSUE TITLE
China, KJ-600 AESA Radar, Band modification

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4739]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 7122

### Summary of Changes

Modify current Sensor 7122 operating band from D to **B (UHF, IEEE)**. If we compare the radar of the E-2C/D to the KLC-7 and KJ-600, it is not difficult to find that the APS-145 and APY-9 are much closer to the radar of the KJ-600. For PLAN that need to defend against LRASM threats, lower frequency radar is a higher priority.

### Sources

https://thediplomat.com/2023/07/kj-600-the-eye-in-the-sky-for-chinas-future-carriers/
https://www.radartutorial.eu/19.kartei/08.airborne/pubs/APS-145-Brochure.pdf
https://www.flightglobal.com/cutaway-technical-description-e-2d-may-not-look-pretty-but-packs-big-new-bunch/94599.article
![image](https://github.com/user-attachments/assets/3efb8870-b9dd-4b5a-b25c-132055144ecf)
https://defenceforumindia.com/threads/e-2d-advanced-hawkeye-us-navys-already-operational-anti-stealth-aew-aircraft.80186/
![image](https://github.com/user-attachments/assets/7dc7b04e-d89e-4fdb-bb42-fac1cac45f81)

This radar certainly does not look like a KLC-7
![image](https://github.com/user-attachments/assets/ede28144-b0d2-4145-bb45-099a42e93f28)
Credit: Google Earth, The War Zone
![image](https://github.com/user-attachments/assets/3dcd9fd5-45c9-4987-9b29-f519e4a3a748)
Credit: Sina Weibo, The Diplomat https://thediplomat.com/2023/07/kj-600-the-eye-in-the-sky-for-chinas-future-carriers/
![image](https://github.com/user-attachments/assets/7a42dc83-1789-4a7b-b664-941b264731b1)
KLC-7

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Put it to C-band as per The Diplomat (Command has C-band as UHF, B-band is VHF). This matches APY-9.

**Comment by LuigiP57** [comment]
> Handled 508. Put it to C-band as per The Diplomat (Command has C-band as UHF, B-band is VHF). This matches APY-9.

I must admit that up until this point, I had been having some misunderstandings about the division of radar bands in Command.

**Comment by PygmalionOfCyprus** [comment]
Yeah, I have no idea why they are the way they are. As with a lot of weird legacy things they might be inherited from Harpoon.

This is what the DB has:
![image](https://github.com/user-attachments/assets/0f5e27e6-825e-4598-9ddd-aecde5263bee)
