### ISSUE TITLE
SSM Bn (SS-21b Scarab [9K79-1 Tochka-U] TEL)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#474]
### DB Selector

DB3K

### DBID to Copy

facility/840/DB3K and facility/627/DB3K

### Hypothetical

No

### Name

SSM Bn (SS-21b Scarab [9K79-1 Tochka-U] TEL)

### Country

Armenia, Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

None Known

### Mounts

None Known

### Loadout Options

None Known

### Other Changes

None Known

### Sources

https://en.wikipedia.org/wiki/OTR-21_Tochka#Operators
https://www.thedrive.com/the-war-zone/37518/video-indicates-armenia-has-fired-its-russian-made-iskander-ballistic-missiles-at-azerbaijan
https://www.thedrive.com/the-war-zone/36777/everything-we-know-about-the-fighting-that-has-erupted-between-armenia-and-azerbaijan
https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
