### ISSUE TITLE
Aster 30 Block 1NT upgrades (SAMP/T MAMBA)

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4740]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3774

### Summary of Changes

-Increase maximum missile speed to mach 4.5 (3000kts)
-Add CRAM capability to the missile

![aster 4](https://github.com/user-attachments/assets/029c8a23-6b4a-4354-aa1c-9fef3d729126)
![aster 2](https://github.com/user-attachments/assets/78ea1d56-b1ef-4b4c-a565-a3737a308076)
![aster 1](https://github.com/user-attachments/assets/109385f6-f8c7-4259-a4df-45a67a907ce5)
![aster 3](https://github.com/user-attachments/assets/a8b34cbc-b1a9-4dd0-8726-1f1e20802173)

### Sources

https://www.mbda-systems.com/product/aster-30-sampt/
https://www.thalesgroup.com/en/ground-fire
https://www.thalesgroup.com/sites/default/files/database/document/2024-06/Ground%20Fire%20Datasheet.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 508. I don't think the Aster 30 is actually intended for CRAM. It'd be pretty overkill. That's just a capability of the GM radar.
