### ISSUE TITLE
Aircraft Loadout Su-34 SU-34M "SVO" UMPK FAB-3000 M54 2024

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4741]
### DB Selector

DB3K

### User(s)

Russia VKS Su-34 post 2024

### Weapons Carried

1 x FAB-3000 M54 UMPK
2 x FAB-250 UMPK

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As extant UMPK loads

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Centre line FAB-3000 and two FAB-250 or FAB-500 on wings. All UMPK Glide kit fitted.
Haven't measured the images to confirm validity of smaller bombs but centre line looks like the 3000.

### Sources

https://x.com/GuyPlopsky/status/1812421974502801532?t=C12Y8BK8kpcTL0B0l-Zh4w&s=19

From VKS via Russian telegram channel.

**Comment by bostonmyk** [comment]
https://x.com/MrFrantarelli/status/1812543730530091051

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
