### ISSUE TITLE
ADD JMSDF SH-60L(improved SH-60K)

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4743]
### DB Selector

DB3K

### Baseline

5935

### Hypothetical

No

### Name

Mitsubishi SH-60L

### Country

JAPAN

### Service

JMSDF

### In Commission

2024

### Number in Service

2

### Length (m)

19.8

### Wingspan (m)

16.4

### Height (m)

5.4

### Empty Weight (kg)

6190

### Maximum Takeoff Weight (MTOW) (kg)

10900

### Payload Weight (kg)

3031

### Crew

4

### Propulsion

T700-IHI-401C2

### Rate of Climb (ft/min)

1480

### Service Ceiling (ft)

18000

### Military/Afterburner Speed (kt)

140

### Cruise Speed (kt)

120

### Supercruise

No

### Ferry Range (nm)

600

### Endurance (min)

175 with long-range

### Takeoff / Landing Distance (m)

0

### Fuel Capacity (kg)

3031

### Sensors

AIS
FLIR
The others are the same as SH-60K

### Mounts

1/2×MK.46
1/2×TYPE 97
1/2×TYPE 12
2AGM-114M

### Loadout Options

MK.46
TYPE 97
TYPE 12
AGM-114M

### Aircraft Codes

Night Navigation/Attack (Incl. Bomb, Rocket Delivery)

### Sources

https://ja.wikipedia.org/wiki/SH-60L_%28%E8%88%AA%E7%A9%BA%E6%A9%9F%29?wprov=sfla1

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
