### ISSUE TITLE
JMSDF TYPE 23 ASM

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4744]
### DB Selector

DB3K

### Baseline

1192

### Hypothetical

No

### Name

TYPE 23 ASM

### Length (m)

May be similar to SSM-2

### Width/Span (m)

May be similar to SSM-2

### Diameter (m)

May be similar to SSM-2

### Weight (kg)

May be similar to SSM-2

### Range (nm)

2-215

### Target Altitude / Depth (ft)

Unknown

### Target Speed (kts)

600

### Launch Altitude / Depth (ft)

Unknown

### LaunchSpeed (kts)

Unknown

### Warhead

The same as SSM-2?

### Targets

Surface Vessel

### CEP (m)

Unknown

### Sensors

May be similar to SSM-2

### Weapon Codes

Uses GPS

### Comments

preceded by ASM-1C(TYPE 91),will service in JMSDF'S P-3C and P-1.

### Sources

05_zuikei_kijunijo-03.xlsx (live.com) *982 *1110
https://ja.wikipedia.org/wiki/91%E5%BC%8F%E7%A9%BA%E5%AF%BE%E8%89%A6%E8%AA%98%E5%B0%8E%E5%BC%BE?wprov=sfla1

**Comment by Huacangzi** [comment]
#3792 and #728 is the DB3K's DBID.

**Comment by PygmalionOfCyprus** [comment]
Both the ASM-2 (Type 93) and ASM-2B (Type 93B) are in the database, weapons 764 and 4468 respectively.

Are you referring to the new ASM/SSM derived from the Type 12?

**Comment by Huacangzi** [comment]
> Both the ASM-2 (Type 93) and ASM-2B (Type 93B) are in the database, weapons 764 and 4468 respectively.
> 
> Are you referring to the new ASM/SSM derived from the Type 12?

No,I am referring to the new ASM derived from the Type 17(SSM-2)for JMSDF's MPA,it seems now have an formal name of TYPE 23 ASM.
Sources:https://warp.da.ndl.go.jp/info:ndljp/pid/10249266/www.mod.go.jp/j/approach/hyouka/seisaku/results/28/pdf/jizen_02_honbun.pdf
https://www.mod.go.jp/atla/souhon/supply/jisseki/rakusatu/kohyo_r05/05_zuikei_kijunijo-03.xlsx  in *982 *1110

**Comment by PygmalionOfCyprus** [comment]
Not sure where you're seeing the Type 17 lineage? The MOD PDF seems pretty clear that the new ASM you refer to is basically the air-launched version of the new SSM [indicated in this image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/The_development_of_Japanese_anti-ship_missiles.svg/1920px-The_development_of_Japanese_anti-ship_missiles.svg.png), and both are derived from the Type 12:

>また、同一の類似誘導弾を活用することを念頭にする１２式地対艦誘導弾（改）と哨戒機用新空対艦誘導弾の二つの事業を一本化することにより、開発時に双方で想定し得る技術的リスク等に対して個別に対応するのではなく、一元的に進捗管理することを念頭にしており、リスク管理上の効率化が図られている。

**Comment by tbrandon517** [comment]
English wiki pages linked to the Japanese indicate Type 17 is the ship based version of the ground based Type 12. Seems tomato tomato really.

**Comment by PygmalionOfCyprus** [comment]
Yep, I'm a fucking idiot. Talk about missing the forest for the trees.

Handled 508.

**Comment by Huacangzi** [comment]
> Not sure where you're seeing the Type 17 lineage? The MOD PDF seems pretty clear that the new ASM you refer to is basically the air-launched version of the new SSM [indicated in this image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/The_development_of_Japanese_anti-ship_missiles.svg/1920px-The_development_of_Japanese_anti-ship_missiles.svg.png), and both are derived from the Type 12:
> 
> > また、同一の類似誘導弾を活用することを念頭にする１２式地対艦誘導弾（改）と哨戒機用新空対艦誘導弾の二つの事業を一本化することにより、開発時に双方で想定し得る技術的リスク等に対して個別に対応するのではなく、一元的に進捗管理することを念頭にしており、リスク管理上の効率化が図られている。

その実施に当たっては、これ
までに国内開発している異なる運用要求を満足する類似誘導弾（新艦対艦誘導弾）等の試
作成果及び技術的知見を最大限活用することを念頭に、構成品を共通化する計画となって
いことから、技術面及び経費面において効率化が図られている。
I am sorry,forgot to mention it,in that moment the TYPE 17 had not got it's formal name,it has been called "新艦対艦誘導弾".

**Comment by tbrandon517** [comment]
> Yep, I'm a fucking idiot. Talk about missing the forest for the trees.
> 
> Handled 508.

Everyone can use another pair of eyes sometimes
