### ISSUE TITLE
ADD JMSDF SS-516 Raigei Submarine

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4745]
### DB Selector

DB3K

### Baseline

DBID #703

### Hypothetical

No

### Name

SS 516 Raigei[Taigei Class]

### Class

Taigei Class

### Country

JAPAN

### Service

JMSDF

### In Commission

2025

### Number in Service

1

### Length (m)

84

### Beam (m)

9.1

### Draft (m)

8.5

### Standard Displacement (t)

3000

### Submerged Displacement (t)

4200

### Empty Displacement (t)

Unknown

### Max Depth (m)

Unknown

### Complement

The same as DBID#703?

### Primary Propulsion Type

Diesel/Electric

### Propulsion

2×Kawasaki 12V 25/31 Diesels

### Flank Speed at Surface (kt)

Unknown

### Flank Speed Submerged (kt)

Unknown

### Range (nm) at Speed (kt)

Unknown

### Sensors

The same as DBID#703

### Mounts

The same as DBID #703

### Magazines

The same as DBID#703

### Comms/Datalinks

The same as DBID #703

### Comments

2×Kawasaki 12V 25/31 Diesels Upgrade

### Sources

https://ja.wikipedia.org/wiki/%E3%82%89%E3%81%84%E3%81%92%E3%81%84_%28%E6%BD%9C%E6%B0%B4%E8%89%A6%29?wprov=sfla1
https://ja.wikipedia.org/wiki/%E3%81%9F%E3%81%84%E3%81%92%E3%81%84%E5%9E%8B%E6%BD%9C%E6%B0%B4%E8%89%A6?wprov=sfla1
https://jm2040.blogspot.com/2021/07/02ss.html

**Comment by PygmalionOfCyprus** [comment]
Handled 508.

For future reference you can use a Copy entry for things like this that are based heavily on existing entries.
