### ISSUE TITLE
Mark 13 Torpedo Loadout for PV-1 and PV-2

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4746]
### DB Selector

CWDB

### User(s)

Aircraft 2492, 2493, 2494

### Weapons Carried

1x Mark 13 Torpedo (weapon 655)
2x 150 USG Drop Tanks (long range)
8x ZUNI 127mm FFAR (weapon 413, Optional)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

600 nm short range, 950nm long range

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

http://www.microworks.net/pacific/aviation/pv_ventura.htm
https://www.history.navy.mil/content/history/nhhc/our-collections/photography/numerical-list-of-images/nhhc-series/nh-series/80-G-322000/80-G-322696.html
https://www.reddit.com/r/WWIIplanes/comments/xjzsxm/mark_xiii_torpedo_with_wooden_drag_ring_being/?share_id=E6-ZrbrwphNPNI3m5_cAo&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=10
https://www.history.navy.mil/content/history/nhhc/our-collections/photography/numerical-list-of-images/nara-series/80-g/80-G-350000/80-G-356150.html

![image](https://github.com/user-attachments/assets/baaab597-6cd8-4189-92af-aaff3764f1eb)

![image](https://github.com/user-attachments/assets/9b6b9921-9413-4812-8abc-bc08db84307c)

Lockheed PV-2 Harpoon is loaded with a torpedo at an Aleutians base for a strike on Japanese shipping and facilities in the Kirils, 7 April 1945.
https://www.history.navy.mil/content/history/nhhc/our-collections/photography/numerical-list-of-images/nhhc-series/nh-series/80-G-322000/80-G-322696/_jcr_content/mediaitem/image.img.jpg/1457052037132.jpg

Lockheed PV-1 Ventura patrol plane Dropping a Mark XIII torpedo over Saratoga Strait, Washington, 4 June 1943.
https://www.history.navy.mil/content/history/nhhc/our-collections/photography/numerical-list-of-images/nara-series/80-g/80-G-350000/80-G-356150/_jcr_content/mediaitem/image.img.jpg/1439265036057.jpg

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
