### ISSUE TITLE
Update AH-64AS Sea Apache - 1990

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4747]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4908

### Summary of Changes

Update AIM-9 variant carried from old AIM-9B to AIM-9M to match actual period USMC AH-1Ws such as aircraft 1220.

### Sources

https://cmano-db.com/aircraft/4908/
https://cmano-db.com/aircraft/1220/

https://images.app.goo.gl/v6wdmvcPyHvzjDuf8
https://images.app.goo.gl/aUTYoCjc2o1BTHm16

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
