### ISSUE TITLE
Copy Aircraft NH90 TTH SF Standard 2 [Caiman] - 2024 , 18x France

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4748]
### DB Selector

DB3K

### DBID to Copy

NH90 TTH [Caiman] - 2014, 34x France

### Hypothetical

No

### Name

NH90 TTH SF [Caiman] - 2024 x18  France CSAR/SF

### Country

France

### Service

Air Force 

### In Commission

2024

### Number in Service

18 ordered

### Sensors

Upgraded cockpit
Safran EurofEye distributed aperture EOTS MAW
Euroflir 410
NVG
HMD

### Mounts

Enlarged rear sliding windows for M3 HMG? FN GPMG? Port and Starboard. 

### Loadout Options

As TTH
Plus CSAR SAR
Special Forces x8

### Other Changes

Has third crew member.

*The article referenced below also states Italian Navy NH90 are getting Link22 Comms a new LEOSS-T electro optical system, new sonar (not specified) and trialling Mk54 torpedoes and the MARTE-ER ASM.

### Sources

Flight International July 2024 pp12
Dominic Perry
"Four Nation Deal to Enhance NH90"

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Also added the new version for Italy. Looks like FI is referring to the SWR3 release: https://www.navalnews.com/naval-news/2024/06/nh90-comprehensive-upgrade-programme-launched/

Mk54s are weird, I can't find any indication that Italy was/is using them.

**Comment by KLABDB3K** [comment]
Yes wondered about Mk54, possible it's being trialled using Italian airframe for potential export or foreign user not for Italy itself?

**Comment by PygmalionOfCyprus** [comment]
That would make sense, a few NATO allies use the Mk54 and it could be for their sake.
