### ISSUE TITLE
Armored Plt (T-72 MBT)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#475]
### DB Selector

DB3K

### DBID to Copy

DB3K facility ID's 499,1923

### Hypothetical

No

### Name

Armored Plt (T-72 MBT)

### Country

Armenia, Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
