### ISSUE TITLE
China, YJ-21, launch altitude problem

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4750]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4058 4059

### Summary of Changes

A long unsolved problem is that the YJ-21 cannot be launched underwater, and in fact we have some solid OSINT to prove it.

Recommended launch altitude: -197ft ~ 65000ft

### Sources

![image](https://github.com/user-attachments/assets/e3a9be54-ebc1-4d0a-9f80-09f9525ae076)
Single Submarine VLS tube with YJ-21
https://www.sinodefenceforum.com/t/09iii-09iv-093-094-nuclear-submarine-thread.6883/page-344
![image](https://github.com/user-attachments/assets/7e982163-473a-474b-90fa-8a69d718a73c)

**Comment by LuigiP57** [comment]
In addition, it should be noted that according to OSINT collection and analysis on SDF, the VLS module used by type 095 is likely to be something similar to VPM. 

Moreover, the device appears to be able to be mounted side-by-side (unlike the VPM mounted in the center on the Virginia blkV), possibly suggesting that the submarine will be large in diameter (8/12 such modules are expected to be installed).

The single VLS tube YJ-21 is considered likely to be installed on 093B (Later, I may propose a overall upgrade ticket for 093B entry in DB, because, according to the known OSINT at present, the reality will be very different from the performance in DB).

https://www.sinodefenceforum.com/t/09v-09vi-095-096-nuclear-submarine-thread.8228/page-130
![image](https://github.com/user-attachments/assets/b2b3e190-c1de-4fc3-ac7f-d5ac686e7a5d)
![image](https://github.com/user-attachments/assets/e2d24e94-8fc7-429b-8204-1b1d4400cd6e)
https://twitter.com/tshugart3/status/1810412652591775810?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1810412652591775810%7Ctwgr%5Ea993500967ffc892df1c4962113df47485964b12%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.sinodefenceforum.com%2Ft%2F09iii-09iv-093-094-nuclear-submarine-thread.6883%2Fpage-353
![image](https://github.com/user-attachments/assets/00299cc4-63fe-4f9b-8144-bd1374ad3f5c)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.

Feel free to submit that 093B ticket, anything wrong with "finished" review items is hi-pri for us.
