### ISSUE TITLE
CWDB Ship 2428 Nagato has no mounts

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4754]
### DB Selector

CWDB

### Affected DBID(s)

Ship 2428

### Summary of Changes

Copy mounts from Ship 2439 and modify as required

4x2 410mm/45 3rd Year Type Cannons,
12x1 140mm/50 3rd Year Type Guns,
6x2 127mm/40 Type 89 DP-AA Guns,
25x3,10x2,24x1 25mm/60 Type 96 AA Guns

![image](https://github.com/user-attachments/assets/d919b83b-b23c-47b0-9c38-92fa58985873)

### Sources

https://en.wikipedia.org/wiki/Japanese_battleship_Nagato
https://naval-encyclopedia.com/ww2/japan/nagato-class-battleships.php
https://www.secretprojects.co.uk/threads/the-development-of-the-nagato-class-battleships.38384/

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Random poorly made WW2 entries in CWDB are my DB nemesis.

**Comment by tbrandon517** [comment]
> Handled 508. Random poorly made WW2 entries in CWDB are my DB nemesis.

I've been watching lectures on inter-war and WWII era naval construction as you probably guessed.
