### ISSUE TITLE
ADD JGSDF (SAM-4 Chu-SAM Kai[Type 03 Kai]) Enhanced Capacity

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4756]
### DB Selector

DB3K

### Affected DBID(s)

Facility DBID3661

### Summary of Changes

Now it seems have 3 Magazines.

### Sources

https://www.mod.go.jp/atla/soubiseisaku/project/gaiyo_r050831.pdf In page 3.

![Screenshot_2024-07-18-08-36-53-492_cn wps moffice_eng-edit](https://github.com/user-attachments/assets/cdc998b9-9d08-449d-b22d-a3921e432136)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
