### ISSUE TITLE
Su-25 Frogfoot A

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#476]
### DB Selector

DB3K

### DBID to Copy

DB3K Aircraft ID's 2378,4265,4262

### Hypothetical

No

### Name

Su-25 Frogfoot A - 1992

### Country

Armenia, Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

None Known

### Mounts

None Known

### Loadout Options

None Known

### Other Changes

None Known

### Sources

https://www.oryxspioenkop.com/2022/01/knights-of-yerevan-armenias-su-30sm.html?m=1&fbclid=IwAR2MV6ynh8bniYCajh0FX7BU6OY7CUc35yORdnx4KjSafiezImRPbuFGJKk
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_Sukhoi_Su-25_operators#Current_operators

**Comment by PygmalionOfCyprus** [comment]
Added 494.
