### ISSUE TITLE
Add JMSDF A-SAM(Type 24?)

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4761]
### DB Selector

DB3K

### Baseline

Weapon ID 4138 and 4096

### Hypothetical

No

### Name

A-SAM(Type 24?)

### Length (m)

Unknown

### Width/Span (m)

Unknown

### Diameter (m)

Unknown

### Weight (kg)

Unknown

### Range (nm)

Unknown

### Target Altitude / Depth (ft)

Unknown

### Target Speed (kts)

Unknown

### Launch Altitude / Depth (ft)

0

### LaunchSpeed (kts)

Unknown

### Warhead

As Weapon ID 4138?

### Targets

Aircraft, Helicopter, Missile

### CEP (m)

none

### Sensors

As Weapon ID 4138?

### Comments

It combined the technology of SAM-4 Kai and Type 07 VL-ASROC,have an longer range than SAM-4 kai,will be use in JMSDF.

### Sources

https://ja.wikipedia.org/wiki/03%E5%BC%8F%E4%B8%AD%E8%B7%9D%E9%9B%A2%E5%9C%B0%E5%AF%BE%E7%A9%BA%E8%AA%98%E5%B0%8E%E5%BC%BE?wprov=sfla1
https://warp.da.ndl.go.jp/info:ndljp/pid/11591426/www.mod.go.jp/j/approach/hyouka/seisaku/28/pdf/jizen_01_honbun.pdf
https://www.mod.go.jp/j/budget/yosan_gaiyo/2024/yosan_20240328.pdf In page 27 新艦対空誘導弾

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
