### ISSUE TITLE
DB's mistake of JMSDF FFM 13(NEW FFM)

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4763]
### DB Selector

DB3K

### Affected DBID(s)

Ship DBID 4477

### Summary of Changes

The radar's degree of NEW FFM is 45⁰ and 135⁰,not 90⁰ as Mogami Class.
The numbers of VLS is 32,not 16,and the VLS will equipped with (A-SAM)issues#4761,not ESSM,there is no sources seems it will equipped with ESSM.

### Sources

https://ja.wikipedia.org/wiki/%E6%96%B0%E5%9E%8BFFM?wprov=sfla1

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
