### ISSUE TITLE
DB's mistake of JMSDF Mogami Class

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4764]
### DB Selector

DB3K

### Affected DBID(s)

Ship DBID 3292/3293

### Summary of Changes

Until FFM-9,the Mogami Class FFM is still not equipped with 16 cells of VLS，and until now,Type 07 VL-ASROC is the only Weapon will equipped with Mogami Class's VLS.Right now there is no sources seems that Mogami Class will equipped with ESSM or A-SAM(issus #4761).

### Sources

https://ja.wikipedia.org/wiki/%E3%82%82%E3%81%8C%E3%81%BF%E5%9E%8B%E8%AD%B7%E8%A1%9B%E8%89%A6?wprov=sfla1

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
