### ISSUE TITLE
HQ-9B new target indicating radar, Type 780 radar

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4765]
### DB Selector

DB3K

### Baseline

Sensor 6954

### Hypothetical

No

### Name

Type 780 radar

### Sensor Generation

Early 2020s

### Range (nm)

0.8-300

### Sensor Capabilities

Air Search, Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Continuous Tracking Capability, Track While Scan (TWS), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA), Frequency Agile

### Search/Track Frequencies

D Band (1-2 GHz) [Old L Band] 15-30 cm

### Scan Interval (s)

3

### Target Altitude (ft)

990000

### Horizontal Beamwidth (deg)

1.5

### Vertical Beamwidth (deg)

1.5

### System Noise Level (dB)

2

### Processing Gain/Loss (dB)

-1.8

### Peak Power (W)

750000

### Pulse Width (μs)

1.2

### Blind Time (μs)

1.2

### PRF (Hz)

150

### Comments

The new radar, revealed at the Zhuhai Air Show, has been confirmed to work in the PLAAF's HQ-9B unit. According to the introduction, it is the fourth generation of air defense and anti-missile integrated multi-function phased array radar, which can carry out various aerodynamic target search, tracking and identification tasks.
![image](https://github.com/user-attachments/assets/8b5c649c-689e-45a2-bc28-95d429b9a69d)
![image](https://github.com/user-attachments/assets/e97b5835-2d30-4fc6-9013-3f1b9f6e09a0)

### Sources

https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/post-928676
https://x.com/jesusfroman/status/1608743345014329345

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
