### ISSUE TITLE
China,PLAAF,The newly integrated HQ-9B system

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4766]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Bn(HQ-9B)(China-2023)

### Facility Type

SAM

### Country

China

### Service

PLAAF

### In Commission

2023

### Number in Service

At least 1+

### Crew

100

### Dispersion Radius (m)

80

### Sensors

1x Mk1 Eyeball
2x China Type 347G [TR-47C, Radar Tracker]
2x Generic Target Indicator, 3D Surface-to-Air, Surface-to-Surface
2x OFC-3 [TV Camera]
2x OFC-3 [LLTV]
2x OFC-3 [IR]
2x OFC-3「Laser Rangefinder]
1x HT-233 [HQ-9A]
1x Type 780 radar
1x China YLC-2V [High Guard]

### Mounts

2x 30mm China LD-2000 [Type 730]
8x HQ-9B TEL(It is also compatible with the HQ-9BG)
1x Vehicle (China Type 780 radar [HQ-9])
1x Vehicle (China HT-233 [HQ-9])
1x Vehicle (China YLC- 2V)

### Magazines

32x HQ-9B
32x HQ-9BG

### Comments

The new HQ-9B air defense system is integrated with a new type of radar, and a new type of missile is integrated.
![image](https://github.com/user-attachments/assets/6c92e63f-3612-448f-b9c1-a467ec4f5cce)
![image](https://github.com/user-attachments/assets/8880ea9e-ede3-47af-befb-dbd3526543ae)
![image](https://github.com/user-attachments/assets/22222e90-e938-46a7-ba20-5c7d70b552e9)

### Sources

https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/post-928676
https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/page-93

**Comment by yU2187sie** [comment]
#4451 #4765

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
