### ISSUE TITLE
China,PLAAF,SLC-14 radar

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4767]
### DB Selector

DB3K

### Baseline

Sensor 6320

### Hypothetical

Yes

### Name

SLC-14

### Sensor Generation

Late 2010s

### Range (nm)

0.2-810

### Sensor Capabilities

Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Continuous Tracking Capability, Track While Scan (TWS), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA)

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Scan Interval (s)

10

### Target Altitude (ft)

3300000

### Horizontal Beamwidth (deg)

1

### Vertical Beamwidth (deg)

1

### System Noise Level (dB)

2.5

### Processing Gain/Loss (dB)

4.5

### Peak Power (W)

2000000

### Pulse Width (μs)

1.2

### Blind Time (μs)

1.2

### PRF (Hz)

85

### Comments

A radar on display mimics the TPY-2 radar as a subsystem of the Chinese version of THAAD. It hopes to draw on the advanced experience of the US military to complete the system.

### Sources

![image](https://github.com/user-attachments/assets/69f9b1d1-c42b-4796-b969-c7be9ec88e15)

**Comment by PygmalionOfCyprus** [comment]
Do we have any indication that this is actually in service? I can't find any mention of it anywhere. Even that picture you posted doesn't seem to be generating returns on reverse image search anymore. This feels like another mockup posted at some trade show that never got legs -- or if it is being developed, it's so far away from deployment as to be unripe.

**Comment by PygmalionOfCyprus** [comment]
Gonna close even though this is a hypothetical since I think China has other appropriate radars they could use in this role and appear to be developing more than this one. There's a million prospective radars that get models at trade shows and I don't wanna add all of them...

**Comment by Jkryos** [comment]
Added DB3K 510 with the public images of the HQ-19.
