### ISSUE TITLE
JMSDF Kongo Class don't equipped with SM-3ⅡA

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4768]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3047

### Summary of Changes

Don't have SM-3ⅡA

### Sources

https://www.mod.go.jp/j/policy/defense/bmd/index.html
![mmexport1721297052451](https://github.com/user-attachments/assets/835f3320-8e12-485c-8392-8a80a6a29628)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
