### ISSUE TITLE
PLAN Yu-11 ASROC(ET-81)[China Review related] 

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4769]
### DB Selector

DB3K

### Baseline

4310

### Hypothetical

No

### Name

Yu-11 ASROC

### Length (m)

6.4

### Width/Span (m)

1.8

### Diameter (m)

0.36

### Weight (kg)

800

### Range (nm)

0.5-54

### Target Altitude / Depth (ft)

-1969ft- -33ft，-600m- -10m

### Warhead

Yu-11 Torpedo payload

### Targets

Submarine

### Sensors

___

### Weapon Codes

Bearing-Only Launch (BOL), Weapon - INS Navigation

### Comments

Photos show that the missile uses a turbofan engine.
Its cruise attitude should be 30ft AGL.
It's launched by YJ-83 quads,not by H/AJK-16 VLS.

### Sources

![image](https://github.com/user-attachments/assets/b4ed8bc7-5cfa-4f3b-af6a-f0a8ce13e57d)
![image](https://github.com/user-attachments/assets/9c2543fe-7ed0-4b8a-bd18-e4746e78ac38)
![image](https://github.com/user-attachments/assets/ea23cff5-c807-4d88-8802-f2bd604e2425)

![image](https://github.com/user-attachments/assets/cd6c3771-0ead-4f2d-8631-82e6e04db7fa)
https://twitter.com/dafengcao/status/899834951884877825
https://twitter.com/dafengcao/status/959118142353031168
https://mx.pinterest.com/pin/david-wang-on-twitter--125045327147397158/

**Comment by LuigiP57** [comment]
You forget platforms: **Ship 2703 4596 4597 4720 4721 4722 (056A) 2459 2714 3568 4723 4724 4725 4582 (054a/p)**

And it's also a **China Review related** ticket, it's a hi-pri.

**Comment by PygmalionOfCyprus** [comment]
This is very interesting. The 056s always seemed under-armed for ASW considering their role.

My understanding is that the ET-series ASROCs were for export-only. Is it possible that the 056s/054As are wired to be able to use such weapons, but they are not actually deployed in PLAN service? I wish we had more info, I would love to know whether that CCTV report mentioned that the ASROC was in service or if it was just testing (could just be testing an export weapon).

**Comment by FRF311** [comment]
As we all know that only weapons which has already in PLA service will be shown in these CCTV 7 progammes like “Sharpening Soldiers”or"Sharpening Swords"and so on .Weapons which are only for export never appear. The relation between Yu-11 ASROC and ET-81 is just like that between Yu-8 ASROC and ET-80,and we know that Yu-8 ASROC has in PLA service for several years.

**Comment by FRF311** [comment]
As we all know that only weapons which has already in PLA service will be shown in these CCTV 7 progammes like “Sharpening Soldiers”or"Sharpening Swords"and so on .Weapons which are only for export never appear. The relation between Yu-11 ASROC and ET-81 is just like that between Yu-8 ASROC and ET-80,and we know that Yu-8 ASROC has in PLA service for several years.

**Comment by PygmalionOfCyprus** [comment]
Handled 508. The Type 056As have new YJ-83 mounts which are capable of firing both and loaded 50/50 (considering their ASW role). The 054As have mounts capable of firing both but remain loaded only w/ YJ-83s by default (of course can be adjusted in ScenEdit).
