### ISSUE TITLE
SSM Bn (SS-1 Scud B [9K72 Elbrus] TEL) (Conventional)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#477]
### DB Selector

DB3K

### DBID to Copy

facility/450/DB3K

### Hypothetical

No

### Name

SSM Bn (SS-1 Scud B [9K72 Elbrus] TEL) (Conventional)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.thedrive.com/the-war-zone/36777/everything-we-know-about-the-fighting-that-has-erupted-between-armenia-and-azerbaijan
https://www.hrw.org/news/2020/12/11/armenia-unlawful-rocket-missile-strikes-azerbaijan
https://en.wikipedia.org/wiki/2020_Ganja_missile_attacks
https://www.csis.org/analysis/air-and-missile-war-nagorno-karabakh-lessons-future-strike-and-defense

**Comment by PygmalionOfCyprus** [comment]
Added 494.
