### ISSUE TITLE
Add Sri Lankan AAA Sec (40mm/70 Bofors x2, Flycatcher FCR) 2005

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4771]
### DB Selector

DB3K

### DBID to Copy

Facility 3028

### Hypothetical

No

### Name

AAA Sec (40mm/70 Bofors x2, Flycatcher FCR) 

### Country

Sri Lanka

### Service

Air Force

### In Commission

2005-Present

### Number in Service

6x

### Other Changes

Imported from India in 2005

### Sources

UN  Database
https://www.unroca.org/india/report/2005/

UK report to Parliament (they did get the flycatcher radar part)

https://parliament.lk/uploads/documents/paperspresented/1662013861062935.pdf

https://en.wikipedia.org/wiki/Sri_Lanka_Air_Force

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
