### ISSUE TITLE
Add Sri Lankan Radar (GRL 610 Indra 2) 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4772]
### DB Selector

DB3K

### DBID to Copy

Facility 1240

### Hypothetical

No

### Name

Radar (GRL 610 Indra 2) 

### Country

Sri Lanka

### Service

Air force

### In Commission

2006

### Number in Service

4x

### Sources

https://sundaytimes.lk/080914/Columns/sitreport.html
https://www.airforce.lk/news.php?news=5365
https://commons.wikimedia.org/wiki/File:Indra-I_radar_SriLanka.JPG
https://www.onlanka.com/news/sri-lanka-wanted-u-s-help-as-indian-radars-not-sufficient.html

Sipri 
Sri Lanka	India	2005		2		Indra	air search radar	2		2006	New	Possibly second-hand; aid against LTTE rebels; Indra-2 version	4.75	9.5	9.5
Sri Lanka	India	2007		2		Indra	air search radar	2		2007	New	Possibly second-hand; aid; Indra-2 version	4.75	9.5	9.5

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
