### ISSUE TITLE
Add Sri Lankan Radar (JY-11B)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4773]
### DB Selector

DB3K

### DBID to Copy

Facility 574

### Hypothetical

No

### Name

Radar (JY-11B)

### Country

Sri Lanka

### Service

Air Force

### In Commission

2007

### Sources

https://www.airforce.lk/news.php?news=5065
https://www.airforce.lk/pages.php?pages=mirigama

Sipri
Sri Lanka	China	2007	?	1		JY-11	air search radar	1	?	2007	New	Mainly for use against LTTE rebels	7.5	7.5	7.5

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
