### ISSUE TITLE
Add Sri Lankan and Pakistani Radar(YLC-18A)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4774]
### DB Selector

DB3K

### Hypothetical

No

### Name

Radar (YLC-18A)

### Facility Type

Radar

### Country

Sri lanka, Pakistan

### Service

Air Force

### In Commission

Sri Lanka 2008

### Number in Service

Sri Lanka 1x, 

### Sensors

1x YLC-18A

### Mounts

1x YLC-18A

### Sources

Radar Stats
https://www.ausairpower.net/APA-PLA-IADS-Radars.html#mozTocId486275

Sri Lanka
https://www.cmetsl.lk/more.php?code=75
https://commons.wikimedia.org/wiki/File:Sri_Lanka_Military_0050.jpg

Pakistan
https://x.com/Defense_Talks/status/1781308977046786354
https://x.com/Mrcool63040811/status/1589830069949702148

Sipri
Sri Lanka	China	2007	?	1	?	YLC-18	air search radar	1	?	2008	New		7.5	7.5	7.5

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
