### ISSUE TITLE
Add Sri Lankan SAM Sec (SA-18 Grouse [9K38 Igla] MANPADS x 3

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4776]
### DB Selector

DB3K

### DBID to Copy

Facility 485

### Hypothetical

No

### Name

SAM Sec (SA-18 Grouse [9K38 Igla] MANPADS x 3

### Country

Sri Lanka

### Service

Air force

### In Commission

2007

### Sources

https://commons.wikimedia.org/wiki/File:Sri_Lanka_Military_0192.jpg
https://en.wikipedia.org/wiki/Sri_Lanka_Air_Force_Regiment

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
