### ISSUE TITLE
Add Sri Lankan F-7BS Fishcan [Mig-21 Copy] 1990

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4778]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3762

### Hypothetical

No

### Name

F-7BS Fishcan [Mig-21 Copy]

### Country

Sri Lanka

### Service

Air Force

### In Commission

1990-Present

### Number in Service

9x, -6

### Mounts

Same

### Loadout Options

Same

### Sources

https://www.airhistory.net/photo/609078/SFI-5103
https://www.airforce.lk/history_pages.php?pages=the_roar_of_jets_once_again
http://www.cavok-aviation-photos.net/SriLankaAF.html

Sipri
Sri Lanka	China	1990		5		J-7	fighter aircraft	5		1991	New	F-7B version (incl 1 FT-7 version); mainly for use against LTTE rebels	9	45	45

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
