### ISSUE TITLE
Add Sri Lankan K-8 Karakorum 2001

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4779]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5498

### Hypothetical

No

### Name

K-8 Karakorum

### Country

Sri Lanka

### Service

Air Force

### In Commission

2001-Present

### Number in Service

6x, -6, +6

### Sources

https://www.scramble.nl/planning/orbats/sri-lanka/sri-lanka-air-force
http://www.cavok-aviation-photos.net/SriLankaAF.html
https://en.wikipedia.org/wiki/No._14_Squadron_SLAF
Sipri
Sri Lanka	China	2000	?	6		K-8	trainer/combat aircraft	6		2001	New		3.5	21	21
Sri Lanka	China	2004	?	3		K-8	trainer/combat aircraft	3		2005	New		3.5	10.5	10.5

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
