### ISSUE TITLE
SAM Bn (SA-3c Goa [S-125M1 Neva-M])

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#478]
### DB Selector

DB3K

### DBID to Copy

facility/1787/DB3K

### Hypothetical

No

### Name

SAM Bn (SA-3c Goa [S-125M1 Neva-M])

### Country

Armenia, Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

No major changes known to be completed

### Mounts

No major changes known to be completed

### Loadout Options

No major changes known to be completed

### Other Changes

No major changes known to be completed

### Sources

https://www.oryxspioenkop.com/2021/12/overlooked-and-underfunded-armenias-s.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces#Anti-aircraft
https://en.wikipedia.org/wiki/S-125_Neva/Pechora#Operators
https://en.wikipedia.org/wiki/Azerbaijani_Air_Forces#Equipment

**Comment by PygmalionOfCyprus** [comment]
Added 494.
