### ISSUE TITLE
Add Sri Lankan Arty Bty (RM-70 MLRS x 6) 2000

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4780]
### DB Selector

DB3K

### DBID to Copy

Facility 4153

### Hypothetical

Yes

### Name

Arty Bty (RM-70 MLRS x 6)

### Country

Sri Lanka

### Service

Army

### In Commission

2001-present

### Other Changes

Czechs were the first to import in 2000. Caught in UN reporting and news report link.

### Sources

https://commons.wikimedia.org/wiki/File:Sri_Lanka_Military_0013.jpg
https://www.flickr.com/photos/36169878@N07/3551970071
https://commons.wikimedia.org/wiki/File:Sri_Lanka_Military_0251.jpg
https://thuppahis.com/2016/07/24/where-ratwatte-and-cbk-stood-strong-coping-with-the-elephant-pass-debacle-in-april-may-2000/
https://en.wikipedia.org/wiki/RM-70_multiple_rocket_launcher
UN DB
https://www.unroca.org/slovakia/report/2002/
https://www.unroca.org/czech-republic/report/2000/
Sipri
Sri Lanka	Czechia	2000		16		RM-70 122mm	self-propelled MRL	16		2000; 2001	Second hand	Second-hand; possibly aid against LTTE rebels
Sri Lanka	Slovakia	2000	?	8	?	RM-70 122mm	self-propelled MRL	8		2002	Second hand	Second-hand	0.36	2.88	2.88

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
