### ISSUE TITLE
Add Sri Lankan IA-58A Pucara 1992-1997

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4781]
### DB Selector

DB3K

### DBID to Copy

Aircraft 142

### Hypothetical

No

### Name

IA-58A Pucara

### Country

Sri Lanka

### Service

Air Force

### In Commission

1992-1997

### Number in Service

4x

### Sources

https://www.facebook.com/thearchivesl/photos/a.300607240111417/463914973780642/?type=3&eid=ARCFG91i8Mxvo_ir0z7OL0FpVM7LjZO1NWXEnPe-_y8F8QTrHs390PxQ-yHvT9ppXm5cdUq7PKPupL9k&locale=hi_IN&_rdr
https://www.airhistory.net/photo/608937/CA605
https://en.wikipedia.org/wiki/FMA_IA_58_Pucar%C3%A1

UN DB
https://www.unroca.org/argentina/report/1992/

Sipri Line
Sri Lanka	Argentina	1992		4		IA-58A Pucara	ground attack aircraft	4		1993; 1994	New	$11 m deal; produced 1980s on speculation for export and sold to Sri Lanka 1992	4.3	17.2	17.2

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
