### ISSUE TITLE
Add Arty Bty (152/29 Type 66 Towed Howitzer x 6) 1991

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4782]
### DB Selector

DB3K

### DBID to Copy

Facility 1966

### Hypothetical

No

### Name

Arty Bty (152/29 Type 66 Towed Howitzer x 6)

### Country

Sri Lanka

### Service

Army

### In Commission

1998-present

### Sources

https://en.m.wikipedia.org/wiki/File:Sri_Lanka_Military_0011.jpg
https://en.m.wikipedia.org/wiki/Type_66_howitzer
Sipri
Sri Lanka	unknown supplier(s)	1990	?	10	?	D-20 152mm	towed gun	10	?	1991	New	Possibly second-hand; supplier possibly China	0.5	5	5
Sri Lanka	China	1998		36		D-20 152mm	towed gun	36	?	1999	New	Type-66 version	0.5	18	18

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
