### ISSUE TITLE
Add Sri Lankan SF.260TP 1985

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4783]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6349

### Hypothetical

Yes

### Name

SF.260TP 

### Country

Sri Lanka

### Service

Air force

### In Commission

1985-

### Number in Service

9x

### Loadout Options

Same

### Sources

https://www.facebook.com/thearchivesl/photos/a.300607240111417/426905284148278/?type=3
https://www.flickr.com/photos/propfreak/11544894676

Sipri
Sri Lanka	Italy	1985		6		SF-260TP	trainer aircraft	6		1985	New	Mainly for use against LTTE rebels	0.52	3.12	3.12
Sri Lanka	Italy	1989		2		SF-260TP	trainer aircraft	2		1989	New	Mainly for use against LTTE rebels	0.52	1.04	1.04
Sri Lanka	Italy	1987	?	1		SF-260TP	trainer aircraft	1		1987	Second hand	Second-hand; mainly for use against LTTE rebels	0.21	0.21	0.21

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
