### ISSUE TITLE
China, SLC-18 Radar, modification

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4784]
### DB Selector

DB3K

### Affected DBID(s)

sensor 6992

### Summary of Changes

- [ ] Change the operating band to **B** (IEEE P-Band, VHF, Same as Pave Paw, **"excellent anti-stealth performance"** on the display board).
- [ ] Add **Air search** feature ("Anti-stealth" usually means anti stealth aircrafts).
- [ ] Appropriately **improve radar performance**: appropriately reduce **vertical/horizontal beamwidth** to 1, and appropriately increase **GainLoss** from -2 to +5 (according to the "all-solid, all-coherent, all-digital active phased array" displayed on the display board).

### Sources

https://www.sinodefenceforum.com/t/zhuhai-airshow-2022.8958/post-910739
![8defadfd290a7a073aa2ba0d978fee96](https://github.com/user-attachments/assets/37188572-c241-433f-a025-34f38a7fae47)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus 

Oops... I'm sorry to bother you again when you just closed this ticket, but I think this issue deserves attention.

I further cross-compared the same **Pave Paw (sensor 7000)** and **China LPAR (same as Pave Paw in performance)**, and found that the SLC-18 had unreasonably poor performance in **pulse width** , **range/height resolution & angle** and **blind time.** In any case, the advanced technology of the 2020s is unlikely to do so much worse than the technology of the 1990s.

Therefore, I further add the modification request: 

- [ ] **range resolution** modify to **0.01** (same as Pave Paw and China LPAR)
- [ ] **height resolution** modify to **54** (better than Pave Paw and China LPAR, better tech used)
- [ ] **blind time** modify to **8** (better than Pave Paw and China LPAR)
- [ ] **pulse width** modify to **0.06** (better than Pave Paw and China LPAR)
- [ ] **resolution angle** modify to **1** (better than Pave Paw and China LPAR)
- [ ] **PRF** modify to **27** (same as Pave Paw and China LPAR)

**Comment by LuigiP57** [comment]
I will submit another ticket
