### ISSUE TITLE
JMSDF SS-513 Taigei transformed to Test Submarine

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4785]
### DB Selector

DB3K

### Affected DBID(s)

Submarine DBID 702

### Summary of Changes

Transformed to Test Submarine
SS-513 changed to SSE-6201

### Sources

https://ja.wikipedia.org/wiki/%E3%81%9F%E3%81%84%E3%81%92%E3%81%84_%28%E6%BD%9C%E6%B0%B4%E8%89%A6%29?wprov=sfla1

**Comment by PygmalionOfCyprus** [comment]
Updated comment to reflect test designation & conversion date.
