### ISSUE TITLE
Add US AN/TPS-44 to CWDB

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4787]
### DB Selector

CWDB

### DBID to Copy

Facility 97

### Hypothetical

No

### Name

AN/TPS-44

### Country

United States

### Service

Air Force

### In Commission

1966-

### Sensors

AN/TPS-44

### Mounts

AN/TPS-44

### Other Changes

Flag as cargo

### Sources

https://www.mobileradar.org/picts/radar_sets/tps_44/tps_44.html
https://www.mobileradar.org/unit_76_112.html
https://en.wikipedia.org/wiki/AN/TPS-44

Stats
https://www.mobileradar.org/radar_descptn_3.html
https://www.radartutorial.eu/19.kartei/11.ancient/karte021.en.html

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
