### ISSUE TITLE
Armenian/Azerbaijani Hip Helos

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#479]
### DB Selector

DB3K

### DBID to Copy

aircraft/2632/DB3K

### Hypothetical

No

### Name

Mi-8/17 Hip - 1992

### Country

Armenia, Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

None Known

### Mounts

None Known

### Loadout Options

Add ATGM Loadouts to Azerbaijan with

LAHAT ATGM
and 
Spike NLOS

### Other Changes

None Known

### Sources

https://www.oryxspioenkop.com/2020/12/caspian-amphibians-azerbaijans-elusive.html
https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces#Aircraft
https://en.wikipedia.org/wiki/Azerbaijani_Air_Forces#Equipment

**Comment by PygmalionOfCyprus** [comment]
Added 494.
