### ISSUE TITLE
Add Pakistani Navy Luna NG UAV 2020

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4793]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6858

### Hypothetical

No

### Name

Luna NG UAV

### Country

Pakistan

### Service

Navy

### In Commission

2020

### Sensors

same

### Mounts

same

### Loadout Options

same

### Sources

https://www.janes.com/osint-insights/defence-news/pakistan-navy-inducts-luna-ng-uavs-and-second-atr-72-mpa
https://en.wikipedia.org/wiki/EMT_Luna_X-2000
https://www.oryxspioenkop.com/2022/01/thunder-from-east-pakistans-operational.html
https://x.com/defencealerts/status/1241066494366085120

**Comment by bostonmyk** [comment]
Sipri Line
Pakistan	Germany	2012	?	8		Luna	UAV	8	?	2019	New	Luna NG version	0.1	0.8	0.8

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
