### ISSUE TITLE
Add Pakistani Luna UAV for Pakistani Army

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4794]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5980

### Hypothetical

No

### Name

Luna UAV

### Country

Pakistan

### Service

Army

### In Commission

2012

### Sources

Pakistan	Germany	2006		30	?	Luna	UAV	30	?	2007; 2008	New	For 3 Luna UAV systems; delivery temporarily delayed after Pakistani state of emergency in 2007	0.1	3	3
https://www.facebook.com/pakistanPKaffairs/photos/a-pakistan-army-luna-uav-crash-lands-near-bahawalnagarit-seems-to-be-a-controlle/1237488313030017/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
