### ISSUE TITLE
Add Saudi Luna UAV 2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4796]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5980

### Hypothetical

No

### Name

Luna UAV

### Country

Saudi Arabia

### Service

Air Force

### In Commission

2012

### Other Changes

Saudi manufacturing these

### Sources

https://en.wikipedia.org/wiki/Royal_Saudi_Air_Force
https://x.com/Harry_Boone/status/1095584553312419840
Sipri
Saudi Arabia	Germany	2010		10	?	Luna	UAV	10	?	2011; 2012	New		0.1	1	1

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
