### ISSUE TITLE
C-110-4 Shahid Bagheri

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#4799]
### DB Selector

DB3K

### DBID to Copy

DB3K Ship 4287

### Hypothetical

No

### Name

C-110-4 Shahid Bagheri

### Country

Iran

### Service

IRGC Navy

### In Commission

2024-

### Number in Service

1x

### Sensors

Said to have same or similar sensor fit to L-110-3 Shaid Mahdavi

### Mounts

Said to have same or similar weapons fit to L-110-3 Shaid Mahdavi

### Loadout Options

N/A

### Other Changes

Sister of L-110-3 Shaid Mahdavi but equipped with an 170m angle deck and ski jump for fixed with UAV operations. Elevator on starboard of flight deck to hangar. Cargo door on the starboard side possibly in port access at Hangar Level.

### Sources

http://www.hisutton.com/Iran-IRGC-Drone-Carrier-Update.html
http://www.hisutton.com/Iran-IRGC-Drone-Carrier-Update-04-2023.html
https://x.com/IrnaEnglish/status/1787495272349684065
https://x.com/mhmiranusa/status/1607045992557281282
https://x.com/Defence_IDA/status/1786951099120841039
https://x.com/mhmiranusa/status/1658558481920585730
https://x.com/AmirIGM/status/1739231437159571753
https://x.com/mhmiranusa/status/1658558481920585730
https://premium.globalsecurity.org/military///world/iran/irgcn-shahid-bagheri-pics.htm
https://splash247.com/iranian-boxship-converted-into-drone-carrier-readies-for-duty/
https://defencesecurityasia.com/en/iran-drone-carrier-border/
https://theaviationgeekclub.com/irans-first-aircraft-carrier-is-under-construction-it-will-be-a-drone-aircraft-carrier-obtained-from-converted-merchant-ship-and-its-expected-to-be-launched-in-2023/

![image](https://github.com/user-attachments/assets/efae46da-e7ce-4ab9-986d-eaea8fc675f8)

![image](https://github.com/user-attachments/assets/0a9309e8-1d6f-4e61-bc05-10de294d4d3d)

![image](https://github.com/user-attachments/assets/47f91042-bc34-4a7c-8082-264ed075746d)

![image](https://github.com/user-attachments/assets/b2656df6-c311-4e5a-a8d4-9e1fc61a8273)
![image](https://github.com/user-attachments/assets/108426a6-9800-45b6-8f82-5f0b5fb190f7)

![image](https://github.com/user-attachments/assets/ad564ca5-53ee-482c-88a9-dfb277029b60)

![image](https://github.com/user-attachments/assets/b9ddc398-5d14-4a15-afca-988760576029)

![image](https://github.com/user-attachments/assets/ecceb3d6-00f3-4f49-aaae-186bb69226eb)
![image](https://github.com/user-attachments/assets/0d5396c3-ad37-4c02-ae32-a3105e6db07e)
![image](https://github.com/user-attachments/assets/47762347-0754-49ee-a381-3ec5b826fb61)
![image](https://github.com/user-attachments/assets/dbfb8c11-e18d-4b42-bba3-4f94347d96f4)
![image](https://github.com/user-attachments/assets/a34da10c-9c25-4bb4-8497-24f121ced73f)
![image](https://github.com/user-attachments/assets/0d634921-34c2-45c2-9b4c-d7d51fefa1f4)

Elevator
![image](https://github.com/user-attachments/assets/fb9f80e7-5ad5-44c3-9081-80d887585ee5)

![image](https://github.com/user-attachments/assets/f9fae110-abc7-4d64-8f33-4f85f7b50906)

Cargo door at Hangar Level?
![image](https://github.com/user-attachments/assets/5d3581e9-9b2c-4f57-9974-73ada040aa51)

**Comment by tbrandon517** [comment]
![FB_IMG_1724366637321](https://github.com/user-attachments/assets/e984550e-50c3-4a65-9b17-62c14d9cd19b)

**Comment by tbrandon517** [comment]
https://www.twz.com/air/irans-bizarre-aircraft-carrier-seen-in-new-detail

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

**Comment by tbrandon517** [comment]
> Handled 509.

Now the West shall tremble! 😉

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus 

There appears to a possible containerized TEL for 'Dezful' medium range ballistic missiles like those fired from Shahid Mahdavi in February, 2024 fitted on after superstructure to starboard of port side Ghader ASM launchers (starboard Ghader launchers appear to be below abd aft on the aft helo deck).

http://www.hisutton.com/Iran-Navy-IRGC-Forward-Base-Ships.html

![17360890170532615857065699593278](https://github.com/user-attachments/assets/c3f8d15a-ae36-40b4-97c6-d993f964f969)
