### ISSUE TITLE
HQ-11(H-11),Short-range anti-aircraft missile

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4801]
### DB Selector

DB3K

### Baseline

weapon 3138

### Hypothetical

No

### Name

HQ-11

### Length (m)

3.66

### Width/Span (m)

1

### Diameter (m)

0.25

### Weight (kg)

280

### Range (nm)

1-25

### Warhead

35kg frag

### Targets

Aircraft, Helicopter, Missile

### CEP (m)

1

### Sensors

1x Active Radar Seeker (Late 2010s)

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer, Lock-On After Launch (LOAL), Level Cruise Flight

### Comments

A weapon system already on display at the 2022 Zhuhai Air Show has been confirmed as a new short-range air defense system. I made the edits based on the information available at the moment, but because there is so little information about HQ-11, I can only refer to more information about the same type of system.At the same time, requests for additional HQ-11 ground facilities with multiple vehicles. A single vehicle of the HQ-11 system **has integrated an AESA** (search range of not less than 50nm), and should **have at least one LD-3000 system** (LD-2000 system replacement H/PJ-14 close defense gun).
If additional information about this system is subsequently discovered, I will resubmit the revised article about this system.

### Sources

#4369
https://en.wikipedia.org/wiki/HQ-11
https://en.topwar.ru/212585-zenitnyj-raketno-artillerijskij-kompleks-hq-11-kitaj.html
https://www.globaltimes.cn/page/202211/1279382.shtml?id=11
![image](https://github.com/user-attachments/assets/b4de8ad3-7581-4ba5-861e-fa75afe6d4e7)
![image](https://github.com/user-attachments/assets/8072c3c7-742a-4d5b-ab45-a71a5123d898)

**Comment by LuigiP57** [comment]
#4369

**Comment by LuigiP57** [comment]
Refer to HQ-64 Plt: **3x HQ-11 TELs + 3x LD-3000 CIWS** in one facility.
![image](https://github.com/user-attachments/assets/846461c4-914e-431d-9961-4a84bcc03df8)

**Comment by LuigiP57** [comment]
May also need a reasonable 16 channel command link.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
