### ISSUE TITLE
China, Large synthetic impulse and aperture radar (SIAR),An OTH radar

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4803]
### DB Selector

DB3K

### Baseline

Sensor 5649

### Hypothetical

No

### Name

China SIAR

### Sensor Generation

Late 2010s

### Range (nm)

10-1500

### Sensor Capabilities

Air Search, Range Information, Altitude Information, Speed Information, Heading Information,OTH-Backscatter

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Pulse Doppler Radar (Full LDSD Capability),Active Electronically Scanned Array (AESA),Moving Target Indicator (MTI),Frequency Agile

### Search/Track Frequencies

A Band (30-250 MHz) [Old P Band (HF)] 100-300 cm

### Lower Frequency (Hz)

100mhz

### Upper Frequency (Hz)

200mhz

### Scan Interval (s)

10

### Target Altitude (ft)

0-100000ft

### Horizontal Beamwidth (deg)

1

### Vertical Beamwidth (deg)

1

### System Noise Level (dB)

3

### Processing Gain/Loss (dB)

10

### Peak Power (W)

7000000

### Pulse Width (μs)

0.16

### Blind Time (μs)

0.4

### PRF (Hz)

30

### Comments

According to satellite images released as early as 2016, the PLA has installed SIAR at its bases in the South China Sea to monitor the air posture of neighboring countries. The analysis believes that the radar works in the 100mhz-200mhz band, the purpose is to effectively monitor the stealth fighters of various countries.
In response to the United States' powerful stealth technology, China's use of this unique new radar as a counter measure is worth keeping track of.

### Sources

https://news.usni.org/2016/02/22/new-possible-chinese-radar-installation-on-south-china-sea-artificial-island-could-put-u-s-allied-stealth-aircraft-at-risk
https://www.popularmechanics.com/military/weapons/news/a19602/china-installing-anti-stealth-radar-in-south-china-sea/
![image](https://github.com/user-attachments/assets/01252f64-93d1-4bb2-b1a7-6336680547be)
![image](https://github.com/user-attachments/assets/f33ac4c8-5106-4a8a-9e18-2bd3b503d1f0)

**Comment by LuigiP57** [comment]
More about SIAR:
https://www.jhuapl.edu/sites/default/files/2022-12/InDepthSubiReefCounterStealthRadar.pdf
Frequency:
![7c51fa8efcc0063e6e81c83f547efc13](https://github.com/user-attachments/assets/0d72fb28-e313-4763-910c-8546c73015d7)
Despite being called VHF, in the game this band is covered by the A/HF band, which is typical of the OTH-B radar band.
![image](https://github.com/user-attachments/assets/68fb4e41-2c2a-4d05-a40d-e1cd91d15dc6)

**Comment by HunterDNiu** [comment]
#3684

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
