### ISSUE TITLE
Add Sudanese Mohajer-6 UCAV 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4805]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6196

### Hypothetical

No

### Name

Mohajer-6 UAV

### Country

Sudan

### Service

Air Force

### In Commission

2024

### Sources

https://www.bloomberg.com/news/articles/2024-01-24/iran-supplies-sudan-army-with-drones-as-civil-war-continues?embedded-checkout=true
https://www.reuters.com/world/middle-east/are-iranian-drones-turning-tide-sudans-civil-war-2024-04-10/
https://www.military.africa/2024/01/rsf-shoot-down-sudans-army-mohajer-drone/
https://adf-magazine.com/2024/02/safs-use-of-iranian-drones-threatens-to-destabilize-region/
https://en.wikipedia.org/wiki/Qods_Mohajer-6
https://x.com/clashreport/status/1801674477887172697

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
