### ISSUE TITLE
Add Sudanese K-8 Karakorum 2007

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4806]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5498

### Hypothetical

No

### Name

K-8 Karakorum

### Country

Sudan

### Service

Air Force

### In Commission

2007

### Number in Service

x9

### Sensors

same

### Mounts

same

### Loadout Options

same

### Sources

https://chinese-military-aviation.blogspot.com/p/trainers.html
https://x.com/HammerOfWar5/status/1794420391840018772
https://x.com/HammerOfWar5/status/1794372389985570875
https://commons.wikimedia.org/wiki/File:Sudanese_Air_Force_Hongdu_K-8-1.jpg
https://x.com/RupprechtDeino/status/1373590681780912128

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
