### ISSUE TITLE
Add IDF Skylark I-LEX 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4809]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6062

### Hypothetical

No

### Name

 Skylark I-LEX 

### Country

Israel

### Service

Army

### In Commission

2006

### Other Changes

40km LOS

### Sources
https://odin.tradoc.army.mil/WEG/Asset/212a251ae97925b9664c15ad1b7ada61
https://x.com/ElbitSystemsLtd/status/1433702994822975494
https://x.com/ElbitSystemsLtd/status/1368532127004909571
https://www.army-technology.com/projects/skylark-i-le-small-unmanned-aircraft-system-suas/?cf-view

**Comment by tbrandon517** [comment]
Related #2650

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
