### ISSUE TITLE
Rethink the speed performance of the DF-27 glider

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4817]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4318 4320 4322

### Summary of Changes

I noticed that the speed performance of the DF-27 as a long-range HGV doesn't seem to be quite what it should be. As an HGV projected by a projectile with a **booster shutdown speed of Mach 18**, such as the DF-26, its top speed is only 6000 kt.

According to the leaked Pentagon report, **it flew 2,100km in 12 minutes** during one test, which translates to an **average speed of about 7000kt**.

Therefore, I propose that the speed performance of the DF-27 HGV be modified as follows:

**6000kt-6500kt (this band is the actual cruise band in game) -8000kt-9000kt**

### Sources

https://twitter.com/ryankakiuchan/status/1645657427315142656
![image](https://github.com/user-attachments/assets/8c3ebf5b-3a22-4aca-9778-4d153e5653e9)
https://zh.wikipedia.org/wiki/%E4%B8%9C%E9%A3%8E-26%E4%B8%AD%E7%A8%8B%E5%BC%B9%E9%81%93%E5%AF%BC%E5%BC%B9

> In 2015, when the "China Science and Technology Award" reported "China's first general medium and long range precision strike missile", it said that "it has achieved the technological leap from Mach 12 to Mach 18 of the dynamic aircraft with air steering gear and a major breakthrough in the actual combat capability of strategic weapons", indirectly confirming the penetration capability of the DF-26 with a maximum speed of Mach 18.

**Comment by HunterDNiu** [comment]
I don't think so. The representative test is not going for an optimal range and was generally meant to validate booster/GV as well as data collection with a more challenging trajectory, and with the same energy (unless depressed trajectory /upper stage withheld). HGV doesn't work that way. A good example would be the old DF-41 HGV or MMIII HGV.

**Comment by LuigiP57** [comment]
> I don't think so. The representative test is not going for an optimal range and was generally meant to validate booster/GV as well as data collection with a more challenging trajectory, and with the same energy (unless depressed trajectory /upper stage withheld). HGV doesn't work that way. A good example would be the old DF-41 HGV or MMIII HGV.

Please note the details of US intelligence: **"HGV flew"**. I think, taken literally, it was referring to the fact that the HGV flew 2100km, which is a long distance. And you also mentioned that it has the potential to test more challenging trajectories, that is, 2100km may just be a spatial movement in a straight line distance, and the actual trajectory may be greater than 2100km. If it can maintain an average cruising speed of 7,000 knots in these conditions, it may be even higher when flying on a straight trajectory.

At the same time, I also compared the intercontinental range HGV. What I'm saying is that it's not fair to expect an HGV with a limit range of 3000 nautical miles to have the same speed performance as an HGV with a limit range of 7000 nautical miles (more than twice that). The C-HGB should at least be its equivalent, with a in-game cruise speed of 4,000 knots (1,000 knots faster than the DF-27 HGV). I don't know the cruising speed of a real C-HGB under the same conditions, but I believe if we have a reliable enough source, we can correct it. The reality is we don't have C-HGB data, only DF-27 data. So we have to fix the DF-27 first.

In fact, the game's simulation of HGV is also controversial. For "boost-glide" hypersonic weapons such as DF-27, C-HGB, Avangard, there may be a long maximum energy ballistic flight phase to obtain maximum speed, and a considerable part of its flight trajectory is no different from that of ballistic missiles, so that its initial glide speed is as high as possible.

However, waveriders such as the DF-17/27 and TBG theoretically have a higher lift-to-drag ratio than bipyramids such as the C-HGB and DF-26, which would allow them to have a much longer range at the same speed, but this is also not shown in the game (previously, I wanted to keep the DF-27's speed performance unchanged while extend its range to 8000km).

**Comment by LuigiP57** [comment]
Anyway, I tweaked the speed performance.

**Comment by LuigiP57** [comment]
@HunterDNiu @PygmalionOfCyprus And have you guys noticed that the Avangard speed performance is even unreasonable?

**Comment by LuigiP57** [comment]
prefer #4904
