### ISSUE TITLE
Mech Inf Plt (BMP-1P [AT-5 Spandrel] IFV x 3) (Widely Exported)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#482]
### DB Selector

DB3K

### DBID to Copy

facility/2042/DB3K

### Hypothetical

No

### Name

Mech Inf Plt (BMP-1P [AT-5 Spandrel] IFV x 3) (Widely Exported)

### Country

Armenia, Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

Not Specified

### Mounts

Armenia upgraded several BMP-1s with the addition of two 23mm autocannons taken from ZU-23s and ZSU-23-4s. This does little towards expanding the actual capabilities of the vehicle however, while hugely increasing the workload of the gunner, who now has to operate both types of guns.

### Loadout Options

Not Specified

### Other Changes

Not Specified

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494. Increased targeting OODA for Armenia's modded version.
