### ISSUE TITLE
Add UK Army Arty Bty (155mm/52 FH-77BW L52 Archer Self-Propelled Howitzer x6 ) 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4821]
### DB Selector

DB3K

### DBID to Copy

Facility 2297

### Hypothetical

No

### Name

Arty Bty (155mm/52 FH-77BW L52 Archer Self-Propelled Howitzer x6 )

### Country

United Kingdom

### Service

Royal Army

### In Commission

2024

### Sensors

Same

### Mounts

same

### Sources

https://www.army.mod.uk/news-and-events/news/2023/10/british-army-s-first-archer-gun-has-arrived-on-uk-soil/
https://en.wikipedia.org/wiki/Archer_artillery_system

Sipri
United Kingdom	Sweden	2023		14		Archer 155mm	self-propelled gun	14	?	2023	New	Second-hand but never used	1.5	21	21

**Comment by bostonmyk** [comment]
https://x.com/royalartillery1/status/1818171595791257712

**Comment by bostonmyk** [comment]
https://x.com/Gabriel64869839/status/1837244395697099014

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
