### ISSUE TITLE
SSM Plt (ATGM) (3x)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#484]
### DB Selector

DB3K

### DBID to Copy

facility/2939/DB3K

### Hypothetical

No

### Name

SSM Plt (ATGM) (3x)

### Country

Armenia, Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

Not Specified

### Mounts

Change missiles to

9K111 Fagot

or

9M113 Konkurs

or 

9M133 Kornet 

### Loadout Options

Not Specified

### Other Changes

Not Specified

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces

**Comment by PygmalionOfCyprus** [comment]
Why not all 3? Added Spandrel, Spigot, and Spriggan platoons for both Armenia and Azerbaijan.
