### ISSUE TITLE
China, CM-501GA Missile (like NLOS)

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4840]
### DB Selector

DB3K

### Baseline

Weapon 2788

### Hypothetical

No

### Name

CM-501GA

### Length (m)

2

### Width/Span (m)

0.9

### Diameter (m)

0.18

### Weight (kg)

100

### Range (nm)

0-70

### Warhead

20kg HE 

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

1

### Sensors

1x TV Camera
1x FLIR Camera
2 Way Datalink for midcourse guidance

### Weapon Codes

Lock-On After Launch (LOAL), Terrain Following, Weapon - INS Navigation, Uses BeiDou/COMPASS

### Comments

CM501GA is a product launched by Chinese military enterprises to imitate the product ideas of their American counterparts.

On the basis of
https://www.armyrecognition.com/news/army-news/2024/china-promotes-new-cm-501ga-lightweight-multi-purpose-missile-at-dimdex-2024.

"The CM-501GA missile is equipped with a dual mid-course guidance system combining an inertial navigation system (INS) and a satellite datalink, alongside TV and infrared (IR) guidance for the terminal flight phase. The missile's known specifications include a length of 2 meters, a diameter of 180 mm, and a total weight of 100 kilograms, which includes a 20-kilogram high-explosive warhead, with a claimed accuracy within 1 meter and a success rate of 90%."

In an interesting picture, we can see that the PLA has equipped and used her. It has been written in the exhibition hall on how to use her, but I would like to leave more information to the following picture. :)

### Sources

http://www.xinhuanet.com//mil/2015-05/27/c_127846853_2.htm
https://www.armyrecognition.com/news/army-news/2024/china-promotes-new-cm-501ga-lightweight-multi-purpose-missile-at-dimdex-2024
https://www.facebook.com/100079514112956/posts/2034810546723027/
#4453 
![6S6RCLY`02W4{`5I5@29QEW](https://github.com/user-attachments/assets/f3002c97-3bec-4470-aa77-de4ab5f14284)
![image](https://github.com/user-attachments/assets/d7d52ccb-b1c8-4a7a-a499-940877eccb8c)
![image](https://github.com/user-attachments/assets/e5c4c4e9-7a0c-4f15-8c04-367cb82e07d9)

**Comment by PygmalionOfCyprus** [comment]
Was added 509.
