### ISSUE TITLE
New PLAAF CM-501GA AGM loadouts

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4846]
### DB Selector

DB3K

### User(s)

Aircraft 2493,5856,7033(Z-10,Z-10ME),3305,5855(Z-19),Z-21,2708(Z-9EC),5854(Z-9C,2015),3302(Z-9D,2013),4908(Z-9D,2019)

### Weapons Carried

Z-10:
-8×CM-501GA,14×70mm rocket
-8×CM-501GA,14×FS 70 Guided Rocket
-8×CM-501GA,4×TY-90
-16×CM-501GA
-8×CM-501GA,2×500 liter drop tank
Z-19:
-8×CM-501GA,14×90mm rocket
-8×CM-501GA,4×TY-90
-16×CM-501GA
-8×CM-501GA,2×500 liter drop tank
Z-21:
-16×CM-501GA,4×TY-90
-16×CM-501GA,2×PL-10
-8×CM-501GA,8×AKD-10,4×TY-90
-8×CM-501GA,8×AKD-10,2×PL-10
-8×CM-501GA,2×500 liter tank,4×TY-90
-8×CM-501GA,2×500 liter tank,2×PL-10
-8×CM-501GA,14×FS 70 Guided Rocket,4×TY-90
-8×CM-501GA,14×FS 70 Guided Rocket,2×PL-10
-8×CM-501GA,14×70mm Rocket,4×TY-90
-8×CM-501GA,14×70mm Rocket,2×PL-10
-8×CM-501GA,2×YJ-9，4×TY-90
-8×CM-501GA,2×YJ-9，2×PL-10
Z-9EC/C/D：
-4×CM-501GA

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://x.com/Nickatgreat1220/status/1547902685168279555
https://www.facebook.com/100079514112956/posts/2034810546723027/
![DM_20240729225120_001](https://github.com/user-attachments/assets/090e54b0-f005-4e32-b61d-e2d5305112eb)
https://www.eurasiantimes.com/china-to-arm-pakistan-navy-z-9-helicopters-anti-ship-missiles/

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Holding off on adding to PLAGF Z-9s until we see some evidence.
