### ISSUE TITLE
Copy ship #2963 - RK Tarantul III Mod [Pr.1241.1M Molniya-1] (Russia [1992-] - 2000) create RK Tarantul IV [Pr.1241.8 Molniya] (Russia [1992-] - 2024) Stupinets. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4849]
### DB Selector

DB3K

### DBID to Copy

Ship #2963 - RK Tarantul III Mod [Pr.1241.1M Molniya-1] (Russia [1992-] - 2000)

### Hypothetical

No

### Name

RK Tarantul IV [Pr.1241.8 Molniya] (Russia [1992-] - 2024) Stupinets

### Country

Russia

### Service

Navy

### In Commission

30/07/24 

### Number in Service

1 to be followed by 1 more - export vessels repurposed after sale fell through. 

### Sensors

Sensors appear as for Tarantul III Mod. 
Radar swap Band Stand for what appears to be 3TS-25E? #114 - Plank Shave [3Ts-25 Garpun-Bal] which is typically Bal related FCR and as on Vietnamese and Indian Tarantuls. 
Probably later than CS Gen 5 (1986-2000) (ex: NTU, Aegis w/ UYK-43 CPU) better CPU? CS Gen 6 (2001-2029) (ex: Aegis w/ COTS/Mil CPU) 

### Mounts

1x AK-176 76mm/60 Single - this is actually the AK-176M but this mount is more accurate as it includes optional ammunition. Previous requested to have the existing AK-176M mount updated as it currently is very inaccurate and less effective than the older version in the DB. 
2x AK-630M 30mm/65 Gatling - slightly modified gun cowling but not enough to warrant a new entry.
2x PK-10 DL
1x SA-N-10 Gimlet [9K310 Igla-1] Twin or quad MANPADS - this could probably also mount the Verba but again not enough to warrant a new entry? MTU-4M quadruple launcher for 9K310 Igla-1 or 9K38 Igla
4x SS-N-25 4x Quad - probably capable of using later version of the Switchblade which has longer range and land attack - could benefit from a copy of #3652 - AS-20 Kayak [Kh-35UE] GLONASS - to create SS-N-25 Switchblade B [Kh-35U] ? 
2x 14.5mm MG mounts are currently empty but can be seen either side of bridge Pt/Stbd. 

### Loadout Options

N/A

### Other Changes

Differ in layout from the Vietnamese version which have 16 Kh-35 replacing the amidships SS-N-22 quads.
Less reflective mid cross deck arrangement. 

### Sources

https://x.com/MrFrantarelli/status/1817989129688465717
https://x.com/GrangerE04117/status/1818009037184856119
https://x.com/Saturnax1/status/1808372417858814147

**Comment by KLABDB3K** [comment]
https://www.janes.com/osint-insights/defence-news/sea/new-class-of-russian-missile-boat-launched-at-vympel-shipyard?utm_campaign=Social_News&utm_content=302983688&utm_medium=social&utm_source=twitter&hss_channel=tw-70529694

Has some interesting updates and the engine configuration is significantly different. Not got past the pay wall limit so will do some more digging.

**Comment by KLABDB3K** [comment]
https://www.navalnews.com/naval-news/2024/07/russia-launches-project-12418-tarantul-class-corvette-stupinets/

Yep CODAD lower speed 29kts.
Not sure if Tarantul IV is really appropriate given the significance of changes to this variant.?

**Comment by Jkryos** [comment]
Added DB3K 508.
