### ISSUE TITLE
Arty Bty (BM-30 Smerch MLRS x 6)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#485]
### DB Selector

DB3K

### DBID to Copy

facility/2116/DB3K

### Hypothetical

No

### Name

Arty Bty (BM-30 Smerch MLRS x 6)

### Country

Armenia, Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

Not Specified

### Mounts

Not Specified

### Loadout Options

Not Specified

### Other Changes

Not Specified

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
