### ISSUE TITLE
SSM Plt (AT-14 Spriggan [9N133 Kornet]) (3x)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#486]
### DB Selector

DB3K

### DBID to Copy

facility/2219/DB3K

### Hypothetical

No

### Name

SSM Plt (AT-14 Spriggan [9N133 Kornet]) (3x)

### Country

Armenia, Azerbaijan

### Service

Army

### In Commission

Post 1995

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
