### ISSUE TITLE
China, WZ-7 AESA

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4865]
### DB Selector

DB3K

### DBID to Copy

sensor 6074

### Hypothetical

No

### Name

WZ-7 AESA

### Country

China

### Service

Navy

### Other Changes

May increase its detecting range to 200nm, since it is a large reconnaissance UAV.

### Sources

https://www.navalnews.com/naval-news/2023/03/china-unveils-naval-variant-of-wz-7-recon-drone/
![image](https://github.com/user-attachments/assets/28d42d72-57bd-4ccc-92a3-58889c925e5f)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
