### ISSUE TITLE
China, WZ-7 UAV update

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4866]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4623

### Summary of Changes

- [ ] Add WZ-7 AESA
- [ ] Add IR & TV Camera (20nm/100nm class)
- [ ] May add a carrier capable property to it, or add a hypothetical carrier capable version

### Sources

https://www.navalnews.com/naval-news/2023/03/china-unveils-naval-variant-of-wz-7-recon-drone/
https://www.csis.org/analysis/chinas-massive-next-generation-amphibious-assault-ship-takes-shape
![image](https://github.com/user-attachments/assets/4d39132a-3ff6-4a3b-8757-1be89ab4aec0)
https://news.cgtn.com/news/2021-11-11/China-s-WZ-7-reconnaissance-UAVs-deployed-for-combat-training-156wAWFV8KQ/index.html
IR & TV Camera under its nose:
![image](https://github.com/user-attachments/assets/0c3870de-fdff-4df9-95c7-c2f3acc0aaed)

**Comment by LuigiP57** [comment]
New images of WZ-7
https://twitter.com/Hurin92/status/1833826868329394539
![image](https://github.com/user-attachments/assets/501ae90e-fcea-4ab9-8a85-44d4b82a2911)

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Only added the AESA to the PLANAF version as they appear to be different (PLAAF versions don't have the frontal WTM).
