### ISSUE TITLE
Quadcopter UAV - Armenia

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#487]
### DB Selector

DB3K

### DBID to Copy

aircraft/5416/DB3K

### Hypothetical

No

### Name

Quadcopter UAV - 2021

### Country

Armenia

### Service

Army

### In Commission

2020-Present

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Gonna leave the quadcopter just as a generic for now, since these things are so widely available commercially that adding them to individual countries is going to be quite the rabbit hole.

**Comment by tbrandon517** [comment]
No worries. I thought you might go that way but OCD got the best of me this time.
