### ISSUE TITLE
Add Malian Shilka 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4871]
### DB Selector

DB3K

### DBID to Copy

Facility 2659

### Hypothetical

No

### Name

AAA Plt/2 ZSU-23-4 Shilka x2

### Country

Mali

### Service

Army

### Sources

https://x.com/HammerOfWar5/status/1752763810383876128
https://x.com/i/bookmarks?post_id=1750952806461087844
https://www.oryxspioenkop.com/2021/10/sons-of-bamako-malian-armed-forces.html
https://maquette-garden.forumactif.com/t31964-zsu-23-4-malien
https://tank-afv.com/coldwar/ussr/ZSU-23-4-Shilka.php

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
