### ISSUE TITLE
Add Malian SAM Bn (SA-3a Goa [S-125 Neva]) 1981-2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4872]
### DB Selector

DB3K

### DBID to Copy

Facility 3616

### Hypothetical

No

### Name

SAM Bn (SA-3a Goa [S-125 Neva])

### Country

Mali

### Service

Air Force

### In Commission

1981-2012

### Number in Service

3x

### Sources
https://www.oryxspioenkop.com/2022/02/goas-in-savanna-s-125-sam-systems-in.html
https://www.oryxspioenkop.com/2021/10/sons-of-bamako-malian-armed-forces.html
https://i.postimg.cc/52KTBg9M/763.png

Sipri
Mali	Soviet Union	1981	?	3	?	S-125 Pechora	SAM system	3	?	1981	New		17.5	52.5	52.5

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
