### ISSUE TITLE
Add Malian Mig-21MF Fishbed J 2005-2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4873]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2749

### Hypothetical

No

### Name

Add Malian Mig-21MF Fishbed J

### Country

Mali

### Service

Air Force

### In Commission

2005-2012

### Number in Service

3x, -1

### Loadout Options

retain most loadouts but AA-1

### Other Changes

ex Czech

### Sources

https://www.armedconflicts.com/MiG-21MF-5512-t213107
https://www.keymilitary.com/article/malian-air-force-modernisation

Sipri
Mali	Czechia	2005		3		MiG-21MF	fighter aircraft	3		2005	Second hand	Second-hand; incl 1 MiG-21UM trainer/combat version	4.28	12.84	12.84

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
