### ISSUE TITLE
Add Malian Mig-21bis Fishbed L 1976-2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4874]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6676

### Hypothetical

No

### Name

Mig-21bis Fishbed L

### Country

Mali

### Service

Air Force

### In Commission

1976-2012

### Number in Service

16x

### Other Changes

The gate guard doesn't have the chin antenna, so it's Mig-21bis L, but the 1997 photo has it, so perhaps it's Mig-21bis N as well. I'm not sure this matters much in CMO terms, as that's a landing system antenna.

### Sources

https://www.keymilitary.com/article/malian-air-force-modernisation
https://x.com/DavidDetten/status/1386566649726345219
https://nara.getarchive.net/media/three-mali-army-troops-stand-in-a-hangar-in-front-of-mali-air-forces-mig-21-777173
https://flancosur.com/2022/07/31/los-mig-21-de-mali/
https://www.airliners.net/photo/Mali-Air-Force/Mikoyan-Gurevich-MiG-21bis/1807589
Sipri
Mali	Soviet Union	1976	?	16	?	MiG-21bis	fighter aircraft	16	?	1976	Second hand	Probably second-hand; incl 2 MiG-21UM trainer/combat version; probably aid	5	80	80

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
