### ISSUE TITLE
AN/TPS-43 for Britain

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4878]
### DB Selector

DB3K

### DBID to Copy

Facility 1810

### Hypothetical

No

### Name

Type 99 [AN/TPS-43F]

### Country

United Kingdom

### Service

Air Force

### In Commission

1985-1999

### Number in Service

1x, Captured from Argentina

### Other Changes

Another Falklands capture, refurbished and used by the RAF as a gap filler system. There's not a lot of information out there, sadly, I've had to scrape some forums for clues.

### Sources

https://www.subbrit.org.uk/sites/buchan-rotor-radar-station/
https://www.pprune.org/archive/index.php/t-377169.html
https://www.rafweb.org/Organsation/1ACC.htm
https://www.worldnavalships.com/forums/thread.php?threadid=13257 - 1999 OOS

ETS is tricky:
https://marconiradarhistory.pbworks.com/w/page/140578029/Memories%20of%20the%20S259%20Radar - "Just as I left the RAF the unit, now with a captured Argentinian TPS43 "Type 99" on strength, was renamed 144 SU."
https://www.egoat.net/threads/144-signals-unit-info-required.15623/ - "the actual day in September 1985 that [144 SU] formed at Wattisham."
144 SU was a formalisation of an ad hoc mobile radar unit called the USST, which presumably had the Type 99 but not significantly before it got the rename. I'm therefore going for 1985 ETS.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
