### ISSUE TITLE
China, PLANAF, BZK-005H SIGINT variant

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4879]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3309

### Hypothetical

No

### Name

BZK-005H, SIGINT Surveillance

### Country

China

### Service

PLAN

### In Commission

2024

### Sensors

1x Generic SIGINT [Advanced] early 2020s

Remove IR & TV Camera. Dedicate SIGINT variant obviously.

### Loadout Options

Surveillance

### Sources

https://www.mod.go.jp/js/pdf/2024/p20240809_06.pdf
![image](https://github.com/user-attachments/assets/be4d2df1-9503-4714-8e93-0b6efc747a87)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
