### ISSUE TITLE
SAM Plt (SA-13 Gopher [9K35 Strela-10])

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#488]
### DB Selector

DB3K

### DBID to Copy

facility/31/DB3K

### Hypothetical

Yes

### Name

SAM Plt (SA-13 Gopher [9K35 Strela-10])

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.thedrive.com/the-war-zone/36777/everything-we-know-about-the-fighting-that-has-erupted-between-armenia-and-azerbaijan
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
