### ISSUE TITLE
Update BM-120 Fath name, guidance and CEP

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4883]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4202 and Facility 3759

### Summary of Changes

Update name to BM-120 Fath 360- Probably pedantic but Fath 360 seems to be used much more lately.
Add GLONASS Guidance to weapon 4202
CEP should be 2m. Iranians have a good record of hitting with newer stuff.

### Sources

https://x.com/sentdefender/status/1821967493080215698
https://en.wikipedia.org/wiki/Fath_360

**Comment by PygmalionOfCyprus** [comment]
> Iranians have a good record of hitting with newer stuff.

Me, looking at BDA of the Israeli airfields after their latest attack w/ brand-new top-line ballistic missiles:

![1300044776986-3567266194](https://github.com/user-attachments/assets/f358981c-3387-41fc-874c-e2fc80e56f85)

I dunno about that. I think a 10m CEP is perfectly far for the domestic version, esp. considering it's only listed as being "<30m" on Wikipedia citing Maghreb news (I know, not a reputable source, but they'd be more likely to exaggerate it down).

Rest handled 509.

**Comment by bostonmyk** [comment]
No problem.

Big issue with all Iranian rocket may be the reliability stat (vs. CEP). Missiles are failing before they get there.
