### ISSUE TITLE
Sensor_6573 "Type 052DL "Anti-Stealth" Radar nomenclature revision

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#4886]
### DB Selector

DB3K

### Affected DBID(s)

Sensor_6573

### Summary of Changes

Sensor_6573 "Type 052DL "Anti-Stealth" Radar  is currently identified as the "Type 518" aka "Sea Eagle" radar

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient4/karte059.en.html
https://news.usni.org/2014/05/14/can-chinas-new-destroyer-find-u-s-stealth-fighters

**Comment by PygmalionOfCyprus** [comment]
I think this is wrong, and these sources are mistaken.

The Type 518 Sea Eagle was the radar they originally put on the Luhus. It was basically a ground airport/ATC surveillance radar. Here's a picture: 
![image](https://github.com/user-attachments/assets/fef009db-670b-41d8-8b3d-5e7cf16cfda1)

As you can see, the curved design is very distinct from the rectangular array currently in service on the 052DLs. As far as I can tell, the 052DL radar has still not been identified.

I think someone screwed this up somewhere and somehow made it to EN Wikipedia, where it is now propagating among people who don't care to actually learn their Chinese naval radar visual recognition (not that I can blame them :stuck_out_tongue:). Most damningly this claim has not been advanced by any Chinese sources...

In fact, it may be radartutorial's fault. They say (correctly) that "The radar was fitted to a number of Luhu-class destroyers of the Chinese Navy. It is now replaced by Type 517M long-range air surveillance anti-stealth radars." But they use this image, which is clearly of an 052DL, not a Luhu...

![image](https://github.com/user-attachments/assets/7fa3fcaa-63f0-4f07-847c-99cfd10b3018)

Someone probably picked up on that and thought they were real clever for IDing the 052DL radar based on that picture.
