### ISSUE TITLE
Ground defenses don't attack propeller planes and the like

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#4887]
### DB Selector

DB3K

### Affected DBID(s)

All aircraft with "WRA Zero"

### Description of Problem

In the DB3K 505, ground defenses as in the attached scenario will not attack low-performance aircraft (think Tucano) with a "WRA 0" automatically. See screenshot for details

![Screenshot 2024-08-11 202719](https://github.com/user-attachments/assets/570c029a-ae4a-4801-9ea0-ea5d0175d503)

[attack0example.zip](https://github.com/user-attachments/files/16576555/attack0example.zip)

### Recommended Fix

Either change the WRA setting of the aircraft in question or see if there's a non-DB reason for the issue .

**Comment by PygmalionOfCyprus** [comment]
This was a non-DB issue and appears to have been fixed in a recent update.
