### ISSUE TITLE
Add French Navy Camcopter S-100

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4888]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5817

### Hypothetical

No

### Name

Camcopter S-100

### Country

France

### Service

Navy

### In Commission

2024

### Other Changes

Started receiving test variants in 2012 but doesn't look like in service with a French Squadron until this year. Used during the Olympics.

### Sources

https://x.com/Defence360/status/1822904735323902222/photo/1
https://www.navalnews.com/naval-news/2024/06/schiebel-opens-facility-in-france/
https://armyrecognition.com/news/navy-news/2024/french-camcopter-s-100-uavs-finally-ready-for-operational-use-after-more-than-10-years-of-testing
https://www.navalnews.com/naval-news/2020/12/four-additional-schiebel-camcopter-s-100-vtol-uav-for-the-french-navy/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
