### ISSUE TITLE
SAM Bn (SA-10b Grumble [S-300PS]) (6x TEL, 4x Bn + Tin Shield B or Big Bird B)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#489]
### DB Selector

DB3K

### DBID to Copy

facility/403/DB3K

### Hypothetical

No

### Name

SAM Bn (SA-10b Grumble [S-300PS]) (6x TEL, 4x Bn + Tin Shield B or Big Bird B)

### Country

Armenia

### Service

Air Force

### In Commission

IOC Uncertain

### Sensors

No Known Changes

### Mounts

No Known Changes

### Loadout Options

No Known Changes

### Other Changes

No Known Changes

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
