### ISSUE TITLE
China, HQ-16C, of high possibility to be an Active Radar Homing missile?

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4892]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4362

### Summary of Changes

- [ ] Add an **Active Radar seeker [sensor 6122]**

If we look at the HQ-16C and HQ-16A/B, we can easily find that the white transparent material part of the HQ-16C warhead is significantly different from that of the A/B, which is likely to replace the larger and more complex old semi-active radar seeker with a lighter active-semi active hybrid radar seeker.

In addition, we note that the 054B does not have any signs of suspected semi-active missile fire control radar, but has the same data link antenna as the 055 and 052d series. The 054A batch IV & V also replaced the original FCR with some kind of phased array, and if we think that the 054b and 054A batch IV & V used the same weapon, then what we originally thought of as "phased array FCR" was just some kind of data link antenna (while having limited ability to illuminate targets for Semi-Active guidance) used to guide active radar missiles.

### Sources

https://twitter.com/Nickatgreat1220/status/1823720586776076796
![image](https://github.com/user-attachments/assets/a9245a07-9f3d-4cf5-952a-835a2bfa673b)
https://www.sinodefenceforum.com/t/054b-new-generation-frigate.8724/page-216
![image](https://github.com/user-attachments/assets/3fe1d322-e189-4c23-98ed-901da8ad035a)
https://www.china-arms.com/2023/10/china-improved-054a-frigate-launches-hq16c-missile/
![image](https://github.com/user-attachments/assets/e9ba16c6-788d-48d3-b3d3-eb8a643552e7)

> In terms of guidance, the HQ-16B/C missile uses a strapdown inertial guidance combined with mid-course command updates and **terminal active/passive radar guidance**. This means the HQ-16B/C has two end-attack modes: **an active radar mode for long-range targets and dealing with saturation attacks and a semi-active mode for medium and short-range targets.** After all, the power of the illuminating radar is much greater than that of the missile’s terminal guidance radar, making them more resistant to jamming and more suitable for striking medium and short-range targets.

**Comment by RickDNiu** [comment]
Not really. C band antenna was integrated on type 346 and 346A (see #5052),

**Comment by LuigiP57** [comment]
The ticket needs more consideration. At the moment, I think it should be possible to increase the number of SARH illuminations for 054B MFR to make the simulation more appropriate.
