### ISSUE TITLE
SAM Plt (SA-17 Grizzly [9K37M1-2 Buk-M1-2]) (3x Plt + Snow Drift + Chair Back B pr Bn, 4x Bn pr Regt)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#490]
### DB Selector

DB3K

### DBID to Copy

facility/192/DB3K

### Hypothetical

No

### Name

SAM Plt (SA-17 Grizzly [9K37M1-2 Buk-M1-2]) (3x Plt + Snow Drift + Chair Back B pr Bn, 4x Bn pr Regt)

### Country

Armenia

### Service

Army

### In Commission

2016

### Sensors

Armenia incorporates the 1S91 SURN Radar with their Buk's. (see destroyed/captured examples from sources)

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
