### ISSUE TITLE
[HIPRI] China, PLAGF, BRE & FD series Rocket & TBM problem in many aspects

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4903]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4469 4470 4471 4472 4473 4475

### Summary of Changes

- [x] Change their Type to **ballistic missile** just like other large long range MLRS rockets. Their current trajectory is cruise missile type which must be an error.
- [x] Increse their speed to **2400kt** just like other typical large long range MLRS rockets. Take ATACMS and PrSM as examples.
- [x] Increse **Weapon 4475 (China BRE10 750mm Rocket/TBM)** range to **325 nm**. Suggestions have been accepted in previous ticket, but I don't see a change.
- [x] Add **Runway** to their valid target lists. They can leave holes in the runway, can't they? I think PLA must be very keen to disable Taiwan's runways by various means.

I have some problems with my previous account (Seems I'm not the only one), so, in light of this major update, I had to create a new account to submit tickets.

### Sources

DB itself.

BREs:
![image](https://github.com/user-attachments/assets/1be27376-8117-4478-a4cc-78871fb6cfb2)
![image](https://github.com/user-attachments/assets/9028d2ec-ab86-47f9-b093-59aec697843f)
ATACMS and PrSM:
![image](https://github.com/user-attachments/assets/1ead68de-015d-4148-9b88-f24669f5aa6d)
![image](https://github.com/user-attachments/assets/bef77ff2-d028-4226-92d2-3da21295fba7)

**Comment by Luigi-II** [comment]
Using [HIPRI] to hi-light that this is a ticket related to China Review

**Comment by Luigi-II** [comment]
I AM SORRY, I'm not arbitrarily asking for "China First", it's just that our DB manager has once said: "Anything wrong with "finished" review items is hi-pri for us".

**Comment by Jkryos** [comment]
Updated DB3K 508.
