### ISSUE TITLE
[HIPRI] China, DF-27, speed and range update in new circumstance

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4904]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4318 4320 4322

### Summary of Changes

- [ ] Change their top speed to **11000kt**. 

There is enough reliable evidence that the vehicle has a top speed of close to Mach 18, the same or similar booster as the DF-26. In the current simulation, The cruising speed performance of the HGV is closely related to its "max range" and "top speed". The current DF-27 is nowhere near the Mach 10 average speed observed in US DoD intelligence. Dude, it's a WAVERIDAER! How can it fly so much slower than the LRHW bipyramid?

Please don't ask me to turn to Tech Support on the CMO forum, that's just a DB problem!

- [ ] extend its max range to **4320nm**

In my tests of the new HGV simulation, when the HGV glides to 60-70% of its distance, its terminal speed is reduced to about 3000 knots. When HGV reaches the max range, its velocity is zero. 

I recall that I quoted US defense reports that estimate the range of the weapon at **5000-8000km**, which probably meant "effective range" and "maximum range". 

ATTENTION, PLEASE! With the new simulation, we are able to achieve the weapon effect that best fits this simulation: with the "maximum range" set at 4320nm/8000km, the DF-27 HGV will get the limit of "effective range" around 2700nm/5000km

### Sources

https://zh.wikipedia.org/wiki/%E4%B8%9C%E9%A3%8E-26%E4%B8%AD%E7%A8%8B%E5%BC%B9%E9%81%93%E5%AF%BC%E5%BC%B9#cite_note-13

> In 2015, when the "China Science and Technology Award" reported "China's first general medium and long range precision strike missile", it said that "it has achieved the technological leap from Mach 12 to Mach 18 of the dynamic aircraft with air steering gear and a major breakthrough in the actual combat capability of strategic weapons", indirectly confirming the penetration capability of the DF-26 with a maximum speed of Mach 18.

https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/china/df-27/
https://media.defense.gov/2021/Nov/03/2002885874/-1/-1/0/2021-CMPR-FINAL.PDF

> Additionally, sources indicate a “longrange” DF-27 ballistic missile is in development. Official PRC military writings indicate this range-class spans 5,000-8,000km, which means the DF-27 could be a new IRBM or ICBM. 

![image](https://github.com/user-attachments/assets/370aa2f1-1024-42a2-9559-fc46a0516541)

Performance:
![663569ca87fbcc1b4083dbfa61321355](https://github.com/user-attachments/assets/56ee2722-7945-432e-bc1f-3fdc9800cb59)
![df9301299e88e61b6b84c293eaadfb3a](https://github.com/user-attachments/assets/44a4a2ff-336f-4c92-9980-c58c1911905b)
You can see the DF-27 has a way slower speed when crusing (And do notice that they are in their "top cruise speed" period)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.

**Comment by Luigi-II** [comment]
@PygmalionOfCyprus Whoops! Found that I only filled in the DBID of HGV, don't forget that booster's range also needs to change! I'm just worried it's going to be like this......

Booster DBID: **Weapon 4317 4319 4321**

**Comment by PygmalionOfCyprus** [comment]
Don't worry, I know how the DB works well enough to handle such mistakes. ;P
