### ISSUE TITLE
HIPRI HQ-9A bug

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4908]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 1225

### Description of Problem

As the picture,HQ-9A has a missile-borne seeker with a 360-degree range.
![image](https://github.com/user-attachments/assets/ce4ee523-c3e2-4906-8627-bf8713c3d4ce)
It's unreasonable.

**Comment by PygmalionOfCyprus** [comment]
Obviously it just has excellent situational awareness. :stuck_out_tongue: 

Handled 508.
