### ISSUE TITLE
HIPRI YJ-18 bug

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4909]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 2867,2868

### Description of Problem

![image](https://github.com/user-attachments/assets/6a8f4b89-f2cf-4a7e-8053-fea969060db2)
![image](https://github.com/user-attachments/assets/2dd5a6da-c89c-4f1c-a886-dea00ff7a1a1)
In the new edition，YJ-18's rocket boosted penetrator can't be realeased.It will continue cruising as a subsonic cruis missle and won't make any damage.

**Comment by PygmalionOfCyprus** [comment]
I don't think this is a DB issue, please post in the Tech Support forum so the devs can take a look at it.

**Comment by ddranidis** [comment]
This was a sim-side issue, it has been fixed for the next public update.
