### ISSUE TITLE
Vehicle (BRDM-2) (Widely Exported)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#491]
### DB Selector

DB3K

### DBID to Copy

facility/2862/DB3K

### Hypothetical

No

### Name

Vehicle (BRDM-2) (Widely Exported)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Changes

### Mounts

Includes anti-tank variant with 9M113 Konkurs missiles

### Other Changes

Includes anti-tank variant.

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces

**Comment by PygmalionOfCyprus** [comment]
Marking wontfix 'cause we're moving to handle individual vehicles as Ground Units, not Facilities, and we've already added the BRDM-2 to the new annex. Again, I know that's small comfort when commercial clients don't have access to Ground Units yet...but hang in there!

**Comment by tbrandon517** [comment]
No worries. I know everything you guys do is worth the wait.
