### ISSUE TITLE
[HIPRI] China, PCL-181 & SH-15 howitzer, should have /52 rather than /39 munition, and ERFB & ERFB-BB-RA for self-used verion

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4911]
### DB Selector

DB3K

### Affected DBID(s)

Facility 4329 4331 4332

### Summary of Changes

- [ ] Replace the /39 HE and Base Bleed with **/52 [Weapon 2245 2246]**
- [ ] Add 155mm ERFB & ERFB-BB-RA PLZ-05 [Weapon 2829 2830] to PCL-181's [Facility 4329] mount. Same caliber, or even same gun.

### Sources

https://en.wikipedia.org/wiki/PCL-181

> The gun has a 52-caliber barrel and is exactly the same as that of the PLZ-05 self-propelled howitzer.

https://www.globalsecurity.org/military/world/china/pcl-181.htm
https://odin.tradoc.army.mil/WEG/Asset/PCL-181_

**Comment by Luigi-II** [comment]
If you are unsure about the ERFB-RA shell, at least replace the /39 mount with /52, this barrel is obviously a /52 caliber
![image](https://github.com/user-attachments/assets/3768b22e-b249-4866-9045-35f015be6b83)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
