### ISSUE TITLE
China, PLAN, Type 071 LPD [986 Simingshan], Laser Weapon System Testbed

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4912]
### DB Selector

DB3K

### DBID to Copy

Ship 2006

### Hypothetical

No

### Name

Type 071 LPD [986 Simingshan], Laser Weapon System Testbed

### Country

China

### Service

PLAN

### Mounts

Add **[China Laser Weapon System]** mount, **10000x** shot, using **Laser Shot 150kW [Weapon 3432]**

### Sources

https://www.sinodefenceforum.com/t/prc-plan-laser-and-rail-gun-development-thread.7906/page-70#post-1107603
![image](https://github.com/user-attachments/assets/ac4fff71-fb4d-40a1-bc6c-4f7175a1a5c0)
![image](https://github.com/user-attachments/assets/3f517e62-903a-43b5-92bb-d729ab2edb06)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
