### ISSUE TITLE
HIPRI China YJ-1000 Correction

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4915]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4461

### Summary of Changes

YJ-1000 should be a laser-guided bomb. It isn't a "kab-1500kr copy" eo-guided bomb.
New loadouts:
J-16 2022:
2×CH-AA-7(PL-12)(optional)+2×PL-8B+2×YJ-1000+1×K/JDC-01A Blue Sky Pod
JH-7A2:
2×PL-8A+2×YJ-1000+1×KG-600 DECM Pod+1+K/JDC-01A Blue Sky Pod

### Sources

![image](https://github.com/user-attachments/assets/3747c28c-3aea-4108-a677-f8d0d255f3b9)
By Norinco

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
