### ISSUE TITLE
HIPRI China H-6K 2022 Version ALCM Loadouts

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4916]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 7135

### Summary of Changes

This kind of H-6K can carry the same quantity of ALCMs as its 2009 version while has 2 more KG-600 DECM Pods.

### Sources

![image](https://github.com/user-attachments/assets/e404558b-3b1c-4cd6-a77c-4d84e9267639)
By JASDF,PLAAF 10th Air Bomber Division(H-6K+H-6H) H-6K Bombers.
It has 6 heavy mount points for ALCMs and 2 for DECM Pods.

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
