### ISSUE TITLE
HIPRI PLAAF WZ-8/BZK-005B(H)/JZ-8F SAR Radar Correction

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4921]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3990

### Summary of Changes

Add ground search(fixed) and ground search(mobile) ability.

### Sources

There isn't too much difference between classifing a target in the sea and on the land for a SAR.
Even Mig-25Rs in 1990s also have this kinds of ability,it won't be difficult for a sonar in late 2010s.
So add ground search ability should be reasonable.

**Comment by PygmalionOfCyprus** [comment]
For some reason the Generic UAV SAR/MTI sensors didn't have land search capability...definitely not intended. Thanks for pointing that out, this will fix it for several other non-China UAVs as well.

Handled 508.
