### ISSUE TITLE
Ship #3100 lack AN/SPY-3 Aegis Command Datalink

### ISSUE THREAD

**Issue by Modzer0** [PygmalionOfCyprus/cmo-db-requests#4924]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3100

### Summary of Changes

Ship lacks AN/SPY-3 Aegis Command Datalink for the RIM-162A ESSM missiles that it carries

### Sources

Ship can't use the Rim-162A ESSM missiles that it carries without the SPY-3  aegis command datalink

**Comment by PygmalionOfCyprus** [comment]
Zumwalts are not AEGIS vessels, so I'm not giving them the datalink. Instead I've swapped their RIMs for the Non-AEGIS type.

Handled 508.
