### ISSUE TITLE
[HIPRI] China, YJ-12B SSM Bty, currently using YJ-12 rather than YJ-12B

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4925]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3177

### Summary of Changes

YJ-12B SSM is already in reviewed DB, but the facility still using YJ-12 as its mount.

### Sources

DB itself

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
