### ISSUE TITLE
HIPRI PLAGF PGL-625【Type 625】SPAAGM Correction

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4926]
### DB Selector

DB3K

### Affected DBID(s)

facitily 4341

### Summary of Changes

Change "35mm/90 single type 90 Burst"which is same as PGL-12 into a new weapon. Maybe it's a mistake？

### Sources

![image](https://github.com/user-attachments/assets/909e003c-0f39-411e-ad60-01bd6992b8f7)
As its name,they use a six-barrel 25mm cannon.

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
