### ISSUE TITLE
[HIPRI] China, H-6K Surface Search Radar, have SAR properties but missing ground search code

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4927]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 7353

### Summary of Changes

Add Ground Search Fixed & Mobile codes

### Sources

DB itself
Same problem as Generic SAR/MTI

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
