### ISSUE TITLE
Add Australian Army Radar (Giraffe AMB 3D) 2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4929]
### DB Selector

DB3K

### DBID to Copy

Facility 1210

### Hypothetical

No

### Name

Radar (Giraffe AMB 3D)

### Country

Australia

### Service

Army

### In Commission

2010

### Number in Service

3x

### Other Changes

These are paired with RBS-70 fire teams, so we could add that to the name lime to the RBS-70 entries like other systems have.

Seems to be modified with IFF but not sure CMO does that just yet
https://www.saab.com/markets/australia/news/stories/2019/australian-army-takes-giraffe-radar-delivery

### Sources

https://www.facebook.com/photo.php?fbid=305005668486104&set=pb.100069300185887.-2207520000&type=3
https://www.facebook.com/photo.php?fbid=556357830017552&set=pb.100069300185887.-2207520000&type=3
https://www.facebook.com/photo.php?fbid=1311608688989921&id=503434203140711&set=a.504951852988946&locale=es_LA
Sipri
Australia	Sweden	2010		3		Giraffe AMB	air search radar	3		2012; 2013	New	SEK550 m ($86 m) 'Land-19 Phase-7A' deal (incl 1 on lease from 2011 until delivery of 3 ordered); for use in Afghanistan	7.5	22.5	22.5

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
