### ISSUE TITLE
AAA Sec (23mm ZU-23-2 x 2)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#493]
### DB Selector

DB3K

### DBID to Copy

facility/2837/DB3K

### Hypothetical

No

### Name

AAA Sec (23mm ZU-23-2 x 2)

### Country

Armenia

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
