### ISSUE TITLE
Update Australian Rapier Blindfire with 1980 in service date and 1988 out of service date

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4931]
### DB Selector

DB3K

### Affected DBID(s)

Facility 1270

### Summary of Changes

In service date 1980
Out of service date 1988- Updated to B1 standard

Add quantity of x10

### Sources

https://aadaa.com.au/air-defence-wiki/air-defence-history/weapon-systems/rapier/

Sipri
Australia	United Kingdom	1977		10		Blindfire	fire control radar	10	?	1979; 1980; 1981	New	Deal worth $20 m; for use with Rapier SAM system	2.5	25	25

**Comment by PygmalionOfCyprus** [comment]
Handled w/ #4932
