### ISSUE TITLE
Add Australian SAM Plt/2 (Rapier FSB1 Blindfire)1988-2006

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4932]
### DB Selector

DB3K

### DBID to Copy

Facility 1139

### Hypothetical

No

### Name

SAM Plt/2 (Rapier FSB1 Blindfire)

### Country

Australia

### Service

Army

### In Commission

1988-2006

### Sources

https://aadaa.com.au/air-defence-wiki/air-defence-history/weapon-systems/rapier/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
