### ISSUE TITLE
Add Australian SAM Plt (RBS-70 Mk1 MANPADS x 3) 1987-2006

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4933]
### DB Selector

DB3K

### DBID to Copy

Facility 4300

### Hypothetical

No

### Name

SAM Plt (RBS-70 Mk1 MANPADS x 3)

### Country

Australia

### Service

Army

### In Commission

1987-2006

### Other Changes

Replaced by Mk3 Bollide

### Sources

https://aadaa.com.au/air-defence-wiki/regimental-history/

Sipri
Australia	Sweden	1985		100	?	RBS-70	portable SAM	100	?	1987	New	$12 m deal (incl 19 launchers)	0.08	8	8

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
