### ISSUE TITLE
China, LPI Radar data based on different platforms

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4935]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 4157 5824 5484 5485 5949

### Summary of Changes

I noticed some discussion on this Github page about the PLA's LPI radar. Here I would like to give some of my views:

First of all, LPI in the game is not just a line of properties code can be implemented, need to be based on a certain database data adjustment to achieve.

Second, although I share DB Manager's doubts about whether China's LPI radar technology can be compared to the advanced technology of the United States. However, it is by no means acceptable to assume that China has not mastered the application of LPI technology, especially when it has a large number of stealth fighters in service.

China has been so tight-lipped about its LPI technology in public that military media around the world have generally not reported on it. Therefore, many so-called "intelligence" will have relatively big misunderstandings. However, when I tried to look at some of the publicly available "academic papers", I could see some hints about Chinese LPI technology.

![image](https://github.com/user-attachments/assets/04069907-879d-47a3-b11d-79d7fbf7b923)
The subject of the above paper, based on my observations, may have to do with a "certain" LPI radar and its "airborne platform." The article was published in 2008, three years before the J-20 made its first flight. What else did I find out? I also noticed that among the references in this article was a 1986 Chinese article on the subject of LPI radar, the Chinese were already interested in LPI radar at this time. This is a year close to the development of the F-22!

![image](https://github.com/user-attachments/assets/47d296b9-fd21-4df8-a0a0-0e692c99be4b)
Almost at the same time as the previous article, this paper shows that it is studying the improvement of the shortcomings of LPI radar. That means they know their product's flaws and are still working on them.

![image](https://github.com/user-attachments/assets/3fd53d6b-095b-4b65-a192-7c9e4d1d954c)
Three years later, in the same year as the J-20's first flight, an article revealed a high interception rate and anti-reconnaissance technology for LPI radars based on "digital arrays" and other technologies. It is known that the F-22 and F-35 do not seem to use digital arrays, of course, we can not assume that the Chinese had relevant applications at the time, right? However, Technology General Iteration.

All above, I now would like to request the followings for simulating the performance of some PLA airborne sensors: 

- [x] For J-20 KLJ-5 [Sensor 4157] : Give it a 200W PP - 45 Gain. Same as AN/APG-77v1.
- [x] For J-10C KLJ-X [Sensor 5824] & J-15 & J-16 AESA [Sensor 5484 5485] : Give them a 160W PP - 45 Gain. Same as AN/APG-81, KF-X AESA and IRFS AESA. This seems to be a typical LPI data template in game.
- [x] For KLJ-7A [Sensor 5949]: Give it a 100W PP - 41 Gain.

However, I also believe that the FC-31/J-35 should have a radar with performance closer to /better than that of the J-10C KLJ-X AESA. If you don't mind:

- [x] Replacing the radar of the current PLAN version of the J-35 [Aircraft 4454] with the KLJ-X [Sensor 5824]. I can't think of any user other than PLAN. This one is definately the "Self-used" version.

### Sources

https://www.forecastinternational.com/archive/disp_pdf.cfm?DACH_RECNO=941
This very "official-looking" document claims that the APG-77 has a power of 20kw. Is it not an LPI radar?

https://www.alljournals.cn/view_abstract.aspx?pcid=26FCEE7E0C06EA5863D91553F1CAF79C693AA6D910AD699D&cid=433C7FE4A4A0ED97&jid=34203DADA4331F4EA34CE4FB68F09569&aid=A858820B206E9F7E6338A2AB03892BCA&yid=67289AFF6305E306
https://www.alljournals.cn/view_abstract.aspx?pcid=26FCEE7E0C06EA5863D91553F1CAF79C693AA6D910AD699D&cid=433C7FE4A4A0ED97&jid=08CF6AFDC4675720&aid=AAEE9865E23C3B5E93626D4337128374&yid=37904DC365DD7266

https://openurl.ebsco.com/EPDB%3Agcd%3A1%3A22317297/detailv2?bquery=low%20probability%20of%20intercept%20radar&page=2
In 2012, their researchers proposed a method for LPI radar energy control that could make LPI radar "stealthier."

https://www.alljournals.cn/view_abstract.aspx?pcid=26FCEE7E0C06EA5863D91553F1CAF79C693AA6D910AD699D&cid=433C7FE4A4A0ED97&jid=34203DADA4331F4EA34CE4FB68F09569&aid=CA8DA797803A447B83EB2F6A82B282F9&yid=9377ED8094509821

**Comment by Luigi-II** [comment]
#4906

**Comment by PygmalionOfCyprus** [comment]
This seems totally fair and well-argued to me. @yUsie108, thoughts?

**Comment by yUsie108** [comment]
It's a reasonable and weighty issue, and I don't think it's wrong. This issue will also be one of the focuses of my study, which is a very meaningful teaching:)

**Comment by PygmalionOfCyprus** [comment]
Also, what happened to you guys' original accounts...?

Did you get suspended or something? All the tickets, comments, etc. you both posted on the old accounts have been 404ed, which is a real shame.

**Comment by PygmalionOfCyprus** [comment]
Handled 508.
