### ISSUE TITLE
Update US U-28A Pilatus name and add laser designator

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4936]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3325

### Summary of Changes

Named Draco so name update could be _U-28A Draco [Pilatus PC-12]_
Add Laser Designator 

### Sources

https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104607/u-28a-draco/
https://www.dvidshub.net/news/458100/hurlburt-field-u-28a-crews-awarded-distinguished-flying-cross-first-ever-draco-community

**Comment by tbrandon517** [comment]
I think all the PC-12s should have a weather/nav radar In the wing pod.

https://images.app.goo.gl/sVoaMwXBME1TAsTq6

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
