### ISSUE TITLE
Fixing Account Suspensions

### ISSUE THREAD

**Issue by PygmalionOfCyprus** [PygmalionOfCyprus/cmo-db-requests#4937]
Several regular contributors to this GitHub seem to have had their accounts suspended/deleted/shadowbanned recently.

I assume that not all of you have been running around violating the site TOS. It looks like Github had some sort of big, poorly-executed ban wave or mistaken auto-mod going rogue, which has attracted enough attention to warrant a pinned post on the r/Github subreddit:

https://www.reddit.com/r/github/comments/1er6iwo/was_your_account_suspended_deleted_or/

Unfortunately, it looks like the solution is just to contact support, wait, and hope for the best. Nevertheless, I would like to encourage anyone affected to **reach out to [Github Support](https://support.github.com/) and try to get those original accounts reinstated**. 

Currently any tickets, comments, etc. posted by affected accounts have been hidden (although, interestingly, you can still see the ones that were assigned to a milestone by viewing the milestone directly) and attempting to view them gets a 404. It looks like we've lost about ~100 tickets or so to this. It would be a shame to have them all lost for good, since I know that represents a lot of work/research! 

Thanks to those of you who persevere and continue to post regardless.

**Comment by Luigi-II** [comment]
It seems that our fellows have been very active in moving in the banned tickets. Great job!

**Comment by RickDNiu** [comment]
Since I could stilll access/appeal I copied a number of issues by @hunterdniu. 
But still one question lingering: 
@PygmalionOfCyprus 
![image](https://github.com/user-attachments/assets/98ad2164-ff2f-4e51-951f-7b3b2c52ec8f)

**Comment by PygmalionOfCyprus** [comment]
Also, if people could just drop a comment here indicating whether they were affected and when (if) they regain account access (as well as what GH support claims was the reason), that would be very helpful for me to track the scope of the issue.

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus Come As a Lightning!

**Comment by PygmalionOfCyprus** [comment]
Looks like most everyone (except @HunterDNiu) is back in the fight now. 👍
