### ISSUE TITLE
PAC-2 GEM+ Range 160km, PAC-3 Max Speed Increase

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#4938]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 642 , weapon 1150 , weapon 3207

### Summary of Changes

_-Increase max range to 160km / 86nmi for PAC-2 GEM+ missile (weapon 642)
-Increase maximum missile speed to mach 5 / 3334kts for both PAC-3 ERINT and PAC-3 MSE (weapon 1150, weapon 3207 respectively)_

![pac-2 max range](https://github.com/user-attachments/assets/92d30c03-a852-41df-8e4f-44b26666c347)
![pac3 speed 2](https://github.com/user-attachments/assets/c9d7afd9-f998-45d9-aaaf-fd1589818ae9)
![pac3 speed](https://github.com/user-attachments/assets/6022bab2-90f9-456c-b228-a56978bb3f1f)

### Sources

https://armyrecognition.com/military-products/army/air-defense-systems/air-defense-vehicles/patriot-pac-3-mse-gem-t-air-defense-missile-system-data
https://www.globalsecurity.org/space/systems/patriot-gem.htm#google_vignette
https://armyrecognition.com/news/army-news/2024/us-announces-acceleration-of-patriot-pac-3-missile-production

**Comment by HunterDNiu** [comment]
F variant is known as the PAC-3 MSE, IOC in 2017. So the paragraph selected in the first pic seems to be confusing/contradictory at least. Or the 35km figure could be for ABM, which is only a practical figure. The source themselves all appear to be primitive and uninformed. 
Dup of #4885.

**Comment by RickDNiu** [comment]
Dup #4885, now in #4950
![image](https://github.com/user-attachments/assets/97bc9174-48d6-4e9d-bd50-64c3e7f62919)

**Comment by sr71xx** [comment]
> Dup #4885, now in #4950 ![image](https://private-user-images.githubusercontent.com/179391537/361242354-97bc9174-48d6-4e9d-bd50-64c3e7f62919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDQxODMsIm5iZiI6MTcyNDYwMzg4MywicGF0aCI6Ii8xNzkzOTE1MzcvMzYxMjQyMzU0LTk3YmM5MTc0LTQ4ZDYtNGU5ZC1iZDUwLTY0YzNlN2Y2MjkxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxNjM4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzFkMjlhYmRkNzI5MGZiYjk4OTYzNzI0NzM0NmUyNDhmYzhkMzM2Y2U2OTliYTdhMGZhNWMzNjIwMWEyZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fLB1-jAMD0QnmRE8VxicTUl_qf_3tie0EZOpwb68WhE)

that is true, armyrecognition confuses pac-3 MIM-104F with the PAC-2 GEM+. But most sources indicate max range for the TVM/SARH GEM+ to have a maximum range of 160km against air breathing targets
