### ISSUE TITLE
Radar (Flat Face A [P-15]) (SA-3)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#494]
### DB Selector

DB3K

### DBID to Copy

facility/1464/DB3K

### Hypothetical

No

### Name

Radar (Flat Face A [P-15]) (SA-3)

### Country

Armenia

### Service

Air Force

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Armenian_Armed_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
