### ISSUE TITLE
Add Jet Fuel Storage to MV Ocean Trader

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#4940]
### DB Selector

DB3K

### Affected DBID(s)

Ship #.2641 MV Ocean Trader, 2015

### Summary of Changes

Add 150,000 Gallons of JP-5 Jet Fuel (408.23t). [1]

### Sources

[1] https://en.wikipedia.org/wiki/MV_Ocean_Trader

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

**Comment by 5th-Domain** [comment]
Excellent, Thanks
