### ISSUE TITLE
Rethink the Radar Signature of J-20B/S and J-35

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4947]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2463 5013 5454 & 4454

### Summary of Changes

It was almost two years ago that my first request of modifying RCS of J-20 was denied. The reason is that we cannot trust so-called "amateur simulations". In the past two days, when I conducted the relevant search of China LPI radar, I also incidentally collected some China's research related to RAS and RAM I think I now have a stronger reason to resubmit my ticket, supported by what I think is stronger evidence.

We all know that advanced military technology is usually highly secret, and the scientific information available to us is more or less different from the state of the art of a country. As far as we know, the Chinese have made great strides in stealth technology over the past 20 years. This should be reflected in the simulation of this game.

However, what we see is that even the J-20B/S variant in the 2020s, as well as the newer J-35, do not have any RCS differences from the early J-20 version from a decade ago. I don't think it's reasonable, not to make improvement when their science and technology booming almost every day.

Still, we can't easily conclude that "the Chinese have surpassed the Americans in the application of stealth technology." However, I do not believe that they have not closed the gap as of today. In this regard, I would like to make the following request:

- [ ] Change the clean /internal loadout RCS of J-20B/S [Aircraft 2463 5013 5454] to 

**A-D Band: -19.9 dBsm Front, -17.7 dBsm Side, -19.9 dbsm Rear**
**E-M Band: -29.9 dBsm Front, -27.7 dBsm Side, -29.9 dbsm Rear**
**Same as F-22 in game. NOT THE MOST ADVANCED US self-used F-35.**

- [ ] Change the clean /internal loadout RCS of J-35 [Aircraft 4454, self-uesd version] to 

**A-D Band: -22.2 dBsm Front, -19.9 dBsm Side, -22.2 dbsm Rear**
**E-M Band: -32.2 dBsm Front, -29.9 dBsm Side, -32.2 dbsm Rear**
**Same as allied version of F-35 in game. NOT THE MOST ADVANCED US self-used F-35.**

The F-22 also had a RAM upgrade, didn't it?
https://theaviationist.com/2022/03/20/second-chrome-f-22-new-shots/
![image](https://github.com/user-attachments/assets/8e5ee082-307f-4bf0-8444-fe556380a782)

Still wanna quote what Dr Michael J Pelosi from AusAirPower said about the J-20 prototype:
https://www.ausairpower.net/APA-2011-03.html
> In conclusion, this study has established through Physical Optics simulation across nine frequency bands, that **no fundamental obstacles** exist in the shaping design of the J-20 prototype, which would preclude its development into a genuine **Very Low Observable design**.

### Sources

For Radar Absorbing Structure:

https://www.mdpi.com/1422-0067/23/18/10424

> SrFe12O19/LSR nanocomposites provide high radar-wave absorption in the frequency band of 11~18 GHz, achieving a minimum reflection loss of **−33 dB** at 11 GHz with an effective absorption bandwidth of 10 GHz.

https://openurl.ebsco.com/EPDB%3Agcd%3A16%3A7480544/detailv2?bquery=radar%20absorbing%20structure&page=1&sid=ebsco:ebsco.com:search

> The optimization analysis indicates that **the sandwich structure** with a two-dimensional (2D) composite lattice core filled with ultra-lightweight sponge may be a better candidate of lightweight RASS than those with cellular foam or hexagonal honeycomb cores. The 2D Kagome lattice is found to outperform the square lattice with respect to radar absorbing.

https://openurl.ebsco.com/EPDB%3Agcd%3A6%3A6090102/detailv2?bquery=radar%20absorbing%20structure&page=1&sid=ebsco:ebsco.com:search

> The maximum absorption of 6 mm‐thick composites is measured to be **−15.98 dB** with 1.5% CNT content. The real part ( ε ′) of permittivity increases from 2.5 to 7 and the imaginary part ( ε ″) of permittivity increases from 0.2 to 1.0 with the increasing content of CNTs. Frequencies, thickness, uniformly distribution of CNT and CNT content are the main factors affecting the RAM properties. The calculated reflection loss, for 12 mm‐thick composites, are **−7 dB, −26 dB, and −34 dB** for 0.5%, 1%, and 1.5% of CNT contents, respectively, and the matching frequency shifts to lower frequencies with the increase of thickness or CNT content, which is in agreement with electromagetic theory and experiment results. POLYM. COMPOS.

The cutting-edge “Metamaterial” RAS research:
https://openurl.ebsco.com/EPDB%3Agcd%3A11%3A30333547/detailv2?bquery=radar%20absorbing%20structure&page=1&sid=ebsco:ebsco.com:search

> Research shows that compared with the absorbing honeycomb, **the reflection loss of the metamaterial absorbing honeycomb is improved by 4.4 dB in 1-10 GHz on average**.

For Radar Absorbing Material:

https://openurl.ebsco.com/EPDB%3Agcd%3A7%3A29549543/detailv2?bquery=radar%20absorbing%20material&page=1

> The proposed method has been proven effective by measuring a prepared multilayer absorbing material, which shows reflectivity of **-30 dB** at a single frequency point and average reflectivity of **-35 dB** in a **broad band**. 

https://openurl.ebsco.com/EPDB%3Agcd%3A13%3A29549517/detailv2?bquery=radar%20absorbing%20material&page=1

Note: There are too many search results on China RAM research, dating back to around Late1990s~Early 2000s, and here are only typical cases. Stealth aircraft generally have a combination of RAS and RAM.

Welcome to use keyword search: https://www.ebsco.com/

**Comment by Luigi-II** [comment]
The category of [Modern Shaping - Lite RAM] should now be represented by KAAN and J-20A

**Comment by Luigi-II** [comment]
I am so jealous of these "former XYZ specialists" who are able to draw "solid" conclusions about a grand topic without having to provide any evidence on Quora. What do you think, my dear friend? @PygmalionOfCyprus 
https://theaviationgeekclub.com/us-navy-operations-specialist-explains-why-china-is-not-yet-able-to-build-a-stealth-fighter-jet-comparable-to-the-f-35/
https://nationalinterest.org/blog/buzz/china-has-serious-f-35-fighter-problem-it-might-never-fix-210811

**Comment by RickDNiu** [comment]
"Although I claim time from the opposition but I'm not opposed."
I've got nothing to say about cybersecurity.

**Comment by RickDNiu** [comment]
I would rather see both possibilities in game.

**Comment by Luigi-II** [comment]
> I would rather see both possibilities in game.

That's just excactly why I keep the older version's and export version's RCS as it is now. What I want, in other word, is the "both possibilities"

**Comment by Siegemiester** [comment]
I think I had a similar discussion about this some time ago about the RCS of the J20 and J35, especially over the egregious fact that the J35 is barely more stealthy than gen 4.5 fighters in game when it is clearly intended to be a VLO design. Or the fact that 40 years later no non-US fighter aircraft can even match the F117, a plane designed with sliderules and who's wreckage has been captured by the chinese in 1999. 

While I'd be satisfied with the early models of the J20 (ie: the 2011 prototype which had a black paintjob) having vastly inferior stealth characteristics, Production models in 2024 should easily be within the ballpark of F22s and F35s if only slightly inferior.

**Comment by Luigi-II** [comment]
> I think I had a similar discussion about this some time ago about the RCS of the J20 and J35, especially over the egregious fact that the J35 is barely more stealthy than gen 4.5 fighters in game when it is clearly intended to be a VLO design. Or the fact that 40 years later no non-US fighter aircraft can even match the F117, a plane designed with sliderules and who's wreckage has been captured by the chinese in 1999.
> 
> While I'd be satisfied with the early models of the J20 (ie: the 2011 prototype which had a black paintjob) having vastly inferior stealth characteristics, Production models in 2024 should easily be within the ballpark of F22s and F35s if only slightly inferior.

In fact, from my literature search of LPI radar, I have found that the Chinese interest in stealth technology and research has been going on for at least 40 years. During this period, they continuously improve their technological level to realize the application of research results. At least judging by the rapid growth of their scientific and technological prowess.

However, due to "doubt" and "confidentiality", we cannot further judge how its application level compares to that of the US.

I'm just trying to request a representative VLO level simulation of the J-20 variant, as well as the self-used version of  J-35. Using TYPICAL SIMULATION of modern VLO stealth fighters IN GAME (only F-22 and Allied version of F-35).

**Comment by Siegemiester** [comment]
> > I think I had a similar discussion about this some time ago about the RCS of the J20 and J35, especially over the egregious fact that the J35 is barely more stealthy than gen 4.5 fighters in game when it is clearly intended to be a VLO design. Or the fact that 40 years later no non-US fighter aircraft can even match the F117, a plane designed with sliderules and who's wreckage has been captured by the chinese in 1999.
> > While I'd be satisfied with the early models of the J20 (ie: the 2011 prototype which had a black paintjob) having vastly inferior stealth characteristics, Production models in 2024 should easily be within the ballpark of F22s and F35s if only slightly inferior.
> 
> In fact, from my literature search of LPI radar, I have found that the Chinese interest in stealth technology and research has been going on for at least 40 years. During this period, they continuously improve their technological level to realize the application of research results. At least judging by the rapid growth of their scientific and technological prowess.
> 
> However, due to "doubt" and "confidentiality", we cannot further judge how its application level compares to that of the US.
> 
> I'm just trying to request a representative VLO level simulation of the J-20 variant, as well as the self-used version of J-35. Using TYPICAL SIMULATION of modern VLO stealth fighters IN GAME (only F-22 and Allied version of F-35).

The whole confidentiality thing is quite the copout. We're supposed to just accept the brochure claims of Lockheed Martin yet we can't take the claims of the chinese defense industry until the hardware is somehow independently corroborated by non-chinese sources.  

In fact for alot of the 'future' hardware in western arsenals specs are liberally extrapolated with no hint of modesty, but for non-western hardware everything needs hard proof before its even considered to be added and quite often its just dismissed because 'oh, its just a concept mockup' as if all those future weapons systems in the western arsenals aren't just that until they actually enter service.

**Comment by Luigi-II** [comment]
Under what circumstances could the J-20's stealth capabilities make the chair of Tactical Air and Land Forces subcommittee "alarmed"?
https://www.airandspaceforces.com/kendall-wittman-budget-adequate-china-hasc/

> But expressing **alarm at the stealthiness of China’s J-20 fighters**, Wittman said he wants to make sure the Air Force’s Next-Generation Air Dominance (NGAD) program “stays on track.” He also voiced support for the CCA concept, but said it must be backed up by a sensor network “from space to Earth” that will be resilient enough to withstand Chinese attempts to disrupt it.

It reminds me of the F-35s in the aggressor squadron:
https://www.f-16.net/forum/viewtopic.php?f=22&t=55497&start=45
https://theaviationgeekclub.com/first-j-20-representing-f-35-aggressor-aircraft-unveiled-at-nellis-afb/
![image](https://github.com/user-attachments/assets/1a15ca26-0c29-42d1-a66d-46dc2b950d32)
![image](https://github.com/user-attachments/assets/052f25d0-3975-490c-bcfd-d8f9f7ca2e39)

**Comment by Luigi-II** [comment]
https://ad-aspi.s3.ap-southeast-2.amazonaws.com/2024-08/ASPIs%20two-decade%20Critical%20Technology%20Tracker_1.pdf?VersionId=1p.Rx9MIuZyK5A5w1SDKIpE2EGNB_H8r
An interesting recent think tank report reveals new dynamics in some key technology research areas. Among them, in the field of material research closely related to stealth technology, China has shown a "drastic" lead. If this advantage was similar to that of other countries, we might suspect that "meaningless" research was padding the numbers, but when a country shows such a lead, we have to think seriously about its strength, don't we?
![image](https://github.com/user-attachments/assets/014a4ef8-1a62-4ef0-875d-6c0442a6c82b)

**Comment by PygmalionOfCyprus** [comment]
Okay. Honestly, I'm convinced -- I agree.

As you say, my initial rejection of the RCS tweak on the J-20s was based on a lack of strong evidence (I still have very little regard for hobbyist RCS simulations being presented as fact) and due to a lot of research on the J-20 in its early development stages. But you've done a good job presenting an updated body of evidence here. I think it's fair to say that the J-20B and any prospective self-used J-35 would fit into the "Modern Shaping, Hev. RAM" category which puts it in the same tier as the F-22 (specific RCSS/IRSS measures notwithstanding).

Even if we're wrong, and the J-20 is in fact less stealthy than we estimate, I think the F-35 aggressors give us cover. If the USAF is wargaming (i.e. doing exercises) w/ F-35-tier aggressors -- even if those end up being "more difficult" than real life -- then we do no harm by applying the same standard to our sim.

Worth addressing this, though:

>The whole confidentiality thing is quite the copout. We're supposed to just accept the brochure claims of Lockheed Martin yet we can't take the claims of the chinese defense industry until the hardware is somehow independently corroborated by non-chinese sources.
>
>In fact for alot of the 'future' hardware in western arsenals specs are liberally extrapolated with no hint of modesty, but for non-western hardware everything needs hard proof before its even considered to be added and quite often its just dismissed because 'oh, its just a concept mockup' as if all those future weapons systems in the western arsenals aren't just that until they actually enter service.

It's frankly disingenuous to pretend like published Chinese equipment specs (export units notwithstanding) and Western brochures are somehow equivalent sources. Western defense contractors exist in a free-market, openly competitive environment and are advertising directly to buyers -- where the consequences of misrepresentation are high. If LM says their equipment is capable of X and in fact it's only capable of X/5 this will be a huge stain on LM for future contracts. In reality -- and we know this for a fact -- such brochures or publicly available data usually drastically understate capabilities.

By contrast, available data from Iran/China/Russia/etc. is rarely intended for internal consumption. The Chinese government can get true equipment specs just fine from CASIC, etc. without blaring it over the internet. They are trying to send a message. When the IRGC parades a bunch of new missiles around and insists that they are all "highly maneuverable," that their shitty Temu EO sensors are "capable of advanced target discrimination", etc. they are not being honest for the purpose of establishing a reputable seller reputation; they are trying to intimidate their opponents. Likewise Russia when it pretends the Su-57 or Su-75 are hyper-capable stealth fighters able to go toe-to-toe with an F-22/F-35. And yes, China does this too. With some exceptions, we generally see OPFOR weapons underperforming their claimed performance in combat, in large part due to this difference in objective re:  data publication.

The exception, of course, are products intended for international export, which are subject to the same pressures mentioned previously; this is why I generally treat export brochures as good, reliable baseline, since it can be safely assumed weapons will not _underperform_ their export numbers (and yes, usually overperform, esp. for a domestic version).

Anyway, handled 509.

**Comment by Luigi-II** [comment]
> Okay. Honestly, I'm convinced -- I agree.
> 
> As you say, my initial rejection of the RCS tweak on the J-20s was based on a lack of strong evidence (I still have very little regard for hobbyist RCS simulations being presented as fact) and due to a lot of research on the J-20 in its early development stages. But you've done a good job presenting an updated body of evidence here. I think it's fair to say that the J-20B and any prospective self-used J-35 would fit into the "Modern Shaping, Hev. RAM" category which puts it in the same tier as the F-22 (specific RCSS/IRSS measures notwithstanding).
> 
> Even if we're wrong, and the J-20 is in fact less stealthy than we estimate, I think the F-35 aggressors give us cover. If the USAF is wargaming (i.e. doing exercises) w/ F-35-tier aggressors -- even if those end up being "more difficult" than real life -- then we do no harm by applying the same standard to our sim.
> 
> Worth addressing this, though:
> 
> > The whole confidentiality thing is quite the copout. We're supposed to just accept the brochure claims of Lockheed Martin yet we can't take the claims of the chinese defense industry until the hardware is somehow independently corroborated by non-chinese sources.
> > In fact for alot of the 'future' hardware in western arsenals specs are liberally extrapolated with no hint of modesty, but for non-western hardware everything needs hard proof before its even considered to be added and quite often its just dismissed because 'oh, its just a concept mockup' as if all those future weapons systems in the western arsenals aren't just that until they actually enter service.
> 
> It's frankly disingenuous to pretend like published Chinese equipment specs (export units notwithstanding) and Western brochures are somehow equivalent sources. Western defense contractors exist in a free-market, openly competitive environment and are advertising directly to buyers -- where the consequences of misrepresentation are high. If LM says their equipment is capable of X and in fact it's only capable of X/5 this will be a huge stain on LM for future contracts. In reality -- and we know this for a fact -- such brochures or publicly available data usually drastically understate capabilities.
> 
> By contrast, available data from Iran/China/Russia/etc. is rarely intended for internal consumption. The Chinese government can get true equipment specs just fine from CASIC, etc. without blaring it over the internet. They are trying to send a message. When the IRGC parades a bunch of new missiles around and insists that they are all "highly maneuverable," that their shitty Temu EO sensors are "capable of advanced target discrimination", etc. they are not being honest for the purpose of establishing a reputable seller reputation; they are trying to intimidate their opponents. Likewise Russia when it pretends the Su-57 or Su-75 are hyper-capable stealth fighters able to go toe-to-toe with an F-22/F-35. And yes, China does this too. With some exceptions, we generally see OPFOR weapons underperforming their claimed performance in combat, in large part due to this difference in objective re: data publication.
> 
> The exception, of course, are products intended for international export, which are subject to the same pressures mentioned previously; this is why I generally treat export brochures as good, reliable baseline, since it can be safely assumed weapons will not _underperform_ their export numbers (and yes, usually overperform, esp. for a domestic version).
> 
> Anyway, handled 509.

At least Aggressor Squadron won't use F-16 to simulate J-20 or J-35. While...
![image](https://github.com/user-attachments/assets/72669f86-83f7-4983-94f0-698b0244d197)
