### ISSUE TITLE
PLAGF/PLAAF Fire Snake 70A Guided Rocket 

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4948]
### DB Selector

DB3K

### Baseline

2597

### Hypothetical

No

### Name

FS-70A Guided Rocket(GR-5)

### Length (m)

2.0

### Width/Span (m)

0.7

### Diameter (m)

0.07

### Weight (kg)

16

### Range (nm)

0.0-3.5

### Warhead

same as generic 70mm rocket

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

2

### Sensors

As it doesn't seem to guide by laser,it's most likely to be guided by INS.

### Weapon Codes

Illuminate at Launch, Terrain Following, Weapon - INS Navigation

### Comments
effect DBIDs:2493,5856,3305,5855,7168

### Sources

![image](https://github.com/user-attachments/assets/b836f874-655e-4f68-8f03-b9a0e05fd2b4)
FS-70A on Zhuhai Air Show,2018.
![image](https://github.com/user-attachments/assets/ef475630-37b3-4dea-ad6b-ceb56fa219f0)
![image](https://github.com/user-attachments/assets/cbc12176-d050-4950-aa3f-54751d468d4f)
PLAGF Z-10 with FS-70A guided rocket.

**Comment by Luigi-II** [comment]
Perhaps there is no rush to throw out so many loadout options at once. We could probably start with some "typical" loadouts, couldn't we?

**Comment by Luigi-II** [comment]
More about PLAGF self-used FS-70A&B:
https://twitter.com/Nickatgreat1220/status/1831272099597701156
https://twitter.com/foolsball/status/1831277047227760827

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
