### ISSUE TITLE
Radar (Flat Face B [P-19])

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#495]
### DB Selector

DB3K

### DBID to Copy

facility/267/DB3K

### Hypothetical

No

### Name

Radar (Flat Face B [P-19])

### Country

Armenia

### Service

Air Force

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
