### ISSUE TITLE
PLA, US, Select countries satellite 

### ISSUE THREAD

**Issue by RickDNiu** [PygmalionOfCyprus/cmo-db-requests#4953]
[US.SBIR (1).xlsx](https://github.com/user-attachments/files/16740765/US.SBIR.1.xlsx)
[Jilin.xlsx](https://github.com/user-attachments/files/16740768/Jilin.xlsx)
[ZY.TH.SJ.SY (1).xlsx](https://github.com/user-attachments/files/16740769/ZY.TH.SJ.SY.1.xlsx)
[GAOFEN.1.xlsx](https://github.com/user-attachments/files/16824248/GAOFEN.1.xlsx)
[China.Extra (1).xlsx](https://github.com/user-attachments/files/16740772/China.Extra.1.xlsx)
[PLASSF.govt (2).xlsx](https://github.com/user-attachments/files/16740773/PLASSF.govt.2.xlsx)
[US.SDA.xlsx](https://github.com/user-attachments/files/16958325/US.SDA.xlsx)
[EO.1.xlsx](https://github.com/user-attachments/files/16958326/EO.1.xlsx)
[PLASSF.yaogan (1).xlsx](https://github.com/user-attachments/files/16958327/PLASSF.yaogan.1.xlsx)
[SAR.gov+com (2).xlsx](https://github.com/user-attachments/files/16958329/SAR.gov%2Bcom.2.xlsx)
[Select.countries.xlsx](https://github.com/user-attachments/files/16958330/Select.countries.xlsx)
[US.commerical.electric.optical.xlsx](https://github.com/user-attachments/files/16958331/US.commerical.electric.optical.xlsx)
[SIGINT.gov+com (1).xlsx](https://github.com/user-attachments/files/16958425/SIGINT.gov%2Bcom.1.xlsx)

**Comment by PygmalionOfCyprus** [comment]
As of 508 we have added (theoretically) every comms/imaging/sensor satellite currently in orbit. These should be covered by that but do please give it a check once it's released!

**Comment by RickDNiu** [comment]
Happy to hear that and I'm willing to turn this into a rolling update/tracker along with sensor/capability(inc sim side)suggestion.
