### ISSUE TITLE
PLAGF Z-21 Loadouts

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4954]
### DB Selector

DB3K

### User(s)

PLAGF Z-21,DBID 7168

### Weapons Carried

-28×FS-70A rockets,2×PL-10
-14×FS-70A rockets,38×70mm rockets,2×PL-10
-14×FS-70A rockets,8×AKD-10,2×PL-10
-14×FS-70A rockets,2×500 liter tank
-8×AKD-10,38×70mm rockets,2×PL-10
-76×70mm rockets,2×PL-10
-8×YJ-9
### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

![image](https://github.com/user-attachments/assets/f70def55-0424-400e-8c29-e418177f3cc1)
![image](https://github.com/user-attachments/assets/390c4dc1-241c-41de-b479-cf333793366d)
![image](https://github.com/user-attachments/assets/bb0e7008-f030-43b1-b936-503f995cc1af)

**Comment by PygmalionOfCyprus** [comment]
Z-21 loadouts were overhauled in 508. FS-70s added 509.
