### ISSUE TITLE
PLAGF Z-10,Z-19 Loadouts 

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4955]
### DB Selector

DB3K

### User(s)

Z-10,DBID 2493,5856
Z-19,DBID 3305,5855

### Weapons Carried

-14×FS-70A rockets，38×70mm rockets
-14×FS-70A rockets，8×AKD-10
-14×FS-70A rockets，8×TY-90
-14×FS-70A rockets，2×500 liter tank
-8×AKD-10，38×70mm rockets
-52×70mm rocket(7×2+14×2)

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Pakistan Z-10ME:
-8×AKD-10,14×FS-70A rockets，DBID 7033

### Sources

![image](https://github.com/user-attachments/assets/b3b3d339-1479-4eab-bc7f-be854ccac110)
![image](https://github.com/user-attachments/assets/617c4026-03ec-45db-93fc-58c871be1a24)

**Comment by PygmalionOfCyprus** [comment]
Z-10/Z-19 loadouts overhauled in 508. Added the FS-70s in 509.
