### ISSUE TITLE
H-6K carries 4x YJ-21 as heavy loadout rather than 4x+2x

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4968]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 7135, Loadout 33914

### Summary of Changes

It should be 4x YJ-21 + 2x KG-600 DECM Pod.

I'm 99.9% sure, you replaced the 2x KG-600 DECM record with the 4x YJ-21 record.

![YJ-21 heavy loadout](https://github.com/user-attachments/assets/a417091d-727b-487c-bca0-a1c454988392)

### Sources

DB itself

**Comment by tbrandon517** [comment]
I'm sure one of the H-6 loadout tickets had a comment and photo about 5 or 6 missiles but it seems to have a 404 error now.

#4698

**Comment by Luigi-II** [comment]
> I'm sure one of the H-6 loadout tickets had a comment and photo about 5 or 6 missiles but it seems to have a 404 error now.

If you mean my ticket about H-6K heavy YJ-21 loadout，it's #4693 and the "5 or 6 missiles" is just DB manager's speculation.

**Comment by PygmalionOfCyprus** [comment]
DB team laughed at this ticket for like 5 minutes in our weekly meeting. Handled 509. 😂

**Comment by Luigi-II** [comment]
> DB team laughed at this ticket for like 5 minutes in our weekly meeting. Handled 509. 😂

More bugs --> More memes --> More fun for boring database work --> More efficiency!
