### ISSUE TITLE
Yu-10 Range Correction

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4971]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3084

### Summary of Changes

Change its range into 21nm(anti-surf+anti-sub)

### Sources

As Yu-10 and Mk48 Mod 5's fuel and kinematic ranges are all the same,their ranges should be both 21nm.
https://www.globalsecurity.org/military/world/china/yu-10.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
