### ISSUE TITLE
Add Jordanian Arty Bty (SR-5 MLRS x 6) 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4974]
### DB Selector

DB3K

### DBID to Copy

Facility 3623

### Hypothetical

No

### Name

Arty Bty (SR-5 MLRS x 6)

### Country

Jordan

### Service

Army

### In Commission

2023

### Sources

https://www.janes.com/osint-insights/defence-news/c4isr/jordanian-military-displays-sr5-mrls-for-kings-silver-jubilee
https://x.com/IdfOsint/status/1815810371996746136
https://armyrecognition.com/news/army-news/army-news-2024/jordan-reveals-secret-acquisition-of-chinese-sr5-and-wm-120-rocket-launchers-in-recent-video

**Comment by yUsie108** [comment]
According to the most widely circulated information, Jordan has not purchased all of the SR-5's available weapons. At present, the only confirmed weapons are 122mm,220mm,300mm rockets, so request to adjust the mount as follows:
4x 300mm BRE2 Rocket
0x 300mm BRE2 Rocket
0x 220mm GR1 King Dragon 60 Rocket
0x 220mm GR1 King Dragon 60 Rocket
20x Fire Dragon 122mm Rocket
0x Fire Dragon 122mm Rocket

**Comment by Luigi-II** [comment]
https://twitter.com/nuwangzi/status/1815976202764521648
![image](https://github.com/user-attachments/assets/cd482761-8110-423b-a368-bc107b75bce5)
![image](https://github.com/user-attachments/assets/5959d582-f0e1-4438-a7b8-7eb22dff41ef)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
