### ISSUE TITLE
Add Jordanian SAM Bty (I-Hawk [Baseline]) 1977

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4976]
### DB Selector

Both

### DBID to Copy

Facility 658

### Hypothetical

No

### Name

SAM Bty (I-Hawk [Baseline])

### Country

Jordan

### Service

Army

### In Commission

1977

### Number in Service

14x

### Other Changes

Ok. Looks like they had the baseline system and B missiles to start so can copy an existing entry. 

Looking into the existing I-Hawk P1 entry to see when upgrades happened.

### Sources

https://www.fordlibrarymuseum.gov/library/document/0019/4520656.pdf
https://www.gao.gov/products/b-165731-3
Sipri Arms DB lines:
Jordan	United States	1976		14		I-HAWK	SAM system	14	?	1977; 1978	New		37.5	525	525
Jordan	United States	1976		1100	?	MIM-23B HAWK	SAM	1100	?	1977; 1978; 1979; 1980	New		0.17	187	187

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
