### ISSUE TITLE
Add Jordanian SAM Sec (SA-14 Gremlin [9K34 Strela-3] MANPADS x3 1987

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4977]
### DB Selector

DB3K

### DBID to Copy

Facility 3885

### Hypothetical

No

### Name

SAM Sec (SA-14 Gremlin [9K34 Strela-3] MANPADS x3

### Country

Jordan

### Service

Army

### In Commission

1987

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP89S01450R000400390001-1.pdf
https://en.wikipedia.org/wiki/9K34_Strela-3
Sipri Line
Jordan	Soviet Union	1985	?	200	?	Strela-3	portable SAM	200	?	1987	New	Acquired after USA refused deal for Stinger portable SAM	0.06	12	12

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
