### ISSUE TITLE
Add Jordanian AAA Plt/2 (23mm ZSU-23-4 Shilka x2) 1981

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4978]
### DB Selector

DB3K

### DBID to Copy

Facility 2748

### Hypothetical

No

### Name

AAA Plt/2 (23mm ZSU-23-4 Shilka x2)

### Country

Jordan

### Service

Army

### In Commission

1981-present

### Sources

https://youtu.be/z8nsuHOrlNo?si=lRkNKFVXkKfOujwE&t=29

Sipri Line
Jordan	Soviet Union	1981		40	?	ZSU-23-4 Shilka	self-propelled AA gun	40	?	1982; 1983	New	Financed by Iraq as reward for Jordanian volunteer unit fighting against Iran	7	280	280

Jordan	Soviet Union	1984	?	8	?	ZSU-23-4 Shilka	self-propelled AA gun	8	?	1986	New		7	56	56

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
