### ISSUE TITLE
Add Jordanian SAM Plt (SA-13 Gopher [9k35 Strela-10]) 1986

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4979]
### DB Selector

DB3K

### DBID to Copy

Facility 1837

### Hypothetical

No

### Name

SAM Plt (SA-13 Gopher [9k35 Strela-10])

### Country

Jordan

### Service

Army

### In Commission

1986-present

### Sources

https://x.com/Harry_Boone/status/1318864615426695168/photo/2
https://www.shutterstock.com/image-photo/royal-tank-museum-amman-jordan-may-2476298655
Sipri Line
Jordan	Soviet Union	1986	?	50	?	Strela-10	mobile SAM system	50	?	1986	New	Possibly financed by Iraq as reward for Jordanian volunteer brigade helping Iraq in Iran-Iraq War	1.25	62.5	62.5

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
