### ISSUE TITLE
Radar (Tin Shield B [5N59S/36D6]) (SA-10b)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#498]
### DB Selector

DB3K

### DBID to Copy

facility/1627/DB3K

### Hypothetical

No

### Name

Radar (Tin Shield B [5N59S/36D6]) (SA-10b)

### Country

Armenia

### Service

Air Force

### In Commission

IOC Uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
