### ISSUE TITLE
Add Jordanian SAM Sec (SA-7b Grail [9K32M Stela-2M] MANPADS x 3) 1982

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4980]
### DB Selector

DB3K

### DBID to Copy

Facility 1965

### Hypothetical

No

### Name

SAM Sec (SA-7b Grail [9K32M Stela-2M] MANPADS x 3)

### Country

Jordan

### Service

Army

### In Commission

1982

### Sources

Jordan	Soviet Union	1981	?	200	?	Strela-2	portable SAM	200	?	1982; 1983	New	Financed by Iraq as reward for Jordanian volunteer unit helping Iraq in Iran-Iraq War	0.04	8	8

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
