### ISSUE TITLE
Add Jordanian SAM Bty/2 (SA-8b Gecko Mod-0 [9K33M2 Romb])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4981]
### DB Selector

DB3K

### DBID to Copy

Facility 1695

### Hypothetical

No

### Name

SAM Bty/2 (SA-8b Gecko Mod-0 [9K33M2 Romb])

### Country

Jordan

### Service

Army

### In Commission

1986

### Sources

https://bulgarianmilitary.com/2023/04/22/jordanian-9m33m2-surface-to-air-missiles-fill-the-ukrainian-stocks/
https://premium.globalsecurity.org/military/world//jordan/army-equipment.htm
https://www.cia.gov/readingroom/docs/CIA-RDP89S01450R000400390001-1.pdf

Sipri Lines
Jordan	Soviet Union	1984		8	?	Osa	mobile SAM system	8	?	1986	New		10	80	80
Jordan	Soviet Union	1984		250	?	9M33	SAM	250	?	1986	New		0.1	25	25

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
