### ISSUE TITLE
Add Jordanian SAM Sec (Redeye MANPADS x4) 1977

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4982]
### DB Selector

Both

### DBID to Copy

Facility 2542

### Hypothetical

No

### Name

SAM Sec (Redeye MANPADS x4)

### Country

Jordan

### Service

Army

### In Commission

1977

### Other Changes

Received these with I-Hawks

### Sources

https://premium.globalsecurity.org/military/world//jordan/army-equipment.htm

Sipri 
Jordan	United States	1975	?	300	?	Redeye	portable SAM	300	?	1977; 1978	New		0.04	12	12

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
