### ISSUE TITLE
Add Jordanian SAM Bty (I-HAWK [P2, TAS]) 2006

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4983]
### DB Selector

DB3K

### DBID to Copy

Facility 739

### Hypothetical

No

### Name

SAM Bty (I-HAWK [P2, TAS]) 

### Country

Jordan

### Service

Air Force

### In Commission

2006

### Other Changes

Received E version missiles in 2006. Bahrain has this configuration and I couldn't find any info on anything being updated with the batteries themselves.

### Sources

Sipri
Jordan	United States	2005		150		MIM-23B HAWK	SAM	150	?	2006; 2007	Second hand	Second-hand; MIM-23E version	0.07	10.2	10.2

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
