### ISSUE TITLE
Add Jordanian Radar (AN/TPS-43E) 1983

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4984]
### DB Selector

DB3K

### DBID to Copy

Facility 146

### Hypothetical

Yes

### Name

Radar (AN/TPS-43E)

### Country

Jordan

### Service

Air Force

### In Commission

1983

### Number in Service

2x

### Sources

https://missiledefenseadvocacy.org/intl_cooperation/jordan/

Sipri Lines
Jordan	United States	1981		2		TPS-43	air search radar	2	?	1982; 1983	New	$13 m deal; part of 'Peace Range' programme: AN/TPS-43E version	9	18	18

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
