### ISSUE TITLE
Add Jordanian Radar (AR-3D)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4985]
### DB Selector

DB3K

### DBID to Copy

Facility 992

### Hypothetical

Yes

### Name

Radar (AR-3D)

### Country

Jordan

### Service

Air Force

### In Commission

198x

### Number in Service

1x

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP89S01450R000400390001-1.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
