### ISSUE TITLE
Add Jordanian AAA Plt/2 (20mm/85 Vulcan M163A1) 1980

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4986]
### DB Selector

DB3K

### DBID to Copy

Facility 643

### Hypothetical

Yes

### Name

Facility 640

### Country

Jordan

### Service

Army

### In Commission

1980-present

### Other Changes

See second - fourth links. They've mounted the turrets on a Cougar MRAP in 2018the 

### Sources

https://en.wikipedia.org/wiki/M163_VADS
https://x.com/Ninja998998/status/1408951268631060483
https://www.reddit.com/r/TankPorn/comments/8hrnpr/jordanian_cougar_6x6_mrap_armed_with_upgraded/
https://www.reddit.com/r/TankPorn/comments/o7mkyd/jordanian_mraps_with_modified_vads_m163_20mm/
Sipri
https://premium.globalsecurity.org/military/world//jordan/army-equipment.htm
Jordan	United States	1974		100		M-163 VADS	self-propelled AA gun	100		1978; 1980	New	$87 m deal (financed by Saudi Arabia)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
