### ISSUE TITLE
Add AAA Plt/2 (20mm/85 Vulcan M167 Towed x2)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4987]
### DB Selector

Both

### DBID to Copy

Facility 643

### Hypothetical

No

### Name

AAA Plt/2 (20mm/85 Vulcan M167 Towed x2) 1976

### Country

Jordan

### Service

Army

### In Commission

1976

### Sources

https://premium.globalsecurity.org/military/world//jordan/army-equipment.htm
Jordan	United States	1975	?	100		M-167 Vulcan	AA gun	100	?	1975; 1976	New	Aid	0.4	40	40

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
