### ISSUE TITLE
Add Jordanian Radar (AN/TPS-77)  2004

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4988]
### DB Selector

DB3K

### DBID to Copy

Facility 155

### Hypothetical

No

### Name

Radar (AN/TPS-77)  2004

### Country

Jordan

### Service

Air Force

### In Commission

2004

### Number in Service

4x

### Sources

Jordan	United States	2002	?	2		TPS-77	air search radar	2		2004	New		11	22	22
Jordan	United States	2016		2		TPS-77	air search radar	2	?	2017; 2018	New	Part of $42 m deal; designation uncertain (reported as 'long-range radar')	11	22	22

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
