### ISSUE TITLE
Add Jordanian SAM Sec (SA-24 Grinch [9k-338 Igla-S] MANPADS x 3)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4990]
### DB Selector

DB3K

### DBID to Copy

Facility 1560

### Hypothetical

Yes

### Name

SAM Sec (SA-24 Grinch [9k-338 Igla-S] MANPADS x2

### Country

Jordan

### Service

Army

### In Commission

2010-Present

### Other Changes

2 Mounted on back of Pickup trucks

### Sources

https://x.com/Harry_Boone/status/1318850805521387520

Sipri Line
Jordan	Russia	2007		1800	?	Igla-S	portable SAM	1800	?	2009; 2010; 2011; 2012	New	For use with 182 Dzhigit launchers on light vehicles	0.08	144	144

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
