### ISSUE TITLE
Add Jordanian Army SAM Sec (SA-18 Grouse [9K38 Igla] MANPADS x 2) 2001

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4991]
### DB Selector

DB3K

### DBID to Copy

Facility 4083

### Hypothetical

Yes

### Name

SAM Sec (SA-18 Grouse [9K38 Igla] MANPADS x 3

### Country

Jordan

### Service

Army

### In Commission

2001

### Sources

Jordan	Russia	2000	?	100	?	Igla	portable SAM	100	?	2001	New		0.08	8	8

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
