### ISSUE TITLE
Add Jordanian Arty Plt (M142 HIMARS) 2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4992]
### DB Selector

DB3K

### DBID to Copy

Facility 3633

### Hypothetical

No

### Name

Arty Plt (M142 HIMARS)

### Country

Jordan

### Service

Army

### In Commission

2012

### Number in Service

12x

### Sources

https://www.centcom.mil/MEDIA/IMAGERY/igphoto/2001662527/
https://www.janes.com/osint-insights/defence-news/weapons/us-approves-gmlrs-rounds-for-jordan
Sipri
Jordan	United States	2010		12		M-142 HIMARS	self-propelled MRL	12		2012	New		1.1	13.2	13.2

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
