### ISSUE TITLE
155mm/52 AGS HVP requires aegis datalink

### ISSUE THREAD

**Issue by Modzer0** [PygmalionOfCyprus/cmo-db-requests#4993]
### DB Selector

DB3K

### Affected DBID(s)

Ship #3100

### Summary of Changes

Ship unable to fire 155mm/52 AGS HVP without one way aegis data link. As the DDG-1000 class is not Aegis suggest switching or adding the datalink to the TSCE command datalink [AN/SPY-3, Two Way] to usable links

### Sources

#3443 - 155mm/52 AGS HVP
COMMS / DATALINKS
Name	Type	Max Range	Channels	Properties
AEGIS Missile Datalink [One-Way]	AEGIS Weapon Link	1400 nm	1	LOS-limited, Receive-only, Secure, UHF Radio

**Comment by PygmalionOfCyprus** [comment]
Which DB are you using? This was fixed in 503 w/ #3893
