### ISSUE TITLE
Add Jordanian Arty Bty (155mm/23 M109A2 Self-Propelled Howitzer x6) 1985

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4995]
### DB Selector

DB3K

### DBID to Copy

Facility 1798

### Hypothetical

Yes

### Name

Arty Bty (155mm/23 M109A2 Self-Propelled Howitzer x6)

### Country

Jordan

### Service

Army

### In Commission

1985

### Sources

https://en.wikipedia.org/wiki/M109_howitzer
https://www.facebook.com/militaryleak/videos/royal-jordanian-artillery-corps/908585139670418/

Sipri
Jordan	United States	1974		30	?	M-109A1 155mm	self-propelled gun	30	?	1975; 1976	New		1.1	33	33
Jordan	United States	1980		78		M-109A1 155mm	self-propelled gun	78	?	1983; 1985	New	$47 m deal; M-109A2 version	1.1	85.8	85.8
Jordan	Netherlands	2010		121		M-109A1 155mm	self-propelled gun	121		2011; 2012	Second hand	Second-hand; M-109A2 version	0.44	53.24	53.24

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
