### ISSUE TITLE
Add Jordanian Arty Bty (203mm/25 M110 Self-Propelled Howitzer x6) 1982

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4996]
### DB Selector

DB3K

### DBID to Copy

Facility 1794

### Hypothetical

Yes

### Name

Arty Bty (203mm/25 M110 Self-Propelled Howitzer x6) 

### Country

Jordan

### Service

Army

### In Commission

1982

### Sources

https://www.facebook.com/militaryleak/videos/royal-jordanian-artillery-corps/908585139670418/
https://en.wikipedia.org/wiki/M110_howitzer
Sipri
Jordan	United States	1980		29		M-110A2 203mm	self-propelled gun	29	?	1982	New	$20 m deal	1.1	31.9	31.9

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
