### ISSUE TITLE
Please consider adding YJ-83K and YJ-91A/YJ-91 (ASM/ARM) to both FC-31 variants...

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#50]
### DB Selector

DB3K

### User(s)

#2917 & #4454

### Weapons Carried

Please consider adding the following loadouts to both variants of the FC-31 (#2917 & #4454 in DB):

1. A Short-Range Loadout of: 4x *EXTERNAL* YJ-83K's (#2137 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB)

2. A Long-Range Loadout of: 2x *EXTERNAL* YJ-83K's (#2137 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB) + 2x *EXTERNAL* 1700L Drop Tank (#1533 in DB)

3. A Short-Range Loadout of: 4x *EXTERNAL* YJ-91A's (#2874 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB)

4. A Long-Range Loadout of: 2x *EXTERNAL* YJ-91A's (#2874 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB) + 2x *EXTERNAL* 1700L Drop Tank (#1533 in DB)

5. A Short-Range Loadout of: 4x *EXTERNAL* YJ-91 ARM's (#2875 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Unknown, but if someone knows a formula I can use to calculate the range from the take-off weight and fuel load, it would be greatly appreciated...

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

1. The following detailed analysis of the "newest" version of the FC-31 points to the existence of 6 External hardpoints *in addition to* the two Internal weapon bays with 2 Internal hardpoints in each of the bays. The 1st article identifies the YJ-83K and the YJ-91A/YJ-91 as possible armaments for the External hardpoints. Once you do the math for the maximum take-off weight minus the weight of the ordinance and fuel, the above suggested loadouts seem to be plausible. 

2. I also found corroborating evidence of the existence of the 6 External hardpoints in the 2nd article provided. Please let me know if you need any additional information...

### Sources

1. http://fullafterburner.weebly.com/aerospace/analysis-of-the-latest-prototype-of-shenyang-j-31
2. https://www.globaldefensecorp.com/2020/06/30/shenyang-fc-31-j-31-a-copycat-f-35-through-cyber-espionage/

**Comment by PygmalionOfCyprus** [comment]
Added 495.
