### ISSUE TITLE
Armored Plt (T-55 MBT x 4)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#500]
### DB Selector

DB3K

### DBID to Copy

facility/812/DB3K

### Hypothetical

No

### Name

Armored Plt (T-55 MBT x 4)

### Country

Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

Used for indirect fire support

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces

**Comment by PygmalionOfCyprus** [comment]
Added 494.
