### ISSUE TITLE
China, Y-9LG Radar Jammer

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5002]
### DB Selector

DB3K

### Baseline

sensor 6491

### Hypothetical

No

### Name

Y-9LG Radar Jammer

### Sensor Generation

Late 2010s

### Range (nm)

-

### Sensor Capabilities

-

### Search/Track Frequencies

A Band (30-250 MHz) [Old P Band (HF)] 100-300 cm, B Band (250-500 MHz) [Old P Band (VHF)] 60-100 cm, C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm, D Band (1-2 GHz) [Old L Band] 15-30 cm, E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm, G Band (4-6 GHz) [Old C Band] 5-7.5 cm, H Band (6-8 GHz) [Old C Band] 3.75-5 cm, I Band (8-10 GHz) [Old X Band] 3-3.75 cm, J Band (10-20 GHz) [Old X Band] 1.5-3 cm

### Processing Gain/Loss (dB)

16.7 (same as other ECM in DB) 

### Peak Power (W)

150000

### Comments

A radar jammer with the same shape as the KJ-200 radar antenna. Give it the same power as the KJ-200 radar in the database (150kW)

### Sources

https://twitter.com/RupprechtDeino/status/1829202876939546960
https://chinese-military-aviation.blogspot.com/p/surveillance-aircraft-ii.html
![image](https://github.com/user-attachments/assets/00b6cf56-6657-40a4-99c1-b7e2af6f235e)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
