### ISSUE TITLE
China, PLAAF, Y-9LG [GX13] Radar Jamming Aircraft

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5003]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4204

### Hypothetical

No

### Name

Y-9LG Cub [GX-13]

### Country

China

### Service

PLAAF

### In Commission

2024

### Other Changes

- [ ] Replace the Generic ECM with Y-9LG Radar Jammer
- [ ] Replace the ELINT with Generic SIGINT Early 2020s (COMINT & ELINT)
- [ ] Add a DECM 2010s
- [ ] Add a Generic Surface Search Radar 200nm (or a copy entry based on this but with 2020s tech?)

### Sources

#5002

**Comment by Luigi-II** [comment]
https://www.janes.com/osint-insights/defence-news/defence/chinese-y-9lg-electronic-warfare-aircraft-breaks-cover
![image](https://github.com/user-attachments/assets/8936b1b0-fc3e-42a1-ae52-9d799b4d2e38)
Curiously, now that Janes has called it an EW Jamming aircraft, it still labels the beam antenna as "Radar." Other tags don't show any problem (COMINT, ELINT, SAR/GMTI, etc.), maybe it's a labeling error?

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
