### ISSUE TITLE
China, Y-9G, should have a DECM

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5004]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4204

### Summary of Changes

- [ ] Add a DECM 2010s.

### Sources

Starting from the Y-9JB, they all have a DECM antenna on their vertical tail:
![image](https://github.com/user-attachments/assets/16ab5fb2-fc32-4730-b281-f1218af5e9c0)
![image](https://github.com/user-attachments/assets/f05ee82e-22a0-4163-b7d0-944f1bafe948)
![image](https://github.com/user-attachments/assets/bc6db62d-fa8b-4239-b952-62efe4133940)
![image](https://github.com/user-attachments/assets/410e978b-2d3b-4d3c-8817-af285a9191b3)

**Comment by Luigi-II** [comment]
![image](https://github.com/user-attachments/assets/5a85f94a-6aef-45e0-a85e-86edbdff7afb)
So, the device on the vertical tail should be some kind of ESM? However, as an EW aircraft, it would make sense to have DECM.

**Comment by PygmalionOfCyprus** [comment]
I don't know that the Y-9G has a "dedicated" DECM, I think that's probably just handled by its onboard EW suite. I'm gonna add the Y-9LG though.
