### ISSUE TITLE
Arty Bty (Lynx MLRS x 3)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#501]
### DB Selector

DB3K

### DBID to Copy

facility/3176/DB3K

### Hypothetical

No

### Name

Arty Bty (Lynx MLRS x 3)

### Country

Azerbaijan

### Service

Army

### In Commission

IOC Uncertain

### Sensors

No Change

### Mounts

Remove EXTRA and Delilah

### Loadout Options

Remove EXTRA and Delilah

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces#Artillery

**Comment by PygmalionOfCyprus** [comment]
Added 494.
