### ISSUE TITLE
Possible phishing attempt using the cmo-db-requests list  

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#5010]
### DB Selector

DB3K

### Affected DBID(s)

N/A

### Description of Problem

I'm sure this is **not** the place to report this, but I don't know where to report it.  I just received two emails from "Robert Santos Freir" that appear to have been sent to the cmo-db-requests list.  It reads:
_hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd**_X**
password: changeme
when you installing it, you need to place a check in install to path and select usx_
(Note: I've added the bold _X to the address so no one accidently clicks on the link.  If you want to go to the link, delete the "_X"
I'm not sure what I received this email, nor does it appear to be related to anything I have posted, nor did my search of the users reveal a "Robert Santos Freir"  I'm not sure what this email refers to, nor do I have any idea what the link does.  In any case, you might want to determine if someone is spaming the users of the list for nefarious purposes.

**Comment by PygmalionOfCyprus** [comment]
Yeah, I've caught him a couple times. I think Github is on top of it; we reported him and most of their comments got wiped.

Fortunately I don't think it's quite so nefarious as somebody directly targeting the CMO community. To repost what I wrote in another thread:

>I doubt it's targeting the CMO page specifically. I think it probably just goes through public Github repos with open issues and a certain amount of traffic and targets them. The fake comment it posts doesn't really make sense on our particular page, where issues are more like unit requests, but it would make more sense on a "normal" repo where issues are actually reporting bugs and problems.
>
>If you were posting an issue like "hey the app freezes when I do X, what should I do" and someone responded "To fix your trouble download this fix, I see it in another issue" etc. etc. you might be more tempted.
>
>Just comes with the territory of being a big repo, I guess. I'll consider it a backhanded compliment. Report them to GH when you see 'em. Now if only they would ban the actual spambots instead of our dutiful contributors...
