### ISSUE TITLE
Add Sudanese Mig-21M (1971-2000)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5014]
### DB Selector

Both

### DBID to Copy

Aircraft 2728

### Hypothetical

No

### Name

Mig-21M Fishbed J

### Country

Sudan

### Service

Airforce

### In Commission

1971-2000

### Number in Service

16x

### Mounts

same

### Loadout Options

same

### Sources

Sudan	Soviet Union	1968		22	?	MiG-21PFM	fighter aircraft	22	?	1970	New	Incl 4 MiG-21U trainer version	10	220	220

Tom Cooper ACIG  Sudan Civil war since 1955

Sipri ids them as PFM. Probably not. I'd go with Cooper and everybody else in ME/AF was getting these.
Sudan	Soviet Union	1968		22	?	MiG-21PFM	fighter aircraft	22	?	1970	New	Incl 4 MiG-21U trainer version	10	220	220

**Comment by bostonmyk** [comment]
Cooper Info
[Sudan, Civil War since 1955 - www.acig.org_files.zip](https://github.com/user-attachments/files/16850463/Sudan.Civil.War.since.1955.-.www.acig.org_files.zip)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
