### ISSUE TITLE
Add Sudanese SAM Bn (SA-2b Guideline [S-75 Dvina]) 1971-

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5015]
### DB Selector

Both

### DBID to Copy

Facility 1774

### Hypothetical

No

### Name

SAM Bn (SA-2b Guideline [S-75 Dvina])

### Country

Sudan

### Service

Air Force

### In Commission

1971

### Number in Service

5x, +3

### Sources

https://en.topwar.ru/245050-sluzhba-i-boevoe-primenenie-sovetskih-i-kitajskih-zrk-sa-75-dvina.html
https://www.ospreyflightsolutions.com/sudan-conflict-ospreys-analysis/
Sudan	Soviet Union	1970		5	?	S-75 Dvina	SAM system	5	?	1971	Second hand		7.15	35.74	35.74
Sudan	Egypt	1984		3	?	S-75 Dvina	SAM system	3	?	1984	Second hand	Second-hand; aid	7.15	21.44	21.44

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
