### ISSUE TITLE
Add Sudanese SAM Sec (SA-7b Grail [9K32M Stela-2M] MANPADS x 3) 1981

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5016]
### DB Selector

DB3K

### DBID to Copy

Facility 2842

### Hypothetical

No

### Name

SAM Sec (SA-7b Grail [9K32M Stela-2M] MANPADS x 3)

### Country

Sudan

### Service

Army

### In Commission

1981-Present

### Sources

Sudan	Soviet Union	1980	?	100	?	Strela-2	portable SAM	100	?	1981	New	Probably incl Strela-2M (SA-7b) version	0.04	4	4

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
