### ISSUE TITLE
Add Sudanese AAA Bty (100mm KS-19 x6, Fire Can FCR]) 1970

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5017]
### DB Selector

Both

### DBID to Copy

Facility 1885

### Hypothetical

No

### Name

AAA Bty (100mm KS-19 x6, Fire Can FCR])

### Country

Sudan

### Service

Army

### In Commission

1970

### Sources

Sudan	Soviet Union	1969	?	10	?	KS-19 100mm	AA gun	10	?	1970	Second hand		0.24	2.4	2.4
Sudan	Soviet Union	1969	?	6	?	SON-9	fire control radar	6	?	1970	Second hand	Fire control for KS-12 85mm and KS-19 100mm anti aircraft guns	0.24	1.44	1.44

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
