### ISSUE TITLE
Update Sudan F-7B in service date to 1987

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5018]
### DB Selector

DB3K

### Affected DBID(s)

aircraft 3762

### Summary of Changes

Update in service date to 1987

### Sources

Sudan	China	1986	?	12	?	J-7	fighter aircraft	12	?	1987	New	F-7B version; incl 2 FT-7; no. could be 15	9	108	108
Sudan	China	1995	?	6	?	J-7	fighter aircraft	6	?	1997	New	F-7B version; no. could be 7; status uncertain	9	54	54

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
