### ISSUE TITLE
Arty Bty (RM-70 MLRS x 6) (BM-21 Grad Copy)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#502]
### DB Selector

DB3K

### DBID to Copy

facility/1963/DB3K

### Hypothetical

No

### Name

Arty Bty (RM-70 MLRS x 6) (BM-21 Grad Copy)

### Country

Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces#Artillery

**Comment by PygmalionOfCyprus** [comment]
Added 494.
