### ISSUE TITLE
Add Sudanese MI-25 Hind D

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5020]
### DB Selector

DB3K

### DBID to Copy

Aircraft 1381

### Hypothetical

No

### Name

Mi-25 Hind D

### Country

Sudan

### Service

Air Force

### In Commission

1989

### Number in Service

2x,+1

### Sources

Sudan	Libya	1988	?	2	?	Mi-24D/Mi-25	combat helicopter	2	?	1989	Second hand	Second-hand	3.3	6.6	6.6
Sudan	Kyrgyzstan	1994	?	1	?	Mi-24D/Mi-25	combat helicopter	1	?	1995	Second hand	Ex-Kyrgiz; no. could be 4	3.3	3.3	3.3

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
