### ISSUE TITLE
Add Sudanese F-5E 1984

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5021]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2241

### Hypothetical

No

### Name

F-5E Tiger II

### Country

Sudan

### Service

Airforce

### In Commission

1984

### Number in Service

10x

### Loadout Options

Used Aim-9J loadout 

### Other Changes

Very murky on what was received and survived. Sipri reports 12 but only received 4.
Tom Cooper's Sudanese history reports 4 crashed so likely received them.

### Sources

https://www.joebaugher.com/usaf_fighters/f5_42.html
https://www.airhistory.net/photo/298140/208

Sudan	United States	1980		4	?	F-5E Tiger-2	FGA aircraft	4		1982; 1984	New	Original order for 12 reduced to 4 for financial reasons; incl 2 F-5F version	10.5	42	42
Sudan	United States	1980	?	10	?	AIM-9J/P Sidewinder	SRAAM	10	?	1982	New	For F-5E combat aircraft	0.09	0.9	0.9

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
