### ISSUE TITLE
Add Sudanese Art Plt (WS-1B MLRS) 2014

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5022]
### DB Selector

DB3K

### DBID to Copy

Facility 1729

### Hypothetical

No

### Name

Art Plt (WS-1B MLRS)

### Country

Sudan

### Service

Army

### In Commission

2014

### Number in Service

6x, -1

### Sources

https://www.oryxspioenkop.com/2023/04/from-conflict-to-conflict-sudans.html
https://x.com/CalibreObscura/status/1649381578244513796
https://armyrecognition.com/news/army-news/army-news-2024/sudanese-rebels-capture-chinese-ws-1b-and-north-korean-bm-11-rocket-launchers-from-the-sudanese-armed-forces
Sudan	China	2009	?	6		WS-1B 302mm	self-propelled MRL	6	?	2014	New		0.9	5.4	5.4

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
