### ISSUE TITLE
Add Sudanese SAM Bty/2 (SA-8b Gecko Mod-0 [9K33M2 Romb]) 2014

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5023]
### DB Selector

DB3K

### DBID to Copy

Facility 1702

### Hypothetical

Yes

### Name

SAM Bty/2 (SA-8b Gecko Mod-0 [9K33M2 Romb])

### Country

Sudan

### Service

Army

### In Commission

2014

### Number in Service

x4

### Other Changes

 still in service

### Sources

https://x.com/africaken1/status/817772003398651904
https://www.oryxspioenkop.com/2023/04/from-conflict-to-conflict-sudans.html
https://www.ospreyflightsolutions.com/sudan-conflict-ospreys-analysis/
https://en.wikipedia.org/wiki/9K33_Osa

Sipri

Sudan	unknown supplier(s)	2013	?	4	?	Osa	mobile SAM system	4	?	2014	Second hand	Second-hand but possibly modernized before delivery	4	16	16
Sudan	unknown supplier(s)	2013	?	120	?	9M33	SAM	120	?	2014	Second hand	Probably second-hand but possibly modernized before delivery	0.04	4.8	4.8

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
