### ISSUE TITLE
Add Sudanese Mig-17PF Fresco D 1970

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5024]
### DB Selector

Both

### DBID to Copy

Aircraft 1144

### Hypothetical

No

### Name

Mig-17PF Fresco D

### Country

Sudan

### Service

Airforce

### In Commission

1970-1990?

### Number in Service

16x

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP83S00854R000200170003-4.pdf

Sudan	China	1969	?	16	?	MiG-17PF	fighter aircraft	16	?	1970	New		4	64	64

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
