### ISSUE TITLE
Add Algerian Mi-24a Hind A 1980-1992

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5025]
### DB Selector

DB3K

### DBID to Copy

Aircraft 5920

### Hypothetical

No

### Name

Mi-24A Hind A

### Country

Algeria

### Service

Air Force

### In Commission

1980-1992

### Number in Service

6x

### Sources

https://x.com/DWatsonfdz/status/1529526129060610049

Algeria	Soviet Union	1977	?	6	?	Mi-24A	combat helicopter	6	?	1979	Second hand	Second-hand	2.65	15.89	15.89

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
