### ISSUE TITLE
Add Algerian Mi-24V Hind E 1999

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5027]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2637

### Hypothetical

Yes

### Name

Mi-24V Hind E

### Country

Algeria

### Service

Air Force

### In Commission

1999

### Number in Service

x28

### Other Changes

ex Ukrainian, Replaced Mi-25

### Sources

https://x.com/DWatsonfdz/status/1529526153664516098

Algeria	Ukraine	2001	?	16		Mi-24V/Mi-35	combat helicopter	16		2001; 2002	Second hand	Second-hand	3.4	54.4	54.4
Algeria	Ukraine	1997	?	28	?	Mi-24V/Mi-35	combat helicopter	28		1998; 1999	Second hand	Second-hand	3.4	95.2	95.2

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
