### ISSUE TITLE
Add Algerian Radar (Flat Face E [36N6E Kasta 2E2]) 2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5028]
### DB Selector

DB3K

### DBID to Copy

Facility 2420

### Hypothetical

No

### Name

Radar (Flat Face E [36N6E Kasta 2E2 ) 

### Country

Algeria

### Service

Air Force

### In Commission

2012

### Number in Service

5x

### Other Changes

For use with Pantsir

### Sources

https://x.com/DWatsonfdz/status/1370083595134586880

Algeria	Russia	2006	?	5	?	Kasta-2E2	air search radar	5	?	2012; 2013; 2014; 2015; 2016	New	For use with Pantsyr AD systems	9	45	45

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
