### ISSUE TITLE
Add Algerian Radar (Tall King A [P-14]) 1983

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5029]
### DB Selector

DB3K

### DBID to Copy

Facility 2245

### Hypothetical

No

### Name

Radar (Tall King A [P-14])

### Country

Algeria

### Service

Air Force

### In Commission

1983

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP91T00712R000200410008-9.pdf
https://www.cia.gov/readingroom/docs/CIA-RDP85T00840R000102850001-2.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
