### ISSUE TITLE
Addition and update: PLA Special Missions/Transport Aircraft[WIP]

### ISSUE THREAD

**Issue by RickDNiu** [PygmalionOfCyprus/cmo-db-requests#5035]
### - [x] Y-8, 1981, Class I platform baseline
An-12B copy, numerous weight reduction measures (heating system removed, thinner fuel tank etc.) due to inferior propulsion. MTOW 61 ton, max payload 15 ton, "5 tons at Lhasa Gonggar Airport". 5000km range. 
4x WS-6 4 blade turboprop engine, 4500hp each. 
Does not have pressurization initially. Aft gun removed for post 1986 production. 5 person crew. 

- [x] Y-8A, 1985
Based on Class I platform, for transporting Blackhawk to Tibet. 

---

- [x] Y-8X, PLAN, 1985, 4x
Based on Class I platform, Aft cargo door & gun removed. Surface search radar from Canada. IR ASW sensor, sonobuoy launcher, rescue boat. 

- [x] Y-8CB, Gaoxin (GX) 1, 2003, 3x

Based on Class I platform, unpressurized. 
EW and SAR antenna prob from Tu-154M/D II, can do ESM and some ECM, probably similar role to EP-3, which was involved in the Hainan Island in 2001. 

- [x] Y-8J, 1998

Y-8X upgrade, Skymaster radar

- [x] Y-8JB, GX2, PLAN?

GX1 similar, larger nose dome. probably similar role to Tu-16R. 

---

- [x] Y-8E, 

Based on Class I platform. WZ-5 UAV carrier. 

Y-8CA, 079
Fighter radar testbed. 

Y-8H, 1992
Mapping

---

Y-8B, 1985?
Based on Class I platform. Civilian, half pressurized. 

Y-8D (I and II), 
Civilian export. 

Y-8F, 1994
Based on Class I platform. Civilian, half pressurized. Known for transporting livestock (sheep). 

- Y-8F-100, 1996
For China Post. All weather flight capable. International standard pallets. 

- Y-8FDII
For export. 

---

### - [x] Y-8C, 1993, Class II platform baseline

Fully pressurized (pressurization tech from Lockheed Martin). Aft gun bay removed. 
Fuel tank below cargo bay removed, 4000km range (suggested that special missions may include internal auxiliary tanks). 
WS-6B. 
Up to 20 ton payload. All weather flight capable. 

---

- [x] Y-8G, YG-8, GX 3

Based on Class II platform. OECM, side looking and vertical stabilizer-top antennas. EC-130 similar. 

- [x] Y-8T, GX 4

ACP, top and belly comms antennas. EP-3B/EP-6B similar. 

- [x] Y-8XZ, GX7

Based on Class II platform. Psyops, EC-130J similar. 

- [x] Y-8CH, PLAN
ASW, probably similar role to P-3C. 

---

- [x] Y-8CI, 

Based on Class II platform, fully pressurized, civilian for export. Some imported equipment. 

- [x] Y-8F-200, 1997

Based on Class II platform, Civilian transport. 15 ton. 

- [x] Y-8F-400, 2002

Redesigned cockpit, new avionics, 3 person crew. 

---

### - [x] Y-9, aka Y-8F-600, Class III platform baseline, 2005
Based on Y-8F-400, glass cockpit, two person crew. 
4x WJ-6C, six blade turboprop, 5100hp. Improved high temperature and high-altitude performance. Improved fuel tank. 
MTOW 65t, max payload 20t, "15t at Lhasa Gonggar Airport". 23t fuel. Larger cargo bay. 6100km range

---

- [x] KJ-200, Y-8W, GX 5, 2009
Balance beam, vertical stabilizer antennas on GX 3, body antennas on GX4, new nose antenna. 

- [x] ZDK-03
Rotodome. Lost to Balance beam. Export. 

- [x] KQ-200, Y-8Q, GX6

ASW, 

- [x] Y-9TZ, GX8

ELINT, GX2 replacement, EP-3 similar, naval intel. Top DL antenna. 

- [x] Y-9XZ, GX9. 

Basically Y-8XZ but class III platform. Improved cyberops against adversarial civil networks, targeting Taiwan. 

- [x] Y-9G, GX11

OECM, Y-8G/GX3 replacement. 

- [x] Y-9Z, GX12, PLAAF

ELINT. 

- [x] GX-13?

- [ ] Y-9Q, GX14

ASW

- [ ] GX-14?

- [ ] KJ-500, GX 10, K/JE04

- [x] KJ-700[^KJ-700], Gaoxin 16

- Baseline: KJ-500, Y-9, with improved propulsion and boom refueling. 

> The more "tactical" variant, succeeding KJ-500. Mentioned "new engine" (WJ-10?, see KJ-600) in the illustration showing 4x 6 blade turboprops. New engine would also contribute to better electricity generation capacity. 

- Sensors: 

1. Weather/navigation radar
2. Long range IRST

> Illustration says "Stealth aircraft and BM detection capable", may need 2 separate sensors (one for space object and one for normal IRST with range and other sim side constraints). Also said to have EO and "powerful" laser rangefinder with multiple windows spotted on the nose turret. 

3. "Air/surface search radar", 3x faces rotodome. 

> Need more work on radar. For scan interval use 1/3 of normal.  

4. "Dual mode, dual band digital array AESA radar", one conformal on each side. 

> Illustration says "Stealth aircraft and BM detection capable", probably long range low band. Need more work. May also support datalink and CEC. 

5. Aft looking radar and wingtip radar. 

> Purpose and specs unknown. Need more work. May also support datalink and CEC. May have ELINT/ECM capability. 

6?. Should have ELINT/DECM but no clear indication of auxiliary antenna. May be integrated, see above. 

7. Satcom and datalink antenna, atop the dome. 
8. GNSS antenna. 

---

- [x] KJ-3000[^KJ-3000], Y-20 AEW [WIP]

> The more "strategic" variant, succeeding KJ-2000 (based on Il-76). Landing gear extended to accommodate belly antenna. 

- Sensors: (provisional)

1. Weather, MAWS, RWR (original). 
2. Dual band AESA rotodome, 2x faces. 
3. Side looking antennas [WIP]. 

> Probably similar to the "Dual mode, dual band digital array AESA radar" on KJ-700. 

4. Top dome/conformal antenna [WIP]. 

5. Belly dome/conformal antenna [WIP]. 

6. ELINT/DECM [WIP]. 

---

- [x] KJ-600

> Carrier AEW. 2x FWJ-6C turboprop, cannot be launched via ski jump, altitude limited, to be replaced by WJ-10. 

[^KJ-700]: https://chinese-military-aviation.blogspot.com/p/surveillance-aircraft-ii.html; https://x.com/louischeung_hk/status/1821029458792624342; https://en.wikipedia.org/wiki/Shaanxi_Y-9; https://x.com/RupprechtDeino/status/1736296335668646215; https://theaviationist.com/2024/06/22/kj-700/
[^KJ-3000]: https://chinese-military-aviation.blogspot.com/p/surveillance-aircraft-ii.html;

**Comment by RickDNiu** [comment]
#4876 surrogate

**Comment by RickDNiu** [comment]
#2903 surrogate

**Comment by RickDNiu** [comment]
Also may add a WJ-10 Y-9, as a simple transport and as baseline for KJ-700 and other potential future stuff. Capability should be on par with C-130.

**Comment by Jkryos** [comment]
Added DB3K 509 and prior. I left 3 unmarked which needs more research, they seem to be platforms commonly confused for one another and I would like a more solid source.

**Comment by Luigi-II** [comment]
> "Air/surface search radar", 3x faces rotodome.

> > Need more work on radar. For scan interval use 1/3 of normal.

KJ-700 is definitely not a 3-phased dome:
https://www.google.com.hk/search?newwindow=1&sca_esv=339a018dea4bc811&rlz=1C1MFPQ_zh-CNUS1068CN1076&q=KJ-700&udm=2&fbs=AEQNm0AaBOazvTRM_Uafu9eNJJzCjPEAP5HX2BE31zy5nlFpWvns3PnbKLxkXEhI71m1WxvHeTVMvW1e5dFpf7LkrSPneJ7MnTowJmKQkE00SKZ4fjsJuUghC_NJfPRR-0kl-tJX_Ys_UHmKEXHdRnrbUcg83w69BOKXKuBdh_EsebtZWv_exJ8&sa=X&ved=2ahUKEwi20cPw8ZaJAxUOD0QIHbpMCKMQtKgLegQIEhAB&biw=1707&bih=979&dpr=1.5#vhid=R142ec07j1oyRM&vssid=mosaic
![image](https://github.com/user-attachments/assets/12e0d7fb-5913-4774-8ff9-49ed2e67311f)
https://x.com/FaySue6/status/1806858864060498070
![image](https://github.com/user-attachments/assets/e0d69753-101e-486e-b167-0f639c5194e1)
KJ-500:
![image](https://github.com/user-attachments/assets/727e1aa9-f593-45b6-a07a-8007b6dd4fca)
![image](https://github.com/user-attachments/assets/8e9c7836-0fcd-4b71-a3fd-0729517566b9)
