### ISSUE TITLE
Soviet Tall King P-14 Radar in service date (1959)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5037]
### DB Selector

CWDB

### Affected DBID(s)

Facility 81

### Summary of Changes

First seen by cia in 1959.

### Sources

https://www.cia.gov/readingroom/docs/CIA-RDP78T05929A000800020039-9.pdf

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
