### ISSUE TITLE
China, Type 054B should use YJ-83B mount

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5038]
### DB Selector

DB3K

### Affected DBID(s)

Ship 

### Summary of Changes

Replace YJ-12 mount with YJ-83B

### Sources

More like YJ-83/B quad canisters than YJ-12:
https://www.sinodefenceforum.com/t/054b-new-generation-frigate.8724/page-218
![image](https://github.com/user-attachments/assets/c1ee9a5f-ddee-4567-a648-70532d80fe1b)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

**Comment by RickDNiu** [comment]
I think they are interchangeable.

**Comment by PygmalionOfCyprus** [comment]
I mean at a certain point any of these box launchers are interchangeable (provided there is appropriate software integration), it's just a matter of making sure the DB reflects the "standard" deployment loadout. Looks like as of right now the 054Bs are rolling with YJ-83s so we'll have the DB entry reflect that.

OFC anyone can use ScenEdit or Lua to modify if they want to do a scenario with YJ-12s, and if we see them consistently deploying with YJ-12s I can create another DB entry.
