### ISSUE TITLE
Correction and Update: Typhon MRC and Mk70 PDS

### ISSUE THREAD

**Issue by RickDNiu** [PygmalionOfCyprus/cmo-db-requests#5039]
- Typhon Launcher and Mk70 PDS: 

Weapon capacity: 4, provision for: 
4x SM-6 Dual II, Blk IAU, Blk IB (cf #4898, now at #5097), 
4x SM-3, IA, IB, IIA [^SM-3&Mk70], cf #4950 
4x Tomahawk Blk IV, IV Multi-Mission, V, Va, Vb (cf #3176, now at #4956), or 
8x (2x each cell) PAC-3 MSE (cf #4885, now at #4950)

Datalink: Link 16, Radio, CEC, IBCS, C2BMC

[^SM-3&Mk70]: https://www.navalnews.com/naval-news/2024/09/sm-3-launched-from-us-navy-containerized-vls-for-the-first-time

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Did not add SM-3 to the Typhon batteries because this isn't a capability the Army is known to have picked up (yet).
