### ISSUE TITLE
Add Nigerian CH-4B Rainbow Drone

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5040]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6657

### Hypothetical

No

### Name

CH-4B Rainbow

### Country

Nigeria 

### Service

Air Force

### In Commission

2020

### Number in Service

4x

### Loadout Options

AR-1 loadouts

### Sources

https://x.com/HammerOfWar5/status/1832006160896909661

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
