### ISSUE TITLE
D 210 Themistoklis edits for the Hellenic Navy

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#5045]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Ship 1049

### Summary of Changes

- [x] Change the name to Themistoklis to more closely match modern Greek
- [x] Reduce hangar size to Small, the hangar wasn't large enough for the Hellenic Navy's Medium-sized AB.212s
- [x] Add two Mk.11 Hedgehog mounts, firing forward as on other Gearings
- [x] Add Sensor 2753, the AN/SQA-10, 360 arcs
- [x] Add 2x 30mm/75 Twin Oerlikon Emerlec-30 (uses weapon 1430), probably with wide left and wide right arcs
- [x] Remove all Oerlikons
- [x] Change date to 1980

![image](https://github.com/user-attachments/assets/1fcbf93c-b242-43fd-91be-20e9e182f720)
I think that there are two single Oerlikons (as currently in the DB) in this image, and that that's the only place I can work out for the Emerlecs to go, after the Oerlikons are removed. In conclusion, Greek is hard.

### Sources

https://www.seaforces.org/marint/Hellenic-Navy/Destroyer/Themistoklis-Gearing-class.htm
https://www.navypedia.org/ships/greece/gr_dd_themistoklis.htm
Combat Fleets of the World, 1990-91
Combat Fleets of the World, 1980-81

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
