### ISSUE TITLE
Kanaris-subclass edits for the Hellenic Navy

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#5047]
### DB Selector

DB3K

### Affected DBID(s)

DB3k Ship 990

### Summary of Changes

- [ ] Add 2x FIM-43 Redeye, probably covering left and right like the AA guns. This is written as 2x2 but I don't think there was a double Redeye mount like the double Strela.
- [ ] Change arcs of Bofors to forward and sides (forward superimposed mount)
- [ ] Change arcs of 76mm OTO to aft and sides (aft superimposed mount)
- [ ] Change date to 1987-1997, 4x
- [ ] Add note "Harpoon"

The current version with the Harpoons is the 1987 refit that four of the ships got, I'm adding a request for the original 1980 version.

### Sources

https://www.seaforces.org/marint/Hellenic-Navy/Destroyer/Themistoklis-Gearing-class.htm
https://www.navypedia.org/ships/greece/gr_dd_themistoklis.htm
Combat Fleets of the World, 1990-91

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
