### ISSUE TITLE
Update: HQ-9 and related inteceptor

### ISSUE THREAD

**Issue by RickDNiu** [PygmalionOfCyprus/cmo-db-requests#5052]
- "Project 9"

> Program started early 1980s. Initial requirements stemmed from the then cancelled HQ-5, during which both heavy anti-high altitude/high speed mobile (Guizhou) and high mobility low altitude focused versions were proposed. ARH was also required instead of the then popular TVM. 
> China purchased S-300PUM in 1991. At around the same time China acquired a Patriot standard or PAC-1 missile. While the latter proved difficult to copy then, China did later manufacture its own licensed copy of S-300 PUM and named it HQ-15. With SAM's performance witnessed during the Gulf war Project 9 went on and both were to inform in technology and in design. 

### - ~~HQ-8, _FT-2000_, 1993~~[^HQ-8]

- Missile: 

> Primitive HQ-9, anti-radiation SAM. Use case, range and flight envelope restricted so did not get any foreign/domestic order and was cancelled/renamed HQ-8. 

100km range, target altitude 3000m-18km. Max speed Mach 4.2. 

> Aerodynamics similar to standard missiles, probably because SRM tech lagging. Would be slower. 

Passive radar seeker, Seeker Band Coverage 2-18 GHz, Low PoK.  
 
### - HQ-9, 1998?[^HQ9_general]

- Missile:  

> Low-rate production in 1995. Went for a S-300 design but larger/would have better fight envelope than PMU. 

120km range, target altitude 30m-18km. Max speed M4.2

TVM+ARH. 75% PoK. 

> Guidance see below radar. 

- Radar: 

Land: 
SJ-212, S band phased array search and missile tracking, enlarged SJ-202 from KS-1 (HQ-12). 300km range, should be able to track 0.1sqm target at 150km. 1MW max power, 60kw avg. 
HT-233, C band search and TVM FCR. also the only search + FCR on HQ-12. PESA, IFF/SSR on top, lens arrangement similar to 30N6E, frequency agile, 90km search, 120km illumination range TVM+ARH, can process 50 targets and guide 6. 1MW max power, 60kw avg. 

- Facility: 

4x launcher per FCR, each search radar can support 4 FCRs. 

> This is important because missiles are tracked by the search radar. 

### - HQ-15, 1999

> Licensed built S-300PMU1. 

### - HQ-9A, HHQ-9A, _FD-2000_, 2001

- Missile: 

> HHQ-9A for 052C. Improved, but ARH seeker proved expensive and difficult to manufacture. Should be the version pitched for Turkey.

150km range, 125km export, 25m-27km. Max speed M6. 

> During the RD of type 346 radar on 052C, the HQ-9A range was extended "by _several scores_ (in Chinese, 20 to 99) kms. 

TVM+ARH. 80% PoK. Lower the RCS to 0.1/0.2/0.1sqm. 

> During the RD of type 346 radar on 052C, the HQ-9A guidance antenna was modified to have less power and lowered RCS, which presented challenge to S band tracking and C band TVM guidance. At endgame 200km range 30% of the power on the S band antenna of 346 would be used to track 8 missiles (see below). 

- Radar: 
Land: 
SJ-212 search or
305A, S band AESA search, ABM, 450km range, 30km ceiling. Probably the JYL-1A[^JYL-1A]
305B, S band PESA search, aka YLC-2U, does not have IFF/SSR

HT-233 FCR or
H-200 improved, C band search and FCR, also FCR on HQ-22. IFF, 300km illumination range for TVM+ARH, 16 channels, can launch all HQ-9B under its command simultaneously. 

YLC-20 ELS

052C: [^052C]Type 346, see #5097

- Facility: 

4x launcher per FCR, one search radar can support 4 FCR (16 launchers). 

> This is important because missiles are tracked by the search radar. 

### - HQ-9B, HHQ-9B, _FD-2000B, HQ-9BE_, 2012?

> Increased range with JL-2 SRM/casing tech (see also HQ-19), may have dual pulse second stage?, ABM (1000km class). BE is the export name. 

260km range (250km export), 10m-30km. Max speed M6. 

TVM+ARH/IR. 90% PoK. Guidance section miniaturized, may use late 2010s tech for seeker. 

> Improved ECCM, anti-LO. 

Same warhead

- Radar: 
Land: 
305A, 305B
YLC-2E?
H-200 improved (16 channels DL) FCR
YLC-20/29 ELS

052D: Type 346A, see #5097
055: Type 346B, see #5097

- Facility: 

4x launcher per FCR, one search radar can support 4 FCR (16 launchers). 

> This is important because missiles are tracked by the search radar. 

### - HQ-12

- Change guidance to TVM plus terminal SARH. Add HQ-12/22 DL to weapon and facility (6 channel, 2x3 targets for H-200, 16 for H-200 improved). 

- Change range to 50km. Change engagement alt to 1500ft to 82,000ft. Change max speed to Mach 4. 

- Change facility to structure: open. 

> Simi-fixed. 

- Radar: 
SJ-202 (HQ-2 and HQ-12) search, or SJ-231 (HQ-12 and HQ-22) search
H-200 or H-200 improved (16 channel DL) FCR

### - HQ-22, 2016

> Cheap HQ-9 with HQ-5 origins.

- Change guidance to TVM plus terminal SARH. Add HQ-12/22 DL to weapon and facility (6 channel, 2x3 targets for H-200, 16 for H-200 improved). 

> HQ-22 facility can guide HQ-12. 

- Change range of HQ-22 to 170km, FK-3 to 100km. Change engagement alt to 160ft to 88,500ft. Change max speed to Mach 6. 

- Change facility to structure: open. 

- Add user for FK-3: Burma, Thailand, Turkmenistan

- Radar
SJ-231 search
H-200 improved (16 channel DL) FCR

### - HQ-19, 2018

Baseline: HQ-9B as above, THAAD-ER

Length: 12m, diameter/span: 1.4m, weight: 1800kg

Range: 600nm, Target alt: 30km-300km

> Carbon fiber casing and improved solid fuel, together with a booster size akin to that of the THAAD-ER, may yield the "3x range, 10 defended area" advantage we expected from it. Sources also states dual-pulse second stage SRM were used (as above HQ-9B). 

Warhead: KKV, Sensor: EO and IIR, DL: HQ-9, ABM

> We are unable to tell the exact but these can be expected. MMW radar may be an option but less likely. 

Targets: AC?, missiles, satellites

> Possibly some direct ascent AS capability. 

Capability: 
Anti-Air All-Aspect
Lock-On After Launch (LOAL) - CEC-Capable
Weapon - INS w/ GNSS Navigation
Re-Attack Capability
Attitude Control - Combined
Uses BeiDou/COMPASS
Level Cruise Flight

Launcher: TAS5380 8×8 

### - HQ-29, HQ-9BG, "Project 8102", 2022

> Thin HQ-9, likely PAC-3 CRI/9M96D similar, stage 2 replaced by ACS? 8x on same TLE. 

Range 120km, 10m-30km?

TVM + ARH? 85% PoK?

Likely kinetic. 

### - HQ-26, 2022

> Maritime, SA-21b copy, tested on 891 maritime testbeds. Anti-LO. 

Range 400km, 10m-28km? 

TVM + ARH/IR? 90% PoK. 

Likely ABM optimized frag warhead?

### - DN-3, 2010-
Baseline: GBI, DF-21

Length: 11m, diameter/span: 1.4m, weight: 14000kg

> DF-21 based. 

Range: 2600nm, Target alt: 100km-1000km

> DF-21 propulsion and basing patterns indicate its likely range and envelope is similar to US GBI. Two stage and separating KKV. 

Warhead: KKV, Sensor: IIR, DL: ABM

Targets: missiles, satellites

Capability: 
Anti-Air All-Aspect 
Multi stage missile
Lock-On After Launch (LOAL) - CEC-Capable
Re-Attack Capability
Attitude Control - Non-Aerodynamic Only
Level Cruise Flight

Launcher: Likely DF-21 TEL similar

> Test record: 7 successes as announced. Reportedly one unannounced test involved two mock warheads after the September 2023 MMIII test with 3 RVs. 

---
> 1. [Chinese source] https://zh.wikipedia.org/wiki/640%E5%B7%A5%E7%A8%8B
> 2. https://www.globalsecurity.org/space/world/china/hq-19.htm
> 3. https://www.armyrecognition.com/defense_news_march_2021_global_security_army_industry/chinese_hq-19_anti-ballistic_missile_interceptor_presumably_operational.html
> 4. [Chinese source] https://zh.wikipedia.org/zh-cn/%E7%BA%A2%E6%97%97-19%E5%A4%A7%E6%B0%94%E5%B1%82%E5%86%85%E5%A4%96%E5%8F%8D%E5%AF%BC%E5%AF%BC%E5%BC%B9
> 5. [Chinese propaganda source 1] https://web.archive.org/web/20170407170938/http://mil.news.sina.com.cn/jssd/2017-04-04/doc-ifycwymx3650845.shtml
>  6. [Chinese propaganda source 2] https://web.archive.org/web/20210113141658/https://www.guancha.cn/wangyu/2017_03_20_399674.shtml
> 7. https://en.wikipedia.org/wiki/Dong_Neng-3
> 8. [HQ-29 source}
> 9. https://www.globalsecurity.org/space/world/china/hq-29.htm
> 10. [Chinese source] https://zh.wikipedia.org/wiki/%E7%BA%A2%E6%97%97-26%E9%98%B2%E7%A9%BA%E5%AF%BC%E5%BC%B9
> 11. [Russian source] https://ru.wikipedia.org/wiki/HQ-26
> 12. https://www.armscontrolwonk.com/archive/1202634/tracking-preparations-at-the-korla-missile-test-base/
> 13. https://www.airuniversity.af.edu/Portals/10/CASI/documents/Research/CASI%20Articles/2021-02-09%20BMD-ASAT%20test.pdf?ver=1EhOyOijiAHdv24QbSp7XA%3d%3d
> 14. https://www.globalsecurity.org/space/world/china/hq-29.htm

[^HQ-8]: https://www.ausairpower.net/APA-PLA-IADS-SAMs.html
[^HQ9_general]: https://www.163.com/dy/article/CQAA2LQU0514A7EL.html; https://www.xinouzhou.com/detail-282072.html; https://www.ausairpower.net/APA-PLA-IADS-SAMs.html; https://imil.ifeng.com/60153938/news.shtml; 
[HQ-9_radar]: http://www.xinhuanet.com//mil/2015-11/12/c_128422197.htm (2015 northwest, older YLC-8?, YLC-2U, JYL-1A); https://www.militarydrones.org.cn/ylc-2a-radar-p00633p1.html (YLC-2, mentioning U); 
[^JYL-1A]: https://web.archive.org/web/20240424130422/https://www.militarydrones.org.cn/jyl-1a-radar-p00632p1.html
[^052C]: https://docs.google.com/document/d/1_DRDzHjmQ5r4d_MWaE4KhTTFwD0cN3OS7IIpgKsadfE/edit?usp=sharing

**Comment by RickDNiu** [comment]
Surrogate #4949, in #4951

**Comment by RickDNiu** [comment]
Surrogate #4839, in #4951

**Comment by RickDNiu** [comment]
Surrogate #4477, in #4951

**Comment by RickDNiu** [comment]
As to YLC-2: 
2U (K/LLQ305B) is an S band variant of 2V wo IFF/SSR, 2E (2023) is an S band high powered (insert anti-stealth) GaN AESA improvement from 2U, has IFF. 2V is L band early warning descended from 2 High guard with some ABM capability. Currently 2V in game uses a pic from SLC-2(A) which is a counter battery/C-RAM radar. 
I may do a China radar series.

**Comment by PygmalionOfCyprus** [comment]
Mostly handled 509. Holding off on the TBM/ASAT stuff since a lot of it is just testing AFAIK? If any of these are confirmed in-service/deployed then by all means correct me, but I suspect only some of these interceptors are gonna make it to full production.

Also, genuine question because I don't know. Was the original HQ-9 ever fielded? Feels like HQ-9A came out almost immediately afterwards and I can't find much mention of those original HQ-9 units.

**Comment by yU2187sie** [comment]
At present, the PLA does not expose the situation of TBM/ASAT ammunition at all, we can currently know its existence only and only two channels, one is the upcoming Zhuhai Air Show, and do not know when there will be a military parade.
