### ISSUE TITLE
Weapon #4233 AD-08 Majid Surface to Air Weapon update

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#5054]
### DB Selector

DB3K

### Affected DBID(s)

Weapon #4233 

### Summary of Changes

Min range 700 m (0.38 Nm)
Max range: 5 km (2.7Nm)
Altitude 200-5000m
Diameter 155mm
Warhead weight 14 kg
Fuze Proximity
Weight 75 kg

### Sources

[https://t.me/pvo_vks/23948](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
