### ISSUE TITLE
French Jaguar A BAP.100 loadout cruises at wrong altitude

### ISSUE THREAD

**Issue by TestPilotKerman** [PygmalionOfCyprus/cmo-db-requests#5055]
### DB Selector

DB3K

### Affected DBID(s)

3024

### Summary of Changes

Aircraft flies at 1k ft AGL. DB entry for loadout suggests it should fly at 36k ft.

### Sources

N/A - asking to adjust game performance to DB.

**Comment by PygmalionOfCyprus** [comment]
It is a Hi-Lo-Hi loadout so if you're within 100nm of the target the A/C should drop to sea-level (or as close as it can get with its systems). If this isn't the case and it's still stuck down at 1k this is either a sim-side issue or a problem with the flight planner (which we've fixed a lot of bugs in recently). Recommend posting in Tech Support forums if it still persists.
