### ISSUE TITLE
Add Romanian SAM Bn/2 (SA-8B Gecko Mod-1 [9K33M3 Osa-AKM])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5058]
### DB Selector

DB3K

### DBID to Copy

Facility 3453

### Hypothetical

No

### Name

SAM Bn/2 (SA-8B Gecko Mod-1 [9K33M3 Osa-AKM])

### Country

Romania

### Service

Army

### In Commission

1985

### Number in Service

28x

### Sources

https://en.topwar.ru/199956-zenitnye-raketnye-kompleksy-vojskovoj-pvo-rumynii.html
https://en.wikipedia.org/wiki/50th_Anti-Aircraft_Missile_Regiment_(Romania)
https://commons.wikimedia.org/wiki/File:Romanian_9K33_Osa_(SA-8).jpg

**Comment by FrangibleCover** [comment]
Not hypo (I do this constantly too)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
