### ISSUE TITLE
Add Romanian SAM Bn (SA-6b Gainful [2K12 Kub]) 1981

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5059]
### DB Selector

DB3K

### DBID to Copy

Facility 3924

### Hypothetical

No

### Name

SAM Bn (SA-6b Gainful [2K12 Kub])

### Country

Romania

### Service

Army

### In Commission

1981

### Sources

https://en.topwar.ru/199956-zenitnye-raketnye-kompleksy-vojskovoj-pvo-rumynii.html
https://commons.wikimedia.org/wiki/File:Romanian_2K12_Kub_(SA-6)_5.jpg
https://military-history.fandom.com/wiki/List_of_equipment_of_the_Romanian_Land_Forces?file=Trageri_la_capu_midia_19.jpg
https://en.wikipedia.org/wiki/2K12_Kub

Sipri
Romania	Soviet Union	1980	?	10	?	Kvadrat	SAM system	10	?	1980; 1981; 1982	New	No. could be 15	17.5	175	175

**Comment by FrangibleCover** [comment]
Also not hypo

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
