### ISSUE TITLE
Arty Plt (WS-1B MLRS [T-300 Kasirga])

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#506]
### DB Selector

DB3K

### DBID to Copy

facility/1729/DB3K

### Hypothetical

No

### Name

Arty Plt (WS-1B MLRS [T-300 Kasirga])

### Country

Azerbaijan

### Service

Army

### In Commission

IOC Uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces#Artillery

**Comment by PygmalionOfCyprus** [comment]
Added 494.
