### ISSUE TITLE
Add Romanian AAA Sec (35mm Twin Oerlikon GDF-003 x2, Skyguard FCR) 1999

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5064]
### DB Selector

DB3K

### DBID to Copy

Facility 1091

### Hypothetical

No

### Name

AAA Sec (35mm Twin Oerlikon x2, Skyguard FCR)

### Country

Romanian

### Service

Army

### In Commission

1999

### Number in Service

x36

### Sensors

Skyguard

### Other Changes

GDF-003 version. I'm not sure if you want to dig too far into the differences in the physical gun yet, but let me know if so.

### Sources

https://en.topwar.ru/199737-zenitnye-pulemetnye-i-artillerijskie-ustanovki-ispolzuemye-vooruzhennymi-silami-rumynii.html

Sipri
Romania	Switzerland	1997		72	?	GDF 35mm	anti-aircraft gun	72	?	1998; 1999	New	GDF-003 version
Romania	Switzerland	1998		36	?	Skyguard	fire control radar	36	?	1998; 1999	New	For use with GDF-003 35mm AA guns	5	180	180

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
