### ISSUE TITLE
Add Romanian SAM Bn (SA-2b Guideline [S-75 Dvina]) 1960

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5065]
### DB Selector

Both

### DBID to Copy

Facility 761 (CWDB), 1296 (DB3K)

### Hypothetical

No

### Name

SAM Bn (SA-2b Guideline [S-75 Dvina])

### Country

Romania

### Service

Air Force

### In Commission

1960-

### Number in Service

18x

### Other Changes

CIA ID'd SAM sites starting in 1960

### Sources

https://www.cia.gov/readingroom/document/cia-rdp78t04751a000200010020-1

Sipri
Romania	Soviet Union	1963	?	18	?	S-75 Dvina	SAM system	18	?	1963; 1964; 1965; 1966; 1967	New	No. could be 20	17.87	321.66	321.66

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
