### ISSUE TITLE
J-16, original PL-17 Light Intercept Loadout could be back

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5068]
### DB Selector

DB3K

### User(s)

Aircraft 6450

### Weapons Carried

[PL-17 Light Intercept] (Loadout 33626 on J-20B)

-2x PL-17
-2x PL-10

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

850nm Intercept radius

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

I remember that such a loadout existed before DB506, which gave the J-16 a long-range interception possibility and made its combat loadout options more flexible.

### Sources

In fact, this is how the PL-17 and J-16 first appeared together:
https://www.google.com/url?sa=i&url=https%3A%2F%2Fmeta-defense.fr%2Fen%2F2023%2F12%2F04%2Fmissile-pl-17-j-16-operational-apl%2F&psig=AOvVaw07t6mWk0OtpvpHOT_8NuEl&ust=1726218401995000&source=images&cd=vfe&opi=89978449&ved=0CBcQjhxqFwoTCPD9sOaGvYgDFQAAAAAdAAAAABAE
![image](https://github.com/user-attachments/assets/f7f9b314-8711-4f9f-a560-4629388c7d28)

**Comment by PygmalionOfCyprus** [comment]
Handled 508.

**Comment by Luigi-II** [comment]
> Handled 508.

So 508 is still working in progress? I thought the work on the 509 have already started.

**Comment by PygmalionOfCyprus** [comment]
Sorry, I wrote the wrong thing. Handled 509. XD
