### ISSUE TITLE
J-16, 4x PL-17 loadout may be added, using current weapon record

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5071]
### DB Selector

DB3K

### User(s)

Aircraft 6450

### Weapons Carried

[PL-17 heavy intercept]

-4x PL-17 (record 10575)
-2x PL-10

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

700nm intercept radius

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Yeah, I can't wait. We have seen the US Navy SH and Russian flanker demonstrate their ability to mount 4 VLRAAM, so why not the Chinese flanker? Do we have to wait until we see the pictures, even though it's a high possibility?

I remember they showed a heavy mixed loadout of VLRAAM and other AAMs, 10 in total. The payload is already much heavier than just 4x VLRAAMs. Currently only one such heavy mixed PL-17 loadout option for J-16 seems too rigid.

### Sources

At least according to the footage captured by Janes, not only the innermost point, but the second-to-the-innermost point is also capable of carrying large munitions.
https://www.janes.com/osint-insights/defence-news/images-show-plaaf-j-16-armed-with-yj-83k-anti-ship-missile
![image](https://github.com/user-attachments/assets/33faabd2-88c5-48f0-927e-07b630fda281)

Large, long ammunition pylon appear on the second innermost point
https://www.google.com/url?sa=i&url=https%3A%2F%2Fm.facebook.com%2F611223845748378%2Fphotos%2Fj-16-armed-with-a-kd-88-agm-and-the-regular-assiciated-guidance-pod%2F1072881989582559%2F&psig=AOvVaw1YPj4JIGM4BPkqHIJfxM83&ust=1726278385301000&source=images&cd=vfe&opi=89978449&ved=0CBcQjhxqFwoTCPDm0KHmvogDFQAAAAAdAAAAABAE
![image](https://github.com/user-attachments/assets/538db3c3-565f-40df-9f0c-24480c212c97)

**Comment by PygmalionOfCyprus** [comment]
Agree. I've added a "PL-17, Heavy" loadout basically assuming something like this, where Red = PL-17, Blue = PL-10, and Black = PL-15.

![image](https://github.com/user-attachments/assets/21662faf-343e-422a-81cd-19bde5a56e64)
