### ISSUE TITLE
Please change Thailand JAS-39 C/D to E/F

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#5076]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #5842 and #5843 

### Summary of Changes

The updated JAS-39's (to MS-20) are dated 2025 in the Database but have already been upgraded in 2022 not in 2025.

**Quote:**
The most modern of the RTAF’s fighters are its 11 Gripens (seven single-seat Gripen Cs and four two-seat Gripen Ds) which were in two separate batches in February 2008 and November 2010. These jets have recently been upgraded to the latest [MS20 configuration](https://www.janes.com/osint-insights/defence-news/defence/thailand-commences-ms20-upgrades-for-gripens) and they have a notable anti-surface warfare capability, armed with Saab’s [RBS 15 anti-ship missile](https://www.saab.com/products/the-rbs15-family)

(The JAS-39E/F was selected for 2025 but I will put this in a separate issue.)
### Sources

.](url)

[https://www.twz.com/air/thailand-chooses-gripen-e-f-as-its-new-fighter](url)
https://aviationweek.com/defense/budget-policy-operations/thailand-completes-gripen-ms20-upgrade-awaits-f-35-nod

**Comment by PygmalionOfCyprus** [comment]
IS date for the MS20 variants changed to 2022.
