### ISSUE TITLE
An-2 Colt - 1992

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#508]
### DB Selector

DB3K

### DBID to Copy

aircraft/3096/CWDB

### Hypothetical

No

### Name

An-2 Colt - 1992

### Country

Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

Uncertain

### Mounts

Uncertain

### Loadout Options

Add for UAV version

- Target Drone
- Strike 

### Other Changes

Converted in large numbers to UAVs for baiting Air Defense Systems. Other An-2s were converted to UCAVs armed with four unguided bombs.

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/12/death-from-above-azerbaijans-killer.html
https://www.oryxspioenkop.com/2021/12/death-from-above-azerbaijans-killer.html

**Comment by PygmalionOfCyprus** [comment]
Added 494. I can't figure out what bombs are in that photo of the armed An-2 UCAV so I slapped some OFAB-250s on there. If anyone can figure it out by all means let me know.

https://postlmg.cc/p9Z11H61
![image](https://user-images.githubusercontent.com/87087226/157627267-e0a3c76c-10a4-4a99-8f71-b2cc102621b3.png)

**Comment by tbrandon517** [comment]
That seems okay. Based on this it appears 12x 50kg bombs or 4x 100-250kg bombs or a simialr payload of rockets on armed An-2 variants.

https://www.globalsecurity.org/military/world/russia/an-2-bombard.htm
https://www.globalsecurity.org/military/world/russia/an-2-variants.htm
