### ISSUE TITLE
PrsM 4

### ISSUE THREAD

**Issue by RickDNiu** [PygmalionOfCyprus/cmo-db-requests#5081]
[Addition_ PrSM Spiral 4 · Issue #4128 · PygmalionOfCyprus_cmo-db-requests.pdf](https://github.com/user-attachments/files/17006191/Addition_.PrSM.Spiral.4.Issue.4128.PygmalionOfCyprus_cmo-db-requests.pdf)

**Comment by PygmalionOfCyprus** [comment]
Re-added in 508. It was originally added for 507 but we had a version control issue that day and we didn't notice until 508.
