### ISSUE TITLE
Be-12PS Mail - 1992, SAR

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#509]
### DB Selector

DB3K

### DBID to Copy

aircraft/2680/DB3K

### Hypothetical

No

### Name

Be-12PS Mail - 1992, SAR

### Country

Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/12/caspian-amphibians-azerbaijans-elusive.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
