### ISSUE TITLE
China, Divine Eagle AMTI AESA & /GMTI/SAR AESA, X Band Mod

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5091]
### DB Selector

DB3K

### DBID to Copy

sensor 6026 6027

### Hypothetical

No

### Name

Divine Eagle AMTI AESA & /GMTI/SAR AESA, X Band Mod

### Country

China

### Service

PLAAF

### Sensors

Copy **sensor 6026 6027** and modifiy them to **I Band**. Add **[X Band]** as suffix (To avoid X/Y Band bug while keeping Dual Band, just like what have been done to KJ-700 Dual Band Radar).

### Sources

#4973

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
