### ISSUE TITLE
China, KJ-600 fuel consumption in Band 3, “Warp Drive" shouldn't be invented in 024.M03

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5092]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5420

### Summary of Changes

Band 3 fuel consumption is currently 0kg/min. Adjust to appropriate 10-12-15kg/min.

In game, It has enough fuel to travel across the galaxy.

### Sources

The timetable for the Great Crusade needs to be greatly advanced. For The Emperor!

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
