### ISSUE TITLE
Indonesia, Thaon di Revel-class OPV [PPA Light+]

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5094]
### DB Selector

DB3K

### DBID to Copy

Ship 3306

### Hypothetical

No

### Name

TBD [Thaon di Revel-class, Light+]

### Country

Indonesia

### Service

Navy

### Sources

https://www.navalnews.com/naval-news/2024/04/new-details-on-fincantieris-ppa-frigates-programme-for-indonesia/
https://en.wikipedia.org/wiki/Italian_offshore_patrol_vessel_Marcantonio_Colonna

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
