### ISSUE TITLE
China, Type XXX MFR, 054B MFR, tech update

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5096]
### DB Selector

DB3K

### Affected DBID(s)

sensor 7278

### Summary of Changes

- [ ] Change its tech level to **Early 2020s**

### Sources

The 054B's radar was first seen on a test ship in early 2020, and installed on 054B in 2023 after further development:
https://mil.sina.cn/sd/2020-01-17/detail-iihnzhha2984832.d.html

> On January 15, a photo of a 054B frigate's shipborne radar being tested on the 892 Hua Luogeng equipment test ship began to circulate online. From the photo, we can roughly guess that this new radar, which takes stealth design into consideration, should be a double-sided rotating upgraded version of the domestically produced "Top Plate" three-coordinate radar that is widely equipped on the domestically produced 054A. It is worth noting that the appearance of the new radar is very similar to the Hercules single-sided S-band passive phased array radar equipped on the French Aquitaine-class frigate. At the same time, it should be clear that the radar weapons tested on the 892 Hua Luogeng equipment test ship must be planned or under construction for the corresponding equipped ships.

**Comment by RickDNiu** [comment]
This is quite a mess, and I might have failed to pay attention to the gap created by Ukrainian/French/german/American and Chinese propulsion. I’ll do a ship review.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

**Comment by PygmalionOfCyprus** [comment]
> This is quite a mess, and I might have failed to pay attention to the gap created by Ukrainian/French/german/American and Chinese propulsion. I’ll do a ship review.

? Maybe replying to wrong issue @RickDNiu?

**Comment by RickDNiu** [comment]
> > This is quite a mess, and I might have failed to pay attention to the gap created by Ukrainian/French/german/American and Chinese propulsion. I’ll do a ship review.
> 
> ? Maybe replying to wrong issue @RickDNiu?

H/LJQ-368 And SR-2410C In #5097
