### ISSUE TITLE
SSM Bty (Harop TEL)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#510]
### DB Selector

DB3K

### DBID to Copy

facility/2620/DB3K

### Hypothetical

No

### Name

SSM Bty (Harop TEL)

### Country

Azerbaijan

### Service

Air Force

### In Commission

2018

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://www.thedrive.com/the-war-zone/23270/israeli-company-allegedly-flew-a-suicide-drone-on-a-real-combat-mission-in-azerbaijan
https://www.thedrive.com/the-war-zone/20116/azerbaijans-border-guard-has-this-awesomely-bad-music-video-with-tanks-and-suicide-drones
https://www.forbes.com/sites/davidhambling/2020/06/22/the-weird-and-worrying-drone-war-in-the-caucasus/?sh=4d3ad66545da

**Comment by PygmalionOfCyprus** [comment]
Added 494.
