### ISSUE TITLE
Wright Flyer

### ISSUE THREAD

**Issue by Laqueesha** [PygmalionOfCyprus/cmo-db-requests#5100]
### DB Selector

Both

### Hypothetical

No

### Name

Wright Flyer

### Country

United States

### Service

Civilian

### In Commission

1903

### Number in Service

1

### Length (m)

6.43

### Wingspan (m)

12.29

### Height (m)

2.74

### Empty Weight (kg)

274

### Maximum Takeoff Weight (MTOW) (kg)

338

### Payload Weight (kg)

65

### Crew

1

### Propulsion

1 × Wright straight-4 water-cooled 201.1 cu in (3,295 cc) piston engine. 12 hp (8.9 kW)

### Rate of Climb (ft/min)

42.4 

### Service Ceiling (ft)

30

### Military/Afterburner Speed (kt)

26

### Cruise Speed (kt)

5.9

### Supercruise

No

### Ferry Range (nm)

0.02

### Endurance (min)

1

### Takeoff / Landing Distance (m)

72

### Fuel Capacity (kg)

1.51

### Sensors

1x Mk1 Eyeball

### Mounts

Passenger

### Loadout Options

1x passenger

### Sources

https://en.wikipedia.org/wiki/Wright_Flyer

**Comment by PygmalionOfCyprus** [comment]
Not in service in DB timeframes.
