### ISSUE TITLE
China, PL-17 & PL-15 command link & DL for CEC function

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5102]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4110

### Summary of Changes

- [ ] Add "Support CEC" code to PL-17 DL & command link and PL-15 command link

Just adding China CEC DL will not solve the problem, it is THE ONLY solution.

### Sources

#4512 Because my account was ghosted, you might not have seen my comment in this thread.
![image](https://github.com/user-attachments/assets/83ea4a1c-c36b-442f-a3fa-bff9fb771f7c)
![image](https://github.com/user-attachments/assets/9af83f23-e955-4f9c-b832-ad7963e43fe5)
![image](https://github.com/user-attachments/assets/bd73e80c-baf0-4326-ac70-a99d8347d79f)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
