### ISSUE TITLE
Add UAE  and Algerian Art Bty (SR-5 MLRS x 6)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5103]
### DB Selector

DB3K

### DBID to Copy

Facility 3623

### Hypothetical

No

### Name

Art Bty (SR-5 MLRS x 6)

### Country

UAE, Algeria

### Service

Army

### In Commission

UAE 2020, Algeria 2017

### Sensors

same

### Mounts

same

### Loadout Options

same

### Other Changes

Export PHL-11

### Sources

UAE

https://www.janes.com/osint-insights/defence-news/uae-reveals-sr5-mrl-acquisition

Algeria
https://armyrecognition.com/news/army-news/2017/china-would-have-delivered-sr5-rocket-launchers-to-algeria
https://defence-blog.com/algeria-confirms-delivery-of-sr5-multiple-rocket-launchers-from-china/
https://x.com/fares4302/status/1576129534768066561

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
