### ISSUE TITLE
China, DF-100 cruise altitude way too low, may caused by climb rate?

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5105]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3669

### Summary of Changes

- [ ] Restore the climb rate to original **4921ft/min - 1500m/min**

It seems that during the database update process, its climb rate was incorrectly set to the same as that of the subsonic sea-skimming CJ-10, resulting in some kind of data overrun or error that made its flight performance completely inconsistent with reality.

### Sources

DB itself
![image](https://github.com/user-attachments/assets/16311877-876e-4dde-8dd1-0ea404e9957b)
![image](https://github.com/user-attachments/assets/30f098f7-b2fe-47b7-94f9-a6d85b3662af)

**Comment by Luigi-II** [comment]
While you were working on the 508 database, my account was ghosted, perhaps you could reconsider this?
#4089

**Comment by PygmalionOfCyprus** [comment]
Weird. Not sure how that happened. Fixed 509.
