### ISSUE TITLE
Add Nigerian and Ugandan Arty Bty (RM-70 MLRS x 6) 2002, 2015

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5107]
### DB Selector

DB3K

### DBID to Copy

Facility 4382

### Hypothetical

No

### Name

Arty Bty (RM-70 MLRS x 6)

### Country

Nigeria, Uganda

### Service

Army

### In Commission

Nigeria 2015 Uganda 2002

### Sources
Nigeria
https://x.com/DefenseNigeria/status/1828745453028155701
https://x.com/DefenseNigeria/status/1579175326579494913
https://x.com/AYOCONORZ/status/1241342308991328256

Uganda
https://www.oryxspioenkop.com/2023/08/guardians-of-pearl-ugandas-inventory-of.html

Sipri
Nigeria	Czechia	2014	?	7	?	RM-70 122mm	self-propelled MRL	7		2015	Second hand	Second-hand	0.36	2.52	2.52
Uganda	Czechia	2002	?	6	?	RM-70 122mm	self-propelled MRL	6		2002	Second hand	Second-hand; sold via Slovakia	0.36	2.16	2.16

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
