### ISSUE TITLE
Add Ugandan AAA Bty (37mm Type 65 Twin x4)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5108]
### DB Selector

DB3K

### DBID to Copy

Facility 4346

### Hypothetical

No

### Name

AAA Bty (37mm Type 65 Twin x4)

### Country

Uganda

### Service

Army

### Sources

https://x.com/HammerOfWar5/status/1834581354991743233
https://www.oryxspioenkop.com/2023/08/guardians-of-pearl-ugandas-inventory-of.html

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
