### ISSUE TITLE
US, PrSM series update

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5109]
### DB Selector

DB3K

### Affected DBID(s)

See Summary of Changes

### Summary of Changes

- [x] Reduce Superfrag warhead to reasonable **200 lb/91kg HE**. It is inconceivable (at least according to most known information) to use a warhead of the same weight as the ATACMS to achieve a longer range with a much smaller diameter and length.
[ weapon **3728 3843 3845 3847 4524**]

- [ ] Cut **PrSM Spiral/Inc 3**'s range to **270nm**. The currently known information for this version does not include increase of range.
[ weapon **3847 3848 4413**]

- [ ] Change the type of **PrSM Spiral/Inc 4** to **Guided Weapon** and engine type to **Ramjet**. Unless there is critical evidence to the contrary, it is hardly reasonable to try to achieve a doubling of range when other metrics (volume, warhead charge, sensors) are remain the (almost) same. The best guess is a change of ramjet engine. The CG reference given by Lockheed Martin is also a ramjet cruise missile.
[ weapon **4524 4525 4526**]

- [ ] Set **PrSM Spiral/Inc 4's** cruise altitude to **100000ft/30480m**. Same as RGM-109Z Fasthawk, also a Ramjet missile developed by US.
[ weapon **4524 4525 4526**]

### Sources

For Superfrag warhead:
https://www.reddit.com/r/LessCredibleDefence/comments/18atvbu/do_we_know_the_warhead_sizeweight_of_prsm_missile/
![image](https://github.com/user-attachments/assets/b5ce6358-c906-4977-b6ca-0ccdd1b8d5a8)
https://www.popularmechanics.com/military/weapons/a46094242/precision-strike-missile/
https://defence-industry.eu/us-army-receives-first-batch-of-precision-strike-missiles-for-enhanced-tactical-capabilities/

> The PrSM is launched from modified ground-based rocket systems, specifically the M142 HIMARS and M270A2 MLRS. The M270A2 MLRS launcher can accommodate four PrSMs (as opposed to two ATACMS), and the M142 HIMARS launcher can house two PrSMs instead of one ATACMS. The PrSM features a solid-fuel engine, is 4 meters long, and has a diameter of 430 mm. Its warhead weighs 91 kg, similar to that of the GMLRS, and the initial version incorporates a satellite-inertial guidance system.

For range & motor type:
https://www.ex2.com.au/news/lockheed-martin-delivers-first-precision-strike-missiles-to-us-army/

> Increment 3 would see the integration of new payloads.

https://breakingdefense.com/2023/03/army-taps-teams-to-build-new-precision-strike-missile-for-targets-beyond-1000-km/

> For PrSM Inc 4 — which may be ready before Inc 3 — the Army is eyeing a new missile form factor possibly with a new propulsion system to strike targets at least 1,000 km away. This new propulsion system could [potentially be](https://www.janes.com/defence-news/news-detail/us-army-conducts-static-test-with-ramjet-for-future-precision-strike-missile) a ramjet, an airbreathing jet engine that uses the forward motion of the engine to produce thrust.

https://warriormaven.com/land/army-adds-payload-seeker-range-improvements-to-its-precision-strike-missile
![image](https://github.com/user-attachments/assets/210981a9-a50a-432d-943f-f512095d485e)

**Comment by PygmalionOfCyprus** [comment]
It's getting harder to find concrete descriptions of the spirals but [this article](https://breakingdefense.com/2020/06/army-tests-prsm-seeker-to-hunt-ships-sams/) (that I based the initial DB entries off of) indicates that the primary feature of Spiral 3 is a range increase.

Also, the Spiral 4 entries should already be ramjet? They are in my copy of the DB. (Also the cruise altitude doesn't matter for weapons with a ballistic trajectory as long as it is set to an arbitrary high value; the sim determines apex heights based on target range, etc.)

Handled the rest in 509.
