### ISSUE TITLE
Heron TP UAV - Azerbaijan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#511]
### DB Selector

DB3K

### DBID to Copy

aircraft/4381/DB3K

### Hypothetical

No

### Name

Heron TP UAV - Azerbaijan

### Country

Azerbaijan

### Service

Air Force

### In Commission

IOC Uncertain

### Sensors

None Known

### Mounts

None Known

### Loadout Options

None Known

### Other Changes

None Known

### Sources

https://www.oryxspioenkop.com/2021/12/death-from-above-azerbaijans-killer.html
https://en.wikipedia.org/wiki/List_of_modern_equipment_of_the_Azerbaijani_Air_Force#Aircraft

**Comment by PygmalionOfCyprus** [comment]
Added 494.
