### ISSUE TITLE
Add Ugandan Mi-24P Hind F 1999

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5111]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4264

### Hypothetical

No

### Name

Mi-24P Hind F

### Country

Uganda

### Service

Air Force

### In Commission

1996

### Number in Service

Few

### Sources

https://commons.wikimedia.org/wiki/File:Uganda_People%27s_Defence_Force_Air_Wing_Mil_Mi-24P_MTI-1.jpg
https://www.defenceweb.co.za/aerospace/aerospace-aerospace/uganda-commissions-first-locally-overhauled-mi-24/
Sipri

Uganda	Belarus	2017	?	2	?	Mi-24P/Mi-35P	combat helicopter	2		2018; 2019	Second hand	Second-hand
Uganda	Ukraine	1999		1		Mi-24P/Mi-35P	combat helicopter	1		1999	Second hand	Second-hand (bought as modernized but found after delivery not to be)
Uganda	Russia	2003	?	3	?	Mi-24P/Mi-35P	combat helicopter	3	?	2004	Second hand but modernized	Second-hand Mi-24P but modernized to Mi-24PN before delivery
Uganda	Belarus	1997		2		Mi-24P/Mi-35P	combat helicopter	2		1998	Second hand	Second-hand; $9 m deal; 4 ordered but 2 cancelled after delivery of first 2 revealed aircraft not modernized as specified in contract

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
