### ISSUE TITLE
Add Ugandan Mig-21MF Fishbed J

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5113]
### DB Selector

Both

### DBID to Copy

Aircraft 4624

### Hypothetical

Yes

### Name

Mig-21MF Fishbed J

### Country

Uganda

### Service

Air Force

### In Commission

1975

### Number in Service

12x, +7

### Sources

https://en.wikipedia.org/wiki/Air_campaign_of_the_Uganda%E2%80%93Tanzania_War
https://www.flickr.com/photos/erwinalexander/45867083721
https://www.mig-21.de/english/inservice.htm
https://x.com/DavidDetten/status/1594325860794134530/photo/1

Uganda	Soviet Union	1976		7	?	MiG-21MF	fighter aircraft	7	?	1976	Second hand	Second-hand	4.28	29.96	29.96
Uganda	Soviet Union	1974	?	12		MiG-21MF	fighter aircraft	12		1975	Second hand	Probably second-hand; financed by Libya and other Arab states	4.28	51.36	51.36

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
