### ISSUE TITLE
Add Ugandan Mig-21bis Fishbed L 1999

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5114]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2768

### Hypothetical

No

### Name

Mig-21bis Fishbed L

### Country

Uganda

### Service

Air Force

### In Commission

1999

### Number in Service

8x

### Sources

https://www.airliners.net/photo/Uganda-Air-Force/Mikoyan-Gurevich-MiG-21bis/724024
https://www.scramble.nl/planning/orbats/uganda
https://x.com/StefanKnippsch3/status/1257307405165015040
https://www.mig-21.de/english/inservice.htm
https://x.com/HammerOfWar5/status/1303352310719041568

Sipri
Uganda	Poland	1998	?	7		MiG-21bis	fighter aircraft	7		1999	Second hand	Second-hand; $8.5 m deal (to fund Polish Su-22 modernization programme); incl 1 MiG-21UM version; modernized in Israel after delivery	5	35	35
Uganda	Ukraine	2005	?	1		MiG-21bis	fighter aircraft	1		2006	Second hand	Second-hand	5	5	5

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
