### ISSUE TITLE
Add Ugandan L-39ZA Albatros 1987

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5116]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4567

### Hypothetical

No

### Name

L-39ZA Albatros

### Country

Uganda

### Service

Air Force

### In Commission

1987

### Sources

https://x.com/africaken1/status/943167438765658112
https://www.keymilitary.com/article/uganda-expands-and-modernises-l-39-fleet

Sipri
Uganda	Bulgaria	2010		3	?	L-39Z Albatros	trainer/combat aircraft	3	?	2012	Second hand	Second-hand but probably modernized in Ukraine; L-39ZA version
Uganda	Libya	1986	?	3		L-39Z Albatros	trainer/combat aircraft	3		1987	Second hand	Second-hand; L-39ZA version
Uganda	Bulgaria	2018	?	2		L-39Z Albatros	trainer/combat aircraft	2		2018	Second hand	Second-hand
Uganda	United States	2009	?	1		L-39Z Albatros	trainer/combat aircraft	1		2009	Second hand

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
