### ISSUE TITLE
[Q] In DB3K_508 All E-2D Hawkeyes Seem to be Missing {IRST] Hawkeye Sensor is this Correct?

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#5117]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #. 5494, 4540, 6003, 690, 4293, 7114 & 6992

### Description of Problem

As stated in title all E-2D Hawkeye missing Sensor #.1764 - IRST [Hawkeye}. In earlier DB versions it was fitted, recently seen in DB3K_501.

### Recommended Fix

Add Sensor #.1764 - IRST [Hawkeye}. Arc PMF2, PB1, PB2, SB1, SB2 & SMF1.

**Comment by PygmalionOfCyprus** [comment]
This should be correct, I can't find the old Mantis ticket but there's no indication that the E-2Ds actually have an IRST fitted. I think this was initially a copy-over sensor created waaaaaaaaay back when the E-2D was still a "new" system and they weren't sure what was going on with it. Or maybe someone saw an article about how the E-2Ds were getting IRST but nothing actually came of it.

Anyway, if anyone actually finds evidence that the E-2Ds have an IRST fitted as standard I'll obviously re-add it, but as of right now I can't find any such info.

**Comment by 5th-Domain** [comment]
No problem, if i come across anything specific i'll come back to it, thanks
