### ISSUE TITLE
Add Aircraft JF-17 Thunder Block 3 (Azerbaijan) AF 2024

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#5118]
### DB Selector

DB3K

### DBID to Copy

Could just rebadge the JF-17 Block 3 for Argentina (Hypothetical) as they went with F-16?

### Hypothetical

No

### Name

JF-17 Thunder Block 3 (Azebaijan) AF 2024

### Country

Azerbaijan 

### Service

Air Force 

### In Commission

September 2024

### Number in Service

12?

### Sensors

Uses Asel Pod. Otherwise copy. 

### Mounts

As existing 

### Loadout Options

Straight copy of Argentine JF-17 BUT no sign of PL-15 but using PL-10 as SRAAM?

### Other Changes

Link shows range of air to ground LGB and short range AAM is PL-10 not PL-9.

### Sources

https://www.azernews.az/nation/231736.html#231736-18

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
