### ISSUE TITLE
Add Saudi Radar (AN/TPY-2) Forward-Based, Radar (AN/TPY-2) Terminal 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5119]
### DB Selector

DB3K

### DBID to Copy

Facility 3364, Facility 3070

### Hypothetical

No

### Name

Radar (AN/TPY-2) Forward-Based, Radar (AN/TPY-2) Terminal

### Country

Saudi Arabia

### Service

Air Force

### In Commission

2024

### Number in Service

1x,+6

### Sources

https://x.com/AirPowerNEW1/status/1839092893891321922
https://www.rtx.com/news/news-center/2024/09/25/rtxs-raytheon-completes-first-an-tpy-2-radar-for-the-kingdom-of-saudi-arabia
https://missilethreat.csis.org/saudi-arabia-purchases-seven-an-tpy-2-radars/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
