### ISSUE TITLE
Add Saudi Arabian SAM Bty (THAAD) 2026

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5120]
### DB Selector

DB3K

### DBID to Copy

Facility 2347

### Hypothetical

No

### Name

SAM Bty (THAAD)

### Country

Saudi Arabia

### Service

Air Force

### In Commission

2026

### Sources

https://www.janes.com/osint-insights/defence-news/weapons/first-saudi-thaad-sites-expected-to-be-completed-in-2026
https://www.dsca.mil/press-media/major-arms-sales/saudi-arabia-terminal-high-altitude-area-defense-and-related-support
https://www.forbes.com/sites/pauliddon/2024/05/14/saudi-arabia-diversifying-air-defenses-and-boosting-local-industries/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
