### ISSUE TITLE
Add  Omani AAA Sec (35mm Twin Oerlikon GDF-005 x2, Skyguard) 1996

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5123]
### DB Selector

DB3K

### DBID to Copy

Facility 4299

### Hypothetical

No

### Name

AAA Sec (35mm Twin Oerlikon GDF-005 x2, Skyguard)

### Country

Oman

### Service

Air Force

### In Commission

1996

### Number in Service

5x

### Sources

Sipri
Oman	Switzerland	1994	?	10	?	GDF 35mm	anti-aircraft gun	10		1995	New		0.75	7.5	7.5
Oman	Switzerland	1995		5		Skyguard	fire control radar	5	?	1996	New	For use with 10 GDF-005 35mm AA guns	5	25	25

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
