### ISSUE TITLE
Add Omani SAM Plt (VBL Albi [Mistral II] x2 )

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5124]
### DB Selector

DB3K

### DBID to Copy

Facility 2859

### Hypothetical

No

### Name

SAM Plt (VBL Albi [Mistral II])

### Country

Oman

### Service

Army

### In Commission

2003

### Sensors

IR/TV

### Mounts

[2] Tubes per Vehicle

6 reloads each

### Sources

https://www.arquus-defense.com/fr/panhard-vbl-albi

sipri
Oman	France	2000		230	?	Mistral	portable SAM	230	?	2001; 2002; 2003	New	For use with ALBI launcher on VBL armoured vehicles; Mistral-2 version	0.09	20.7	20.7
Oman	France	2000		81	?	VBL	APV	81	?	2001; 2002; 2003; 2004	New	Incl some with ALBI Mistral SAM launcher	0.12	9.72	9.72

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
