### ISSUE TITLE
Add Omani Arty Bty (155mm/45 G6 Self-Propelled Howitzer x 6) 1996

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5125]
### DB Selector

DB3K

### DBID to Copy

Facility 3108

### Hypothetical

No

### Name

Arty Bty (155mm/45 G6 Self-Propelled Howitzer x 6)

### Country

Oman

### Service

Army

### In Commission

1996

### Number in Service

24x

### Sources

https://www.reddit.com/r/MilitaryPorn/comments/fjh3jx/omani_denel_g6_155mm_sf_howitzers_1024x682/
https://armyrecognition.com/military-products/army/artillery-vehicles-and-weapons/self-propelled-howitzers/g6-rhino-south-africa-uk
Sipri

Oman	South Africa	1994		24		G-6 Rhino 155mm	self-propelled gun	24	?	1994; 1996	New	$120 m deal

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
