### ISSUE TITLE
Add Armored Sec (FV101 Scorpion Light Tank x2) 1982

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5126]
### DB Selector

DB3K

### DBID to Copy

Facility 2286

### Hypothetical

No

### Name

Armored Sec (FV101 Scorpion Light Tank x2)

### Country

Oman

### Service

Army

### In Commission

1982

### Sources

https://www.army-guide.com/eng/product1153.html
https://en.wikipedia.org/wiki/Royal_Army_of_Oman

Sipri
Oman	United Kingdom	1980		30	?	Scorpion	light tank	30	?	1982; 1983	New	No. could be up to 50
Oman	United Kingdom	1983	?	10	?	Scorpion	light tank	10	?	1985	New

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
