### ISSUE TITLE
Add Omani Motor Inf Plt (WZ-551B [Type 92A] APC x 4) 2003

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5127]
### DB Selector

DB3K

### DBID to Copy

Facility 4632

### Hypothetical

No

### Name

Motor Inf Plt (WZ-551B [Type 92A] APC x 4)

### Country

Oman

### Service

Army

### In Commission

2003

### Number in Service

50x

### Sources

https://en.wikipedia.org/wiki/Royal_Army_of_Oman
https://defencehub.live/attachments/db-01-jpg.23021/

Sipri
Oman	China	2003	?	50	?	WZ-551	APC	50	?	2003	New	WZ-551B version; incl CP and ambulance version

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
