### ISSUE TITLE
Add Omani Armored Plt (Challenger 2 MBT x 4) 1996

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5128]
### DB Selector

DB3K

### DBID to Copy

Facility 1930

### Hypothetical

No

### Name

Armored Plt (Challenger 2 MBT x 4)

### Country

Oman

### Service

Army

### In Commission

1996

### Number in Service

38x

### Sources

https://en.wikipedia.org/wiki/Royal_Army_of_Oman
https://www.gettyimages.com/photos/royal-army-of-oman
Sipri
Oman	United Kingdom	1997		20		Challenger-2	tank	20	?	2000	New	$172 m deal; Challenger-2 (Oman) Phase-2 version	4.25	85	85
Oman	United Kingdom	1993		18		Challenger-2	tank	18		1995; 1996	New	Part of $225 m deal	4.25	76.5	76.5

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
