### ISSUE TITLE
Add Omani Motor Inf Plt (Piranha II [12.7mm/50 M2 MG] x4)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5129]
### DB Selector

DB3K

### DBID to Copy

Facility 2866

### Hypothetical

No

### Name

Motor Inf Plt (Piranha II [12.7mm/50 M2 MG] x4)

### Country

Oman

### Service

Army

### In Commission

1996

### Number in Service

30x

### Sources

https://fighting-vehicles.com/wheeled-afv/mowag-piranha-ii/
https://defencehub.live/attachments/db-01-jpg.23021/
Sipri
Oman	United Kingdom	1994		80		Piranha	APC	80	?	1995; 1996; 1997	New	$138 m deal; incl ARV; CP; 81mm mortar carrier; ambulance and artillery observation versions; option on 46 or 47 more not used	0.27	21.6	21.6

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
