### ISSUE TITLE
Add Omani Armored Plt (M60A3 Patton MBT x4) 1990

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5130]
### DB Selector

DB3K

### DBID to Copy

Facility 1933

### Hypothetical

No

### Name

Armored Plt (M60A3 Patton MBT x4)

### Country

Oman

### Service

Army

### In Commission

1990

### Sources

https://defencehub.live/attachments/db-01-jpg.23021/
https://en.wikipedia.org/wiki/Royal_Army_of_Oman
Oman	United States	1990	?	43	?	M-60A3 Patton-2	tank	43	?	1990	Second hand	Second-hand	0.84	36.12	36.12
Oman	United States	1995		30		M-60A3 Patton-2	tank	30		1996	Second hand	Second-hand; lease; aid	0.84	25.2	25.2

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
