### ISSUE TITLE
Add Omani Armored Plt (Chieftain Mk.5 MBT x 3) 1981

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5131]
### DB Selector

DB3K

### DBID to Copy

Facility 2995

### Hypothetical

No

### Name

Armored Plt (Chieftain Mk.5 MBT x 4) 

### Country

Oman

### Service

Army

### In Commission

1981

### Number in Service

15x

### Sources
https://commons.wikimedia.org/wiki/File:Salalah_to_Somerset_1982_Oman_%282077780954%29.jpg

Sipri
Oman	United Kingdom	1983	?	15		Chieftain Mk-5	tank	15	?	1984; 1985	New	Omani designation Qayis Al Ardh; Chieftain Mk-15 version

Oman	United Kingdom	1981		12		Chieftain Mk-5	tank	12		1981	Second hand	Second-hand; lease until bought in 1983; Omani designation Qayis Al Ardh; Chieftain Mk-7/2C version

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
