### ISSUE TITLE
Add Omani SAM Sec (Blowpipe MANPADS x 4)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5132]
### DB Selector

DB3K

### DBID to Copy

Facility 3821

### Hypothetical

No

### Name

SAM Sec (Blowpipe MANPADS x 4)

### Country

Oman

### Service

Army

### In Commission

1985

### Sources

Oman	United Kingdom	1982		200	?	Blowpipe	portable SAM	200	?	1985; 1986	New		0.06	12	12

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
