### ISSUE TITLE
[HIPRI] China, YJ-1000-1 LGB, can not fire because of lacking essential LGB codes

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5134]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4461

### Summary of Changes

- [ ] Add LGB codes of **"Illuminate at Launch"** & **"Supports Buddy Illumination"**

The YJ-1000-1 is missing two key properties of the LGB in the database, causing it to fail to fire.

### Sources

DB itself

YJ-1000-1 in database:
![image](https://github.com/user-attachments/assets/c84a1d51-abca-4fd0-a4d6-3666013274aa)
![image](https://github.com/user-attachments/assets/c59924e0-5ab0-4187-af12-b58cc347df6a)

As contrast, LT-2 could fire:
![image](https://github.com/user-attachments/assets/cd27abfd-170a-457d-a404-fea35105e2f1)
![image](https://github.com/user-attachments/assets/9426c2d8-7c9a-45da-91e3-237f88deed81)
![image](https://github.com/user-attachments/assets/97e513d3-071d-40a8-b576-eee517b345c8)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
