### ISSUE TITLE
PLARF: Silos, Mountain Shelters, Tunnel Networks 

### ISSUE THREAD

**Issue by RickDNiu** [PygmalionOfCyprus/cmo-db-requests#5141]
> I'm not getting into the effectiveness or resistance to weapons, but rather modeling and mechanics. 

- DF-5/5A Silo, Early

> Deemed too expensive in the 80s so few were built as an initial strike option. Missiles would be fueled (taking 1-3h), elevated to the ground (slowly, it's 200t full of hypergolic) and then hot launched. 

> DF-5 also 5A compatible. 

- DF-5B and 5C, Late

> Hot launch. Still needs to be pre fueled. 5C were all somewhat under construction (6+1 (training) in 631 along with 6 old 5B and 12+1 all new in 634). Don't know if 5B is upgradable. 

- DF-5 Series Mountain Shelter 

> Alternative basing for DF-5 as a second-strike option. Initially most were based in this way as silos were too expensive. They would be rolled out after experiencing enemy first strike, erected, fueled (taking 1-3h) and hot launched. 

> DF-5A included fuel loading improvements, which could push its time to the lower end of the 1-3h mark. 

- Tunnel Networks

> Extensive underground facilities that are not limited to DF-5s or even nuclear missiles: DF-31, DF-26, DF-21, DF-17, DF-15, DF-11 bases all have tunnel entrances spotted. They often have multiple entrances connected to base/roads and exits directly connected to launchpads. 

> As to DF-5 (12+1 under construction for 5C at 662, 6x 5B at older 661), this could permit them to be fueled underground.

**Comment by PygmalionOfCyprus** [comment]
I think the tunnel/mountain shelters are already sort of covered by the existing Tunnel/Tunnel Entrance entries. The "roll-out" behavior could be modelled with Lua.

Likewise the difference between hot/cold fueling, etc. The DB doesn't currently use the "ROF" value to simulate these multi-hour preparatory phases on a weapon; that's something else you'd want to model w/ Lua. (The logic is that it's much easier to delay a weapon firing via Lua vs. overriding the ROF values if they're too high.) As for weapon effects modelling, the DF-5 silos are already in the DB as of 508.
