### ISSUE TITLE
Add Czechoslovakian, Czech Republic and Slovakian SU-25K Frogfoot A

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5142]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4600

### Hypothetical

No

### Name

Su-25K Frogfoot A

### Country

Czechoslovakia, Slovakia, Czech Republic

### Service

Air Force

### In Commission

Czechoslovakia 1984-1992, Czech Republic 1993-2000, Slovakia, 1993-2003

### Number in Service

CR 24x, Slovakia 12x

### Sources

https://en.wikipedia.org/wiki/List_of_Sukhoi_Su-25_operators
https://www.airliners.net/photo/Czech-Republic-Air-Force/Sukhoi-Su-25K/1235699
https://www.researchgate.net/publication/294252048_Slovakia_sells_surplus_Su-25s_to_Armenia
https://www.redstar.gr/index.php?option=com_content&view=article&id=2260:su-25-frogfoot-attack-aircraft&catid=417&lang=en&Itemid=526

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
