### ISSUE TITLE
Add Slovakian Mig-29 Fulcrum A and AS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5143]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6806

### Hypothetical

No

### Name

Mig-29 Fulcrum A, Mig-29AS

### Country

Slovakia

### Service

Air Force

### In Commission

A 1993-2008, AS 2008-2023

### Number in Service

Mig-29A x24, Mig-29AS x10

### Other Changes

You have Ukrainian Mig-29AS in the DB as #6849. Could copy over and lose the Harm loadout

AS updates in 2006-2008
Comms link to NATINAMDS

### Sources

https://en.wikipedia.org/wiki/Mikoyan_MiG-29

AS info
https://web.archive.org/web/20171117070228/https://www.flightglobal.com/news/articles/ila-2008-slovakian-mig-upgrade-debuts-at-berlin-224271/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
