### ISSUE TITLE
Add Bulgarian Mig-23MLD Flogger K 1984-2002

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5144]
### DB Selector

DB3K

### DBID to Copy

Aircraft 2136

### Hypothetical

No

### Name

Mig-23MLD Flogger K

### Country

Bulgaria

### Service

Air Force

### In Commission

1984-2002

### Number in Service

21x

### Sources

https://www.arrow-aviation.nl/bvvs_mig23mld.html
https://x.com/BaA43A3aHY/status/1824496553882685891
https://www.oryxspioenkop.com/2022/07/beast-from-east-bulgarias-mig-25-foxbats.html

**Comment by FrangibleCover** [comment]
This is a "yes but no", Bulgaria had MiG-23MLDs of two types, the original export series (Izdeliye 22) which were MiG-23MLA airframes with the new radar and also, in 1991, ex-Soviet MiG-23MLDs (Izdeliye 18) with the aerodynamic changes and overwing CMDS. I've had a chat with some knowledgeable people on this but hadn't got around to finding proper sourcing. R-73s are also in question, certainly they weren't available for export in 1984 and even when they were exported to Bulgaria in 1989 with the MiG-29s, they didn't get the necessary APU-73 pylons to put them on the 23s. I'll try and get some stuff together tonight to clarify this.

**Comment by FrangibleCover** [comment]
https://www.flickr.com/photos/nilsmosberg/34282658875
https://old-forum.warthunder.com/index.php?/topic/492904-mikoyan-gurevich-mig-23-flogger-history-design-performance-dissection-updated-8102021/

Best I've got for you, you can see from the blade antenna on the nose of the flickr aircraft that it _is_ an MLD, but you can see from the absence of the wing root dog tooth that it's not an Izdeliye 18.

**Comment by bostonmyk** [comment]
Ok so what is your suggestion with a focus on getting this done?  My sense is if its a MLD and the other stuff isn't relevant to the game model we can just move forward with the request and drop the archers?

M

**Comment by FrangibleCover** [comment]
Two aircraft:
1. Copy MLD, cut R-73 (replace with R-60M where relevant), countermeasure dispensers and any agility improvement over ML (I can't remember if there is one). Name: Flogger K [MiG-23MLD izd. 22], date 1984-2004, 16x.
2. Copy MLD, cut R-73. Name: Flogger K [MiG-23MLD], date 1991-2004, 5x.

**Comment by bostonmyk** [comment]
This one is all set.

M

**Comment by Jkryos** [comment]
Added DB3K 509.
