### ISSUE TITLE
Fix fuel consumption for "A 629 Lac Chambon"

### ISSUE THREAD

**Issue by simast** [PygmalionOfCyprus/cmo-db-requests#5145]
### DB Selector

CWDB

### Affected DBID(s)

Ship 543

### Summary of Changes

Please fix fuel consumption for this ship. This is a fleet oiler but currently runs out of fuel in ~30mins at flank speed.

### Sources

No sources, but it's a fleet oiler... I think current fuel consumption is a bug.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
