### ISSUE TITLE
Wrong speed band for "MiG-15bis B Fagot"

### ISSUE THREAD

**Issue by simast** [PygmalionOfCyprus/cmo-db-requests#5146]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 1118

### Summary of Changes

This aircraft has wrong 55 kt speed at Band 3, Military Speed. Probably a typo and should be 550 kts instead.

### Sources

N/A

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
