### ISSUE TITLE
Add Australian M1A1 Abrams out of service date of 2024 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5147]
### DB Selector

DB3K

### Affected DBID(s)

Facility 2888

### Summary of Changes

Add out of service date of 2024

Replaced by M1A2C SEP which is in the db as a ground unit

### Sources

https://www.smh.com.au/politics/federal/australia-has-mothballed-a-550m-tank-fleet-ukraine-would-like-a-word-20240919-p5kbsx.html
https://en.defence-ua.com/news/australia_retires_the_m1a1_abrams_tanks_with_potential_future_use_by_the_armed_forces_of_ukraine-11437.html

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
