### ISSUE TITLE
Add GPS/GLONASS Guidance to BM-120 Missiles and version with EO guidance

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5149]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4202 and 4203

### Summary of Changes

Add GPS/GLONASS properties to weapons
Add EO version of missile with ships as valid targets

### Sources

https://www.iiss.org/online-analysis/missile-dialogue-initiative/2024/09/iranian-missile-deliveries-to-russia-escalating-military-cooperation-in-ukraine/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
