### ISSUE TITLE
Tu-134B Crusty - 1992

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#515]
### DB Selector

DB3K

### DBID to Copy

aircraft/4023/DB3K

### Hypothetical

No

### Name

Tu-134B Crusty - 1992

### Country

Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/12/caspian-amphibians-azerbaijans-elusive.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
