### ISSUE TITLE
Please add Arman ATBM SAM system for Iran Air Defence Forces

### ISSUE THREAD

**Issue by zulualpha91** [PygmalionOfCyprus/cmo-db-requests#5150]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Bty (Arman) - Joshan PESA / SAM Bty (Arman) - Najm-804 AESA

### Facility Type

SAM

### Country

Iran

### Service

Air Defence Force

### In Commission

2024

### Sensors

Only TELAR:
SAM Bty (Arman) - Joshan PESA
- 1x Joshan PESA
- Mk1 Eyeball

SAM Bty (Arman) - Najm-804 AESA
- 1x Najm-804 AESA (smaller Najm-802 with probably capability to guide SAM via SARH/TVM mode)
- Mk1 Eyeball

### Mounts

SAM Bty (Arman) - Joshan PESA
- 1x TELAR (3 missiles per launcher)
- 2x TEL (6 missiles per launcher)

SAM Bty (Arman) - Najm-804 AESA
- 1x TELAR (3 missiles per launcher)
- 2x TEL (6 missiles per launcher)

![image](https://github.com/user-attachments/assets/81b4ba5a-e548-404f-b05e-1126017abfc7)

### Magazines

30x Sayyad-3F

### Comments

- This SAM system exists in 2 variant, the one with Joshan PESA from Khordad-15 system and Najm-804 AESA radar
![image](https://github.com/user-attachments/assets/4b094e0b-2619-44ad-8ac5-fc280214414f)

- Sayyad-3F is basically improved Sayyad-3 with active radar seeker and probably ABM-optimised warhead + 4500kts target speed because of its role
![image](https://github.com/user-attachments/assets/e1b2cf8f-c79f-4b86-b415-9512262e3418)
![image](https://github.com/user-attachments/assets/e7f2bcff-5c48-43e3-8b95-93177a858401)

- Najm-804 were said to be smaller version of Najm-802. It should be still AESA radar but with shorter range and have illumination capability for SARH/TVM for Sayyad-3F missile. Should have max of 6 illumination targets 
![image](https://github.com/user-attachments/assets/b73623e0-8649-47b5-a46d-5f7ea95da975)

### Sources

- https://english.iswnews.com/33741/military-knowledge-arman-missile-system-tactical-sayyad/
- https://www.reuters.com/world/middle-east/iran-unveils-new-air-defense-weaponry-regional-tensions-ramp-up-irna-2024-02-17/
- https://x.com/Pataramesh/status/1765778261001269519
- https://x.com/IranDefense/status/1758802053554487544

**Comment by capcop98** [comment]
Sayyad-3F is likely use datalink for midcourse, like Sayyad-3C. 

https://x.com/A_z_im/status/1846133723479105810

**Comment by Jkryos** [comment]
Added DB3K 509.
