### ISSUE TITLE
Please add Azarakhsh short-range SAM system for Iran Air Defence Forces

### ISSUE THREAD

**Issue by zulualpha91** [PygmalionOfCyprus/cmo-db-requests#5151]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Bty (Azarakhsh)

### Facility Type

SAM

### Country

Iran

### Service

Air Defence Forces

### In Commission

2024

### Sensors

Per launcher:
1x Unknown AESA Radar, could be Kashef-99(Sensor 7033)
1x Seraj-1 TV camera (Sensor 6744)
1x Seraj-1 IR camera (Sensor 6743)

![image](https://github.com/user-attachments/assets/d6b297e4-685d-4de4-bc03-4505d1b38a69)

### Mounts

2x Azarakhsh(4 missiles per launcher)

### Magazines

16x Azarakhsh (Weapon 3941)

### Comments

- Its basically similar system to Taiwanese Antelope short-range SAM system. 
![image](https://github.com/user-attachments/assets/586a16ff-0d09-4481-a27e-6d50c631d2a8)

### Sources

- https://english.iswnews.com/34061/military-knowledge-azarakhsh-air-defense-system/
- https://armyrecognition.com/military-products/army/air-defense-systems/air-defense-vehicles/azarakhsh-air-defense-missile-system
- https://www.reuters.com/world/middle-east/iran-unveils-new-air-defense-weaponry-regional-tensions-ramp-up-irna-2024-02-17/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
