### ISSUE TITLE
Type 051B Deck Gun Correction

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5152]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1832, 3041

### Summary of Changes

Replace existing single 100mm mount with 100m/56 China H/PJ-33B [Type 79A] Twin

That mount exists on ship 3040

### Sources

https://x.com/AlexLuck9/status/1841782000241590712/photo/1
https://www.seaforces.org/marint/China-Navy-PLAN/Destroyers/Type-051B-Luhai-class-DDG.htm
https://weaponsystems.net/system/1095-Type-051B+class

**Comment by PygmalionOfCyprus** [comment]
How did I get this wrong...? Handled 509.
