### ISSUE TITLE
China, J-15B, PL-17 loadout

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#5153]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 6098

### Summary of Changes

- [ ] Add the same PL-17 loadouts (4x mix, 2x mix, 2x light) as J-16’s

In fact, there is another thing that seems strange to me: why do the PLAAF's Su-30MKK and Su-35SK have PL-17 mix loadout? I am curious as to how this conclusion was drawn. Shouldn't the J-15B, which has more similar electronic systems to the J-16, be the other one to carry the PL-17 instead? (When the F/A-18E is equipped with the AIM-174B, the PLAN should be even more eager to equip their new J-15B with the PL-17)

### Sources

DB itself

**Comment by PygmalionOfCyprus** [comment]
Air University reported that the PL-17 is deployed on the PLAAF's imported Su-30 and Su-35s: https://www.airuniversity.af.edu/Portals/10/CASI/documents/Research/Other-Topics/2022-08-15%20PLA%20Primer%203rd%20edition.pdf?ver=CHnk2NAOlCMqoqs7tGdjkw%3D%3D&timestamp=1660595152807

We have of course seen the famous picture of the PL-17s on the J-16s: https://www.twz.com/massive-pl-17-air-to-air-missile-seen-on-chinese-j-16-fighters

But we have not yet seen any evidence of PL-17s on the J-15s. Perhaps they are too heavy (doubtful), or maybe PLANAF just does not envision this "AWACS killer" missile being a critical part of their fleet defense mission? I'm sure we will see integration eventually but as far as we know it has not happened yet.

With that said I have added the loadouts, just not added them to the aircraft.

**Comment by LuigiP57** [comment]
> Air University reported that the PL-17 is deployed on the PLAAF's imported Su-30 and Su-35s: https://www.airuniversity.af.edu/Portals/10/CASI/documents/Research/Other-Topics/2022-08-15%20PLA%20Primer%203rd%20edition.pdf?ver=CHnk2NAOlCMqoqs7tGdjkw%3D%3D&timestamp=1660595152807
> 
> We have of course seen the famous picture of the PL-17s on the J-16s: https://www.twz.com/massive-pl-17-air-to-air-missile-seen-on-chinese-j-16-fighters
> 
> But we have not yet seen any evidence of PL-17s on the J-15s. Perhaps they are too heavy (doubtful), or maybe PLANAF just does not envision this "AWACS killer" missile being a critical part of their fleet defense mission? I'm sure we will see integration eventually but as far as we know it has not happened yet.
> 
> With that said I have added the loadouts, just not added them to the aircraft.

Okay, since it's being said by the Air University. However, I still have my doubts about this claim. I think the J-15B is a more reasonable option.
