### ISSUE TITLE
Add Indonesian Army SAM Plt (Mistral ATLAS x 2 ) 2014, Komodo

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5154]
### DB Selector

DB3K

### DBID to Copy

Facility 554

### Hypothetical

No

### Name

SAM Plt (Mistral ATLAS x 2) 

### Country

Indonesia

### Service

Army

### In Commission

2014

### Mounts

Komodo Mount with [2] Mistral II Rails.
No optics etc.

### Sources

https://x.com/tkmtomorixwb/status/1841622932331889058/photo/3
https://www.reddit.com/r/TankPorn/comments/18fwwga/air_defense_variant_of_pindad_komodo/
https://pindad.com/komodo-4x4-missile-launcher
Sipri
Indonesia	France	2012	?	136	?	Mistral	portable SAM	136	?	2013; 2014; 2015; 2016	New	For use with ATLAS launchers on Komodo APC produced in Indonesia	0.09	12.24	12.24

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
