### ISSUE TITLE
Add Indonesian Sam Plt/2 (NASAMS II) 2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5155]
### DB Selector

DB3K

### DBID to Copy

Facility 860

### Hypothetical

No

### Name

Sam Plt/2 (NASAMS II)

### Country

Indonesia

### Service

Air Force

### In Commission

2021

### Number in Service

2x

### Sensors

MPQ-64 Sentinel

### Loadout Options

Aim-120C

### Sources

https://x.com/Nebuchanedzar_I/status/1842105406539366463
https://x.com/defenceview_id/status/1698631467130323285

Sipri
Indonesia	United States	2017	?	200		AIM-120C AMRAAM	BVRAAM	200	?	2020; 2021	New	For NASAMS-2 SAM systems
Indonesia	United States	2017		2	?	MPQ-64 Sentinel	air search radar	2	?	2020; 2021	New	For NASAMS-2 SAM systems from Norway
Indonesia	Norway	2017		2	?	NASAMS-2	SAM system	2	?	2020; 2021	New	$77 m deal

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
