### ISSUE TITLE
Add Indonesian Army SAM Plt (MPCV x 2 ) 2014, Sherpa

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5156]
### DB Selector

DB3K

### DBID to Copy

Facility 554

### Hypothetical

No

### Name

Add Indonesian Army SAM Plt (MCVP ) 2014, Sherpa

### Country

Indonesia

### Service

Army

### In Commission

2014

### Sensors

EOSS day/thermal sensor suite with integrated laser rangefinder,

### Mounts

[2] Mistral 2
12.7 mm Machine Gun

### Sources

https://www.army-guide.com/eng/product3355.html
https://x.com/tkmtomorixwb/status/1841622932331889058/photo/2
https://www.reddit.com/r/TankPorn/comments/1cq69np/renault_sherpa_mcpv_mistral_of_indonesian_armys/
https://www.facebook.com/100064034714806/videos/renault-sherpa-mpcv-mobile-sam-units-of-the-indonesian-army-2nd-air-def-artiller/1254636462578928/
https://www.army-technology.com/projects/multi-purpose-combat-vehicle-mpcv/?cf-view
https://www.indomiliter.com/renault-sherpa-light-rantis-pengusung-rudal-mistral-rcws-arhanud-tni-ad/
Sipri
Indonesia France 2012 ? 136 ? Mistral portable SAM 136 ? 2013; 2014; 2015; 2016 New For use with ATLAS launchers on Komodo APC produced in Indonesia 0.09 12.24 12.24

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
