### ISSUE TITLE
Add Indonesian Arty Bty (155mm/39 M109A4+ Self Propelled Howizer x 6)  2018

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5157]
### DB Selector

DB3K

### DBID to Copy

Facility 3538

### Hypothetical

No

### Name

Arty Bty (155mm/39 M109A4+ Self Propelled Howizer x 6) 

### Country

Indonesia

### Service

Army

### In Commission

2018

### Number in Service

36x

### Sources

https://www.indomiliter.com/gelombang-kedua-m109a4-be-tiba-armed-tni-ad-kini-punya-36-unit-self-tracked-propelled-howitzer/
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indonesian_Army

Sipri
Indonesia	Belgium	2016		36	?	M-109A1 155mm	self-propelled gun	36		2017; 2018	Second hand but modernized	Second-hand but modernized before delivery; M-109A4 version

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
