### ISSUE TITLE
Add Indonesian Arty Bty (155mm/52 Caesar Self-Propelled Howitzer) 2015

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5158]
### DB Selector

DB3K

### DBID to Copy

Facility 2401

### Hypothetical

No

### Name

Arty Bty (155mm/52 Caesar Self-Propelled Howitzer)

### Country

Indonesia 

### Service

Army

### Sources

https://en.m.wikipedia.org/wiki/File:CAESAR_self-propelled_howitzer_of_the_Indonesian_Army.jpg
https://www.janes.com/osint-insights/defence-news/weapons/indonesia-conducts-loading-trials-of-155-mm-howitzers-for-rapid-insertion-operations
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indonesian_Army

sipri
Indonesia	France	2012		37		CAESAR 155mm	self-propelled gun	37	?	2014; 2015	New

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
