### ISSUE TITLE
Add Indonesian Arty Bty (PHL-90B [Type 90B] x 4) 2016

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5159]
### DB Selector

DB3K

### DBID to Copy

Facility 4321

### Hypothetical

No

### Name

Arty Bty (PHL-90B [Type 90B] x 4) 2016

### Country

Indonesia

### Service

Marines

### In Commission

2014

### Number in Service

4x

### Sources

https://armyrecognition.com/news/army-news/army-news-2022/indonesian-marines-carry-out-gun-drill-with-norinco-90b-mlrs

Sipri
Indonesia	China	2015		4		Type-90 122mm	self-propelled MRL	4		2016	New	Type-90B version

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
