### ISSUE TITLE
Add Indonesian Marine Mech Inf Sec (LVPT-7A1 IFV x 3) 2009

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5160]
### DB Selector

DB3K

### DBID to Copy

Facility 3689

### Hypothetical

No

### Name

Mech Inf Sec (LVPT-7A1 IFV x 3)

### Country

Indonesia

### Service

Marines

### In Commission

2009

### Sources

Don't do this
https://www.reddit.com/r/MilitaryPorn/comments/nhomvt/indonesian_marine_lvtp7_jump_into_the_sea_1080x720/
https://commons.wikimedia.org/wiki/File:LVTP-7A1_of_Indonesian_Marine_Corps.jpg
https://commons.wikimedia.org/wiki/File:Indonesian_Marine_Corps_LVTP-7_during_CARAT_2015.jpg
Sipri
South Korea	2009		10	?	LVTP-7	APC	10	?	2009	Second hand	Second-hand; LVTP-7A1 version; aid

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
