### ISSUE TITLE
Add Indonesian Marine Mech Inf Plt (BTR-50 APC x 3 )

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5161]
### DB Selector

DB3K

### DBID to Copy

Facility 2946

### Hypothetical

No

### Name

Mech Inf Plt (BTR-50 APC x 3 )

### Country

Indonesia 

### Service

Marines

### In Commission

1960s

### Sources
https://en.m.wikipedia.org/wiki/File:Indonesian_Korps_Marinir_BTR-50_on_Tanjung_Priok.jpg
https://www.reddit.com/r/MilitaryPorn/comments/bc0cif/indonesian_marine_corps_1080x724/
https://en.wikipedia.org/wiki/BTR-50#/media/File:BTR_50_P(M).jpg
https://www.dsaexhibition.com/indonesian-marine-corps-seeks-successor-for-aging-btr-50p-apc
Hope they did this on purpose
https://www.reddit.com/r/TankPorn/comments/18l5opq/indonesia_marine_corps_btr50_with_vegetation/
https://euro-sd.com/2022/12/articles/28435/the-indonesian-defence-environment/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
