### ISSUE TITLE
Add Indonesian Marine Mech Inf Plt (BVP-2 IFV x 3) 1998

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5162]
### DB Selector

DB3K

### DBID to Copy

Facility 2664

### Hypothetical

No

### Name

Mech Inf Plt (BVP-2 IFV x 3)

### Country

Indonesia

### Service

Marines

### In Commission

1998

### Other Changes

Remove Spandrel ATGM

### Sources

https://x.com/Jatosint/status/1793991355343204692
https://commons.wikimedia.org/wiki/File:BVP-2_Marinir_Indonesia.jpg
https://world-defense.com/threads/indonesian-armed-forces.3458/
Sipri 
Indonesia	Slovakia	1999	?	11		BMP-2	IFV	11		2000	Second hand	Probably second-hand; BVP-2 version
Indonesia	Slovakia	1998	?	9	?	BMP-2	IFV	9	?	1998	New	Possibly second-hand from Ukraine delivered via Slovakia
Indonesia	Ukraine	1998	?	2	?	BMP-2	IFV	2	?	1998	Second hand	Probably second-hand; delivered via Slovakia

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
