### ISSUE TITLE
Add Indonesian AAA Sec (20mm/80 Rhinemetal FK 20-2 [RH 202 Zwillingsflak] Towed x2)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5163]
### DB Selector

DB3K

### DBID to Copy

Facility 3850

### Hypothetical

No

### Name

AAA Sec (20mm/80 Rhinemetal FK 20-2 [RH 202 Zwillingsflak] Towed x2)

### Country

Indonesia

### Service

Army

### Sources

https://world-defense.com/threads/indonesian-armed-forces.3458/page-2
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indonesian_Army
https://en.wikipedia.org/wiki/Rheinmetall_Mk_20_Rh-202

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
