### ISSUE TITLE
Add Indonesian Army SAM Plt/2 (Rapier FSB1 Blindfire) 1986

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5164]
### DB Selector

DB3K

### DBID to Copy

Facility 1214

### Hypothetical

No

### Name

SAM Plt/2 (Rapier FSB1 Blindfire)

### Country

Indonesia

### Service

Army

### In Commission

1986

### Sources

Jane's Land Based Air Defense pg.269,299

Sipri 
Indonesia	United Kingdom	1985		21	?	Rapier	SAM system	21	?	1986; 1987	New	GBP83-100 m (USD100-120 m) deal (offsets incl technology transfer to Indonesia)	7	147	147
Indonesia	United Kingdom	1986		9	?	Rapier	SAM system	9	?	1987	New	$60 m deal (offsets incl technology transfer to Indonesia)	7	63	63
Indonesia	United Kingdom	1986		120	?	Rapier-1	SAM	120	?	1987	New	Offsets incl technology transfer to Indonesia	0.1	12	12
Indonesia	United Kingdom	1984		21	?	Rapier	SAM system	21	?	1985; 1986	New	GBP100 m deal (offsets incl technology transfer to Indonesia)	7	147	147
Indonesia	United Kingdom	1985		400	?	Rapier-1	SAM	400	?	1986; 1987	New	Offsets incl technology transfer to Indonesia	0.1	40	40
Indonesia	United Kingdom	1984		300	?	Rapier-1	SAM	300	?	1985; 1986	New	Offsets incl technology transfer to Indonesia	0.1	30	30

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
