### ISSUE TITLE
Add Indonesian Vehicle Vehicle (Vera-NG ELS) 2019

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5165]
### DB Selector

DB3K

### DBID to Copy

Facility 4039

### Hypothetical

No

### Name

Vehicle (Vera-NG ELS)

### Country

Indonesia

### Service

Air Force

### In Commission

2019

### Sources

https://defencesecurityasia.com/indonesia-vera-natuna-halimunan/

Sipri
Indonesia	Czechia	2017	?	1		VERA-E	air search system	1		2019	New	VERA-NG version

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
