### ISSUE TITLE
Add Indonesian SAM Plt (RBS 70 Mk1 MANPADS x 3)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5166]
### DB Selector

DB3K

### DBID to Copy

Facility 4300

### Hypothetical

No

### Name

SAM Plt (RBS 70 Mk1 MANPADS x 3)

### Country

Indonesia

### Service

Army

### In Commission

1982

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indonesian_Army
Sipri
Indonesia	Sweden	1981	?	150	?	RBS-70	portable SAM	150	?	1982	New

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
