### ISSUE TITLE
Add Indonesian Radar (Giraffe 40) 1982

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5167]
### DB Selector

DB3K

### DBID to Copy

Facility 1183

### Hypothetical

No

### Name

Radar (Giraffe 40)

### Country

Indonesia

### Service

Army

### In Commission

1982

### Number in Service

5x

### Sources

https://www.indomiliter.com/wp-content/uploads/2015/10/ok.jpg

Sipri
Indonesia	Sweden	1981	?	5	?	Giraffe-40	air search radar	5	?	1982	New	For use with RBS-70 SAM systems

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
