### ISSUE TITLE
Add Indonesian SAM Plt (RBS-70 Mk2 MANPADS x 3)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5168]
### DB Selector

DB3K

### DBID to Copy

Facility 1193

### Hypothetical

No

### Name

SAM Plt (RBS-70 Mk2 MANPADS x 3)

### Country

Indonesia

### Service

Army

### In Commission

1998

### Sources

https://www.youtube.com/watch?v=mxNlTUAtNx0
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indonesian_Army
https://www.indomiliter.com/pt-pindad-dan-saab-perpanjang-usia-operasional-rudal-rbs-70-arhanud-tni-ad/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
