### ISSUE TITLE
Add Indonesian Motor Inf Plt (Pandur II IFV [Steyr 30mm] x 3)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5169]
### DB Selector

DB3K

### DBID to Copy

Facility 2950

### Hypothetical

No

### Name

Motor Inf Plt (Pandur II IFV [Steyr 30mm] x 3)

### Country

Indonesia

### Service

Army

### In Commission

2024

### Other Changes

Remove Spike

### Sources

https://x.com/tweetmiliter/status/1841470079831363858
https://www.janes.com/osint-insights/defence-news/indonesia-signs-usd82-million-loi-for-pandur-ii-ifvs
https://www.youtube.com/watch?v=bzsXHO2M20Y

Sipri
Indonesia	Austria	2019		23		Pandur-2	IFV	11	?	2023	New	$80 m deal; from Czech production line; Indonesian designation Cobra

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
