### ISSUE TITLE
P 223 [AB 36 Class] -- Azerbaijan (Navy) 2000 2x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#517]
### DB Selector

DB3K

### DBID to Copy

ship/1539/DB3K

### Hypothetical

No

### Name

P 223 [AB 36 Class] -- Azerbaijan (Navy) 2000 2x

### Country

Azerbaijan

### Service

Navy

### In Commission

2000-

### Sensors

Changes Uncertain

### Mounts

40mm Bofors was replaced by twin 25mm MG just after transfer.

### Loadout Options

Changes Uncertain

### Other Changes

Changes Uncertain

### Sources

https://www.oryxspioenkop.com/2022/01/bridge-of-friendship-donated-turkish-ab.html?m=1&fbclid=IwAR37RZCGSPgIx222WIuObzIVHdoUpCQHsM7C_55Z1I6EIb_a5YopLyQ5uog
https://en.wikipedia.org/wiki/Azerbaijani_Navy
http://navypedia.org/ships/azerbaijan/aze_cf_araz.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494. Replaced primary weapons fit w/ 70-K and 2M-3 and stripped other armament (sans the 12.7mms) as indicated in article.
