### ISSUE TITLE
Add Exocet Blk-3 to 630 Halasan [KCR-60M Batch 1] 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5170]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3428

### Summary of Changes

Add 2 Dual Box mounts like ship #3431

### Sources

https://www.navalnews.com/naval-news/2024/05/indonesia-conducts-third-sinkex-in-under-a-year/

**Comment by KLABDB3K** [comment]
TNI AL stated that during the exercise, they also fired Black Shark heavy-weight and A244/S light-weight torpedoes from a Type-209/1400 submarine, KRI Alugoro (405), ... Also interesting. Can't check DB but think the Indonesian Type 209-1400 only has SUT torpedoes currently?

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

@KLABDB3K the Imp. Chang Bogos (the 209/1400s) do indeed have Black Shark torpedoes equipped currently.
