### ISSUE TITLE
A 09 Manawanui out of service date 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5171]
### DB Selector

DB3K

### Affected DBID(s)

Ship 3362

### Summary of Changes

Add out of service date of 2024. It ran aground and sunk.

### Sources

https://x.com/infogatecl/status/1842663341904503205
https://x.com/WarshipCam/status/1842684135963570323
https://x.com/TheSubHunter1/status/1842670737137758533
https://www.nzherald.co.nz/nz/hmnzs-manawanui-on-fire-and-tilting-badly-after-it-ran-aground-off-the-coast-of-samoa-last-night/44PLWNBV6RBVJHLVHARNGMOUKU/#google_vignette

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
