### ISSUE TITLE
More Ticonderoga Decommissionings 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5172]
### DB Selector

DB3K

### Affected DBID(s)

2860

### Summary of Changes

Add out of service date of 2024 for 2860 CG 54 Antietam as both CG54 and CG 55 Leyte Gulf are retired

### Sources

https://www.naval-technology.com/news/us-navy-decommissions-the-third-ticonderoga-class-in-one-month/

Related to issue
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/3831

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
