### ISSUE TITLE
Add AAA Plt/2 (23mm ZSU-23-2 Type 89 x 2) Ethiopia

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5173]
### DB Selector

DB3K

### DBID to Copy

Facility 2108

### Hypothetical

No

### Name

AAA Plt/2 (23mm ZSU-23-2 Type 89 x 2

### Country

Ethiopia

### Service

Army

### In Commission

2013

### Sources

https://x.com/HammerOfWar5/status/1842623207624331452/photo/1
https://x.com/HammerOfWar5/status/1813270507732472174/photo/4
Sipri
Ethiopia	China	2011	?	10	?	Type-89/ZSD-89	APC	10	?	2013	New		0.3	3	3

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
