### ISSUE TITLE
Update Ship A09 Manawanui - (ex Edda Fonn) 2019 - out of service date 05/10/24

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#5175]
### DB Selector

DB3K

### Affected DBID(s)

Ship A09 Manawanui - (ex Edda Fonn) 2019

### Summary of Changes

It sank off the coast of Samoa yesterday. Out of service date 05 October 2024. 

### Sources

https://www.msn.com/en-gb/news/news/content/ar-AA1rLyTm?ocid=sapphireappshare

**Comment by tbrandon517** [comment]
Duplicate of #5171
