### ISSUE TITLE
Add Ethiopian Arty Bty (BM-21 Grad MLRS x 6) 1977

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5176]
### DB Selector

Both

### DBID to Copy

Facility 2662

### Hypothetical

No

### Name

Arty Bty (BM-21 Grad MLRS x 6)

### Country

Ethiopia

### Service

Army

### In Commission

1977

### Sources

https://x.com/HammerOfWar5/status/1842917014391660827
https://x.com/HammerOfWar5/status/1834643208871027112
https://x.com/HammerOfWar5/status/1825529507786240386/photo/2

Sipri
Ethiopia	Soviet Union	1977		58	?	BM-21 Grad 122mm	self-propelled MRL	58	?	1977	New	Possibly Second-hand	0.6	34.8	34.8

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
