### ISSUE TITLE
Add Ethiopian Arty Bty (122mm/38 D-30 2A18 Towed Howitizer x 6) 1980

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5178]
### DB Selector

DB3K

### DBID to Copy

Facility 3032

### Hypothetical

No

### Name

Arty Bty (122mm/38 D-30 2A18 Towed Howitizer x 6)

### Country

Ethiopia

### Service

Army

### In Commission

1980

### Sources

https://x.com/HammerOfWar5/status/1835731408050127034
https://x.com/HammerOfWar5/status/1832114693743198477

Sipri
Ethiopia	Soviet Union	1980	?	210	?	D-30 122mm	towed gun	210	?	1980; 1981; 1982; 1983; 1984; 1985; 1986	New	Possibly Second-hand	0.35	73.5	73.5
Ethiopia	Serbia	2011	?	64	?	D-30 122mm	towed gun	64		2012	Second hand	Probably second-hand; sold and/or delivered via Bulgaria; designation uncertain (reported as '122mm howitzer')	0.14	8.96	8.96
Ethiopia	Kazakhstan	1999	?	100		D-30 122mm	towed gun	100		2000	Second hand	Ex-Kazakh	0.14	14	14
Ethiopia	Russia	1997	?	309	?	D-30 122mm	towed gun	309	?	1998; 2000	Second hand	Possibly second-hand; designation uncertain (reported as artillery of 100mm or more calibre)	0.14	43.26	43.26

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
