### ISSUE TITLE
MiG-29 Fulcrum C , 9-13

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#518]
### DB Selector

DB3K

### DBID to Copy

aircraft/1049/DB3K

### Hypothetical

Yes

### Name

MiG-29 Fulcrum C - 9-13

### Country

Azerbaijan

### Service

Air Force

### In Commission

IOC Uncertain

### Sensors

No Known Changes

### Mounts

No Known Changes

### Loadout Options

Can carry a variety of Turkish designed PGM kits for Soviet type ordnance (see source)

### Other Changes

No Known Changes

### Sources

https://www.oryxspioenkop.com/2021/09/hear-me-roar-azeri-mig-29s-put-on-show.html
https://www.oryxspioenkop.com/2022/01/knights-of-yerevan-armenias-su-30sm.html
https://www.oryxspioenkop.com/2022/01/bombs-from-baku-cataloguing-azerbaijans.html?m=1&fbclid=IwAR1eff-yjQLT1WMly_IWjFmUXddcGoe58SNQeDM8w1hWSBlYz2lmoX1bWW4
https://en.wikipedia.org/wiki/Azerbaijani_Air_Forces#Equipment
https://en.wikipedia.org/wiki/List_of_modern_equipment_of_the_Azerbaijani_Air_Force#Aircraft
https://en.wikipedia.org/wiki/Mikoyan_MiG-29#Variants

**Comment by PygmalionOfCyprus** [comment]
Added; IOC 2006.

A lot of the Azerbaijani bombs/guided munitions are a black hole but I did find enough info to add the QFAB-250-LG, which seems fairly representative. If you find info on the others feel free to post some weapon requests.

**Comment by tbrandon517** [comment]
I will keep an eye open for any good info.
