### ISSUE TITLE
Add Ethiopian SAM BN (SA-3c Goa [S-125M1 Neva-M])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5181]
### DB Selector

DB3K

### DBID to Copy

Facility 3462

### Hypothetical

Yes

### Name

SAM BN (SA-3c Goa [S-125M1 Neva-M])

### Country

Ethiopia

### Service

Army

### Number in Service

4x

### Other Changes

Different model than one currently in there. 4 missile launcher whereas the existing is 2

### Sources

https://en.wikipedia.org/wiki/S-125_Neva/Pechora
https://x.com/HammerOfWar5/status/1842977918458449951
https://x.com/mahmouedgamal44/status/1657426569856446465
https://x.com/africaken1/status/1325725681372827648?lang=en
https://www.ospreyflightsolutions.com/osprey-analysis-the-potential-impact-of-the-tigray-region-conflict-on-aviation/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
