### ISSUE TITLE
Add Ethiopian Mig-21bis Fishbed L 1978

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5182]
### DB Selector

DB3K

### DBID to Copy

Aircraft 1895

### Hypothetical

No

### Name

Mig-21bis Fishbed L

### Country

Ethiopia

### Service

Air Force

### In Commission

1978

### Number in Service

30x

### Sources
https://web.archive.org/web/20080119152836/http://www.acig.org/artman/publish/article_188.shtml
http://vietnam.warbirdsresourcegroup.org/mig21_operators.html
https://www.britmodeller.com/forums/index.php?/topic/234942608-mig-21-single-type-group-build/page/10/
Sipri
Ethiopia	Soviet Union	1985	?	30	?	MiG-21bis	fighter aircraft	30	?	1986; 1987; 1988	Second hand	Probably scond-hand	5	150	150

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
