### ISSUE TITLE
[HIPRI] China, Type 056A FFL, batch 3 should have OFC-3 TV/LLTV/IR/Laser Designator sensor package

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5185]
### DB Selector

DB3K

### Affected DBID(s)

Ship 4596 4722

### Summary of Changes

- [ ] Add **OFC-3 TV/LLTV/IR/Laser Designator {sensor 6323 6324 6325 6327)** to Type 056A Batch 3 [625 Bazhong]

The third batch of Type 056A has an OFC-3 integrated optical tracker installed.

### Sources

https://www.seaforces.org/marint/China-Navy-PLAN/Corvettes/Type-056A-Jiangdao-II-class.htm
https://www.globaldefensecorp.com/2020/06/21/china-launched-9th-type-056-corvette-in-2020/
https://www.usni.org/magazines/proceedings/2022/september/chinas-jiangdao-class-corvette-mainstay-first-island-chain
![image](https://github.com/user-attachments/assets/6664f2c5-cd4e-4ffa-b8d7-f803d354073d)
![image](https://github.com/user-attachments/assets/57a53812-014d-4a92-8527-e810d1de1145)

**Comment by PygmalionOfCyprus** [comment]
Actually I think there has been at least one OFC-3 on all the Type 056s (though it has been moved up to a higher location on the Batch 3), I just had it incorrectly listed as an IR-17. Handled 509.
