### ISSUE TITLE
Add Ethiopian Motor Rifle Plt (BTR-60PB APC x 3) 1985

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5186]
### DB Selector

DB3K

### DBID to Copy

Facility 2839

### Hypothetical

No

### Name

Motor Rifle Plt (BTR-60PB APC x 3)

### Country

Ethiopia

### Service

Army

### In Commission

1985

### Sources

https://en.topwar.ru/31540-semeystvo-btr-60-70-80-v-boevyh-deystviyah.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Ethiopian_Army
https://www.cia.gov/readingroom/docs/CIA-RDP90T00784R000100050001-9.pdf
Sipri
Ethiopia	Soviet Union	1984	?	250	?	BTR-60PB	APC	250	?	1985; 1986	Second hand	Second-hand	0.1	25	25

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
