### ISSUE TITLE
Add Ethiopian Mi-8T Hip C 1980

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5188]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6544

### Hypothetical

No

### Name

Mi-8T Hip C

### Country

Ethiopia

### Service

Airforce

### In Commission

1980

### Sources

https://web.archive.org/web/20080125170208/http://www.acig.org/artman/publish/article_189.shtml

Sipri
Ethiopia	Soviet Union	1980	?	24	?	Mi-8T	transport helicopter	24	?	1980; 1981; 1982	New		6	144	144

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
