### ISSUE TITLE
Add air superiority loadout to Ethiopian F-5E

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#5189]
### DB Selector

CWDB

### User(s)

#2557 - F-5E Tiger II (Ethiopia - 1976)

### Weapons Carried

4 x AIM-9B Sidewinder #88
3 x 275 USG Drop Tank #1410

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

650nm intercept radius

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Based on loadout #3450.
It's mentioned in multiple sources that Ethiopian F-5E's were used as interceptors and flew CAP mission during the Ogaden conflict. But the Ethiopian F-5E currently lacks the air superiority  loadout that other F-5E's have acces to. 

### Sources

Cooper, T. (2015). Wings over Ogaden: The Ethiopian-somali war 1978-1979. Helion & Company Limited
![afbeelding](https://github.com/user-attachments/assets/ab1c2956-ea76-402a-8f5e-cf5b2681da95)
![afbeelding](https://github.com/user-attachments/assets/f7487807-bac5-4249-b0d1-4245608b3859)

https://web.archive.org/web/20210927200840fw_/https://the-northrop-f-5-enthusiast-page.info/

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Also added to the F-5F.
