### ISSUE TITLE
Azerbaijani Hind Helos

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#519]
### DB Selector

DB3K

### DBID to Copy

DB3K aircraft 4896, 2375, 457, & 1657

### Hypothetical

No

### Name

Mi-35M Hind, M-24V Hind E, Mi-24P Hind F, & Mi-24G Super Hind

### Country

Azerbaijan

### Service

Air Force

### In Commission

Various

### Sensors

No Known Changes Per Type

### Mounts

No Known Changes Per Type

### Loadout Options

AT-9 Spiral-2 [9M120 Ataka-V] missiles for Mi-35M

AT-6 Spiral [9M114 Sturm-V] missiles for Mi-24V/P

R-2 Baryer ''Barrier'' missiles for Mi-24G

### Other Changes

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/Azerbaijani_Air_Forces#Equipment
https://en.wikipedia.org/wiki/List_of_modern_equipment_of_the_Azerbaijani_Air_Force#Aircraft

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/Azerbaijani_Air_Forces#Equipment
https://en.wikipedia.org/wiki/List_of_modern_equipment_of_the_Azerbaijani_Air_Force#Aircraft

**Comment by PygmalionOfCyprus** [comment]
Added 494. Looks like most of them came in 2010.
