### ISSUE TITLE
Update in service date of Egyptian IRIS-T to 2024 and unflag it as hypothetical

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5190]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3581

### Summary of Changes

Update IOC to 2024
Unmark it as hypothetical

### Sources
https://x.com/Willy_Egy/status/1843612316249797073
https://x.com/GSSReport/status/1843593728625357223/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
