### ISSUE TITLE
Add Egyptian Arty Plt (M270 MLRS) 2003

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5191]
### DB Selector

DB3K

### DBID to Copy

Facility 20

### Hypothetical

No

### Name

Arty Plt (M270 MLRS)

### Country

Egypt

### Service

Army

### In Commission

2003

### Number in Service

38x

### Sources

https://x.com/mahmouedgamal44/status/1843559689650614637/photo/3
https://x.com/TheEgyAnalysis/status/1717143138886668789
Sipri
Egypt	United States	2004	?	12		M-270 MLRS 227mm	self-propelled MRL	12		2005	New		1.2	14.4	14.4
Egypt	United States	2001		26		M-270 MLRS 227mm	self-propelled MRL	26		2003; 2004; 2005	New	Part of $354 m deal; 'FMF' aid	1.2	31.2	31.2

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
