### ISSUE TITLE
Add Egyptian Radar (TRS-2100 Tiger S) 1980

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5192]
### DB Selector

DB3K

### DBID to Copy

Facility 693

### Hypothetical

No

### Name

Radar (TRS-2100 Tiger S)

### Country

Egypt

### Service

Air Force

### In Commission

1980

### Number in Service

12x

### Sources

Sipri
Egypt	France	1979		12		TRS-2100 Tiger-S	air search radar	12		1980; 1981	New		4.75	57	57

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
