### ISSUE TITLE
Add Venezualian Mech Inf Plt (BMP-3  IFV x 3) 2011

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5193]
### DB Selector

DB3K

### DBID to Copy

Facility 3495

### Hypothetical

No

### Name

Mech Inf Plt (BMP-3  IFV x 3)

### Country

Venezuela

### Service

Army

### In Commission

2011

### Number in Service

123x

### Sources

https://www.reddit.com/r/MilitaryPorn/comments/545fet/bmp3_of_the_venezuelan_army_1000_x_714/
https://en.wikipedia.org/wiki/BMP-3
https://www.infodefensa.com/texto-diario/mostrar/3144824/41-brigada-blindada-ejercito-venezuela-prueba-capacidad-anfibia-bmp-3

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
