### ISSUE TITLE
Add Venezuelan Armored Plt (T-72B1 MBT x 3) 2009

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5194]
### DB Selector

DB3K

### DBID to Copy

Facility 2826

### Hypothetical

No

### Name

Armored Plt (T-72B1 MBT x 3)

### Country

Venezuela

### Service

Army

### In Commission

2009

### Number in Service

92x

### Sources

https://www.reddit.com/r/TankPorn/comments/i8g0wg/the_t72b1_tank_in_the_venezuelan_bolivarian_army/
https://en.wikipedia.org/wiki/T-72_operators_and_variants

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
