### ISSUE TITLE
YJ-12 Cruise Altitude Update

### ISSUE THREAD

**Issue by Matharx** [PygmalionOfCyprus/cmo-db-requests#5198]
### DB Selector

DB3K

### Affected DBID(s)

Guided Weapon 2863, 4459, 2862

### Summary of Changes

- Change cruise altitude from 50.2m AGL to 15m AGL

### Sources

> Its reported speed is around Mach 2 if launched from a low altitude and up to Mach 3.2 if launched from high altitude. According to Chinese sources, the YJ-12 maximum range is around 380 kilometers (the distance varies depending on launch altitude) **and its terminal attack altitude is 15 meters**

https://dev.navyrecognition.com/index.php?option=com_content&view=article&id=1504

**Comment by Luigi-II** [comment]
The game has a long unresolved problem: the altitude of the cruise missile varies in different flight phase. A typical ramjet cruise missile like YJ-12, flies high during cruise phase but drops to an extremely low sea-skimming altitude as it approaches its target. The current YJ-12 cruising altitude is set at 50m, making it unable to implement the original sea-skimming effect, which causes some "terminal interception" simulation errors. OSINT also indicates that its terminal height is between 5-15m, so my recommendation is to bring its cruising altitude back to **9.1m/30ft**, same in previous DB. Consistent with P-800, Hsiung Feng-III, Brahmos, typical ramjet AShM in game.
https://weaponsystems.net/system/1221-YJ-12
![image](https://github.com/user-attachments/assets/49a7d56e-e5e7-49b6-8776-adbda85e4772)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
