### ISSUE TITLE
Retirement of German Navy Seaking mk41

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#5199]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft #94

### Summary of Changes

The retirement of German Navy Sea King Mark 41s has provided an additional boost to Ukraine.

After 51 years of service, the German Navy retired its last Westland [Sea King](https://www.key.aero/sea-king) Mark 41 SAR helicopters on August 31, 2024. In service of the Marinefliegergeschwader 5 (Naval Aviation Squadron 5, MFG 5) at Nordholz Naval Air Station, these helicopters were also used for anti-surface vessel duties thanks to their Ferranti Seaspray radars and Sea Skua anti-ship missiles. Starting in 2019, the helicopter's role was gradually taken by its replacement, the NH90-NTH Sea Lion, a maritime transport variant of NH90-TTH in use by the German Army.

**Six of the last eight Sea King Mark 41As are due to be donated to the Ukrainian Navy Aviation**, while the remaining two will be preserved in Germany. The helicopters took part in various airshows in Austria, Belgium and France during summer 2024.

### Sources

[https://www.key.aero/article/german-navy-sea-king-retirement?hss_channel=tw-1070855149](url)

**Comment by Jkryos** [comment]
Updated DB3K 509.
