### ISSUE TITLE
Update US 2021/2022 Carrier Magazines to current weapons records

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#52]
### DB Selector

DB3K

### Affected DBID(s)

All US CVNs 2021, 2022

### Summary of Changes

Hi All

Would it be possible to update the aircraft mags on the carriers to include records for:

GBU-38v2/B
GBU-53B-SDBII
GBU-54v2/B
GBU-56v4/B[BLU-109]
GBU-56v4/B[Mk 84]
AN/ASG-35 IRST
AGM-154C-1 JSOW
AN/ASG-34 IRST
AGM-179 JAGM
AOEW AMP AN/ALQ-248
Hydra APKWS II 70mm Rocket [WGU-59/B, Rotary Wing Launch]

### Sources

Add aircraft to shift and use the air ops menu to check and see what's missing for current US aircraft.

**Comment by KushanGaming** [comment]
Done for DB495.

**Comment by bostonmyk** [comment]
Thanks and sorry
