### ISSUE TITLE
Mi-2A Hoplite - Azerbaijan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#520]
### DB Selector

DB3K

### DBID to Copy

aircraft/1497/CWDB

### Hypothetical

No

### Name

Mi-2A Hoplite - Azerbaijan

### Country

Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

Add

- Training

### Other Changes

None Known

### Sources

https://www.oryxspioenkop.com/2020/12/caspian-amphibians-azerbaijans-elusive.html
https://en.wikipedia.org/wiki/Azerbaijani_Air_Forces#Equipment
https://en.wikipedia.org/wiki/List_of_modern_equipment_of_the_Azerbaijani_Air_Force#Aircraft

**Comment by PygmalionOfCyprus** [comment]
Was added at some point in the past.

**Comment by tbrandon517** [comment]
https://cmano-db.com/aircraft/6947/

Forgot to close this when I saw it added.
