### ISSUE TITLE
SU-34 NVO in service 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5201]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 7297

### Summary of Changes

Doesn't appear to be a prototype but production models.

### Sources

https://x.com/GuyPlopsky/status/1843890573721383253
https://x.com/GuyPlopsky/status/1830474475919581406

**Comment by PygmalionOfCyprus** [comment]
The DB annotation doesn't refer to the Su-34NVO being a prototype, it refers to the fact that the Su-34NVO is in essence a 'prototype' variant of the upcoming Su-34M. Hence the comment "Su-34M Prototype" rather than just "Prototype".
