### ISSUE TITLE
China, YJ-12A ASCM, Lofted Trajectory entry

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5204]
### DB Selector

DB3K

### DBID to Copy

Weapon 4459

### Hypothetical

No

### Name

YJ-12A [Lofted Trajectory]

### Country

China

### Service

PLAAF & PLAN

### Other Changes

- [ ] Change its cruise altitude to **"120000ft"**.
- [ ] Modify its speed band to **"2000kt-2200kt-2400kt-2650kt (Mach 3-4)"**.
- [ ] Change its climb rate to appropriate **“1000m/s”**. On the one hand, maintaining a Mach 3 dive speed requires a more drastic dive (Reality). On the other hand, increasing the cruising altitude while avoiding the error caused by the low climb rate of the CJ-100 previously (Game).
- [ ] May give it **2x & 4x weapon record**. **Paltforms** like H-6K/J (Aircraft 4816 7134 7135 7184, light and heavy loadout) couldn't be better.

Numerous OSINT points out (I don't even need to stress this) that the YJ-12 has a "Lofted-Dive" trajectory. This trajectory gives the YJ-12 a faster cruise speed and terminal attack speed, similar to ballsitic missile. However, this also makes it a more vulnerable target for interception by the SAMs of the 21st century. I think we can put it in the game, after all who says the PLA won't use them that way.

### Sources

https://www.globalsecurity.org/military/world/china/cm-302.htm
https://weaponsystems.net/system/1221-YJ-12
![image](https://github.com/user-attachments/assets/bc46b29a-4513-47fc-b8c3-6b45a8d7e3b0)

**Comment by Matharx** [comment]
I believe the best way to tackle this would be a system similar to plot course where you could define flight profile for cruise missiles when allocating them. Because typically every cruise missile can use a hi-lo flight profile for extended range and speeds. And adding duplicates for every missile would clutter the database and loadout screen.

**Comment by Luigi-II** [comment]
> I believe the best way to tackle this would be a system similar to plot course where you could define flight profile for cruise missiles when allocating them. Because typically every cruise missile can use a hi-lo flight profile for extended range and speeds. And adding duplicates for every missile would clutter the database and loadout screen.

Yes, I totally agree with you, but, at the moment, our expectation for this complex simulation seem still unrealistic. I wanted to try to create a "test entry" to achieve this. According to the known descriptions, the YJ-12's Lofted trajectory has a very different performance, and it deserves a special simulation. If one day, when the simulation you mentioned are implemented, this weapon could just go into JUNKYARD.

**Comment by Luigi-II** [comment]
It does happen that some DB entries lose their functionality due to updates to the game simulation, so maybe it doesn't matter that much. It does happen that some DB entries lose their functionality due to updates to the game simulation, so maybe it doesn't matter that much. As a higher potential participant in a large-scale conflict, I think it's worthwhile.

**Comment by Luigi-II** [comment]
In fact, according to OSINT, it is more like a Kh-22 or PrSM Inc 4 (ramjet engine) under Lofted trajectory.

**Comment by PygmalionOfCyprus** [comment]
Okay, bear with me on this one. We know that the cruise missiles need an ability to define altitudes and more complex attack profiles. This doesn't just affect the Chinese missiles but a lot of Western and Russian weapons as well. We've held off on adding profile variants of things like LRASM since we're working to create a sim-side solution as suggested by @Matharox. So just hold on for now!

**Comment by LuigiP57** [comment]
> Okay, bear with me on this one. We know that the cruise missiles need an ability to define altitudes and more complex attack profiles. This doesn't just effect the Chinese missiles but a lot of Western and Russian weapons as well. We've held off on adding profile variants of things like LRASM since we're working to create a sim-side solution as suggested by @Matharox. So just hold on for now!

Couldn‘t be better!
