### ISSUE TITLE
Add Probe Refueling to Finnish C-295M [CC] and C-295M

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5205]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4570

### Summary of Changes

Add Probe Refueling

### Sources

https://x.com/3315Aviation/status/1844177910372135101/photo/1

**Comment by bostonmyk** [comment]
Looks like all Finnish C-295Ms got the probes in 2012. Add to 4569 as well.
https://www.defense-aerospace.com/finnish-c295s-fitted-with-in-flight-refueling-probe/

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
