### ISSUE TITLE
Add Albanian F-6C Farmer [Mig-19P Copy] 1964-2005

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5206]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3010

### Hypothetical

No

### Name

F-6C Farmer [Mig-19P Copy]

### Country

Albania

### Service

Air Force

### In Commission

1954-2005

### Loadout Options

Add 2x PL-2 Loadout

### Sources

https://x.com/Destroye83/status/1844321823615549481/photo/1
http://www.easternorbat.com/html/albanian_air_force_1988_eng.html
https://en.wikipedia.org/wiki/List_of_Albanian_Air_Force_aircraft

Sipri
Albania	China	1962	?	71	?	F-6	fighter aircraft	71	?	1965; 1967; 1968; 1971	New	Partly exchanged for Albanian MiG-19PM combat aircraft; incl some FT-6 version

Albania	China	1965	?	450	?	PL-2	SRAAM	450	?	1966; 1967; 1968; 1969; 1970; 1971	New	For F-6 and F-7 combat aircraft	0.04	18	18

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
