### ISSUE TITLE
Add Albanian SAM Bn (HQ-2 [SA-2 Copy])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5208]
### DB Selector

DB3K

### DBID to Copy

Facility 760

### Hypothetical

No

### Name

SAM Bn (HQ-2 [SA-2 Copy])

### Country

Albania

### Service

Air Force

### In Commission

1972-

### Number in Service

2x

### Sources

https://www.oryxspioenkop.com/2023/03/the-north-korea-of-europe-listing.html
http://www.easternorbat.com/html/albanian_air_force_1988_eng.html
https://en.topwar.ru/45728-kitayskiy-zenitno-raketnyy-kompleks-nq-2.html
Sipri
Albania	China	1970	?	2	?	S-75 Dvina	SAM system	2	?	1971; 1972	New		17.87	35.74	35.74

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
