### ISSUE TITLE
Add Albanian AAA Bty (100mm KS-19 x6, Fire Can FCR] 1960

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5209]
### DB Selector

DB3K

### DBID to Copy

Facility 4356

### Hypothetical

No

### Name

AAA Bty (100mm KS-19 x6, Fire Can FCR]

### Country

Albania

### Service

Army

### Sources

https://www.oryxspioenkop.com/2023/03/the-north-korea-of-europe-listing.html
Sipri
Albania	Soviet Union	1955	?	28	?	SON-9	fire control radar	10	?	1960; 1961	Second hand	Supplier uncertain; possibly second-hand; for use with S-60 57mm; KS-12 85mm and KS-19 100mm AA guns

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
