### ISSUE TITLE
Ka-27PS Helix D - 1992

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#521]
### DB Selector

DB3K

### DBID to Copy

aircraft/2372/DB3K

### Hypothetical

No

### Name

Ka-27PS Helix D - 1992

### Country

Azerbaijan

### Service

Air Force

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/12/caspian-amphibians-azerbaijans-elusive.html
https://en.wikipedia.org/wiki/Azerbaijani_Air_Forces#Equipment

**Comment by PygmalionOfCyprus** [comment]
Added 494.
