### ISSUE TITLE
Add Albanian AAA Bty (37mm Type 65 Twin x 4)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5210]
### DB Selector

DB3K

### DBID to Copy

Facility 70

### Hypothetical

No

### Name

AAA Bty (37mm Type 65 Twin x 4)

### Country

Albania

### Service

Army

### In Commission

1964-

### Sources

https://www.oryxspioenkop.com/2023/03/the-north-korea-of-europe-listing.html

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
