### ISSUE TITLE
Add Albanian AAA Bty (57mm S-60 x 6, RPK-1M1 FCR)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5211]
### DB Selector

DB3K

### DBID to Copy

Facility 2661

### Hypothetical

No

### Name

AAA Bty (57mm S-60 x 6, RPK-1M1 FCR)

### Country

Albania

### Service

Army

### Sources

https://www.oryxspioenkop.com/2023/03/the-north-korea-of-europe-listing.html

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
