### ISSUE TITLE
Add Albanian SAM Plt (CH-SA-3 [HN-5A] MANPADS x 4) 1978

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5212]
### DB Selector

DB3K

### DBID to Copy

Facility 748

### Hypothetical

No

### Name

SAM Plt (CH-SA-3 [HN-5A] MANPADS x 4)

### Country

Albania

### Service

Army

### In Commission

1978

### Sources

https://en.wikipedia.org/wiki/HN-5
https://en.topwar.ru/206708-kitajskie-pzrk-skopirovannye-s-inostrannyh-obrazcov.html

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
