### ISSUE TITLE
Add Aim-9P and 69mm SNEB Rocket Loadout to Pakistani F-6s

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5213]
### DB Selector

DB3K

### User(s)

Aircraft 2771

### Weapons Carried

AAW (looks like 1974 so can probably swap out the AIM-9B in the existing loadout 13324
[2] Aim-9P
[2] 760 Drop Tank

Strike
[2] Matria 8-Tube SNEB 68mm Pods
[2) 760 Drop Tank

### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

Aim-9P
https://x.com/Destroye83/status/1844359009555579390/photo/1
https://x.com/Destroye83/status/1844319815814803806/photo/1
https://x.com/Destroye83/status/1844307588294619632/photo/1
Sipri
Pakistan	United States	1974		500	?	AIM-9J/P Sidewinder	SRAAM	500	?	1974	New	Second-hand AIM-9B version rebuilt after delivery to AIM-9J in Pakistan with US-supplied components

68mm SNEB
https://x.com/Destroye83/status/1844357299105824896/photo/1
https://x.com/Destroye83/status/1844360577331888419/photo/1
https://x.com/Destroye83/status/1844351364031218105/photo/1

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
