### ISSUE TITLE
Add Albanian Navy MPK-389 [Pr.122bis Kronshadt]

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5214]
### DB Selector

DB3K

### DBID to Copy

Ship 248

### Hypothetical

Yes

### Name

MPK-389 [Pr.122bis Kronshadt]

### Country

Albania

### Service

Navy

### In Commission

1958-2012

### Number in Service

2x

### Sources

https://www.navypedia.org/ships/russia/ru_es_artillerist.htm
https://en.m.wikipedia.org/wiki/File:Project122bis-2007-Pashaliman.jpg
https://en.wikipedia.org/wiki/Kronshtadt-class_submarine_chaser

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
