### ISSUE TITLE
Copy Aircraft #4013 - KC-390 Millennium (Brazil - 2018) for Morocco, UAE? , Chile? 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#5217]
### DB Selector

DB3K

### DBID to Copy

Copy Aircraft #4013 - KC-390 Millennium (Brazil - 2018) 

### Hypothetical

No

### Name

C-390 Millennium (Morocco - 2025) (UAE - 2025) (Chile - 2025)

### Country

Morocco (Possible/probably UAE & CHILE) 

### Service

Air Force 

### In Commission

2024-2025

### Number in Service

To be confirmed. 

### Sensors

Straight copy. 

### Mounts

Straight copy. 

### Loadout Options

Copy. 

### Other Changes

Nil identified. 

### Sources

Appears highly likely if not unequivocally confirmed for Morocco and likely for UAE and Chile (subject to confirmation) .
https://www.scramble.nl/military-news/morocco-new-customer-for-the-c-390-millennium
https://www.armyrecognition.com/news/aerospace-news/2024/morocco-selects-brazilian-embraer-c-390-millennium-to-replace-c-130-hercules-transport-fleet
https://x.com/kharchoufibra/status/1843673203115471156?t=6dsvn67bbEvS9RO48qRntw&s=19
Graphic from Embraer is pretty intriguing ?

**Comment by KLABDB3K** [comment]
https://masarat.institute/%d8%b1%d8%b3%d9%85%d9%8a%d9%8b%d8%a7%d8%8c-%d8%a7%d9%84%d9%85%d8%ba%d8%b1%d8%a8-%d9%88%d8%a7%d9%84%d8%a5%d9%85%d8%a7%d8%b1%d8%a7%d8%aa-%d8%b3%d9%8a%d8%b5%d8%a8%d8%ad%d8%a7%d9%86-%d9%82%d8%b1%d9%8a/
Translated from above link it makes the Morocco Brazil deal seem cut and dry with the technology transfer deals signed off in April 2023.

**Comment by KLABDB3K** [comment]
India and Saudi offset technology transfer and production deals being proferred too. Too soon to speculate. WIP

**Comment by PygmalionOfCyprus** [comment]
Added for Morocco 509.
