### ISSUE TITLE
Out of Service Date of Thai A-7E Corsair 2007 and they were operated by the Navy

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5218]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 964

### Summary of Changes

Add out of service date of 2007
Operated by the Navy, not AF (and their nose cones were black!). I promise it's not pedantry; I just surprised myself.

### Sources

https://www.militaryimages.net/threads/royal-thai-defense-force.6782/page-9
https://en.wikipedia.org/wiki/LTV_A-7_Corsair_II
https://www.jetphotos.com/photo/10685522

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
