### ISSUE TITLE
Add Bangladesh F-6C Farmer [Mig-19 Copy] 1977-1998

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5219]
### DB Selector

DB3K

### DBID to Copy

Aircraft 3010

### Hypothetical

No

### Name

F-6C Farmer [Mig-19 Copy]

### Country

Bangladesh

### Service

Air Force

### In Commission

1977-1998

### Number in Service

24x,+12,+40

### Loadout Options

Add [2] 8 Sneb 68mm Rocket loadout

### Sources
https://x.com/Destroye83/status/1844671229996699870
https://www.airhistory.net/photo/548635/8626
https://warmachinesdrawn.blogspot.com/2020/10/shenyang-f-6-various-asian-users.html
https://x.com/Destroye83/status/1844747990574969027/photo/1
Bangladesh	China	1975	?	24	?	F-6	fighter aircraft	24	?	1976; 1977; 1978	Second hand	Second-hand; incl some FT-6 trainer version; no. delivered could be up to 36	2	48	48

Bangladesh	China	1980	?	12	?	F-6	fighter aircraft	12	?	1983	Second hand	Probably Second-hand; status uncertain	2	24	24
Bangladesh	Pakistan	1989		40	?	F-6	fighter aircraft	40	?	1990	Second hand	Second-hand; aid; incl some FT-6 trainer version	2	80	80

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
