### ISSUE TITLE
Vehicle (KORAL Mobile Jammer+ELINT) (Multi-Purpose)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#522]
### DB Selector

DB3K

### DBID to Copy

facility/3015/DB3K

### Hypothetical

No

### Name

Vehicle (KORAL Mobile Jammer+ELINT) (Multi-Purpose)

### Country

Azerbaijan

### Service

Army

### In Commission

IOC Uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
