### ISSUE TITLE
Add Cypriot SAM Sec (SA-7b Grail [9K32M Stela-2M] MANPADS x 3) 1984

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5220]
### DB Selector

DB3K

### DBID to Copy

Facility 2657

### Hypothetical

No

### Name

SAM Sec (SA-7b Grail [9K32M Stela-2M] MANPADS x 3)

### Country

Cyprus

### Service

Army

### In Commission

1984

### Sources

Cyprus	Yugoslavia	1987		300	?	Strela-2	portable SAM	300	?	1988	New	
Cyprus	Syria	1984	?	50	?	Strela-2	portable SAM	50	?	1984	Second hand	Second-hand

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
