### ISSUE TITLE
Add Cypriot Armored Plt (T-80U/UD MBT x 3)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5221]
### DB Selector

DB3K

### DBID to Copy

Facility 3120

### Hypothetical

Yes

### Name

Armored Plt (T-80U/UD MBT x 3)

### Country

Cyprus

### Service

Army

### In Commission

1996

### Number in Service

41x, +41

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Cypriot_National_Guard
https://www.reddit.com/r/TankPorn/comments/1dncwjc/cypriot_national_guard_t80u_main_battle_tank_on/
Sipri
Cyprus	Russia	2010		41		T-80U	tank	41		2010; 2011	Second hand	Second-hand; EUR115 m deal; incl 14 T-80UK version
Cyprus	Russia	1996		41		T-80U	tank	41		1996; 1997	New	Deal worth $174 m

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
