### ISSUE TITLE
Add Cypriot Motor Inf (VAB APC x 4) 1985

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5222]
### DB Selector

DB3K

### DBID to Copy

Facility 771

### Hypothetical

No

### Name

Motor Inf (VAB APC x 4)

### Country

Cyprus

### Service

Army

### In Commission

1985

### Sources
https://www.militaryimages.net/media/vab-vtt-cyprus-national-guard.12827/
Sipri
Cyprus	France	1984		100		VAB-VTT	APC	100	?	1985; 1986; 1987; 1988	New	Incl 4 VAB-PC CP version; 4-wheeled version

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
