### ISSUE TITLE
Add Cypriot Armored Plt (AMX-30B2 MBT x 4) 1988

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5223]
### DB Selector

DB3K

### DBID to Copy

Facility 773

### Hypothetical

No

### Name

Armored Plt (AMX-30B2 MBT x 4)

### Country

Cyprus

### Service

Army

### In Commission

1988

### Sources

https://www.reddit.com/r/MilitaryPorn/comments/907g1s/1028x460_amx30b2s_of_the_cyprus_national_guard/
https://www.flickr.com/photos/bronpancerna/23821800071
Sipri
Cyprus	France	1987		15		AMX-30B2	tank	15		1988	New	
Cyprus	France	1989		35		AMX-30B2	tank	35	?	1990; 1991	New	Part of $115 m deal	2.25	78.75	78.75

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
