### ISSUE TITLE
Add Cypriot Mech Inf Plt (BMP-3 IFV x 3) 1995

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5224]
### DB Selector

DB3K

### DBID to Copy

Facility 2818

### Hypothetical

No

### Name

Mech Inf Plt (BMP-3 IFV x 3) 

### Country

Cyprus

### Service

Army

### In Commission

1995

### Number in Service

43x

### Sources

https://defenceredefined.com.cy/bmp-3-national-guards-russian-made-ifv-and-first-conclusions-from-the-ukraine-war-photos-video/
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Cypriot_National_Guard
sipri
Cyprus	Russia	1995		43		BMP-3	IFV	43		1995; 1996	New	Deal worth $68 m

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
