### ISSUE TITLE
Add Cypriot, Ukrainian  Arty Bty (155mm T RF-1 Towed Howitzer x 6)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5225]
### DB Selector

DB3K

### DBID to Copy

Facility 2397

### Hypothetical

No

### Name

Arty Bty (155mm TRF-1 Towed Howitzer x 6)

### Country

Cyprus, Ukraine

### Service

Army

### In Commission

Cyprus 1991, Ukraine 2022

### Number in Service

12x

### Sources

Ukraine
https://mil.in.ua/en/news/trf1-howitzers-already-at-the-frontline/
https://mil.in.ua/en/articles/155mm-artillery-of-ukraine/#google_vignette

Cyprus
https://www.militaryimages.net/threads/cypriot-national-guard.8872/
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Cypriot_National_Guard
Sipri
Cyprus	France	1989	?	12		TR-F-1 155mm	towed gun	12	?	1991	New

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
