### ISSUE TITLE
Add 2023 Out of service date for Cypriot Hinds

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5226]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 7233

### Summary of Changes

Add out of service date of 2023

Serbs purchased these

### Sources

https://www.scramble.nl/military-news/first-overhauled-serbian-mi-35p-attack-helicopters
https://www.scramble.nl/military-news/cyprus-mi-35s-for-sale

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
