### ISSUE TITLE
Add Cypriot SSM Bty (MM.40 Exocet) 1994

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5227]
### DB Selector

DB3K

### DBID to Copy

Facility 365

### Hypothetical

No

### Name

SSM Bty (MM.40 Exocet)

### Country

Cyprus

### Service

Navy

### In Commission

1994

### Number in Service

1x

### Other Changes

Upgraded to Block 3c Exocet 2025

### Sources
https://www.militaryimages.net/threads/cypriot-national-guard.8872/page-2
https://defenceredefined.com.cy/exocet-mm40-blk-3-tremendous-upgrade-for-the-capabilities-of-national-guards-navy-photos-and-videos/

Sipri
Cyprus	France	1989		1	?	Exocet CDS	coastal defence system	1	?	1994	New

**Comment by PygmalionOfCyprus** [comment]
Handled 509. They were actually Blk II.
