### ISSUE TITLE
Add Cypriot SA.342L Gazelle 1988

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5228]
### DB Selector

DB3K

### DBID to Copy

Aircraft 6285

### Hypothetical

No

### Name

SA.342L Gazelle

### Country

Cyprus

### Service

Air Force

### In Commission

1988

### Number in Service

4x

### Sources

https://www.militaryimages.net/threads/cypriot-national-guard.8872/page-2

Sipri
Cyprus	France	1987		4		SA-342 Gazelle	light helicopter	4		1988	New	SA-342L-1 armed version (with HOT anti-tank missiles)	0.85	3.4	3.4
Cyprus	France	1987		500	?	HOT	anti-tank missile	500	?	1988	New	For SA-342L helicopters and VAB-VCAC tank destroyers; HOT-2 version	0.02	10	10

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
