### ISSUE TITLE
[HIPRI] PCL-181 [SH-15] SPH, missing GP155B mount after adding ERFB-BB/-RA

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5229]
### DB Selector

DB3K

### Affected DBID(s)

Facility 4329 4331 4332

### Summary of Changes

- [ ] Re-adding **GP155B (Weapon 4477)** to their mount

### Sources

https://www.janes.com/osint-insights/defence-news/norinco-marketing-sh-15-155-mm-artillery-system-for-export

> It can fire conventional ammunition as well as the NORINCO GP155 laser homing projectile, **GP155B satellite guided projectile**, and the GP155G terminally guided top attack projectile.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
