### ISSUE TITLE
SSM Sec [LORA]

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#523]
### DB Selector

DB3K

### DBID to Copy

facility/2904/DB3K

### Hypothetical

No

### Name

SSM Sec [LORA]

### Country

Azerbaijan

### Service

Army

### In Commission

IOC Uncertain

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces#Surface-to-surface_missile
https://www.thedrive.com/the-war-zone/36777/everything-we-know-about-the-fighting-that-has-erupted-between-armenia-and-azerbaijan
https://www.thedrive.com/the-war-zone/36877/video-points-to-azerbaijans-first-use-of-israeli-made-ballistic-missile-against-armenia

**Comment by PygmalionOfCyprus** [comment]
Added 494.
