### ISSUE TITLE
Please add Bulgaria as user of the IRIS-T SAM system

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#5232]
### DB Selector

DB3K

### DBID to Copy

Facility # 3987

### Hypothetical

No

### Name

IRIS-T SLS

### Country

Bulgaria

### Service

Army

### In Commission

2025

### Number in Service

1 and more in 2032...

### Sources

[https://www.diehl.com/defence/en/press-and-media/news/diehl-defence-welcomes-bulgaria-in-the-iris-t-slm-user-family/](url)
[https://bulgarianmilitary.com/2024/10/10/additional-agreement-signed-for-iris-t-delivery-to-bulgaria/](url)
[https://armstransfers.sipri.org/ArmsTransfer/TransferRegister](url)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
