### ISSUE TITLE
Add Venezuelan Arty Bty (152mm/48 2S19 MSTA-S Self Propelled Howitzer x 6) 2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5233]
### DB Selector

DB3K

### DBID to Copy

Facility 1953

### Hypothetical

No

### Name

Arty Bty (152mm/48 2S19 MSTA-S Self Propelled Howitzer x 6)

### Country

Venezuela

### Service

Army

### In Commission

2012

### Number in Service

48x

### Sources

https://x.com/ConflictsW/status/1759681728367444354
https://en.wikipedia.org/wiki/2S19_Msta-S
https://armyrecognition.com/news/army-news/army-news-2011/venezuela-11-july-2011-news-uk
sipri
Venezuela	Russia	2009		48	?	2S19 MSTA-S 152mm	self-propelled gun	48	?	2011; 2012; 2013	New	2S19M version	1.75	84	84

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
