### ISSUE TITLE
Add Venezualan Arty Bty (BM-30 Smerch MLRS x 6) 2013

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5234]
### DB Selector

DB3K

### DBID to Copy

Facility 2117

### Hypothetical

No

### Name

Arty Bty (BM-30 Smerch MLRS x 6) 2013

### Country

Venezuela

### Service

Army

### In Commission

2013

### Number in Service

12x

### Sources

https://x.com/somos_ejercito/status/1590824180001423360
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Venezuelan_Army
https://www.arabianbusiness.com/gallery/venezuelan-army-tests-russian-rockets-550013
Sipri
Venezuela	Russia	2009	?	12	?	BM-9A52 Smerch	self-propelled MRL	12	?	2013	New		1.2	14.4	14.4

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
