### ISSUE TITLE
Add Venezuelan Motor Inf Plt (BTR-80 APC x 3) 2012

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5235]
### DB Selector

DB3K

### DBID to Copy

Facility 2354

### Hypothetical

No

### Name

Motor Inf Plt (BTR-80 APC x 3)

### Country

Venezuela

### Service

Army

### In Commission

2012

### Number in Service

x114

### Mounts

Use the same gun moutins as VN-1 (2a-72+MG) so can copy that as baseline.

### Sources

https://www.reddit.com/r/TankPorn/comments/1fq5cin/bolivarian_army_of_venezuela_t72b1_bmp3m_btr80a/
https://en.wikipedia.org/wiki/BTR-80
Sipri
Venezuela	Russia	2009		114	?	BTR-80A	IFV	114	?	2011; 2012; 2013; 2014	New		0.9	102.6	102.6

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
