### ISSUE TITLE
Add Venezualan Arty Bty (BM-21 Grad MLRS x 6) 2011

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5236]
### DB Selector

DB3K

### DBID to Copy

Facility 2834

### Hypothetical

No

### Name

Arty Bty (BM-21 Grad MLRS x 6) 

### Country

Venezuela

### Service

Army

### In Commission

2011

### Number in Service

24x

### Sources

https://commons.wikimedia.org/wiki/File:BM-21_Grad_VEN.jpg
https://www.facebook.com/favclub/posts/el-bm-21-apodado-grad-granizo-es-un-sistema-m%C3%BAltiple-de-lanzamiento-de-cohetes-d/10157050971931122/?locale=es_LA
https://www.defencetalk.com/military/photos/bm-21-grad.45771/
Sipri
Venezuela	Russia	2009	?	24	?	BM-21 Grad 122mm	self-propelled MRL	24	?	2011	Second hand	Probably second-hand (but possibly modernized before delivery); BM-21-1 version	0.24	5.76	5.76

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
