### ISSUE TITLE
Add Venezuelan Armored Plt (Scorpion Light Tank x 3) 1989

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5237]
### DB Selector

DB3K

### DBID to Copy

Facility 2399

### Hypothetical

No

### Name

Armored Plt (Scorpion Light Tank x 3) 

### Country

Venezuela

### Service

Army

### In Commission

1989-Present

### Number in Service

84x

### Other Changes

Slightly modernized in 2021 with Thermal Sites

### Sources
https://x.com/SA_Defensa/status/1840128393011974435/photo/1
https://x.com/SA_Defensa/status/1843111236130742450
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Venezuelan_Army
https://x.com/Raphviva/status/1653645880870813698
https://x.com/ConflictsW/status/1383808179406999554
Sipri
Venezuela	United Kingdom	1988		84	?	Scorpion-90	light tank	84	?	1989; 1990; 1991	New	Part of $85 m deal	1	84	84

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
