### ISSUE TITLE
Add Venezuelan Motor Inf Plt (E-11 Urutu APC x 4) 1984

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5238]
### DB Selector

DB3K

### DBID to Copy

Facility 2202

### Hypothetical

No

### Name

Motor Inf Plt (E-11 Urutu APC x 4)

### Country

Venezuela

### Service

Marines

### In Commission

1984

### Number in Service

38x

### Other Changes

Modernized with Thermal Imager 2013
Mark as cargo. Marines use it

### Sources

https://x.com/ConflictsW/status/1223006670688866305
https://x.com/ConflictsW/status/1751315906607612078

Venezuela	Brazil	1983		38	?	EE-11 Urutu	APC	38	?	1984	New	Incl IFV; ARV and command post versions

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
