### ISSUE TITLE
Armored Plt (AMX-30V MBT x 4)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5239]
### DB Selector

DB3K

### DBID to Copy

Facility 773

### Hypothetical

No

### Name

Armored Plt (AMX-30V MBT x 4)

### Country

Venezuela

### Service

Army

### In Commission

1974

### Number in Service

82x

### Other Changes

Slight upgrades to Fire control and GPS upgrades and an engine replacement

### Sources

https://en.wikipedia.org/wiki/AMX-30
https://www.reddit.com/r/TankPorn/comments/i83sz8/venezuelan_amx30v_tanks_upgraded_amx30b_they_got/
https://www.infodefensa.com/texto-diario/mostrar/2964303/venezuela-completa-repotenciacion-nuevo-lote-tanques-amx-30
Venezuela	France	1972	?	82	?	AMX-30B	tank	82	?	1973; 1974	New

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
