### ISSUE TITLE
Add Venezuelan Mech Inf (LVTP-7 IFV x 3) 1971

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5240]
### DB Selector

DB3K

### DBID to Copy

Facility 3689

### Hypothetical

No

### Name

Mech Inf (LVTP-7 IFV x 3)

### Country

Venezuela

### Service

Marines

### In Commission

1971

### Sources

https://www.militaryimages.net/media/lvtp-7-venezuelan-marine-corps.29435/
https://worlddefencenews.blogspot.com/2012/12/venezuelan-marine-corps-has-planned-to.html
Sipri
Venezuela	United States	1971	?	11		LVTP-7	APC	11		1973	New	Incl 1 CP and 1 ARV version	0.9	9.9	9.9

**Comment by PygmalionOfCyprus** [comment]
Handled 509.

**Comment by Echoblammo** [comment]
> Handled 509.

My Venezuelan ground unit request is the second oldest request on the Github. Seeing all of these Venezuela entries makes me sad.

![8c73bf3160af9c9b39ade39efc68eec0-2439597367](https://github.com/user-attachments/assets/7b7bf1f9-5096-4fb3-8e3f-852c67e750b8)

**Comment by PygmalionOfCyprus** [comment]
That's partially because we've not really been doing random ground unit tickets (these are all facilities). The GU annex is bare enough right now that it's not really worth doing "requests." We wanna go through and add stuff with purpose.

**Comment by Echoblammo** [comment]
> That's partially because we've not really been doing random ground unit tickets (these are all facilities). The GU annex is bare enough right now that it's not really worth doing "requests." We wanna go through and add stuff with purpose.

So is it primarily an issue of unit type? Back when I made those requests, it seemed like the transition from facilities to GUs was in full swing, but now it appears that demand for them has died down or been fulfilled. 

Could you just mark them as facilities?
