### ISSUE TITLE
Add T-21 Amazonas [Terrebonne Parish Class] 1972-1993

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5241]
### DB Selector

DB3K

### DBID to Copy

Ship 2705

### Hypothetical

No

### Name

T-21 Amazonas [Terrebonne Parish Class] 

### Country

Venezuela

### Service

Navy

### In Commission

1973-1993

### Number in Service

1x

### Other Changes

Add Medium Helicopter Pad and 1 Parking spot

### Sources

https://www.shipspotting.com/photos/gallery?shipName=ABV%20Amazonas%20T21
https://es-la.facebook.com/favclub/photos/el-arv-amazonas-t-21-luego-t-51-ex-lst-1161-uss-vernon-county-transferido-a-vene/10152747874436122/
https://www.seaforces.org/marint/Venezuelan-Navy/ships.htm
https://en.wikipedia.org/wiki/USS_Vernon_County

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
