### ISSUE TITLE
Sayyad-4 engagement radar issue

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#5244]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3229

### Description of Problem

- Its engagement radar is of the older generation. Shouldnt this Iranian Sayyad-4`s FCR supposed to be of the same generation as its air search radar since its also an AESA radar? 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/f732f485-b45c-41c0-8d38-4b59c85dd11d)

### Recommended Fix

- Update the engagement radar`s generation to Early 2010

**Comment by capcop98** [comment]
Also as per @sr71xx:

"Also noticed the Sayyad-4 is missing INS/Midcourse datalink, functions more as a TVM missile instead.
Sayyad-4 should have midcourse datalink/INS uplink just like other ARH missiles such as PAC-3, 40N6, HQ-9B, etc"

**Comment by Jkryos** [comment]
Fixed DB3K 509.
