### ISSUE TITLE
Azerbaijan - Spike SSM Teams Mobile Vehicle & Mobile Personnel

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#525]
### DB Selector

DB3K

### DBID to Copy

facility/2939/DB3K (mobile personnel) & facility/1588/DB3K (mobile vehicles)

### Hypothetical

No

### Name

SSM Plt (Spike)

### Country

Azerbaijan

### Service

Army

### In Commission

IOC Uncertain

### Sensors

No Change

### Mounts

Mobile Personnel Teams with Spike ER and/or Spike LR

Mobile Vehicle Units with Spike ER and/or Spike LR

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces#Anti-tank_missiles

**Comment by PygmalionOfCyprus** [comment]
Added a SPIKE ER platoon to Azerbaijan.

**Comment by tbrandon517** [comment]
> Added a SPIKE ER platoon to Azerbaijan.

Confirming if just SPIKE ER and not SPIKE LR as well.

**Comment by PygmalionOfCyprus** [comment]
Blargh. Meant to write both!
