### ISSUE TITLE
PAK Babur class not Hypothetical

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#5254]
### DB Selector

DB3K

### Affected DBID(s)

3570

### Summary of Changes

#3570 - F 280 Babur [Ada Class] (Pakistan - 2024) -- HYPOTHETICAL UNIT change to non Hypo.
Aselsan ARES-2NC prob for the generic SIGINT
Not sure if the P-282 is teh same as Harbah SSM or later made?
2 × 3-cell [Mark 32 324 mm].
Aselsan HIZIR [torpedo-countermeasure system]
Ref: closed entry 3838
![01](https://github.com/user-attachments/assets/736a8ca9-02de-4b9d-a919-ff45cae0e6f0)
![2](https://github.com/user-attachments/assets/b00129a7-d057-4deb-896a-550bfb70ce2b)
![3](https://github.com/user-attachments/assets/2daef474-bd08-495c-b51a-7e7be824283b)
![4](https://github.com/user-attachments/assets/e823c4ef-cdc8-4541-9798-d403db6efe90)

### Sources

https://www.navalnews.com/naval-news/2023/09/turkiye-delivers-corvette-to-pakistan-launches-2-opvs-for-turkish-navy/#prettyPhoto
https://en.wikipedia.org/wiki/Babur-class_corvette
https://quwa.org/quwa-premium-excerpt/pakistans-surface-to-surface-missiles-strategic-intent-with-conventional-potential-2
https://pakstrategic.com/project-p-282-pakistan-navys-hypersonic-weapons-program

**Comment by Jkryos** [comment]
Updated DB3K 509.
