### ISSUE TITLE
WZ8 drone cannot be launched

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#5257]
### DB Selector

DB3K

### Affected DBID(s)

#4274

### Description of Problem

WZ8 drone seems to lack any WRA meaning it can't be used against anything, it also lacks BOL meaning it can't even be launched at all. 

![Screenshot 2024-10-20 023307](https://github.com/user-attachments/assets/6f3b3f19-81bb-4259-9554-ca6b14f3191a)

### Recommended Fix

Give WZ8 the BOL tag

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Also added BOL to all other platform-as-payload entries.

**Comment by Siegemiester** [comment]
> Handled 509. Also added BOL to all other platform-as-payload entries.

On a side note, Attempting to click on the 'payload' entry for the WZ8 from the database incorrectly redirects to the FA-50PH for some reason
![Screenshot 2024-10-26 134231](https://github.com/user-attachments/assets/27b544bf-ab69-49b5-bd51-a1cdf4129d5d)
![Screenshot 2024-10-26 134305](https://github.com/user-attachments/assets/a23bddb8-f9cf-4902-98c4-504b56b70678)
