### ISSUE TITLE
Armored Plt (T-90A MBT)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#526]
### DB Selector

DB3K

### DBID to Copy

facility/1919/DB3K & facility/1918/DB3K

### Hypothetical

No

### Name

Armored Plt (T-90A MBT)

### Country

Azerbaijan

### Service

Army

### In Commission

2013

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces#Main_battle_tanks

**Comment by PygmalionOfCyprus** [comment]
Added 494.
