### ISSUE TITLE
Mech Inf Plt (BMP-3 IFV x 3)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#527]
### DB Selector

DB3K

### DBID to Copy

facility/2044/DB3K

### Hypothetical

No

### Name

Mech Inf Plt (BMP-3 IFV x 3)

### Country

Azerbaijan

### Service

Army

### In Commission

1992-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html
https://en.wikipedia.org/wiki/List_of_equipment_of_the_Azerbaijani_Land_Forces#Infantry_fighting_vehicles

**Comment by PygmalionOfCyprus** [comment]
Added 494.
