### ISSUE TITLE
Change JASDF F-35A with loadouts of JSM commission year to 2024

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#5274]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft DBID 4223

### Summary of Changes

Change commission year to 2024

### Sources

https://www.mod.go.jp/j/policy/agenda/meeting/drastic-reinforcement/pdf/[bukai_siryo01_02.pdf] in page 33
![スクリーンショット 2024-10-22 233822](https://github.com/user-attachments/assets/ceec47b6-4c83-40d4-814b-40e56afe5a2f)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
