### ISSUE TITLE
Change: Aircraft #7096 "ZEPHYR 8/S" High altitude pseudo satellites critical wrong MAX ALTITUDE

### ISSUE THREAD

**Issue by ninjaDEU** [PygmalionOfCyprus/cmo-db-requests#5275]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 7096 Zephyr 8/S United Kingdom 2024

### Summary of Changes

Dear Team,
The current ingame max altitude is 12.000 feet which is far from the reality as it is used as an HIGH ALTITUDE pseudo satellite.
Airbus says it is casually operating at >60.000ft and it has reached 78.100ft.
Thank you for your work! All the best.

### Sources

1) https://www.airbus.com/en/newsroom/press-releases/2020-12-the-airbus-zephyr-solar-high-altitude-platform-station-haps
2) https://www.airbus.com/en/products-services/defence/uas/uas-solutions/zephyr
3) https://www.aerosociety.com/news/zephyr-down-but-definitely-not-out/

**Comment by PygmalionOfCyprus** [comment]
DB entry had the correct alt in ft but the weird nuclear propulsion didn't auto-convert to metric. Whoops. Fixed 509.
