### ISSUE TITLE
LRASM lost its ability to attack land targets

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#5276]
### DB Selector

DB3K

### Affected DBID(s)

Weapons 2378, 4466

### Summary of Changes

The LRASM should be able to attack ground targets as well as surface ships. I genuinely can't imagine how it would lose the capability to do so based on its upgrades, and this really hampers the Navy's long-range attack capabilities.

### Sources

https://www.defensemedianetwork.com/stories/lrasm-long-range-maritime-strike-for-air-sea-battle/
https://jalopnik.com/the-navys-smart-new-stealth-anti-ship-missile-can-plan-1666079462

**Comment by RickDNiu** [comment]
#5088
https://www.twz.com/air/land-attack-capability-axed-on-agm-158c-lrasm-anti-ship-missile
