### ISSUE TITLE
[HIPRI] China, Type 780 Radar Facility w/ wrong sensor, currently YLC-2V as sensor

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5277]
### DB Selector

DB3K

### Affected DBID(s)

Facility 4388

### Summary of Changes

- [ ] Change to **Sensor 7403 (Type 780 Radar)**

### Sources

DB itself

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
