### ISSUE TITLE
Add Egyptian Arty Bty (155mm/53 K-9A1 EGY Self-Propelled Howitzer x 6) 2024

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5280]
### DB Selector

DB3K

### DBID to Copy

Facility 2196

### Hypothetical

No

### Name

Arty Bty (155mm/53 K-9A1 Thunder Self-Propelled Howitzer x 6)

### Country

Egypt

### Service

Army

### In Commission

2024

### Sources

https://x.com/clashreport/status/1843631674829271397
https://x.com/mahmouedgamal44/status/1667771654078971904
https://x.com/Esll7970Gladii/status/1843604492497104929/photo/1
https://www.janes.com/osint-insights/defence-news/industry/egypt-outlines-k9-howitzer-production-plan

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
