### ISSUE TITLE
Add PLA SA-21AB SAM Facility (8 launchers, mixture of 48N6DM and 40N6E) China

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#5294]
### DB Selector

DB3K

### DBID to Copy

facility 1937

### Hypothetical

No

### Name

SA-21AB?

### Country

China

### Service

Air Force

### Sensors

4x TEL 5P85T2 (48N6DM)
4x TEL 5P16 (40N6E)

### Other Changes

same as original battery, just with  a half and half mix of 48n6dm/40n6e (8 launchers total)
![image](https://github.com/user-attachments/assets/f2370865-5a56-45da-8ebe-38d716bef868)

### Sources

https://x.com/benreuter_IMINT/status/1851589441107660868/photo/1

**Comment by sr71xx** [comment]
you could also just modify mounts in game, up to admins if they want to keep this ticket open or not

**Comment by PygmalionOfCyprus** [comment]
Yeah, this mix/match capability is already reflected in the mount entries, it can be adjusted in-game to reflect whatever mixture the player wants.
