### ISSUE TITLE
Update US 2021/2022 LHA Magazines to current weapons records

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#53]
### DB Selector

DB3K

### Affected DBID(s)

America, Bougainville,Essex, Wasp, Makin Island 

### Summary of Changes

AGM-114M Hellfire II
AGM-179 JAGM
AOEW AMP AN/ALQ-248
GBU-53/B SDB II
AIM-120C-5 Amraam (Harrier Loadout)

### Sources

Add aircraft to ship and check in air ops menu.

**Comment by bostonmyk** [comment]
Add GBU-49/B Paveway II's as well. F-35B's use these.

**Comment by KushanGaming** [comment]
Done for DB495.
