### ISSUE TITLE
S201 patrol craft (2015-2019)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#530]
### DB Selector

DB3K

### DBID to Copy

ship/3145/DB3K

### Hypothetical

No

### Name

S201 patrol craft (2015-2019)

### Country

Azerbaijan

### Service

Coast Guard

### In Commission

2015

### Sensors

EL/M-2228X radar
Toplite e/o system

### Mounts

1 x 8 Spike SSM (20 Spike-NLOS), 
1 x 1 - 23/82 Typhoon, 
4 x 1 - 12.7/90, 2 x 1 - 7.6/90, 
Wizard decoy RL

### Other Changes

helicopter deck

### Sources

https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://www.navypedia.org/ships/azerbaijan/aze_cg_s201.htm
https://en.wikipedia.org/wiki/Sa%27ar_62-class_offshore_patrol_vessel
https://www.thedrive.com/the-war-zone/20116/azerbaijans-border-guard-has-this-awesomely-bad-music-video-with-tanks-and-suicide-drones

**Comment by PygmalionOfCyprus** [comment]
Just dropping in to tell you what I told @cdnice55 re: his big Canadian update dump:

Lemme know in a comment when you've finished making all the requests for Armenia/Azerbaijan that you want, and we'll come through and sweep the whole milestone.

**Comment by tbrandon517** [comment]
Thanks, I've got through my main list. Every other item is something not in the db already or not related to some other pending request. So I will do more research on that stuff for sources. Probably won't get to start looking at those for at least a couple weeks. So, Sweep away!

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also overhauled the Cyprus Saar 62 this was "copied" from since it was totally wrong.
