### ISSUE TITLE
[HIPRI] China, 095 Vertical Payload Module systems, there is a little misunderstanding

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5318]
### DB Selector

DB3K

### Affected DBID(s)

submarine 676

### Summary of Changes

- [ ] Should be **12x 3-cell-in-1 VPM**. Total **36x YJ-21** (50% more firepower than Type 093B).

![image](https://github.com/user-attachments/assets/53783939-132b-4c18-8988-ece8a239297f)

Okay, maybe I shouldn't have divided the points that way, my bad. What I was actually trying to say was, "The 3-in-1-cell VPM" is arranged side by side in a "2x6" pattern. Because 095 is known to have a diameter of 12m+, and based on other evidence I gave earlier, it has a high probability of such an arrangement of VPM.

### Sources

#4762 #4750

**Comment by Jkryos** [comment]
Okay I understand now, should be correct 510.
