### ISSUE TITLE
China, J-35A Fighter, PLAAF version of J-35

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5319]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4454

### Hypothetical

No

### Name

J-35A Gyrfalcon, PLAAF

### Country

China

### Service

PLAAF

### In Commission

2025

### Other Changes

Remove [Carrier Capable]

### Sources

https://www.sinodefenceforum.com/t/j-35a-fighter-plaaf-fc-31-thread.9151/
![image](https://github.com/user-attachments/assets/fec67778-4d86-4fef-be52-663f614b0b9a)
And A LOT, A LOT, A LOT of X posts

**Comment by Jkryos** [comment]
Added DB3K 510.
