### ISSUE TITLE
Add Z-8L Transport helicopter 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#532]
### DB Selector

DB3K

### DBID to Copy

4743

### Hypothetical

No

### Name

Z-8L

### Country

China

### Service

PLAGF

### In Commission

2021

### Sensors

Both Z-8G and Z-8L have simple nav weather reader up front
RWR on each side on L

### Mounts

Generic Chaff and Flare launchers

### Other Changes

China built body Z-8G called Z-8L variant to accommodate bulkier cargo.  Fuel tanks now visible on outside whereas the standard Z-8 has smaller nubs.  1st link original request. Second Link picture comparison between G and L. Third Link notes 15 ton vs. 13ton. Capacity similar to Mi-17. 4th Link. Jane's notes 1.8-2.4 meter width difference from G. 5th link notes 10 were in service in 2021 when I made this post. More recent photos at the end.

### Sources

http://www.matrixgames.com/forums/fb.asp?m=4889486
[https://twitter.com/louischeung_hk/stat ... 4887618561](https://twitter.com/louischeung_hk/status/1407479474887618561)
[https://www.airrecognition.com/index.ph ... opter.html](https://www.airrecognition.com/index.php/news/defense-aviation-news/2020/august/6527-china-unveils-z-8l-first-indigenous-15-ton-class-transport-helicopter.html)
[https://www.janes.com/defence-news/news ... ing-trials](https://www.janes.com/defence-news/news-detail/update-images-show-wide-body-variant-of-z-8g-helicopter-undergoing-load-carrying-trials)
[https://chinese-military-aviation.blogs ... s-iii.html](https://chinese-military-aviation.blogspot.com/p/helicopters-iii.html)
https://twitter.com/louischeung_hk/status/1412583219644354563
https://twitter.com/AlexLuck9/status/1458521862942519296
https://twitter.com/AlexLuck9/status/1458521862942519296
http://chinese-military-aviation.blogspot.com/p/helicopters-iii.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
