### ISSUE TITLE
China, J-35 carrier-borne Fighter, should be no longer called FC-31

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5320]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4454

### Summary of Changes

- [ ] Rename it as J-35 and remove all the supplement

### Sources

J-35A is the official code name of its Air Force version.

**Comment by Jkryos** [comment]
So looking at the navalized version on debut in 2022 and the one at Zhuhai '24 there are some minor changes still. I think it might be best to keep the carrier capable one as FC-31 and make a new entry for J-35A to distinguish between the flying protype and the full in service version.

**Comment by Luigi-II** [comment]
@Jkryos The AVIC officially call it J-35:
https://www.sinodefenceforum.com/t/j-35-carrier-fighter-plan-thread.8173/page-315
![image](https://github.com/user-attachments/assets/27f4cd9f-cef3-4c07-a8bd-b3b8a102e5e9)
![image](https://github.com/user-attachments/assets/16dfe626-8527-4e5b-ac8d-7fc82eb32d46)

**Comment by Jkryos** [comment]
Thats good enough for me. Updated DB3K 510.
