### ISSUE TITLE
China, PLAAF, HQ-19 ABM Interceptor, Sino THAAD-ER

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5321]
### DB Selector

DB3K

### Baseline

weapon 3447

### Hypothetical

No

### Name

HQ-19

### Length (m)

7

### Width/Span (m)

0.7

### Diameter (m)

0.7

### Weight (kg)

1700

### Range (nm)

2-300

### Target Speed (kts)

0-12000kt

### Warhead

Kinetic (1 DP)

### Targets

Missile

### Sensors

1x IIR Seeker

### Weapon Codes

Anti-Air All-Aspect, Lock-On After Launch (LOAL), Attitude Control - Combined, Level Cruise Flight, ABM Capable

### Comments

- [ ] Need a **facility** with

> 1x SLC-14 X-Band ABM FC/Early waring Radar (May Just copy **AN/TPY-2 [sensor 515]**, **2020s tech** and Give it **360 degree arc**)

> 8x TELs (same as HQ-9B site), each TEL with 6x Missile

> C2 vehicles

- [ ] **PoH** increase to **95%**. The display board highlighted its capability against strong-penetration-capability missile (most likely the DF-17). Not to mention, China's vast BM & HGV arsenal provides a testing environment unmatched worldwide.

### Sources

The OSINT, which is mostly from China (including reliable sources), refers to it as "Sino THAAD-ER". From the looks of it, its container is indeed larger than THAAD that it can only carry 6 rounds per TEL. Give it a range between 40N6 and SM-6 BLK IB, half the range of SC-19.
https://twitter.com/Nickatgreat1220/status/1853666771146018919
https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/page-106
https://www.defenseone.com/ideas/2019/03/technological-path-out-missile-defense-security-dilemma/155641/
![image](https://github.com/user-attachments/assets/61ac99e8-473b-45a1-9cc1-4a9c2dba077f)
![image](https://github.com/user-attachments/assets/c9c19593-309d-4034-916e-1988d82d3497)
![image](https://github.com/user-attachments/assets/ae6520ef-a928-40ce-8070-18abd1a86cef)
![image](https://github.com/user-attachments/assets/6a78d9f2-7f5d-42d2-9ccb-be6b15190bae)

**Comment by Luigi-II** [comment]
#4767

**Comment by RickDNiu** [comment]
#5052

**Comment by Luigi-II** [comment]
Not reliable, but a bit valuable estimate:
https://twitter.com/Flankerchan/status/1854007158708552182
![image](https://github.com/user-attachments/assets/9cb4b5f4-1313-43e9-82c8-73fe3d4e0da5)
(Its diameter may 2-time larger than THAAD)

**Comment by Luigi-II** [comment]
SLC-14 is rotatable:
![image](https://github.com/user-attachments/assets/2464af67-12c0-4eb5-a06e-51278664b218)

**Comment by Luigi-II** [comment]
CCTV officially announced that HQ-19 has the ability to effectively engage HGV, seems to have the capability of GPI? Does that mean it has a greater range than we thought?
https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/page-110#post-1130665
![image](https://github.com/user-attachments/assets/2e507a46-a675-4b79-8613-d9ddc4585a18)

**Comment by Jkryos** [comment]
Added DB3K 510.
