### ISSUE TITLE
[HIPRI] China, Type XXX Stealth Corvette, RCS way too large

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5322]
### DB Selector

DB3K

### Affected DBID(s)

Ship 4929

### Summary of Changes

- [x] RCS should be reasonably set at **Visby [Ship 3345]** level. Not current DDG 51 Burke level.

I remember I said “It’s RCS and IR signature should be at least the same level with Visby [Ship 3345]”

### Sources

Visby:
![image](https://github.com/user-attachments/assets/9fd727b5-c3bd-42d3-80dc-182c8b80dece)
![image](https://github.com/user-attachments/assets/fd26a056-8b2c-40be-8217-4e36668193df)
Type XXX (it even needs an additional reflector to Increase radar signature):
![image](https://github.com/user-attachments/assets/2c9dab0d-1ae5-4524-aed4-bddb5fae503d)
![image](https://github.com/user-attachments/assets/b3fe0d3e-57b4-4d65-907d-736b04d7f4fe)
Burke:
![image](https://github.com/user-attachments/assets/67898d0c-cc69-4174-a49f-16e05843005a)
![image](https://github.com/user-attachments/assets/f56e861e-57ae-4f06-a6f2-318476a37e31)

**Comment by Jkryos** [comment]
Updated DB3K 510
