### ISSUE TITLE
Senegal 58m OPV Walo, displacement correction. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#5324]
### DB Selector

DB3K

### Affected DBID(s)

Ship Senegal 58m OPV Walo. 

### Summary of Changes

Displacement is wrong at only 32 tonnes. Should be circa 650t.

### Sources

https://armyrecognition.com/news/navy-news/2023/senegalese-navy-receives-2nd-opv-58-s-class-niani-from-piriou
https://www.piriou.com/en/piriou-delivers-the-cayor-and-finalizes-the-opv-58-s-program-for-the-senegalese-navy/

**Comment by Jkryos** [comment]
Updated DB3K 510.
