### ISSUE TITLE
China, PLAAF, HQ-19 facility

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#5325]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Bn (HQ-19)

### Facility Type

SAM

### Country

China

### Service

PLAAF

### In Commission

2020

### Number in Service

2+

### Dispersion Radius (m)

150

### Sensors

1x SLC-14 X-Band ABM FC/Early waring Radar
1x Type 780 FCRadar

### Mounts

1x Vehicle (China Type 780 radar)
1x Vehicle (SLC-14)
8x TELs (same as HQ-9B site), each TEL with 6x Missile
C2 vehicles

### Magazines

48x HQ-19

### Comments

The information comes from the early exposure information of Zhuhai Air Show, and there is a new ABM system.

### Sources

![image](https://github.com/user-attachments/assets/5b724db3-cf21-4e61-b96e-202bb9a308a7)
![image](https://github.com/user-attachments/assets/65667e4e-6b42-43f1-9f20-4328696ac8d1)

**Comment by yU2187sie** [comment]
#5321 #4765 #4767

**Comment by Luigi-II** [comment]
I've included this request in my ticket, but a separate facility ticket isn't a bad thing.

**Comment by Jkryos** [comment]
Added DB3K 510.

**Comment by yU2187sie** [comment]
Completed the tracking of  #5321 , deleted the 780 radar, after verification, it should not be in the HQ-19 facility. @Jkryos
