### ISSUE TITLE
Project 58250 (Volodymyr Velykyi class) Corvette

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#533]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

Volodymyr Velykyi

### Class

Project 58250

### Country

Ukraine

### Service

Navy

### Length (m)

112

### Beam (m)

13.5

### Draft (m)

3.5

### Standard Displacement (t)

2650

### Complement

110

### Primary Propulsion Type

Diesel

### Propulsion

CODOG, Zorya-Mash-proekt Gas Turbines, C230-16 diesels and C32 ACERT diesel generators (Catapillar)

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

4000 @14

### Sensors

- Thales Kingklip Hull-Mounted Sonar
- Thales Captas-2 Variable-Depth Sonar 
- Phoenix Active Fixed-Face Phased-Array 3D Radar
- ORLS Protazan-K Optical Radar to manage the 76mm gun
- ORLS Spys-K Optical Radar to manage the 35mm CWIS, Selena Navigation System
- BZOI Pohljad Data Link
- Saiga Aircraft Management System
- Gudzik Signals Intelligence System
- Zirnytsja Multi-Purpose Hydroacoustic System
- 1x  KNPA-58250 Remotely Operated Underwater Vehicle

### Mounts

- 1x OTO Melara 76mm Strales Gun
- 8x Exocet MM40 Block 3 Anti-Ship Missiles in two quadruple launchers or Neptune
- 16x VLS Cells for Aster 15 Anti-Aircraft/Anti-Ballistic Missiles or Dnipro
- 6x MU90 Impact Torpedoes in two triple launchers
- 2x Rheinmetall 35mm GDM-008 CIWS
- 2x LSD Hephaestus 12.7mm Miniguns
- 2x Rheinmetall MASS Active Defence System

### Aircraft & Docking Facilities

- 1x pad for Medium Helicopter (KA-27)
- 1x davit for 11m RHIB

### Comms/Datalinks

- Secure VHF
- Secure UHF
- Secure HF
- BZOI Pohljad Data Link
- ASTER Datalink
- HF Datalink
- LINK system? 

### Comments

- The Phoenix Radar is the same radar that is [mounted on the Chinese Type 052C destroyers](http://cimsec.org/gutting-of-ukraine/15016), and is a radar that was [originally developed by Ukrainian firms for that project](https://en.wikipedia.org/wiki/Type_052C_destroyer).
- 

### Sources

https://en.wikipedia.org/wiki/Volodymyr_Velykyi-class_corvette
[defencedb.com/profile_page.php?item_id=90](https://defencedb.com/profile_page.php?item_id=90)
https://www.reddit.com/r/GlobalPowers/comments/791cnz/rd_project_58250_volodymyr_velykyclass_corvette/
https://www.globalsecurity.org/military/world/ukraine/project-58250.htm

![Corvette “58250 PROJECT”](https://user-images.githubusercontent.com/99632305/156694340-68d21510-56ce-40a1-87fb-17a2d0372f6c.png)
![Corvette “58250 PROJECT” 1](https://user-images.githubusercontent.com/99632305/156694352-13a4fa09-af1f-4289-95ef-8d08467223e7.jpg)
![volodymyr-velykyi-class-corvette-project-58250-defence-database-defencedb com](https://user-images.githubusercontent.com/99632305/156701108-9614f649-1550-4a15-ad38-76d8c44a8c73.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 502.
