### ISSUE TITLE
[HIPRI] China, CJ-100 AShM, lacking necessary ability to strike a moving ship

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5330]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4543 & Sensor 7427

### Summary of Changes

- [x] Increase **[Sensor 7427]** range to regular **80nm** as other **ASM LR seekers**. Long-range, high-speed, cruise AShMs like Kh-32, SS-N-33 and HAWC AShM all use 80nm seeker to increase possibilty of catching moving ship after long range flying. Current AAM class 5nm is just way too insufficient.

- [x] Give the missile (weapon 4543) **"Home on Jam (HOJ)"** property. Only having passive radar seeker is not enough. All AShMs in this game (and in real world) have HOJ capability to lock moving, electronic-signal-emitting target. The basiline version of CJ-100 don't have this since its a land-attack missile, but this is an AShM.

### Sources

DB itself
![image](https://github.com/user-attachments/assets/d2ca1cc3-e3f4-4240-9506-dc65cf2b65e6)

**Comment by Jkryos** [comment]
Added DB3K 510.
