### ISSUE TITLE
Advanced Bulgarian Blk 70 IOC F-16Cs to 2025

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5331]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4954

### Summary of Changes

Change IOC from 2022 to 2025-27
Quantity is 16 total. 10Cs and 6Ds

### Sources

https://www.scramble.nl/military-news/first-flight-bulgarian-air-force-f-16c-block-70
https://theaviationist.com/2024/10/25/first-bulgarian-f-16-block-70-performs-maiden-flight/

**Comment by Jkryos** [comment]
Fixed DB3K 510.
