### ISSUE TITLE
Add out of service date of 2024 to all Dutch F-16 MLUs

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#5332]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 3167, 5814

### Summary of Changes

Add out of service date of 2024

### Sources

https://www.janes.com/osint-insights/defence-news/defence/netherlands-declares-foc-for-f-35-retires-f-16
https://www.scramble.nl/military-news/farewell-klu-f-16
https://theaviationist.com/2024/09/28/final-flight-the-dutch-f-16s/

**Comment by Jkryos** [comment]
Updated DB3K 510.
