### ISSUE TITLE
[HIPRI] China, HQ-9C SAM, the actual code name of so-called "HQ-9BE"

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5333]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4488

### Summary of Changes

As the title.

### Sources

https://www.sinodefenceforum.com/t/pla-anti-air-missile-sam-systems.7266/page-110#post-1130701
![image](https://github.com/user-attachments/assets/3673139f-e39e-4bff-b8cd-ac11387332e6)

**Comment by Luigi-II** [comment]
Okay, last ticket before I go to bed. The PLA's equipment OSINT is so much and attractive that I have been putting off my ticket for Marina Militare's FREMM-EVO for a long long time (and it will continue to be postponed at least til the end of Zhuhai 2024).

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
