### ISSUE TITLE
Update for Sayyad-3F

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#5334]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4552

### Summary of Changes

- Replace SARH seeker with ARH one
- Change the guidance type from "Semi-Active Radar Homing (SARH)" to: "All-Aspect and Datalink (DL/INS) mid-course plus Active Radar Homing (ARH) terminal guidance"
- Remove weapon`s property "illuminate at launch"
- Add weapon`s property "ABM-capable"
- Change the warhead for ABM-optimized one

### Sources

- https://x.com/Pataramesh/status/1765778261001269519
- https://defencepk.com/forums/threads/integrated-air-defence-iads-assets-of-iran-current-and-possibilities.14225/

**Comment by Jkryos** [comment]
Fixed DB3K 510.
