### ISSUE TITLE
 SAM Bty (Arman) - Najm-804 AESA cannot fires Sayyad-3F

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#5335]
### DB Selector

DB3K

### Affected DBID(s)

Facility 4550

### Description of Problem

Seems this Iranian SAM cannot guide the missile for some reason. 

### Recommended Fix

Might be change Sayyad-3F spec according to request #5334

**Comment by Jkryos** [comment]
Should be fixed with #5334
