### ISSUE TITLE
Chinese Sovremenny missing Band Stand radar

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#5341]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1803, 4614

### Summary of Changes

May have already been caught, but as of DB508 the Taizhou in game doesn't have Sensor Group 213, the Band Stand radar system. It has one in the DB image, and it has the associated data link.

### Sources

DB
![PLANS_Taizhou_(DDG-138)_20150817](https://github.com/user-attachments/assets/71ff9777-ea45-4902-8ff6-4a9d1fd457bb)
Another image

**Comment by Jkryos** [comment]
Added DB3K 510.
