### ISSUE TITLE
#16 AS-24 KODIAK (Kh-101) cruise missile will not target runways

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#535]
### DB Selector

DB3K

### Affected DBID(s)

#16

### Description of Problem

During the (attached) mission Kyiv, Ukraine, 2022 the Tu-95 Bears keep circling the base and do not attack the runways, taxiways or access points, although Runways are mentioned in the DB as valid targets.

A dressed down scenario is attached to see the inactivity.
[AS-23 versus runways.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8190493/AS-23.versus.runways.zip)
.

**Comment by claudejdev** [comment]
Hey there,
in your scenario, the mission's WRA is set not to use the Kh-101 against runways type of target.

**Comment by PygmalionOfCyprus** [comment]
Thanks @claudejdev! Issue closed. (If that doesn't fix it drop a line and I'll reopen.)
