### ISSUE TITLE
China, J-20S, add the J-20S OECM Suite

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5350]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5454

### Summary of Changes

- [ ] Add J-20S OECM Suite

### Sources

https://twitter.com/globaltimesnews/status/1855447272970231933
https://www.sinodefenceforum.com/t/j-20-5th-gen-fighter-thread-viii.9082/page-219
https://www.ithome.com/0/809/307.htm

> J-20S is a new generation of medium- and long-range, heavy, two-seat, multi-purpose stealth fighter independently developed by the Aviation Industry Corporation of China . It has excellent medium- and long-range air combat capabilities and precision strike capabilities against ground and sea; has **outstanding** situational awareness, **electronic jamming** and tactical command and control capabilities; and has manned/unmanned aerial vehicle coordinated combat capabilities.

**Comment by Luigi-II** [comment]
#5351

**Comment by Jkryos** [comment]
Added DB3K 510.
