### ISSUE TITLE
China, J-20S OECM Suite

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5351]
### DB Selector

DB3K

### Baseline

sensor 6491

### Hypothetical

No

### Name

J-20S OECM Suite

### Sensor Generation

Early 2020s

### Range (nm)

-

### Sensor Capabilities

Same as J-16D OECM

### Search/Track Frequencies

Same as J-16D OECM

### Sources

https://twitter.com/globaltimesnews/status/1855447272970231933
https://www.sinodefenceforum.com/t/j-20-5th-gen-fighter-thread-viii.9082/page-219
https://www.ithome.com/0/809/307.htm

> J-20S is a new generation of medium- and long-range, heavy, two-seat, multi-purpose stealth fighter independently developed by the Aviation Industry Corporation of China . It has excellent medium- and long-range air combat capabilities and precision strike capabilities against ground and sea; has **outstanding** situational awareness, **electronic jamming** and tactical command and control capabilities; and has manned/unmanned aerial vehicle coordinated combat capabilities.

**Comment by Jkryos** [comment]
Added DB3K 510.
