### ISSUE TITLE
PLA CM-501G Launch Facility

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#5359]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM Sec (CM-501G)

### Facility Type

SSM

### Country

China

### Service

PLA Airborne Troops

### In Commission

2023-

### Sensors

1×Eye Ball
1×generic IR camera
1×generic laser rangefinder
1×generic TV camera

### Mounts

1×CM-501G Launch Vehicle(8×CM-501G)

### Magazines

16×CM-501G
Reload Rate:900

### Sources

![image](https://github.com/user-attachments/assets/10e4bd16-1284-4b03-9c92-f7771ed6a21e)
https://www.sinodefenceforum.com/t/chinese-atgm-discussion.6468/page-63
![020fa49bb994053c58cc7a70976bda9d](https://github.com/user-attachments/assets/25dc0485-11ed-4a49-87b1-05505e3b4bea)
Zhuhai Air Show,2024
It seems that CM-501G cruise missle has already been equipped by PLA Airborne troopers.
So a facility is needed.

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
