### ISSUE TITLE
HJ-8E (ATGM Team - China) in the "add cargo list" is not Paradrop capable

### ISSUE THREAD

**Issue by nukkxx** [PygmalionOfCyprus/cmo-db-requests#536]
### DB Selector

DB3K

### Affected DBID(s)

2429

### Summary of Changes

HJ-8E (ATGM Team - China) in the cargo list is not Paradrop capable. I think it should be. Similar MILAN 2T ATGM team (among others) are droppable.
Thank you.
![dropable manpads](https://user-images.githubusercontent.com/100931230/156903600-02926866-3b09-4765-9870-8049d06ae685.jpg)
.

### Sources

Similar units are dropable. Looks like this one has been forgotten.
![dropable manpads2](https://user-images.githubusercontent.com/100931230/156903686-e156deba-9651-41e3-bdf7-9123ca2509d7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
