### ISSUE TITLE
Increase Max Target Channels to 6 for FCR (Pantsir-SM)

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#5367]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 6649 (name change to 1RS3)

### Summary of Changes

_-increase max targeting channels to 6_ 
_-add PESA property_

Manufacturer states the ability of Pantsir-SM to engage 18 targets within 60 seconds, with 3 simultaneous targets engaged per channel. This would imply 6 targeting channels

_Also, surveillance radar shown as an AESA using Gallium Arsenide transistors, reported by manufacturer. AESA surveillance radar has range of 27km for a 0.07m2 target (max range 80km)
PESA FCR has a range of 20km for a 0.07m2 target (max range 40km)_
**FCR Designation for Pantsir-SM Domestic is 1rs3**
![image](https://github.com/user-attachments/assets/8901dbe0-8d76-4035-b306-6a38947939e6)

The older pantsir-s1 and s2 with the 1rs-2 shlem radars can engage only 4 targets simultaneously, but the newer SM FCR is hypothesized to engage up to 6-9 simultaneously.  Especially when you factor in the loadout with 48 mini missiles TBK-1055. Multiple OSINT/military blogger sources on twitter are speculating with the mini missiles, targeting channels could be anywhere from 6-18. But most agree with 6 at least, and maybe 8 so double the original radar?

picture shows FCR upgrade, same radar used on export Pantsir-S1/M and the Naval Pantsir-M
![1593185440_-sm-1](https://github.com/user-attachments/assets/761a229d-9ff3-4460-95d1-fa29732f0b65)
![mclVeUUQGqA](https://github.com/user-attachments/assets/ae184b12-a576-4702-8631-5e82c4bbd28c)

### Sources

https://www.twz.com/land/pantsir-packed-with-drone-intercepting-mini-missiles-unveiled-by-russia
https://x.com/RALee85/status/1435702660003504132
https://en.topcor.ru/42951-nashe-vse-pancir-sm-i-derivacija-pvo-kak-glavnaja-nadezhda-protiv-dronov.html

**Comment by sr71xx** [comment]
the FCR radars that the Pantsir-S2E, Pantsir-S1M, Pantsir-SM and naval Pantsir-M all appear to be pretty much completely identical. However, export Pantsir-S1M has only 4 target channels as shown in brochure. Domestic version must have at least 6-8 channels as speculated by various military analysts and reporters on twitter/OSINT channels

Export variant of this radar keeps the original 4 targeting channels, but domestic has an increased number since it's able to engage 18 targets within 60 seconds

**Comment by sr71xx** [comment]
**update: the SM surveillance radar can track 100+ targets, and the FCR is able to engage 2-3 targets per channel. 
It is given by Rosbornoexport that the system can engage 18 targets within 60 seconds. If it can engage 3 targets per channel, then 6 targeting channels is most likely**

if 2 targets can be engaged per channel, that would be 9 channels which seems quite high for a SHORAD system. So 6 channels is the most likely and practical

**Comment by Jkryos** [comment]
Updated DB3K 510.
