### ISSUE TITLE
China, PLAGF, HQ-17A Missile

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5368]
### DB Selector

DB3K

### Baseline

weapon 3211

### Hypothetical

No

### Name

HQ-17A

### Length (m)

same as hq-17 for now

### Width/Span (m)

same as hq-17 for now

### Diameter (m)

same as hq-17 for now

### Weight (kg)

same as hq-17 for now

### Range (nm)

1-16.2

### Target Altitude / Depth (ft)

30-36000ft (AGL & ASL)

### Target Speed (kts)

0-2000kt

### Warhead

same as hq-17 for now

### Targets

Aircraft, Helicopter, Missile

### Sensors

same as hq-17 for now

### Weapon Codes

Illuminate at Launch, Anti-Air All-Aspect, Capable vs Seaskimmer

### Comments

Export version of HQ-17A has shown that it has an incresed capability to HQ-17/Tor 

- [ ] Need to increase its **speed** band to **1460kt-2000kt**. It has increased the range with meerly change on size, which indicate the speed increase.

### Sources

https://www.armyrecognition.com/news/army-news/2018/cpmiec-fm-2000-short-range-air-defense-system-at-air-show-china-2018

> It is designed to intercept various fixed wing aircraft, helicopters, air-to-ground missiles, and cruise missils in an operational range of 1.5 to 15 km and **altitudes from 10 to 10,000 m**. 

https://twitter.com/Nickatgreat1220/status/1856585930158887207
![image](https://github.com/user-attachments/assets/bd651a14-2559-45c5-be20-efeafeae3081)

**Comment by Luigi-II** [comment]
Worth noticing that they display a fire support UGV with total 72 anti-air/drone missile for HQ-17AE system. It is not clear whether the PLAGF will procure this.
https://twitter.com/TheDeadDistrict/status/1855524960082509833
![image](https://github.com/user-attachments/assets/47c178df-6554-4e5e-ac75-f7dc2bc31c20)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
