### ISSUE TITLE
China, HQ-17A Facility, replace the current HQ-17 mount and magazine with HQ-17A

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5369]
### DB Selector

DB3K

### Affected DBID(s)

Facility 4339

### Summary of Changes

- [ ] Replace the HQ-17 mount and magazine with HQ-17A

### Sources

#5368

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
