### ISSUE TITLE
China, HQ-17 Guidance Radar, increase the range to fit the increased missile range

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5370]
### DB Selector

DB3K

### Affected DBID(s)

sensor 7396

### Summary of Changes

- [ ] Increase the guidance radar range to 24nm. Same as the HQ-17 search radar. Current 12nm is way shorter than the missile's max ramge.

### Sources

#5368

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
