### ISSUE TITLE
Change cargo capacity of LST Jason-class of Hellenic navy

### ISSUE THREAD

**Issue by K1l0tangoDef3nce** [PygmalionOfCyprus/cmo-db-requests#538]
### DB Selector

DB3K

### Affected DBID(s)

#1304

### Summary of Changes

Greek LSTs can not carry the cargo that can carry ships of similar dimensions and weight, e.g. # 1615.
In the sources I attach it seems that the ships can carry up to 22 Leopard 1a5 tanks each weighing 42t. This gives us a load of 920 tons and a load area of ​​about 600 square meters. Morerover there is cargo capacity for 350 soldiers 

### Sources

https://en.wikipedia.org/wiki/Jason-class_tank_landing_ship
https://www.naval-technology.com/projects/jasonclasstanklandin/
https://www.navalanalyses.com/2017/01/jason-class-landing-ships-of-hellenic.html

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
