### ISSUE TITLE
Add Belarussian SAM Plt (SA-15d Gauntlet [ 9А-331 Tor-M2K]) 2016

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#539]
### DB Selector

DB3K

### DBID to Copy

2163

### Hypothetical

No

### Name

SAM Plt (SA-15d Gauntlet [ 9А-331 Tor-M2k])

### Country

Belarus

### Service

Air Force and Air Defense

### In Commission

2016

### Mounts

The TEL vehicle type is 9А331МК. 

### Other Changes

Export of wheeled M2-KM. This version doesn't appear to have an IR or EO-type sensor like the M2U. I can't find any pictures of a Russian M2-KM outside of an arms show in 2015. May not have bought and exported only. 

### Sources

https://twitter.com/halmiso1/status/1293493986301222912/photo/1
https://defence-blog.com/belarus-air-and-air-defense-force-enhances-their-combat-skills/
https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/tor-m2_tor-m2e_sa-15d_short_range_air_defense_missile_system_data_sheet_specifications_information.html
https://twitter.com/MotolkoHelp/status/1496776470680723457
https://twitter.com/RALee85/status/1078722957281763329

**Comment by Jkryos** [comment]
Added DB3K 494.
