### ISSUE TITLE
C 550 Cavour 76mm update

### ISSUE THREAD

**Issue by Venom63it** [PygmalionOfCyprus/cmo-db-requests#54]
### DB Selector

DB3K

### Affected DBID(s)

847

### Summary of Changes

The Cavour has currently 2  OTO 76/62 Davide gun on Database only the bow one 76/62 super rapido is listed

### Sources

Ship's data from the officila Italian Navy page
 https://www.marina.difesa.it/noi-siamo-la-marina/mezzi/forze-navali/Pagine/Cavour.aspx
https://www.seaforces.org/marint/Italian-Navy/Aircraft-Carrier/C-550-ITS-Cavour.htm

**Comment by bostonmyk** [comment]
Hi all

Couple items to add to this 

Cavour is now fitted with 2 Super Rapido 76mm (see first 2 photo links, one forward, one aft starboard), 4x8 cell A43 (Aster 15)-2x8 cells starboard-forward,2x8 cells port-aft. Sensor adds are WASS SNA-2000 Mine Avoidance Sonar, Fire Controls are SELEX ES RTN-25X Orions. Everything else looks ok to copy from last entry.

https://twitter.com/CavasShips/status/1367720415762726912/photo/1
https://twitter.com/CavasShips/status/1367720415762726912/photo/3
https://www.navyrecognition.com/index.php/world-naval-forces/west-european-navies-vessels-ships-equipment/italian-navy-marina-militare-vessels-ships-equipment/aircraft-carriers/8408-conte-di-cavour-aircraft-carrier-italian-navy-technical-data.html
https://en.wikipedia.org/wiki/Italian_aircraft_carrier_Cavour

**Comment by PygmalionOfCyprus** [comment]
Fixed, and did a big revamp of the sensors, etc. in accordance with above sources for 493.
