### ISSUE TITLE
China, CJ/DF-100 cruise missile, range extension

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5402]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3668 3669 4543

### Summary of Changes

- [ ] Increase range to 2160nm (4000km)

### Sources

https://www.sinodefenceforum.com/t/chinese-hypersonic-developments-hgvs-hcms.8717/page-152#post-1135413
https://twitter.com/Hurin92/status/1858517876145008921

**Comment by Jkryos** [comment]
I increased range to 1620 nmi. The infographic gives the range between 3000 km and 4000 km. I am also slightly dubious of that source because if my translator is correct it is claiming it is hypersonic even though it only barely can touch Mach 4 depending on the flight profile. Updated DB3K 510.
