### ISSUE TITLE
Please consider adding the Cessna 182 Skylane to both DBs (Civilian, in service with many militaries)

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#541]
### DB Selector

Both

### Baseline

Cessna 172 is close I suppose

### Hypothetical

No

### Name

Cessna 182 Skylane

### Country

Civilian, see list of operators: https://en.wikipedia.org/wiki/Cessna_182_Skylane#Operators

### Service

Civilian

### In Commission

1956-

### Length (m)

8.6868

### Wingspan (m)

11

### Height (m)

2.8

### Empty Weight (kg)

698.5322

### Maximum Takeoff Weight (MTOW) (kg)

1406.136

### Payload Weight (kg)

466.7465

### Crew

1

### Propulsion

1x Continental O-470-L (230 hp/172 kW)

### Rate of Climb (ft/min)

1120 (sources vary)

### Service Ceiling (ft)

20000 (sources vary)

### Military/Afterburner Speed (kt)

156

### Cruise Speed (kt)

118 (sources vary)

### Supercruise

No

### Ferry Range (nm)

1480

### Endurance (min)

Lots of data here https://www.planeandpilotmag.com/article/1956-cessna-182-n4966e-2/

### Takeoff / Landing Distance (m)

188 / 185

### Fuel Capacity (kg)

87 Gallons (unknown for kg)

### Sensors

1x Generic Weather Radar

### Mounts

None

### Loadout Options

3x Passengers

### Comms/Datalinks

HF Radio [Unsecure] (Assumed)

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

The specifications I've given are for the baseline Cessna 182, as far as I'm aware. Most of the research I conducted on the plane was because of Venezuelan Cessna 182s, which are (mostly) the 182N variant. There's no major changes as far as I can tell until the 182T variant, which is the most recently produced example. I would suggest simply implementing the 182 as a generic civilian aircraft for now. I didn't feel like doing all the research on specifics of each and every variant, so I'll just be as broad as possible with this!

### Sources

https://www.globalair.com/aircraft-for-sale/Specifications?specid=259
https://aviatorinsider.com/airplane-brands/cessna-182/
https://www.planeandpilotmag.com/article/1956-cessna-182-n4966e-2/
https://www.cessnaflyer.org/specifications-182.html#item_935

**Comment by PygmalionOfCyprus** [comment]
Added 494.
