### ISSUE TITLE
Duplicate Entries

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#542]
### DB Selector

DB3K

### Affected DBID(s)

2175&3509, 2013&3501, 1544&3502

### Summary of Changes

Appears to be duplicate entries, info looks the same, one has a picture and the other does not.

### Sources

DB3K: 2175&3509, 2013&3501, 1544&3502

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #460
