### ISSUE TITLE
Request for Increasing Max Speed to Mach 5 for PAC-3 ERINT/MSE

### ISSUE THREAD

**Issue by sr71xx** [PygmalionOfCyprus/cmo-db-requests#5447]
### DB Selector

DB3K

### Affected DBID(s)

weapon 1150, weapon 3207

### Summary of Changes

**_-Increase maximum missile speed to mach 5 / 3334kts for both PAC-3 ERINT and PAC-3 MSE (weapon 1150, weapon 3207 respectively)_**
most sources indicate a speed of at least mach 5 for the PAC-3 variants

### Sources

https://en.missilery.info/missile/erint
http://www.astronautix.com/p/pac-3.html
https://www.redstar.gr/index.php?option=com_content&view=article&id=3297:patriot-pac-iii-mobile-surface-to-air-missile-system&catid=546&lang=en&Itemid=552
https://armyrecognition.com/military-products/army/air-defense-systems/air-defense-vehicles/patriot-pac-3-mse-gem-t-air-defense-missile-system-data#:~:text=Active%20radar%20seeker%20in%20the,missile's%20onboard%20inertial%20navigation%20system.&text=Top%20speed%20of%20Mach%205,(6%2C173%20km%2Fh).

**Comment by KushanGaming** [comment]
Done for DB510.
