### ISSUE TITLE
Poland 272 Gen. K. Pulaski [Perry]

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#546]
### DB Selector

DB3K

### DBID to Copy

2414

### Hypothetical

No

### Name

272 ORP Gen. K. Pulaski 

### Country

Poland

### Service

Navy

### In Commission

2018

### Mounts

- Add #1197 MK13 Mod 4 
- Add #6 Phalanx CIWS (on hangar)

### Other Changes

- Add Link 16

- Also please note that in Janes 2003-2004 the MK13 is shown as active as is the CIWS. On DB#1767 and #2414 both weapons are missing. Unfortunately Janes 2003-04 is the latest copy I have to reference.

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2018/august-2018-navy-naval-defense-news/6476-polish-navy-perry-class-frigate-in-maiden-sm-1-sam-test-firing.html#:~:text=Pu%C5%82aski%20is%20one%20of%20two,of%20the%20Combat%20Warship%20Squadron.
https://romeosquared.eu/2018/03/20/poland-extends-service-life-of-perry-class-frigates-until-2024/
https://armstrade.org/includes/periodics/news/2018/0319/134545870/detail.shtml
Janes 2003-2004, pg. 545

![43409149334_092e018a4a_b](https://user-images.githubusercontent.com/99632305/157165026-0cf61077-bb6f-4bb4-8330-e13824316089.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494. I've also given all versions of the Polish Perrys back their Mk13 Mod 4s and Phalanx CIWS; if Janes is accurate (and I have no reason to doubt them in this particular case) it seems very unlikely to me that the weapons would have been removed in ~2000 and then re-added a couple years later. (Of course, I could be wrong and putting my stupidity in writing for posterity, but I feel safe enough to make the change now and eat my words if necessary later.)

**Comment by tbrandon517** [comment]
Well feom it's history USS Clark FFG-11 was decommissioned by the the USN and then immediately handed over to a waiting Polish and commissioned as the Pulaski. That was before they started removing the Mk13s.

Here's a 2004 shot from navsource showing the Phalanx and the one armed bandit.

![image](https://user-images.githubusercontent.com/99599482/159820325-daf8b665-8df3-402f-a6af-efa78ebb7773.png)

http://www.navsource.org/archives/07/0711.htm

**Comment by cdnice55** [comment]
To make you feel even more secure, I found one from 2008 as well ;-) :

![CSpolish0417](https://user-images.githubusercontent.com/99632305/159837355-e800495e-2495-4677-a99f-77c5efa97182.jpg)

http://clydesights.com/2008/04/orp-general-k-pulaski-272.html
