### ISSUE TITLE
Almost all F-105 Thunderchief versions have wrong number of engines

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#547]
### DB Selector

CWDB

### Affected DBID(s)

Almost all F-105 Thunderchief versions

### Summary of Changes

I've noticed that almost all F-105 Thunderchief versions in the current CWDB have 2x J75 engines. The F-105 should have only **one** J75.

### Sources

[https://www.nationalmuseum.af.mil/Visit ... nderchief/](https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196044/republic-f-105g-thunderchief/)

[https://www.nationalmuseum.af.mil/Visit ... nderchief/](https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196054/republic-f-105d-thunderchief/)

https://en.wikipedia.org/wiki/Republic_F-105_Thunderchief#Specifications_(F-105D)

**Comment by Jkryos** [comment]
Fixed CWDB 494.
