### ISSUE TITLE
Mine loadouts for the B-29

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#549]
### DB Selector

CWDB

### User(s)

US B-29s- DBID 388 and 2193, Perhaps British Washingtons

### Weapons Carried

 7 x Mark 25 Mines
Perhaps Mark 36 Mines as well? 

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Probably same as the bombload of similar weight

### Weather Restrictions

Limited All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Used extensively during "Operation Starvation" during WWII, presumably the capability would have been maintained after the war.

Seems to have been done from lower altitude. Would use Hi-Lo-Hi or Hi-Med-Hi, I think  

### Sources

http://www.navweaps.com/Weapons/WAMUS_Mines.php

https://media.defense.gov/2009/Oct/08/2000459105/-1/-1/0/091008-F-1234S-002.JPG
(At the NMUSAF, the Mark 25 is part of the B-29 display)

https://en.wikipedia.org/wiki/Operation_Starvation

**Comment by PygmalionOfCyprus** [comment]
Handled 503.
