### ISSUE TITLE
Correction to sensors on Ship_1326 and _2238 HMCS Mackenzie DELEX

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#55]
### DB Selector

DB3K

### Affected DBID(s)

Ship_1326 and Ship_2238

### Description of Problem

The DELEX (Destroyer Life Extension) replaced the SQS-503 sonar with the SQS-505 sonar. The ships also had LINK 11 added during the DELEX. Current database has ship with -503 sonar and no LINK 11.
<detail>
<evidence>
Couhat, Jean L., and A. D. Baker. Combat Fleets of the World 1990/91: Their Ships, Aircraft, and Armament. US Naval Institute Press, 1990. pg 55 accord https://en.wikipedia.org/wiki/Mackenzie-class_destroyer#cite_note-con-1;
http://jproc.ca/rrp/rrp2/1980s_adlips_link.html

### Recommended Fix

Add LINK 11 and replace SQS-503 sonar with the SQS-505

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
