### ISSUE TITLE
Please add JAS 39 to Hungary 

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#551]
### DB Selector

DB3K

### DBID to Copy

#816 (JAS 39C) & #3364 JAS 39D

### Hypothetical

No

### Name

JAS 39 C and JAS 39 D

### Country

Hungary

### Service

Air Force

### In Commission

2006

### Sensors

5x Litening 4i LDP (Laser Designator Pod) in total.

### Mounts

40 x AIM-120C-5 in 2006/2007 plus 180 AIM-120C-7 in 2020
AIM-9L
100x AGM-65 Maverick

### Loadout Options

Typical loadout is 2x AIM-120 and 2x AIM-9L and a centreline tank in the air-to-air role.

For A/G see sources links.

### Other Changes

Remove the Swedish weapons like BK 90, rocket pods, RB 15F, RB 74 Sidewinder, RB-75, RB 98 and RB 99 but retain the GBU-12 loadout. Replace RB 75 Maverick with AGM-65H/G.

Their jets’ air-to-ground weapons include AGM-65H and AGM-65G-2 Maverick missiles and 500lb (227kg) Mk82 ‘dumb’ and GBU-12 precision-guided bombs.
See sources for more details

### Sources

http://en.aviation-report.com/hungarian-air-force-from-mig-to-gripen/
https://www.janes.com/defence-news/news-detail/hungarian-gripens-showcase-new-capabilities-in-nato-baltic-air-policing-mission

Loadouts:
https://www.janes.com/images/default-source/news-images/fg_2393642-idr-427.jpg?sfvrsn=3140112c_2
https://www.thedefensepost.com/2019/08/28/us-hungary-amraam-air-to-air-missiles/
https://www.saab.com/newsroom/stories/2021/september/gripen-plays-an-important-role-at-the-ample-strike-2021
https://www.keymilitary.com/article/hungarian-gripens-hit-north
https://www.youtube.com/watch?v=hiInxo4SifQ
https://twitter.com/gripennews/status/946515959237545984 (4x GBU-12s)
https://cdn.airplane-pictures.net/images/uploaded-images/2021/9/26/1420409as.jpg (AMRAAM & GBU-12 combi)

**Comment by Huib18** [comment]
The Hungarian Government Commissioner Office responsible for defence development and the Swedish Defence Materiel Administration (FMV) have successfully completed the negotiations for the MS20 Block 2 capability upgrade to the Hungarian fleet of Gripen fighter aircraft. From 2023 onward.

New radar PS-05/A Mk 4, Latest Link-16 and Mode-5 IFF, new comms.
New weapons include IRIS-T missiles. 
But no contract **yet** for Meteor or GBU-49's.


**Sources:**
https://frontierindia.com/hungary-modernises-gripen-c-d-to-the-ms20-block-2-standard-buys-iris-t-missiles/
https://www.saab.com/newsroom/press-releases/2022/saab-to-deliver-upgrade-for-hungarian-gripen-fleet
https://www.janes.com/defence-news/news-detail/hungary-to-upgrade-gripens

**IRIS-T deal**
https://hungarytoday.hu/hungarian-military-missile-purchase/
https://www.overtdefense.com/2021/12/23/hungary-purchases-iris-t-missiles-as-part-of-the-gripen-ms20-block-ii-modernization-program/
https://esut.de/en/2021/12/meldungen/31569/31569/

**Comment by Huib18** [comment]
Just saw a picture of a Hungarian Gripen with a probable  #93 GBU-38 JDAM Mk82.
But I am not certain:
https://www.facebook.com/saabtechnologies/photos/a-rare-view-of-a-gripen-and-some-of-its-necessities-created-by-the-personnel-at-/4549261935114471/

**Comment by claudejdev** [comment]
Some background about IOC and orbat :

> The JAS39 Gripens are currently being upgraded and are leased until 2026. With the upcoming end-date of the lease contract, the HuAF has chosen to update thirteen JAS39s instead of leasing new-build JAS39E Next Generation Gripens. 
> Except for one dual Gripen, Hungary will upgrade twelve JAS39C and one JAS39D to the newest MS20 Block 2 standard, which is also the most recent version of the Gripen C and D variants used by the Flygvapnet (Swedish Air Force). One of the dual-seat 
> Gripens, serial 44, is ex Swedish AF and is already MS20 Block 2 standard. This fighter was delivered on 1 July 2016 as a replacement for the one that crashed. 

Air-to-air with Gripens. The Aviation Magazine, N°77, March-April 2022, pg 7;
https://lowpassaviation.com/wp-content/uploads/The-Aviation-Magazine-MarchApril-2022.pdf

**Comment by tbrandon517** [comment]
Additional Report on Upgrades

https://www.scramble.nl/military-news/hungarian-gripens-to-be-upgraded?fbclid=IwAR1iZ69NujCHBjOMu3dkQD6YtX2ydiFKK2hewlpA5P8lsYC4i17PcZVNnAE

**Comment by PygmalionOfCyprus** [comment]
These were technically added 493 but with a "default" loadout set; will update weapons based on above information.

**Comment by PygmalionOfCyprus** [comment]
Fixed 494! If anyone has any more info about whether/when the Hungarian Gripens received their various software updates between 2006-2023 (MS18, MS19, etc.) let me know.

**Comment by claudejdev** [comment]
> Fixed 494! If anyone has any more info about whether/when the Hungarian Gripens received their various software updates between 2006-2023 (MS18, MS19, etc.) let me know.

Asking around, ie. have asked Saab.
Could you please add the "help wanted" label ? It would make it easier to remember

**Comment by PygmalionOfCyprus** [comment]
Done.
