### ISSUE TITLE
Add: Gen. Ba-Oumar class ship, Gabon Navy

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#552]
### DB Selector

DB3K

### Baseline

#325 & #687 (France), #2824 (Kenya, ex-France)

### Hypothetical

No

### Name

Large Patrol Craft (PBO), P07,General D Armee Ba-Oumar 

### Class

Ba-Oumar (P-400)(French Super-Patra design)

### Country

Gabon

### Service

Navy

### In Commission

1988 - present

### Length (m)

54.6

### Beam (m)

8

### Draft (m)

2.5

### Standard Displacement (t)

371.5 (src2)

### Full Displacement (t)

453

### Complement

32 + 23 extra or 32 + 20 troops (src2)

### Primary Propulsion Type

Diesel

### Propulsion

2x Wartsila UD33V16 diesels, 2 shafts

### Flank Speed (kt)

24

### Range (nm) at Speed (kt)

4200 @ 15 (src1), 4400 @ 14.5 (src2)

### Sensors

Decca 1226C I-band navigation (both units)
CSEE Naja EO director (P07)

### Mounts

1x Bofors 57mm/70 SAK 57 Mk2 (P07)
1x 20mm/90 GAM B1 (P07)
2x Giat F2 20mm/90 (P08)

### Aircraft & Docking Facilities

1x RHIB Aft
1x crane

### Comments

2 units in class.

### Sources

Src 4 is generic P-400 class
1: JFS 2015-2016
2: MilPer 2006
3: https://www.navypedia.org/ships/gabon/gab_cf_general_darmee_ba_oumar.htm
4: https://en.wikipedia.org/wiki/P400-class_patrol_vessel
![2](https://user-images.githubusercontent.com/99532490/157207124-60b5070a-409b-4547-9384-c4a7207c328b.jpg)
![1](https://user-images.githubusercontent.com/99532490/157207134-177f09a2-b2d3-4405-9967-a962019bc5e6.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added both to 494.
