### ISSUE TITLE
Please add JAS 39 Gripen to Czech Republic

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#553]
### DB Selector

DB3K

### DBID to Copy

#816 (JAS 39C) & #3364 JAS 39D

### Hypothetical

No

### Name

JAS 39 C and JAS 39 D

### Country

Czech Republic

### Service

Air Force

### In Commission

2005

### Sensors

4x Litening-4I targeting pod 

### Mounts

Same removal of Swedish weapons as the item JAS 39 for Hungary item #551

Here are a lot of details, make a choice yourself what to include and what not:

Gripen did not do much at the beginning of his service in the Czech Air Force. The aircraft were delivered in the original software edition MS18.5 (Materiel System - sometimes referred to as MS18 Block 5), which gave it only initial operational capabilities , limited essentially only to the use of Mauser BK-27 on-board cannon caliber 27 mm and anti-aircraft missiles short-range AIM-9L Sidewinder, which, in addition, the Czech Republic only lent.

In 2006, the MS18.7 software was put into operation, which was associated with the integration of a more modern version of the Sidewinder AIM-9M-9 and especially the powerful medium-range anti-aircraft missiles AIM-120C-5 AMRAAM, which were introduced in 2008. A modern system of self-protection and electronic warfare EWS39, an IFF identification device and a communication system resistant to interference Have Quick II were put into operation on Gripen as part of the upgrade to MS18.7. Combat capabilities were also improved by the new modes of the onboard radar PS-05 / A Mark 3.

In 2012, another modernization took place, when the entire fleet of Czech Gripen switched to the MS19.2 software edition. In this case, the radar and its meteorological and surveillance regime were improved, plus the regime for strikes on ground targets, although the only usable armament for "Air-To-Ground" missions at that time remained only a cannon on our machines. There have also been improvements in the navigation system, the Swedish TIDLS data plant, the EWS39 self-protection and electronic warfare system, and the ground-based planning and evaluation system.

In 2015, another software update was carried out to version MS19.3, which again improved the system of self-protection and electronic warfare EWS39

After extending the lease for at least another 12 years, the last and most extensive modernization program that the Czech Gripenes underwent in 2016-2018 was launched in connection with the planned transition to the latest software edition MS20 Block 1.2 in spring 2018 , which we informed you in detail. article " [Czech Gripenas switch to the new software edition MS20](https://translate.google.com/website?sl=auto&tl=en&hl=nl&client=webapp&u=http://czechairforce.com/news/ceske-gripeny-prechazeji-na-novou-softwarovou-edici-ms20/) ". The modernization took place directly at the manufacturer in Linköping, Sweden, where the planes gradually flew as part of regular work after 1,600 flight hours. 

During the modernization, members of the 211th Tactical Squadron still managed to participate in the third operation ASICIPPN III, when the squadron sent to the protection of Iceland's airspace a standard number of 4 +1 JAS-39 Gripen aircraft and a total of up to 66 people. The task force operated at the Keflavík air base, including the preparatory and deployment phases from September 25 to November 7, 2016, the operational task was performed from October 5 to 31, 2016. This mission is interesting for another priority when the Czech Police for the first time operationally used medium-range missiles AIM-120C-5 AMRAAM.

Czech air force could not operate with A/G armament until 2014 (MS20 software update). But had no bombs until 2018!
The Czech Republic specifically ordered 120 pcs of bombs Mk.82 caliber 500lb (227kg) filled with tritonone ***and 60 pcs of training bombs Mk.82 INERT, which should all be produced by the Spanish company EXPAL Systems SA. 139, which should be supplied by the Czech trading company Max Merlin Ltd. The supply of ammunition was originally supposed to take place in 2017, but in January 2018 the ammunition was still not in the Czech Republic. However, the purchase of anti-ground ammunition for Gripen aircraft will continue, as the Ministry of Defense of the Czech Republic announced another tender at the end of April 2018, this time for the supply of 140 Mk.82 bombs, of which 50 should be training INERT and 90 sharp, the contents again considered Tritonal or PBXN-109). The delivery should take place in three stages between 2018 and 2020.

### Loadout Options

No sources of air-to-ground armament has been found for the Czech JAS 39 Gripen.  
They appear to be in air-to-air role only, even after the MS20 upgrade. No picture found. Although one source mentioned Mk82

### Other Changes

In 2015, the service decided to upgrade its fleet to the MS20 configuration. The MS20 upgrade was completed in 2018.
The Czech JAS-39 Gripen will now receive, for example, a new coding device for communication, a compatible NATO datalink or pilot glasses for night vision.

https://www.saab.com/newsroom/press-releases/2018/czech-air-force-gripen-fleet-completes-ms20-upgrade-giving-enhanced-operational-capabilities

### Sources

https://www-armadninoviny-cz.translate.goog/moznosti-dalsi-modernizace-a-provozu-stroju-jas-39cd-gripen-vzdusnych-sil-acr.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=nl&_x_tr_pto=wapp
http://afterburner.com.pl/fourteen-years-of-fourteen-gripens-in-the-czech-air-force/

Details MS20 software
https://czechairforce-com.translate.goog/news/ceske-gripeny-prechazeji-na-novou-softwarovou-edici-ms20/?_x_tr_sch=http&_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=nl&_x_tr_pto=wapp

**Comment by PygmalionOfCyprus** [comment]
Added 494! Thanks for the detailed ticket; it was interesting and fun to implement. The Czech Air Force now has a correspondingly detailed Gripen series to play with!
