### ISSUE TITLE
Add: Gen. N.Boulingui class ship, Gabon Navy

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#554]
### DB Selector

DB3K

### Hypothetical

No

### Name

Fast Attack Craft (PTM), P10, General Nazaire Boulingui 

### Class

Boulingui 

### Country

Gabon

### Service

Navy

### In Commission

2000 - present

### Length (m)

42

### Beam (m)

7.7

### Draft (m)

1.9

### Standard Displacement (t)

Not found

### Full Displacement (t)

163

### Complement

20

### Primary Propulsion Type

Diesel

### Propulsion

3x SACM AGO195 12CSNR (was <2000 3x MTU 20V672 TY90), 3 shafts

### Fuel Capacity (kg)

28 tons

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

1500 @ 15

### Sensors

1x Decca RM1226 I-band navigation

### Mounts

1x Bofors 40mm/70 564
1x 20mm/90 GAM-B01

### Ship Codes

Wooden Hull Construction

### Comments

Triple-skinned mahogany-hulled boat.
First period is 1978-1999:
- 3 MTU 20V672 TY90 diesels
- 2 x 2 SS-12M SSM (4 SS-12M)

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/gabon/gab_cf_president_el_hadj_omar_bongo.htm

**Comment by Jkryos** [comment]
Added DB3K 509.
