### ISSUE TITLE
H145M (LUH SOF) for Germany

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#555]
### DB Selector

DB3K

### DBID to Copy

#4853 H.135 T2 (Australia - 2019)

### Hypothetical

No

### Name

H145M (LUH SOF)

### Country

Germany

### Service

Army (Special Forces)

### In Commission

2017

### Sensors

-Equipped with missile warning systems and RWR at the front and at the back and 4x flare dispensers.
https://www.bundeswehr.de/resource/image/119006/landscape_ratio16x9/800/450/d92201fcc7b7b8a74ec84c182280de2d/45D1D9690482837CBCD939B9364A3AD7/h145m-soldaten-beim-abseilen.jpg

- Secure comms

### Mounts

Armed with miniguns in the doorsways.
https://www.airbus.com/sites/g/files/jlcbta136/files/styles/airbus_1920x1920/public/2021-08/H145M-Bundeswehr-13.jpg?itok=TspDh8eM

### Loadout Options

Please add 4 heavy loaded or 7 light loaded SOF for troop transport.

Medevac variant max up to 2x litters and 2 paramedics.
https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Maple_Resolve_2014_140520-Z-SU669-460.jpg/1280px-Maple_Resolve_2014_140520-Z-SU669-460.jpg
https://pbs.twimg.com/media/EkYhgH0VgAsx9nQ?format=jpg&name=medium

Please remove FLIR pod. Not used on 

### Other Changes

Intro tekst:
The H 145M is a Light Utility Helicopter Special Operations Forces ( LUH SOF) Light Utility Helicopter - Special Operations Forces), so a light utility helicopter for support of special forces. The machine is tailored to their needs. Each H 145M brings four fully equipped special forces soldiers, such as the KSKSpecial Forces Commandor the KSMNavy Special Forces Command, to their place of use. In the future, the helicopter will also be able to provide fire support and reconnaissance from the air. In addition, the wounded will soon be able to be evacuated with this helicopter.

Cruise speed just over 130 kts.

15 ordered.

### Sources

https://www.airbus.com/en/products-services/helicopters/military-helicopters/h145m
https://www.bundeswehr.de/de/ausruestung-technik-bundeswehr/luftsysteme-bundeswehr/h145m-luh-sof
https://www.thedrive.com/the-war-zone/42083/germany-sending-special-ops-helicopters-to-kabul-to-rescue-evacuees-outside-the-airport
https://pbs.twimg.com/media/EkYhgH0VgAsx9nQ?format=jpg&name=medium
https://mediaassets.airbus.com/pm_38_379_379477-atewgmdurt.pdf?dl=true

**Comment by PygmalionOfCyprus** [comment]
Already in the DB as DBID 4936, but made some tweaks to incorporate this info.

**Comment by Huib18** [comment]
The new light support helicopter for the special forces (LUH SOF, Light Utility Helicopter Special Operations Forces ),  has been called the **MBB BK-117** since this month - after five years in which Parliament, the Ministry of Defense and the German Armed Forces always spoke and wrote about the H145M helicopter , the name was changed without further ado.
https://augengeradeaus.net/2020/11/h145m-heisst-jetzt-mbb-bk-117-sonst-aendert-sich-nix/

http://www.flying-wings.com/luftwaffe-h145m-luh-sof

**Comment by PygmalionOfCyprus** [comment]
Name adjusted.

**Comment by Huib18** [comment]
Thanx, I could not find the H145 in de DB, Even after typing H145 or H145M etc.
Now after a restart it does. Thanx for your patience..
