### ISSUE TITLE
Please add #4936 MBB BK-117 helicopter as a loadout for the A-400 Atlas of Germany.

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#556]
### DB Selector

DB3K

### User(s)

#1403 A400M Atlas and #4918 A.400M Grizzly for Germany

### Weapons Carried

One #4936 MBB BK-117 helicopter with rotorblades removed.
Ready to fly after 6 hrs after unloading.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Cargo is less than 4 tons, so 3450 Nm must be possible

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://www.thedrive.com/the-war-zone/42083/germany-sending-special-ops-helicopters-to-kabul-to-rescue-evacuees-outside-the-airport

However, after the disassembly of the rotor blades the H145M is on the other hand still small enough to fit in the cargo bay of the Luftwaffe’s Airbus A400M, and therefore worldwide deployable.
http://www.flying-wings.com/luftwaffe-h145m-luh-sof

**Comment by tbrandon517** [comment]
![200](https://user-images.githubusercontent.com/99599482/157259506-d9a104a5-3be7-43fa-860f-7638a27f1b84.gif)

**Comment by KLABDB3K** [comment]
Spent hours learning how to get LUA to replicate transporting helos in fixed wing transports so this is intriguing!

**Comment by claudejdev** [comment]
> Generally we haven't created loadouts to handle transporting specific aircraft, ground units, etc. as cargo.
> 
> However, **[REDACTED]**.
> 
> Stay tuned~ ;)

DataContainer ? 8)
