### ISSUE TITLE
Please add chaff/flare dispenser for BAE Hawk 108 & 208

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#557]
### DB Selector

DB3K

### Affected DBID(s)

1398 BAE Hawk 108 & 182 BAE Hawk 208

### Summary of Changes

-Add chaff/flare dispenser for Bae Hawk 208 as it were demonstrated releasing flares during Merdeka Parade 2018.
![image](https://user-images.githubusercontent.com/99646926/157240493-c7f7a1ec-8cfd-4c76-b5f7-9a25b726e07f.png)

-Add chaff chaff/flare dispenser for Bae Hawk 108 as it were demonstrated releasing flares during 25th Anniversary RMAF Hawk Fleet.
![image](https://user-images.githubusercontent.com/99646926/157241808-c478a1a0-ec58-4d12-b3e5-870c2c001601.png)

### Sources

https://www.youtube.com/watch?v=1Ng7bt-kEtY 
https://twitter.com/ck1157/status/1035767434521661442

**Comment by PygmalionOfCyprus** [comment]
Related to #540

**Comment by Jkryos** [comment]
Added DB3K 494.
