### ISSUE TITLE
Generic Cargo Mount for each CargoType, copy of DataMount 'Personnel' ID = 3037

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#558]
### DB Selector

DB3K

### DBID to Copy

3037

### Hypothetical

No

### Name

[Size] Cargo

### Country

Generic

### Service

Generic

### Mounts

Replace cargotype 'Personnel (Squads, MANPADS, ATGM)'ID = 1000;
by one of each : 

- 'Small Cargo (Car, AAA Guns, AMRAAM)'ID = 2000;
- 'Medium Cargo (APC, Towed Arty, Cruise Missiles)'ID = 3000;
- 'Large Cargo (Tank, TEL, Trailer)'ID = 4000;
- 'Very Large Cargo (IRBM / ICBM TEL)'ID = 5000;

Adjust the CargoMass, CargoArea, Crew and Paradrop_capable values.

### Sources

The reasoning here is to allow players and designers alike to perform complex, while still abstracted, logistical operations.
Having a generic cargo element would be a convenient way to do it.

(Edit for splelling...)

**Comment by PygmalionOfCyprus** [comment]
Good idea.

**Comment by PygmalionOfCyprus** [comment]
Added 494.
