### ISSUE TITLE
Add J-83K and YJ-91A/YJ-91 (ASM/ARM) to both FC-31 variants

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#56]
### DB Selector

DB3K

### Affected DBID(s)

Aircrraft_4454, Aircrraft_2917

### Summary of Changes

Please consider adding YJ-83K and YJ-91A/YJ-91 (ASM/ARM) to both FC-31 variants...
</summary>
<detail>
Please consider adding the following loadouts to both variants of the FC-31 (#2917 & #4454 in DB):

1. A Short-Range Loadout of: 4x *EXTERNAL* YJ-83K's (#2137 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB)

2. A Long-Range Loadout of: 2x *EXTERNAL* YJ-83K's (#2137 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB) + 2x *EXTERNAL* 1700L Drop Tank (#1533 in DB)

3. A Short-Range Loadout of: 4x *EXTERNAL* YJ-91A's (#2874 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB)

4. A Long-Range Loadout of: 2x *EXTERNAL* YJ-91A's (#2874 in DB) + 2x *INTERNAL* PL-12C's (#2108 in DB) + 2x *EXTERNAL* 1700L Drop Tank (#1533 in DB)

The following detailed analysis of the "newest" version of the FC-31 points to the existence of 6 External hardpoints *in addition to* the two Internal weapon bays with 2 Internal hardpoints in each of the bays. The 1st article identifies the YJ-83K and the YJ-91A/YJ-91 as possible armaments for the External hardpoints. Once you do the math for the max take-off weight and the weight of the ordinance, the above suggested loadouts seem to be plausible. I also found corroborating evidence of the existence of the 6 External hardpoints in the 2nd article provided. Please let me know if you need any additional information...

### Sources

1. (http://fullafterburner.weebly.com/aerospace/analysis-of-the-latest-prototype-of-shenyang-j-31)
2. (https://www.globaldefensecorp.com/2020/06/30/shenyang-fc-31-j-31-a-copycat-f-35-through-cyber-espionage/)

**Comment by CV60LCC19** [comment]
This issue has already been submitted by another user.

**Comment by PygmalionOfCyprus** [comment]
@CV60LCC19 Tagging duplicates is extremely useful, thank you. For future reference, could you include a reference to the duplicate issue in question (e.g. #50) so we can link them appropriately?

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #50
