### ISSUE TITLE
Latvia A-53 Virsaitis [Vidar-class Minelayer]

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#560]
### DB Selector

DB3K

### DBID to Copy

2145

### Hypothetical

No

### Name

A-53 Virsaitis

### Country

Latvis

### Service

Navy

### In Commission

2003-

### Mounts

- Add 2x Triple 324mm Torpedo Tubes

### Other Changes

The record for the Norway entry doesn't seem to have the minelaying capability added. I have not played with mine laying before so am unsure what to add for that ability. Can carry 400 mines.

The Vidar entries 2145, 2146, 2110 and 3007 for Lithuania should have minelaying capability added.

### Sources

https://en.wikipedia.org/wiki/HNoMS_Vale_(N53)
https://www.navypedia.org/ships/latvia/lv_cf_virsaitis.htm
https://www.militaryperiscope.com/weapons/ships/mine-warfare/virsaitis-53-class
https://navaltheater.com/ships/virsaitis-a53

![Kugis_Virsaitis](https://user-images.githubusercontent.com/99632305/157341974-aaf91268-b476-4b19-83c3-2fa67813d361.jpg)

**Comment by PygmalionOfCyprus** [comment]
Handled 501. No TTs, those were removed on transfer.
