### ISSUE TITLE
Estonia EML Tasuja [Lindormen Class]

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#561]
### DB Selector

DB3K

### DBID to Copy

2949

### Hypothetical

No

### Name

A 432 EML Tasuja 

### Country

Estonia

### Service

Navy

### In Commission

2006-

### Sensors

- Navigation radar 2x Litton Decca E, I-band

### Mounts

- 4x 12.7mm machine guns

### Loadout Options

- Add mines

### Other Changes

2x davit for RHIB 7m

### Sources

https://en.wikipedia.org/wiki/EML_Tasuja
https://en.wikipedia.org/wiki/EML_Wambola_(A433)
https://en.wikipedia.org/wiki/Lindormen-class_minelayer

**Comment by PygmalionOfCyprus** [comment]
Added 494. Unsure what mines Estonia uses, so I've given it a magazine of 30 PM04 and 30 PM16; there was a sale of undisclosed influence mines from Finland a couple years back which were probably these. Before the sale, though, I don't know what it would have been, if anything at all.
