### ISSUE TITLE
AIM-9C Sidewinder Critical Bug

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#564]
### DB Selector

CWDB

### Affected DBID(s)

Weapon 247

### Description of Problem

The AIM-9C Sidewinder (Weapon 247) can't be fired ("Weapon must detect target prior to firing" message on manual target allocation screen).

### Recommended Fix

Needs the "Illuminate at launch" property, I think

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Also totally reworked the DB3K version, which was just a pure copy of the R.530 SARH for some reason.
