### ISSUE TITLE
Argentina AOR Patagonia [Durance Class]

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#565]
### DB Selector

DB3K

### DBID to Copy

57

### Hypothetical

No

### Name

B1 ARA Patagonia

### Country

Argentina

### Service

Navy

### In Commission

2000-

### Sensors

2x  Decca 1226 Radars

### Other Changes

- Add Generic ESM/ECM (Janes 2003-2004 pg.18)

### Sources

Janes 2003-04
https://en.wikipedia.org/wiki/French_tanker_Durance
https://www.naval-technology.com/projects/duranceclassmultipro/

![El buque logístico ARA “Patagonia” realizó reabastecimiento en el mar_desarrollodefensaytecnologiabelica blogspot com ar](https://user-images.githubusercontent.com/99632305/157378898-f4aba549-354c-4767-bef2-ffd92591b519.png)

**Comment by PygmalionOfCyprus** [comment]
@claudejdev does that data apply to both the French and Argentinian versions of the Durance or only post-Argentina acquisition?

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also did a deep review of the Durance class and its exports: basically ripped it all up and rebuilt them from scratch. We now have separate entries for the Durance, Meuse, and Var as well to reflect their differences.

**Comment by claudejdev** [comment]
> Added 494. Also did a deep review of the Durance class and its exports: basically ripped it all up and rebuilt them from scratch. We now have separate entries for the Durance, Meuse, and Var as well to reflect their differences.

Awesome ! I'm looking forward to seeing them all :)
Oh boy, they will all need a proper picture too, that's great, the more, the merrier.
