### ISSUE TITLE
Please fix *almost* all aircraft carriers' heights / mast heights...

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#567]
### DB Selector

DB3K

### Affected DBID(s)

Almost every aircraft carrier of the following sub-types: CV, CVA, CVH, and a few CVN...

### Description of Problem

Almost all aircraft carriers' heights / mast heights are set to 0m, which negatively impacts sensor and weapon performance, especially Radars and SARH weapons...

I'll do my best to give you an overview of the units affected:

1. Every carrier of the "CV" sub-type...
2. Every carrier of the "CVA" sub-type, except for the CV 41 and CV 43 classes...
3. Every carrier of the "CVH" sub-type, except for the Moskva class...
4. Of the "CVN" sub-type, only the CVN 65 and R 91 classes are affected...

### Recommended Fix

Apart from doing a lot of research and editing each unit individually, the only temporary solution I can think of is:

Doing a bulk edit of the DB and setting all of the affected carriers' heights to between 45m-55m (which seems to be the range of the unaffected carriers' heights). It wouldn't be completely accurate, but it would be _more_ accurate than leaving them all set to 0m for an extended amount of time while research is done on the many affected carriers...

Thank you for your time,
-Noah K.

**Comment by claudejdev** [comment]
> Almost all aircraft carriers' heights / mast heights are set to 0m, which negatively impacts sensor and weapon performance, especially Radars and SARH weapons...

Does it actually ?

I wondered that too myself and concluded that the platform's signature is in fact set by the DataShipSignature table, instead of by the Height column in the DataShip table.

Thanks for filling in that report, though, I would love to have an answer to that.

**Comment by nkocevar** [comment]
> > (...) which negatively impacts sensor and weapon performance, especially Radars and SARH weapons...
> 
> Does it actually ?
> 
> I wondered that too myself and concluded that the platform's signature is in fact set by the DataShipSignature table, instead of by the Height column in the DataShip table.
> 
> Thanks for filling in that report, though, I would love to have an answer to that.

I'm not referring to the signature of the ship, but the ship's sensor's ability to "see" as high above the horizon as possible, which is important for both radar detection and illuminating targets...

**Comment by PygmalionOfCyprus** [comment]
Ships without a specified height (which you may notice is nearly all of them) default to varying mast heights depending on their size. For "Very Large" ships, which carriers obviously are, the fallback height is 50m. So, the code's got you covered even if the DB doesn't. 🙂

I'm going to mark this "wontfix," but if you find specific height data on particular vessels, feel free to post a request accordingly.
