### ISSUE TITLE
SSM Bn (FROG-7 [9K52 Luna-M] TEL) - Kuwait

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#568]
### DB Selector

DB3K

### DBID to Copy

facility/2589/DB3K and facility/1848/CWDB

### Hypothetical

No

### Name

SSM Bn (FROG-7 [9K52 Luna-M] TEL)

### Country

Kuwait

### Service

Army

### In Commission

1977-1990

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

NOTE: Request is for both CWDB and DB3K. I was note able to select both under the DB selector.

### Sources

https://www.oryxspioenkop.com/2020/03/kuwaits-little-known-9k52-luna-m-frog-7.html
https://en.wikipedia.org/wiki/9K52_Luna-M#Operators

**Comment by PygmalionOfCyprus** [comment]
Added 494.
