### ISSUE TITLE
Angola - RK Osa II [Pr.205U] - 1982

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#569]
### DB Selector

DB3K

### DBID to Copy

ship/134/DB3K

### Hypothetical

No

### Name

RK Osa II [Pr.205U] - Angola, (Navy), 1982

### Country

Angola

### Service

Navy

### In Commission

1982-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

Source indicates that of the 6 Pr.205 FAC received by Angola 2x were Pr.205ER export models already in DB and 4 were Pr.205U retired from Soviet Navy service.

https://www.navypedia.org/ships/angola/ang_cf_205.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
