### ISSUE TITLE
Vasily Bykov main armament correction

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#57]
### DB Selector

DB3K

### Affected DBID(s)

#2890 - PK Vasily Bykov [Pr.22160] (Russia [1992-] - 2017) Accuracy issues. 

### Summary of Changes

**Vessels main armament is 1 x 76mm AK-176MA NOT 57mm AU-220. See photos and the DB photo itself.** 
No sign of the quad 3M47 Komar/Gibka SAM mounting in any photos.
No Containerised Kalibr/SS-N-27/30 on any in service vessel. 
It appears that perhaps this is an optional war load but is NOT routinely fitted.
Two davits for 7m RHIB.
There is a stern well deck capable of handling a large RHIB 11m  or typically the armoured Project 02800 assault landing boat. (Pr.02800 is Not in DB3K)
The Bykov in its current form is different from the many models of it shown at defence exhibitions and cannot carry both containerised SSM, a helicopter and the stern RHIB. The containerised SSM would have to occupy the helicopter deck as there is no stern modular mission bay contrary to the original models.
Link to the You Tube documentaries show the vessels interior and shows that this is primarily a constabulary type vessel in its current form using a helicopter and the fast boats from the stern dock. 

### Sources

"Russia's Vasily Bykov Corvette Completes Arctic trials - Naval News" 
https://www.navalnews.com/naval-news/2020/11/russias-vasily-bykov-corvette-completes-arctic-trials/
https://www.youtube.com/watch?v=bEgzVEazSxc
https://www.youtube.com/watch?v=ljjQwbaXWx0
https://www.youtube.com/watch?v=i9DYIr-kVtM
https://www.youtube.com/watch?v=Gj_lW4oMfJk Pr.02800 Assault Landing boat. 
http://roe.ru/eng/catalog/naval-systems/shipborne-weapons/3m-47/ Komar Gibka mount is quite obvious when fitted and is nowhere to be seen on the vessel. 
http://roe.ru/eng/catalog/naval-systems/shipborne-weapons/komar-new/
http://roe.ru/eng/catalog/naval-systems/surface-ships-ships-and-boats/project-22160E/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493. Will probably cycle around and add a hypothetical entry at some point for the containerized stuff.

**Comment by KLABDB3K** [comment]
Thanks. Much appreciated. Agree SSM containerised hypothetical Bykov is a good idea.
