### ISSUE TITLE
Angola - MANDUME patrol boats (1993)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#573]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

P100 MANDUME patrol boats (1993)

### Class

MANDUME patrol boats

### Country

Angola

### Service

Navy

### In Commission

1993-Present

### Length (m)

29.1,

### Beam (m)

5.93m

### Draft (m)

2m

### Standard Displacement (t)

104

### Full Displacement (t)

112

### Empty Displacement (t)

Not Stated

### Complement

11

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 Paxman 16SET-CWM diesels

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

500nm @ 15 Kts

### Sensors

2x Decca radars

### Mounts

1 x 1 - 20mm/90 GAM-B01
2 x 1 - 12.7mm/90 MG

### Aircraft & Docking Facilities

Not Stated

### Comms/Datalinks

VHF/UHF Radio

### Ship Codes

Aluminum Superstructure Only

### Comments

4x Ordered in 1990 for fisheries patrol duties, delivered in 1993. Steel hull, aluminum superstructure. Refurbished in 2009.

### Sources

https://www.navypedia.org/ships/angola/ang_cf_mandume.htm
https://en.wikipedia.org/wiki/Angolan_Navy#Inland/Coastal_Patrol_Boats
http://www.hisutton.com/Guide-To-Angolan-Navy.html
![Angola-Mandume-Class](https://user-images.githubusercontent.com/99599482/157469285-a67e1e3c-6b56-497a-afb8-4122b825e143.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
