### ISSUE TITLE
Add: Cocobeach class ship, Gabon Navy

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#574]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), V7, Cocobeach

### Class

Cocobeach (VCSM)(Raidco Marine RPB 20)

### Country

Gabon

### Service

Navy

### In Commission

2010 - present

### Length (m)

20

### Beam (m)

5.2

### Draft (m)

1.5

### Standard Displacement (t)

32 (src2)

### Full Displacement (t)

42 (src2)

### Complement

8 (src2)

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN V12, 2 shafts

### Flank Speed (kt)

25 (src1), 28 (src2)

### Range (nm) at Speed (kt)

530 @ 15 (src1), 600 @ 18 (src2)

### Sensors

1x furuno I-band navigation radar

### Mounts

1x 7.62mm/90

### Sources

Src 2 & 3 are generic 
1: JFS 2015-2016
2: https://www.navypedia.org/ships/gabon/gab_cf_coco_beach.htm
3: https://www.homelandsecurity-technology.com/projects/vedette-cotiere-de-surveillance-maritime-boats
4: https://fr.wikipedia.org/wiki/Vedette_c%C3%B4ti%C3%A8re_de_surveillance_maritime
![1](https://user-images.githubusercontent.com/99532490/157470678-575a8146-c46e-49af-ad88-aeeefcccf61b.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
