### ISSUE TITLE
Angola - PATRULHEIRO patrol boats (1993)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#575]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

PATRULHEIRO patrol boats (1993-1994)

### Class

PATRULHEIRO patrol boats

### Country

Angola

### Service

Navy

### In Commission

1993-Present

### Length (m)

19.3m

### Beam (m)

5.55m

### Draft (m)

1m

### Standard Displacement (t)

Unknown

### Full Displacement (t)

UnKown

### Empty Displacement (t)

Unknown

### Complement

8

### Max Sea State

Unknown

### Primary Propulsion Type

Diesel

### Propulsion

2 Baudouin V12BTI diesels

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

1000nm @ 18kts

### Sensors

1x Furuno 1830 radar

### Mounts

No Mounts. Small Arms Only

### Aircraft & Docking Facilities

Not Known

### Comms/Datalinks

VHF/UHF Radios

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

French supplied Plascoa type. GRP hull.

### Sources

https://www.navypedia.org/ships/angola/ang_cf_patrulheiro.htm
http://www.hisutton.com/Guide-To-Angolan-Navy.html
https://en.wikipedia.org/wiki/Angolan_Navy#Inland/Coastal_Patrol_Boats
![ang_cf30](https://user-images.githubusercontent.com/99599482/157471301-861c0f3e-0349-41d4-9e80-4b69c2795691.gif)

**Comment by Jkryos** [comment]
Added DB3K 496.
