### ISSUE TITLE
JAGM IOC for AH-1Z 2022

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#576]
### DB Selector

DB3K

### Affected DBID(s)

4792

### Summary of Changes

IOC will be this year 2022. Can likely just advance the in-service date.

### Sources

https://www.navair.navy.mil/news/Marine-Corps-Joint-Air-Ground-Missile-achieves-Initial-Operational-Capability/Fri-03042022
https://www.janes.com/defence-news/news-detail/us-marine-corps-declares-ioc-with-jagm-on-ah-1z-viper
https://defbrief.com/2022/03/06/us-marine-corps-ah-1z-viper-cleared-for-jagm-missile-operations/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
