### ISSUE TITLE
Add additional generic truck variants

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#58]
### DB Selector

DB3K

### Hypothetical

No

### Name

Vehicle (Truck, Shelter, Wrecker, 2.5-ton, 5-ton, etc x 1)

### Facility Type

Supply

### Country

Generic

### In Commission

-

### Sensors

[Generic Binoculars](https://cmano-db.com/sensor/4342/) - (Surface Only) Visual
Visual, Binoculars
Max Range: 33.3 km

### Mounts

None

### Magazines

None

### Comments
This also applies to the CWDB.

This is mostly a fluff request, since a lot of the features these truck variants would add are out of the scope of the game in its current state. It would be interesting however to kit out ground units with accurately modelled TOE&Es of all their trucks and such. 

### Sources

https://en.wikipedia.org/wiki/M35_series_2%C2%BD-ton_6%C3%976_cargo_truck#Variants

**Comment by PygmalionOfCyprus** [comment]
Not worth adding to facilities as fluff considering the shift towards Ground Units for...well, ground units. Logistic vehicles, etc. pop up not infrequently as Pro requests, however, so you'll see more fidelity/options in the GU annex over time as we continue to flesh that out!
