### ISSUE TITLE
Angola - NGOLA KILUANGE patrol ships (2012)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#580]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

NGOLA KILUANGE patrol ships (2012)

### Class

Damen type 6210 FISV

### Country

Angola

### Service

Department of Fisheries

### In Commission

2012-Present

### Length (m)

61.9m

### Beam (m)

9.7m

### Draft (m)

3.25m

### Standard Displacement (t)

1022

### Full Displacement (t)

Not disclosed

### Empty Displacement (t)

Not Stated

### Complement

45

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 MTU 16V4000 M70 diesels

### Fuel Capacity (kg)

69,920

### Flank Speed (kt)

18

### Range (nm) at Speed (kt)

Undisclosed

### Sensors

1x X-band and 1x S-band

### Mounts

None

### Aircraft & Docking Facilities

1x Helicopter Deck for 3t MTOW helo.
1x davit for 6.7m inspection launch
1x davit for Lifeboat

### Comms/Datalinks

VHF/UHF Radio

### Comments

Fishery Inspection Surveillance Vessels. 6.7m inspection launch is carried aft. Have hospital with 12 beds. 30t bollard pull.

### Sources

https://www.navypedia.org/ships/angola/ang_cg_ngola_kiluange.htm
http://www.hisutton.com/Guide-To-Angolan-Navy.html
https://products.damen.com/en/ranges/fishery-research-vessel/frv-6210
https://www.defenceweb.co.za/sea/sea-sea/damen-launches-ngola-kiluange-fishery-patrol-vessel-for-angola/

![image](https://user-images.githubusercontent.com/99599482/157478466-07fdaf23-048d-4973-921d-906c3b7fa458.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
