### ISSUE TITLE
Singapore F-16 Block 52 Radar and loadout upgrades

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#581]
### DB Selector

DB3K

### DBID to Copy

1532, 2966

### Hypothetical

No

### Name

Same 

### Country

Singapore

### Service

Airforce

### In Commission

2022

### Sensors

Replace APG-68 with AN/APG-83 AESA

### Loadout Options

Update sidewinders to AIM-9X(2)
Update Amraam to C-7
Add GBU-39 Loadout
Add Litening Pods to loadouts

May want to consider GBU-38, 54 and 31. No pictures yet but ordered lots and F-15SG got them.

### Other Changes

Link-16

### Sources

https://aviationweek.com/shownews/singapore-airshow/singapores-first-upgraded-f-16s-enter-service#:~:text=The%20RSAF's%20F%2D16D%2Bs,program%20of%20the%20type%20here.
https://www.janes.com/defence-news/news-detail/singapore-airshow-2022-singapore-receives-initial-batch-of-upgraded-f-16s#:~:text=The%20Republic%20of%20Singapore%20Air,up%20to%20Singapore%20Airshow%202022
https://www.dsca.mil/press-media/major-arms-sales/singapore-aim-120c7-amraam-and-related-support
https://nationalinterest.org/blog/reboot/small-mighty-singapores-military-can-kick-some-major-185258
https://www.ainonline.com/aviation-news/defense/2015-12-02/upgrade-singapores-f-16-fleet-goes-ahead
https://www.airforce-technology.com/news/newsus-approves-sale-for-upgrade-of-singapores-f-16cdd-aircraft-4572418/
Litening Pods
https://www.defensenews.com/resizer/dxJTyDb7kOHgIvmpQ4sEvXAWGTU=/1024x0/filters:format(jpg):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/mco/EKLILDP6BRD3BG5474JYXVPR5Y.jpg
https://www.defenseindustrydaily.com/singapore-adding-sniper-atp-pods-to-its-f-16s-04887/

Sipri Arms Db Lines
100	AIM-120C AMRAAM	BVRAAM	2014	2016-2017	(100)	AIM-120C-7 version
20	AIM-9X Sidewinder	BVRAAM	2014	2015-2016	(20)	AIM-9X Block-2 version
(250)	GBU-39 SDB	Guided bomb	2017	2020	(250)

**Comment by bostonmyk** [comment]
Add GBU-49 Loadout (2022)
https://twitter.com/TheBaseLeg/status/1564600170456973312/photo/1

**Comment by transientSG** [comment]
Add CBU-105s in the inventory as well.

https://www.defensenews.com/air/2020/02/18/singapore-expects-first-upgraded-f-16-jets-to-fly-next-year/

**Comment by beaconmail** [comment]
SIPRI Arms DB notes extensive Python 4 purchases for their F-16s as well, so may want to add for Singapore's F-16CJ/DJ:
Python 4 - 600 - 1997-2004

**Comment by transientSG** [comment]
Is there any more info required for the above? This has been outstanding for quite a while, really hope to have this updated in db500...

**Comment by transientSG** [comment]
https://euro-sd.com/2023/06/news/32434/raytheon-awarded-largest-ever-amraam-contract/

Based on latest info, the AIM-120C8 version should be in service soon on the F-16s.
