### ISSUE TITLE
Angola - BAÍA FARTA patrol ship (2018)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#582]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

BAÍA FARTA patrol ship (2018)

### Class

Damen type FRV 7417

### Country

Angola

### Service

Department of Fisheries

### In Commission

2018-Present

### Length (m)

74.1m

### Beam (m)

16.4m

### Draft (m)

8.7m

### Standard Displacement (t)

3209

### Full Displacement (t)

Not disclosed

### Empty Displacement (t)

Not Stated

### Complement

29 + 22 scientists

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 Wärtsilä 9L20 diesel-generators, 1 Wärtsilä 6L20 diesel-generator, 2 electric motors

### Fuel Capacity (kg)

151,850

### Flank Speed (kt)

15

### Range (nm) at Speed (kt)

9000nm @ 13 knts

### Sensors

1 X-band and 1x S-band nav radar
Double (2x) Retractable keel for lowering scientific transducers.
Split beam echo sounder, Simrad EK80
Multi beam echo sounder, Simrad MS70
Omni directional sounder, Simrad SU90
Trawl monitoring system, Simrad PI and FX80
Bottom sounder, Kongsberg EA640 12/200 kHz (optional)
Deepwater multi beam echo sounder, Kongsberg EM122 1x2 degree
Acoustic positioning system, Kongsberg HiPAP 501 system
Acoustic Doppler Current Profiler with a 38+150 kHz transducer
GeoAcoustic system, Kongsberg GeoPulse Plus
Thermosalinograph, Seabird SBE21
CTD and Rosette sampler, Seabird SBE911 and SBE32 (24 bottle of 10ltr)
Motion Reference Unit and extensive meteorological instruments.

### Mounts

None

### Aircraft & Docking Facilities

1x davit for 6.7m RHIB
1x ROV davit - ROV, Saab Seaeye Leopard - up to 1500 m depth (optional)

### Comms/Datalinks

VHF/UHF Radios

### Comments

Department of Fisheries. Patrol ship intended for hydrographic, acoustic, environmental and oil-and-gas survey duties.

### Sources

https://www.navypedia.org/ships/angola/ang_cg_baia_farte.htm
http://www.hisutton.com/Guide-To-Angolan-Navy.html
https://products.damen.com/en/ranges/fishery-research-vessel/frv-7417
https://www.verangola.net/va/en/072021/Environment/26506/Oceanographic-ship-Ba%C3%ADa-Farta-will-finally-sail-and-assess-fishery-resources-in-the-next-days.htm

![Angola-FRV-7417-Baia-Farta](https://user-images.githubusercontent.com/99599482/157480382-3f48327d-7337-4d2c-ac05-61b9bbf057c1.jpg)
![image](https://user-images.githubusercontent.com/99599482/157480849-15bc867a-2c9a-4666-be34-255cb4a11fe6.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
