### ISSUE TITLE
Angola - REI KINGURY KIA BANGUELA patrol craft (2009)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#584]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

REI KINGURY KIA BANGUELA patrol craft (2009)

### Class

REI KINGURY KIA BANGUELA patrol craft (2009)

### Country

Angola

### Service

Department of Fisheries

### In Commission

2009-Present

### Length (m)

47.4

### Beam (m)

7.6

### Draft (m)

2.55

### Standard Displacement (t)

320

### Full Displacement (t)

Not disclosed

### Empty Displacement (t)

Not disclosed

### Complement

unknown

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 MTU 12V4000 M70 diesels

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

420nm @ 20 kts

### Sensors

2x radars

### Mounts

None

### Aircraft & Docking Facilities

Not Stated

### Comms/Datalinks

VHF/UHF Radios

### Comments

Fisheries Patrol Ship

### Sources

https://www.navypedia.org/ships/angola/ang_cg_rei.htm

**Comment by Jkryos** [comment]
Added DB3K 496.
