### ISSUE TITLE
Angola - P618 patrol launches (2009)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#585]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

P618 patrol launches (2009)

### Class

Aresa_PVC-170 patrol launches (2009)

### Country

Angola

### Service

Department of Fisheries

### In Commission

2009-Present

### Length (m)

16

### Beam (m)

4.48

### Draft (m)

1.8

### Standard Displacement (t)

Unknown

### Full Displacement (t)

18

### Empty Displacement (t)

Not disclosed

### Complement

5

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 diesels

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

35

### Range (nm) at Speed (kt)

420nm @ 20 kts

### Sensors

1x Generic Navigation Radar

### Mounts

None

### Aircraft & Docking Facilities

Not Stated

### Comms/Datalinks

VHF/UHF Radio

### Comments

Fisheries Patrol Boat

### Sources

https://www.navypedia.org/ships/angola/ang_cg_p618.htm
https://en.wikipedia.org/wiki/Aresa_PVC-170

![ang_cg36](https://user-images.githubusercontent.com/99599482/157484580-c054f723-e454-4979-a39a-01876852a388.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
