### ISSUE TITLE
MANPADS missing Helicopter as Valid Target

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#588]
### DB Selector

DB3K

### Affected DBID(s)

730, 1409, 1847, 3314

### Summary of Changes

Some MPADS are missing Helicopter as ValidTarget

In the DataWeaponTargets table, I would suggest adding a few rows with, for each ID, CodeID = 1002 (Helicopter).

The ID would be :
730	Mistral 2
1409	Mistral 1
1847	Blowpipe
3314	KP-SAM Shin-Gung

### Sources

Jane's Naval Weapon Systems Issue # 44 - 2006
https://www.mbda-systems.com/product/mistral-manpads/

**Comment by KLABDB3K** [comment]
Just tried all these against an Mi-24 and these weapons are able to fire at and hit helicopters? I don't think the valid target label in this sense has any real impact?
Probably need an amendment to the blowpipe as its showing as a rear aspect only weapon were as its radio command guided and therefore all aspect not a stern chaser?

**Comment by claudejdev** [comment]
Awesome! I'm glad it's not an actual issue then.
Thanks for testing @KLABDB3K (as I should have done... ^^)
