### ISSUE TITLE
Angola - DV-15 High Speed Interceptor, 3x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#589]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

DV-15 High Speed Interceptor

### Class

DV-15 High Speed Interceptor

### Country

Angola

### Service

Navy

### In Commission

2018-Present

### Length (m)

15.5

### Beam (m)

3

### Draft (m)

0.8

### Standard Displacement (t)

not stated

### Full Displacement (t)

not stated

### Empty Displacement (t)

not stated

### Complement

4

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

Two diesel engines, One surface drive system (two propellers)

### Fuel Capacity (kg)

777

### Flank Speed (kt)

50+ (53 stated in one source)

### Range (nm) at Speed (kt)

350nm @ 40 Knts

### Sensors

One 4 KW Navigation radar

### Mounts

One remote-controlled gun system (up to 30 mm)

One 7.62 mm manual gun

### Aircraft & Docking Facilities

None

### Comms/Datalinks

One Tactical V/UHF

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Sources

http://www.hisutton.com/Guide-To-Angolan-Navy.html
https://www.privinvest.com/naval-vessels/interceptor-dv15-rws/
https://www.cmn-group.com/vessel/interceptor-dv15-rws/
https://defense-update.com/20040213_interceptor-dv-15.html

![image](https://user-images.githubusercontent.com/99599482/157491050-1113b601-aaef-441f-b017-2b95093eff55.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
