### ISSUE TITLE
Add Venezuelan Army AS-61

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#59]
### DB Selector

DB3K

### Hypothetical

No

### Name

SH-3D Sea King [AS-61A-4]

### Country

Venezuela

### Service

Army

### In Commission

1984-

### Length (m)

16.69

### Wingspan (m)

4.98

### Height (m)

5.13

### Empty Weight (kg)

5382

### Maximum Takeoff Weight (MTOW) (kg)

9752

### Payload Weight (kg)

3630

### Crew

2

### Propulsion

 2 × General Electric T58-GE-10 turboshaft engines, 1,400 shp (1,044 kW) each (total power limited to 2,500 hp (1,864 kW) by main gearbox)

### Rate of Climb (ft/min)

 2,200 ft/min (11.2 m/s) at sea level (All performance figures at weight of 20,500 lb (9,300 kg))

### Service Ceiling (ft)

14700

### Military/Afterburner Speed (kt)

144

### Cruise Speed (kt)

118

### Supercruise

No

### Ferry Range (nm)

542 

### Takeoff / Landing Distance (m)

0

### Fuel Capacity (kg)

977 gallon 3,698 litre (Only information available)

### Sensors

This is largely speculation since I can't find any concrete data on the AS-61A-4s avionics in particular. It was used as transports by the Ejercito de Venezuela, so this is likely overkill. The AS-61A-4s were developed from 1975 and delivered in 1984 by Agusta, so this is a direct copy from its current DB entry.

[MM/APS-705 [Sea Spray Mk1]](https://www.cmano-db.com/sensor/1887/) - Radar
Radar, Surface Search, Medium-Range
Max Range: 148.2 km
Colibri [ELT 161, ESM] - (Farad) ESM 					ELINT Max Range: 926 km

### Mounts

None

### Loadout Options

26 troops, or 15 stretchers, or 12 VIP passengers

Search and Rescue

225 USG Drop Tank - 				 Drop Tank

### Comms/Datalinks

AKT-22 data link

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

4 ordered, 3 in inventory, one was lost in 2006 in a crash. 

A lot of the avionics as I've already mentioned is speculation. The AS-61A-4 were manufactured in 1975 by Augusta so I'm assuming the avionics stayed the same. The only role I can find for them is their usage as troop transports and SAR, so I'd assume that all ASW avionics and weapons would not be present. I did not include them here.

I also found no information on the communications aside from the data link which is used for sonar anyway.

### Sources

https://www.helis.com/database/model/838/
https://www.flightglobal.com/download?ac=75345
https://www.globalsecurity.org/military/world/venezuela/army-equipment.htm
https://aerocorner.com/aircraft/sikorskyAS-sh-3-sea-king/

**Comment by PygmalionOfCyprus** [comment]
Added, mostly. Marking closed.

I agree with your assessment that they probably didn't have sonar on this chopper, which appears to have been built specifically as a transport variant. Frankly, they probably didn't have the Sea Spray either, but I'm leaving it until we confirm otherwise.

Where are you seeing the 225 USG drop tank? (And was it 1 or 2? Usually I see drop tanks double-carried on helos.) I can't find anything in your sources and none of our other SH-3 loadouts have drop tanks. If I get confirmation I'll double back and add it; otherwise I've given it standard tankless SAR and troop transport loadouts.

**Comment by Echoblammo** [comment]
> Added, mostly. Marking closed.
> 
> I agree with your assessment that they probably didn't have sonar on this chopper, which appears to have been built specifically as a transport variant. Frankly, they probably didn't have the Sea Spray either, but I'm leaving it until we confirm otherwise.
> 
> Where are you seeing the 225 USG drop tank? (And was it 1 or 2? Usually I see drop tanks double-carried on helos.) I can't find anything in your sources and none of our other SH-3 loadouts have drop tanks. If I get confirmation I'll double back and add it; otherwise I've given it standard tankless SAR and troop transport loadouts.

Thanks for checking out my request. I found some additional details here that I must have missed, has details on endurance (3.5-5.5 hours) and avionics, as well as information stating that up to 3-tons can be externally loaded (3-ton sling-load loadout). Confirmation of all-weather (so I'm assuming night as well) operations, and specifics on radars.  

https://www.globalsecurity.org/military/systems/aircraft/h-3-specs.htm

I also recently found the holy grail: a flight manual. 
https://www.avialogs.com/aircraft-s/sikorsky/item/5146-4264sh-3hstandardaircraftcharacteristics-april1972

It may ask that you make a subscription, but I just did for free, and I never even needed a confirmation email. Virtually everything that you could possibly need is here, including electronics and details on fuel tanks. It does indeed have 2 forward droppable 220-gal Drop Tanks, straight from Sikorsky themselves.
