### ISSUE TITLE
Angola - Super Dvora Mk.III Patrol Boats, 2015

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#590]
### DB Selector

DB3K

### DBID to Copy

ship/500/DB3K

### Hypothetical

No

### Name

Dvora MkIII [Super Dvora MkII]

### Country

Angola

### Service

Navy

### In Commission

2015-Present

### Sensors

No Change Certain

### Mounts

No Change Certain

### Loadout Options

No Change Certain

### Other Changes

No Change Certain

### Sources

http://www.hisutton.com/Guide-To-Angolan-Navy.html
https://www.defenceweb.co.za/sea/sea-sea/angola-confirmed-as-super-dvora-mk-3-patrol-boat-customer/
https://www.bairdmaritime.com/work-boat-world/maritime-security-world/naval/ships-naval/angola-confirmed-as-customer-of-iai-patrol-boat-order/

**Comment by PygmalionOfCyprus** [comment]
Added 494.

**Comment by PygmalionOfCyprus** [comment]
And forgot to close.

**Comment by tbrandon517** [comment]
No worries. I didn't notice either.
