### ISSUE TITLE
Mistral 3 2015, MANPADS copy of #730 Mistral 2 2002, MANPADS

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#591]
### DB Selector

DB3K

### DBID to Copy

730

### Hypothetical

No

### Name

Mistral 3	(Comments = 2016, MANPADS)

### Country

France

### Service

Army

### In Commission

2015

### Sensors

Replace # 1528 by # 6483

### Other Changes

AirRangeMax to 4 nm (7 500 m)

### Sources

https://www.mbda-systems.com/product/mistral-manpads/
https://www.mbda-systems.com/?action=force-download-attachment&attachment_id=17900 (PDF Datasheet with AirRangeMax)

IOC 2015 : 
https://www.senat.fr/basile/visio.do?id=d153322-94728_23&idtable=d153322-94728_23&_c=missiles+Mistral&rch=ds&de=20150309&au=20220309&dp=1+an&radio=deau&aff=53322&tri=p&off=0&afd=ppr&afd=ppl&afd=pjl&afd=cvn#eltSign8
"La 850e et dernière munition rénovée a été livrée en novembre 2015"
http://www.strategic-bureau.com/mistral-f3-et-milan-pour-lestonie/

**Comment by Jkryos** [comment]
Added DB3K 494.
