### ISSUE TITLE
Please add Venezuelan Turbo Commander 980C (Navy)

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#592]
### DB Selector

DB3K

### Baseline

https://cmano-db.com/aircraft/4014/

### Hypothetical

No

### Name

Turbo Commander 980C (I don't know why its listed as the 980C, but several sources state this)

### Country

Venezuela

### Service

Navy

### In Commission

1986-

### Length (m)

13.10

### Wingspan (m)

15.89

### Height (m)

4.56

### Empty Weight (kg)

2845

### Maximum Takeoff Weight (MTOW) (kg)

4683

### Payload Weight (kg)

1861

### Crew

2

### Propulsion

2x Honeywell TPE331-511k 

### Rate of Climb (ft/min)

2777.78

### Service Ceiling (ft)

31000 (Highest listed)

### Military/Afterburner Speed (kt)

315

### Cruise Speed (kt)

306

### Supercruise

No

### Ferry Range (nm)

1800

### Takeoff / Landing Distance (m)

500 / 500

### Fuel Capacity (kg)

I actually can't find a single source that mentions fuel capacity. Shit.

### Sensors

Likely just 1x Generic Weather Radar

### Mounts

None

### Loadout Options

11x Passengers

### Comms/Datalinks

Unknown, Likely HF/VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Alternatively called Aerocommander 980 (695) Jetprop Commander.

Several sources list the Venezuelan model as the Turbo Commander 980C, but further research suggests that this might not be an actual airframe. I believe they may be referring to the Aero Commander 980, so that is the data I have entered here. A lot of details are sparse, but what I have comes straight from the source, so its pretty concrete.

### Sources

https://twincommander.com/models/ac980-695/
https://cloudflare-ipfs.com/ipfs/bafykbzaceboosmu6dr3mbynmxzfug7f6fus2qunjmdodklqwu7x6bqz3jcmw2?filename=International%20Institute%20for%20Strategic%20Studies%20-%20The%20Military%20Balance%202019-Routledge%20%282019%29.pdf
https://www.xairforces.net/army.asp?id=42
https://www.flightglobal.com/download?ac=75345
https://www.globalsecurity.org/military/world/venezuela/navy-equipment.htm
https://www.aeroflight.co.uk/waf/americas/venezuela/Navy/Venezuela-naf-AC980.htm
https://www.globalsecurity.org/military/systems/aircraft/jetprop-commander.htm

**Comment by Jkryos** [comment]
Added DB3K 494.
