### ISSUE TITLE
SAM Plt (Mistral III MANPADS x 3), copy of SAM Plt (Mistral II MANPADS x 3) (France - 2002) #58 (+Estonia, Serbia and Spain)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#593]
### DB Selector

DB3K

### DBID to Copy

58

### Hypothetical

No

### Name

SAM Plt (Mistral III MANPADS x 3)

### Country

France

### Service

Army

### In Commission

2015

### Mounts

Copy Mount # 762 Mistral II MANPADS
Name Mistral III MANPADS
Weapons, new Mistral 3 Manpads as created per suggested in issue #591

### Other Changes

**Estonia**
Please Copy SAM Plt (Mistral II MANPADS x 3) (Estonia - 2010) #1206, and name SAM Plt (Mistral III MANPADS x 3), then apply same modifications as suggested above.

**Serbia**
Please Copy such a new SAM Plt (Mistral III MANPADS x 3), then set its OperatorCountry to 2081 Serbia [1992-], Service to 2003 Army and YearCommissionned to 2019.

**Spain**
Please do the same for 2089 Spain, YearCommissionned to 221.

### Sources

**IOC 2015**
https://www.senat.fr/basile/visio.do?id=d153322-94728_23&idtable=d153322-94728_23&_c=missiles+Mistral&rch=ds&de=20150309&au=20220309&dp=1+an&radio=deau&aff=53322&tri=p&off=0&afd=ppr&afd=ppl&afd=pjl&afd=cvn#eltSign8
"La 850e et dernière munition rénovée a été livrée en novembre 2015"
http://www.strategic-bureau.com/mistral-f3-et-milan-pour-lestonie/
https://vm.ee/en/newsletter/estonian-defence-forces-receive-first-batch-mistral-m3-missiles

**Estonia**
https://vm.ee/en/newsletter/estonian-defence-forces-receive-first-batch-mistral-m3-missiles
http://www.strategic-bureau.com/mistral-f3-et-milan-pour-lestonie/

**Serbia**
https://www.mbda-systems.com/press-releases/serbia-signs-for-the-acquisition-of-mistral-3-short-range-air-defense-systems-with-mbda/

**Spain**
https://www.infodefensa.com/texto-diario/mostrar/3124445/mbda-entregara-espana-primeros-misiles-mistral-3-mismo-ano
https://www.infodefensa.com/texto-diario/mostrar/3123840/espana-comprara-100-misiles-mistral-3-francia-478-millones-euros

**Comment by Jkryos** [comment]
Added DB3K 494.

**Comment by claudejdev** [comment]
Follow-up on Spain :
102 launcher units updated, as Manpad or Atlas, 522 missiles bought in 2023, 94 bought in 2020. User: 71st Artillery Regiment.

MBDA claims a 95% probability of "success".
https://www.opex360.com/2023/09/26/lespagne-confirme-lachat-de-522-missiles-anti-aeriens-mistral-3-aupres-de-mbda/
