### ISSUE TITLE
#1847 - Blowpipe properties of Anti-Air Rear-Aspect is inaccurate as its command guided and could be fired at any aspect?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#594]
### DB Selector

Both

### Affected DBID(s)

#1847 - Blowpipe

### Summary of Changes

Property of "Anti-Air Rear-Aspect" is inaccurate as it should be an all aspect weapon.
As a radio command guided weapon the Blowpipe could be fired at any aspect of the target, if anything stern chasing would be a weaker aspect than a head on engagement.
Key weakness of Blowpipe was the amount of training and skill needed to use the joystick to keep it on target but its not dependant upon the aspect of the target. 
Target size and crossing speed are probably more important.

### Sources

DB3K
https://youtu.be/M78gadYbQNs?t=38 Engagement sequence and joystick. 
https://youtu.be/M78gadYbQNs?t=95 Head on engagement simulated from UK training video.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494 (in both DBs). 

As a related aside, Blowpipe cracks me up. 

> With the targets being fast-flying aircraft, flying low and using the ground to hide their approach, the Blowpipe operator had about 20 seconds to spot the target, align the unit and fire. Brigadier Julian Thompson compared using the weapon to "trying to shoot pheasants with a drainpipe". During the conflict, British forces fired 95 missiles, of which approximately half suffered failures of various kinds, and only 9 managed to destroy their targets and all of these were slow flying planes and helicopters. A later report determined that only one kill could be attributed with certainty to Blowpipe, that of an Argentine Navy Aermacchi MB-339 during the Battle of Goose Green on May 28.

What a stupid idea for a MANPADS.
