### ISSUE TITLE
#309 - EC.665 Tiger UHT (ASGARD) (Germany [FRG/Reunified] - 2012) would benefit from PARS-3LR ATGM load out please.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#595]
### DB Selector

DB3K

### User(s)

#309 - EC.665 Tiger UHT (ASGARD) (Germany [FRG/Reunified] - 2012) 

### Weapons Carried

#2231 - PARS-3LR [TRIGAT-LR] max of 8.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

130

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Can directly copy all existing HOT-3 load outs and use them as template for loads with PARS-3.
#19718 copy and replace to create 8 x PARS
#19722 copy and replace to create 4 x PARS and 20 x 12.7mm burst.
Etc,
Allegedly 680 were purchased/ordered in 2012?

### Sources

DB3K 492
https://www.bundeswehr.de/de/ausruestung-technik-bundeswehr/luftsysteme-bundeswehr/kampfhubschrauber-tiger
Bundesheer website.

**Comment by PygmalionOfCyprus** [comment]
Added 495.
