### ISSUE TITLE
GBU-50 Enhanced Paveway II GPS/LGB, copy of GBU-56 LJDAM (used by Bahrain, France, Singapore)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#596]
### DB Selector

DB3K

### DBID to Copy

3393 GBU-56(V)4/B LJDAM [BLU-109A/B], 3394 GBU-56(V)2/B LJDAM [Mk84]

### Hypothetical

No

### Name

GBU-50 Enhanced Paveway II GPS/LGB (See Other Changes)

### Country

nan

### Service

nan

### In Commission

2014

### Other Changes

Copy of 3393 GBU-56(V)4/B LJDAM [BLU-109A/B] would be named _GBU-50(V)2 Enhanced Paveway II GPS/LGB [BLU-109A/B]_

Copy of 3394 GBU-56(V)2/B LJDAM [Mk84] would be named _GBU-50(V)1 Enhanced Paveway II GPS/LGB [Mk84]_

### Sources

Although this is actually a modification of GBU-10, it seemed to me that it would be less tedious to copy GBU-56, from a database perspective.

> GBU-50 Enhanced Paveway II – Mk 84 or BLU-109 2,000 lb (907 kg) bomb. Raytheon’s Enhanced dual-mode GPS and Laser guided version of the laser-only GBU-10.
https://aoav.org.uk/2016/the-mark-80-series-and-paveway-attachments/
 

> The designation GBU-50/B covers Raytheon Enhanced Paveway II GPS/INS-equipped GBU-10/B variants, which are informally also known as EGBU-10.
 https://www.designation-systems.net/dusrm/app5/paveway-2.html
 
 IOC = 2014
Demo in 2014 by Raytheon and French Air Force, then ordered by Singapore Air Force

**France**
https://www.spacewar.com/reports/Raytheon_French_Air_Force_complete_Enhanced_Paveway_II_GBU_50_demonstration_999.html
https://theaviationist.com/2021/08/02/faf-mir2000-test-djibouti/
https://centraledesmarches.com/marches-publics/Paris-cedex-15-DGA-DO-S2A-Integration-des-munitions-GBU-48-et-GBU-50-sous-Mirage-2000D-et-augmentation-de-la-capacite-de-gestion-de-son-EPAK-de-2-a-4-munitions-EPWll-et-prestations-associees/3530918

**Bahrain**
https://www.federalregister.gov/documents/2017/09/27/2017-20707/arms-sales-notification
https://www.federalregister.gov/documents/2018/11/08/2018-24402/arms-sales-notification
https://www.federalregister.gov/documents/2019/06/17/2019-12662/arms-sales-notification

**Singapore**
https://www.federalregister.gov/documents/2014/01/21/2014-01062/36b1-arms-sales-notification

**Comment by PygmalionOfCyprus** [comment]
Added 494.
