### ISSUE TITLE
BGL-400 LGB, warhead and range correction

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#597]
### DB Selector

DB3K

### Affected DBID(s)

1909 - BGL-400 LGB -- 1986

### Summary of Changes

Please change : 
- its warhead to #693 - EU.3 452 kg GPB [203kg HE]
- its SurfRangeMax to 4.86 nm (9 km)
- Out of concern for detail, its Span to 0.79 m

### Sources

Jane's Air-Launched Weapons, Issue 40, 2002.
Liébert, M. Buyck, S. Le Mirage F1 Volume 2. Outreau, Lela Presse Aviation, 2007. Page 279.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
