### ISSUE TITLE
BGL-1000 Arcole LGB, warhead correction

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#598]
### DB Selector

DB3K

### Affected DBID(s)

1564 - BGL-1000 Arcole LGB -- 1993

### Summary of Changes

Please change its warhead to #694 - EU.4 1000kg GPB [550kg HE].
Out of concern for detail, its span is 0.9 m

### Sources

Jane's Air-Launched Weapons, Issue 40, 2002.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
