### ISSUE TITLE
TOS-1 MLRS

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#599]
### DB Selector

DB3K

### Hypothetical

No

### Name

Tos-1 MLRS

### Facility Type

Arty

### Country

Russia

### Service

Army

### In Commission

1988

### Crew

5

### Dispersion Radius (m)

40

### Sensors

Mk1 eyeball

### Mounts

6x Tos-1 MLRS (30 rockets per unit)

### Comments

Russian thermobaric MLRS system based on T72 chassis, 6km range. 30 rockets per unit.

### Sources

https://en.m.wikipedia.org/wiki/TOS-1

![Heavy_flamethrower_system__Solntsepyok__during_the__Armiya_2020__exhibition_(front_view)](https://user-images.githubusercontent.com/99824301/157563193-eab0cdaf-4bdb-4a27-9149-41b0e916275a.jpg)

**Comment by tbrandon517** [comment]
Additional sources for Russia, Azerbaijani, and Armenian TOS-1 and TOS-1A systems.

https://www.thedrive.com/the-war-zone/44479/the-truth-about-russias-terrifying-tos-1a-thermobaric-rocket-launchers-now-in-ukraine?fbclid=IwAR2x9VkhR-DXFIxcrBkfCvTMvYxS3l6GNPc1neDC4fgY8tqacuVtDVvU2w0
https://www.oryxspioenkop.com/2021/10/azerbaijans-emerging-arsenal-of.html
https://www.oryxspioenkop.com/2021/01/aftermath-lessons-of-nagorno-karabakh.html
https://www.oryxspioenkop.com/2020/09/the-fight-for-nagorno-karabakh.html

**Comment by Jkryos** [comment]
Added DB3K 494.
