### ISSUE TITLE
Please amend UK Apache AH-64E loadouts title and change in service date to 2022

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#6]
### DB Selector

DB3K

### Affected DBID(s)

4842 Apache Guardian AH.Mk.2 [AH-64E]  

### Summary of Changes

<type>AMMENDMENT</type>
<summary>#4842 - Apache Guardian AH.Mk.2 [AH-64E] (United Kingdom - 2023) Service Entry name and load outs are inaccurate!
</summary>
<detail>#4842 - Apache Guardian AH.Mk.2 [AH-64E] First air frame was delivered in November 2020 and began flight testing as of July 2021. In an entry level configuration it will be ready for service as of 2022 not 2023.

It is very unlikely to be called the Apache Guardian in UK service and all current official references are to the Apache AH-64E so likely to be AH.Mk.2 Apache [AH-64E].

There are no plans to integrate Brimstone (2) and the UK has placed substantial orders for AGM-114R and AGM-114-N4/P4 HELLFIRE and would use existing inventories.

Stinger ATAS is unlikely for the vast majority of missions and should be omitted. No sign of UK ever having anything but tiny stock of Stingers for SF use?

The UK does not use 2.75" Hydra rockets it has retained the CRV-7 and will continue to use these with AH-64E.
Weapons and load outs wise in the near term UK AH-64E will use the same AGM-114 CRV-7 combo's as the AH-64D

There is a possibility of JAGM in the mid term?

The 11 Jan 2022 article gives the impression the UK order of JAGM is in flux but still appears BRIMSTONE is NOT on the agenda due to integration costs. A case of Brimstone (2) being too expensive and not offering enough bang for the buck.
As an aside the term Brimstone 2 is a bit dated as MBDA don't make the original MM wave Brimstone anymore and production is now all the dual mode version trialled as Brimstone DMS and evolved into Brimstone 2, in production it is now just referred to as Brimstone.</detail>
<evidence>

</evidence>

Any how all a bit picky I know but its not as if the UK's primary attack helicopter shouldn't it be represented with some degree of precision.
For consideration anyway.

Thanks
K

< Message edited by KLAB -- 2/2/2022 4:46:48 PM >

### Sources

https://www.army.mod.uk/news-and-events/news/2020/11/new-apache-helicopter/ November 2020 arrival.
https://ukdefencejournal.org.uk/new-version-of-apache-attack-helicopter-enters-service/ 23 January 2022 in service.
https://www.army.mod.uk/equipment/aircraft/ Note refers to Apache AH-64E NOT Apache Guardian. In service as of 2022.
https://www.dsca.mil/press-media/major-arms-sales/united-kingdom-ah-64e-apache-guardian-attack-helicopters Full details of the order and equipment spares and EW kit.
https://www.dsca.mil/press-media/major-arms-sales/united-kingdom-hellfire-missiles-1 FOR 1k x AGM-114-R1/R2 Hellfire II
https://www.dsca.mil/press-media/major-arms-sales/united-kingdom-hellfire-missiles For 500 x AGM-114-N4/P4 HELLFIRE
https://www.janes.com/defence-news/news-detail/uk-signs-up-for-jagm-missile#:~:text=The%20United%20Kingdom%20has%20placed%20its%20first%20order,air-to-surface%20mission%20set%2C%20including%20the%20Apache%20attack%20helicopter. JAGM order.
https://ukdefencejournal.org.uk/uk-yet-to-purchase-jagm-missiles-for-apache-helicopters/ JAGM issues but only references to HELLFIRE NOT Brimstone!
https://www.dsca.mil/node/1379 Bought more AGM-114R2 in August 2020
https://www.mbda-systems.com/product/brimstone/ MBDA Page refers to just Brimstone but the dual seeker and spec relates to what is called Brimstone 2 in the DB3K.

**Comment by bostonmyk** [comment]
JAGM for Apache Links
https://www.janes.com/defence-news/news-detail/uk-selects-jagm-for-apache
https://ukdefencejournal.org.uk/uk-confirms-jagm-missile-for-ah-64e-apache-fleet/

**Comment by KLABDB3K** [comment]
https://www.army-technology.com/features/apache-jagm-uk
In a nutshell confirms JAGM over Brimstone as Apache weapon of choice.

**Comment by PygmalionOfCyprus** [comment]
Replaced current loadouts with versions of the AH-64D loadouts + variants using JAGM.
