### ISSUE TITLE
Seal Teams...

### ISSUE THREAD

**Issue by TWA517** [PygmalionOfCyprus/cmo-db-requests#600]
### DB Selector

DB3K

### User(s)

Cargo and Helos (anything used for deploying seal teams.....watch the show).

### Weapons Carried

Not weapon specific. Just adding Seal Teams to/for cargo planes such as but not limited to C-17's, C-130's, Helos for air-assault etc

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Aircraft range not effected

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Noted in the DB3k that Navy Seals have no load-outs for cargo aircraft such as C-17's, C-130's...
Rangers, Delta Force and paratroopers are set but not Seal Teams

How do we load them to aircraft for para-drops?
Could we also add a print feature to print outtakes from the DB and print maps. It is just too hard to keep things strait on screen. Even and export to Excel or the like would helpful.

Could we also add some drawing features to create and illustrate operational flow for land and air units.

Something to think about...

### Sources

Compared C-17 and C-130 loadouts...no Seal Teams available.

**Comment by PygmalionOfCyprus** [comment]
I know some of the aircraft currently have "SEAL Team" loadouts, but this is a slippery slope that will require a ton of work for basically no benefit.

We'll have a better solution for cargo in the future; until then, you should be able to load SEALs using standard cargo/personnel loadouts.

Questions and non-DB suggestions should be posted on the main CMO forums.

**Comment by TWA517** [comment]
With respect, how are seal team different than rangers, delta force or other special operators (aside from the obvious and various missions). In terms of benefit,  story telling is everything in relation to a good scenario or campaign. Anybody every heard of ARMA?
Special Ops is a major story telling device.

In terms of cargo it appears cargo is limited to supplies, ammo and all things in organic.  It just seems that seal teams were left out of the special operators loadouts for aviation assets. Please understand, I’m not complaining just trying to understand the context of CMO and how thing work together.
Please keep up the good work and we all look forward to all the roads yet taken.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by TWA517** [comment]
Thank you for your time…one last thing if a S/T’s are not a loadout for an aviation asset, and therefore cannot be deployed, how are the picked up?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by PygmalionOfCyprus** [comment]
I don't disagree at all. But by "slippery slope," I'm referring to the workload that would result if we take that to its logical conclusion. Yes, having a "SEAL Team" loadout as opposed to a generic "Personnel" loadout offers some immersion/storytelling capability. But are we to create separate loadouts for every single possible sub-group of people that could be loaded into an aircraft? I know there are currently separate loadouts for some special forces teams and certain aircraft in the DB. But to be honest, I'm not a fan of these; if I was building the DB from scratch, I wouldn't put them in. 

Under the hood, a "Seal Team" loadout is just a troops/personnel loadout with a different name, so you can use one of those in the interim. We're working on a much better, more comprehensive cargo system that will make this all moot, anyway.

As for the specifics of cargo ops, that's a bit of a complicated question: cargo is currently pretty esoteric and often abstracted / Lua supported in _Command_. Probably worth looking through some old threads on the forums or creating a new one for specific info.

**Comment by TWA517** [comment]
Very well, it is what it is. I did find Seal Team loadouts for the MH-60’s, those will (have to) do. Another thought was what happens when OPFOR uses special operators for strike or sabotage missions against BLUE bases of assets. This could be a double edge sword.
Good fortunes to future efforts, thankyou for allowing me to take your time.

tg

**Comment by PygmalionOfCyprus** [comment]
It's important to note that the functionality you're looking for is still there: the "SEAL Team" loadouts are a bit misleading because they don't actually facilitate the transportation of a "SEAL Team" any more than any other kind of cargo loadout. It's just for payload weight calculation.

You can still drop SEALs using Lua or standard cargo operations and conduct the missions / strikes you describe. :)

**Comment by TWA517** [comment]
Fair enough, I asked Paul G. If he would consider doing a tutorial on the matter. My only line of debarkation is…I WANT MY HALO JUMPS.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TWA517** [comment]
Considering all the other sub classes for other entries, and considering how the state of modern warfare is going, and how many countries are using special operators… would that not be worth considering for future changes (halo jumps not withstanding).

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by PygmalionOfCyprus** [comment]
As mentioned, we're working on some pretty significant adjustments to cargo that will make a lot of this discussion moot. 

The presence of "subclasses" is a symptom of the legacy system. They're virtually identical loadouts, with no in-sim difference. There is literally no difference between a "Delta Force Paras" loadout and a "Green Berets Paras" loadout except that one of them is called "Delta Force Paras" and the other is called "Green Berets Paras." You can load a SEAL team into them (or any other paradroppable cargo loadout for that matter) and toss them out the back same as anything else with a parachute.

As for the specifics of specops insertions, that isn't really a DB thing. You should probably make a request over on the main forums; I'd personally be interested in seeing a proposal for simulated paradrops, but this is tracker for DB issues and simulation requests are a different beast. 😛

**Comment by TWA517** [comment]
Understood and thanks, you been most helpful.
Have a good evening

Thx
tg

________________________________
