### ISSUE TITLE
Add: Leconi II class ship (LCU9), Gabon Navy

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#601]
### DB Selector

DB3K

### Baseline

#1336 (UK)

### Hypothetical

No

### Name

Landing Craft, L3015, Leconi II (LCU 9)

### Class

Leconi II (LCU 9)

### Country

Gabon

### Service

Navy

### In Commission

2010 - present

### Length (m)

25.7

### Beam (m)

6.5

### Draft (m)

1.7

### Standard Displacement (t)

75 (src1), 90 (src2)

### Full Displacement (t)

176 (src1), 160 (sr2)

### Complement

6

### Primary Propulsion Type

Diesel

### Propulsion

2 diesel, 2 waterjets

### Flank Speed (kt)

10

### Range (nm) at Speed (kt)

300 @ 9

### Sensors

1x Furuni I-band navigation radar

### Mounts

None

### Aircraft & Docking Facilities

1x small boat (image)

### Comments

Former RN LCM(9) craft, purchased by Irish merchant company and served as Island Harvester. 
Mil.lift: 2 tanks or 100t cargo

### Sources

1: JFS 2015 - 2016
2: https://www.navypedia.org/ships/gabon/gab_ls_leconi_ii.htm
![1](https://user-images.githubusercontent.com/99532490/157616395-985451f9-b3ca-4561-a3e1-4956dce2ed84.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
