### ISSUE TITLE
L-Cat [EDA-R], Egypt France, data correction

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#603]
### DB Selector

DB3K

### Affected DBID(s)

#2085 - L-Cat [EDA-R] (France - 2012), #3045 - L-Cat [EDA-R] (Egypt - 2018)

### Summary of Changes

- Height : 6.1m (does height have any impact ?)
- DisplacementEmpty : 185
- Crew : 6
- Cargo_Mass to 80
- Cargo_Area to 127
- Cargo_Crew to 42
- Properties : I would suggest adding #4002 All Aluminum Construction (-30% DP Penalty) and #4012 Catamaran/Trimaran Multihull (-30% DP Penalty), if that matter in any way
- Propulsion : Flank speed is 30 knots
- Fuel : 18.5 tons

### Sources

http://www.defense.gouv.fr/marine/equipements/batiments-de-combat/eda-r/eda-r
http://www.defense.gouv.fr/marine/magazine/eda-r-le-nouveau-moyen-de-connecter-la-mer-et-la-terre/fiche-technique
http://www.defense.gouv.fr/marine/magazine/eda-r-le-nouveau-moyen-de-connecter-la-mer-et-la-terre/l-eda-r-en-quelques-dates
https://cnim.com/sites/default/files/media/Publications/brochures%20pdf/L-CAT-shiptoshore-web-ppp.pdf
https://www.meretmarine.com/fr/content/le-premier-catamaran-de-debarquement-egyptien-rejoint-saint-nazaire
https://www.meretmarine.com/fr/content/eda-r-la-marine-francaise-dresse-un-premier-bilan-positif

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
