### ISSUE TITLE
EDA-S, new French landing craft; copy of #2085 - L-Cat [EDA-R] -- France (Navy), 2012

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#604]
### DB Selector

DB3K

### DBID to Copy

2085 - L-Cat [EDA-R] -- France (Navy), 2012

### Hypothetical

No

### Name

EDA-S

### Country

France

### Service

Navy

### In Commission

2021

### Other Changes

- Please input the modifications suggested in #603, _but the Properties_
- Comments 2x + 12x, Mistral
- Length: 29 m
- Beam: 6.7 m 
- Draft : 1.3 m
- Crew to 4
- Cargo_Crew to 80
- Propulsion : # 2935 2x Scania Marine DI16 076M Diesels

### Sources

https://cnim.com/sites/default/files/2019-01/CP%20-%20CNIM%20-%20EDAS%20Contrat%20Marine%20Nationale%2021012018.pdf
https://www.navalnews.com/naval-news/2021/11/first-two-eda-s-next-gen-amphibious-landing-crafts-delivered-to-french-dga/
https://www.janes.com/defence-news/news-detail/french-navy-eda-s-landing-craft-successfully-conclude-end-user-evaluations
https://www.meretmarine.com/fr/defense/le-dixmude-part-en-norvege-avec-un-edas
https://www.defense.gouv.fr/dga/actualite/les-nouvelles-embarcations-de-debarquement-amphibie-arrivent-dans-les-forces-armees-francaises

Various pics and vid, for further ref
https://twitter.com/MarineNationale/status/1463921636344795145
https://www.youtube.com/watch?v=Xvq_kMoF-P0

**Comment by Jkryos** [comment]
Added DB3K 494.
