### ISSUE TITLE
Czech Republic - UH-1Y Venom [Huey] - 2023

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#606]
### DB Selector

DB3K

### DBID to Copy

aircraft/2844/DB3K

### Hypothetical

No

### Name

UH-1Y Venom [Huey] - 2023

### Country

Czech Republic

### Service

Air Force

### In Commission

2023

### Sensors

Brite Star II infrared and electro-optical sensor turrets
AN/APR-38 radar warning receivers

### Mounts

AN/ALE-47s countermeasure (flare and chaff) dispensers

Can mount either M134 GAU-17 7.62mm mini-guns, M240 7.62mm machine guns, and M3M GAU-21 .50 caliber chain guns for door gunners.

### Loadout Options

No Known Changes

### Other Changes

helmet mounted displays

### Sources

https://verticalmag.com/news/czech-h-1-deal-will-keep-bells-production-line-open-at-least-through-2024/
https://en.wikipedia.org/wiki/Bell_UH-1Y_Venom#Operators
https://www.thedrive.com/the-war-zone/15467/latest-bell-uh-1y-venom-variant-of-the-iconic-huey-finds-an-export-customer
https://www.helis.com/database/news/czech-uh-1y-ah-1z-simulator/?noamp=1
https://www.dsca.mil/press-media/major-arms-sales/czech-republic-uh-1y-utility-helicopters
https://seapowermagazine.org/bell-begins-uh-1y-production-for-the-czech-republic/
https://www.shephardmedia.com/news/defence-helicopter/bell-starts-czech-republic-ah-1z-production/
https://www.defenseworld.net/news/31441/Bell_Kickstarts_Production_of_AH_1Z_Choppers_for_the_Czech_Republic#.YioPG4nMLrc
https://www.helis.com/database/modelorg/Czech-UH-1Y/

**Comment by Jkryos** [comment]
Added DB3K 494.
