### ISSUE TITLE
Czech Republic - AH-1Z Viper [Super Cobra] - 2023

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#607]
### DB Selector

DB3K

### DBID to Copy

aircraft/2843/DB3K

### Hypothetical

No

### Name

AH-1Z Viper [Super Cobra]

### Country

Czech Republic

### Service

Air Force

### In Commission

2023

### Sensors

No changes specified

### Mounts

No changes specified

### Loadout Options

No changes specified

### Other Changes

No changes specified

### Sources

https://www.helis.com/database/modelorg/Czech-AH-1Z/
https://www.defenseworld.net/news/31441/Bell_Kickstarts_Production_of_AH_1Z_Choppers_for_the_Czech_Republic#.YioPG4nMLrc
https://www.shephardmedia.com/news/defence-helicopter/bell-starts-czech-republic-ah-1z-production/
https://www.dsca.mil/press-media/major-arms-sales/czech-republic-ah-1z-attack-helicopters
https://seapowermagazine.org/bell-begins-uh-1y-production-for-the-czech-republic/
https://www.helis.com/database/news/czech-uh-1y-ah-1z-simulator/?noamp=1
https://verticalmag.com/news/czech-h-1-deal-will-keep-bells-production-line-open-at-least-through-2024/
https://en.wikipedia.org/wiki/Bell_AH-1Z_Viper

**Comment by tbrandon517** [comment]
Tagged as Hypothetical in error. Fixed.

**Comment by tbrandon517** [comment]
Looks like added for v496

**Comment by Jkryos** [comment]
Added DB3K 496.
