### ISSUE TITLE
Romania - SSM Bty (Naval Strike Missile (NSM)) - 2024

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#608]
### DB Selector

DB3K

### DBID to Copy

facility/2145/DB3K

### Hypothetical

No

### Name

SSM Bty (Naval Strike Missile (NSM))

### Country

Romania

### Service

Navy

### In Commission

2024

### Sensors

No change apparent from sources.

### Mounts

No change apparent from sources.

### Loadout Options

No change apparent from sources.

### Other Changes

No change apparent from sources.

### Sources

https://www.navalnews.com/naval-news/2021/05/romania-becomes-latest-naval-strike-missile-customer/?fbclid=IwAR2OKX2lOwGcJZoHZ6HLsSuhu818oKuEo3NRwDD3zADOscnYPSn8Ub_PjG0
https://www.defensenews.com/global/europe/2021/01/14/romanian-government-approves-naval-strike-missile-buy/
https://www.raytheonmissilesanddefense.com/news/2021/05/18/romania-becomes-latest-customer-for
https://www.dsca.mil/press-media/major-arms-sales/romania-naval-strike-missile-nsm-coastal-defense-systems
https://missilethreat.csis.org/romania-approves-antiship-missile-purchase/
https://defbrief.com/2021/04/29/romania-officially-signs-up-for-naval-strike-missile-systems/

**Comment by PygmalionOfCyprus** [comment]
Added 494.
