### ISSUE TITLE
Bangladesh - Mi-28NE Havoc - 2022/2023

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#609]
### DB Selector

DB3K

### DBID to Copy

aircraft/4583/DB3K

### Hypothetical

No

### Name

Mi-28NE Havoc

### Country

Bangladesh

### Service

Air Force

### In Commission

Planned for 2022 or 2023

### Sensors

No indicated changes

### Mounts

No indicated changes

### Loadout Options

No indicated changes

### Other Changes

No indicated changes

### Sources

https://www.scramble.nl/military-news/mi-28-attack-helicopters-for-bangladesh?fbclid=IwAR1HVPkPn2vnrArMpG_fGsC_x1OiEr8JSY7rSJvHt4wfiBlVc4NI4BDzfeg
https://frontierindia.com/bangladesh-to-buy-russian-mi-28ne-attack-helicopter-rejects-u-s-ah-64-apache/
https://en.wikipedia.org/wiki/Mil_Mi-28#Bangladesh
https://bonikbarta.net/home/news_description/284648/%E0%A6%B0%E0%A6%BE%E0%A6%B6%E0%A6%BF%E0%A7%9F%E0%A6%BE-%E0%A6%A5%E0%A7%87%E0%A6%95%E0%A7%87-%E0%A6%95%E0%A7%87%E0%A6%A8%E0%A6%BE-%E0%A6%B9%E0%A6%9A%E0%A7%8D%E0%A6%9B%E0%A7%87-%E0%A7%AE%E0%A6%9F%E0%A6%BF-%E0%A6%85%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%9F%E0%A6%BE%E0%A6%95-%E0%A6%B9%E0%A7%87%E0%A6%B2%E0%A6%BF%E0%A6%95%E0%A6%AA%E0%A7%8D%E0%A6%9F%E0%A6%BE%E0%A6%B0-

**Comment by KLABDB3K** [comment]
https://www.airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/march/8264-bangladesh-may-abandon-the-acquisition-of-russian-aircraft-in-favor-of-european-ones.html

Watch this space, anything not set in stone is going to risk being hit with sanctions.

**Comment by PygmalionOfCyprus** [comment]
Added 494 as hypothetical.
