### ISSUE TITLE
Belgium - F-35A Lightning II - 2025, 34x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#610]
### DB Selector

DB3K

### DBID to Copy

aircraft/3902/DB3K

### Hypothetical

No

### Name

F-35A Lightning II - 2020

### Country

Belgium

### Service

Air Force

### In Commission

2025

### Sensors

No Change Specified

### Mounts

No Change Specified

### Loadout Options

B61 for NATO nuclear sharing indicated as probable.

### Other Changes

No Change Specified

### Sources

https://en.wikipedia.org/wiki/Lockheed_Martin_F-35_Lightning_II#Operators
https://www.defensenews.com/air/2018/10/25/f-35-officially-wins-belgian-fighter-contest/
https://www.f35.com/f35/global-enterprise/belgium.html#:~:text=The%20F%2D35%20for%20Belgium,and%20Belgian%20government%20and%20industry.
https://www.lockheedmartin.com/en-us/products/f-35/f-35-global-partnership/f-35-belgium.html
https://www.nieuwsblad.be/cnt/dmf20190708_04499594
https://www.reuters.com/article/us-aerospace-belgium/belgium-picks-lockheeds-f-35-over-eurofighter-on-price-idUSKCN1MZ1S0
https://www.thedrive.com/the-war-zone/24465/belgium-decides-to-join-the-f-35-club-over-competing-offers-for-european-fighter-jets

**Comment by claudejdev** [comment]
IOC would actually be **2025**.
The platforms that are planned to be delivered in 2023 will remain in the U.S. to train the pilots and technicians.

https://www.mil.be/fr/l-evolution-de-la-defense/lockheed-martin-f-35a-lightning-ii-le-nouveau-frontline-fighter-de-la-composante-air/

**Comment by tbrandon517** [comment]
> IOC would actually be **2025**. The platforms that are planned to be delivered in 2023 will remain in the U.S. to train the pilots and technicians.
> 
> https://www.mil.be/fr/l-evolution-de-la-defense/lockheed-martin-f-35a-lightning-ii-le-nouveau-frontline-fighter-de-la-composante-air/

Updated Request Data

**Comment by PygmalionOfCyprus** [comment]
Added 494.
