### ISSUE TITLE
Iran - AB.206A1 Jet Ranger - ~1975

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#612]
### DB Selector

DB3K

### DBID to Copy

aircraft/5051/DB3K

### Hypothetical

No

### Name

AB.206A1 Jet Ranger

### Country

Iran

### Service

Army, Air Force

### In Commission

~ 1975-Present

### Sensors

No Changes

### Mounts

No Changes

### Loadout Options

Add

1x - Nasr-1 (C-704) - Naval Strike

### Other Changes

For CWDB and DB3k, ASM loadout for DB3K

### Sources

https://www.thedrive.com/the-war-zone/40348/irans-used-its-wacky-catamaran-to-cut-off-u-s-coast-guard-ships-in-the-persian-gulf?fbclid=IwAR0uqF2jp9hZOkYuJQFHKuA0kRnz5CTcrVxlKkzRHkR9XR30m0ItXb3De-g
https://img.en25.com/Web/flightglobal/%7B88f2f053-6c3d-4ab4-a297-0b453358a560%7D_FC055_PREM_201312.pdf?elq=&elqCampaignId=
https://en.wikipedia.org/wiki/Bell_206#Variants
https://en.wikipedia.org/wiki/Nasr-1
https://www.thedrive.com/the-war-zone/35150/iran-fires-missiles-at-its-fake-carrier-says-its-satellite-has-been-watching-from-above
https://www.timesaerospace.aero/features/irans-helicopter-options
https://twitter.com/josephhdempsey/status/1288159654279880708

![image](https://user-images.githubusercontent.com/99599482/157707861-c0ab23ad-ad89-432c-a8e9-9e4bd0660e82.png)

**Comment by Jkryos** [comment]
Added DB3K and CWDB 494.
