### ISSUE TITLE
Italy - S 526 Salvatore Todaro [Type 212A] - 2016, DDS

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#614]
### DB Selector

DB3K

### Affected DBID(s)

submarine/218/DB3K

### Summary of Changes

Italian type 212 submarines first seen in 2016 with COMSUBIN DDS installed.

### Sources

http://www.hisutton.com/COMSUBIN_Container.html

![image](https://user-images.githubusercontent.com/99599482/157710294-3f27c2d1-79fb-4a71-84bf-a946df3d18fc.png)
![image](https://user-images.githubusercontent.com/99599482/157710334-d3ee8cf9-1a65-4947-8202-6d6485ec360c.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
