### ISSUE TITLE
MOZAMBIQUE - RT Yevgenya [Pr.1258] - 1986

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#615]
### DB Selector

DB3K

### DBID to Copy

ship/2918/DB3K

### Hypothetical

No

### Name

RT Yevgenya [Pr.1258] - 1986

### Country

Mozambique

### Service

Navy

### In Commission

1986-1993

### Mounts

1 x 2 - 25mm/82 2M-3M, 
1 x 7 - 55mm MRG-1 AGL
Same Depth Charges

### Loadout Options

No Chnage

### Other Changes

None Stated

### Sources

https://www.navypedia.org/ships/mozambique/moz_ms_1258e.htm
https://en.wikipedia.org/wiki/MRG-1

**Comment by PygmalionOfCyprus** [comment]
Added 494. Left off the anti-diver munitions since that's a bit out of scope.
