### ISSUE TITLE
Mozambique - Ocean Eagle 43 - 2016, Patrol Boat, 3x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#618]
### DB Selector

DB3K

### DBID to Copy

ship/3203/DB3K

### Hypothetical

No

### Name

Ocean Eagle 43 - 2016, Patrol Boat

### Country

Mozambique

### Service

Navy

### In Commission

2016-Present

### Sensors

No Known Change

### Mounts

Improvised anti-aircraft gun mount on the center of the helideck of at least 1 unit, Type unclear possibly a ZU-23_2. Position renders helipad unusable.

### Loadout Options

No Known Change

### Other Changes

No Known Change

### Sources

http://www.hisutton.com/Guide-To-Mozambique-Navy.html
https://www.navypedia.org/ships/mozambique/moz_cf_eagle_43.htm
https://en.wikipedia.org/wiki/Mozambique_Defence_Armed_Forces#Navy
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/year-2014-news/september-2014-navy-naval-forces-maritime-industry-technology-security-global-news/1991-first-ocean-eagle-43-trimaran-patrol-vessel-hull-for-mozambique-delivered-to-cmn.html
https://www.defenceweb.co.za/sea/sea-sea/cmn-launches-mozambiques-first-ocean-eagle-patrol-vessel/
https://www.globalsecurity.org/military/world/europe/cmn-ocean-eagle-43.htm
https://www.cmn-group.com/vessel/ocean-eagle-43/
https://www.homelandsecurity-technology.com/projects/ocean-eagle-43-trimaran-ocean-patrol-vessel/
https://www.naval-technology.com/projects/ocean-eagle-43-trimaran-maritime-surveillance-vessel/
https://www.military.africa/2021/08/mozambique-navy-all-you-need-to-know

![image](https://user-images.githubusercontent.com/99599482/157727000-2b289318-268a-40d2-9eed-bb5d5015d5e3.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494 in helipad-gun and non-helipad-gun variants.
