### ISSUE TITLE
30mm DEFA 553 Gun Pod Burst [250 rnds], copy of #2781 - 20mm/85 SUU-23/A Gun Pod Burst [100 rnds]

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#619]
### DB Selector

DB3K

### DBID to Copy

2781

### Hypothetical

No

### Name

30mm DEFA 553 Gun Pod Burst [250 rnds]

### Country

France

### Service

Air Force

### In Commission

2021

### Other Changes

- Please create a new warhead, '30mm Burst [250 rnds], by copying #1105 - '30mm Burst [200 rnds]'.
- Replace the warhead #930 - 20mm Burst [100 rnds] (1 DP) with that new '30mm Burst [250 rnds]'.
 
If that's of any use : 

- length = 4.42 m
- diameter = 0.46 m
- weight = 350 kg

### Sources

https://theaviationist.com/2021/08/02/faf-mir2000-test-djibouti/
https://www.meta-defense.fr/en/2020/03/02/dassault-aviation-would-have-finished-testing-the-canon-cc-422-pod-for-modernized-mirage-2000d/
http://www.opex360.com/2020/03/01/destinee-au-mirage-2000d-la-nacelle-canon-cc422-a-passe-ses-derniers-essais-avec-succes/

Liébert, M. Buyck, S. Le Mirage F1 Volume 2. Outreau, Lela Presse Aviation, 2007. Page 274.

**Comment by PygmalionOfCyprus** [comment]
Added 494.
