### ISSUE TITLE
Mozambique - WP18 interceptor launches (2016) 3x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#621]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

WP18 interceptor launches (2016)

### Class

WP18 interceptor launches (2016)

### Country

Mozambique

### Service

Navy

### In Commission

2016-Present

### Length (m)

18.6

### Beam (m)

3.5

### Draft (m)

0.8

### Standard Displacement (t)

13

### Full Displacement (t)

not stated

### Empty Displacement (t)

not stated

### Complement

3

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

2 Seatek V12 diesels

### Fuel Capacity (kg)

3200

### Flank Speed (kt)

65

### Range (nm) at Speed (kt)

400nm @ 47

### Sensors

1x Generic Navigation Radar

### Mounts

small arms only for Mozambique

Design is capable of pop-up remote weapons station, soft kill systems and missiles.

### Aircraft & Docking Facilities

None

### Comms/Datalinks

VHF/UHF Radio

### Comments

With its sleek wave-piercing hull and stealthy lines, the blisteringly quick WP-18 is the fastest naval vessel in the world. Its 'Tactical Strike Craft' role would see it interdicting illegal vessels. The high speed allows it to react quickly to developing circumstances. Inside the fully-enclosed composite exterior is a highly automated cockpit meaning minimal crewing. The trade-off is that it cannot be used for boarding and utility tasks.

### Sources

http://www.hisutton.com/Guide-To-Mozambique-Navy.html
http://www.hisutton.com/WP-18%20Tactical%20Strike%20Craft.html
https://www.navypedia.org/ships/mozambique/moz_cf_wp18.htm
http://www.hisutton.com/New%20video%20of%20WP-18%20stealth%20Special%20Forces%20boat.html
https://www.military.africa/2021/08/mozambique-navy-all-you-need-to-know
https://www.privinvest.com/naval-vessels/interceptor-wp18/
https://sofrep.com/news/worlds-fastest-naval-vessel-wp-18-special-forces-interceptor/

![image](https://user-images.githubusercontent.com/99599482/157731927-e55789a2-fbd9-4e22-92e4-5643d79b14e7.png)
![image](https://user-images.githubusercontent.com/99599482/157731946-09258450-a191-4e88-ad28-d65c85755d54.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
