### ISSUE TITLE
Unmanned platforms which have a crew.

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#622]
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

Please the crew value to 0 for these platforms :

**Aircraft**

- 5435 J-6 Farmer [MiG-19S Copy] UAV
- 5424 P.1HH Hammerhead UCAV
- 5425 P.1HH Hammerhead UCAV

**Ships**

- 2455 Protector USV [Typhoon, Armed]
- 2456 Protector USV [Typhoon, Armed]
- 2699 Fleet Class CUSV [Empty Mission Module]
- 2731 Fleet Class CUSV [MCM Mission Module]
- 3104 Sea Hunter [ACTUV]
- 3142 Seagull USV [MCM Mission Module]

The reasoning here is especially to not encounter odd situation in scenarios with crew ejection and SAR features.

### Sources

It seems there ain't any Passenger drone around nowadays.
https://en.wikipedia.org/wiki/Passenger_drone

;)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
