### ISSUE TITLE
Mozambique - pr. 1400ME patrol boats (1979)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#625]
### DB Selector

DB3K

### DBID to Copy

ship/2858/DB3K

### Hypothetical

No

### Name

pr. 1400ME patrol boats

### Country

Mozambique

### Service

Navy

### In Commission

1979-1998

### Sensors

1x Lotsiya radar

### Mounts

2 x 2 - 12.7mm/79

### Loadout Options

Not Stated

### Other Changes

For CWDB as well.

### Sources

https://www.navypedia.org/ships/mozambique/moz_cf_1400me.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
