### ISSUE TITLE
Armed Surface Combatant unmanned platform with Civilian type

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#627]
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

Please change the following ship's category to #3308 USV - Unmanned Surface Vess

- 2455 Protector USV [Typhoon, Armed]
- 2456 Protector USV [Typhoon, Armed]
- 2699 Fleet Class CUSV [Empty Mission Module]
- 2731 Fleet Class CUSV [MCM Mission Module]
- 3142 Seagull USV [MCM Mission Module]

The reasoning here is that modification may prevent in game confusion, such with unit type trigger.

### Sources

42

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.

Pretty bold of you to cite the meaning of life, the universe, and everything as a source. But I'll allow it. 😉
