### ISSUE TITLE
AN/ALQ-225 radio frequency countermeasure (RFCM) system for AC-130J

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#630]
### DB Selector

DB3K

### Baseline

#3173 AC-130J Ghostrider

### Hypothetical

No

### Name

AN/ALQ-225

### Sensor Generation

Early 2020s

### Sensor Capabilities

Heading Information

### Search/Track Frequencies

C Band (500-1000 MHz) [Old L Band (UHF)] 60-30cm, D Band (1-2 GHz) [Old L Band] 15-30 cm, E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm, G Band (4-6 GHz) [Old C Band] 5-7.5 cm, H Band (6-8 GHz) [Old C Band] 3.75-5 cm, I Band (8-10 GHz) [Old X Band] 3-3.75 cm, J Band (10-20 GHz) [Old X Band] 1.5-3 cm, K Band (20-40 GHz) [Old Ku Band] 0.75-1.5 cm

### Lower Frequency (Hz)

Possible C band

### Upper Frequency (Hz)

Possible K band

### Sources

https://news.northropgrumman.com/news/releases/northrop-grumman-delivers-radio-frequency-countermeasures-system-to-us-special-operations-command?utm_source=Twitter&utm_medium=Image&utm_content=radio&utm_campaign=radio&Code=SNS-13493

https://militaryleak.com/2022/03/04/northrop-grumman-delivers-alq-251-radio-frequency-countermeasures-system-to-us-special-operations-command/

https://www.janes.com/defence-news/news-detail/first-rfcm-fit-completed-for-ac-130j-ghostrider

**Comment by PygmalionOfCyprus** [comment]
Assume you meant the ALQ-251 as mentioned in your sources. Added 494.
