### ISSUE TITLE
Mozambique - pr. 201M patrol craft (1985)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#632]
### DB Selector

DB3K

### DBID to Copy

ship/2205/DB3K

### Hypothetical

No

### Name

pr. 201M patrol craft (1985)

### Country

Mozambique

### Service

Navy

### In Commission

1985-1993

### Sensors

No Change

### Mounts

No Change

### Loadout Options

No Change

### Other Changes

No Change

### Sources

https://www.navypedia.org/ships/mozambique/moz_cf_201.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
