### ISSUE TITLE
Mozambique - Namacurra-class patrol boats - 2004, 2x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#634]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

Namacurra-class patrol boats

### Class

Namacurra-class patrol boats

### Country

Mozambique

### Service

Navy

### In Commission

2004-Present

### Length (m)

9.5

### Beam (m)

2.5

### Draft (m)

<1

### Standard Displacement (t)

4

### Full Displacement (t)

5.2

### Empty Displacement (t)

Not Stated

### Complement

5

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 x 140Kw BMW marine petrol engines

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

Not Stated

### Sensors

1x Surface search: Racal Decca; I-band

### Mounts

1x12.7mm Browning Machine Gun
2x7.62mm LMG
Small Arms

### Aircraft & Docking Facilities

None

### Comms/Datalinks

VHF/UHF Radio

### Comments

South Africa donated two Namacurra class harbour patrol boats to the Mozambique Navy. The Namacurra class harbour boats is an Inshore Patrol vessel built by Tornado Products and Stellenbosch.

### Sources

https://www.military.africa/2021/08/mozambique-navy-all-you-need-to-know
https://en.wikipedia.org/wiki/Mozambique_Defence_Armed_Forces#Navy
https://en.wikipedia.org/wiki/Namacurra-class_patrol_boat

![image](https://user-images.githubusercontent.com/99599482/157748843-978afc57-8204-48df-af84-213ec7951ace.png)
![image](https://user-images.githubusercontent.com/99599482/157748963-734fae8e-f584-4e97-8ee3-0b2d4b272e55.png)

**Comment by Jkryos** [comment]
Added DB3K 496.
