### ISSUE TITLE
Ghana - GNS Volta (Flex Fighter class) - 2022

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#639]
### DB Selector

DB3K

### Baseline

Unknown

### Hypothetical

No

### Name

GNS Volta

### Class

Flex Fighter

### Country

Ghana

### Service

Navy

### In Commission

2022

### Length (m)

40

### Beam (m)

7.6

### Draft (m)

1.89

### Standard Displacement (t)

not stated

### Full Displacement (t)

not stated

### Complement

12

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

three Caterpillar C32 main engines

### Fuel Capacity (kg)

86,000

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

2923nm @ 26 kts

### Sensors

GMDSS - Sea Area A1+A2
BNWAS - LeGuardian2025
Marine Radar - HALO-6
Depth / Echo Sounder - SonarHub
Search Lights - 3 x 1000W
Night Vision Camera - FLIR V5035

### Mounts

HMG Mounts with Ballistic Shields (1 x forward and 2 x aft)

### Aircraft & Docking Facilities

Not Stated

### Comms/Datalinks

VHF	- Sailor 6222
MF/HF Radio - Sailor 6310

### Ship Codes

All Aluminum Construction

### Comments

54 PAX Capacity
93-sqm cargo deck, 60 MT cargo capacity

### Sources

http://www.penguin.com.sg/vessel-specs/flex-fighter/
https://www.janes.com/defence-news/news-detail/ghana-to-receive-flex-fighter-security-vessels
https://www.defenceweb.co.za/featured/ghana-receives-flex-fighter-vessels/
https://militaryleak.com/2022/01/09/ghana-navy-takes-delivery-of-singapore-shipyard-penguin-international-flex-fighter-boats/
https://www.shephardmedia.com/news/naval-warfare/flex-fighters-enhance-ghanaian-offshore-security/
https://globalupfront.com/2022/01/11/ghanaian-navy-receives-4-new-flex-fighter-vessels/
https://www.businessghana.com/site/news/general/253839/4-Fighter-vessels-acquired-for-the-Navy
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/january/11229-navy-of-ghana-acquires-four-flex-fighter-security-vessels-from-penguin-compnay-of-singapore.html?fbclid=IwAR1YlDVoj7uCd1D8YJb6q4TnOiYuWh-HVikJ8WCUwzQ3VWErwBeMpwzA7wI

![image](https://user-images.githubusercontent.com/99599482/157762351-ae049227-5372-4053-a1d4-25aca08d5d95.png)
![image](https://user-images.githubusercontent.com/99599482/157762121-cbb7e2c8-9478-436f-8f4e-42bf6bb62064.png)

**Comment by PygmalionOfCyprus** [comment]
Aha, already added in DB 493 as part of a news roundup! Always nice when I get out in front of something for a change. 😛
