### ISSUE TITLE
Israel - Dolphin/Dolphin II DDS

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#640]
### DB Selector

DB3K

### Affected DBID(s)

submarine/421/DB3k & submarine/584/DB3K

### Summary of Changes

Israeli Dolphin class submarines sighted with DDS shelter in 2020. Dolphin II likely has the same capability

### Sources

http://www.hisutton.com/Israeli-Navy-Dolphin-Class-Submarine-with-Special-Forces-Hangar.html?fbclid=IwAR3Bklrao_ZlxankKLLsyE-IPSJM7hvmiTXpWlk2l9uFZI84SY9U5dJmsA4

![image](https://user-images.githubusercontent.com/99599482/157767029-771bfd00-58f5-420a-a71e-7e34045d89a3.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
