### ISSUE TITLE
'Mirage 2000D RMV' (MLU), copy of 'Mirage 2000D R2.1' (France)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#641]
### DB Selector

DB3K

### DBID to Copy

3931 'Mirage 2000D R2.1'

### Hypothetical

No

### Name

Mirage 2000D RMV

### Country

France

### Service

Air Force

### In Commission

2022-2035

### Mounts

**Add**

- issue #619 30mm DEFA 553 Gun Pod Burst [250 rnds]
- issue #596 GBU-50 Enhanced Paveway II GPS/LGB
- ID 1873 - MICA IR
- ID 3149 - Talios LDP-NG Pod [FLIR + LRMTS, 40k ft]

_Remove_
- ID 1771 - Atlis II Pod [EO + LRMTS, 12k ft]
- ID 898 - PDLCT Pod [FLIR + LRMTS, 12k ft]
- ID 479 - Damocles LDP Pod [FLIR + LRMTS, 40k ft]
- ID 871 - GBU-24A/B Paveway III LGB [BLU-109/B]
- ID 242 - R.550 Magic 2 Mk2

### Loadout Options

- [x] Assign following loadouts as is
- ID 3(Reserve [Available])
- ID 4 (Maintenance [Unavailable])
- ID 2454 (Ferry)
- ID 14128 ASTAC Pod [ESM]

- [x] Copy following loadouts, and in each, replace weapon ID 242 - R.550 Magic 2 Mk2 by weapon ID 1873 - MICA IR
- ID 951 Apache
- ID 6201 SCALP EG
- ID 19740 Mk82 500lb LDGP

- [x] Copy following loadouts, and in each, replace weapon ID 242 - R.550 Magic 2 Mk2 by weapon ID 1873 - MICA IR, and replace weapon ID 898 - PDLCT Pod [FLIR + LRMTS, 12k ft] by ID 3149 - Talios LDP-NG Pod [FLIR + LRMTS, 40k ft]
- ID 1278 GBU-12D/B LGB [Mk82], PDLCT Pod [FLIR]
- ID 2137 GBU-22/B LGB [Mk82], PDLCT Pod [FLIR]
- ID 10150 GBU-49/B GPS/LGB [Mk82], PDLCT Pod [FLIR]
- ID 19739 Mk82 500lb LDGP, PDLCT Pod [FLIR]
 

- [x] Copy that new loadout GBU-49/B GPS/LGB [Mk82], Talios LDP-NG Pod [FLIR] 
- add 2x #1814 - Mk82 500lb LDGP
- add 1x issue #619 30mm DEFA 553 Gun Pod Burst [250 rnds]
(it's a new "Close Air Support" loadout which have been tested out in July 21 at Djibouti)

- [x] Copy loadout ID 14366 GBU-24A/B LGB [BLU-109/B], PDLCT Pod [FLIR] 
- replace weapon ID 242 - R.550 Magic 2 Mk2 by weapon ID 1873 - MICA IR
- replace weapon ID 898 - PDLCT Pod [FLIR + LRMTS, 12k ft] by ID 3149 - Talios LDP-NG Pod [FLIR + LRMTS, 40k ft]
- replace weapon ID 14366 GBU-24A/B LGB [BLU-109/B]] by the new GBU-50(V)2 Enhanced Paveway II GPS/LGB [BLU-109A/B] from issue #596.

- [x] Copy that new loadout GBU-50(V)2 Enhanced Paveway II GPS/LGB [BLU-109A/B, Talios LDP-NG Pod [FLIR] 
- replace weapon GBU-50(V)**2** Enhanced Paveway II GPS/LGB [BLU-109A/B] from issue #596 by GBU-50(V)**1** Enhanced Paveway II GPS/LGB [Mk84] from issue #596.

- [x] Copy that new loadout GBU-50(V)**1** Enhanced Paveway II GPS/LGB [Mk84], Talios LDP-NG Pod [FLIR] 
- add 1x ID 1906 - GBU-12D/B Paveway II LGB [Mk82]
(it's a new "Air Interdiction" loadout which have been tested out in July 21 at Djibouti)

---

I would suggest _NOT_ to copy these loadouts (their designation pods are being phased out and will all be replaced by the Talios LDP-NG Pod quite soon-ish : AtlisII Pod and PDLCT Pod won't be maintained in operational condition beyond 2022, while the Damocles LDP Pod won't be maintained in operational condition beyond 2023 )

> ID 19733 GBU-12D/B LGB [Mk82], Atlis II Pod [EO]
> ID 19734 GBU-49/B GPS/LGB [Mk82], Atlis II Pod [EO]
> ID 19735 GBU-12D/B LGB [Mk82], Damocles LDP Pod [FLIR]
> ID 19736 GBU-49/B GPS/LGB [Mk82], Damocles LDP Pod [FLIR]
> ID 19737 Mk82 500lb LDGP, Damocles LDP Pod [FLIR]
> ID 19738 Mk82 500lb LDGP, Atlis II Pod [EO]

### Other Changes

-  WeightMax to 17500
-  WeightPayload to 7300

Comments to x55

**Notes**
 RMV, 'Rénovation Mi-Vie' litteraly means Mid-Lif Update. I would still keep it named RMV to have a French touch to it.

### Sources

Lert, Frédéric. "Le Mirage 2000D fait sa révolution", Avions de Combat, issue 21, December 2021, pg. 10-20
Roublot, Michel. "Rénovation à mi-vie du Mirage 2000D", Aviation News issue 76, February 2022, pg. 6-8.
https://fr.calameo.com/read/006376944b0aaefc5977e

http://www.senat.fr/rap/a18-149-8/a18-149-811.html
https://air.defense.gouv.fr/armee-de-lair-et-de-lespace/fiche/109
https://air.defense.gouv.fr/armee-de-lair-et-de-lespace/actualite/168
https://defense-militaire.over-blog.com/2020/10/la-renovation-a-mi-vie-des-mirage-2000-d-va-permettre-leur-emploi-en-complement-des-rafale-jusqu-au-dela-de-2030.html

_Image_
https://www.defense.gouv.fr/var/dicod/storage/images/base-de-medias/images/air/actualites/images-2021/juillet-2021/campagne-temps-chaud-djibouti-10/10359093-1-fre-FR/campagne-temps-chaud-djibouti-10.jpg

https://www.defense.gouv.fr/var/dicod/storage/images/base-de-medias/images/air/actualites/images-2021/images-janvier-2021/m2000d_10/10153500-1-fre-FR/m2000d_10.jpg

**Comment by PygmalionOfCyprus** [comment]
I just wanna drop in and say this is such a beautiful report it brings tears to my eyes. DBIDs...task lists...great job. 🥲

**Comment by PygmalionOfCyprus** [comment]
All done, just one question before closing: how many bursts of the "30mm DEFA 553 Gun Pod Burst [250 rnds]" should I put in the loadout? Or, in other words, what's the total capacity of a 553 pod?

**Comment by claudejdev** [comment]
> All done, just one question before closing: how many bursts of the "30mm DEFA 553 Gun Pod Burst [250 rnds]" should I put in the loadout? Or, in other words, what's the total capacity of a 553 pod?

Oh, sorry, I really need to check my notification settings.

The capacity is 250 rounds.

(Some source says it's 180, however that is with links and cases collector installed. In which case, the pod weights 317 Kg.)

**Comment by PygmalionOfCyprus** [comment]
In that case, it would probably be better for me to make it a 50-round burst and give it 5 "shots" of that so that the unit can attack more than once with its gun. Any objection?

**Comment by claudejdev** [comment]
> In that case, it would probably be better for me to make it a 50-round burst and give it 5 "shots" of that so that the unit can attack more than once with its gun. Any objection?

It makes sense, no objection here. :)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
