### ISSUE TITLE
Tender 404 wrong armament/mount/fuel capacity

### ISSUE THREAD

**Issue by CasualGerman** [PygmalionOfCyprus/cmo-db-requests#643]
### DB Selector

DB3K

### Affected DBID(s)

1270

### Summary of Changes

The Tender 404 class still has the Armament and sensor suit from the 90's the Tender are now equipt with the MLG 27 and the MSP 500, also 3 of the 6 Tenders already have a new boats davit and now carry the FRB (Zodiac Milpro Gecko). It also carries 780 tonnes of fuel and in real life its classified as a replenishment ship not repair

### Sources

https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Autocannon_MLG27.jpg/1280px-Autocannon_MLG27.jpg
https://www.instagram.com/p/CQGDYcfMc0b/?utm_source=ig_web_copy_link
https://www.bundeswehr.de/resource/image/5084968/landscape_ratio16x9/2000/1125/e5524540ac6710d0a6a597562b63c381/65E64801C06C23B3BA5F7F269C469485/tender-donau-transporthubschrauber.jpg (MSP 500 is visible over the bridge)
https://www.bundeswehr.de/de/ausruestung-technik-bundeswehr/seesysteme-bundeswehr/elbe-klasse-404 (even the Bundeswehr site is out of date)
https://esut.de/2020/02/meldungen/streitkraefte/18613/marine-bereitschaftsboote-gecko-werden-ausgeliefert/
Myself (i am stationed on one)

**Comment by PygmalionOfCyprus** [comment]
Do we know when (what year) the MLG-27s replaced the Rh202s? Likewise with installation of the MSP-500, if that didn't occur at the same time.

Also, are those new boat davits expected to go to all ships of the class, or are they only installed for those attached to specific squadrons (FAC, minsweeper, subs, etc.)? If so, which ships/units have received those davits? And when were they first installed?

**Comment by CasualGerman** [comment]
But i can tell you that the MSP 500 got installed on the Elbe,Mosel and
rhein same with the gecko and davit. Mosel and Rhein got both last year and
the elbe got them around 2018/2019. werra will get them presumably next
year when they go into the shipyard for maintenance. I cant say anything
about the Main because their part of a different squadron and theyre pretty
different from the other tenders they have sonar for example because they
resupply the uboats

Leon Graupner ***@***.***> schrieb am Do. 17. März 2022 um
18:21:

**Comment by CasualGerman** [comment]
Forgot about the donau. She is currently in the yards but i dont know for
certain if she is getting them currently but it was planned that all
tenders are getting the frb (gecko) and msp 500

Leon Graupner ***@***.***> schrieb am Do. 17. März 2022 um
18:31:

**Comment by claudejdev** [comment]
As for the MLG 27, Dimitris Mitsopoulos mention that it came in service in early 2003
https://web.archive.org/web/20071204030517/http://www.rheinmetall-defence.com//index.php?lang=2&fid=962

However, a picture of 2008 shows the A513 Rhein without it, and the comment mention that "2 × Rheinmetall Rh202 20 mm autocannon; being replaced by 2 × MLG-27 27 mm remote controlled autocannons"
https://www.flickr.com/photos/trainplanepro/2719613900

**Comment by PygmalionOfCyprus** [comment]
Added 494. Used IS date of 2019.
