### ISSUE TITLE
Brazil Grajaú Class (Large patrol Craft) PBO x12

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#644]
### DB Selector

DB3K

### DBID to Copy

3161

### Hypothetical

No

### Name

P 40 NPa Grajaú

### Country

Brazil

### Service

Navy

### In Commission

1993-

### Sensors

- 1x Decca 1290A
- Furuno M1954C radars
- 1x Radamec 1000N (mentioned in Janes 2003-04)

### Mounts

- 1x Bofors L/70 40 mm cannon (FWD)
- 2x Oerlikon 20 mm cannon
- Remove 57mm

### Other Changes

- 2x davit for 7m RHIB

### Sources

Janes 2003-04, Pg 67
https://en.wikipedia.org/wiki/Graja%C3%BA-class_patrol_boat
https://www.navypedia.org/ships/brazil/br_cf_grajau.htm
https://www.marinha.mil.br/emgepron/en-us/grajau-class-patrol-ship
https://www.marinha.mil.br/emgepron/sites/www.marinha.mil.br.emgepron/files/fichatecnica/lt_grajau_0.pdf

![grajau_1_0](https://user-images.githubusercontent.com/99632305/157772264-8621a248-8be4-41d4-8314-15be4e309faa.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494. Built from scratch instead of using the Bangladeshi ship since it's pretty much totally different.

**Comment by cdnice55** [comment]
Re: Radmec, my bad, Janes 03-04 has it listed as possible future fitting, sorry. Late night researching....

**Comment by PygmalionOfCyprus** [comment]
Checks and balances! 😉
