### ISSUE TITLE
Brazil Bracuí Class Patrol Corvette x4 [ex River Class Minesweeper] x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#645]
### DB Selector

DB3K

### DBID to Copy

3168

### Hypothetical

No

### Name

P 60 NPa Bracuí

### Country

Brazil

### Service

Navy

### In Commission

1993-

### Sensors

- 2x Decca RM1226 radars

### Mounts

- 1x 1 - 40/60 Mk 9, 
- 2x 1 - 12.7/90
- remove sweep gear

### Other Changes

Displacement standard, t : 770, full 890
Length: 47m
Beam: 11m
Draft: 3.75m max
Engines: 2x Ruston 6RKCM diesels (3040hp)
Max Speed: 14
Fuel: diesel oil 88t
Endurance: 4500nm @ 10kn
Complement: 33 
Boats: 2x RHIBS

Have steel hulls built to commercial single-compartment damage standard.

### Sources

https://en.wikipedia.org/wiki/River-class_minesweeper
https://www.navypedia.org/ships/brazil/br_es_bracui.htm

![br_es_25](https://user-images.githubusercontent.com/99632305/157774493-ea208c10-0d88-4b39-9e9c-b58cdf5ff812.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also totally reworked the existing River Class MSFs (1600, 3168). Bangladesh's was just a straight copy of a tugboat for some reason?!

**Comment by cdnice55** [comment]
Nice, had not even noticed that!
