### ISSUE TITLE
Correction to Yugoslav/Former-Yugoslav Koni/Kotor Frigate Armament

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#65]
### DB Selector

DB3K

### Affected DBID(s)

#1883 - RF 31 Beograd [Ex-Split, Pr.1159 Koni] (Montenegro [1992-] -1992); #1955 - RF 31 Beograd [Ex-Split, Pr.1159 Koni] (Serbia [1992-] -1992); #1956 - RF 31 Spilt [Pr.1159 Koni] (Yugoslavia [-1992] -1987); #1106 - RF 31 Spilt [Pr.1159 Koni] (Yugoslavia [-1992] -1987); #1882 - RF 33 Kotor [Pr.1159 Koni] (Montenegro [1992-] -1992); #1109 - RF 33 Kotor [Pr.1159 Koni] (Yugoslavia [-1992] -1988)

### Summary of Changes

The Spilt/Beograd Konis should have 2 AK-726 mounts (1 fore and 1 aft) like the other Koni class frigates but in the DB they only have one.

#1883 - RF 31 Beograd [Ex-Split, Pr.1159 Koni] (Montenegro [1992-] -1992)
#1955 - RF 31 Beograd [Ex-Split, Pr.1159 Koni] (Serbia [1992-] -1992)
#1956 - RF 31 Spilt [Pr.1159 Koni] (Yugoslavia [-1992] -1987)
#1106 - RF 31 Spilt [Pr.1159 Koni] (Yugoslavia [-1992] -1987)

The Kotors should have 1 AK-726 mount forward but in the DB they have two (1 fore and 1 aft).

#1882 - RF 33 Kotor [Pr.1159 Koni] (Montenegro [1992-] -1992)
#1109 - RF 33 Kotor [Pr.1159 Koni] (Yugoslavia [-1992] -1988)

### Sources

https://en.wikipedia.org/wiki/Kotor-class_frigate

http://www.navypedia.org/ships/yugoslavia/yu_es_kotor.htm

http://www.balkanwarhistory.com/2016/05/kotor-class-frigate.html

http://www.navypedia.org/ships/yugoslavia/yu_es_split.htm

http://www.balkanwarhistory.com/2017/12/koni-class-frigates-in-service-of.html

https://en.wikipedia.org/wiki/Yugoslav_frigate_Split

![4D2500CE1687412898B04C1A68219938](https://user-images.githubusercontent.com/99599482/153756371-844b0569-4f97-4f3f-9427-25768461ec6f.jpg)

![6F13B99E15B34BC194909AC8D2738547](https://user-images.githubusercontent.com/99599482/153756382-579dfee5-4bae-4e29-a971-8ba684376af1.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
