### ISSUE TITLE
Brazil Tamandaré-class (MEKO A-100) Frigate x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#650]
### DB Selector

DB3K

### Baseline

1439

### Hypothetical

No

### Name

F 35 Tamandaré

### Class

Tamandaré-class

### Country

Brazil

### Service

Navy

### In Commission

2025-

### Length (m)

107.2

### Beam (m)

15.95

### Draft (m)

5.2

### Standard Displacement (t)

3500

### Complement

136

### Primary Propulsion Type

Diesel

### Propulsion

4 × MAN V12 28/33D 5,460 kW (7,320 hp)[3] 4 x Caterpillar C32 1,417 kW (1,900 hp) diesel generators[3]

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

4000 @ 14

### Sensors

- Hensoldt TRS-4D AESA radar
- Thales STIR 1.2 EO Mk2 fire control system
- 2x Safran PASEO XLR optronic system
- Raytheon X & S-Band radars
- Atlas Elektronik ASO 713 bow sonar
- Omnisys MAGE Defensor ET/SLR-1 MK3 EW system
- C-ESM 

### Mounts

- VLS MBDA Sea Ceptor GWS.35 x12cells, MBDA CAMM
- 2x twin MBDA MSS ITL 70A: MANSUP AV-RE404-8 
- 2x triple 533mm SEA TLS-TT Mark 46 torpedo tubes
- 1x Leonardo OTO Melara SRGM 76/62 mm main gun
- 1x Rheinmetall Sea Snake 30mm CIWS
- 2x FN Herstal Sea Defender 12.7mm RWS
- 2x miniguns
- TERMA C-Guard

### Aircraft & Docking Facilities

- 2x davits for 11m RHIB
- 1x landing pad for S-70B or Super Lynx
- 1x hangar for S-70B or Super Lynx
- 1x hangar for UAV

### Comms/Datalinks

Standard, nothing noted that I could find

### Sources

https://en.wikipedia.org/wiki/Tamandar%C3%A9-class_frigate#Units
https://www.naval.com.br/blog/2014/10/29/euronaval-2014-caracteristicas-das-corvetas-tamandare-e-do-npaoc-br/
https://www.naval-technology.com/projects/tamandare-class-frigates-brazil/
https://www.edrmagazine.eu/aguas-azuis-consortium-is-chosen-as-preferred-supplier-to-build-four-new-tamandare-class-corvettes

![download](https://user-images.githubusercontent.com/99632305/157807872-1c47e089-6fec-47e3-82fb-b97c86717e9a.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
