### ISSUE TITLE
Benin, Add Alibori class ship

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#652]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), P109, Alibori

### Class

Alibori (Ocea FPB98 Mk I)

### Country

Benin

### Service

Navy

### In Commission

2012 - present

### Length (m)

31.8

### Beam (m)

6.3

### Draft (m)

1.2

### Standard Displacement (t)

100

### Full Displacement (t)

116

### Complement

13

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar C32, 2 waterjets

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

900 @ 14

### Sensors

2x Furuno FAR2117 navigation radar (src1)

### Mounts

1x single 20mm/90 Super Sea Rogue (src2)

### Aircraft & Docking Facilities

1x small RHIB (image)

### Comments

3 units in class. 
Class also in service with the Algerian, Nigerian, Surinam Navy. And build for Ukraine (not sure if delivered)

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/benin/ben_cf_alibori.htm
3: https://beegeagle.wordpress.com/2012/04/02/benin-navy-acquire-three-new-ocea-built-32m-coastal-patrol-craft
4: https://www.defenceweb.co.za/security/maritime-security/benin-acquires-three-new-coastal-patrol-craft
5: https://www.wikiwand.com/cs/T%C5%99%C3%ADda_FPB_98
![1](https://user-images.githubusercontent.com/99532490/157925517-92f60f27-71c6-4c63-9317-f154090408a8.jpg)
![2](https://user-images.githubusercontent.com/99532490/157925521-df80142e-da6a-45ac-88a4-b36bbddd6122.jpg)
![4](https://user-images.githubusercontent.com/99532490/157925523-0603e22d-a4f9-4c45-a266-76c3f2ead0f7.jpg)
![5](https://user-images.githubusercontent.com/99532490/157925524-d9a82739-56f1-4e9c-95ad-cf661c62da9b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
