### ISSUE TITLE
Jar of Pickled Tomatoes

### ISSUE THREAD

**Issue by yooperdude** [PygmalionOfCyprus/cmo-db-requests#654]
### DB Selector

DB3K

### Hypothetical

No

### Name

Jar of Pickled Tomatoes

### Length (m)

0.1

### Width/Span (m)

0.1

### Diameter (m)

0.1

### Weight (kg)

1

### Range (nm)

.01

### Target Altitude / Depth (ft)

60

### Warhead

0.1 kg, impact

### Targets

Aircraft, Helicopter

### CEP (m)

1

### Sensors

Visual Only, no guidance.

### Comments

Wielded by ground forces for anti-drone duty. Primarily used against quadcopters and commercial type drones. 

### Sources

https://www.express.co.uk/news/world/1578061/Ukraine-news-woman-brought-down-drone-jar-of-tomatoes-Russia-invasion-Kyiv
https://dronedj.com/2022/03/08/ukrainian-woman-russian-drone-cucumbers-tomatoes/
https://www.forbes.com/sites/davidhambling/2022/03/08/how-small-drones-could-win-the-fight-in-ukraines-cities-and-the-truth-about-that-anti-drone-pickle-jar-story/?sh=2c252c84641e

**Comment by PygmalionOfCyprus** [comment]
Pilots may call "pickle" on bombing runs, but I don't think this is what they mean...

Keep on the lookout for our spin-off game, _Cucumber: Modern Operations_.

**Comment by PygmalionOfCyprus** [comment]
I changed my mind.

It just so happens that we hit a milestone today: 10,000 weapon records. I wanted to make record 10,000 special.

So now it's a jar of pickled tomatoes.

Congratulations.
