### ISSUE TITLE
Load out #26232 and #26233 described as KD-88 LACM (SEAD, ARM, Land/Naval) Please change to KD-88 LACM (Strike, Land/Naval)?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#655]
### DB Selector

DB3K

### Affected DBID(s)

#26232 #26233

### Summary of Changes

J-16 Load outs #26232 and #26233 are described as **KD-88 LACM (SEAD, ARM, Land/Naval)** 
Request amend to **KD-88 LACM (Strike, Land/Naval)** for clarification of new users not familiar with KD-88 target sets etc.

KD-88 #2876 - KD-88 LACM cannot attack radar and for new users the misleading load out title could be confusing.
Surface Ships
Land Structures (Hard)
Land Structures (Soft)
Mobile Units (Hard)
Mobile Units (Soft)
Runways

### Sources

DB3K 492

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Also changed the two KD-88 loadouts for the J-10C and J-16 to have the "Standoff Strike (Land/Naval)" role better reflecting the weapon nature (and bringing those loadouts in line with other KD-88 loadouts for the JH-7).
