### ISSUE TITLE
Please change load out title of #27343 #26344 from C-803/YJ-83 LACM, C-802AKG (Strike, Land/Naval) to match weapon consistent with other KD-88 Load outs 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#656]
### DB Selector

DB3K

### Affected DBID(s)

#27343 #26344 J-10 load outs. 

### Summary of Changes

Both load outs for the J-10 are entitled **C-803/YJ-83 LACM, C-802AKG (Strike, Land/Naval)**
The weapons used are 2 x  #2876 - KD-88 LACM
**I realise that the KD-88 is aka the C-802AKG etc but its not immediately clear and its inconsistent.**
Other PLAAF/PLAN aircraft such as the J-16 etc use the KD-88 title in the load out so it would be clearer to stay with the convention of calling the load out KD-88 etc. For DB management it would also be simpler in the long run to be consistent to use the KD-88 title and be easier to search against. 
For consistency and clarification request both load outs names are changed to:
**KD-88 LACM (Strike, Land/Naval)**

### Sources

DB3K 492

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. I also adjusted the loadout names to better reflect their differences: 27344 is now "KD-88 LACM, PL-10, DECM" and 27343 is now "KD-88 LACM, PL-8C".
