### ISSUE TITLE
#3025 - AN/AVQ-27 Kit [EO + LRMTS, 12k ft] Cannot illuminate GBU-12 etc - #5289 - AN/AVQ-27 [Laser Designator] does not illuminate?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#657]
### DB Selector

DB3K

### Affected DBID(s)

#3025 - AN/AVQ-27 Kit [EO + LRMTS, 12k ft] #5289 - AN/AVQ-27 [Laser Designator] 

### Description of Problem

The sensor will not illuminate LGB targets.
Have tried load out with a GBU-12 armed #3790 - F-5E Tiger II (Saudi Arabia - 1989) and a 
#3791 - F-5F Tiger II (Saudi Arabia - 1989) with the AN/AVQ-27 [EO], with load out **19090 Buddy Illumination
(Buddy Illumination)** and despite the laser being on and all parameters correct it cannot illuminate the target.
Load out 19090 has the tag "Requires External Illumination" which may be why it does not work??.
Substituting an MX-15 LASER and the GBU is lased perfectly from the buddy aircraft?
Also seems to not work on #3603 - F-5F Tiger II (Taiwan - 1993)
Platforms as follows:
F-5E Tiger II (Saudi Arabia - 1984)
F-5F Tiger II (Saudi Arabia - 1984)
F-5F Tiger II (Saudi Arabia - 1989)
F-5F Tiger II (Taiwan - 1984)
F-5F Tiger II (Taiwan - 1993)

### Recommended Fix

Perhaps check load out description and remove "requires buddy illumination" tag from load out DB3k : 
19090 for Saudi
19087 for Taiwan 
19086 for Taiwan
Or else its an issue with arcs or the sensor itself?

**Comment by PygmalionOfCyprus** [comment]
The problem was that the GBU-12s weren't set to accept an AVQ-27 laser designator as a valid lase. I've added the -27 to its list of lasers and that should fix the problem. 🙂

**Comment by KLABDB3K** [comment]
Brilliant. Thanks for that. Been grappling with this Saudi F-5 combo issue for a Socotra scenario for over 12 months.

**Comment by PygmalionOfCyprus** [comment]
We're also implementing a change to allow laser designators to default to accepting lazing from any laser designator unless we specifically specify otherwise; this should get out in front of future issues like this instead of dealing with them in whack-a-mole fashion as they inevitably continue to pop up.
