### ISSUE TITLE
Russian bombs (BetAB, FAB, KAB, OFAB, ODAB, RBK-250,500,1500) data correction : Length, Weight, LaunchSpeed, LaunchAlt, Range.

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#658]
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

- [x] **BetAB-500**

- ID 1026 - BetAB-500SP CB [12 x Anti-Runway Penetrator Bomblets]
```
- Name = may be "BetAB-500ShP"
- Span = 0.45 m
- Diameter = 0.3 m
- Weight = 380 kg
- LaunchSpeedMin = 324 kts (600 km/h)
- LaunchSpeedMax = 540 kts (1000 km/h)
- LaunchAltitudeMin = 30 m
- LaunchAltitudeMax = 5000 m
```

- [x] **FAB-250**

- ID 1502 - FAB-250M-62 GPB
- ID 1505 - FAB-250M-54 GPB
- ID 2068 - FAB-250M-46 GPB

```
- LaunchSpeedMin = 270 kts (500 km/h)
- LaunchSpeedMax = 594 kts (1100 km/h)
- LaunchAltitudeMin = 500 m
- LaunchAltitudeMax = 12000 m
```

- [x] **FAB-500**
- ID 48 - FAB-500M-62 GPB
- ID 592 - FAB-500M-62T GPB -- Heat-Insulated

```
- Length = 2.47 m
- Weight = 457 kg
- LaunchSpeedMin = 270 kts (500 km/h)
- LaunchSpeedMax = 1026 kts (1900 km/h) (ID 592 = 1350 kts or 2500 km/h )
- LaunchAltitudeMin = 570 m
- LaunchAltitudeMax = 12000 m
```
- ID 1578 - FAB-500M-54 GPB
- ID 2067 - FAB-500M-46 GP
- ID 3458 - FAB-500ShN-54 GPB -- Parabrake

```
- LaunchSpeedMin = 270 kts (500 km/h)
- LaunchSpeedMax = 648 kts (1200 km/h) (ID 2067 = 540 kts)
- LaunchAltitudeMin = 570 m (ID 3458 = 150 m )
- LaunchAltitudeMax = 12000 m (ID 3458 = 500 m )
```
- ID 1578 - FAB-500M-54 GPB
```
- Weight = 474 kg
```

- ID 3458 - FAB-500ShN-54 GPB -- Parabrake

```
- Length = 1.8 m
```

- [x] **KAB-500**
- ID 640 - KAB-500Kr TV/EO -- -
- ID 1035 - KAB-500L LGB -- 1980
- ID 3340 - KAB-500S GLONASS -- 2015
```
- LaunchSpeedMin = 297 kts (550 km/h)
- LaunchSpeedMax = 594 kts (1100 km/h)
- LaunchAltitudeMin = 550 m
- LaunchAltitudeMax = 5000 m
- RangeMax = 4.86 nm (9 km)
- Warhead = ID 664 - FAB-500M-62 [213kg Torpex]
- Comments = ID 1035 IOC in 1979, could be renamed "L-F", that is the most widespread version;
   ID 640 IOC in 1984;
   ID 3340 was cleared on Su-34 in 2006.
```

- [x] **KAB-1500**

- ID 49 - KAB-1500L-Pr LGB [Penetrator] -- -
- ID 639 - KAB-1500L-F LGB -- -
- ID 641 - KAB-1500Kr TV/EO -- -
- ID 3077 - KAB-1500Kr-Pr TV/EO [Penetrator] -- -

```
- LaunchSpeedMin = 297 kts (550 km/h)
- LaunchSpeedMax = 777.5 kts (1440 km/h)
- LaunchAltitudeMin = 500 m
- LaunchAltitudeMax = 18000 m
- RangeMax = 6.48 nm (12 km)
- Comments = (ID 49 and ID 639) commissioned in 1989, (ID 641 and ID 3077) commissioned in 1996.
```

- [x] **OFAB-100**
- ID 644 - OFAB-100-120 Frag
```
- Weight = 123 kg
- LaunchSpeedMin = 270 kts (500 km/h)
- LaunchSpeedMax = 810 kts (1500 km/h)
- LaunchAltitudeMin = 500 m
- LaunchAltitudeMax = 15000 m
```

- [x] **OFAB-250**
- ID 2065 - OFAB-250-270 Frag
```
- Length = 1.46 m
- LaunchSpeedMin = 270 kts (500 km/h)
- LaunchSpeedMax = 810 kts (1500 km/h)
- LaunchAltitudeMin = 500 m
- LaunchAltitudeMax = 12000 m
```

- [x] **ODAB-500**
- ID 3459 - ODAB-500ShL FAE -- Parabrake
```
- Name = "ODAB-500ShP"
- Length = 2.3 m
- Span = 0.5 m
- Diameter = 0.5
- Weight = 520 kg
- LaunchSpeedMin = 270 kts (500 km/h)
- LaunchSpeedMax = 648 kts (1200 km/h)
- LaunchAltitudeMin = 30 m
- LaunchAltitudeMax = 1000 m
```

- [x] **RBK-500**
- ID 842 - RBK-500-PTAB CB [268 x PTAB-1M Anti-Tank Bomblets]
- ID 843 - RBK-500-ZAB [117 x ZAB-2.5SM Incendiary]
```
- Length = 1.9 m
- Weight = 435 kg
- LaunchSpeedMin = 270 kts (500 km/h)
- LaunchSpeedMax = 648 kts (1200 km/h)
- LaunchAltitudeMin = 100 m 
- LaunchAltitudeMax = 20000 m
```

### Sources

**Sources :**

- "Russia's Air-launched Weapons: Russian-made Aircraft Ordnance Today" (2017), Piotr Butowski, ISBN: 978-0997309218.
- "Jane's Air-Launched Weapons" (2001), Duncan Lennox.
- "Soviet/Russian Aircraft Weapons: Since World War Two" (2004), Yefim Gordon, ISBN: 978-1857801880.
- Aerospace systems | Catalog Rosoboronexport
- http://roe.ru/eng/catalog/aerospace-systems/

LLAP

**Comment by Jkryos** [comment]
Updated DB3K 494.

**Comment by claudejdev** [comment]
Guys,
I just realized we don't have most "retarded" Russian bombs in the DB, but the FAB-500ShN-54 GPB on the Syrian Su-22.
The gameplay consequence is that low level bombing attack profile ain't available in most cases, unlike for the Western aircraft for which we have the AIR, Snakeye and such bombs in the DB.
_Would it be better to suggest a bombload of copy and new loadouts or just edit back the LaunchAltitudeMin of the common Russian iron bombs?_

I mean, I'd LOVE to research all bombs and send a request that would Arthur Travers Harris weep, I just don't know if that's what you guys want.
