### ISSUE TITLE
Add Mighty Mouse FFAR to F-102/TF-102

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#66]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft - 623, 1513, 1780, 2242, 2743, 3094, 3095

### Summary of Changes

Could the Mighty Mouse FFAR's be added to the F-102 and TF-102? Launchers were in the missile bay doors.

### Sources

https://www.thedrive.com/the-war-zone/36009/f-102-delta-daggers-weapons-bays-combined-rockets-and-missiles-in-a-feat-of-cold-war-ingenuity

https://www.456fis.org/F-102_IN_VIETNAM.htm

https://www.456fis.org/F-102_HISTORY.htm

https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/197477/f-102-armament/

**Comment by PygmalionOfCyprus** [comment]
This is awesome.

Keyes, we're gonna need to create some new variants of the 102s:
>At first, the rocket armament comprised 36 T-214-2 2-inch FFARs, but these gave way to 24 2.75-inch Mighty Mouse FFARs by mid-1956, being introduced on the 190th production aircraft and then being retrofitted on earlier jets.

>Beginning in 1957, the rocket tubes were removed from the inner doors of the left and right bays, and from the two doors of the center bay, reducing the load to just 12 of the Mighty Mouse projectiles. This remained the standard ‘fit’ until the Delta Dagger was finally retired in 1976, making it the last USAF air defense fighter to carry FFARs in the air-to-air role.

**Comment by tbrandon517** [comment]
I just realized the 456th FIS sites pages are dead. There was some info there similar to the OP on this thread about them using the Mighty Mouse rockets during ground strike missions in Vietnam.

https://www.key.aero/forum/modern-military-aviation/4392-f-102-in-combat

**Comment by PygmalionOfCyprus** [comment]
Added 493.

**Comment by tbrandon517** [comment]
Awesome, thanks!
