### ISSUE TITLE
#5623 Hungaria JAS-39C Amraam loadout doesn't have amraam

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#660]
### DB Selector

DB3K

### Affected DBID(s)

Loadouts 30178, 30179

### Summary of Changes

Good ole copy over gotcha!

30178 Add 2 Iris T
30179- Add 2 Amraam, Remove 2 Iris T

### Sources

Somewhere in the Gamma quadrant of my brain.

**Comment by Huib18** [comment]
I don't have a Hungarian #5623 JAS 39C in my DB3000 v492.  Users of the JAS 39C are Sweden, South Afria and Thailand in the DB..?
How is it possible that you do have one? I just made a new item to request a Hungarian JAS 39C
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/551

**Comment by bostonmyk** [comment]
Check the forum. There was a beta build posted today with an db update.

**Comment by Huib18** [comment]
Ahh, tnx

**Comment by PygmalionOfCyprus** [comment]
I don't even know what I was trying to do here; it's not a copy-over error because I actually would have had to intentionally make these wrong.

The database keeps her secrets.

Fixed for 494.
