### ISSUE TITLE
#3431 Radar (48Ya-K1 Podlet) detections strange

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#661]
### DB Selector

DB3K

### Affected DBID(s)

3431

### Description of Problem

Detection is at around 30nm for a 2000ft F-15E. . There are both surface search and air search rings displayed. The detection correlates with surface search ring.

### Recommended Fix

Not sure. I couldn't tell from the sensor form. Added save game
[PodletTest.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8237729/PodletTest.zip)
.

**Comment by PygmalionOfCyprus** [comment]
Yeah, there was some weird stuff going on with the sensor stats, looks like. Unfortunately I don't know what exactly they're supposed to be (such is the joy of adding currently-fielded platforms from less-than-transparent countries), but I've massaged the values to be more in line with a radar of this class. Pumped the power, raised the gain, etc. It should pick up a fighter-sized target at around ~120nm now.
