### ISSUE TITLE
Please add Switchblade 600 loitering munition

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#662]
### DB Selector

DB3K

### Hypothetical

No

### Name

Switchblade 600 loitering munition

### Country

United States

### Service

Army & USSOCOM

### In Commission

2021

### Length (m)

1.3

### Wingspan (m)

1.8

### Height (m)

unkown

### Empty Weight (kg)

14.97kg

### Maximum Takeoff Weight (MTOW) (kg)

22.7

### Payload Weight (kg)

N/A

### Crew

Unmanned

### Propulsion

Electric

### Rate of Climb (ft/min)

unknown

### Service Ceiling (ft)

operating alt >500 ft AGL (max ceiling >15,000 ft MSL)

### Military/Afterburner Speed (kt)

100 kts dash speed

### Cruise Speed (kt)

61kts

### Supercruise

No

### Ferry Range (nm)

80km

### Endurance (min)

40+ min

### Takeoff / Landing Distance (m)

Tube launched, recovery possibli

### Fuel Capacity (kg)

unknown

### Sensors

2 axis-4 sensor gimbal EO/IR
GPS

A target lock-on capability enables day/night precision engagement of non-line-of-sight hardened static and moving armour targets. Other features include automatic target recognition, selectable attack angle options, a patented wave-off/recommit capability

### Mounts

A multipurpose/anti-armour warhead, derived from the FGM-148 Javelin anti-tank guided missile, equipped with a height of burst sensor. for light armor and anti-personnel or small boats or radars.

### Loadout Options

No loadouts

### Comms/Datalinks

Secure, encrypted M1/2/5 pocket digital data link (pDDL) Line-of-sight.

Tech data from:
https://www.avinc.com/images/uploads/product_docs/DDL_FutureState_Datasheet_05222020.pdf
This is possibly M1@20 GHz, M2@24 GHz, M3@28 GHz
from :https://www.mdpi.com/2076-3417/10/20/7187/pdf

Commslink is dependend of used antenna.
https://www.avinc.com/uas/network-connectivity/antennas.

If a situation causes a strike to be called off, the operator can call off the Switchblade and re-target it. The operator the opportunity to wave off until four seconds from impact.

### Aircraft Codes

Bombsight - Advanced Navigation (INS/GPS)

### Comments

Operational in less than 10 minutes.

AeroVironment will integrate its Switchblade 600 loitering missile system onto US Naval Special Warfare (NSW) combatant craft under a USD26.1 million contract awarded by the US Special Operations Command (USSOCOM).

Announced by the company on 27 April, the contract will address a requirement for a Maritime Precision Engagement (MPE) capability to defeat asymmetric threats on land and at sea. Both the 18.2 m Combatant Craft Medium (CCM) and the 24.3 m Combatant Craft Heavy (CCH) have been identified as potential host platforms for the MPE capability.
https://www.thefifthcolumn.xyz/forum/land-warfare/654-loitering-munitions-and-low-level-swarms#post698

The weight of the overall system, including the SB600, the launcher and the Fire Control System, made of the tablet and the long-range antenna, is 54.4 kg.
https://www.edrmagazine.eu/switchblade-600-the-new-medium-range-loitering-munition.

Switchblade 600 to transit up to 50 miles (80 kilometers) to a target area before conducting multiple confirmatory orbits, and engage in target prosecution – without the need for external ISR or fire assets. 
https://defense-update.com/20210427_switchblade-600.html

The Switchblade 600 can be launched from the ground as well as from air or ground platforms.
https://www.edrmagazine.eu/switchblade-600-the-new-medium-range-loitering-munition

### Sources

https://www.edrmagazine.eu/switchblade-600-the-new-medium-range-loitering-munition
https://www.avinc.com/tms/switchblade-600
https://www.businesswire.com/news/home/20211104005095/en/AeroVironment-Awarded-20.3-Million-Switchblade-600-Tactical-Missile-Systems-Hardware-Contract-by-U.S.-Special-Operations-Command
https://defense-update.com/20210427_switchblade-600.html
https://www.janes.com/defence-news/news-detail/switchblade-600-loitering-missile-to-equip-us-naval-special-warfare-craft

**Vids:**
https://www.youtube.com/watch?v=EBNayBINEBc
https://www.youtube.com/watch?v=tN2HN6ra4nw

More tech data on loitering munitions, maybe handy for other oncoming DB entries:
https://www.sciencedirect.com/science/article/pii/S221491472100146X

**Comment by tbrandon517** [comment]
Additional Sources for Switchblade and Launch Platforms

https://en.wikipedia.org/wiki/AeroVironment_Switchblade
https://www.thedrive.com/the-war-zone/42755/new-tracked-unmanned-vehicle-bristles-with-a-whopping-50-switchblade-suicide-drones
https://www.thedrive.com/the-war-zone/42465/kratos-new-airwolf-combat-drone-has-launched-a-switchblade-loitering-munition-in-flight

**Comment by nkocevar** [comment]
We may want to add Ukraine as an operating country, as the US has begun shipping them over in "Security Assistance Packages"... I'm actually planning on using these in my split Ukraine scenario! 

It looks like both the Switchblade 300 & 600 have been sent to Ukraine, with both being sent in the hundreds at this point:

Evidence 1: https://www.cnet.com/news/us-military-sends-another-600-switchblade-drones-to-ukraine/
Evidence 2: https://www.19fortyfive.com/2022/04/switchblade-the-drone-ukraine-is-using-to-strike-russia-in-ukraine/
Evidence 3: https://www.msn.com/en-us/news/world/us-is-training-ukrainians-to-use-their-new-switchblade-drones-discussing-fuel-needs-pentagon-says/ar-AAVXkjk?ocid=uxbndlbing

**Comment by Huib18** [comment]
Extra info about flight heights:
Switchblade 300: 150m
Switchblade 600: 198m

![Switchblades](https://user-images.githubusercontent.com/60408110/164079315-89fa6368-976e-483f-88e8-f308aa40cbf7.jpg)
https://twitter.com/A7_Mirza/status/1513846453533384709
