### ISSUE TITLE
Russian/Chinese Bomb loadouts for #5609 - An-32B Cline (Iraq - 2011) (DB3K_493)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#663]
### DB Selector

DB3K

### User(s)

ID 5609 - An-32B Cline (Iraq - 2011)

### Weapons Carried

4x ID 1581 - 250kg GPB
or 
4x ID 48 - FAB-500M-62 GPB

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day-Only

### Capable of Quick Turnaround

No

### Comments

An interesting pair of loadouts that could be used in a scenario where the player's forces are quite low tech.
Since it seems quite widespread too, that modification could be copied later on.

- [ ] Please also add to DataAircraftCodes 7001 (Bombsight - Basic) to ID 5609 (An-32B Cline (Iraq - 2011)).

### Sources

_An Iraqi Air Force An-32 with bomb racks in June 2017._
![image](https://user-images.githubusercontent.com/35732829/158026370-790dad28-0fcd-4b31-acc3-3f3da26dd235.png)

![image](https://user-images.githubusercontent.com/35732829/158026721-55b58126-4d0c-4af1-98f2-f7803bf4e227.png)

![image](https://user-images.githubusercontent.com/35732829/158026739-c76e95d8-7fa9-4ea7-8ee9-4df04d51e9fd.png)
![image](https://user-images.githubusercontent.com/35732829/158026891-20205509-a0d0-4d04-9903-bf532c745d46.png)
![image](https://user-images.githubusercontent.com/35732829/158026996-002e6c91-0dd1-4590-bb4c-afddeb26ea7d.png)
![image](https://user-images.githubusercontent.com/35732829/158027355-bc060e27-65e2-424d-bdc9-1c94e0757b15.png)
![image](https://user-images.githubusercontent.com/35732829/158027724-9297ca73-f592-4a60-a855-b9a34213d840.png)

"Technicians equipped the first An-32 with four-beamed BDZ-34 bomb racks on four pylons, two on each side of the fuselage. The idea was to arm the An-32s with four 500-pound Chinese-made bombs. The An-32 also got an NKPB-7 bomb sight."
I thus suggest the bomb mentioned above as it's used on several Chinese, and client states, platforms.

"The two makeshift bombers have been fully engaged since the beginning of the battle for Mosul last October and have regularly carried out tactical bombing in non-populated areas. The aircraft are equipped with Russianmade FAB‑500M-62 "

https://www.keymilitary.com/article/wolves-sheeps-clothing
https://warisboring.com/the-iraqi-air-force-just-got-new-bomber-planes-by-arming-transports/
https://www.thedrive.com/the-war-zone/20330/iraqs-an-32-cargo-planes-turned-bombers-flew-nearly-twice-as-many-strikes-as-its-f-16s
http://iraqimilitary.org/forums/viewtopic.php?t=242&start=45

https://www.globalsecurity.org/military/world/russia/an-32-bombard.htm

**Comment by tbrandon517** [comment]
Link to #329

**Comment by claudejdev** [comment]
> Link to #329

Thanks for the heads up Brandon. I can't beleive I didn't see it was already in the DB.
Maybe that having Chinese and Russian bombs would add more flexibility scenario wise.
I see no need to do it right now though.

**Comment by tbrandon517** [comment]
I haven't downloaded the beta so I don't know if anything important was missed. Wanted to draw attention is case an update was warranted.
