### ISSUE TITLE
YJ-83KB WRA Fix

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#664]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3943 in loadouts 30282 and 30283 for aircraft 5596

### Description of Problem

WRA for YJ-83KB is set for do not use for land units so won't fire unless the player manually resets it. 

### Recommended Fix

The default WRA for land target should be adjusted to allow.

**Comment by PygmalionOfCyprus** [comment]
Not a "bug," per se, just me being stupid. Will fix.

**Comment by bostonmyk** [comment]
Thanks and no worries. I know this isn't easy.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
