### ISSUE TITLE
Update Canadian CSC (Type-26 frigate)

### ISSUE THREAD

**Issue by Seaside232** [PygmalionOfCyprus/cmo-db-requests#666]
### DB Selector

DB3K

### Affected DBID(s)

Latest DB 3000

### Summary of Changes

Update Canadian Type-26 Frigate

### Sources

https://www.navalnews.com/naval-news/2020/11/royal-canadian-navy-unveils-new-details-on-csc-frigates/

**Comment by tbrandon517** [comment]
Link to #252

**Comment by Seaside232** [comment]
Ok , Thanks . I searched for this . Guess not enough :)
Glad it's being looked at.

**Comment by PygmalionOfCyprus** [comment]
Probably didn't see it because the issue was closed; i.e., we already handled it! Guess the CSC must be popular, eh?

**Comment by PygmalionOfCyprus** [comment]
Duplicate of #252

**Comment by PygmalionOfCyprus** [comment]
494 is currently only out on private beta. Do you have access to that or are you on the public beta?

**Comment by Seaside232** [comment]
Just the public. I was just wondering as the original thread did not have all the latest info.
I can wait :)

Thanks for the reply.
Mark
