### ISSUE TITLE
SAM Plt (Mistral I MANPADS x 3) (Spain - 1992), copy of #71 - SAM Plt (Mistral I MANPADS x 3) (France - 1990)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#668]
### DB Selector

DB3K

### DBID to Copy

71

### Hypothetical

No

### Name

SAM Plt (Mistral I MANPADS x 3)

### Country

Spain

### Service

Army

### In Commission

1992

### Sources

Mistral in Spanish Army :
https://ejercito.defensa.gob.es/materiales/artilleria_antiaerea/MISTRAL.html

Spain is still using Mistral I, while the Mistral III is coming :
https://www.infodefensa.com/texto-diario/mostrar/3127060/ejercito-evalua-misil-mistral-3-espera-proxima-adquisicion

IOC 1992 :
http://www.forcesoperations.com/mistral-a-une/

SIPRI Arms Transfers Database | SIPRI, Trade registers
https://www.sipri.org/databases/armstransfers

**Comment by PygmalionOfCyprus** [comment]
Added 494.
