### ISSUE TITLE
APG-30 Range issue reappeared

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#67]
### DB Selector

CWDB

### Affected DBID(s)

All APG-30 radars

### Summary of Changes

The APG-30 range had been corrected previously but as of CWDB v478 had a range of 30nm. It think it was fixed again but as of v491 had a range again of 30nm but now as a surface search radar.

AN/APG-30 range was 3000 yards (not 20nm!). It is a ranging radar.

### Sources

https://www.radartutorial.eu/19.kartei/11.ancient2/karte057.en.html

**Comment by Jkryos** [comment]
Fixed CWDB 493.
