### ISSUE TITLE
ASTAC Pod [ESM] loadout for Mirage 2000-5EI (Taiwan)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#670]
### DB Selector

DB3K

### User(s)

ID 175 - Mirage 2000-5EI (Taiwan - 1999)

### Weapons Carried

1x ID 1031 - ASTAC Pod [ESM]
2x ID 1533 - 1700 liter Drop Tank
(optional) 2x ID 242 - R.550 Magic 2 Mk2 -- 1997

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

![image](https://user-images.githubusercontent.com/35732829/158084822-59bb79f8-6019-42fb-a50f-0eaa2754451f.png)
![image](https://user-images.githubusercontent.com/35732829/158084831-68907f45-4a1a-40f9-8b7d-cb53d357b2a7.png)
![image](https://user-images.githubusercontent.com/35732829/158084834-edf900fb-7b7c-45c7-b9d8-6f1f2021a55b.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
