### ISSUE TITLE
New Oil Slick units in 493 missing? 

### ISSUE THREAD

**Issue by boogaboogaCMO** [PygmalionOfCyprus/cmo-db-requests#671]
### DB Selector

DB3K

### Affected DBID(s)

?

### Description of Problem

The new 493 version of the DB3K is supposed to have these units (as ships): 

Oil Slick (Huge) -- Unknown (None)
Oil Slick (Large) -- Unknown (None)
Oil Slick (Medium) -- Unknown (None)
Oil Slick (Small) -- Unknown (None)
Oil Slick (Tiny) -- Unknown (None)

However, I'm not seeing them in the DB viewer.

### Recommended Fix

I don't know. Perhaps they were omitted for some reason?

**Comment by PygmalionOfCyprus** [comment]
That's strange.

This might be related to its "None" values; it's possible the DB viewer doesn't know how to handle them. Are you able to spawn one in via Lua? The DBIDs are Ship 3612-3616.

**Comment by Parel803** [comment]
Added 3612 with new unit but also no luck in DB viewer,
regards GJ

**Comment by boogaboogaCMO** [comment]
Yes, I can add with Lua, but not though the normal scen. editor UI interface and can't see it in DB viewer.

**Comment by PygmalionOfCyprus** [comment]
Okay. That definitely sounds like an issue with the DB viewer.

I passed this on to the team a couple days ago so we should have it fixed shortly. 🙂

**Comment by boogaboogaCMO** [comment]
FWIW, I think that these kind of creative/generic units that are not tied to any particular time period should be added to the CWDB as well...  

Pistol shrimp as well.

**Comment by PygmalionOfCyprus** [comment]
Yes, I agree. The CWDB-DB3K relationship has historically been a bit of an odd beast (different ownership/management, etc.) but I'm aiming to consolidate things now.

We're currently testing a new tool for copying entries between the two DBs (our legacy program was being held together by duct tape and hope and was a _massive_ pain to use) so once that's safe to use on a "live" DB you should see a bunch more stuff getting brought over from one to the other.

**Comment by Parel803** [comment]
Thanks for the hard work, much appreciated
regards GJ

**Comment by PygmalionOfCyprus** [comment]
Just closing this ticket in the pre-release wrapup since it's not technically a DB issue, moreso a "sim-side" thing. (Specifically an issue with the DB viewer, as mentioned previously.) It's been passed on so not much more I can do keeping it open here.
