### ISSUE TITLE
127mm Shell Corrections

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#672]
### DB Selector

DB3K

### Affected DBID(s)

3043, 3047, 3048

### Summary of Changes

3043 is the 127mm Mk187 HE-MFF shell used in later model USN Mk45 guns for AAW, but it doesn't have any AAW ability in the DB. Conversely 3047, the Mk 186 HE-MOFN that in reality doesn't have any AAW capability does have it in the DB. The descriptions are correct however. The same goes for 3048, which is a carbon copy of 3047, but isn't actually used on any platforms.

![3043](https://user-images.githubusercontent.com/101542189/158107993-ef2bc989-bb40-4a37-bc12-22f7733ff5e9.PNG)
![3048](https://user-images.githubusercontent.com/101542189/158108004-c5a99099-7324-4f3f-a32e-6f0e4e9f23e3.PNG)

Attached source is an article on fuse procurement talking about which shells accomplish which tasks.

### Sources

https://www.defenseindustrydaily.com/mk437-mofn-naval-fuzes-07508/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Also marked that unused copy as UNUSED for later transformation into something else.
