### ISSUE TITLE
#3217 FFG 818 Daegu need revise of its weapon system

### ISSUE THREAD

**Issue by Ma-ryang** [PygmalionOfCyprus/cmo-db-requests#673]
### DB Selector

DB3K

### Affected DBID(s)

#3217

### Summary of Changes

1. Currently #3217 Daegu class frigate is equipped with the MK31 RAM that never used, it must be removed.
2. Daegu class's #3596 KM-SAM Block 2 Must replaced with #3938 K-SAAM (해궁), some website (navyrecognition, diplomat) claims daegu's has capable of launching KM-SAM (Cheongung or Cheolmae) but it is not true. IRL KM-SAM cannot fire from any kind of KVLS, only the ROKAF's Air Defence Missile Command operates the KM-SAM as ground sam battery

### Sources

https://scontent-gmp1-1.xx.fbcdn.net/v/t1.6435-9/148684302_3602918713139823_3894728254912739134_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=730e14&_nc_ohc=kKrTBgZisU0AX_zo2jd&_nc_ht=scontent-gmp1-1.xx&oh=00_AT_W_3C4m9fBMXgyfZoHO5zsoRZjjc08WssxvqNek9sTzQ&oe=625271DE
https://www.navalnews.com/naval-news/2021/12/south-koreas-new-k-saam-sam-system-ready-for-mass-production/
https://blog.kakaocdn.net/dn/szEcw/btqIH55tEME/idQoKNkaUkXEdiKZu6mWz0/img.jpg

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Did a full review of the ship and replaced a bunch of its sensors, weapons, etc. to be accurate to real life.
