### ISSUE TITLE
Russian engines specs (AL-31, AL-41 SFC, Thrust)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#674]
### DB Selector

DB3K

### Affected DBID(s)

2178, 2361, 2905, 1867

### Summary of Changes

Hey there, I would like to suggest a few changes on Specific fuel Consumption value I feel could be changed to match their manufacturer's figures. 

> ID 2178 2x AL-31FP 
> ID 2361 2x AL-31FM-1

- SFCMilitary = 0.78 
- SFCAfterburner = 1.96
(The whole AL-31 family's SFCs could be changed to these values, for coherence's sake.)

> ID 2178 2x AL-31FP
- ThrustPerEngineMilitary = 7770.0
- ThrustPerEngineAfterburner = 12500.0

> ID 2361 2x AL-31FM-1
- ThrustPerEngineAfterburner = 13500.0

> ID 2905 2x AL-31FN Series 2
- Name = AL-31FM-2
- ThrustPerEngineAfterburner = 14500.0

> ID 1867 2x AL-41F1S [Saturn 117S] TVC
- SFCMilitary = 0.77
- SFCAfterburner = 1.78
- ThrustPerEngineAfterburner = 14500.0

### Sources

AL-31F/P https://www.uecrus.com/eng/products/military_aviation/al31f/
AL-31FM-1 https://web.archive.org/web/20120311140017/http://www.salut.ru/ViewTopic.php?Id=652
AL-31FM-2 https://www.uecrus.com//viewtopic.php/?Id=1459
AL-41F-1S http://roe.ru/eng/catalog/aerospace-systems/engines/al-41f-1s/

**Comment by PygmalionOfCyprus** [comment]
This is extremely useful, thank you.

**Comment by claudejdev** [comment]
> This is extremely useful, thank you.

Glad to help! ;) (and I'm having a blast searching data ^^)

Is there any platform, or group of platforms, that would be more useful to focus on for now ?

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
