### ISSUE TITLE
ID 2801 - T 61 Capana [Pr.1171 Tapir] (Venezuela - 1984), misleading name (is not a Pr.1171 Tapir)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#675]
### DB Selector

DB3K

### Affected DBID(s)

ID 2801 - T 61 Capana [Pr.1171 Tapir] (Venezuela - 1984)

### Summary of Changes

Hey there, so the ship ID 2801 - T 61 Capana [Pr.1171 Tapir] (Venezuela - 1984), actually ain't a [Pr.1171 Tapir].
So I would suggest _updating its name to 'T 61 Capana'_ to avoid any misunderstanding for the player and content creator alike.

### Sources

http://old-navypedia.org/ships/venezuela/ven_ls_capana84.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
