### ISSUE TITLE
P-8 Poseidon LRASM Loadout

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#677]
### DB Selector

DB3K

### User(s)

Australian and USN P-8 Poseidons

### Weapons Carried

4x AGM-158C LRASM

Copy and replace Harpoons for loadout.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Likely same as Harpoon

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

LRASM integration for the P-8 is planned by the USN after F/A-18E/F. Australia is considering LRASM for P-8 after LRASM aqquistion announced. 

### Sources

https://adbr.com.au/adf-to-commit-to-maritime-missile-programs/
https://www.navalnews.com/naval-news/2020/05/navair-progressing-towards-lrasm-integration-on-p-8a-mpa/
https://www.thedrive.com/the-war-zone/32071/navy-to-greatly-expand-p-8-poseidons-mission-with-new-missiles-mines-bombs-and-decoys

**Comment by HudsonCW** [comment]
"America’s Aircraft U.S Military Aircraft 1955 - 2020 edited by Larry Bond, Chris Carlson, & Peter Grining" Supports this, places IOC around 2024 (This book is presently 2 years old so info could be dated) and gives a loadout out of "5 Mk54 HAAWC (231kg/u), 4 AGM-158C LRSAM (1084kg/u), 75 SSQ-53G (search), 14 SSQ-77C VLAD, 12 SSQ-62F, 15 SSQ-101A ADAR, 10 SSQ-125" with a combat radius of roughly 1950nm.

**Comment by PygmalionOfCyprus** [comment]
Added 494 for USN. Holding on Aus until we get official word.

**Comment by tbrandon517** [comment]
> Added 494 for USN. Holding on Aus until we get official word.

#PygmalionOfCyprus 

Aussie P-8 demonstrates LRASm capability at RIMPAC 26 test. Not operational deployed yet but moving closer.

https://www.armyrecognition.com/news/aerospace-news/2026/australia-pushes-p-8a-poseidon-beyond-maritime-patrol-with-agm-158c-long-range-anti-ship-strike-capability?fbclid=IwdGRzaAUSzYxjbGNrBRLNZnBkb2YFZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMzUwNjg1NTMxNzI4AAEeJ8GnL32AOLQdZH8JZPrQW0SkhyCJhu-lYGIdUI_eWIiEyKNvYt3EhV16Eu8_aem_sL0rIGsLaYfjnTIh6C5Yqg

**Comment by tbrandon517** [comment]
IOC declared 

https://www.navalnews.com/naval-news/2026/09/australian-air-force-declares-ioc-for-lrasm-jassm/?fbclid=IwdGRzaAUUqk9jbGNrBRSqSXBkb2YFZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMzUwNjg1NTMxNzI4AAEefzFc6kOOhFGA4dkovJDkWPZFT4-v-sy8XkSs-l7AniEJ-7q_Q6r6DOpAumE_aem_Slfcp1w1ASPRN23OAUAkcg
