### ISSUE TITLE
Togo, Add: Agou class PB

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#679]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat(PB), P763, Agou

### Class

Agou (Raidco RPB33)

### Country

Togo

### Service

Navy

### In Commission

2014 - present

### Length (m)

34

### Beam (m)

6.53

### Draft (m)

1.9

### Standard Displacement (t)

Not found

### Full Displacement (t)

100

### Complement

17

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 12V2000 M72 diesels, 2 shafts

### Flank Speed (kt)

23

### Range (nm) at Speed (kt)

1500 @ 15

### Sensors

1x Furuno I-band navigation radar

### Mounts

1x single 12.7mm/90, 2x single 7.6mm/90

### Aircraft & Docking Facilities

Small RHIB aft ramp

### Comments

2 units in class

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/togo/tog_cf_agou.htm
3: https://www.defenceweb.co.za/sea/sea-sea/togo-takes-delivery-of-33-metre-patrol-boat
4: https://www.nauticexpo.com/prod/raidco-marine/product-22737-264120.html
![1](https://user-images.githubusercontent.com/99532490/158341933-b89210d4-5e50-4d03-a63d-1420aee058e7.jpg)
![2](https://user-images.githubusercontent.com/99532490/158341937-23525dbc-1876-4894-b37c-4e562956089a.jpg)

**Comment by Parel803** [comment]
![3](https://user-images.githubusercontent.com/99532490/158343998-897d80bd-5d3b-4f39-8f49-dbac592eb951.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
