### ISSUE TITLE
Yak-3 Fuel Issue

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#68]
### DB Selector

CWDB

### Affected DBID(s)

DB ID #s - 376, 806, 1934, 2411, 2412

### Summary of Changes

Yak-3's have a fuel burn issue at full throttle. Fuel use drop dramatically at full power to the point of intercontinental range at high altitude.

### Sources

![51956343EF4F4FACB879DBB154FCD196](https://user-images.githubusercontent.com/99599482/153757730-fd9eba2e-7b64-49eb-8c6c-283f10a96e81.gif)

**Comment by Jkryos** [comment]
Fixed CWDB 493.

**Comment by PygmalionOfCyprus** [comment]
Reopening. This turns out to be a little more pernicious than initially expected...

**Comment by PygmalionOfCyprus** [comment]
Not only have I fixed the Yak-3s, I discovered a long chain of bad-copies that was leading to bogus mil-power fuel consumption across 150+ piston/turboprop engines and God knows how many aircraft. So, I fixed all those, too. There are sure to be more like this that escaped my hasty net, but this is nevertheless another blow landed against the nightmare that is CWDB propulsion.
