### ISSUE TITLE
Russian Forpost R UCAV variant of #4038 Searcher II [Forpost] UAV - 2011, 10x

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#681]
### DB Selector

DB3K

### DBID to Copy

#4038 Searcher II [Forpost] UAV - 2011, 10x

### Hypothetical

No

### Name

Forpost R [Searcher II] UCAV - 2019, 

### Country

Russia

### Service

Air Force

### In Commission

2019

### Sensors

Gimbled PTZ
Generic 2nd Generation FLIR
CCD/TV
LRMTS

### Mounts

NIL

### Loadout Options

2 x KAB-20L Laser guided mini bomb.
or 
2 x KAB-20S Satellite guided mini bomb.
Or
2 x 9M133 Kornet D ATGM (Air launched long range 8-10km variant) 

### Other Changes

Russian copy of Israeli Searcher II following withdrawl of Israeli support. Russian version of existing foreign engine and foreign components replaced with Russian systems. 
Ruggedised and armed with 2 x pylons for KAB-20 or two air launched Kornet ATGM with laser designator.
KAB-20 similar in overall capability as Turkish MAM-L. 

### Sources

Jane's. 
https://www.janes.com/defence-news/defence/latest/ukraine-conflict-russia-employs-forpost-r-ucav

**Comment by Jkryos** [comment]
Added DB3K 494.
