### ISSUE TITLE
AASM 1000, specs

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#682]
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

Hey there, the values currently in the DB are those from the 250 kg weapon.
For this 1000 kg version, I would suggest the following values :

> 3863	AASM/D [Hammer, Mk84, GPS-Only]
> 3864	AASM/M [Hammer, Mk84, GPS + IIR]
> 3865	AASM/M [Hammer, Mk84, GPS + SALH]
> 3866	AASM/D [Hammer, BLU-109, GPS-Only]
> 3867	AASM/M [Hammer, BLU-109, GPS + IIR]
> 3868	AASM/M [Hammer, BLU-109, GPS + SALH]

- Length = 4,2
- Span = 1
- Diameter = 0,4
- Weight = 1150

### Sources

The values are an estimation based on these elements 

- The guidance kit's weight is _estimated_ at 150 kg
- the bomb's istelf is around 1 000 kghttps://www.deagel.com/Defensive%20Weapons/AASM/a001098

As for the size, I looked at the Spice 2000 bomb as a guideline
![image](https://user-images.githubusercontent.com/35732829/158469964-339b7889-73eb-4e8f-82b3-6613b431385c.png)
![image](https://user-images.githubusercontent.com/35732829/158473647-a90c42b1-56f3-4cd8-bd37-c126d88d31b8.png)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
