### ISSUE TITLE
#2581 - A 136 Tidespring [MARS Tide Class], 2017 (Fuel update, #2)

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#683]
### DB Selector

DB3K

### Affected DBID(s)

#2581 - A 136 Tidespring [MARS Tide Cass] (United Kingdom - 2017)

### Summary of Changes

I think the fuel needs an additional 0 adding to both fuel capacities making 10,000 tons Diesel and 6000 tons Aviation fuel this would put them more inline with other tankers and works mathematically with the 19,000m3 capacity.

Diesel: 959Kg/m3 x 19,000m3 = 18221000Kg, 18221000/1000Kg = 18221 metrics tonnes = 17933 Long tons = 20085 Short tons.

I think the math is right but i'm not sure which ton we are using for me it would be tonne (metric) given fuel consumption is in Kg

Thanks

### Sources

Ticket #192 (Closed)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. I'll get it eventually...
