### ISSUE TITLE
RU/UA/CN engine specs (Thrust, SFC, Name)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#684]
### DB Selector

DB3K

### Summary of Changes

Hey there, I would like to suggest various modifications to make the data of these engines match the figures of their manufacturer or reliable references.

Let me know how you think I could improve the format of such a report, whith that many entries.

### DataPropulsion
---

| #    | Name                     |
|------|--------------------------|
| 55 | 6x D-18T|
| 398 | 4x D-18T|
- [x] SFCMilitary = 0.345

| 207  | 1x AI-25TL |
| ------------- | ------------- |
- [x] SFCMilitary = 0.815

| 223 | 2x AI-20D-4|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary =5180.0
- [x] SFCMilitary = 0.227

| #    | Name                     |
|------|--------------------------|
| 278 | 2x TV3-117KM|
| 1954 | 2x TV3-117KM|
| 1039 | 2x TV3-117M|
| 2373 | 2x TV3-117M|
| 1129 | 2x TV3-117MT|
- [x] ThrustPerEngineMilitary = 2225.0
- [x] SFCMilitary = 0.23

| #    | Name                     |
|------|--------------------------|
| 337  | 2x RD-33 |
| 1756  | 2x RD-33 |
| 1757  | 2x RD-33 |
- [x] SFCMilitary = 0.77
- [x] SFCAfterburner = 1.85

| #    | Name                     |
|------|--------------------------|
| 356 | 2x TV3-117V|
| 752 | 2x TV3-117VK|
| 1531 | 2x TV3-117VK|
| 1953 | 2x TV3-117VK|
- [x] ThrustPerEngineMilitary = 2200.0
- [x] SFCMilitary = 0.23

| #    | Name                     |
|------|--------------------------|
| 360 | 4x AI-20M|
| 1453 | 4x AI-20M|
| 1581 | 4x AI-20M|
| 1713 | 4x AI-20M|
- [x] SFCMilitary = 0.239

| ID  | Name |
| ------------- | ------------- |
| 370  | 1x AL-21F-3  |
| 417  | 2x AL-21F-3A  |
| 1895  | 1x AL-21F-3  |
| 1896  | 1x AL-21F-3  |
| 2269  | 1x AL-21F-3  |
- [x] SFCMilitary = 0.86
<kbd>_0.76_ is at Cruise regime [^1]</kbd>

| 394 |2x D-30F6 |
| ------------- | ------------- |
- [x] ThrustPerEngineAfterburner = 15510.0

| 421 | 2x AI-24T|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 2820.0
- [x] SFCMilitary = 0.255

| #    | Name                     |
|------|--------------------------|
| 573  | 4x D-30KP-2              |
| 727  | 4x D-30KP                |
| 1987 | 4x D-30KP-2              |
| 2215 | 2x WS-18 [D-30KP-2 Copy] |
| 2754 | 4x D-30KP                |
- [x] SFCMilitary = 0.49

| #    | Name                     |
|------|--------------------------|
| 605  | 2x RD-33MK |
| 1951  | 2x RD-33MK |
| 2393  | 2x RD-33MK |
- [x] ThrustPerEngineMilitary = 5300.0
- [x] ThrustPerEngineAfterburner = 9000.0
- [x] SFCMilitary = 0.88
- [x] SFCAfterburner = 1.82

| #    | Name                     |
|------|--------------------------|
| 723  | 2x RD-33.3 |
| 2266  | 2x RD-33.3 |
- [x] ThrustPerEngineMilitary = 5600.0
- [x] SFCMilitary = 0.78
- [x] SFCAfterburner = 1.85

| #    | Name                     |
|------|--------------------------|
| 770 | 2x TV3-117VMA|
| 1532 | 2x TV3-117VMA|
| 1600 | 2x TV3-117VMA|
- [x] ThrustPerEngineMilitary = 2200.0
- [x] SFCMilitary = 0.231

| 1111 | 4x AI-20D-6|
| ------------- | ------------- |
- [x] Name : AI-20M [WJ-6]
- [x] ThrustPerEngineMilitary =5180.0
- [x] SFCMilitary = 0.227
<kbd>Reason : I couldn't find any mention of an 'AI-20D-6' in my sources, while it is assigned to the An-12 and Y-8 families; which already share the same DataAircraftPropulsion profile. And that match the real AI-20M and its Chinese copy</kbd>

| 1113 | 2x D-136|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 10000.0
- [x] SFCMilitary = 0.210

| 1136 | 1x RD-93MA  |
| ------------- | ------------- |
- [x] SFCMilitary = 0.77
- [x] SFCAfterburner = 1.85

| 1508 | 1x RD-35 |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 2500.0

| 1530 | 2x TV2-117A|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 1500.0
- [x] SFCMilitary = 0.275

| #    | Name                     |
|------|--------------------------|
| 1601 | 2x VK-2500|
| 2980 | 2x VK-2500|
- [x] ThrustPerEngineMilitary = 2400.0
- [x] SFCMilitary = 0.210

| 1612 | 2x AI-24A|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 2550.0
- [x] SFCMilitary = 0.257

| 1712  | 3x D-30KU-154 |
| ------------- | ------------- |
- SFCMilitary = 0.482

| 2475  | 2x D-30-II |
| ------------- | ------------- |
- [x] SFCMilitary = 0.608

| 2476 | 2x TV3-117VMA-SBM1|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 2500.0	
- [x] SFCMilitary = 0.199

| 2477 | 2x D-436-148 Progress|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 6570.0
- [x] SFCMilitary = 0.351

| 2725 | 2x TV2500|
| ------------- | ------------- |
- [x] Name = VK-2500P
- [x] ThrustPerEngineMilitary = 2400.0
- [x] SFCMilitary = 0.210
(that would actually be a VK-2500 engine)

| 2898 | 2x AI-450T|
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 450.0
- [x] SFCMilitary = 0.277

### Sources
[^1]: Jane's Aero-Engines issue 11
<details>
<summary>Click to open the URL box</summary>

https://www.klimov.ru/production/aircraft/RD-33-family/
http://roe.ru/eng/catalog/aerospace-systems/engines/rd-33/
http://www.airwar.ru/enc/engines/rd33k.html
https://www.klimov.ru/production/aircraft/RD-33MK/
http://www.airwar.ru/enc/engines/rd133.html
http://motorsich.com.ua/AI-20
https://ivchenko-progress.com/?portfolio=ai-20&lang=en
http://motorsich.com.ua/TV3-117VMA-SBM1
https://www.klimov.ru/en/production/aircraft/TV3-117-SBM1/
https://ivchenko-progress.com/?portfolio=ai-24&lang=en
http://motorsich.com.ua/AI-24
https://ivchenko-progress.com/?portfolio=d136&lang=en
https://ivchenko-progress.com/?portfolio=%D0%B0%D0%B8-450%D1%81&lang=en
https://www.klimov.ru/en/production/helicopter/VK-2500/
http://motorsich.com.ua/VK-2500
https://www.klimov.ru/production/helicopter/TV2-117/
https://lenta.ru/news/2015/11/10/amtsh/
https://www.klimov.ru/production/helicopter/vc-2500ps/
https://web.archive.org/web/20130307012729/http://en.klimov.ru/production/helicopter/TV2-117/
http://uoe.com.ua/products/en/?id=0&pid=catalogue&language=eng&catalogue_id=56&type=content
http://uoe.com.ua/products/en/?id=0&pid=catalogue&language=eng&catalogue_id=58&type=content
http://uoe.com.ua/products/en/?id=0&pid=catalogue&language=eng&catalogue_id=57&type=content
https://www.klimov.ru/en/production/helicopter/TV3-117/
http://motorsich.com.ua/TV3-117VMA
http://motorsich.com.ua/TV3-117VM
http://motorsich.com.ua/TV3-117VMA-SBM1V-4E-series
https://ivchenko-progress.com/?portfolio=d436-148&lang=en
http://uoe.com.ua/products/en/?id=0&pid=catalogue&language=eng&catalogue_id=45&type=content
http://uoe.com.ua/products/en/?id=0&pid=catalogue&language=eng&catalogue_id=42&type=content
https://ivchenko-progress.com/?portfolio=d18t&lang=en
http://motorsich.com.ua/D-18T
</details>

**Comment by claudejdev** [comment]
**AI-20 Addendum**
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

> 360	4x AI-20M
> 1453	4x AI-20M
> 1581	4x AI-20M
> 1713	4x AI-20M
- SFCMilitary = 0.239

> 223	2x AI-20D-4
- ThrustPerEngineMilitary =5180.0
- SFCMilitary = 0.227

> 1111 4x AI-20D-6
- Name : AI-20M [WJ-6]
- ThrustPerEngineMilitary =5180.0
- SFCMilitary = 0.227

Reasoning : I couldn't find any mention of an 'AI-20D-6' in my sources. That engine is assigned to the An-12 and Y-8 families; which already share the same DataAircraftPropulsion profile.

### Sources
http://motorsich.com.ua/AI-20
https://ivchenko-progress.com/?portfolio=ai-20&lang=en
Jane's Aero-Engines issue 03

**Comment by claudejdev** [comment]
**Addendum**

### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

> 360	4x AI-20M
> 1453	4x AI-20M
> 1581	4x AI-20M
> 1713	4x AI-20M
- SFCMilitary = 0.239

> 223	2x AI-20D-4
- ThrustPerEngineMilitary =5180.0
- SFCMilitary = 0.227

> 1111 4x AI-20D-6
- Name : AI-20M [WJ-6]
- ThrustPerEngineMilitary =5180.0
- SFCMilitary = 0.227

(Reasoning : I couldn't find any mention of an 'AI-20D-6' in my sources. That engine is assigned to the An-12 and Y-8 families; which already share the same DataAircraftPropulsion profile.)

> 2476	2x TV3-117VMA-SBM1
- ThrustPerEngineMilitary = 2500.0	
- SFCMilitary = 0.199

> 1612	2x AI-24A
- ThrustPerEngineMilitary = 2550.0
- SFCMilitary = 0.257

> 421	2x AI-24T
2560.0 0.51
- ThrustPerEngineMilitary = 2820.0
- SFCMilitary = 0.255
- 

### Sources
http://motorsich.com.ua/AI-20
https://ivchenko-progress.com/?portfolio=ai-20&lang=en
http://motorsich.com.ua/TV3-117VMA-SBM1
https://ivchenko-progress.com/?portfolio=ai-24&lang=en
http://motorsich.com.ua/AI-24
Jane's Aero-Engines issue 03


Note : it seems like values were previously expressed in pounds, while now it's in kg. That might explain some significant difference observed of values.

_Question : does that format work for you ? Let me know if you would prefer tasks for each item and or even a separate issue. Whatever works best for you._

**Comment by Jkryos** [comment]
Updated DB3K 494.
