### ISSUE TITLE
SNECMA M88-9, not actually used on Rafale

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#685]
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

In DataAircraftPropulsion table

- [ ] please set ComponentID = 269 2x SNECMA M88-2/3/4

for each ID :

- 3230 - Rafale C (France - 2019)
- 3231 - Rafale M (France - 2019)
- 3643 - Rafale B (France - 2019)
- 4360 - Rafale C (Qatar - 2018)
- 4361 - Rafale B (Qatar - 2018)
- 4362 - Rafale C (Egypt - 2017)
- 4363 - Rafale B (Egypt - 2017)
- 4777 - Rafale B (India - 2020)
- 4778 - Rafale C (India - 2020)
- 5267 - Rafale B (Croatia [1992-] - 2024)
- 5268 - Rafale C (Croatia [1992-] - 2024)
- 5271 - Rafale B (France - 2022)
- 5272 - Rafale C (France - 2022)
- 5273 - Rafale M (France - 2022)
- 5274 - Rafale B (France - 2024)
- 5275 - Rafale C (France - 2024)
- 5276 - Rafale M (France - 2024)
- 5404 - Rafale B (Greece - 2021)
- 5405 - Rafale C (Greece - 2021)
- 5485 - Rafale B (UAE - 2027)
- 5486 - Rafale C (UAE - 2027)
- 5505 - Rafale C (Qatar - 2022)
- 5506 - Rafale B (Qatar - 2022)
- 5588 - Rafale B (Indonesia - 2027)
- 5589 - Rafale C (Indonesia - 2027)

### Sources

Landry Dellis, M88 Product Engineer at Safran, confirmed that the M88-9 engine version actually is not produced, and that all current Rafale are using the same engine.

https://www.facebook.com/groups/565680463831717/posts/1575064599559960/?comment_id=1575076602892093
https://fr.linkedin.com/in/landry-dellis-a89a0b103

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
