### ISSUE TITLE
Y-8F-200W Cub - 2018, 8x - Kazakhstan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#687]
### DB Selector

DB3K

### DBID to Copy

aircraft/3737/DB3K

### Hypothetical

No

### Name

Y-8F-200W Cub

### Country

Kazakhstan

### Service

National Guard

### In Commission

2018-Present

### Sensors

No changes indicated

### Mounts

No changes indicated

### Loadout Options

No changes indicated

### Other Changes

No changes indicated

### Sources

https://www.oryxspioenkop.com/2021/08/tried-and-trusted-kazakhstan-acquires-y.html

https://archive.ph/20181006143401/https://www.janes.com/article/83301/china-hands-over-y-8f200w-transport-aircraft-to-kazakhstan

https://defence-blog.com/kazakhstan-receives-first-y-8-military-transport-aircraft/

![image](https://user-images.githubusercontent.com/99599482/158597969-b6521820-8030-4497-9d70-0844baa69948.png)

**Comment by Jkryos** [comment]
Added DB3K 494.
