### ISSUE TITLE
Bayraktar TB2 UCAV - 2022, MX-15D - Pakistan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#688]
### DB Selector

DB3K

### DBID to Copy

aircraft/5397/DB3K

### Hypothetical

No

### Name

Bayraktar TB2 UCAV

### Country

Pakistan

### Service

Air Force

### In Commission

2022-Present

### Sensors

Not stated but images seem to show MX-15 turret

### Mounts

Images show 2x MAM Loadouts

### Loadout Options

Images show 2x MAM Loadouts

### Other Changes

None Stated 

### Sources

https://www.oryxspioenkop.com/2021/10/perfect-storm-pakistan-eyes-bayraktar.html

https://www.pakdefense.com/blog/pakistan-air-force/pakistan-air-force-officially-deploys-turkish-bayraktar-tb2-medium-altitude-long-endurance-tactical-combat-drone-for-combat-missions/

https://www.overtdefense.com/2022/03/14/pakistan-acquires-bayraktar-tb2-and-akinci-drones-from-turkey/

**Comment by Jkryos** [comment]
Added DB3K 494.
