### ISSUE TITLE
AAA Plt (H/PJ-14 [Type 1130] x 2) - China 

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#689]
### DB Selector

DB3K

### Hypothetical

No

### Name

AAA Plt (H/PJ-14 [Type 1130] x 2)

### Facility Type

AAA

### Country

China

### Service

PLA

### In Commission

2021

### Dispersion Radius (m)

Not Stated

### Sensors

Generic TV Camera (DB3Ksensor/4604/) - (3rd Gen, Weapon Director) Visual

China Type 347G [TR-47C, Radar Tracker] (DB3K/sensor/2892/) - (Goalkeeper, Type 730 CIWS) Radar

Generic Target Indicator, 3D Surface-to-Air, Surface-to-Surface (DB3K/sensor/5718/) - (Goalkeeper, Type 730 CIWS) Radar

### Mounts

2x 30mm China H/PJ-14 [Type 1130, 500 rnds] - (China, 11 Barrels, Upgr Goalkeeper Copy) Gun (DB3K/weapon/2602/)

### Magazines

as DB3K/facility/2720/

### Aircraft & Docking Facilities

None

### Sources

https://www.thedrive.com/the-war-zone/42532/chinas-massive-11-barrel-naval-gatling-gun-has-been-adapted-for-close-in-defense-on-land

![image](https://user-images.githubusercontent.com/99599482/158603582-7ae88423-c6b6-4eae-9bad-0a699b41006c.png)

**Comment by PygmalionOfCyprus** [comment]
\>China has unveiled

God, I fucking hate when The Drive does this. "China" is not an organization...

I don't think this is in service:

>Video footage of the trailer-mounted gun appeared in the run-up to Airshow China in the southern city of Zhuhai, which formally opens tomorrow and runs until October 3. The system has been developed by the NORINCO Group, a Chinese state-owned defense corporation that produces a wide array of artillery and small arms, as well as various types of munitions.

Norinco puts this sort of stuff out all the time and it rarely gets adopted. Even less likely considering the PLA already has the LD-2000. If we do get confirmation of it being picked up by the PLA, reopen the ticket.

**Comment by tbrandon517** [comment]
No worries, I figured since 7 barrel version was in ground based service then the 11 barrel might gave a good shot.
