### ISSUE TITLE
Bf.109 Fuel Issue

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#69]
### DB Selector

CWDB

### Affected DBID(s)

DB ID #s - 2415, 2416, 2417, 2418, 2419, 2420, 3841

### Summary of Changes

Messerschmitt Bf 109s and HA-1112 have a fuel burn issue at full throttle. Fuel use drop dramatically at full power.

### Sources

![E658B3EF2B044D519BD5C63A2EA3FFE6](https://user-images.githubusercontent.com/99599482/153757777-aca7f689-2736-4417-a954-27428419f1a9.gif)

**Comment by boogaboogaCMO** [comment]
Also FWIW, the really optimistic top speed of a Bf-109G would be around 350 kt.  The top speeds there (400-420 kt) are **WAY** high.

**Comment by PygmalionOfCyprus** [comment]
Fixed 496. Also dealt with an unrelated enum issue that was causing Nazi German aircraft to show up as Senegalese. 😅
