### ISSUE TITLE
City-class mine countermeasures vessel - Belgium/Netherlands

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#690]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

M 940 Oostende (Belgium), M XXX Vlissingen (Netherlands)

### Class

City-class mine countermeasures vessel

### Country

Belgium, Netherlands

### Service

Navy

### In Commission

2024-

### Length (m)

82.3m

### Beam (m)

17m

### Draft (m)

3.8m

### Standard Displacement (t)

2800

### Full Displacement (t)

not stated

### Empty Displacement (t)

not stated

### Complement

63

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

not stated

### Fuel Capacity (kg)

not stated

### Flank Speed (kt)

15.5 kts

### Range (nm) at Speed (kt)

>3500nm

### Sensors

NS50 radar by Thales, 
Sea Eagle EO/IR by Chess Dynamics, 

### Mounts

1x Bofors 40 Mk4
2× 12.7 mm FN Herstal Sea deFNder
7.62 mm MAG
LRAD Sonic Cannon

### Aircraft & Docking Facilities

Handling:
2x side gantries with floating cradle for surface drones and commando boats, a 15t rear crane and a 3t overhead crane.
1x Medium HELO Pad

Embarkation: 
capacity: 2x SOLAS rigid hull inflatable boats of 7m.

Drone capabilities: 
ECA Group’s UMISOFT System, 
2x unmanned surface vehicles (ECA Group’s Inspector 125), 
3x autonomous underwater vehicles (A-18 equipped with ECA Group’s UMISAS 120 sonar), 
2x towed sonars (T-18 equipped with ECA Group’s UMISAS 240 sonar), 
2x Mine Identification & Destruction Systems (MIDS) systems (ECA Group’s Seascan et K-Ster C), 
2x unmanned aerial vessels (UMS Skeldar’s V200), 
1x ECA Group influence dredger integrating 5 CTM magnetic modules et 1 PATRIA acoustic module.

### Comms/Datalinks

Saab TactiCall Communication System

### Ship Codes

Degaussed Steel Hull, Advanced Quieting

### Comments

Next Generation Joint Belgian-Butch MCM using a highly automated drone based MCM system.

### Sources

https://en.wikipedia.org/wiki/City-class_mine_countermeasures_vessel
https://militaryleak.com/2021/12/02/naval-group-lays-keel-for-first-mine-countermeasure-vessel-of-belgian-dutch-rmcm-program/
https://sldinfo.com/whitepapers/belgian-dutch-rmcm-program-new-mine-countermeasure-vessel/
https://www.navalnews.com/naval-news/2021/02/belgian-dutch-rmcm-program-achieved-preliminary-design-review/
https://www.navalnews.com/naval-news/2021/11/naval-group-lays-keel-of-1st-mcm-vessel-of-belgian-dutch-rmcm-program/
https://www.naval-technology.com/news/keel-laid-belgian-dutch-rmcm-vessel/
https://www.thedefensepost.com/2021/12/03/naval-group-counter-mine-vessel/

![image](https://user-images.githubusercontent.com/99599482/158605296-76962b01-c6e9-494b-a5cd-0b986ab6555f.png)
![image](https://user-images.githubusercontent.com/99599482/158606934-4f0fe808-c5a9-4119-b2ab-d309d4e6185e.png)
![image](https://user-images.githubusercontent.com/99599482/158607167-5b9bb61a-dbee-48c0-8669-d60af86277b2.png)
![image](https://user-images.githubusercontent.com/99599482/158607551-b18432e0-7880-45fe-8c0d-f537799576a8.png)
![image](https://user-images.githubusercontent.com/99599482/158607606-f07287f9-9751-409d-8e5f-05be7ced3e91.png)
![image](https://user-images.githubusercontent.com/99599482/158607668-3ed014a8-9914-4446-a541-753e7f485386.png)

**Comment by tbrandon517** [comment]
V499

**Comment by tbrandon517** [comment]
Lead ship for the Netherlands will be HNLMS Vlissingen (M840).

**Comment by tbrandon517** [comment]
France joins program

https://www.navalnews.com/naval-news/2023/10/france-joins-belgium-and-the-netherlands-for-mine-warfare-motherships/

**Comment by tbrandon517** [comment]
Dutch lead ship  M840 Vlissingen launched

https://navyrecognition.com/index.php/naval-news/naval-news-archive/2023/october/13695-dutch-navy-mine-countermeasures-vessel-vlissingen-hits-water.html

**Comment by Jkryos** [comment]
Added DB3K 505.
