### ISSUE TITLE
3237 Talash Doesn't Fire

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#692]
### DB Selector

DB3K

### Affected DBID(s)

3237

### Description of Problem

Illuminator and Search radars need to be updated. They are most definitely not Fan Song and Spoon Rest.

Illuminator not linked to missile and range isn't matching.

Caught this one while testing Kushan's scenario.

### Recommended Fix

It looks like they use a FCR similar to Mersad (MPQ-50/60 or Ofoogh 3). Google calls the MPQ-50 Copy Kavosh. Search radar is Hafez which is in the DB (check newest Mersad variant).

Googles says..Sayad 2 a copy of RIM-66. Range in DB now is very optimistic. Its likely close to the RIM-66 (60km). Sayad-3 is the follow on that seems like much greater range (120Km).

There isn't likely to be many of this. Khordad-15 (4 tube launcher) seems to have superceded it.

[https://www.secretprojects.co.uk/thread ... ams.16864/](https://www.secretprojects.co.uk/threads/iranian-made-sams.16864/)
[https://www.globalsecurity.org/military ... hordad.htm](https://www.globalsecurity.org/military/world/iran/15th-khordad.htm)
[https://www.janes.com/defence-news/news ... nous-hawks](https://www.janes.com/defence-news/news-detail/iran-uses-new-sam-with-indigenous-hawks)
[https://defense-arab.com/vb/proxy.php?i ... f37aab0cbc](https://defense-arab.com/vb/proxy.php?image=https:%2F%2Fpbs.twimg.com%2Fmedia%2FEk3FYItXEAASNOa%3Fformat%3Djpg%26name%3D900x900&hash=74507c05d7128889da5851f37aab0cbc)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Adjusted facility radar vehicles, adjusted the missile's illuminator accordingly (and gave it a SARH seeker, which it was missing), and knocked range down to 35nm.
