### ISSUE TITLE
North Korean Hind should be flagged as hypothetical

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#696]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 1383

### Summary of Changes

No changes to the platform itself, just add the hypothetical flag. Their presence is believed to have been an intel misunderstanding (see source) and no actual Korean Hinds have been displayed in parades and the like. 

### Sources

On the Path Of Songun, Mitzer and Oliemans, pages 99-100

_Reports of up to 47 Mi-24Ds reaching the DPRK stemmed from a misreporting to the US Congressional Research Service decades ago and are therefore certainly incorrect, which is not surprising given the fact that North Korean military doctrine seemed to favour lighter helicopter gunships instead._

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
