### ISSUE TITLE
Q30 Al-Mabrukah (ex-Al-Said Royal Yacht 1982-2008) Training Ship 2018-

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#697]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

Q30 Al-Mabrukah

### Class

Q30 Al-Mabrukah

### Country

Oman

### Service

Navy

### In Commission

2018-Present

### Length (m)

103.6

### Beam (m)

16.2m

### Draft (m)

5m

### Standard Displacement (t)

3300

### Full Displacement (t)

not stated

### Empty Displacement (t)

not stated

### Complement

80 as charter yacht 

### Max Sea State

not stated

### Primary Propulsion Type

Diesel

### Propulsion

 2 Detroit Diesel TA 420-6 engines

### Fuel Capacity (kg)

not stated

### Flank Speed (kt)

18 kts

### Range (nm) at Speed (kt)

not stated

### Sensors

Generic Navigation Radar

### Mounts

None

### Aircraft & Docking Facilities

1x Medium Helo Deck
2x Lifeboat Davits

### Comms/Datalinks

VHF/UHF Radio
SATCOM

### Ship Codes

Built to Mercantile Standards

### Comments

Former Royal yacht Al-Said 1982-2008, turned Loaloat Al-Behar charther yacht 2008-2018, turned Al-Mabrukah Q30 training ship 2018-Present

### Sources

https://www.thedrive.com/the-war-zone/24734/impractical-to-tactical-omani-royal-yacht-transforms-into-navy-training-vessel
https://warsearcher.com/shipsearcher/small-navies-of-the-world-great-ships/small-navies-of-the-world-auxiliaries-and-other-ships/
https://www.superyachttimes.com/yachts/al-mabrukah
https://www.superyachts.com/news/story/loaloat-al-behar-(103m-ex-royal-yacht)-to-exhibit-at-abu-dhabi-yacht-show-328/
https://en.wikipedia.org/wiki/Loaloat_Al_Behar

![image](https://user-images.githubusercontent.com/99599482/158849816-44b87e24-685a-4886-9929-da39e9a08a31.png)

**Comment by Jkryos** [comment]
Added DB3K 494.
