### ISSUE TITLE
CH-3 [Rainbow] UAV - 2016 - Turkmenistan

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#698]
### DB Selector

DB3K

### DBID to Copy

aircraft/4785/DB3K

### Hypothetical

No

### Name

CH-3 [Rainbow] UAV

### Country

Turkmenistan

### Service

Air Force

### In Commission

2016-Present

### Sensors

No Change Noted

### Mounts

No Change Noted

### Loadout Options

Turkmen CH-3's seen only with AR-1 ATGM, remove LS-6-50 loadout.

### Other Changes

None Noted

### Sources

https://www.oryxspioenkop.com/2022/01/the-last-of-many-turkmenistans-ch-3a.html
https://web.archive.org/web/20161102161902/http://www.janes.com/article/65098/military-parade-reveals-turkmenistan-s-new-chinese-built-uavs
https://www.oryxspioenkop.com/2022/02/turkmenistans-path-to-drone-power.html

![image](https://user-images.githubusercontent.com/99599482/158858946-7e3e4709-f472-4ba2-a339-69728e9fe375.png)
![image](https://user-images.githubusercontent.com/99599482/158859007-c1301997-defb-42ec-927a-b2ae2dfed4c2.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
