### ISSUE TITLE
Add Mk.53 launcher and Mk.234 Nulka Decoys to US Carriers from 2016 on

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#7]
### DB Selector

DB3K

### Affected DBID(s)

All US CVNs

### Summary of Changes

Add Mk.53 launcher and Mk.234 Nulka Decoys to US Carriers from 2016 on. Looks like Ike was the first and on port and starboard sides. Launchers are already in DB on #2397 Canberra

### Sources

https://twitter.com/ThrustWR/status/1470940245390675974
https://www.defenseworld.net/news/15143/BAE_Systems_Nulka_Decoy_Launched_From_US_Aircraft_Carrier
https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2167877/mk-53-decoy-launching-system-nulka/
https://www.lockheedmartin.com/content/dam/lockheed-martin/rms/documents/electronic-warfare/Nulka-Brochure.pdf
https://twitter.com/Alstar_tw/status/1431864599138078723
https://twitter.com/Alstar_tw/status/1431865290573312000/photo/1

**Comment by PygmalionOfCyprus** [comment]
Added 493.
