### ISSUE TITLE
A-6C TRIM LLTV Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#70]
### DB Selector

CWDB

### Affected DBID(s)

Aircraft 136 and 1241

### Summary of Changes

Add LLTV to the A-6C TRIM as sources indicate the TRIM pod used both a LLTV in addition to the IR sensors present in the current DB entry.

### Sources

https://www.thedrive.com/the-war-zone/6072/behold-the-pioneering-a-6c-intruder-with-its-massive-ventral-sensor-pod
http://www.joebaugher.com/usattack/newa6_3.html
http://tailspintopics.blogspot.com/2015/10/grumman-6c-trim.html
https://en.wikipedia.org/wiki/Grumman_A-6_Intruder#A-6C

**Comment by Jkryos** [comment]
Fixed in previous build of CWDB pre-492.
