### ISSUE TITLE
MQ-9 AIM-9X Loadout

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#703]
### DB Selector

DB3K

### User(s)

USAF MQ-9 Reapers

### Weapons Carried

2x AIM-9X Blk II

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

1600nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Seen as a replacement for Predator Stinger loadout and useful to counter cruise missile threats.

### Sources

https://www.thedrive.com/the-war-zone/36345/mq-9-reaper-howitzer-rocket-toting-f-16-all-shoot-down-mock-cruise-missiles-in-huge-test?fbclid=IwAR3Bklrao_ZlxankKLLsyE-IPSJM7hvmiTXpWlk2l9uFZI84SY9U5dJmsA4
https://www.thedrive.com/the-war-zone/23694/heat-seeking-missile-armed-mq-9-reaper-shot-down-target-drone-during-exercise
https://www.thedrive.com/the-war-zone/19122/usaf-officially-retires-mq-1-predator-while-mq-9-reaper-set-to-gain-air-to-air-missiles

![image](https://user-images.githubusercontent.com/99599482/158919525-dca900b6-64c8-4428-b8c3-5787a3c1e2fc.png)
![image](https://user-images.githubusercontent.com/99599482/158919557-f594da79-fe20-4908-aa5c-7a7c0c0a278a.png)
![image](https://user-images.githubusercontent.com/99599482/158919558-88c9f39c-d5fd-42e1-b9a5-6522e1311250.png)

**Comment by PygmalionOfCyprus** [comment]
Added for the USAF Blk 5s.
