### ISSUE TITLE
Ireland Lake Class (ex-NZ) x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#705]
### DB Selector

DB3K

### DBID to Copy

2747

### Hypothetical

No

### Name

Unknown at this time possibly LÉ Orla and LÉ Ciara

### Country

Ireland

### Service

Navy

### In Commission

2023-

### Mounts

- 2x davits for 2x 7m RHIB's

### Other Changes

- Update to radars?
- No notation on upgrade to weapons at this time

### Sources

https://www.navaltoday.com/2022/03/14/ireland-buys-two-inshore-patrol-vessels-from-new-zealand/

**Comment by Jkryos** [comment]
Added DB3K 494.
