### ISSUE TITLE
Ghana, Add: Yaa Asantewa class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#707]
### DB Selector

DB3K

### Baseline

#568, #1386

### Hypothetical

No

### Name

Patrol Boat (PB), P38, Yaa Asantewa

### Class

Yaa Asantewa (Warrior class) (Type 143B) (Albatros)

### Country

Ghana

### Service

Navy

### In Commission

2012 - present

### Length (m)

57.6

### Beam (m)

7.76

### Draft (m)

2.82

### Standard Displacement (t)

300

### Full Displacement (t)

393

### Complement

40

### Primary Propulsion Type

Diesel

### Propulsion

4x MTU 16V956 TB91, 4 shafts

### Fuel Capacity (kg)

116 t

### Flank Speed (kt)

38

### Range (nm) at Speed (kt)

2600 @ 16 (src2), 1300 @ 30 (src1)

### Sensors

1x Furuno I-band nav radar

### Mounts

1x single 20mm/90 GAM-B01
2x single 12.7mm90

### Aircraft & Docking Facilities

1x RHIB Port-Aft with small crane.

### Comments

2 units in class (ex-Bussard, Ex-Albatros).

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/ghana/gha_cf_yaa_asantewaa.htm
3: https://navyonline.mil.gh/assets/ships
![1](https://user-images.githubusercontent.com/99532490/159126723-d6288f08-545a-4436-9c39-61a115dc4f96.jpg)
![2](https://user-images.githubusercontent.com/99532490/159126725-9d06f35b-a559-427f-9e9c-b2155b8be6a9.jpg)
![3](https://user-images.githubusercontent.com/99532490/159126726-a5aeeddb-e0b4-4eba-ae80-c0cffeef3531.JPG)
![4](https://user-images.githubusercontent.com/99532490/159126728-696c3af9-a868-46b2-8f72-2320f945683e.JPG)
![5](https://user-images.githubusercontent.com/99532490/159126730-a462bcbc-8c58-4b6e-8861-a4f864ac20b1.JPG)
![6](https://user-images.githubusercontent.com/99532490/159126732-a073b2cb-df80-4212-bef8-24b9bb5d150a.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
