### ISSUE TITLE
Russia, Add: A-222 Bereg

### ISSUE THREAD

**Issue by TestPilotKerman** [PygmalionOfCyprus/cmo-db-requests#710]
### DB Selector

DB3K

### Hypothetical

No

### Name

Arty Bty, A-222 Bereg

### Facility Type

Arty

### Country

Russia

### Service

Navy

### In Commission

1988-Present

### Crew

59

### Dispersion Radius (m)

330

### Sensors

1x surface search radar, 35km range
1x optical sensor, range unspecified (backup)
1x laser rangefinder, range unspecified (backup)

### Mounts

6x 130mm gun (derived from AK-130 turret)

### Magazines

40 rounds on each mount, which may include HE, semi-armor piercing, and illumination 

### Aircraft & Docking Facilities

n/a

### Comments

This unit is used by Russian naval forces in the Black Sea fleet
Max speed 60 kph
Range 650 km
Max distance between control unit and firing unit is 1km (dispersion value provided assumes 6 firing units distributed evenly in a line 2km long with the control unit in the center)
Effective firing range 20km
Firing rate 10-14 rds/min
Mount laying angle is +/- 120 degrees
Mount elevation angle is <50 deg
Radar can track up to 4 targets and engage up to 2 simultaneously
Firing units capable of engaging static or mobile ground targets
Sources disagree about the date of the system's introduction

### Sources

https://weaponsystems.net/system/153-A-222+Bereg
https://roe.ru/eng/catalog/naval-systems/coastal-weapon-systems/bereg-e/
http://www.navyrecognition.com/index.php/news/defence-news/2017/january-2017-navy-naval-forces-defense-industry-technology-maritime-security-global-news/4800-a-222e-bereg-e-and-bal-e-modern-coastal-defense-systems-from-russia.html
http://www.military-today.com/artillery/bereg.htm

**Comment by Jkryos** [comment]
Added DB3K 505.
