### ISSUE TITLE
Kh-31A/AD for Russian Navy Su-30SM (2015, 2019). DBID: 4582, 4589.

### ISSUE THREAD

**Issue by DetlefKroeze** [PygmalionOfCyprus/cmo-db-requests#713]
### DB Selector

DB3K

### User(s)

Russian Navy Su-30SM DBID: 4582, 4589.

### Weapons Carried

2x Kh-31A (1309)
2x AA-10 Alamo A [R-27R MR TSARH] (1901)
2x AA-11 Archer [R-73M] (2053)

AND

2x Kh-31AD (1308)
2x AA-10 Alamo A [R-27R MR TSARH] (1901)
2x AA-11 Archer [R-73M] (2053)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

570

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

This would add the anti-ship variants of the Kh-31 to the Naval Aviation SU-30SM. 

### Sources

https://tass.com/defense/918614

**Comment by PygmalionOfCyprus** [comment]
Added 495.
