### ISSUE TITLE
SS-N-27 Sizzler range error

### ISSUE THREAD

**Issue by BartGauvin** [PygmalionOfCyprus/cmo-db-requests#720]
### DB Selector

DB3K

### Affected DBID(s)

2671 and several others for the SS-N-27 

### Summary of Changes

The range for the SS-N-27 is listed at 20nm (30 in some entries) but 290nm for the YJ-18 (DBID 2868).

It should be in the area of 2-300Km depending on version 

### Sources

https://en.wikipedia.org/wiki/3M-54_Kalibr
https://missilethreat.csis.org/missile/ss-n-27-sizzler/
https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/russia/ss-n-27-sizzler/
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/viewer.html?pdfurl=http%3A%2F%2Fwww.mycity-military.com%2Fuploads2%2F133284_924010280_Klub-Family.pdf&clen=540091&chunk=true

Many others

**Comment by KLABDB3K** [comment]
**There are no issues with the range of the "Sizzler" its a two stage weapon:**
The booster is not the entirety of the weapon:
#2671 - SS-N-27 Sizzler [3M54E Klub, Rocket Boosted Penetrator] range 20nm
#2670 - SS-N-27 Sizzler [3M54E Klub] range 160nm.
#3218 - SS-N-27 Sizzler [3M54T Kalibr] Range 200nm? 
#3219 - SS-N-27 Sizzler [3M54T Kalibr, Rocket Boosted Penetrator] range 20nm.
**The #3218/2670 cruise missile subsonic stage carries the #3219/2671 very high speed final stage to within the launch range of the rocket boosted high speed final stage i.e #3219/2671 which then speeds off to the target.**
The range of the exisiting entries are accurate give or take the variances in sources and export versus domestic products?
There have been errors in the DB mounts which have placed just the booster phase on the mount and not the whole weapon.
This has been raised but unfortunately is on a mount by mount basis.

**Comment by KLABDB3K** [comment]
#677 - PLA-885M Severodvinsk [Yasen] (Russia [1992-] - 2020) for example. 
![yasen error 2](https://user-images.githubusercontent.com/99494755/159183873-27015c01-e496-42f9-9fbe-79447c9a0bbf.JPG)

**Comment by KLABDB3K** [comment]
Amendment #727 refers.

**Comment by PygmalionOfCyprus** [comment]
True, but there are definitely some discrepancies; I think some of the Sizzler entries were copied from the warheads without understanding the distinction. I'll review the family.

**Comment by PygmalionOfCyprus** [comment]
Review complete; everything looks okay after all. @KLABDB3K was correct. I've now confirmed that none of the boosted penetrators are being used in any mounts; looks like the issue was isolated to #727. Fixed 494.

**Comment by BartGauvin** [comment]
Thanks guys, I'm not sure I followed everything above but it is weird that the player only sees the short range.

**Comment by PygmalionOfCyprus** [comment]
You won't see the short range anymore. 🙂

**Comment by KLABDB3K** [comment]
Much obliged again.
