### ISSUE TITLE
Add P-18-2 Prima VHF Radar 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#721]
### DB Selector

DB3K

### DBID to Copy

1653

### Hypothetical

No

### Name

Radar (Prima[P-18-2]

### Country

Russia

### Service

Army

### In Commission

2019

### Sensors

Follow on of VHF Spoonrest D. Add IFF and stat mods. More resistant to jamming and can see in more adverse weather.

Most stats stay the same if match the description file.
Up generation to late 2010s
Scan rate: 12 RPM
azimuth: 25 minimum
minimum range 500 meters
Max range 300-400km.

### Sources

Product Page
http://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/P-18-2%20%281RL131-2%29/
https://www.youtube.com/watch?v=ghEKD6_WHCQ
https://dfnc.ru/en/press-release/p-18-2-prima-radar-enters-the-foreign-market/
https://twitter.com/kmldial70/status/1258816684758097930/photo/1

General
https://www.globalsecurity.org/military/world/russia/spoon-rest-d.htm

Deployed Syria 2021. Lower left (VLF array with square IFF center)

https://twitter.com/200_zoka/status/1474741964675457026

**Comment by bostonmyk** [comment]
More pics. Looks like these at Tartus and Tiksi

https://twitter.com/halmiso1/status/1284147888642293760

**Comment by PygmalionOfCyprus** [comment]
Added 494.
