### ISSUE TITLE
Add KA-52 6 Igla UAV hunter loadouts

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#723]
### DB Selector

DB3K

### User(s)

5072, 2929,5072

### Weapons Carried

6 igla-V, 1 S-8KO rocket pod,  2 fuel tank 2 ATGM

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://twitter.com/RALee85/status/1505517431023972352/photo/1

**Comment by KLABDB3K** [comment]
#732 ref KA-52 from Ukraine footage on the same theme:
Long range option of multi-role load out as used by Russian KA-52's over Ukraine;
Six AT-16 ATGM, one rocket pod with 20 x S-8 80mm rockets and 2 x 450l fuel tanks.

**Comment by PygmalionOfCyprus** [comment]
Do the Ka-52s use 450l fuel tanks? I know the Ka-50 uses 550ls; I sort of assumed it would be the same for its two-seater sibling.

**Comment by bostonmyk** [comment]
I can't find any consistency in my google-fu. I'd match em.

**Comment by PygmalionOfCyprus** [comment]
Added 494.
