### ISSUE TITLE
#677 - PLA-885M Severodvinsk [Yasen] (Russia [1992-] - 2020) Sizzler mount entry is using wrong part of missile and wrong missile. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#727]
### DB Selector

DB3K

### Affected DBID(s)

#677 - PLA-885M Severodvinsk [Yasen] (Russia [1992-] - 2020)

### Description of Problem

#677 - PLA-885M Severodvinsk [Yasen] (Russia [1992-] - 2020)
The 1x 3R-14UKSK-Kh VLS [32 Cells, SS-N-26,27] mount has weapon records for the wrong component of the Sizzler, only the booster phase #2671 - SS-N-27 Sizzler [3M54E Klub, Rocket Boosted Penetrator]
not the full missile.  
This is also the export weapon and so the mount should be amended to the domestic version with 16 x 
#3218 - SS-N-27 Sizzler [3M54T Kalibr] (i.e the carrier for the #3219 - SS-N-27 Sizzler [3M54T Kalibr, Rocket Boosted Penetrator])

### Recommended Fix

Amend the mount with correct weapon:
16 x #3218 - SS-N-27 Sizzler [3M54T Kalibr] (i.e the carrier for the #3219 - SS-N-27 Sizzler [3M54T Kalibr, Rocket Boosted Penetrator]
![yasen error 2](https://user-images.githubusercontent.com/99494755/159184933-83f7529a-5a8a-41b3-adbd-2b7bcc879916.JPG)
![yasen error](https://user-images.githubusercontent.com/99494755/159184949-87e11e5e-b452-4150-9c5c-3856a55c9483.JPG)
)

**Comment by KLABDB3K** [comment]
Also just noticed that there is no weapon record for the **SS-N-26 Sizzler [3M53T] (16/16) -ROF:2** so its not possible to manually edit the mount weapons either.

**Comment by PygmalionOfCyprus** [comment]
Changed the weapon record to be for the proper Sizzler booster rather than the boosted penetrator itself. Also added a 16/16 weapon record for the domestic Sizzler and gave it to the Severodvinsk.
