### ISSUE TITLE
MICA NG name, confusing

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#728]
### DB Selector

DB3K

### Affected DBID(s)

3861 MICA NG, 3862 MICA NG

### Summary of Changes

The  MICA NG's name in the DB doesn't mention its type, and is thus confusing while looked through the game's interface, since one doesn't know which is which.[^1]

### DataWeapon

3861 | MICA NG (2024, ARH)
--- | ---
- [x] Name = MICA EM NG

3862 | MICA NG (2024, IR)
--- | ---
- [x] Name = MICA IR NG

### Sources

![Capture d’écran 2022-03-21 041115](https://user-images.githubusercontent.com/35732829/159201654-77693ec6-b344-4b29-b394-8c238b99b47e.jpg)
![Capture d’écran 2022-03-21 041304](https://user-images.githubusercontent.com/35732829/159201668-cd987a3d-bcc4-41e1-9a4e-49fc0f2de6d7.jpg)

![image](https://user-images.githubusercontent.com/35732829/159201251-1c61e066-008e-4690-b423-043b91690d2e.png)

https://www.defense.gouv.fr/sites/default/files/ministere-armees/Fiche%20LPM%20-%20Mica%20NG%20%28missile%20nouvelle%20g%C3%A9n%C3%A9ration%29.pdf

_MICA NG_ means Missiles d’interception, de combat et d’autodéfense – Nouvelle Génération
_EM_ means électromagnétique

[^1]: [Rafale C issue with the MICA NG missile - Matrix Games Forums](https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=381481)

**Comment by PygmalionOfCyprus** [comment]
My bad. This was marked in the "hidden" comments so us DB gurus could see it but not actual users. Have edited the names as per your suggestion.
