### ISSUE TITLE
MIM-104F Patriot PAC-3 ERINT/MSE Active Radar Seeker Band Actually Operates in Ka-Band

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#729]
### DB Selector

DB3K

### Affected DBID(s)

1715

### Summary of Changes

#1715 - Active Radar Seeker (Sensor), only used by weapon #1150 and #3207

The operating band is currently NATO I-band (corresponding to IEEE X-band), but out of all classified information about the PAC-3 missile, the seeker is publicly stated to be a Ka-band seeker. This corresponds to NATO K-band. 

 
![PatriotARHSeeker](https://user-images.githubusercontent.com/99858862/159243604-e2e48e9a-22b0-4c0d-bb3a-ba271caf3946.PNG)

### Sources

[Lockheed Martin Official News Site](https://news.lockheedmartin.com/2004-03-04-Lockheed-Martins-PAC-3-Missile-Successfully-Intercepts-Tactical-Ballistic-Missile-in-Test) --- 4 March, 2004

"Other test objectives of the mission included demonstrating the PAC-3 Missile Segment software and ground system improvements, demonstrating system capability to intercept and kill a short-range, full-body TBM target, and demonstrating and validating successful operation of the PAC-3 Missile seeker with a domestic source Traveling Wave Tube, the Ka-band radar seeker's high power amplifier. Preliminary data indicate that all objectives were achieved."

---------------------------------------------------------------------------------------------------------------------------------------------

[Defense Technical Information Center, document approved for public release](https://apps.dtic.mil/sti/pdfs/ADA319957.pdf) --- 7 Jan, 1997 (.pdf)

"Missile components being tested include:: The PAC-3 seeker, an active Ka-Band, coherent, range-gated pulse Doppler radar capable of operation in high acceleration environments."

--- pg. 10-4

---------------------------------------------------------------------------------------------------------------------------------------------

[Center for Strategic and International Studies](https://missilethreat.csis.org/system/patriot/) --- 30 June, 2021

"The PAC-3 also features a active Ka-band radar seeker for endgame guidance."

---------------------------------------------------------------------------------------------------------------------------------------------

[GlobalSecurity.org](https://www.globalsecurity.org/space/systems/patriot-ac-3.htm) --- 8 January, 2016

"Shortly before arrival at the intercept point, the PAC-3 Missile's on board Ka band seeker acquires the target, selects the optimal aim point and terminal guidance is initiated."

---------------------------------------------------------------------------------------------------------------------------------------------

[SkyBow](https://en.wikipedia.org/wiki/Sky_Bow)

Wikipedia Entry on the SkyBow III Development --- cited 2006 Taiwan Defense Review, but I'm unable to obtain the original source.

"Taiwan officials asked for U.S. technical support for Taiwan's indigenous anti-tactical ballistic missile (ATBM) effort, including the transfer of Hit-to-Kill (HTK) technologies, specifically those related to an active radar Ka-band seeker and precision attitude control. CSIST was reported to had sought the release of the associated [traveling-wave tube](https://en.wikipedia.org/wiki/Traveling-wave_tube) (TWT) transmitter of the Ka-band active radar seeker technology. However, U.S. refusal of the export release of a complete Ka-band active radar seeker without tamper protection or to provide the TWT on a stand-alone basis, forced CSIST to use a different active radar seeker technology with a little European content."

Mei, Fu S. "Retaining Missile Defense Focus," Taiwan Defense Review, March 27, 2006.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
