### ISSUE TITLE
JF-17 missing mandatory datalink for PL-15E

### ISSUE THREAD

**Issue by Matharox** [PygmalionOfCyprus/cmo-db-requests#73]
### DB Selector

DB3K

### Affected DBID(s)

4827 4828

### Description of Problem

Aircraft have PL-15E loadout but cannot fire them because they don't have the datalink for it 

### Recommended Fix

Give them PL-15 Weapon Link

**Comment by Jkryos** [comment]
Fixed DB3K 493.
