### ISSUE TITLE
EU_US engine specs (Thrust, SFC, Name)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#730]
### DB Selector

DB3K

### Affected DBID(s)

See below

### Summary of Changes

Hey there, I would like to suggest various modifications to make the data of these engines match the figures of their manufacturer or reliable references. This is the Atlantic cousin of the #684 

Let me know how you think I could improve the format of such a report, with that many entries.

### DataPropulsion
---

| #    | Name                     |
|------|--------------------------|
| 41  | 2x T56-A-427 |
| 1985  | 2x T56-A-427A |
- [x] SFCMilitary = 0.47

| #    | Name                     |
|------|--------------------------|
| 269  | 2x SNECMA M88-2/3/4 |
| 2405  | 2x SNECMA M88-2/3/4 |
- [x] SFCAfterburner = 1.66

| 273  | 1x Atar 8K-50 |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 5000.0

| 341  | 1x Atar 8B |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 4400.0
- [x] ThrustPerEngineAfterburner = 0.0
- [x] SFCAfterburner = 0.0
<kbd>Reason : this is a non-afterburning engine.</kbd>

| #    | Name                     |
|------|--------------------------|
| 351  | 1x M53-5 |
| 1970  | 1x M53-5 |
| 2406  | 1x M53-5 |
- [x] ThrustPerEngineAfterburner = 9000.0

| #    | Name                     |
|------|--------------------------|
| 355  | 2x T406-AD-400 |
| 711  | 2x T406-AD-400 |
| 1722  | 2x T406-AD-400 |
| 1986  | 2x T406-AD-400 |
| 2481  | 2x T406-AD-400 |
- [x] SFCMilitary = 0.48
<kbd>_0.424_ is at Max continuous power (static 1,219 m; 4,000 ft. 4,362 shp), not Max power (S/L) [^1]</kbd>

| 357  | 2x Tyne RTy.20 Mk.21 |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 6100.0

| 371  | 2x Adour RT.172 Mk.102 |
| ------------- | ------------- |
- [x] ThrustPerEngineAfterburner = 3315.0

| 500  | 2x Turmo IVC |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 1560.0

| 592  | 1x RM8B |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 7250.0
- [x] ThrustPerEngineAfterburner = 12746.0
- [x] SFCMilitary = 0.64
- [x] SFCAfterburner = 2.52

| 656  | 2x Larzac 04-C5 |
| ------------- | ------------- |
- [x] Name = Larzac 04-C20
- [x] ThrustPerEngineMilitary = 1440.0
- [x] SFCMilitary = 0.74
<kbd>Reason : Larzac 04-C6 is the baseline engine for Alpha Jet. From 1985, the Larzac 04-C20 becomes the standard equipment of the jets. I thus recommend changing its name as a good enough solution.</kbd>

| 674  | 2x Adour RT.172 Mk.104 |
| ------------- | ------------- |
- [x] ThrustPerEngineAfterburner = 3585.0

| #    | Name                     |
|------|--------------------------|
| 741  | 2x F100-PW-229 |
| 745  | 1x F100-PW-229 |
| 1591  | 2x F100-PW-229 |
| 2123  | 1x F100-PW-229 |
- [x] SFCAfterburner = 1.94

| #    | Name                     |
|------|--------------------------|
| 744  | 1x F110-GE-129 |
| 1887  | 1x F110-GE-129 |
| 1912  | 2x F110-GE-129 |
| 1957  | 1x F110-GE-129 |
- [x] ThrustPerEngineMilitary = 7720.0
- [x] ThrustPerEngineAfterburner = 13154.0
- [x] SFCMilitary = 0.64
- [x] SFCAfterburner = 1.74

| 796  | 2x PW123C|
| ------------- | ------------- |
- ThrustPerEngineMilitary = 2262.0

| 831  | 2x T56-A-425 |
| ------------- | ------------- |
- [x] SFCMilitary = 0.54
	
| 867  | 2x PW120 |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 2100.0

| 1040  | 3x Turmo IIIC5 |
| ------------- | ------------- |
- [x] Name = Turmo IIIC5 [WZ6]
- [x] ThrustPerEngineMilitary = 1408.0
- [x] SFCMilitary = 0.632
<kbd>Reason : WZ6 is the Chinese licensed version, used by the Z-8, the Chinese version of the Super Frelon.</kbd>

| #    | Name                     |
| ------------- | ------------- |
| 1466  | 4x T56-A-7 |
| 1558  | 4x T56-A-7A |
| 2159 | 4x T56-A-7A |
| 2270  | 4x T56-A-7 |
- [x] ThrustPerEngineMilitary = 3755.0

| #    | Name                     |
| ------------- | ------------- |
| 1461  | 1x M53-P2 |
| 1971  | 1x M53-P2 |
| 1972  | 1x M53-P2 |
| 2407  | 1x M53-P2 |
- [x] ThrustPerEngineMilitary = 6800.0
- [x] ThrustPerEngineAfterburner = 9700.0

| 1501  | 2x Adour RT.172 Mk.106 |
| ------------- | ------------- |
- [x] ThrustPerEngineAfterburner = 3942.0

| #    | Name                     |
|------|--------------------------|
| 1515  | 1x RM8A |
| 2264  | 1x RM8A |
- [x] ThrustPerEngineMilitary = 6690.0
- [x] ThrustPerEngineAfterburner = 11789.0
- [x] SFCMilitary = 0.63
- [x] SFCAfterburner = 2.47

| 1559  | 4x T56-A-10W |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 4180.0
- [x] SFCMilitary = 0.528

| 1739  | 2x PW127E		|
| ------------- | ------------- |
- ThrustPerEngineMilitary = 2516.0
- SFCMilitary = 0.474

| 1740  | 2x PW124B|
| ------------- | ------------- |
- ThrustPerEngineMilitary = 2626.0
- SFCMilitary = 0.468

| #    | Name                     |
|------|--------------------------|
| 1741  | 2x PW127		|
| 1738  | 2x PW127F |
| 1744  | 2x PW127F		|
| 2974  | 2x PW127J |
- ThrustPerEngineMilitary = 2880.0
- SFCMilitary = 0.459

| 1742  | 2x PW121|
| ------------- | ------------- |
- ThrustPerEngineMilitary = 2252.0
- SFCMilitary = 0.477

| 1743  | 2x PW121|
| ------------- | ------------- |
- Name = PW121A
- ThrustPerEngineMilitary = 2304.0
- SFCMilitary = 0.474
<kbd>Reason : that version have been certified in 1995. The platforms using it are commissioned in 2000 and 2009. I thus assume that they would be equiped with the most recent engine version.</kbd>

| #    | Name                     |
|------|--------------------------|
| 1944  | 2x PW127G		|
| 2119  | 2x PW127G |
- ThrustPerEngineMilitary = 3549.0
- SFCMilitary = 0.453

| 1945  | 2x PW125B|
| ------------- | ------------- |
- ThrustPerEngineMilitary = 2522.0
- SFCMilitary = 0.463

| 1976  | 4x T56-A-9 |
| ------------- | ------------- |
- [x] ThrustPerEngineMilitary = 3460.0
- [x] SFCMilitary = 0.54

| 2465  | 2x PW123B|
| ------------- | ------------- |
- SFCMilitary = 0.463

| 2466  | 2x PW150A|
| ------------- | ------------- |
- ThrustPerEngineMilitary = 5492.0
- SFCMilitary = 0.433

| 2676  | 2x Turmo IV |
| ------------- | ------------- |
- [x] SFCMilitary = 0.632

| 3230  | 2x PW127M		|
| ------------- | ------------- |
- ThrustPerEngineMilitary = 2619.0
- SFCMilitary = 0.459

### Sources

[^1]: Jane's Aero-Engines issue 11
Lasserre, Michel. "Un demi-siècle d’aéronautique en France : les moteurs". Centre des hautes études de l’armement, 2005.
Roux, Élodie. "Réacteurs simple et double flux : données caractéristiques", Les Editions Elodie Roux, 2007.

<details>
<summary>Click to open the URL box</summary>

https://web.archive.org/web/20100815090254/http://www.pw.utc.com/Products/Military/F100
https://web.archive.org/web/20210302010834/https://www.safran-aircraft-engines.com/military-engines/training-and-combat-aircraft/larzac
https://web.archive.org/web/20210218224331/https://www.safran-aircraft-engines.com/military-engines/training-and-combat-aircraft/m88
https://asmedigitalcollection.asme.org/GT/proceedings/GT1990/79054/Brussels,%20Belgium/240937 T406 Engine Development Program
https://www.easa.europa.eu/sites/default/files/dfu/EASA%20IM.E.041%20TCDS%20Issue%204.pdf PW100 series engines
</details>

**Comment by PygmalionOfCyprus** [comment]
Format is fine! You don't need to create separate tasks for every data point, though: just a separate task per-engine is fine.

**Comment by Jkryos** [comment]
Updated DB3K 494.
