### ISSUE TITLE
AN/ALQ-55 is a Communication Jammer, not a DECM

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#731]
### DB Selector

Both

### Affected DBID(s)

308, 946

### Summary of Changes

I found this out after I realized that one DECM that operates only in the B-band, which resulted in it having no use in the game. 

AN/ALQ-55 is a communication disruptor. I can see why there is a confusion, one of them is probably stemmed from the USN training film, which placed the AN/ALQ-55 under the DECM concept along with ALQ-35, 41, 51. However, the standalone system doesn't operate as a DECM. 

DB3K ID: 308
CWDB ID: 946

---------------------------------------------------------------------------------------------------------------------------------------------

In-Game Evidence:

DB3K:
![ALQ55DECMMistake](https://user-images.githubusercontent.com/99858862/159271305-056a93ef-8991-49cf-a990-2ecc1af09d47.PNG)

CWDB:
![CWDBALQ55Mistake](https://user-images.githubusercontent.com/99858862/159271595-6d7c875b-8b04-4081-b203-506990ccb214.PNG)

### Sources

[Standard Aircraft Characteristics Archive](http://www.alternatewars.com/SAC/EA-6A_Prowler_SAC_-_1_July_1967.pdf) (.pdf, scanned official declassified document) --- 1 July, 1967

![SACALQ55](https://user-images.githubusercontent.com/99858862/159271149-3ed6e469-b891-408d-8901-72e250225bb4.PNG)

--- pg. 3

---------------------------------------------------------------------------------------------------------------------------------------------

[United States Department of Defense Media](https://media.defense.gov/2011/Mar/23/2001330092/-1/-1/0/AFD-110323-034.pdf) (.pdf, official declassified document) --- 16 August, 1977

Under "Jamming Enemy Communications" Section

"Despite the problems, EB-66rs, along with Navy and Marine Corps planes carrying AN/ALQ-92 or AN/ALQ-55 transmitters, made occasional attempts to disrupt enemy communications."

--- pg. 64

---------------------------------------------------------------------------------------------------------------------------------------------

[United States Navy Training Film](https://archive.org/details/MN-9705) (video) --- Originally released in 1962, Archived by Internet Archive organization in 2014

Timestamp of Interest:

03:53
05:37
14:05

---------------------------------------------------------------------------------------------------------------------------------------------

[Designation-Systems.Net](http://www.designation-systems.info/usmilav/jetds/an-alq2aly.html) --- Last Updated: 9 October, 2007

"VHF Data-Link Jammer; manufactured by Sanders; used in A-3, RA-5C, EA-6A"

Relevant Entries:

"AN/ALQ-59 | VHF Data Link Jamming System (USAF version of AN/ALQ-55, developed from QRC-128); manufactured by Hallicrafters; used in F-105F, B-52, EB-66"

"AN/ALQ-92 | A-Band Communications Jamming System (modified AN/ALQ-55); manufactured by Sanders; used in EKA-3B, EA-6B" 

---------------------------------------------------------------------------------------------------------------------------------------------

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Wonder if these were intended to jam SA-2/3 datalinks; that'd explain its lumping under "DECM". Its pretty narrowly focused for a dedicated comms jammer.
