### ISSUE TITLE
Ka-52K Hokum B [Katran] Naval version load outs amendments suggestions. (It has two less pylons than the land version)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#732]
### DB Selector

DB3K

### Affected DBID(s)

#2930 - Ka-52K Hokum B [Katran] (Russia [1992-] - 2016) #5073 - Ka-52K Hokum B [Katran] (Egypt - 2018)

### Summary of Changes

The Katran version has folding wings for carrier storage and **only two pylons** per wing **not the three of land version**.

KA-52K Naval version with 4 pylons.
![KA52K PYLONS](https://user-images.githubusercontent.com/99494755/159361147-2d2a21d4-d751-4c87-a716-119a63b05f07.jpg)

KA-52 Land version 6 pylons:
![KA52 PYLONS](https://user-images.githubusercontent.com/99494755/159361451-66958161-21dc-4a4c-9a65-5957269d50db.jpg)

So the load outs as follows which are shared with the land version would not be possible in the Naval version.
#15679 is inaccurate as Katran could not also carry Igla or Verba AAM.
#15675 etc
#15676 etc
#15677 etc
#15678 etc (Could be scrapped as 57mm S-5 rockets were phased out of use in RuAF)

Suggest copy and replace above load outs with:
BAI/CAS
AT-16 Scallion [9M127 Vikhr], S-8KO 80mm Rockets (BAI/CAS) 12 x Vikhr 20 x S-8 only
AT-9 Spiral-2 [9M120 Ataka-V], S-8KO 80mm Rockets (BAI/CAS) 12 x Ataka 20 x S-8 only
S-13B 122mm Rockets (BAI/CAS) 20 x S-13 rockets only.
S-8KO 80mm Rockets (BAI/CAS) 80 x S-8 rockets only.
_S-5K 57mm Rockets (BAI/CAS)_ Could be scrapped as 57mm rockets are not in use.

Create additional load outs of:
BAI/ATA
AT-16 Scallion, Igla-V - 12 x Vikhr 4 x Igla-V (or Verba-V?)
AT-9 Spiral 2, Igla-V - 12 x Ataka, 4 x Igla-V
S-13 10 Rockets and 4 Igla
S-8 40 Rockets and 4 Igla
S-5 64 Rockets and 4 Igla

BAI/CAS Long range
AT-16 x 12 2 x 450l fuel tanks.
AT-9 x 12 2 x 450l fuel tanks.
S-13 (10) & S-8 (40) rockets and 2 x 450l fuel tanks.
And a long range option of multi-role load out for both land and naval versions which has been used by Russian KA-52's over Ukraine;
AT-16 x 6, S-8 x 20 2 x 450l fuel tanks. 
![KA-52 LONG RNAGE](https://user-images.githubusercontent.com/99494755/159361740-d699641e-dc4a-43c3-8775-a4cc763f8463.JPG) * This could be applied to land or naval version if Igla-v omitted?

Based on:
The inner pylons can carry:
1 x APU-6 with 6 x AT-16 Scallion Vikhr (9M127-1) ATGM
or 
1 x APU-6 with 6 x AT-9 Spiral II (Ataka 9M-120-1 ATGM)
or 
1 x Rocket pod for each of 5 x S-13 122mm / or 20 x S-8 80mm rockets.
or
1 x Fuel tank 450L

The outer pylons can carry:
1 x Rocket pod for each of 5 x S-13 122mm / or 20 x S-8 80mm rockets. 
or
1 x Fuel tank 450L
or 
2 x Verba or Igla-V 

### Sources

https://wallup.net/kamov-ka-52-alligator-russian-red-star-russia-helicopter-aircraft-attack-military-arm-36/

https://www.airliners.net/photo/Russia-Navy/Kamov-Ka-52K-Katran/5509635

https://twitter.com/qretaxyeta/status/1454408659535028224/photo/1

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.

**Comment by KLABDB3K** [comment]
It is very good of you to indulge my OCD about pylons! 😁
