### ISSUE TITLE
Russian submarine mast mounts have not been updated with recent MANPADS such as Igla-S or Verba? SA-N-8 Gremlin is old tec?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#733]
### DB Selector

DB3K

### Affected DBID(s)

All Russian SSN/SSK/SSBN etc with mast mounts for MANPADS. 

### Summary of Changes

Russias latest submarines are still using the SA-N-8 Gremlin mast mount.

#2693 - SA-N-24 Grinch [9M342] Igla-S has almost universally supplanted the old SA-N-8 in the mast mounts of Russian subs, the mast mounts are also highly likely to also accept the Verba MANPADS as the design features common mountings.
It appears no Russian sub of recent years has a compatible recent mast launcher for a current MANPAD which is unlikely given the commonality of the systems and elapsed time?

### Sources

DB3K

**Comment by PygmalionOfCyprus** [comment]
Do we know from what year (roughly) the SA-N-8s were replaced with the -24s? If so we can quickly fix this by running a mass update of all Russian submarines with that particular mount and with an in-service date equalling or greater than that year.

**Comment by KLABDB3K** [comment]
Its a good point, definitive dates are evasive. I will do more research. Simply from a maintenance and support point of view its unlikely brand new subs would have old Gremlins. I will look for a list of subs refitted in the past decade rather than drip feed dates.

**Comment by PygmalionOfCyprus** [comment]
Awesome. Yeah, if you drop us either a list of DBIDs or selectors ("all Russian subs w/ IS >2007" or whatever) we can make this happen. 🙂

**Comment by KLABDB3K** [comment]
There's an element of copy and paste in the entries from Janes. From a supply maintenance and servicing point of view the Gremlins are literally museum peices, there is one in the artillery museum in St Petersburg by example.

**Comment by PygmalionOfCyprus** [comment]
Janes has my utmost respect and I will forever love them dearly, but it wouldn't be the first time I've caught them in an error. Nobody's perfect!

**Comment by KLABDB3K** [comment]
This is Pandoras box, I'm still checking! 😁 My plan is to check each type in the DB3K and pick the most likely revision point so its a case of just updating an existing entry with a new SA-N-24? mount rather than a new entry.

**Comment by claudejdev** [comment]
In Conway's All the World's Fighting Ships 1947-1995 :
![image](https://user-images.githubusercontent.com/35732829/159927834-20de6d47-3f55-49ae-b389-fb10e73612c6.png)
![image](https://user-images.githubusercontent.com/35732829/159928330-3b62ff4c-08a5-476b-b91d-f1995ed63d66.png)
![image](https://user-images.githubusercontent.com/35732829/159928683-95a8cdd4-1cf3-4838-8dc6-30b113a126de.png)

**Comment by KLABDB3K** [comment]
I am going with the following as a safe point with 2005 being the ball park point at which Igla-S would have started to supplant the Igla and either the Igla-1 or Igla would have largely superseded the SA-N-8 Strela 3 which was circulating since 1974.
So all the following should have at least the SA-N-10 and or a SA-N-24 hybrid launcher capable of launching both? 
#508 - PL-636.3 Kilo [Varshavyanka] (Russia [1992-] - 2014)
#622 - PLA-671RTMK Victor III [Shchuka] (Russia [1992-] - 2005)
#621 - PLA-671RTMK Victor III [Shchuka] (Russia [1992-] - 2017)
#405 - PLA-885 Severodvinsk [Yasen] (Russia [1992-] - 2012)
#677 - PLA-885M Severodvinsk [Yasen] (Russia [1992-] - 2020)
#623 - PLA-971 Akula I [Shchuka-B] (Russia [1992-] - 2005)
#624 - PLA-971 Akula I Improved [Shchuka-B] (Russia [1992-] - 2005)
#625 - PLA-971M Akula II [Shchuka-B] (Russia [1992-] - 2005)
#626 - PLARK-949A Oscar II [Antey] (Russia [1992-] - 2005)
#568 - PLARK-949AM Oscar III [Antey] (Russia [1992-] - 2018)
#647 - PLASN-9852 [Belgorod] (Russia [1992-] - 2018)
#674 - Pr.545 ‘Laika’ (Russia [1992-] - 2027) -- HYPOTHETICAL UNIT
http://russianships.info/eng/submarines/project_877.htm
KILO
http://russianships.info/eng/submarines/project_677.htm
Lada
http://russianships.info/eng/submarines/project_941.htm
Typhoon
http://russianships.info/eng/submarines/project_955.htm
Borei 
http://russianships.info/eng/submarines/project_945.htm
Sierra III Pr.945A Kondor
http://russianships.info/eng/submarines/project_971.htm
Alkula /Shchuka / Irbis from 2011 onwards refitted. 
http://russianships.info/eng/submarines/project_941.htm
Typhoon / Alkula
http://russianships.info/eng/submarines/project_949.htm
Oscar from 1989

#508 - PL-636.3 Kilo [Varshavyanka] (Russia [1992-] - 2014)
#622 - PLA-671RTMK Victor III [Shchuka] (Russia [1992-] - 2005)
#621 - PLA-671RTMK Victor III [Shchuka] (Russia [1992-] - 2017)
#405 - PLA-885 Severodvinsk [Yasen] (Russia [1992-] - 2012)
#677 - PLA-885M Severodvinsk [Yasen] (Russia [1992-] - 2020)
#623 - PLA-971 Akula I [Shchuka-B] (Russia [1992-] - 2005)
#624 - PLA-971 Akula I Improved [Shchuka-B] (Russia [1992-] - 2005)
#625 - PLA-971M Akula II [Shchuka-B] (Russia [1992-] - 2005)
#626 - PLARK-949A Oscar II [Antey] (Russia [1992-] - 2005)
#568 - PLARK-949AM Oscar III [Antey] (Russia [1992-] - 2018)
#647 - PLASN-9852 [Belgorod] (Russia [1992-] - 2018)
#674 - Pr.545 ‘Laika’ (Russia [1992-] - 2027) -- HYPOTHETICAL UNIT

**Comment by PygmalionOfCyprus** [comment]
You know, you have to wonder...

...do you think they bothered?

Like, honestly, I know we're here talking about how it just makes sense that they'd give their subs their fancy new MANPAD missiles, but...it's 2022. If your SSN is launching Iglas at aircraft something has gone comically wrong. I could see those mast launchers basically being abandonware at this point.

**Comment by KLABDB3K** [comment]
Yes agreed totally on reflection, and the effort is not worth the gain. 
I am sceptical that the SSN SSGN etc Yasen Borey etc even have them or that a "mast launcher" is anything but a pressurised storage container for a manually aimed shoulder fired weapon for security when the boats are going into port as in the export KILO. that could be added by the scenario designer or via LUA . 
Anything SSN is never going to surface in the presence of ASW anyway! Unless its got a critical injury.

**Comment by PygmalionOfCyprus** [comment]
Agreed.

Okay, I hate to do this after you went and did all the digging, but it sounds like we're calling this wontfix then pending concrete evidence of a AA upgrade in the Russian sub fleet?

**Comment by KLABDB3K** [comment]
Agree, the effort isn't worth it for something that will never be used.
