### ISSUE TITLE
Beechcraft C-12J Huron

### ISSUE THREAD

**Issue by HudsonCW** [PygmalionOfCyprus/cmo-db-requests#736]
### DB Selector

DB3K

### Baseline

Super King Air 200T

### Hypothetical

No

### Name

C-12J Huron

### Country

United States

### Service

US Army/US Air Force

### In Commission

1992

### Length (m)

17.63

### Wingspan (m)

16.61

### Height (m)

4.6

### Empty Weight (kg)

3518

### Maximum Takeoff Weight (MTOW) (kg)

7579.5

### Crew

2

### Propulsion

x2 P&W PT6A-65B

### Service Ceiling (ft)

25,000

### Military/Afterburner Speed (kt)

284

### Cruise Speed (kt)

260

### Supercruise

No

### Ferry Range (nm)

1450

### Fuel Capacity (kg)

2033

### Sensors

GPS
Mk1 Eyeball
Generic Nav Radar

### Mounts

N/A

### Loadout Options

- 19 Passengers
or 
- 3500 Lb Cargo

### Comms/Datalinks

HF Radio (Secure)
UHF Radio (Secure)
VHF Radio (Secure)

### Sources

https://en.wikipedia.org/wiki/Beechcraft_C-12_Huron
https://www.yokota.af.mil/About-Us/Fact-Sheets/Display/Article/410687/c-12-huron/

**Comment by Jkryos** [comment]
Added DB3K 506.
