### ISSUE TITLE
Typhoon, Spain, Meteor with Litening pod

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#737]
### DB Selector

DB3K

### User(s)

# 3229 - EF2000 Eurofighter Typhoon [C.16A] (Spain - 2021)

### Weapons Carried

- 2x # 961 - Meteor
- 2x # 963 - 1000 liter Drop Tank
- 2x # 1129 - AIM-2000A IRIS-T
- 1x # 1293 - Litening III/EF Pod [FLIR + LRMTS, 40k ft]

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Name = A/A: Meteor, Litening III/EF Pod [FLIR], Intercept
LoadoutRole = 2003

That loadout is interesting because it's easy on the supplies and, thanks to its Litening Pod, offers a long range Visual ID capability.
It have been seen over Romania in 2021 (Destacamento PAZNIC), and now over Bulgaria (Strela).

### Sources

![51051971308_4651b5878a_k](https://user-images.githubusercontent.com/35732829/159588590-0014e846-313f-4517-acf7-eb4367c90c45.jpg)
https://www.flickr.com/photos/ejercitoaire/51052783592/in/album-72157683191341721/
https://www.flickr.com/photos/ejercitoaire/albums/72157718206809006/page2
https://emad.defensa.gob.es/operaciones/operaciones-en-el-exterior/36-OTAN-eAP-Rumania/

![image](https://user-images.githubusercontent.com/35732829/159590391-f7ad85f0-f9cc-4594-a94b-85912e60fbec.png)
https://twitter.com/NATO_AIRCOM/status/1506253194556583942
https://emad.defensa.gob.es/operaciones/operaciones-en-el-exterior/37-OTAN-eAP-Bulgaria/

**Comment by Huib18** [comment]
The first photo is with AMRAAMs, the second picture with Meteor missiles.

**Comment by Jkryos** [comment]
Added DB3K 494.
