### ISSUE TITLE
MQ-8CFire-X ASW Loadout

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#738]
### DB Selector

DB3K

### User(s)

MQ-8C DBID 4031

### Weapons Carried

2x ASW Pods (24x Sonobouys)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

~ 175nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Projected ASW Loadout for MQ-8C as part of a manned/Unmanned Teaming with MH-60R. Up to 48x sonobuoys of types consistent with the MH-60R and/or MQ-9B.

### Sources

https://www.thedrive.com/the-war-zone/38691/submarine-hunting-kit-will-let-mq-8c-fire-scout-drone-helicopters-launch-sonobuoys?fbclid=IwAR1j4WHdOp24gm3y1ZxProXcsl-pRFM6myxyTPCKDUxoEpwRTyU3QpOBdD8

https://www.defenceconnect.com.au/maritime-antisub/7569-northrop-grumman-demonstrates-asw-capability-of-mq-8c-fire-scout

https://www.naval-technology.com/features/fire-scout-asw/

https://www.janes.com/defence-news/news-detail/northrop-grumman-touts-fire-scout-uas-for-shipborne-asw

https://www.shephardmedia.com/news/uv-online/flexibility-fire-scout-applied-asw-fight-studio/

https://aviationweek.com/defense-space/sensors-electronic-warfare/northrop-ultra-eye-advance-production-mq-8c-asw-kit

![image](https://user-images.githubusercontent.com/99599482/159596169-0e3ab387-4308-47c0-b5c6-8432b0338ba7.png)

![image](https://user-images.githubusercontent.com/99599482/159596217-62cfc831-3abc-4fe7-bb4a-c6e3fff6db79.png)

**Comment by PygmalionOfCyprus** [comment]
Added 495.
