### ISSUE TITLE
EMARSS Name Update

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#739]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5464, 5465, 5466, 5482

### Summary of Changes

Update designation to MC-12S. Recommend Names as

MC-12S EMARSS-G [King Air 350ER MEK]

MC-12S EMARSS-M [King Air 350ER MEK]

MC-12S EMARSS-S [King Air 350ER MEK]

MC-12S EMARSS-V [King Air 350ER MEK]

### Sources

https://www.thedrive.com/the-war-zone/15305/the-armys-latest-spy-planes-are-flying-hundreds-of-hours-overseas

https://en.wikipedia.org/wiki/Beechcraft_C-12_Huron#King_Air_350-based_variants

https://en.wikipedia.org/wiki/EMARSS

https://www.thedrive.com/the-war-zone/8443/the-u-s-armys-newest-spy-plane-is-in-action-in-africa-and-latin-america

https://www.thedrive.com/the-war-zone/8752/yet-another-version-of-the-u-s-armys-new-spy-plane-appears-in-arizona

**Comment by Jkryos** [comment]
Updated DB3K 494.
