### ISSUE TITLE
Israeli Sa'ar 6 Corvettes should be using Barak 8

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#740]
### DB Selector

DB3K

### Affected DBID(s)

3224

### Summary of Changes

Israeli Navy Sa'ar 6 corvettes use Barak 8 SAMs, not Barak 1. Tried using editor to give them Barak 8s, but they also need the datalink.

### Sources

https://www.idf.il/en/minisites/israeli-navy/meet-the-new-sa-ar-6-ships/

**Comment by PygmalionOfCyprus** [comment]
601 Magen already has Barak 8s in my DB; this may have been ninja'ed or fixed in 493. Didn't have the datalink though, so that's now been added for 494!
