### ISSUE TITLE
RAN ANZAC Post AMCAP

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#741]
### DB Selector

DB3K

### Affected DBID(s)

3290, potentially earlier

### Summary of Changes

AMCAP ANZAC's as currently modeled have a misaligned CEAFAR radar face.
![ANZAC](https://user-images.githubusercontent.com/101542189/159610781-651522c6-d637-4e07-a364-78f46e782978.jpg)
Looking at ANZAC herself, the mast has a face directly on 90 and 270 degrees, with the remaining four in between at 30, 150, 210 and 330.
![ANZAC Face 1](https://user-images.githubusercontent.com/101542189/159611042-dab0ecc9-2df9-4ca9-9a93-4bb0f32569ed.PNG)
CMO thinks that there is a face at 0 degrees. The earlier ASMD ANZAC has the correct layout
![ASMD ANZAC](https://user-images.githubusercontent.com/101542189/159612065-468e5ea0-3d28-4036-b739-23f896bb340d.PNG)
Also the AMCAP upgrade kept the original CEAFAR radars and added CEAFAR2-Ls on top, but in CMO they only have the 2-Ls. Doesn't really affect much, just an accuracy thing.

Other sensor issues include the ANZACs having Kelvin Hughes Sharp Eyes, not Atlas 9600. They were added in the ASMD upgrade. They also have a Thales Petrel mine detection sonar according to the Navy's site.
In addition, ANZACs have 2 davits for RHIBS, port and starboard, not one as currently modeled. Earlier picture shows starboard, this one shows port for ANZAC.
![ANZAC P](https://user-images.githubusercontent.com/101542189/159613507-54153ad7-1839-4d3f-8261-72a843fab9ec.jpg)

In terms of weapons, some of the ANZACs now have Mk 45 Mod 4 guns, not the original Mod 2s. For instance this is Warramunga (L) and Perth (C), showing the difference between the 2.
![Ships Guns](https://user-images.githubusercontent.com/101542189/159613576-50d5e247-9846-4464-ab44-582c095106f4.jpg)
I have no idea when the guns were added because some of the ships have Mod 4 even pre-ASMD (see above), while others like Perth still don't have them post-AMCAP.

### Sources

https://www.navy.gov.au/hmas-anzac-iii

**Comment by PygmalionOfCyprus** [comment]
Fixed all for 494. Added the Petrel from 2006 as that's around when they were being passed out (first installation 2005, final 2008). In lieu of more detailed info about the introduction of the Mod 4 guns I've just replaced the Mod 2s on everything from ASMD up. Mounts can always be tweaked in-game if necessary.
