### ISSUE TITLE
Canberra Class LHD A/C capacity

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#742]
### DB Selector

DB3K

### Affected DBID(s)

2397

### Summary of Changes

Despite the Canberra's being mostly identical to the Juan Carlos and the Anadolu, the Canberra's can load clos to three times the number of aircraft. This is due to their open parking being a 22x Large A/C, while the Juan Carlos has a 6x medium.
![Canberra Parking](https://user-images.githubusercontent.com/101542189/159623404-d07772d4-1c37-4e27-ab0a-bf588e84ffad.PNG)
![Juan Carlos Parking](https://user-images.githubusercontent.com/101542189/159623419-c8aedad5-b425-4de6-9a2f-0e66672e9b39.PNG)
This means I can load 45 MRH-90s onto a Canberra, far more than the 18 on a Juan Carlos and almost as many as onto a Wasp (57). Navy figures put it at 18 medium aircraft, like the Juan Carlos.
 

### Sources

https://www.navy.gov.au/fleet/ships-boats-craft/lhd

**Comment by Jkryos** [comment]
Fixed DB3K 494.
