### ISSUE TITLE
Chinese-Type-928C Inshore Patrol Boats

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#748]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

Type-928C Inshore Patrol Boats (Type-928-YC for Bolivia)

### Class

Type-928C

### Country

China, Bolivia

### Service

Army (PRC), Navy (Bolivia)

### In Commission

~2019

### Length (m)

13.2m

### Beam (m)

3.24m

### Draft (m)

1.3m

### Standard Displacement (t)

Not Stated

### Full Displacement (t)

Not Stated

### Empty Displacement (t)

Not Stated

### Complement

~3

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2 x 440hp Diesels

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

33.3 kts

### Range (nm) at Speed (kt)

Not Stated

### Sensors

2x Generic Navigation Radars

### Mounts

1x crew-served machine gun on forward deck, crew weapons

### Aircraft & Docking Facilities

None Stated

### Comms/Datalinks

VHF/UHF Radios

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

A patrol boat built by Changzhou FRP Shipyard Co, this boat yard specializes in GRP (glass reinforced plastic) boats. the Type-928C is deployed alongside the assault boat variant. They do not use the same hull. 23 PAX capacity.

### Sources

http://www.hisutton.com/Chinese-Type-928D-Assault-Boat.html
https://en.wikipedia.org/wiki/Type_928_assault_boat
https://inf.news/en/military/82a1dab1b8ae810089b5fee8687bb539.html
https://twitter.com/indopac_info/status/1307951612313313281

![image](https://user-images.githubusercontent.com/99599482/159706012-9aeda2e5-67b7-4d27-bb74-e82fd8ae1566.png)
![image](https://user-images.githubusercontent.com/99599482/159706083-5af2cb43-c73a-4764-8540-0eb70c3f2401.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
