### ISSUE TITLE
Add Colombian Air Force AC-47 and AC-47T Fantasma gunships

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#75]
### DB Selector

DB3K

### Hypothetical

No

### Name

AC-47 and AC-47T Fantasma

### Country

Colombia

### Service

Air Force

### In Commission

1987-Present

### Length (m)

19.63 m for AC-47, 20.54 for AC-47T

### Wingspan (m)

28.96 m

### Height (m)

5.16 m

### Empty Weight (kg)

8,201 kg

### Maximum Takeoff Weight (MTOW) (kg)

14,969 kg

### Crew

7

### Propulsion

2 × Pratt & Whitney R-1830 Twin Wasp 14-cylinder air-cooled radial piston engines, 1,200 hp (890 kW) each (AC-47)

### Rate of Climb (ft/min)

1052.63

### Service Ceiling (ft)

24,450 ft

### Military/Afterburner Speed (kt)

200 kn

### Cruise Speed (kt)

152 kn

### Supercruise

No

### Ferry Range (nm)

3,100 nmi

### Endurance (min)

420 

### Takeoff / Landing Distance (m)

488/762

### Fuel Capacity (kg)

2350.74

### Sensors

AC-47
mk 1 eyeball
T-33 gunsight for aiming

AC-47T 1993+
mk 1 eyeball
Star Safire sensor turret

AC-47T 1997+
mk 1 eyeball
Star Safire sensor turret
NVGs

AC-47T Current
mk 1 eyeball
BRITE Star II sensor turret
NVGs

### Mounts

AC-47 Colombia (Air Force) 1987
3x single barrel Browning M2 12.7mm/.50 caliber machine guns

AC-47T Fantasma --Colombia (Air Force) 1993-1997, 3 .50 cal
3x three-barreled .50-caliber GAU-19/A Gatling-type machine guns

AC-47T Fantasma --Colombia (Air Force) 1993-1997, 2 .50 cal, 1 20mm
2x three-barreled .50-caliber GAU-19/A Gatling-type machine guns
1x French-made 20mm-caliber GIAT M621 cannon

AC-47T Fantasma --Colombia (Air Force) 1997-?, 3 .50 cal, NVG's
3x three-barreled .50-caliber GAU-19/A Gatling-type machine guns

AC-47T Fantasma --Colombia (Air Force) 1997-?, 2 .50 cal, 1 20mm, NVG's
2x three-barreled .50-caliber GAU-19/A Gatling-type machine guns
1x French-made 20mm-caliber GIAT M621 cannon

AC-47T Fantasma --Colombia (Air Force) ?+, 3 .50 cal, NVG's, Brite Star II, SATCOM
3x three-barreled .50-caliber GAU-19/A Gatling-type machine guns

AC-47T Fantasma --Colombia (Air Force) ?+, 2 .50 cal, 1 20mm, NVG's, Brite Star II, SATCOM
2x three-barreled .50-caliber GAU-19/A Gatling-type machine guns
1x French-made 20mm-caliber GIAT M621 cannon

### Loadout Options

Illumination Flairs

### Comms/Datalinks

AC-47
UHF unsecure
VHF Unsecure

AC-47T 
UHF Secure
VHF Secure

AC-47T at present
UHF Secure
VHF Secure
SATCOM
GPS

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Basic

### Comments

AC-47 Fantasma --Colombia (Air Force) 1987-1994
Original 5 AC-47 acquired/converted in the 1987 from standard C-47 configuration, 1 lost in 1988. Armament consisted of three (3) single barrel Browning 12.8mm/.50 caliber machine guns rather than the 7.62mm miniguns used in Vietnam. Other equipment included illumination flares and a sight from a T-33 to assist aiming.

AC-47T Fantasma --Colombia (Air Force) 1993-1997, 3 .50 cal
AC-47T Fantasma --Colombia (Air Force) 1993-1997, 2 .50 cal, 1 20mm
AC-47T Fantasma --Colombia (Air Force) 1997-?, 3 .50 cal, NVG's
AC-47T Fantasma --Colombia (Air Force) 1997-?, 2 .50 cal, 1 20mm, NVG's
AC-47T Fantasma --Colombia (Air Force) ?+, 3 .50 cal, NVG's, Brite Star II, SATCOM
AC-47T Fantasma --Colombia (Air Force) ?+, 2 .50 cal, 1 20mm, NVG's, Brite Star II, SATCOM
Updated to AC-47T configuration from 1993/4 based on BT-67 conversions, 9 converted, 3 lost. Twin Wasp radials were replaced by Pratt & Whitney PT6A-67R turboprops to improve high altitude performance. Fuselage lengthened by three feet to maintain COG with new engines. Star Safire sensor turret and upgraded communications gear installed. Night Vision Goggles for crew since 1997. Able to operate as a Forward Air Controller-Armed or Airborne Command Post. Armament upgraded and is either three (3) three-barreled .50-caliber GAU-19/A Gatling-type machine guns or two (2) three-barreled .50-caliber GAU-19/A Gatling-type machine guns and one (1) French-made 20mm-caliber GIAT M621 cannon, used to defeat hardened targets. Other improvements included countermeasure chaff and flare dispensers. The FLIR turret was later updated to a BRITE Star II unit offering improved definition, and the communications suite now includes satellite communications and GPS.

### Sources

https://www.thedrive.com/the-war-zone/39236/theres-one-place-in-the-world-where-ac-47-spooky-gunships-still-fly
https://warisboring.com/colombias-ac-47t-fantasmas-are-still-going-strong/

![download](https://user-images.githubusercontent.com/99599482/154355597-135f5e7a-90d1-451f-b516-d7dc9cb0bc36.jpg)

![download](https://user-images.githubusercontent.com/99599482/154355614-4ec67f16-794a-4908-83df-a690bd04e702.jpg)

![download](https://user-images.githubusercontent.com/99599482/154355631-e7304407-b6c1-4bba-9d19-71dc28811f25.jpg)

![download](https://user-images.githubusercontent.com/99599482/154355654-a6a1ac5b-8ea0-4b38-a7b2-1cff93f97dea.jpg)

![images](https://user-images.githubusercontent.com/99599482/154355758-9e9afc6d-ffeb-4a9c-9733-fe3db1034331.jpg)

**Comment by Jkryos** [comment]
Added DB3K 501.
