### ISSUE TITLE
WD-1K Wing Loong [Pterodactyl] I UAV - 2021, Ethiopia

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#750]
### DB Selector

DB3K

### DBID to Copy

aircraft/3310/DB3K

### Hypothetical

No

### Name

WD-1K Wing Loong [Pterodactyl] I UAV - 2021, Ethiopia

### Country

Ethiopia

### Service

Air Force

### In Commission

2021-

### Sensors

No Change

### Mounts

No Change

### Loadout Options

Exchange armed loadout from

2x HJ-10 for PRC

to 

2x TL-2 Skythunder ATGM DBID #3488 for Ethiopia

### Other Changes

None Stated

### Sources

https://www.oryxspioenkop.com/2021/10/wing-loong-is-over-ethiopia-chinese.html
https://www.oryxspioenkop.com/2021/10/from-mohajer-6s-to-wing-loong-is.html
https://www.oryxspioenkop.com/2021/10/tigray-war-chinese-made-armed-drones.html
https://www.oryxspioenkop.com/2021/11/ethiopia-acquires-chinese-tl-2-missiles.html
https://www.oryxspioenkop.com/2021/11/deadly-ineffective-chinese-made-wing.html
https://www.oryxspioenkop.com/2021/11/satellite-images-show-ethiopias.html
https://www.oryxspioenkop.com/2021/11/unfit-for-service-ethiopias-troublesome.html
https://www.oryxspioenkop.com/2021/12/new-drone-infrastructure-emerges-at.html?m=1&fbclid=IwAR1gOIdkWstxGmfNkwJsuuAdPb8Fgbvb1BSv1xDpVshl-J1QPGlThDoo86U

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also added the TL-2 loadout to the Chinese version, because, you know. They can probably use their own weapons on their own aircraft.
