### ISSUE TITLE
B-26N Invader [Night Fighter] - France

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#751]
### DB Selector

CWDB

### DBID to Copy

aircraft/754/CWDB

### Hypothetical

No

### Name

B-26N Invader [Night Fighter]

### Country

France

### Service

Air Force

### In Commission

1961-1962, Possibly to 1965 as trainers

### Sensors

1x British Mk. X air intercept radar from Gloster Meteor NF.11s

### Mounts

remove 2x twin .50 cal turrets.

### Loadout Options

Each B-26N carried 2 weapon pods under each wing, 

2x Gun Pods each housing a pair of Browning .50 caliber machine guns (probably match the built in twin .50 mount)

2x 68mm SNEB rocket pods with 19 rockets each.

### Other Changes

8x A/B-26C Invaders converted by the French to Night Fighters to combat smugglers supporting Algerian rebel forces.

### Sources

https://www.thedrive.com/the-war-zone/9767/france-turned-the-b-26-invader-into-a-colonial-night-fighter
http://www.passionpourlaviation.fr/tag/ecn-171/
http://worldatwar.net/chandelle/v3/v3n1/frcoin.html
http://www.joebaugher.com/usattack/a26_14.html
https://www.airvectors.net/ava26.html (indicated trainer use until 1965)
https://books.google.com/books?id=M_oA_b92XK8C&pg=PA406&lpg=PA406&dq=B-26N+Night+Fighter&source=bl&ots=63SwTKL-hh&sig=ACfU3U2q_Z6VhkstZzqSVWS625FmwmEEUg&hl=en&sa=X&ved=2ahUKEwiaqpL20tz2AhW2jIkEHdlwDNcQ6AF6BAg1EAM#v=onepage&q=B-26N%20Night%20Fighter&f=false

![image](https://user-images.githubusercontent.com/99599482/159746109-ec22810a-43e6-4c9d-af9f-4803ec326c10.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
