### ISSUE TITLE
SSBN 734 Tennessee [Ohio Class] - 2021, Trident D5, 4 VLS Tubes Deactivated, Large Vertical Array

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#752]
### DB Selector

DB3K

### Affected DBID(s)

aircraft/754/DB3K

### Summary of Changes

USS Tennessee received the new Large Vertical Array flank sonar intended for other SSBN's and Block V Virgina Class SSNs. 

### Sources

https://www.thedrive.com/the-war-zone/41452/bulges-on-ballistic-missile-submarine-uss-tennessee-after-refit-point-to-new-flank-sonar-array
https://news.usni.org/2016/03/28/submarines-to-become-stealthier-through-acoustic-superiority-upgrades-operational-concepts
https://www.autoblog.com/2014/10/27/us-navy-update-submarine-sonar-stealth-abilities/
https://www.wbparts.com/rfq/5845-01-633-3749.html
https://www.wearethemighty.com/mighty-trending/the-us-navy-just-launched-an-effort-to-built-this-is-the-super-stealthy-submarine/

![image](https://user-images.githubusercontent.com/99599482/159754091-7a5b8708-ea10-43cb-8668-287911fb9a12.png)

**Comment by PygmalionOfCyprus** [comment]
On hold re: D's comment on PygmalionOfCyprus/cmo-db-dev#282

**Comment by PygmalionOfCyprus** [comment]
Added as one of the final additions to 494. (Also added the VLA to the Blk V Virginias; other subs will get them as they get them.) Sim-side update to support schema will probably lag behind the DB release.
