### ISSUE TITLE
Raptor [Pr.03160] --Russia [1992] (Navy), 2015 Fast Patrol Boat/Landing Boat

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#753]
### DB Selector

DB3K

### Baseline

#3467 - Stridsbat 90H [CB90] (Sweden - 1990)

### Hypothetical

No

### Name

Raptor [Pr.03160] --Russia [1992] (Navy), 2014 Fast Patrol Boat

### Class

Raptor

### Country

Russia

### Service

Navy FSB Border guard

### In Commission

March 2015 for in service 

### Length (m)

17

### Beam (m)

4.1

### Draft (m)

0.9

### Standard Displacement (t)

28t

### Complement

2 Crew 20 Pax - Landing party

### Max Sea State

5

### Primary Propulsion Type

Diesel

### Propulsion

2 × C18 ACERT "Caterpillar" diesel engine, producing 845 kilowatts (1,133 hp) each, 2 Kamewa 36A3 HS waterjet*

### Flank Speed (kt)

48

### Range (nm) at Speed (kt)

300 @ 20kts

### Sensors

1x Generic Navigation radar
EO/TV System on bridge roof with near 360 gimballed mount, 
14.5mm RCW's has additional EO/TV sighting system and Thermal imager channel with dual stabilisation.

### Mounts

1 x 14.5mm UKSS "Uprava-Kord remote control weapon station" EO/TV/Thermal sighting stabilised. centre amidships with 360 rotation obstructed by mast to rear as per image. 
https://www.c4defence.com/en/new-weapon-to-russian-boats/
2 x pintle mounted 7.62mm MG Port and starboard manually aimed. 
![RAPTOR PCI](https://user-images.githubusercontent.com/99494755/159750309-3a6a56d8-3e9a-4016-889a-eb65932b8833.JPG)

### Aircraft & Docking Facilities

Nil. Would be capable of being housed in most LPD/LHA well docks etc. 

### Comms/Datalinks

VHF/HF Secure radios.
GPS/GLONASS nav system.

### Ship Codes

Passive or Single Stabilizers

### Comments

1. Marginally bigger than the Swedish CB-90 from which it is evidently derived, 
2. Is armoured overall to Level 5 7.62mm x 54 etc
3. Status of imported diesel engines and water jets is unclear.
4. Production started circa 2012-13 but actual acceptance to service was circa 2015. 
5. The Ukrava-Kord UKSS has a dual axis stabilization system and integrated electro-optic (EO) unit. This platform also allows for the integration of the EO station with a separate gyro-stabilized EO station whic enables enabling image stabilization to be enhanced to a higher level. The system is 1,000 millimeters high. Platform has a radius of rotation of 1355 millimeters and has an elevation angle of -20 to +80 degrees. RCWS' traverse angle is 200 degree. Uprava-Kord RCWS has EO module, a thermal imager, a wide-angle colour day camera and a variety of focusing equipment and laser markers. In addition to these systems, the system can be integrated with an automatic target tracking system and a ballistic computer depending on the user's request, allowing the integration of a 14.5 mm KPVT heavy machine gun, a 12.7 mm Kord or a 7.62 mm PKT machine gun. The RCWS can also engage aerial targets flying at low altitude. **Uprava-Kord is being used with KPVT in Project 03160 class boats and with Kord machine gun in Project 12150 class boats.**

### Sources

https://en.topwar.ru/170290-stroitelstvo-patrulnyh-katerov-pr-03160-raptor.html
https://www.naval-technology.com/projects/raptor-project-03160-high-speed-patrol-boat/
http://www.pellaship.ru/images/ref_list/03160-709.jpg
https://mil.in.ua/en/news/the-russians-confirm-the-damage-to-the-raptor-class-boat-near-mariupol/ One less. 
https://www.c4defence.com/en/new-weapon-to-russian-boats/
https://en.wikipedia.org/wiki/Raptor-class_patrol_boat

**Comment by tbrandon517** [comment]
Additional Sources/Images

http://www.hisutton.com/Naval_Capabilities-Sea_of_Azov.html
http://www.hisutton.com/Russian%20Assault%20Boats%20head%20to%20Syria.html
http://www.hisutton.com/Ru_Raptor_2018-04.html
http://www.hisutton.com/Russian%20Raptor%20SF%20assault%20boats%20arrive%20in%20Black%20Sea.html

**Comment by PygmalionOfCyprus** [comment]
Added 495. At the rate things are going I'm going to need to update the out-of-service date before the DB even releases...
