### ISSUE TITLE
Ukraine - Project 58181 Centaur Class Armored Assault Boat

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#760]
### DB Selector

DB3K

### Baseline

Uncertain

### Hypothetical

No

### Name

Project 58181 Centaur Class Armored Assault Boat

### Class

Project 58181 Centaur Class Armored Assault Boat

### Country

Ukraine

### Service

Navy

### In Commission

2018

### Length (m)

24.3m

### Beam (m)

4.8m

### Draft (m)

1m

### Standard Displacement (t)

Not Stated

### Full Displacement (t)

47

### Empty Displacement (t)

Not Stated

### Complement

5-6

### Max Sea State

Not Stated

### Primary Propulsion Type

Diesel

### Propulsion

2x diesel engines coupled to 2x waterjets.

### Fuel Capacity (kg)

Not Stated

### Flank Speed (kt)

35 kts, 35+ kts, 50 kts depending on source 

### Range (nm) at Speed (kt)

>500nm @ 11 knts

### Sensors

Laser Warning System
An optoelectronic monitoring system 
1x Furuno DRS4D-NX solid-state pulse compression doppler radar

### Mounts

2x RWS with 2x stations for 12.7 mm machine guns and/or 40 mm rocket (grenade?) launchers. 
3x SFP-20 steerable banks of 50mm smoke dischargers
1x turret with 2x S-8 80mm rocket pods for fire support.

### Aircraft & Docking Facilities

None

### Comms/Datalinks

VHF/UHF Radio
SATCOM

### Comments

A hybrid of Ukraine’s stereotypical Armored Artillery Boat concept (i.e. Gurza type)and the Swedish Assault Boat concept (i.e. CB90). The type combines the armor and the firepower of the artillery boat with the high performance, robust build and bow ramp for troops of the assault boat. The resulting boat is much larger than other assault boats, but packs a formidable punch. They are designed to patrol rivers and coastal areas.

32 PAX Capacity

### Sources

http://www.hisutton.com/Centaur_assault_boat.html
http://www.hisutton.com/Naval_Capabilities-Sea_of_Azov.html
https://www.usni.org/magazines/proceedings/2018/december/combat-fleets
https://www.navaltoday.com/2018/09/17/ukraine-launches-first-centaur-class-assault-boat/
https://www.naval-technology.com/projects/centaur-class-fast-assault-craft/
https://en.wikipedia.org/wiki/Centaur-class_fast_assault_craft

![image](https://user-images.githubusercontent.com/99599482/159775672-44321c14-09c0-4a2b-a6ae-fc221d53d16c.png)
![image](https://user-images.githubusercontent.com/99599482/159775686-52ed265a-5f01-4010-87f8-867c9bd798f6.png)
![image](https://user-images.githubusercontent.com/99599482/159777011-293a4c48-4a0a-4571-ac44-07d439946dec.png)
![image](https://user-images.githubusercontent.com/99599482/159778069-c237ea04-38d6-443c-9ce2-67ae27c01048.png)

**Comment by PygmalionOfCyprus** [comment]
Handled 502.

**Comment by tbrandon517** [comment]
@PygmalionOfCyprus can the 40mm GL be added to the RWS along with the HMG?

**Comment by PygmalionOfCyprus** [comment]
Fixed 503.
