### ISSUE TITLE
Chilean Navy out of service Dates for #1792 and #1702

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#761]
### DB Selector

DB3K

### Affected DBID(s)

Ship 1792 and 1702

### Summary of Changes

#1796 FFG 14 Almirante Latorre [Jacob Van Heeenskerk]frigates retired 2019 and #1702 LM 36 Requelme [Type 148] all 4 retired by 2015

### Sources

https://en.wikipedia.org/wiki/List_of_decommissioned_ships_of_the_Chilean_Navy
https://www.navalnews.com/naval-news/2020/04/ex-ran-adelaide-class-frigates-commissioned-with-the-chilean-navy/

**Comment by Jkryos** [comment]
Updated DB3K 494.
