### ISSUE TITLE
Add Romanian Gepard SPAAG 2005

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#762]
### DB Selector

DB3K

### DBID to Copy

Facility 67

### Hypothetical

No

### Name

(AAA Sec 35mm Twin Gepard)

### Country

Romania

### Service

Army

### In Commission

2005

### Sources

https://twitter.com/gepardtatze/status/1321390398296727553
https://en.wikipedia.org/wiki/File:Romanian_Gepard_SPAAGs_during_the_Romanian_National_Day_military_parade.jpg
Sipri DB Line
: Romania	(36)	Gepard	SPAAG	1998	2004-2009	(36)	Second-hand; $37 m aid; modernized before delivery; 7 more for spare part only

**Comment by PygmalionOfCyprus** [comment]
Added 494.
