### ISSUE TITLE
Chinese DF-21D causing game breaking freeze.

### ISSUE THREAD

**Issue by HudsonCW** [PygmalionOfCyprus/cmo-db-requests#763]
### DB Selector

DB3K

### Affected DBID(s)

2106 (DF-21D)

### Description of Problem

Game stops running when MIRV reaches roughly 63ft ASL on re-entry and requires a restart, tested multiple times w/ 100% reproduction. Other ballistic missiles were tested (DF-21C #89, DF-15 #367, etc) without being able to reproduce the problem with 2106. Deleting the MIRV does not unfreeze the Sim.

**Comment by PygmalionOfCyprus** [comment]
Closing since this isn't a DB issue -- something weird sim-side. If it's not fixed and you haven't already please post in the Tech Support forum.
