### ISSUE TITLE
Add EO/IR guidance to Khaji Fars ASBM 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#765]
### DB Selector

DB3K

### Affected DBID(s)

2393, 2394

### Summary of Changes

Add EO (like Walleye) and IIR (like maverick)seeker

### Sources

Take a look at the nose cones.  Oryx is reliable as well.
https://www.oryxspioenkop.com/2019/10/the-oryx-handbook-of-iranian-ballistic.html
https://www.groundreport.com/wp-content/uploads/2014/09/6_920328_L600.jpg
https://postlmg.cc/DJ96bqSB

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
