### ISSUE TITLE
Croatia Cetina (Silba) Class LCT/ML x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#766]
### DB Selector

DB3K

### DBID to Copy

1291 DB3K

### Hypothetical

No

### Name

DBM 81 Cetina

### Country

Croatia

### Service

Navy

### In Commission

1993-

### Sensors

- 1x Racal Decca 1290A - I Band (Surface Search)

### Mounts

DBM-81 Cetina
- 2x AK-230 mounted on side (1 each)
- 1x 20mm M-75 on stern
- 1x MTU-4 9K32M Strela-2M (SA-N-5or7 Grail)
DBM-82 Krka
- 1x Bofors 40mm/70 (bow mounted)
- 1x MTU-4 9K32M Strela-2M (SA-N-5or7 Grail)
- 2x Hispano 20mm M71 mounted on side (1 each)

### Other Changes

- Roll-on/roll-off design with two loading ramps located on the bow and the stern
- Two ships, second entry details noted above
- Cetina: two mine rails, can be used to carry up to 152 different naval mines, six medium tanks or 300 troops with equipment, a total cargo capacity of 460 t (450 long tons)
- Krka: two mine rails, can be used to carry up to 114 different naval mines, six medium tanks or 300 troops with equipment, a total cargo capacity of 460 t (450 long tons), also completed as an auxiliary water carrier with a capacity of around 230 t (230 long tons) of fresh water

### Sources

Janes 2003-04, Pg 160
https://en.wikipedia.org/wiki/Silba-class_landing_ship-minelayer
https://hr.wikipedia.org/wiki/DBM-81_Cetina
https://hr.wikipedia.org/wiki/DBM-82_Krka

![HRM_Krka_82_170909](https://user-images.githubusercontent.com/99632305/159804770-f6f461c4-8b3b-4448-a827-8ef302630dae.jpg)

**Comment by claudejdev** [comment]
Piggybacking here : 
from an old suggestion I sent a few while ago, on the forum.

- [ ] DBM 241 Silba
|1291 | DBM 241 Silba -- Yugoslavia [-1992] (Navy) , 1991-0, -|
|------|------|
- Height to 5.4m
- Cargo_Type to #4000 Large Cargo, Cargo_Mass to 460

Note : secondary role as a minelayer, the ship can carry up to 152 mines. As of 2007, it seems to have been abandonned. Maybe transferred to Montenegro.

### Sources
[PALUBA - Jugoslovenska Ratna Mornaric - Desantni Brod Minopolagač tipa DBM-241](http://www.paluba.info/smf/index.php/topic,3047.0.html)
[OSRH - Ships and combat systems HRM](http://www.osrh.hr/#rubData/HTML/HR/RAZNO/NAORU%C5%BDANJE/20150521_Brodovi_i_borbeni_sustavi_HRM_v2/Brodovi_i_borbeni_sustavi_HRM_HR.htm)
[OSRH - Flota HRM](http://www.osrh.hr/#rubData/HTML/HR/O%20NAMA/HRM/05_20191120_Flota_HRM/Flota_HRM_HR.htm)

**Comment by PygmalionOfCyprus** [comment]
Added 494 (as well as Claude's tweaks).
