### ISSUE TITLE
Croatia Helsinki Class Missile Boat x4 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#767]
### DB Selector

DB3K

### DBID to Copy

1297 DB3K

### Hypothetical

No

### Name

RTOP 41 Vukovar

### Country

Croatia

### Service

Navy

### In Commission

2009-

### Sensors

- Raytheon 9GA208 and 9LV225 radars
- EOS-400 e/o system
- SS304
- SONAC-PTA towed sonar (instead of 1 x 4 RBS-15SF SSM)
- Argo ECM suite
- 2x Philax decoy RL
- 9LV Mk 2.3 CCS

### Mounts

- 2x 4 RBS-15SF SSM (8 RBS-15SF3)
- 2x 6 Sako SAM (12 Mistral) or 2 x 2 - 23/87 Sako
- 1 x 1 - 57/70 Bofors SAK-1
- 2 DCR (6)
- or mines instead of SSMs and DCRs

### Other Changes

- ex Finland Helsinki class Oulu and Kotka
- Aluminium hull

### Sources

Janes 2003-04 Page 209
http://www.navypedia.org/ships/croatia/cro_cf_vukovar.htm
https://hr.wikipedia.org/wiki/RTOP-41_Vukovar
https://hr.wikipedia.org/wiki/RTOP-42_Dubrovnik

![375px-RTOP-41_Vukovar](https://user-images.githubusercontent.com/99632305/159807863-664f0c45-dff8-4632-aaab-6fc08732ec3e.jpg)
![RTOP_Vukovar_42_c_170909](https://user-images.githubusercontent.com/99632305/159807893-afe960e5-fa4b-49a5-a4e8-f7e0be45fda9.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
