### ISSUE TITLE
KJ-1 Radar

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#77]
### DB Selector

Both

### Hypothetical

Yes

### Name

KJ-1 Radar

### Sensor Generation

Late 1960s

### Sensor Capabilities

Air Search, Surface Search, Range Information, Altitude Information, Speed Information, Heading Information

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm

### Scan Interval (s)

10

### Target Altitude (ft)

1500 feet AGL/45000 feet ASL

### Comments

Mounted on a rotodome in the KJ-1 AEW (in Aircraft issue request). As it's an AEW plane, the actual radar is essential. 

For range (translated):
According to Chinese sources, during the flight test program, during which the prototype aircraft flew several hundred hours, it was empirically determined that the radio-technical complex installed on the KJ-1 ensures the detection and tracking of medium-sized air targets at an altitude of 1500 m at a distance of up to 220 km, at an altitude of 1000 m - at a distance of 208 km, at an altitude of 500 m - at a distance of 200 km, and small targets at an altitude of 10,000 m - at a distance of up to 269 km.

During the tests, the H-6 bomber (the Chinese version of the Soviet Tu-16 jet bomber) imitating a high-altitude target was detected by the radar, according to Chinese sources, at a distance of 300-350 km. A low-flying target coming from the sea was imitated by a transport aircraft, its radar detected at a distance of up to 250 km. Evaluation tests were also carried out to detect a surface target, which, as the Chinese note, "were confidently detected at a distance of up to 300 km."

### Sources

http://www.airwar.ru/enc/spy/hh2.html (In Russian)

**Comment by PygmalionOfCyprus** [comment]
Handled 509.
