### ISSUE TITLE
Cuba Sonya Class (Pr.1265) MSC/MH x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#771]
### DB Selector

DB3K

### DBID to Copy

1981 DB3k

### Hypothetical

No

### Name

570

### Country

Cuba

### Service

Navy

### In Commission

1985-

### Sensors

- 1x Navigation Radar Don 2 - I band
- IFF: 2 Square Head, High pole B
- Sonars: MG 89 hull mounted, active mine-hunting, high frequency, MG-7 Braslet Sonars

### Mounts

- 2x 30mm/70 (twin) AL-230M
- 2x 25mm/82 (twin) 2M-3M
- 1x 4 Strela-3 SAM (16 9M36)
- mines x 8 (GKT-2 mechanical, AT-2 acoustic or PEMT-4 magnetic, AT-2 acoustic or ST-2 magnetic)
- AT-2 acoustic minesweeping gear or IT-3 USV or 2x 200m mine clearance line charges

### Other Changes

- generic mechanical cable cutter mine sweep
- generic magnetic & acoustic mine sweep

### Sources

Janes 2003-2004, pg 162
http://www.navypedia.org/ships/cuba/cub_ms_560.htm
https://en.wikipedia.org/wiki/Sonya-class_minesweeper
http://russianships.info/eng/warships/project_1265.htm

![«Герман_Угрюмов»1](https://user-images.githubusercontent.com/99632305/159832368-6977d127-4d6b-4656-8dc8-2655dec40c24.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fill #458

**Comment by PygmalionOfCyprus** [comment]
Added as DBID 3501, fixing #458.
