### ISSUE TITLE
Cuba Yevgenya  Class (Pr.1258/E) MHC

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#772]
### DB Selector

DB3K

### DBID to Copy

2917 DB3k

### Hypothetical

No

### Name

510

### Country

Cuba

### Service

Navy

### In Commission

1977

### Sensors

- Kivach radar
- MG-7 Braslet sonar

### Loadout Options

- 1x 2 - 25/112 2M-3M
- 1x 7 - 55 MRG-1 GL
- 2 DCR (12)
- IT-1 Neva-1 USV or MT-3U or OPT-1 mechanical or SEMT-1 magnetic or AT-2 acoustic minesweeping gear

### Sources

http://www.navypedia.org/ships/cuba/cub_ms_501.htm
https://en.wikipedia.org/wiki/Yevgenya-class_minesweeper
http://russianships.info/eng/warships/project_1258.htm

![Caspian_boat_207](https://user-images.githubusercontent.com/99632305/159840625-ada130ee-1fb9-4181-af3b-83b81dd7e3e6.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fill #459

**Comment by PygmalionOfCyprus** [comment]
Added as DBID 3509, fixing #458.
