### ISSUE TITLE
Denmark SSK Näcken (A-14) Class

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#773]
### DB Selector

DB3K

### DBID to Copy

175

### Hypothetical

No

### Name

Kronborg

### Country

Denmark

### Service

Navy

### In Commission

2001-2005

### Sensors

None noted

### Mounts

None noted

### Loadout Options

None noted

### Sources

http://www.navalhistory.dk/English/TheShips/K/Kronborg(2001).htm
https://en.wikipedia.org/wiki/N%C3%A4cken-class_submarine
Janes 2003-04, pg166

![KRONBORG_ubaad](https://user-images.githubusercontent.com/99632305/159845581-b47218b5-ce02-489d-ace7-af92caf5e39e.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
