### ISSUE TITLE
Ecuador 512-1152 Class LST

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#774]
### DB Selector

DB3K

### DBID to Copy

1242 DB3k

### Hypothetical

No

### Name

TR 61 Hualcopo

### Country

Ecuador

### Service

Navy

### In Commission

1977-2007

### Sources

https://en.wikipedia.org/wiki/USS_Summit_County_(LST-1146)
Janes 2003-04, pg 184

![ecu_ls72](https://user-images.githubusercontent.com/99632305/159849359-41a3bddc-291e-42fa-b478-514e3b1b0e1b.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.

**Comment by PygmalionOfCyprus** [comment]
Added 494.
