### ISSUE TITLE
Please add Al-Quwaisat-class LST for UAE Navy

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#775]
### DB Selector

DB3K

### Hypothetical

No

### Name

A81 Al-Quwaisat

### Class

Al-Quwaisat class LST

### Country

UAE

### Service

Navy

### In Commission

2013

### Length (m)

80

### Beam (m)

16.8

### Draft (m)

4

### Standard Displacement (t)

2046

### Full Displacement (t)

3469

### Complement

106

### Max Sea State

6

### Primary Propulsion Type

Diesel

### Propulsion

2x Cummins KTA50-M2 CODAD

### Fuel Capacity (kg)

680640

### Flank Speed (kt)

14

### Range (nm) at Speed (kt)

2500nm @ 12 Knot

### Sensors

1x generic navigation radar

### Mounts

4x Aselsan STAMP RWS

### Aircraft & Docking Facilities

1x davit for 7m RHIB
1x Pad for Medium Helicopter

### Comms/Datalinks

generic SATCOM
VHF Radio
UHF Radio

### Ship Codes

Degaussed Steel Hull

### Comments

The helipad can fit a EC.725 Caracal medium helicopter as per the blueprint of the ship, the single davit can also been seen here.
![image](https://user-images.githubusercontent.com/99646926/159907178-7fc75dd2-a9ff-42af-9af0-49de03056708.png)

the black circle is the navigation radar, the blue circle is the SATCOM and the red circles is the RWS, probably Aselsan STAMP
![image](https://user-images.githubusercontent.com/99646926/159908789-6cbd4daa-902c-4c14-835b-437d568526aa.png)

### Sources

https://twitter.com/JeremyBinnie/status/986239118534307842/photo/1
https://www.syshippingcorp.com.my/shipyard/portfolio/category/10-80m-navy-ship.html
https://en.wikipedia.org/wiki/Al-Quwaisat-class_LST

**Comment by Jkryos** [comment]
Added DB3K 494.
