### ISSUE TITLE
LCVP Mk.V (NL) mods, new LCVP Mk5 (UK)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#777]
Hey there, I would like to suggest a few mods on the Dutch LCVP Mk.V, and then have it used a base to create its origin class : the British LCVP Mk.5.

- [ ] LCVP Mk.V (NL)

| 2088 | LCVP Mk.V (NL) -- Netherlands (Navy) , 1995-2011, 12x|
| ------------- | ------------- |
- YearCommissioned = 2008
- YearDecommissioned = empty
- Crew of 3
- DisplacementStandard 16 tons, DisplacementFull 24 tons
- Cargo_Type = 2000 Small Cargo
- Cargo_Mass = 8.2
- Cargo_Crew = 35

> Properties
- add 4002 All Aluminum Construction (-30% DP Penalty)

> Propulsion

- Copy 662	2x Volvo Penta TAMD-71A Diesels
- Name = 2 x Volvo Penta TAMD-72WJ Diesels
Peformance
- Flank speed is 25 knots,
- Cruise speed is 16 knots
- Endurance is 210 nm at 16 knots

### Sources
https://weaponsystems.net/system/1231-LCVP%20Mk%205%20class
https://www.defensie.nl/onderwerpen/materieel/inhoud/schepen/lcvp-landingsvaartuig-personeel
https://nl.wikipedia.org/wiki/%28NL%29LCVP

---

- [ ] LCVP MK5 -- United Kingdom (Royal Navy)

| NEW | LCVP Mk5 -- United Kingdom (Royal Navy), 1996-, 23x|
| ------------- | ------------- |

- Copy 2088 LCVP Mk.V (NL) -- Netherlands (Navy)
- Name = LCVP MK5
- Comments = 23x
- Country = United Kingdom
- Service = Royal Navy
- YearCommissioned = 1996

### Sources
http://www.navypedia.org/ships/uk/brit_aws_lcvp5.htm
http://www.royalnavy.mod.uk/the-equipment/commando/landing-craft
https://weaponsystems.net/system/1231-LCVP%20Mk%205%20class
https://www.eliteukforces.info/uksf-gear/lcvp/

Hampshire, Edward. "British Amphibious Assault Ships: From Suez to the Falklands and the present day", Osprey, 2019.

**Comment by PygmalionOfCyprus** [comment]
Edited/added 494.
