### ISSUE TITLE
MQ-28A Ghost Bat

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#779]
### DB Selector

DB3K

### Affected DBID(s)

5487

### Summary of Changes

Boeing's Airpower Teaming System/Loyal Wingman has been given the RAAF designation of MQ-28A Ghost Bat

### Sources

https://australianaviation.com.au/2022/03/breaking-loyal-wingman-to-be-called-ghost-bat/
https://www.aumanufacturing.com.au/loyal-wingman-now-known-as-mq-28a-ghost-bat
https://boeing.mediaroom.com/news-releases-statements?item=131020

**Comment by PygmalionOfCyprus** [comment]
Handled as part of an internal news roundup.
