### ISSUE TITLE
F-5EM Tiger II [F-5BR] (Brazil - 2007) has two radars should have just one.

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#78]
### DB Selector

DB3K

### Affected DBID(s)

#2102 - F-5EM Tiger II [F-5BR] (Brazil - 2007)

### Summary of Changes

#2102 - F-5EM Tiger II [F-5BR] (Brazil - 2007)

DB entry has two radars having both 

1x EL/M-2032B 
and a
1x Grifo F-BR

Both have the same arcs and position etc.

The F-5EM uses just the Grifo.

### Sources

![image](https://user-images.githubusercontent.com/99494755/153770647-d158b08a-2476-4de8-ae61-41c5f5d858da.png)

**Comment by Jkryos** [comment]
Fixed DB3K 493.

**Comment by KLABDB3K** [comment]
Thank you
