### ISSUE TITLE
#2104 - RK Bora [Pr.1239 Sivuch] PCFG has only 4 x SS-N-22 should have 8. Russian and Soviet entry is inaccurate. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#781]
### DB Selector

DB3K

### Affected DBID(s)

#2104 - RK Bora [Pr.1239 Sivuch] (Russia [1992-] - 1992) #2103 - RK Bora [Pr.1239 Sivuch] (Soviet Union [-1991] - 1989)

### Summary of Changes

#2103 - RK Bora [Pr.1239 Sivuch] (Soviet Union [-1991] - 1989)
#2104 - RK Bora [Pr.1239 Sivuch] (Russia [1992-] - 1992) 
Bora / Dergach class corvette have 2 x 4 SS-N-22 Sunburn mounts not 2 x 2. 
Total of 8 missiles. Discovered whilst adding to scenario. 
![bora](https://user-images.githubusercontent.com/99494755/160142993-931598c4-e939-421c-853e-16d08b9699f4.jpg)
https://www.snafu-solomon.com/2019/11/russian-bora-class-hoverborne-guided.html
 

### Sources

https://www.shutterstock.com/video/clip-9646745-sevastopol-russia-15-september-2014-black-sea
https://turkishnavy.net/2013/05/12/photos-of-russian-warship-bora/
https://1.bp.blogspot.com/-TNo2VvtgP3g/XeHAQrVhUuI/AAAAAAABzmY/Pj3EU3uFHeMr2HB-B2hR8isTKIZvMNFgQCLcBGAsYHQ/s1600/z92699nozn141.jpg

**Comment by PygmalionOfCyprus** [comment]
Fixed 494.
