### ISSUE TITLE
Greece, [FDI], with ASTER 30 B1 and Exocet Blk IIIC

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#782]
### DB Selector

DB3K

### Affected DBID(s)

|ID |Name|
|---|---|
|3173 | TBD [FDI] (Greece - 2025)|
|3636 | TBD [FDI] (Greece - 2027)|

### Summary of Changes

- [x] MM.40 Exocet Blk IIIC

**DataShipMounts**

For each:

ID | ComponentNumber | ComponentID
---| ---| ---
3173| 8| 2175
3173| 9| 2175
3636| 8| 2175
3636| 9| 2175

Replace ComponentID : 
```diff
-  2175 MM.40 Blk III Quad Box
+  3505	MM.40 Blk IIIC Quad Box
```
---
- [x] ASTER 30 B1 (4x 8x)

**Mount**

  Copy

3564 | Sylver A-50 VLS [8 Cells] | Aster 30
| ------------- | ------------- | ------------- |

- In that new mount : Comment = Aster 30 Blk 1 NT
    
Adapt WeaponRecord and MountWeapons so that new mount have : 
```diff
-  133	Aster 30 PAAMS [GWS.45 Sea Viper
+  3774	Aster 30 Blk 1 NT	2020+, ABM
```

**DataShipMounts**

For each:

ID | ComponentNumber | ComponentID
---| ---| ---
3173|12| 3118
3173|13| 3118
3636|12|3118
3636|13|3118
3636|14|3564
3636|15|3564

Replace ComponentID : 
```diff
-  2175 MM.40 Blk III Quad Box
+  NEW Sylver A-50 VLS [8 Cells] Aster 30 Blk 1 NT 
```

_Add two more to 3173_

### Sources

> MBDA "(...) will supply the ASTER 30 B1 area air defence and MM40 Exocet Block 3C anti-ship missiles for three Defence and Intervention Frigates (FDI HN)).

https://newsroom.mbda-systems.com/mbda-awarded-two-contracts-by-greecenbspfor-naval-and-aircraft-weaponry/

https://www.naval-group.com/en/greece-signs-memorandum-understanding-naval-group-and-mbda-opening-negotiations-supply-three-fdi

> The Greek FDI frigates will carry 32 Aster missiles and 8 Exocet MM40 B3C from MBDA, RAM missiles, the aforementioned torpedoes and countermeasures, and a 76mm gun.

https://www.shephardmedia.com/news/naval-warfare/greece-signs-contracts-for-fdi-frigates/

https://www.navalnews.com/naval-news/2022/03/greece-and-naval-group-ink-contract-for-3-fdi-hn-frigates/

**Comment by PygmalionOfCyprus** [comment]
Updated the Exocets and adjusted the Aster Blk 30s on the Standard 2. Are you sure it's a total fit of Blk 30 NTs on both the Standard 1 and 2? Previous sources were indicating a delivery of Aster 15s for Standard 1 in '25 and then a mixed 15/30 loadout for Standard 2 in '27.

**Comment by claudejdev** [comment]
That ship is flexible by design and the actual louadout could change.
However, a source I think is reliable mention 32 Aster 30
![image](https://user-images.githubusercontent.com/35732829/160583115-237c8560-dcce-4248-8f7e-3f41ffbaa0ca.png)

And MBDA have been contracted for ASTER 30 B1, only.

Besides the Greek ship will be equipped with RIM-116C RAM Blk II too and that would be redundant with having Aster 15 aboard.

**Comment by PygmalionOfCyprus** [comment]
I was working off the same source; I guess I just misread his Twitter post. 😅
