### ISSUE TITLE
R 97 Jeanne d Arc -- France (Name, Specs, Facilities, Properties)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#783]
### DB Selector

DB3K

### Affected DBID(s)

|ID |Name|
|---|---|
|999|R 97 Jeanne d Arc -- France (Navy) , 1984-0, -|
|1391|R 97 Jeanne d Arc -- France (Navy) , 1977-0, -|
|1392|R 97 Jeanne d Arc -- France (Navy) , 2000-2010, -|

### Summary of Changes

- [x] **DataShip**

- Name = Jeanne d'Arc
- Height = 52
- DisplacementEmpty = 10575
- DisplacementStandard = 11170
- Crew = 503 [^1]
- Cargo_Mass = 200
- Cargo_Area = 648
- Cargo_Crew = 700

- [x] **DataShipAircraftFacilities**

For each:

ID | ComponentNumber | ComponentID
---| ---| ---
999 | 1 | 45
1391 | 1 | 45
1392 | 1 | 45

Replace ComponentID [^2]
```diff
-  # 45 Hangar (6x Large Aircraft (18.1-26m Long))
+  # 17 Hangar (8x Large Aircraft (18.1-26m Long))
```

For each:
999, 1391, 1392

- Add two new # 15 Open Parking (1x Large Aircraft (18.1-26m Long))[^3]

- [x] **DataShipCodes**

Please add Refuel to Starboard x 1 (Out), Refuel from Starboard x 1 (In), Replenish to Port x 1 (Out) and Replenish from Port x 1 (In)[^4][^5]:

ID | CodeID
---| ---
999 | 8005
999 | 8106
999 | 9001
999 | 9101
1391 | 8005
1391 | 8106
1391 | 9001
1391 | 9101
1392 | 8005
1392 | 8106
1392 | 9001
1392 | 9101

- [x] **DataShipDockingFacilities**

Please _add_ 2x "33 Davit (2x Very Small Dock/Davit (0-11m Long))"[^6]:

ID | ComponentNumber | ComponentID
---| ---| ---
999 | 1 | 33
999 | 2 | 33
1391 | 1 | 33
1391 | 2 | 33
1392 | 1 | 33
1392 | 2 | 33

### Sources

[^1]: Wartime crew
[^2]: In wartime, more hangar space is made by removing the cadet's accommodation
[^3]: http://www.netmarine.net/bat/ecole/jeanne/photo21.jpg
[^4]: http://www.ffaa.net/ships/helicopter-carrier/jeanne-arc/images/jeanne-arc-0107.jpg
[^5]: http://www.ffaa.net/ships/helicopter-carrier/jeanne-arc/images/jeanne-arc-0064.jpg
[^6]: http://www.ffaa.net/ships/helicopter-carrier/jeanne-arc/images/jeanne-arc-0010.jpg

http://www.defense.gouv.fr/marine/patrimoine/histoire/la-marine-d-hier/les-batiments-de-surface/jeanne-d-arc-r-97
http://navalanalyses.blogspot.be/2016/02/warships-of-past-jeanne-darc-helicopter.html
http://www.netmarine.net/bat/ecole/jeanne/caracter.htm
http://www.ffaa.net/ships/helicopter-carrier/jeanne-arc/caracteristiques.htm
"Conway's all the world's fighting ships 1947-1995" (1996), ISBN: 978-1557501325.

**Comment by PygmalionOfCyprus** [comment]
Fixed 494.
