### ISSUE TITLE
IvoryCoast, Add RPB33 (L'émergence) class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#784]
### DB Selector

DB3K

### Baseline

See entry 679 for Togo

### Hypothetical

No

### Name

Patrol Boat (PB), P1401, L'Émergence

### Class

L'Émergence (Raidco RPB33)

### Country

Ivory Coast (Cote d'Ivoire)

### Service

Navy

### In Commission

2014 - present

### Length (m)

33.7

### Beam (m)

6.53

### Draft (m)

1.9

### Standard Displacement (t)

Not found

### Full Displacement (t)

80

### Complement

14 (+3 extra)

### Primary Propulsion Type

Diesel

### Propulsion

2x MAN D2842 LE410 diesels, 2 shafts

### Flank Speed (kt)

35 (src1), 22 (src2), 40 (src3)

### Range (nm) at Speed (kt)

1800 @ 15 (src2), 1500 @ 15 (src3)

### Sensors

1x I-band navigation radar 

### Mounts

1x single 20mm/70 Mk10 (front)
2x single 12.7mm/90 (aft)

### Aircraft & Docking Facilities

6.15m RHIB aft ramp

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

3 units in class. 
Entry 679 on this site for Togo is same class, sources giving differences in data.
Also delivered to Senegal

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/cote_divoire/cdi_cf_lemergence.htm
3: https://www.naval-technology.com/projects/rpb-33-offshore-patrol-boat
4: https://www.defenceweb.co.za/sea/sea-sea/ivory-coast-receives-final-rpb-33-patrol-boat
5: https://www.defenceweb.co.za/sea/sea-sea/ivory-coast-receiving-rpb33-patrol-boats
6: https://www.military.africa/2021/04/senegalese-navy-receives-another-rpb-33-patrol-boat-from-ufas
![1](https://user-images.githubusercontent.com/99532490/160243491-856202c4-c8b7-4465-8694-cbf118c3ddb7.jpg)
t

**Comment by PygmalionOfCyprus** [comment]
Added 494.
