### ISSUE TITLE
IvoryCoast, Add Predator (CHN) class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#785]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), -, -

### Class

Predator class (Chinese built)

### Country

Ivory Coast (Cote d'Ivoire)

### Service

Navy

### In Commission

2017 - present

### Length (m)

27.1

### Beam (m)

3.8

### Draft (m)

1.8

### Standard Displacement (t)

Not found

### Full Displacement (t)

70

### Complement

12

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 12V396 TE742, 2 shafts

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

Not found

### Sensors

1x JRC I-band Navigation radar

### Mounts

1x single 12.7mm/79
1x single 7.6mm/90

### Comments

Chinese built.
Not all data found.

### Sources

1: https://www.navypedia.org/ships/cote_divoire/cdi_cf_predator.htm
2: https://www.defenceweb.co.za/sea/sea-sea/china-donates-patrol-boat-to-ivory-coast
![1](https://user-images.githubusercontent.com/99532490/160245938-381aa260-2bf1-4b72-93c9-1e17c97ce9d8.jpg)
![2](https://user-images.githubusercontent.com/99532490/160245940-81b2df35-2dc2-4687-a8ff-d4cf2f765173.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
