### ISSUE TITLE
Poland PPZR Piorun MANPADS

### ISSUE THREAD

**Issue by Vasto** [PygmalionOfCyprus/cmo-db-requests#787]
### DB Selector

DB3K

### Hypothetical

No

### Name

PPZR Piorun MANPADS

### Facility Type

SAM

### Country

Poland

### Service

Army

### In Commission

2019

### Crew

1

### Sensors

1x Mk1 Eyeball
Night vision

### Mounts

3x PPZR Piorun MANPADS

### Magazines

Piorun

### Comments
Missile added as a separate Weapon request: #790 
Missile parameters:
Type: Guided Weapon
Length: 1.596 m
Diameter: 0.072m
Weight: 10.5 kg 
Target altitude: 10-4000 m
Range (anti air):  400-6500 m

### Sources

https://en.wikipedia.org/wiki/Piorun_(missile)
https://defence24.com/industry/polish-piorun-manpads-exported-to-us-and-provided-to-ukraine-a-success-for-mesko-company
https://www.armyrecognition.com/polish_missile_vehicles_systems_weapons_poland_uk/piorun_grom-m_manpads_man-portable_air-defense_systems_short-range_missile_technical_data_sheet_pictures_video_12612165.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
