### ISSUE TITLE
L 167 Ios [Type 520 Barbe] -- Greece, copy of 1492 L 760 Flunder [Type 520 Barbe] -- Germany

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#788]
### DB Selector

DB3K

### DBID to Copy

1492 L 760 Flunder [Type 520 Barbe] -- Germany

### Hypothetical

No

### Name

L 167 Ios [Type 520 Barbe]

### Country

Greece

### Service

Navy

### In Commission

1992

### Other Changes

- Comments = 6 to 8 transferred in 1992
- 
Note : secondary role as a minelayer, no details.

### Sources

http://www.hellas.org/military/navy/lcu520.htm
http://www.marine.de/portal/a/marine/start/waffenun/hilfsfah/mehrzwec/
http://www.navypedia.org/ships/germany/ger_ls_butt.htm

**Comment by PygmalionOfCyprus** [comment]
Added 494.
