### ISSUE TITLE
Al Khalid MBT too heavy as cargo

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#789]
### DB Selector

DB3K

### Affected DBID(s)

2112

### Summary of Changes

Currently, the Al-Khalid MBT (ID 2431 as cargo) is listed as having a mass of 58 tons as cargo. All the sources I've seen have it substantially lighter, at either 46 or 48 tons. 

### Sources

https://www.tanks-encyclopedia.com/modern/Pakistan/Al-Khalid.php

https://man.fas.org/dod-101/sys/land/row/mbt-2000.htm

https://www.globalsecurity.org/military/world/pakistan/mbt-2000.htm

**Comment by PygmalionOfCyprus** [comment]
Fixed 494; changed to 48t.
