### ISSUE TITLE
#3588 AGM-88E AARGM-ER on F-35 variants

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#79]
### DB Selector

DB3K

### User(s)

F-35A/B/C

### Weapons Carried

<type>UPDATE</type>
<summary>Please consider to update the AARGM-ER loadout of the F-35A,B,C and name the missile AGM-88G</summary>
<detail>
#3588 AGM-88E AARGM-ER anti-radiation missile is called AGM-88G AARGM-ER

This press release from @NGCNews claims that the AARGM-ER is being integrated on the F-35B.
Currently in de DB:
#3835 F-35A 2025 has only a external AARGM-ER load-out available and no internal. Please change into internal.
#4701 F-35B 2025 the AARGM-ER is not available (should be external because of the shorter weaponbay of the F-35B).
#3836 F-35C 2025 has the weapon internal and is fine.
#4874 F-35C 2028 has the AARGM-ER behind its name but the weapon is already present in #3836 F-35 2025. Maybe a name change needed?

Grumman is currently under contract to deliver production units of AARGM-ER to support a 2023 initial operational capability (IOC) fielding. Could not find a FOC date.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

![520F57BBF95D46B0BB9A958E974155C8](https://user-images.githubusercontent.com/60408110/153772010-546c2119-80c7-4589-8155-d44300914b6c.jpg)

### Sources

https://www.navalnews.com/naval-news/2022/02/aargm-er-completes-second-successful-missile-live-fire/
https://news.northropgrumman.com/news/releases/advanced-anti-radiation-guided-missile-extended-range-completes-second-successful-missile-live-fire
https://twitter.com/MIL_STD/status/1490801490843389954
https://twitter.com/MIL_STD/status/1490802483937034245

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493. Except for the weird naming on #4874. I don't know what that entry was supposed to be; it has less loadouts than the preceding entry, for some reason. I'm sure there was some logic to that at some point but as it stands currently I can only assume it was unfinished or created in error.

I'm gonna leave that one until we decide on what to do with it. (This is where I wish I could delete things, but alas, backwards compat...)
