### ISSUE TITLE
Poland, Piorun Anti Air Missile

### ISSUE THREAD

**Issue by Vasto** [PygmalionOfCyprus/cmo-db-requests#790]
### DB Selector

DB3K

### Baseline

2799

### Hypothetical

No

### Name

Piorun

### Length (m)

1.596

### Width/Span (m)

0.3

### Diameter (m)

0.072

### Weight (kg)

10.5

### Range (nm)

0.215 - 3.5

### Target Altitude / Depth (ft)

32 - 13123

### Warhead

1,82kg

### Targets

Aircraft, Helicopter

### Sensors

IR seeker

### Weapon Codes

Anti-Air All-Aspect

### Sources

https://en.wikipedia.org/wiki/Piorun_(missile)
https://www.armyrecognition.com/polish_missile_vehicles_systems_weapons_poland_uk/piorun_grom-m_manpads_man-portable_air-defense_systems_short-range_missile_technical_data_sheet_pictures_video_12612165.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
