### ISSUE TITLE
Poland, SPZR Poprad

### ISSUE THREAD

**Issue by Vasto** [PygmalionOfCyprus/cmo-db-requests#791]
### DB Selector

DB3K

### Hypothetical

No

### Name

SPZR Poprad

### Facility Type

SAM

### Country

Poland

### Service

Army

### In Commission

2018

### Crew

2

### Sensors

1x Mk1 Eyeball
1x Generic FLIR Camera
1x Generic TV Camera
1x Generic Laser Rangefinder

### Mounts

4x Piorun
or 4x PZR Grom

### Magazines

4x Piorun
or 4x PZR Grom

### Comments

Piorun missile added as a separate Weapon request: #790 

### Sources

https://en.wikipedia.org/wiki/Poprad_(self-propelled_anti-aircraft_missile_system)
https://pl.wikipedia.org/wiki/SPZR_Poprad
https://www.army-technology.com/projects/spzr-poprad-anti-aircraft-missile-system/
https://www.armyrecognition.com/defense_news_june_2021_global_security_army_industry/pit-radwar_delivers_more_poprad_mobile_anti-aircraft_missile_systems_to_polish_army.html

**Comment by PygmalionOfCyprus** [comment]
Added 494. Bafflingly this was already in the DB for Indonesia but not for Poland, its original operator...
