### ISSUE TITLE
Special Forces Quadcopter launchpad

### ISSUE THREAD

**Issue by BartGauvin** [PygmalionOfCyprus/cmo-db-requests#792]
### DB Selector

DB3K

### Hypothetical

No

### Name

Quadcopter Control Site

### Facility Type

Inf

### Country

Generic

### Service

Army

### In Commission

2010

### Crew

2-3

### Dispersion Radius (m)

10

### Sensors

Eyeball
NVGs

### Mounts

Not sure

### Aircraft & Docking Facilities

1x Pad
1x Open parking
1x runway access Point

### Comments

Currently DBID 3157 can be used but it is a truck and therefore is fairly easy to detect.  With the ability for a single operator to control a drone from anywhere, an Infantry version of this facility should be available which is much harder to detect

### Sources

I'm not suggesting a [nano-drone](https://en.wikipedia.org/wiki/Black_Hornet_Nano) be added but this is an example.

here is a paper on the subject https://irp.fas.org/eprint/howard.htm

Thanks

**Comment by PygmalionOfCyprus** [comment]
Close with PygmalionOfCyprus/cmo-db-dev#225

**Comment by PygmalionOfCyprus** [comment]
(I'm aware you can't see issues in the dev GitHub; long story short, we're going to improve the distinction between hand-launched / catapult-launched / conventionally-launched UAVs. Once that's implemented you'll be able to launch small man-portable UAVs like quadcopters, etc. from any platform regardless of the aircraft facilities or lack thereof, so we won't need a dedicated "quadcopter launchpad" to represent some dude putting a quadcopter on the ground.)

**Comment by BartGauvin** [comment]
OK, excellent thanks
