### ISSUE TITLE
Brunei, Add Ijhtihad class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#793]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol craft (PC), 17, Ijhtihad

### Class

Ijhtihad (FPB 41)

### Country

Brunei

### Service

Navy

### In Commission

2009 - present

### Length (m)

41.3

### Beam (m)

7.7

### Draft (m)

2.6

### Standard Displacement (t)

Not found

### Full Displacement (t)

265

### Complement

16 + 5 extra

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 16V4000 M93L, 2 shafts

### Flank Speed (kt)

32 (src2), 33 (src1)

### Range (nm) at Speed (kt)

1500 @ 12

### Sensors

1x Furuno 2217 I-band Navigation radar
Zeiss MEOS II EO
Thales cutlass ESM (scr1)

### Mounts

1x single Rheinmetall 27mm/63 MLG-27, front.
2x single 7.62mm/90.

### Aircraft & Docking Facilities

1x 4m RHIB on Davits, port side

### Comments

4 units in class.
Lurssen DEU build

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/brunei/bru_cf_ijhtihad.htm
3: https://defense-studies.blogspot.com/2010/08/ijtihad-class-kapal-patroli-terbaru.html
![1p](https://user-images.githubusercontent.com/99532490/160287941-d29b171d-bd6e-49de-a951-a490abfbeaa9.jpg)
![4p](https://user-images.githubusercontent.com/99532490/160287943-a59e459d-fceb-4359-a589-adef7bace038.jpg)
![5p](https://user-images.githubusercontent.com/99532490/160287944-6afdc05b-3abf-4623-b207-13192a32787c.jpg)
![6p](https://user-images.githubusercontent.com/99532490/160287945-4b8e640a-8a74-4f64-b9e7-a0a3a96515c3.jpg)

**Comment by Jkryos** [comment]
Added DB3k 494.
