### ISSUE TITLE
Brunei, Add Mustaed class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#794]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), 21, Mustaed

### Class

Mustaed (FIB 025-12)

### Country

Brunei

### Service

Navy

### In Commission

2011 - present

### Length (m)

27.2

### Beam (m)

6.2

### Draft (m)

1.2

### Standard Displacement (t)

60

### Complement

15

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 16V2000 M93, 2 MJP waterjets

### Flank Speed (kt)

40

### Range (nm) at Speed (kt)

Not found

### Sensors

1x Furuno I-band navigation radar

### Mounts

3x single 7.6mm/90

### Aircraft & Docking Facilities

small RHIB aft (image)

### Ship Codes

All Aluminum Construction

### Comments

1 unit in class

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/brunei/bru_cf_mustaed.htm
3: http://rpdefense.over-blog.com/article-rbaf-accepts-new-fast-interceptor-boat-88592612.html
4: https://vospernaval.com.sg/fib25
![3p](https://user-images.githubusercontent.com/99532490/160288878-30d2e8b2-7748-4c84-bcff-1ae1b38e4fab.jpg)
![7p](https://user-images.githubusercontent.com/99532490/160288879-2ffbf536-b086-45ae-8c51-795c74e93c0f.jpg)
![8p](https://user-images.githubusercontent.com/99532490/160288880-321fd9a1-fde7-4921-9f1f-a7159d14747d.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
