### ISSUE TITLE
Brunei, Add Serasa class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#795]
### DB Selector

DB3K

### Hypothetical

No

### Name

Landing Craft Utility (LCU), L33, Serasa

### Class

Serasa 

### Country

Brunei

### Service

Navy

### In Commission

1996 - present

### Length (m)

36.5

### Beam (m)

8

### Draft (m)

1.5

### Standard Displacement (t)

220

### Full Displacement (t)

374

### Complement

12

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3508, 2 shafts

### Flank Speed (kt)

12

### Range (nm) at Speed (kt)

1500 @ 10

### Sensors

1x RacalDecca I-Band navigation radar

### Mounts

2x single 20mm/90 GAM-B01 (fitted for)
2x single 7.6mm/90 (fitted for)

### Comments

2 units in class. 
Bow and Side ramp fitted. 
Military lift: 100 tons. 
Australian build.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/brunei/bru_ls_serasa.htm
3: https://en.wikipedia.org/wiki/Serasa-class_landing_craft
![1](https://user-images.githubusercontent.com/99532490/160289734-0c22cc98-1351-4bb4-8843-edb486a3239b.jpg)
![2](https://user-images.githubusercontent.com/99532490/160289736-3eef78c7-f154-4bf0-a720-666c472de222.jpg)
![3](https://user-images.githubusercontent.com/99532490/160289737-7a0afb70-6339-4a15-8876-b74ef43093c8.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
