### ISSUE TITLE
3772 - RIM-174A ERAM SM-6 Blk IB can't fire at a land target (Target altitude set at 30ft)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#797]
### DB Selector

DB3K

### Affected DBID(s)

3772 - RIM-174A ERAM SM-6 Blk IB

### Description of Problem

As mentioned on Discord by jayTAC [^1] and by Gorillabond [^2], the 

> eram here says can target land up to 200nm, but min alt is 30ft so it wont fire. is this just a typo or can the BLOCK IB really strike land targets as well?

![image](https://user-images.githubusercontent.com/35732829/160293285-b6103ced-d9f8-47c0-a14e-794b8c42fff0.png)
![image](https://user-images.githubusercontent.com/35732829/160293302-abf0d349-08e9-47a6-8312-84ed9e8338b0.png)

[^1]: https://discord.com/channels/557667391438454800/557675190738485272/955015620800438272
[^2]: https://discord.com/channels/557667391438454800/557669654055878676/957684384893394975

### Recommended Fix

Set TargetAltitudeMin = 0.0

---
However, in my _opinion_, that missile shouldn't be able to strike at land target at all.
That idea seems to come from, what consider to be, a vague statement : "But the new SM-6 is also capable of [striking surface targets](https://breakingdefense.com/2016/03/anti-aircraft-missile-sinks-ship-navy-sm-6/) on land and sea."

While the latest official document I could find illustrate that it does have _not_.
![image](https://user-images.githubusercontent.com/35732829/160293263-36a339d6-d452-44ff-9828-f1327722b028.png)
https://navyclippings.nl/index.php/2022/01/29/lockheed-martins-optionally-unmanned-surface-vessel-ousv/
https://breakingdefense.com/2020/11/army-picks-tomahawk-sm-6-for-mid-range-missiles/

If you consider that that model cannot strike land target, then I would recommend to, in DataWeaponTargets, _delete_ :

ID | CodeID
---| ---
3772 | 3001
3772 | 3002
3772 | 3003
3772 | 4001
3772 | 4002
3772 | 4003

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.

3772 is specifically the SM-6 Blk 1B being used for the Army's MRC (now Typhon) capability; it's still not 100% clear whether it is, in fact, land-attack capable, but since they're buffing the surface attack capabilities for primary use it's a fair bet that any land-attack capability present -- however rudimentary -- is probably on the cards.

Weapon ID 3714 is the "standard" SM-6 that gets put on naval vessels, etc.
