### ISSUE TITLE
3025 - DKA Dyugon [Pr.2182.0] (Russia [1992-] - 2011), CargoCapacity

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#798]
### DB Selector

DB3K

### Affected DBID(s)

3025 - DKA Dyugon [Pr.2182.0] (Russia [1992-] - 2011)

### Summary of Changes

- CargoCapacity = 
```diff
-  50
+  140
```

### Sources

- IHS Jane's Fighting Ships 2015-2016, page 709
- [project 21820 Dugong - DYUGON | MilitaryRussia.Ru - domestic military equipment (after 1945)](http://militaryrussia.ru/blog/topic-630.html)

**Comment by PygmalionOfCyprus** [comment]
Fixed 494.

**Comment by claudejdev** [comment]
Out of curiosity, what is the most convenient for you guys : a single platform ticket, such as this one, or family pack such as #776 ?

I'm on the fence because of granularity vs spamming.

**Comment by PygmalionOfCyprus** [comment]
For stuff like this, where it's literally just a matter of changing one or a couple of data points, you can bundle them all together. It may take a little longer for us to sit down and tackle them all but with changes that small it actually takes more time to open, read, and close the tickets than to actually edit the data.

For bigger, more complicated stuff (like refits, or changing out mounts, etc.) it's generally better to file individual requests.
