### ISSUE TITLE
LSF 621 [MDK Tsaplya, Pr.1206.1 Murena] -- South Korea (Navy) , 2007 - Datas

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#799]
### DB Selector

DB3K

### Affected DBID(s)

2575 LSF 621 [MDK Tsaplya, Pr.1206.1 Murena] -- South Korea (Navy) , 2007

### Summary of Changes

- name = LSF 621 [Pr.12061E - Murena-E]
- YearCommissioned = 2006
- Beam = 14.6
- MaxSeaState = 4
- PhysicalSizeCode = 2004 Large Pier (25.1-45m Long)

There would be 1000 rounds for the AK-306 30mm guns and there would be 10 to 24 mines.

### Sources

- http://russianships.info/eng/warships/project_12061.htm
- http://roe.ru/eng/catalog/naval-systems/murena-e/
- http://www.oaoosk.ru/en/products/murena-e/
- http://www.navyrecognition.com/index.php/news/defence-news/2016/february-2016-navy-naval-forces-defense-industry-technology-maritime-security-global-news/3596-russian-navy-caspian-flotilla-to-receive-project-12061-murena-class-assault-hovercraft.html

**Comment by PygmalionOfCyprus** [comment]
Fixed 494 with two caveats. Re: the 1000 rnds per AK-306, they already have 1000 rnds (50 rnd burst x 20); are you suggesting we remove the magazines with extra ammo?

Also, I have no idea which mines the South Koreans would be using or even if they would, so unless I can get some info on that I'll probably just leave it for people to add via Lua or the Add Mounts menu if they need it.

**Comment by claudejdev** [comment]
Yes!
"There would be _only_ 1000 rounds", should have been my sentence.

I don't have more details regarding the mines. That's probably best to leave that aside then.

Cheers

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
