### ISSUE TITLE
Add Russian 48Ya-K1 Podlet Radar from 2016

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#8]
### DB Selector

DB3K

### Hypothetical

- [ ] Yes

### Name

Radar (48Ya-K1 Podlet)

### Facility Type

Radar

### Country

Russia

### Service

Airforce

### In Commission

2016

### Crew

Default

### Dispersion Radius (m)

default

### Sensors

48Ya-K1 Podlet

### Mounts

48Ya-K1 Podlet

### Comments

Is the current standard mobile low-altitude detection radar. S-band. 10km alt and 200km range (if you believe sales literature). These are everywhere Russia is right now. Syria, Ukrainian Border. etc. etc 

### Sources

http://www.matrixgames.com/forums/fb.asp?m=5071345
http://www.matrixgames.com/forums/fb.asp?m=4931657
https://twitter.com/Lorkeske/status/1474068024776876048
https://twitter.com/halmiso1/status/1176729815849865216
https://twitter.com/RALee85/status/1359929147766800385
https://twitter.com/Missilito/status/472293701512077312
https://twitter.com/IiiTango/status/1341051952352931842
https://twitter.com/colonelhomsi/status/1199814982315188224
https://twitter.com/Cyberspec1/status/1471669183054188551

**Comment by Jkryos** [comment]
Added DB3K 493.
