### ISSUE TITLE
Please consider to update the #461 Spice-2000 bomb with a Mk.84 BLU-109 fuze

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#80]
### DB Selector

DB3K

### Affected DBID(s)

#461

### Summary of Changes

Please consider to update the #461 Spice-2000 bomb with a Mk.84 BLU-109

The weapon can be combined with a 2,000lb BLU-109 penetrating warhead to tackle hardened targets.
The CEP is in the brochure 3 meters instead of 5 m in the database.

### Sources

https://www.key.aero/article/israeli-air-force-spice-munitions-airforces-magazine
https://www.rafael.co.il/wp-content/uploads/2019/03/Spice.pdf
https://www.slideshare.net/hindujudaic/spice-bomb

**Comment by Jkryos** [comment]
Updated CEP and created new SPICE 2000 variant with BLU-109 warhead, DB3K 493.
