### ISSUE TITLE
MDK Murena [Pr.12061, Tsaplya] -- Soviet Union, Russia, from #799

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#800]
### DB Selector

DB3K

### DBID to Copy

#799 2575 LSF 621 [MDK Tsaplya, Pr.1206.1 Murena] -- South Korea (Navy) , 2007

### Hypothetical

No

### Name

MDK Murena [Pr.12061, Tsaplya]

### Country

Soviet Union, Russia

### Service

(Naval Fleet [V-MF]), (Navy)

### In Commission

1985-1991, 1992-2004

### Other Changes

- Russian version would have 1x quad 9K310 "Igla-1" SAM system launcher.
- There would be 800 grenade launchers rounds.
- Tsaplya would be her NATO designation name.
- From late 1994 all ships would have been handed to the Coast Guard.
### Sources

- http://russianships.info/eng/warships/project_12061.htm
- http://roe.ru/eng/catalog/naval-systems/murena-e/
- http://www.oaoosk.ru/en/products/murena-e/
- http://www.navyrecognition.com/index.php/news/defence-news/2016/february-2016-navy-naval-forces-defense-industry-technology-maritime-security-global-news/3596-russian-navy-caspian-flotilla-to-receive-project-12061-murena-class-assault-hovercraft.html

**Comment by PygmalionOfCyprus** [comment]
Added 494.
