### ISSUE TITLE
Please consider updating Kh-15 max speed (*before* copying/adding the linked issues below)

### ISSUE THREAD

**Issue by nkocevar** [PygmalionOfCyprus/cmo-db-requests#801]
### DB Selector

DB3K

### Affected DBID(s)

1060, 3717

### Summary of Changes

Please update the Kh-15's max speed & propulsion ***prior to copying/adding the Kh-15S and Kh-15P*** weapons that I requested in issues #254 and #261 ...

Max speed: Should be increased to 3300 Kts @ 130,000 Ft.
Propulsion: Should be changed to "SRM-160"

### Sources

https://weaponsystems.net/system/99-HH08%20-%20AS-16%20Kickback%20(Kh-15)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
