### ISSUE TITLE
XQ-58 USN variant has no radar.

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#802]
### DB Selector

DB3K

### Affected DBID(s)

4774

### Summary of Changes

The US Navy variant of the XQ-58 has no APG-81 radar but the USAF version (5186) does. Request that this version has the radar added too.

### Sources

CMO DB493.

**Comment by 5th-Domain** [comment]
#4774 XQ-58 Valkyrie, United States, Navy, 2021, XQ-222, Has AN/APG-81 AESA (#2081) In DB3000 v493
