### ISSUE TITLE
Please add 1x davit for 7m RHIB and also small pad for UAV for Hendijan-class of Iranian Navy.

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#804]
### DB Selector

DB3K

### Affected DBID(s)

1202 & 2784 MIG-S-4700-SC Bakhtaran [Hendijan Class]

### Summary of Changes

-Add 1x davit for 7m RHIB as the ships were seen equipped with it. the pics is as below. the red circles is where the davit is located.
![image](https://user-images.githubusercontent.com/99646926/160525022-41334276-10d1-4c50-97c7-7828cb332b7c.png)
![image](https://user-images.githubusercontent.com/99646926/160525065-3fe40ada-a88f-47b8-998e-f8be4f4042f5.png)
![image](https://user-images.githubusercontent.com/99646926/160526318-e89eacf6-9415-4359-ab53-55f92908baac.png)

-Add small pad or any facility that can handle at least 1x small UAV. The ship were able to carry and launch at least one UAV at a time. The pics is as below.
![image](https://user-images.githubusercontent.com/99646926/160526346-3ad3bd7e-c672-4cff-8097-f258ed6bb25a.png)
![image](https://user-images.githubusercontent.com/99646926/160526406-9d44b926-55d4-4fa5-94aa-95a47a4bd278.png)

### Sources

https://www.uskowioniran.com/2012/01/velayat-90-military-maneuvers-6.html
https://www.republicworld.com/world-news/rest-of-the-world-news/iranian-frigate-accidentally-opens-fire-on-its-own-logistical-ship-kon.html
https://www.tasnimnews.com/en/news/2013/09/03/132215/iran-navy-using-drones-to-boost-intelligence-combat-capabilities
http://www.navaldrones.com/Iran-Navy-UAV.html

**Comment by PygmalionOfCyprus** [comment]
Added the davits; UAV catapult requires completion of PygmalionOfCyprus/cmo-db-dev/issues#225

**Comment by PygmalionOfCyprus** [comment]
Catapult launchers added! The Hendijan class now has the honor of being the very first platform in the DB to get the fancy new UAV launchers.

...probably should have gone for a flashier first platform, huh...

**Comment by capcop98** [comment]
> Catapult launchers added! The Hendijan class now has the honor of being the very first platform in the DB to get the fancy new UAV launchers.
> 
> ...probably should have gone for a flashier first platform, huh...

Thank you! And sorry for having the auxiliary ship got the honor of being the first vessel to be equipped with the new capability though hahaha
