### ISSUE TITLE
Egypt Shanghai II Class x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#806]
### DB Selector

DB3K

### DBID to Copy

#1347 DB3K

### Hypothetical

No

### Name

793

### Country

Egypt

### Service

Navy

### In Commission

1984

### Sensors

- Decca - I Band
- ESM: Thompson-CSF: Radar warning

### Mounts

- Mine rails for 10 mines

### Sources

https://en.wikipedia.org/wiki/Type_062_gunboat
http://www.navypedia.org/ships/egypt/eg_cf_793.htm
Janes 2003-04. pg 193

![image](https://user-images.githubusercontent.com/99632305/160527885-80297237-a283-4e5c-9638-210edfaf7fd9.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
