### ISSUE TITLE
Egypt T 43 Minesweepers (Pr.254K/M) - Ocean x 6

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#808]
### DB Selector

DB3K

### DBID to Copy

#945 DB3k

### Hypothetical

No

### Name

510 Bahaira 

### Country

Egypt

### Service

Navy

### In Commission

1970-

### Sensors

- Navigation radar: Don 2: I-band
- Sonar: Stag Ear, hull mounted
- Generic Mechancial Cable Cutter Mine Sweep
- Generic Magnetic & Acoustic Mine Sweep
- Generic Mine Disposal Diver

### Mounts

- 4x 37mm/63 (2 twin, 1fwd, 1rear)
- 8x 12.7mm (4 twin) mg's 
- mine rack for 20 mines

### Sources

http://www.navypedia.org/ships/egypt/eg_ms_bahaira.htm
https://en.wikipedia.org/wiki/T43-class_minesweeper
Janes 2003-04, pg 194

![image](https://user-images.githubusercontent.com/99632305/160534204-705ce8e1-6b06-403a-a33d-42acb3450363.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
