### ISSUE TITLE
Please consider to update the loadout of the Mirage-2000 of India with Spice-2000 bomb

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#81]
### DB Selector

DB3K

### User(s)

#3798 Mirage 2000H-5

### Weapons Carried

#3798 Mirage 2000H-5 of India is observed with a Spice-2000 bomb and also bombed Pakistan with it.

In Feb 2019, during the Balakot strike, 12 Mirage 2000 of the No.7 Squadron of the IAF based in Gwalior flew, each carrying a single 1000 kg SPICE-2000 bomb & bombed the camps across LOC.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Combat radius is unk, but maybe an estimation can be done compared to other loadouts?

### Sources

https://www.ndtv.com/india-news/iaf-strikes-mirage-2000-is-air-forces-go-to-fighter-for-tough-jobs-10-things-to-know-1999626
https://fighterjetsworld.com/air/indian-air-force-to-receive-israel-made-spice-2000-bombs-next-month/17559/
https://www.youtube.com/watch?v=l8SD0yCucjw
https://www.quora.com/Can-the-Dassault-Mirage-2000-be-used-as-a-bomber

**Comment by PygmalionOfCyprus** [comment]
Do we have any images/description of the full loadout? I'm assuming centerline Spice, 2 tanks, and outboard A:A missiles (MICA IR?) but I'm just guessing.

**Comment by tbrandon517** [comment]
How about this?

![image](https://user-images.githubusercontent.com/99599482/154662993-cf948b70-ec10-4da7-bc79-a6391927ad33.png)

**Comment by PygmalionOfCyprus** [comment]
That'll do! Looks like I was basically right. Added 493.
