### ISSUE TITLE
Add Indian SSM Plt (SSC-3 Styx [4k51 Rubezh])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#810]
### DB Selector

DB3K

### DBID to Copy

Facility 651

### Hypothetical

No

### Name

SSM Plt (SSC-3 Styx [4k51 Rubezh])

### Country

India

### Service

Navy

### In Commission

1988

### Sources

https://www.facebook.com/IndianDefenceFacts/posts/indian-navy-operates-the-4k51-rubezh-coastal-defense-system-for-a-coastal-defens/1977068199211946/
https://twitter.com/nocallsigns/status/596665008441823232
https://twitter.com/pakimint/status/1282987524919562241

Sipri Arms Database Line
    		150	P-15M	Anti-ship missile	(1985)	1986-1987	(150)	For Rubezh (SS-C-3) coast defence systems

**Comment by PygmalionOfCyprus** [comment]
Added 494.
