### ISSUE TITLE
Add 2022 Retirement date To UK T.1

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#811]
### DB Selector

DB3K

### Affected DBID(s)

#2176 and #2910

### Summary of Changes

Add out of service date of 2022

### Sources

https://www.scramble.nl/military-news/raf-hawk-t1s-to-retire-by-march-2022
https://ukdefencejournal.org.uk/uk-to-bring-forward-hawk-t1-retirement/

**Comment by PygmalionOfCyprus** [comment]
Added 494.
