### ISSUE TITLE
Egypt MEKO A-200 EN x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#812]
### DB Selector

DB3K

### DBID to Copy

#3020 Db3K

### Hypothetical

No

### Name

ENS Al-Aziz

### Country

Egypt

### Service

Navy

### Sensors

- 1x Thales NS-110 4D AESA air and surface surveillance radar
- Thales SCORPION Electronic Warfare Support Measures System (ECM)
- Towed array sonar

### Mounts

- 1x Oto Melara 127/64 LW (Vulcano and Dart shells)
- 32 Vertical Launch Systems that will be equipped with MICA New Generation Surface-to-Air Missiles
- 16× Launchers planned to be equipped with Exocet Block 3 anti-ship missiles
- 2x Oerlikon Searanger 20mm naval guns (Fwd/Aft)
- Torpedos: DM2A4 Seahake and MU-90 Torpedos
- Decoy launchers for C310 high-performance anti-torpedo counter-measures system
- 4x Rheinmetall Multi Ammunition Softkill System EM/IR
- 2 × WASS/Finmeccanica MORPHEUS acoustic countermeasures launching systems (on each side of the VLS cells

### Other Changes

- Full load 3,700-4,000t
- 7,200 nm/16kts
- Helicopters: 1 x 10 ton or 2 x 5-ton; 2 x UAVs
- Boats/USV's: 2 x 7.5 m
- Mission Modules: 2 x TEU-sized modules; or 2 x 11 m boats; TAS; UUVs/USVs
- SATCOM

### Sources

https://www.thyssenkrupp-marinesystems.com/en/products-services/surface-vessels/frigates
https://military-wiki.com/localization-of-meko-a200-frigate-egypt-masters-navy-shipbuilding-capacity/
https://www.military.africa/2022/01/egypt-building-meko-a200en-frigate-in-alexandria
https://navalpost.com/egypt-begins-local-manufacturing-of-meko-a200-frigate/
https://www.naval-technology.com/projects/meko-a-class-combat-ship/

https://www.globalsecurity.org/military/world/europe/meko-a300-specs.htm
![image](https://user-images.githubusercontent.com/99632305/160748071-7a45710f-5469-4af9-bb56-e3f56bd02a92.png)

![D3TcozEWkAEPJVB](https://user-images.githubusercontent.com/99632305/160751056-ce8fe8ee-b4fd-4a6c-9ea6-28bc3714e4c2.jpg)

**Comment by bostonmyk** [comment]
Looks like the Pennant number ended up being  904. https://twitter.com/mahmouedgamal44/status/1539131496535150592

**Comment by bostonmyk** [comment]
https://twitter.com/D__Mitch/status/1582361232778022912
127/64 LW (with VULCANO?), 2 x Narwhal 20mm RWS, 2 x 16-cell VLS for VL MICA / VL MICA NG SAM, 8 x MM40 Block3 EXOSET SSM, 2 x 2 MU90 TTs, 2 x MASS DLS and C-GUARD (2 x DL-6T?) DLS with CANTO.

**Comment by bostonmyk** [comment]
https://twitter.com/D__Mitch/status/1582994610665959424
 R-ESM (Vigile 100?), L-ESM (COLDS NGB?), MIRADOR Mk2  EOS-FCS, Sperry Marine navigation radars (X/S-band), NS110 AESA radar, ALTESSE-H C-ESM & COMINT, STIR 1.2 EO Mk2 FCR, an EOS (new from Thales?) and is FFBNW R-ECM (SCORPION 2?).

**Comment by Jkryos** [comment]
Added DB3K 497.
