### ISSUE TITLE
Egypt Pohang Class Corvette x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#813]
### DB Selector

DB3K

### Hypothetical

No

### Name

1000 Shab Misr

### Class

Pohang-class

### Country

Egypt

### Service

Navy

### In Commission

2017-

### Length (m)

88.3

### Beam (m)

10.2

### Draft (m)

2.88

### Standard Displacement (t)

950

### Full Displacement (t)

1220

### Complement

95

### Primary Propulsion Type

Diesel

### Propulsion

CODOG: 1 General Electric LM-2500 gas turbine / 2 MTU 12V956 TB82 diesels

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

4000 @ 15

### Sensors

- X-band & S-band navigational radars
- Raytheon AN/SPS-64(V)5B surface search radar
- Signaal (Thales Nederland) WM-28 Fire Control System
- Signaal (Thales Nederland) LIOD optronic director
- Raytheon AN/SQS-58 hull mounted passive/active sonar
- ULQ-12K ECM suite

### Mounts

- 2× Loral Hycor Mk 34 RBOC Chaff and Decoy Launching System
- 2 × Oto Melara 76 mm/62 caliber Compact naval guns
- 2 × Otobreda 40mm L/70 twin naval guns
- 2 × Mk 32 324mm triple torpedo tubes
- 2 × Mk 9 Depth Charge Racks (12)
- 6 × M2HB Browning .50 caliber machine guns
- 4x Protean decoy RL
- 2x TACM torpedo decoy launchers
- WSA-423 CCS

### Aircraft & Docking Facilities

- 2x davits for 7m RHIB

### Comms/Datalinks

Standard for Egypt

### Sources

https://en.wikipedia.org/wiki/ROKS_Jinju#/media/File:ENS_Shabab_Misr_visits_Kochi_(1).jpg
Janes 2003-04, pg 423
http://www.navypedia.org/ships/egypt/eg_es_shahab_misr.htm

![ENS_Shabab_Misr_visits_Kochi_(1)](https://user-images.githubusercontent.com/99632305/160752780-2a2abe6d-690f-4b93-835f-05c5dc6bd33f.jpg)

**Comment by Jkryos** [comment]
Added DB3K pre 507
