### ISSUE TITLE
Egypt Type 701C AOE x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#815]
### DB Selector

DB3K

### DBID to Copy

#1268 DB3k

### Hypothetical

No

### Name

230 Shaladein

### Country

Egypt

### Service

Navy

### In Commission

2003-

### Mounts

- 2x 40mm/70 Bofors (twin)
- 2x Breda 105mm SCLAR chaff launchers

### Sources

Janes 2003-04, pg 195

![093627l](https://user-images.githubusercontent.com/99632305/160757059-ce775b44-e052-4343-b371-d35a099691b8.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
