### ISSUE TITLE
Egypt Westerwald Type 760 x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#816]
### DB Selector

DB3K

### DBID to Copy

#1269 DB3K

### Hypothetical

No

### Name

231 Halayib

### Country

Egypt

### Service

Navy

### In Commission

2003-

### Sources

https://en.wikipedia.org/wiki/Westerwald-class_transport_ship
Janes 2003-04, page 195

![image](https://user-images.githubusercontent.com/99632305/160757711-61af9cdc-9e69-43bb-8887-bc883d333a0d.png)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
