### ISSUE TITLE
Egypt Fort Class x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#817]
### DB Selector

DB3K

### DBID to Copy

#1604 DB3K

### Hypothetical

No

### Name

ENS Abu Simbel

### Country

Egypt

### Service

Navy

### Sources

https://en.wikipedia.org/wiki/Fort_Rosalie-class_replenishment_ship
https://www.naval-technology.com/news/royal-navy-sells-ships-to-egypt-desa-royal-fleet-auxiliary-fort-austin-fort-rosalie/
https://www.forces.net/news/done-deal-first-royal-navy-ships-sold-egypt-30-years

![300px-Fort_Rosalie_class_replenishment_ship](https://user-images.githubusercontent.com/99632305/160759407-16249072-6d82-4ce3-a241-09b4c5b4ebe1.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494 as "Abu Simbel [Fort Class]", leaving off the navy designation as per DB convention.
