### ISSUE TITLE
Malaysia, Add Maharaja Lela class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#818]
### DB Selector

DB3K

### Baseline

#2885(FRA), #3087(EGY), #35144(GRC), #3585(UAE), #3533(ARG)

### Hypothetical

No

### Name

Littoral Combat Ship (LCS), 2501, Maharaja Lela

### Class

Maharaja Lela (Gowind 2500)

### Country

Malaysia

### Service

Navy

### In Commission

2025 - 

### Length (m)

111

### Beam (m)

16

### Draft (m)

3.85 (5.1 over sonar)

### Standard Displacement (t)

3000

### Full Displacement (t)

2730

### Complement

106 (src1), 138 (src3)

### Max Sea State

9

### Primary Propulsion Type

Diesel

### Propulsion

4x CODAD MTU 20V1163 M94, 2 waterjets

### Flank Speed (kt)

28

### Range (nm) at Speed (kt)

5000 @ 15

### Sensors

1 x SMART-S Mk 2 3D surveillance radar
2 x Sharp-eye navigation radars
2x Rheinmetall TMX-EO3 Fire-control radars
2 x Rheinmetall TM-EO2 e/o tracking systems
1 x Captas-2 LF Act/Pas var.Depth sonar
1 x Vigile Radar-ESM system

### Mounts

2 x 4 NSM SSM (8 NSM)
16 x MICA SAM (Sylver VLS)
1 x single - 57/70 SAK-57 Mk 3, 
2 x single - 30/75 DS-30B
2 x single - 12.7/90
2 x triple J+S torpedo launcher
2 x SuperBarricade decoy
1 x Vigile Radar-ECM

### Aircraft & Docking Facilities

1 x Landing platform 
1 x Hanger
for Helo/Uav up to 10t, (EC725, AS555, Super Lynx 300)
2 x  RHIB with davits in closed (RCS) compartment

### Comms/Datalinks

L11, L16, TUUM-6, TSB3520 (MilPer)

### Comments

6 units planned
Endurance 21 days

### Sources

1: https://www.navypedia.org/ships/malaysia/mal_es_maharaja_lela.htm
2: https://mymilitarytimes.blogspot.com/2018/08/malaysian-navy-maharaja-lela-class.html
3: https://en.wikipedia.org/wiki/Maharaja_Lela-class_frigate
4: https://mymilitarytimes.blogspot.com/2018/08/malaysian-navy-maharaja-lela-class.html
5: https://militaryleak.com/2021/11/19/royal-malaysian-navy-to-receive-first-maharaja-lela-class-littoral-combat-ship-in-2025
6: https://www.malaysiandefence.com/dry-launch-for-lcs
7: https://www.naval-technology.com/projects/maharaja-lela-class-littoral-combat-ships
![1](https://user-images.githubusercontent.com/99532490/160794640-522a1a40-c314-4e10-9ca3-c4e58ff4ba6d.jpg)
![2](https://user-images.githubusercontent.com/99532490/160794649-6267e3fa-d8aa-4065-9559-71fd966c327c.jpg)
![3](https://user-images.githubusercontent.com/99532490/160794652-cfba9e8e-3b0f-48ba-ab06-f5c58e4bff37.jpg)
![4](https://user-images.githubusercontent.com/99532490/160794656-46821de9-b899-400a-b24c-8d177b6a686a.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
