### ISSUE TITLE
Malaysia, Add Tempur001 (CB90HEX) class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#819]
### DB Selector

DB3K

### Baseline

#3266(GRC), #3467(SWE), #3468(SWE)

### Hypothetical

No

### Name

Fast Landing Craft, 001, -

### Class

Tempur (Combatboat 90HEX)

### Country

Malaysia

### Service

Navy

### In Commission

1998 - present

### Length (m)

15.9

### Beam (m)

3.8

### Draft (m)

0.8

### Standard Displacement (t)

13

### Full Displacement (t)

19

### Complement

3 to 5

### Primary Propulsion Type

Diesel

### Propulsion

2 x  Caterpillar 3406E, 2x waterjet

### Fuel Capacity (kg)

2.5 tons

### Flank Speed (kt)

45

### Range (nm) at Speed (kt)

240 @ 30

### Sensors

1x Furuno 1834 I-band navigation radar

### Mounts

1x 7.62mm/90

### Comments

Military Load: 20 troops or 2.8 tons of Cargo
Numbers in class 17 (5xCB90, 12 CB90HEX)

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/malaysia/mal_ls_001.htm
3: https://www.dockstavarvet.se/references/malaysia/
4: https://www.straitstimes.com/asia/se-asia/missing-malaysian-gunboat-found-with-all-crew-members-safe-but-hungry
5: https://en.wikipedia.org/wiki/CB90-class_fast_assault_craft
![1](https://user-images.githubusercontent.com/99532490/160802266-c04fc357-65a9-4abb-b5e1-033eb2fa6701.jpg)
![2](https://user-images.githubusercontent.com/99532490/160802271-940023bd-bc13-4319-8c53-a7a919654b88.jpg)
![3](https://user-images.githubusercontent.com/99532490/160802273-7dca6811-8dc0-4dd3-86ec-bc457c650d82.jpg)
![4](https://user-images.githubusercontent.com/99532490/160802279-d1953706-b2f0-4dbc-8169-9bd77266de39.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
