### ISSUE TITLE
Please consider to update the load out of the Mirage-2000 of India with the Popeye ASM

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#82]
### DB Selector

DB3K

### User(s)

#3798 Mirage 2000H-5 of India

### Weapons Carried

#3798 Mirage 2000H-5 of India is observed with a Popeye ASM, and its datalink pod, 2 drop tanks of 1700 ltr, 2 Mica IR on the outermost wing and a single Mica EM on the fuselage.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://twitter.com/LASD_off/status/1489924342469337091?t=1O4XHfPNyMWRIHeUxg1iLQ&s=19
https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fthedefenstar%2Fposts%2F2664077233843688
https://twitter.com/zone5aviation/status/1314037259914498048
https://www.reddit.com/r/Land_Air_Sea_Defense/comments/sl3zit/an_indian_mirage2000i_with_a_popeye_a2g_missile/?utm_source=ifttt
![BF58F228B7A84BD8947CBFCA3B0AC7D5 (1)](https://user-images.githubusercontent.com/60408110/153772714-f782a148-03e4-494f-8d3b-97b7711f3517.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 493 for the H-5s. Apparently India picked up the Popeyes back in 2004 (IS 2006) but I'm not sure when/if they started fielding them on the old Mirages and what those loadouts would have looked like. So I've added this one for now, and if we get more info on their Popeye employment, we can add more down the line.
