### ISSUE TITLE
Malaysia, Add Sri Indera Sakti class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#820]
### DB Selector

DB3K

### Hypothetical

No

### Name

Logistic Support Ship, 1503, Sri Indera Sakti

### Class

Sri Indera Sakti

### Country

Malaysia

### Service

Navy

### In Commission

1980 - present

### Length (m)

100

### Beam (m)

15

### Draft (m)

4.75

### Standard Displacement (t)

1800

### Full Displacement (t)

4300

### Complement

140

### Primary Propulsion Type

Diesel

### Propulsion

2 x Deutz S/BMV6540, 2x CPP

### Fuel Capacity (kg)

1300 tons

### Flank Speed (kt)

16.5

### Range (nm) at Speed (kt)

4000 @ 15

### Sensors

2 x KH T-1007 I-band navigation radars
1x DR3000 RESM
1x CT Naja EO

### Mounts

1x single 57/70 SAK-57 mk1
2x single 20mm/90 GAM-B01

### Aircraft & Docking Facilities

Helicopter deck for small Helicopter
2x RHIB

### Comments

The second (of 2) unit has different parametrics: 1504 Mahawangsa (post seperate)
Miltary load: 1800 t of cargo (inc. 1300 t of fuel, 200 t of fresh water) or 17 tanks or 600 troops, 80 passengers
Transfer stations on either beam an aft. light jackstay on both sides and a 15t crane for Replenishment at sea.

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/malaysia/mal_ls_sri_indera_sakti.htm
3: MilPer 2011
4: https://militaryasset.blogspot.com/2016/06/kapal-sokongan-armada-pelbagai-peranan.html
5: https://en.wikipedia.org/wiki/KD_Sri_Indera_Sakti
![a1](https://user-images.githubusercontent.com/99532490/160823914-2b5552d7-7788-495c-8821-c418e768b865.jpg)
![a2](https://user-images.githubusercontent.com/99532490/160823917-1de218a2-5c5c-40bc-adec-9e3b786d00ad.jpg)
![a3](https://user-images.githubusercontent.com/99532490/160823923-cacfd99c-81b5-4967-a935-9a3767cf0096.jpg)
![a4](https://user-images.githubusercontent.com/99532490/160823926-6426ed6b-632c-4ff8-b908-a25b32e46160.jpg)
![a5](https://user-images.githubusercontent.com/99532490/160823927-ea2409f7-c04b-47ba-89fe-920eb268bf6b.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
