### ISSUE TITLE
Malaysia, Add: Mahawangsa (Sri Indera Sakti cl)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#821]
### DB Selector

DB3K

### Hypothetical

No

### Name

Logistic Support Ship, 1504, Mahawangsa

### Class

Sri Indera Sakti

### Country

Malaysia

### Service

Navy

### In Commission

1983 - PRESENT

### Length (m)

103

### Beam (m)

15

### Draft (m)

5

### Standard Displacement (t)

1800

### Full Displacement (t)

5000

### Complement

129

### Primary Propulsion Type

Diesel

### Propulsion

2 x Deutz S/BMV6540, 2x CP Props

### Fuel Capacity (kg)

1300 tons

### Flank Speed (kt)

16.5

### Range (nm) at Speed (kt)

4000 @ 15

### Sensors

2 x KH T-1007 I-band navigation radars
DR3000 RESM
CT Naja EO

### Mounts

1x single 57/70 SAK-57 mk1
2x single 20mm/90 GAM-B01

### Aircraft & Docking Facilities

Helicopter deck able to carry 1x Sikorsky S-61A
2x RHIB (crane)

### Comments

Second unit in Sri Indera Sakti class (entry 820)
Military load: 410 t of ammunition, 17 tanks, 11 3-ton trucks, 50 passengers,
The 680m² vehicle deck equipped by side ramps can also accommodate up to 600 troops.
Transfer stations on either beam an aft. light jackstay on both sides and a 15t crane for Replenishment at sea.

### Sources

1: JFS 2015-2016
2: MilPer 2011
3: https://www.navypedia.org/ships/malaysia/mal_ls_sri_indera_sakti.htm
4: https://militaryasset.blogspot.com/2016/06/kapal-sokongan-armada-pelbagai-peranan.html
5: https://en.wikipedia.org/wiki/KD_Mahawangsa
![b1](https://user-images.githubusercontent.com/99532490/160826379-3f90d95f-b982-400c-b82f-c7770b2f3ce4.jpg)
![b2](https://user-images.githubusercontent.com/99532490/160826381-818c0138-a18a-4cf6-937b-fab7cfedf512.jpg)
![b3](https://user-images.githubusercontent.com/99532490/160826382-aa860417-02af-48dd-85ad-2befea2c81a5.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
