### ISSUE TITLE
RFI: Ships w/ Drone Catapults

### ISSUE THREAD

**Issue by PygmalionOfCyprus** [PygmalionOfCyprus/cmo-db-requests#822]
We've just recently overhauled the way we treat small UAVs, adding a number of new aircraft sizes to reflect UAV-specific classifications and two new "Runway Lengths."

![image](https://user-images.githubusercontent.com/87087226/160853093-1a509a77-5136-4a0e-affa-653dd09540ef.png)![image](https://user-images.githubusercontent.com/87087226/160852872-9ad295d2-ba4a-4cec-ab32-469e11f1ac25.png)

The idea is that small, hand-launched UAVs can be stored in effectively infinite numbers (cargo/weight allowing) and launched/recovered from _any_ platform, regardless of whether it has any dedicated aircraft facilities; for larger tactical drones (such as the RQ-7), the new catapult launchers will enable properly-equipped platforms to launch these without also gaining the ability to launch and recover helicopters, etc.

Issue #804 is a good example: the Hendijan-class can launch Class I UAVs, but to give it a helipad (as the old implementation demanded) would give it a capability it doesn't have. I know that there are other ships out there which carried drone launch/recovery equipment as part of their standard mission kit: the Iowa-class and its RQ-2s come to mind.

**Please comment if you know of other ships with permanently attached drones / drone launch capability!**

A few things to note:
- Any ship with existing aircraft facilities is capable of [wheeling out a catapult](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/ScanEagle_recovery_on_USS_Oscar_Austin.jpg/1280px-ScanEagle_recovery_on_USS_Oscar_Austin.jpg); when one loads a Class I UAV onto those ships, it can be safely assumed that the crew are also bringing aboard the necessary launch/recovery gear. We therefore don't need to add catapults separately for those vessels. One exception to this: ships with dedicated catapults _in addition_ to their regular aircraft facilities, enabling them to launch/recover without pausing regular flight operations. 
- Pretty much any ship can theoretically operate a catapult-launched UAV, and there are numerous news articles, examples, etc. reflecting this. I'd like to empower mission makers to add/remove Aircraft/Docking Facilities to platforms just as they can currently add/remove mounts, sensors, etc. so scenario designers can add this functionality if the mission calls for it. In the DB, however, I'll only be adding catapults for ships that have persistent, dedicated catapult capabilities; in other words, when a player spawns said ship, there should be a catapult by default because there is IRL. (See YV-3 Targeteer, Hendijan, Iowa, etc.)
- Manually-launched drones will be launchable from anywhere without a catapult, so some guy throwing a quadcopter off the side of his Boston Whaler doesn't count.
- We aren't distinguishing between JATO/RATO and traditional pneumatic catapults at this time.

Anyway, sorry for _droning_ on.

**Comment by KLABDB3K** [comment]
Top of my head Russian Buyan gunboat and Buyan M with SSM both have trialled with Orlan 10 UAV with a catapult launch and net recovery system. Will find a photo or other refs in due course.

**Comment by tbrandon517** [comment]
US Mk5 SOC would be a candidate. Here launching a Scan Eagle.

![image](https://user-images.githubusercontent.com/99599482/160879875-5a5f37e8-029c-4851-a8d0-c8e211f1c89e.png)

**Comment by bostonmyk** [comment]
Ship 2678 Kingston

https://www.youtube.com/watch?v=m_H3hVq8638

**Comment by bostonmyk** [comment]
RQ-21 off San Antonio's 2599 and 3230 
https://www.youtube.com/watch?v=J4uJ4yShEDA

**Comment by bostonmyk** [comment]
Scan Eagle of Spanish Perry's- Santa Maria 1400, 2065

https://www.youtube.com/watch?v=PQcy3R00g-o

**Comment by bostonmyk** [comment]
Scan Eagle off Legend Class Cutter #2431

https://www.youtube.com/watch?v=i5VM4DBCoiE

**Comment by bostonmyk** [comment]
Seagull #3142

https://www.defensenews.com/industry/techwatch/2020/07/09/elbit-combines-uav-with-unmanned-naval-vessel/

**Comment by bostonmyk** [comment]
Ship 2555 Cyclone

https://www.defensemedianetwork.com/stories/uss-zephyr-pc-8-counters-illicit-trafficking-in-caribbean/

**Comment by bostonmyk** [comment]
Historical YV-3 Targeteer. LSM with drone catapults. 1960-69

https://www.history.navy.mil/content/history/nhhc/our-collections/photography/numerical-list-of-images/nara-series/usn/USN-1060000/usn-1066963-uss-targeteer--yv-3-.html

https://en.wikipedia.org/wiki/USS_Targeteer

**Comment by cdnice55** [comment]
Canada - Kingston Class

http://www.navy-marine.forces.gc.ca/en/innovation/innovation-view.page?doc=advanced-unmanned-aircraft-to-provide-eye-in-the-sky-for-kingston-class-ships/jsagj4mt

https://www.unmannedsystemstechnology.com/2018/02/canadian-navy-integrate-maritime-uas-capabilities/

**Comment by claudejdev** [comment]
- _3136 - P 88 Victory [FPB-62] (Singapore - 2013)_
> (existing Aircraft facilities could then be converted to that new Cat launcher)
> https://daisetsuzan.blogspot.com/2020/09/victory-class-missile-corvettes-quirky.html
> https://archive.ph/20120804191201/http://www.mindef.gov.sg/imindef/news_and_events/nr/2012/may/15may12_nr.html

- 1396 - F 781 D Estienne D Orves [A 69] (France - 1997)
> (still in service in the waiting for the next gen OPV)
> https://www.meretmarine.com/fr/defense/le-dvf-2000-teste-avec-succes-par-la-marine-francaise
> http://www.opex360.com/2021/02/12/la-dga-commande-22-mini-drones-aeriens-pour-les-fregates-legeres-et-les-patrouilleurs-de-haute-mer/
> https://defense-militaire.over-blog.com/2022/01/combien-coute-l-acquisition-de-systeme-de-mini-drones-aeriens-embarques-pour-la-marine-smdm.html

(hypothetical)
- 2638 - P 61 Samuel Beckett (Ireland - 2014) 
> It should be noted also that the Samuel Beckett class OPVs have an expanded deck area at the stern that will allow in the future the Naval Service to potentially deploy unmanned aerial vehicles (UAV) for the first time.
> https://www.navalanalyses.com/2017/06/the-irish-naval-service-fleet-today.html

- 3251 - P355GR (Greece - 2020)
> https://www.navalanalyses.com/2020/10/cnv-p355gr-new-coastal-patrol-vessels.html

- #642 
> https://www.navalanalyses.com/2020/12/castor-class-coastal-patrol-vessels-of.html


Comment : it seems to me that about any OPV could operate a catapult launched UAV, thanks to the flexibility of that system. I expect the SE Asian/South American navies which received SeaScan recently to do it at the first opportunity, eg.
Maybe that

**Comment by PygmalionOfCyprus** [comment]
Yeah, one clarification here (that I probably should have made clearer in the OP):

As @claudejdev points out, pretty much any ship can theoretically operate a catapult-launched UAV, and there are numerous news articles, examples, etc. reflecting this. As part of these changes I'd like to see players empowered to add/remove Aircraft/Docking Facilities to platforms just as they can currently add/remove mounts, sensors, etc. That way, in cases like the aforementioned Mk5 SOC, scenario designers can add this functionality if the mission calls for it -- but the DB won't treat it as a "default" capability. (As that picture demonstrates, the catapult is fairly bulky; most Mk5s are not driving around with one.)

This RFI is more aimed at ships that have persistent, dedicated catapult capabilities; in other words, when a player spawns said ship, there should be a catapult by default because there is IRL. There are probably not very many of these.

The Targeteer is a good example, as is the Singaporean Victory-class (looks like they committed to permanent catapult installation); so too are the aforementioned Iowa (demonstrated consistent drone employment) and Hendijan-class ships.

**Comment by PygmalionOfCyprus** [comment]
@cdnice55 hand-launched drones like the Puma are covered:

> small, hand-launched UAVs can be stored in effectively infinite numbers (cargo/weight allowing) and launched/recovered from any platform, regardless of whether it has any other dedicated aircraft facilities

**Comment by KLABDB3K** [comment]
Russia wise the Orlan-10 on the Karakurt appeqrs to be an established practice and in use, although it seems to "land" via parachute and an inflatable on the water, which is going to impact on the turn round time massively and the sea state ot can be launched in. I will keep checking. 
The Raptor is just a trial by the look of it.

**Comment by bostonmyk** [comment]
Saar 4.5 seems to have tried a fixed launcher for Green Dragon loitering munitions. https://www.navalnews.com/naval-news/2019/02/israeli-navy-saar-4-5-fast-attack-craft-fitted-with-iai-green-dragon/

**Comment by bostonmyk** [comment]
Here's Zala on a BK-16 

https://www.homelandsecurity-technology.com/projects/zala-421-16em-unmanned-aerial-vehicle/

**Comment by bostonmyk** [comment]
> Saar 4.5 seems to have tried a fixed launcher for Green Dragon loitering munitions. Not sure if these are ever used in the ISR role or something that fits in that launcher that is https://www.navalnews.com/naval-news/2019/02/israeli-navy-saar-4-5-fast-attack-craft-fitted-with-iai-green-dragon/

https://navalpost.com/the-new-launchers-on-the-saar-4-5-corvettes-of-idf/

**Comment by Parel803** [comment]
Maybe the Malaysian MEA Bagan Datuk class.

Recently, the Malaysian Coast Guard delivered the first of the six New Generation Patrol Coast (NGPC) boats, the KM Bagan Datuk, constructed by local company Destini Shipbuilding. Such a vessel can provide flexibility in performing a wide range of operational duties and security missions (antipiracy, fisheries polishing, anti-smuggling, borderline surveillance). It is worth of mention that the class is equipped with the Fulmar UAV system. 
![afbeelding](https://user-images.githubusercontent.com/99532490/161434347-b3390466-01a7-4342-bb2a-dfbd9566f5b4.png)

https://www.naval-technology.com/projects/km-bagan-datuk-class-patrol-craft/

Proposal entry #855

**Comment by KLABDB3K** [comment]
https://youtu.be/R6-Xa7nPEIo?t=1358
https://youtu.be/R6-Xa7nPEIo?t=1446

I appreciate this is Admiral Grigorvich but if they have to inflate a bouncy castle to get their drone back its not exactly speedy!!

**Comment by cdnice55** [comment]
> @cdnice55 hand-launched drones like the Puma are covered:
> 
> > small, hand-launched UAVs can be stored in effectively infinite numbers (cargo/weight allowing) and launched/recovered from any platform, regardless of whether it has any dedicated aircraft facilities

So will the handhelds be added as a cargo or easier to just add one generic hand launched UAV instead?

**Comment by gosnold** [comment]
French A69 (#1759) ,Floreal surveillance frigate (#2643) and POM patrol boats (https://fr.wikipedia.org/wiki/Patrouilleur_Outre-mer) will get one (starting this year), for the DVF 2000 Aliaca from Survey Copter (https://www.survey-copter.com/produits/aliaca/),

sources:
https://www.meretmarine.com/fr/defense/marine-nationale-une-premiere-capacite-operationnelle-du-smdm-esperee-cet-ete
https://www.meretmarine.com/fr/defense/drones-commande-des-11-premiers-smdm-pour-les-fregates-et-patrouilleurs-francais

Non upgraded Lafayette (#2519 ) will be reclassified as patrol boats and probably get it too

I'll open issues for POM and Aliaca if there are none

**Comment by PygmalionOfCyprus** [comment]
Added drone catapults to aforementioned extant ships that have catapults permanently installed. Ships not yet added will of course get theirs when we eventually add them.

Closing the RFI here; moving forward catapults should be requested the "usual" way, i.e. as an update or as part of a copy/addition request.
