### ISSUE TITLE
Update KLJ-7A's Range

### ISSUE THREAD

**Issue by Matharox** [PygmalionOfCyprus/cmo-db-requests#823]
### DB Selector

DB3K

### Affected DBID(s)

#5949

### Summary of Changes

Increase Max Range at least to 80 nm (150 km) for a target of RCS 5m2

### Sources

https://pbs.twimg.com/media/EVLDC_vUUAAJ5rH?format=jpg&name=900x900

**Comment by PygmalionOfCyprus** [comment]
Gotta love building radars with absolutely no idea of stats. Ah, well...when in doubt...

https://youtu.be/9fzM6ey9fo0

Fixed 494.
