### ISSUE TITLE
Finland Kuha-class Minesweeper x6 (Inshore)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#825]
### DB Selector

DB3K

### Hypothetical

No

### Name

Kuha 21

### Class

Kuha Class

### Country

Finland

### Service

Navy

### In Commission

1974

### Length (m)

31.6

### Beam (m)

6.9

### Draft (m)

2.0

### Standard Displacement (t)

127

### Full Displacement (t)

127

### Complement

14

### Primary Propulsion Type

Diesel

### Propulsion

2 × Cummins NT-380M diesel engines, 450 kW (600 bhp)

### Flank Speed (kt)

12

### Range (nm) at Speed (kt)

N/A

### Sensors

- 1x Decca Racal Navigation Radar: I-band
- 1x Reson Seabat 6012 mine avoidance; active high frequency
- 1x Generic Mechanical Cable Cutter Mine Sweep
- 1x Generic Magnetic & Accoustic Mine Sweep
- 1x Generic Mine Disposal Diver
- 1x Pluto ROV (maybe)

### Mounts

- 2x ZU 23mm/60 (twin)
- 1x 12.7mm MG

### Comms/Datalinks

Standard minesweeper

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Sources

https://en.wikipedia.org/wiki/Kuha-class_minesweeper_(1974)
Janes 2003-04, pg 211

**Comment by Jkryos** [comment]
Added DB3K 507.
