### ISSUE TITLE
Gabon Batral Type LST x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#826]
### DB Selector

DB3K

### DBID to Copy

#1261 DB3k

### Hypothetical

No

### Name

L05 President El Hadj Omar Bongo

### Country

Gabon 

### Service

Navy

### In Commission

1984-2016

### Sensors

- 1x DRBN-32 radar

### Mounts

- 2x 1 - 40/60 Mk 7 
- 1x 1 - 81/29 M29 mortar
- 2x 1 - 12.7/90

### Other Changes

- 340t cargo, 138 troops, 7 combat vehicles

- Second entry for 1997-2016: - 2x 1 - 40/60; + 1x 1 - 40/70 Breda-Bofors 564, 2x 1 - 20/90 F2, bow doors welded closed

### Sources

https://www.navypedia.org/ships/gabon/gab_ls_president_al_hadj_omar_bongo.htm
Janes 2003-04, Page 248

![gab_ls29](https://user-images.githubusercontent.com/99632305/160937303-83f1d74a-a34b-44eb-bf5e-4650791d0150.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
