### ISSUE TITLE
Add UAE Globaleye AEW 2020 (copy 4999)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#827]
### DB Selector

DB3K

### DBID to Copy

4999

### Hypothetical

No

### Name

GlobalEye AEW[G6000]

### Country

UAE

### Service

Airforce

### In Commission

2020

### Sensors

same

### Mounts

same

### Loadout Options

same

### Other Changes

Same as saudi model. 

### Sources

https://www.scramble.nl/military-news/second-saab-globaleye-for-uae-air-force-delivered
https://www.janes.com/defence-news/news-detail/uae-receives-second-globaleye-aewc-aircraft
https://www.airforce-technology.com/news/saab-uae-third-globaleye-aircraft/
https://www.timesaerospace.aero/features/defence/uae-in-the-swing-with-globaleye

Sipri Lines
2	Erieye SRSS	AEW radar	2015	2020	2	Part of $1.3 b deal; for modification of 2 Global-6000 transport aircraft from Canada to GlobalEye AEW&C/AGS aircraft
1	Erieye SRSS	AEW radar	2017	2021	1	Part of AED866 m ($238 m) deal; for modification of 1 Global-6000 transport aircraft from Canada to GlobalEye AEW&C aircraft.
2	Erieye SRSS	AEW radar	2020			For modification of 2 Global-6000 transport aircraft from Canada to GlobalEye AEW&C/AGS aircraft
2	Seaspray	MP aircraft radar	2015	2020	2	For 2 GlobalEye AEW&C aircraft from Sweden; SeaSpray-7500E version
     		1	Seaspray	MP aircraft radar	2017	2021	1	For 1 GlobalEye AEW&C/AGS aircraft from Sweden; SeaSpray-7500E version
     		2	Seaspray	MP aircraft radar	2020			For 2 GlobalEye AEW&C aircraft from Sweden; SeaSpray-7500E version

**Comment by PygmalionOfCyprus** [comment]
Added 494.
