### ISSUE TITLE
Malaysia, Add Sri Gaya class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#828]
### DB Selector

DB3K

### Hypothetical

No

### Name

Fast Troop Vessel (AP), 331, Sri Gaya

### Class

Sri Gaya

### Country

Malaysia

### Service

Navy

### In Commission

2001 - present

### Length (m)

37.5

### Beam (m)

7

### Draft (m)

1.1

### Standard Displacement (t)

Not found

### Full Displacement (t)

118

### Complement

8

### Primary Propulsion Type

Diesel

### Propulsion

4x MAN D2842 LE 408, 2 waterjets

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

1000 @ 14

### Sensors

- 1x Furuno I-band navigation radar

### Mounts

- 2x single 7.6mm/90 (src1&2)
- (or 1 single 20mm by some sources)

### Ship Codes

All Aluminum Construction

### Comments

- 2 units in class.
- Design based on Australian Wave Master fast-ferry monohull.
- 200troops + 4 tons cargo

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/malaysia/mal_ls_sri_gaya.htm
3: https://en.wikipedia.org/wiki/Sri_Tiga-class_fast_troop_vessel
4: https://mudzaffar.blogspot.com/2008/09/register-of-active-rmn-commissioned_1489.html
![1](https://user-images.githubusercontent.com/99532490/160999890-7b6cb10b-aaf6-444a-8dad-da80fe20842a.jpg)
![2](https://user-images.githubusercontent.com/99532490/160999900-896e23f8-10f7-4251-916e-98c2754cfa88.jpg)
![3](https://user-images.githubusercontent.com/99532490/160999902-3746921d-1e47-4b90-9c06-cb420c3b4c7e.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
