### ISSUE TITLE
Malaysia, Add Sri Perlis (Kedah) class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#829]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), 47, Sri Perlis

### Class

Sri Perlis (Sri Kedah)(Kris/Keris)

### Country

Malaysia

### Service

Navy

### In Commission

1976 - present (first unit). Sri Perlis 1968

### Length (m)

31.4

### Beam (m)

6

### Draft (m)

1.7

### Standard Displacement (t)

96

### Full Displacement (t)

109

### Complement

22

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU MD 655/18, 2 shafts

### Flank Speed (kt)

27

### Range (nm) at Speed (kt)

1400 @ 14

### Sensors

- (1x Racal Decca 616 I-band navigation radar (src1/2))
- 1x Image shows Furuno navigation radar I (src3)

### Mounts

- 2x single 40mm/70 Bofors 564
- 2x single 7.62mm/90 

### Ship Codes

Aluminum Superstructure Only

### Comments

- 2 units left in class for navy, reported active in 2019. Of the 23 units total were 15 transferred to the MMEA (now also stricken)
- First unit in class was Sri Kedah P3138 (stricken in 1976)
- Ref to Kris or Keris class, Vosper build, not being the Keris class China build sidenr 111

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/malaysia/mal_cf_sri_kedah.htm
3: https://www.youtube.com/watch?v=XpDkvYe7glc
4: https://en.wikipedia.org/wiki/Keris-class_patrol_craft
![5](https://user-images.githubusercontent.com/99532490/161007462-8e4b16f3-7079-4c98-bc7c-1de00c178444.jpg)
![6](https://user-images.githubusercontent.com/99532490/161007467-412ca6e6-a996-4947-9bda-30df0449032e.jpg)
![7](https://user-images.githubusercontent.com/99532490/161007470-f1a7c31c-10a7-4ccc-8374-69995aa4e0d2.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
