### ISSUE TITLE
Please update the #2783 SEA CEPTOR SAM missile also for surface targets

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#83]
### DB Selector

DB3K

### Affected DBID(s)

 #2783 SEA CEPTOR missile

### Summary of Changes

Please update the #2783 SEA CEPTOR missile for surface targets. 

HMS Portland used a Sea Ceptor missile in a surface-surface mode to take out a FIAC-type threat, validating the system's ability to hit targets such as swarming fast boats.

Doesn't have enough range to consider it a true anti-ship weapon, obviously. Small warhead is less of a limit (could still hurt pretty bad).

### Sources

https://www.royalnavy.mod.uk/news-and-latest-activity/news/2021/july/06/20210706-sea-ceptor
https://twitter.com/Gabriel64869839/status/1482046561957855235?t=o8nU9iDe0OVkQCome2M3Ag&s=19
https://twitter.com/Gabriel64869839/status/1482325827098447875

**Comment by PygmalionOfCyprus** [comment]
Fixed for 493.
