### ISSUE TITLE
Malaysia, Add Arau class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#830]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Schip (PL/PSOH), 8704, Arau

### Class

Arau (Nojima)

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2017 - present

### Length (m)

87

### Beam (m)

10.5

### Draft (m)

3.7

### Standard Displacement (t)

1524

### Empty Displacement (t)

993

### Complement

39

### Primary Propulsion Type

Diesel

### Propulsion

2x Fuji 8S40B, 2 shafts

### Flank Speed (kt)

19

### Range (nm) at Speed (kt)

8000 @ 14

### Sensors

2x JMA 1596 I-band navigation radar

### Mounts

- 1x single Oerlikon 35mm/90
- 1x single 20mm JM-61B Sea Vulcan 

### Aircraft & Docking Facilities

1x Helicopterdeck, was used by Bell 212 (JPN)

### Comments

ex-Oki PL-01, Nojima class (JPN)

### Sources

1: JFS 2015-2016 (JPN)
2: https://www.navypedia.org/ships/malaysia/mal_cg_arau.htm
3: https://www.maritimeoptima.com/public/vessels/pages/imo:8715596/mmsi:533130612/KM_ARAU.html
4: https://machinesforwar.blogspot.com/2017/06/malaysian-coastguard-ship-km-arau.html
5: https://defense-studies.blogspot.com/2017/06/mmeas-new-patrol-boat-from-japan-coast.html
![1](https://user-images.githubusercontent.com/99532490/161012754-5fb2e5eb-b4a8-4789-998d-c3ce5a07c268.jpg)
![2](https://user-images.githubusercontent.com/99532490/161012760-5741a529-36d1-4c9d-96ef-570417135428.jpg)
![3](https://user-images.githubusercontent.com/99532490/161012763-ed76aacf-4894-410c-b499-659958c79659.jpg)
![4](https://user-images.githubusercontent.com/99532490/161012768-06a345de-6f25-4d9e-81ce-2bcc9a8407c9.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
