### ISSUE TITLE
Please add davits/ROV crane, top speed and vessel`s draft correction for Alta-Class MCM

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#832]
### DB Selector

DB3K

### Affected DBID(s)

491 & 684 M 350 Alta 

### Summary of Changes

-Add 2x davits as the vessels were seen to be equipped with 2x davits and 2x RHIBs. and it were also seen to be carrying at least 2 ROVs. The blue circle is the davits and black circle is the RHIBs.
![image](https://user-images.githubusercontent.com/99646926/161052721-da797d4a-7fbf-4534-8583-4f7f4ae7fbd8.png)
![image](https://user-images.githubusercontent.com/99646926/161052796-41d30cf0-607d-4213-950c-79298e88820f.png)

-Change the ship`s draft from 0 m to 2.5 m
![image](https://user-images.githubusercontent.com/99646926/161054921-bd355d37-b46a-4131-968e-aee6eceb6f3a.png)

-Change the vessel`s top speed from current 23 knot to 30 knots. KNM Oksoy is basically the same as KNM Alta so they should be able to reach around the same top speed. 
![image](https://user-images.githubusercontent.com/99646926/161054044-fc3559c1-b7ff-40c6-8f87-2bbda6b9b1bf.png)

### Sources

https://www.globalsecurity.org/military/world/europe/knm-oksoy.htm
https://www.naval-technology.com/projects/oksoy/
https://en.wikipedia.org/wiki/Alta-class_minesweeper

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
