### ISSUE TITLE
Please add Underground Pier Facilities

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#833]
### DB Selector

Both

### Hypothetical

No

### Name

Structure (Underground Pier [Extra Large, 200-500m]) (for example)

### Facility Type

Supply

### Country

Generic

### Service

Generic

### Sensors

Same as generic piers already in the CMO DB. 

### Mounts

Same as generic piers already in the CMO DB. 

### Magazines

Same as generic piers already in the CMO DB. 

### Aircraft & Docking Facilities

Same as generic piers already in the CMO DB. 

### Comments

Underground Pier options, ideally replicating the current CMO pier sizes. They'll obviously be armoured / protected against anything other than bunker buster / specific penetration weapons. The vessels in them would also be granted some protection and not visible to most sensors (I'm not sure how the game models "Lacrosse" type satellites but apparently they can see through the Earth's surface to at least some extent). 

### Sources

https://en.wikipedia.org/wiki/Yulin_Naval_Base

https://edition.cnn.com/2020/08/21/asia/china-submarine-underground-base-satellite-photo-intl-hnk-scli/index.html

https://www.nbcnews.com/id/wbna3077885

**Comment by KushanGaming** [comment]
Done in DB3K for DB495.

**Comment by PygmalionOfCyprus** [comment]
\>ticket done
\>not closed for over a year

![1512983636968](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/aaf8c50b-1866-4d32-8837-630131525774)
