### ISSUE TITLE
Add Commandant Rivière Cold War Frigates (1962-1994)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#834]
### DB Selector

DB3K

### DBID to Copy

DB3k Ship 1609 or 1308 in CWDB

### Hypothetical

No

### Name

F 733 Commandant Rivière 

### Country

France

### Service

Navy

### In Commission

1962-1994

### Sensors

Same

### Mounts

Same torps, guns.
Add 2 pair exocet launchers
Decoys 2 Dagaie 10 barrel launchers-chaff and flares.

### Other Changes

There were 9 of these 
2 davits for 9m lcp

### Sources

http://netmarine.net/bat/ae/cdtriviere/index.htm
https://en.wikipedia.org/wiki/Commandant_Rivi%C3%A8re-class_frigate

**Comment by PygmalionOfCyprus** [comment]
Did a deep review of the Commandant Riviere for 494, including sensor/mount tweaks, Exocet installation, various versions w/ different propulsion, etc.
