### ISSUE TITLE
Add P 626 Gajabahu[Hamilton] 2019

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#837]
### DB Selector

DB3K

### DBID to Copy

2406 or 2407

### Hypothetical

No

### Name

P 626 Gajabahu[Hamilton]

### Country

Sri Lanka

### Service

Navy

### In Commission

2019

### Sensors

none

### Mounts

none

### Loadout Options

none

### Other Changes

Ex WHEC-720 Sherman

### Sources

https://en.wikipedia.org/wiki/Hamilton-class_cutter

[https://en.wikipedia.org/wiki/SLNS_Gajabahu_(P626)](https://en.wikipedia.org/wiki/SLNS_Gajabahu_%28P626%29)
[https://twitter.com/srilanka_navy/statu ... 0785073152](https://twitter.com/srilanka_navy/status/1151453590785073152)
https://twitter.com/srilanka_navy/status/1489557166122237954

**Comment by PygmalionOfCyprus** [comment]
Added 494; also gave it its rear ZU-23-2.
