### ISSUE TITLE
Add P625 Parakramabahu [Type 053H2G]

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#838]
### DB Selector

DB3K

### DBID to Copy

DB3k 346

### Hypothetical

No

### Name

P625 Parakramabahu

### Country

Sri Lanka

### Service

Navy

### In Commission

2019

### Sensors

Remove Type 517 Knife Rest
Remove 981 Jammer
Remove Sonars

### Mounts

Remove SSM
Remove SAM
Remove ASW rockets
Remove Decoy Launchers
Deck guns retained

### Other Changes

Ex Tongling

### Sources

https://twitter.com/ChinaEmbSL/status/1456877072635232264
https://en.wikipedia.org/wiki/SLNS_Parakramabahu_(P625)
https://twitter.com/srilankaglobal/status/1165063714145558533
http://www.dailynews.lk/2021/05/24/features/249955/pride-naval-fleet

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also stripped HQ-61 and 37mm FCR as the former wasn't needed and the latter appear to be down to optical guidance.
