### ISSUE TITLE
Please add land-based Hsiung Feng III for Taiwanese Navy

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#839]
### DB Selector

DB3K

### Hypothetical

No

### Name

SSM plt (Hsiung Feng III)

### Facility Type

SSM

### Country

Taiwan

### Service

Navy

### Dispersion Radius (m)

60

### Sensors

1x MK1 Eyeball

### Mounts

2x Hsiung Feng III Quad

### Comments

Below is the pics for references:
![image](https://user-images.githubusercontent.com/99646926/161172183-515aecaa-3780-4e69-9920-ba56b0ad6eba.png)
![image](https://user-images.githubusercontent.com/99646926/161172226-d56bb6f6-82a5-42a4-be02-a5484b232706.png)
![image](https://user-images.githubusercontent.com/99646926/161172381-89fa35ff-dcbd-4e1f-bf9a-c8b94ad8fc25.png)

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/year-2013-news/august-2013-navy-world-naval-forces-maritime-industry-technology-news/1196-roc-navy-unveils-land-based-hf-3-supersonic-anti-ship-cruise-missile-at-tadte-2013-show.html
http://china-defense.blogspot.com/2010/12/roc-navy-opens-missile-base-in-eastern.html
https://www.taiwannews.com.tw/en/news/4038843

**Comment by PygmalionOfCyprus** [comment]
Added 494.
