### ISSUE TITLE
Please update Israeli HAWK SAM phase-2 and 3 TV sensor range & max alt engagement range of the missiles

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#84]
### DB Selector

Both

### Affected DBID(s)

#788 & #793 & #503

### Summary of Changes

Israeli Hawk Phase 2 HPIs had an optical tracking system added for operation in an ECM environment. This device, called the Tracking Adjunct System (TAS), was positioned on top and between the two radar dishes. 

The Israelis have upgraded the Phase 2 standard with the addition of a Super Eye electro-optical TV system (DB sensor #503) for detection of aircraft at 30 to 40 km and identification at 17 to 25 km. 
Current DB detection range is 80 Nm.

Please have a look because the #503 sensor does not detect or ID aircraft during tests.
At present, for example an Alpha Jet, is sometimes detected only at 17 km, but more often when it is flying above the SAM site.. And not by the Super Eye sensor but the MK1 Eyeball.. This was tested at altitudes of FL360 and FL120.

Secondly:
They have also modified their HAWK SAM system for engagements at altitudes up to 24,000 m
The missile max engagement altitude is presently set at FL580, but can be adjusted to max FL787 (24.000m)
(so it will be able to engage a Syrian MiG-25 at FL60 )

Thirdly
#715 has no start date:
* 1965 March the first HAWK battalion was deployed to Israel.

### Sources

https://en-academic.com/dic.nsf/enwiki/776038
https://www.seniorennet.be/forum/viewtopic.php?p=2341767&sid=80aaf6cf319d9ec5008593949234342b

**Comment by PygmalionOfCyprus** [comment]
I just want to clarify the fix here.

Currently all the Israeli I-HAWKs are Super Eye-equipped. If I'm reading this correctly, only P2+ should be. Or should P2+ be receiving the TAS? Or both?

**Comment by Huib18** [comment]
Super Eye is only with P2, this is correct.

You also have a sharp eye ;-)

**Comment by PygmalionOfCyprus** [comment]
Fixed the IS dates and Super Eye timeline. Not knowing when exactly they made their missile altitude mods, I'm just assuming it came w/ P2.
