### ISSUE TITLE
#4222 F-35 Canada is no longer cancelled. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#840]
### DB Selector

DB3K

### Affected DBID(s)

#4222 F-35A Lightning II - 2026, Cancelled, new competition 2019

### Summary of Changes

Just change the title and in service dates? 
Possible and probable that it will have AIM-120D not C7 due to elapsed time.
88 ordered. 

### Sources

https://airrecognition.com/index.php/news/defense-aviation-news/2022-news-aviation-aerospace/march/8308-canada-to-buy-88-f-35-lightning-ii-fighter-jets-from-lockheed-martin.html
Amongst many.

**Comment by PygmalionOfCyprus** [comment]
Nothing like cancelling an aircraft acquisition in order to run a multi-year review concluding that you should have bought the aircraft after all.

**Comment by PygmalionOfCyprus** [comment]
Changed 494.
