### ISSUE TITLE
Please add Mesbah-1 for Islamic Republic of Iran Air Defense Force

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#842]
### DB Selector

DB3K

### Hypothetical

No

### Name

AAA Sec (ZSU-23-8, Mesbah-1)

### Facility Type

AAA

### Country

Iran

### Service

Air Defense Force

### Sensors

1x 3D Phased array radar(claimed to be able to track HARM from 30KM)
![image](https://user-images.githubusercontent.com/99646926/161233798-639d1ed1-d5d8-4908-a0f3-420b46b36beb.png)

1x EO/IR sensor
![image](https://user-images.githubusercontent.com/99646926/161233864-5fb0d8f9-5b9e-4307-aac4-4887c4b6c876.png)

*Notes: apparently the sensors were being equipped on separate container as per screenshot below:
![image](https://user-images.githubusercontent.com/99646926/161236215-f113fe2c-1efc-4eee-a9d0-2a5e312aad44.png)

### Mounts

1x Container equipped with 3D Phased array radar

1x Container equipped with EO/IR sensor

2x radar guided ZU-23-8(basically 4x ZU-23-2 slapped together)
![image](https://user-images.githubusercontent.com/99646926/161234458-1d0c6379-f1fa-4dc3-b41b-0794a5c6a9d9.png)

### Comments

This radar-guided ZU-23-8 were to have around the same PoH against air target as ZSU-23-4 Shilka (DBID 1844), which is 50% in CMO due to similar volume of fire (4000 rounds per minute) and both are radar-guided with Mesbah-1`s ZU-23-8 were also able to be guided by EO sensor.
![image](https://user-images.githubusercontent.com/99646926/161235298-e5ec3d1a-3086-4acf-b1d7-d2f37b90cb00.png)

Below pics is for the reference:
![image](https://user-images.githubusercontent.com/99646926/161235710-972465c6-6401-4d68-9c8e-0bc30fde7614.png)
![image](https://user-images.githubusercontent.com/99646926/161236595-8a9024ba-4c12-4381-b096-a755d78b6eb2.png)

Some were seen to be mounted on a truck as well
![image](https://user-images.githubusercontent.com/99646926/161236821-6ec98fc9-ae52-4aae-aee6-bcbdf6a5f1d3.png)

### Sources

https://www.armyrecognition.com/iran_iranian_army_light_heavy_weapons_uk/mesbah-1_mesbah_1_23mm_towed_anti-aircraft_eight-cannon_technical_data_sheet_specifications_pictures.html
https://www.uskowioniran.com/2010/05/mesbah-1-aaa-system.html
https://www.youtube.com/watch?v=w1esK8KDatw
https://en.topwar.ru/20883-zenitnyy-malokalibernyy-avtomatizirovannyy-artkompleks-mesbah-1-iran.html

**Comment by Huib18** [comment]
Have you ever seen this outside the factory, or is this Hypothetical?

**Comment by capcop98** [comment]
> Have you ever seen this outside the factory, or is this Hypothetical?

Yes, the system were seen in one of the Iranian military exercise.
![image](https://user-images.githubusercontent.com/99646926/162097341-586b9588-1c40-4782-8b4e-f95ca8e94a66.png)

Source:https://twitter.com/jeremybinnie/status/748547641169092612

**Comment by Jkryos** [comment]
Added DB3K 499.
