### ISSUE TITLE
Copy CSB-8020 [Hamilton]

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#843]
### DB Selector

DB3K

### DBID to Copy

2407

### Hypothetical

No

### Name

CSB 8020 [Hamilton]

### Country

Vietnam

### Service

Coast Guard

### In Commission

2018

### Other Changes

x2 Ex Morganthau and Midgett

### Sources

https://twitter.com/AnnQuann/status/1467717195749019649
https://en.wikipedia.org/wiki/Vietnam_Coast_Guard
https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Acquisitions-CG-9/Newsroom/Latest-Acquisition-News/Article/2684024/former-coast-guard-cutter-en-route-to-vietnam/
https://www.youtube.com/watch?v=GY2_sWtNsFE

**Comment by Jkryos** [comment]
Added DB3K 494.
