### ISSUE TITLE
Add Vietnamest SSM Plt (SSC-3 Styx [4k51 Rubezh])

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#844]
### DB Selector

DB3K

### DBID to Copy

816

### Hypothetical

No

### Name

SSM Plt (SSC-3 Styx [4k51 Rubezh])

### Country

Vietnam

### Service

Army

### In Commission

1980

### Sources

https://twitter.com/annquann/status/1336995736395816965
https://twitter.com/AnnQuann/status/1204711123221504007
https://www.facebook.com/VietDefenseVN/posts/the-680th-brigade-of-the-vietnam-peoples-navy-recently-carried-out-a-training-dr/1639004479591061/
And in this episode of sitting on the missile
https://twitter.com/AnnQuann/status/1491642806355783680

**Comment by Jkryos** [comment]
Added DB3K 494.
