### ISSUE TITLE
UK Typhoon #4948 loadout #27247

### ISSUE THREAD

**Issue by StanleyDeRolmate** [PygmalionOfCyprus/cmo-db-requests#845]
### DB Selector

DB3K

### Affected DBID(s)

#4948 #27247

### Summary of Changes

The GBU-24 loadout (#27247) of the RAF Typhoon FGR.4 (#4948) currently also includes 4 CPU-123's.

### Sources

CMO DB

**Comment by PygmalionOfCyprus** [comment]
Removed CPU-123s in 494.
