### ISSUE TITLE
Algeria FPB 98 Class x21

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#846]
### DB Selector

DB3K

### Hypothetical

No

### Name

334 Deneb

### Class

FPB-98 Class

### Country

Algeria

### Service

Navy

### In Commission

2009-

### Length (m)

31.8

### Beam (m)

6.3

### Draft (m)

1.2

### Standard Displacement (t)

100

### Complement

13

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar C32 Diesels; 2x waterjets

### Flank Speed (kt)

30

### Range (nm) at Speed (kt)

900@14

### Sensors

- 2x Furuno Navigation Radar

### Mounts

- 1x 30-mm DS-30B

### Aircraft & Docking Facilities

1x Davit for 7m RHIB

### Comms/Datalinks

- VHF/UHF Radio

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Sources

Combat Fleets of the World, 16th Edition, pg 5
https://www.ocea-ssm.com/fpb-98

![fpb98-bandeau](https://user-images.githubusercontent.com/99632305/161367142-cc95c916-6fa9-43cd-8d14-c44892e15454.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
