### ISSUE TITLE
RAAF MQ-9B SkyGuardian Acquisition Cancelled

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#848]
### DB Selector

DB3K

### Affected DBID(s)

5196

### Summary of Changes

Air 7003, the CASG project to acquire a MALE UCAV has been cancelled to free up funding for recruitment. Was expected the MQ-9B would be acquired, but that is no longer the case. Update description and title for 5193 to reflect this.

### Sources

https://asiapacificdefencereporter.com/speculation-that-air-7003-armed-ucav-project-to-be-cancelled/
https://adbr.com.au/raaf-air-7003-skyguardian-uas-cancelled/
https://www.defenceconnect.com.au/strike-air-combat/9785-mq-9b-skyguardian-project-axed

**Comment by Jkryos** [comment]
Updated DB3K 494.
