### ISSUE TITLE
Transfer Ship Mysytari to Langkawi, Malaysia

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#851]
### DB Selector

DB3K

### Affected DBID(s)

Ship #209 (160 Musytari, Malaysia navy)

### Summary of Changes

- The Navy Musytari is in 2006 transferred from the navy the the MMEA(CG).
- Langkawi class with sidnr 7501
- Both units transferred

- Crew 70 + 10 extra
- Navigation radar changed to KH T1007
- added 1x single 57mm/70 SAK-57 Mk 1 (src1)
- delete 100mm/55 (src1)

### Sources

1: https://www.navypedia.org/ships/malaysia/mal_es_musytari.htm
2: pdf on Malyasian CG, page 2
3: https://www.vesseltracker.com/en/Ships/Km-Langkawi-7501.html
![1](https://user-images.githubusercontent.com/99532490/161424295-a7be8f80-fe09-42ac-add1-50b38d5355d7.jpg)
![2](https://user-images.githubusercontent.com/99532490/161424296-05fff584-9790-4ca9-938e-486ecfa425bf.jpg)
![3](https://user-images.githubusercontent.com/99532490/161424297-c92dde52-ccc3-4c4b-a5f9-4c1cba64b4d2.jpg)
[KELAS KAPAL APMM 2021 NEW.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8404322/KELAS.KAPAL.APMM.2021.NEW.pdf)

**Comment by Jkryos** [comment]
Added DB3K 494.
