### ISSUE TITLE
Malaysia, Add Perwira class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#852]
### DB Selector

DB3K

### Baseline

#2744, Australia

### Hypothetical

No

### Name

Patrol Boat (PB), 3801, Perwira

### Class

Perwira (Bay, Australia)

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2015 - present

### Length (m)

38

### Beam (m)

7.3

### Draft (m)

2.2

### Standard Displacement (t)

Not found

### Full Displacement (t)

134

### Complement

24 + 5

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 16V2000 M70

### Flank Speed (kt)

24

### Range (nm) at Speed (kt)

1000 @ 20

### Sensors

2x Nucleus2 5000 ARPA radars (I & E/F on image)

### Mounts

SMASH 30mm RWS (src3 & on later image)

### Aircraft & Docking Facilities

2x RHIB (image) with crane

### Comments

2 units in class

### Sources

1: PDF page 3
2: https://www.navypedia.org/ships/malaysia/mal_cg_perwira.htm
3: https://www.malaysiandefence.com/firing-trials-km-bagan-datuk
![1](https://user-images.githubusercontent.com/99532490/161425877-4f8183fe-96db-4df0-86eb-d5a7b25e1169.jpg)
![2](https://user-images.githubusercontent.com/99532490/161425878-010c0908-f390-49be-8a62-9b78ec88f3e6.jpg)
[KELAS KAPAL APMM 2021 NEW.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8404380/KELAS.KAPAL.APMM.2021.NEW.pdf)

**Comment by Jkryos** [comment]
Added DB3K 496.
