### ISSUE TITLE
France - LSD L 9021 Ouragan (Deep Review)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#854]
_So, I had a fascinating reading on that ship from a book just unboxed from the attic, had a chat with former crew and felt like it would be worth spending some hobby hours to bring up a few details to your attention.
Hope that you'll have as much fun as I did.
Cheers_ 🚢 

---

### DB Selector

DB3K 493

### Affected DBID(s)

|ID |Name|
|---|---|
|1155|L 9021 Ouragan -- France (Navy) , 1993-0, -|
|1156|L 9021 Ouragan -- France (Navy) , 1969-0, -|
|1890|L 9021 Ouragan -- France (Navy) , 1998-2007, -|

---
- [x] **General data**

**DataShip** [^1] [^2] [^3]   

Please _modify_
- Type = 4015 (LSD - Dock Landing Ship)
- Name = L 9021 Ouragan [TCD 60]
- (1890 only) Name = L 9022 Orage [TCD 60]
- (1155 only) Comments = Simbad
- (1890 only) Comments = OP3A
- (1156 only) YearCommissioned = 1965
- (1156 only) YearDecommissioned = 1993
- (1155 only) YearDecommissioned = 2002
- (1890 only) YearCommissioned = 1995
- Height = 42
- DisplacementStandard = 7300
- DisplacementFull = 8500
- Cargo_Area = 1584
- (1155 and 1156) Crew = 240
- (1155 and 1156) Cargo_Crew = 340
- (1890 only) Cargo_Crew = 350

- [x] **Properties**

 **DataShipCodes**  [^1]

Please _add_ Refuel to Starboard x 1 (Out), Refuel from Starboard x 1 (In), Replenish to Port x 1 (Out) and Replenish from Port x 1 (In):

ID | CodeID
---| ---
1155 | 8005
1155 | 8106
1155 | 9001
1155 | 9101
1156 | 8005
1156 | 8106
1156 | 9001
1156 | 9101
1890 | 8005
1890 | 8106
1890 | 9001
1890 | 9101

```diff
+ # 8005 Refuel to Starboard x 1 (Out)
+ # 8106 Refuel from Starboard x 1 (In)
+ # 9001 Replenish to Port x 1 (Out)
+ # 9101 Replenish from Port x 1 (In)
```

- [x] **Fuel**

**DataFuel**  
- please create a _new entry_ of Type _3001_ (Diesel), and Capacity of _740000_ (740 tons)

**DataShipFuel**  [^1]

Please _modify_ (113 m³ of TR5/JP5 fuel are held aboard, at 0.8195 kg/m³, thus 92 tons) :
ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 1 | 290
1156 | 1 | 290
1890 | 1 | 290

```diff
- # 290 Aviation Fuel x 8500
+ # 1744 Aviation Fuel x 92210
```

Please _modify_ (with that new 740 tons of Diesel fuel entry) :
ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 2 | 114
1156 | 2 | 114
1890 | 2 | 114

```diff
- # 114 Diesel Fuel x 36000
+ # NEW Diesel Fuel x 740000
```
</p>
</details>

- [x] **Performance Details**

**DataPropulsionPerformance**  [^1][^4]

Let's deal with her propulsion, the 1178 2x SEMT-Pielstick 12 PC2 Vxxx Diesels (which it's the sole user)

> With 740 tons of diesel, their range is :
> - 7400 nm at 17 knots
> - 9 000 nm at 15 knots
> - 15 000 nm at 12 knots
> (no data at 5 knots though. I leave it to your best judgement )
> My cat have computed that it would translate, in kg/min, to : 
> - (740000/(15000/12))/60 = 9.86666666667
> - (740000/(9000/15))/60 = 20.5555555556 
> - (740000/(7400/17))/60 = 28.3333333333

So what I suggest doing here is :

ID | AltitudeBand | Throttle | Speed | AltitudeMin | AltitudeMax | Consumption
---| --- | ---| --- | --- | --- | --- 
1178| 1| 1| 5| 0.0| 0.0| 0.9
1178| 1| 2| 15| 0.0| 0.0| 1.0
1178| 1| 3| 16| 0.0| 0.0| 1.89
1178| 1| 4| 17| 0.0| 0.0| 3.75

```diff
- # Throttle 2 Speed 15 Consumption 1.0
+ # Throttle 2 Speed 12 Consumption 9.87
- # Throttle 3 Speed 16 Consumption 1.89
+ # Throttle 3 Speed 15 Consumption 20.55
- # Throttle 4 Speed 17 Consumption 3.75
+ # Throttle 4 Speed 17 Consumption 20.55
```

- [x] **Sensors/EW**

 **DataShipSensors**  [^1] [^2] [^3] 

Please _add_ a, forward facing, 2133 AN/SQS-17A to 1156 L 9021 Ouragan -- France (Navy) 1969 only.

ID | ComponentNumber | ComponentID
---| ---| ---
1156 | 5 | 2133

```diff
+ # 2133 AN/SQS-17A
```

Please _remove_ the DRBV 51A Triton [TRS 3035]. 

<kbd>Observer mixed it up with the look-alike NRBI21 IFF antenna. [^1]  pg.205, note 48.</kbd> 

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 3 | 1160
1156 | 3 | 1160
1890 | 3 | 1160

```diff
- # 1160 - DRBV 51A Triton [TRS 3035]
```
Please _replace_ the two Decca 1226 by _1x_ DRBN 32 and _1x_ Decca 202 on the 1965 variant.

<kbd>The Decca 1226 was installed in 1972 and 1980. A proper description may mention it.</kbd>

ID | ComponentNumber | ComponentID
---| ---| ---
1156 | 4 | 3761
1156 | 5 | 3761

```diff
- # 3761 Decca 1226
+ # 1959 DRBN 32 [Decca 1226]
+ # 2144 Decca 202
```

Please _replace_ the Decca 1226 with a DRBN 34 on 1993 and 1995 variants
ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 4 | 3761
1155 | 5 | 3761
1890 | 6 | 3761
1890 | 7 | 3761

```diff
- # 3761 Decca 1226
+ # 1969 DRBN 34 [Decca 1229]
```
<kbd>As for the Telegon 4 (165) and the ARBR 16 (1133), I haven't seen any mention. And that kind of equipment is more often seen aboard frigates. I just can't tell for sure one way or the other, so I would suggest to keep as is, until proven otherwise.</kbd>
</p>
</details>

- [x] **Mounts (Guns/Launchers/Ejectors/etc.)**

**DataShipMounts**  [^1]

- please _change_ the Twin 40mm Bofors, it's a Single one. [^1]

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 3 | 205
1155 | 4 | 205
1156 | 3 | 205
1156 | 4 | 205
1156 | 5 | 205
1156 | 6 | 205

```diff
- # 205	40mm/60 Twin Bofors
+ # 993	40mm/60 Single Bofors
```
- please _remove_ the Bofors from the 1995 variant, she had none.

ID | ComponentNumber | ComponentID
---| ---| ---
1890 | 3 | 205
1890 | 4 | 205

```diff
- # 205	40mm/60 Twin Bofors
```

- please _remove_ the 4x 12.7mm/50 MG from the 1965 variant.

ID | ComponentNumber | ComponentID
---| ---| ---
1156 | 7 | 561
1156 | 8 | 561
1156 | 9 | 561
1156 | 10 | 561

```diff
- # 561	12.7mm/50 MG
```

- please _remove_ the 30 mm gun from the pre-1995 variants. It wasn't aboard before.

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 1 | 103
1155 | 2 | 103
1156 | 1 | 451
1156 | 2 | 451

```diff
- # 451	30mm/75 Twin Oerlikon GCM-AO1 UK, 1969
- # 103	30mm/75 Twin Oerlikon GCM-AO2 UK
```

- please _change_ the 30mm gun that's left. It actually is the 30mm/82 Breda/Mauser, same as on the Foudre.

ID | ComponentNumber | ComponentID
---| ---| ---
1890 | 1 | 103
1890 | 2 | 103

```diff
- # 103	30mm/75 Twin Oerlikon GCM-AO2 UK
+ # 1093 30mm/82 Compact OTO-Breda/Mauser Mk30 1989
```
---
**DataMountDirectors**  [^1]
Let's take a moment to add the Vigy Director for that 30mm gun, as part of the OP3A self-defense system.

ID | ComponentNumber | ComponentID
---| ---| ---
1093 | 3 | 3497
1093 | 4 | 3498
1093 | 5 | 3499

```diff
+ # 3497	Vigy 105 [CCD]
+ # 3498	Vigy 105 [IR]
+ # 3499	Vigy 105 [Laser Rangefinder]
```

(Does adding a sensor group as Director works by the way ? If so : 2190 - DIBC-2A Vigy 105)

- [x] **Magazines**

 **DataShipMagazines**  [^1]

Let's now adapt the magazine to the new Mounts' settings

- please _remove_ the 12.7mm/50 MG magazine of the 1965 Ouragan variants.

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 1 | 760

```diff
- # 760	12.7mm/50 MG 4x Mounts
```

- please _change_ the Twin 40mm Bofors magazine to the Single one.

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 2 | 771

```diff
- # 771	40mm/60 Twin Bofors	2x Mounts
+ # 261	40mm/60 Single Bofors 2x Mounts
```
ID | ComponentNumber | ComponentID
---| ---| ---
1156 | 3 | 1054

```diff
- # 1054	40mm/60 Twin Bofors	4x Mounts
+ # 1344	40mm/60 Single Bofors	4x Mounts
```

- please _remove_ the Bofors magazine of the 1995 variant.

ID | ComponentNumber | ComponentID
---| ---| ---
1890 | 2 | 771

```diff
- # 771	40mm/60 Twin Bofors	2x Mounts
```

- please _remove_ the 30 mm gun magazine of the pre-1995 Ouragan variants.

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 4 | 36
1156 | 2 | 818

```diff
- # 36	30mm/75 Twin Oerlikon GCM-AO2 2x Mounts
- # 818	30mm/75 Twin Oerlikon GCM-AO1 2x Mounts
```

- please _change_ the 30 mm gun magazine to match the 30mm/82 Breda/Mauser mount.

ID | ComponentNumber | ComponentID
---| ---| ---
1890 | 4 | 36

```diff
- # 36	30mm/75 Twin Oerlikon GCM-AO2 2x Mounts
+ # 465	30mm/82 Compact OTO-Breda/Mauser Mk30 2x Mounts
```
---
- [x] **DataMagazine**  [^1]
- please _copy_ ID 288 AS.12 HMS Endurance
- change its Comments to "L 9021 Ouragan"
- change Capacity = 20

**DataShipMagazines**
- then _add_ this new magazine to 1156 L 9021 Ouragan -- France (Navy), 1969. 
  There was 20 AS.12 stored, just in case.

ID | ComponentNumber | ComponentID
---| ---| ---
1156 | 5 | NEW

- [x] **Comms/Datalinks**

**DataShipComms**  [^1]

Please _add_ a Syracuse  2 satcom to 1993 and 1995 variants

ID | ComponentNumber | ComponentID |	ParentSpecific 
---| ---| ---| ---
1156 | 6 | 306 | 1
1890 | 6 | 306 | 1

```diff
+ # 306	Syracuse II SATCOM
```
<kbd>As for the Link 10 (210), I haven't seen any mention of it. As for now, I just can't tell if it was there or not, so I would suggest to keep as is, until proven otherwise.</kbd>

- [x] **Aircraft Facilities**

**DataShipAircraftFacilities** [^1] [^6]

Please _modify_ 

<kbd>there's no hangar, but an open spot which can hold up to two Super Frelon sized helo</kbd>

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 1 | 26
1156 | 1 | 26
1890 | 1 | 26

```diff
- # 26 Hangar (4x Medium Aircraft (12.1-18m Long))
+ # 19 Open Parking (2x Large Aircraft (18.1-26m Long)) 
```

Please _modify_ 

<kbd>there is one Small sized pad</kbd>

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 2 | 57
1156 | 2 | 57
1890 | 2 | 57

```diff
- # 57 Pad (1x Medium Aircraft (12.1-18m Long))
+ # 49 Pad (1x Small Aircraft (0-12m Long))
```
Please _modify_ 

<kbd>plus two Large sized pad, one of which on a mobile deck</kbd>

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 3 | 57
1155 | 4 | 57
1156 | 3 | 57
1156 | 4 | 57
1890 | 3 | 57
1890 | 4 | 57

```diff
- # 57 Pad (1x Medium Aircraft (12.1-18m Long))
+ # 28 Pad (1x Large Aircraft (18.1-26m Long))
```

- [x] **Docking Facilities**

**DataShipDockingFacilities**  [^1]

Please _modify_ 
<kbd>8 Medium sized LCM fits in. Since there's no such Dock Well, I believe that the easiest way to do it is to use a 4x Large sized Dock</kbd>
ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 1 | 17
1156 | 1 | 17
1890 | 1 | 17

```diff
- # 17 Dock Well (2x Medium Dock (LCM, 17.1-25m Long))
+ # 4 Dock Well (4x Large Dock (LCU/LCAC, 25.1-45m Long))
```

<kbd>Note : 2 Very Large sized LCU (59m) should be able to fit in. However, the game engine doesn't have such a Physical state, yet?</kbd>

Please _add_ (a couple LCVP sized davit and 3 RHIB sized davit) :

ID | ComponentNumber | ComponentID
---| ---| ---
1155 | 2 | 9
1156 | 2 | 9
1890 | 2 | 9
1155 | 3 | 39
1156 | 3 | 39
1890 | 3 | 39

```diff
+ # 9 Davit (2x Small Dock/Davit (LCVP, 11.1-17m Long))
+ # 39 Davit (3x Very Small Dock/Davit (0-11m Long))
```

- [x] **2002 variant**

2002 Copy [^1][^7]

<kbd>Ouragan : in 2002, her intermediate mobile deck was welded to fit a pair if new diesel generator on. Only 2 LCM could then fit. </kbd>

Please _copy_ the now modified 1155 - L 9021 Ouragan (France - 1993).

- Comments = PMI welded
- YearCommissioned = 2002
- YearDecommissioned = 2007
- Cargo_Crew = 360

**DataShipDockingFacilities**
Please _modify_ 

ID | ComponentNumber | ComponentID
---| ---| ---
NEW | 1 | 4

```diff
- # 4 Dock Well (4x Large Dock (LCU/LCAC, 25.1-45m Long))
+ # 17 Dock Well (2x Medium Dock (LCM, 17.1-25m Long))
```

</details>

- **Mortars ?**
<kbd>On the Ouragan only, there was a pair of old 120mm mortar, dismounted in 1990.
The crew mentioned how impractical they were and seldom used.
If you absolutely want to include them, let me know. I have no specs for now, but that they had 180 rounds each.  [^8][^9]</kbd>

- **Trivia**
*there's a 16 750 liters reserve of wine aboard.* 🍷 

---

### Sources

[^1]: Moulin, J., & Maurand, P. (2004). TCD, les transports de chalands de débarquement. Rennes: Marines éd.
[^2]: [Marine | Patrimoine | Histoire | La Marine d'hier | Les bâtiments de surface | Ouragan (L 9021)](https://web.archive.org/web/20160124213232/http://www.defense.gouv.fr/marine/patrimoine/histoire/la-marine-d-hier/les-batiments-de-surface/ouragan-l-9021)
[^3]: [Marine | Patrimoine | Histoire | La Marine d'hier | Les bâtiments de surface | Orage (L 9022)](https://web.archive.org/web/20160124235309/http://www.defense.gouv.fr/marine/patrimoine/histoire/la-marine-d-hier/les-batiments-de-surface/orage-l-9022)
[^4]: [Archives TCD ORAGE](http://archives.tcd.orage.free.fr/)
[^5]: [Canon de 40mm Bofors](http://netmarine.net/f/armes/40mm/index.htm)
[^6]: http://archives.tcd.orage.free.fr/histoire/histor21.jpg
[^7]: http://tcdouragan.free.fr/0007/photos/divers2001/divers2001_03.jpg
[^8]: https://i.servimg.com/u/f84/20/24/15/22/ae0c2610.jpg
[^9]: https://i.servimg.com/u/f84/20/24/15/22/f6003010.jpg

- [TCD Ouragan transport de chalands de debarquement de la marine nationale 1964 - 2007](http://tcdouragan.free.fr/)
- [Anciens Cols Bleus et Pompons Rouges - OURAGAN (TCD)](https://www.anciens-cols-bleus.net/t1515-ouragan-tcd)
- Gardiner, R., Chumbley, S., & Budzbon, P. (1995). Conway's all the world's fighting ships, 1947-1995. Annapolis, Md: Naval Institute Press. Pg. 125-126
- Saunders, S. (2002). Jane's fighting ships, 2002-2003. Coulsdon, Surrey, UK: Jane's Information Group. Pg. 233
- In Hooton, E. R. (1997). Jane's naval weapon systems. Coulsdon, Surrey: Jane's Information Group, Ltd.
- [p3d.in - TCD Orage](https://p3d.in/VIsht/spin) (The .50 are missing but still, it looks good! ID 1890)

**Comment by PygmalionOfCyprus** [comment]
Is it only on my end that all the sub-sections have disappeared?

**Comment by claudejdev** [comment]
I still see them Ethan

Le ven. 20 mai 2022 à 03:44, Ethan Hermanson ***@***.***> a
écrit :

**Comment by claudejdev** [comment]
@PygmalionOfCyprus I've removed the expandable content tag. Let me know if there's anything else to make it more convenient to you.

**Comment by PygmalionOfCyprus** [comment]
Yep, now I can see them. Not sure what was going on -- the expandable tags on other posts were/are still working fine. It was just this one that suddenly stopped being expandable for me. Thanks!

**Comment by PygmalionOfCyprus** [comment]
Handled all for 495. Also created 1972 and 1990 variants of Ouragan w/ Decca 1226 and mortars removed, respectively.

**Comment by PygmalionOfCyprus** [comment]
Also, re: the Sensor Groups, those basically just act as a way to easily add/cue a bunch of sensors all at once. That way, for stuff like EO/IR balls, we can just add the one group (and be sure we haven't forgotten anything) instead of manually adding each component.

So yes, you can treat those as directors!
