### ISSUE TITLE
Malaysia, Add Bagan Datuk class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#855]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Craft (PC), 4541Bagan Datuk

### Class

Bagan Datuk

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2017 - present

### Length (m)

44.3

### Beam (m)

7.7

### Draft (m)

1.95

### Standard Displacement (t)

Not found

### Full Displacement (t)

297

### Complement

27 + 14

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 12V 4000 M70 M73

### Flank Speed (kt)

24

### Range (nm) at Speed (kt)

2000 @ 12

### Sensors

1x KH navigation radar I-band
1x KH navigation radar E/F-band
1x FLIR (scr4)

### Mounts

1x single 30mm/80 SMASH
2x single 12.7mm/90

### Aircraft & Docking Facilities

1x Maritime Aerovision Fulmar UAS, Thales (src3), The UAS is launched using a catapult launcher located behind the vessel’s main armament. It is recovered by a net-based impact-absorbing system at the aft.
1x larger RHIB with crane.

### Comments

Fassmer design. 
6 units in class.

### Sources

1: pdf (page7)
2: https://www.navypedia.org/ships/malaysia/mal_cg_bagan_datuk.htm
3: https://en.wikipedia.org/wiki/Bagan_Datuk-class_patrol_vessel
4: https://www.malaysiandefence.com/second-ngpc-operational
5: https://www.malaysiandefence.com/sgpv-laksamana-lcs
6: https://www.malaysiandefence.com/km-bagan-datuk
![1](https://user-images.githubusercontent.com/99532490/161434133-9984d984-2842-49ce-a4f7-b7309eaaabdc.jpg)
![2](https://user-images.githubusercontent.com/99532490/161434135-083ff7e7-fe6f-4479-a004-78e29e612165.jpg)
![3](https://user-images.githubusercontent.com/99532490/161434136-fb4561ef-4682-454a-9538-d6c841b158ea.jpg)
![4](https://user-images.githubusercontent.com/99532490/161434137-af0f371b-f1a6-420b-baa1-ff59a4c946cc.jpg)
[KELAS KAPAL APMM 2021 NEW.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8404782/KELAS.KAPAL.APMM.2021.NEW.pdf)

**Comment by Jkryos** [comment]
Added DB3K 496.
