### ISSUE TITLE
CWDB_493, Mount 3048, Infantry Section [7.62mm Rifle] : Cargo Mass and Space

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#856]
### DB Selector

CWDB

### Affected DBID(s)

3048 Infantry Section [7.62mm Rifle] Infantry

### Summary of Changes

> P Gatcomb reported on Discord that the Infantry Section [7.62mm Rifle] weighs 0.8 T and takes up 16 space, while the Infantry Section [7.62mm MG/Unguided Infantry Anti Tank Weapon] weighs 0 and takes up no cargo.
> 
> So what is suggested here is to harmonize the two by setting the value of these two parameters to zero, based on _2948 Infantry Section [7.62mm MG/Unguided Infantry Anti Tank Weapon]_.

- [ ] **DataMount**

ID | Name
---| ---
3048 | Infantry Section [7.62mm Rifle]
- Cargo_Mass
```diff
- # 0.8
+ # 0.0
```
- Cargo_Area
```diff
- # 16.0
+ # 0.0
```

### Sources

field_medic — Today at 2:12 PM
https://discord.com/channels/557667391438454800/557675190738485272/960149804414013490

**Comment by Jkryos** [comment]
Fixed CWDB 494.
