### ISSUE TITLE
Malaysia, Add Rhu class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#857]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), 2601, Rhu

### Class

Rhu (Siri 200; P202)

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2007 - present (MMEA), 1990 -2007 (Fishery Department)

### Length (m)

26.9

### Beam (m)

5.8

### Draft (m)

1.9

### Standard Displacement (t)

Not found

### Full Displacement (t)

100

### Complement

15 + 5

### Primary Propulsion Type

Diesel

### Propulsion

2x Deutz 16M816CR, 2 shafts

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

Not found

### Sensors

1x I-Band navigation radar, Furuno (image)

### Mounts

Small arms

### Sources

1: JFS 2015-2016
2: PDF image
3: https://www.navypedia.org/ships/malaysia/mal_cg_p202.htm
![1](https://user-images.githubusercontent.com/99532490/161435513-20b22d89-3369-45d8-85ca-982226cbd351.jpg)
![2](https://user-images.githubusercontent.com/99532490/161435515-7126fcb1-503f-43bd-9431-a89d2e71d57a.jpg)
![3](https://user-images.githubusercontent.com/99532490/161435516-9a3a3215-2e8f-481c-a985-01e65a2f100a.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
