### ISSUE TITLE
DRBN 32 [Decca 1226], should be as Decca 1226

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#858]
### DB Selector

DB3K

### Affected DBID(s)

1959 DRBN 32 [Decca 1226]

### Summary of Changes

> Radar DRBN 32 [Decca 1226] is supposed to be a Decca 1226 put into French service. However its parameters differs in the DB.
> 
> So what is suggested here is to harmonize the two by mirroring the DRBN 32 [Decca 1226] values.

- [ ] **DataSensor**

ID | Name
---| ---
1959 | DRBN 32 [Decca 1226]
- RangeMax
```diff
- # 20.0
+ # 25.0
```
- ResolutionAngle
```diff
- # 2.0
+ # 1.2
```
- RadarHorizontalBeamwidth
```diff
- # 2.0
+ # 1.2
```
- RadarVerticalBeamwidth
 ```diff
- # 2.0
+ # 25.0
```
- RadarPRF
 ```diff
- # 600
+ # 650
```

### Sources

DB3K_493

**Comment by claudejdev** [comment]
Couldn't find a confirmation that the DRBN 32 actually is a Decca 1226.
However, Friedman does mention it : 
![image](https://user-images.githubusercontent.com/35732829/161577814-6b4ed1ad-f09d-4e8d-9456-578b6185285e.png)
_Friedman, N. (1989). The Naval Institute guide to world naval weapons systems. Annapolis: Naval Institute Press._

**Comment by Jkryos** [comment]
Updated DB3K 494.
