### ISSUE TITLE
Modify SAR/CSAR helicopter loadout to carry a small number of downed pilots

### ISSUE THREAD

**Issue by K1l0tangoDef3nce** [PygmalionOfCyprus/cmo-db-requests#859]
### DB Selector

Both

### Affected DBID(s)

any helicopter that has SAR/CSAR loadout.

### Summary of Changes

Helicopters with SAR/CSAR loadout cannot pick up downed pilots that are created when a scenario has SAR/CSAR script
What I do propose, is to add the ability every helicopter that has SAR/CSAR loadout to be able to carry 2 to 6 downed pilots depending on its size.
I know it's a huge job because of the amount of data entries but it would be useful to have that ability.

### Sources

https://www.lockheedmartin.com/content/dam/lockheed-martin/rms/documents/s-92/Sikorsky-S92-search-rescue-helicopter-brochure.pdf
https://www.airforce-technology.com/projects/hh-60w-combat-rescue-helicopter-crh/
https://www.lockheedmartin.com/en-us/products/sikorsky-hh-60w-combat-rescue-helicopter.html
https://www.airforce-technology.com/projects/sikorsky-hh-60g-pave-hawk-combat-search-rescue-helicopter/
https://www.airforce-technology.com/projects/as532-cougar-helicopter/
https://www.airforce-technology.com/projects/hh-101a-caesar-medium-lift-helicopter/
https://www.airforce-technology.com/projects/seaking/

**Comment by KLABDB3K** [comment]
Not sure entirely what you mean?
They can, its dependant on the LUA script to enable that function in the "downed pilot" script?
so for example **SurvivorsS.SAR_enabled=true**
E.g
local Mu=ScenEdit_UnitX() -- GRABS THE UNIT SHOT DOWN
local MuC= Mu.crew -- CHECKS IT HAS A CREW
print (MuC)
local elevation = World_GetElevation({latitude=Mu.latitude, longitude=Mu.longitude}) --GETS LAND OR WATER THE UNIT WAS OVER
print (MElav)
if elevation < 0 then do -- CREATES ONE LIFE RAFT AS PER THE NUMBER OF CREW IF OVER WATER
local i= 1, Mu.crew
    for planes = 1, Mu.crew, 1 do
local SurvivorsS =
ScenEdit_AddUnit({
    type='ship',
    dbid=2553,
    side='Aircrew',
    name=Mu.name .. " " .. "Aircrew".." "..planes,
    guid=Mu.guid .." ".."Aircrew".." "..planes,
    latitude=Mu.latitude,
    longitude=Mu.longitude})
**SurvivorsS.SAR_enabled=true**  -- **ENABLES IT TO BE RECOVERED AS SAR**
end

**Comment by K1l0tangoDef3nce** [comment]
I am aware of the LUA script. What I want is to be able to pick up those created crew. How are SAR loadouts until now you can't pick up these guys as a cargo because there is no cargo room in the SAR loadout

**Comment by PygmalionOfCyprus** [comment]
The amount of work this will require is vastly disproportionate to the result, esp. since "CSAR/SAR" is basically entirely handled through Lua anyway. Whether a pilot is actually being carried as "cargo" or not isn't really important to gameplay: if you absolutely, positively _have_ to pick up a pilot at Point A and then actually physically place him down in Point B (as opposed to just getting "recovery points" or whatever for a successful RTB) that can be dealt with on a per-scenario basis via Lua.
