### ISSUE TITLE
Multiple Russian load outs using export AA-11 not domestic AA-11

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#86]
### DB Selector

DB3K

### Affected DBID(s)

Multiple Russian load outs using export AA-11 not domestic AA-11

### Summary of Changes

The following Russian air force load outs are using the #2003 - AA-11 Archer [R-73M1] --1998, HMS, Export 
They  should be using the domestic Russian 
#2053 - AA-11 Archer [R-73M]
The mismatch with the other loads for the aircraft creates a need for two AA-11 entries in each magazine etc and complicates logistics. 
Aircraft impacted are most RuAF/VKS Su-30SM. Su-35 etc

Affected load outs:

#26997 AS-17 Krypton C [Kh-31P, ARM] (SEAD, ARM, Land/Naval)
#26998 AS-17 Krypton C [Kh-31P, ARM], Long-Range (SEAD, ARM, Land/Naval)
#26999 AS-18 Kazoo [Kh-59M], APK-9 Datalink Pod (Standoff Strike, Land/Naval)
#26997 AS-17 Krypton C [Kh-31P, ARM] (SEAD, ARM, Land/Naval)
#26998 AS-17 Krypton C [Kh-31P, ARM], Long-Range (SEAD, ARM, Land/Naval)
#26999 AS-18 Kazoo [Kh-59M], APK-9 Datalink Pod (Standoff Strike, Land/Naval)
#21753 AS-17 Krypton C [Kh-31P, ARM] (SEAD, ARM, Land/Naval)
#21754 AS-17 Krypton C [Kh-31P, ARM], Long-Range (SEAD, ARM, Land/Naval)
#21757 AS-11 Kilter [Kh-58UShK, ARM] (SEAD, ARM, Land/Naval)
#21758 AS-11 Kilter [Kh-58UShK, ARM], Long-Range (SEAD, ARM, Land/Naval)
#21755 AS-17 Krypton D [Kh-31PD, ARM] (SEAD, ARM, Land/Naval)
#21756 AS-17 Krypton D [Kh-31PD, ARM], Long-Range (SEAD, ARM, Land/Naval)

### Sources

See DB3k 492 et all.

**Comment by Jkryos** [comment]
Fixed DB3K 493.

**Comment by KLABDB3K** [comment]
Thank you.
