### ISSUE TITLE
1.8m Life raft single person [Aircrew Survival Raft] Single person life raft. Non civilian. Generic. Naval - possibly three variants Basic Normal and Enhanced/Advanced?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#860]
### DB Selector

Both

### Baseline

#2553 5m Civil raft

### Hypothetical

No

### Name

1.8m Life raft single person {Aircrew Survival Raft]

### Class

1.8m Life raft single person {Aircrew Survival Raft]

### Country

Generic

### Service

All

### In Commission

Since they had inflatable boats but 1944 first ejector seat?

### Length (m)

1.8

### Beam (m)

0.9

### Draft (m)

00.1

### Standard Displacement (t)

0.03

### Full Displacement (t)

0.1

### Empty Displacement (t)

0.03

### Complement

1

### Max Sea State

5

### Primary Propulsion Type

Sail

### Propulsion

A person

### Fuel Capacity (kg)

muscle

### Flank Speed (kt)

1kt

### Range (nm) at Speed (kt)

As far as you can paddle?

### Sensors

Mk1 Eyeball, possibly the Enhanced version gets NVG's or binos?

### Mounts

Nil unless the plucky survivor wants to duke it out with a sidearm or their knife?

### Aircraft & Docking Facilities

SAR Enabled true
You could have basic normal and enhanced variants of the one person raft:
Basic no comms,

Normal distress beacon / hand held insecure HF radio,

Enhanced Secure SATCOM or HF radio - Most NATO level countries?

### Comms/Datalinks

This is were you could have basic normal and enhanced variants of teh one person raft:
Basic no comms,
Normal distress beacon / hand held radio,
Enhanced Secure SATCOM or HF radio - Most NATO level countries? PLB ELB etc

### Ship Codes

Low Construction Standards

### Comments

Using LUA with one crew the raft is easier to create limits on how many persons you can "pick up" with your SAR and its more realistic for single aircraft bale outs etc.

### Sources

https://www.aeromiltec.com/liferafts/1manliferaft.html
![image](https://user-images.githubusercontent.com/99494755/161529712-bf1e30d9-d923-4175-a236-85e79abc8424.png)
https://www.aeromiltec.com/radiossurvivalplb.html
https://www.aeromiltec.com/radiossurvivalelt.html

**Comment by PygmalionOfCyprus** [comment]
_Become a fighter pilot, they said._

_Fighter pilots always look cool, they said._

![image](https://user-images.githubusercontent.com/87087226/161538383-79597dbd-7cdd-4db4-89cc-c34bf41f3c95.png)

**Comment by Jkryos** [comment]
Added DB3K 494
![](https://user-images.githubusercontent.com/87087226/161538383-79597dbd-7cdd-4db4-89cc-c34bf41f3c95.png)
