### ISSUE TITLE
Search And Rescue (SAR) loadout with a Maritime Surveillance role

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#861]
### DB Selector

DB3K

### Affected DBID(s)

30298 Search And Rescue (SAR)

### Summary of Changes

> Loadout 30298 'Search And Rescue (SAR)' is having a 'Maritime Surveillance' (7005) role set. However other such loadouts have a ''Search And Rescue (SAR)" (4101) role.
> 
> So what is suggested here is to harmonize the two by modifying the 30298 loadout role value.

- [ ] **DataLoadout**

ID | Name
---| ---
30298 | Search And Rescue (SAR)
- LoadoutRole
```diff
- # 7005	Maritime Surveillance
+ # 4101	Search And Rescue (SAR)
```

### Sources

DB3K_493

**Comment by Jkryos** [comment]
Updated DB3K 494.
