### ISSUE TITLE
Vessel`s length and magazine capacity correction for Fateh-class submarine

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#862]
### DB Selector

DB3K

### Affected DBID(s)

450 & 682 Fateh-class

### Summary of Changes

-change the vessel`s length from 35m to 48m
![image](https://user-images.githubusercontent.com/99646926/161667028-6ab13522-ece4-4729-b4ab-31b01b35f6b1.png)
![image](https://user-images.githubusercontent.com/99646926/161666915-2d83b619-595f-4a14-b258-083fd0720055.png)

-Magazine capacity from 8x torpedo to just 2x torpedo, as per the illustration from Hi Sutton only showed there is only enough space for 2 torps at best.
![image](https://user-images.githubusercontent.com/99646926/161667289-3ab80bed-967d-47ae-97eb-989820f54abb.png)

### Sources

http://www.hisutton.com/Fateh-Class_Submarine.html

**Comment by Jkryos** [comment]
Updated DB3k 494.
