### ISSUE TITLE
Please add TV & IR sensor on Sadral sextuplet Mistral mount

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#863]
### DB Selector

DB3K

### Affected DBID(s)

437 Sadral[Mistral] Sextuplet

### Summary of Changes

-Please add TV & IR sensor(probably 2nd Gen due to the facts Sadral were introduced in the early 90s) to Mount/437 Sadral[Mistral] Sextuplet as it were seen equipped with it. 
![image](https://user-images.githubusercontent.com/99646926/161762851-d07fb7e4-04bf-4587-9ccb-6e4455916fcf.png)
![image](https://user-images.githubusercontent.com/99646926/161763094-e9db36a6-b760-4998-8499-4f41eb3d7d1d.png)
![image](https://user-images.githubusercontent.com/99646926/161763196-432ca196-2c9e-442a-8b58-344f3e1ee5a1.png)

### Sources

https://weaponsystems.net/system/470-Sadral
https://forums.spacebattles.com/threads/french-ciws.255924/

**Comment by Jkryos** [comment]
Updated DB3K 494.
