### ISSUE TITLE
Add Pakistani Navy RAS-72 Sea Eagle [ATR-72 ASW] 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#864]
### DB Selector

DB3K

### DBID to Copy

2598

### Hypothetical

No

### Name

RAS-72-500 Sea Eagle [ATR-72 ASW]

### Country

Pakistan

### Service

Navy 

### In Commission

2019

### Sensors

Radar is Sea Spray 7300 so no change
FLIR is SAFIRE III (In DB)

### Mounts

Sonobouys

### Loadout Options

2 YU-7/MK-46

### Sources

https://www.youtube.com/watch?v=YeozSDHne20
https://quwa.org/2020/07/05/atr-72-maritime-patrol-aircraft-mpa/
https://www.janes.com/defence-news/news-detail/pakistan-navy-receives-second-atr-72-mpa
https://theaviationist.com/2020/06/28/pakistan-navy-atr-72-arrives-at-monchengladbach-to-be-upgraded-to-ras-72-500-sea-eagle/
https://militaryleak.com/2020/07/01/pakistan-navy-atr-72-converted-to-ras-72-500-sea-eagle/

Sipri Lines
2	ATR-72MP	ASW aircraft	2015	2018-2019	2	RAS-72 Sea Eagle version; Pakistani ATR-72 transport aircraft (acquired from 
1	ATR-72MP	ASW aircraft	2020			RAS-72 Sea Eagle version; Pakistani ATR-72 transport aircraft rebuilt in Germany to ASW aircraft

**Comment by Jkryos** [comment]
Added DB3K 494.
