### ISSUE TITLE
Add P 1027 Himmat [Azmat]

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#866]
### DB Selector

DB3K

### DBID to Copy

2544

### Hypothetical

No

### Name

P 1027 Himmat [Azmat]

### Country

Pakistan

### Service

Navy

### In Commission

2018

### Sensors

Add Generic ESM

### Mounts

Swap 25mm Type 87 Mount for 25mm STOP mount. (Ship 3314 has STOP Mounts)

### Other Changes

2nd two Azmats delivered slightly different. They mounted  ASELAN 25mm STOP deck guns.
There are photos of different missiles on the third unit for a test but subsequent photos seem to have the same quads as the rest.

### Sources

https://www.dawn.com/news/1348242
https://www.navyrecognition.com/index.php/naval-news/naval-exhibitions/dimdex-2022-exhibitors-visitors-information/dimdex-2022-news-official-show-daily/11531-dimdex-2022-pakistan-navy-showcases-fast-attack-craft-pns-himmat.html
https://youtu.be/tq0MCNHQ0UI?t=175

**Comment by Jkryos** [comment]
Added DB3k 494.
