### ISSUE TITLE
Argentina B 52 Hercules [Type 42], 2000 Transport Refit

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#868]
### DB Selector

DB3K

### Affected DBID(s)

1423

### Summary of Changes

Refit in 2000 which converted her to LPA removed Exocet, Sea Dart, torpedo tubes, Type 909 FCR, Type 184M hull-mounted sonar, and KH Type 162M bottom profiler.

### Sources

Naval Institute Guide to Combat Fleets of the World, 16th Edition, page 13

**Comment by bostonmyk** [comment]
https://www.navalanalyses.com/2014/06/hercules-multi-purpose-rapid-transport.html

**Comment by Jkryos** [comment]
Added DB3K 494.
