### ISSUE TITLE
Hobart Class Corrections

### ISSUE THREAD

**Issue by 52Novembers** [PygmalionOfCyprus/cmo-db-requests#869]
### DB Selector

DB3K

### Affected DBID(s)

2068

### Summary of Changes

Hobart Class DDG's have two davits for RHIBs, while they currently have none in game. The starboard one can be seen on Sydney during her commissioning.
![Hobart RHIB](https://user-images.githubusercontent.com/101542189/161962982-9a2377a5-fa97-4ada-a363-5c9342d0e460.jpg)
Their Wiki article lists them as having "2 × L-3 Communications SAM Electronics X-band navigation radars" probably in place of the generic surface search radars they have, but I couldn't find this anywhere else.

For weapons: Hobart's actually have fixed two-tube Mk32 Mod 9 torpedo sets, not the triple tube sets. This video is of Hobart and describes them as Mod 9s.
https://www.youtube.com/watch?v=K7O6dZnOB8M&t=10s
![Mk32 Description](https://user-images.githubusercontent.com/101542189/161963830-b5491d39-3e93-41e6-a415-b0bbf2d5d00b.PNG)
And finally they currently come from the DB carrying SM-6 missiles. The RAN/ADF/Govt has committed to obtaining SM-6s, NSMs (in place of Harpoons) and T-Hawks for the Hobarts, but none of these three are in service yet. 

### Sources

https://en.wikipedia.org/wiki/Mark_32_Surface_Vessel_Torpedo_Tubes
https://en.wikipedia.org/wiki/Hobart-class_destroyer
https://www.youtube.com/watch?v=K7O6dZnOB8M&t=10s
https://adbr.com.au/australian-to-buy-naval-strike-missile-fast-track-jassm-er-buy/

**Comment by Jkryos** [comment]
Updated DB3K 494.
