### ISSUE TITLE
OECM loadout option for SU-30SM and SU-35S

### ISSUE THREAD

**Issue by HyperGopher** [PygmalionOfCyprus/cmo-db-requests#87]
### DB Selector

CWDB

### User(s)

SU-30SM and SU-35S

### Weapons Carried

SAP-14 offensive jammer pod

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

810

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Would be cool to see a dedicated OECM loud-out option for the Su-30SM and SU-35s (or at least just the Su-30sm for now) with SAP-14 offensive jamming pod. Russian Airforce SU-34 usually have this pod, but it's possible for the SU-30SM and even Su-35s to equip it. Currently confirmed in active service for Su-30SM and Su-34 for Russian Airforce. Used as stand off/escort jammer similar to EA-6 Prowler or EA-18 Growler. (Deagel)

"The heavyweight high power KNIRTI SAP-14 Support Jammer ECM pod is a Russian analogue to the US ALQ-99E pod carried on the EA-6B Prowler and EA-18G Growler. It was developed for Flanker family aircraft and is carried on a large centreline pylon. To date little has been disclosed about this design, but it has been observed on the Su-30MK Flanker G/H and Su-34 Fullback. It operates between 1 GHz and 4 GHz" (Ausairpower)

So just an addon which allows normal air-air/air-ground loadouts but with the option for a SAP-14 OECM jammer pod for both SU-30SM and SU-35S.

### Sources

https://www.deagel.com/Protection%20Systems/SAP-14/a002474

http://ausairpower.net/APA-Su-35S-Flanker.html

**Comment by Jkryos** [comment]
Added DB3K 493.
