### ISSUE TITLE
Copy Bangladesh Mig-21MF Fishbed J (1973-1990)

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#870]
### DB Selector

DB3K

### DBID to Copy

3055

### Hypothetical

No

### Name

MIG-21MF Fishbed J

### Country

Bangladesh

### Service

Airforce

### In Commission

1973-1990

### Sensors

same

### Mounts

same

### Loadout Options

same

### Other Changes

Bought x12 +2 U variants

### Sources

https://twitter.com/StefanKnippsch3/status/1219750504173133829
http://www.mig-21.de/english/inservice.htm#bangladesh

Sipri Lines. Atoll and aircraft
(75)	K-13A	SRAAM	(1972)	1973	(75)	For MiG-21F combat aircraft
     		14	MiG-21MF	fighter aircraft	(1972)	1973	14	Second-hand; incl 2 MiG-21UM version

**Comment by Jkryos** [comment]
Added DB3K 494.

**Comment by PygmalionOfCyprus** [comment]
Reopening because we forgot to add the UMs & K-13s.

**Comment by Jkryos** [comment]
Corrected
