### ISSUE TITLE
Copy Bangladesh Hoku (P 8111 Durbar) IOC 1983-2018 x5

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#871]
### DB Selector

DB3K

### DBID to Copy

388

### Hypothetical

No

### Name

P 8111 BNS Durbar [Hoku]

### Country

Bangladesh

### Service

Navy

### In Commission

1983

### Sensors

same

### Mounts

same

### Loadout Options

Same

### Other Changes

They were grey. This will be way funnier after a few hundred more requests.

### Sources

http://files.balancer.ru/forums/attaches/2019/06/07-7569561-137417.jpg
http://files.balancer.ru/cache/forums/attaches/2019/06/800x600/07-7569565-191646.jpg
https://web.archive.org/web/20160305081228/https://www.globalsecurity.org/military/world/bangladesh/bns-durbar.htm
https://en.wikipedia.org/wiki/BNS_Durbar

**Comment by Jkryos** [comment]
Added DB3K 494.
