### ISSUE TITLE
Please add TC-2C extended range Sky Sword 2 air-to-air missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#872]
### DB Selector

DB3K

### Baseline

1768   TC-2 [Tien Chien II] (2000, Sky Sword II)

### Hypothetical

No

### Name

TC-2C Sky Sword II (Extended range)

### Length (m)

3.6

### Width/Span (m)

0.7

### Diameter (m)

0.19

### Weight (kg)

183

### Range (nm)

54

### Target Altitude / Depth (ft)

same as Weapon/1768

### Launch Altitude / Depth (ft)

same as Weapon/1768

### Warhead

same as Weapon/1768

### Targets

Aircraft, Missile

### CEP (m)

same as Weapon/1768

### Sensors

1x Active radar seeker (~5 nm range, 2010s technology)

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer, Level Cruise Flight

### Comments

The missiles with "TC2C" written on it were seen to be carried by a F-CK-1C/D. It have similar profile to the older TC-2 (Weapon/1768) with improved performance.
![image](https://user-images.githubusercontent.com/99646926/162001032-7e9db9cc-5899-42ec-8bb5-ccf214f90ae4.png)

### Sources

https://www.taipeitimes.com/News/front/archives/2017/12/25/2003684599
https://alert5.com/2019/04/25/rocaf-tactical-evaluation-of-tc-2c-air-to-air-missile/
https://asianmilitaryreview.com/2021/08/taiwan-readies-extended-range-sky-sword-2-missile-for-production/

**Comment by Jkryos** [comment]
Added DB3 494.
