### ISSUE TITLE
Target, properties and range correction for Wan Chien air-launched cruise missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#873]
### DB Selector

DB3K

### Affected DBID(s)

3026 Wan Chien

### Summary of Changes

-Change the missile`s max range from 100nm to 130nm
![image](https://user-images.githubusercontent.com/99646926/162004394-8b8a1804-8819-478b-bf45-b91a21c48e84.png)
![image](https://user-images.githubusercontent.com/99646926/162004581-c933ceba-d06e-4f21-b5c6-03db0fb14366.png)

-Add Land Structures(Hard & Soft) and Mobile Units (Hard & Soft) as the valid target. Wan Chien have the capability similar to JSOW and Storm Shadow and its cluster munitions can be used to destroy land targets other than runway too.
![image](https://user-images.githubusercontent.com/99646926/162005482-d29840f5-1cb8-4eb3-a73e-10d72747759b.png)
![image](https://user-images.githubusercontent.com/99646926/162005880-de49a87c-8343-43df-924c-4b72416d6829.png)

-Add Global positioning system (GPS) and inertial navigation system (INS) with terrain recognition (TERCOM) into the "Properties"
![image](https://user-images.githubusercontent.com/99646926/162006661-41507615-d593-4830-894a-3572e84ded07.png)

### Sources

https://missilethreat.csis.org/missile/wan-chien/
https://www.globalsecurity.org/military/world/taiwan/wan-jian.htm
https://en.wikipedia.org/wiki/Wan_Chien

**Comment by Jkryos** [comment]
Added DB3K 494.
