### ISSUE TITLE
Please add Hsiung Feng III`s land-attack capability.

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#874]
### DB Selector

DB3K

### Affected DBID(s)

1133 Hsiung Feng III

### Summary of Changes

-Add land-attack capability to the missile as it were reportedly to have land-attack capability, even though it were primarily built for anti-shipping role.
![image](https://user-images.githubusercontent.com/99646926/162011031-fc66db5d-262b-4e2e-912b-572dd2858f17.png)
![image](https://user-images.githubusercontent.com/99646926/162011189-43a5238b-4f4f-40a2-b450-1523521d98b2.png)
![image](https://user-images.githubusercontent.com/99646926/162010905-b423815f-9bba-4ac8-97a2-e0fd05636c76.png)

### Sources

https://missilethreat.csis.org/missile/hsiung-feng-iii/
https://www.naval-technology.com/news/newstaiwan-test-fires-hsiung-feng-iii-long-range-missile/
https://www.globalsecurity.org/military/world/taiwan/hf-3.htm

**Comment by Jkryos** [comment]
Updated DB3K 494.
