### ISSUE TITLE
Add Boat Docking facilities to Vietnamese Yurka Minehunters to support Pluto Plus ROV

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#878]
### DB Selector

DB3K

### Affected DBID(s)

1598

### Summary of Changes

Add docking facilities for a couple of pluto Plus ROV. Looks like cranes added 2020.

### Sources

https://twitter.com/seawaves_mag/status/1305562096105525248
https://defense-studies.blogspot.com/2017/01/vietnamese-navy-equipped-with-pluto.html?m=1

**Comment by Jkryos** [comment]
Updated DB3K 494.
