### ISSUE TITLE
Copy Pluto Plus ROV to Vietnam 2020

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#879]
### DB Selector

DB3K

### DBID to Copy

486

### Hypothetical

No

### Name

Pluto Plus ROV

### Country

Vietnam

### Service

Navy

### In Commission

2020

### Sources

https://twitter.com/seawaves_mag/status/1305562096105525248
https://defense-studies.blogspot.com/2017/01/vietnamese-navy-equipped-with-pluto.html?m=1
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2020/september/8987-vietnamese-largest-minesweepers-of-project-266-to-be-equipped-with-with-minehunting-rov.html

**Comment by Jkryos** [comment]
Added DB3K 494.
