### ISSUE TITLE
Can Stinger minimum altitudes be adjusted down to 30 ft to match other manpads

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#880]
### DB Selector

DB3K

### Affected DBID(s)

Most Stingers

### Summary of Changes

Adjust the minimum altitude to 30ft.

### Sources

Game play feedback. Its likely correct and a copy over from a past version.

**Comment by claudejdev** [comment]
For whatever it's worth :

Name | Minimum effective Altitude (m)
---|---
HN-5  | 50
Matra Mistral SATCP  | 15 
RBS 70  | ground-level
SA-16 'Gimlet'  | 10
SA-14 'Gremlin', Strela-3  | 10
SA-7b (Strela-2M/9K32M)  | 50 (can be down to 15 m but missile may be seduced by horizon and ground radiative heat effects)
Shorts Javelin  | 10
Shorts Blowpipe  | 10
FIM-92 Stinger  |  effectively ground level
FIM-43 Redeye  |  effectively ground level

_Cullen, T., Foss, C. F., & Jane's Information Group. (1992). Jane's land-based air defence, 1992-93. Coulsdon, Eng: Jane's Information Group_

**Comment by PygmalionOfCyprus** [comment]
Moved Claude's comment to its own issue; closing this one and using that as home plate for this issue.
