### ISSUE TITLE
Please change the active radar seeker on TC-2N 

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#883]
### DB Selector

DB3K

### Affected DBID(s)

3831 TC-2N [Tien Chien II]

### Summary of Changes

-Change the Active Radar Seeker on TC-2N from (~5nm, Late 1990 technology) to (~5nm, Early 2010s technology). The seeker on TC-2N is the improved one compared to older TC-2, as per the manufacturer itself.
![image](https://user-images.githubusercontent.com/99646926/162183332-6008a5f9-f4e6-4362-b8b8-aba8294365f7.png)

### Sources

https://www.ncsist.org.tw/ENG/csistdup/products/product.aspx?product_id=290&catalog=41
https://www.globalsecurity.org/military/world/taiwan/tc-2-shorad.htm

**Comment by Jkryos** [comment]
Fixed DB3K 494.
