### ISSUE TITLE
Properties and dimension correction for Hsiung Feng IIE Land Attack Cruise Missile.

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#884]
### DB Selector

DB3K

### Affected DBID(s)

3228 Hsiung Feng IIE

### Summary of Changes

-Add "Weapon - TERCOM Navigation" into the the weapon "Properties".
![image](https://user-images.githubusercontent.com/99646926/162185110-907b4c5a-2a92-4310-bfc4-55f52eac9bbe.png)

-Change the missile`s dimension into as below:
Length: 6m
Diameter: 0.5m
Weight: 980kg
![image](https://user-images.githubusercontent.com/99646926/162185747-f8ddcb76-192d-40f0-b134-c598e2f9c7a8.png)
![image](https://user-images.githubusercontent.com/99646926/162186134-b2d0db50-42d0-4f82-9fe9-756e10d51f03.png)

### Sources

https://missilethreat.csis.org/missile/hsiung-feng-iie/
https://www.globalsecurity.org/wmd/world/taiwan/hf-2e.htm

**Comment by Jkryos** [comment]
Updated DB3K 494.
