### ISSUE TITLE
DataMount - ParadropCapable, Dumbo Drop Update

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#885]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

> The US Air Force certified various equipment to be para-dropped. On the assumption that it demonstrate that it's possible, I thus assumed that other platforms with close dimension and weight could be airdropped too, even if not documented on the internet.
> I also reviewed known specially designed VDV airborne vehicles.
> Otherwise, I also compared with other similar platforms in the DB

### DataMount

- [x] **Is ParadropCapable**

ID | Name
---| ---
467 | 155mm/39 Tampella 155 K83 Towed Gun
547 | Avenger SAM
747 | LAV-AD SAM
822 | RB 17 Hellfire
837 | Avenger SAM
849 | Type 63 APC
850 | Saboteur
853 | Type 90 APC
858 | Spetsnaz Saboteur
1042 | VAB APC
1961 | 155mm/39 M114 Mod Towed Howitzer
2234 | LAV-25 [25mm/75 M242 Bushmaster]
2312 | 155mm/39 M198 Towed Howitzer
2313 | 155mm/39 M777 Towed Howitzer
2325 | 122mm/38 Type 86 Towed Howitzer
2329 | BTR-70 APC
2389 | 5.56mm MG
2429 | HJ-8E
2430 | 2S25 Sprut-SD Airborne Tank
2497 | Fahd 240 APC
2517 | AT-14 Spriggan [9N133 Kornet]
2551 | ASLAV-25 [25mm/75 Bushmaster]
2552 | ASLAV-PC [12.7mm/50 M2 MG]
2572 | 155mm/39 M777 Towed Howitzer
2573 | 155mm/39 M777 Towed Howitzer
2611 | Type 79 Jyu-Mat
2646 | LAV-III [25mm/75 M242 Bushmaster]
2647 | LAV-III/ICS [12.7mm/50 M2 MG]
2941 | LAV-300 Mk2 AGS [Cockerill 90mm Mk3]
2942 | LAV-300 IFV [12.7mm/50 M2 MG]
2969 | Skif [AT-2]
2715 | Poprad [PZR Grom]
2874 | BTR-60PB APC
2875 | BTR-152 APC
2975 | 155mm/39 Norinco AH-4 Howitzer
3175 | Kommando Spezialkräfte
3310 | 5.56mm MG
3345 | 5.56mm Assault Rifle
3346 | 72mm HEAT [Unguided]
3055 | BGM-71A TOW Section
3525 | Smash Dragon [5.56mm Assault Rifle]
3540 | RPK-74 [5.45mm MG]

```diff
+ Cargo_ParadropCapable = 1
```

- [ ] **Is _Not_ ParadropCapable**

> On the opposite, I believe that these platforms shouldn't be parachutable.

ID | Name
---| ---
2964 | ZTQ Light Tank | 
2982 | Vehicle (Train Engine, Unarmed) | 
2983 | Vehicle (Train Car, Unarmed) | 
3051 | Vehicle (Truck, C2/C3) | 
3472 | Vehicle (Fuel Bowser) | 

```diff
- Cargo_ParadropCapable = 0
```

### Sources

- [Airdrop of Supplies and Equipment Reference Data for Airdrop Platform Loads](https://www.marines.mil/Portals/1/MCRP%204-11.3L%20Airdrop%20of%20Supplies%20and%20Equipment%20Reference%20Data%20for%20Airdrop%20Platform%20Loads%201.pdf)  (pdf)
- [Airdrop of Supplies and Equipment: Rigging High-Mobility Multipurpose Wheeled Vehicles (HMMWV)](https://armypubs.army.mil/epubs/DR_pubs/DR_a/pdf/web/TM%204-48x17.pdf)  (pdf)
- [AIRDROP OF SUPPLIES AND EQUIPMENT: RIGGING LOADS FOR SPECIAL OPERATIONS](https://irp.fas.org/doddir/army/fm4-20-142.pdf) (pdf)
- [US Army performed airdrop certification of LAV-25A2 light armored vehicle | weapons defence industry military technology UK | analysis focus army defence military industry army](https://www.armyrecognition.com/weapons_defence_industry_military_technology_uk/us_army_performed_airdrop_certification_of_lav-25a2_light_armored_vehicle.html)
- [D-30-A, UAZ-469, HUMVEE Rigged for Airdrop Kazakhstan September 2003](https://www.flickr.com/photos/16498755@N07/5063908257)

DB3K v493

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
