### ISSUE TITLE
DataMount - MobileUnitCategory, the River update

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#886]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

> Based on examination of similar platforms in the DB, I believe that the MobileUnitCategory could be modified as suggested below.

### DataMount

- [ ] **Is Artillery Gun**

ID | Name
---| ---
3208 | 155mm/58 M1299 Howitzer (MG)

```diff
+ MobileUnitCategory = 3000 (Artillery Gun)
```

- [ ] **Is Artillery SSM**

ID | Name
---| ---
2518 | M1114GR [AT-14 Spriggan, 9M133 Kornet]
2535 | RT-2000 AMLRS
3077 | ZBD-08 [HJ-10 ATGM]
3186 | Raad-500 MRBM	
3325 | SSM Trailer [Improvised] (SS-N-2a Styx [P-15])
3326 | C2 Vehicle [Improvised] (KRA-3002)

```diff
+ MobileUnitCategory = 4000 (Artillery SSM)
```

- [ ] **Is MechInfantry**

ID | Name
---| ---
2373 | Vehicle (Truck, HMMWV)
2423 | Puma
2424 | VTML Lince
2510 | Vehicle (Truck, Gaz Tigr)
2551 | ASLAV-25 [25mm/75 Bushmaster]
2552 | ASLAV-PC [12.7mm/50 M2 MG]
2902 | Vehicle (Truck, Armed Technical)
2935 | AMX-10P
2938 | BRDM-2

```diff
+ MobileUnitCategory = 11000 (MechInfantry)
```

> Here _I think_ it may be best set to None, given they are ship armament mounts. You tell me.

- [ ] **Is None**

ID | Name
---| ---
901 | SA-N-10 Gimlet [9K310 Igla-1] Quad MANPADS
3018 | BM-5M.01 Katran-M

```diff
+ MobileUnitCategory = 0 (None)
```

### Sources

DB3K v493

**Comment by PygmalionOfCyprus** [comment]
MobileUnitCategory is actually deprecated AFAIK. I believe it may have once served a purpose pre-Ground Units but it's never been on the form for as long as I've been around and its associated enum table is MIA. So, wontfix/cantfix.
