### ISSUE TITLE
DataMount - Cargo_Type, the Fedex update

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#887]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

> Based on examination of similar platforms in the DB, I believe that the Cargo_Type could be modified as suggested below.

### DataMount

- [x] **Is Small Cargo (Car, AAA Guns, AMRAAM)**

ID | Name
---| ---
2902  | Vehicle (Truck, Armed Technical)

```diff
+ Cargo_Type = 2000
```

- [x] **Is Medium Cargo (APC, Towed Arty, Cruise Missiles)**

ID | Name
---| ---
179  | Vehicle (AN/MPQ-65)
906  | 122mm/38 D-30 2A18 Towed Howitzer
1057  | 155mm/45 G5 Howitzer
2326  | 155mm/39 FH-70 Towed Howitzer
2423  | Puma
2441  | AAV-P7/A1
2571  | 155mm/52 FH-77BW Archer Howitzer
2964  | ZTQ Light Tank
3052  | M-24 Chaffee Light Tank
3053  | NM-116 Light Recon	 
3272  | ROGUE-Fires
3356  | Vehicle (KALKAN-II)
3432  | NASAMS III HML [HMMWV]

```diff
+ Cargo_Type = 3000
```

- [x] **Is Large Cargo (Tank, TEL, Trailer)**

ID | Name
---| ---
1043 | 155mm/39 AUF Howitzer
1056 | 155mm/45 G6 Howitzer
1957 | 155mm/52 T-155 Firtina Howitzer
2291 | 152mm/48 2S19 MSTA-S
2302 | BM-27 Uragan MLRS
2311 | 152mm/29 Type 83 Howitzer
2328 | 122mm/38 Type 89/PLZ-89 Towed Howitzer
2383 | 155mm/52 Krab Howitzer
2417 | 155mm/45 PLZ-45
2418 | 155mm/52 PLZ-05
2425 | 155mm/41 Palmaria
2435 | BM-30 Smerch MLRS
2440 | 155mm/52 PzH 2000 Howitzer
2485 | 155mm/52 K-9 Thunder Self-Propelled Howitzer
2501 | SS-60 Astros 2 MLRS
2502 | Sejil-60 MLRS
2547 | 170mm M-1978 Koksan Howitzer
2548 | 170mm M-1989 Koksan Howitzer
2567 | Fajr-3 MLRS
2571 | 155mm/52 FH-77BW Archer Howitzer
2574 | 155mm/39 M109A6 Paladin Howitzer
2575 | 155mm/39 M109A6 Paladin Howitzer
2648 | 203mm/44 2A44 2S7 Pion Mobile Howitzer
2655 | 155mm/52 Caesar Mobile Howitzer
2773 | SS-26 Stone [9P78E, Iskander-E] TEL
2774 | SS-26 Stone [9P78, Iskander-M/K] TEL
2775 | SS-26 Stone [9P78, Iskander-M/K] TEL
2873 | Type 90 122mm MLRS
2882 | 122mm/38 PCL-09
2993 | 152mm/52 2S35 Koalitsiya-SV
3029 | PHL-03 MLRS
3060 | Lynx MLRS
3090 | M-87 MLRS TEL
3208 | 155mm/58 M1299 Howitzer (MG)

```diff
+ Cargo_Type = 4000
```

> Here _I think_ it may be best set to No Cargo, given they are ship armament mounts. You tell me.

- [x] **Is No Cargo**

ID | Name
---| ---
363  | SA-N-8 Gremlin [9K34 Strela-3] Twin MANPADS
420  | SA-N-5 Grail [9K32M Strela-2M] Quad MANPADS
901  | SA-N-10 Gimlet [9K310 Igla-1] Quad MANPADS
928  | SA-N-5 Grail [9K32M Strela-2M] Twin MANPADS
1398  | SA-N-8 Gremlin [9K34 Strela-3] Quad MANPADS
2868  | SA-N-10 Gimlet [9K310 Igla-1] Twin MANPADS
2923  | SA-N-24 Grinch [9K338 Igla-S / 3M-47 Gibka] Octuple
3018  | BM-5M.01 Katran-M 
3027  | HT-16PGJ [9M313] Sextuplet MANPADS

```diff
+ Cargo_Type = 0 (No Cargo)
```

### Sources

DB3K v493

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
