### ISSUE TITLE
DataMount - Name, the WYSIWYG update

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#888]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

> Based on examination of similar platforms in the DB, and some thorough Googling, I believe that the Name could be modified as suggested below.

### DataMount

- [x] **_Add_ Self-Propelled Howitzer**

ID | Name
---| ---
2289 | 122mm/36 2S1 M1974 Gvozdika
2290 | 152mm/34 2S3 M1973 Akatsiya
2291 | 152mm/48 2S19 MSTA-S
2417 | 155mm/45 PLZ-45
2418 | 155mm/52 PLZ-05
2425 | 155mm/41 Palmaria
2545 | 122mm/36 Raad 1
2643 | 122mm/38 PLZ-07
2872 | 122mm/38 PLL-09
2882 | 122mm/38 PCL-09

```diff
+ Name += Self-Propelled Howitzer
```

- [x] **_Modifiy to_ Self-Propelled Howitzer**

ID | Name
---| ---
1043 | 155mm/39 AUF Howitzer
1056 | 155mm/45 G6 Howitzer
1957 | 155mm/52 T-155 Firtina Howitzer
2311 | 152mm/29 Type 83 Howitzer
2314 | 152mm/48 2A37 2S5 Giatsint-S Mobile Howitzer
2328 | 122mm/38 Type 89/PLZ-89 Towed Howitzer
2328 | 122mm/38 Type 89/PLZ-89 Towed Howitzer
2383 | 155mm/52 Krab Howitzer
2440 | 155mm/52 PzH 2000 Howitzer
2547 | 170mm M-1978 Koksan Howitzer
2548 | 170mm M-1989 Koksan Howitzer
2571 | 155mm/52 FH-77BW Archer Howitzer
2648 | 203mm/44 2A44 2S7 Pion Mobile Howitzer
2655 | 155mm/52 Caesar Mobile Howitzer
3207 | 155mm/58 M1299 Howitzer (Shell)
3208 | 155mm/58 M1299 Howitzer (MG)
3395 | 155mm/39 M1299 ERCA Howitzer
3572 | 155mm/39 M1299 ERCA Howitzer

```diff
- Howitzer
- Mobile Howitzer
- Towed Howitzer
+ Self-Propelled Howitzer
```

- [x] **_Modifiy to_ Self-Propelled Howitzer**

ID | Name
---| ---
467 | 155mm/39 Tampella 155 K83 Towed Gun
900 | 152mm/25 D-20 M1955 Howitzer
1057 | 155mm/45 G5 Howitzer
2975 | 155mm/39 Norinco AH-4 Howitzer

```diff
- Howitzer
- Towed Gun
+ Towed Howitzer
```

### Sources

DB3K v493

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
