### ISSUE TITLE
Malaysia, Add Malawali class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#889]
### DB Selector

DB3K

### Hypothetical

No

### Name

Patrol Boat (PB), 2521, Malawali (ex- Bintang Utara)

### Class

Malawali  (ex-Bintang Utara)

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2006 - present (MMEA), 1999 -2006 (Marine Department)

### Length (m)

25

### Beam (m)

6

### Draft (m)

1.1

### Standard Displacement (t)

Not found

### Full Displacement (t)

65

### Complement

14

### Primary Propulsion Type

Diesel

### Propulsion

2x Deutz 16M816CR, 2 shafts

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

Not found

### Sensors

1x Generic I-band navigation radar

### Mounts

Small Arms

### Aircraft & Docking Facilities

1x small RHIB aft with crane (image)

### Comments

4 units in class

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/malaysia/mal_cg_bintang_utara.htm
![1](https://user-images.githubusercontent.com/99532490/162441258-326210de-3d08-49c1-89f7-e8c88e9037d3.jpg)
![2](https://user-images.githubusercontent.com/99532490/162441262-050dbf82-444f-421c-ad65-99d82bae302c.jpeg)
![3](https://user-images.githubusercontent.com/99532490/162441263-2fcc450b-cdc5-4df4-acc6-9d2aa4f733d4.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
