### ISSUE TITLE
Increase Arrow-3 Engagement Range (Max Reported Range is 2,400km)

### ISSUE THREAD

**Issue by HyperGopher** [PygmalionOfCyprus/cmo-db-requests#89]
### DB Selector

CWDB

### Affected DBID(s)

2624

### Summary of Changes

1. Arrow 3 has a max reported range of 2400km (~1300 nm). But in the game it only reaches an engagement range of 200nm (370km). Would like to see this tweaked to at least 1000-1500km (~800nm) since the max range of 2400km is probably it's burnout range at which it doesn't have enough speed for an interception.

I could be wrong, but 200nm seems too short for a ABM with a reported max range of 1300nm.

### Sources

https://missilethreat.csis.org/defsys/arrow-3/

https://www.armyrecognition.com/israel_israeli_military_missile_vehicles_systems_u/arrow_3_long-range_anti-ballistic_missile_technical_data_sheet_specifications_pictures_video_12901173.html

**Comment by PygmalionOfCyprus** [comment]
Max range is now 1295nm. I'll let the energy model decide whether it's too slow to intercept at that range or not. Also changed the seeker to an EO seeker (as it should be) vs. the IIR seeker copied over from the Arrow 2 it had before.

**Comment by HyperGopher** [comment]
Awesome! Thank you for working on this!
