### ISSUE TITLE
Please add FV107 Scimitar Reconnaissance Vehicle

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#891]
### DB Selector

DB3K

### Hypothetical

No

### Name

Mech Inf Sec (FV107 Scimitar x2) 

### Facility Type

Mech

### Country

United Kingdom

### Service

Army

### Dispersion Radius (m)

80

### Sensors

Per vehicle:
-same as Mount/2541 FV510 Warrior IFV

### Mounts

2x FV107 Scimitar (each vehicle have exact weapon as Mount/2541 FV510 Warrior IFV except Scimitar can only carry 165x 30mm rounds while Warrior carry up to 220x 30mm rounds).

![image](https://user-images.githubusercontent.com/99646926/162627875-0ced489f-76dd-4b11-b355-4ede2fba87dd.png)

### Comments

The vehicle`s protection is adequate against 12.7 mm frontally.
![image](https://user-images.githubusercontent.com/99646926/162628320-aa172b6c-e7d7-40d3-b6db-e789eeb39e9e.png)

Below pics is for the reference:
![image](https://user-images.githubusercontent.com/99646926/162628055-c9ed5212-7523-41c1-bdec-02239fc01223.png)
![image](https://user-images.githubusercontent.com/99646926/162628369-fbbf5944-c854-491a-922d-0ce308a36d6a.png)

### Sources

https://www.tanks-encyclopedia.com/coldwar/UK/FV107-Scimitar.php
https://www.militaryfactory.com/armor/detail.php?armor_id=188
http://www.army-guide.com/eng/product1153.html

**Comment by Jkryos** [comment]
Added DB3K 494.
