### ISSUE TITLE
Please add FV103 Spartan APC

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#892]
### DB Selector

DB3K

### Hypothetical

No

### Name

Mech Inf Plt (FV103 Spartan x4)

### Facility Type

Mech

### Country

United Kingdom

### Service

Army

### Dispersion Radius (m)

80

### Sensors

Per vehicle:
1x Generic optical sight
1x Generic IR camera(2nd gen)

### Mounts

4x FV103 Spartan (each vehicle have a 7.62mm Machinegun with 3000 rounds that can be fired from within the hull and the aiming can be done with the commander`s sight.)
![image](https://user-images.githubusercontent.com/99646926/162628733-211cf99e-e02c-4757-8ae9-51dfd8b7c849.png)
![image](https://user-images.githubusercontent.com/99646926/162628768-505ab9d6-e511-4965-bbad-a6c384f3d997.png)

### Comments

-the 2001`s upgrade saw the vehicle being fitted with Thermal sight. Since we don't have actual thermal sight in the game , probably can be replaced with Generic IR camera(2nd gen) instead.
![image](https://user-images.githubusercontent.com/99646926/162629006-0ab2fd88-4a83-4b9e-b446-fd0d64f1ef32.png)
![image](https://user-images.githubusercontent.com/99646926/162629022-f7358c6e-6073-4085-9ce2-1a97e798af58.png)

-It have similar level of protection as proposal entry #891 

Below pics is for the reference:
![image](https://user-images.githubusercontent.com/99646926/162629318-7e3e2309-5f1d-48e9-a0a7-400f8f1bf8cd.png)
![image](https://user-images.githubusercontent.com/99646926/162629288-0cf1a886-4f6a-47cb-a635-8d775959e331.png)

### Sources

https://www.pmulcahy.com/tracked_apcs/british_tracked_apcs.htm
https://www.militaryfactory.com/armor/detail.php?armor_id=159
http://www.military-today.com/apc/fv103_spartan.htm
https://leicestermodellers.weebly.com/fv103-spartan-apc.html

**Comment by Jkryos** [comment]
Added DB3K.
