### ISSUE TITLE
#2411 - MRK Buyan Mod has two Komar 3M47 Quad SA-N-24 launchers not one, covering 360 arc*. 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#896]
### DB Selector

DB3K

### Affected DBID(s)

#2411 - MRK Buyan Mod

### Summary of Changes

#2411 - MRK Buyan Mod [Pr.21631 Buyan-M] (Russia [1992-] - 2014)
![buyan mod err](https://user-images.githubusercontent.com/99494755/163045496-c6f1a71f-abe2-4b56-a8c1-fa1140adc550.JPG)

Currently has one #2239 mount aft octuple 3M47 Komar for SA-N-24 launcher.
In reality the class has one quad forward (B position) and one quad aft (X position) 3M47 launcher giving 360' coverage with limitations on the aft arcs elevation due to a deck obstruction and the 30mm Duet installation.
![buyan mod missiles](https://user-images.githubusercontent.com/99494755/163046750-c04262ff-0169-43df-87cf-351da88082fe.jpg)

*There is no Russian Komar Quad mount in the DB only an export version.  
![komar quad](https://user-images.githubusercontent.com/99494755/163045843-31d0a9a2-4dfb-4b6b-ac67-abb2f0181edb.JPG)

![buyan gibka quad fwd](https://user-images.githubusercontent.com/99494755/163045698-c95f0aef-528c-4cc6-9f11-04bb5523beec.JPG)

### Sources

http://russianships.info/pics/21631.gif
https://www.youtube.com/watch?v=Wvgs0DX7Z_w
https://youtu.be/Wvgs0DX7Z_w?t=76
https://youtu.be/Wvgs0DX7Z_w?t=130
https://www.youtube.com/watch?v=c6e-QmLZkjs
https://www.youtube.com/watch?v=Wvgs0DX7Z_w
https://youtu.be/Wvgs0DX7Z_w?t=145 Foward quad GIBKA/KOMAR in shot. 
http://roe.ru/eng/catalog/naval-systems/shipborne-weapons/3m-47/ kOMAR TYPE QUAD LAUNCHER

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494 (along w/ adding Russian quad Komar).
