### ISSUE TITLE
Poland "Miecznik" Arrowhead-140PL x3

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#898]
### DB Selector

DB3K

### DBID to Copy

3271 DB3k

### Hypothetical

No

### Name

XX Miecznik Class (Placeholder)

### Country

Poland

### Service

Navy

### In Commission

2028-

### Sensors

- SM-400 AESA
- NS 50
- CAPTAS-2 VDS
- Thales BlueHunter? 

### Mounts

- 4x quad RBS-15 Mk3 or 4
- Mk41 32 cell VLS with Sea Ceptor CAMM/CAMM ER
- 76mm main gun
- 2x 35mm AM-35 gun (1x fore, 1x aft) (OSU-35k from Kormoran MCM)
- 324mm MU-90 Torpedoes
- Davits for 2x11m and 2x7.5m RHIBS
- 

### Other Changes

- 138.7m long, 19.7m wide, 5.5m draught
- 7,000 tonnes
- 30kts
- 6000km @ 18kn
- 100-120 crew, accommodate up to 160
- CODAD (COmbined Diesel And Diesel) propulsion system consisting of 4 diesel engines
- Hangar for helo (non-folded tail atm, too small for AW.101?)

### Sources

https://www.navalnews.com/naval-news/2022/04/first-look-at-polands-new-miecznik-frigate/
https://bulgarianmilitary.com/2022/04/11/polish-arrowhead-140pl-frigates-get-rbs-15-ashms-sea-ceptor-76mm-gun/
https://defencereview.gr/i-pgz-group-edose-sti-dimosiotita-leptomereie/
https://milmag.pl/en/miecznik-the-current-state-of-the-most-important-modernisation-programme-of-the-polish-navy/

![arrowhead140pl-770x410](https://user-images.githubusercontent.com/99632305/163098189-3599f010-6f7c-4b8f-8b1d-17f37c88b9ac.jpg)

**Comment by cdnice55** [comment]
https://www.navalnews.com/naval-news/2022/12/latest-news-on-polands-miecznik-frigate-program/
The position of the RBS15 Mk3 missile launcher has been changed and the helipad has been lengthened.

The arrangement of the anti-ship missile containers is also different. There are a total of 16 of them. Eight (2×4) are left unchanged – they fire outward perpendicular to both sides. While another eight (4×2) are deployed on the superstructure deck and angled toward the bow – similar to those on typical Fast Attack Crafts (FACs).

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
