### ISSUE TITLE
Malaysia, Add Ramunia class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#899]
### DB Selector

DB3K

### Baseline

Patrol Craft (PC), 3221, Ramunia

### Hypothetical

No

### Name

Patrol Craft (PC), 3221, Ramunia

### Class

Ramunia  (ex-Bahtera Juang, K33) (different unit as class name giver)(Vosper 32m Design)

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2005 - present (MMEA), 1982 -2005 (Customs Service)

### Length (m)

32.4

### Beam (m)

7.2

### Draft (m)

1.8

### Standard Displacement (t)

100

### Full Displacement (t)

143

### Complement

24 + 5

### Primary Propulsion Type

Diesel

### Propulsion

2x Paxman-Valenta 16RP200, 2 shafts

### Flank Speed (kt)

27

### Range (nm) at Speed (kt)

2000 @ 8

### Sensors

1x Kelvin Hughes I-band Navigation radar

### Mounts

1x single 40mm/60 Mk 3
2x single 7.6mm/90

### Aircraft & Docking Facilities

1x small RHIB (image)

### Comments

7 units in class. 

### Sources

1: JFS 2015-2016
2: https://www.navypedia.org/ships/malaysia/mal_cg_bahtera_juang.htm
3: Image MMEA
![5](https://user-images.githubusercontent.com/99532490/163133493-794b1e81-520b-4c83-99e4-582d556714cd.jpg)
![3](https://user-images.githubusercontent.com/99532490/163133520-a583d2d5-d79f-4ccb-9bb0-33d6d3211e15.jpg)
![4](https://user-images.githubusercontent.com/99532490/163133526-82e28fdd-f8fa-47f3-81c5-a91d87faa559.jpg)
![6](https://user-images.githubusercontent.com/99532490/163133527-b2ab37ff-b178-455c-a336-40a8521b8548.jpg)
![7](https://user-images.githubusercontent.com/99532490/163133529-248ea7de-870a-44fd-8d06-38ee62c99704.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
