### ISSUE TITLE
Add retirement date of 2021 to Norwegian F-16AM/BM aircraft #2602 #3278

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#9]
### DB Selector

DB3K

### Affected DBID(s)

2602, 3278

### Summary of Changes

All aircraft required by end of 2021. May sell to Romania and Draken.

### Sources

https://www.scramble.nl/military-news/rnoaf-f-16am-delivered-to-aviation-museum
https://www.overtdefense.com/2021/12/03/norway-sells-12-f-16s-to-draken-as-retirement-looms/
https://www.defensenews.com/air/2017/01/27/as-f-35-comes-online-norway-to-scrap-f-16-fleet/

**Comment by Jkryos** [comment]
Fixed DB3K 493.
