### ISSUE TITLE
B-1B (4909) O-EMP JASSM  Loadout Issue

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#900]
### DB Selector

DB3K

### Affected DBID(s)

4909

### Summary of Changes

The External Pylons (4909) B-1B's O-EMP JASSM Loadout (27468) has D-EMP JASSMs on the external racks instead of O-EMP AGM-158B-ERs. Please change these to O-EMP weapons.

![20220413 - JASSM Issue](https://user-images.githubusercontent.com/99649251/163184936-85733184-4af1-4eca-b075-ca3d71bc77ef.jpg)

### Sources

CMO DB 493.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
