### ISSUE TITLE
#3295 - #3294  [Pr.22800 Karakurt] both variants (Russia [1992-] - 2019) Main armaments incorrect on first version plus name convention MRK added missing OECM DECM and ESM - Wine Flask Half Hat?

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#901]
### DB Selector

DB3K

### Affected DBID(s)

#3295 #3294 - Both versions Pr.22800 Karakurt] (Russia [1992-] - 2018)

### Summary of Changes
For both:
Change names to reflect convention MRK - Small missile ship
#3295 - MRK Shkval [Pr.22800 Karakurt] (Russia [1992-] - 2019)
#3294 - MRK Uragan [Pr.22800 Karakurt] (Russia [1992-] - 2018)
Currently have no OECM DECM or ESM apart from Mineral passive capability. 
Both should have 2 x #1098 Wine Flask {MP-405] and #2427 Half Hat {MP-405] ELINT / OECM DECM ? or upgraded variant there of. Systems are visible on either side of the mast. 
At the moment in the DB they have fewer EW systems than the earlier Buyans which have the full TK-25 suite. 

#3294 - MRK Uragan [Pr.22800 Karakurt] (Russia [1992-] - 2018) Single unit:
Main gun is the same as the rest of the class:
1x 76mm AK-176MA not the 100mm A-190 in A position which it has in the DB currently. 
Also it has normal Russian CIWS not Duet system.
It has 2x AK-630M 30mm/65 Gatling not the AK-630M2 Duet. Starboard and port X position aft.
![Karakurt Mod 1 Mystichi](https://user-images.githubusercontent.com/99494755/163253216-6e6f2cfc-cecc-4d3b-8f3d-f1a92f693613.JPG)

### Sources
https://en.wikipedia.org/wiki/AK-630
http://bastion-karpenko.ru/mp-405-reb/
https://pbs.twimg.com/media/EeaHvAWWkAA05ng?format=jpg&name=small
http://russianships.info/eng/warships/project_22800.htm
![karakurt mp405](https://user-images.githubusercontent.com/99494755/163213398-dadf0e9f-28d2-4cce-896b-287aedad182b.JPG)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Did a general review and rework. There was an article mentioning an A-190 on the first-in-class but that appears to have been either a mistake or a temporary/test fit since the picture you attached clearly shows otherwise.
