### ISSUE TITLE
Malaysia, Add Pekan class (ex-JPN CG Erimo/Ojika)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#902]
### DB Selector

DB3K

### Hypothetical

No

### Name

Large Patrol vessel (PL), 9203, Pekan

### Class

Pekan (ex-Erimo/Ojika PL02 Japan)

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2017 - present (MMEA), 1991 -2017 (Japan coastguard)

### Length (m)

91.4

### Beam (m)

11

### Draft (m)

3.5 (src1)

### Standard Displacement (t)

1883 (src3)

### Full Displacement (t)

2006 (src3)

### Complement

38 + 32 (src image)

### Primary Propulsion Type

Diesel

### Propulsion

2x Fuji 8S40B, 2 shafts CP props

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

4400 @ 15 (src1), 8000 @ 14 (scr3)

### Sensors

1x JMA 1596 I-band navigation
1x JMA E/F-band Navigation radar
* Might be replaced by Furuno radar, see images

### Mounts

1x 20mm JM-61B Sea Vulcan Gatling

### Aircraft & Docking Facilities

Helicopter platform for 1x Bell212 or super Puma. 
Stern docks an "unsinkable" rescue craft.
2x boats in crane

### Ship Codes

Dual or Triple Stabilizers

### Comments

1 unit in class, malaysia, still 6 units in Japan Coastguard. 
Cargo Hold under the helicopter pad. 
Fin stabilization.

### Sources

1: JFS 2015-2016 (JPN)
2: https://www.malaysiandefence.com/new-ship-mmea/
3: https://www.navypedia.org/ships/japan/jap_cg_ojika.htm
4: https://en.wikipedia.org/wiki/Ojika-class_patrol_vessel
5: Image
![2](https://user-images.githubusercontent.com/99532490/163216140-94597f90-a839-45b4-b8c8-c2819c8991a9.jpg)
![3](https://user-images.githubusercontent.com/99532490/163216145-5ab5308c-4cbc-4dcc-97b1-abc546ff5852.jpg)
![4](https://user-images.githubusercontent.com/99532490/163216150-f2704aff-5e50-41b6-83c6-9cad6668869c.jpg)
![5](https://user-images.githubusercontent.com/99532490/163216154-2aedd3b4-ccf9-45b6-bdca-f58c27ecb269.jpg)
![9](https://user-images.githubusercontent.com/99532490/163216156-c2783dc7-01b2-4e01-8623-9d081e14424b.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
