### ISSUE TITLE
A fire control radar does not stop emitting

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#903]
### DB Selector

DB3K

### Affected DBID(s)

Fire Control radars

### Summary of Changes

his is a follow-up of the topic located at:[url] https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=382655[/url] with attached [i]Tests AGM-45.zip[/i] file.

The situation is that I try to shut down a fire control radar because a anti-radiation missile (AGM-45) is coming my way. This to reduce the chance that the ARM will hit my radar.
Source: [url]https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196035/agm-45-shrike-anti-radar-missile/[/url]
With the help of others it was found that only the attached search radars will stop emitting (see discussion on the above mentioned link) and the fire ontrol radar remains emitting, even when all buttons tell it to shut down. Beware the sensor window will not be updated, you have to open a new one..

It is possible to shut the FC radar down via: go to passive emcon, then set weapons 'hold', then drop all of the contacts. But this is a lot of micro management, while there is a single button emcon passive present.

The goal is to make the gameplay more interesting in case of an ARM attack, and to properly use the button EMCON passive.

Is it possible to adjust the EMCON and program a reduced hit propability of ARMs in case of radar shutdown?

### Sources

https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196035/agm-45-shrike-anti-radar-missile/

https://www.globalsecurity.org/military/world/china/missile-arm.htm

**Comment by PygmalionOfCyprus** [comment]
Not a DB issue so will leave for the sim-code guys to handle via tech support thread.
