### ISSUE TITLE
Ship #3141 Update Name to DDG 15 USS Berkeley

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#904]
### DB Selector

DB3K

### Affected DBID(s)

3141

### Summary of Changes

 DDG 14 Buchanan was the last Mk.11 (Twin) rail launcher Ship. DDG 15 Berkeley was the first Mk.13 single rail ship. If you can add [CF Adams] to the title would be great too (easier to search when my brain is tired).

### Sources

https://www.seaforces.org/usnships/ddg/Charles-F-Adams-class.htm

Notice in this dated pictures. Buchanans in the late 80-90 Twin Launcher

https://www.maritimequest.com/warship_directory/us_navy_pages/destroyers/pages/uss_buchanan_ddg14_page_1.htm

USS Berkeley

https://ussberkeley.com/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Name is now "DDG 15 Berkeley [Charles F. Adams]".
