### ISSUE TITLE
DataFacility_length, aka the 'When size matters' update

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#905]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

> Based on examination of similar entries in the DB, I believe that the values could be modified as suggested below.

### DataFacility

- [ ] _Modify_

ID | Name | Area | Length
--- | --- | --- | ---
1592 | Single-Unit Airfield (1x 3201-4000m Runway) | 4480000 | 5600

_Area_
```diff
- 4480000
+ 3200000
```

_Length_
```diff
- 5600
+ 4000
```

ID | Name | Area | Length
--- | --- | --- | ---
1996 | Single-Unit Airfield (2x 4000m+ Runways) | 3200000 | 4000
2413 | Single-Unit Airfield (3x 4000m+ Runways) | 3200000 | 4000
2416 | Single-Unit Airfield (4x 4000m+ Runways) | 3200000 | 4000

( Based on 1995 Single-Unit Airfield (1x 4000m+ Runway) )

_Area_
```diff
- 3200000
+ 4480000
```

_Length_
```diff
- 4000
+ 5600
```

ID | Name | Area | Length
--- | --- | --- | ---
1712 | Single-Unit Airfield (1x 2001-2600m Runway) | 1600000 | 2000

_Area_
```diff
- 1600000
+ 2080000
```

_Length_
```diff
- 2000
+ 2600
```

ID | Name | Area | Length
--- | --- | --- | ---
1877 | Single-Unit Airfield (1x 2600-3200m, Runway) | 1600000 | 2000

_Area_
```diff
- 1600000
+ 2560000
```

_Length_
```diff
- 2000
+ 3200
```

### Sources

DB3K_493

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
