### ISSUE TITLE
#2815 and #2305 - SKR Admiral Grigorovich [Pr.1135.6M] (Russia [1992-] - 2018)  Has AK-630M not AK-630M2 Duet system

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#906]
### DB Selector

DB3K

### Affected DBID(s)

#2815 and #2305 - SKR Admiral Grigorovich [Pr.1135.6M] (Russia [1992-] 

### Summary of Changes

#2815 and #2305 - SKR Admiral Grigorovich [Pr.1135.6M] (Russia [1992-] 
Has 2 x #1108 - AK-630M 30mm/65 Gatling Burst [400 rnds] One each side of hangar rear admidships.
Does not have #3038 - AK-630M 30mm/65 Twin Gatling Burst [800 rnds]
![Grigorvich ciws](https://user-images.githubusercontent.com/99494755/163255616-a1d10000-76a5-4f96-85ed-8b26d04a7dda.JPG)

### Sources

http://roe.ru/eng/catalog/naval-systems/surface-ships-ships-and-boats/project-11356/
Good overhead perspective with full layout. 
http://russianships.info/eng/warships/project_11356.htm
https://en.wikipedia.org/wiki/AK-630
https://www.youtube.com/watch?v=fyYMOWq5dII&t=4s
https://www.youtube.com/watch?v=f08c-xdQeP4&t=4s
https://youtu.be/f08c-xdQeP4
https://youtu.be/f08c-xdQeP4?t=70

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
