### ISSUE TITLE
Malaysia, Add Gagah class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#908]
### DB Selector

DB3K

### Baseline

279 (Egypt)

### Hypothetical

No

### Name

Patrol boat (PBF), 3901, Gagah (ex-Lang Malam, PZ2)

### Class

Gagah (ex- Lang Hitam class)

### Country

Malaysia

### Service

MMEA (CG)

### In Commission

2006 - present (MMEA), 1980 - 2006 (Maritime Police)

### Length (m)

39.5

### Beam (m)

7

### Draft (m)

1.8

### Standard Displacement (t)

188

### Full Displacement (t)

234(src1)

### Complement

27 + 9

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 20V538TB92, 2 shafts

### Flank Speed (kt)

23 (src1&3), 34 (src2)

### Range (nm) at Speed (kt)

1200 @ 15 (src1), 100 @ 16 (src2)

### Sensors

1x Kelvin Hughes I-band navigation radar

### Mounts

1x single bofors40mm/70
1x single oerlikon 20mm
2x single 7.62mm

### Aircraft & Docking Facilities

Small RHIB midships

### Comments

15 units in class. Lost 1x single 20mm/70 in mid 2010's. Lurssen FPB38 design

### Sources

1: FS 2015-2016
2: https://www.navypedia.org/ships/malaysia/mal_cg_lang_hitam.htm
3: images 1
![1](https://user-images.githubusercontent.com/99532490/163450352-7378cbfa-3050-4f3f-9c35-001501fcde1a.jpg)
![2](https://user-images.githubusercontent.com/99532490/163450354-7b843312-60f6-43b6-808c-4bb75cd8856c.jpg)
![3](https://user-images.githubusercontent.com/99532490/163450355-928326fc-ea27-4ebe-996a-6e6cf22530a8.jpg)
![4](https://user-images.githubusercontent.com/99532490/163450356-99961f07-05f9-474e-ab46-63d8a069ff8c.jpg)

**Comment by Jkryos** [comment]
Added DB3K 496.
