### ISSUE TITLE
RKR Moskva [Pr.1164 Atlant, Ex-Slava] - Out of action 2022

### ISSUE THREAD

**Issue by Echoblammo** [PygmalionOfCyprus/cmo-db-requests#911]
### DB Selector

DB3K

### Affected DBID(s)

3190

### Summary of Changes

2019-2022. 

The ship has been promoted to a submarine.

### Sources

https://t.me/tass_agency/127473
https://euroweeklynews.com/2022/04/14/russian-cruiser-moskva-sank-ukraine/
https://www.wsj.com/livecoverage/russia-ukraine-latest-news-2022-04-14/card/russia-s-black-sea-fleet-flagship-moskva-sinks-OCci2H1wPsTSHwZ5P4pS
https://www.msn.com/en-au/news/australia/russian-warship-moskva-has-sunk-off-ukraine-here-s-what-we-know/ar-AAWd0M2
https://www.newsweek.com/moskva-cruiser-sinks-black-sea-russia-denies-missile-strike-1698139

I'm sure more to come.

**Comment by PygmalionOfCyprus** [comment]
Extremely satisfying to plug into 494.
