### ISSUE TITLE
Bulgaria Mesar Class AORL x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#912]
### DB Selector

DB3K

### Hypothetical

No

### Name

302 Atiya

### Class

Mesar Class

### Country

Bulgaria

### Service

Navy

### In Commission

1979-

### Length (m)

97.5

### Beam (m)

13.2

### Draft (m)

5.2

### Standard Displacement (t)

3240

### Complement

32

### Primary Propulsion Type

Diesel

### Propulsion

2x Diesels

### Flank Speed (kt)

20

### Range (nm) at Speed (kt)

Not noted

### Sensors

- 2x Don-2 Navigation

### Mounts

- 2x twin 30-mm 65 cal. AK 230 AA

### Comments

- Cargo Capacity: 1,593 tons liquid
- Over the stern fueling
- Also has dry stores cargo

### Sources

https://www.militaryperiscope.com/weapons/ships/auxiliary/mesar-aorl-class-aorl

![atiya-atia-2008](https://user-images.githubusercontent.com/99632305/163475900-1c2c8b67-9c0c-4c0c-9cc7-fa03fc0c44cf.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
