### ISSUE TITLE
Generic Fassmer FPB 21 

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#913]
### DB Selector

DB3K

### Hypothetical

No

### Name

FPB 21

### Class

21m Fast Patrol Boat

### Country

Generic

### Length (m)

21.0

### Beam (m)

5.8

### Draft (m)

1.3

### Standard Displacement (t)

45

### Complement

13

### Primary Propulsion Type

Diesel

### Propulsion

2x Deutz MWM TBD 616

### Fuel Capacity (kg)

5.6 m3

### Flank Speed (kt)

34

### Range (nm) at Speed (kt)

500/20

### Sensors

- 1x Navigation radar

### Mounts

- Small arms
- 1x davit for small RHIB

### Sources

https://www.fassmer.de/fileadmin/user_upload/10_Technical_Data_PDFs/fassmer-21m-fast-patrol-boat-technical-data.pdf

![download](https://user-images.githubusercontent.com/99632305/163479205-6500ce86-99a7-46fe-bc18-43dc5356a357.jpg)
![download](https://user-images.githubusercontent.com/99632305/163479222-92f6ab9f-dcb0-44e3-a3ca-317660dfeddf.jpg)

**Comment by PygmalionOfCyprus** [comment]
Do you one better. Added the Cambodian M 1105 Kaoh Chhlam and Bulgarian Varnas.

**Comment by cdnice55** [comment]
I was going to do them individually actually but figured the boat is probably widely used so a generic one might be of more use. Also didn't want to overload you guys too much!

**Comment by PygmalionOfCyprus** [comment]
![thats-my-secret-im-always-overloaded](https://user-images.githubusercontent.com/87087226/163739394-2ea928b7-c880-4341-b4b1-8a98972a2176.jpg)

It actually doesn't appear that there are customers beyond those two, but hey, if they pop up now that there's a version in the DB it will be very easy for us to add more.
