### ISSUE TITLE
Add Long Range 4 BL-755 Bomb 2 Droptank loadouts to Indian SEPECAT IM/IS Jaguars

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#914]
### DB Selector

DB3K

### User(s)

All Indian Jaguar IS and IM

### Weapons Carried

4 BL-755
2 1200 Liter Droptanks

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Sources

https://twitter.com/indiandefence11/status/1008911244399554560
https://timesofindia.indiatimes.com/photo.cms?msid=1301017

**Comment by PygmalionOfCyprus** [comment]
Added 494.
