### ISSUE TITLE
Indonesia, Add Pulau Rengat class

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#916]
### DB Selector

DB3K

### Baseline

1263,2138(NLD),1265,2132(BEL),2133(PAK),…

### Hypothetical

No

### Name

Mine Counter Ship (MHSC), 711, Pulau Rengat

### Class

Pulau Rengat (Tripartite)

### Country

Indonesia

### Service

Navy

### In Commission

1988 - present

### Length (m)

51.5

### Beam (m)

8.9

### Draft (m)

2.5 (3.5 max)

### Standard Displacement (t)

510

### Full Displacement (t)

588

### Complement

46+4

### Primary Propulsion Type

Diesel

### Propulsion

2x MTU 12V396TC82, 1 shaft LIPS CP prop (+ 2 75-hp bow-thrusters + 2 120 hp Schottel active rudders)

### Flank Speed (kt)

15

### Range (nm) at Speed (kt)

3000 @ 12, 3500 @ 10

### Sensors

Racal Decca 1229 I-band navigation radar
Thomson Sintra TSM2022
MCM: 
OD3 Oropesa mech gear sweep
Fiskars F-82 magnetic
SA Marine AS-203 acoustic seweep
Ibis V minehunting system2x PAP 104 Mk4 mine disposal

### Mounts

2x Rheinmetall 20mm/85 S.20
Matra Simbad SAM or third 20mm/85 S.20
MCM: 
2x PAP 104 USV Mk4 mine disposal

### Aircraft & Docking Facilities

1x crane aft

### Ship Codes

Glass Reinforced Polyester (GRP) Construction

### Comments

2 units in class. 
A 5 ton container can be shipped (research,extended dinving, Drone control).

### Sources

1: JFS 2016-2016
2: MilPer 2008
3: https://www.navypedia.org/ships/indonesia/ino_ms_pulau_rengat.htm
![2](https://user-images.githubusercontent.com/99532490/163668827-321e82cf-419b-4d19-a97a-3646e9c38350.jpg)
![3](https://user-images.githubusercontent.com/99532490/163668830-e6fbad1c-75f0-422f-b8f1-47298eb69178.jpg)
![4](https://user-images.githubusercontent.com/99532490/163668831-367c2aad-d748-4741-b446-26a118f30c6a.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. I also went through and changed all the Tripartides to have GRP construction.

**Comment by Parel803** [comment]
Thx
