### ISSUE TITLE
Add new Saudi Corvette 828 Al Jubail [Avant 2200 Combatant] 2023 x5

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#917]
### DB Selector

DB3K

### DBID to Copy

Ship 2542

### Hypothetical

No

### Name

828 Al Jubail

### Country

Saudi Arabia

### Service

Navy

### In Commission

2023

### Sensors

Fire control is Dorna
Radar is TRS-4D
MK 11 and S Band Sharpeye Nav Radars

### Mounts

Forward Deck gun same (SUPER RAPID 76mm main gun)
8 Cell MK.41 VLS (32 ESSM)
Aft Millenium CIWS Same
2 Triple 324mm Torpedo Launchers: Mk.54 Torpedoes

### Other Changes

104 meters long
14 meters draft
Diesel Engines are MTU-1163. Can cruise to 4500nm and top speed is 27knts. Looks close to copied entry.
Crew 102

### Sources

https://www.navalnews.com/naval-news/2022/03/navantia-delivers-the-first-avante-2200-class-corvette-to-the-rsnf/
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/january/11335-the-corvette-al-jubail-to-join-royal-saudi-navy-in-two-months.html
https://www.navalnews.com/naval-news/2020/08/navantia-lays-keel-of-3rd-avante-2200-corvette-for-royal-saudi-navy/
https://twitter.com/d__mitch/status/1463787146280640518
https://navalpost.com/navantia-delivers-the-1st-avante-2200/ (look at picture. Definitely TRS-4D and likely Sharpeye Nav Radars)

Sipri Arms DB Lines
MTU-1163	Diesel engine	2018			For 5 Avante-2000 frigate from Spain; from Spanish production line
5	GDM-008 35mm	CIWS	2018			For 5 Avante-2200 frigates from Spain
5	Mk-41 VLS	naval SAM system	(2018)			For 5 Avante-2200 frigates from Spain
5	Super Rapid 76mm	naval gun	(2018)			For 5 Avante-2200 frigates from Spain
(5)	TRS-4D	multi-function radar	(2017)			For 4 MMSC frigates from USA (doubtful its for the MMSC)

**Comment by bostonmyk** [comment]
Too little info on VLS, SSM and sonar fits. Things will be clearer by the end of this year.

**Comment by bostonmyk** [comment]
Decoys are Sylena https://www.navalnews.com/event-news/dimdex-2022/2022/04/lacroix-decoy-launchers-aboard-all-qatari-navy-surface-combatants/

**Comment by PygmalionOfCyprus** [comment]
Fortunately we have a label for just such a scenario!

**Comment by PygmalionOfCyprus** [comment]
(We have a lot of stuff like this come up during our internal news roundups; the "unripe" label is a nifty way of reminding ourselves to double back a few months later and see what new info we can dig up.)

**Comment by bostonmyk** [comment]
Awesome. Thanks.

**Comment by PygmalionOfCyprus** [comment]
I was gonna say, I can just keep this guy open and relabel it as an update.

**Comment by bostonmyk** [comment]
https://twitter.com/D__Mitch/status/1734306385268002854

**Comment by Jkryos** [comment]
Updated DB3K 506.
