### ISSUE TITLE
RCN Diving Tenders x2

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#921]
### DB Selector

DB3K

### Hypothetical

No

### Name

TSRV 610 Sechelt

### Class

Test Range Support Vessels

### Country

Canada

### Service

Navy

### In Commission

1996-

### Length (m)

33

### Beam (m)

7.7

### Draft (m)

2.46

### Standard Displacement (t)

254.7

### Complement

12

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3412 diesels

### Flank Speed (kt)

12.5

### Range (nm) at Speed (kt)

1,000 nm @ 12

### Sensors

- 1x Furuno 1831
- AN/SQQ-505(V)
- x3 Generic Mine Disposal Diver 80m ? (No other options for divers)

### Mounts

- N/A

### Comms/Datalinks

- UHF
- VHF
- VHF/FM

### Comments

Originally 4 vessels were built by West Coast Manly Shipyard to be used as Torpedo and Sound Ranging Vessels (TSRVs) at the Nanoose range but two of the vessels, formally YTPs Sechelt and Sooke, were declared surplus to requirement in March 1996. They have since been converted to Yard Diving Tenders (YDTs) which are manned by regular force personnel and are designated as Minor Warships. The vessels are configured to aid in diving support training and can be fitted with a portable hyperbaric chamber payload. They have fitted mixed gas cylinders, mixing stations, HP compressors, and diving equipment. The 610 Diving Support Vessels have a secondary role of Search and Rescue.

YDT 610 Sechelt
YDT 612 Sooke

### Sources

https://publications.gc.ca/collections/collection_2015/mdn-dnd/D12-21-18-2-eng.pdf
http://www.forposterityssake.ca/Navy/SECHELT.htm
USNI Combat Fleets of the World 16th Edition, pg 84

![00275](https://user-images.githubusercontent.com/99632305/163757621-79e89cd2-52ee-449e-be6b-6a05b0c67ea1.jpg)
![CTB026362](https://user-images.githubusercontent.com/99632305/163757635-25022e7c-0e39-4170-b8e6-aa8930b1e872.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
