### ISSUE TITLE
RCN Torpedo Retrievers x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#922]
### DB Selector

DB3K

### Hypothetical

No

### Name

TSRV 611 Sikanni

### Class

Test Range Support Vessels

### Country

Canada

### Service

Navy

### In Commission

1990-

### Length (m)

33

### Beam (m)

7.7

### Draft (m)

2.46

### Standard Displacement (t)

254.7

### Full Displacement (t)

290

### Complement

6

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3412 diesels

### Flank Speed (kt)

12.5

### Range (nm) at Speed (kt)

1,000 nm @ 12

### Sensors

- 1x Navigation Radar

### Mounts

None

### Comms/Datalinks

- VHF/UHF
- standard

### Comments

The YTP class consists of Torpedo and Sound Ranging Vessels (TSRVs) which are configured to perform various range and underwater acoustic functions. There were originally four vessels in this class. Two of these, formally YPTs Sechelt and Sooke, were declared surplus to requirement in March 1996, and are now converted to diving tenders. The YTP class vessels were specifically
designed and built for use at the Canadian Forces Maritime Experimental Test Range (CFMETR) and are operated by civilian DND personnel. 

YPT 611 CFAV Sikanni
YPT 613 CFAV Stikine

### Sources

buyandsell.gc.ca/cds/public/2019/12/17/6f21d0eb198c841ecb85828e3b087ad6/ABES.PROD.PW_ISM.B029.E27541.ATTA002.PDF
shipspotting.com/photos/2362530
forposterityssake.ca/Navy/SIKANNI.htm
USNI Combat Fleets of the World, 16th Edition, pg 84
https://www.hazegray.org/navhist/canada/current/auxiliary/

![00274](https://user-images.githubusercontent.com/99632305/163758386-b25c9255-d449-4a8d-b364-3d6903385e17.jpg)
![2362530](https://user-images.githubusercontent.com/99632305/163758432-e5908f6d-444a-4a66-ada6-d72fcec7e659.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
