### ISSUE TITLE
RCN Orca Class Training Ships YXT x8

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#923]
### DB Selector

DB3K

### Baseline

2503 DB3k

### Hypothetical

No

### Name

KC 55 Orca

### Class

Orca Class

### Country

Canada

### Service

Navy

### In Commission

2006-

### Length (m)

33

### Beam (m)

8.4

### Draft (m)

2.5

### Standard Displacement (t)

210

### Full Displacement (t)

210

### Complement

20

### Primary Propulsion Type

Diesel

### Propulsion

2x Caterpillar 3516 diesels

### Fuel Capacity (kg)

25000

### Flank Speed (kt)

21

### Range (nm) at Speed (kt)

750@15, 2700 @10

### Sensors

- 1x Raytheon Pathfinder NSC 1810; X band navigation radar

### Mounts

- 1x 12.7mm MG on foredeck

### Aircraft & Docking Facilities

- 1x davit for Zodiac SR2

### Comms/Datalinks

- Standard as per " The design incorporates mock training stations on an enhanced bridge. These training stations feature modern communication and navigation equipment found in major warships."
- communication equipment includes Sailor RT4822 VHF-DSC, SP3300 VHF portable, Taiyo TD-L1630A VHF DF, Sailor HC4500B MF/HF/SSB, Wulfsberg RT-5000 multiband transceiver, Kannad Search and Rescue Transponder (SART) and S1210 EPIRB (Emergency Position Indicating Radio Beacon).

### Comments

Based on the Australian Pacific-class patrol boat design (ASI 315)

### Sources

https://www.naval-technology.com/projects/orca-class/
https://www.hazegray.org/navhist/canada/current/orca/
https://en.wikipedia.org/wiki/Orca-class_patrol_vessel
USNI Combat Fleets of the World, 16th Edition pg 85

![pct-wolf](https://user-images.githubusercontent.com/99632305/163762207-99367250-00a6-450d-bc34-7ba2fe891f19.jpg)
![ORCA_HMCS55](https://user-images.githubusercontent.com/99632305/163762186-8be7962b-2882-494b-a731-b3beb51fb788.jpg)
![06def6_ORCA_55](https://user-images.githubusercontent.com/99632305/163762158-2660abd3-064b-4d79-9e35-5f0f2d98dfd8.jpg)
![06def6_ORCA_boatfront](https://user-images.githubusercontent.com/99632305/163762174-4b923feb-53d1-4a21-aff5-ab4dee4d6c31.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
