### ISSUE TITLE
CCGS Sir Wilfred Grenfell Offshore Multitask Patrol Vessel (WPS)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#924]
### DB Selector

DB3K

### Baseline

1002

### Hypothetical

No

### Name

Sir Wilfred Grenfell

### Class

Sir Wilfred Grenfell

### Country

Canada

### Service

Canadian Coast Guard

### In Commission

1987-

### Length (m)

68.48

### Beam (m)

15.3

### Draft (m)

5.42

### Standard Displacement (t)

3753

### Full Displacement (t)

3753

### Complement

20

### Primary Propulsion Type

Diesel

### Propulsion

2x Deutz 268-2SBV16M and 2x Deutz SBV9m Diesels

### Fuel Capacity (kg)

879.7 m3

### Flank Speed (kt)

16

### Range (nm) at Speed (kt)

11,000 @ 11.5

### Sensors

- 2x Sperry Marine Bridgemaster E - X Band

### Mounts

- None

### Aircraft & Docking Facilities

- 3x davits for 7m RHIB 

### Comms/Datalinks

- VHF AM: ((2) x Colllins HS-500)
- VHF FM: ((2) x Sailor RT-146, (1) x Motorola Astro Spectra, (1) x Skanti 3000
- HF: ((1) x Motorola Micom, (1) x Harris RF 3200)
- SatComms: ((1) x Nera B Inmarsat, (1) x Westinghouse Series 1000 Msat, (1) x Sailor SC4000 Iridium)

### Comments

- Ice strengthened hull

### Sources

https://web.archive.org/web/20180222225758/http://www.ccg-gcc.gc.ca/Fleet/Vessel?vessel_id=99

![dfo-photo-281-multimedia-eng](https://user-images.githubusercontent.com/99632305/163869018-a0d7d3d2-ee1f-46c5-a8dc-12192832be91.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
