### ISSUE TITLE
CCGS Leonard J. Cowley Offshore Multitask Patrol Vessel

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#925]
### DB Selector

DB3K

### Hypothetical

No

### Name

CCGS Leonard J. Cowley

### Class

Leonard J. Cowley

### Country

Canada

### Service

Canadian Coast Guard

### In Commission

1985-

### Length (m)

72.01

### Beam (m)

14.2

### Draft (m)

4.51

### Standard Displacement (t)

1470

### Full Displacement (t)

2080

### Complement

19

### Primary Propulsion Type

Diesel

### Propulsion

2x Nohab Polar F312V diesels

### Fuel Capacity (kg)

420 m3

### Flank Speed (kt)

15

### Range (nm) at Speed (kt)

12,000 @12

### Sensors

- 1x Sperry Marine - Bridgemaster E - X Band
- 1x Sperry Marine - Bridgemaster E - S Band

### Mounts

None

### Aircraft & Docking Facilities

- 2x davits for 7m RHIB's
- 1x pad/hangar for small helicopter

### Comms/Datalinks

- VHF AM: (1) x Icom - L(1) x Collins - 251
- VHF FM: (2) x Sailor - RT-146
- HF: (1) x Yaesu - FRG 7700
- SatComms: (1) x Nera B Inmarsat, (1) x Sailor SC4000 Iridium

### Comments

- 8.1m3 heli fuel

### Sources

https://inter-j01.dfo-mpo.gc.ca/fdat/vessels/78

![dfo-photo-133-multimedia](https://user-images.githubusercontent.com/99632305/163870330-2838c6c5-9b8c-4d1e-9b10-26c03fd97dcd.jpg)
![dfo-photo-137-multimedia](https://user-images.githubusercontent.com/99632305/163870351-bddb1011-fbb9-4543-855b-8896b1487724.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
