### ISSUE TITLE
CCGS Gordon Reid Intermediate Multitask Patrol Cutter

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#926]
### DB Selector

DB3K

### Hypothetical

No

### Name

CCGS Gordon Reid

### Class

Gordon Reid Class

### Country

Canada

### Service

Canadian Coast Guard

### In Commission

1991-

### Length (m)

50

### Beam (m)

11

### Draft (m)

5.4

### Standard Displacement (t)

1100

### Complement

14

### Primary Propulsion Type

Diesel

### Propulsion

4x Deutz-MWM SBV-6M-628

### Fuel Capacity (kg)

148.2m3

### Flank Speed (kt)

16.5

### Range (nm) at Speed (kt)

2500 @12

### Sensors

- 2x Sperry Marine - Bridgemaster E - X Band

### Mounts

None

### Aircraft & Docking Facilities

- 2x Davits for 7m RHIB
- 1x Stern ramp for RHIB

### Comms/Datalinks

- VHF FM: (3) x Motorola - MCX1000
- HF: (1) x Motorola - Micom

### Sources

https://inter-j01.dfo-mpo.gc.ca/fdat/vessels/67

![dfo-photo-785-multimedia](https://user-images.githubusercontent.com/99632305/163871702-d30034f7-8164-4a5f-8e18-617fc820025d.jpg)
![dfo-photo-603-multimedia](https://user-images.githubusercontent.com/99632305/163871713-4313747c-a839-4169-aa57-6e34dae991a0.jpg)
![dfo-photo-708-multimedia](https://user-images.githubusercontent.com/99632305/163871724-dfbd0884-93f3-48ab-b8a1-603659350be3.jpg)

**Comment by Jkryos** [comment]
Added DB3K 497.
