### ISSUE TITLE
Chile BMS 42 Almirante José Toribio Merino Castro [Alvsborg Class Submarine Tender]

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#929]
### DB Selector

DB3K

### DBID to Copy

2225 DB3k

### Hypothetical

No

### Name

 2x Nohab-Polar 112VS Diesels

### Country

Chile

### Service

Navy

### In Commission

1997-2015

### Sensors

- 1x Terma Scanter 009 Navigation
- 1x Raytheon Navigation
- 1x Sea Giraffe 50HC surf/air search
- 1x CelsiusTech 9LV 200 f.c.

### Mounts

- 3x single 40mm/70 Bofors SAK 40/48 AA
- Mine racks

### Loadout Options

- 300 mines

### Other Changes

- Crew of 90
- Accomodation's for 205 submarine crew members

### Sources

Combat Fleets of the World, 16th Edition pg. 102
https://en.wikipedia.org/wiki/HSwMS_%C3%84lvsborg
https://www.globalsecurity.org/military/world/chile/bach-toribio-merino.htm
https://www.armada.cl/history-of-the-navy/current-ships/a/submarine-tender-almirante-jose-toribio-merino-castro

![BASENAVAL_383](https://user-images.githubusercontent.com/99632305/163924533-c3e82f09-2b16-4f41-bfdb-0907658bf5b7.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
