### ISSUE TITLE
Please add air-to-air missile loadout to HESA Karrar

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#93]
### DB Selector

DB3K

### User(s)

#4903 HESA Karrar

### Weapons Carried

- 1x  Azarakhsh missile, IR guided AAM, most likely an Iranian Sidewinder copy

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

160

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Iranian has recently tested the Karrar as anti-air role. The missile attached below the UCAV is  Azarakhsh missile, which most probably Iranian copy of Sidewinder. Since the game doesnt have the missile yet, for the sake of simplicity, it can be equipped with AIM-9 missile instead,

### Sources

https://www.reddit.com/r/WarplanePorn/comments/m8dya8/iranian_hesa_karrar_ucav_fitted_with_a_shortrange/
https://www.thedrive.com/the-war-zone/38580/iran-just-fired-its-sidewinder-missile-clone-from-a-drone
https://mobile.twitter.com/fab_hinz/status/1406912732780281856
https://www.tehrantimes.com/news/456707/Iran-s-Army-fires-Azarakhsh-missile-in-large-scale-drone-exercise
![image](https://user-images.githubusercontent.com/99646926/153844149-f9440a2e-d5a5-4448-8a7a-f7fd6299832d.png)

**Comment by PygmalionOfCyprus** [comment]
Added along with Azarakhsh missile for 493. (For now I've got the Azarakhsh in as only A/A even though the Iranians claim it can do A2G since we've seen nothing of that capability.)
