### ISSUE TITLE
Cruiser Ukrainia (Hypothetical finished Fourth Slava)

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#931]
### DB Selector

DB3K

### DBID to Copy

Ship 87 (DB3K)

### Hypothetical

Yes

### Name

RKR Ukrainia

### Country

Ukraine

### Service

Navy

### In Commission

1992-present

### Sensors

Same as Ship 87

### Mounts

Same as Ship 87

### Loadout Options

Same as Ship 87

### Other Changes

Just a hypothetical where Ukraine got to finish the unfinished Slava cruiser. No apparent differences with the existing USSR model (ship 87) that I could find. 

### Sources

https://en.wikipedia.org/wiki/Ukrainian_cruiser_Ukraina

**Comment by PygmalionOfCyprus** [comment]
Unless we get some indication / source that indicates a hypothetical alternate fitting I'd say people can just plop down an existing Slava and rename it in ScenEdit if they want to create "Ukraine gets a Slava" scenarios.

**Comment by Coiler12** [comment]
All right, no problem.
