### ISSUE TITLE
Loadouts, QuickTurnaround, the Cutie update, part 1

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#933]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

From a gameplay situation during which I was kind of surprised that my Algerian MiG-29 couldn't perform a quick-turnaround in their AA role, I went ahead and looked at the DB. Based on the manual description of what should be quick- turnaround capable[^1], and similar DB entries, I believe that these loadouts values could be modified as suggested below.

**DataLoadout**

> So here we have _land based_ aircraft with an Air Superiority, with WVR or BVR AAMs, loadouts.
> I determined that, throughout the DB, a standard ReadyTime for such a combination seems to be 30 minutes [^2].
> What I thus suggest doing here is :

_DataLoadout.ID_
- `69, 147, 150, 151, 170, 332, 352, 361, 389, 532, 538, 683, 707, 739, 765, 770, 827, 966, 1099, 1134, 1348, 1437, 1629, 1675, 1777, 1851, 1853, 2078, 2105, 2127, 2173, 2195, 2205, 2215, 2220, 2241, 2488, 2491, 2523, 2543, 2637, 2648, 2885, 2920, 2993, 3058, 3078, 3333, 3406, 3637, 3982, 4017, 4018, 4141, 4216, 4224, 4225, 4280, 4281, 4352, 4444, 4451, 4455, 4457, 4467, 4472, 4485, 4494, 4654, 4663, 4686, 4691, 4716, 4733, 4754, 4878, 4891, 4897, 4903, 4909, 4916, 4917, 4921, 4924, 4925, 4932, 4933, 4939, 4940, 4947, 4948, 4954, 4955, 4961, 4962, 4971, 4972, 5003, 5011, 5027, 5028, 5040, 5041, 5059, 5060, 5068, 5077, 5158, 5167, 5176, 5185, 5186, 5195, 5204, 5213, 5222, 5251, 5252, 5280, 5281, 5289, 5290, 5298, 5299, 5307, 5308, 5325, 5326, 5347, 5348, 5376, 5377, 5466, 5715, 5755, 5756, 6041, 6091, 6092, 6159, 6169, 6267, 6284, 6285, 6293, 6417, 6484, 6492, 6494, 6533, 6583, 6590, 6600, 6610, 6684, 6798, 6799, 6806, 6807, 6813, 6852, 6853, 6961, 6968, 6969, 6976, 7164, 7174, 7175, 7184, 7351, 7553, 7572, 7597, 7680, 7697, 7732, 7749, 7802, 7815, 7816, 8020, 9137, 9138, 9166, 9255, 9529, 10594, 11794, 11795, 11841, 11842, 11843, 11850, 11852, 11853, 11854, 11855, 11862, 11863, 11865, 11866, 11868, 11869, 11870, 11871, 11882, 11883, 11884, 11885, 11895, 11896, 11899, 11900, 11916, 11917, 11918, 11928, 11929, 12039, 12048, 12085, 12088, 12089, 12656, 12684, 12704, 12714, 12724, 12734, 12735, 12747, 12777, 12787, 12788, 12798, 12808, 12861, 12862, 12882, 12892, 12893, 12903, 13025, 13035, 13045, 13046, 13134, 13192, 13258, 13297, 13298, 13299, 13324, 13330, 13336, 13342, 13348, 13360, 13842, 13843, 13844, 14011, 14012, 14013, 14018, 14022, 14045, 14046, 14176, 14247, 14248, 14249, 14250, 14251, 15204, 15427, 15428, 15429, 15430, 15446, 15447, 15448, 15449, 15511, 15512, 15513, 15514, 15539, 15540, 15541, 15542, 16112, 16172, 16182, 16192, 16205, 16217, 16218, 16304, 16334, 16707, 16708, 16709, 16710, 16711, 16712, 16713, 16714, 16731, 16732, 16787, 16788, 16864, 16865, 16866, 16867, 16871, 16979, 16980, 16981, 16982, 17168, 17169, 17170, 17171, 17191, 17192, 17270, 17271, 17643, 17644, 17646, 17647, 17654, 17655, 17832, 18075, 18077, 18405, 18406, 18411, 18412, 18416, 18417, 18418, 18419, 18423, 18424, 18425, 18426, 18427, 18428, 18429, 18430, 18479, 18480, 18582, 18598, 18599, 18606, 18607, 18684, 18694, 18695, 19113, 19115, 19270, 19280, 19366, 19367, 19368, 19369, 19404, 19550, 19825, 19853, 20077, 20252, 21651, 21652, 22108, 22116, 22290, 22306, 22307, 22354, 22459, 22745, 22798, 22799, 22800, 22801, 22802, 25001, 25002, 25119, 25458, 25465, 25475, 25476, 25775, 26344, 26345, 26378, 26379, 26613, 26614, 26615, 26625, 26626, 26627, 27615, 28228, 29050, 29055, 29067, 29068, 29500, 29507, 29509, 29516, 29518, 29525, 29529, 29531, 29811, 29866, 29867, 29868, 29869, 29871, 29872, 29873, 30333, 30334`

- [ ] _SET_

- `DataLoadout.QuickTurnaround = 1, DataLoadout.QuickTurnaround_ReadyTime = 30, DataLoadout.QuickTurnaround_MaxSorties = 2, DataLoadout.QuickTurnaround_AirborneTime = 240, DataLoadout.QuickTurnaround_TimeofDay = 2001`

<kbd>6417 is an AIM9L loadout that offers to the Turksih F-4E Phantom II [Terminator 2020] a QuickTurnaround_ReadyTime of 360. I assumed a typo.</kbd>
---

> Then we have a few _carrier based_ aircraft with an Air Superiority,  with WVR AAMs, loadouts.
> I determined that, throughout the DB, a standard ReadyTime for such a combination seems to be 60 minutes [^2].
> What I thus suggest doing here is :

_DataLoadout.ID_
- `1437, 2291, 2294`

- [ ] _SET_

- `SET DataLoadout.QuickTurnaround = 1, DataLoadout.QuickTurnaround_ReadyTime = 60, DataLoadout.QuickTurnaround_MaxSorties = 2, DataLoadout.QuickTurnaround_AirborneTime = 240, DataLoadout.QuickTurnaround_TimeofDay = 2001`

---

### Sources

[^1]: CMO manual EBOOK, page 302 :
_The default quick-turnaround mode is for “fighters and ASW” aircraft, which allows for appropriate aircraft with simple anti air/submarine loadouts (that would realistically need to launch quickly) to deploy rapidly without unbalancing the rest of the scenario._

DB3K_493

[^2]: There are various ReadyTime values for a same loadout role. I guess it's a way to simulate soft factors such as doctrine and training. While I believe that some harmonization wouldn't hurt, I am taking some time to gather evidence to substantiate my suggestions.

**Comment by claudejdev** [comment]
Hey there @PygmalionOfCyprus 
is there anything I could do to make this issue easier for you to fix?

Cheers

**Comment by PygmalionOfCyprus** [comment]
Handled 505. Sorry it took so long!
