### ISSUE TITLE
Brazil - SAM RBS-70NG

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#936]
### DB Selector

DB3K

### Hypothetical

No

### Name

RBS70NG

### Facility Type

SAM

### Country

Brazil

### Service

Army

### In Commission

2021

### Crew

2

### Dispersion Radius (m)

20

### Sensors

1 X MK1 Eyeball
1 x SABER M60

### Mounts

3 x RB70NG 

### Sources

https://www.saab.com/newsroom/press-releases/2019/saab-receives-rbs-70-ng-order-from-the-brazilian-army

https://www.infodefensa.com/texto-diario/mostrar/3123176/exercito-brasileiro-recebera-sistema-antiaereo-rbs-70-ng-nos-proximos-dias

**Comment by Jkryos** [comment]
Added DB3K 496.
