### ISSUE TITLE
Brazil - SAM RBS70

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#937]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM RBS70Mk.2

### Facility Type

SAM

### Country

Brazil

### Service

Army

### Sensors

1 X EYEBALL MK1
1 X SABER M60

### Mounts

3 X RB70 Rayrider MK2

### Sources

https://caiafamaster.com.br/cobertura/exercito-brasileiro-adquire-mais-50-misseis-rbs70-mk2-da-saab-por-us-usd-295-milhoes/

https://www.defesanet.com.br/terrestre/noticia/14410/EB-%E2%80%93-Adquire-o--missil-SAAB--RBS-70-MkII/

**Comment by Jkryos** [comment]
Added DB3K 494.
