### ISSUE TITLE
Brazil - AAA Bofors L70 with EDT FILA

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#939]
### DB Selector

DB3K

### Hypothetical

No

### Name

Bofors L70 with EDT FILA

### Facility Type

AAA

### Country

Brazil

### Service

Army

### In Commission

1980 -

### Crew

4

### Dispersion Radius (m)

40

### Sensors

1 x Avibras EDT FILA

### Mounts

[40mm/70 Single Bofors Burst]

### Comments

The Avibras EDT FILA RADAR is pretty much a SKYGUARD Avibras Copy 

For Reference https://www.deagel.com/Sensor%20Systems/Skyguard/a001389

### Sources

http://www.eb.mil.br/web/noticias/noticiario-do-exercito?p_p_id=101&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_101_struts_action=%2Fasset_publisher%2Fview_content&_101_assetEntryId=8348721&_101_type=content&_101_urlTitle=4-gac-escola-de-fogo-de-tres-marias-mg&inheritRedirect=true

http://www.eb.mil.br/web/noticias/noticiario-do-exercito?p_p_id=101&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_101_struts_action=%2Fasset_publisher%2Fview_content&_101_assetEntryId=2155330&_101_type=content&_101_groupId=11425&_101_urlTitle=3-grupo-de-artilharia-antiaerea-operacao-fenix&_101_redirect=http%3A%2F%2Fwww.eb.mil.br%2Fweb%2Fnoticias%2Fnoticiario-do-exercito%3Fp_p_id%3D3%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_3_cur%3D250%26_3_keywords%3Dcorrida%2Bda%2Bpaz%26_3_advancedSearch%3Dfalse%26_3_groupId%3D0%26_3_delta%3D20%26_3_assetTagNames%3Dcms%26_3_resetCur%3Dfalse%26_3_andOperator%3Dtrue%26_3_struts_action%3D%252Fsearch%252Fsearch&inheritRedirect=true

https://tecnodefesa.com.br/os-desafios-da-defesa-antiaerea-de-media-altura-no-exercito-brasileiro-parte-1/

https://www.brasilemdefesa.com/2013/03/canhao-antiaereo-bofors-l70-40mm.html

**Comment by Jkryos** [comment]
Added DB3K 496.
