### ISSUE TITLE
USAF F-15E GBU-39 / GBU-53 Loadout Request

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#94]
### DB Selector

DB3K

### User(s)

USAF F-15E (#3222 and subsequent models)

### Weapons Carried

F-15Es can be armed with upto 28 GBU-39s and GBU-53s on seven BRU-61/A racks. At the moment, I can only find proof of 20 on five racks.

Loadouts:
x2 AIM-120D
x2 AIM-9X
x1 AN/AAQ-13
x1 AN/AAQ-33
x2 CFTs
x2 EFTs
x20 GBU-39s OR x20 GBU-53s

Loadouts:
x2 AIM-120D
x2 AIM-9X
x1 AN/AAQ-13
x1 AN/AAQ-33
x2 CFTs
x28 GBU-39s OR x28 GBU-53s

![BRU-61A ProductImage](https://user-images.githubusercontent.com/99649251/153843469-5a2bc3a4-9a2c-466e-844a-29ec74486398.jpg)
![message-editor_1610069115754-f-15-sdbs](https://user-images.githubusercontent.com/99649251/153843994-924d8744-afbe-4fb7-ab72-26d45ffe71b4.jpg)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Unknown

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Unsure of range, but will be shorter than 1150nm range on x8 SDB loadouts (#17276).

### Sources

https://www.thedrive.com/the-war-zone/38604/the-age-of-swarming-air-launched-munitions-has-officially-begun-with-air-force-test

https://en.wikipedia.org/wiki/GBU-53/B_StormBreaker

**Comment by PygmalionOfCyprus** [comment]
Added, with the 28x versions marked as hypothetical.
