### ISSUE TITLE
BRAZIL - Leopard 1A5 

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#940]
### DB Selector

DB3K

### DBID to Copy

Facility 530

### Hypothetical

No

### Name

Armored Plt (Leopard 1A5BR MBT x 4)

### Country

Brazil

### Service

Army

### In Commission

2009 - Present

### Sources

http://www.eb.mil.br/exercito-brasileiro?p_p_id=101&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_101_struts_action=%2Fasset_publisher%2Fview_content&_101_assetEntryId=750157&_101_type=content&_101_groupId=16541&_101_urlTitle=exercito-recebe-novo-lote-do-leopard-1a5br&_101_redirect=http%3A%2F%2Fwww.eb.mil.br%2Fexercito-brasileiro%3Fp_p_id%3D3%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_3_cur%3D102%26_3_keywords%3Dcampo%2Bgrande%26_3_advancedSearch%3Dfalse%26_3_groupId%3D0%26_3_delta%3D20%26_3_resetCur%3Dfalse%26_3_andOperator%3Dtrue%26_3_struts_action%3D%252Fsearch%252Fsearch&inheritRedirect=true

https://www.brasilemdefesa.com/2012/05/leopard-1-a5.html

**Comment by Jkryos** [comment]
Added DB3K 494.
