### ISSUE TITLE
BRAZIL - M109A5 BR+

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#941]
### DB Selector

DB3K

### DBID to Copy

Facility 2929

### Hypothetical

No

### Name

Arty Bty (155mm/39 M109A5br+ Self-Propelled Howitzer x 6)

### Country

Brazil

### Service

Army

### In Commission

2019 - Present

### Sources

https://tecnodefesa.com.br/chegam-finalmente-ao-brasil-os-m-109a5-br-plus-modernizados-pela-bae-systems-aco/

https://www.defesanet.com.br/doutrina/noticia/35079/M109-A5+BR---Uma-nova-Forma-de-Atuar-da-Artilharia-do-Exercito-Brasileiro/

https://www.eb.mil.br/web/noticias/noticiario-do-exercito/-/asset_publisher/znUQcGfQ6N3x/content/id/12357262

**Comment by Jkryos** [comment]
Added DB3K 494.
