### ISSUE TITLE
Brazil - L118 AR Light Gun

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#943]
### DB Selector

DB3K

### DBID to Copy

Facility 330

### Hypothetical

No

### Name

Arty Bty/3 (105mm/37 L118 Towed Light Gun x 2)

### Country

Brazil

### Service

Army

### In Commission

2000 - Present

### Sources

https://www.brasilemdefesa.com/2013/12/obuseiro-leve-105-mm-l118-ar.html

https://estrategiaglobal.blog.br/2017/05/batalhao-de-artilharia-de-fuzileiros-navais-realiza-exercicio-de-tiro-de-artilharia.html

https://tecnodefesa.com.br/recuperacao-de-obuseiros-de-105mm/

**Comment by Jkryos** [comment]
Added DB3K 494.
