### ISSUE TITLE
Brazil - LP23SST Radar

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#944]
### DB Selector

DB3K

### Hypothetical

No

### Name

Radar (LP23SST) 

### Facility Type

Radar

### Country

Brazil

### Service

Air Force

### Crew

6

### Sensors

1 X LP23SST

### Mounts

1 X LP23SST

### Sources

https://caiafamaster.com.br/aereo/cobertura-radar-na-fronteira-brasil-paraguai-e-bolivia-capacidade-de-vigilancia-aerea-ampliada/

https://omnisys.com.br/a-thales-apresenta-o-lp23sst-ng-o-radar-de-vigilancia-em-rota-de-uso-dual-civil-e-militar-mais-avancado-do-mundo-e-ja-vendido-para-o-brasil

https://www.omnisys.com.br/data-seet/radar-primario-lp23sst-ng.pdf

**Comment by LucasSFCMANO** [comment]
Will do, and paste the link on the comments

**Comment by PygmalionOfCyprus** [comment]
Added 494.
