### ISSUE TITLE
Brazil - Agusta Lynx MK-11B Wild Lynx

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#945]
### DB Selector

DB3K

### DBID to Copy

Aircraft #4221

### Hypothetical

No

### Name

Agusta Lynx MK-11B Wild Lynx

### Country

Brazil

### Service

Navy

### In Commission

2019 - Present

### Loadout Options

2 x Sea Skua

### Sources

https://www.helis.com/database/news/super-lynx-brasil-ah-11b-4/

https://www.helis.com/database/news/super-lynx-brasil-ah-11b-3/

https://www.helis.com/database/news/super-lynx-brasil-ah-11b-2/

https://www.helis.com/database/cn/2184/

https://forcaaerea.com.br/marinha-do-brasil-incorpora-o-quarto-ah-11b-wild-lynx/

**Comment by PygmalionOfCyprus** [comment]
Added 494.
