### ISSUE TITLE
Missing Firing Control for HMS Dragon Main gun

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#946]
### DB Selector

DB3K

### Affected DBID(s)

2642 3438 3200

### Summary of Changes

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=383066&p=4989140#p4989140

Add Radamec Fire Control directors back. Doesn't look like it was copied over.

### Sources

Testing

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=383066&p=4989140#p4989140

**Comment by Jkryos** [comment]
Updated DB3K 494.
