### ISSUE TITLE
INS Delhi and Mysore Barack-1 VLS and CIWS Fixes 

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#947]
### DB Selector

DB3K

### Affected DBID(s)

603, 2778

### Summary of Changes

Delhi and Mysore have 32 VLS total so reduce by 2 8-cell mounts VLS Mounts (see first 2 links). Should be 2 8-cell banks on each side. INS Mumbai doesn't have VLS at all but 2 more CIWS (so like nonupgraded #345)

### Sources

Mysore
https://twitter.com/DefenceDecode/status/1493227629004324864
Delhi
https://upload.wikimedia.org/wikipedia/commons/9/95/INS_Delhi.jpg
Mumbai
https://upload.wikimedia.org/wikipedia/commons/5/57/INS_Mumbai_celebrates_20th_anniversary_today.jpg
All three Delhis
https://www.reddit.com/r/IndianDefense/comments/ngd33p/all_three_delhi_class_destroyers_sailing_together/

**Comment by Jkryos** [comment]
Updated DB3K 494.
