### ISSUE TITLE
Amendment to weapons of SSM Plt (SSC-6 Sennight [3K60 Bal-E])

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#948]
### DB Selector

DB3K

### Affected DBID(s)

#2217 - SSM Plt (SSC-6 Sennight [3K60 Bal-E]) (Russia [1992-] - 2009)

### Summary of Changes
#2217 - SSM Plt (SSC-6 Sennight [3K60 Bal-E]) (Russia [1992-] - 2009)
Bal-E is the export version. Should just be [3K60 Bal] . 
More importantly the DB entry uses the ship based Kh-35 SS-N-25 Switchblade x8 from 2x SSC-6 "Switchblade" TELAR [3M24E] which should be amended to Sennight TELAR [3M24] and then:
Please create a copy of the Switchblade #969 - SS-N-25 Switchblade [Kh-35 Uran] GLONASS
OR more accurately a ground launched version of  air launched Kayak #978 - AS-20 Kayak [Kh-35U Star]
to create the SSC-6 Sennight [Kh-35U Star] as a weapon in its own right and in fact the Bal land based system appears to be using the Kh-35U with longer range (240-260km) and land attack capability rather than the original basic Kh-35.
Although it appears either missile can be mounted. 

### Sources

DB493 and recent evidence of Bal launches against Ukrainian land targets. https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/april/11639-russian-forces-reportedly-uses-bal-coastal-defense-systems-in-ukraine.html
http://roe.ru/eng/catalog/naval-systems/coastal-weapon-systems/bal-e/

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
