### ISSUE TITLE
USA - US Army - Raytheon GhostEye (formerly LTAMDS) - Main Array

### ISSUE THREAD

**Issue by SolomonDread** [PygmalionOfCyprus/cmo-db-requests#949]
### DB Selector

DB3K

### Baseline

2498

### Hypothetical

No

### Name

GhostEye (LTAMDS) Main Array

### Sensor Generation

Late 2010s

### Sensor Capabilities

Air Search, Space Search - ABM, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Continuous Tracking Capability, Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA), Interrupted Continuous Wave Illumination

### Search/Track Frequencies

G Band (4-6 GHz) [Old C Band] 5-7.5 cm, H Band (6-8 GHz) [Old C Band] 3.75-5 cm

### Comments

GhostEye is a replacement radar for the AN/MPQ-53 and AN/MPQ-65 currently used by the MIM-104 Patriot missile system. The radar is consisted of one main array flanked by two smaller secondary arrays to create a system that can provide a full 360-degree in azimuth of coverage. [1][2]  

- This entry is specifically about the main array. Unfortunately, I don't have much information about the secondary array except for it being a scaled down main array. I don't know if the equation that will be mentioned below can be used to get a rough estimate (maybe the scale can be obtained from the picture).

The main array is about the size of the MPQ-53 or 65, but has at least twice more power. GhostEye radars are AESAs with gallium nitride technology, which improves the capabilities of the radar (compare to?). [1][2] 

- I'm not sure if "twice more power" means the power output. I do some back-of-the-envelope calculation with a help of the online calculator based on this [equation](https://www.translatorscafe.com/static/ucvt/img/calc-radar-max-range-f1.svg) to visualize what could that mean. The AN/MPQ-53 in CMO has a range of 90 nautical mile, that means that, if all things are equal, then doubling in power means a 20% increase in range, or a range of ~108 nautical mile for GhostEye. This is just a visualization with all but one variables controlled, so this is not helpful. 

GhostEye is operating in NATO G/H bands (IEEE C-band) like the AN/MPQ-53 and 65. It also have S and X-band missile communication arrays that may be used in target acquisition. [3]

The radar is planned to be operational sometime in late 2022. [1]

- So we know that this isn't hypothetical and a possible time it'll enter service. It didn't have a military designation yet.

- I don't know exactly how much more capable is the GhostEye compared to AN/MPQ-53 or 65. In-game, the main array alone might have the same or similar arc as the current Patriot radar, but as a facility, with two secondary arrays, the coverage will be 360, but the secondary array means that their sector will not have as much range as the primary one, at least according to this [presentation](https://pbs.twimg.com/media/FIHH6w-XMAEi9w2.jpg).

### Sources

1. [Official Raytheon News](https://www.raytheonmissilesanddefense.com/news/2021/10/08/ghosteye-nothing-goes-unseen) --- 8 October, 2021

> These radars provide 360-degree coverage and use active electronically scanned array, or AESA, and gallium nitride, or GaN.

> GaN strengthens the radar signal and enhances its sensitivity for longer range, higher resolution and increased capacity.

> The first radars are planned to be operational in the fourth quarter of 2022.

---------------------------------------------------------------------------------------------------------------------------------------------
2. [Official Raytheon Page](https://www.raytheonmissilesanddefense.com/what-we-do/missile-defense/air-and-missile-defense-systems/ghosteye) --- Page Indexed 2 Years Ago by Google

> LTAMDS has three antenna arrays – a primary array on the front, and two secondary arrays on the back. They work together, detecting and engaging multiple threats from any direction at the same time. 

> The primary array is about the same size as the array for the Patriot Air and Missile Defense System, but it has more than twice the power.

---------------------------------------------------------------------------------------------------------------------------------------------
3. [MDAA](https://missiledefenseadvocacy.org/defense-systems/lower-tier-air-and-missile-defense-sensor-ltamds/) --- 24 July, 2020

> LTAMDS uses C-band radar for its primary mission, however, the dual-band frequency functionality is an important design feature to meet the needs of the Army to fill capability gaps for decades to come.  The LTAMDS uses S-band and X-band frequencies for missile communication, to include target acquisition through deep surveillance. 

---------------------------------------------------------------------------------------------------------------------------------------------
4. [LTAMDS presentation](https://pbs.twimg.com/media/FIHH6w-XMAEi9w2.jpg) --- Original source unknown

**Comment by PygmalionOfCyprus** [comment]
Added 494. Sort of. We don't currently have a good way of modelling multiple different sensors pointing in various directions on a single "mount," so for now it's a big 360-degree blob, which isn't ideal.

Workaround option is to create three (two?) separate mounts to represent the different radars. This would work okay, but it will lead to weird situations where one radar gets knocked out and the other is fine despite them being mounted on the same vehicle.

I'll do that in the interim if we can't ship some sort of better solution for 494.
