### ISSUE TITLE
HESA Karrar EO sensor is missing

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#95]
### DB Selector

DB3K

### Affected DBID(s)

#4904 - HESA Karrar UCAV [Recon] (Iran - 2010)

### Summary of Changes

The EO sensor for recon loadout is missing even thought the description said got EO/IR. Add EO sensor to the aircraft.

### Sources

![image](https://user-images.githubusercontent.com/99646926/153845555-df5b2f87-eda6-4576-89c8-63ff9a6c2492.png)

![image](https://user-images.githubusercontent.com/99646926/153845707-8e4ce9d9-3775-4360-b9a9-05775224fe6f.png)

**Comment by PygmalionOfCyprus** [comment]
Did a deeper dive on the Karrar. Couple issues in the DB, namely that the thing doesn't have any internal EO/IR. Nor does it have a radar, which for some reason it had. Anyway, I've stripped its sensors and made some adjustments to both versions, including to the loadouts of the armed version. "Recon" variant is now the target drone version.
