### ISSUE TITLE
Brazil - A-29 - Air to Air Capablity 

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#951]
### DB Selector

DB3K

### User(s)

#1840 A29A Super Tucano

### Weapons Carried

[12.7mm/50 Twin MG Burst [20 rnds]

### Requires Buddy Illumination

No

### Weather Restrictions

Clear Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Configuration used for Air to Air INTERCEPTS of Illegal Aircraft and Patrolling - QRA for Air Defense

### Sources

https://www.flickr.com/photos/portalfab/13569550445

https://www.fab.mil.br/noticias/mostra/38659/INTERCEPTA%C3%87%C3%83O%20-%20FAB%20intercepta%20aeronave%20carregada%20com%20165%20kg%20de%20drogas%20no%20Amazonas

https://www.youtube.com/watch?v=bPg_oZNXlb0 ( Real Use)

https://globoplay.globo.com/v/5980541/ ( Real Use)

**Comment by PygmalionOfCyprus** [comment]
This looks like an internal mount more than a loadout; I'll handle it accordingly.

**Comment by PygmalionOfCyprus** [comment]
Added 494.
