### ISSUE TITLE
Brazil - LP23SST Radar (Sensor)

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#952]
### DB Selector

DB3K

### Hypothetical

No

### Name

Radar (LP23SST)

### Sensor Generation

Early 2020s

### Sensor Capabilities

Air Search, Altitude Information, Speed Information, Heading Information

### Search/Track Frequencies

L Band (40-60 GHz) [Old Ka Band] 5-7.5 mm

### Lower Frequency (Hz)

1.250mhz

### Upper Frequency (Hz)

1350mhz

### Target Altitude (ft)

75000

### Comments

Link to Previous Request:

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/944

### Sources

https://caiafamaster.com.br/aereo/cobertura-radar-na-fronteira-brasil-paraguai-e-bolivia-capacidade-de-vigilancia-aerea-ampliada/

https://omnisys.com.br/a-thales-apresenta-o-lp23sst-ng-o-radar-de-vigilancia-em-rota-de-uso-dual-civil-e-militar-mais-avancado-do-mundo-e-ja-vendido-para-o-brasil

https://www.omnisys.com.br/data-seet/radar-primario-lp23sst-ng.pdf (radar manual/pamplet)

**Comment by PygmalionOfCyprus** [comment]
Added 494.
