### ISSUE TITLE
Brazil - EE-9 CASCAVEL Engesa

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#953]
### DB Selector

DB3K

### Hypothetical

No

### Name

Mech Inf Plt (EE-09 Cascavel APC x 4) 

### Facility Type

Mech

### Country

Brazil

### Service

Army

### In Commission

1974 - Current

### Crew

12

### Dispersion Radius (m)

20

### Sensors

1 x Eyeball MK1
1 x Binoculars
[Generic Gun Director [LLTV]

### Mounts

1 x 90mm CM90 Mk.3
1 x Mag 7,62 

### Magazines

44 x 90MM ammunition
500 x 7.62 ammo

### Sources

https://www.brasilemdefesa.com/2014/01/ee-9-cascavel-engesa.html

https://www.defesanet.com.br/guarani/noticia/24184/Blindado-Cascavel-volta-modernizado/

https://www.armasnacionais.com/2017/10/engesa-ee-9-cascavel-mk-iii.html

**Comment by Jkryos** [comment]
Added DB3K 496.
