### ISSUE TITLE
Brazil - SMKB Bomb

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#956]
### DB Selector

DB3K

### User(s)

#1840 #1537 #2945 #2102

### Weapons Carried

2 X SMKB 83

----------------------------

2 X SMKB 82

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Smart Guided Weapon System - SMKB

Smart Guided Bomb, for air-to-ground warfare, low exposure to enemy fire and providing improved accuracy, at a range of up to 24 km, under all-weather, sandstorm, smoke, fog and dusty environments.

The SMKB employs Inertial Guidance and Global Positioning Systems (INS/GPS) operating under encrypted wireless data transfer and guiding 500 pounds MK-82 or 1,000 pounds MK-83 modular bombs.

Features and advantages:

The SMKB weapon receives its mission data and can change its operating modes, download and upload its firmware and execute built-in tests, via wireless communication;
No electrical connection, subsequently easier operation in any airplane;
Significant reduction in integration costs;
GPS position and impact angle settled on ground or during the captive flight;
BIT and “in range” information available during the captive flight;
Wide range of launching points;
Real time envelope calculation sending to pilot;
Developed for worldwide aircrafts, including non-modernized ones.

The SMKB (Smart-MK-Bomb) is a guidance kit that turns a standard Mk 82 (500 lbs) and Mk 83 (1.000 lbs) into a Precision-guided weapon, respectively called SMKB-82 and SMKB-83. The kit provides extended range up to 50 kilometres (27 nmi) and are guided by an integrated inertial guidance system coupled to three satellites networks, relying on wireless to handle the flow of data between the aircraft and the munition.

### Sources

https://artigos.wiki/blog/en/SMKB

https://archive.ph/20121231143549/http://www.mectron.com.br/armamentos-inteligentes.asp

https://www.aereo.jor.br/2013/01/08/aeq-e-fab-darao-inicio-aos-testes-com-bomba-guiada-smkb-83/

https://www.aereo.jor.br/2013/01/08/aeq-e-fab-darao-inicio-aos-testes-com-bomba-guiada-smkb-83/

https://en.wikipedia.org/wiki/SMKB

http://sistemasdearmas.com.br/pgm/smkb.htm
[catalogo-smkb.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8764283/catalogo-smkb.pdf)
l

**Comment by LucasSFCMANO** [comment]
Updated the Weapon Catalog from the manufacturer in .pdf

**Comment by Jkryos** [comment]
Added DB3K 496.
