### ISSUE TITLE
Kamand CIWS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#958]
### DB Selector

DB3K

### DBID to Copy

AK-630M 30mm/60m Gatling

### Hypothetical

No

### Name

Kamand CIWS

### Country

Iran

### Service

Navy

### In Commission

2019

### Sensors

Seroj EO/IR FC

### Other Changes

Seen Mounted on 
#1154 Vosper-Frigate Alborz and Alvand in 2019 (mounted aft)
#2250 Jamaran-class frigate IRIS Sahand (74). (mounted aft)

### Sources

https://www.janes.com/defence-news/news-detail/iranian-navy-upgrades-alborz-frigate-with-new-combat-systems
https://twitter.com/AmirIGM/status/1202152878137323520
https://twitter.com/AmirIGM/status/1419223026277756929
https://missilethreat.csis.org/iran-installs-kamand-phalanx-like-weapon-system-on-destroyer/
https://www.deagel.com/Cannons%20&%20Gear/Kamand/a003749

**Comment by PygmalionOfCyprus** [comment]
Added 494. Also did the rest of the Alvand-class refit since there was more than just the new CIWS.
