### ISSUE TITLE
Thai Gripen ASuW and AAW Loadout Updates

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#959]
### DB Selector

DB3K

### User(s)

3361 and 3362

### Weapons Carried

Since 2012-IOC
ASuW
2 RB-15F + 2 Iris T+centerline tank
2 RB-15F + 2 IRIS-T and 2 Sidewinder P

I'd copy AAW loadouts and swap Sidewinder for IRIS-T.

Looks like they share Sidewinders and Amraams with Falcons.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

RBS-15F+IRIS T+ centerline Tank
https://www.janes.com/defence-news/news-detail/royal-thai-air-force-to-upgrade-gripen-cd-combat-aircraft-to-ms20-standard
https://twitter.com/thebaseleg/status/951807381414952960
https://thaimilitaryandasianregion.wordpress.com/2015/10/18/saab-gripen-royal-thai-air-force/
https://twitter.com/Saab/status/1412801870964342795/photo/1

Sipri Lines
(40)	IRIS-T	BVRAAM	2010	2012-2013	(40)	For JAS-39 combat aircraft
(25)	RBS-15M	Anti-ship missile	2010	2012-2013	(25)	RBS-15F version; for JAS-39 combat aircraft
(50)	AIM-120C AMRAAM	BVRAAM	2014	2016-2017	(50)	For JAS-39C combat aircraft

**Comment by PygmalionOfCyprus** [comment]
Added 494.
