### ISSUE TITLE
Brazil - SABER M200 Radar

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#961]
### DB Selector

DB3K

### Baseline

n/a Probable ELM-2288 AD-STAR

### Hypothetical

Yes

### Name

Radar (Saber M200) 

### Sensor Generation

Late 2010s

### Sensor Capabilities

Air Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Non-Cooperative Target Recognition (NCTR) - Jet Engine Modulation [Class Info], Continuous Tracking Capability, Passive Electronically Scanned Array (PESA)

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm

### Comments

SABER M200 PESA Radar 200NM Range

SABER - M200
Multi-mission air defense radar

Primary Radar:
Technical specifications:
4 fixed panels with electronic beam in the S band;
Peak power: up to 115kW per panel;
Digital AESA technology with pulse noise;
Height coverage: 0 – 20 km;
Maximum opening in elevation: 70°;
MIL STD 810G and 461F;
Range (targets with a radar cross section of 2 m2):
250 NM (nautical miles) in Surveillance, Route and ISAR mode;
100 NM (nautical miles) in Defense mode with 1s refresh;
170 NM (nautical miles) in weather mode.

Secondary Radar:
Technical specifications:
Operation in Modes: 1, 2, 3/A, C, S and 4;
MIL STD 810G and 461F;
STANAG 4193 and annex 10 vol. IV of the ICAO;
Range:
110 NM (nautical miles) for 2m compact antenna;
200 NM (nautical miles) for 8.5m long antenna.

Technical Characteristics Expected for Radar P200
Maximum range: 200km
Maximum ceiling: 15km
Vertical beam opening angle: 0-70º
Minimum target refresh time: 1s
Target separation capability: 20m
Maximum number of targets for tracking: 200

Program is approved, one functioning SABER M200, and SABER S200.

Underwent sucessful trials and testing. 

### Sources

https://www.brasilemdefesa.com/2018/05/saber-m200.html

https://www.radartutorial.eu/19.kartei/02.surv/karte081.pt.html

https://www.defesaaereanaval.com.br/defesa/bradar-e-ctex-testam-com-sucesso-radar-saber-m200

https://www.eb.mil.br/web/noticias/noticiario-do-exercito/-/asset_publisher/znUQcGfQ6N3x/content/id/14728435

https://www.defesanet.com.br/at/noticia/42990/EMBRAER-e-Exercito-Brasileiro-apresentam-o-radar-nacional-SABER-M200-VIGILANTE-de-alerta-aereo-antecipado/

http://www.ctex.eb.mil.br/projetos-em-andamento/82-radar-saber-m200

https://www.infodefensa.com/texto-diario/mostrar/3131628/brasil-aprova-um-investimento-142-milhes-dolares-saber-m200

**Comment by Jkryos** [comment]
Added DB3K 496.
