### ISSUE TITLE
Generic M577 and M577A3 Command Post Carrier

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#964]
### DB Selector

Both

### Hypothetical

No

### Name

M577 and M577A3 Command Post Carrier (M113)

### Facility Type

Mech

### Country

Generic, Canada, United States

### Service

Army 

### In Commission

1963-

### Crew

5

### Sensors

- front and side are four M17 day periscopes with an AN/VVS-2 image intensifier or AN/VAS-5 thermal viewer being provided in the roof

### Mounts

- None

### Comments

Command variant, the roof over the rear troop compartment is higher. The vehicle also carries additional radios and a generator. 

A variant of this is the M1068 standard integrated command post system carrier, equipped with the newest U.S. Army automated command and control system. Upgrades included mounting/stowage positions for the Army Tactical Command and Control Systems (ATCCS) hardware, which has two workstations. A 10 m telescoping antenna mast and a type M13 NBC system, with a ventilated facepiece for each crew member

### Sources

https://en.wikipedia.org/wiki/M113_armored_personnel_carrier#Basic_variants
http://www.army-guide.com/eng/product3249.html

M577
![60f1cc2a7cad97ecb460e2b7_M577A3-Command-Post---Edmonton--Anthony-Sewards](https://user-images.githubusercontent.com/99632305/164785852-218b4e1c-2e4d-49fe-925b-e2a01a8d0c76.jpg)
M577A3
![1d241e2b829f9029476339028e65e6cd](https://user-images.githubusercontent.com/99632305/164785718-c70344d7-3780-4fb6-b4d3-b6b68da9ce8f.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494. Will be added to CWDB with mass ground units copy-over.
