### ISSUE TITLE
CA M113A3 APCLE Troop Carrier/Cargo x4, 1990 x289

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#965]
### DB Selector

DB3K

### DBID to Copy

2009 DB3k

### Hypothetical

No

### Name

M113A3 APCLE (Troop Carrier/Cargo)

### Country

Canada

### Service

Canadian Army

### In Commission

1990-

### Sensors

- Same

### Mounts

- Same

### Other Changes

Straight copy

### Sources

https://en.wikipedia.org/wiki/List_of_equipment_of_the_Canadian_Army
https://military-history.fandom.com/wiki/Variants_of_the_M113_armored_personnel_carrier#Canada

![de6b3d10-6300-40bc-bfa7-3ae2a7dcb5f7](https://user-images.githubusercontent.com/99632305/164785550-1da82089-c6d0-48e9-8b95-4b17979fee91.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
