### ISSUE TITLE
CA Lynx Command and Reconnaissance Vehicle x174

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#966]
### DB Selector

Both

### Hypothetical

No

### Name

Lynx C&R Vehicle

### Facility Type

Mech

### Country

Canada

### Service

Canadian Army

### In Commission

1968-1993

### Crew

3

### Sensors

- Binoculars
- Mk1 Eyeball

### Mounts

- M2 Heavy Machine Gun (fwd)
- 7.62mm machine Gun (pintle-mounted

### Magazines

- .50 cal
- 7.62mm

### Comments

- Other operators of variants: Bahrain, Chile, Iran, Netherlands
- Amphibious

### Sources

https://tanks-encyclopedia.com/coldwar/canada/m113_lynx.php
https://en.wikipedia.org/wiki/Lynx_reconnaissance_vehicle#:~:text=M113%20C%26R)%20is%20a%20United,of%20the%20Netherlands%20and%20Canada.
http://afvdb.50megs.com/usa/acrc.html

![ca_acarv_m113_1-2_lynx-001-e1470068014885](https://user-images.githubusercontent.com/99632305/164787811-e7e67c01-f11c-4c04-b0c0-a6a3d8e9d820.jpg)
![ff9fc4295dec00bbb8c568f8acd188d6](https://user-images.githubusercontent.com/99632305/164788245-fb8923cf-0ac4-49eb-9c98-1756fa21ae25.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
