### ISSUE TITLE
CA M113A2 TUA (TOW Under Armour)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#967]
### DB Selector

DB3K

### DBID to Copy

3171DB3k

### Hypothetical

No

### Name

CA M113A2 TUA

### Country

Canada

### Service

Canadian Army

### In Commission

1990-

### Sensors

Same

### Mounts

Same

### Loadout Options

Same

### Other Changes

Canadian version of the NM142 anti-tank vehicle on a M113A2 chassis. Very similar to the Norwegian version, but with external fuel tanks.

### Sources

https://en.wikipedia.org/wiki/Variants_of_the_M113_armored_personnel_carrier#Canada

![318168c0fb45db8bcbb03a9888404c67f152d8d3](https://user-images.githubusercontent.com/99632305/164790535-ed9171d6-faba-4b04-96e9-5751a1bf3e9e.jpg)
![images](https://user-images.githubusercontent.com/99632305/164790600-a1118732-cbc4-4972-9d17-6d8cce01ef47.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
