### ISSUE TITLE
CA M113A3 TLAV-TUR (Mobile Tactical Vehicle Light) x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#968]
### DB Selector

DB3K

### DBID to Copy

2009 DB3k

### Hypothetical

No

### Name

M113A3 TLAV-TUR x4

### Country

Canada

### Service

Canadian Army

### In Commission

2001-

### Sensors

Same

### Mounts

-1x Cadillac-Gage 1 metre turret taken from a AVGP Grizzly, armed with a M2HB .50cal machine gun and a C6 GPMG 7.62mm

### Loadout Options

- .50cal
- 7.62mm

### Other Changes

341 Canadian M113A2 series vehicles will be refurbished: 183 will be the stretched MTVL version (6 road wheels) and the remaining 158 will be vehicles upgraded to the M113A3 (retaining 5 road wheels). Modifications include more powerful engines, upgraded suspension, bolt-on steel armour plates and/or steel cage armour, and improved armament.

### Sources

https://en.wikipedia.org/wiki/Cadillac-Gage_1_metre_turret
https://en.wikipedia.org/wiki/AVGP

![M113 A3 jpg e9ba2253](https://user-images.githubusercontent.com/99632305/164793084-64488fdd-8ea8-4565-9385-a42c5d5b84fe.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
