### ISSUE TITLE
CA M113A3 TLAV-RWS (Mobile Tactical Vehicle Light) x4

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#969]
### DB Selector

DB3K

### DBID to Copy

2009 DB3k

### Hypothetical

No

### Name

M113A3 MTVL-RWS x4

### Country

Canada

### Service

Canadian Army

### In Commission

2001- 

### Sensors

- Day camera
- Thermal Imaging Camera

### Mounts

- 7.62mm MG with 220 round ammunition box (C6)

### Other Changes

M113A3 RWS – Otherwise known as the LAV-T RWS (Light Armoured Vehicle - Tracked) or M113 TLAV RWS is a APC version of the M113A3 standard, equipped with either a [Nanuk Remotely Controlled Weapon Station](https://en.wikipedia.org/wiki/Nanuk_Remotely_Controlled_Weapon_Station) (Remote Weapon Station) system. When armed with the [Nanuk Remotely Controlled Weapon Station](https://en.wikipedia.org/wiki/Nanuk_Remotely_Controlled_Weapon_Station) it mounts a [C6 GPMG](https://en.wikipedia.org/wiki/FN_MAG) with a 220 round ammunition box. Using either the day camera or thermal imaging camera, an LCD screen and joystick, the crew commander can engage targets from the protection of the vehicle without exposure. A total of 40 of the variant were produced.

### Sources

http://kingsown.ca/regiment/vehicles/
https://en.wikipedia.org/wiki/Nanuk_Remotely_Controlled_Weapon_Station

![9d75bcf525badf3a7130ef8598282f03--military-vehicles-track](https://user-images.githubusercontent.com/99632305/164794289-21cc0af5-1795-47e1-a432-b003a5a4b416.jpg)
![a611cc5246efe2c5012d40d6e83e5e87--military-post-military-man](https://user-images.githubusercontent.com/99632305/164794353-8ae9a19f-2d25-46fa-b0b5-0acbc345e6bf.jpg)
![IMG_8569](https://user-images.githubusercontent.com/99632305/164795120-016aaa35-6c75-48ed-83d9-65ded37f29b1.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
