### ISSUE TITLE
RAAF AIM-120D Loadouts for F/A-18Fs, E/A-18Gs and F-35As

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#97]
### DB Selector

DB3K

### User(s)

RAAF

### Weapons Carried

Add additional loadouts replicating RAAF F/A-18Fs, E/A-18Gs and F-35As containing AIM-120C-7s, but replacing them with AIM-120Ds

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

thediplomat.com/2016/04/australia-to-buy-450-advanced-us-made-air-to-air-missiles/

**Comment by PygmalionOfCyprus** [comment]
Added 494.
