### ISSUE TITLE
CA M113A1 RCL (Recoilless Rifle Carrier)

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#970]
### DB Selector

CWDB + DB3K

### DBID to Copy

2006 DB3K

### Hypothetical

No

### Name

M113A1 RCL

### Country

Canada

### Service

Canadian Army

### In Commission

1963-

### Sensors

Same

### Mounts

- 1x 106mm recoilless rifle (couldn't find a 106 in DB)
- 7.62mm MG 

### Loadout Options

- 7.62mm
- 106mm

### Sources

https://www.silverhawkauthor.com/post/armour-in-canadian-service-m113-armoured-personnel-carrier-apc
https://en.wikipedia.org/wiki/Variants_of_the_M113_armored_personnel_carrier#Canada
https://en.wikipedia.org/wiki/M113_armored_personnel_carrier

![60f1c775d6dfe944ff0a3014_106-mm-M40A1-Recoilless-Rifle-mounted-on-an-M113--Ex-Reforger-74--3-Mech-Cdo--Oct-1974---MIKAN-No--4631327](https://user-images.githubusercontent.com/99632305/164799716-6539248a-f294-4c73-adfe-83940d31ff0f.jpg)
![60f1c776de0b146b73e180e6_M113--R22eR--106-mm-recoiless-rifle--Ex-Certain-Trek--S-of-Wurzberg--20-Oct-1975---MIKAN-No--4692424](https://user-images.githubusercontent.com/99632305/164799731-66f40030-52c8-4237-810e-3944de1695d4.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
