### ISSUE TITLE
Serbia - Pantsir-S2E doesn't launch/ can't guide missiles

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#971]
### DB Selector

DB3K

### Affected DBID(s)

3432

### Description of Problem

The SAM Plt (SA-22 Greyhound [Pantsir-S2E]) doesn't launch missiles at aircraft or missiles. The message "No weapons directors available to illuminate the target" shows up during weapons allocation. This was tested against aerial targets at different heights, distances and with different rcs, where other SA-22 versions fire their missiles.

Also not a bug: the Pantsir-S2E lacks the "Hot Shot [RLM SOC] Acquisition" radar which all other SA-22s have. Without it, it only detects aerial targets with the Generic IR Camera as shown in the unit message log.

### Recommended Fix

SA-22 Greyhound [57E6] weapons entry lacks the "Can be guided by: ..." part which is present in the weapons entry of all other SA-22s. "Can be guided by: SOT-S [1RS1-3E-RLM]" should be added.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. Also tweaked FCR role so hopefully it uses it for search as well as tracking.
