### ISSUE TITLE
Pantsir-SM can't launch missiles, launch alt 20ft AGL

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#972]
### DB Selector

DB3K

### Affected DBID(s)

3693

### Description of Problem

The SA-22 Greyhound ER [57E6] missile can't be launched by the Pantsir-SM since the missile has a launch altitude of 20ft AGL - .... in the DB entry. I've tested this by adding the missile and required sensor to a helicopter, it works... for helos.

### Recommended Fix

Change SA-22 Greyhound ER [57E6] entry to: Launch Altitude: -

**Comment by PygmalionOfCyprus** [comment]
Fix w/ #971

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
