### ISSUE TITLE
J-10C & J-10CE have incorrect PL-15 datalink channels

### ISSUE THREAD

**Issue by ywturbo** [PygmalionOfCyprus/cmo-db-requests#973]
### DB Selector

DB3K

### Affected DBID(s)

5259,5521

### Summary of Changes

Correct PL-15 Missile Datalink channels from 1 to 12 for #5259 J-10C & #5521 J-10CE.

### Sources

#2057 J-10C has the correct PL-15 command datalink of 12, so the same variants #5259 & #5521 shall be the same.

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
