### ISSUE TITLE
CA Nyala RG-31 Light Armoured Vehicle

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#977]
### DB Selector

DB3K

### Hypothetical

No

### Name

RG-31 Nyala x4

### Facility Type

Mech

### Country

Canada

### Service

Canadian Army

### In Commission

2006-

### Crew

2+10

### Sensors

- Mk1 Eyeball
- Binoculars
- Day and night vision cameras
-

### Mounts

- Kongsberg Protector RWS; M151 7.62mm remote-controlled machine gun and 40mm HMG grenade launcher

### Magazines

For above

### Comments

VBP also provides protection against small arms, hand grenades and anti-tank mines

### Sources

https://www.armyrecognition.com/canada_canadian_army_wheeled_armoured_vehicle_fr/rg-31_nyala_vbl_patrol_wheeled_armoured_vehicle_canada_canadian_army_pictures_technical_data_sheet_d.html
https://defense-update.com/20070704_rg-31.html
https://army.ca/wiki/index.php?title=RG-31_Nyala_Armoured_Patrol_Vehicle

![AR2006-H030-0015a](https://user-images.githubusercontent.com/99632305/164872828-8a5f8ffd-d90c-4664-816c-c0869e655693.jpg)
![600px-Nyala2](https://user-images.githubusercontent.com/99632305/164872831-8b31ef21-eb42-4765-8cba-7f0ac15f8801.jpg)
![image_](https://user-images.githubusercontent.com/99632305/164872841-fc45c8c6-79c4-4e56-9810-2f7b3dd9ecc5.jpg)

**Comment by Jkryos** [comment]
Added DB3K 494.
