### ISSUE TITLE
Can we add #2597 - HYDRA APKWS II 70mm Rocket [WGU-59/B, Rotary Wing Launch] loadouts to  AH-64E Apache Guardian

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#978]
### DB Selector

DB3K

### User(s)

#441, #246, - AH-64D Apache Longbow. #2419, #4793, #5280 - AH-64E Apache Guardian

### Weapons Carried

- Create same as existing HYDRA 70mm Rocket Loadouts but with HYDRA APKWS. [1]

Loadouts: #15214, #15215, #15216, #15217, #15218, #15219, #15223, #15224, #15227, #26113, #26114, #26116, #26117, #26118, #15228, #15229, #29453, #29454, #29456, #29458.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As Existing

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The source [1] provided has the PDF'S; BAE Systems APKWS brochures for both the rotary launched and fixed wing versions of the missile if you want to see if they still match up. From what i can tell some slight tweaks may be necessary. It also has a fairly complete list of aircraft that are Qualified platforms, those on Demonstrated platforms and Potential platforms.

### Qualified Platforms

1. **Rotary-wing**

- • AH-64D/E Apache
- • AH-1W/Z Super Cobra/Viper
- • UH-1Y Venom
- • MH-60S/R Knight Hawk/Seahawk
- • UH-60L/M Black Hawk
- • IA-407 Bell
- • ARH Tiger
- • OH-58 Kiowa Warrior
- • AH-6M Little Bird

2. **Fixed-wing**

- • F-16 Fighting Falcon
- • A-10 Thunderbolt
- • AV-8B Harrier
- • OV-10 Bronco

### Demonstrated Platforms

1. **Rotary-wing**

- • V-22 Osprey
- • Bell 407GT
- • Boeing AH-6i
- • MQ-8B Fire Scout

2. **Fixed-wing**

- • AT-6 Texan
- • Textron Scorpion

### Potential Platforms

1. **Rotary-wing**

- • AH-1F Cobra
- • MD 530G Light Scout
- • AW109 Power
- • AW139
- • Airbus H135
- • Airbus H145

2. **Fixed-wing**

- • F-18 Hornet
- • Eurofighter Typhoon
- • Hawk
- • A-29 Super Tucano
- • AT-802L Air Tractor
- • C-208 Combat Caravan
- • CASA 235 Gunship

It would also be nice if you could choose which warhead were loaded into the pods, there are currently nine types available. [3] 

Theses are as follows:

"_The nine warheads used with Hydra-70 include the M264 smoke, M255A1 flechette, M257/M278 illuminating flare, M278 infrared flare, M151 high explosive (10lb), M229 high explosive (17lb), M156 (WP), WTU-1/B (practice) and M274 (practice) smoke signature. M264 smoke warhead is filled with red phosphorus and used for smoke obscuration. It is 26.9in-long and weighs 8.6lb.

The M255A1 Flechette contains 1,179 60-grain hardened steel flechettes. It is used against light material and personnel targets. Upon firing, the flechettes contained in the warhead form a disk-like mass, with each flechette taking an independent trajectory. The warhead is 26.9in long and weighs 14lb.

The M257/M278 illuminating flare is used for battlefield target illumination and includes an ignition system, flare, parachute, drogue parachute assembly, fuse and delay assembly. The warhead can illuminate an area of 1km². It is 29.1in long and weighs 11lb.

The M278 infrared flare is also used for battlefield illumination with infrared goggles. It can provide infrared light for three minutes. The warhead is 29.1in long and weighs 11lb.

The M151 high explosive is an anti-personnel warhead, which breaks into thousands of high velocity fragments upon detonation. It is 16.2in long and weighs 9.3lb. M229 high explosive is a heavier variant of the M151. It is 26in long and weighs 17lb. M156 (WP) is a smoke warhead filled with white phosphorus. It is 16.2in long and weighs 9.65lb.

The WTU-1/B is a 16.2in long fused warhead and weighs 9.3lb. M274 is identical to the M151 and is used to provide training with a smoke signature. It is 16.2in long and weighs 9.3lb._" [3]

**Extended range of the missiles** 

"BAE Systems said in a statement._“The maximum publicly stated range is 5+ km for APKWS rockets fired from rotary-wing platforms and 12+ km for APKWS rockets fired from fixed-wing platforms,” APKWS programme manager Samantha Kirsh told Janes. “The Block Upgrade guidance kit extends the range by up to 30% via an improved flight trajectory,”_ " [2], [4]

**Increased Surface PoH, Land PoH / Reliability**

"_In combat, our APKWS system has achieved over a 93 percent hit rate when fired from rotary- and fixed-wing platforms. In fact, it is the most accurate precision guided weapon in its class, exceeding program requirements. That is just part of why the APKWS is utilized by all four branches of the U.S. armed forces, as well as numerous allied countries._" [1]

### #2597 - HYDRA APKWS II 70mm Rocket [WGU-59/B, Rotary Wing Launch]

- Decrease Launch Speed 0 - 150 Knots True Airspeed (KTAS).
- Increase CEP, Surface, CEP, Land (nominal) 2m.
- Launch height above target 0 to 3000 ft.
- Launch Altitude 200 to 25,000 ft MSL  (Mean Sea Level).

### #3540 - HYDRA APKWS II 70mm Rocket [WGU-59/B, Fixed Wing Launch]

- Increase CEP, Surface, CEP, Land (nominal) 2m.
- Launch height above target 0 to 15,000 ft.
- Launch Altitude 200 to 25,000 ft MSL  (Mean Sea Level).

### Sources

[1]   https://www.baesystems.com/en-uk/product/apkws
[2]   https://www.janes.com/defence-news/news-detail/bae-systems-enhances-apkws-ii-range-by-30
[3]   https://www.army-technology.com/projects/hydra-70-rocket-system-us/
[4]   https://www.flightglobal.com/helicopters/bae-systems-stretches-apkws-range-30-using-new-trajectory/144907.article

**Comment by PygmalionOfCyprus** [comment]
Added to the 2013- US Apaches. Extended-range Blk III version will have to get modelled at some point as a different weapon but that's gonna be a huge can of worms, so...later. Made the other tweaks.
