### ISSUE TITLE
Increase #2684 Lewis Puller's aircraft capacity to 4 large aircraft

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#979]
### DB Selector

DB3K

### Affected DBID(s)

Ship #2684

### Summary of Changes

Need pads and storage for 4 Large aircraft.

### Sources

![Miguel-Keith-1](https://user-images.githubusercontent.com/7115648/164909939-41c8e981-3425-43e8-a6bc-14be3b5afd18.jpg)
https://militaryleak.com/2020/04/28/u-s-army-rotary-wing-conduct-deck-landings-in-arabian-gulf/
https://www.surfpac.navy.mil/Media/News/Article/2919641/commander-task-force-seventy-six-ctf-76-embarks-uss-miguel-keith-to-command-and/

**Comment by PygmalionOfCyprus** [comment]
Have they officially expanded to using all four pads for flight ops?

At least a couple of years ago, despite having four "pads," two of those were actually more like "Open Parking." See [this USNI article](https://news.usni.org/2015/11/02/expeditionary-mobile-base-chesty-puller-may-receive-sof-upgrades-before-5th-fleet-deployment):

>Currently, the deck is designed with two parking spots and two operating spots – along with space for two helos inside the hangar – but he said the Navy could decide to convert all four spots to operational spots if needed. The front of the flight deck leads into the hangar [...]

This _could_ also explain the specific opening to that MilitaryLeak article (emphasis mine):

>The repetitive whoosh of helicopter blades is heard as **two** AH-64E Apache attack helicopters land on board the deck of the Navy Expeditionary Landing Base ship USS Lewis B. Puller [...]

Either way, that capability wasn't reflected in the DB, so I've added two large Open Parking spots: the ship can now hold 4x Large Aircraft (two on the deck, two in the hangar) but only takeoff/land two at a time.

If I missed something in your sources or you have info that indicates they are now using the whole deck for flight ops, I can come back and twiddle with it.
