### ISSUE TITLE
Add land-based TC-2

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#98]
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Plt (TC-2)

### Facility Type

SAM

### Country

Taiwan

### Service

Army

### In Commission

2022

### Dispersion Radius (m)

40

### Sensors

1x CS/MPQ-90 Bee Eye

### Mounts

2x or 4x TC-2 quad launcher

### Magazines

24x TC-2

### Comments

the missile used is the TC-2 missile that were used on the F-CK-1 aircraft, so the missile is most probably is the one without naval booster like the one on TC-2N naval version. So it will have significantly less range than TC-2N. Each missile launcher can carry up to 4 missiles max. The system also included at minimum 2x 40mm Bofors that were equipped with some sort of EO system.

### Sources

https://www.shephardmedia.com/news/landwarfareintl/ground-based-tc-2-will-soon-enter-taiwanese-servic/
https://www.globalsecurity.org/military/world/taiwan/tc-2-shorad.htm
https://www.armyrecognition.com/idex_2019_news_official_online_show_daily_partner/idex_2019_land-based_tc-2_air_defense_missile_system_by_ncsist.html
![image](https://user-images.githubusercontent.com/99646926/153852375-53c60697-1c78-47d0-8552-d9e8b93ea4a1.png)

**Comment by bostonmyk** [comment]
More on Bee Eye radar including some stats.

https://twitter.com/stoa1984/status/1617999919071264768?cxt=HHwWgIDU7dKWpfQsAAAA

**Comment by Jkryos** [comment]
Added DB3K 505.
