### ISSUE TITLE
M-87 Orkan MLRS correction - Yugoslavia

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#980]
### DB Selector

DB3K

### Affected DBID(s)

3207

### Summary of Changes

The M-87 Orkan MLRS which was designed by the Military Technical Institute of Yugoslavia in 1987 has **12 launch tubes instead of 4** for M-87 262mm rockets. This is the original version of this MLRS. The version with 4 launch tubes (only operated by Serbia after 1995) is a makeshift civil war version with 4 launch tubes strapped on a Luna-M launcher. Except for the rockets it has nothing in common with the original M-87 Orkan.

The M-87 rocket has a **range of 50km, not 50nm**. It also has air brakes which allow for a minimum firing distance of 5km. The range should change to this: **Range (anti-surf): 3 - 27nm. All rocket versions have the same range.** There are two cluster munition warhead options: **288x KB-1 0.25kg DPICM Dual Purpose (main rocket used by Orkan)** and **24x KPOM Anti-Tank mines**. In 1990 **HE warheads were planed  for development in the future**. 

I don't know why the M26 and M26A1 rockets of the MLRS are guided weapons (inertial). If the reason for them beeing guided weapons is the ballistic computer of the M270 MLRS itself, then **M-87 Orkan should have the guided weapon (inertial) type aswell**: The M-87 Orkan was a quite sophisticated MLRS with a relatively high degree of automation for it's time. Like the US M270 MLRS it has a digital ballistic computer. A ccd sensor camera (visible and near ir spectrum) is mounted on the top left side of the launcher. This camera meassures the deviation of the first 3 missiles in a salvo from the calculated flightpath and then adjusts the flightpath of the remaining rockets by adjusting the elevation and azimuth of the launcher. The adjusted firing solution is then sent by a datalink to the other Orkan launchers in the battery. The fuzes and air brakes can be individually, electronically adjusted from the cabin while the rockets are in the launch tubes.

### Sources

General information in Serbian:
https://web.archive.org/web/20001006103508/http://www.geocities.com/Pentagon/7178/orkan.htm

M-87 Orkan with 12 launch tubes and Bosch camera system on the left side of the launcher:
https://imgur.com/Eej7HQR
https://www.youtube.com/watch?v=rsPWPDz24Qs
https://www.youtube.com/watch?v=EWQgOB8e9Eg&t=5s

M-87 rocket:
https://cat-uxo.com/explosive-hazards/rockets/262mm-m87-orkan-rocket
https://cat-uxo.com/explosive-hazards/submunitions/kb-1-submunition
https://www.lexpev.nl/minesandcharges/sovietbalkan/yugoslavia/kb1.html
https://cat-uxo.com/explosive-hazards/submunitions/kpom-submunition
https://www.lexpev.nl/minesandcharges/sovietbalkan/yugoslavia/ababel.html

Pictures of DPICM, mine and HE warheads:
https://imgur.com/QbCydfc
https://imgur.com/qC6o96q

Orkan reloading crane:
https://imgur.com/nzOMtid

Organisation of an M-87 Orkan battery and battalion:
https://imgur.com/QDjL3Sc

The ballistic computer of the Orkan launcher itself can be seen here (0:30) and in the following pictures:
https://youtu.be/PC4qoF6RWak?t=30
https://imgur.com/EkcJOoB
https://imgur.com/c6q6yyD

The artillery computer of the Orkan battery command vehicle can be seen here (13:52) and in the following picture:
https://youtu.be/eLvXYvgpqDA?t=832
https://imgur.com/qz8ZAHf

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.

As for the guided weapon discrepancies, we're actually discussing that internally right now. IIRC it was initially a sort of hacky workaround to allow interception of MLRS projectiles, but it was an imperfect solution even back then. We're going to talk about how best to proceed in order to allow systems like Iron Dome, etc. to do their jobs...ideally without calling everything ballistic a "guided weapon."

Anyway, don't worry too much about that for now. We'll revisit it soon enough and standardize everything once we're clear about the direction we want to go.
