### ISSUE TITLE
Sensors of SH-60F Oceanhawk

### ISSUE THREAD

**Issue by eclair16543** [PygmalionOfCyprus/cmo-db-requests#981]
### DB Selector

DB3K

### Affected DBID(s)

#2347, #698, and #1136

### Summary of Changes

SH-60F Oceanhawk is "CV-Helo" which uses AN/AQS-13F Dipping sonar for search, and unlike DD/FF-based LAMPS III/SH-60B, they should NOT have AN/APS-124 Radar, AN/ASQ-81(V)4 MAD (and possibly, even ESM and some of Sonobuoys) instead.

### Sources

"…The AQS-13F active dipping sonar shown here replaced the SH-60B MAD and search radar. A gravity launcher holding six sonobouys replaced the pneumatic system. The SH-60B RAST system was also deleted as the SH-60F was intended to operate from carrier decks instead of from small vessels."
https://www.sikorskyarchives.com/S-70B%20(SH-60B%20Seahawk,%20SH-60F%20CV,%20HH-60H%20Rescue%20Hawk,%20HH-60J%20Jayhawk,%20VH-60N).php

"The US Navy acquired another version of the S-70B for close-in carrier group antisubmarine warfare, with this variant designated the "SH-60F Ocean Hawk". The Ocean Hawk deleted the RAST gear, which wasn't required since the SH-60F operated off carrier decks, and replaced the LAMPS III suite with a much less elaborate offensive avionics suite, centered around a Bendix AN/AQS-13F dipping sonar. Radar, ESM, and the datalink were deleted. The sonobuoy array was deleted, but there was a sonobuoy tube in the floor of the cabin, and a rack was included for of eight sonobuoys that could be dropped manually through the tube."
http://www.airvectors.net/avs70_2.html

"…They would be equipped with a new lightweight dipping sonar and some avionics improvements over the earlier B model Seahawks. These improvements came at a price, however: the loss of most of the LAMPS equipment, including the sonobuoy launchers and data links."
https://books.google.co.jp/books?id=kM8RUfGqYU0C&pg=PT258&lpg=PT258&dq=SH-60F+Tom+clancy+carriers&source=bl&ots=ANXe0TM9aS&sig=ACfU3U0f8LG9XdJgOFc0MKIsPga8tJnKfA&hl=ja&sa=X&ved=2ahUKEwjBwpLgwKz3AhXkKqYKHdWQCNIQ6AF6BAgcEAM#v=onepage&q=SH-60F%20Tom%20clancy%20carriers&f=false

This is Wikimedia Commons link to SH-60F/SH-60B photos, and you will notice that SH-60F does not have Radar dome (under the cockpit) nor MAD boom (rear of starboard) which SH-60B have.
https://commons.wikimedia.org/wiki/Category:SH-60F_Seahawk
https://commons.wikimedia.org/wiki/Category:SH-60B_Seahawk

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494. (Also adjusted the Israeli version.) In addition to paring down their sonobuoy loads and raising ROF to reflect the hand-loading, I've also given them a third torpedo when not carrying external fuel to reflect the lengthened left pylon.
