### ISSUE TITLE
Ericsson SLAR (side looking airborne radar)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#983]
### DB Selector

DB3K

### Baseline

6234

### Hypothetical

No

### Name

Ericsson SLAR

### Sensor Generation

Late 1970s

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Range Information, Speed Information, Heading Information

### Search/Track Frequencies

I Band (8-10 GHz) [Old X Band] 3-3.75 cm

### Lower Frequency (Hz)

9,300,000,000

### Upper Frequency (Hz)

9,400,000,000

### Scan Interval (s)

5

### Horizontal Beamwidth (deg)

0.52

### Vertical Beamwidth (deg)

33.00

### System Noise Level (dB)

8

### Processing Gain/Loss (dB)

31 dBi

### Peak Power (W)

10000

### Pulse Width (ms)

0.0005

### PRF (Hz)

1000

### Comments

The swath width/range of the Ericsson SLAR is stated by most sources as 80km (either 80km to one side of the aircraft or 40km to each side of the aircraft which is chosen by the operator). A range of 100km is stated by one a Korean source. A range of 80km should be considered for this sensor in the DB since a maritime patrol aircraft searching for enemy ships would radiate the radar energy in one direction to maximise the swath width towards the sea.

The Yugoslav twinseater INJ-22M Orao and NJ-21M Jastreb maritime patrol aircraft are equipped with the Ericsson SLAR. I'm going to make a seperate request for both aircraft.

### Sources

https://www.google.com/books/edition/Observation_of_the_Earth_and_Its_Environ/Xpr6CAAAQBAJ?hl=de&gbpv=1&dq=Survey+of+Airborne+Sensors+Herbert+J.+Kramer+ericsson&pg=PA603&printsec=frontcover

in case the link doesn't work:
https://imgur.com/bIlG4MM

https://books.google.com/books?id=ix-VmRkrQHAC&pg=PA309&lpg=PA309&dq=swedish+space+corporation+slar+radar&source=bl&ots=4KzZyl6dy4&sig=ACfU3U1vJwdQFZFs95OnXsh4z6Ngm7d9YQ&hl=de&sa=X&ved=2ahUKEwjD1_6pqK33AhVNQ_EDHfD-DXUQ6AF6BAgdEAM#v=onepage&q=swedish%20space%20corporation%20slar%20radar&f=false

Ericsson SLAR use over land:
https://imgur.com/pa6FFHZ

https://fdocuments.in/document/location-of-the-rhine-plume-front-by-airborne-remote-sensing.html?page=2

https://www.kafi.net/airforce/arms_3_8.htm

https://imgur.com/TXaPXL9

**Comment by PygmalionOfCyprus** [comment]
Added 494. There are few things more satisfying than a sensor entry for which all the data is filled out and supported by sources... 🥲
