### ISSUE TITLE
ELT-400 series update (ELT-457,458,459,460)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#985]
### DB Selector

DB3K

### Affected DBID(s)

904, 903, 902, 901

### Summary of Changes

add "(noise jammer)" to name
category: OECM
Role: OECM, Offensive ECM
Abilities: (Early 70s Technology)
Operating Bands: G, H, I, J, K, L
Scan Interval: 1 

In the Electronic Warfare Directory (1990), the ELT-400 Series of Jammers (ELT-457, ELT-458, ELT-459, ELT-460) are discribed as "podded , power-managed, radar noise jammers which operate in the G-L frequency bands." This would make them OECM pods since the Aries A is also described as a noise jammer.

### Sources

ELT-400 series:
https://www.mycity-military.com/imgs4/476830_54689796_79915967-EW-Directory-1990-005.jpg
"the G-to L-band ELT/400 series of pod-mounted, noise jammers":
https://www.thefreelibrary.com/NATO+EW+-+at+the+turning+point.-a09323281
http://stage.militaryperiscope.com/weapons/sensorselectronics/electronic-support-measureselectronic-warfare/elt457
German source (70 tech):
http://www.whq-forum.de/invisionboard/index.php?showtopic=25603

**Comment by PygmalionOfCyprus** [comment]
Fixed for 495.
