### ISSUE TITLE
An-22 Cock, the... well, the update.

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#986]
### DB Selector

DB3K

### Affected DBID(s)

*

### Summary of Changes

> From a post by the acclaimed author and scenarist Bart Gauvin about this platforms' description[^1], I've examined the corresponding entries in the DB, and I believe that the values could be modified as suggested below.

ID | Name
---|---
2509 | An-22 Cock (Soviet Union [-1991] - 1970)
2510 | An-22 Cock (Russia [1992-] - 1992)
2511 | An-22A Cock (Russia [1992-] - 1992)
2512 | An-22A Cock (Soviet Union [-1991] - 1968)

**UPDATE DataAircraft**[^2][^3][^6][^7]
```
SET DataAircraft.Comments = 38x
WHERE DataAircraft.ID IN (2509, 2510);
```
```
SET DataAircraft.YearCommissioned = 1969
WHERE DataAircraft.ID=2509;
```
```
SET DataAircraft.YearCommissioned = 1973
WHERE DataAircraft.ID=2511;
```
```
SET DataAircraft.Comments = 28x
WHERE DataAircraft.ID IN (2511, 2512);
```
```
SET DataAircraft.WeightEmpty = 118727,  DataAircraft.WeightMax = 225000,  DataAircraft.WeightPayload = 60000, DataAircraft.Crew = 7
WHERE DataAircraft.ID IN (2509, 2510, 2511, 2512);
```
<kbd>250 tons max weight comes from a 1966 project, confusingly also named An-22A that didn't get through.</kbd>
<kbd>Take-off/Landing Distance is borderline 2004, the figures I have are 1460/1040 m. Your call.</kbd>
---

**UPDATE DataAircraftFuel**[^2][^3]
```
SET DataAircraftFuel.ComponentID = 15
WHERE DataAircraftFuel.ID IN (2509, 2510, 2511, 2512);
```
<kbd>DataFuel.ID 15 is made of Aviation Fuel x 96000</kbd>
---

**UPDATE DataLoadout**[^2][^3] (and COPY)
```
SET DataLoadout.ID='Cargo, 60 tons', DataLoadout.Cargo_Mass=60.0, DataLoadout.Cargo_Area=147.0
WHERE DataLoadout.ID=9864;
```
<kbd>Cargo hold is 33.4 x 4.4 m large, ramp included</kbd>
```
SET DataLoadout.ID='Cargo, 20 tons, Air Drop', DataLoadout.Cargo_Mass=20.0, DataLoadout.Cargo_Area=147.0
WHERE DataLoadout.ID=9865;
```
<kbd>20 tons is the weight limit for dropped cargo. Same as for the An-124 by the way.</kbd>
```
SET DataLoadout.DefaultCombatRadius=5130
WHERE DataLoadout.ID=9862;
```
<kbd>I'm on the fence with ranges. Source [^2] says with Full payload = 3700 km (1998 nm) and Full fuel 9500 km (5130 nm). Source [^3] says with Full payload = 5000 km (2700 nm) and Full fuel 11 000 km (5940 nm). I trust source [^2] more, it's a long difference, though. </kbd>

```
COPY DataLoadout.ID=9865;
SET DataLoadout.ID='Paratroopers, 151x', DataLoadout.Capacity=151, DataLoadout.LoadoutRole=7101, DataLoadout.DefaultMissionProfile=8002, DataLoadout.Cargo_Type=1000,DataLoadout.Cargo_Mass=0.0, DataLoadout.Cargo_Area=0.0, DataLoadout.Crew=151.0
```
```
COPY ((DataLoadout.ID)=9862);
SET DataLoadout.ID='Troops, 292x', DataLoadout.Capacity=292, DataLoadout.LoadoutRole=7102, DataLoadout.DefaultMissionProfile=8003, DataLoadout.Cargo_Type=1000,DataLoadout.Cargo_Mass=0.0, DataLoadout.Cargo_Area=0.0, DataLoadout.Crew=292.0
```
---
**DataAircraftMounts**[^2][^3] DELETE
```
DELETE FROM DataAircraftMounts
WHERE DataAircraftMounts.ID IN (2509, 2510, 2511, 2512);
```
<kbd>There's no defensive 23 mm tail gun on that aircraft. The only known armament would be flare bombs.</kbd>
---
**DataAircraftSensors**[^2][^3] DELETE
```
DELETE FROM DataAircraftSensors
WHERE DataAircraftSensors.ID IN (2509, 2510, 2511, 2512) AND DataAircraftSensors.ComponentID=4227;
```
<kbd>Nor there's a Generic Tail Gun Director [TV Camera]</kbd>
---

_Note :  please let me know if formatting the request in quasi SQL actually help. When i'll be done with course, I'll post proper SQL request ^^_

### Sources

[^1]: [Review and Editing of Unit Descriptions - Page 7 - Matrix Games Forums](https://www.matrixgames.com/forums/viewtopic.php?p=4990284#p4990284)
[^2]: Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
[^3]: Gordon, E., Komissarov, S., & Komissarov, D. (2004). Antonov's heavy transports: The An-22, An-124/225, and An-70. Hinckley: Midland.
[^4]: Kaminski-Morrow, D. (5 April 2022). An-22 among several Antonov aircraft damaged during Gostomel combat. Flight Global.
[^5]: Taghvaee, B. (27th December, 2018). An-22 in the war on terror. AIR International Magazine.
[^6]: [Sky Pacific Air Services – Antonov brochure](https://www.skypac.co.th/wp-content/uploads/2022/03/Antonov_Spec-1.pdf)(PDF)
[^7]:[[ANTONOV gliders and airplanes - AN−22](https://web.archive.org/web/20120731031317/http://www.antonov.com/aircraft/antonov-gliders-and-airplanes)

**Comment by PygmalionOfCyprus** [comment]
I actually don't usually use SQL to directly interface with the DB, so if you just dump a list of DBIDs and the datapoints/values to which you want them changed that will fit better into my workflow.

**Comment by claudejdev** [comment]
Oh dang! 😃
Well, here or maybe in the FAQ, if you could post an example of how you
would yourself fill your ideal report, that could clarify things once for
all.
Just trying to make it as smooth and efficient as possible here.
Thanks for interacting so openly by the way Ethan. It's not always a given.
Cheers

Le lun. 25 avr. 2022 à 07:03, Ethan Hermanson ***@***.***> a
écrit :

**Comment by PygmalionOfCyprus** [comment]
Fixed 494.

I actually had a grand old time using your SQL for the DataAircraft edits. It's only once it starts to get into loadouts, components (mounts, sensors, etc.), etc. that the SQL begins to break down -- the DB is ridiculously complex and it's honestly just easier to use Access queries rather than SQL for those since you otherwise have to INNER JOIN the whole damn DB together before you can do anything.

**Comment by PygmalionOfCyprus** [comment]
>Thanks for interacting so openly by the way Ethan. It's not always a given.

This is the only time they let me out of the DB dungeon.

**Comment by claudejdev** [comment]
Just to mention that source number 2 actually is "Butowski, P. (2016). Russia's warplanes: Russian-made military aircraft and helicopters today. Volume 2.", not "Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.". Obviously.
