### ISSUE TITLE
An-22 Antey, Commercial

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#987]
### DB Selector

DB3K

### DBID to Copy

2511 | An-22A Cock (Russia [1992-] - 1992), see #986 

### Hypothetical

No

### Name

An-22 Antey

### Country

1102

### Service

9002

### In Commission

1994

### Loadout Options

No Paratrooper loadout, nor Airdrop.

### Sources

Lore : 
> After the breakup of the Soviet Union, 1 An-22A, converted to a civilian cargo aircraft, was operated by Antonov Airlines, the aeronautical division of Antonov Design Bureau. From June 1994, it was registered in Ukraine as UR- 09307 and used for carrying heavy and large cargos for civil and military customers across the world. That last operating Ukrainian machine was apparently damaged during the so dubbed Battle of Antonov Airport with Russian forces at Gostomel airport, in February 2022.

- Kaminski-Morrow, D. (5 April 2022). An-22 among several Antonov aircraft damaged during Gostomel combat. Flight Global.
- Taghvaee, B. (27th December, 2018). An-22 in the war on terror. AIR International Magazine.

For Steve and Dwight :
<details><summary>Description</summary>
<p>
OVERVIEW: The An-22 Antaeus, NATO nickname COCK, is a heavy transport aircraft and the largest turboprop aircraft built. Resembling a scaled up An-12 CUB, the An-22 could conduct paratroop operations with a rear ramp and operate off of austere airstrips.

DETAILS: The An-22 falls between the Il-76 and the An-124 in terms of transport capacity. Designed to operate from short semi-prepared runways, this aircraft has adjustable landing gear and massive flaps to control airspeed. The cargo hold is 33 m (ca. 108 feet) long, ramp included, and equipped with travelling cranes. It can accommodate 4 BMD-1 airborne combat vehicles. There is also a pressurized compartment for 29 passengers.

NOTES: Developed by Antonov Design Bureau in Kiev, Ukraine, series manufacture was undertaken in Tashkent, Uzbekistan. First flew in February 1965, at the time the world's heaviest aircraft. Two months later, it was exhibited at the Paris Air Show. It became operational in January 1969, breaking several world records for payload and flight. There were 68 built from 1966 to 1976, including 2 prototypes, 38 An-22 and 28 An-22A. That variant changed installations, mainly the fuel system, thus fixing issues that caused numerous crashes with the early airframes, and improved equipment. They have seen extensive service, first for the Soviet Union, flying military support to Afghanistan, Algeria, Angola, Ethiopia, India, Syria Vietnam and other countries between 1970 and 1989. In 1971, they carried rescue equipment to Peru, after the country was hit by an earthquake. In Russian service, it evacuated personnel and equipment from former Soviet airbases, and supported the campaign in Chechnya. By the year 2000, 26 An-22 remained in Russian service, with only 9 airworthy. Fifteen years later, in 2015, 5 were still in service, with 6 being preserved.
After the breakup of the Soviet Union, 1 airframe, converted to a civilian cargo aircraft, was operated by Antonov Airlines, the aeronautical division of Antonov Design Bureau. From June 1994, it was registered in Ukraine as UR- 09307 and used for carrying heavy and large cargos for civil and military customers across the world. That last operating Ukrainian machine was apparently damaged during the so dubbed Battle of Antonov Airport with Russian forces at Gostomel airport, in February 2022.  

SOURCES:
Butowski, P. (2017). Russia's air-launched weapons: Russian-made aircraft ordnance today.
Gordon, E., Komissarov, S., & Komissarov, D. (2004). Antonov's heavy transports: The An-22, An-124/225, and An-70. Hinckley: Midland.
Kaminski-Morrow, D. (5 April 2022). An-22 among several Antonov aircraft damaged during Gostomel combat. Flight Global.
Taghvaee, B. (27th December, 2018). An-22 in the war on terror. AIR International Magazine
</p>
</details>
<details><summary>Picture</summary>
<p>

![image](https://user-images.githubusercontent.com/35732829/165012125-9c4f4888-6c60-4a78-86a5-ce9e2a17bc0e.png)
https://commons.wikimedia.org/wiki/File:Antonov_An-22_in_new_livery_at_Kyiv_Sviatoshyn_Airfield.jpg
![image](https://user-images.githubusercontent.com/35732829/165012151-96a8ed72-4d6c-4ff6-b02b-ccda2236bf21.png)
https://commons.wikimedia.org/wiki/File:Antonov_An-22_1.jpg

</p>
</details>

**Comment by PygmalionOfCyprus** [comment]
Added 494.

Also, fun fact: the DB editor actually has enums linked up directly to the DataX tables. So, unless I get into the weeds with it (e.g. running queries), the front-end UI has us working with string "values" instead of the enum's integer "keys."

For single entries like this where I'm not manipulating multiple datapoints at once, it's easier if you just write "Commercial," etc. rather than "1102," etc.

A tiny snippet of the form view to illustrate:
<img width="1016" alt="Screen Shot 2022-04-26 at 15 34 24" src="https://user-images.githubusercontent.com/87087226/165236739-dd05e319-abb7-4206-b7d9-245d56db73ac.png">

(This doesn't apply for the mass-edit stuff you usually post -- those get handled with queries, and queries conversely are a lot easier with numbers.)

**Comment by claudejdev** [comment]
Roger that.
I think I saw a screenshot of that interface on the Dev's blog. I wasn't sure what you guys are using nowadays.

**Comment by PygmalionOfCyprus** [comment]
We don't always use that particular view (in fact I often prefer to just crunch through things spreadsheet-style), but its a good illustration of the higher "level" at which we can view/manipulate the data vs. a pure enum dump like you might get from an external DB viewer.
