### ISSUE TITLE
Add Chinese PHL-16 [PCH-191] MRLS

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#988]
### DB Selector

DB3K

### Hypothetical

No

### Name

PHL-16 [PCH-191] MRLS

### Facility Type

Arty

### Country

China

### Service

PLAGF

### In Commission

2019

### Crew

5

### Dispersion Radius (m)

40

### Sensors

none

### Mounts

TEL Is 12m x 3m x 3m and 45tons
Seems to have different rocket configurations but only types seen. 
6 8-Tube TELS eight 370mm rockets, each with a range of 350km. (can hit Taiwan)

- BRE6/FD220: 220 km range, 30m CEP

12-Tube same as #300mm. 

- Same config and ammo as #3126

### Sources

https://twitter.com/jesusfroman/status/1459449426091651079
http://www.military-today.com/artillery/phl_16.htm
https://en.wikipedia.org/wiki/PHL-16
https://chanakyaforum.com/china-deploys-long-range-rockets/

300mm Rocket Config
https://youtu.be/Bnr2Om9-9OQ?t=108
https://twitter.com/ImperialLuis1/status/1447808334468419587/photo/2

370mm Rocket
BRE6/FD220: 220 km range, 30m [CEP](https://en.wikipedia.org/wiki/Circular_error_probable)
https://i.insider.com/5df05096fd9db27b2a6c6092?width=1136&format=jpeg

**Comment by bostonmyk** [comment]
https://twitter.com/isekaimint/status/1550821236774780928
https://militaryleak.com/2022/07/23/china-tests-new-pcl191-multiple-launch-rocket-system-near-disputed-border-with-india/

**Comment by PygmalionOfCyprus** [comment]
Handled 507.
