### ISSUE TITLE
Copy K-9 Thunder 155mm for India, Norway, Finland, and Estonia

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#989]
### DB Selector

DB3K

### DBID to Copy

Facility 2196

### Hypothetical

No

### Name

Arty Bty (Vajra-T[155mm/52 K-9 Thunder]),Arty Bty (Moukari[155mm/52 K-9 Thunder]),Arty Bty (Vidar[155mm/52 K-9A1 Thunder]),

### Country

India, Finland, Norway and Estonia

### Service

Army

### In Commission

see below

### Other Changes

India designates K-9 Vajra-T and receive by 2018. 
Finland designates K-9 Moukari and received 2018. 
Norway designates as Vidar 2019 
Estonia designate as Kou and receive by 2020

Egypt and Australia bought K-10 version with delivery completion dates ~2025

### Sources

Sipri Lines
**India**	100	K-9 Thunder 155mm	self-propelled gun	2017	2018-2021	(100)	INR44 b ($646-700 m) deal; incl production under licence in India; K-9 Vajra-T version; probably option on 50 more
**Estonia**	18	K-9 Thunder 155mm	self-propelled gun	2018	2020-2021	(6)	EUR83 m deal; Estonian designation Kou; delivery planned 2020-2023
**Finland**	48	K-9 Thunder 155mm	self-propelled gun	2017	2018-2021	(24)	Second-hand; EUR146 m deal; delivery planned 2018-2024
     		(10)	K-9 Thunder 155mm	self-propelled gun	(2021)			Second-hand
**Norway**       24	K-9 Thunder 155mm	self-propelled gun	2017	2019-2021	24	$383 m deal; option on 24 more; Norwegian designation Vidar

India
https://twitter.com/L_Team10/status/1429428976943050756
https://twitter.com/PKRoyIAF/status/1362965000055263235/photo/1
https://www.hindustantimes.com/india-news/indian-army-deploys-k9-vajra-howitzer-regiment-along-lac-know-all-about-the-gun-101633166922888.html
https://thediplomat.com/2020/01/indias-army-takes-delivery-of-new-k-9-howitzers-ahead-of-schedule/

Finland
https://twitter.com/r116440/status/1462407538276589568
https://defbrief.com/2021/10/22/finland-exercises-options-for-additional-k9-howitzers/
https://www.armyrecognition.com/defense_news_october_2021_global_security_army_industry/finnish_army_to_use_option_for_5_additional_k9_155_mm_self-propelled_howitzers.html

Norway
https://militaryleak.com/2019/12/26/norway-k9-vidar-self-propelled-howtitzer/
https://www.youtube.com/watch?v=VyBE9YfhbGk

Estonia
https://militaryleak.com/2020/10/12/estonia-receives-south-korean-k9-thunder-self-propelled-howitzers/

General
https://en.wikipedia.org/wiki/K9_Thunder

**Comment by PygmalionOfCyprus** [comment]
Added 494.
