### ISSUE TITLE
Add RAF F-35A (Hypothetical) 

### ISSUE THREAD

**Issue by TempestII** [PygmalionOfCyprus/cmo-db-requests#99]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

F-35A Lightning II

### Country

UK

### Service

RAF

### In Commission

2018+

### Length (m)

15.67

### Wingspan (m)

10.7

### Height (m)

4.33

### Empty Weight (kg)

13300

### Maximum Takeoff Weight (MTOW) (kg)

31800

### Payload Weight (kg)

6810

### Crew

1

### Propulsion

F135PW-100

### Rate of Climb (ft/min)

32610

### Service Ceiling (ft)

50000+

### Military/Afterburner Speed (kt)

1066

### Cruise Speed (kt)

480

### Supercruise

No

### Ferry Range (nm)

2400

### Endurance (min)

Same as USAF F-35A

### Takeoff / Landing Distance (m)

Same as USAF F-35A

### Fuel Capacity (kg)

8375

### Sensors

Same as UK F-35B.

### Mounts

1x 25mm GAU-22A internal cannon
Otherwise, same as UK F-35B minus the external gunpod.

### Loadout Options

Same as UK F-35B, minus gunpods. However, a hypothetical option for x6 Meteor AAMs could be added with "Sidekick" in the future. 

### Comms/Datalinks

Same as UK F-35B.

### Aircraft Codes

Terrain Avoidance, Terrain Following, Fly-by-Wire, Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Navigation (INS/GPS), Helmet Mounted Sight / Display (HMS/HMD), Probe Refuelling

### Comments

"Could you see the U.K. shifting from buying the “B” model to the conventional “A” model?

Yes. It’s been a live topic over the years in the United Kingdom, and to that, I also say: “Never say never.” But that’s a decision for the future, and that’s something that perhaps my successor will come back to."

### Sources

https://www.defensenews.com/interviews/2021/05/09/britains-royal-air-force-chief-talks-f-35-tally-and-divesting-equipment/

**Comment by KushanGaming** [comment]
Done for DB495
