### ISSUE TITLE
Yugoslavia - Jak-40EiPED Electronic Warfare Aircraft (Aries-A)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#990]
### DB Selector

DB3K

### Baseline

1267 - PD.808GE2 (Italy)

### Hypothetical

No

### Name

Jak-40EiPED

### Country

Yugoslavia

### Service

Airforce

### In Commission

1990-1999 (used by Serbia[1992-])

### Length (m)

20.4

### Wingspan (m)

25.0

### Height (m)

6.5

### Empty Weight (kg)

9400

### Maximum Takeoff Weight (MTOW) (kg)

16100

### Payload Weight (kg)

2700

### Crew

6

### Propulsion

3x AI-25, 3 x 14,7 kN

### Service Ceiling (ft)

26000

### Military/Afterburner Speed (kt)

430

### Cruise Speed (kt)

400

### Supercruise

No

### Ferry Range (nm)

972

### Fuel Capacity (kg)

4430

### Sensors

1x Mk1 Eyeball
1x Generic Weather Radar
1x Aries-A [ELINT]
1x Aries-A [Smart Guard COMINT]
1x Aries-A [ECM]
1x Aries-A [Fast Jam Communications Jammer]

### Mounts

unarmed

### Loadout Options

ELINT (Area Surveillance)
Offensive ECM

### Comms/Datalinks

UHF/VHF Radio [Unsecure]
HF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

The Yugoslav Jak-40EiPED electronic warfare aircraft uses the same EW suite that is used by the Italian PD.808GE2 EW aircraft. The acronym EiPED means: Elektronsko Izvidjanje i Protivelektronska Dejstva (roughly: Electronic Reconnaissance and Jamming). EiPED was the official designation of all EW units and this aircraft. One was put into service in 1990 and was used throughout the wars until 1999 with over 270 flight hours doing combat missions, disrupting enemy communications and conducting COMINT and ELINT.

### Sources

Pictures:
https://www.mycity-military.com/slika.php?slika=476830_182292573_1127144.jpg
https://www.mycity-military.com/slika.php?slika=476830_149148416_Jak-40E_01.jpg
https://www.mycity-military.com/slika.php?slika=111943_51948847_144625_51704808_29.572.jpg
(best picture I could find where it is in good shape, for the DB image):
https://imgur.com/1o8syob

Jak-40 Aircraft Specifications:
https://www.airlines-inform.com/commercial-aircraft/yak-40.html
http://www.flugzeuginfo.net/acdata_php/acdata_yak40_en.php

Aries listed in the Electronic Warfare Directory of 1990 as suitable for use by the Jak-40:
https://www.mycity-military.com/slika.php?slika=476830_82034693_79915967-EW-Directory-1990-004.jpg

Jak-40EiPED sources (Czech and Serbian):
https://ruslet-webnode-cz.translate.goog/technika/ruska-technika/letecka-technika/a-s-jakovlev/jak-40e/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=sc

(first post, talks about electronic warfare helicopter aswell):
https://www.mycity-military.com/Vazduhoplovno-naoruzanje-i-oprema/HT-40-PED-Aries-F-i-Jak-40-EI-Aries-A.html

(post by dinja):
https://www.mycity-military.com/Vazduhoplovno-naoruzanje-i-oprema/HT-40-PED-Aries-F-i-Jak-40-EI-Aries-A_5.html

**Comment by PygmalionOfCyprus** [comment]
Added 494 (as "Yak-40 EiPED"). Brought the Yak-40 over from CWDB for this one.
