### ISSUE TITLE
Yugoslavia - HT-40EiPED (Mi-8T/EiPED) Electronic Warfare Helicopter (Aries-F)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#991]
### DB Selector

DB3K

### Baseline

1416 Mi-8T Hip C

### Hypothetical

No

### Name

HT-40EiPED or Mi-8T/EiPED

### Country

Yugoslavia

### Service

Airforce

### In Commission

1989-1991

### Length (m)

18.2

### Wingspan (m)

5.7

### Height (m)

5.7

### Empty Weight (kg)

7160

### Maximum Takeoff Weight (MTOW) (kg)

12000

### Crew

5

### Propulsion

2x TV2-117A

### Rate of Climb (ft/min)

720

### Service Ceiling (ft)

16000

### Military/Afterburner Speed (kt)

135

### Cruise Speed (kt)

130

### Supercruise

No

### Ferry Range (nm)

305

### Fuel Capacity (kg)

1495

### Sensors

1x ARIES-F [ECM]
1x ARIES-F [ELINT]
1x Mk1 Eyeball

### Mounts

unarmed

### Loadout Options

ELINT (Area Surveillance)
Offensive ECM (Offensive ECM)

### Comms/Datalinks

UHF/VHF Radio [Unsecure]

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Four HT-40EiPED (Mi-8T/EiPED) electronic warfare helicopters were put into service by the Yugoslav Airforce in 1990. The helicopters were modified at the Moma Stanojlovic Aeronautical Plant in Yugoslavia in a cooperation by the Italian Elettronica SpA and Yugoslav Imtel Institute. These helicopters were used during the 90s and were operational until 2004. In the Yugoslav and Serbian Airforces Mi-8T are designated as HT-40.

This helicopter is equiped with an Italian Aries-F EW suite. It is equiped with nine antennas. Two directional transmitting antennas are located behind a rectangular dielectric cover above the cockpit. They are used for 1-4GHz (D,E,F-band) jamming in flight direction. Omnidirectional antennas for (D,E,F-band) jamming are mounted on racks to the left and right, each carrying an antenna pair. Omnidirectional transmitting and receiving antennas are located below the cockpit infront of the landing gear. They operate at 3,9-18GHz (G,H,I,J-band). The Aries-F system would thus be identical in function to the Aries-A [ECM] and [ELINT] system operating in D,E,F,G,H,I,J-bands.

### Sources

Sources (Czech and Serbian):
https://ruslet.webnode.cz/technika/ruska-technika/letecka-technika/m-l-mil/ht-40e/
(first post):
https://www.mycity-military.com/Vazduhoplovno-naoruzanje-i-oprema/HT-40-PED-Aries-F-i-Jak-40-EI-Aries-A.html
https://tangosix.rs/2013/01/07/mi-8-45-godina-u-sluzbi/
(page 23):
http://elektron.tmf.bg.ac.rs/bojan/JNA%20OOB%20new.pdf

https://www.mycity-military.com/imgs4/71011_803871723_2%20JRV%20Mi-8T%20EiPED.png
https://www.mycity.rs/imgs/76133_59817385_HT-40%20PED%20u%20letu.jpg
https://www.mycity.rs/imgs/76133_299087145_HT-40%20za%20elektronska%20dejstva.jpg
https://www.mycity.rs/imgs/76133_49847829_Mi-8%20HT-40%20PED.jpg
https://www.mycity.rs/imgs/76133_62965720_HT-40%20Aries-F.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 494.

For future reference and to save you time/energy, you can use the "copy" form instead of the "addition" form when requesting aircraft that are structurally identical to existing DB entries. (See the FAQs on the Discussions page for more detail about what makes a "copy.")
