### ISSUE TITLE
Aries-F [ECM] and Aries-F [ELINT] (identical to Aries-A EW system)

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#992]
### DB Selector

DB3K

### DBID to Copy

821 and 2039

### Hypothetical

No

### Name

Aries-F [ECM] and Aries-F [ELINT]

### Country

-

### Service

-

### Other Changes

The Italian Aries-F EW suite consists of nine antennas. Two directional transmitting antennas are located behind a rectangular dielectric cover above the cockpit. They are used for 1-4GHz (D,E,F-band) jamming in flight direction. Omnidirectional antennas for (D,E,F-band) jamming are mounted on racks to the left and right, each carrying an antenna pair. Omnidirectional transmitting and receiving antennas are located below the cockpit infront of the landing gear. They operate at 3,9-18GHz (G,H,I,J-band). The Aries-F system would thus be identical in function to the Aries-A [ECM] and [ELINT] system operating in D,E,F,G,H,I,J-bands.

### Sources

Sources (Czech and Serbian):
https://ruslet.webnode.cz/technika/ruska-technika/letecka-technika/m-l-mil/ht-40e/
(first post):
https://www.mycity-military.com/Vazduhoplovno-naoruzanje-i-oprema/HT-40-PED-Aries-F-i-Jak-40-EI-Aries-A.html

Aries-A Electronic Warfare Directory 1990:
https://www.mycity-military.com/imgs4/476830_82034693_79915967-EW-Directory-1990-004.jpg

https://www.mycity.rs/imgs/76133_59817385_HT-40%20PED%20u%20letu.jpg

**Comment by PygmalionOfCyprus** [comment]
Added 494.
