### ISSUE TITLE
Update JF-17A/B Thunder Blk 3 PL-15E Missile Datalink Channels

### ISSUE THREAD

**Issue by ywturbo** [PygmalionOfCyprus/cmo-db-requests#993]
### DB Selector

DB3K

### Affected DBID(s)

4827,4828

### Summary of Changes

Update PL-15E datalink channels from 1 to 12 (?)  for both Pakistani JF-17A/B Thunder Blk 3 aircrafts.

### Sources

The Pakistani JF-17A/B Thunder Blk 3 have already equiped with PL-15E missile, but both with only one PL-15E missile datalink channel, probably against common sense. By contrast, they have 12 AA-10/12 command datalink channels. Therefore the PL-15E datalink channel seems to be updated to 12 for both aircrafts, although there's no public source.

**Comment by KLABDB3K** [comment]
This may have already been fixed for Db494? #73

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.
