### ISSUE TITLE
Add Iraqi AN/TWQ-1 Avenger x8

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#995]
### DB Selector

DB3K

### DBID to Copy

#286

### Hypothetical

No

### Name

SAM Sec (Avenger)

### Country

Iraq

### Service

Army

### In Commission

2014

### Sensors

MPQ-64 Sentinel

### Sources

https://twitter.com/FarooqB90714421/status/1405839981826949122
https://twitter.com/klkamashiq/status/898233562041905154

Sipri Lines
8	Avenger	Mobile AD system	(2012)	2013-2014	(8)	Part of $105 m deal; 'ISFF' aid

**Comment by PygmalionOfCyprus** [comment]
Added 494.
