### ISSUE TITLE
Add Iraqi SA-24 Igla-S 2016

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#996]
### DB Selector

DB3K

### DBID to Copy

3172

### Hypothetical

No

### Name

SAM Sec ( SA-24 Grouse[9K-338 Igla-S]MANPADS X 3)

### Country

Iraq

### Service

Army

### In Commission

2016

### Mounts

2 types
Standard Manpad
Dzhigit vehicle-mounted launchers on a Chevy pickup (so mobile vehicle unit type)

### Sources

https://twitter.com/ralee85/status/1236718272109740032
https://twitter.com/missilito/status/516996734862761986?lang=he
https://twitter.com/missilito/status/516996734862761986?lang=he

Sipri Lines
(500)	Igla-S	portable SAM	(2012)	2014-2016	(500)	For portable and Dzhigit vehicle-mounted launchers

**Comment by PygmalionOfCyprus** [comment]
Added 494.
