### ISSUE TITLE
Correction to Sensor_2746   SPIN SCAN [RP-21M] radar

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#997]
DB Selector
DB3K, CWDB

Affected DBID(s)
Sensor_2746 (DB3k)
Sensor_272 (CWDB)

Summary of Changes
The RP-21M is given a max range of 16nm.  This is too large. According to Jane's "Radar and Electronic Warfare Systems 2001-02" (screenshot attached) the RP-21M had a max range of 20 km (10.7nm) against 16m2 (bomber) sized targets. This appears confirmed by a translated technical manual for the RP-21 (see source below) and Mladenov (source below)

Source
https://sites.google.com/site/sovietaircrafttech/mig-21/rp-21-sapfir-manual/1-2-specifications
Mladenov, Alexander. Mikoyan-Gurevich MiG-21 (Air Vanguard)(Kindle ed., pg. 44-45) 
Jane's "Radar and Electronic Warfare Systems 2001-02"
![2022-04-26_14-45-06](https://user-images.githubusercontent.com/99547401/165380296-c037b1e3-28a3-453d-afec-56caefedeaf4.jpg)

**Comment by PygmalionOfCyprus** [comment]
Fixed for 494.

Also inspired a future schema change with big consequences for Cold War radars. For 495, maybe...

**Comment by CV60LCC19** [comment]
Is it anything that would change my research into the database entries?  You have me curious what type of schema change you are considering.  Possibly between LD/SD radars and non-LD/SD radars?

**Comment by PygmalionOfCyprus** [comment]
Sort of. We already model LD/SD vs LD/SD with sensor codes; you can select those that apply in the "Sensor Codes" section of the New Sensor Request form.

I want to add fidelity to our sensor arc modeling. Currently we indicate arcs using a 16-point circle, limiting my ability to reflect, say, a 60deg arc: if I want to build a cone (which obviously I almost always do) I have to make it 44deg, 88 deg, etc. A manual override to that system allowing for an inputted degree value (e.g., "60deg") would be ideal in cases where exact data is available.

I also want to extend that to _vertical_ scan, which is currently handled completely sim-side. Being able to limit the RP-21 to its 20deg vertical arc, for example, will have big effects for players setting up CAPs, etc. You'll have to consider multiple-altitude CAPs (LOCAP, HICAP, etc.) in older scenarios just like mission planners of that era IRL.

**Comment by CV60LCC19** [comment]
K. I’ll try to dig out that info as I go through the aircraft sensors 

Sincerely,
Steve Lohr
