### ISSUE TITLE
Yugoslavia - Grom missile

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#999]
### DB Selector

DB3K

### DBID to Copy

218 AS-7 Kerry

### Hypothetical

No

### Name

Grom

### Country

Yugoslavia

### Service

Airforce

### Sensors

Grom Missile Datalink

### Mounts

-

### Loadout Options

-

### Other Changes

Range: 1-6 NM
needs also a datalink pod

### Sources

specs:
300mm diameter, 3.33m length, 330kg mass, 0.8m wingspan, 104kg warhead HEAT/FRAG, 12km range, up to 6km launch alt
https://www.mycity-military.com/slika.php?slika=65178_47803018_G4%20grom.JPG

https://imgur.com/LTqAXih
https://imgur.com/xudSkDp
https://www.youtube.com/watch?v=sUNktVwhVd4
Grom and Datalink Pod:
https://imgur.com/krOZhM2

**Comment by PygmalionOfCyprus** [comment]
Since these are domestic weapons and not direct copies of their US equivalents (AFAIK) it would probably be better to post a proper weapon request here so you can include all those specs in the designated places.

**Comment by PygmalionOfCyprus** [comment]
Wait, isn't this already in the DB? How does the Yugoslavian Grom differ from the normal Kh-23?

**Comment by nuk92** [comment]
You are right. I thought the AS-7 has probably less range in the DB entry because it is the Kh-23 instead of the improved Kh-23M. But either way despite being called a copy the Grom is actually a local development which was based on the Kh-23M. The specs barely differ but the design, the physical appearance differs from the Kh-23M like the position of the rocket motors and state of the art rocket nozzles and heat warhead. The development of the Grom started in the late 70s. It was planed to be finished by 1985, but the development took longer than anticipated. There was still testing beeing done by the late 80s and it was never formally put into service by the Yugoslav airforce despite it being used in the wars of the 90s with over 50 launched. More than a hundred were made in the 80s. By the time Yugoslavia broke apart there were still improvements being planed like increased range and a TV seeker but the Grom-B is a different story that wasn't even finished.

But the main difference in the game would be that Grom requires a Datalink pod which is carried on one of the inner pylons since the J-22 Orao has no integrated datalink.

https://www.mycity-military.com/imgs4/123381_57600679_Grom.jpg
https://www.mycity-military.com/slika.php?slika=52022_436442343_Kh-23M-MiroslavGyurosi-1S.jpg

**Comment by nuk92** [comment]
Would the Datalink pod require a separate request?
It would basically be the AS-7 datalink inside a Pod called Grom Datalink Pod:
Name: Grom Command Datalink, Type: Grom Weapon Link, Send-only

Left page:
https://www.vojnaknjizara.com/wp-content/uploads/2017/03/4.jpg

**Comment by PygmalionOfCyprus** [comment]
Got it. No need for a separate request.

I'll create a Yugoslavian version of the Grom to reflect those differences.

**Comment by PygmalionOfCyprus** [comment]
Added 494.
